### ISSUE TITLE
[Bug]:  electron 12.0.0 crash silently irregularity

### ISSUE THREAD

**Issue by xland** [electron/electron#28292] opened 2021-03-19 12:27 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

ia32

### Last Known Working Electron version

unknown

### Expected Behavior

doesn't crash

### Actual Behavior

crash silently frequently

dump file opend by  visual studio
```
errorcode:  0xC0000005
errorinfo:  该线程尝试读写某个虚拟地址，而它对该地址不具有相应的访问权限 (translate：The thread is trying to read and write to a virtual address that it does not have access to)
Heap information:  inexistence
```

dump file opened by WinDBG
```

Microsoft (R) Windows Debugger Version 10.0.17763.132 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Users\liuxiaolun\Downloads\Crashpad\reports\7d286649-80c7-4997-b5d0-03f533215108.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             D:\project\symbols\electron-v12.0.0-win32-x64-symbols\breakpad_symbols
Symbol search path is: D:\project\symbols\electron-v12.0.0-win32-x64-symbols\breakpad_symbols
Executable search path is: 
Windows 7 Version 7601 (24545) MP (2 procs) Free x64
Product: WinNt
Windows NT 6.1.7601.24545
Machine Name:
Debug session time: Thu Mar 18 11:28:10.000 2021 (UTC + 8:00)
System Uptime: not available
Process Uptime: 0 days 17:12:02.000
................................................................
.........................................................
Loading unloaded module list
...
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(8c54.84e4): Access violation - code c0000005 (first/second chance not available)
*** WARNING: Unable to verify timestamp for ntdll.dll
*** ERROR: Module load completed but symbols could not be loaded for ntdll.dll
*** WARNING: Unable to verify timestamp for KERNELBASE.dll
*** ERROR: Module load completed but symbols could not be loaded for KERNELBASE.dll
ntdll+0x69aea:
00000000`776c9aea c3              ret
0:034> .ecxr.
rax=0000000022f64bf0 rbx=0000000000000000 rcx=000000001b2603e8
rdx=0000000023b2f618 rsi=0000000023b2f618 rdi=000000001b2603e8
rip=0000000000000000 rsp=0000000023b2f5a8 rbp=0000000023b2f750
 r8=000000000000037f  r9=feeefeeefeeefeee r10=00000000008c0158
r11=0000000023b2f590 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei pl zr na po nc
cs=0033  ss=0000  ds=0000  es=0000  fs=0053  gs=002b             efl=00010246
00000000`00000000 ??              ???
            ^ Extra character error in '.ecxr.'
```

**Comment by codebytere** [comment] 2021-03-22 10:56
Duplicate of https://github.com/electron/electron/issues/25937

**Closed by codebytere** 2021-03-22 10:56 UTC
Labels: bug :beetle:
