### ISSUE TITLE
i want to control autoUpdater why i canot contron when i want the update or not

### ISSUE THREAD

**Issue by George35mk** [electron/electron#8920] opened 2017-03-14 13:49 UTC
* Electron version: 1.6.2
* Operating system: 10

### How to reproduce

http://stackoverflow.com/questions/42786393/how-to-set-option-to-electron-app-when-to-install-the-updates-if-the-user-want

**Comment by MarshallOfSound** [comment] 2017-03-14 14:08
This is how Squirrel works and unfortunately there is nothing you can do to change this behavior.  It is how Squirrel was designed to work (silent, no user hassle updates)

**Comment by George35mk** [comment] 2017-03-14 14:11
Marshall if the download start is ok if finish is ok the problem is i dont want the app to close in the midle and i want a buttton that say ok we have update avaliable you want to install and if this is not imposible what choises i have??

**Comment by George35mk** [comment] 2017-03-14 14:11
atom and vscode are using electron how they are make that??

**Comment by MarshallOfSound** [comment] 2017-03-14 14:13
@George35mk The app should not restart automatically, if it does can you provide the code that causes the issue.  The app will only restart when you call `autoUpdater.quitAndUpdate()`

**Comment by George35mk** [comment] 2017-03-14 14:17
ok if i delete that line `autoUpdater.quitAndInstall()`  and the app dont close if?? is gona open the app next time the setup is gona start again ??

**Comment by George35mk** [comment] 2017-03-14 14:19
i have this code for updating 

 `const {app, BrowserWindow, Menu, protocol, ipcMain} = require('electron');
 const log = require('electron-log');
 const {autoUpdater} = require("electron-updater");

//-------------------------------------------------------------------
// Logging
//
// THIS SECTION IS NOT REQUIRED
//
// This logging setup is not required for auto-updates to work,
// but it sure makes debugging easier :)
//-------------------------------------------------------------------
autoUpdater.logger = log;
autoUpdater.logger.transports.file.level = 'info';
log.info('App starting...');



//-------------------------------------------------------------------
// Open a window that displays the version
//
// THIS SECTION IS NOT REQUIRED
//
// This isn't required for auto-updates to work, but it's easier
// for the app to show a window than to have to click "About" to see
// that updates are working.
//-------------------------------------------------------------------
let win;

function sendStatusToWindow(text) {
  log.info(text);
  win.webContents.send('message', text);
}

function createDefaultWindow() {
  win = new BrowserWindow({
    width:800,
    height: 500,
    minWidth: 600,
    minHeight: 400,
    // 'auto-hide-menu-bar': true,
    center: true
  });
  // win.webContents.openDevTools();
  win.on('closed', () => {
    win = null;
  });
  win.loadURL(`file://${__dirname}/index.html#v${app.getVersion()}`);
  console.log(app.getVersion());
  // win.loadURL(`file://${__dirname}/index.html`);
  // win.webContents.openDevTools();
  return win;
}



autoUpdater.on('checking-for-update', () => {
  sendStatusToWindow('Checking for update...');
})
autoUpdater.on('update-available', (ev, info) => {
  sendStatusToWindow('Update available.');
})
autoUpdater.on('update-not-available', (ev, info) => {
  sendStatusToWindow('Update not available.');
})
autoUpdater.on('error', (ev, err) => {
  sendStatusToWindow('Error in auto-updater.');
})
autoUpdater.on('download-progress', (ev, progressObj) => {
  sendStatusToWindow('Download progress...');
})
autoUpdater.on('update-downloaded', (ev, info) => {
  sendStatusToWindow('Update downloaded; will install in 5 seconds');
});


app.on('ready', function() {
  // Create the Menu
  // const menu = Menu.buildFromTemplate(template);
  // Menu.setApplicationMenu(menu);

  createDefaultWindow();
});
app.on('window-all-closed', () => {
  app.quit();
});

//-------------------------------------------------------------------
// Auto updates
//
// For details about these events, see the Wiki:
// https://github.com/electron-userland/electron-builder/wiki/Auto-Update#events
//
// The app doesn't need to listen to any events except `update-downloaded`
//
// Uncomment any of the below events to listen for them.  Also,
// look in the previous section to see them being used.
//-------------------------------------------------------------------
// autoUpdater.on('checking-for-update', () => {
// })
// autoUpdater.on('update-available', (ev, info) => {
// })
// autoUpdater.on('update-not-available', (ev, info) => {
// })
// autoUpdater.on('error', (ev, err) => {
// })
// autoUpdater.on('download-progress', (ev, progressObj) => {
// })



autoUpdater.on('update-downloaded', (ev, info) => {
  // Wait 5 seconds, then quit and install
  // In your application, you don't need to wait 5 seconds.
  // You could call autoUpdater.quitAndInstall(); immediately
  setTimeout(function() {
    autoUpdater.quitAndInstall();  
  }, 5000)
})

app.on('ready', function()  {
  autoUpdater.checkForUpdates();
});
`

**Comment by George35mk** [comment] 2017-03-14 14:20
but if i make second js file like updater.js and i add the code above without electron window 

only to see the logs nothin show

**Comment by George35mk** [comment] 2017-03-14 14:22
all hapend inside main.js where my app initializing if i kan all update code put it not in the main.js file nothink is working there is any way ??

**Comment by George35mk** [comment] 2017-03-14 16:47
why is sow dificul to make apps with electron **WHY**

there is no documantation or one single example on the internet how to make a simple updater but manualy 

i search on **Squirrel**    -> https://github.com/Squirrel/Squirrel.Windows

but this site is for **c++** users or windows c# i am using electron and nodejs javascript and css

why is sow defecul to make this work i have my app main.js that create the main window and updater that is inside that main.js if i create new file update.js that have my update fuctionlity NOT main procese only because i want to control the updates i have erros 

![adsasadasd](https://cloud.githubusercontent.com/assets/20750445/23911816/98ac1a78-08e6-11e7-9904-ad3bd699289d.PNG)

**Comment by baconface** [comment] 2017-03-14 22:18
The problem is in your code `update-downloaded` event will fire `autoUpdater.quitAndInstall();` after 5 seconds. Instead you can use IPC to notify your user of what is going on and let them have control when to update.

```javascript
autoUpdater.on('update-downloaded', function(event, releaseNotes, releaseName) {
      win.webContents.send('update-ready', releaseName);
});
```

This will fire the `update-ready` event in your renderer. You can then make it alert them about an update. 

```javascript
ipc.on('update-ready', function (event, version) {
      // Make notification appear
});
```

Then you can have a button talk back to the main process when you are ready to update.
```javascript
ipc.send('update-apply');
```

Then in the main process you look for the event and call for the app to restart and apply the update.
```javascript
ipc.on('update-apply', function (event) {
      autoUpdater.quitAndInstall();
});
```

You can do the same with the `checking-for-update`, `update-available`, `update-not-available`, `update-download`, and `error` events as well. And instead of calling `autoUpdater.checkForUpdates();` immediately you can have a button from your renderer do an IPC call to the main to call it. When you get really into it all you go from a silent style updater to one that is actually pretty customizable. So while it is kind of frustrating with the minimal example the design of it all is necessary to have a really flexible updater.

**Comment by George35mk** [comment] 2017-03-14 22:23
baconface i realy thnx you for your help from morning 03:00 itry to solve that problem i am 21 hours only with caffe . i try to find solution thnk you again 🥇

**Comment by MarshallOfSound** [comment] 2017-03-15 00:56
This issue appears to have been user generated code, closing out 👍

**Closed by MarshallOfSound** 2017-03-15 00:56 UTC
