### ISSUE TITLE
[Bug]: Dictionary doesn't suggest auto-correction from words added to the dictionary

### ISSUE THREAD

**Issue by kittykat** [electron/electron#32631] opened 2022-01-26 13:09 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.6

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Expected Behavior

Words that I add to the dictionary are suggested as results for mis-spelled words

### Actual Behavior

Words that I add to the dictionary are not suggested as results for mis-spelled words

### Additional Information

Found in Element Nightly:
1. Add "Poecilia" to the dictionary
2. Type "poecilia" into the composer and right click to see suggested autocorrections
3. Do not see "Poecilia" in the list of suggestions

**Comment by nornagon** [comment] 2022-01-26 22:15
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2022-02-16 03:52
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2022-02-16 03:52 UTC
Labels: bug :beetle:, blocked/need-repro
