### ISSUE TITLE
[Bug]: Permission issue in electron js (NEXT.js + Electron)

### ISSUE THREAD

**Issue by dipaksavaliya04** [electron/electron#32029] opened 2021-11-27 04:39 UTC
[my-app.zip](https://github.com/electron/electron/files/7607143/my-app.zip)

[Annotation 2021-11-26 130117](https://user-images.githubusercontent.com/93366473/143543414-e233dfac-3973-4c84-8aea-bcfbb2841b51.png))

This is my code and permission function inside renderer folder -> helpers -> permission.jsx

and permission function use inside renderer folder ->  components folder -> permission.jsx

and permission component use inside renderer folder -> pages folder 

** I need camera, microphone and screen recording permission so I'm using systemPreferences But Getting undefined for system preference mediaType as a 'camera', 'microphone' and 'screen'**

_Originally posted by @dipaksavaliya04 in https://github.com/electron/electron/issues/31875#issuecomment-979751591_

**Comment by VerteDinde** [comment] 2021-11-28 16:36
Closing as a duplicate of #31875, just so we can keep conversations in one place

**Closed by VerteDinde** 2021-11-28 16:36 UTC
