### ISSUE TITLE
[Bug]: appendSwitch(disable-site-isolation-trials) breaks devtools extensions

### ISSUE THREAD

**Issue by yourfavorite** [electron/electron#29052] opened 2021-05-06 23:39 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.6

### What operating system are you using?

macOS

### Operating System Version

11.2.3

### What arch are you using?

x64

### Expected Behavior

React and Redux Devtools load and are functionally connected to application.

### Actual Behavior

With `app.commandLine.appendSwitch('disable-site-isolation-trials');` the application loads and the tabs for React and Redux DevTools appear as expected. However the React Components tab in DevTools is empty and the Redux tab in DevTools says "No store found". Additionally, the error below appears in the console. Removing the disable-site-isolation-trials switch fixes the issue.

`[12334:0506/163419.330578:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.", source: chrome-extension://omcdjfajiojhldgojnbbiohlcbkcbane/main.html`

### Additional Information

It's possible this is related: https://github.com/electron/electron/issues/26714

**Comment by miniak** [comment] 2021-06-25 19:45
Duplicate of #28316

**Closed by miniak** 2021-06-25 19:45 UTC
Labels: bug :beetle:
