### ISSUE TITLE
Crash when running in docker

### ISSUE THREAD

**Issue by qrohlf** [electron/electron#6186] opened 2016-06-22 18:52 UTC
* Electron version: v1.2.4
* Operating system: docker image [node:6.2.2](https://hub.docker.com/_/node/) (debian derived) running Xvfb

When running electron-prebuilt on debian in docker, electron exits WITHOUT firing the `app.on('ready', () => {})` callback. 

Here's the stack dump generated by running with `ELECTRON_ENABLE_STACK_DUMPING=true`:

```
Received signal 11 SEGV_MAPERR 000000000000
#0 0x00000140f1eb <unknown>
#1 0x7ff897ff98d0 <unknown>
  r8: 0000000000000006  r9: 0000000000000002 r10: 00000000034ac851 r11: 00007ff8997953ec
 r12: 0000192062db5280 r13: 00007ff88f875b00 r14: 00000000000025cf r15: 0000192062dff420
  di: 00007ff88f875b00  si: 00000000000025cf  bp: 0000192062ddec90  bx: 0000000000000001
  dx: 00007ff88f65ac40  ax: 0000192062ddec80  cx: 00000000034ac918  sp: 00007ffefcf3aed8
  ip: 0000000000000000 efl: 0000000000010206 cgf: 0000000000000033 erf: 0000000000000014
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
```

See this gist for a minimal example that reproduces the issue here: https://gist.github.com/qrohlf/02b4152d788a103a9596b2444b0d5500

**Comment by kevinsawicki** [comment] 2016-06-22 20:29
This looks like a duplicate of #6178

**Closed by kevinsawicki** 2016-06-22 20:29 UTC
