### ISSUE TITLE
[Feature Request]: event before minimizing

### ISSUE THREAD

**Issue by freddy-daniel** [electron/electron#36435] opened 2022-11-24 08:57 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Requesting will-minimize event, is that possible 

### Proposed Solution

It would be better if we have event fired before window pp minimize happen. with event.preventDefault method like will-quite

### Alternatives Considered

No alternatives considered

**Comment by Thangy24** [comment] 2022-11-30 03:40
Let try

**Comment by nornagon** [comment] 2022-12-01 00:56
Duplicate of #29860

**Closed by nornagon** 2022-12-01 00:56 UTC
Labels: enhancement :sparkles:
