### ISSUE TITLE
Focus doesn't work

### ISSUE THREAD

**Issue by alexk111** [electron/electron#5276] opened 2016-04-24 13:17 UTC
* Electron version: 0.37.6
* Operating system: Ubuntu 16 64-bit

Hi guys,

Trying to bring Electron app on top & focus it when the user pushes a registered globalShortcut. Nor App.focus() nor BrowserWindow.focus() seems working on Ubuntu. Could only bring it on top by calling:
```
mainWin.setAlwaysOnTop(true);
mainWin.setAlwaysOnTop(false);
```
But still no success in focusing it.

**Comment by zcbenz** [comment] 2016-04-25 08:06
This is a duplicate of #5206.

**Closed by zcbenz** 2016-04-25 08:06 UTC
