### ISSUE TITLE
Very slow webcam capture with Raspberry PI 3 and Electron 10/11

### ISSUE THREAD

**Issue by mathieucaralp** [electron/electron#27653] opened 2021-02-08 13:47 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.3
* **Operating System:**
  * Raspberry PI 3B+, Raspbian 9.4
* **Last Known Working Electron version:**
  * 9.4.3

### Expected Behavior
I use Electron to get data from a webcam connected to a RPI 3B+. I use the usual procedure: I retrieve the webcam stream with `navigator.mediaDevices.getUserMedia()`, then I draw it to a canvas with the `drawImage` method of my context. It works smoothly with Electron 9.4.3.

### Actual Behavior
With Electron 11.2.3, the CPU goes really high and it produces a lot of lags. It is unusable. 

### To Reproduce

**Main process code**
```js
const { app, BrowserWindow } = require('electron')

async function main()
{
    await app.whenReady()

    app.on('window-all-closed', () => {
            app.quit()
    })

    const win = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            nodeIntegration: true
        }
    })
    win.loadFile('index.html')
}

main()
```
**Renderer code**

```html
<html>
    <head>
    </head>
    <body>
        <script>            
            async function waitReady(video) {
                return new Promise(accept => {
                    const callback = () => {
                        video.removeEventListener('canplay', callback)
                        accept()
                    }

                    video.addEventListener('canplay', callback)
                })
            }

            function sleep(timeout) {
                return new Promise(accept => setTimeout(accept, timeout))
            }

            async function main() {
                const video  = document.createElement('video')
                const canvas = document.createElement('canvas')
                const ctx    = canvas.getContext("2d")    
                const stream = await navigator.mediaDevices.getUserMedia({ video:true })

                if(stream.getVideoTracks().length != 0) {
                    video.srcObject = stream
                    video.play()
                    await waitReady(video)

                    canvas.width = video.videoWidth
                    canvas.height = video.videoHeight        
                    document.body.appendChild(canvas)

                    while(true) {
                        ctx.drawImage(video, 0, 0, video.videoWidth, video.videoHeight)
                        await sleep(100)
                    }
                }
            }

            main()
        </script>
    </body>
</html>
```
### Screenshots
![screenshot](https://user-images.githubusercontent.com/37294998/107224825-4091fa00-6a18-11eb-80d2-53873d7681e4.jpg)

### Additional Information
I also tested Electron 10.3.2 with the same result. On my laptop with Ubuntu 20.04 it works well.

**Comment by ckerr** [comment] 2021-02-08 14:19
gist copy of testcase above ^: https://gist.github.com/ckerr/c175454778b75f5be0e9ef74002d9563

**Comment by ckerr** [comment] 2021-02-08 15:31
@mathieucaralp, thanks for reaching out and reporting this issue!

Like  you, I'm not seeing the behavior on a laptop -- CPU use there is just a few % points. (Tested on Ubuntu 20.10 with Electron 10.3.2 and 11.2.3 by running the gist, confirming that the camera feed was working, and checking top.)

However, I'm also not able to reproduce this with 11.2.3 on a Raspberry Pi. Unfortunately I got the screenshot resolution wrong and so the text isn't readable, but htop's percentage bars still tell the story: CPU use running the testcase clocked the CPU at about 20%, and that is with electron-fiddle running as well. (Tested on Raspberry Pi 400 Rev 1.0 running Ubuntu 20.10 with Electron 11.2.3.):

![foo](https://user-images.githubusercontent.com/70381/107240735-debd9a00-69ef-11eb-955c-eb70d33724a0.jpg)

Since I'm not able to reproduce this issue even when testing on a Pi, I'm going to mark this as `blocked/need-info` for now. @mathieucaralp if you have any information that might lead to an Electron team member being able to triage this better, please let us know.

**Comment by mathieucaralp** [comment] 2021-02-08 19:10
Since it is working for you with a RPI4, I tried to change the OpenGL driver. By default It's not enabled with RPI3, but now it's enabled with RPI4. And it seems to work far better. That said I have some strange messages:
```
libGL error: MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device informatio
```
But the webcam works smoothly. To change the OpenGL driver, use the raspi-config command, got to advanced->GL Driver

**Comment by mathieucaralp** [comment] 2021-02-08 19:20
It seems also to work by calling the function `app.disableHardwareAcceleration()`.

**Comment by ckerr** [comment] 2021-02-08 19:45
I'm closing this issue because it appears to be a config issue rather than a problem in Electron itself.

If I've misunderstood and you do think this is an Electron bug, please open a new issue to let the Electron team know.

Thank you!

**Closed by ckerr** 2021-02-08 19:45 UTC
Labels: 11-x-y, blocked/need-info ❌, bug/regression :leftwards_arrow_with_hook:, has-repro-gist, performance :checkered_flag:, status/reviewed

**Comment by mathieucaralp** [comment] 2021-02-09 09:17
Yes I agree with you, It's probably a configuration issue. But I would like to understand why this config was not necessary for Electron 9, and is mandatory now. Do you know if Electron (or V8?) changed the way it handles the video streams since version 10?
