### ISSUE TITLE
black screen on win7 - electron6

### ISSUE THREAD

**Issue by xiaoping6688** [electron/electron#20281] opened 2019-09-19 03:19 UTC
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.9
* **Operating System:**
  * window7
* **Nodejs version:**
  * 12.10.0

### Expected Behavior
boot the app normal

### Actual Behavior
black screen on started

**Comment by DBnR1** [comment] 2019-09-19 10:10
Likely same as #19569

**Comment by MarshallOfSound** [comment] 2019-09-20 06:28
Duplicate of #19569

**Closed by MarshallOfSound** 2019-09-20 06:28 UTC
