### ISSUE TITLE
Menu.buildFromTemplate is not a Function Error

### ISSUE THREAD

**Issue by sujithv28** [electron/electron#5862] opened 2016-06-03 23:29 UTC
* Electron version: Latest
* Operating system: Mac OS X

`var Menu = require("menu");`

`var template = [{
      label: "Application",
      submenu: [
          { label: "About Application", selector: "orderFrontStandardAboutPanel:" },
          { type: "separator" },
          { label: "Quit", accelerator: "Command+Q", click: function() { app.quit(); }}
      ]}, {
      label: "Edit",
      submenu: [
          { label: "Undo", accelerator: "CmdOrCtrl+Z", selector: "undo:" },
          { label: "Redo", accelerator: "Shift+CmdOrCtrl+Z", selector: "redo:" },
          { type: "separator" },
          { label: "Cut", accelerator: "CmdOrCtrl+X", selector: "cut:" },
          { label: "Copy", accelerator: "CmdOrCtrl+C", selector: "copy:" },
          { label: "Paste", accelerator: "CmdOrCtrl+V", selector: "paste:" },
          { label: "Select All", accelerator: "CmdOrCtrl+A", selector: "selectAll:" }
      ]}
  ];
`

 `const menu = Menu.buildFromTemplate(template); `

  `Menu.setApplicationMenu(menu); 
`

This code results in the error:

`A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Menu.buildFromTemplate is not a function
    at EventEmitter.createWindow (/Users/user/Documents/AppName/main.js:66:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
`

**Comment by enlight** [comment] 2016-06-04 02:07
As of v1.0.0 all built-in modules must be accessed via the `electron` module, so use `const { Menu } = require('electron')`.

**Comment by sujithv28** [comment] 2016-06-04 05:07
For some reason it doesn't work when I copy text within the app and try to paste it. It only works if I copy text from some source outside the App.

**Comment by zcbenz** [comment] 2016-06-06 00:53
Thanks @enlight for answering this, closing since this is not a bug.

**Closed by zcbenz** 2016-06-06 00:53 UTC

**Comment by jasonkester** [comment] 2016-11-23 13:46
The docs are wrong (as of 20161123).

If you have:
```
var electron = require('electron');

```
then you need to access menu as

`electron.Menu`

**Comment by MarshallOfSound** [comment] 2016-11-23 13:51
@jasonkester The docs currently state

```js
const {app, Menu} = require('electron')
```

Notice the `{ Menu }` syntax, it ES6 destructuring.
