### ISSUE TITLE
[Bug]: Window overlay controls ignores `maximizable` and `minimizable` properties

### ISSUE THREAD

**Issue by lee011** [electron/electron#31352] opened 2021-10-08 17:10 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22000.194

### What arch are you using?

x64

### Expected Behavior

When a `BrowserWindow` is initialized with the following properties:

```js
{
    titleBarStyle: "hidden",
    maximizable: false,
    minimizable: false,
    titleBarOverlay: true,
}
```

The window's controls overlay should disable (or not display) the maximize and minimize buttons.

### Actual Behavior

The window still displays the maximize and minimize buttons, and the window can still be maximized or minimized using these buttons when `maximizable` and `minimizable` are set to `false`.

### Testcase Gist URL

https://gist.github.com/lee011/3e392cd3e936b0791a2e6b991a8c5434

**Comment by theolivenbaum** [comment] 2021-11-25 12:32
Also wanted to add, the maximize button seems to be doing nothing for me. Minimize and close works.
Tested on both Win10 and Win11, window options on creation set to: `{ transparent:true, frame:true, titleBarStatus: 'hidden', maximizable: true,resizable:true, titleBarOverlay: true }`

**Comment by limacheb** [comment] 2022-01-17 12:48
I can confirm this bug also for Electron 16.  
Are there any plans for delivering a fix?

**Comment by SquitchYT** [comment] 2022-02-23 17:08
I have the same bug when setting window as transparent. But in my case, i don't set maximizable and minimizable as `false`

**Comment by gpetrov** [comment] 2022-05-20 14:04
Still happening in Electron 18, very annoying bug, we just can't disable/hide the minimize or maximize buttons. This makes the WCO integration a bit useless.

@clavin any ideas?

**Comment by panther7** [comment] 2022-05-23 13:23
Is `maximizable` and `minimizable` somewhere are documented?

**Comment by limacheb** [comment] 2022-06-21 05:52
Still happening in Electron 19.   
This makes the WCO unusable for us.  
I would appreciate a statement from the electron team in respect to the timeline by when this could be fixed.

**Comment by codebytere** [comment] 2022-06-28 20:25
Fixed in https://github.com/electron/electron/pull/34677

**Closed by codebytere** 2022-06-28 20:25 UTC
Labels: platform/windows, bug :beetle:, 15-x-y
