### ISSUE TITLE
the adaptive formula to calculate zoomfactor to make Html look the same on diverse device

### ISSUE THREAD

**Issue by zhbzhbzhbz** [electron/electron#8722] opened 2017-02-20 16:57 UTC
On different device(different length-width ratio, different resolution, such as Mac/Windows Laptop), the display effect of a HTML page will be different.
Under the circumstance of using Bootstrap(adaptive width), I have developed a formula to calculate the accurate zoomFactor in order to make the page look fully the same.
In any JS file in render process, We could use the code below (these code can be called at some point e.g. when maximized)

```
var devInnerHeight = 658.0; //the innerHeight of your dev environment
var devDevicePixelRatio = 1.5; //the devDevicePixelRatio of your dev environment
var devScaleFactor = 1.5; //the devScaleFactor of your dev environment
var scaleFactor = require('electron').screen.getPrimaryDisplay().scaleFactor;
var zoomFactor = window.innerHeight / devInnerHeight * window.devicePixelRatio / devDevicePixelRatio * devScaleFactor / scaleFactor;
require('electron').webFrame.setZoomFactor(factor);
```

**Comment by groundwater** [comment] 2017-02-20 19:38
Hi @zhbzhbzhbz. Thank you for this.

We can look at adding this to the appropriate documentation.

**Comment by zeke** [comment] 2017-03-02 20:02
@zhbzhbzhbz thanks for sharing your formula! Would you be willing to submit a pull request that adds this to the documentation?

If so, I think adding it to the [`webContents` doc](https://github.com/electron/electron/blob/master/docs/api/web-contents.md) would be best, as it is the [most-viewed API](https://cloudup.com/cDjARyBrWIc) that has a `setZoomFactor` method. It would also be good to link to it from the other APIs that offer a `setZoomFactor` method, such as [<webview> tag](https://github.com/electron/electron/blob/master/docs/api/webview-tag.md) and [webFrame](https://github.com/electron/electron/blob/master/docs/api/web-frame.md).

**Comment by zcbenz** [comment] 2017-06-12 07:49
I'm closing this since it is not a bug report nor feature request.

**Closed by zcbenz** 2017-06-12 07:49 UTC
Labels: triage/docs
