### ISSUE TITLE
No shadow on transparent window with inital `show` set to `false`

### ISSUE THREAD

**Issue by davej** [electron/electron#4472] opened 2016-02-13 23:55 UTC
The following code should display a window after it has finished loading:

```js
const prefWindow = new BrowserWindow({
  width: 450,
  'min-width': 450,
  'max-width': 450,
  height: 400,
  'min-height': 400,
  'max-height': 400,
  titleBarStyle: 'hidden',
  transparent: true,
  maximizable: false,
  show: false,
  hasShadow: true
});

prefWindow.loadURL('prefs.html');

prefWindow.webContents.on('did-finish-load', () => {
  prefWindow.show();
});
```

Here's a video of what this window looks like: http://cl.ly/1P0u3z3k3p46 (notice the missing shadow).

This can be fixed by simply resizing the window after it has been shown.

```js
const prefWindow = new BrowserWindow({
  // ... same as previous example
});

prefWindow.setSize(0, 0); // HACK
prefWindow.loadURL('prefs.html');

prefWindow.webContents.on('did-finish-load', () => {
  prefWindow.show();
  prefWindow.setSize(450, 400); // HACK
});
```

Tested on Electron 0.36.7 on OS X 10.10.5.

**Comment by DannyvanderJagt** [comment] 2016-04-20 21:25
@davej I tried to recreate your problem but everything is working fine. (Electron 0.37.5 & OSX 10.11.3)
Can you confirm this for me please :)

**Comment by davej** [comment] 2016-04-21 15:13
@DannyvanderJagt Just upgraded to Electron 0.37.6 and the issue still remains for me. I only have access to OS X 10.10.5 at the moment so can't test OS X 10.11 at the moment.

**Comment by DannyvanderJagt** [comment] 2016-04-21 18:06
No problem, I was just checking if some issues are still active. I won't be able to help with this one, I don't have an device at the moment that runs on OSX 10.10. Maybe someone else can help here.

**Comment by davej** [comment] 2016-05-10 16:46
To anyone coming across this. My initial hack doesn't work with more recent versions of Electron, I'm now using setTimeout to delay showing the window instead:

```js
const prefWindow = new BrowserWindow({
  // ...
});

prefWindow.loadURL('prefs.html');

prefWindow.webContents.on('did-finish-load', () => {
  setTimeout(() => prefWindow.show(), 50); // HACK
});
```

This bug may be specific to my app and the way I'm doing things. Does anybody know when the window shadow is drawn? Is it after the `window.onload` event?

**Comment by kevinsawicki** [comment] 2016-06-24 17:15
@davej are you still seeing this behavior on the latest release? I was unable to reproduce today on 10.11.5 using Electron 1.2.5.

Did you ever upgrade to 10.11, and are you still seeing it on 10.10.x or 10.11.x as well? Thanks.

<img width="891" alt="screen shot 2016-06-24 at 10 13 21 am" src="https://cloud.githubusercontent.com/assets/671378/16344996/6d5b8672-39f4-11e6-8281-294f46a0579f.png">

**Comment by davej** [comment] 2016-06-24 17:38
@kevinsawicki Yes, I am still seeing this most of the time. It seems to be related to the load time of the page. Small basic pages work fine but more complex pages seem to work intermittently or not at all.

I have tried using the new `win.on('ready-to-show')` event instead of `win.webContents.on('did-finish-load')` but I still experienced the same issue. I'll add this to my todo list and hopefully I can come up with a reproducible demo for this behaviour when I have some free time.

**Comment by kevinsawicki** [comment] 2016-06-24 17:39
> Yes, I am still seeing this most of the time

Ever on OS X 10.11.x?

**Comment by davej** [comment] 2016-06-24 17:42
> Ever on OS X 10.11.x?

I haven't checked that actually. My day-to-day machine is 10.10 but I've got 10.11 in a VM so I'll boot that up and give it a try. I can't do it right now but I'll get around to it over the weekend.

**Comment by kevinsawicki** [comment] 2016-06-24 17:44
> I can't do it right now but I'll get around to it over the weekend.

Awesome, thanks 👍

**Comment by davej** [comment] 2016-06-27 11:32
@kevinsawicki I've just tried it on 10.11.6 Beta and it seems to work OK consistently. This was in a VM though and it runs quite a bit slower than my host OS (I only mention this because the conditions may just mean that there's a different winner of the race rather than a bug in 10.10).

**Comment by davej** [comment] 2016-06-27 15:03
I've managed to find a shadow issue on 10.11 now too. It manifests itself a bit differently though, see attached screenshot. On 10.10, this window will either show with a shadow or without it. On 10.11 it consistently shows a lumpy shadow like below. The 50ms hack fixes the issue on both operating systems for me.

![screen shot 2016-06-27 at 15 50 43](https://cloud.githubusercontent.com/assets/26971/16384311/555115fe-3c80-11e6-9cb9-f5cb484c8328.png)

This may well be an issue specific to my app. I can't find anything unusual that I'm doing though, the app is being rendered using React.

**Comment by zcbenz** [comment] 2016-07-01 05:53
Can you share the HTML file that has the problem?

**Comment by davej** [comment] 2016-07-01 09:05
@zcbenz Sure.

```html
<!DOCTYPE html>
<html>
  <head>
  	<meta charset="utf-8">
    <title>export</title>
    <link href="app.css" rel="stylesheet" />
    <script>
      if (!process.env.HOT) {
        const link = document.createElement('link');
        link.rel = 'stylesheet';
        link.href = `../dist/${document.title}.css`;
        document.write(link.outerHTML);
      }
    </script>
    <link rel="stylesheet" href="css/photon.css" />
  </head>
  <body>
    <div id="root"></div>
    <script>
      global.runningInMenuBar = !process.env.WINDOWED;

      const vendorScript = document.createElement('script');
      vendorScript.src = '../dist/frontend.chunk.js';
      if (!process.env.HOT) document.write(vendorScript.outerHTML);

      const script = document.createElement('script');
      script.src = (process.env.HOT) ?
        `http://localhost:3000/dist/${document.title}.js` :
        `../dist/${document.title}.js`;
        document.write(script.outerHTML);
    </script>
  </body>
</html>
```

**Comment by zcbenz** [comment] 2016-07-12 07:06
It seems that OS X only draws the shadow when the window is showed for the first time, so if you changed page's content after showing the window, the shadow will not be updated. The only solution is to show the window after you have created all DOM elements.

I'm closing this as won't fix since it is a limitation of OS X.

**Closed by zcbenz** 2016-07-12 07:06 UTC
Labels: bug, osx
