### ISSUE TITLE
When a transparent window shows, it will flicker twice

### ISSUE THREAD

**Issue by ervinewell** [electron/electron#24753] opened 2020-07-28 03:43 UTC
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:**
  * 7.1.13
* **Operating System:**
  * Windows 10

### Expected Behavior
When a transparent window shows from a hidden state, it should flicker once.

### Actual Behavior
It flicker twice.

### To Reproduce
```
const win = new BrowserWindow({
  width: 200,
  height: 200,
  frame: false,
  transparent: true,
  backgroundColor: '#80000000'
})
win.hide() // make it hidden
win.show() // it'll flicker twice when it becomes visible
```

### Screenshots
![ezgif-2-fa4446371d8e](https://user-images.githubusercontent.com/11768033/88616905-e8248c00-d0c7-11ea-9723-06a72b859ad2.gif)

**Comment by ahallicks** [comment] 2020-07-28 07:40
See https://github.com/electron/electron/issues/12130#issuecomment-627198990 and that issue in general

**Comment by ckerr** [comment] 2020-07-28 16:34
I agree with @ahallicks, this looks like a dupe of #12130 so I'm going to close this one.

**Closed by ckerr** 2020-07-28 16:34 UTC
Labels: 7-1-x, platform/windows
