### ISSUE TITLE
2.0.0-beta.1 context menu click event doesnt fire

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#12030] opened 2018-02-23 19:13 UTC
* Electron version: 2.0.0-beta.1
* Operating system: MacOS 10.12

### Expected behavior

Context menu MenuItem click event fires on click

### Actual behavior

Event doesnt fire

### How to reproduce

https://github.com/pfrazee/electron-bug-context-menu-click

```
git clone https://github.com/pfrazee/electron-bug-context-menu-click
cd electron-bug-context-menu-click
npm install
npm start
```

Right click, select 'MenuItem1'. A log event should occur but wont.

**Comment by ckerr** [comment] 2018-02-23 23:25
I'm closing this issue because it appears to be a duplicate of #11818. If this is in error, please @ me in a followup comment and I'll reopen the issue. Thank you!

**Closed by ckerr** 2018-02-23 23:25 UTC
