### ISSUE TITLE
Unpacked from asar module loading ends up with ".../package.json: Unexpected end of JSON input"-like error

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#26819] opened 2020-12-03 17:43 UTC
### Issue Details

* **Electron Version:** 11.0.3
* **Operating System:** Linux, Windows 10, macOS
* **Last Known Working Electron version:** 10.x

### Expected Behavior
- Modules get successfully loaded even if they have been unpacked.
- The https://github.com/vladimiry-playground/electron-asar-issue app prints `{ packageName: 'electron-asar-issue' }` to console.

### Actual Behavior

A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Error parsing /home/user/dev/electron-asar-issue/build/resources/app.asar/node_modules/fs-extra/package.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:269:20)
    at readPackageExports (internal/modules/cjs/loader.js:309:15)
    at applyExports (internal/modules/cjs/loader.js:450:20)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Module._resolveFilename (internal/modules/cjs/loader.js:959:27)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)

### To Reproduce
- git clone https://github.com/vladimiry-playground/electron-asar-issue.git
- cd electron-asar-issue
- npm ci
- npm start

### Additional Information
- Please don't close the issue with motivation that it's up to `electron-builder` or `electron-packager` projects. The repro project packs things to asar using just pure https://www.npmjs.com/package/asar.
- The `fs-extra` module picked for demo purposes. The issue is not specific to this module.
- The `fs-extra` module is not a native one, so please don't blame #18397.
- Removing the `--unpack-dir \"node_modules/fs-extra\"` part from [this](https://github.com/vladimiry-playground/electron-asar-issue/blob/7fe2c1847445a16fa9f7541291b1d0a3bc573f40/package.json#L12) line will make it work since there won't be `app.asar.unpacked` dir involving anymore.
- Related issues: #25438, #26079, https://github.com/electron-userland/electron-builder/issues/5360.

**Comment by MarshallOfSound** [comment] 2020-12-03 19:51
Followed your steps to reproduce on macOS and can't reproduce it 🤔  Specifically cloning that repo, running `yarn build && yarn start` does not result in any errors 🤔

**Comment by HyperSprite** [comment] 2020-12-03 20:21
@MarshallOfSound
Thanks for all your hard work,

I didn't want to muddy this issue if the OP can repo this on macOS but in my case:

Tested latest builds from 9.3.5, 10.1.6, and 11.0.3 from yesterday (we were upgrading from 8 to 11 to fix the Big Sur autoupdate restart issue, which seems to be resolved, thank you).

- macOS builds and runs fine with 11.0.3. (done at least 10 test builds that have all worked)
- win32 works for 9.3.5 and 10.1.6 but fails with 11.0.3 with the `Unexpected end of JSON input` error for SQLite (our only unpacked package).
  - If I set the windows build to `asar: false` it will build and run fine on win32.
  - tried `rm -rf node_modules && yarn cache clean && yarn`

**Comment by vladimiry** [comment] 2020-12-03 20:41
> Followed your steps to reproduce on macOS and can't reproduce it thinking Specifically cloning that repo, running yarn build && yarn start does not result in any errors thinking

I have just updated the issue description with the only systems I was actually able to reproduce the issue on. Any system was put there since both original unresolved issues were reported on macos. I guess the repro project can be adjusted somehow to include the macos but I'm not planning to do so.

Also fixed in the repro project the npm start script for win32 platform.

**Comment by vladimiry** [comment] 2020-12-03 20:50
> Followed your steps to reproduce on macOS and can't reproduce it

> I guess the repro project can be adjusted somehow to include the macos but I'm not planning to do so.

The guess is that on macOS system the path of the resources normally looks like `./ProductName.app/Contents/Resources` but on linux/win32 it's just `./resources`. The repro project directly referencing the `./resources` location so that might be the cause of why it's not reproduced on macos. But again, I'm not planning to fix repro project for including macos.

**Comment by lockieluke** [comment] 2020-12-04 02:10
I have the same issue the problem breaks when asar is enabled but works well with asar disabled

**Comment by kirille** [comment] 2020-12-04 09:36
I was able to reproduce issue on macOS with **electron-asar-issue**  repo with minor changes in package.json:

```
diff --git a/package.json b/package.json
index 5bba690..f9e52a0 100644
--- a/package.json
+++ b/package.json
@@ -9,12 +9,15 @@
     "build:clean": "rimraf ./build",
     "build:app:npm:clean": "rimraf ./app/node_modules",
     "build:app:npm:install": "npm --prefix ./app ci",
-    "build:app:pack-to-asar": "npx --no-install asar pack ./app ./build/resources/app.asar --unpack-dir \"node_modules/fs-extra\"",
+    "build:app:pack-to-asar": "run-script-os",
+    "build:app:pack-to-asar:win32:linux": "npx --no-install asar pack ./app ./build/resources/app.asar --unpack-dir \"node_modules/fs-extra\"",
+    "build:app:pack-to-asar:darwin": "npx --no-install asar pack ./app ./build/Electron.app/Contents/Resources/app.asar --unpack-dir \"node_modules/fs-extra\"",
     "build:electron:copy": "cpx \"./node_modules/electron/dist/**/*\" ./build",
     "build:electron:remove-default-app": "rimraf ./build/resources/default_app.asar",
     "build:start": "run-script-os",
     "build:start:win32": "build\\electron.exe",
-    "build:start:darwin:linux": "./build/electron"
+    "build:start:linux": "./build/electron",
+    "build:start:darwin:": "./build/Electron.app/Contents/MacOS/Electron app/index.js"
   },
   "devDependencies": {
     "asar": "3.0.3",
```

These issue is a blocker forupdate to Electron 11, for our project

**Comment by benpratt22** [comment] 2020-12-04 10:03
Happening to us on macOS, electron version 11.0.3. Using asar: false in the meantime.

**Comment by vladimiry** [comment] 2020-12-04 11:36
@kirille, thanks for the patch. This is what I guessed needs to be done to make the issue reproducible on macos, ie picking proper resources path for macos. Repro repo got updated accordingly.

**Comment by MarshallOfSound** [comment] 2020-12-04 21:49
Fixed in #26749

**Closed by MarshallOfSound** 2020-12-04 21:49 UTC

**Comment by vladimiry** [comment] 2020-12-05 08:39
@vadim-termius, thanks for fixing the issue even before it got properly placed.

**Comment by vinay-khatri** [comment] 2020-12-06 14:03
> @vadim-termius, thanks for fixing the issue even before it got properly placed.

I dont know much about github issues .. but i have this same issue in my first ever electron app. Already wasted 24 hrs trying to solve it but no luck.
As i can see @MarshallOfSound has fixed this issue and sent a pull-request. Should i use Marshal's branch.. or should i wait for official master branch to get updated? Will this break my official electron branch (11.0.3) i downloaded from npm? and what if Marshal has added some hidden malecious code in his branch ?? 

Any info would be really helpful

**Comment by vladimiry** [comment] 2020-12-06 14:10
@vinay-khatri, I guess you have to wait until the new release with the #26749 fix included gets landed on https://www.npmjs.com/package/electron. Until then you have a workaround of not packing node modules to asar.

**Comment by vladimiry** [comment] 2020-12-11 04:51
Con confirm issue resolving in v11.0.4. Thanks everyone involved in fixing it.
