### ISSUE TITLE
[Feature Request]: Multiple electron apps in the same shared process/hub for less resource usage

### ISSUE THREAD

**Issue by p32929** [electron/electron#27976] opened 2021-03-03 05:01 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Electron apps are increasing exponentially. Nowadays we have to use multiple electron app instances in the same computer.
But every single app instance runs a separate instance of Chromium/ElectronJS which uses more resources, which is bad for performance.

### Proposed Solution

Since, multiple apps are already using Chromium/ElectronJS, if there was a way to make them share the same instance of Chromium/ElectronJS, kind of like multiple Tabs/Windows in a browser, that would make ElectronJS apps faster, less resource hungry, and so on. 

### Alternatives Considered

I have searched for some alternatives but haven't found any yet

### Additional Information

Or if there's an App made by the official team of ElectronJS that scans all the ElectronJS apps installed in the system and puts them into the same ElectronJS folder/instance to share resources, should be good too.

Thanks

**Comment by vladimiry** [comment] 2021-03-03 06:42
Normally, for a list of reasons, apps get developed and tested on the specific version of Electron (the version is normally defined in the package.json file). For example, some Linux distros cut of the Electron part/bundle from the apps and make them/the-asar-files use a single Electron package installed on the system. I think you understand that you can't expect the original level of stability from that kind of apps.

**Comment by p32929** [comment] 2021-03-05 04:35
So, here's what we can actually do to make it work.
1. We can make the future releases of ElectronJS backward compatible
2. Whenever someone tries to install an app made using ElectronJS,
Suppose App1 and App2 were made using Electron. But App1 was made using Electron X.Y.1 and App2 was made using X.Y.2
Now, whenever a new app is getting installed, if the electron version is higher, we first upgrade the Electron ( May be by putting ElectronJS in a new folder or sandboxed something or IDK, so that its easier to upgrade )
Then the rest of the installation progress can carry on, by putting the app into its own folder.
Now, when the apps try to run, it can use the same electron/chromium version.

I think, this way we can have the stability and performance

**Comment by vladimiry** [comment] 2021-03-05 09:03
> I think, this way we can have the stability

Unfortunately not.

Electron is not a library but a runtime. After the update/upgrade there might be hundreds of subtle changes lets say in @chromium that won't be marked as breaking. You update the Electron version and one of those subtle changes will break your app (see recent example [here](https://github.com/vladimiry/ElectronMail/commit/3b0cf9aba3058908fe55488aab488cdfd01fca80#diff-10365f4640c72834678beb6270b0f823db3b0188d591564fa698656d27468d2fR148-R164)). So to get stability after each Electron `update` the original app developers have to test things before releasing. In my experience even minor `update` might break things, not only the `upgrade`.

Even if all the potentially breaking changes get thoroughly marked as such (which is not the case), the developers will need to adopt the changes of the new Electron/runtime before switching to it.

**Comment by p32929** [comment] 2021-03-05 13:52
Oww, I see. So, there's no way to make ElectronJS apps more performant and less bloated than now?
I mean, there's gotta be a way, right?

**Comment by nornagon** [comment] 2021-06-23 22:43
Duplicate of #673

**Closed by nornagon** 2021-06-23 22:43 UTC
Labels: enhancement :sparkles:
