### ISSUE TITLE
Apps are not treated as `.zip` files when uploading through `<input type="file" />`

### ISSUE THREAD

**Issue by zoubin** [electron/electron#9244] opened 2017-04-21 09:46 UTC
* Electron version: 1.4.0
* Operating system: macOS 10.12.4

### Expected behavior
When uploading Chess in the Applications folder through  `<input type="file" />`, `event.target.files[0].type` should be `application/zip`, which is the case when uploaded in Chrome.

### Actual behavior
`event.target.files[0].type` is an empty string.

### How to reproduce

Run the following the code in some page loaded by Electron and Chrome, different logs are displayed in dev tools.

```js
var input = document.createElement('input')
input.type = 'file'
input.addEventListener('change', e => console.log(e.target.files[0]))
document.body.appendChild(input)
```

Electron:
![image](https://cloud.githubusercontent.com/assets/2097644/25272350/08fad382-26ba-11e7-8032-1a6c05350072.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/2097644/25272467/916658fe-26ba-11e7-8e5b-b819c25eb262.png)

We can see that the `name`, `size` and `type` properties have different values.

**Comment by kevinsawicki** [comment] 2017-04-21 15:41
I believe this is a duplicate of #8948, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2017-04-21 15:41 UTC
