### ISSUE TITLE
[Bug]: `renderer-process-gone` when resize window

### ISSUE THREAD

**Issue by JesuisTong** [electron/electron#35457] opened 2022-08-25 13:13 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19042.928

### What arch are you using?

ia32

### Last Known Working Electron version

unknown

### Expected Behavior

I use css `em` unit to implement `responsive app`. Of course i use both of  `window.addEventListener('resize')` and `ResizeObserver` API. Renderer process should not crashed.

### Actual Behavior

When i drag the window boundary, renderer process will be crashed. Even if i `throttle` or `debounce` the `resize callback`, can not resolve the crash problem.

The `renderer-process-gone` event result is `oom`.

The `Windbg` error log:
```
(5ed8.5c8c): Unknown exception - code e0000008 (first chance)
(5ed8.5c8c): Unknown exception - code e0000008 (!!! second chance !!!)
eax=00197970 ebx=0640ccac ecx=00000001 edx=00000000 esi=e0000008 edi=012bccf8
eip=76bea6e2 esp=00197970 ebp=001979c8 iopl=0         nv up ei pl nz ac po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000212
KERNELBASE!RaiseException+0x62:
76bea6e2 8b4c2454        mov     ecx,dword ptr [esp+54h] ss:002b:001979c4=ec72ecac
```

### Additional Information

Renderer process code implementation just look like below:
```js
export const useFontSize = () => {
  const [fontSize, setFontSize] = useState<number>(initialFontSize);

  useEffect(() => {
    const observe = entries => {
      const { contentRect } = entries[0];
      setFontSize(calculateFontSize(contentRect));
    };
    const obs = new ResizeObserver(observe);
    obs.observe(document.body);
    return () => {
      obs.disconnect();
    };
  }, []);

  return [fontSize];
};

const MainLayout = () => {
  const [fontSize] = useFontSize();
  return <div style={{ fontSize }}>
    // sth auto resized by fontSize
  </div>
}
```

**Comment by codebytere** [comment] 2022-08-25 14:15
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-09-05 08:38
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-09-05 08:38 UTC
Labels: bug :beetle:, blocked/need-repro
