### ISSUE TITLE
Website lists bogus changelog entry for 3.0.0-beta.2 release

### ISSUE THREAD

**Issue by jacobq** [electron/electron#13631] opened 2018-07-11 19:10 UTC
* Electron Version: 3.0.0-beta.2

I'm not sure where to report electron webpage issues so am creating this here.

1. Go to https://electronjs.org/releases#3.0.0-beta.2
2. Note the "Linux" section:

   > Linux
   > Fixed a Linux thing. #123

#123 appears to be a Windows issue that was opened 4+ years ago. Also, this entry does not appear in the [Github release info](https://github.com/electron/electron/releases/tag/v3.0.0-beta.2), so I strongly suspect this is just a placeholder that should have been removed.

**Comment by ckerr** [comment] 2018-07-11 23:06
You're correct, this is a placeholder. :D

**Comment by ckerr** [comment] 2018-07-12 14:45
The placeholder's been removed from https://github.com/electron/electron/releases/tag/v3.0.0-beta.2 but the page at https://electronjs.org/releases hasn't picked up this change yet. This disconnect is already discussed at https://github.com/electron/releases/issues/6 so I'm going to close this as a duplicate of that issue.

**Closed by ckerr** 2018-07-12 14:45 UTC
Labels: documentation :notebook:, enhancement :sparkles:, version/3.0.x
