### ISSUE TITLE
[Bug]: renderer crashes when running native debug build of electron

### ISSUE THREAD

**Issue by MichaelBelousov** [electron/electron#34977] opened 2022-07-19 15:16 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.10

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21.10

### What arch are you using?

x64

### Expected Behavior

renderer doesn't crash with a native debug build. Use [this documentation](https://www.electronjs.org/zh/docs/latest/development/debugging#breakpoint-debugging) to set up an electron build. Then build [this open source electron application](https://github.com/iTwin/itwinjs-core/tree/master/test-apps/display-test-app). Here is a quick guide to building it:

```sh
git clone https://github.com/iTwin/itwinjs-core.git
cd itwinjs-core/test-apps/display-test-app
# instead of the npx usage, you can install rush globally `npm install -g @microsoft/rush`, and use `rush`
npx --package @microsoft/rush install
npx --package @microsoft/rush build -t display-test-app
# run the local development server for the application in the background (use another terminal perhaps)
npm run start:webserver &
NODE_ENV=development path/to/debug/built/electron --change-stack-guard-on-fork=disable ./lib/backend/DtaEletronMain.js
```

The change-stack-guard-on-fork option was mentioned to me in #34923 as a solution for code detecting stack smashing and is required or it will die on stack smashing before it gets to the crash.

I'm not sure how to make a more minimal reproduction since I can't seem to catch the crash in gdb even with follow-fork-mode child. I'd appreciate any pointers on further details I can provide.

Here is the stack trace upon renderer death. The window stays open but goes blank and the devtools disconnect.

```stack
Received signal 11 SEGV_MAPERR 000000000000
#0 0x561176607dbf base::debug::CollectStackTrace()
#1 0x5611763e048a base::debug::StackTrace::StackTrace()
#2 0x5611763e0445 base::debug::StackTrace::StackTrace()
#3 0x56117660789d base::debug::(anonymous namespace)::StackDumpSignalHandler()
#4 0x7fb158467520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#5 0x5611690cbd95 std::__1::basic_string<>::__is_long()
#6 0x5611690cc9a9 std::__1::basic_string<>::__get_pointer()
#7 0x5611690cc8c5 std::__1::basic_string<>::data()
#8 0x5611764e5061 base::BasicStringPiece<>::BasicStringPiece()
#9 0x56117cffdd1f blink::SecurityOrigin::CreateFromUrlOrigin()
#10 0x56117cce0b26 blink::WebSecurityOrigin::WebSecurityOrigin()
#11 0x56117635277e extensions::(anonymous namespace)::WebLocalFrameAdapter::CanAccess()
#12 0x561181ed1f15 extensions::ContentScriptInjectionUrlGetter::Get()
#13 0x561176350ab4 extensions::(anonymous namespace)::GetEffectiveDocumentURL()
#14 0x561176350a56 extensions::ScriptContext::GetEffectiveDocumentURLForContext()
#15 0x56117629d028 extensions::Dispatcher::DidCreateDocumentElement()
#16 0x56117629cf6f extensions::Dispatcher::OnRenderFrameCreated()
#17 0x5611695b5432 electron::RendererClientBase::RenderFrameCreated()
#18 0x5611695ade3f electron::ElectronSandboxedRendererClient::RenderFrameCreated()
#19 0x56117ea8e117 content::RenderFrameImpl::Initialize()
#20 0x56117ea9ba21 content::RenderFrameImpl::InitializeAsChildFrame()
#21 0x56117b7e9c22 blink::WebLocalFrameImpl::CreateChildFrame()
#22 0x56117b811891 blink::LocalFrameClientImpl::CreateFrame()
#23 0x56117b9ee521 blink::HTMLFrameOwnerElement::LoadOrRedirectSubframe()
#24 0x56117cbd7fe7 blink::HTMLFrameElementBase::OpenURL()
#25 0x56117cbd88fa blink::HTMLFrameElementBase::SetNameAndOpenURL()
#26 0x56117cbd8a42 blink::HTMLFrameElementBase::DidNotifySubtreeInsertionsToDocument()
#27 0x56117b06d0db blink::ContainerNode::DidInsertNodeVector()
#28 0x56117b06db35 blink::ContainerNode::AppendChild()
#29 0x56117b24c30b blink::Node::appendChild()
#30 0x56117d5fb4c2 blink::(anonymous namespace)::v8_node::AppendChildOperationCallbackForMainWorld()
#31 0x56116e1d5af6 v8::internal::FunctionCallbackArguments::Call()
#32 0x56116e1d3caf v8::internal::(anonymous namespace)::HandleApiCallHelper<>()
#33 0x56116e1d15d7 v8::internal::Builtin_Impl_HandleApiCall()
#34 0x56116e1d1058 v8::internal::Builtin_HandleApiCall()
#35 0x3cbb079f517f <unknown>
  r8: 00000a28002d1403  r9: 0000000000000000 r10: 00007fb1585e2ac0 r11: 00007fb1585e33c0
 r12: 00007fffe727b610 r13: 000056117d5fb030 r14: 00007fffe727b500 r15: 00000a2800478000
  di: 0000000000000000  si: 0000000000000000  bp: 00007fffe7279090  bx: aaaaaaaaaaaaaaaa
  dx: 0000000000000018  ax: 0000000000000000  cx: 0000000000000001  sp: 00007fffe7279080
  ip: 00005611690cbd95 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
```

### Actual Behavior

renderer crashes when using a debug build to load the application. Testing and Release builds load it fine.

### Additional Information

related to #34923

**Comment by MichaelBelousov** [comment] 2022-07-19 15:25
I tried breaking on `base::debug::CollectStackTrace` and `base::debug::*anonymous*::StackDumpSignalHandler` and still couldn't break on it

**Comment by ckerr** [comment] 2022-07-19 17:51
Hey @MichaelBelousov, 

I agree there's something going on here, but before either of us bangs our heads against this stacktrace too much, do you mind if I ask what the goal is for doing this in 17.4.10?

The crash you're seeing is in Blink, and since 17 is based on Chromium 98.0.4758.141 while 19 is based on Chromium 102.0.5005.148, I think it would be worthwhile updating to see if the problem has solved itself. Maybe the problem is still in 19; but even if it is, that would also be worth knowing...

**Comment by MichaelBelousov** [comment] 2022-07-19 20:44
pulled and rebuilt main, `electron --version` now says: `v21.0.0-nightly.20220719`, but I get stack smashing even with the flag, will need to try a few more things

**Comment by MichaelBelousov** [comment] 2022-07-19 21:18
did the flag change? I can't find the docs for it. stack smashing occurs even in the default app without specifying an entry js file

**Comment by MichaelBelousov** [comment] 2022-08-15 14:14
@ckerr is the "blocked/need-info" flag still valid?

**Comment by chase** [comment] 2022-10-16 09:32
This also occurs on 20-x-y @ cbe1debbe. @MichaelBelousov were you able to make any further progress on this?

---

In my case, I was trying to check locals in a frame during a segfault, but for some reason even with `gdbinit` setup correctly per the Chromium developer docs they didn't display. My first thought was that I needed to make a developer build, unfortunately this is where I ended up.

**Comment by MichaelBelousov** [comment] 2022-10-18 23:00
I wasn't @chase but I also just sent `symbols_level = 2`

**Comment by RaisinTen** [comment] 2022-10-19 05:07
IIUC, this issue is an extension of https://github.com/electron/electron/issues/34923. If that's true, I'd suggest closing this and going through https://github.com/electron/electron/issues/34923#issuecomment-1283435123. I'd highly appreciate it if someone could spend some time to figure out where the bug is and perhaps send a fix.

**Comment by codebytere** [comment] 2023-01-05 13:06
Closing in agreement with https://github.com/electron/electron/issues/34977#issuecomment-1283436545

**Closed by codebytere** 2023-01-05 13:06 UTC
Labels: platform/linux, crash :boom:, blocked/need-info ❌, bug :beetle:
