### ISSUE TITLE
Inconsistent Tray Blur

### ISSUE THREAD

**Issue by Hsaylor** [electron/electron#8600] opened 2017-02-06 19:36 UTC
* Electron version: electron v1.4.15
* Operating system: mac OSX 10.11.6

I'm building a tray app, however I seem to be running into inconsistent behavior with how the app blurs when I click on other tray items. I expect that when I click on another tray item, that tray item should become focused while the previous app should become blurred. Sometimes this behavior is exhibited. However, other times it is not.

For example when clicking on Adobe's tray app, my electron tray app blurs
![traycaptureadobe](https://cloud.githubusercontent.com/assets/11164750/22658045/587c479c-ec5e-11e6-9e3e-65f94fe131f6.gif)

However when clicking on other apps, like power level, the blur doesn't occur
![traycaptureimproper](https://cloud.githubusercontent.com/assets/11164750/22658228/03eec262-ec5f-11e6-9670-5ebdd7b0ca7b.gif)
This behavior happens with the wifi, bluetooth, and airPlay tray apps as well.

### How to reproduce
Create a window that captures focus and blur events

```
mainWindow = new BrowserWindow({width:300, height:400, frame: false, show: false, resizable: false})
mainWindow.on('focus', logFocus)
mainWindow.on('blur', logBlur)

function logFocus() {
  console.log("focus!")
}

function logBlur() {
  console.log("blur")
}
```

Click other tray icons

### Other information

This is similar to #7759, however window levels are not at all the solution here. I can change the window level to `screen-saver`, but all that will do is keep my app's window on top of the other app; no blurring occurs.  I somewhat suspect this inconsistency has something to do with how menus and windows interact.

**Comment by MarshallOfSound** [comment] 2017-02-07 09:23
@Hsaylor I have noticed this as well, it appears to be something special about the Creative Cloud app as it only affects that icon / is caused by that icon.

You can also see interesting behavior if you have multiple screens the Creative Cloud icon doesn't fade out with the rest of the tray icons when you move focus between screens.

These issues could be caused by something the Creative Cloud is doing

**Comment by groundwater** [comment] 2017-02-09 23:44
Thanks for the report @Hsaylor. Is the behavior consistent across the various tray icons? i.e. does clicking Adobe CC always cause the same behavior?

I wonder if we can identify the tray items that are giving incorrect behaviors.

**Comment by zeke** [comment] 2017-03-08 18:40
@Hsaylor take a look at https://github.com/electron/electron/issues/8689, in which user @pronebird shares a module they created to address this problem.

**Comment by zcbenz** [comment] 2017-06-06 06:03
I'm closing this since #8689 provided a solution.

**Closed by zcbenz** 2017-06-06 06:03 UTC
Labels: component/tray, platform/macOS, triage/bug
