### ISSUE TITLE
[Feature Request]: Electron/vuejs app not loaded by setting "Always on top"/ uiAccess true

### ISSUE THREAD

**Issue by jvarchana** [electron/electron#34934] opened 2022-07-16 04:08 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Issue : Electron/vuejs app not loaded by setting "Always on top"/ uiAccess true

I want to use electron to develop an app to show above lock screen. I need to set my window alwaysOnTop and set the uiAccess of the exe as true.
 The exe can load index.html successfully without uiAccess change, but when I change the uiAccess to true, the exe can only create a window but the 
 window is blank, sometimes it's white while sometimes it's black.I tried to log some event and found that the crashed event was triggered if 
 I open the exe with non-Administrator. If I open the exe with administrator,the 'did-finish-load' was triggered but the window is black, didn't 
 show my index.html. How can I fix this?

Steps followed:

1.After installation of NodeJS
2.Created a sample application using the following commands

https://itnext.io/electron-application-with-vue-js-and-vuetify-f2a1f9c749b8

=> npm install -g @vue/cli
=> vue --version
=> vue create sample-electron-app
=> cd sample-electron-app
=> npm run serve
=> vue add vuetify
=> npm run serve
=> vue add electron-builder
=> npm run electron:serve

3.Builded electron exe using command  - npm run electron:build
4.Installed the sample application and placed the bin files under 
"C:\Program Files\sample-electron-app"
5.Created the manifest file for the sample-electron-app.exe using mt.exe
mt.exe -inputresource:"..\sample-electron-app.exe";#1 -out:"..\manifest.xml"
6.Updated the uiAccess="true" in manifest.xml file 
<requestedExecutionLevel level="asInvoker" uiAccess="true"></requestedExecutionLevel>
7.Embedded the manifest file to executable using following command
mt -manifest "..\manifest.xml" -outputresource:"..\sample-electron-app.exe";1
8.Created the the sample certificate using visual studio and digitally signed using the signtool.exe
signtool.exe sign /as /fd sha256 /tr http://timestamp.comodoca.com /td sha256 /f "..\samplecertificate.pfx" /p @1234 "..\sample-electron-app.exe"
=> Open sample-electron-app.exe properties under Digital Signatures tab
=> Select the signature under signature list and  view certificate and click install
=> Select local machine
=> Select Place all certificates in the following store and browse Trusted People and Click Finish.

9.Open the properties of sample-electron-app.exe and in the compatibility tab ->settings ->Check [run this program as administrator]
10.Now Launch the application as run as administrator.
11.**Application launch successfully but entire application is white /blank screen.**
![image](https://user-images.githubusercontent.com/100353987/179338672-f509c9f2-8574-4951-9c6c-c6153bf103eb.png)

### Proposed Solution

Electron app must be able to launch with all administrator rights.

### Alternatives Considered

 I open the exe with non-Administrator. If I open the exe with administrator,the 'did-finish-load' was triggered but the window is black, didn't 
 show my index.html. How can I fix this?
![image](https://user-images.githubusercontent.com/100353987/179338659-94a9a6ef-0e17-48a2-97f3-b50a4b23a016.png)

**Comment by ckerr** [comment] 2022-09-16 16:05
Hi @jvarchana,

Electron's team is pretty small and usually doesn't have the bandwidth to triage issues that depend on 3rd party tools e.g. Vue. Would it be possible for you to create a standalone [Electron Fiddle](https://github.com/electron/fiddle)  to demonstrate this that doesn't rely on Vue?

Also, to jump over to another part of this issue:

> Electron app must be able to launch with all administrator rights.

Are you sure this is what  you want? GUI apps should rarely be run with admin rights because of their intrinsically large surface area, and that's doubly true for web browsers.

**Comment by hpateljc** [comment] 2022-12-21 15:48
@jvarchana Did you able to solve this problem somehow ? I am also facing same issue with uiAccess application.

**Comment by phuong74200** [comment] 2023-03-27 03:56
I was able to fix it by:

1. Right click on the "sample-electron-app.exe" choose "Properties"
2. Choosing the "Compatibility" tab
3. In the "Compatibility mode" section check the "Run this program in compatibility mode for:" and select for "Windows 7"
4. Click "Apply" to confirm the changes
5. Right click on the "sample-electron-app.exe" and select "Run as administrator"

_In the step 2 and 3 don't check the "Run this program as an administrator" inside the "Settings" section. You must right click and select "Run as administrator"_

**Comment by ckerr** [comment] 2023-03-28 18:10
I'm closing this ticket based on the lack of a response & lack of a way to reproduce this issue in standalone Electron; e.g. in this case, without Vue.

If anyone has information that this is a bug in Electron's code and has either a repro testcase or other actionable information that a maintainer can use to reproduce the issue without third-party tools, please open a new bug and let us know.  Thank you!

**Closed by ckerr** 2023-03-28 18:10 UTC
Labels: enhancement :sparkles:
