### ISSUE TITLE
Preload script's process.mainModule points to Electron's renderer/init.js when loading from custom buffer protocol

### ISSUE THREAD

**Issue by smotaal** [electron/electron#12163] opened 2018-03-08 00:02 UTC
* Electron version: 2.0.0-beta.2
* Operating system: macOS High 10.13.3 (17D102)

### Expected behavior

I believe this issue is essential in order to gear Electron towards a friendlier NodeJS ES modules experience (using the 'internal/loader/Loader').

Specifically for preload scripts, `process.mainModule` or some other (maybe new) Electron-specific feature should always be a point of reference to an application module. This is currently the case when using `win.loadFile()` but not when using `win.loadURL()` (at least with custom protocols as tested) where `process.mainModule` seems to point to Electron's 'renderer/init'.

I make a distinction between preload and the actual page because `process.mainModule` in the actual page can be different (or even nonexistent if isolated, sandboxed... etc) in which case preload scripts may not only need to `require(…)` relative to their path but also `process.mainModule.require(…)` relative to some determination of what that path would be in the application's world.

So I would expect in preload to have (something like or the actual) `process.mainModule` where if loadFile and loadURL were used to load "./index.html" relative to the app's main, this mainModule object would be identical instances of a traditional node Module, from which we can require 'electron', './lib/cjs.js' and './vendor/module-x' (for folders with node-compliant package.json).

This would make it possible (still experimental but promising) to actually create an instance of Node's loader that can be used to load pure ES modules and very soon (tested in NW.Js) can even be hooked into chromium's **dynamic import** mechanism (with no impact on static imports).

I don't know if this is a feature request or a bug, but the inconsistency is hopefully not "working as intended", and not having a mechanism to associate pages with ambiguous URL's to a path in the application-world makes me wonder if this is more like a feature request or something of the sort.

### Actual behavior

Using `win.loadFile('./index.html')`: **good**
```js
window.location.href = "file:///[…]/index.html"

window.origin = "file://"

process.mainModule.filename = "/[…]/index.html"
```

Using a custom buffer protocol and `win.loadURL('app://./index.html')`: **not good**
```js
window.location.href = "app://./index.html"

window.origin = "app://."

process.mainModule.filename = "/[…]/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/init.js"
```

### How to reproduce

Since this is not a testable issue the only thing that comes to mind to include is a gist on the basic setup of the custom protocol used:

https://gist.github.com/smotaal/f1e6dbb5c0420bfd585874bd29f11c43

So this is specific to using a custom buffer protocol (I assumed a custom file protocol would prevent loading modules so I did not test that but willing to do if you indicate otherwise).

**Comment by zcbenz** [comment] 2018-03-12 03:03
The problem is it is impossible to get the filesystem path from a custom protocol. While many people are serving files from filesystem for the custom protocols, it is entirely possible that they are also generating strings dynamically.

The only solution to this is to change the `mainModule.filename` in the preload script:

```js
const parsed = url.parse(window.location.href)

process.mainModule.filename = __filename = path.join(process.resourcesPath, parsed.path)
```

I'm closing this since the request is not possible by default, and there is a way to work around it.

**Closed by zcbenz** 2018-03-12 03:03 UTC
Labels: platform/macOS, version/2.0.x

**Comment by smotaal** [comment] 2018-03-12 11:35
@zcbenz I just have to point out that the current patching done to the module system in Electron compared to the base NodeJS `internal/module` is introducing a lot of inconsistencies when attempting to use `internal/loader/Loader`.

Sadly, we all have grown too comfortable with how the conventional module subsystem works, and the fact that the new module subsystem is not simply an extension of the old means that such conveniences like simply changing a Module object do not influence the `internal/loader/Loader`.

From my testing, it seems that Electron's bootstrapping breaks the loader's ability to `import electron from "electron"` which might be the result of a single line in your bootstrapping or more (not ready to make an educated guess).

Down the road, I think Electron will need to address this issue here and others to support Node's new  module system.

**Comment by fish520** [comment] 2018-06-23 11:05
That's wired, I've met the same problem, If I used the ESM in electron, I've to use the custom protocol, but node module can't be resolved, or if I use the file protocol, I can't use the ESM, oops ...

**Comment by fish520** [comment] 2018-06-23 11:28
@zcbenz I don't understand much how 'generating strings dynamically' interfere with node modules, just like what node adopted, the '.mjs' extension can be used to specifically indicates a node module, it's the user's decide, and if the `process.mainModule.filename` being the path of host html document, things will be easier.
