### ISSUE TITLE
Possibly slow webview loading

### ISSUE THREAD

**Issue by zurajanai** [electron/electron#6751] opened 2016-08-05 21:16 UTC
* Electron version: v1.3.2
* Operating system: Windows 10

Hello,
I really like Electron, and I'm trying to use it in a new project.
I'm not really sure if this is a real issue or not, but it seems to me that the `webview` loading time is a bit too slow.

Here is a minimal code to reproduce my issue:
`index.html`

```html
<button id="create">New webview</button>

<script>
document.getElementById('create').addEventListener('click', () => {
  let view = document.createElement('webview')
  view.setAttribute('nodeintegration', true)

  console.time('start')
  console.time('end')
  view.addEventListener('did-start-loading', () => {
    console.timeEnd('start')
  })

  view.addEventListener('did-finish-load', () => {
    console.timeEnd('end')
  })

  view.src = 'file:///hello.html'

  document.body.appendChild(view)
})
</script>
```

`hello.html` is just:
```html
<h1>Hello world</h1>
```

The `end` time is hovering around `500ms` (the `start` event is around `20-30ms`) and it seems a bit too slow for loading a super small local file. `about:blank`'s loading time is similar to this. The same thing with an `iframe` loads in about `25-30ms` (but I need the separate process that comes with the webviews). It does not seem to matter if `nodeintegration` is on or off.
My laptop has a fast SSD, core i7, and plenty of RAM.

Did I miss something? Or is it possible to make this faster, like preloading files, pooling webviews before using them, or something along the line?

Thanks.

**Comment by MarshallOfSound** [comment] 2016-08-06 14:49
>  I need the separate process that comes with the webviews

I think you hit the nail on the head there.  Without much testing (or even trying to reproduce your times) that time you notice is almost certainly the WebView process launching.

**Comment by zurajanai** [comment] 2016-08-06 14:53
That was my first guess too. But does it start a brand new process even when I change the url for example from `file:///hello.html` to `file:///foo.html`?

**Comment by MarshallOfSound** [comment] 2016-08-06 14:59
My understanding is it doesn't make a new process, but it does destrory and recreate the `webContents` each time.

**Comment by zurajanai** [comment] 2016-08-06 15:14
Hmm, looking at the `webContents` documentation it really seems quite vast, so that might be the cause my 'issue'. But then I think this is expected and not a bug or something that can be changed.
Thank you for your response!

**Comment by MarshallOfSound** [comment] 2016-08-06 15:19
@zurajanai FWIW I just tested your code on a fresh Electron download of `1.3.2` and I don't get anywhere near `500ms`

```
start: 13.137ms
end: 142.403ms
```

So something else *may* being going on, but I doubt it.

**Comment by zurajanai** [comment] 2016-08-06 16:02
Did you test it on Windows 10? Maybe Windows related, or I'm not sure. `~150ms` sounds much more acceptable to me.

**Comment by MarshallOfSound** [comment] 2016-08-06 16:04
@zurajanai I am on Windows 10

**Comment by zurajanai** [comment] 2016-08-06 16:38
Then most likely this can be closed, because it's something about my system that slows things down.
Thank you for taking the time to test this for me. And sorry for the false alarm.

**Comment by zcbenz** [comment] 2016-08-08 07:40
Closing since it is not caused by Electron's side.

**Closed** 2016-08-08 07:40 UTC

**Comment by boneyao** [comment] 2016-11-04 12:59
2000ms+

**Comment by boneyao** [comment] 2016-11-04 13:05
I just test a simple example 2000ms+;
Webview tag  spend time more than iframe;
I suggest you use iframe
@katsura-da
