### ISSUE TITLE
[Bug]: node_modules/electron/dist/electron exited with signal SIGSEGV

### ISSUE THREAD

**Issue by AgTech930** [electron/electron#41980] opened 2024-04-27 08:57 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.1

### What operating system are you using?

Ubuntu

### Operating System Version

20.04.1-Ubuntu

### What arch are you using?

x64

### Expected Behavior

I wish to ensure that the Electron application runs smoothly.

### Actual Behavior

An issue arises upon initiating the Electron script.
/home/gaurav/Downloads/op/op-1.1/ui/node_modules/electron/dist/electron exited with signal SIGSEGV

### Additional Information

This is my code 

```
const {app, BrowserWindow, crashReporter} = require('electron');
const { spawn } = require('child_process')
const path = require('node:path');

let mainWindow


function createWindow() {
    mainWindow = new BrowserWindow({
        width:800,
        height:600,
    });
    
    mainWindow.loadFile("index.html");
    mainWindow.maximize();
    mainWindow.removeMenu();
    
    mainWindow.on('closed', function(){
        app.quit()
    });
}

app.whenReady().then(() => {
    createWindow();
    console.log(app.getPath('crashDumps'))
    crashReporter.start({ submitURL: '', uploadToServer: false })

});
```

**Comment by clavin** [comment] 2024-04-29 21:53
Closing as a duplicate of #41839

**Closed by clavin** 2024-04-29 21:53 UTC
Labels: bug :beetle:

**Comment by Nantris** [comment] 2024-05-08 21:46
I don't believe this should be closed. #41839 mentions maximizing is required to trigger it - but we cannot start our app at all due to this error (and it does not start maximized)

**Comment by KernelPanic0** [comment] 2026-02-09 17:38
For anyone else that might be reading this in the future this most likely happens because of Wayland compositor incompatibility. My issue had nothing to do with resizing or maximizing the window, I just couldn't create one. What fixed the issue for me was forcing X11 backend by adding `--enable-features=UseOzonePlatform --ozone-platform=x11`
