### ISSUE TITLE
[Bug]: Error unable to load preload.js when using sandbox mode

### ISSUE THREAD

**Issue by tmotagam** [electron/electron#32280] opened 2021-12-23 16:56 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

The preload.js file should run without any issue when sandbox is enabled

### Actual Behavior

when the sandbox flag or the app.enableSandbox() is used the preload.js file is unable to load.

But when I disable the sandbox mode the preload.js file loads without any issue

![Screenshot 2021-12-22 213503](https://user-images.githubusercontent.com/63451837/147270059-be626035-c4e7-4e87-88b7-df5829f3f869.png)

here is the code

javascript `
import { app, BrowserWindow, nativeTheme } from 'electron'
import path from 'path'
import os from 'os'

// needed in case process is undefined under Linux
const platform = process.platform || os.platform()

try {
  if (platform === 'win32' && nativeTheme.shouldUseDarkColors === true) {
    require('fs').unlinkSync(path.join(app.getPath('userData'), 'DevTools Extensions'))
  }
} catch (_) { }

let mainWindow

function createWindow () {
  /**
   * Initial window options
   */
  mainWindow = new BrowserWindow({
    icon: path.resolve(__dirname, 'icons/icon.png'), // tray icon
    width: 1000,
    height: 600,
    useContentSize: true,
    kiosk: true,
    webPreferences: {
      allowRunningInsecureContent: false,
      nativeWindowOpen: false,
      contextIsolation: true,
      enableRemoteModule: false,
      nodeIntegration: false,
      nodeIntegrationInWorker: false,
      nodeIntegrationInSubFrames: false,
      safeDialogs: true,
      webSecurity: true,
      webviewTag: false,
      // More info: /quasar-cli/developing-electron-apps/electron-preload-script
      preload: path.resolve(__dirname, process.env.QUASAR_ELECTRON_PRELOAD)
    }
  })

  mainWindow.loadURL(process.env.APP_URL)

  if (process.env.DEBUGGING) {
    // if on DEV or Production with debug enabled
    mainWindow.webContents.openDevTools()
  } else {
    // we're on production; no access to devtools pls
    mainWindow.webContents.on('devtools-opened', () => {
      mainWindow.webContents.closeDevTools()
    })
  }

  mainWindow.on('closed', () => {
    mainWindow = null
  })
}

app.enableSandbox()

app.whenReady().then(createWindow)

app.on('web-contents-created', (_, contents) => {
  contents.on('will-navigate', (event, url) => {
    console.log(`[will-navigate] ${url}`)
    console.log(event)
    event.preventDefault()
  })
  contents.on('will-redirect', (event, url) => {
    console.log(`[will-redirect] ${url}`)
    console.log(event)
    event.preventDefault()
  })
})

app.on('window-all-closed', () => {
  if (platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (mainWindow === null) {
    createWindow()
  }
})

`

### Additional Information

I am using quasar v 2.0.0 electron mode when the webpack transpiles the preload.js file without the sandbox flag there is no issue during dev mode or during production but if I use the webpack and sandbox flag the issue appears

I raised the issue on the quasar and they are saying that the issue is in the electron.

thanks.

**Comment by codebytere** [comment] 2022-01-05 20:28
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by tmotagam** [comment] 2022-01-06 14:16
@codebytere The problem is that without quasar framework the error is not there. The electron acts weird when the quasar uses webpack for the preload.js file.
I have also done some research and found that the while the electron gives me that error the preload.js file somehow is loaded by the electron and used properly.
So I cannot create a standalone test case
Thanks.

**Comment by codebytere** [comment] 2022-01-06 14:45
@tmotagam i see you said

> I raised the issue on the quasar and they are saying that the issue is in the electron.

but if the issue doesn't occur _without_ quasar then it's on them to demonstrate that it doesn't or show how it's our issue. Without more information we cannot proceed.

**Closed** 2022-02-12 00:57 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, 16-x-y
