### ISSUE TITLE
[Bug]: AudioRtpReceiver::OnSetVolume: No audio channel exists.

### ISSUE THREAD

**Issue by ngohuytrieu** [electron/electron#30434] opened 2021-08-06 09:16 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

7.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.5

### What arch are you using?

x64

### Last Known Working Electron version

7.1.1

### Expected Behavior

Macos app work well in webRTC call

### Actual Behavior

AudioRtpReceiver::OnSetVolume: No audio channel exists.

### Additional Information

I am building one macos app has webview loads an domain. In that webview use webRTC to make a call. But whenever I make a call i receive this issue `AudioRtpReceiver::OnSetVolume: No audio channel exists.`

**Comment by clavin** [comment] 2021-08-07 03:24
Thanks for taking the time to contribute!

I noticed that this is a duplicate of #23529. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by clavin** 2021-08-07 03:24 UTC
Labels: bug :beetle:
