### ISSUE TITLE
[Bug]: findNext not working properly

### ISSUE THREAD

**Issue by SoloEgo** [electron/electron#34490] opened 2022-06-09 14:54 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

When calling function
` win.webContents.findInPage(arg.searchText, { forward: true, findNext: true })` focus and highlight will move ti next founded result
like
![expected](https://user-images.githubusercontent.com/98180809/172875434-64f12b02-f86c-4ac0-8d6a-c8cf1ed1a1f2.gif)
 

### Actual Behavior

When i call it for first time it looks greate, it marks the results, but when i call it for next time nothing happens, focus is still on first result

![actual](https://user-images.githubusercontent.com/98180809/172876283-1ded8ba7-42c3-44e6-aabb-66ed0b8f0970.gif)

### Testcase Gist URL

https://gist.github.com/6d7ae1b803381a5206b4db1fea67d489

### Additional Information

I've tried to downgrade electron version till to 13~ but nothing happens, also tried it on Mac - same behavior

**Comment by SoloEgo** [comment] 2022-06-11 08:34
So, it seems to me that the problem in ipcMain, because if i run function in interval without ipcMain it works correctly
[](https://gist.github.com/9d67d46f37f9752e7bd33faab6bfd4e3)

**Comment by kkostalkowicz** [comment] 2022-08-17 11:02
Bump!
Problem persists in 2.0.2 under Linux and Windows@Wine (probably under real Windows as well).

What I can add is that the `found-in-page` event is sent correctly - it reflects what is happening on the UI.
So in the Expected Behaviour scenario you get events with increasing match number.
And in the Actual Behaviour scenario you get events with the same match number.

**Comment by SoloEgo** [comment] 2022-11-25 12:50
Bump!
21.3.1, 22.0.0.-bet8  - issue still there

**Comment by nornagon** [comment] 2022-11-29 23:13
I think what's going on here is that clicking the search button sets the caret position (i.e. selection) in the document, and find-in-page proceeds from the current selection position. Specifically see this comment in the Blink find-in-page code: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/find_in_page.cc;l=121-123;drc=2899fd9a2767ef605edff106d1e00ff45af08a2e

Chrome doesn't suffer from this problem because the find-in-page UI is not embedded in the page itself, so doesn't share selection state (in fact, it's implemented using Chrome's native UI toolkit, Views).

As a workaround, you can clear the document's selection before finding the next match with `window.getSelection().empty()`. That will cause Blink to go through the "increment match count" path instead of restarting the search from the current selection position.

**Comment by nornagon** [comment] 2022-11-29 23:14
I'm going to close this as this is a limitation of the underlying API, and not something we can fix in Electron.

**Closed by nornagon** 2022-11-29 23:14 UTC
Labels: bug :beetle:, platform/all, status/confirmed, has-repro-gist, component/webcontents, 19-x-y, 21-x-y, 22-x-y, 23-x-y

**Comment by nornagon** [comment] 2022-11-29 23:15
here's a modified version of your gist with this workaround: https://gist.github.com/1905bfe8f1d84ad12794f877baf00029

**Comment by SoloEgo** [comment] 2022-12-15 06:24
Great news!!! Thanks for the response! Your solution works really well, and that's what I was looking for.
