### ISSUE TITLE
-webkit-app-region: drag not working when DevTools opened

### ISSUE THREAD

**Issue by jbleuzen** [electron/electron#5732] opened 2016-05-27 08:06 UTC
* Electron version: 1.1.0 & 1.2.0
* Operating system: OSX El Capitan

When creating a BrowserWindow and enabling DevTools, `-webkit-app-region` is not working. If you close the DevTools, drag works as expected.
For info, it works great with 1.0.0...

Here's a small exemple : 

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        #top {
            -webkit-app-region: drag;
            position: fixed;
            top:0;
            right: 0;
            left: 0;
            bottom: 0;
            background: red;
        }
    </style>
</head>
<body>
    <div id="top"></div>
</body>
</html>
```

```js
const electron = require('electron')
const BrowserWindow = electron.BrowserWindow

electron.app.on('ready',() => {
    const win = new BrowserWindow({
        minWidth: 1024,
        minHeight: 600,
        frameLess: true,
        titleBarStyle: 'hidden-inset',
        show: true
    })

    win.loadURL(`file://${__dirname}/bug.html`)
    win.openDevTools()
})
```

Not a big bug, but it's annoying to have to close DevTools to move the windows...

**EDIT** :
Probably related to option : "titleBarStyle", as this code is working on Windows...

**Comment by danhp** [comment] 2016-05-27 12:30
Can reproduce in `1.2.0`
Happens only when the DevTools are docked.
Happens with any frameless window by setting either `titleBarStyle` or `frame: false`

**Comment by bbondy** [comment] 2016-05-27 12:57
I can also repro.

**Comment by samueleaton** [comment] 2016-05-27 14:59
If the dev tools are EVER opened then the `-webkit-app-region: drag` does nothing.  Event when i close the dev tools the drag is still not working.

I have my app set up to open dev tools if in development mode

```
if (process.env.NODE_ENV === 'development')
  renderer.toggleDevTools(); 
```
 which makes my app unusable in dev.

**Comment by CharlieHess** [comment] 2016-05-27 18:59
I can reproduce this in `1.1.3` without even opening DevTools. Simply creating a window with
```
titleBarStyle: 'hidden-inset'
```
Is enough; it's no longer draggable.

**Comment by samueleaton** [comment] 2016-05-27 19:01
@CharlieHess  that's with `-webkit-app-region: drag` in the css?

**Comment by CharlieHess** [comment] 2016-05-27 19:04
Ah, nevermind; @mnquintana clarified that `hidden-inset` should not have made the window draggable in the first place (although it previously did).

**Comment by kevinsawicki** [comment] 2016-06-01 22:05
Is this a duplicate of #3647?

**Comment by jbleuzen** [comment] 2016-06-01 22:22
Looks like it is yes...

**Comment by kevinsawicki** [comment] 2016-06-01 22:27
Closing this out here in favor of tracking it via #3647

**Closed by kevinsawicki** 2016-06-01 22:27 UTC
Labels: bug, devtools, osx

**Comment by winterbang** [comment] 2019-02-21 03:14
Maby u can try the way below:

>1. Click other spaces of ur desktop and make ur electron application **blur**
>2. Just drag ur electron application **without reactive**

It is working for me when i open devtools and wanna move the window of my electron application

**Comment by PhyllisWong** [comment] 2020-01-23 20:21
This has been bugging me for weeks. Thanks for the tip. The fix for me was to click my desktop to make Electron blur, then hold spacebar while dragging. I'm on a Mac.
