### ISSUE TITLE
Not able to add icon in browser window on Linux

### ISSUE THREAD

**Issue by Ajeey** [electron/electron#19667] opened 2019-08-07 13:40 UTC
### Issue Details

* **Electron Version:**
4.0.8

* **Operating System:**
Ubuntu - 16.04
RedHat 7.6
RedHat 8
  
* **Last Known Working Electron version:**
 None

### Expected Behavior
If provide an icon for the browser window, the icon should appear in the browser window's title bar

### Actual Behavior

The icon is not appearing in the browser window's title bar
### To Reproduce
```
mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    backgroundColor: "#074595",
    icon: __dirname + "/switzerland.png" // also tried with .icns, .ico
});

Icon is of the dimension 24x24
```

### Additional Information
The same code works in Windows platform.

Is this a limitation on Linux?

**Comment by vladimiry** [comment] 2019-08-07 16:27
I'd suggest trying the following code:
```
icon: require("path").join(__dirname, "switzerland.png")
```

**Comment by hovancik** [comment] 2019-08-08 12:59
I believe this works fine in my app: `icon: `${__dirname}/images/windowIcon.png`,`

**Comment by Ajeey** [comment] 2019-08-08 13:50
@hovancik on Ubuntu and Redhat?

**Comment by Ajeey** [comment] 2019-08-08 13:51
@vladimiry Thank you did try it, still no luck :(

**Comment by hovancik** [comment] 2019-08-08 13:55
I build with electron builder for different platforms, but my pcs are debian and ubuntu. I don't have it next to me right now but I can check later. (I was using electon 2 and now I am on 5/6)

**Comment by Ajeey** [comment] 2019-08-08 14:16
@hovancik If you can check on linux and let me know later (probably add a screenshot) that'd be great. Thank you in advance

**Comment by hovancik** [comment] 2019-08-10 11:10
@Ajeey my bad, you are maybe right: can't really tell because non of my applications in Linux have icons. I get icons in list of running apps

![image](https://user-images.githubusercontent.com/4745859/62821115-c1480f80-bb6f-11e9-98b2-daa29255ddc9.png)

**Comment by sudhakar3697** [comment] 2019-09-25 09:15
@Ajeey  
It depends on how you launch the app?

if you directly call electron with 'main.js' file like  ("electron main.js"), it doesn't work on Ubuntu.
Call it like "electron /dir/where/**package.json**/is/there/with/main/as/main.js/"
or navigate to the directory where package.json is present and do "electron ." (package.json should have main param with "yourBrowserWindowFile.js".

**Comment by sudhakar3697** [comment] 2019-09-25 10:07
@Ajeey  Check the icon size using file command

**Comment by electron-triage** [comment] 2020-02-19 20:35
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:19
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:19 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/linux
