### ISSUE TITLE
browserWindow.webContents.printToPDF() fails when used with await at the renderer.

### ISSUE THREAD

**Issue by benji0522** [electron/electron#17202] opened 2019-03-03 02:55 UTC
Electron Version:
4.0.6
Operating System:
windows 10 1803
Expected Behavior
It shd print using PrintToPDF() when requested from the renderer

Actual Behavior
Upon the print request everything freezes

To Reproduce
//RENDERER
await ipc.sendSync("ExecuteBackendFx", { fxName: "PrintToPDF", fxArgs: null });
//MAIN
global.PrintToPDF = async () => {
let out = await new Promise((resolve, reject) => {
mainWindow.webContents.printToPDF(
{
marginsType: 0,
printBackground: false,
printSelectionOnly: false,
landscape: false
},
function(error1, data1) {
fs.writeFile(rootDir + "/UI/Temp/print.pdf", (data1, error1) => {
resolve("Success");
});
}
);
}
});

return out;
}

Additional Information
It prints normally when the request comes from the backend directly.for eg calling the function directly from the debug on VSCODE

**Comment by MarshallOfSound** [comment] 2019-03-03 05:41
Closing as duplicate of #17171

**Closed by MarshallOfSound** 2019-03-03 05:41 UTC
