### ISSUE TITLE
[Bug]: small content in center when use slient: true

### ISSUE THREAD

**Issue by hothaifadev** [electron/electron#40913] opened 2024-01-08 09:41 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.6.0

### What operating system are you using?

Windows

### Operating System Version

21H2

### What arch are you using?

x64

### Last Known Working Electron version

21

### Expected Behavior

When I use silent:true it just gives me very small content in the middle
The same code and the same page when canceling silent: false gives me a correct result

### Actual Behavior

this happend when use silent: true
![image](https://github.com/electron/electron/assets/139741620/99df15d5-d30c-48fc-b181-8d7ccadcbdcf)

when silent: false
![image](https://github.com/electron/electron/assets/139741620/a5791a38-5c98-4c3c-9b41-3b1e0782d8da)

**Comment by hothaifadev** [comment] 2024-01-08 21:07
sorry this gist code for my problem
https://gist.github.com/ecc9cc515e70651f2e30b9bd3180ab3d

**Comment by victorcarablut** [comment] 2024-01-08 22:28
i can confirm the bug, same with latest electron version

**Comment by hothaifadev** [comment] 2024-01-09 12:32
i test some version
from v25 and latest version have a this bugs
v25.1 get me printing faild error
v25.5 same bug (small content)

v24 and less not a bug

**Comment by jkleinsc** [comment] 2024-01-10 21:29
- Closing as duplicate of #39179

**Closed by jkleinsc** 2024-01-10 21:29 UTC
Labels: platform/windows, component/printing, bug :beetle:, has-repro-gist, 25-x-y
