### ISSUE TITLE
Assertion failed: (err == 0), function uv_loop_delete, file ../../vendor/node/deps/uv/src/uv-common.c, line 661.

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#11243] opened 2017-11-24 09:53 UTC
Latest master, reproducible on Mac at least.
Started to happen after the Chromium 61 upgrade.

Run the "chromium feature > web workers > Worker has node integration with nodeIntegrationInWorker" test, there will be a log message in the console:
`Assertion failed: (err == 0), function uv_loop_delete, file ../../vendor/node/deps/uv/src/uv-common.c, line 661.`
Doesn't look good to me. The test passes though.

**Comment by codebytere** [comment] 2017-12-10 04:55
Looks like some thread locking happening here: we're getting back -16 as an error which corresponds to `UV_EBUSY`

**Comment by ckerr** [comment] 2017-12-12 21:59
Seeing the same issue on Ubuntu. The assertion failure triggers a crash with bare-bones backtrace:

```text
electron --type=renderer --js-flags=--expose_gc --no-s: ../../vendor/node/deps/uv/src/uv-common.c:661: void uv_loop_delete(uv_loop_t *): Assertion `err == 0' failed.
Received signal 6
#0 0x7f4482dfbecb base::debug::StackTrace::StackTrace()
#1 0x7f4482dfaa3c base::debug::StackTrace::StackTrace()
#2 0x7f4482dfb9b5 <unknown>
#3 0x7f447d3e2150 <unknown>
#4 0x7f4476fd70bb gsignal
#5 0x7f4476fd8f5d abort
#6 0x7f4476fcef17 <unknown>
#7 0x7f4476fcefc2 __assert_fail
#8 0x7f449619f151 uv_loop_delete
#9 0x000000d4cb15 atom::NodeBindings::~NodeBindings()
#10 0x000000d510d5 atom::NodeBindingsLinux::~NodeBindingsLinux()
#11 0x000000d510f9 electron --type=renderer --js-flags=--expose_gc --no-s: ../../vendor/node/deps/uv/src/uv-common.c:661: void uv_loop_delete(uv_loop_t *): Assertion `err == 0' failed.
Received signal 6
```

**Comment by ckerr** [comment] 2017-12-12 22:31
Yep the it's `UV_EBUSY`. Here's the assertion:

> void uv_loop_delete(uv_loop_t* loop) {
>   uv_loop_t* default_loop;
>   int err;
> 
>   default_loop = default_loop_ptr;
> 
>   err = uv_loop_close(loop);
>   (void) err;    /* Squelch compiler warnings. */
>   assert(err == 0);
>   if (loop != default_loop)
>     uv__free(loop);

and the docs for [`uv_loop_close()`](http://docs.libuv.org/en/v1.x/loop.html) read "Call this function only when the loop has finished executing and all open handles and requests have been closed, or it will return UV_EBUS"

**Comment by alexeykuzmin** [comment] 2017-12-12 22:39
@ckerr I would look for anything suspicious in our Node.js patches first.
For some reason I trust Node.js developers more than our changes )

**Comment by ckerr** [comment] 2017-12-13 23:18
Still happening after v8.9.3 update

**Comment by alexeykuzmin** [comment] 2017-12-14 00:36
@ckerr happens for the 9.2.1 too.

**Comment by ckerr** [comment] 2017-12-14 22:55
OK, so this seems to be reasonably straightforward. The problem is coming from this block of code:

```js
  let worker = new Worker(`../workers/worker_node.js`)
  worker.onmessage = function (event) {
    ipcRenderer.sendToHost(event.data)
    worker.terminate()
  }
```

The control flow is that `ipcRenderer.sendToHost` kicks off an async IPC call, then `worker.terminate()` is immediately called, which "[immediately terminates the Worker [and] does not offer the worker an opportunity to finish its operations](https://developer.mozilla.org/en-US/docs/Web/API/Worker/terminate)." -- ie the async IPC call is in an undetermined state. So it's plausible that libcc is handling `worker.terminate()` more aggressively than in older versions.

In testing, both of these changes removed the crash:

1. Removing the call to `worker.terminate()`

2. Replacing the call to `ipcRenderer.sendToHost()` with a call to a new synchronous variant, `ipcRenderer.sendToHostSync()`.

I'm leaning towards the second option as this does feel like a valid use case, but since it's new API in an area I'm just getting up to speed with, I thought I'd discuss here first and see if anyone objects.

NB: in the Thursday sync meeting I mentioned that I was also seeing the crash by hitting ctrl-c in the test application. That's only half correct; ctrl-c in the test app *does* crash but with a different trace, so that belongs in a separate issue. :boom:

**Comment by alexeykuzmin** [comment] 2017-12-14 23:53
Why calling `ipcRenderer.sendToHost()` affects shutting down of the worker thread?
It looks like calling the synchronous variant just creates a delay long enough for the loop to finish all the stuff and become ready to be deleted.

**Comment by ckerr** [comment] 2017-12-15 04:32
> Why calling `ipcRenderer.sendToHost()` affects shutting down of the worker thread?

`ipcRenderer.sendToHost()` is called by the Worker, so its local event queue gets asynchronous tasks added to it immediately before we terminate the Worker. I think that's why the we see uv_loop_delete() error out with EBUSY.

> Maybe calling the synchronous variant just creates a delay long enough for the loop to finish all the stuff and become ready to be deleted?

That's exactly what's happening, but by design rather than as a side-effect. We're saying "this worker should make this IPC call, and then when that's done, the worker should terminate."

**Comment by alexeykuzmin** [comment] 2017-12-15 09:35
> `ipcRenderer.sendToHost()` is called by the Worker

No, it's called by the parent page of the worker.
Worker itself ("workers/worker_node.js") only calls `self.postMessage([typeof process, typeof setImmediate, typeof global, typeof Buffer].join(' '))` and that's it.
That's why I don't understand how `ipcRenderer.sendToHost()` affects worker's shutdown and why removing the `worker.terminate()` call "fixes" the problem.

**Comment by ckerr** [comment] 2017-12-15 14:34
*grumble grumble* :smile:

**Comment by codebytere** [comment] 2018-01-10 23:31
solution merged!

**Closed by codebytere** 2018-01-10 23:31 UTC
Labels: chromium, fixme/bug, platform/linux/ubuntu, platform/macOS
