### ISSUE TITLE
Can't move window when titlebar is set to hidden

### ISSUE THREAD

**Issue by pb03** [electron/electron#13524] opened 2018-07-01 10:23 UTC
* Electron Version: 3.0.0-beta.1
* Operating System (Platform and Version): MacOS High Sierra (10.13.4)
* Last known working Electron version: 2.0.3  

**To Reproduce**
1. Add `titleBarStyle: 'hidden' as option while creating a new electron window
2. Add `-webkit-app-region: drag` style to the element by which the app window should move (header or whole body)
3. Run the app and try to move the app window

**Additional Information**
It works fine with the latest stable release (v2.0.3) but doesn't work with v3.0.0-beta.1

**Comment by javan** [comment] 2018-07-01 12:55
Duplicate of #13358

**Closed by javan** 2018-07-01 12:55 UTC
