### ISSUE TITLE
Lack of notification functionality

### ISSUE THREAD

**Issue by tom-james-watson** [electron/electron#7171] opened 2016-09-10 13:19 UTC
Hello,

I've been creating notifications with https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md#notifications-windows-linux-macos

Can someone please confirm what I suspect:

* There is no way to bind some kind of click handler to a notification, all clicking ever does it close the notification
* There is no way to add actions/buttons to a notification.

If these are true then I think as they stand, notifications are not very useful. If this functionality is not possible to implement, maybe it would be better to provide a standardised BrowserWindow implementation?

As an aside - can anyone recommend a third party package for implementing cross-platform rich notifications?

Thanks!

**Comment by MarshallOfSound** [comment] 2016-09-10 13:28
> There is no way to bind some kind of click handler to a notification, all clicking ever does it close the notification

I can confirm that (at least on windows) the below code works and the click event is firing.
```js
const test = new Notification('Hello World');
test.onclick = () => console.log('Clicked the thing');
```

> There is no way to add actions/buttons to a notification.

Currently there is no way to add actions to the Notification API provided by Electron.  The enhancement can be tracked in it's existing issue #4424 

Closing this out as a duplicate of #4424 as that appears to be the main/unresolved concern

**Closed by MarshallOfSound** 2016-09-10 13:28 UTC
