### ISSUE TITLE
Please, make printing work with Electron !

### ISSUE THREAD

**Issue by popod** [electron/electron#17523] opened 2019-03-23 14:07 UTC
### Problem Description

There are many printing problems since Electron 3 and this prevents people who need a working print solution to use Electron 3, 4 or 5 !

So please, can you take a look at all this **printings issues** and trying to fix it ? We are a lot of developers waiting for this since a long time..

Thanks a lot for your work ! And I hope you could give us some feedback about this.

cc: @codebytere @MarshallOfSound @nornagon 

### Related issues

All this issues seems related to `webContents.print()` which seems to be buggy:

- ~~#17265 `webContents.print()` callback always return `false`~~ :heavy_check_mark:
  - **Fixed since v5.0.5**
- ~~#16085 Fix callback for `webContents.print()` cancel event~~ :heavy_check_mark:
  - **Fixed since v5.0.5**
- ~~#18123 `'silent: true'` for printing not working in version 5~~
  - ~~#18858 `webContents.print()` doesn't respond when adding parameters~~
  - ~~#17670 Don't ask user for print settings.~~
  - ~~#16362 Silent print not working in mac/osX~~
  - **Fixed since v5.0.7**
- ~~#18980 Better callback value for `webContents.print()`~~
  - **Available since v7**
- ~~#18917 print blurring~~
  - **Fixed since v7** (by #18984 feat: add a series of new printing options)
- ~~`webContents.print()` doesn't work when `deviceName` is provided and `silent: true`~~
   - #17077, #17260, #18123,  #17077 

Other printing issues:

- #16813 Unable to print large documents in Electron 4, 5
- ~~#16534 `webview.print()` not working properly in 4.0.X~~
  - **Seems to be fixed since v5.0.5**
- #15847 `webContents.print()` random missing letters
- ~~#7849 Printing needs more options~~
  - ~~#15568 Add error information to `webContents.print()` callback~~
  - **Available since v7**
- ~#19056 Add an option to choose the paper format (size) on `webContents.print()`~
- #18093 `webContents.printToPDF()` regression in v5
- ~~#19108 Electron crashed after print~~
   - **Fixed by https://github.com/electron/electron/pull/19598**
   - Will be released in `v6.0.2` and `v5.0.10`

(Non-exhaustive list)

**Comment by mojason-81** [comment] 2019-04-12 14:47
Just thought I'd leave some more info here.  I'm having similar issues on v4.1.4 (and 4.0.x before).  The print dialog will open, but only intermittently.  It will open several times in a row, then not open for a while and maybe open again once or twice, but ultimately seems to stop opening altogether.

**Comment by baconbrad** [comment] 2019-05-01 20:00
This is out of my abilities to fix. I see it was self assigned by @brenca 2 weeks ago. I am just curious if there is any progress on these issues. Particularly in regards to using a `deviceName` and having `webContents.print()` work as expected. Until they are resolved my projects and many others will be blocked to Electron 3.X.X. I apologize I have nothing to contribute to these issues and I don't want this comment to come off as unappreciative nagging. I am just interested to see how they are coming along. Thank you.

**Comment by baconbrad** [comment] 2019-05-28 22:10
Just noticed this. https://github.com/electron/electron/blob/96b32a814ceda6818f7b9e1138f7468e7767cda2/patches/common/chromium/printing.patch

Looks like the issues are getting addressed. Thanks, @brenca!

**Comment by gozzoo** [comment] 2019-05-29 07:46
It doesn't seem so.  PR descrption says: 

> Fixes #18409

**Comment by popod** [comment] 2019-06-25 14:37
**Hooray !** It seems that printing problems with Electron will soon be only old memories!

Some problems have already been fixed in Electron `5.0.5` and others seem to be soon. Thanks to @codebytere for his work!

**Comment by JonaMX** [comment] 2019-07-01 16:05
I just tested `5.0.5` and silent print still not working

**Comment by codebytere** [comment] 2019-07-01 16:08
@JonaMX yes, that is expected. It has not been backported to that release line yet and remains in flight; if it had you would have been able to see it in the release notes.

**Comment by craftzdog** [comment] 2019-07-10 04:26
It still does not work in 5.0.6.
I tried `webview.getWebContents().print` as a workaround but did not work.
A print dialog properly opens but nothing is produced.
When I chose 'Save as PDF', it outputs an empty file.
`webView.printToPDF` does nothing.

**Comment by baconbrad** [comment] 2019-07-10 19:19
@craftzdog As expected. According to the releases notes this change was not pushed in 5.0.6.

**Comment by craftzdog** [comment] 2019-07-11 06:07
@baconbrad thx for letting me know. hope it will be pushed to 5.x soon!

**Comment by ebmbook** [comment] 2019-07-12 20:27
Just in case this helps someone, the only stable version which works with printing is v3.0.10.

**Comment by gozzoo** [comment] 2019-07-13 06:47
@ebmbook yes, it seems that the supposed fix has not been ported to any release branch.

**Comment by misbeliever** [comment] 2019-07-15 06:25
Same here stuck on v3 because silent printing still does not work correctly on any newer version.

**Comment by codebytere** [comment] 2019-08-08 04:00
@JonaMX https://github.com/electron/electron/releases/tag/v5.0.7 fixes silent printing.

https://github.com/electron/electron/pull/19598 was also recently merged and fixes a slew of issues, which you can test in https://github.com/electron/electron/releases/tag/v7.0.0-beta.2.

I'll be porting portions of that fix back as soon as i can for v6 and v5.

**Comment by JonaMX** [comment] 2019-08-08 15:28
Thanks @codebytere I'll test this out and let you know how it went.

**Comment by baconbrad** [comment] 2019-09-25 21:15
Just tested our POS with v6.0.10 and most everything works with the exception when we specify a `deviceName`. Just waiting for either the fixes for PR #19598 to make it to v6 or a stable release of v7. I appreciate the hard work of everyone that addressed the issues. Thank you! Looking forward to ditching v3 for good.

**Comment by barbalex** [comment] 2019-09-25 21:45
Don't know if this is the right place to add this but `printBackground: true` seems to be completely ignored inside `webContents.print`. 

It _does_ work when using `webContents.printToPDF`. This has been rather consistent for us since we use electron (v3).

**Comment by cxyao** [comment] 2019-10-14 08:05
We also meet the same problem @barbalex 
webContents.print { printBackground: true }  not work.
@codebytere @popod  could you help us ?

**Comment by shabeer-mdy** [comment] 2019-10-16 09:34
Hi .
is there any way to print bar code using this method

**Comment by seksitha** [comment] 2019-12-03 16:39
> @JonaMX [v5.0.7](https://github.com/electron/electron/releases/tag/v5.0.7) fixes silent printing.
> 
> #19598 was also recently merged and fixes a slew of issues, which y'all can test in [v7.0.0-beta.2](https://github.com/electron/electron/releases/tag/v7.0.0-beta.2)
> 
> I'll be porting portions of that fix back as soon as I can for v6 and v5.

I test the beta and it works. Thank you very much. no more printToPdf and say goodby to exec pdfToPrinter.exe with a long lagging. the process of printing the barcode label is fast now.

**Comment by codebytere** [comment] 2020-01-25 18:05
Hey folks - i still monitor this issue so if you see printing issues please amalgamate them here so i can continue to chip away at printing problems!

**Comment by barbalex** [comment] 2020-01-25 21:36
@codebytere how about https://github.com/electron/electron/issues/17523#issuecomment-535234212?

**Comment by codebytere** [comment] 2020-01-26 00:38
@barbalex i'll need some more info; what platforms is this occurring on? do you have a simple repro you know triggers the issue (ex. so i can be sure i'm testing with the config closest to the one you're having issues with)

**Comment by seksitha** [comment] 2020-01-26 14:24
I just had a recent bad experienced with windows 7 with Intel Celeron CPU. it takes 10+ seconds to spool the SVG barcode generated by [Jsbarcode](https://github.com/lindell/JsBarcode). I now in electron 8. My workaround is by using `printhtml.exe` by sending `HTML` string write it to file and print. Still not perfect for my printing job and that might be a deal-breaker to some people.

**Comment by barbalex** [comment] 2020-01-28 15:37
@codebytere 
Am have developed two electron apps so far. With all the electron versions since v2, up to 8beta. As far as I can remember this has always been the case but there were so many more important printing problems that I am not 100% sure.

I can see this in dev and prod mode on Windows 10 ans MacOS (whatever the newest version is).

Unfortunately I do not know how to build a simple repro.

**Comment by codebytere** [comment] 2020-01-28 16:53
@barbalex this unfortunately seems to be an issue with chrome itself; you can see this if you create a simple webpage:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <style>
      body {
        background-color: lightgreen;
        -webkit-print-color-adjust: exact;
      }
    </style>
  </head>
  <body>
    <h1>Hello World!</h1>
    <script>
    </script>
  </body>
</html>
```
and then open it in chrome and try to print it. That too is bereft of background colors.

**Comment by barbalex** [comment] 2020-01-28 17:49
@codebytere 

Yes, but:

1. You can tell Chrome in the print settings to print "Hintergrundgrafiken" (not sure what the name is that chrome uses in English).
2. You can set this value in css to force Chrome to print background-images (and -colors, I think):
```css
@media print {
  -webkit-print-color-adjust: exact;
}
```

**Comment by Hedwig188** [comment] 2020-02-26 03:29
I ran into an issue when calling `window.webContents.print(),` it just outputs an empty file in v5.0.7+window10.  I also tried to pass the options, but it didn't help. [window.webContents.printToPDF()](url) has the same issue. Here is my example code.
```
window.webContents.on('did-finish-load', function () {
			// Use default printing options
			window.webContents.print({}, function (response) {
				console.log(response);

			});
```
Is there any workaround for this for v5.0.7?

**Comment by gozzoo** [comment] 2020-02-26 09:56
@Hedwig188 I had this problem and it turned out that the events 'did-finish-load' and 'ready-to-show' sometimes come in different order.

I did it like this:

```
  let p1 = new Promise((resolve) => win.webContents.on('did-finish-load', resolve))
  let p2 = new Promise((resolve) => win.on('ready-to-show', resolve))
  Promise.all([p1, p2]).then(printCallback)
```

**Comment by Hedwig188** [comment] 2020-02-26 23:12
@gozzoo I tried your solution, but still got the empty file as the result.

**Comment by gozzoo** [comment] 2020-02-27 07:47
@Hedwig188 you may try saving the html before printing, to make sure that there is actually something ready to be printed. If the page contents gets generated dynamically it's quite possible that at the time those events get fired the page is still empty.

**Comment by jriffel** [comment] 2020-06-01 12:25
@codebytere - Thanks for your printing contributions ... seems like there was a mountain to climb here over the last few years.  

On Windows the option for printBackground is still ignored if you allow the user to select the printer.  If you print silent and specify the printer printBackground works as advertised.  Thankfully your comments above did provide me a workaround which allowed us to remove our own printer selection dialog to work around this:

```
body {
  -webkit-print-color-adjust: exact;
}
```

**Comment by yetianyue** [comment] 2020-09-10 05:39
> Just in case this helps someone, the only stable version which works with printing is v3.0.10.

Thx，At last it worked

**Comment by gozzoo** [comment] 2020-09-10 08:25
> Thx，At last it worked

@yetianyue what worked and what didn't work before that?

I'm also stuck with v.3.0 and just don't want to spend the time and energy to test if printing works with each new version. I've been keeping my hopes up for v.10. 

Has anywone tested printing with v10?

**Comment by orionlu0916** [comment] 2020-09-11 03:35
> > Thx，At last it worked
> 
> @yetianyue what worked and what didn't work before that?
> 
> I'm also stuck with v.3.0 and just don't want to spend the time and energy to test if printing works with each new version. I've been keeping my hopes up for v.10.
> 
> Has anywone tested printing with v10?

for my case, the current highest working version is 2.0.18

**Comment by squalle0nhart** [comment] 2020-10-21 04:08
> > Thx，At last it worked
> 
> @yetianyue what worked and what didn't work before that?
> 
> I'm also stuck with v.3.0 and just don't want to spend the time and energy to test if printing works with each new version. I've been keeping my hopes up for v.10.
> 
> Has anywone tested printing with v10?

I've tested with latest electron 10. Print functions working fine!

**Comment by jngbng** [comment] 2020-11-11 05:23
@gozzoo  I've tested with electron 10.1.5 and printing iFrame is still not working.

```javascript
document.querySelector("#print-iframe").contentWindow.print()
```

freezes after a print job is queue.

**Comment by SUH11** [comment] 2020-11-17 08:48
> @gozzoo I've tested with electron 10.1.5 and printing iFrame is still not working.
> 
> ```js
> document.querySelector("#print-iframe").contentWindow.print()
> ```
> 
> freezes after a print job is queue.

I have same problem in  electron 10.1.5 and mac

**Comment by lynxtaa** [comment] 2020-11-17 09:54
We've "solved" all printing issues by discarding electron printing altogether. 

1) By running [Gotenberg](https://thecodingmachine.github.io/) in Docker we can convert HTML pages to PDF. Also this method solves missing page numbers at the bottom of the page: https://thecodingmachine.github.io/gotenberg/#html.header_and_footer)
2) We pack our application with a PDF Printer. [SumatraPDF](https://www.sumatrapdfreader.org/docs/Command-line-arguments.html) in our case.

So when user clicks *Print* we convert HTML to PDF and just open resulted PDF in SumatraPDF. This solves [missing print preview issue](https://github.com/electron/electron/issues/4890).

Also we can print in silent mode by supplying `-silent` to SumatraPDF.

I know it's a very hacky solution but I hope it helps.

**Comment by ckerr** [comment] 2020-11-17 17:23
It looks like the issues in the description have all either been fixed by @codebytere or are referring to versions of Electron that are no longer supported. Moreover, a long-running thread with the topic "Please, make printing work with Electron !" is probably not the best place to report ongoing issues, so I'm going to close this issue.

Despite the overall vibe of this issue, the project _does_ take printing seriously. If anyone is still seeing issues in supported versions of electron -- currently 9, 10, and 11 -- then I encourage you to report them as standalone issues. Thank you!

**Closed by ckerr** 2020-11-17 17:23 UTC
Labels: bug :beetle:, component/printing

**Comment by ibalaji777** [comment] 2021-05-29 07:14
Electron missing font while print 

i tested electron **3.1.10 working perfecly in developement** 
but i am facing issue only in production

**Comment by baconbrad** [comment] 2021-06-04 21:46
@ibalaji777 3.X is too out of date. A fix will never be backported since it is unsupported. You will need to use a later version. Unfortunately later versions are having regression issues. 11.X is still in the support scope and seems to be working fine for most printing issues though.

**Comment by exander77** [comment] 2021-10-05 11:33
@baconbrad In what version it realiably prints? How to print PDFs as images?

**Comment by biswajit123** [comment] 2022-03-31 09:43
I have a problem when working with **win.webContents.printToPDF**, pdf is getting generated but the text (color) is getting faded instead of my css text color, it is looks like a Gray color text with some opacity. has anyone faced this kind of issue before ? Can you please share any solutions?

Thanks!!
