### ISSUE TITLE
[Bug]: Transparency not working on Windows or macOS

### ISSUE THREAD

**Issue by codebytere** [electron/electron#30135] opened 2021-07-14 16:07 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

v15.0.0-nightly.20210623

### What operating system are you using?

macOS

### Operating System Version

Big Sur

### What arch are you using?

x64

### Last Known Working Electron version

v15.0.0-nightly.20210622

### Expected Behavior

When `transparent: true` is set in BrowserWindow constructor options, the resulting window is transparent.

### Actual Behavior

It is opaque white, though the titlebar correctly does not show.

<img width="821" alt="Screen Shot 2021-07-14 at 9 06 06 AM" src="https://user-images.githubusercontent.com/2036040/125655542-e65369bf-28a5-4005-a333-5ae55effedfe.png">

### Testcase Gist URL

https://gist.github.com/b52f026c763057f97f745fade82758fd

### Additional Information

Bisected to https://github.com/electron/electron/commit/b8261f15916eb94428d5672716f85c56720b1501, and from within the Chromium roll to [this CL](https://chromium-review.googlesource.com/c/chromium/src/+/2695928)

**Comment by nornagon** [comment] 2021-07-14 17:39
Duplicate of #30082?

**Comment by codebytere** [comment] 2021-07-14 17:40
Oops, yeah!

**Closed** 2021-07-14 17:40 UTC
Labels: 15-x-y, bug :beetle:, component/BrowserWindow, platform/macOS, platform/windows
