### ISSUE TITLE
Setcookies throwing errors

### ISSUE THREAD

**Issue by notanark** [electron/electron#8181] opened 2016-12-11 09:47 UTC
* Electron version: 1.4
* Operating system: windows

### Expected behavior
After taking from cookies.get I should be able to use the same output to cookies.set

### Actual behavior
Error: Setting cookie failed
    at Error (native)

### How to reproduce

When a browser window closes I want to nab it's cookies and store them. I don't want to use your system because the user might want to export the cookies and use them on another machine. I'm developing something to allow people to browse on multiple machines using the same cookies.
```

function ChildBrowserClose(e) {
console.log(e.sender);
    e
        .sender
        .webContents
        .session
        .cookies
        .get({}, (error, cookies) => {
            e.sender.CustomSession.Cookies = JSON.stringify(cookies);
            var Sessions = app
                .Session
                .get('Sessions')
            Sessions
                .find({id: e.sender.CustomSession.id})
                .assign(e.sender.CustomSession)
                .value()
            console.log(error, cookies)
        });

}
```
-----------------------

later I try to set with

```
  for(var i=0;i<Cookies.length;i++){ 
            NewBrowser
                .webContents
                .session
                .cookies
                .set(Cookies[i], (error) => {
                    console.log(error);
                });
            }
```

Error: Setting cookie failed
    at Error (native)

**Comment by kevinsawicki** [comment] 2016-12-13 18:14
The `url` property is required for `cookies.set`.

I believe this is a duplicate of https://github.com/electron/electron/issues/4422

See https://github.com/electron/electron/issues/4422#issuecomment-182618974 for details on how to generate this property from the values returned from `cookies.get`.

**Closed by kevinsawicki** 2016-12-13 18:14 UTC

**Comment by notanark** [comment] 2016-12-13 18:16
Probably is, but if someone finds this and wants the answer: parse url from domain it works fine.  You may close
