### ISSUE TITLE
Menu doesn't work in 2.0.0-beta.1 on macOS

### ISSUE THREAD

**Issue by qazbnm456** [electron/electron#12007] opened 2018-02-22 05:38 UTC
* Electron version: 2.0.0-beta.1
* Operating system: masOS High Sierra 10.13.4 Beta (17E150g)

### Expected behavior

When I clicked one of the Menu Items, the click function should be triggered.

### Actual behavior

![image](https://user-images.githubusercontent.com/6451933/36522155-d97db440-17d5-11e8-80f2-53b1dc341041.png)

After clicking the menu item, nothing happened. However, I've tested on Window 10 and it worked fine.

### How to reproduce

Just clone https://github.com/qazbnm456/electron-quick-start and run.
When clicking the only entry on the context menu, there's no any message logged in the console panel.

**Comment by codebytere** [comment] 2018-02-22 16:23
@qazbnm456 this bug pre-exists `2.0.0`, closing as a duplicate of https://github.com/electron/electron/issues/11818

**Closed by codebytere** 2018-02-22 16:23 UTC

**Comment by qazbnm456** [comment] 2018-02-22 16:47
Oops, I didn't notice that. Thank you 😃
