### ISSUE TITLE
Downloaded electron app shortcut icon becomes question mark and unable to be executed after reboot

### ISSUE THREAD

**Issue by kmsheng** [electron/electron#9293] opened 2017-04-26 03:20 UTC
* Electron version: 1.6.2
* Operating system: macOS Sierra 10.12.3

### Expected behavior

I expected electron app shortcut to be shown as normal and able to be executed after reboot.

### Actual behavior

Electron app icon became question mark and unable to be executed after reboot.

### How to reproduce

Before reboot:
https://drive.google.com/file/d/0B7IngcS_Eo5Jd050QjJGc2Y0ZWc/view

After reboot:
https://drive.google.com/file/d/0B7IngcS_Eo5JNHNsbFltOEFQUEU/view

This issue only happens when the app is downloaded from internet.

**Comment by kmsheng** [comment] 2017-04-26 03:21
I don't know if this issue is related to apple's new policy or electron, so I post here to get some clues : p

**Comment by kmsheng** [comment] 2017-04-26 03:23
found a similar issue here https://github.com/atom/atom/issues/13695#issuecomment-294179983

**Comment by Hedinhiervard** [comment] 2017-05-02 06:26
Yeah, this happens for me for several Electron apps, including Atom, Discord, WhatsApp and some others. However, this happens for Airmail 3 which (I believe) is not an Electron app.
Symptoms are all the same: after `killall Dock` (or reboot) the icon of the app is question mark and doesn't work anymore. Removing it from the Dock and dragging back to Dock helps till the next reboot. Sometimes I observed two identical icons, one with light no (app running) both switching to app. After `killall Dock` one becomes question mark. 
Sometimes after I reboot I see the icon intact, however, when I click it, the **second** icon of the same app appears alongside the first one and starts jumping.
I'm running Sierra 10.12.5 Beta (16F67a), however, I was able with 10.12.3 & 4.
Right now it reproduces 99% of my reboots. I can run any tests you like.

**Comment by mhuusko5** [comment] 2017-05-16 13:06
Same here 👍

**Comment by colingourlay** [comment] 2017-06-01 06:50
@kmsheng This issue first appeared for me with Visual Studio code. It provides an option to install a command line shortcut "code" to launch the app with the current directory as a project folder; this command also disappears after a restart, which hints at a larger issue than just dock icons.

**Comment by mhuusko5** [comment] 2017-06-01 10:35
I have a launcher that launches/activates apps based on bundle ID, and that's not functioning properly for electron apps either. I feel like someone who works on electron should know exactly what's going on, because I suspect there has to be something very deliberate going on in electron to produce this not-a-single-stable-bundle behavior (my guess, something to do with updates, but idk).

**Comment by rainstormza** [comment] 2017-06-13 09:26
http://macappstore.org/atom-2/

`brew cask install atom`

solve the problem

**Comment by kmsheng** [comment] 2017-06-14 12:42
@rainstormza Would you explain a little more about how `brew cask install atom` solve this issue ? It's a little weird to convince my user to install an editor app to git rid of this question mark shortcut.

**Comment by rainstormza** [comment] 2017-06-14 14:01
@kmsheng  macOS Sierra didn't know path of atom that installed from drag and drop into Applications folder.

**Comment by zcbenz** [comment] 2017-06-20 08:18
Does it happen for the Chrome browser?

**Comment by kmsheng** [comment] 2017-06-20 09:49
@zcbenz no, I tried it. Chrome browser for mac is a dmg file that requires user to drag its executive program to ~/Applications

![screen shot 2017-06-20 at 5 39 53 pm](https://user-images.githubusercontent.com/880569/27327144-2d9d5fd4-55e0-11e7-92cf-05895f524cbc.png)

**Comment by MarqueIV** [comment] 2017-09-18 14:27
Same issue here on macOS 10.12.6 (Sierra) and VSCode 1.16.1 which uses Electron.  Download to 'Downloads', double-click to extract, drag to '/Applications', drag from '/Applications' to dock.  Icon appears.  Click on it, a second icon appears at the right end of the dock.  Click 'Keep in Dock' for that second icon and delete the first.  All good until reboot as when you do, the icons change to question marks.

Of course I can just leave the original icons in the dock, but then when I start VS Code, I get the second icon which is frustrating and clutters up the bar.

Of note: Right-clicking on either icon--the original or the second one that appears when you run the original--choosing 'Options', then clicking 'Show in Finder' both point to the same file, in '/Applications'.  To double-check this, I performed that for the first icon, then when it opened Finder showing the app, I clicked the app next to it.  I then performed 'Show in Finder' from the second icon and the selection changed back to 'Visual Studio Code.app' which was just added.

I'm starting to think this may have something to do with application policies.  While I am the only user on this machine, it's a corporate machine that restricts certain installs.  Obviously it didn't restrict the download and running of the app, but perhaps it's stopping VS Code (ergo Electron) from writing needed information on disk.  Not sure, but it's really frustrating.

**Comment by stevenreddie** [comment] 2017-09-22 11:29
I just started using VSCode and am hitting this same issue. I believe I've found the root cause, though I don't currently know of a fix...

Sierra has a security feature named AppTranslocation (aka Gatekeeper Path Randomization). For certain apps, even though it is installed into the /Applications folder, the app gets run from a randomized path. When keeping such an app in the dock, the path changes across app restarts and so the dock item references a non-existent location.

Here is the path stored for my dock, and note that it is the only such app on my machine:

```bash
$ defaults read com.apple.dock | grep private.var.folders
                    "_CFURLString" = "file:///private/var/folders/t8/slxfsjpj3_19s9rq06qxrr5c0000gn/T/AppTranslocation/A61041F6-42B1-44CF-A707-2947259109B7/d/Visual%20Studio%20Code.app/";
```

The first randomized part of the path ("t8/slxfsjpj3_19s9rq06qxrr5c0000gn") changes on reboot. The GUID changes each time the app is started.

Here is proof of the GUID change. Before I restarted VSCode just now:
```bash
$ ps -ef | grep Electron$
  501 12575     1   0  3:55AM ??         0:01.74 /private/var/folders/t8/slxfsjpj3_19s9rq06qxrr5c0000gn/T/AppTranslocation/AD0094A8-A202-4FC4-A193-4CD47EA87F47/d/Visual Studio Code.app/Contents/MacOS/Electron
```
And then after quitting and restarting:
```bash
$ ps -ef | grep Electron$
  501 12671     1   0  4:07AM ??         0:00.95 /private/var/folders/t8/slxfsjpj3_19s9rq06qxrr5c0000gn/T/AppTranslocation/4F0246D3-76AE-4FF3-8552-613BB6E2E811/d/Visual Studio Code.app/Contents/MacOS/Electron
```

**Comment by stevenreddie** [comment] 2017-09-22 11:49
I was able to resolve it just now by doing the following:

1. Quit VSCode (Cmd+Q) and remove any shortcuts pinned to the dock
2. In Finder, navigate to Applications
3. Select Visual Studio Code and move it to Desktop by dragging while holding Cmd
4. Repeat previous step in reverse to move it back to Applications
5. Run VSCode and pin it to the dock again

I verified that it had worked with the following command:
```bash
$ defaults read com.apple.dock | grep "Visual.*Studio.*Code.app"
                    "_CFURLString" = "file:///Applications/Visual%20Studio%20Code.app/";
```
Notice that the location references Applications rather than the /private/var/folders path in my previous comment.

**Comment by stevenreddie** [comment] 2017-09-22 11:59
Interestingly, the following attribute which is meant to cause this sandboxing is still present on my copy in the Applications folder, yet I'm not having an issue at the moment:

```bash
$ xattr -l /Applications/Visual\ Studio\ Code.app/
com.apple.quarantine: 01e1;59bcf17b;Google\x20Chrome;EED68288-14EF-4326-953F-F7B16B30FCE1
```

**Comment by BenGitsCode** [comment] 2017-09-27 15:15
Broken image all the way up to when I pinned it to the dock and then it appeared. 👍

**Comment by mixn** [comment] 2018-09-08 12:45
[This answer](https://github.com/electron/electron/issues/9293#issuecomment-331425878) provided by @stevenreddie was the **only** thing that helped me solve this annoying issue. Thank you so much, @stevenreddie! 👏

**Comment by mixn** [comment] 2018-09-10 15:12
@MarqueIV I have read your answer and am aware of it, this just isn’t the case for me. When I `brew cask uninstall <foo>`, then `brew cask install <foo>` and open the app, close it, then add it to the Dock, open it, close it, wait like 20s — it leads to a `?` on the next click. Only doing the `cmd` + drag thing, as suggested by @stevenreddie helps and solves the issue for me.

**Comment by MarqueIV** [comment] 2018-09-10 15:51
Do you get the security prompt when you uninstall/reinstall, then open it?  And are you dragging it to the dock *after* you've added it to the Applications folder?

**Comment by MarqueIV** [comment] 2018-09-10 15:57
I'm wondering if by my marking the app as safe, it turned off that location randomization issue, whereas you're installing it from brew, which doesn't, hence @stevenreddie's workaround working for you since that forces the path of the dock shortcut to be in the applications folder. (Again, not familiar enough with brew to speak to it.)

**Comment by mixn** [comment] 2018-09-17 23:32
@MarqueIV Whatever was causing the issue for me must have been wired to a fresh install of macOS and the very first opening of particular apps. Since I’ve done the drag-redrag thing, I haven’t had a single problem. Wonder if this will be the case after every wipe/new machine… 🤔 Would sure be annoying.

I unfortunately don’t install things manually, I do everything via `brew cask install`, so I’m sorry on that front. 

**But** I’m using [dockutil](https://github.com/kcrawford/dockutil) and [this initial script](https://github.com/mixn/dotfiles/blob/master/dockutil/install.sh) to set up my dock. When I run `dockutil --list` now, I get this:

<img width="1679" alt="screen shot 2018-09-18 at 01 28 33" src="https://user-images.githubusercontent.com/672237/45655817-64201700-bae2-11e8-818a-d3cc83c247eb.png">

Before doing the drag/re-drag fix, I didn’t get these clean paths for Hyper.app and Macdown.app (`file:///Applications/Hyper.app/`/`file:///Applications/Macdown.app/`), instead I got stuff like `/private/var/…`. Is that what you mean by this?

> I'm wondering if by my marking the app as safe, it turned off that location randomization issue, whereas you're installing it from brew, which doesn't, hence @stevenreddie's workaround working for you since that forces the path of the dock shortcut to be in the applications folder. (Again, not familiar enough with brew to speak to it.)

**Comment by codebytere** [comment] 2018-09-24 04:48
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 04:48 UTC
Labels: bug :beetle:, platform/macOS, version/1.6.x

**Comment by ryskin** [comment] 2020-05-05 12:33
I had same problem, this link helped me
https://discussions.apple.com/thread/8098050

**Comment by stevenreddie** [comment] 2020-08-02 11:14
@mixn @MarqueIV: Just letting you know that `brew install cask visual-studio-code` downloads the zipfile from Microsoft and installs from it, so it's the same issue in both cases.
