### ISSUE TITLE
How to use iCloud to sync with multiple devices?

### ISSUE THREAD

**Issue by LDubya** [electron/electron#22002] opened 2020-02-01 16:07 UTC
Hello,

This is more of a question than a bug report.

Is there documentation on how to use iCloud to sync data in Electron? (Preferably in a way that can be implemented using auto-save without user input)

I’ve searched the issues for any mention of iCloud and have also done a Google search. This seems like something that should have documentation since a desktop app may need to share data with a mobile app over iCloud.

**Comment by miniak** [comment] 2020-02-11 23:29
Thanks for taking the time to contribute!

We noticed that this is a duplicate of [Issue URL]. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by miniak** 2020-02-11 23:29 UTC

**Comment by LDubya** [comment] 2020-02-12 00:01
@miniak I’ve googled this and couldn’t find anything. In addition, you didn’t include the issue number that it’s a duplicate of.

**Comment by LDubya** [comment] 2020-03-02 01:41
Hi @miniak , just wanted to follow up on this. I'd like to find the issue that it's a duplicate of so that I can subscribe there for updates.

**Comment by idoodler** [comment] 2020-09-09 07:43
Any update on this? I also want to implement iCloud Sync

**Comment by LDubya** [comment] 2020-09-09 14:37
> Any update on this? I also want to implement iCloud Sync

he shut down the issue, never gave an actual link to the similar issue he was referring to (which doesn't come up in search), and then never responded after I replied twice asking for further clarification.

Thanks for bringing this back up. I'm seeing a lot of emoji reactions from different users. For future lurkers: if this is something that you're interested in adding to your Electron app, please drop a comment so you can be counted, and so we can continue the discussion.

**Comment by idoodler** [comment] 2020-09-09 14:44
@miniak May you please clarify your comment.

**Comment by evorts** [comment] 2020-12-30 05:38
up. I'd love to implement icloud sync as well. and solving this would be greatly helpful.

**Comment by streamliner18** [comment] 2022-06-13 06:18
Bringing this back up and we'd love to see some framework support on this.

**Comment by maheskrishnan** [comment] 2023-12-21 04:08
@miniak you didn’t include the issue number that it’s a duplicate of.

**Comment by maheskrishnan** [comment] 2023-12-21 04:15
Looks like @miniak is working for Microsoft.

**Comment by LDubya** [comment] 2023-12-21 19:10
I wish everyone giving an emoji reaction could also leave a comment. There are 21 downvotes in response to this issue being closed. However I doubt those downvotes get any attention.

**Comment by byshovets-dr** [comment] 2024-01-08 18:27
I'm also interested in the topic

**Comment by LDubya** [comment] 2024-01-22 18:54
@codebytere please see this comment thread. I would open a new issue, but I don't want to duplicate this one.

**Comment by ramesaliyev** [comment] 2024-08-07 19:02
Hey, any updates on this?

Other than meaningless copy paste template answer I mean.

**Comment by Jocs** [comment] 2024-09-29 10:21
Any updates on this issue?

**Comment by LDubya** [comment] 2024-10-04 00:51
@codebytere tagging you since you seem to be actively maintaining issues. Please take a look at this issue. You can tell by the number of downvotes to miniak's response that it was improperly closed.
