### ISSUE TITLE
Windows: electron does not start from a folder that has a leading #

### ISSUE THREAD

**Issue by bpasero** [electron/electron#10311] opened 2017-08-21 15:00 UTC
* Electron version: 1.7.6
* Operating system: Windows 10

### Expected behavior

Electron opens

### Actual behavior

Electron opens but does not show any contents.

### How to reproduce

1. download Electron
2. rename its folder to `# electron`
3. start it

**Comment by codebytere** [comment] 2018-09-24 05:27
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by bpasero** [comment] 2018-09-24 06:29
Still happens with 3.0.0.

**Comment by Kthulu120** [comment] 2018-10-02 22:34
@bpasero I can't seem to reproduce this on Windows 10 would you mind  perhaps forking [electron-quickstart](https://github.com/electron/electron-quick-start) so I can see exactly the setup needed to reproduce the error. For now I'll label this `needs-repro` until we can reproduce it. Thanks in advance!

**Comment by bpasero** [comment] 2018-10-03 04:28
@Kthulu120 all I do is literally download Electron, rename the folder to `# electron` and then clicking on `electron.exe`:

![image](https://user-images.githubusercontent.com/900690/46389949-79e22e80-c6d5-11e8-895e-5a2b752ad087.png)

**Comment by MarshallOfSound** [comment] 2018-10-03 05:03
@bpasero I know what this is and it shouldn't happen on actual Electron apps, we have a bug in the `default_app` code.

Basically whenever you call `loadURL` most people pass it something like this

```js
loadURL(`file://${path.resolve(__dirname, 'index.html')}`)
```

This will fail when there is a `#` in the path because the `#` will not be escaped and the path will be treated as a anchor tag.

E.g.

```
file:///Users/me/test/#myapp/index.html
```

Actually attempts to load `file:///Users/me/test` as the path with an anchor of `#myapp/index.html`

You should use `url.format` everywhere or the `loadFile` helper which does this for you.  See https://github.com/electron/electron/blob/master/default_app/main.js#L193 for an example of how we do it correct in the default_app.  There are other places we do it wrong though.

**Comment by bpasero** [comment] 2018-10-03 05:07
@MarshallOfSound awesome, thanks for the pointers, will see how we do it in VSCode

**Closed** 2018-10-03 15:10 UTC
Labels: blocked/needs-repro, bug :beetle:, platform/windows, version/3.0.x
