### ISSUE TITLE
Menu separator with visibility set to false fails on Windows

### ISSUE THREAD

**Issue by coreybutler** [electron/electron#6906] opened 2016-08-20 00:18 UTC
* Electron version: 1.3.3
* Operating system: Windows

I'm reopening this issue (see #3494). @zcbenz closed it, citing that macOS doesn't support hiding the separator. However; it seems to be working on El Capitan (10.11.16).

On OSX, I have a menu that collapses as shown (when a user disables SSL):

![image](https://cloud.githubusercontent.com/assets/770982/17827362/47bb24f8-6641-11e6-8448-44723a430413.png)

![image](https://cloud.githubusercontent.com/assets/770982/17827361/35dfbdfc-6641-11e6-9af6-f515d97dd09e.png)

On Windows, it looks like this:

![image](https://cloud.githubusercontent.com/assets/770982/17827418/341bb5ba-6642-11e6-8347-8c2e73d72975.png)

![image](https://cloud.githubusercontent.com/assets/770982/17827422/4d6d049c-6642-11e6-9cef-11d0beea1c65.png)

The code responsible for this action looks like:

```js
sslmenu.items.forEach((item) => {
  item.visible = assets.CA.enabled
})
```

Clearly, changing the visibility of a separator on OSX works while Windows does not.

**Comment by kevinsawicki** [comment] 2016-08-20 00:22
macOS does automatically remove leading and trailing separators, could that be what you are seeing?

**Comment by coreybutler** [comment] 2016-08-20 00:24
@kevinsawicki - I don't think that's it.... I don't remove any menu items, I'm simply hiding them.

**Comment by kevinsawicki** [comment] 2016-08-20 00:25
@coreybutler try not setting the separators to `false` in your example but just the other ones, do you still end up seeing the separators on macOS?

**Comment by coreybutler** [comment] 2016-08-20 00:25
Here's the whole menu file:

```js
'use strict'

// Setup Menu
const electron = require('electron')
const ipc = electron.ipcMain
const Menu = electron.Menu
const sep = {type: 'separator'}

module.exports = function (assets) {
  let menuTpl = [{
    label: 'Application',
    submenu: [{
      label: 'About',
      click () {
        ipc.emit('display.about')
      }
    }, sep, {
      label: 'New Server',
      accelerator: 'CmdOrCtrl+N',
      click () {
        ipc.emit('webroot.identify')
      }
    }, sep, {
      label: 'Start All',
      accelerator: 'Alt+CmdOrCtrl+Up',
      click () {
        ipc.emit('webserver.startall')
      }
    }, {
      label: 'Stop All',
      accelerator: 'Alt+CmdOrCtrl+Down',
      click () {
        ipc.emit('webserver.stopall')
      }
    }, {
      label: 'Delete All',
      click () {
        ipc.emit('webserver.delete.all')
      }
    }, {
      label: 'Share Selected Server',
      accelerator: 'Alt+CmdOrCtrl+S',
      type: 'checkbox',
      checked: false,
      visible: false,
      click () {
        ipc.emit('toggle.share')
      }
    }, sep, {
      label: 'Server List',
      accelerator: 'CmdOrCtrl+.',
      click () {
        ipc.emit('servers.display')
      }
    }, {
      label: 'Preferences',
      accelerator: 'CmdOrCtrl+,',
      click () {
        ipc.emit('preferences.display')
      }
    }, sep, {
      label: 'Theme',
      submenu: [{
        label: 'Light',
        type: 'radio',
        checked: true,
        click () {
          ipc.emit('theme.select', 'light')
        }
      }, {
        label: 'Dark',
        type: 'radio',
        checked: false,
        click () {
          ipc.emit('theme.select', 'dark')
        }
      }]
    }, sep, {
      label: 'Quit',
      accelerator: 'CmdOrCtrl+Q',
      click () {
        assets.app.quit()
      }
    }]
  }, {
    label: 'Edit',
    submenu: [{
      label: 'Cut',
      accelerator: 'CmdOrCtrl+X',
      selector: 'cut:',
      role: 'cut'
    }, {
      label: 'Copy',
      accelerator: 'CmdOrCtrl+C',
      selector: 'copy:',
      role: 'copy'
    }, {
      label: 'Paste',
      accelerator: 'CmdOrCtrl+V',
      // selector: 'paste:',
      role: 'paste'
    }, {
      label: 'Select All',
      accelerator: 'CmdOrCtrl+A',
      selector: 'selectAll:',
      role: 'selectall'
    }, sep, {
      label: 'Undo',
      accelerator: 'CmdOrCtrl+Z',
      role: 'undo'
    }, {
      label: 'Redo',
      accelerator: 'Shift+CmdOrCtrl+Z',
      role: 'redo'
    }]
  }, {
    label: 'SSL',
    submenu: [{
      label: 'View Certificate Details',
      visible: true,
      click () {
        ipc.emit('show.ssl.filebrowser')
      }
    }, {
      label: 'Open Certificate Directory',
      click () {
        ipc.emit('ssl.filebrowser')
      }
    }, sep, {
      label: 'Regenerate',
      visible: true,
      click () {
        ipc.emit('ssl.regenerate.ca')
      }
    }, sep, {
      label: 'Disable',
      visible: true,
      click () {
        assets.CA.disable()
      }
    }, {
      label: 'Enable',
      visible: false,
      click () {
        assets.CA.regenerate()
        console.log('ENABLE SSL')
      }
    }]
  }, {
    label: 'Team',
    submenu: [{
      label: 'Show Team',
      accelerator: 'CmdOrCtrl+T',
      type: 'checkbox',
      checked: false,
      // enabled: false,
      click () {
        ipc.emit('toggle.collaboration')
      }
    }]
  }/*,{
    role: 'help',
    submenu: [{
      label: 'My IP Addresses',
      click () {
        console.log(require('os').networkInterfaces())
      }
    }]
  }*/]

  // If the user is a developer, support devtools
  menuTpl.push({
    label: 'Developer',
    submenu: [{
      label: 'Show Devtools',
      accelerator: 'Alt+CmdOrCtrl+I',
      type: 'checkbox',
      checked: false,
      click () {
        assets.mainWindow.toggleDevTools()
      }
    }]
  })

  let menu = Menu.buildFromTemplate(menuTpl)
  Menu.setApplicationMenu(menu)

  let sharingItem = function () {
    return menu.items[0].submenu.items.filter(function (item) {
      return item.label === 'Share Selected Server'
    })[0]
  }

  ipc.on('menu.sharing.visible', function (show) {
    sharingItem().visible = show
    if (!show) {
      sharingItem().checked = false
    }
  })

  ipc.on('menu.sharing.checked', function (checked) {
    if (arguments.length > 1) {
      checked = arguments[1]
    }

    sharingItem().checked = checked
  })

  const sslmenu = menu.items[2].submenu
  const disabledItem = sslmenu.items[sslmenu.items.length - 2]
  const enabledItem = sslmenu.items[sslmenu.items.length - 1]
  const setSslMenuAction = function () {
    console.log('Changing menu items')
    sslmenu.items.forEach((item) => {
      item.visible = assets.CA.enabled
    })
    enabledItem.visible = !assets.CA.enabled
    disabledItem.visible = assets.CA.enabled
  }

  setTimeout(function () {
    assets.CA.on('disable', () => {
      console.log('RECOGNIZED CA DISABLE')
      setSslMenuAction()
    })
    assets.CA.on('enable', () => {
      console.log('RECOGNIZED CA DISABLE')
      setSslMenuAction()
    })
    setSslMenuAction()
  }, 1)

}
```

**Comment by kevinsawicki** [comment] 2016-08-20 00:29
@coreybutler Do you still see the separator in this menu example?

```js
{
  label: 'Separator below?',
},
{
  type: 'separator',
  visible: false
},
{
  label: 'Separator above?',
}

**Comment by coreybutler** [comment] 2016-08-20 00:33
@kevinsawicki - Your example works as you're expecting... no separators above or below. But that's not really the issue. My separators aren't at the top/bottom of the menu.... they're in the middle.

Just to clarify, my goal is to REMOVE the separators on Windows when "Enable" is the only item, preferably without having to reconstruct the menu items (which is what I'll do if I have to).

**Comment by kevinsawicki** [comment] 2016-08-20 00:35
> Just to clarify, my goal is to REMOVE the separators on Windows when "Enable" is the only item, preferably without having to reconstruct the menu items (which is what I'll do if I have to).

Oh okay, I see what you are referring to now, this seems like a duplicate of https://github.com/electron/electron/issues/5869, closing this out here, please subscribe to that one for updates.

**Closed by kevinsawicki** 2016-08-20 00:35 UTC

**Comment by coreybutler** [comment] 2016-08-20 00:36
Ah thanks, sorry for the duplicate... didn't see that one.

**Comment by kevinsawicki** [comment] 2016-08-20 00:36
>  citing that macOS doesn't support hiding the separator. However; it seems to be working on El Capitan (10.11.16).

Just to be clear, I don't believe this is supported via the `visible` property on macOS, what macOS does support is removing leading and trailing separators automatically, while Windows and Linux does not.

**Comment by coreybutler** [comment] 2016-08-20 00:45
@kevinsawicki - I was initially under the impression that as long as the menu items _existed_ (even if visibility = `false`), then macOS would treat them as though they exist. In reality, it appears as though any menu item whose visibility is set to `false` will be treated as though the menu item doesn't exist. Since I'm hiding every item dynamically, macOS is treating it as though the non-separator menu items don't exist while the separators and visible menu items do exist. So in my case, macOS sees two separators and one menu item (just like the last Windows screen shot).... and therefore removes the leading separators because that's the default action.

This all makes sense now. I figured I'd write this out in case anyone else comes across it.
