### ISSUE TITLE
Hide icon of modal dialog on Windows

### ISSUE THREAD

**Issue by lutzroeder** [electron/electron#22105] opened 2020-02-08 19:29 UTC
Is there a way to hide the icon of a `BrowserWindow` on Windows?

**Expected:**
<img width="142" alt="Screen Shot 2020-02-08 at 11 28 08 AM" src="https://user-images.githubusercontent.com/438516/74090908-1ce34f00-4a66-11ea-81ee-d2a89ed4a11e.png">

**Actual:**
<img width="68" alt="Screen Shot 2020-02-08 at 11 27 35 AM" src="https://user-images.githubusercontent.com/438516/74090907-194fc800-4a66-11ea-8930-0d2cf139e78b.png">

**Repro:**
[electron-22105.zip](https://github.com/electron/electron/files/4177328/electron-22105.zip)

**Comment by aman-kumar-jh** [comment] 2020-02-13 16:21
I am solving this issue

**Comment by julienpan** [comment] 2020-02-19 13:47
Hi, I'd like to work on this, I would like to have more information about how to start on it.

**Comment by VVlasy** [comment] 2020-02-21 01:31
@julienpan Hi, start off by compiling your own build of Electron as described [here](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Comment by VVlasy** [comment] 2020-02-22 18:51
@lutzroeder @MarshallOfSound What is the proposed solution? 

There a few I had in mind.

1. Handle `null` value for `icon` property of `electron.BrowserWindow` and when set to null remove window icon instead of throwing up an error `file not found`

2. Remove icon from window when it is set as modal on Windows

3. Add property `showWindowIcon` that is by default set to `true`, could be set to false by default on modal windows as well.

**Comment by lutzroeder** [comment] 2020-02-22 20:48
Both 1. and 2. would change the behavior in existing apps.

Maybe setting `icon` to `electron.nativeImage.createEmpty()` and checking `icon && icon.isEmpty()` would work?

See also https://stackoverflow.com/questions/53880863/electron-cant-hide-program-icon-in-browserwindow.

**Comment by VVlasy** [comment] 2020-02-22 23:57
And after the check in JS make a callback to c++ -> platform specific implementations

**Comment by elizaho** [comment] 2020-03-17 17:53
Did this ever get resolved, or is this still an issue that someone can work on? If no one is working on it right now, I'd like to work on it. Are you still working on it? @julienpan

**Comment by Falgu9** [comment] 2020-03-19 13:58
Hi ! I can also help if @julienpan or @elizaho didnt start to fix this issue. Give news if you can please !

**Comment by aritramullick** [comment] 2020-05-06 08:55
I would be interested in helping if this hasn't been resolved yet. However, I am a first-timer and I dont really know exactly how to go about this.

**Comment by rghv9** [comment] 2020-05-10 00:04
inspect it
and do in its css file and set
display:"none";

**Comment by Aryan-Sihag** [comment] 2020-05-14 08:54
hey i am new to github and i want to make some early contributions , i think i can work on it and i would like to get some instructions on how to get started.

**Comment by mahdi-farnia** [comment] 2020-05-16 12:58
Hello i think the best way is hiding browser frames...
and Create another one with your custom items.
You now how.. right??

**Comment by lutzroeder** [comment] 2020-05-16 17:29
Goal here is not to find a workaround but fix the underlying issue in Electron. This probably requires understanding how Electron creates the native HWND on Windows.

**Comment by ReverPL** [comment] 2020-05-22 15:31
Znalazłem coś takiego, może się przyda
https://stackoverflow.com/questions/42988166/show-and-hide-main-window-on-electron

**Comment by uditswaroopa** [comment] 2020-05-25 04:45
Hey I want to work on this issue can you please assign it to me

**Comment by lars-berger** [comment] 2020-05-28 15:03
On a similar note, it would be nice to be able to hide the application title in the titlebar, while still being able to show a title on taskbar hover (eg. as done by File Explorer).

**Comment by faraz16iqbal** [comment] 2020-06-18 17:10
If this is issue hasn't been resolved, I'd love to work on it!

**Comment by Le-Roi777** [comment] 2020-06-20 20:09
Hi gents... : ) quick question, why is this an issue? And why do you want or need to hide the icon?

**Comment by lutzroeder** [comment] 2020-06-20 20:16
@Le-Roi777 Modal dialogs in Windows apps often do not show an icon. For example, open Notepad > Help > About Notepad.

**Comment by vishal-1408** [comment] 2020-06-24 12:37
Hi, If the issue is still not fixed i would love to work on it .

**Comment by MobiuSid** [comment] 2020-06-28 18:01
@lutzroeder Hi, I have started to work on the issue, can u assign it to me?
Am very excited to work on this.

**Comment by lutzroeder** [comment] 2020-06-28 19:02
@MarshallOfSound

**Comment by Mobius1D** [comment] 2020-07-01 12:31
Hey, still working on this issue here, 
I initially read through the shell/browser/api/electron_api_browser_window.cc but wasn't able to find anything relevant. 
Then I searched through the entire project for the code related to the title bar and am not finding anything useful here too.
It would be amazing and easier to work on this if I could get some help on what files that I would be working on.
I am pretty much sure that I would have to modify the API to include a field called showWindowIcon that can be set to true to show the icon on the title bar and by default set to false if it is a modal window. These arguments would be passed to the class responsible for the title bar which I can modify accordingly.
Need some help with finding the files that I might be working with and also with the approach.
Thanks in advance.

**Comment by lutzroeder** [comment] 2020-07-01 21:03
@zcbenz might be able to provide some context. [native_window_views.cc](https://github.com/electron/electron/blob/master/shell/browser/native_window_views.cc) looks like the right place to get started.


[WinForms](https://stackoverflow.com/questions/4905465/creating-a-window-using-createwindowex-without-an-icon) has [ShowIcon](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.showicon?view=netcore-3.1). Another option might be `electron.nativeImage.createEmpty()` and `icon && icon.isEmpty()`.

**Comment by AkshataJ96** [comment] 2020-09-09 19:32
Hi, I would like to start working on this if this issue is not resolved yet!

**Comment by unbeatable01** [comment] 2020-10-14 10:16
I'd like to work on this, could you assign it to me?

**Comment by BHAKTA-VARUN** [comment] 2020-11-04 15:10
hi everyone,
i would like to start working in it can please assign in it

**Comment by TaufeqRazakh** [comment] 2020-12-15 01:31
Hi ya'all. Am interest too. Assigne et tu me

**Comment by theRoushan** [comment] 2021-03-26 05:15
Hi I would like to work on this issue.

**Comment by Anmolreshi** [comment] 2021-06-02 16:08
HI I would like to work on this issue

**Comment by AkashKalala** [comment] 2022-04-02 06:14
I would like to work on this issue

**Comment by david-fiaty** [comment] 2022-10-12 10:34
+1

**Comment by RaisinTen** [comment] 2022-10-12 10:38
Hi folks 👋 , instead of commenting that you would like to work on this issue, please feel free to send a PR right away and we'll be happy to review.

**Comment by RaisinTen** [comment] 2022-10-12 10:48
No worries! I think upvoting the issue with a :+1: is a nicer way to convey that without sending notifications to everyone subbed to this thread.

**Comment by david-fiaty** [comment] 2022-10-12 10:56
So removing specifically the icon from the browser window is not that straight forward as the same icon is used in the taskbar when the app is running with minimised windows. For those it could help, I'd suggest to just provide a blank/transparent image when building a window.

**Comment by hemanthnxtwave** [comment] 2023-02-12 16:51
I would like to work on this issue. Please assign it to me.

**Closed** 2023-06-05 03:33 UTC
Labels: enhancement :sparkles:, platform/windows, beginner friendly
