### ISSUE TITLE
defaultPath does not work in dialog.showOpenDialog when called from renderer process

### ISSUE THREAD

**Issue by distributev** [electron/electron#10421] opened 2017-09-01 10:51 UTC
The same issue was raised in the past here - https://github.com/electron/electron/issues/6371

Electron version: 1.7.5
Operating system: Windows 10 64-bit

Here is a screenshot

![defaultpath](https://user-images.githubusercontent.com/19224635/29966895-343ea39e-8f14-11e7-99c8-53540337bffb.png)

**Comment by codebytere** [comment] 2018-02-15 15:50
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by distributev** [comment] 2018-03-02 14:28
Hi @codebytere,

Thank you for your help.

If you check the issue details you'll see electron version, OS details and a screen-shot with the exact code to reproduce this issue. I think this is enough information to reproduce the situation. I'm not sure what you mean with "standalone test" but I'll probably not have the possibility to provide additional inputs.

**Comment by MarshallOfSound** [comment] 2018-03-02 14:49
@distributev That path is not valid for Windows, the path separator on windows is `\` (backslash) not `/` (forward slash)

**Comment by codebytere** [comment] 2018-03-02 17:27
In light of @MarshallOfSound's comment above, i'm going to go ahead and close this.

**Closed by codebytere** 2018-03-02 17:27 UTC
Labels: platform/windows, triaged/bug, version/1.7.x

**Comment by distributev** [comment] 2018-03-12 19:35
I'll try this but I'm >95% it is not because of that - Windows does accept / folder separator wherever it accepts \ character - there are couple of years since I'm using without any issue / char in my source code everywhere in windows just to write more cross OS portable code.

**Comment by jogisarge** [comment] 2019-05-20 18:26
Hi, i had the same problem on Windows.
i solved it by using double slashes !
`let options = {defaultPath: 'C:\\ADS\\FOLDER11\\FILES'}`

**Comment by rmzetti** [comment] 2024-11-12 08:49
I recommend this issue be re-opened. As @distributev notes Windows accepts / characters as folder separators, and from a cross-platform perspective electron should also accept them - as much as possible we need to avoid writing platform specific sections within electron code - that is cross-platform pretense...

And thanks to @jogisarge for the reminder (it's quite a while since I've been forced to use backslashes..)
