### ISSUE TITLE
Electron apps freeze on linux 5.x kernel

### ISSUE THREAD

**Issue by vbatts** [electron/electron#21415] opened 2019-12-06 15:06 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
really not sure. It seems to affect every app using electron that I have tried so far (vscode, signal-desktop, slack, etc.)
* **Operating System:**
* linux slackware64-current, kernel 5.4.2
* **Last Known Working Electron version:**
* on linux kernel 4.x

### Expected Behavior
a functional app

### Actual Behavior
applications freeze in about 5-10 minutes

### To Reproduce
just open them. even leave them running in the background

### Additional Information
I discovered thread https://forum.manjaro.org/t/electron-apps-crashing-randomly/81717/17
which indicates that adding `--disable-gpu` is a workaround.

**Comment by ckerr** [comment] 2019-12-12 20:18
I'm not having this issue in Ubuntu 19.10, which ships with 5.3.0-24-generic.

I don't want to just close this issue indiscriminately, but I'm not sure how to proceed with this. If someone finds a consistent reproduction for this, e.g. by using `electron-quick-start` as a starting point and making sample code that can repro this behavior on a given kernel, it would be much appreciated.

**Comment by vbatts** [comment] 2019-12-12 20:32
right. I figured there is something nuanced, otherwise this would've been a bigger blocker, or more quickly noticed.
since it seems possibly GPU related, here's the video info on the card in the machine I'm personally experiencing this:
```
00:02.0 VGA compatible controller [0300]: Intel Corporation Skylake GT2 [HD Graphics 520] [8086:1916] (rev 07) (prog-if 00 [VGA controller])
        DeviceName:  Onboard IGD   
        Subsystem: Dell Skylake GT2 [HD Graphics 520] [1028:0704]
        Flags: bus master, fast devsel, latency 0, IRQ 129
        Memory at db000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 90000000 (64-bit, prefetchable) [size=256M]
        I/O ports at f000 [size=64]
        [virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: i915
        Kernel modules: i915
```

**Comment by cipriancraciun** [comment] 2020-01-16 08:16
I'm using Sabaki (Go player based on Electron 5 in their last release), and I do suffer a similar freezing issue, which I've also reported to them: https://github.com/SabakiHQ/Sabaki/issues/618

Can I enable some flag that would provide a verbose log and help diagnose the issue?

(I'm not an Electron user-developer, therefore I can't help in creating a test-case, but I can help by triggering the issue in the application and reporting back the logs / context.  Or I can help running some test-cases if provided.)

(My OS is OpenSUSE Tumbleweed, i.e. rolling release, with kernel `5.3.12`, using Xorg, thus not Wayland, and the `i3` window manager.)

**Comment by vbatts** [comment] 2020-01-16 11:24
@cipriancraciun what video card is on this machine, and driver is it using?

As an update, I've been upgrading kernels to validate this issue. It still happens through 5.4.12 (latest)

-------- Original Message --------

**Comment by cipriancraciun** [comment] 2020-01-17 07:22
> @cipriancraciun what video card is on this machine, and driver is it using? As an update, I've been upgrading kernels to validate this issue. It still happens through 5.4.12 (latest)

@vbatts I'm pasting bellow the info I've given to the other project and some extra Xorg related details.

```
lsmod | grep -e i915 -e drm

i915                 2351104  9
drm_kms_helper        217088  1 i915
drm                   516096  10 drm_kms_helper,i915
fb_sys_fops            16384  1 drm_kms_helper
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
i2c_algo_bit           16384  1 i915
video                  53248  2 fujitsu_laptop,i915
```

```
cat /var/log/Xorg.0.log

[...]
[    33.644] (II) LoadModule: "intel"
[    33.644] (II) Loading /usr/lib64/xorg/modules/drivers/intel_drv.so
[    33.653] (II) Module intel: vendor="X.Org Foundation"
[    33.653]    compiled for 1.20.5, module version = 2.99.917
[    33.653]    Module class: X.Org Video Driver
[    33.653]    ABI class: X.Org Video Driver, version 24.0
[    33.653] (II) LoadModule: "modesetting"
[    33.653] (II) Loading /usr/lib64/xorg/modules/drivers/modesetting_drv.so
[    33.654] (II) Module modesetting: vendor="X.Org Foundation"
[    33.654]    compiled for 1.20.6, module version = 1.20.6
[    33.654]    Module class: X.Org Video Driver
[    33.654]    ABI class: X.Org Video Driver, version 24.0
[...]
[    33.654] (II) intel: Driver for Intel(R) Integrated Graphics Chipsets:
    i810, i810-dc100, i810e, i815, i830M, 845G, 854, 852GM/855GM, 865G,
    915G, E7221 (i915), 915GM, 945G, 945GM, 945GME, Pineview GM,
    Pineview G, 965G, G35, 965Q, 946GZ, 965GM, 965GME/GLE, G33, Q35, Q33,
    GM45, 4 Series, G45/G43, Q45/Q43, G41, B43
[    33.654] (II) intel: Driver for Intel(R) HD Graphics
[    33.654] (II) intel: Driver for Intel(R) Iris(TM) Graphics
[    33.654] (II) intel: Driver for Intel(R) Iris(TM) Pro Graphics
[    33.654] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[    33.675] (II) intel(0): Using Kernel Mode Setting driver: i915, version 1.6.0 20190619
[    33.692] (WW) Falling back to old probe method for modesetting
[    33.692] (--) intel(0): Integrated Graphics Chipset: Intel(R) HD Graphics 4000
[    33.692] (--) intel(0): CPU: x86-64, sse2, sse3, ssse3, sse4.1, sse4.2, avx; using a maximum of 2 threads
[    33.692] (II) intel(0): Creating default Display subsection in Screen section
    "Default Screen Section" for depth/fbbpp 24/32
[    33.692] (==) intel(0): Depth 24, (--) framebuffer bpp 32
[    33.692] (==) intel(0): RGB weight 888
[    33.693] (==) intel(0): Default visual is TrueColor
[    33.693] (**) intel(0): Option "AccelMethod" "SNA"
[    33.693] (**) intel(0): Option "SwapbuffersWait" "True"
[    33.693] (**) intel(0): Option "TripleBuffer" "True"
[    33.693] (**) intel(0): Option "TearFree" "True"
[...]
[    33.694] (II) intel(0): SNA initialized with Ivybridge (gen7, gt2) backend
[    33.694] (==) intel(0): Backing store enabled
[    33.694] (==) intel(0): Silken mouse enabled
[    33.694] (II) intel(0): HW Cursor enabled
[    33.695] (==) intel(0): DPMS enabled
[    33.695] (==) intel(0): Display hotplug detection enabled
[    33.695] (II) intel(0): [DRI2] Setup complete
[    33.695] (II) intel(0): [DRI2]   DRI driver: i965
[    33.695] (II) intel(0): [DRI2]   VDPAU driver: va_gl
[    33.695] (II) intel(0): direct rendering: DRI2 enabled
[    33.695] (II) intel(0): hardware support for Present enabled
[...]
```

```
cat /proc/cpuinfo

processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 58
model name  : Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
stepping    : 9
...
```

```
lshw -class display

  *-display                 
       description: VGA compatible controller
       product: 3rd Gen Core processor Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:35 memory:f0000000-f03fffff memory:e0000000-efffffff ioport:4000(size=64) memory:c0000-dffff
```

```
glxinfo  -B

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Ivybridge Mobile  (0x166)
    Version: 19.2.6
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.2
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 19.2.6
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 19.2.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

**Comment by vbatts** [comment] 2020-01-27 11:52
This weekend at devconf.cz I was directed to a similar issue as it relates to Intel GPU since linux 5.x + mesa + applications/desktop freezing: https://gitlab.freedesktop.org/drm/intel/issues/673

**Comment by bedwardly-down** [comment] 2020-02-20 18:17
Has anyone had issues on Arch with Kernel 5.5 on this? The bug that mentions this above I don't think is exactly related, but me and several others are trying to pinpoint where the issue lies for a note taking app called Joplin. Thanks.

**Comment by vbatts** [comment] 2020-02-20 18:19
yes, the joplin gui is affected as well for me. Even on 5.4.20. While passing `--disable-gpu` helps many of the other electron apps, something in joplin swallows that flag getting passed to the electron runtime. so that workaround is not feasible currently.

**Comment by bedwardly-down** [comment] 2020-02-20 18:23
Thanks for getting back to me. I don't think the issue that mentioned this is directly related to this specific bug since the main issue happens during syncing and doesn't fully affect the entire app, but this Electron bug could be related to multiple others.

**Comment by vladimiry** [comment] 2020-02-20 18:34
> Has anyone had issues on Arch with Kernel 5.5 on this?

Yes, exactly Arch + kernel 5.5.x.

https://github.com/vladimiry/ElectronMail/issues/253
https://github.com/vladimiry/ElectronMail/issues/252
https://github.com/vladimiry/ElectronMail/issues/250

**Comment by bedwardly-down** [comment] 2020-02-20 18:47
@vladimiry, thanks for the issue links. These look similar enough to what I'm trying to figure out that I've notified the Joplin dev. We'll see how things go with that.

**Comment by bedwardly-down** [comment] 2020-02-22 15:52
Upgrading to Electron 8 did not solve Joplin's issue but instead made it worse. In fact, it caused the app to be completely unresponsive during my tests. So, downgrading to kernel 5.4 is becoming the go to option until we can get something more concrete down. Thanks again, @vladimiry

**Comment by ChALkeR** [comment] 2020-02-22 23:14
The recent Arch (and other glibc 2.31 distros) issue is https://github.com/electron/electron/issues/22291, but it does not affect Electron 8 -- and that's where upgrading to 8 (or waiting for #22338 / #22339) helps.

If this affects Electron 8, then it's an entirely separate issue (which means that there are two issues affecting Arch).

**Comment by ChALkeR** [comment] 2020-02-22 23:17
As for linux 5.5, there is another significant issue there which could be related to random freezes: https://gitlab.freedesktop.org/drm/intel/issues/1201

**Comment by bedwardly-down** [comment] 2020-02-22 23:34
@ChALkeR that could definitely apply to me since I'm on Intel hardware. And that could be related to Wayland issues that i resolved by just removing the packages that needed it. I had a music player i was testing out because of its Tidal support but the browser version was miles better.

**Comment by bedwardly-down** [comment] 2020-03-04 13:56
Through research and a long string of git bisects and whatnot, I'm finding that this bug seems to be caused by this commit: https://github.com/torvalds/linux/commit/339ddb53d373baee6e7946aec17c739c4924d6d9

Is there any major work being done to solve this issue?

It looks like the Flutter team is onto something and at least have the issue fixed in their main branch, but I'm not finding much else about it. https://github.com/flutter/flutter/issues/49185

**Comment by lnicola** [comment] 2020-03-04 14:29
There's also https://bugzilla.kernel.org/show_bug.cgi?id=205933 which could be related (courtesy of @vladimiry). It's not clear to me if it's fixed or not.

**Comment by bedwardly-down** [comment] 2020-03-04 18:42
Thanks for the link, @lnicola . If you scroll to the bottom, it looks like netdev (the apparent maintainer of this particular feature; in my git bisect tests, merges involving their contributions kept appearing), have worked on resolving this issue but I'm having problems finding exactly which branch the fix will be applied to. Either way, I'm surprised this particular messup is actually kind of hard to find on the Internet without knowing where to look in particular. This is one of those strange edge cases. Ha

**Comment by leifmadsen** [comment] 2020-10-06 14:04
Still having this issue on my new desktop :)

**Comment by bedwardly-down** [comment] 2020-10-06 18:44
@leifmadsen any way to provide more information here such as kernel release, operating system, hardware etc? thanks

**Comment by peletomi** [comment] 2020-10-07 12:23
The issue is still present on following configuration:

- Linux nubo 5.8.11-1-MANJARO
- Electron 9.2.1

All electron apps freeze (Spotify, Signal, VSCode...). More often when they are in the background, but sometimes when they are in use as well.

It is not occurring with kernel v4.9

**Comment by leifmadsen** [comment] 2020-10-07 12:51
> @leifmadsen any way to provide more information here such as kernel release, operating system, hardware etc? thanks

Absolutely!

(Sidebar: I also just noticed the issue opened about freezing when getting notifications, so I've disabled notifications to see if that helps.)

**OS**
* Fedora 32, fresh install all updates applied.
* Linux desktop 5.8.12-200.fc32.x86_64 #1 SMP Mon Sep 28 12:17:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Hardware**
```
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation 6th-9th Gen Core Processor PCIe Controller (x16) (rev 07)
00:02.0 Display controller: Intel Corporation HD Graphics 530 (rev 06)
00:14.0 USB controller: Intel Corporation 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller (rev 31)
00:14.2 Signal processing controller: Intel Corporation 100 Series/C230 Series Chipset Family Thermal Subsystem (rev 31)
00:16.0 Communication controller: Intel Corporation 100 Series/C230 Series Chipset Family MEI Controller #1 (rev 31)
00:17.0 SATA controller: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode] (rev 31)
00:1c.0 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #5 (rev f1)
00:1d.0 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #9 (rev f1)
00:1f.0 ISA bridge: Intel Corporation B150 Chipset LPC/eSPI Controller (rev 31)
00:1f.2 Memory controller: Intel Corporation 100 Series/C230 Series Chipset Family Power Management Controller (rev 31)
00:1f.3 Audio device: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller (rev 31)
00:1f.4 SMBus: Intel Corporation 100 Series/C230 Series Chipset Family SMBus (rev 31)
01:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GP106 High Definition Audio Controller (rev a1)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
```

This is found when using Slack via slack-4.9.1-0.1.fc21.x86_64.rpm. Sorry, I tried to export the list of packages but it doesn't show me the version of Electron in use there.

**Comment by leifmadsen** [comment] 2020-10-07 13:28
Note that I seemed to work around the issue by running `dunst`. Disabling notifications in the application didn't seem to totally solve the issue for me, but running `dunst` as a notification system seems to keep the application from locking up.

**Comment by cmosig** [comment] 2020-11-25 10:45
I am also having this issue. 
Information about my setup:
```
> $ cat /etc/os-release                                                                                                                           
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
```
> $ uname -a                                                                                                                                   
Linux findme 5.9.10-1-MANJARO #1 SMP PREEMPT Sun Nov 22 11:25:19 UTC 2020 x86_64 GNU/Linux
```
```
> $ electron --version                                                                                                                            
v10.1.5
```
Apps like spotify, discord, obsidian, ... freeze. Sometimes after minutes, sometimes hours.  
I am also getting the error when starting electron apps:
```
(electron:24430): GLib-GIO-CRITICAL **: 11:37:35.552: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```
```
> $ lspci                                                                                                                                          
00:00.0 Host bridge: Intel Corporation Coffee Lake HOST and DRAM Controller (rev 0c)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (Whiskey Lake) (rev 02)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 0c)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Cannon Point-LP Thermal Controller (rev 30)
00:14.0 USB controller: Intel Corporation Cannon Point-LP USB 3.1 xHCI Controller (rev 30)
00:14.2 RAM memory: Intel Corporation Cannon Point-LP Shared SRAM (rev 30)
00:14.3 Network controller: Intel Corporation Cannon Point-LP CNVi [Wireless-AC] (rev 30)
00:15.0 Serial bus controller [0c80]: Intel Corporation Cannon Point-LP Serial IO I2C Controller #0 (rev 30)
00:16.0 Communication controller: Intel Corporation Cannon Point-LP MEI Controller #1 (rev 30)
00:1c.0 PCI bridge: Intel Corporation Cannon Point-LP PCI Express Root Port #1 (rev f0)
00:1c.4 PCI bridge: Intel Corporation Cannon Point-LP PCI Express Root Port #5 (rev f0)
00:1d.0 PCI bridge: Intel Corporation Cannon Point-LP PCI Express Root Port #9 (rev f0)
00:1d.4 PCI bridge: Intel Corporation Cannon Point-LP PCI Express Root Port #13 (rev f0)
00:1f.0 ISA bridge: Intel Corporation Cannon Point-LP LPC Controller (rev 30)
00:1f.3 Audio device: Intel Corporation Cannon Point-LP High Definition Audio Controller (rev 30)
00:1f.4 SMBus: Intel Corporation Cannon Point-LP SMBus Controller (rev 30)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Cannon Point-LP SPI Controller (rev 30)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (6) I219-V (rev 30)
01:00.0 SD Host controller: Genesys Logic, Inc GL9750 SD Host Controller (rev 01)
3c:00.0 3D controller: NVIDIA Corporation GP108M [GeForce MX250] (rev a1)
3d:00.0 Non-Volatile memory controller: Sandisk Corp Device 5006
```

**Comment by scottsidekick** [comment] 2020-11-27 20:20
I am having the same issue. VSCode and Discord both freeze unless I turn off gpu acceleration on both.

`NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
`
`00:00.0 Host bridge: Intel Corporation 4th Gen Core Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
00:03.0 Audio device: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (rev 06)
00:14.0 USB controller: Intel Corporation 9 Series Chipset Family USB xHCI Controller
00:16.0 Communication controller: Intel Corporation 9 Series Chipset Family ME Interface #1
00:1a.0 USB controller: Intel Corporation 9 Series Chipset Family USB EHCI Controller #2
00:1b.0 Audio device: Intel Corporation 9 Series Chipset Family HD Audio Controller
00:1c.0 PCI bridge: Intel Corporation 9 Series Chipset Family PCI Express Root Port 1 (rev d0)
00:1c.2 PCI bridge: Intel Corporation 9 Series Chipset Family PCI Express Root Port 3 (rev d0)
00:1c.3 PCI bridge: Intel Corporation 82801 PCI Bridge (rev d0)
00:1d.0 USB controller: Intel Corporation 9 Series Chipset Family USB EHCI Controller #1
00:1f.0 ISA bridge: Intel Corporation Z97 Chipset LPC Controller
00:1f.2 SATA controller: Intel Corporation 9 Series Chipset Family SATA Controller [AHCI Mode]
00:1f.3 SMBus: Intel Corporation 9 Series Chipset Family SMBus Controller
01:00.0 VGA compatible controller: NVIDIA Corporation GF110 [GeForce GTX 580] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GF110 High Definition Audio Controller (rev a1)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)
04:00.0 PCI bridge: Intel Corporation 82801 PCI Bridge (rev 41)
05:00.0 Multimedia audio controller: Creative Labs EMU20k1 [Sound Blaster X-Fi Series]
`

**Comment by shayas** [comment] 2020-11-28 16:11
In addition to what @vbatts described in his `--disable-gpu` workaround, one can also disable it this way:

1. In [VSCode](https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration): `"disable-hardware-acceleration": true` in **Preferences: Configure Runtime Arguments**
2. In Slack: Preferences → Advanced → **Disable hardware acceleration**
3. In Brave (isn't Electron but is Chromium as well): Settings → Additional settings → System → Toggle **Use hardware acceleration when available** off

**Comment by deescuderoo** [comment] 2021-01-06 14:29
> yes, the joplin gui is affected as well for me. Even on 5.4.20. While passing `--disable-gpu` helps many of the other electron apps, something in joplin swallows that flag getting passed to the electron runtime. so that workaround is not feasible currently.

I came here due to having this issue with Joplin. I use to fix electron apps with the `--disable-gpu` flag, but as @vbatts mentions, Joplin just ignores the flag and doesn't hand it to Electron. I wonder if someone could find a workaround this.

**Comment by ecbftw** [comment] 2021-01-10 18:38
This continues to affect slack and I think other apps on my system.  Disabling acceleration works around it. Some stats:

```
root@diffie:~# cat /etc/debian_version 
bullseye/sid

root@diffie:~# uname -a
Linux diffie 5.9.0-5-amd64 #1 SMP Debian 5.9.15-1 (2020-12-17) x86_64 GNU/Linux

root@diffie:~# dpkg -l | grep mesa
ii  libegl-mesa0:amd64                            20.3.2-1                          amd64        free implementation of the EGL API -- Mesa vendor library
ii  libegl1-mesa:amd64                            20.3.2-1                          amd64        transitional dummy package
ii  libgl1-mesa-dri:amd64                         20.3.2-1                          amd64        free implementation of the OpenGL API -- DRI modules
ii  libgl1-mesa-glx:amd64                         20.3.2-1                          amd64        transitional dummy package
ii  libglapi-mesa:amd64                           20.3.2-1                          amd64        free implementation of the GL API -- shared library
ii  libglu1-mesa:amd64                            9.0.1-1                           amd64        Mesa OpenGL utility library (GLU)
ii  libglx-mesa0:amd64                            20.3.2-1                          amd64        free implementation of the OpenGL API -- GLX vendor library
ii  mesa-utils                                    8.4.0-1+b1                        amd64        Miscellaneous Mesa GL utilities

root@diffie:~# dpkg -l | grep intel | grep -v whois
ii  libdrm-intel1:amd64                           2.4.103-2                         amd64        Userspace interface to intel-specific kernel DRM services -- runtime
ii  xserver-xorg-video-intel                      2:2.99.917+git20200714-1+b1       amd64        X.Org X server -- Intel i8xx, i9xx display driver
```

No errors/warnings in kernel log or in xorg log relating to video.  No errors from slack's stdout/stderr.

The problem seems to manifest itself more prominently when resizing the slack window.  I use the "awesome" window manager.  Sometimes some functionality returns when going into slack's fullscreen mode, but not always.  The application seems to still be responsive...  the issue appears to be more that the video buffer doesn't refresh/paint itself on the screen, but clicking on the window (which still appears to have some other window's data in it; whatever window was shown prior to giving slack focus) causes the application to react to clicks, right clicks, etc.

Let me know if I can provide anything else.

**Comment by feluxe** [comment] 2021-01-14 10:52
I had the electron freezing issue on my laptop with intel graphics using arch linux. I could use electron apps only with the `--disable-gpu` flag.

Switching from the `xf86-video-intel` driver to the kernel's `modesetting` driver solved the issue. Electron apps now run stable on my machine, even without the `--disbale-gpu` flag.

I have read that "xf86-video-intel's development has stalled for a long time, and many intel developers are instead actively improving the modesetting driver". I think ditching the `xf86-video-intel` driver was the right solution for me.

My harware:
* Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (Kaby Lake R)
* Intel UHD Graphics 620 (rev 07)

**Comment by electron-triage** [comment] 2021-03-08 22:54
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-08 22:54 UTC
Labels: 5-0-x, 6-1-x, 7-1-x, platform/linux

**Comment by dm17** [comment] 2021-05-30 18:16
I'm seeing a very similar issue via ```Mesa Gallium driver 21.0.3 for AMD Radeon(TM) Vega 8 Graphics``` (according to vainfo) that is triggered by chromium. Maybe that can lend a clue. I also see some instances of:
```usb usb4: root hub lost power or was reset```
right before
```traps: Chrome_ChildIOT[15396] trap int3 ip:5589735b85ab sp:7fc983b118d0 error:0 in chromium```
It is still a mystery to me.

**Comment by Rasie1** [comment] 2021-08-04 22:05
Disabling GPU/acceleration is obviously is not a good solution. 
Installing dunst as suggested workaround in many places doesn't help.

It was working perfectly for years, and now VSCode, all browsers and everything periodically freezes. Maybe someone was able to get rid of this bug?

**Comment by myTerminal** [comment] 2022-03-29 12:31
> I guess a lot of people who run into this issue might be using the `xf86-video-intel` driver.

I've been facing the same issue on my Lenovo ThinkPad Yoga Gen 1, and simply removing `xf86-video-intel` seems to solve the problem. As I'm using Void Linux, it was a `sudo xbps-remove -F xf86-video-intel`, breaking the dependency for `xorg-video-drivers`.

**Comment by Rasie1** [comment] 2022-03-29 13:52
> > I guess a lot of people who run into this issue might be using the `xf86-video-intel` driver.
> 
> simply removing `xf86-video-intel` seems to solve the problem

Is there an alternative? I would want to make use of 2D acceleration for the sake of battery and speed
