### ISSUE TITLE
Apps using the Electron framework on macOS 10.14.x does not let you close or minimize the window if the app is not the active/selected app

### ISSUE THREAD

**Issue by isommers1** [electron/electron#30371] opened 2021-08-02 16:57 UTC
**Bug Description**

Apps built on the Electron framework (Signal, Discord, Slack, probably others, but for sure demonstrable on these) on macOS 10.14.6 does not let you close or minimize the window if the window is not the active/selected app

**Steps to Reproduce**

- Open app (best examples are Signal or Slack)
- Have another app selected (for example, Safari is the active window but Signal or Slack is next to it)
- Mouse over and click the Minimize or Close buttons (red and yellow) in the app window. They do not work. They will colorize on mouseover as all apps do/should, but when you click them, they don't 
- Actual Result: Minimize and Close traffic light buttons do not work on Electron framework'd apps when it's not the app in focus. They do on every other app in macOS

**Expected Result:** Window should minimize or close like every other app on macOS (10.14.6)

**Proof Video 1:** https://www.dropbox.com/s/eip6yz4rflfikoc/Proof1.mov?dl=0 (when I click at the end on the close button with the app selected, it does properly close—I just didn't show the result because of privacy reasons).

**Comment by clavin** [comment] 2021-08-02 22:24
Hi! I'm going to see if I can manage to track down an older version of macOS so I can test this myself and confirm it. This might take a while, but I figured I'd post here so you know what's taking time.

**Comment by necrotech** [comment] 2021-08-03 04:31
- 11.5.1 -- both example apps behave properly
- 10.15.7 -- both example apps behave properly
- 10.14.6 -- both example apps behave as described in the initial report.  Additionally, the app window pops to the top of stack when either button is clicked, but the application does not activate, and the zoom (green) button fullscreens the window, no matter if the app is active, or if option is being held.
- 10.13.6 -- Signal behaves as on 10.14.6.  Slack behaves properly.

**Comment by resuna** [comment] 2021-08-25 12:41
Repro 10.14.6 (Mojave) and Signal 5.14.0.

Can not move on from Mojave because of older apps that do not run on Catalina or later.

**Comment by subminimbus** [comment] 2021-09-03 10:35
Same issue with 10.14.6 (Mojave) and Signal 5.16.0

**Comment by clavin** [comment] 2021-09-09 00:29
I finally found out how to test on macOS 10.14 and while I was able to reproduce this bug, I was also able to verify that it is also already fixed.

The issue was indeed with BrowserWindows with a `titleBarStyle` of `hidden` or `hiddenInset`. I was able to reproduce this bug on macOS 10.14 on Electron 13.1.6, however it was no longer broken starting with Electron 13.1.9 and above on the version 13 stable line.

That means that as apps upgrade to Electron 14 (or even a newer version of 13) this bug should hopefully disappear. For that reason, I'm closing this issue as there is no more work to be done, but feel free to reopen it if you find out more information!

**Closed by clavin** 2021-09-09 00:29 UTC
Labels: platform/macOS, bug :beetle:, status/confirmed, 13-x-y
