### ISSUE TITLE
Electron crashed after click <input type="file">

### ISSUE THREAD

**Issue by agata** [electron/electron#18346] opened 2019-05-18 02:13 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta3
* **Operating System:**
  * macOS 10.13.6 10.14.4 / Windows 7 -->
* **Last Known Working Electron version:**:
  * 5.0.1

### Expected Behavior
Clicked button <input type="file"> in renderer process, then show file chooser dialog and choose local files.

### Actual Behavior
Clicked button <input type="file"> in renderer process, then crash electron app.

### To Reproduce

1. Clone and start sample app
```sh
$ git clone https://github.com/agata/crash-electron-with-file-picker-dialog.git
$ cd ./crash-electron-with-file-picker-dialog
$ npm install
$ npm start
```
3. Click a button in the app -> Crash electron app

#### Electron 5.0.1
<img width="1261" alt="Electron-5 0 1" src="https://user-images.githubusercontent.com/40473/57963337-ca08bb00-795d-11e9-9da0-75a2ca3e55d9.png">

#### Electron 6.0.0-beta.3
Screencast: [Electron-6.0.0-beta.3.mov.zip](https://github.com/electron/electron/files/3193544/Electron-6.0.0-beta.3.mov.zip)

**Comment by MarshallOfSound** [comment] 2019-05-18 03:58
Duplicate of #18313

**Closed by MarshallOfSound** 2019-05-18 03:58 UTC
