### ISSUE TITLE
Frameless Vibrant windows have square corners (no border radius)

### ISSUE THREAD

**Issue by natew** [electron/electron#10886] opened 2017-10-23 18:04 UTC
* Electron version: 1.8.0
* Operating system: MacOS Sierra / High Sierra

### Expected behavior

Some sort of control over this would be nice.

### Actual behavior

Only square windows show.

### More

Keeping this ticket purposely narrow. In the ideal you'd have control over regions where it shows + the border radius. Or really ideal would be just to have backdrop-filter work through to the desktop (perhaps configurable). But, baby steps...

I noticed that the original PR for vibrancy [seems to show a screenshot](https://github.com/electron/electron/pull/7898#issuecomment-259158609) that implies it was rounded at one point, but for me I see this:

<img width="329" alt="screen shot 2017-10-23 at 11 04 14 am" src="https://user-images.githubusercontent.com/12100/31905109-ee246370-b7e1-11e7-86b6-68707674f73e.png">

**Comment by felixrieseberg** [comment] 2017-10-24 23:39
Hm, I tried to replicate the behavior but was unable to do so with the latest master (running macOS Sierra). Do you have a solid repro?

<img width="987" alt="screen shot 2017-10-24 at 4 38 46 pm" src="https://user-images.githubusercontent.com/1426799/31973259-da0a636e-b8d9-11e7-86e6-f90e8b51d000.png">

**Comment by sandor** [comment] 2017-10-27 09:33
Guys, getting something similar here: https://github.com/electron/electron/issues/10823

**Comment by sandor** [comment] 2017-11-03 15:13
If you need a working example: https://github.com/sandor/floido-designer

**Comment by natew** [comment] 2017-11-22 03:39
@sandor I actually don't see the light/darkbackground behavior, it's sharp cornered on any background:

![image](https://user-images.githubusercontent.com/12100/33108933-aa5d2c16-cef3-11e7-808c-3b08c4e2b7d1.png)

**Comment by sandor** [comment] 2017-11-22 08:58
@natew I think if you make the background of your header transparent you will get the same results (light/dark/bg) but can not test it here now – sorry...

**Comment by sandor** [comment] 2017-11-24 20:01
Hey Guys, just saw this in my terminal (think this appears since I updated to the latest beta). To be honest I am not experienced enough to see what this is implying, but it seems to have some relavanve to the behaviours described in this thred...

`2017-11-24 13:55:57.923 Electron[7973:767197] *** WARNING: Textured window <AtomNSWindow: 0x7fe68d86a8b0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.`

**Comment by okonet** [comment] 2017-12-26 20:39
I see a very weird behavior on 1.8.2-beta.3 with the following initializer:

```js
windows.main = new BrowserWindow({
    width,
    height,
    center: true,
    frame: false,
    alwaysOnTop: true,
    maximizable: false,
    minimizable: false,
    fullscreenable: false,
    skipTaskbar: true,
    titleBarStyle: 'hiddenInset',
    vibrancy: 'dark',
    show: false
  })
```

![2017-12-26 at 21 38](https://user-images.githubusercontent.com/11071/34364346-4b6f8840-ea85-11e7-8254-19c16a539ae3.png)

**Comment by tommoor** [comment] 2018-01-20 00:57
This is still an issue however I was able to overcome it by rounding the webpage content at the top corners. It seems like the content is escaping the window bounds causing it to appear square, the rounding was still rendered beneath that and revealed with css border-radius.

**Comment by johnryan** [comment] 2018-01-21 19:22
@tommoor can you share a screenshot of the result you were able to achieve? even trying your solution I have square corners on the top (but not the bottom).
<img width="346" alt="screen shot 2018-01-21 at 11 21 03 am" src="https://user-images.githubusercontent.com/416564/35198016-49e84878-fe9d-11e7-94b4-423fbee7e94b.png">

**Comment by tommoor** [comment] 2018-02-06 19:42
@johnryan you'd have to put the rounding on the dark grey element, I was able to achieve:
![image](https://user-images.githubusercontent.com/380914/35880436-ce6cf91c-0b32-11e8-92d0-2e33002109a9.png)

**Comment by vincelwt** [comment] 2018-02-22 18:05
@tommoor What do you mean by the dark grey element? 
I tried putting a border-radius on almost every concerned elements with no results :/
My window is on light vibrancy

**Comment by tommoor** [comment] 2018-02-22 18:08
Try putting border-radius on `*`, just to check.

**Comment by vincelwt** [comment] 2018-02-22 18:21
@tommor Ok the issue was with the latest beta of Electron. 1.8.2 is working as you say, thanks

**Comment by tommoor** [comment] 2018-02-22 18:23
Oh no - I wonder if it got worse because of the fix for https://github.com/electron/electron/pull/11886 ? If I have to choose between which of these bugs to put up with it's going to be really frustrating.

@MarshallOfSound any chance your fix affected this?

**Comment by okonet** [comment] 2018-02-23 13:23
I can confirm this is still an issue: the combination of `frame: false` and `transparent: true` removes rounded corners on the top of the window :(

**Comment by HuChundong** [comment] 2018-02-27 01:44
is this issue in schedule？

**Comment by tommoor** [comment] 2018-04-14 00:26
This is definitely a bug – and one that makes vibrant windows in `2.0` unusable for a production application. [My workaround](https://github.com/electron/electron/issues/10886#issuecomment-359130267) did the trick in `1.7` but no longer works in `2.0`

@sofianguy could you label it bug instead of enhancement?

**Comment by PhoenixFieryn** [comment] 2018-04-14 01:00
I'm getting something similar here. The menu bar refuses to adopt the vibrancy effect. It's just strangely transparent.
<img width="176" alt="screen shot 2018-04-13 at 5 59 17 pm" src="https://user-images.githubusercontent.com/4925624/38762764-7bc5fed4-3f44-11e8-8148-92f8e1c4db25.png">

**Comment by natew** [comment] 2018-05-02 23:58
Separately, does this bug let you do non-vibrant transparent windows *without* border radius? Would be a nice bug for me.

**Comment by npezza93** [comment] 2018-07-13 00:05
This looks to be resolved in v3 beta2

**Comment by pmkary** [comment] 2018-07-26 11:50
I'm on version `2.0.5` and I also can spot the problem. I also tried `border-radius` on various possible elements and it did not work.

<img width="229" alt="screen shot 1397-05-04 at 4 18 44 pm" src="https://user-images.githubusercontent.com/2157285/43260786-acece746-90ef-11e8-957d-6527b5ac4cc3.png">

**Comment by gastonmorixe** [comment] 2018-08-13 17:16
any update on this?

**Comment by ryanbadger** [comment] 2018-08-23 08:27
Confirmed still an issue on "electron": "^2.0.7"
When using titleBarStyle: 'customButtonsOnHover', and frame: false, window edges become square, and not rounded. If you remove customButtonsOnHover, it's fine...

**Comment by bjoernm** [comment] 2019-06-18 09:47
#10424 is a separate issue dedicated to the problem of using titleBarStyle: 'customButtonsOnHover', and frame: false leading to window corners not being rounded.

**Comment by natew** [comment] 2019-09-05 23:36
I've opened a PR with a fix for it here: https://github.com/electron/electron/pull/20141

**Comment by Jip-Hop** [comment] 2019-09-08 15:55
Would it be possible to keep this behaviour (non rounded corners) as an option? I make use of it for a video application and I've seen others requesting the behaviour too: https://github.com/electron/electron/issues/414.

**Comment by natew** [comment] 2019-09-09 16:55
@Jip-Hop I would suggest we do it in two parts: part one, restore the original functionality. Part two, add an option for either `borderRadius: true/false` or `borderRadius: 10`.

If I was more comfortable with the whole framework/repo/language I'd happily try to make that work, but given it's fairly foreign and seems like there's not much help with PR's to start, I'd err on the side of conservative to start.

Feel free to open a follow-on PR to mine that adds that configuration, then perhaps they can both go into master.

**Comment by zcbenz** [comment] 2020-12-02 06:06
This had been fixed by https://github.com/electron/electron/pull/20360.

**Closed by zcbenz** 2020-12-02 06:06 UTC
Labels: 2-0-x, enhancement :sparkles:, platform/macOS, version/1.8.x
