### ISSUE TITLE
will-navigate preventDefault doesn't work on webviews when called in the render

### ISSUE THREAD

**Issue by frozeman** [electron/electron#8008] opened 2016-11-17 22:40 UTC
* Electron version: 1.4.7
* Operating system: OSX 10.12.1

### Expected behavior

```js
// in the render
var webview = document.querySelector('webview');

webview.addEventListener('will-navigate', function(e){
    e.preventDefault(); // should prevent webview navigation

    console.log(e);
    // e.defaultPrevented: false
});
```

Also `webview.stop()` has no effect.

### Actual behavior

The webview navigates to the target

### How to reproduce

See code above.

**Comment by kevinsawicki** [comment] 2016-11-17 22:44
I believe this is a duplicate of #1378, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2016-11-17 22:44 UTC
