### ISSUE TITLE
Problems on how menu shows on RTL Windows

### ISSUE THREAD

**Issue by netanelrevah** [electron/electron#2112] opened 2015-07-03 07:04 UTC
I'm using Atom 1.0, with Hebrew (RTL) Windows 8.1.
It's happanning also with the updated version of VSCode.

The menu is on the right side of the screen although it's english.
When I'm reducing the window size, the menu disappear (See screenshot).
It's also disappear somtimes when I'm hovering the menu with the mouse but I couldn't cache it.

![screenshot](https://cloud.githubusercontent.com/assets/5959136/8494048/bf7cfc32-2169-11e5-8a74-635d8bbbd937.png)

**Comment by zcbenz** [comment] 2015-07-06 01:36
Hmm I don't have a RTL Windows to test this, so I'm leaving this open in case someone can verify it.

**Comment by the-curator** [comment] 2015-07-09 19:37
OK, Thank you.

**Comment by ozsay** [comment] 2015-10-10 14:44
@zcbenz The native menu in atom is always on the right side for me (Win 7 64bit RTL).

Is it a bug? or perhaps electron should have a feature of choosing the side of the menu.

BTW, The same happens in an app I'm developing using electron.

**Comment by zcbenz** [comment] 2015-10-10 15:11
@ozsay I never used a RTL system before, should the menu show on the left side?

**Comment by netanelrevah** [comment] 2015-10-10 16:28
It should be on the right side when the UI language is written RTL, and on the left side otherwise. Currently the UI language is English but the menu is on the right side (Apparently by some default property).

**Comment by ozsay** [comment] 2015-10-10 22:12
Yeah, that sums it up.

@zcbenz Should I open a feature request for changing the menu direction and side?

**Comment by zcbenz** [comment] 2015-10-11 07:24
@ozsay I think we can track it in this issue since it is about menu on RTL system anyway.

**Comment by nitzanbueno** [comment] 2017-02-05 12:35
Bumping this issue because it's really annoying.

Normally the way to fix this in other programs involves changing the language from Hebrew to English, or deleting/renaming the "he" locale dll in the program.

**Comment by brenca** [comment] 2017-05-21 22:04
Is this still a problem in simple electron applications? You can try the RTL layout out with the `--force-ui-direction=rtl` command line argument. I ran into some problems with the default menu (locations calculated without respect to RTL, I have fixed that in the datalist PR), but the menu did not disappear for me when resizing.

**Comment by codebytere** [comment] 2018-01-19 21:24
There has been no follow-up on this issue for some time, so i'm going to go ahead and close it. If this is still a bug on recent versions of electron, please reach out and I will re-open this issue.

**Closed by codebytere** 2018-01-19 21:24 UTC
Labels: component/menu, fixme/bug, platform/windows

**Comment by abuassar** [comment] 2018-02-08 21:18
I can confirm that this issue still exists, using the latest version of electron.

I'm using windows 10 1709 with arabic gui language (which is RTL), and electron menu appears on the right. Just give me an option to move it to the left, even an env variable will be enough.

![vscode-electron-rtl](https://user-images.githubusercontent.com/2022065/35998662-01016fbc-0d26-11e8-897f-d216414ac26c.png)
