### ISSUE TITLE
Cannot specify browserWindow option on dialog.showMessageBox when browserWindow is an instance of a subclass of BrowserWindow

### ISSUE THREAD

**Issue by arantes555** [electron/electron#8895] opened 2017-03-10 15:24 UTC
* Electron version: tested on 1.6.2, but same on all versions
* Operating system: All

### Expected behavior

When you subclass `BrowserWindow`, you shoud be able to use instances of these subclasses as arguments for `dialog.showMessageBox`.

### Actual behavior

When you subclass `BrowserWindow`, you cannot use instances of these subclasses as arguments for `dialog.showMessageBox` .

### How to reproduce

- Subclass `BrowserWindow` with a custom constructor.
- Try using an instance of that class as argument of `dialog.showMessageBox`.
- You get an empty message box.

### What actually happens.

The code at `lib/browser/api/dialog.js:24` checks for `window.constructor !== BrowserWindow`.
In that case, the first argument is interpreted as an options argument.
It should instead use the `instanceof` operator.
With a quick search on the repo, this happens at at least 3 places of electron's code :
 
https://github.com/electron/electron/blob/d4a8a64ba7be50906ed5116669b7c06d8da3574f/lib/browser/api/menu-item.js line 15 which checks for `Menu` constructor
https://github.com/electron/electron/blob/d01250eceb6d567378df1de44b5631246c1a523b/lib/browser/api/menu.js line 150 which checks for `BrowserWindow` constructor
https://github.com/electron/electron/blob/8c2cf03f378008baf2cb31050795ac9c929411b0/lib/browser/api/dialog.js line 24 which checks for `BrowserWindow` constructor

**Comment by enlight** [comment] 2017-03-10 15:30
Duplicate of #8219

**Closed by enlight** 2017-03-10 15:30 UTC
