### ISSUE TITLE
Top of window with "hiddenInset" title bar becomes unresponsive after exiting fullscreen

### ISSUE THREAD

**Issue by javan** [electron/electron#16418] opened 2019-01-16 13:46 UTC
* Output of `node_modules/.bin/electron --version`: v4.0.1
* Operating System (Platform and Version): macOS 10.14.2

**Expected Behavior**
The top of the window should continue responding to clicks after exiting from fullscreen.

**Actual behavior**
The top ~40px stops responding to clicks after exiting from fullscreen. 

**To Reproduce**
1. Clone and run https://github.com/javan/electron-quick-start/tree/hidden-inset-mojave
1. Click the black bar at the top of the window. It should turn purple while the mouse is down.
1. Enter and exit fullscreen.
1. Click the top of the window and note that it no longer turns purple.

```
$ git clone https://github.com/javan/electron-quick-start.git -b hidden-inset-mojave
$ npm install
$ npm start
```

**Screenshots**
![electron-fullscreen-clicks](https://user-images.githubusercontent.com/5355/51252742-93e50b80-196a-11e9-977d-13da6324bf1a.gif)

**Additional Information**
This issue is quite similar to https://github.com/electron/electron/issues/14529.

**Comment by olafuria** [comment] 2019-01-21 13:41
We are also seeing this in Tidal update we are working on.

**Comment by littlecold233** [comment] 2019-01-22 03:08
I have the same problem！！！

How Could I fix that？It's really strange

**Comment by littlecold233** [comment] 2019-01-22 03:56
@javan  **set the titleBarStyle `hidden` fix the issue** 

I just test `hidden` and `hiddenInset` for my BrowserWindow and I find `hidden` works much better then `hiddenInset`

**Comment by nathanlesage** [comment] 2019-01-25 14:18
I second that. Using `hidden` and having the buttons placed very close to the edge of the frame would require me to overthink my whole toolbar design in Zettlr, which I'd like to avoid. Besides, Chrome, e.g. also uses the hiddenInset way of displaying the traffic lights, but still does not expose the strange unresponsiveness after exiting fullscreen.

Besides, what I noted is that in fullscreen the window uses an extra-high titlebar, which is normally indicative of websites that go in a "fake fullscreen" mode (I'll just call it that, because something different happens there, but I don't know what). Chrome for some time had used this "thick frame" mode as well. Maybe electron is using the same "fake" fullscreen (that is not used anymore in Chrome) as well and that's causing the problems?

To show what I mean: if you put an app into fullscreen mode, e.g. Chrome, or Safari, and go to the very top with your mouse, you'll see a standard-height titlebar:

![image](https://user-images.githubusercontent.com/17251683/51750889-b0441f00-20b3-11e9-83ad-2ed87bde143f.png)

But compare this to an electron app using `hiddenInset`:

![image](https://user-images.githubusercontent.com/17251683/51750951-e08bbd80-20b3-11e9-9b60-a4f84a584f7e.png)

The titlebar is twice the size, so it seems to be something that happens with the native Window controller on macOS. I'm not a Swift/Apple native programmer so I wouldn't know where to look, but maybe have a look there?

What I also tested and can confirm it does not work:

- Show the window title in fullscreen
- Force-reload the CSS-Stylesheets with the draggable-region directives in them

**Comment by nathanlesage** [comment] 2019-01-27 10:47
Some updates. I did some digging into what might be the cause.

1. To achieve the inset traffic lights, Electron uses a Toolbar with no buttons, makes it transparent and click-through.
2. After exiting the fullscreen precisely the area of the toolbar becomes unclickable. Still, it is strange that the hovering still works.
3. Can confirm that Electron 3.1.2 on macOS Mojave 10.14.2 works and buttons stay responsive. I still haven't been able to pinpoint what has changed from 3.1.2 to 4.0.2 what might cause this issue.

**Comment by issacgerges** [comment] 2019-02-05 17:32
From some testing with fiddle, this appears to have started in `4.0.0-beta.1` and stops appearing in `5.0.0-beta.1`.

**Comment by circleapps** [comment] 2019-03-21 02:18
Good to know this issue has been addressed.
Could you please kindly let me know whether it will be fixed in the recently build of electron 4.x or not? 
I'm thinking about choosing between waiting electron 5.x going public or the fix for this issue for 4.x.
Thanks.

**Comment by codebytere** [comment] 2019-03-21 19:27
I'm fairly certain that this was fixed via Chromium upgrade in 5, so i'd proceed with that information in mind.

**Closed by codebytere** 2019-03-21 19:27 UTC
Labels: 4-1-x, app-feedback-program, bug :beetle:, platform/macOS

**Comment by knopp** [comment] 2019-06-08 22:05
VSCode just picked up Electron 4 for insider builds. Any chance of backporting this?
