### ISSUE TITLE
Support printing in native PDF rendering

### ISSUE THREAD

**Issue by rreimann** [electron/electron#9029] opened 2017-03-27 12:29 UTC
Electron [1.6.4 beta](https://github.com/electron/electron/releases/tag/v1.6.4) added support for native PDF rendering https://github.com/electron/electron/pull/8435

Currently the native PDF rendering view [doesn't support printing](https://github.com/electron/electron/pull/8435#issuecomment-286838827) - it would be nice if printing support could be added.

**Comment by setpixel** [comment] 2017-03-30 02:08
Just to +1, I would love this. Generating pdfs and printing them cross platform would be great, as printing support via css is, you know, very :/

**Comment by setpixel** [comment] 2017-04-21 08:07
Hi friends! I'm working on an app that needs to print documents. On the mac, there are some built in facilities to print pdfs natively. However on the PC, there is no such support. Adding the ability to print a PDF would be super excellent in standardizing a method of printing.

I'm curious what you guys think?

**Comment by timfish** [comment] 2017-05-01 18:06
This would be great as currently printing to landscape requires the user to select landscape after printing in their printer settings. 

I could remove my printing support completely and let the user print the generated PDF's where I can force landscape.

**Comment by setpixel** [comment] 2017-05-15 15:54
YESS!!! How can I help?

**Comment by timfish** [comment] 2017-06-27 11:14
It looks like much of the PDF printing functionality is already there: 
https://github.com/electron/electron/blob/e0b9395a133d85e51143842b63bcf6855910f0ab/chromium_src/chrome/browser/printing/print_view_manager_base.cc#L174

It would be great if this API was exposed directly as well as in the native PDF viewer.

**Comment by MichaelIT** [comment] 2017-07-04 03:48
I found a way work on *nix & windows OS after download/save pdf file.
on *ninx u can use `lpr test.pdf`
on windows, u can use `SumatraPDF.exe -print-to-default -slient test.pdf`.
It was not perfect on windows, because SumatraPdf.exe was too large for print pdf file.
It will be great to support print pdf with electron api.

**Comment by moritzhasse** [comment] 2017-07-05 08:38
Would love to see that feature too. No workaroud needed like: download pdf, open in local pdf viewer and print.

**Comment by tonyski** [comment] 2017-12-27 07:16
+1
It will be very helpful !

**Comment by jampy** [comment] 2018-01-07 21:54
any news on this? currently a blocker for me..

**Comment by setpixel** [comment] 2018-01-07 22:01
+2

**Comment by mathieupothier** [comment] 2018-02-22 18:28
+1

**Comment by patrickrobbins** [comment] 2018-02-27 16:01
+1

**Comment by 0x13R** [comment] 2018-04-02 03:04
Any new on this?

**Comment by setpixel** [comment] 2018-04-02 15:56
@timfish why do you thumbsdown their comments?

**Comment by zer09** [comment] 2018-04-04 03:47
@setpixel might be he doesn't like "+1's" comment on the issue, it just giving unnecessary noise. putting :+1:  on the main comment is much better.

**Comment by zoftc** [comment] 2018-04-26 08:27
any update on pdf print ?

**Comment by gavi** [comment] 2018-06-05 15:59
This feature would be very helpful

**Comment by davidnorthetal** [comment] 2018-06-25 13:55
How would first steps for this look like?

**Comment by noserati** [comment] 2018-08-13 20:30
[Linking this request from StackOverflow](https://stackoverflow.com/q/49650784/1768303). I've put a bounty on that question.

**Comment by burningTyger** [comment] 2019-01-23 15:31
Since PDF is broken since v3 I have resorted to this:

    import { shell } from 'electron'
    shell.openItem(pdfPath)

You do have to store the pdf though but since there is always some kind of pdf viewer on a users pc this should be ok.

**Comment by codebytere** [comment] 2020-03-24 16:55
Closed in https://github.com/electron/electron/pull/22760.

**Closed by codebytere** 2020-03-24 16:55 UTC
Labels: component/printing, enhancement :sparkles:

**Comment by benwmills** [comment] 2021-04-15 14:54
This would be so nice instead of having to install some kind of external PDF viewer and running shell commands.

Does Electron have access to the print button action that is built into Chromium?  I wonder if the problem is that you can load a PDF into a window, but there's no class that represents the PDF viewer.  If we had that class, then we'd obvious want a print method, but other actions like next page and zoom would also be useful at times.

**Comment by inacio0196** [comment] 2021-08-03 02:15
Any news about functionality?
