### ISSUE TITLE
Crash on accessing non-existing array item in sendSync

### ISSUE THREAD

**Issue by zarubond** [electron/electron#23849] opened 2020-05-29 13:05 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.2.3, 7.3.0
* **Operating System:**
  * Window 10, 8
* **Last Known Working Electron version:**
  * 7.1.11

### Expected Behavior
Electron should not crash whole sensing sendSync

### Actual Behavior
Electron crashes while sending sync IPC call from renderer here https://github.com/electron/electron/blob/7-3-x/shell/renderer/api/atom_api_renderer_ipc.cc#L105 because it is trying to access element of which does not exists on array size 0.

### To Reproduce
Stack trace
`    wkernelbase.pdb
    0x77824402 + 1131522
    electron.exe.pdb
    _CxxThrowException throw.cpp:129
    electron.exe.pdb
    std::_Xout_of_range(char const *) xthrow.cpp:23
    electron.exe.pdb
    std::vector<SkBitmap,std::allocator<SkBitmap> >::_Xrange() vector:1931
    electron.exe.pdb
    class base::Value ``anonymous namespace'::IPCRenderer::SendSync(bool, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > & const, class base::ListValue) atom_api_renderer_ipc.cc:121
    electron.exe.pdb
    static class base::Value base::internal::FunctorTraits<base::Value ((anonymous namespace)::IPCRenderer::*)(bool, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, base::ListValue) __attribute__((thiscall)),void>::Invoke<base::Value ((anonymous namespace)::IPCRenderer::*)(bool, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, base::ListValue) __attribute__((thiscall)),(anonymous namespace)::IPCRenderer *,bool,const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &,base::ListValue>( *, class ``anonymous namespace'::IPCRenderer * *, bool *, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > & const, class base::ListValue *) bind_internal.h:499
    electron.exe.pdb
    static class base::Value base::internal::Invoker<base::internal::BindState<base::Value ((anonymous namespace)::IPCRenderer::*)(bool, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, base::ListValue) __attribute__((thiscall))>,base::Value ((anonymous namespace)::IPCRenderer *, bool, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, base::ListValue)>::Run(class base::internal::BindStateBase *, class `anonymous namespace'::IPCRenderer *, bool, const class std::basic_string<char,std::char_traits<char>,std::allocator<char> > & const, class base::ListValue *) bind_internal.h:654
    electron.exe.pdb
    static void mate::internal::Invoker<mate::internal::IndicesHolder<0,1,2,3>,(anonymous namespace)::IPCRenderer *,bool,const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &,base::ListValue>::DispatchToCallback<base::Value>(class base::RepeatingCallback<base::Value ((anonymous namespace)::IPCRenderer *, bool, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, base::ListValue)>) function_template.h:202
    electron.exe.pdb
    static void mate::internal::Dispatcher<base::Value ((anonymous namespace)::IPCRenderer *, bool, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &, base::ListValue)>::DispatchToCallback(const class v8::FunctionCallbackInfo<v8::Value> & const) function_template.h:246
    electron.exe.pdb
    v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) api-arguments-inl.h:158
    electron.exe.pdb
    static class v8::internal::MaybeHandle<v8::internal::Object> v8::internal::``anonymous namespace'::HandleApiCallHelper<0>(class v8::internal::Isolate *, class v8::internal::Handle<v8::internal::HeapObject>, class v8::internal::Handle<v8::internal::HeapObject>, class v8::internal::Handle<v8::internal::FunctionTemplateInfo>, class v8::internal::Handle<v8::internal::Object>, class v8::internal::BuiltinArguments) builtins-api.cc:111
    electron.exe.pdb
    static class v8::internal::Object v8::internal::Builtin_Impl_HandleApiCall(class v8::internal::BuiltinArguments, class v8::internal::Isolate *) builtins-api.cc:141
    electron.exe.pdb
    v8::internal::Builtin_HandleApiCall(int,unsigned int *,v8::internal::Isolate *) builtins-api.cc:129
    electron.exe.pdb
    Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_ArrayForEach
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_ArrayForEach
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_ArrayForEach
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_ArrayForEach
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_ArrayForEach
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_ArrayForEach
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_ArrayForEach
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_ArrayForEach
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_InterpreterEntryTrampoline
    electron.exe.pdb
    Builtins_ArgumentsAdaptorTrampoline
    electron.exe.pdb
    Builtins_JSEntryTrampoline
    electron.exe.pdb
    Builtins_JSEntry
    electron.exe.pdb
    static class v8::internal::MaybeHandle<v8::internal::Object> v8::internal::`anonymous namespace'::Invoke(class v8::internal::Isolate *, const struct v8::internal::`anonymous namespace'::InvokeParams & const) execution.cc:266
    electron.exe.pdb
    v8::internal::Execution::Call(v8::internal::Isolate *,v8::internal::Handle<v8::internal::Object>,v8::internal::Handle<v8::internal::Object>,int,v8::internal::Handle<v8::internal::Object> * const) execution.cc:358
    electron.exe.pdb
    v8::Function::Call(v8::Local<v8::Context>,v8::Local<v8::Value>,int,v8::Local<v8::Value> * const) api.cc:4883
    electron.exe.pdb
    blink::V8ScriptRunner::CallFunction(v8::Local<v8::Function>,blink::ExecutionContext *,v8::Local<v8::Value>,int,v8::Local<v8::Value> * const,v8::Isolate *) v8_script_runner.cc:470
    electron.exe.pdb
    blink::V8EventHandlerNonNull::InvokeWithoutRunnabilityCheck(blink::bindings::V8ValueOrScriptWrappableAdapter,WTF::Vector<blink::ScriptValue,0,WTF::PartitionAllocator> const &) v8_event_handler_non_null.cc:372
    electron.exe.pdb
    blink::JSEventHandler::InvokeInternal(blink::EventTarget &,blink::Event &,v8::Local<v8::Value>) js_event_handler.cc:122
    electron.exe.pdb
    blink::JSBasedEventListener::Invoke(blink::ExecutionContext *,blink::Event *) js_based_event_listener.cc:152
    electron.exe.pdb
    blink::EventTarget::FireEventListeners(blink::Event &,blink::EventTargetData *,blink::HeapVector<blink::RegisteredEventListener,1> &) event_target.cc:926
    electron.exe.pdb
    blink::EventTarget::FireEventListeners(blink::Event &) event_target.cc:840
    electron.exe.pdb
    blink::EventTarget::DispatchEventInternal(blink::Event &) event_target.cc:747
    electron.exe.pdb
    blink::XMLHttpRequestProgressEventThrottle::DispatchReadyStateChangeEvent(blink::Event *,blink::XMLHttpRequestProgressEventThrottle::DeferredEventAction) xml_http_request_progress_event_throttle.cc:137
    electron.exe.pdb
    blink::XMLHttpRequest::DispatchReadyStateChangeEvent() xml_http_request.cc:592
    electron.exe.pdb
    blink::XMLHttpRequest::EndLoading() xml_http_request.cc:1783
    electron.exe.pdb
    blink::XMLHttpRequest::DidFinishLoadingInternal() xml_http_request.cc:1732
    electron.exe.pdb
    blink::XMLHttpRequest::DidFinishLoading(unsigned __int64) xml_http_request.cc:1707
    electron.exe.pdb
    blink::ThreadableLoader::NotifyFinished(blink::Resource *) threadable_loader.cc:943
    electron.exe.pdb
    blink::Resource::NotifyFinished() resource.cc:240
    electron.exe.pdb
    blink::Resource::Finish(base::TimeTicks,base::SingleThreadTaskRunner *) resource.cc:375
    electron.exe.pdb
    blink::ResourceFetcher::HandleLoaderFinish(blink::Resource *,base::TimeTicks,blink::ResourceFetcher::LoaderFinishType,unsigned int,bool) resource_fetcher.cc:1816
    electron.exe.pdb
    blink::ResourceLoader::DidFinishLoading(base::TimeTicks,__int64,__int64,__int64,bool) resource_loader.cc:1177
    electron.exe.pdb
    blink::ResourceLoader::DidFinishLoadingBody() resource_loader.cc:532
    electron.exe.pdb
    blink::ResponseBodyLoader::OnStateChange() response_body_loader.cc:472
    electron.exe.pdb
    base::TaskAnnotator::RunTask(char const *,base::PendingTask *) task_annotator.cc:142
    electron.exe.pdb
    base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow *,bool *) thread_controller_with_message_pump_impl.cc:365
    electron.exe.pdb
    base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork() thread_controller_with_message_pump_impl.cc:218
    electron.exe.pdb
    base::MessagePumpDefault::Run(base::MessagePump::Delegate *) message_pump_default.cc:39
    electron.exe.pdb
    base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool,base::TimeDelta) thread_controller_with_message_pump_impl.cc:463
    electron.exe.pdb
    base::RunLoop::Run() run_loop.cc:156
    electron.exe.pdb
    content::RendererMain(content::MainFunctionParams const &) renderer_main.cc:213
    electron.exe.pdb
    content::RunOtherNamedProcessTypeMain(std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,content::MainFunctionParams const &,content::ContentMainDelegate *) content_main_runner_impl.cc:581
    electron.exe.pdb
    content::ContentMainRunnerImpl::Run(bool) content_main_runner_impl.cc:874
    electron.exe.pdb
    content::ContentServiceManagerMainDelegate::RunEmbedderProcess() content_service_manager_main_delegate.cc:52
    electron.exe.pdb
    service_manager::Main(service_manager::MainParams const &) main.cc:423
    electron.exe.pdb
    content::ContentMain(content::ContentMainParams const &) content_main.cc:19
    electron.exe.pdb
    wWinMain atom_main.cc:177
    electron.exe.pdb
    static int __scrt_common_main_seh() exe_common.inl:288
    wkernel32.pdb
    0x752e6359 + 90969
`

**Comment by MarshallOfSound** [comment] 2020-05-30 09:59
This is fixed in Electron 8 / 9 and as the underlying IPC implementation was refactored.  That refactor unfortunately can't be backported so if this crash is causing you a lot of issues I suggest upgrading to Electron 8

**Comment by ckerr** [comment] 2020-06-09 21:17
There are two bugs going on here.

1. The root cause is exactly as @MarshallOfSound says, that the IPC refactor that comes in newer versions of Electron is the real fix. Also, it doesn't make sense to backport a change of that size to the 7-x-y series as it reaches end-of-life.

2. However there is the specific bug here that we're crashing instead of failing gracefully when IPC does fail, because of the lack of bounds-checking in the ListValue's vector. IMO it could make sense to fix this issue so that at least Electron doesn't crash when hitting this case. **Note: even so, this only addresses the symptom. The real fix is to upgrade to a newer version of Electron.**

**Comment by codebytere** [comment] 2020-11-12 22:55
Closed in https://github.com/electron/electron/pull/24041

**Closed by codebytere** 2020-11-12 22:55 UTC
Labels: 7-3-x, bug/crash :boom:, platform/windows
