### ISSUE TITLE
Spellchecker is not initialised for iframes inside webviews in electron@7.x.x

### ISSUE THREAD

**Issue by Syed-Umair** [electron/electron#21729] opened 2020-01-10 14:15 UTC
### Issue Details

* **Electron Version:** 7.1.8

* **Operating System:** macOS 10.15.2/Windows 10
* **Last Known Working Electron version:** 4.1.4

### Expected Behavior

with Site Isolation enabled in electron 7.x, When I execute
```javascript
webFrame.setSpellCheckProvider("en-US", {
  spellCheck(words, callback) {
    setTimeout(() => {
     const misspelled = words.filter((text) => checker.isMisspelled(text));
     callback(misspelled);
    }, 0);
  }
});
```
Spellchecker is not working inside the iframes but works in the top webview.

Provided, it works if I disable site isolation trials using 
```app.commandLine.appendSwitch('disable-site-isolation-trials', 'true');```

### Actual Behavior

Irrespective of site isolation feature setting, We should be able to set spellchecker for the entire webview including the iframes.
Thanks.

### To Reproduce

```
git clone https://github.com/Syed-Umair/electron-quick-start.git
git checkout spellcheck-issue
npm i
npm run start
```
You can checkout the recording of the issue in the following link:

https://mega.nz/#!1M0lUY4Z!j1snymVCCsNZMafzF5RKLR84PcpoLzdeqc4NVOwOwLk

**Comment by vladimiry** [comment] 2020-01-10 18:16
Spellchecker is working for me inside the iframes but those are dynamically created iframes used for rich-content-editing purposes. So there is no remote-loaded/from-other-domains content in those iframes and that's why I guess it works for me without any switches.

**Comment by vladimiry** [comment] 2020-01-10 18:19
By the way, this issue might be a duplicate of #21324.

**Comment by Syed-Umair** [comment] 2020-01-11 08:42
Yes, @vladimiry spellchecker works when i load same origin iframes but most of the cases in my app i have to embed non related domains. It would be great to have spellchecker with site isolation enabled.

**Comment by Syed-Umair** [comment] 2020-10-15 16:15
In electron 10x, spellchecker is supported by default in electron and it works like a charm.

**Closed** 2020-10-15 16:16 UTC
Labels: 7-1-x, bug :beetle:, platform/macOS, platform/windows

**Comment by vladimiry** [comment] 2020-10-15 17:54
> it works like a charm.

Not yet, https://github.com/electron/electron/issues/22995.
