### ISSUE TITLE
"blur" event not emitted when "always-on-top" option is set to true

### ISSUE THREAD

**Issue by mkozakov** [electron/electron#3222] opened 2015-10-26 16:10 UTC
This code does nothing on Ubuntu:

<code>
mainWindow.on('blur', function() {
            console.log("blur")        });
    }
</code>

**Comment by zcbenz** [comment] 2015-10-27 02:57
I'm not able to reproduce, which version of Electron are you using? And what's the version and desktop environment of Ubuntu?

**Comment by mkozakov** [comment] 2015-10-29 16:54
This is running on Ubuntu 12.04, with Electron 0.34.1

**Comment by mkozakov** [comment] 2015-10-29 17:32
After more investigation, it seems that the "blur" event on Ubuntu and Windows is not being fired IF the "always-on-top" option is set to True. But this is not the behavior on OS X.

**Comment by zcbenz** [comment] 2016-05-06 11:26
After looking into it I'm afraid this is a platform limitation on Windows and Linux, so on those platforms the system would "lock" the app into focused state when it is in the alwaysOnTop state, and the blur event will never emit. So I'm closing this as won't fix.

**Closed by zcbenz** 2016-05-06 11:26 UTC
Labels: bug, linux, windows

**Comment by avalanche1** [comment] 2021-08-10 18:12
This is also the case on macOS 10.14.6
