### ISSUE TITLE
Support before dialog event that can be canceled

### ISSUE THREAD

**Issue by renambot-uic** [electron/electron#9011] opened 2017-03-25 02:11 UTC
I would like to be able to capture (or cancel) the native file open dialog.
It is possible for 'download/save' by catching the 'will-download' event. I would like the same for the file selection.

Basically I need to control all native UI element (popup, dialogs, ...).
Does it make sense?

thanks.

**Comment by zcbenz** [comment] 2017-06-14 11:54
Duplicate of #5577.

**Closed by zcbenz** 2017-06-14 11:54 UTC
Labels: component/dialog, enhancement
