### ISSUE TITLE
Menus being covered by the window content on Windows 10 build 15025.rs_prerelease

### ISSUE THREAD

**Issue by be5invis** [electron/electron#8562] opened 2017-02-02 08:31 UTC
cc. https://github.com/Microsoft/vscode/issues/19698
Another image, from https://www.zhihu.com/question/55328189?group_id=810523368477581312
![](https://pic1.zhimg.com/v2-c170ddc40bf0a06eebfbf6bca20e2a10_b.jpg)

**Comment by be5invis** [comment] 2017-02-02 09:22
Feedback link: https://insider.windows.com/FeedbackHub/fb?contextid=52&feedbackid=04a842d2-6eed-4452-b96a-5c64e7c2b3eb&form=1

**Comment by be5invis** [comment] 2017-02-02 18:54
@gongminmin ← WDG DWM guy. May be related.

**Comment by groundwater** [comment] 2017-02-02 23:31
Hi @be5invis, what version of Electron is VSC using?

If you update Electron via `npm i electron@latest` can you reproduce the issue using the default app?

Regarding your link above, I am unable to see the content, it just says 

> This content is available only in FeedbackHub app through the Windows 10 Anniversary Update

**Comment by Rhywden** [comment] 2017-02-03 20:46
Okay, I found the source of the issue - it's the DPI scaling. If it's set to 200% or above (which is the default for a Surface Book with its 3000 by 2000 resolution) then I don't see the menus. If I set the scaling to anything below 200% (i.e. 175% to 100%) then it works normally again.

**Comment by madcampos** [comment] 2017-02-09 02:23
Tested with electron 1.4.10, got the same problem. It only happens with native menus.

**Comment by darwinkim** [comment] 2017-02-24 13:37
@Rhywden The main problem does not seem to be DPI scaling. Compatibility mode for DPI scaling has no effect. The issue returns after restarting or logging out and signing back in after setting the DPI to a lower value.

**Comment by darwinkim** [comment] 2017-02-24 13:44
Issue is not present when running application with the NVIDIA GPU on the Surface Book.

**Comment by darwinkim** [comment] 2017-02-25 18:18
The bug has been fixed on build 15042! Tested on VS Code and Electron API demos.

**Comment by madcampos** [comment] 2017-02-25 20:04
So it was a electron bug then, not a,windows one? 🤔
Also, setting it to use the gpu works and disabling the gpu resource consuming features, like antialiasing, helps on battery life

**Comment by alespergl** [comment] 2017-03-06 12:44
@darwinkim @be5invis Can you confirm that the problem went away?

**Comment by madcampos** [comment] 2017-03-06 12:55
In the latest fast ring build (15048) the bug is gone for surface book with 200% resolution.

**Comment by alespergl** [comment] 2017-03-06 13:01
OK. Since the original VS Code issue has been closed, I will close this as well. If anyone still experiences problems with this, we can reopen.

**Closed by alespergl** 2017-03-06 13:01 UTC
Labels: platform/windows, triage/bug
