### ISSUE TITLE
32bit Electron Browser window renders white screen on 64bit windows

### ISSUE THREAD

**Issue by weiway** [electron/electron#7049] opened 2016-08-31 17:25 UTC
- Electron version: 1.3.2, ia32
- Operating system: Windows 10, x64

32bit prebuilt electron renders a white screen,
No crash report from electron and browser devtool is disconnected

My app was trying to render a page with about 6 images (from aws s3), very shortly after done rendering images, the browser window goes white and devtool is disconnected.
This problem only happens on 64bit windows, works fine on 32bit windows

**Comment by zeke** [comment] 2016-08-31 20:15
Can you provide a minimal app that reproduces this problem?

**Comment by weiway** [comment] 2016-08-31 20:18
Basically what happend is that our app works fine on all other platforms, only have this problem with Windows ia32 build

**Comment by zcbenz** [comment] 2016-09-01 04:54
Can you try to use debuggers like WinDbg or Visual Studio to capture the stack trace? We have a few guides on this but it might be tough if you never did it before:
http://electron.atom.io/docs/development/debug-instructions-windows/
http://electron.atom.io/docs/development/setting-up-symbol-server/

If there is neither a reproducible example nor a stack trace, it would be impossible to solve this.

**Comment by weiway** [comment] 2016-09-01 21:14
ok, I'll see what I can do.

**Comment by hankbao** [comment] 2016-09-24 15:12
One of our customers reported this issue recently. It looks like that is a reproducible problem and it's related  exactly to a 32 bit electron running on a 64 bit Windows.

I'll try to capture the stack trace.

**Comment by kevinsawicki** [comment] 2016-11-16 23:44
> I'll try to capture the stack trace.

Closing this out until more information is provided. If you are still experiencing this issue please verify it is still happening on the latest Electron release and comment with reproduction steps or further debugging information, thanks.

**Comment by weiway** [comment] 2016-11-18 22:17
Sorry it took me this long to get back. I did manage to get the dump file

**Comment by timfish** [comment] 2017-02-06 22:18
I'm also seeing this quite reliably with 1.4.14 if our app is left open for a long time. White screen,  ia32 build on 64bit Windows, Dev tools disconnected. I'll try and get a dump file.

**Comment by hankbao** [comment] 2017-03-13 07:14
Hello, any update here?

**Comment by timfish** [comment] 2017-03-14 19:27
I'm no longer using 32bit builds on x64 and no longer see this issue. It does mean my installer is twice the size it could be.

**Comment by akdes** [comment] 2017-04-20 08:16
i have the same issue on Win10 32 with 64 CPU. White Screen, DevTools disconnected.
This is 24/7 unit... i get this after 30-50 hours

**Comment by timfish** [comment] 2017-04-20 08:24
A white screen just means the render process has crashed so it could be caused by many things.

One option is to hook the on crash event on webContents and restart you're crashed browser window.

**Comment by akdes** [comment] 2017-04-20 09:19
have you some example for me? process.on("crash"... not working for me

**Comment by timfish** [comment] 2017-04-20 09:39
For it to work, I had to do it in the main process, like this:
```
function createWindow() {
  win = new BrowserWindow({ ... });

  // if the render process crashes, reload the window
  win.webContents.on('crashed', () => {
    win.destroy();
    createWindow();
  });

  win.on('closed', () => {  win = null  })

  // and load the index.html of the app.
  win.loadURL( ... )
}

app.on('ready', createWindow);
```

**Comment by akdes** [comment] 2017-04-20 09:55
i hope it works for me, thank you!

**Comment by jhovgaard** [comment] 2017-08-27 20:44
Had the same issue. We found out that deleting the content of `%appdata%\[Your app name]` solved the problem. It seems to be corrupting something on some random crash.

**Comment by mnicic** [comment] 2018-02-19 20:56
@jhovgaard not solving problem for me... 32bit app, 32bit Windows, 64bit processor

**Comment by simongregory** [comment] 2018-02-28 20:04
@mnicic I don't have that hardware combination to confirm this works, but some of our users suffering from 'whitescreens' are reporting that deleting the `d3dcompiler_47.dll` file from the app directory works for them. It would be interesting to find out if it was the same for you.

**Comment by mnicic** [comment] 2018-02-28 20:27
Disappeared after updating Electron (and Node consequently) to the latest version, so i'm not able to reproduce it anymore...

**Comment by simongregory** [comment] 2018-03-01 09:09
Thanks @mnicic, we've not yet upgraded to v1.8.x so that sounds promising. Our user reports were against v1.7.3.

**Comment by dovk** [comment] 2018-09-21 21:05
It started with me today after doing an npm install on my project and it inadvertently installed Electron 3.0 which was just released. I tried to revert back to 2.0.9 which worked perfectly as of yesterday but it didn't help, the page does not render now. Nothing written above seems to help but I hope something will come up soon.

**Comment by amolngt** [comment] 2019-02-26 14:13
> Disappeared after updating Electron (and Node consequently) to the latest version, so i'm not able to reproduce it anymore...

Hello sir,

I am facing same issue .... my electron(v1.7.10) app going to run 365 days 24 hours...previously i was using ia32 package on 64bit... now m using x64 on 64 bit
node version v8.11.3
npm version 5.6.0
see following cmd....

electron-packager . --overwrite --asar=true --platform=win32 --arch=x64 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName="CompanyName" --version-string.FileDescription=CE --win32metadata.requested-execution-level=requireAdministrator --version-string.ProductName="project_name"

will it be useful ?
should i update my electron

**Comment by amolngt** [comment] 2019-02-28 05:06
> Disappeared after updating Electron (and Node consequently) to the latest version, so i'm not able to reproduce it anymore...



> Thanks @mnicic, we've not yet upgraded to v1.8.x so that sounds promising. Our user reports were against v1.7.3.

i updated electron --- v4.0.6
m using 64bit windows OS
Packaging app for platform win32 x64 using electron v1.7.16-- command while packaging

blank screen after one day..
Please Help

**Comment by amolngt** [comment] 2019-02-28 11:25
> i have the same issue on Win10 32 with 64 CPU. White Screen, DevTools disconnected.
> This is 24/7 unit... i get it after 30-50 hours

problem solved?

**Comment by schontz** [comment] 2019-05-13 22:08
I'm running into the same issue as well. I want to test listening for the `crashed` event. Is there any way to test this, i.e., to force the renderer to crash?

**Comment by miniak** [comment] 2019-05-18 08:47
you can call `process.crash()` in the renderer process

**Comment by weifengsmile** [comment] 2019-12-03 14:35
I use electron2.0.9 and the exe built by x64 builder works on win64， but app built by ia32 builder is blank except menu bar on win64.
How should I do?

**Closed** 2021-03-09 17:11 UTC
Labels: bug :beetle:, platform/windows

**Comment by wangjunjie000** [comment] 2021-12-10 10:41
> d3dcompiler_47.dll

Thank you very much, you've been very helpful

**Comment by wangjunjie000** [comment] 2021-12-13 03:01
> For it to work, I had to do it in the main process, like this:
> 
> ```
> function createWindow() {
>   win = new BrowserWindow({ ... });
> 
>   // if the render process crashes, reload the window
>   win.webContents.on('crashed', () => {
>     win.destroy();
>     createWindow();
>   });
> 
>   win.on('closed', () => {  win = null  })
> 
>   // and load the index.html of the app.
>   win.loadURL( ... )
> }
> 
> app.on('ready', createWindow);
> ```
> 
> You can test it by terminating the render process and it should start again

Thank you very much, you've been very helpful
