### ISSUE TITLE
(registerStreamProtocol)the callback cannot process set-cookie on the response headers

### ISSUE THREAD

**Issue by 952185530** [electron/electron#29473] opened 2021-06-02 06:37 UTC
> **I'm use the onBeforeRequest to intercept my request and redirect to my protocol "app",but,when i use the http.request(nodejs) to make a request(a set-cookie will come with the response),let this registerStreamProtocol‘s callback process the response,and then , I'm lose the  set-cookie.’**

> How do I get this set-cookie

> electron@9.3.1

**Comment by Prinzhorn** [comment] 2021-06-02 07:34
I think this is a duplicate of https://github.com/electron/electron/issues/23865

**Comment by 952185530** [comment] 2021-06-02 07:49
> 我认为这是#23865的重复[](https://github.com/electron/electron/issues/23865)

yes,I think so,but I can't find a solution in it.Thank you for your reply !

**Comment by 952185530** [comment] 2021-06-02 09:29
> 我认为这是#23865的重复[](https://github.com/electron/electron/issues/23865)

I reread the issues several times,they use the net ,but I'm use the registerStreamProtocol.Are they the same thing?

**Comment by dsanders11** [comment] 2021-06-03 03:07
@952185530, can you provide a code example of the issue? It's not clear to me from your original description, since there are multiple APIs in use.

**Comment by nornagon** [comment] 2021-06-22 20:26
I'm closing this as there's not enough information here to take action.

**Closed by nornagon** 2021-06-22 20:26 UTC
Labels: blocked/need-repro
