### ISSUE TITLE
[v3.0.0-beta.1] command line switches not sent to window.

### ISSUE THREAD

**Issue by haroldiedema** [electron/electron#13392] opened 2018-06-22 23:15 UTC
* Electron Version: v3.0.0-beta.1
* Operating System (Platform and Version): Windows 10 x64
* Last known working Electron version:  v2.0.3

**Expected Behavior**
`app.commandLine.appendSwitch('enable-experimental-canvas-features');` should allow me to use `canvas.transferControlToOffscreen()`

**Actual behavior**
I'm getting an error stating that `transferControlToOffscreen` is not a function. This works by enabling the `--enable-experimental-canvas-features` flag, but the flag isn't sent to the "chromium process" I think?

**To Reproduce**
In your main process:
```js
app.commandLine.appendSwitch('enable-experimental-canvas-features');
```

In the renderer process:
```js
let canvas = document.createElement('canvas'),
    offscreen = canvas.transferControlToOffscreen();
```
The above code works fine on previous versions of Electron, but fails to run on 3.0.0-beta.1.
Also, I have enabled `experimentalFeatures` in the `BrowserWindow` options.

**Comment by codebytere** [comment] 2018-07-13 22:07
Reproduced this on Mac as well, will continue to investigate

**Comment by haroldiedema** [comment] 2018-07-14 11:20
Apparently, the experimental canvas features flag was removed from chromium entirely - at least for the flags page. I did find this https://peter.sh/experiments/chromium-command-line-switches/ although I think this list is not up-to-date anymore.

I'm unsure which flags I could use for testing - something that gives a visual output on the browser window or exposes certain API's. I can't get Blink features to work either, not just in electron but not in Google Chrome as well. Do you have anything that I could try out for this? Just to confirm that this issue is actually valid.

From what I gather from https://www.chromestatus.com/feature/5681560598609920 is that I'll be stuck on 61 until electron has a build with chromium 69+.

**Comment by codebytere** [comment] 2018-07-16 00:37
@brenca do you have any ideas? is there something we could potentially backport?

**Comment by deepak1556** [comment] 2018-07-16 04:05
As of CL https://chromium-review.googlesource.com/c/chromium/src/+/957646 , experimental canvas features has been merged to experimental web platform features. So with electron, users can simply enable `experimentalFeatures` webPreference option to use this feature. @codebytere we can remove `experimentalCanvasFeatures` option as its a noop.

**Comment by codebytere** [comment] 2018-07-16 04:07
will take care of that tomorrow morning! in the meantime @haroldiedema since there's a clear path forward for you on 3.0.0 betas i'm going to go ahead and close this!

**Closed by codebytere** 2018-07-16 04:07 UTC
Labels: bug :beetle:, bug/regression :leftwards_arrow_with_hook:, platform/macOS, platform/windows, status/reviewed, version/3.0.x

**Comment by deepak1556** [comment] 2018-07-16 04:12
@haroldiedema on separate note where did you find the commandLine switch `enable-experimental-canvas-features` in the electron docs ? We actually don't have support for that switch, it was a webPreference option since it was added. Would like to remove it if one is present in the docs to avoid confusion in the future, thanks!

**Comment by haroldiedema** [comment] 2018-07-16 06:35
@deepak1556 I found it on some website describing command line switches for Google Chrome I think. This was somewhere last year, I just tried it out and it seemed to do what I was looking for.


I just confirmed that setting `experimentalFeatures` to true sees to solve it. I feel ashamed the solution was so simple, haha 😅 

Offtopic: I don't know who thought of this limitation... How am I to resize my window after rendering has started?
```
Cannot resize canvas after call to transferControlToOffscreen().
```
Oh well... Thanks for the help guys!

**Comment by codebytere** [comment] 2018-07-16 18:18
@haroldiedema for sure! happy we could help :)

**Comment by mnesarco** [comment] 2021-04-05 00:11
Hi Friends,
I am trying to use Threejs with offscreen renderer (transferControlToOffscreen) without success.
I am using Electron 12.0.2 i have set `experimentalFeatures=true` but all that i get is a blank screen.

My code is based on this very simple example[1] that works in Chrome, and also works in electron if i set it to not use a worker. But if i se it so use the worker all that i get is a blank screen (no errors). I suppose it is beacuse i need to add some configuration to electron?

[1] https://github.com/puxiao/using-orbitcontrols-in-worker
