### ISSUE TITLE
Inconsistent appearance of accelerators containing an fn key shown in menu item

### ISSUE THREAD

**Issue by jddxf** [electron/electron#9209] opened 2017-04-17 06:36 UTC
* Electron version: 1.6.6
* Operating system: Win10

### Expected behavior
Consistent look of accelerators.

### Actual behavior

![electron](https://cloud.githubusercontent.com/assets/11155177/25081085/bc38afe8-237a-11e7-9d99-8dfadac0fcdc.png)
All fn keys have a space before them except F1 and F11
### How to reproduce
```  
const template = [{
    label: 'Edit',
    submenu: [{
      label: 'F1',
      accelerator: 'ctrl+f1'
    }, {
      label: 'F2',
      accelerator: 'ctrl+f2'
    }, {
      label: 'F3',
      accelerator: 'ctrl+f3'
    }, {
      label: 'F4',
      accelerator: 'ctrl+f4'
    }, {
      label: 'F5',
      accelerator: 'ctrl+f5'
    }, {
      label: 'F6',
      accelerator: 'ctrl+f6'
    }, {
      label: 'F7',
      accelerator: 'ctrl+f7'
    }, {
      label: 'F8',
      accelerator: 'ctrl+f8'
    }, {
      label: 'F9',
      accelerator: 'ctrl+f9'
    }, {
      label: 'F10',
      accelerator: 'ctrl+f10'
    }, {
      label: 'F11',
      accelerator: 'ctrl+f11'
    }, {
      label: 'F12',
      accelerator: 'ctrl+f12'
    }]
  }]
  const menu = Menu.buildFromTemplate(template)
```

**Comment by kevinsawicki** [comment] 2017-04-27 17:38
Hmm, I'm unable to reproduce this on Windows 10 using your example:

<img width="449" alt="screen shot 2017-04-27 at 10 37 48 am" src="https://cloud.githubusercontent.com/assets/671378/25496396/a65727e6-2b35-11e7-9543-4c0d4012feda.png">

Our fonts/zoom levels look like they might be different, what are you using?

**Comment by jddxf** [comment] 2017-04-28 11:44
It's really wierd. But I don't know what I'm using. Where can I get that information?

**Comment by kevinsawicki** [comment] 2017-04-28 15:54
> Where can I get that information?

Scale factor should be in the display settings, not sure where fonts are stored, also, what specific version of Windows 10 are you on?

**Comment by jddxf** [comment] 2017-04-28 16:02
I think I'm not using a scale setting. And I'm using a home edition of Windows 10.

**Comment by kevinsawicki** [comment] 2017-04-28 17:00
@jddxf what system language/locale are you using?

**Comment by jddxf** [comment] 2017-04-28 17:06
@kevinsawicki simplified Chinese

**Comment by kevinsawicki** [comment] 2017-04-28 17:09
> simplified Chinese

Thanks, can you check if you still see the issue using the English locale?

**Comment by jddxf** [comment] 2017-04-28 17:22
It still happens after I change system locale and reboot.

**Comment by zcbenz** [comment] 2017-06-20 07:21
I can reproduce with Chinese locale:
<img width="169" alt="screen shot 2017-06-20 at 16 19 29" src="https://user-images.githubusercontent.com/639601/27321241-633b7f56-55d4-11e7-8100-8c83fbb58c18.png">

I think this is an upstream Chrome bug, but Chrome does not seem to use any combination of F keys as shortcuts.

**Comment by codebytere** [comment] 2018-05-09 04:00
Does this occur on `2.0.0`?

**Comment by codebytere** [comment] 2018-09-24 04:45
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 04:45 UTC
Labels: blocked/upstream, bug :beetle:, component/menu, platform/windows, version/1.6.x
