### ISSUE TITLE
"unresponsive" event is incorrectly fired when calling synchronous version of `dialog` methods

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#6146] opened 2016-06-20 09:10 UTC
- Electron version: 1.2.1
- Operating system: OS X 10.9.5
  1. Subscribe to the BrowserWindow "unresponsive" event (and add a debugger)
  2. Call the synchronous version of `dialog. showOpenDialog()` method
  3. Wait enough time and the debugger in the unresponsive event will be called

I understand why this happens. However, can something be done for this case? I hope you guys could fix it or maybe just provide an API for `dialog.hasOpenDialog` so this behavior could be fixed in our code.

**Comment by zcbenz** [comment] 2016-06-21 00:09
How did you call the API? I think we have solved this before, we probably missed some cases.

**Comment by astoilkov** [comment] 2016-06-21 12:29
Pasted the code we use below. Note that I have to wait 2-3 minutes before the unresponsive event is called.

```js
caret.showOpenDialog({
  title: 'Open File',
  properties: ['openFile']
});
```

**Comment by zcbenz** [comment] 2016-06-21 23:54
Are you running the code in the main process? If so this would be quite surprising to me, the code is blocking the whole main process and there is no chance for `unresponsive` event to emit. A minimal app that can reproduce it would be very helpful here.

**Comment by astoilkov** [comment] 2016-06-22 05:32
I call the `dialog.showOpenDialog()` method in the renderer process. Is this the problem?

**Comment by zcbenz** [comment] 2016-06-22 11:24
Hmm I'm unable to reproduce by calling it in renderer process.

**Comment by astoilkov** [comment] 2016-06-22 11:27
Ok. I will create a simple app that reproduces the issue.

**Comment by astoilkov** [comment] 2016-06-24 07:48
Sorry for the delay but I will have to do it next week.

**Comment by astoilkov** [comment] 2016-06-30 10:51
Hi,

I have created a simple app that replicates the issue. Steps to reproduce:

  1. Open the app
  2. Hit "s" character on the keyboard
  3. The dialog will appear
  4. Wait for 2-3 minutes
  5. The unresponsive event is called and and a message box will appear

[electron-dialog-unresponsive.zip](https://github.com/electron/electron/files/338789/electron-dialog-unresponsive.zip)

**Comment by zcbenz** [comment] 2016-07-01 12:00
Hmm I can not reproduce with your app, it is probably because I'm using OS X 10.11.

**Comment by zcbenz** [comment] 2016-07-01 12:03
Currently we only suppress unresponsive event when a dialog is attached to a window, which might be why it is happening for some systems. We should probably just suppress it for all windows as long as there is dialog showing.

**Comment by astoilkov** [comment] 2016-07-01 12:24
I agree.

P.S. I have also tested the sample under OS X 10.11.5 and successfully replicated the problem. After I open the dialog I wait and don't do anything else (maybe this is also related).

**Comment by zcbenz** [comment] 2017-06-14 11:44
Reopening since it reappears in v1.6.x.

**Comment by codebytere** [comment] 2018-04-13 20:44
Left this up for 10 minutes on the latest `master` and could not reproduce, so i'm going to close this out! feel free to @ me for a reopen if it crops up again 😁

**Closed by codebytere** 2018-04-13 20:44 UTC
Labels: bug :beetle:, fixme/regression, good-beginner-issue :1st_place_medal:, version/1.6.x
