### ISSUE TITLE
[Bug]: Preload modules don't load in Electron 20.x

### ISSUE THREAD

**Issue by Awendel** [electron/electron#35713] opened 2022-09-17 10:27 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.x

### What operating system are you using?

Windows

### Operating System Version

Win 10, latest

### What arch are you using?

x64

### Last Known Working Electron version

19.x

### Expected Behavior

Simple Setup:

Load a preload script that imports another script (using require syntax)
--> this works fine in Electron 19 and below

### Actual Behavior

For electron 20x, it throws the following error:

```
Preload failed for preloadFile.js

Module not found "./pathToRequiredModule.js"
```

installing the old version (19) of Electron solves the issue

**Comment by Prinzhorn** [comment] 2022-09-17 11:40
Please read the breaking changes section

https://github.com/electron/electron/releases/tag/v20.0.0

https://github.com/electron/electron/issues/35587
https://github.com/electron/electron/issues/35584
https://github.com/electron/electron/issues/35387
https://github.com/electron/electron/issues/35589

**Comment by ckerr** [comment] 2022-09-17 14:29
Closing as duplicate of #35387

**Closed by ckerr** 2022-09-17 14:29 UTC
Labels: bug :beetle:
