### ISSUE TITLE
[Bug]: Electron 22.0.0 pageSize not work when silent print on windows 10

### ISSUE THREAD

**Issue by moom-en** [electron/electron#36620] opened 2022-12-09 08:43 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

pageSize works when silent print

### Actual Behavior

`webContents.print({silent:true, pageSize: "A4"});`
pageSize not works when silent print. it always use printer default pageSize.

**Comment by lacthon** [comment] 2022-12-09 14:17
If i want to work on this issue it is important to having windows 10 in our own system.
Assign it to me i will do my best

**Comment by pushkin-** [comment] 2022-12-09 20:43
this should be closed as a dupe of [this](https://github.com/electron/electron/issues/31705)

**Comment by mlaurencin** [comment] 2023-02-07 20:56
As mentioned above, this is a dupe of another issue. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by mlaurencin** 2023-02-07 20:56 UTC
Labels: bug :beetle:
