### ISSUE TITLE
[Bug]: Can't import esm package into main process

### ISSUE THREAD

**Issue by mazury** [electron/electron#30352] opened 2021-07-30 16:11 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20

### What arch are you using?

x64

### Expected Behavior

Electron imports package, no error messages

### Actual Behavior

There is and error message when I'm trying to import es6 module to electron main process (specifically ib-tws-api), which breaks the app:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/amz/projects/test/electron-boilerplate/node_modules/ib-tws-api/index.js
require() of ES modules is not supported.
require() of /home/amz/projects/test/electron-boilerplate/node_modules/ib-tws-api/index.js from /home/amz/projects/test/electron-boilerplate/app/main.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/amz/projects/test/electron-boilerplate/node_modules/ib-tws-api/package.json.
```
I'm using electron-boilerplate here, but I don't whink it matters.
Not sure if it's really a bug, but I couldn't figure it out. There has to be the way to import this package. I searched everywhere and couldn't find any solutions. I'm sure I could just convert the package to use commonjs, but I think there are simpler ways.

**Comment by murtazaali1999** [comment] 2021-08-01 13:08
Hi @mazury, Ive also opened this issue 2 months ago, They still haven't resolved it yet and didnt reply. This is the link to my issue.
https://github.com/electron/electron/issues/29657

**Comment by malept** [comment] 2021-08-01 17:21
Duplicate of #21457

**Closed by malept** 2021-08-01 17:21 UTC
Labels: bug :beetle:
