### ISSUE TITLE
Child BrowserWindow modal on macOS has no close, minimize, maximize buttons

### ISSUE THREAD

**Issue by ShlomiRex** [electron/electron#27160] opened 2021-01-01 17:27 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  v9.4.0
* **Operating System:**
  *  macOS Big Sur
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Child BrowserWindow should have close, minimize, maximize buttons like this:
![image](https://user-images.githubusercontent.com/17744127/103443332-e35f9780-4c66-11eb-891f-d340ab140605.png)

On Windows and Linux it's ok

### Actual Behavior
Doesn't have those buttons

![image](https://user-images.githubusercontent.com/17744127/103443342-04c08380-4c67-11eb-9507-d9e4737cbd4a.png)

### To Reproduce
Create new BrowserWindow with modal: true 
Example:
```
	let child = new BrowserWindow({
		parent: mainWindow, 
		modal: true, 
		show: false,
		title: "New Session",
		webPreferences: {
			contextIsolation: true,
			preload: path.join(__dirname, './preload/NewSession.js')
		}
	})
```

**Comment by codebytere** [comment] 2021-01-05 22:18
@ShlomiRex we're going to need more information in order to triage this properly. You've for example created a new child window which *isn't shown* - what actions are you taking? Please provide a _complete_ piece of code demonstrating the behavior you perceive to be broken.

**Comment by ShlomiRex** [comment] 2021-01-07 11:07
> @ShlomiRex we're going to need more information in order to triage this properly. You've for example created a new child window which _isn't shown_ - what actions are you taking? Please provide a _complete_ piece of code demonstrating the behavior you perceive to be broken.

"new child window which isn't shown"
I gave screenshots showing the child window is frameless, and without buttons like in the screen shot above

**Comment by cjiang-ibm** [comment] 2021-02-22 14:34
I can replicate the identical problem reported here on my Mac with Big Sur.

**Comment by toioski** [comment] 2021-04-20 14:34
I have the exact same problem on Big Sur

**Comment by nornagon** [comment] 2021-04-20 22:03
Closing due to no repro.

**Closed by nornagon** 2021-04-20 22:03 UTC
Labels: 9-x-y, Big Sur 🍎, blocked/need-info ❌, bug :beetle:, platform/macOS

**Comment by toioski** [comment] 2021-04-22 07:02
@nornagon why did you close the issue? The problem's still there. Do you think a better explanation is needed?

**Comment by aljosa** [comment] 2021-04-22 09:08
I have the same issue, modal window has no options to close it on Big Sur

**Comment by nornagon** [comment] 2021-04-23 22:05
If someone wants to get this looked at, the best way to do that is to create a standalone testcase with only the code necessary to reproduce the issue. For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by poisonReact** [comment] 2021-07-22 08:55
the bug still exist. Open new issue with reproduce code https://github.com/electron/electron/issues/30232

**Comment by lwinmaungmaung** [comment] 2022-01-04 05:07
<img width="825" alt="Screen Shot 2022-01-04 at 11 37 01" src="https://user-images.githubusercontent.com/12186725/148012073-b8cd09c8-7e5b-4e00-9e28-f064d35b77a7.png">
Still on Montery!

**Comment by omarduarte** [comment] 2022-04-06 09:27
I have the same issue :(

**Comment by ym13349140** [comment] 2022-05-17 09:05
I have the same issue with electron@11.3.0 on MacOS 10.14.6.

**Comment by jamesonsaunders** [comment] 2022-08-08 16:46
Same issue

**Comment by Kenhuey** [comment] 2022-09-08 17:16
same problem, when child window use those options
```
modal: true,
parent: xxx
```

**Comment by charise-arter-sony** [comment] 2022-11-24 01:38
I had this issue today. I just changed modal into false and made sure closeable was true.  I had to do this for the app to work properly on macOS.

**Comment by mqliutie** [comment] 2024-10-18 01:43
I have the same issue with electron@32.0.1 on MacOS 14.5.
