### ISSUE TITLE
Undo/Redo/Cut/Copy/Paste & more Not work using Menubar in Windows

### ISSUE THREAD

**Issue by damianaiamad** [electron/electron#18745] opened 2019-06-12 15:09 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.3
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * 4.2.4

### Expected Behavior
Selecting Undo/Redo/Cut/Copy/Paste/ZoomIn/ZoomOut/ResetZoom from menu bar with mouse performs those various functions.

### Actual Behavior
Selecting these options from the menubar using the mouse seems to have no effect.
Using keyboard shortcuts does work ok.

Both mouse & keyboard works ok for all functions in MacOS 10.14.5.

### To Reproduce

https://github.com/electron/fiddle/releases/tag/v0.8.1
Download and run, then try Edit and View menus.
This uses 5.0.1

I have same problem in my own app using 5.0.3. Problem eliminated by downgrading to 4.2.4.

### Additional Information

My app uses standard MenuItem roles:
```
        { role: 'resetzoom' },
        { role: 'zoomin' },
        { role: 'zoomout' },

```

Electron Fiddle does the same:
https://github.com/electron/fiddle/blob/88ce4a76e97c4c93821306b59b3de9a147378058/src/main/menu.ts
```
     item.submenu.push({ type: 'separator' }, { role: 'resetzoom' }, { role: 'zoomin' }, { role: 'zoomout' }); // Add zooming actions
```

**Comment by codebytere** [comment] 2019-06-13 04:08
cc @felixrieseberg, perhaps this is a fiddle issue?

**Comment by damianaiamad** [comment] 2019-06-13 04:51
My app has the same problems, so I don't think it's just a fiddle problem.

Also, these "role" based menu behaviours are provided by Electron, not by application code.

**Comment by damianaiamad** [comment] 2019-06-17 02:42
I did some more investigation and can reproduce all problems with **Electron API Demo**.
https://github.com/electron/electron-api-demos

Current version uses Electron@4, so upgrade to Electron@5 as follows:

**To Reproduce**

$ git clone https://github.com/electron/electron-api-demos
$ cd electron-api-demos

Edit package.json to update electron version
    "electron": "^5",
 
$ npm install
$ npm start

In the app go to System > Copy & paste from the clipboard

Use the provided text field to test: Undo/Redo/Cut/Copy/Paste/SelectAll

**Observations**

In Electron@5, when click on menubar, keyboard focus disappears from text field, doesn't work.
In Electron@4, when click on menubar keyboard focus remains in text field, works!

But this doesn't explain failure of ZoomIn/ZoomOut/ResetZoom, as follows.

** To Reproduce **

API Demo doesn't include zoom function so add.
Edit main-process/menus/application-menu.js

Add to any menu:
  { role: 'resetzoom' },
  { role: 'zoomin' },
  { role: 'zoomout' },

**Observations**

In Electron@5, Zoom functions don't work from menubar with mouse, but work fine using keyboard shortcuts.
In Electron@4, all works ok mouse and keyboard.

**Comment by vladimiry** [comment] 2019-06-18 09:00
Is not this the same as #15219?

**Comment by nicodorn** [comment] 2019-07-12 19:57
It seems to be the same as #18518 and it's not confined to Windows. I experienced the same issue running Linux. As far as I can see, there is a change in the behaviour of the menu that seems to steel the focus from the WebView. In consequence the actions have no effect.

See my [comment](https://github.com/electron/electron/issues/18518#issuecomment-510424093) for a workaround (which only applies under certain circumstances). Clearly a regression to 4.x.

**Comment by javan** [comment] 2019-08-01 14:18
I can confirm that the following roles do not work on Windows with Electron v5.0.8 and v6.0.0:
* `undo`
* `redo`
* `cut`
* `copy`
* `paste`
* `pasteAndMatchStyle`
* `selectAll`
* `delete`
* `resetZoom`
* `zoomIn`
* `zoomOut`

Here's a fiddle gist: https://gist.github.com/javan/69c1075d389acd5a3437c6459e4c6a6d

The underlying issue may be the window losing focus (as noted in https://github.com/electron/electron/issues/18518), which appears to happen when you interact with the menu.

<details><summary>Note how the window blurs when clicking the menu 👎</summary>

![windows-menu](https://user-images.githubusercontent.com/5355/62300090-30bd5100-b444-11e9-96e8-65407fa68379.gif)

</details>

<details><summary>This doesn't happen with earlier (<= v4.2.8) Electron versions, the window remains focused 👍</summary>

![windows-menu-v4](https://user-images.githubusercontent.com/5355/62300608-1c2d8880-b445-11e9-9dd9-f5ee9b65071c.gif)

</details>

<details><summary>It also doesn't happen on macOS with any Electron version, the window remains focused 👍</summary>

![macos-menu](https://user-images.githubusercontent.com/5355/62300224-695d2a80-b444-11e9-930b-3b6b31e83fef.gif)

</details>

**Comment by javan** [comment] 2019-08-01 20:28
> perhaps this is a fiddle issue?

To clarify, I only used a fiddle URL above because it's the easiest way to share an app that reproduces the issue. The issue itself is not related to fiddle.

**Comment by erickzhao** [comment] 2019-08-02 18:29
Can confirm that this is occurring for me on Ubuntu 19.04 as well. Investigating. :male_detective:

**Comment by bpasero** [comment] 2019-08-07 06:48
Just to confirm: When I open any menu on Linux (with Electron 6) and hit ESC to close it, focus does not return to the input field. So this is a general issue for menus, not just Undo/Redo etc.

**Comment by javan** [comment] 2019-08-20 15:19
This is still an issue on Windows with Electron [v6.0.3](https://github.com/electron/electron/releases/tag/v6.0.3) which includes #19657 (the fix). Reproducible with the same fiddle I shared [above](https://github.com/electron/electron/issues/18745#issuecomment-517307966).

<details><summary>👀</summary>

![windows-menu-roles](https://user-images.githubusercontent.com/5355/63360362-4a173600-c33c-11e9-8162-06da4d03e0d1.gif)

</details>

**Comment by javan** [comment] 2019-08-20 18:45
@sofianguy, ⇡ ⇡ ⇡ this wasn't actually  **_Fixed in 5.0.10_**  or 6.03 and should be reopened (see my last comment above)

**Comment by erickzhao** [comment] 2019-08-28 23:26
According to @nornagon, seems like this bug was reintroduced as a side effect for another fix: https://github.com/electron/electron/pull/19710#issuecomment-525945274 

cc @javan

**Comment by codebytere** [comment] 2019-09-04 17:44
This should now be resolved by https://github.com/electron/electron/pull/20019.

**Closed by codebytere** 2019-09-04 17:44 UTC
Labels: 5-0-x, 6-0-x, 7-0-x, bug :beetle:, platform/linux, platform/windows

**Comment by leonardocfor** [comment] 2020-07-31 22:15
It is not working. undo, redo, copy, paste roles do not work using Electron ^5.0.10 on Ubuntu 18.04

**Comment by johnosbb** [comment] 2020-12-23 14:32
Still not working on Ubuntu 16.04 LTS and Electron 12.0.0
