### ISSUE TITLE
 in multi-column mode, caret not displayed if element flows to second column

### ISSUE THREAD

**Issue by xthdraft** [electron/electron#17587] opened 2019-03-28 01:58 UTC
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 3.0.6**
  * 

* **Operating System: windows 10 x64**
  * 
* **Last Known Working Electron version:**: v 1.8.4
  * 

### Expected Behavior

I have also filed this as a bug in chrome under: " chrome css3 multi-column cursor bug"

### Actual Behavior

In chrome recent versions, and in electron recent versions (observed in v3.0.6), in the case of text inside a contenteditable div, using css3 multi-columnn mode, I am finding the following behaviour:

If a <p> element starts in one column and continues to the following column, the cursor will only be visible in the part of the <p> displayed in the second column. The cursor in the part of the <p> in the first column is invisible.

Any <p> element wholly contained in the first column is OK.

Demo: https://jsfiddle.net/oqr346hk/

Note:   electron v1.8.4 displays the caret correctly in all columns as expected.
I suspect this is a chromium bug which occurred sometime after electron v1.8.4

**Comment by MarshallOfSound** [comment] 2019-03-28 20:57
> I have also filed this as a bug in chrome under: " chrome css3 multi-column cursor bug"

If the issue is in Chromium we'll inherit the fix when it is fix upstreamed.  Closing this out, it should be tracked upstream

**Closed by MarshallOfSound** 2019-03-28 20:57 UTC
