### ISSUE TITLE
Problem when spawning process from node with IPC enabled with electron >v2

### ISSUE THREAD

**Issue by redders6600** [electron/electron#17044] opened 2019-02-19 10:21 UTC
* **Electron Version** (output of `node_modules/.bin/electron --version`): 3.x , 4.x
* **Operating System** (Platform and Version): Ubuntu 16.04 x64, Ubuntu 18.04 x64
* **Last known working Electron version** (if applicable): 2.x (latest works)

### Expected Behavior

Spawning packaged electron apps from node like so:
```javascript
let child = childProc.spawn('./path/to/electron-executable', [], {
  stdio: [0, 1, 2, 'ipc'] // note presence of last 'ipc' flag
});
```
Should work as normal, but enable `process.send()`ing data to the app that spawns it from within the node process.

### Actual behavior

With electron major versions higher than 2, the browser windows that are spawned don't load properly if the IPC flag is set. If the IPC flag is not set, everything works as normal.

### To Reproduce

1. Clone [my issue reproduction repo](https://github.com/redders6600/electron-quick-start/tree/packaged-ipc-test)
2. `git checkout packaged-ipc-test`
3. `npm i`
4. `npm run package`
5. `npm run launch-from-node`

You'll see that the app is launched, but the Browser Window it launches never loads. If you downgrade electrion to 2.x it'll all work properly. If you remove the `'ipc'` flag from `launch-from-node.js:5` then the browserwindows load properly but there's no IPC with the parent process.

**Remember to re-package with any change to the electron app - this has caught me out a few times now!**

### Screenshots

Launching packaged electron app from node with `'ipc'` flag:
![blank app window](https://user-images.githubusercontent.com/2893500/53007818-ea44de80-342f-11e9-8904-042992a327a0.png)

### Additional Information

Appreciate this is possibly an unusual use-case, but the IPC is critical for my application (we need to be able to detect if it crashes and re-launch).

**Comment by redders6600** [comment] 2019-02-25 11:15
Has anyone been able to reproduce this issue?

**Comment by rlidwka** [comment] 2019-03-11 09:50
Yes, I was able to reproduce this as well (ubuntu 18, node.js 8.10).

As a side note, same exact issue happens when using navit, [here](https://github.com/nodeca/navit/blob/master/lib/electron/driver/index.js#L111-L115) is how electron is launched in that package, which works with electron@2 but fails with electron@4 (shows blank white screen, nothing ever loads).

**Comment by xudafeng** [comment] 2019-03-27 15:37
the same issue 3.x , 4.x 

https://github.com/macacajs/macaca-electron

**Comment by xudafeng** [comment] 2019-03-27 15:49
@redders6600 Have you found a solution?

**Comment by redders6600** [comment] 2019-04-01 08:46
@xudafeng - nope - we just haven't upgraded to 3.x yet. Haven't seen any movement on this issue at all so we might end up changing the way our launcher works.

**Comment by xudafeng** [comment] 2019-04-01 08:49
@redders6600 Thanks for your reply

**Comment by xudafeng** [comment] 2019-04-01 08:54
Dear core maintainers, do you have an exact plan to fix this ipc-related problem? This problem seriously affects our operation in CI environments such as Linux.

@rlidwka @ckerr @zcbenz @MarshallOfSound

**Comment by dead-horse** [comment] 2019-05-24 06:32
can anybody take a look at this issue? 

cc @zcbenz @groundwater

**Comment by VladimirMerk** [comment] 2019-06-06 05:13
It looks like this is fixed in version 5. I checked the example on several computers (win7 x64, win8 x86, win10 x64) with an electron 5.0.2 and it worked correctly.
I haven't tried it on Linux, but it probably will be fine there.

**Comment by xudafeng** [comment] 2019-06-09 11:05
@VladimirMerk 
Still not working, my environment is centos7

```
Linux 6af1da182676 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by xudafeng** [comment] 2019-06-11 07:48
this issue can be changed to  **Confirmed**?
cc @zcbenz @groundwater

**Comment by redders6600** [comment] 2019-07-11 11:42
I finally got around to testing this - it works for me on ubuntu 18.04 using electron version 5. 

I won't close this as assume @xudafeng can't get this to work on centos still.

**Comment by xudafeng** [comment] 2020-01-16 06:12
I think, upgrade directly to 7, and give up solving this problem

@paradite

**Comment by electron-triage** [comment] 2020-02-19 21:06
We are no longer supporting versions older than 6.x.y, per our [supported versions policy](https://www.electronjs.org/docs/tutorial/support#supported-versions). Please upgrade to a later version of Electron and reach out if you are still experiencing this issue and we will reopen.

**Closed by electron-triage** 2020-02-19 21:06 UTC
Labels: 3-0-x, 4-2-x, bug :beetle:, platform/linux, status/confirmed
