### ISSUE TITLE
[Bug]: Mouse wheel freeze on Electron windows apps

### ISSUE THREAD

**Issue by wakawakka** [electron/electron#36727] opened 2022-12-22 06:48 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

Any

### What operating system are you using?

Windows

### Operating System Version

Microsoft Windows 10 Pro OS Version: 10.0.19043 N/A Build 19043 x64

### What arch are you using?

x64

### Expected Behavior

Normal scrolling

### Actual Behavior

There is mouse wheel icon near the mouse pointer (looks like horizontal scrolling mode is enabled) appears when window is in focus. Scrolling is possible only holding ctrl or secondary mouse button).

### Additional Information

All electron windows apps (like teams, edge, vscode, etc...) are affected.
No-focused windows are not affected (using windows feature scroll inactive hovered window).

Interesting facts:
Connecting second display - bug reproduce on both.
Connecting third display - bug affects primary and third display. Moving window to display 2 fix the problem (while just 1 pixel of application is on display 2)

**Comment by mlaurencin** [comment] 2023-02-13 19:42
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2023-04-03 13:11
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2023-04-03 13:11 UTC
Labels: platform/windows, blocked/need-info ❌, bug :beetle:
