### ISSUE TITLE
How to make electron support mac os share extension

### ISSUE THREAD

**Issue by zhenwei12138** [electron/electron#17702] opened 2019-04-05 08:17 UTC
I have a question
I want my application support mac os native share extension .
how to do it

**Comment by codebytere** [comment] 2019-04-08 16:23
Duplicate of https://github.com/electron/electron/issues/6330

**Closed by codebytere** 2019-04-08 16:23 UTC

**Comment by pszypowicz** [comment] 2021-11-15 10:17
I would like to reopen this feature request. 

This issue is about sharing content from other apps with a electron app. 

The "marked as duplicate" issue was about sharing content from the electron app to other apps. 

Two messaging applications: Element and Signal were discussing this and came to the same conclusion:
https://github.com/vector-im/element-web/issues/19673
https://github.com/signalapp/Signal-Desktop/issues/1905

There is a developer guide to implement it on MacOS:
https://developer.apple.com/design/human-interface-guidelines/macos/extensions/share-extensions/

**Comment by foss-** [comment] 2024-12-15 12:37
Polite ping about last comment which has not received a reply in over 3 years. Can someone from electron please re-visit this? @codebytere
