### ISSUE TITLE
Cannot load content on Windows when sandbox is enabled

### ISSUE THREAD

**Issue by dataich** [electron/electron#18857] opened 2019-06-18 06:28 UTC
If sandbox option is enabled on BrowserWindow, the content isn't loaded on the window. It happens on only Windows. It works on macOS mojave correctly. Any help?

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.4
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
Content should be loaded

### Actual Behavior
No content loaded

### To Reproduce
- clone sample app https://github.com/dataich/electron-sandbox-sample
- Run electron app
```
$ cd electron-sandbox-sample
$ yarn
$ npm start
```

### Additional Information
```
Y:\github.com\dataich\electron-sandbox-sample (master) (electron-sandbox-sample@1.0.0)
$ npm start

> electron-sandbox-sample@1.0.0 start Y:\github.com\dataich\electron-sandbox-sample
> electron-forge start

√ Checking your system
√ Locating Application
√ Preparing native dependencies
√ Launching Application

 { Error: ERR_FAILED (-2) loading 'file://Y:\github.com\dataich\electron-sandbox-sample\src/index.html'
    at rejectAndCleanup (Y:\github.com\dataich\electron-sandbox-sample\node_modules\electron\dist\resources\electron.asar\browser\navigation-controller.js:72:21)
    at WebContents.stopLoadingListener (Y:\github.com\dataich\electron-sandbox-sample\node_modules\electron\dist\resources\electron.asar\browser\navigation-controller.js:113:9)
    at WebContents.emit (events.js:194:13)
  errno: -2,
  code: 'ERR_FAILED',
  url:
   'file://Y:\\github.com\\dataich\\electron-sandbox-sample\\src/index.html' }
```

**Comment by vladimiry** [comment] 2019-06-18 08:54
`WebContents.emit` should not be called until the page is loaded.

So try moving `openDevTools` to `then` handler:

```
mainWindow
  .loadURL(`file://${__dirname}/index.html`)
  .then(() => {
    mainWindow.webContents.openDevTools();
  })
  .catch(console.log);
```

**Comment by dataich** [comment] 2019-06-19 00:01
> So try moving openDevTools to then handler:

Thanks! It's not related with this issue, but I removed the code.

**Comment by vladimiry** [comment] 2019-06-19 03:54
The issue is not reproducible for me on Win 10 (don't know the exact version).

The page address in your example has slashes mixed with backslashes I guess that could cause an error in your case.

So I'd suggest trying something like this:
```
const pageFile = require("path").join(__dirname, "index.html");

mainWindow
  .loadFile(pageFile)
  .catch(console.log);
```

Or this:
```
const pageFile = require("path").join(__dirname, "index.html");
const pageUrl = require("url").format({ pathname: pageFile, protocol: "file:", slashes: true });

mainWindow
  .loadURL(pageUrl)
  .catch(console.log);
```

**Comment by dataich** [comment] 2019-06-19 04:31
Thanks! It could not be fixed, I've tried that though. If I disable `sandbox` option, it works.

**Comment by dataich** [comment] 2019-06-25 01:37
My coworker could reproduce this problem too.

**Comment by dataich** [comment] 2019-07-04 23:20
any updates?

**Comment by patrickmichalina** [comment] 2019-12-07 06:39
I am seeing this too, OSX works just fine - windows is the issue.

**Comment by nornagon** [comment] 2020-01-23 22:05
If anyone who's experiencing this issue could collect a netlog (`--log-net-log=net.log`) and upload the log here that might be helpful!

**Comment by electron-triage** [comment] 2020-02-19 19:04
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by shlomisas** [comment] 2020-02-25 13:12
Hi, @dataich, did you solved it?

**Comment by electron-triage** [comment] 2020-02-26 21:03
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 21:03 UTC
Labels: 5-0-x, blocked/need-info ❌, bug :beetle:, platform/windows

**Comment by samermurad** [comment] 2020-09-04 09:38
I know this is a closed issue, and the OP has a slightly different situation than I did, nevertheless here are my two cents on a similar issue I had.

My case has nothing to do with the sandbox, but still, in some cases, I got the same error when trying to load windows from a webpack-dev-server url (for example `http://localhost:3040/#/settings/(true|false)`).

In my case, the problem was related to the React Routers' `HashRouter` which for some reason refuses to jump between relative routes if it gets an absolute value, so trying to route to `http://localhost:3040/#/settings/true` to  `http://localhost:3040/#/settings/false` fails with the above described error 

 
    {      
           Error: ERR_FAILED (-2) loading 'http://localhost:3040/#/settings/false' ......
           errno: -2,
           code: 'ERR_FAILED',
           url: 'http://localhost:3040/#/settings/false'
    }


For anyone that lands here, my solution was to switch the Router from the `HashRouter` to the `BrowserRouter`,
this solved the error completely, hopefully I'll save someone some time.

**Comment by almas** [comment] 2021-04-05 07:57
Error occurring "electron": "11.3.0", on Windows 7 32bit. But it's not persistent. 
Only some clients have issue. But it's not persistent. Just sometimes open app is fail and got this error.

Error: ERR_FAILED (-2) loading 'app://./'

Any help?

**Comment by GillZhou** [comment] 2021-06-06 15:17
I have the same problem in version 12.0.0;Any help?
`(node:13584) UnhandledPromiseRejectionWarning: Error: ERR_FAILED (-2) loading 'file:///D:\myProject\base-tools\src\lib\screenCapture\fixedImage.html'
    at rejectAndCleanup (electron/js2c/browser_init.js:217:1457)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:217:1832)
    at Object.emit (events.js:315:20)
` 

> Thank you for your issue!
> 
> We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by linonetwo** [comment] 2021-07-09 15:27
omg this should be reopened


```
ERR_FAILED (-2) loading 'http://localhost:3000/main_window' Error: ERR_FAILED (-2) loading 'http://localhost:3000/main_window'\n    at rejectAndCleanup (electron/js2c/browser_init.js:161:7364)\n    at Object.stopLoadingListener (electron/js2c/browser_init.js:161:7739)\n    at Object.emit (events.js:376:20)","level":"error"}
```

**Comment by danielspaceuy** [comment] 2021-07-21 19:24
Hi, I'm having this issue too.

- Happens on Windows only
- The app works for some clients but fails for others.

Electron `v12.0.2`

I'm no able to reproduce the error but I can see the logs:

```
Error: ERR_FAILED (-2) loading 'file:///C:\Users\tom\AppData\Local\Programs\not-real-app-name\resources\app.asar\renderer\index.html'
    at rejectAndCleanup (electron/js2c/browser_init.js:217:1457)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:217:1832)
    at Object.emit (events.js:315:20)
    at Object.emit (domain.js:467:12)
    at Object.emit (evalmachine.<anonymous>:1:195165)
```

**Comment by alexfr26** [comment] 2021-10-15 00:46
Hi. Faced the same issue. The only difference is we use Electron without sandboxing, but some users occasionally get an ERR_FAILED (-2) error when our application tries to load external data from a URL with https protocol via loadURL(). The problem only occurs on machines with 32bit Windows system (mostly Windows 7, but there are also some users with the same issue and architecture in Windows 10). No such errors were noticed on any OS based on Linux and macOS. The error can occur once in 100 cases, so it is difficult to reproduce. 

Node version: 12.18.3
Electron version: 11.3.0 (we can’t upgare to newer versions, because the features important for us don't work correctly there)

**Comment by DanielMcAssey** [comment] 2021-11-12 11:53
Having this same issue as well, this should be re-opened

**Comment by ktaicoder** [comment] 2021-12-02 02:46
Having this same issue as well.

**Comment by sertraline** [comment] 2021-12-02 10:16
```
Uncaught (in promise) Error: ERR_FAILED (-2) loading 'https://docs.google.com/gview?url=https://calibre-ebook.com/downloads/demos/demo.docx'
    at rejectAndCleanup (:8080/electron/js2c/browser_init.js:217)
    at Object.stopLoadingListener (:8080/electron/js2c/browser_init.js:217)
    at Object.emit (events.js:327)
```  

This happens on our Linux (5.10 - 5.15) machines randomly. Most of the time it loads successfully, but once in a while it fails.

package.json:
```
        "electron": "^12.0.1",
        "electron-devtools-installer": "^3.1.0",
        "electron-updater": "^4.3.8",
```  

background.js:
```
    win = new BrowserWindow({
        width: 800,
        height: 600,
        minWidth: 800,
        minHeight: 600,
        webPreferences: {
            nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION,
            devTools: isDevelopment,
            enableRemoteModule: true,
            contextIsolation: false,
            webSecurity: false
        },
        frame: false,
        backgroundColor: '#FFF'
    });
    win.webContents.setWindowOpenHandler(() => {
        return {
            action: 'allow',
            overrideBrowserWindowOptions: {
                webPreferences: {
                    nativeWindowOpen: true
                }
            }
        };
    });
```  

The code:
```
  const { BrowserWindow } = require('electron').remote;

  const win = new BrowserWindow({ width: 800, height: 600 });
  win.loadURL(
      'https://docs.google.com/gview?url=https://calibre-ebook.com/downloads/demos/demo.docx'
  );
  win.webContents.openDevTools();
```

**Comment by sertraline** [comment] 2021-12-02 12:03
Update to the above: loading 'https://google.com' is instant and seems to never fail, same for github and main google docs page. So I'd assume it has something to do with load timeouts, or the fact there is a URL passed as a URL parameter.

**Comment by almas** [comment] 2021-12-06 03:41
Here is my solution. It might work. Not yet fully tested.

`    let url
      if (isProd) {
        url = 'app://./'
      } else {
        const port = process.argv[2]
        url = `http://localhost:${port}`
      }

      const loadUrl = () => {
        let resWindow = mainWindow.loadURL(url).catch(error => {
          return { error }
        })

        if (resWindow !== undefined && resWindow.error) {
          log.error(resWindow.error)
          setTimeout(() => {
            loadUrl()
          }, 5000)
          return
        }
      }

      setTimeout(() => {
        loadUrl()
      }, 5000)
`

**Comment by almas** [comment] 2021-12-06 03:50
It is still in there version 11. Problem occur when computer is too slow.

Here is my solution. It might work. Not yet fully tested.

```JavaScript
let url
if (isProd) {
  url = 'app://./'
} else {
  const port = process.argv[2]
  url = 'http://localhost:' + port
}

const loadUrl = () => {
  const resWindow = mainWindow.loadURL(url).catch(error => {
    return { error }
  })
  if (resWindow !== undefined && resWindow.error) {
    log.error(resWindow.error)
    setTimeout(() => {
      loadUrl()
    }, 5000)
  }
}

setTimeout(() => {
  loadUrl()
}, 5000)
```

**Comment by eric-burel** [comment] 2022-01-11 15:39
Weird issue, I am updating to Electron 7, I need to reverse `newWindow.show()` and `newWindow.loadUrl()` to avoid this issue. I am on Ubuntu, the URL is valid.

**Comment by chetbox** [comment] 2022-03-17 15:33
We are seeing a very similar issue on Ubuntu 20.04 x64 with Electron 12.0.9 loading `http://localhost:3000` which is running Webpack 4.44.1. I can reliably reproduce the problem but if I try to run the requests through a proxy the problem goes away. Debugging from Webpack shows that the request never comes in.

**Comment by bbrand84** [comment] 2022-05-31 12:07
This is killing me. 
I open a window and receive
Error: ERR_FAILED (-2) loading 'http://localhost:1800/something?key=val'
I made my code retry it, it then works and opens the URl in a window.

After that , net.request(...) also seems to be broken:

net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)

The URL that causes this error for me is valid when I paste it in a Browser directly.

Electron 11.1.1

**Comment by alexfr26** [comment] 2022-06-01 09:07
@bbrand84 Are you running the Electron app on Windows OS?

**Comment by ArtemAvramenko** [comment] 2024-08-06 14:28
In my application, I create a window at the very beginning, and to have it already loaded, I preload it with `'about:blank'`:
```ts
void (async () => {
    const window = new BrowserWindow({
        show: false,
        paintWhenInitiallyHidden: false,
        webPreferences: {
            nodeIntegration: false,
            devTools: false,
            javascript: false,
            spellcheck: false,
            webgl: false
        }
    });
    await window.loadURL('about:blank');
    ...
})();
```
And even in this simplest scenario, an error occurs, albeit extremely rare:
```
Error: ERR_FAILED (-2) loading 'about:blank'
at rejectAndCleanup (node:electron/js2c/browser_init:2:85498)
at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:2:85885)
at EventEmitter.emit (node:events:513:28)
```

I'm using **v26.6.0** on Windows

It seems to be related to PC speed, because it reproduces for some users during OS booting, when the application is in startup folder, and when CPU and HDD are busy with simultaneous launching of other applications.

**Comment by jjaeseong** [comment] 2025-03-31 07:50
I turned off the option to run as administrator and it works.
like win32metadata in forge.config.ts
