### ISSUE TITLE
[Bug]: Electron windows resize slowly

### ISSUE THREAD

**Issue by bpasero** [electron/electron#40603] opened 2023-11-23 08:13 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.2

### What operating system are you using?

macOS

### Operating System Version

14.1.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When resizing an Electron window, I would assume the content sizes snappy.

### Actual Behavior

I see lag from the contents of the window adjusting to the new size. I cannot reproduce in Chrome.

### Additional Information

**Electron:**
![Recording 2023-11-23 at 09 10 01](https://github.com/electron/electron/assets/900690/94b9fd58-f5df-4229-8234-085e333e2937)

**Web:**
![Recording 2023-11-23 at 09 11 18](https://github.com/electron/electron/assets/900690/d3ee7a52-dd10-45a8-909a-1199d661e08d)

//cc @deepak1556

**Comment by codebytere** [comment] 2023-11-23 09:08
@bpasero is this a new occurrence? I think this may be a duplicate of https://github.com/electron/electron/issues/36280 otherwise!

**Comment by bpasero** [comment] 2023-11-23 09:14
@codebytere oh yeah, its not a regression. I was not aware of https://github.com/electron/electron/issues/36280

**Comment by codebytere** [comment] 2023-11-23 09:36
ok thanks! in that case, closing as a duplicate of https://github.com/electron/electron/issues/36280

**Closed by codebytere** 2023-11-23 09:36 UTC
Labels: platform/macOS, blocked/need-info ❌, bug :beetle:, component/webcontents, 27-x-y
