### ISSUE TITLE
BrowserWindow removeMenu method not working on v7.1.1

### ISSUE THREAD

**Issue by gschattenhofer** [electron/electron#21088] opened 2019-11-12 08:52 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
BrowserWindow method `removeMenu()` is not working on v7.1.1. The only change made was upgrading Electron version.
https://electronjs.org/docs/api/browser-window#winremovemenu-linux-windows

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * v6.0.3

### Expected Behavior
Menu Bar not visible.

### Actual Behavior
Menu Bar is visible.

### To Reproduce
For me, just update Electron version.

### Screenshots
With version 7.1.1:
![image](https://user-images.githubusercontent.com/11201504/68656003-c5d5e880-050f-11ea-8d22-dfd58d166762.png)

With version 6.0.3:
![image](https://user-images.githubusercontent.com/11201504/68656185-1baa9080-0510-11ea-9033-bec7554f4b40.png)

**Comment by gschattenhofer** [comment] 2019-11-12 09:10
I've also tried this by cloning [electron/electron-quick-start](https://github.com/electron/electron-quick-start) which is using v7.1.1 and added `mainWindow.removeMenu()` on main.js inside `createWindow` function. It didn't removed the menu either.

![image](https://user-images.githubusercontent.com/11201504/68657788-1864d400-0513-11ea-9dcc-457ff960b6e1.png)

**Comment by jacobq** [comment] 2019-11-13 15:57
Is this related to https://github.com/electron/electron/issues/15901?

**Comment by gschattenhofer** [comment] 2019-11-13 16:07
@jacobq  Can't tell, i didnt used v4.0.0 betas.

btw `Menu.setApplicationMenu(null);` did the trick but still, if `removeMenu` isn't deprecated then it should be working by it self.

**Comment by jacobq** [comment] 2019-11-13 16:43
FWIW, I encountered the same behavior in Linux (`5.2.0-3-amd64 #1 SMP Debian 5.2.17-1 (2019-09-26) x86_64 GNU/Linux`)

A quick test suggests that v7.1.1 behaves as follows:

| Method | Affects single window | Affects all/child windows |
|---|:-:|:-:|
| [`{ autoHideMenuBar: true }`](https://electronjs.org/docs/api/browser-window#new-browserwindowoptions)  | Yes<sup>1</sup> |  No  | 
| [`window.removeMenu()`](https://electronjs.org/docs/api/browser-window#winremovemenu-linux-windows) |  No :bug:   |  No | 
| [`window.setMenu(null)`](https://electronjs.org/docs/api/browser-window#winsetmenumenu-linux-windows) | No :bug: | No | 
| [`window.setMenuBarVisibility(false)`](https://electronjs.org/docs/api/browser-window#winsetmenubarvisibilityvisible-windows-linux) | No :bug: | No | 
| [`Menu.setApplicationMenu(null)`](https://electronjs.org/docs/api/browser-window#winsetmenubarvisibilityvisible-windows-linux) | Yes | Yes | 

<sup>1</sup>menu still accessible via keyboard shortcut (by design)

**Comment by Pfuster12** [comment] 2019-11-14 11:58
If this was planned behaviour please deprecate the methods in the docs as well. It's a bit confusing!

**Comment by IceHacks** [comment] 2019-11-15 00:32
Electron changes a lot in short amounts of time. It's like learning to use a whole new tool every update. Don't know whether that is good or bad. Not very backward compatible.

**Comment by PolyviosP** [comment] 2019-12-03 00:20
this it work for me@ electron 7.1.1

const {app, BrowserWindow, Menu} = require(‘electron’)

Menu.setApplicationMenu(false)

**Comment by igortupini** [comment] 2019-12-03 15:53
> this it work for me@ electron 7.1.1
> 
> const {app, BrowserWindow, Menu} = require(‘electron’)
> 
> Menu.setApplicationMenu(false)

This also worked for me @electron 7.1.2
But the win.removeMenu() shouldn't work as well?

**Comment by codebytere** [comment] 2019-12-05 18:36
@zcbenz re-assigning this since it's the original bug corresponding to the one assigned to you in the Releases WG meeting

**Comment by superheri** [comment] 2019-12-05 22:16
Not only removeMenu is not working, setMenu is not working for me too on 7.1.2.

**Comment by yarhamjohn** [comment] 2019-12-06 10:30
I have also found that neither `win.removeMenu()` nor `win.setMenu(null)` work in electron 7.1.3.

Whilst setting `Menu.setApplicationMenu(false)` does remove the menu bar, this isn't a good solution since it also disables the ability to bring up the debugging console when developing the application.

**Comment by igortupini** [comment] 2019-12-06 14:34
> I have also found that neither `win.removeMenu()` nor `win.setMenu(null)` work in electron 7.1.3.
> 
> Whilst setting `Menu.setApplicationMenu(false)` does remove the menu bar, this isn't a good solution since it also disables the ability to bring up the debugging console when developing the application.

@yarhamjohn You can open the developer with `win.webContents.openDevTools()`

**Closed** 2019-12-09 19:17 UTC
Labels: 7-1-x, bug :beetle:, platform/windows
