### ISSUE TITLE
shortcut can't quit fullscreen

### ISSUE THREAD

**Issue by jerryyan1990** [electron/electron#12689] opened 2018-04-23 07:37 UTC
* Electron version: 1.8.4
* Operating system: macOS Sierra 10.12.6

* Last known working Electron version: never used before

### Expected behavior

when i click maximize button the window becomes full screen，when i use shortcut ‘ESC’ to quit full screen

### Actual behavior
_I was builded application by electron-builder，and test application on windows 7 & windows 10_

use shortcut doesn't work，the window still is  full screen

### How to reproduce

```
const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow
const globalShortcut = electron.globalShortcut

const path = require('path')
const url = require('url')
const dialog = electron.dialog

let mainWindow = null

function createWindow () {
	// Create the browser window.
	mainWindow = new BrowserWindow({minWidth: 1024, minHeight: 768, width: 1024, height: 768})

	// and load the index.html of the app.
	mainWindow.loadURL(url.format({
		pathname: path.join(__dirname, 'index.html'),
		protocol: 'file:',
		slashes: true
	}))

	// Open the DevTools.
	// mainWindow.webContents.openDevTools()

	mainWindow.on('close', (e) => {
		/* the user only tried to close the window */
		e.preventDefault()
		mainWindow.hide()
	})
	
	mainWindow.on('maximize', function () {
		mainWindow.setFullScreen(true)
	})

        globalShortcut.register('Esc', () => {
		if (mainWindow.isFullScreen()) {
			mainWindow.setFullScreen(false)
		}
	})
}

app.on('ready', createWindow)

```

**Comment by codebytere** [comment] 2018-04-24 04:40
I'm unable to reproduce this on the latest stable release, `1.8.4`, or current `master` on MacOS Sierra. Is there any other code in your application?

**Comment by jerryyan1990** [comment] 2018-04-25 08:36
@codebytere thanks for replay my question :sparkling_heart:，here is my all code below

```
const electron = require('electron')
// Module to control application life.
const app = electron.app
// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow

const globalShortcut = electron.globalShortcut

const AutoLaunch = require('auto-launch')

const path = require('path')
const url = require('url')
const dialog = electron.dialog
const Menu = electron.Menu
const Tray = electron.Tray

let mainWindow = null
let appTray = null
let haveTray = false

function createWindow () {
	let autoLaunch = new AutoLaunch({
		name: 'appname',
		path: app.getPath('exe')
	})
	autoLaunch.isEnabled().then((isEnabled) => {
		if (!isEnabled) autoLaunch.enable()
	})
	// Create the browser window.
	mainWindow = new BrowserWindow({minWidth: 1024, minHeight: 768, width: 1024, height: 768})
	// quit fullscreen
	globalShortcut.register('Esc', () => {
		if (mainWindow.isFullScreen()) {
			mainWindow.setFullScreen(false)
		}
	})
	// and load the index.html of the app.
	mainWindow.loadURL(url.format({
		pathname: path.join(__dirname, 'index.html'),
		protocol: 'file:',
		slashes: true
	}))
	// Open the DevTools.
	// mainWindow.webContents.openDevTools()
	// tray
	let trayMenu = [
		{
			label: 'exit',
			click: function () {
				dialog.showMessageBox({
					title: "exit",
					message: "are you sure？",
					type: 'warning',
					buttons: ["no", "yes"],
					defaultId: 0
				}, function (index) {
					if (index === 1) {
						app.exit()
					} else {
						if (!mainWindow.isVisible()) {
							mainWindow.show()
						}
					}
				})
			}
		}
	]
	const iconName = 'windows-icon.png'
	const iconPath = path.join(__dirname, iconName)
	if (!haveTray) {
		appTray = new Tray(iconPath)
		haveTray = true
	}
	const contextMenu = Menu.buildFromTemplate(trayMenu)
	appTray.setToolTip('appname')
	appTray.setContextMenu(contextMenu)
	appTray.on('double-click', function () {
		mainWindow.show()
	})
	// hide window
	mainWindow.on('close', (e) => {
		/* the user only tried to close the window */
		e.preventDefault()
		mainWindow.hide()
	})
	
	// maximize
	mainWindow.on('maximize', function () {
		mainWindow.setFullScreen(true)
	})
}

// singleInstance
const shouldQuit = app.makeSingleInstance((commandLine, workingDirectory) => {
	if (mainWindow) {
		if (mainWindow.isMinimized()) {
			mainWindow.restore()
		}
		mainWindow.focus()
	}
})
if (shouldQuit) {
	app.quit()
}
// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
	// On OS X it is common for applications and their menu bar
	// to stay active until the user quits explicitly with Cmd + Q
	if (process.platform !== 'darwin') {
		app.quit()
	}
})

app.on('activate', function () {
	// On OS X it's common to re-create a window in the app when the
	// dock icon is clicked and there are no other windows open.
	if (mainWindow === null) {
		createWindow()
	}
})
app.on('will-quit', function () {
	globalShortcut.unregisterAll()
})
// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.

```

**Comment by sznowak** [comment] 2018-04-30 21:57
I can't reproduce this issue. I have tested Electron 1.8.6 on High Sierra(10.13.4)

**Comment by codebytere** [comment] 2018-05-18 15:48
Does this occur on `2.0.0`? I can't reproduce this either, and so unless it occurs on a later version or one i can reproduce i'm going to go ahead and close this.

**Comment by codebytere** [comment] 2018-05-18 15:48
^ignore me, accidentally closed pre-emptively :)

**Comment by sofianguy** [comment] 2018-08-16 23:12
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2018-08-16 23:12 UTC
Labels: blocked/needs-repro, bug :beetle:, platform/macOS, version/1.8.x
