### ISSUE TITLE
fs.readFile callback function never called

### ISSUE THREAD

**Issue by afloras** [electron/electron#24073] opened 2020-06-11 14:05 UTC
Hello,

I have multiple readFile in my Electron project and it seems the callback function is never called since Electron 9.0.0 was released :

```
const fs = require('fs')
fs.readFile('myconfigfile', 'utf8', function(err, data) {
  // Never called, no error, nothing
  console.log('success')
})
```

Did the syntax change? Am i doing something wrong?

Everything works just fine until Electron 8.3.1 included.

**Comment by miniak** [comment] 2020-06-11 14:25
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by miniak** [comment] 2020-06-11 14:26
@afloras btw I would suggest using the more modern promise based API
https://nodejs.org/api/fs.html#fs_fs_promises_api

**Comment by miniak** [comment] 2020-06-11 14:33
can you please include a full repro, I cannot reproduce this issue in [Fiddle](https://www.electronjs.org/fiddle)

**Comment by afloras** [comment] 2020-06-11 16:12
@miniak Sure, i realize the bug occurs when i change the current window. Here's a test repository : https://github.com/afloras/read-file-callback-bug.

I wasn't aware of the promise methods, are they more efficient in performance?

Thank you.

**Comment by codebytere** [comment] 2020-06-11 17:02
@afloras I believe this is just an issue with your path handling...i changed the following:

```
diff --git a/renderer2.js b/renderer2.js
index 74a5080..4a0d91b 100644
--- a/renderer2.js
+++ b/renderer2.js
@@ -2,8 +2,9 @@
 
 window.addEventListener('load', async function () {
        const fs = require('fs')
+       const path = require('path')
        alert(__dirname + '\\config')
-       fs.readFile(__dirname + '\\config', 'utf8', function(err, data) {
+       fs.readFile(path.join(__dirname, 'config'), 'utf8', function(err, data) {
                if (err) throw err
                alert('success')
        })
```

And it worked as expected with your repro. Closing this out in that event but feel free to respond if something else comes up.

**Closed by codebytere** 2020-06-11 17:02 UTC

**Comment by afloras** [comment] 2020-06-11 17:19
Well, even with this modification, the message 'success' never shows up on electron 9.0.3 and nodejs 12.14.1
I even uninstalled/reinstalled the npm packages... if it works for you, why doesn't it work for me? I'm confused.

**Comment by afloras** [comment] 2020-06-11 21:01
Found the correct answer at last. The callback function was probably called for the previous active renderer due to the electron 9.0 change : app.allowRendererProcessReuse will be default to true (https://www.electronjs.org/docs/api/app).

> A Boolean which when true disables the overrides that Electron has in place to ensure renderer processes are restarted on every navigation. The current default value for this property is true.

I set it to false in my main process and the problem vanishes... Thing is this option will be removed in the future. So is this a bug regarding the option, or do i have to adapt my code so the callback functions are called in my active renderer?

It'd be good someone answers to that, cause i feel that i will not be the only one meeting this inconsistency.

**Comment by YYvanYang** [comment] 2020-07-01 01:36
I also have the same issue. when hot reload in development, it may be not enter the callback function of fs.

**Comment by heylying** [comment] 2021-09-11 08:34
> I also have the same issue. when hot reload in development, it may be not enter the callback function of fs.

me too...Electron V10.4.7

**Comment by alexanderkasten** [comment] 2021-12-06 12:53
Having the same issue with Electron 13.x.x, but only on Windows. MacOS works as expected. 
@afloras  Do you fixed the problem?
