### ISSUE TITLE
getUserMedia calls inside webview do not prompt user 

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#27208] opened 2021-01-06 23:20 UTC
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.1.1
* **Operating System:** MacOS 11.0.1
* **Last Known Working Electron version:** NA

For a webview served up using a electron protocol (`registerStringProtocol`),  calls to `navigator.mediaDevices.getUserMedia` inside the webview do not end up showing a prompt even though I believe the webview is conceptually in its own origin. 

### Expected Behavior
For webview content served up in its own origin, the user should be prompted for permission to access the mic/camera

### Actual Behavior
No prompt and the call to `navigator.mediaDevices.getUserMedia` succeeds for me on all operating systems I've tested on, but you cannot actually record anything on MacOS by default since the app itself does not have mic permissions. You can record on Windows

### To Reproduce
1. Run this electron fiddle: https://gist.github.com/aff16432afe8bb29e61f53a0652ffc62
2. When run, it should record 5 seconds of audio using a webview. Notice that there are no prompts

### Additional Information
If I set `secure: false` for the webview protocol, then the call to `getUserMedia` will always fail. Not sure if there's a way to force the prompt while keeping `secure: true`.

Discovered in https://github.com/microsoft/vscode/issues/113916

/cc @deepak1556

**Comment by miniak** [comment] 2021-01-24 05:45
@mjbvz what kind of prompt do you mean? Electron does not show any prompts by default, which is by design. You must implement your own using `webContents.session.setPermissionRequestHandler()`

**Comment by mjbvz** [comment] 2021-02-02 02:40
Thanks! I do see that being called, so I think we can work around this

However shouldn't this default to false if no one has implemented it? We implemented this for our main browser window but overlooked it for webviews, which are in a separate session/partition

**Comment by deepak1556** [comment] 2021-03-12 04:35
> However shouldn't this default to false if no one has implemented it? 

Its tracked in https://github.com/electron/electron/issues/12931

Closing this one as per design.

**Closed by deepak1556** 2021-03-12 04:35 UTC
Labels: 11-x-y, bug :beetle:, platform/macOS
