### ISSUE TITLE
Backspace can not erase the last one character during Japanese IME conversion (macOS) 

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#9173] opened 2017-04-12 13:23 UTC
* Electron version: 1.6.2, 1.6.6, not 1.4.16
* Operating system: macOS 10.12.2 Sierra, macOS 10.12.4

### Expected behavior

When inputting Japanese sentences using the Japanese IME (Input Method Editor) to convert alphabets to Japanese (CJK) characters you should be able to delete each character in turn by pressing backspace

### Actual behavior

The very last character always needs two backspace presses

### How to reproduce

* Clone my version of electron starter
```
$ git clone https://github.com/wavebox/electron-quick-start -b japanese_delete_bug
$ npm install
$ npm start
```
* Go to `System preferences` > `Language & Region`
* Press the `+` to add a language and add Japanese (about a whole scroll down for me)
* When prompted use your current language as the primary language
* Launch the repository clone of quickstart (above)
* Using the flag icon in the mac top bar change your current input method to Katakana
* Click in the input field, type a few characters, then start hitting backspace
* To delete the last character you have to hit backspace twice

Some other things about this I've found...
* Remove the webview tag from the page and it works as expected (input field is not within the webview, but does also affect it there)
* Issue is reproducible in 1.6.2 & 1.6.6 (maybe others inbetween)
* Issue not apparent in 1.4.16
* Some gifs of the behaviour in the [original issue](https://github.com/wavebox/waveboxapp/issues/44#issuecomment-293243627)

**Comment by kevinsawicki** [comment] 2017-04-24 20:10
I reported a related issue upstream where when the input is inside the `<webview>` tag, two backspaces are required to delete the last character, https://bugs.chromium.org/p/chromium/issues/detail?id=714771

**Comment by kevinsawicki** [comment] 2017-05-22 21:03
This will be fixed in the next Electron release, 1.7.2

**Comment by Thomas101** [comment] 2017-05-24 07:52
Awesome thank you :)

**Comment by kevinsawicki** [comment] 2017-07-10 21:32
Reopening this since the original fix introduced #9709 on 1.7.x.

Will revisit in 1.8.x since we can land further patches from upstream Chrome that have been applied since this original fix.

**Comment by achimnol** [comment] 2017-07-17 02:27
This seems to be affecting the current releases of Slack, Microsoft Teams, and some other Electron-based apps. Subscribing this issue with hopes to be fixed soon!

**Comment by gerges** [comment] 2017-10-12 19:58
I'm having a hard time understanding the status of this issue. As far as i can tell this is fixed in 1.6.x, broken in 1.7.x, and ideally will be fixed again in 1.8.x? Is that correct?

**Comment by chenerzhang** [comment] 2018-01-10 06:32
any update?

**Comment by chenerzhang** [comment] 2018-01-26 13:39
You can test this way. My trouble is Chinese IME and this can help me solve this problem on mac.
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Hello World!</title>
  <style>
    *,
    *::before,
    *::after {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    html,
    body {
      width: 100%;
      height: 100%;
    }

    body {
      display: flex;
      flex-direction: column;
    }

    webview {
      flex: 1;
      width: 100%;
    }

    input {
      height: 300px;
    }
  </style>
</head>

<body>
  <textarea rows="10" id="input"></textarea>
  <webview src="https://www.google.com"></webview>
  <script>
    // You can also require other files to run in this process
    require('./renderer.js');
    const { exec, spawn } = require('child_process');

    const $input = document.querySelector('#input');
    let inputTimeStamp = 0;
    let inputNums = 0;
    let delta = 1;
    let backspaceKeydownTimestamp = 0;
    $input.addEventListener('input', (e) => {
      inputTimeStamp = e.timeStamp;
      inputNums += delta;
    });
    $input.addEventListener('keyup', (e) => {
      if (e.key === 'Backspace') {
        let deleteFlag = false;
        // slow delete detect
        if (inputTimeStamp === -1) {
          deleteFlag = true;
          delta = 1;
          inputTimeStamp = 0;
          exexDelete();
        }
        // quick delete detect
        if (!deleteFlag && inputNums === 1 && e.timeStamp - backspaceKeydownTimestamp < 60) {
          inputNums = 0;
          exexDelete();
        }
      }
      inputTimeStamp = -1;
    });
    $input.addEventListener('keydown', (e) => {
      if (e.key === 'Backspace') {
        backspaceKeydownTimestamp = e.timeStamp;
        delta = -1;
      } else {
        delta = 1;
      }
    });
    $input.addEventListener('compositionstart', () => {
      inputTimeStamp = 0;
      inputNums = 0;
      delta = 1;
      backspaceKeydownTimestamp = 0;
    });
    function exexDelete() {
      const ps = spawn('osascript');
      ps.stdin.write(`
      tell application "System Events"
        keystroke ascii character 8
      end tell
      `);
      ps.stdin.end();
    }
  </script>
</body>

</html>
```

**Comment by zjfjiayou** [comment] 2018-01-29 13:16
I have encountered the same problem in this version 1.7.11. The language is Chinese.

**Comment by fateleak** [comment] 2018-02-13 10:28
same problem on 1.7.10, Chinese

**Comment by kenan2002** [comment] 2018-04-11 10:47
I'm in trouble with this issue, too.
I see that this issue has been fixed in Electron 2.0 beta which is based on Chromium 61. Is there any plan on an Electron 1.x version based on Chromium 61 or above so that we can fix this issue without any impact of breaking-changed API?

**Comment by shadeofgod** [comment] 2018-04-11 13:26
Yes, we really need this to be fixed, pls make it happen in 1.8.x if possible, plsssssssssss
🙇

**Comment by shuntaroy** [comment] 2018-06-28 03:05
Even v2 reproduces the same issue again. I confirmed it on Atom v1.29.0 which uses Electron v2. How many times does this issue give us pain...

**Comment by codebytere** [comment] 2018-09-24 04:44
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by tete1030** [comment] 2018-12-03 11:01
> We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

The version 2.0.12 is still broken on this issue after it was fixed in 2.0 beta. VSCode's latest version 1.29.1 is using Electron 2.0.12. Please see:
https://github.com/Microsoft/vscode/issues/37114#issuecomment-433195512

I'm using macOS 10.14.1

**Comment by tete1030** [comment] 2018-12-04 06:17
Sorry, while I can reproduce this issue in v1.8.8, I cannot reproduce it in 2.0.7, 2.0.12, 3.0.10, 4.0.0-beta.8 .
I tested them with Electron Fiddle with the following code using macOS Pinyin input method.
```
<webview src="data:text/html,<input type=text />"></webview>
```
I'm also reporting this result to the vscode issue.

**Comment by rebornix** [comment] 2018-12-04 17:51
@tete1030 input in webview is not affected while input outside of webview is still running into this issue.

Sample html to reproduce

```
<input />
<webview src="data:text/html,<input type=text />"></webview>
```


The issue is gone in 3.0.10 and 4.0.0-beta.8 but IMO we should have a fix for 2.x

**Comment by sofianguy** [comment] 2019-08-09 04:03
Given this is reported as fixed in 4.x, I will close this issue. We are no longer supporting versions earlier than 4.x

**Closed by sofianguy** 2019-08-09 04:03 UTC
Labels: 2-0-x, bug/regression :leftwards_arrow_with_hook:, chromium, component/webview, platform/macOS
