### ISSUE TITLE
Input method shows at wrong position in webview while typing

### ISSUE THREAD

**Issue by KynoYang** [electron/electron#6141] opened 2016-06-20 04:40 UTC
* Electron version: 1.2.2
* Operating system: OSX 10.11.5

It's quite normal in Chrome or without webview. So, I guess maybe something wrong with it. Below is the example gif.  [Here](https://github.com/KynoYang/ElectronSpellCheckerDemo) is the example code.
![zoom_0](https://cloud.githubusercontent.com/assets/2586026/16183331/2fe5b54c-36e3-11e6-8b91-fd9ac42a5ff5.gif)

**Comment by zcbenz** [comment] 2016-06-20 07:05
This is a duplicate of #4539.

**Closed by zcbenz** 2016-06-20 07:05 UTC
