### ISSUE TITLE
Cannot use touch keyboard with password fields

### ISSUE THREAD

**Issue by conteit** [electron/electron#13832] opened 2018-07-27 09:09 UTC
* Electron Version: 2.0.4
* Operating System (Platform and Version): Windows 10 1803
* Last known working Electron version: N/A

**Expected Behavior**
When focusing a password field, like any other text field, the touch keyboard should stay open.

**Actual behavior**
When focusing a password field the touch keyboard disappears

**To Reproduce**
Create an Electron app with a BrowserWindows that opens a web page with a login form. Enable Tablet Mode in Windows and try to fill username and password via touchscreen monitor. When tapping on the username field the Touch Keyboard shows, while when tapping on the password field it disappears.

**Additional Information**
It looks like it is related to a breaking change in Windows 10 1803 that breaks Chromium behaviour. See https://bugs.chromium.org/p/chromium/issues/detail?id=853403

**Comment by MarshallOfSound** [comment] 2018-07-30 03:22
Looks to be fixed by https://chromium-review.googlesource.com/c/chromium/src/+/946928, someone just needs to backport that as a patch to libcc 👍

**Comment by mekza** [comment] 2018-08-03 09:28
Hello, I just wanted to know when this bug will be fixed. MSFT is currently forcing users to upgrade to 1803.

**Comment by conteit** [comment] 2018-08-06 08:50
I've tried to see if the backport was easy, but it looks like the required feature is implemented somewhere between the libcc's chromium version and the fix that has been linked above.

Should I open an issue in libcc referring to this one, in order to let someone more competent than me try to backport the patch?

**Comment by mekza** [comment] 2018-08-06 09:51
@conteit good idea.

**Comment by mekza** [comment] 2018-08-16 09:49
Hey! Any update on this issue?

**Comment by toddfhenry** [comment] 2018-08-16 18:59
Bump!  We really need an update on this.  Appreciate this getting some attention.  Thanks.

**Comment by ildade** [comment] 2018-08-28 09:10
We are experiencing the same issue, and it is _heavily_ impacting on the usage of every application running in "kiosk" mode, which is something Electron is perfect for.

Is there any update about the patch release?

Thanks a lot!

**Comment by scrozier** [comment] 2018-09-17 17:47
+1 This is keeping us from deploying an Electron app that we'd love to deploy this way.

**Comment by happypoulp** [comment] 2018-09-24 16:05
This issue seems to also reproduce on Electron@3 for **password inputs** as well as for **text inputs**.

**Comment by conteit** [comment] 2018-09-27 07:05
It looks like a new Windows update may have solved the bug. Anybody else can confirm?

**Comment by toddfhenry** [comment] 2018-09-27 07:13
We have it working at Nanthealth Inc. with 3.0 and some integration and custom code on our end.

R,
Todd Henry
Sr. Director Product Engineering
Nanthealth Inc.
Sent from my iPhone
CONFIDENTIALITY NOTICE
This e-mail message and any attachments are only for the use of the intended recipient and may contain information that is privileged, confidential or exempt from disclosure under applicable law. If you are not the intended recipient, any disclosure, distribution or other use of this e-mail message or attachments is prohibited. If you have received this e-mail message in error, please delete and notify the sender immediately. Thank you.

________________________________

**Comment by happypoulp** [comment] 2018-09-27 14:04
I am still reproducing the issue on a **Surface device (Windows 10 1803 with latest updates)** + **electron 3.0.1**. 

However, I just found out that the issue seems to be present only if the window is opened with option `show: false` (and shown in a window.webContents 'did-finish-load' handler). If the window is opened without `show: false` option, the touch keyboard appears as expected when focusing an input. I can make a reproducible example if it helps.

**Comment by toddfhenry** [comment] 2018-09-27 15:29
Hey Francois:

We don’t use the windows setting:false, we removed that since we reworked the electron code too.  We do use Surface Pro tablets though running 1803+
R,
Todd Henry | Sr. Director Product Engineering |  Office Tel: +1 850.270.1369 | Mobile: 757.286.3739  | Email<mailto:todd.henry@nanthealth.com> | 430 West 5TH St. Suite 800, Panama City, FL 32401
[cid:image001.png@01D36925.654EDD10]<http://www.nanthealth.com/> |  [cid:image002.png@01D36925.654EDD10] <http://www.facebook.com/nanthealth>      [cid:image003.png@01D36925.654EDD10] <http://www.twitter.com/nanthealth>      [cid:image004.png@01D36925.654EDD10] <http://www.linkedin.com/company/nanthealth>
 CONFIDENTIALITY NOTICE
This e-mail message and any attachments are only for the use of the intended recipient and may contain information that is privileged, confidential or exempt from disclosure under applicable law. If you are not the intended recipient, any disclosure, distribution or other use of this e-mail message or attachments is prohibited. If you have received this e-mail message in error, please delete and notify the sender immediately. Thank you.

**Comment by happypoulp** [comment] 2018-09-27 15:50
I can get rid of `show: false` too, but maybe there is a patch to fix the issue regardless of the usage of this option?

**Comment by conteit** [comment] 2018-09-27 15:58
In my case `show: false` is not used, but the issue still occur.. It looks like the windows updates installed on Sep 13, 2018 solved the issue. I'm still trying to find exactly what makes the magic.

**Comment by pronebird** [comment] 2018-11-12 14:11
We don't see the keyboard used on regular text fields either on Surface Pro.

**Comment by sirius007** [comment] 2019-01-14 06:09
who fixed it

**Comment by nornagon** [comment] 2019-01-14 23:38
I believe this was fixed upstream in Chromium and we just inherited the fix by upgrading.

**Comment by pronebird** [comment] 2019-01-15 09:17
@nornagon was this fix merged to the latest Electron?

**Comment by appskitchen** [comment] 2019-01-16 15:56
@nornagon where should we run that command? I tried it from windows command prompt but it says 
```
'--enable-features' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by appskitchen** [comment] 2019-01-16 16:11
@happypoulp Could you share an working example repo for windows 10 1803? Really appreciate it. Thanks

**Comment by happypoulp** [comment] 2019-01-16 16:25
@appskitchen I did not do anything special appart from going from

```js
const win = new BrowserWindow({
    frameLess: true,
    frame: false,
    webPreferences: {
        plugins: true,
        nodeIntegration: false,
        webviewTag: true,
    },
    show: false,
})

win.webContents.once('did-finish-load', () => {
    win.show()
})
```

to 

```js
const win = new BrowserWindow({
    frameLess: true,
    frame: false,
    webPreferences: {
        plugins: true,
        nodeIntegration: false,
        webviewTag: true,
    },
})

win.webContents.once('did-finish-load', () => {
    // No need for this anymore
    // win.show()
})
```

And it fixed the issue for me.

**Comment by appskitchen** [comment] 2019-01-16 20:09
@happypoulp Thanks to share the codes but it doesn't work either.

**Comment by appskitchen** [comment] 2019-01-23 14:27
@nornagon I tried the following codes in main.js not sure if there are correct but it didn't resolve the issue.

```
  app.commandLine.appendSwitch('InputPaneOnScreenKeyboard') 
  app.commandLine.appendSwitch('--enable-features=InputPaneOnScreenKeyboard') 
```

**Comment by nornagon** [comment] 2019-02-05 21:03
```js
app.commandLine.appendSwitch('enable-features', 'InputPaneOnScreenKeyboard')
```
should do it.

**Comment by sirius007** [comment] 2019-02-13 09:54
@nornagon thanks for share codes，it works

**Comment by appskitchen** [comment] 2019-02-13 14:14
> 
> 
> ```js
> app.commandLine.appendSwitch('enable-features', 'InputPaneOnScreenKeyboard')
> ```
> 
> should do it.

Thanks, It works.

**Comment by nornagon** [comment] 2019-02-13 18:51
Great, well then this issue should be fixed on 5.x and higher. I'll open a PR to backport https://chromium-review.googlesource.com/c/chromium/src/+/946928 to 4-0-x and then it should be fixed on 4 as well.

**Closed** 2019-05-09 17:51 UTC
Labels: 2-0-x, bug/os-regression, platform/windows, status/confirmed
