### ISSUE TITLE
Cannot use eval on iframe

### ISSUE THREAD

**Issue by baconface** [electron/electron#5096] opened 2016-04-08 22:30 UTC
* Electron version: 0.36.12 (earliest tested) to 0.37.5 (latest)
* Operating system: Windows 8.1

I am working on a project to test some code in a sandboxed iframe that gives limited access to the parent. The implementation is pretty straight forward. The problem is it works in modern web browsers but not in Electron. It is even verified working in Chrome. And both the jQuery and vanilla JS versions produce the same results.

The iframe is created with:
```javascript
$('<iframe>', {
	src: 'about:blank',
	id:  'ptg-sandbox',
	frameborder: 0,
	scrolling: 'no',
	style: 'width: 0px; height: 0px; display: none;'
}).appendTo('body');
```

And then the eval works much like:
```javascript
$('#ptg-sandbox')[0].contentWindow.eval('alert("test");');
```

Code is in place to ensure the iframe exists in the DOM before firing the code. So I ruled that out. The expected result should be an alert that says "test". But unfortunately I can't get it and no error is returned. If it helps to know I am also have nodeIntegration set to false for this BrowserWindow.

**Comment by baconface** [comment] 2016-04-09 00:09
Does not work with the latest version (0.37.5) as well.

**Comment by jean-emmanuel** [comment] 2016-04-09 09:00
Isn't it just the alert() method that can't run in this context ? Executing some more trivial code seems to work just fine : 

`$('#ptg-sandbox')[0].contentWindow.eval('2+2');` prints `4` the console.

Also, have you been considering using node's native [`vm`](https://nodejs.org/api/vm.html) module, either by remote requiring it in the browser or through ipc in the main process ?

**Comment by baconface** [comment] 2016-04-11 06:39
In the browser context alert() can work. So if I use Electron with nodeIntegrate set to false I should expect the same result. At least that is what I should expect?

Also since I am needing it to mirror the results of the browser context and not the node/Electron context I can't use the VM module for this case. Thanks for the suggestion though.

The idea is to not call a particular method but eval complete scripts. So I can't get away with iframe.contentWindow.method either. I tried to document.write script tags with it in place but I didn't get the results I was looking for as well due to browser restrictions. I have a few other ideas for a work around but won't try them until I am in the office Monday.

Either way, I just thought Electron in this usage should replicate Chromium. But I also know this is a fringe case type of situation.

**Comment by zcbenz** [comment] 2016-04-11 23:47
This is a duplicate of #2644.

**Closed by zcbenz** 2016-04-11 23:47 UTC

**Comment by baconface** [comment] 2016-04-12 05:22
Didn't see that. If no alerts is the case then I am all good since I was only using them for testing the eval. Thanks @zcbenz .
