### ISSUE TITLE
Menu entries with a submenu cannot be disabled

### ISSUE THREAD

**Issue by ricardomatias** [electron/electron#3416] opened 2015-11-12 14:57 UTC
When I set ´enabled: false´ to a menu entry which has a submenu with more entries, it doesn't get disabled.

Platform: Mac OS X

**Comment by bundyo** [comment] 2016-01-15 15:25
Possibly similar issue can be reproduced in Windows - root items can't be disabled at all, regardless if there is a submenu on the item or not. (Tested with 0.35.5)

**Comment by bengotow** [comment] 2016-04-22 21:39
This may not actually be the intended behavior. I just noticed that in Apple's Mail.app and Messages.app, you can open disabled submenus:

![image](https://cloud.githubusercontent.com/assets/1037212/14755548/fa1b12fa-0897-11e6-8ea3-b264c49ccbee.png)

![image](https://cloud.githubusercontent.com/assets/1037212/14755552/022e5862-0898-11e6-8a4b-bfa0813eefeb.png)

**Comment by erkyrath** [comment] 2016-08-04 19:01
It would still be reasonable to disable all the child entries (recursively) when a submenu item is disabled.

**Comment by Dexwell** [comment] 2017-04-06 15:48
@bengotow It should be a possibility though. See Finder > Go > Recent Folder if the user has clicked Clear Menu in that submenu. 'Recent Folder' itself becomes disabled.

**Comment by codebytere** [comment] 2017-09-27 01:37
closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:37 UTC
Labels: component/menu, fixme/bug, platform/macOS

**Comment by chrilith** [comment] 2018-01-04 19:02
Hum, why this issue as been closed? Auto-close because of inactivity?
The problem is still there. It would be nice to have an official answer to this problem.

The screenshot posted by @bengotow clearly shows that menu items can be disabled even if they have submenus.

It is a real pain to have to disable all child entries in order to mimic this behavior (and parent menuItem is still enabled of course).

Thanks!
