### ISSUE TITLE
Devtools console crashes with Electron 1.8.2-beta.3

### ISSUE THREAD

**Issue by burkoyuriy** [electron/electron#11642] opened 2018-01-15 09:05 UTC
When I try to enter a command into the devtool console, the program crashes

**Comment by vulture** [comment] 2018-01-16 16:57
I ran into the same issue. The problem is that this was fixed in master but never merged into the stable branches. This is the commit that fixed it for me iirc https://github.com/electron/electron/pull/11233/commits/d5ab691fdb2f954141c9b1713346a13efd9151ab

**Comment by sakamudis** [comment] 2018-01-23 04:22
I have updated electron to latest version Eletronc1.8.2-beta.3. when I tried to type in Devtools console application  was crashing.

**Comment by bryphe** [comment] 2018-01-23 20:48
I'm hitting the same issue with Electron v1.8.2-beta4

**Comment by vulture** [comment] 2018-01-23 22:32
![image](https://user-images.githubusercontent.com/216979/35304336-00336b6e-004a-11e8-9e8f-b54e502435aa.png)

Yeah they forgot to pull it in for the security update, but it's totally in there now for next time. :)

**Comment by codebytere** [comment] 2018-01-25 05:40
Closing as this will be remedied with the next release :)

**Closed by codebytere** 2018-01-25 05:40 UTC
Labels: triaged/bug

**Comment by brenca** [comment] 2018-01-28 23:59
Duplicate of #11375
