### ISSUE TITLE
[Bug]: electron does not render webgl in offscreen mode

### ISSUE THREAD

**Issue by Monster-mr** [electron/electron#39859] opened 2023-09-14 07:40 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 家庭中文版 22621.2283

### What arch are you using?

x64

### Expected Behavior

I'm using electron to make a app which renders webgl for remote usage via webrtc, I created a BrowserWindow in offscreen mode, and created webrtc connection using peer.js, the remote video contains only one frame as still image, all the animations in the page loaded with loadURL does not render, it seems only the first frame is rendered.

### Actual Behavior

Every frame should be rendered and send to remote video.

### Additional Information

Code:
```javascript

  mainWindow = new BrowserWindow({
    width: 800,
    height: 500,
    // enableLargerThanScreen: true,
    // resizable: false,
    // frame: false,
    // // show: false,
    // skipTaskbar: true,
    // paintWhenInitiallyHidden: true,
    webPreferences: {
      backgroundThrottling: false,
      preload: path.join(__dirname, 'preload.js'),
      sandbox: false,
      offscreen: true,
      // webSecurity:false,
      allowRunningInsecureContent: true,
    },

  });
  mainWindow.webContents.setFrameRate(30);
  mainWindow.focusOnWebView()
  mainWindow.webContents.startPainting();

	mainWindow.webContents.on('did-finish-load', async () => {
		// mainWindow.webContents.setFrameRate(60);
		// mainWindow.webContents.setBackgroundThrottling(false);
		mainWindow.webContents.startPainting();
    // mainWindow.focus()
    // mainWindow.focusOnWebView()
    setInterval(() => {
      console.log(mainWindow.webContents.isPainting()) // true
      console.log(mainWindow.webContents.isFocused()) // false
    }, 3000);
	})
      const { session } = require('electron')


    session.defaultSession.setDisplayMediaRequestHandler((request, callback) => {
      // Allow the tab to capture itself.
      callback({ video: request.frame });
    });
```

preload:
```javascript
require("./libs/peer.js")
let connOption = { host: 'localhost', port: 9000, path: '/myapp', debug: 2 , secure: false, };

let peer
peer = new Peer("11111111111",connOption);


peer.on("call", async (call) => {

    try {
      const stream = await navigator.mediaDevices.getDisplayMedia({
        audio: false,
        video: true,
      })

      call.answer(stream)
    } catch (e) {
      // handleError(e)
    }
  // } else {
  //   call.close();
  // }
});


```

**Comment by mlaurencin** [comment] 2023-09-25 19:17
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

If possible, would it be possible for you to make your provided code into a standalone testcase to reproduce the issue without peer.js? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

If not possible, you may have have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I'm adding the `blocked/need-info` label for this reason. Please make a follow-up comment with the new test case or this issue will be closed in 10 days.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2023-10-10 10:38
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2023-10-10 10:38 UTC
Labels: blocked/need-info ❌, bug :beetle:

**Comment by qian-jiang** [comment] 2024-11-05 03:35
你好，请问后续有解决这个问题吗
