### ISSUE TITLE
Webview Not Displaying

### ISSUE THREAD

**Issue by domkalan** [electron/electron#5132] opened 2016-04-13 04:04 UTC
* Electron version: v0.37.5
* Operating system: Fedora Workstation 23

As far as I can see in the latest version, `<webview>` is not working for me. The element is on the document but Electron seems to skip right over it. On the other hand `<iframe>` seems to work as expected. I have had it setup similar to the following:

`<html>
  <head>
    <style>
      .box {
        height: 500px;
        width: 500px;
      }
    </style>
  </head>
  <body>
    <p>IFrame</p>
    <iframe class="box" src="https://www.github.com/"></iframe>
    <p>Webview</p>
    <webview class="box" id="foo" src="https://www.github.com/"></webview>
  </body>
</html>`

Screenshot:
![electron](https://cloud.githubusercontent.com/assets/6377796/14482418/6ff2d836-00f1-11e6-9806-75ee7f25a7b4.png)
**Note:** I am aware that GitHub not loading in the iframe, that is **NOT** the error I am trying to report.

**Comment by xywz** [comment] 2016-04-13 07:51
Duplicate of #1117.

Add `<script>void 0</script>` to your HTML until the next release, which will include #5118.

**Comment by zcbenz** [comment] 2016-04-14 05:07
@xywz Thanks for answering it!

**Closed by zcbenz** 2016-04-14 05:07 UTC
