### ISSUE TITLE
Uncaught Error: Module version mismatch. Expected 49, got 47. after upgrading to 1.3.3

### ISSUE THREAD

**Issue by Iliyass** [electron/electron#6843] opened 2016-08-15 10:13 UTC
* Electron version: v1.3.3
* Operating system: OS X El Capitan and Ubuntu 14.04 LTS
* Node version: v6.3.0

I have been using v0.36.6 and I faced a menu context problem, so I tried to upgrade electron to latest version after I have finished upgrading I tried to build it, it run throwing 
```
Uncaught Error: Module version mismatch. Expected 49, got 47. ELECTRON_ASAR.js:167 
```
I have installed `electron-rebuild` and I run `./node_modules/.bin/electron-rebuild` and still the same error 

Any help guys ?

**Comment by enlight** [comment] 2016-08-15 12:06
Every single time I've seen people encounter this issue it was because they didn't rebuild the module properly. Make sure you set the target to the exact Electron version you're using when you do the rebuild.

**Comment by MarshallOfSound** [comment] 2016-08-15 12:13
> Every single time I've seen people encounter this issue it was because they didn't rebuild the module properly. Make sure you set the target to the exact Electron version you're using when you do the rebuild.

This is exactly the same as my experience.  The safest thing to do is clean out your `node_modules` folder and run `npm install` then rerun `electron-rebuild`.  

Closing this out as it is not a bug with electron rather a question / support request.

**Closed by MarshallOfSound** 2016-08-15 12:13 UTC

**Comment by Iliyass** [comment] 2016-08-15 14:16
@enlight @MarshallOfSound I have already executed `electron-rebuild .` with no luck

**Comment by MarshallOfSound** [comment] 2016-08-15 14:18
@Iliyass What module in particular is causing this issue?

**Comment by Iliyass** [comment] 2016-08-15 14:28
I just can't tell which module that causing this issue, because the error is not helping

**Comment by MarshallOfSound** [comment] 2016-08-15 14:30
@Iliyass Can you provide a minimal app that reproduces the error / is your code public?

**Comment by robin850** [comment] 2016-09-01 20:25
Hi there !

I stumbled against this problem and here's the solution if anyone is  in the same situation (I highly doubt, but anyway :smile: ) ; the problem was that I had a `start` script inside my `package.json` which was just `"electron main.js"` ; the problem is that I hate to have the `node_modules` folder inside my project because we can't just `cloc .` or `grep` without having to pass special options so I just `mv node_modules ..` after each `npm install`.

The problem was that then, running `npm start`, finding no `node_modules/.bin` folder, NPM would pick the electron binary inside the PATH, which is not matching the version the native addon was re-build against.
