### ISSUE TITLE
[Bug]: Finder becomes unresponsive once using shell.showItemInFolder

### ISSUE THREAD

**Issue by oalfroukh** [electron/electron#42082] opened 2024-05-08 08:46 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura

### What arch are you using?

x64

### Last Known Working Electron version

24.8.8

### Expected Behavior

using `shell.showItemInFolder` from `non-sandboxing` renderer process should show the items on the `Finder` without affecting its responsiveness

### Actual Behavior

When using `shell.showItemInFolder` to show an item on the `Finder` it will make the `Finder` unresponsive for more than a minute till shows the item.

### Testcase Gist URL

https://gist.github.com/f90c413dc438ac760ffbb14af496aeed

**Comment by codebytere** [comment] 2024-05-08 13:59
Duplicate of https://github.com/electron/electron/issues/38540

**Closed by codebytere** 2024-05-08 13:59 UTC
Labels: platform/macOS, bug :beetle:, has-repro-gist, component/shell, 30-x-y, 31-x-y
