### ISSUE TITLE
[Bug]: In Draw.io, opening a child window results in opening it on the background

### ISSUE THREAD

**Issue by rickiewars** [electron/electron#34341] opened 2022-05-24 13:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.2

### What operating system are you using?

Other Linux

### Operating System Version

Manjaro KDE edition

### What arch are you using?

x64

### Expected Behavior

In the Drawio-Desktop application, when opening a new window by clicking on `Open`, `Save as`, `Import...`, etc. a new window should open and be in focus which will show an interface to browse on your filesystem.

### Actual Behavior

In the Drawio-Desktop application, when opening a new window by clicking on `Open`, `Save as`, `Import...`, etc. a new window opens in the background and has no focus. The new window does appear in the taskbar and when clicking on that icon, the window will go to the foreground and get focus and will show you an interface to browse on your filesystem.

### Additional Information

An pull-request has originally been opened on the github page of Drawio-Desktop but the developers told me there is nothing they can do to fix it and that it has to be fixed upstream in Electron.
Here is the link to the original post: [https://github.com/jgraph/drawio-desktop/issues/430](https://github.com/jgraph/drawio-desktop/issues/430)
(i am not the developer of DrawIO or DrawIO-Desktop)

My thanks in advance.

**Comment by codebytere** [comment] 2022-05-26 07:35
Duplicate of https://github.com/electron/electron/issues/32857

**Closed by codebytere** 2022-05-26 07:35 UTC
Labels: platform/linux, bug :beetle:, blocked/need-repro
