### ISSUE TITLE
new Window opens Windows 10 Store

### ISSUE THREAD

**Issue by HurricanKai** [electron/electron#9543] opened 2017-05-21 16:04 UTC
* Electron version: 1.6.11, 1.7.4
* Operating system: Windows 10

### Expected behavior

Normaly just my new (empty) window shoud appear

### Actual behavior

My Window appears, but it also opens the Windows 10 Store Dialog, where it says "you need an application to open xyz"

### How to reproduce

Create an new Electron project by installing Electron using
$ npm install electron
add code for opening an new window on button press.

###additonal stuff:

Im completly new to Electron and js in general.

**Comment by MarshallOfSound** [comment] 2017-05-22 09:58
@HurricanKai Can you provide sample code that replicates the scenario you are describing? 😄

**Comment by HurricanKai** [comment] 2017-05-30 19:53
Ill paste it here, but the files are also in Attached
Modules were installed using
`npm install electron




[helloworld.zip](https://github.com/electron/electron/files/1039529/helloworld.zip)





`

Sure:
Main.js:
`const electron = require('electron')
const {app, BrowserWindow} = electron

app.on('ready', () => {
    let win = new BrowserWindow({width:800, hieght: 600})
    win.loadURL(`file://${__dirname}/index.html`)
    //win.webContents.openDevTools()
})

exports.openWindow = () => {
    let win = new BrowserWindow({width:400, height:200})
    win.loadURL(`fiel://${__dirname}/cam1.html`)
}`

index.js:
`const remote = require('electron').remote
const main = remote.require('./main.js')

var button = document.createElement('button')
button.textContent = 'Open window'
button.addEventListener('click', () => {
    main.openWindow()
}, false)
document.body.appendChild(button)`

index.html:
`<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="UTF-8">
<title>Hello World!</title>
</head>
<body>
    <h1>Hello World!</h1>
    <script>require('./index.js')</script>
</body>
</html>
`

Cam1.html:
`<!DOCTYPE html>
<html lang="de"?>
<head>
<meta charset="UTF-8">
<title>Cam1</title>
</head>
<body>
    <h1>Here will The Cam1 View go!</h1>
</body>
</html>`

**Comment by enlight** [comment] 2017-07-30 05:14
The zip you've attached doesn't appear to exist, can you put your project in a GitHub repo?

**Comment by HurricanKai** [comment] 2017-08-03 09:19
here you go:
https://github.com/HurricanKai/Issue-With-Electron

**Comment by enlight** [comment] 2017-08-03 09:38
Thanks, I can reproduce in Electron 1.6.11 and 1.7.4. You have a typo in `win.loadURL(`fiel://${__dirname}/cam1.html`)`, `fiel` should be `file`. But this is definitely a bug in Electron, it shouldn't be passing the URL to the OS if the scheme is unregistered.

**Comment by enlight** [comment] 2017-08-03 16:57
Upon further examination when Chromium encounters a protocol it doesn't know what to do with it forwards the URL onto `AtomResourceDispatcherHostDelegate::HandleExternalProtocol()` which basically just calls `shell.openExternal()`. That all makes perfect sense when a user clicks on a `mailto:` link for example, but when you pass such a URL to `BrowserWindow.loadURL()` you end up with a blank browser window. Maybe there's a case to be made that Electron should throw some kind of error, but I don't think this is a bug.

Closing this issue since it's been resolved.

**Closed by enlight** 2017-08-03 16:57 UTC
Labels: platform/windows, version/1.6.x, version/1.7.x
