### ISSUE TITLE
--enable-logging option does not consistently produce output on windows 8.1

### ISSUE THREAD

**Issue by rainyday** [electron/electron#6946] opened 2016-08-23 20:19 UTC
- Electron version: 1.3.4
- Operating system: Windows 8.1 x64

Running electron  with the `--enable-logging` option does not reliably actually show any logging when run on Windows 8.1. Occasionally it will log to the console as expected but the vast majority of the time when launching, it will instead spawn a new blank console window that remain empty for the duration of the application's runtime.

**Comment by paulcbetts** [comment] 2016-08-23 21:02
This is deeply frustrating to me, can we please just reenable logging? This pretty thoroughly trolls new users who don't understand why their `console.log` statements don't show up and think that it's broken

**Comment by zcbenz** [comment] 2016-08-24 07:22
This seems like a new behavior of Chrome 52, currently you can use the `ELECTRON_ENABLE_LOGGING` environment variable instead.

@paulcbetts Enabling logging by default makes it impossible to turn off logging after Electron runs, and it only disables logging from Chromium, the output from JavaScript are always printed.

**Comment by Metamist** [comment] 2016-11-28 15:59
Setting `ELECTRON_ENABLE_LOGGING=true` does not work for me at all, it simply doesn't log anything to the console, and using `--enable-logging` yields the same results as the OP is describing. I tried setting the environment variable globally in windows, or setting it in the command line before executing the electron command, neither worked.

**Comment by JonMarbach** [comment] 2017-03-14 23:50
I'm experiencing the same issue here. --enable-logging worked for maybe 5 runs, and then all subsequent runs are opening 2-3 blank console windows. (I believe I'm running Electron 1.6.x on Windows 8.1.)

I'm a new electron user and as awesome as electron seems in other areas, I've probably sunk a few hours into trying to make console.log work... Not exactly a productive afternoon! Like someone else posted, this is  a big detriment to the new-developer experience. 

For the few times that it worked, I was also disappointed that it logged everything from main and from the browser (including those chrome logging prefixes)...

**Comment by RedMaps** [comment] 2017-04-11 17:13
I am still experiencing the same issue.
The difference for me is that I'm running Windows 10. Until now I spendt the whole day trying to figure out what the problem is, but I can't get the console to output any console.log() statements. 

One thing to note is that when I run my app with node, except for of course giving me an error, it does actually output the log to the console.

I hope this can be fixed easily, or maybe its just me being stupid and doing something wrong.

**Comment by melgeo** [comment] 2017-05-18 19:57
try to run you app like this:
C:\myproject\node_modules\electron\dist\electron.exe myapp.js

**Comment by tkshnwesper** [comment] 2017-06-12 17:47
I am facing the same issue on Windows 8.1, please kindly address this. It's impossible to code the main process without `console`.

**Comment by mporter-di** [comment] 2017-06-19 14:03
disclaimer - This is such a hack, 
copy %windir%\system32\cmd.exe  to some other location.
right click -> Properties and choose Compatibility tab.  Run it for Windows 8

Presto - console messages!

**Comment by kapilgupta77** [comment] 2017-06-30 06:57
Hi,
Am facing exactly the same issue on Windows 2k12 Server machine. It is quite frustrating.
My Electron version is 1.6.11 and chromium is 56

**Comment by MikeSoft** [comment] 2017-11-28 22:01
i have this issue too

**Comment by tkshnwesper** [comment] 2017-11-29 02:23
My workaround (not a great one) was to install a Linux distro on virtualbox and do the testing there.

**Comment by farfromrefug** [comment] 2018-01-16 14:03
Just started to face the same issue. 
@zcbenz did you make any progress on this?
This happens with all electron version at least since 1.6.0
Thanks

**Comment by lastmjs** [comment] 2018-03-05 17:22
After upgrading to 1.8.2 this seems to be broken for me as well. `--enable-logging electron ...`, `ELECTRON_ENABLE_LOGGING=true electron ...` and `app.commandLine.appendSwitch('--enable-logging');` all fail. I'm running Arch Linux.

**Comment by lastmjs** [comment] 2018-03-05 17:24
A slight correction, it seems like Chromium's logging is enabled. I'm getting the following output:

```
[18215:0305/102312.563219:VERBOSE1:CONSOLE(8160)] "Main._createAppUI: 20.992919921875ms", source: chrome-devtools://devtools/bundled/inspector.js (8160)
[18215:0305/102312.585255:VERBOSE1:CONSOLE(8165)] "Main._showAppUI: 20.720947265625ms", source: chrome-devtools://devtools/bundled/inspector.js (8165)
[18215:0305/102312.652693:VERBOSE1:CONSOLE(8166)] "Main._initializeTarget: 9.762939453125ms", source: chrome-devtools://devtools/bundled/inspector.js (8166)
```

But I'm not getting the console.log output that I used to get. So none of my app logs work.

**Comment by lastmjs** [comment] 2018-03-05 19:19
Switching to 2.0.0-beta.1 has solved the issue for me

**Comment by CapOM** [comment] 2018-03-21 22:39
var nodeConsole = require('console');
var myConsole = new nodeConsole.Console(process.stdout, process.stderr);
myConsole.log('Hello World!');

**Comment by kaizhu256** [comment] 2018-05-10 12:16
can confirm the macos v1.8.6 version @ https://github.com/electron/electron/releases/download/v1.8.6/electron-v1.8.6-darwin-x64.zip also doesn't honor --enable-logging or $ELECTRON_ENABLE_LOGGING flags inside of webviews.

v1.7.14 and v2.0.0 works fine on mac

**Comment by fcastilloec** [comment] 2018-07-11 00:06
I can confirm from `v1.8.7` to `v2.0.4`, all have this problem on windows 8.1 and windows 10. The hack from @mporter-di was the only thing that made it work.
In the meantime, I've opted for using [`electron-log`](https://www.npmjs.com/package/electron-log) module to output into a file.

**Comment by frostbitten** [comment] 2018-07-25 00:13
Another workaround I found is to use PowerShell.

Experiencing this issue with: Windows 8.1, Electron v2.0.5 (shows Chromium v61.0.3163.100, Node v8.9.3, v8 v6.1.534.41 when I run `electron` with no args)

**Comment by dbakuntsev** [comment] 2018-10-09 18:07
To offer a cleaner alternative to @mporter-di method:

If you don't want to muck about with `cmd.exe`, it will suffice to set the compatibility mode for `%AppData%\Roaming\npm\node_modules\electron\dist\electron.exe` executable instead. Or, if you are running from the local package, the compatibility mode can be set on `.\node_modules\electron\dist\electron.exe` executable.

Let's face it, after 3 years this problem is unlikely to be fixed. But, perhaps, the workaround can be documented in official documentation? One can only hope.

**Comment by sofianguy** [comment] 2019-08-09 04:07
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:05
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:05 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows, version/1.8.x
