### ISSUE TITLE
npm install electron failing

### ISSUE THREAD

**Issue by souravm84** [electron/electron#9631] opened 2017-05-31 11:24 UTC
> electron@1.6.10 postinstall G:\nodejs\electron app\sqljs\node_modules\electron
> node install.js

Downloading electron-v1.6.10-win32-x64.zip
Error: read ECONNRESET
G:\nodejs\electron app\sqljs\node_modules\electron\install.js:47
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TLSWrap.onread (net.js:568:26)
npm verb lifecycle electron@1.6.10~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle electron@1.6.10~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;G:\nodejs\electron app\sqljs\node_modules\electron\node_modules\.bin;G:\nodejs\electron app\sqljs\node_modules\.bin;C:\Users\bear\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd;C:\Users\bear\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\usr\bin;C:\Users\bear\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\usr\share\git-tfs;C:\Users\bear\AppData\Local\Apps\2.0\LQWXNEMJ.2HO\4X297WEN.TB2\gith..tion_317444273a93ac29_0003.0003_5794af8169eeff14;C:\Users\bear\AppData\Local\GitHub\lfs-amd64_1.5.5;c:\Software\octave3.6.4\bin;C:\Program Files (x86)\Qucs\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Lenovo\Bluetooth Software\;C:\Program Files\Lenovo\Bluetooth Software\syswow64;C:\Program Files\Broadcom\WHL\;C:\Program Files\Broadcom\WHL\syswow64;C:\Program Files\Broadcom\WHL\SysWow64\;C:\Program Files\Broadcom\WHL\SysWow64\syswow64;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files\Internet Explorer;C:\Program Files (x86)\Common Files\GTK\2.0\bin;C:\Program Files (x86)\Java\jdk1.8.0_111\bin;G:\AndroidSDK\tools\templates\gradle\wrapper;C:\ant\bin;C:\android-sdk-win\tools;C:\android-sdk-win\platform-tools;C:\Program Files (x86)\mingw32\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;G:\AndroidSDK\tools;G:\AndroidSDK\platform-tools;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Brackets\command;C:\Program Files\nodejs\;C:\Users\bear\AppData\Local\Microsoft\WindowsApps;G:\web\xampp\php;C:\Users\bear\AppData\Roaming\npm;C:\Program Files (x86)\MSBuild\14.0\bin\
npm verb lifecycle electron@1.6.10~postinstall: CWD: G:\nodejs\electron app\sqljs\node_modules\electron
npm info lifecycle electron@1.6.10~postinstall: Failed to exec postinstall script
npm verb unlock done using C:\Users\bear\AppData\Roaming\npm-cache\_locks\staging-0c641607ed835d70.lock for G:\nodejs\electron app\sqljs\node_modules\.staging
npm WARN sqljs@1.0.0 No repository field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm verb stack Error: electron@1.6.10 postinstall: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:886:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid electron@1.6.10
npm verb cwd G:\nodejs\electron app\sqljs
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "electron" "--verbose"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.6.10 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.10 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     G:\nodejs\electron app\sqljs\npm-debug.log

G:\nodejs\electron app\sqljs> node --version
v6.10.3

**Comment by enlight** [comment] 2017-05-31 11:41
Please check the [previously reported issues](https://github.com/electron/electron/issues?utf8=%E2%9C%93&q=is%3Aissue%20ECONNRESET%20) before opening a new one.

Closing as duplicate of #9307.

**Closed by enlight** 2017-05-31 11:41 UTC

**Comment by shanshel** [comment] 2017-07-27 06:27
I was facing the same problem. 
I can say that happened because of bad internet connection (or maybe very far from the router and ping become high) 

that's was my problem. nothing else

**Comment by michaeltamsil** [comment] 2019-11-21 04:34
when changing other internet provider, it's smooth & no ECONNRESET message error.
