### ISSUE TITLE
App minimize or not visible after click outside browserWindow or Windows key+D

### ISSUE THREAD

**Issue by vaidyaanand** [electron/electron#11232] opened 2017-11-23 14:24 UTC
I am developing a desktop widget which shows current system status. But the problem is **when any user clicks outside of browser window the app get hide/not visible on the desktop. The same thing happens when user press key windows key +D**. Is there anything that we can do for preventing this or catch this event and call window.show(). Because lots of desktop widget support this kind of feature. 

Example: If the [rainmeter](https://www.rainmeter.net) hides when you press windows key +D or click outside, the app features will get limited.

 If you provide me with any solution it will definitely be going to help me because I am continuously in search of it.

 I have also tried community help and slack but unable to get any solution.
 
* Electron version: 1.4.13, also checked in 1.8.x
* Operating system: Windows 10

### Actual behaviour

 The app is minimizing or not displaying on desktop when clicking outside the window

### How to reproduce : create a simple electron frameless app with width around 260 px and 400px height. Click outside the browserWindow or press windows key + D. the app disappears 

Git repo: I am using the same example as you have described in a [simple-sample ](https://github.com/electron/simple-samples)https://github.com/electron/simple-samples.git -> activity-monitor

**Comment by vaidyaanand** [comment] 2017-11-29 12:40
Hello Every one,
Does anyone get some clue how to make it?

**Comment by vaidyaanand** [comment] 2017-12-21 09:02
@codebytere Can you please help in resolving this. I am waiting for it.

**Comment by codebytere** [comment] 2018-01-06 16:08
does this occur on later versions of electron? 1.4 is dated enough that it's not in our best interest to work on fixes unless it's still occurring on more recent versions.

**Comment by vaidyaanand** [comment] 2018-01-08 04:46
@codebytere I will update the electron version and let you know.

**Comment by vaidyaanand** [comment] 2018-01-08 05:06
@codebytere Yes, It has occurred in version 1.8.1.

**Comment by vaidyaanand** [comment] 2018-07-03 10:55
Hi, Is there any update on this issue?

**Comment by Art4** [comment] 2019-01-07 12:34
I have the same problem if [windows]+[d] or [windows]+[m] is pressed. I'm building an app as a replacement for a Windows 7 Sidebar Gadget and want to emulate the old behavior where you could place a Gadget on the Desktop but behind other windows.

If I set `win.setAlwaysOnTop(true)` then pressing [windows]+[d] has no effect (:+1:) but the app will stay in front of other windows. (:-1:)
If I set `win.setAlwaysOnTop(false)` then pressing [windows]+[d] will minimize/hide the app (:-1:) but the app will stay behind other windows. (:+1:)

**Comment by sofianguy** [comment] 2019-01-07 22:30
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by Art4** [comment] 2019-01-10 09:42
I'm experiencing this issue with electron 3.0.13 on windows 7, 64bit.

To reproduce my issue try create a BrowserWindow that is not minimizable, always on the desktop, but behind every other window.

If I try

```js
    mainWindow = new BrowserWindow({
        resizable: false,
        frame: false,
        movable: true,
        minimizable: false,
        maximizable: false,
        alwaysOnTop: true,
        fullscreenable: false,
        skipTaskbar: true
    });
```

the window will be in front of other windows, but pressing [windows]+[d] will not minimize the window. If I change `alwaysOnTop` to `false` then it will behind other windows, but will be minimize if [windows]+[d] is pressed.

**Comment by sofianguy** [comment] 2019-08-09 23:11
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:01
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:01 UTC
Labels: 3-0-x, blocked/need-info ❌, bug :beetle:, platform/windows, version/1.8.x

**Comment by Art4** [comment] 2019-09-03 13:53
I tested this issue again with electron 4.2.10 on windows 10, 64bit. The issue is still present but my users have gotten used to it, so for me this issue is done. Thank you for your patience.

**Comment by huangcs427** [comment] 2024-10-17 07:13
@sofianguy Sorry to disturb you.

It seems that there is the same problem in electron v33.0.0. I have tried it on both Windows 10 and Windows 11.

**Minimum reproducible code**: https://gist.github.com/huangcs427/e2778885fa01f63ba8ad45ae0e73c1c3

**Comment by huangcs427** [comment] 2024-10-17 07:17
> It seems that there is the same problem in electron v33.0.0. I have tried it on both Windows 10 and Windows 11.
> 
> **Minimum reproducible code**: https://gist.github.com/huangcs427/e2778885fa01f63ba8ad45ae0e73c1c3

I want to achieve an effect similar to Rainmeter. 
Rainmeter: https://www.rainmeter.net/

What I want to achieve is that when I press Win + D, my Electron application still remains on the desktop, but it cannot block other applications.

**Comment by huangcs427** [comment] 2024-11-08 01:15
any update?

**Comment by huangcs427** [comment] 2024-11-08 01:50
Can we use the koffi library to solve this problem?

**Comment by huangcs427** [comment] 2024-11-08 01:54
@MarshallOfSound Sorry to disturb you.

It seems that there is the same problem in electron v33.0.0. I have tried it on both Windows 10 and Windows 11.

Minimum reproducible code: https://gist.github.com/huangcs427/e2778885fa01f63ba8ad45ae0e73c1c3
