### ISSUE TITLE
[Bug]: Preload-error. Preload script fail to find a module. (It happens during SSO login navigation flow)

### ISSUE THREAD

**Issue by shaluyadav13** [electron/electron#28142] opened 2021-03-11 21:29 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

The preload script should get loaded correctly all the time.

### Actual Behavior

During SSO flow in the main window preload-error occurs. Not reproducible all the time. But the number of occurrences is significant.

Below is the error happening during SSO navigation in the electron main browser window.

```
2021-02-22 10:16:05.929] [error] [main-window] preload-error preloadPath= C:\Users\rtm24\AppData\Local\Programs\appName\resources\app.asar\app\main\windows\main.preload.js error= Error: module not found: @gg/app-api-electron
    at preloadRequire (electron/js2c/sandbox_bundle.js:127:1711)
    at f (<anonymous>:2:355)
    at p (<anonymous>:2:606)
    at Object.parcelRequire.WoF5.../../services/container/app-api/app-api(<anonymous>:101:727)
    at f (<anonymous>:2:530)
    at parcelRequire.UDUI (<anonymous>:2:833)
    at <anonymous>:2:1085
    at runPreloadScript (electron/js2c/sandbox_bundle.js:127:3085)
    at Object.<anonymous> (electron/js2c/sandbox_bundle.js:127:3182)
    at Object../lib/sandboxed_renderer/init.ts (electron/js2c/sandbox_bundle.js:127:3488)
```
The BrowserWindow has the following window options set:

```
export const defaultOptions: Electron.BrowserWindowConstructorOptions = {
  minWidth: 650,
  minHeight: 660,
  width: 1000,
  height: 600,
  frame: false,
  titleBarStyle: 'hidden',
  webPreferences: {
    allowRunningInsecureContent: false,
    contextIsolation: true,
    enableRemoteModule: true,
    nativeWindowOpen: true,
    nodeIntegration: false,
    nodeIntegrationInSubFrames: false,
    nodeIntegrationInWorker: false,
    sandbox: false,
    webSecurity: true,
    webviewTag: false,
    worldSafeExecuteJavaScript: true,
  },
};
```
Even though the browser window is not sandboxed, in the error message I see "at preloadRequire (electron/js2c/sandbox_bundle.js:127:1711)" And this error can't be reproed all the time. Only happens in SSO auth flow after auth is acknowledged/approved and before url appended auth token is loaded. Any help/suggestions are really appreciated.

**Comment by nornagon** [comment] 2021-03-11 23:52
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by shaluyadav13** [comment] 2021-03-12 00:30
@nornagon I experienced the issue once and couldn't repro it now. Our Splunk logs show a lot of occurrences. And after this error happens app doesn't work even if we reload the app. To fix the issue I needed to restart the application. Even though the window is not sandboxed error shows `preloadRequire (electron/js2c/sandbox_bundle.js:127:1711)`

**Comment by nornagon** [comment] 2021-03-12 00:47
Unfortunately we can't do anything further to diagnose this issue without more information. I'm going to close this for now, but if you're able to reproduce the issue, I'd be happy to reopen.

**Closed by nornagon** 2021-03-12 00:47 UTC
Labels: blocked/need-repro

**Comment by asd281533890** [comment] 2022-09-26 12:27
I encountered the same problem, my trigger condition is that there is an iframe in the webview, the src of the iframe is the login page, then the webview redirects to the **same** login page(or redirects to the web app corresponding to the login page. Since you are not logged in, the server will redirect to the same login page as the iframe through 302), and then the webview will report the error like yours: "module not found: fs". The first line of code in the iframe's preload.js is ```const fs = require('fs')```, which looks like the iframe's preload has no node environment.

**Comment by xland** [comment] 2022-11-23 03:43
> I encountered the same problem, my trigger condition is that there is an iframe in the webview, the src of the iframe is the login page, then the webview redirects to the **same** login page(or redirects to the web app corresponding to the login page. Since you are not logged in, the server will redirect to the same login page as the iframe through 302), and then the webview will report the error like yours: "module not found: fs". The first line of code in the iframe's preload.js is `const fs = require('fs')`, which looks like the iframe's preload has no node environment.

Same Issue
