### ISSUE TITLE
svg's don't print semi-transparent shapes in Windows

### ISSUE THREAD

**Issue by Janneman84** [electron/electron#3924] opened 2015-12-26 11:53 UTC
I'm creating a graph with SVG which has white grid lines that are 50% transparent. On screen it looks fine but when I try to print it the print preview and the print itself are missing the grid lines.

This only happens in Electron in Windows, in Chrome browser it works fine. I tried some more and it turns out that any shape or text that doesn't have a 100% opacity is just not showing on prints.

To circumvent this I created a png of the grid lines and used that instead. Apparently semi transparent pngs work fine.

**Comment by zcbenz** [comment] 2015-12-28 11:31
Can you provide the SVG file?

**Comment by Janneman84** [comment] 2016-01-01 15:58
Try putting something simple like this in an html page and then try to print it through Electron in Windows:

`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="400px" height="400px">
<rect x="10" y="10" opacity="1.0" fill="#0000FF" width="300" height="300"/>
<rect x="90" y="90" opacity="0.6" fill="#ED1C24" width="300" height="300"/>
</svg>`

This draws two overlapping squares, one blue with 1.0 opacity and one red with 0.6 opacity. I noticed that red one does show up on paper but a lot smaller than it should. If you give the blue square a lower opacity it too becomes a lot smaller.

You don't have to print on paper to test this, printing to pdf or looking at the print preview works too.

**Comment by zcbenz** [comment] 2016-01-04 03:11
I can reproduce on Windows but not on OS X, it seems to be a bug of our printing code on Windows.

**Comment by davemackintosh** [comment] 2016-02-05 11:59
Any fix for this?

**Comment by cgoehl** [comment] 2017-08-11 20:58
I investigated a little bit. It works if the svg has a single group with opacity. However, it does not work when there is just one rect inside. 

[index.html](https://gist.github.com/cgoehl/a87fc66e68144a1ed0592524d0ea2574)

Expected:
![expected](https://user-images.githubusercontent.com/1002725/29231691-6e5c5ab2-7ee8-11e7-93d2-caec74ef254a.png)


Actual:
![actual](https://user-images.githubusercontent.com/1002725/29231408-5823594a-7ee7-11e7-834e-43cf8f88a5dc.png)

[nativefier.pdf](https://github.com/electron/electron/files/1219060/nativefier.pdf)

I have tested the index.html with the nativefier npm package on Windows 10 using the built-in PDF Printer.

Notice the garbage on the left corner, which seems to match the colors of the missing elements.

**Comment by codebytere** [comment] 2020-03-25 19:10
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.

**Closed by codebytere** 2020-03-25 19:10 UTC
Labels: bug :beetle:, component/printing, platform/windows
