### ISSUE TITLE
Unable to print large documents in Electron 4, 5

### ISSUE THREAD

**Issue by justin-elliott** [electron/electron#16813] opened 2019-02-07 16:50 UTC
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.4
  * 5.0.0-beta.2
* **Operating System** (Platform and Version):
  * Windows 10 Pro (1803)
* **Last known working Electron version** (if applicable):
  * 3.1.3

### Expected Behavior
When printing a large document, every page should print successfully.

### Actual behavior
When printing a large document, printing fails before completing, or produces a run of blank pages at the end. Given the number of pages involved, 800+, this has only been tested through print-to-file drivers such as Microsoft Print to PDF, and Microsoft XPS Document Writer.

This appears to be memory-related, as memory usage climbs for each additional page spooled. Prior versions of Electron did not exhibit increasing memory usage during page spooling.

### To Reproduce
This issue was first observed in a PDF.js-based viewer embedded in our application. I have created a simple application that emulates PDF.js printing behavior, here:

https://github.com/justin-elliott/electron-printing-bug

The README contains details of the testing that I have conducted.

**Comment by ablesser** [comment] 2019-02-07 18:54
I've reproduced this with a video (see here: [https://youtu.be/v3kmpai4-h8] ) showing what happens with windows memory as it creeps up to the 64 gb limit on my machine and then fails near ~2200 pages out of 2500 using the test app @justin-elliott provided.  I also show Resource monitor live monitoring during the process showing electron consuming ungodly amounts of memory (50 + GB) before everything falls over.

Note that the output PDF is 0kb / blank in this case, as the print spooling process (which seems to be running under electron's memory footprint) just seems to fall over.

I also show that windows event viewer triggers a resource exhaustion warning, which may relate to why the process ultimately terminates.  Clearly , though this is some sort of memory leak/bloat that didn't exist before.

**Comment by electron-triage** [comment] 2020-02-19 20:01
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:21
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:21 UTC
Labels: 4-2-x, 5-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
