### ISSUE TITLE
how protect ASAR file from unpackaging

### ISSUE THREAD

**Issue by kumarom1203** [electron/electron#8508] opened 2017-01-25 19:30 UTC
Hi everyone,
Is any way to protect ASAR file from unpackaging(generated by electron atom) so other can not able to modify my code.
If any one has any idea or other option to protect my code please suggest
Thanx in advance

**Comment by paul321** [comment] 2017-01-25 19:42
There should be an option to protect the asar file with a certificate

**Comment by kumarom1203** [comment] 2017-01-25 19:53
Thanx @paul321 
Can you provide any link or reference for  this certificate

**Comment by paulcbetts** [comment] 2017-01-25 20:03
This is a dupe of #4359, please subscribe there

**Closed by paulcbetts** 2017-01-25 20:03 UTC
