### ISSUE TITLE
webPreferences.preload stopped working with 1.2.0

### ISSUE THREAD

**Issue by avoidwork** [electron/electron#5827] opened 2016-06-01 16:48 UTC
* Electron version: 1.2.0
* Operating system: OSX 10.11.5

Hi,

I just moved an app from 1.1.x to 1.2.x and discovered my preload script isn't executing for the `BrowserWindow`

```javascript
'use strict';

window.$ = window.jQuery = require('jquery');
console.info("Preloaded jquery");
```

If I move back to 1.1.x, the script runs as expected.

**Comment by kevinsawicki** [comment] 2016-06-01 16:53
I think this might be a duplicate of #5719, can you try `1.2.1` and see if you still see the issue?

**Comment by avoidwork** [comment] 2016-06-01 17:35
Hi,

I just tried with 1.2.1 again, and this is the error I'm getting in the console:

<img width="1524" alt="screen shot 2016-06-01 at 1 34 40 pm" src="https://cloud.githubusercontent.com/assets/369698/15719404/c2c463c6-27fd-11e6-829a-6993695155fc.png">

**Comment by avoidwork** [comment] 2016-06-01 17:39
This is the setting used to generate the window (default security)

```
new BrowserWindow({
	frame: true,
	height: settings.size[1],
	width: settings.size[0],
	minWidth: 480 + (!osx ? 20 : 0), // scroll bar + theme
	minHeight: 580 + (!osx ? 40 : 0), // menu + theme
	resizable: true,
	show: !hidden,
	title: 'Adobe Hub',
	webPreferences: {
		preload: preload
	}
});
```

`preload` is set via `path.join(__dirname, 'app', 'assets', 'js', 'preload.js')` and hasn't changed between the builds.

**Comment by kevinsawicki** [comment] 2016-06-01 18:06
> I just tried with 1.2.1 again, and this is the error I'm getting in the console:

Electron 1.1 was Chrome 50 and Electron 1.2 is Chrome 51, could that error be related at all to the differences?

It seems to be coming from `jquery.js`, can you provide the line of code there where `createElement` is undefined?

**Comment by kevinsawicki** [comment] 2016-06-01 18:07
That error appears related to this https://github.com/electron/electron/issues/4633#issuecomment-192603286 actually

**Comment by avoidwork** [comment] 2016-06-01 19:23
Hmm, that's interesting. I had to move to a preload script to deal with an Okta authentication problem; I'll have to revisit that problem/solution to address this one.

**Comment by kevinsawicki** [comment] 2016-06-01 19:55
Closing this out, thanks for the updates.

**Closed by kevinsawicki** 2016-06-01 19:55 UTC

**Comment by avoidwork** [comment] 2016-06-03 13:29
Just wanted to mention the issue is solved by waiting for `DOMContentLoaded` event (mentioned in linked bug), e.g.

```javascript
'use strict';

document.addEventListener( "DOMContentLoaded" , function () {
	window.$ = window.jQuery = require('jquery');
	console.info("Preloaded jquery");
}, false);
```

**Comment by danielpascal** [comment] 2016-06-18 16:42
DOMContentLoaded didn't work for me, I used DOMNodeInserted instead.

**Comment by avoidwork** [comment] 2016-06-22 21:41
That would reinsert jquery as the DOM mutates, which is highly implied using jquery :)
