### ISSUE TITLE
Problem printing PDF files with electron 9.0.0

### ISSUE THREAD

**Issue by rjlfurtado** [electron/electron#25010] opened 2020-08-18 02:32 UTC
The problem occurs when pressing the button to print from the browser.
The electron simply locks or ignores the pressure command.
which load is any page like electron.com it prints normal.
but when loading a pdf file and ordering the print it doesn't work.
does this have any solution today?
```
const win2 = new BrowserWindow({
      webPreferences: {
        plugins: true
      }
    })

    win2.loadURL(__dirname + '/file.pdf', {})
    win2.webContents.once('did-finish-load', async function() {
      try {
        const pdfData = await win2.webContents.printToPDF({})
        const outPath = __dirname +'/snotas.pdf'
        fs.writeFile(outPath, pdfData, (error) => {
          if (error) throw error
          console.log(`Wrote PDF to: ${outPath}`)
        })
      } catch(e) {
        console.error(e)
      }

    })
  })
```
The code above is only a third of the many I have tried.

**Comment by zcbenz** [comment] 2020-08-19 07:30
This is duplicate of https://github.com/electron/electron/issues/24458.

**Closed by zcbenz** 2020-08-19 07:30 UTC
Labels: bug :beetle:, component/printing
