### ISSUE TITLE
Tray icon disappear from Topbar when system goes in stand by

### ISSUE THREAD

**Issue by p-fusi** [electron/electron#22443] opened 2020-02-28 16:44 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
8.0.0
* **Operating System:**
Ubuntu 18.04.4 LTS x64
* **Last Known Working Electron version:**
7.1.13

### Expected Behavior
When the system goes in stand by the Tray icon should stay visible in the Topbar

### Actual Behavior
When system goes stand by the Tray icon disappear

### To Reproduce
I set the icon and the Menu in main process:

```
let tray;
const icon = path.join(__dirname, "./icon.png");
const tryMenu = Menu.buildFromTemplate([
  { label: "Reload", role: "reload" },
  { label: "Toggle dev tools", role: "toggleDevTools" }
]);
tray = new Tray(icon);
tray.setContextMenu(tryMenu);
```
When starting electron everything works fine: the icon (and the menu) is visible in the Topbar.  
But if system goes stand by, when I log in again the icon is disappeared.

```sh
$ git clone https://github.com/p-fusi/electron-quick-start -b master
$ npm install
$ npm start || electron .
```

**Comment by beltrame** [comment] 2020-03-25 12:46
This happens with all electron applications, I can confirm with Ubuntu 19.10

**Comment by jhasse** [comment] 2020-04-02 15:57
This is a Chromium bug, see https://bugs.chromium.org/p/chromium/issues/detail?id=1042098

**Comment by felixrieseberg** [comment] 2020-04-21 00:30
Interesting tidbit from @sbuschjaeger: 

> By random chance, I noticed a [similar](https://github.com/jiahaog/nativefier/issues/945) bugreport which mentions a [fix](https://github.com/telegramdesktop/tdesktop/issues/7541) for the telegram desktop app. There seems to be a problem with the icon counter, but the telegram app does not use electron. However, maybe it helps.

**Comment by vladimiry** [comment] 2020-04-27 15:56
The above-referenced issue says it's Gnome related but I face the issue of getting disappeared icon after the suspend mode using Xfce Desktop Environment, happens quite rarely though.

**Comment by MatMaul** [comment] 2020-05-08 12:17
After reading various bugs, here is my understanding of the problem of the disappearing icon on lock/unlock.

From what I get, Chromium doesn't re-register the tray after the StatusNotifierWatcher disappears/reappears from the d-bus session on lock/unlock, while it probably should. From what I quickly read the spec doesn't really seem to deal with that, it just says only one StatusNotifierWatcher instance is allowed at any time.

https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/126cb934c59562e55e6454dece9056e15b8e2221/statusNotifierWatcher.js#L126
There is a workaround here using introspection, which seems to be what the chromium team is complaining (https://bugs.chromium.org/p/chromium/issues/detail?id=1042098), but I am not sure they understood that they are complaining about a workaround that should not be needed if they correctly watch for StatusNotifierWatcher changes.
I am interested in your opinion on my interpretation here, before I bump the chromium bug with a link to this post :) 

From my point of view, the best upstream fix Gnome-side would be that the StatusNotifierWatcher is not handle by the gnome-shell plugin, but by some other process, so it doesn't depend on Gnome plugins lifecycle. Then the gnome plugin can register itself as a StatusNotifierHost.

Thought on using something similar to https://github.com/zulip/zulip-desktop/pull/922/files in the meantime ?

**Comment by Thatoo** [comment] 2020-05-16 22:07
Same on Debian Buster (10)

**Comment by vladimiry** [comment] 2020-05-26 17:24
It turned out Electron is getting rid of DBus related tray icon implementation rolled out with @chromium update in Electron v8 in favor of previously used / `GTK/appindicator` approach, see electron/electron#23674.

**Comment by codebytere** [comment] 2020-06-04 21:00
Closed by https://github.com/electron/electron/pull/23674

**Closed by codebytere** 2020-06-04 21:00 UTC
Labels: 8-x-y, bug :beetle:, platform/linux
