### ISSUE TITLE
Electron 1.8.7 rejected by the app store due to usage of private API

### ISSUE THREAD

**Issue by gerges** [electron/electron#13957] opened 2018-08-06 16:21 UTC
* Electron Version: 1.8.7
* Operating System (Platform and Version): MacOS
* Last known working Electron version: 1.8.6

**Expected Behavior**
Electron.framework doesn't include the use of private APIs and can be approved on the Apple App Store

**Actual behavior**
Electron.framework includes the use of private APIs and cannot be approved on the Apple App Store

**Additional Information**

```
Guideline 2.5.1 - Performance - Software Requirements


Your app uses or references the following non-public APIs:

-Symbol: _CGDisplayUsesForceToGray
From framework: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics

-Symbol: __CFIsObjC
From framework: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
In binary: Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework

The use of non-public APIs is not permitted on the App Store, because it can lead to a poor user experience should these APIs change.
```

**Comment by nornagon** [comment] 2018-08-06 19:13
Duplicate of #13938

**Closed by nornagon** 2018-08-06 19:13 UTC
