### ISSUE TITLE
Facebook login/share window can not be closed when nodeIntegration = false

### ISSUE THREAD

**Issue by salomvary** [electron/electron#7424] opened 2016-09-30 13:31 UTC
* Electron version: v1.4.2
* Operating system: masOS 10.11.6 (El Capitan)

When an window that has `nodeIntegration: false` tries to open a Facebook login or share window, the window can not be closed. Neither with operating-system provided closing methods (close button, cmd+w) nor from the window itself (`window.close()`) is the window closeable. The Facebook window can also not be reloaded (cmd+r or `window.location.reload()` do nothing). There are no errors logged (neither windows nor to the main process).

Steps to reproduce:
- Given the example app below, start it with `electron .`
- Click on "Facebook"
- The first time Facebook will prompt for login
- Log in to Facebook
- Try closing the Facebook popup window (might need to restart the application before this to see the bug happening)

Example app:
index.html:
```html
<a href="https://www.facebook.com/sharer/sharer.php?u=http://electron.atom.io/" target="_blank">Facebook</a>
<a href="about:blank" target="_blank">Blank</a>
```
main.js:
```js
'use strict'

const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow

var mainWindow = null

app.on('ready', function() {
  mainWindow = new BrowserWindow({
    width: 1290,
    height: 800,
    webPreferences: {
      nodeIntegration: false
    }
  })

  mainWindow.loadURL(`file://${__dirname}/index.html`)
})
```

package.json
```json
{
  "name": "no-facebook",
  "private": true,
  "version": "1.0.0",
  "main": "main.js"
}
```

**Comment by kevinsawicki** [comment] 2016-09-30 17:23
@salomvary do you know if this worked in previous Electron releases?

**Comment by salomvary** [comment] 2016-09-30 18:48
Don't really know, I'm new to Electron.

**Comment by sukhmeet2390** [comment] 2016-09-30 20:45
Facing a similar issue. 
On pressing Quit (Cmd+Q) in the lifecycle method i get till  'will-quit' , but not after that. 
on clicking the window close or calling window.close() doesn't close the BrowserWindow.
BrowserWindow.getAllWindows(), still has that window object.

PS : I am overriding 'require' to 'electronRequire' and using that to get specific modules as I am using requirejs inside my code , and my 'require' points to requirejs 'require' .

**Comment by salomvary** [comment] 2016-10-01 09:33
OK, I traced it down. The problem lies in Facebook using `window.unbeforeunload` to prevent and confirm closing the window with unsaved/unsent input.

`window.unbeforeunload` [is overridden by Electron](http://electron.atom.io/docs/api/browser-window/#event-close) to silently prevent closing the window on any non-`undefined` return value from the event handler.

The above behavior is reasonable in case `nodeIntegration = true` however when it's off, I'd expect this to behave more like on web browsers, where a confirmation dialog is shown.

I dumped the un-minified Facebook dialog and my test app [into this repo](https://github.com/salomvary/tmp-fb-on-electron) for further investigation. It also contains a [trivial test page](https://github.com/salomvary/tmp-fb-on-electron/blob/master/test.html) to showcase the behavior.

Thinking of workarounds, one possible solution would be hijacking `window.addEventListener('beforeunload')` and the `window.onbeforeunload` setter and wrapping whatever is added there with an Electron dialog implementation in a `preload` script added to all `BrowserWindows` opened.

**Comment by salomvary** [comment] 2016-10-01 10:09
Btw web-standard `window.onbeforeunload` implementation on "mainWindow" is the perfect way of creating an app that is impossible to close without force quitting or using `kill -9` on Mac ;)

**Comment by kevinsawicki** [comment] 2016-10-03 22:06
> The problem lies in Facebook using window.unbeforeunload to prevent and confirm closing the window with unsaved/unsent input.

I believe this is a duplicate of https://github.com/electron/electron/issues/2579, please subscribe to that issue for updates.

> Thinking of workarounds, one possible solution would be hijacking

Using a `preload` script seems like the right workaround for now 👍

**Closed by kevinsawicki** 2016-10-03 22:06 UTC

**Comment by synergyseeker** [comment] 2017-04-13 14:47
did anyone ever get this working? I am able to get the FB login / share dialogue to open and share properly on FB. But you can't close or cancel the share window, unless you complete the Share process ( post to FB ) or use the "swtich user" function in the upper right

**Comment by vharshit1** [comment] 2019-03-12 22:41
I am having same issue now any work arounds?
