### ISSUE TITLE
crashReporter isn't working

### ISSUE THREAD

**Issue by TanninOne** [electron/electron#11626] opened 2018-01-12 11:18 UTC
* Electron version: 1.7.9
* Operating system: Windows 10 (64-bit)

### Expected behavior

crash reports when the process crashes.

### Actual behavior

The crashReporter doesn't seem to be doing anything apart from writing to operation_log.txt
operation_log.txt looks like this:

```
[7924:12544:0112/120638.289:VERBOSE1:crash_service_main.cc(78)] Session start. cmdline is [--reporter-url=http://localhost:1127 --application-name=Vortex "--crashes-directory=C:\Users\Tannin\AppData\Roaming\vortex\temp\Vortex Crashes" --v=1]
[7924:12544:0112/120638.295:VERBOSE1:crash_service.cc(142)] window handle is 00000000001E215E
[7924:12544:0112/120638.295:VERBOSE1:crash_service.cc(284)] pipe name is \\.\pipe\Vortex Crash Service
dumps at C:\Users\Tannin\AppData\Roaming\vortex\temp\Vortex Crashes
[7924:12544:0112/120638.295:VERBOSE1:crash_service.cc(288)] checkpoint is C:\Users\Tannin\AppData\Roaming\vortex\temp\Vortex Crashes\crash_checkpoint.txt
server is http://localhost:1127
maximum 128 reports/day
reporter is electron-crash-service
[7924:12544:0112/120638.295:ERROR:crash_service.cc(295)] could not start dumper
```

So I guess the problem is "dumper" can't be started but why that is the log doesn't say.

**Comment by sachetsharma1** [comment] 2018-04-04 12:10
This is not working on Mac either. I am setting a custom directory for temp using 

app.setPath('temp', join(app.getAppPath(), 'temp'))

I also have a crash reporter setup in my renderer process:

  crashReporter.start({
    productName: 'abc',
    companyName: 'company.abc',
    submitURL: 'http://localhost:3001/api/app-crashes',
    uploadToServer: true,
 });

but nothing is written on disk and I don't see the submitURL being called.

**Comment by computerquip-streamlabs** [comment] 2018-07-20 22:46
This isn't specific to 1.7.x. I just ran into this on 2.0.x as well. Quite a shame given I can't tell how many reports I've missed up to this point because of this.

**Comment by alxmiron** [comment] 2018-08-15 13:10
I also suffer from it. electron: 2.0.7

**Comment by mako-taco** [comment] 2019-03-11 22:48
Similar issue on 3.0.14

`crashReporter` successfully posts to the provided endpoint, but there is no request body, so nothing is uploaded.

**Comment by sofianguy** [comment] 2019-08-09 03:33
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:10
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:10 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows, version/1.7.x
