### ISSUE TITLE
[Bug] 3.0.0-beta1 CSS3 `-webkit-app-region: drag` not working

### ISSUE THREAD

**Issue by JieJiSS** [electron/electron#13358] opened 2018-06-21 07:22 UTC
* Electron Version: 3.0.0-beta1
* Operating System (Platform and Version): macOS
* Last known working Electron version: 2.0.2

**Expected Behavior**
```css
html, body, * {
    -webkit-app-region: drag;
    -webkit-user-select: none;
    cursor: default;
}
```
should allow users to move the position of the window by dragging it directly.

**Actual behavior**
The window is not draggable.
The `cursor` and `-webkit-user-select` properties work well.

**To Reproduce**
copy the CSS above, paste it into a frameless app's `<style>` tag, and run the app.

**Screenshots**

**Additional Information**

**Comment by gnattu** [comment] 2018-06-21 07:27
I could reproduce this on macOS as well.
I also found that the window seems to be drag-able when it is not focused: drag the top of the window when it is not focused can move it around.

**Comment by setpixel** [comment] 2018-06-22 20:04
This should probably also be marked as a regression

**Comment by MarshallOfSound** [comment] 2018-07-09 03:52
This is a strange one, did some investigation and it looks like our view heirachy changed from 2.0.x to 3.0.x.

##### 2.0.x
```
[   A      WLU ] h=--- v=--- BRYInspectableWebContentsView 0x11899d170 f=(0,0,0,0) b=(-) => <_NSViewBackingLayer: 0x118c5a5a0>
  [   A    v  LU ] h=-&- v=-&- WebContentsViewCocoa 0x11899b360 f=(0,0,0,0) b=(-)
A=autoresizesSubviews, C=canDrawConcurrently, D=needsDisplay, F=flipped, G=gstate, H=hidden (h=by ancestor), L=needsLayout (l=child needsLayout), U=needsUpdateConstraints (u=child needsUpdateConstraints), O=opaque, P=preservesContentDuringLiveResize, S=scaled/rotated, W=wantsLayer (w=ancestor wantsLayer), V=needsVibrancy (v=allowsVibrancy), #=has surface
```

##### 3.0.x
```
[   A      w  #] h=--- v=--- NSThemeFrame 0x11c9c3e30 "Electron" f=(0,0,900,600) b=(-) => <_NSViewBackingLayer: 0x11cb806a0>
  [   A  O   W   ] h=--- v=--- BridgedContentView 0x11ca45bf0 f=(0,0,900,600) b=(-) => <CALayer: 0x11cf74690>
    [   A      W   ] h=-&- v=-&- ViewsCompositorSuperview 0x11cb55280 f=(0,0,900,600) b=(-) => <CALayer: 0x11cb551d0>
    [   A      W   ] h=--- v=--- BRYInspectableWebContentsView 0x11c9f6360 f=(0,0,900,600) b=(-) => <_NSViewBackingLayer: 0x11c9f70d0>
      [   A    v w   ] h=-&- v=-&- WebContentsViewCocoa 0x11cf87070 f=(0,0,900,600) b=(-) => <_NSViewBackingLayer: 0x11cb7fdc0>
        [   A      W   ] h=-&- v=-&- RenderWidgetHostViewCocoa 0x11cb75ad0 f=(0,0,900,600) b=(-) => <CALayer: 0x125e15d10>
  [   A      W   ] h=-&- v=--- NSTitlebarContainerView 0x11c9c5590 f=(0,578,900,22) b=(-) => <_NSViewBackingLayer: 0x11c9c5320>
    [   A      W   ] h=-&- v=-&- NSTitlebarView 0x11c96f520 f=(0,0,900,22) b=(-) => <_NSViewBackingLayer: 0x11c92b9a0>
      [  HAF     w   ] h=--- v=--- _NSThemeCloseWidget 0x11c9cf470 "Button" f=(7,3,14,16) b=(-) => <_NSViewBackingLayer: 0x11cb80350>
      [  HAF     w   ] h=--- v=--- _NSThemeZoomWidget 0x11cf68940 "Button" f=(47,3,14,16) b=(-) => <_NSViewBackingLayer: 0x11cb80400>
      [  HAF     w   ] h=--- v=--- _NSThemeWidget 0x11cf68a10 "Button" f=(27,3,14,16) b=(-) => <_NSViewBackingLayer: 0x11cb804a0>
      [  HAF   V W   ] h=--- v=&-- NSTextField 0x11ca10930 "Electron" f=(423,3,54,17) b=(-) => <NSTextLayer: 0x11ca42d50>
A=autoresizesSubviews, C=canDrawConcurrently, D=needsDisplay, F=flipped, G=gstate, H=hidden (h=by ancestor), L=needsLayout (l=child needsLayout), U=needsUpdateConstraints (u=child needsUpdateConstraints), O=opaque, P=preservesContentDuringLiveResize, S=scaled/rotated, W=wantsLayer (w=ancestor wantsLayer), V=needsVibrancy (v=allowsVibrancy), #=has surface
```

I don't know where `BridgedContentView` and `NSTitlebarContainerView` are coming from 🤔

**Comment by MarshallOfSound** [comment] 2018-07-09 06:07
I spent a few hours running a `git bisect`, this exact commit is the first broken one.

https://github.com/electron/electron/commit/28fc58067bc05f679cd00d2710ea1e825e6b1a0c

**Closed** 2018-07-10 01:43 UTC
Labels: bug :beetle:, bug/regression :leftwards_arrow_with_hook:, version/3.0.x
