### ISSUE TITLE
webview dialog event

### ISSUE THREAD

**Issue by felicienfrancois** [electron/electron#1374] opened 2015-04-07 15:23 UTC
It could be useful to be able to intercept dialog events from webview (alert, confirm, prompt) to be able to implement our own gui.

Also it is part of chrome webview events
https://developer.chrome.com/apps/tags/webview#event-dialog

**Comment by felicienfrancois** [comment] 2015-04-24 09:23
I have just seen that native prompt is not supported in electron.
It renforces the need for a dialog event in order to be able to handle prompts

**Comment by KevinMartin** [comment] 2015-07-21 18:23
+1

**Comment by armoret** [comment] 2015-07-23 12:14
+1
And I would also have the possibility to intercept the other kind of dialogs (print, save as, select file) as they can be triggered by javascript in the webview object.

**Comment by alexindigo** [comment] 2015-07-23 15:42
+1 and +1 for other dialogs.

**Comment by superbrothers** [comment] 2015-09-06 08:29
+1

**Comment by etiktin** [comment] 2015-09-06 20:15
If your looking for a temporary solution until the event is added, I think you can implement it yourself in a `preload` script. Electron implements the default dialogs in  [override.coffee](https://github.com/atom/electron/blob/50bfe9e335279491706c5c4ab13e53bc9c0bcdae/atom/renderer/lib/override.coffee#L77-L95), so you can use that as a starting point and change the `dialog.showMessageBox` options to your liking.

**Comment by arnolem** [comment] 2015-11-11 20:26
+1

**Comment by kaepora** [comment] 2015-12-02 16:36
+1

**Comment by Klestofer** [comment] 2016-03-22 15:38
It would be very cool to have such possibility. For example, I automate some site in `<webview>` and it calls window.confirm(). I need to press OK somehow! Now I call this in injected script to confirm:
```
      window.confirm = function (msg) {
        console.log('always agree:', msg);
        return true;
      };

```
But having more general handler for all dialog windows would be more powerful

**Comment by rickmed** [comment] 2016-05-10 01:02
+1

**Comment by AdrianoPatrizio** [comment] 2017-03-10 16:23
+1

It could be useful too intercept file picker, print dialog and color chooser.

**Comment by alexk111** [comment] 2017-03-27 09:01
+1. Google Tasks uses windows.prompt, which doesn't work when called from Webview.

**Comment by arnolem** [comment] 2017-04-07 13:31
@alexk111 if you want a Google Tasks Desktop build with electron 
https://github.com/wixiweb/googletasks-desktop/releases

**Comment by mikesteele** [comment] 2017-06-05 17:38
+1

**Comment by elite28** [comment] 2017-07-03 03:55
+1

**Comment by dosyago-coder-0** [comment] 2017-08-03 08:47
Couldn't you just custom hook the `ELECTRON_BROWSER_WINDOW_{type}` events on `ipcRenderer`, since webviews will already preload with a script that overwrites alert/confirm/prompt with a method sends a `ipcRenderer.sendSync`?

**Comment by updatesvc** [comment] 2017-12-02 18:20
+1

**Comment by 4eveRS** [comment] 2018-03-26 21:41
+1

**Comment by DarlanBellinati** [comment] 2018-03-29 17:29
+1

**Comment by dosyago-coder-0** [comment] 2018-06-11 09:14
One way to do this is to use the modal dialogue events api by connecting chrome remote debugging protocol to the webview.

**Comment by Veiintc** [comment] 2018-09-18 15:40
Any Update on this?

**Comment by ZsgsDesign** [comment] 2019-01-09 04:03
Any Update on this?

**Comment by xudafeng** [comment] 2019-03-06 12:55
Any Update?

**Comment by honzapatCZ** [comment] 2019-08-27 21:52
It could probably be done with preload script and overriding functions and for files making on click return false and trigerring own code though native implementation would be useful

**Comment by Mrhoho** [comment] 2020-10-16 14:02
Any Update on this?

**Comment by theArina** [comment] 2020-12-03 13:10
Well. +1

**Comment by RHeynsZa** [comment] 2020-12-04 08:10
Nice seeing you again @theArina. +1 for this as well.

**Comment by miniak** [comment] 2021-11-06 05:51
Duplicate of #26160

**Closed by miniak** 2021-11-06 05:51 UTC
Labels: enhancement :sparkles:, component/webview, component/dialog
