### ISSUE TITLE
[Bug]: The memory usage is too high when the gpu is turned on

### ISSUE THREAD

**Issue by 1056824847** [electron/electron#28633] opened 2021-04-13 10:29 UTC
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.2.1

### What operating system are you using?

Windows

### Operating System Version

window10 

### What arch are you using?

x64

### Expected Behavior

When I use the app.disableHardwareAcceleration() command, the electron occupies 100m+ of memory, but when I turn on the gpu, the software is 100m when the software is opened, but the memory usage will become higher and higher when switching pages, probably to 500m 600m, and later I found that the GPU process has been increasing. How can I keep the GPU from occupying so much memory without turning off the GPU?

### Actual Behavior

When I use the app.disableHardwareAcceleration() command, the electron occupies 100m+ of memory, but when I turn on the gpu, the software is 100m when the software is opened, but the memory usage will become higher and higher when switching pages, probably to 500m 600m, and later I found that the GPU process has been increasing. How can I keep the GPU from occupying so much memory without turning off the GPU?

**Comment by Kilian** [comment] 2021-04-14 10:18
Electron 9.x is no longer supported so I'm closing out this issue. Please note that "Electron uses a lot of memory" is not a bug. 

If this is still a problem in Electron 12 feel free to provide a testcase and re-open the ticket.

**Closed by Kilian** 2021-04-14 10:18 UTC
Labels: bug :beetle:
