### ISSUE TITLE
[Bug]: desktopCapturer output is blank when capturing own window.

### ISSUE THREAD

**Issue by praneetrohida** [electron/electron#30208] opened 2021-07-20 10:05 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

macOS

### Operating System Version

macOS 11.4

### What arch are you using?

x64

### Last Known Working Electron version

12.x

### Expected Behavior

desktopCapturer should be able to capture the output of the current window.

### Actual Behavior

The output is a blank stream of black frames.

### Testcase Gist URL

https://gist.github.com/e40b251b8ec56191ca9df9f568139304

### Additional Information

This happens only for the current window. If you change the name of the target window to the name of any other window open on your machine, it shows the stream correctly. 
This works correctly is 11.x/12.x so it seems to be broken only in 13.x versions. My actual use case is not to show the output of the stream in the UI, but to record it and output a video file.
#29931 is similar to this but a different issue since it is concerned with the source not being available and it affects both 12 and 13, but in this case, the source is always available but does not output anything.

**Comment by VerteDinde** [comment] 2021-07-20 22:22
May be a dupe of https://github.com/electron/electron/issues/29931, (that issue was Windows-only). Can confirm this is breaking in [13.0.0-beta.4](https://www.electronjs.org/releases/beta?version=13&page=5#13.0.0-beta.4) with a hard crash when you try to start the stream.

**Comment by phanmn** [comment] 2021-07-21 06:03
You can try this https://github.com/electron/electron/issues/29458

**Comment by praneetrohida** [comment] 2021-07-21 06:09
This worked for now! Thanks @phanmn and @nornagon, you saved my release! 🙌

**Comment by nornagon** [comment] 2021-07-26 23:53
Duplicate of #29458

**Closed by nornagon** 2021-07-26 23:53 UTC
Labels: 13-x-y, 14-x-y, bug :beetle:, has-repro-gist, platform/all, status/confirmed
