### ISSUE TITLE
Window height is not calculated correctly when menu is set to null

### ISSUE THREAD

**Issue by Kangaroux** [electron/electron#8789] opened 2017-02-27 20:45 UTC
Windows 10
Electron version: 1.4.15
Node version: 6.9.5

## The problem
Removing a window's menu when `useContentSize == true` leaves whitespace at the bottom of the window, equal to the menu's height (window does not shrink vertically to remove menu height)

## How to reproduce
Create a window with `useContentSize: true` and then call `win.setMenu(null)` (before loading your HTML page). Note the excess whitespace at the bottom of the window.

The height of the (now non-existent) menu is taken into account and added to the window height. This leads to an extra ~20px of whitespace at the bottom of the window.

Using `autoHideMenuBar: true` produces the correct result (no whitespace). However, this does not disable the alt key functionality to make the menu reappear.

## (update) Workaround

Set `autoHideMenuBar: true` to remove the whitespace and `win.setMenu(null)` to disable alt key functionality

**Comment by Kangaroux** [comment] 2017-02-27 21:56
Added a workaround

**Comment by groundwater** [comment] 2017-02-28 00:13
Hi @Kangaroux what OS and version are you running?

**Comment by Kangaroux** [comment] 2017-02-28 03:40
@groundwater Windows 10, updated OP with versions

**Comment by alespergl** [comment] 2017-03-06 14:07
Hey @Kangaroux, I can't seem to be able to reproduce your problem. I tried the steps you describe with the [electron-quick-start](https://github.com/electron/electron-quick-start) sample (even with the exact reported version of Electron), but as far as I can tell, the window looks normal and no additional white space is added. Can you please provide a minimal working example demonstrating the issue?
Thanks

**Comment by Kagami** [comment] 2017-03-08 17:43
Getting exact same issue on Windows 7. `autoHideMenuBar: true` fix works. Also I guess it doesn't affect packaged apps, because I can't reproduce bug in production build of another application.

@alespergl try with following changes:

```patch
diff --git a/index.html b/index.html
index d9161f3..f8fd676 100644
--- a/index.html
+++ b/index.html
@@ -1,15 +1,16 @@
 <!DOCTYPE html>
-<html>
+<html style="height:100%">
   <head>
     <meta charset="UTF-8">
     <title>Hello World!</title>
   </head>
-  <body>
+  <body style="height:100%">
     <h1>Hello World!</h1>
     <!-- All of the Node.js APIs are available in this renderer process. -->
     We are using Node.js <script>document.write(process.versions.node)</script>,
     Chromium <script>document.write(process.versions.chrome)</script>,
     and Electron <script>document.write(process.versions.electron)</script>.
+    <br><br><script>document.write(document.body.clientHeight)</script>
   </body>
 
   <script>
diff --git a/main.js b/main.js
index 623740a..02be313 100644
--- a/main.js
+++ b/main.js
@@ -13,7 +13,8 @@ let mainWindow
 
 function createWindow () {
   // Create the browser window.
-  mainWindow = new BrowserWindow({width: 800, height: 600})
+  mainWindow = new BrowserWindow({width: 800, height: 600, useContentSize: true})
+  mainWindow.setMenu(null)
 
   // and load the index.html of the app.
   mainWindow.loadURL(url.format({
@@ -23,7 +24,6 @@ function createWindow () {
   }))
 
   // Open the DevTools.
-  mainWindow.webContents.openDevTools()
 
   // Emitted when the window is closed.
   mainWindow.on('closed', function () {
```

You should see `620`. Then add `autoHideMenuBar: true` option and run again, you should get expected `600`.

**Comment by dragonjet** [comment] 2017-07-09 07:15
I can reproduce this problem, but I think we should have a formal fix rather than the workaround. I will use for around for now though.

For more info just in case:

window initialization
```
mainWindow = new BrowserWindow({
	width: 400,
	height: 400,
	show: false,
	resizable: false,
	useContentSize: true
})
mainWindow.setMenu(null)
```
css
```
body {
  margin:0px;
  padding:0px;
  overflow:hidden;
}
#divid {
  width:400px;
  height:400px;
  float:left;
  background:#faa;
}
```
output
![image](https://user-images.githubusercontent.com/557312/27991946-526dbf6a-64b9-11e7-8956-28abc80f0adb.png)

a 400x400 window with `useContentSize: true`, then a css box of 400x400, and there's still space at the bottom of the window.

**Comment by sofianguy** [comment] 2018-02-02 00:27
Thanks for contributing!

We are no longer releasing bug fixes for versions of Electron older than 1.6x. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.

**Comment by neminovno** [comment] 2018-05-08 20:09
This issue exists in 2.0.0. No fix yet?

**Comment by punteek** [comment] 2018-12-21 03:09
Is this issue still open to work on? Looking to start contributing!

**Comment by sofianguy** [comment] 2019-01-02 02:46
@punteek Feel free! 👍

**Comment by sofianguy** [comment] 2019-08-09 04:04
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:04
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:04 UTC
Labels: 2-0-x, blocked/need-info ❌, component/menu, good first issue, platform/windows

**Comment by neilujnihprad** [comment] 2021-08-01 08:31
Hello, 

I know this post is old, but I want to add my contribution. For me, it was an error in my CSS file. The height and the width of the HTML element were at 100%...... By removing these lines, the whitespace disappears.
