### ISSUE TITLE
Tmp files should be cleaned 

### ISSUE THREAD

**Issue by cberescu** [electron/electron#10139] opened 2017-07-27 17:31 UTC
* Electron version: 1.6.11
* Operating system: win 10

### Expected behavior
After Electron closes the addon tmp files created should be deleted.

### Actual behavior
The created .node tmp files are not deleted from the tmp directory. If it is an app that is started many times a day it will increase the size of the temp directory considerably.

### How to reproduce

Any app that imports a native addon (.node) and is packed in an asar file.

**Comment by allenbriggs** [comment] 2017-11-09 23:01
I'm experiencing the exact same issue.  Has anyone came up with a workaround?

**Comment by allenbriggs** [comment] 2017-11-28 19:34
As a workaround, is it possible to obtain the full path of the native addon .tmp.node file for manual deletion?  I understand the file is stored in the `Users\[username]\AppData\Local\Temp`, but the random name to the tmp files leaves them undistinguished.

**Comment by allenbriggs** [comment] 2017-12-05 16:26
I have confirmed that this is also a mac problem, at least on `macOS 10.13.1`.  You must get the temp directory string via `getPath` from the addon responsible for the temp files.  I simply output the string to a log file.  As an example, mine was: `HD/private/var/folders/gb/1r067cl506sfrgt4n9sh01v80000gn/T`.

On both Windows 10 and macOS 10.13.1, these files can accumulate quickly on every app launch.

**Comment by sdkester** [comment] 2018-07-12 19:24
When you spawn a child process from a file within an asar container, Windows copies it to a temp folder to be executed because it can't run it from within the container. 

In our case, the electron-builder _smartUnpack_ function was detecting things like the _ssh2_ module and correctly putting it in `/resources/app.asar.unpacked/`, but not _sqlite3_. On each run, the executable file was copied out of the asar and put into `%appdata%/Local/Temp` as `<guid>.tmp.node`. 

I suspect that it was undetected because the file extension was `.node`, not a more common executable like `.exe` or `.dll`. 

In our case, adding `"asarUnpack": "**\\*.node",` to the electron-builder configuration adds the sqlite3 module to the unpacked folder and the temp file is no longer created on each run.

**Comment by codebytere** [comment] 2018-09-24 05:09
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 05:09 UTC
Labels: enhancement :sparkles:, platform/windows, version/1.6.x

**Comment by alokchauhan13** [comment] 2018-12-30 03:48
Same issue I can see with Electron 3 and 4 as well.

**Comment by papuruth** [comment] 2020-02-05 06:25
Same issue here my .node file depends on custom dlls and it doesn't work because electron only copies the .node file to temp dir but leaving the dlls. Please help.

**Comment by ewu02** [comment] 2020-05-04 20:00
same issue in electron 8

**Comment by ndtreviv** [comment] 2020-11-26 09:47
> In our case, adding "asarUnpack": "**\\*.node", to the electron-builder configuration adds the sqlite3 module to the unpacked folder and the temp file is no longer created on each run.

I'm using `asarUnpack` in my electron-builder config:

```
  "build": {
    "asarUnpack": [
      "**/node_modules/dist-exiftool/**/*",
      "**/node_modules/myexe.exe/**/*",
    ],
```

 In my case the exe is being unpacked into `C:\Program Files\My Application\resources\app.asar.unpacked\node_modules\myexe.exe\vendor\myexe.exe` but `child-process.spawn` results in it attempting to run the exe from a random temp directory created in `%APPDATA%`. (Not ideal, as my users have blockers that stop executables running from anywhere in `%APPDATA%`.)

I even have a log message before the `spawn` indicating that the targeted exe path is the one in the unpacked directory.

**Comment by xoxloviwan** [comment] 2023-11-28 20:11
I believe this problem still needs a precise solution

And I don't understand why this issue was closed. All used in asar files unpacked and stored as before in `Users\[username]\AppData\Local\Temp`. Who must clean that after usage?
