### ISSUE TITLE
Listening for pressed ALT key while displaying menu

### ISSUE THREAD

**Issue by jankuca** [electron/electron#7098] opened 2016-09-05 10:04 UTC
Is there a way to observe alt key press state change while displaying application menus?

I would like to update the menu items (which I am not sure is possible either) while the menu is displayed and the user is toggling the alt key.

This behavior can be seen in the OS X Finder app for instance.

**Comment by xywz** [comment] 2016-09-05 10:16
Duplicate of #5992.

**Comment by kevinsawicki** [comment] 2016-09-06 17:16
Closing and merging into #5992

**Closed by kevinsawicki** 2016-09-06 17:16 UTC
