### ISSUE TITLE
Electron hangs when requiring certain dependencies from within tmux

### ISSUE THREAD

**Issue by yggie** [electron/electron#8479] opened 2017-01-23 17:03 UTC
* Electron version: `v1.4.15`
* Operating system: `macOS Sierra (10.12.2)`
* [tmux](https://tmux.github.io/) version: `2.3`
* node version: `7.4.0`

For reasons that I cannot understand, electron hangs when trying to import certain dependencies. I tried to narrow down the dependency as far as I could go, and ended up with this line:

```javascript
require('define-properties')
```

### Expected behavior

electron runs as normal.

### Actual behavior

electron **hangs**

### How to reproduce

1. Create a basic electron project with a single dependency (`define-properties`) and have the following line execute in the electron window:

   ```javascript
   require('define-properties')
   ```

   Do this by adding the line within a `script` tag. Alternatively, clone [this](https://github.com/yggie/electron-tmux-bug-replication) repository which does most of the boilerplate.
2. Run `tmux` and within a `tmux` window, navigate into the project directory
3. Run the app using `electron .` (or `npm start` in the provided repo)
4. Electron should hang when trying to bring up the page

**Comment by dkfiresky** [comment] 2017-01-23 19:57
@yggie the cause of your issue is that you ask nodejs to install packages **each** time you're launching your app via `npm start`.

https://docs.npmjs.com/misc/scripts
> prestart, start, poststart: Run by the npm start command.

Here is how it works:
```sh
$ > npm start

> your-app@0.1.0 prestart ~/electron-tmux-bug-replication
> echo prestart

prestart

> your-app@0.1.0 start ~/electron-tmux-bug-replication
> echo start

start
```

To fix your issue, simply don't do the `npm install` on `prestart`.
Launching the app via `electron .` doesn't reflect your issue.

**Comment by yggie** [comment] 2017-01-23 22:32
@dkfiresky have you tried running it within a `tmux` session? I can still replicate the problem when running:

```
./node_modules/.bin/electron .
```

within a `tmux` session. Running this outside a `tmux` session works fine.

**Note**: I have also managed to successfully replicated this problem on a colleagues machine using the same `tmux` and `node` version and following the instructions in the description.

Also as a side note, I don’t think it installs the dependencies each time, but checks before it runs each time and installs missing dependencies though I might be wrong.

**Comment by yggie** [comment] 2017-01-24 08:09
Looks like the same problem happens when trying to inspect the `window` object in the development console, not sure if this would be related to the bug above.

**Comment by groundwater** [comment] 2017-02-21 07:25
Hi @yggie. Can you update your repro case with @dkfiresky's suggestion and confirm you're still experiencing the same issue?

**Comment by yggie** [comment] 2017-02-21 15:58
@groundwater the repo has been updated to remove `prestart` as suggested by @dkfiresky. The issue still exists for me, running either `npm start` or `./node_modules/.bin/electron .` causes electron to hang.

**Comment by dkfiresky** [comment] 2017-02-21 16:43
I can confirm that electron process hangs on requiring the `define-properties` module.

When I start digging, I found that It's caused by one of dependencies called `object-keys`.
But then I tried to log the `window` object inside the Developer Tools console and the process freeze.

Electron was executed within the `tmux` session.

**Comment by groundwater** [comment] 2017-02-22 00:31
Thanks for the work @yggie and @dkfiresky. Will take a look.

If you get the chance, trying this on the current `1.6.0` beta would be great `npm i electron@beta`.

**Comment by yggie** [comment] 2017-02-22 10:02
unfortunately electron `1.6.0` still has this issue… I have updated the repo to reflect that

**Comment by dkfiresky** [comment] 2017-02-22 10:03
@groundwater I was able to reproduce the issue on these versions: 
 - 1.6.1
 - 1.6.0
 - 1.5.1
 - 1.5.0
 - 1.4.15
 - 1.4.14 (was unable to install)

**Comment by zcbenz** [comment] 2017-06-06 01:54
Running Electron from tmux has some [unintended behaviors](https://github.com/electron/electron/issues?q=is%3Aissue+tmux+is%3Aclosed), I'm not sure whether is a bug of tmux or macOS, but we are not able to fix it on Electron's side, and tmux is not designed to be run any GUI program inside at all. So I'm closing this as won't fix.

**Closed by zcbenz** 2017-06-06 01:54 UTC
Labels: platform/macOS, triage/bug
