### ISSUE TITLE
Resizing window while moving does not work

### ISSUE THREAD

**Issue by RX14** [electron/electron#3614] opened 2015-11-28 13:40 UTC
Using electron v0.35.1 on windows 10, there is significant bugginess when resizing a window from code.

[Screen recording](https://aww.moe/wqqazi.mp4). Here I resize the window shortly after startup to be smaller than full size, but hidden content still shows. The area that should not be shown glitches out when dragging, and reappears when you stop.  When you drag the window off the top of the screen, the glitchiness stops.

Here is my code:
```javascript
const electron = require("electron");
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

var mainWindow = null;
var electronScreen = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
    app.quit();
});

const winWidth = 1184;
const winHeight = 804;
const winSmallHeight = 666;

function recalculateSize() {
    var display = electronScreen.getDisplayMatching(mainWindow.getBounds());
    if (display.workAreaSize.height > 803) {
        mainWindow.setSize(1184, 804);
    } else {
        mainWindow.setSize(1184, 666);
    }
}

app.on("ready", function() {
    electronScreen = electron.screen;

    mainWindow = new BrowserWindow({
        width: 1184,
        height: 804,

        useContentSize: true,
        center: true,
        resizable: false,
        fullscreen: false,
        frame: false,
        type: "splash"
    });

    mainWindow.on("move", function(e) {
        recalculateSize();
    });
    electronScreen.on("display-metrics-changed", function() {
        recalculateSize();
    });

    recalculateSize();

    mainWindow.loadURL("file://" + __dirname + "/src/main.html");

    mainWindow.on("closed", function() {
        mainWindow = null;
    })
});
```

**Comment by RX14** [comment] 2015-11-28 13:41
This might be related to #734.

**Comment by etiktin** [comment] 2015-11-29 17:56
- Does it reproduce if you set `resizable` to true?
- Does it work better if you check the current size and resize only if it's different than the current size?
- Are you getting many move events (I imagine it's constantly firing while you move the window)? If that's the case, consider using a timer to delay the resize (e.g. once every 100ms) which might provide a smoother experience.

**Comment by RX14** [comment] 2015-11-29 23:37
1. It does reproduce with `resizable: true`
2. It still exhibits the same behaviour if setSize is called if there's a change.
3. Setting a rate limit on the function does not help. For every call of the function, it seems to change the window size then immediately clip back the the original size.

None of the options passed to `new BrowserWindow` seem to cause it, in fact it reproduces with an empty hash as options.

**Comment by RX14** [comment] 2015-11-29 23:44
I haven't tested in windows 7, but windows definitely do not change size for more than a single frame when calling `setSize()` in my testing on windows 10.

**Comment by zcbenz** [comment] 2015-11-30 07:57
I'm unable to reproduce by loading google.com. Does it happen if you load pages other than your `main.html`?

**Comment by RX14** [comment] 2015-11-30 14:17
I'll try and create a minimal reproducible example when I get home tonight.

**Comment by RX14** [comment] 2015-12-02 23:17
OK, I can reproduce on windows 10 with this:
```javascript
const electron = require("electron");
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

app.on("ready", function() {
    mainWindow = new BrowserWindow({
      width: 500,
      height: 500
    });

    mainWindow.on("move", function(e) {
        mainWindow.setSize(1000, 1000);
    });

    mainWindow.loadURL("https://google.com/");
});
```

**Comment by RX14** [comment] 2015-12-02 23:33
Just tested in windows 7, also the same.

Also with v0.35.2.

**Comment by etiktin** [comment] 2015-12-02 23:51
> It still exhibits the same behaviour if setSize is called if there's a change.

So you only see it once you move the window to a screen with a different resolution, right? Doesn't this solve your original issue? A single resize as opposed to the dozens in the original code, should be hardly noticeable.

**Comment by RX14** [comment] 2015-12-03 08:32
It seems to me that resizing a window while it is being moved/dragged is the issue here. I haven't really tested resizing when the window isn't being dragged but I'm almost sure it will work. 

Re @etiktin
I'm not sure I quite understand what you are staying but the issue occurs on all screens. Calling setSize only when the current window size is different to the target window size doesn't work because most of the time getSize reports the old window size, as the window keeps snapping back to its old size.

**Comment by etiktin** [comment] 2015-12-03 17:12
I tried it on Windows 8.1 and the issue is that during move (until you release the window), the size change is getting overridden. So you see it resizing to the new size and than it goes back to the old size which will cause that flicker you're seeing.

As a workaround I tried setting a timer to do the resize 100ms later and reset that timer when ever move is fired. It doesn't work reliably because while you hold the window frame or drag area without actually moving (no move event is fired), the issue still happens (the window is resized to the new size and then changes back to the old size).

My first hunch was that it might be caused by a patch we added a while back to fix incorrect size on window restore (the stuff we do with `last_normal_size_` at https://github.com/atom/electron/blob/master/atom/browser/native_window_views_win.cc#L115-L160), but it's unrelated (commenting out all the code doesn't fix the issue).

@zcbenz any thoughts? Do we have any way of knowing when the window frame or drag area is released?

**Comment by RX14** [comment] 2015-12-03 17:27
It would be easy to work around if there was a "moved" event on windows that fired after the window move was complete.

**Comment by zcbenz** [comment] 2016-07-09 13:08
The same behavior can be reproduce in Chrome apps, since Electron is using Chromium's code for creating windows, we are not able to fix this on Electron's side. I suggest making a reproducible example as Chrome app, and reporting it to Chromium' issues list instead.

I'm closing this as won't fix.

**Closed by zcbenz** 2016-07-09 13:08 UTC
Labels: bug, windows
