### ISSUE TITLE
Webviews with different session partition do not own their own WebSQL DB

### ISSUE THREAD

**Issue by mannok** [electron/electron#17106] opened 2019-02-24 16:38 UTC
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.5
* **Operating System** (Platform and Version):
  * Windows 10 (1809)
* **Last known working Electron version** (if applicable):
  * n/a

### Expected Behavior
Webviews with different session partition have their own WebSQL scope. For e.g. each partition get its own DBs, tables, records, etc.

### Actual behavior
Webviews with different session partition affecting the same DB instance. One partition insert a record to a table, another one can read that record.

### To Reproduce
Create 2 webviews on main window with different session partition. Try to insert a record into a table from a webview and then select it from another webview.

### Screenshots
![image](https://user-images.githubusercontent.com/458220/53302081-6eb2b980-3895-11e9-95f8-d7da96af93f3.png)

**Comment by jameza111** [comment] 2019-02-24 16:46
ส่งจากโทรศัพท์มือถือ Huawei ของฉัน-------- ข้อความต้นฉบับ --------เรื่อง: Re: [electron/electron] Webviews with different session partition do not own their own WebSQL DB (#17106)จาก: "welcome[bot]" ถึง: electron/electron สำเนา: Subscribed 👋 Thanks for opening your first issue here! If you're reporting a 🐞 bug, please make sure you include steps to reproduce it. We get a lot of issues on this repo, so please be patient and we will get back to you as soon as we can.

To help make it easier for us to investigate your issue, please follow the contributing guidelines.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/electron/electron","title":"electron/electron","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/electron/electron"}},"updates":{"snippets":[{"icon":"PERSON","message":"@welcome in #17106: 👋 Thanks for opening your first issue here! If you're reporting a 🐞 bug, please make sure you include steps to reproduce it. We get a lot of issues on this repo, so please be patient and we will get back to you as soon as we can.\n\nTo help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).\n"}],"action":{"name":"View Issue","url":"https://github.com/electron/electron/issues/17106#issuecomment-466792534"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/electron/electron/issues/17106#issuecomment-466792534",

"url": "https://github.com/electron/electron/issues/17106#issuecomment-466792534",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by jameza111** [comment] 2019-02-24 16:46
ส่งจากโทรศัพท์มือถือ Huawei ของฉัน-------- ข้อความต้นฉบับ --------เรื่อง: [electron/electron] Webviews with different session partition do not own their own WebSQL DB (#17106)จาก: Xanthus Wong ถึง: electron/electron สำเนา: Subscribed 
Electron Version (output of node_modules/.bin/electron --version):

4.0.5


Operating System (Platform and Version):

Windows 10 (1809)


Last known working Electron version (if applicable):

n/a



Expected Behavior
Webviews with different session partition have their own WebSQL scope. For e.g. each partition get its own DBs, tables, records, etc.
Actual behavior
Webviews with different session partition affecting the same DB instance. One partition insert a record to a table, another one can read that record.
To Reproduce
Create 2 webviews on main window with different session partition. Try to insert a record into a table from a webview and then select it from another webview.
Screenshots


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/electron/electron","title":"electron/electron","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/electron/electron"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Webviews with different session partition do not own their own WebSQL DB (#17106)"}],"action":{"name":"View Issue","url":"https://github.com/electron/electron/issues/17106"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/electron/electron/issues/17106",
"url": "https://github.com/electron/electron/issues/17106",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by electron-triage** [comment] 2020-02-19 20:54
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by mannok** [comment] 2020-02-20 17:04
still not solved!!

**Comment by electron-triage** [comment] 2020-02-26 20:50
Thank you for your issue!

We haven't gotten a response to our questions in our [comment above](https://github.com/electron/electron/issues/17106#issuecomment-588455632). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:50 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/windows

**Comment by mannok** [comment] 2020-10-28 07:50
Still happening on 2020-10-28
