### ISSUE TITLE
GetSources is not showing open full screen apps in Mac

### ISSUE THREAD

**Issue by steff456** [electron/electron#17767] opened 2019-04-11 22:58 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
4.1.3
  * 
* **Operating System:**
macOS 10.14.3
  * 
* **Last Known Working Electron version:**:
1.3.0
  * 

### Expected Behavior

When using desktopCapturer.getSources() I expect to have a complete list of the applications that are open. Including if they are in full screen mode or not.

### Actual Behavior

desktopCapturer.getSources() only show the windows and screens that are windowed but not the full screen ones.

### To Reproduce

Clone this repository 
```
git clone https://github.com/hokein/electron-screen-recorder
npm init
npm start
```
This app is running under electron 1.3.0, select the screen sharing and all the applications will show. Then, we update to the last electron version 4.1.3 changing the package.json requirement.

```
npm init
npm start
```

The app is not showing the full screen applications anymore.

**Comment by steff456** [comment] 2019-05-02 17:23
> desktopCapturer.getSources(options, callback)

What's the replacement method?
I cannot find the new function. In the [docs](https://electronjs.org/docs/api/desktop-capturer) they say that it will be deprecated soon but nothing else.

**Comment by codebytere** [comment] 2019-05-02 17:34
@steff456 the replacement is the method directly [beneath](https://electronjs.org/docs/api/desktop-capturer#desktopcapturergetsourcesoptions)! The change is simply a move from callback to promise-based asynchronous functionality. This shouldn't make any difference in the issue you're otherwise experiencing, though.

**Comment by steff456** [comment] 2019-05-02 17:58
> @steff456 the replacement is the method directly [beneath](https://electronjs.org/docs/api/desktop-capturer#desktopcapturergetsourcesoptions)! The change is simply a move from callback to promise-based asynchronous functionality. This shouldn't make any difference in the issue you're otherwise experiencing, though.

Thanks!!!

**Comment by codebytere** [comment] 2019-05-02 18:04
@steff456 i just reproduced this locally off `master` and have a bit of bandwidth so i'll see if i can dig into this :)

**Comment by codebytere** [comment] 2019-05-24 01:10
Circling back to this: i spent a few hours on it today and determined that unfortunately it's a behavior that originates in Chromium, perhaps by design. Chromium will capture all windows or screens that are _currently in view_ only.

You can see this behavior replicated if you run [this app](https://chrome.google.com/webstore/detail/desktop-capture-sample/mhkidniocjdaiddjckopkigjmjbadfji/related) locally. There, the window items are updated dynamically, and so by flipping between different fullscreen app views on macOS you'll see the contents of the `Application Window` view change to reflect the windows currently on-screen. As such, this is unfortunately not something we can fix and so i'm going to go ahead and close it.

Should something change on Chromium's side, i'll be sure to re-investigate!

**Closed by codebytere** 2019-05-24 01:10 UTC
Labels: 4-2-x, bug :beetle:, platform/macOS

**Comment by ramaralo** [comment] 2020-12-07 11:48
@codebytere 
Do you have any update on this issue? 

I've noticed there are other related issues like:
https://github.com/electron/electron/issues/20073
https://github.com/electron/electron/issues/18417

Thanks!

**Comment by alectrocute** [comment] 2021-02-09 18:59
@codebytere Kindly looking forward to an update if one exists!
