### ISSUE TITLE
[Bug]: ERR_UNSAFE_REDIRECT

### ISSUE THREAD

**Issue by alhafram** [electron/electron#35581] opened 2022-09-06 14:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.1

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.0 Beta

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

20.0.3

### Expected Behavior

No error when redirection happens in `onBeforeRequest`

### Actual Behavior

Error when redirection happens in `onBeforeRequest`

### Additional Information

I redirect some remote scripts like in code below to some local and get this error
```
session.defaultSession.webRequest.onBeforeRequest(filter, (details, callback) => {
    if(details.resourceType == 'script') {
        if(details.url.includes('js/common.js?ux=')) {
            callback({
                redirectURL: `file://${app.getAppPath()}/src/Scripts/common.js`
            })
            return
        }
    }
})


Browser view setup code

const browserView = new BrowserView({
    webPreferences: {
        enablePreferredSizeMode: true,
        preload: path.join(__dirname, 'MainBrowserViewPreload.js'),
        contextIsolation: false,
        webSecurity: false,
        nodeIntegration: true,
        allowRunningInsecureContent: true,
        sandbox: false
    }
})
```

**Comment by codebytere** [comment] 2022-09-07 13:38
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by alhafram** [comment] 2022-09-07 21:17
https://gist.github.com/alhafram/af4313cd2c7cb2ecc97105316e978981

**Comment by vicrep** [comment] 2022-09-12 17:15
I have a similar issue when upgrading from electron 19.0.11 to 19.0.14 (and when upgrading to latest v20). Looking at related changes, I have a feeling that this is what could've caused the issue: https://github.com/electron/electron/pull/35271

Still haven't found resolution steps though and not too sure if it's an intended error.

**Comment by MarshallOfSound** [comment] 2022-11-30 10:51
Per https://github.com/electron/electron/pull/35357 this change is intentional, please read through that PR for how to change your code to not violate web security protections 👍

**Closed by MarshallOfSound** 2022-11-30 10:51 UTC
Labels: platform/macOS, bug/regression :leftwards_arrow_with_hook:, has-repro-gist, 20-x-y
