### ISSUE TITLE
Clicking a menu item causes freeze in video tag playback

### ISSUE THREAD

**Issue by feross** [electron/electron#6897] opened 2016-08-19 01:37 UTC
* Electron version: 1.3.3
* Operating system: macOS

Clicking on a menu item causes a small freeze/stutter in `<video>` playback. 

<img width="387" alt="screen shot 2016-08-18 at 6 32 48 pm" src="https://cloud.githubusercontent.com/assets/121766/17796026/4d0a91a2-6572-11e6-994d-17e297cb09ab.png">

We're not running any code in WebTorrent Desktop when the menu item is closed, and I confirmed the same behavior in another video app based on Electron ([Playback](https://mafintosh.github.io/playback/)) so this looks like an Electron issue.

Could Electron be running some synchronous code that is blocking the event loop?

**Comment by zcbenz** [comment] 2016-08-22 00:13
I can reproduce the same problem when playing youtube videos on Chrome 52 browser, I suggest reporting this to Chromium's issues list instead since it is an upstream bug.

I'm closing this since we are not able to solve this on Electron's side.

**Closed by zcbenz** 2016-08-22 00:13 UTC

**Comment by feross** [comment] 2016-08-22 00:15
No problem.
