### ISSUE TITLE
[Bug]: Eyedropper does not working outside the electron window.

### ISSUE THREAD

**Issue by 50UM3N** [electron/electron#32732] opened 2022-02-03 16:35 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

The Eyedropper tool should work outside the electron window so that we can pick colors from the outside of the application, not in the application window only.

### Actual Behavior

The Eyedropper tool goes vanishes when the pointer crosses the window.

### Additional Information

Here are some previews of my problem

1. When I use ```new window.EyeDropper()```

![preview](https://user-images.githubusercontent.com/30142639/152385724-6ebe22aa-5ede-4133-9049-9dfd2c934836.gif)
2. When I use ```<input type="color" name="foo" id="bar">```

![preview2](https://user-images.githubusercontent.com/30142639/152385761-76dbed68-78a7-4cf0-a30e-d2701430fe6a.gif)

**Comment by nornagon** [comment] 2022-02-04 19:52
Duplicate of #27980

**Closed by nornagon** 2022-02-04 19:52 UTC
Labels: bug :beetle:, duplicate
