### ISSUE TITLE
[Bug]: Electron crashes sporadically on Apple M1 hardware

### ISSUE THREAD

**Issue by Glebka** [electron/electron#28565] opened 2021-04-07 15:12 UTC
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.3

### What operating system are you using?

macOS

### Operating System Version

macOs Big Sur 11.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

N/A

### Expected Behavior

The app is not crashing.

### Actual Behavior

The app crashing sporadically.

### Testcase Gist URL

https://gist.github.com/Glebka/b7c6b202d89ea25e3b64d6c504dfd194

I attached a crash report as gist.
Please have a look.

Our app is a corporate messenger with telephony and video meeting capabilities.
The version that is crashing was built for x64 arch and was running using Rosetta on Apple M1 hardware.

The crash occurs sporadically. Users report that may happen suddenly when they navigate thru the UI or start a telephony / video call. We use WebRTC features and WebAssembly, fyi.

The crash I published were caught by Mac OS, despite we have a Sentry crash reporter configured.

I see the stack trace from com.github.Electron.framework is not symbolicated, so, probably not useful.
Could you please suggest how to symbolicate it?

Will appreciate any help on this. Thanks.

**Comment by VerteDinde** [comment] 2021-04-10 04:34
Hey @Glebka, is this a duplicate of #28578 ? The two reports and gist crash reports look similar, but if there's two different issues, let me know. I'll close this as a duplicate if they are the same issue 🙇‍♀️

**Comment by zcbenz** [comment] 2021-04-13 11:57
I'm merging this issue to https://github.com/electron/electron/issues/28577 since the both the crashed thread and the behavior are the same.

**Closed by zcbenz** 2021-04-13 11:57 UTC
Labels: bug :beetle:
