### ISSUE TITLE
[Bug]: setContentProtection(true) does not work

### ISSUE THREAD

**Issue by cgri1** [electron/electron#39453] opened 2023-08-10 07:10 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.5.0

### What operating system are you using?

macOS

### Operating System Version

macOs Monterey 12.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

21.4.1

### Expected Behavior

The function of setContentProtection(true) work by the always on top mode

### Actual Behavior

The function of setContentProtection(true) does not work by the always on top mode. The participants see always on top screen
![error](https://github.com/electron/electron/assets/39028198/4791a488-936a-4228-905d-a9aab8c0979b)

**Comment by codebytere** [comment] 2023-08-10 13:52
Duplicate of https://github.com/electron/electron/issues/39452

**Closed by codebytere** 2023-08-10 13:52 UTC
Labels: bug :beetle:
