### ISSUE TITLE
Blob is empty if it is passed as a parameter via contextBridge

### ISSUE THREAD

**Issue by AmarBouchibane** [electron/electron#27364] opened 2021-01-19 11:16 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0-beta.16
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * unknown 

### Expected Behavior

Since blobs belong to the cloneable object types, the value should arrive in the function.

### Actual Behavior

The parameter value is empty.

### To Reproduce

preload.js

> const {contextBridge} = require("electron");
> contextBridge.exposeInMainWorld("WebVC", {
>   writeBlobToFile: (blob) => {
>     console.log(blob);
>   }
> });

renderer.js

> window.WebVC.writeBlobToFile(new Blob(["Hello World"]));

Electron fiddle: https://gist.github.com/AmarBouchibane/624d61b9208f7d67c768a9a7f3df3109

**Comment by codebytere** [comment] 2021-01-19 20:53
@AmarBouchibane please provide a reproducible piece of code that could for example be run with [Fiddle](https://github.com/electron/fiddle). The code you have provided forces us to make assumptions about what else might be going on, which makes effective triage difficult. We will continue to triage when this is provided.

**Comment by AmarBouchibane** [comment] 2021-01-20 09:24
I've published an Electron fiddle in Gist here:
https://gist.github.com/AmarBouchibane/624d61b9208f7d67c768a9a7f3df3109.js
If you set contextIsolation: false, the blob.text() promise can be resolved. If it's set to contextIsolation:true, the text() function isn't availbale.

**Comment by codebytere** [comment] 2021-01-26 19:36
Thanks @AmarBouchibane !

**Comment by ckerr** [comment] 2021-01-26 20:25
Marking as `confirmed` because when running the testcase I'm seeing the same error message: https://gist.github.com/AmarBouchibane/624d61b9208f7d67c768a9a7f3df3109, yields this message when setting `contextIsolation: true`:

`Uncaught Error: Uncaught TypeError: blob.text is not a function`

Tested on Ubuntu 20.10 using v12.0.0-beta.6, v11.2.1, and v11.0.0. Same error in all three.

**Comment by MarshallOfSound** [comment] 2021-01-27 04:09
To clarify why this is an issue and currently expected behavior.  Blob is a DOM clonable type not a JS cloneable type.  There's an open issue somewhere to use blinks serialized in the contextBridge instead of V8's but that has complications attached to it

**Comment by AmarBouchibane** [comment] 2021-01-27 07:01
Thanks to everyone for your efforts!
If this is expected behavior, is there a workaround?

**Comment by AmarBouchibane** [comment] 2021-05-18 05:50
Is there any news when we can expect a fix? We cannot set contextIsolation to true in our application because of this defect.
Thanks!

**Closed** 2021-05-26 17:34 UTC
Labels: 11-x-y, 12-x-y, bug :beetle:, has-repro-gist, platform/all, status/confirmed
