### ISSUE TITLE
[Bug]: wraping a nodejs web-client tunneling ROS over websockets in electron

### ISSUE THREAD

**Issue by newcanopies** [electron/electron#28512] opened 2021-04-05 18:23 UTC
### Preflight Checklist

I have read the Contributing Guidelines for this project.
I agree to follow the Code of Conduct that this project adheres to.
I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### Operating System Version

Windows 10 Build 19041 running WSL2 Ubuntu 20.04 , Arch x64, VS Code

### Expected Behavior

Trying to load the Nodejs based robot simulation web-client [GZWEB](https://github.com/osrf/gzweb) that the user can interact with -- in an electron window. 

Normally, 
GZWEB Nodejs package creates a websocket server tunneling over websockets from another robot simulator package to a Web Browser @ localhost:8080, via it's internal modules GZBRIDGE (websocket server) and GZ3D (html and WebGL rendering).

### Actual Behavior

When electron is added as a node_module inside GZWEB package, 
and appropriate changes are made to package.json and Main.js, 
GZWEB should load inside a new electron Window the way it would in the Web Broswer @localhost:8080.
However, only the static content of GZWEB loads, not the stream of the robot or the WebGL elements.
Essentially, not displayed is everything that needs to get tunneled over the websocket server, giving this DevTools error:

**Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ws://:' is invalid. roslib.js:2224**

How can a package like GZWEB be wrapped in electron, so that the GZBRIDGE module node is properly initiated as well as the websocket server on port localhost:8080?

Below are modifications to the gzweb package in order to load in electron window. 

**_gzweb/package.json_**
<details>

```{
  "name": "gzweb",
  "version": "1.4.0",
  "description": "WebGL client for Gazebo",
  "repository": {
    "type": "mercurial",
    "url": "https://github.com/osrf/gzweb"
  },
  "config": {
    "port": ""
  },
  "scripts": {
    "test": "./node_modules/.bin/eslint gz3d/src/*.js gz3d/test/*.js gzbridge/server.js && ./node_modules/karma/bin/karma start --singleRun",
    "update": "./node_modules/.bin/grunt build && cd build && cmake ..",
    "start": "if [ $npm_config_port ]; then port=$npm_config_port; fi; cd gzbridge && ./server.js $port",
    "deploy": "./deploy.sh",
    "docs": "./node_modules/.bin/grunt doc",
    "coverage": "codecov"
  },
  "dependencies": {
    "custom-electron-titlebar": "^3.2.3",
    "dotenv": "^8.2.0",
    "fs": "0.0.1-security",
    "http": "0.0.0",
    "node-gyp": "6.1.0",
    "path": "^0.12.7",
    "rclnodejs": "^0.17.0",
    "websocket": "^1.0.33"
  },
  "devDependencies": {
    "catharsis": "^0.8.9",
    "codecov": "^2.3.0",
    "electron": "^12.0.0",
    "eslint": "^4.8.0",
    "grunt": "~0.4.1",
    "grunt-cli": "^1.2.0",
    "grunt-contrib-clean": "^1.1.0",
    "grunt-contrib-concat": "^1.0.1",
    "grunt-contrib-jshint": "^1.1.0",
    "grunt-contrib-uglify": "^3.1.0",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-jsdoc": "^2.1.1",
    "istanbul": "^0.4.5",
    "jasmine-core": "^2.8.0",
    "jasmine-jquery": "^2.1.1",
    "jsdoc": "^3.5.5",
    "karma": "^1.7.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.1",
    "karma-htmlfile-reporter": "^0.3.5",
    "karma-jasmine": "^1.1.0",
    "taffydb": "^2.7.3",
    "underscore": "^1.8.3",
    "ws": "3.3.2"
  }
}
```
</details>

```
"devDependencies": {
    "electron": "^12.0.0",
```

**_gzweb/gzbridge/main.js_**

<details>

``` require('dotenv').config();

const setupEvents = require('../electron/installers/setupEvents')
if (setupEvents.handleSquirrelEvent()) {
  return;
}

const electron = require('electron');
  console.log(require.resolve('electron'));

const app = electron.app;

app.allowRendererProcessReuse = true;

const {ipcMain} = require('electron');
var path = require('path')
require('../electron/dialog/dialog')

const BrowserWindow = electron.BrowserWindow

let mainWindow
let secondWindow

function createWindow () {
  mainWindow = new BrowserWindow({titleBarStyle: 'hidden',
    width: 1400,
    height: 800,
    minWidth: 1400,
    minHeight: 800,
    backgroundColor: '#312450',
    show: false,
    icon: path.join(__dirname, '../electron/icons/png/64x64.png'),
    webPreferences: {
      nodeIntegration: true
    }
  })

  mainWindow.loadURL(`file://${__dirname}gzweb/http/client/index.html`)
 
  mainWindow.webContents.openDevTools()


  mainWindow.once('ready-to-show', () => {
    mainWindow.show()
  })

  mainWindow.on('closed', function () {
    mainWindow = null
  })

  secondWindow = new BrowserWindow({frame: false,
    width: 800,
    height: 600,
    minWidth: 800,
    minHeight: 600,
    backgroundColor: '#312450',
    show: false,
    icon: path.join(__dirname, '../electron/icons/png/64x64.png'),
    parent: mainWindow,
    webPreferences: {
      nodeIntegration: true
    }
  })

  secondWindow.loadURL(`file://${__dirname}../electron/windows/ipcwindow.html`)

  require('../electron/menu/mainmenu.js')
}


ipcMain.on('open-second-window', (event, arg)=> {
    secondWindow.show()
})

ipcMain.on('close-second-window', (event, arg)=> {
    secondWindow.hide()
})

app.on('ready', createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})

```
</details>

**Comment by newcanopies** [comment] 2021-04-05 18:23
gzweb/gzbridge/**server.js**   (with electron as required node_module)

<details>
```
#!/usr/bin/env node

"use strict"

const WebSocketServer = require('websocket').server;
const http = require('http');
const fs = require('fs');
//const path = require('path');
const gzbridge = require('./build/Debug/gzbridge');


const {spawn} = require('child_process');
const electron = require('electron');
  console.log(require.resolve('electron'));

const path = require('path')
const appPath = path.join(__dirname, 'main.js')
const args = [appPath].concat(process.argv.slice(2))
const proc = spawn(electron, args, {stdio: 'inherit'})

proc.on('close', (code) => process.exit(code))


var mimes = require('./mimeTypes.json')

/**
 * Path from where the static site is served
 */
//const staticBasePath = './../http/client';
const staticBasePath = '';

/**
 * Port to serve from, defaults to 8080
 */
//ORIGINALLY [2]
//const port = process.argv[2] || 8080;
const port = process.argv[3] || 8080;
  console.log(process);


/**
 * Array of websocket connections currently active, if it is empty, there are no
 * clients connected.
 */
let connections = [];
  console.log(connections);
/**
 * Holds the message containing all material scripts in case there is no
 * gzserver connected
 */
let materialScriptsMessage = {};

/**
 * Whether currently connected to a gzserver
 */
let isConnected = false;

/**
 * Callback to serve static files
 * @param req Request
 * @param res Response
 */
let staticServe = function(req, res) {

  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Request-Method', '*');
  res.setHeader('Access-Control-Allow-Methods', 'OPTIONS, GET');
  res.setHeader('Access-Control-Allow-Headers', '*');

  let fileLoc = path.resolve(staticBasePath);
    console.log(staticBasePath);

  if (req.url === '/')
    req.url = '/index.html';

  fileLoc = unescape(path.join(fileLoc, req.url));

  fs.readFile(fileLoc, function(err, data) {
    if (err) {
        console.error('File not found [', fileLoc, ']');
        res.writeHead(404, 'Not Found');
        res.write('404: File Not Found!');
        return res.end();
    }

    res.statusCode = 200;

    var extension = req.url.substring(
      req.
      url.lastIndexOf(".")
    );
  
    var type = mimes[extension];
    if(type) {
        res.setHeader("content-type", type);
    }

    res.write(data);
    return res.end();
  });
};

// HTTP server
let httpServer = http.createServer(staticServe);
httpServer.listen(port);
  console.log(port);

console.log(new Date() + " Static server listening on port: " + port);

// Websocket
let gzNode = new gzbridge.GZNode();
if (gzNode.getIsGzServerConnected())
{
  gzNode.loadMaterialScripts(staticBasePath + './assets');
  gzNode.setPoseMsgFilterMinimumAge(0.02);
  gzNode.setPoseMsgFilterMinimumDistanceSquared(0.00001);
  gzNode.setPoseMsgFilterMinimumQuaternionSquared(0.00001);

  console.log('--------------------------------------------------------------');
  console.log('Gazebo transport node connected to gzserver.');
  console.log('Pose message filter parameters between successive messages: ');
  console.log('  minimum seconds: ' +
      gzNode.getPoseMsgFilterMinimumAge());
  console.log('  minimum XYZ distance squared: ' +
      gzNode.getPoseMsgFilterMinimumDistanceSquared());
  console.log('  minimum Quartenion distance squared:'
      + ' ' + gzNode.getPoseMsgFilterMinimumQuaternionSquared());
  console.log('--------------------------------------------------------------');
}
else
{
  materialScriptsMessage =
      gzNode.getMaterialScriptsMessage(staticBasePath + '/assets');
}

// Start websocket server
let wsServer = new WebSocketServer({
  httpServer: httpServer,
  // You should not use autoAcceptConnections for production
  // applications, as it defeats all standard cross-origin protection
  // facilities built into the protocol and the browser.  You should
  // *always* verify the connection's origin and decide whether or not
  // to accept it.
  //NOTE ------------------------------------------------------------------------CHANGE BACK TO FALSE
  autoAcceptConnections: true
});

wsServer.on('request', function(request) {

  // Accept request
  let connection = request.accept(null, request.origin);

  // If gzserver is not connected just send material scripts and status
  if (!gzNode.getIsGzServerConnected())
  {
    // create error status and send it
    let statusMessage =
        '{"op":"publish","topic":"~/status","msg":{"status":"error"}}';
    connection.sendUTF(statusMessage);
    // send material scripts message
    connection.sendUTF(materialScriptsMessage);
    return;
  }

  connections.push(connection);

  if (!isConnected)
  {
    isConnected = true;
    gzNode.setConnected(isConnected);
  }

  console.log(new Date() + ' New connection accepted from: ' + request.origin +
      ' ' + connection.remoteAddress);

  // Handle messages received from client
  connection.on('message', function(message) {
    if (message.type === 'utf8') {
      console.log(new Date() + ' Received Message: ' + message.utf8Data +
          ' from ' + request.origin + ' ' + connection.remoteAddress);
      gzNode.request(message.utf8Data);
    }
    else if (message.type === 'binary') {
      console.log(new Date() + ' Received Binary Message of ' +
          message.binaryData.length + ' bytes from ' + request.origin + ' ' +
          connection.remoteAddress);
      connection.sendBytes(message.binaryData);
    }
  });

  // Handle client disconnection
  connection.on('close', function(reasonCode, description) {
    console.log(new Date() + ' Peer ' + request.origin + ' ' +
        connection.remoteAddress + ' disconnected.');

    // remove connection from array
    let conIndex = connections.indexOf(connection);
    connections.splice(conIndex, 1);

    // if there is no connection notify server that there is no connected client
    if (connections.length === 0) {
      isConnected = false;
      gzNode.setConnected(isConnected);
    }
  });
});

// If not connected, periodically send messages
if (gzNode.getIsGzServerConnected())
{
  setInterval(update, 10);

  function update()
  {
    if (connections.length > 0)
    {
      let msgs = gzNode.getMessages();
      for (let i = 0; i < connections.length; ++i)
      {
        for (let j = 0; j < msgs.length; ++j)
        {
          connections[i].sendUTF(msgs[j]);
        }
      }
    }
  }
}
```
</details>

**Comment by newcanopies** [comment] 2021-04-07 01:17
Javascript linked in index.html, calls on objects and classes in other directory scripts as below.

this is the ros-package code that is not being execute once wrapped in electron:

`
GZ3D.GZIface = function(scene, url)
{
  this.emitter = globalEmitter || new EventEmitter2({verboseMemoryLeak: true});
  this.scene = scene;
  this.url = url ||
      **(location.hostname + ':' + location.port + location.pathname);**
  this.protocol = location.protocol;
  this.secure = location.protocol === 'https:';

  this.isConnected = false;

  this.material = [];
  this.entityMaterial = {};

  this.connect();
  this.visualsToAdd = [];

  this.numConnectionTrials = 0;
  this.maxConnectionTrials = 30; // try to connect 30 times
  this.timeToSleepBtwTrials = 1000; // wait 1 second between connection trials
};

/**
 * Attempt to establish websocket connection.
 */
GZ3D.GZIface.prototype.connect = function()
{
  this.webSocket = new ROSLIB.Ros({
    url : (this.secure ? 'wss://' : 'ws://') + this.url
  });

  var that = this;
  this.webSocket.on('connection', function() {
    that.onConnected();
  });
  this.webSocket.on('error', function() {
    that.onError();
  });

  this.numConnectionTrials++;
};
`

the` location `object seems to be empty

**Comment by ckerr** [comment] 2021-04-07 04:21
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

If the issue is that Node is doing one thing and Electron is doing another, would it be possible for you to make a standalone testcase demonstrating that difference without third party code? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by newcanopies** [comment] 2021-04-08 12:00
hi @ckerr 

Windows Fiddle is not saving/running or uploading for some reason - see hangup screenshot at bottom. 

Secondly, as I am developing on WSL2 x86 it is not possible to run the correct Fiddle for Ubuntu 20.04 inside WSL2.

To solve this problem, 
the [minimal example Fiddle](https://github.com/newcanopies/webgl_cli_webbrowser_app) is uploaded.

Please have a look at the [minimal example Fiddle](https://github.com/newcanopies/webgl_cli_webbrowser_app) and suggest how to structure the core scripts so they load in correct order. 
In particular the server.js script is essential for running the websocket server for both WebGL and simulation rendering.

Windows Fiddle error  
![image](https://user-images.githubusercontent.com/65022111/114022694-55510980-9872-11eb-83a8-9d0a04818095.png)

**Comment by newcanopies** [comment] 2021-04-08 14:55
The thirdparty WebGL client package is creating the Websocket server using Nodejs websocket module. (./server.js)

Is electron interfering with the creation of the Node Websocket server because of native WebSocket API in chromium?

**Comment by zcbenz** [comment] 2021-04-14 03:36
I'm afraid this is not something that the Electron team can look into, it is a very complex third party module that we are not familiar with, and debugging it would require a lot of time.

The only way that we can help, is either you or the maintainers of the module can find out why the code is not working in Electron, and then we can fix it.

I'm closing this issue since we generally do not look into bug reports that involve with complex third party code.

**Closed by zcbenz** 2021-04-14 03:36 UTC
Labels: 12-x-y, blocked/need-repro, bug :beetle:, platform/windows
