### ISSUE TITLE
Move Electron app caches from config to cache folder on Linux systems

### ISSUE THREAD

**Issue by MurzNN** [electron/electron#10082] opened 2017-07-21 09:49 UTC
At now Electron application store cache files near to config files in folders `~/.config/APP/Cache` and `~/.config/APP/GPUCache`, so config folder contains many useless files with large size (more than 200 mb).

Linux systems use separate `~/.cache` folder for store cache files, so Google Chrome store configs in `~/.config/google-chrome` but all cache files in `~/.cache/google-chrome`. 

We can find [right location of cache folder](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) via `$XDG_CACHE_HOME` environment variable.

Please move all Electron cache files from `~/.config/APP` to `~/$XDG_CACHE_HOME/APP` folder, like other apps do.

**Comment by MarshallOfSound** [comment] 2017-07-21 09:52
Duplicate of #8124

**Closed by MarshallOfSound** 2017-07-21 09:52 UTC
