### ISSUE TITLE
Electron Linux silently exits with code 1 when DISPLAY is not set

### ISSUE THREAD

**Issue by morganrallen** [electron/electron#8757] opened 2017-02-23 17:51 UTC
* Electron version: 1.4.5
* Operating system: Linux

### Expected behavior

Electron should provide an informative error message on exit.
`xterm` for example..
```
$ xterm
xterm: Xt error: Can't open display: 
xterm: DISPLAY is not set
```

### Actual behavior

Electron exits with exit code 1 providing no further information.

### How to reproduce
```
$ unset DISPLAY
$ ./node_modules/.bin/electron .
$ echo $?
1
$
```

**Comment by deepak1556** [comment] 2017-03-13 09:28
You can get the error when passing `--enable-logging` or setting `ELECTRON_ENABLE_LOGGING`, chromium handles these errors https://cs.chromium.org/chromium/src/content/browser/browser_main_loop.cc?q=browser_main_loop+package:%5Echromium$&l=287 . I am not sure if we should expose them when the flag is not used, will defer to @zcbenz

**Comment by morganrallen** [comment] 2017-03-13 19:43
Cool, I hadn't seen the error when using `--enable-logging` which I'm using all the time now. I guess that should be good enough, but at the time it had caused a lot of head scratching.

**Comment by tim-janik** [comment] 2017-03-24 14:34
Please note that this is issue also affects development toolchains and CI scripts inside docker which may build electron modules without DISPLAY and only provide DISPLAY for testing or at runtime. The resulting errors may be hard to interpret, example:

~~~~
node-gyp --target=`electron --version` ...
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://atom.io/download/electron/v4.2.6/node-v4.2.6-headers.tar.gz
~~~~

Here, node-gyp picked up the wrong version inside a dockerized CI build, because --target="\`electron --version\`" essentially resulted in `--target=""`, since DISPLAY is unset inside a travis-ci docker.

**Comment by zcbenz** [comment] 2017-06-12 08:31
You can search past issues for why logging is disabled by default, closing since it is expected behavior and there is workaround to solve this.

**Closed by zcbenz** 2017-06-12 08:31 UTC
Labels: enhancement, help/beginner, platform/linux
