### ISSUE TITLE
Pepper Flash play rtmp is not work

### ISSUE THREAD

**Issue by PlutoCA** [electron/electron#18824] opened 2019-06-16 04:20 UTC
this is navigator.plugins console
![image](https://user-images.githubusercontent.com/31099607/59558885-cb95d380-902e-11e9-97d2-2d3901eccd41.png)
main.js
![image](https://user-images.githubusercontent.com/31099607/59558972-81aded00-9030-11e9-896c-5ee82e0ad9bf.png)
I use video.js flash play http://rtmp
The player didn't load the screen and didn't do anything. I tried to play it manually and it didn't work, and there was no error.

What should I do to solve this situation? Thank you.

**Comment by PlutoCA** [comment] 2019-06-16 04:22
`
"electron": "^5.0.3",
"electron-packager": "^13.1.1",
`

**Comment by coreybruce** [comment] 2019-07-03 03:03
Same issue with Electron 5.0.9

**Comment by 18124772589** [comment] 2019-07-11 07:43
"electron": "^2.0.4" "electron-builder": "^20.19.2" 在开发环境播放rtmp正常，打包后也是无法播放，显示无法加载插件，用nw-flash-trust只能对本地的.swf授权，项目里是远程的.swf, 这都没有解决方案吗？难道在electron里真的就无法播放rtmp？

**Comment by 18124772589** [comment] 2019-07-11 07:44
RTMP playback is normal in the development environment, and cannot be played after packaging. Plug-in cannot be displayed, and nw-flash-trust can only be used for local. SWF authorization, which is remote in the project. Couldn't RTMP really be played in electron?

**Comment by coreybruce** [comment] 2019-09-15 10:04
Has there been any progress at all with a fix? I'm currently holding back a application to 4.6.2 because of this issue but I really want to move to a newer version and have this issue resolved.

**Comment by raochoar** [comment] 2019-09-20 17:28
Any news regarding this? It appears to work on windows but not in linux.

**Comment by coreybruce** [comment] 2019-09-21 08:59
Which still means its not completely working, having it only work on one OS and not all when it worked on both in the past means the bug is still there and should be fixed.

**Comment by manman0512** [comment] 2019-10-10 03:29
May I ask if your problem has been solved? I have the same problem. I hope you will let me know. Thank you.

**Comment by manman0512** [comment] 2019-10-10 03:30
> RTMP播放在开发环境中是正常的，打包后无法播放。无法显示插件，并且nw-flash-trust仅可用于本地。SWF授权，在项目中是远程的。RTMP真的不能在电子中播放吗？

May I ask if your problem has been solved? I have the same problem. I hope you will let me know. Thank you.

**Comment by coreybruce** [comment] 2019-10-10 03:32
Sorry the issue has not yet been fixed :(

**Comment by ncodeyx** [comment] 2019-10-20 17:00
This issue appears in Electron 6.0.0+ as well. Flash Player cannot be played at all.

**Comment by spl237** [comment] 2019-11-06 14:19
I'm seeing this issue as well - attempting to load PepperFlash player in either electron v5 or v6 (Linux, ARMv7) causes a failure to load the plugin. I can run Flash on Electron 4, but not on any version later than that.

**Comment by raochoar** [comment] 2020-02-06 15:40
Could someone add more labels to this issue? is affecting all versions after 4. thanks

**Comment by coreybruce** [comment] 2020-02-17 05:10
The issue is due to sandboxing in newer versions, there was a line of code you could add but it wouldn't be recommended for security reasons.

**Comment by raochoar** [comment] 2020-02-17 21:34
So there is a workaround to make it work? it is a setting?

**Comment by coreybruce** [comment] 2020-02-18 02:24
Yes but isn't safe nor secure and I wouldn't recommend it, the issue itself needs to be fixed by the Electron team

**Comment by koush** [comment] 2020-04-28 07:57
I can confirm that this issue is causing all plugins to fail to load on Linux. Windows and Mac plugins work fine. Took several hours to track this down. The plugin ostensibly is loaded according to navigator.plugins, but does not actually load. Nothing showed up in strace either. Here is the workaround:

```js
// in the main thread, run as soon as possible.
app.commandLine.appendSwitch('--no-sandbox')
```

**Comment by caperso** [comment] 2020-11-03 02:42
> So there is a workaround to make it work? it is a setting?

there is a way to build a express-ws server in main process .

then using flunt-ffmpeg handle the rtmp/rtsp stream and export with ws.

renderer side using flv.js to play ws stream

BUT latency might up to 10 seconds

**Comment by electron-triage** [comment] 2021-03-08 23:16
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-08 23:16 UTC
Labels: 5-0-x, 6-1-x
