### ISSUE TITLE
[Bug]:  Broken link

### ISSUE THREAD

**Issue by tinubaby** [electron/electron#32142] opened 2021-12-09 20:00 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows10

### What arch are you using?

x64

### Last Known Working Electron version

11.1.0

### Expected Behavior

It should open up the github respository, to edit that page.

### Actual Behavior

Showing up 404 Error page

**Comment by Kilian** [comment] 2021-12-14 14:36
Please add more information. _what_ link is broken, and _where_ is it located?

**Comment by Kilian** [comment] 2021-12-14 14:47
closing as duplicate of #32122

**Closed by Kilian** 2021-12-14 14:47 UTC
Labels: blocked/need-info ❌, bug :beetle:
