### ISSUE TITLE
GL Context Issues in addon

### ISSUE THREAD

**Issue by tyduptyler13** [electron/electron#8848] opened 2017-03-06 22:06 UTC
* Electron version: 1.6.1
* Operating system: Linux

### Expected behavior

I have created a nodejs addon that works inside electron as well. When running against nodejs I can
create a GLFW window with a GLES2 context and use it as expected. When running against electron, a GLFW window is created, the context briefly exists, then as soon as I call a GL function, it behaves as if the context is gone. glGetString(GL_VERSION) returns null immediately after creating the window, and after explicitly making the context current. glGetError also returns 0.

This worked previously just fine in v1.4.15.

### How to reproduce

This requires that GLFW3, Electron, and node-gyp are installed on the system.

The build script is also hard coded to build for electron 1.6.1.

```
git clone https://github.com/MyUPlay/MyEngine
cd MyEngine
make -j8
electron test/core/BasicExample-electron.js
```

To prove the code works otherwise (from inside the repo):
```
NODEBUILD=1 make -j8
node test/core/BasicExample.js
```
The js has to be different, obviously, so that it doesn't call electron to do the UI, which should be the only difference.

**Comment by tyduptyler13** [comment] 2017-03-15 19:41
Tested in electron 1.6.2 and the issue still exists.

Using a forced downgrade to 1.4.15 until resolved.

**Comment by zcbenz** [comment] 2017-06-13 09:55
This is very likely related to how Chromium initializes OpenGL, I believe your module is affected by some global states set by Chromium.

I'm closing this because it is an issue of Chromium's GPU rendering, and none of us in Electron team is familiar with that part of code enough to be able to fix this. A pull request to fix it would be welcomed.

**Closed by zcbenz** 2017-06-13 09:55 UTC

**Comment by tyduptyler13** [comment] 2017-06-20 00:21
I decided to solve this using IPC instead. Its not the prettiest solution, but it will work and will mean I can change dependencies on a whim.

**Comment by alexlitty** [comment] 2017-09-05 01:15
I submitted [an issue with Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=761858) to get their opinion on the matter. I too suspect this is within Chromium's territory, maybe they can provide deeper insight on the problem's origins.

I'd like to personally pursue this if we can find a reasonable root cause. I see many amazing use-cases if we can get this working.

**Comment by tyduptyler13** [comment] 2017-09-05 16:30
@alexlitty I would have to definitely agree. I was developing a very lightweight game engine and was using electron/node as the UI and launcher. This was particularly nice since I was using javascript as the runtime scripting language. The project is currently on hold as my job is consuming most of my time but if I ever return to it, it would be really nice to be able to use the latest Electron versions again and avoid IPC if I can.

**Comment by ihnorton** [comment] 2018-02-02 15:03
Related: https://discuss.atom.io/t/get-hwnd-or-window-handle-from-electron-for-directx-opengl/18418 (no resolution there, though. user eventually switched to Qt)

**Comment by alexlitty** [comment] 2018-02-02 22:00
@zcbenz The Chromium team [answered us a little while ago](https://bugs.chromium.org/p/chromium/issues/detail?id=761858#c4) suggesting:

>I don't think there is anything actionable from the Chromium side here.

piman's thoughts about the same-process GL bindings is accurate, but Electron separates the rendering process from the browser process -- I would imagine only _one_ of those processes is unsafe to run independent GL code in.

Theoretically I'd think we should be able to run GL code in the browser process. Any thoughts?
