### ISSUE TITLE
Feature Request: comprehensively hide devtools

### ISSUE THREAD

**Issue by pjebs** [electron/electron#12769] opened 2018-05-01 20:33 UTC
Can the documentation clearly state how to comprehensively prevent the user from accessing the dev tools.

remove from top menu
remove toggle code when app starts up so it's initially hidden
What else must I do? Perhaps this should be in the documentation.
I read in a few places about handling the --remote-debugging-port command line argument. I read that if it exists, the app should just immediately exit.

There might be some other ways that the user can access it. What are they? It would be great if the documentation stated it for security reasons.

**Comment by ckerr** [comment] 2018-05-01 23:38
This is a duplicate of issue #12748.

As stated there, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/) -- indeed, the first hit when Googling for "Electron hide devtools" is a [discussion in the Atom forums](https://discuss.atom.io/t/a-way-to-prevent-developer-tools/29746/8), so it's likely that the people there may be able to answer your questions.

**Closed by ckerr** 2018-05-01 23:38 UTC
