### ISSUE TITLE
Window transparency bug in 1.5

### ISSUE THREAD

**Issue by jas99** [electron/electron#8532] opened 2017-01-30 03:37 UTC
* Electron version: 1.5.x
* Operating system: mint 18.1

### Expected behavior

Window transparency with --enable-transparent-visuals is supposed to produce see thru window

### Actual behavior
Window produce black background with old frames not disposing

### How to reproduce

Use 1.5.x version; **works well with 1.4.x version**

**Comment by zeke** [comment] 2017-02-09 00:26
@jas99 can you try `npm install electron@beta --save-dev` (which is currently 1.6 with a newer version of Chromium), and let us know if the problem persists?

**Comment by sidneys** [comment] 2017-02-27 01:36
Electron: 1.4.15
OS: Ubuntu 16.10

@zeke @jas99 
I have the same exact problem, no transparency, and no frames disposing.

**Comment by optimisme** [comment] 2017-04-10 09:12
Is this a duplicate of https://github.com/electron/electron/issues/2170?

**Comment by samkelly** [comment] 2017-04-17 16:04
OS: Ubuntu 16.04
Electron: 1.4.15

exact problem as people above, issue starts with 1.4.15 (works in 14)

**Comment by wmin0** [comment] 2017-05-11 08:13
Chromium has remove --enable-transparent-visuals and check your gpu automatically.
It seems there is no way forcing to set rgba visual

https://chromium.googlesource.com/chromium/src/+/71b2517dd4cd620a56ca6f13571129c6aee30b42%5E%21/
https://chromium.googlesource.com/chromium/src/+/62ba78ffcdf525eb9ed640724e640fcf22fbbf87%5E%21/

**Comment by sam0x17** [comment] 2017-05-12 01:28
@wmin0 thanks for the heads up

This is a very serious issue for us, as our entire UI is translucent.

**Comment by zcbenz** [comment] 2017-06-06 05:08
Transparent window is not officially supported in Chromium, so you have to take your own risks when using it. While we would like to fix it, none of us is familiar with Chromium's GPU rendering enough to be able to solve this. So I'm closing this as won't fix.

**Closed by zcbenz** 2017-06-06 05:08 UTC
Labels: more-information-needed
