### ISSUE TITLE
v11: no method completion in the renderer devtools console

### ISSUE THREAD

**Issue by bughit** [electron/electron#25783] opened 2020-10-05 22:32 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.0.0-beta.9 x86
* **Operating System:**
  * win7 sp1 x64
* **Last Known Working Electron version:**
  * v10.1.3 x86

### To Reproduce
- run electron (default app)
- ctrl-shift-i for devtools
- type `window.`
- no method suggestions

**Comment by nornagon** [comment] 2020-10-05 22:33
Probably related to #25778.

**Comment by nornagon** [comment] 2020-10-05 22:37
Confirmed that #25780 fixes this. Closing this as a duplicate of #25778.

**Closed by nornagon** 2020-10-05 22:37 UTC
