### ISSUE TITLE
Reloading webContents will close opened windows.

### ISSUE THREAD

**Issue by WhiteFur** [electron/electron#10624] opened 2017-09-27 08:24 UTC
* Electron version: 1.7.8
* Operating system: macOS sierra,  windows7, windows10

### Expected behavior

Refreshing the page does not effect other opened windows.

### Actual behavior

Refreshing the page will close other windows.

### How to reproduce

Open a new BrowserWindow and refresh the main window then the opened BrowserWindow is closed.

**Comment by cuixiping** [comment] 2018-07-26 01:15
duplicate with #10546

**Comment by MarshallOfSound** [comment] 2018-07-26 06:01
Duplicate of #10546

**Closed by MarshallOfSound** 2018-07-26 06:01 UTC
Labels: bug :beetle:, platform/macOS, platform/windows, version/1.7.x
