### ISSUE TITLE
macOS: Electron crashes if NEXT_ROOT is set

### ISSUE THREAD

**Issue by bpasero** [electron/electron#20477] opened 2019-10-08 07:29 UTC
### Issue Details

* **Electron Version:**
  * 6.x
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**
  * none

### Expected Behavior
Electron does not crash when starting from terminal while `NEXT_ROOT` is defined.

### Actual Behavior
Electron crashes.

### To Reproduce
* `export NEXT_ROOT=1`
* start Electron

**Comment by electron-triage** [comment] 2021-03-09 03:37
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by bpasero** [comment] 2021-03-10 06:09
@electron-triage @nornagon @codebytere @sofianguy @samuelmaddock this reproduces in Electron 11 still.

**Comment by nornagon** [comment] 2021-03-10 19:32
Stack trace:

```
0   Electron Framework                  0x000000010fc16e49 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x000000010fb33343 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework                  0x000000010fc16d71 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 2385
3   libsystem_platform.dylib            0x00007fff6f6d55fd _sigtramp + 29
4   ???                                 0x00007fb70dd1c500 0x0 + 140424187593984
5   AppKit                              0x00007fff32abf256 -[NSApplication reportException:] + 901
6   AppKit                              0x00007fff32b6ed8d uncaughtErrorProc + 145
7   CoreFoundation                      0x00007fff3556193c __handleUncaughtException + 726
8   libobjc.A.dylib                     0x00007fff6e3365a3 _objc_terminate() + 90
9   libc++abi.dylib                     0x00007fff6c809887 std::__terminate(void (*)()) + 8
10  libc++abi.dylib                     0x00007fff6c809829 std::terminate() + 41
11  libdispatch.dylib                   0x00007fff6f48366c _dispatch_client_callout + 28
12  libdispatch.dylib                   0x00007fff6f4847de _dispatch_once_callout + 20
13  AppKit                              0x00007fff326a3fda +[NSAppearance _initializeCoreUI] + 35
14  AppKit                              0x00007fff326c937d +[NSAppearance _aquaAppearance] + 51
15  AppKit                              0x00007fff326a3964 +[NSAppearance appearanceNamed:] + 21
16  AppKit                              0x00007fff326a36b3 _NSAppearanceCurrentSystemAppearance + 178
17  AppKit                              0x00007fff326a3486 -[NSSystemAppearanceProxy init] + 81
18  AppKit                              0x00007fff326a342c __38+[NSSystemAppearanceProxy systemProxy]_block_invoke + 24
19  libdispatch.dylib                   0x00007fff6f483658 _dispatch_client_callout + 8
20  libdispatch.dylib                   0x00007fff6f4847de _dispatch_once_callout + 20
21  AppKit                              0x00007fff326a3412 +[NSSystemAppearanceProxy systemProxy] + 42
22  AppKit                              0x00007fff326a33be -[NSApplication(NSApplicationAppearance_Internal) _registerForAppearanceNotifications] + 34
23  AppKit                              0x00007fff326a0ee5 -[NSApplication init] + 669
24  AppKit                              0x00007fff326a09e9 +[NSApplication sharedApplication] + 123
25  Electron Framework                  0x000000010b4a16d7 +[AtomApplication sharedApplication] + 39
26  Electron Framework                  0x000000010cb40e6f content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams&, bool) + 175
27  Electron Framework                  0x000000010cb40d8f content::ContentMainRunnerImpl::Run(bool) + 495
28  Electron Framework                  0x000000010cb3faf6 content::RunContentProcess(content::ContentMainParams const&, content::ContentMainRunner*) + 2630
29  Electron Framework                  0x000000010cb3fbcd content::ContentMain(content::ContentMainParams const&) + 29
30  Electron Framework                  0x000000010b2a79b9 ElectronMain + 137
31  Electron                            0x00000001093cadea main + 298
32  libdyld.dylib                       0x00007fff6f4dccc9 start + 1
33  ???                                 0x0000000000000001 0x0 + 1
[end of stack trace]
```

**Comment by nornagon** [comment] 2021-03-10 19:35
This looks like a macOS bug. I can reproduce this in non-Electron apps too, e.g. here's MacVim crashing:


```
$ NEXT_ROOT=1 /Applications/MacVim.app/Contents/MacOS/macvim
2021-03-10 11:34:48.241 macvim[30556:29121454] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Critical error: required built-in appearance SystemAppearance not found'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff354e8b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6e3345bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff354e89b5 +[NSException raise:format:] + 189
	3   libdispatch.dylib                   0x00007fff6f483658 _dispatch_client_callout + 8
	4   libdispatch.dylib                   0x00007fff6f4847de _dispatch_once_callout + 20
	5   AppKit                              0x00007fff326a3fda +[NSAppearance _initializeCoreUI] + 35
	6   AppKit                              0x00007fff326c937d +[NSAppearance _aquaAppearance] + 51
	7   AppKit                              0x00007fff326a3964 +[NSAppearance appearanceNamed:] + 21
	8   AppKit                              0x00007fff326a36b3 _NSAppearanceCurrentSystemAppearance + 178
	9   AppKit                              0x00007fff326a3486 -[NSSystemAppearanceProxy init] + 81
	10  AppKit                              0x00007fff326a342c __38+[NSSystemAppearanceProxy systemProxy]_block_invoke + 24
	11  libdispatch.dylib                   0x00007fff6f483658 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00007fff6f4847de _dispatch_once_callout + 20
	13  AppKit                              0x00007fff326a3412 +[NSSystemAppearanceProxy systemProxy] + 42
	14  AppKit                              0x00007fff326a33be -[NSApplication(NSApplicationAppearance_Internal) _registerForAppearanceNotifications] + 34
	15  AppKit                              0x00007fff326a0ee5 -[NSApplication init] + 669
	16  AppKit                              0x00007fff326a09e9 +[NSApplication sharedApplication] + 123
	17  AppKit                              0x00007fff3269f1fb NSApplicationMain + 366
	18  libdyld.dylib                       0x00007fff6f4dccc9 start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
zsh: abort      NEXT_ROOT=1 /Applications/MacVim.app/Contents/MacOS/macvim
```

Closing this as wontfix.

**Closed by nornagon** 2021-03-10 19:35 UTC
Labels: 11-x-y, 6-1-x, bug/crash :boom:, platform/macOS, status/wontfix 🚫
