### ISSUE TITLE
I can't open the chrome://flags page in Electron

### ISSUE THREAD

**Issue by jdwalker** [electron/electron#22209] opened 2020-02-15 20:58 UTC
## Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I am looking at developing an XR app now Chromium updated to version 80 - however in order to make it work with Windows and  SteamVR in chrome, I need to disable the XR sandbox via chrome://flags. I would normally use [a command line switch for this except one does not exist](https://peter.sh/experiments/chromium-command-line-switches/).

Instead I am thinking of prompting the user to open the chrome://flags page and disable the XR 
 sandbox, however when I try to open it, it redirects me to "chrome-error://chromewebdata/"

* **Electron Version:**
  * 8.0.0
* **Operating System:**
  * Windows 10 x64 Build 18362

### Expected Behavior
I can open "chrome://flags" using mainWindow.loadURL 

### Actual Behavior
It redirects me to  "chrome-error://chromewebdata/"

### To Reproduce
Please see the following electron fiddle: https://gist.github.com/459df8fd3c113acb2daadd0e7287afb3

**Comment by codebytere** [comment] 2020-02-15 23:20
Duplicate of https://github.com/electron/electron/issues/22120.

**Closed by codebytere** 2020-02-15 23:20 UTC

**Comment by ThaUnknown** [comment] 2024-11-29 21:33
for anyone wanting to enable arbirtary flags they test on other browsers, open `about://version/` in your browser of choice, there inside `Command Line` you'll find for example: `--flag-switches-begin --enable-experimental-web-platform-features --enable-features=FileSystemAccessAPI,FluentOverlayScrollbar,WindowsScrollingPersonality --flag-switches-end` as I have enabled: ![Image](https://github.com/user-attachments/assets/e8fb8593-1fda-4591-9e89-8c404a382b23)
in my browser

some switches are part of `--enable-features`, some arent such as experimental web platform features, safest bet to enable these is:
```js
import { app } from 'electron'
app.commandLine.appendSwitch(flag, value)
```
but
```js
new BrowserWindow({
    webPreferences: {
      enableBlinkFeatures: 'FluentOverlayScrollbar, WindowsScrollingPersonality'
    }
  })
```
seems to work as well?

enjoy
