### ISSUE TITLE
file:// protocol will block loading local resources

### ISSUE THREAD

**Issue by dingchaoyan1983** [electron/electron#12608] opened 2018-04-13 01:24 UTC
the `file://` protocol will block the sixth request when load the local source files
![wechatimg29](https://user-images.githubusercontent.com/7593506/38712119-320831ce-3efc-11e8-82be-e035d56bf460.jpeg)

**Comment by MarshallOfSound** [comment] 2018-04-13 01:52
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.  In particular the "How to reproduce" section is critical for us to find the issue, providing a cloneable example is the best way to do this.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by sofianguy** [comment] 2018-04-23 17:35
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/12608#issuecomment-380996337). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2018-04-23 17:35 UTC
Labels: blocked/need-info
