### ISSUE TITLE
Can I make non global accelerators without putting things in a menu?

### ISSUE THREAD

**Issue by maxkorp** [electron/electron#1334] opened 2015-03-30 16:39 UTC
I'd like to add some hotkeys for events in my app, and accelerators seem like the natural way to do that, but some of these things don't make sense in a menu. Is there a way to use accelerators without registering a global shortcut or a menu? I'd rather not have hidden menus.

**Comment by paulcbetts** [comment] 2015-03-30 17:48
https://github.com/atom/atom-shell/blob/master/docs/api/global-shortcut.md

**Comment by paulcbetts** [comment] 2015-03-30 17:48
@maxkorp You can capture key shortcuts via `keyup` on document.

**Comment by maxkorp** [comment] 2015-03-30 17:53
Yeah, I was just hoping to use some of the super nice `'CmdOrCtrl+X'` type declarations Accelerators offer, rather than using keycodes etc. Digging around to see if theres a way I can instantiate an accelerator manually and manipulate that.

**Comment by maxkorp** [comment] 2015-03-30 17:58
Note: Title of the issue was meant to be NON global, not on global.

**Comment by paulcbetts** [comment] 2015-03-30 18:18
I'd buy that feature actually, because one of our biggest bugs right now is trying to deal with the non-US keyboard web debacle in Chrome; even when you know the keyboard layout you still have to have a massive list of tables

**Comment by maxkorp** [comment] 2015-03-30 18:25
As far as I can tell, theres no way currently on the js side to access the accelerator class. I'll take a look at enabling that, but I'm not familiar enough with the code to give a real opinion. From what I see, i'd need to add something in atom/browser/api, then add it to the bindings as well. That seem roughly correct-ish?

**Comment by paulcbetts** [comment] 2015-03-30 18:26
@maxkorp Yeah, classes get automatically bound via this framework called `mate` but I don't understand much about it :(

**Comment by maxkorp** [comment] 2015-03-30 18:29
Hrm, I'll take a crack at it. No clue if being able to instantiate an accelerator would help, even, but it's worth a shot.

**Comment by maxkorp** [comment] 2015-03-30 22:02
Hrm, unfortunately a little more complex than I'd hoped but I have a plan of attack. IMO, 2 separate features would be good, and I'd be happy to start at them if you guys think they're good ideas.
1) It would be nice to be able to just pass a key[up/down/press] event and an accelerator to a function and see if it lines up. I'd probably start here. 

2) Create a LocalShortcutHandler setup, akin to globalshortcuthandler. This needs to be either enableable or disableable (using its own version of `GlobalShortcutListener::SetShortcutHandlingSuspended` that respects observers), or it needs to automatically enable/disable based on some sort of window focus. Any thoughts?

**Comment by maxkorp** [comment] 2015-03-31 16:56
FYI: I have a temporary workaround, where I set up a small helper with a map that stores shortcuts by keystroke (and in my case, by some other stuff dependent on my apps architecture). Whenever a window focuses, all of the shortcuts are registered. Whenever a window blurs, it checks if any window has focus, and if one does, it leaves them enabled. If no window has focus anymore, then the shortcuts are unregistered.  Clearly, that could be tweaked to work on a per window basis, etc, to fit someones needs. 

Does anyone have any opinion on how they'd like to see that implemented in atom shell? I'm still leaning towards putting something in API, but I might put a compatible js/coffee solution in first, then move over to the native way next. 

My thoughts are as follows: 
Local shortcuts can be cross window, or per window (so they are only active if a specific window has focus, or any window has focus). 
```js
// This is global, if any window in the app is focused it works
LocalShortcut.register(accelerator, callback);

// This is only active if someWindow has focus
LocalShortcut.register(accelerator, callback, someWindow);
```

**Comment by zcbenz** [comment] 2015-04-01 03:19
The accelerators are handled natively in `NativeWindow::HandleKeyboardEvent`, it is easy to provide a API on Linux/Windows since we handle accelerators registration/activation completely on atom-shell's side, however on OS X it would need much more work because we currently rely on application menu to do the accelerator stuff.

A js/coffee solution sounds good to me, but we should probably make it a third party module instead of being in atom-shell core.

**Comment by etiktin** [comment] 2015-08-19 20:12
@maxkorp, did you end up publishing a module for this?

**Comment by maxkorp** [comment] 2015-08-20 21:08
Unfortunately no. I have some ideas, but I haven't had time.

**Comment by zcbenz** [comment] 2015-08-24 04:04
For people looking at this issue, most of you can just use a JavaScript library like https://github.com/atom/atom-keymap or https://craig.is/killing/mice.

**Comment by paulcbetts** [comment] 2015-08-24 21:55
This solution is gonna be a real bummer with international keyboards though until https://code.google.com/p/chromium/issues/detail?id=227231 lands in Elecron

**Comment by sindresorhus** [comment] 2015-09-15 06:50
:+1: In my app, I need to do something when a shortcut combination is triggered, but only when my app is focused. Currently, I use global shortcuts and [subscribe/unsubscribe](https://github.com/sindresorhus/electron-debug/blob/e5ae265a958b71d2a544ab3b0d093ff50e2b8d87/index.js#L26-L38) depending on whether the window is focused, but support for local shortcuts would be much better.

**Comment by maxkorp** [comment] 2015-09-17 20:41
@sindresorhus has that been working consistantly for you? I was having issues with those events not firing when switching was caused by electon itself, for example by the dev tools getting focused by a breakpoint.

**Comment by frankhale** [comment] 2015-09-17 20:45
I'm using keymaster in my app to declare key combos and events to execute when they are pressed. It seems to be enough for my needs. Maybe it can work for you?

https://github.com/madrobby/keymaster

**Comment by sindresorhus** [comment] 2015-09-18 04:22
> has that been working consistantly for you?

Yes, but I just started using it.

> I was having issues with those events not firing when switching was caused by electon itself, for example by the dev tools getting focused by a breakpoint.

Create a minimal testcase and open a new issue.

**Comment by lipis** [comment] 2015-09-28 13:01
How is that issue going.. how soon do you think we'll be able to use accelerators without the menu?

**Comment by parro-it** [comment] 2015-11-03 21:59
I published a module to handle local window shortcuts. 
It is actually a lightway wrapper around globalshortcuts that register/unregister all window shortcuts on focus/blur. 
In case it can help you, it's published [here](https://github.com/parro-it/electron-localshortcut).

**Comment by feross** [comment] 2016-06-06 02:38
@parro-it Thanks for `electron-localshortcut`. It was useful to us, but we had to remove it after all from WebTorrent Desktop because it's too aggressive at capturing keys that are included in global OS shortcuts. See: https://github.com/feross/webtorrent-desktop/issues/585

Menu item accelerators don't have that issue, so there's still a need for this issue to be fixed.

**Comment by parro-it** [comment] 2016-06-06 07:02
@feross You're welcome. I agree with you that a native solution would be ideal. Anyway, I read the issue you linked and I can't guess what could be the cause, since `electron-localshortcut` is already removing shortcut registration when your window loose focus. 
Had you do further investigation on the issue?

**Comment by paulcbetts** [comment] 2016-06-06 07:10
Silly question - now that `key` and `code` are in Chrome 51, you should be able to just capture `keyup` and correctly detect the key even with non-US keyboard layouts

**Comment by feross** [comment] 2016-06-07 02:15
@parro-it The issue with `electron-localshortcut` is when the window actually *has* focus. If you listen for the `Esc` key, then click an menu item on OS X (for example), then `Esc` won't work for de-focusing it. It's subtle.

@paulcbetts You're right.

**Comment by parro-it** [comment] 2016-06-07 05:26
Oh yes I didn' t check but that is for sure because that action doesn' t trigger lostfocus event on browserwindow instance.
I think there is no easy solution to the problem...

**Comment by pmario** [comment] 2017-01-23 12:39
Any news on this one?

**Comment by connorbode** [comment] 2017-02-01 17:42
@pmario I just solved it as follows:

```
const {app, BrowserWindow, globalShortcut} = require('electron')

function registerShortcuts () {
  globalShortcut.register(..)
}

function unregisterShortcuts () {
  globalShortcut.unregister(..)
}

app.on('ready', () => {
  win = new BrowserWindow({ .. })
  win.on('focus', registerShortcuts)
  win.on('blur', unregisterShortcuts)
})
```

I only use one window but it can be modified for multiple to check if at least one window is still in focus.

**Comment by poiru** [comment] 2017-06-25 18:56
You can use [`before-input-event`](https://electron.atom.io/docs/api/web-contents/#event-before-input-event) to catch and handle custom shortcuts that are not visible in the menu. If you want to attach it to all web contents, use something like:

```js
app.on('web-contents-created', function (event, wc) {
  wc.on('before-input-event', function (event, input) {
    if (input.key === 'x' && input.ctrl && !input.alt && !input.meta && !input.shift) {
      // Do something for Ctrl-X
      event.preventDefault()
    }
  })
})
```

@parro-it `electron-localshortcut` should probably use the approach above.

**Comment by codebytere** [comment] 2018-09-24 03:43
Given the workarounds above, we believe this module is better implemented in userland (ex. the excellent [electron-localshortcut](https://github.com/parro-it/electron-localshortcut) and thus i'm going to label this a `wontfix`.

**Closed by codebytere** 2018-09-24 03:43 UTC
Labels: component/menu, enhancement :sparkles:

**Comment by omeid** [comment] 2019-03-22 00:51
I think there is good value in having a consistent API for shortcuts inline with Menu Accelerators and GlobalShortcuts.

**Comment by madprops** [comment] 2019-06-06 09:01
This should be implemented. Most of the time you'd want local shortcuts. Making event listeners on BrowserWindows don't work if there are webviews in use that capture focus. And even if creating a menu worked it makes no sense that a menu has to be created to enable keyboard shortcuts (which are a very core feature of most applications).

**Comment by Praveer1981** [comment] 2020-01-07 06:54
@poiru  

> You can use [`before-input-event`](https://electron.atom.io/docs/api/web-contents/#event-before-input-event) to catch and handle custom shortcuts that are not visible in the menu. If you want to attach it to all web contents, use something like:
> 
> ```js
> app.on('web-contents-created', function (event, wc) {
>   wc.on('before-input-event', function (event, input) {
>     if (input.key === 'x' && input.ctrl && !input.alt && !input.meta && !input.shift) {
>       // Do something for Ctrl-X
>       event.preventDefault()
>     }
>   })
> })
> ```
> 
> @parro-it `electron-localshortcut` should probably use the above approach.

Unfortunately, It did not work for me. It never allows me to press `Ctrl+x` key.

**Comment by JayCasee** [comment] 2020-06-27 08:54
Just for someone who may have a same problem like me in 2020...

```
BrowserWindow.getFocusedWindow()
```

This returns the current focused BrowserWindow object.

```
globalShortcut.register( 'F11', () => {
  BrowserWindow.getFocusedWindow().setFullScreen( ! BrowserWindow.getFocusedWindow().isFullScreen() )
} )
```

E.g. I could make a full screen shortcut as the above way.

**Comment by aleksey-hoffman** [comment] 2020-10-25 01:38
Here's a working flexible solution that allows you to manually set the shortcuts that gets removed when you disable the app Menu (or if you just want to overwrite them):

```js
app.on('web-contents-created', (webContentsCreatedEvent, webContents) => {
  webContents.on('before-input-event', (beforeInputEvent, input) => {
    // console.log('Main console::', input)
    const { code, alt, control, shift, meta } = input
    // Shortcut: toggle devTools
    if (shift && control && !alt && !meta && code === 'KeyI') {
      beforeInputEvent.preventDefault()
      BrowserWindow.getFocusedWindow().webContents.toggleDevTools({ mode: 'detach' }) 
    }
  })
})
```

**Comment by aleksey-hoffman** [comment] 2020-10-25 01:43
Here's a working flexible solution that allows you to manually re-define the shortcuts like `toggleDevTools` which get removed when you disable the app Menu:

```js
app.on('web-contents-created', (webContentsCreatedEvent, webContents) => {
  webContents.on('before-input-event', (beforeInputEvent, input) => {
    // console.log('Main console::', input)
    const { code, alt, control, shift, meta } = input
    // Shortcut: toggle devTools
    if (shift && control && !alt && !meta && code === 'KeyI') {
      beforeInputEvent.preventDefault()
      BrowserWindow.getFocusedWindow().webContents.toggleDevTools({ mode: 'detach' }) 
    }
  })
})
```

**Comment by eterzago** [comment] 2020-12-16 10:41
Wouldn't a native solution be infinitely better than any hacky workaround? As another user said, keyboard shortcuts _are_ a core feature of most applications...

**Comment by parro-it** [comment] 2020-12-16 12:55
> Edit: Also what this guy says about how registering/unregistering globalShortcuts on focus/blur (which is what electron-localshortcut does) leads to unwanted behaviors.

By the way, the current version of electron-localshortcut does not register globalShortcuts
but listen to a keyboard event on the BrowserWindow instance. It's not an hack anymore!

**Comment by eterzago** [comment] 2020-12-16 13:11
@parro-it  That's great to know, thanks for pointing it out!

**Comment by mlrv** [comment] 2020-12-24 15:22
For anyone interested in this issue, I just published [electron-shortcuts](https://www.npmjs.com/package/electron-shortcuts). I needed a safe solution to local shortcuts and decided to put something together, which ended up becoming a tiny, safety-focused npm library 😄 

It's definitely still early stage, so contributions and feedback of any kind are definitely welcome!
