### ISSUE TITLE
[Feature Request]: Create bookmarks from header titles in source file with printToPDF function

### ISSUE THREAD

**Issue by phirestalker** [electron/electron#32288] opened 2021-12-26 20:10 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The PDFs generated with printToPDF function do not create bookmarks from H1 - H4 headers. I use a project called Joplin for my note taking. When it generates PDFs it does not create bookmarks automatically from the outline (headers). I was told that they use the printToPDF function in electron.

### Proposed Solution

Functionality, maybe optional with a flag, to generate bookmarks from the headers of the source document be added to the printToPDF function.

### Alternatives Considered

I am not sure of any alternatives.

**Comment by codebytere** [comment] 2022-01-03 10:39
@phirestalker please add a title to this issue.

**Comment by codebytere** [comment] 2022-01-10 13:56
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by 0lelouch** [comment] 2022-02-04 16:33
This will be a very useful feature.

**Comment by nornagon** [comment] 2022-02-04 18:40
This seems like an upstream issue. We only invoke the Chrome print functionality; if Chrome doesn't support this then it's outside of the scope of the Electron project to add it.

As a test, I tried printing that page to a PDF from Chrome, and it also did not contain any bookmarks.

**Closed by nornagon** 2022-02-04 18:40 UTC
Labels: enhancement :sparkles:, status/confirmed, blocked/need-repro, has-repro-gist
