### ISSUE TITLE
I opened a new subpage with window. open, named newPage.But in the electron-packaged exe, I couldn't read the name of the subpage and I can get it in Google browser.

### ISSUE THREAD

**Issue by lQei** [electron/electron#15047] opened 2018-10-10 07:07 UTC
* Output of `node_modules/.bin/electron --version`:3.0.0
* Operating System (Platform and Version):win10 64bit
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):3.0.0

**Expected Behavior**
I opened a new subpage with window. open, named newPage. I want to  read the name of the subpage in the electron-packaged exe.

**Actual behavior**
I opened a new subpage with window. open, named newPage.But in the electron-packaged exe, I couldn't read the name of the subpage and I can get it in Google browser.

**To Reproduce**
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    <button onClick="newpage()">newpage</button>
    
    We are using Node.js <script>document.write(process.versions.node)</script>,
    Chromium <script>document.write(process.versions.chrome)</script>,
    and Electron <script>document.write(process.versions.electron)</script>.

    <script>
      alert(name);//there get the subpage name
      require('./renderer.js')
      function newpage(){
        var newpage = window.open("index.html","newPage");
      }
    </script>
  </body>
</html>

**Screenshots**
![image](https://user-images.githubusercontent.com/20189143/46723794-3b3b0e00-ccab-11e8-8726-18235e6218fc.png)

**Additional Information**

**Comment by MarshallOfSound** [comment] 2018-10-10 08:12
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by sofianguy** [comment] 2019-08-09 22:47
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:15
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:15 UTC
Labels: 3-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
