### ISSUE TITLE
Some MenuItem roles are not behaving correctly when `Option` key is pressed on macOS

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#17120] opened 2019-02-25 17:05 UTC
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 5.0.0-beta.3 and 4.0.5
* **Operating System** (Platform and Version):
  * macOS 10.14.3

### Expected Behavior

On macOS with native apps, if I press <kbd>Option</kbd> while a menu is open, the `MenuItem`s change their label and action. I expect this to happen for Electron's `role` `MenuItem`s too.

For example, for the roles `minimize`, `zoom`, and `front`, this is how they look like normally:

<img width="229" alt="screen shot 2019-02-25 at 23 56 23" src="https://user-images.githubusercontent.com/170270/53354379-3674af00-3959-11e9-8025-93cbacaf700b.png">

And this is how they **should** look when the <kbd>Option</kbd> key is pressed:

<img width="184" alt="screen shot 2019-02-25 at 23 57 59" src="https://user-images.githubusercontent.com/170270/53354400-442a3480-3959-11e9-853d-e09eac7fdf39.png">

### Actual behavior

They don't change when the <kbd>Option</kbd> key is pressed.

### Additional info

I have only tested the above roles. There might be more that needs to be handled correctly.

Getting little things like this right is important to make Electron apps feel native.

**Comment by codebytere** [comment] 2019-02-26 09:42
Looks like Chrome does this correctly, so i'll dig in and see if i can port that logic!

**Comment by codebytere** [comment] 2019-02-26 10:40
hmm @sindresorhus do you have a specific repro? I just tried this with the default Electron app, and it seems to update the menu items to their alternates, at least in the Window menu.

**Comment by MarshallOfSound** [comment] 2019-02-26 20:32
Worth noting that the "expected behavior" is the behavior I get in multiple Electron apps and the `default_app` 🤔

**Comment by codebytere** [comment] 2019-03-19 19:49
Closing based on above commentary, but can reopen should more info come to light!

**Closed by codebytere** 2019-03-19 19:49 UTC
Labels: component/menu, enhancement :sparkles:, platform/macOS
