### ISSUE TITLE
CrashReporter misses some types of crash

### ISSUE THREAD

**Issue by MrBlenny** [electron/electron#7876] opened 2016-11-04 15:18 UTC
* Electron version: 1.4.4
* Operating system: Windows 10.1

Crash reporter is setup as follows:
```javascript
crashReporter.start({
  companyName: 'Company',
  productName: 'Product',
  submitURL: 'http://localhost:1127',
  autoSubmit: true,
})
```

If I run `process.crash()` , a crash report is sent properly.

If for example, I run (in the main thread):
```javascript
setTimeout(()=>{
  console.log(thisVarIsUndefined)
}, 5000)
```

The application will exit with:
```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "app"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
```

No crash report is sent and there is not stack trace.

Is there any way to submit crash reports for these sports of basic Javascript errors? At the very least it would be good to have a stack trace but `process.on('uncaughtException')` doesn't seem to show anything.

**Comment by kevinsawicki** [comment] 2016-11-04 16:26
> Is there any way to submit crash reports for these sports of basic Javascript errors?

The crash reporter module sends minidump formatted reports and there is no way to convert a JavaScript error stack trace to one of those. The `crashReporter` module is intended for crashes and not uncaught errors.

You can use `process.on('uncaughtException')` in both the main and renderer processes to catch these errors and forward them to an exception tracker like BugSnag, Sentry, or Google Analytics to collect/analyze them.

> At the very least it would be good to have a stack trace but process.on('uncaughtException') doesn't seem to show anything.

Hmm, which process are you registering that on? That technique should work and provide a stack trace, can you provide a small app that reproduces the issue? Thanks.

**Comment by MrBlenny** [comment] 2016-11-05 00:13
I've managed to narrow the issue down.

Try `npm install sql.js` and import/require it in the electron main thread. 
The library works fine but somehow seems to break electron's stack trace (at least it does on windows).

Should I make a separate issue for this? It seems like this is an electron issue rather than a sql.js issue.

**Comment by kevinsawicki** [comment] 2016-11-07 19:56
> It seems like this is an electron issue rather than a sql.js issue.


I think this is a `sql.js` issue, it has the following code in it:

```
process['on']('uncaughtException', function(ex) {
    // suppress ExitStatus exceptions from showing an error
    if (!(ex instanceof ExitStatus)) {
      throw ex;
    }
  });
```

And the node.js docs state:

> Exceptions thrown from within the event handler will not be caught. Instead the process will exit with a non-zero exit code and the stack trace will be printed. This is to avoid infinite recursion.


If you register your `uncaughtException` handler before requiring `sql.js` you'll see it does get hit:

```js
const {app} = require('electron')

process.on('uncaughtException', (error) => {
  console.log('Error caught');
});

require('sql.js')

const start = () => {
  console.log('Electron is running');
  setTimeout(()=>{throw new Error('foo?')}, 1000)
}

app.on('ready', start);
```

**Comment by kevinsawicki** [comment] 2016-11-07 21:50
I'm going to close this out for now since it seems to be expected behavior given that `sql.js` is throwing errors from an `uncaughtException` error handler.

**Closed by kevinsawicki** 2016-11-07 21:50 UTC
Labels: more-information-needed
