### ISSUE TITLE
[Test]: Failing BrowserWindow.setAspectRatio(ratio) doesn\'t change bounds when maximum size is set

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#38937] opened 2023-06-27 13:33 UTC
https://chromium-review.googlesource.com/c/chromium/src/+/4575565 that comes as part of the roll https://github.com/electron/electron/pull/38891 breaks the calculation of content bounds when adjusting the maximum/minimum size.

The calculation done as part of https://github.com/electron/electron/blob/09669f9d215ceb96d7f02f9085d7906e27c2b301/shell/browser/native_window_views.cc#L1526-L1528 conflicts with the adjustments in https://github.com/electron/electron/blob/main/patches/chromium/fix_aspect_ratio_with_max_size.patch leading to the following dcheck failure in the said test

```
FATAL:resize_utils.cc(48)] Check failed: Rect(rect.origin(), *max_window_size).Contains(rect). 312,164 400x400 is larger than the maximum size 390x390
```

I tried to resolve this via the following patch which address the failing test but introduces regression in other bound calculations. @zcbenz can you take a look at this, thanks!

```patch
diff --git a/shell/browser/native_window_views.cc b/shell/browser/native_window_views.cc
index a1581d98d0..48bc8ac23e 100644
--- a/shell/browser/native_window_views.cc
+++ b/shell/browser/native_window_views.cc
@@ -1521,11 +1521,10 @@ gfx::Rect NativeWindowViews::WindowBoundsToContentBounds(
 #if BUILDFLAG(IS_WIN)
   HWND hwnd = GetAcceleratedWidget();
   content_bounds.set_size(DIPToScreenRect(hwnd, content_bounds).size());
-  RECT rect;
-  SetRectEmpty(&rect);
-  DWORD style = ::GetWindowLong(hwnd, GWL_STYLE);
-  DWORD ex_style = ::GetWindowLong(hwnd, GWL_EXSTYLE);
-  AdjustWindowRectEx(&rect, style, FALSE, ex_style);
+  RECT rect, client_rect;
+  GetClientRect(hwnd, &client_rect);
+  GetWindowRect(hwnd, &rect);
+  CR_DEFLATE_RECT(&rect, &client_rect);
   content_bounds.set_width(content_bounds.width() - (rect.right - rect.left));
   content_bounds.set_height(content_bounds.height() - (rect.bottom - rect.top));
   content_bounds.set_size(ScreenToDIPRect(hwnd, content_bounds).size());
```

**Comment by zcbenz** [comment] 2023-06-29 06:33
This bug is caused by WinFrameView returning content_maximum_size when it should return the size that has window frame included, I have pushed a fix to https://github.com/electron/electron/pull/38891.

**Comment by zcbenz** [comment] 2023-07-03 06:44
This is composed of a few nasty bugs.

In Chromium when calculating sizes it does not consider the window frame in most places (see code related to `WidgetSizeIsClientSize`), and for places where window frame matters (for example when setting min/max window sizes), it will calculate the window frame size on the fly to make up for the numbers (see `HWNDMessageHandler::OnGetMinMaxInfo`).

However the way Chromium calculates window frame size is buggy, it relies the GetClientRect API, which returns different sizes when window is under different states, for examples when minimizing a window it calculates one window frame size, but when restoring the window the size will be larger.

All these behaviors lead to our failing tests, and they were passing before the Chromium upgrade simply because the older code were more buggy and the min/max sizes set to the window were too wrong that the tests accidentally passed.

**Closed** 2023-07-05 15:02 UTC
Labels: upgrade-follow-up
