### ISSUE TITLE
Font Smoothing Issue

### ISSUE THREAD

**Issue by Devilanc** [electron/electron#14918] opened 2018-10-02 06:39 UTC
I'm Using Electron 3.0.2 now, I found font-smoothing is broken after i setting up windows performance. 
so i set to default windows performance, it was same.
Is there way to solve this?

Output of node_modules/.bin/electron --version: v 3.0.2

Operating System (Platform and Version): [ Windows 10 64 Bit ]

Expected behavior

Actual behavior

Electron 3.0.2 vs Electron 1.7.9
![comp](https://user-images.githubusercontent.com/22481188/46332824-e9fe9f00-c658-11e8-8abb-1b689ac2ad6b.PNG)

**Comment by MarshallOfSound** [comment] 2018-10-02 06:45
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by Dear-Min** [comment] 2018-10-02 06:54
@MarshallOfSound I Edited more info. sorry for not fill out template.

**Comment by sofianguy** [comment] 2019-08-09 22:52
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by Dear-Min** [comment] 2019-08-11 03:04
@sofianguy hello, there's a same issue with 6.0.1 release.

**Comment by electron-triage** [comment] 2021-03-08 18:37
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by Devilanc** [comment] 2021-03-08 18:50
I am using Electron v11.1 Now, Nothing Changed

**Comment by nornagon** [comment] 2021-03-12 00:52
Hey @Devilanc, sorry that this bug has gotten so little attention 😅  there are a lot of issues on the tracker and we're a small team with few resources. Thanks for letting us know that it's still happening on 11.x.

A few questions to help us narrow this down:
- Does this also happen in Chrome?
- Is the default Electron app enough to reproduce this issue, or is there something specific that triggers it? If the latter, would you be able to help us out by providing a small repro case that shows the issue, perhaps using [Electron Fiddle](/electron/fiddle)?

Thanks!

**Comment by Devilanc** [comment] 2021-03-12 20:13
@nornagon 
https://github.com/Devilanc/Nova-Interactive-Client/releases/latest

I just deployed some custom font into my client it works at Electron v1.7.9
But 1.7.9 version is old to use..

Works at Chrome, but electron is not working

I think -webkit-font-smoothing: antialiased; is not working

**Comment by nornagon** [comment] 2021-03-15 18:47
Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Devilanc** [comment] 2021-04-01 04:48
@nornagon 

https://gist.github.com/Devilanc/2b03acbdc524a0f8ddec2da4ded186c9 < Electron v1.7.9 Case
https://gist.github.com/Devilanc/1060f8536c198fb5be87725c195c4e22 < Electron v13.0 (Latest) Case

**Comment by nornagon** [comment] 2021-04-01 20:47
Hm, I'm not seeing the same behavior:

![image](https://user-images.githubusercontent.com/172800/113351811-3e4d6d00-92f0-11eb-93c0-47bbe8bb2ba6.png)

I turned off font smoothing in system settings, and again the two versions behave identically:

![image](https://user-images.githubusercontent.com/172800/113352093-b156e380-92f0-11eb-9251-f5b511ec4b16.png)

Is there some other setting I need to change to see the behavior you're running into?

**Comment by Devilanc** [comment] 2021-07-30 16:20
I Just turn off font smoothing, and back to default settings(on), it was not working :(

**Comment by nornagon** [comment] 2021-08-03 22:24
@Devilanc are you changing the settings _while the app is running_?

**Comment by Devilanc** [comment] 2021-08-05 06:45
I'm not sure it was.

**Comment by nornagon** [comment] 2021-08-05 16:58
Unfortunately, without repro steps, there's not much we can do to address this. I'm going to close this for now, but if you can help us out with steps that reliably reproduce this, I'd be happy to reopen.

**Closed by nornagon** 2021-08-05 16:58 UTC
Labels: platform/windows, 3-0-x, 6-0-x, 6-1-x, has-repro-gist, 11-x-y
