### ISSUE TITLE
[Bug]: deviceName property does not work when you have a printer set as the system default

### ISSUE THREAD

**Issue by joaovitmac** [electron/electron#29731] opened 2021-06-16 15:36 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

Microsoft Windows 10 Pro 10.0.19042 Build 19042

### What arch are you using?

x64

### Last Known Working Electron version

11.4.8

### Expected Behavior

When a window.webContents.print function is called with the deviceName property: "MyPrinter", the print must be destined for the device "MyPrinter"

![ex1](https://user-images.githubusercontent.com/66485490/122248009-27a1c580-ce9e-11eb-8ace-ea8708fa669e.png)

### Actual Behavior

The problem occurs on Electron versions greater than 11.4.8 when a default printer is configured in the operating system.
In the window.webContents.print function the deviceName property has no behavior, it's as if it doesn't exist

![ex2](https://user-images.githubusercontent.com/66485490/122249327-20c78280-ce9f-11eb-8043-2a78b8ee7cee.png)

### Testcase Gist URL

https://gist.github.com/d2be71545b59c8449f8206180168d122

**Comment by mmarvinedge** [comment] 2021-06-16 16:56
up

**Comment by pushkin-** [comment] 2021-06-16 17:29
Duplicate of [this](https://github.com/electron/electron/issues/28502) I believe

**Comment by codebytere** [comment] 2021-06-17 16:09
duplicate of https://github.com/electron/electron/issues/28502

**Closed by codebytere** 2021-06-17 16:09 UTC
Labels: bug :beetle:
