### ISSUE TITLE
Add Titlebar support for Wayland

### ISSUE THREAD

**Issue by Devorlon** [electron/electron#27016] opened 2020-12-15 09:06 UTC
Electron (with some finagling) can now be built with Wayland support. 

One problem is that it does not support drawing a title bar for any applications using it. Either requiring the application to call for the draw or having the window manager draw one (Client Side Decorations (CSD) and Server Side Decorations (SSD)), and unfortunately some applications have not implemented CSD (Discord, Vscode).

Deciphering the conversation from #10915 it seems that Chromium already supports CSD through GTK (which would be 'ported'?). And failing that it seems that gnome does provide the library [libdecoration](https://gitlab.gnome.org/jadahl/libdecoration).

Here is an example of a native Wayland window without a [titlebar](https://i.imgur.com/FV6NsoG.jpg).

**Comment by 4ndv** [comment] 2021-01-24 08:25
On vscode you can fix it using this setting:

```
"window.titleBarStyle": "custom"
```

**Comment by memeplex** [comment] 2021-02-07 17:30
GTK4 provides many components besides the headerbar itself. For example, you can define a handle area overlaid on top of your webview and add window buttons somewhere, thus getting a result similar to what MacOS Electron apps offer nowadays instead of a classic (even if CSD) title bar. Indeed, the headerbar widget is composed of these smaller parts that are also separately available. I've been doing some experiments and all this is easily achievable.

Now the bad part: the surfaces you get from Chromium/Electron are no GTK at all, not even the container is GTK, it's all done at the Aura/Ozone level AFAICS. So there is no place where to hook these GTK goodies. I've been inspecting the MacOS implementation in Electron and they seem to have reimplemented the entire NativeWindow in order to have a NSView, I guess something like that would be required to introduce a GTK container at the top of the hierarchy. That's a lot of complex work, I don't think it will come from an individual community contributor anytime soon.

OTOH, Chromium has its own rendering of window buttons that, although not perfect, does its best to follow the system theme. Maybe these parts could be reused, although they seem to be pretty intertwined with the browser windows, tab bar, etc.

**Comment by memeplex** [comment] 2021-02-07 17:34
These are the Electron issues that are the most relevant to the current one:

https://github.com/electron/electron/issues/27522

https://github.com/electron/electron/issues/11907

**Comment by StiliyanKushev** [comment] 2021-11-29 17:28
@4ndv's workaround is the only thing that works until the fix hits the latest bin.

**Comment by RaisinTen** [comment] 2022-07-15 08:15
Since https://github.com/electron/electron/pull/29618 has been merged, I'm closing this issue. Do let me know if this needs to stay open!

**Closed by RaisinTen** 2022-07-15 08:15 UTC
Labels: enhancement :sparkles:, platform/linux, status/confirmed, wayland

**Comment by gurnben** [comment] 2023-01-05 14:48
Hey folks!  

First - thank you for this incredibly descriptive issue - I found myself here when, upon setting the `--enable-features=UseOzonePlatform --ozone-platform=wayland` launch flags for VSCode (to resolve some stuttering) I lost my title bar entirely.  

I'm still experiencing this issue on Fedora 37 / Wayland / Nvidia (via akmod).  VSCode version details as follow:
```
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:27:19.253Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.15-300.fc37.x86_64
Sandboxed: No
```

The:
```
"window.titleBarStyle": "custom"
```
workaround resolves my issue, but isn't ideal.  

@RaisinTen Does anything look awry with my configuration that could cause me to experience this issue after the Electron issues were resolved and flagged properly?  

Let me know if I can provide any additional information - or try anything to resolve!  Thanks folks!

**Comment by RaisinTen** [comment] 2023-01-06 05:19
Interesting. @deepak1556 any clue?

**Comment by sepehr** [comment] 2023-01-06 06:24
@gurnben, try it like: 

```
code --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
```

---

In my experience with vscode, I had to install the `insiders` build as the standard one started crashing under native Wayland. Wish I could link the issue, but couldn't find it again.

**Comment by gurnben** [comment] 2023-01-06 14:54
@sepehr Ah!  Thanks for the tip!  I've switched to using:
```
--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
```
and the Title Bar is back (upon switching from custom to native) but I have another odd issue... 

This is what full screen looks like now on both my ultrawide and standard display:
![image](https://user-images.githubusercontent.com/14117802/211036767-098184b7-9f3d-40e0-b0bf-1792e19cdd18.png)

**Comment by sepehr** [comment] 2023-01-09 12:40
> _"@gurnben: but I have another odd issue... This is what full screen looks like now on both my ultrawide and standard display (complete with the border):"_

Not sure what is the problem you are referring to. Your title bar looks good to me tbh. Here's mine using insiders build:

![image](https://user-images.githubusercontent.com/23576/211310063-446bbfaf-7e4e-4275-b682-d2c937913602.png)

**Comment by sepehr** [comment] 2023-01-09 12:42
Oh, you probably mean that even though it is set to "native", you're not able to see the native GTK title bar like I do. I would try the insiders build, maybe that would help.

![image](https://user-images.githubusercontent.com/23576/211310441-9d4dfab3-a849-4b09-aeea-0dccd2b4e616.png)

**Comment by gurnben** [comment] 2023-01-09 14:52
@sepehr thanks for the suggestion - I'll give the insider build a try later today!  

The issue is actually that, with `WaylandWindowDecorations` set - full-screening the application leaves about a 10-pixel gap on all sides of the window (where you can see my wallpaper) - the application in my screenshot is fullscreen but has a gap around the window!  

Let me know if that makes sense - if not I can attach an annotated screenshot!

**Comment by kaimast** [comment] 2023-01-09 17:36
See this issue https://github.com/electron/electron/issues/33161 

Not sure if this is a regression or if you are using an old version of Electron.

**Comment by gurnben** [comment] 2023-01-09 18:17
Incredible - thank you @kaimast!  

I'm currently on:
```
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:27:19.253Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.15-300.fc37.x86_64
Sandboxed: No
```
on GNOME 43.2

In theory - Electron 19.1.8 should contain all fixes discussed in https://github.com/electron/electron/issues/33161 (just looking through the commits before the 1.19.8 tag [here](https://github.com/electron/electron/commit/f887fa45dfaeeddfe20c9835ae7ca3a0823b661b).
