### ISSUE TITLE
webContents.printToPDF never ends

### ISSUE THREAD

**Issue by torakiki** [electron/electron#20634] opened 2019-10-18 15:47 UTC
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I'm creating an "html to pdf" feature for my app, the user can enter a list of urls or html file, clicks a button and the app converts all of them. I'm using the Promise version of loadUrl and printToPdf, this is a fiddle I managed to create to [reproduce the issue](https://gist.github.com/f062371cd25fd38130af2e8e2151556e).
My issue is that it works most of the times but for some urls it just stays there and never ends. It reaches the printToPDF and then nothing happens, no error is printed or pdf file written, it just stays there in the printToPDF.
I tried the 7.0.0.beta7 and it does the same, I tried on Windows and Linux and I have the same issue.
If I enable logs I get many of these, they don't seem to be related to the printToPdf issue but still, they don't seem normal either:
```
[1:1018/121218.543891:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121218.544037:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121218.612767:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121220.512380:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
```

When I trigger the printToPDF these are the logs I get:
```
[1:1018/121435.112578:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[12207:1018/121435.113286:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1
[1:1018/121435.141258:VERBOSE1:sandbox_linux.cc(69)] Activated seccomp-bpf sandbox for process type: utility.
[1:1018/121435.141539:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.141857:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.141901:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.141952:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.141980:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.142012:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.142036:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.142060:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.142098:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.142127:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.142158:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.142187:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121435.145491:VERBOSE1:v8_context_snapshot.cc(152)] A context is created from snapshot for main world
[1:1018/121435.173524:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
[1:1018/121520.471001:ERROR:paint_controller.cc(547)] PaintController::FinishCycle() completed
```
Any idea on how to debug this or is there anything wrong in my code? As I said it works most of the times for some urls it seems to hang without any feedback
Thanks

* **Electron Version:**
  * 6.0.12
* **Operating System:**
  * Linux Mint Linux Mint 19.1 Cinnamon 64bits, Windows 7 64 bits
* **Last Known Working Electron version:**
  * don't know

### Expected Behavior
The page is printed to PDF

### Actual Behavior
printToPDF never ends

### To Reproduce
https://gist.github.com/f062371cd25fd38130af2e8e2151556e

### Screenshots
This the fiddle screeshot, 'after print' is never reached.
![image](https://user-images.githubusercontent.com/3884479/67108467-daec7f80-f1ce-11e9-8ae0-20fd4755a4e5.png)

**Comment by neopostmodern** [comment] 2019-10-27 13:18
@sofianguy I think this also applies to 7.x and is platform independent.

At least that's what I and other users experience here too (and I understand @torakiki in that he tested it on the 7.0.0-beta and on Windows too): https://github.com/neopostmodern/wohnungsbot/issues/11

The failure rates can be [as high as 90%](https://github.com/neopostmodern/wohnungsbot/issues/11#issuecomment-546232676)

**Comment by bjbk** [comment] 2019-10-29 04:14
Same on macOS

**Comment by bjbk** [comment] 2019-12-05 04:00
The docs are a bit confusing.  The `contents.printToPdf(options)` returns a promise, but the [docs](https://electronjs.org/docs/api/web-contents#contentsprinttopdfoptions) have a callback example.  I got this to work:

```js
ipcMain.on('printPDF', (event, arg) => {
  const pdfPath = `${app.getPath('desktop')}/${arg.name}.pdf`
  mainWindow.webContents.printToPDF({
    pageSize: 'Letter'
  }).then(data => {
    fs.writeFileSync(pdfPath, data, (err) => {
      if (err) throw err
      console.log('PDF success!')
    })
  }
  )
})
```

**Comment by torakiki** [comment] 2019-12-05 08:36
> The docs are a bit confusing. The `contents.printToPdf(options)` returns a promise, but the [docs](https://electronjs.org/docs/api/web-contents#contentsprinttopdfoptions) have a callback example. I got this to work:
> 
> ```js
> ipcMain.on('printPDF', (event, arg) => {
>   const pdfPath = `${app.getPath('desktop')}/${arg.name}.pdf`
>   mainWindow.webContents.printToPDF({
>     pageSize: 'Letter'
>   }).then(data => {
>     fs.writeFileSync(pdfPath, data, (err) => {
>       if (err) throw err
>       console.log('PDF success!')
>     })
>   }
>   )
> })
> ```
I tried both, Promise and callback and got the same result, it works with some address and silently fails with others. Did you try the address in the gist ?

**Comment by codecounselor** [comment] 2020-01-07 22:02
I am seeing this behavior when the page being printed contains an iFrame.  But in my case it only occurs on MacOS.  Windows/Linux are working.

**Comment by neopostmodern** [comment] 2020-01-27 19:08
I've just updated to [v8.0.0-beta.7](https://github.com/electron/electron/releases/tag/v8.0.0-beta.7) which includes #21783, but `printToPDF` still never ends in my scenario (https://github.com/neopostmodern/wohnungsbot/issues/11).

**Comment by fabiospampinato** [comment] 2020-05-28 20:36
I can confirm what @codecounselor said, under v8.3.0 it hangs forever when the HTML contains an iframe. I haven't checked if this issue occurs only under macOS though.

**Comment by codebytere** [comment] 2020-05-29 00:05
Interestingly, this does not seem to be the case in the main process?
```
const { app, BrowserWindow } = require('electron')
const fs = require('fs')

app.whenReady().then(() => {
  let win = new BrowserWindow({ width: 800, height: 600 })
  win.loadURL('https://stackoverflow.com/questions/909018/avoiding-initial-memory-heap-size-error')

  win.webContents.on('did-finish-load', () => {
    // Use default printing options
    win.webContents.printToPDF({}).then(data => {
      fs.writeFile('/Users/codebytere/Desktop/print.pdf', data, (error) => {
        if (error) throw error
        console.log('Write PDF successfully.')
      })
    }).catch(error => {
      console.log(error)
    })
  })
})
```

works fine in v9.0.0 and v8.3.0

**Comment by fabiospampinato** [comment] 2020-05-29 00:11
@codebytere I tried pretty much the same thing from the main process too, and the thing got ~fixed by adding a line like this:

```
html = html.replace ( /<iframe /ig, '<no-iframe ' );
```

I think you can't reproduce it because the URL you are using doesn't seem to contain any iframes anymore.

**Comment by codebytere** [comment] 2020-05-29 00:15
@fabiospampinato ah you're correct: tried with http://www.littlewebhut.com/articles/html_iframe_example/ and it hung.

**Comment by gearcoded** [comment] 2020-06-09 10:51
I encountered the same issue when running Electron on Windows 10 in Virtualbox.
Everything works correctly up to the 6.1 version. But starting from the 7.0 version, the `printToPdf` function hangs. 

Steps to reproduce:
1. Download the following archive:
https://ufile.io/6h0b2sy8
2. Unpack it somewhere.
3. Install the components and run the application:
```
npm install
npm start
```
4. When the browser is opened, press `z` on the keyboard.
5. Within 5 seconds, you should have the `print.pdf` file in the folder.
Otherwise, the bug is reproduced.

I installed Guest Additions but it doesn't help.

**Comment by codebytere** [comment] 2020-07-05 16:10
Gonna try to spend some time on this during the upcoming week.

**Comment by palashkulsh** [comment] 2020-07-06 18:04
For others facing the same issue you can try something like
      win.webContents.insertCSS('iframe {display: none !important;}')

seems like printing with iframe on the page is the culprit of printing pdf hanging.

**Comment by markleutloff** [comment] 2020-11-26 13:48
I can still reproduce this issue with the latest electron versions (~11.0.3). IFrames are very common and frames will even be used when displaying PDFs (the pdf viewer extension will be hosted in a frame).

Is there any news on this? PrintToPdf functionality is kind of an core feature in our product as the print handling in electron is very limited (kiosk mode printing, eg.).

**Comment by mikkorantalainen** [comment] 2020-12-04 08:20
Is anybody working on this issue (printing hangs on iframe elements)? Is the only known workaround to downgrade to Electron version 6.1 or older??

**Comment by codebytere** [comment] 2021-02-09 22:11
Closing in favor of https://github.com/electron/electron/issues/27605

**Closed by codebytere** 2021-02-09 22:11 UTC
Labels: 6-1-x, bug :beetle:, platform/all
