### ISSUE TITLE
[Bug]: BabylonJS doesn't work with some versions of Electron

### ISSUE THREAD

**Issue by nandin-borjigin** [electron/electron#35441] opened 2022-08-25 04:46 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.5.6, 15.5.7, 16.2.7, 16.2.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Last Known Working Electron version

12.2.3,13.6.9, 14.2.9, 15.4.2, 15.5.3,15.5.5, 17.0.0

### Expected Behavior

A minimal sample code of BabylonJS should work.

### Actual Behavior

On some versions of Electron, the minimal BabylonJS sample doesn't work. The console output says
```
[17592:0825/122030.758:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=-1073741819
```
And the renderer process reports `WebGL context lost`
![image](https://user-images.githubusercontent.com/10903833/186576868-f06df806-2df6-4f7d-be53-65426b5c92c2.png)

### Testcase Gist URL

https://gist.github.com/abc73139a0ca72b2a97c4a9856f7f442

### Additional Information

I've tried with the versions I've listed above but those are not exhaustive, i.e., versions that are not listed in the `Electron Version` section doesn't necessarily mean they will work.

**Comment by VerteDinde** [comment] 2022-08-29 20:49
@nandin-borjigin Is this issue still occurring for newer versions of Electron (18, 19, 20, 21)? E15 and E16 are both now outside of our supported versions, so we cannot apply a fix to those. If the issue is still occurring in the supported versions above, happy to look more.

**Comment by ckerr** [comment] 2022-09-12 23:02
This is working in the supported versions of Electron (18, 19, 20, 21) so I'm going to close this issue.

Tested with https://gist.github.com/abc73139a0ca72b2a97c4a9856f7f442 on 18.3.12, 19.0.16, 20.0.0, and 21.0.0-beta.5 on Ubuntu 22.04.1

**Closed by ckerr** 2022-09-12 23:02 UTC
Labels: blocked/need-info ❌, bug :beetle:

**Comment by Blizzard-liu** [comment] 2023-05-17 03:07
> ### Preflight Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.
> 
> ### Electron Version
> 15.5.6, 15.5.7, 16.2.7, 16.2.8
> 
> ### What operating system are you using?
> Windows
> 
> ### Operating System Version
> Windows 11 22H2
> 
> ### What arch are you using?
> x64
> 
> ### Last Known Working Electron version
> 12.2.3,13.6.9, 14.2.9, 15.4.2, 15.5.3,15.5.5, 17.0.0
> 
> ### Expected Behavior
> A minimal sample code of BabylonJS should work.
> 
> ### Actual Behavior
> On some versions of Electron, the minimal BabylonJS sample doesn't work. The console output says
> 
> ```
> [17592:0825/122030.758:ERROR:gpu_process_host.cc(957)] GPU process exited unexpectedly: exit_code=-1073741819
> ```
> 
> And the renderer process reports `WebGL context lost` ![image](https://user-images.githubusercontent.com/10903833/186576868-f06df806-2df6-4f7d-be53-65426b5c92c2.png)
> 
> ### Testcase Gist URL
> https://gist.github.com/abc73139a0ca72b2a97c4a9856f7f442
> 
> ### Additional Information
> I've tried with the versions I've listed above but those are not exhaustive, i.e., versions that are not listed in the `Electron Version` section doesn't necessarily mean they will work.

我也遇到了同样的问题 canvas 画布内容突然消失了 请问你解决了吗   platform=win32 arch=x64 electron=22.3.8
