### ISSUE TITLE
want to customize the frame header color 

### ISSUE THREAD

**Issue by wangxiexe** [electron/electron#6250] opened 2016-06-27 06:53 UTC
* Electron version:
1.2.1
* Operating system:
windows 10

I am developing an app with electron on win 10 and the frame header (where you find functions like close the window 'x' ) is white which is not the color I want.

Is there any way I can customize the color? 

Thx!

**Comment by abdihaikal** [comment] 2016-06-27 14:06
IMO, for this purpose, you can read from this document: [__Frameless Window__](http://electron.atom.io/docs/api/frameless-window/#frameless-window)

**Comment by MarshallOfSound** [comment] 2016-06-27 14:21
@abdihaikal That will allow you to make a completely custom frame border by disabling the system borders.  What @wangxiexe wants (I believe) and what I would find useful aswell is this API.

http://blog.thomasnigro.fr/2015/02/11/exploring-w10-apis-windows-and-titlebar/

The ability to set the color of the default control bar. (This is a windows 10 only API)

**Comment by wangxiexe** [comment] 2016-06-28 01:28
@MarshallOfSound is right, I just want set the color of the titlebar, thx.

**Comment by lukeapage** [comment] 2016-06-28 04:16
duplicate of #1582

**Comment by kevinsawicki** [comment] 2016-06-29 00:42
Closing this out, please subscribe to #1582 for future updates.

**Closed by kevinsawicki** 2016-06-29 00:42 UTC

**Comment by hz0324** [comment] 2018-01-22 09:50
Hi, guys. How to make the window movable when using frameless window?

**Comment by isEdison** [comment] 2018-01-22 11:04
@hz0324 Did you mean this? [https://electronjs.org/docs/api/frameless-window#draggable-region](url)

**Comment by euangordon** [comment] 2018-10-19 10:03
@MarshallOfSound can you update your link to:
[http://thomasnigro.fr/2015/02/11/exploring-w10-apis-windows-and-titlebar/](http://thomasnigro.fr/2015/02/11/exploring-w10-apis-windows-and-titlebar/)

Thank everyone for your help.
