### ISSUE TITLE
clipboard.writeImage fails on Ubuntu

### ISSUE THREAD

**Issue by Mikepicker** [electron/electron#8665] opened 2017-02-12 22:04 UTC
* Electron version: 1.4.15
* Operating system: Elementary OS (Ubuntu)

### Expected behavior

NativeImage object copied on clipboard.

### Actual behavior

```
remote.js:217 Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from #<Object>
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from #<Object>
    at callFunction (/home/mike/dev/onion-packer/node_modules/electron/dist/resources/electron.asar/browser/rpc-server.js:235:11)
    at EventEmitter.<anonymous> (/home/mike/dev/onion-packer/node_modules/electron/dist/resources/electron.asar/browser/rpc-server.js:342:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/home/mike/dev/onion-packer/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

### How to reproduce

clipboard.writeImage(nativeImage.createFromPath(path));

### Further Info

I noticed that it works fine on Windows. I tried the solutions suggested in #8151 without success.

**Comment by kevinsawicki** [comment] 2017-02-14 19:37
> clipboard.writeImage(nativeImage.createFromPath(path));

@Mikepicker are you requiring `nativeImage` via `require('electron').nativeImage` or `require('electron').remote.nativeImage`?

Can you provide a more complete reproduction example and the image you are using?

**Comment by Mikepicker** [comment] 2017-02-25 13:32
@kevinsawicki thank you for your answer.
I'm importing it using es6 simport style: `import { clipboard, nativeImage } from 'electron';`

This is the function I call to copy to clipboard:
`copyToClipboard = (texturePath) => {
    clipboard.writeImage(nativeImage.createFromPath(texturePath));
  }`

Where `texturePath` is the path of a jpg or png texture like this:

![floor_1](https://cloud.githubusercontent.com/assets/5290127/23331475/18a0fd76-fb67-11e6-9e97-717ff7c4b700.jpg)
`

**Comment by kevinsawicki** [comment] 2017-03-16 23:15
@Mikepicker 

Does this work for you?

```js
clipboard.writeImage(texturePath)
```

**Comment by kevinsawicki** [comment] 2017-03-16 23:44
After looking into this a bit, I believe this is a duplicate of #8151.

On Linux, the clipboard module uses the `remote` API under the hood and `NativeImage` objects can't be sent over `remote` currently.

To work around this issue you can either specify a String path to `clipboard.writeImage` which will automatically get converted to a `NativeImage` in C++, or you can implement this using IPC.

Merging this into #8151, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2017-03-16 23:44 UTC
