### ISSUE TITLE
webview 'console-message' missing arguments.

### ISSUE THREAD

**Issue by burtonator** [electron/electron#18558] opened 2019-06-01 14:39 UTC
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * all
* **Operating System:**
  * ubuntu 19.04
* **Last Known Working Electron version:**
  * none

### Expected Behavior

The webview 'console-message' event doesn't have an 'args'

https://electronjs.org/docs/api/webview-tag#event-console-message

If you want to listen to what's happening in a webview you can only get the message.

For example if you do:

```javascript
log.info("hello: ", "electron"); 
```

You can only get 'hello: ' not the "electron" string because there isn't an args.

This makes it very very difficult to debug what's happening in a webview.

Normally what I do is forward the console message from the child webview to the parent console so I can see what's happening there but I can't get 'args' which really breaks things.  

I can fix my own code but I can't fix the code of others.

**Comment by MarshallOfSound** [comment] 2019-06-02 00:01
Duplicate of #8090

This is an upstream issue

**Closed by MarshallOfSound** 2019-06-02 00:01 UTC
