### ISSUE TITLE
Linux/X11: BrowserWindow.getNativeWindowHandle() returns pointer instead of X window ID

### ISSUE THREAD

**Issue by sorentycho** [electron/electron#19068] opened 2019-07-01 20:53 UTC
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.6
* **Operating System:** Arch Linux

### Expected Behavior
Per the documentation: 
>Returns Buffer - The platform-specific handle of the window.
> The native type of the handle is HWND on Windows, NSView* on macOS, and **Window (unsigned long) on Linux**.

Here I understand `Window` refer to the `Window` resource type from the X11 [spec](https://www.x.org/releases/X11R7.5/doc/x11proto/proto.pdf) (see page two, bottom half of page).

Example X11 `Window` values:
```
0x004000e5
0x00400096
0x01e0000b
```

### Actual Behavior
Returns a 64-bit value (on a 64-bit system) that is not a valid X window id. The value looks like a memory pointer to the value rather than the actual `Window` value:
```
0x1500e00100000000
0x1400e00100000000
0x1300e00100000000
```
(Notice the constant stride between values, indicating successive members of an array in memory)

### To Reproduce
Run this in the console of any electron window:
```
require('electron').remote.getCurrentWindow().getNativeWindowHandle()
```
(this returns a `UInt8Array`, which when assembled into a hex string yields a value like the ones shown above in "Actual Behavior")

### Additional Information

On Linux/X11, the `Window` type refers to an opaque, unsigned 32-bit ID number supplied by the X server, not a memory address. This ID is constant across the lifetime of the window (hence no need to provide a double-derefenceable memory handle) and is useful even without writing native code--it can be supplied to shell utilities, or used with a pure-JS X11 client such as node-x11 without using any native add-on.

**Comment by codebytere** [comment] 2019-07-01 21:46
This was done [here](https://github.com/electron/electron/commit/624ade2c257f5dd6e915023f261d829e36540333) for context.

**Comment by zcbenz** [comment] 2019-07-02 10:35
I don't have a Linux machine by hand, just to verify, is `sizeof(unsigned long) == 16` on x64 Linux?

```
typedef unsigned long int XID;
typedef unsigned long int Atom;
typedef unsigned long int VisualID;
typedef unsigned long int Time;
typedef XID Window;
```

**Comment by sorentycho** [comment] 2019-07-02 22:33
@zcbenz On Linux, `sizeof(unsigned long)` varies by compiler config, however, `sizeof(Window) == 4` is always true, as per the X11 spec:
> WINDOW 32-bit value (top three bits guaranteed to be zero)

**Comment by zcbenz** [comment] 2019-07-03 04:08
Hmm in Chromium the native handle is represented as `unsigned long`, and `Window` is also defined as `unsigned long` in `X11/X.h` http://refspecs.linuxbase.org/LSB_4.0.0/LSB-Desktop-generic/LSB-Desktop-generic/libx11-ddefs.html, I don't quite understand why X11 spec requires `Window` to be 32bit value.

**Comment by sorentycho** [comment] 2019-07-03 05:48
Reading the spec more carefully...a `Window` is actually just an unsigned number <= 2^29. There's no reason you couldn't represent that in a 64-bit long if that was convenient.

The requirement for a 32-bit width is that the X11R6 wire protocol is binary and so needs to set a specific width for `Window` fields, but we're not building an X11 protocol client, just passing the ID around, so yeah, it doesn't actually matter as long as there's at least 29 bits available. :-P

**Comment by ckerr** [comment] 2019-08-30 23:58
I'm not able to reproduce this issue.

I tested on an amd64 box running X11 19.04, [This test gist](https://gist.github.com/105463e65146c455577497a33b57579a) is a clone of electron-quick-start with these lines added:

```js
+  const handle = mainWindow.getNativeWindowHandle().readUInt32LE()
+  console.log(`nativeWindowHandle: ${handle}`)
```

The output I get from that is

```text
nativeWindowHandle: 136314881
```

(136314881 is 0x8200001 in hex -- I should've converted before printing, but I'm not going to go back and change the gist for that :slightly_smiling_face -- and that's the same handle I get from `xwininfo`:

```text
xwininfo: Window id: 0x8200001 "Hello World!"
```

This works for me in both 5-0-x and 6-0-x

@sorentycho, what does the test above do when you try it?

**Comment by sorentycho** [comment] 2019-08-31 00:35
Huzzah, it seems to be fixed! That worked for me.

**Comment by codebytere** [comment] 2019-08-31 02:18
Rad, thanks for the update! Closing this out in that event, but of course happy to re-open should this recur.

**Closed by codebytere** 2019-08-31 02:18 UTC
Labels: 5-0-x, blocked/need-info ❌, bug :beetle:, platform/linux
