### ISSUE TITLE
Change the tray menu in ipcMain.on callback two times and it crash.

### ISSUE THREAD

**Issue by fomenyesu** [electron/electron#9996] opened 2017-07-13 09:18 UTC
I can change the tray menu in ipcMain.on callback at first time. But when I try to change the tray menu in ipcMain.on callback for the second time ,  I got follow errors :

2017-07-13 17:10:21.863 Electron[34599:260881] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (5.66 secs).
2017-07-13 17:10:21.863 Electron[34599:260881] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_attributesForCharacterIndex:reply:) block performed very slowly (4.99 secs).
2017-07-13 17:10:21.863 Electron[34599:260881] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_windowLevelWithReply:) block performed very slowly (2.99 secs).

**Comment by enlight** [comment] 2017-07-13 09:37
Please specify the Electron version, your Operating System, and provide a minimal app that reproduces the issue (you can fork https://github.com/electron/electron-quick-start and include a link to the branch with your changes).

**Comment by codebytere** [comment] 2017-09-27 01:22
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:22 UTC
Labels: more-information-needed
