### ISSUE TITLE
Cannot find module '../screen'

### ISSUE THREAD

**Issue by gregor** [electron/electron#8862] opened 2017-03-08 11:20 UTC
![electron](https://cloud.githubusercontent.com/assets/10243309/23701513/653c30fe-03f7-11e7-98b6-d34be1825207.png)

* Electron version: at least 1.6.0, 1.6.1, 1.6.2 and 1.6.3 are affected; 1.4.15 is fine
* Operating system: Windows 10

### Expected behavior

When starting an electron app that makes use of app.makeSingleInstance() from taskbar or desktop shortcut while it is already running in the background, we do not expect any uncaught errors for electron modules not found.

### Actual behavior

App window is restored and put to the foreground but an uncaught exception is thrown- Module '../screen' cannot be required in module.js:470:1.

### How to reproduce

https://github.com/wireapp/wire-desktop/releases/tag/release%2F2.13.2731

1. Run Electron app that makes use of app.makeSingleInstance()
2. Close main app window to continue app running in tray
3. Start app from desktop or tasbar

**Comment by kevinsawicki** [comment] 2017-03-09 01:04
@gregor can you provide the full text of the stack trace?

**Comment by Gloridea** [comment] 2017-03-13 08:09
@kevinsawicki  I have a same issue. full stack trace is:

```
Error: Cannot find module '../screen'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/gloridea/Workspaces/myapp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as screen] (/Users/gloridea/Workspaces/myapp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:91:14)
    at App.<anonymous> (/Users/gloridea/Workspaces/myapp/src/electron/main.ts:111:18)
    at Generator.next (<anonymous>)
    at /Users/gloridea/Workspaces/myapp/output/electron/main.js:7:71
    at __awaiter (/Users/gloridea/Workspaces/myapp/output/electron/main.js:3:12)
    at App.<anonymous> (/Users/gloridea/Workspaces/myapp/output/electron/main.js:99:12)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7) code: 'MODULE_NOT_FOUND' }
(node:52416) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../screen'
(node:52416) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I also tried to check followings:
```
console.log('electron_1', Object.keys(electron_1));
```

and it's result:
```
electron_1 [ 'clipboard',
  'crashReporter',
  'nativeImage',
  'shell',
  'app',
  'autoUpdater',
  'BrowserWindow',
  'contentTracing',
  'dialog',
  'globalShortcut',
  'ipcMain',
  'Menu',
  'MenuItem',
  'net',
  'powerMonitor',
  'powerSaveBlocker',
  'protocol',
  'screen',
  'session',
  'systemPreferences',
  'Tray',
  'webContents' ]
```

**Comment by gregor** [comment] 2017-03-14 15:54
@Gloridea Thanks for adding this. Didn't find the time to do so myself yet.

**Comment by kevinsawicki** [comment] 2017-03-16 23:10
@Gloridea are you using `app.makeSingleInstance()` as well?

**Comment by kevinsawicki** [comment] 2017-03-16 23:53
@Gloridea also, are you able to provide an example app that reproduces this for you?

**Comment by Gloridea** [comment] 2017-03-21 07:51
@kevinsawicki 
Sorry for may late answer. 
1. Yes, I'm using `app.makeSingleInstance()`.
2. I'll have a try to create sample error app soon.

**Comment by oukan** [comment] 2017-03-31 12:12
Electron version: at least 1.6.2
Operating system: Windows 7
Also have this problem

**Comment by arantes555** [comment] 2017-04-03 16:06
Seeing the same issue here, on electron 1.6.2, on a app that does use makeSingleInstance, but only from one of our users. More precisely, what we get is an error on `../net`.
Full error stack (not very informative):
```
UNKNOWNMODULE_NOT_FOUND Cannot find module '../net'
    at APIError.t (C:\Users\gdotts\AppData\Local\Programs\Seald\resources\app.asar\background.js:1:545)
    at APIError (C:\Users\gdotts\AppData\Local\Programs\Seald\resources\app.asar\background.js:1:22793)
    at C:\Users\gdotts\AppData\Local\Programs\Seald\resources\app.asar\background.js:1:23984
    at Generator.throw ()
    at r (C:\Users\gdotts\AppData\Local\Programs\Seald\resources\app.asar\background.js:1:5017)
    at C:\Users\gdotts\AppData\Local\Programs\Seald\resources\app.asar\background.js:1:5136
```

**Comment by tex0l** [comment] 2017-04-03 16:33
Just completing what @arantes555 has provided, it happened on Win7-64.

**Comment by kevinsawicki** [comment] 2017-04-03 22:47
I'm having trouble reproducing this issue exactly on Windows 10 but am seeing one major difference between 1.4.15 and 1.6.5, the `app` `ready` event fires for each instance that is created in 1.6.x while in 1.4.x it is only fired for the first app instance.

Are people who are experiencing this issue listening in their apps to the ready event even when `app.makeSingleInstance` returns `false`?

This was the app I tried with:

```js
const {app, BrowserWindow} = require('electron')
let window = null

const shouldQuit = app.makeSingleInstance(() => {
  window.focus()
  console.log('app.makeSingleInstance')
  console.log(require('electron').screen.getCursorScreenPoint())
})

if (shouldQuit) {
  app.quit()
} else {
  app.on('ready', () => {
    window = new BrowserWindow()
    window.loadURL('about:blank')
  })
}
```

But if I switch it to the following I do see multiple dialog boxes in 1.6.x but not in 1.4.x:

```js
const {app, dialog, BrowserWindow} = require('electron')
let window = null

const shouldQuit = app.makeSingleInstance(() => {
  window.focus()
  console.log('app.makeSingleInstance')
  console.log(require('electron').screen.getCursorScreenPoint())
})

if (shouldQuit) {
  app.quit()
}

app.on('ready', () => {
  dialog.showErrorBox('app', 'app is ready')
  window = new BrowserWindow()
  window.loadURL('about:blank')
})
```

**Comment by Arm1stice** [comment] 2017-04-05 18:10
I've been able to reproduce the bug on macOS Sierra

**Comment by kevinsawicki** [comment] 2017-04-05 18:14
@Arm1stice are you able to provide a reproduction app that demonstrates it? Thanks.

**Comment by Arm1stice** [comment] 2017-04-05 18:16
@kevinsawicki My laptop is dying on me, but I'll post a link to my repo when I get home. I would like to note, though, my error was reproduced without using app.makeSingleInstance()

**Comment by Arm1stice** [comment] 2017-04-05 19:56
https://gist.github.com/Arm1stice/9e3c99d6d4353dafd2ba9f9e3ec94db9

Running this gist with electron will produce the error. My theory is that, because the last open window closes before the next code runs, electron possibly attempts to shut down.

**Comment by Arm1stice** [comment] 2017-04-05 19:58
Is there the possibility that this only happens with some users as @arantes555 suggests because electron could be shutting down faster on better computers?

**Comment by tex0l** [comment] 2017-04-06 05:36
@kevinsawicki in the case of @arantes555 (and mine), I've checked, yes we do listen for the `'ready'` event even if `app.makeSingleInstance` returns `false` (it's a bit dirty though).

**Comment by kivS** [comment] 2017-04-15 16:27
Had the same problem using makeSingleInstance, I solved it using app.exit() instead of app.quit().

```javascript
const shouldQuit = app.makeSingleInstance(() =>{
  if(mainWindow) mainWindow.show();
})
if(shouldQuit) app.exit();
```
something to do with app.exit not having to emit events before quitting

**Comment by gch1p** [comment] 2017-06-16 20:49
On windows, I can sometimes caught this bug just by running my app from command line. I'm not sure how to reproduce it or why it happens, but it happened to me twice in the last hour. Both times I was launching the app from cmd.exe

**Comment by gch1p** [comment] 2017-06-16 21:41
I figured it: it's because of `process.noAsar = true`, but I don't think it's a feature, right?

**Comment by bcomnes** [comment] 2017-11-11 00:56
> had the same problem using makeSingleInstance, I solved it using app.exit() instead of app.quit().
@kivS Perfect solution!

**Comment by wip0** [comment] 2018-02-14 10:07
On Window 7 with Electron 1.7.11
```
Error: Cannot find module '../screen'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (D:\@misc\xplatform-installer\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as screen] (D:\@misc\xplatform-installer\node_modules\electron\dist\resources\electron.asar\browser\api\exports\electron.js:11:16)
```
I did not use app.makeSingleInstance.

**Comment by codebytere** [comment] 2018-09-24 04:42
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 04:42 UTC
Labels: bug :beetle:, bug/regression :leftwards_arrow_with_hook:, platform/windows, version/1.6.x

**Comment by joshuapinter** [comment] 2019-03-28 17:09
I can confirm, changing:

```js
if ( require( "electron-squirrel-startup" ) ) app.quit();
```

to:

```js
if ( require( "electron-squirrel-startup" ) ) app.exit();
```

and the issue went away.

Thanks!
