### ISSUE TITLE
Unable to start application without connecting to network.

### ISSUE THREAD

**Issue by Neil-Pan** [electron/electron#13788] opened 2018-07-24 18:08 UTC
* Electron Version:2.0.4
* Operating System (Platform and Version):window 7/8/10
* Last known working Electron version: unknown

Unable to start application without connecting to network.

**Expected Behavior**
application can startup with normal.

**Actual behavior**
application can not  startup  with some errors.

**Screenshots**
Unable to upload pictures.

**Additional Information**
The error's informations are as follow:
dns.js:246 Uncaught Error: EFILE
    at new Resolver (dns.js:246)
    at dns.js:377
    at dns.js:431
    at NativeModule.compile (bootstrap_node.js:606)
    at NativeModule.require (bootstrap_node.js:550)
    at net.js:45
    at net.js:1730
    at NativeModule.compile (bootstrap_node.js:606)
    at NativeModule.require (bootstrap_node.js:550)
    at internal/child_process.js:6
Resolver	@	dns.js:246
(anonymous)	@	dns.js:377
(anonymous)	@	dns.js:431
NativeModule.compile	@	bootstrap_node.js:606
NativeModule.require	@	bootstrap_node.js:550
(anonymous)	@	net.js:45
(anonymous)	@	net.js:1730
NativeModule.compile	@	bootstrap_node.js:606
NativeModule.require	@	bootstrap_node.js:550
(anonymous)	@	internal/child_process.js:6
(anonymous)	@	internal/child_process.js:936
NativeModule.compile	@	bootstrap_node.js:606
NativeModule.require	@	bootstrap_node.js:550
(anonymous)	@	child_process.js:35
(anonymous)	@	child_process.js:685
NativeModule.compile	@	bootstrap_node.js:606
NativeModule.require	@	bootstrap_node.js:550
(anonymous)	@	ELECTRON_ASAR.js:4
(anonymous)	@	ELECTRON_ASAR.js:703
(anonymous)	@	ELECTRON_ASAR.js:704
NativeModule.compile	@	bootstrap_node.js:606
NativeModule.require	@	bootstrap_node.js:550
(anonymous)	@	VM43:7
setupAsarSupport	@	bootstrap_node.js:619
startup	@	bootstrap_node.js:60
(anonymous)	@	bootstrap_node.js:622

Uncaught ReferenceError: require is not defined
    at (index):1
(anonymous) @ (index):1
renderer.js:1 Uncaught ReferenceError: module is not defined
    at renderer.js:1
(anonymous) @ renderer.js:1

**Comment by Mikerr1111** [comment] 2018-07-25 06:48
So you said Windows 7/8/10 are you having the problem across all Windows versions or just one specific version of Windows?

**Comment by Neil-Pan** [comment] 2018-07-25 16:33
Windows 7 Ultimate with Service Pack 1 32/64 bit
Windows 8.1 (multiple editions) 64 bit
 Windows 10 (Multiple Editions), Version 1703 (Updated July 2017) (x64) /Windows 10 (consumer editions), version 1803 (Updated March 2018) (x64)

**Comment by sofianguy** [comment] 2018-07-26 23:09
Thanks for contributing! This is a duplicate of #13779. Please follow that issue for updates.

**Closed by sofianguy** 2018-07-26 23:09 UTC
