### ISSUE TITLE
on start webview background is always white 

### ISSUE THREAD

**Issue by jrieken** [electron/electron#5175] opened 2016-04-15 09:31 UTC
- Electron version: 0.37.5
- Operating system: OS X 10.11.4
- Have web view with static html as such below
- Use the file uri of that code and set to source
- bring the web view to live
- for a short moment the background is white, then it changes to green

```
<!DOCTYPE html>
<html lang="en">
<head>
    <style>* {background-color: greenyellow; }</style>
</head>
<body style="margin: 0; overflow: hidden; width: 100%; height: 100%">
</body>
</html>
```

**Comment by zcbenz** [comment] 2016-04-16 02:09
I can confirm this, we need to patch Chromium to remove the white flash.

**Comment by antelle** [comment] 2016-06-05 12:12
Please also consider this related bug: #4645
For desktop apps, it would be very helpful to control what happens while the app is running in background.

**Comment by codebytere** [comment] 2017-09-27 01:44
closing due to abandonment.

**Comment by jcj52436999** [comment] 2017-09-27 01:45
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:42306 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dx1QC-0017ju-CU
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:45:59 -0500
Date: Tue, 26 Sep 2017 18:45:09 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1506476709;
	bh=JcZDJk4iP6V1Fjxl2A5pq9f9T38NEmgXGZg5nfy/mK4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=seowugpV8s5mQFt5vsNera8LO4zQ6vbSgjiHXQp7OAobLhh0T1O6H7GExBIyPOjR5
	 nA95uBbAcntbk493sxAs/ET/v37kNfzOTuXkMatCm1T74UDkdXlyKmy3LuRkf4M7oc
	 0rUjmnfWla5kvqDdqE2CXm+bw7Hw2vW+VPvPSegE=

**Closed by codebytere** 2017-09-27 01:44 UTC
Labels: component/webview, fixme/bug

**Comment by jcj52436999** [comment] 2017-09-27 01:46
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (109/100 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:42026 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dx1QB-0017iw-B7
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:45:58 -0500
Date: Tue, 26 Sep 2017 18:45:08 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1506476708;
	bh=Iaf/tIFyXemlTYWMd+Se5UhoDHtV3TQBATQqh0LUCMc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=kwU6BpKYN2lTp0VCUW/H07MFyDC4DAYhUbdPyxpDfULGeCJ6ugyIkPffcU+Idao0b
	 98sA2IumFrrUTjhRvEWQajrrowYBC8glHKJ6wX/6mROKhYX+r9UCyGZpWFtpKV+h9c
	 B4QeQpSqtgSVR2q8z5uqBbe2QFyNfL2A/ZXGyrms=
