### ISSUE TITLE
vibrancy + backdrop-filter breaks (works without vibrancy)

### ISSUE THREAD

**Issue by natew** [electron/electron#19765] opened 2019-08-15 03:06 UTC
### Issue Details

* **Electron Version:** Tried 6.0.2 and 7 beta 2
* **Operating System:** Mac 10.14.6
* **Last Known Working Electron version:** never

### Expected Behavior

If I don't do vibrancy I see the proper blur effect like so:

![image](https://user-images.githubusercontent.com/12100/63069890-dacdbc00-becd-11e9-8f7d-4a358fe3c9d5.png)

If I do have vibrancy on the window, it looks like this, where it shows a blurred layer *as well as the original non-blurred layer both*:

![image](https://user-images.githubusercontent.com/12100/63069966-2d0edd00-bece-11e9-8f9c-8590f652c7ab.png)

### To Reproduce

Started on a fiddle but this is a super complex fiddle, is there a simpler one? May not work...

https://github.com/natew/fiddle

```sh
$ git clone git@github.com:natew/fiddle.git
$ npm install
$ npm start || electron .
```

**Comment by mofux** [comment] 2019-08-28 14:52
I'm seeing exactly the same. This was kinda working with previous electron versions (4.x), although that version (4.x) was inheriting other `backdrop-filter` bugs from the incomplete chrome implementation.

It looks like a composition failure to me, where the blurred layer is not correctly applied (like it would have an opacity of 0.5 or so).

**Comment by latesamurai** [comment] 2020-02-19 17:57
The bug is still present in version 8.0.1. Is anyone fixing it?

**Comment by sapkra** [comment] 2020-07-16 17:17
It's still a problem in electron 9. Background blur is getting more popular. I hope it will be fixed soon.

But I'm not using any vibrancy on the window. Instead I just use the following snipped in my css and getting the same effect like the screenshot above.

```css
@supports ((-webkit-backdrop-filter: blur(10px)) or (backdrop-filter: blur(10px))) {
  background: rgba($color-grey-medium, 0.5);
  backdrop-filter: blur(10px);
}
```

**Comment by wthoutanymmries** [comment] 2020-07-18 18:38
@sapkra can you please provide full example? there's literally no information on this topic online

**Comment by sapkra** [comment] 2020-07-18 21:00
It's just a div element on top of another element with the backdrop-filter and a semi transparent background.

### Chrome
![image](https://user-images.githubusercontent.com/8087568/87861708-2348f180-c949-11ea-8239-d0431b3a7d5a.png)

### Electron
It's not like it does nothing. The elements behind the overlay become a little glowing like in the example above.
![image](https://user-images.githubusercontent.com/8087568/87861712-2c39c300-c949-11ea-9e44-913268d95d31.png)

**Comment by wthoutanymmries** [comment] 2020-07-19 07:30
@sapkra Oh, yup! I knew it. I was talking about browser window vibrancy. Do you know how to implement it properly?
Sorry if I didn't understand something and thanks for your time!

**Comment by wthoutanymmries** [comment] 2020-07-19 10:55
I found a solution. You may use [https://github.com/AryToNeX/Glasstron](glasstron) package

**Comment by andredezzy** [comment] 2020-12-04 04:18
Hey, somebody found a solution?

**Comment by jcarpenter** [comment] 2020-12-24 19:43
> I found a solution. You may use [https://github.com/AryToNeX/Glasstron](glasstron) package

Tried this, and it seems to possibly be broken with Big Sur ([issue filed](https://github.com/AryToNeX/Glasstron/issues/54)).

**Comment by jcarpenter** [comment] 2020-12-24 19:50
Opacity of the background elements seem to be a factor.

Dropdown w/ `backdrop-filter` over a "sidebar" div w/ `background: transparent`. **Doesn't work**.

![image](https://user-images.githubusercontent.com/1425497/103104701-a39d0e00-45dd-11eb-8cac-ec99165102e4.png)

Opaque `background` on the sidebar div. **Works**.

![image](https://user-images.githubusercontent.com/1425497/103104763-0c848600-45de-11eb-9f99-cfb9f1af6dac.png)

**Comment by jcarpenter** [comment] 2020-12-24 20:34
Conjecture on cause from Android system UI engineer who has dealt with similar issues ([Twitter thread)](https://twitter.com/jpohhhh/status/1342204511423758347): 

> I was doing a deep dive on blur from Android system UI about 18 months ago, this looks nearly identical to the issue that ended up blocking me TL;DR the compositor can't see the blended contents of the layer below, only the 'acutal' layer below

> complete guess, but if that was the case: OS X's compositor handles the blending of the sidebar with the 'behind app' layer, Skia draws the sidebar and dropdown background blur, and can only see the blur result _before_ color from the 'behind app' layer

**Comment by thesimpledev** [comment] 2021-03-01 23:29
> It's just a div element on top of another element with the backdrop-filter and a semi transparent background.
> 
> ### Chrome
> ![image](https://user-images.githubusercontent.com/8087568/87861708-2348f180-c949-11ea-8239-d0431b3a7d5a.png)
> 
> ### Electron
> It's not like it does nothing. The elements behind the overlay become a little glowing like in the example above.
> ![image](https://user-images.githubusercontent.com/8087568/87861712-2c39c300-c949-11ea-9e44-913268d95d31.png)

I'm having this same issue with Electron 9. I've been searching everywhere for any information/known bugs. It's reassuring to find that I'm not the only one running into this.

**Comment by electron-triage** [comment] 2021-03-09 03:42
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 03:42 UTC
Labels: 6-1-x, 7-0-x, 7-1-x, bug :beetle:, platform/macOS

**Comment by Servinjesus1** [comment] 2022-01-18 03:06
I believe this issue still exists. The workaround in the [above report](https://github.com/electron/electron/issues/30077) was to force disable vibrancy in a way by setting the background to solid white. Thus, I still reproduce the issue with vibrant windows. In my case, I'm running Win10, specifically Obsidian with window translucency enabled (Appearance - Translucent window) and a custom CSS theme with some transparent UI elements.

![image](https://user-images.githubusercontent.com/8541095/149863488-4ddc1411-925d-4ae8-9884-e5744dbc0810.png)

It's interesting how successive application of the blur _occasionally_ works on some elements, and not on others, even within the same element's `backdrop-filter` (compare how the Ventures card blurs the Agencies card name, but not the blue text in the right frame of the UI).

I'm curious if this is a high DPI issue, since my 1080p laptop running nominally the same program+setup does not exhibit this issue.

**Comment by augustography** [comment] 2022-09-19 23:51
This is a CSS rendering issue.
In testing yesterday with Chrome v105, elements with an applied css **filter** (with any value) appearing underneath an absolutely positioned element with a blurred **backdrop-filter** don't get the blur applied correctly.
Solution for me in another app was to remove the filter applied to the element/s underneath (and apply workarounds).

**Comment by davidcann** [comment] 2023-01-15 04:31
This is still an issue with Electron 22. The key is a semi-transparent window vibrancy (such as "sidebar") and a transparent background in the web page, as clearly shown in @jcarpenter's comment with screenshots. Given that it involves the Electron-specific vibrancy effect, I doubt that Chromium can fix it.

**Comment by zenithquinn** [comment] 2023-06-28 14:16
@MarshallOfSound could i be cheeky and do a polite bump on this one in case it's a "quick" fix 😅

**Comment by szalaybalazs** [comment] 2023-07-05 19:30
It would be superb if this could be fixed. Quite annoying.

**Comment by devnomic** [comment] 2023-08-08 01:40
This issue need to be opened, still an issue today. electron 25.

**Comment by marktoman** [comment] 2024-10-19 01:56
Please reopen this. I am experiencing it in the latest version.

To reiterate, disabling `vibrancy` works around the problem, but setting it to anything (including `content`) ruins the in-app `blur()`.
