### ISSUE TITLE
Cursor does not automatically hide on video playback

### ISSUE THREAD

**Issue by amilajack** [electron/electron#6357] opened 2016-07-06 04:08 UTC
- Electron version: 1.2.5
- Operating system tested on: macOS Sierra, El Capitan, Windows

Issue:
Usually when playing a video in chrome, safari, etc, the browser will hide the cursor when a video element is made fullscreen. The versions of electron that I have tested do not seem to have this feature.

**Comment by zcbenz** [comment] 2016-07-26 08:09
Can you give an example? I tried YouTube and the mouse is hidden in the same way with Chrome.

**Comment by amilajack** [comment] 2016-07-26 15:41
I haven't tried this in the latest version of electron.

**Comment by zcbenz** [comment] 2016-07-26 23:48
I only tried with 1.3.0.

**Comment by zcbenz** [comment] 2016-09-12 05:52
Closing until more information is provided.

**Comment by andymartinwork** [comment] 2016-10-06 08:39
@MarshallOfSound

I created a demo app here:

https://github.com/andymartinwork/electron-flash-issue

It's Mac OS only at the moment, but I can add Windows if you want. The issue is there too.

Run npm start and click the fullscreen button on the video. Then notice how the mouse cursor doesn't disappear like it does on other browsers.

I updated it to the latest version of flash just to check that wasn't the issue, but things were the same.

Having a good experience on music videos is really important for us at TIDAL!

**Comment by andymartinwork** [comment] 2016-10-07 08:30
Perhaps we could reopen?

**Comment by MarshallOfSound** [comment] 2016-10-07 08:44
@andymartinwork Sorry mate, haven't got around to testing this yet.  I don't have a mac easily available at the moment, will try to test it shortly.

**Comment by MarshallOfSound** [comment] 2016-10-07 08:52
@zcbenz Can confirm that it's an issue.  Interestingly my mouse appears to "glitch" when I click when it is supposed to be hidden.  Not sure if it's related.

**Comment by deepak1556** [comment] 2016-10-07 10:00
The problem seems to be with only `webview` , affects both html5 and flash videos. I am also able to reproduce with https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/webview-samples/multi-tab-browser . Most likely an upstream issue.

**Comment by codebytere** [comment] 2018-09-24 04:35
Given that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!

**Closed by codebytere** 2018-09-24 04:35 UTC
Labels: bug :beetle:, component/webview

**Comment by Spongman** [comment] 2019-02-16 02:00
very sad to see this marked as wontfix. this essentially breaks using electron as a ui-less fullscreen video player.
