### ISSUE TITLE
Electron under Mojave requests access to Contacts and Calendar

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#14833] opened 2018-09-27 09:09 UTC
* Output of `node_modules/.bin/electron --version`: 2.0.0
* Operating System (Platform and Version): macOS Mojave

**Expected Behavior**
As in previous operating systems Electron shouldn't show requests to access Contacts or Calendar because the app is actually not accessing it.

**Actual behavior**
The requests show up. See the screenshots.

**To Reproduce**
This issue can be replicated by downloading Atom or VS Code on Mojave.

**Screenshots**
<img width="465" alt="screen shot 2018-09-26 at 12 25 30 pm" src="https://user-images.githubusercontent.com/5859177/46065802-45361a80-c19d-11e8-9ea8-90078b44964d.png">
<img width="479" alt="screen shot 2018-09-26 at 12 25 05 pm" src="https://user-images.githubusercontent.com/5859177/46065804-45ceb100-c19d-11e8-901a-7f4cf6e82daa.png">

**Additional Information**
This issue was reported by one of our users. The same issue is reported in Atom and VS Code. Links below:
[VS Code](https://github.com/Microsoft/vscode/issues/55236)
[Atom](https://github.com/atom/atom/issues/17687)

**Comment by MarshallOfSound** [comment] 2018-09-30 04:59
Refs: https://bugs.chromium.org/p/chromium/issues/detail?id=881631

**Comment by astoilkov** [comment] 2018-10-01 10:27
@MarshallOfSound I saw the ref. Note that the reference is talking about access to photos which I didn't see as an Electron issue. The problem is the access to contacts and calendar.

**Comment by MarshallOfSound** [comment] 2018-10-01 11:48
@astoilkov The issues are probably linked and some people have reported the photos prompt as well.  Reffing purely to monitor chromium's progress on that issue

**Comment by pronebird** [comment] 2018-10-03 10:00
It didn't happen to me though. Perhaps the use of certain Electron APIs causes this?

**Comment by astoilkov** [comment] 2018-10-03 10:07
@pronebird Which app did you try? It seems to be different for users. On one of the computers we tried it happened when performing export to pdf.

**Comment by matheusbaumgart** [comment] 2019-04-28 23:46
This is what I'm trying to accomplish but can't find any documentation or support for this. Is it possible to request access to the user's Calendar and therefore render all events across all Calendars added to the Calendar.app? Including events from Google Calendar added there?

Any help is appreciated, thanks!

**Comment by DeerMichel** [comment] 2019-07-03 16:29
I can't reproduce this with macOS Mojave 10.14.5. Tried Electron v4-v6 - can the issue be closed?

**Comment by nornagon** [comment] 2019-07-03 17:24
@DeerMichel what were your repro steps? I was able to produce this error with Terminal.app even, by running `ls ~/Library/Calendars`. I think this is kind of a Mojave issue rather than an Electron one... though I'm confused why Electron would be accessing `~/Library/Calendars` without asking.

**Comment by DeerMichel** [comment] 2019-07-03 17:46
I did start Electron 😄. Also, when i run `ls ~/Library/Calendars` I don't get asked for permissions. I ran `tccutil reset Calendar` and checked system preferences:

![image](https://user-images.githubusercontent.com/8472721/60613478-d1561d80-9d7f-11e9-9c96-5cb717f5eed5.png)

**Comment by nornagon** [comment] 2019-07-03 21:36
It seems that mojave keeps these particular permissions somewhere that `tccutil reset` doesn't reach, as the Atom issue above found.

I can reproduce this with the following fiddle on macOS 10.14.5: https://gist.github.com/4848593f6a7afad2b139868653e7e604

**Comment by sofianguy** [comment] 2019-08-08 23:41
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:17
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:17 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS
