### ISSUE TITLE
Click "about" MenuItem in Tray can't make app activate

### ISSUE THREAD

**Issue by lif3ng** [electron/electron#11519] opened 2017-12-26 08:43 UTC
* Electron version: 1.8.1
* Operating system: macOS 10.12.5

### Expected behavior

Tray > contextMenu > menuItem(role="about")

when I click menuItem to show about panel, can handle click event to show app. 

### Actual behavior

no place can write click handle can make app to activate

### How to reproduce

Create a menuItem with "about" role in the tray's contextMenu. Run another application, with the window at the top, covering the electron's app. Click about menuItem in tray contextmenu. Can not be shown covered under the about the panel

**Comment by codebytere** [comment] 2018-02-18 17:14
Closing as duplicate of https://github.com/electron/electron/issues/11818

**Closed by codebytere** 2018-02-18 17:14 UTC
Labels: platform/macOS, triaged/bug, version/1.8.x
