### ISSUE TITLE
Electron creates bogus directory path

### ISSUE THREAD

**Issue by alespergl** [electron/electron#10848] opened 2017-10-19 12:21 UTC
On Windows, when Electron ~with Chromium61~ is run, the path `%HOMEDRIVE%%HOMEPATH%\AppData\Roaming\Electron\logs` is created under the current directory.

This can likely be attributed to the following code:
https://github.com/electron/electron/blob/306b62709017e12f6f4865e3d2b069cc7177db1f/brightray/browser/browser_main_parts.cc#L168-L179

I did not reproduce it with Electron 1.8.1, so I'm deducing that it has something to do with upgrade to Chromium 61 - possibly the function `PathService::Override` no longer expands environment variables.

**Comment by robinwassen** [comment] 2017-10-19 17:10
This folder has also been created for me under the current working directory, and the latest version that I have been running has been 60e614b10ce31bf84b43efd06d77d47991c39bf0 (which says 1.8.1 in package.json).

**Comment by HitomiTenshi** [comment] 2017-10-20 09:02
This error is now happening with the latest electron `1.8.2-beta.1`.

**Comment by alespergl** [comment] 2017-10-20 10:09
Ok, so it seems unrelated to chromium. Removing the tag.

**Comment by codebytere** [comment] 2017-10-25 15:56
@alespergl sorry this fell through my attention the first time but i've opened a PR to fix, see https://github.com/electron/electron/pull/10911 :)

**Comment by codebytere** [comment] 2017-10-25 15:57
Closing as duplicate of https://github.com/electron/electron/issues/10910

**Closed by codebytere** 2017-10-25 15:57 UTC
Labels: platform/windows, triage/bug
