### ISSUE TITLE
Open DevTools, click on any key in the console, the entire application crashes

### ISSUE THREAD

**Issue by WangMl** [electron/electron#11764] opened 2018-01-29 10:29 UTC
* Electron version: v1.8.2-beta.3
* Operating system: window7

### Actual behavior
Open DevTools, click on any key in the console, the entire application crashes

####Scenario Restore
1. Execute /script/build.py No error occurred. 
2. After deployment, find the electron.exe in out and open the electron through the command line. 3. Open DevTools, click on any key in the console, the entire application crashes.

**Comment by brenca** [comment] 2018-01-29 10:37
Closing as a duplicate of #11375

**Closed by brenca** 2018-01-29 10:37 UTC
