### ISSUE TITLE
Setting tray pressedImage while tray is active

### ISSUE THREAD

**Issue by anthonybruno** [electron/electron#8831] opened 2017-03-04 00:06 UTC
* Electron version: 1.4.15
* Operating system: macOS Sierra 10.12.3

### Expected behavior

If `tray.setPressedImage()` is updated while the tray is actually "active" it should update to the new asset.

### Actual behavior

Whatever image has been set prior to the tray becoming active it will remain as such even if a new image has been set with `tray.setPressedImage()`. If you make the tray inactive, and then click it again, your new image will then display properly.

### How to reproduce

Update `tray.setPressedImage()` while the tray is active.

**Comment by zcbenz** [comment] 2017-06-13 09:49
The `setPressedImage` simply calls the native API, which behaves in this way, it is also consistent with behaviors of other UI frameworks. And if you ever implemented a similar thing, you would find this behavior actually quite reasonable.

Closing since it is expected behavior. A pull request to explicitly document it would be welcomed though.

**Closed by zcbenz** 2017-06-13 09:49 UTC
Labels: component/tray, fixme/bug
