### ISSUE TITLE
APIs should use a property instead of separate getter/setter methods

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#12745] opened 2018-04-29 16:56 UTC
Continued from https://github.com/electron/electron/pull/12496/files#r181941682

---

* Electron version: 2.0.0-beta.8
* Operating system: macOS 10.13

### Expected behavior

JavaScript supports getters and setters, so it's quite awkward that most of the Electron APIs instead use separate methods for getting and setting. This feels more like Java than JavaScript.

I propose that new APIs start using getters and setters (for example https://github.com/electron/electron/pull/12496), when it makes sense, and that eventually old APIs moves to it too.

For example, the `app.getName()`/`app.setName()` methods could simply be:

```js
const {app} = require('electron');

console.log(app.name);
//=> 'Electron'

app.name = 'Unicorn';

console.log(app.name);
//=> 'Unicorn'
```

### Actual behavior

This is how it currently works:

```js
const {app} = require('electron');

console.log(app.getName());
//=> 'Electron'

app.setName('Unicorn');

console.log(app.getName());
//=> 'Unicorn'
```

**Comment by dmckenna24** [comment] 2018-04-29 19:27
Agreed, why waste up more lines of code when JavaScript does the work for you? Anyone tackling this issue?

**Comment by codebytere** [comment] 2018-04-30 00:33
@sindresorhus at the moment, we don't do that because we have some instances (like `getBounds()`) where the property would be an object, so we couldn't handle deep modifications like `mainWindow.bounds.x`. 

I agree that it's definitely more idiomatic, so once we find a clean way to account for aforementioned cases i think this is something we could definitely do.

**Comment by LinusU** [comment] 2018-04-30 11:12
@codebytere should be easily fixed with a `Proxy`? 🙌 

Something like

```js
class Window {
  get bounds () {
    return this._bounds
  }

  set bounds (newValue) {
    this._bounds = new Proxy(newValue, {
      set: (obj, prop, value) => {
        Reflect.set(obj, prop, value)
        this._boundsChanged()
      }
    })

    this._boundsChanged()
  }
}
```

**Comment by MarshallOfSound** [comment] 2018-04-30 11:25
@LinusU 

> easily fixed with a `Proxy`

Not really in a scalable and generic way, sure we could wrap everything in a Proxy in JS land but then you have this weird bridge between a JS proxy and native land.  You would also need to wrap things in JS for **all** the API's that do this.  Even if we do `v8::Proxy` stuff in native land it's going to be messy code

We're definitely going to look into this, but it isn't as simple as "let's put a proxy everywhere" unfortunately.

**Comment by MarshallOfSound** [comment] 2018-04-30 11:28
For added context people can look at the `TouchBar` API's which currently already partially do this.  We have this weird `_setLiveProperty` wrapper and do all the logic in JS land (not really the best thing to do).  And even with that we still have deep property issues like someone doing this:

```js
touchBar.items.push(new TouchBarButton({ label: 'new' }))
```

Because even though we can do setters, detecting things being pushed into arrays is just a whole bunch more complicated.

**Comment by zcbenz** [comment] 2019-06-07 03:06
There is no confirmed conclusion that getter/setters are better, for example [this discussion](https://nemisj.com/why-getterssetters-is-a-bad-idea-in-javascript/). And IMO https://github.com/electron/electron/pull/18674 is a clear example that getter/setters are worse.

If we are going to do this change, we should do a formal discussion.

**Comment by zcbenz** [comment] 2019-06-12 10:46
To explain my oppositions to switching to property APIs:

1. The returned JS value is not bind to C++ value

The property getter returns a copy instead of reference to the native value, so for APIs that return Array or Object, it gives user wrong assumptions.

```js
// This does not have any effect
win.browserViews.push(new BrowserView)
win.bounds.x = 123
```

And considering the complexity of the implementation, I don't think we will support full Array or Object semantics.

2. We should not do breaking API changes for styling reasons

I don't think we should deprecate dozens of APIs just because one style looks better than the other.

I have listed a few cons of property APIs here, they don't mean methods APIs are always better, but they should be able to explain why we shouldn't simply deprecate one style for another.

Moving to promises is good idea because it makes async code easier and safer, and it improves code quality, but I don't see such improvements in switching from methods to properties.

3. No error would be printed for typos

With methods, typos can be found immediately as exceptions would be thrown, while with properties no error would be printed.

```js
// This throws.
win.loadUUL(url)

// This does not throw.
win.uul = url
```

4. Costs are hidden

When using method APIs, it is very clear that the API has some cost, while users are very easy to ignore the cost of properties APIs.

For example with `app.getName()`, users usually only call it once and save the result:

```js
const appName = app.getName()
doThingsA(appName)
doThingsB(appName)
```

While with `app.name` most users would just do:

```js
doThingsA(app.name)
doThingsB(app.name)
```

So I think it encourages users to write worse code.

5. Monkey-patching properties are hard

Iterating or monkey-patching methods of classes are common tasks, and it is easy. With properties while it is still possible, it becomes much more difficult and is hard to get right.

6. Future extensions are impossible

When we want to extend an existing method API, we can just add optional parameters. An example is `win.setBounds(bounds[, animate])`, similar things are impossible to do with `win.bounds`.

**Comment by MarshallOfSound** [comment] 2019-06-12 17:28
> The returned JS value is not bind to C++ value

I noted this concern above, this is why the current proposal has been amended is to only change primitive properties.  E.g. strings, numbers, etc.

> No error would be printed for typos

Although fair, this is just how javascript works.  If you want type safety / the ability to know if you make these mistakes the project should be using a type checker like typescript.

> Costs are hidden

This is fair but the assumed pattern that folks follow is not correct.  With object destructuring, property reuse has become this common pattern.

```js
const { name } = app
doThingA(name)
doThingB(name)
```

> Monkey-patching properties are hard

I'm not entirely sure what the point is here, we shouldn't be sacrificing other benefits to make it so folks can monkey-patch our API.  That said monkey-patching properties is really easy with `Object.defineProperty` or the new ES6 Proxy.

> Future extensions are impossible

At a glance this makes sense but I think this actually leans us more towards properties than methods.  If you have a set/get method pair they should take in a single "thing" and return exactly what was set.  The pattern of `thing.setValue(newValue, { modifier: true })` doesn't make much sense IMO.  E.g. Look at our `autoUpdater.setFeedURL` API where `getFeedURL` returns a string and `setFeedURL` takes in a complex object.

> We should not do breaking API changes for styling reasons

I do not believe that this is any more "for styling reasons" than the promisification.  E.g. the promisification allows users to right cleaner, more usable code like this.

```js
doThing(() => done())
```

```js
await doThing()
```

With properties a similar effect occurs.  Take the common use case of saving and restoring window properties across relaunches (position, title, last url, etc.)

```js
// Old
const x = win.getX()
const y = win.getY()
const title = win.getTitle()
const url = win.getURL()
saveValues({ x, y, title, url })
const values = loadValues()
win.setX(values.x)
win.setY(values.y)
win.setTitle(values.title)
win.setURL(values.url)
```

```js
// New
const { x, y, title, url } = win
saveValues({x, y, title, url })
Object.assign(win, loadValues())
```

Properties lead into things like destructuring, spreading and other new JS language features that make code easier to write, read and use in the same way that promises did.

**Comment by ckerr** [comment] 2019-08-29 17:00
I'm not especially pro- or anti- conversion from getter/setter to properties, but I do have a concern that Electron's API churn will make it difficult for people to upgrade versions of Electron easily. This may have been less of a problem in the past, but now that we're following Chromium's release cadence I think this is a real concern.

**Comment by ckerr** [comment] 2019-08-29 23:55
...actually after re-reading 19996, I think [this discussion](https://github.com/electron/electron/pull/19996#discussion_r318914352) of @zcbenz' has a good point about platform-specific properties not throwing. That PR proposes a read/write property `tray.visible`.

However if this property is only exposed on macOS (as suggested by @miniak and @zcbenz) then developers are going to hit some unexpected behavior on platforms where the property is not exposed:

```
if (!tray.visible) {
  // because the `visible` property does not exist on Linux or Windows,
  // this block will be reached even if the tray is actually visible
}
```

What makes this example different from the throws / does-not-throw above in the conversation about in 12745 is that not even typescript will save you here, since we don't have per-platform .ts bindings.

So, on the specific topic of per-platform properties:

1. Stick with the getters/setters that we have now as those throw, are easy to write, and easy to use. This seems the shortest path to error-free code but I may come at the price of forever getting pushback about non-idiomatic JS.

2. Clearly document in the code samples that people need to test the property for existence before using it, e.g. require app developers to write `tray.hasOwnProperty('visible') && !tray.visible`. I don't like this choice because many developers will not be rigorous about this.

3. Expose the properties on all platforms, but call isolate::ThrowException() when they're accessed on unsupported platforms. If we go with properties, this feels like the Lead Bad way to do it for per-platform properties: the API will be idiomatic JS, but will preserve the throw-on-incorrect-use as before:

```js
tray.setVisible(flag) // throws non non-macOS
```
and

```js
tray.visible = flag // throws on non-macOS
```

**Comment by jkleinsc** [comment] 2020-05-26 13:43
This issue was addressed in the API WGs document here:
https://github.com/electron/governance/blob/master/wg-api/best-practices.md#getters-and-setters.  The TLDR is that getters and setters should be implemented as methods but if they are primitives, they should be also added as a property interface for the value.

**Closed by jkleinsc** 2020-05-26 13:43 UTC
Labels: discussion :speech_balloon:
