### ISSUE TITLE
I'm getting the below error after upgrading the Electron to "electron@2.0.0-beta.2." from "electron": "^1.7.9"

### ISSUE THREAD

**Issue by sunkari00** [electron/electron#12318] opened 2018-03-16 06:12 UTC
I'm getting the below error after upgrading the Electron to "electron@2.0.0-beta.2." from "electron": "^1.7.9",

unknown error: Element is not clickable at point (1792, 1412)
Error: An unknown server-side error occurred while processing the command.
at elementIdClick("0.19542284114016173-38") - click.js:20:22

Below is the same function was working before the upgrade but now fails with the above error message. Greatly appreciate any pointers to resolve this issue. 

export function marketRegionFieldNavigation(client) {
  // Select Market from the list of Dropdown
  client.click(territoriesPage.marketField)
    .pause(5000)
    .keys(jsonTestData.market)
    .keys(webdriver.Key.ENTER)

    // Select Release Region from the list of displayed Release Regions
    .waitForExist(territoriesPage.releaseRegionField)
    .click(territoriesPage.releaseRegionField)
    .keys(jsonTestData.releaseRegion)
    .keys(webdriver.Key.ENTER)

    // Select Build Region from the list of BRs
    .waitForVisible(territoriesPage.buildRegionField)
    .click(territoriesPage.buildRegionField)
    .keys(jsonTestData.buildRegion1)
    .keys(webdriver.Key.ENTER)
    .pause(3000)

    // Click on the Continue Button
    .pause(waitTime.explicitWaitTimeShort)
    .click(mainPage.continueButton);
}

**Comment by ckerr** [comment] 2018-03-16 07:14
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sunkari00** [comment] 2018-03-16 07:27
[Individual_Test.txt](https://github.com/electron/electron/files/1818277/Individual_Test.txt)

@ckerr  Attached the individual test. I hope this is sufficient to troubleshoot the issue I'm facing.

**Comment by ckerr** [comment] 2018-03-16 07:40
@sunkari00, thank you for this, but a standalone test would be more useful as something that could be run outside of your local environment.

Would it be possible for you to write a small index.html + main.js that exercises this bug without dependencies?

**Comment by sunkari00** [comment] 2018-03-16 16:02
@ckerr , thank you for your quick response. The problem is simple. Our automation mocha tests were all running fine before the electron upgrade.  Once we upgraded to electron@2.0.0-beta.2 . All our tests are failing with the below error message.  Basically. webdriver is unable to local the object as the object is not in the viewport.  Earlier same tests were working without having to scroll to the object and click. But now, looks like in order to click on any object the object needs to be in visible area and viewport to perform click operations.  This's indeed a huge drawback going into the newer version where webdriver click operations are not working if the object is not in the viewport. 


unknown error: Element is not clickable at point (1792, 1412)
Error: An unknown server-side error occurred while processing the command.
at elementIdClick("0.19542284114016173-38") - click.js:20:22

**Comment by felixrieseberg** [comment] 2018-03-16 17:18
You may have noticed that you paid $0 for Electron, so if anyone is going to fix this for you, they're going to do it for free. Trying to figure out what is actually going on here is difficult since your code has references to code that's not here - we'd have to guess what's going on.

A general rule of thumb: If it's too much trouble for you to create a standalone app that reproduces the bug it'll _likely_ be too much trouble for someone to fix this for you.

**Comment by ckerr** [comment] 2018-03-17 22:51
@sunkari00, I have no context for the application that the test was written for.

However, Electron also uses Mocha.

If your application's authors could write a small test application and mocha test case for it, then we could use that to reproduce the issue here.

**Comment by ckerr** [comment] 2018-03-17 22:56
Possibly related to https://bugs.chromium.org/p/chromedriver/issues/detail?id=1852 -- upstream reported seeing a similar issue in c61+.

If it's the same issue, upstream fixed it this patch:
https://chromium.googlesource.com/chromium/src/+/47d5c0062c7a4a7a41374c91da4170e22ea681e1%5E%21/

**Comment by ckerr** [comment] 2018-03-17 23:11
@sunkari00, you may want to ensure that your chromedriver version is up-to-date. At least one Selenium user reports this fixed in chromedriver [2.32](https://github.com/SeleniumHQ/docker-selenium/issues/566#issuecomment-329697590).

At any rate, this seems to have moved out of the realm of "Electron bug" and so I'm going to close this issue. If you feel this is in error please let me know.

**Closed by ckerr** 2018-03-17 23:11 UTC
Labels: more-info-needed :information_source:, version/2.0.x
