### ISSUE TITLE
Cannot open any electron application

### ISSUE THREAD

**Issue by J-Bollie** [electron/electron#24320] opened 2020-06-26 18:43 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * Don't know

### Expected Behavior
A normal launch of the application.

### Actual Behavior
Doesn't launch the application because it can't find "cli.js" in the electron node module, this started happening after I resolved the issue that npm can't find certain node_modules via npm install

### To Reproduce
/

![image](https://user-images.githubusercontent.com/48119536/85890493-b9c44000-b7ed-11ea-9cdd-9c708759cad1.png)

**Comment by codebytere** [comment] 2020-06-28 04:14
Duplicate of https://github.com/electron/electron/issues/24298

**Closed by codebytere** 2020-06-28 04:14 UTC
