### ISSUE TITLE
[Bug]: 'restore' event not emitted after minimize and maximize application

### ISSUE THREAD

**Issue by khanhnguyen3759** [electron/electron#35223] opened 2022-08-04 11:04 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21H1

### What arch are you using?

x64

### Expected Behavior

Event 'restore' should notify to application

### Actual Behavior

After clicking maximize application, the event 'restore' does not notify after minimize

`
BrowserWindow.on( 'restore', () => { // nothing happend });
`

**Comment by codebytere** [comment] 2022-08-04 11:07
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by khanhnguyen3759** [comment] 2022-08-04 11:18
@codebytere  fiddle here https://gist.github.com/75b80d682f9408b56bbf534f57b23072

**Comment by pushkin-** [comment] 2022-08-18 15:07
Seems like this is a dupe of [this issue](https://github.com/electron/electron/issues/28570) @mlaurencin

**Comment by mlaurencin** [comment] 2022-08-18 19:16
@pushkin- It seems like it is a dupe of the maximization portion of that issue, but there is still the firing late portion. I tried testing on versions v17+, but was not able to replicate the firing late. I can close both issues with my PR if that not problem is no longer present in the currently supported versions.

**Comment by pushkin-** [comment] 2022-08-18 19:53
@mlaurencin That other issue about it firing late doesn't matter for me. The title was edited by clavin.

**Comment by mlaurencin** [comment] 2022-08-18 21:31
@pushkin- I will go ahead and use the PR to close both issues, but note in the other issue that it can be reopened if the firing late problem persists, as it should still be acknowledged.

**Closed** 2022-08-23 01:32 UTC
Labels: platform/windows, bug :beetle:, component/BrowserWindow, 19-x-y
