### ISSUE TITLE
Frameless Window with Controls (titleBarStyle: ‘hidden’.) In WIndows OS.

### ISSUE THREAD

**Issue by JGSangara** [electron/electron#20343] opened 2019-09-25 16:34 UTC
### Problem Description
No way to implement the frameless window in Windows OS with only the controls 

### Proposed Solution
I would really appreciate a feature in electron that can only implement the frameless window without the electron name and icon to the side in windows OS like the (titleBarStyle: ‘hidden’.) feature in Mac OS

### Alternatives Considered
I have tried implementing custom NPM solutions but they really interfere with my project and make it slow in run-time 

### Additional Information
I have tried using the feature "Frame:  false"  but it does not provide the controls and also the window is not draggable.

**Comment by bsclifton** [comment] 2019-10-08 07:37
I ran into this issue myself a while ago and logged some notes in https://github.com/electron/electron/issues/6823

(includes a simple test program)

**Comment by miniak** [comment] 2019-11-10 17:05
Duplicate of #18342

**Closed by miniak** 2019-11-10 17:05 UTC
Labels: enhancement :sparkles:
