### ISSUE TITLE
Devtools errors

### ISSUE THREAD

**Issue by GitNomster** [electron/electron#14687] opened 2018-09-19 11:12 UTC
* Output of `node_modules/.bin/electron --version`: v3.0.0
* Operating System (Platform and Version): Win 10 x64
I'm using VS code for developing.

**Expected Behavior**
Working without any error.

**Actual behavior**
```
[18244:0919/160757.998:ERROR:CONSOLE(22)] "Empty response arrived for script 'chrome-devtools://devtools/remote/serve_file/@164c37e3f235134c88e80fac2a182cfba3f07f00/product_registry_impl/product_registry_impl_module.js'", source: chrome-devtools://devtools/bundled/shell.js (22)
[18244:0919/160757.999:ERROR:CONSOLE(106)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (106)
```

**To Reproduce**
Clone electron-quick-start. Start project (npm start). Open chrome dev-tools (ctrl+shift+i), switch to Network tab and punch F5. And error will appears in terminal.

**Comment by anvaynk** [comment] 2018-10-03 15:38
+1

**Comment by samuelt1** [comment] 2018-11-09 23:06
duplicate of #12185

**Comment by gmonte** [comment] 2018-11-20 14:19
+1

**Comment by GitNomster** [comment] 2018-12-21 05:06
Still persist in electron 4.0.0.

**Comment by sarthology** [comment] 2019-01-04 14:39
+1

**Comment by aestrro** [comment] 2019-01-14 01:17
+1

**Comment by Bulbousonions13** [comment] 2019-01-29 15:59
+1

**Comment by feroivanko** [comment] 2019-02-06 11:08
+1

**Comment by MrJeffLarry** [comment] 2019-02-12 11:25
+1

**Comment by richjun** [comment] 2019-02-18 13:32
Still persist in electron 4.0.3

**Comment by JiiB** [comment] 2019-03-10 22:28
+1

**Comment by ZhangZheng-GIS** [comment] 2019-03-12 01:06
+1

**Comment by praschl** [comment] 2019-03-28 18:12
+1
create-react-app --typescript + electron 4.1.1
added electron to CRA with this guide:
https://medium.com/@brockhoff/using-electron-with-react-the-basics-e93f9761f86f

**Comment by zenghongtu** [comment] 2019-04-09 05:39
+1
create-react-app --typescript + electron 4.1.3

**Comment by monika-sharma2294** [comment] 2019-04-10 05:33
I am facing the same issue in electron v4.1.4.Getting blank screen and these errors on console when hitting f5 on network tab.
Electron Version -4.1.4
OS-Windows 10
Using Visual Studio Code for development
[19770:0531/201447.419529:ERROR:CONSOLE(22)] "Empty response arrived for script 'https://chrome-devtools-frontend.appspot.com/serve_file/@7accc8730b0f99b5e7c0702ea89d1fa7c17bfe33/product_registry_impl/product_registry_impl_module.js'", source: chrome-devtools://devtools/bundled/inspector.js (22)
[19770:0531/201447.419763:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/inspector.js (105)
[19770:0531/201447.419795:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/inspector.js (105)
[19770:0531/201447.419821:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/inspector.js (105)

**Comment by ukyiwin** [comment] 2019-04-10 11:04
+1

**Comment by freedomelf** [comment] 2019-04-13 17:11
+1

**Comment by fudanglp** [comment] 2019-04-15 06:07
+1

**Comment by xmuskrat** [comment] 2019-04-16 17:20
+1

**Comment by LukeTurp** [comment] 2019-04-17 15:35
+1

**Comment by Galkon** [comment] 2019-04-27 09:41
+1

**Comment by nielsrask** [comment] 2019-05-03 06:39
+1

**Comment by mattddonovan** [comment] 2019-05-06 21:50
+1

**Comment by bthulu** [comment] 2019-05-07 16:53
still in 5.0.1

**Comment by cuixiping** [comment] 2019-05-22 07:58
same in 4.2.0
![image](https://user-images.githubusercontent.com/1104492/58157179-5b539680-7caa-11e9-8d69-2a6fe73df906.png)

**Comment by leozzyzheng** [comment] 2019-05-29 01:55
Same in
```
"electron": "^5.0.0",
"electron-debug": "^2.2.0",
```

**Comment by ridesky** [comment] 2019-06-03 07:19
+1

**Comment by AnthonyCouval** [comment] 2019-06-04 08:14
+1

**Comment by innest** [comment] 2019-06-08 03:32
+1

**Comment by galileomd** [comment] 2019-06-09 12:58
+1 grr

**Comment by codebytere** [comment] 2019-06-10 21:43
Duplicate of https://github.com/electron/electron/issues/13008.

**Closed by codebytere** 2019-06-10 21:43 UTC
Labels: 3-0-x, bug :beetle:, platform/windows

**Comment by tuxianchao** [comment] 2019-07-04 09:13
Still persist in electron 5.0.6

```
┏ Electron -------------------

  [53938:0704/170230.147482:ERROR:CONSOLE(24)] "Empty response arrived for script 'chrome-devtools://devtools/remote/serve_file/@10883df2e1a5aebd67e8b70fa71ebc5988b23b5d/product_registry_impl/product_registry_impl_module.js'", source: chrome-devtools://devtools/bundled/shell.js (24)

┗ ----------------------------
┏ Electron -------------------

  [53938:0704/170230.150957:ERROR:CONSOLE(108)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (108)

┗ ----------------------------
┏ Electron -------------------

  [53938:0704/170230.347614:ERROR:CONSOLE(108)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (108)

┗ ----------------------------
```

**Comment by IMlixingwang** [comment] 2019-08-13 07:06
"electron": "^5.0.8",

[32944:0813/150221.864:ERROR:CONSOLE(108)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (108)

**Comment by plantyoon** [comment] 2019-09-11 04:51
Still...

"electron": "^6.0.8",
[16152:0911/134252.536:ERROR:CONSOLE(5738)] "SyntaxError: Unexpected token < in JSON at position 
0", source: devtools://devtools/bundled/shell.js (5738)

**Comment by zwdgit** [comment] 2019-10-22 01:38
Still...
6.0.11
  [10548:1022/093400.306:ERROR:CONSOLE(109)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: devtools://devtools/bundled/shell.js (109)

**Comment by IhorVimmi** [comment] 2019-11-08 11:22
+1

**Comment by AlejoSalvoAbstracta** [comment] 2019-11-12 18:10
+1

**Comment by kailang-dev** [comment] 2019-11-13 08:01
still 
"electron": "^7.1.1",
Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: devtools://devtools/bundled/shell.js (109)

**Comment by KingsleyZheng** [comment] 2019-11-20 03:31
Refer to [this issue](https://github.com/electron/electron/issues/12438#issuecomment-390211011), you can solve this by changing the timing of opening devtools.
`win.loadURL('http://localhost:8080')
win.webContents.once('dom-ready', () => {
  win.webContents.openDevTools()
})`

**Comment by 13banda** [comment] 2019-11-21 08:04
+1

**Comment by MBetters** [comment] 2019-12-02 17:41
Same

**Comment by dthomascafex** [comment] 2019-12-04 09:36
Why is this issue closed? It's still happening for people, including me.

**Comment by castle321** [comment] 2019-12-04 09:47
electron 7.1.3
 [8844:1204/174125.315:ERROR:CONSOLE(109)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: devtools://devtools/bundled/shell.js (109)

**Comment by castle321** [comment] 2019-12-04 09:48
so the question is solved?

**Comment by norbertbede** [comment] 2019-12-09 09:25
same here 7.1.3

**Comment by Darius8867** [comment] 2019-12-25 07:44
Also in "electron": "^7.1.2"
[10276:1225/111005.752:ERROR:CONSOLE(109)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: devtools://devtools/bundled/shell.js (109)

**Comment by cmdevlpr** [comment] 2020-01-02 21:05
same with electron 7.1.7, issue still exists

**Comment by zhaoyao91** [comment] 2020-01-07 03:51
electron 7.1.7, webpack 4.41.5, macos

```
[49600:0107/114635.422158:ERROR:CONSOLE(109)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: devtools://devtools/bundled/shell.js (109)
```

**Comment by cppddz** [comment] 2020-01-09 07:28
same + 1
chrome:79.0.3945.88
platform:windows10 & windows 2012

**Comment by alex-cory** [comment] 2020-01-21 02:30
+1

**Comment by ido-rapid** [comment] 2020-01-22 11:11
+1

**Comment by milos-v** [comment] 2020-01-24 17:54
+1

**Comment by tbakerweb** [comment] 2020-01-28 04:10
This is appalling.   + 1

**Comment by marcosilvestroni** [comment] 2020-01-29 12:09
Stil here also in linux

**Comment by alisoncamilleri** [comment] 2020-02-01 10:28
Experiencing the same issue as well.

**Comment by Goddak** [comment] 2020-02-10 13:11
THIS ISSUE IS CLOSED BECAUSE IT'S A DUPLICATE.

POSTING HERE DOESN'T HELP! Posting +1 on an issue without reading the thread is also tragic..

@tbakerweb @marcosilvestroni @alisoncamilleri (Sorry you guys were recent)

https://github.com/electron/electron/issues/13008

**Comment by k365tv** [comment] 2020-03-11 01:26
> 我在电子版v4.1.4中遇到相同的问题。在网络标签上按f5键时，在控制台上出现黑屏和这些错误。
> 电子版-4.1.4
> OS-Windows 10
> 使用Visual Studio代码进行开发
> “脚本'chrome-devtools：//devtools/remote/serve_file/@a19d58ec502349db4b1424eb58c3ee45bc062878/product_registry_impl/product_registry_impl_module.js'的响应已到达，来源：chrome- devtools：//devtools/bundled/shell.js（24）
> [37536：0410 / 100335.048：ERROR：CONSOLE（108）]“未捕获（承诺）错误：无法实例化：ProductRegistryImpl.Registry”，来源：chrome-devtools ：//devtools/bundled/shell.js（108）
> [37536：0410 / 100335.623：ERROR：CONSOLE（108）]“未捕获（承诺）错误：无法实例化：ProductRegistryImpl.Registry”，来源：chrome-devtools：//devtools/bundled/shell.js（108）
> [ 37536：0410 / 100335.631：ERROR：CONSOLE（108）]“未捕获（承诺）错误：无法实例化：ProductRegistryImpl.Registry”，来源：chrome-devtools：//devtools/bundled/shell.js（108）

请问你是如何解决的

**Comment by xiaosu12138** [comment] 2020-03-12 13:45
same in electron 7.1.11

**Comment by rokit** [comment] 2020-03-13 00:36
I first noticed this happening when I went to the performance tab in dev tools and hit the record button. My app still seems to runs fine, but I get those annoying error messages in console. I'm using 7.1.7.

This issue was even mentioned in this performance profiling bug:
https://github.com/electron/electron/issues/14763

**Comment by rokit** [comment] 2020-03-13 00:48
I just tried out @xiaosu12138's suggestion to not open the devtools, in my `main.ts` file, and the error did go away for me. I found that the error appears when I simply visit the performance tab in dev tools.

Since Electron remembers your last visited tab in dev tools, if you last visited the performance tab, it will show the error. What worked for me is just visiting a different tab before I closed the app. Now, I can still start the app with dev tools open and won't see the error.

**Comment by YCaptain** [comment] 2020-04-03 12:14
After I updated to electron@^8.2.0, this error has gone. It bothered me when I was in electron@^7.x.x.

**Comment by yuexing0921** [comment] 2020-06-11 12:16
same in electron 7.3.1

**Comment by miyanoyuriko** [comment] 2020-06-15 03:20
Nobody solved this problem?

**Comment by kusmierczykw** [comment] 2020-06-18 16:49
same problem in v9.0.4

**Comment by miyanoyuriko** [comment] 2020-07-02 09:54
Nobody can solve it?

**Comment by schacker** [comment] 2020-08-04 02:53
> After I updated to electron@^8.2.0, this error has gone. It bothered me when I was in electron@^7.x.x.

really ?????

**Comment by schacker** [comment] 2020-08-04 08:43
After I updated to electron@^8.2.0, this error has gone.

really!

**Comment by lwj06** [comment] 2020-10-26 10:11
same in electron 4.2.12

**Comment by yyccQQu** [comment] 2020-12-25 10:15
same here 7.3.3
```
 Electron -------------------

  [2355:1225/141517.921379:ERROR:CONSOLE(7)] "[shared data] Master init failed", source: chrome-extension://vue-js-devtools/build/devtools.js (7)
  
┗ ----------------------------

┏ Electron -------------------

  [2355:1225/141518.834382:ERROR:CONSOLE(7)] "[shared data] Master init failed", source: chrome-extension://vue-js-devtools/build/devtools.js (7)
  
┗ ----------------------------

┏ Electron -------------------

  [2355:1225/141519.886906:ERROR:CONSOLE(7)] "[shared data] Master init failed", source: chrome-extension://vue-js-devtools/build/devtools.js (7)
  
┗ ----------------------------
```

**Comment by yssmile** [comment] 2021-07-27 03:51
set this
`const {app, BrowserWindow} = require('electron')
app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');
app.commandLine.appendSwitch('disable-site-isolation-trials')
app.commandLine.appendSwitch('disable-web-security')
`
It may work.
For me,it worked.

**Comment by OfirTheOne** [comment] 2022-08-26 20:34
> set this const {app, BrowserWindow} = require('electron') app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors'); app.commandLine.appendSwitch('disable-site-isolation-trials') app.commandLine.appendSwitch('disable-web-security')
> 
> It may work. For me,it worked.

thanks, but it did not worked for me
