### ISSUE TITLE
electron clipboard writeImage only png type

### ISSUE THREAD

**Issue by biosina1** [electron/electron#14916] opened 2018-10-02 03:27 UTC
I do not have an answer, so I post it again. I will delete it if there is a problem.
I use React and Elextron together.

Output of node_modules/.bin/electron --version:
[ I have verified the package.json file. ]
"electron": "2.0.2",
"electron-builder": "19.31.1",
"electron-prebuilt": "^1.4.13",
"electron-rebuild": "^1.5.11",

Operating System (Platform and Version): [ window10 ]

Expected behavior
[ jpeg type images must be saved to the clipboard.]

Actual behavior
[ An image of type png is saved to the clipboard. ]

The store can not be attached due to security reasons. Attach react source code instead.
```
copyClipboard(){
        let that = this;
        var xhr = new XMLHttpRequest();
        xhr.onload = function() {
            var reader = new FileReader();
            reader.onloadend = function() {    
     
                let image = nativeImage.createFromDataURL(reader.result);
                clipboard.writeImage(image, 'jpeg');

            }
            reader.readAsDataURL(xhr.response);
        };
        xhr.open('GET', imgURL);
        xhr.responseType = 'blob';
        xhr.send();
}
```

**Comment by ckerr** [comment] 2018-10-08 19:44
The file extensions are different, but this is a possible duplicate of https://github.com/electron/electron/issues/14647

**Comment by sofianguy** [comment] 2019-08-08 23:39
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:15
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:15 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
