### ISSUE TITLE
[Feature Request]: how to handle upload dialog in electron JS webview

### ISSUE THREAD

**Issue by ashkan21** [electron/electron#32586] opened 2022-01-23 09:47 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

In electron JS web view , when we click on an input file element a attach dialog will be showed I need to handle this dialog to cancel or attach file but I checked electron document but it doesn't have any method how can I handle it?

### Proposed Solution

this is need a handler

### Alternatives Considered

handle web input file

**Comment by codebytere** [comment] 2022-01-24 11:43
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-01-24 11:44
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.

**Closed by codebytere** 2022-01-24 11:44 UTC
Labels: enhancement :sparkles:
