### ISSUE TITLE
Bad threads support

### ISSUE THREAD

**Issue by Inomezi** [electron/electron#20550] opened 2019-10-12 10:08 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 6.0.11 and v7.0.0-beta.6
* **Operating System:**
 MacOs Mojave Version 10.14.5

### Expected Behavior
Hi, I need to create a multi-threaded application. I used two threads options, but both don't work.
First option is `worker_threads` https://nodejs.org/api/worker_threads.html
Second option is web workers https://electronjs.org/docs/tutorial/multithreading

### Actual Behavior
When i used `worker_threads` i got this error: `Uncaught Error: The V8 platform used by this instance of Node does not support creating Workers`
When i used `web workers` I ran into a threads creation limit. I can create max 240-243 threads, but when i add 1 more thread - it crash. I have free 7 GB RAM, but it crush anyway. Btw, in activity monitor it'll show x2 threads count, than i created. If i created 240 threads - it'll show 480+ threads in activity monitor

### To Reproduce
1. For reproduce `worker_threads` error:
`
const { Worker } = require("worker_threads")
new Worker("./src/workers/profile.js")` // need provide a path to file
2. For reproduce `web workers` error:
`
for( let i = 0 ; i < 250 ; i ++ ) {
  new Worker("./src/workers/profile.js") // need provide a path to file
} // 240 = no crush, 250 will crush
`

### Screenshots
1. `worker_threads`

![image](https://user-images.githubusercontent.com/24946599/66699551-935a8500-ecf0-11e9-884e-fc589e1e7d15.png)

2. `Web workers`

This screenshot shows that were created x2 threads, than I actually create (as I described above).  Were created 240 threads, but in fact 486 is displayed
![image](https://user-images.githubusercontent.com/24946599/66699513-378ffc00-ecf0-11e9-8c63-4760b39160c1.png)

This screenshot shows what happens when I add one thread, after creating 240 web workers
![image](https://user-images.githubusercontent.com/24946599/66699533-6b6b2180-ecf0-11e9-9b93-5e505664cf66.png)

### Additional Information
If i can provide more info for you - tell me it please !

**Comment by codebytere** [comment] 2019-10-13 14:42
Duplicate of https://github.com/electron/electron/issues/18540.

**Closed by codebytere** 2019-10-13 14:42 UTC

**Comment by Inomezi** [comment] 2019-10-13 16:29
> Duplicate of #18540.

Hi, my issue not only about `worker_threads` , my issue about `web workers` too, it don't work for me. Please, read carefully

**Comment by mubaidr** [comment] 2023-06-28 21:55
Any update about this issue? IT still shows this message trying to initialize worker_thread.

**Comment by sun-xm** [comment] 2024-08-27 07:35
Seems worker_threads works fine in vscode extensions which is electron based i believe. But I have the same problem in my own electron app. What's the difference?

**Comment by sun-xm** [comment] 2024-08-28 07:15
Looks like worker_threads can only work in main process. In render process web workers should be used. The reason why worker_threads works fine in vscode extensions is that extension is running in main process of a vscode extension server, I guess.
