### ISSUE TITLE
[Bug]: The drop-down option of console performace crashes with a click.

### ISSUE THREAD

**Issue by huangruiqi** [electron/electron#44157] opened 2024-10-09 03:41 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.0,32.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

mac os 13.4 (22F66)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

28.0.0

### Expected Behavior

Drop-down options that can use performace normally.
![Image](https://github.com/user-attachments/assets/2373c28a-dd2b-4644-8be5-5103ff75291f)

### Actual Behavior

When you click the console drop-down option, it will crash.
![Image](https://github.com/user-attachments/assets/2373c28a-dd2b-4644-8be5-5103ff75291f)

**Comment by jkleinsc** [comment] 2024-10-09 19:15
@huangruiqi can you provide more details as to exactly what steps you are following to reproduce this crash? I just tried this via Electron Fiddle on Electron 32.0.0 and I cannot reproduce the crash.

**Comment by nikwen** [comment] 2024-10-10 01:45
Also wasn't able to reproduce on macOS 14.7 (arm64).

**Comment by huangruiqi** [comment] 2024-10-10 06:57
> [@huangruiqi](https://github.com/huangruiqi) can you provide more details as to exactly what steps you are following to reproduce this crash? I just tried this via Electron Fiddle on Electron 32.0.0 and I cannot reproduce the crash.

Just open the console and click the performance drop-down box to see it. actually, The version of electron is 31.0.2.
Is your computer system mac arm? It can work normally under the Windows system.

**Comment by jkleinsc** [comment] 2024-10-10 15:14
@huangruiqi I just tested 31.0.2 on mac arm and it works fine for me:
![Image](https://github.com/user-attachments/assets/54e43b2f-42bc-430f-a145-625a0de6d934)

**Comment by huangruiqi** [comment] 2024-10-11 03:27
> [@huangruiqi](https://github.com/huangruiqi) I just tested 31.0.2 on mac arm and it works fine for me: ![Image](https://github.com/user-attachments/assets/54e43b2f-42bc-430f-a145-625a0de6d934)

Excuse me, can you try the 31.6.0 version? This version of the demo will inevitably flash back.
However, I used version 32.0.0 to solve this problem. I can upgrade it. Thank you.

**Comment by codebytere** [comment] 2024-10-15 13:11
Closing as an upstream issue since resolved on 32. If that's not the case, please let us know and we can re-open this issue.

**Closed by codebytere** 2024-10-15 13:11 UTC
Labels: platform/macOS, blocked/need-info ❌, bug :beetle:
