### ISSUE TITLE
[Bug]: savePage no generated files 

### ISSUE THREAD

**Issue by fatwolf** [electron/electron#32696] opened 2022-02-01 10:44 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

Windows

### Operating System Version

WIN10 20H2

### What arch are you using?

x64

### Expected Behavior

 win.webContents.savePage('d:/aaaaaa.html', 'HTMLComplete').then(() => {
      console.log('Page was saved successfully.')
    }).catch(err => {
      console.log(err)
    })

it will generate a html page file at d: 

### Actual Behavior

savePage has three formats that can be used

if use HTMLComplete
 only produced a aaaaaa_files empty folder

if use HTMLonly 
No files are generated nor error callbacks are generated

MHTML option works fine

**Comment by codebytere** [comment] 2022-02-02 18:37
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-02-03 09:25
@fatwolf i tried to reproduce with https://gist.github.com/53c778864f931bcf1b524685d7ce8ea2 and could not.

**Comment by fatwolf** [comment] 2022-02-03 10:28
> @fatwolf i tried to reproduce with https://gist.github.com/53c778864f931bcf1b524685d7ce8ea2 and could not.

Thanks for the quick reply
I use your code to solve the problem
After comparison, savePage does not work properly when using relative paths
If you change your test case to


  const p1 = path.join(__dirname, '1.html')
  await reportWin.webContents.savePage("1.html", 'HTMLOnly')

  const p2 = path.join(__dirname, '2.html')
  await reportWin.webContents.savePage("2.html", 'HTMLComplete')

  const p3 = path.join(__dirname, '3.html')
  await reportWin.webContents.savePage("3.html", 'MHTML')


it will only generate 3.html

**Comment by codebytere** [comment] 2022-02-03 10:44
@fatwolf interesting 🤔 

if i do:

```js
async function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  await mainWindow.loadFile('index.html')

  const p1 = path.join(__dirname, '1.html')
  await mainWindow.webContents.savePage('1.html', 'HTMLOnly')

  const p2 = path.join(__dirname, '2.html')
  await mainWindow.webContents.savePage('2.html', 'HTMLComplete')

  const p3 = path.join(__dirname, '3.html')
  await mainWindow.webContents.savePage('3.html', 'MHTML')


  const allCreated = [p1, p2, p3].every(p => {
    const e = fs.existsSync(p)
    if (!e) {
      console.log(`File at path ${p} does not exist`)
    }
    return e
  })

  process.exit(allCreated ? 0 : 1)
}
```

it still exits with 0, indicating it properly saved all the pages on macOS, but on Windows, it fails like you're saying. At minimum, this is something that should be specified in documentation, but ulttimately we should ensure that behavior is consistent across platforms. Thanks for the catch! in the meantime, I recommend using absolute pathing.

**Comment by codebytere** [comment] 2022-02-03 13:06
@fatwolf i reopened so that I can properly close this with a PR to fix the underlying issue.

**Closed** 2022-02-07 08:52 UTC
Labels: platform/windows, bug :beetle:, 16-x-y
