### ISSUE TITLE
[Bug]: the fse.copy() function failed sometimes after updating from 5.10.0 to 11.2.3

### ISSUE THREAD

**Issue by hz0324** [electron/electron#29520] opened 2021-06-03 08:26 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

5.10.0

### Expected Behavior

When use fse.copy() function to copy a file from one location to another, it should works.

### Actual Behavior

It seems like, on 11.2.3, fse.copy() will stop working sometimes, without any error or warning. It's like the app doesn't have the permission to perform the operation. On 5.10.0, the same code works perfectly.

Here is more information.
1.Not everyone will encounter this BUG.
2.For some people, they can temporarily solve this problem by restarting the app. The bug will show up afterwards.
3.For some people, even restarting the app will not solve this problem.
4.This bug is only found on Windows OS.

### Additional Information

Our app is a book reading app. We updated the version of electron from 5.10 to 11.2.3 last month.
We have got a lot of complaints about "can not add new books to the library sometimes." after the update.
Our team member has encountered the same problem once, but we cannot reproduce it afterwards.
Right now, we have narrowed down the problem to following functions fse.copy(). 

It seems like, on 11.2.3, fse.copy() will stop working sometimes, without any error or warning. It's like the app doesn't have the permission to perform the operation. On 5.10.0, the same code works perfectly.

**Comment by MarshallOfSound** [comment] 2021-06-03 08:55
This is a duplicate of #29489 and although this one follows the template it is still not actionable and is therefore a request for generic help rather than a bug report.

Without a repro case or other supporting information like an actual error trace there's nothing we can do here.  I'll mark this as blocked needs repro and if it's still like that in a week or so our automation will close this issue.  Our backlog is huge, if the issue isn't actionable there's not a lot we can do.

**Comment by zcbenz** [comment] 2021-06-16 08:46
I'm closing this issue since we are unable to debug it with provided information.

**Closed by zcbenz** 2021-06-16 08:46 UTC
Labels: blocked/need-repro, bug :beetle:
