### ISSUE TITLE
[Bug]: electron app not sending device id to sign-in server

### ISSUE THREAD

**Issue by nsainath21** [electron/electron#32112] opened 2021-12-06 08:18 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro version 20H2 OS build 19042.1237

### What arch are you using?

x64

### Expected Behavior

requirement is to make electron app send proper device fingerprint (id) to Sign-in server (azure AD)
The request URL should successfully open in Browser Window. 

### Actual Behavior

The requested URL does not open and no device id found in Azure AD logs.
![deviceinfo](https://user-images.githubusercontent.com/95610470/144811221-490f44cb-a1ae-4365-985f-35ecbc0c10f8.png)

### Additional Information

User agent used : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 Edg/95.0.1020.30 SynappxMeeting/3.1.0
Electron App

**Comment by codebytere** [comment] 2022-01-10 15:04
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-01-20 09:25
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-01-20 09:25 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, 11-x-y
