### ISSUE TITLE
[Bug]: Unable to load preload script due enable sandbox by default

### ISSUE THREAD

**Issue by oalfroukh** [electron/electron#36437] opened 2022-11-24 14:42 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19041

### What arch are you using?

x64

### Last Known Working Electron version

19.1.6

### Expected Behavior

Loading preload script without issues.

### Actual Behavior

Unable to load preload script due to `Error: module not found: inversify`

### Additional Information

- We are using [InversifyJS ](https://github.com/inversify/InversifyJS)library to inversion of control (IoC) container for TypeScript in both the main and renderer process in our project, it's OK on the `main process` while not on the `renderer process`.

- Electron `v20` has a breaking change https://github.com/electron/electron/pull/35125 , after enabling `sandbox` we got an error `Error: module not found: inversify` that will prevent loading the `preload script`, while when disabling `sandbox` will be OK, but we would like to apply Electron recommendations for the security on our app.

![image](https://user-images.githubusercontent.com/80884942/203805079-4b53e521-9152-4bd5-96e4-f2e979e1522e.png)

- I can not attach `Electron Fiddle project` that doesn't support `ts`, Here is a [quick app](https://github.com/oalfroukh/electron-quick-start-typescript) on GitHub to reproduce the issue

** Edit: Here is [Electron Fiddle project](https://gist.github.com/06757370c62cb787f6eb239c9f34b57f) with the same issue when using `jszip` library.

**Comment by VerteDinde** [comment] 2022-11-28 07:26
Hey @oalfroukh, thanks for reporting this issue! This is happening because your preload script is trying to use node in the renderer process, which Electron no longer allows by default. It's not technically a bug; this is by design.

Like you mentioned above, you can get around this in the short-term by explicitly specifying `sandbox: false` for the relevant renderer processes. In the longer term, we'd recommend refactoring the renderer process to remove Node usage. You can read more about [the breaking change here (link)](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#default-changed-renderers-without-nodeintegration-true-are-sandboxed-by-default) and the reasoning behind [why we're doing this here (link)](https://github.com/electron/electron/issues/28466#issuecomment-812107261).

Since this isn't technically a bug, I'm going to close this issue, but if you'd like to discuss further, let me know and I can reopen it. Thanks!

**Closed by VerteDinde** 2022-11-28 07:26 UTC
Labels: bug :beetle:

**Comment by pranavwani** [comment] 2024-02-05 12:06
> Hey @oalfroukh, thanks for reporting this issue! This is happening because your preload script is trying to use node in the renderer process, which Electron no longer allows by default. It's not technically a bug; this is by design.
> 
> Like you mentioned above, you can get around this in the short-term by explicitly specifying `sandbox: false` for the relevant renderer processes. In the longer term, we'd recommend refactoring the renderer process to remove Node usage. You can read more about [the breaking change here (link)](https://github.com/electron/electron/blob/main/docs/breaking-changes.md#default-changed-renderers-without-nodeintegration-true-are-sandboxed-by-default) and the reasoning behind [why we're doing this here (link)](https://github.com/electron/electron/issues/28466#issuecomment-812107261).
> 
> Since this isn't technically a bug, I'm going to close this issue, but if you'd like to discuss further, let me know and I can reopen it. Thanks!

Hi @VerteDinde 

What if i disabled sandox, enable **ContextIsolation to true** and want to use **require** API to import relative module/script? Does it also cause issue in future as you suggested to refactor renderer process to remove Node.js usge.

**main.js**
```js
const windowConfig = {
        width: winState.width,      
        height: winState.height,
        x: winState.x,
        y: winState.y, 
        show: false,
        webPreferences: {
            sandbox: false,
            contextIsolation: true,
            preload: path.join(__dirname, `preload.js`)
        }
    }
```

**preload.js**
```js
const { contextBridge } = require('electron');
const module = require('./module')

contextBridge.exposeInMainWorld('api', {
     module
})
```
