### ISSUE TITLE
[Feature Request]:  Same default value for --unhandled-rejections as Nodejs: --unhandled-rejections=throw

### ISSUE THREAD

**Issue by SimonSiefke** [electron/electron#36528] opened 2022-12-01 13:44 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron uses a different unhandled rejection behaviour than Nodejs:

Default Values: 
- Electron: `--unhandled-rejections=warn`
- Nodejs: ` --unhandled-rejections=throw`

This leads to different output:

```js
const main = async () => {
  throw new Error("oops");
};

main();
```

### Nodejs

```
// node index.js
/tmp/node-unhandled/index.js:2
  throw new Error("oops");
  ^

Error: oops
    at main (/tmp/node-unhandled/index.js:7:9)
    at Object.<anonymous> (/tmp/node-unhandled/index.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.1
```

### Electron

```
// npx electron .
(node:55195) UnhandledPromiseRejectionWarning: Error: oops
    at main (/tmp/node-unhandled/index.js:2:9)
    at Object.<anonymous> (/tmp/node-unhandled/index.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at loadApplicationPackage (/tmp/node-unhandled/node_modules/electron/dist/resources/default_app.asar/main.js:121:16)
    at Object.<anonymous> (/tmp/node-unhandled/node_modules/electron/dist/resources/default_app.asar/main.js:233:9)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:55195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

The different behaviour can be unexpected, for example in this issue https://github.com/electron/electron/issues/36526

### Proposed Solution

Not overriding the default value for `--unhandled-rejections`: This would mean that Electron's and nodejs behaviour for unhandled rejections would always be aligned.

### Alternatives Considered

Providing an option to set the Nodejs flag `--unhandled-rejections=throw`

Some Nodejs options are already configurable: https://www.electronjs.org/docs/latest/api/environment-variables#production-variables `unhandled-rejections` could be added to the list of configurable options

**Comment by nornagon** [comment] 2022-12-01 18:15
I believe it is an intentional design decision to diverge from Node here, see e.g. https://github.com/electron/electron/pull/29244#issuecomment-860735951, so I'm going to close this as not planned / working as intended.

**Closed by nornagon** 2022-12-01 18:15 UTC
Labels: enhancement :sparkles:
