### ISSUE TITLE
use electron 9.1.1 open a pdf url dialog , press print button always hang 

### ISSUE THREAD

**Issue by Lawrence0528** [electron/electron#24720] opened 2020-07-24 06:52 UTC
use electron 9.1.1 open a pdf url dialog , press print button always hang 

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  *

**Comment by aashutoshrathi** [comment] 2020-07-24 10:31
I am able to reproduce this on Windows 10.

**Comment by mohitkyadav** [comment] 2020-07-24 11:03
@Lawrence0528  this also happens with me in Windows, Mac and Linux.

**Comment by codebytere** [comment] 2020-07-24 16:38
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by Lawrence0528** [comment] 2020-07-27 01:55
[https://github.com/electron/electron/issues/24458](url)

ISSUE 24458 can reproduce same problem

**Comment by codebytere** [comment] 2020-07-27 01:57
Closing as duplicate of https://github.com/electron/electron/issues/24458

**Closed by codebytere** 2020-07-27 01:57 UTC
Labels: blocked/need-info ❌
