### ISSUE TITLE
Black border around webFrame

### ISSUE THREAD

**Issue by bennyn** [electron/electron#9419] opened 2017-05-10 14:26 UTC
* Electron version: 1.6.8 (Chromium 56.0.2924.87)
* Operating system: Windows 10

### Expected behavior

No black border around `about:blank` page.

### Actual behavior

Black border around `about:blank` page.

### How to reproduce

Just by using Electron v1.6.8 we recognized that [our app](https://github.com/wireapp/wire-desktop) has a black frame rendered around the `webFrame`. The frame shows up even when navigating to `about:blank`:

![screenshot](https://cloud.githubusercontent.com/assets/469989/25903582/1bf83c76-359d-11e7-9676-d5f2eb0ef894.png)

On a co-worker's laptop I also saw that such frame can appear even in Chrome (screenshot taken from Chrome v58):

![screenshot-2](https://cloud.githubusercontent.com/assets/469989/25903644/5461f700-359d-11e7-8eda-60dada67c384.png)

Is this a Chromium issue or is it related to Electron?

**Comment by kevinsawicki** [comment] 2017-05-15 17:02
> Just by using Electron v1.6.8 we recognized that our app has a black frame rendered around the webFrame. 

Are you able to provide more instructions for reproducing this? Like a minimal sample app.

**Comment by davidwr** [comment] 2017-08-29 18:56
Same problem here when I move the application window.

**Comment by pushkin-** [comment] 2017-08-31 22:34
I don't have a minimal example at this point, but I see this when I create a non-centered window, point it to some page, then call `window.center()`.

Update: I don't see this behavior anymore...

**Comment by codebytere** [comment] 2017-09-27 01:19
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:19 UTC
Labels: more-information-needed

**Comment by tsyopa** [comment] 2018-02-09 11:11
I my code this bug appears if I do `win.setResizable(false);`.

**Comment by orionlu0916** [comment] 2018-05-11 02:47
as @pushkin- said, if you use "win.setResizable(false)" just add "win.center()" after it, which makes the black border gone.

**Comment by takashi1kun** [comment] 2018-12-11 11:46
It happens to me and adding win.center() after win.setResizable(false) does not solve it for me at least

**Comment by francoisdutoit** [comment] 2019-03-29 21:09
@takashi1kun Have you found a resolution to this issue? - I'm having the same issue. win.center() also makes no difference for me...

**Comment by francoisdutoit** [comment] 2019-03-29 21:13
@takashi1kun I'm having the same issue - win.center() does not make a difference. Have you managed to resolve it at all using another method?

**Comment by LuisTibayan** [comment] 2019-05-09 07:26
work around that worked for me is to not use the win.setResizable(false) and used the will-resize event instead.

 win.on('will-resize', (e) => {
    //prevent resizing even if resizable property is true.
      e.preventDefault();
  });

**Comment by oonqt** [comment] 2019-08-11 23:18
Noticing this as well, still no fix after a year

**Comment by papb** [comment] 2020-04-21 14:19
I also experience this black border, but it just lasts about half a second, upon startup, then it goes away. Is this what everyone else has been experiencing as well? Or in your case the border is there forever?

**Comment by Borderliner** [comment] 2020-06-28 20:30
If you don't want to change this property later, you can pass `resizable` boolean to `BrowserWindow`:
```
mainWindow = new BrowserWindow({
    width: 1000,
    height: 563,
    useContentSize: true,
    center: true,
    // Here
    resizable: false
});
```
