### ISSUE TITLE
[Feature Request]: hide 'path' property of File from web content

### ISSUE THREAD

**Issue by 8HoLoN** [electron/electron#29175] opened 2021-05-14 16:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.4

### What operating system are you using?

Windows

### Operating System Version

W10P 20h2 19042.985

### What arch are you using?

x64

### Expected Behavior

There should be an option to not enable fullpath but only name (like on chromium).

### Actual Behavior

The fullpath seems to be always available whatever the flags sandbox or node_integration is set.

**Comment by nornagon** [comment] 2021-07-13 19:07
We currently enable this unconditionally: https://github.com/electron/electron/blob/main/patches/chromium/blink_file_path.patch

unfortunately, making this conditional would be a breaking change. I think it's a reasonable thing to do though; I would like to remove this patch.

I'd prefer that instead of making the path available to web content, there would be a privileged API to call (e.g. only available from the isolated context) which would provide the path.

**Comment by MarshallOfSound** [comment] 2022-11-13 12:17
Duplicate of https://github.com/electron/electron/issues/35094

**Closed by MarshallOfSound** 2022-11-13 12:17 UTC
Labels: enhancement :sparkles:
