### ISSUE TITLE
[Bug]: ERROR:sandbox_linux.cc(376) InitializeSandbox() called with multiple threads in process gpu-process.

### ISSUE THREAD

**Issue by raphael10-collab** [electron/electron#32701] opened 2022-02-01 14:34 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04 Desktop

### What arch are you using?

x64

### Expected Behavior

No error messages about `multiple threads in process gpu-process`

### Actual Behavior

I'm getting this error message:

    [153499:0201/151406.499268:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-
    process.

### Additional Information

Searching around about this kind of error message, I found that it might be related with chrome drivers : 
https://github.com/bitpay/wallet/issues/8768

What libraries should I then upgrade in order to remove this kind of errors?

**Comment by ckerr** [comment] 2022-02-01 18:30
This is a dupe of https://github.com/electron/electron/issues/31491

**Closed by ckerr** 2022-02-01 18:30 UTC
Labels: bug :beetle:
