### ISSUE TITLE
Reproducible crash on focus window after idle

### ISSUE THREAD

**Issue by vikrantpogula** [electron/electron#5112] opened 2016-04-11 11:10 UTC
* Electron version: v0.37.5
* Operating system: OSX 10.11.3, Windows 8 (32-bit build), Windows 10 (32-bit build)

Reproducible crash with error :  `Check failed: Alive == liveness`.
Occurs window is left out of focus for a while and then brought into focus. Everything works normally at electron `v0.36.4`

Sometimes the difference in the check failed error is very large also ( ie i just got `ALIVE == liveness (3390155539 vs. 2110)`)

Im attaching a stack trace from OSX when it happens:
```
[8380:0411/153412:FATAL:net_log.cc(490)] Check failed: ALIVE == liveness (3390155539 vs. 3735928559)
0   Electron Framework                  0x0000000109ee30b3 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 391203
1   Electron Framework                  0x0000000109ef9579 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 482537
2   Electron Framework                  0x000000010b36a8fb _CTFontManagerUnregisterFontForData + 10336347
3   Electron Framework                  0x000000010b36fa82 _CTFontManagerUnregisterFontForData + 10357218
4   Electron Framework                  0x0000000109dd5c9a _ZNK4base8CallbackIFviEE3RunERKi + 42
5   Electron Framework                  0x0000000109dc2d32 _ZN4base8internal12InvokeHelperILb0EvNS_8CallbackIFviEEENS0_8TypeListIJRKN3net5ErrorEEEEE8MakeItSoES4_S9_ + 34
6   Electron Framework                  0x0000000109dc2cfd _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0EEEENS0_9BindStateINS_8CallbackIFviEEES6_JN3net5ErrorEEEENS0_8TypeListIJNS0_12UnwrapTraitsIS9_EEEEENS0_12InvokeHelperILb0EvS7_NSB_IJRKS9_EEEEEFvvEE3RunEPNS0_13BindStateBaseE + 61
7   Electron Framework                  0x0000000109ee35ca _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 392506
8   Electron Framework                  0x0000000109f02149 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 518329
9   Electron Framework                  0x0000000109f02688 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 519672
10  Electron Framework                  0x0000000109ed8451 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 347073
11  Electron Framework                  0x0000000109f12de3 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 587091
12  Electron Framework                  0x0000000109f018ed _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 516189
13  Electron Framework                  0x000000010a5264e8 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 6958168
14  Electron Framework                  0x000000010a5265f7 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 6958439
15  Electron Framework                  0x0000000109f32e88 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 718328
16  Electron Framework                  0x0000000109f2ef1c _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 702092
17  libsystem_pthread.dylib             0x00007fff8bb46c13 _pthread_body + 131
18  libsystem_pthread.dylib             0x00007fff8bb46b90 _pthread_body + 0
19  libsystem_pthread.dylib             0x00007fff8bb44375 thread_start + 13
``` 

Please let me know if theres anything else you need.

**Comment by zcbenz** [comment] 2016-04-12 05:23
The check was added by Chromium to get the stack trace of a certain bug, but I don't have permissions to view that bug because bugs related to crashes are security related.

You can probably work out a reproducible example and I'll see if it is possible to work around it in Electron, or you can wait for next release of Chrome browser and see whether it has been fixed by Chrome team.

**Comment by vikrantpogula** [comment] 2016-04-12 12:07
@zcbenz thanks for your help ! i will try to get a repo up with just the bug or just build with an older version of chrome. Preliminary tests show that it may have to do with the network reconnection / idle timeout, because the crash also happens after resume from sleep.

**Comment by zcbenz** [comment] 2016-06-14 05:21
@vikrantpogula Does this still happen for you in latest versions of Electron?

**Closed** 2016-06-21 07:47 UTC
Labels: blocked, bug, crash
