### ISSUE TITLE
[Bug]: Bluetooth requestDevice not working on Electron 13

### ISSUE THREAD

**Issue by zeenfaizpy** [electron/electron#29554] opened 2021-06-06 08:55 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version 2004

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0

### Expected Behavior

navigator.bluetooth.requestDevice({acceptAllDevices: true})should scan the BLE devices and returns it.
But it worked in MacOS.

### Actual Behavior

navigator.bluetooth.requestDevice({acceptAllDevices: true}) is not returning anything and keeps scanning.
It is not working in windows only and worked in MacOS.

**Comment by jkleinsc** [comment] 2021-06-07 17:58
this is a duplicate of #28185.  Closing in favor of that issue.

**Closed by jkleinsc** 2021-06-07 17:58 UTC
Labels: bug :beetle:

**Comment by bierzorutas** [comment] 2021-06-16 17:30
Problem present also here, other issue closed due another issue that is not related with this case... Easy way to decrease opened issues ....
