### ISSUE TITLE
Cookie is not saved on application close

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#8416] opened 2017-01-16 09:18 UTC
* Electron version: 1.4.14
* Operating system: Windows

Hi!
I faced with issue described in this two comments: 
https://github.com/electron/electron/issues/6388#issuecomment-236498471
https://github.com/electron/electron/issues/6388#issuecomment-244483403
The main issue is fixed, but the session is lost if the app is closed immediately after login and setting the cookie.

### Expected behavior
Cookie should be saved.

### Actual behavior
When the app is closed after less then 10-15 seconds a cookie is set, it is not saved when the app is reopened.

**Comment by LoganDark** [comment] 2017-01-16 11:57
Isn't that what `localStorage` is for?

**Comment by clusterberries** [comment] 2017-01-16 13:59
@LoganDark could you please explain for what purpose localStorage should be used in this case?

**Comment by LoganDark** [comment] 2017-01-16 14:43
Persistent data storage.

**Comment by clusterberries** [comment] 2017-01-16 14:54
Yes, I use it as data storage. But I'm talking about session, cookies are used in this case.

**Comment by LoganDark** [comment] 2017-01-16 16:11
If you need it to persist when the app is reopened, use localStorage or a file

**Comment by TimNZ** [comment] 2017-01-18 01:11
@clusterberries is referring to my comment on testing on BrowserWindow or webview session persistence when an Electron app is closed seconds after a change to session data.

Basically there's a small window of a few seconds when changes to cookies (perhaps other things) are not persisted and are lost if the app is closed in the meantime.

**Comment by ButzYung** [comment] 2017-01-18 08:06
I am affected by the same problem. I wonder if there can be a workaround for now, like saving the current session of cookies to localStorage or file before the app closes, and then restore it on app restart.

**Comment by TimNZ** [comment] 2017-01-18 08:21
I think the easiest thing to do in short term is try to introduce a delay before quitting the app.
You can hide any windows first, delay, then quit.

Users won't care.

**Comment by LoganDark** [comment] 2017-01-18 16:58
@ButzYung That was my idea at first, but nobody seemed to understand.

**Comment by deepak1556** [comment] 2017-01-19 07:21
@clusterberries can you provide a minimal example to reproduce the issue ? Also @TimNZ if you are still facing the webview issue can you open a new issue with a reproducible example ? Thanks!

Have you tried the `session.flushStorageData` api ?

**Comment by juturu** [comment] 2017-04-14 04:39
I'm noticing this issue with electron 1.6.2. I tried `session.flushStorageData` without any luck. 

Looking into chromium issues, found [this](https://bugs.chromium.org/p/chromium/issues/detail?id=496564&can=1&q=component%3AInternals%3ENetwork%3ECookies%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&start=100). Delaying the restart by 30s resolved the issue for me. Should this limitation be removed from electron or make `flushStorageData` update sqlite db? @kevinsawicki @deepak1556

**Comment by deepak1556** [comment] 2017-04-14 05:20
Thanks @juturu for confirming!

> Should this limitation be removed from electron or make flushStorageData update sqlite db? 

Changing the commit interval in general will cause some perf regressions. Currently `session.flushStorageData` seems to only be flushing localstorage data to disk. We need to implement flushing cookie store with it. This can be achieved by calling [net::CookieStore::FlushStore](https://cs.chromium.org/chromium/src/net/cookies/cookie_store.h?q=flushsto&l=208) api.

**Closed** 2017-04-18 16:09 UTC
Labels: enhancement

**Comment by danielravina** [comment] 2018-04-24 07:08
Hey I think the issue is not fixed. I can reproduce the error consistently on `v1.8.4`.

**Comment by SergitoBcn** [comment] 2018-10-03 08:13
Which version of Electron has the issue fix included?

**Comment by julian-alarcon** [comment] 2018-11-23 15:43
@danielravina Did you tried electron 3 or 2 (or version 4) to check if the issue is still present?

**Comment by lq-manh** [comment] 2019-04-08 03:37
Any update? I'm on electron 3.1.8 and this annoying bug is still present.

**Comment by mrmign** [comment] 2019-06-18 03:43
I use Electron 5, and this bug is still there. When you close the app, cookies are cleared.

**Comment by twinslizzy** [comment] 2019-09-06 02:46
any update? I use electron v4.1.3, cookie is not flushed when close app

**Comment by dengyaolong** [comment] 2019-09-06 03:05
the bug still there. And I  need to write a lot of workaround before quit and after start...

**Comment by jianzhiyao** [comment] 2019-10-14 09:15
still the same

**Comment by jianzhiyao** [comment] 2019-10-14 09:59
> the bug still there. And I need to write a lot of workaround before quit and after start...

May i ask some examples for cookie persistence? thx

**Comment by FinlayDaG33k** [comment] 2019-12-03 19:35
electron 6.0.10 also has this issue still...

**Comment by robbylucia** [comment] 2020-01-03 16:08
electron 5.0.10 has this issue. I'm using **localStorage** to store the data I need to persist between sessions.

**Comment by stuartambient** [comment] 2020-03-25 19:43
Version 7,1.11 problem still exists.  It seems to be working at times but not consistently.  
I was under the impression that setting the session partition to persist meant it would between sessions.

**Comment by logidelic** [comment] 2020-04-28 13:42
I too have been bitten by this one (explains some mysterious issues I've observed in the past too).

Is there a workaround (other than waiting an arbitrary amount of time) in Electron 7.x?

I see from the docs that in Electron 8 there is `cookies.flushStore()`... Does that fix the issue?

**Comment by fer-fullstackdev** [comment] 2020-05-07 17:02
I also face this damn issue. There is nobody to fix this issue in Electron Company???

**Comment by logidelic** [comment] 2020-05-07 17:55
FWIW, `cookies.flushStore()` did seem to help things for me, but I needed to run it both before and after the navigation changed... I didn't have time to investigate further...

**Comment by fer-fullstackdev** [comment] 2020-05-07 17:58
Thanks for your reply.. @logidelic 
How about if we add it app's 'before-quit' event?
Do you think that it will work?

**Comment by u1aryz** [comment] 2020-08-01 12:31
I had the same problem with the defaultSession in electron 5.0.13.
I solved it by using partition.

```
const win = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    partition: 'persist:yourname',
  },
});
```

**Comment by AndrewSouthpaw** [comment] 2020-09-11 22:12
We ran into a similar problem (albeit not on electron), and our issue was that our cookie storing our session didn't have an expiration date, which meant it was a "session cookie" and would clear when the browser app closed. (For whatever reason, this behaved inconsistently on desktop, but was consistent on Android and iOS.) Setting an explicit expiration date for our cookie fixed the issue.

**Comment by Deepakmukka1** [comment] 2021-07-26 09:55
@u1aryz can you explain your solution cause , using partition  is showing the same default behavior , session is not being persistent

**Comment by jeannen** [comment] 2023-09-05 00:43
Still have the same issue on Electron 25
