### ISSUE TITLE
event.sender.send doesn't send message back to render process on Windows

### ISSUE THREAD

**Issue by changkun** [electron/electron#7455] opened 2016-10-03 05:16 UTC
* Electron version: 1.4.2 or Any
* Operating system: Windows & macOS

I'm creating a custom menu. One of menu item (`test2`) should be disable when receive a message from `event.sender.send`. However the behavior of `event.sender.send` doesn't as expected on Windows.

![](http://ww1.sinaimg.cn/large/73406662gw1f8f05zj7j7j20aw09c3z4.jpg)

I'm also tested this code on macOS, it works fine, which means **the code behavior on Windows doesn't as same as on macOS**.

![](http://ww4.sinaimg.cn/large/73406662gw1f8f068mhudj20bk062mxj.jpg)

Here is my code snippet: 

```js
//
// package.json
//
{
  "name": "electron-test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "electron index.js"
  },
  "devDependencies": {
    "electron": "1.4.1"
  }
}

//
// index.js
//
'use strict'
const {app, BrowserWindow, ipcMain} = require('electron');

let win;
function createWindow() {
    win = new BrowserWindow({
        webPreferences: {
          preload: `${__dirname}/preload.js`,
        }
    });
    win.loadURL(`https://github.com`);
    win.on('closed', () => {
        app.exit(0);
    });
}

app.on('ready', createWindow);
ipcMain.on('menu', (event, status) => {
  switch(status) {
    case 'created':
      console.log(status);
      event.sender.send('menu', 'disable');
      break;
  }
});

//
// preload.js
//
'use strict';

const menu = require('./menu');
const {ipcRenderer} = require('electron');

menu.createMenu();
ipcRenderer.send('menu', 'created');

//
// menu.js
//
'use strict';

const electron = require('electron');
const remote   = electron.remote;
const Menu      = remote.Menu;
const ipcRenderer = electron.ipcRenderer;

function createMenu() {
    let menu = [{
  	  label: 'options',
  	  submenu: [{
	        label: 'test1'
  	    }, {
	        label: 'test2'
  	    }, {
          label: 'dev-tool',
          click: (item, focusedWindow) => {
            if (focusedWindow)
              focusedWindow.toggleDevTools();
          }
        }
   	  ]
    }];
    menu = Menu.buildFromTemplate(menu);
    Menu.setApplicationMenu(menu);
    ipcRenderer.on('menu', (event, arg) => {
      console.log('menu message reviced'); // appear on macOS, not appear on Windows.
      if (arg == 'disable')
        menu.items[0].submenu.items[1].enabled = false;
    });
}

module.exports.createMenu = createMenu;
```

Console log `menu message reviced` will be printed in renderer process if this run on macOS, but no response when it run on Windows. Why this situation happens? 

Thanks!

**Comment by zcbenz** [comment] 2016-10-19 01:16
That's because the renderer only after the `document` object has been created, while the `preload` script is loaded before the `document` object gets created, so there is a chance that the message sent from the main process gets received too early.

An immediate workaround is to send the message after DOM has loaded, and I'm closing this since it is expected behavior.

(We should probably have a more decent solution for the early messages though.)

**Closed by zcbenz** 2016-10-19 01:16 UTC

**Comment by changkun** [comment] 2016-10-21 07:10
Well, I didn't realized that. It indeed an strange behavior until now due to the message always received on macOS but not on Windows.

This issue gives an example that shows how to change menu status through process message communication, if menu created in main process, there is no way to change menu item status in runtime (except re-create it) I suppose?

**Comment by zcbenz** [comment] 2016-10-24 07:56
> @zcbenz This issue gives an example that shows how to change menu item status through process message communication. If menu created in main process, there is no way to change menu item status in runtime (except re-create it) I suppose?

Yeah currently you have to recreate menu to change items, we do plan to support dynamic menu and there is an issue tracking it.

**Comment by changkun** [comment] 2017-03-14 12:28
@zcbenz Is Electron 2.0 plan to introduce dynamic menu?
