### ISSUE TITLE
autoUpdater.quitAndInstall does not restart when I change the app product name

### ISSUE THREAD

**Issue by wangxiexe** [electron/electron#8418] opened 2017-01-17 02:39 UTC
* Electron version:

1.4.10

* Operating system:

Windows 10

### Expected behavior

autoUpdater.quitAndInstall is called and the new version of the app get started

### Actual behavior

old version get closed but the new version did not get launched.

### How to reproduce

change the product name in the package.json and create an updated version
update got downloaded, but autoUpdater.quitAndInstall only quite the old version.

**Comment by kevinsawicki** [comment] 2017-01-17 17:23
@paulcbetts does squirrel for windows handle a changing product name?

**Comment by zcbenz** [comment] 2017-06-06 01:02
I'm closing this as won't fix since it is a behavior by design, I suggest requesting https://github.com/Squirrel/Squirrel.Windows to add this ability.

**Closed by zcbenz** 2017-06-06 01:02 UTC
Labels: component/auto-updater, fixme/bug, platform/windows
