### ISSUE TITLE
EventListener "will-navigate" doesn't produce a function.

### ISSUE THREAD

**Issue by jakubkarbowski** [electron/electron#12096] opened 2018-03-01 14:40 UTC
* Electron version: 1.6.12 (electron-prebuilt-compile)
* Operating system: Windows 10

### Expected behavior

I am writing application in react. I want to create eventListener, which will send by ipcRenderer url of first webview, to another. Also some links should be blocked. I tried a lot of evens, but finally ended with `'will-navigate'` and `event.preventDefault()`.

### Actual behavior

Will-navigate doesn't work at all. It doesn't display even console logs. I checked other events. F.g `did-navigate` or `did-navigate-in-page` and from these events I received respones. 

### How to reproduce
```
ReactDOM.findDOMNode(this).addEventListener('did-navigate-in-page',(event) =>{ console.log("did-navigate-in-page")});

ReactDOM.findDOMNode(this).addEventListener('did-navigate',(event, url) =>{ console.log("did-navigate")});

ReactDOM.findDOMNode(this).addEventListener('will-navigate',(event, url) =>{ console.log("will-navigate")})
```

And responses are:
```
did-navigate-in-page 
did-navigate
```

**Comment by Acidic9** [comment] 2018-03-01 14:45
I believe this is a duplicate of #11885

**Comment by jakubkarbowski** [comment] 2018-03-01 15:00
I don't think so, because this problem refers only to <webview>

**Comment by sofianguy** [comment] 2018-05-10 19:06
Does this issue persist on a later version of Electron, such as 1.8 or 2.0.0?

**Comment by codebytere** [comment] 2018-05-18 15:43
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2018-05-18 15:43 UTC
Labels: blocked/need-info, bug :beetle:, platform/windows, version/1.6.x
