### ISSUE TITLE
[Bug]: BrowserWindow focus and Electron.Menu breaks after unmaximize window on Ubuntu

### ISSUE THREAD

**Issue by poisonReact** [electron/electron#35960] opened 2022-10-10 10:21 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.2 LTS

### What arch are you using?

x64

### Last Known Working Electron version

18.3.9

### Expected Behavior

After unmaximize BrowserWindow, the menu window opens and the BrowserWindow is not blurred when the cursor leaves the window.

### Actual Behavior

After unmaximize BrowserWindow, the menu window not opens and the BrowserWindow is blurred when the cursor leaves the window.

### Testcase Gist URL

https://gist.github.com/poisonReact/83fd391a3b4d2ba86fe51530f145e722

### Additional Information

[Screencast from 10.10.2022 12_47_54 (1).webm](https://user-images.githubusercontent.com/54484694/194845214-8827e7fc-d728-4ece-9c65-dc79d56a17bb.webm)

**Comment by veekxt** [comment] 2022-10-11 10:25
Seems related to https://github.com/electron/electron/issues/35724

**Comment by clavin** [comment] 2022-10-12 20:55
Closing as a duplicate of #35724. Thank you for the test case, video, and report!

**Closed by clavin** 2022-10-12 20:55 UTC
Labels: platform/linux, bug :beetle:, component/BrowserWindow, has-repro-gist, 21-x-y
