### ISSUE TITLE
[Bug]: Error installing extension 'extensions::SafeBuiltins'. v8_initializer.cc(96)

### ISSUE THREAD

**Issue by xland** [electron/electron#28487] opened 2021-04-02 00:50 UTC
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.1,12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

ia32

### Last Known Working Electron version

don't know

### Expected Behavior

run correctly

### Actual Behavior

When open window. this bug appread frequently

```
Exception thrown during bootstrapping
Error installing extension 'extensions::SafeBuiltins'.
[15296:0329/160109.446:FATAL:v8_initializer.cc(96)]
```

**Comment by VerteDinde** [comment] 2021-04-02 02:45
Hey @xland, thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by xland** [comment] 2021-04-02 05:25
Sorry , I can not
This issue appears not regularly.

**Comment by nornagon** [comment] 2021-04-02 18:26
Possibly related: https://bugs.chromium.org/p/chromium/issues/detail?id=923774

**Comment by jiangjianping** [comment] 2021-04-09 07:03
We encounter the same issue on electron 12.0-12.0.2.

**Comment by jiangjianping** [comment] 2021-04-13 12:01
@xland ,

I wonder the contextIsolation is true or false in your app? my app is false.

**Comment by xland** [comment] 2021-04-14 01:15
@jiangjianping 

Wo de ye shi `false`.

Ha Ha Ha

**Comment by jiangjianping** [comment] 2021-04-14 03:01
@xland,
  xie xie la !

**Comment by jiangjianping** [comment] 2021-04-14 03:05
@nornagon ,
This problem may be related to  contextIsolation setting with "false".  I test the all version between 11.1-12.0.2, windows 10 worked well and windows 7 (ia32) failed once in a while.

**Comment by jiangjianping** [comment] 2021-04-15 04:38
I montor the read-to-show event of browseWindow, I call the win.reload() when the read-to-show is not reached, the problem can be resolved.

**Comment by jiangjianping** [comment] 2021-04-15 08:33
@VerteDinde 
I catch the render-process-gone event, The reason is render process crashed.  disableHardwareAcceleration (no gpu) is better than gpu, but both ecounter the crash very easily under win7.

**Comment by jiangjianping** [comment] 2021-05-02 00:58
@nornagon 

has this problem been confirmed by you?

**Comment by Mrhoho** [comment] 2021-05-03 10:53
any update?👀

**Comment by bdelsaz** [comment] 2021-05-04 18:33
I'm also interested on this exact problem is happening to us as well.
Could you provide more information on what you did/which prop you set where to fix it? Our problem is that the logging will not even start up, so the chrome dev tools are of no use. What else can I use to debug?

**Comment by jiangjianping** [comment] 2021-05-08 04:37
@nornagon 
Any progress? What can we do for this problem?

**Comment by jiangjianping** [comment] 2021-05-13 11:53
@nornagon 
Hello there. I deep into the source code of v8 and found that this error is caused by stack-overflow during parsing extensions::SafeBuiltins, not always. Is there a method to increase the stack size under win7? 
v8/src/parsing/parser-base.h:
 void CheckStackOverflow() {
    // Any further calls to Next or peek will return the illegal token.
    if (GetCurrentStackPosition() < stack_limit_) set_stack_overflow();
  }

**Comment by andrewrutter** [comment] 2021-05-19 02:19
I am seeing the same issue here. We have a small application being packed for win32 and win64 machines. Stopping and then starting the application causes the same error to be logged randomly and fails to load.  I am able to reload from the menu which does load the web application. Have tried builds with contextIsolation set to both true and false without success.  

Not sure of any other settings that can be tried to resolve since this is occurring during bootstrap and therefore prior to the main application javascript loading. Is there a way to bind into the bootstrapping process and do an automated reload on failure?

Packaging is run using 
`npx electron-packager . gaa-ticket-sales --overwrite  --platform=win32 --arch=ia32 --prune=true --out=../dist`

package.json
`{
  "name": "kiosk-sales",
  "version": "1.0.0",
  "description": "Sales Application",
  "main": "electron_build.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron": "^12.0.5"
  }
}`

**Comment by fzcs** [comment] 2021-05-26 13:00
I can reproduce this issue. 

Use the code below.
[mediasdk_multiprocess_demo-fix-win7-crash.zip](https://github.com/electron/electron/files/6546786/mediasdk_multiprocess_demo-fix-win7-crash.zip)

The expected behavior is to open a new window 200 times.
Actual Behavior is randomly stop and got this error.

```
Exception thrown during bootstrapping
Error installing extension 'extensions::SafeBuiltins'.
[3892:0526/205906.218:FATAL:v8_initializer.cc(96)]

```

this can be reproduce since 11.2.1，11.2.0 is ok.

**Comment by StaZhu** [comment] 2021-06-06 11:53
I have tried remove "ldflags += ["/stack:0x80000"]" which introduced in 11.2.1 for x86 arch cpu, and rebuild the electron. then issue has been completed solved! just for reference, seems the stack size from 1.5MiB to 0.5MiB causes the issue.

**Comment by nornagon** [comment] 2021-06-16 00:26
Possibly related: https://github.com/electron/electron/pull/29474

**Comment by y489436672** [comment] 2021-06-21 12:11
I had the same problem. in 13.1.2

**Comment by nornagon** [comment] 2021-06-22 19:11
Duplicate of #29177

**Closed by nornagon** 2021-06-22 19:11 UTC
Labels: blocked/need-repro, bug :beetle:

**Comment by zengdongbao** [comment] 2021-10-21 03:42
fixed at: #https://github.com/electron/electron/pull/30244

**Comment by lnjpcl** [comment] 2022-01-20 09:34
> @nornagon， 这个问题可能与 contextIsolation 设置为“false”有关。我测试了 11.1-12.0.2 之间的所有版本，windows 10 运行良好，windows 7 (ia32) 偶尔失败。

你好，我想问下解决了吗，怎么解决的
