### ISSUE TITLE
Window level `screen-saver` doesn't work on macOS

### ISSUE THREAD

**Issue by matheuss** [electron/electron#7866] opened 2016-11-03 19:32 UTC
* Electron version: 1.4.5
* Operating system: OS X El Capitan – 10.11.6

### Expected behavior:

`window.setAlwaysOnTop(true, "screen-saver")` should allow the window to be placed above the menu bar, as per https://github.com/electron/electron/pull/7296#issuecomment-248982212.

This would be **very useful** for us at [wulkano/kap](https://github.com/wulkano/kap).

### Actual behavior

After calling such method with such parameters, I'm able to place the window above the Dock, but not above the menubar.

### How to reproduce

```
git clone https://github.com/matheuss/electron-issue-7866
cd electron-issue-7866
npm install && npm start
```

Click anywhere in the window and try to drag it above the menubar 😕

**Comment by kevinsawicki** [comment] 2016-11-03 20:15
@matheuss if you create the `BrowserWindow` with `enableLargerThanScreen: true` then it does appear initially above the menu bar, seems like dragging behavior is still kind of strange though, not sure if there are other mac window settings that should be used to support this.

**Comment by matheuss** [comment] 2016-11-03 21:07
That's strange, @kevinsawicki. With `enableLargerThanScreen: true` you can freely move the window above the menubar, but if you move it away, then you can't put it back 😕 

@adammeyer since you implemented this feature: any ideas?

**Comment by matheuss** [comment] 2016-11-03 21:32
Updated the example:
*  Added `enableLargerThanScreen : true`
* A double click on the window moves it to the very top of the screen (above the menu bar)

**Comment by zcbenz** [comment] 2016-11-16 08:12
`window.setAlwaysOnTop(true, "screen-saver")` sets the window level to `NSScreenSaverWindowLevel`, and it does that, so this is not a bug and I'm closing this issue.

For allowing the window to be placed above the menu bar, you have to find the solution yourself, and we will be very happy to add a new API or option for it.

**Closed by zcbenz** 2016-11-16 08:12 UTC
Labels: bug, macOS
