### ISSUE TITLE
can't resize electron window on elements with -webkit-app-region: drag;

### ISSUE THREAD

**Issue by Dan-Gamin** [electron/electron#22474] opened 2020-03-02 07:47 UTC
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.2
* **Operating System:**
  * Windows 10 Home Version 10.0.18362 Build 1836

### Expected Behavior

Just to window resize on elements with  `-webkit-app-region: drag;`

### Actual Behavior
The Window 

### To Reproduce
Make an element that somewhere next to the edge of the window with `-webkit-app-region: drag;`

### ScreenShots
Window:
![Window](https://user-images.githubusercontent.com/58695417/75655553-ca631000-5c6a-11ea-8529-4596b3a638b4.png)

### Additional Information
the header's css: 
```
    -webkit-app-region: drag;
    background: silver;
    width: 100vw;
    height: 40px;

    /* align the elements */
    display: grid;
    grid-template-columns: calc(100vw - calc(10px + 40px + 40px)) 10px 40px 40px;
    grid-template-rows: 1fr;
    grid-template-areas: 
        "Title Min . Close"
    ;
```

**Comment by jhuckaby** [comment] 2020-03-28 04:48
Can confirm, this is 100% reproducible on macOS 10.15.3 with Electron 8.1.1, even using the most vanilla of examples.  I believe `-webkit-app-region: drag;` is completely broken in this version.

**Comment by jhuckaby** [comment] 2020-03-28 04:53
@Dan-Gamin Can you possibly read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) and [Code of Condult](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) and check those two boxes in your bug description?  Then 3/3 will show on the bug list and will increase its visibility.  

Also, this may be a dupe of #21621.

**Comment by fabiospampinato** [comment] 2020-09-24 01:05
An ugly workaround for this is not making the `drag` portion of the titlebar full-height, but trimming a few pixel from it, that way at least the window will become draggable from everywhere.

The workaround is particularly ugly because if you have some content in those draggable elements you probably want that to be centered, but you don't want to chip pixels off the element from the bottom as that would make that region of the titlebar non-draggable.

**Comment by electron-triage** [comment] 2021-03-10 03:35
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Closed by electron-triage** 2021-03-10 03:35 UTC
Labels: 8-x-y, bug :beetle:, platform/windows
