### ISSUE TITLE
HTML5 title  attribute  do not work correct 

### ISSUE THREAD

**Issue by gaoktp** [electron/electron#9294] opened 2017-04-26 10:17 UTC
* Electron version:1.6.6 64 bit
* Operating system: windows 10 64bit

### Expected behavior

the title Attribute change along with mouse move 

### Actual behavior

the title Attribute do not correctly change, sometimes do not change at All 

### How to reproduce
on Chrome It looks like this gif 
![gif](https://cloud.githubusercontent.com/assets/17586114/25429518/d716ee28-2aab-11e7-8477-2af6539e39cb.gif)

In Electron  it looks like this gif, it will show the same title attribute with different divs
![gif2](https://cloud.githubusercontent.com/assets/17586114/25429727/7db8bb94-2aac-11e7-95a2-393ff0cca790.gif)

**Comment by gaoktp** [comment] 2017-05-05 06:35
No one has got the same problem???

**Comment by zcbenz** [comment] 2017-06-20 08:19
Can you provide a minimal app to reproduce this problem?

**Comment by codebytere** [comment] 2017-09-27 01:20
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:20 UTC
Labels: more-information-needed
