### ISSUE TITLE
[Bug]: Latest release label on GitHub repository is not correct

### ISSUE THREAD

**Issue by rhysd** [electron/electron#37864] opened 2023-04-06 13:18 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.0.0

### What operating system are you using?

macOS

### Operating System Version

11

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

N/A

### Expected Behavior

Currently the latest version is 24.0.0. So the latest release should point to the 24.0.0 release.

### Actual Behavior

21.4.4 is marked as the latest release in the repository page. 21.4.4 is a version for security backport though it was released after v24.0.0. https://github.com/electron/electron

Some users may accidentally use older version of Electron by visiting the link.

<img width="229" alt="image" src="https://user-images.githubusercontent.com/823277/230389354-5444165c-a4d1-446f-890d-6072c0931f1f.png">

**Comment by Prinzhorn** [comment] 2023-04-06 18:06
I think this is just the GitHub UI showing the _most recent_ release and nothing you can actually control? I might be wrong, it's just what I've always seen on GitHub.

**Comment by dsanders11** [comment] 2023-04-07 00:05
This was intended to be fixed by #37233, but looks like it didn't work for this release for some reason.

cc @MarshallOfSound

**Comment by MarshallOfSound** [comment] 2023-04-07 00:21
@dsanders11 It's because that PR was never backported to `21-x-y` to the 21 release used default behavior and claimed the latest tag 🤷 The next 24 release will fix this and then it won't be "wrong" again.

**Closed by MarshallOfSound** 2023-04-07 00:21 UTC
Labels: bug :beetle:

**Comment by MarshallOfSound** [comment] 2023-04-07 00:23
As an added bonus I just manually hit some API endpoints and forced 24.0.0 to be considered latest
