### ISSUE TITLE
Tray icon context menu strange behavior

### ISSUE THREAD

**Issue by doonay21** [electron/electron#9797] opened 2017-06-19 11:01 UTC
* Electron version: 1.7.3
* Operating system: Windows 10 Pro 64-bit

![wrong](https://user-images.githubusercontent.com/5584647/27281050-93071154-54ea-11e7-9d9d-8461157fef84.gif)

Right clicking on Tray Icon causes Windows native menu pop up covering menu from my app. It is important that Windows taskbar should not be focused, when it is focused everything work as expected.

### Expected behavior

Only context menu of my application should open.

### Actual behavior

Windows native context menu (the same menu when right clicking Windows taskbar) pops up covering menu from electron application.

### How to reproduce

1. `git clone https://github.com/doonay21/electron-quick-start.git`
2. `cd electron-quick-start`
3. `electron .`
4. Click anywhere but Windows taskbar
5. Right click on tray icon

**Comment by MarshallOfSound** [comment] 2017-06-19 11:05
@doonay21 I can reproduce this but only when right clicking on the transparent parts of the tray icon.  I think there is something wrong with the alpha channel in your PNG file as other apps don't experience this.  Where did you get the tray icon from / how did you generate it?  Trying to figure out what exactly is different from let's say my tray icon which doesn't exhibit this behavior.

**Comment by doonay21** [comment] 2017-06-19 11:40
@MarshallOfSound I tried two icons, one I made myself with GIMP, second was random file downloaded from google images. I also tried to create ICO file with alpha channel using GIMP - got the same result. Could you please provide me your ICO/PNG with alpha channel that works for you?

**Comment by MarshallOfSound** [comment] 2017-06-19 12:15
![main_tray_s](https://user-images.githubusercontent.com/6634592/27284610-caa89748-553c-11e7-8bd6-3e5ba29124a9.png)

This is the one I was testing on 👍

**Comment by doonay21** [comment] 2017-06-19 12:19
@MarshallOfSound thank you, but unfortunately the issue remains even with your PNG, here is the proof:

![wrong_2](https://user-images.githubusercontent.com/5584647/27284745-585d661a-54fa-11e7-87fe-a3d03d73dc75.gif)

**Comment by blukai** [comment] 2017-08-04 23:05
I have the same problem, tried different icons with different extensions - `png` and `ico`. 😕

**Comment by rebelvg** [comment] 2017-09-08 00:34
Are you running multi-monitor setup?
My friend discovered this bug with electron apps when running multi-monitor setup WITH task bar on both displays. If task-bar is disabled on the second monitor, this bug disappears.

**Comment by 1511pzz** [comment] 2017-12-27 04:38
I also encountered this problem,I solved it in a weird way,I do not know why
`    let appIcon = null
    var iconName = 'icon.ico'
    var iconPath = path.join(__dirname, iconName)
    appIcon = new Tray(iconPath)
    const contextMenu = Menu.buildFromTemplate([
        {
            label: 'show',
            click: function () {
                win.show()
            }
        }, {
            label: 'quit',
            click: function () {
                appIcon.destroy()
                app.quit()
            }
        }
    ])
    appIcon.setToolTip('This is my application.')
    // appIcon.setContextMenu(contextMenu)
    appIcon.on('double-click', function () {
        console.log('double click')
        win.show()
    })
    appIcon.on('right-click', function (event, bounds) {
        setTimeout(function () {
            appIcon.popUpContextMenu(contextMenu)
        }, 100)
    })`

**Comment by 1511pzz** [comment] 2017-12-27 06:40
I also encountered this problem,I solved it in a weird way,I do not know why
```
let appIcon = null
var iconName = 'icon.ico'
var iconPath = path.join(__dirname, iconName)
appIcon = new Tray(iconPath)
const contextMenu = Menu.buildFromTemplate([
    {
        label: 'show',
        click: function () {
            win.show()
        }
    }, {
        label: 'quit',
        click: function () {
            appIcon.destroy()
            app.quit()
        }
    }
])
appIcon.setToolTip('This is my application.')
// appIcon.setContextMenu(contextMenu)
appIcon.on('double-click', function () {
    console.log('double click')
    win.show()
})
appIcon.on('right-click', function (event, bounds) {
    setTimeout(function () {
        appIcon.popUpContextMenu(contextMenu)
    }, 100)
})
```

**Comment by codebytere** [comment] 2018-05-09 04:14
Does this occur on `2.0.0`?

**Comment by codebytere** [comment] 2018-05-18 15:42
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2018-05-18 15:42 UTC
Labels: blocked/need-info, bug :beetle:, component/tray, platform/windows, version/1.7.x

**Comment by vanowm** [comment] 2021-02-15 03:36
Still reproducible in v11.1.0
I don't believe it's related to icon structure, because I'm able reproduce it if I keep clicking in the same spot without moving cursor, but closing electron's menu with escape key;

![image](https://user-images.githubusercontent.com/511517/107902352-2bcfcd80-6f14-11eb-853e-da664e8bf832.png)

On this screenshot electron's menu is behind system's menu (huge), I'm able highlight it's items as visible on the screenshot and click them too, but system menu remains on screen until I click on taskbar, in fact it remained opened while I typed all this...

I do have multimonitor setup but with single native taskbar on right side of main monitor and DisplayFusion's taskbars on secondary monitors.
I'm unable reproduce this issue on DF taskbars.

```
Edition	Windows 10 Pro x64
Version	20H2
Installed on	‎2020-‎08-‎14
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0
```

**Comment by vanowm** [comment] 2021-02-19 03:02
I wonder if context menu gets opened on mouse down, instead of mouse up event has something to do with this issue?

**Comment by alexNecroJack** [comment] 2022-05-26 01:13
Still reproduceable in v. , Windows 8.1

* Windows Taskbar Context Menu (WTCM) is this 
![image](https://user-images.githubusercontent.com/16266778/170394245-b7273833-0648-4225-b2f1-390f9ff216f5.png)

I confirm that tray icon opens on right-click down, not right click up,
I confirm that right-clicking-down on tray icon opens Electron menu, and if yot drag your click towards WTCM then release  (right-click-up on taskbar), opens and the WTCM (2 menus, 1 right-click).

I confirm that the solution [1511pzz](https://github.com/1511pzz) provided seems to work,
the important part is this:
```Js
//tray.setContextMenu(contextMenu);
  tray.on("right-click", function (event, bounds) {
    setTimeout(function () {
      tray.popUpContextMenu(contextMenu);
    }, 100);
  });
  ```
And it seems to work even with lower delays, like 50ms.

Yes, it's a BUG.
Out of all the tray icons I have from other programs, with none I can right-drag-click the icon to the taskbar and open the windows taskbar context menu, they open no menu on right-click-down, they wait for right-click-up.
With none except Electron tray of cource.
The drag-right click though opens WTCM for windows Language tollbar and for Windows Calendar
![image](https://user-images.githubusercontent.com/16266778/170394179-4f4460ad-9c76-4ab1-9ec3-a0f27dda54e9.png)

**Comment by art-hck** [comment] 2023-05-19 09:06
Same in electron 24.3.0

**Comment by byte110** [comment] 2024-01-10 09:09
Same in electron 24.6.2
