### ISSUE TITLE
Electron application shows blank screen on Ubuntu

### ISSUE THREAD

**Issue by AmeerHamoodi** [electron/electron#27824] opened 2021-02-19 19:43 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v11.2.3
* **Operating System:** Ubuntu 20.04.2 LTS

### Expected Behavior
Electron window should display the html file being loaded.

### Actual Behavior
White screen and no electron logo are being displayed.

### To Reproduce
```sh
$ git clone https://github.com/AmeerHamoodi/electron_ubuntu_issue.git
$ npm install
$ npm install electron --save-dev
$ npm start
```

### Screenshots
![image](https://user-images.githubusercontent.com/38434341/108553107-3695b400-72c0-11eb-978a-b5a674105b28.png)
![image](https://user-images.githubusercontent.com/38434341/108553168-4d3c0b00-72c0-11eb-8f2e-024ce7f7842f.png)

### Additional Information
The code works fine on windows but is showing a blank screen on ubuntu. Also, I've only recently installed ubuntu as a dual boot on my computer, not sure if that has anything to do with the problem.

**Comment by nornagon** [comment] 2021-02-19 21:27
Does it work when you supply `--disable-gpu` on the command line?

**Comment by AmeerHamoodi** [comment] 2021-02-19 22:14
No it still just shows a blank screen

**Comment by ckerr** [comment] 2021-02-24 22:57
Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

It looks like this testcase has a few third-party dependencies that aren't supported by the electron team -- specifically, electron-log and electron-updater. Are these necessary to trigger the behavior, or does it still happen without them? For example would it be possible for you to make a standalone testcase using [Electron Fiddle](https://www.electronjs.org/fiddle) without third-party dependencies? If so, you can use Fiddle to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by ckerr** [comment] 2021-02-24 23:02
Just for completeness' sake -- FWIW I get a similar screen as @AmeerHamoodi does when running that git repo on Ubuntu 20.10 running native on a machine with no Electron + GPU issues. So it's unlikely to be specific to @AmeerHamoodi's machine, and unlikely to be a GPU issue.

That said, my previous comment is still valid. Addressing this in `electron/electron` makes much more sense if @AmeerHamoodi distills this down to an issue that can be reproduced using only `electron/electron` code.

**Comment by electron-triage** [comment] 2021-03-09 16:30
Thank you for your issue!

We haven't gotten a response to our questions in our [comment above](https://github.com/electron/electron/issues/27824#issuecomment-785439916). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2021-03-09 16:30 UTC
Labels: 11-x-y, blocked/need-repro, platform/linux
