### ISSUE TITLE
globalShortcut error when registered only meta key combination

### ISSUE THREAD

**Issue by ctxhou** [electron/electron#12990] opened 2018-05-18 05:05 UTC
* Electron Version: 2.0.1
* Operating System (Platform and Version): MacOS 10.13.1
* Last known working Electron version: 2.0.1

**Expected Behavior**
This error occurred when registered the shortcut in only meta key combination.
For example, <kbd>CommandOrControl</kbd>+<kbd>Shift</kbd> or only <kbd>CommandOrControl</kbd>

The code is
```js
globalShortcut.register('CommandOrControl+Shift', () => {
	// …
})
```

I expected it would work as other shortcut registration.

**Actual behavior**

It occurs this error message.

```
TypeError: Error processing argument at index 0, conversion failure from Shift+CommandOrControl
    at registerFontShortcut (/repo-path/main.js:161:20)
    at fonts.map.font (/repo-path/main.js:97:36)
    at Array.map (<anonymous>)
    at EventEmitter._electron.ipcMain.on (/repo-path/main.js:97:24)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at WebContents.<anonymous> (/repo-path/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
```

**To Reproduce**

Starting a electron app and using these accelerator combination can reproduce it.

**Additional Information**

I think maybe it is the limitation of the OS. It’s weird to register only the meta key as shortcut.
If it is not permitted by the OS, should add usage restrictions of this api?

**Comment by sindresorhus** [comment] 2018-07-18 08:44
This is a duplicate of #9900.

**Comment by codebytere** [comment] 2018-10-26 04:46
This is an OS limitation and also an upstream error; Chromium implements this check [here](https://cs.chromium.org/chromium/src/chrome/browser/extensions/global_shortcut_listener_mac.mm?q=RegisterAcceleratorImpl&sq=package:chromium&dr=C&l=84) which precludes two meta keys from being used as an accelerator.

**Closed by codebytere** 2018-10-26 04:46 UTC
Labels: 2-0-x, bug :beetle:, platform/macOS
