### ISSUE TITLE
[Bug]: Electron main process crash during any navigator.serial requests on MacOS in development mode

### ISSUE THREAD

**Issue by ottomen** [electron/electron#41220] opened 2024-02-02 14:26 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.0

### What operating system are you using?

macOS

### Operating System Version

MacOS: 13.2.1 (22D68)

### What arch are you using?

x64

### Expected Behavior

Electron process should not be crashed during the Serial port operations on MacOS in development mode running `electron .`

### Actual Behavior

Error: Failed to execute 'requestPort' on 'Serial': No port selected by the user. ::
[0202/091640.098527:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)
/Users/user/Work/web-ui/electron/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGABRT

### Additional Information

Processor: 2.6 GHz 6-Core Intel Core i7
RAM: 16 GB 2667 MHz DDR4
MacOS: 13.2.1 (22D68)

```
const BrowserWindowConstructorOptions = {
  autoHideMenuBar: true,
  show: false,
  width: 1280,
  height: 720,
  minWidth: 640,
  minHeight: 480,
  webPreferences: {
    contextIsolation: true,
    nodeIntegration: false,
    sandbox: true,
    webSecurity: true,
    allowRunningInsecureContent: false,
    experimentalFeatures: false,
    spellcheck: false,
    v8CacheOptions: 'bypassHeatCheck',
    preload: path.join(__dirname, 'preload.js'),
  },
}
```

And it works fine on Windows development and production builded modes.

**Comment by ottomen** [comment] 2024-02-06 16:50
Electron Fiddle doesn't show the issue, first of all because there is a `mainWindow.loadFile('index.html')` but we use `mainWindow.loadURL('http://localhost:3000');`. in the project. 
This is minor thing, but still, it Fiddle is a tool over the code, that is not the real environment, that can't be the reference for all issues.  

I've made a repo with a simplified version, similar to gist: https://github.com/ottomen/electron-serial-issue-demo that shows the problem. Can you check it, please? 

Thank you!

**Comment by ottomen** [comment] 2024-03-06 18:45
Any updates?

**Comment by codebytere** [comment] 2024-04-10 13:31
I ran the repro and could not reproduce the issue. it logs `Serial port open request` to console and does not crash.

**Comment by ottomen** [comment] 2024-05-02 14:47
Update. I've installed Sonoma 14.4.1 on Mac, and the issue is gone. I haven't updated the Electron version, so it seems it was a problem with a specific Mac OS 13.2.1

**Comment by codebytere** [comment] 2024-07-14 19:53
Closing as resolved given we could not reproduce it and it is no longer occurring.

**Closed by codebytere** 2024-07-14 19:53 UTC
Labels: blocked/need-info ❌, bug :beetle:, has-repro-repo, 28-x-y
