### ISSUE TITLE
windows 10 task bar recent items don't do anything when clicked

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#6039] opened 2016-06-14 07:05 UTC
- Electron version: 1.2.1
- Operating system: Windows 10

We are adding recent documents with `app.addRecentDocument()` which get added to the task bar icon of the application when you right click on it. However, clicking these items opens a terminal window for less than a second closes it and then nothing happens...so this task bar items don't work.

Maybe Electron doesn't have a way to handle this scenario? Or this is a bug?

**Comment by zcbenz** [comment] 2016-06-14 11:01
When clicking the items Windows will use your app to open them, and the filename will be passed by command line parameters. So it is probably your app didn't handle opening files well, or somehow Windows executes a wrong app.

You can also reference [how Atom does it](https://github.com/atom/atom/blob/21a5ef6d741c3dedec5c71447c5662e1026a77b8/src/main-process/main.coffee#L16):
<img width="262" alt="screen shot 2016-06-14 at 7 58 29 pm 1" src="https://cloud.githubusercontent.com/assets/639601/16040462/900bdf46-326a-11e6-8572-4a708d533152.png">

**Comment by astoilkov** [comment] 2016-06-15 05:27
I can't seem to find a way to add an item to the Recents in Atom to test it. I have made a video of the behavior in our app and my failed attempt to add file to Atom recents.

http://screencast.com/t/DdlP9xaZeDBO

Hope this helps understand the problem better.

**Comment by astoilkov** [comment] 2016-06-15 08:07
I forgot to say that our app already handles command line parameters and opens the file when such argument have been passed. You could download the app and test it under Windows to see that it opens files when file is dragged, double clicked, called with Open with Caret using the context menu - http://caret.io/

**Comment by zcbenz** [comment] 2016-06-16 04:11
From the screencast there is an `Update.exe` started, which I guess it is the squirrel updater shipped within your app. Under the hood of the `addRecentDocument` API, it simply passes the path to Windows, it seems that Windows picked wrong process for opening the app.

**Comment by astoilkov** [comment] 2016-06-16 06:07
How is this possible when we set `electron.app.setAppUserModelId();` and call `electron.app.setName()`? We collect the paths Windows passes and open this paths but in this case the application doesn't even open so we could chance to open it. If Windows passed the path and we didn't handle it the app would have been opened but not the file.

Do you think this could be some kind of bug in Electron's `addRecentDocument()` API?

**Comment by zcbenz** [comment] 2016-06-16 06:58
The API is a [simple wrapper of win32 call](https://github.com/electron/electron/blob/master/atom/browser/browser_win.cc#L53-L66), I don't have any idea why Windows picked wrong executable for your app.

**Comment by astoilkov** [comment] 2016-06-16 07:08
Does Atom support the same functionality? I wasn't able to add recent files in the Atom context menu? If we can replicate it there maybe we could determine if there is some global problem or if it's a problem of our app code.

**Comment by astoilkov** [comment] 2016-06-16 07:09
I am not sure what could be done in this scenario. Do you have any other ideas how we could find the cause of the problem?

**Comment by zcbenz** [comment] 2016-06-16 07:14
Atom supports recent documents, if you open a file with it the file will be added to the recent list. It at least works on my machine.

I don't know how to solve this for your app, but I might try deleting `Update.exe` and changing AppUserModelID.

**Comment by astoilkov** [comment] 2016-06-16 07:28
Are you on Windows 10? Have you seen the video I posted - I am trying to add a recent document there but without success. What are the steps for adding a recent document in Atom?

**Comment by astoilkov** [comment] 2016-06-29 07:59
Hi,

I have created a simple app that replicates the issue. Steps to reproduce:

  1. Open the app
  2. Hit "s" character on the keyboard
  3. The dialog will appear
  4. Wait for 2-3 minutes
  5. The unresponsive event is called and and a message box will appear

[electron-dialog-unresponsive.zip](https://github.com/electron/electron/files/338789/electron-dialog-unresponsive.zip)

**Comment by zcbenz** [comment] 2016-07-01 07:59
I can reproduce on Windows 10.

**Comment by damieng** [comment] 2016-11-23 04:19
Atom doesn't display the recent documents on Windows because of a regression in Atom 1.4.3 where a workaround to avoid crashing spotlight with URL's inadvertently also disabled it for Windows (url.parse considers Windows paths to have a protocol that is the drive letter)

Should be fixed up there shortly.  There is no issue with Electron itself as far as I can tell.

**Comment by astoilkov** [comment] 2016-11-23 06:25
The problem wasn't that Atom didn't display recent documents. The problem was that when a recent document was clicked the Atom app didn't open it. I gave this example so the problem could replicated. The same issue happens in our app too.

Please consider reopening this bug.

**Comment by damieng** [comment] 2016-11-23 06:28
Not sure how you were getting Atom to display a recent document then given it was broken.

Atom and Electron are definitely working fine with Recent files in this PR I just created https://github.com/atom/atom/pull/13307

**Comment by astoilkov** [comment] 2016-11-23 06:34
I am not sure how but me and @zcbenz were reproducing it under Windows 10. I am reproducing the problem in our app too.

I will test this in our app today and let you know. If it is needed I will create a demo reproducing the problem.

**Comment by astoilkov** [comment] 2016-11-23 07:52
Ok. I tried our app under Windows 10 and the behaviour has changed but it still doesn't work.

When a recent document is clicked a popup always appears saying that the document doesn't exist anymore. Could try downloading the app and see if you replicate the issue https://caret.io/.

The only code that we execute is the one below:

```
if (app.addRecentDocument) {
  app.addRecentDocument(file);
}
```

We are currently using Electron 1.4.6

**Comment by damieng** [comment] 2016-11-23 16:40
I would recommend checking out the app.setJumpList api as it looks like addRecentDocument might be going away.

What is the exact path specified by file?  One thing to check is that it is using forward-slashes, e.g. c:\docs\myfile.txt as it is passed to Windows which exclusively likes these paths.  Many node tools like mangling them to c:/docs/myfile.txt for example which although node is happy with Windows won't be.

**Comment by enlight** [comment] 2016-11-24 01:39
@damieng `app.setJumpList` hasn't superseded `app.addRecentDocument` if that's what you're thinking, the two are complimentary.

**Comment by damieng** [comment] 2016-11-24 01:48
Sorry, yes was confusing with `app.setUserTasks()`

**Comment by astoilkov** [comment] 2018-01-21 09:00
A year and a half later our users are still complaining that the recent documents don't work. Is there any update on this? A rough estimation of when this could be worked on would be of great value in order for us to know if we should use `setJumpList()` API or wait for this to get fixed.

Thanks in advance.

**Comment by damieng** [comment] 2018-02-13 16:46
I just re-tested this with Atom again and it's working fine there.

I clear the jump list entirely. Launch Atom, open a file and the file is added to the recent documents icon pinned on the task bar.  I then click on it and it opens Atom with the correct file.

There are some tools for inspecting the contents of Automatic Destinations - I just used [JumpLister](http://www.woanware.co.uk/forensics/jumplister.html) which seems to have some problems parsing the file in newer version of Windows 10 but it confirms the contents for the most recent item opened by Atom;

![image](https://user-images.githubusercontent.com/118951/36162095-5c00ae92-109a-11e8-86e1-c4615fc9ea7e.png)

**Comment by astoilkov** [comment] 2018-02-14 14:45
@damieng - with what version of Atom are you testing?

**Comment by damieng** [comment] 2018-02-14 15:03
I'm using the version of Atom on master (so Electron 1.7.11)

**Comment by astoilkov** [comment] 2018-02-14 15:16
It seems really hard for me to take the time to build Atom from source. When will the version of master be available as a beta release?

In the meantime, you could try our app [here](caret.io) if you want to experience the problem.

**Comment by damieng** [comment] 2018-02-14 16:03
Atom Beta uses the same Electron and works - releases available at https://github.com/atom/atom/releases

I did try Caret and can confirm I got an error loading jumplist entries. I had a quick peek in the jumplist files and couldn't see anything obviously wrong but it's not the clearest file format in the world.  What version of Electron are you using?

**Comment by astoilkov** [comment] 2018-02-16 14:53
Very strange. I tried the latest Atom Beta but couldn't get it to display recent files. Additionally, my icon is yellow, not blue.

We are using Electron `1.7.11`.

**Comment by damieng** [comment] 2018-02-16 16:23
Beta's always have a yellow icon - that is normal.

If it's not displaying any at all that could be due to previously having
selected a 'remove' on an item in Windows and then Atom adding it back.
Windows decides you are not honoring removals and stops displaying Recents
entirely.

**Comment by codebytere** [comment] 2018-05-09 03:25
Given the conversation above, it appears that the actionable issues in this have been addressed. In that event, i'm going to go ahead and close this, but please feel free to @ me if something else arises!

**Closed by codebytere** 2018-05-09 03:25 UTC
Labels: bug :beetle:, platform/windows
