### ISSUE TITLE
Node fs doesn't work on renderer process when reloading

### ISSUE THREAD

**Issue by mnmallea** [electron/electron#24727] opened 2020-07-25 20:32 UTC
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  9.1.1
* **Operating System:**
  Windows 10 (2004)
* **Last Known Working Electron version:**
  Unknown

### Expected Behavior
After reloading (or force reloading), placeholder should be filled with the `tini.csv` file content. See `renderer.js` and `index.html`.

### Actual Behavior
`fs.promises.readFile` call hangs infinitely (never resolves or rejects).

### To Reproduce
If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/mnmallea/electron-fs-issues.git -b master
$ cd electron-quick-start
$ npm install
$ npm start
```

### Screenshots
![electron-issue](https://user-images.githubusercontent.com/28768483/88465711-4c163d00-ce9b-11ea-845f-ddbcfe82d919.gif)

### Additional Information
I have tried this on Ubuntu and MacOS too and it works fine there.
I have originally ran into this issue on an electron-forge application, using their webpack and ts template. I left an example on `electron-forge-ts-template` folder on the same repo. There, file system `readFile` call doesn't work at all (it hangs infinitely the first time too).

**Comment by pushkin-** [comment] 2020-07-27 22:50
This is a dupe of [this](https://github.com/electron/electron/issues/22119), right?

**Comment by mnmallea** [comment] 2020-07-28 01:00
It seems it is.
I´ve also experimenting #19554 on the webpack-typescript version.

**Comment by codebytere** [comment] 2020-09-28 00:38
Same underlying issues as https://github.com/electron/electron/issues/22119

**Closed by codebytere** 2020-09-28 00:38 UTC
Labels: 9-x-y, bug :beetle:, platform/windows
