### ISSUE TITLE
[Electron 3.0.0-beta.8] browser windows flicker and cause explorer to crash when loading resources at the same time

### ISSUE THREAD

**Issue by t57ser** [electron/electron#14432] opened 2018-09-03 07:58 UTC
* Output of `node_modules/.bin/electron --version`: 3.0.0-beta.8
* Operating System (Platform and Version): Windows 7 and Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.8

**Expected Behavior**
browser windows work correctly

**Actual behavior**
The browser windows start to flicker and the explorer.exe might not work correctly anymore (things do not respond anymore, like the taskbar)

**To Reproduce**
clone https://github.com/t57ser/electron-webview-focus-issue (repo from another issue but works for this showcase as well)
add "3.0.0-beta.8" as electron version in package.json
replace the init function in main.js with this code:
```
browserWindow = new BrowserWindow({
	width: 800,
	height: 600,
	x: 200,
	y: 200
});
browserWindow.loadFile("index.html");
browserWindow.on("closed", () => {
	browserWindow = null
});
browserWindow2 = new BrowserWindow({
	width: 800,
	height: 600,
	x: 100,
	y: 100
});
browserWindow2.loadFile("index.html");
browserWindow2.on("closed", () => {
	browserWindow2 = null
});
```

**Additional Information**
If you remove one of the loadFile functions it will start to work, so it appears to only cause problems if browser windows load files at the same time. Also note that setting a timeout (around one of the loadFile functions) does not necessarily help, what I experienced:
timeout of 0 (bug occurs)
timeout of 1 (bug occurs)
timeout of 10 (it works)
but this might be random depending on the machine this is tested on

**Comment by bpasero** [comment] 2018-09-03 14:54
Duplicate of https://github.com/electron/electron/issues/13549

**Comment by MarshallOfSound** [comment] 2018-09-03 22:08
Closing as per @bpasero above

**Closed by MarshallOfSound** 2018-09-03 22:08 UTC
