### ISSUE TITLE
[Bug]: setWindowOpenHandler changes default stylesheet for plain text files in dark theme

### ISSUE THREAD

**Issue by ajafff** [electron/electron#37737] opened 2023-03-28 10:17 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version
&gt;=22.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 22H2

### What arch are you using?

x64

### Last Known Working Electron version

21

### Expected Behavior

Click on the link to open the plain text file in a new window.
Text should be readable, e.g. white text on dark background.

### Actual Behavior

Text is not readable. It's white text on white background.
This seems to only happen if there is a `setWindowOpenHandler`. If you comment out that line, a dark background is applied.

### Testcase Gist URL

https://gist.github.com/ajafff/8d9e8eb8cc0a7ec2297f2445c54f5526

**Comment by jeremyspiegel** [comment] 2023-03-28 18:18
Is this the same as https://github.com/electron/electron/issues/36538?

**Comment by ckerr** [comment] 2023-03-28 18:28
@jeremyspiegel probably not?

I agree they do look similar, but if 36538 was present in 21.3.1 and 37737 first appeared in v22.0.0-nightly.20220810 then they can't be the same issue :dizzy:

**Comment by jeremyspiegel** [comment] 2023-03-28 18:45
@ckerr sorry you're right. Using `onclick="window.open('/popup.txt')"` to open the window had the issue in v21, but using `<a href="/popup.txt" target="_blank">` doesn't.

**Comment by jeremyspiegel** [comment] 2023-03-28 19:03
I would guess that the underlying issue behind both is something about the change to use the `transparent` web preference to set the background color, introduced in https://github.com/electron/electron/pull/28054. Looks like that preference was only being set for the `window.open` case at that point, but then with https://github.com/electron/electron/pull/34526 it was then set for the `<a target="_blank">` case as well.

**Comment by ajafff** [comment] 2023-03-28 19:14
I agree that they look like duplicates. Feel free to close this one.
I would also like to see the `window.open()` case fixed, as that's what I'm actually using in my app. I just reduced it to `<a target="_blank">` for this reproduction

**Comment by dsanders11** [comment] 2023-03-30 06:22
@ckerr, it's the same issue as #36538. I have the fix for these issues in #36914 but CI was giving me trouble with the tests, so I shelved it and then got sidetracked with other work. I've confirmed the fix in that PR fixes the gist provided in this issue. I'll pick it back up and see if I can make the tests happy.

**Comment by nornagon** [comment] 2023-03-30 17:11
Duplicate of #36538.

**Closed by nornagon** 2023-03-30 17:11 UTC
Labels: bug :beetle:, platform/all, status/confirmed, has-repro-gist, 22-x-y, duplicate
