### ISSUE TITLE
Electron Helper crashes after signing for MAS

### ISSUE THREAD

**Issue by MrPanos** [electron/electron#7637] opened 2016-10-15 12:32 UTC
* Electron version:1.4.3
* Operating system:OSX

After signing an app for the mac app store the app crashes.  I've been able to trace the issue to /Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper .   Before signing this works fine and my app runs normally.   However after signing it just hangs.  

When running Electron Helper  manually from the command line after signing I get the error _Illegal instruction: 4_ 

This error also occurs on 1.4.2

**Comment by MarshallOfSound** [comment] 2016-10-15 12:36
Possible a duplicate of #7559 ?

**Comment by MrPanos** [comment] 2016-10-15 13:06
Similar, but my build script does not include entitlementsInherit which resolved the issue in #7559 

    "build": "electron-packager . MyApp --platform=mas --arch=x64 --version=1.4.3 --icon=../source/MyApp.icns --overwrite"

I'm signing using a script as per https://github.com/electron/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md  

...
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/Contents/MacOS/$APP Helper"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/"
...

 My child.plist is the same as in the doc with the follow

...
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.inherit</key>
    <true/>
...

but even without any keys in child.plist the error occurs.

**Comment by MrPanos** [comment] 2016-10-15 15:55
After stepping away for a bit I've started from scratch, redownloading the apple certs and going through all the steps in the doc mentioned above, as well as replaced my code with a simple "Hello World".   I no longer get the Illegal Operation: 4 error now when running Electron Helper. 

However, I am still having a problem with the app crashing at the same place when loading and I've been able to trace it to : 

window.loadURL(url);  

If I remove that line the app does not crash, but obvious is useless because I can't load anything.  

If I remove the  com.apple.security.app-sandbox  key from parent.plist when signing the app it does not crash, but obviously I cannot submit to the app store.   

I am now under the impression this is an entitlement / documentation issue.  It seems that Electron or Electron Helper needs a specific entitlement in the parent.plist that is not included in the documentation.

Any insight would be appreciated.

**Comment by paulcbetts** [comment] 2016-10-15 17:26
This is almost always because your application-groups / ElectronTeamID setting isn't correct

**Comment by MrPanos** [comment] 2016-10-15 23:04
It doesn't seem this is the case  (lucky me)

/Contents/Info.plist

...
    <key>ElectronTeamID</key>
  	<string>T4******</string>
  </dict>
</plist>

parent.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.application-groups</key>
    <string>T4******.com.blah.MyApp</string>
  </dict>
</plist>

**Comment by paulcbetts** [comment] 2016-10-16 01:30
Check what actually ends up in your app, an app from the App Store, "RB App Checker Lite" is super useful for seeing what is actually ending up in your signed app

**Comment by MrPanos** [comment] 2016-10-16 09:19
You might be right.  RB App Checker shows T4*******.com.electron.MyApp

**Comment by MrPanos** [comment] 2016-10-16 09:34
If I sign using electron-osx-sign I get 

`Evaluating the application “MyApp.app”.

The application was signed by “Apple Root CA”, “3rd Party Mac Developer Application: Blah (T4*******)”.
	The (unverified) signing-time is: Oct 16, 2016, 12:23:12 PM.
	The object code format is “app bundle with Mach-O thin (x86_64)”.
	The signature contains the Team ID “T4**********”.
	Both bundle and signing identifiers are “com.electron.MyApp”.
	The signature specifies implicit requirements. ￼
	The signature specifies resource rules (v1). ￼
	The signature specifies resource rules (v2). ￼
	Requirements and resources validate correctly.

The code signature has the UUID “DA1AE5A2-****-****-7B79-***********”.
	Executable code for x86_64 has the UUID “E140337E-****-****-80E2-**********”.

A signing-time snapshot of the application’s Info.plist was found. ￼
	Version 1.0.0 (1.0.0) 

The signature contains 3 certificates. ￼
	Certificate “Apple Root CA”: ￼
		Your keychain contains this trusted root certificate.
		Will expire on Feb 9, 2035.
	Certificate “Apple Worldwide Developer Relations Certification Authority”: ￼
		Will expire on Feb 7, 2023.
	Certificate “3rd Party Mac Developer Application: Blah (T4*******)”: ￼
		Will expire on Oct 15, 2017.
		SHA1 fingerprint: “4CEF1*********”.
		Team ID or Organizational Unit: “T4*******”.
			This matches the Team ID contained in the signature.

The application is sandboxed.

The code signature contains entitlements. ￼

There is one embedded framework. ￼

7 auxiliary executables have been found. ￼
	One file is invisible in the Finder. ￼ ￼
	One executable is unsigned. ￼ ￼
	6 executables are signed by  “Apple Root CA”, “3rd Party Mac Developer Application:  Blah (T4*******)”. ￼
	One executable is in the Resources folder. ￼
	One executable file has no executable permissions, but should.`


If I sign using the shell script method I get

`The application was signed by “Apple Root CA”, “3rd Party Mac Developer Application: Blah (T4*******)”.
	The (unverified) signing-time is: Oct 16, 2016, 12:25:48 PM.
	The object code format is “app bundle with Mach-O thin (x86_64)”.
	The signature contains the Team ID “T4********”.
	Both bundle and signing identifiers are “com.electron.MyApp”.
	The signature specifies implicit requirements. ￼
	The signature specifies resource rules (v1). ￼
	The signature specifies resource rules (v2). ￼
	Requirements and resources validate correctly.

The code signature has the UUID “********-******-D007-BB08-*****”.
	Executable code for x86_64 has the UUID “******-******-3E1B-80E2-***********”.

A signing-time snapshot of the application’s Info.plist was found. ￼
	Version 1.0.0 (1.0.0) 

The signature contains 3 certificates. ￼
	Certificate “Apple Root CA”: ￼
		Your keychain contains this trusted root certificate.
		Will expire on Feb 9, 2035.
	Certificate “Apple Worldwide Developer Relations Certification Authority”: ￼
		Will expire on Feb 7, 2023.
	Certificate “3rd Party Mac Developer Application: Blah (T4******)”: ￼
		Will expire on Oct 15, 2017.
		SHA1 fingerprint: “4********”.
		Team ID or Organizational Unit: “T4**********”.
			This matches the Team ID contained in the signature.

The application is sandboxed.

The code signature contains entitlements. ￼
	Sandbox entitlements:
		Application groups: “T4*********.com.electron.MyApp”.

There is one embedded framework. ￼

7 auxiliary executables have been found. ￼
	One file is invisible in the Finder. ￼ ￼
	One executable is unsigned. ￼ ￼
	6 executables are signed by  “Apple Root CA”, “3rd Party Mac Developer Application: Blah (T4********)”. ￼
	One executable is in the Resources folder. ￼
	One executable file has no executable permissions, but should.`

**Comment by MrPanos** [comment] 2016-10-16 11:32
I've traced my steps back and found that the docs I based my build script did not include --app-bundle-id and --helper-bundle-id .  I've added these and now the signing seems correct, with one exception 


```
The code signature contains entitlements. ￼
	Sandbox entitlements:
		Application groups: “T4*****.com.electron.MyApp”.
```


And it's still crashing.

**Comment by MrPanos** [comment] 2016-10-16 11:50
Running 
`
electron-osx-sign "./MyApp.app"`

Produces 
```

The application is sandboxed.

The code signature contains entitlements. ￼

There is one embedded framework.
```


Running

`electron-osx-sign "./MyApp.app"  --verbose --entitlements="parent.plist" --entitlements-inherit="child.plist"`

or the shell script defined in the doc ( https://github.com/electron/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md )

Produces

The application is sandboxed.
```

The code signature contains entitlements. ￼
	Sandbox entitlements:
		Application groups: “T4*****.com.electron.connections”.

There is one embedded framework. 
```

All ways create the same error.

**Comment by MrPanos** [comment] 2016-10-16 12:47
Added 

<key>com.apple.security.network.client</key>
    <true/>

to parent.plist and all is good.

**Comment by zcbenz** [comment] 2016-10-24 03:00
Closing since it is actually a usage problem and has already been resolved.

**Closed by zcbenz** 2016-10-24 03:00 UTC
Labels: more-information-needed
