### ISSUE TITLE
The "Zoom In" shortcut doesn't work

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#15496] opened 2018-10-31 10:51 UTC
* Output of `node_modules/.bin/electron --version`: **3.0.6**, **4.0.0-beta.4**
* Operating System (Platform and Version): **Mac** at least
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): **2.0.11**

**Expected Behavior**
Behaviour in Electron 2:
1) "View > Zoom In" menu item shows "⌘+" as a shortcut.
2) Pressing "⌘+" increases a page's zoom.

**Actual behavior**
1) For Electron 3 the app "View" menu shows "⌘+" as a shortcut for the "Zoom In" item.
For Electron 4 it shows "⇧⌘+".
2) The "⌘ and +" shortcut  doesn't work but "Shift and ⌘ and +" does the job in both Electron 3 and 4.

The other zoom shortcuts "⌘ and -" and "⌘ and 0" work as expected.

**To Reproduce**
Open any webpage in Electron, e.g. `$ ...Electron.app/Contents/MacOS/Electron https://youtube.com`, try to Zoom in and Zoom out with a keyboard.
Can be reproduced even with the default app.

**Comment by alexstrat** [comment] 2018-11-14 13:46
I allow myself to reopen this issue as #15502 only fixes the display and not the shortcut itself.

Related: #14742

**Comment by javan** [comment] 2018-12-31 20:03
For now, I'm working around this issue with:
```diff
     { role: 'resetzoom' },
-    { role: 'zoomin' },
+    { role: 'zoomin', accelerator: 'CommandOrControl+=' },
     { role: 'zoomout' },
```
It restores the keyboard shortcut, which is used more frequently than the actual menu (for us, at least). The downside is it displays as **⌘=** instead of **⌘+**.

**Comment by aaronraimist** [comment] 2019-02-02 21:36
I was trying to use that solution but I want it to display ⌘+. I tried duplicating the menu item and marking it as `visible: false` however that doesn't work. Once the menu item is invisible it seems to be disabled even if I specifically enable it.

```
{ role: 'zoomin' },
{ 
    role: 'zoomin', 
    accelerator: 'CommandOrControl+=',
    visible: false,
    enabled: true,
},
```

**Comment by mx2323** [comment] 2020-01-08 23:09
just hit this - does anyone have a real fix or know why this doesnt work? im reverting back to 2.0.11  for now.

**Comment by electron-triage** [comment] 2020-02-19 21:40
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by dsteinman** [comment] 2020-02-23 00:22
This problem still appears to be unresolved as of v7.1.12.

**Comment by shahan312** [comment] 2020-02-23 18:12
Reproducible on v8.0.0 too. We are using the `{ role: 'zoomin', accelerator: 'CommandOrControl+=' }` workaround.

**Comment by danutzcodrescu** [comment] 2020-03-25 15:42
I would like to add my 2 cents on this. I thought as well that this is a bug, but I would not say so. It works with `Command + Shift + +`, which is exactly what the shortcut says. You cannot obtain `+` without pressing `Shift`.  Maybe the default accelerator should be `Command + =` instead, which would not require pressing `Shift`.

**Comment by codebytere** [comment] 2020-03-25 15:55
Due to the way that Apple's keyboard shortcuts work here, there are two options moving forward:

1. Display the menu item with `⌘=`
2. Correct the current item to reflect that it needs to be triggered with `⇪⌘+`

What would you all prefer?

**Comment by danutzcodrescu** [comment] 2020-03-25 15:58
I would say option 1. It would be more intuitive to press.

**Comment by KiranNiranjan** [comment] 2020-03-25 16:02
@codebytere I think it would be better to support both ⌘+ & ⌘= in MacOS and display ⌘+ in the menu... This will also support both US and variants keyboard

**Comment by clavin** [comment] 2021-02-19 21:10
This was actually fixed as a byproduct of #27701! <kbd>Cmd</kbd> and <kbd>+</kbd> (no shift key) triggers the same code path it used to trigger before Electron v3, zooming in the window as you would expect. This also works as expected on other keyboard layouts, e.g. French.

@codebytere Now that <kbd>Cmd</kbd> and <kbd>+</kbd> (no shift key) works without touching shortcuts, what to do with the <kbd>Cmd</kbd> and <kbd>Shift</kbd> and <kbd>=</kbd> shortcut lying around somewhere?

**Comment by electron-triage** [comment] 2021-03-08 18:35
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-08 18:35 UTC
Labels: 3-0-x, 4-2-x, 7-1-x, 8-x-y, bug :beetle:, bug/regression :leftwards_arrow_with_hook:, platform/macOS

**Comment by nikhilmishra11** [comment] 2021-04-07 14:04
Getting zoom in issue,
Zoom in ctrl+ then pressing the next button and loading the new page. After the new page loaded, ctrl- is not working. 
For making it work, I have to first press ctrl+ then zoom out is working again on ctrl-.

**Comment by tr3ysmith** [comment] 2021-06-26 19:43
This is still a problem.
Electron 13.1.3

have to use Ctrl Shift + to get it to work....

**Comment by Paxxous** [comment] 2022-02-24 22:46
It hasn't been working for me either. Can't seem to find a fix. Not even manually zooming in through the top menu seems to work. And every time I reboot my app the zoom saves.

**Comment by J-N-R** [comment] 2023-04-18 02:11
Any update on this? I'm getting this error too.

**Comment by bradisbell** [comment] 2023-05-08 05:19
Still an issue, in Electron 24.2.0 on Windows.

**Comment by bradisbell** [comment] 2023-06-07 08:10
Still an issue, in Electron 25.1.0 on Windows.

**Comment by julian-alarcon** [comment] 2023-09-19 10:49
As mentioned here by @cbesangeeth
This works for me 👇 (Linux, Ubuntu)

Zoom In : Ctrl Shift +
Zoom Out : Ctrl -

**Comment by Johnrobmiller** [comment] 2024-07-23 01:27
This is still an issue on windows. If I close the app and reopen it, it's still zoomed out.

This is a horrible bug, and it's been broken for literally years it looks like. Is Electron being maintaned?

**Comment by shakeelahmad686** [comment] 2024-07-26 19:38
Can work around this issue like this

This will allow shortcut keys to work with both 
Ctrl+Shift+Plus
Ctrl++



**Update your main.js with these line of code**
```
app.on('ready', () => {
  // TO UPDATE WITH YOUR SETTINGS
  mainWindow = new BrowserWindow({...})
  globalShortcut.register('Control+=', () => {
    mainWindow.webContents.setZoomLevel(mainWindow.webContents.getZoomLevel() + 1)
  })
})
```
