### ISSUE TITLE
dialog.showOpenDialog's callback stops being called for no reason

### ISSUE THREAD

**Issue by oxcarga** [electron/electron#6207] opened 2016-06-23 19:08 UTC
* Electron version: ^1.1.1
* Operating system: El Capitan 10.11.5

Here the gist:
https://gist.github.com/oxcarga/289dadcd829458b50823c6b57bf8e218/edit

In renderer process we have a simple button calling `remote.dialog.showOpenDialog()`
with a callback fn which just prints in console the filenames for the selected images.

At some point callback fn ( callback for dialog.showOpenDialog() ) stops being called. Lets say we repeat this process some times:

(with console opened)
1. click btn (dialog opens)
  - "clicked!" is console-logged 
2. select 1,5 or N number of images from X folder
3. hit open
  - array length & array itself are console-logged
4. repeat #1

Do this for several times, then stop for a while, then try again.
Not sure how or why but this reproduces the issue for me. At some point we just get the "clicked!" console log and we stops receiving callback's console logs.

P.D.: gist above is ready to run
`npm install && npm start`

**Comment by zcbenz** [comment] 2016-06-23 23:36
This is a duplicate of #6050.

**Closed by zcbenz** 2016-06-23 23:36 UTC
