### ISSUE TITLE
Synchronous Font Loading

### ISSUE THREAD

**Issue by Antix-Development** [electron/electron#21320] opened 2019-11-28 08:54 UTC
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I am creating an application which uses fonts, and loading fonts has become problematic.

I cannot seem to find any way to load a font synchronously... JavaScript/HTML/CSS/whatever only appears to be able to load them asynchronously.

The result is that when my application opens saved projects, fonts are not loaded by the time the application is wanting to access them.

### Proposed Solution
It would be a great boon to myself and others if there was a way to load fonts synchronously in Electron.

### Alternatives Considered
My current method to hide this issue is...
1. Open a div that fills the entire window that stops users clicking anything, and eat all key-presses.
2. Call setTimeout() to wait for half a second and after the timeout has elapsed re-enables key-presses, hides the cover div, and runs the code that uses the fonts.

Whilst this works, it is kind of messy and I feel it would be beneficial if Electron had some method to load fonts synchronously.

Maybe this is already possible with JavaScript but after extensive searching I could not find any solution.

### Additional Information
I love how Electron allows me to basically turn a web application into a desktop application, complete with local file access. For me personally this seems like some holy grail of web application development. Thanks and respect to all maintainers for their mammoth efforts :)

**Comment by loc** [comment] 2019-12-03 22:26
This is largely the problem of FOUT / FOIT (Flash of Unstyled / Invisible Text) and exists outside of the purview of Electron. The problem isn't that the font fetches are not asynchronous but that they're just late; they're coming in after the document has been rendered. A common strategy to deal with this: pre-fetching and caching. Once the font is fetched the first time, subsequent requests should be served from the disk cache.

If you're only dealing with a subset of fonts you could bundle the fonts with your app and serve them locally.

Closing as it's unlikely we'll address your issue in any way outside of the browser's capabilities.

**Closed by loc** 2019-12-03 22:26 UTC

**Comment by Antix-Development** [comment] 2019-12-03 22:38
Thanks for explaining and yes... there's no solution besides waiting for a short number of milliseconds and hope nothing breaks LOL
