### ISSUE TITLE
close button of quick look window is not working 

### ISSUE THREAD

**Issue by zoubin** [electron/electron#8749] opened 2017-02-23 07:18 UTC
* Electron version: 1.6.1, 1.4.0
* Operating system: macOS 10.12.3

I click a file upload button (input element with type 'file'), and try to quick look a numbers file by clicking the 'Quick Look' item from the context menu, but the close button on the upper left of the quick look window is not clickable. I click it, and nothing happens. Have to press `ESC`.

### Expected behavior

Click the close button on the upper left and the quick look window will disappear

### Actual behavior

Click the close button on the upper left and nothing happens.
You have to press `ESC` to close the quick look window.

### How to reproduce

https://github.com/zoubin/repro-electron-quick-look-window-unclosable

**Comment by enlight** [comment] 2017-02-23 07:33
Duplicate of #8457

**Closed by enlight** 2017-02-23 07:33 UTC
