### ISSUE TITLE
[Bug]: setContentProtection(true) does nothing on macOS

### ISSUE THREAD

**Issue by MetaiR** [electron/electron#31787] opened 2021-11-11 00:30 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.1, 16.0.0-beta.8, 9.0.0

### What operating system are you using?

macOS

### Operating System Version

MacOS 11.6.1

### What arch are you using?

x64

### Last Known Working Electron version

-

### Expected Behavior

since document mention `setContentProtection(true)` supports MacOS, I expect it to prevent the window from being captured and took screenshot from.

### Actual Behavior

u can easy capture screen by the built-in app in macOS
just search `screenshot` in ur spotlight searcher and take video.
the property has no effect

### Additional Information

I already read about something similar on #19880 but that issue was about specific app (chrome browser) but mine is macOS built-in screenshot app (and probably all other desktop recording applications). 
beside that that issue was for old version of electron and being closed and no one responding to it.
I tried after two years of that issue and it is not fixed after 2 years.
all the solutions and flag settings in that issue were also useless.

please, this is important, if u know any alternative solution to handle such thing in electron tell me.

**Comment by ckerr** [comment] 2021-11-11 15:36
I believe this is a duplicate of https://github.com/electron/electron/issues/14415. 

From what I can tell, what @miniak said in that ticket is still the current state of things. I've confirmed that the codepath does call `[NSWindow setSharingType:NSWindowSharingNone]` on macOS as documented; unfortunately, that does not prevent some applications capturing the window. If there is a better way of preventing sharing on macOS a pointer (or better yet, a PR :slightly_smiling_face:) would be hugely appreciated!

**Closed by ckerr** 2021-11-11 15:36 UTC
Labels: bug :beetle:

**Comment by SergiiMarkin** [comment] 2021-12-15 16:35
Hi @ckerr 
I am running the same issues.
If there is any update, hope you will let me know.
Thanks.

**Comment by OferSisso1** [comment] 2022-03-22 10:11
`setContentProtection` works on macOS with Electron 11.x.x when calling
`app.commandLine.appendSwitch('disable-features', 'IOSurfaceCapturer')` before the `app` is initialized.
but unfortunately it doesn't work for Electron 17.x.x (and probably on older versions too).

**Comment by MetaiR** [comment] 2022-03-23 23:47
Hello @SergiiMarkin @OferSisso1 
after this issue, I end up checking the running processes and close my application if there is any running capturing process available. sure due to the variety of the capturing application this might not be the best and most practical option but combining this solution and getting a list of applications from the server at my application startup; was the best I could do to prevent my clients to record the application,

hope this helps u too

**Comment by salmanSOFTECH** [comment] 2022-03-28 06:47
how did you get the running processes?

**Comment by MetaiR** [comment] 2022-04-09 01:38
@salmanSOFTECH using this package `find-process`
