### ISSUE TITLE
Tray icon can't be destroyed on GNOME

### ISSUE THREAD

**Issue by mitchchn** [electron/electron#24976] opened 2020-08-13 22:12 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.0
* **Operating System:**
  * Fedora 32
* **Last Known Working Electron version:**
  * 9.0.2

### Expected Behavior

Calling `tray.destroy()` on a `Tray` instance should remove the icon from the notification area.

### Actual Behavior

The icon remains in the notification area.

### To Reproduce

This code will result in two tray icons side by side instead of one:

```
const tray = new Tray();
tray.destroy();
const tray2 = new Tray();
```

### Additional Information

I believe the issue was (re-?)introduced in https://github.com/electron/electron/pull/23674.

**Comment by ckerr** [comment] 2020-08-15 23:36
Interesting. I'm not able to reproduce this using the snippet above in Ubuntu 19.10 + Electron 9.2.0.

@mitchchn, I realize the example above is trivial, but just to make sure we're testing the same thing -- would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case (e.g. in a fork or, better yet, a gist that can be run in electron-fiddle -- and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2020-09-01 03:30
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2020-09-01 03:30 UTC
Labels: blocked/need-repro, bug/regression :leftwards_arrow_with_hook:, platform/linux
