### ISSUE TITLE
Detect and change the preference of the tray icon in notification area

### ISSUE THREAD

**Issue by wearhere** [electron/electron#3970] opened 2015-12-31 20:06 UTC
On Windows, it seems that `Tray` items are not visible by default but must be shown by the user.

<img width="307" alt="screen shot 2015-12-30 at 1 52 00 pm" src="https://cloud.githubusercontent.com/assets/110000/12067866/2c4ae57c-afc7-11e5-9cf3-bd0617c5ce20.png">

But our item looks terrible in the customization tray—its icon is designed for the dark background of the tray bar:

<img width="116" alt="screen shot 2015-12-31 at 1 25 21 pm" src="https://cloud.githubusercontent.com/assets/110000/12067869/4c89b34a-afc7-11e5-99d1-abed5fb8db50.png">

Is there a way to have different icons depending on whether the item is in the bar or in the customization tray?

It also seems that @paulcbetts added a way to promote the item from the customization tray to the bar in https://github.com/Squirrel/Squirrel.Windows/pull/447, that'd be even better, but I don't know how to call that from Electron. It doesn't appear that any of the `Squirrel.Windows` executables expose an option to do that.

**Comment by wearhere** [comment] 2016-01-05 06:28
For anyone facing this issue, I factored @paulcbetts' logic out into an NPM package: https://www.npmjs.com/package/electron-promote-windows-tray-items Now you can work around the issue like so:

```js
var promoteWindowsTrayItems = require('electron-promote-windows-tray-items');

// Create a tray item.
var icon = new Tray(/* ... */);

if (process.platform === 'win32') {
  // Icon will now be in the toolbar customization area without the user explicitly toggling it to show in the toolbar.

  promoteWindowsTrayItems(function(err) {
    // Icon will now be in the toolbar itself unless the user explicitly hid it from the toolbar.
  });
}
```

Not having to explicitly show the icon is a nicer UX anyway I think!

**Comment by mattetti** [comment] 2017-05-22 23:58
To summarize, the problem is that squirrel uses a wrapper binary pointing to a versioned binary. When the icon is dragged, windows links to the versioned binary instead of the wrapper (AKA trampoline binary). When an update is available, a new binary is changed and the link is deal. Squirrel for windows exposes a C# API to link the proper executable when an icon is dragged into the tray, but because the option isn't available via command line. Electron communicates with squirrel only using the command line and that's why the behavior is broken on all electron/squirrel apps out there (starting with Slack).

**Comment by DeerMichel** [comment] 2019-06-27 05:07
Closing this issue since there has not been any recent activity or plans made to implement such feature.

**Closed by DeerMichel** 2019-06-27 05:07 UTC
Labels: component/tray, enhancement :sparkles:, platform/windows
