### ISSUE TITLE
Electron crashed after set BrowserView

### ISSUE THREAD

**Issue by ChugunovRoman** [electron/electron#13581] opened 2018-07-08 08:15 UTC
* Electron Version: 2.0.4
* Operating System (Platform and Version): Debian 9.4 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)
* Last known working Electron version: N/A

**Expected Behavior**
When I set the instance of the BrowserView to the BrowserWindow, and than I destroy the current  the BrowserView, and after these actions I set another the instance of the BrowserView to the BrowserWindow. Ok. Everything should be fine.

But...

**Actual behavior**
When I try to set another the instance of tne BrowserView to the BrowserWindow after removing the current BrowserView from the BrowserWindow, than Electron app close without any errors.
Is it normal behavior?

```
// mainWindow already have a view
const currentView = this.mainWindow.getBrowserView();
currentView.destroy();

const view = new BrowserView({
            webPreferences: {
                nodeIntegration: false
            }
        });

        tab.setBounds({
            x: 0,
            y: 19,
            width: 300,
            height: 200
        });
        tab.webContents.loadURL(`https://google.com`);

this.mainWindow.setBrowserView(view); // Here Electron is closeing without errors
```

But, if set the other instance of the BrowserView before removing the current view,  that Electron does not closed.

**Comment by lpjohnson** [comment] 2018-11-02 15:34
Seeing this as well on the latest version (3.0.7). Reproducing the issue is as simple as:

1. Create a new `BrowserView` and attach it to the main window using `setBrowserView`
2. At any point, call `.destroy() `on said BrowserView
3. Try then to create a another new `BrowserView` and use `setBrowserView` again on the main window - the app will crash immediately.

**Comment by lpjohnson** [comment] 2018-11-21 17:10
Update: This actually appears to be a non-issue. I didn't realize that calling `.setBrowserView` with a value of `null` on the main window was required before calling `.destroy()`. In other words, if you do this when the `BrowserView` is no longer needed:

```
mainWindow.setBrowserView(null)
browserView.destroy()
browserView = null
```
Then you can subsequently create a new `BrowserView` without the app crashing. Just figured this would be helpful for others who have experienced this (and maybe it's worth updating the documentation to reflect this?)

**Comment by ChugunovRoman** [comment] 2018-11-21 17:31
Maybe show a error message when this happens?
If don't call
```
mainWindow.setBrowserView(null)
```

**Comment by vladimiry** [comment] 2018-12-28 10:38
The issue is also reproducible with Electron v4. But this workaround does the trick:
> I didn't realize that calling .setBrowserView with a value of null on the main window was required before calling .destroy()

So I think this is what needs to be done:
- Updating documentation regarding a need to call `mainWindow.setBrowserView(null)` before destroying the BrowserView.
- Updating TypeScript declaration file as `setBrowserView` method currently doesn't accept the `null` argument but only `BrowserView`.

**Comment by krausekai** [comment] 2019-08-03 12:13
Issue continues to occur in 5.x and 6.x, where ``win.removeBrowserView(browserView)`` needs to be called prior to ``.destroy()``. Including this in the documentation would be helpful.

**Comment by sofianguy** [comment] 2019-08-09 00:20
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 20:53
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 20:53 UTC
Labels: 2-0-x, blocked/need-info ❌, bug/crash :boom:, platform/linux

**Comment by DreamFox** [comment] 2020-05-08 09:18
in Electron 8.x，if you use a frameless window, also will reproduction it.
so, in anycase, if you want destory a browserView and set it again,
you should call `win.removeBrowserView(browserView) ` before 
 `win.setBrowserView(browserView)`
