### ISSUE TITLE
Transparent apps have bleed issues.

### ISSUE THREAD

**Issue by iamdriz** [electron/electron#2532] opened 2015-08-20 09:49 UTC
If you have two Electron applications that are both frameless and have transparency turned on then sometimes when interacting with the top most application the application behind bleeds through:

![image](https://cloud.githubusercontent.com/assets/801252/9380578/0afebc9c-4729-11e5-9d98-79f8d9f7fce1.png)

If you look at the screenshot you can see that the top most application where it has the general, games + apps, prizes, etc menu items has a squared block of opaque content and then around it the application below is bleeding through. It should all just be the light green color, but it seems that Electron gets upset and causes things behind to start bleeding.

This is on Windows 7.

**Comment by iamdriz** [comment] 2015-08-20 10:07
Here's another screenshot of it even worse!

![image](https://cloud.githubusercontent.com/assets/801252/9380969/afead95a-472b-11e5-8752-35ac9c497b8b.png)

**Comment by iamdriz** [comment] 2015-08-20 10:09
It's actually not because I have another application underneath (as I though before) as even the desktop can shine through when this is the only application running:

![image](https://cloud.githubusercontent.com/assets/801252/9381009/e8549a9c-472b-11e5-9b38-6d1d97db06df.png)

**Comment by iamdriz** [comment] 2015-08-20 10:25
Disabling Windows 7 Aero fixes this issue (but we lose the transparency effect on the app) so it seems that the transparency in Electron has some performance issues with Aero in Windows 7.

**Comment by iamdriz** [comment] 2015-08-20 10:36
Also noticed that this ONLY happens on a compiled application. When running it in test mode with `electron-prebuilt` it works fine, but once compiled, then it has the performance issues.

**Comment by Ivshti** [comment] 2015-08-22 08:29
Are you by any chance using Webkit transitions/translations on your entire UI or do you have a transform() enabled? It could create some issues with Chromium + transparency.

There are certain ways to work around it.

Also, which version of electron are your unning?

**Comment by iamdriz** [comment] 2015-08-22 09:53
Yeah using all of the above. And running the latest versions of Electron.

What could be the reason for it working with electron prebuilt but not the compiled versions I wonder?

**Comment by Ivshti** [comment] 2015-08-22 10:09
I've seen this exact problem in nwjs, I think, but I could be mistaken, with the software fallback for transparency.

Open about://gpu on chromium, electron-prebuilt and your electron build - compare if there are significant differences.

A possible reason might be your build starting without gpu acceleration, for example because of not loading some dll - like d3d shader compiler.

**Comment by iamdriz** [comment] 2015-08-23 10:56
How do i do the about gpu for electron apps?

**Comment by etiktin** [comment] 2015-08-27 16:38
@iamdriz, the url in Electron for the gpu is `chrome://gpu`. You can change the url through devtools:
```javascript
location.href = "chrome://gpu";
```

**Comment by iamdriz** [comment] 2015-08-28 09:27
@etiktin Tried that but I just get an invisible window with no content...

**Comment by etiktin** [comment] 2015-08-29 16:55
That's odd. It works for me:
![chromegpu](https://cloud.githubusercontent.com/assets/4381579/9563279/ff46f8b4-4e86-11e5-9db6-743310394f0f.png)
I tested it with Electron v0.31.0 on Windows 8.1.

Can you try it again, but this time check the "Preserve log" checkbox in the console view? If it fails to navigate to the page, it might log the error.

**Comment by iamdriz** [comment] 2015-08-29 18:46
I'm off work for a couple days but I'll try again when back.... But noticed that you are using Windows 8/10.. Could that have any affect do you think?

**Comment by etiktin** [comment] 2015-08-29 19:13
I'm not familiar with the relevant code, so I'm not sure what the issue is. Hopefully the log will tell us more.

Once you get back, you might want to try running your code with the latest version (v0.31.1). The executable manifest was updated with compatibility information, so it might influence rendering (I doubt it will solve the issue, but it's worth a try).

**Comment by iamdriz** [comment] 2015-09-01 09:03
Okies managed to get it working this time. As you can see Raterization is software only... So the big question is how to make sure that it uses the GPU. Thanks.

![image](https://cloud.githubusercontent.com/assets/801252/9600045/8b7b6daa-5090-11e5-8df7-c8e1bea0b713.png)

**Comment by iamdriz** [comment] 2015-09-01 09:16
Also noticed that my grunt-electron task was hard-coded to use 0.25.3 of Electron. Which might explain why the test version worked and the built version to break. I'll comment back with findings.

**Comment by Ivshti** [comment] 2015-09-01 09:22
@iamdriz gpu_rasterization is often disabled..and it doesn't caused issues - everything else is hardware accelerated  so I think your'e fine. The issue is weird, I have no idea now

**Comment by iamdriz** [comment] 2015-09-01 09:23
Also noticed that when doing the GPU output and scrolling it makes all the text blurred:

![image](https://cloud.githubusercontent.com/assets/801252/9600546/89bd2d7a-5093-11e5-9ac2-4ef818c34a58.png)

**Comment by iamdriz** [comment] 2015-09-01 10:05
Okies, I've had a chat with our ICT support and we believe we may have a fault with my computer as I have tested this build on another computer and not been able to reproduce the problem. So looks like it isn't a bug with Electron but rather an OS/Driver fault on my local machine.

I'll close this unless it comes back as otherwise. But thanks for the all the help.

**Comment by iamdriz** [comment] 2015-09-07 13:10
It looks like this is a Windows 7 bug as it works on Windows 8 + but I have confirmed it's an issue on multiple Windows 7 machines.

**Comment by paulcbetts** [comment] 2015-09-07 18:16
@iamdriz Do these machines have the latest version of Internet Explorer installed? IE pulls down some DirectWrite patches that basically make DWrite not completely broken like it was when it was shipped

**Comment by iamdriz** [comment] 2015-09-08 08:42
@paulcbetts We should be running the latest version:
![image](https://cloud.githubusercontent.com/assets/801252/9730347/d79b03da-560d-11e5-9587-2cc7b99641f7.png)

**Comment by Ivshti** [comment] 2015-09-08 08:46
So, does this latest version of IE break transparency?
- In what conditions?
- Is there a workaround?

**Comment by felixrieseberg** [comment] 2015-11-18 11:10
I think you misunderstood @paulcbetts - if Windows 7 is on the latest version, everything should be fine. I could not reproduce the issue here at Microsoft (that being said, I used RDP to test, so it'd be interesting to hear the exact parameters for this issue).

**Comment by zcbenz** [comment] 2016-05-06 10:54
I'm closing this since this issue is deeply related to hardware and the version of Windows, so we are not able to fix this on Electron's side. For people troubled with this issue, the only suggestion I can give is to wait for upgrades of Chrome.

**Closed by zcbenz** 2016-05-06 10:54 UTC
Labels: blocked, bug, transparent-window, windows
