### ISSUE TITLE
Impossible to open electron apps from within Atom and others

### ISSUE THREAD

**Issue by RomanADavis** [electron/electron#8449] opened 2017-01-19 20:11 UTC
* Electron version: Latest version of Atom, GitKraken, etc.
* Operating system: Tested on the big 3 with Atom, unevenly replicated with GitKraken
Crossposted from here: https://github.com/atom/atom/issues/13624
### Expected behavior

Using a terminal embedded in Atom on Windows 10, it should be possible to type atom $profile and open up your powershell profile.

Nothing. Although on other OSes you'll get an error. See the crosspost on the Atom repo and it's link to other complaints.

https://github.com/atom/atom/issues/13624

**Comment by kevinsawicki** [comment] 2017-01-23 18:29
I'm not sure this is an Electron issue, https://github.com/atom/atom/issues/13624#issuecomment-273936723

Are you able to reproduce this using just Electron?

**Comment by MarshallOfSound** [comment] 2017-01-23 20:58
I believe this is due to the Electron applications spawning process with ELECTRON_RUN_AS_NODE and then this environment variable being inherited when opening an Electron application

**Comment by kevinsawicki** [comment] 2017-01-24 22:17
> I believe this is due to the Electron applications spawning process with ELECTRON_RUN_AS_NODE and then this environment variable being inherited when opening an Electron application

Closing this out, apps like Atom can unset this environment variable from spawned processes if those spawned process are spawning processes in non-Node mode.

**Closed by kevinsawicki** 2017-01-24 22:17 UTC
Labels: more-information-needed
