### ISSUE TITLE
[Bug]: PDF Viewer is broken for the 100th time

### ISSUE THREAD

**Issue by megakraken** [electron/electron#29757] opened 2021-06-17 18:05 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Version 10.0.19043.1055 

### What arch are you using?

x64

### Last Known Working Electron version

11.0.0

### Expected Behavior

Opening a PDF file in a BrowserWindow should **display** the PDF file using Chromium's built-in PDF Viewer.

### Actual Behavior

Opening a PDF file in a BrowserWindow just shows a broken and seemingly half-loaded PDF Viewer with no PDF content in it whatsoever.

### Additional Information

This project needs some serious regression testing for crying out loud. How is it possible that things that were already working fine keep breaking all the time and none of the developers care or even notice?

**Comment by nornagon** [comment] 2021-06-17 18:11
Duplicate of #29326

**Closed by nornagon** 2021-06-17 18:11 UTC
Labels: bug :beetle:

**Comment by VerteDinde** [comment] 2021-06-17 21:38
Hey @megakraken, I understand your frustration, but this bug is actively being worked on - please follow the issue linked above for progress 🙂

**Comment by VerteDinde** [comment] 2021-06-22 17:40
@megakraken This issue is now fixed in Electron 13.1.4! Let me know if you have more issues.
