### ISSUE TITLE
Updating Text Results In A Mess When In Frameless Mode

### ISSUE THREAD

**Issue by gaojiyong** [electron/electron#5221] opened 2016-04-20 04:23 UTC
#* Electron version: v0.3.75 
* Operating system:win7 x64

example:

![image](https://cloud.githubusercontent.com/assets/11253729/14663322/51d51b32-06f2-11e6-888f-c92c6b639e60.png)

then i change the html in the span  through javascript

![image](https://cloud.githubusercontent.com/assets/11253729/14663343/92d6d468-06f2-11e6-8c0f-5498e1e48610.png)

when the frame equal true,it's normal,but the frame equal false,then

0,1,2  they are show...

![image](https://cloud.githubusercontent.com/assets/11253729/14663354/b4a56794-06f2-11e6-84c5-9e1efd90cebb.png)

there is another example about form file upload

before select the file :

![image](https://cloud.githubusercontent.com/assets/11253729/14663334/7938d830-06f2-11e6-9a7f-d5239d9a3cd1.png)

after select the file:

![image](https://cloud.githubusercontent.com/assets/11253729/14663337/7d5ca2e8-06f2-11e6-8613-03b26efb323c.png)

so,i think it is a bug,and this cause that i can't choose electron to ,plase development

**Comment by xuanhun** [comment] 2016-04-20 04:28
ding！

**Comment by zcbenz** [comment] 2016-04-20 11:17
Can you provide a minimal app that can reproduce this problem?

**Comment by gaojiyong** [comment] 2016-04-28 05:34
i changed the backgroud-color ,then it works normal

**Comment by zcbenz** [comment] 2016-04-28 08:14
Thanks for letting me the solution, from the description this should be a duplicate of #5120 and had been fixed in 0.37.6.

**Closed by zcbenz** 2016-04-28 08:14 UTC
Labels: more-information-needed
