### ISSUE TITLE
Some menu accelerators don't work in Windows

### ISSUE THREAD

**Issue by kasrak** [electron/electron#7165] opened 2016-09-09 22:36 UTC
* Electron version: 1.3.5
* Operating system: Windows 10 

It seems like certain menu accelerators don't work when the app is running in Windows, but they do work in macOS. In the example below, none of the accelerators work in Windows, but clicking the menu item does log the correct message. But `CmdOrCtrl+B` *does* work in Windows. 

Here's the code:

```
const electron = require('electron');
const app = electron.app;
const Menu = electron.Menu;
const BrowserWindow = electron.BrowserWindow;
app.on('ready', function() {
    let mainWindow = new BrowserWindow({width: 800, height: 600});
    mainWindow.loadURL(`file://${__dirname}/index.html`);

    let menu = Menu.buildFromTemplate([
        {
            label: 'Edit',
            submenu: [
                {
                    label: 'Cut',
                    accelerator: 'CmdOrCtrl+X',
                    click: () => console.log('cut'),
                },
                {
                    label: 'Copy',
                    accelerator: 'CmdOrCtrl+C',
                    click: () => console.log('copy'),
                },
                {
                    label: 'Paste',
                    accelerator: 'CmdOrCtrl+V',
                    click: () => console.log('paste'),
                },
                {
                    label: 'Select All',
                    accelerator: 'CmdOrCtrl+A',
                    click: () => console.log('select all'),
                },
            ],
        },
    ]);
    Menu.setApplicationMenu(menu);
});
app.on('window-all-closed', function() {
    app.quit();
});
```

**Comment by fhemery** [comment] 2016-09-11 09:20
I have same issue on my side. Seems on my side accelerators are not working at all. Tried with both electron and electron prebuilt, 1.3.5, on Windows 7.

Code below
```
const electron = require('electron')

const app = electron.app
const BrowserWindow = electron.BrowserWindow
const Menu = electron.Menu

app.on('ready', _ => {
  new BrowserWindow()

  const template = [
    {
      label : 'Accelerators ?',
      submenu : [{
        label: `Ctrl`,
        accelerator: 'CmdOrCtrl+A',
        click: _ => console.log('Ctrl')
      }, {
        label: `Alt`,
        accelerator: 'Alt+A',
        click: _ => console.log('Alt')
      },{
        label: `Shift`,
        accelerator: 'Shift+A',
        click: _ => console.log('Shift')
      },{
        label: `Key only`,
        accelerator: 'A',
        click: _ => console.log('Key only')
      }]

    }
  ]
  const menu = Menu.buildFromTemplate(template)
  Menu.setApplicationMenu(menu);

})
```

Hope it helps,
Regards,
Frederic

**Comment by kevinsawicki** [comment] 2016-09-12 20:45
I believe this is a duplicate of https://github.com/electron/electron/issues/7040, some keybindings cannot be overridden on Windows/Linux because they are hard-coded in Chrome.

@fhemery I think your issue might be different than the original one reported, it looks like from your example that your window has not loaded a URL which I think is causing the issue, your example works for me if calling `loadURL` on the window.

**Closed by kevinsawicki** 2016-09-12 20:45 UTC

**Comment by fhemery** [comment] 2016-09-12 21:25
@kevinsawicki Indeed, confirmed working with loadURL, all key combinations are responding except Ctrl+A. My bad, thus.

**Comment by Bug-Reaper** [comment] 2019-06-03 07:43
> I believe this is a duplicate of #7040, some keybindings cannot be overridden on Windows/Linux because they are hard-coded in Chrome.
> 
> @fhemery I think your issue might be different than the original one reported, it looks like from your example that your window has not loaded a URL which I think is causing the issue, your example works for me if calling `loadURL` on the window.

Is this documented anywhere in the electron docs. That's super useful to know.
