### ISSUE TITLE
Electron 8.x 32bit failed to run on 64bit Windows 10

### ISSUE THREAD

**Issue by abnerlee** [electron/electron#23680] opened 2020-05-20 13:59 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5 / 8.3.0
* **Operating System:**
  * Windows 10 1909 64bit
* **Last Known Working Electron version:**
  * 6.x.y

### Actual Behavior
- If I double click electron.exe in node_modules or in downloaded package, no window show up, the exe will crash immediately.
- If I run "electron ." in cmd, it will show following error, and also crashed:
```
[12192:0520/214855.899:FATAL:tsf_text_store.cc(33)] Failed to initialize CategoryMgr.
npm ERR! code ELIFECYCLE
npm ERR! errno 2147483651
```

### Additional Information
The 64bit version is working fine

**Comment by codebytere** [comment] 2020-06-09 16:38
Duplicate of https://github.com/electron/electron/issues/23841

**Closed by codebytere** 2020-06-09 16:38 UTC

**Comment by johannesjo** [comment] 2020-06-09 16:41
@codebytere what makes you think that this is a duplicate?? The versions don't add up and the same is true for the error...
