### ISSUE TITLE
Dialog box with `cancelId` but no "Cancel" button can't be dismissed with esc key

### ISSUE THREAD

**Issue by jwheare** [electron/electron#8573] opened 2017-02-02 22:37 UTC
* Electron version: 1.4.15
* Operating system: macOS 10.12.3

### Expected behavior

Pressing esc on a dialog box with a cancelId should emulate clicking the button with that index.

### Actual behavior

An alert tone from the OS is produced, as with any unrecognised key press.

### How to reproduce

```javascript
require('electron').dialog.showMessageBox({
  buttons: ['OK', 'Button text'],
  cancelId: 1
});
```

The esc to cancel does work if you change the cancel button text to `Cancel`.

**Comment by groundwater** [comment] 2017-02-02 23:14
I can reproduce the issue, but I'm not sure if it's a bug. We will review this a little further and decide if we want to support this behavior or not.

**Comment by kevinsawicki** [comment] 2017-02-22 17:45
I believe this is a limitation of the macOS API being used.

Electron uses a [NSAlert](https://developer.apple.com/reference/appkit/nsalert?language=objc) and the docs state:

> Any button with a title of “Cancel” has a key equivalent of Escape, and any button with the title “Don’t Save” has a key equivalent of Command-D (but only if it is not the first button)

https://developer.apple.com/reference/appkit/nsalert/1532992-buttons?language=objc

So I'm going to close this out since this is the expected behavior for a message box on macOS.

Using a modal `BrowserWindow` could be an option you can pursue to have complete control over the styling and behavior of this.

**Comment by jwheare** [comment] 2017-02-22 17:53
Does NSAlert really prevent you from overriding the Escape key behaviour? I'm curious how Chrome manages to make Esc work to dismiss the "Do you want to leave the site" dialog then when the cancel button is labeled "Stay"

![screen shot 2017-02-22 at 17 52 01](https://cloud.githubusercontent.com/assets/49224/23224836/bbf670d8-f927-11e6-9826-7f4b10836e87.png)

**Comment by jwheare** [comment] 2017-02-22 17:57
Isn't that exactly what `keyEquivalent` is for? As mentioned in the next sentence in the docs you linked:

> You can also assign different key equivalents for the buttons using the keyEquivalent method of the NSButton class.

**Comment by kevinsawicki** [comment] 2017-02-22 18:00
> Isn't that exactly what keyEquivalent is for?

Yup, you are right, thanks for digging into this further 👍

**Closed** 2017-02-24 17:32 UTC
Labels: component/dialog, platform/macOS, triage/enhancement
