### ISSUE TITLE
White dots leaking over time Windows 10

### ISSUE THREAD

**Issue by woutervmertens** [electron/electron#24424] opened 2020-07-04 16:39 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  unknown
* **Operating System:**
  *  Windows 10 (2004)
* **Last Known Working Electron version:**
  *  unknown

### Expected Behavior
 
Rendering does not change.

### Actual Behavior
 
Dots bleed out over time from various elements until state is changed (mouseover/highlight/...)

### To Reproduce

Open electron app and wait. Reliably happens on Slack, VSCode, GitHub Desktop

### Screenshots

![Code_2020-07-04_18-06-20](https://user-images.githubusercontent.com/23281537/86516975-6a04fa80-be25-11ea-8266-1e5255537dcc.png)

**Comment by ahallicks** [comment] 2020-07-06 07:58
This might need a bit more information as I have the same version of Windows 10 and have never seen this (despite having apps open all day that I don't interact with). What GPU do you have? I think this might be more tied to external graphical factors.

**Comment by woutervmertens** [comment] 2020-07-06 09:29
I have a NVIDIA GeForce GTX 1070 driver version 451.48 although this problem has been present since the previous windows 10 update and previous driver versions.

The problem can be screenshot, so it doesn't seem to be a hardware issue
![2020-03-27_14-53-26](https://user-images.githubusercontent.com/23281537/86578251-ce39d280-bf7b-11ea-8d00-2c616f1c2723.gif)

**Comment by ahallicks** [comment] 2020-07-07 15:27
Sounds like this is similar, if not the same, as https://github.com/electron/electron/issues/23983

**Comment by codebytere** [comment] 2020-07-07 16:20
Duplicate of https://github.com/electron/electron/issues/23983

**Closed by codebytere** 2020-07-07 16:20 UTC
