### ISSUE TITLE
Windows 10: Window is not put to front on focus()

### ISSUE THREAD

**Issue by bpasero** [electron/electron#2867] opened 2015-09-22 09:49 UTC
I am hitting an issue where a window (in Windows 10) is not being put to the front when I call focus() on it. The same code brings the window to the front on Windows 8 and below, so something must have changed in Windows 10 with regards to window management.

What I see happening is that the task bar is flashing in orange, so there is some indication. Just the window does not get focussed properly.

**Comment by OlsonDev** [comment] 2015-09-22 13:36
I find it interesting you've had this working at all in the past. I've always found it to be relatively inconsistent due to `ForegroundFlashCount` and `ForegroundLockTimeout`; see http://www.thewindowsclub.com/disable-flashing-taskbar-buttons-windows if you're unfamiliar.

**Comment by zcbenz** [comment] 2015-09-23 03:33
Under the hood `focus()` just called [SetForegroundWindow](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633539(v=vs.85).aspx) API, from the description it only brings window to foreground if the calling process is a foreground process.

From #1954 it seems that Windows 10 starts to treat the renderer process of Chromium as foreground process, and thus the browser process becomes a background process, resulting in `SetForegroundWindow` not working.

I can probably fix this by calling `AllowSetForegroundWindow` in the renderer process to allow browser process to set foreground window, but I need to install Windows 10 first.

P.S. @bpasero Is it possible for you to reach the Windows team to verify my assumption? I know Microsoft is HUGE and it is hard to find the right team, but it can help understand the mysterious behaviors.

**Comment by bpasero** [comment] 2015-09-23 05:25
@zcbenz I will try to find a contact, meanwhile if you have a change in mind, I can build electron on my windows 10 to verify the fix. Is it possible that this also causes the issue that I cannot set user tasks anymore to the task bar menu of the window?

**Comment by paulcbetts** [comment] 2015-09-23 06:04
@bpasero Start at `win32prg` and go from there

**Comment by bpasero** [comment] 2015-09-23 06:11
@paulcbetts ???

**Comment by paulcbetts** [comment] 2015-09-23 06:18
@bpasero Open up Outlook and look in the GAL for it :)

**Comment by bpasero** [comment] 2015-09-23 06:28
@paulcbetts ah you are talking about an email alias, I was searching electron source code for "win32prg" to fix this myself ;). Yeah I might have some people to ask, might not get back to me until Redmond wakes up though.

**Comment by paulcbetts** [comment] 2015-09-23 06:52
Fixing this Properly actually might be not particularly trivial if you have to do it The Hard Way. Basically:

1. Every time a renderer process gets focus (either pragmatically, or via normal means), it needs to signal the browser process with its window ID.
1. When someone calls `focus`, they signal the browser to ask, "Can you tell whoever currently has focus to AllowSetForegroundWindow me?"
1. Browser has to IPC that renderer, who calls AllowSetForegroundWindow and responds back
1. Browser has to signal the `focus` caller and say "Yep you can SetForegroundWindow now"

However, Windows probably has some heuristics around this and there might be a _way_ less involved way to do it (do all processes in a Job share SetForegroundWindow'ability? Maybe!)  This is where `win32prg` comes in, because the people on that list probably built some of this stuff.

**Comment by antoinepairet** [comment] 2015-10-19 08:59
@zcbenz if I understand [your previous comment](https://github.com/atom/electron/issues/2867#issuecomment-142480964) correctly, I should be able to bring a window to the foreground only if the call is made a foreground process. Therefore I understand that to have it working:
 * Win 10: the call needs to be made from the renderer process
 * Win 7, Win 8: the call needs to be made from the main process

As far I am concerned (see #3124), the call is made from the renderer process. If my assumptions are correct, I should get this working using windows 10. I will try it and report the result here.

Looking forward to have the feedback from the Windows team :-).
Thanks to everyone involved!

**Comment by bpasero** [comment] 2015-10-19 09:06
@antoinepairet is it really possible to make the call from the renderer? My understanding is that the call is just getting proxied, but still executed on the main side.

**Comment by antoinepairet** [comment] 2015-10-19 09:34
@bpasero I do not know the internal details of electron. Here is what I do: In the renderer process, I am loading a DLL using `node-ffi`. Still within the renderer process, I call a function of that DLL which in the end calls [`ShowWindow`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633548(v=vs.85).aspx).

FYI, NW.js also seem to struggle with similar issues: https://github.com/nwjs/nw.js/issues/3387

**Comment by bpasero** [comment] 2015-10-19 09:35
Ah ok that might work, I thought you would go through the official Electron API to focus a window.

**Comment by antoinepairet** [comment] 2015-10-28 16:53
We found a bug in our code. Shame on me. :-s.
To recap: from the renderer process, we successfully call `showWindow` through a DLL through ffi. It works on Win7 and Win8. Not tested under Win10.
Sorry for the confusion.
regards

**Comment by bpasero** [comment] 2015-10-28 21:38
@antoinepairet is your node-ffi code somewhere on GitHub? Just curious...

**Comment by antoinepairet** [comment] 2015-11-01 18:05
@bpasero Sorry for the late response. It's closed source but if you are interested, we can setup a Skype call or Google Hangout for a quick demo and have a look at the code :-). I am on CEST.

**Comment by jorangreef** [comment] 2015-11-03 09:27
I ran into this today. It's a huge blocker for using BrowserWindow on Windows 10, since if you ever hide a BrowserWindow there is no way to give focus back to it.

@zcbenz have you tried calling AllowSetForegroundWindow in the renderer just to see if it works?

@bpasero have you made any progress within Microsoft?

Would be great to have this fixed.

**Comment by bpasero** [comment] 2015-11-04 19:47
After reading https://github.com/atom/electron/issues/1954#issuecomment-150959890 I have setup the latest Windows insider build and I cannot reproduce the issue anymore. It seems to me that Windows 10 v10565 now behaves again like Windows 8 in terms of Windows and SetForegroundWindow. To verify this assumption I have send a mail on win32prg.

**Comment by bpasero** [comment] 2015-11-05 00:52
Ok more insights: There is in fact **no** difference between the stable Win 10 and the insiders release. However there is a difference with how window.focus() works depending on wether the window is minimized or not. I was likely testing it with a minimized window in the one build and non-minimized in the other.

If I call `window.minimize()` right before `window.focus()`, I can get the window to the foreground no matter what on Windows 10.

**Comment by jorangreef** [comment] 2015-11-05 06:11
Thanks @bpasero

**Comment by bpasero** [comment] 2015-11-06 03:00
@zcbenz would it actually be possible to call SetForegroundWindow from the renderer process without going through the main process? win32prg agrees that the workaround in https://github.com/atom/electron/issues/2867#issuecomment-142511956 is ugly and if you can call SetAllowForegroundWindow from the renderer you might as well just call SetForegroundWindow directly.

**Comment by zcbenz** [comment] 2015-11-06 03:19
@bpasero We can probably pass the window handle to renderer process and call `SetForegroundWindow` there whenever `BrowserWindow.focus` is called.

**Comment by bpasero** [comment] 2015-11-06 05:38
@zcbenz I can look into that and verify the solution if you could send me pointers how to wire that up.

**Comment by zcbenz** [comment] 2015-11-06 08:49
@bpasero You can references how `WebContents::ExecuteJavaScript` or `WebContents::EnableDeviceEmulation` is implemented to have an idea of how to send the handle to renderer process, it can be put under `NativeWindowViews::Focus`.

**Comment by bpasero** [comment] 2015-11-09 07:48
@zcbenz any clue if/how it is possible to get a hold of the renderer window's HWND from the renderer side?

**Comment by zcbenz** [comment] 2015-11-09 08:28
@bpasero You can send a synchronous message to the main process to get it, an example is the `SendSync` API.

**Comment by tyv** [comment] 2016-06-07 12:44
Any updates with this issue?

**Comment by friksa** [comment] 2016-06-20 22:15
+1 to fix this

**Comment by felixtosh** [comment] 2016-08-08 10:13
+1 - can we get a heads-up on that issue?

**Comment by ro78** [comment] 2016-09-13 15:45
+1

**Comment by mrtdeh** [comment] 2016-09-29 16:39
+1

**Comment by doonetheprune** [comment] 2016-09-30 09:03
Hi 

I solved my problem by changing the ForegroundLockTimeout in the registry. [https://www.npmjs.com/package/windows](url) supports changing the registry. Its by far not the best or a good solution, however if like me you need the window to popup, it might be worth a go.

**Comment by bpasero** [comment] 2016-09-30 10:00
Confirmed this works for me after a Windows restart.

**Comment by bpasero** [comment] 2016-10-07 07:21
This is a good blog post about why on Windows you cannot put a window to the foreground if you are a second instance that talks to the first instance: https://blogs.msdn.microsoft.com/oldnewthing/20090220-00/?p=19083

For VS Code this is the main issue that users are reporting and we will probably go with a custom solution where we call `AllowSetForegroundWindow` from the second instance. 

I think if a solution is being added to Electron it would have to bake it into the `app.makeSingleInstance` API.

**Comment by the-ress** [comment] 2016-10-07 09:25
It looks like `app.makeSingleInstance` uses Chromium code that [already does this](https://github.com/electron/electron/blob/787bc8570382e98c4f204abff05b2af122e5a422/chromium_src/chrome/browser/chrome_process_finder_win.cc#L58).

**Comment by bpasero** [comment] 2016-10-07 10:09
Interesting, I guess its time to write a simple test app to try this out using `app.makeSingleInstance`

**Comment by andreieftimie** [comment] 2016-10-20 12:14
Hi guys, any updates here?
A workaround that actually works?

I've tried calling `focus()` from both the Main and from the Renderer process without any success.

**Comment by felixtosh** [comment] 2016-11-16 13:19
Still having that issue - [beer offer](https://github.com/electron/electron/issues/2867#issuecomment-238195819) stands :)

**Comment by andreieftimie** [comment] 2016-11-16 20:48
@felixtosh we fixed (worked around) this by enabling `setAlwaysOnTop` and disabling it afterwards:

```
const win = new BrowserWindow();
win.setAlwaysOnTop(true);
win.focus();
win.setAlwaysOnTop(false);
```

**Comment by wkentdag** [comment] 2016-12-01 22:15
@felixtosh, @bpasero's [workaround](https://github.com/electron/electron/issues/2867#issuecomment-153918442) is also pretty painless for now: call `window.minimize()` before `window.focus()` 👍

**Comment by bpasero** [comment] 2016-12-02 05:47
We are not using that hack anymore, it never really worked. The solution is to use either `app.makeSingleInstance` or the awesome [windows-foreground-love](https://www.npmjs.com/package/windows-foreground-love) module from @the-ress

**Comment by CptMaumau** [comment] 2017-06-29 03:07
Any news on this? I can't find a way to put my app window to front when I click a notification in Windows 10

**Comment by ruleechen** [comment] 2017-07-31 07:09
@bpasero i have tried [windows-foreground-love](https://www.npmjs.com/package/windows-foreground-love) and it seems does resolve the focus issue.

**Comment by ruleechen** [comment] 2017-07-31 07:20
+1 to fix this

**Comment by enlight** [comment] 2017-08-09 07:03
If the suggested workarounds no longer work it may be related to #9291

**Comment by robinwassen** [comment] 2017-10-13 08:09
The following workaround causes other functional regressions:

	const win = new BrowserWindow();
	win.setAlwaysOnTop(true);
	win.focus();
	win.setAlwaysOnTop(false);

It brings the windows properly to the front, but the focus inside the window (e.g. caret in a textbox) is lost.

**Step to reproduce:**
1. Run the following code in the dev console of your app

		setTimeout(function() {
			var win = require("electron").remote.getCurrentWindow();
			win.setAlwaysOnTop(true);
			win.focus();
			win.setAlwaysOnTop(false);
			console.log("Focus");
		}, 4000)

2. Focus a textbox
3. Switch focus to another application
4. Wait for your application to be brought to front
5. Enter text into the textbox without manually focusing it

**Expected result:** You should be able to enter text

**Actual result:** The textbox focus is lost and you cannot enter text

**Functional comparison:** Alt+Tab between applications to see how it works when it works as intended

**Comment by PerfectionCSGO** [comment] 2018-02-06 14:45
This seems to occur on windows 7 as well as windows 10.
It does not seem to occur on windows 8.1.

**Comment by robsonhermes** [comment] 2018-08-02 09:04
While we wait for a fix, sharing the code I used to work around the issue:

`//This is how I show the window`
`win.setAlwaysOnTop(true);`
`win.show();`
`win.setAlwaysOnTop(false);`

`//But the window is not focused, even if I call win.focus(). The below did the trick`
`app.focus();`

**Comment by robinwassen** [comment] 2018-08-16 16:13
**Short version:** I was planning on fixing this in Electron since it is highly requested, but decided not to since I think it would take Electron in the wrong direction. Instead I created a module for forcing focus in Windows: https://github.com/robinwassen/forcefocus

**Long version:** See comment on my PR: https://github.com/electron/electron/pull/10783#issuecomment-413599294

**To the Electron maintainers:** If the module is a good enough work around I guess you can refer people to it and close this issue.

**Comment by codebytere** [comment] 2018-09-23 18:16
Given the above workaround, and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!

**Closed by codebytere** 2018-09-23 18:16 UTC
Labels: bug :beetle:, platform/windows

**Comment by ventsislav-georgiev** [comment] 2019-05-09 10:41
The @robinwassen's lib has a native dep and this complicates the build process which is a stopper for some projects and @robsonhermes' solution does not focus the window if it is already open, just moves it to the foreground. 😞 
We need a proper solution without native dependencies.

**Comment by robsonhermes** [comment] 2019-05-17 08:54
@ventsislav-georgiev 

Electron v4.2.0 contains fix [18079](https://github.com/electron/electron/pull/18079)

I know the fix explicit mentions `.show()`, but maybe it also fixes the problem with `.focus()`

Guess it is worth trying. I could not check yet. Will post here when having the time.

**Comment by jwheare** [comment] 2019-05-17 08:59
It doesn't fix it. My workaround is to have an event triggered in the webapp on notification click and then use this monstrosity to trigger a focus in the electron side:

https://github.com/irccloud/irccloud-desktop/blob/694923a20efd42bcc09943c8167c8fcffb3f0a01/app/render/notification.js#L4-L9

**Comment by nehbit** [comment] 2019-08-06 22:11
Another vote for this. We're facing this issue as well with our Electron app.

**Comment by NathanHawks** [comment] 2020-01-03 04:47
Contrary to a report earlier in this thread, the issue does exist on Windows 8.1. 

I tried to use the `.setAlwaysOnTop()` solution but while `.setAlwaysOnTop(true)` does work, `.setAlwaysOnTop(false) does not work.

`.moveTop()` also does not work.

**Comment by elliottzheng** [comment] 2020-06-20 10:42
Thanks to @robinwassen, https://www.npmjs.com/package/@adeperio/forcefocus this works for me.

**Comment by ericblade** [comment] 2020-10-21 10:56
... for what it's worth, it should probably be in the documentation that BrowserWindow.show() is effectively non-functional for single window applications when running in Windows.  BrowserWindow.show() will bring a window to the front only if it shares (X,Y) screenspace with another window from the same application.

**Comment by rmuchall** [comment] 2021-02-08 13:13
This should probably be re-opened as there are definitely issues surrounding focus under Windows.
The comment below solved the problem for me without requiring any third party dependencies:
https://github.com/electron/electron/issues/9291#issuecomment-409859882

**Comment by pushkin-** [comment] 2021-02-08 15:06
@bpasero You say above:
>If I call window.minimize() right before window.focus(), I can get the window to the foreground no matter what on Windows 10.

And later:
>We are not using that hack anymore, it never really worked and can cause some serious issues with OS windows manager

This trick seems to work for me. What issues were you running into that made you stop using it?

**Comment by ericblade** [comment] 2021-02-08 15:48
@rmuchall 's version seems to work pretty well in Windows at least, better than any other method i've found so far, however, the keyboard focus is not being forced into the window.  That might actually be preferable for my application, but it's directly in contradiction of what the code seems to indicate it should do :-)

**Comment by ericblade** [comment] 2021-02-08 15:52
> @bpasero You say above:
> 
> > If I call window.minimize() right before window.focus(), I can get the window to the foreground no matter what on Windows 10.
> 
> And later:
> 
> > We are not using that hack anymore, it never really worked and can cause some serious issues with OS windows manager
> 
> This trick seems to work for me. What issues were you running into that made you stop using it?

I can say for sure that messing with the minimized state definitely does weird things with the state of windows that are positioned using Aero-Snap in Windows.

**Comment by rmuchall** [comment] 2021-02-08 22:37
> ... though, after using it for a while, there is an odd flicker of the window occasionally that i can't yet explain
> 
> ... scratch that, it doesn't work 100% reliably when other windows are in front of it, still only works 100% when another window from the same app is already in the fore.

Hi @ericblade ,
Weird, I'm not seeing the issues you describe above. My app uses a single BrowserWindow. I'm not sure if that would make any difference. I'll try putting together a minimal repository. Are you seeing those issues in Windows 10?

**Comment by ericblade** [comment] 2021-02-08 22:56
@rmuchall yeah, i can pretty consistently defeat it coming foreground if I have Visual Studio Code or Vivaldi maximized.  It does work better/more consistently than most of the other solutions that don't involve native plugins, though.    The flashing seems to be some other window in the application coming forward briefly before the correct one does.  It may have to do with that my application has many windows... which is part of why i want to bring forward specific ones.. 

i'm presently using a native node module called 'forcefocus', but it has pretty awful drawbacks, too.. namely it screws up keyboard input.

**Comment by rmuchall** [comment] 2021-02-08 23:23
@ericblade 
Thanks for the info! :)
I've created a minimal repository. If possible, please could you check if it has the same issues that you listed above?
https://github.com/rmuchall/electron-focus

**Comment by CiriousJoker** [comment] 2021-07-13 10:39
From a user's perspective, this is terrible.
If an Electron window tries to get focus and doesn't get it due to this issue, Windows tries to make the taskbar flash.
However, if I understood it correctly, this bug causes the renderer process to get focus which isn't possible, resulting in nothing flashing.
However, the taskbar still won't close (I have it set to auto-hide).
I then have to cycle through all Electron windows (Spotify, Discord etc.) until I found the window that tried to grab focus...

Please consider fixing this issue if the behavior is caused by this issue.

**Comment by ericblade** [comment] 2021-07-23 12:06
@CiriousJoker that doesn't sound related

unfortunately, the TLDR on this thread is -- there's not really anything to fix.  Windows (the product)' window management features don't explicitly allow this to occur, and pretty much every way around it is garbage.

**Comment by liuyike98** [comment] 2021-12-06 09:08
> While we wait for a fix, sharing the code I used to work around the issue:
> 
> `//This is how I show the window` `win.setAlwaysOnTop(true);` `win.show();` `win.setAlwaysOnTop(false);`
> 
> `//But the window is not focused, even if I call win.focus(). The below did the trick` `app.focus();`
> 
> Not the best solution, but at least solved my problem meanwhile...

that's so fanny, 2021 now, still has the problem, and your method still works

**Comment by gkourpa** [comment] 2022-01-12 13:41
I discovered that if you first minimize and then restore the `win` object, you can successfully bring it to the foreground, above all the other windows. The following did the work for me on Windows 10.
`
if (!win.isFocused()) {
  win.minimize();
  win.restore();
  win.focus();
}
`

**Comment by kreativhut** [comment] 2022-02-16 06:32
Take a look into [BrowserWindow.moveTop()](https://www.electronjs.org/docs/latest/api/browser-window#winfocus). Bring the window above all the other windows. Did the work for me.

**Comment by darklightblue** [comment] 2022-03-28 12:12
2022, `minimize` then `focus` no longer works (at least for me). What [liuyike98](https://github.com/liuyike98) suggested however still works:

```
  ipcMain.on('foreground', () => {
    mainWindow?.setAlwaysOnTop(true);
    mainWindow?.show();
    mainWindow?.setAlwaysOnTop(false);
  });
```

For some reason the `app.focus();` doesnt't work for me tho, but I guess this is better than having your app behind the browser/other apps.

**Comment by skident** [comment] 2023-06-07 10:13
@darklightblue, your example of `setAlwaysOnTop(true/false)` has a bad side-effect on Windows 11. Once, you close the app window, OS will bring to front one or two non-related windows (for instance, you had opened a notepad, a browser and other applications, so then one of those windows will be pushed to foreground).

**Comment by sinamotamedi** [comment] 2023-07-14 21:36
The workaround of calling `window.minimize()` first works for Windows but on Mac it makes the app launch minimized to the dock.

```
window.minimize();
window.show();
```

Instead, using `window.setAlwaysOnTop()` seems to work for both platforms.
```
window.show();
window.setAlwaysOnTop(true);
window.setAlwaysOnTop(false);
```

It's worth noting that we observed this issue only happens when we construct the `BrowserWindow` object with `show: false`. If we do `new BrowserWindow({ show: true })` then the app launches in the foreground. It's only when we do new `BrowserWindow({ show: false })` and later call `window.show()` that we encounter this problem. We do the latter so we can wait for the page to be loaded before displaying the app to the user.

Not sure why this issue is unresolved after 8 years and this thread is closed. At a minimum, the [Electron docs](https://www.electronjs.org/docs/latest/api/browser-window#winshow) should be updated.

**Comment by TreeOfAlpha** [comment] 2023-08-21 07:21
After having to fight with this issue for most of the day yesterday none of the solutions here were acceptable.
The closest one was @robinwassen's "forcefocus", but it messes with keyboard input and that is a dealbreaker for my use case.

I ended up adopting a very hacky but functional workaround.
Bottom line is: Windows only cares that the user is actually doing something at the time of showing the window, so the easiest and most stable fix is to emulate keyboard/mouse input at the time.

I used RobotJS and tried several keyboard/mouse input combinations including "alt" and "shift", but the most stable, smooth and least harmful for the user ended up being a simple mouse click release.

```
const robot = require('robotjs');

robot.mouseToggle("up");
win.show();
win.focus();
```

Combined with electron-rebuild, this offered a smooth alternative to Windows' sturbborness and hope this can help someone out.

**Comment by ikarofelix** [comment] 2025-05-22 14:04
If you're still experiencing this issue, here's something that worked for me.
**Note: all of this was tested on Windows only, it may work for you on linux or mac or some changes may be needed.**

Initially, I was using the following code:

```
win.show();

if (win.isMinimized()) win.restore();

win.setAlwaysOnTop(true);
app.focus();
win.setAlwaysOnTop(false);
```

However, after some testing, I found that this approach only successfully focused the window when the app was minimized or closed but still running in the system tray. If the app had just lost focus (e.g. switched away via Alt+Tab), this code wouldn’t bring it to the foreground.

After further experimentation, this version worked consistently for me:

```
if (!win.isFocused() && !win.isMinimized()) win.minimize();

win.show();

win.setAlwaysOnTop(true);
app.focus();
win.setAlwaysOnTop(false);

```
Hope this helps someone out there!

**Comment by Gvozd** [comment] 2025-07-10 17:30
This works in all the cases I've tested, but I'm not sure about the value of the delay.
```js
win.show();
setTimeout(() => win.focus(), 200);
```
