### ISSUE TITLE
Embedded window renders transparent over the electron window in windows 10

### ISSUE THREAD

**Issue by sachetsharma1** [electron/electron#26729] opened 2020-11-29 23:43 UTC
* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.1
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * None

### Expected Behavior
Embedded window should be visible.

### Actual Behavior
Embedded window renders over the Electron window but is transparent.

### To Reproduce

- Create a C# form application.
- Create a Electron application.
- Open a window in Electron application.
- Start the c# application and pass the native window handle of the electron window to the c# application. 
- Set the c# application window as a child of the electron window using the native win32 API using the give electron window handle. 

In our case we are using the following APIs:
 
```
[DllImport("user32.dll")]
   public static extern IntPtr SetParent(IntPtr hWndChild, IntPtr hWndNewParent);
 
[DllImport("user32.dll")]
   public static extern bool GetWindowRect(IntPtr hwnd, out RECT rectangle);
```

### Additional Information
The workaround is to follow the parent window, but this approach has sufficient drawbacks:
 - The embedded window is not clipped by parent window size
 - Embedded window needs to calculate the correct z-index of the parent window and regulate the topmost property by itself, sometimes it is not correct (not often but still happens)
 - To follow the parent, embedded window needs to watch parent position

**Note:** This feature works fine in windows 7 without using the workaround.

**Comment by ckerr** [comment] 2020-12-03 18:14
Hi @sachetsharma1, thanks for reaching out!

This is a tricky issue because of the level of technical involvement. I have two thoughts:

1. Because of time constraints, triaging code with external dependencies is usually not feasible for a small team like Electron's. The issue described here will require significant setup time before we can even try to reproduce the bug. Multiply that by the number of new issues reported to Electron every day and you see the scaling problem. I understand that by definition some external code is required for this test; however, if you could create a minimal testcase that would make life easier for the team in regards to triage.

2. Even if we have a testcase, this is a pretty involved issue of an edge use case of using embedded native windows via native imported APIs. I suspect this issue will get fixed faster if you're interested in digging into Electron's code and championing the issue yourself. If so, consider joining the [the Electron Discord server](https://discord.com/invite/electron) for followup discussion!

I'm adding a `blocked/needs-repro` label to this issue for point #1; however, I think #2 is the more important question.

I hope this helps!

**Comment by sofianguy** [comment] 2021-01-05 21:39
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2021-01-05 21:39 UTC
Labels: 9-x-y, blocked/need-repro, bug :beetle:, platform/windows
