### ISSUE TITLE
macOS: Cursor resets to default when notification is displayed

### ISSUE THREAD

**Issue by envex** [electron/electron#14328] opened 2018-08-27 15:32 UTC
* Output of `node_modules/.bin/electron --version`: v2.0.2
* Operating System (Platform and Version): MacOS High Sierra 10.13.6 (17G65)

**Expected Behavior**

Cursor doesn't reset to default when a macOS alert is displayed or hidden.

**Actual behavior**

When the mouse button is pressed and the cursor is changed via css, the cursor is reset to default when a macOS alert is displayed or hidden.

**To Reproduce**

```sh
$ git clone git@github.com:envex/electron-quick-start.git -b cursor-focus
$ npm install
$ npm start || electron .
```

- Launch the app.
- In the terminal run the following snippet which will display an alert every 10 seconds.
```
while true; do osascript -e 'display notification "Alert"'; sleep 10; done;
```
- Dismiss the first alert and mousedown on the red rectangle.
  - The cursor should change to `crosshair` and the rectangle should turn green.
- Wait for the alert to display.
  - The cursor will reset to `default`.
  - The rectangle will remain green.

> NOTE: It's random, but sometimes the cursor resets when the notification hides itself instead of on display.

**Screenshots**

Video: https://www.dropbox.com/s/iudu607w3uwb1j9/cursor-focus.mov?dl=0

**Comment by akashnimare** [comment] 2018-08-29 18:37
Unrelated - this is how everyone should file a bug. @envex great details 👏

**Comment by envex** [comment] 2018-08-29 18:38
@akashnimare Thank you!

**Comment by CvX** [comment] 2019-01-22 13:31
@akashnimare It's not an Electron bug. It's the default behavior of macOS (though it's most likely because of a bug and not an intentional feature).

Try the same with, for example, the resize cursor on the window border of Finder. Or the text cursor in Notes.

**Comment by sofianguy** [comment] 2019-08-08 23:54
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:34
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:34 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS, status/confirmed
