### ISSUE TITLE
window.onbeforeunload not fired when a BrowserView is closed

### ISSUE THREAD

**Issue by ccnokes** [electron/electron#14020] opened 2018-08-10 18:00 UTC
* Electron Version: 2.0.7
* Operating System (Platform and Version): MacOS 10.13.6
* Last known working Electron version: 

**Expected Behavior**
When a renderer process in a BrowserView is closed, I expect the `window.onbeforeunload` event to fire.

**Actual behavior**
It does not fire in a BrowserView renderer.

**To Reproduce**
Run this code in an Electron fiddle https://gist.github.com/ccnokes/88d847e32a8a2e6ba1eca15cb9e5bc47
When the window opens, close it (but don't quit the app)
Note that there's no message received from the renderer
Also note that you can comment in the same code with a `onbeforeunload` event that works when it's run in a BrowserWindow but not in a BrowserView

Let me know if you want a repo.

Possibly related to https://github.com/electron/electron/issues/5661?

**Comment by sofianguy** [comment] 2019-08-09 00:08
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:38
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by ccnokes** [comment] 2019-08-23 21:24
@sofianguy this is still an issue in Electron 6. Can we re-open? I updated the fiddle to work in 6.

**Comment by Xylobol** [comment] 2020-01-04 05:55
Still effects 7.x. I think this isn't a case of broken functionality as much as it is a case of needing different functionality. .destroy() does the same thing for both BrowserWindow and BrowserView, however, only BrowserWindow has .close(), which is what I think OP & I are looking for.

**Comment by kevinlinv** [comment] 2020-04-02 01:56
This affects 8.x and would probably affect any new version of electron too.

> I think this isn't a case of broken functionality as much as it is a case of needing different functionality.

I agree with @Xylobol, at present, there is no direct API on `BrowserView` that would allow us to gracefully close the `webContents` that would trigger `beforeunload`. I played around with a solution that involves reloading the `webContents` to maybe trigger `beforeunload` on my page and a timeout to decide whether we should destroy the `BrowserView`, but that solution is less than ideal.

That said, `BrowserView.close` would be a much-needed addition at this point, since it is no longer experimental. Does anyone know the appropriate steps that we should take to surface an API addition request to the team?

**Comment by YogaLin** [comment] 2020-04-12 10:08
Handly trigger `beforeunload` event before destroy works right now.

`webContents.executeJavaScript('window.dispatchEvent(new Event("beforeunload"))');`

**Comment by kevinlinv** [comment] 2020-04-14 01:05
O, that's one workaround, thanks for sharing @YogaLin 👌

**Comment by electron-triage** [comment] 2021-03-08 17:00
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-08 17:00 UTC
Labels: 2-0-x, 6-0-x, 6-1-x, bug :beetle:, platform/macOS

**Comment by pushkin-** [comment] 2021-03-08 17:15
This repros in Electron 11. Also, I think this is a dupe of [this](https://github.com/electron/electron/issues/20746)

**Comment by nornagon** [comment] 2021-03-12 00:59
Duplicate of #20746
