### ISSUE TITLE
Assigning guestinstance to webview sometimes reverts to undefined

### ISSUE THREAD

**Issue by mhuggins** [electron/electron#13144] opened 2018-06-02 23:01 UTC
* Electron Version: 2.0.0
* Operating System (Platform and Version): macOS High Sierra 10.13.3
* Last known working Electron version: N/A

**Expected Behavior**
When creating a new webview and assigning a `guestinstance` attribute copied from another webview, the new webview should take on the `guestinstance` attribute value.

**Actual behavior**
When creating a new webview and assigning a `guestinstance` attribute copied from another webview, the new webview's `guestinstance` attribute value is `undefined`.

**To Reproduce**
I created a sample repo here, the [last commit](https://github.com/nos/electron-move-webview/commit/a9091bc9ae48ed37c9ae81ae9edcc3a5930668f3) containing the example code that demonstrates the issue.

```sh
$ git clone https://github.com/nos/electron-move-webview
$ cd electron-move-webview
$ yarn install && yarn start
```

This is the code in a nutshell:

```js
moveWebview = (existingWebview, container) => {
  const { attributes } = existingWebview;
  const webview = document.createElement('webview');

  console.log('original guestinstance:', existingWebview.guestinstance); // "2"

  for (let i = 0; i < attributes.length; i += 1) {
    webview.setAttribute(attributes[i].nodeName, attributes[i].nodeValue);
  }

  console.log('copied guestinstance:', webview.guestinstance); // undefined

  document.body.appendChild(webview);
  existingWebview.parentNode.removeChild(existingWebview);

  return webview;
}
```

The behavior is the same if I replace the for-loop above with this one-liner:

```js
webview.guestinstance = existingWebview.guestinstance;
```

**Screenshots**
![electron-move-webview](https://user-images.githubusercontent.com/169093/40881666-2dfe7832-6692-11e8-8470-cfb56200fbe3.gif)

**Additional Information**
* This doesn't seem to be consistent.  In the scenario I'm seeing it, it's happening when moving from one DOM element B to A, but not from A to B.  Element B appears later in the DOM, in case it's relevant.
* In the scenario where this does assign the `guestinstance` value properly, the second webview never actually loads the content.  It behaves like an empty `div`.
* A hunch from the above info -- it seems like the `webContent` might be unloading on the first move, and so the guestinstance isn't able to be assigned on the second move.  I'm not sure why the content isn't loading on the first move though.

**Comment by mhuggins** [comment] 2018-06-03 14:07
I'm realizing now that this is a duplicate of #12251.  If I wrap the `removeChild` call with a `setTimeout` of 1000 ms before removing the original webview from the DOM, then everything works as expected.  This isn't realistic though since I'm using react, and this is happening in the context of `componentWillUnmount`, which won't wait for a delay before continuing.

**Comment by ckerr** [comment] 2018-07-22 05:32
Closing this as a duplicate of #12251

**Closed by ckerr** 2018-07-22 05:32 UTC
Labels: bug :beetle:, platform/macOS, version/2.0.x
