### ISSUE TITLE
win_delay_load_hook would not work if there is no visual c++ redistributable on win7/8

### ISSUE THREAD

**Issue by daCapricorn** [electron/electron#18014] opened 2019-04-28 05:06 UTC
### Issue Details

* **Electron Version:**
  * 4 and above
* **Operating System:**
  * Windows 7 / 8 (Windows 10 is OK)
* **Last Known Working Electron version:**:
  * 3.1.8 (because win_delay_load_hook not needed)

### Expected Behavior
Load .node files without any errors.

### Actual Behavior
Failed to load .node files. It show the error: The specified module could not be found.

### To Reproduce
On a win7 pc without visual c++ redistributable, try to load a .node file.

### A Solution
Use a custom nsis script to install visual c++ redistributable. But I think a better way to solve the issus is make electron packaged with visual c++ runtime.

**Comment by nornagon** [comment] 2019-04-29 17:08
Is your module is linked against the vc++ runtime? In that case, I'm confused why it would work on 3.1.8 and not 4. To my knowledge (though I might be wrong), the win_delay_load_hook code itself does not invoke any functions that are specific to the vc++ runtime.

**Comment by daCapricorn** [comment] 2019-04-30 08:49
@nornagon The 3rd party module is [https://github.com/cmake-js/fastcall](url). I don't think it need invoke any functions that are specific to the vc++ runtime, because it just work well on <4.

**Comment by TanninOne** [comment] 2019-06-03 10:48
win_delay_load_hook is a red herring. The reason this fails is because electron v3 and earlier included the vc runtime and newer releases don't.
Every electron application that uses native modules has a new dependency on windows.
And no, to my knowledge this was not communicated publicly.

**Comment by brenthompson** [comment] 2019-06-20 16:43
Any solution forthcoming? @daCapricorn could you provide a detailed workaround?

**Comment by electron-triage** [comment] 2020-02-19 20:42
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:26
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:26 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/windows

**Comment by Superlokkus** [comment] 2020-02-27 15:20
Is it just me, or shouldn't this issue be reopned? I have this issue too on electron 6 and many recent issues like https://github.com/zeit/pkg/issues/687#issuecomment-585535607 are IMHO suggesting that too.

**Comment by TanninOne** [comment] 2020-02-27 15:57
Arguably this isn't a bug in electron or anything they need to fix. Imho this was simply a bit of bad communication.
In older releases electron linked dynamically to the visual-c runtime and included the libraries. Thus on systems that don't have them installed globally the application would just use the runtime included in electron.
With newer electron versions I guess they are statically linked so electron itself doesn't _need_ the rt anymore so there is no good reason for electron to distribute it.
Honestly I don't think it would be a brilliant idea for electron to ship with libraries it doesn't use, just so applications that _do_ require them _don't_ have to include them directly.

**Comment by Superlokkus** [comment] 2020-02-28 10:38
Well technically you are right, but almost all native applications need the VC++ runtime libs, electron just walked around the problem by static linking to them, which is the non default, AFAIK non recommended way, on one part because electron is already shipping the libraries with in itselfs binary. So from the native modules pov, there are the runtime libs in electron, but it can't use them, but have to use their own, which also caused some exception and runtime problems, when one process is using the runetime in different ways.
For me its also just another "batteries not included" moment, since this is a low hanging fruit, of a thing I strongly assume >95% of native node module user are now patching in their installation routine anyway, but in very different and probably buggy ways. What good is an application framework, when I have to do more and more stuff, in order to be an application.
