### ISSUE TITLE
[Bug]: KDE Plasma denies designated icon

### ISSUE THREAD

**Issue by zeankundev** [electron/electron#32577] opened 2022-01-21 10:43 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

Other Linux

### Operating System Version

KDE neon 5.23

### What arch are you using?

x64

### Expected Behavior

The icon should appear as designated in the program

### Actual Behavior

But KDE just assigned it to a random XWin icon.
![image](https://user-images.githubusercontent.com/58360911/150513462-89eabbd2-ddb0-4fbe-9132-de6dc95414d2.png)
Here is the code for further details. 
```js
function createWindow() {
    const win = new BrowserWindow({
        width: 1024,
        height: 600,
        title: 'Art Studio Pro',
        icon: path.join(__dirname, 'asset/icon.png'),
        webPreferences: {
            nodeIntegration: true,
        },
    })
    win.loadFile('html/index.html')
    win.setMenuBarVisibility(false)
}
```

**Comment by zcbenz** [comment] 2022-01-25 10:59
On Linux the `icon` option is only a hint and the desktop shell is free to ignore it, usually the shell only displays icon when the app has a desktop file installed in system. You can check https://wiki.archlinux.org/title/desktop_entries for more.

I'm closing this as won't fix since it is not a bug.

**Closed by zcbenz** 2022-01-25 10:59 UTC
Labels: bug :beetle:
