### ISSUE TITLE
powerMonitor events not firing on Ubuntu

### ISSUE THREAD

**Issue by KeitIG** [electron/electron#7699] opened 2016-10-21 23:18 UTC
* Electron version: 1.4.4
* Operating system: elementary OS Loki (basically Ubuntu 16.04)

``` javascript
app.on('ready', () => {

    const powerMonitor = require('electron').powerMonitor;

    powerMonitor.on('suspend', () => {
        console.log('SUSPEND');
    });
});
```

does not output anything. Works fine on Windows.

**Comment by zcbenz** [comment] 2016-10-25 00:00
This is a duplicate of #1615.

**Closed by zcbenz** 2016-10-25 00:00 UTC
