### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by an78mK89fy** [electron/electron#44145] opened 2024-10-08 08:47 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.1

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11	23H2	22631.4169	Windows Feature Experience Pack 1000.22700.1034.0

### What arch are you using?

x64

### Expected Behavior

```
const window = new BrowserWindow();
window.setTitle('myTitle');
// After a route change in my HTML file, execute:
window.webContents.navigationHistory.goBack();
// => The title of the window should not be overridden by the HTML's title when `goBack()` is called.
```

### Actual Behavior

```
const window = new BrowserWindow();
window.setTitle('myTitle');
// After a route change in my HTML file, execute:
window.webContents.navigationHistory.goBack();
// => At this point, the title of the window is no longer 'myTitle', but the content of the title tag in the HTML file.
```

### Additional Information

The front-end uses Vue.js + Vue-Router

**Comment by jkleinsc** [comment] 2024-10-08 15:48
Closing as duplicate of #44144

**Closed** 2024-10-08 15:48 UTC
Labels: platform/windows, bug :beetle:, 32-x-y
