### ISSUE TITLE
input with datalist not working

### ISSUE THREAD

**Issue by MichaelF1** [electron/electron#11263] opened 2017-11-26 13:05 UTC
I use electron 1.7.9 with node 7.9.0 on a raspberry pi

input list does get the actual value from the datalist.

I have a input element with a datalist in my electron application and it works just fine if i run my .html file in Chrome. If I start the electron app with "electron ." the input element is not working. My datalist is displayed but if i choose one its set in my input list as suggested but if I do a alert of the input-element I just get what I typed in and not the actual element what is in the datalist. At this point I can not figure out how to fix that or is there any possible solution? Another problem is that if I run my application locally with "./node_modules/.bin/electron ." the datalist elements don´t even show up.

Maybe anyone can help me out if there is a solution for this or a way how I can solve this.

Regards Michael

**Comment by brenca** [comment] 2017-11-26 14:10
This seems to be a duplicate of #9860

**Comment by MichaelF1** [comment] 2017-11-26 19:24
Thanks, so there is no fix up to now?

regards

**Comment by brenca** [comment] 2017-11-26 19:43
Yes, the next release should have the fix for this. As to when the next release is coming, you would have to ask the other Maintainers. :) The last beta was released 20 days ago, and the fix was pulled in 13 days ago, so you can't `npm install` a version that has the fix I'm afraid as of today.

**Comment by sofianguy** [comment] 2017-12-03 01:58
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Closed by sofianguy** 2017-12-03 01:58 UTC
Labels: triaged/helpme, version/1.7.x

**Comment by mDeepanshu** [comment] 2019-02-19 15:13
I m still facing the same problem, if it is resolved then please guide me
