### ISSUE TITLE
[Bug]: "Request Storage.getStorageKeyForFrame failed. {"code":-32602,"message":"Frame tree node for given frame not found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js

### ISSUE THREAD

**Issue by JiangBingLong** [electron/electron#37222] opened 2023-02-10 12:48 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

Winodws 10 version 2200

### What arch are you using?

x64

### Expected Behavior

The error is not printed

### Actual Behavior

console print this error

**Comment by codebytere** [comment] 2023-02-15 12:31
Duplicate of https://github.com/electron/electron/issues/37249 - same underlying issue

**Closed by codebytere** 2023-02-15 12:31 UTC
Labels: bug :beetle:
