### ISSUE TITLE
Renderer crashes with signal 11 SEGV_MAPERR

### ISSUE THREAD

**Issue by herrjemand** [electron/electron#9236] opened 2017-04-20 12:53 UTC
Here is a stack trace

```
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7f5f5acc9d07 <unknown>
#1 0x7f5f48ecffe0 <unknown>
#2 0x7f5f6012f39c <unknown>
#3 0x7f5f6043d713 <unknown>
#4 0x0ac4032883a6 <unknown>
  r8: 00000000beeddead  r9: 00000000beeddead r10: 000009af72c938f0 r11: 00000000beeddead
 r12: 000009af72c92000 r13: 000009af72bc1ff0 r14: 00007ffc8c970d68 r15: 00007ffc8c970d98
  di: 00007ffc8c970c70  si: 000000000000000a  bp: 00007ffc8c970d58  bx: 00007ffc8c970c70
  dx: 0000000000000001  ax: 0000000000000001  cx: 000009af72c92000  sp: 00007ffc8c970c40
  ip: 00007f5f6012f39c efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
```

**Comment by herrjemand** [comment] 2017-04-20 12:55
I've been stuck with this issue for a week. Application does not crash, only renderer.

**Comment by herrjemand** [comment] 2017-04-20 13:02
Ref: #9199

**Comment by herrjemand** [comment] 2017-04-20 17:28
Running electron v1.6.7

**Comment by kevinsawicki** [comment] 2017-05-01 21:22
@herrjemand can you provide the minidump from the crash report submitted by the `crashReporter` module? That should contain enough information to generate a more complete stack trace.

https://electron.atom.io/docs/api/crash-reporter/

Another option would be to set the ELECTRON_DEFAULT_ERROR_MODE env var and then open the crash in Visual Studio.

A third option would be to provide some reproduction steps if possible and and we can investigate it further.

**Comment by kevinsawicki** [comment] 2017-05-31 21:52
Closing this out until more information is available.

**Closed by kevinsawicki** 2017-05-31 21:52 UTC
Labels: more-information-needed

**Comment by creatist** [comment] 2017-09-01 07:54
I got the same problem on my arm linux board ,does it have been resolved?

**Comment by AndrewGrachov** [comment] 2018-01-23 15:19
Upvote. having problems

**Comment by AndrewGrachov** [comment] 2018-01-23 15:20
```
Received signal 11 SEGV_MAPERR 000000001008
#0 0x000001ccd877 <unknown>
#1 0x7f3b3c626890 <unknown>
#2 0x00000292d046 <unknown>
#3 0x000002938923 <unknown>
#4 0x0000029387a5 <unknown>
#5 0x000002934d4f <unknown>
#6 0x000002a2d5c8 <unknown>
#7 0x000003042f35 <unknown>
#8 0x000001cb63ee <unknown>
#9 0x000001d08a2c <unknown>
#10 0x000001d08cd8 <unknown>
#11 0x000001d0903b <unknown>
#12 0x000001cbe20a <unknown>
#13 0x7f3b37f9ec5d g_main_context_dispatch
#14 0x7f3b37f9ef48 <unknown>
#15 0x7f3b37f9effc g_main_context_iteration
#16 0x000001cbe0f6 <unknown>
#17 0x000001d087c7 <unknown>
#18 0x000001ceb110 <unknown>
#19 0x000002996248 <unknown>
#20 0x000002996095 <unknown>
#21 0x0000029e414d <unknown>
#22 0x0000029898fe <unknown>
#23 0x0000026da1a4 <unknown>
#24 0x0000026da5b0 <unknown>
#25 0x000003b85c43 main
#26 0x7f3b36024b45 __libc_start_main
#27 0x0000005a97c9 <unknown>
r8: 00007fff94d41610 r9: 0000000000000000 r10: 000000000000000c r11: 0000000000000246
r12: 00007fff94d41610 r13: 0000000000006d01 r14: 0000000000000000 r15: 0000000000006ddc
di: 000000000000000b si: 000007326b4c7ae0 bp: 000007326be8d200 bx: 000007326b5173c0
dx: 0000000000000000 ax: 0000000000001000 cx: 0000000000000000 sp: 00007fff94d41550
ip: 000000000292d046 efl: 0000000000010246 cgf: 0000000000000033 erf: 0000000000000004
trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000001008
[end of stack trace]
Received signal 11 SEGV_MAPERR 000000001008
#0 0x000001ccd877 <unknown>
#1 0x7efe310df890 <unknown>
#2 0x00000292d046 <unknown>
#3 0x000002938923 <unknown>
#4 0x0000029387a5 <unknown>
#5 0x000002934d4f <unknown>
#6 0x000002a2d5c8 <unknown>
#7 0x000003042f35 <unknown>
#8 0x000001cb63ee <unknown>
#9 0x000001d08a2c <unknown>
#10 0x000001d08cd8 <unknown>
#11 0x000001d0903b <unknown>
#12 0x000001cbe099 <unknown>
#13 0x000001d087c7 <unknown>
#14 0x000001ceb110 <unknown>
#15 0x000002996248 <unknown>
#16 0x000002996095 <unknown>
#17 0x0000029e414d <unknown>
#18 0x0000029898fe <unknown>
#19 0x0000026da1a4 <unknown>
#20 0x0000026da5b0 <unknown>
#21 0x000003b85c43 main
#22 0x7efe2aaddb45 __libc_start_main
#23 0x0000005a97c9 <unknown>
r8: 00007ffc57bd2680 r9: 0000000000000000 r10: 000009d06c6de58c r11: 0000000000000246
r12: 00007ffc57bd2680 r13: 0000000000000201 r14: 0000000000000000 r15: 0000000000000288
di: 000000000000000b si: 000009d06d6d94e0 bp: 000009d06db2f880 bx: 000009d06d766280
dx: 0000000000000000 ax: 0000000000001000 cx: 0000000000000000 sp: 00007ffc57bd25c0
ip: 000000000292d046 efl: 0000000000010246 cgf: 0000000000000033 erf: 0000000000000004
trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000001008
[end of stack trace]
Received signal 11 SEGV_MAPERR 000000001008
#0 0x000001ccd877 <unknown>
#1 0x7fc92751d890 <unknown>
#2 0x00000292d046 <unknown>
#3 0x000002938923 <unknown>
#4 0x0000029387a5 <unknown>
#5 0x000002934d4f <unknown>
#6 0x000002a2d5c8 <unknown>
#7 0x000003042f35 <unknown>
#8 0x000001cb63ee <unknown>
#9 0x000001d08a2c <unknown>
#10 0x000001d08cd8 <unknown>
#11 0x000001d0903b <unknown>
#12 0x000001cbe20a <unknown>
#13 0x7fc922e95c5d g_main_context_dispatch
#14 0x7fc922e95f48 <unknown>
#15 0x7fc922e95ffc g_main_context_iteration
#16 0x000001cbe0f6 <unknown>
#17 0x000001d087c7 <unknown>
#18 0x000001ceb110 <unknown>
#19 0x000002996248 <unknown>
#20 0x000002996095 <unknown>
#21 0x0000029e414d <unknown>
#22 0x0000029898fe <unknown>
#23 0x0000026da1a4 <unknown>
#24 0x0000026da5b0 <unknown>
#25 0x000003b85c43 main
#26 0x7fc920f1bb45 __libc_start_main
#27 0x0000005a97c9 <unknown>
r8: 00007ffcb56ca320 r9: 0000000000000000 r10: fffffffffeac9a80 r11: 0000000000000246
r12: 00007ffcb56ca320 r13: 0000000000000401 r14: 0000000000000000 r15: 0000000000000436
di: 000000000000000b si: 00002b057aa71480 bp: 00002b0579a52b00 bx: 00002b057a261640
dx: 0000000000000000 ax: 0000000000001000 cx: 0000000000000000 sp: 00007ffcb56ca260
ip: 000000000292d046 efl: 0000000000010246 cgf: 0000000000000033 erf: 0000000000000004
trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000001008
[end of stack trace]
```

**Comment by cyril23** [comment] 2018-11-13 16:37
Same issue here. Server has been up and running since over 6 months, thousands of PDFs were created successfully. 

Am using the https://hub.docker.com/r/msokk/electron-render-service/

Hope my last log lines help you fix it:

```
2018-11-12T14:05:39.462646016Z [2018-11-12T14:05:39.461Z] global@172.18.0.1 - GET 200 /pdf?accessKey=MY_SECRET_KEY&url=MY_URL&pageSize=A4&waitForText=pdfready 136729 "-" 3632.103 ms
2018-11-12T14:05:39.987739568Z Received signal 11 SEGV_MAPERR 000000001008
2018-11-12T14:05:40.043726117Z #0 0x000002861aa7 <unknown>
2018-11-12T14:05:40.048214528Z #1 0x00000286161f <unknown>
2018-11-12T14:05:40.053706442Z #2 0x7ff791669890 <unknown>
2018-11-12T14:05:40.056922913Z #3 0x000003136946 <unknown>
2018-11-12T14:05:40.059874715Z #4 0x000003083d5b <unknown>
2018-11-12T14:05:40.062598532Z #5 0x000003081713 <unknown>
2018-11-12T14:05:40.065619381Z #6 0x00000305e933 <unknown>
2018-11-12T14:05:40.068586175Z #7 0x00000346c895 <unknown>
2018-11-12T14:05:40.071391092Z #8 0x00000286ac36 <unknown>
2018-11-12T14:05:40.074298884Z #9 0x0000028cd69d <unknown>
2018-11-12T14:05:40.077208651Z #10 0x0000028cdf68 <unknown>
2018-11-12T14:05:40.080022503Z #11 0x000002852ffa <unknown>
2018-11-12T14:05:40.082793900Z #12 0x7ff78cfe1c5d g_main_context_dispatch
2018-11-12T14:05:40.083772422Z #13 0x7ff78cfe1f48 <unknown>
2018-11-12T14:05:40.084872980Z #14 0x7ff78cfe1ffc g_main_context_iteration
2018-11-12T14:05:40.089179481Z #15 0x000002852ee6 <unknown>
2018-11-12T14:05:40.093963355Z #16 0x0000028cd3b7 <unknown>
2018-11-12T14:05:40.098811041Z #17 0x0000028dad0e <unknown>
2018-11-12T14:05:40.103613911Z #18 0x000002db8c6c <unknown>
2018-11-12T14:05:40.108340537Z #19 0x000002db8ab5 <unknown>
2018-11-12T14:05:40.113302179Z #20 0x000002dd8abd <unknown>
2018-11-12T14:05:40.117900951Z #21 0x0000031f662e <unknown>
2018-11-12T14:05:40.122288951Z #22 0x000002b8ba6c <unknown>
2018-11-12T14:05:40.126651755Z #23 0x000002b8bec0 <unknown>
2018-11-12T14:05:40.129507094Z #24 0x000003e3cc58 main
2018-11-12T14:05:40.131275436Z #25 0x7ff78a9c8b45 __libc_start_main
2018-11-12T14:05:40.135655566Z #26 0x0000005b0f99 <unknown>
2018-11-12T14:05:40.136878257Z   r8: 00007ffd01e14518  r9: 0000000000000000 r10: 00007ffd01e14500 r11: 000c850538113e63
2018-11-12T14:05:40.138113335Z  r12: 00007ffd01e14518 r13: 00003fb274a44101 r14: 0000000000000000 r15: 00000000000008ee
2018-11-12T14:05:40.139410109Z   di: 0000000000000017  si: 00003fb274ba6840  bp: 00003fb274ec3800  bx: 00003fb274246140
2018-11-12T14:05:40.140686338Z   dx: 0000000000000000  ax: 0000000000001000  cx: 0000000000000000  sp: 00007ffd01e144a0
2018-11-12T14:05:40.141510229Z   ip: 0000000003136946 efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
2018-11-12T14:05:40.142498538Z  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000001008
2018-11-12T14:05:40.142644360Z [end of stack trace]
2018-11-12T14:05:40.142819156Z Calling _exit(1). Core file will not be generated.
```

**Comment by AndrewGrachov** [comment] 2018-11-14 06:48
We switched to puppeteer.. It helped )
