### ISSUE TITLE
gl_out_of_memory crash on  windows 7

### ISSUE THREAD

**Issue by lonelyWalkor** [electron/electron#21500] opened 2019-12-13 01:56 UTC
### Issue Details

* **Electron Version: 7.1.4
* **Operating System: windows7
* **Last Known Working Electron version: 4.1.0

### Expected Behavior
![企业微信截图_15762018861365](https://user-images.githubusercontent.com/20573782/70763372-d091d080-1d8e-11ea-87e7-bafabde8f112.png)

**Comment by nornagon** [comment] 2019-12-13 19:37
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

From what you've said, though, it looks like your video card is out of memory. I don't think there's anything we can do to address that. I'm closing for now assuming that that's what's going on, but if you're sure that's not the case, and can provide a repro, I'll reopen.

**Closed by nornagon** 2019-12-13 19:37 UTC

**Comment by zacard-orc** [comment] 2020-01-14 09:21
i have the same problem....

**Comment by imaginezz** [comment] 2020-02-27 12:10
I have the same problem in a machine running windows 7, but I can't reproduce the issue on other machines.

**Comment by vincent-yan** [comment] 2020-06-08 03:22
app.disableHardwareAcceleration()    can fixed this problem
