### ISSUE TITLE
tensorflow/tfjs-node causes Node-GYP Dynamic Dependency error

### ISSUE THREAD

**Issue by Nuzzlet** [electron/electron#26790] opened 2020-12-02 07:38 UTC
### Issue Details

Electrion Versino: 9.3.5
Windows 10 20H2

### Expected Behavior

Requiring @tensorflow/tfjs-node would work.

### Actual Behavior

devtools console shows:

`Uncaught Error: Cannot find module 'G:\PROGRAMMING\tapeAI\node_modules\@tensorflow\tfjs-node\package.json'
    at webpackEmptyContext (eval at ./node_modules/@tensorflow/tfjs-node/node_modules/node-pre-gyp/lib sync recursive (app.js:1065), <anonymous>:2:10)
    at Object.exports.find (webpack-internal:///./node_modules/@tensorflow/tfjs-node/node_modules/node-pre-gyp/lib/pre-binding.js:20)
    at Object.eval (webpack-internal:///./node_modules/@tensorflow/tfjs-node/dist/index.js:44)
    at eval (webpack-internal:///./node_modules/@tensorflow/tfjs-node/dist/index.js:80)
    at Object../node_modules/@tensorflow/tfjs-node/dist/index.js (vendor.js:1029)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (webpack-internal:///./src/boot/ai.js:39)
    at Module../src/boot/ai.js (app.js:1180)
    at __webpack_require__ (app.js:854)`

and

`client?db9c:126 [WDS] Warnings while compiling.
warnings @ client?db9c:126
eval @ socket.js?43d9:47
sock.onmessage @ SockJSClient.js?3dfd:67
EventTarget.dispatchEvent @ sockjs.js?b1aa:170
eval @ sockjs.js?b1aa:888
SockJS._transportMessage @ sockjs.js?b1aa:886
EventEmitter.emit @ sockjs.js?b1aa:86
WebSocketTransport.ws.onmessage @ sockjs.js?b1aa:2962
client?db9c:135 ./node_modules/@tensorflow/tfjs-node/dist/index.js 58:15-35
Critical dependency: the request of a dependency is an expression
warnings @ client?db9c:135
eval @ socket.js?43d9:47
sock.onmessage @ SockJSClient.js?3dfd:67
EventTarget.dispatchEvent @ sockjs.js?b1aa:170
eval @ sockjs.js?b1aa:888
SockJS._transportMessage @ sockjs.js?b1aa:886
EventEmitter.emit @ sockjs.js?b1aa:86
WebSocketTransport.ws.onmessage @ sockjs.js?b1aa:2962
client?db9c:135 ./node_modules/@tensorflow/tfjs-node/node_modules/node-pre-gyp/lib/pre-binding.js 20:22-48
Critical dependency: the request of a dependency is an expression
warnings @ client?db9c:135
eval @ socket.js?43d9:47
sock.onmessage @ SockJSClient.js?3dfd:67
EventTarget.dispatchEvent @ sockjs.js?b1aa:170
eval @ sockjs.js?b1aa:888
SockJS._transportMessage @ sockjs.js?b1aa:886
EventEmitter.emit @ sockjs.js?b1aa:86
WebSocketTransport.ws.onmessage @ sockjs.js?b1aa:2962
client?db9c:135 ./node_modules/@tensorflow/tfjs-node/node_modules/node-pre-gyp/lib/util/versioning.js 17:20-67
Critical dependency: the request of a dependency is an expression
warnings @ client?db9c:135
eval @ socket.js?43d9:47
sock.onmessage @ SockJSClient.js?3dfd:67
EventTarget.dispatchEvent @ sockjs.js?b1aa:170
eval @ sockjs.js?b1aa:888
SockJS._transportMessage @ sockjs.js?b1aa:886
EventEmitter.emit @ sockjs.js?b1aa:86
WebSocketTransport.ws.onmessage @ sockjs.js?b1aa:2962
client?db9c:135 ./node_modules/@tensorflow/tfjs-node/node_modules/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'npm' in 'G:\PROGRAMMING\tapeAI\node_modules\@tensorflow\tfjs-node\node_modules\node-pre-gyp\lib\util'
warnings @ client?db9c:135
eval @ socket.js?43d9:47
sock.onmessage @ SockJSClient.js?3dfd:67
EventTarget.dispatchEvent @ sockjs.js?b1aa:170
eval @ sockjs.js?b1aa:888
SockJS._transportMessage @ sockjs.js?b1aa:886
EventEmitter.emit @ sockjs.js?b1aa:86
WebSocketTransport.ws.onmessage @ sockjs.js?b1aa:2962
client?db9c:135 ./node_modules/@tensorflow/tfjs-node/node_modules/node-pre-gyp/lib/util/nw-pre-gyp/index.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>
warnings @ client?db9c:135
eval @ socket.js?43d9:47
sock.onmessage @ SockJSClient.js?3dfd:67
EventTarget.dispatchEvent @ sockjs.js?b1aa:170
eval @ sockjs.js?b1aa:888
SockJS._transportMessage @ sockjs.js?b1aa:886
EventEmitter.emit @ sockjs.js?b1aa:86
WebSocketTransport.ws.onmessage @ sockjs.js?b1aa:2962
client?db9c:135 ./node_modules/node-gyp/lib/Find-VisualStudio.cs 9:6
Module parse failed: Unexpected token (9:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // This script needs to be compatible with PowerShell v2 to run on Windows 2008R2 and Windows 7.
| 
> using System;
| using System.Text;
| using System.Runtime.InteropServices;`

### To Reproduce

Simply install & require the NPM package @tensorflow/tfjs-node in your electron project

****I HAVE Web Security Disabled (this program is only for internal use)

### Additional Information
Code works fine when requiring plain @tensorflow/tfjs without node.

**Comment by VerteDinde** [comment] 2020-12-02 16:40
Hey @Nuzzlet, thanks for reporting this. Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/needs-repro label for this reason. After you make a test case, please link to it in a follow up comment. Thanks!

**Comment by sofianguy** [comment] 2021-01-05 21:39
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2021-01-05 21:39 UTC
Labels: 9-x-y, blocked/need-repro, platform/windows
