### ISSUE TITLE
`webContents.capturePage` can only capture visible parts

### ISSUE THREAD

**Issue by abnerlee** [electron/electron#8587] opened 2017-02-04 08:07 UTC
from discussions in #7378

* Electron version: 1.0.2
* Operating system: 10.12

I tried `webContents.capturePage`, but it can only capture the "visible" part of the page. If the height of your html node is larger than the BrowserWindow (or when there's a scroll bar), the overflow part is not included in the captured image. Is there any way to capture the whole page?

### Expected behavior

`webContents.capturePage` take a snapshot of the whole complete webpage

### Actual behavior

only visible part is captured.

### How to reproduce

```js
            const remote = require('electron').remote;
            const webContents = remote.getCurrentWebContents();

            webContents.capturePage({
                x: 0,
                y: 0,
                width: 1000,
                height: 2000
            }, (img) => {
                remote.require('fs')
                    .writeFile(TEMP_URL, img.toPng());
            });
```

**Comment by li-xinyang** [comment] 2017-02-04 11:29
+1

**Comment by groundwater** [comment] 2017-02-06 19:44
Thanks @abnerlee, we'll take a look.

Possible dup of #8586

**Comment by zeke** [comment] 2017-02-08 19:39
This appears to be a duplicate of https://github.com/electron/electron/issues/8314 -- let's move the discussion there.

**Closed by zeke** 2017-02-08 19:39 UTC
Labels: triage/bug

**Comment by operapreneur** [comment] 2019-03-04 00:47
While the linked issue is helpful I didn't find that it solved the expected behavior:

> webContents.capturePage take a snapshot of the whole complete webpage

In my example, I am opening an offscreen BrowserWindow and enabling the window to be larger than the screen through the following BrowserWindow([options]): `enableLargerThanScreen: true`

Execute Javascript on the webContents to return the `document.body.offsetHeight`

Before executing the capturePage method, resize the BrowserWindow with `win.setContentSize()` using the page's offsetHeight result.

I haven't used this in production but this is returning a complete webpage.

**Comment by AVert** [comment] 2021-11-19 01:00
+1
