### ISSUE TITLE
Crashing the render process with render.process() doesn't work properly

### ISSUE THREAD

**Issue by ClaudiaStefan** [electron/electron#19209] opened 2019-07-11 15:11 UTC
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.6
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 2.0.18

### Expected Behavior
Render process recovers

### Actual Behavior
Render process doesn't recover after the second crash

### To Reproduce
1. Open this test repo: https://github.com/ClaudiaStefan/electron-notification-test
2. Type process.crash() in devtools console and wait for window to recover
3. Type again process.crash() in devtools console

### Test project setup:
**Clone this repository**
git clone https://github.com/ClaudiaStefan/electron-notification-test.git
**Go into the repository**
cd electron-notification-test
**Install dependencies and run the app**
npm install && npm start

### Additional Information
The issue has started in 3.0.0.
In electron 5.0.6 and in 6.0.0-beta.13, when I type process.crash() the first time, the entire process is crashed, not only the render process.

**Comment by miniak** [comment] 2019-10-29 10:26
In Electron 5+, doing this crashes the main process
```
  mainWindow.webContents.on('crashed', (event, killed) => {
    mainWindow.reload();
  });
```

**Comment by miniak** [comment] 2019-10-29 10:29
Duplicate of #19887

**Comment by miniak** [comment] 2019-10-29 10:31
Actually there are 2 issues reported here:
- reloading the page second time makes it crash again.
- since Electron 5, it crashes the main process. This is the same as #19887

**Comment by miniak** [comment] 2019-10-29 11:01
This is a possible workaround for the Electron 5+ issue
```
  mainWindow.webContents.on('crashed', (event, killed) => {
    setImmediate(() => {
      mainWindow.reload();
    })
  });
```

**Comment by miniak** [comment] 2019-10-29 11:02
However since Electron 7+, the renderer keeps crashing repeatedly after reload
```
Received signal 11 SEGV_MAPERR 000000000000
0   libbase.dylib                       0x000000010ca9174f base::debug::CollectStackTrace(void**, unsigned long) + 31
1   libbase.dylib                       0x000000010c71d17b base::debug::StackTrace::StackTrace(unsigned long) + 75
2   libbase.dylib                       0x000000010c71d1cd base::debug::StackTrace::StackTrace(unsigned long) + 29
3   libbase.dylib                       0x000000010c7114c8 base::debug::StackTrace::StackTrace() + 40
4   libbase.dylib                       0x000000010ca915c5 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 1381
5   libsystem_platform.dylib            0x00007fff64cfcb5d _sigtramp + 29
6   ???                                 0x00007ffee3a801e0 0x0 + 140732717859296
7   Electron Framework                  0x00000001183aa397 void base::internal::FunctorTraits<void (*)(), void>::Invoke<void (* const&)()>(void (* const&)()) + 23
8   Electron Framework                  0x00000001183aa35d void base::internal::InvokeHelper<false, void>::MakeItSo<void (* const&)()>(void (* const&)()) + 29
9   Electron Framework                  0x00000001183aa331 void base::internal::Invoker<base::internal::BindState<void (*)()>, void ()>::RunImpl<void (* const&)(), std::__1::tuple<> const&>(void (* const&)(), std::__1::tuple<> const&, std::__1::integer_sequence<unsigned long>) + 33
10  Electron Framework                  0x00000001183aa304 base::internal::Invoker<base::internal::BindState<void (*)()>, void ()>::Run(base::internal::BindStateBase*) + 52
11  Electron Framework                  0x000000011837c6b0 base::RepeatingCallback<void ()>::Run() const & + 64
12  Electron Framework                  0x00000001187b4b11 mate::internal::Invoker<mate::internal::IndicesHolder<> >::DispatchToCallback(base::RepeatingCallback<void ()>) + 65
13  Electron Framework                  0x00000001187b498a mate::internal::Dispatcher<void ()>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 170
14  libv8.dylib                         0x00000001990310bc v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 1132
15  libv8.dylib                         0x0000000198fc5277 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 1463
16  libv8.dylib                         0x0000000198fc35f3 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 835
17  libv8.dylib                         0x0000000198fc301f v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) + 127
18  libv8.dylib                         0x0000000199fd3380 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 64
19  libv8.dylib                         0x0000000199dad6bb Builtins_InterpreterEntryTrampoline + 187
20  libv8.dylib                         0x0000000199da41fa Builtins_JSEntryTrampoline + 90
[end of stack trace]
```

**Comment by hxkuc** [comment] 2020-05-18 07:47
i have this problem too,  ---Render process doesn't recover after the second crash---

**Comment by electron-triage** [comment] 2021-03-08 23:14
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-08 23:14 UTC
Labels: 5-0-x, 6-1-x, 7-0-x, 7-1-x, bug :beetle:, platform/macOS
