### ISSUE TITLE
[Bug]: beforeunload fires for iframes before will-navigate has had a chance to cancel the event

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#29921] opened 2021-06-28 18:25 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.1, 12, 11, 10.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

10.0.0

### Expected Behavior

Canceling `will-navigate` will prevent `beforeunload` from firing in iframes

### Actual Behavior

`beforeunload` fires in iframes before `will-navigate` has a chance to cancel the navigation

### Additional Information

This might be intentional, but wanted to report this. Causing issues in my app.

This worked in 10.0.0, but was changed in 10.0.1.

Not clear from the [release notes](https://github.com/electron/electron/releases/tag/v10.0.1) what could have lead to this. Possibly due to [this refactor](https://github.com/electron/electron/pull/25065)? @MarshallOfSound 

Having trouble published the gist, but here's the code.

1. start main.js
2. put a breakpoint in the will-navigate handler
3. in the devtools, navigate the page to something else (e.g. `location = location.href`)
4. see the `beforeunload`  log in the devtools even before will-navigate has had a chance to cancel the event

main.js:
```
const { app, BrowserWindow } = require('electron');

const {join} = require("path");

(async () => {
  await app.whenReady();
  const win = new BrowserWindow({ webPreferences: { nativeWindowOpen: true }});
  await win.loadFile(join(__dirname, "index.html"));
  win.webContents.openDevTools();

  win.webContents.on("will-navigate", (e) => {
    e.preventDefault(); // put a breakpoint here
  });

  app.on('window-all-closed', function () {
    app.quit()
  });
})();
```

index.html:
```
<!DOCTYPE html>
<html>
  <body>
    <iframe src="./index2.html"></iframe>
  </body>
</html>
```

index2.html:
```
<!DOCTYPE html>
<html>
  <body>
    <script>
      window.onbeforeunload = () => {
        console.log("beforeunload");
      };
      window.onunload = () => {
        console.log("unload");
      };
    </script>
  </body>
</html>
```

**Comment by nornagon** [comment] 2021-06-28 23:02
Isn't `will-navigate` only for the top frame?

**Comment by pushkin-** [comment] 2021-06-28 23:05
yes, but the point is that I'm only navigating the top frame with `location = location.href`. If the top frame navigation is canceled, it's arguable that the iframes shouldn't raise beforeunload.

In any case, I just want to verify if the new behavior is intentional or not, because it used to not work this way.

**Comment by MarshallOfSound** [comment] 2021-06-28 23:24
I'm not sure where you're getting your expected behavior from, the API is documented to run before the navigation in time for you to cancel it.

https://www.electronjs.org/docs/api/web-contents#event-will-navigate

There aren't any documented guarantees (unlike other navigation events) on the timing of this event with regards to other DOM / navigation events.

I understand that what you describe is how it used to work, but I'd point out that relying on undocumented timing behavior is inevitably going to break down the road.

**Comment by pushkin-** [comment] 2021-06-28 23:36
@MarshallOfSound That's fair, and I'm not saying that I expected there to necessarily be guarantees on the order. I just wanted point out the change in case it wasn't intentional, because fixing it will fix an issue for me, but if this is expected / not something Electron wants to enforce/guarantee, I'm fine closing this issue.

**Comment by nornagon** [comment] 2021-06-28 23:37
Looking at https://source.chromium.org/chromium/chromium/src/+/main:content/renderer/render_frame_impl.cc;l=5174;drc=c14f6f4b9c44fe479a8d004576b42723b2a5feb6, it seems like beforeunload is always emitted for the main frame + child frames before `BeginNavigation` is called, so I think this is expected behavior. I'm going to close this out as status/wontfix.

@pushkin- what is the underlying problem you're trying to solve? perhaps there's another way to approach it that would be better supported.

**Closed by nornagon** 2021-06-28 23:37 UTC
Labels: bug :beetle:

**Comment by pushkin-** [comment] 2021-06-29 00:07
@nornagon It's very app-specific. Basically if some iframes get unloaded inappropriately (meaning rather than going through the normal destructions process, someone just navigates away), we throw an error.

We have a `will-navigate` handler that cancels navigations, so someone can't really navigate away anyway in the Electron app (though they could when just accessing the webapp through a browser), but the `beforeunload` event fires and we throw this error even though we're didn't really unload the iframe.

**Comment by nornagon** [comment] 2021-06-29 00:10
@pushkin- do you maybe want the `unload` event as opposed to `beforeunload`? Or, possibly, watch for iframe unloads from the main process via the `WebFrameMain` API?

**Comment by pushkin-** [comment] 2021-06-29 15:23
@nornagon Yeah it does seem like that logic should really be in the `unload` handler instead of the `beforeunload` handler. I'm not sure why it was added there. Thanks

**Comment by jcompagner** [comment] 2023-01-30 13:31
i have a similar problem.. "will-navigate" in the electron main electron part will cancel the navigation
This is a bit annoying because that onbeforeunload does some stuff that doesn't expect that it really will continue..

hooking by default in the "unload" is not really nice. because unload is very unreliable.. you can't really build on that see for examples the docs here:

https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event

Now i don't really know how to fix this, the app inside electron should not be able to show urls directly in electron (we want to reroute that always to new browser windows or very likely even external browsers)
So we can catch that in "will-navigate" problem is that then the app will already have executed its onbeforeuload..
(which kind of sets the app in an unusable state)
