### ISSUE TITLE
Error: Failed to find Electron v3.0.0-beta.3 for linux-arm

### ISSUE THREAD

**Issue by lastmjs** [electron/electron#13745] opened 2018-07-19 22:55 UTC
* Electron Version: v3.0.0-beta.3
* Operating System (Platform and Version): Raspberry Pi Model 3B, 2018-06-27-raspbian-stretch.img
* Last known working Electron version: v2.0.5

**Expected Behavior**

I expect to be able to run this command: `npm install electron@beta` and have the installation complete successfully.

**Actual behavior**

When I run the command: `npm install electron@beta`, I get the following error:
```bash
Downloading tmp-3455-0-electron-v3.0.0-beta.3-linux-arm.zip
Error: GET https://github.com/electron/electron/releases/download/v3.0.0-beta.3/electron-v3.0.0-beta.3-linux-arm.zip returned 404
/home/pi/portal-image/node_modules/electron/install.js:47
  throw err
  ^

Error: Failed to find Electron v3.0.0-beta.3 for linux-arm at https://github.com/electron/electron/releases/download/v3.0.0-beta.3/electron-v3.0.0-beta.3-linux-arm.zip
    at Request.<anonymous> (/home/pi/portal-image/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/home/pi/portal-image/node_modules/request/request.js:1062:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
```

**To Reproduce**

Install a fresh image of Raspbian Stretch (with Desktop) from here: https://www.raspberrypi.org/downloads/raspbian Create an empty directory, then run the following command: `npm install electron@beta`. Make sure to use Node.js version 8.11.3 and npm version 5.6.0

**Comment by nmenke** [comment] 2018-07-20 05:47
Hi lastmjs,

version 3 has removed the support for arm architecture. You should set "npm_config_arch=armv7l" and the install should success.  I don't know why it defaults to "arm" with a raspbian image. But it was the same problem for me.

**Comment by malept** [comment] 2018-07-25 01:42
I'm fixing this in https://github.com/electron-userland/electron-download/pull/77.

**Comment by MarshallOfSound** [comment] 2018-07-26 14:05
In version 3.0 we stopped uploading aliased arm builds.  You can as @nmenke said set your `npm_config_arch` variable to download the correct build of Electron.  @malept is also working on making `electron-download` to this aliasing automatically.

For now though, this is not a bug in `electron` itself, closing out 👍

**Closed by MarshallOfSound** 2018-07-26 14:05 UTC
Labels: bug :beetle:, platform/linux/ubuntu, version/3.0.x

**Comment by lastmjs** [comment] 2018-07-26 17:18
Sorry, I was out of town. Thanks everyone, @nmenke it works.
