### ISSUE TITLE
why can appear such problem？

### ISSUE THREAD

**Issue by longboy** [electron/electron#6501] opened 2016-07-15 06:14 UTC
main.js:
var app = require("app");
var BrowserWindow = require('browser-window');
var mainWindow = null;
app.on('ready', function () {
    mainWindow = new BrowserWindow({
        width: 800,
        height: 700
    });
    mainWindow.loadUrl('file://' + __dirname + '/html/index.html');
    mainWindow.openDevTools();
    mainWindow.on('closed', function(){
        mainWindow = null
    });
});
package.json:
{
  "name": "mclans",
  "version": "1.0.0",
  "description": "Hello world.",
  "main": "app/main.js",
  "dependencies": {
    "electron-prebuilt": "^1.2.7",
    "jquery": "^3.1.0"
  },
  "devDependencies": {
    "electron-prebuilt": "^1.2.7"
  },
  "scripts": {
    "test": "hello",
    "start": "electron ."
  },
  "author": "zhonglc",
  "license": "ISC"
}
when I run npm start。
![0202](https://cloud.githubusercontent.com/assets/6941888/16865317/64e27052-4a96-11e6-9ea6-fb3a9ebca75d.png)

**Comment by enlight** [comment] 2016-07-15 06:30
Dupe of #5517.

**Comment by MarshallOfSound** [comment] 2016-07-15 06:31
As @enlight referenced

**Closed by MarshallOfSound** 2016-07-15 06:31 UTC
