### ISSUE TITLE
process.versions should include boringssl

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#18827] opened 2019-06-16 05:49 UTC
On a similar vein to https://github.com/electron/electron/issues/18826 the `process.versions` object should include the `boringssl` version to allow people to do version checks 👍

**Comment by DeerMichel** [comment] 2019-06-17 17:20
See #18826.

**Comment by jkleinsc** [comment] 2019-06-17 17:45
@DeerMichel this shouldn't be closed until a PR addressing this is merged in.

**Comment by nornagon** [comment] 2019-06-21 18:48
Closing this as a duplicate of #18826.

**Closed by nornagon** 2019-06-21 18:48 UTC
Labels: enhancement :sparkles:, platform/all
