### ISSUE TITLE
No opener using native window.open from an iframe in non-sandbox mode

### ISSUE THREAD

**Issue by AshDevFr** [electron/electron#9533] opened 2017-05-19 16:39 UTC
* Electron version: 1.7.1
* Operating system: MacOS

### Expected behavior

The popup should have `window.opener` set

### Actual behavior

I was using native `window.open` in sandbox mode until this PR was merged : https://github.com/electron/electron/pull/8963

I switched to non-sandbox mode using the version 1.7.1 and what happen is that, if your main app is embedded in an iframe and if it open a new window using `window.open`, the new window won't have `window.opener` set

If I load the same app directly in the main window and not using the iframe, it is working as expected

I am using the code from https://github.com/electron/electron/blob/master/docs/api/window-open.md

### How to reproduce

In the main window load in an iframe your app.

In the app open a popup with `window.open`

The new popup does not have `window.opener` set

**Comment by kevinsawicki** [comment] 2017-05-23 22:03
@AshDevFr are you setting the `nativeWindowOpen` option to `true` on the `BrowserWindow`?

**Comment by kevinsawicki** [comment] 2017-05-24 18:06
@AshDevFr I'm having trouble reproducing this with the following example, can you confirm if it works for you or not?


### index.js

```js
const {app, BrowserWindow} = require('electron')

let mainWindow

app.once('ready', () => {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nativeWindowOpen: true
    }
  })
  mainWindow.webContents.on('new-window', (event, url, frameName, disposition, options, additionalFeatures) => {
    if (frameName === 'modal') {
      // open window as modal
      event.preventDefault()
      Object.assign(options, {
        modal: true,
        parent: mainWindow,
        width: 500,
        height: 500
      })
      event.newGuest = new BrowserWindow(options)
    }
  })
  mainWindow.loadURL(`file://${__dirname}/frame.html`)
})
```

### frame.html

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <iframe src="./index.html"></iframe>
  </body>
</html>
```

### index.html

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <script>
      let modal = window.open('./popup.html', 'modal')
    </script>
  </body>
</html>
```

### popup.html

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <script>
      alert(window.opener.location)
    </script>
  </body>
</html>
```

**Comment by AshDevFr** [comment] 2017-05-24 20:05
@kevinsawicki I was using this:
```
nativeWindowOpen: true,
sandbox: false
```

I was not setting the parent with `parent: mainWindow` because if I do it it link the popup window to the parent position.

I will try your example and let you know if it is working for me.

Thank you

**Comment by kevinsawicki** [comment] 2017-06-12 18:08
>  will try your example and let you know if it is working for me.

@AshDevFr were you able to confirm it is is working for you?

**Comment by codebytere** [comment] 2017-09-27 01:21
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:21 UTC
Labels: fixme/bug, more-information-needed

**Comment by Gvozd** [comment] 2018-07-04 09:42
To correct window.opener, and work facebook(and others) logins

You need use `webPreferences.nativeWindowOpen=true`, and set same `webPreferences.affinity` for mainWindow, and opened windows(hook on `mainWindow.webContents.on('new-window')`)
https://gist.github.com/Gvozd/2cec0c8c510a707854e439fb15c561b0
