### ISSUE TITLE
[Bug]: Unable to register a service worker with custom protocol

### ISSUE THREAD

**Issue by Losses** [electron/electron#33096] opened 2022-02-28 01:53 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22000.493

### What arch are you using?

x64

### Expected Behavior

The service worker should be registered

### Actual Behavior

The script is not registered, with the error:

```
Uncaught (in promise) TypeError: Failed to update a ServiceWorker for scope ('myprotocol://ap/') with script ('myprotocol://ap/sw.js'): An unknown error occurred when fetching the script.
```

### Additional Information

Related code from Chromium:

https://github.com/chromium/chromium/blob/b1afdff06ff5959aabf451c54ad50f7b11bb7466/content/browser/service_worker/service_worker_single_script_update_checker.cc
https://github.com/chromium/chromium/blob/b1afdff06ff5959aabf451c54ad50f7b11bb7466/content/browser/service_worker/service_worker_updated_script_loader.cc
https://github.com/chromium/chromium/blob/b1afdff06ff5959aabf451c54ad50f7b11bb7466/content/browser/service_worker/service_worker_new_script_loader.cc
https://github.com/chromium/chromium/blob/6e8ed70160d0d04c997ae6f39f238cdc73e5304c/content/browser/service_worker/service_worker_register_job.cc

Related Bug Report:
https://github.com/electron/electron/issues/9663

The file could be fetched,
![image](https://user-images.githubusercontent.com/1384036/155912245-372118c7-e081-46e6-8cff-90b6e54115b9.png)
With correct response,
![image](https://user-images.githubusercontent.com/1384036/155912296-eab0fccf-c98d-4b29-9311-b2b22b200765.png)
and content:
![image](https://user-images.githubusercontent.com/1384036/155912339-511184ed-fe5c-457d-81e0-520d95979a6d.png)

**Comment by vladimiry** [comment] 2022-04-11 09:03
Apparently duplicate of #32664.

**Comment by mlaurencin** [comment] 2022-04-19 21:15
Thanks for taking the time to contribute!

As mentioned above, this appears to be a duplicate of https://github.com/electron/electron/issues/32664. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by mlaurencin** 2022-04-19 21:15 UTC
Labels: bug :beetle:
