### ISSUE TITLE
Menu.popup blocks the run/render loop

### ISSUE THREAD

**Issue by aackerman** [electron/electron#1854] opened 2015-06-03 18:24 UTC
Version of Electron: 0.25.1
OS: Window 64bit 8.1

The issue for our specific application presents with animations happening in the background of the application not continuing when a context menu is opened. The expectation is that animations and the run/render loop would continue the same way context menus work in Chrome.

**Comment by Ivshti** [comment] 2015-06-04 11:11
I also have this and can confirm it. Menu.popup, but only on OS X -  blocks the GPU process I think or does something that disallows rendering from happening. The renderer process is still active, it still does stuff, but the window doesn't update visually

**Comment by zcbenz** [comment] 2015-06-09 02:05
`Menu.popup` is desired to be a synchronous function in the main process, so the blocking is expected. We can probably add an asynchronous version.

**Comment by Ivshti** [comment] 2015-06-09 06:09
That doesn't make much sense if the all is showing live data, something animated or a video. In this case it has to be async. Will doing it in the main process workaround the issue?

**Comment by Ivshti** [comment] 2015-06-12 13:59
Confirming again that with 0.27.3, rendering continues just fine under Windows. Is it possible that this is under some form resolved?

**Comment by aackerman** [comment] 2015-08-15 01:02
I think the issue was attempting to run Menu.popup in a renderer window from a remote require. This is definitely not what you should do.

**Comment by Ivshti** [comment] 2015-08-15 05:41
This is not true, the issue is still there even with async IPC. Please do not make assumptions like that. I realize the temptation to clean up Issues, but closing issues like that is a bit extreme.

You may have been confused by the fact that this only happens under OS X, and it doesn't really block the thread, only the rendering itself.

**Comment by Ivshti** [comment] 2015-08-16 09:55
Should we just open another issue? As I said, the issue for me is not related to **blocking the main thread**, but instead stops rendering, only under OS X. @zcbenz what do you think we should do?

**Comment by zcbenz** [comment] 2015-08-21 00:51
I think we can reopen this issue and add OS X label.

**Comment by sstur** [comment] 2015-08-26 09:04
Is there an async version of `Menu.popup` that doesn't block rendering? If so can we make it the default context menu used for right-click events? It causes UI issues that when a user right-clicks the UI freezes. It causes issues in the tree-view around selected nodes. This has been an ongoing issue.

**Comment by Mingling94** [comment] 2015-11-04 21:31
I'm not sure if this is the same issue, but this happens on my Ubuntu 15.04 system as well. Right clicking to popup a context menu makes the loading of certain elements, most notably webview processes, to not hang.

Here's a gif (because screen-taping this would have required more effort) of me releasing a right click and how both renderer css icons and webview page loading resumes afterwards:

![](http://im.ezgif.com/tmp/ezgif-946303853.gif)

**Comment by KeitIG** [comment] 2015-12-27 21:15
@Mingling94 do you have a piece of code to show to me ? I'm experiencing the same problem, but the documentation does not help me to find a workaround.

**Comment by Mingling94** [comment] 2015-12-28 17:22
@KeitIG Glad my app helped you! It's basically the same as the documentation except that the renderer sends IPC to the main to bring up a context menu, thus not blocking the renderer. For future viewers of this issue:
In your renderer process:
```js
const ipcRenderer = require('electron').ipcRenderer;
var template = /* Some menu template */

window.addEventListener('contextmenu', function (e) {
	e.preventDefault();
	ipcRenderer.send('context-menu', template);
}, false);
```
Main process:
```js
const electron = require('electron');
const menu = electron.Menu;
const ipcRenderer = electron.ipcRenderer;

MainIPC.on('context-menu', function(event, template) {
 	var contextMenu = menu.buildFromTemplate(template);
 	contextMenu.popup(mainWindow);
 });
```

**Comment by KeitIG** [comment] 2015-12-30 08:27
Thanks @Mingling94, that was what I was looking for, but there's something I don't understand, and I'm sure other people will look for it: how do you return the MenuItem selected to the renderer process, I didn't figure out how to return even a string.

``` javascript
var template = [
    {
        label : 'Add to queue',
        click :  function() {
            // Here, what should I write to return something back to the renderer process
        }
    }
];
```

There should be something like:

```
MainIPC.on('context-menu', function(event, template) {
    var contextMenu = menu.buildFromTemplate(template);
    contextMenu.popup(mainWindow);

    // Here, how do I get the contextMenu action to event.sender.send('contextMenuAnswer', contextMenuResult);
});
```

**Comment by Mingling94** [comment] 2015-12-30 09:19
That's improper use of the Menu module. Even in the main process, you can't get a return value from a `MenuItem` being clicked. Instead, try having the function itself do the thing you're trying to have the click do, as opposed to getting the click function's return value and responding to it.

**Comment by KeitIG** [comment] 2015-12-30 10:27
Ok, that's what I was trying to do first, but I think I may have a problem with Electron: the `click` function is not executed (a console.log output nothing with `enable-logging` flag). I'll investigate with other electron versions.

I will update the issue to help others once I find out what's going wrong.

**Comment by KeitIG** [comment] 2015-12-31 09:13
Ok, if someone is looking for a workaround, here's mine: we can't pass functions with ipc because a `JSON.stringify()` is applied to the `Menu` template we send, so you'll have to declare your menu template in the main process, and use `event.sender.send` on the `click` key. I'm using React btw.

in your main process:
``` javascript
ipcMain.on('artistListContextMenu', (event) => {

    var template = [
        {
            label : 'Add to queue',
            click :  function() {
                event.sender.send('artistListContextMenuReply', 'addToQueue');
            }
        },
        {
            label : 'Play next',
            click :  function() {
                event.sender.send('artistListContextMenuReply', 'playNext');
            }
        }
    ];

    var context = Menu.buildFromTemplate(template);

    context.popup(mainWindow); // Let it appear
});
```

and in my renderer process
``` javascript

showContextMenu() {
    ipcRenderer.send('artistListContextMenu');
}

componentDidMount() {
    ipcRenderer.on('artistListContextMenuReply', (event, reply) => {
        console.log(reply); // Here is your reply from Menu API
    });
}

componentWillUnmount() {
    ipcRenderer.removeAllListeners('artistListContextMenuReply');
}
```

It moves a part of your logic in another place than your app. It's definetly not a best practice, but it works pretty well. An async version of `Menu.popup()` would clean this up.

**Comment by tommoor** [comment] 2016-04-07 21:06
This is a real mess, how high up in priority is an async version of this functionality?

**Comment by KeitIG** [comment] 2016-04-08 07:50
Btw it's not only related to OXS but to all platforms.

**Comment by ssorallen** [comment] 2016-04-08 18:47
@KeitIG, are you sure? When I originally investigated https://github.com/atom/atom/issues/2991 I tried right clicking on atom/tree-view on a Windows machine, and the highlight updated as expeced.

**Comment by asherkin** [comment] 2016-04-08 19:01
I definitely get this on Linux, my context menu being open stops WebGL animating (using requestAnimationFrame).

**Comment by KeitIG** [comment] 2016-04-08 23:53
@ssorallen yes, I have a progress bar in my app that update every 150ms, when the contextMenu was displayed, it was stopping to update, until I dismissed the menu.

And worse, I had an audio playing, on Linux, the audio just paused.

**Comment by pgmlde** [comment] 2016-06-17 11:03
Any news on this?
I have the exact same problem, progress bar and audio. 
It really is a big issue for me.

**Comment by KeitIG** [comment] 2016-06-17 11:32
@pgmlde see my comment for a workaround https://github.com/electron/electron/issues/1854#issuecomment-168154026

**Comment by pgmlde** [comment] 2016-06-17 12:03
Already saw it, unfortunately it's not really an option to declare the context menu in the main process due to the project's code design and the fact that there is not just one menu with two elements. :/

**Comment by r1si** [comment] 2016-08-29 08:51
I have also the same problem....

**Comment by lizprun** [comment] 2016-10-03 09:39
I have also the same problem.
but it seems that slack has resolved this problem... 
how did slack do it ?

**Comment by KeitIG** [comment] 2016-10-03 14:56
@r1si @lizprun You can have a look at my solution here: https://github.com/electron/electron/issues/1854#issuecomment-168154026

Not the easiest to implement, but it does the job pretty well.

**Comment by AoDev** [comment] 2017-01-15 15:14
Hi, I see this issues is more than half a year old. I also face this problem and just wanted to know if there are plans on implementing the async popup in the near future. Depending on the response I would change my strategy and go for an html context menu instead of going native.

**Closed** 2017-02-22 20:50 UTC
Labels: component/menu, fixme/bug

**Comment by pjebs** [comment] 2018-07-26 21:51
https://github.com/electron/electron/issues/13820
