### ISSUE TITLE
Can't disable MenuItem with a role

### ISSUE THREAD

**Issue by jbleuzen** [electron/electron#8843] opened 2017-03-06 14:03 UTC
* Electron version: 1.4.15
* Operating system: OSX 10.12.2

### Expected behavior

MenuItem with role should be disabled when a set a menuItem with `enabled:false`

### Actual behavior

MenuItem with role are not disabled whereas a MenuItem without role is correctly disabled

### How to reproduce

I made a small repo that shows the bug : https://github.com/jbleuzen/electron-menu

If you have any questions... :)

**Comment by kevinsawicki** [comment] 2017-03-06 19:03
I believe this is a duplicate of #5794, please see that issue for more details about this, closing this out.

**Closed by kevinsawicki** 2017-03-06 19:03 UTC

**Comment by jbleuzen** [comment] 2017-03-06 20:02
Sorry didn't find it while I was searching, it is a duplicate :(
