### ISSUE TITLE
ReferenceError: show is not defined :bug:

### ISSUE THREAD

**Issue by binjospookie** [electron/electron#7418] opened 2016-09-29 18:57 UTC
* "electron": "^1.3.4",
* Linux Ubuntu 16.4

When calling `win.hide()` it's OK, but then I'm calling `win.show()` and always app breaks, but sometimes i see that `ReferenceError: show is not defined`.

**Comment by kevinsawicki** [comment] 2016-09-29 21:36
@binjospookie could you provide a minimal example app that reproduces the issue? Thanks.

**Comment by binjospookie** [comment] 2016-09-30 07:45
@kevinsawicki yes, ofcourse. Here it is.

```JS
const electron = require('electron');
const app = electron.app;
const globalShortcut = electron.globalShortcut;
const BrowserWindow = electron.BrowserWindow;
const windowStateKeeper = require('electron-window-state');
const {
    ipcMain
} = require('electron');
const ipc = require('electron').ipcMain;
const dialog = require('electron').dialog;
const {
    Menu
} = require('electron');
const appMenu = require('./scripts/appMenu');
const {
    clipboard,
    Tray
} = require('electron');
let tray = null;
let appWindow;

app.on('ready', () => {
    createWindow();

    const template = appMenu(app, appWindow);
    const menu = Menu.buildFromTemplate(template);

    Menu.setApplicationMenu(menu);

    tray = new Tray('./icon.png')
    const contextMenu = Menu.buildFromTemplate([{
        label: 'New',
        click() {
					dialog.showMessageBox(newShotDialog, function(index) {
							if (index === 0) {
                              app.relaunch();
                              app.exit(0);
							}
					})
        }
    }, {
        label: 'Open',
				click() {
					  // here
						appWindow.show();
				}
    }, {
        label: 'Quit',
				click() {
						globalShortcut.unregisterAll();
						if (process.platform !== 'darwin') {
				        app.quit()
				    }
				}
    }])

    tray.setToolTip('some');
    tray.setContextMenu(contextMenu);

});

app.on('will-quit', () => {
    globalShortcut.unregisterAll();
});


app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
        app.quit()
    }
});

function createWindow() {
    appWindow = new BrowserWindow({
        width: 0,
        height: 0,
        icon: __dirname + '/icon.png'
    });
    appWindow.loadURL(`file://${__dirname}/index.html`);
    appWindow.on('closed', function() {
        appWindow = null;
    });
    appWindow.on('minimize',function(event){
        event.preventDefault();
        // it's ok
        appWindow.hide();
    });
    appWindow.setAutoHideMenuBar(false);
}
```

**Comment by kevinsawicki** [comment] 2016-09-30 17:26
@binjospookie what are you doing in your app when you see the error?

**Comment by binjospookie** [comment] 2016-09-30 17:47
@kevinsawicki I turn(hide) my app an then call tray-menu and click "open".

**Comment by kevinsawicki** [comment] 2016-09-30 18:08
@binjospookie are you able to provide the line number of where the error is occurring?

**Comment by binjospookie** [comment] 2016-09-30 18:33
@kevinsawicki 45.

**Comment by kevinsawicki** [comment] 2016-09-30 18:37
> 45.

Can you verify that `appWindow` is not null when your menu click handler runs?

**Comment by binjospookie** [comment] 2016-09-30 18:49
<img src="http://shots.binjo.ru/saved/138832221457eeb36fa27d31.20721483.png" />

**Comment by kevinsawicki** [comment] 2016-09-30 18:54
Can you log out `appWindow.show`?

**Comment by kevinsawicki** [comment] 2016-09-30 18:55
Does this only happen when you explicitly close the window instead of minimizing it?

It looks like `appWindow` is nulled out on close so if you ran the tray menu open item afterwards it would not be able to call `show()` since `appWindow` would be `null` then.

**Comment by binjospookie** [comment] 2016-09-30 19:03
<img src="http://shots.binjo.ru/saved/86416190957eeb67474a961.45007881.png" />

On minimize I prevented defaults and call `appWindow.hide()`.

**Comment by kevinsawicki** [comment] 2016-09-30 19:05
> On minimize I prevented defaults and call appWindow.hide().

Can you provide some details steps to reproduce this? Having a little trouble wince the function appears to be there but you are reporting an error when calling it.

**Comment by kevinsawicki** [comment] 2016-10-03 21:14
Closing this out since the show function does appear to be there and this looks like an issue in your specific app and not an Electron core issue.

**Closed by kevinsawicki** 2016-10-03 21:14 UTC
Labels: more-information-needed
