### ISSUE TITLE
Build mac app on windows EPERM error

### ISSUE THREAD

**Issue by LorenzoDelpi** [electron/electron#26765] opened 2020-12-01 18:50 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Electron Version:
4.1.4
Electron Packager Version:
13.1.1
Operating System:
 Windows 10 Pro (1909)

### Expected Behavior
I' am building a app for darwin os on a windows system with the following instruction:
`electron-packager . HyperloopUPV --overwrite --asar --platform=darwin --arch=x64  --prune --out=release`
I expected to create the app with no errors

### Actual Behavior
The folder with the app is created and apparentely there is all. However, the execution is interruppet by the following error:

EPERM: operation not permitted, stat 'C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64\HyperloopUPV.app\Contents\Frameworks\Squirrel.framework\Versions\Current'

It seems is like a permissions error, so i have run with administrator permissions and abilitate symlink, but doesn't work
I ve run it with the DEBUG variable and these are the final statements before the error

` electron-packager Running asar with the options {} +1m
  electron-packager Renaming Electron to HyperloopUPV in C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64\Electron.app\Contents\MacOS +9s
  electron-packager Renaming Electron Helper to HyperloopUPV Helper in C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64\Electron.app\Contents\Frameworks\Electron Helper.app\Contents\MacOS +15ms
  electron-packager Renaming Electron Helper.app to HyperloopUPV Helper.app in C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64\Electron.app\Contents\Frameworks +16ms
  electron-packager Moving C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64 to release\HyperloopUPV-darwin-x64 +16ms
EPERM: operation not permitted, stat 'C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64\HyperloopUPV.app\Contents\Frameworks\Squirrel.framework\Versions\Current'`

### To Reproduce
I ve tried in a pc with mac and it works perfectly, so the prolem mus t be in my pc, updating electron-packager to latest version doesn't work to

**Comment by VerteDinde** [comment] 2020-12-02 16:28
Hey @LorenzoDelpi! It looks like you're using a pretty old version of Electron - we're currently supporting Electron 9 through Electron 11. Electron 4 is at EOL.

I'm going to close this issue because this version is no supported, but if you're able to reproduce this issue with the newer version of Electron, please feel free to open a new issue.

Additionally, if you think the issue is more related to your setup than Electron itself, please feel free to join our Discord and get more direct help there!: https://discord.gg/electron

**Closed by VerteDinde** 2020-12-02 16:28 UTC
