### ISSUE TITLE
[Bug]: sockjs closed after 2-5 minutes only in electron v13.x.y and higher

### ISSUE THREAD

**Issue by songming43** [electron/electron#33753] opened 2022-04-13 07:09 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.1

### What operating system are you using?

Windows

### Operating System Version

windows10 

### What arch are you using?

x64

### Expected Behavior

1. i use stompjs and sockjs-client to connect to the server.
2. i expected the sockjs will not close  

### Actual Behavior

1. the sockjs will close only in v13.x.y and higher, but acts normal in lower version, like v5.0.2, v8.5.5, v7.3.3. 

### Additional Information

sockjs-client:  v1.6.0
stompjs: v2.3.3

**Comment by codebytere** [comment] 2022-04-13 12:56
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed** 2022-04-23 07:32 UTC
Labels: bug :beetle:, blocked/need-repro
