### ISSUE TITLE
[Bug]: Browser window can't get dragged after resizing on MacOS M1 machine

### ISSUE THREAD

**Issue by dmermigkas** [electron/electron#30713] opened 2021-08-26 12:57 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.2.1

### What operating system are you using?

macOS

### Operating System Version

MacOS Big Sur

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

After resizing the browser window, app should be draggable from point (x1,y1) to point (x2,y2).

### Actual Behavior

Browser window gets dragged to point (x2,y2) but on drag end event, the browser windows reverts to the initial position (x1,y1).

**Comment by rmraya** [comment] 2021-09-03 08:56
Can't reproduce with Electron 13.3.0 or 14.0.0 on a Mac with Apple M1 chip running macOS 11.5.2

BrowserWindow can be resized and dragged without issues.

**Comment by dmermigkas** [comment] 2021-09-28 12:02
Looks like it is fixed in the newer 15.0.0 version. Thanks

**Comment by VerteDinde** [comment] 2021-10-04 18:17
Closing this since the original poster mentioned it's fixed in 15.x 🙂

**Closed by VerteDinde** 2021-10-04 18:17 UTC
Labels: bug :beetle:, blocked/need-repro
