### ISSUE TITLE
multi-level menu for tray loading too slow

### ISSUE THREAD

**Issue by orangeChu** [electron/electron#16413] opened 2019-01-16 00:52 UTC
* Electron version: 4.0.x
* Operating system: Windows 7 & macOS 10.14.2

**Expected Behavior**
The tray menu displays the same speed as normal.

**Actual behavior**
Windows 7:
It took almost a second to show up.
Almost impossible to display when the number of menus increases.
macOS 10.14.2:
No difference from the normal menu. There is no problem.

**To Reproduce**
[multi-level-menu-for-tray](https://github.com/orangeChu/multi-level-menu-for-tray.git)
[link issue#16156](https://github.com/electron/electron/issues/16156)

Also you can run with the following commands:
```sh
$ git clone https://github.com/orangeChu/multi-level-menu-for-tray.git
$ cd multi-level-menu-for-tray
$ npm install
$ npm start || electron .
```
![screen](https://user-images.githubusercontent.com/25950247/51219452-f7bc0400-196b-11e9-866f-9d5e91b06bc1.gif)

**Comment by codebytere** [comment] 2019-01-16 22:14
Closing as duplicate of https://github.com/electron/electron/issues/16156.

**Closed by codebytere** 2019-01-16 22:14 UTC
