### ISSUE TITLE
Compile without used features?

### ISSUE THREAD

**Issue by trusktr** [electron/electron#10140] opened 2017-07-27 19:08 UTC
Is there a way to compile Electron without all the stuff that isn't used?

Suppose my app never creates a canvas 2D context, and it never creates a <video> element.

Is there a way to build my app so that those features are not included knowing they will never be used?

If not, this is a feature request for that.

**Comment by enlight** [comment] 2017-07-28 01:50
Dupe of #4961.

**Closed by enlight** 2017-07-28 01:50 UTC
