### ISSUE TITLE
Is it possible to get main screen on OS X?

### ISSUE THREAD

**Issue by octref** [electron/electron#6670] opened 2016-07-31 22:59 UTC
Like using `[NSScreen mainScreen]`, main screen being the screen that contains the active window.

A very common use-case is to start an app on the main screen centered, instead of on primary screen.

Also, it would be awesome if you can add an option to start app on an external screen centered, instead of hard-coding x and y as I see in this example:

```js
app.on('ready', () => {
  let displays = electron.screen.getAllDisplays()
  let externalDisplay = displays.find((display) => {
    return display.bounds.x !== 0 || display.bounds.y !== 0
  })

  if (externalDisplay) {
    win = new BrowserWindow({
      x: externalDisplay.bounds.x + 50,
      y: externalDisplay.bounds.y + 50
    })
    win.loadURL('https://github.com')
  }
})
```

**Comment by zcbenz** [comment] 2016-08-01 00:44
This is a duplicate of #1836.

**Closed by zcbenz** 2016-08-01 00:44 UTC

**Comment by octref** [comment] 2016-08-01 02:31
@zcbenz 
OK. Sorry didn't find that issue while searching.
Any plan for this feature?

**Comment by zcbenz** [comment] 2016-08-01 03:01
I don't have a plan on it recently.
