### ISSUE TITLE
The values of outerHeight and outerWidth are incorrect

### ISSUE THREAD

**Issue by etiktin** [electron/electron#2952] opened 2015-10-01 16:02 UTC
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/outerHeight), the outer dimensions are supposed to be equal to the entire size of the Window (border and everything). This is the example they use:
![firefoxinnervsouterheight2](https://cloud.githubusercontent.com/assets/4381579/10224536/241e7154-6867-11e5-8714-5a29791fd637.png)

So it seems that the outer dimensions should be equal to `win.getSize()`, but that's not what is returned:
![demo](https://cloud.githubusercontent.com/assets/4381579/10226088/4e7a1942-686e-11e5-825f-487d4f62c771.png)
The outer dimensions are 784x561 while the actual window size is 800x600. The difference is the window border/frame size. 

I tested it on Windows 8.1 64 bit with Electron v0.33.3.

**Comment by Tyriar** [comment] 2015-10-22 21:52
Situation on Window 10 64 bit with Electron v0.34.0:

![windows_10](https://cloud.githubusercontent.com/assets/2193314/10679107/398587e8-78cb-11e5-8481-44f147c87c8c.png)

Based on the spec I would expect the following numbers:

```
       [window.innerWidth, window.innerHeight] -> 229x600
       [window.outerWidth, window.outerHeight] -> 786x652
require('remote').getCurrentWindow().getSize() -> 786x652
```

Some observations:

- It looks like `getSize()` is including part of the shadow, maybe somewhere is assuming a Windows 10 border has a large border like Windows 8?
- `window.innerWidth` is reporting 226, not 229.
- `window.outer*` is reporting exactly the rect including the viewport, devtools and menu bar.

**Comment by Tyriar** [comment] 2015-10-22 22:25
And Ubuntu 15.04 on Electron v0.34.0:

![ubuntu_15 04](https://cloud.githubusercontent.com/assets/2193314/10679714/3ad3a00e-78cf-11e5-8965-1a769258b0a7.png)

Some observations:

- WIndows does not seem to use the initial width passed to `new BrowserWindow` for the viewport width.
- The 3 pixels are missing from innerWidth here as well. Moving this to a new issue as it is probably due to a different root cause https://github.com/atom/electron/issues/3182

**Comment by codebytere** [comment] 2017-09-27 01:33
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:33 UTC
Labels: fixme/bug

**Comment by ncfausti** [comment] 2021-12-22 20:28
This is still an issue, Dec. 22, 2021.

Steps to reproduce:
window.resizeTo(800, 600);
window.outerWidth; // 801
