### ISSUE TITLE
Frameless apps don't have taskbar context menu on Windows

### ISSUE THREAD

**Issue by MehediH** [electron/electron#12551] opened 2018-04-06 12:12 UTC
* Electron version: 1.8.4
* Operating system: Windows 10 version 1803

### Expected behavior

Frameless applications without a titlebar should have the context menu (accessible with Shift+Right Click) on the taskbar:

![image](https://user-images.githubusercontent.com/10274434/38420464-b38aa49a-399b-11e8-97b5-83cd10e3de40.png)

### Actual behavior

Due to the lack of the titlebar on frameless applications, this menu does not appear. There also doesn't seem to be any API that would let devs add the context menu while keeping the app frameless. 

Shift + right clicking on frameless apps doesn't show anything and prevents the end user from restoring the window or move the app around when it is off screen (https://github.com/desktop/desktop/issues/2311) 

### How to reproduce

Shift + Right Click on a frameless app on the taskbar

**Comment by felixrieseberg** [comment] 2018-10-08 16:45
Duplicate of https://github.com/electron/electron/issues/12134

**Closed by felixrieseberg** 2018-10-08 16:45 UTC
Labels: bug :beetle:, platform/windows, version/1.8.x, version/3.0.x
