### ISSUE TITLE
Out of Memory when ClientDiscardableSharedMemoryManager  execute AllocateLockedDiscardableSharedMemory

### ISSUE THREAD

**Issue by ape-casear** [electron/electron#25054] opened 2020-08-20 04:59 UTC
### Preflight Checklist
* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  5.0.11
* **Operating System:**
  * Win10  Win7

### Expected Behavior
no crash

### Actual Behavior
crash intermittently

### To Reproduce
very sorry I can offer the way to reproduce.

but. I can offer the crash tracker.

```
Thread 5504 Crashed:
0   KERNELBASE.dll                  0x76edc54f          <unknown>
1   XX.exe                        0x2acdbad           base::`anonymous namespace'::OnNoMemory (memory_win.cc:52)
2   XX.exe                        0x2acdb8b           base::TerminateBecauseOutOfMemory(unsigned int) (memory_win.cc:65)
3   XX.exe                        0x319b1ed           discardable_memory::ClientDiscardableSharedMemoryManager::AllocateLockedDiscardableSharedMemory(unsigned int,int) (client_discardable_shared_memory_manager.cc:374)
4   XX.exe                        0x319af2d           discardable_memory::ClientDiscardableSharedMemoryManager::AllocateLockedDiscardableMemory(unsigned int) (client_discardable_shared_memory_manager.cc:211)
5   XX.exe                        0x2ef5e07           cc::GpuImageDecodeCache::DecodeImageIfNecessary(cc::DrawImage const &,cc::GpuImageDecodeCache::ImageData *,cc::ImageDecodeCache::TaskType) (gpu_image_decode_cache.cc:1459)
6   XX.exe                        0x2ef7844           cc::GpuImageDecodeCache::DecodeImageInTask(cc::DrawImage const &,cc::ImageDecodeCache::TaskType) (gpu_image_decode_cache.cc:1098)
7   XX.exe                        0x2f0c723           cc::GpuImageDecodeTaskImpl::RunOnWorkerThread() (gpu_image_decode_cache.cc:373)
8   XX.exe                        0x45482f1           content::CategorizedWorkerPool::RunTaskInCategoryWithLockAcquired(cc::TaskCategory) (categorized_worker_pool.cc:401)
9   XX.exe                        0x4547d6b           content::CategorizedWorkerPool::RunTaskWithLockAcquired(std::vector<cc::TaskCategory,std::allocator<cc::TaskCategory> > const &) (categorized_worker_pool.cc:379)
10  XX.exe                        0x4547d0b           content::CategorizedWorkerPool::Run(std::vector<cc::TaskCategory,std::allocator<cc::TaskCategory> > const &,base::ConditionVariable *) (categorized_worker_pool.cc:261)
11 XX.exe                        0x454f3a4           content::`anonymous namespace'::CategorizedWorkerPoolThread::Run (categorized_worker_pool.cc:54)
12  XX.exe                        0x2b15b5b           base::SimpleThread::ThreadMain() (simple_thread.cc:80)
13  XX.exe                        0x2b179d6           base::`anonymous namespace'::ThreadFunc (platform_thread_win.cc:97)
```

### Additional Information
My app has a lot of Lottie animations to play.
I try to low down the memory by 'webframe.clearCache' and 'session.clearCache()',  but it seems didn't work; Is there has any way to clear the GPU images cache?

**Comment by ckerr** [comment] 2020-08-20 16:42
Thank you for taking the time to report this issue and helping to make Electron better.

This issue has been marked for closing because support for Electron 5 was [discontinued in February 2020](https://www.electronjs.org/blog/electron-8-0#end-of-support-for-5xy).

If you're still experiencing this issue in the latest version of Electron and would like this issue to remain open, please add a comment specifying the version you're testing with and any other information that a maintainer needs to know to reproduce the issue.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2020-09-01 03:15
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2020-09-01 03:15 UTC
Labels: 5-0-x, blocked/need-info ❌, bug/crash :boom:, platform/windows

**Comment by hxkuc** [comment] 2020-09-22 07:16
many OnNoMemory
