### ISSUE TITLE
capturePage leaking memory

### ISSUE THREAD

**Issue by webfraggle** [electron/electron#4086] opened 2016-01-13 13:51 UTC
I capture the mainWindows screen every 40ms to stream it to another computer. But the memory consumption rises and rises and at about 15 GB it slows down the webpage. 

```javascript
var handleScreenCapture = function(image) {
			image = null;
			setTimeout(screenTick, 40);
	}
	
	var screenTick = function() {
			mainWindow.capturePage({x:0,y:0, width:1920,height:360}, handleScreenCapture);
	}
		
	
	mainWindow.webContents.on('did-finish-load', function() {
		setTimeout(screenTick, 40);
	});
```
Is there a fix for that. Is it possible to garbage collect manually?

Thanks
Christoph

**Comment by zcbenz** [comment] 2016-01-13 14:40
Are you running the code in renderer process or the main process?

**Comment by webfraggle** [comment] 2016-01-13 14:57
i'm running this in the main process. The webpage I want to capture is loaded into the mainWindow.

**Comment by zcbenz** [comment] 2016-01-14 11:25
I can reproduce the leak on OS X.

**Comment by zcbenz** [comment] 2016-04-13 07:28
It turns out there is actually no memory leak, but somehow V8 doesn't do garbage collection even when there is pressure on memory. Before we have a fix for this, you can do the garbage collection manually by appending `--js-flags="--expose_gc"` to command line and call `gc()` in your code.

**Closed** 2016-04-13 09:47 UTC
Labels: bug
