### ISSUE TITLE
autoUpdater.checkForUpdates() doesn't wait for quitAndInstall()

### ISSUE THREAD

**Issue by joelthe1** [electron/electron#8698] opened 2017-02-16 10:04 UTC
* Electron version: 1.4.12
* Operating system: Windows 10

### Expected and Actual behavior
I'm trying to implement the Auto-Update feature in my app which is a simple editor for a niche text format. I'm able to get the application to update using the native autoUpdater APIs as soon as the app starts. However, I want to show a pop-up to the user to either defer the update or continue and restart immediately. Also note, I don't mind the auto-download happening anyway.

The problem is that whenever I call autoUpdater.checkForUpdates(); It automatically downloads, quits, updates and restarts the app. This clearly is not the behavior that is mentioned in the documentation.

### How to reproduce
The code I'm using is given below. It just shows the APIs I'm using. Let me know if I'm missing something. 
https://github.com/Bridgeconn/bib-edit/blob/autoupdate-working/app.js#L92

**Comment by baconface** [comment] 2017-02-16 19:24
What does your `SquirrelSetup.log` file say?

**Comment by joelthe1** [comment] 2017-02-17 08:35
This is the [SquirrelSetup.log](https://drive.google.com/file/d/0B-Z5AUy8MaKEbHJHbkw2eUdfcVU/view?usp=sharing) file.

**Comment by kevinsawicki** [comment] 2017-04-27 22:04
> The problem is that whenever I call autoUpdater.checkForUpdates(); It automatically downloads, quits, updates and restarts the app.

So you are seeing your app restart just by calling `checkForUpdates`?

Are you still experiencing this issue? Is it only on Windows?

**Comment by joelthe1** [comment] 2017-04-28 10:14
Hi! This was happening for me in Windows 10 and I haven't checked it on other platforms.

I'll try again and get back to you in a couple of days to see if I can still reproduce the issue.

**Comment by zcbenz** [comment] 2017-06-06 07:49
Closing until more information is provided, also a minimal app to reproduce would be very helpful, since the problem is very likely to be some other bugs in your app.

**Closed by zcbenz** 2017-06-06 07:49 UTC
Labels: component/auto-updater, more-information-needed, platform/windows

**Comment by joelthe1** [comment] 2017-06-07 08:05
I've updated my Node version to 7.4.0 and Electron to 1.6.10 But the problem persists.

[Here](https://github.com/Bridgeconn/autographa-lite/blob/autoupdate-working/app.js#L92) is the point in my code where I'm calling the checkForUpdates() function.
