### ISSUE TITLE
BrowserWindow initially opened with show: false can never open popups

### ISSUE THREAD

**Issue by pedromcunha** [electron/electron#6729] opened 2016-08-04 13:56 UTC
* Electron version: 1.3.2
* Operating system: Mac osx (El Capitan 10.11.5)

I have an electron app which was working perfectly until I decided to make a splash screen. I would show the splash screen (which is just a different browser window) and in the background load my app. When the window reports 'did-finish-load' I would then call window.show on the application's BrowserWindow.

I then noticed that anytime the BrowserWindow attempted to open a popup they would not open. I suspect this is a security feature so that hidden BrowserWindows are prevented from opening other windows. I found a workaround but thought it would be important to report this.

The workaround was to initialize the app's BrowserWindow with show: true and then hide it after initializing it (via the win.hide functionality). Now when I call win.show the popups work as usual.

**Comment by zcbenz** [comment] 2016-08-05 07:42
The popup windows inherit the parent window's options, so if the parent window is hidden the popup windows are hidden by default. This behavior is for the apps that run tasks in background like `nightmare`.

I'm closing this since it is expected behavior.

**Closed by zcbenz** 2016-08-05 07:42 UTC
