### ISSUE TITLE
[Bug]: Subsequent invocations of system dialog not shown in front of parent window

### ISSUE THREAD

**Issue by craxal** [electron/electron#35846] opened 2022-09-28 00:17 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

Ubuntu has this feature where system dialogs don't automatically block the parent window, but rather a system notification pops up, and clicking it shows the dialog. Granted, this is an odd feature, but so it is.

In an Electron application, I would expect any modal dialog to appear in front of the parent window.

### Actual Behavior

If some action in the renderer process triggers a system dialog to open, the first time around, no system notification appears, and the system dialog is shown in front of the parent window. This is expected.

The second time the renderer process triggers the system dialog, it appears _behind_ the parent window, and a system notification is shown.

### Testcase Gist URL

https://gist.github.com/5bddfcc720ac5e52c3940b549c734c32

**Comment by VerteDinde** [comment] 2022-09-28 01:34
@craxal Thanks for reporting this! Sorry, I don't have access to Ubuntu this week, or I'd check myself - is it possible to confirm whether this is also happening in versions of Electron older than 21.0.0? You can do this by downloading [Electron Fiddle (link here)](https://www.electronjs.org/fiddle), loading your gist, and selecting an older version (i.e., 20.0.0). This will just help us bisect where this broke and determine if it's a recent regression. 🙇‍♀️

**Comment by Prinzhorn** [comment] 2022-09-28 06:19
https://github.com/electron/electron/issues/32857

**Comment by codebytere** [comment] 2022-09-28 08:32
Duplicate of https://github.com/electron/electron/issues/32857

**Closed by codebytere** 2022-09-28 08:32 UTC
Labels: platform/linux, bug :beetle:, component/BrowserWindow, has-repro-gist, 21-x-y
