### ISSUE TITLE
[Bug]: The secondary menu of the native menu is not displayed after the window is maximized or the window is restored.

### ISSUE THREAD

**Issue by xb0726** [electron/electron#37467] opened 2023-03-02 00:28 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

&gt;18.3.15

### What operating system are you using?

Ubuntu

### Operating System Version

18.04

### What arch are you using?

x64

### Last Known Working Electron version

18.3.15

### Expected Behavior

The secondary menu of the native menu should be able to display normally after the window is maximized or the window is restored

### Actual Behavior

The secondary menu of the native menu is not displayed after the window is maximized or the window is restored.

**Comment by codebytere** [comment] 2023-03-13 21:54
Duplicate of https://github.com/electron/electron/issues/35724

**Closed by codebytere** 2023-03-13 21:54 UTC
Labels: bug :beetle:
