### ISSUE TITLE
[Bug]: showOpenDialog don't act as modal

### ISSUE THREAD

**Issue by dawidgarus** [electron/electron#33351] opened 2022-03-20 10:54 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

Other Linux

### Operating System Version

Linux desktop 5.16.15-arch1-1 #1 SMP PREEMPT Thu, 17 Mar 2022 00:30:09 +0000 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

When passing `BrowserWindow` instance as a first argument to `showOpenDialog`, the dialog should act as modal, that is to block the window and be always on top of it, the same way that `showMessageBox` does it

### Actual Behavior

File selection dialog is opened as separate window completely independent from the `BrowserWindow`

### Additional Information

To reproduce:
```javascript
const { app, BrowserWindow, dialog } = require('electron');

const createWindow = () => {
  const win = new BrowserWindow({
    width: 800,
    height: 600
  });
  dialog.showOpenDialog(win, {});
}

app.whenReady().then(() => {
  createWindow();
});
```

**Comment by codebytere** [comment] 2022-03-21 09:23
Duplicate of https://github.com/electron/electron/issues/32857

**Closed by codebytere** 2022-03-21 09:23 UTC
Labels: bug :beetle:
