### ISSUE TITLE
[Bug]: Media Session API was brocken in v14

### ISSUE THREAD

**Issue by cawa-93** [electron/electron#30934] opened 2021-09-13 20:21 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14

### What operating system are you using?

Windows

### Operating System Version

Випуск	Windows 10 Pro 21H1

### What arch are you using?

x64

### Last Known Working Electron version

13

### Expected Behavior

![зображення](https://user-images.githubusercontent.com/1662812/133150570-89a56f31-bb12-481c-aa55-2a26bbb1802b.png)
Metadata is loaded correctly and displayed in the system widget.
Clicking on media buttons trigger action handlers.

### Actual Behavior

![зображення](https://user-images.githubusercontent.com/1662812/133150483-b2e898ee-d213-4620-b6b4-204d9ab7f3f1.png)
Metadata not displayed in system widget.
Clicking on media buttons doesn't trigger action handlers.

### Testcase Gist URL

https://gist.github.com/7a51c4236a83c4536b6759bf938c69e8

**Comment by Prinzhorn** [comment] 2021-09-14 11:33
Is this the same as #30860 ?

**Comment by cawa-93** [comment] 2021-09-14 11:39
> Is this the same as #30860 ?

Yes, I think

**Comment by erickzhao** [comment] 2021-09-17 00:02
Closing as a duplicate of the above :)

**Closed by erickzhao** 2021-09-17 00:02 UTC
Labels: bug :beetle:
