### ISSUE TITLE
Maximize and restore the window. The window size is larger than the original size

### ISSUE THREAD

**Issue by w602542704** [electron/electron#22678] opened 2020-03-13 07:46 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
 "electron": "^4.2.12",
* **Operating System:**
 Windows 10 home Chinese
  * 
* **Last Known Working Electron version:**
     6.0.0 +
  * 

### Expected Behavior

Reduce the window to the minimum and click to maximize. In the Restore window, the size of the window is the same as the original size, and the window cannot be reduced
### Actual Behavior

Reduce the window to the minimum, and click to maximize it. In the Restore window, the window size is larger than the original size, and the window can be reduced
### To Reproduce

Reduce the vscode editor to the smallest window, click to maximize and restore the window. The size of the window is larger than the original size, and the window can be reduced

### Additional Information
In the borderless windows of windows computers, the minimum window width is 800. Drag it to the place where the minimum window cannot be dragged, that is, the window width is 800. Click our customized maximize button. Does the maximize button change the restore button? Click the restore button. It is found that the window has not been restored. The window width may be 814 instead of 800. You can still drag it to the left. Wechat pin can do it, vscode can't.

**Comment by w602542704** [comment] 2020-03-13 07:57
Strongly protest to ignore this problem, and strongly ask electron to change the problem of "Restore window size inconsistency after maximization", otherwise a large number of experience seeking developers will be lost!

**Comment by aleksey-hoffman** [comment] 2020-03-14 20:41
Duplicate of #22440

**Comment by sofianguy** [comment] 2020-03-20 23:28
Duplicate of #22440. Please follow that issue for updates. Also we are no longer pushing fixes to versions older than 6.1.x per our [supported versions policy](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#currently-supported-versions).

**Closed by sofianguy** 2020-03-20 23:28 UTC
