### ISSUE TITLE
Linux: Double actions when handling `app-command` handlers: `browser-backward` and `browser-forward`

### ISSUE THREAD

**Issue by jwheare** [electron/electron#18322] opened 2019-05-16 11:36 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v5.0.1
* **Operating System:**
  * Ubuntu 19.04

#15441 added support for `app-command` handlers: `browser-backward` and `browser-forward` on Linux.

The docs describe how to make use of these here:
https://github.com/electron/electron/blob/v5.0.1/docs/api/browser-window.md#event-app-command-windows-linux

Our code is very similar here, and has been in place to support windows for years:
https://github.com/irccloud/irccloud-desktop/blob/master/app/main.js#L293-L311

When testing this on Ubuntu 19.04, this results in back and forward actions being triggered twice when using the appropriate mouse buttons.

I wonder if it's necessary to have these handlers on Linux or if they should only be registered on Windows?

My hunch is that the action is already automatically handled, and the handlers just repeat it. If this is the case, the docs should be updated.

An `e.preventDefault()` might also fix the issue but that seems like the wrong fix.

**Comment by jwheare** [comment] 2019-05-16 11:40
cc @SaswatB @MarshallOfSound

**Comment by jwheare** [comment] 2019-05-17 12:44
Just confirmed that `e.preventDefault()` does not prevent this after all

**Comment by electron-triage** [comment] 2020-02-19 19:23
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:15
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:15 UTC
Labels: 5-0-x, blocked/need-info ❌, bug :beetle:, platform/linux

**Comment by jwheare** [comment] 2020-03-01 22:51
I have now tested this on electron 8.0.2 on Linux, and the back/forward mouse buttons are still functioning without binding app-command. The documentation still suggests that binding this event is needed:

https://github.com/electron/electron/blob/v8.0.2/docs/api/browser-window.md#event-app-command-windows-linux

> The following app commands are explicitly supported on Linux: browser-backward / browser-forward

This is by no means a major issue, but just misleading: if the docs are followed, double actions will be registered.

**Comment by hawkeyetwolf** [comment] 2021-04-06 19:18
I worked around this for now by using Piper to reassign the forward/back buttons on my Logitech mouse to "alt+left" and "alt+right" rather than "backward/forward". This focuses the menubar in electron apps, which is annoying and clunky, but less so than double actions.

**Comment by LunNova** [comment] 2021-12-26 01:29
This should be reopened as it is still an issue.

**Comment by Rayrsn** [comment] 2022-01-05 17:32
> This should be reopened as it is still an issue.
> 
> Discord issue caused by this issue: [support.discord.com/hc/en-us/community/posts/1500000622702-Thumb-mouse-button-on-Linux-registers-twice](https://support.discord.com/hc/en-us/community/posts/1500000622702-Thumb-mouse-button-on-Linux-registers-twice)

@LunNova how can i apply your "workaround" with BetterDiscord?

**Comment by LunNova** [comment] 2022-01-06 00:29
Apply the same .diff but to [this file](https://github.com/BetterDiscord/BetterDiscord/blob/f35b82c69e9e19078e4620495547dc647152475d/injector/src/modules/browserwindow.js#L24) and change `win` to `this`.

**Comment by Rayrsn** [comment] 2022-01-06 02:34
I've ended up with this [browserwindow.js](https://gist.github.com/Rayrsn/66676366483042876b274dfe029619d9)
but its not working i dont know what im doing wrong
and im pretty sure im doing the injection correctly ([Instructions](https://github.com/BetterDiscord/BetterDiscord#manual-installation))

**Comment by Inve1951** [comment] 2022-01-07 22:45
> @LunNova how can i apply your "workaround" with BetterDiscord?

Here's a [NavigationFix](https://betterdiscord.app/plugin/NavigationFix) for BD.

**Comment by Rayrsn** [comment] 2022-01-08 13:37
@Inve1951 Thanks brother.

**Comment by LunNova** [comment] 2022-02-06 20:06
Raised https://github.com/electron/electron/issues/32763 since it seems unlikely this will get reopened.

**Comment by lmcarreiro** [comment] 2022-06-17 01:21
@hawkeyetwolf, this workaround with Piper, is it possible to use it with Slack/Discord only, and keep default behavior on other apps? Could you share more details about it or how to do it? Thanks.

**Comment by hawkeyetwolf** [comment] 2022-06-19 02:24
@lmcarreiro, [Piper](https://github.com/libratbag/piper) is a system-wide tool, so I don't think there's a way to limit it to Slack/Discord only, unfortunately. And it only works for the mouse buttons, but in my case, that's all I needed. Here's a [post ](https://itsfoss.com/piper-configure-gaming-mouse-linux/) about configuring Piper.
