### ISSUE TITLE
DOM elements should lose focus after mouse cursor leaves the frameless window

### ISSUE THREAD

**Issue by szymonc** [electron/electron#8947] opened 2017-03-17 10:31 UTC
* Electron version:  1.4 - 1.6 - but most likely happens on all of them
* Operating system: Windows 7/8 

### Expected behavior
In frameless window any dom element should lose focus after mouse cursor leaves the window area.

### Actual behavior
In frameless window any dom element stays focused after mouse cursor  leaves the window area.
![Bug](https://media.giphy.com/media/l4FGtIoBP3w9Uqrv2/giphy.gif)

### How to reproduce
Create div element with on :hover css state that changes its background-color. Place the div close to the frameless window border. Move mouse cursor over the div then move the cursor outside of the window.

**Comment by zcbenz** [comment] 2017-06-14 11:29
This is a duplicate of #611.

**Closed by zcbenz** 2017-06-14 11:29 UTC
