### ISSUE TITLE
v7 shows background color for a sec when clicking the icon 

### ISSUE THREAD

**Issue by JCBsystem** [electron/electron#21066] opened 2019-11-10 14:53 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

* **Electron Version:**
  * 7
* **Operating System:**
  * Mac OS 10.14.6
* **Last Known Working Electron version:**
  * 6

### Expected Behavior
no window background flicker
### Actual Behavior
window background color is shown for a short while before the content is 

### To Reproduce
open and minimize any electron project with version 7 
using the icon the you will see the background color of the frame for a sec before the content is displayed
do the same with v6 and the content will be shown directly 
see the included gif

the first 2 open and close is correct , open/close 3 and 4 is showing the bugg
### Screenshots
![bugg1](https://user-images.githubusercontent.com/31064157/68545843-3e825b00-03d1-11ea-940a-91cf767f4b4c.gif)

**Comment by shahan312** [comment] 2019-11-18 21:20
+1

I can reproduce on electron v7.1.1 on macos 10.15.1

**Comment by shahan312** [comment] 2019-11-18 21:25
Might be a regression of: https://github.com/electron/electron/issues/19858

And related to the following:
https://github.com/electron/electron/pull/20846

There's a white flash on showing the window from a hidden state too, just much shorter.

**Comment by shahan312** [comment] 2019-11-22 15:54
I think this may be related to these too:

https://github.com/electron/electron/issues/21189
https://github.com/electron/electron/pull/21205

**Comment by loc** [comment] 2019-12-17 21:26
Yep, this is a dupe of #21189. Working on it!

**Closed by loc** 2019-12-17 21:26 UTC
Labels: 7-1-x, bug :beetle:, platform/macOS
