### ISSUE TITLE
Default BrowserWindow's backgroundColor is not #FFF

### ISSUE THREAD

**Issue by yuya-oc** [electron/electron#10025] opened 2017-07-16 07:44 UTC
* Electron version: 1.7.4, 1.6.11
* Operating system: Windows 10

### Expected behavior
Default background color is #FFF as described in the documentation. And texts don't have grayscale anti-aliasing.
( `<webview>` also should have #FFF background (NOT CSS background) by default.)

### Actual behavior
BrowserWindow shows different rendering when using `backgroundColor: '#FFF'` in the constructor.

![antialiasing_vs_backgroundcolor](https://user-images.githubusercontent.com/1412057/28245466-57ee60b4-6a42-11e7-9d34-30c59ebbf4f2.png)

### How to reproduce

1. Use `backgroundColor` in BrowserWindow constructor.
2. Load a html.

```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <p>Electron</p>
</body>
</html>
```

As far as reading #6344, the window doesn't have background color when not specifying `backgroundColor`. This might cause other anti-aliasing/blurry-text issues like #8708. When I set `backgroundColor`, I got good anti-aliasing as well as Chrome.

And due to this anti-aliasing behavior, `<webview>` also should have #FFF background (NOT CSS background) by default.

### Possible fixes
I think the problem is that there are two ways to set background color.

- https://github.com/electron/electron/blob/v1.7.4/atom/browser/native_window.cc#L188-L194
- https://github.com/electron/electron/blob/v1.7.4/atom/browser/api/atom_api_window.cc#L87-L93

`native_window.cc` tries to set #FFF by using `SetBackgroundColor()`, but its implementation is different from `atom_api_window.cc`.
And  `atom_api_window.cc` doesn't set #FFF when `backgroundColor` doesn't exist, so the background is not set to #FFF.

Unfortunately I could not imagine a consist way to resolve this.

**Comment by stanleyxu2005** [comment] 2017-07-17 04:06
Are you suggesting user should specify `#fff` when creating a BrowserWindow for the time being?

**Comment by yuya-oc** [comment] 2017-07-17 08:52
Yes. Possibly another color may also be okay (I didn't test). The [documentation](https://github.com/electron/electron/blob/v1.7.4/docs/api/browser-window.md#new-browserwindowoptions) says the default value is `#FFF`, but I got different results.

**Comment by gribunin** [comment] 2018-05-09 14:28
BrowserView also doesn't let to set background color in the constructor and content of BrowserView also has grayscale antialiasing.

**Comment by Lombra** [comment] 2018-08-17 15:09
This finally explains my ancient gripe with unclear text. Confirmed that setting the backgroundColor property on the BrowserWindow options enabled subpixel antialiasing.

Logically the solution should be to actually set the background color to white as per the documentation, or to update the docs to reflect reality. I don't know if there are reasons to go with the latter, but personally I would prefer the former.

**Comment by JieJiSS** [comment] 2018-08-18 01:49
Setting backgroundColor to `#FFF` to enable subpixel antialiasing is quite tricky and confusing, and it's hard for developers to locate the bug.
Hope this could be fixed before the first formal release of 3.0.0

**Comment by blackknifes** [comment] 2018-09-05 09:51
Has anyone try to fix this bug with The Possible fixes?

**Comment by codebytere** [comment] 2018-09-24 05:05
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by blackknifes** [comment] 2018-09-29 08:39
@codebytere The same problem exists still in Electron 3.0.0.

**Comment by burtonator** [comment] 2019-06-01 16:38
If anyone can point me to the source where the default is set (or should be set) I will send a PR

**Comment by sofianguy** [comment] 2019-08-09 23:15
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by stanleyxu2005** [comment] 2019-08-10 15:57
@sofianguy Hi Sofia, the reproduce step is described pretty clear. Isn't it Electron Official's obligation to verify the issue is gone, before closing the issue?

**Comment by c3er** [comment] 2019-08-10 16:11
@stanleyxu2005 I think they just try to close all issues up to a certain version number and hope that the bugs either got away or there is at least no one anymore who is bothered by that issue. ;)

@sofianguy I just reproduced this issue with Electron 6.0.1!

**Comment by stanleyxu2005** [comment] 2019-08-10 16:11
@sofianguy Hi Sofia, the problem still exists in Electron v5!

The reproduce step is described pretty clear. The original author has been kind enough to have even posted some potential solution at source code level. TBH, I have been subscribing this issue already two years. Do you know how annoying to me to see notification about this issue, but it is not any updates on the issue itself, but just somebody has upvoted the problem. 

You can leave it open, or you might say "After further investigation the root cause is in the Chromium core. We have raised an issue to Chromium community." But label it as "blocked/need-info" is not appropriate. It makes me think the Electron Official closes issue without doing any real verification. There is none merged bugfix PR in this thread, isn't it?

**Comment by burtonator** [comment] 2019-08-10 16:52
I think we will need to fix this ourselves.... It's not getting attention by the core contributors for years. We should just start taking notes where it is set and try to submit pr. I just don't know where these variables are set.

**Comment by fadeevab** [comment] 2019-08-10 21:48
Hello! I'm the author of the original Mattermost issue https://github.com/mattermost/desktop/issues/560, which is still open after two years, because the current issue in Electron is still not solved. There are a lot of details as well as here. Nice to see a notification that the issue is blocked and info is needed.

**Comment by MarshallOfSound** [comment] 2019-08-10 22:31
> You can leave it open, or you might say "After further investigation the root cause is in the Chromium core. We have raised an issue to Chromium community." But label it as "blocked/need-info" is not appropriate. It makes me think the Electron Official closes issue without doing any real verification. There is no merged bugfix PR in this thread, isn't it?

@stanleyxu2005 There are over 1200 issues currently open on the Electron repository.  If we assume it takes 10 minutes to verify each issue (which is **incredibly** generous, some issues don't have code samples or even good repro instructions) then it would take around 25 working days of testing, 8 hours a day to verify each individual bug, that is quite simply not realistic.

We have a system where-by old issues that are labelled with an EOL electron versions get a standard message pasted on them by @sofianguy (who does an awful lot of work here so 👏 ) asking the person who raised the issue or anyone interested in the issue to verify that it is in fact still an issue.

We find a large quantity of issues are resolved over time due to architectural changes, chromium upgrades or v8 version bumps and as previously mentioned the Electron team does not have the resources to spend 200 hours verifying all the open bugs.

This is an open source project and we need and ask for help from community members such as yourself with things like this where you can make the maintainers load a little lighter.  Your attitude to this very simple "is this still an issue" request should probably change a bit.

**Comment by stanleyxu2005** [comment] 2019-08-11 03:49
@MarshallOfSound If people open issue for a valid reason, so it deserves a valid reason for closing it. I admit I'm a bit emotional after seeing a pretty clear described issue ([like this](https://github.com/electron/electron/issues/9092)) going to be closed without a valid reason. 

---
> This is an open source project and we need and ask for help from community members such as yourself with things like this where you can make the maintainers load a little lighter. Your attitude to this very simple "is this still an issue" request should probably change a bit.

Now @c3er and I confirmed the issue still exists in v6.0 and @fadeevab has even provided extra information. I'd just kindly to request, please don't close the issue for now. **Once it is closed, people cannot reopen the issue except admin.** This will actually increase the maintainers load.

**Comment by MarshallOfSound** [comment] 2019-08-11 03:59
@stanleyxu2005 

> a pretty clear described issue going to be closed without a valid reason.

The `blocked` label has already been removed indicating a maintainer has seen the response confirming the issue is still present, as the original message stated we aren't going to close issues if a response is received within those 7 days.

> Once it is closed, people cannot reopen the issue except admin. This will actually increase the maintainers load.

We are well aware, this is why we post the 7 days comment before actually mass-closing issues for EOL versions.

> By the way, if original author closes an issue but it is still reproducible. Shall we create a new issue, or how to capture core team's attention to reopen it? Issue like --> this <--

I can't speak for other maintainers but I have a set of issue / notification filters and because that issue was closed **by the original reporter** and not by me or another maintainer it won't appear in the same category as other issues I review the comments for.  Normally I'd re-open issues like that but could you raise a new one for that with detailed information, that issue thread is 95% random comments with different repros so it's not clear if it's all the same issue.  Raising one new issue with a clear repro would probably be more productive than re-opening that old one 👍

Notifications are hard 😆 E.g. This is just from the last few days 🤷‍♂ 
![image](https://user-images.githubusercontent.com/6634592/62829404-9c748c00-bbb1-11e9-83b5-4835ace4c8f6.png)

**Comment by GiovanH** [comment] 2020-10-20 04:33
> So at the moment content of `<webview>` always has grayscale antialiasing no matter what and there is no workaround for it? Looks like a serious bug, is there any estimates when this bug can be fixed?

The webview problem in particular makes this a critical issue, as there is no workaround.

**Comment by electron-triage** [comment] 2021-03-10 21:10
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Closed by electron-triage** 2021-03-10 21:10 UTC
Labels: 6-0-x, 6-1-x, bug :beetle:, platform/windows
