### ISSUE TITLE
Rectangle Passed into CapturePage Only Change Output Size

### ISSUE THREAD

**Issue by li-xinyang** [electron/electron#8586] opened 2017-02-04 03:54 UTC
* Electron version: 1.4
* Operating system: MacOS 10.12

### Expected behavior

The output image area should be the same as the area of the rectangle passed into the `capturePage` method instead of the squeeze the currently visible area of WebContent into the rectangle size.

### Actual behavior

The rectangle object is the output image size instead of the intended capture area. 

Read more detailed info. and screenshots at http://stackoverflow.com/questions/42036126/how-to-capture-entire-webcontent-inside-currentwindow

### How to reproduce

            const remote = require('electron').remote;
            const webContents = remote.getCurrentWebContents();
            webContents.capturePage({
                x: 0,
                y: 0,
                width: 1000,
                height: 2000
            }, (img) => {
                remote.require('fs')
                    .writeFile(TEMP_URL, img.toPng());
            });

![1](https://cloud.githubusercontent.com/assets/3349406/22615515/da19d088-ead0-11e6-864d-9014ccda3ae9.png)

![2](https://cloud.githubusercontent.com/assets/3349406/22615529/1f91c738-ead1-11e6-9861-0ee312d3e32e.png)

**Comment by groundwater** [comment] 2017-02-06 19:43
Thanks for the report @li-xinyang, we will take a look.

**Comment by zeke** [comment] 2017-02-08 19:39
This appears to be a duplicate of https://github.com/electron/electron/issues/8314 -- let's move the discussion there.

**Closed by zeke** 2017-02-08 19:39 UTC
Labels: triage/bug
