### ISSUE TITLE
Throwing in an Electron app executed from the CLI never exits

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#5675] opened 2016-05-24 10:03 UTC
```js
// foo.js
throw new Error('foo');
```

```
❯ electron foo.js
App threw an error when running Error: foo
    at Object.<anonymous> (/Users/sindresorhus/dev/foo.js:1:86)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at loadApplicationPackage (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:252:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:292:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

It never exits. I expected it to exit with code 1.

I'm trying to use an Electron app in a Node.js script using `childProcess.execFile` and it never finishes when an error happens because of this.

-

* Electron version: 1.1.1
* Operating system: 10.11.5

**Comment by zcbenz** [comment] 2016-05-24 23:48
Actually we used to follow Node's behavior that quits the app when there is no listeners to uncaught exception, but the problem is we got LOTS of complaints that their apps just quit after an JavaScript exception, and we finally suppressed this behavior. 

I think current behavior is reasonable for GUI apps and not suitable for CLI apps, but Electron apps are mostly GUI apps and we should use the convention for GUI apps.

**Comment by sindresorhus** [comment] 2016-05-25 03:47
That makes sense actually, I was just expecting different behavior when Electron is spawned. Maybe an environment variable then? Which makes it not open a GUI dialog with the error, but instead logs it to stdout and then exits with the correct exit code. There are many use cases for spawning Electron, from headless testing, to my use-case of testing an Electron module I'm working on.

**Comment by zcbenz** [comment] 2016-05-25 10:37
You can suppress this behavior by adding a listener to `uncaughtException`, when there is a listener to the event the GUI dialog will not show.

**Comment by zcbenz** [comment] 2016-06-01 04:39
Closing since current behavior is expected, and there is a way change that.

**Closed by zcbenz** 2016-06-01 04:39 UTC
Labels: discussion
