### ISSUE TITLE
Window put on second monitor invisible on first

### ISSUE THREAD

**Issue by krainboltgreene** [electron/electron#5323] opened 2016-04-27 23:36 UTC
* Electron version: Latest
* Operating system: Mac OS X

1. Take a single window application.
2. Put the window on a secondary monitor (in my case a mac monitor as primary and macbook monitor as secondary).
3. Close the application.
4. Turn off the monitor.
5. Open the application

You should now have a strange state where the application is working and active and responding, but the window is invisible and impossible to view.

If you close the application, turn on the secondary monitor, and open the application it now exists on the secondary monitor.

Here are two other examples of this: 

  1. https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/973
  2. https://github.com/mawie81/electron-window-state/issues/1

Based on the first one's "fix" I'm betting Electron is storing the window monitor placement but then also not ignoring it when the monitor's index isn't present.

**Comment by zcbenz** [comment] 2016-04-28 08:02
Electron doesn't save the position of window, and I can not reproduce this with the default app.

Can you try if it happens with the default app?

**Comment by zcbenz** [comment] 2016-06-01 04:38
Closing until more information is provided.

**Closed by zcbenz** 2016-06-01 04:38 UTC
Labels: more-information-needed

**Comment by twhitbeck** [comment] 2016-12-20 16:03
Just wanted to say I'm also experiencing this issue.
Windows 10
Hyper 1.0.0 (electron 1.4.5?)

Can't get the window back unless I plug the 2nd monitor back in.
Tried
* Right click task bar and `Cascade windows`
* `alt + space`, `Move` to drag it on screen
* `Shift+right-click` the task bar button, and I don't get the menu which is supposed to contain `Move`

**Comment by twhitbeck** [comment] 2016-12-20 16:05
Wait, I managed to get it back onscreen, I had forgotten the magical incantation:

* Click the window in the task bar to focus the window
* `alt+space`
* `m`
* `down arrow`
* move mouse to bring it on screen.

**Comment by kirashi3** [comment] 2018-04-30 23:05
This issue needs to be re-opened as it still happens when using dual monitors as per 2 apps using Electron's framework linked below. Again, the issue is that if you use an Electron app on a second monitor, close it, then disconnect the second screen, the app will open where the second monitor would be with no user-friendly way to have it moved back to the main display.

meetfranz/franz#911
desktop/desktop#2107
https://github.com/desktop/desktop/blob/master/docs/known-issues.md#window-is-hidden-after-detaching-secondary-monitor---2107

Electron should check via an OS API whether the other monitor still exists, or if the resolution is different, and automagically adjust its' own window size and/or position so the user at least has control over the app without having to band-aid fix it with a keyboard shortcut "solution". I can provide more details if needed; just mention me and I'll reproduce the bug readily.
