### ISSUE TITLE
[Bug]:  Dark mode in Devtools is not working on the latest 16.0.0 - 16.0.8 / 17.0.0

### ISSUE THREAD

**Issue by andmm** [electron/electron#31864] opened 2021-11-16 17:32 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0 - 16.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 7 x64 SP1

### What arch are you using?

x64

### Last Known Working Electron version

15.3.4

### Expected Behavior

Devtools should have a dark mode applied when the settings is set to 'Dark Mode'. 

### Actual Behavior

When switching to dark mode, it displays the message that 'Devtools requires a reload' but when I click on the reload button it does nothing. Restarting the app has no effect as well and stays on the light mode.

This worked fine on the previous 15.3.2 version.

### Additional Information

One thing I noticed, when updating from the last version (15.3.2) the dev tools will show up with dark mode enabled on the first run but on subsequent runs, it reverts back to light mode.

**Comment by ckerr** [comment] 2021-11-16 17:53
Looks like this broke sometime between 16.0.0-beta.3 and 16.0.0-beta.4.

How I tested:

- select version number in electron-fiddle with a stock fiddle
- ctrl-shift-i to open devtools
- click on gear to change settings
- in sidebar, click 'preferences'
- under 'Appearance' setting, change 'Theme' to a new value that is not 'system preference', e.g. if current value is 'dark' or 'system preference', choose 'light'
- ctrl-shift-i to close devtools
- ctrl-shift-r to force reload
- ctrl-shift-i to reopen devtools
- clck gear to change settings again
- in sidebar, click 'preferences' again

Expected: 'Theme' has the same value as set in previous steps.

Actual (16.0.0-beta.3): same as expected

Acutal (16.0.9-beta.4): 'Theme' is now 'System preference' rather than the value set above

**Comment by ckerr** [comment] 2021-11-16 17:54
https://github.com/electron/electron/compare/v16.0.0-beta.3...v16.0.0-beta.4

**Comment by andmm** [comment] 2021-11-16 17:58
Don't know if this is related but on clicking 'reload dev tools' I'm getting this error message sometimes, not always.

![image](https://user-images.githubusercontent.com/4256677/142039730-bf1bdd4a-143f-4ce5-80a1-f4811af2f579.png)

Browser window was created with barebones options (width, heigh, preloadScript).

**Comment by codebytere** [comment] 2021-11-17 11:48
https://github.com/electron/electron/commit/22df8eadbf73c9fd2a6d6ce25534819679cb07de feels like the most likely culprit i'd say

**Comment by andmm** [comment] 2021-12-01 13:08
Still present in the latest 16.0.3 but not on the new 15.3.3.

**Comment by xbb** [comment] 2021-12-01 15:26
Not only the theme but also other settings like "Preserve log" or "Log XMLHttpRequests", they work but the state don't persist

**Comment by andriyasdf** [comment] 2021-12-17 02:53
I was able to reproduce this bug on Windows 10 and confirmed what @ckerr said about the regress happening between 16.0.0.beta3 and 16.0.0.beta4. I was also able to reproduce this bug on Windows 11 using Electron 18.0.0-nightly.20211209. devtools in the Electron Fiddle app itself do retain preferences upon closing and reopening the app.

**Comment by andmm** [comment] 2022-02-03 13:56
This problem still persists on the latest 16.0.8 and the newer 17.0.0. Works fine on the 15.x.y branch.

**Comment by nornagon** [comment] 2022-02-03 20:01
I'd say this is the culprit: https://github.com/electron/electron/pull/31529/commits/7ef4e4d4f0c111e3c0dd534b3e8e28dc58e38383

**Closed** 2022-03-09 01:17 UTC
Labels: component/devtools, bug :beetle:, bug/regression :leftwards_arrow_with_hook:, status/confirmed, 16-x-y
