### ISSUE TITLE
Windows bash installs Linux version

### ISSUE THREAD

**Issue by ameno-** [electron/electron#5597] opened 2016-05-18 23:03 UTC
* Electron version:
Electron 1.1.0
* Operating system:
Windows 10 build Build 1431.rs1

This occurs when running [native Bash through the Windows command line](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/)

`npm install` installs the linux version

![image](https://cloud.githubusercontent.com/assets/2416135/15377610/ee491024-1d2a-11e6-880e-3e1a7bbc90a2.png)

Running the command in a regular CMD windows installs the correct Windows version.

![image](https://cloud.githubusercontent.com/assets/2416135/15377626/1ce204b8-1d2b-11e6-9e6a-cc51a8c9bc0f.png)

**Comment by damieng** [comment] 2016-05-19 02:51
The Windows bash is a complete Linux subsystem, this is to be expected. It is not like Cygwin.

**Comment by zcbenz** [comment] 2016-05-19 04:42
Closing since it is expected behavior.

**Closed by zcbenz** 2016-05-19 04:42 UTC

**Comment by NyxCode** [comment] 2018-08-09 19:02
Well, this might be the expected behaviour, but it's a problem since the WSL can't run graphics under linux. 
I tried
```
electron-forge init test ; cd test
npm install ; npm uninstall electron
set npm_config_platform=win32
npm install electron
unset npm_config_platform
```
but `npm start` failes with 
```

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application

(electron:325): Gtk-WARNING **: cannot open display:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 start: `electron-forge start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/moritz/.npm/_logs/2018-08-09T18_59_35_102Z-debug.log
```
