### ISSUE TITLE
single call of desktopCapturer.getSources() with types set to 'screen' causes OS to stutter

### ISSUE THREAD

**Issue by mviktora** [electron/electron#10222] opened 2017-08-08 18:59 UTC
* Electron version: v1.6.11
* Operating system: MacOS Sierra 10.12.6 (16G29)

### Expected behavior

A call to desktopCapturer.getSources() should not adversely affect the electron process / entire OS.

See the video file attached to this issue: notice the cursor movement after getSources is called.

[getSoucesIssue2.mov.zip](https://github.com/electron/electron/files/1209249/getSoucesIssue2.mov.zip)

The call to desktopCapturer.getSources() with 'types' parameter containing 'screen' causes some performance issue inside the Electron process and subsequently the entire OS is slowed down (mouse cursor movement is not smooth)

### How to reproduce

1. run the stock electron app, such as:

./node_modules/.bin/electron

2. open developers console and run:

window.require('electron').desktopCapturer.getSources({types: ['screen']}, function() {});

From that moment the OS is slowed down until the electron process is killed.

Note: if types is set to 'window' only this issue is not happening.

**Comment by vanessayuenn** [comment] 2017-08-11 17:15
@mviktora I am unable to reproduce this issue. Does this happen when `desktopCapturer.getSources` is called within the renderer instead of from the dev console?

**Comment by mviktora** [comment] 2017-08-17 17:26
I have done some more digging and the issue seems to be hardware configuration related.
I can clearly reproduce this issue every single time on my MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports) that is connected to an LG UltraFine 5K Display (Apple recommended).
However, when my MacBook is not connected to the external display, the issue is not happening.

**Comment by ajmacd** [comment] 2018-01-12 03:26
This has been fixed in `master` with this libchromium content PR:
https://github.com/electron/libchromiumcontent/pull/417

I think this issue can be closed.

**Closed** 2018-01-17 01:54 UTC
Labels: platform/macOS, reviewed, version/1.6.x, waiting/needs-repro
