### ISSUE TITLE
webContents.closeEvent is fired by redirect sub window using window.close()

### ISSUE THREAD

**Issue by RandalTeng** [electron/electron#15558] opened 2018-11-03 05:30 UTC
* Output of `node_modules/.bin/electron --version`: v2.0.13
* Operating System (Platform and Version): Win10
Run with yarn 1.9.4 & node v10.8.0

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): none

### Expected behavior

When call window.close(), it should trigger the webContents close event, and execute the code in executeJavaScript(), end of it, run the callback.

### Actual behavior

Do nothing, just close the subWindow.

### How to reproduce

Open a renderer window with `new BrowserWindow` and load an external url like `https://github.com`,
click a link to redirect a new page, and then, run window.close() win console, finally, you will see this. Otherwise, the callback will be execute if you click the close button in the right-top with Windows OS.

And my code:
``` javascript
function createWindow () {
  /**
   * Initial window options
   */
  mainWindow = new BrowserWindow({
    width: 1180,
    height: 720,
    minWidth: 1180,
    minHeight: 720,
    useContentSize: true,
    webPreferences: {
      webSecurity: false,
      nativeWindowOpen: true
    },
    frame: false
  })

  mainWindow.on('maximize', (e) => {
    mainWindow.webContents.send('resizeWin', 'max')
  })
  mainWindow.on('unmaximize', (e) => {
    mainWindow.webContents.send('resizeWin', 'unmax')
  })

  mainWindow.loadURL(someFlie) // whatever file code just like hello world :-)

  mainWindow.on('closed', () => {
    mainWindow = null
  })
}
app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (mainWindow === null) {
    createWindow()
  }
})

// the subWindow main code:
const subWindow= new BrowserWindow({
    width: 750,
    height: 450,
    resizable: false,
    minimizable: false,
    maximizable: false,
    webPreferences: {
      devTools: true
    }
  })

  subWindow.setMenu(null)
  let url = 'http://github.com' // the external url
  subWindow.loadURL(url)

  const content = subWindow.webContents
  content.on('did-finish-load', () => {
    console.log('loading finish', content.getURL(), content.getUserAgent())
    qqLoginWindow.on('close', (e) => {
      content.executeJavaScript(`
       param = 1; param
      `, false, (res) => {
        console.log('in call', res)
      }).then( (res) => {
        console.log('in then', res)
      }).catch((e) => {
        console.log('error:', e.message)
      })
    })
  })
```

Actually, I'm not sure is this situation can be named 'bugs' or anything, but it's bothering me two days, for my best thanks, if someone can help me :-,

**Comment by RandalTeng** [comment] 2018-11-05 13:30
Forgive of my bad English,
I read the commit comment, but I don't understand, what relation of this PR with my question?

**Comment by MarshallOfSound** [comment] 2018-11-05 13:42
@RandalTeng That PR incorrectly tagged this issue

**Comment by RandalTeng** [comment] 2018-11-05 13:49
Get it, sad message :-(
Anyway, thank you.

**Comment by codebytere** [comment] 2018-11-05 21:40
Sorry, incorrect copy/paste. I corrected the PR a while ago but it looks like the artifact remains. Apologies!

**Comment by RandalTeng** [comment] 2018-11-06 00:48
Never mind, all is fine.

**Comment by sofianguy** [comment] 2019-08-08 23:32
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2019-08-09 22:00
Closing as this seems resolved per https://github.com/electron/electron/issues/15558#issuecomment-436090625.

**Closed by codebytere** 2019-08-09 22:00 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows

**Comment by RandalTeng** [comment] 2019-08-10 02:27
Thanks for the work all of you, apologies for the late reply, I will check it in time.
