### ISSUE TITLE
memory leak in 1.6.7 when using window.open

### ISSUE THREAD

**Issue by lneir** [electron/electron#9191] opened 2017-04-14 02:54 UTC
* Electron version: 1.6.7
* Operating system: Mac OS X 10.10.5 and Windows 8.1

I realize 1.6.7 is still in beta but thought I should report a memory leak I am seeing...  in a simple app that does window.open with every new window opened the memory keeps growing and is never released when the sub-windows get closed.

The demo repo is committed here: https://github.com/lneir/electron-memory-leak

To repo.
1. git clone https://github.com/lneir/electron-memory-leak.git
2. npm i
3. npm run start
4. in the main window click the open window button 5 times.
Notice: the memory goes very high (approx 500 Mbytes) because each sub-window is allocating a big chunk of memory.
5. now close all the open windows.

Result: the memory of the renderer process stays very high
Expected: memory to go back to original before all sub-windows were opened.

Note: This does not happen on electron 1.4.16 but only appears to be a problem in electron 1.6.7.  
Note: Also the problem seems to be related to the having preload enabled

**Comment by kevinsawicki** [comment] 2017-04-27 15:33
> This does not happen on electron 1.4.16 but only appears to be a problem in electron 1.6.7.

Are you not able to reproduce it using 1.6.6?

**Comment by lneir** [comment] 2017-04-27 16:00
yes also happens in 1.6.6.

**Comment by kevinsawicki** [comment] 2017-04-27 16:01
@lneir could you try 1.6.0 as well? If we can narrow it down to a minor version change than it might be related to the chrome 56 upgrade.

**Comment by lneir** [comment] 2017-04-27 16:09
just checked 1.6.0 (on mac) and appears to be fine - no memory growth.

**Comment by kevinsawicki** [comment] 2017-04-27 16:15
> just checked 1.6.0 (on mac) and appears to be fine - no memory growth.

Do you have time to check other releases and see the earliest release that you can reproduce this? Thanks.

**Comment by lneir** [comment] 2017-04-27 16:17
sure, i'l give it a try.

**Comment by lneir** [comment] 2017-04-27 18:47
@kevinsawicki did some more testing...  

1.6.0 to 1.6.3 all appear to be fine and eventually give back memory.
1.6.4 to 1.6.7 all never give up memory, continues to grow.

my test was:
-  window.open from main window.
- close the child window.
- repeat first two steps 5 times.

looking at release notes for 1.6.4, wondering if this change to include remote in sandboxed renderer might be cause: https://github.com/electron/electron/pull/8939

**Comment by kevinsawicki** [comment] 2017-04-27 18:49
> did some more testing...

Thank you so much, really appreciate it 👍 

> looking at release notes for 1.6.4, wondering if this change to include remote in sandboxed renderer might be cause: #8939

/cc @tarruda do you think it might be related?

**Comment by tarruda** [comment] 2017-04-27 19:22
> /cc @tarruda do you think it might be related?

I think it is related, there's probably some code there that prevents a context from being freed when a window is closed. I will try to bisect the issue to confirm if that commit is indeed what caused the bug.

**Comment by tarruda** [comment] 2017-04-27 20:27
I confirm that  @lneir test case isn't reproducible before @e9b955b9ec353817fafb2db21edec8dd5cb8847e, but I believe the actual bug is caused by the remote module and wasn't noticed until now because each non-sandbox has a dedicated process which is killed when the window is closed.

I will continue investigating.

**Comment by tarruda** [comment] 2017-04-27 23:05
Pushed a fix to #9314

**Closed** 2017-05-01 06:49 UTC
Labels: component/sandbox, fixme/bug, fixme/regression, topic/performance, version/1.6.x
