### ISSUE TITLE
[Bug]: Method to get / set the file pointer in the clipboard is invalid

### ISSUE THREAD

**Issue by y489436672** [electron/electron#30487] opened 2021-08-11 04:04 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0-beta.18

### What operating system are you using?

Windows

### Operating System Version

win10 

### What arch are you using?

x64

### Expected Behavior

let rawFilePath  = clipboard.readBuffer('FileNameW').toString('ucs2')
rawFilePath = rawFilePath.replace(new RegExp(String.fromCharCode(0), 'g'), '');
rawFilePath  === ''     false

### Actual Behavior

rawFilePath  === ''     true

**Comment by codebytere** [comment] 2021-08-17 17:44
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by zcbenz** [comment] 2021-08-25 09:14
The `clipboard.readBuffer` API does not support reading arbitrary types, please check https://github.com/electron/electron/issues/9035 and https://github.com/electron/electron/issues/11838 for this topic.

**Closed by zcbenz** 2021-08-25 09:14 UTC
Labels: platform/windows, component/clipboard, bug :beetle:, blocked/need-repro, 14-x-y
