### ISSUE TITLE
When I use sourcemap to debug ts project, chromium only load source files in the project root dir

### ISSUE THREAD

**Issue by raregrass** [electron/electron#6877] opened 2016-08-17 07:15 UTC
* Electron version: 1.3.3
* Operating system: win10

What I do: 

1. Use typescript to compile a react project with sourcemap enabled.
1. Do not use any package tools like webpack or browerify, aka, directly use require() in browser process.
1. Open the electron instance to debug.

What I expect:  

1. The chromium source panel can display tsx files using sourcemaps.

What I get:

1. The source panel can only display the tsx souce files in the root dir, which includes our index.html and main process js file. The components tsx files in some folders do not show up.

What I try:

1. I try to use the inlineSourcemap or set the sourceRoot property, then I get a tsx blank page. What happened?

Please help me, thanks!

**Comment by zcbenz** [comment] 2016-08-17 13:44
This is a duplicate of #2379.

**Closed by zcbenz** 2016-08-17 13:44 UTC
