### ISSUE TITLE
[Bug]: globalShortcut command+Shift+*arrowKey*+s is not working as intended on Mac Ventura 13.0.1

### ISSUE THREAD

**Issue by Evilu** [electron/electron#36915] opened 2023-01-15 15:24 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.2

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.0.1

### What arch are you using?

x64

### Expected Behavior

```
   const leftSave = globalShortcut.register('CommandOrControl+Shift+left+s', () => {
      console.log('CommandOrControl+Shift+left+s was pressed')
    })


    const rightSave = globalShortcut.register('CommandOrControl+Shift+right+s', () => {
      console.log('CommandOrControl+Shift+right+ was pressed')
    })
```

*pressing CommandOrControl+Shift+left+s*
//Expected to print 'CommandOrControl+Shift+left+s was pressed'

*pressing CommandOrControl+Shift+right+s*
//Expected to print 'CommandOrControl+Shift+right+s was pressed'

### Actual Behavior

prints 'CommandOrControl+Shift+left+s was Pressed'
on both cases.

### Additional Information

If you switch the implementation to 
`   const leftSave = globalShortcut.register('CommandOrControl+Shift+left+s', () => {
      console.log('CommandOrControl+Shift+left+s was pressed')
    })

    const rightSave = globalShortcut.register('CommandOrControl+Shift+right+s', () => {
      console.log('CommandOrControl+Shift+right+ was pressed')
    })`

It prints the opposite,Which makes me suspect that in the implementation of 4 keys, when keyboard arrows are involved, the first register is decisive for both.

**Comment by mlaurencin** [comment] 2023-02-08 02:19
As noted in the [Accelerator documentation](https://www.electronjs.org/docs/latest/api/accelerator), an accelerator can only contain a single key code. Left, Right, and S are all key codes, thus your accelerators are both defaulting to 'CommandOrControl+Shift+S' as the system attempts to handle the incorrect input.

Since this is not a bug, I am going to go ahead and close this issue. Should anyone feel this is incorrect, feel free to comment.

**Closed by mlaurencin** 2023-02-08 02:19 UTC
Labels: bug :beetle:
