### ISSUE TITLE
[Bug]: MacOS: Class WebSwapCGLLayer is implemented in two places message

### ISSUE THREAD

**Issue by robertpatrick** [electron/electron#35386] opened 2022-08-19 14:43 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.13

### What operating system are you using?

macOS

### Operating System Version

12.5

### What arch are you using?

x64

### Expected Behavior

My electron app to start up without error messages.

### Actual Behavior

When starting my app in dev mode, I see the following messages to stdout/stderr:

```
objc[5678]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb41afbec8) and /Users/rpatrick/Projects/weblogic-toolkit-ui/electron/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x109a2bce0). One of the two will be used. Which one is undefined.

...

[5683:0819/093431.464284:ERROR:node_bindings.cc(277)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
debug: WebLogic Remote Console stderr: [5684:0819/093431.540705:ERROR:node_bindings.cc(276)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.

...

[5664:0819/093432.740416:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[5664:0819/093432.740457:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[5664:0819/093432.740477:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[5664:0819/093432.740495:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[5664:0819/093432.740513:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
```

### Additional Information

This is happening with my project at https://github.com/oracle/weblogic-toolkit-ui.  This application has been working for a long time and I recently upgraded from electron 17.x to electron 19.x (I tried 20.x but it is failing with a different problem that I will report in a separate bug).

**Comment by oalfroukh** [comment] 2022-08-21 08:13
Hi
Also, I have the same issue with Windows (10 Pro ) and macOS (12.4) on Electron 19.0.13:

macOS ERROR:
```js
objc[67745]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb4b029948) 
and project/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10841ace0). 
One of the two will be used. Which one is undefined.
...
... 
[67740:0821/104555.672005:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[67740:0821/104555.672404:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
.
.
.hundreds of errors
```
Window ERROR:
```js
... 
[36732:0821/103147.787:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
.
.
.hundreds of errors
```

**Comment by codebytere** [comment] 2022-08-22 10:51
Duplicate of https://github.com/electron/electron/issues/33685

**Closed by codebytere** 2022-08-22 10:51 UTC
Labels: bug :beetle:
