### ISSUE TITLE
Add API to set locale of current app

### ISSUE THREAD

**Issue by strille** [electron/electron#5649] opened 2016-05-23 08:23 UTC
I have Swedish as regional setting on a Windows 10 tablet. This means that the soft keyboard will show a , (comma) instead of a . (dot) when it's configured for entering numbers.

So, if an input is set to type "number":

`<input type="number" value="0" step="any" />`

When the input is given focus the soft keyboard appears with 0-9 and , keys. But pressing , doesn't do anything. It works in the desktop version of Chrome (v 50.0.2661.102 m) on the same device, which leads me to believe it's an issue with Electron.
- Electron version: 0.36.10
- Operating system: Windows 10 Home
- Device: Acer Iconia Tab 8

**Comment by felixrieseberg** [comment] 2016-05-23 10:09
I'm wondering if this is really a localization issue. If you have means of doing so (maybe using copy & paste), could you check if you can enter dots?

**Comment by strille** [comment] 2016-05-23 11:30
I can enter dots without problems, yes (by switching from the numeric keyboard layout to the normal keyboard or change to en english numeric keyboard).

**Comment by zcbenz** [comment] 2016-05-24 01:15
Can you print `navigator.language` in console and paste the result?

**Comment by strille** [comment] 2016-05-24 05:59
When running in electron, navigator.language is "en-GB" while in the desktop version of Chrome on the same device it's set to "sv".

**Comment by zcbenz** [comment] 2016-05-24 10:33
It seems to be caused by the wrong locale information, did you ship the `locales` folder in your app?

**Comment by strille** [comment] 2016-05-24 10:40
Yes, the app folder contains a "locales" folder with a lot of locales, including "sv.pak".

**Comment by zcbenz** [comment] 2016-05-24 23:53
Can you open the default app and see if `navigator.language` is still `en-GB`? And can you also have a try of v1.1.x release?

**Comment by strille** [comment] 2016-05-25 05:18
I just tried to run a modified version of [helloworld](https://github.com/hokein/electron-sample-apps/tree/master/helloworld) with electron v1.1.1 with the same result: `navigator.language` is "en-GB", and comma sign doesn't work in input fields with type "number". 

Here's the modified index.html if anyone's interested:

```
<!DOCTYPE html>
<html>
    <body>
        <input type="number" />
        <script type="text/javascript">
           alert(navigator.language);
        </script>
    </body>
</html>

```

**Comment by strille** [comment] 2016-06-09 13:29
It turns out this happens if you have Windows set to English but with a Swedish soft keyboard. By switching Windows to Swedish as well the comma starts working.

It would be nice if Electron allowed you to set Chromium's --lang flag to force Chromium to a specific locale.

**Comment by zcbenz** [comment] 2016-06-09 23:15
@strille Thanks for the follow-up, I'm changing this issue to track allowing custom locales.

**Comment by allenm** [comment] 2016-08-25 07:24
Need this feature too .

**Comment by virror** [comment] 2016-10-12 16:30
Yes, this is annoying. Seems like locale is set to win language instead of the win locale?
Date displays fine in a regular browser, respecting the correct locale.

**Comment by XueWei** [comment] 2017-06-08 01:06
In my application, similar requirement, I need to set electron locale. What progress does about this issue? Has it already implemented setLocale() API? 
I checked document, it seems only has getLocale() API so far. 
Any update?

**Comment by XueWei** [comment] 2017-06-08 01:09
@zcbenz  I need this feature too. Any update on this? Has it implemented ? I checked document, it only has getLocale() so far.

**Comment by motakbiri** [comment] 2017-08-22 10:00
I need the setLocale() API too.

**Comment by fmarzocca** [comment] 2017-12-04 14:10
any news on this feature request?

**Comment by chenerzhang** [comment] 2017-12-08 09:21
I need the setLocale() API too. @zcbenz

**Comment by codebytere** [comment] 2017-12-10 18:43
i've been busy but i'll try and circle back to this this week

**Comment by mohnen** [comment] 2018-01-03 14:49
I would like to upvote this feature.

**Comment by codebytere** [comment] 2018-01-03 16:32
it's in the works

**Comment by ckerr** [comment] 2018-01-24 14:54
I'd like to get a feel for what people are looking for here, is it a way to set the locale at startup similar to Chromium's `--lang` option, or a JavaScript `setLocale()` API so that app developers can add a feature to change locales at runtime?

Asking because it seems like `--lang` would solve the problems being discussed here but `setLocale()` is what's being worked on.

**Comment by virror** [comment] 2018-01-24 15:05
For me it would be a way to set Locale at runtime so the user can change it.

**Comment by ckerr** [comment] 2018-01-24 15:11
@virror (and anyone else), could you describe how the you plan to use `setLocale()` so that I can better understand what you're trying to get working?

**Comment by mohnen** [comment] 2018-01-25 14:13
​My use case is:
- Our app has a UI in en-us only.
- ​Inputs we use in this app are displayed according to locale of the
operating system, e.g. de-de in our case
Which results in an en-us UI, where numeric inputs are displayed in de-de.
For instance "3*,*1415" instead of "3*.*1415"

**Comment by mrobrian** [comment] 2018-02-05 23:06
For me, I have an application that allows the user to choose between English and Spanish, and we use a third party program for video conferencing (launched from within an iframe). That program will pick up on the locale from the browser to offer the correct language, but doesn't allow for it to be set manually. Since our users can change language at any time, we can't choose the correct language when starting up the application.
It would also be nice to have dates and numbers correctly formatted, especially as we start supporting more languages.

**Comment by matthiasg** [comment] 2018-05-15 13:58
this issue was closed but the feature is not included correct ? So at the moment there is no way to change the locale at runtime (maybe with a page refresh) ?

**Comment by codebytere** [comment] 2018-05-16 16:05
@matthiasg it was included, but it's able to be set at runtime not dynamically so i need to fix the docs

**Comment by matthiasg** [comment] 2018-05-17 13:30
@codebytere thanks for the info ... when you say runtime you mean startup time via chrome flags right ? 

Other than that it seems that chrome still displays its embedded controls (such as datetime-local) in en locale anyway , so it won't help me in my use case sadly.

**Comment by buddythumbs** [comment] 2018-05-24 07:28
I am trying to set the language in man.dev.js and using:

```app.commandLine.appendSwitch('--lang=en-GB,en')```

but when I put ```navigator.language```  in console I get ```"en-US"```

**Comment by clausjoergensen** [comment] 2018-08-16 08:58
So I was looking into this today, and the conclusion on this thread is rather ambiguous.

`app.commandLine.appendSwitch('lang', 'de')` should work according to [docs/api/chrome-command-line-switches.md](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md) but it doesn't,

`app.setLocale('de')` isn't supported in Electron v.2.0.6, and there's no versioning info/tags provided in the merged PR #11469. And [docs/api/app](https://electronjs.org/docs/api/app) doesn't list `app.setLocale` at all.

Which is it? And which to use in what version?

**Comment by pookiepew** [comment] 2019-02-16 16:13
Hi! I had a problem getting date picker from HTML <input type="date"> to show DD MM YYYY as we do in Norway. It was set on MM DD YYYY. I changed this with first require add from electron then added `app.commandLine.appendSwitch('lang' 'nb')` nb = Norwegian Bokmål and it fixed the issue. I found that I had to choose NB instead of NO from locale folder in my electron app. Check for your language locale in `your_app\node_modules\electron\dist\locales\your_locale.pak`. As I didn't find NO.pak and found NB.pak this helped me a lot. Also used [https://electronjs.org/docs/api/locales](url) and [https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md](url) as references. Hope this helps somebody out there :)

**Comment by jianzhiyao** [comment] 2019-09-19 06:29
still not woking after merging [https://github.com/electron/electron/pull/11469](https://github.com/electron/electron/pull/11469)
my electron version:6.0.9

**Comment by jianzhiyao** [comment] 2019-09-19 06:42
still not working

**Comment by Slapbox** [comment] 2020-02-12 21:54
For me, it works if you actually set `--lang=de' in the CLI. Setting it with `.appenchSwitch('lang', 'de')` doesn't work for me in `Electron@7.1`. The docs on command line switches have disappeared though, so this may not be supported in 8 and up - I'm not sure.

**Comment by iwiedenm** [comment] 2020-05-16 04:51
This still is not working in `8.3.0` :/

**Comment by mahnunchik** [comment] 2020-05-19 12:34
Any news?

**Comment by alongite** [comment] 2020-06-19 11:27
any news?

**Comment by kastwey** [comment] 2020-06-20 13:29
hi! Any news? I need to develop a multilanguage application and I don't know how to do it.
Thanks!

**Comment by orbitfum** [comment] 2020-08-30 09:16
Looks no news... still can't change it.

**Comment by Achder** [comment] 2020-10-02 08:45
Not working for me either. 
I'm on Electron 10. I tried the following variations:

app.commandLine.appendSwitch('lang', 'en')
app.commandLine.appendSwitch('lang', 'en-US')
app.commandLine.appendSwitch('lang', 'en_US')
app.commandLine.appendSwitch('lang', 'en-US,en')
app.commandLine.appendSwitch('lang', 'en_US,en')

Browser locale is still 'de'.

**Comment by iwiedenm** [comment] 2020-10-02 20:17
Hopefully this can get looked at!

**Closed** 2020-10-28 16:18 UTC
Labels: enhancement :sparkles:, good first issue

**Comment by MBurchard** [comment] 2022-05-05 13:02
I would be very happy if the current solution were reconsidered.  
With modern libraries, it is very easy to change the language of an Electron application during runtime, both for the Electron backend (menus and tray) and for the frontend (renderer).  
With menus, however, the accelerators remain on what Electron has as locale. As far as I know, this can only be switched via the commandline switch `app.commandLine.appendSwitch('lang', 'en')`, which requires a restart.  
Additionally, it would be great if the labels in menus and the tray could not simply be set as text, but an observer mechanism would be implemented (similar to Vue or React). Currently, you have to recreate the entire menu when changing languages. It would be much more efficient if only the labels changed.

**Comment by MBurchard** [comment] 2022-08-05 19:42
@James-Livesey Will this change the menus and accelerators? If so, nice hack 😎
It would be still better, if there is an official API for it.

**Comment by James-Livesey** [comment] 2022-08-05 19:50
I'm not sure if it does, mainly because my app doesn't utilise them at the moment... I doubt it on the basis that emulating a different locale in Chrome DevTools doesn't change the text on context menus/accelerators etc. (or any of Chrome's non-viewport UI), but in any case, it's probably best to implement your own custom context menu items (that can be localised using whatever library you use) youself so that you get full control over it.

I agree, `app.setLocale` seemed nice for the time it was implemented — shame it was removed, but oh well!

**Comment by MBurchard** [comment] 2022-08-05 19:53
Then this workaround is not needed., because the language within the browser window for my electron app can be changed by code easily.  
My electron app does not load external content, so I don't need to change locales for external pages and for my own this is very very simple.  
The only issue are normal browser window menus.

**Comment by James-Livesey** [comment] 2022-08-05 20:00
Yeah fair, if your app doesn't load any external content etc. that you want to translate, it's probably not a useful workaround. Seems that creating custom [`Menu`](https://www.electronjs.org/docs/latest/api/menu)s whose contents are changed to match the locale would probably be the best option in your case; but you'd have to translate all the command names ("back", "forward" etc.) which is a bit of a pain.

**Comment by MBurchard** [comment] 2022-08-05 20:04
yes and also custom menus do not solve the problem that accelerators do not change. So users switching to German do not necessarily know what the English written accelerators  mean...

**Comment by SkrOYC** [comment] 2022-09-15 01:07
> I've found a workaround to this problem! It involves the use of the Chrome DevTools Protocol, which can be used to control many aspects of a `BrowserWindow`, `BrowserView` or `webview`. In this case, you can not only change the locale of the app on-the-fly, but you can also assign different locales to different `webview`s etc. too.
> 
> This solution updates `navigator.language`, the `Accept-Language` header and more, and will even trick sites such as Google into thinking that you're using a different locale.
> 
> Initially, I tried using [`Emulation.setLocaleOverride`](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setLocaleOverride) to override the locale, but DevTools still kept reporting my system locale in `navigator.language`. The same thing happened when trying to use **Sensors** > **Location** > **Locale** to override the locale as a test, so I presume DevTools uses this command to try and change the locale. Bizarre bug indeed.
> 
> However, this is not the only command that can (theoretically) change the locale: [`Emulation.setUserAgentOverride`](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setUserAgentOverride) also lets you change the locale code with its `acceptLanguage` parameter, so long as you provide the mandatory `userAgent` parameter, too. The best bit: unlike `Emulation.setLocaleOverride`, it actually works and the locale correctly changes!
> 
> So, to change the locale, use the following for each `webContents` that exists in your app:
> 
> ```js
> var webContents = ... ; // Such as a `BrowserWindow` or `webview`'s `webContents`
> 
> webContents.debugger.attach(); // You only need to call this once
> 
> // This can be run to change the locale code whenever needed
> webContents.debugger.sendCommand("Emulation.setUserAgentOverride", {
>     userAgent: userAgent, // You could pass it to the main process from the renderer, or use your own
>     acceptLanguage: localeCode
> });
> ```
> 
> > **Note:** `localeCode`'s string value must use `-` instead of `_` for locale codes (such as that shown in `navigator.language`), such as `en_GB`.
> 
> You may want to use `electron.webContents.getAllWebContents()` and iterate over the returned value to change the locale for everything.
> 
> (Wow this problem bugged me for ages until I found this workaround lol)

Hi James, can you tell me where this code goes? I know this may sound like a weird and noob question but I'm having this problem of locales on nativefier and after some hours I found that it was related to electron and the Accepted-Language header. My app displayed the info correctly after I passed the locale using devtools, but obviously I need to fix this for all my future apps.
Is the `electron.webContents.getAllWebContents()` an array?, because I tried this at the end of my main.js:
```javascript
var allWebContents = electron.webContents.getAllWebContents();
for (let i = 0; i < allWebContents.length; i++) {
  allWebContents[i].debugger.attach();
  allWebContents[i].debugger.sendCommand("Emulation.setUserAgentOverride", {
    userAgent:
      "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36", // You could pass it to the main process from the renderer, or use your own
    acceptLanguage:
      "es-CL,es-US;q=0.9,es;q=0.8,en-US;q=0.7,en;q=0.6,es-419;q=0.5",
  });
}
```
...and it didn't work.
****
Thanks in advance!

**Comment by dandeancook** [comment] 2024-01-18 20:33
If it's just for spellcheck, I found this: https://www.electronjs.org/docs/latest/tutorial/spellchecker

**Comment by Slapbox** [comment] 2024-01-19 00:36
This is necessary for testing date/time features as well, if I'm not mistaken. This issue really shouldn't be closed given that (last I checked) the docs outlined features which don't actually work.
