### ISSUE TITLE
BrowserWindow vibrancy in mac os high sierra system have different behavior

### ISSUE THREAD

**Issue by imRainChen** [electron/electron#10808] opened 2017-10-16 07:05 UTC
* Electron version:1.8.1 beta
* Operating system: mac os high sierra

### Expected behavior
system: mac os 10.11.6
![image](https://user-images.githubusercontent.com/13149266/31598921-d866d882-b215-11e7-9c19-78411fcfdd66.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/13149266/31598934-e1781fbc-b215-11e7-8eb1-504a59db8a25.png)

### How to reproduce
This my BrowserWindow config.

```js
const url = require('url')

var config = {
    resizable: true,
    frame: false,
    titleBarStyle: 'hidden-inset',
    fullscreenable: false,
    "vibrancy": "dark"
}

var win = new BrowserWindow(config)
win.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))

```

**Comment by sallar** [comment] 2017-10-18 16:25
@sofianguy @imRainChen this is a duplicate of #10521

**Comment by sofianguy** [comment] 2017-10-18 17:33
@sallar thanks!

@imRainChen 
Thanks for taking the time to contribute!

We noticed that this is a duplicate of [#10521](https://github.com/electron/electron/issues/10521). You may want to subscribe there for updates.

Because we treat our issues list as the team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the [CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by sofianguy** 2017-10-18 17:33 UTC
Labels: platform/macOS, triage/bug, version/1.8.x
