### ISSUE TITLE
crash when attempting to quit while a modal browser window is open

### ISSUE THREAD

**Issue by cbfiddle** [electron/electron#6292] opened 2016-06-29 21:15 UTC
* Electron version: 1.2.5
* Operating system: macOS 10.10.5

If I try to quit my Electron application while a modal browser window is being displayed, the application crashes.
[crash 1.txt](https://github.com/electron/electron/files/340223/crash.1.txt)

**Comment by zcbenz** [comment] 2016-07-01 11:09
Can you provide a minimal app that can reproduce this problem? I'm unable to reproduce with your description.

**Comment by zcbenz** [comment] 2016-08-02 00:46
Closing until more information is provided.

**Closed by zcbenz** 2016-08-02 00:46 UTC
Labels: more-information-needed

**Comment by cbfiddle** [comment] 2016-08-03 21:21
I have an idea about what is happening.

My application has its own handler for the Quit application menu item, because in some cases quitting may require interaction with the user (e.g. to save changes). If there is no issue preventing the application from closing, then it will explicitly close all of the main browser windows (not the modal dialog) and call app.exit(0). My application calls window.close() but does not wait for the window to be closed.

The crash happens when Browser::Exit() calls NativeWindow::CloseContents(). I suspect the crash is caused by a race condition, if the actual closing of the window is asynchronous.

The standard system Quit handler will beep when there is a modal window open, but my Quit handler is allowed to run even when there is a modal window open.
