### ISSUE TITLE
macOS "Emoji & Symbols" popover incorrectly positioned in webview

### ISSUE THREAD

**Issue by kasrak** [electron/electron#7166] opened 2016-09-09 23:03 UTC
* Electron version: 1.3.5
* Operating system: macOS 10.11.6

If you have a text input inside a `<webview>` and you bring up the Emoji and Symbols popover (Ctrl+Cmd+Space), the popover is always positioned at the top left of the window, instead of at the cursor:

<img width="1136" alt="screen shot 2016-09-09 at 3 54 58 pm" src="https://cloud.githubusercontent.com/assets/331454/18405450/eaf70f0e-76a6-11e6-9c3a-184cdba62805.png">

**Comment by zcbenz** [comment] 2016-09-13 06:12
I can reproduce the same bug in Chrome extension's `<webview>` tag by using this extension:
https://chrome.google.com/webstore/detail/browser-sample/edggnmnajhcbhlnpjnogkjpghaikidaa

Can you report this to [Chromium's issues list](https://crbug.com) instead? There is probably already an existing issue on this.

I'm closing this issue since it is an upstream bug, and we are not able to fix it on Electron's side.

**Closed by zcbenz** 2016-09-13 06:12 UTC
Labels: bug, macOS, webview
