### ISSUE TITLE
[Bug]: Devtools theme setting is resetting after you close the app. 

### ISSUE THREAD

**Issue by andmm** [electron/electron#43549] opened 2024-09-04 11:28 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.1

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2

### What arch are you using?

x64

### Last Known Working Electron version

31.*.*

### Expected Behavior

The devtools theme should follow system settings or the user choice. 

### Actual Behavior

In this latest 32.0.1 version, the devtools theme is always light regardless of system preference.  Changing it to dark doesn't appear to save the configuration after you close the app nor using the nativeTheme module solves this issue.

![WindowsTerminal_zvOAO5JZ0K](https://github.com/user-attachments/assets/aee5035f-49ff-46ac-9fce-000b963b6a6b)

**Comment by mlaurencin** [comment] 2024-09-04 16:06
Duplicate of #43367

**Closed by mlaurencin** 2024-09-04 16:06 UTC
Labels: platform/windows, bug :beetle:, 32-x-y

**Comment by andmm** [comment] 2024-09-04 17:07
> Duplicate of #43367

Apologies, apparently didn't search hard enough.
