### ISSUE TITLE
[Bug]: White flickering when switching between BrowserViews on macOS

### ISSUE THREAD

**Issue by XiaoBaiClassmate** [electron/electron#40618] opened 2023-11-27 07:03 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.2

### What operating system are you using?

macOS

### Operating System Version

MacOS Sonoma 14.1.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

27.1.2

### Expected Behavior

1. Launch the Electron application on macOS.
2.Create multiple BrowserViews within the application.
3.Switch between different BrowserViews by programmatically changing the focused BrowserView or using any user interaction that triggers the view switch.
4.Observe the screen during the view switch and notice the white flickering that occurs briefly.

This is the same problem  #37201 

### Actual Behavior

Switch white flicker

### Testcase Gist URL

https://gist.github.com/Imperat/ad54907ca6e8d1167c5bde6a6bf389ac

### Additional Information

No response

**Comment by XiaoBaiClassmate** [comment] 2023-11-27 07:10
Under Windows, it's not as obvious, but it still happens.

**Comment by codebytere** [comment] 2023-11-27 10:59
Duplicate of https://github.com/electron/electron/issues/37201

**Closed by codebytere** 2023-11-27 10:59 UTC
Labels: bug :beetle:

**Comment by XiaoBaiClassmate** [comment] 2023-11-27 11:00
@codebytere Yes, is there a solution now?
