### ISSUE TITLE
XHR requests are getting failed/cancelled

### ISSUE THREAD

**Issue by alirezavalizade** [electron/electron#25195] opened 2020-08-28 17:17 UTC
Hello There,

Recently I updated my current electron version to "^9.1.2" but notice that all the XHR requests are getting cancelled regardless of which api or library you using, I saw some reports in Issues but they were related to "7" beta version. I tried some settings but they didn't work out.
For example:

```
webPreferences: {
    nodeIntegration: true,
    enableRemoteModule: true
    // webSecurity: false
  }
```

Thanks in advance

**Comment by lukeapage** [comment] 2020-08-29 06:09
Are they cors requests? There’s an open issue with disabling web security not working.
You would need to provide details on the type of requests - eg a screenshot from the networks page in DevTools. Then record a network log using netlog in the electron object and load it into https://netlog-viewer.appspot.com/#events to see what the problem is.

**Comment by sofianguy** [comment] 2020-09-01 03:42
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks for understanding and meeting us half way 😀

**Comment by alirezavalizade** [comment] 2020-09-01 10:58
@lucaslopes They're not cors issue, It's the same setup as it was before, But when I upgrade my electron version they're getting failed. I'll prepare the report today. The weird thing is if you disable `webSecurity` then it becomes cors issue.

**Comment by codebytere** [comment] 2020-09-24 02:46
Closing as template request was not addressed.

**Closed by codebytere** 2020-09-24 02:46 UTC
Labels: blocked/need-info ❌
