### ISSUE TITLE
`KeyboardEvent.key` reports an incorrect code on Linux for non-US keyboards when holding `ctrl` down

### ISSUE THREAD

**Issue by as-cii** [electron/electron#8116] opened 2016-12-01 13:22 UTC
**Electron version:** 1.3.9 (but it doesn't work properly on Chrome 54 either)

When receiving `keydown` events on Linux from a non-US keyboard layout, the `.key` property will report an incorrect value if the user also presses <kbd>Ctrl</kbd>. In Atom, we have circumvented this issue by directly accessing the X11 APIs, but some users are [experiencing problems](https://github.com/atom/atom/issues/13170) on operating systems that have GNOME installed. [This codepen](http://codepen.io/anon/pen/aBENLP) illustrates the bug: 

* Create a VM and install Ubuntu on it.
* Install Chrome.
* Add the Colemak US keyboard layout.
* Open the codepen with Google Chrome and toggle the DevTools Console.
* Press <kbd>L</kbd>: notice that the console prints `i`.
* While holding <kbd>Ctrl</kbd>, press <kbd>L</kbd>: notice that the console prints `l`.

Could this be fixed in Electron somehow? Alternatively, can the Electron team submit a patch to Chromium that solves this? Fixing it upstream feels easier than [doing it in a library](https://github.com/atom/keyboard-layout/blob/master/src/keyboard-layout-manager-linux.cc#L81-L132) because we should have direct access to the operating system `KeyPress` events. Thoughts? 💭 

/cc: @groundwater @zcbenz

**Comment by Ben3eeE** [comment] 2016-12-01 13:30
Another report of this where <kbd>Ctrl-UpArrow</kbd> resolves to things like <kbd>Ctrl-katakana</kbd> at  https://discuss.atom.io/t/ctrl-arrow-key-sends-unrelated-combination-to-atom/36405/5

**Comment by kevinsawicki** [comment] 2016-12-01 18:05
Looks like this could be https://bugs.chromium.org/p/chromium/issues/detail?id=633838 and fixed in Chrome 56.

If that is the same issue then the patch for it in https://codereview.chromium.org/2474083002 looks pretty small and probably could be applied against Electron's current Chrome version.

@as-cii would you want this backported to 1.3.x or is Atom moving to 1.4 soon?

**Comment by kevinsawicki** [comment] 2016-12-01 18:19
This does appear to be fixed in Chrome 56, tested on Ubuntu 16.04 with Colemak.

<img width="622" alt="screen shot 2016-12-01 at 10 18 34 am" src="https://cloud.githubusercontent.com/assets/671378/20806404/9924ed64-b7af-11e6-8722-1decd8a5edd4.png">

**Comment by kevinsawicki** [comment] 2016-12-02 20:27
I have a patch for this against Chrome 52 over at https://github.com/electron/libchromiumcontent/compare/control-dom-key-patch-52

With it applied against Electron 1.3.12 I can no longer reproduce the issue on Ubuntu 16.04.

**Comment by as-cii** [comment] 2016-12-05 14:53
Awesome, @kevinsawicki. Thank you so much! Looking forward to seeing this shipped in Electron 1.3.13 and use it in Atom. 💯

**Closed** 2016-12-06 18:36 UTC
Labels: bug, linux
