### ISSUE TITLE
showOpenDialog does not return proper escaped path for Windows

### ISSUE THREAD

**Issue by tHBp** [electron/electron#7023] opened 2016-08-29 17:13 UTC
* Electron version: 1.3.4
* Operating system: Windows 7 x64
 
The **dialog** method `showOpenDialog `returns path as `X:\path\to\file`, while it should return properly escaped path as `X:\\path\\to\\file` for windows platform.

So far, I have not found a workaround yet.

**EDIT**:  There does not seem to be a workaround at Javascript end. Probably the issue is with path returned here (Line _233_, file: _/atom/browser/ui/file_dialog_win.cc_):
```
    hr = CShellFileOpenDialog::GetFileNameFromShellItem(
        item, SIGDN_FILESYSPATH, file_name, MAX_PATH);
```
Any ideas @zcbenz ?

**Comment by enlight** [comment] 2016-08-30 03:01
What are you doing with the filename that breaks things for you?

**Comment by tHBp** [comment] 2016-08-30 05:09
@enlight I'm trying to set user preferences on first screen by asking user about app workspace and other stuff where the content of the app will be stored. Kind of like project directory. But a single `\` works effectively as a escape character. In the example given above, if I try to use `path.join` on the path returned by the `showOpenDialog`, it boils down to `X:path	oile` because of the `\t`.  This is one of the many cases where is path returned cannot be properly used again.

**Comment by enlight** [comment] 2016-08-30 07:05
I've just tried using `path.join()` on a filename returned by `showOpenDialog` and it works as expected, can you provide a minimal code sample that shows the issue?

**Comment by tHBp** [comment] 2016-08-30 08:55
@enlight Yes, sure.
``` 
const {
    app,
    BrowserWindow,
    dialog
} = require('electron');
const fs = require('fs');

var mainWindow = null;

app.on('ready', function() {
    mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        center: true
    });
    dialog.showOpenDialog({
        title: 'Random Title',
        properties: ['openDirectory']
    }, function(pathName) {
        fs.writeFileSync('new.js', pathName, 'utf8');
    });
});
```
The file ```new.js``` has path in the form ```X:\some\path```.

**Comment by enlight** [comment] 2016-08-30 09:24
This is expected behavior. Escaping slashes is usually only necessary in literal strings in your code, however, if you're writing a path out to file and then reading it back in again as a string literal you'll need to escape those slashes yourself before writing the path to disk. Incidentally `JSON.stringify()` will escape slashes for you, so if you write out your settings in JSON format you won't have to bother escaping the slashes yourself.

**Comment by zcbenz** [comment] 2016-08-30 10:43
I'm closing this since it is expected behavior.

**Closed by zcbenz** 2016-08-30 10:43 UTC
Labels: more-information-needed

**Comment by etiennejcharles** [comment] 2017-01-04 20:49
@zcbenz, @enlight : I'm having the same problem, not sure how to resolve it and how it's the expected behavior : Given I have the following path on windows. :

"X:\some\path"

When I use that value in my browser, it's shown as ~

"X:somepath"

Are you saying I should use JSON.stringify to add a double \\ character before sending back the result to my app? i.e JSON.stringify("X:\some\path")?

**Comment by PalokhaO** [comment] 2020-12-14 14:07
I know this issue is closed, but in case someone arrives here for the same reason as @etiennejcharles : The backslashes are **escape characters**, so in order to actually write a backslash in a string literal, you need to escape it with another backslash: "X:\\some\\path"
