### ISSUE TITLE
http/s.request(...) always times out when used with allowRendererProcessReuse=true

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#22791] opened 2020-03-21 14:55 UTC
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.1.1
* **Operating System:** Windows 10 (1709)
* **Last Known Working Electron version:** n/a - relates to new allowRendererProcessReuse flag; works fine without it

### Expected Behavior
I am using Node's http/https modules to ping a site in a renderer process. I expect that I can successfully ping a site like "https://google.com" without timing out when `app.allowRendererProcessReuse` is `true`.

### Actual Behavior
The request always times out.

### To Reproduce

Code below, but the gist is this.

I navigate a window to a page. Then, I navigate the window to another page and ping the site with the http/https modules.

When `allowRendererProcessReuse` is set, the requests always time out.

When I unset the flag, everything works fine.
When I load the second page (that makes the requests) instead of the first, everything works fine.
When I explicitly kill the renderer process from the first navigation, and then do the second navigation, everything works fine.

Something about keeping the old renderer around makes it not work for some reason.

main.ts:
```
import "electron";

function createMainWindow(): void {
	const { BrowserWindow, ipcMain } = require("electron");

	const mainWindow: Electron.BrowserWindow = new BrowserWindow({
		show: true,
		webPreferences: {
			nodeIntegration: true
		}
	});

	mainWindow.loadFile("./firstPage.html"); // Workaround 2: load the secondPage instead of the firstPage

	ipcMain.once("next", () => {
		mainWindow.loadFile("./secondPage.html");
		mainWindow.webContents.openDevTools();
	});
}

export async function main(): Promise<void> {
	const { app } = require("electron");

	app.allowRendererProcessReuse = true; // Workaround 1: comment this out

	app.on("window-all-closed", () => {
		app.quit();
	});

	await app.whenReady();
	createMainWindow();
}

if (require.main === module) {
	main();
}
```

firstPage.html:
```
<!DOCTYPE html>
<html>

<body>
	<button id="acceptButton">Accept</button>
	<script src="./firstPage.ts"></script>
</body>

</html>
```

firstPage.ts:
```
document.getElementById("acceptButton").onclick = () => {
	require("electron").ipcRenderer.send("next");
	// Workaround 3: Do a process.exit() here and await the loadFile(secondPage) navigation. This causes us to create a new renderer process
};
```

secondPage.html:
```
<!DOCTYPE html>
<html>

<body>
	<div id="controlDiv">
		<input id="url" type="url" value="https://google.com" />
		<button id="navigateButton">Navigate</button>
	</div>

	<script src="./secondPage.js"></script>
</body>

</html>
```

secondPage.ts:
```
const https = require("https");
const http = require("http");
const dialog = require("electron").remote.dialog;

document.getElementById("navigateButton").onclick = () => {
	const url: string = (document.getElementById("url") as HTMLInputElement).value.trim();

	const parsedURL: URL = new URL(url);
	let requestMethod = http.request;
	if (parsedURL.protocol === "https:") {
		requestMethod = https.request;
	}

	const clientRequest = requestMethod(url, { method: "HEAD", timeout: 3000 }, () => {
		dialog.showMessageBox({ message: "valid" });
	});

	clientRequest.on("timeout", () => {
		dialog.showMessageBox({ message: "timed out" });
		clientRequest.abort();
	});

	clientRequest.end();
};
```

Start the app. Click the button to go to the second page. Click the navigate button (or try another URL). You will see the "timed out" dialog appear instead of the "valid" dialog.

**Comment by pushkin-** [comment] 2020-03-21 15:35
oh, is this just me observing that the module isn't context aware or something? maybe that's all this is. If so, is `process.exit()` a kosher way of handling this?

**Comment by pushkin-** [comment] 2020-03-23 19:20
`process.exit()` worked in my minimal test app, but doesn't work in my actual app. The renderer process dies and doesn't restart. I tried `await win.webContents.executeJavascript("process.exit()"); await win.loadFile("...");`, thinking the renderer will just restart when I make the `loadFile` call since I already killed the other one, but that didn't work in my actual app.

**Comment by lyswhut** [comment] 2020-05-08 12:12
Same question:
electron: `8.2.5`
Platform: `Windows 10`

This seems to be caused by loading the native module multiple times. I searched for related issues:
- <https://github.com/electron/electron/issues/22809>
- <https://github.com/electron/electron/issues/22119>

When `app.allowRendererProcessReuse = true` is set, after the page is loaded multiple times,  the callback of the node module will time out, and the rendering process will no response.

**Comment by pushkin-** [comment] 2020-09-21 17:50
Still an issue in Electron 10.1.2

**Comment by codebytere** [comment] 2020-09-28 00:35
Duplicate of https://github.com/electron/electron/issues/22119

**Closed by codebytere** 2020-09-28 00:35 UTC
Labels: 8-x-y, bug :beetle:
