### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by xiaoqisha** [electron/electron#19595] opened 2019-08-02 15:19 UTC
System: Ubuntu 18.04
Electron Version: 6.0.0
Qs: electron ouput a path for 'electron.exe' & electron.app output 'undefined'

![image](https://user-images.githubusercontent.com/35207655/62380516-f35bdf00-b57b-11e9-8055-057ef057721b.png)

**Comment by vladimiry** [comment] 2019-08-02 17:13
This is expected behavior when you run it as `node` script. Try running like `npx electron .\index.js` or `.\node_modules\electron\dist\electron.exe .\index.js`.

**Comment by codebytere** [comment] 2019-08-02 19:50
Closing as this is not a bug. Follow the steps outlined above by @vladimiry and your issue should be corrected.

**Closed by codebytere** 2019-08-02 19:50 UTC
