### ISSUE TITLE
[Bug]: webContents.printToPDF ignores printBackground option in v28+

### ISSUE THREAD

**Issue by Hedwig188** [electron/electron#41159] opened 2024-01-29 17:19 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

27.3.0

### Expected Behavior

When printBackground is set to true, webContents.PrintToPDF should print the background color on the element.

### Actual Behavior

printBackground option is no longer respected when calling webContents.printToPDF in v28.

### Testcase Gist URL

https://gist.github.com/Hedwig188/79d0e0e7cac3f6a708e5c84c8e38b715

### Additional Information

Run the above test case to see the result. I confirmed it works fine in v27.3.0.

**Comment by Hedwig188** [comment] 2024-01-29 17:28
Looks like this is the dup of [41135](https://github.com/electron/electron/issues/41136).

**Comment by Hedwig188** [comment] 2024-01-29 17:29
Looks like this is the dup of https://github.com/electron/electron/issues/41136.

**Comment by codebytere** [comment] 2024-01-30 10:55
Duplicate of https://github.com/electron/electron/issues/41136

**Closed by codebytere** 2024-01-30 10:55 UTC
Labels: bug :beetle:
