### ISSUE TITLE
Issues with webview history APIs when visiting Twitter

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#9835] opened 2017-06-23 01:51 UTC
* Electron version: Tested on 1.6.2 and 1.7.x
* Operating system: MacOS

The webview canGoBack/canGoForward, and actual goBack/goForward actions, seem to get confused with Twitter.

You can observe this by visiting twitter from a webview:

![twitter-history-issue](https://user-images.githubusercontent.com/1270099/27463307-69f3e522-578c-11e7-9eab-0c1635a4693f.gif)

Demo: https://github.com/pfrazee/electron-bug-twitter-history

```
  $ git clone https://github.com/pfrazee/electron-bug-twitter-history
  $ cd electron-bug-twitter-history
  $ npm install
  $ npm start
```

**Comment by codebytere** [comment] 2017-09-21 23:37
is it a problem on any other sites? or literally just twitter?

**Comment by pfrazee** [comment] 2017-09-21 23:45
Twitter's the only site I've ever observed it

**Comment by 4eveRS** [comment] 2018-04-09 17:36
Same problem here, it seem's that twitter changes the webview / window history.

When you perform a webview.goBack(), the twitter page changes it position on the history array to a previous index from the actual webview loaded page, and if there's a page forward in history and you navigate in twitter site, it will also delete it from the webview history array, this causes in a loop, not allowing to actually go back or forward correctly.

**Comment by charlesclu** [comment] 2018-06-14 02:19
After playing around with the event listeners, the only thing I can find that is different about twitter from other sites is that after calling .goBack() from twitter, first a did-navigate-in-page event with url "https://twitter.com/" is fired, then the normal did-navigate event with the url of the previous page in history is fired. 

Maybe upon calling .goBack(), twitter does some in-page navigation that affects the history, and then the navigation by the goBack() method occurs, but it screws up because of the in-page navigation by twitter just beforehand.

**Comment by charlesclu** [comment] 2018-06-14 19:27
I think I've found what is exactly happening with this problem after playing around with the electron source code. See https://github.com/electron/electron/issues/13249

**Comment by codebytere** [comment] 2018-09-24 05:00
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by pfrazee** [comment] 2018-09-24 17:33
@codebytere I just confirmed this problem still exists in Electron 3.0.0. You can still reproduce it with the test case linked above

**Comment by codebytere** [comment] 2019-06-06 05:48
Closing as duplicate of https://github.com/electron/electron/issues/13249.

**Closed by codebytere** 2019-06-06 05:48 UTC
Labels: 3-0-x, bug :beetle:, platform/macOS
