### ISSUE TITLE
Crash: atom::`anonymous namespace'::Crash() Line 28

### ISSUE THREAD

**Issue by bennyn** [electron/electron#6971] opened 2016-08-25 15:17 UTC
* Electron version: 1.2.8

* Operating system: Windows 10 Home Edition

Today my Electron-based app crashed. I tried to get a good stacktrace for you (adding the symbol server to my VS settings) but unfortunately it was unable to find sources for `atom_bindings.cc`. But I made a screenshot which might help.

For the future: How can I provide better debug logs?

**Screenshot:**

![unbenannt](https://cloud.githubusercontent.com/assets/469989/17974728/850aca3e-6ae7-11e6-841c-77f2654a30b3.png)

**Comment by zcbenz** [comment] 2016-08-26 11:22
From the stack trace it seems that the renderer process crashed and your code called `process.crash()` in the `crashed` event handler.

**Comment by bennyn** [comment] 2016-08-26 11:40
Indeed. Our `crashed` event handler does the following:

```javascript
main.webContents.on('crashed', function() {
  process.crash();
});
```

What is the best practice in case the render process crashes?

**Comment by enlight** [comment] 2016-08-26 13:23
I'd say recreating the BrowserWindow that crashed would be a good idea, but ultimately that's for you to decide.

**Comment by bennyn** [comment] 2016-08-26 15:03
@enlight What involves recreating the `BrowserWindow`? Is it fairly easy to do? Can I just create a new instance and point it to a specific URL?

**Comment by kevinsawicki** [comment] 2016-08-26 17:48
> What involves recreating the BrowserWindow? Is it fairly easy to do? Can I just create a new instance and point it to a specific URL?

You might just be able to reload the window, you might want to take some code from Atom on this:

https://github.com/atom/atom/blob/2710ce33d124973f09a06c1fec2b5f064641bde0/src/main-process/atom-window.coffee#L149-L160

Closing this out since this is the expected behavior when calling `process.crash()`.

**Closed by kevinsawicki** 2016-08-26 17:48 UTC
Labels: more-information-needed
