### ISSUE TITLE
[Bug]: close/blur event handlers don't fire in main process when "invoked" from renderer

### ISSUE THREAD

**Issue by Ben-Barron** [electron/electron#32850] opened 2022-02-10 09:56 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0 or 16.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

15.1.2

### Expected Behavior

If I register an event handler on a `BrowserWindow` for the `close` or `blur` events, then subsequently from the renderer call `window.close()` or `window.blur()` I would expect my event handlers to be called. Furthermore, had the event handlers been called and I've overridden the behaviour of via `event.preventDefault()`, then I would also expect that to prevent the action in question.

### Actual Behavior

The event handlers are not be called, therefore the behaviour is not being prevented.

### Additional Information

I've put two versions where this is definitely broken and a version that is definitely working. I don't know about the versions inbetween.

**Comment by mlaurencin** [comment] 2022-02-11 03:11
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.

**Comment by Ben-Barron** [comment] 2022-02-15 14:01
This is the best I can do as I can't upload code:

`
app.on("ready", () =. {
  let win = new BrowserWindow();
  win.on("close", e => {
    e.preventDefault();
    console.log("here");
  });
  win.loadURL("http://www.google.co.uk");
  win.show();
});
`

Then open dev tools and in the immediate console window, execute `window.close()`. With 17.0.0, the window will close (it should not), nothing in the console.

Do the same thing with v15.1.2 and the window will remain open and you'll see `here` in the console.

**Comment by mlaurencin** [comment] 2022-02-16 23:12
@Ben-Barron I am having trouble reproducing your issue. Can you confirm whether or not [this gist](https://gist.github.com/mlaurencin/5169f0e45044898fdedac3474b1b876b) works for you?

**Comment by Ben-Barron** [comment] 2022-02-17 16:01
No, it does not work. Same issue. Windows 10 Build 1909

**Comment by mlaurencin** [comment] 2022-02-17 22:11
I performed tests on both Windows 10 and 11 and still could not reproduce. I am going to close this issue, but if someone else can reproduce it, then it can be reopened.

**Closed by mlaurencin** 2022-02-17 22:11 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, has-repro-comment, 16-x-y, 17-x-y, 18-x-y
