### ISSUE TITLE
Node integration: timers/promises/async callbacks stop working randomly in renderer process

### ISSUE THREAD

**Issue by KishanBagaria** [electron/electron#25311] opened 2020-09-03 19:11 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v10.1.1 (also present in v9)
* **Operating System:** macOS 10.15.5

### Actual Behavior

Node.js timers stop working indefinitely after running Electron for a while. This breaks all async Node.js functions like `fs.readFile`, `fs.promises.readFile`, and `http.get`:

<img width="869" alt="" src="https://user-images.githubusercontent.com/1093313/92156093-196e4580-ee46-11ea-9665-773db9f7ffd6.png">

In case it's not clear in the screenshot, `window.setTimeout` works but the Node.js version of `setTimeout` doesn't.

`fs.readFileSync` and synchronous functions continue to work fine:
<img width="869" alt="" src="https://user-images.githubusercontent.com/1093313/92156278-5d614a80-ee46-11ea-81b2-4f9d8d67dc96.png">

### To Reproduce

It's hard to reproduce. This issue happens randomly but frequently enough. It could happen after 10 seconds of launching Electron or after 1 hour.

### Additional Information

`allowRendererProcessReuse` is set to `true`. I use 3 native modules in the renderer process: [`keytar`](https://github.com/atom/node-keytar), [`node-mac-contacts`](https://github.com/codebytere/node-mac-contacts/) and [`node-mac-permissions`](https://github.com/codebytere/node-mac-permissions). All 3 modules are up to date.

Only refreshing (⌘ R) fixes this and gets everything to work again.

**Comment by nornagon** [comment] 2020-09-03 19:41
If you're able to reproduce this in a small Electron app (e.g. with [Electron Fiddle](/electron/fiddle) or [electron-quick-start](/electron/electron-quick-start)), even if it sometimes takes a while to reproduce, that would be very helpful!

**Comment by KishanBagaria** [comment] 2020-09-03 21:46
Definitely understand that. Will make a minimal reproducible sample as I find more info. I'm operating in a fairly large codebase. If y'all have any ideas on how to narrow it down, would appreciate it.

I moved all native modules to the main process and made an async IPC layer to call them but the issue persists.

I heavily use `v8.serialize` and `v8.deserialize`. That has previously caused weird issues.

**Comment by KishanBagaria** [comment] 2020-09-04 21:42
@zcbenz Since you [integrated the Node.js event loop](https://www.electronjs.org/blog/electron-internals-node-integration), do you have any ideas on how to debug this or reproduce this more consistently?

**Comment by aabuhijleh** [comment] 2020-09-09 14:14
Probably a duplicate of #22119?

**Comment by codebytere** [comment] 2020-09-28 00:31
Closing as duplicate of https://github.com/electron/electron/issues/22119 - progress will be tracked there!

**Closed by codebytere** 2020-09-28 00:31 UTC
Labels: 10-x-y, 9-x-y, blocked/need-repro, bug :beetle:, platform/macOS
