### ISSUE TITLE
Child window minimization, parent stays visible (but not accessible)

### ISSUE THREAD

**Issue by taras-chernovol** [electron/electron#20059] opened 2019-08-31 11:59 UTC
Window 10. Electron 5.0.1

When user minimizes child window, and there are no other windows on the desktop (windows of other apps) parent window stays visible (but not accessible) and child becomes an ugly bar...

![image](https://user-images.githubusercontent.com/20777701/64063660-c85abe80-cbff-11e9-861a-4d48da90ef45.png)

![image](https://user-images.githubusercontent.com/20777701/64063691-25567480-cc00-11e9-8c0f-de8a7a832c40.png)

```
import {app, BrowserWindow} from 'electron';

app.on('ready', () => {
    const parent = new BrowserWindow({width: 600, height: 600});
    const child = new BrowserWindow({parent: parent, width: 200, height: 200});
});
```

**Comment by taras-chernovol** [comment] 2019-09-03 09:53
Hi, is everybody here?

**Comment by pushkin-** [comment] 2019-09-26 14:45
It's kind of annoying, because there's only one taskbar icon for the app, so Alt+Tabbing will never bring you back to the child window, only to the parent window. Minimizing and restoring the main window will however restore the child window.

**Comment by electron-triage** [comment] 2020-02-15 01:04
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by pushkin-** [comment] 2020-02-15 16:31
This is still true in Electron 8. Though I'm guessing this is because of Windows, not Electron.

**Comment by maxherrmann** [comment] 2020-10-20 09:32
I can reproduce this in Electron 10.1.3 on Windows 10 (1909).

**Comment by acivan** [comment] 2020-11-17 09:18
Unfortunately, I also encountered this problem, Electron version 8.5.3 and 11.0.0. I didn't find any explanation in the documentation, Electron is really great.

**Comment by Mumbaso21** [comment] 2021-03-11 17:44
this bug is still there

**Comment by larissa-n** [comment] 2022-01-21 12:39
Any update on this? I'm still experiencing the problem in windows 11. Are child windows an unstable feature?

**Comment by pushkin-** [comment] 2022-01-21 15:43
Maybe Electron can provide a way to make them more accessible (like restore with a hotkey? I don't know), but is this not just the typical behavior of child windows on Windows?

**Comment by larissa-n** [comment] 2022-01-22 15:19
The problem still persists in v13.6.7, v14.2.4, v15.3.5, and v16.0.7 (all the latest stable releases).

If you have a frameless window, the issue is even worse: the window just collapses to a black box that can not be restored or closed. Closing the app with the task manager is the only way forward.

![Screen Shot 2022-01-22 at 4 09 11 PM](https://user-images.githubusercontent.com/37840830/150644284-481dddc0-3677-41cc-b42c-efb55e0057ab.png)

This is clearly a bug should not happen in production. 

For the time being, I think the [API](https://www.electronjs.org/docs/latest/api/browser-window#winsetparentwindowparent) should be updated so people don't use BrowserWindow's `parent` property in production.

**Comment by larissa-n** [comment] 2022-01-23 14:18
https://github.com/electron/electron/issues/30429#issuecomment-894594528

@clavin : I did not know the "floating box" in the corner was expected behavior on Windows, my bad. 

Is there any guidance on how to format a frameless window so it can be restored (so it's not just a black box that you can't restore)? Or would you give a frameless window a frame as soon as it's minimized, and make it frameless again when it's restored?

**Comment by pushkin-** [comment] 2023-01-10 15:57
bump

**Comment by pushkin-** [comment] 2023-04-12 15:03
bump

**Comment by llevasseur** [comment] 2023-04-18 19:57
bump

**Comment by codebytere** [comment] 2023-05-24 19:51
Closing in favor of https://github.com/electron/electron/issues/38425

**Closed by codebytere** 2023-05-24 19:51 UTC
Labels: platform/windows, bug :beetle:, 5-0-x, 8-x-y, 10-x-y, 11-x-y
