### ISSUE TITLE
[Clipboard] No file in ClipboardEvent when paste ( ctrl+v )

### ISSUE THREAD

**Issue by lamthanvan** [electron/electron#30124] opened 2021-07-14 08:06 UTC
Hi, i have a problem with Electrons app
I want to paste file from local computer into app to upload using vue+ts, my idea is using clipboard using ctrl+v to get file from clipboard . The problem is it worked on browser but on Electrons app side it not work properly. My code is:
`onPaste(event:ClipboardEvent) {
      var items = (event.clipboardData || event.originalEvent.clipboardData).items;
      console.log(items);
}
`
When I console log clipboard data
On browser the items will return lenth = 1
On App the items return length = 0
![image](https://user-images.githubusercontent.com/8468514/125585759-3b761014-9fab-40db-8e75-e904cdaade2e.png)

This is my first time :)
Does anyone can help me or have an other solution for this.

**Comment by duyhung1** [comment] 2021-07-14 08:10
i have same issue and still not found answer for this :((

**Comment by jkleinsc** [comment] 2021-07-14 18:08
This appears to be a duplicate of #9035.  Closing in favor of that issue.

**Closed by jkleinsc** 2021-07-14 18:08 UTC
