### ISSUE TITLE
webview tag ignores attributes when rendered via React

### ISSUE THREAD

**Issue by fasterthanlime** [electron/electron#6046] opened 2016-06-14 18:04 UTC
* Electron version: 1.2.2
* Operating system: macOS

I'm not entirely sure this is an electron bug, but here goes: https://github.com/fasterthanlime/electron-react-bug

### Expected behavior

Chrome devtools console shows the following:

```
webview partition:  react
webview partition:  not react
```

### Observed behavior

Chrome devtools console shows the following:

```
webview partition:  
webview partition:  not react
```

### Theory

I *think* what may be happening here is that React creates the DOM node, then sets the attributes while the webview isn't initialized yet (because of it running in another thread, etc.) — I suppose there's a short time period between the webview node being created and it emitting dom-ready where assigning properties doesn't do anything.

This probably is only an issue starting with React 15.0+, because they changed the way they render the DOM (they used to rely on innerHTML, which probably worked fine because it set the attributes directly on node creation).

**Comment by fasterthanlime** [comment] 2016-06-14 18:11
More research: using createElement + assigning attributes directly works as expected, so react must be doing something else, see the [almost-react](https://github.com/fasterthanlime/electron-react-bug/tree/almost-react) branch of my example repository.

**Comment by zeke** [comment] 2016-06-14 18:27
First sighting of `macOS` in the wild!

**Comment by zcbenz** [comment] 2016-06-15 01:48
The biggest difference between `src` and `partition` is, the `partition` attribute can not be changed after the the navigation has began, e.g. the element has `src` attribute and gets attached to DOM.

I think this is caused by how React creates the element, it seems that React only sets the `partition` attribute after setting `src` and attaching the element. This is only my guessing though, I tried to investigate React's source code but it is too complex.

I'm closing this issue since we don't seem to have a way to solve this on Electron's side.

**Closed by zcbenz** 2016-06-15 01:48 UTC

**Comment by steverandy** [comment] 2016-06-15 02:27
`partition` is not one of the supported attributes by react.
https://facebook.github.io/react/docs/tags-and-attributes.html

**Comment by fasterthanlime** [comment] 2016-06-15 08:37
> partition is not one of the supported attributes by react.
> https://facebook.github.io/react/docs/tags-and-attributes.html

Ooh, that makes a lot more sense than any previous theories! That means there's basically two ways to fix this:

  * ask React to add valid attributes (not really future-proof + unsure they would accept that)
  * let Electron support `data-*` variants for nonstandard attributes like partition, useragent, etc.

The second one would make my life much easier. Does it seem feasible without cluttering electron's codebase too much? (I'm blissfully unaware of that part of electron's internals for now).

If neither solutions are adopted, then it'd probably be worth a note in the documentation — I suppose I'm not the only one using the electron/react/webview combo.

**Comment by enlight** [comment] 2016-06-15 09:19
You could wrap the `webview` element in a React component, and have the component create and insert the element into the DOM in `componentDidMount()` so that React doesn't mess things up.

**Comment by fasterthanlime** [comment] 2016-06-15 10:26
> You could wrap the webview element in a React component, and have the component create and insert the element into the DOM in componentDidMount() so that React doesn't mess things up.

That's [what we do now](https://github.com/itchio/itch/blob/3231a7f02a13ba2452616528a15f66670a8f088d/appsrc/components/browser-meat.js#L227) — but I'm still really hoping the `data-*` solution I suggested above gets implemented.

**Comment by McPo** [comment] 2017-03-09 20:59
@fasterthanlime  I agree that following the standard of data-* seems like a good change.
However to work around it you can use the is operator in react, more info here http://stackoverflow.com/a/33860892/1167880

```
<webview is nodeintegration width="100%" height="100%" src="./webview.html" />
```

**Comment by fasterthanlime** [comment] 2017-03-11 09:51
@McPo Interesting! I didn't know about the `is` operator. However, I'm hesitant to rely on it since it's not documented. Who knows if it'll still be there in a few versions of React (especially with Fiber around the corner!). I suppose the next step would be to file a React bug so they document the feature :)
