### ISSUE TITLE
[Bug]:  Print options not work when silent true

### ISSUE THREAD

**Issue by sunchanglong** [electron/electron#29334] opened 2021-05-26 09:40 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.x

### What operating system are you using?

Other (specify below)

### Operating System Version

both in win and mac

### What arch are you using?

x64

### Last Known Working Electron version

11.4.3

### Expected Behavior

print options
``` 
{
  silent: true,
  deviceName: 'actual printer name',
  landscape: true,
  copies: 2,
  pageRanges: [{from: 1, to: 1}],
  pageSize: 'A5'
}
``` 

all of the options would be honored when silent true

### Actual Behavior

all of the options above not honored

**Comment by sunchanglong** [comment] 2021-05-26 09:41
`pageRanges ` also not honored in 11.x. others above works in 11.x.

**Comment by Linbubin** [comment] 2021-05-27 03:20
10.x is work，but in the process of printing, clicking software quickly will cause software crash.
So, not know how version can i choose.  :(

**Comment by k2s** [comment] 2021-09-09 06:26
This ticket is duplicate of #28502 which also contains Electron Fiddle example.
Version Electron 11 is deprecated now, but printing doesn't' work in 12, 13 and 14 which is now stable.
Unfortunately my knowledge is not enough to fix it and would appreciate very much if somebody would.

**Comment by Hedwig188** [comment] 2021-09-16 19:59
Do we have some estimate timeline when this issue can be fixed?

**Comment by Hedwig188** [comment] 2021-10-01 16:22
@codebytere Could you point us to the right direction to investigate this issue?

**Closed as completed** 2021-10-25 15:52 UTC
Labels: platform/windows, platform/macOS, bug :beetle:, 12-x-y
