### ISSUE TITLE
[Bug]: miss a '{'

### ISSUE THREAD

**Issue by TingyuanZhang1208** [electron/electron#29311] opened 2021-05-24 12:11 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

doc

### What operating system are you using?

macOS

### Operating System Version

doc

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

doc

### Expected Behavior

https://www.electronjs.org/docs/tutorial/notifications
showNotification ()

### Actual Behavior

https://www.electronjs.org/docs/tutorial/notifications
showNotification ()

### Additional Information

https://www.electronjs.org/docs/tutorial/notifications
showNotification ()

**Comment by Kilian** [comment] 2021-05-25 12:14
I'm gonna close this issue as I can't see any missing { on that page. Feel free to create a PR or re-open with a screenshot or other clear indication of where you think the issue is.

**Closed by Kilian** 2021-05-25 12:14 UTC
Labels: bug :beetle:
