### ISSUE TITLE
Remote object method return values scrambled

### ISSUE THREAD

**Issue by wmnnd** [electron/electron#6834] opened 2016-08-12 22:39 UTC
Hi there, I’m trying to build a Flux-like architecture with an immutable data store potentially shared by multiple browser windows. For this I am using Immutable.js and the remote module of Electron.

However, even though everything *seemed* to work fine initially, it turns out that non-primitive return values from remote objects seem to become scrambled. The problem with this is that it is unclear which interactions with a remote object will work reliably and which won’t.

It seems like this might be related to #6407 which has been closed already, though.

**app.js**
```javascript
var Immutable = require("immutable")
var map = Immutable.Map({"a": 1, "b": 2})
```
**test.js**
```javascript
var Immutable = require("immutable")

//This is the expected behavior
var map = Immutable.Map({"a": 1, "b": 2})
map.toJS() /* => {
    "a": 1,
    "b": 2
}*/

//Unexpected behavior with remote object
var remoteMap = require('electron').remote.getGlobal('map')
remoteMap.toJS() /* => {
    "a": 1,
    "get a": function(),
    "set a": function(value),
    "b": 2,
    "get b": function(),
    "set b": function(value)
} */
````

Interestingly, ipcRenderer.sendSync serializes the return value (instead of returning a seemingly intact object) so that the following code produces a different result from the one shown above:
**app.js**
```javascript
const {ipcMain} = require("electron")
var Immutable = require("immutable")

var map = Immutable.Map({"a": 1, "b": 2})

ipcMain.on("getMap"), (event, arg) => {
    event.returnValue = map
})
```

**test.js**
```javascript
var remoteMap = ipcRenderer.sendSync("getMap")
remoteMap.toJS // => undefined; we’re getting an object that has already been serialized!
remoteMap /* => {
    "a": 1,
    "b": 2
} */
```
* Electron version: v1.3.3
* Operating system: Ubuntu 16.04

**Comment by TimNZ** [comment] 2016-08-13 08:50
A ready to run test app that reproduces the error is helpful, but I believe the sendSync serialization will be doing the equivalent of toObject(), where as .remote.getGlobal supports full marshalling of functions.

https://github.com/electron/electron/blob/master/docs/api/ipc-renderer.md#ipcrenderersendsyncchannel-arg1-arg2-

**Comment by wmnnd** [comment] 2016-08-13 09:18
Thank you for your response, @TimNZ. 
I have created a working example here: https://github.com/wmnnd/electron-remote-ipc-scramble

**Comment by TimNZ** [comment] 2016-08-13 09:23
I think my comment re sendSync addresses the difference.

**Comment by wmnnd** [comment] 2016-08-13 09:28
I agree the difference is clear, and sendSync works as expected but don’t you think the behavior with remote is unexpected?

**Comment by TimNZ** [comment] 2016-08-13 09:31
Nope. For getGlobal, .toJS() is being executed in the browser/main process and the result marshalled back to the calling renderer via internal IPC, where it is then wrapped up, resulting in getters/setters.  

You only think it's an issue because you are inspecting it via DevTools or console.log perhaps, whereas what is the real world issue - what is it breaking?

**Comment by TimNZ** [comment] 2016-08-13 09:34
The reason there are getters/setters introduced as they will actually call back into the browser process on access - the source object may have getters/setters that need to be called.

**Comment by MarshallOfSound** [comment] 2016-08-13 09:34
@wmnnd What you are seeing is the automatic marshalling that the `remote` and `IPC` modules perform.

Those getters and setters are actually wrapped function that call IPC methods behind the scenes.  This is because the remote module runs the method in the `main` process and then it is emulated with getter and setter methods on an object in the `renderer` process.

Whereas IPC actually sends a serialized object through IPC which is why it looks correct on the other end in your console.

As far as I can tell this isn't an issue as the return values are correct, just you might have been confused by the getters and setters.  Is that correct?

**Comment by MarshallOfSound** [comment] 2016-08-13 09:36
Pretty much what @TimNZ said 👍

**Comment by TimNZ** [comment] 2016-08-13 09:36
@MarshallOfSound  yeah, what i said :)

**Comment by TimNZ** [comment] 2016-08-13 09:36
Lolz..

**Comment by MarshallOfSound** [comment] 2016-08-13 09:37
Team NZ FTW 👍 

Closing this out as a non-issue unless someone can point out what is actually wrong here

**Comment by wmnnd** [comment] 2016-08-13 09:38
Unfortunately, the marshalling breaks some of the functionality of the Immutable.js object. I have updated my example to show that, while map.get("a") still returns the value for "a", as expected, map.map(x => x*x) does not return the expected result but rather a mess of unexpected properties:
https://github.com/wmnnd/electron-remote-ipc-scramble

**Closed by MarshallOfSound** 2016-08-13 09:37 UTC
Labels: more-information-needed

**Comment by TimNZ** [comment] 2016-08-13 09:41
@MarshallOfSound Even spookier is I went to Bucklands Beach intermediate and Pakuranga College.. though many years before you.

**Comment by TimNZ** [comment] 2016-08-13 09:50
@wmnnd What code is being broken?  Seeing things in console.log()  you are not expecting doesn't mean anything is broken.

**Comment by MarshallOfSound** [comment] 2016-08-13 09:51
@wmnnd I believe this was explained by @zcbenz somewhere (I can't find it now).  So I'll give it a shot.

Basically I don't think the `remote` implementation doesn't allow mutations like that across IPC.  That `.map` call you tried to run could result in hundreds or even thousands of synchronous IPC messages (depending on your object size) passing the arguments through as remote objects each time and passing the return value of your function in the renderer process back to the main process.

I think you are attempting to do something the wrong way, I.e. you are trying to sync an object between two processes using the `remote` module.  Personally in your case I would be using IPC events to send the result `.toJS()` to the renderer process and custom IPC events to perform the `.map` operations.

Something like this perhaps.

```js
// Main process
const map = Immutable.Map({"a": 1, "b": 2})

ipcMain.on("getMap"), (event, arg) => {
    event.sender.send(map.toJS())
})

ipcMain.on("mapTheMap", (event, mapFn) => {
  map.map(mapFn)
  event.sender.send("theMap", map.toJS())
});

// Renderer process
ipcRenderer.on("theMap", (newMap) => {
  console.log(newMap)
})
ipcRenderer.send("getMap")

const mappedRemoteMap = ipcRenderer.send("mapTheMap", (x) => x * x)
```

You may notice I switched from `sendSync`.  This is because using `sendSync` is generally a bad plan  **especially** when sending large objects as it blocks the entire thread until it is successful.  Hopefully this code helps you with your implementation
