### ISSUE TITLE
webview uploadfile net::ERR_ACCESS_DENIED in linux 

### ISSUE THREAD

**Issue by skybtone** [electron/electron#35567] opened 2022-09-02 14:28 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.15

### What operating system are you using?

Other Linux

### Operating System Version

linux 4.9.0

### What arch are you using?

x64

### Last Known Working Electron version

no

### Expected Behavior

When I use electron for webview, the web has file upload function
My electron version is 19.0.15, I test file upload in windows 11, and the file name is chinese name, and It's OK!
BUT, when I test file upload in linux 4.9.0(debian),  and the file name is chinese name, It's NOT OK!
The web for testing file upload, for example:https://element-plus.gitee.io/zh-CN/component/upload.html

Before  I report this bug, I have visited https://github.com/electron/electron/issues/24850, my problem is not the same, because it's in linux, not windows, for windows is OK!

### Actual Behavior

![bugreport](https://user-images.githubusercontent.com/28429945/188170840-73e0a849-efe6-404d-a5a4-5349b928071c.jpg)

### Testcase Gist URL

https://element-plus.gitee.io/zh-CN/component/upload.html

**Comment by skybtone** [comment] 2022-09-02 15:06
when the file for uploading is english name, the result is yet not OK, it's:
![fileupload](https://user-images.githubusercontent.com/28429945/188178826-93238c58-5a43-4074-9425-6dd0f7647b35.jpg)

**Comment by skybtone** [comment] 2022-09-03 06:02
I have confirmed the basic reason of this issue is here:
https://github.com/electron/electron/issues/34812

**Comment by mlaurencin** [comment] 2022-09-07 20:46
Thanks for taking the time to contribute!

It does seem that this is a duplicate of https://github.com/electron/electron/issues/34812. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by mlaurencin** 2022-09-07 20:46 UTC
Labels: bug :beetle:
