### ISSUE TITLE
Files in locales directory have got bigger between Electron 3 and 4

### ISSUE THREAD

**Issue by torycl** [electron/electron#18738] opened 2019-06-12 08:16 UTC
On Windows, files in locales directory are much bigger with no apparent reason. The change has happened between Electron 3 and 4. 

### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 4.2.4
* **Operating System:**
  * Windows, all versions (can be similar on other platforms)
* **Last Known Working Electron version:**
  * 3.1.9

### Expected Behavior
If files in locales were wrong and now they are correct, there should be some issue which has been fixed or documentation what has been changed and how.
There should be some documentation why these files are important and why they are distributed with core electron packge.
Otherwise it would be understandable if these files grow slowly between version as localisation in these languages improve.

### Actual Behavior
Directory "locales" filed with tens of approx. 100 kB files with unknown content.
I cannot find any relevant documents about contents of electron package and "locales" directory.
There is a big jump between version 3 and 4 and I cannot find why.

### To Reproduce
Unzip [any electron 4 distribution zip](https://github.com/electron/electron/releases/download/v4.2.4/electron-v4.2.4-win32-ia32.zip) and check locales directory on Windows.

### Screenshots
![locales-diff](https://user-images.githubusercontent.com/3928694/59334168-2c08d600-8cfa-11e9-9fed-c6a12ff27c8c.png)

### Additional Information
My intent is to shrink electron distribution package as much as possible. Every MB counts. So I try to inspect every file and explore possibilities how to make it smaller or remove. I don't want to compromise quality of the package. I just want to get rid of files which are not used in our products. So I need to understand why I would need that file.

**Comment by cachius** [comment] 2019-07-16 07:43
When using electron-builder, you can default to the locale en-US via
`app.commandLine.appendSwitch('lang', 'en-US'); // before app.on('ready', ...)`
and remove the unused locales from your electron project via the "afterPack" hook in the package.json
`"build": {
    "afterPack": "./removeLocales.js",
...
}`
which could look like
```
//https://www.electron.build/configuration/configuration#afterpack
exports.default = async function(context) {
	//console.log(context)
	var fs = require('fs');
	var localeDir = context.appOutDir+'/locales/';

	fs.readdir(localeDir, function(err, files){
		//files is array of filenames (basename form)
		if(!(files && files.length)) return;
		for (var i = 0, len = files.length; i < len; i++) {
			var match = files[i].match(/en-US\.pak/);
			if(match === null){
				fs.unlinkSync(localeDir+files[i]);
			}
		}
	});
}
```

**Comment by electron-triage** [comment] 2020-02-19 20:37
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:25
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:25 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/windows

**Comment by fabiospampinato** [comment] 2020-03-21 01:13
Electron builder now supports a `mac.electronLanguages` option, which makes this even easier to do.

However since Electron v8 those locale files are empty for me, so it might be pointless to remove them.

**Comment by vanowm** [comment] 2021-12-14 05:06
The issue still exists in v11.5.0
