### ISSUE TITLE
[Bug]: Large regression in `crashReporter.start()` blocking time on macOS

### ISSUE THREAD

**Issue by timfish** [electron/electron#33072] opened 2022-02-24 18:53 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v12.0.0-nightly.20201116 to 17.1.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur

### What arch are you using?

x64

### Last Known Working Electron version

v12.0.0-nightly.20201112

### Expected Behavior

`crashReporter.start()` should return quickly so that it doesn't delay app startup?

### Actual Behavior

With the following code:
```ts
console.time('crashReporter');
crashReporter.start({ submitURL: 'https://my.url.com/etc'});
console.timeEnd('crashReporter');
```
On a very slow old mac I get the following times:

v10.4.7 - <50ms
v11.5.0 - <50ms
v12.0.0-nightly.20201112 - <50ms

v12.0.0-nightly.20201116 - 800-1000ms
v12.0.0 - 800-1000ms
v12.2.3 - 800-1000ms
v13.6.9 - 800-1000ms
v17.1.0 - 800-1000ms

### Additional Information

Here are the relevant commits between these versions:
https://github.com/electron/electron/commits/main?since=2020-11-11&until=2020-11-16

Caused by this Chromium bump?
https://github.com/electron/electron/pull/26223

**Comment by nornagon** [comment] 2022-02-28 16:05
Related? https://github.com/electron/electron/issues/26143

**Comment by timfish** [comment] 2022-02-28 17:41
My testing was entirely using Fiddle so appears to have nothing to do with signing. 

@toxik can you confirm which macOS version you've tested this on?

**Comment by toxik** [comment] 2022-02-28 18:11
Hey @timfish, I'm on 12.2.1

**Comment by timfish** [comment] 2022-02-28 18:22
The linked issue needs the title updating.

Looks like it happens on Big Sur and Monterey regardless of signing.

**Comment by nornagon** [comment] 2022-03-17 00:10
Duplicate of #26143

**Closed by nornagon** 2022-03-17 00:10 UTC
Labels: performance :checkered_flag:, bug :beetle:

**Comment by mrchaofan** [comment] 2022-04-18 09:05
I met same problem. I update electron to version 17.4.0. crashReporter.start is still slow.
