### ISSUE TITLE
Scrollbars too wide on zoomed DPI

### ISSUE THREAD

**Issue by sgehrman** [electron/electron#8513] opened 2017-01-25 23:33 UTC
just did an npm update and it downloaded electron 1.5.  now scrollbars are crazy ugly weird.

![image](https://cloud.githubusercontent.com/assets/287137/22313832/839a897e-e313-11e6-9a29-6c285876c10b.png)

**Comment by kevinsawicki** [comment] 2017-01-25 23:54
@sgehrman can you include a code snippet that works in 1.4.15 but not in 1.5.0 to help reproduce this issue?

**Comment by seanchas116** [comment] 2017-01-26 02:35
This unintended big scroll bars appear in Windows and Electron 1.5 when DPI scale is large.

How to reproduce:

* Set display DPI scale to 200% in Windows and relogin
* Open webpage with scrollbar in Electron (e.g., Electron tests)
* The big scroll bar appears

[![https://gyazo.com/df1ef745ccec7d7290ea81f4f8fc6769](https://i.gyazo.com/df1ef745ccec7d7290ea81f4f8fc6769.png)](https://gyazo.com/df1ef745ccec7d7290ea81f4f8fc6769)

**Comment by kevinsawicki** [comment] 2017-01-26 18:13
@bsclifton any ideas on this one? Seen anything similar on Brave?

**Comment by bsclifton** [comment] 2017-01-27 00:34
@kevinsawicki yes- we definitely have seen this and other DPI related issues ☹️ 

I have some hints, although I haven't traced it down in the code yet.  The width of the scrollbar is calculated using GetSystemMetrics.  Unless there is a bug in the Chromium code (which is totally possible), I'm thinking that the electron code is processing this in one of the inherited classes (widget delegate, etc).  This value needs to be adjusted from DIP to screen size.  It's going to be a similar problem to what I had fixed with the border on 200% with frameless windows:
https://github.com/electron/electron/blob/master/atom/browser/ui/views/menu_layout.cc#L21-L22

**Comment by kevinsawicki** [comment] 2017-01-27 23:03
Looks like a scrollbar change did land in 55 so I'll check if this still occurs on the Chrome 56 branch in #8501 just in case.

https://codereview.chromium.org/2290743002

**Comment by kevinsawicki** [comment] 2017-02-07 17:37
This appears to be fixed in Chrome 56 which is used in Electron 1.6.0, closing this out.

**Closed by kevinsawicki** 2017-02-07 17:37 UTC
Labels: bug, windows

**Comment by zachsa** [comment] 2018-03-05 13:47
This same wide scrollbar is appearing for me in general usage of V64.0.3282.186. And that's on all sites (including this one). I'm using a Surface Pro 3 with screen at 200% (recommended).

![capture](https://user-images.githubusercontent.com/6336500/36978233-749ebf28-208c-11e8-9000-be17f447d70a.PNG)
