### ISSUE TITLE
Flash not work in Electron

### ISSUE THREAD

**Issue by flute** [electron/electron#7727] opened 2016-10-25 11:40 UTC
I`m tried to play flash in electron, and I have followed this:

https://github.com/electron/electron/blob/master/docs/tutorial/using-pepper-flash-plugin.md

The flash plugin was load successful, but still not work, the terminal shows:

```
NOT SANDBOXED
Vector smash protection is enabled.
```

What should I do to resolve this?

**Comment by zeke** [comment] 2016-10-25 18:52
Can you provide a minimal app that reproduces this problem?

Also, what operating system and Electron version are you using?

**Comment by flute** [comment] 2016-10-26 01:59
@zeke Tkanks for your replay, I'm willing to provide this app, but due to company's secret, I can't do that.
* System: OSX 10.12.1
* Electron: 1.3.5
* Flash: 23.0.0.185

What I'm doing is  live show provided by Tecent(Qcloud.com), I will get video from phone and play it at pc. It works when I palyed in chrome, but failed in electron. 
Here's paly code:
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"/>
    <title>live</title>
</head>
<body>
<div id="id_video_container" style="width:100%; height:auto;"></div>
<script src="//qzonestyle.gtimg.cn/open/qcloud/video/live/h5/live_connect.js" charset="utf-8"></script>
<script type="text/javascript">
    (function () {
        var player = new qcVideo.Player("id_video_container", {
            "live_url" : "http://4928.liveplay.myqcloud.com/live/4928_ludis.flv",
            "live_url2" : "http://4928.liveplay.myqcloud.com/live/4928_ludis.m3u8",
            "width" : 800,
            "height" : 450
        });
    })()
</script>
</body>
</html>
```

**Comment by zeke** [comment] 2016-10-26 06:12
Understandable that you can't share your company secrets, but this is not enough info for us to easily diagnose the problem. Please try to reproduce the error in a simple app, perhaps using https://github.com/electron/electron-quick-start as a starting point.

**Comment by andymartinwork** [comment] 2016-10-27 06:53
```

**Comment by flute** [comment] 2016-10-28 09:15
@andymartinwork It surely caused by flash. After load flash plugin, simply flash works well, but streaming media using RTMP does't work, It seems the `.swf` has no permissions.
I have also tried this:
https://github.com/szwacz/nw-flash-trust
But still not work,  it may be because I'm using an internal `.swf` file, rather than the one on my computer, this really confuse me.

**Comment by andymartinwork** [comment] 2016-10-28 13:28
Have you checked the console log?
You might need to disablewebsecurity if your RTMP source is http and your website is https

**Comment by zcbenz** [comment] 2016-11-16 01:44
I'm closing this since we are not able to fix it without more information.

**Closed by zcbenz** 2016-11-16 01:44 UTC
Labels: more-information-needed

**Comment by stellar2016** [comment] 2017-03-25 01:37
@flute I'm meeting the same situation ,do you solve it now ?

**Comment by 18124772589** [comment] 2019-07-11 07:49
@stellar2016 I'm meeting the same situation ,do you solve it now ?

**Comment by 18124772589** [comment] 2019-07-11 07:55
> @andymartinwork @zeke 肯定是由flash造成的。加载flash插件后，简单的flash工作正常，但使用RTMP的流媒体不起作用，似乎`.swf`没有权限。
> 我也试过这个：
> [https](https://github.com/szwacz/nw-flash-trust)：[//github.com/szwacz/nw-flash-trust](https://github.com/szwacz/nw-flash-trust)
> 但是仍然无法正常工作，可能是因为我使用的是内部`.swf`文件，而不是我电脑上的文件，这真让我困惑。

我遇到了跟您一样的问题，使用的是远程的.swf文件，无法用nw-flash-trust授权，请问您这个问题有解决方案吗？

**Comment by stellar2016** [comment] 2019-07-15 01:10
@18124772589 finally，we give up this method.
