### ISSUE TITLE
Trigger Click on MenuItem

### ISSUE THREAD

**Issue by jeremythuff** [electron/electron#7067] opened 2016-09-02 04:00 UTC
* Electron version: 1.3.4
* Operating system: Windows 10

I am attempting to create an html based menu for the application that is derived from `Menu.getApplicationMenu()` 

When an item on my derived menu is click I would like to be able to trigger the associated behavior on the corresponding MenuItem. 

In angular my code looks as follows:

```
     $scope.execute = (menuItem, $event) => {

	     if(menuItem.role) {
		//trigger role...?
	     } else {
		menuItem.click(menuItem, remote.getCurrentWindow(), $event);
	     }
     }
```

Firstly I would like to be able to trigger the role if that is set, and secondly `menuItem.click(...);` results in the following error:

> [10152:0831/231147:ERROR:atom_bindings.cc(79)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

Maybe this is not the desired functionality of click on MenuItem, and maybe there is another way to accomplish this. If not, I feel that it would be useful be able to customize the look of the application's menu without having to re-implement all of its functionality.

**Comment by kevinsawicki** [comment] 2016-09-06 17:42
Are you able to create a minimal reproduction app that demonstrates the issue?

> [10152:0831/231147:ERROR:atom_bindings.cc(79)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

It looks like your app is running out of memory, this could be a leak in your app or an issue in Electron, a reproduction example would really help track things down.

**Comment by kevinsawicki** [comment] 2016-09-30 18:04
Closing this out until more information is provided.

**Closed by kevinsawicki** 2016-09-30 18:04 UTC
Labels: more-information-needed

**Comment by lacymorrow** [comment] 2024-01-02 04:28
I am interested in this exact same situation. I would like to build an HTML representation of the "File" menubar that is derived from `Menu.getApplicationMenu()`.

Also:
> When an item on my derived menu is click I would like to be able to trigger the associated behavior on the corresponding MenuItem.

I was able to accomplish this with a combination of 
- Setting an `id` for every MenuItem
- Serializing the menu using a function like below
- Loading the serialized menu over IPC
- Using `Menu.getMenuItemById(id)?.click()`, triggered by another IPC call

```js
// export a serialized version of the menu
export const serializeMenu = (
	menu: Menu | null,
): MenuItemConstructorOptions[] => {
	if (!menu) return [];
	return menu.items.map((item) => {
		// MenuItem properties that are passed to the renderer process
		const serialized: MenuItemConstructorOptions = {
			label: item.label,
			id: item.id,
			type: item.type,
			accelerator: item.accelerator,
			// icon: item.icon,
			sublabel: item.sublabel,
			enabled: item.enabled,
			visible: item.visible,
			checked: item.checked,
		};

		if (item.submenu) {
			serialized.submenu = serializeMenu(item.submenu);
		}

		return serialized;
	});
};
```

**Comment by lacymorrow** [comment] 2024-01-02 04:28
I've created an Electron boilerplate with the code here: https://github.com/lacymorrow/electron-shadcn-boilerplate
