### ISSUE TITLE
[Bug]: when i use setPosition or setBounds api to drag window in windows10 platform, my window's width and height will keep add

### ISSUE THREAD

**Issue by SorryToPerson** [electron/electron#40566] opened 2023-11-20 11:35 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

when i use setPosition or setBounds api to drag window in windows10 platform, my window's width and height will keep add

### Actual Behavior

when i use setPosition or setBounds api to drag window in windows10 platform, my window's width and height will keep add

### Testcase Gist URL

https://gist.github.com/SorryToPerson/ea9bbbcf0596a5114291c9e742ddbbfe

### Additional Information

[Bug]: When i use setPosition or setBounds api to drag window in windows10 platform, my window's width and height will keep add.
And the same behaviour is not exist on mac

**Comment by fanchenio** [comment] 2023-11-21 02:44
This is an old question.

https://github.com/electron/electron/issues/10862

**Comment by SorryToPerson** [comment] 2023-11-21 02:49
> This is an old question.
> 
> #10862

thanks

**Comment by fanchenio** [comment] 2023-11-21 03:10
But the problem has not been solved.

**Comment by codebytere** [comment] 2023-11-27 11:03
Closing as duplicate of https://github.com/electron/electron/issues/10862

**Closed by codebytere** 2023-11-27 11:03 UTC
Labels: bug :beetle:
