### ISSUE TITLE
Renaming electron.exe 4 beta 3 leads to unloadable native node module

### ISSUE THREAD

**Issue by Titaye** [electron/electron#15147] opened 2018-10-13 15:55 UTC
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.3
* Operating System (Platform and Version): Window 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
Renaming electron.exe doesn't break native addon linked against node.dll

**Actual behavior**
electron 4 is not using node as a shared dll liked explained here https://electronjs.org/blog/electron-internals-using-node-as-a-library#shared-library-or-static-library
If you build a native module with nodegyp and renames electron.exe to whatever.exe, the corresponding nodemodule will not load.

**To Reproduce**
Build any native module agains electron 4, renames electron.exe to something else and tries to load the module. It will fail

**Comment by MarshallOfSound** [comment] 2018-10-14 00:00
cc @nornagon

**Comment by nornagon** [comment] 2018-10-15 22:37
#15173 works around this until the fix is landed in node-gyp.

**Comment by MarshallOfSound** [comment] 2018-10-20 15:29
@Titaye We have a test for this now: https://github.com/electron/electron/pull/15173/files#diff-71be06e4e3b7346633fd1f9d74913732R29

If you can provide a failing case / repro (preferably based off of electron-quick-start) we might be able to help.  But I just verified locally and this does work.  Please ensure you are using 4.0.0-beta.4 and npm isn't giving you a nightly or something by mistske

**Comment by nornagon** [comment] 2018-10-22 19:48
Looking at the dependencies will show node.exe, but when loading the module, this [delay load hook](https://github.com/nodejs/node-gyp/blob/e2401e1395bef1d3c8acec268b42dc5fb71c4a38/src/win_delay_load_hook.cc#L21) from node-gyp will kick in and instead return a handle to the current executable. I'm surprised it doesn't work—our test is passing!

I'll see if I can reproduce the issue you're seeing using your repo.

**Comment by nornagon** [comment] 2018-10-22 20:29
I can reproduce the issue on beta.4. It works when renaming `electron.exe` to `node.exe` but otherwise gives the extremely helpful message `The specified procedure could not be found.`.

**Comment by nornagon** [comment] 2018-10-22 23:35
Well, 3 hours later, I finally figured out what's going on.

Your repro case defines the `msbuild_settings` field, which takes precedence over `msvs_settings`: https://github.com/nodejs/node-gyp/blob/master/gyp/pylib/gyp/generator/msvs.py#L3009

Unfortunately, all of node-gyp's configuration expects the `msvs_settings` field to be respected, which in your project, it isn't, because `msbuild_settings` is defined. In particular, when linking your project, gyp fails to specify that `/DELAYLOAD:node.exe` should be passed to the linker. Removing the `msbuild_settings` section from your binding.gyp fixes the issue.

**Closed by nornagon** 2018-10-22 23:35 UTC
Labels: bug/regression :leftwards_arrow_with_hook:
