### ISSUE TITLE
[Bug]: powerMonitor.onBatteryPower always returns undefined

### ISSUE THREAD

**Issue by jcalado** [electron/electron#29291] opened 2021-05-22 21:32 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 20H2

### What arch are you using?

x64

### Expected Behavior

powerMonitor.onBatteryPower should return a boolean

### Actual Behavior

powerMonitor.onBatteryPower always returns `undefined`. Tested while on AC and on battery power.

**Comment by nornagon** [comment] 2021-06-22 22:53
I can't reproduce this. Further, I can't see any possible code path by which `onBatteryPower` should return anything other than a boolean. I'm going to close this as unreproducible, but if you can provide a gist (especially using [Electron Fiddle](/electron/fiddle)) that shows the issue then I'm happy to continue investigation.

**Closed by nornagon** 2021-06-22 22:53 UTC
Labels: bug :beetle:
