### ISSUE TITLE
macOS High Sierra: native window tabs are not showing up properly

### ISSUE THREAD

**Issue by bpasero** [electron/electron#10657] opened 2017-09-29 09:23 UTC
* Electron version: 1.7.x
* Operating system: mac OS 10.13.0 (high sierra)

### Expected behavior

Native tabs show up properly like in the finder:

![image](https://user-images.githubusercontent.com/900690/31009597-51599c36-a508-11e7-8081-fa4e44a55f0b.png)

### Actual behavior

Native tabs are not showing up at all even though some space is reserved to show them:

![image](https://user-images.githubusercontent.com/900690/31009611-5f16812c-a508-11e7-80ff-8c4509fbf1bc.png)

### How to reproduce

Just set `tabbingIdentifier` to a `BrowserWindow` and make sure to "View > Show Tab Bar".

This all works fine in macOS Sierra, so it must be a regression with High Sierra. Do we maybe have some checks in the code that test for Sierra but not newer releases?

ping @tonyganch

**Comment by thomasjo** [comment] 2017-09-29 11:49
> Do we maybe have some checks in the code that test for Sierra but not newer releases?

@bpasero [We do indeed](https://github.com/electron/electron/blob/04430c6dda80c25d24b7752f38f87003ac7ab3aa/atom/browser/native_window_mac.mm#L468-L484).

**Comment by bpasero** [comment] 2017-10-22 06:55
@jkleinsc I do not think this is fixed (see https://github.com/electron/electron/pull/10696#issuecomment-337278050), can we reopen? 

/cc @tonyganch as original [author](https://github.com/electron/electron/pull/9052) of this feature

**Comment by jkleinsc** [comment] 2017-10-22 16:51
@bpasero yes I’ll reopen it.

**Comment by michaelduminy** [comment] 2017-11-15 09:23
Any update on this?

**Comment by rvielma** [comment] 2017-11-22 17:18
Something new, please can not work like this

**Comment by phoenixgao** [comment] 2017-12-05 03:58
It's so broken without tabs..

**Comment by miltonbecker** [comment] 2017-12-05 12:56
@jkleinsc please, is there any update on this?

**Comment by jkleinsc** [comment] 2017-12-05 17:07
@miltonbecker unfortunately there isn't a fix for this issue yet.

**Comment by nicobytes** [comment] 2018-01-05 14:35
@jkleinsc  please, is there any update on this?

**Comment by pi0** [comment] 2018-01-05 15:17
This really reduced my productivity for weeks 😂 Any hint if someone wants contribute to fix it sooner?

**Comment by phoenixgao** [comment] 2018-01-06 15:52
😂 I have been not working for weeks

**Comment by linmodev** [comment] 2018-01-08 02:19
It doesn't have anyone fix it yet

**Comment by bpasero** [comment] 2018-02-06 16:22
@jkleinsc can this be triaged as regression?

**Comment by jkleinsc** [comment] 2018-02-06 16:33
@bpasero is this a regression or is this a result of Electron never properly supporting this feature in High Sierra?  eg, did this feature ever properly work in Electron?

**Comment by bpasero** [comment] 2018-02-06 16:35
@jkleinsc yes this feature works fine in macOS < high sierra

**Comment by jkleinsc** [comment] 2018-02-06 16:42
ok @bpasero I added a new label "OS regression" to distinguish from Electron version regressions.

**Comment by KeKs0r** [comment] 2018-03-16 13:01
@phoenixgao can your fix from your repository (https://github.com/phoenixgao/electron-high-sierra-build) be applied here?

**Comment by rvielma** [comment] 2018-03-16 14:51
Excellent works, finally everything went back to normal, so many months bad. Thks

**Comment by Azael05x** [comment] 2018-04-03 07:04
Thanks, works for me. Hope it gets fixed soon on master with this solution present.

**Comment by miltonbecker** [comment] 2018-04-17 13:02
@bpasero any chance Microsoft could allocate someone to fix this bug, please? :(

**Comment by ryenus** [comment] 2018-04-17 14:12
It seems already resolved in master since update to Electron 2.0, looking forward to next monthly release:

<img width="362" alt="image" src="https://user-images.githubusercontent.com/610161/38875035-196871a4-428c-11e8-9600-206ef30ea4a0.png">

**Comment by ckerr** [comment] 2018-04-17 16:10
Closing as this is reported fixed in the 2.0.0 betas. Thanks for the update!

**Closed by ckerr** 2018-04-17 16:10 UTC
Labels: bug :beetle:, bug/os-regression, platform/macOS, version/1.7.x

**Comment by johnelm** [comment] 2018-06-01 20:00
Hi @ckerr, can you please re-open this?  Please see @bpasero 's comments.  There's an [Electron 2.0 build of VSCode](https://github.com/Microsoft/vscode/issues/45542), and the native tabs issue is _not_ fixed.

**Comment by philfreo** [comment] 2018-06-01 20:19
Here's a specific and reproducible issue with Tabs in Electron:

https://github.com/electron/electron/issues/13078

**Comment by bpasero** [comment] 2018-06-09 13:41
I am no longer convinced that this is an issue with Electron itself. See the discussion from https://github.com/Microsoft/vscode/issues/35361#issuecomment-395365519 onward.

**Comment by bpasero** [comment] 2018-06-25 16:34
And we know the reason: https://github.com/Microsoft/vscode/issues/35361#issuecomment-399794085
