### ISSUE TITLE
Electron and Multiple BLE Devices

### ISSUE THREAD

**Issue by aramperez** [electron/electron#11865] opened 2018-02-08 22:32 UTC
* Electron version: v1.7.11
* Operating system: Mac OS X v10.13.3

### Expected behavior

Although issue [#7367](https://github.com/electron/electron/issues/7367) is closed, the given solution does not address when there are multiple BLE devices.

Under Google Chrome, when calling the BLE navigator.bluetooth.requestDevice(options) API, Chrome displays a special dialog (attached to the address bar) with showing all the BLE devices that meet the filters in options. You are given the option to select one of the BLE devices. When the [working example with Web Bluetooth API](https://github.com/aalhaimi/electron-web-bluetooth), no special dialog is display, even when clicking the "All Devices" checkbox.

In my house I have two Apple TV devices. Running the samples from [here](https://googlechrome.github.io/samples/web-bluetooth/index.html), they show up. 

### Actual behavior

No special dialog allowing the selection of found BLE devices appears.

### How to reproduce

Run the sample electron app from [here](https://github.com/aalhaimi/electron-web-bluetooth). If there are multiple BLE devices, it is not possible to select one.

**Comment by NAllred91** [comment] 2018-02-13 16:11
@aramperez 

I've found there is an event you can listen for like this, that should let you select devices.  It is documented here https://electronjs.org/docs/api/web-contents
```
webContents.on('select-bluetooth-device', (event, deviceList, callback) => { })
```

Unfortunately, there is a huge delay for the callback being called, so it isn't very useful at the moment..

**Comment by aramperez** [comment] 2018-02-13 16:52
@NAllred91 

Thanks for the info. It's interesting that the documentation states:
> To use navigator.bluetooth api webBluetooth should be enabled.
However, I'm calling 'navigator.bluetooth.requestDevice' (with the 'namePrefix' filter) and I'm connecting to the 'nearest' device (a robot I've built), after a long delay. But I have not enabled the webBluetooth api.

I'll try the sample code to see what happens. It looks like I'll have to create my own dialog to select the device I want. I should point out I'm just learning Javascript (I'm have primarily C/C++ experience), so it will take me a few days.

Thanks,
Aram

**Comment by NAllred91** [comment] 2018-02-13 16:56
@aramperez Yea, I've also noticed that the call to enable web bluetooth doesn't seem to do anything.  it's just enabled by default.

**Comment by aramperez** [comment] 2018-02-13 17:01
@NAllred91, It's probably there for when the Chrome web bluetooth still in [Origin Trials](https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web).

**Comment by aramperez** [comment] 2018-02-16 13:00
@NAllred91, I've been "playing" with the event. At first, I would console.log the event but I wasn't seeing any events. It turns out that the "console" for the "app" context is the terminal window and not the BrowserWindow. The event occurs one time per call to navigator.bluetooth.requestDevice, after the 1+ minute delay. And as pointed out in #10800, it returns duplicates (I haven't experiences the strange addresses). As I've stated, I'm just learning web technologies, so my question is, how do you have the user select from the list of devices when the "app" context doesn't have access to the "DOM" of the BrowserWindow?

**Comment by NAllred91** [comment] 2018-02-16 14:30
@aramperez You can use the ipc objects to communicate between the main process and the render process. http://electron.rocks/different-ways-to-communicate-between-main-and-renderer-process/

**Comment by sofianguy** [comment] 2019-01-07 22:59
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by martpie** [comment] 2019-03-12 14:36
@sofianguy This is reproducible on any version of Electron including 4.0.8.

On Chrome/Chromium, calling 

```
const device = await navigator.bluetooth.requestDevice({
  filters: [{
    namePrefix: 'CT_'
  }]
});
```

will display the following: 

<img width="488" alt="Screen Shot 2019-03-12 at 15 31 02" src="https://user-images.githubusercontent.com/1311607/54208408-28d43300-44dc-11e9-9ab8-0a7dfbe789c4.png">

which allow to specifically choose a device in this list (there is currently only one, but there could be multiple).

Electron on the opposite, **returns the first device found** (or something else, but there is no way to select the device you want to connect to)

Can be reproduced on any Electron installation just by executing the following in the console:
`await navigator.bluetooth.requestDevice({ acceptAllDevices: true });`

**Comment by martpie** [comment] 2019-03-15 09:31
Here is a GIF comparing Chromium (left), and Electron (via `electron-quick-strart`) (right):

![Screen Recording 2019-03-15 at 10 28 44](https://user-images.githubusercontent.com/1311607/54421823-7d122980-470d-11e9-8f27-975adcfc7c0d.gif)

Can this be re-opened @sofianguy ?

**Comment by martpie** [comment] 2019-03-15 10:07
For those looking for a solution, I think the answer is just: implement this device selection yourself:

https://electronjs.org/docs/api/web-contents#event-select-bluetooth-device

In the `.on('select-bluetooth-device')`, you should transmit the list of devices to the renderer process, create a device selector somehow, that will communicate back the selected device to the main process, to finally resolve the `navigator.bluetooth.requestDevice()`

**Comment by Darkle** [comment] 2019-03-15 10:14
> For those looking for a solution, I think the answer is just: implement this device selection yourself:

> electronjs.org/docs/api/web-contents#event-select-bluetooth-device

> In the .on('select-bluetooth-device'), you should transmit the list of devices to the renderer process, create a device selector somehow, that will communicate back the selected device to the main process, to finally resolve the navigator.bluetooth.requestDevice()

I've tried that before and you still seem to only get one device. I had to go back to back to Electron 1.8 to get multiple devices returned.

**Comment by martpie** [comment] 2019-03-15 10:41
`select-bluetooth-device` is triggered each time Chromium discovers new devices, so it happens multiple time per second. So you need to update the device list in your app accordingly.

Also, the example on Electron's website is a bit misleading because of these lines:

```
let result = deviceList.find((device) => {
  return device.deviceName === 'test'
})

if (!result) {
  callback('')
 } else {
  callback(result.deviceId)
}
```

which will return only one or no devies. You need to replace this piece of code by a Promise or some asynchronous code to make sure to call `callback` only when you selected your device.

If you remove the callback calls and add a `console.log(deviceList)`, I can see dozens of devices in my main-process logs.

**Comment by daumling** [comment] 2019-04-02 17:27
On Mac OS 10.14.4 and the latest release 4.1.3, no events are fired at all if I specify two filters. I receive events if I set acceptAllDevices to true. If I specify one filter, sometimes I receive events, and sometimes not. The behavior is strangely unstable. FYI: I have two devices using the Microchip BM77 BLE chip. As said, when I simply pass the first filter entry and nothing else, I see events sometimes.
![filters](https://user-images.githubusercontent.com/15716793/55422988-40ec1f00-557d-11e9-9ed7-1ef377fe10cf.png)

**Comment by electron-triage** [comment] 2020-02-19 23:37
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by daumling** [comment] 2020-02-22 10:29
I guess that it is low priority, but it would be good to implement the workaround as a fix. There is no need for other developers to stumble over this problem over and over again.

**Comment by electron-triage** [comment] 2020-02-26 20:59
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:59 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/macOS, version/1.7.x

**Comment by jastax** [comment] 2022-01-16 17:40
Just a heads up: there is still no device picker with electron 13.1.9. I also do think this should be implemented by electron instead of every developer rolling their own solutions.

Have a nice day :)

**Comment by samjgorman** [comment] 2022-01-28 05:57
@electron-triage Agreed with the comments above on the utility of a device picker and confirm there is no device picker with electron 16.0.8.

![image](https://user-images.githubusercontent.com/31233283/151495040-7a79fc28-676d-4ac8-a15a-eaea4d7e8ae6.png)

**Comment by jastax** [comment] 2022-01-31 06:33
I've implemented it by myself now and it's not that hard, the integration is probably even better now. Still, it's one of the few things where electron did not just work exactly the same way chrome does.

**Comment by POPOBE97** [comment] 2022-03-04 17:17
> I've implemented it by myself now and it's not that hard, the integration is probably even better now. Still, it's one of the few things where electron did not just work exactly the same way chrome does.

> `select-bluetooth-device` is triggered each time Chromium discovers new devices, so it happens multiple time per second. 

⬆️ I would still prefer the Chrome way. It doesn't require users to wait one minute long and gives developers much more flexibility.

**Comment by aramperez** [comment] 2023-09-04 14:09
Sorry I don't have an answer. I gave up on using Electron and went with NativeScript  because this issue was not resolve when I was working on my project.
