### ISSUE TITLE
`electron path/to/app/.` will load `path/to/app.json` instead of app/index / package / etc

### ISSUE THREAD

**Issue by gnarf** [electron/electron#15967] opened 2018-12-06 02:19 UTC
* Output of `node_modules/.bin/electron --version`:
v3.0.7 and v3.0.10 tested
* Operating System (Platform and Version):
Mac

**Expected Behavior**
`electron path/to/app` should load the app in that directory, not a file called `app.json`

**Actual behavior**
Tries to load a file called `app.json` instead of the app

**To Reproduce**

* Clone [electron-quick-start](https://github.com/electron/electron-quick-start) 
* `npm install`
* `npm start` - works in the fresh clone
* `echo "invalid" > ../electron-quick-start.json` (assuming you named the clone electron-quick-start)
* `npm start` - blows up trying to load the json

```
✓ gnarf@pro:electron-quick-start (master=)$ electron .
App threw an error during load
SyntaxError: /REDACTED/electron-quick-start.json: Unexpected token i in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:730:27)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at loadApplicationPackage (/REDACTED/electron-quick-start/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:287:12)
    at Object.<anonymous> (/REDACTED/electron-quick-start/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:328:5)
    at Object.<anonymous> (/REDACTED/electron-quick-start/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
```

note that `npm start` in the quickstart is even using `electron .` - but prefers a file called `${PWD}.json` instead

**Comment by sofianguy** [comment] 2019-08-09 22:22
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by gnarf** [comment] 2019-08-09 22:42
Took me about 2 minutes to follow my instructions again using electron-quick-start repo which is now on 6.0.1

* Given a folder `path/to/app` and a side file called `path/to/app.json` : `electron path/to/app` still trys to load the json instead of the app in the path.

Still an issue, still incorrect

**Comment by gnarf** [comment] 2019-08-09 22:43
Even `electron .` wont run the application if `../$(pwd).json` exists

**Comment by gnarf** [comment] 2019-08-09 22:44
Also my most recent test was on windows - I double checked also on mac - so I assume this is also a bug on linux

**Comment by MarshallOfSound** [comment] 2019-08-09 22:53
This issue described expected behavior / how the node.js module loader works.  E.g. Here is an example using just `node`

![image](https://user-images.githubusercontent.com/6634592/62813061-b5037a00-babd-11e9-9ebd-984921a9b0e3.png)

As you can see it attempted to load the JSON file first before it would even consider searching the child directory.

Closing out as expected behavior

**Closed by MarshallOfSound** 2019-08-09 22:53 UTC
Labels: 3-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS

**Comment by gnarf** [comment] 2019-08-09 23:07
The buggines is that isn't expected `electron ./` should not try to load `../${pwd}.json`

Also: 

```
gnarf@gnarf-PC MINGW64 /c/Code/bocoup/electron-quick-start (master)
$ echo "notjson"> test.json

gnarf@gnarf-PC MINGW64 /c/Code/bocoup/electron-quick-start (master)
$ echo "console.log('yay')" > test/index.js

gnarf@gnarf-PC MINGW64 /c/Code/bocoup/electron-quick-start (master)
$ node
> require('./test/')
yay
{}
```

```
gnarf@gnarf-PC MINGW64 /c/Code/bocoup/electron-quick-start (master)
$ electron test/

App threw an error during load
SyntaxError: C:\Code\bocoup\electron-quick-start\test.json: Unexpected token o in JSON at position 1```

**Comment by gnarf** [comment] 2019-08-09 23:09
So there are two more cases which don't quite follow the "node-require" semantics because you strip trailing "/" and also it would never manage to load `../$(pwd).json` from `require('.')` -- this is just weird and unexpected behavior in general and since you cant end it with a trailing `/` to get around the issue with the node-resolver prefering json you are basically screwed if you want a JSON file with the same name as your app folder.

**Comment by gnarf** [comment] 2019-08-09 23:10
(I found this because I was using a folder.json to contain some checksums of the content i had shipped)

**Comment by gnarf** [comment] 2019-08-09 23:20
`require('path/to/app/')` will NOT load `app.json` but `electron path/to/app/` will

**Comment by MarshallOfSound** [comment] 2019-08-09 23:27
@gnarf Instead of using `require` compare it to `node {path}` the behavior is the same.  Because both `node` and `electron` use some form of `path.resolve()` to find the absolute path you provided so the trailing slash is removed when it is eventually passed to `Module._load`.

E.g. check this out from my previous example

![image](https://user-images.githubusercontent.com/6634592/62813973-98b60c00-bac2-11e9-9801-752cbaf0b13e.png)

**Comment by gnarf** [comment] 2019-08-09 23:30
Weird - learned something today - what an awkward unexpected interface for launching a command with a `path/to/app/` somehow stripping a trailing `/` and adding `.json` but I guess if it works for node :shrug:

😄
