### ISSUE TITLE
Macos, frameless window, -webkit-app-region: drag on fixed height/width not working after resizing the window #electron7.1

### ISSUE THREAD

**Issue by KASOGIT** [electron/electron#21034] opened 2019-11-07 13:51 UTC
### Issue Details

* **Electron Version:** v7.1.0
* **Operating System:** macOS 10.15.1
* **Last Known Working Electron version:** v5.x.x

### Expected Behavior
After manually resizing my window or with electron api func like `maximize` or `setBounds` i would like the `-webkit-app-region: drag` property to keep on working on a title bar with fixed width or/and height.

### Actual Behavior
When opening the app drag works perfectly but once manually resize the window or call size changing electron api func the drag stop working directly.

### To Reproduce
https://github.com/bonjourio/electron-test-repository

`npm install && npm run start`

On the exemple the header has a fixed height of 40px and width 100% when resizing on the width drag works fine after it but after resizing on the height not. You can edit the style in index.html to test different behavior, like: `height: 100%; width: 40px;` = not working after resizing on width.

Best regards.

**Comment by g1eny0ung** [comment] 2019-11-08 01:56
@KASOGIT Same behavior to me.

**Comment by MaximeMarchand** [comment] 2019-11-08 14:37
This is a problem and we will have to postpone our upgrade.

**Comment by m4thieulavoie** [comment] 2019-11-08 16:58
We have the same issue, but when resizing on height. Resizing on width and corners afterwards fixes it.

**Comment by xuzhaobin** [comment] 2019-11-25 10:38
I have the same issue, when leave-full-screen

**Comment by Zei33** [comment] 2019-12-25 07:24
This seems to be an issue with reducing the window height. 

When the height is reduced, the window is no longer draggable.

Expanding the height AND width of the window will restore the usual functionality. This can be done by expanding one edge at a time or both at the same time.

One other thing to note is that the issue is somewhat inconsistent. Most of the time it occurs, but sometimes it doesn't. 

For the record, I'm using electron 7.1.7 on OSX.

**Comment by MaximeMarchand** [comment] 2020-01-10 18:43
Any updates on this one?

**Comment by trungutt** [comment] 2020-02-26 17:08
It seems to be fixed by https://github.com/electron/electron/pull/21723, so normally you shouldn't have this problem anymore after Electron 7.1.9

**Comment by electron-triage** [comment] 2021-03-09 04:01
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 04:01 UTC
Labels: 7-1-x, bug :beetle:, platform/macOS
