### ISSUE TITLE
Changing the "name" attribute in package.json increases start time by 500%

### ISSUE THREAD

**Issue by aicioara** [electron/electron#17810] opened 2019-04-16 15:43 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.4
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**:
  * n/a

### Expected Behavior

When I started the Electron project, it was called `paneer-app`. I renamed it to `andrei-commander` and start time increased from 1 second to 5.

I expect start time to be 1 second. I can achieve that by setting `"name": "paneer-app"` in the `package.json` for the main (renderer does not matter)

### Actual Behavior

Start time is 5 seconds. During these 5 seconds, the original static HTML is loaded, but none of the JS is ran. Also the ChromeDevTools (which I programatically open `win.webContents.openDevTools();` do not show for 5 seconds). I cannot investigate further because ChromeDevTools does not open until the app starts.

### Additional Information

Question: Why would package.json even matter to Electron?

Additionally, in the fast version I get the following errors in the console. 

```
[46632:0416/183738.236025:ERROR:CONSOLE(24)] "Empty response arrived for script 'chrome-devtools://devtools/remote/serve_file/@05ed968b5c3891b34be0facae4ec402bc9b3ad69/product_registry_impl/product_registry_impl_module.js'", source: chrome-devtools://devtools/bundled/shell.js (24)
[46632:0416/183738.243014:ERROR:CONSOLE(108)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (108)
[46632:0416/183738.243104:ERROR:CONSOLE(108)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (108)
[46632:0416/183738.243153:ERROR:CONSOLE(108)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (108)
```

The slow version either **does not** show any errors in the console, or sometimes shows
```
[46671:0416/184401.435808:ERROR:CONSOLE(7830)] "Extension server error: Object not found: <top>", source: chrome-devtools://devtools/bundled/shell.js (7830)
```

### Addons

I have react-devtools and redux-devtools. I added them using `BrowserWindow.addDevToolsExtension` in the past, but now they seem to be "remembered", why is that?

**Comment by nornagon** [comment] 2019-04-16 17:08
I can't reproduce this issue with `electron-quick-start`; changing the package.json there has no effect.

Would you be able to provide a small app, preferably based on `electron-quick-start`, which exhibits this issue? Unfortunately it's difficult for us to narrow down a problem without a reliable reproduction.

**Comment by aicioara** [comment] 2019-04-16 17:32
I cannot reproduce this either outside this one project. All new projects work as expected. I was hoping someone can point me in some direction. As in: why could this even be the case?

**Comment by nornagon** [comment] 2019-04-16 17:36
Without a repro, we can't answer that. You'll have to do some digging on your own, unfortunately :) To the best of my knowledge there's nothing in Electron that would explain the behaviour you're seeing. Possibly one of your dependencies or something in your code is causing the issue.

Closing this for now, but feel free to reopen if you uncover further information that points to a bug in Electron.

**Closed by nornagon** 2019-04-16 17:36 UTC
Labels: blocked/needs-repro ❌

**Comment by aicioara** [comment] 2019-04-16 21:24
I figured out what caused the issue. Hopefully this will help someone some headaches in the future. If you develop an electron app, while also using a "deployed" version of the same electron app, this will cause issues.

For instance, let's say I have an app called andrei-commander. I package it with `electron-packager` and I now have it running in the background all the time. 

In the same time, I continue doing development on the dev version of the next iteration of andrei-commander. Starting the dev version will take a really long time, unless I name it something else inside package.json. The reason `name` is important inside `package.json` is because that will become the name of the app.

To fix this, I have to either name the dev version different or to stop the background one while doing development. 

@nornagon let me know if this issue is worth reopening.

**Comment by nornagon** [comment] 2019-04-16 23:28
It's unclear to mean what you mean by "deployed", but this sounds like an issue specific to your app and not a bug with Electron.

**Comment by jacobpretorius** [comment] 2019-06-04 08:56
Getting the exact same behaviour as @aicioara.
"Deployed" means a version of the app built and packaged for live release with electron-packager. 

So, for example, I use the packager and build v0.1.0 of the app into a .dmg/.exe. I then have v0.1.0 running on my device and I keep it open to test long term stability. In the meantime I go back into the development environment and start making changes to the code and test these with `electron .`, this "dev" version of the app will take anywhere from 10-20 seconds to start with a blank screen showing.

If I on my machine close the built v0.1.0 and then do `electron .` for dev version the dev version opens quickly like it should.

Also getting the error on the dev version (while v0.1.0 built version is NOT running) 

`[28172:0604/094844.464:ERROR:CONSOLE(24)] "Empty response arrived for script 'chrome-devtools://devtools/remote/serve_file/@3db247ef936a47bb9b242fe59d5581dce0f05c4a/product_registry_impl/product_registry_impl_module.js'", source: chrome-devtools://devtools/bundled/shell.js (24)`

if I run both (so slow startup) I do not get the above error.
