### ISSUE TITLE
F12 Developer Tools too slow to be usable

### ISSUE THREAD

**Issue by deejbee** [electron/electron#6806] opened 2016-08-11 08:31 UTC
- Electron version: 1.3.3 electron-prebuilt
- Operating system: Win10

This has started to happen recently.  Developer Tools is unusable as it is so slow.  Task manager also reports high CPU usage when trying to drill down through Elements.  Deleting elements from the tree causes high CPU spikes of 30-40% for several seconds and the Dev tools window is becomes unresponsive.

I haven't been able to determine the version when it started to happen yet but I think it was when I upgraded to v1.  I will try reverting to a pre v1 build to see if it still occurs and report back.

I'm wondering if anyone else has had the same experience?

May be relevant but I have a large project with around 100 scripts in the DOM.

**Comment by deejbee** [comment] 2016-08-11 09:13
I can confirm the downgrading the app to use electron-prebuilt@0.37.0 cures the issue.  Continuing to look back through the change logs now.

**Comment by deejbee** [comment] 2016-08-11 09:58
I can confirm this slowdown issue started at 1.3.0

**Comment by zcbenz** [comment] 2016-08-12 08:04
Can you try opening the page in Chrome 52 browser and see whether it has the same problem?

**Comment by deejbee** [comment] 2016-08-12 09:47
Works fine in Chrome 52 Browser.  Rendering and DevTools were all snappy. I did have to rip out the clientside IPC code to get it working.  Same number of overall scripts included on the page.

**Comment by zcbenz** [comment] 2016-08-17 11:24
Can you provide a reproducible example page that can run in both Chrome 52 and Electron?

**Comment by SCLeoX** [comment] 2016-08-18 14:06
I ran into same problem I think. What information can I provide if I want to help it to get fixed? @zcbenz

**Comment by debussy2k** [comment] 2016-10-17 15:23
I have same problem. It's ok on v1.2.5, but v1.4.1. 
Works fine in my home pc but it's very slow in company's pc with same source code on v4.1.4

**Comment by debussy2k** [comment] 2016-12-07 05:55
This issue is supposed to be related with "inline" source map of typescript.
I changed typescript compiler option as not using inline source map and then slow devtools problem was fixed.

**Comment by jonathansampson** [comment] 2016-12-24 22:34
I'm curious if anybody has identified the root cause behind this issue, or has an idea as to what may be influencing the sluggish behavior.

**Comment by zcbenz** [comment] 2017-05-30 08:15
Closing until more information is provided. Will reopen if anyone can provide a reproducible example here.

**Closed by zcbenz** 2017-05-30 08:15 UTC
Labels: more-information-needed

**Comment by niik** [comment] 2017-05-30 08:19
@zcbenz I was able to reproduce this consistently over in https://github.com/desktop/desktop but only on Windows. The problem went away by itself in one of the subsequent Electron updates and is no longer an issue for us.
