### ISSUE TITLE
electron on docker

### ISSUE THREAD

**Issue by prakash09** [electron/electron#8763] opened 2017-02-24 10:37 UTC
* Electron version: 1.4.15
* Operating system: ubuntu 14.04

### I am trying to run electron app on a docker container with GUI but after "npm install and npm start" I am getting the following error.

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/local/nodejs/bin/node" "/usr/local/nodejs/bin/npm" "start"
npm ERR! node v7.6.0
npm ERR! npm  v4.3.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! helpmebuild-sm-electron@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the helpmebuild-sm-electron@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the helpmebuild-sm-electron package,
npm ERR! not with npm itself.

**Comment by groundwater** [comment] 2017-02-24 19:09
Hi @prakash09. Can you provide a link to your repository? My guess is that this is not a bug with Electron, but configuration problem with either the `Dockerfile` or the application.

I'm going to leave this open, because I would be into developing some user documentation for this scenario.

**Comment by qazbnm456** [comment] 2017-02-25 05:03
@groundwater @prakash09 

I believe that this problem is not related to electron, since I've run my project built with electron version 1.4.15 on docker before and it worked.

**Comment by zcbenz** [comment] 2017-06-12 08:38
Closing until more information is provided.

**Closed by zcbenz** 2017-06-12 08:38 UTC
Labels: more-information-needed
