### ISSUE TITLE
[Bug]: PiP Controls do not work

### ISSUE THREAD

**Issue by PrestonN** [electron/electron#31637] opened 2021-10-29 15:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.6.1

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 34

### What arch are you using?

x64

### Last Known Working Electron version

13.3.0

### Expected Behavior

When playing a video using picture in picture (PiP). I would expect to be able to return the PiP window back to the video player.

### Actual Behavior

PiP mode is enabled as expected, however none of the controls for closing the PiP window or pausing the video works.

### Testcase Gist URL

https://gist.github.com/5ba749964fcd7576b677a3ca93093edd

### Additional Information

I thought that the issue was related to #31448 as both issues occurred in the same versions and fixed in the same version. I wanted to wait until the fix for that issue was released before making this one in hope of this issue also getting fixed. This issue doesn't seem to be present in v15.2.0 after further testing. I couldn't get Electron Fiddle to install v15.3.0 so I couldn't test that one. Let me know if you need any more information from me. Thanks!

**Comment by codebytere** [comment] 2021-11-01 09:26
@PrestonN This works as intended that I can see:
![pip](https://user-images.githubusercontent.com/2036040/139650773-7ca26776-b61c-4377-a7ec-345dfbbb6d01.gif)

**Comment by PrestonN** [comment] 2021-11-01 15:31
Hey there! Thanks for getting back with me.

As I mentioned, I noticed that it worked fine in v15.2.0, however it is not working in v13.6.1. Judging by your gif, it looks like you're also using a variant of v15.

**Comment by zcbenz** [comment] 2021-11-03 00:51
Thanks for reporting back, this is a bug fixed in upstream Chromium, so the only way to fix it in 13 would be backporting the patch from Chromium. However since 13 is now for security patches only, the only solution would be upgrading the Electron instead, so I'm closing this issue.

**Closed by zcbenz** 2021-11-03 00:51 UTC
Labels: bug :beetle:, blocked/need-repro
