### ISSUE TITLE
[Bug]: WebContents.startDrag feature seems to have changed unexpectedly from electron version 19.0.4 to 19.0.5

### ISSUE THREAD

**Issue by takumus** [electron/electron#35264] opened 2022-08-08 14:19 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.5

### What operating system are you using?

macOS

### Operating System Version

Mac OS Montrey 12.2.1 (Apple M1)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

19.0.4

### Expected Behavior

1. This feature should copy the target file.

2. With reference to the sample code:
```js
console.timeEnd('drag2') // line 38 of main.js 
```
This line should be called at the end of dragging.

### Actual Behavior

1. This feature is moving the target file instead of copying. If you run the sample code in the attached Gist URL, you will find that you are unable to drag the same target more than once.

2. With reference to the same sample code as [2.] in Expected Behavior, above:
```js
console.timeEnd('drag2') // line 38 of main.js 
```
This line is being called at the start of dragging, instead of the end.

### Testcase Gist URL

https://gist.github.com/34bc977bc272030760b586d53961e0f1

### Additional Information

The sample code I provided in the Gist URL was created from the official [Sample Code](https://www.electronjs.org/docs/latest/tutorial/native-file-drag-drop) with an addition of `console.time` and `console.timeEnd`

I have a feeling this bug was introduced when merging the following Pull Request:
https://github.com/electron/electron/pull/34615

### Questions:
How can I do the following, like before (in 19.0.4 and earlier versions)
1. Copy the target file on drag
2. Act on the end of the user's dragging

### Behavior on Windows:
In Windows 11, the behavior is as expected, and identical across all Electron versions, including 19.0.4 and 19.0.5.

**Comment by clavin** [comment] 2022-08-08 15:59
Thanks for the report! I was able to reproduce the behavior you described, where the old behavior was to copy the file and the new one moves the file. Looking at the changes between 19.0.4 and 19.0.5, I suspect this was caused by #34615.

@codebytere Was this an intended side effect of refactoring that code?

**Comment by codebytere** [comment] 2022-08-08 17:51
Unfortunately yes - the old APIs are deprecated with no replacement, and the new ones have move behavior.

**Comment by bjorn-nesby** [comment] 2022-09-14 09:15
While I can certainly understand the need to replace outdated APIs, this essentially amounted to a breaking change for us. 
And while it's certainly possible to create a custom native node module to replace the electron drag & drop implementation, I think it would be good if electron aimed for a behavior that is simply consistent across platforms.

**Comment by alan-zhang** [comment] 2022-10-09 12:44
So when this issue will be fixed in coming version?

**Comment by codebytere** [comment] 2022-10-10 14:36
Came up with a fix! PR up shortly.

**Closed** 2022-10-11 16:20 UTC
Labels: platform/macOS, bug :beetle:, component/drag-and-drop, status/confirmed, 19-x-y, 20-x-y
