### ISSUE TITLE
Electron fails to go fullscreen

### ISSUE THREAD

**Issue by jsonnull** [electron/electron#7411] opened 2016-09-29 15:07 UTC
My electron app cannot go in fullscreen mode.

I've tried multiple ways to enter fullscreen:
- Clicking fullscreen button in native frame
- Using `setFullScreen` method on window
- Using `fullscreen` option in BrowserWindow options
- Choosing View -> Enter Full Screen from OS X menu bar

Every time the following happens:
- There's a brief flicker as the content inside the window appears to reflow according to the fullscreen dimensions
- The operating system beeps
- If started with fullscreen option on BrowserWindow, the flicker is white and fullscreen, and then window goes to default size
- If started in windowed mode and try to enter fullscreen by any other means, flicker happens but window dimensions never change

I've tried everything I can think of, from removing drag regions, using native frame, removing width/height from initial BrowserWindow options, nothing seems to work.

I think it is OS related since I'm getting a beep when trying to go fullscreen.

* Electron version: v1.4.1
* Operating system: OS X 10.11.4 El Capitan

**Comment by kevinsawicki** [comment] 2016-09-29 15:46
Are you able to reproduce this using the default app? `npm install electron@1.4.1` and then just run `electron`.

**Comment by jsonnull** [comment] 2016-09-29 17:41
I was able to reproduce using the default app, here's what I ran:

```sh
$ npm install -g electron@1.4.1
$ electron
```

Default app came up, tried to go fullscreen, got the beep.

**Comment by kevinsawicki** [comment] 2016-09-29 17:51
> Default app came up, tried to go fullscreen, got the beep.

I'm having trouble reproducing this, I am able to go fullscreen by clicking the toolbar button, menu item, and keyboard shortcut, I am on 10.11.6.

Might you have some application installed that could be preventing this (because of the beep)? Are you able to take all other apps fullscreen on your machine (like Chrome)?

**Comment by jsonnull** [comment] 2016-09-29 17:54
Just tried Chrome and and it goes fullscreen fine.

I closed any programs that I thought could be causing the issue. Next I'll try on a fresh boot to further eliminate some options.

**Comment by jbleuzen** [comment] 2016-09-30 07:42
@jsonnull Are you starting your electron app from tmux ? There are known bugs with tmux when starting some applications...

**Comment by jsonnull** [comment] 2016-09-30 08:49
> Are you starting your electron app from tmux ? There are known bugs with tmux when starting some applications...

Yes! And I just confirmed this was the issue—when starting electron outside of tmux on the command line, fullscreen works just fine.

**Comment by kevinsawicki** [comment] 2016-09-30 14:54
Closing as duplicate of #2599

**Closed by kevinsawicki** 2016-09-30 14:54 UTC
Labels: more-information-needed
