### ISSUE TITLE
Global shortcut unregisters/disables default actions

### ISSUE THREAD

**Issue by jesperbjerke** [electron/electron#1338] opened 2015-03-31 20:33 UTC
Not sure if this is the intended outcome, but wasnt what I expected;
if I register 'ctrl+c' or 'ctrl+x' as a global shortcut, the system will only listen to that function and not run the default copy/cut-function. I was hoping to bind my listener as an addition to the default function..

**Comment by zcbenz** [comment] 2015-04-01 02:50
This behavior is intended, it sounds good to add a way to invoke default actions though.

**Comment by jesperbjerke** [comment] 2015-04-30 19:04
Any chance for this to be implemented in the near future?

**Comment by tyson-benson** [comment] 2015-07-15 06:35
+1, I want a way to register a global keyboard shortcut without intercepting and preventing the default behaviour. Same example as above, (Ctrl+C).

**Comment by RealOrangeOne** [comment] 2015-11-06 09:19
:+1: Definately a necessary feature, preferably without writing things natively, defeating the 'cross-platform'-ness

**Comment by MadLittleMods** [comment] 2015-12-28 19:07
:+1: I have a similar issue on the NW.js repo: https://github.com/nwjs/nw.js/issues/3503

**Comment by zcbenz** [comment] 2016-05-06 07:01
I have to say this is a very useful feature, but it is impossible with the APIs provided by system, it is by design that registering a global shortcut would disable the default actions.

The only possible way to achieve this is to set global keyboard hooks, which on some platforms would make the app behave like virus, and for others it would require root privilege to run. And it is better to write a node module for this instead of make it a built-in feature of Electron.

So I'm closing this as won't fix.

**Closed by zcbenz** 2016-05-06 07:01 UTC
Labels: enhancement

**Comment by DracotMolver** [comment] 2016-07-18 02:22
I expermient same issue. I'm using ctrl/cmd+F in my application and it replaced the behavior in vscode to search for :/, so bad. There is a way to register this shourtkeys without affecting the whole system and some programs?

**Comment by aAmitSengar** [comment] 2016-09-09 12:54
hey every one i'm new here and i'm just trying to register globalShortcut like 
```javascript
globalShortcut.register('ctrl+F5', function() {
        console.log('ctrl+F5 pressed');
        //mainWindow.webContents.send('global-shortcut', 0);
    });
```

But ctrl+F5 is not working in other applications like  Firefox :( 
i just want to disable Development Tools and want to stop refreshing the page .
Please suggest me 


Thanks in advance

**Comment by RealOrangeOne** [comment] 2016-09-09 14:19
@aAmitSengar Global shortcuts in electron block any other application from listening to that keyboard shortcut. That's what this issue is about. There is currently no fix for this

**Comment by akshayhashedIn** [comment] 2018-07-23 18:33
@Slapbox This might help.
[Recent discussions](https://github.com/electron/electron/issues/8491#issuecomment-274790124)

**Comment by Slapbox** [comment] 2018-07-23 19:07
Thanks @akshayhashedIn!

**Comment by nonoroazoro** [comment] 2021-12-02 08:20
Why this issue is closed while there's no available solution?

**Comment by qssns** [comment] 2022-05-14 11:21
still having this issue, is the solution here yet?

**Comment by 1739616529** [comment] 2022-05-21 04:05
啥时候能有对应的api啊

**Comment by Slapbox** [comment] 2022-05-21 21:10
[It's not going to be addressed](https://github.com/electron/electron/issues/16803#issuecomment-461272250)

**Comment by T31K** [comment] 2022-11-01 15:24
Figured out a work around:
[https://github.com/electron/electron/issues/36204](https://github.com/electron/electron/issues/36204)
