### ISSUE TITLE
[Bug]: Input of certain letters not possible (v15.3.0, Ozone Wayland, Mobian@Pinephone)

### ISSUE THREAD

**Issue by nuehm-arno** [electron/electron#32006] opened 2021-11-26 13:07 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Other Linux

### Operating System Version

Mobian (Debian arm64)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

13?

### Expected Behavior

Input of every letter is possible.

### Actual Behavior

It is currently not possible to enter the letters "z", "o", "x", "é", "ö", "ü" (=Pos1-key), "ô", "W" into the input field in [Axolotl](https://github.com/nanu-c/axolotl) chats using the Pinephone keyboard squeekboard and Electron with the Ozone Wayland backend.

### Additional Information

See [Axolotl bug tracker](https://github.com/nanu-c/axolotl/issues/635) for more info.
Electron v16.0.0 is currently not starting on Mobian@Pinephone using the Ozone Wayland backend.

**Comment by jkleinsc** [comment] 2021-11-30 19:31
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

If the bug you've found can be tested with a pass/fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug by checking your test against different OSes and Electron versions.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2022-01-10 14:41
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-01-10 14:41 UTC
Labels: bug :beetle:, blocked/need-repro
