### ISSUE TITLE
[Bug]: SIGTRAP on callback of registerFileProtocol

### ISSUE THREAD

**Issue by thegnuu** [electron/electron#32915] opened 2022-02-15 17:03 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

unknown

### Expected Behavior

`registerFileProtocol` callback should return the file and not kill the application with a SIGTRAP.

### Actual Behavior

If you try to load a file over a custom file protocol registered with `registerFileProtocol` electron should not crash.

### Testcase Gist URL

https://gist.github.com/1a886dfdf51217d8e8450e3723a0bb63

### Additional Information

Just click "Load iframe" in the Fiddle and Electron will crash, I tested this on windows as well with the same result.

**Comment by mlaurencin** [comment] 2022-02-24 00:52
This appears to be a problem from at least v14. Also Windows fails with `Electron exited with code 2147483651.`

**Comment by dsanders11** [comment] 2022-03-14 07:05
I'm fairly certain this is a duplicate of #28407. Using `registerStringProtocol` here also causes a crash. Changing the gist here to load `index.html` via `my-app://` doesn't crash.

Closing as a duplicate, please ping me if you think this is incorrect.

**Closed by dsanders11** 2022-03-14 07:05 UTC
Labels: platform/windows, platform/macOS, bug :beetle:, status/confirmed, has-repro-gist, 17-x-y

**Comment by george-thomas-hill** [comment] 2022-10-22 18:33
@dsanders11 :

I'm still finding (in Electron 21.2.0) that loading a PDF in an iFrame fails to display the PDF, and loading a PDF in a webview crashes Electron.

Here's an Electron Fiddle gist that demonstrates this:

https://gist.github.com/george-thomas-hill/c3179e6eddeb1a2715201a20dbf95015

Could you please take another look?
