### ISSUE TITLE
spell check doesn't ignore urls and email addresses

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#2334] opened 2015-07-25 11:24 UTC
We have the following code:

``` javascript
require('web-frame').setSpellCheckProvider("en-US", false, {
  spellCheck: function (word) {
    // the spell checking mechanism
  }
});
```
- `isn't` gets wrong highlighting when:
  - spellCheck have been called with `isn` and we return `false`
  - spellCheck have been called with `isn't` and we return `true`

The only way to get correct highlighting for `isn't` is to return true in both cases. However, `isn` is not a correct word so this is somewhat hacky. The same applies for `doesn't`, 'aren't`, 'didn't`, 'wasn't`, etc...

With the current implementation it is also not possible to make an URL or email address valid because the `spellCheck` callback is called individually for `http`, `the-website` and `com`.

---

Solutions for these problems would be to call `spellCheck` callback only when a `Space` have been entered.

**Comment by zcbenz** [comment] 2015-07-28 07:44
This is a duplicate of #1005.

**Comment by astoilkov** [comment] 2015-07-28 08:10
What about the second issue? There is no way to avoid an URL or email highlighted by the spell checker.

**Comment by zcbenz** [comment] 2015-07-28 08:18
Sorry I didn't notice that.

**Comment by codebytere** [comment] 2020-03-30 18:41
This is fixed with the integration of Chromium's built-in spellchecker.

**Closed by codebytere** 2020-03-30 18:41 UTC
Labels: bug :beetle:
