### ISSUE TITLE
Wrong screen detected with getDisplayNearestPoint from mouse XY

### ISSUE THREAD

**Issue by mikoelsuperbeasto** [electron/electron#25690] opened 2020-09-29 18:37 UTC
# Issue Details
Electron version : 10.1.2
Operating System: Windows 10

### Expected Behavior
I created a draggable widget and when i drag it from my primary screen to the second one, it should return the right screen using kind of this code:

`  const currentScreen = getDisplayNearestPoint(getCursorScreenPoint()); `

This was good with electron < 10.

### Actual Behavior
When i drag my mouse around my primary screen to the second, it should return me the right display.

### To Reproduce
My primary screen is using a 100% scaleFactor while my second is at 175%. While i move around my mouse with updated mouse XY to my secondary screen it still return my primary screen as the display nearest point.

**Comment by VerteDinde** [comment] 2020-09-30 04:09
Hey @mikoelsuperbeasto, thanks for reporting this issue! Would it be possible to repro a case of this in a Fiddle? This would help us reproduce and get to the issue more quickly: https://www.electronjs.org/fiddle

**Comment by mikoelsuperbeasto** [comment] 2020-09-30 15:15
Well, i created a fiddle and everything look fine today even in my application without any changes. 

I'm trying to figure out why or what exactly changed from yesterday.

**Comment by codebytere** [comment] 2020-10-22 05:05
Closing as this seems to be resolved but should more information come to light we can reopen this.

**Closed by codebytere** 2020-10-22 05:05 UTC
Labels: 10-x-y, 11-x-y, blocked/need-info ❌, bug :beetle:
