### ISSUE TITLE
problem with "Alt+Shift" key in electron apps

### ISSUE THREAD

**Issue by geeksesi** [electron/electron#17418] opened 2019-03-16 15:39 UTC
* **Electron Version:**
   4.0.^
* **Operating System:**
Ubuntu + Xfce 18.04 x64

hi, when i want to change my keyboard layout with "Alt+Shift" shortcut. in electron apps like 
- [notable](https://github.com/notable/notable)
- [post man](https://www.getpostman.com/)
- [this test](https://github.com/geeksesi/time_reminder)
one menu will open ( check screenshots ).
i don't have any shortcut on my app or OS for this action. 

### Screenshots
![image](https://user-images.githubusercontent.com/28778964/54477533-03b62c00-481e-11e9-8c63-3c1f7402eaa5.png)
![image](https://user-images.githubusercontent.com/28778964/54477564-4b3cb800-481e-11e9-80a6-02fe46b8dec8.png)

### Additional Information
please read this issue : [issue](https://github.com/notable/notable/issues/557)

**Comment by agorf** [comment] 2019-08-11 06:32
Relevant issue #11106

**Comment by alexey-v-paramonov** [comment] 2019-10-22 13:42
Linux Mint 19.2, same problem in Skype, Slack.
Very annoying.

**Comment by MurzNN** [comment] 2020-02-01 09:09
Same problem is on VS Code: https://github.com/microsoft/vscode/issues/85405

**Comment by ToxaZ** [comment] 2020-02-05 17:35
Same on Ubuntu 18.04 both on X11 and Wayland.

**Comment by geeksesi** [comment] 2020-02-05 22:25
guys watch this : https://github.com/notable/notable/issues/557
if you are a developer you can fix it on your app.
also i have this problem in newer version of vscode. i have no idea about vscode.

**Comment by ToxaZ** [comment] 2020-02-06 12:51
@geeksesi There is still an issue for proprietary software like Slack-desktop when you just don't have access to source code.

**Comment by electron-triage** [comment] 2020-02-19 20:50
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by MurzNN** [comment] 2020-02-20 09:31
This issue is still very actual for 6.0 and all newer releases! :( It is reproducibe, for example, in all VS Code 1.40+ versions.

**Comment by caiiiycuk** [comment] 2020-03-10 05:10
Same here on Ubuntu 19.04 with apps: slack, vscode.

**Comment by gocemitevski** [comment] 2020-03-30 07:32
Same here on LinuxMint 19.3 with Slack and VS Code.

**Comment by koshelevdk** [comment] 2020-04-28 15:17
> Same here on LinuxMint 19.3 with Slack and VS Code.
JFYI For Slack there is a workaround - downgrade to version 4.0.2

**Comment by ToxaZ** [comment] 2020-04-28 19:51
> JFYI For Slack there is a workaround - downgrade to version 4.0.2

Worked for me. For users of flatpak slack version downgrade is a little bit tricky: 
`sudo flatpak update --commit=45cd270cb3a69dc2c9c08cd9211068336fdc52ece08c77e5413a44f70e2a0d5b com.slack.Slack`

**Comment by anatoly-kireev** [comment] 2020-09-07 04:22
Do have the same issue Linux Mint 19 and Slack

**Comment by rootcss** [comment] 2020-10-10 18:15
Unfortunately, the issue still persists in all such major apps.

**Comment by geeksesi** [comment] 2020-10-11 05:33
i'm suffering in visual studio code and other electron apps.

**Comment by TheHett** [comment] 2020-10-30 10:08
>_<

**Comment by alon-dotan-starkware** [comment] 2021-01-15 16:30
same here, Fedora 33

**Comment by isaacvonaaron** [comment] 2021-01-19 06:31
Same here, with Ubuntu 20.04.
Most of the world outside the US and EU switches languages with ALT+SHIFT. Although new Windows installations now suggests WIN+SPACE, most users stick to the good old alt+shift even though it's not optimal (why isn't there a "Hebrew" or "Lang1/Lang2" button on the keyboard?).
To reproduce, 
1. Install an extra language, preferably with a non-latin script like Hebrew. 
2. Install gnome-tweak
3. On gnome tweak (Tweaks) - Pick "Keyboard & Mouse" on the left menu, click "Additional Layout Options" , Expand "Switching to another layout", and tick "Alt+Shift"

Now try opening an electron app like RocketChat. Note that on vscode this issue is locally resolved. Use alt+shift and observe the keyboard not typing (because the app menu is now highlighted). Press ESC, type something, and repeat the process

**Comment by gocemitevski** [comment] 2021-03-09 19:20
It's funny that, doing a Shift + Alt does not transfer the focus to the window menu and the problem is gone, but that's a different key combination. I'm using VS Code 1.54.1 on LinuxMint 20.1 (with Cinnamon 4.8.6) and I still have the Alt + Shift problem in it, as well.

**Comment by TheHett** [comment] 2021-03-10 05:29
The problem is already 2 years old, and everyone can not fix it, even maintainers? It's not funny anymore.

**Comment by MurzNN** [comment] 2021-03-10 06:09
Here https://github.com/electron/electron/issues/22213 is similar issue about this problem and it's even closed without any solution! So I fill the fresh new one for actual Electron version: https://github.com/electron/electron/issues/28088

**Comment by nornagon** [comment] 2021-03-15 22:18
Duplicate of #28088

**Closed by nornagon** 2021-03-15 22:18 UTC
Labels: 4-2-x, 6-1-x, bug :beetle:, platform/linux
