### ISSUE TITLE
window.print not work in a pdf view using 9.x version

### ISSUE THREAD

**Issue by FrankWangZY** [electron/electron#26498] opened 2020-11-14 08:46 UTC
### Preflight Checklist

*  [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
*  [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
*  [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
    
   window.print not work in a pdf view using 9.x version. printer doesn‘t give response.  I try to open a pdf file from http service like `http://xxxx/a.pdf`using webview, but get a 0kb blank pdf file ( save as pdf file) when I use window.print() or electron api webview.print()/webcontents.print(),  it seems that the only way to print within a PDF viewer is to click the print icon. 

![image](https://user-images.githubusercontent.com/28087610/99143234-daa30a00-2696-11eb-9ed6-748e4a35e5ae.png)

* **Electron Version:**
   9.3.4
* **Operating System:**
   win 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
print correctly 

### Actual Behavior
not work

**Comment by codebytere** [comment] 2020-11-16 00:55
Duplicate of https://github.com/electron/electron/issues/26448

**Closed by codebytere** 2020-11-16 00:55 UTC

**Comment by FrankWangZY** [comment] 2020-11-17 02:08
Thanks!   one more question, I don't understand the relations between window.print and electron webview.print/webcontent.print, just hope maybe window.print could work  as chrome does, or is there any workaround? that's quite important for me

**Comment by LFdeWeb** [comment] 2021-01-15 13:50
> Thanks! one more question, I don't understand the relations between window.print and electron webview.print/webcontent.print, just hope maybe window.print could work as chrome does, or is there any workaround? @codebytere . for now window.print will cause electron crashed, that's quite important for me

这个解决了吗？
