### ISSUE TITLE
[Windows] Title bar does not respect dark mode

### ISSUE THREAD

**Issue by zlstringham** [electron/electron#23479] opened 2020-05-09 12:17 UTC
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
When setting nativeTheme.themeSource to 'dark' (or 'system' and setting the system theme to 'dark'), the title bar on Windows remains light. On macOS, the title bar accurately reflects the setting.

* **Electron Version:**
  * `npm ./node_modules/.bin/electron --version`: 6.9.0
  * package.json: `"electron": "^8.2.5",`
  * yarn.lock: 8.2.5
* **Operating System:**
  * Windows 10 (1903)

### Expected Behavior

(This works as expected on macOS)
|             | nativeTheme.themeSource = 'system' | nativeTheme.themeSource = 'light' | nativeTheme.themeSource = 'dark' |
|-------------|------------------------------------|-----------------------------------|----------------------------------|
| Light Theme | Light Title Bar                    | Light Title Bar                   | Dark Title Bar                   |
| Dark Theme  | Dark Title Bar                     | Light Title Bar                   | Dark Title Bar                   |

### Actual Behavior

|  | nativeTheme.themeSource = 'system' | nativeTheme.themeSource = 'light' | nativeTheme.themeSource = 'dark' |
|-------------|------------------------------------|-----------------------------------|----------------------------------|
| Light Theme | Light Title Bar | Light Title Bar | Light Title Bar |
| Dark Theme | Light Title Bar | Light Title Bar | Light Title Bar |

### To Reproduce

```js
nativeTheme.themeSource = 'dark'
```

### Screenshots

Command Prompt:
![Command Prompt](https://user-images.githubusercontent.com/4406098/81472203-533a8280-91ab-11ea-9a9d-a3c2229d08ba.png)

File Explorer:
![File Explorer](https://user-images.githubusercontent.com/4406098/81472549-95fd5a00-91ad-11ea-9a4a-7ceef2c5a5a9.png)

Title Bar in Electron with `nativeTheme.themeSource = 'dark'`
![Windows Title Bar](https://user-images.githubusercontent.com/4406098/81472609-1459fc00-91ae-11ea-936a-b0cc0c18a20e.png)

**Comment by miniak** [comment] 2020-06-09 20:58
This is only doable using undocumented APIs for win32 applications
https://stackoverflow.com/questions/53501268/win10-dark-theme-how-to-use-in-winapi
https://github.com/ysc3839/win32-darkmode

**Comment by ckerr** [comment] 2020-08-18 16:14
I have a WIP for this and will push it to a public branch RSN. Hoping to have this ready by the end of the week.

**Comment by ckerr** [comment] 2020-10-13 05:04
I have updated the patch based on review feedback.

In this week's Releases Workgroup meeting, I'll propose its inclusion. The point of contention in review is that a fair amount of private API is necessary to make this work.

**Comment by ckerr** [comment] 2020-10-20 14:32
An agreement has been reached about how to handle use of nonpublic APIs -- this PR will be merged behind a compile-time feature flag.

**Comment by ckerr** [comment] 2020-10-27 14:39
After a few more revision requests, the PR to honor `nativeTheme.themeSource = 'dark'` being called before the Window is created has finally been approved. The backport bot 'trop' can port it from master to 11; I'll backport it to 10 manually.

**Closed** 2020-10-28 20:00 UTC
Labels: 8-x-y, component/native-theme, platform/windows

**Comment by ckerr** [comment] 2020-11-03 00:44
This has been merged into Electron 10, 11, and `master` behind a disabled build flag. It can be enabled by changing `enable_win_dark_mode_window_ui` to `true` in `buildflags/buildflags.gni`.

**Comment by Arjan-Zuidema** [comment] 2020-11-09 11:02
Any chance this will be enabled in pre-built versions so I can actually use this in my projects? I do not like using a custom title bar for Windows only.

**Comment by gpetrov** [comment] 2021-04-23 16:36
Maybe this issue should be reopened as it is still not available in the production builds

**Comment by twitharshil** [comment] 2021-05-06 10:45
@ckerr I tried the flag mentioned [here](https://github.com/electron/electron/issues/23479#issuecomment-720808269) on electron v11.4.4, looks like the issue is partially solved. The right OS theme is applied to the browserWindow title bar at the time when browserWindow is created during the app launch, but the theme change is not getting reflected in the title bar when we switch between the OS theme while the app is already launched. I have tried setting `nativeTheme.themeSource = 'system` and explicitly setting it to dark and light by listening to this [updated event](https://www.electronjs.org/docs/api/native-theme#event-updated) but didn't get any success. 
Check the attached gif that reflects the issue correctly  
![electron-v11-theme-issue](https://user-images.githubusercontent.com/25850676/117285805-0bb20980-ae86-11eb-8fef-16bb83eb325a.gif)

**Comment by jviotti** [comment] 2021-05-06 13:30
@ckerr I haven't spent a lot of time looking at your initial PR, but it seems that the code is only checking the system theme and applying the theme mode on windows creations, i.e.:

```c++
if (message == WM_NCCREATE) {
   ...
}
``` 

From https://github.com/electron/electron/pull/25373/files#diff-9a00c5b8d17617acce09892658a116c0f0f0d03c1cf7e4d59d8247c2ecfa911cR33. 

Based on what @twitharshil , the `nativeTheme` updated event does get correctly triggered, so it might be about adding that same snippet of code in reaction to that event too.

**Comment by bmsuseluda** [comment] 2022-03-16 12:51
Im confused because It is closed but not fixed in the production build.
I hope someone could explain why it is like that.

**Comment by damienallen** [comment] 2022-03-16 13:14
@bmsuseluda Been tracking this for a while and we kinda gave up on this being fixed quickly. I suspect it doesn't help that, at least on the Windows side, the OS-level handling of dark mode seemed a bit shaky to start with. I also remember some old thread saying that there were also changes needed on the Chromium side before this could work in Electron.

I agree this should get re-opened if it's not being tracked elsewhere.

**Comment by damienallen** [comment] 2022-06-20 20:34
@bradmanAWS Sounds like there has been some movement, see: https://github.com/electron/electron/pull/33624
