### ISSUE TITLE
macOS Mojave delay on packaged app when using spawn/exec etc.

### ISSUE THREAD

**Issue by will-stone** [electron/electron#16166] opened 2018-12-20 20:55 UTC
* Output of `node_modules/.bin/electron --version`: v4.0.2
* Operating System (Platform and Version): macOS 10.14.2
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): N/A

**Expected Behavior**
A packaged app and a dev-mode app should execute spawn commands immediately.

**Actual behavior**
Calling spawn in dev-mode happens immediately. However, when an Electron app is packaged it causes spawn commands to have a delay of up 5 seconds (depending on the system).

**To Reproduce**
https://github.com/will-stone/electron-spawn-delay-demo
Please note you will need Firefox installed to run that demo. If you do not want to install Firefox, change this line: https://github.com/will-stone/electron-spawn-delay-demo/blob/master/src/renderer.js#L8

```sh
# Install dependencies with yarn:
$ yarn
# Run in dev mode:
$ yarn start
# Package the app:
$ yarn package
```

**Additional Information**
I am tracking this issue on my app here: https://github.com/will-stone/browserosaurus/issues/77
This only started happening after the upgrade to Mojave; previous versions of macOS did not cause this issue.

**Comment by bengotow** [comment] 2019-01-01 16:59
Hey! Just passing by—I think this might be caused by `tccd`'s database of apps that are allowed to access various system features being corrupted. If this is the case, your packaged app will also be slow to launch itself and the whole OS will appear to "freeze" a bit in the 3-5 seconds it's stuck. 

If that checks out, could you run `tccutil reset All` on the command line and see if that resolves the issue? (NOTE: This will make macOS show you security dialogs all over again, etg: "Can Chrome access your contacts?"

**Comment by will-stone** [comment] 2019-01-01 19:31
Hi @bengotow, thanks for the suggestion but unfortunately that didn't fix the issue.

**Comment by constantincerdan** [comment] 2019-01-05 16:34
This is happening to me too. Using version 4.0.1 of electron and electron-packager 13.0.1. No issues in dev, but once packaged there is a very noticeable delay.

**Comment by sohelsd** [comment] 2019-01-23 00:01
Same issue using electron 4.0.1 and packager 12.2.0.
No issues on dev. Once packaged, calling `exec` on Mojave results in delay of 10 seconds for me.

**Comment by will-stone** [comment] 2019-01-23 22:07
I have bumped the electron version to v4 in my example repo: https://github.com/will-stone/electron-spawn-delay-demo

**Comment by will-stone** [comment] 2019-01-28 11:42
@badouralix and @bitnot have done some analysis (https://github.com/will-stone/browserosaurus/issues/77#issuecomment-458004480) and found the issue to do with unsigned apps. This issue was also afflicting MacVim (https://github.com/macvim-dev/macvim/issues/763) and they solved it by signing the app. Can Electron put some pressure on Apple? After all, not all of us want to pay a yearly subscription to be able to build free software.

**Comment by sohelsd** [comment] 2019-01-29 20:23
Thank you @will-stone !
Your comment made me realize realize I was not signing the app properly. After signing it, it does seem to respond much faster.

**Comment by miniak** [comment] 2019-10-29 12:04
Closing as Electron 4 is not supported anymore (although this seems like an issue not related to Electron version). Also I can see that you've found a fix / workaround for the problem.

**Closed** 2019-10-29 12:03 UTC
Labels: 3-0-x, 4-2-x, bug :beetle:, platform/macOS
