### ISSUE TITLE
Electron 7 BrowserWindow.loadURL with data URL regression

### ISSUE THREAD

**Issue by monsterkodi** [electron/electron#20728] opened 2019-10-24 19:04 UTC
Electron Version 7
Operating System: Windows
Last Known Working Electron version: 6.1.1

Loading from a data URL doesn't work anymore:

win.loadURL('data:text/html;charset=utf-8 ...', {baseURLForDataURL: ... })

**Comment by burningTyger** [comment] 2019-10-25 06:59
#20700 duplicate it seems

**Comment by sofianguy** [comment] 2019-11-06 20:44
duplicate of #20700

**Closed** 2019-11-06 20:43 UTC

**Comment by monsterkodi** [comment] 2019-11-07 08:48
This is not a duplicate of #20700, IMHO.
While the other bug limits the problem to webviews and setting the baseURL
this one tells you that you can't load *any* browser window with data content.
But both bugs are probably caused by the same problem, so I am fine with this being closed, as long as the problem gets fixed :).

**Comment by Aworldc** [comment] 2023-09-11 08:06
not working in electron nightly 28 either.

**Comment by Aworldc** [comment] 2023-09-11 08:23
hangon it is working in nightly 28
im dum
