### ISSUE TITLE
Force touch support

### ISSUE THREAD

**Issue by msavin** [electron/electron#15498] opened 2018-10-31 14:03 UTC
I know that this issue has been discussed many times before, and that it depends on Chromium integrating support for it. However, maybe there can be an easy workaround?

For example: track a force touch on the entire window rather than on a specific element, and have Electron fire events when it is detected?

**Comment by MarshallOfSound** [comment] 2018-11-01 05:45
@msavin That workaround would require users to determine the element that was force touched which is actually a hard problem to solve.

The decision made in #5570 to wait for Chromium to do something is still something we stand by.

Duplicate of #5570

**Closed by MarshallOfSound** 2018-11-01 05:45 UTC

**Comment by brenca** [comment] 2018-11-01 14:41
Would https://pressurejs.com/ work as a workaround for native support? I can't test it since I don't own a force touch enabled device, but it claims to be able to detect it AFAICS.

**Comment by msavin** [comment] 2018-11-01 15:20
It’s a neat library but unfortunately Chrome does not support the features
it requires. It’s really odd - Chrome usually supports everything and more.
I wonder if it’s a political issue with Apple. (That’s why I think Electron
needs to work around all this.)
