### ISSUE TITLE
Could not load flash plugin Electron 6.0.0 Linux

### ISSUE THREAD

**Issue by coreybruce** [electron/electron#19642] opened 2019-08-06 02:16 UTC
Plugin will say cannot load plugin dispite no code has been changed but seems to work on WIndows. flash last worked on Electron 4.2.6 on Linux

E.g:

Gamer World based on Electron 4.2.6 (working Linux)
https://imgur.com/o6dvCP2.png

Gamer World based on Electron 6.0.0 (not LInux)
https://imgur.com/YUrPMs8.png

Gamer World on Electron 6.0.0 on Windows 10
https://i.imgur.com/qquoj9P.png

Code for Flash (code not changed)
`// Specify flash path, supposing it is placed in the same directory with main.js.
const pluginList = {
  'win32':  '/legacy/pepflashplayer.dll',
  'darwin': '/legacy/PepperFlashPlayer.plugin',
  'linux':  '/legacy/libpepflashplayer.so'
}
app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, pluginList[process.platform]))`

**Comment by MarshallOfSound** [comment] 2019-08-06 05:24
This is a duplicate of your own issue #19093 which itself was a duplicate of #18824

**Closed by MarshallOfSound** 2019-08-06 05:24 UTC

**Comment by coreybruce** [comment] 2019-08-07 03:41
This one is more of a update, it now seems to work in Windows but not Linux, maybe it's not correctly reading the path?
