### ISSUE TITLE
Error installing electron on Ubuntu Xenial (Linux version 3.18.0)

### ISSUE THREAD

**Issue by reblevins** [electron/electron#9815] opened 2017-06-20 20:58 UTC
I'm on Linux trying to install electron using: `sudo npm -g install electron@1.7.2`

(I don't normally install using `sudo`, but when I didn't it complained that I should)

and I'm getting the following errors:

```
Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I also tried a plain vanilla: `sudo npm -g install electron` and got the same errors.

* Operating system:
Linux version 3.18.0-14856-g9bbe428768eb (chrome-bot@cros-beefy107-c2) (gcc version 4.9.x 20150123 (prerelease) (4.9.2_cos_gg_4.9.2-r154-32c89c19b042a12b5a1bf0153299154ea5435c03_4.9.2-r154) ) #1 SMP PREEMPT Wed Jun 14 22:13:29 PDT 2017

(I am running inside a chroot on a Chromebook if that makes any difference.)

I have attached the output from /home/username_redacted/.npm/_logs/2017-06-20T14_43_16_506Z-debug.log.

[2017-06-20T14_43_16_506Z-debug.txt](https://github.com/electron/electron/files/1089670/2017-06-20T14_43_16_506Z-debug.txt)

Thanks for your help.

**Comment by jamesla** [comment] 2017-08-27 09:27
+1 on ubuntu 17.04

**Comment by neonfuzz** [comment] 2017-12-21 01:47
I also had this problem on Xenial on a Chromebook. I solved it with `sudo ln -s /usr/bin/nodejs /usr/bin/node`. Apparently node-js uses different names for upstream/downstream versions. There are less janky ways to get this to work (e.g. install node from third-party repositories or compile from source) but this seems to work fine at the moment.

**Comment by aminorex** [comment] 2018-01-26 00:41
This persists in electron@1.7.11:

 sudo npm i -g electron
/usr/bin/electron -> /usr/lib/node_modules/electron/cli.js

> electron@1.7.11 postinstall /usr/lib/node_modules/electron
> node install.js

/usr/lib/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.11 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.11 postinstall script.

**Comment by codebytere** [comment] 2018-02-02 14:40
@neonfuzz has provided the best current solution for this, so i'm going to close it out.

**Closed by codebytere** 2018-02-02 14:40 UTC
Labels: platform/linux, platform/linux/ubuntu, triaged/bug, version/1.7.x

**Comment by ckerr** [comment] 2018-02-02 16:57
@codebytere is right to close this issue, the problem is coming from Debian rather than Electron.

Users who hit this issue may want to check out [the nodejs-legacy package] (https://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu) which does essentially the same thing so that you don't have to tinker around in /usr/bin with sudo. :smile: 

If a Debian user/maintainer has dealt with this in other Node packages and wants to submit a PR that would make this work on all systems, I'd be receptive to that. The issue is coming from `npm/package.json` which has this entry:

```json
  "scripts": {
    ...
    "postinstall": "node install.js",
    ...
  },
```

If this were changed to read `nodejs install.js`, this would break everywhere _but_ Debian.
