### ISSUE TITLE
Electron title on frameless with transparency 

### ISSUE THREAD

**Issue by Aduentix** [electron/electron#12033] opened 2018-02-24 06:28 UTC
So I'm pretty much at the end here.
Every time I make the browser window transparent, a wired title appears.
So in it is the HTML title and when I remove it says index.html or the folder/package name.
(this sort of thing just appears, when I unfocus and focus the app again.

![capture](https://user-images.githubusercontent.com/32692451/36626489-1502c1cc-1934-11e8-9600-0f43a4d1b386.PNG)

Best Regards

Elias

**Comment by brenca** [comment] 2018-02-24 07:54
What version of electron are you on? This should be fixed on 2.0.x and in the next 1.8 release (1.8.3).

**Comment by brenca** [comment] 2018-02-24 07:56
Closing as a duplicate of #11849

**Closed by brenca** 2018-02-24 07:56 UTC

**Comment by iamisti** [comment] 2023-11-09 07:48
this is happening again

**Comment by hjiachuang** [comment] 2023-12-01 05:43
![image](https://github.com/electron/electron/assets/37433108/86dd160b-2dc4-44fd-bdad-7b542169da2a)
this is happening again with electron 27.1.2

**Comment by buithaibinh** [comment] 2023-12-28 08:56
still not fixed in electron 28.0.0

**Comment by ararif724** [comment] 2024-07-07 09:39
Still not fixed in electron 31.1.0

**Comment by ararif724** [comment] 2024-07-07 10:07
I found a hotfix if I disable hardware acceleration the issue disappear.

`app.disableHardwareAcceleration();`

@hjiachuang @iamisti @buithaibinh
