### ISSUE TITLE
PDF download button doesn't work

### ISSUE THREAD

**Issue by Shandawei** [electron/electron#23885] opened 2020-06-01 16:58 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0
* **Operating System:**
  * 10.15.5
* **Last Known Working Electron version:**
  * no

### Expected Behavior
show the download file dialog

### Actual Behavior
nothing happened

### To Reproduce
use the follow config to load remote `pdf`
```
 frame: true,
      fullscreenable: true,
      width: 500,
      height: 600,
      resizable: true,
      backgroundColor: '#ffffff',
      webPreferences: {
        plugins: true,
        nodeIntegration: true,
        contextIsolation: false,
        javascript: true,
        webSecurity: true,
        allowRunningInsecureContent: true,
      },
      show: false
```
```
    pdfWindow.webContents.loadURL(url);

```

[https://gist.github.com/c09409811c4264df06535f24cfd7194d](https://gist.github.com/c09409811c4264df06535f24cfd7194d)

**Comment by codebytere** [comment] 2020-06-03 20:39
Duplicate of https://github.com/electron/electron/issues/22178.

**Closed by codebytere** 2020-06-03 20:39 UTC
