### ISSUE TITLE
Auto-updater not relaunching/updating

### ISSUE THREAD

**Issue by ghego1** [electron/electron#6345] opened 2016-07-04 17:31 UTC
- Electron version: 1.2.5
- Operating system: MacOSX 10.11.5

I had implemented the autoupdate functions correctly, and I was using them with Electron 0.37.8.

Then I bumped up to 1.2.5 and `var autoUpdater = require('auto-updater');` was not working anymore. So I switched to `var autoUpdater = electron.autoUpdater;`.

Then I tried to see if everything was working, but unfortunately it isn't.

The app does download the new zip file, and does quit after the download has finished, but it never relaunches and it does not install the update.

To Update I tried several solutions, none of which work.

```
autoUpdater.addListener("update-downloaded", function (event, releaseNotes, releaseName, releaseDate, updateURL, quitAndUpdate) {

        // simple call to quitAndInstall method - does not relaunch nor update
        autoUpdater.quitAndInstall();

        // call to function passed by event listener - does not relaunch nor update
        quitAndUpdate();

        /*
        // Same, but with confirm dialog - does not relaunch nor update
        var options = {
            type: 'info',
            buttons: ['Restart', 'Later'],
            title: "Enoron",
            message: 'The new version has been downloaded. Restart the application to apply the updates.',
            detail: releaseName + "\n\n" + releaseNotes
        };
        dialog.showMessageBox(options, function(response) {
            if (response == 0) {
                autoUpdater.quitAndInstall();
            }
        });
        */
    });
```

**Comment by zcbenz** [comment] 2016-07-05 01:30
Can you try whether 1.2.4 works?

**Comment by claygriffiths** [comment] 2016-07-07 04:41
I'm having the same problem as @ghego1. I'm usually seeing the following error:

7/6/16 10:29:40.605 PM ShipIt[8038]: Installation error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={NSLocalizedDescription=Permission denied}

This search always shows issues popping up regarding non-admin accounts but I am on an admin account and this is happening even inside of my user directory.

**Comment by craigp** [comment] 2016-07-08 10:39
> Can you try whether 1.2.4 works?

I am having this problem on 1.2.5, but it does work properly in 1.2.4, I've just tried it.

**Comment by ghego1** [comment] 2016-07-08 10:42
@craigp thanks for trying that, I did not had a chance to test it yet...

**Comment by zcbenz** [comment] 2016-07-08 12:18
It seems to be related to the update of Squirrel.Mac. /cc @joshaber

**Comment by joshaber** [comment] 2016-07-08 13:30
@craigp @ghego1 Let's try to find more logs. Go to `~/Library/Application Support/your-bundle-id.ShipIt` and `~/Library/Caches/your-bundle-id.ShipIt` and check out the logs in there.

**Comment by fantasticsid** [comment] 2016-08-04 00:50
Having the same issue on OSX 10.11.5

**Comment by fantasticsid** [comment] 2016-08-04 00:51
There wasn't much log generated related to this as far as I can see. Though I do see an extracted app binary under ~/Library/Application Support/your-bundle.ShiptIt/updatexxxxx/

**Comment by joshaber** [comment] 2016-08-04 01:02
Try updating to Electron 1.3+. If you're still seeing the problem, your logs should be in `~/Library/Caches/your-bundle.ShiptIt` (note that the location changed).

**Comment by fravic** [comment] 2016-08-05 22:38
Also having the same problem with Electron 1.2.4, 1.2.8, and 1.3.2 on OS X 10.11.5.

I'm seeing an error in the logs:
```
Couldn't remove owned bundle at location file:///var/folders/T/your-bundle.ShipIt/AppName.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“AppName.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }
```
But it then says after that the `Installation completed successfully`, so I don't think it's relevant.

My updater code:
```
  autoUpdater.setFeedURL(config.macUpdateUrl + '/' + appVersion);
  autoUpdater.addListener('update-downloaded', function(e, releaseNotes, releaseName, releaseDate, updateURL, quitAndInstall) {
    var index = dialog.showMessageBox(mainWindow, {
      type: 'info',
      buttons: ['Restart', 'Later'],
      message: 'A new version is available! Please restart the app to apply the updates.',
      detail: releaseName + "\n\n" + releaseNotes
    });
    if (index !== 1) {
      quitAndInstall();
    }
  });
  autoUpdater.checkForUpdates();
```

**Comment by CyanCorsair** [comment] 2016-08-11 15:18
I have a similar issue. The autoUpdater gets stuck at update-available on both Windows 7 and MacOS 10.10.5, Electron 1.3.2). It basically emits that [update-available] event - downloads the update, installs it - and then refuses to proceed. It will not, in any way, fire update-downloaded. The app is fully signed, I tried granting it the proper chown and chmod on Mac, kept it in the Application's folder like a regular user would. Nothing.

I've been banging my head against this for the past 3 days. Any help? My ShipIt_Stderr.log outputs the same as the above: Couldn't remove owned bundle at location ... error NSError code 4, "The File doesn't exist".

If I then shut down the app and relaunch it, manually, it will have successfully updated, as ShipIt in its logs also report that "Installation completed successfully" - "ShipIt quitting". How can I provide my user with a good notification that they should restart, if the events do not propagate properly?

**Comment by cumajkeee** [comment] 2016-08-26 09:28
Did anybody can confirm than problem solved in 1.3.3/4?

In 1.2.7 can confirm error in ShipIt/stderr.log with "File not found", and all process of auto update of application can finish with 3 results:

1. Success: updated and app restarted
2. Fail: app not updated but restarted (rear, but reproducible, all process of auto update passed well, except error with "File not found" which is not affect, as I understand, update process) 
3. Fail: app not updated and doesn't restarted (found once, not sure is it updater issue)

**Comment by fantasticsid** [comment] 2016-09-08 19:48
This still happens with 1.3.3


```
2016-09-08 11:00:59.620 ShipIt[14545:269605] Beginning installation
2016-09-08 11:01:01.656 ShipIt[14545:269606] Moved bundle from file:///Applications/Cal.app to file:///var/folders/4x/fpvqvdvd7z5fzz7x5rm4z73clntvfz/T/Cal.ShipIt.joQfyCSY/Cal.app
2016-09-08 11:01:01.656 ShipIt[14545:269606] Moved bundle from file:///var/folders/4x/fpvqvdvd7z5fzz7x5rm4z73clntvfz/T/Cal.ShipIt.8opbMw2n/Cal.app to file:///Applications/Cal.app
2016-09-08 11:01:01.690 ShipIt[14545:269606] Couldn't remove owned bundle at location file:///Users/zhenchao/Library/Caches/Cal.ShipIt/update.CC2zIay/Cal.app/, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Cal.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/Users/zhenchao/Library/Caches/Cal.ShipIt/update.CC2zIay/Cal.app";
    NSUserStringVariant =     (
        Remove
    );
} }
2016-09-08 11:01:01.719 ShipIt[14545:269606] Couldn't remove owned bundle at location file:///var/folders/4x/fpvqvdvd7z5fzz7x5rm4z73clntvfz/T/Cal.ShipIt.8opbMw2n/Cal.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Cal.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/4x/fpvqvdvd7z5fzz7x5rm4z73clntvfz/T/Cal.ShipIt.8opbMw2n/Cal.app";
    NSUserStringVariant =     (
        Remove
    );
} }
2016-09-08 11:01:01.748 ShipIt[14545:269606] Installation completed successfully
2016-09-08 11:01:01.748 ShipIt[14545:269606] ShipIt quitting
```

**Comment by fantasticsid** [comment] 2016-09-09 18:42
Hmm, some updates:

The app updated itself yesterday. I don't see any difference in logs. This is still updating from and to electron 1.3.3.

@joshaber do you think it might have something to do with 413b1d2bca22e4c73d88989c40dbbe5d36c8e9c7 ?

**Comment by paul321** [comment] 2016-09-14 07:57
I'm having the same problem with 1.2.5, is this fixed in 1.3.5?

**Comment by joshaber** [comment] 2016-09-14 12:06
>@joshaber do you think it might have something to do with Squirrel/Squirrel.Mac@413b1d2 ?

It's certainly possible, but given that some folks are reporting it in 1.2.6 makes me think it's something else.

**Comment by paul321** [comment] 2016-09-14 13:40
We were using 1.2.6 for 2 months now and we got out few updates, everything worked perfectly, after the last OSX update the app has problems updating, i think this is related to Squirrel. See this issue regarding Squirrel logs:
https://github.com/Squirrel/Squirrel.Mac/issues/181

**Comment by paul321** [comment] 2016-09-23 09:33
It seems the problem is that we changed the codesign certificate that has other identity, the updater fails to install the new certificate :)

**Comment by ghego1** [comment] 2016-09-23 09:39
In our case my feeling is that this issue is due to the fact that we build the app also with xcode (macgap). It has a different `bundle identifier`, but the app name and certificate used are the same.
Does this sound like a plausible cause?

**Comment by danielsht86** [comment] 2016-09-27 18:36
Also running into this issue with Electron 1.4.0 and MacOS 10.12

I am running as an Admin user and have installed the application in /Applications

My system.log is filled with these as some others have reported:
```
Sep 27 11:29:02 Daniels-MacBook-Pro-15 com.apple.usbmuxd[98]: HandleUSBMuxConnect Client 0x7faa44f0a470-SketchMirrorHelper/NULL requesting attach to 0x176:55334 failed, no such device
Sep 27 11:29:03 Daniels-MacBook-Pro-15 com.apple.usbmuxd[98]: HandleUSBMuxDictionary client 0x7faa44f0a470-SketchMirrorHelper/NULL using library 1, running usbmuxd-374.70
Sep 27 11:29:03 Daniels-MacBook-Pro-15 com.apple.usbmuxd[98]: HandleUSBMuxConnect Client 0x7faa44f0a470-SketchMirrorHelper/NULL requesting attach to 0x176:55334 failed, no such device
Sep 27 11:29:03 Daniels-MacBook-Pro-15 com.apple.xpc.launchd[1] (ai.ark.arkIDE.ShipIt[57611]): Service could not initialize: 16A323: xpcproxy + 11769 [1475][625A730D-D6CA-3B26-ABFC-E0FD9005BAB6]: 0xd
Sep 27 11:29:03 Daniels-MacBook-Pro-15 com.apple.xpc.launchd[1] (ai.ark.arkIDE.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
```

Also ~/Library/Caches/ai.ark.arkIDE.ShipIt/ShipIt_stderr.log show the following, which was only logged the first time I attempted an update. This log is no longer being populated, most likely since  the service is crashing or not running

```
2016-09-22 13:47:07.820 ShipIt[12939:865137] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fda9e2012b0 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist, NSUnderlyingError=0x7fda9e200560 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2016-09-22 13:47:07.820 ShipIt[12939:865137] ShipIt quitting
2016-09-22 13:47:09.852 ShipIt[12940:865177] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7f80b65154f0 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist, NSUnderlyingError=0x7f80b6513e60 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2016-09-22 13:47:09.852 ShipIt[12940:865177] ShipIt quitting
2016-09-22 13:47:11.892 ShipIt[12941:865223] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fae6db09b20 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist, NSUnderlyingError=0x7fae6db0a8d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2016-09-22 13:47:11.893 ShipIt[12941:865223] ShipIt quitting
2016-09-22 13:47:13.928 ShipIt[12945:865311] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fea08500fe0 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist, NSUnderlyingError=0x7fea08500e70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2016-09-22 13:47:13.928 ShipIt[12945:865311] ShipIt quitting
2016-09-22 13:47:15.955 ShipIt[12946:865320] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7f81c0f1e6b0 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist, NSUnderlyingError=0x7f81c0f1cfe0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2016-09-22 13:47:15.955 ShipIt[12946:865320] ShipIt quitting
```

I can confirm that there is no file at `/var/root/Library/Caches/ai.ark.arkIDE.ShipIt/ShipItState.plist`

This is not happening for everyone on our team. Any ideas/thoughts/clues?

**Comment by danielsht86** [comment] 2016-09-27 20:34
Quick update: Deleting ~/Library/Caches/ai.ark.arkIDE.ShipIt and ~/Library/Caches/ai.ark.arkIDE and restarting fixed the issue. Not sure what caused it but hopefully this information is helpful to figuring out the root cause

**Comment by kevinsawicki** [comment] 2016-11-16 23:34
The Electron version that came out today, 1.4.7, upgraded to Squirrel.Mac@0.3.0. Are people still experiencing this issue or has it gone away on 1.4.x? If you are still experiencing it, can you try 1.4.7 and see if it is working there? Thanks.

**Comment by nkt** [comment] 2017-01-07 02:18
Still present. Code:
```js
autoUpdater.on('update-downloaded', (event, notes, version) => {
  const window = getAppWindow();
  if (window) {
    dialog.showMessageBox(window, {
      type: 'question',
      cancelId: 0,
      defaultId: 1,
      buttons: [
        translator.translate('update_cancel'),
        translator.translate('update_submit')
      ],
      message: translator.translate('update_question', { appName, notes, version })
    }, (shouldUpdate) => {
      if (shouldUpdate) {
        autoUpdater.emit('quit-and-install');
        autoUpdater.quitAndInstall();
      } else {
        autoCheck = false;
      }
    });
  }
});
```

After `quitAndInstall` call nothing happens. If I'm closing app using cmd+Q/quit in dock, app reopening with new version.

**Comment by stouch** [comment] 2017-01-18 10:34
I experience same problem as fantasticsid (8 Sep 2016).

2016-11-05 17:17:49.632 ShipIt[4132:2188928] Couldn't remove owned bundle at location file:///var/folders/sg/nh8znnm10hzg2h9tx75f21480000gn/T/<bundleid>.ShipIt.nqdkAhGh/<appname>.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“<appname>” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/sg/nh8znnm10hzg2h9tx75f21480000gn/T/<bundleid>.ShipIt.nqdkAhGh/<appname>.app";
    NSUserStringVariant =     (
        Remove
    );
} }

I use Electron 1.4.8

Code (called after update downloaded).
My app is just minimized but doesn't relaunch and I need to kill/launch it manually one or several times before it updates.

```
    autoUpdater.quitAndInstall()

    // I tried this below : doesnt work either
    setTimeout(function(){
      app.relaunch({args: process.argv.slice(1).concat(['--relaunch'])})
      app.exit(0)
    },1000);

```

**Comment by 0x00A** [comment] 2017-03-27 16:17
When I open `console.app` to watch the activity from autoupdater, i thinks my app is called `Beaker Browser` haha. Its definitely called `Voltra`. Yes, I use Beaker Browser. I have it installed. It's not open though. I uninstalled it and tried again. I also tried restarting my system. No luck, when i try to update it fails. In fact, the path that is referred to no longer exists, but it is still appearing in the logs.

These logs are pretty interesting...
![image](https://cloud.githubusercontent.com/assets/136109/24365656/07d3e4c8-1317-11e7-8ebf-165106596ee1.png)

**Comment by codebytere** [comment] 2017-09-27 01:18
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:18 UTC
Labels: component/auto-updater, more-information-needed

**Comment by theuniverse** [comment] 2017-12-11 09:27
@stouch May I know how you solved your problem at last?

**Comment by FanShiDe** [comment] 2018-10-18 06:57
electron-updater: v3.1.2
electron-builder: 19.5.2 or 20.26.0
```js
[2018-10-18 14:35:32:0776] [warn] Error: No update available, can't quit and install
    at MacUpdater.quitAndInstall (/Applications/WOOKONG Solo.app/Contents/Resources/app/node_modules/electron-updater/src/MacUpdater.ts:149:24)
    at Timeout._onTimeout (/Applications/WOOKONG Solo.app/Contents/Resources/app/dist/main.js:864:45)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

upgrade `electron-builder` version to the latest，for me，it is working now :smile: 
the reason why i use `electron-updater@3.1.2` is use `__update__` path to verify download file

**Comment by alexanderturinske** [comment] 2019-12-06 23:10
On electron v6.1.4 and getting this issue.
```
2019-12-06 15:01:34.060 ShipIt[43055:761200] Beginning installation
2019-12-06 15:01:37.054 ShipIt[43055:761078] Moved bundle from file:///Applications/MyApp.app/ to file:///var/folders/j1/8l7658ts4clgsxr4lt9hjgcc452cwr/T/com.electron.pix.ShipIt.gvraoNpy/MyApp.app
2019-12-06 15:01:37.054 ShipIt[43055:761078] Moved bundle from file:///var/folders/j1/8l7658ts4clgsxr4lt9hjgcc452cwr/T/com.electron.pix.ShipIt.uFlFtIKm/MyApp.app to file:///Applications/MyApp.app/
2019-12-06 15:01:37.229 ShipIt[43055:761078] Couldn't remove owned bundle at location file:///var/folders/j1/8l7658ts4clgsxr4lt9hjgcc452cwr/T/com.electron.MyApp.ShipIt.uFlFtIKm/MyApp.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“MyApp.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/j1/8l7658ts4clgsxr4lt9hjgcc452cwr/T/com.electron.MyApp.ShipIt.uFlFtIKm/MyApp.app";
    NSUserStringVariant =     (
        Remove
    );
} }
2019-12-06 15:01:37.322 ShipIt[43055:761078] Installation completed successfully
2019-12-06 15:01:37.323 ShipIt[43055:761078] ShipIt quitting
```
the new app does update, but doesn't restart.
Didn't change the codesigning when this started
Any suggestions?

**Comment by zdQAQ** [comment] 2020-07-06 09:34
> On electron v6.1.4 and getting this issue.
> 
> ```
> 2019-12-06 15:01:34.060 ShipIt[43055:761200] Beginning installation
> 2019-12-06 15:01:37.054 ShipIt[43055:761078] Moved bundle from file:///Applications/MyApp.app/ to file:///var/folders/j1/8l7658ts4clgsxr4lt9hjgcc452cwr/T/com.electron.MyApp.ShipIt.gvraoNpy/MyApp.app
> 2019-12-06 15:01:37.054 ShipIt[43055:761078] Moved bundle from file:///var/folders/j1/8l7658ts4clgsxr4lt9hjgcc452cwr/T/com.electron.MyApp.ShipIt.uFlFtIKm/MyApp.app to file:///Applications/MyApp.app/
> 2019-12-06 15:01:37.229 ShipIt[43055:761078] Couldn't remove owned bundle at location file:///var/folders/j1/8l7658ts4clgsxr4lt9hjgcc452cwr/T/com.electron.MyApp.ShipIt.uFlFtIKm/MyApp.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“MyApp.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
>     NSFilePath = "/var/folders/j1/8l7658ts4clgsxr4lt9hjgcc452cwr/T/com.electron.MyApp.ShipIt.uFlFtIKm/MyApp.app";
>     NSUserStringVariant =     (
>         Remove
>     );
> } }
> 2019-12-06 15:01:37.322 ShipIt[43055:761078] Installation completed successfully
> 2019-12-06 15:01:37.323 ShipIt[43055:761078] ShipIt quitting
> ```
> 
> the new app does update, but doesn't restart.
> Didn't change the codesigning when this started
> Any suggestions?

did you solve it ? I got the same err.

**Comment by calebl** [comment] 2020-08-05 14:39
@zdQAQ I seem to be running into a similar issue, but I can't find the logs. Where are you finding the log output for mac?

**Comment by zdQAQ** [comment] 2020-09-15 07:54
@calebl check this folder``` ~/Library/Caches/your-bundle.ShiptIt ```
