### ISSUE TITLE
[Bug]: SIGTRAP after loadURL of text/html data URI

### ISSUE THREAD

**Issue by exander77** [electron/electron#31779] opened 2021-11-09 23:08 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

All versions in electron-fiddle

### What operating system are you using?

Ubuntu

### Operating System Version

21.10

### What arch are you using?

x64

### Last Known Working Electron version

I think it worked in version 11, but it is not in fiddle anymore...

### Expected Behavior

Electron should not be a crashing simulator.

### Actual Behavior

Electron is a crashing simulator.

### Testcase Gist URL

https://gist.github.com/63fa86785e3638ae1a7c673c4bed7c7d

### Additional Information
Does not crash if `baseURLForDataURL` is not set.
```
    baseURLForDataURL: `file://${__dirname}/`
```

**Comment by codebytere** [comment] 2021-11-10 08:37
Duplicate of https://github.com/electron/electron/issues/28765

**Closed by codebytere** 2021-11-10 08:37 UTC
Labels: bug :beetle:
