### ISSUE TITLE
[Help]instance of FormData result false in electron

### ISSUE THREAD

**Issue by highalps** [electron/electron#9060] opened 2017-03-30 02:17 UTC
* Electron version: 1.4.6
* Operating system: mac OS Sierra 10.12.2

### Expected behavior

when sending formData  like this

```
 const formData = new window.FormData()
 formData.append('file', file)
 post(url, formData)
```

and post method look like (using typescript)

```
 post(url: String, body?: Object | FormData) {
  
  if(body instanceof FormData) {
   ......
 }

   .........
}

```

in web, if statement result true.
so i expected true in electron, but false

### Actual behavior

web : instanceof FormData // true
electron: instacneof FromData // false (expected true)

**Comment by MarshallOfSound** [comment] 2017-03-30 04:11
Admittedly tested this on `1.4.13` but I can't repro this issue, can you provide code that has this issue to test with please 👍 

<img width="912" alt="screen shot 2017-03-30 at 3 10 08 pm" src="https://cloud.githubusercontent.com/assets/6634592/24487414/065a3d04-155b-11e7-881d-9bc5bcbc49ac.png">

**Comment by highalps** [comment] 2017-03-30 06:38
@MarshallOfSound 

thk, but that is not what i mean
post method using typescript like this

```
    post(url: String, body?: Object | FormData) {
       console.log(body, instanceof FormData)
        if (body instanceof FormData) {
            return ......
        }
       return .....
    }

```

when function received FormData as parameter,  web(Chrome, Safari..) logging "FormData, true". but debugging in electron,  logged "FormData, false"

problem is occurred when using console.log in source code not only using Development tool's Console.

though I am poor at English, thank you for reading.

**Comment by kevinsawicki** [comment] 2017-04-27 21:37
@highalps can you provide a more complete example that demonstrates this issue?

This is the file I tried and could not reproduce the issue:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script>
      function post (form) {
        if (form instanceof FormData) {
          alert('form instanceof FormData')
        } else {
          alert('form not instanceof FormData')
        }
      }

      const formData = new window.FormData()
      formData.append('foo', 'bar')
      post(formData)
    </script>
  </head>
  <body>

  </body>
</html>
```

**Comment by kevinsawicki** [comment] 2017-05-31 15:57
Closing this out until more information is available.

**Closed by kevinsawicki** 2017-05-31 15:57 UTC
Labels: more-information-needed
