### ISSUE TITLE
[Bug]: Hardened runtime causes blank screen in MAS app on Apple Silicon

### ISSUE THREAD

**Issue by buu700** [electron/electron#29102] opened 2021-05-11 16:03 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Using my app via the Mac App Store, which is a universal build with hardened runtime enabled, should work as expected.

### Actual Behavior

The app initially appears to work for maybe a few hundred ms, and then the window goes blank (aside from retaining the background color set by the app's CSS).

However, the problem is only reproducible on Apple Silicon, not Intel. I can also confirm that disabling the hardened runtime resolves the immediate issue. Unfortunately, I'm not sure whether the problem also affects x86 builds running through Rosetta 2.

Parent entitlements:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>com.apple.security.app-sandbox</key>
		<true/>
		<key>com.apple.security.application-groups</key>
		<array>
			<string>SXZZ8WLPV2.com.cyph.desktop</string>
		</array>
		<key>com.apple.security.cs.allow-dyld-environment-variables</key>
		<true/>
		<key>com.apple.security.cs.allow-jit</key>
		<true/>
		<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
		<true/>
		<key>com.apple.security.cs.disable-library-validation</key>
		<true/>
		<key>com.apple.security.device.audio-input</key>
		<true/>
		<key>com.apple.security.device.camera</key>
		<true/>
		<key>com.apple.security.device.microphone</key>
		<true/>
		<key>com.apple.security.files.user-selected.read-only</key>
		<true/>
		<key>com.apple.security.files.user-selected.read-write</key>
		<true/>
		<key>com.apple.security.network.client</key>
		<true/>
	</dict>
</plist>
```

Child entitlements:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>com.apple.security.app-sandbox</key>
		<true/>
		<key>com.apple.security.inherit</key>
		<true/>
		<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
		<true/>
		<key>com.apple.security.cs.disable-library-validation</key>
		<true/>
	</dict>
</plist>
```

**Comment by jkleinsc** [comment] 2021-05-12 14:42
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by buu700** [comment] 2021-05-12 19:00
Thanks @jkleinsc. What would be the recommended way to set up a reproducible test case?

I can export the hello world project for Electron Forge and set hardened runtime to enabled, but as per https://www.electronjs.org/docs/tutorial/code-signing#electron-forge that would require knowing the signing information for the person who will be attempting the test case, unless there's some way to test hardened runtime directly within Electron Fiddle that I'm not seeing.

**Comment by jkleinsc** [comment] 2021-05-13 01:26
@buu700 https://www.electronjs.org/docs/tutorial/code-signing#electron-forge notes that:

> Your app may crash. See the Resource Access section in Hardened Runtime for more information and entitlements you may need.

So it is possible your app needs additional entitlements.  It is really difficult for us to narrow down the problem without some details about what your application is trying to do, which is why the request for a reproducible test case.  If you can reproduce the problem with electron forge/fiddle hello world, then please let us know that; otherwise we would need a test case that reproduces the problem.

**Comment by jkleinsc** [comment] 2021-05-13 01:27
Just a followup - we don't need a hardened runtime/signed app - just the app code that when hardened causes the issue.

**Comment by buu700** [comment] 2021-05-13 04:31
Got it, thanks for clarifying that. I adapted the project as well as I could to an Electron Fiddle at https://gist.github.com/buu700/790a7bbdd8bf9915b2772e50509465d8, but unfortunately I wasn't able to test it because that fails to start with the error `Command failed: npm install -S electron-push-receiver @electron/remote/main`. I also didn't see a way to set the entitlements in the fiddle, but they're the same as I noted in the original issue body.

To clarify the behavior, if this matters, it doesn't ever actually crash. The app starts, and for a fraction of a second I can see the expected UI briefly appear, then suddenly it all goes blank but the window remains open until I close it. (And to reiterate the issue body, this only happens on Apple Silicon; everything works as expected on x86.)

**Comment by nornagon** [comment] 2021-07-08 18:17
It looks like that Fiddle is quite large and contains references to several 3rd-party dependencies. Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue?

I'm re-adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2022-06-09 10:24
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-06-09 10:24 UTC
Labels: platform/macOS, bug :beetle:, blocked/need-repro, 12-x-y
