### ISSUE TITLE
Event 'ready-to-show' never fired if setZoomLevel is called in preload

### ISSUE THREAD

**Issue by zarubond** [electron/electron#19773] opened 2019-08-15 12:26 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
If a call the code below inside preload script, the 'ready-to-show' event is never emitted on BroserWindow. I my case I am starting the window hidden and showing it only when it is loaded, but without this event I never know if it was loaded.

`const { webFrame } = require('electron');
webFrame.setZoomLevel(2);`

* **Electron Version:**
5.0.9, 6.0.2
* **Operating System:**
Window, Linux
* **Last Known Working Electron version:**
3.1.12, 4.2.9

### Expected Behavior
webFrame.setZoomLevel should set zoom level without any sideeffects.

### Actual Behavior
Calling webFrame.setZoomLevel inside preload script block 'ready-to-show' event on BrowserWindow

### To Reproduce
Add these two lines into your preload script:

`const { webFrame } = require('electron');
webFrame.setZoomLevel(2);`

**Comment by ckerr** [comment] 2019-08-15 21:38
I'm able to repro this on Ubuntu 19.04: confirmed that it works in 3-1-x but not in 6-0-x

Quick & dirty gist: https://gist.github.com/ckerr/1c515352ed0831e91d9df7e19520655e

**Comment by miniak** [comment] 2019-08-19 17:23
It does not reproduce anymore with Electron 7 beta 3

**Comment by pushkin-** [comment] 2020-03-05 21:07
I can repro this in Electron 8.0.0. Doing the `setZoomLevel` call on a `setTimeout(, 100);` works around it (not surprisingly), but is obviously not ideal.

**Comment by codebytere** [comment] 2020-06-23 22:03
@pushkin- with this gist: https://gist.github.com/ckerr/1c515352ed0831e91d9df7e19520655e?

I ran this on 8.0.0 and 8.3.3 and experienced issues on neither.

**Comment by codebytere** [comment] 2020-07-06 16:12
Closing due to not response but will re-open if more information comes to light.

**Closed by codebytere** 2020-07-06 16:12 UTC
Labels: 5-0-x, 6-1-x, bug :beetle:, bug/regression :leftwards_arrow_with_hook:, platform/linux, platform/windows, status/confirmed
