### ISSUE TITLE
Fail to profiling reloading page at Performance of Chrome devtools 

### ISSUE THREAD

**Issue by hezhuojie** [electron/electron#15411] opened 2018-10-26 09:42 UTC
* Output of `node_modules/.bin/electron --version`: 3.0.5
* Operating System (Platform and Version): macOS Sierra 10.12.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.4

**Expected Behavior**
Show profiling result
![image](https://user-images.githubusercontent.com/10278872/47558592-1222aa80-d946-11e8-927b-daed88019533.png)

**Actual behavior**
Profiling result is empty
![image](https://user-images.githubusercontent.com/10278872/47556900-03d28f80-d942-11e8-9284-2f2bb6ad5f49.png)

**To Reproduce**

Setup and start [electron-api-demos](https://github.com/electron/electron-api-demos)  -> open devtools of BrowserWindow -> open 'Performance' tab -> click 'Start profiling and reload page'  button at left-top corner -> wait for page reload completed and stop profilling

Besides, Start profiling at first , then press `Command+R` to reload page, and then stop profiling, Same result will occur

**Screenshots**

**Additional Information**
This issue can be reproduced at other project using electron 3.0.5

**Comment by kwonoj** [comment] 2018-10-26 17:55
looks dupe of https://github.com/electron/electron/issues/14763?

**Comment by MarshallOfSound** [comment] 2018-10-26 21:29
Yup, dupe of #14763

**Closed by MarshallOfSound** 2018-10-26 21:29 UTC
