### ISSUE TITLE
In task bar (linux) frameless window shows [Object object]

### ISSUE THREAD

**Issue by ncoevoet** [electron/electron#7680] opened 2016-10-20 11:24 UTC
- Electron version:
  1.4.4
- Operating system:
  Linux

On linux, if you create a BrowserWindow of that type : 
{
            "title" : "Something",
        "skipTaskbar" : false,
        "frame" : false,
        "type" : "notification"
}
Ie : a window with no window's borders that should appears in task bar, the task bar title are always "[object Object]" even when you try to win.setTitle, it works well on windows seven. 
Is is something fixable or it's due to the relation between window manager and the task manager ?

**Comment by StefanYohansson** [comment] 2016-10-20 16:54
can you provide more info about your problem ? (example code, distro, graphical interface)
I am using KDE neon (ubuntu 16.04) and can't reproduce your problem using [electron-quick-start](https://github.com/electron/electron-quick-start) project.

I just downloaded electron-quick-start and apply this patch like you describe in your description.

```
diff --git a/index.html b/index.html
index 7bbf746..1688d41 100644
--- a/index.html
+++ b/index.html
@@ -2,7 +2,6 @@
 <html>
   <head>
     <meta charset="UTF-8">
-    <title>Hello World!</title>
   </head>
   <body>
     <h1>Hello World!</h1>
diff --git a/main.js b/main.js
index fdce321..3db79a5 100644
--- a/main.js
+++ b/main.js
@@ -10,7 +10,14 @@ let mainWindow

 function createWindow () {
   // Create the browser window.
-  mainWindow = new BrowserWindow({width: 800, height: 600})
+  mainWindow = new BrowserWindow({
+    width: 800,
+    height: 600,
+    skipTaskbar: false,
+    title: "Something",
+    frame: false,
+    type: "nofitication"
+  })

   // and load the index.html of the app.
   mainWindow.loadURL(`file://${__dirname}/index.html`)
```

the result is a window with title "Something" as you can see:

![screenshot_20161020_134702](https://cloud.githubusercontent.com/assets/1783252/19569500/5d5bb06e-96cc-11e6-965e-b3d56d35d368.png)

electron version installed:
$> cat ./node_modules/electron/package.json | grep version
  "version": "1.4.4"

**Comment by kevinsawicki** [comment] 2016-11-17 00:00
Closing this out until more information is provided.

**Closed by kevinsawicki** 2016-11-17 00:00 UTC
Labels: more-information-needed
