### ISSUE TITLE
Won't fire keydown event when an input session starting with Sogou IME

### ISSUE THREAD

**Issue by wyattzheng** [electron/electron#28044] opened 2021-03-08 15:56 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.0-beta1
* **Operating System:**
  * Windows 10 (18363.1379)
* **Last Known Working Electron version:**
  * 10.4.0

### Expected Behavior
Some events like ``input``,``keydown``,``keyup``,``compositionstart``,``compositionupdate``,``compositionend`` would be fired correctly.

### Actual Behavior
Some input IMEs like Sogou Pinyin would never trigger the event like ``keydown`` when they are inputing.

### To Reproduce

for windows:

1. download the Sogou IME installer from https://pinyin.sogou.com/
2. try to input Chinese words or Japanese words in integrated terminal of vscode

**Comment by ckerr** [comment] 2021-03-08 17:25
> try to input Chinese words or Japanese words in integrated terminal of vscode

Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a folloup comment.

Thanks in advance! Your help is appreciated.

**Comment by ZhyMC** [comment] 2021-03-08 17:28
@ckerr Sure, i will make a testcase.

**Comment by ZhyMC** [comment] 2021-03-08 18:01
@ckerr i created a gist by Electron Fiddle to reproduce: https://gist.github.com/4e49015759016591d9be00305f734303

**Comment by ZhyMC** [comment] 2021-03-08 18:08
i am also trying to see what causes this between ``11.0.0-beta``` and ``10.4.0`` .
So i am setting up a developing environment and try to use ``git bisect`` to find out the bad commit.

**Comment by nornagon** [comment] 2021-03-12 00:54
@ZhyMC You might be able to narrow it down with Electron Fiddle's built-in bisect feature. Enable it with View > Toggle Bisect Helper.

**Comment by ZhyMC** [comment] 2021-03-12 01:05
@nornagon sure, but these two versions and close.

**Comment by ZhyMC** [comment] 2021-03-12 02:06
it's hard to setting up a electron developing environment. i need to download source of chromium.

**Comment by nornagon** [comment] 2021-03-15 18:56
@ZhyMC you might find https://github.com/electron/build-tools helpful. But also a Fiddle bisect range will probably get us pretty close. You can enable nightlies in Fiddle to get a finer range than released versions.

**Comment by uv-w** [comment] 2021-05-12 13:24
Is there any progress so far？

**Comment by codebytere** [comment] 2022-07-20 19:35
Duplicate of https://github.com/electron/electron/issues/33386

**Closed by codebytere** 2022-07-20 19:35 UTC
Labels: platform/windows, bug :beetle:, bug/regression :leftwards_arrow_with_hook:, blocked/need-repro, 11-x-y

**Comment by Linguoyan** [comment] 2022-07-28 02:12
Same problem with electron 16.0.8. Won't fire any inputEvent with Sougou IME. Is there any good solution?

**Comment by asd281533890** [comment] 2022-10-18 12:08
No problem on Windows 7 with electron 11.5.0.

**Comment by 1339240789** [comment] 2023-08-28 08:39
bump

**Comment by 1339240789** [comment] 2023-11-17 03:28
bump
