### ISSUE TITLE
[Bug]: Electron 19 Crash: EXC_BAD_ACCESS / KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by nbashkankov** [electron/electron#35948] opened 2022-10-08 17:10 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.1.1

### What operating system are you using?

macOS

### Operating System Version

MacOS 12.6

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

11.x.x

### Expected Behavior

App not crashing when BrowserWindow is closed.

### Actual Behavior

App crashing when BrowserWindows is closed.

### Testcase Gist URL

https://gist.github.com/nbashkankov/c73c14b4cec02ac6fa59c144a44813ee

### Additional Information

Happends on both platforms: Windows / MacOS.
Testcase: call for Notification during Window is closing.
Here crash call stack (used 19.1.1 Electron Framework.dSYM to get call stack):
```
base::SupportsUserData::GetUserData(void const*) const (in Electron Framework) (supports_user_data.cc:28)
electron::ElectronBrowserClient::WebNotificationAllowed(content::RenderFrameHost*, base::OnceCallback<void (bool, bool)>) (in Electron Framework) + 56
electron::PlatformNotificationService::DisplayNotification(content::RenderFrameHost*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, GURL const&, GURL const&, blink::PlatformNotificationData const&, blink::NotificationResources const&) (in Electron Framework) (platform_notification_service.cc:106)
content::BlinkNotificationServiceImpl::DisplayNonPersistentNotification(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, blink::PlatformNotificationData const&, blink::NotificationResources const&, mojo::PendingRemote<blink::mojom::NonPersistentNotificationListener>) (in Electron Framework) (blink_notification_service_impl.cc:153)
blink::mojom::NotificationServiceStubDispatch::Accept(blink::mojom::NotificationService*, mojo::Message*) (in Electron Framework) + 660
mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*) (in Electron Framework) + 592
mojo::MessageDispatcher::Accept(mojo::Message*) (in Electron Framework) (message_dispatcher.cc:43)
mojo::InterfaceEndpointClient::HandleIncomingMessage(mojo::Message*) (in Electron Framework) + 40
mojo::internal::MultiplexRouter::Accept(mojo::Message*) (in Electron Framework) + 464
mojo::MessageDispatcher::Accept(mojo::Message*) (in Electron Framework) (message_dispatcher.cc:43)
base::internal::Invoker<base::internal::BindState<void (mojo::Connector::*)(unsigned int), base::internal::UnretainedWrapper<mojo::Connector> >, void (unsigned int)>::Run(base::internal::BindStateBase*, unsigned int) (in Electron Framework) + 476
base::internal::Invoker<base::internal::BindState<void (mojo::SimpleWatcher::*)(int, unsigned int, mojo::HandleSignalsState const&), base::WeakPtr<mojo::SimpleWatcher>, int, unsigned int, mojo::HandleSignalsState>, void ()>::RunOnce(base::internal::BindStateBase*) (in Electron Framework) (bind_internal.h:748)
base::TaskAnnotator::RunTaskImpl(base::PendingTask&) (in Electron Framework) + 228
non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() (in Electron Framework) (thread_controller_with_message_pump_impl.cc:0)
invocation function for block in base::MessagePumpCFRunLoopBase::RunWorkSource(void*) (in Electron Framework) (message_pump_mac.mm:376)
base::mac::CallWithEHFrame(void () block_pointer) (in Electron Framework) + 16
base::MessagePumpCFRunLoopBase::RunWorkSource(void*) (in Electron Framework) (message_pump_mac.mm:378)
base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) (in Electron Framework) (message_pump_mac.mm:760)
base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) (in Electron Framework) (message_pump_mac.mm:163)
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) (in Electron Framework) (thread_controller_with_message_pump_impl.cc:501)
base::RunLoop::Run(base::Location const&) (in Electron Framework) (run_loop.cc:143)
content::BrowserMainLoop::RunMainMessageLoop() (in Electron Framework) + 136
content::BrowserMainRunnerImpl::Run() (in Electron Framework) (browser_main_runner_impl.cc:156)
content::BrowserMain(content::MainFunctionParams) (in Electron Framework) (browser_main.cc:30)
content::RunBrowserProcessMain(content::MainFunctionParams, content::ContentMainDelegate*) (in Electron Framework) + 120
content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) (in Electron Framework) + 1072
content::ContentMainRunnerImpl::Run() (in Electron Framework) + 508
content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) (in Electron Framework) (content_main.cc:411)
content::ContentMain(content::ContentMainParams) (in Electron Framework) (content_main.cc:439)
ElectronMain (in Electron Framework) (electron_library_main.mm:0)
```

**Comment by codebytere** [comment] 2022-10-17 20:59
Looks like an upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1320510

**Comment by nbashkankov** [comment] 2022-10-19 07:38
@codebytere hello,
is there any news on when fix will be available?

> Looks like an upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1320510
what does it means for fix inside Electron?

**Comment by codebytere** [comment] 2023-01-04 17:52
Closing as this is no longer reproducible on latest supported versions

**Closed by codebytere** 2023-01-04 17:52 UTC
Labels: platform/macOS, crash :boom:, bug :beetle:, component/notifications, status/confirmed
