### ISSUE TITLE
Electron-webview not loading images in few websites

### ISSUE THREAD

**Issue by myfrndjk** [electron/electron#7581] opened 2016-10-12 19:26 UTC
* Electron version:1.4.3. 
* Operating system: OSX EI Captain 11.6 
*Nodejs Version :  6.7 

I am creating an electron desktop app and using webview to display websites.For few sites it is not loading some of the images and throws following error "CGAffineTransformInvert: singular matrix" in Mac. 

URL which is having issue : https://www.aliexpress.com/item/Brand-New-Tshirt-Men-Camouflage-2016-Summer-Camo-Top-Design-Hip-Hop-Military-Army-Cool-Tee/32680167051.html

**Comment by pfrazee** [comment] 2016-10-19 19:08
Try enabling `allowDisplayingInsecureContent` in the BrowserWindow. That page is serving images over HTTP, while the site is served over HTTPS.

If you're using a webview, you'll need to wait for https://github.com/electron/electron/pull/7631 to merge so you can set that flag.

**Comment by kevinsawicki** [comment] 2016-10-24 03:37
> That page is serving images over HTTP, while the site is served over HTTPS.

All the images on that page seem to be HTTPS now for me so I'm unable to reproduce.

@myfrndjk please try the suggestion by @pfrazee and if you are still experiencing this please provide a URL that is still failing for you, closing this out for now.

**Closed by kevinsawicki** 2016-10-24 03:37 UTC
