### ISSUE TITLE
HTML5 drag-drop is now working un KUbuntu

### ISSUE THREAD

**Issue by antelle** [electron/electron#5162] opened 2016-04-14 21:07 UTC
- Electron version: 0.37.5 x64
- Operating system: KUbuntu: Linux 4.2.0-16-generic # 19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

HTML drag-drop event files list is empty.
Steps:
1. create an electron app which will open html drag-drop demo page: http://html5demos.com/file-api
2. drop a picture from built-in file manager
Expected: files array contains 1 dragged file
Actual: files length is 0:
`file-api:49 Uncaught TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'`
This is ok on Mac, Windows and Ubuntu.

**Comment by zcbenz** [comment] 2016-04-15 11:19
Does it work in Chromium browser?

**Comment by antelle** [comment] 2016-04-15 11:28
yes

**Comment by zcbenz** [comment] 2016-04-15 11:54
It could a regression of recent Chrome browsers. Can you try if it works in Chrome/Chromium 49? Electron shares the same code with Chromium on HTML drag-drop, so if it is a bug of Chromium we would not be able to fix it on our side.

**Comment by antelle** [comment] 2016-04-15 17:10
Tested on fresh Chrome: drag-drop doesn't work as well.

**Comment by antelle** [comment] 2016-04-15 19:34
Found this bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=348312
So it's a regression, you're right.

**Comment by zcbenz** [comment] 2016-04-16 02:36
Thanks for reporting it to upstream!

**Comment by codebytere** [comment] 2017-09-27 11:58
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 11:58 UTC
Labels: blocked, component/drag-and-drop, fixme/bug, linux-distribution-specific, platform/linux
