### ISSUE TITLE
Notifications disappear from Action Center once it's opened  in Windows 10

### ISSUE THREAD

**Issue by seanchas116** [electron/electron#3916] opened 2015-12-24 11:41 UTC
I'm using Web Notification API to show notifications in Windows. The notifications shown in Action Center are disappeared once I open Action Center and see them.

Is this a bug? Is there a way to preserve notifications in Action Center even after it's opened?

I'm using Electron 0.36.1 and Windows 10.

This is a simple example I tried:

``` js
var count = 0;
setInterval(() => {
  new Notification("TEST", {body: String(count)});
  ++count;
}, 3000);
```

![703f06cc49c466841e19a70b8054fb36](https://cloud.githubusercontent.com/assets/1025246/11994253/9819cf5a-aa7e-11e5-990f-6c8d816ebf11.gif)

**Comment by zcbenz** [comment] 2015-12-25 04:18
This is designed by Windows 10's action center, every app including the Microsoft ones behaves the same. :(

**Comment by seanchas116** [comment] 2015-12-25 10:19
Thanks!

**Comment by paulcbetts** [comment] 2015-12-27 18:48
Hm, I'm not so sure, we implement Win10 notifications natively, and they don't go away (much to the frustration of some users :-/). It seems as if it's at least _possible_ to keep them in the action center though whether we _should_ is a good question.

**Comment by seanchas116** [comment] 2015-12-28 10:28
I've tested this now in Slack and Twitter (the one included in Windows 10) and both of them keep notifications in the Action Center.

> much to the frustration of some users :-/

This is why I opened this issue. I'm developing a messaging app and it's essential not to miss message notifications...

**Comment by zcbenz** [comment] 2015-12-28 12:43
There seems to be a trick to make notifications persist, on OS X the notifications will stay until they are clicked or when the app quits, I think we should follow the same behavior on Windows.

**Comment by seanchas116** [comment] 2015-12-28 14:01
Maybe related: https://github.com/telegramdesktop/tdesktop/issues/1009

**Comment by DerNivel** [comment] 2015-12-28 15:20
Here are more information on Notifications in Win 10: http://blogs.msdn.com/b/tiles_and_toasts/archive/2015/10/15/quickstart-handling-toast-activations-from-win32-apps-in-windows-10.aspx

**Comment by paulcbetts** [comment] 2015-12-28 18:54
> This is why I opened this issue. I'm developing a messaging app and it's essential not to miss message notifications...

No, I meant the opposite - if you leave notifications in the center, users will be annoyed with you and claim that you should remove them. You can't win with Windows users :-/

**Comment by DerNivel** [comment] 2015-12-28 18:56
@paulcbetts I think it would be nice if it's possible to turn that behaivor on and off.

**Comment by bytex64** [comment] 2016-02-25 05:34
> if you leave notifications in the center, users will be annoyed with you and claim that you should remove them.

Going out on a limb here, but what they *probably* mean is that the notifications should go away when you return to the app and see what they were pointing to. Notifications that persist after their usefulness are just as annoying as notifications that don't persist long enough.

**Comment by Rhedox** [comment] 2016-06-10 11:40
Apparently Win32 apps need to implement a COM Server that activates the app when the notification is clicked in order for it stay in the action center.

**Comment by prime-ralph** [comment] 2016-09-29 11:19
Just found this while looking around.
![image](https://cloud.githubusercontent.com/assets/15341353/18951719/35ab0550-8679-11e6-97e0-936cc9e94c66.png)
Clicking on this item leads to a page with advanced options:
![image](https://cloud.githubusercontent.com/assets/15341353/18951745/5381dcde-8679-11e6-8900-16b99bfa2de0.png)
Turning on this option enables Electron to persist notifications in Action Center. 
Sample screenshot:
![image](https://cloud.githubusercontent.com/assets/15341353/18951804/9af92b62-8679-11e6-9f0a-53540e8fb69f.png)

Was wondering if there can be an option we can use to toggle that option by default... As some has observed, other apps were able to do the same.

**Comment by CorinChappy** [comment] 2016-11-28 10:41
There is a way to toggle this option on via the registry, however when I tested it notifications still did not persist (whether the option was set through the UI or via the registry), hopefully that's just my setup!

Anyway the command you can use (in command prompt) is:
```
reg add HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Electron /t REG_DWORD /v ShowInActionCenter /d 1 /f
```
I guess this can be run at install time or the first time the application is launched?

If your app has a different ID (changing it in the code or using squirrel, for example), you need to replace Electron with that ID.

More information about this registry entry here: http://stackoverflow.com/questions/31772192/toastnotifications-sent-from-powershell-disappear-from-action-center/39564998#39564998
It's worth looking at the link in that answer too.

**Comment by ElvisPresly** [comment] 2017-04-24 14:29
this bug will be fixed generally?

**Comment by sofianguy** [comment] 2018-01-30 03:19
Thanks for contributing!

This is an old version that we are no longer supporting. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.

**Comment by Thomas101** [comment] 2018-03-01 13:22
@sofianguy this behaviour is still present in 1.8.2 and 2.0.0-beta.1

**Comment by SaileshKumar** [comment] 2018-05-08 23:14
I'm seeing the same behavior. I googled around and some people referred to other notification APIs, but I can't get any to persist in the Action Center. Has anyone else had any luck?

**Comment by SaileshKumar** [comment] 2018-05-08 23:28
So if I wanted to have the notif go there automatically, it wouldn't be possible? I feel like other apps do that, but maybe they are using something else?

**Comment by hacdias** [comment] 2019-01-28 09:11
The same is happening on Electron 4!

**Comment by MarchWorks** [comment] 2019-12-20 09:38
https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl#step-4-implement-the-activator

> This is required for your toast to persist in Action Center

**Comment by Venryx** [comment] 2019-12-20 21:25
Somehow this short Powershell script is able to create persistent-in-action-center notifications, even without implementing the activator-callback mentioned in your link above (there's a line for it, but it's commented out): https://deploywindows.com/2015/12/01/powershell-can-i-use-balloons-toasts-and-notifications

I don't know why the Powershell-triggered notification persists, but Electron's does not; perhaps powershell uses a different call path internally for the notification creation.

Anyway, hopefully the solution in [your link above](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl#step-4-implement-the-activator) can work for Electron.

Multiple apps I use (eg. [Rambox](https://github.com/ramboxapp/community-edition/issues/151), [Mailspring](https://github.com/Foundry376/Mailspring/issues/1343)) currently have their notifications not persist, because of this issue. (meaning if you don't notice the notification, or you're afk, you can miss important messages!)

**Comment by electron-triage** [comment] 2020-02-19 23:53
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:43
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:43 UTC
Labels: 2-0-x, 4-2-x, blocked/need-info ❌, bug :beetle:, platform/windows, version/1.8.x

**Comment by codedebugrepeat** [comment] 2020-02-27 12:31
The issue persists in Electron 8.0.0
Notifications will show in Action Center once, then when you close and reopen Action center without deleting the notification, the notification is gone.

**Comment by jwoo0122** [comment] 2020-10-12 06:41
Still remains in Electron 10.1.2...
It seems like [this issue](https://github.com/RocketChat/Rocket.Chat.Electron/issues/357) also points same issue, and they resolved it from [this PR](https://github.com/RocketChat/Rocket.Chat.Electron/pull/969), with [electron-windows-notifications](https://github.com/felixrieseberg/electron-windows-notifications).

This is not a solution for Electron itself, but maybe it can be a way to bypass this issue.

**Comment by codedebugrepeat** [comment] 2020-12-09 12:16
@sofianguy Can you folks please take another look at this issue? It means Windows notifications are seriously broken out-of-the-box. Right now even apps like WhatsApp have their notifications disappear.

A fix on the Electron-level would be very much appreciated. 

As a workaround, we had to switch to custom notifications writing a native node-addon, and consult with Microsoft on some internal calls. Available solutions like `electron-windows-notifications` are not well maintained and in our experience also didn't fix the issue. We would love to share our workaround as open-source, but the community would benefit _much_ more from a core fix. 

Not every app needs fully custom Windows notifications, many could just leverage Electron's really great built-in notifications functionality if this issue was fixed. Instead of having to build and include C++ code and register the app for notifications on start and all of that they could just do a simple `new Notification()` and be done.

**Comment by indianscout** [comment] 2021-01-14 09:23
Same issue with electron version 11.1.1. Fully agree with _codedebugrepeat_. The messages should stay as it is in MacOS. Disappearing notifications are not worth much.

**Comment by Vulquimar-Silva** [comment] 2021-02-10 02:37
Hello guys, any news?

This problem still persists in the version of Electron 11.0.4.

**Comment by RandomEngy** [comment] 2021-12-20 21:57
[It looks like it's "fixed" as of Electron 12](https://github.com/electron/electron/issues/29557) but now there is a different problem: [it seems to be impossible to recall them](https://github.com/electron/electron/issues/32260).

I think what is needed is proper support for persistent notifications: https://github.com/electron/electron/issues/32261
