### ISSUE TITLE
desktopCapturer to support audio recording on BrowserWindow

### ISSUE THREAD

**Issue by hijklmno** [electron/electron#7255] opened 2016-09-19 18:29 UTC
* Electron version: 1.4.0
* Operating system: OS

Hi Electron team,

Awesome project! Discovered this the other day and it's on our way to production!

Chrome 53 has a flag `Desktop Share with tab source` (chrome://flags/#tab-for-desktop-share) that enables audio recording on the tab level. Is this possible on Electron?

I have tried this:
```  
var screenSource = null;
desktopCapturer.getSources({  
	types: ['window', 'screen']  
}, function(err, sources) {  
	for (let source of sources) {  
		if (source.name === 'Electron Dashboard') {  
			console.log('Found dashboard:', source);  
			screenSource = source;  
		}  
	}  
});  
```  

and then grabbing the tab with:
```  
getUserMedia({
	audio: {
		mandatory: {
			chromeMediaSource: 'desktop',
			chromeMediaSourceId: screenSource.id
		},
		optional: []
	},
	video: {
		mandatory: {
			chromeMediaSource: 'desktop',
			chromeMediaSourceId: screenSource.id,
			maxWidth: window.screen.width,
			maxHeight: window.screen.height
		},
		optional: []
	}
},
function(screenStream) {
	console.log('getUserMedia on screen success', screenStream);
	// attach screenStream to local video element
},
function(err) {
	console.error('getUserMedia on tab video error:', err);
});
```

The video is captured splendidly, but audio is not. This audio recording works using my old setup, with the flag enabled and Chrome extensions. I used `chrome.desktopCapture.chooseDesktopMedia` and passed in the captured stream id to the above `getUserMedia` function as the `chromeMediaSourceId`. 

Is there something I'm doing wrong? Thanks again! Let me know if you need anything else from me.

**Comment by MarshallOfSound** [comment] 2016-09-19 23:31
Our current API can't currently do this.

Duplicate of https://github.com/electron/electron/issues/4776

**Closed by MarshallOfSound** 2016-09-19 23:31 UTC

**Comment by hijklmno** [comment] 2016-09-19 23:45
@MarshallOfSound thank you for your quick reply. Will be awesome to have this feature once tab audio recording via `desktopCapture` is stabilized (targeted for Chrome 55 I think).

**Comment by hijklmno** [comment] 2016-09-20 06:46
Just curious, how hard would it be to improve the current API to support audio? @hokein, I know you did the first (awesome) iteration on desktopCapturer at #2963, which back then didn't support audio. I wanted to hear your thoughts (: I would _love_ this feature to work on electron.

By the way, I'm unable to obtain the audio of the screen through the `chromeMediaSource: 'screen'` method. Can you provide a sample `getUserMedia` constraint that captures the audio and video of a screen, or give a hint to point me into the right direction? I tried the following constraint but I got `NavigatorUserMediaError: {name: "ScreenCaptureError", message: "", constraintName: ""}`:

```
{
	audio: true,
	video: {
		mandatory: {
			chromeMediaSource: 'screen'
		}
	}
}
```

 Thanks again!

**Comment by demian85** [comment] 2016-12-23 18:36
I'm hitting the same wall here on Mac. Additionally, I'm having serious issues with frame rate, it's like video is captured with less than 1fps, even though I used maxFrameRate: 25.
I'll create a new issue with further details.

**Comment by demian85** [comment] 2017-01-06 02:19
Helllo? what about comment from @hijklmno? having the same issue here!

**Comment by siman** [comment] 2017-02-02 11:07
@hijklmno I have the same `ScreenCaptureError` problem on Linux. What is your OS?
Anybody experiences the same error on Win or OSX when recording audio+screen?
