### ISSUE TITLE
[Bug]: Electron's cache folder gets backed up by TimeMachine

### ISSUE THREAD

**Issue by idontusenumbers** [electron/electron#28997] opened 2021-05-04 17:26 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

Slack Version 4.15.0 5d7680b5e4c7d0ab1f4315edae52ef1f7e74f8bd@1620079581 (Production)

### What operating system are you using?

macOS

### Operating System Version

MacOS 10.13.6

### What arch are you using?

x64

### Expected Behavior

Electron stores caches in system caches folder as to avoid those files being backed up by TimeMachine

### Actual Behavior

Electron stores caches in ApplicationSupport causing tens of gigabytes of wasted backup per application

### Additional Information

Electron should store caches in /Users/<user>/Library/Caches/<appdomain>/ instead of /Users/<user>/Library/ApplicationSupport/<app>/Cache

**Comment by MarshallOfSound** [comment] 2021-05-04 20:22
Closing as duplicate of https://github.com/electron/electron/issues/8124

There are multiple years worth of discussion there around how this is a breaking change that we are unlikely to make, individual apps can change paths but again, it would be a breaking change for those apps and in some cases is not viable.  We are currently aligned with Chromium in terms of where content is stored on disk and there is currently no overwhelmingly compelling reason to change that.

**Closed by MarshallOfSound** 2021-05-04 20:22 UTC
Labels: bug :beetle:

**Comment by idontusenumbers** [comment] 2021-05-04 21:01
> There are multiple years worth of discussion

My bad, I searched for TimeMachine including closed tickets and got no results; ill discuss on the ticket you mentioned if it's warranted.
