### ISSUE TITLE
[Bug]: Window don't move

### ISSUE THREAD

**Issue by ArthurLobopro** [electron/electron#31171] opened 2021-09-28 12:23 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

13.1.7

### Expected Behavior

`-webkit-app-region: drag` move the window

### Actual Behavior

`-webkit-app-region: drag` is not moving the window

### Additional Information

I created a BrowserWindow with this configuration

```js 
{
        frame: false,
        width: 315,
        minWidth: 315,
        height: 485,
        minHeight: 485,
        resizable: false,
        maximizable: false,
        webPreferences:{
            nodeIntegration: true,
            preload: path.join(__dirname, "preload.js")
        }
}
```

In the window there was a div with this style: `-webkit-app-region: drag`
But he not moves this window

After some tests I found out that the property ` resizable: false` was what caused the problem and the property 
`movable: true` does not fix the error

Sorry for the poor English I'm not fluent :)

**Comment by codebytere** [comment] 2021-09-28 19:17
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by ArthurLobopro** [comment] 2021-09-29 03:47
Hi !

Here it is the [Gist Link](https://gist.github.com/cd9d5abc8bc35dca904eeb2b8ef14c1e)

**Comment by codebytere** [comment] 2021-09-29 08:31
Might be closed by https://github.com/electron/electron/pull/30925

**Closed** 2021-09-29 08:32 UTC
Labels: bug :beetle:, blocked/need-repro
