### ISSUE TITLE
AddTrust CA root cert expiration breaking TLS connections through Node

### ISSUE THREAD

**Issue by yang991178** [electron/electron#24123] opened 2020-06-13 10:08 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v9.0.4
* **Operating System:**
  * Windows 10 1903
* **Last Known Working Electron version:**
  * None

### Expected Behavior
Node should be able to establish TLS connection using the latest certificates.

### Actual Behavior
An expired root certificate is used by Node, resulting in:
```
Error: certificate has expired at TLSSocket.onConnectSecure
```

### To Reproduce
Use Node to establish a TLS connection with websites that use certificates signed by AddTrust (For instance, https://sspai.com/feed).

### Additional Information
It seems that the AddTrust root certificate bundled with Node has [expired on May 30](https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020). This causes TLS connections to sites with certificates issued by AddTrust to fail when initiated through Node. New certificates [have been added](https://github.com/nodejs/node/issues/33681) in newer builds of Node. Requests made through Chromium are unaffected as the result of #11741.

**Comment by kr3l** [comment] 2020-06-19 07:26
We are experiencing (what I think to be) the same issue, both on Mac and Windows. 

We have a file index.js which contains

```
const got = require("got");
console.log(process.version);

(async () => {
    const result = await got("https://addtrustchain.test.certificatetest.com/", {
        method: "GET",
    });
    console.log(result && result.body);
})();
```

Running 

```
.\node_modules\.bin\electron .\index.js
```

results in 

```
λ .\node_modules\.bin\electron .\index.js                                                                                                                                                  
                                                                                                                                                                                                                                      
v12.14.1                                                                                                                                                                                                                              
(node:17756) UnhandledPromiseRejectionWarning: RequestError: certificate has expired                                                                                                                                                  
    at ClientRequest.<anonymous> (C:\Users\Karel\Documents\code\testje\node_modules\got\dist\source\core\index.js:826:25)                                                                       
    at Object.onceWrapper (events.js:313:26)                                                                                                                                                                                          
    at ClientRequest.emit (events.js:228:7)                                                                                                                                                                                           
    at ClientRequest.origin.emit (C:\Users\Karel\Documents\code\testje\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)                                                           
    at TLSSocket.socketErrorListener (_http_client.js:406:9)                                                                                                                                                                          
    at TLSSocket.emit (events.js:223:5)                                                                                                                                                                                               
    at emitErrorNT (internal/streams/destroy.js:92:8)                                                                                                                                                                                 
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)                                                                                                                                                                         
    at processTicksAndRejections (internal/process/task_queues.js:81:21)                                                                                                                                                              
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)                                                                                                                                                                               
    at TLSSocket.emit (events.js:223:5)                                                                                                                                                                                               
    at TLSSocket._finishInit (_tls_wrap.js:794:8)                                                                                                                                                                                     
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)                                                                                                                                                                              
(node:17756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 (rejection id: 1)                                                                                                                                                                                                                    
(node:17756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.                          
```

If we run the same javascript file using node 12.14.1, however, the code runs successfully

```
node .\index.js
v12.14.1
Certificate issued from a CA signed by <b>USERTrust RSA Certification Authority</b> with a cross cert via server chain from <b>AddTrust External CA Root</b>
```

If we adjust the script to use http instead of the got library, the same issue still occurs (just to rule out this being caused by got library).

**Comment by nornagon** [comment] 2020-06-22 18:18
Looks like we should backport https://github.com/nodejs/node/pull/33682.

**Comment by sdbacq** [comment] 2020-06-26 07:47
This is not yet released in v9, but I saw that it should be fixed in [release 8.3.4 ](https://github.com/electron/electron/releases/tag/v8.3.4), but I'm running into the same issue when running the following code with electron:

```
const got = require('got');

console.log(`node: ${process.version}`);
console.log(`electron: ${process.versions && process.versions.electron}`);

(async () => {
    try {
        const result = await got('https://addtrustchain.test.certificatetest.com/', {
            method: 'GET',
        });
        console.log(result && result.body);
    } catch (error) {
        console.error(error.message);
    }
})();
```

```
/node_modules/.bin/electron test.js 
node: v12.13.0
electron: 8.3.4
certificate has expired
```

but running it with the same node version works

```
node test.js
node: v12.13.0
electron: undefined
Certificate issued from a CA signed by <b>USERTrust RSA Certification Authority</b> with a cross cert via server chain from <b>AddTrust External CA Root</b>
```

**Comment by jmfarnsworth** [comment] 2020-06-30 11:26
I'm seeing the same issue as @sdbacq on the following setups

node: v12.18.0
electron: 7.3.2
Error: certificate has expired

node: v12.18.0
electron: 8.3.4
Error: certificate has expired

which is the same as I was getting on electron 9.0.4 which doesn't have the fix in.

**Comment by frederikreher** [comment] 2020-07-02 17:53
I'm having the same issues with v.12.13.0 and 8.3.4. @nornagon should this issue be reopened?

**Comment by MRayermannMSFT** [comment] 2020-07-13 01:48
Ditto. We had a user attempting to hit an endpoint where this cert was in the chain, and they continue to get an expired certificate error w/v8.3.4. Let me/us know if there's any info we can grab to help!

**Closed** 2020-09-08 11:28 UTC
Labels: 10-x-y, 11-x-y, 9-x-y, bug :beetle:, platform/all

**Comment by XingXiaoWu** [comment] 2024-01-22 13:07
same question in ` "electron": "^24.1.3",`，maybe  this issue can be reopened?
