### ISSUE TITLE
TypeError: Error processing argument at index 0

### ISSUE THREAD

**Issue by YellowPure** [electron/electron#22137] opened 2020-02-11 07:58 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0
* **Operating System:**
  * macOS 10.15 x64
* **Last Known Working Electron version:**
  * i dont'work

### Expected Behavior
success create a new Icon

### Actual Behavior
dialog tips: `TypeError: Error processing argument at index 0`

### To Reproduce
`let appIcon;
appIcon = new Tray(path.join(__dirname, 'icon.png'))`

### Screenshots
`
A JavaScript error occurred in the main process.
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /Users/huangliang/Work/electron-quick-start/icon.png
    at App.createWindow (/Users/huangliang/Work/electron-quick-start/main.js:19:13)
    at App.emit (events.js:215:7) 
`

**Comment by vladimiry** [comment] 2020-02-11 11:09
I reported similar issue before, originally detected in v8-beta2, #21154. But it got fixed at least on Linux and Windows and I have a reason to believe that it was fixed on macOS too.

@YellowPure, can you provide repro-repository based on https://github.com/electron/electron-quick-start?

**Comment by MarshallOfSound** [comment] 2020-02-13 06:33
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by YellowPure** [comment] 2020-02-14 01:44
@MarshallOfSound @vladimiry .
`https://github.com/YellowPure/electron-quick-start`
I used yarn to install modules.
if need more info,contact to me.

thanks 😊

**Comment by vladimiry** [comment] 2020-02-14 05:33
The first issue here is that the used icon is not a real `*.png` file but probably renamed `*.ico` file. So try using another image, like for example this one https://github.com/vladimiry-playground/electron-quick-start-tray-issue/blob/master/icon.png.

But here is more. The app gets crashed on at least Linux until I perform any of the following change:
- Call `tray.setContextMenu(...)`. The function argument is either `null` or actual menu instance created using `Menu.buildFromTemplate`.
- Replace `path.join(__dirname, 'icon.png')` with just `icon.png`.
- Use full symlinked path to `icon.png`. If a real full path used then the app still crashes.
- Replace tray creating to this pattern:
```
  const {nativeImage} = require("electron");
  tray = new Tray(nativeImage.createEmpty());
  tray.setImage(nativeImage.createFromPath(path.join(__dirname, 'icon.png')));
```

**Comment by YellowPure** [comment] 2020-02-14 06:17
@vladimiry  hi, thanks for reply.
you are right,my used icon is not a real *.png.
` https://github.com/vladimiry-playground/electron-quick-start-tray-issue/blob/master/icon.png `
worked.

thanks for help!~
I will close this issue.

**Comment by vladimiry** [comment] 2020-02-14 06:20
>  I will close this issue.

I would not close since there is still I believe a major issue I described as a second point (occurring on at least Linux).

**Comment by averissimo** [comment] 2020-05-07 18:23
This still happens with non symbolic images

Below shows ow to reproduce it. Run `npm start` more than once if it doesn't fail in the first try (or click on the menu item `CreateTray`

```
git clone https://github.com/averissimo/electron-quick-start-tray
cd electron-quick-start-tray
npm install
npm start
```

**Comment by aawadall** [comment] 2020-05-17 03:37
this happens in Windows 10 as well, electron 8.3.0

**Comment by codebytere** [comment] 2020-05-27 02:08
@averissimo on macOS? I just ran it and saw no issues.

**Comment by averissimo** [comment] 2020-05-28 13:39
Oops, I didn't specify the OS.. @codebytere on Ubuntu with gnome.

**Comment by codebytere** [comment] 2020-06-09 05:13
This is fixed in v9.0.3 - i experienced no crashes running the above repro with that version on Ubuntu with gnome. Ping if anything else comes up!

**Closed by codebytere** 2020-06-09 05:13 UTC
Labels: 8-x-y, bug :beetle:, platform/macOS

**Comment by yyccQQu** [comment] 2020-10-15 09:02
> Bug is also present in 9.0.0
> 
> Steps to reproduce in `9.0.0`
> 
> ```
> git clone https://github.com/averissimo/electron-quick-start-tray
> cd electron-quick-start-tray
> sed -i 's/8\.2\.5/9.0.0/g' package.json
> npm install
> npm start
> ```
> 
> _edit_: 9.0.0 was released since _(updated to it, instead of beta.24)_, still has a problem
<img width="1115" alt="截屏2020-10-15 下午12 59 32" src="https://user-images.githubusercontent.com/32674176/96101259-5407db00-0ee6-11eb-8963-8307a18542c2.png">

-- Click on that icon and the menu will not show up
but the code is 
```
const { Menu, Tray, nativeImage, MenuItem } = require('electron').remote
const path = require('path')

// All of the Node.js APIs are available in the preload process.
// It has the same sandbox as a Chrome extension.
window.addEventListener('DOMContentLoaded', () => {

  unread = path.join(__dirname, 'icon-unread_016.png')
  read = path.join(__dirname, 'icon-read_016.png')

  imgRead = nativeImage.createFromPath(read)
  imgUnread = nativeImage.createFromPath(unread)
  
  let tray = undefined;

  const menuItem1 = new MenuItem({
    label: 'CreateTray', 
    click: () => {
      tray = new Tray(unread)
    }
  })
  const menuItem2 = new MenuItem({
    label: 'DestroyTray', 
    click: () => {
      if (tray) { tray.destroy() }
      tray = undefined
    }
  })

  // Append "Create menu"
  const menu = Menu.getApplicationMenu()
  menu.append(menuItem1)
  menu.append(menuItem2)

  Menu.setApplicationMenu(menu)


  // Automatic generation of menu
  tray = new Tray(imgRead)

  tray.setImage(imgUnread)

  tray.destroy()
  tray = new Tray(imgRead)

  tray.setImage(imgUnread)

  const replaceText = (selector, text) => {
    const element = document.getElementById(selector)
    if (element) element.innerText = text
  }

  for (const type of ['chrome', 'node', 'electron']) {
    replaceText(`${type}-version`, process.versions[type])
  }
})

```
-- help me ~  Big Boss！

**Comment by yyccQQu** [comment] 2020-10-15 09:14
> @averissimo on macOS? I just ran it and saw no issues.

PLS help me

**Comment by yyccQQu** [comment] 2020-10-15 11:10
> > Bug is also present in 9.0.0
> > Steps to reproduce in `9.0.0`
> > ```
> > git clone https://github.com/averissimo/electron-quick-start-tray
> > cd electron-quick-start-tray
> > sed -i 's/8\.2\.5/9.0.0/g' package.json
> > npm install
> > npm start
> > ```
> > 
> > 
> > _edit_: 9.0.0 was released since _(updated to it, instead of beta.24)_, still has a problem
> 
> <img alt="截屏2020-10-15 下午12 59 32" width="1115" src="https://user-images.githubusercontent.com/32674176/96101259-5407db00-0ee6-11eb-8963-8307a18542c2.png">
> 
> -- Click on that icon and the menu will not show up
> but the code is
> 
> ```
> const { Menu, Tray, nativeImage, MenuItem } = require('electron').remote
> const path = require('path')
> 
> // All of the Node.js APIs are available in the preload process.
> // It has the same sandbox as a Chrome extension.
> window.addEventListener('DOMContentLoaded', () => {
> 
>   unread = path.join(__dirname, 'icon-unread_016.png')
>   read = path.join(__dirname, 'icon-read_016.png')
> 
>   imgRead = nativeImage.createFromPath(read)
>   imgUnread = nativeImage.createFromPath(unread)
>   
>   let tray = undefined;
> 
>   const menuItem1 = new MenuItem({
>     label: 'CreateTray', 
>     click: () => {
>       tray = new Tray(unread)
>     }
>   })
>   const menuItem2 = new MenuItem({
>     label: 'DestroyTray', 
>     click: () => {
>       if (tray) { tray.destroy() }
>       tray = undefined
>     }
>   })
> 
>   // Append "Create menu"
>   const menu = Menu.getApplicationMenu()
>   menu.append(menuItem1)
>   menu.append(menuItem2)
> 
>   Menu.setApplicationMenu(menu)
> 
> 
>   // Automatic generation of menu
>   tray = new Tray(imgRead)
> 
>   tray.setImage(imgUnread)
> 
>   tray.destroy()
>   tray = new Tray(imgRead)
> 
>   tray.setImage(imgUnread)
> 
>   const replaceText = (selector, text) => {
>     const element = document.getElementById(selector)
>     if (element) element.innerText = text
>   }
> 
>   for (const type of ['chrome', 'node', 'electron']) {
>     replaceText(`${type}-version`, process.versions[type])
>   }
> })
> ```
> 
> -- help me ~ Big Boss！
it`s ok ===>
```
const MenuTray = Menu.buildFromTemplate([
  {
    label: 'Afficher l\'application fréquence country',
    click: () => {
      mainWindow.show()
    }
  },
  {
    label: 'Ouvrir le site officiel de la radio',
    click: () => {
      console.log(234567654567)
      // shell.openExternal('https://frequencecountry.mirandais.fr')
    }
  },
  {
    label: 'Accéder à notre page facebook',
    click: () => {
      console.log(234567654567)
      // shell.openExternal('https://www.facebook.com/Frequence-Country-862322540540302/')
    }
  },
  {
    label: 'Fermer la radio',
    click: () => {
      app.isQuiting = true
      app.quit()
    }
  },
  {
    label: 'ping',
    click: () => {
      mainWindow.webContents.send('ping')
    }
  }
])

  mainWindow.setSkipTaskbar(true)

  let unread = path.join(__dirname, '../../static/icons/icons.png')
  let read = path.join(__dirname, '../../static/icons/icons.png')

  let imgRead = nativeImage.createFromPath(read)
  let imgUnread = nativeImage.createFromPath(unread)

  // let tray = new Tray(imgages)
  let tray = new Tray(imgRead)
  tray.setImage(imgUnread)
  
  tray.setToolTip('Fréquence Country: l\'application')
  tray.setContextMenu(MenuTray)
```
