### ISSUE TITLE
BrowserWindow 的frame 为 false的时候isMaximized始终返回false

### ISSUE THREAD

**Issue by seekwe** [electron/electron#8488] opened 2017-01-24 08:02 UTC

**Comment by spartucus** [comment] 2017-01-24 09:25
兄弟得说英语啊。

I think The Title is :

> isMaximized() always returns false when BrowserWindows' frame is false.

**Comment by kevinsawicki** [comment] 2017-01-25 22:59
@seekwe what version of Electron are you using and on what platform?

**Comment by kevinsawicki** [comment] 2017-02-09 21:17
Closing this out until more information is available, I was unable to reproduce this using 1.6.0 on macOS.

**Closed by kevinsawicki** 2017-02-09 21:17 UTC
Labels: more-information-needed

**Comment by seekwe** [comment] 2017-02-12 06:18
很抱歉,忘了说英语了,谢谢@spartucus ,
测试环境:win10 x64,如果frame 不等于false则没问题
