### ISSUE TITLE
Crash Reporter: crashes are not persisted on disk unless crashing main

### ISSUE THREAD

**Issue by bpasero** [electron/electron#20234] opened 2019-09-14 07:48 UTC
* **Electron Version:**
  * 7.x
* **Operating System:**
  * macOS 10.15.x

Steps:
* `git clone https://github.com/bpasero/electron-crashreporter`
* `yarn`
* open `constants.js` and configure:
  * `enableCrashReporter: true`
  * `crashRenderer` (or child process): `true`
  * `tmpDir`: some location that exists that you can check on
* `yarn start`

=> 🐛there is no crash report generated on disk. I see crash report if I configure `crashMain: true` but not in the case of renderer nor child process.

On Windows I see some suspicious output: `[0914/094933.958:ERROR:crashpad_client_win.cc(791)] not connected`

//cc @deepak1556

**Comment by bpasero** [comment] 2020-03-05 17:33
This still reproduces with Electron 7.

**Comment by sean-mcmanus** [comment] 2020-03-06 19:24
We're not seeing crashes being logged to ~/Library/Logs/DiagnosticReports on Mac for our VS Code C/C++ extension child processes (not sure when the started, but it used to work), and the crashes are logged if we launch our process via the command line and not from VS Code. Do you believe this issue is the cause?

**Comment by electron-triage** [comment] 2021-03-09 21:28
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by deepak1556** [comment] 2021-03-12 03:42
The original repro is based on an outdated api, @sean-mcmanus can you provide a gist demonstrating the issue.

**Comment by sean-mcmanus** [comment] 2021-03-12 19:07
@deepak1556 What is a gist?

Maybe @bpasero knows?

**Comment by deepak1556** [comment] 2021-03-12 19:20
I missed that the issue you are seeing is specifically wrt vscode c++ extension crashes. Crash persistence is bit different now in vscode due to how crashpad monitors child processes, you can get crash reports for the child process following the instructions at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports . The issue opened by @bpasero is no longer valid for vscode, hence closing this. If you can't get reports for your extension, please open an issue in vscode and I will look into it. Thanks!

**Closed by deepak1556** 2021-03-12 19:20 UTC
Labels: blocked/need-repro, component/crash-reporter
