### ISSUE TITLE
Save dialog does not expand/collapse properly on macOS

### ISSUE THREAD

**Issue by BONDbATIF** [electron/electron#14606] opened 2018-09-13 11:47 UTC
**Electron Version:**"electron": "^1.8.4"
Operating System (Platform and Version):MAC .10.12 and 10.13

**Expected Behaviour**
After Click "^" on 'Save As'  in showSaveDialog, it should display expanded save as dialog window in MAC.
**_Note:_** working in Windows 

**Actual behavior**
In showSaveDialog , UI shows some abnormal buttons after Click "^" on 'Save As' dialog box.
Note: save as window not Expanded & New folder not responding

**Recreation Steps:**
 this.dialog = this._electronService.remote.dialog;
 this.saveDialog = this.dialog.showSaveDialog({
            title: 'select File Folder',
            defaultPath: '123 copy 1.cxf',
            filters: FilterValues,
        },
     function (fileNames) {
     });
![image](https://user-images.githubusercontent.com/5045450/45485271-96451800-b774-11e8-9087-0f4b1d8d7b88.png)
If i double click the Right side arrow to expand, Most of the time i'm getting the below issue, Some rare cases i'm also getting issue in single click
![image](https://user-images.githubusercontent.com/5045450/45485301-b543aa00-b774-11e8-99a7-68b61473a6d7.png)

1) Please give the solution for the above issue 
2) and also In angular i  programmatically want to set expanded save as dialog by default- as per below snap  (without arrow click on save as )

![image](https://user-images.githubusercontent.com/5045450/45486176-d0fc7f80-b777-11e8-931a-c4ceea5123c7.png)

**Comment by Romace** [comment] 2018-09-18 11:07
I'm experiencing the similar issue on expanding/collapsing Save Dialog in Electron v.2.0.9. I've made a screen record of Postman as an example.
I've verified that the issue is not reproducible in Electron v.1.6.11.

![postman_savedialog_issue](https://user-images.githubusercontent.com/17388835/45683359-04f6ec80-bb4c-11e8-8c4c-1fcccad7b81a.gif)

**Comment by sindresorhus** [comment] 2018-10-04 06:48
I can reproduce this on Electron 3.0.2 too.

**Comment by Anrock** [comment] 2018-10-04 07:35
Seeing this on 1.7. 
In my case file dialog is attached as a sheet to a BrowserWindow and glitchy part is over BrowserView, i suspect this is somehow related.

**Comment by cwillisf** [comment] 2019-01-08 23:15
As far as I can tell, this issue affects version 1.7.0 and newer. The issue is not present in 1.6.18.

I haven't checked every release since 1.7.0 but I've spot-checked a bunch and haven't found any that aren't affected.

**Comment by zcbenz** [comment] 2019-01-30 11:48
As workaround, you can call the API asynchronously by passing a callback.

**Comment by sindresorhus** [comment] 2019-03-16 12:13
There is a workaround for this which we should implement in the meantime, seeing as it doesn't look like Electron will fix this anytime soon: https://github.com/electron/electron/commit/24f1eac84f44fd9a7c7e68ea1fc9cd1568e66247

**Comment by sofianguy** [comment] 2019-08-09 22:57
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by kakadiya91** [comment] 2019-08-13 01:58
Experiencing this issue on electron version `4.2.0` when using `dialog.showSaveDialog` in the sessions `will-download` callback to choose the download location<sup>1</sup>. But using a callback to wait for the path as per https://github.com/electron/electron/pull/16649 seems to work well.


[1] The reason I am not using `item.getSavePath()` instead is because I want the save dialog to have a specified default path instead of just `~/Downloads` and electron `4.2.0` doesn't have the new `item.setSaveDialogOptions` API.

**Comment by electron-triage** [comment] 2020-02-19 21:59
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:40
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:40 UTC
Labels: 3-0-x, 4-2-x, blocked/need-info ❌, bug :beetle:, platform/macOS, version/1.8.x
