### ISSUE TITLE
LoadLibrary works only in certain situations

### ISSUE THREAD

**Issue by 2JJ1** [electron/electron#12907] opened 2018-05-14 01:31 UTC
* Electron Version: 1.8.3
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
Native addon should be able to call methods from a DLL. LoadLibrary() shouldn't return NULL.

**Actual behavior**
With C++ Electron compiled addon, LoadLibrary() returns NULL when compiled with node-gyp for Electron, thus limiting me from calling methods from a C++ DLL. Though when I call LoadLibrary() with a VisualStudio DLL project, it returns the actual module.

**Comment by MarshallOfSound** [comment] 2018-05-14 01:51
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.  In particular if you do not provide a way to reproduce the issue easily and quickly there is a very small chance anyone can help you.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by sofianguy** [comment] 2018-05-21 19:20
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2018-05-21 19:20 UTC
Labels: blocked/need-info
