### ISSUE TITLE
[Feature Request]: Review and clarify the Windows version support

### ISSUE THREAD

**Issue by chulkilee** [electron/electron#35597] opened 2022-09-07 17:25 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron 19.0.6 (and the latest version as well) says it supports Windows 7 and up. However, when I check the dependencies, nodejs and libuv say it supports Windows 8 and up

- Electron 19.0.6 uses Node.js 16.14.2 - [ref](https://github.com/electron/electron/blob/v19.0.6/DEPS)
- Node.js 16.14.2 uses libuv 1.43.0 - [ref](https://github.com/nodejs/node/blob/v16.14.2/deps/uv/ChangeLog)
  - Node.js 16.14.2 supports Windows 8.1/2012 R2 - [ref](https://github.com/nodejs/node/blob/v16.14.2/BUILDING.md)
- libuv 1.43.0 supports Windows >=8 [ref](https://github.com/libuv/libuv/blob/v1.43.0/SUPPORTED_PLATFORMS.md)

Therefore it is not clear whether Electron would run on Windows 7 without issues in future, even I confirmed it works on Windows 7 at this moment.

### Proposed Solution

Review platform supports of all dependencies and update the supported platforms of Electron accordingly

### Alternatives Considered

Not sure

**Comment by zedayseekay** [comment] 2022-09-09 11:49
To your third point "libuv 1.43.0 supports Windows >=8" that is correct, but Electron worked around this issue at the end of 2021 and thus limited Windows 7 support could continue despite libuv upstream dropping support. Some good discussion in progress over on #35219. When that reaches a meaningful conclusion I will report a summary here.

**Comment by miniak** [comment] 2022-09-16 02:22
It may not be necessary when #35702 is merged

**Comment by zedayseekay** [comment] 2022-09-18 10:41
It has been merged, into 19, 20, and 21. I guess that means it will make it to a release soon.

Does the release process for 19 include any testing *on Windows 7? * That's related to the "Review and clarify" ask here because if Electron's releasing without running even the general test coverage under Windows 7, that needs to be clear in the documentation.

I understand that's going to be difficult to achieve because Appveyor does not support Windows 7 either - I guess if Windows 7 still has a nominated maintainer they could be accountable for some sort of reasonable-efforts testing on some virtual infrastructure but without the full Appveyor automation. (Volunteers could be responsible for the actual testing, including me...)

**Comment by chulkilee** [comment] 2022-09-18 16:07
Thanks for the info - yeah I appreciate this project patches dependencies to support Windows 7 as needed. As Windows 7 support is ended, I also see it's challenging to support them like other platforms.

As they're "supported" with different confidence... one option is to introduce tiered supported platform - e.g. Tier 1 for tested with CI and Tier 2 for community test. I've seen this from some other projects.

What about making the current limitation/scope documented and close this - with further action item (e.g. Windows 7  CI)?

**Comment by zedayseekay** [comment] 2022-09-20 16:51
Support for Windows 7 is stated in https://github.com/electron/electron/blob/main/README.md.

Is there any other documentation that should be updated? If we went with @chulkilee 's suggestion of adding the appropriate caveats, where should we include those in the documentation?

**Comment by GitMensch** [comment] 2022-09-21 16:31
> Is there any other documentation that should be updated?

The website: https://www.electronjs.org/docs/latest/development/build-instructions-windows#prerequisites

**Comment by zedayseekay** [comment] 2022-09-22 22:16
> > Is there any other documentation that should be updated?
> 
> The website: https://www.electronjs.org/docs/latest/development/build-instructions-windows#prerequisites

The pre-reqs for *building* electron are different to the prereqs for deploying/installing and running. It's been impossible to build electron on Windows 7 for a lot longer than this most recent *run* regression.

**Comment by GitMensch** [comment] 2022-09-23 05:05
Thanks for making clear that build under Win7 are out of scope.
Is there a possible Win7 CI for running tests only or would this be a manual thing to check before dong a release?

**Comment by zedayseekay** [comment] 2022-09-24 12:17
It seems very unlikely CI will be available, because Windows 7 is in paid-support-only now and goes out of support completely next year. Therefore none of the free CI environments are likely to support it.

That's the bad news. The good news is the fix made it into https://github.com/electron/electron/releases/tag/v19.1.0 :-)

**Closed** 2022-12-01 01:13 UTC
Labels: enhancement :sparkles:, documentation :notebook:
