### ISSUE TITLE
Start with sudo on electron version 5 above causes issue

### ISSUE THREAD

**Issue by chucky86boy** [electron/electron#19187] opened 2019-07-10 04:46 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.6
* **Node Version:**
  * 8.16.0
* **Operating System:**
  * Ubuntu 18.04 x64
* **Last Known Working Electron version:**
  * 4.2.6

### Expected Behavior
It starts the electron app smoothly

### Actual Behavior
npm ERR! Linux 4.18.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! electron-test-sdk@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-test-sdk@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-test-sdk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-test-sdk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-test-sdk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/taghive/Programming/Code/electron-test-sdk/npm-debug.log

### To Reproduce
https://github.com/electron/electron-quick-start
sudo npm start (with above configuration)

**Comment by DeerMichel** [comment] 2019-07-10 05:33
Hi, thanks for reaching out. This issue might be a duplicate of #18547. Which output do you get when setting `ELECTRON_ENABLE_LOGGING=true`?

**Comment by chucky86boy** [comment] 2019-07-10 08:15
```
root@taghive-desktop:/home/taghive/Programming/Code/electron-test-sdk# ELECTRON_ENABLE_LOGGING=true
root@taghive-desktop:/home/taghive/Programming/Code/electron-test-sdk# echo $ELECTRON_ENABLE_LOGGING
true
root@taghive-desktop:/home/taghive/Programming/Code/electron-test-sdk# npm start
> electron-test-sdk@1.0.0 start /home/taghive/Programming/Code/electron-test-sdk
> electron .
npm ERR! Linux 4.18.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! electron-test-sdk@1.0.0 start: 'electron .'
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-test-sdk@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-test-sdk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-test-sdk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-test-sdk
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/taghive/Programming/Code/electron-test-sdk/npm-debug.log
```
They result in same error whether I have the logging set to true or not

**Comment by DeerMichel** [comment] 2019-07-10 16:28
Oki, what happens when you run Electron with the `--no-sandbox` parameter? I'll try to reproduce it as soon as I get my hands on a Linux machine.

**Comment by DeerMichel** [comment] 2019-07-11 21:13
Yep, confirmed as a duplicate of #18547. If you run it like `npm start -- --no-sandbox`, it'll work. As proposed in the original issue, we'll add a verbose message saying the `--no-sandbox` parameter is necessary when running as root.

**Closed by DeerMichel** 2019-07-11 21:13 UTC
Labels: 5-0-x, blocked/need-info ❌, bug :beetle:, platform/linux
