### ISSUE TITLE
[Bug]: Picture in picture window doesnt stay within the boundries of the screen 

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [electron/electron#28928] opened 2021-04-29 08:16 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

20H2

### What arch are you using?

x64

### Expected Behavior

PIP window must stay within the boundaries of the screen.

### Actual Behavior

When trying to enlarge the picture in picture window it disappears and doesn't come back until u close and reopen PIP.
See video in issue link for more context.
FreeTubeApp/FreeTube/issues/1176

**Comment by mlaurencin** [comment] 2021-04-29 21:50
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.

Thanks in advance! Your help is appreciated.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-05-26 20:11
@mlaurencin im unable to make a testcase. I'm really not that technical.

**Comment by VerteDinde** [comment] 2022-09-15 22:54
Thanks for reporting this issue! This is no longer a supported version of Electron, and has not seen activity for roughly a year, so I'm going to close this issue. If the FreeTube maintainers are seeing this issue in the supported versions of Electron, please feel free to open a new issue! 🙇‍♀️

**Closed by VerteDinde** 2022-09-15 22:54 UTC
Labels: bug :beetle:, blocked/need-repro, 12-x-y
