### ISSUE TITLE
How to  Consume rest api 

### ISSUE THREAD

**Issue by RamakantVerma** [electron/electron#5283] opened 2016-04-25 06:53 UTC
I m working an application which talks to a wcf rest service.
I am using jquery to call WCF rest service which return the json data and making the UI changes.
But jquery is not able to call wcf rest service at all.

Here is my json data that i am getting from service
[
  {
    "Code": null,
    "LanguageId": 528,
    "LanguageName": "Assamese"
  },
  {
    "Code": null,
    "LanguageId": 518,
    "LanguageName": "Bengali"
  },
  {
    "Code": null,
    "LanguageId": 508,
    "LanguageName": "Gujarathi"
  },
  {
    "Code": null,
    "LanguageId": 501,
    "LanguageName": "Hindi"
  }
  ]
Here is the jQuery code I m using 
 $.ajax({url: "http://localhost:57788/Service1.svc/GetTblLanguage_SELAll/0", success: function(result){
       $.each(result,function (key, value){
                $("ddlMotherTongue").append("<Option>"+ value.LanguageName+"</Option>");
      });
    }});

I Checked the index.html page running in web browser its running fine (Mean i am able to hit the service and get data back) but same code is not working in electron.

Is it possible to call the service and render the data in UI or may simple CRUD operation.
Or do i require some kind of HTTP protocol registration or implementation to work with rest service

**Comment by wmonk** [comment] 2016-04-25 11:15
`$("ddlMotherTongue").append(""+ value.LanguageName+"");`

Looks like your selector is invalid.

**Comment by MarshallOfSound** [comment] 2016-04-25 13:51
jQuery requires the DOM and certain browser global methods to be available to function correctly.  This means it won't correctly function inside the main process of an electron app.  To consume a rest service from the main process you should use something like https://www.npmjs.com/package/request

**Comment by baconface** [comment] 2016-04-25 19:55
Does your developer console in Electron indicate that jQuery is unavailable via $? If so I think the problem is context issues. If you have ```nodeIntegration``` set for the window it will attempt to load jQuery in the node context and not a regular browser context. As a result you will need to set ```nodeIntegration``` to false if you don't need it or require jQuery or assign it's ```module.exports``` to ```window.$```.

**Comment by zcbenz** [comment] 2016-04-26 02:12
Closing since this is a question and has been answered.

**Closed by zcbenz** 2016-04-26 02:12 UTC

**Comment by RamakantVerma** [comment] 2016-04-26 06:54
thanx a lot wmonk, MarshallOfSound ,baconface
It was Jquery issue only . As it was working fine in browser window no in desktop so did not get doubt on Jquery.
