### ISSUE TITLE
[Feature Request] Support CSD in Wayland

### ISSUE THREAD

**Issue by memeplex** [electron/electron#27522] opened 2021-01-27 19:03 UTC
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem Description**

In Wayland clients usually render their own decorations, they don't get SSD anymore (although there seems to be a protocol for SSD negotiation that Plasma and some compositors based on wlroots implement). The Wayland build is not very useful until Electron app windows get a proper headerbar. The headerbar can be a stock headerbar similar to old-school SSD or can be customized by the app (for example, by setting its color/theme in accordance with the app contents). 

**Proposed Solution**

Use GTK CSD support, which is also well-integrated in Qt-based environments (mainly Plasma):

https://developer.gnome.org/gtk3/stable/GtkHeaderBar.html:

```
void gtk_header_bar_set_show_close_button (GtkHeaderBar *bar, gboolean setting);

Sets whether this header bar shows the standard window decorations, including close, maximize, and minimize.
```

https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-decoration-layout:

```
“gtk-decoration-layout”    char *

This setting determines which buttons should be put in the titlebar of client-side decorated windows, and whether they should be placed at the left of right.
```

**Alternatives Considered**

It doesn't seem to exist much more alternatives. Maybe Qt has a native headerbar implementation, but it won't properly work inside a GTK-based environment like GNOME, while it works the other way around. See https://pointieststick.com/2019/11/30/this-week-in-kde-gtk-csd-support-and-more

Maybe xdg-decoration as suggested in some comments below. But I ignore everything about it and SSD doesn't seem to me the best alternative for Electron apps that tend to be more app-centric than platform-centric by its very nature and so, at least in major platforms, usually customize headerbars.

**Additional Information**

More details in discussion starting from https://github.com/electron/electron/issues/10915#issuecomment-767997150

**Comment by Xyene** [comment] 2021-01-27 20:03
Leaving aside the meat of this request, I did want to point out one misconception:

> In Wayland all clients have to render their own decorations, there are no SSD anymore.

This is not true.

There exists a protocol (`xdg-decoration`) that at least KDE and Sway/wlroots implement, allowing negotiation of SSDs. What _is_ true is that GNOME have made it very clear they will not implement this protocol, such that applications wishing to have decorations on GNOME _must_ implement CSDs.

See:

- https://gitlab.gnome.org/GNOME/mutter/-/issues/217
- https://blog.martin-graesslin.com/blog/2018/01/server-side-decorations-and-wayland/
- https://blogs.gnome.org/tbernard/2018/01/26/csd-initiative/

**Comment by ckerr** [comment] 2021-01-27 20:03
Thanks for the suggestion!

I know the Electron project would be very happy to have better Wayland support but I don't think there is anyone on the project actively working on this right now. If anyone in the community wants to contribute work to this, I for one would be very happy about that.

**Comment by ZanderBrown** [comment] 2021-01-27 20:08
> There exists a protocol

An unstable optional/extension protocol when even states that a valid `xdg-decoration` implementation doesn't actually have to support SSD, so whilst it may be something electron is interested in it **is not** the solution you are looking for as even when `xdg-decoration` is present (and at least on GNOME it isn't) it may not do anything

**Comment by memeplex** [comment] 2021-01-27 20:17
>> In Wayland all clients have to render their own decorations, there are no SSD anymore.

> This is not true.

I didn't know about xdg-decoration, I edited the description to account for this. Thank you.

**Comment by Xyene** [comment] 2021-01-27 20:24
> .. so whilst it may be something electron is interested in it **is not** the solution you are looking for ...

Yes, agreed, I was only pointing out against the (probably unintentional) absolutist "there are _no_ SSDs [in Wayland]" (emphasis mine). There is an extension for negotiating SSDs that KDE and wlroots implement. It's not supported by GNOME. Electron doesn't strictly use core Wayland protocols. Leaving aside personal opinions on the matter, this is the current state of decorations on Wayland :)

>  I edited the description to account for this.

Note that KDE's Wayland support isn't based on wlroots :)

**Comment by memeplex** [comment] 2021-01-27 20:52
I remember having read the post by Tobias @Xyene linked at the time, I mean https://blogs.gnome.org/tbernard/2018/01/26/csd-initiative/. Rereading it now I realize Electron was mentioned as a potentially easy case:

> Many Electron apps might be low-hanging fruit, because they already use CSD on macOS. This means it should be possible to make this happen on GNU/Linux as well without major changes to the app. However, some underlying work in Electron to expose the necessary settings to apps might be required first.

**Comment by ZanderBrown** [comment] 2021-01-27 20:55
Note Tobias made that comment from the perspective of app developers using it, not electron providing it

**Comment by memeplex** [comment] 2021-01-27 20:59
> Note Tobias made that comment from the perspective of app developers using it, not electron providing it

Yes, that's true, but I assume that the fact that apps are doing this in MacOS, combining their own widgets with platform provided ones in a coherent way, means that the abstractions are right there in Electron and we need to implement them, not define them. I ignore everything about Electron, TBH, so I'm going to take a look later.

**Comment by christianrauch** [comment] 2021-03-04 21:58
Just want to add here that [`libdecor`](https://gitlab.gnome.org/jadahl/libdecoration) could be used specifically to implement client-side decorations under Wayland.

**Comment by stalkerg** [comment] 2021-03-16 08:24
@christianrauch I can't see any much activities there it looks like a prototype. Also, it does not support Enignlement.

**Comment by christianrauch** [comment] 2021-03-16 10:07
> I can't see any much activities there it looks like a prototype.

What activity would you expect? `libdecor` is a library that only implements window decorations, nothing more. If you need a specific feature, you can open an issue and we can review how feasible this is.
I hereby officially invite you to become active in the project :-)

> Also, it does not support Enignlement.

What is "Enignlement"? Is it an application? If the decorations don't work as expected with your application then please open an issue so we can review if this is an issue with `libdecor` or the client application.

**Comment by jokeyrhyme** [comment] 2021-03-16 19:34
Possibly a reference to the Enlightenment desktop/compositor, which does support client-side decorations in wayland: https://www.enlightenment.org/about-wayland

**Comment by rohmishra** [comment] 2021-03-19 09:39
_I'm looking for clarification and also take this with a grain of salt since it's been a while since I last worked on anything electron but:_

AFAIR the buttons used in mac and windows were a bit more bespoke/custom than they looked because since windows & mac is a singular platform we knew where the buttons had to be and how they looked so apps just implemented buttons looking like that (and I guess on mac you can request the system to draw the buttons for you). But for true CSD support on Linux it's not that simple because on Linux you can configure where you want the buttons, which buttons do you want and how the buttons look. So for true CSD the apps need to implement a way to handle button arrangement so that it follows the system style (left/right, which buttons) and either devise a way to make sure current button style looks good/usable with their app theme or just use custom assets for the icon.

Which leads me to my conclusion/questions/clarification:

- What's missing is a way for apps to read `gtk-decoration-layout` easily. But once apps can read that, apps can replicate (with a bit or rework and code sharing between Linux left side decoration/mac and right side/windows) button layout and apps should feel more in line with native apps as far as layout goes. (Or is it possible just never done?)
- there still are edge cases for buttons outside of the standard close, minimize, restore or systems like elementary which has button on both sides where apps need to have more flexible solution for their headers.
- this only works for apps that have window decorations mixed with their layout and apps are explicitly responsible for placing them like vscode but not apps that usually have system draw decorations for them (native window frame in vsc and other apps/almost all electron apps currently on Linux) so electron still needs to ship something (eg. libdecoration) to draw the buttons for those apps behind the scenes. 
- developers still have to implement it or use a library that does most of the heavy lifting for them especially if they plan to support more exotic decoration config or using system assets for buttons

**Comment by WhyNotHugo** [comment] 2021-03-19 11:37
@rohmishra You are correct.

In reality, Server Side Decorations are the simplest way to implement thing for developers: applications will be drawn with buttons (and everything else) in whichever way the user configured it in whatever desktop they may be using. It's what works almost everywhere, and works best.

Gnome is the notable exception, since it requires applications to use CSD. This forces applications to have explicit support for Gnome (my understand is that it's to kinda force applications to have dedicated Gnome-support, further pulling them into the Gnome/Gtk ecosystem).

I don't think there's any way to have _customised_ decorations with SSDs though; it's generally an all-or-nothing kind of thing.

**Comment by ZanderBrown** [comment] 2021-03-19 15:24
> In reality, Server Side Decorations are the simplest way to implement thing for developers: applications will be drawn with buttons (and everything else) in whichever way the user configured it in whatever desktop they may be using. It's what works almost everywhere

Except Wayland (and yes **Wayland** not GNOME), so a no-go

**Comment by WhyNotHugo** [comment] 2021-03-19 17:30
> Except Wayland (and yes Wayland not GNOME), so a no-go

What are you talking about? Wayland itself support SSDs just fine. It's merely GNOME that has decided not to support it. This is why applications require special support for GNOME, other compositors implement SSDs.

**Comment by ZanderBrown** [comment] 2021-03-19 19:18
> Wayland itself support SSDs just fine. 

No it doesn't, the Wayland spec has no concept of decorations

**Comment by oscarkey** [comment] 2021-03-19 19:21
To avoid going in circles about Wayland support for SSDs, please see the second comment in this thread: https://github.com/electron/electron/issues/27522#issuecomment-768542543

**Comment by rohmishra** [comment] 2021-03-20 03:04
It seems that wayland itself doesnt require SSD. While there is a protocol to implement SSD (just like there is a protocol to implement screen capture, pipewire) but it isnt part of wayland itself. So to be compliant with wayland electron HAS to draw its own decorations because wayland allows compositors to not care about decoration it they dont want to.

In addition we also need a way for electron apps to be able to read layout so that if apps want to implement their own button style (like in ss below, true CSD), they know where to place them.

eg. 
![CSD buttons](https://user-images.githubusercontent.com/2221064/111857339-272d7900-8907-11eb-9845-b519b381f7b4.png)

**Comment by eternal-sorrow** [comment] 2021-03-20 03:16
>While there is a protocol to implement SSD (just like there is a protocol to implement screen capture, pipewire) but it isnt part of wayland itself

That's not correct. Pipewire (and xdg-desktop-portal for that matter) is not a wayland protocol indeed. But xdg-decoration is a [wayland protocol](/wayland-protocols/blob/master/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml).

**Comment by rohmishra** [comment] 2021-03-20 03:27
> > While there is a protocol to implement SSD (just like there is a protocol to implement screen capture, pipewire) but it isnt part of wayland itself
> 
> That's not correct. Pipewire (and xdg-desktop-portal for that matter) is not a wayland protocol indeed. But xdg-decoration is a [wayland protocol](/wayland-project/wayland-protocols/blob/master/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml).

Oh, I was mistaken about it. Sorry About that.

```
      A client can use this protocol to request being decorated by a supporting
      compositor.

      If compositor and client do not negotiate the use of a server-side
      decoration using this protocol, clients continue to self-decorate as they
      see fit.
```

It does seem that the protocol implies that decorations might not be implemented by compositor and apps should have some fallback regardless.

**Comment by jokeyrhyme** [comment] 2021-03-20 03:34
I'd suggest that we don't need to get button placement and sequence perfect on the first try

We mostly just need to detect when SSD is not provided/negotiated, and draw a CSD with an exit button, at a minimum

Offering some sort of customisation or WM-detection that puts CSD buttons in the correct WM-specific conventional sequence could come later

**Comment by rohmishra** [comment] 2021-03-20 03:48
@jokeyrhyme Since we already depend on gtk which does provide GtkHeaderBar, is it not possible to just ask toolkit (gtk) to draw it for us like you can with regular gtk apps?

**Comment by ZanderBrown** [comment] 2021-03-20 03:57
*wonders if people [actually read prior comments](https://github.com/electron/electron/issues/27522#issuecomment-768545473)*

It would seem to me making use of GtkHeaderBar/GtkWindowControls would make sense for electron (the latter requiring gtk4, though you could implement it for gtk3), the alternative being [libdeco(ration)](https://gitlab.gnome.org/jadahl/libdecoration)

Whilst electron could try to parse `gtk-decoration-layout` I'm not sure it's A) worth the effort B) simpler than using GtkHeaderBar/GtkWindowControls

**Comment by eternal-sorrow** [comment] 2021-03-20 04:40
Does chrome/ium not have its own titlebar? You can enable it by right-clicking on empty space in the tab panel. Can it be utilised in electron?

**Comment by rohmishra** [comment] 2021-03-20 04:40
@ZanderBrown parsing gtk-decoration-layout  (+ GtkWindowControls) would allow apps to implement their own controls like they do on other platforms ( eg. [slack](https://a.slack-edge.com/c5da2d2/marketing/img/downloads/refreshed/slack-client-windows-desktop.png), [discord](https://support.discord.com/hc/article_attachments/360061122851/switching_participants_multistream_demo.gif), [slack](https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4MEwE?ver=0c05&q=90&h=700&w=1920&b=%23FFFFFFFF&aim=true) ) while respecting the layout and button configuration.

Just adding back the HeaderBar brings us back to what we have currently. Most apps just display the system bar on linux while they have custom implementation on Mac/Windows or apps like VSCode while look good if your system follows the same layout it uses.

Ability for apps to read the system layout needs to be added regardless if we want electron apps to implement custom window buttons like they do for other platforms and not be shouted at by community for not following the system layout.

**Comment by ZanderBrown** [comment] 2021-03-20 09:53
If your using GtkWindowControls you don't need to care about `gtk-decoration-layout`, that's somewhat the point - you just have one GtkWindowControls on the left and another on the right and gtk figures out the buttons for you

**Comment by christianrauch** [comment] 2021-03-20 10:36
The focus of this discussion should be the integration of CSD on Wayland (as the title says). Using custom widgets or `GtKWindowControls` to create "integrated decorations" like Visual Studio Code does will obviously also apply to X11 and is not Wayland specific. Requesting these "integrated decorations" should be a dedicated issue.

The limiting factor to get proper Wayland support in Electron is when a developer does not want to implement custom decorations and just wants to use a standard titlebar, e.g. as displayed with XWayland.

In this case, Electron should either:
1. use GTK directly and render all Electron content into a widget
2. draw GTK widgets the "Firefox" style (i.e. assemble a titlebar manually using the GTK widgets)
3. use a third-party library to draw decorations

**Comment by diamondburned** [comment] 2021-03-20 10:48
> draw GTK widgets the "Firefox" style (i.e. assemble a titlebar manually using the GTK widgets)

This is probably a big hack, but:

1. [libhandy'sHdyWindowBin](https://gnome.pages.gitlab.gnome.org/libhandy/doc/1-latest/HdyWindowHandle.html) allows a region to be drag-and-droppable like a header bar.
2. [libhandy's HdyWindow](https://gnome.pages.gitlab.gnome.org/libhandy/doc/1-latest/HdyWindow.html) allows a window with an arbitrary header bar to still have rounded corners.
2. [libhandy's HdyHeaderBar](https://gnome.pages.gitlab.gnome.org/libhandy/doc/1-latest/HdyHeaderBar.html) can probably be CSS-themed to only show close buttons by forcing the background to be transparent.

**Comment by christianrauch** [comment] 2021-03-20 10:58
> > draw GTK widgets the "Firefox" style (i.e. assemble a titlebar manually using the GTK widgets)
> 
> This is probably a big hack, but:
> 
> 1. [libhandy's HdyWindowBin](https://gnome.pages.gitlab.gnome.org/libhandy/doc/1-latest/HdyWindowHandle.html) allows a region to be draggable like a header bar.
> 2. [libhandy's HdyWindow](https://gnome.pages.gitlab.gnome.org/libhandy/doc/1-latest/HdyWindow.html) allows a window with an arbitrary header bar to still have rounded corners.
> 3. [libhandy's HdyHeaderBar](https://gnome.pages.gitlab.gnome.org/libhandy/doc/1-latest/HdyHeaderBar.html) can probably be CSS-themed to only show close buttons by forcing the background to be transparent.

With "assemble a titlebar manually" I meant to draw that titlbar background, the title itself and the window control buttons manually like Firefox does, but skip any custom widgets.
If you want to mix the decoration and content in any other way using `libhandy`, e.g. showing window control buttons within the application content, then this again will apply to X11 too and is irrelevant to solving the Wayland specific problem.

**Comment by ZanderBrown** [comment] 2021-03-20 12:37
If you just want to draw a plain GtkHeaderBar don't mess around with manually packing stuff etc - just use GtkHeaderBar

If you want macOS style buttons-in-window (which I thought was the point of this issue) that's two GtkWindowControls, the notable differences being that you do need two (depending on the layout controls may be located on the left or right or both) and, perhaps more significantly, you can't predict the area covered by controls

**Comment by stalkerg** [comment] 2021-03-22 01:04
In all this discussion please don't forget about KDE/Plasma users and the SSD cases under Wayland.

**Comment by iMonZ** [comment] 2021-03-22 09:12
Hey, anything new here?
This issue is really important for future Linux support!

**Comment by WhyNotHugo** [comment] 2021-03-22 09:17
> In all this discussion please don't forget about KDE/Plasma users and the SSD cases under Wayland.

Yes, I've made emphasis how this feature is only required for GNOME exactly due to this item. It's really the only compositor that **requires** CSD, while all other provide SSD.

This'll make developer's life a pain though, since they'll basically need to target two distinct platform: Linux-GNOME and Linux-not-GNOME.

**Comment by Exalm** [comment] 2021-03-22 09:38
https://github.com/wayland-project/wayland-protocols/blob/master/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml#L115-L122

Quoting:

```
        The compositor can decide not to use the client's mode and enforce a
        different mode instead.
```

In other words, xdg-decoration requires CSD to work. You can make an implementation where the compositor always passes `mode=1` in `configure` and ignores the client preference (as it's just a hint), it will be perfectly valid. So yes, if you want to support xdg-decoration, you must support CSD _and_ SSD. You can downvote me if you want to, but it doesn't change the reality. 🤷️

Also, a reminder that Weston and Enlightenment exist. And one of them is a reference compositor. If your app doesn't work correctly on the reference compositor...

**Comment by stalkerg** [comment] 2021-03-22 14:19
> but it doesn't change the reality. 

I suppose everybody agrees. But maybe for the first implementation not so important to implement gtk/gnome-like decorations, just something will be enough. 

> And one of them is a reference compositor. 

Weston is mostly an example compositor, they thought about SSR but want to keep this as simplest as possible because it's an example.

**Comment by ZanderBrown** [comment] 2021-03-22 14:29
> maybe for the first implementation not so important to implement gtk/gnome-like decorations, just something will be enough

Right, using GtkWindowControl embedded in content is a nice added extra. Just a plain GtkHeaderBar (since electron is somewhat already using Gtk) would do - or even a libdecor simple draggable box with close button

> Weston is mostly an example compositor

Yes implements just the core spec **which doesn't include xdg-decoration**. That's somewhat the point.

**Comment by stalkerg** [comment] 2021-03-23 00:24
> This'll make developer's life a pain though, since they'll basically need to target two distinct platform: Linux-GNOME and Linux-not-GNOME.

yes, it's why I don't want to support CSD in my own application, just not enough time for this journey. 

> Yes, I've made emphasis how this feature is only required for GNOME exactly due to this item. It's really the only compositor that requires CSD, while all other provide SSD.

yes, but if you will add some extra logic into the header like the GNOME application it will not working under KDE or looking weird (two titlebars). It's why we have some limitations on CSD if we want also to support SSD.

**Comment by rohmishra** [comment] 2021-03-27 03:30
> yes, but if you will add some extra logic into the header like the GNOME application it will not working under KDE or looking weird (two titlebars). It's why we have some limitations on CSD if we want also to support SSD. 

It would are forcing SSD (KDE supports CSD too) then the window controls should be displayed by your compositor but any extra controls will be drawn by the app, just like how gtk apps behave with compositor titlebars.

**Comment by kennylevinsen** [comment] 2021-03-28 13:01
> Yes implements just the core spec which doesn't include xdg-decoration. That's somewhat the point.

The core spec cannot open a window (ignoring the deprecated and largely unsupported wl_shell).

wayland-protocols is a collection of additional shared protocols. While the "stable" xdg-shell protocol will be used to create windows, you will also be using protocols from the "unstable" set—at the very least linux-dmabuf for GPU buffers. You will likely also use the unstable primary-selection protocol for X11-style clipboard, text-input for IME support, tablet for drawing tablet tool integration, and so forth.

All the protocols in there are *optional* and may or may not be provided by a given Wayland compositor, including xdg-shell and linux-dmabuf. Compositor developers decide which they provide, application developers decide which they use and which they require. GNOME not wishing to support xdg-decoration, while slightly frustrating, is not particularly weird—other compositors exclude other protocols after all. And yes, compositors not implementing xdg-shell are more common that you would think.

Chromium and Gtk uses many unstable protocols. Gtk even supports server-side decorations—even though Mutter does not support it—through the pre-cursor to xdg-decoration, the "super-unstable" org-kde-kwin-server-decoration-manager.

With all that out of the way, all that remains is the question as to whether support for server-side decoration is wanted. If wanted, xdg-decoration is the preferred way to request a decoration mode.

---
Links:

1. Protocols used by Gtk/Gdk: https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gdk/wayland/meson.build#L47
2. Protocols used by Chromium: https://github.com/chromium/chromium/tree/master/third_party/wayland-protocols/unstable (note: contains non-upstreamed protocols despite the folder name)
3. Gtk/Gdk server-side decoration functionality: https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gtk/gtkwindow.c#L3067, https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gtk/gtkwindow.c#L2980 and https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gdk/wayland/gdksurface-wayland.c#L2248. `gtk_window_set_decorated(win, FALSE)` or `gtk_window_set_titlebar(win, NULL)` will enable server-side decorations.
2. Discussion about changing the stable/unstable separation and protocol maturity flow: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/30

**Comment by WhyNotHugo** [comment] 2021-06-11 12:58
Looks like this is a duplicate of #27016

**Closed** 2022-01-26 21:59 UTC
Labels: enhancement :sparkles:
