### ISSUE TITLE
[Feature Request]: Electron Clipboard onChange eventListener

### ISSUE THREAD

**Issue by AhnafS** [electron/electron#35060] opened 2022-07-26 01:56 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Im trying to create an app that is highly dependent on the keyboard, as it's an easy and efficient way to transfer short-term data for my project. The problem that I have encountered is that I need to run few commands each time the clipboard changes, but cannot do so with the electron clipboard api

### Proposed Solution

Create an event emitter for the clipboard api

### Alternatives Considered

none

**Comment by Prinzhorn** [comment] 2022-07-26 06:39
https://github.com/electron/electron/search?q=Clipboard+event&type=issues
https://github.com/electron/electron/issues/2280
https://www.npmjs.com/search?q=clipboard%20event

I don't know if anything has changed in Chromium since 2018 or if #2280 is outdated.

**Comment by clavin** [comment] 2022-07-27 20:08
Closing this as a duplicate of #2280.

This functionality doesn't already exist in Chromium cross-platform, so we believe this should instead be implemented in a native module instead of the Electron core. If Chromium does implement this functionality in the future (e.g. to support the widely-unsupported `clipboardchange` event) then we'd be happy to think about this feature request again.

**Closed by clavin** 2022-07-27 20:08 UTC
Labels: enhancement :sparkles:

**Comment by mraheelkhan** [comment] 2023-07-30 20:24
@clavin , Hi,  so it's been a year, is there any update on this feature request?

**Comment by felipecrs** [comment] 2024-01-12 17:25
For anyone interested in this feature, I suggest you star this crbug: https://bugs.chromium.org/p/chromium/issues/detail?id=933608
