### ISSUE TITLE
[Bug]: unable to open window from window created with native window open

### ISSUE THREAD

**Issue by naineshsolanki-lmi** [electron/electron#29094] opened 2021-05-10 22:16 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

11.4.5

### Expected Behavior

With either the `sandbox` option or the `nativeWindowOpen` option enabled:

When you open a new window using `window.open` from a window that is created using `window.open`, I expect to see 3 windows rendering their own html.

### Actual Behavior

When you open a new window using `window.open` from a window that is created using `window.open`, the second window goes blank (white screen). Closing either of these two windows closes the other window.

Step to reproduce:
+ Run the attached sample:
+ Click open window to create a new window
+ Click open window from the new window to create third window
+ Observe second window is blank

### Testcase Gist URL

https://gist.github.com/naineshsolanki-lmi/587f79ad7a4f0c794f9561f9ec85b389

**Comment by dharesign** [comment] 2021-06-01 23:08
The windows all seem to open, just the content doesn't seem to be in the correct OS window.

If you have a `BrowserWindow` load `1.html`, and then `1.js` `window.open` `2.html`, and then `2.js` `window.open` `3.html`, when the third window opens, the contents of the original second window gets reparented there, and the contents of the third window is nowhere to be seen.  Its actually present somewhere though, because you can continue going and have `3.js` load `4.html`.  I went up to `6.html` and ended up with 6 windows showing:

1. `1.html` (from browser window)
1. blank (was initially `2.html`)
1. `2.html` (should be 3)
1. blank (was initially `4.html`)
1. `4.html` (should be 5)
1. `6.html`

The blank windows seem to have their lifetime tied to the window that's actually showing the content that should be in them, so if you close window 2, window 3 also closes. If you close window 3, window 2 also closes.

**Comment by dharesign** [comment] 2021-06-02 00:22
Note this is the same as #28217, and it also behaves incorrectly on Windows (though the contents of the windows there are slightly different to the above situation on macOS).

**Comment by dharesign** [comment] 2021-06-02 03:19
This seems fixed in `v14.0.0-beta.2`.

**Comment by dharesign** [comment] 2021-06-02 03:52
Trying different versions from `electron-nightly`, `v14.0.0-nightly.20210413` is broken, and `v14.0.0-nightly.20210426` is fixed.  There doesn't seem to be any intermediate versions published to npm.

https://github.com/electron/electron/compare/v14.0.0-nightly.20210413...v14.0.0-nightly.20210426

**Comment by naineshsolanki-lmi** [comment] 2021-06-16 21:01
Any plans to back port the fix to v13.x.y and/or 12.x.y?

**Comment by jupp0r** [comment] 2021-06-17 07:47
Just a wild guess: could it be this change that fixed it? https://github.com/electron/electron/commit/4ca518468d015a2d78524cad88e9917775921232#diff-20475bc1b5be1a77156c1b370b9e5c1f813ae1f5cb6c4b989429e384d6742f9f

**Comment by nornagon** [comment] 2021-06-17 18:21
@jupp0r hm... that particular change is only relevant when there's a _non_-nativeWindowOpen window in the mix, which isn't the case in the gist in the top post here. That PR did change some other stuff related to nativeWindowOpen though, and it is in the range mentioned by https://github.com/electron/electron/issues/29094#issuecomment-852696916, so it's possible a different fix in there was the cause.

**Comment by nornagon** [comment] 2021-06-17 21:01
Duplicate of #28217

**Closed by nornagon** 2021-06-17 21:01 UTC
Labels: 12-x-y, 13-x-y, bug :beetle:
