### ISSUE TITLE
[Bug]: Empty dictionarySuggestions on Windows since electron 13.x

### ISSUE THREAD

**Issue by EtienneLem** [electron/electron#29685] opened 2021-06-14 16:19 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 2004

### What arch are you using?

x64

### Last Known Working Electron version

12.0.11

### Expected Behavior

`dictionarySuggestions` is expected to have suggestions.

### Actual Behavior

`dictionarySuggestions` is empty.

### Additional Information

Reminiscent of #24455, but it probably is a different issue given the difference of how spellchecking works on each platform.

### electron 12
```
electron 12.0.11
chrome 89.0.4389.128

misspelledWord: Houuse
dictionarySuggestions: [ 'House', 'Housed', 'Houses', 'Housel', 'Houser' ]
session.getSpellCheckerLanguages: [ 'en-GB', 'en-US' ]
```

### electron 13
```
electron 13.1.2
chrome 91.0.4472.77

misspelledWord: Houuse
dictionarySuggestions: []
session.getSpellCheckerLanguages: [ 'en-GB', 'en-US' ]
```

**Comment by MarshallOfSound** [comment] 2021-06-14 19:23
@EtienneLem Can you launch your app with `--disable-features=WinRetrieveSuggestionsOnlyOnDemand` and test again?

**Comment by EtienneLem** [comment] 2021-06-14 19:30
@MarshallOfSound It does work with this flag. Getting suggestions when launching the app with

```sh
electron --disable-features=WinRetrieveSuggestionsOnlyOnDemand .
```

**Comment by MarshallOfSound** [comment] 2021-06-14 19:40
Sweet, you can use `app.commandLine.appendSwitch` to add that flag at runtime while we work on getting it into an actual release, that's our bad, totally knew about this but PRing it into Electron slipped through the cracks 😄

**Comment by Jelmerro** [comment] 2021-06-14 19:41
This issue is probably related, and is affecting electron 12 (and also 13 of course): https://github.com/electron/electron/issues/28684

**Comment by MarshallOfSound** [comment] 2021-06-14 19:44
@Jelmerro Please don't thread snipe similar issues, if your issue is also fixed by the above flag then awesome that's great info to share, otherwise please keep discussion to that other thread so that the issue tracker remains clean and followable 😄

**Comment by Jelmerro** [comment] 2021-06-14 19:48
I just thought the two might be related, no need to accuse me of thread sniping right away. I just thought that with so many open issues it would help to group the ones that are similar...

**Comment by VerteDinde** [comment] 2021-06-14 20:45
Sorry all, I had committed the PR to this and dropped it, that's on me - a fix should be in shortly! 🙇‍♀️ 

@Jelmerro Just took a quick look at your issue, and I unfortunately don't think it's related to the same underlying root cause. As @MarshallOfSound mentioned, we try to keep our issue and conversations in them as distinct as possible, so that issues are easier to follow, track, and fix. 🙂 I just took a look at your Fiddle gist and will drop a question in your original issue - we can keep speaking there. Thanks!

**Comment by Jelmerro** [comment] 2021-06-14 20:55
The cause seems unrelated indeed, the result is simply the same, but for a different reason. I jumped on the "since version 13" part of this issue and remembered the other one, which seemed the same on the surface, so I decided to link it just in case, but if they have a different cause that's also fine.

**Closed** 2021-06-15 16:11 UTC
Labels: 13-x-y, 14-x-y, bug :beetle:, platform/windows
