### ISSUE TITLE
Why is electron more blur than chrome?

### ISSUE THREAD

**Issue by blackknifes** [electron/electron#14105] opened 2018-08-15 08:52 UTC
* Electron Version: 2.0.7 and 3.0.0-beta5
* Operating System (Platform and Version): Windows7 7601
* Last known working Electron version: 3.0.0-beta5

**Expected Behavior**
Render behavior of electron is the same as chrome.

**Actual behavior**
![capture](https://user-images.githubusercontent.com/9638801/44139810-c1ef704e-a0aa-11e8-9017-227ce675c773.png)
left: chrome    right: electron-3.0.0-beta5 + electron-vue
Electron is more blur than chrome.

**Comment by gribunin** [comment] 2018-08-16 14:05
Try to specify backgroundcolor for a Browserwindow when creating it:

`w = new BrowserWindow({
        ...
        backgroundColor: "#FFF"
    });`

**Comment by gribunin** [comment] 2018-08-17 15:35
#10025 -- This is the corresponding issue

**Comment by gribunin** [comment] 2018-08-17 16:37
It seems that at the moment content of <webview> always has grayscale antialiasing no matter what and there is no way to specify backgroundcolor and no workaround for it. I mentioned that in the issue #10025, don't have answer yet. Very serious bug from my point of view.

**Comment by blackknifes** [comment] 2018-08-17 16:59
Thanks, I hope electron 3.0.x release version resolve this bug.

**Comment by ckerr** [comment] 2018-08-23 00:03
Closing this as a duplicate of #10025 as per @gribunin's comment.

**Closed** 2018-08-29 15:36 UTC
Labels: bug :beetle:, platform/windows, version/2.0.x, version/3.0.x
