### ISSUE TITLE
Enable the JS flag --harmony to enable Harmony features in the main process

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#8538] opened 2017-01-30 14:13 UTC
* Electron version: 1.5
* Operating system: macOS

### Expected behavior

When I run electron with the command `electron --js-flags="--harmony"` all Harmony features should be enabled.

### Actual behavior

Harmony features are not enabled. I have to specify exact flags, using a command such as `electron --js-flags="--harmony-async-await"`

**Comment by kevinsawicki** [comment] 2017-01-30 18:16
Having a little trouble reproducing this. I'm able to create an async function in the dev tools on 1.5.0 when running with `--js-flags="--harmony"`.

<img width="1680" alt="screen shot 2017-01-30 at 10 14 49 am" src="https://cloud.githubusercontent.com/assets/671378/22435480/0ac13f28-e6d5-11e6-81dc-51ab1b34cdcc.png">

Can you log out `process.argv` and `process.versions.electron` in the dev tools and verify you are on 1.5.0 and you see the harmony option in there?

**Comment by kirkouimet** [comment] 2017-02-02 06:47
OK so I figured out this was a weird one, I was actually directly opening a .js file instead of a .html file.

This successfully enables all Harmony features:

`electron --js-flags="--harmony" index.html`

This does not enable any Harmony features:

`electron --js-flags="--harmony" index.js`

This successfully enables a Harmony feature:

`electron --js-flags="--harmony-async-await" index.js`

**Comment by kevinsawicki** [comment] 2017-02-03 17:31
@kirkouimet yes, I can reproduce the same behavior, thanks for investigating further.

This doc for `--harmony` states "(enable all completed harmony features)" so perhaps that list of complete features is being interpreted differently in the main process vs. the renderer process.

For now I'd recommend using `--harmony-async-await` if you are trying to use async functions in the main process in the current Electron release.

It looks like `harmony-async-await` was removed in Chrome 55 so the upgrade to Chrome 56 in #8501 should resolve this.

https://codereview.chromium.org/2621173002

I'm going to close this out since it looks like this will be addressed by the Chrome 56 upgrade.

**Closed by kevinsawicki** 2017-02-03 17:31 UTC
Labels: more-information-needed
