### ISSUE TITLE
wrong screen size after restoring from minimize .

### ISSUE THREAD

**Issue by pejman1** [electron/electron#24632] opened 2020-07-17 19:07 UTC
after restoring from minimize the size expands about 10 pixel .
I set min width and min height and use getCurrentWindow().minimize(); function .
I have frame less windows and run app in windows 10
if windows was set to min width and min height after recovering from minimize state it expands the size about 10 pixel
same issue while maximizing and restoring window

applications like what's app which is written by electron has same problem 

I use electron 9.1.0

**Comment by ckerr** [comment] 2020-07-20 15:46
This looks like a duplicate of frameless windows sizing issue @ https://github.com/electron/electron/issues/22393

**Closed by ckerr** 2020-07-20 15:46 UTC
Labels: 9-x-y, bug :beetle:, platform/windows
