### ISSUE TITLE
[Bug]: Electron 13 crashes when running on system with intel 11th generation cpu (cetcompat)

### ISSUE THREAD

**Issue by t57ser** [electron/electron#29335] opened 2021-05-26 11:26 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0

### What operating system are you using?

Windows

### Operating System Version

19042.985

### What arch are you using?

x64

### Last Known Working Electron version

12

### Expected Behavior

no crash

### Actual Behavior

I have not yet managed to create a reproducable example since the app code is quite large and the crash seems to happen randomly based on what gets executed. (I.e. there is a function that compares 2 objects, executing that 66 times will eventually lead to a crash, but only executing it 65 times does not lead to the crash)
This is happening because Chrome introduced CET support https://bugs.chromium.org/p/chromium/issues/detail?id=1131225
when disabling it on the machine the crash does not happen.
Also more info on CET here: https://www.offensive-security.com/offsec/intel-cet-in-action/
Note that this is only happening when using a supported CPU and newer windows version.
Considering that there is only javascript code running from the app side I do not see how this could be an issue within the app code at all. So this is likely on the electron side.
Since electron is anyway building from chrome source I would recommend disabling the flag.
See: https://chromium.googlesource.com/chromium/src/+/ea32df5c92d67c4c8c3cfffb2fd6ee2609da04f0/build/config/compiler/compiler.gni
`enable_cet_shadow_stack = target_cpu == "x64"`
The only workaround I see at the moment is to use x32 builds of electron

### Additional Information
Also see: https://github.com/electron/electron/issues/29160#issuecomment-848065956

**Comment by t57ser** [comment] 2021-05-28 08:51
I made an electron build with the flag disabled and everything is working fine

**Comment by VerteDinde** [comment] 2021-06-02 23:56
Hey @t57ser, thanks so much for reporting this issue! I know it's not easy to get a repro of this and that you fixed it by disabling the flag, but would it be possible for you to share a crash dump file or stack trace?

We're trying to hunt down the root cause of this, and any additional information is appreciated.

**Comment by t57ser** [comment] 2021-06-03 19:27
The crash reporter unfortunately does not work in this case, but I will see what I can get from WinDbg

**Comment by t57ser** [comment] 2021-06-04 07:08
[electron-13-crash.zip](https://github.com/electron/electron/files/6596428/electron-13-crash.zip)

**Comment by t57ser** [comment] 2021-06-04 10:12
other findings: 
- executing garbage collection manually during the comparison seems to prevent the crash
- while trying to reduce app code to a small exmaple, another weird point was found, removing an object.assign within the code stopped the crash from happening

I assume the crash is happening based on how the app uses memory

**Comment by MarshallOfSound** [comment] 2021-06-04 17:51
Fixed in https://github.com/electron/electron/pull/29546 and the latest nightlies should already be fine.

The exact cause is v8 deoptimization being incompatible with cet

**Closed by MarshallOfSound** 2021-06-04 17:51 UTC
Labels: 13-x-y, 14-x-y, bug :beetle:

**Comment by vladimiry** [comment] 2021-06-13 15:15
Thanks to everyone involved in reporting and fixing the issue. It helped with resolving https://github.com/vladimiry/ElectronMail/issues/412 which would be hard to hunt down without @t57ser 's report.

**Comment by vladimiry** [comment] 2021-06-14 15:39
@t57ser if you have tested the case on v14.0.0-beta.x, can you confirm that it's not affected?

**Comment by t57ser** [comment] 2021-06-14 18:32
@vladimiry The fix is already available in electron 13.1.1 and I can confirm it's working. Haven't tested with 14 but I would assume it's the same.

**Comment by vladimiry** [comment] 2021-06-14 18:38
@t57ser I asked because #29546 change didn't come into the `14-x-y` branch yet and because I can't test it on my own since don't have that kind of hardware.
