### ISSUE TITLE
frameless window in windows 10 fulscreen bug

### ISSUE THREAD

**Issue by pejman1** [electron/electron#25610] opened 2020-09-23 22:22 UTC
Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Problem Description
 In new version there is new issue . while I maximize the app it adds 6px border on top of the app in widnows 10
using frameless windows 

* **Electron Version:**
  * 10.1.2

*** **Operating System:**
  *Windows 10 (2004)
* **Last Known Working Electron version:**
  * Version 9

### Expected Behavior
not add any border or change modification to the windows 

### Actual Behavior
while you maximize the windows it add a border on top of the windows **

 ### Screenshots
![Screen Shot 2020-09-24 at 01 43 13 AM](https://user-images.githubusercontent.com/11601344/94075775-a6cf0500-fe08-11ea-9ad7-9bb244a15333.png)

**Comment by codebytere** [comment] 2020-09-23 23:37
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by Slapbox** [comment] 2020-09-24 21:12
Same issue here, first noticed it just today.

----

### Preflight Checklist


* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.5.1
* **Operating System:** Windows 7
* **Last Known Working Electron version:** Unknown. Possibly `8.2.x` - Will confirm this

### Expected Behavior
A maximized window should have x/y coordinates of 0 and any underlying windows should be hidden completely (barring using Electron's window transparency)

### Actual Behavior

In my case the issue is visible on the right edge and the bottom edge, and checking the position with `win.getBounds()`  I see that `x = -8` and `y = -8` when maximized.

### To Reproduce

TBD

### Screenshots
You can see here the line on the right and bottom edge that comes from a setting my desktop background to pure white.

![image](https://user-images.githubusercontent.com/6835891/94200425-66af6700-fe88-11ea-8bad-1bfd56470c95.png)

**Comment by Slapbox** [comment] 2020-09-28 21:49
@codebytere would it be better for me to create a new issue from my comment above, since the initial comment on this issue doesn't follow the issue template?

**Comment by zcbenz** [comment] 2020-10-12 01:51
I'm merging this issue to https://github.com/electron/electron/issues/25746 since according to https://github.com/electron/electron/issues/25746#issuecomment-703125319 they are the same issue, and #25746 has more details.

**Closed by zcbenz** 2020-10-12 01:51 UTC
Labels: 10-x-y, component/BrowserWindow, platform/windows
