### ISSUE TITLE
Submenu can't be disabled

### ISSUE THREAD

**Issue by Dexwell** [electron/electron#9131] opened 2017-04-06 14:56 UTC
* Electron version: 1.6.2
* Operating system: macOS 10.12.4 (Sierra)

### Expected behavior

A disabled submenu should be grayed out and not open when `enabled: false` is set. See Finder > Go > Recent Folder if the user has clicked Clear Menu in that submenu.

### Actual behavior

Submenu is not grayed out and can be opened

### How to reproduce

```javascript
const template = [
{
	label: 'File',
	submenu: [
	{
		label: 'Recent Files',
		enabled: false,
		submenu: [
		{
			label: 'test'
		}
		]
	}
	]
}
]

const menu = Menu.buildFromTemplate(template)
Menu.setApplicationMenu(menu)

```

**Comment by kevinsawicki** [comment] 2017-04-06 15:43
I believe this is a duplicate of #3416

**Closed by kevinsawicki** 2017-04-06 15:43 UTC
