### ISSUE TITLE
remote.app.getPath('appData') escapes / mangles strings on Windows

### ISSUE THREAD

**Issue by framerate** [electron/electron#12102] opened 2018-03-02 18:46 UTC
Thanks guys I could use some help on this one! It very well could be a platform thing, a V8 bug or a react rendering bug. If anyone has experience with this as to why it's different across platforms let me know. Having different behavior on only one of the three platforms definitely seems wrong from a user perspective!

Posting here in case anyone else searches for this obscure problem at least they'll find some info (unlike me!)

* Electron version: 1.7.12 (latest version has other bugs also reported: #10905 )
* Operating system: Windows (Only)

### Expected behavior
Using `remove.app.getPath('appData)` should have the same behavior on all platforms. It should return a string that can be used to create a full path of an image/file.

### Actual behavior
Works great on macOS and Linux, but on Windows the path is escaped and mangled when used in React JSX inside a `url()` call for a background image.
![image](https://user-images.githubusercontent.com/74291/36915649-5246ee4c-1e06-11e8-8f02-c4c4a7175eb9.png)

### How to reproduce
In a react electron app's render function try and set a background image that contains a `getPath('appData')` call.

**Comment by framerate** [comment] 2018-03-02 18:49
As an aside (using react) I was able to do a work around by

`
art.src = `${remote.app.getPath('appData')}/Doomtrooper/assets/cardart/${this.props.card.img}.png`;
art.onload = () => this.setState({art: art.src});
`

Then using `this.state.art` inside the `url()` call. This is such a hack, though. It makes me think maybe the bug is actually in `remote.app.getPath()` since the behavior is consistent once I cache the variable in state AFTER getting it from the `Image()` src instead...

**Comment by framerate** [comment] 2018-03-02 21:55
Also I'm aware that `/` is the escape character which would be why it happens on Windows. I'm just unsure where to start on figuring out the root cause and how to avoid it! Any suggestions are appreciated!

**Comment by ckerr** [comment] 2018-03-05 01:37
Hi @framerate, thanks for reporting this issue. A couple of questions:

> Electron version: 1.7.12 (latest version has other bugs also reported: #10905 )

I don't understand what this means, #10905 seems to be unrelated to this `remote.app.getPath()` issue? Do you mean that you're seeing this behavior in the lastest version as well, or that you haven't tested this issue with newer versions of Electron because #10905 is a blocker for you?

> In a react electron app's render function try and set a background image that contains a getPath('appData') call.

Can you give an example of an expected and actual result that you're seeing, e.g. something that could be added to a test in `spec/api-remote-spec.js`?

**Comment by framerate** [comment] 2018-03-05 01:48
@ckerr Thanks for following up!

> that you haven't tested this issue with newer versions of Electron because #10905 is a blocker for you?

This one, I have to roll back to this version or my build doesn't work currently. Still hoping to figure that one out as well.

> Can you give an example of an expected and actual result that you're seeing,

Maybe. I'm trying to figure out how to make a simple test case to show it, but since it happens with React it's tricky. Also the more I think about the problem the more I think it's a React JSX bug (if so, I apologize but I would rather have this documented for the next guy!

The line that NEVER works (and produced the managed/escaped file path above is:

```js
<div id="avatar" style={{...style.avatar, backgroundImage: `url("${remote.app.getPath('appData')}/Doomtrooper/assets/cardart/${avatar}")`}} />
```

Inside a react `render()` function. It will ALWAYS mangle/escape the appData path, but ONLY on windows.

However, if I do:
```js
        const avatar = new Image(); // eslint-disable-line no-undef
        avatar.src = this.props.player ?
            `${remote.app.getPath('appData')}/Doomtrooper/assets/cardart/bannermen.png` :
            `${remote.app.getPath('appData')}/Doomtrooper/assets/cardart/nephariteWarlord.png`;
        avatar.style.width = 100;
        avatar.onload = () => this.setState({avatar: avatar.src});
```

And then change the first line to:

```js
<div id="avatar" style={{...style.avatar, backgroundImage: `url(${this.state.avatar})`}} />
```
It's all fine, but obviously that feels like quite a hack.

I'm sure this is a great opportunity for me to learn more about string parsing/file names because there has to be a reason one works and one doesn't (since I imagine they're both stored as a String type....) but it feels like it's a bug SOMEWHERE (either here or in React) that would cause said staring parse to fail only on one platform...

Any suggestions as to how I can further test/fix/provide info?

**Comment by framerate** [comment] 2018-04-01 01:37
@ckerr and @sofianguy What can I do to best help you guys help me? This issue is leading to a lot of hacky code on my app and I posted on https://github.com/facebook/react/issues/6575#issuecomment-377735647 to see if it's a react bug and they seem to think it would be back in Electron's camp.

As I said, it's ONLY on Windows, which may hopefully help track it down?

**Comment by sofianguy** [comment] 2019-01-07 22:57
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by framerate** [comment] 2019-01-07 23:07
No prob! It was definitely a bug. We investigated and it had to do with the C++ layer I believe, when it received slashes it perceived as escape characters. 

We moved past it but if we can provide any info to help if you guys investigated don't hesitate to reach out!

**Comment by sofianguy** [comment] 2019-01-25 00:53
@framerate thank you. I'm going to go ahead and close this as we are no longer releasing bug fixes for bugs reported on versions older than 2.0.x. Feel free to reach out if you see this issue again on versions later than 2.0.x

**Comment by framerate** [comment] 2019-01-25 00:55
No problem @sofianguy! I'll keep an eye out!

**Comment by framerate** [comment] 2019-02-19 06:54
@sofianguy this has come back for me, I'm on 4.X now.

```
<div style={{ ...styles.cardRarity, backgroundImage: `url(${global.UI_ASSET_LOCATION}/cards/${faction.replace(/\s+/g, '')}/faction-blok.png)` }} />
```
![image](https://user-images.githubusercontent.com/74291/52995515-c05bcf80-33cf-11e9-9cf5-497638bdae93.png)

^ notice the file URL's are mangled anywhere there is a slash. We investigated and it had to do with when you use a file path in a javascript CSS, it gets passed to the C++ layer and then back to the javascript layer (I believe, I'm repeating another engineer) and when it hits the C++ the slashes become escape characters sowhen javascript gets it back it's mangled.

Would that make it a bug in V8 instead? Or is that something electron handles in the pipeline?

**Comment by Nebukam** [comment] 2019-04-03 17:38
I'm having the same issue on windows, using Electron 4.
A quick way to witness it is to execute the following line in the main process:
`mainWindow.webContents.executeJavaScript('console.log("'+app.getPath("appData")+'")');`

All '\' are treated as escaping characters.

**Comment by electron-triage** [comment] 2020-02-19 22:15
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by framerate** [comment] 2020-02-19 22:22
This is a very frustrating and confusing bug. I hope some day someone can report the right info to get it fixed!

**Comment by electron-triage** [comment] 2020-02-26 20:41
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:41 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/windows, version/1.7.x
