### ISSUE TITLE
Error ->  Uncaught Exception: Error: listen EADDRINUSE 127.0.0.1:8000     at Server.setupListenHandle [as _listen2] (net.js:1330:14)     at listenInCluster (net.js:1378:12)     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1492:7)     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:55:10)

### ISSUE THREAD

**Issue by somkundu1989** [electron/electron#16230] opened 2019-01-02 08:08 UTC
* Output of `node_modules/.bin/electron --version`: v3.0.7
* Operating System (Platform and Version): ubuntu 16.04 LTS

Error: 
Uncaught Exception:
Error: listen EADDRINUSE 127.0.0.1:8000
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1492:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:55:10)

tried to run adonisjs in electron

**Comment by felixrieseberg** [comment] 2019-01-02 14:09
Hey @somkundu1989! By itself, your stack trace looks like you were asking Electron to register a server on your computer (`127.0.0.1`) on a port that was already in use (`8000`). Chances are high that you already had the same app running and somehow blocked this port.

If that's not the case, could you provide reproduction steps?

**Comment by sofianguy** [comment] 2019-01-15 20:48
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-01-15 20:48 UTC
Labels: blocked/need-info
