### ISSUE TITLE
Different undo behaviour when using accelerate key between Windows and Mac.

### ISSUE THREAD

**Issue by jwu** [electron/electron#7040] opened 2016-08-31 02:07 UTC
* Electron version: All
* Operating system: Windows vs Mac

When I define a custom undo behaviour I found it become different between Windows and Mac devices.

This is what I did:

```javascript
// the main menu I overwrite:
let menuTemplate = [
  // Edit
  {
    label: 'Edit',
    submenu: [
      {
        label: 'Undo',
        accelerator: 'CmdOrCtrl+Z',
        click () {
          console.log('Undo');
        }
      },

      {
        label: 'Redo',
        accelerator: 'Shift+CmdOrCtrl+Z',
        click () {
          console.log('Redo');
        }
      },
    ]
  }
];
```

As you can see, I overwrite the Undo behaviour and use the same shortcuts from the Browser. When I press `ctrl/cmd+z` on Mac, things goes fine, the menu click go first and take over it. But in Windows, it seems like the original `webContents.undo()` will be executed first, if the undo stack have states (which means you should typing some letters on a `<input>` first).

This makes me have no chance to overwrite the undo for Windows platform. Is this expect in Windows? If we can not change the menu behaviour, is there a way to disable/stop `webContents.undo` when pressing `ctrl+z` so that the Main Menu can receive it?

**Comment by jwu** [comment] 2016-08-31 03:00
To make things clearly, I add this test repo: https://github.com/jwu/electron-custom-undo

You can try it and see the difference between Mac and Windows machine.

**Comment by zeke** [comment] 2016-08-31 20:03
Related: https://github.com/electron/electron/issues/3682

**Comment by zcbenz** [comment] 2016-09-02 05:13
Yeah this is a duplicate of #3682, this should be not expected in Electron but that's how Chromium handles undo events on Windows/Linux. It works as expected on Mac because Chromium uses the system events chain for handling undo events.

Sp I'm closing this since it is a behavior of Chromium that we are unable to change.

**Closed by zcbenz** 2016-09-02 05:13 UTC
