### ISSUE TITLE
Setting the size of window to screen size breaks skipTaskbar

### ISSUE THREAD

**Issue by codehz** [electron/electron#5181] opened 2016-04-16 01:53 UTC
- Electron version: 0.37.6
- Operating system: Windows 10 1511 64-bit

```
win = new BrowserWindow({
        width: screenSize.width,
        height: screenSize.height,
        enableLargerThanScreen: true,
        show: false,
        transparent: true,
        frame: false,
        resizable: false,
        skipTaskbar: true, // will be deactivated after win.setSize
    });
//...some code...
win.show();
win.setSize(screenSize.width, screenSize.height);
win.setSkipTaskbar(true); // If I dont add this line, the skipping taskbar effect will be deactivated
```

`win.setBounds` will also break this effect;

**Comment by zcbenz** [comment] 2016-04-18 05:28
I'm unable to reproduce this, can you provide a minimal app that reproduces this? The problem is probably in other parts of your code.

**Comment by codehz** [comment] 2016-04-21 03:22
@zcbenz 
I forgot a key point(this bug only occur when setSize(screenSize.width, screenSize.height) and source size are (screenSize.width, screenSize.height))
In the previous example code, BrowserWindow's initial width and height are (800,600),but in my code,they are (screenSize.width, screenSize.height) and it not working corrently(only display at clientarea of desktop),so I add `win.setSize(screenSize.width, screenSize.height);`,and the bug appear.
(The following is a minimum app that reproduces this bug)
```
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;
let mainWindow = null;
app.on('window-all-closed', function() {
    app.quit();
});

app.on('ready', function() {
    let screenSize = electron.screen.getPrimaryDisplay().size;
    mainWindow = new BrowserWindow({
        width: screenSize.width,
        height: screenSize.height,
        enableLargerThanScreen: true,
        show: false,
        transparent: true,
        frame: false,
        resizable: false,
        skipTaskbar: true
    });
    mainWindow.loadURL('http://github.com');
    mainWindow.setSkipTaskbar(true);
    mainWindow.setSize(screenSize.width, screenSize.height);
    mainWindow.show();
});
```
Q:Why you dont use full-screen window directly? A: Full-screen window couldn't be transparent ...

**Comment by adammeyer** [comment] 2016-07-26 01:26
+1

This keeps the window in taskbar:
```javascript
let window = new BrowserWindow({
      height: externalDisplay.size.height,
      width: externalDisplay.size.width,
      frame: false,
      skipTaskbar: true
    });
```

This does not:
```javascript
let window = new BrowserWindow({
      height: externalDisplay.size.height - 1,
      width: externalDisplay.size.width,
      frame: false,
      skipTaskbar: true
    });
```

Windows 10, Electron 1.2.8

**Comment by kevinsawicki** [comment] 2016-08-08 20:35
@adammeyer @codehz are you able to still reproduce this on 1.3.2?

I tried with those same `BrowserWindow` options on Windows 10 but was unable to reproduce.

<img width="1280" alt="screen shot 2016-08-08 at 1 34 44 pm" src="https://cloud.githubusercontent.com/assets/671378/17495186/e9d24f7e-5d6c-11e6-9822-57404cf86747.png">

**Comment by zcbenz** [comment] 2017-06-12 07:27
I'm closing since the problem seems to be gone.

**Closed by zcbenz** 2017-06-12 07:27 UTC
Labels: fixme/bug, more-information-needed, platform/windows
