### ISSUE TITLE
Production build: unusable binary dependencies (Unexpected end of JSON input)

### ISSUE THREAD

**Issue by lmancel** [electron/electron#26079] opened 2020-10-21 15:03 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Node Version:**
  v12.16.1
* **Electron Version:**
  v11.0.0-beta.13
* **Electron-builder Version:**
  v22.9.1
* **Operating System:**
  macOS 10.15.2
* **Last Known Working Electron version:**
  v10.1.4

Hello,

I am not sure this is the right place to post this or if I should create this on electron-builder, but considering the behavior changed between version 10.x and 11 of electron it might be relevant. Please tell me if I should open it elsewhere instead. We are having an issue when building our application with version 11-beta using electron-builder. We rely on static binaries to be included in our build (ffmpeg, to name it), but when starting the built app we get a JS error saying the package.json file for this module is invalid (Unexpected end of JSON input).

### Expected Behavior
The production application should run similarly to the dev

### Actual Behavior
Production build crashes on start

When looking at the content of the generated .app the (unpacked) app.asar has properly included the dependencies, and the package.json is valid.

### To Reproduce
The project runs fine on dev, it's the finalized built version that has an issue. I created a repo with the base project, as well as uploaded the built version in the 1.0.0 release of this repo.

```sh
$ git clone https://github.com/lmancel/electron-tests.git
$ yarn install
$ yarn build
```
Built binary:
https://github.com/lmancel/electron-tests/releases/download/1.0.0/electron-test-1.0.0-mac.zip

### Screenshots
![Screenshot 2020-10-21 at 16 41 49](https://user-images.githubusercontent.com/5877409/96736606-0e06b780-13bd-11eb-8a0a-e430d0a38fd3.png)

![Screenshot 2020-10-21 at 16 50 46](https://user-images.githubusercontent.com/5877409/96737270-c59bc980-13bd-11eb-9e32-94b413942660.png)

**Comment by ckerr** [comment] 2020-10-21 20:12
Hey @lmancel, thanks for reaching out -- and extra thanks for the good description of the issue you're seeing!

I agree that it's not clear from the error message whether this is coming from Electron or Builder or one of their dependencies, but I _think_ that Builder is going to be the first place to look for this and would suggest reporting it at https://github.com/electron-userland/electron-forge/issues . As such, I'm going to close this issue in the Electron tracker. If this turns out to be in error, it can be reopened and we can go from there.

I hope this helps! Good luck!

**Closed by ckerr** 2020-10-21 20:12 UTC

**Comment by vladimiry** [comment] 2020-11-02 15:08
This is a duplicate of #25438 which was closed as unresolved. The most recent v11-beta release is still affected (beta 18).
