### ISSUE TITLE
Only first page prints under Electron 3 using webContents.print()

### ISSUE THREAD

**Issue by maplemike** [electron/electron#14260] opened 2018-08-22 13:50 UTC
* Electron Version: 3.0.0-beta.6
* Operating System (Platform and Version): Mac OS 10.13.6
* Last known working Electron version: 2.0.7

**Expected Behavior**

If content spans multiple pages, all pages should print.

**Actual behavior**

Only content on the first page is being printed

**To Reproduce**

https://github.com/enstrategic/printing-example

```sh
$ git clone https://github.com/enstrategic/printing-example
$ yarn
$ yarn run start
```
Click on the print button

**Screenshots**

Electron 3 example:

![image](https://user-images.githubusercontent.com/6138011/44467294-c0754100-a5df-11e8-945e-f8ce2a5063ef.png)

Electron 2 output:

![image](https://user-images.githubusercontent.com/6138011/44467391-029e8280-a5e0-11e8-92fd-9dacc900322b.png)

**Additional Information**

**Comment by mviktora** [comment] 2018-10-12 15:40
Hello,

Our customers ran into this issue as well after we updated our app to Electron 3.0.x. Any news about a fix?

Thanks.

**Comment by jrobeson** [comment] 2018-10-12 21:28
same as https://github.com/electron/electron/issues/15036, but #15036 has other details.

**Comment by ivandroid** [comment] 2018-10-24 23:50
Experiencing the same issue and getting upset customers. Please help!

**Comment by ivandroid** [comment] 2018-10-26 16:20
Will there be a fix soon?

**Comment by brenca** [comment] 2018-10-26 16:55
After the next 3.0.x release, can you please test if this is still happening for you? #15402 most likely fixed this.

**Comment by ivandroid** [comment] 2018-10-29 10:56
Eagerly waiting for the next update...

**Comment by ckerr** [comment] 2018-10-31 23:49
Marking as `blocked/need-info` for issue bookkeeping pending the next `3.0.x` release, which will be out shortly

**Comment by ivandroid** [comment] 2018-11-01 09:36
The bug is still present in 3.0.7.

**Comment by jiri-nohavec** [comment] 2018-11-02 14:08
Hello, the issue is still present in Electron 3.0.7 on macOS. (Windows are fine.)

**Comment by mviktora** [comment] 2018-11-03 20:43
Any chance of doing a quick 3.0.8. release focused just on just this one issue? It seems like a lot of people would appreciate it.

**Comment by deepak1556** [comment] 2018-11-06 02:19
@ivandroid once https://github.com/electron/electron/pull/15143 is merged it will need to be backported to 3.x branches for fixing this issue. Please follow that PR for updates, thanks!

**Comment by ivandroid** [comment] 2018-11-06 02:20
Thank you! This bug is crucial for my application. Eagerly waiting for a fix...

**Comment by ivandroid** [comment] 2018-11-07 20:33
Any chance to resolve this issue within the next 3 days? The bug is still present both in 3.0.7 and 3.0.8 releases. I lose customers. Please help.

**Comment by BinaryMuse** [comment] 2018-11-07 21:50
Hey there @ivandroid! I understand that bugs in general are frustrating, and that this bug in particular is very important to you, but we can't promise any specific date and time for a fix (for any issue, not just this one). That said, we will do what we can to get it fixed as soon as we can. In the meantime, please kindly hold off on additional comments mentioning that it's still broken or asking for a timeframe; dealing with such comments only serves to take away time that we could instead be spending on fixing this (and other) issues. Thanks for your understanding.

**Comment by popod** [comment] 2018-11-14 11:14
Is this fixed with electron v3.0.9 as display in the[ project 3.0.x](https://github.com/orgs/electron/projects/14#column-3795669) ? Because this still don't works in my application and I see nothing about that in the v3.0.9 changelogs ?

Thanks !

**Comment by ivandroid** [comment] 2018-11-14 11:18
The issue seems to be fixed, but it has to be backborted to 3.0.x, which hasn't been done yet.

**Comment by popod** [comment] 2018-11-19 23:20
Hi @MarshallOfSound ! Please, can you reopen this issue ? because it is not resolved in electron 3.x.x and depending of the application, this should be a major issue..

And could you read my previous comment please ? I think that this issus has been moved into the 3.0.9 column in the project by error, because this version does not remove it !

Where could we follow the backport of this issue in the 3-x-x branche ?

Thanks in advance :)

**Comment by ivandroid** [comment] 2018-11-20 14:24
This issue seems to be forgotten. Nobody cares about it. This is sad.

**Comment by deepak1556** [comment] 2018-11-20 14:41
Reopening to track backporting the fix to 3.x

**Comment by popod** [comment] 2018-11-20 14:49
Thank you for reopening. As said before (but not reported on the tags of this issue), printing works fine on Windows. The problem appears only with macOS, not on Windows.. Hope this helps.

**Comment by MathieuMonney** [comment] 2018-12-01 12:05
Encountering the same issue on OSX. @deepak1556 do you  have any update on the backport, or an idea when this will be fixed in 3.x? Thanks!

**Comment by ivandroid** [comment] 2018-12-01 18:20
It seems that nobody cares about this issue. I asked the same question a month ago but the issue is still present.

**Comment by adammeyer** [comment] 2018-12-20 16:22
I find this thread of some concern.  Electron 3 is considered to be the "stable" release and when something as basic as printing is reported not to be working, four months go by without any fix.  Are most production projects still using Electron 2?  I don't mean this as a complaint, I'm seriously looking for a way to evaluate when a build is actually stable enough to be used in production. Thank you.

**Comment by deepak1556** [comment] 2018-12-20 19:15
@adammeyer the issue was originally fixed in https://github.com/electron/electron/pull/15023 and https://github.com/electron/electron/pull/15143 which were landed in master and later backported to 4.x release line https://github.com/electron/electron/pull/15976 which is soon to become stable, considering the volume of change that would question the stability of 3.x and technical challenges with backporting to 3.x stable release line, it has not been considered yet. Is there something thats blocking your app from upgrading to 4.x ?

**Comment by ivandroid** [comment] 2018-12-20 20:40
@deepak1556 a migration from 3.x to 4.x would be very work-intensive and could produce a lot of new issues and bugs. I think, many of other devs would agree with me. Hence, I would also appreciate backporting the changes to 3.x.

**Comment by bjbk** [comment] 2018-12-25 13:57
Forgive me if I have not updated Electron correctly, however, I cloned the above sample then updated Electron to 4.0.0 and now the print function appears to do nothing at all.

With 3.x.x at least the print dialog displays, however, now with 4.0.0 there is no print dialog or indication of an error.

macOS 10.14.3 Beta (18D32a) ⇐ could be part of the problem

```
  "devDependencies": {
    "electron": "4.0.0"
  }

```

**Comment by yapwr** [comment] 2018-12-25 15:11
@bjbk Happened to me as well for Electron 4.0.0. Nothing shown on `webContents.print()`. But surprisingly `window.print()` works.

**Comment by bjbk** [comment] 2018-12-25 15:50
@yapwr How did you get `window.print()` to work?  In the main process or renderer?

**Comment by Jacobkg** [comment] 2019-03-28 18:04
I wanted to add a +1 for backporting this fix to 3.x if possible

**Comment by shekar1212** [comment] 2019-07-23 06:52
is this issue working in 5.x ?

**Comment by codebytere** [comment] 2020-01-24 21:30
Closing as this has been fixed in v7, but is it not possible to backport owing to chromium architecture changes.

**Closed by codebytere** 2020-01-24 21:30 UTC
Labels: 3-0-x, 4-2-x, bug/regression :leftwards_arrow_with_hook:, component/printing, platform/all, status/confirmed
