### ISSUE TITLE
child_process.spawn is considerably slower in Electron 12+ 

### ISSUE THREAD

**Issue by ion-dev** [electron/electron#32480] opened 2022-01-14 17:00 UTC
We've discovered an issue with macOS (Big Sur) and Electron 12 and above (Node 14 and above), where spawning a child_process takes considerably longer than Electron 11 and lower (Node 12 and lower).

Here's an example app with instructions to demonstrate the problem: 
https://github.com/dev-manager-uk/spawn-delay

After running the app initially, you'll notice the spawn function takes ~10ms.

After upgrading Electron to 12 or higher, you'll notice the spawn function takes ~500ms!

What's changed to cause this and can anything be done about it?

Thanks!

-- UPDATE --

macOS (Big Sur) - Bug exists
macOS (Mojave) - unable to replicate this bug
Windows 10 - unable to replicate this bug

**Comment by RaisinTen** [comment] 2022-01-15 14:30
Related - https://github.com/electron/electron/issues/26143?

**Comment by nornagon** [comment] 2022-01-19 01:09
#26143 is about a problem with macOS >= Big Sur, but the symptom you're describing makes it seem like it's an issue with a particular Electron version. Would be great if you could take a look at #26143 and let me know if your symptoms match those described!

**Comment by ion-dev** [comment] 2022-01-19 09:46
@RaisinTen @nornagon 
 I've now tested on Windows 10 and macOS running Mojave and cannot replicate! 

The delay only occurs on macOS running Big Sur, and only when Electron 12 or greater. Electron 11 and lower are fine!

**Comment by RaisinTen** [comment] 2022-01-19 15:16
In that case, should we close this issue in favour of https://github.com/electron/electron/issues/26143 as this is a duplicate of that?

**Comment by ion-dev** [comment] 2022-01-19 15:28
> In that case, should we close this issue in favour of #26143 as this is a duplicate of that?

Perhaps, although I'm seeing normal behaviour using Electron 11 on Big Sur. For me the problem arises after updating to 12+.

**Closed** 2022-02-14 19:46 UTC

**Comment by dreamthen** [comment] 2022-03-28 18:34
I also encountered this problem, after version 12 using the node main process fork the child process is about 800ms slower.

**Comment by dreamthen** [comment] 2022-03-28 19:06
The result of running the same code on version 11 and version 12+ is that version 12+ is 800 ms slower.

**Comment by RaisinTen** [comment] 2022-03-29 04:23
@dreamthen the libuv patch that fixes the perf regression has been merged and backported to v15, v16, v17 and v18; see https://github.com/electron/electron/pull/33337, so this shouldn't be an issue anymore if you are on supported versions.

**Comment by dreamthen** [comment] 2022-03-29 15:03
well done~it works.
