### ISSUE TITLE
[Bug]: Printing blank pages

### ISSUE THREAD

**Issue by saifudheen9745** [electron/electron#43235] opened 2024-08-07 06:42 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.3.1

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 10 Pro 22H2

### What arch are you using?

x64

### Expected Behavior

After invoking the print method, I expect it to print the bill without any further interactions.

### Actual Behavior

Printing blank pages.

### Additional Information

I have an Angular application with requirement to print a bill without displaying any previews or dialogues.
eg: If I click on the "Print Bill" button it needs to create a new order and print the bill (Thermal printer or any printer) without any additional dialogues.

![method](https://github.com/user-attachments/assets/881488d5-8f4d-4ca3-a7ca-c6751b7560d9)

This is a method in my angular service file. Here I receive a blob {type: application/pdf} as response from backend (Python) and I need to print this pdf.

I am using electron to bypass the dialogue boxed and previews.

The "printPdf" method in the electron service accepts the object url, the method invokes a 'print-pdf' channel.

![preload](https://github.com/user-attachments/assets/5464f920-f0d1-4636-9f23-30c960293c13)

I also created a handler for the 'print-pdf' where I created a new window and load the pdf into the window for printing.

![false](https://github.com/user-attachments/assets/83d2acb2-5568-4f32-9132-764b14a1fb8a)

As you can see I am loading the data into the window before invoking the print function. But the print method is getting executed before completing the preview.

![print befoer preview](https://github.com/user-attachments/assets/aa9f7e70-07a3-4d59-aea1-712b9cba0142)

After clicking the print I am getting blank page from printer, Event if I go with 'Microsoft Print to PDF' option it is creating a blank pdf.

But If I were to cancel the print dialogue box It is rendering the complete preview

![pdf preview](https://github.com/user-attachments/assets/f567d39b-bec7-4d7e-bff6-b5acf986542d)

If I click on the print icon and try to print , then it works. But the problem happens when I try to invoke the print method automatically after loading the data to the window.

**Comment by saifudheen9745** [comment] 2024-08-07 11:27
https://gist.github.com/ca5433408f5feef7c1e62ec891e77c8e

**Comment by codebytere** [comment] 2024-08-07 13:51
Duplicate of https://github.com/electron/electron/issues/30947

**Closed by codebytere** 2024-08-07 13:51 UTC
Labels: platform/windows, bug :beetle:, 31-x-y

**Comment by lanrenbulan** [comment] 2024-11-12 07:18
@saifudheen9745 Excuse me, have you solved this problem
