### ISSUE TITLE
DevTools HAR File Downloads are Always 0KB

### ISSUE THREAD

**Issue by KiranNiranjan** [electron/electron#44441] opened 2024-10-29 08:24 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

Sequoia 15.0.1

### What arch are you using?

x64

### Last Known Working Electron version

32.0.0

### Expected Behavior

The downloaded HAR file should contain valid data.

### Actual Behavior

Downloaded HAR files are Always 0KB

**Comment by codebytere** [comment] 2024-10-29 15:53
Duplicate of https://github.com/electron/electron/issues/44316

**Closed by codebytere** 2024-10-29 15:53 UTC
Labels: platform/macOS, bug :beetle:, 33-x-y
