### ISSUE TITLE
[Bug]: Electron crashes when navigating to custom file protocol

### ISSUE THREAD

**Issue by t57ser** [electron/electron#29542] opened 2021-06-04 09:43 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.0

### What operating system are you using?

Windows

### Operating System Version

19042.985

### What arch are you using?

x64

### Expected Behavior

test.html should get loaded

### Actual Behavior

electron crashes.

### Testcase Gist URL

https://gist.github.com/t57ser/591ace911d2274f5500a702d178d7b96

### Additional Information

After example.com gets loaded, open the devtools and type
location = "test://"

**Comment by t57ser** [comment] 2021-06-04 14:09
works when adding:
```
electron.protocol.registerSchemesAsPrivileged([
	{
		scheme: "test",
		privileges: {
			bypassCSP: true,
			secure: true,
			standard: true,
			supportFetchAPI: true,
			corsEnabled: true,
			allowServiceWorkers: true,
		},
	},
]);
```

**Comment by VerteDinde** [comment] 2021-06-04 20:49
Closing this as a duplicate of #28407, but I’ll test this repro against that fix as well. Thanks for reporting! 🙇‍♀️

**Closed by VerteDinde** 2021-06-04 20:49 UTC
Labels: bug :beetle:
