### ISSUE TITLE
desktopCapturer.getSources returns empty thumbnails

### ISSUE THREAD

**Issue by ErikSom** [electron/electron#24412] opened 2020-07-03 14:40 UTC
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  v9.0.0
* **Operating System:**
  * macOS 10.15.3

### Expected Behavior
I expect to receive thumbnails when calling the getSources

### Actual Behavior
The getSources retrieves no thumbnails, all the thumbnails are empty objects

### Screenshots
https://share.getcloudapp.com/E0uzX5yg

### Additional Information
Not sure if relevant, but I'm using the following webPreferences:
`    
webPreferences: {
      preload: path.join(__dirname, '/src/app/preload.js'),
      nodeIntegration: false,
      contextIsolation: true,
      enableRemoteModule: false,
}
`

**Comment by Khivar** [comment] 2020-11-08 10:23
Did you ever find a way to make it work ? I use the same webPreferences object and have the same bug on Linux. I tried electron v8, v9 and v10 and they all return empty thumbnail objects.

**Comment by ErikSom** [comment] 2020-11-08 18:16
Nope unfortunately not...

**Comment by pratik14** [comment] 2021-03-11 18:52
I was facing with same issue, empty thumbnail and apiIcon. It worked with IPC



```
ipcMain.handle(channels.GET_DESKTOP_SOURCES, async () => {
  const sources = await electron.desktopCapturer.getSources({
    thumbnailSize: {
      height: 90,
      width: 150,
    },
    fetchWindowIcons: true,
    types: ["window", "screen"],
  });

  return sources.map((source) => {
    return {
      id: source.id,
      name: source.name,
      appIconDataURI: source.appIcon?.toDataURL() || null,
      thumbnailDataURI: source.thumbnail?.toDataURL() || null,
    };
  });
});

```

**Comment by nornagon** [comment] 2021-03-11 19:13
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by pratik14** [comment] 2021-03-12 13:07
@nornagon Created gist using electron-fiddle to reproduce error: 
https://gist.github.com/pratik14/8feab378a48715b13524a4139e0d3c0a.


Response of `desktopCapturer.getSources ` has screen info but appIcon and thumbnail are missing
```

        window.api.desktopCapturer.getSources({
          thumbnailSize: {
            height: 90,
            width: 150,
          },
          fetchWindowIcons: true,
          types: ["window", "screen"],
        }).then((resp) => {
          console.log(response)
          //In response appIcon and thumbnail are empty
        })
```

**Comment by jho293** [comment] 2021-03-12 14:03
Bantu aku dengan $1 aku dalam kesusahan uang

Kalau berkenan transfer via rekening mandiri

No. 152-00-1748706-3

Terima kasih orang baik



JhoynSannMalakian

Pada tanggal Jum, 12 Mar 2021 21.08, Pratik Shah ***@***.***>
menulis:

**Comment by nornagon** [comment] 2021-03-15 18:59
@pratik14 i think that's a result of the use of `contextBridge`. `contextBridge` does not support transferring NativeImage objects, see: https://www.electronjs.org/docs/api/context-bridge#parameter--error--return-type-support

**Closed by nornagon** 2021-03-15 18:59 UTC
Labels: 9-x-y, blocked/need-repro, bug :beetle:, platform/macOS

**Comment by yetyman** [comment] 2021-05-06 19:48
hi @nornagon I am getting the same error inside of main.js, so no context bridge should be involved. Any suggestions?
```
ipcMain.on('screenshot', (event, args) => {
    const thumbSize = determineScreenShotSize();
    let options = { types: ['screen'], thumbnailSize: thumbSize }
    desktopCapturer.getSources(options).then(function (sources) {
        sources.forEach(function (source) {
            if (source.name === 'Entire screen' || source.name === 'Screen 1') {
                let date = new Date();
                try {
                    const screenshotPath = path.join(args.screenshotDirectory, `screenshot_${fileSafeDateTime(date)}.png`)
                    fs.promises.writeFile(screenshotPath, source.thumbnail.toPng())
                        .then(() => {
                            if (args.showScreenshot)
                                win.webContents.send("screenshot-path", screenshotPath);
                        },
                        (e) => win.webContents.send("log", JSON.stringify(e))
                    );
                } catch (ex) {
                    win.webContents.send("log", JSON.stringify(ex, replaceErrors));
                }

            }
        })
    }, (e) => win.webContents.send("log", JSON.stringify(e)));
});
```

**Comment by yetyman** [comment] 2021-05-06 19:49
if you would like to reproduce this, here are the functions i'm using inside
```

function formatDate(date, format) {
    const map = {
        mm: date.getMonth() + 1,
        dd: date.getDate(),
        yy: date.getFullYear().toString().slice(-2),
        yyyy: date.getFullYear()
    }

    return format.replace(/mm|dd|yy|yyy/gi, matched => map[matched])
}
function fileSafeDateTime(date) {
    return `${formatDate(date, 'yyyy-mm-dd')}_${pad0(date.getHours() + "", 2)}-${pad0(date.getMinutes() + "", 2)}-${pad0(date.getSeconds() + "", 2)}-${pad0(date.getMilliseconds() + "", 3)}`;
}
function determineScreenShotSize() {
    const screenSize = screen.getPrimaryDisplay().workAreaSize;
    const maxDimension = Math.max(screenSize.width, screenSize.height)
    return {
        width: maxDimension,
        height: maxDimension
    }
}
function replaceErrors(key, value) {
    if (value instanceof Error) {
        var error = {};

        Object.getOwnPropertyNames(value).forEach(function (propName) {
            error[propName] = value[propName];
        });

        return error;
    }

    return value;
}

function pad0(value, count) {
    var result = value.toString();
    while (result.length < count)
        result = '0' + result;
    return result;
}
```

**Comment by manhtai** [comment] 2022-03-24 08:35
I got empty thumbnails when using `clipboard.getImage()` too. The function is called from main process so I assume no contextBridge is relevant. No idea how to resolve it so far.

**Comment by nornagon** [comment] 2022-03-29 19:07
@yetyman please open a new issue with a complete repro, preferably using [Electron Fiddle](/electron/fiddle).

**Comment by prattcmp** [comment] 2022-06-21 03:05
> @yetyman please open a new issue with a complete repro, preferably using [Electron Fiddle](/electron/fiddle).

Why do you need this? It seems like you know what the issue is.
