### ISSUE TITLE
How to change desktop icon

### ISSUE THREAD

**Issue by Suryadevelops** [electron/electron#27099] opened 2020-12-21 16:28 UTC
Hi I'm new to this framework and i'm making a desktop app i don't want this to be too long i have only one questin how can i change the desktop icon i can't find it in docs

**Comment by Kilian** [comment] 2020-12-21 16:53
Closing this because it is not a bug and does not follow our issue template. You can ask for help on our [discord server](https://www.electronjs.org/blog/discord-hacktoberfest-2020#electron-community-discord-launch).

**Closed by Kilian** 2020-12-21 16:53 UTC
