### ISSUE TITLE
SIGSEGV crash: electron::api::WebRequest::

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#27616] opened 2021-02-03 22:57 UTC
* **Electron Version:** 12.0.0-beta.21
* **Operating System:** Linux
* **Last Known Working Electron version:** 11.x works well on the same project/code-base and dataset

### Expected Behavior
No crash.

### Actual Behavior
See attached [dump.txt](https://github.com/electron/electron/files/5922021/dump.txt) file.

### To Reproduce
There is no simple way to provide minimal repro project but there are `session.webRequest.{onBeforeRequest,onBeforeSendHeaders,onHeadersReceived,onErrorOccurred,onCompleted}`-like handlers setup in this way: https://github.com/vladimiry/ElectronMail/blob/48ac271b441a7860bad41c31707316fb9447db36/src/electron-main/web-request/index.ts.

### Additional Information
 The #27603 is a possibly related issue.

**Comment by ckerr** [comment] 2021-02-04 15:56
Agreed, this is a duplicate of #27603. Both are crashes in v8 internal code after being called from `ToDictionary(gin::Dictionary* details, extensions::WebRequestInfo* info)` so I'm closing this as a duplicate.

Thank  you for reporting it though! This dump.txt has a slightly different crash than the trace in #27603 and that may be useful in tracking down the source of the problem!

**Closed by ckerr** 2021-02-04 15:56 UTC
Labels: 12-x-y, bug/crash :boom:, bug/regression :leftwards_arrow_with_hook:, platform/linux
