### ISSUE TITLE
No linux packages for 1.7.8

### ISSUE THREAD

**Issue by johnf** [electron/electron#10595] opened 2017-09-24 04:27 UTC
* Electron version: 1.7.8
* Operating system: Linux

### Expected behavior

Latest electron should install on linux

### Actual behavior
Error: Failed to find Electron v1.7.8 for linux-x64 at https://github.com/electron/electron/releases/download/v1.7.8/electron-v1.7.8-linux-x64.zip

### How to reproduce

yarn add electron@1.7.8

Version 1.7.8 has hit npm but it doesn't look like linux packages are ready yet. They are missing from github releases page.

**Comment by monoxane** [comment] 2017-09-24 06:43
Can confirm, I am currently installing with `npm install electron@1.6.13` because of this.

**Comment by brenca** [comment] 2017-09-24 06:44
Dupe of #10594 ?

**Comment by monoxane** [comment] 2017-09-24 06:46
@brenca Yup, npm needs to be reverted to 1.6.13 until 1.7.8 is ready for release.

**Comment by MarshallOfSound** [comment] 2017-09-24 07:13
Hm, not sure what happened here, looking into it

**Comment by Stanzilla** [comment] 2017-09-24 15:59
@MarshallOfSound any news?

**Comment by sean-hill** [comment] 2017-09-24 20:03
I'm facing this same issue while using Nightmare.js. Our current build is failing because of it, with no package changes on our end.

**Comment by englishextra** [comment] 2017-09-24 20:29
[Error: Failed to find Electron v1.7.8 for linux-x64 at https://github.com/electron/electron/releases/download/v1.7.8/electron-v1.7.8-linux-x64.zip](https://travis-ci.org/englishextra/englishextra.github.io/builds/279279224)

While in ```package.json```

```
 "dependencies": {
    "autoprefixer": "^7.1.1",
    "babel-cli": "^6.24.1",
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-plugin-transform-es2015-arrow-functions": "^6.22.0",
    "beautify-css": "^1.0.0",
    "bower": "^1.8.0",
    "browserify": "^14.4.0",
    "clean-css-cli": "^4.1.5",
    "electron": "^1.6.11",
    "electron-debug": "^1.1.0",
    "electron-packager": "^8.7.1",
    "grunt-cli": "^1.2.0",
    "gulp-cli": "^1.3.0",
    "http-server": "^0.10.0",
    "node-sass": "^4.5.3",
    "npm": "^4.0.5",
    "nw": "^0.23.4-sdk",
    "postcss-cli": "^4.1.0",
    "surge": "^0.19.0",
    "sw-precache": "^5.2.0",
    "uglify-js": "^3.0.18",
    "webpack": "^3.0.0",
    "xo": "^0.18.2"
  },
```

**Comment by maks** [comment] 2017-09-25 00:16
This is also breaking `npm install -g react-devtools`

**Comment by gucong3000** [comment] 2017-09-25 01:40
+1

**Comment by wnereiz** [comment] 2017-09-25 03:00
Just found the same problem for "npm install electron"

**Comment by ivenspontes** [comment] 2017-09-25 03:49
i'm tryng: ``` npm install -g electron ```
but same problem.

**Comment by KozaKrisz** [comment] 2017-09-25 05:44
Same issue here, unfortunately. +1 :-(

**Comment by zcbenz** [comment] 2017-09-25 06:04
We have some issues with CI servers, I'm now manually building and uploading the binaries.

**Comment by zcbenz** [comment] 2017-09-25 08:27
Should be working now.

**Closed by zcbenz** 2017-09-25 08:27 UTC
Labels: component/build, fixme/bug, platform/linux, version/1.7.x

**Comment by zeke** [comment] 2017-09-25 16:08
> This is also breaking npm install -g react-devtools

@maks I'm able to install react-devtools without issue. Are you still having this problem?

**Comment by englishextra** [comment] 2017-09-25 16:20
@zcbenz [Build](https://github.com/electron/electron/issues/10595#issuecomment-331738077) works now with [travis-ci](https://travis-ci.org/englishextra/englishextra.github.io/builds/279584025) Thanks

**Comment by maks** [comment] 2017-09-25 21:47
@zeke it works fine now that @zcbenz fixed it, thanks!

**Comment by evertonfraga** [comment] 2017-09-26 14:48
Whoever had problems with the Linux file checksum, just delete the cached file and try again. `~/.electron/SHASUMS256.txt-1.7.8` 

👍
