### ISSUE TITLE
[Bug]: Electron app freezes/crashes after printing or saving a pdf

### ISSUE THREAD

**Issue by TC-kHa** [electron/electron#32764] opened 2022-02-07 01:06 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey Version 12.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Electron freezes/crashes after the user either save or print a page with a pdf.

### Actual Behavior

Electron application freezes/crashes. 

Theres no workaround except closing and reopening application

### Additional Information

Electron app freezes/crashes when a user tries to save or print a page that has pdf display.

The pdf is render inside a ```iframe```.

There's no error logs that displays inside console or terminal.

The issue is happening on mac and window.

I was able to reproduce the issue with a simple electron app. Please look at the code example below for details.

Steps to reproduce:
Requirements: Need 2 pdfs display inside 2 different pages
1) Open up home page with a pdf that is display
2) Navigate to a second page with a pdf
3) Open up the print dialog
4) Either save or print pdf

```index.html```
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <!-- https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP -->
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'">
    <link href="./styles.css" rel="stylesheet">
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using Node.js <span id="node-version"></span>,
    Chromium <span id="chrome-version"></span>,
    and Electron <span id="electron-version"></span>.

    <!-- You can also require other files to run in this process -->
    <script src="./renderer.js"></script>
    <iframe src="http://www.africau.edu/images/default/sample.pdf"></iframe>
    <a href='secondpage.html'>Click this button</a>
  </body>
</html>
```

```secondpage.html```
```
<html />
    <iframe src="http://www.africau.edu/images/default/sample.pdf"></iframe>
    <a href='index.html'>Click this button</a>
    <button onclick="window.print()">Click print button</button>
</html>
```

**Comment by codebytere** [comment] 2022-02-07 09:53
Crash fixed in https://github.com/electron/electron/pull/32632, and other issue is duplicate of https://github.com/electron/electron/issues/27605

**Closed by codebytere** 2022-02-07 09:53 UTC
Labels: bug :beetle:

**Comment by TC-kHa** [comment] 2022-08-15 20:54
@codebytere I updated the application to latest Electron version `20.0.2` and the issue is still reproducible

**Comment by rdking** [comment] 2024-07-12 02:34
v31.1.0 and this bug still exists.
