### ISSUE TITLE
Moving mouse increases CPU on renderer process to 7-10%

### ISSUE THREAD

**Issue by bpasero** [electron/electron#22459] opened 2020-03-01 08:18 UTC
* **Electron Version:**
  * `7.1.8`
* **Operating System:**
  * macOS 10.15.3

### Expected Behavior
Moving mouse should have a minimal impact on CPU.

### Actual Behavior
Moving mouse increases CPU usage of renderer to 7-10%.

### To Reproduce
* install Electron Fiddle
* run htop and monitor CPU usage of Fiddle
* move the mouse

![Kapture 2020-03-01 at 9 17 29](https://user-images.githubusercontent.com/900690/75622140-8d7d1780-5b9d-11ea-8e24-3ee95a7b2feb.gif)

Reported from https://github.com/microsoft/vscode/issues/89666

**Comment by aleksey-hoffman** [comment] 2020-03-03 22:58
This is expected. It's caused by execution of CSS and event listeners. It's not Electron specific, it comes from Chromium.

I see similar results in a completely different Electron app as well as on any other website in Chrome 80. On a 4-cores i7 CPU usage increases to 3-10% when I'm quickly moving the cursor over simple static elements like text, and it increases to 20% for more dynamic elements (with more complex CSS, e.g. `:hover` rules).

In Chrome 80, CPU usage is similar, it increases to 3-10% for simple static elements and up to 20% for more complex elements.

**Comment by electron-triage** [comment] 2021-03-09 03:50
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by bpasero** [comment] 2021-03-12 15:55
This reproduces with latest Fiddle app on my macOS ARM machine still when moving the mouse.

**Comment by deepak1556** [comment] 2021-03-13 04:43
Issue is seen in latest chromium, should report in upstream as next step.

**Comment by nornagon** [comment] 2021-03-15 20:39
@bpasero would you be able to report this upstream and link the bug here? https://crbug.com/new

**Comment by bpasero** [comment] 2021-03-16 06:29
https://bugs.chromium.org/p/chromium/issues/detail?id=1188505

**Comment by nornagon** [comment] 2022-03-17 00:18
Closing as this doesn't appear to be an Electron issue.

**Closed by nornagon** 2022-03-17 00:18 UTC
Labels: chromium, blocked/upstream ❌
