### ISSUE TITLE
Tray icon in macOS dark mode isn’t displayed at full opacity

### ISSUE THREAD

**Issue by rdev** [electron/electron#19006] opened 2019-06-27 10:51 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.5
* **Operating System:**
  * macOS Mojave 10.14.5
* **Last Known Working Electron version:**
  * 5.0.4

### Expected Behavior
Tray icon using a template image is white at full opacity in dark mode

### Actual Behavior
Icon is about 50% transparent in dark mode, unless clicked. When active, it’s at full opacity

### To Reproduce
Use any Electron version with #18666 fix, create a tray icon using a template image

### Screenshots

![image (5)](https://user-images.githubusercontent.com/8418866/60260586-1bfd1300-9904-11e9-80b4-3d0c3c25781b.png)

**Comment by codebytere** [comment] 2019-06-27 14:42
Odd, i can reproduce this in 5.0.6 but not in latest master 🤔

**Comment by giddens9527** [comment] 2019-06-28 05:34
@codebytere I was on electron 5.0.6 and using the second approach in the comment. The tray icon was still not displayed at full opacity in dark mode.

**Comment by brunolemos** [comment] 2019-07-02 20:34
Also seeing this at 5.0.6. And I noticed the Title is gray. 

Any patch I can apply locally?

___


#### Template tray image + No title

| State            | Dark Mode | Light Mode |
|-------------|------------|------------|
| Normal        | ❌![image](https://user-images.githubusercontent.com/619186/60543505-d8801b80-9cec-11e9-9fb9-aa1919743972.png) * | ✅ ![image](https://user-images.githubusercontent.com/619186/60543625-21d06b00-9ced-11e9-82c0-8fb4e956d4aa.png) |
| Highlighted | ✅ ![image](https://user-images.githubusercontent.com/619186/60543481-cd2cf000-9cec-11e9-881c-9cfe9f81e48b.png) | ✅ ![image](https://user-images.githubusercontent.com/619186/60543640-29900f80-9ced-11e9-8f21-9301040c9efa.png) |

#### Normal tray image + Title


| State            | Dark Mode | Light Mode |
|-------------|------------|------------|
| Normal        | ❌![image](https://user-images.githubusercontent.com/619186/60543521-e33ab080-9cec-11e9-8e6c-efc5b483207f.png) ** | ❌ ![image](https://user-images.githubusercontent.com/619186/60543798-a02d0d00-9ced-11e9-9070-d8711bfcd6a9.png) *** |
| Highlighted | ✅ ![image](https://user-images.githubusercontent.com/619186/60543949-06199480-9cee-11e9-8155-d9647b413052.png) | ✅ ![image](https://user-images.githubusercontent.com/619186/60543819-af13bf80-9ced-11e9-8d5b-e4872ba85dcb.png) |

_Notes:_
_* Wrong opacity_
_** Title should not be gray and logo seems lighter than it should_
_*** Logo seems darker than it should_

**Comment by codebytere** [comment] 2019-07-02 20:37
@brunolemos yes, the fix is merged already and will go out with the next stable.

**Comment by MarshallOfSound** [comment] 2019-07-02 20:40
@brunolemos You can also fix locally by opting in to dark mode --> https://electronjs.org/docs/tutorial/mojave-dark-mode-guide#automatically-updating-the-native-interfaces

But that will have other affects, I'd suggest waiting for the fix to be released 👍

**Comment by MarshallOfSound** [comment] 2019-07-04 18:19
Fixed in #19013

**Closed by MarshallOfSound** 2019-07-04 18:19 UTC
Labels: 5-0-x, bug :beetle:, platform/macOS

**Comment by brunolemos** [comment] 2019-08-29 00:08
I still have the same issue on macOS Catalina.

**Comment by MarshallOfSound** [comment] 2019-08-29 00:17
@brunolemos This is all documented.  For Catalina on Electron 6 set `NSRequiresAquaSystemAppearance` to `false` in your `Info.plist`

**Comment by brunolemos** [comment] 2019-08-29 04:57
My app doesn’t have any Info.plist, but I’ll look into it, thanks for pointing it out.

**Comment by JamieRuderman** [comment] 2019-10-09 22:59
This seems to be happening again in MacOS 10.15 Catalina

**Comment by brunolemos** [comment] 2019-10-09 23:09
> This seems to be happening again in MacOS 10.15 Catalina

Try a production build, for me it only happens on development, which is less of a big deal.

**Comment by oluul** [comment] 2019-12-06 04:49
> This seems to be happening again in MacOS 10.15 Catalina

+1  macos 10.15.1 electron: 6.1.3

**Comment by ovo4096** [comment] 2020-02-22 02:07
> This seems to be happening again in MacOS 10.15 Catalina

macOS 10.15 electron: 6.1.7

**Comment by ovo4096** [comment] 2020-02-22 02:10
> > This seems to be happening again in MacOS 10.15 Catalina
> 
> Try a production build, for me it only happens on development, which is less of a big deal.

The same happens in production build.

**Comment by masonlee** [comment] 2020-07-13 03:18
Is this issue truly fixed?  I have a full color png tray image (not a template image), and in dark mode on both MacOS 10.14.6 Mojave and on MacOS 10.15.15 Catalina, its color is "washed out".  It's not a simple transparency adjustment; it seems more like a boosted brightness/reduced contrast, just as in the screenshots from @brunolemos above.  And similarly, when I select the tray, the icon displays with normal color while selected.  This happens for me in both dev mode and in my packaged build. I am using electron 9.04. @nick-denry is this what you are seeing, too? Thanks in advance!

**Comment by sebszocinski** [comment] 2021-01-05 01:55
This was happening for me on Catalina, and I just ignored it, but i've since upgraded to Big Sur and it's still an issue (grey icon and title). Hope there is a fix!
