### ISSUE TITLE
Is there a way to force my dedicated GPU to be used rather than integrated, in development?

### ISSUE THREAD

**Issue by enviziion** [electron/electron#18376] opened 2019-05-21 06:59 UTC
Obviously I could export the app to an executable every time I make a change, then use Windows settings to force that executable to use the GPU I want to be used, but that would be extremely tedious. Is there some way through Electron I can force my dedicated GPU to be used rather than the CPU integrated graphics?

**Comment by robatwilliams** [comment] 2019-05-21 08:44
Duplicate of #9842 which needs re-titling

**Comment by enviziion** [comment] 2019-05-21 16:57
I commented there too but was worried the focus on that end would be on forcing integrated GPU.

**Comment by miniak** [comment] 2019-11-10 17:00
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Closed by miniak** 2019-11-10 17:00 UTC
