### ISSUE TITLE
[Bug]: win.setFullScreen() call HIToolbox Error under macOS 13.2.1

### ISSUE THREAD

**Issue by 690591397** [electron/electron#37276] opened 2023-02-15 11:02 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

^18.0.0

### What operating system are you using?

macOS

### Operating System Version

13.2.1 (22D68)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

^18.0.0

### Expected Behavior

No error or confirmation that this error has no effect

### Actual Behavior

When I call **win.setFullScreen(true | false)**, I get an error
```
1   HIToolbox                           0x00000001a5f045c8 _ZN15MenuBarInstance22EnsureAutoShowObserverEv + 120
2   HIToolbox                           0x00000001a5f04188 _ZN15MenuBarInstance14EnableAutoShowEv + 60
3   HIToolbox                           0x00000001a5e718bc _ZN15MenuBarInstance21UpdateAggregateUIModeE21MenuBarAnimationStylehhh + 1184
4   HIToolbox                           0x00000001a5f04004 _ZN15MenuBarInstance19SetFullScreenUIModeEjj + 180
5   AppKit                              0x000000019fcf3d30 -[NSApplication _setPresentationOptions:instance:flags:] + 956
6   AppKit                              0x000000019fb8993c -[NSApplication _updateFullScreenPresentationOptionsForInstance:] + 404
7   CoreFoundation                      0x000000019c7a6560 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
8   CoreFoundation                      0x000000019c844044 ___CFXRegistrationPost_block_invoke + 88
9   CoreFoundation                      0x000000019c843f8c _CFXRegistrationPost + 440
10  CoreFoundation                      0x000000019c777b64 _CFXNotificationPost + 708
11  Foundation                          0x000000019d66738c -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
12  AppKit                              0x000000019fcf42b4 spacesNotificationHandler + 96
13  SkyLight                            0x00000001a13e1214 _ZN12_GLOBAL__N_123notify_datagram_handlerEj15CGSDatagramTypePvmS1_ + 896
14  SkyLight                            0x00000001a170d4d4 _ZN21CGSDatagramReadStream26dispatchMainQueueDatagramsEv + 228
15  SkyLight                            0x00000001a170d3d0 ___ZN21CGSDatagramReadStream15mainQueueWakeupEv_block_invoke + 28
16  libdispatch.dylib                   0x000000019c5489dc _dispatch_call_block_and_release + 32
17  libdispatch.dylib                   0x000000019c54a504 _dispatch_client_callout + 20
18  libdispatch.dylib                   0x000000019c558d1c _dispatch_main_queue_drain + 928
19  libdispatch.dylib                   0x000000019c55896c _dispatch_main_queue_callback_4CF + 44
20  CoreFoundation                      0x000000019c7f2d40 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
21  CoreFoundation                      0x000000019c7b07c0 __CFRunLoopRun + 2036
22  CoreFoundation                      0x000000019c7af878 CFRunLoopRunSpecific + 612
23  HIToolbox                           0x00000001a5e8ffa0 RunCurrentEventLoopInMode + 292
24  HIToolbox                           0x00000001a5e8fde4 ReceiveNextEventCommon + 672
25  HIToolbox                           0x00000001a5e8fb2c _BlockUntilNextEventMatchingListInModeWithFilter + 72
26  AppKit                              0x000000019fa3584c _DPSNextEvent + 632
27  AppKit                              0x000000019fa349dc -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 728
28  AppKit                              0x000000019fa28e0c -[NSApplication run] + 464
29  Electron Framework                  0x000000010ad41510 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 15860032
30  Electron Framework                  0x000000010ad4010c _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 15854908
31  Electron Framework                  0x000000010ad08194 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 15625668
32  Electron Framework                  0x000000010acd7d28 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 15427928
33  Electron Framework                  0x000000010a1209c8 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 3143160
34  Electron Framework                  0x000000010a122178 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 3149224
35  Electron Framework                  0x000000010a11e688 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 3134136
36  Electron Framework                  0x0000000108800018 _ZN2v88internal8compiler10BasicBlock15set_loop_headerEPS2_ + 13624
37  Electron Framework                  0x0000000108801038 _ZN2v88internal8compiler10BasicBlock15set_loop_headerEPS2_ + 17752
38  Electron Framework                  0x0000000108800bd4 _ZN2v88internal8compiler10BasicBlock15set_loop_headerEPS2_ + 16628
39  Electron Framework                  0x00000001087ff6dc _ZN2v88internal8compiler10BasicBlock15set_loop_headerEPS2_ + 11260
40  Electron Framework                  0x00000001087ffba8 _ZN2v88internal8compiler10BasicBlock15set_loop_headerEPS2_ + 12488
41  Electron Framework                  0x00000001085896e8 ElectronMain + 128
42  dyld                                0x000000019c3a7e50 start + 2544
1   HIToolbox                           0x00000001a5e8f90c _ZN15MenuBarInstance22RemoveAutoShowObserverEv + 44
2   HIToolbox                           0x00000001a5f04fbc _ZN15MenuBarInstance15DisableAutoShowEv + 36
3   HIToolbox                           0x00000001a5f050b0 _ZN15MenuBarInstanceD2Ev + 128
4   HIToolbox                           0x00000001a5f04ee0 _ZN15MenuBarInstance7ReleaseEv + 56
5   AppKit                              0x00000001a00914dc -[NSHIPresentationInstance discard] + 228
6   AppKit                              0x00000001a04508b4 -[_NSFullScreenSpace(PresentationInstance) discardPresentationInstance] + 32
```

**Comment by codebytere** [comment] 2023-02-15 11:27
Duplicate of https://github.com/electron/electron/issues/36891. Also, this isn't an error. It's just logging.

**Closed by codebytere** 2023-02-15 11:27 UTC
Labels: bug :beetle:, duplicate
