### ISSUE TITLE
navigator.permissions.query does not reflect that all perms are denied (via session.setPermission(Check|Request)Handler)

### ISSUE THREAD

**Issue by bughit** [electron/electron#19891] opened 2019-08-22 17:43 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * x86 v4.2.9
   * x86 v7.0.0-beta.3
* **Operating System:**
  * win7 sp1 x64

### Expected Behavior
When all perms are denied in chrome, both `navigator.mediaDevices.getUserMedia({audio: true})` and `navigator.permissions.query({name: 'microphone'})` report denials.

The electron facility for denying chrome perms is `session.setPermission(Check|Request)Handler` so it's expected that when all perms are denied, `navigator.permissions.query({name: 'microphone'})` would return "denied".

### Actual Behavior
`navigator.permissions.query({name: 'microphone'})` returns `{state: 'granted'}`

It doesn't actually have this perm as `navigator.mediaDevices.getUserMedia({audio: true})` correctly throws "permission denied"

### To Reproduce
- run the app
  ```js
  'use strict';
  
  const {app, BrowserWindow} = require('electron');
  
  let win;
  
  
  app.on('ready', () => {
  
    win = new BrowserWindow({
      width: 1440,
      height: 900,
      useContentSize: true,
      webPreferences: {
        nodeIntegration: false,
      },
    });
  
    win.webContents.session.setPermissionCheckHandler((webCont, perm, origin, details) => {
      console.log('ChromePermissionCheck %s %O', perm, details);
      return false;
    });
  
    win.webContents.session.setPermissionRequestHandler((webCont, perm, callback, details) => {
      console.log('ChromePermissionRequest %s %O', perm, details);
      callback(false);
    });
  
    win.webContents.openDevTools({mode: 'right'});
  
    win.loadURL('https://example.org/');
  
  });
  ```
- eval `await navigator.permissions.query({name: 'microphone'})` in the devtools console

### Screenshots

![image](https://user-images.githubusercontent.com/895588/63536544-d9aa1980-c4e1-11e9-82fb-7f12cb1b11ac.png)

**Comment by bughit** [comment] 2019-08-22 17:50
@MarshallOfSound What's expected here given the current implementation of denials?

Such a discrepancy between what navigator.permissions.query reports and what is actually available, looks like a bug.

**Comment by MarshallOfSound** [comment] 2019-08-22 22:53
See https://github.com/electron/electron/issues/14544 and https://github.com/electron/electron/pull/14569

In particular closing as a duplicate of #14544 this is a bug as we don't currently route some of these permissions **checks** through the check handler.  They are all correctly routed to the **request** handler though.

In this case the request handler does the async work and the check handler should be responsible for the sync APIs like `permissions.query`

**Closed by MarshallOfSound** 2019-08-22 22:53 UTC

**Comment by bughit** [comment] 2019-08-22 23:07
@MarshallOfSound Are there plans to get this fixed? And will the fix be back-ported?

**Comment by MarshallOfSound** [comment] 2019-08-22 23:15
@bughit The fix would be `feat:` so probably wouldn't be backported

**Comment by bughit** [comment] 2019-08-22 23:23
I'd like to advocate for back-porting. This discrepancy is likely to produce bugs in code that depends on the fidelity of `permissions.query`

**Comment by MarshallOfSound** [comment] 2019-08-22 23:31
@bughit My counter point to that is this has worked this way Since The Beginning Of Time and no one has run into issues yet 😄 Happy to fix, but backporting is a whole other thing that probably won't happen

**Comment by jan4984** [comment] 2019-09-18 06:16
I have same problem.  how can I do screen and user media capture now?

**Comment by spooksmus** [comment] 2021-01-11 08:02
Same issue here- both camera and microphone report granted permissions regardless of their actual permissions. Any plans to resolve this?
