### ISSUE TITLE
`webview` contents don't get properly resized if window is resized when webview is hidden

### ISSUE THREAD

**Issue by elisee** [electron/electron#5110] opened 2016-04-11 10:26 UTC
- Electron version: 0.37.5
- Operating system: Windows 10

Hi! Here's a minimal Electron app to reproduce the bug: [electron-webview-resize-bug.zip](https://github.com/electron/electron/files/212723/electron-webview-resize-bug.zip)
1. Run the app
2. Click the button to hide the webview
3. Resize window
4. Click the button again to show webview
5. **Bug:** Notice the webview hasn't been resized (if you resize the window now then the bug disappears)

GIF demo:
![webview-resize-bug-demo](https://cloud.githubusercontent.com/assets/446986/14424265/6bf2675e-ffe0-11e5-9c4d-fbbd5612f2d3.gif)

Actual use case where I hit the bug: tabbed UI with hidden `<webview>`s for non-active tabs.

---

Bonus bug found while creating the testcase:
1. Remove the `<script>...</script>` tag in `index.html`
2. Launch the app
3. **Bug:** The webview doesn't show up at all.
4. Try reloading with `Ctrl+R`, still doesn't show up
5. Open devtools with `Ctrl+Shift+I`.
6. Try realoding with `Ctrl+R`, notice the webview shows up.

The absence of a script / not having the devtools open seems to prevent the webview from showing? ¯\_(ツ)_/¯

**Comment by xywz** [comment] 2016-04-11 18:15
Can confirm.

The bonus bug is a duplicate of #1117.

**Comment by christoth** [comment] 2016-04-12 16:28
`webview` has issues being hidden or using `display: none;`. It causes the behaviour you're seeing here as well as reloading the current page when un-hidden, as opposed to just becoming visible again.

The `webview` and child `browserplugin` object occupy the correct dimensions in your testcase, it's just the `browserplugin` is not rendering to fill its updated dimensions, cause because the `webview` was hidden.

If the best workaround, is to set the `webview` CSS to `{ width: 0px; height: 0px; flex: 0 1; }`. This will effectively hide it, and not cause the adverse side effects of `display: none;`/`hidden`
[electron-webview-resize-bug-workaround.zip](https://github.com/electron/electron/files/215456/electron-webview-resize-bug-workaround.zip)

I will update the `webview` documentation to make note of this behaviour and the workaround.

**Comment by flexpaper** [comment] 2016-10-04 01:22
I would like to see this fixed as opposed to this workaround as it causes regression issues when trying to calculate the size of elements that are being resized

**Comment by evertonfraga** [comment] 2016-10-07 15:30
Just to make sure: any news on this subject? 

thanks

**Comment by craxal** [comment] 2017-09-25 21:57
I notice something similar happens when you change the zoom level of the shell and the webview's contents. When zooming in, while the webview element itself fills it's parent content, the content with the webview contracts.

**Comment by sofianguy** [comment] 2018-01-30 03:40
Thanks for contributing!

This is an old version that we are no longer releasing bug fixes for. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.

**Comment by craxal** [comment] 2018-02-08 17:14
This doesn't appear to be just an old version problem. I've observed these issues as late as 1.7.7.

**Comment by jondwillis** [comment] 2018-03-09 20:23
I ran into an issue where initially setting `display: none;` or `visibility: hidden` on a `<webview>` initially never allowed it to later appear.

A possible hacky workaround that worked for me is to set width and height to 0, 0 and then to their desired size later.

**Comment by mhuggins** [comment] 2018-08-03 20:38
@christoth Does the scroll position get lost by resizing?  Seems like a negative adverse effect.  Better than the original issue I suppose though.

**Comment by MarshallOfSound** [comment] 2018-09-24 04:40
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by mhuggins** [comment] 2018-09-24 04:45
@MarshallOfSound I haven't upgraded to 3.x yet, but this is still happening on 2.0.9.

**Comment by george-cz** [comment] 2019-04-04 09:42
This no longer reproes on Electron 3.x and newer.

**Closed** 2019-07-10 07:51 UTC
Labels: 2-0-x, bug :beetle:, component/webview, platform/windows

**Comment by MashukeAlam** [comment] 2020-11-06 12:10
Still has this problem in latest electron version. But the advice of setting height and width to 0,0 worked!
