### ISSUE TITLE
Removing iframes doesn't remove their contents from memory

### ISSUE THREAD

**Issue by premitius** [electron/electron#11817] opened 2018-02-02 18:52 UTC
* Electron version: 1.6.1
* Operating system: Mac OSX

### Expected behavior

Memory should be freed when removing iframe

### Actual behavior

Memory is not freed

### How to reproduce

Create an app containing 50 iframes which should each load a heavy webpage with images. Memory usage will increase a lot. If you remove the iframes from the DOM, the memory usage is still as high as if the iframes were still there. session.clearCache will not help.

**Comment by ckerr** [comment] 2018-02-02 19:33
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you're reporting this on, 1.6.1, has been superseded by newer releases -- the latest in that series is 1.6.17. In addition, the latest development release is 1.8.2-beta.5. It would help us greatly if you could test this issue with the latest version.

Please provide a standalone test case that a tester could run to reproduce the issue. Processing and fixing issues goes more smoothly with such tests: not only does it ensure the tester is testing the right thing, but it also speeds the process up. Even a well-described issue without a testcase will be slower because the tester would have to write a test case for every issue.

Additionally, if you could provide more information on how you're measuring memory usage that would make it easier for us to try to reproduce your results.

I'm tagging this issue with needs-information due to the reasons listed above. After you've responded to these requests, please remove the tag and @ me in a followup comment. Thanks in advance! I appreciate your help.

**Comment by premitius** [comment] 2018-02-04 20:23
More specific - it's not the iframes it's the images in the iframes. If you add 500 remote images in a div in Electron, memory usage increases by around 100mb (checked in activity monitor) and never goes below that, even if you remove the element containing the images

**Comment by codebytere** [comment] 2018-02-05 02:58
@premitius thanks for letting us know, since this is a duplicate of https://github.com/electron/electron/issues/11550 as you said we're going to close this out in favor of the pre-existing one. Keep an eye on that one for updates :)

**Closed by codebytere** 2018-02-05 02:58 UTC
Labels: more-information-needed
