### ISSUE TITLE
When Leaving Fullscreen Mode The Window not responding

### ISSUE THREAD

**Issue by shneorasa** [electron/electron#8193] opened 2016-12-13 11:38 UTC
* Electron version: 1.4.1
* Operating system: Windows 10

I open a window with ({fullscreen: true}) property and it load the URL just fine
but when i press F11 to leave Fullscreen mode the window not responding and when i click on the window to get focus, it (the window) disappear and the npm session in the console keep to run

**Comment by kevinsawicki** [comment] 2016-12-13 17:12
I believe this is a duplicate of https://github.com/electron/electron/issues/6036, please subscribe to that issue for updates and it also contains some workarounds.

**Closed by kevinsawicki** 2016-12-13 17:12 UTC
