### ISSUE TITLE
`fs` module does not operate as expected

### ISSUE THREAD

**Issue by michaelwooley** [electron/electron#15932] opened 2018-12-03 16:59 UTC
* Output of `node_modules/.bin/electron --version`: v3.0.5
* Operating System (Platform and Version): Windows 10

I've found that at least two methods of `fs` are not operating as expected when I try to embed them on the renderer side of my electron app.

They are `fs.stat` and `fs.readdir` with option `withFileTypes=true`.

**Expected Behavior**

The sample code shows examples of where errors arise. Figures 1b and 2b in the screenshots show the expected outputs.

**Actual behavior**

Figures 1a and 2a show the outputs/errors that are output when the same commands from the sample code are run from my electron app.

**To Reproduce**

```js
// In a renderer side script
const FS = window.require('fs');

// Will produce error in Fig. 1 below
FS.stat('C:/Users', {}, (err,stats) => console.log(err,stats))

// Will produce output in 
FS.readdir('C:/Users', { encoding: "utf8", withFileTypes: true }, 
  (err,files) => console.log(files)
)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/8423171/49388118-f8187c80-f6e8-11e8-8888-06cb2eaa390b.png)
_**(Fig. 1a)** Error thrown in electron app when `FS.stat` is called as above._

![image](https://user-images.githubusercontent.com/8423171/49388451-97d60a80-f6e9-11e8-9daa-2936fae41f66.png)
_**(Fig. 1b)** Output of `FS.stat` when called from shell._

![image](https://user-images.githubusercontent.com/8423171/49388289-43cb2600-f6e9-11e8-96d7-f44478d48e13.png)
_**(Fig. 2a)** Output from electron app for `FS.readdir` with `withFileTypes = true`_

![image](https://user-images.githubusercontent.com/8423171/49388408-8260e080-f6e9-11e8-894b-76dc887e2b29.png)
_**(Fig. 2b)** Output from node console for `FS.readdir` with `withFileTypes = true`_

**Additional Information**

- These features require somewhat recent builds of node. I checked `process.versions` in my electron app and am running node v10.2.0, so this should not be a problem.
- I am attempting to create a library of react component to be used in my electron app. My use case/issues with `fs` pops up there. (Both modules are being reloaded at the same time with lerna in development.) Could there perhaps be a rebuild issue there?

**Comment by MarshallOfSound** [comment] 2018-12-03 17:23
@michaelwooley That error trace appears to be coming from your own code, in particular, the method `FileBrowser.setFileOrPath`.

Without a repro case we can't look into this, it looks like this issue is coming from your code, if it isn't please provide a minimal bit of sample code that reproduces the error.

**Comment by michaelwooley** [comment] 2018-12-03 20:53
Fair enough. I will pull that together.

**Comment by codebytere** [comment] 2019-05-08 01:07
With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2019-05-08 01:07 UTC
Labels: 3-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
