### ISSUE TITLE
onBeforeSendHeaders behavior changed

### ISSUE THREAD

**Issue by oscar-broman** [electron/electron#21308] opened 2019-11-27 14:00 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 7.1.2**
  * 
* **Operating System: macOS 10.15.1**
  * 
* **Last Known Working Electron version: 6.1.5**
  * 

### Expected Behavior

Outgoing WebSocket connections should be captured.

### Actual Behavior

Outgoing WebSocket connections do not trigger the listener.

### To Reproduce
```js
// main.js
  session.defaultSession.webRequest.onBeforeSendHeaders({ urls: ['ws://*/*', 'wss://*/*'] }, (details, callback) => {
    console.log(details);
    callback(details);
  });

// renderer process
new WebSocket('ws://localhost:8080/') // port different from window.location.port
```

### Additional Information

There is an additional argument to onBeforeSendHeaders which is inaccessible from Electron.

https://developers.chrome.com/extensions/webRequest#implementation

**Comment by sandeep1995** [comment] 2019-11-28 19:39
@anaisbetts 
I guess this is due to the bug on Chromium 
https://bugs.chromium.org/p/chromium/issues/detail?id=1011108

**Comment by sandeep1995** [comment] 2019-12-13 10:55
@ckerr @sofianguy Seems like the issue is fixed in Chromium 81
https://bugs.chromium.org/p/chromium/issues/detail?id=1011108#c21

Can we have a nightly build of electron with Chromium 81? Then I can test and confirm.

**Comment by oscar-broman** [comment] 2020-01-27 12:33
@sandeep1995 I've tried it on 9.0.0-nightly.20200121 which has Chromium version 81.0.4030.0 and the problem remains.

**Closed** 2020-02-11 05:56 UTC
Labels: 7-1-x, blocked/upstream ❌, bug/regression :leftwards_arrow_with_hook:, platform/macOS

**Comment by holmberd** [comment] 2020-04-08 16:09
@sofianguy @sandeep1995 

Looks like WebSocket requests aren't captured when using more laxed rules, i.e. `{ urls: ['*://*/*'] }` on `7.2.1`, only when specifically targeted with e.g. `{ urls: ['wss://*/*'] }`.

**Comment by sckimynwa** [comment] 2025-03-18 06:42
@holmberd same issue & same solution! saved my day thx
still happening in electron 34.1.1
