### ISSUE TITLE
Cannot launch bundled Electron 4.0 app on Linux via file manager

### ISSUE THREAD

**Issue by coreybruce** [electron/electron#15406] opened 2018-10-26 05:35 UTC
Compiled binaries on Linux do no compile properly and show up as shared files, I have been told by the team at electron-packager that this is an electron bug and not a electron-packager bug as seen here as well as an explanation of the bug here:

https://github.com/electron-userland/electron-packager/issues/901#issuecomment-433101967

**Comment by MarshallOfSound** [comment] 2018-10-26 05:36
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by coreybruce** [comment] 2018-10-26 05:51
Sorry @MarshallOfSound, all the information is on that post already explained, I got told to move the bug report here

Electron 4.0.0 beta
Xubuntu 18.04 LTS

### Expected behavior
Compile the binary properly so it's a binary and not a shared filed  (does this on 4.0.0 nightly but not 3.0.6 Latest)



### Actual behavior
proper compiled binary

**Comment by GhostlyDark** [comment] 2018-10-26 16:11
To reproduce, simply double click **electron** in the file manager. An error message should pop up.
Electron v4.0.x works fine when started via terminal or packed as an AppImage (using electron-builder).

**Comment by coreybruce** [comment] 2018-10-26 16:18
@GhostlyDark yes but I don't want to have to run it from the terminal or have my end users have to run it from the terminal to run it, I want it to be a clickable proper running executable also has weird issues after compiling it.

Is Electron 4.x.x broken when compiling with Electron-packager?

**Comment by GhostlyDark** [comment] 2018-10-26 17:19
@coreybruce I don't want AppImage either, I just mentioned it as a workaround. Although I didn't try, I would assume electron-packager is going to have the exact same issue. The messed up binary is always going to be used regardless of the packager.

**Comment by coreybruce** [comment] 2018-10-27 05:33
@GhostlyDark I understand and thanks for the suggestions but that but instead of workarounds we should have this bug fixed

**Comment by adill** [comment] 2018-11-02 19:12
@coreybruce This is a direct result of https://github.com/electron/electron/pull/14962. Nautilus (or, rather, the `file` command it uses) cannot properly distinguish position independent executables from shared libraries (hence it considering `electron` a shared library.) If you take a look at Google Chrome, for example, or any other PIE, it behaves similarly.

This is not an electron bug and is not likely to be resolved anytime soon by the Nautilus or related teams.

**Comment by MarshallOfSound** [comment] 2018-11-03 00:08
Thanks @adill for tracking down the cause, closing this out as wontfix

**Closed by MarshallOfSound** 2018-11-03 00:08 UTC
Labels: blocked/need-info

**Comment by coreybruce** [comment] 2018-11-03 03:12
I never said what file manager I was using nor the Linux distro I was using so how could you assume it's a nautilus bug? 

I am running Xubuntu 18.04 LTS and using Thunar file manager, compiling with electron 3.0.6 and compiles as a proper executable file while using 4.0.0 doesn't. One user at electron-packager said this is a electron bug because of changes to how electron works which I have a link to on this post.

**Comment by MarshallOfSound** [comment] 2018-11-03 10:58
@coreybruce Let's set a couple of things straight.

> compiling with electron 3.0.6 and compiles as a proper executable file while using 4.0.0 doesn't

`electron-packager` does not really compile anything.  All it does is copy thing to the right place, rename a few files and occasionally change some filesystem metadata stuff (`ProductName` on windows, etc.).  

> One user at electron-packager

@malept 👏 did the right thing sending over to the `electron` repository to file a bug report, it definitely wasn't a bug in `electron-packager` so it fell to this repo to investigate.

> I never said what file manager I was using nor the Linux distro I was using so how could you assume it's a nautilus bug?

Nautilus was used an example here, the actual issue comes from the `file` command (as @adill pointed out) that doubtless many other file managers use to identify file types.

> also what do you mean thanks and won't fix? this is a bug and bugs should be fixed especially if it's one that stops users properly making there applications with newer version of Electron.

This is a bug, but not in Electron.  If us enabling `PIE` (a security feature) means file managers don't recognize binaries, that's an issue with those file managers, not Electron.

Just going to say this as well, please moderate your tone here, everyone is volunteering there time to help people out in our issues section so let's be respectful 👍

**Comment by MarshallOfSound** [comment] 2018-11-03 11:47
> does it have to do with that pie security feature and was that added to electron 4.0.0?

Yes

**Comment by coreybruce** [comment] 2018-11-03 11:58
Ok so what do I need to do to allow it to properly compile and show up as an executable binary for Linux users?

**Comment by MarshallOfSound** [comment] 2018-11-03 12:05
@coreybruce Follow along with https://bugs.launchpad.net/ubuntu/+source/file/+bug/1747711 and hope it gets fixed 👍 Also keep in mind most linux users wouldn't be launching binaries from a file manager, they'll be launched from their desktop env using `.desktop` shortcuts or from terminal with their exact name.

**Comment by coreybruce** [comment] 2018-11-03 12:15
Hmm I hope this gets fixed some time soon, thanks for the update!
