### ISSUE TITLE
shell.openExternal as root on Linux freezes the app

### ISSUE THREAD

**Issue by jviotti** [electron/electron#5039] opened 2016-04-05 19:23 UTC
Pass a URL to `shell.openExternal()` freezes the application in GNU/Linux, and the URL is not opened at all. 

![screenshot from 2016-04-05 15 16 06](https://cloud.githubusercontent.com/assets/2192773/14295014/d120bf20-fb41-11e5-867b-bf37a1264e6e.png)

See the following Gist: https://gist.github.com/jviotti/84a69e6d11097187059b6b584ff5e86f

Instructions:

```sh
cd path/to/gist
npm install
sudo npm start
```

No error is thrown, the app just hangs forever.

***

* Electron version: 0.37.4
* Operating system: Ubuntu 14.04 x64

**Comment by jviotti** [comment] 2016-04-05 19:42
By looking at the source code, I see that Electron internally calls `xdg-open`. Running `xdg-open` as `root` is probably not a good idea (I'm not surprised that it doesn't work), however I wonder if we could still workaround this, at least for consistency with the other platforms.

We can find the original username with `who am i`, in case he used `sudo` to run the Electron app, and prepend `sudo -u <user>` to the command in `platform_util_linux.cc`.

There also exists the possibility of a user running a desktop environment as `root`, in which case running `xdg-open` as another user wouldn't be the expected result, although in that case `who am i` would return `root`, and `sudo -u root xdg-open` should lead to the expected results in any case.

Potentially, we can check the result of `who am i`, and if it equals the current user, don't prepend the `sudo` part at all.

**Comment by jviotti** [comment] 2016-04-05 19:45
[node-open](https://github.com/pwnall/node-open) covers this edge case very nicely by checking the `SUDO_USER` environment variable:

```js
// See https://github.com/pwnall/node-open/blob/master/lib/open.js#L55

if (process.env.SUDO_USER) {
    opener = 'sudo -u ' + process.env.SUDO_USER + ' ' + opener;
}
```

**Comment by kevinsawicki** [comment] 2016-04-06 23:39
I believe this is a duplicate of #4916, closing this out here.

**Comment by jviotti** [comment] 2016-04-06 23:58
@kevinsawicki The issue that you linked to talks about `xdg-open` freezing the app because it doesn't return right away (notice it does open the resource). What I'm reporting here is that `xdg-open` freezes the app because its not running as the correct user (without opening the resource at all).

**Comment by kevinsawicki** [comment] 2016-04-07 00:01
Ah okay, sorry about that, they seemed very similar at first.

**Comment by zcbenz** [comment] 2016-04-08 05:36
The problem is not with Electron or root, it is Chrome. When your browser is Chrome, `sudo xdg-open` would block forever, because `sudo chromium-browser` blocks, I didn't try other browsers but they probably have the same problem.

The same thing will happen when you use other users with `sudo`, so unless you can know the user of current shell, you can never really fix this. The only workaround we can do, I think is to make `openExternal` not blocking, which makes this issue a duplicate of #4916.

**Closed by zcbenz** 2016-04-08 05:36 UTC
Labels: bug, linux

**Comment by Tyriar** [comment] 2016-04-08 18:25
@zcbenz so the new API would be `shell.openExternal(string[, options], callback)` then?
