### ISSUE TITLE
[Bug]: pageSize not work when silent print on windows 10

### ISSUE THREAD

**Issue by moom-en** [electron/electron#39590] opened 2023-08-21 08:05 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

pageSize works when silent print.

### Actual Behavior

webContents.print({silent:true, pageSize: 'A5'});
pageSize not works when silent print. it always use printer default pageSize.
![GQ)`MAHY{ LLZVU% AL68V](https://github.com/electron/electron/assets/35919845/c196a2e8-3605-453e-9e98-029e8675e834)
![$WC`JP}C}YNK%0 ~V9Q6O`2](https://github.com/electron/electron/assets/35919845/154b7f80-6ea8-4120-b1f9-496a80ea60df)

**Comment by moom-en** [comment] 2023-08-21 08:07
![GQ)`MAHY{ LLZVU% AL68V](https://github.com/electron/electron/assets/35919845/88971a7e-a2d7-47bc-b62b-a4f6f0589499)

**Comment by codebytere** [comment] 2023-08-23 09:42
Duplicate of https://github.com/electron/electron/issues/31705

**Closed by codebytere** 2023-08-23 09:42 UTC
Labels: bug :beetle:, blocked/need-repro
