### ISSUE TITLE
ready-to-show never fires

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#7779] opened 2016-10-27 22:09 UTC
- Electron version: 1.3.7
- Operating system: macOS & Windows

I'm having some trouble creating a minimal repro for this but it seems that the `ready-to-show` event is not firing for us, since ~1.3.7, despite us having `show: false` in the window options. Filing this in case others are seeing the same behavior.

We had to switch to using `browserWindow.webContents.on('dom-ready', ...`).

**Comment by kevinsawicki** [comment] 2016-10-27 22:14
> Electron version: 1.3.7

Are you able to reproduce this on 1.4.x?

**Comment by kevinsawicki** [comment] 2016-10-27 22:15
> since ~1.3.7

So it fires in 1.3.6 but not in 1.3.7?

**Comment by CharlieHess** [comment] 2016-10-27 22:31
@kevinsawicki also repros on 1.4.4, 1.3.7. Let me step further back in time.

**Comment by CharlieHess** [comment] 2016-10-27 22:44
@kevinsawicki definitely working in 1.2.7.

**Comment by kevinsawicki** [comment] 2016-10-27 22:46
> definitely working in 1.2.7.

@CharlieHess what about 1.3.6?

**Comment by CharlieHess** [comment] 2016-10-28 00:04
@kevinsawicki works in 1.3.6.

**Comment by kevinsawicki** [comment] 2016-10-28 00:09
> works in 1.3.6

Hmm, that is really strange, the only change from 1.3.6 to 1.3.7 was a node upgrade, https://github.com/electron/electron/compare/v1.3.6...v1.3.7

I'm surprised that upgrade would impact this event firing unless something with the event loop integration broke/regressed.

**Comment by kevinsawicki** [comment] 2016-10-31 16:16
> I'm having some trouble creating a minimal repro

@CharlieHess any progress on this?

**Comment by CharlieHess** [comment] 2016-10-31 19:37
No, we swapped out the event and moved on to other things. 😞 I'll let you know if / when I get a simpler repro.

**Comment by zcbenz** [comment] 2016-11-16 01:58
As a work around, I think we can also emit `ready-to-show` on `dom-ready` event, so it would be guaranteed to emit.

Related: #6898.

**Comment by mikecao** [comment] 2016-11-28 06:57
I'm running into the same issue with 1.4.8 (windows x64). The strange thing is that it was working fine and then all of a sudden it just stopped working. No changes were made to the startup script. Had to resort the `dom-ready` event to get it working.

**Comment by mikecao** [comment] 2017-01-02 08:12
@kevinsawicki I think I've identified the issue. Well sort of. I tried copying the main.js of my application over to an electron-quick-start project and it ran fine. So the only difference would be the index.html content that it was loading. I started stripping out content line by line and found that it was my main application bundle that was blocking the event. Unfortunately, my app is in a giant browserified bundle so I can't tell where the problem is. Also it doesn't throw any errors and using `dom-ready` instead works fine. I don't know what triggers `ready-to-show` but it seems to be stuck somewhere when parsing javascript.

**Comment by jprichardson** [comment] 2017-01-05 03:47
Also hit this issue. 

It turns out that when Electron was maximized, and it'd restart, maximized, the the window would show, but this event would never fire. Despite having my windows set visibility to false, I'm assuming it doesn't fire because of this: https://github.com/electron/electron/blob/fcc7dc774accfeb526d7ec8b7ff7115c0693f416/atom/browser/native_window.cc#L565 - which may be a mistake, it should probably always fire regardless of the window being visible or not??

If it matters, I'm also using https://github.com/mawie81/electron-window-state which may be triggering something to cause this issue.

**Comment by Sendoushi** [comment] 2017-02-18 16:08
I'm also having issues. Here is an example (I'm using `electron 1.4.15`):

```js
const {app, BrowserWindow} = require('electron');

function createWindow () {
    // Create the browser window.
    win = new BrowserWindow({width: 800, height: 600});

    // Emitted when the window is closed.
    win.on('closed', () => {
        console.log('closed!');
        win = null
    })

    win.on('ready-to-show', () => console.log("READY TO SHOW!"));

    // and load the url of the app.
    win.loadURL('https://www.google.com');
}

app.on('ready', createWindow);
```

On this example, `closed` logs whenever it is quit (so fine there) but ready to show never triggers.

**Comment by datapimp** [comment] 2017-03-17 12:07
I am also experiencing this on electron 1.6.2, using the most trivial example code on OSX

**Comment by drom98** [comment] 2017-03-17 19:33
I have the same problem, electron 1.6.2 running on elementary os (ubuntu 16.04)

**Comment by gandalius** [comment] 2017-03-29 09:51
I have same problem in electron 1.6.2, windows 7 :(

**Comment by anton-kabysh** [comment] 2017-04-02 22:46
Have the same trouble.

**Comment by mydansun** [comment] 2017-06-04 16:31
Here is my situation.
If I use `webContents.openDevTools()`, this window will never be hidden in start process and the `ready-to-show` event never fires

**Comment by hovancik** [comment] 2017-07-26 14:36
This happens to me sometimes on MacOS, but with `ready-to-show` event.  @zcbenz should I open new isssue or keep it here? 

my code: 

```js
  console.log('1')
  const modalPath = path.join('file://', __dirname, 'break.html')
  console.log('2')
  breakWin = new BrowserWindow({
    x: displaysX(),
    y: displaysY(),
    frame: false,
    show: false,
    fullscreen: settings.get('fullscreen'),
    backgroundColor: settings.get('mainColor'),
    skipTaskbar: true,
    focusable: false,
    title: 'stretchly'
  })
  console.log('3')
  breakWin.loadURL(modalPath)
  console.log('4')
  // breakWin.webContents.openDevTools()
  breakWin.webContents.on('did-finish-load', () => {
    console.log('5')
    breakWin.webContents.send('breakIdea', breakIdeas.randomElement, settings.get('breakStrictMode'))
    breakWin.webContents.send('progress', Date.now(), settings.get('breakDuration'))
    breakWin.setAlwaysOnTop(true)
    breakWin.show()
    breakPlanner.emit('breakStarted', true)
  })
```


in console I see: 

```
1
2
3
4
[13634:0726/140545.134407:INFO:child_thread_impl.cc(882)] ChildThreadImpl::EnsureConnected()
```

**Comment by hovancik** [comment] 2017-07-27 07:47
forgot to add: 
macOS 10.12.5
node 7.4.0
electron 1.6.11

**Comment by itpimp** [comment] 2017-08-16 21:56
Same problem. Worked and then poof... no more.

I have a loading window which first checks some stuff and then IPC to the main.js when it's done. main.js would then load another window in the background and on read-to-show, would close the load screen and .show() the main screen. Just stopped working.

To solve:
```
	mainWindow.loadURL('https://google.co.za')
	loadWindow.close()
	loadWindow = null
 	mainWindow.once('ready-to-show', function(e){
		mainWindow.show()
		mainWindow.maximize();
		mainWindow.webContents.executeJavaScript('alert(1);', function (result) {})
	})
```

Code ON!

**Comment by enlight** [comment] 2017-08-17 01:33
@hovancik @itpimp Have you tried subscribing to the `ready-to-show` event before calling `loadURL()`?

**Comment by hovancik** [comment] 2017-08-17 07:01
@enlight you mean `loadURL()` inside `ready-to-show`? 

I've changed my syntax to: 

```
  breakWin.once('ready-to-show', () => {
    breakWin.show()
    breakPlanner.emit('breakStarted', true)
    breakWin.webContents.send('breakIdea', breakIdeas.randomElement, settings.get('breakStrictMode'))
    breakWin.webContents.send('progress', Date.now(), settings.get('breakDuration'))
    breakWin.setAlwaysOnTop(true)
  })
```
so basically I do `show()` first and have `once()`instead of `.webContents.on(` and it seems to happen less. I haven't had the issue for few days. I've also upgraded node and electron. 

What I think is that the issue occurs when my mac is using a lot of CPU and RAM.

**Comment by enlight** [comment] 2017-08-17 07:27
@hovancik No, I meant:

```javascript
mainWindow.once('ready-to-show', () => {
   ...
})
mainWindow.loadURL('https://google.co.za')
```

**Comment by itpimp** [comment] 2017-08-17 20:12
@enlight Hit's the spot. Thanks.

**Comment by jstrellner** [comment] 2017-08-25 03:43
I am not sure if it's related, but I've noticed that if you have `fullscreen: true` set, then `ready-to-show` will never fire.

In my case, I removed the `fullscreen` option from the `new BrowserWindow()` call, and then after my `win.show();` line, I added `win.setFullScreen(true);` and now the `ready-to-show` event fires, and I can still go full screen with just a small jitter.

Personally, I consider this a bug, and most likely related to this issue.  If you want me to file a new bug report, let me know though.

**Comment by exiadb** [comment] 2017-10-20 08:02
I am having the same issue with electron " 1.8.1" on mac, any other event can be used to register and fire off some script in the browser.

**Comment by marceloavf** [comment] 2017-11-06 16:55
It stop working in `development` mode when is `fullscreen`, only work properly in `production`

**Comment by dwalintukan** [comment] 2018-02-16 03:23
Is there a fix for this?

I just started with Electron and experiencing the same issue. I create a new BrowserWindow on app:ready:
```
uiWin = new BrowserWindow({
    width: 10000,
    height: 10000,
  });
```

and also creating a renderer BrowserWindow:
```
let bgWin = new BrowserWindow({ 
  show: false,
  focusable: false,
  skipTaskbar: true,
});
```

Both do not fire off the `ready-to-show` or `did-finish-load` events...

**Comment by alexeyv** [comment] 2018-02-16 18:54
Had the same issue, consistently reproduced on a tester's computer (Win 7), but never happening on my Win10 virtual machine.

**Comment by lluisrojass** [comment] 2018-03-07 04:27
macOS 10.12.4 
Electron 1.4

still does not work (even after removing `electron-reload` module). Some people might be able to exchange this event for the `webContents` `"dom-ready"` event, which fires on dom load instead.

**Comment by easterism** [comment] 2018-03-23 20:48
`let win = new BrowserWindow({show: false})
win.once('ready-to-show', () => {
  win.show()
})`
https://github.com/electron/electron/blob/master/docs/api/browser-window.md#showing-window-gracefully

**Comment by itonyday** [comment] 2018-03-24 07:40
@easterism 
oh, it works, and it's a strange logic.

**Comment by Zlocoder** [comment] 2018-07-28 18:32
ready-to-show not fired if I set webPreferences.preload

**Comment by Slapbox** [comment] 2018-09-10 19:42
I'm seeing the same behavior as @Zlocoder, `ready-to-show` doesn't seem to fire if I use `preload`, except for my first window.

**Comment by VladimirMerk** [comment] 2018-11-05 20:56
A similar problem with ips, which was not in version 2, but appeared in version 3.
If you create an electron as a child process using **spawn.child_process** and specify **ipc** in **stdio**, then **ready-to-show** will never work, but if the **ipc** is not specified, then everything works.
Another thing I noticed is that the **ready-to-show** works only if **show: false**
If **show: true**, then the event does not work, but the page is loaded if **inherit**, and if the **ipc** is just a white screen

Test code
_spawn.js_
```const path = require('path')
const { spawn } = require('child_process')
const spawnCommand = process.execPath
const spawnOptions = {
  // stdio: ['inherit'] ready-to-show work
  stdio: ['inherit', 'inherit', 'inherit', 'ipc'] //  ready-to-show don't work
}
const spawnArgs = [
  path.join(__dirname, 'index.js')
]
const child = spawn(spawnCommand, spawnArgs, spawnOptions)
```

_index.js_
```const {app, BrowserWindow} = require('electron')
console.log('start')
let window = null
app.once('ready', () => {
  window = new BrowserWindow({show: false})
  window.loadURL('https://github.com')
  window.once('ready-to-show', () => {
    console.log('ready-to-show')
    window.show()
  })
})
```

**Comment by dxwc** [comment] 2019-01-24 01:37
Same Issue

+ Node v10.11.0
+ Electron v4.0.2
+ Linux, Solus 3.9999

```
const { app, BrowserWindow } = require('electron');

let win;

function create_window()
{
    win = new BrowserWindow({ show : false });
    win.once('ready-to-show', () =>
    {
        console.log('Emitted');
        win.show();
    });
    win.on('close', () => win = null);
}

app.on('ready', create_window);
```

**Comment by jaishankarh** [comment] 2019-02-13 11:05
Same Issue.

But I realised that if win.maximize() is called, then ready-to-show event does not fire. It worked after having removed the call to maximize().

Hope it helps!

Thanks,

**Comment by DeerMichel** [comment] 2019-06-26 22:58
Confirmed to work under Electron 5, 6, 7. Feel free to open a new issue if this problem persists under one of these (currently supported) versions.

**Closed by DeerMichel** 2019-06-26 22:58 UTC
Labels: 3-0-x, bug :beetle:, good first issue

**Comment by pushkin-** [comment] 2019-06-28 22:23
@DeerMichel This issue still exists in Electron 5.0.6.

In the electron quick start example, make main.js:

```
const {app, BrowserWindow} = require('electron')

function createWindow () {
  var mainWindow = new BrowserWindow({width: 800, height: 600, show: false });
	mainWindow.maximize(); // if you comment this, ready-to-show will fire
	mainWindow.on("ready-to-show", () => {
		console.log("!!!!!!!!!!!!!!!!!");
		mainWindow.show();
	});
  mainWindow.loadFile('index.html');
}

app.on('ready', createWindow);
app.on('window-all-closed', function () { app.quit() });
```

When you call `maximize()` on the window, `ready-to-show` never fires and you don't see the `"!!!!!"` logged to the console.

**Comment by pushkin-** [comment] 2019-06-28 22:32
@DeerMichel  Actually, nevermind that's. That's [documented](https://github.com/electron/electron/issues/8861) behavior.

**Comment by JsusDev** [comment] 2019-07-26 13:40
https://www.npmjs.com/package/ready-to-show

**Comment by jrcichra** [comment] 2019-11-24 01:49
Still seeing this issue with v6.1.2. Is there any way I can maximize before I hit "did-finish-load?"

**Comment by Slapbox** [comment] 2019-11-25 18:39
Also still seeing this in `6.x` - with a `preload` script, which I strongly suspect is the cause.

**Comment by dannyharding10** [comment] 2020-08-05 18:52
For me, `ready-to-show` was never firing in Windows because we were calling `browserWindow.hide()`. That issue is documented here #24855

**Comment by devflow** [comment] 2020-09-07 13:32
**Note for others.** if you load a local html file with `loadURL()` on macOS(with ASAR. but works on Windows). it's failed to load and never firing `ready-to-show`. use instead `loadFile()`.

**Comment by Slapbox** [comment] 2020-09-07 19:04
@devflow, interesting tip! What exactly is the difference between these two methods? Since `loadURL` mentions it accepts the `file://` URI, I'm not clear on when one would want to use `loadURL('file://...')` over `loadFile`.

**Comment by pushkin-** [comment] 2020-09-07 22:42
@Slapbox I'm pretty sure `loadFile` is just a convenience method.

`win.loadURL('file://${__dirname}/app/index.html')`

vs

`win.loadFile('app/index.html')`

also the options objects that you can pass to them are different.

**Comment by devflow** [comment] 2020-09-08 06:47
@Slapbox in my case, 
- `win.loadURL(path.join(__dirname, 'views', 'anchor.html'));` : works on windows, but not on macOS.
- `win.loadFile(path.join(__dirname, 'views', 'anchor.html'));`: works on Windows and macOS.

**Comment by BlessonKu** [comment] 2020-09-13 06:55
I seem to still be having a similar problem. 
Everything works as expected on Electron v8.2.5, however, Electron v10.1.1 fires ready-to-show very randomly.
Is this a bug or a feature?
Am I using something improperly?

I used [electron-forge](https://www.electronforge.io/) to create the project.
Here's the code
```js
const {app, BrowserWindow} = require('electron');
const path = require('path');

if (require('electron-squirrel-startup')) { // eslint-disable-line global-require
  app.quit();
}

const createWindow = (WindowName,properties) => {
    properties = properties || {}
    
    properties.show = properties.show || false
    properties.frame = properties.frame || false
    
    if (!properties.webPreferences)
        properties.webPreferences= {
            nodeIntegration: true
        }
	
    var Window = new BrowserWindow(properties);
	
    Window.once('ready-to-show',function(){
        console.log('sending window to load')
        Window.show();
        Window.webContents.send('loadWindow', WindowName)
    });
    
    Window.loadFile(path.join(__dirname, '/window.html'));
    
    return Window
};

const createMainWindows = () => {
    
    mainWindow = createWindow('Main')//,{fullscreen:true});
	
    toolbarWindow = createWindow('Tools',{
        parent:mainWindow,
        width: 200,
        height: 400,
        fullScreenable: false,
        maxWidth: 300,
        x: 10,
        y: 60
    });
};

app.on('ready', createMainWindows);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createMainWindows();
  }
});
```
I removed some comments but you should be able to replicate the issue with this

**Comment by devflow** [comment] 2020-09-13 10:09
@BlessonKu Try deleting the slash(`/`) at your loadFile().
