### ISSUE TITLE
[Bug]: When the window minimize button is pressed and held, the main process is suspended

### ISSUE THREAD

**Issue by WangJM001** [electron/electron#37647] opened 2023-03-22 15:30 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

19.1.9

### Expected Behavior

The main process is running normally

### Actual Behavior

 The main process is suspended

### Testcase Gist URL

https://gist.github.com/fa48f70deb38585da905056167629d49

### Additional Information

https://user-images.githubusercontent.com/20501316/226955145-02d52487-1ce7-425c-843f-c2fbf9acd55f.mp4

**Comment by dsanders11** [comment] 2023-04-19 20:54
Thanks for the report @WangJM001.

This is standard quirky behavior on Windows. You can see the same thing with "Task Manager" - pressing and holding any of the window control buttons will cause the UI to stop updating. Right-clicking and holding anywhere on the titlebar will also have the same effect.

If this is problematic for your application, you could make your `BrowserWindow` frameless and create a custom titlebar, as some Electron apps do.

Since this repros in native Windows apps, is a corner case, a workaround exists, and it's not easy for Electron to fix/maintain, I'm going to close this issue.

For the interested reader, the root cause here is that calling `DefWindowProc` for a `WM_NCLBUTTONDOWN` message on the window control buttons (`HTMINBUTTON`/`HTMAXBUTTON`/`HTCLOSE`) blocks until the user releases the button, for whatever reason.

**Closed by dsanders11** 2023-04-19 20:54 UTC
Labels: platform/windows, bug :beetle:, has-repro-gist, 22-x-y
