### ISSUE TITLE
"beforeunload" event doesn't work reliable

### ISSUE THREAD

**Issue by ysengrimm** [electron/electron#7977] opened 2016-11-15 15:27 UTC
* Electron version: 1.4.6
* Operating system: Windows 10 (Version 1607)

```js
function handleWindowBeforeunload(event) {
    const confirmed = (dialog.showMessageBox(remote.getCurrentWindow(), options) === 1);
    if (confirmed) {
        remote.getCurrentWindow().close();
    } else {
        event.returnValue = false;
    }
}

window.addEventListener("beforeunload", handleWindowBeforeunload);
```

### Expected behavior

The window should stay open except when button 1 is pressed in the message box.

### Actual behavior

Sometimes (~1 out of 10 times) the window will close, regardless of the button pressed in the message box.
It happens more often when the developer tools are closed, and never happens when using the debugger to step over the code.

### How to reproduce

Use the code snipped above with any message box with >= 2 buttons, with closed developer tools.

The code above is loosely modeled in the way atom does their beforeunload handling. 
(https://github.com/atom/atom/blob/master/src/window-event-handler.coffee#L150)

**Comment by zcbenz** [comment] 2016-11-17 03:58
I'm unable to reproduce, can you print some logging in your code to see whether `event.returnValue` is actually executed?

**Comment by yishn** [comment] 2016-11-23 14:33
Hi, I have the same problem on Windows 10 with v1.4.7, and I could reproduce it with the following code, appended in the default app:

~~~html
<script>
    let {dialog} = require('electron').remote

    window.addEventListener('beforeunload', evt => {
        let result = dialog.showMessageBox({
            message: 'Quit app?',
            buttons: ['Yes', 'No']
        })

        if (result == 1) evt.returnValue = false
    })
</script>
~~~

What I found out is this: If you want to close the window and click on the 'No' button *right away*, the close operation is canceled. But if you *wait ~3 sec* and then click 'No', the window closes anyway.

**Comment by Kagami** [comment] 2016-11-23 18:06
Exactly same issue on Linux with electron 1.4.8.

>click on the 'No' button right away, the close operation is canceled. But if you wait ~3 sec and then click 'No', the window closes anyway

Same here.

**Comment by YsenGrimm** [comment] 2016-11-23 18:14
I can reproduce the ~3 mark after which the return  value is ignored, as described by @yishn.

Also artificially pausing the render process with a ```while (true)  {} ``` loop doesn't change the behavior.

**Comment by Kagami** [comment] 2016-12-11 01:50
Any progress on this? Seems pretty important. Have you been able to reproduce, @zcbenz?

**Comment by yishn** [comment] 2016-12-15 20:07
I've found a workaround for this problem if someone is interested in that:

~~~js
let {dialog} = remote
let closeWindow = false

window.addEventListener('beforeunload', evt => {
    if (closeWindow) return

    evt.returnValue = false

    setTimeout(() => {
        let result = dialog.showMessageBox({
            message: 'Quit app?',
            buttons: ['Yes', 'No']
        })

        if (result == 0) {
            closeWindow = true
            remote.getCurrentWindow().close()
        }
    }, 0)
})
~~~

**Comment by Kagami** [comment] 2016-12-15 20:16
That's smart, thanks! Will try.

**Comment by yishn** [comment] 2017-01-07 14:02
It seems that my hack has a drawback on macOS: Quitting an app doesn't behave as expected. Since we always signal that the window closing has been cancelled the first time, the OS always assumes that we don't want to quit the app after all.

**Comment by astoilkov** [comment] 2017-01-12 11:29
I am also experiencing the exact same problem. The issue starts to appear when you use `dialog.showMessageBox()`. Using `event.returnValue = false;` works every time.

@zcbenz Are you still unable to replicate this? Maybe I can put some time making a project that showcases the problem.

**Comment by Kagami** [comment] 2017-02-20 20:00
@yishn it works for me on Sierra.

**Comment by badams** [comment] 2017-02-28 02:56
I'm having the same issue on MacOS with the following code 
```
    window.addEventListener('beforeunload', function (event) {
        event.returnValue = confirm('Do you want to quit ?');
    });
```

Clicking cancel the first time works (most of the time) clicking cancel subsequent time closed the app.

**Comment by brrd** [comment] 2017-03-10 10:38
I'm experiencing a similar issue. In my case (electron 1.6.2, ubuntu 14.04), this occurs when the window is closed with the `win.close()` or `app.quit()` methods. Everything work as expected when clicking the window native close button or when using the `"role": "close"` attribute in menu.

**Comment by Scazzino** [comment] 2017-05-06 02:04
I'm having the same problem. It works fine if I have the devtools open. But if I close the devtools then the the window closes even if I click the no button in a confirmation dialog triggered by onbeforeunload. My dialog confirmation returns true or false for should close on not to the onbeforeunload handler. I then set e.returnValue to that returned result. With the devtools open it works fine. With the devtools closed the window always closes regardless of what I return from the dialog. What's even weirder is that if I just set e.returnValue = false; directly, without using a confirmation dialog then it does prevent the window from closing whether the devtools are open or closed. So it appears to be some conflict between the combination of the main window, the devtools and the dialog window... I'm currently testing on Mac OS X El Capitan.

**Comment by zcbenz** [comment] 2017-05-31 07:50
I'm unable to reproduce with following steps, a minimal app to reproduce this would be appreciated:

1. Open default app of Electron v1.7.1
2. Open devtools and run:
```js
    window.addEventListener('beforeunload', function (event) {
        event.returnValue = confirm('Do you want to quit ?');
    });
```
3. Close devtools
4. Close window and dialog shows
5. Click cancel and window keeps open
6. Repeat 4-5

**Comment by yishn** [comment] 2017-05-31 08:32
I can still reproduce the issue with [my code](https://github.com/electron/electron/issues/7977#issuecomment-262528220) on Windows 10 and Electron v1.7.2.

~~~js
let {dialog} = require('electron').remote

window.addEventListener('beforeunload', evt => {
    let result = dialog.showMessageBox({
        message: 'Quit app?',
        buttons: ['Yes', 'No']
    })

    if (result == 1) evt.returnValue = false
})
~~~

>  If you want to close the window and click on the 'No' button *right away*, the close operation is canceled. But if you *wait ~3 sec* and then click 'No', the window closes anyway.

**Comment by CoDanny** [comment] 2017-06-18 21:38
@zcbenz it looks like the combination of the ```onbeforeunload``` event and using a ```dialog.ShowMessageBox``` in the handler to confirm the close is what's causing this to fail. Could try to lookn that specific combo? It's still happening for me on 1.6.11

**Comment by eteisman** [comment] 2017-12-20 10:04
I'm running into this issue with electron 1.7.6

Sometime the window will not close at all. In this case it is impossible to kill the app.
Sometimes it will close, even when I choose "No" in the confirmation box. 

Code (Angular 2):
  @HostListener('window:beforeunload', ['$event'])
  public beforeUnloadWindow($event) {
    let sConfirmMessage: string = 'Close this application?';
    $event.returnValue = confirm(sConfirmMessage);
  }

**Comment by eteisman** [comment] 2017-12-20 10:11
I can confirm yishn 's solution works on Windows. Thanks!

**Comment by Aurora12** [comment] 2017-12-21 14:48
I can confirm the problem on electron mac 1.7.9 app built by electron-builder 19.49.0.

However, appears to work fine _with dev tools closed_ when you use **callback** in dialog.showMessageBox() instead of relying on return result. 

Otherwise closes the app upon dismissing the dialog with any answer. My guess is that you shouldn't block main thread by modal window in onbeforeunload handler. No Idea why dev tools matter though.

**Comment by CptMaumau** [comment] 2018-02-01 08:16
This works for me on both Mac and Windows
```
$(window).on('beforeunload', function (evt) {
  if (!confirm('Do you want to close screen')) {
    return false;
  }
}
```

**Comment by codebytere** [comment] 2018-02-15 16:15
Closing as duplicate of https://github.com/electron/electron/issues/9966

**Closed by codebytere** 2018-02-15 16:15 UTC
Labels: platform/windows, triaged/bug, version/1.4.x

**Comment by swapnil0545** [comment] 2018-08-03 12:21
I tried everything but its not working for me.
`if (!confirm(this.leaveDialogText)) {
              e.preventDefault();
              e.returnValue = 'false';
              return false;
            };`
It works when I am in debugging mode though. Otherwise doesn't

**Comment by fuweichin** [comment] 2020-06-08 08:08
use both `event.preventDefault()` and `event.returnValue='xxx'`

see my blog post [A robust way to prevent window from unloading with onbeforeunload and addEventListener beforeunload](https://blog.csdn.net/flashdelover/article/details/106605541)
