### ISSUE TITLE
webContents.print silent option not working as expected

### ISSUE THREAD

**Issue by Prosen-Ghosh** [electron/electron#14072] opened 2018-08-14 10:29 UTC
* Electron Version: 2.0.7
* Operating System (Platform and Version): Ubuntu 16.04

**Expected Behavior**
The print task should be sent without showing the system dialog, and it should print the html content.

**Actual behavior**
it is not doing anything at all.

**To Reproduce**

```js
secondWindow.webContents.print({silent: true, printBackground : false, deviceName : ''},(success) => { 
    if(success){
        console.log(success);
        secondWindow = null;
     }
 });
```

`silent : false` option is printing the content but not calling the callback function. i don't want the user interaction when something need to be printed.

```js
secondWindow.webContents.print({silent: false, printBackground : false, deviceName : ''},(success) => { 
    if(success){
        console.log(success);
        secondWindow = null;
     }
 });
```

**Comment by nornagon** [comment] 2019-01-23 19:53
Duplicate of #16362 I think?

**Closed by nornagon** 2019-01-23 19:53 UTC
Labels: 2-0-x, bug :beetle:, platform/linux/ubuntu

**Comment by FranckFreiburger** [comment] 2019-01-23 19:57
please also merge issue labels ?
