### ISSUE TITLE
[Bug]: Tray menu item is not centered in windows10

### ISSUE THREAD

**Issue by WangleJiu** [electron/electron#40914] opened 2024-01-08 14:12 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.3

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

I try to set Tray's Menu for my app with Electron version 27.0.3, I hope Menu item is Centered, but the text is right-aligned.

my code is:

```tray = new Tray('D:\\Program Files\\XiaoWei\\resources\\assets\\icon.png');
    const contextMenu = Menu.buildFromTemplate([
      { label: 'Item1', type: 'normal' },
      { label: 'Item2', type: 'normal' },
      { label: 'Item4', type: 'normal' }
    ]);
    tray.setToolTip('This is my application.');
    tray.setContextMenu(contextMenu);
```

the screenshot is:
![image](https://github.com/electron/electron/assets/15786478/dd5a5347-1774-43b7-ab2e-c621219294e1)

### Actual Behavior

I also try Electron by version 25.4.0, It's acting correctly.
![image](https://github.com/electron/electron/assets/15786478/76974345-0e61-4577-b266-323813e9421f)

### Testcase Gist URL

https://gist.github.com/WangleJiu/64e11575334f6c38f886b672703c42f2

**Comment by WangleJiu** [comment] 2024-01-09 03:11
this is gist for my problem
https://gist.github.com/WangleJiu/64e11575334f6c38f886b672703c42f2

**Comment by codebytere** [comment] 2024-01-12 13:45
I'm not able to reproduce this behavior; it looks as expected on 27.0.3:

<img width="333" alt="Screenshot 2024-01-12 at 2 44 54 PM" src="https://github.com/electron/electron/assets/2036040/9a004426-7bb0-46f0-bb88-f7e1fff77af4">

**Comment by WangleJiu** [comment] 2024-01-15 03:54
This problem occurs on win10，on win11 it works fine. 
Your system looks to be win11. @codebytere

**Comment by Veiintc** [comment] 2024-03-07 02:19
I have the same problem in 28.2.0

**Comment by mlaurencin** [comment] 2024-04-17 21:20
I'm able to repro this but only on Windows 10. As mentioned above, it works fine on Windows 11.

![image](https://github.com/electron/electron/assets/35157522/8d821603-9d6f-4f43-8beb-f84fdbcd21fc)

**Comment by mlaurencin** [comment] 2024-04-17 22:33
After doing some bisecting, it looks like all through v26 and v27 the menu was going from being centered to left aligned to centered to right aligned. This continued at least up through the 29 nightlies. With v30.0.0-alpha.2 however there is a distinct change in the UI and the text is centered. Unfortunately, after doing a comparison it looks like the commit that probably fixed things was a Chromium bump https://github.com/electron/electron/compare/v30.0.0-alpha.1...v30.0.0-alpha.2 . 

@WangleJiu If you test on v30.0.0-alpha.2 or v30.0.0 is the issue resolved for you?

**Comment by WangleJiu** [comment] 2024-06-25 07:02
@mlaurencin I have tried v30.0.0-alpha.2 and it works normal, thanks a lot!

**Comment by rmchen-12** [comment] 2024-07-16 07:31
same problem in 29.x.x

**Comment by codebytere** [comment] 2024-07-16 09:08
Closing as there's not much more we can do here - 29 is security-only and it's fixed in 30.

**Closed by codebytere** 2024-07-16 09:08 UTC
Labels: platform/windows, bug :beetle:, status/confirmed, has-repro-gist, 27-x-y, 29-x-y, 30-x-y
