### ISSUE TITLE
geolocation.getCurrentPosition returns PositionError

### ISSUE THREAD

**Issue by yapwr** [electron/electron#16139] opened 2018-12-19 04:20 UTC
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.11
* Operating System (Platform and Version): MacOS 10.14.2
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.0.10

**Expected Behavior**
navigator.geolocation.getCurrentPosition should provide location.

**Actual behavior**
navigator.geolocation.getCurrentPosition returns `PositionError`.

**To Reproduce**
Main.js
```
process.env.GOOGLE_API_KEY = '<some value>';
```

In any renderer process
``` 
navigator.geolocation.getCurrentPosition(function (position) {
    console.log('Pos: ', position);
}, function (error) {
    console.log('Err', error);
});
```

**Screenshots**
v4.0.0-beta.11
<img width="362" alt="screenshot 2018-12-19 at 12 14 35 pm" src="https://user-images.githubusercontent.com/8402861/50198730-d0cbdb80-0387-11e9-9e8d-37fa6a3d6c25.png">

v3.0.10
<img width="935" alt="screenshot 2018-12-19 at 12 18 22 pm" src="https://user-images.githubusercontent.com/8402861/50198821-5a7ba900-0388-11e9-85b1-550ad41b605c.png">

**Comment by EricGeigerQ** [comment] 2018-12-23 18:44
I can confirm I also have this issue. navigator.geolocation.getCurrentPosition works as expected under Electron 3.0.x, but upgrade to Electron 4.0.0 and I get a PositionError instead.

**Comment by lucienimmink** [comment] 2019-01-31 21:38
Still happening with electron 4.0.3

**Comment by deepak1556** [comment] 2019-02-11 07:17
The issue is fixed in https://github.com/electron/electron/pull/15618, which is available in 5.x releases. I will check if this can be considered to backport into 4.x releases.

**Comment by groundwater** [comment] 2019-02-11 17:30
We discussed this change for 4.0, but do not feel it would be a safe-enough change for an already-stable release line.

**Comment by codebytere** [comment] 2019-02-26 14:36
Closing as `wontfix` based on above comment.

**Closed by codebytere** 2019-02-26 14:36 UTC
Labels: 4-0-x, bug :beetle:, platform/macOS
