### ISSUE TITLE
[Bug]: showOpenDialog / showSaveDialog opens _behind_ the app after the second call onward

### ISSUE THREAD

**Issue by Prinzhorn** [electron/electron#32857] opened 2022-02-10 18:06 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.8, 17.0.0, 18.0.0-alpha.1

### What operating system are you using?

Ubuntu

### Operating System Version

Linux alex-desktop 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

Opening a file save / open dialog opens the dialog on top of the app

### Actual Behavior

The first time it works, every dialog after that opens behind the app

### Testcase Gist URL

https://gist.github.com/0302a1125c460df377ff8733e7ddb154

### Additional Information

Related

https://github.com/electron/electron/issues/27053
https://github.com/electron/electron/issues/24959

But this doesn't require any special arguments.

Steps:

1. Run Fiddle
2. Click "Open File"
3. Cancel
4. Click "Open File" again
5. Dialog is off-center and behind the app

Fiddle itself has the same issue when I click "Save As"

**Comment by codebytere** [comment] 2022-02-14 11:47
@Prinzhorn it looks like this is a function of a new-ish Gnome focus-stealing prevention behavior; it happens when a notification pops at the top saying "app_name is ready". I'll try to see if there's some kind of way around it. In the meantime, here's a workaround you can probably use: https://ubuntuhandbook.org/index.php/2020/12/quick-tip-remove-window-is-ready-notification-focus-window-immediately/

**Comment by Prinzhorn** [comment] 2022-02-14 12:18
Thanks for looking into this. FWIW `window.open` with `nativeWindowOpen` does not have this issue (which is an entirely different window system I assume and not related to the gtk file dialog). Also Chromium itself doesn't have this issue either (e.g. hitting `ctrl+s`). The dialog opened by https://github.com/electron/electron/issues/32165 does have the same issue. I'm using Ubuntu exclusively and have never noticed this issue with other apps I'm using. So there must be a way to consistently open the window in focus.

**Comment by codebytere** [comment] 2022-02-14 13:57
@Prinzhorn you're right - it happened after https://github.com/electron/electron/pull/19159 because the transient window isn't being set properly anymore. I'm looking into it :)

**Comment by Jelmerro** [comment] 2022-05-03 13:15
I'm also running into this issue, but in my case I do not get the Gnome notification at all, and the workaround doesn't work either, as I'm using the Cinnamon DE, which was forked from Gnome a long time ago. But the issue is exactly the same, second dialog opens behind the window, and in my case breaks mouse interaction with both the parent and the dialog. I have to alt-tab and kill the app to get back any mouse interaction. Is there any more info required to resolve this issue, if so, I'll happily provide it, as this is quite a big issue for one of my apps. Interestingly, `dialog.showMessageBox` and `dialog.showMessageBoxSync` both work flawlessly.

**Comment by iggith** [comment] 2022-05-24 11:08
Same here: a dialog preceded by notification opens behind the main window. The simplest case -- just a `dialog.showOpenDialog` call in a template application.

`Electron Fiddle` on the same machine: the file dialog works as expected no matter how many times used (no notifications as well), however `About` dialog triggers notification and opens behind the main window.

Ubuntu 20.04.4 LTS, GNOME 3.36.8
Node.js 16.13.2, Chromium 100.0.4896.143, Electron 18.2.1
Electron Fiddle 0.28.1

**Comment by origin-yaropolk** [comment] 2022-06-02 17:20
Got this issue too

**Comment by quanzhuo** [comment] 2022-06-08 06:10
After some test, I found that this issue didn't exist on electron 13.6.9  but appears in 14.0.1. Hope this information helps. @codebytere

**Comment by darac-10** [comment] 2022-06-09 09:29
I use fedora 35, gnome 41, architecture x64, electron 19.x.y. and I have the same problem.
After several tests and attempts of old versions, I found that on version 17.4.7 everything is correct, and on version 18.x.y and higher the mentioned problem occurs.
The same problem is on both the X11 and the Wayland desktop environment.

the electron I use is not customized, but pre-built.
It is installed with `npm install electron` .

Hope this information helps.

**Comment by codebytere** [comment] 2022-06-09 10:11
@darac-10 as mentioned above, we already know precisely why this is occurring. It's simply that we don't know how to address the problem.

https://github.com/electron/electron/issues/32857#issuecomment-1039117399

**Comment by tristan957** [comment] 2022-07-06 16:53
@krkarel the problem is that the dialog is ran in a separate process, the `xdg-desktop-portal` implementation. You aren't given a handle to the actual window unfortunately, which is what Electron was relying on to set various X11/Wayland modifiers on the native window.

Here are the docs for the parent class of the object GTK hands back to Electron: https://docs.gtk.org/gtk3/class.NativeDialog.html. You can see it is a pretty bare bones class with no access to the X11 window or Wayland surfaces (correct terminology?).

Ideally Electron would set [transient-for](https://docs.gtk.org/gtk3/property.NativeDialog.transient-for.html), but I can't see that an Electron window is actually a [GtkWindow](https://docs.gtk.org/gtk3/class.Window.html).

**Comment by tristan957** [comment] 2022-07-06 18:37
That is already happening:

https://github.com/electron/electron/blob/main/shell/browser/ui/file_dialog_gtk.cc#L171=
https://github.com/electron/electron/blob/main/shell/browser/ui/file_dialog_gtk.cc#L338=

**Comment by tristan957** [comment] 2022-07-27 23:11
Ok, I had a little bit of an epiphany today.

In the relevant XDG Desktop Portal D-Bus API: https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.FileChooser, you can see that there is a `parent_window` argument. This argument is either the `xid` or Wayland `handle` depending on whether or not the the program is running under X11 or Wayland. GTK usually gets this argument from a parent `GtkWindow`. In our case, we have no such thing because the Electron window is not a `GtkWindow` from what I can tell. Luckily Chromium has the relevant APIs to grab at the [`xid`](https://source.chromium.org/chromium/chromium/src/+/main:ui/gtk/x/gtk_ui_platform_x11.cc;drc=1db5690e105e2e987042b13d2a1c7d48193fe6df;bpv=1;bpt=1;l=80?gsn=SetGtkWidgetTransientFor&gs=kythe%3A%2F%2Fchromium.googlesource.com%2Fchromium%2Fsrc%3Flang%3Dc%252B%252B%3Fpath%3Dui%2Fgtk%2Fx%2Fgtk_ui_platform_x11.cc%23FnPOMz2iCwELhW6pCy7ntxsdik4tsjIfPsxpj7smJMY&gs=kythe%3A%2F%2Fchromium.googlesource.com%2Fchromium%2Fsrc%3Flang%3Dc%252B%252B%3Fpath%3Dui%2Fgtk%2Fx%2Fgtk_ui_platform_x11.h%237gqq-Wgz0P7dcoM2a63ZJGzix5il2Jm6lE7v3AAhXnk) and [`handle`](https://source.chromium.org/chromium/chromium/src/+/main:ui/gtk/wayland/gtk_ui_platform_wayland.cc;drc=1db5690e105e2e987042b13d2a1c7d48193fe6df;bpv=1;bpt=1;l=106?gsn=SetGtkWidgetTransientFor&gs=kythe%3A%2F%2Fchromium.googlesource.com%2Fchromium%2Fsrc%3Flang%3Dc%252B%252B%3Fpath%3Dui%2Fgtk%2Fwayland%2Fgtk_ui_platform_wayland.cc%23zUnwOvvAMGQBMTj6vgdT-fjCaSnSs_gbv6lQ13pxigs&gs=kythe%3A%2F%2Fchromium.googlesource.com%2Fchromium%2Fsrc%3Flang%3Dc%252B%252B%3Fpath%3Dui%2Fgtk%2Fwayland%2Fgtk_ui_platform_wayland.h%23_5p48hh5CJKxc-3QU-YPAbTIYYE0Klj1ss1ahj0IXWk).

So in order to fix this we need to be able to construct a fake `GtkWindow` using the `xid` or the `handle` where the `GtkWindow` will represent the Electron window. Luckily this code has already been [written](https://github.com/flatpak/xdg-desktop-portal-gtk/blob/main/src/filechooser.c#L483).

Think I might tinker with this tonight to see what I can dig up.

Alternatively Electron could use the DBus APIs directly, but sounds horrible to me :).

**Comment by stingray21** [comment] 2022-08-24 17:12
Is there a fix or maybe a work-around, that one can implement until a fixed version in published?

**Comment by tristan957** [comment] 2022-08-24 17:17
Refer to the upstream issue where discussion is taking place. Slow moving, but we know how to solve the issue.

**Comment by bigloong** [comment] 2022-09-05 09:50
Any progress?

**Comment by AlexanderWright** [comment] 2022-09-25 10:27
> Refer to the upstream issue where discussion is taking place. Slow moving, but we know how to solve the issue.

Could you please link to the upstream issue? I could not find it. TY.

**Comment by tristan957** [comment] 2022-09-26 15:04
TBH I thought this was the VSCode repo when I made that, so the "upstream issue" I was probably referring to was the PR that I made to try and solve the issue that didn't end up working out. See https://github.com/electron/electron/pull/35110.

**Comment by tristan957** [comment] 2022-09-28 18:56
This has been an issue since version 14 I believe.

**Comment by codebytere** [comment] 2022-09-29 09:07
@craxal: https://github.com/electron/electron/issues/32857#issuecomment-1150935043

**Comment by bkilinc** [comment] 2022-09-29 09:27
> This has been an issue since version 14 I believe.

15.5.7 works fine for me. From 16 on there is this issue. So I don't upgrade.

**Comment by freimer** [comment] 2022-09-29 12:17
Is there a system package or library or something we can back-rev to an earlier version that does not have the PR / commit that caused this issue?  I suspect most don't really care about "native file chooser dialogs" if it is going to break things.  So my preference would be to back-rev as mentioned above by @bkilinc even if that is moving from a recent version to one from way back.  Unfortunately, I don't know if that is easy to do, or if Electron is baked into applications such as VS Code, where we would need to back-rev the version of the app itself.  I'll check with the VS Code team as far as how to back-rev the whole app, but if we can fix this by downgrading Electron on the whole system that would be better than playing whack a mole for each application.  I can't imagine the number of hours wasted by everyone across the whole world on this one issue.  Must be in the millions of hours by now.

**Comment by bkilinc** [comment] 2022-09-29 15:34
> I suspect most don't really care about "native file chooser dialogs" if it is going to break things.
That is correct, we dropped native dialogs and used web based filemanager in newer version. After that we dropped Electron as application can be installed as PWA and also can be used as web based application. Sometimes we need legacy version but not much.

**Comment by Prinzhorn** [comment] 2022-09-29 15:41
Please keep the discussion on-topic. With every comment you make you are sending notifications to dozens of people for no reason. If your project needs native dialogs / Electron or not is not relevant to this discussion.

**Comment by tristan957** [comment] 2022-09-29 15:46
@codebytere last we talked in the PR that _tried_ to fix this, we came to two possible solutions.

1. Implement the Linux file chooser using the xdg-desktop-portal primitives (ie libportal or dbus)
2. Pull in the Chromium file choosers from upstream that seem to already implement this

You said 2 hadn't been possible previously because Chromium's file choosers didn't have all the features that Electron needed. Discussion seemed to have stalled when I asked whether that was still the case.

**Comment by MikeJerred** [comment] 2022-10-04 13:00
Is there any workaround for this?

**Comment by zerkms** [comment] 2022-10-04 22:09
@MikeJerred for vscode I stopped using the open file dialog and switched to `ctrl-r` (and I find it actually is much more convenient, so even when this bug is fixed I won't switch back).

**Comment by bkilinc** [comment] 2022-10-05 06:31
> @MikeJerred for vscode I stopped using the open file dialog and switched to `ctrl-r` (and I find it actually is much more convenient, so even when this bug is fixed I won't switch back).
"eclipse theia blueprint" does not have this issue. I won't switch back either.

**Comment by maymage** [comment] 2022-11-11 12:55
@tristan957 

Reading this issue I recalled https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/358#note_266379

Anyway.. the focus stealing thing is a common problem in GNOME land with electron apps.. I am sure that the folks over there would be happy, if this got fixed on an Electron level. 

I think [Florian Müllner ](https://gitlab.gnome.org/fmuellner) is the right guy to ask..
e.g. on https://matrix.to/#/%23gnome-shell%3Agnome.org

**Comment by gagayuan** [comment] 2022-11-17 03:38
Obviously ,this is a ubuntu's bug which called "focus-stealing-prevention policy",a very Bad new feature. Even vscode have the same problem. According to @maymage ,I found the extension【[Focus my Window](https://extensions.gnome.org/extension/1005/focus-my-window/)】 is perfect to solve this bug!! Thank you !!!
显然，这是一个ubuntu的bug，原本是个称为“焦点窃取预防策略”的新特性，然而这是个非常糟糕的新功能。甚至大名鼎鼎的vscode也有同样的问题。根据@maymage的说法，我发现安装GNOME Shell Extensions扩展：【[Focus my window](https://extensions.gnome.org/extension/1005/focus-my-window/)】能够完美解决这个bug ！！非常感谢！！

**Comment by cmarincia** [comment] 2022-11-19 18:47
Coming from https://github.com/microsoft/vscode/issues/146422, any news on this topic?

**Comment by theamarin** [comment] 2022-11-25 16:23
Signal Desktop app on Gnome would also be happy if this could get fixed: signalapp/Signal-Desktop/issues/6184
Thanks for your work folks!

**Comment by jordan4ibanez** [comment] 2023-01-24 02:36
Yes, it would benefit the Linux ecosystem greatly if there were any news on fixes for this minor nuisance

**Comment by bkilinc** [comment] 2023-01-24 06:50
Since this is issue is 1 year old, we can assume that electron is not supported in Linux. It is a good choice for windows (or mac, I don't know), but don't assume that your app will be cross-platform.

**Comment by jordan4ibanez** [comment] 2023-01-24 07:27
> Since this is issue is 1 year old, we can assume that electron is not supported in Linux. It is a good choice for windows (or mac, I don't know), but don't assume that your app will be cross-platform.

My friend, I appreciate your input, I really do. But, it seems like you missed a pretty huge section on the readme. https://github.com/electron/electron#platform-support

**Comment by bkilinc** [comment] 2023-01-24 08:26
> > Since this is issue is 1 year old, we can assume that electron is not supported in Linux. It is a good choice for windows (or mac, I don't know), but don't assume that your app will be cross-platform.
> 
> My friend, I appreciate your input, I really do. But, it seems like you missed a pretty huge section on the readme. https://github.com/electron/electron#platform-support

Yes, it writes Linux is supported and there is this issue unfixed for 1 year. These are just the facts. May be README should be updated also.

**Comment by jordan4ibanez** [comment] 2023-01-24 08:28
> > > Since this is issue is 1 year old, we can assume that electron is not supported in Linux. It is a good choice for windows (or mac, I don't know), but don't assume that your app will be cross-platform.
> > 
> > 
> > My friend, I appreciate your input, I really do. But, it seems like you missed a pretty huge section on the readme. https://github.com/electron/electron#platform-support
> 
> Yes, it writes Linux is supported and there is this issue unfixed for 1 year. These are just the facts. May be README should be updated also.

If this simple issue cannot be fixed within a year, I don't think we're going to see a readme update within the next decade I'm afraid :(

**Comment by gbodeen** [comment] 2023-03-08 17:54
This bug occurs with Electron apps running in MATE 1.16.2 (from 2016) as well, so it's not limited to recent versions of GNOME.

**Comment by freimer** [comment] 2023-03-11 13:36
Does anyone have a fork that simply removes the commit changes that broke this?  Seems like the most straight-forward easy fix.

**Comment by alexanderjohn** [comment] 2023-03-16 17:10
Same issue confirmed with VSCode on Mint 21.1, Cinnamon 5.6.7, Kernel 5.19.0

VSCode:
```
Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:57:21.103Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.19.0-35-generic
Sandboxed: No
```

**Comment by tristan957** [comment] 2023-04-11 16:40
The bugs are not related. This bug has to do with not passing either the X id or the Wayland handle, which isn't possible because the root Electron window is not a GTK window, so Electron needs to drop down to libportal or D-Bus primitives to fix this. The same underlying bug could be the same in the Chromium one, but the code in Electron is completely separate in this case. I gave a pretty good write up in a linked PR or earlier in this issue. Unfortunately, no one from the Electron team seems to have an answer to the question, "Can Electron use the file chooser dialog implementations from Chromium?" All I know is that previously the answer was no, but I am not sure if that is still the case. This bug could be fixed by using upstream Chromium's portal implementation, which they should have if I am remembering correctly. Been months and months since the last time I paid active attention to this bug, even though I have been affected by it recently.

**Comment by morfyum** [comment] 2023-04-29 16:55
Same issue on Fedora 38 with VSCode. Any solution? 
VsCode devs close the comments.

**Comment by rienheuver** [comment] 2023-05-09 11:18
Same here.
OS:
Ubuntu 22.04.2 LTS
Gnome 42.5
X11

App:
VSCode 1.77.3
Electron 19.1.11
Chromium 102.0.5005.196

**Comment by nkallen** [comment] 2023-05-12 10:47
This bug significantly impacts the usability of Electron apps on Linux. Would a bug bounty help prioritize a fix for this? I would be happy to use the built-in Chromium file browser if there were a way to access it. I would be willing to donate money to have this fixed.

**Comment by afagund** [comment] 2023-05-14 14:09
Looks like nobody cares, this issue is more than one year old. The Linux community does not deserve this.

**Comment by jannotti-glaucio** [comment] 2023-05-14 15:11
I agree @afagund, this bug disturbs me a lot using vscode and slack on Linux Mint.

**Comment by securegh** [comment] 2023-06-21 23:45
same here:

  Operating System: Zorin OS 16.2
            Kernel: Linux 5.15.0-72-generic
      Architecture: x86-64

VSCodium:

Version: 1.78.2
Release: 23132
Commit: e06ea6147733c975d26c3d3552462681e05cb147
Date: 2023-05-12T00:42:22.773Z
Electron: 22.3.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-72-generic
Sandboxed: No

**Comment by origintopleft** [comment] 2023-07-02 19:35
I can't reproduce this with KDE, and they've had focus stealing prevention since 3.x. Maybe this is a GNOME/GTK bug instead of an Electron one?

**Comment by zomp** [comment] 2023-07-03 08:09
I have been experiencing this (every time) on KDE for some time (a year?). Kubuntu 23.04, KDE backports.

**Comment by amoliski** [comment] 2023-07-26 17:41
This is still an issue, and a nasty surprise to find after spending a year developing an Electron app with the assumption that basic functionality would work given the documentation says it's supported on Linux without an asterisk. 

Can we please get a response to [tristan957](https://github.com/tristan957) or [nkallen](https://github.com/nkallen)'s questions on using Chromium's picker, a bug bounty. If it's really a 'them' issue, can we have an Electron dev being a bit more forceful in the GNOME bug thread, because the devs over there seem to think their focus stealing prevention stopping a file picker dialog from opening is working as intended.

**Comment by tristan957** [comment] 2023-07-26 18:11
> can we have an Electron dev being a bit more forceful in the GNOME bug thread, because the devs over there seem to think their focus stealing prevention stopping a file picker dialog from opening is working as intended

This is in no way a GNOME bug, and it is entirely an Electron bug. I know because I wrote the code that introduced it. I debugged the issue as you can see in a linked PR to Electron that has since been closed because it didn't actually solve the issue. To summarize, what I didn't know at the time of adding support for the file chooser portal was that I have no way of notifying GTK of the parent window's X11 ID or Wayland handle.

So, until someone from Electron decides on 1 of the 2 aforementioned directions, we are dead in the water on this issue.

**Comment by tristan957** [comment] 2023-07-26 18:17
The first `NULL` here is the bug: https://github.com/electron/electron/blob/main/shell/browser/ui/file_dialog_gtk.cc#L77-L79

**Comment by maymage** [comment] 2023-07-26 19:02
Perhaps related

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/358#note_266379

**Comment by nkallen** [comment] 2023-07-26 21:19
Hm - I'm wondering if the "discretionary control over funding allocation"
would actually allow this bug to get prioritized. For me it's easily worth
several thousand dollars in value, and I would join this tier.

**Comment by bkilinc** [comment] 2023-07-27 06:55
> Perhaps related
> 
> https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/358#note_266379

I don't think this is a gnome issue. Electron works fine with version 15.5.7. If I upgrade, this issue appears, on the same machine (Linux Mint 21.2)

**Comment by amoliski** [comment] 2023-07-27 21:38
> > Perhaps related
> > https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/358#note_266379
> 
> I don't think this is a gnome issue. Electron works fine with version 15.5.7. If I upgrade, this issue appears, on the same machine (Linux Mint 21.2)

I would argue that having an OS API for bringing a window to the foreground, then applying a heuristic system that selectively ignores calls to the API (the first time works just fine, the second and onward calls are treated differently) that causes issues with a large swath of consumer software is an issue with their implementation. I understand not wanting a chat window stealing keyboard focus while you are typing a password in another window, but maybe something as simple as allowing dialogs titled 'Save'/'Save As'/'Open' take focus could be a working solution.

**Comment by bkilinc** [comment] 2023-07-29 11:15
> I would argue that having an OS API for bringing a window to the foreground, then applying a heuristic system that selectively ignores calls to the API (the first time works just fine, the second and onward calls are treated differently) that causes issues with a large swath of consumer software is an issue with their implementation. I understand not wanting a chat window stealing keyboard focus while you are typing a password in another window, but maybe something as simple as allowing dialogs titled 'Save'/'Save As'/'Open' take focus could be a working solution.

This does not help solving the problem. Even if, gnome has a bug, there should be a workaround or electron should not be advertised as cross platform. Moreover this does look like a gnome bug. How do you explain version 15.5.7. does not have this problem ?
I understand this is an happy accident; some applications does not work as it should on linux. Forcing people to move to other platforms.

**Comment by craxal** [comment] 2023-08-01 17:59
> > can we have an Electron dev being a bit more forceful in the GNOME bug thread, because the devs over there seem to think their focus stealing prevention stopping a file picker dialog from opening is working as intended
> 
> This is in no way a GNOME bug, and it is entirely an Electron bug. I know because I wrote the code that introduced it. I debugged the issue as you can see in a linked PR to Electron that has since been closed because it didn't actually solve the issue. To summarize, what I didn't know at the time of adding support for the file chooser portal was that I have no way of notifying GTK of the parent window's X11 ID or Wayland handle.
> 
> So, until someone from Electron decides on 1 of the 2 aforementioned directions, we are dead in the water on this issue.

Is there an existing issue or discussion about how to make the parent window or handle available in the necessary contexts? What's the current state of that discussion?

**Comment by tristan957** [comment] 2023-08-01 18:31
It already is available within Chromium.

**Comment by aiddya** [comment] 2023-08-18 05:26
I looked at the Electron [dialog API](https://www.electronjs.org/docs/latest/api/dialog) and compared it with what's available in Chromium's [SelectFileDialog](https://source.chromium.org/chromium/chromium/src/+/main:ui/shell_dialogs/select_file_dialog.h).

Electron's dialog API has a lot of platform specific options. It tries to combine all platforms' options into one API. Chromium on the other hand only supports options that are supported everywhere, that is an intersection instead of a union. So, I don't think it'll be possible to completely replace Electron's implementation with Chromium's. However, Linux has far fewer platform-specific features. It might be possible to implement some common features in upstream and patch the rest in Electron. Linux can use the patched Chromium implementation, while Mac and Windows will have bespoke ones.

The additional features that will need to be implemented are:

* Customizing button labels
* Selecting multiple directories
* Showing hidden files
* Hiding overwrite confirmation for save dialog (This should be deprecated, IMO)

Here are the full details:

| Open Dialog Features                            | SelectFileDialog option                                                  |
| :---------------------------------------------- | :----------------------------------------------------------------------- |
| title                                           | SelectFile ctor                                                          |
| defaultPath                                     | SelectFile ctor                                                          |
| buttonLabel                                     | **MISSING**                                                              |
| filters\[]                                      | SelectFile ctor                                                          |
| filters\[].name                                 | FileTypeInfo->extension\_description\_overrides                          |
| filters\[].extensions                           | FileTypeInfo->extensions                                                 |
| properties.openFile                             | Type.SELECT\_OPEN\_FILE                                                  |
| properties.openDirectory                        | Type.SELECT\_EXISTING\_FOLDER                                            |
| properties.multiSelections                      | Type.SELECT\_OPEN\_MULTI\_FILE (only for files, **directories missing**) |
| properties.showHiddenFiles                      | **MISSING**                                                              |
| properties.createDirectory (macOS only)         | Type.SELECT\_FOLDER                                                      |
| properties.promptToCreate (Windows only)        | **MISSING**                                                              |
| properties.noResolveAliases (macOS only)        | **MISSING**                                                              |
| properties.treatPackageAsDirectory (macOS only) | **MISSING**                                                              |
| properties.dontAddToRecent (Windows only)       | **MISSING**                                                              |
| message (macOS only)                            | **MISSING**                                                              |
| securityScopedBookmarks (macOS only)            | could probably be implemented                                            |

Save dialog API has a large overlap with open dialog. SelectFileDialog supports both types with similar limitations. A save dialog can be created by setting the type as `SELECT_SAVEAS_FILE`. The next table is for unique save dialog features.

| Save Dialog Features                   | SelectFileDialog option  |
| :------------------------------------- | :----------------------- |
| nameFieldLabel (macOS only)            | **MISSING**              |
| showsTagField (macOS only)             | **MISSING**              |
| showOverwriteConfirmation (Linux only) | **MISSING**, always true |

**Comment by tristan957** [comment] 2023-08-18 05:33
@aiddya thanks for looking into this! To me, it seems like the viability of patching upstream code is how they do their fallback if the D-Bus portal APIs aren't available. Not sure how much churn would have to happen on the Electron side to share the same fallback mechanisms.

**Comment by aiddya** [comment] 2023-08-18 05:44
You can see the [details here](https://source.chromium.org/chromium/chromium/src/+/main:ui/shell_dialogs/shell_dialog_linux.cc). Chromium tries to call DBus APIs during initialization and will use portals if it succeeds. It falls back to toolkit APIs if that fails. It should be possible to replicate that by kicking off the DBus check in the `Initialize` method of `electron_api_dialog`.

**Comment by albicasty** [comment] 2023-08-22 17:16
+1, found the same issue

**Comment by qbadev** [comment] 2023-08-29 14:40
as a workaround, Ubuntu or maybe even Gnome users may install Grand Theft Focus extension.
https://extensions.gnome.org/extension/5410/grand-theft-focus/

**Comment by luojinzhang** [comment] 2023-09-04 04:26
Have this issue on ubuntu 20.04, and electron 20.0.2. I notice VSCode also has this issue too. Seriously, this drives me nuts, but at least the workaround works.

**Comment by foxxy432** [comment] 2023-09-05 22:05
It is ignored by Microsoft because of incompatibilities BUT you can use my fork: https://github.com/lnxx-kernel/electron_touch

**Comment by bkilinc** [comment] 2023-09-06 06:30
> It is ignored by Microsoft because of incompatibilities BUT you can use my fork: https://github.com/lnxx-kernel/electron_touch

So, the bug is fixable. Is it possible for you to create a pull request for the fix ?

**Comment by konstantin-lukas** [comment] 2023-09-24 17:59
Adding my piece to the cake: I just go this issue refactoring an old project. Weirdly I am not getting this error with the old version of my app but with the new one I do. Both times I'm using Fedora. In terms of code both versions are quite different so I don't know what could be causing it. Maybe some dependency like React, maybe something else, idk. So far, it seems to me that this is not a bug that is caused by the combination of electron and some operating system but by the combination of electron and some other code. I'm not saying it is react, I'm just saying there's got to be some fix for this as I have two versions of my app that behave differently on the same machine as far as this bug is concerned. Imho this is quite a nasty bug because it made me think my app froze until I found this issue and realized the dialog had just opened behind the window.

**Comment by afagund** [comment] 2023-11-19 18:08
Congrats to the people involved. Its been almost 2 years since we reported this bug.

**Comment by AlexandreBonneau** [comment] 2023-12-15 03:04
> I can't reproduce this with KDE, and they've had focus stealing prevention since 3.x. Maybe this is a GNOME/GTK bug instead of an Electron one?

> I have been experiencing this (every time) on KDE for some time (a year?). Kubuntu 23.04, KDE backports.

This bug exists in KDE and is 100% reproducible since the beginning of times (I can remember being hit with it using Draw.io in 2018, so it's been going on at least 5 years now).
For info this is happening in Linux Debian using X11 (haven't tried wayland).

**Comment by tristan957** [comment] 2023-12-15 04:55
> I can remember being hit with it using Draw.io in 2018, so it's been going on at least 5 years now

As the author of the bug, this is incorrect. The bug was introduced in 2021.

**Comment by AlexandreBonneau** [comment] 2023-12-15 06:43
My memory could fail me, but I'm pretty sure I experienced this bug from the get go, and I started using draw.io in 2018.
Or perhaps I first used draw.io within confluence for a few years before using the desktop version, and then got hit with that bug..

**Comment by espeluznante** [comment] 2023-12-25 03:53
The first time it works fine, but when called a second time, the dialog box appears behind the main window.

**Comment by afagund** [comment] 2024-01-23 12:28
Next month it's going to complete 2 years that we've been waiting for a solution for this. I will not give up, I am still waiting.

**Comment by brtdylan** [comment] 2024-03-07 02:11
I see this issue as well on ubuntu 22.04 when calling dialog.showOpenDialog with a parent window set. The first call seems to work, then the subsequent calls all open the dialog behind the app with the system notification triggered, etc

I noticed that when downloading a file via electron's webcontents::downloadURL API, and not manually setting a save path on the DownloadItem, a save dialog is opened. This dialog seems to work correctly, opening on top of the app and in focus. I looked into the electron source to see if I could identify what's different here, but I was quickly out of my depth here. However, I wanted to share this in case it's insight in fixing the issue:

This seems to be where downloadURL eventually opens a properly functioning (save) dialog: https://github.com/electron/electron/blob/62331f5ac14954367e1e762b9f206c81ebe35109/shell/browser/electron_download_manager_delegate.cc#L272

and this is where I believe dialog.showOpenDialog leads to: https://github.com/electron/electron/blob/62331f5ac14954367e1e762b9f206c81ebe35109/shell/browser/api/electron_api_dialog.cc#L60

**Comment by AlexandreBonneau** [comment] 2024-03-15 07:17
On Debian testing (trixie) with Kde, the dialog is opened behind the parent window for the very first call (tested with Draw.io desktop 24.0.4 which uses electron 28.1.0).

**Comment by morfyum** [comment] 2024-03-17 14:58
I found similar issue in Gnome notification. 
Supposedly come some improvement for gnome. 
Gnome issue can related to this?

On Gnome with Firefox or any application can be reproduce.

When download something from Firefox, and click to "Open in folder" button, Firefox open Nautilus application.
When you dont close Nautilus, and navigate back to Firefox, and click again into "Open if folder" button, Gnome-shell just send a notification about opening. When I click to notification, Nautilus select this file, but stay in background.

Same issue on Fractal 6 client. When application in background, gnome send notification every message, but nitifications has no function. Won't open, won't move into top layer the application.

**Comment by starball5** [comment] 2024-03-26 23:13
Is this related in any way to https://github.com/flatpak/xdg-desktop-portal-gtk/issues/137?

**Comment by xing403** [comment] 2024-04-18 01:24
关于这个问题(`Linux Ubuntu` 调用系统`dialog` 首次出现在应用顶层，之后调用 显示 `已就绪` 并且 `dialog` 一直在应用下方)，有什么可以解决的方法吗

**Comment by Jamtastic808** [comment] 2024-04-19 14:36
Hi, any sign of a fix for this please?

**Comment by ReillyBrogan** [comment] 2024-04-19 20:32
> Hi, any sign of a fix for this please?

Do you see any Electron PRs linked to this issue? No? Then no there is no sign of a fix. Please avoid commenting if you have nothing to add to the issue.

**Closed** 2024-05-09 13:51 UTC
Labels: platform/linux, bug :beetle:, component/dialog, status/confirmed, has-repro-gist, 16-x-y, 17-x-y, 18-x-y, 19-x-y, 20-x-y

**Comment by Yoryky** [comment] 2024-09-12 02:26
I find that electron v17.4.8 is ok but V17.4.9 will meet this problem. this code changes like this in file_dialog_gtk.cc
![图片](https://github.com/user-attachments/assets/021e5c96-e957-4fb1-bde7-70182f31adde)
