### ISSUE TITLE
The tooltip of the button for annotations is "undefined" in PDF 

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#25971] opened 2020-10-15 19:01 UTC
There is one button which tooltip displays "undefined"

### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.1
* **Operating System:**
  * Windows 10 

### Expected Behavior
To be not undefined

### Actual Behavior
It is undefined

### To Reproduce
Open PDF and hover it
### Screenshots
![image](https://user-images.githubusercontent.com/5815794/96174391-eaadb980-0f31-11eb-9fa1-fd60ecbb1624.png)

**Comment by MarshallOfSound** [comment] 2020-10-15 19:30
Probably missing a translation string. 🤔

**Comment by codebytere** [comment] 2020-10-16 04:23
To triage this further we're going to need a sample pdf @gdavidkov - i don't know which you loaded and by default the annotate button doesn't show on most PDFs so I'm having trouble reproducing.

**Comment by gdavidkov** [comment] 2020-10-16 07:40
@codebytere  thanks for your prompt response. I also wonder if it possible to control these buttons? I don't why this button for annotations is visible.

I tested it on Electron 9.3.1 and 9.2.1 - the result is the same.

Here is the repo - https://gist.github.com/gdavidkov/fb910fda8c271bd8451b6f2fb95157f8

![image](https://user-images.githubusercontent.com/5815794/96226337-24ff7100-0f9b-11eb-9891-00df103c38f1.png)

**Comment by codebytere** [comment] 2020-10-16 21:27
ah @gdavidkov you're right! looks like we disabled it on v10 and beyond (it didn't work before) I'll pop up a PR to get it on v9 too!

**Comment by gdavidkov** [comment] 2020-10-18 14:06
@codebytere thank you very much!

**Comment by codebytere** [comment] 2020-10-19 20:02
Closed by https://github.com/electron/electron/pull/26004

**Closed by codebytere** 2020-10-19 20:02 UTC
Labels: bug :beetle:, component/pdf-viewer, platform/all
