### ISSUE TITLE
[Bug]: query string missed when form  submit get in webview

### ISSUE THREAD

**Issue by magmaliang** [electron/electron#28688] opened 2021-04-16 10:45 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

macOS

### Operating System Version

mac os 11.2.3

### What arch are you using?

x64

### Expected Behavior

I  cloned rep from `https://github.com/electron/electron-quick-start`

then just update `index.html` 's content as following : 

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <!-- https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP -->
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'">
    <meta http-equiv="X-Content-Security-Policy" content="default-src 'self'; script-src 'self'">
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using Node.js <span id="node-version"></span>,
    Chromium <span id="chrome-version"></span>,
    and Electron <span id="electron-version"></span>.

    <form id="searchForm" action="https://github.com/electron/electron/issue" target="_blank" method="get">
      <div class="form-inline form-control-normal">
          <label class="label">
              <span class="label-name large-span">query:</span>
              <input type="text" class="small-input" name="q" value="form+method+get">
          </label>
      </div>
      <div class="btn-group form-inline">
          <button name='submit'>open window</button>
      </div>
    </form>

    <!-- You can also require other files to run in this process -->
    <script src="./renderer.js"></script>
  </body>
</html>

```

when button [open window] clicked,  a window with url `https://github.com/electron/electron/issue?q=form%2Bmethod%2Bget&submit=` should be opened.

### Actual Behavior

Actually the url of  new-popped-window is : `"https://github.com/electron/electron/issue"`

query string is missing.

**Comment by Prinzhorn** [comment] 2021-04-16 13:57
I can confirm this. It works with `nativeWindowOpen: true` as expected. It also works as expected when removing `target="_blank"`. So it's some edge case I guess.

**Comment by magmaliang** [comment] 2021-04-19 13:54
> I can confirm this up to most recent `v13.0.0-beta.14 `. It works with `nativeWindowOpen: true` as expected. It also works as expected when removing `target="_blank"`. So it's some edge case I guess.

Thanks for response.It works.

But another question discovered: web within webview cannot open new window(window.open or <a> element) under the config `nativeWindowOpen: true`. I have searched the issues and stackoverflow, no usefull tricks can solve this....


Is there any suggestion?

Thanks a lot!

**Comment by Prinzhorn** [comment] 2021-04-19 15:33
I wasn't suggesting using `nativeWindowOpen` in general, I only tried to narrow this down for the Electron team to track this bug down faster. I have never used webview, so I can't help you with that.

**Comment by nornagon** [comment] 2021-04-20 23:50
I can reproduce this. Here's a gist version for easy [Fiddle](/electron/fiddle)ing: https://gist.github.com/b34db338397fbbdf7c44731e5d253fbb

It works in the current master branch because [nativeWindowOpen is now true by default](https://github.com/electron/electron/pull/28552). nativeWindowOpen: false is deprecated and will eventually be removed.

Unfortunately I don't think it's worth fixing this for the nativeWindowOpen: false case. It would mean parsing the form data and converting it to URL query parameters, which is rather a lot of error-prone code for quite an obscure feature to fix a bug that only occurs when using a deprecated option. So I'd recommend switching to nativeWindowOpen: true and filing a bug for the issue you're having with <webview> and window.open under nativeWindowOpen: true.

I'm closing this as status/wontfix for the above reason.

**Closed** 2021-04-20 23:50 UTC
Labels: bug :beetle:, status/wontfix 🚫

**Comment by lazyManLearn** [comment] 2021-06-25 07:58
我想问一下这个问题解决了没？我之前用11.3的版本出现这个问题，改成13.0以上的版本还是出现这个问题
