### ISSUE TITLE
webview touch event cannot handling outside webview

### ISSUE THREAD

**Issue by smilejp** [electron/electron#6563] opened 2016-07-21 15:44 UTC
* Electron version: 1.2.8
* Operation system : Windows 8 64bit
* Touch Screen monitor(LG-23ET63)

index.html body
```
  <h2>
    <script>
      document.write(`Welcome to Electron ${process.versions.electron}`);
    </script>
  </h2>

  <webview id="webView" src="./webview1.html" style="height:300px;width:100%;top:200px;position:absolute" autosize="on" minWidth="300" minHeight="400"></webview>

  <script>
    document.body.addEventListener('mouseup', function() {console.log("mouseup");});
    document.body.addEventListener('mousedown', function() {console.log("mousedown");});
    document.body.addEventListener('click', function() {console.log("click");});
    document.body.addEventListener('touchstart', function() {console.log("touchstart");});
    document.body.addEventListener('touchend', function() {console.log("touchend");});
  </script>
```

webview1.html body
```
<body>
  <div style="height:300px;width:100%;background-color:red;">
    <h2>
      WebView Page Area
    </h2>
  </div>

  <script>
    document.body.addEventListener('mouseup', function() {console.log("webview mouseup");});
    document.body.addEventListener('mousedown', function() {console.log("webview mousedown");});
    document.body.addEventListener('click', function() {console.log("webview click");});
    document.body.addEventListener('touchstart', function() {console.log("webview touchstart");});
    document.body.addEventListener('touchend', function() {console.log("webview touchend");});
  </script>
</body>
```

test page like this :
<img width="439" alt="electron-problem" src="https://cloud.githubusercontent.com/assets/3704914/17028506/cc471a16-4fa2-11e6-9500-f2b01e725aee.png">

when i TOUCH  1 area.
index.html developer console message :
```
touchstart
touchend
mousedown
mouseup
click
```
webview developer console message :
nothing.

when i TOUCH 2 area.
index.html developer console message :
nothing.

webview developer console message :
```
webview touchstart
webview touchend
webview mousedown
webview mouseup
webview click
```

when i MOUSE CLICK 2 area.
index.html developer console message :
```
mousedown
mouseup
```
webview developer console message :
```
webview mousedown
webview mouseup
webview click
```

when i select Developer Tools "toggle device toolbar" and click 2 area
index.html developer console message :
```
touchstart
touchend
```
webview developer console message :
```
webview touchstart
webview touchend
```

why webview touch event can not handled index.html body?

so i tried test another electron version and i found something.
v0.36.12 and before version of electron can handle touch event.
index.html developer console message :
```
touchstart
touchend
```
webview developer console message :
```
webview touchstart
webview touchend
webview mousedown
webview mouseup
webview click
```

i want handle webview touch event in index.html body. how can i do?

my test code repo : https://github.com/smilejp/electron-webview-event-test

**Comment by zcbenz** [comment] 2016-07-25 01:07
Can you try whether the same bug occurs in the webview of Chrome app? You can try by modifying this app:
https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/webview-samples/browser

**Comment by smilejp** [comment] 2016-07-26 02:27
i tried same test in webview of Chrome App.
sadly, same bug occurs that test.

so i make gif screenshot( total 6 frames)
1-2 frames touch down & up in webview area
3-4 frames touch down & up in out of webview area
5-6 frames mouse down & up in webview area

my test code here : https://github.com/smilejp/electron-webview-event-test/tree/master/chrome_app_test_based_official_sample

![chrome_app_sample_test](https://cloud.githubusercontent.com/assets/3704914/17123979/c4835f5a-5322-11e6-98a2-dce2cbcd1e59.gif)

**Comment by zcbenz** [comment] 2016-07-26 07:16
Thanks for testing, can you report this bug to [Chromium's issues list](https://crbug.com) instead? Electron is using Chromium for the webview code so it is an upstream bug. I'm closing this since we are not able to fix it on Electron's side.

**Closed by zcbenz** 2016-07-26 07:16 UTC
Labels: more-information-needed

**Comment by nbergseng** [comment] 2016-09-13 22:05
for anyone who finds this: https://bugs.chromium.org/p/chromium/issues/detail?id=631484&q=webview&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

regression bug in Chromium :(
