### ISSUE TITLE
dialog.showMessageBox ignores defaultId property

### ISSUE THREAD

**Issue by arielspalter** [electron/electron#23932] opened 2020-06-03 04:08 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
6.9.0
* **Operating System:**
Windows 10
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

The defaultId property in the Options object in dialog.showMessageBox should change the default button.

### Actual Behavior

The defaultId property in the Options object in dialog.showMessageBox isn't changing the default button. The rest of the properties work just fine

### To Reproduce
`                    dialog.showMessageBox(mainWindow, {
                    type: 'warning',
                    buttons: ['Yes', 'No', 'Cancel'],
                    defaultId: 2,
                    cancelId: 2,
                    detail: "...you want to continue?",
                    message:"You are about to delete the current calendar!"
                  })`

### Screenshots

<img width="418" alt="Capture" src="https://user-images.githubusercontent.com/30180567/83594887-616f8a80-a52e-11ea-8ef4-292a6efe6628.PNG">

**Comment by glen-84** [comment] 2020-06-04 15:35
Duplicate of #22600.

**Closed** 2020-06-04 21:10 UTC
Labels: bug :beetle:, platform/windows
