### ISSUE TITLE
iframe window.open broken

### ISSUE THREAD

**Issue by majames** [electron/electron#9581] opened 2017-05-24 23:53 UTC
* Electron version: 1.6.8
* Operating system: MacOS

Apologies if this is a duplicate, I found issues related to `window.open`, however I believe none covered my use case

### Expected behavior

Communication between an iframe and windows it opens should be possible (via `postMessage` API). Therefore, `window.open` should behave correctly when used within an iframe.

#### Opener to opened

Calling `window.open` from within an iframe should return the created `BrowserProxyWindow`, allowing the **opener** to post messages to the **opened**

#### Opened to opener

The opened windows `window.opener` should point back to the iframes window (the window that opened it), allowing the **opened** to post messages to the **opener**

### Actual behavior

Communication between the opener and the opened window is broken in both directions when the 
opener is an iframe.

#### Opener to opened

`window.open` returns `null` when called within an iframe. Therefore,  it is impossible for the opener to communicate to the opened window. 

`window.open` uses Chromiums implementation instead of Electron's proxy from within an iframe.

#### Opened to opener

`window.opener` points to `top` instead of the iframe which opened the window. Therefore, it is impossible to communicate from the opened window to the opener window (the iframe).

### How to reproduce

The easiest way to reproduce is to:

1. open up the example electron app
2. open dev tools and insert an iframe
3. from dev tools console set the context to the iframe, and execute `window.open` (it will return `null`)
4. open the dev tools in the opened window and inspect `window.opener`... it will NOT point to the opener (the iframe) instead it will be pointing at `top`

**Comment by ddxdental** [comment] 2017-07-18 16:05
Are there any notable work arounds for this issue currently?

**Comment by groundwater** [comment] 2017-08-07 16:02
Gonna re-open because we have to revert this fix #10204

**Comment by alexstrat** [comment] 2018-01-17 22:38
@MarshallOfSound so that the investigation you made to get to #9961 are not lost, would you mind writing them down in this issue please? Others could continue from there.

_(I could not find a summary of your investigations, but I may have missed it 😉)_

**Comment by codebytere** [comment] 2018-09-24 04:55
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by Anrock** [comment] 2018-09-24 09:41
@codebytere just reproduced on 1.8.8, 2.0.10, 3.0.0. Please reopen and add corresponding version tags.

**Comment by Anrock** [comment] 2018-10-04 13:16
Seems the same happens if using BrowserView instead of iframe.

**Comment by Gozala** [comment] 2018-10-17 20:47
I have identified source of the issues and proposed solution based on the exploration described in the the [corresponding comment](https://github.com/electron/electron/issues/15040#issuecomment-428458325). Posting this here given that that issue is closed & I don't seem to get any response.

**Comment by sofianguy** [comment] 2019-08-09 03:53
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:04
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:04 UTC
Labels: 2-0-x, 3-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS, version/1.8.x
