### ISSUE TITLE
Mac App Store builds don't respond to CMD+~ correctly

### ISSUE THREAD

**Issue by cruzerld** [electron/electron#18672] opened 2019-06-06 16:46 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
4.1.4
* **Operating System:**
macOS 10.14.3
* **Last Known Working Electron version:**
unsure

### Expected Behavior
Cmd+~ is supposed to toggle between open windows of the current application. This works for applications build for Mac directly (dmg) but not for MAS pkgs.

### Actual Behavior
When using CMD+~ on a MAS build the application does nothing.

### To Reproduce
Install an Electron-based application from the app store (Trello would work), log in, use SHIFT+CMD+N to open a second window, and then use CMD+~ to try to toggle between the two windows. I verified that this occurs for multiple applications before opening this bug.

### Additional Information
The same code built as a .dmg works. I used electron-forge to build my application. I don't know the last time this was working because I jumped from Electron 1 to 4.

**Comment by zubin** [comment] 2019-06-14 21:58
Possibly related: https://github.com/atom/atom/issues/10852

**Comment by cruzerld** [comment] 2019-06-21 16:46
I've also verified that CMD+F4 (which switches between all open windows on the Mac desktop) isn't working. I suspect this is related.

**Comment by NReilingh** [comment] 2019-10-22 17:46
The keyboard shortcut in question is actually cmd+`, not cmd+~ (on EN-US keyboards these are on the same key, but shift is not required for the combo).

**Comment by zubin** [comment] 2019-10-22 19:19
> The keyboard shortcut in question is actually cmd+`, not cmd+~ (on EN-US keyboards these are on the same key, but shift is not required for the combo).

`cmd+~` can be used to reverse cycle (ie if you have multiple windows open and skip past the one you want, you can go back with `cmd+~`).

**Comment by NReilingh** [comment] 2019-10-22 19:36
Oh, of course! Hah, I forgot about that. But the issue affects both, does it not?

**Comment by zubin** [comment] 2019-10-22 20:26
> Oh, of course! Hah, I forgot about that. But the issue affects both, does it not?

Yep, sure does. :)

**Comment by julienma** [comment] 2019-11-06 13:56
Because I use an AZERTY keyboard, the standard shortcut to switch between windows of the same app is hard to trigger.

So I changed it to ⌥+⇥ (ALT+TAB). And with this shortcut I can successfully switch between Trello windows.

Note: macOS 10.15.1

**Comment by electron-triage** [comment] 2020-02-19 20:39
@cruzerld is this still an issue in electron 6.x.y or later?

**Comment by electron-triage** [comment] 2020-02-26 20:25
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:25 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/macOS

**Comment by zubin** [comment] 2020-02-26 21:28
> Thank you for your issue!
> 
> We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

Which question was awaiting a response? The only one I see was replied to. 😕 

This is still an issue (it's especially annoying on a Slack call, where there's no way to toggle between the main and call windows with the keyboard; the only way is to click into the Window menu).

**Comment by theconsultant** [comment] 2020-11-18 15:05
I'm still seeing this issue in the latest Slack (4.03) from MAS. How do I find out which version of Electron the app was built with?

**Comment by nornagon** [comment] 2020-11-18 20:34
@theconsultant it looks to me like the latest version of Slack on the MAS is 4.10.3, which uses Electron 10.1.2. The version number you posted doesn't seem to match any released version of Slack, can you clarify which version you're seeing the issue in?

**Comment by theconsultant** [comment] 2020-11-18 20:46
My bad, I forgot that i'm way behind as I am still on Mojave / 10.14.6. The version I have is "Version 4.0.3 (App Store)".
How do I know which version of Electron my install of Slack runs?

**Comment by nornagon** [comment] 2020-11-18 22:11
you can run with `--remote-debugging-port=9229`, go to `about:inspect` and run `process.versions.electron`. But 4.0.3 is ancient, and runs on a version of Electron that is no longer supported (4.2.8).

**Comment by theconsultant** [comment] 2020-11-18 22:17
Thank you! I will check it out.. and ignore the issue until I can run a current version. Much appreciated!

**Comment by zubin** [comment] 2020-11-18 23:07
I'm using Big Sur and am seeing the issue in Trello v2.11.7. 

I can't check Slack right now because it requires making a call (can't think of another way to create another window).

**Comment by nornagon** [comment] 2020-11-18 23:29
@zubin if you create a Post, that will open a new window. (I believe you can do this by clicking the lightning icon to the left of the message field and searching for 'post'.)

Also, what version of Slack are you using?

**Comment by zubin** [comment] 2020-11-19 03:20
> @zubin if you create a Post, that will open a new window. (I believe you can do this by clicking the lightning icon to the left of the message field and searching for 'post'.)
> 
> Also, what version of Slack are you using?

Thanks, I was looking for "Create a post" forgot where it was.

Confirmed: cycling windows does not work with "Create a post" window. 

Am on latest version:

> Version 4.10.3
> 673039f-s@1605650770 (App Store)

Interestingly, I noticed that cmd-~ worked only once with the "About Slack" dialog (ie it went to the background). Pressing it again had no effect.

**Comment by NReilingh** [comment] 2020-12-02 16:54
@electron-triage I think I can confirm that this issue is present on at least Electron 8. Using Trello 2.11.7 (which is only available from the MAS), I ran the executable in terminal and got a warning message:

```
/Applications/Trello.app/Contents/MacOS/Trello --remote-debugging-port=9229
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

I couldn't figure out how to connect Chrome's debugger to the port, but given that the warning message refers to Electron 9 as the next version, I believe we can safely say it is using a version of Electron 8.
