### ISSUE TITLE
[Bug]: in window plateform，the blur event not emit。i create a window,when it show i use focus function and it get the focus,but when i click outside the blur event not emit. this  bug not appear in my computer

### ISSUE THREAD

**Issue by zhanghhuc** [electron/electron#28880] opened 2021-04-28 02:07 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.1

### What operating system are you using?

Windows

### Operating System Version

window 10

### What arch are you using?

x64

### Last Known Working Electron version

3.1.1

### Expected Behavior

blur event emitted

### Actual Behavior

blur event not being emitted

**Comment by mlaurencin** [comment] 2021-04-28 20:19
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you’re still experiencing this issue in Electron 10.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2021-07-07 21:30
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2021-07-07 21:30 UTC
Labels: blocked/need-info ❌, bug :beetle:

**Comment by FushimiYuki** [comment] 2024-02-05 10:41
Hi, I have the same question. I'm using electron 28.0.0

**Comment by mlaurencin** [comment] 2024-02-05 16:51
@FushimiYuki You can ask questions at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try. 

And since this issue was closed a while ago, it is not actively being tracked. If you determine that this is an issue beyond your code, please check the issue tracker to see if an active issue matches yours, and if not, feel free to make a new issue with a test case.

I hope this helps!
