### ISSUE TITLE
electron App doesn't work at startup windows

### ISSUE THREAD

**Issue by loreberti89** [electron/electron#8719] opened 2017-02-20 10:12 UTC
I have developed a small desktop app with electron. 
I have put the link of .exe file in startup windows folder , because my app should start at start of windows. My problem is that when windows starts, the app starts but it remains with white screen with no log console, no error, nothing, only white screen, so I can't debug or know Why app not work, but if I disconnected my user in windows and reconnect, the app works, like at the moment that app started hasn't something for complete start.

**Comment by MarshallOfSound** [comment] 2017-02-20 10:14
@loreberti89 Sounds like at startup your computer hasn't connected to the internet yet, and your app simply failed to load a page.  Does that sound possible?

**Comment by loreberti89** [comment] 2017-02-20 10:19
@MarshallOfSound thankyou, I thought about it, but I tried to unplug the ethernet cable and restart the app, but i start and return error connection, if it was a connection problem, It should behave in the usual way if I unplug the cable

**Comment by groundwater** [comment] 2017-02-20 19:27
Hi @loreberti89, thanks for your report.

Unfortunately it will be tough to track down the error if we cannot reproduce it. Are you able to share your application, and steps to reproduce the error?

**Comment by loreberti89** [comment] 2017-02-21 08:38
Hello @groundwater  thankyou, I will try to write a snippet for understand.

In **main.js**  I have  these require
```
const electron = require('electron');
const {Menu, Tray} = require('electron');
const appExpress = require('express')();
const Redis = require('ioredis');
const path = require('path');
const url = require('url');
const http = require('http').Server(appExpress);
const https = require('https');
const io = require('socket.io')(http);
```

Maybe are too many? I don't know but the problem is when I try to do a async Call in main.js because if I comment the async call the app start correctly. My async call is like this:

```
https.get(global.globalConfig.baseUrl + "getListenPassword?key_access="+settings.get("key_access"), function(res) {
    res.on('data', function (body) {
      global.globalConfig.redis =  JSON.parse(body).data;
      const redis = new Redis({
        port: 443,
        host: 'mySite.it',
        protocol: "https",
        password: global.globalConfig.redis
      })
      redis.on('pmessage', function(subscribed, channel, message) {
        message = JSON.parse(message);
        notifier.notify({
          'title': 'change state',
          'message': 'The data with rif.'+message.data.data.id+' is changed',
          sound: true,
          icon: path.join(__dirname, '/images/icon.ico')
        });
        io.emit(channel + ':' + message.event, message.data);

      });
      redis.psubscribe(personal_event, function(err, count) {
      });

    });

  }).on('error', function(e) {
    console.log("Got error: " + e.message);
  });
```

**Comment by MarshallOfSound** [comment] 2017-02-21 09:46
Hmm, I keep coming back to it being something to do with the network not being initialized during bootup.  Can you try commenting subsections out to isolate the exact call that causes the crash.  Or what might be easier is adding a script like this to your startup directory.

```bash
set ELECTRON_ENABLE_LOGGING=true
set ELECTRON_ENABLE_STACK_DUMPING=true
path\to\executable.exe
```

That should launch a CMD prompt on logic and execute those commands allowing you to see any errors that may be being thrown either by your code or internal Electron things 👍

**Comment by loreberti89** [comment] 2017-02-21 11:10
@MarshallOfSound  I have resolved! 
It's probably, as you say, a problem with connection initialize.
So I have used a IPC module for make a request in a moment when I am enough secure that the connection is established.
Thankyou for your help!

**Comment by groundwater** [comment] 2017-02-22 00:29
Sounds like this is solved. Going to close it.

**Closed by groundwater** 2017-02-22 00:29 UTC
Labels: more-information-needed, platform/windows, triage/bug
