### ISSUE TITLE
Using worker_threads that keep running indefinitely fails assertion on SIGTERM

### ISSUE THREAD

**Issue by KishanBagaria** [electron/electron#23315] opened 2020-04-28 13:27 UTC
### Issue Details

* **Electron Version:**
  * v9.0.0-beta.21 and 8.2.4
* **Operating System:**
  * macOS 10.15.4

### Actual Behavior

An electron app that uses a worker thread that runs indefinitely in the main process (because of a server listening on a port etc.) throws the following error on exit:

```
/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron[93383]: ../../third_party/electron_node/src/node_worker.cc:358:virtual node::worker::Worker::~Worker(): Assertion `stopped_' failed.
 1: 0x10f4ce9b5 node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x10f4ce73f node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x10f54eb01 node::MultiIsolatePlatform::CancelPendingDelayedTasks(v8::Isolate*) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x10f54eb3e node::MultiIsolatePlatform::CancelPendingDelayedTasks(v8::Isolate*) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x10f47f56f node::EmitAsyncDestroy(node::Environment*, node::async_context) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x10f44cc4e node::FreeEnvironment(node::Environment*) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x1095c4c81 ElectronInitializeICUandStartNode [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x10b0fac71 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x10b0fc514 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x10b0f8294 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x10afa1616 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x10afa126b v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x10d522488 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x10a2222b4 ElectronInitializeICUandStartNode [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x1094f8a54 ElectronMain [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
16: 0x108377110  [/Users/kishan/Downloads/electron-test/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron]
17: 0x7fff6cb41cc9 start [/usr/lib/system/libdyld.dylib]
```

### Expected Behavior
It shouldn't throw the error.

### To Reproduce
Couldn't repro this in Electron Fiddle but the following should work:

1. Copy the following to `worker-exit-issue.js`
```js
const { Worker, isMainThread } = require('worker_threads')

if (isMainThread) {
  new Worker(__filename)
  console.log('main thread')
} else {
  console.log('worker')
  const http = require('http')
  const server = http.createServer((req, res) => {
    res.end()
  })
  server.listen(12345)
}
```

2. Run `electron worker-exit-issue.js`

3. Quit the Electron app that runs from Dock or equivalent. (CTRL+C/SIGINT will not throw the error)

4. You'll see the above error printed in the console:
<img width="1102" alt="" src="https://user-images.githubusercontent.com/1093313/80492622-eb519400-8981-11ea-90a9-92f46aad6806.png">

This doesn't happen if I run `node worker-exit-issue.js`

**Comment by codebytere** [comment] 2020-04-28 18:02
@KishanBagaria There is some existing incompatibility with worker thread in Node.js at the moment that's existed for a while - we're looking into it but recommend you try to use Web Workers instead where possible :)

**Comment by KishanBagaria** [comment] 2020-04-28 18:09
I would but I need to use native modules. I also have to move my node-mac-contacts code to a worker thread from the renderer process since it's compute heavy :)

**Comment by flotwig** [comment] 2020-05-29 15:42
@KishanBagaria I believe I'm having the same issue: #23366

**Comment by KishanBagaria** [comment] 2020-07-26 20:29
Is there a way I can silence this by monkey patching or something?

**Comment by flotwig** [comment] 2020-07-27 13:47
@KishanBagaria we are working around it by monkey-patching `process.exit` to exit all `worker_threads` before calling `process.exit`. This is a dirty hack because (among other reasons) it makes `process.exit` an asynchronous operation, but I've not been able to find a better workaround :/

Initially, we were calling `.terminate()` on each `worker_thread` on `process.exit` and waiting for that to finish, but some users were still running into problems with `SIGABRT`. So we switched to using `postMessage` to tell each thread to kill itself, waiting for that, and *then* exiting the parent process. This seems to work fine in practice: https://github.com/cypress-io/cypress/pull/7572/files

Still, this is a bad workaround due to the reasons mentioned above. I hope someone from the Electron team can take an in-depth look at this issue.

**Comment by dpaola2** [comment] 2020-08-28 13:08
I'm this boat as well - while trying to refactor some blocking native logic out of the main thread for performance reasons, I'm now encountering an app crash every time I exit the app because I followed the advice in https://www.electronjs.org/docs/tutorial/performance and used Node.js workers.

From where I'm sitting, it looks to me like there is no way to have multithreaded native logic without encountering this error. Is that accurate?

**Comment by linonetwo** [comment] 2020-10-11 09:59
No way around, my code is waiting enough of time to prevent race condition:

```js
async function stopWorker(id) {
  const worker = wikiWorkers[id];
  if (!worker) {
    logger.warning(
      `No worker for ${id}. No running worker, means maybe worker failed to start`
    );
    return Promise.resolve();
  }
  return (
    new Promise(resolve => {
      worker.postMessage({ type: 'command', message: 'exit' });
      worker.once('exit', resolve);
      worker.once('error', resolve);
    })
      .timeout(100)
      .catch(error => {
        logger.info(`Wiki-worker have error ${error} when try to stop`); // this never happens
        return worker.terminate();
      })
      .then(() => {
        delete wikiWorkers[id]; // this is useless, but I tried
        logger.info(`Wiki-worker for ${id} stopped`);
      })
  );
}

  const tasks = [];
  for (const id of Object.keys(workers)) {
    tasks.push(stopWiki(id));
  }
  await Promise.all(tasks);
  await Promise.delay(5000);
```

And in worker

```js
if (!isMainThread) {
  startNodeJSWiki();
  parentPort.once('message', async message => {
    if (typeof message === 'object' && message.type === 'command' && message.message === 'exit') {
      process.exit(0);
    }
  });
}
```

and in electron

```js
  app.on('before-quit', async event => {
    logger.info('Quitting worker threads and watcher.');
    await Promise.all([stopAllWiki(), stopWatchAllWiki()]);
    logger.info('Worker threads and watchers all terminated.');
    logger.info('Quitting I18N server.');
    clearMainBindings(ipcMain);
    logger.info('Quitted I18N server.');

    // https://github.com/atom/electron/issues/444#issuecomment-76492576
    // if (process.platform === 'darwin') {
    //   const win = mainWindow.get();
    //   if (win) {
    //     logger.info('App force quit on MacOS');
    //     win.forceClose = true;
    //   }
    // }
    app.exit(0);
  });

  app.on('quit', async () => {
    logger.info('App quit');
  });
```

All of this are not working. Always

```
Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV
[1] wait-on http://localhost:3000 && electron . exited with code 1
--> Sending SIGTERM to other processes..
[0] cross-env BROWSER=none npm run start exited with code 1
```

**Comment by linonetwo** [comment] 2020-10-11 10:03
I tried @flotwig 's solution, seems it is not working.

**Comment by codebytere** [comment] 2020-10-13 01:06
This issue seems like it's present in Node.js v12 but not v14 - i can't repro it after https://github.com/electron/electron/pull/25249.

**Comment by linonetwo** [comment] 2020-10-13 03:19
@codebytere that is in electron v11 ? I will try that later

**Comment by regular** [comment] 2020-10-22 18:49
Tried with Electron 11.0.0-beta13. It crashes even when all threads terminate prior to calling app.quit(), like described in #26103 it's enough to have had a thread running at any point to make Electron crash on exit.

**Comment by codebytere** [comment] 2020-11-10 03:18
I'm fairly certain it's this commit: https://github.com/nodejs/node/pull/30467/commits/b6738bc62479391e5d93026716ed92d6879ea60e

that would need to be backported to `9-x-y` through `11-x-y`

**Comment by linonetwo** [comment] 2020-11-10 05:54
I can confirm this is fixed in v12 nightly, but v12 drop support for non-NAPI native addons, so I have to disable asar to use those native packages.
But, yes, v12 fixes this already.

**Comment by KishanBagaria** [comment] 2020-11-10 18:09
Would be great to have this backported! 🎉

**Comment by m4heshd** [comment] 2021-02-20 14:12
Having the same issue. Blocked from everywhere. Can't use web workers because of the need to use native modules and [it can't seem to load any kind of external module](https://github.com/electron/electron/issues/27802). Can't use worker threads because of this issue. So frustrated not being able to move forward.

**Comment by indutny-signal** [comment] 2021-03-31 01:22
A different stack trace for the same issue with a testing build of Electron:

```
  * frame #0: 0x0000000122464f80 Electron Framework`::AddIsolateFinishedCallback() [inlined] operator bool at memory:3851:68 [opt]
    frame #1: 0x0000000122464f74 Electron Framework`::AddIsolateFinishedCallback() at node_platform.cc:354 [opt]
    frame #2: 0x000000012222686e Electron Framework`::AddArrayBufferAllocatorToKeepAliveUntilIsolateDispose() at env.cc:1074:15 [opt]
    frame #3: 0x000000012255e5fb Electron Framework`::CleanupHook() at sharedarraybuffer_metadata.cc:75:18 [opt]
    frame #4: 0x00000001222193af Electron Framework`::RunCleanup() at env.cc:627:7 [opt]
    frame #5: 0x000000012212d20e Electron Framework`::FreeEnvironment() at environment.cc:335:8 [opt]
    frame #6: 0x0000000100717d88 Electron Framework`::PostMainMessageLoopRun() [inlined] operator() at memory:2378:5 [opt]
    frame #7: 0x0000000100717d80 Electron Framework`::PostMainMessageLoopRun() [inlined] reset at memory:2633 [opt]
    frame #8: 0x0000000100717d66 Electron Framework`::PostMainMessageLoopRun() at electron_browser_main_parts.cc:598 [opt]
    frame #9: 0x000000010b68dced Electron Framework`::ShutdownThreadsAndCleanUp() at browser_main_loop.cc:1057:13 [opt]
    frame #10: 0x000000010b693ea4 Electron Framework`::Shutdown() at browser_main_runner_impl.cc:178:17 [opt]
    frame #11: 0x000000010b684796 Electron Framework`::BrowserMain() at browser_main.cc:49:16 [opt]
    frame #12: 0x000000010b059d75 Electron Framework`::RunServiceManager() [inlined] RunBrowserProcessMain at content_main_runner_impl.cc:507:10 [opt]
    frame #13: 0x000000010b059cb4 Electron Framework`::RunServiceManager() at content_main_runner_impl.cc:979 [opt]
    frame #14: 0x000000010b058f28 Electron Framework`::Run() at content_main_runner_impl.cc:858:12 [opt]
    frame #15: 0x0000000105e07384 Electron Framework`::RunContentProcess() at content_main.cc:373:36 [opt]
    frame #16: 0x0000000105e07a78 Electron Framework`::ContentMain() at content_main.cc:399:10 [opt]
    frame #17: 0x00000001003ca00d Electron Framework`ElectronMain at electron_library_main.mm:23:10 [opt]
    frame #18: 0x0000000100004acd Electron`main at electron_main.cc:274:10 [opt]
    frame #19: 0x00007fff2057c621 libdyld.dylib`start + 1
```

**Comment by linonetwo** [comment] 2021-03-31 03:02
@indutny-signal I think upgrade to v12 beta solves this.

**Comment by m4heshd** [comment] 2021-03-31 18:17
@linonetwo Why beta? The stable version was released a long time ago. And yeah it's fixed because of Node ABI v83.

**Comment by indutny-signal** [comment] 2021-03-31 18:20
It still isn't fixed in the latest v11 release which was published a week ago.

**Comment by m4heshd** [comment] 2021-03-31 18:51
@indutny-signal You're never gonna get a fix on v11 because it's using older Node ABI (v72). That will never change.

**Comment by indutny** [comment] 2021-03-31 20:34
@m4heshd of course it can be fixed.  Just need to fix node v12 first :joy: (See: https://github.com/nodejs/node/pull/38010)

**Comment by m4heshd** [comment] 2021-03-31 21:17
@indutny big props. Now I'm glad I added that last part on my comment 😂. Wasted countless amounts of hours because of this. Hope It'll get merged soon. But still, not sure about the Electron side of it. Unless you integrate that too.

**Comment by indutny-signal** [comment] 2021-03-31 21:19
@m4heshd I don't anticipate any problems with the electron release, since it'd be just a version bump for node that they use. That being said only time will show if I was right!

**Comment by m4heshd** [comment] 2021-03-31 21:26
@indutny Agreed. Well, hoping for the best. 🤞🏼 _(Still wondering why devs on Electron guaranteed that It's unfixable though 🥴)_

**Comment by indutny** [comment] 2021-03-31 21:47
Correction, the proper fix actually needs to be done in electron: https://github.com/electron/electron/pull/28468 Thanks @addaleax for helping me with this!

**Comment by indutny-signal** [comment] 2021-04-06 23:13
@m4heshd does this release fix the problem for you?

**Comment by m4heshd** [comment] 2021-04-07 07:41
> @m4heshd does this release fix the problem for you?

Well you've apparently done the impossible. 😁 But I migrated all of my projects to v12 as soon as I discovered this issue. Still, thank you because It's gonna benefit a lot of devs. _slowclaps 👏🏽_

**Comment by nornagon** [comment] 2021-04-09 22:56
Sounds like this is fixed, so I'll close the issue. Let me know if I'm mistaken and I can reopen.

**Closed by nornagon** 2021-04-09 22:56 UTC
Labels: 10-x-y, 11-x-y, 8-x-y, 9-x-y, component/node-integration, crash :boom:, platform/all
