### ISSUE TITLE
Don't work autoUpdate with proxy basic auth

### ISSUE THREAD

**Issue by vadim-ch** [electron/electron#8194] opened 2016-12-13 13:02 UTC
Don't work autoUpdate with proxy basic auth! Please, help me. I'm desperate.
Error in logs: System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.

How can I set credentials proxy basic auth???

**Comment by kevinsawicki** [comment] 2016-12-13 17:11
This is a duplicate of https://github.com/electron/electron/issues/5020, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2016-12-13 17:11 UTC
