### ISSUE TITLE
Electron 1.8.2 Crashes when gulp is required.

### ISSUE THREAD

**Issue by mk010101** [electron/electron#12022] opened 2018-02-23 10:42 UTC
* Electron version: 1.8.2
* Operating system: OSX, Windows

Issue: Whenever `gulp = require("gulp");` is invoked, Electron 1.8.2 application crashes with "DevTools was disconnected from the page" message. 

Everything works fine with Electron 1.7.11.

**Comment by james-criscuolo** [comment] 2018-02-26 22:22
I'm seeing this behavior (devtools disconnected) and not using gulp. In my case, the log in screen of my app loads fine. Upon logging in everything seems to spin up, then just as the app looks ready, the screen goes white (this is an angular application).

I'm putting this in this ticket because this is the only recent issue regarding devtools disconnecting. This app had been working on 1.7.11 as well.

**Comment by james-criscuolo** [comment] 2018-03-06 13:31
Small version updates here, tested 1.8.3 and the same behavior held. I also wanted to mention its latest 1.7.x, 1.7.12, that is working for me. I tested on the latest version 2 beta (v2.0.0-beta.2), and it was the same behavior as 1.8.x.

**Comment by barisozanguler** [comment] 2018-04-05 15:12
Not gulp but I had same issue "DevTools was disconnected from the page" in 1.8.4 and its work 1.7.13. I solved this with deleting "**unzip2**" npm requirements. Somehow this npm causes in my case.

**Comment by james-criscuolo** [comment] 2018-04-09 15:10
I believe this is a duplicate of https://github.com/electron/electron/issues/10905#issuecomment-379379239, so I'm going to continue discussion there.

**Comment by sofianguy** [comment] 2019-01-07 21:50
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:41
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-01-15 20:41 UTC
Labels: blocked/need-info, bug :beetle:, platform/macOS, platform/windows, version/1.8.x
