### ISSUE TITLE
Webview tag with Visibility hidden does not work on MacOS

### ISSUE THREAD

**Issue by jjprestes** [electron/electron#8826] opened 2017-03-03 15:23 UTC
* Electron version: 1.6.1
* Operating system: MacOS

### Expected behavior
Show the page loaded by the webview;

### Actual behavior
the webview must reload the page to show its contents.

### How to reproduce
Setting CSS property visibility as hidden and then set visibility as visible on 'did stop loading' event does not show the webpage content. Just a blank page, although is possible to inspect the webview host contents. I'm setting this property adding and removing a class name in my webview tag. That was working on 1.4.15. Now it only does not work on Mac Os.

Inspecting the webview I can see that the class was added and the property visibility is set as 'visible'.

.webBrowser {
    position: relative;
    width: 100%;
    height: 100%;
    overflow: hidden;
    visibility: hidden;
    display: inline-flex;
    z-index: 1001;
    min-width: 450px;
    min-height: 420px;
    user-select: auto;
}
.webBrowser.loaded
{
    visibility: visible;
}

**Comment by kevinsawicki** [comment] 2017-03-03 19:03
I believe this is a duplicate of #8505, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2017-03-03 19:03 UTC
