### ISSUE TITLE
[Bug]: The frameless window is not resizable

### ISSUE THREAD

**Issue by FlysoftBeta** [electron/electron#33458] opened 2022-03-27 04:41 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0-beta.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2

### What arch are you using?

x64

### Expected Behavior

Frameless window is not resizable ,except the lower right corner.

### Actual Behavior

All the corners should be resizable.

### Testcase Gist URL

https://gist.github.com/2e63311259109218284b1f6648cc036d

**Comment by SquitchYT** [comment] 2022-03-27 16:11
I have the same issue, except that sometime, I can resize the window with one of it side

**Comment by Leshu7w7** [comment] 2022-03-27 16:13
same for me but I have 17.2.0 version and I can't resize window except sometimes, last version it worked was in 17.1.2

**Comment by codebytere** [comment] 2022-03-28 13:23
Duplicate of https://github.com/electron/electron/issues/33443

**Closed by codebytere** 2022-03-28 13:23 UTC
Labels: bug :beetle:
