### ISSUE TITLE
Simple WebView local storage is not accessible 

### ISSUE THREAD

**Issue by brunomilhan** [electron/electron#9569] opened 2017-05-23 22:21 UTC
Hellow guys, i can't  access local storage of my webview. 
In dev console, the localstorage is empty, but when i open in chrome the localstorage is work. :/

Thanks!
app.js
```
 mainWindow = new BrowserWindow({width: 1615, height: 1020, frame: true, resizable: true})
  
  // and load the index.html of the app.
  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))
```

index.html
```
<webview id="wv_simplifica" src="http://mysite.com.br" style="position:absolute;width:100%;height:100%;" autosize="on"
        localStorage="true" partition="persist:simplifica">
```

**Comment by smachs** [comment] 2017-06-09 17:16
hey try this!

Change it:
` mainWindow = new BrowserWindow({width: 1615, height: 1020, frame: true, resizable: true})
  
  // and load the index.html of the app.
  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))`

for this:
`app.on('ready', function() {
  mainWindow = new BrowserWindow({
    width: 1615,
    height: 1020,
    frame: true,
    resizable: true
  });

  mainWindow.loadUrl('file://' + __dirname + '/index.html');

  if(process.env.ENVIRONMENT === 'DEV') {

    mainWindow.openDevTools();
  }

  mainWindow.on('closed', function() {
    mainWindow = null;
  });
});`

**Comment by deepak1556** [comment] 2017-06-22 16:25
@brunomilhan there is no `localStorage` attribute for webview in Electron. It is available by default, are you by chance checking the dev console of parent page ? Can you provide a minimal example to reproduce the issue, thanks!

**Comment by codebytere** [comment] 2017-09-27 01:21
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:21 UTC
Labels: more-information-needed, waiting/needs-repro
