### ISSUE TITLE
[Bug]: BrowserWindows are printing stack traces for no reason

### ISSUE THREAD

**Issue by mattlucock** [electron/electron#37101] opened 2023-02-01 20:00 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.2.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.2

### What arch are you using?

x64

### Last Known Working Electron version

I also observe this in 21.4.1, 20.3.11, and 19.1.9.

### Expected Behavior

Opening and interacting with `BrowserWindow`s does not print random stack traces to `stdout`.

### Actual Behavior

Every time I open a `BrowserWindow`, one (or sometimes two?) stack traces are printed to `stdout`. Additional stack traces are printed every time I blur or focus the window.

I say "stack traces", but I don't exactly know what they are; they appear to be stack traces. This is one I got from opening a window (they all look like this):

```
1   HIToolbox                           0x00007ff81528d726 _ZN15MenuBarInstance22EnsureAutoShowObserverEv + 102
2   HIToolbox                           0x00007ff81528d2b8 _ZN15MenuBarInstance14EnableAutoShowEv + 52
3   HIToolbox                           0x00007ff815231908 SetMenuBarObscured + 408
4   HIToolbox                           0x00007ff8152314ca _ZN13HIApplication15HandleActivatedEP14OpaqueEventRefhP15OpaqueWindowPtrh + 164
5   HIToolbox                           0x00007ff81522b996 _ZN13HIApplication13EventObserverEjP14OpaqueEventRefPv + 252
6   HIToolbox                           0x00007ff8151f3bd2 _NotifyEventLoopObservers + 153
7   HIToolbox                           0x00007ff81522b3e6 AcquireEventFromQueue + 494
8   HIToolbox                           0x00007ff81521a5a4 ReceiveNextEventCommon + 725
9   HIToolbox                           0x00007ff81521a2b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
10  AppKit                              0x00007ff80ea1d293 _DPSNextEvent + 909
11  AppKit                              0x00007ff80ea1c114 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
12  AppKit                              0x00007ff80ea0e757 -[NSApplication run] + 586
13  Electron Framework                  0x000000011c78aac6 _ZNK4node13AsyncResource12get_async_idEv + 9762534
14  Electron Framework                  0x000000011c78860a _ZNK4node13AsyncResource12get_async_idEv + 9753130
15  Electron Framework                  0x000000011c74abca _ZNK4node13AsyncResource12get_async_idEv + 9500650
16  Electron Framework                  0x000000011c70d2d1 _ZNK4node13AsyncResource12get_async_idEv + 9248497
17  Electron Framework                  0x000000011b825460 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 4799664
18  Electron Framework                  0x000000011b826f42 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 4806546
19  Electron Framework                  0x000000011b822d03 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 4789587
20  Electron Framework                  0x00000001195f9a64 _ZN2v88internal8compiler10BasicBlock15set_loop_headerEPS2_ + 17044
21  Electron Framework                  0x00000001195faa78 _ZN2v88internal8compiler10BasicBlock15set_loop_headerEPS2_ + 21160
22  Electron Framework                  0x00000001195fa855 _ZN2v88internal8compiler10BasicBlock15set_loop_headerEPS2_ + 20613
23  Electron Framework                  0x00000001195f8d74 _ZN2v88internal8compiler10BasicBlock15set_loop_headerEPS2_ + 13732
24  Electron Framework                  0x00000001195f93d7 _ZN2v88internal8compiler10BasicBlock15set_loop_headerEPS2_ + 15367
25  Electron Framework                  0x00000001192db9bb ElectronMain + 155
26  dyld                                0x00007ff80b4c0310 start + 2432
```

### Additional Information

Needless to say, I'm a bit perplexed by this. I was concerned I had caused this by somehow misconfiguring Electron through an environment variable or otherwise (even though I was pretty certain I hadn't), but having attempted to research this, I haven't been able to determine a way I could configure Electron to do this even if I wanted it to.

I've chosen not to provide a reproduction simply because literally any Electron app reproduces this. The default app presented upon launching Fiddle reproduces this without modification.

**Comment by dsanders11** [comment] 2023-02-02 02:59
Thanks for the report! Closing this as it's a duplicate of an earlier report.

Duplicate of #36891.

**Closed by dsanders11** 2023-02-02 02:59 UTC
Labels: bug :beetle:
