### ISSUE TITLE
Mac OS CPU issues? Seems to affect multiple apps.

### ISSUE THREAD

**Issue by BuckAMayzing** [electron/electron#26467] opened 2020-11-12 16:13 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

I'm not exactly sure how to characterize this. I've submitted [this issue](https://github.com/microsoft/vscode/issues/110323) to VSCode's repo, but there are [hints](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/36387562-mac-teams-helper-takes-up-too-much-cpu-and-makes) that this could be happening [elsewhere](https://old.reddit.com/r/Atom/comments/emy79x/high_cpu_usage_of_atom_helper/). There does seem to be a pretty compelling trend of MacOS "{Electron App} Helper" threads using a lot of CPU. I have no idea if it's Chromium or Electron itself, but I thought I'd start here.

I'm not sure how to go about confirming what's causing this CPU usage. Profiling in developer tools doesn't show the CPU being used to the extreme that the OS is reporting.

* **Electron Version:**
  * Likely Multiple. Code is using 9.3.3. Teams and Slack aren't open source, so I'm not sure.
* **Operating System:**
  * Mac OS 10.15.7 (for me)
* **Last Known Working Electron version:**
  * Unsure. I can find similar reports going back to 2017, but they could be different underlying causes.

### Expected Behavior
CPU usage that isn't in the double/triple digit percentages for idling apps.

### Actual Behavior
Regular spikes of 300% or more when idling in Code. Regular spikes of 50% or more when idling in Slack. Reports of similar issues in MS Teams and Atom.

### To Reproduce
This is the big question. I haven't come up with a specific set of circumstances in which this can happen, but I'm willing to work with someone to diagnose the problem. For most of my team, this happens on a daily basis when using VS Code on Mac. Slack also reliably idles with high CPU usage on Mac for me.

### Additional Information
I know this one is pretty vague, but I'm not sure how to report this in a clearer/more concise way since I've never written an electron app. Again, I don't mind to work with someone to get a memory dump/trace, but I'm not sure where to start.

**Comment by nornagon** [comment] 2020-11-13 19:41
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by BuckAMayzing** [comment] 2020-11-18 15:01
@nornagon - this is happening with regular usage of many apps. It seems that the repro steps would be to run electron in MacOS. It seems like a fundamental issue - if it's happening across most apps, I'm not sure how you narrow that down to a specific set of steps. That's why I'm here looking for guidance.

**Comment by nornagon** [comment] 2020-11-18 20:37
I can't reproduce this on macOS 10.15.7 using Electron Fiddle. CPU is flat at 0% for all Fiddle-related processes:

![Activity_Monitor__My_Processes_](https://user-images.githubusercontent.com/172800/99585007-9bc4cb00-299a-11eb-879b-48a0320b9a0d.png)

it rises to ~1% when the window is focused and the cursor is blinking, but if the cursor isn't blinking (i.e. no input is focused), falls back to 0%.

**Comment by sofianguy** [comment] 2021-01-05 21:43
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2021-01-05 21:43 UTC
Labels: blocked/need-repro

**Comment by mikeyyyzhao** [comment] 2021-01-06 07:00
Similar to @BuckAMayzing , we've also heard feedback from users about cpu issues on big sur. Unfortunately, I'm also having a difficult time reproducing it but just wanted to note that @BuckAMayzing isn't alone in hearing about cpu issues

**Comment by pcullum** [comment] 2021-05-20 17:01
https://github.com/signalapp/Signal-Desktop/issues/3542

**Comment by boblannon** [comment] 2021-06-11 19:35
I can attest to experiencing this on macOS Big Sur 11.1 

I've had this problem in both the Authy and Signal Desktop apps. In both apps, the problem recently disappeared and then re-appeared at around the same time. I know it's not conclusive evidence, but I think it suggests that this is an Electron issue (Authy is also an Electron app, afaik).

- Electron Version:
  - Signal Desktop v5.4.1 [is using 12.0.7](https://github.com/signalapp/Signal-Desktop/blob/v5.4.1/package.json#L242)
  - Authy isn't open source, so I'm not sure.
- Operating System:
  - Mac OS Big Sur, 11.1 (20C69) 
- Last Known Working Electron version:
  - My best guess is 12.0.6, which is the version used in Signal's v5.1.0
