### ISSUE TITLE
Setting titleBarStyle causes a warning

### ISSUE THREAD

**Issue by axelkennedal** [electron/electron#14925] opened 2018-10-02 10:12 UTC
* Output of `node_modules/.bin/electron --version`: v3.0.2
* Operating System (Platform and Version): macOS Mojave 10.14
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): -

**Expected Behavior**
The title bar of the main window to display in the expected style, without errors.

**Actual behavior**
The title bar is displayed in the right style, but there is this warning;
`2018-10-02 12:06:59.730 Electron[34332:825632] *** WARNING: Textured window <AtomNSWindow: 0x7fa08cd74cb0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.`

**To Reproduce**
Set `titleBarStyle: "hiddenInset"` on the mainWindow of the Electron app and run.

**Additional Information**

**Comment by pronebird** [comment] 2018-10-03 09:57
This warning has been there since forever. Perhaps electron needs to properly configure the `NSWindow`

**Comment by codebytere** [comment] 2018-10-05 23:12
Interestingly, we _do_ use `titlebarAppearsTransparent` in almost all conceivable places 🤔 some digging is in order, it seems!

**Comment by pronebird** [comment] 2018-10-05 23:36
@codebytere perhaps macOS is upset because of use of `NSWindowStyleMaskTexturedBackground`

https://github.com/electron/electron/blob/79c6e7c3f79f8919b2e9fd65f35c15a0470d3550/atom/browser/native_window_mac.mm#L342

**Comment by sofianguy** [comment] 2019-08-09 22:51
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:15
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:15 UTC
Labels: 3-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS
