### ISSUE TITLE
`systemPreferences.isDarkMode()` is broken in Electron 6.0.0-beta.11

### ISSUE THREAD

**Issue by caesar** [electron/electron#19021] opened 2019-06-28 00:11 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta.11
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 6.0.0-beta.10

### Expected Behavior
`systemPreferences.isDarkMode()` should return `true` when the system is in dark mode.

### Actual Behavior
`systemPreferences.isDarkMode()` always returns `false`.

### To Reproduce
- Open Electron
- Open Developer Tools Console
- Execute the following commands:
    - `const electron = require('electron');`
    - `electron.remote.systemPreferences.isDarkMode();`
- Observe that the return value is `false` even if the system is in Dark Mode.

### Screenshots
<img width="872" alt="Screenshot 2019-06-28 at 01 10 04" src="https://user-images.githubusercontent.com/1566516/60308594-7f596600-9941-11e9-8b4c-5cb59df9bd0b.png">

### Additional Information
I believe this bug was probably introduced in #18958.

**Comment by MarshallOfSound** [comment] 2019-06-28 00:20
Thanks for the report -->

Duplicate of #19009

Will be fixed by #19013

**Closed by MarshallOfSound** 2019-06-28 00:20 UTC

**Comment by caesar** [comment] 2019-06-28 00:33
Oh sorry, I thought that was only on Catalina from the title.

Good to hear a fix is in the works. 👍

**Comment by RoderickQiu** [comment] 2019-06-29 00:14
@MarshallOfSound Same problem for 5.0.6.
So maybe this update should no longer be on the stable channel, or you guys should send a notification.

**Comment by MarshallOfSound** [comment] 2019-06-29 01:11
@RoderickQiu As mentioned above this issue was closed as a duplicate and has a PR up to fix it, the next release of `5-0-x` will fix this issue 👍
