### ISSUE TITLE
Can't disable menu item with a `role`

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#5860] opened 2016-06-03 22:03 UTC
Run the below and notice that the `Select All` menu item is enabled even though `enabled: false` is specified. Remove `role: 'selectall'` and it's correctly disabled. The `enabled` option should override the `role`. I need this so I can enable some role based menu items only in some cases.

```js
const electron = require('electron');

electron.app.on('ready', () => {
	electron.Menu.setApplicationMenu(electron.Menu.buildFromTemplate([{
		submenu: [{
			label: 'Select All',
			role: 'selectall',
			enabled: false
		}]
	}]));

	(new electron.BrowserWindow())
		.loadURL(`https://github.com`);
});
```

-

* Electron version: 1.2.0
* Operating system: OS X 10.11.5

**Comment by enlight** [comment] 2016-06-04 01:59
Dupe of #5794

**Comment by zcbenz** [comment] 2016-06-06 00:45
This is unfortunately a limitation of OS X, as explained in https://github.com/electron/electron/issues/5794#issuecomment-222687713.

**Closed by zcbenz** 2016-06-06 00:45 UTC
