### ISSUE TITLE
Crash on startup on ubuntu   Fatal error in ../../v8/src/objects.cc, line 2631 # Check failed: receiver->IsJSFunction()

### ISSUE THREAD

**Issue by serjN** [electron/electron#7030] opened 2016-08-30 08:32 UTC
Application crashed on  startup only with electron 1.3.3 and 1.3.4,  electron 1.3.2 works good.
OS: ubuntu 16.04 64bit
Error log:
```
#
# Fatal error in ../../v8/src/objects.cc, line 2631
# Check failed: receiver->IsJSFunction().
#

==== C stack trace ===============================

 1: V8_Fatal
 2: 0x7fb76fac8906
 3: v8::Object::CreationContext()
 4: atom::V8ValueConverter::FromV8Object(v8::Local<v8::Object>, atom::V8ValueConverter::FromV8ValueState*, v8::Isolate*) const
 5: atom::V8ValueConverter::FromV8ValueImpl(atom::V8ValueConverter::FromV8ValueState*, v8::Local<v8::Value>, v8::Isolate*) const
 6: atom::V8ValueConverter::FromV8Object(v8::Local<v8::Object>, atom::V8ValueConverter::FromV8ValueState*, v8::Isolate*) const
 7: atom::V8ValueConverter::FromV8ValueImpl(atom::V8ValueConverter::FromV8ValueState*, v8::Local<v8::Value>, v8::Isolate*) const
 8: atom::V8ValueConverter::FromV8Object(v8::Local<v8::Object>, atom::V8ValueConverter::FromV8ValueState*, v8::Isolate*) const
 9: atom::V8ValueConverter::FromV8ValueImpl(atom::V8ValueConverter::FromV8ValueState*, v8::Local<v8::Value>, v8::Isolate*) const
10: atom::V8ValueConverter::FromV8Object(v8::Local<v8::Object>, atom::V8ValueConverter::FromV8ValueState*, v8::Isolate*) const
11: atom::V8ValueConverter::FromV8ValueImpl(atom::V8ValueConverter::FromV8ValueState*, v8::Local<v8::Value>, v8::Isolate*) const
12: atom::V8ValueConverter::FromV8Object(v8::Local<v8::Object>, atom::V8ValueConverter::FromV8ValueState*, v8::Isolate*) const
13: atom::V8ValueConverter::FromV8ValueImpl(atom::V8ValueConverter::FromV8ValueState*, v8::Local<v8::Value>, v8::Isolate*) const
14: atom::V8ValueConverter::FromV8Array(v8::Local<v8::Array>, atom::V8ValueConverter::FromV8ValueState*, v8::Isolate*) const
15: atom::V8ValueConverter::FromV8ValueImpl(atom::V8ValueConverter::FromV8ValueState*, v8::Local<v8::Value>, v8::Isolate*) const
16: atom::V8ValueConverter::FromV8Value(v8::Local<v8::Value>, v8::Local<v8::Context>) const
17: mate::Converter<base::ListValue, void>::FromV8(v8::Isolate*, v8::Local<v8::Value>, base::ListValue*)
18: mate::internal::ArgumentHolder<3ul, base::ListValue const&>::ArgumentHolder(mate::Arguments*, int)
19: mate::internal::Invoker<mate::internal::IndicesHolder<0ul, 1ul, 2ul, 3ul>, atom::api::WebContents*, bool, std::basic_string<unsigned short, base::string16_char_traits, std::allocator<unsigned short> > const&, base::ListValue const&>::Invoker(mate::Arguments*, int)
20: mate::internal::Dispatcher<bool (atom::api::WebContents*, bool, std::basic_string<unsigned short, base::string16_char_traits, std::allocator<unsigned short> > const&, base::ListValue const&)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&)
21: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
22: 0x7fb76f72b1b7
23: 0x7fb76f72cf86
24: 0x3faa24408ba7


```

**Comment by zcbenz** [comment] 2016-08-30 10:42
This is a duplicate of #6992.

**Closed by zcbenz** 2016-08-30 10:42 UTC
