### ISSUE TITLE
Allow hide menuItem of type separator

### ISSUE THREAD

**Issue by popod** [electron/electron#7484] opened 2016-10-04 16:26 UTC
Electron : 1.4.2
OS : Windows 8

Allow to set `visible: false` to menuItem of `type: separator` ?

**Comment by kevinsawicki** [comment] 2016-10-04 16:36
This is not currently possible and most likely won't be implemented since it is not supported on macOS, closing as duplicate of https://github.com/electron/electron/issues/3494

**Closed by kevinsawicki** 2016-10-04 16:36 UTC

**Comment by popod** [comment] 2016-10-04 16:41
Okey, thanks for reply !
