### ISSUE TITLE
[Bug]: Maximizing/Minimizing/Etc A Frameless Window Has No Animations On Windows 11

### ISSUE THREAD

**Issue by nobu-sh** [electron/electron#33152] opened 2022-03-05 02:01 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1,0

### What operating system are you using?

Windows

### Operating System Version

Microsoft Windows 11 Pro 10.0.22000 Build 22000

### What arch are you using?

x64

### Last Known Working Electron version

14.2.5

### Expected Behavior

When setting `frame` in web preferences to `false` and creating my own app bar with `-webkit-app-region: drag;` (as shown in docs) when double clicking the area or dragging to the top to maximize the window, it should transition between sizes smoothly with an animation.

### Actual Behavior

It statically changes sizes. Instantly going from one size to another without the smooth transition.

### Testcase Gist URL

https://gist.github.com/nobu-sh/cf9c56ab9fd8488d3a1327a6f048789b

### Additional Information

Video to go along with the gist linked:

https://user-images.githubusercontent.com/61068742/156863370-3516162c-672c-4b5b-be80-a4e795f466b4.mp4

For context, fullscreening is an instant static movement. Normally is a smooth transition from windowed to fullscreen.

**Comment by FlysoftBeta** [comment] 2022-03-05 05:48
i have the same problem and it causes by https://github.com/electron/electron/pull/32692
so my solution is:
    if (process.platform == "win32") {
// ffi-napi
        var set_style = new Library("user32.dll", {
            "SetWindowLongA": ["int", ["int", "int", "long"]]
        });
        const WS_THICKFRAME = 0x00040000;
        const WS_CAPTION = 0x00C00000;
        const WS_OVERLAPPED = 0x00C00000;
        const WS_MAXIMIZEBOX = 0x00010000;
        const WS_MINIMIZEBOX = 0x00020000;
        var style = WS_CAPTION | WS_OVERLAPPED | WS_THICKFRAME | WS_MINIMIZEBOX | WS_MAXIMIZEBOX;
        set_style.SetWindowLongA(window.getNativeWindowHandle().readUint32LE(), -16, style);
    }

**Comment by FlysoftBeta** [comment] 2022-03-05 05:50
> i have the same problem and it causes by #32692 so my solution is: if (process.platform == "win32") { // ffi-napi var set_style = new Library("user32.dll", { "SetWindowLongA": ["int", ["int", "int", "long"]] }); const WS_THICKFRAME = 0x00040000; const WS_CAPTION = 0x00C00000; const WS_OVERLAPPED = 0x00C00000; const WS_MAXIMIZEBOX = 0x00010000; const WS_MINIMIZEBOX = 0x00020000; var style = WS_CAPTION | WS_OVERLAPPED | WS_THICKFRAME | WS_MINIMIZEBOX | WS_MAXIMIZEBOX; set_style.SetWindowLongA(window.getNativeWindowHandle().readUint32LE(), -16, style); }

the problem appears in electron v14.2.6

**Comment by nobu-sh** [comment] 2022-03-05 08:45
Thankyou for sharing this, very interesting; However, it does not appear to work for me. It results in a border and no window haha. Appears to not fully initialize now.

![image](https://user-images.githubusercontent.com/61068742/156875826-a38c31dd-b1fe-471b-9318-9950fcf681e5.png)

**Comment by FlysoftBeta** [comment] 2022-03-05 08:46
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by FlysoftBeta** [comment] 2022-03-05 10:23
> 

Well, you can use 14.2.5,it is newer than 13.6.9 and the  problem wont appear in 14.2.5

**Comment by nobu-sh** [comment] 2022-03-05 17:33
Ah alright thanks, will try that out!

**Comment by xpirt** [comment] 2022-03-08 13:08
I think it's a duplicate of the issue #32993.

**Comment by mlaurencin** [comment] 2022-03-15 18:54
I agree, this looks like a duplicate of https://github.com/electron/electron/issues/32993. Please continue any further discussion in that issue instead. You may also want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by mlaurencin** 2022-03-15 18:54 UTC
Labels: bug :beetle:, duplicate
