### ISSUE TITLE
[Bug]: macOS bitmap dfonts have incorrect spacing

### ISSUE THREAD

**Issue by David-A-RogersHS2** [electron/electron#30297] opened 2021-07-27 22:48 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.13 in VSCode 1.58.2

### What operating system are you using?

macOS

### Operating System Version

macOS 10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

7.3.2 in VSCode 1.48.2

### Expected Behavior

Mac bitmap dfonts should appear correctly laid out. You can see the behavior in VS Code, though I understand that Atom has the same problem now.

Steps to reproduce:
- Install a macOS bitmap dfont such as Dina (https://aaroniba.net/dina-font-osx)
or Gohufont (https://font.gohu.org) you'll find the link to the dfont at the bottom of the page
or any of the X11 misc fonts for Mac found here (http://monkey.org/~marius/x11-misc-fixed.tar.gz)
- Install and run VS Code 1.48.2
- Set the dfont and the proper font size
- Open any source file.
- You'll see that the text looks fine.
- ------------------
- Delete the VS Code app
- Download and run the latest VS Code app (I used 1.58.2)
- Set the dfont and the proper font size
- Open any source file
- You'll see extremely wide spacing.
- You may need to close and reopen the VS Code app, but all subsequent runs will have the problem. See the attached image.
![image](https://user-images.githubusercontent.com/20795729/127237003-4eb04d3e-7be7-4f9c-9c2f-1e54f946a62b.png)

### Actual Behavior

Text using macOS bitmap dfonts are extremely widely spaced. See the attached image.

### Additional Information

I tried submitting this with Visual Studio Code, but they've sent me to you.

Please let me know if there's any other information I can give you. I'm stuck using a very old version of VS Code for now.

**Comment by clavin** [comment] 2021-08-03 03:54
Hi there! Thanks for the report. I've dug in deep on this one for you.

I was able to reproduce this bug (at least with the Dina font; I didn't try the others). While it's still a little strange, I am personally able to consistently reproduce this bug. Additionally, this bug is also reproducible in Chrome which means that this is definitely a bug in Chromium.

I'm going to open a bug on the Chromium bug tracker (since I've already figured out the repro criteria) and mark this as blocked by upstream changes there. I'll post again here once I've submitted that bug to Chromium's tracker.

**Comment by clavin** [comment] 2021-08-03 07:31
I have opened a bug in Chromium's bug tracker with more info: https://bugs.chromium.org/p/chromium/issues/detail?id=1235963

**Comment by David-A-RogersHS2** [comment] 2021-08-03 14:08
> Hi there! Thanks for the report. I've dug in deep on this one for you.

Thanks for running this down.

**Comment by nornagon** [comment] 2021-08-03 17:11
Let's close this; the upstream bug is the one to track!

**Closed by nornagon** 2021-08-03 17:11 UTC
Labels: blocked/upstream ❌, bug :beetle:, status/confirmed
