### ISSUE TITLE
before-input-event is not working in production mode

### ISSUE THREAD

**Issue by rohail411** [electron/electron#30380] opened 2021-08-03 10:59 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.5

### What operating system are you using?

macOS

### Operating System Version

macOS Cataline 10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

13.1.5

### Expected Behavior

The (before-input-event) is trigger in production but unfortunality listener is not working.

### Actual Behavior

The (before-input-event) is working fine in dev mode but not working in production mode. 

### Testcase Gist URL

https://gist.github.com/ccda24555fe7c6cb93e8f4fe93138e14

**Comment by nornagon** [comment] 2021-08-03 17:11
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2021-08-17 17:44
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by nornagon** [comment] 2021-08-18 18:45
@codebytere it looks like the author added a gist but didn't comment, so I'm reopening this.

**Comment by MarshallOfSound** [comment] 2021-08-23 16:32
Tested this on macOS via the provided fiddle gist and the code appears to function as expected in both the unpackaged and packaged cases.  Given no the repro doesn't appear to actually repro I'm going to close this out, if there is something wrong on your machine I'd suggest double checking your specific setup and ensuring that the differences between your app and the gist itself are correct as this seems like an implementation specific issue.

**Closed by MarshallOfSound** 2021-08-23 16:32 UTC
Labels: bug :beetle:, has-repro-gist
