### ISSUE TITLE
Cycling through windows on macOS doesn't respect the shift key to reverse direction.

### ISSUE THREAD

**Issue by doughsay** [electron/electron#6852] opened 2016-08-15 22:03 UTC
* Electron version: 0.37.8
* Operating system: macOS 10.11.6

I reported this here: https://github.com/atom/atom/issues/12242

But I believe it's an electron issue, and also, they're ignoring me over there...

This appears to be a regression since it looks like it was fixed once: #4577

**Comment by kevinsawicki** [comment] 2016-08-15 22:18
This is a duplicate of https://github.com/electron/electron/issues/5246 and was fixed in https://github.com/electron/electron/pull/6068 and released in `1.2.4`.

**Closed by kevinsawicki** 2016-08-15 22:18 UTC
