### ISSUE TITLE
[Bug]: Electron@25/26/27 cannot trigger the camera device change event of the system in macOS？

### ISSUE THREAD

**Issue by luojinghui** [electron/electron#39577] opened 2023-08-18 11:12 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25 | 26 | 27beta

### What operating system are you using?

macOS

### Operating System Version

13.5 (22G74)  - 2.6 GHz 六核Intel Core i7

### What arch are you using?

x64

### Last Known Working Electron version

Versions 24 and below are available

### Expected Behavior

Under the MacOS system, use the Electron@25+ version, the api of the system [AVCaptureDeviceWasConnectedNotification](https://developer.apple.com/documentation/avfoundation/avcapturedevicewasconnectednotification) can be used to monitor the changes of the camera device normally.

### Actual Behavior

Use C++ encapsulates the device management module of oc (based on: [AVCaptureDeviceWasConnectedNotification](https://developer.apple.com/documentation/avfoundation/avcapturedevicewasconnectednotification)), and implements a dylib dynamic library.

When the electron@25+ version calls dylib, after the camera device changes, the system api monitoring is not triggered. Electron versions of electron@24 and below can be triggered normally.

### Testcase Gist URL

https://gist.github.com/luojinghui/098f3e1dc6322f16626cdab8e145a8f1

### Additional Information

After comparing and testing with different electron versions under the same system, it is confirmed that this problem is a problem after Electronv25+. Can confirm whether there are any restrictions?

**Comment by codebytere** [comment] 2023-08-21 14:48
you previously opened an issue about this, so i'm closing this out as a duplicate of https://github.com/electron/electron/issues/38854. Please comment there instead of opening new identical issues.

**Closed by codebytere** 2023-08-21 14:48 UTC
Labels: bug :beetle:
