### ISSUE TITLE
electron 'will-download' not working 

### ISSUE THREAD

**Issue by tonifds** [electron/electron#29602] opened 2021-06-09 05:20 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 21H1 build 19043.1023

### What arch are you using?

x64

### Last Known Working Electron version

5.0

### Expected Behavior

get files downloaded to a specific folder without popup saving dialog as usual.

### Actual Behavior

After upgrading to electron v13.1.1, i cannot download anymore files using classic method like this:

// In the main process.
const { BrowserWindow } = require('electron')
const win = new BrowserWindow()
win.webContents.session.on('will-download', (event, item, webContents) => {
  // Set the save path, making Electron not to prompt a save dialog.
  item.setSavePath('tmp0'+ '/' + item.getFilename())

  item.on('updated', (event, state) => {
    if (state === 'interrupted') {
      console.log('Download is interrupted but can be resumed')
    } else if (state === 'progressing') {
      if (item.isPaused()) {
        console.log('Download is paused')
      } else {
        console.log(`Received bytes: ${item.getReceivedBytes()}`)
      }
    }
  })
  item.once('done', (event, state) => {
    if (state === 'completed') {
      console.log('Download successfully')
    } else {
      console.log(`Download failed: ${state}`)
    }
  })
})

**Comment by DEEPAKCHOUDHARY2004** [comment] 2021-06-09 06:06
Dodo

**Comment by tonifds** [comment] 2021-06-09 08:48
no error appear console

**Comment by tonifds** [comment] 2021-06-09 11:29
item.setSavePath(app.getAppPath()+ '/tmp/' +  item.getFilename())    this format not working but item.setSavePath(app.getAppPath()+ '/' +  item.getFilename())  is working, how to add the folder "tmp" to the path?

**Comment by zcbenz** [comment] 2021-06-16 07:46
We have a few tests covering the `will-download` event and it seems that we did not detect anything broken. Can you make a minimal app that can reproduce your issue?

**Comment by codebytere** [comment] 2021-06-21 07:52
I cannot reproduce with https://gist.github.com/691f2e2bd4c5ca323022500b2ba98406 - please provide a reproducible gist or this issue will be closed in 7 days @tonifds

**Comment by sofianguy** [comment] 2021-07-07 21:12
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2021-07-07 21:12 UTC
Labels: 13-x-y, blocked/need-repro, bug :beetle:, platform/windows
