### ISSUE TITLE
[Bug]: Sudden crash with no error

### ISSUE THREAD

**Issue by skymen** [electron/electron#30908] opened 2021-09-10 08:33 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

6.1.9

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Not crash

### Actual Behavior

I have an electron app that communicates with a web client through a socketio server that the electron app hosts itself.

When I hit a button in my app, it sends a message to the client to update its data, and on rare occasions, when there is "enough" data to send, the app just crashes with no error message.

I have never had this happen to me, but a few people that have used the app have gotten it quite a few times.

### Additional Information

I think this is a bug on my end, but I genuinely have NO idea what causes it, nor how to replicate it, and I don't even know where to start looking.

Profiler seems to be fine, and it doesn't look like I have any memory leak. I don't know where electron dumps crash logs, so I can't even try and find that info either. I'm genuinely just shooting in the dark with no way of knowing if what I'm doing works since I can't even reproduce the bug.

If anyone has some advice as to where to start it would be insanely helpful, I'm completely lost.

**Comment by VerteDinde** [comment] 2021-09-10 19:55
Hey @skymen, thanks for reporting this issue!

Electron 6 is a fairly old version of Electron that's outside of our current LTS versions. Could you try upgrading your app to one of the current supported versions (12, 13 or 14) and see if the issue persists?  I suspect there may be an older API in your Electron version that's no longer working as expected; upgrading may solve the issue.

If you do upgrade and the issue continues, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use. Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a follow up comment.

Thanks!

**Comment by skymen** [comment] 2021-09-11 13:00
Hey, thanks for your suggestion!

Is there some guide about how to cleanly upgrade? Because I updated my electron version to latest, and now I'm getting errors on build about how "app" is a property of undefined :/

**Comment by VerteDinde** [comment] 2021-09-12 20:12
Yeah! There's a few things I generally do when upgrading:

1. Try to go one or two major versions at a time; it's easier to find and fix breaking changes that way.
2. Look at our breaking changes doc, which lists breaking API changes per version: https://www.electronjs.org/docs/breaking-changes

If you're seeing `"app" is not a property of undefined`, I'd guess that you're seeing an error with either nodeIntegration or contextIsolation; the defaults for both have changed since Electron 6. In the short term, try changing these settings when you set your main window to see if it addresses the error:

```
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      contextIsolation: false,
      nodeIntegration: true
    }
  });
```

Long term, I'd recommend setting your app to `nodeIntegration: false` and `contextIsolation: true` for security reasons, but this should at least help you debug while upgrading 🙂 

Good luck! If you need more in-depth debugging help, check out the [Electron Discord](https://discord.gg/electron) - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Comment by skymen** [comment] 2021-09-12 21:21
Thank you very much for your help :)

**Comment by ropau001** [comment] 2021-09-22 09:03
Hey,

I have the same issue on Version 10.4.2. In my case i can't reproduce the bug. But different Customers reports a grey window and the console show's: electron devtools was disconnected from the page

In two different location my company can't reproduce this issue.

The Appliation is base on in framework and can't updated to a newer Version. The Electron is running in a JVM.

Any ideas?

**Comment by codebytere** [comment] 2022-05-11 13:43
Closing as there is no actionable next step for this issue.

**Closed by codebytere** 2022-05-11 13:43 UTC
Labels: bug :beetle:, blocked/need-repro
