### ISSUE TITLE
BrowserView is not filling the available area when window size is adjusted on Windows.

### ISSUE THREAD

**Issue by pingviini** [electron/electron#27285] opened 2021-01-12 19:43 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.x - 12.0.0-beta14
* **Operating System:**
  * Windows 10 (Build 18363)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
BrowserView should fill the available space in BrowserWindow when application window size is changed when it has been set to autoresize view according to BrowserWindow width/height.

### Actual Behavior
BrowserView does fill the available space, but leaves small gaps to the right/bottom side of the view. Gap size is relative to how much the size is enlarged. This happens only in Windows. On Linux there are no gaps and changing window size works without 
issues.

### To Reproduce

Gist for Electron Fiddle: https://gist.github.com/4c1a403df092cded0d8ff85640a9c19f

### Screenshots
![image](https://user-images.githubusercontent.com/66526/104361211-d8382180-551a-11eb-9579-d808fc0437a2.png)

https://user-images.githubusercontent.com/66526/104364196-f142d180-551e-11eb-9349-798f658f9e30.mp4

**Comment by pushkin-** [comment] 2021-01-12 20:35
if you move the window around does it solve the problem? I've seen issues where I'd get some white bars when moving the window from one monitor to another that has different DPI settings, but moving the window a little, or maybe resizing a little fixes it.

**Comment by pingviini** [comment] 2021-01-13 09:36
I've tried moving the window around and to a different display, resizing a little, maximizing and then resizing to a smaller size. Unfortunately any of those steps has no effect - the gap stays visible and it's size is relative to the window size. When window is maximized it claims about 2 cm from the bottom border on my display (2560x1440) so this looks really bad.

**Comment by pingviini** [comment] 2021-01-13 11:46
To make this work properly on Windows requires adding 'will-resize' event listener to BrowserWindow to set the view size manually - so for some reason the BrowserView.setAutoResize doesn't seem to work in here.

**Comment by yourfriendoss** [comment] 2021-12-11 18:02
Duplicate of #22174.

**Comment by codebytere** [comment] 2022-06-22 11:35
Duplicate of https://github.com/electron/electron/issues/22174

**Closed by codebytere** 2022-06-22 11:35 UTC
Labels: platform/windows, component/BrowserView, 8-x-y, 9-x-y, 10-x-y, 11-x-y, 12-x-y
