### ISSUE TITLE
Setting User Agent string?

### ISSUE THREAD

**Issue by RaNo99** [electron/electron#7218] opened 2016-09-15 13:33 UTC
* Electron version: 1.3.2 prebuilt
* Operating system: Windows 10

I'm setting user agent with:
```
const webview = document.createElement('webview');
webview.useragent = "my user agent string";
```

Later, from that webview, I call `webview.getWebContents().session.getUserAgent()`, and it returns the original one, not mine :(

Please advise what am I doing wrong. I'd like to set the User Agent string globally. Thank you.

**Comment by MarshallOfSound** [comment] 2016-09-15 15:48
@RaNo99 I'm 99% sure that that property is read only and doesn't propograte write attempts throughout the API.

You should probably use the [`setUserAgent()`](http://electron.atom.io/docs/api/web-contents/#contentssetuseragentuseragent) API.

```js
webview.getWebContents().setUserAgent('string of magical things');
```

Please  close this issue if this method resolves your problem

**Comment by paulcbetts** [comment] 2016-09-15 16:07
userAgent is basically only for when you create a webview tag via HTML, the API is a little confusing

**Comment by MarshallOfSound** [comment] 2016-09-15 16:14
> useragent is basically only for when you create a webview tag via HTML, the API is a little confusing

@paulcbetts Perhaps we should make those setters and proxy them to the appropriate API's?

**Comment by paulcbetts** [comment] 2016-09-16 00:36
@MarshallOfSound Seems reasonable. The reason there's an attribute on the tag is because otherwise you have this race condition where the first few requests on the WebView are issued with the original useragent

**Comment by deepak1556** [comment] 2016-09-16 03:34
@RaNo99 setting user agent for webcontents and session are two different things, the former is a subset of the latter. In your case you have set the useragent for webview webContents, so `webview.getWebContents().getUserAgent()` will return the right value and `webview.getWebContents().session.getUserAgent()` will return the default one since it wasn't modified.

This can be closed since its not a bug in Electron.

**Closed** 2016-09-16 07:38 UTC
Labels: more-information-needed
