### ISSUE TITLE
Accept § as a valid accelerator

### ISSUE THREAD

**Issue by gfpacheco** [electron/electron#8263] opened 2016-12-21 17:14 UTC
The UK keyboard has this `§` key right under the `esc` key. Would be great to be able to use it for shortcut commands.

Does it make sense?

BTW: It's shifted value is `±`.

**Comment by kevinsawicki** [comment] 2016-12-21 17:41
I believe this is a duplicate of #8208

**Closed by kevinsawicki** 2016-12-21 17:41 UTC
