### ISSUE TITLE
[Bug]: Unable to focus / show on Windows notification protocol activation

### ISSUE THREAD

**Issue by alefoll** [electron/electron#35085] opened 2022-07-27 01:46 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.9

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 (22622.436)

### What arch are you using?

x64

### Expected Behavior

Clicking on notification should focus and show the `mainWindow`.

### Actual Behavior

The app is alerted in the taskbar.

### Testcase Gist URL

https://gist.github.com/alefoll/d9837a001f4cf6847e365541a31633d9

### Additional Information

To reproduce :
- `yarn start`
- Unfocus the app
- Click on the notification

https://user-images.githubusercontent.com/6286683/181142533-9702c578-4865-44a9-8b0f-2a4be61261a8.mp4

**Comment by clavin** [comment] 2022-07-29 16:37
(Only triaging this issue.) I was able to repro this bug on 19.0.9 as well as 20.0.0-beta.13. Trying further back, I was also able to repro this on every version from 16-x-y onwards that I tried.

Searching around in the bug tracker, it looks like this is the same as #32892. I'm closing this one as a duplicate of that one to keep the bug tracker tidy. Thank you for the report! 👍

**Closed by clavin** 2022-07-29 16:37 UTC
Labels: bug :beetle:
