### ISSUE TITLE
win.setFullScreen Not working properly

### ISSUE THREAD

**Issue by imtiyazs** [electron/electron#13108] opened 2018-05-30 04:57 UTC
* Electron Version: 2.0.2
* Operating System (Platform and Version): x64 - Windows 10 Enterprise
* Last known working Electron version: 1.8.6

**Expected Behavior**
The window should become fullscreen (hiding taskbar too) when win.setFullScreen(true) is called. But the window stays above the taskbar.

**Actual behavior**
I'm changing my window properties in below sequence : 
```
        main.setFullScreen(false)
        main.setMinimizable(false)
        main.setClosable(false)
        main.setSkipTaskbar(true)
        main.setResizable(false)
        let screenResize = setInterval(() => {
          if (main.isFullScreen() == false) {
            main.setSize(263, 292)
            main.setPosition(screenSize.width - 263, screenSize.height - 292)
            clearInterval(screenResize)
          }
        }, 10)
```

When I want my screen to original size and position, m following this sequence:
``` 
        main.setSize(screenSize.width, screenSize.height)
        main.setFullScreen(true)
        main.setMinimizable(true)
        main.setMovable(false)
        main.setClosable(true)
        main.setPosition(0, 0)
        main.setSkipTaskbar(false)
```

In electron 1.8.6, the above code worked perfectly as expected, but after upgrading to 2.0.2, the window does not go fullscreen. Taskbar is visible below whereas in earlier versions the window use to go fullscreen hiding taskbar too.

**To Reproduce**
You can use above window properties on any basic electron application to reproduce.

**Comment by Kthulu120** [comment] 2018-09-21 07:35
Hmm not able to reproduce on my machine, perhaps you could fork the electron-start-app and build an simple example so its easier to replicate and we can take a look again
From your example the initial issue the taskbar still seems to disappear. I attempted to reproduce on on 2.0.0 - 2.0.7.

**Comment by sofianguy** [comment] 2018-10-12 22:09
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2018-10-12 22:09 UTC
Labels: blocked/needs-repro, bug :beetle:, platform/windows, version/2.0.x
