### ISSUE TITLE
[Bug]: nodeIntergration dosnt work

### ISSUE THREAD

**Issue by richmailYT** [electron/electron#32000] opened 2021-11-25 14:11 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.2.3

### What operating system are you using?

macOS

### Operating System Version

10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

0.0.0

### Expected Behavior

I enable `nodeIntergration`. I use require in render.js without error.

I am forced to use electron 12.2.3 beucase of a depenency

### Actual Behavior

It throws `require not defined`

### Additional Information

node 14.18.1

https://github.com/richmailYT/AutoClicker/tree/main

**Comment by codebytere** [comment] 2021-11-25 15:18
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed** 2021-11-25 15:19 UTC
Labels: bug :beetle:, blocked/need-repro

**Comment by richmailYT** [comment] 2021-11-25 15:46
i added `contextIsolation: true` and it still says require if not defined

**Comment by codebytere** [comment] 2021-11-25 15:50
@richmailYT you need to _disable_ `contextIsolation`, not enable it.

**Comment by richmailYT** [comment] 2021-11-25 15:55
that fixed the warning, but i cant seem to use the imports. I imported ipc and followed https://www.electronjs.org/docs/latest/api/ipc-main but it dosnt sned the message. or it does the the mian prosess never resives @codebytere
