### ISSUE TITLE
Dev tools display absolute file paths instead of short file names everywhere

### ISSUE THREAD

**Issue by anri-asaturov** [electron/electron#8869] opened 2017-03-08 17:31 UTC
* Electron version: 1.6.1
* Operating system: OSX

It might be a chromium issue, i'm not sure.

### Expected behavior

Console log and other parts of the dev tools that display file names, should display file names only, like it was in Electron 1.5.x.
![image](https://cloud.githubusercontent.com/assets/1479005/23715441/58ef8dd0-0435-11e7-8766-3be83fc01540.png)

### Actual behavior

Electron 1.6.x displays absolute file paths in console, file search(cmd+o) and so on.
![image](https://cloud.githubusercontent.com/assets/1479005/23715502/8d2e987a-0435-11e7-890e-7e963a1ebaf1.png)

This complicates working with dev tools a lot :(

**Comment by zeke** [comment] 2017-03-08 18:59
> This complicates working with dev tools a lot :(

What specifically is more complicated? Is it just a matter of more visual noise in the devtools window?

**Comment by anri-asaturov** [comment] 2017-03-08 19:09
Yeah,  
- it's impossible to follow logs with all the wraps, the screenshot i posted is nice, just an example, real life log is a terrible mess. 
- When I do CMD+O i don't see file names in the dropdown, they just don't fit.

If you try to debug any serious electron app, you'll notice immediately.

**Comment by kevinsawicki** [comment] 2017-03-09 00:43
Opened a chrome issue upstream since I can reproduce this in standalone chrome, https://bugs.chromium.org/p/chromium/issues/detail?id=699817

**Comment by codebytere** [comment] 2018-09-24 04:43
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 04:43 UTC
Labels: bug :beetle:, component/devtools, platform/macOS, version/1.6.x
