### ISSUE TITLE
Electron 6.0.0 application crashes/not compactable on all Windows 32bit

### ISSUE THREAD

**Issue by giridharkannan** [electron/electron#19594] opened 2019-08-02 13:45 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0
* **Operating System:**
  * Windows 7 Professional 32 bit
* **Last Known Working Electron version:**
  * 5.0.8 

### Expected Behavior
The app must run without crash

### Actual Behavior
App crashes

### To Reproducee 
Build the application for Windows platform with arch type as ia32

### Sample repo based out of electron activity-monitor
https://github.com/giridharkannan/simple-samples
```bash
git clone https://github.com/giridharkannan/simple-samples.git
cd simple-samples/activity-monitor/
npm install
npm run deploy
cd dist
```

Use the generated activity-monitor_1.0.0.exe to reproduce the issue

### Additional Information
You need 32bit OS or VM to reporduce the issue as we would not face problem in creating the exe nor in installing it. The app would just have a blank black screen

**Comment by zlab** [comment] 2019-08-03 01:24
the same issue https://github.com/electron/electron/issues/19569

**Comment by giridharkannan** [comment] 2019-08-05 05:39
Since this is a critical issue, I would like you to take this as a prioprity and do the needfull. If you need any more information from my end, don't be hesitant to ask the same.

**Comment by nornagon** [comment] 2019-08-05 23:11
Duplicate of #19569.

**Closed by nornagon** 2019-08-05 23:11 UTC
