### ISSUE TITLE
[Bug]: Electron 13: Devtools does not open on windows

### ISSUE THREAD

**Issue by tillgi** [electron/electron#30489] opened 2021-08-11 07:45 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

11.2.1

### Expected Behavior

Devtools should open on windows with Ctrl+Shift+I.

### Actual Behavior

Devtools do not appear.

### Additional Information

We build our electron app with electron builder 22.11.7 on macOs BigSur 11.4

**Comment by tillgi** [comment] 2021-08-11 12:45
Found the solution: 
Override the default menu with your own and use one submenu for devtools. Toggle them with webContents.toggleDevtools(). https://www.electronjs.org/docs/tutorial/keyboard-shortcuts#example

**Comment by codebytere** [comment] 2021-08-12 14:58
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests. I tried to run this with the default Fiddle and when pressing `Ctrl+Shift+I` the devtools window popped up with no issue.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by ckerr** [comment] 2021-08-18 19:31
> I tried to run this with the default Fiddle and when pressing `Ctrl+Shift+I` the devtools window popped up with no issue.

I'm seeing the same here; Ctrl-Shift-I pops up devtools for me as well.

@tillgi, if you open up Electron 13.1.2 with the default app, are you able to see devtools there?

**Comment by codebytere** [comment] 2021-09-07 15:06
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2021-09-07 15:06 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, 13-x-y
