### ISSUE TITLE
[Bug]: Electron app crash on Windows

### ISSUE THREAD

**Issue by denytheman** [electron/electron#32580] opened 2022-01-21 22:28 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.2.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10, 10.0.19043

### What arch are you using?

x64

### Last Known Working Electron version

13.2.3

### Expected Behavior

The application should run as expected.

### Actual Behavior

There was a crash dump generated. 

NOTE: This is a random issue and happened only once.  

I have a crash dump to attach but I'm not sure how so here are the details:

> The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
> 
> Unhandled exception at 0x00007FF7018AFFB3 (logioptionsplus.exe) in logioptionsplus.exe.13144.dmp: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

**Comment by codebytere** [comment] 2022-01-24 09:34
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by nornagon** [comment] 2022-01-24 22:48
@denytheman you can attach your crash dump by zipping it and commenting here.

**Comment by denytheman** [comment] 2022-01-24 23:04
@nornagon  Unfortunately attaching does not work, I'm guessing maybe there is a size limit. The crash dump is 113MB compressed. Is there some other way to post somewhere else and put a link here?

@codebytere This was a random crash and not something I can easily reproduce.

**Comment by zcbenz** [comment] 2022-01-25 10:56
Can you setup crash reporter in your app and get a symbolized crash report?
https://www.electronjs.org/docs/latest/api/crash-reporter

**Comment by nornagon** [comment] 2022-01-25 20:56
Ah, I assumed you had a crash report from the crash reporter. Here's a snippet for enabling that. Add this to your main process, before the `ready` event:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by denytheman** [comment] 2022-01-28 05:19
Thank you for the information, here are the crash dumps that got generated.

[54f5861c-9239-4691-8b69-d53dd3bd5899.zip](https://github.com/electron/electron/files/7955901/54f5861c-9239-4691-8b69-d53dd3bd5899.zip)
[7544f114-dea8-4dd6-8e0b-fdb4b97f1bac.zip](https://github.com/electron/electron/files/7955904/7544f114-dea8-4dd6-8e0b-fdb4b97f1bac.zip)

**Comment by nornagon** [comment] 2022-02-22 00:22
Symbolicated crash:

<details>

```
Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0xffffffffffffffff
Process uptime: 10 seconds

Thread 0 (crashed)
 0  logioptionsplus.exe!v8::internal::GlobalHandles::Destroy(unsigned __int64 *) [global-handles.cc : 1131 + 0x58]
    rax = 0x005c280050660000   rdx = 0xffffffffffffe720
    rcx = 0x0000665000f87ce0   rbx = 0x0000665000fc4440
    rsi = 0x0000665000285660   rdi = 0x000066500106ef80
    rbp = 0x0000665000290be0   rsp = 0x000000c695dff330
     r8 = 0x0000000000000000    r9 = 0x000000007ffea000
    r10 = 0x00000000546c6148   r11 = 0xfffffffffe19bff5
    r12 = 0xaaaaaaaaaaaaaaaa   r13 = 0x0000665001054c90
    r14 = 0x000066500037a100   r15 = 0x0000000000000000
    rip = 0x00007ff72f5effb3
    Found by: given as instruction pointer in context
 1  logioptionsplus.exe!gin_helper::PromiseBase::~PromiseBase() [promise.cc : 22 + 0x16]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff370   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72c9fd9f6
    Found by: call frame info
 2  logioptionsplus.exe!static void base::internal::BindState<`lambda at ../../electron/shell/browser/api/electron_api_cookies.cc:280:11',gin_helper::Promise<void> >::Destroy(const class base::internal::BindStateBase *) [bind_internal.h : 921 + 0x11]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff3a0   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72c8d19d6
    Found by: call frame info
 3  logioptionsplus.exe!static void base::internal::BindState<`lambda at ../../device/bluetooth/bluetooth_adapter_winrt.cc:820:7',base::WeakPtr<device::BluetoothAdapterWinrt>,base::OnceCallback<void ()> >::Destroy(const class base::internal::BindStateBase *) [bind_internal.h : 921 + 0x11]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff3d0   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72ca40706
    Found by: call frame info
 4  logioptionsplus.exe!static void base::internal::BindState<void (*)(base::OnceCallback<void (std::pair<scoped_refptr<const extensions::Extension>,std::string>)>, std::unique_ptr<std::pair<scoped_refptr<const extensions::Extension>,std::string>,std::default_delete<std::pair<scoped_refptr<const extensions::Extension>,std::string> > > *),base::OnceCallback<void (std::pair<scoped_refptr<const extensions::Extension>,std::string>)>,base::internal::OwnedWrapper<std::unique_ptr<std::pair<scoped_refptr<const extensions::Extension>,std::string>,std::default_delete<std::pair<scoped_refptr<const extensions::Extension>,std::string> > >,std::default_delete<std::unique_ptr<std::pair<scoped_refptr<const extensions::Extension>,std::string>,std::default_delete<std::pair<scoped_refptr<const extensions::Extension>,std::string> > > > > >::Destroy(const class base::internal::BindStateBase *) [bind_internal.h : 921 + 0x6e]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff400   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72ca61777
    Found by: call frame info
 5  logioptionsplus.exe!static void base::internal::BindState<void (*)(base::(anonymous namespace)::PostTaskAndReplyRelay),base::(anonymous namespace)::PostTaskAndReplyRelay>::Destroy(const class base::internal::BindStateBase *) [bind_internal.h : 921 + 0x22]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff450   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72fb697bb
    Found by: call frame info
 6  logioptionsplus.exe!base::sequence_manager::internal::LazilyDeallocatedDeque<base::sequence_manager::Task,&base::subtle::TimeTicksNowIgnoringOverride(void)>::Ring::~Ring() [lazily_deallocated_deque.h : 248 + 0x2b]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff4a0   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72dab94ad
    Found by: call frame info
 7  logioptionsplus.exe!base::sequence_manager::internal::WorkQueue::~WorkQueue() [work_queue.cc : 31 + 0x26]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff4e0   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72dfdc895
    Found by: call frame info
 8  logioptionsplus.exe!base::sequence_manager::internal::TaskQueueImpl::UnregisterTaskQueue() [task_queue_impl.cc : 221 + 0x22]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff520   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72dab66d8
    Found by: call frame info
 9  logioptionsplus.exe!base::sequence_manager::internal::SequenceManagerImpl::UnregisterTaskQueueImpl(std::__1::unique_ptr<base::sequence_manager::internal::TaskQueueImpl,std::__1::default_delete<base::sequence_manager::internal::TaskQueueImpl> >) [sequence_manager_impl.cc : 410 + 0x5]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff610   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72dab3529
    Found by: call frame info
10  logioptionsplus.exe!base::sequence_manager::TaskQueue::ShutdownTaskQueue() [task_queue.cc : 188 + 0xb]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff700   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72dab4f90
    Found by: call frame info
11  logioptionsplus.exe!content::BrowserTaskQueues::~BrowserTaskQueues() [browser_task_queues.cc : 204 + 0x5]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff770   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72d6a5600
    Found by: call frame info
12  logioptionsplus.exe!content::BrowserUIThreadScheduler::~BrowserUIThreadScheduler() [browser_ui_thread_scheduler.cc : 26 + 0x9]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff7b0   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72d6a5873
    Found by: call frame info
13  logioptionsplus.exe!void content::BrowserTaskExecutor::UIThreadExecutor::~UIThreadExecutor() [browser_task_executor.cc : 342 + 0x19]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff7f0   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72d6a4cc9
    Found by: call frame info
14  logioptionsplus.exe!void content::BrowserTaskExecutor::UIThreadExecutor::~UIThreadExecutor() [browser_task_executor.cc : 339 + 0x5]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff830   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72d6a4d40
    Found by: call frame info
15  logioptionsplus.exe!content::BrowserTaskExecutor::Shutdown() [browser_task_executor.cc : 255 + 0x1b]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff870   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72d6a499b
    Found by: call frame info
16  logioptionsplus.exe!content::ContentMainRunnerImpl::Shutdown() [content_main_runner_impl.cc : 1100 + 0x5]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff8a0   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72cf3e68d
    Found by: call frame info
17  logioptionsplus.exe!static int content::RunContentProcess(const struct content::ContentMainParams & const, class content::ContentMainRunner *) [content_main.cc : 390 + 0x8]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dff920   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72cf3cf43
    Found by: call frame info
18  logioptionsplus.exe!content::ContentMain(content::ContentMainParams const &) [content_main.cc : 398 + 0x8]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dffb40   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72cf3d20d
    Found by: call frame info
19  logioptionsplus.exe!wWinMain [electron_main.cc : 285 + 0x8]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dffb90   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72c8be9b3
    Found by: call frame info
20  logioptionsplus.exe!static int __scrt_common_main_seh() [exe_common.inl : 288 + 0x21]
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dffd50   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ff72ff07402
    Found by: call frame info
21  KERNEL32.DLL!BaseThreadInitThunk + 0x14
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dffd90   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ffbf5ec7034
    Found by: call frame info
22  ntdll.dll!RtlUserThreadStart + 0x21
    rbx = 0x0000665000fc4440   rbp = 0x0000665000290be0
    rsp = 0x000000c695dffdc0   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x0000665001054c90   r14 = 0x000066500037a100
    r15 = 0x0000000000000000   rip = 0x00007ffbf6e82651
    Found by: call frame info
```

</details>

**Comment by nornagon** [comment] 2022-02-22 00:29
Can you please test this on a newer version of Electron? 13.x is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).

**Comment by miniak** [comment] 2022-03-20 00:55
Closing due to lack of activity.

**Closed by miniak** 2022-03-20 00:55 UTC
Labels: blocked/need-info ❌, bug :beetle:, 13-x-y
