### ISSUE TITLE
[Bug]: electron 7.x raise an error "Cannot read property 'createTexture' of null"

### ISSUE THREAD

**Issue by StitchC** [electron/electron#29041] opened 2021-05-06 07:30 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

7.3.3

### What operating system are you using?

Windows

### Operating System Version

windows 10.0.14393

### What arch are you using?

x64

### Last Known Working Electron version

4.2.12

### Expected Behavior

this error should not be shown

### Actual Behavior

this error show and the app stuck on this error 

![image](https://user-images.githubusercontent.com/21286819/117258826-f803a480-ae7f-11eb-98ef-f1bffa987414.png)

### Additional Information

our application use layabox game engine render the app interface, when our use electron 4.2.12 everything is ok but upgrade to electron 7.x this error shown, i have confused in this error for a long time please help me as soon as possible

**Comment by pushkin-** [comment] 2021-05-06 14:44
Electron 7 isn't supported anymore - try with Electron 10 or higher

**Comment by VerteDinde** [comment] 2021-05-06 20:01
Hey @StitchC, thanks for reporting an issue! As @pushkin- stated above, Electron 7 is no longer supported - can you confirm that this is still an issue for you on Electron 10 or higher? 

One thing that might help you debug: Electron 5 and Electron 6 introduced Promise-based versions of existing asynchronous APIs and deprecated their older, callback-based counterparts. In Electron 7, all deprecated callback-based APIs are now removed. You can see those APIs in our breaking changes doc: [Breaking Changes](https://www.electronjs.org/docs/breaking-changes#api-changed-callback-based-versions-of-promisified-apis). Your error looks like a JS error hitting `null`, so my off-the-cuff is that an API was changed and is no longer returning what you expect.

Since we use this issue tracker as our team board, I'll close this issue if you can't reproduce in Electron 10+. If you can and if you can make a small repro of the error itself for our team to look at, let me know! 🙂

**Comment by StitchC** [comment] 2021-05-07 01:42
@VerteDinde 

i try to set the switch
`
app.commandLine.appendSwitch('no-sandbox')
`

the error was resolve

How amazing!

**Closed** 2021-06-30 23:16 UTC
Labels: blocked/need-info ❌, bug :beetle:
