### ISSUE TITLE
child_process spawn locks up renderer for 300 - 3000ms on signed app on macOS Big Sur

### ISSUE THREAD

**Issue by marcello3d** [electron/electron#26143] opened 2020-10-24 01:22 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.3
  * 10.1.4
  * 11.0.0-beta.13
  * 11.0.0-beta.17
  * 11.0.0-beta.19
* **Operating System:**
  * macOS 11.0 Beta (20A5395g)
  * macOS 11.0.1 Release (20B28)
* **Last Known Working Electron version:**
  * works on macOS 10.15 Catalina

### Expected Behavior

If I call `require('child_process').spawn('ls', ['.'])`, it should return quickly (<10ms).

Measurable with:
```javascript
const { spawn } = require('child_process');
const start = Date.now();
spawn('ls', ['.']);
console.log(`spawn sync time: ${Date.now() - start}`);
```

### Actual Behavior

If run in a renderer process with `nodeIntegration: true`, it takes 300+ ms. When used with `ffmpeg` (our real-world case), we're seeing it go as long as 2-3 seconds, which leads me to think it's related to the binary size/code signing?

### To Reproduce

To reproduce the bug, you'll need:
* macOS 11 Beta
* an Apple Developer code-signing certificate

Or you can download the version I code-signed: https://github.com/descriptinc/electron-spawn-perf-bug/releases/tag/1.0.0

Repo: https://github.com/descriptinc/electron-spawn-perf-bug
If you want to build/run it locally:
```sh
$ git clone https://github.com/descriptinc/electron-spawn-perf-bug.git
$ yarn install
$ yarn build
$ dist/mac/electron-spawn-bug.app/Contents/MacOS/electron-spawn-bug
```

### Screenshots

<img width="912" alt="image" src="https://user-images.githubusercontent.com/21952/97063176-feb97280-1552-11eb-8ed3-023b427b4351.png">

### Additional Information

I'm not sure if this is an Electron, Electron Builder, or Big Sur bug.

**Comment by pdesantis** [comment] 2020-10-26 18:30
I can reproduce these results. Here are my ranges of spawn durations (in ms) on Catalina & Big Sur machines:

## macOS Catalina 10.15.7 (19H2)
| Main: `spawn ls` | Main: `ls exit` | Renderer: `spawn ls` | Renderer: `ls exit` |
| --: | --: | --: | --: |
| 1-3 | 111-126 | 1-3 | 19-31 |

## macOS Big Sur 11.0 Beta (20A5395g)
| Main: `spawn ls` | Main: `ls exit` | Renderer: `spawn ls` | Renderer: `ls exit` |
| --: | --: | --: | --: |
| 3-10 | 224-275 | 282-285 | 308-2825 |

Both of these samples were taken on a MacBook Pro (15-inch, 2016), 2.9 GHz Quad-Core Intel Core i7, 16 GB RAM
They were using Node.js 12.18.3, Chromium 87.0.4280.11, and Electron 11.0.0-beta.13.

**Comment by marcello3d** [comment] 2020-10-27 19:03
Just tested: this also happens on Electron v11.0.0-beta.17

**Comment by marcello3d** [comment] 2020-10-27 22:50
I'm not sure if this is helpful, but I ran contentTracing and got some profile snapshots with the signed (slow) and signed (fast) versions.
- [electron-trace-not-signed.zip](https://github.com/electron/electron/files/5448526/electron-trace-not-signed.zip)
- [electron-trace-signed.zip](https://github.com/electron/electron/files/5448527/electron-trace-signed.zip)

You can open these up in Chrome by going to `chrome://tracing` and loading them in (after unzipping).

But I don't know how to read it.

**Comment by nornagon** [comment] 2020-10-30 21:24
This seems likely to be a Big Sur bug. Electron doesn't do anything special related to code signing.

It's surprising that the behavior is different in the renderer process, though...

**Comment by marcello3d** [comment] 2020-10-31 00:38
@nornagon: yea that's the part that also stood out to me—and the process we're running `ls` isn't changing status (presumably codesigned by Apple?).

Is there anything special about `child_process` in a renderer process? Is it going through IPC?

**Comment by pdesantis** [comment] 2020-11-06 20:31
This is still reproducible on macOS 11.0.1 Beta (20B5022a) and Electron 11 beta 19

I filed a bug report with Apple (http://openradar.appspot.com/radar?id=5027087777792000), will post here if there are any updates.

@MarshallOfSound is there any chance this is related to your comment here https://github.com/electron/electron/issues/14011#issuecomment-461655158? These issues are similar in that something in the renderer process is taking much longer than the same action in the main process.

**Comment by marcello3d** [comment] 2020-11-13 23:45
It looks like a few VS Code users are now hitting this as they upgrade to Big Sur: https://github.com/microsoft/vscode/issues/105446

**Comment by implausible** [comment] 2020-11-16 20:13
GitKraken users are also affected.

**Comment by pdesantis** [comment] 2020-11-16 23:40
There's been speculation in the VSCode issue (https://github.com/microsoft/vscode/issues/105446#issuecomment-727642247) that maybe this is due to Apple's dev certificate checks, however that doesn't seem likely since: 
1. This problem still happens while offline
2. The main process avoids this issue

**Comment by srubin** [comment] 2020-11-18 04:14
Per this comment https://github.com/microsoft/vscode/issues/105446#issuecomment-729390368 - I just confirmed that the [test project](https://github.com/descriptinc/electron-spawn-perf-bug) has the slowndown on the browser (main) process when using the latest nightly electron build.

**Comment by deepak1556** [comment] 2020-11-18 04:58
A suggestion from @davidzech to fix this issue https://github.com/microsoft/vscode/issues/105446#issuecomment-729274600

> It would be nice if libuv used posix_spawn instead.

**Comment by deepak1556** [comment] 2020-11-18 05:07
I think that is the correct solution moving forward, looked a bit at what chromium uses for spawning child processes based on a question from @MarshallOfSound and chromium does use `posix_spawn` https://source.chromium.org/chromium/chromium/src/+/master:base/process/launch_mac.cc

**Comment by marcello3d** [comment] 2020-11-19 17:00
@deepak1556 is the idea that https://github.com/libuv/libuv/issues/2133 needs to be fixed to resolve this? Or is this something that would be patched in Electron?

**Comment by deepak1556** [comment] 2020-11-19 20:48
The above libuv issue tracks updating fork calls on linux too, which is outside our scope for current issue. I am working on creating a minimal repro and opening an issue with libuv to get a fix just for macOS, I would be happy if we are able to have fix atleast for big sur versions and above. Will update here once I open up an issue in libuv.

**Comment by jhhl** [comment] 2020-11-19 21:25
Using yarn start on an Apple Silicon mini. 
 file  dist/mac/electron-spawn-bug.app/Contents/MacOS/electron-spawn-bug 
dist/mac/electron-spawn-bug.app/Contents/MacOS/electron-spawn-bug: Mach-O 64-bit executable x86_64

![exited in 233](https://user-images.githubusercontent.com/4635997/99725863-baeb5780-2a83-11eb-9587-06d83b0b7c3c.png)

**Comment by srubin** [comment] 2020-11-19 21:30
@jhhl Those results are expected. You need to sign the binary in order to see the slowdown.

**Comment by deepak1556** [comment] 2020-11-21 10:19
Upstream issue : https://github.com/libuv/libuv/issues/3050

**Comment by pdesantis** [comment] 2020-12-15 20:34
My colleague has been working on a patch for libuv. It currently has a breaking change, but depending on how you use child processes it may not affect you (see PR below for more details).

We've done a custom Electron build with this libuv patch, which has solved the Big Sur issue for us. If anyone else is experiencing the issue, you can try patch https://github.com/electron/electron/pull/27026

P.S. Many thanks for https://github.com/electron/build-tools, that made the build process simple!

**Comment by calrsom** [comment] 2021-02-18 22:40
Just a heads up, the upstream issue was reopened because the PR was reverted: https://github.com/libuv/libuv/issues/3050#issuecomment-778495429

**Comment by mifi** [comment] 2021-04-14 04:12
FWIW the issue also exists with electron 9.4.4, but 8.5.5 does not have the issue. It's blocking me from upgrading my app from electron 8.

**Comment by nomagick** [comment] 2021-05-12 08:35
Any news on this ?

This is severe.
However libuv is not motivated enough to fix this issue.

Vscode has kept this patch in their code.

It's Electron being the most affected.

How about revert the revert?

**Comment by vdeantoni** [comment] 2021-05-12 18:22
As a workaround, I downgraded Electron to version 11.4.6, and the slowness is gone. When running version 12, CPU usage would often go to 100% for a second or so when `spawn` was called.

The weird thing was that for me even when calling `spawn` from the main process the UI would freeze.  I also tried tried calling from a web worker, same problem.

**Comment by KishanBagaria** [comment] 2021-05-26 18:23
This is also present in Electron v13. Is there a workaround other than disabling hardened runtime and downgrading?

**Comment by starpit** [comment] 2021-05-30 17:34
Oddly, on Electron 10, we only saw this with signed builds (on only Big Sur). With Electron 13, we see this even for development builds.

**Comment by edenhermelin** [comment] 2021-07-03 17:50
any updates on this issue?
It seems as everything was fine when I used version `11.4.7` (on BigSur, both signed and unsigned).
But on versions 12 and 13 every spawnSync / execSync locks the renderer..

**Comment by cupcakearmy** [comment] 2021-07-03 17:56
> any updates on this issue?
> It seems as everything was fine when I used version `11.4.7` (on BigSur, both signed and unsigned).
> But on versions 12 and 13 every spawnSync / execSync locks the renderer..

Can confirm the same behaviour. Downgraded to 11 and everything is fine but seems like a werid fix xD

**Comment by edenhermelin** [comment] 2021-07-03 18:30
@cupcakearmy I hope that it will be fixed before Electron v11 will reach `end-of-support`  🥲

**Comment by seb-mtl** [comment] 2021-07-03 19:01
I found the `posix_spawn` implementation quite promising despite the failure in the test suite of `libuv`. I would like to dig more into this to see what's happening there. Since Electron brings its own(?) node implementation I was expecting a specific node/libuv version being referenced somwhere in the config files. Could someone give me a brief update on this?

**Comment by MarshallOfSound** [comment] 2021-07-03 21:23
@seb-mtl 

Node version: https://github.com/electron/electron/blob/main/DEPS#L19-L20
Patches we apply on top of Node: https://github.com/electron/electron/tree/main/patches/node

**Comment by seb-mtl** [comment] 2021-07-14 03:06
Today I had some time to look into the issue. Because the issue touches Electron, node and libuv I would like to use this post to quickly recap the current situation. Please correct me if anything is wrong. 

## Chronology

1. The `spawn` performance bug got reported
2. The fix [#27026](https://github.com/electron/electron/pull/27026) got commited to libuv that uses [posix_spawn](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/posix_spawn.2.html).
3. The fix got reverted [here](https://github.com/electron/electron/commit/77525acf798e8fe4915be29df27baa9b6edcb3d8) due to a unit-test failure in the libuv suite.
4. VScode kept the fix nonetheless

## Recap

Last working version for me: **Electron v8.5.5**
First broken version for me: **Electron v9.0.0-beta.1**

According to [this](https://github.com/electron/releases) release table here are some version details:

|Tag|Published|npm|Prerelease|Module Version|Node|Chrome|Downloads|
|----|----|----|----|----|----|----|----|
|[v9.0.0-beta.1](https://github.com/electron/electron/releases/tag/v9.0.0-beta.1)|2020-02-10||yes|76|12.14.1|82.0.4048.0|2082|
|[v8.5.5](https://github.com/electron/electron/releases/tag/v8.5.5)|2020-11-18|8-x-y|no|76|12.13.0|80.0.3987.163|272251|

The error seems to be in libuv. Since libuv is located in [deps/uv/](https://github.com/nodejs/node/tree/v12.13.1/deps/uv) of node we can diff the two node versions **v12.13.0** and **v12.14.1**: https://github.com/nodejs/node/compare/v12.13.0...v12.14.1

**Comment by seb-mtl** [comment] 2021-07-14 03:12
Recap done, let's go on. There are 2 possible fixes:

1. Find the change in libuv that causes the problem
2. Fix the issue that causes the libuv unit-tests to fail.

Personally I would like to find the issue first in libuv. On the other side, there don't seem to be any obvious changes in `deps/uv/` (also not in `deps/uv/unix`) that look suspicious. Ideas?

**Comment by deepak1556** [comment] 2021-07-14 04:06
Thanks for looking into this, to clarify some points

> The fix got reverted here due to a unit-test failure in the libuv suite.

Nope it was reverted because of unittest failures in node test suite, you can refer to https://github.com/libuv/libuv/pull/3107#issuecomment-781585353 for discussions along what specific tests failed. I got most of them passing, the only one I couldn't fix is the `test.parallel/test-child-process-spawnsync-validation-errors` where it tries to test uid option. If this can be fixed then `posix_spawn` change can be given another attempt in libuv.

> VScode kept the fix in their repo

vscode does not rely on uid, gid options of child_process module, so I decided to try the patch. But over user testing, we found two new issues in the implementation,

1) https://github.com/microsoft/vscode-remote-release/issues/4630 - the manual path resolution implementation used for `posix_spawn` path https://github.com/descriptinc/electron/blob/2f9ed1de9f8e533c0458c83fd2bec7b4cfb01cf0/patches/node/darwin_libuv_use_posix_spawn.patch#L413-L439 differed from `execvp` in that it started respecting `ENOTDIR` errors.

2) https://github.com/microsoft/vscode/issues/118267 - cwd option of child_process module didn't work well in some situations, turned out to be a bug in `posix_spawnp` implementation https://github.com/microsoft/vscode/issues/118267#issuecomment-840122005

Attaching the final version of the patch which we use in vscode 
[use_posix_spawn_to_spawn_subprocesses_on_macos.patch.zip](https://github.com/electron/electron/files/6813387/use_posix_spawn_to_spawn_subprocesses_on_macos.patch.zip)


> Fix the issue that causes the libuv unit-tests to fail.

Yup the ideal next step is to get the node test suite passing with the `posix_spawn` change. Also it would be best to test with vanilla node but if you are running it for node built alongside electron then use this script https://github.com/electron/electron/blob/main/script/node-spec-runner.js to ignore tests that are known to be broken.

I am unassigning myself from this bug due to lack of cycles, but happy to assist were possible.

**Comment by seb-mtl** [comment] 2021-07-14 14:30
Great insights, and thanks for the clarification. I updated/corrected my post accordingly

**Comment by LabhanshAgrawal** [comment] 2021-07-23 12:55
@deepak1556 Where can we keep track of the patch used in VScode (and any guide to apply it). Thinking of trying it out for [hyper](https://github.com/vercel/hyper).
Thanks

**Comment by deepak1556** [comment] 2021-07-26 18:19
There is no public endpoint to track the patch, if you are building electron locally then the patch should cleanly apply on `src/electron`, no special steps required. Also the patch should be exercised with caution when using with apps, it was posted as a starting point for anyone interested in upstreaming.

**Comment by KishanBagaria** [comment] 2021-08-05 08:39
@deepak1556 since vscode is already applying the patch, can we download the patched and prebuilt electron binaries from somewhere?

**Comment by KishanBagaria** [comment] 2021-08-05 17:01
Patch failed:

```
Applying: src: add missing context scopes
Applying: Use posix_spawn to spawn subprocesses on macOS
error: invalid object 100644 9e9183e9d8a1eb81659154b660812693cf7e441f for 'patches/node/.patches'
error: Repository lacks necessary blobs to fall back on 3-way merge.
Patch failed at 0039 Use posix_spawn to spawn subprocesses on macOS
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Traceback (most recent call last):
  File "/Users/distiller/project/src/electron/script/apply_all_patches.py", line 34, in <module>
    main()
  File "/Users/distiller/project/src/electron/script/apply_all_patches.py", line 30, in main
    apply_patches(json.load(config_json))
  File "/Users/distiller/project/src/electron/script/apply_all_patches.py", line 14, in apply_patches
    git.import_patches(repo=repo, patch_data=patch_from_dir(patch_dir),
  File "/Users/distiller/project/src/electron/script/lib/git.py", line 84, in import_patches
    am(repo=repo, **kwargs)
  File "/Users/distiller/project/src/electron/script/lib/git.py", line 72, in am
    raise RuntimeError("Command {} returned {}".format(command,
RuntimeError: Command ['git', '-C', 'src/third_party/electron_node', '-c', 'user.name=Electron Scripts', '-c', 'user.email=scripts@electron', '-c', 'commit.gpgsign=false', 'am', '--3way'] returned 128

Hook 'python3 src/electron/script/apply_all_patches.py src/electron/patches/config.json' took 110.83 secs


Exited with code exit status 2
CircleCI received exit code 2
```

**Comment by flotwig** [comment] 2021-08-19 17:29
I will email 10 funny cat GIFs to whoever fixes this bug. It's causing some issues for our users. For now, we are [working around](https://github.com/cypress-io/cypress/pull/17807) this slowdown by spawning a bare Node.js process and then using that process to run additional spawns, but this is pretty ugly and still adds a couple of seconds to execution time due to the 1 spawn call made from Electron.

**Comment by KishanBagaria** [comment] 2021-08-21 20:30
After battling with CircleCI config, I was able to build Electron v13.2.1 with the patch @deepak1556 linked (the one used in VS Code).

Released here:
https://github.com/KishanBagaria/electron/releases/tag/v13.2.1

CI download links:
https://app.circleci.com/pipelines/github/KishanBagaria/electron/11/workflows/990e9f15-c9c3-46ae-b643-9124638b16df/jobs/56/artifacts (dist.zip is electron-v13.2.1-darwin-x64.zip)
https://app.circleci.com/pipelines/github/KishanBagaria/electron/11/workflows/990e9f15-c9c3-46ae-b643-9124638b16df/jobs/55/artifacts (dist.zip is electron-v13.2.1-darwin-arm64.zip)

I'm running this for patching my local dev build in node_modules:
```js
const ELECTRON_GET_OPTIONS = {
  mirror: 'https://github.com/KishanBagaria/electron/releases/download/',

  // override the default cache path to avoid accidentally using the regular binaries https://github.com/electron/get#how-it-works
  cache: path.join(os.homedir(), 'Library/Caches/electron/patched'),
}
async function downloadPatchedElectron() {
  const electronGet = require('@electron/get')
  console.log('downloading patched electron')
  const zipPath = await electronGet.download(pkg.devDependencies.electron.slice(1), {
    cacheRoot: ELECTRON_GET_OPTIONS.cache,
    mirrorOptions: {
      mirror: ELECTRON_GET_OPTIONS.mirror,
    },
  })
  console.log('downloaded patched electron to', zipPath)
  const unzipDirPath = path.join(ROOT_DIR_PATH, 'node_modules/electron/dist')
  shell.rm('-rf', unzipDirPath)
  shell.exec(`unzip -q "${zipPath}" -d "${unzipDirPath}"`)
}
```

And passing these CLI flags to electron-builder to use the patched build for packaging:
`-c.electronDownload.mirror ${ELECTRON_GET_OPTIONS.mirror}v -c.electronDownload.cache ${ELECTRON_GET_OPTIONS.cache}`

**Comment by KishanBagaria** [comment] 2021-09-02 16:52
@deepak1556 can you post `use_posix_spawn_to_spawn_subprocesses_on_macos.patch` for Electron v14? Running into some merge conflicts.

**Comment by deepak1556** [comment] 2021-09-08 20:45
Might want to wait on https://github.com/libuv/libuv/pull/3257 instead. Thanks!

**Comment by octalmage** [comment] 2021-09-22 18:33
Does anyone know of a solution that does not involve compiling and managing a fork of Electron, or downloading a pre-built application? 

What about the possibility of using the Electron shipped with VS Code?

**Comment by mifi** [comment] 2021-09-23 03:32
Two other workaround solutions:
- Running spawn instead from the main process (not renderer)
- Downgrading to electron 8

**Comment by ikkisoft** [comment] 2021-09-23 19:12
While performing security engagements on behalf of my customers I am discovering more and more apps that are behind the latest Electron stable release due to the fact that they have to maintain a separate fork of Electron (hence upgrading is a lot more work). While this issue is not strictly security related, this is clearly affecting their security posture.

**Comment by marcello3d** [comment] 2021-09-23 19:35
@mifi Last we tested, running from main process doesn't help on Electron 12+ (see https://github.com/electron/electron/issues/26143#issuecomment-729393664). 

It looks like Electron 8 is no longer supported/maintained: https://www.electronjs.org/releases/stable?version=8#end-of-support-for-8xy-855

**Comment by NicolasLacombe** [comment] 2021-10-20 18:06
FYI, we're seeing the same behaviour on the beta release of macOS Monterey 12.0.1. In 5 days Electron child_process will be slugish for the last two releases of macOS, without any fix in sight.

**Comment by rndlaine** [comment] 2021-10-29 19:55
Do you know if this is only related to macOS? Because I'm experimenting similar issues on both Linux and Windows. I have a forked process running which is roughly 300ms slower than when its not running from the forked Electron's main process. Any ideas on what might cause this issue?

**Comment by edenhermelin** [comment] 2021-12-04 20:56
Did anyone managed to workaround this issue?

**Comment by NicolasLacombe** [comment] 2021-12-04 21:34
We managed to fix it by writing and running a native SWIFT client that will run command on behalf of Electron (through XPC communication). Of course the whole things needs to be secure, so runtime check of signature and all that fun stuff. 

Such a hassle but what are you going to do ? People are finally switching to BigSur & Monterey, and if your application run a lot of child_process command, their experience is horrible (if usable at all).

Right now this issue is a big thorn in Electron's foot that will keep growing as people switch to BigSur & Monterey, and
the lack of commitment from big dev companies to help fix libuv is surprising. Unfortunately it seems they'd rather fork Electron and apply the original libuv fix, rather than help fix the underlying issues for the community.

**Comment by GitFiend** [comment] 2021-12-05 02:44
I've managed to work around this bug by writing a native app shell for the Mac version (Not using Electron). The app uses WKWebView for renderer and bundled node js for the backend. This is quite a large app and this shell required <1000 lines of Swift. 

This approach is probably not for everyone as it required learning enough Swift to handle JSON, debugging message passing, async etc. It would also depend on your architecture. I had recently refactored and removed electron/remote from my app which made it easier.

**Comment by pdkovacs** [comment] 2021-12-05 14:15
How come that this seems to be an Electron-only issue? NodeJS also uses libuv doesn't it?

**Comment by mifi** [comment] 2021-12-05 15:57
perhaps it will also happen with node.js if signing the `node` binary

**Comment by pdkovacs** [comment] 2021-12-05 16:01
> perhaps it will also happen with node.js if signing the `node` binary

Oh yes, sorry, I totally forgot is related to signing. This issue has been dragging on so long and got stuck on some MacOS/Apple system call bug (unrelated to signing).

**Comment by GitFiend** [comment] 2021-12-05 19:59
> perhaps it will also happen with node.js if signing the `node` binary

I've bundled the app, signed it and the included node binary and also notarized it (according to the Xcode UI). I'm not experiencing the issue on my machine, though I want to do more testing on other macs.

**Comment by mifi** [comment] 2021-12-06 06:45
> I've bundled the app, signed it and the included node binary and also notarized it (according to the Xcode UI). I'm not experiencing the issue on my machine, though I want to do more testing on other macs.

and the signed node binary is the one calling `child_process.spawn`?

**Comment by GitFiend** [comment] 2021-12-06 07:51
Yes. It didn't occur to me that this would be a problem as I'm pretty sure nodejs is signed and notarized on Mac.

**Comment by MMcKester** [comment] 2021-12-14 04:13
I am trying to build Electron 14 with the **libuv** patch. Could anyone share some lights how I can apply the patch? Do I first build libuv with the patch and then build Electron with it? Thanks!

**Comment by KishanBagaria** [comment] 2021-12-14 08:52
@MMcKester https://github.com/KishanBagaria/electron/releases/

**Comment by starpit** [comment] 2022-01-16 23:46
@KishanBagaria thanks so much for providing these builds. We have just tried your 13.2.1 build. This combined with node-pty 0.11.0-beta17 (0.11.0 has [a matching fix for porting to posix_spawn](https://github.com/microsoft/node-pty/pull/487)) seems to work!

Is there a process for updating your builds? e.g. your 13.x.y is 13.2.1, whereas the latest 13.x.y is 13.6.6. 🙇

**Comment by mifi** [comment] 2022-01-18 19:23
Did some more testing with electron 16.07. Some observations:

- the app doesn't need to be signed, also happens with `npx electron .`
- the slowdown happens when child_process.spawn is called
  - from the renderer
  - from main process
  - from a worker_thread
  - from a long-running spawned child_process, every time it calls child_process
- does **not** happen in node.js (at least v16.13.0), **has to be electron.**
- It doesn't just lock up the renderer, it also locks up the main process and **the whole macos** (whole macos UI get sluggish, mouse cursor starts lagging)
- more prominent effect when running multiple spawn in parallel (>=4)

I created a relatively simple reproducible example:

```js
// worker.js

const workerpool = require('workerpool');
const childProcess = require('child_process');

workerpool.worker({
  spawn: async () => new Promise((resolve, reject) => {
    const ps = childProcess.spawn('ls', { stdio: 'ignore' });
    ps.on('exit', resolve);
    ps.on('error', reject);
  }),
});
```

```js
// lockup-test.js

const workerpool = require('workerpool');

const pool = workerpool.pool(__dirname + '/worker.js', {
  workerType: 'process',
  minWorkers: 'max',
  maxWorkers: 5,
  onCreateWorker: () => console.log('onCreateWorker'),
});

const spawn = (...args) => pool.exec('spawn', args);

(async () => {
  try {
    for (;;) {
      await Promise.all(Array(4).fill(0).map(async () => {
        console.log('spawn');
        await spawn();
        await new Promise((resolve) => setTimeout(resolve, 30));
      }));
    }
  } catch (err) {
    console.error(err);
  }
})();
```

Now run `npx electron lockup-test.js` and observe a complete slowdown of the system and `spawn` being printed very slowly.

If you instead run `node lockup-test.js`, there is no slowdown and `spawn` gets printed out rapidly.

big sur 11.6. because the whole system slows down it strengthens the hypothesis that this is really a macos bug (not just electron)

**Comment by astoilkov** [comment] 2022-01-20 12:15
Hey, @nornagon @zcbenz @MarshallOfSound.

Sorry for the intrusion of directly mentioning you. However, I am following this issue for more than a year now and I still don't know what you think and if you have plans for it.

I'm asking because we are blocked and can't update. I see a lot of people here in the same situation. Also, correct me if I'm wrong, but Microsoft's own two products — VSCode and GitHub Desktop are dealing with the same problem.

**Comment by KishanBagaria** [comment] 2022-01-20 12:17
they're working on fixing this here: https://github.com/libuv/libuv/pull/3257

**Comment by mifi** [comment] 2022-03-03 01:58
This has now been fixed in libuv 🎉 hoping for a release soon!

https://github.com/libuv/libuv/pull/3257

**Comment by nornagon** [comment] 2022-03-18 18:13
We should consider backporting this. Node.js hasn't yet updated their version of libuv to include the fix, but it affects Electron significantly more heavily than Node, and I think the fix is probably worth backporting to supported Electron versions (>= 15.x, 14.x is currently security-only).

**Closed** 2022-03-23 13:30 UTC
Labels: platform/macOS, performance :checkered_flag:, bug :beetle:, blocked/upstream ❌, bug/os-regression, 13-x-y, 14-x-y, 15-x-y

**Comment by cupcakearmy** [comment] 2022-03-23 14:34
Awesome 🚀 Thanks a lot!
What electron version will have the fix included?

**Comment by KishanBagaria** [comment] 2022-03-24 19:40
[Electron v18.0.0-beta.6](https://github.com/electron/electron/releases/tag/v18.0.0-beta.6) was just released with the fix.

**Comment by dreamthen** [comment] 2022-03-28 20:26
Nice!Delicious!

**Comment by KishanBagaria** [comment] 2022-03-29 06:59
[Electron v16.2.0](https://github.com/electron/electron/releases/tag/v16.2.0) and [Electron v17.3.0](https://github.com/electron/electron/releases/tag/v17.3.0) have been released with the fix.

**Comment by Nick-Lucas** [comment] 2022-03-29 08:12
Is there any chance of making an exception to the support cycle and backporting further, back to 11 and up?

The reason I say this, is this issue has been blocking upgrades in projects for so long that there are now other issues preventing upgrades to the latest releases such as context aware modules support, and the dropping of Spectron. It's become a mammoth task to move so far forward in one jump.

**Comment by MarshallOfSound** [comment] 2022-03-29 09:53
The support cycle isn't something that we can make exceptions to easily even if we wanted to (which in this case I'd still be against).

Older versions like 11 were built using CI images / VMs / compile clusters that aren't running / available anymore and modifying / spinning up infrastructure just for a one off release would take an unreasonable amount of effort.  15-x-y is as far back as this one will go.

**Comment by Nick-Lucas** [comment] 2022-03-29 10:00
15 might be workable. It's been a while since I was investigating this, so correct me if I'm wrong, but that version still has the necessary features for running non-context aware modules like node-pty, and also still has a Spectron release, I believe?

**Comment by clemp6r** [comment] 2022-03-29 11:12
@Nick-Lucas Spectron does not support Electron 14+
https://www.electronjs.org/blog/spectron-deprecation-notice

**Comment by Nick-Lucas** [comment] 2022-03-29 11:16
The GitHub repo says Spectron supports up to 17 in the versions table:

https://github.com/electron-userland/spectron

Is there more nuance that the table doesn't convey?

**Comment by clemp6r** [comment] 2022-03-29 11:52
Indeed. The blog article may be outdated or unclear.

**Comment by daqi** [comment] 2022-04-19 04:09
![image](https://user-images.githubusercontent.com/1715916/163918195-7e8dd266-5c49-43bf-8b56-92f0fe6500db.png)
![image](https://user-images.githubusercontent.com/1715916/163918222-d0ef035f-6bf5-4480-b7a5-075c1d910080.png)
In my test, rerender ok, but main not ok.
