### ISSUE TITLE
Blurry rendering on Mac OS X after switching from non-retina display to retina display

### ISSUE THREAD

**Issue by aterenin** [electron/electron#21393] opened 2019-12-05 11:35 UTC
NOTE: I previously reported this at #21229 which was closed after someone was unable to reproduce it. I insist that this bug *is* present, and *is* an Electron bug, because it occurs on Caprine, Slack, WhatsApp, VS Code, and my own home-built Google Photos desktop app. After the issue was closed, @nielsvandepas was able to reproduce the bug, but the issue was not reopened after commented. I'm not sure why this issue couldn't be reproduced using the steps I've given, so I'm attaching screenshots. Sorry for duplicate - I don't have permissions for reopening the other issue.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7
* **Operating System:**
Mac OS X
* **Last Known Working Electron version:**
N/A

### To Reproduce
1. Connect MacBook to a non-retina display - in my case, a 40" 4k display connected via DisplayPort with standard scaling (i.e. full resolution, not retina-like 1080p scaled up to 4k).
2. Close the MacBook lid.
3. Open an Electron app.
4. Unplug the display.
5. Open the MacBook lid. Electron app is blurry.

### Screenshots

<img width="311" alt="Screen Shot 2019-12-05 at 11 31 43 AM" src="https://user-images.githubusercontent.com/4722472/70231858-12999180-1753-11ea-8955-9ce04d9b2b32.png">
<img width="300" alt="Screen Shot 2019-12-05 at 11 32 52 AM" src="https://user-images.githubusercontent.com/4722472/70231870-19280900-1753-11ea-926e-3fb8bc8563c7.png">
<img width="389" alt="Screen Shot 2019-12-05 at 11 32 27 AM" src="https://user-images.githubusercontent.com/4722472/70231899-2644f800-1753-11ea-9e09-07c712f3abe9.png">
<img width="360" alt="Screen Shot 2019-12-05 at 11 33 12 AM" src="https://user-images.githubusercontent.com/4722472/70231905-29d87f00-1753-11ea-8715-f3b1437538d6.png">

**Comment by ckerr** [comment] 2019-12-05 18:55
Alexander, to help narrow down the problem, could you see if the same blurry rendering occurs under the same circumstances in Chrome 78 by itself?

In addition, could you see if the problem persists in the Electron 8 betas (e.g. by using [electron-fiddle](https://github.com/electron/fiddle/), choosing an 8 beta, and running demo code)?

**Comment by EllDoubleYew** [comment] 2019-12-06 16:16
I see this issue a lot on 7, but the actual steps to reproduce it are hard for me to pin down: 

- It usually happens in the morning when I first open up my laptop and plug it into my external monitor.
- Dragging the window over to my external display and back to my Retina display will bring my window back to the correct resolution. 
- Even after disconnecting the external display I still see the low resolution window on my Retina display. If I quit the application and re-open it it is still at a low resolution. I have to either restart my machine or reconnect to an external display to bring it back to the correct resolution. 
- I'm using one 1080p secondary display and a 2880 x 1880 Retina display on my MBP.

Wish I could give more sure-fire steps to reproduce but I can't find a method that always results in finding the bug.

**Comment by karipov** [comment] 2019-12-13 21:36
Hi,

I'd like to add on to this, as I've experienced this with both VS Code, but more interestingly the Spotify Desktop App which uses the Chromium Embedded Framework. Could it be deeper than just an electron issue?

I'm seeing this after connecting my 2K 16:10 MacBook 13" to a Dell U2518D (also 2K but 16:9).

**Comment by obahareth** [comment] 2019-12-24 09:06
I believe the root cause might be [this Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1021340&can=1&q=catalina%20fuzzy&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).

**Comment by eric1iu** [comment] 2020-01-15 17:51
I've experienced the same issue with Slack and VS Code on my Catalina mbp. As a workaround without restart the apps, I open System Preferences / Display do a resolution scaled change and revert it back.

**Comment by deepak1556** [comment] 2020-01-22 23:34
Thanks @obahareth , yes thats the issue, have backported the patch https://github.com/electron/electron/pull/21872

**Comment by deepak1556** [comment] 2020-01-23 19:49
Fixed in https://github.com/electron/electron/commit/c7bb1d0300fc40b8a6019ca3d07e26a1f1f90064

**Closed by deepak1556** 2020-01-23 19:49 UTC
Labels: 7-1-x, bug :beetle:, platform/macOS
