### ISSUE TITLE
[Bug]: ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)

### ISSUE THREAD

**Issue by Zankel-Engineering** [electron/electron#36237] opened 2022-11-02 12:21 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 10.0.19041, Windows 10 10.0.19043, Windows 10 10.0.19044

### What arch are you using?

x64

### Expected Behavior

Have no errors in regards to the cache moving.

### Actual Behavior

Errors in regards to the cache moving

### Additional Information

Hello gentleman and gentlewoman,

we have the issue that our electron based application has problems when we start different instance of it, which are going again different origins. It seems that issues with moving the cache occur.

Here are our logs:

17:28:07.591 > Host retrieved from .env file. Host is https://cockpit-frontend.kuc.abn.ahs.dev/
[5676:0905/172807.690:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)
[5676:0905/172807.690:ERROR:cache_util.cc(146)] Unable to move cache folder C:\Users\mf\AppData\Roaming\kvaipro-cockpit-client\GPUCache to C:\Users\mf\AppData\Roaming\kvaipro-cockpit-client\old_GPUCache_000
[5676:0905/172807.690:ERROR:disk_cache.cc(186)] Unable to create cache
[5676:0905/172807.690:ERROR:shader_disk_cache.cc(612)] Shader Cache Creation failed: -2
[2480:0905/172811.144:ERROR:cache_util_win.cc(20)] Unable to move the cache: Zugriff verweigert (0x5)
[2480:0905/172811.144:ERROR:cache_util.cc(146)] Unable to move cache folder C:\Users\mf\AppData\Roaming\kvaipro-cockpit-client\Cache\Cache_Data to C:\Users\mf\AppData\Roaming\kvaipro-cockpit-client\Cache\old_Cache_Data_000
[2480:0905/172811.144:ERROR:disk_cache.cc(186)] Unable to create cache
[7908:0905/173007.706:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is

The problem seems to only occur, when we have as said multiple instances of electron running.

Thanks in advance for your time,

Sebastian Zankel

**Comment by codebytere** [comment] 2022-11-08 11:39
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed** 2023-01-10 02:04 UTC
Labels: bug :beetle:, blocked/need-repro

**Comment by DarkSynx** [comment] 2023-03-09 05:26
[21920:0309/092027.547:ERROR:cache_util_win.cc(20)] Unable to move the cache: AccÞs refusÚ. (0x5)
[21920:0309/092027.547:ERROR:cache_util_win.cc(20)] Unable to move the cache: AccÞs refusÚ. (0x5)
[21920:0309/092027.553:ERROR:disk_cache.cc(205)] Unable to create cache
[21920:0309/092027.553:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2
[21920:0309/092027.554:ERROR:disk_cache.cc(205)] Unable to create cache
[21920:0309/092027.554:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2
[1140:0309/092027.805:ERROR:cache_util_win.cc(20)] Unable to move the cache: Le processus ne peut pas accÚder au fichier car ce fichier est utilisÚ par un autre processus. (0x20)
[1140:0309/092027.805:ERROR:disk_cache.cc(205)] Unable to create cache
[21920:0309/092033.576:ERROR:CONSOLE(1)] "TypeError: Failed to fetch", source: devtools://devtools/bundled/entrypoints/main/main.js (1)
[21920:0309/092048.075:ERROR:CONSOLE(1)] "Request Storage.getStorageKeyForFrame failed. {"code":-32602,"message":"Frame tree node for given frame not found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[21920:0309/092048.076:ERROR:CONSOLE(1)] "Request Storage.getStorageKeyForFrame failed. {"code":-32602,"message":"Frame tree node for given frame not found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[2824:0309/092227.697:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
![image](https://user-images.githubusercontent.com/9467611/223928430-a903d19f-da71-428d-80f8-4c795e162d33.png)

**Comment by jiereal** [comment] 2024-09-20 09:26
有进展吗？
