### ISSUE TITLE
Accelerator on Windows 'Ctrl+Shift+Plus'  appears in menu as 'Ctrl+Shift+='

### ISSUE THREAD

**Issue by vrbsm** [electron/electron#15597] opened 2018-11-06 18:32 UTC
* Output of `node_modules/.bin/electron --version`: v3.0.8
* Operating System (Platform and Version): Windows 10 (OS Build 17134.345)

**Expected Behavior**
The accelerator must show: **Ctrl+Shift++**

**Actual behavior**
When this accelerator is used: '**Ctrl+Shift+Plus**'  appears in the menu as '**Ctrl+Shift+=**'

**To Reproduce**

- Clone https://github.com/vrbsm/example-accelerator-bug.git
- Run npm run start

**Code**
```
const template = [
    {
      label: "Bug",
      submenu: [
        { role: "copy" },
        { type: "separator" },
        { label: "testing", accelerator: "CmdOrCtrl+Shift+Plus"},
      ]
    }
  ];
  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);
```

**Screenshots**
![bug](https://user-images.githubusercontent.com/9887288/48084652-7283d880-e1df-11e8-9bb1-228d58ac0320.png)

**Comment by brenca** [comment] 2018-11-09 20:46
I think this is intended behaviour, since there is no dedicated `+` key on most keyboards (the numpad key is a different story), that key is actually `Shift+=`. You should get the same accelerator if you set the accelerator to `CmdOrCtrl+Plus`.
Gonna /cc @MarshallOfSound on this to be sure

**Comment by MarshallOfSound** [comment] 2018-11-09 23:07
Yeah ignoring the numpad there is no actual way do do the key combination `Ctrl+Shift+Plus`

In order for the `+` key to be hit you already need to be pressing Shift, and you can't press shift twice.  😄 I.e. `Ctrl+Shift+Plus` is equal to `Ctrl+Shift+Shift+=` which is like not a thing.

Closing this out as `wontfix`.

**Closed by MarshallOfSound** 2018-11-09 23:07 UTC
Labels: 3-0-x, bug :beetle:, platform/windows
