### ISSUE TITLE
__dirname encodes space in path with "%20"

### ISSUE THREAD

**Issue by yaooluu** [electron/electron#8738] opened 2017-02-22 20:59 UTC
* Electron version: 1.4.15
* Operating system: MacOS El Captain

### Expected behavior

**__dirname** shouldn't encode spaces in path with "20%". For example, I have a directory "/Users/test 1". **__dirname** should print out "/Users/test 1" as it does in pure NodeJS environment.

### Actual behavior

**__dirname** prints "/Users/test%201". This breaks other NodeJS functionalities like fs.existsSync(), which doesn't accept an encoded path.

Example: 
> __dirname ==> "/Users/test%201"
> require('fs').existsSync(__dirname) ==> false
> require('fs').existsSync("Users/test 1") ==> true

Please refer to https://github.com/nodejs/node/issues/11509 for my original post.

**Comment by kevinsawicki** [comment] 2017-02-22 22:24
@yaooluu are you seeing this in the main process or the renderer process or both? Can you include a reproduction app? Here is what I tried but it seemed to log the `__dirname` without any `%20` characters in the path.

```js
const {app, BrowserWindow} = require('electron')
const path = require('path')
const url = require('url')

let win

app.once('ready', () => {
  win = new BrowserWindow()
  win.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))
})
```

```js
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script>
      console.log(__dirname);
    </script>
  </head>
  <body>

  </body>
</html>
```

And the path on disk that the app is in is `/Users/kevin/github/electron-scratch/with space/`

**Comment by yaooluu** [comment] 2017-02-22 23:52
Hi @kevinsawicki ,

So I've created a sample app with Angular 2 and Electron. Below is what I've observed:

<img width="851" alt="screen shot 2017-02-22 at 3 45 55 pm" src="https://cloud.githubusercontent.com/assets/8813134/23238282/0aac13b6-f916-11e6-9b93-ef45a4203ae4.png">

So looks like in both HTML and JS files, **__dirname** doesn't encode spaces. But in TS file it does. Do you have any idea why this happens?

Attached my modified sample app. ([ng2-electron.zip](https://github.com/electron/electron/files/795151/ng2-electron.zip))

From source:  https://github.com/DenisVuyka/ng2-electron

**Comment by kevinsawicki** [comment] 2017-02-22 23:54
>  Do you have any idea why this happens?

I don't, how are these files being required? Are they precompiled or compiled on the fly?

**Comment by yaooluu** [comment] 2017-02-23 20:20
@kevinsawicki The TS files are compiled into JS before the application starts. And "__dirname" syntax remains the same from TS to JS. 

However the compiled JS files are loaded through Angular 2 framework, which is different from the directly included JS files (where __dirname prints out correctly). 

My temporary solution is to replace "__dirname" with "decodeURI(__dirname)" in all TS files.

**Comment by kevinsawicki** [comment] 2017-02-25 00:13
> However the compiled JS files are loaded through Angular 2 framework, which is different from the directly included JS files (where __dirname prints out correctly).

This sounds like an Angular (and/or precompiler) issue then and not something that can be addressed in Electron.

I'm going to close this issue out based on this information but if you can reproduce it in an app that doesn't use TypeScript or Angular then we can reopen it and see what is happening, but I was unable to reproduce it using node's `require`.

**Closed by kevinsawicki** 2017-02-25 00:13 UTC
Labels: more-information-needed, triage/bug
