### ISSUE TITLE
Lots of errors pop up when starting electron app by using electron command

### ISSUE THREAD

**Issue by vojtatranta** [electron/electron#11027] opened 2017-11-06 10:13 UTC
* Electron version: 1.7.5
* Operating system: Mac and Win

### Expected behavior

No errors :)

### Actual behavior

First one:
```
events.js:308 Uncaught TypeError: this.on is not a function
    at once (events.js:308)
    at CallbacksRegistry.apply (/code/avocode/avocode/node_modules/electron/dist/Avocode Next.app/Contents/Resources/electron.asar/…:48)
    at EventEmitter.<anonymous> (/code/avocode/avocode/node_modules/electron/dist/Avocode Next.app/Contents/Resources/electron.asar/…:299)
    at emitThree (events.js:116)
    at EventEmitter.emit (events.js:197)
```

And than:
```
Uncaught TypeError: Cannot read property 'ended' of undefined
    at Writable.write (_stream_writable.js:237)
    at CallbacksRegistry.apply (/code/avocode/avocode/node_modules/electron/dist/Avocode Next.app/Contents/Resources/electron.asar/…:48)
    at EventEmitter.<anonymous> (/code/avocode/avocode/node_modules/electron/dist/Avocode Next.app/Contents/Resources/electron.asar/…:299)
    at emitThree (events.js:116)
    at EventEmitter.emit (events.js:197)
```
than:
```
Uncaught TypeError: Cannot read property 'corked' of undefined
    at Writable.end (_stream_writable.js:478:12)
    at CallbacksRegistry.apply (/code/avocode/avocode/node_modules/electron/dist/Avocode Next.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (/code/avocode/avocode/node_modules/electron/dist/Avocode Next.app/Contents/Resources/electron.asar/renderer/api/remote.js:299:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```
These errors pop up all the time when app is running

### How to reproduce
It happens on the Mac too. But when you run electron app in windows using `electron main.js`

It pops every time.

I will provide repo when you'll have troubles reproducing it. But it seems like some typical javascript type problem...

**Comment by felixrieseberg** [comment] 2017-11-07 22:09
`node_modules/electron/dist/Avocode Next.app/Contents/Resources/electron.asar`

☝️ That looks pretty weird. Could you provide a repro, because I have trouble getting any similar issues.

**Comment by vojtatranta** [comment] 2017-11-08 18:44
Don't worry about this path. We just rename .app bundle. Will try to provide it. Thanks

**Comment by codebytere** [comment] 2017-11-29 17:08
did you solve this? i'm going to go ahead and close this issue unless we can see a repro

**Closed** 2017-12-03 01:41 UTC
Labels: platform/macOS, platform/windows, triaged/helpme, version/1.7.x, waiting/needs-repro

**Comment by matthew-matvei** [comment] 2018-01-03 09:57
@codebytere I'm currently experiencing this issue in [my project](https://github.com/matthew-matvei/freeman/tree/packaging). It affects me on Linux and Windows. If you clone the repo and checkout the `packaging` branch, the problem will hopefully be reproducible.

Let me know if you need any more info
