### ISSUE TITLE
MediaDevices.enumerateDevices: default audio device returned with empty label

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#4931] opened 2016-03-28 10:21 UTC
* Electron version: 0.36.12
* Operating system: Mac OS/Win

When call MediaDevices.enumerateDevices default audio input/output device returned with empty label.

**Comment by MarshallOfSound** [comment] 2016-03-29 01:20
It always has the `deviceId` of `"default"` or `"communications"`.  You can use those standard ID's as a workaround.

**Comment by cumajkeee** [comment] 2016-03-29 06:24
Yeap, sure, but want to let know about issue. Thanks.

**Comment by zcbenz** [comment] 2016-03-31 10:58
As I tried in Chrome 49, the label is also empty in it, so I'm closing this.

If you really need to fix this, I suggest reporting it to Chromium's issues list instead.

**Comment by ckaczor** [comment] 2016-03-31 19:59
I don't think it is a Chrome/Chromium issue.  I have code that has proper labels when run in Chrome 49.0.2623.110 but has blank labels in Electron using version 0.37.3 of electron-prebuilt.

**Comment by ckaczor** [comment] 2016-03-31 20:07
You can test this with: https://www.webrtc-experiment.com/DetectRTC/

In Chrome 49 the first two devices show a label of "Default" and "Communications" - in Electron they show as "Please invoke getUserMedia once." because that's what DetectRTC puts in as a placehodler when labels are blank.

I've confirmed that getUserMedia is called (same code in both cases) and everything looks fine except for the label being blank.

**Comment by zcbenz** [comment] 2016-04-02 11:01
@ckaczor I tested with following code:

```js
navigator.mediaDevices.enumerateDevices().then(function(devices) {
  devices.forEach(function(device) {
    console.log(device.label)
  })
})
```

Is there misunderstanding?

**Comment by ckaczor** [comment] 2016-04-02 12:48
@zcbenz You need to call getUserMedia to request microphone/camera permission before you get the labels.  With your code above I get all empty strings, but when I request and grant permission I get the proper labels.

`
navigator.webkitGetUserMedia({ audio: true, video: true }, function() {
    navigator.mediaDevices.enumerateDevices().then(function(devices) {
        devices.forEach(function(device) {
            console.log(device.label)
        })
    })
}, function() { console.log('getUserMedia failed') })
`

**Comment by MarshallOfSound** [comment] 2016-04-02 13:33
@ckaczor Chiming in here, the media devices having empty labels was an issue I reported a while back and has been fixed in the more recent versions.  To fix that issue at least I would suggest running Electron `0.37.x` (That's when it was fixed I think :thought_balloon: )

**Comment by ckaczor** [comment] 2016-04-02 13:38
@MarshallOfSound Thanks - but I already tried that.  I was running 0.36.x when I first noticed the issue and when I ran across issue 4613 I upgraded to 0.37.3 and the problem is still there.  It might have been fixed somewhere in the middle but it seems broken again.

**Comment by ckaczor** [comment] 2016-04-02 13:41
Actually - I just checked and it seems like I'm still at 0.36.7 for some reason.  Let me figure out why and check again with the latest version - it may indeed be fixed.

**Comment by ckaczor** [comment] 2016-04-02 13:56
I made sure I was running 0.37.3 (I had missed an update to the version in the packager previously) and I'm still getting blank "default" and "communication" labels.  I do get the labels in Chrome.

**Comment by zcbenz** [comment] 2016-04-07 02:12
@ckaczor Thanks for the test code, I'm reopening this issue.

**Closed** 2016-04-11 10:30 UTC
Labels: bug
