### ISSUE TITLE
contextMenu items label not updating even after tray.setContextMenu(contextMenu)

### ISSUE THREAD

**Issue by JerryGoyal** [electron/electron#10951] opened 2017-10-27 18:17 UTC
I updated the `contextMenu.items[0].label = "Resume Program"` from "`Pause Program`" item label  but it is not updated in system tray menu. it is still showing the old "Pause Program" label.
```
const template = [
        {
            label: 'Pause Program', click: function () {
                pauseplay();
            }
        }]
contextMenu = Menu.buildFromTemplate(template)
    tray.setContextMenu(contextMenu)

function pauseplay(){
contextMenu.items[0].label = "Resume Program";
tray.setContextMenu(contextMenu);
}
```

I even tried setting  `tray.setContextMenu(contextMenu)` but still no effect.

* Electron version: 1.7.9
* Operating system: Windows 10

**Comment by juliangruber** [comment] 2017-11-22 15:58
This happens in OSX as well. The only fix is to create a new menu object and set it.

**Comment by NaLLiFFuNT** [comment] 2018-09-01 13:38
is there any updates? got the same issue on macOS

**Comment by codebytere** [comment] 2018-09-26 20:08
This would require rearchitecting of most of our current Menu architecture, at a glance

**Comment by amirangorgazjan** [comment] 2018-11-16 09:35
I have the same problem. I want to update a Tray context menu in 1-3 second intervals. When the menu is opened, this results in the menu being closed.

**Comment by sofianguy** [comment] 2019-01-08 18:23
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-09 18:42
Given @codebytere's [comment](https://github.com/electron/electron/issues/10951#issuecomment-424852555), this issue will not be fixed in later versions of Electron unfortunately.

**Closed by sofianguy** 2019-01-09 18:42 UTC
Labels: blocked/need-info, bug :beetle:, platform/windows, version/1.7.x

**Comment by matthewjumpsoffbuildings** [comment] 2019-09-10 03:57
Is this still beyond consideration? Its a pretty major PITA having the menu constantly being closed because it has to be rebuilt every time a label needs changing...

**Comment by hmake98** [comment] 2020-04-19 13:55
Yes, I'm having the same issue. I assigned first at the app on ready and then changing it in ipcMain call. but look like it's changed in the context menu but not be able to set in the tray context menu.
Platform: Ubuntu 
Electron version: 5.0.2

**Comment by SuperKirik** [comment] 2021-12-30 16:19
Still no fix for this ?
The same issue with:

Electron 15.3.3
macOS
