### ISSUE TITLE
Window won't stay alwaysOnTop with OpenGL or Vulkan. Works with DX11.

### ISSUE THREAD

**Issue by sklink** [electron/electron#8530] opened 2017-01-29 00:23 UTC
* Electron version: 1.4.15
* Operating system: Windows 10 x64

### Expected behavior

Application is built to be an overlay for games, currently Dota 2.

Issue happens with a BrowserWindow that is set as frameless, fullscreen, and transparent.

The BrowserWindow will not stay on top of OpenGL or Vulkan apps.

**With disabled hardware acceleration:**
1. Disabling hardware acceleration prevents the window from staying on top of OpenGL and Vulkan applications. (Tested with Dota 2 and launch options: `-gl` or `-vulkan`). However, on DX11, the window stays on top and transparent regions are click-through.

**With enabled hardware acceleration:**
2. Window stays on top, regardless of OpenGL, Vulkan, or DX11 applications running. Click-through of transparent regions doesn't work.

**With enabled hardware acceleration and Kiosk mode enabled and setIgnoreMouseEvents = false:**
Acts the same as number 2.

**With enabled hardware acceleration and Kiosk mode enabled and setIgnoreMouseEvents = true:**
Acts the same is number 1.

(Dota 2 is set to be Borderless Window in all of these cases)

It seems when Dota 2 takes focus, regardless of hardware acceleration, alwaysOnTop, or Kiosk mode. It always pushes the electron window to the back when running on OpenGL or Vulkan. The fact that the transparency cannot be clicked through is just preventing Dota from having focus.

### Actual behavior

The window should stay on top of OpenGL and Vulkan applications, just as it does DX11.

### How to reproduce

Open up a Borderless Window OpenGL or Vulkan application (Dota 2 is what I've used) and create a frameless, fullscreen, transparent window. Attempt to keep the window alwaysOnTop while being able to click through transparent areas.

Happy to add more context or provide code if needed, but it's very basic. Just create a window with the settings as stated above and play with hardware acceleration if you feel that will influence it.

**Comment by groundwater** [comment] 2017-02-17 18:35
Hi @sklink, thanks for the detailed report! 

Can you also try `1.6.0` accessible by `npm i electron@beta` and see if the problem is still happening?

**Comment by sklink** [comment] 2017-02-27 19:23
Yes, 1.6.1 still has the same issue.

A couple interesting things I noticed this time around--although it is consistent with what I experienced on `v1.4.15` 

Here's a video. ***Note:** When the recording goes black, I've changed application focus by clicking on either the Electron app (the black box on the left) or the Dota 2 interface.*

https://drive.google.com/open?id=0B6Wu2okZpithd05zbl9tLXQtY00

* The application is still on top, even though it's not rendering. You can tell this by watching the cursor when Dota is in focus. Although you can't see the Electron window, the cursor type changes when I mouse over the location it would be.
* During the focus switch, there's a slight flash of black, but when I recorded with OBS the duration of black was significantly longer.

**Comment by sklink** [comment] 2017-02-28 14:53
Forgot another one:

* The application is running in Borderless Window mode. This error only occurs when the resolution of Dota matches the resolution of Windows. If Dota is smaller than the desktop, the application, alwaysOnTop works as expected.

**Comment by zcbenz** [comment] 2017-06-06 05:04
While we would like to fix this, I'm afraid it is deeply related to Chromium's GPU rendering, which we are not able to solve. I'm closing this as won't fix.

**Closed by zcbenz** 2017-06-06 05:04 UTC
Labels: component/fullscreen, platform/windows, triage/bug

**Comment by robsontenorio** [comment] 2017-07-21 01:30
@sklink can you provide the setup for  "BrowserWindow({ .... })" ?

**Comment by sklink** [comment] 2017-07-21 17:42
app.disableHardwareAcceleration();

app.on('ready', async () => {
    mainWindow = new BrowserWindow({
      show: false,
      transparent: true,
      frame: false,
      fullscreen: true,
      x: 0,
      y: 0,
      width: screenResolution.width,
      height: screenResolution.height
    });

    mainWindow.once('ready-to-show', () => {
      mainWindow.show();
      mainWindow.focus();
    });
});

After that I used `active-window` to monitor the application and set it's `alwaysOnTop` and `kiosk` both of which were required to make it function as an overlay.

**Comment by robsontenorio** [comment] 2017-07-21 19:05
@sklink i cant reproduce it, can you past whole index.js file?
