### ISSUE TITLE
When maximizing frameless window, the borders are out of screen.

### ISSUE THREAD

**Issue by Sential** [electron/electron#9017] opened 2017-03-25 21:40 UTC
* Electron version: 1.6.2
* Operating system: Windows 10

### Actual behavior

When I'm maximizing the frameless window, the borders of window are out of screen.
For example: If I have my custom titlebar with 100px height and if I'll maximize the window, the titlebar will be 96px height.

On screenshot, the borders aren't out of screen.

### How to reproduce

Please clone my repository by using these commands:

  $ git clone https://github.com/nersent/wexond -b refactor
  $ npm install
  $ npm run browser
  $ npm start

Or create your own frameless window, then maximize it and see what happens.

**Comment by Sential** [comment] 2017-03-28 11:02
Bump

**Comment by Sential** [comment] 2017-03-28 11:09
#8728

**Comment by tonyganch** [comment] 2017-03-29 12:51
I think both this issue and #8454 should be closed as duplicates of #8728, because the latter one has a longer discussion plus an open PR.

**Comment by kevinsawicki** [comment] 2017-03-31 21:47
> I think both this issue and #8454 should be closed as duplicates of #8728, because the latter one has a longer discussion plus an open PR.

👍 Closing as duplicate of #8728, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2017-03-31 21:47 UTC
