### ISSUE TITLE
[Bug]: using the print method to print, the printed content is not on A4 paper

### ISSUE THREAD

**Issue by xiaorenjunsong** [electron/electron#39102] opened 2023-07-14 06:08 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

Windows

### Operating System Version

windows10

### What arch are you using?

x64

### Expected Behavior

I hope the content can be displayed on A4 paper

### Actual Behavior

using the print method to print, the printed content is not on A4 paper

**Comment by pushkin-** [comment] 2023-07-14 19:01
dupe of [this](https://github.com/electron/electron/issues/31705)?

**Closed** 2023-07-28 01:53 UTC
Labels: bug :beetle:, blocked/need-repro
