### ISSUE TITLE
[Bug]: SpeechRecognition does not work

### ISSUE THREAD

**Issue by IvanCodeslol** [electron/electron#31732] opened 2021-11-06 12:44 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Electron Version

15.3.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.1

### What arch are you using?

x64

### Expected Behavior

SpeechRecognition `onresult` event gets triggered.

### Actual Behavior

SpeechRecognition `onresult` event does not get triggered. 

### Additional Information

I have tried using this in Chromium and it does not work there either, it does work on Chrome though.

**Comment by codebytere** [comment] 2021-11-08 09:44
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by Kilian** [comment] 2022-01-10 11:29
SpeechRecognition depends on Google's servers, so this is disabled in all places except Google Chrome. You might be able to enable it by [adding a google api key](https://www.electronjs.org/docs/latest/api/environment-variables#google_api_key) with the appropriate Google API enabled.

**Comment by codebytere** [comment] 2022-01-10 14:40
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-01-10 14:40 UTC
Labels: platform/linux, bug :beetle:, blocked/need-repro, 15-x-y

**Comment by IvanCodeslol** [comment] 2022-01-11 20:20
> SpeechRecognition depends on Google's servers, so this is disabled in all places except Google Chrome. You might be able to enable it by [adding a google api key](https://www.electronjs.org/docs/latest/api/environment-variables#google_api_key) with the appropriate Google API enabled.

Not sure if this is true since Chrome without internet had working speech recognition.

**Comment by IvanCodeslol** [comment] 2022-01-11 20:22
> We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

I will make & upload a fiddle as soon as I have time.

**Comment by jtbandes** [comment] 2025-01-14 02:21
This can be reproduced by placing the following code in `renderer.js`:

```js
var r = new webkitSpeechRecognition();
r.continuous = true;
r.interimResults = true;
r.onstart = (event)=>console.log('start',event);
r.onerror = (event)=>console.log('error',event);
r.onend = (event)=>console.log('end',event);
r.onresult = (event)=>console.log('result',event);
r.start()
```

This results in an `error` event with the error `"network"`: 

<img width="895" alt="Image" src="https://github.com/user-attachments/assets/d1c9b6d3-3b4f-4e69-9902-4539706d9eaf" />

**Comment by FerLuisxd** [comment] 2025-08-08 04:01
This is stil an issue today, please reopen the issue.
