### ISSUE TITLE
Add support of webview in webview

### ISSUE THREAD

**Issue by vladkens** [electron/electron#6916] opened 2016-08-20 20:31 UTC
Hello, i try to open webview in webview and attach it like parent-child.
Chrome has API for this https://developer.chrome.com/apps/tags/webview#event-newwindow, but electron does not emit native `newwindow` event.

**Comment by zcbenz** [comment] 2016-08-22 02:22
This is a duplicate of #1130.

**Closed by zcbenz** 2016-08-22 02:22 UTC
