### ISSUE TITLE
interceptBufferProtocol default callback

### ISSUE THREAD

**Issue by kaiserdj** [electron/electron#28028] opened 2021-03-06 16:36 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  11.3.0
* **Operating System:**
  *  Windows 10 Pro (20H2)
* **Last Known Working Electron version:**
  * 

### Expected Behavior

I would like to make a default callback if I don't want to modify the request

### Actual Behavior

I can create a callback of my own, but there is no way to return the default callback or let it follow normal rhythm without modifying

### To Reproduce
Fiddle: https://gist.github.com/19c24511024997d2415c2df3f5eabe2e

**Comment by nornagon** [comment] 2021-03-15 22:59
Duplicate of #15434

**Closed by nornagon** 2021-03-15 22:59 UTC
Labels: 11-x-y, bug :beetle:, has-repro-gist, platform/windows
