### ISSUE TITLE
browserWindow.capturePage() may fail occationally [v12 only]

### ISSUE THREAD

**Issue by ozooner** [electron/electron#27657] opened 2021-02-08 16:21 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  v12.0.0-beta.21
* **Operating System:**
  *  Ubuntu 20.04
* **Last Known Working Electron version:**
  *  v11.2.3 (the same provided example works most recent v11 release, tested!)

### Expected Behavior
Expecting `browserWindow.capturePage()` to return a promise that resolves to captured image

### Actual Behavior
The function call will at some point result an uncaught promise exception. Currently it seems it's random and about a 5% chance of this happening.

### To Reproduce

Minimal example is a loop calling `browserWindow.capturePage()` every 1 second until eventually it fails. On my machine it will fail within a minute and result in the error.
I tried with the new `@electron/remote` and also with the old `electron.remote`. The example is using the new remote module as it will result in an error whereas the old `electron.remote` will not result an exception, but instead the promise **will never resolve or reject**
```
git clone https://github.com/ozooner/electron-capture-page.git
npm install
npm start
```

### Screenshots
![image](https://user-images.githubusercontent.com/2709373/107247085-c34d9180-69e5-11eb-83d3-344a77387cde.png)

**Comment by ckerr** [comment] 2021-02-08 19:42
Thanks for reaching out and reporting this issue!

I'm seeing the same when running the testcase. When I checked the generated `browser_init.js` file, the crash is happening when trying to access `processId` in this code block:

> function getWebFrame(e,t){if("number"==typeof t)return o.webFrameMain.fromId(e.mainFrame.processId,t)

So the WebMainFrame is null.

This appears to be a duplicate of https://github.com/electron/electron/issues/26824, which is fixed by https://github.com/electron/electron/pull/27648 which should be in the next 12.0.0 beta.

As such, I'm going to close this issue. If you still see this problem after the next 12.0.0 beta, please open a new issue to let the Electron team know. Thank you!

**Closed by ckerr** 2021-02-08 19:42 UTC
Labels: 12-x-y, bug/regression :leftwards_arrow_with_hook:, has-repro-repo, platform/linux, status/confirmed
