### ISSUE TITLE
Converting web app to desktop app problem.

### ISSUE THREAD

**Issue by bdevelops** [electron/electron#6746] opened 2016-08-05 18:09 UTC
* Electron version: v1.3.2
* Operating system: Windows 7

So, I wanted to convert web app to desktop app with electron. Here is web app: [click](http://dinoz.mobi/shelter-editor/
) And here is github repo: [click](https://github.com/MobileSam/shelter-editor)

But when I opened it with electron as a desktop app, it's mixing a "drag file page" with next page that allows to edit that file. It looks like that:
![error](https://cloud.githubusercontent.com/assets/19797790/17445811/bed50a5a-5b46-11e6-850a-d827d523884e.png)

main.js:

    const {app, BrowserWindow} = require('electron')

    let win

    function createWindow () {
      win = new BrowserWindow({width: 1366, height: 768})
        webPreferences: {
            nodeIntegration: false
        }
      win.show()

      win.loadURL(`file://${__dirname}/shelter.html`)

      win.on('closed', () => {
        win = null
      })
    }

    app.on('ready', createWindow)

    app.on('window-all-closed', () => {
      if (process.platform !== 'darwin') {
        app.quit()
      }
    })

    app.on('activate', () => {
      if (win === null) {
        createWindow()
      }
    })

**What's wrong?**

**Comment by kevinsawicki** [comment] 2016-08-05 18:23
If you open the dev tools and click the console tab you will see the following errors:

> Uncaught Error: Bootstrap's JavaScript requires jQuery
> Uncaught ReferenceError: $ is not defined

This is a duplicate of #254, you can read there for more discussion and fixes for this, a quick hack to get your app working would be:

```diff
diff --git a/shelter.html b/shelter.html
index 1a3a696..7dbc9c1 100644
--- a/shelter.html
+++ b/shelter.html
@@ -152,6 +152,7 @@
     </div>
 
     <script src="js/jquery-2.1.4.min.js"></script>
+    <script>window.jQuery = window.$ = module.exports</script>
     <script src="js/angular.min.js"></script>
     <script src="js/bootstrap.min.js"></script>
     <script src="js/json2.min.js"></script>
```

**Closed by kevinsawicki** 2016-08-05 18:23 UTC
