### ISSUE TITLE
Closing detach devtools disables browser window transparency/vibrancy

### ISSUE THREAD

**Issue by KagamiChan** [electron/electron#10420] opened 2017-09-01 06:18 UTC
* Electron version: 1.8.0 beta
* Operating system: macOS 10.12.6

### Expected behavior

Browser window's vibrancy settings persists after closing detached devtools

### Actual behavior

Closing detached devtools will disable browser window's vibrancy, and calling setVibrancy again can't re-enable it.

![sep-01-2017 14-04-05](https://user-images.githubusercontent.com/3816900/29957222-e6bced2c-8eb1-11e7-875b-9527213e92a0.gif)

### How to reproduce

The repo for reproducing is https://github.com/KagamiChan/electron-quick-start in branch `1.8.0-vibrancy-mac`. I simply added these lines in `renderer.js`

```js
const { remote } = require('electron')

const win = remote.getCurrentWindow()
win.setVibrancy('ultra-dark')

win.webContents.openDevTools({mode: 'detach'})

win.webContents.on('devtools-closed', () => {
  setTimeout(() => {
    console.log('restoring vibrancy')
    win.setVibrancy('ultra-dark')
  }, 1000)
})
```

Steps to reproduce:

1. git clone -b 1.8.0-vibrancy-mac https://github.com/KagamiChan/electron-quick-start
2. cd electron-quick-start && npm i && npm run start
3. Close the detached devtools
4. the browser window loses vibrancy

btw, In previous version (1.7.5), non-detached devtools breaks the vibrancy but then it will restore after closing the devtools, and in 1.8.0 the vibrancy does not come back either.

**Comment by KagamiChan** [comment] 2017-09-12 03:18
Could someone give me a hint on how to fix this?

**Comment by gerhardberger** [comment] 2017-09-16 12:05
the problem is when closing the devtools a new render view is created and because there is no background color specified it [defaults to white](https://github.com/electron/electron/blob/master/atom/renderer/renderer_client_base.cc#L171).

one solution would be to change this default color to transparent, since I don't see, if it is particularly important here to use white (in some other place there is [transparent default color](https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_web_contents.cc#L1056)), but there could be a reason.

but to solve it without code change, use a clear color as your BrowserWindow's background color, e.g.:
``` js
mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  backgroundColor: '#00000000'
})
```

**Comment by KagamiChan** [comment] 2017-09-18 12:34
@gerhardberger Thank you for looking into this. Setting background color works like a charm.
But I think this is still a bug since the behavior is inconsistent across versions

**Comment by zcbenz** [comment] 2017-12-20 06:16
To add a note, this problem also applies to transparent window on all platforms

**Comment by natew** [comment] 2018-10-15 19:11
This has been intermittent for me, but setting background color isn't fixing it. It was working fine for a while, and now is not. But I can't really tell why. I've seen it happen only when I have a remote debugger attached and then I inspect and element (opening an in-electron debugger) and then close that one.

**Comment by aam1r** [comment] 2018-12-30 03:49
I can confirm that this is still happening on Electron v3.0.8.

Setting a background color of `#00FFFFFF` seems to "fix" the issue for now but after reading @natew's comment I am worried that the background color solution might stop working one day.

**Comment by izuchukwu** [comment] 2018-12-31 08:12
In addition to confirming that this still occurs on Electron v3.0.13, this same issue occurs when using a detached devtools for a `BrowserView`, and the experimental `browserView.setBackgroundColor(color)` doesn't seem to fix it.

**Comment by mallgrab** [comment] 2019-04-18 06:11
Can confirm that this still happens on 4.1.4

**Comment by sindresorhus** [comment] 2019-04-25 06:26
This still occurs on Electron 5.0.0

**Comment by Eugeny** [comment] 2019-09-24 13:09
Still the case with 6.0.10

**Comment by 0xdeafcafe** [comment] 2020-11-15 12:38
Bumping as this still happens on `10.1.5`

**Comment by rrroyal** [comment] 2021-05-02 11:07
Still happens on `11.4.3` :/

**Comment by kysubay** [comment] 2021-05-26 03:37
when I use multiple browsers View and close the devtools on any browser shows a white window. I don't know if it's like you

**Comment by codebytere** [comment] 2022-07-27 08:48
This no longer happens as of v16 - so all supported versions now work correctly. Closing this out.

**Closed by codebytere** 2022-07-27 08:48 UTC
Labels: component/devtools, bug :beetle:, platform/all, 9-x-y, 10-x-y, 11-x-y
