### ISSUE TITLE
Electron tray.displayBalloon()

### ISSUE THREAD

**Issue by yuritk** [electron/electron#7936] opened 2016-11-10 20:58 UTC
Notifications appears, but at sometime, the function dont work again,
For example: those notifications appears just for the first minute. Later dont work

**Comment by zeke** [comment] 2016-11-11 17:41
Please provide a minimal app that reproduces this problem.

**Comment by kevinsawicki** [comment] 2016-11-15 22:50
I think this might be a duplicate of #5844, @yuritk can you check out https://github.com/electron/electron/issues/5844#issuecomment-251018364 and see if it resolves your issue?

**Closed** 2016-11-15 22:50 UTC
Labels: more-information-needed
