### ISSUE TITLE
Received non-DTLS packet before DTLS complete

### ISSUE THREAD

**Issue by sante85** [electron/electron#10608] opened 2017-09-25 14:59 UTC
<!--
Thanks for opening an issue! A few things to keep in mind:

dtlstransportchannel.cc

reject handshake

* Electron version: 1.7.6
* Operating system: Linux

### Expected behavior

WebRTC handshake not fail

### Actual behavior

WebRTC handshake fail

### How to reproduce

Do a client webRTC video streaming under linux under VPN connection and video is black

**Comment by codebytere** [comment] 2017-09-26 17:00
lol you gotta give us more information than this

before we can do anything we need:
**Electron Version**
**OS Version**
**Steps to reproduce**
**Crash Report** (if available)

**Comment by sofianguy** [comment] 2017-09-27 02:20
@sante85 please follow this [contributing guideline](https://github.com/electron/electron/blob/master/CONTRIBUTING.md#submitting-issues)

**Comment by sante85** [comment] 2017-09-27 08:53
electron version 1.7.8 (and other all)
os version: linux ubuntu 16.04

Open a webRTC video on non local connection (eg VPN) and video is black.
Error in console is 
[6224:0927/094922.166315:ERROR:dtlstransportchannel.cc(527)] Jingle:DtlsTransport[video|1|__]: Received non-DTLS packet before DTLS complete.

If open video on local LAN or Windows executable (packaged with electron builder) works fine.

**Comment by ibc** [comment] 2018-01-29 21:14
Let me anticipate some more tags for this issue:

#version/1.9.x
#version/2.0.0
#version/2.0.1
#version/2.0.2
#version/2.0.3
#version/2.0.4
#version/2.0.5
#WhatIsWebRTC?
#WhatIsDtls?
#ClosedBecauseWeHaveNoIdeaWhatThisIssueIsAbout
#LOL

Jokes aside, this is a libwebrtc related issue and hence should be reported (if it still exists) into the Google's WebRTC project: https://bugs.chromium.org/p/webrtc/issues/list

**Comment by codebytere** [comment] 2018-01-30 01:59
@sante85 this is an issue in upstream as per @ibc's comment, so i'm going to go ahead and close this.

**Closed by codebytere** 2018-01-30 01:59 UTC
Labels: platform/linux/ubuntu, version/1.4.x, version/1.5.x, version/1.6.x, version/1.7.x, version/1.8.x
