### ISSUE TITLE
Second menu item click() ignored in submenu on Linux

### ISSUE THREAD

**Issue by semencov** [electron/electron#5255] opened 2016-04-22 14:57 UTC
- Electron version: 0.37.6
- Operating system: Deepin 15.1.1 (based on Debian 8.0)

I have a context menu of a tray icon which built from a template like this (simplified):

``` js
let template = [
  {
    label  : "Settings",
    submenu: [
      {
        type: "checkbox",
        label: "Open at startup",
        checked: (config.get('open-at-startup') === true),
        click: (item) => config.set('open-at-startup', (item.checked === true))
      },
      {
        type: 'checkbox',
        label: "Play notification sound",
        checked: (config.get('play-notification-sound') === true),
        click: (item) => config.set('play-notification-sound', (item.checked === true))
      }
    ]
  }
];

let menu = Menu.buildFromTemplate(template);
appIcon.setContextMenu(menu);
```

So when I toggle "Open at startup" item, it works like a charm. However when I toggle "Play notification sound" it's `click()` function never called (but visually the checkbox toggles). Even better, if I put another one checkbox in the submenu, it is also work fine, so the issue is specific for the second item. Also it is always the second one even if I switch items position and the both items work fine if I put a separator between them.

**Comment by zcbenz** [comment] 2016-04-24 04:42
Can you provide a minimal app that can reproduce this problem? It is probably related to how your `config.set/get` is implemented.

**Comment by semencov** [comment] 2016-04-24 21:05
It does not depend on the `click()` body itself, the code was just for an example. The same code with just a `console.log` works exactly as I’ve described.

**Comment by zcbenz** [comment] 2016-04-26 00:35
I'm unable to reproduce on Ubuntu. Does the same problem occur if you set it as window menu?

**Comment by semencov** [comment] 2016-04-26 08:26
If I set the menu as window menu it is work like expected. However here is what is going on with it when it is a tray icon's menu: https://youtu.be/uuWrzAVPtt4

**Comment by semencov** [comment] 2016-04-26 13:40
I've noticed that the issue is not the specific `checkbox` problem, but also for any type of the second `MenuItem` within a submenu.

**Comment by zcbenz** [comment] 2016-04-27 01:59
I have managed to reproduce it with Unity on Ubuntu 14.04, when I click the second menu item the whole program just crashed.

```
[24799:0427/105419:FATAL:simple_menu_model.cc(426)] Check failed: static_cast<size_t>(index) < items_.size() (1 vs. 1)
#0 0x7f9b1529cebe base::debug::StackTrace::StackTrace()
#1 0x7f9b152b6f8b logging::LogMessage::~LogMessage()
#2 0x7f9b1603d32c ui::SimpleMenuModel::ValidateItemIndex()
#3 0x7f9b1603d649 ui::SimpleMenuModel::GetCommandIdAt()
#4 0x7f9b1603d952 ui::SimpleMenuModel::IsEnabledAt()
#5 0x000000af914e libgtk2ui::AppIndicatorIconMenu::OnMenuItemActivated()
#6 0x7f9b11d243b8 g_closure_invoke
#7 0x7f9b11d35d3d <unknown>
#8 0x7f9b11d3da29 g_signal_emit_valist
#9 0x7f9b11d3dce2 g_signal_emit
#10 0x7f9af2a0b1dd <unknown>
#11 0x7f9b11d26731 g_cclosure_marshal_VOID__UINTv
#12 0x7f9b11d245e7 <unknown>
#13 0x7f9b11d3d088 g_signal_emit_valist
#14 0x7f9b11d3dce2 g_signal_emit
#15 0x7f9af27ed3fe <unknown>
#16 0x7f9af27ee897 <unknown>
#17 0x7f9b0fc49703 <unknown>
#18 0x7f9b0fc48ce5 g_main_context_dispatch
#19 0x7f9b0fc49048 <unknown>
#20 0x7f9b0fc490ec g_main_context_iteration
#21 0x7f9b1528f076 base::MessagePumpGlib::Run()
#22 0x7f9b152d67b0 base::RunLoop::Run()
#23 0x7f9b17dbeadb content::BrowserMainLoop::MainMessageLoopRun()
#24 0x7f9b17dbe8e4 content::BrowserMainLoop::RunMainMessageLoopParts()
#25 0x7f9b17dc187d <unknown>
#26 0x7f9b17db9f4c content::BrowserMain()
#27 0x7f9b17d37641 <unknown>
#28 0x7f9b17d363b0 content::ContentMain()
#29 0x0000007f4c22 main
#30 0x7f9b0de11ec5 __libc_start_main
#31 0x0000007f4a75 <unknown>
```

**Comment by jichu4n** [comment] 2017-02-25 03:32
Getting a similar error here. I have a menu with several items triggered from the tray icon.

Strangely, the click handler for the first item never triggers; if I insert an invisible item at the top ({label: "", visible: false}), the original first item's click handler does trigger.

However, after adding several more items into the menu, clicking the last item now causes the app to crash:

```
[12656:0224/192746:FATAL:simple_menu_model.cc(428)] Check failed: static_cast<size_t>(index) < items_.size() (5 vs. 5)                                                                                                               [5/36939]
#0 0x000001e5801e <unknown>
#1 0x000001e6dd1b <unknown>
#2 0x000002633b5c <unknown>
#3 0x000002633e29 <unknown>
#4 0x000002634132 <unknown>
#5 0x000001b1d64e <unknown>
#6 0x7f7ec63a93b8 g_closure_invoke
#7 0x7f7ec63bad3d <unknown>
#8 0x7f7ec63c2a29 g_signal_emit_valist
#9 0x7f7ec63c2ce2 g_signal_emit
#10 0x7f7ec7ed390c gtk_widget_activate
#11 0x7f7ec7dd610d gtk_menu_shell_activate_item
#12 0x7f7ec7dd645c <unknown>
#13 0x7f7ec7dc4945 <unknown>
#14 0x7f7ec63a93b8 g_closure_invoke
#15 0x7f7ec63baafb <unknown>
#16 0x7f7ec63c26f9 g_signal_emit_valist
#17 0x7f7ec63c2ce2 g_signal_emit
#18 0x7f7ec7ed4a94 <unknown>
#19 0x7f7ec7dc30f4 gtk_propagate_event
#20 0x7f7ec7dc34ab gtk_main_do_event
#21 0x000001b1e818 <unknown>
#22 0x7f7ec7a3d4ac <unknown>
#23 0x7f7ec40cee04 g_main_context_dispatch
#24 0x7f7ec40cf048 <unknown>
#25 0x7f7ec40cf0ec g_main_context_iteration
#26 0x000001e4d996 <unknown>
#27 0x000001e8cede <unknown>
#28 0x0000026fd029 <unknown>
#29 0x0000026fce75 <unknown>
#30 0x0000026ffcfd <unknown>
#31 0x0000026f8eac <unknown>
#32 0x0000012215b7 <unknown>
#33 0x000001220090 <unknown>
#34 0x000003479173 main
#35 0x7f7ec1d86f45 __libc_start_main
#36 0x000000578cc9 <unknown>

xxx terminated by signal SIGABRT (Abort)

```

**Comment by praveenkumarzoho** [comment] 2017-04-03 09:10
I am also facing this above issue in linux ubuntu, it happens when the submenu has more entries than the number of menus in first of the hierarchy.
I think the doubt that the size of the submenu is taken from the size of the parent.
For example,
When I have 4 menu in parent and 6 menu in submenu, For the first 4 submenu the issue will not occur, only if I select 5th or 6th submenu the above issue will occur with the exception,
`FATAL:simple_menu_model.cc(428)] Check failed: static_cast<size_t>(index) < items_.size() (4 vs. 4)`
or
`FATAL:simple_menu_model.cc(428)] Check failed: static_cast<size_t>(index) < items_.size() (6 vs. 5)`

**Comment by codebytere** [comment] 2017-09-27 01:45
closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:45 UTC
Labels: component/menu, fixme/bug, fixme/crash, platform/linux

**Comment by jcj52436999** [comment] 2017-09-27 01:46
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (112/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:41462 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dx1QN-0017ob-Lz
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:46:10 -0500
Date: Tue, 26 Sep 2017 18:45:20 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1506476720;
	bh=/2gO/VPaoJUHLf3vlGNGUSnbi6TAlk4tVO+9xFzN0vA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=n0IZKyMHQN/RerJt2K6vkfsOZgbF2LO69fF8UAydrKAnN+0TI5iaJxhDwrKt0+r4a
	 XE112YPSETiIcSgztC0ccNXCYXdLK0/r98o3+MIPJixvbZ3H6nMH8kD0dsBkeRauNw
	 MpMNQDQIumy44fGEaIAQquDUxbotCB9iHRwCWkn4=

**Comment by jcj52436999** [comment] 2017-09-27 01:46
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (111/100 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:33950)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-96d6-jcjackson=joe-jackson.net@sgmail.github.com>)
	id 1dx1QN-0017oi-5P
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:46:09 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=peqcMOq5GGsi/NS6FGLSa7bfBqg=; b=mwWo+m+hJhX6+jBz
	3w2miNQNkq8iyxXDKPhZ1JW3XwH2ATZmmOu3SDfJineIyaH7j4cVATUSnrGJHQkc
	pD/kaI19Z57SLSTHHyAllZ1gXdsMudLOguAcb08s672WwBdQMv7OUXP+KZ+c41jo
	0RRmm+6K2UUjV238+hpOvCFruDU=
Received: by filter1109p1mdw1.sendgrid.net with SMTP id filter1109p1mdw1-28166-59CB02B0-11
        2017-09-27 01:45:20.453694671 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id IRxd5C1xT7yT8MFKLHp-5w
	for <jcjackson@joe-jackson.net>; Wed, 27 Sep 2017 01:45:20.427 +0000 (UTC)
Date: Wed, 27 Sep 2017 01:45:20 +0000 (UTC)

**Comment by jakedouglas** [comment] 2018-03-06 20:18
@jichu4n @praveenkumarzoho @zcbenz Did you ever find a solution to this crash?

**Comment by codebytere** [comment] 2018-03-06 20:21
@jakedouglas do you still see it happening?

**Comment by jakedouglas** [comment] 2018-03-06 20:23
@codebytere The same crash occurs in another project using Chromium. If Electron was able to fix it, I'm curious as to how.
