### ISSUE TITLE
`desktopCapturer` Electron Client Screenshare with Audio Causes Participants to Hear Echo

### ISSUE THREAD

**Issue by info-ankit** [electron/electron#27337] opened 2021-01-16 08:26 UTC
I am using the desktop sharing feature of the Electron `desktopCapturer` on our demos. Some of our demos require to share audio of our application. When we share the desktop with audio on desktopCapturer electron client participants start to hear their own voice.

```
const constraints = {
  audio: {
    mandatory: {
      chromeMediaSource: 'desktop'
    }
  },
  video: {
    mandatory: {
      chromeMediaSource: 'desktop'
    }
  }
}
```

Current behavior:
-
When screen share enabled with audio participant sounds echoing back to themselves.

Expected Behavior:
-
Only system sounds should be broadcasted to the conference.

Expected Solution:
-
Behaviour should be converted as same as chrome web client.

Steps:
-
1- Using `desktopCapturer` Electron
2- Share screen with audio
3- Another participant starts to talk. (As a result, hears themself)

Environment:
-
Windows 10
Electron ^9.2.1
desktopCapturer Electron

**Comment by asineth0** [comment] 2021-03-30 04:39
Same issue here. Also trying to capture the audio for one application/window results in getting the entire system audio instead of the audio for that specific application.

**Comment by nornagon** [comment] 2021-03-30 22:47
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by yavuzcakir** [comment] 2021-05-26 14:45
You can download electron based Jitsi Meet desktop Client from link: https://desktop.jitsi.org/Main/Download.html. 
Join a room and share your desktop with video play. The other participants will hear echo

**Comment by yavuzcakir** [comment] 2021-05-26 14:46
@narnagon You can download electron based Jitsi Meet desktop Client from link: https://desktop.jitsi.org/Main/Download.html.
Join a room and share your desktop with video play. The other participants will hear echo

**Comment by nornagon** [comment] 2021-06-17 17:33
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by nornagon** [comment] 2021-07-06 21:47
I'm closing this as there's no minimal repro available. I'm happy to reopen if you're able to provide a more directed example that shows the issue.

**Comment by Apak00** [comment] 2021-07-07 09:52
@nornagon 
Hello there I created this repository [https://github.com/Apak00/electron-ss-echo-problem](https://github.com/Apak00/electron-ss-echo-problem) starting from electron-quick-starter.
As it requires a peerconnection to be established, there is a signaling server involved but it should have nothing to do with echo problem because all it does is really trading the sdp between peers.
Also added reproduce steps, but if you have any problem with reproducing, I am more than happy to help.

I hope this helps you

**Comment by dx200010** [comment] 2021-07-16 06:59
Here’re some findings after struggling with this issue for months.

1. Using getDisplayMedia() in chrome doesn’t have echo issue, but it will have it too if echo cancellation was turned off. 
2. Debug log shows getUserMedia() have no audio processing applied, but getDisplayMedia() does.
3. Audio processing was skipped since chrome want to create a direct-path and skipped it for screen capture device. 
4. getUserMedia() was caught in above by its device type, getDisplayMedia() have different device type and escaped
5. Tried to made a mod to disable checking of screen catpure device type, it do works and echo was removed. But there're still lot of differences comparing to getDisplayMedia()

What I modified:
third_party/blink/renderer/modules/mediastream/user_media_processor.cc:CreateAudioSource()
Commented out blink::IsScreenCaptureMediaType(device.type)

**Comment by asineth0** [comment] 2021-07-24 07:39
Seems to work, should make a PR.

**Comment by as0577** [comment] 2021-07-26 21:56
![1627253804545](https://user-images.githubusercontent.com/85883447/127064270-b35a4d67-7df2-4e0e-bf82-0c9abac38166.jpg)
[]() @codebytere

**Comment by asineth0** [comment] 2021-07-26 21:59
> ![1627253804545](https://user-images.githubusercontent.com/85883447/127064270-b35a4d67-7df2-4e0e-bf82-0c9abac38166.jpg)
> @codebytere

What?

**Comment by Durgaprasad-Budhwani** [comment] 2021-07-28 23:37
Team, any update on this issue.

**Comment by Durgaprasad-Budhwani** [comment] 2021-07-29 00:20
@dx200010 If possible, can you please provide your code snippet or repo with working example.

**Comment by dx200010** [comment] 2021-07-30 01:35
> @dx200010 If possible, can you please provide your code snippet or repo with working example.

Firstly, please make sure you have downloaded full source codes of electron by following official build instruction.

Find the `UserMediaProcessor::CreateAudioSource()` in `third_party/blink/renderer/modules/mediastream/user_media_processor.cc`
and change below if-block
```C++
  if (blink::IsScreenCaptureMediaType(device.type) ||
      !blink::MediaStreamAudioProcessor::WouldModifyAudio(
          audio_processing_properties)) {
```
to
```C++
  if (//blink::IsScreenCaptureMediaType(device.type) ||
      !blink::MediaStreamAudioProcessor::WouldModifyAudio(
          audio_processing_properties)) {
```
Then build a modified electron from source, and use this modified electron to build your own application.

Now, you can enable echo cancellation by inserting the constraint like below.
```JS
navigator.mediaDevices.getUserMedia({
    audio : {
        mandatory: {
            echoCancellation: true,
            chromeMediaSource: 'desktop'
          }
    },
    video :
    {
        mandatory :
        {
            chromeMediaSource : 'desktop'
        }
    }
})	
```

**Comment by Apak00** [comment] 2021-08-04 13:56
@dx200010 Thanks a lot for the details, But unfortunately this did not work for me.

Could it be because of a certain electron version I need to checkout? the version I tried is : 12.0.1

**Comment by dx200010** [comment] 2021-08-05 01:17
> @dx200010 Thanks a lot for the details, But unfortunately this did not work for me.
> 
> Could it be because of a certain electron version I need to checkout? the version I tried is : 12.0.1

Maybe...
I have only tried this on 13.1.4, don't know if it's version specific or not.

**Comment by Apak00** [comment] 2021-08-05 06:48
@dx200010  Have you had a chance to try your custom electron build on this repo?
 https://github.com/Apak00/electron-ss-echo-problem

**Comment by Apak00** [comment] 2021-08-05 15:28
I point my package.json electron dependency to custom electron build like this

devDependencies: {
...
electron: "file:../electron/src/electron"
}

Eventhough I am able build app with this, could that be wrong?

What is the right way of adding custom electron build to a project?

**Comment by dx200010** [comment] 2021-08-06 03:08
@Apak00 Maybe your app was still linked to an unmodified electron.

Try launching your app directly from your own built electron for testing,
`<Path to your electron source>\out\Release\electron.exe .`

If it does works, then it's just packaging issue. Or, this workaround may just not always works.

**Comment by asineth0** [comment] 2021-08-06 10:22
Either way, would love to fix this upstream instead of having to build Electron which is quite time consuming for many.

**Comment by cosysun** [comment] 2021-08-13 14:55
> I'm closing this as there's no minimal repro available. I'm happy to reopen if you're able to provide a more directed example that shows the issue.

hi，nornagon，Same issue here

**Comment by Durgaprasad-Budhwani** [comment] 2021-10-08 20:05
Team, can we work on fixing this in the upstream solution?

**Comment by mayuresh-tech9** [comment] 2021-10-13 12:42
Any update on this issue?

**Comment by sudhirk496** [comment] 2021-10-13 12:44
Facing the same issue, is there any PR raised for fixing this?

**Comment by asineth0** [comment] 2021-10-13 12:46
I'd like to add that this is something that already works in some popular Electron apps (eg. Discord, Teams). It would be nice to have it implemented properly upstream as well.

**Comment by WesUnwin** [comment] 2021-11-16 19:38
Have also encountered this issue. Am using Electron 15.0.0. Am going to attempt the above workaround involving creating a custom electron package. Which there was even more steps/documentation on how to exactly do this.

+1 for requesting this to be fixed properly, in the official electron package, to avoid workarounds.

**Comment by Durgaprasad-Budhwani** [comment] 2021-11-22 17:13
Team, any update will be much appreciated.

**Comment by kiritnarain** [comment] 2021-12-02 05:59
Would be great to get this merged in

**Comment by asineth0** [comment] 2021-12-02 06:01
Any updates on this? Is there anything I could do to move this forward or help things along here?

**Comment by Durgaprasad-Budhwani** [comment] 2021-12-07 18:14
Any update on this issue will be much appreciated.

**Comment by Durgaprasad-Budhwani** [comment] 2021-12-24 06:39
Team, any update on this issue.

**Comment by codebytere** [comment] 2022-01-12 09:09
@mwcampbell fwiw your issue will get addressed 99999999x faster if you open a CL with your proposed change  - i can also try to do it if you don't have bandwidth but i might not get to it for a bit

**Comment by nornagon** [comment] 2022-02-22 00:34
According to https://bugs.chromium.org/p/chromium/issues/detail?id=1286503#c8 this is an upstream issue and is a feature request, not a bug per se. I'm marking this blocked/upstream to reflect that.

**Comment by berkon** [comment] 2022-04-22 08:35
After looking into this topic (and the associated issue opened for Chromium) and doing a lot of tests to find a possible workaround, for a few days now, there is a general question I'd like to ask. My impression is, that Chromium does nothing wrong. According to the author of this issue, the function `getDisplayMedia()` works fine in the browser and also cancels the echo there. On Electron we have to use `getUserMedia()` with specific constraints to achieve the same functionality (which lacks echo cancellation). I'm not doubting that there is a good technical reason for this, but when we consider this to be a Chromium issue, we do request from the Chromium team to implement a specific functionality (which they don't need for the browser itself) just to get it work in Electron. Thus I can understand that they do not consider this to be a bug and not high priority as well.

I'm not in the details of the Electron/Chromium code at all, but I'd just like to raise the question whether there is really no feasible way to take over the the `getDisplayMedia()` implementation.

BTW: I was able to extract the app code of MS Teams, because I wanted to know how they achieve audio sharing without echo. From what I could see, they created an own native module called "slimcore" (not to be confused with a module of the same name which was removed from npm registry because of malicious code!) which seems to handle this. If someone want's to have a look as well (and maybe find out more), here is how to enable the developer tools on in Teams:

7x left-click on Teams tray icon. Then right-click and you get additional tray menu options which let you open the developer tools 😉.

**Comment by berkon** [comment] 2022-04-22 08:47
If we definitely can't switch to `getDisplayMedia()`, wouldn't it be possible to add a temporary method to enable the workaround proposed by @dx200010 explicitly until a final solution is implemented? I could think of a:

- command line switch
- `getUserMedia()` constraint
- environment variable
- etc.

**Comment by berkon** [comment] 2022-06-16 09:57
@Apak00, I guess you probably solved the issue with building your app with a custom Electron build meanwhile. I had the same problem. My impression is that electron-builder is not using the Electron binaries installed in node_modules folder. Instead it seems to just look for the version installed there, but then downloads it from the server by itself, thus making it impossible to use a private Electron build. I found a way to workaround this by using the win-unpacked folder, by replacing the Electron files by my self-built ones manually. Its not nice, but it works. So in case others ran into the same issue: https://stackoverflow.com/questions/72633870/how-to-use-self-built-electron-binaries-with-electron-builder If someone knows how to properly use a self-built Electron in a an app please let me know/post a better answer on Stackoverflow. ;-) Thanks!

**Comment by Apak00** [comment] 2022-06-16 10:05
I guess you are looking for 'electronDist' property on electron-builder configs, here;
https://www.electron.build/configuration/configuration.html

**Comment by asineth0** [comment] 2022-06-16 15:47
I just ended up writing an entire separate media engine for my app in native C++/Win32. Unfortunately, Electron almost never fixes or adds anything unless some major company needs it.

**Comment by bzmaxat** [comment] 2022-08-01 05:27
I built my own electron with the suggested changes and ran my application from it. Although the `stream.getAudioTracks()[0].getSettings()` shows that `echoCancellation: true`, the participants of the stream still hear their own voice. Any thoughts on how to fix this? I am using Electron v13.6.9

**Comment by berkon** [comment] 2022-08-01 07:49
@bzmaxat, did you see Apak00's post regarding the `electronDist` attribute? In my case that worked. If it doesn't, then I'd guess that something went wrong with the compilation. To be honest, I wouldn't trust the content of the `echoCancellation` attribute in this specific case.

**Comment by bukharin** [comment] 2022-10-31 05:09
Bump

**Comment by nornagon** [comment] 2022-10-31 17:58
FYI `getDisplayMedia` works in Electron now: https://github.com/electron/electron/pull/30702

**Comment by berkon** [comment] 2022-11-02 09:44
@nornagon, I tried to use `getDisplayMedia()` with Electron **22.0.0-beta.1** (on beta 2 and 3 devtools are not working!). But I'm getting `Uncaught (in promise) DOMException: Not supported`

**Comment by nornagon** [comment] 2022-11-02 20:14
@berkon please open a new issue with an example gist. Note that you'll have to install a handler in the main process using [setDisplayMediaHandler](https://github.com/electron/electron/blob/main/docs/api/session.md#sessetdisplaymediarequesthandlerhandler).

**Comment by bukharin** [comment] 2022-11-03 02:41
Support for getDisplayMedia apu does not related to this issue

**Comment by berkon** [comment] 2022-11-03 08:30
You were absolutely right @nornagon! I adapted @Apak00 's demo and it works fine now. As you said, it is important to add the handler in Main. So I guess this issue can be closed once Electron 22 is released.

**Comment by bukharin** [comment] 2022-11-03 17:11
@berkon Could you provide an adapted demo?

**Comment by MustafaEminn** [comment] 2022-12-02 09:21
Please could someone open pr for this issue? The issue opened 1 year ago but still not solved on Electron codebase.

**Comment by saghul** [comment] 2022-12-02 11:45
Have you re-tested now what `getDisplayMedia` is available?

**Comment by MustafaEminn** [comment] 2022-12-02 13:33
I did not test getDisplayMedia because has not good browser compatibility

**Comment by saghul** [comment] 2022-12-02 17:54
That's absolutely not true. Also this is Electron we're talking about so even if you were right, that wouldn't apply here.

**Comment by kycnexynpuwejl** [comment] 2023-04-02 17:53
bump

**Comment by kycnexynpuwejl** [comment] 2023-04-02 17:55
can anyone share custom electron build with updated(commented or removed) line blink::IsScreenCaptureMediaType(device.type)?
it's kind of magic for me to build custom electron with these depot_tool and gclient.

**Comment by codebytere** [comment] 2023-04-03 13:08
This should be closed by https://github.com/electron/electron/pull/37315

**Closed by codebytere** 2023-04-03 13:08 UTC
Labels: platform/windows, bug :beetle:, blocked/upstream ❌, 9-x-y, 10-x-y, 11-x-y, has-repro-repo, component/desktopcapturer, 13-x-y

**Comment by simo-an** [comment] 2023-08-17 04:09
set `enableLocalEcho` to `true` at `ses.setDisplayMediaRequestHandler(handler)` will cancel all the voice ?

**Comment by ProdigyView** [comment] 2024-02-06 12:24
bump

**Comment by yutokawasaki** [comment] 2024-08-22 13:20
bump

**Comment by SupertigerDev** [comment] 2024-10-12 10:33
bump
