### ISSUE TITLE
[Bug]: Electron 30 Menu in toolbar - font has changed from v29. 

### ISSUE THREAD

**Issue by geetee24** [electron/electron#42262] opened 2024-05-23 21:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

29

### Expected Behavior

want same font as in e29.

### Actual Behavior

want same font as in e29.   now in e30 font is too bold!   How to revert it please

### Testcase Gist URL

na

### Additional Information

na

**Comment by personalizedrefrigerator** [comment] 2024-05-30 02:59
I'm also experiencing this on Electron 30.

## Screenshot comparison

**Electron 29**:
![screenshot](https://github.com/electron/electron/assets/46334387/01f8e688-793a-4b67-b680-9ddc312d1f6c)

**Electron 30**:
![screenshot](https://github.com/electron/electron/assets/46334387/249c396d-dd43-493e-a475-e83341668b13)


This is with the default Electron Fiddle template (Electron Fiddle 0.36.2).

**Comment by mlaurencin** [comment] 2024-06-27 19:14
It is possible that these stylistic changes are done upstream and we inherit them. Are these changes present in Chromium as well? If not, could you please provide a reproduction method as asked for in [this above message](https://github.com/electron/electron/issues/42262#issuecomment-2128208946)?

I'm adding https://github.com/electron/electron/labels/blocked%2Fneed-info%20%E2%9D%8C for this reason. After you confirm where these changes are present and make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by personalizedrefrigerator** [comment] 2024-07-05 21:31
> Are these changes present in Chromium as well?

**On Linux**: These changes are likely inherited from Chromium — the updated right-click menu style in Electron's development tools matches the style of the right-click menu in Chromium's development tools (I'm testing this with the "Elements" tab).

Note that the original issue is specific to Windows 10.

**Comment by askiiart** [comment] 2024-08-02 18:44
I can confirm that on Linux, the change seems to be inherited from Chromium. Chromium 120.0.6099.212 has the old style of menus, while Chromium 126.0.6478.182 has the new menu style.

**Comment by Tatsh** [comment] 2024-08-05 16:45
Sad. The chance of getting Google to realise this is an issue, give an option or to undo the change is about 0%.

**Comment by medovina** [comment] 2024-08-05 17:24
> Sad. The chance of getting Google to realise this is an issue, give an option, or undo the change is about 0%.

Um, Microsoft has a market cap of $3 trillion.  You don't think they are able to get Google's attention when necessary?  :)

**Comment by Tatsh** [comment] 2024-08-05 20:52
> > Sad. The chance of getting Google to realise this is an issue, give an option, or undo the change is about 0%.
> 
> Um, Microsoft has a market cap of $3 trillion. You don't think they are able to get Google's attention when necessary? :)

They either didn't or don't want to convince Google to not go forward with MV3 despite universally negative feedback.

What I've noticed about the Chromium project especially is once they make a decision, they never make an option to allow prior behaviour and they rarely revert the change. Google likely thinks the enlarged font is good for touch screens or something and they don't want to maintain 2 versions of the experience ('never give options' seems to be their motto).

**Comment by RokeJulianLockhart** [comment] 2024-08-07 15:25
> https://github.com/electron/electron/issues/42262#issuecomment-2138583635

This looks rather similar to native GTK context menus instead of custom-drawn ones, which would be in improvement, if the padding wasn't so bonkers: https://github.com/microsoft/vscode/issues/225055#issue-2453505666

**Comment by firavoyage** [comment] 2024-08-20 15:33
sadness.
using old revision forever...

**Comment by Vallek** [comment] 2024-08-23 11:52
The fact that chromium devs thought it was a good idea to do that without giving any options and then every single electron app just rolled with it is insane. The absolute state of modern "desktop" software.

**Comment by flying-sheep** [comment] 2024-08-23 13:15
Does anyone have a Chromium bug tracker link? I can’t find anything useful there …

I think even if Chromium doesn‘t consider this inconsistent mess a bug, Electron should show menus by default with the OS’s default font rendering for menus:

Electron’s purpose is different from Chromium’s, since Chromium can control where to show how many context menu entries. So if Chromium’s devs feel like “we only show two of them in many cases anyway”, that doesn’t apply to Electron, whose users write desktop applications that might need many entries.

**Comment by codebytere** [comment] 2024-09-05 10:24
Tracked to https://chromium.googlesource.com/chromium/src/+log/123.0.6296.0..123.0.6312.5?n=10000&pretty=full

**Comment by codebytere** [comment] 2024-09-12 15:13
Hey folks - I've determined this is unfortunately part of Chrome Refresh 2023.

We inherited it in https://chromium.googlesource.com/chromium/src/+log/123.0.6296.0..123.0.6312.5?n=10000&pretty=full via https://chromium-review.googlesource.com/c/chromium/src/+/5247338, when they enabled the flag by default (and then later removed it entirely). It's not clear as yet what a potential path forward is, as Chrome changed this intentionally with no intent to revert or consider reverting it.

**Comment by nicolas17** [comment] 2024-12-12 02:37
This is definitely affecting me. When VSCode started getting the huge fonts in menus, I downgraded and didn't upgrade again since. The context menu in the editor barely fits in my screen height.

**Comment by ruvkr** [comment] 2024-12-13 05:50
Scrolling on that is the most horrifying experience I endure daily

**Comment by elamperti** [comment] 2024-12-14 13:56
The gigantic context menus are painful to use, it's a continous struggle. There must be a way around it 😕

**Comment by codebytere** [comment] 2024-12-16 08:58
As a follow-up to the above - there's nothing we can do on our end about this short of reverting it and we're not going to diverge from Chromium in this way as it'd be increasingly untenable over time. You are more than welcome to open an issue upstream at https://issues.chromium.org - any changes they then make we'd be able to leverage.

**Closed by codebytere** 2024-12-16 08:58 UTC
Labels: bug :beetle:, blocked/upstream ❌, status/confirmed, 30-x-y

**Comment by RokeJulianLockhart** [comment] 2024-12-16 11:44
> You are more than welcome to open an issue upstream at https://issues.chromium.org/ - any changes they then make we'd be able to leverage.

@codebytere, https://issues.chromium.org/issues/330373923 appears to be the issue to follow.

**Comment by positron96** [comment] 2025-03-10 22:17
Oh, I never noticed that it cannot go outside window boundaries, but indeed it can't. Thanks for clarifying!
