### ISSUE TITLE
App window not hiding on dock right click hide (MacOS)

### ISSUE THREAD

**Issue by icevita** [electron/electron#10034] opened 2017-07-17 07:28 UTC
Steps to reproduce:

1. git clone https://github.com/electron/electron-quick-start
2. cd electron-quick-start
3. npm install
4. npm start
5. Cmd+Shift+I (to open chrom dev tool)
in dev tools console write:
6. require('electron').remote.app.dock.hide()
7. require('electron').remote.app.dock.show()
8. dock icon right click -> Hide

Actual behavior:
electron window is not hiding

Expected behavior:
electron window is hiding

p.s.
tried latest v1.6.11 version of electron and beta version v1.7.4 beta also

**Comment by shubham2892** [comment] 2017-07-20 01:58
@icevita I was not able to reproduce the issue, may be you can make a small video highlighting the issue will help.

**Comment by icevita** [comment] 2017-07-20 04:51
Here is the video https://www.dropbox.com/s/09uqyo92smt8t32/bug.mov?dl=0

**Comment by shubham2892** [comment] 2017-07-20 19:13
@icevita Thanks for the video. I was able to reproduce the issue, but it is only happening when windows of all other open application are minimized. If there is another window open, electron window is hiding properly.

**Comment by codebytere** [comment] 2018-09-24 05:05
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 05:05 UTC
Labels: bug :beetle:, platform/macOS, version/1.6.x, version/1.7.x
