### ISSUE TITLE
DevTools break without app.setPath.

### ISSUE THREAD

**Issue by wcatron** [electron/electron#19854] opened 2019-08-21 00:06 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.3
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * Unknown this was a refactor of an application that was working using `electron-compile`.  Since that's being deprecated I refactored to `electron-webpack` and that's when this occurred.

### Expected Behavior
React DevTools load normally.

### Actual Behavior
Error in console and devtools do not show up in the inspector. "Warning: The installed version of React DevTools is too old and will not work with the current version of React. Please update React DevTools. https://fb.me/react-devtools"

### To Reproduce
Clone https://github.com/biggyspender/electron-typescript-react-redux-vscode-boilerplate
Comment out the `setPath` call in `./src/main/setAppName.ts`

### Screenshots
without the calling `app.setPath`
<img width="1293" alt="Screen Shot 2019-08-20 at 8 02 35 PM" src="https://user-images.githubusercontent.com/5385284/63392627-75724300-c385-11e9-9e28-f437a76ec6d7.png">

with calling `app.setPath`
<img width="1460" alt="Screen Shot 2019-08-20 at 8 03 41 PM" src="https://user-images.githubusercontent.com/5385284/63392702-b10d0d00-c385-11e9-8066-4ddc857d7dbe.png">

**Comment by codebytere** [comment] 2019-08-21 15:05
@wcatron at the moment, especially given the fact that you noted you just refactored to `electron-webpack`, it's not clear that the locus of this issue is Electron itself. In order for us to be able to investigate this, we'll need a repro that demonstrates this to be an Electron-specific issue and not one potentially caused by ecosystem tooling.

**Comment by ckerr** [comment] 2019-08-21 15:16
@codebytere is correct, it's not clear that this is an Electron issue rather than something dependent on your other tools or on the `electron-starter` code itself. Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

That said, I was curious about this bug and gave the repo  you mentioned a spin. If you don't set the `userData` path, it's possible that some default folder is getting used instead (e.g. `/home/username/.config/Electron`) and that folder has some config data in there that somehow is confusing this app. The app itself doesn't touch the `userData` directory again. When I look for `app.getPath('userData')` in `node_modules/`, though, I see that `electron-json-storage` and `electron-devtools-installer` both use it. So, my _guess_ is that maybe `electron-devtools-installer` is getting confused by config files in a different `userData` directory from some other Electron application that you've run in the past.

**Comment by codebytere** [comment] 2019-09-06 15:30
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2019-09-06 15:30 UTC
Labels: 6-0-x, blocked/need-info ❌, platform/macOS
