### ISSUE TITLE
Links inside webview are not firing new-window event

### ISSUE THREAD

**Issue by sergeyd63** [electron/electron#31117] opened 2021-09-24 19:57 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

10.4.7

### Expected Behavior

While clicking on a link inside webview trigger a new-window event

### Actual Behavior

No new-window event is triggered 

### Additional Information

Did not find any deprecation notices for the new-window event on webview
When i add `allowpopups` to webview it works (opens 2 windows for some reason, but i didn't dig into it)
When i switch to the older app version, based on Electron 10, everything works fine.
Also tried different settings for `nativeWindowOpen` true/false and it didn't have any effect.

If anyone has any idea/direction would appretiate.
Thanks

**Comment by codebytere** [comment] 2021-09-27 10:23
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by sergeyd63** [comment] 2021-09-27 17:16
added that (nice tool)
i test on the links on top - **Releases** and **GitHub**
they should open in new window

i added **_allowpopups_** and it works, once you remove that the links are not working

[https://gist.github.com/sergeyd63/ff0a436e706272f441d974edd3163175](url)

please send help :)

thank you

**Comment by codebytere** [comment] 2021-11-03 08:19
@sergeyd63  the `new-window` event is deprecated as [noted in docs](https://github.com/electron/electron/blob/f8e6d45b7037e4017d1afbe66c102acbe169cd68/docs/breaking-changes.md#L289-L302) - you should be using `setWindowOpenHandler` instead.

**Closed by codebytere** 2021-11-03 08:19 UTC
Labels: platform/windows, bug :beetle:, 15-x-y

**Comment by TanninOne** [comment] 2021-11-03 09:30
@codebytere It is still an api that exists and it is still broken, so why did you close this? Deprecated means "please migrate" not "broken" otherwise why not just remove it?
It's not actually declared deprecated in the docs: https://www.electronjs.org/docs/latest/api/webview-tag, so basically this should be two open bug reports not one closed one.
Fix the api and fix the docs please.
E.g. how would one even use setWindowOpenHandler to handle open requests from a webview? Even if it did work I wouldn't know _which_ webview emitted the event? Your fiddle doesn't demonstrate that.

**Comment by wangxueliang** [comment] 2021-12-14 08:33
@TanninOne   because ”nativewindopen“ is set to true by default, please set 'webreferences = "nativewindopen = no"' on the WebView tab if necessary,  new-window is work
