### ISSUE TITLE
I want to create an booklist app by electron, and i have a problem that  i don´t know how to fix

### ISSUE THREAD

**Issue by juliohsu** [electron/electron#24786] opened 2020-07-29 20:58 UTC
--------------------------------------------------------------------------------------------------------------------------------------------
*App threw an error during load
ReferenceError: document is not defined
    at Object.<anonymous> (C:\Users\tnt70\OneDrive\?rea de Trabalho\booklist project with problem\Booklist\main.js:148:4)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at loadApplicationPackage (C:\Users\tnt70\OneDrive\?rea de Trabalho\booklist project with problem\Booklist\node_modules\electron\dist\resources\default_app.asar\main.js:109:16)
    at Object.<anonymous> (C:\Users\tnt70\OneDrive\?rea de Trabalho\booklist project with problem\Booklist\node_modules\electron\dist\resources\default_app.asar\main.js:155:9)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)*
-------------------------------------------------------------------------------------------------------------------------------------------
In this file you can find my project files such as main.js, html, package.json, etc...

https://drive.google.com/drive/folders/1ZXpL5MZkbd9JyWqUu-UsoHdFQRLZOBPm?usp=sharing

**Comment by ckerr** [comment] 2020-07-29 21:19
Hi @juliohsu, thanks for reaching out!

Your source code appears to be behind a permission wall. Also, we generally try to not triage other projects' code because, when doing so, it's often difficult to tell whether the core issue is in Electron or in the application.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

In addition, you seem to have skipped the issue template -- I don't know what version of Electron you're using, what platform you're using, etc. -- because of all these issues in aggregate, I'm going to close this issue. If you'd like to continue with this, please file a new issue that provides the information requested by the issue template *and* contains a standalone repro from electron-quick-start.

Thanks in advance! Your help is appreciated.

**Closed by ckerr** 2020-07-29 21:19 UTC

**Comment by juliohsu** [comment] 2020-07-31 12:30
I have forked electron-quick-start just like what you said, but i didn´t find any problem of that.
Please tell me what should i do
