### ISSUE TITLE
Renderer process crashes on Windows on fs.watch call against network shares

### ISSUE THREAD

**Issue by antelle** [electron/electron#5186] opened 2016-04-17 15:12 UTC
* Electron version: 0.37.6
* Operating system: Windows 10 x64
* node.js: 5.10.1

1. launch Windows 10 inside a virtualbox
2. add a shared folder, e.g. HostTemp
3. reboot
4. find out mounted name of the shared folder (e.g. `HostTemp` => `E:`)
5. launch from Electron app window:
```javascript
require('fs').watch('e:\\', { persistent: false })
```

Actual result: crash, devtools become disconnected from target
Expected: error, like in node.js

```
>node
> w = fs.watch('e:\\', { persistent: false })
Error: watch e:\ EISDIR
```

Here's a stack trace from WinDBG (it shows failure in node.js code but node.js doesn't fail on this call).
```
Microsoft (R) Windows Debugger Version 10.0.10586.567 X86
Copyright (c) Microsoft Corporation. All rights reserved.

*** wait with pending attach
Symbol search path is: srv*
Executable search path is: 
ModLoad: 002b0000 039c3000   C:\Users\Antelle\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\electron.exe
ModLoad: 77e70000 77fe9000   C:\Windows\SYSTEM32\ntdll.dll
ModLoad: 753b0000 754a0000   C:\Windows\SYSTEM32\KERNEL32.DLL
ModLoad: 751d0000 75346000   C:\Windows\SYSTEM32\KERNELBASE.dll
ModLoad: 75a30000 75aee000   C:\Windows\SYSTEM32\COMDLG32.dll
ModLoad: 758d0000 7598e000   C:\Windows\SYSTEM32\msvcrt.dll
ModLoad: 77910000 77aca000   C:\Windows\SYSTEM32\combase.dll
ModLoad: 757c0000 7586c000   C:\Windows\SYSTEM32\RPCRT4.dll
ModLoad: 74f40000 74f5e000   C:\Windows\SYSTEM32\SspiCli.dll
ModLoad: 74f30000 74f3a000   C:\Windows\SYSTEM32\CRYPTBASE.dll
ModLoad: 74ed0000 74f29000   C:\Windows\SYSTEM32\bcryptPrimitives.dll
ModLoad: 76130000 76173000   C:\Windows\SYSTEM32\sechost.dll
ModLoad: 77de0000 77e6d000   C:\Windows\SYSTEM32\shcore.dll
ModLoad: 754d0000 75610000   C:\Windows\SYSTEM32\USER32.dll
ModLoad: 75fd0000 7611d000   C:\Windows\SYSTEM32\GDI32.dll
ModLoad: 77c70000 77cb4000   C:\Windows\SYSTEM32\SHLWAPI.dll
ModLoad: 76190000 77587000   C:\Windows\SYSTEM32\SHELL32.dll
ModLoad: 75af0000 75fcc000   C:\Windows\SYSTEM32\windows.storage.dll
ModLoad: 77890000 7790b000   C:\Windows\SYSTEM32\advapi32.dll
ModLoad: 77c50000 77c5c000   C:\Windows\SYSTEM32\kernel.appcore.dll
ModLoad: 77c00000 77c44000   C:\Windows\SYSTEM32\powrprof.dll
ModLoad: 77c60000 77c6f000   C:\Windows\SYSTEM32\profapi.dll
ModLoad: 77590000 77596000   C:\Windows\SYSTEM32\PSAPI.DLL
ModLoad: 75350000 753ac000   C:\Windows\SYSTEM32\WS2_32.dll
ModLoad: 775c0000 775c7000   C:\Windows\SYSTEM32\NSI.dll
ModLoad: 77ad0000 77bba000   C:\Windows\SYSTEM32\ole32.dll
ModLoad: 74fb0000 75042000   C:\Windows\SYSTEM32\OLEAUT32.dll
ModLoad: 75050000 751c5000   C:\Windows\SYSTEM32\CRYPT32.dll
ModLoad: 76120000 7612e000   C:\Windows\SYSTEM32\MSASN1.dll
ModLoad: 754a0000 754cb000   C:\Windows\SYSTEM32\IMM32.dll
ModLoad: 77cc0000 77de0000   C:\Windows\SYSTEM32\MSCTF.dll
ModLoad: 70190000 70b9a000   C:\Users\Antelle\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\node.dll
ModLoad: 72e10000 73019000   C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.10240.16384_none_3bccb1ff6bcd1849\COMCTL32.dll
ModLoad: 72840000 72a7e000   C:\Windows\SYSTEM32\WININET.dll
ModLoad: 72b10000 72e0a000   C:\Users\Antelle\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\ffmpeg.dll
ModLoad: 732e0000 73310000   C:\Windows\SYSTEM32\IPHLPAPI.DLL
ModLoad: 72680000 727bf000   C:\Windows\SYSTEM32\dbghelp.dll
ModLoad: 72160000 7217d000   C:\Windows\SYSTEM32\dwmapi.dll
ModLoad: 73050000 73063000   C:\Windows\SYSTEM32\NETAPI32.dll
ModLoad: 73030000 73046000   C:\Windows\SYSTEM32\USP10.dll
ModLoad: 74de0000 74de8000   C:\Windows\SYSTEM32\VERSION.dll
ModLoad: 72aa0000 72b07000   C:\Windows\SYSTEM32\WINSPOOL.DRV
ModLoad: 727c0000 72831000   C:\Users\Antelle\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\MSVCP120.dll
ModLoad: 700a0000 7018e000   C:\Users\Antelle\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\MSVCR120.dll
ModLoad: 71470000 715d0000   C:\Windows\SYSTEM32\urlmon.dll
ModLoad: 71860000 71907000   C:\Windows\SYSTEM32\WINHTTP.dll
ModLoad: 720b0000 720ba000   C:\Windows\SYSTEM32\Secur32.dll
ModLoad: 70d80000 70d94000   C:\Windows\SYSTEM32\dhcpcsvc.DLL
ModLoad: 73020000 7302f000   C:\Windows\SYSTEM32\WTSAPI32.dll
ModLoad: 70040000 70093000   C:\Windows\SYSTEM32\OLEACC.dll
ModLoad: 73130000 73154000   C:\Windows\SYSTEM32\WINMM.dll
ModLoad: 6fe20000 70033000   C:\Windows\SYSTEM32\d3d11.dll
ModLoad: 73110000 73129000   C:\Windows\SYSTEM32\USERENV.dll
ModLoad: 732d0000 732d8000   C:\Windows\SYSTEM32\WINNSI.DLL
ModLoad: 72a90000 72aa0000   C:\Windows\SYSTEM32\wkscli.dll
ModLoad: 70dc0000 70ddc000   C:\Windows\SYSTEM32\srvcli.dll
ModLoad: 72a80000 72a8a000   C:\Windows\SYSTEM32\netutils.dll
ModLoad: 733c0000 733db000   C:\Windows\SYSTEM32\bcrypt.dll
ModLoad: 711a0000 71461000   C:\Windows\SYSTEM32\iertutil.dll
ModLoad: 730e0000 73103000   C:\Windows\SYSTEM32\WINMMBASE.dll
ModLoad: 77bc0000 77bf6000   C:\Windows\SYSTEM32\cfgmgr32.dll
ModLoad: 6fda0000 6fe1e000   C:\Windows\SYSTEM32\dxgi.dll
ModLoad: 73160000 73181000   C:\Windows\SYSTEM32\DEVOBJ.dll
ModLoad: 73220000 7326e000   C:\Windows\system32\mswsock.dll
ModLoad: 6fbb0000 6fda0000   C:\Windows\SYSTEM32\dwrite.dll
ModLoad: 70c80000 70d04000   C:\Windows\SYSTEM32\DNSAPI.dll
ModLoad: 70da0000 70db3000   C:\Windows\SYSTEM32\dhcpcsvc6.DLL
ModLoad: 730c0000 730d2000   C:\Windows\system32\napinsp.dll
ModLoad: 730a0000 730b6000   C:\Windows\system32\pnrpnsp.dll
ModLoad: 73080000 73093000   C:\Windows\system32\NLAapi.dll
ModLoad: 73070000 7307b000   C:\Windows\System32\winrnr.dll
ModLoad: 720e0000 72155000   C:\Windows\system32\uxtheme.dll
(af0.d60): Break instruction exception - code 80000003 (first chance)
eax=7ef47000 ebx=00000000 ecx=77f10f50 edx=77f10f50 esi=77f10f50 edi=77f10f50
eip=77edac20 esp=09f0fd5c ebp=09f0fd88 iopl=0         nv up ei pl zr na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000246
ntdll!DbgBreakPoint:
77edac20 cc              int     3
0:011> g
Critical error detected c0000374
(af0.11fc): Break instruction exception - code 80000003 (first chance)
eax=00000000 ebx=77f764b8 ecx=c0000374 edx=00000021 esi=00000002 edi=07c63cf8
eip=77f4623f esp=03b5d8c0 ebp=03b5d950 iopl=0         nv up ei pl zr na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000246
ntdll!RtlReportCriticalFailure+0x46:
77f4623f cc              int     3

************* Symbol Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*c:\symbols*https://msdl.microsoft.com/download/symbols*http://54.249.141.255:8086/atom-shell/symbols
0:000> k
 # ChildEBP RetAddr  
00 03b5d950 77f4a7bf ntdll!RtlReportCriticalFailure+0x46
01 03b5d960 77eec7a8 ntdll!RtlpHeapHandleError+0x1c
02 03b5d990 77eec3cd ntdll!RtlpLogHeapFailure+0x9f
03 03b5d9cc 77eac6dc ntdll!RtlpFreeHeapInternal+0xdb
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Users\Antelle\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\MSVCR120.dll - 
04 03b5d9dc 700aecfa ntdll!RtlFreeHeap+0x2c
*** WARNING: Unable to verify checksum for C:\Users\Antelle\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\node.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Users\Antelle\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\node.dll - 
WARNING: Stack unwind information not available. Following frames may be wrong.
05 03b5d9f0 7056f03c MSVCR120!free+0x1a
06 03b5da04 7056ebc2 node!uv_fs_event_stop+0x83
07 03b5da14 7056de9a node!uv_thread_self+0x33
08 03b5da2c 701a9b79 node!uv_close+0xc9
09 03b5da4c 701a47d7 node!v8::String::Cast+0x2b9a
0a 03b5da5c 701a4c1f node!node::Environment::PrintSyncTrace+0x43d
0b 03b5de94 7040f54e node!v8::Value::QuickIsString+0x19e
0c 03b5dec8 7038ac38 node!v8::String::WriteUtf8+0x1b04e
0d 03b5df58 70393c6f node!v8::Locker::IsLocked+0x55948
0e 03b5df80 2db0a43c node!v8::Locker::IsLocked+0x5e97f
0f 03b5dfa0 1b38a3d0 0x2db0a43c
10 03b5dfd0 1b389c4c 0x1b38a3d0
11 03b5e004 1b389966 0x1b389c4c
12 03b5e024 2db2f441 0x1b389966
13 03b5e040 2db1a27f 0x2db2f441
14 03b5e06c 70674750 0x2db1a27f
15 03b5e0b4 70673fce node!uv_udp_set_ttl+0xf47c2
16 03b5e100 703edfa8 node!uv_udp_set_ttl+0xf4040
*** WARNING: Unable to verify checksum for C:\Users\Antelle\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\electron.exe
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Users\Antelle\AppData\Roaming\npm\node_modules\electron-prebuilt\dist\electron.exe - 
17 03b5e150 01ecfc63 node!v8::Script::Run+0x168
18 03b5e1c8 02287460 electron!icu_54::RegexPattern::operator!=+0x31ef73
19 03b5e224 7040f54e electron!icu_54::IDNAInfo::reset+0x294370
1a 03b5e258 7038ac38 node!v8::String::WriteUtf8+0x1b04e
1b 03b5e2e8 70393c6f node!v8::Locker::IsLocked+0x55948
1c 03b5e310 2db0a43c node!v8::Locker::IsLocked+0x5e97f
1d 03b5e330 1b36ecd8 0x2db0a43c
1e 03b5e36c 1b36e4f0 0x1b36ecd8
1f 03b5e39c 2db106be 0x1b36e4f0
20 03b5e3d0 1b36e410 0x2db106be
21 03b5e400 2db2f441 0x1b36e410
22 03b5e430 2db1a27f 0x2db2f441
23 03b5e45c 70674750 0x2db1a27f
24 03b5e4a4 70673fce node!uv_udp_set_ttl+0xf47c2
25 03b5e4f0 703d8b89 node!uv_udp_set_ttl+0xf4040
26 03b5e538 01ece819 node!v8::Function::Call+0x109
27 03b5e5ac 02e5573f electron!icu_54::RegexPattern::operator!=+0x31db29
28 03b5e60c 02e55588 electron!icu_54::MessagePattern::partSubstringMatches+0x88a92f
29 03b5e648 0226280f electron!icu_54::MessagePattern::partSubstringMatches+0x88a778
2a 03b5e68c 022633f6 electron!icu_54::IDNAInfo::reset+0x26f71f
2b 03b5e6b0 02263893 electron!icu_54::IDNAInfo::reset+0x270306
2c 03b5e6e4 02262a1b electron!icu_54::IDNAInfo::reset+0x2707a3
2d 03b5e724 02329c09 electron!icu_54::IDNAInfo::reset+0x26f92b
2e 03b5e7a4 0229a451 electron!icu_54::IDNAInfo::reset+0x336b19
2f 03b5e800 01d940ce electron!icu_54::IDNAInfo::reset+0x2a7361
30 03b5e874 01d96696 electron!icu_54::RegexPattern::operator!=+0x1e33de
31 03b5e8cc 0055d864 electron!icu_54::RegexPattern::operator!=+0x1e59a6
32 03b5e8ec 00b4c20b electron!icu_54::BreakIterator::isBufferClone+0x35214
33 03b5e930 00b4b5cb electron!icu_54::TimeZone::setID+0x51096b
34 03b5e968 00b4c3dd electron!icu_54::TimeZone::setID+0x50fd2b
35 03b5ea0c 00b04707 electron!icu_54::TimeZone::setID+0x510b3d
36 03b5edec 029a9f30 electron!icu_54::TimeZone::setID+0x4c8e67
37 03b5ee04 02917ff8 electron!icu_54::MessagePattern::partSubstringMatches+0x3df120
38 03b5eeac 00e07fb9 electron!icu_54::MessagePattern::partSubstringMatches+0x34d1e8
39 03b5ef08 00e0837c electron!icu_54::RuleBasedBreakIterator::operator!=+0xddfb9
3a 03b5ef18 004bfd05 electron!icu_54::RuleBasedBreakIterator::operator!=+0xde37c
3b 03b5ef74 018d6e35 electron!GetHandleVerifier+0x26c15
3c 03b5f050 018d672d electron!IsSandboxedProcess+0x11895
3d 03b5f198 018d705a electron!IsSandboxedProcess+0x1118d
3e 03b5f1b8 004bfd05 electron!IsSandboxedProcess+0x11aba
3f 03b5f214 0048a1fc electron!GetHandleVerifier+0x26c15
40 03b5f358 004898d9 electron+0x1da1fc
41 03b5f3dc 004c1f77 electron+0x1d98d9
42 03b5f400 00489ff0 electron!GetHandleVerifier+0x28e87
43 03b5f430 00489fad electron+0x1d9ff0
44 03b5f458 00b22596 electron+0x1d9fad
45 03b5f61c 0059bdfe electron!icu_54::TimeZone::setID+0x4e6cf6
46 03b5f63c 0059bcad electron!icu_54::BreakIterator::isBufferClone+0x737ae
47 03b5f688 00599043 electron!icu_54::BreakIterator::isBufferClone+0x7365d
48 03b5f698 0032a13f electron!icu_54::BreakIterator::isBufferClone+0x709f3
49 03b5f73c 0255f8fa electron+0x7a13f
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Windows\SYSTEM32\KERNEL32.DLL - 
4a 03b5f788 753c3744 electron!icu_54::Transliterator::setID+0x2c91a
4b 03b5f79c 77ec9e54 KERNEL32!BaseThreadInitThunk+0x24
4c 03b5f7e4 77ec9e1f ntdll!__RtlUserThreadStart+0x2f
4d 03b5f7f4 00000000 ntdll!_RtlUserThreadStart+0x1b
```

**Comment by zcbenz** [comment] 2016-04-18 11:56
It looks like memory corruption, I don't have idea why it happened. Also I'm unable to reproduce on the Parallels virtual machine, so it probably only happens when using Virtualbox.

**Comment by zcbenz** [comment] 2016-06-14 05:19
I'm closing this as won't fix since it is very likely a Virtualbox bug.

**Closed by zcbenz** 2016-06-14 05:19 UTC
Labels: bug, crash
