### ISSUE TITLE
webContents.on('will-navigate'), event.preventDefault(); BUG

### ISSUE THREAD

**Issue by bdxing** [electron/electron#7105] opened 2016-09-06 08:27 UTC
* Electron version:1.3.4
* Operating system:window 7

`event.preventDefault();`Can't stop the loading in the iframe events in the rendering process.

<a href="github.com"></a>

**Comment by bontibon** [comment] 2016-09-06 13:29
#1378

**Comment by kevinsawicki** [comment] 2016-09-06 17:08
Closing as duplicate of #1378

**Closed by kevinsawicki** 2016-09-06 17:08 UTC

**Comment by deepak1556** [comment] 2016-09-06 20:21
@kevinsawicki i believe this issue is about `will-navigate` not being triggered in sub-frame loads, its different from the webview issue.

**Comment by kevinsawicki** [comment] 2016-09-06 20:26
Thanks @deepak1556, does seem the same as #7097 to you though? Maybe I should reopen that one instead?

**Comment by deepak1556** [comment] 2016-09-06 20:29
> Maybe I should reopen that one instead?

Yup, both are by the same OP :)

**Comment by ulihecht** [comment] 2018-01-31 12:24
Please re-open. I still have this problem. event.preventDefault() in "will-navigate" has no effect and I'm not talking about iframes like in #7097. It doesn't work in general. The event "will-navigate" itself is called properly but it will also navigate if you call preventDefault()

OS: Windows 7 64Bit
Electron 1.6.16

**Comment by MarshallOfSound** [comment] 2018-01-31 12:35
@ulihecht If you provide a minimal repro case that demonstrates this bug still exists we can reopen

**Comment by ulihecht** [comment] 2018-02-01 10:33
While I tried to reproduce this case it turned out that preventDefault is only ignored in will-navigate, if you open a browser window inside the renderer process. Everything works fine for browser windows created in the main process. To keep it minimalistic, I use a data URL to load the HTML into the outer browser window. However, I'm experiencing the same problem when loading an external HTML document:

<pre><code class="js">
const {app, BrowserWindow} = require('electron');
app.on("ready", function() {
   var html =
      '<script>' +
      '  var b2 = new (require("electron").remote.BrowserWindow)();' +
      '  b2.loadURL("https://www.google.com");' +
      '  b2.webContents.on("will-navigate", function(event) {' +
      '     console.log("will-navigate triggered");' +
      '     event.preventDefault();' +
      '  })' +
      '<'+'/script>'; // Github-markdown formatting problems if I don't split script end tag ;-)
   var b = new BrowserWindow();
   b.loadURL("data:text/html,"+ encodeURIComponent(html));
   b.on("closed", function() { app.quit(); });
});
</code></pre>

**Comment by MarshallOfSound** [comment] 2018-02-01 10:39
@ulihecht See this comment that explains why `event.preventDefault()` doesn't work over the `remote` module.

https://github.com/electron/electron/pull/11679#issuecomment-359180722
