### ISSUE TITLE
Native PDF Viewer not loading PDF from Blob

### ISSUE THREAD

**Issue by RockGuitarist1** [electron/electron#13038] opened 2018-05-22 14:00 UTC
* Electron Version: 2.0.3
* Operating System (Platform and Version): Win 7
* Last known working Electron version: None

**Expected Behavior**
PDF should open with Electron's native PDF Viewer. Right now nothing shows up. I have logged the arg variable and I get back 'blob:file///......'.

I am pulling my PDF data from our API and getting back a blob with application/pdf.

```
let fileUrl = URL.createObjectURL(data);
ipcRenderer.send('show-pdf', fileUrl);
```
```
ipcMain.on('show-pdf', (event, arg) => {
let win = new BrowserWindow({
  webPreferences: {
    plugins: true
  }
});

win.loadURL(arg);
```

**Comment by mazeeblanke** [comment] 2018-06-25 17:28
I there a solution for this ?

**Comment by RockGuitarist1** [comment] 2018-06-28 13:43
I haven't heard anything yet. Still waiting. It's holding up a major web to Electron switch over here at work.

**Comment by RockGuitarist1** [comment] 2018-07-02 14:13
It looks as if Electron doesn't support loading ObjectUrls at all. The current workaround for this is to use File System and write your blob to the directory and then load the file, but that is not feasible at all. Overtime, you would end up with hundreds of random PDF files laying around in a user's directory. Hopefully an Electron contributor who has the knowledge of this topic can comment with a more accurate explanation on why Electron won't load ObjectUrls.

**Comment by jbmonroe** [comment] 2018-08-01 14:47
I have the same problem with a 3rd-party site my Electron shell has to run--the actual blob is buried to where I can't capture the URL and use the method I would normally employ (download PDF and put it in a queue folder), so I'm depending on Electron to step in.  The pop-up <object> tag just shows "can't load plugin" and we stop there.  Seems to work in Chrome and probably in Chromium but I don't have any live data with which to test that assumption right now.

**Comment by jbmonroe** [comment] 2018-08-06 13:45
I've resolved my problem partially by capturing the URL of the object tag in which the embed occurs.  Instead of letting it open in the ```<object>``` tag I open a second BrowserWindow and feed the xhtml (!) into that; ```webContents.printToPDF()``` _almost_ works after that--it clips the bottom of the PDF content on each page.  It's a start, though.

**Comment by jbmonroe** [comment] 2018-08-07 07:15
The clipping of the PDF occurs at the same place where the window-rendered PDF content runs off the bottom window--so it renders the first _N_ "lines," where _N_ is the height of the window.  This seems to be an interaction with pdf-viewer, but it's still frustrating.  I already have an issue filed there asking how to remove the unnecessary "chrome" from the presentation there, or at least to gain access to the binary blob so I can drop the plain old PDF data into my queue folder.

**Comment by jbmonroe** [comment] 2018-08-08 12:58
And just when it couldn't get worse--it gets worse.  The logic for PDF printing seems to notice it has a multi-page document, but each page is just a clipped view of whatever is in the presentation window.

**Comment by RockGuitarist1** [comment] 2018-08-09 11:30
@jbmonroe Didn't know that there was a repo just for the PDF Viewer. I'll be sure to reference this post there. Seeing that that project has been dead for many months makes me believe this is not their scope any time soon. Shame on Electron.

**Comment by felixrieseberg** [comment] 2018-08-09 15:47
I’m sorry your issue isn’t getting the attention you think it deserves. Electron is an open source community project. I’m sure you’ve noticed that you didn’t pay anything for Electron and that all the people investing their hours into this project are either sponsored by companies that currently have different priorities or are themselves motivated by different goals.

A PR that closes this issue would be most welcome. If you need this issue to be fixed and you are unable to either do it yourself or sponsor someone to do it for you, I’d humbly offer the advice that “shaming” people isn’t the best way to motivate people to gift their time and effort to you.

**Comment by jbmonroe** [comment] 2018-08-09 17:33
Yeah, I get that, but on the other hand, if you can't take the fast ball, don't come to the plate.  You put something out like this, people will use it.  They might even use it for mission-critical projects, and in the main, Electron works brilliantly.  It's doing the job--and then I try to capture a document from someone else's web app, and it can't get the job done.  I would have no way of knowing that beforehand, so I committed time, resources, and the company's cash on Electron as a way to produce what we were asked to produce.

I can't even get a "yeah, here's what I'd do in that situation," and I'm not the only one begging here.  There are tickets outstanding since 2016 on issues similar to this.  I guess they're pretty busy.  I suppose I'll have to fork pdf-viewer and try to sort it out myself as a first approximation.  Yeah, no one forced me to use Electron, but it looked right as a way to frame the solution. I would think that more than an automated bot response to the OP's ticket would be warranted.

**Comment by ckerr** [comment] 2018-08-09 18:16
> I suppose I'll have to fork pdf-viewer and try to sort it out myself as a first approximation.

Thank you for this offer! The Electron maintainers group would _love_ good patches on the PDF viewer. It has fewer users than other features, so it rarely gets the attention it needs. The fulltime Electron team is small and so open source contributions from a user scratching an itch often wind up being the wind beneath Electron's wings.

It's certainly a more productive use of time than adding more "and just when it couldn't get worse--it gets worse" style comments. :smile:

**Comment by akashnimare** [comment] 2018-08-29 17:46
I have implemented the similar thing in the Zulip app. @jbmonroe, @RockGuitarist1 have a look at the PR if it helps - https://github.com/zulip/zulip-electron/pull/549

**Comment by jbmonroe** [comment] 2018-08-29 19:44
@akashnimare That is about half of the issue I have--I'd prefer to simply capture the PDF content itself and drop it into a folder.  I've already routed the URL to a Window, but the control only prints (via wc#printToPDF() what shows in the viewer, rather than the document.  At the moment I'm just trying to get the true PDF stream into a temp folder, where processes already on the machine will ship the PDF off to be printed.

**Comment by RockGuitarist1** [comment] 2018-08-30 01:27
@akashnimare From what I saw, it looks as if the PDF is saved first and then opened in a new window. Sadly we can't do that, because the PDFs we are dealing with have sensitive information on them and we cannot have these PDFs stored on our clients' computers. That's why we serve our files from a DB as a Blob.

**Comment by jbmonroe** [comment] 2018-08-30 11:05
@RockGuitarist1 I haven't seen that part of the code--got chapter and verse?  I don't have an issue dropping the PDF onto the drive--in fact, I want that.  Another standalone C++ process watches the target folder and consumes the PDFs for printing so even though there's sensitive info in the PDFs, they're not on the drive for more than milliseconds at a time.

I think I'm trying to do the same thing but the "saved" documents I get with my code are zero-length.

**Comment by RockGuitarist1** [comment] 2018-08-31 15:09
For anyone who needs to do something with their PDFs in Blob form while we wait for Blob support in PDF Viewer, you can use this:

```
let a = document.createElement('a');
document.body.appendChild(a);
let aUrl = URL.createObjectURL(data);
a.href = aUrl;
a.download = fileName;
a.click();
URL.revokeObjectURL(aUrl);
```

This will take the Blob you are getting back from your endpoint and prompt a save dialog so that your users can save it somewhere. They can then open it with Chrome, or any other PDF Viewer.

**Comment by jbmonroe** [comment] 2018-08-31 15:44
I'd love to do that--but how does one dig the blob out from the bloody Polymer link imports?

**Comment by RockGuitarist1** [comment] 2018-08-31 18:47
@jbmonroe What do you mean? I'm getting my PDF Blobs from our internal APIs.  Where you are intending on getting yours?

**Comment by RockGuitarist1** [comment] 2018-08-31 21:40
@jbmonroe If you are able to, make a jsfiddle or a repo that I can download, and i'll see if I can give you a hand. It's easier to help if I can see the code.

**Comment by jbmonroe** [comment] 2018-09-02 00:55
The code itself would be an issue because it's corp IP.  I actually don't know how the doc is rendered on the server side, and I haven't had any luck sorting out how one inserts a PDF into an <embed>, itself inside an <object>.  I rely on data supplied by the target application in order to test, and I can only get that once a week.

If you just want to hack at the Polymer bits, create a BrowserWindow and do a load URL pointed at a convenient PDF.

**Comment by weihong1028** [comment] 2018-09-07 10:27
My solution is to save the pdf file in the app's temporary directory as temp.pdf so I can use 'file:// ...'(blob://... not work) in webview or new BrowserWindow. Work for me. (Users won't feel that I saved a file)

```
// set temp.pdf path
const pdfPreviewFilePath =
  process.platform === 'darwin'
    ? `${homePath}/Library/Logs/${appName}/temp.pdf`
    : `${homePath}\\AppData\\Roaming\\${appName}\\temp.pdf`;

// save as temp.pdf
const reader = new FileReader();
reader.onload = function() {
    try {
        const fs = window.electron.remote.require('fs');
        fs.writeFileSync('${path}/temp_preview.pdf', this.result, 'binary');
        window.electron.ipcRenderer.send('pdf-viewer');
    } catch (error) {
        console.error('write file error', error);
    }
}
reader.readAsBinaryString(blob);

// open pdf viewer
ipcMain.on('pdf-viewer', () => {
    const pdfViewerConfig = {
        webPreferences: {
            plugins: true,
        },
    };
    const pdfViewer = new BrowserWindow(pdfViewerConfig);
    pdfViewer.loadURL(`file://${pdfPreviewFilePath}`); // the path of temp.pdf
});
```

**Comment by jbmonroe** [comment] 2018-09-07 10:54
I probably didn't provide one key clarification earlier--my app is just running arbitrary tenant application pages on a kiosk and at the end of the session, the user will need to print a document.  Since the tenant apps aren't mine, I can't rewrite the application every time the physical site owner wants to add a application, so I need a general, all purpose approach to detecting and redirecting an incoming PDF for printing.

Some of the web pages just render out the document in HTML and offer a button which triggers a call to ```window.print()```, which I can (and do) redirect.  I can inspect incoming HTTP response headers to look for incoming PDFs, but when the web site drops an ```<embed>``` inside an ```<object>``` into the page via JavaScript that's a bit unexpected and obscures the payload.  Once I found out that's how the application gets a PDF to the end-user, I had to inject a preload script to poll the tenant for the appearance of the ```<object>``` and pull the ```src``` attribute out and IPC that to the main code to redirect it to a new window...and that isn't the PDF--it's a partial page that invokes the embedded Polymer components in Chromium to bring up the PDF viewer.

Anyway, I can direct the user to press the download button on the viewer, intercept the download and push it to the \temp folder, and other on-kiosk processes will capture the PDF and send it to the PDF print processor.  It's not ideal, but it's what I can do.  If I could get _inside_ the PDF viewer, that would be ideal--but I haven't found a way in yet.

**Comment by RockGuitarist1** [comment] 2018-09-20 14:40
Note that in Electron v3 this no longer works. It will now prompt you to save the already saved pdf to a location of your choice.

**Comment by jbmonroe** [comment] 2018-09-20 14:51
Another thing to add to the list of reasons not to upgrade past the version of Electron I'm using.  The way they deprecated the event propagation model is another--it completely broke everything I was doing.

**Comment by jbmonroe** [comment] 2018-09-20 14:54
The link from @weihong1028 is very interesting!  I need to look into that further.

**Comment by RockGuitarist1** [comment] 2018-09-21 11:29
@weihong1028 Good thing they know what the issue is and know how to fix it.

**Comment by sofianguy** [comment] 2019-08-09 00:44
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 21:03
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 21:03 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
