### ISSUE TITLE
macOS systemPreferences.getColor values dont match when appearance theme is changed

### ISSUE THREAD

**Issue by crowlKats** [electron/electron#18699] opened 2019-06-09 09:56 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.3
* **Operating System:** macOS 10.14.5

### Expected Behavior

Update `systemPreferences.getColor` when the theme in Mojave is updated 
### Actual Behavior

the values `systemPreferences.getColor` returns are the values of the theme in which the browserwindow was created

### To Reproduce

```js
const {app, BrowserWindow, systemPreferences} = require("electron");

let mainWindow;

function updateAppearanceTheme() {
	if (systemPreferences.isDarkMode()) {
		systemPreferences.setAppLevelAppearance("dark");
	} else {
		systemPreferences.setAppLevelAppearance("light");
	}
	
	console.log(systemPreferences.getColor("window-background"));
}

systemPreferences.subscribeNotification("AppleInterfaceThemeChangedNotification", updateAppearanceTheme);

updateAppearanceTheme();


function createWindow() {
	mainWindow = new BrowserWindow({
		width: 800,
		height: 600,
		backgroundColor: systemPreferences.getColor("window-background")
	});
}

app.on("ready", createWindow);
```

**Comment by codebytere** [comment] 2019-07-18 19:26
Perhaps i'm not understanding this correctly, but in dark mode the app level appearance should be set to dark mode, and the color returned match that, yes? 

I'm not seeing the issue and cannot repro, if that's the case.

**Comment by sofianguy** [comment] 2019-08-08 23:18
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-08 23:18 UTC
Labels: 5-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS

**Comment by crowlKats** [comment] 2019-08-08 23:48
Sorry for not responding.
I dont know how to explain with words well, so here is a video showing it. Basically the value of `systemPreferences.getColor("window-background")` doesnt change even tho it should when the theme is changed

https://www.youtube.com/watch?v=7RDwCGirl44

**Comment by Tundon** [comment] 2020-07-14 05:29
This issue still exists, and I've created a repo to reproduce it. (v9.1.0)

https://github.com/Tundon/issue-18699

## To Reproduce
1. Set the system apperance to light mode, `npm install` and `npm start`
2. Watch the console, which prints:
   ```
   initial background color:  #e8e8e8
   ```
3. Change the system appearance to dark mode, note in the console:
   ```
   changed background color:  #e8e8e8
   ```

### Expected:
In step 3, the code to get color `systemPreferences.getColor("window-background")` is supposed to get dark mode background color, which should be `#252525`, but it is still getting light mode background color `#e8e8e8`

**Comment by will-stone** [comment] 2020-12-21 08:56
Hi. I'm getting this issue with v11.1.0. @sofianguy do you mind please reopening the issue? Unless there's a recommended method of adapting to dynamic colour changes?

**Comment by jcarpenter** [comment] 2021-04-16 00:12
Am also seeing broken, in the same fashion described above. Electron 12.0.2.

Between this and getColor() values not returning alphas, per #26628, this API is unfortunately broken for its intended purpose (styling to match OS). For now I'm hard coding the values.
