### ISSUE TITLE
Fix the grey line rendered at the top of window on Mojave

### ISSUE THREAD

**Issue by pronebird** [electron/electron#15008] opened 2018-10-07 12:10 UTC
* Output of `node_modules/.bin/electron --version`: 3.0.2
* Operating System (Platform and Version): macOS 10.14
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
There should be no grey line rendered at the top of the window area in frameless window. 

My conclusion is that Electron uses some obscure combination of window styles that cause this behaviour. I was able to reproduce the same appearance when using Cocoa API in the same fashion on a sample Xcode project.

**Actual behavior**
On macOS Mojave the grey line is rendered at the top of the window area even when the contents are transparent and the window is configured to be frameless.

**To Reproduce**
Fork and run https://github.com/pronebird/electron-mojave-titlebar-bug

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/pronebird/electron-mojave-titlebar-bug.git
$ npm install
$ npm start
```
**Screenshots**
<img width="363" alt="screenshot 2018-10-07 at 16 43 14" src="https://user-images.githubusercontent.com/704044/46583008-2b73bd80-ca50-11e8-8b52-0a7a9b514798.png">

( The dark background is the standard wallpaper on Mojave)

**Additional Information**

**Comment by pronebird** [comment] 2018-10-07 13:57
@MarshallOfSound on Mojave the one gets the grey line rendered above "hidden" titlebar.

**Comment by pronebird** [comment] 2018-10-07 14:17
I have tested my assumption on a new Xcode project and it seems that the combination of flags that Electron uses is not desirable. 

I was able to reproduce this by setting the following window configuration (which is pretty much what Electron does):

```swift
guard let window = view.window else { return }

window.backgroundColor = NSColor.clear
window.isOpaque = false

let defaultStyle: NSWindow.StyleMask = [.borderless, .titled]

window.titleVisibility = .hidden
window.titlebarAppearsTransparent = true
window.styleMask = defaultStyle
```

<img width="592" alt="screenshot 2018-10-07 at 16 13 09" src="https://user-images.githubusercontent.com/704044/46582748-49d7ba00-ca4c-11e8-927b-3998683ef376.png">

**Comment by MarshallOfSound** [comment] 2018-10-07 14:30
@pronebird I'm still not 100% clear on what the issue you're having is.  Can you refill out the issue template but instead of referencing electrons source code describe what isn't currently working and how it should be working.

I think you're experiencing some kind of bug with frameless windows in Mojave but from it's still unclear from your comments.

Also providing a way to reproduce whatever issue you are having would be very useful.

**Comment by pronebird** [comment] 2018-10-07 14:47
@MarshallOfSound I've added a test project that you can run to reproduce the issue.

**Comment by garshythoel** [comment] 2018-10-11 18:56
We're having the same issues

**Comment by jdsimcoe** [comment] 2018-10-30 15:47
Same here.

**Comment by KevinHughes** [comment] 2018-11-01 21:05
Same here, I can't release my app with this bug!

**Comment by KevinHughes** [comment] 2018-11-21 08:33
> Hi there, thanks for maintaining Electron. And thanks for taking care of detailing the issue @pronebird !
> 
> I'm waiting for a fix to release my app and it may be worth for me to figure out a workaround.
> Could you share a rough timeline?

See [this comment](https://github.com/electron/electron/pull/15012#issuecomment-435257268) - it's a complex issue that currently seems to be on the OS side and thus not fixable any time soon, if at all. It is affecting many apps though (see #13164).

**Comment by pronebird** [comment] 2018-11-21 11:35
@KevinHughes please do not spread fake news.

All native apps are doing fine except Electron. The problem lays in fact that Electron does not remove the titlebar for frameless windows, but instead hides it. That's why the line is still there. See my investigation above that shows that removing the titlebar solves the mystery.

@lsenta I hate to sound negative about Electron, but looking at the age of this issue which was raised well before the macOS Mojave was released, I don't think it's going to be solved anytime soon.

The best suggestion I can give at this point is to look towards going native for macOS and not depend on third-party framework like Electron.

**Comment by KevinHughes** [comment] 2018-11-21 22:00
> All native apps are doing fine except Electron. The problem lays in fact that Electron does not remove the titlebar for frameless windows, but instead hides it. That's why the line is still there. See my investigation above that shows that removing the titlebar solves the mystery.

@pronebird I see now - sorry about the misunderstanding! I depend on Electron since I know nothing about native macOS programming. It's too bad this issue is taking so long since it causes such a bad visual defect and the fix for this specific case appears to be so easy.

**Comment by floating** [comment] 2019-01-09 22:45
Has there been any progress on this?

**Comment by KevinHughes** [comment] 2019-02-02 02:53
As mentioned in #13164, there is a workaround: when creating a `BrowserWindow`, set `titleBarStyle` to `'customButtonsOnHover'`. I've found that with `transparent: true` and `frame: false` this does everything I expected, and I'm finding that window operations (setting the location, resizing, opacity changes) appear to be faster using this option.

The downside is that it causes #10424, but I just set a CSS `border-radius` on what I'm rendering and it's fine. And of course, with `customButtonsOnHover`, moving the mouse to the upper left corner of the window shows the macOS title bar buttons.

In light of this, my suggestion to @MarshallOfSound and @pronebird is to create a new `transparent` option to `titleBarStyle` that does everything `customButtonsOnHover` does but prevents the buttons from appearing on mouse hover. Does that make sense?

**Comment by floating** [comment] 2019-02-12 18:12
Definitely would like a solution for this!

**Comment by MarshallOfSound** [comment] 2019-02-12 19:06
Didn't realize this was open, closing as duplicate of #13164 

See https://github.com/electron/electron/issues/13164#issuecomment-462099631 for final comments

**Closed by MarshallOfSound** 2019-02-12 19:06 UTC
Labels: 3-0-x, bug :beetle:, platform/macOS

**Comment by pronebird** [comment] 2019-05-20 13:11
@KevinHughes is there a tracking issue for this? I think it's a viable option.

**Comment by KevinHughes** [comment] 2019-05-23 02:08
> @KevinHughes is there a tracking issue for this? I think it's a viable option.

I haven't seen a separate issue for that - if you think it's viable please do make one! I haven't made one since I don't have the ability to test if it's really technically possible or not.

**Comment by pronebird** [comment] 2019-05-30 21:48
Since 6.0.0-beta.5 it's possible to fix this issue by using the following window configuration:

```
titleBarStyle: 'customButtonsOnHover',
minimizable: false,
maximizable: false,
closable: false,
```

Then just before qutting the app, the one has to make sure to re-enable the `closable` attribute on window, otherwise the app will never quit, at least on macOS.

```
window.setClosable(true);
```

This seems to work very well.
