### ISSUE TITLE
electron for android/ios

### ISSUE THREAD

**Issue by bomb1e** [electron/electron#5541] opened 2016-05-15 09:49 UTC
It would be cool if electron would serve as the go to platform for web devs looking to roll out on all the popular platforms.

Native mobile is key because of the convenience of having an app sit on your phone rather than in a browser tab somewhere. Could be popular because a lot of the apps built on electron are already responsive.

Thoughts on implementation: Android -> Webviews, IOS -> ??

**Comment by enlight** [comment] 2016-05-15 10:00
Issue #562 seems to indicate this would be highly unlikely.

**Comment by zcbenz** [comment] 2016-05-16 01:34
Closing as a duplicate of #562.

**Closed by zcbenz** 2016-05-16 01:34 UTC
