### ISSUE TITLE
[Bug]: When starting a child Electron app from another Electron app via exec/execFile/spawn, drag & drop is not working

### ISSUE THREAD

**Issue by berkon** [electron/electron#30306] opened 2021-07-28 11:37 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.3 and 13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

When spawning a child - Electron app from a parent - Electron app, it should be possible to drag/drop a file e.g. from the Desktop onto this app.

### Actual Behavior

I have an Electron app which starts another Electron app via `spawn`. It is not possible to drag/drop a file onto this secondary app ( I also tried `exec` and `execFile`, but the behavior is the same). Drag/drop works fine within the app and also when running this secondary app 'standalone' (I mean starting it manually ... not from the parent-app).

I also found this post https://github.com/electron/electron/issues/5243. But this refers to running an app as Administrator. I'm not doing that. When running it as Administrator (standalone) the behavior is exactly the same to what was mentioned in that post and also to what I found in my case: Drag/drop works within the app, but it is not possible to drag a file from outside the app window onto the app.

**Comment by codebytere** [comment] 2021-07-28 14:01
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by berkon** [comment] 2021-07-28 15:46
Sorry, for the confusion @codebytere. We can close this issue. Indeed it is related to the Administrator mode in Windows. I was debugging an app which was not installed under the usual `AppData` path, but instead in `C:\Program Files`. In order to be able to modify files in that folder directly, I had to start VS Code as Administrator. And then I started the electron.exe of the app from the cmd line within VS Code. Obviously it then got the same (Administrator) permissions and thus caused the mentioned issue.

**Closed** 2021-07-29 07:05 UTC
Labels: blocked/need-repro, bug :beetle:
