### ISSUE TITLE
Unable to execute system commands in packaged app

### ISSUE THREAD

**Issue by rohanpai** [electron/electron#6445] opened 2016-07-11 20:44 UTC
Electron Info 

    "electron-devtools-installer": "^1.1.2",
    "electron-packager": "^7.0.2",
    "electron-prebuilt": "^1.2.3",
    "electron-rebuild": "^1.1.4",

* Operating system: Mac 10.11.2

Problem:
The following code snipped runs fine in development but does not execute when packaged.
```
const exec = require('child_process').exec;
exec('echo $NODEPATH', (function(error, stdout, stderr){
  this.log_info("hehe")
  if (error) {
    console.error(`exec error: ${error}`);
    return;
  }
  console.log(`stdout: ${stdout}`);
  console.log(`stderr: ${stderr}`);
}).bind(this));

```

Any ideas why I can't execute system commands in Electron when the app is packaged?

**Comment by kevinsawicki** [comment] 2016-07-11 21:52
> Any ideas why I can't execute system commands in Electron when the app is packaged?

It is most likely due to the environment or how it is being launched.

Are you launching it differently when you are developing it than when it is packaged?

What output does it log to the console in both cases?

**Comment by rohanpai** [comment] 2016-07-11 22:24
Hi Kevin, thanks for the quick response!

I realized that Electron does not inherit the same settings as the user's terminal. Is there anyway to run a command as if it was run in their terminal?

**Comment by MarshallOfSound** [comment] 2016-07-11 22:27
@rohanpai Not 100% sure on this but I believe that is the difference between `spawn` and `exec`.

Use `require('child_process').spawn` https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

**Comment by kevinsawicki** [comment] 2016-07-11 23:01
> Is there anyway to run a command as if it was run in their terminal?

You may want to use https://github.com/sindresorhus/fix-path

Closing this out as a duplicate of https://github.com/electron/electron/issues/5626#issuecomment-220818378

**Closed by kevinsawicki** 2016-07-11 23:01 UTC
Labels: more-information-needed
