### ISSUE TITLE
webContents.print() random missing letters :(

### ISSUE THREAD

**Issue by popod** [electron/electron#15847] opened 2018-11-27 00:49 UTC
* Electron version: 3.0.10
* Operating System: Windows 7, Windows 10
* Last known working Electron version: 2.x.x

**Expected Behavior**
When printing an HTML page with `win.webContents.print()`, the printed documents should have the same content as the HTML page. It should match what is displayed in the print preview.

**Actual behavior**
When printing an HTLM page with `win.webContents.print()`, The printed documents randomly missing characters as described [here](https://bugs.chromium.org/p/chromium/issues/detail?id=658606) and [here](https://productforums.google.com/forum/#!topic/chrome/7tOI8sTGlbQ). 

**Screenshoot**
![exemple](https://user-images.githubusercontent.com/3807312/49074575-391a1800-f235-11e8-9273-f3f3f65cd595.jpg)

**To Reproduce / Additional Information**
Sometimes all printed documents are affected, sometimes only some of the printed documents are affected and the others not.. Cannot reproduce this issue with 100% failure. It seems that issue appears a lot with Brother printers..

The print preview is always correct and using `win.webContents.printToPDF()` always works fine !

**Comment by sofianguy** [comment] 2019-08-09 22:31
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by popod** [comment] 2019-08-11 12:46
@sofianguy Hi, this is always an issue with electron 5.0.6. But no other informations available.

**Comment by codebytere** [comment] 2020-01-25 18:12
This is unfortunately a Wontfix from our end for 5. While we are willing to and capable of overriding some of the print functionality present in Chromium in order to provide it to you in Electron, we only do so for printing settings, and not for the fundamental way that Chromium has chosen to construct documents from the DOM, which is the root cause of this issue. It will be fixed when Chromium does so, at which point we'll roll it into Electron and release it.

**Closed by codebytere** 2020-01-25 18:12 UTC
Labels: 3-0-x, 5-0-x, bug :beetle:, platform/windows

**Comment by ibalaji777** [comment] 2021-05-29 06:37
> This is unfortunately a Wontfix from our end for 5. While we are willing to and capable of overriding some of the print functionality present in Chromium in order to provide it to you in Electron, we only do so for printing settings, and not for the fundamental way that Chromium has chosen to construct documents from the DOM, which is the root cause of this issue. It will be fixed when Chromium does so, at which point we'll roll it into Electron and release it.

is this bug fixed?
