### ISSUE TITLE
dock.show() causes app to lose focus

### ISSUE THREAD

**Issue by wmnnd** [electron/electron#7329] opened 2016-09-23 21:30 UTC
If an application is currently focused and you call app.dock.show(), this window will lose the focus and then get focused again. This creates ugly flashes and occasionally leads to the window losing focus completely when it happens while opening or closing new windows.

![dock show-3](https://cloud.githubusercontent.com/assets/7488303/18801830/77ad8fa6-81e5-11e6-888f-d9cf51a9ede2.gif)

You can try it out with this little program:
```javascript
const {app, BrowserWindow} = require("electron")

app.on("ready", () => {
	let mainWindow = new BrowserWindow
	mainWindow.loadURL("https://google.com")

	setInterval(app.dock.show, 1000)
})
```
* Electron version: 3.4.1
* Operating system: macOS 10.11

**Comment by zeke** [comment] 2016-09-23 22:07
I am able to reproduce the flashing issue with your above code.

What if you change your code to only show the dock when it's not already visible?

This works for me with no flickering:

```js
app.dock.hide()

setInterval(function() {
  if (!app.dock.isVisible()) app.dock.show
}, 1000)
```

**Comment by wmnnd** [comment] 2016-09-23 22:13
That works indeed but the point of my demo was to show this general behavior.

If you have an application that hides the dock icon when no more windows are visible (e. g. to keep living in the systray) and then re-shows the dock icon when a window gets opened, you can’t really avoid the behavior unless you use something like the following which is kinda hacky:
```javascript
app.dock.show()
setInterval(win.show, 250)
```

**Comment by zcbenz** [comment] 2016-09-26 07:21
OS X does not really support showing/hiding dock icon dynamically, it is done by switching the app between foreground and background modes, and unfortunately by using the APIs provided by Apple this glitch is not avoidable. So your only solution is to avoid doing this, or just live with the side effect.

I'm closing this as won't fix since there does not seem to have a way to fix it.

**Closed by zcbenz** 2016-09-26 07:21 UTC
