### ISSUE TITLE
Silent print not working in mac/osX 

### ISSUE THREAD

**Issue by neerajmanoharan** [electron/electron#16362] opened 2019-01-11 06:47 UTC

**Comment by sators** [comment] 2019-01-15 19:36
Same here...

**Comment by sofianguy** [comment] 2019-01-15 19:53
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by NerdGuruDevelopers** [comment] 2019-01-22 04:49
I was able to get it working by reverting to 3.1.1. :/

**Comment by mozainuddin** [comment] 2019-01-22 22:22
You are right, I rollback to 3.1.1, and It worked just fine! Thank you @NerdGuruDevelopers

**Comment by mrts** [comment] 2019-01-24 10:47
Same problem in Ubuntu: #14072

**Comment by willswire** [comment] 2019-02-25 19:19
Also experiencing this issue on Debian Jessie with v3.1.4.  Reverting to v3.1.1 **did not fix** the issue.

**Comment by mojason-81** [comment] 2019-04-12 16:59
Tried downgrading from 4.1.x to 3.1.1 for this issue and it did not fix on Win 10.

**Comment by orionlu0916** [comment] 2019-04-17 05:51
> Tried downgrading from 4.1.x to 3.1.1 for this issue and it did not fix on Win 10.

same issue. with silent mode, I always get failed result from the callback. (on Win 10)

**Comment by codebytere** [comment] 2019-06-20 02:35
Closing as duplicate of https://github.com/electron/electron/issues/18123.

**Closed by codebytere** 2019-06-20 02:35 UTC
Labels: 2-0-x, 4-2-x
