### ISSUE TITLE
Failed to query stereo recording when i use PeerJS

### ISSUE THREAD

**Issue by howion** [electron/electron#13803] opened 2018-07-25 15:01 UTC
* **Electron Version:** v1.8.4
* **Operating System (Platform and Version):** Windows 10 x64
* **Last known working Electron version:** -

When i include [**peer.min.js**](https://cdnjs.cloudflare.com/ajax/libs/peerjs/0.3.9/peer.min.js) **( locally or from url )** to my index.html
**[7280:0725/175218.153:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.** ) appears in console

**P.S** even i dont create new Peer() object error still appears
**P.S** Btw everything works as excepted... Yet

**Screenshots**
![image](https://user-images.githubusercontent.com/39840945/43208811-e65b3e86-9033-11e8-8386-ab15d2856722.png)
![image](https://user-images.githubusercontent.com/39840945/43208527-51552b08-9033-11e8-9ad9-c844c9b77f7f.png)

**Comment by sofianguy** [comment] 2019-01-15 20:48
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-29 00:08
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by TheDigiBusiness** [comment] 2019-08-28 10:33
This is issue still exists in 4.0.x. Though using later versions than v. 4.0.x, other issues just arise that is worse like: 
[9668:0828/122452.578:ERROR:audio_rtp_receiver.cc(87)] AudioRtpReceiver::OnSetVolume: No audio channel exists

**Comment by Teranode** [comment] 2019-10-15 00:49
@sofianguy I am using electron 6.0.12 (Latest) & 7.0.0-beta.6. I can confirm on both versions that this error does pop up, when trying to add audio to desktopcapturer.

```
[17712:1014/203545.570:ERROR:audio_rtp_receiver.cc(88)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
[17712:1014/203545.571:ERROR:audio_rtp_receiver.cc(88)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
[17712:1014/203545.589:ERROR:audio_rtp_receiver.cc(88)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
[17712:1014/203545.590:ERROR:audio_rtp_receiver.cc(88)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
[17712:1014/203546.387:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[17712:1014/203546.388:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[17712:1014/203546.390:ERROR:audio_rtp_receiver.cc(88)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
```

It starts to work fine if `audio` is set to false when using `getUserMedia`.

**Comment by piotrw86** [comment] 2019-12-16 08:18
> in `electron@^5` i get this:
> 
> ```
>  [28892:1014/205919.615:ERROR:rtp_receiver.cc(121)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
> [28892:1014/205919.616:ERROR:rtp_receiver.cc(121)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
> [28892:1014/205919.620:ERROR:rtp_receiver.cc(121)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
> [28892:1014/205919.621:ERROR:rtp_receiver.cc(121)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
> [28892:1014/205919.937:ERROR:rtp_receiver.cc(121)] AudioRtpReceiver::OnSetVolume: No audio channel exists.
> ```
> 
> however audio works and is transmitted through peers while above version 5 audio doesnt work and webRTC just stops working.

Can you write exact version number you have managed to work? I have tried with 4.2.12, but I got "ERROR:adm_helpers.cc(73)] Failed to query stereo recording."

**Comment by Teranode** [comment] 2019-12-16 08:49
I've stopped using electron since there's no fixing it and moved onto something else, but i believe i was using the last version of version 5

**Comment by TheDigiBusiness** [comment] 2019-12-16 09:33
We're stuck at 4.2.12, because it's the highest electron version that allows for audio usage when working with webrtc.

**Comment by piotrw86** [comment] 2019-12-16 10:33
> I've stopped using electron since there's no fixing it and moved onto something else, but i believe i was using the last version of version 5

Thanks for response. I have tested the latest 5.x.x and 4.2.12.
@5.x.x. I got the same error as reported in this issue
@4.2.12 i got: ERROR:adm_helpers.cc(73)] Failed to query stereo recording.

What is curious those bugs occurs only when I run packaged electron app (*.deb). While running from 'ng serve' it works even in electron 6.0.3...

**Comment by MonkeyInWind** [comment] 2020-01-12 12:13
I got the same error, when I play a video in electron.
```
[74614:0112/200433.474345:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/200433.474384:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/200439.594472:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/200439.594510:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/200445.599205:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/200445.599234:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/200451.647903:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/200451.647934:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/200457.849747:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/200457.849784:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/200504.317172:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/200504.317199:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/200511.353782:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/200511.353811:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/200517.630065:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/200517.630106:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/200611.884793:ERROR:stun_port.cc(96)] Binding request timed out from 172.20.10.x:57217 (en0)
[74614:0112/200612.330806:ERROR:stun_port.cc(96)] Binding request timed out from 172.20.10.x:57217 (en0)
[74614:0112/200612.627142:ERROR:stun_port.cc(96)] Binding request timed out from 172.20.10.x:57217 (en0)
[74614:0112/200647.372719:ERROR:stun_port.cc(96)] Binding request timed out from 172.20.10.x:57217 (en0)
[74614:0112/200658.809622:ERROR:stun_port.cc(96)] Binding request timed out from 172.20.10.x:57217 (en0)
[74614:0112/200706.127945:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/200706.127972:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/200736.509618:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/200736.509640:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/200832.824255:ERROR:stun_port.cc(96)] Binding request timed out from 172.20.10.x:57217 (en0)
[74614:0112/200938.590690:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/200938.590739:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/200941.185093:ERROR:peer_connection.cc(3724)] AddIceCandidate: ICE candidates can't be added without any remote session description.
[74614:0112/200941.545377:ERROR:peer_connection.cc(3724)] AddIceCandidate: ICE candidates can't be added without any remote session description.
[74614:0112/201211.035809:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
[74614:0112/201211.035828:ERROR:data_channel.cc(59)] Accepting maxRetransmitTime = -1 for backwards compatibility
[74614:0112/201217.211234:ERROR:data_channel.cc(54)] Accepting maxRetransmits = -1 for backwards compatibility
```

**Comment by electron-triage** [comment] 2021-03-09 01:01
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 01:01 UTC
Labels: 4-2-x, 6-0-x, 6-1-x, 7-0-x, 7-1-x, bug :beetle:, platform/windows, version/1.8.x
