### ISSUE TITLE
shell.openExternal passes console on Windows

### ISSUE THREAD

**Issue by felixrieseberg** [electron/electron#12416] opened 2018-03-22 23:31 UTC
`shell.openExternal` opens target processes as true child processes and passes the console. In practice, that means that environment variables set for your app are passed to the child processes. 

Here's an example:

• Your app sets `process.env.NODE_ENV="development"`
• Now, using `shell.openExternal`, you open a link (`https://google.com`)
• If the system's default browser wasn't already running, it will now be launched with `NODE_ENV="development"`

* Electron version: 1.8.5, 2.0.0-beta
* Operating system: Windows, all versions

![pasted image at 2018_03_22 04_30 pm](https://user-images.githubusercontent.com/1426799/37803840-5e781964-2dee-11e8-8388-20fc7e97320b.png)

### Expected behavior

`shell.openExternal` should not pass the current console and launch processes detached.

### Actual behavior

`shell.openExternal` passes the current console and environment.

### How to reproduce

```sh
  $ git clone https://github.com/felixrieseberg/electron-quick-start -b passed-env
  $ npm install
  $ npm start || electron .
```

Then, do the following:
1) Close your browser
2) Open [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer)
3) In the app, click the "Launch Browser and Open Google" button
4) In Process Explorer, select your browser, right-click, and open the "Properties". Switch the panel to `Environment` to see your whole environment passed to your browser.

**Comment by nornagon** [comment] 2018-03-27 16:50
I have a fix for this that involves using COM to ask explorer.exe to open the URL on our behalf, but I'm not sure it's the right thing to do for Electron. Chrome and Firefox both use the exact same call to open external files/URLs that Electron does, so they exhibit this behaviour also. It's possible that some apps or use-cases depend on the current behaviour (though I'm not sure they should...)

The COM approach might bring new and exciting different link-opening bugs, so I'm hesitant to change it without some further testing and a lot more conviction that it's the right way to go.

Not opening a PR because I'm not yet convinced that it should be merged, but here's the code:

```diff
commit 240d0b3e467be5b00e5d37e81100bef194762d7b
Author: Jeremy Apthorp <nornagon@nornagon.net>
Date:   Tue Mar 27 09:38:36 2018 -0700

    Open external URLs via COM to avoid propagating environment
    
    Fixes #12416.
    
    Approach is from the Windows 7 SDK sample [ExecInExplorer][1]. See also
    Raymond Chen's [post on the topic][2].
    
    I'm not sure if this changes the error cases, i.e. what happens when
    'open' fails.
    
    [1]: https://github.com/Microsoft/Windows-classic-samples/blob/master/Samples/Win7Samples/winui/shell/appplatform/ExecInExplorer/ExecInExplorer.cpp
    [2]: https://blogs.msdn.microsoft.com/oldnewthing/20131118-00/?p=2643

diff --git a/atom/common/platform_util_win.cc b/atom/common/platform_util_win.cc
index ef5920202..8453a4767 100644
--- a/atom/common/platform_util_win.cc
+++ b/atom/common/platform_util_win.cc
@@ -13,14 +13,16 @@
 #include <objbase.h>
 #include <shellapi.h>
 #include <shlobj.h>
+#include <shlwapi.h>
 
-#include "base/bind.h"
 #include "base/bind_helpers.h"
+#include "base/bind.h"
 #include "base/files/file_path.h"
 #include "base/files/file_util.h"
 #include "base/logging.h"
 #include "base/strings/string_util.h"
 #include "base/strings/utf_string_conversions.h"
+#include "base/task_scheduler/post_task.h"
 #include "base/win/registry.h"
 #include "base/win/scoped_co_mem.h"
 #include "base/win/scoped_com_initializer.h"
@@ -300,21 +302,99 @@ bool OpenItem(const base::FilePath& full_path) {
     return ui::win::OpenFileViaShell(full_path);
 }
 
+HRESULT GetShellViewForDesktop(REFIID riid, void **ppv) {
+  *ppv = nullptr;
+
+  base::win::ScopedComPtr<IShellWindows> shell_windows;
+  HRESULT hr;
+  hr = ::CoCreateInstance(CLSID_ShellWindows, nullptr, CLSCTX_ALL,
+                          IID_PPV_ARGS(&shell_windows));
+  if (FAILED(hr))
+    return hr;
+  CComVariant empty_variant = {};
+  long lhwnd;
+  base::win::ScopedComPtr<IDispatch> dispatch;
+  if (S_OK != shell_windows->FindWindowSW(&empty_variant, &empty_variant,
+                                          SWC_DESKTOP, &lhwnd,
+                                          SWFO_NEEDDISPATCH, &dispatch))
+    return E_FAIL;
+  base::win::ScopedComPtr<IServiceProvider> service_provider;
+  hr = dispatch->QueryInterface(IID_PPV_ARGS(&service_provider));
+  if (FAILED(hr))
+    return hr;
+  base::win::ScopedComPtr<IShellBrowser> shell_browser;
+  hr = service_provider->QueryService(SID_STopLevelBrowser,
+                                      IID_PPV_ARGS(&shell_browser));
+  if (FAILED(hr))
+    return hr;
+  base::win::ScopedComPtr<IShellView> shell_view;
+  hr = shell_browser->QueryActiveShellView(&shell_view);
+  if (FAILED(hr))
+    return hr;
+  return shell_view->QueryInterface(riid, ppv);
+}
+
+HRESULT GetShellDispatchFromView(IShellView *psv, REFIID riid, void **ppv) {
+  *ppv = NULL;
+  base::win::ScopedComPtr<IDispatch> spdispBackground;
+  HRESULT hr;
+  hr = psv->GetItemObject(SVGIO_BACKGROUND, IID_PPV_ARGS(&spdispBackground));
+  if (FAILED(hr))
+    return hr;
+  base::win::ScopedComPtr<IShellFolderViewDual> spFolderView;
+  hr = spdispBackground->QueryInterface(IID_PPV_ARGS(&spFolderView));
+  if (FAILED(hr))
+    return hr;
+  base::win::ScopedComPtr<IDispatch> spdispShell;
+  hr = spFolderView->get_Application(&spdispShell);
+  if (FAILED(hr))
+    return hr;
+  return spdispShell->QueryInterface(riid, ppv);
+}
+
+HRESULT ShellExecInExplorerProcess(LPCWSTR lpFile, LPCWSTR lpParameters,
+                                   LPCWSTR lpDirectory, LPCWSTR lpOperation,
+                                   INT nShowCmd) {
+  base::win::ScopedComPtr<IShellView> psv;
+  HRESULT hr;
+
+  hr = GetShellViewForDesktop(IID_PPV_ARGS(&psv));
+  if (FAILED(hr))
+    return hr;
+  base::win::ScopedComPtr<IShellDispatch2> psd;
+  hr = GetShellDispatchFromView(psv.Get(), IID_PPV_ARGS(&psd));
+  if (FAILED(hr))
+    return hr;
+  return psd->ShellExecuteW(
+    CComBSTR(lpFile),
+    CComVariant(lpParameters ? lpParameters : L""),
+    CComVariant(lpDirectory ? lpDirectory : L""),
+    CComVariant(lpOperation ? lpOperation : L""),
+    CComVariant(nShowCmd)
+  );
+}
+
 bool OpenExternal(const base::string16& url, bool activate) {
+  base::win::ScopedCOMInitializer com_initializer;
+  if (!com_initializer.succeeded())
+    return false;
+
   // Quote the input scheme to be sure that the command does not have
   // parameters unexpected by the external program. This url should already
   // have been escaped.
   base::string16 escaped_url = L"\"" + url + L"\"";
 
-  if (reinterpret_cast<ULONG_PTR>(ShellExecuteW(NULL, L"open",
-                                                escaped_url.c_str(), NULL, NULL,
-                                                SW_SHOWNORMAL)) <= 32) {
-    // We fail to execute the call. We could display a message to the user.
-    // TODO(nsylvain): we should also add a dialog to warn on errors. See
-    // bug 1136923.
+  // According to Mozilla in uriloader/exthandler/win/nsOSHelperAppService.cpp:
+  // "Some versions of windows (Win2k before SP3, Win XP before SP1) crash in
+  // ShellExecute on long URLs (bug 161357 on bugzilla.mozilla.org). IE 5 and 6
+  // support URLS of 2083 chars in length, 2K is safe."
+  //
+  // It may be possible to increase this. https://crbug.com/727909
+  const size_t kMaxUrlLength = 2048;
+  if (escaped_url.length() > kMaxUrlLength)
     return false;
-  }
-  return true;
+  return SUCCEEDED(ShellExecInExplorerProcess(
+    escaped_url.c_str(), NULL, NULL, L"open", SW_SHOWNORMAL));
 }
 
 void OpenExternal(const base::string16& url, bool activate,
```

**Comment by ckerr** [comment] 2018-04-17 15:50
@nornagon since this issue hasn't moved in a few weeks, could you ask in #core for feedback on your suggestion above so that we can unstick this issue?

Also, DYK if this is a new regression in 2.0.0 or if the issue exists in 1.8.x as well?

**Comment by nornagon** [comment] 2018-04-17 16:05
This behavior is unchanged since it was introduced, so it is the same in all current versions of electron.

**Comment by ckerr** [comment] 2018-04-17 16:07
@nornagon d'oh, it even says 1.8.x in @felixrieseberg's original description. :man_facepalming:

**Comment by sofianguy** [comment] 2019-08-09 03:25
@felixrieseberg is this bug still happening in version 4.2.x or later?

**Comment by sofianguy** [comment] 2019-08-19 19:07
I'm going to close this for now but happy to reopen if this is still happening on v4.2.x or later

**Closed by sofianguy** 2019-08-19 19:07 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows, status/confirmed, version/1.8.x

**Comment by phosphore** [comment] 2020-11-06 16:32
This behavior is still present in v10.1.5 and can be reproduced slightly updating @felixrieseberg's PoC from the original issue. The real solution is to be proactive in preventing the variables leaking to the child process, using https://github.com/electron/electron/issues/12416#issuecomment-376596073 solution featuring `ShellExecInExplorerProcess`.

![env_var_10-15-2](https://user-images.githubusercontent.com/1053079/98390147-4660f380-2055-11eb-8b7e-c37ee3b6fa99.png)
