### ISSUE TITLE
[Bug]: The problem that the screenshot of a web page cannot be achieved when the window is minimized in electron 25.2.0

### ISSUE THREAD

**Issue by 82318179** [electron/electron#39104] opened 2023-07-14 08:37 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Windows

### Operating System Version

win11

### What arch are you using?

x64

### Last Known Working Electron version

22.3.0

### Expected Behavior

How to make electron 25 version can still take screenshots even if the window is minimized or completely obscured by other applications? how do you need to set it? MainWindow.webContents.capturePage ({}, {stayAwake: true}); this setting is not valid, while the webContents.incrementCapturerCount (undefined, undefined, true) setting has been deprecated.
the code :

The results of running with electron version 25.2.0 are as follows:
package.json
{ "name": "ttt", "version": "1.0.0", "main": "main.js", "license": "MIT", "scripts": { "start": "electron ." }, "dependencies": { "electron": "^25.2.0" } }
main.js
`const { app, BrowserWindow } = require('electron');
const path = require('path');
function createWindow() {
const mainWindow = new BrowserWindow({
width: 800,
height: 600,
webPreferences: {
preload: path.join(__dirname, 'preload.js'),
},
});
mainWindow.loadFile('index.html');
setTimeout(async () => {
mainWindow.minimize();
setTimeout(async () => {
let abc = await mainWindow.webContents.capturePage();
console.log(abc.getSize().height);
}, 4000);
}, 4000);
}

app.whenReady().then(() => {
createWindow();
app.on('activate', function () {
if (BrowserWindow.getAllWindows().length === 0) createWindow();
});
});
app.on('window-all-closed', function () {
if (process.platform !== 'darwin') app.quit();
});`

The height of the output screenshot is 0. The screenshot failed.

but use electron version ^22.3.0 ，A line of code was added like mainWindow.webContents.incrementCapturerCount(undefined, undefined, true);

The effect of this screenshot is good, and the height of the screenshot can be obtained. the electron version 22.3.0 code as follows:
`{ "name": "ttt", "version": "1.0.0", "main": "main.js", "license": "MIT", "scripts": { "start": "electron ." }, "dependencies": { "electron": "^22.3.0" } }`
`const { app, BrowserWindow } = require('electron'); const path = require('path'); function createWindow() { const mainWindow = new BrowserWindow({ width: 800, height: 600, webPreferences: { preload: path.join(__dirname, 'preload.js'), }, }); mainWindow.loadFile('index.html'); setTimeout(async () => { //Add the following code mainWindow.webContents.incrementCapturerCount(undefined, undefined, true); mainWindow.minimize(); setTimeout(async () => { let abc = await mainWindow.webContents.capturePage(); console.log(abc.getSize().height); }, 4000); }, 4000); } app.whenReady().then(() => { createWindow(); app.on('activate', function () { if (BrowserWindow.getAllWindows().length === 0) createWindow(); }); }); app.on('window-all-closed', function () { if (process.platform !== 'darwin') app.quit(); });`

The screenshot height of the output is correct。

### Actual Behavior

in electron 25.2.0 ,The height of the output screenshot is 0. The screenshot failed.

![238b3ee2dead621dfeb59aeeec57244c_252833247-9f59a855-db74-4600-b3db-e3fe29c25d71](https://github.com/electron/electron/assets/25976728/1c1762b2-33a5-432c-943a-725aeda34153)

but use electron version ^22.3.0 ，A line of code was added like mainWindow.webContents.incrementCapturerCount(undefined, undefined, true);
The screenshot height of the output is correct。
![c254f8aac5367aeddc9c82bd91e3ca56_252832904-885eb9a6-5f2e-4ccf-b649-ee131f1961a2](https://github.com/electron/electron/assets/25976728/ef96be45-71f7-446e-87b3-7e1cceda5b65)

### Testcase Gist URL

https://gist.github.com/b131b0bfbe2bdd85660e2d5d6ea6217c

**Comment by VerteDinde** [comment] 2023-07-19 16:55
Thanks for reporting this issue! I think this is a duplicate of #37611 - I'm going to close this as a duplicate, but thank you for the gist and let us know if there's more we can do! You can follow fix progress in the original ticket 🙇‍♀

**Closed by VerteDinde** 2023-07-19 16:55 UTC
Labels: bug :beetle:, has-repro-gist, windows 7, 25-x-y, 26-x-y
