### ISSUE TITLE
setSize() multiple times stop working after two calls

### ISSUE THREAD

**Issue by justduy** [electron/electron#17217] opened 2019-03-04 18:53 UTC
* **Electron Version:**
  * 4.0.1
* **Operating System:**
  * Windwos 10

### Expected Behavior
Setting BrowserWindow size via `.setSize()` sets size, in disregard of how many times called, when call through a `globalShortcut.register()`.

### Actual Behavior
Window is set successfully twice, but upon the last time it will not set window size.

### To Reproduce/ Code
```
  globalShortcut.register("Shift+L", () => {
    isMinimized ? win.setSize(1000, 700) : win.setSize(700, 300);
    isMinimized = !isMinimized;
  });
```

EDIT: Not sure if helpful: 
```
     win = new BrowserWindow({ width: 1000, height: 700, resizable: false });
     win.loadURL("someUrl"); 
     var isMinimized = false;

```

**Comment by MarshallOfSound** [comment] 2019-03-04 22:17
Cannot reproduce on macOS, someone on Windows will have to try verify this

**Comment by codebytere** [comment] 2019-03-19 19:42
cc @brenca could you potentially try to repro this?

**Comment by electron-triage** [comment] 2020-02-19 20:52
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:33
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:33 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/windows

**Comment by ahmadmarhaba** [comment] 2020-03-16 15:54
I'm sorry, Ik this discussion is closed but I had this problem too and solved it by adding resizable to true then launch the set size then set resizable to false again, IDK why but the set-size function doesn't work more than 2 times unless resizable is set to true.

- mainWindow.resizable = true;
- mainWindow.setSize(x, y);
- mainWindow.resizable = false;

Hope anyone who reads this understands what I mean :)

**Comment by rodrigosantosti01** [comment] 2020-11-10 22:44
I had this problem too and solved it by adding resizable as a function:
- mainWindow.setResizable(true);
- mainWindow.setSize(width,height)
- mainWindow.setResizable(false);

**Comment by Sandhya1007** [comment] 2021-11-26 11:27
Is there a way that you can toggle between three different window sizes in electron? I am trying with setSize but its not working. I am also trying to manipulate the functionality of minimize button but that is also not working.

**Comment by sergioortegac** [comment] 2022-04-14 19:54
> I'm sorry, Ik this discussion is closed but I had this problem too and solved it by adding resizable to true then launch the set size then set resizable to false again, IDK why but the set-size function doesn't work more than 2 times unless resizable is set to true.
> 
> * mainWindow.resizable = true;
> * mainWindow.setSize(x, y);
> * mainWindow.resizable = false;
> 
> Hope anyone who reads this understands what I mean :)

This works perfectly! Thank a lot

**Comment by shuhad** [comment] 2022-06-16 13:56
> * mainWindow.resizable = false;

Still working

**Comment by shuhad** [comment] 2022-06-16 13:57
> I'm sorry, Ik this discussion is closed but I had this problem too and solved it by adding resizable to true then launch the set size then set resizable to false again, IDK why but the set-size function doesn't work more than 2 times unless resizable is set to true.
> 
> * mainWindow.resizable = true;
> * mainWindow.setSize(x, y);
> * mainWindow.resizable = false;
> 
> Hope anyone who reads this understands what I mean :)

Still working !
