### ISSUE TITLE
Add Chromium 59 Support

### ISSUE THREAD

**Issue by setpixel** [electron/electron#9679] opened 2017-06-05 23:16 UTC
Woot. Chromium 59 was released stable with some gigantic bugs squashed very important to my project! 💃 

What can I do to help?

**Comment by kevinsawicki** [comment] 2017-06-05 23:25
> What can I do to help?

There is https://electron.atom.io/docs/development/upgrading-chrome/ which gives an overview of the broad steps to upgrade to a new chrome version.

This process hasn't been started yet for 59 but should begin this week.

Once things are compiling, it is really helpful to have help testing the initial builds since the Electron tests do not cover every Chrome feature or combination of options, so sometimes there are regressions with components like printing, rendering in `<webview>` tags, certificate validation, etc.

**Comment by tonyganch** [comment] 2017-06-08 08:04
We've started work on that issue today.
In case anyone else started the same effort, talk now or forever hold your peace 🐙

**Comment by setpixel** [comment] 2017-06-09 02:53
@tonyganch Will it be in a branch on this repository?

**Comment by tonyganch** [comment] 2017-06-12 08:55
@setpixel, due to some legal requirements we're starting work internally, and will push branches/PRs once we get it all settled.

**Comment by achrist** [comment] 2017-06-13 16:11
@tonyganch Just out of curiosity how long does updating to a new version of Chromium take?

**Comment by setpixel** [comment] 2017-06-13 16:23
@tonyganch interesting! what are the legal requirements out of curiosity?

**Comment by tonyganch** [comment] 2017-06-14 10:01
@achrist, from days to weeks, depending on how much Chromium code has changed between versions and how much we need to update Electron's code to reflect those changes. Sometimes things get renamed, sometimes things get removed.

@setpixel, we need to run open-source contributions through some checks to make sure PRs are not by accident leaking any confidential/proprietary code.

**Comment by tonyganch** [comment] 2017-06-15 07:12
PR with changes to libcc: electron/libchromiumcontent#311

**Comment by djalmaaraujo** [comment] 2017-06-17 20:40
Take a look a this BUG for WebRTC::GetStats method. https://github.com/webrtc/adapter/issues/476

Would be amazing to have an official electron version with m59

**Comment by stanleyxu2005** [comment] 2017-08-13 17:52
Yeah. This is an interesting point. How electron community sync with chrome major updates. I have currently such an issue with jquery's show() and hide(). Here is my question detail https://github.com/uikit/uikit/issues/2844

**Comment by setpixel** [comment] 2017-08-27 22:36
Hi friends,

I know there are still some issues with CI that prevent a release. I was just curious what the loose plans are for a 1.8 release and what is left to be done.

Really looking forward to Chromium 59! 👍

**Comment by jkleinsc** [comment] 2017-10-11 18:30
Closing this as 1.8.1 release is now available with the upgrade to Chromium 59: 
https://github.com/electron/electron/releases/tag/v1.8.1

**Closed by jkleinsc** 2017-10-11 18:30 UTC
Labels: component/build, enhancement
