### ISSUE TITLE
electron keeps respawning itself 

### ISSUE THREAD

**Issue by ca333** [electron/electron#8375] opened 2017-01-10 14:00 UTC
https://discuss.atom.io/t/electron-app-respawns-itself/37897

integrating pm2 with electron leads to a strange behaviour in production mode(after packaging the app for distribution). The electron app keeps respawning itself in a loop and pm2 is not being launched. 

The same code is confirmed to work in a simple node app as well as in electron development mode. 
Seems like electron has an issue with the pm2 package in production only. 

Hope you have an idea or hint on what could be the problem.

**Comment by MarshallOfSound** [comment] 2017-01-10 14:08
> Seems like electron has an issue with the pm2 package in production only.

Past experience points me towards this being an issue caused by the difference in architecture rather than anything else.  If I interpret that question correctly you are attempting to spawn your own app in PM2?

A couple of issues I can potentially see occurring

* You're getting hit by macOS's gatekeepers sandbox and spawning the "path/to/executable" isn't working (not sure what platform you are on)
* Single instance is being enforced for some reason
* You've lost dependencies during your package step (perhaps an incorrect prune / deletion)

To be honest this sounds very much like an issue with either PM2 or in your exact implementation.  If you could provide a minimal example to reproduce the issue it would help determine if this is an Electron issue or not.

**Comment by ca333** [comment] 2017-01-11 19:06
> you are attempting to spawn your own app in PM2?

@MarshallOfSound: no i am attempting to spawn a 3rd party binary from within my electron application via pm2. I just uploaded my [sample-app](https://github.com/ca333/pm2_electron_app). It is quite simple and its job is only to  launch a binary via pm2 from within the electron app. This works fine unless it is packed with electron-packager for public distribution.

(to reproduce the issue just integrate pm2 into any electron app and launch a external binary from within it. once you pack it for distribution the app will respawn itself due to an unknow issue.)

**Comment by MarshallOfSound** [comment] 2017-01-11 20:17
@ca333 Is ASAR enabled when you package your app?

**Comment by ca333** [comment] 2017-01-11 22:40
@MarshallOfSound No it's not enabled. I am packaging it with `electron-packager . --platform=darwin --arch=x64 --icon=assets/icons/icon.icns --out=build/`

**Comment by ca333** [comment] 2017-01-23 11:58
@MarshallOfSound did you find time to reprocude the bug?

**Comment by atilacamurca** [comment] 2017-02-22 15:18
I have the same issue when I was trying to run 2 node services through pm2. I even try to use other tool ([forever-monitor](https://github.com/foreverjs/forever-monitor)) but the result is the same, the electron app keeps respawning itself until the system crashes.

I hope to see a workaround to this.

**Comment by atilacamurca** [comment] 2017-02-22 21:34
I finally found a solution! :tada: 

The pull request #7479 introduces two env variables: `ELECTRON_NO_ASAR` and `ELECTRON_RUN_AS_NODE`.

For fork process use `ELECTRON_NO_ASAR` set to `true`.

Example: <https://github.com/electron/electron/pull/7479/files#diff-5686e6130dcc1145c5340c794b919d3cR759>

For spawn process use both `ELECTRON_NO_ASAR` and `ELECTRON_RUN_AS_NODE` set to `true`.

Example: <https://github.com/electron/electron/pull/7479/files#diff-5686e6130dcc1145c5340c794b919d3cR772>

Both pm2 and forever-monitor accepts `env` as object where you can pass custom env variables.

Hey @ca333, can you try this and tell if it works for you?

ps. tested with electron v1.4.15

**Comment by kevinsawicki** [comment] 2017-03-09 01:14
> I finally found a solution!

Thanks for posting this, closing this out.

**Closed by kevinsawicki** 2017-03-09 01:14 UTC
Labels: more-information-needed

**Comment by xeoshow** [comment] 2024-02-13 14:18
Hello, 

For the newer version "electron": "22.3.27", below code still failed when start from the after packaging app , while the same code is confirmed to work in a simple node app as well as in electron development mode. I am running this on Windows 10. Any one could please help? Thanks a lot.
`
function startApp(configFile) {
  return new Promise((resolve, reject) => {
    pm2.connect((err) => {
      if (err) {
        console.error('Error connecting to PM2:', err);
        return reject(err);
      }

      pm2.start(configFile, (error, apps) => {
        pm2.disconnect(); // Disconnects from PM2
        if (error) {
          console.error('Error starting app:', error);
          return reject(error);
        }

        return resolve(apps);
      });
      return null;
    });
  });
}
` 

My package.json file is something as below:
`
{
  "name": "test-software",
  "version": "3.0.0",
  "author": "test",
  "description": "test software project",
  "main": "main.js",
  "dependencies": {
    "electron-squirrel-startup": "^1.0.0",
    "pm2": "^5.3.1",
  },
  "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "lint": "eslint .",
    "lint-fix": "eslint --fix --cache ."
  },
  "engines": {
    "node": ">=16.17.1"
  },
  "devDependencies": {
    "@electron-forge/cli": "^7.2.0",
    "@electron-forge/maker-deb": "^7.2.0",
    "@electron-forge/maker-rpm": "^7.2.0",
    "@electron-forge/maker-squirrel": "^7.2.0",
    "@electron-forge/maker-zip": "^7.2.0",
    "@electron-forge/plugin-auto-unpack-natives": "^7.2.0",
    "electron": "22.3.27",


    "eslint": "^8.7.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-import": "^2.25.4",
    "nyc": "15.1.0",
    "prettier": "2.2.1"
  }
}
`
