### ISSUE TITLE
use window.close in Browserview-webcontents(web page) will close the app!!!!!!!

### ISSUE THREAD

**Issue by spcBackToLife** [electron/electron#19194] opened 2019-07-10 11:41 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Electron Version: 5.0.6
Platform: macOs 10.14

Expected Behavior: 
    when use `window.close()` in web page of Browserview, which page with `onbeforunload` hook. and it will fire `webContents.on('will-prevent-unload', xxx)`, so that i can open a tips dialog of leaving page.

Actual Behavior:
   The Electron app is closed.

I have saw the source code. and it had rewrite the function `window.close` just like this:

```

export const windowSetup = (
  guestInstanceId: number, openerId: number, isHiddenPage: boolean, usesNativeWindowOpen: boolean
) => {
  if (guestInstanceId == null) {
    // Override default window.close.
    window.close = function () {
      ipcRendererInternal.sendSync('ELECTRON_BROWSER_WINDOW_CLOSE')
    }
  }
......
}
```

and in rpc-server.js ,just like this:

```
ipcMainInternal.on('ELECTRON_BROWSER_WINDOW_CLOSE', function (event) {
  const window = event.sender.getOwnerBrowserWindow()
  if (window) {
    window.close()
  }
  event.returnValue = null
})

```

so if like this, how i can close the web page in Browserview, and can get the thing i want?

**Comment by pushkin-** [comment] 2019-07-10 20:01
>how i can close the web page in Browserview, and can get the thing i want?

I don't understand. From what you said earlier, it sounds like you *don't* want the window to close. What is the "thing you want?"

I think closing the window is the right thing to do here - that's how browsers behave. You can alter the behavior by latching onto the `close` event of BrowserWindow and doing whatever you want there in response to the close.

**Comment by PalmerAL** [comment] 2019-07-11 15:47
I think the issue is that if you have a BrowserWindow with a BrowserView attached to it, calling `window.close` from inside the view will close the parent window, which isn't what I would expect to happen. Since the `close` event on BrowserWindow doesn't provide a way to tell whether the window itself or just the view is closing, there's no way to prevent this behavior without also making it impossible to close the window.

I think the expected behavior would be that calling close() from inside a BrowserView doesn't do anything to the window, and the view would emit a `close` event to let you destroy the view (like [how webviews work](https://electronjs.org/docs/api/webview-tag#event-close)).

**Comment by spcBackToLife** [comment] 2019-07-12 09:14
I didn't describe it clearly, sorry, @pushkin- !   
@PalmerAL The thing you said is what I mean.  calling close() from inside a BrowserView doesn't do anything to the window, and the view would emit a close event to let you destroy the view (like how webviews work).

**Comment by sentialx** [comment] 2019-07-22 23:47
Oh, that's a critical issue. I think `window.close` should emit a `close` event in `webContents`, to let users  close a tab for example.

**Comment by Xylobol** [comment] 2019-07-23 23:34
> Oh, that's a critical issue. I think `window.close` should emit a `close` event in `webContents`, to let users close a tab for example.

I think this is the correct behavior. One renderer hitting a `close` event should not take out another.

**Comment by codebytere** [comment] 2019-08-01 22:29
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by PalmerAL** [comment] 2019-08-02 01:51
@codebytere Here's a testcase:

```
git clone https://github.com/palmeral/electron-quick-start.git
cd electron-quick-start
git checkout issue-19194
```

When `window.close()` is called from within the BrowserView, the entire parent window is closed, which shouldn't happen.

**Comment by miniak** [comment] 2019-08-18 10:19
the problem is related to this piece of code:
https://github.com/electron/electron/blob/master/lib/renderer/window-setup.ts#L180-L185

**Comment by miniak** [comment] 2019-08-18 10:27
@codebytere I would suggest this fix: https://github.com/electron/electron/pull/19813

**Comment by MatthieuLeMee** [comment] 2019-10-21 08:30
Experimenting this problem too, trying to have simple "tabs" in an Electron app.

''window.close'' in a BrowserView should fire ''browserView.webContents.close'' event before hitting the ''browserWindow.webContents.close'' event, or at least send an additional info to the close event to be able to differentiate closing events coming from window (X button on OS window frame) or coming from inside the BrowserView and be able to prevent it if needed.

Maybe add a new ''browserView.webContents.will-close'' otherwise.

**Comment by electron-triage** [comment] 2020-02-15 01:21
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by PalmerAL** [comment] 2020-02-15 02:27
I believe this issue still exists in the latest version.

**Comment by spcBackToLife** [comment] 2020-02-15 04:48
> Thank you for taking the time to report this issue and helping to make Electron better.
> 
> The version of Electron you reported this on has been superseded by newer releases.
> 
> If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.
> 
> I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.
> 
> Thanks in advance! Your help is appreciated.

ok~

**Comment by pushkin-** [comment] 2020-02-15 16:28
I confirmed that this still happens in Electron 8.

**Comment by electron-triage** [comment] 2021-03-08 23:15
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-08 23:15 UTC
Labels: 5-0-x, 8-x-y, bug :beetle:, platform/macOS

**Comment by pushkin-** [comment] 2021-03-18 00:04
Follow [this issue](https://github.com/electron/electron/issues/28260) for updates
