### ISSUE TITLE
color of window's background property versus CSS background is different

### ISSUE THREAD

**Issue by msudgh** [electron/electron#13753] opened 2018-07-20 14:11 UTC
* Electron Version: v2.0.2
* Operating System (Platform and Version): Linux
* Last known working Electron version: 

**Expected Behavior**
while using window's background property in electron API and CSS background property I should get a similar result.

**Actual behavior**
I set the window's background property with color `#141414` and also applied `#141414` color to `html, body` tags with CSS but in the attached screenshot, the result isn't what I expect.

**Note:** the top section is CSS colored and the bottom section is native chromium background color. Also, this problem will occur while using [`--disable-gpu`](https://github.com/electron/electron/issues/12820#issuecomment-387798184)  flag and well my window is frameless and in Linux by selecting a text object or something else and dragging it to out electron will crash.

![screenshot from 2018-07-20 18-32-53](https://user-images.githubusercontent.com/11756815/43007060-85b71752-8c4c-11e8-9c36-886fd21b6dec.png)

**Comment by sindresorhus** [comment] 2018-07-20 14:59
This is a duplicate of https://github.com/electron/electron/issues/9671

**Comment by msudgh** [comment] 2018-07-20 15:12
@sindresorhus this issue occurred to me while using `--disable-gpu` flag but in #9671 didn't refer to this note. I think this's a different issue.

**Comment by MarshallOfSound** [comment] 2018-07-20 15:16
@sindresorhus is correct, this is a duplicate of that issue.  The window bg color is for some reason slightly offset from the CSS color

**Closed by MarshallOfSound** 2018-07-20 15:16 UTC
