### ISSUE TITLE
`navigator.connection` does not report accurate stats and the `onchange` event is never fired in a renderer process

### ISSUE THREAD

**Issue by ccnokes** [electron/electron#13074] opened 2018-05-25 16:49 UTC
* Electron Version: 2.0.0
* Operating System (Platform and Version): MacOS 10.13.4
* Last known working Electron version:  -

**Expected Behavior**
The `navigator.connection` API should work in a renderer process.

**Actual behavior**
The `navigator.connection` API does not seemed to get updated when there are network changes. 

**To Reproduce**
1. In a renderer process, run `navigator.connection.onchange = console.log`. Do the same in Chrome.
2. From bash run: `sudo ifconfig en0 down` (or whatever your active network interface is, or just turn off wifi).
3. Note that the event gets fired in Chrome but not in Electron. Also logging out `navigator.connection` in Electron still shows the `effectiveType` to be "4g", even though there is no network connectivity.  Chrome will show "none". 

**Additional Information**
I ❤️ Electron.

Fiddle: https://gist.github.com/ede2f41faa187fb08d71a343a33b98f8

**Comment by ccnokes** [comment] 2018-10-02 15:42
Confirmed this doesn't work in v3 either

**Comment by dryzhkov** [comment] 2018-11-29 00:40
navigator.connection seems to be working in v3.0.6 on MacOS 10.14 and windows

![image](https://user-images.githubusercontent.com/3053670/49191661-4403a400-f32c-11e8-9add-aa5dbfbd2bed.png)

**Comment by miniak** [comment] 2018-12-01 08:36
@dryzhkov it is not, those are just default values, which are not being updated.

**Comment by dryzhkov** [comment] 2018-12-03 17:55
@miniak - downlink, effectiveType and rtt all get updated when I throttle network using Chrome devtools.

![image](https://user-images.githubusercontent.com/3053670/49391778-783ae400-f6e1-11e8-9d40-1f610926d822.png)

**Comment by ccnokes** [comment] 2018-12-03 18:11
This does appear to be working in 3.0.6 but not in 3.1.0-beta. Here's an electron fiddle: https://gist.github.com/ccnokes/6359d26dce6f7781a1c03ab089838c78

**Comment by MarshallOfSound** [comment] 2018-12-03 18:14
@ccnokes Can you test 3.0.10, would be good to try narrow down the breakage to an exact patch bump if we did actually break something here

**Comment by ccnokes** [comment] 2018-12-15 22:36
@MarshallOfSound Sorry I spoke too soon before. It doesn't work in 3.0.6 either. It works when you simulate it via dev tools but not when you actually kill your network. Same behavior in 3.0.10, 3.1.0-beta3, 4.0.0-beta9.

**Comment by sofianguy** [comment] 2019-08-09 00:42
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 21:01
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by ccnokes** [comment] 2019-08-23 21:26
Confirmed that this is still broken in v6. Can we re-open @sofianguy? I updated the fiddle to work in 6. (https://gist.github.com/ede2f41faa187fb08d71a343a33b98f8)

**Comment by ahallicks** [comment] 2020-04-29 11:51
Just tested this in v8.2.3 with Electron Fiddle and the same issue remains: no update is logged when the network is changed.

**Comment by HyperClockUp** [comment] 2020-11-13 09:24
same problem in v9.0.4

**Comment by electron-triage** [comment] 2021-03-08 17:02
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-08 17:02 UTC
Labels: 2-0-x, 9-x-y, blocked/need-info ❌, bug :beetle:, platform/macOS

**Comment by kevin-wagner** [comment] 2021-06-01 13:56
I've got the same problem with electron version 13.0.1
