### ISSUE TITLE
Attaching chrome file upload dialog

### ISSUE THREAD

**Issue by HovhannesB** [electron/electron#15166] opened 2018-10-15 08:50 UTC
My chrome attach file dialog box is not attached to main window.

* Output of `node_modules/.bin/electron --version`: v3.0.2
* Operating System (Platform and Version): MAC OS High Sierra 10.13.6

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.11 

### Expected behavior
Chrome file dialog box should be attached to main Window, and don't let you do interact with main window till you haven't closed or do the actions in dialog.

### Actual behavior
Chrome file dialog box opens as independent window.

### How to reproduce
 1. $ git clone https://github.com/electron/electron-quick-start
2.  $ cd electron-quick-start
3.  $ npm install

4. change index.html code to 

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <input type="file" value="Check">
  </body>
</html>
```

5. $ npm start
6. Click "Check" button the opened file dialog window is detached independent
7. Change electron version in package.json to  "electron": "^2.0.2", do npm install and npm start
8. Clicke "Check" button and the opened file dialog is attached to main window

I recently changed my electron environment to electron 3 and electron-builder, and now I have problem with upload file dialog window. Before changing the environment the file upload dialog was attached to my mainWindow, now it is detached and I can use the program when dialog is opened, and even if I click outside the dialog fall behind of main window. I tried to use dialog feature of electron, which gives me the opportunity to attach file dialog, but it lacks performance, when I try to upload files more then 500-1000mb, I need to open them with fs.readFile or http get request and make them blob. Browser native file dialog do this for me and it works maybe 100 times faster then with fs. How can I attach native browser upload dialog to my main window?

**Comment by MarshallOfSound** [comment] 2018-10-15 09:32
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by nicbabchenko** [comment] 2018-10-29 16:55
Any news about this?

**Comment by HovhannesB** [comment] 2018-10-29 17:14
no there are no new, but if your files are not big enough, less then 50mb u can use electron dialog. My files can be more than 1GB.

**Comment by nicbabchenko** [comment] 2018-10-31 16:03
> no there are no new, but if your files are not big enough, less then 50mb u can use electron dialog. My files can be more than 1GB.

It's more convenient for me to work with web dialog) But it works weird now.

**Comment by sanchesking9** [comment] 2018-12-04 10:10
Any news about this?

**Comment by HovhannesB** [comment] 2018-12-05 07:07
No not yet, there is no good turnaround. If you are not very much depend on electron 3, you can use electron version 2, while this problem will be fixed.

>Вторник,  4 декабря 2018, 14:12 +04:00 от sanchesking9 <notifications@github.com>:
>
>Any news about this?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Hovhannes Babayan

**Comment by caldwellc** [comment] 2019-01-16 20:26
I am also seeing this behavior.

OS: MacOS Mojave: v10.14.1
Electron: v4.0.1

Any updates on when this issue will be fixed?

**Comment by HovhannesB** [comment] 2019-01-29 08:08
I run the program on electron v3.1.1 and it works, can you try version 3.1.1 to verify that the bug is fixed in this version.

**Comment by caldwellc** [comment] 2019-02-20 16:58
@HovhannesB I tested in v3.1.1 and it does appear to be fixed. Will this fix make its way into 4.0 as well?

**Comment by sondremare** [comment] 2019-08-27 13:37
Any news on this? It is a problem in electron v4.2.9 as well

**Comment by electron-triage** [comment] 2020-02-19 21:53
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:37
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:37 UTC
Labels: 3-0-x, 4-2-x, blocked/need-info ❌, bug :beetle:, platform/macOS
