### ISSUE TITLE
[Bug]: emoji display problem on macOS

### ISSUE THREAD

**Issue by Muscipular** [electron/electron#28849] opened 2021-04-26 13:03 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

macOS

### Operating System Version

10.15.7

### What arch are you using?

x64

### Expected Behavior

emoji display with letter-space

### Actual Behavior

emoji display without letter-space, it stack like letter-space: -5px
![image](https://user-images.githubusercontent.com/1454178/116086983-fa713c00-a6d2-11eb-9132-ec0f3202add1.png)

**Comment by nornagon** [comment] 2021-04-27 19:27
I can't reproduce this. https://gist.github.com/c3376ec0c9e6797e4f53407bcc3aa50b

![image](https://user-images.githubusercontent.com/172800/116300622-f3d6d900-a753-11eb-9b51-f96009001eab.png)

**Comment by Muscipular** [comment] 2021-05-07 02:19
code from https://gist.github.com/c3376ec0c9e6797e4f53407bcc3aa50b ,  my result: 
![image](https://user-images.githubusercontent.com/1454178/117388413-516de100-af1d-11eb-842f-8a131f52e2b1.png)
my macos version is 10.15.7 (19H524)

**Comment by nornagon** [comment] 2021-06-30 23:12
Hm, I still can't reproduce it. I'm also on macOS 10.15.7, using Electron 12:

![image](https://user-images.githubusercontent.com/172800/124042496-cf9ab100-d9bd-11eb-9a52-e6317e979479.png)

Perhaps this has to do with the system-default font? I notice that the font being shown in your screenshot is not `Times`, like it is on my machine.

**Comment by MarxJiao** [comment] 2021-07-06 10:14
I can reproduce this on Chrome on my external monitor with resolution 2560 * 1440. Seems to be a bug of Chrome.
![image](https://user-images.githubusercontent.com/9550456/124583222-661b1680-de85-11eb-813f-4a9301ee4a84.png)

**Comment by nornagon** [comment] 2021-07-06 18:41
Ah ok, I'm going to close this as blocked/upstream then. Perhaps file a bug at https://crbug.com/new?

**Closed by nornagon** 2021-07-06 18:41 UTC
Labels: blocked/upstream ❌, bug :beetle:

**Comment by MarxJiao** [comment] 2021-07-09 10:38
I found the  issue https://crbug.com/1159689.
