### ISSUE TITLE
Click handler is not executed for top level menu items

### ISSUE THREAD

**Issue by petrfelzmann** [electron/electron#3049] opened 2015-10-09 09:51 UTC
I create menu in render process.  But the `console.log` below is not executed for top level menu items.

``` javascript
var remote = require('remote'),
    Menu = remote.require('menu'),
    MenuItem = remote.require('menu-item');

var tmp = [{
    label: 'menu item',
    click: function() {
        console.log('menu item clicked'); // not executed
    }
}];

var menu = Menu.buildFromTemplate(tmp);
Menu.setApplicationMenu(menu);
```

**Comment by etiktin** [comment] 2015-10-09 17:18
Does it work when you execute this on the main process and not the renderer (on Windows you'll need to run the app with `--enable-logging` to see the output)?

**Comment by petrfelzmann** [comment] 2015-10-12 06:43
No, it's not working even from main process.

**Comment by hannanabdul55** [comment] 2015-10-13 01:07
Hey, I was wondering if I can start contributing to this project by fixing this bug.

**Comment by etiktin** [comment] 2015-10-13 01:12
Sure. Contributions are welcomed.

**Comment by fdelayen** [comment] 2016-06-13 21:02
It works fine if you follow the [doc](https://github.com/electron/electron/blob/master/docs/api/remote.md).
According to this one, it is not like a context menu. Your menu should have a submenu like that : 

```javascript
let menu = [{
  label: 'Menu',
  role: 'menu',
  submenu: [{
    label: 'menu item',
    click: function() {
      console.log('menu item clicked'); // executed
    }
  }]
}];
```
For the moment your code is creating an "Activate" submenu automatically and the click does not make it to the javascript side ([menu-item.js](https://github.com/electron/electron/blob/master/lib/browser/api/menu-item.js)) but I don't even know if it should appear.

@zcbenz What do you think about it ? It can search deeper why it does not work or not create top level menu without submenu. I don't know what is the most consistent solution.

**Comment by fdelayen** [comment] 2016-06-17 10:07
At least, that's what it's doing on Linux (and dbus is not notifying us that it's been activated, that's really strange). On windows, it doesn't create that strange submenu, but the click does not work either.
As menus are defined separately (globalmenu via dbus for X11 and another class for Windows), I'm not sure whether these bugs are related or platform-per-platform.
I'm gonna debug that on Windows to see what's happening when I'll have a bit of time :stuck_out_tongue:

**Comment by tonyganch** [comment] 2017-01-31 11:25
Hi, I wanted to check if the issue is fixed already since I see there is a PR merged.

**Comment by codebytere** [comment] 2017-09-27 01:33
Closing due to abandonment, but yes @tonyganch i think it has

**Closed by codebytere** 2017-09-27 01:33 UTC
Labels: component/menu, fixme/bug, help/beginner

**Comment by IshanArya** [comment] 2017-10-15 03:00
The problem still exists for MacOS at least.

**Comment by DesselBane** [comment] 2018-04-24 07:33
It still exists on Linux too

**Comment by asmab** [comment] 2018-07-17 08:59
Same problem on Linux

**Comment by codebytere** [comment] 2018-07-17 16:25
@DesselBane @IshanArya there is another related issue open at https://github.com/electron/electron/issues/8703, track that one for ongoing efforts to address this

**Comment by tHBp** [comment] 2019-11-16 10:56
Unfortunately, the issue linked above is closed as duplicate of #2895, which itself has been abandoned. The issue is fixed for Windows but affects macOS still (can't say for Linux though).

**Comment by MarkNBroadhead** [comment] 2020-12-31 02:08
This works as expected with MacOS 11.1 Big Sur, Node 12.18.3, Chrome 87.0.4280.88, and Electron 11.1.1.
