### ISSUE TITLE
can't drag file to the window of an electron app

### ISSUE THREAD

**Issue by jaweii** [electron/electron#12460] opened 2018-03-28 07:27 UTC
* Electron version: 1.8.3
* Operating system: windows 10

### Expected behavior

I want to drag a file to the window of an electron app , But I can't do this, when I drag the file to the application window, the mouse cursor becomes disabled.

### Actual behavior

the mouse cursor changes to disabled: 🛇
can't capture drag & drop event

### How to reproduce

> 
> //Install vue-cli and scaffold boilerplate
> npm install -g vue-cli
> vue init simulatedgreg/electron-vue my-project
> 
> //Install dependencies and run your app
> cd my-project
> yarn # or npm install
> yarn run dev # or npm run dev
> 
>
![2](https://user-images.githubusercontent.com/22613580/38015009-09931256-329d-11e8-964f-004531d09a18.gif)

**Comment by jukefr** [comment] 2018-08-25 17:59
Did you ever find a solution to this problem ? I am experiencing the same thing.

**Comment by sanchezpablo** [comment] 2018-08-30 09:56
Same behaviour here... any solution for this? Electron 2.0.4

**Comment by sanchezpablo** [comment] 2018-09-16 18:14
As far as I understand, the problem is when the application runs in Administration mode (windows), in this mode it's impossible to drag and drop files because the OS is avoiding this behavior, if the same application runs with normal user rights, the drag and drop of files works as expected. I don't know if there is some technique to change this, although.

**Comment by sofianguy** [comment] 2019-08-09 03:19
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by l1b3r** [comment] 2019-08-12 18:23
I can confirm having the same issue with electron `5.0.2` which wraps Angular `8.2.0` application. I have a file-input component that works as expected in a different Angular application that runs in the browser. However, if I copy-paste it into the Angular-under-electron application on Windows (no Admin privileges though), I'm also getting the 🛇 icon and can't drop anything.

```
<div class="drop-container"
     (dragover)="$event.preventDefault(); $event.dataTransfer.dropEffect = 'move';"
     (drop)="dropped($event)">...</div>
```
```
dropped(event) {
  event.preventDefault();
  // process the dropped files via accessing event.dataTransfer.items or event.dataTransfer.files.length
}
```
Is there any configuration required in the `ipcMain` process of electron to enable drag'n'dropping files from the OS into the application?

**Comment by bpasero** [comment] 2019-10-15 15:05
VSCode is also hitting this. Cross referencing: https://github.com/microsoft/vscode/issues/38999

**Comment by railsjack** [comment] 2019-10-25 19:32
same issue

**Comment by SharePointRadi** [comment] 2019-10-26 12:12
This is not a problem with Electron, this is a Windows OS concept (Mandatory Integrity Control).

If you run Electron from an administrator mode console, or any "Run as Administrator" process, then you try to drag&drop from a Windows Explorer instance (which can't run in administrator mode), then Drag & Drop, and many other capabilities, will not work. 

If I run my Electron app from a normal console with no administrator UAC elevation, I can drag and drop normally.

See Windows integrity levels, process explorer can show which process cross the integrity level.

![image](https://user-images.githubusercontent.com/5693618/67619283-4ef7da80-f802-11e9-836d-0c4440170ab7.png)

**Comment by swampthang** [comment] 2020-07-26 20:50
According this article, I created a .bat file with the following:

`cmd /min /C "set __COMPAT_LAYER=RUNASINVOKER && start "" %1"`

Saved it to my desktop and dragged the exe of my electron app onto the .bat file icon and it opened the app and allowed me to drag and drop onto the app window just fine. 

What I'm wondering is this: Is there a way to build that into the packaged app? Iow, have that command execute automatically when someone opens the app without having to tell someone what to do?

**Comment by pedro-surf** [comment] 2020-08-20 22:53
Any good news or better trick to accomplish it while developing on Win10?

**Comment by riccardospeggiorin-centropaghe** [comment] 2020-08-28 09:38
any news?
I still having the issue.  the OS (w10) block my drag n drop with the block-icon!

**Comment by zcbenz** [comment] 2020-12-10 07:16
As explained by https://github.com/electron/electron/issues/12460#issuecomment-421806991, this is a limitation applied by Windows itself and we are unable to solve it. So I'm closing this as won't fix.

**Closed by zcbenz** 2020-12-10 07:16 UTC
Labels: 2-0-x, 5-0-x, bug :beetle:, platform/windows, version/1.8.x

**Comment by ArnieGA** [comment] 2022-06-14 17:22
> This is not a problem with Electron, this is a Windows OS concept (Mandatory Integrity Control).
> 
> If you run Electron from an administrator mode console, or any "Run as Administrator" process, then you try to drag&drop from a Windows Explorer instance (which can't run in administrator mode), then Drag & Drop, and many other capabilities, will not work.
> 
> If I run my Electron app from a normal console with no administrator UAC elevation, I can drag and drop normally.
> 
> See Windows integrity levels, process explorer can show which process cross the integrity level.
> 
> ![image](https://user-images.githubusercontent.com/5693618/67619283-4ef7da80-f802-11e9-836d-0c4440170ab7.png)
> 
> I have posted more info in the referenced VSCode issue.

Confirming that running VSCode without administrative privileges solved the issue on my end.  
This creates a very big problem from many of us, yet for the moment is a workaround.
Thank you very very much!

**Comment by MoaMoa90** [comment] 2024-10-14 06:19
still same problem in 2024.10...

**Comment by Coded-By-Pooria** [comment] 2024-10-26 18:19
@MoaMoa90 I solved my problem by setting `navigateOnDragDrop: true` on creating BrowserWindow, actually like this:
```javascript
new BrowserWindow(
  {
// other configs
      webPreferences:{
// other configs
           navigateOnDragDrop: true,
      }
  }
)
```
I think this option allow dragging event get dispatch while dragging over window.
But note that i had these problem with electron32.1.2 and when i upgraded to 32.2.2 it work as fine

**Comment by sakibavian** [comment] 2025-05-14 11:14
i am getting the same problem. Is there any package to fix this? because my app runs on admin privilege. So i cannot withdraw it. But also I need to implement drag and drop functionality.
