### ISSUE TITLE
MacOS: Switching desktops will cause Electron to believe it has focus

### ISSUE THREAD

**Issue by scottnonnenberg-signal** [electron/electron#18212] opened 2019-05-08 16:54 UTC
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.2
* **Operating System:**
  * MacOS 10.14.4
* **Last Known Working Electron version:**:
  * unknown

### Expected Behavior

1. Give Signal Desktop focus in a conversation
2. GIve another application in that same MacOS desktop focus
3. Receive a message from someone in that conversation, see that it is visible in Signal Desktop but still unread
4. Switch to another MacOS desktop (or full screen app) and back to that desktop
5. Everything is the same as before - application from 2 has focus, Signal Desktop still has unread message

### Actual Behavior

5. Signal Desktop has cursor blinking in message composition box, message is marked read, and application from 2 has focus. SIgnal Desktop mistakenly believes that it has focus and is acting like it.

### To Reproduce

You can pull down Signal Desktop v1.24.1 right now and repro this. You can also repro this when you use Exposé. Signal Desktop appears to believe that it has focus when this happens as well.

### Additional Information

Original bug: https://github.com/signalapp/Signal-Desktop/issues/3310

**Comment by lehresman** [comment] 2019-06-18 17:24
I am seeing this behavior with Slack now today too.  Perhaps they updated to a more recent Electron which has this bug.  It has been plaguing me in Signal for a few months.

**Comment by fleish** [comment] 2019-07-31 07:49
Any movement on this? It's rendered signal quite unreliable as I'm missing new messages on the regular

**Comment by eppfel** [comment] 2019-08-08 20:14
I just tested and it seems this goes one level deeper to Chromium. You can reproduce the same behaviour with text input in Google Chrome.

**Comment by eppfel** [comment] 2019-08-09 08:04
I filed a bug report at Chromium: https://crbug.com/992319

**Comment by codebytere** [comment] 2019-08-30 20:52
I'm going to close this as it's not an issue on Electron itself; when that bug is fixed we'll shortly get it in a rolling Chromium update.

**Closed by codebytere** 2019-08-30 20:52 UTC
Labels: 4-2-x, bug :beetle:, platform/macOS

**Comment by eppfel** [comment] 2019-09-04 06:51
Sry, but would it not make more sense to mark it as upstream? Because it is definitely not resolved. Also for people searching for this issue.

**Comment by pmetzger** [comment] 2019-09-20 12:59
There may be workarounds that Electron could take while waiting for Chromium, so maybe this shouldn't be closed.
