### ISSUE TITLE
[Bug]: RequestAnimationFrame hangs the document after calling window.show();

### ISSUE THREAD

**Issue by AstroGD** [electron/electron#28603] opened 2021-04-10 15:56 UTC
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0.beta.21

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro version 20H2

### What arch are you using?

x64

### Last Known Working Electron version

12.0.0.beta.20

### Expected Behavior

The callback of RequestAnimationFrame should be called

### Actual Behavior

The callback of RequestAnimationFrame is only called if the window looses focus and regains it afterwards
(This is definitely not working in every version from 12.0.0.beta.21 to 13.0.0.beta.12)

### Testcase Gist URL

https://gist.github.com/49c429e5c8191338de03588a3de93b59

**Comment by AstroGD** [comment] 2021-04-10 15:58
![Electron_RAF_Bug](https://user-images.githubusercontent.com/35271072/114276254-1ebbf000-9a26-11eb-9561-00c23d198b2a.gif)
This is a gif showing the issue
The Electron app is programmed to show the blinking square. The colour should change every second

**Comment by AstroGD** [comment] 2021-04-10 15:59
The issue is not appearing if BrowserWindowOptions#show is set to true or BrowserWindowOptions#resizable is set to true

**Comment by AstroGD** [comment] 2021-04-10 16:17
I just checked and the issue still exists for electron 13 (I checked version 13.0.0.beta.12)

**Comment by Prinzhorn** [comment] 2021-04-12 14:17
Does it happen with `backgroundThrottling: false` as well? I think there is already an open issue about `show` not properly focusing windows on Windows. So the window looks like it's focused and in the foreground but it isn't really and backgroundThrottling is still active.

**Comment by AstroGD** [comment] 2021-04-13 09:12
Yes this also happens when backgroundThrottling is set to false.

**Comment by zcbenz** [comment] 2021-04-13 11:05
The only thing between beta.20 and beta.21 is a Chromium upgrade: https://github.com/electron/electron/pull/27280, so it looks like a Chromium regression. Can you try if it reproduces in a Chrome browser that is larger than version 89.0.4388.2?

**Comment by AstroGD** [comment] 2021-04-13 14:02
I tried to reproduce using `start chrome file:///PATH/TO/FILE/index.html` inside a command prompt as I think this is the closest to what is happening in electron but I couldn't reproduce the issue.

I also don't think this is a chrome related issue because as soon as the window is resizable the bug doesn't occur. Same if window.show is set to true. (But I'm not experienced with chrome it's just my feeling)

**Comment by deepak1556** [comment] 2021-04-14 23:28
Can you start the app like `<path-to>/electron.exe <fiddle-gist> --disable-features=CalculateNativeWinOcclusion` and see if the issue happens.

**Comment by AstroGD** [comment] 2021-04-15 08:23
This seems to resolve the issue. Without the flag I can reproduce the issue, with it I can't

**Comment by deepak1556** [comment] 2021-04-15 18:35
Thanks for confirming, there were a couple of changes related to occlusion tracking that went in between `12.0.0.beta.20` and `12.0.0.beta.21`. To help narrow down the change, can you clarify your setup as I am unable to reproduce the issue with the gist provided. Are you running on a VM or over a virtual desktop, do you have multiple displays setup ? 

@zcbenz are you able to repro the issue ?

**Comment by AstroGD** [comment] 2021-04-16 13:02
Sure - I am running Windows 10 Pro version 20H2 with 2 monitors (2560x1440px). I am not using a VM or a virtual desktop but I have WSL and Hyper-V running in the background. Is there anything else I can do that might help?

**Comment by AstroGD** [comment] 2021-05-28 12:06
Hey there - I just tested Electron V13 with this bug and it does not apply there anymore.
Version 12 is still affected.
Should I leave this issue open because of it being present in V12 or is this no longer relevant as V13 is released now?

**Comment by nornagon** [comment] 2021-06-22 22:21
Let's close this since it's fixed in 13.x, which is the current stable version of Electron.

**Closed by nornagon** 2021-06-22 22:21 UTC
Labels: 12-x-y, bug :beetle:, bug/regression :leftwards_arrow_with_hook:, platform/windows
