### ISSUE TITLE
Accelerators for invisible menu items should not fire on Windows

### ISSUE THREAD

**Issue by poiru** [electron/electron#9851] opened 2017-06-25 18:50 UTC
See https://github.com/electron/electron/issues/7737#issuecomment-257750474

**Comment by ohadleshno** [comment] 2017-07-05 19:45
hey i would like to take this one, Im a beginner can anyone guide me and help me understand what the problem is in more specific?

**Comment by fzxt** [comment] 2017-07-11 14:51
Would adding:

```cpp
    #if defined(OS_WIN)
      if (!item.model->IsVisibleAt(item.position)) {
        return false;
      }
```

In `bool TriggerAcceleratorTableCommand` in `electron/atom/browser/ui/accelerator_util.cc` do the trick?

**Comment by AyushBhargav** [comment] 2017-10-24 10:33
Hi, a beginner here! I would like to take this one.

**Comment by PrashantNagdeve** [comment] 2017-11-22 20:37
Hi, I am a beginner trying to work on this. Can anyone guide me on how to go ahead? If anyone has any document regarding installation,can you please share that doc. I checked on the website but that did not help.
Don't know if I am doing right.
I ran ->npm install electron --save-dev --save-exact
and then npm start
Got the following
 
D:\Programs\GIT repos\electron (master -> origin)
λ npm start

> electron@1.8.2-beta.2 start D:\Programs\GIT repos\electron
> python ./script/start.py

Traceback (most recent call last):
  File "./script/start.py", line 40, in <module>
    sys.exit(main())
  File "./script/start.py", line 34, in main
    subprocess.check_call([electron] + sys.argv[1:])
  File "C:\Python27\lib\subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! electron@1.8.2-beta.2 start: `python ./script/start.py`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.8.2-beta.2 start script 'python ./script/start.py'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     python ./script/start.py
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Programs\GIT repos\electron\npm-debug.log

D:\Programs\GIT repos\electron (master -> origin)

**Comment by kqpham** [comment] 2018-03-22 17:33
Hi is this issue still valid? if so can I take tackle this issue?

**Comment by steverandy** [comment] 2018-03-24 06:04
I'm using electron v2.0.0-beta.5.
The click event is no longer fired if the menu item visible is false. But there a side effect, if I have another menu item with the same accelerator and visible is true, that menu item click event will not fire.

**Comment by codebytere** [comment] 2018-05-09 04:12
Given the above comment, i'm going to go ahead and close this.

**Closed by codebytere** 2018-05-09 04:12 UTC
Labels: bug :beetle:, component/menu, good-beginner-issue :1st_place_medal:
