### ISSUE TITLE
Cannot disable MenuItem when specifying `role`

### ISSUE THREAD

**Issue by pdesantis** [electron/electron#13554] opened 2018-07-03 20:54 UTC
* Electron Version: 2.0.4
* Operating System (Platform and Version): macOS 10.13.5
* Last known working Electron version: Unknown

**Expected Behavior**
A `MenuItem` instance will be disabled when specifying `enabled: false`

**Actual behavior**
A `MenuItem` instance is still enabled when specifying `enabled: false` if it has a `role` specified.

**To Reproduce**
Clone this repo https://github.com/pdesantis/electron-api-demos/tree/menu-item-disable
The demo was forked from the official electron-api-demos repo. The only changes made are visible in this commit https://github.com/pdesantis/electron-api-demos/commit/c97c8762de24b4e9683ccc76c5fc2ab16b1f1c45

```sh
$ git clone https://github.com/pdesantis/electron-api-demos -b menu-item-disable
$ npm install
$ npm start
```

**Screenshots**
![screen shot 2018-07-03 at 1 52 49 pm](https://user-images.githubusercontent.com/1420364/42244098-73b98904-7ec8-11e8-9362-4c49c10a3e3a.png)

**Additional Information**
Removing the `role` from the `MenuItem` object correctly disables the item.

**Comment by Kthulu120** [comment] 2018-08-22 22:43
@pdesantis is this still an issue can't reproduce in 2.0.x. If not I can go ahead and close this

**Comment by samiskin** [comment] 2018-09-01 00:03
I poked around with @codebytere and narrowed things down a bit to `atom/browser/ui/cocoa/atom_menu_controller.mm`

In general, not all roles appear to be affected, only those found in `kRolesMap` excluding keys below `togglefullscreen` (ex: setting role: `toggletabbar` or `movetabtonewwindow` doesn't cause the issue to surface)


When looking at lines 253 to 263
```mm
    // Set menu item's role.
    [item setTarget:self];
    if (!role.empty()) {
      for (const Role& pair : kRolesMap) {
        if (role == base::ASCIIToUTF16(pair.role)) {
          [item setTarget:nil];
          [item setAction:pair.selector];
          break;
        }
      }
    }
``` 

We found that commenting out `[item setTarget:nil]` **xor** `[item setAction:pair.selector]` causes all items to be disabled, and commenting out **both** of them causes the items to be correctly enabled/disabled.

**Comment by codebytere** [comment] 2018-10-03 02:57
Hey all, i had some time to circle back to this. Essentially, when a `MenuItem` has a role, the `NSMenuItem` has a selector and MacOS automatically enables/disables it according to the first responder's implementation of `validateUserInterfaceItem`, which we cannot then override. Otherwise, MacOS calls `validateUserInterfaceItem` when the menu item is about to show, which we've implemented ourselves and which respects `visible` and `enabled`.

If anyone would like to explore potential solutions, we would welcome this, but and unfortunately my conclusion is that this is a `wontfix` at this time.

**Closed by codebytere** 2018-10-03 02:57 UTC
Labels: bug :beetle:, platform/macOS, version/2.0.x
