### ISSUE TITLE
[Bug]: preload cant be loaded in browserview while loadurl

### ISSUE THREAD

**Issue by rbmyself** [electron/electron#30592] opened 2021-08-18 12:43 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.15

### What operating system are you using?

Windows

### Operating System Version

	Windows 10	20H2 	‎2021/‎3/‎10 	19042.1110 	Windows Feature Experience Pack 120.2212.3530.0

### What arch are you using?

x64

### Last Known Working Electron version

Electron 13.2.0

### Expected Behavior

preload can be loaded while open browserview
my code：
```
 const view = new BrowserView({
      webPreferences: {
        // partition,
        // webviewTag: true,
        session: ses,
        webSecurity: false,
        contextIsolation: false,
        enableRemoteModule: false,

        allowRunningInsecureContent: true,
        // webviewTag: true,
        // preload: ENV_URL_SENTRY,
        experimentalFeatures: true,
        // nodeIntegrationInSubFrames: true,
        nodeIntegration: true,
        // nodeIntegration: true,
        // webSecurity: false,
        worldSafeExecuteJavaScript: false,
        // allowRunningInsecureContent: true,
        preload: ENV_URL_ESHOPPRELOAD,
      },
    });
    console.log(url, ENV_URL_ESHOPPRELOAD);
    if (/^http/.test(url)) {
      view.webContents.loadURL(url);   // while go here,no preload
    } else {
      // //console.log('loafile', viewUrl);
      view.webContents.loadFile(url);   //while go here ,preload successfully loaded
    }

    viewManager.showView(window, view, { x: 0, y: 36, width: width, height: height - 36 });
```
### Actual Behavior

preload cant loaded

### Additional Information

d

**Comment by codebytere** [comment] 2021-08-18 16:22
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by ckerr** [comment] 2021-08-18 19:04
Hey @rbmyself, in addition to what @codebytere requested -- can you also confirm the version numbers you're reporting here --  that it works in 13.2.0 but not in 12.0.15?

**Comment by codebytere** [comment] 2021-09-06 09:25
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2021-09-06 09:25 UTC
Labels: bug :beetle:, blocked/need-repro
