### ISSUE TITLE
Electron crashed after click download link

### ISSUE THREAD

**Issue by agata** [electron/electron#18347] opened 2019-05-18 02:27 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta3
* **Operating System:**
  * macOS 10.13.6 10.14.4 / Windows 7 -->
* **Last Known Working Electron version:**:
  * 5.0.1

### Expected Behavior
Clicked download link in renderer process, then show Save as dialog.

### Actual Behavior
Clicked download link in renderer process, then Electron app creshed.

### To Reproduce

1. Clone and start sample app
```sh
$ git clone https://github.com/agata/crash-electron-with-download-link.git
$ cd ./crash-electron-with-download-link
$ npm install
$ npm start
```
3. Click a download link in the app -> Crash electron app

#### Electron 5.0.1
<img width="1260" alt="Electron-5 0 1" src="https://user-images.githubusercontent.com/40473/57963469-8adb6980-795f-11e9-8cf6-1e58b8358e5f.png">

#### Electron 6.0.0-beta.3
Screencast: [Electron-6.0.0-beta.3.mov.zip](https://github.com/electron/electron/files/3193560/Electron-6.0.0-beta.3.mov.zip)

### Additional Information
If using [electron-dl](https://github.com/sindresorhus/electron-dl), it does not happen this problem.  Electron-dl don't show Save As dialog with default mode.

**Comment by MarshallOfSound** [comment] 2019-05-18 03:58
Duplicate of #18313

**Closed by MarshallOfSound** 2019-05-18 03:58 UTC

**Comment by MY020537** [comment] 2020-03-25 12:35
Hi, Was this ever resolved ? I am facing same issue when trying to load webpage in iframe having input type file on it. Upon clicking input type button it terminates the window unexpectedly. :(
