### ISSUE TITLE
[Bug]: screenX is not correct in the touchmove event

### ISSUE THREAD

**Issue by wscj** [electron/electron#30151] opened 2021-07-15 01:23 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.6

### What operating system are you using?

Windows

### Operating System Version

1903 and 1709

### What arch are you using?

x64

### Last Known Working Electron version

4.1.5

### Expected Behavior

In touch screen computer, the touchmove event has a screenX property, it's value is correct as I found it's definition in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/screenX)
> The screenX read-only property of the MouseEvent interface provides the horizontal coordinate (offset) of the mouse pointer in global (screen) coordinates.

### Actual Behavior

The screenX is always equal to pageX, not the horizontal coordinate in screen coordinates.

### Additional Information

For example:

``` js
document.body.addEventListener('touchmove', (e) => {
  console.log(e.touches)
})
```
The result as below

![111](https://user-images.githubusercontent.com/18430196/94239271-20b7d900-ff44-11ea-9c1d-1b5598a697de.png)

**Comment by codebytere** [comment] 2021-07-21 09:52
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2021-08-09 11:54
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2021-08-09 11:54 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, 13-x-y

**Comment by Timson020** [comment] 2023-04-07 04:07
in ```One machine```
it computer can touch and mouse 
touchEvent touches[0].screenX and screenY not correct.

**Comment by wscj** [comment] 2023-04-07 04:08
谢谢来信，祝生活愉快。

**Comment by Timson020** [comment] 2023-04-07 04:08
in MouseEvent screenX is correct
