### ISSUE TITLE
nativeWindowOpen with transparency not working

### ISSUE THREAD

**Issue by zarubond** [electron/electron#22281] opened 2020-02-19 14:31 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
6, 7, 8
* **Operating System:**
Windows 10 1909, 1903 (probably other OS too)
* **Last Known Working Electron version:**
never

### Expected Behavior
Windows opened with nativeWindowOpen should support transparency.

### Actual Behavior
Windwos created with nativeWindowOpen and window.open does not support option "transparent", the window just keeps the white background 

### To Reproduce
Open child window with window.open, intercept it in main process, add an transparent option to it and it will remain still be white

### Screenshots

Broken window with frame disabled and transparency enabled.

![image](https://user-images.githubusercontent.com/6961047/74842238-5a7b8e00-532a-11ea-8682-980afac48f2e.png)

### Additional Information
Electron quick start example

https://github.com/zarubond/electron-quick-start/tree/transparent_window

**Comment by codebytere** [comment] 2020-06-24 23:24
Note that this is currently a function of the fact that web prefs from a parent window are passed over the command line, so two windows in the same process will use the first windows command line. Thus, a child window opened with `nativeWindowOpen` will have the parent webprefs; fixing this essentially involves refactoring basically every single webpref out of cmd line args. One of our other maintainers is working on something that does this incidental to some other `nativeWindowOpen`, so this should hopefully be fixed at some soon juncture!

**Comment by codebytere** [comment] 2020-06-24 23:43
Closing this issue in favor of https://github.com/electron/electron/issues/20084 - the underlying refactor & fix will be the same for box.

**Closed by codebytere** 2020-06-24 23:43 UTC
Labels: 6-1-x, 7-1-x, 8-x-y, bug :beetle:, platform/all

**Comment by ibc** [comment] 2020-08-10 11:32
Just dealing with this issue right now. Just to clarify, please, is this supposed to work or not?

* Main window is open with `nativeWindowOpen: true`, `frame: true` and `transparent: false`.
* Within the `new-window` event in the main window (produced by `window.open()` in renderer) we create a new `BrowserWindow` with `frame: false` and `transparent: true` and provide it with the `webContents` given by the `new-window` event in its `options` argument:

```ts
mainWindow.webContents.on(
      'new-window',
      (
        event: Event,
        url: string,
        frameName: string,
        disposition: any,
        options: BrowserWindowConstructorOptions,
      ) => {
  event.preventDefault();

  const childWindow = new BrowserWindow({
    frame: false,
    transparent: true,
    webContents: options.webContents
  });

  event.newGuest = childWindow;
});
```

* And yes, the child window has white background instead of being transparent.

So, is this the unfortunate but expected behavior for now?

**Comment by ibc** [comment] 2020-08-10 14:31
BTW we have also tested the other way around, this is: create the main window in Electron with `transparent: true` and `frame: false` and calling `window.open()` from it. The child window is NOT frameless and it's NOT transparent. So it seems that any window created upon `new-window` event (`window.open()`) has hardcoded settings.

**Comment by ibc** [comment] 2020-08-11 13:52
Ok, no feedback. Here two hacks to make it work:

```ts
// Within the 'new-window' event:
// [...]

event.newGuest = window;

// Hack 1:
window.loadFile('');

// Hack 2:
window.setBackgroundColor('#00000000');
```

**Comment by tals** [comment] 2021-04-02 23:11
@ibc thanks! your trick with `event.newGuest` seems to work as of Electron 12.
I can spawn a transparent, frameless window with `window.open()`, and even share objects using the old school `window.opener` method.

I am not sure why this works, since it doesn't quite jive with what @codebytere mentioned, and we're still running under the same process.

P.S: The `loadFile` + `setBackgroundColor` hacks seems to no longer be necessary
