### ISSUE TITLE
Electron not opening (no errors, just wont open at all)

### ISSUE THREAD

**Issue by ColdNightHour** [electron/electron#6187] opened 2016-06-22 20:22 UTC
* Electron version: v1.2.4
* Operating system: Ubuntu LTS 14.04
If there is an existing Electron issue for this, please link it here:

https://github.com/atom/electron/issues

Describe your problem:
Electron won't open at all. I ran the command to install electron-prebuilt. Nothing happens when I run electron afterward. I am using the code found on the website under Quick Start and it won't open so it's not the code as far as I am concerned. There have been other issues regarding electron not opening but those have been with errors popping up when trying to run electron. Mine is simple: electron doesn't do anything. I don't really know why this is happening but I need it to work asap and after having spent four hours of trying to get it to work I am running out of options

**Comment by kevinsawicki** [comment] 2016-06-22 20:24
I believe this is a duplicate of #6178

**Closed by kevinsawicki** 2016-06-22 20:24 UTC

**Comment by ColdNightHour** [comment] 2016-06-22 20:27
That thread doesn't help much at all.

**Comment by kevinsawicki** [comment] 2016-06-22 20:28
> I don't really know why this is happening but I need it to work asap and after having spent four hours of trying to get it to work I am running out of options

Are you able to use `1.2.3` instead?

**Comment by ColdNightHour** [comment] 2016-06-22 20:32
I just did that. Saw that they were saying 1.2.2 or 1.2.3 worked but 1.2.4 produced the problem so I just downgraded to 1.2.3 and it works. Interesting. Thanks for the pointer to the duplicate thread.

**Comment by soryy708** [comment] 2020-04-27 11:42
Duplicate: https://github.com/electron-userland/electron-prebuilt/issues/156
