### ISSUE TITLE
Document file scheme behavior for different request mechanisms

### ISSUE THREAD

**Issue by adamvoss** [electron/electron#9474] opened 2017-05-15 17:45 UTC
* Electron version: 1.7.0, 1.6.5
* Operating system: Linux

### Expected behavior

Fetch and XHR behave the same.

A previous issue, #3922, appears to have the same complaint and the discussion on that issue at least makes it sound like the issue was fixed at the time.

### Actual behavior

XHR succeeds while fetch fails.

### How to reproduce

> git clone https://github.com/vossad01/electron-file-fetch-fail.git
$ npm install
$ npm start || electron .

Observe the output in the Developer Tools Console.

**Comment by kevinsawicki** [comment] 2017-05-15 18:01
@vossad01 can you confirm this has regressed? Does it work correctly for you in 1.6.9?

**Comment by vossad01** [comment] 2017-05-15 18:08
It did not work correctly in 1.6.5 (assuming my expected behavior is "correct").  Cross-referencing the date on the original issue with tags, the original issue fix likely released before 0.37.0

**Comment by kevinsawicki** [comment] 2017-05-15 19:25
> It did not work correctly in 1.6.5 or 1.6.9

Would it be possible for you to try older releases and find out when it might have initially regressed? Thanks.

**Comment by vossad01** [comment] 2017-05-15 20:08
2e78aba09038fadc785e65a23aceae3dae492776 is the commit attached to #3922.  Git tells me the first tag containing that commit is 0.36.10.

I tested this against 0.36.10, 0.36.12, and 0.37.8.  It fails for all of them.

**Comment by deepak1556** [comment] 2017-05-16 10:52
This is not a regression, the default behavior of fetch api with file scheme is same as chrome. Although the spec supports file scheme, there is no guidelines. Hence explicit support was avoided. You can add fetch support to file scheme in your app by using [webFrame.registerURLSchemeAsPrivileged](https://github.com/electron/electron/blob/master/docs/api/web-frame.md#webframeregisterurlschemeasprivilegedscheme-options) api. I would also recommend to avoid setting privileges to file scheme and instead create a custom protocol that is privileged. Closing this out, thanks!

**Comment by vossad01** [comment] 2017-05-16 13:13
@deepak1556 Shouldn't both requests fail?  In Chrome, both requests fail due to the same origin policy unless you pass `--disable-web-security`.  However, in electron the XMLHttpRequest request works without setting `webPreferences.webSecurity` to false.

**Comment by deepak1556** [comment] 2017-05-16 15:02
@vossad01 yeah that's because XHR and fetch have different CORS checking paths and we have allowed request to any origin succeed from file scheme. As you suggest the behavior should be consistent for both but changing it now will break apps, we can streamline this in 2.0. In the meantime we can document the behavior of file scheme and promote the use of custom protocols.

**Comment by codebytere** [comment] 2018-09-24 04:54
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 04:54 UTC
Labels: documentation :notebook:, enhancement :sparkles:, platform/linux, version/1.6.x, version/1.7.x
