### ISSUE TITLE
Electron apps entirely blank after updating to Windows 10 build 16257.1

### ISSUE THREAD

**Issue by Pokechu22** [electron/electron#10239] opened 2017-08-10 16:16 UTC
_All_ electron apps are blank for me after updating Windows 10 to the latest preview build (10.0.16257.1).  This has persisted after several restarts, and affects production apps (tested with slack and discord).

* Electron version: 1.7.5
* Operating system: Windows 10 insider preview build 10.0.16257.1

### Expected behavior

Apps would not be entirely blank (as was the case on windows build 10.0.15065).

### Actual behavior

Apps are completely blank, including the quick-start app (no modifications; this is just running it directly):

![electronblank](https://user-images.githubusercontent.com/8334194/29180289-30f6b952-7dac-11e7-99f2-ba833a6b25e8.png)

### How to reproduce

I'm not 100% sure if this will be consistent to reproduce, or only will happen on my machine.

The only step that I can provide is updating to the latest Windows insider preview build (10.0.16257.1), and then launching any electron app (I used [the sample given in the quick start section](https://github.com/electron/electron#quick-start)).

If there's more information I can provide, let me know.

**Comment by bpasero** [comment] 2017-08-12 08:02
@Pokechu22 does this reproduce with Electron 1.6.x too?

**Comment by Pokechu22** [comment] 2017-08-12 13:48
Tried 1.6.2; same problem as 1.7.5.

**Comment by bpasero** [comment] 2017-08-12 16:11
@Pokechu22 any output printed to the chrome developer console?

**Comment by Pokechu22** [comment] 2017-08-12 23:10
I don't know how to open the developer console; if the View &rarr; <kbd>Toggle Developer Tools</kbd> button is supposed to open it, that is blank as well, although it does make the app black instead of white (which changes back after toggling again):

![electronstillblank](https://user-images.githubusercontent.com/8334194/29244801-626d1374-7f77-11e7-9b33-8d9cee1a2f9d.png)

There's nothing of note in the command window:

```
C:\Users\Pokechu22\Downloads\electron-quick-start>npm start

> electron-quick-start@1.0.0 start C:\Users\Pokechu22\Downloads\electron-quick-start
> electron .



C:\Users\Pokechu22\Downloads\electron-quick-start>
```

I checked my pi to see what it should look like, and tried to switch to the console tab by clicking near the middle top.  As far as I can tell, there's nothing in the console, since I can select it and copy from there and there's no results (as a control, I typed in `test` and then tried again, and I successfully copied a `Uncaught ReferenceError` message, so I think I can actually select).

**Comment by kristaps-ancans** [comment] 2017-10-18 07:17
Issue persists on Windows 10 insider preview build 16299.19.

Affected applications - VS Code (doesn't matter which version), GeForce Experience.

**Comment by jarek-foksa** [comment] 2017-10-18 07:31
Have you tried launching the app with hardware acceleration disabled? This can be done with `--disable-gpu` command line flag or by calling `app.disableHardwareAcceleration()` in the main process before the app is ready.

**Comment by kristaps-ancans** [comment] 2017-10-18 07:41
Launching app with --disable-gpu works.

Seems that the same problem persisted on Ubuntu with HipChat, as it was unusable without --disable-gpu param.

**Comment by jarek-foksa** [comment] 2017-10-18 14:00
As a temporary workaround, perhaps Electron could check whether it is running on Windows build 16299.19 or later and automatically disable hardware acceleration? This appears to be a critical issue.

**Comment by MarshallOfSound** [comment] 2017-10-18 14:03
I'm running 17017 and not having this issue, not sure it's caused by the insider builds

**Comment by jarek-foksa** [comment] 2017-10-18 14:05
@Pokechu22, @kristaps-ancans Did you use virtual machine to test the apps? Can you confirm this issue also happens when not using a virtual machine?

**Comment by kristaps-ancans** [comment] 2017-10-18 14:17
@jarek-foksa not using virtual machine. Maybe it's related to 2 graphic cards? Have built in Intel one and NVIDIA GeForce.

**Comment by Pokechu22** [comment] 2017-10-18 15:51
Also not a virtual machine.  I'm using a laptop with AMD Radeon HD 6520G.

**Comment by codebytere** [comment] 2018-09-24 05:30
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 05:30 UTC
Labels: bug :beetle:, platform/windows, version/1.7.x
