### ISSUE TITLE
"win.setMenu(null)" did not hide the window menu bar

### ISSUE THREAD

**Issue by Unlimiter** [electron/electron#16521] opened 2019-01-23 21:45 UTC
* Output of `node_modules/.bin/electron --version`: **v4.0.1**
* Operating System (Platform and Version):
  * OS: **Linux, Xubuntu (Ubuntu)**.
  * Version: **18.04.1 LTS (Bionic Beaver)**.
  * Kernel version: **4.15.0-43-generic**
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): **v5.0.1**

**Procedure**
I put `win.setMenu(null)` directly under the browser window creation/declaration:
```
// Create the browser window.
win = new BrowserWindow({ width: 800, height: 600 })

// Hide the menu bar
win.setMenu(null)

...
```

**Expected Behavior**
I expected the menu bar to be hidden at window creation.

**Actual behavior**
The menu was still showing.

**Comment by algernon** [comment] 2019-01-28 07:47
I'm seeing the same thing, even if I call `setApplicationMenu(null)` after the `ready` event of `app`. Works fine with electron **v3.1.2**.

**Comment by algernon** [comment] 2019-01-28 08:22
I found a workaround: if we call `Menu.setApplicationMenu(null)` *before* creating the browser window, the menu is not shown. If we call it after, it is.

**Comment by Ajeey** [comment] 2019-03-18 05:23
Some more details here - 
https://github.com/electron/electron/issues/15901#issuecomment-473773527

**Comment by fxha** [comment] 2019-05-08 19:43
The Electron v5 application menu is also broken on Linux. When you need to remove the (application) menu at runtime you can build a dummy menu like `Menu.buildFromTemplate([])`.

**Comment by Unlimiter** [comment] 2019-05-08 20:31
I have now Electron **v5.0.1**, but the problem is still occuring.

**Comment by codebytere** [comment] 2019-05-09 15:35
@Unlimiter with what code? I just ran:
```
const {app, BrowserWindow, Menu} = require('electron')

let mainWindow

function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow() 

  mainWindow.loadFile('index.html')

  const menu = Menu.buildFromTemplate([
    { role: 'appMenu' }
  ])

  mainWindow.setMenu(menu)
  console.log('we are here')
  mainWindow.setMenu(null)

  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', function () {
  if (mainWindow === null) createWindow()
})
```
and could not reproduce it. I'm on 16.06 and v5.0.1.

**Comment by fxha** [comment] 2019-05-09 23:32
@codebytere You can reproduce the issue with the following example (tested on Fedora 29, v5.0.1):

```js
const {app, BrowserWindow, Menu} = require('electron')

let mainWindow

function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow() 

  Menu.setApplicationMenu(Menu.buildFromTemplate([{ label: 'Init' }]))

  mainWindow.loadFile('index.html')

  mainWindow.webContents.once('did-finish-load', () => {
    Menu.setApplicationMenu(null)

    setTimeout(() => {
      const menu = Menu.buildFromTemplate([{ label: 'File' }])
      Menu.setApplicationMenu(menu)
      Menu.setApplicationMenu(null)
    }, 500)
  })

  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', function () {
  if (mainWindow === null) createWindow()
})
```

**Comment by josephpei** [comment] 2019-05-24 05:41
Ubuntu 18.04.02, Gnome 3.28, Electron 5.0.1, have the same problem.

setApplicationMenu(null) can hide the Menu, but press 'Alt' key will bring up the Menu.

**Comment by codebytere** [comment] 2019-05-24 14:53
@Unlimiter you put
> Output of node_modules/.bin/electron --version: v4.0.1
and 
> Output of node_modules/.bin/electron --version on last known working Electron version (if applicable): v5.0.1
do you mean that it's _working_ in `4.0.1`? These seem to be reversed so i'd like to clarify :)

**Comment by hhyyrylainen** [comment] 2019-06-08 19:34
I also have the same issue with electron 5.0.3:
```
$ node_modules/.bin/electron --version
v5.0.3
```
On Fedora 29 with Gnome.

The posted workaround `electron.Menu.setApplicationMenu(null);` works for me. With the auto hide option pressing alt brings up the menu. The new function [win.removeMenu](https://electronjs.org/docs/api/browser-window#winremovemenu-linux-windows) does not work either.

My code is here: https://github.com/Revolutionary-Games/Thrive-Launcher/blob/b5939c9f99b0f2aa8f4cfc488559b2558e2f9a8b/main.js#L76

**Comment by codebytere** [comment] 2019-06-09 03:57
@hhyyrylainen what confuses me here is that there should be no difference between the two since one directly invokes the other:

```
Menu.setApplicationMenu = function (menu) {
  if (menu && menu.constructor !== Menu) {
    throw new TypeError('Invalid menu')
  }

  applicationMenu = menu
  v8Util.setHiddenValue(global, 'applicationMenuSet', true)

  if (process.platform === 'darwin') {
    if (!menu) return
    menu._callMenuWillShow()
    bindings.setApplicationMenu(menu)
  } else {
    const windows = TopLevelWindow.getAllWindows()
    return windows.map(w => w.setMenu(menu))
  }
}
```

specifically:
```
return windows.map(w => w.setMenu(menu))
```
is calling `setMenu`. This leads me to think that perhaps the wrong menu is being incorrectly set to `null`? I can try to look further.

**Comment by hhyyrylainen** [comment] 2019-06-09 09:08
The call to `electron.Menu.setApplicationMenu(null);` needs to be done *before* the window is created. Otherwise it does not work. 
I just tried moving `Menu.setApplicationMenu` to be after the window creation and it stopped working. So setApplicationMenu seems to do something that affects what happens when the window is created. But doesn't work after the window is created.

**Comment by vasyl-shumskyi** [comment] 2019-09-24 10:08
I would like to remove menu from specific window only (for example: About App window), but not globally. Is it possible?

**Comment by TheBoneJarmer** [comment] 2019-10-20 12:36
Using electron version 6.0.12 and the solution @hhyyrylainen suggested works for me as well. Running Ubuntu 18.04 LTS. The functions "win.setMenu" or "win.removeMenu" did not work.

`const { app, BrowserWindow, Menu } = require("electron");

Menu.setApplicationMenu(null);
app.on("ready", createWindow);

/* CALLBACKS */
function createWindow() {
		
	let win = new BrowserWindow({
		width: 800,
		height: 600
	});
	
	win.loadFile("www/index.html");
}`

**Comment by Naphier** [comment] 2019-10-24 00:28
`Menu.setApplicationMenu(null);` seems to be the only way I could now get this working with Windows 10 @ electron version 7.0.0 :/

**Comment by whyboris** [comment] 2019-11-03 05:59
🙇 @algernon for `Menu.setApplicationMenu(null)` <-- the only thing that worked 🎉 
⚠️ ~`win.setMenu(null)`~ does not work despite [documentation](https://electronjs.org/docs/api/browser-window#winsetmenumenu-linux-windows)
⚠️ ~`win.removeMenu()`~ does not work despite [documentation](https://electronjs.org/docs/api/browser-window#winremovemenu-linux-windows)

**Comment by cmgcomsol** [comment] 2019-11-03 15:49
debian 10 nodejs 10 lts 
win.setMenu(null) does not work despite documentation
win.setMenu(menu)  does not work despite documentation
win.removeMenu() does not work despite documentation

**Comment by andmm** [comment] 2019-11-12 20:49
> Thank you  @algernon for `Menu.setApplicationMenu(null)` <-- the only thing that worked  (Electron 7 & Windows 10)
>  ~`win.setMenu(null)`~ does not work despite [documentation](https://electronjs.org/docs/api/browser-window#winsetmenumenu-linux-windows)
>  ~`win.removeMenu()`~ does not work despite [documentation](https://electronjs.org/docs/api/browser-window#winremovemenu-linux-windows)

Can confirm this issue

**Comment by benjhess** [comment] 2020-02-06 15:20
BTW: Using `Menu.setApplicationMenu(null)` will disable copy and past keyboard shortcuts, which is not ideal. There seems to be no way to disable the menu and keep copy/paste functionality...

**Comment by johannesjo** [comment] 2020-02-06 17:05
@benjhess do you mean on mac?

**Comment by joehonton** [comment] 2020-02-21 16:55
This appears to be a duplicate of the previously report issue https://github.com/electron/electron/issues/15901

**Comment by zcbenz** [comment] 2020-11-19 07:25
I believe this had already been fixed by https://github.com/electron/electron/pull/23214, and I can not reproduce with the code in above comments.

**Closed by zcbenz** 2020-11-19 07:25 UTC
Labels: bug :beetle:, platform/linux

**Comment by pyrusdev** [comment] 2024-06-14 02:27
Use win.setMenuBarVisibility(false)

```
function createWindow() {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
    },
  });

  win.setMenuBarVisibility(false)

  win.loadFile('index.html');
}

```
