### ISSUE TITLE
process.windowsStore reports undefined when it should be true 

### ISSUE THREAD

**Issue by bitdisaster** [electron/electron#21689] opened 2020-01-06 23:57 UTC
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0 and up
* **Operating System:**
  *  Windows 10, 1903 
* **Last Known Working Electron version:**
  *  6.1.7 

### Expected Behavior

process.windowsStore returns true
### Actual Behavior

process.windowsStore returns undefined 
### To Reproduce
Package and run App as a Windows Store App

**Comment by codebytere** [comment] 2020-01-08 00:28
Duplicate of https://github.com/electron/electron/issues/18161.

**Closed by codebytere** 2020-01-08 00:28 UTC
