### ISSUE TITLE
crash when using ANY hotkey in the franz app

### ISSUE THREAD

**Issue by Daij-Djan** [electron/electron#8972] opened 2017-03-20 21:07 UTC
Hi,
I got a crash (always) when crash when using ANY hotkey in the franz app

---

Performing @selector(itemSelected:) from sender NSMenuItem 0x6100002a6180

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   com.github.electron.framework 	0x0000000103079dbc 0x10242c000 + 12901820
1   com.github.electron.framework 	0x00000001024a144d atom::api::WebContents::IsFocused() const + 45
2   com.github.electron.framework 	0x0000000102496c20 bool base::internal::RunnableAdapter<bool (atom::api::WebContents::*)() const>::Run<atom::api::WebContents const*>(atom::api::WebContents const*&&) + 32
3   com.github.electron.framework 	0x0000000102496bec bool base::internal::InvokeHelper<false, bool, base::internal::RunnableAdapter<bool (atom::api::WebContents::*)() const> >::MakeItSo<atom::api::WebContents const*>(base::internal::RunnableAdapter<bool (atom::api::WebContents::*)() const>, atom::api::WebContents const*&&) + 28
4   com.github.electron.framework 	0x0000000102496bca base::internal::Invoker<base::IndexSequence<>, base::internal::BindState<base::internal::RunnableAdapter<bool (atom::api::WebContents::*)() const>, bool (atom::api::WebContents const*)>, base::internal::InvokeHelper<false, bool, base::internal::RunnableAdapter<bool (atom::api::WebContents::*)() const> >, bool (atom::api::WebContents const*)>::Run(base::internal::BindStateBase*, atom::api::WebContents const*&&) + 26
5   com.github.electron.framework 	0x0000000102496acc base::Callback<bool (atom::api::WebContents const*), (base::internal::CopyMode)1>::Run(atom::api::WebContents const*) const + 28
6   com.github.electron.framework 	0x0000000102496a8c void mate::internal::Invoker<mate::internal::IndicesHolder<0ul>, atom::api::WebContents const*>::DispatchToCallback<bool>(base::Callback<bool (atom::api::WebContents const*), (base::internal::CopyMode)1>) + 60
7   com.github.electron.framework 	0x000000010249695c mate::internal::Dispatcher<bool (atom::api::WebContents const*)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 124
8   libnode.dylib                 	0x0000000106e24eda v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) + 298
9   libnode.dylib                 	0x0000000106e5e925 0x106a7c000 + 4073765
10  libnode.dylib                 	0x0000000106e6078e 0x106a7c000 + 4081550
11  ???                           	0x00002f0ade808ba7 0 + 51723729144743
12  ???                           	0x00002f0adeaa9ac7 0 + 51723731901127
13  ???                           	0x00002f0adeac7b0a 0 + 51723732024074
14  ???                           	0x00002f0ade845fa3 0 + 51723729395619
15  ???                           	0x00002f0ade829f0f 0 + 51723729280783
16  libnode.dylib                 	0x000000010713899b 0x106a7c000 + 7063963
17  libnode.dylib                 	0x000000010713879b v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 331
18  libnode.dylib                 	0x0000000106e0b8b7 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 535
19  com.github.electron.framework 	0x000000010245f87c mate::internal::V8FunctionInvoker<void (v8::Local<v8::Value>, int)>::Go(v8::Isolate*, mate::internal::SafeV8Function const&, v8::Local<v8::Value>, int) + 252
20  com.github.electron.framework 	0x000000010245fa89 void base::internal::RunnableAdapter<void (*)(v8::Isolate*, mate::internal::SafeV8Function const&, v8::Local<v8::Value>, int)>::Run<v8::Isolate* const&, mate::internal::SafeV8Function const&, v8::Local<v8::Value>, int>(v8::Isolate* const&&&, mate::internal::SafeV8Function const&&&, v8::Local<v8::Value>&&, int&&) + 25
21  com.github.electron.framework 	0x000000010245fa65 void base::internal::InvokeHelper<false, void, base::internal::RunnableAdapter<void (*)(v8::Isolate*, mate::internal::SafeV8Function const&, v8::Local<v8::Value>, int)> >::MakeItSo<v8::Isolate* const&, mate::internal::SafeV8Function const&, v8::Local<v8::Value>, int>(base::internal::RunnableAdapter<void (*)(v8::Isolate*, mate::internal::SafeV8Function const&, v8::Local<v8::Value>, int)>, v8::Isolate* const&&&, mate::internal::SafeV8Function const&&&, v8::Local<v8::Value>&&, int&&) + 21
22  com.github.electron.framework 	0x000000010245fa37 base::internal::Invoker<base::IndexSequence<0ul, 1ul>, base::internal::BindState<base::internal::RunnableAdapter<void (*)(v8::Isolate*, mate::internal::SafeV8Function const&, v8::Local<v8::Value>, int)>, void (v8::Isolate*, mate::internal::SafeV8Function const&, v8::Local<v8::Value>, int), v8::Isolate*&, mate::internal::SafeV8Function>, base::internal::InvokeHelper<false, void, base::internal::RunnableAdapter<void (*)(v8::Isolate*, mate::internal::SafeV8Function const&, v8::Local<v8::Value>, int)> >, void (v8::Local<v8::Value>, int)>::Run(base::internal::BindStateBase*, v8::Local<v8::Value>&&, int&&) + 71
23  com.github.electron.framework 	0x000000010245d606 base::Callback<void (v8::Local<v8::Value>, int), (base::internal::CopyMode)1>::Run(v8::Local<v8::Value>, int) const + 38
24  com.github.electron.framework 	0x000000010245d5c7 atom::api::Menu::ExecuteCommand(int, int) + 55
25  com.github.electron.framework 	0x000000010245d61d non-virtual thunk to atom::api::Menu::ExecuteCommand(int, int) + 13
26  com.github.electron.framework 	0x00000001024e6845 0x10242c000 + 763973
27  libsystem_trace.dylib         	0x00007fffda5adc3d _os_activity_initiate + 61
28  com.apple.AppKit              	0x00007fffc30d1c9c -[NSApplication(NSResponder) sendAction:to:from:] + 456
29  com.apple.AppKit              	0x00007fffc2ba5e06 -[NSMenuItem _corePerformAction] + 324
30  com.apple.AppKit              	0x00007fffc2ba5b72 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
31  libsystem_trace.dylib         	0x00007fffda5adc3d _os_activity_initiate + 61
32  com.apple.AppKit              	0x00007fffc2ba4985 -[NSMenu performKeyEquivalent:] + 367
33  com.github.electron.framework 	0x00000001024bff8b atom::CommonWebContentsDelegate::HandleKeyboardEvent(content::WebContents*, content::NativeWebKeyboardEvent const&) + 139
34  com.github.electron.framework 	0x0000000102486c5d atom::api::WebContents::HandleKeyboardEvent(content::WebContents*, content::NativeWebKeyboardEvent const&) + 45
35  com.github.electron.framework 	0x0000000102486c52 atom::api::WebContents::HandleKeyboardEvent(content::WebContents*, content::NativeWebKeyboardEvent const&) + 34
36  com.github.electron.framework 	0x0000000102486c6d non-virtual thunk to atom::api::WebContents::HandleKeyboardEvent(content::WebContents*, content::NativeWebKeyboardEvent const&) + 13
37  com.github.electron.framework 	0x0000000102f3ebcc 0x10242c000 + 11611084
38  com.github.electron.framework 	0x0000000102f3e7c7 0x10242c000 + 11610055
39  com.github.electron.framework 	0x0000000102f3d5a4 0x10242c000 + 11605412
40  com.github.electron.framework 	0x0000000102f3d40e 0x10242c000 + 11605006
41  com.github.electron.framework 	0x0000000102f3d08f 0x10242c000 + 11604111
42  com.github.electron.framework 	0x0000000102f95fd1 0x10242c000 + 11968465
43  com.github.electron.framework 	0x0000000102f835d9 0x10242c000 + 11892185
44  com.github.electron.framework 	0x00000001035479c8 0x10242c000 + 17938888
45  com.github.electron.framework 	0x000000010260172b 0x10242c000 + 1922859
46  com.github.electron.framework 	0x0000000102622543 0x10242c000 + 2057539
47  com.github.electron.framework 	0x000000010262283c 0x10242c000 + 2058300
48  com.github.electron.framework 	0x0000000102622b9b 0x10242c000 + 2059163
49  com.github.electron.framework 	0x00000001025f62cd 0x10242c000 + 1876685
50  com.github.electron.framework 	0x00000001026196ba 0x10242c000 + 2021050
51  com.github.electron.framework 	0x00000001025f5cd4 0x10242c000 + 1875156
52  com.apple.CoreFoundation      	0x00007fffc4e43981 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
53  com.apple.CoreFoundation      	0x00007fffc4e24a7d __CFRunLoopDoSources0 + 557
54  com.apple.CoreFoundation      	0x00007fffc4e23f76 __CFRunLoopRun + 934
55  com.apple.CoreFoundation      	0x00007fffc4e23974 CFRunLoopRunSpecific + 420
56  com.apple.HIToolbox           	0x00007fffc43afa5c RunCurrentEventLoopInMode + 240
57  com.apple.HIToolbox           	0x00007fffc43af891 ReceiveNextEventCommon + 432
58  com.apple.HIToolbox           	0x00007fffc43af6c6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
59  com.apple.AppKit              	0x00007fffc29555b4 _DPSNextEvent + 1120
60  com.apple.AppKit              	0x00007fffc30cfd6b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2789
61  com.apple.AppKit              	0x00007fffc2949f35 -[NSApplication run] + 926
62  com.github.electron.framework 	0x00000001025f6b26 0x10242c000 + 1878822
63  com.github.electron.framework 	0x00000001025f6124 0x10242c000 + 1876260
64  com.github.electron.framework 	0x0000000102638a61 0x10242c000 + 2148961
65  com.github.electron.framework 	0x0000000102d60cab 0x10242c000 + 9653419
66  com.github.electron.framework 	0x0000000102d60b00 0x10242c000 + 9652992
67  com.github.electron.framework 	0x0000000102d63052 0x10242c000 + 9662546
68  com.github.electron.framework 	0x0000000102d5ce1d 0x10242c000 + 9637405
69  com.github.electron.framework 	0x0000000102cc8d30 0x10242c000 + 9030960
70  com.github.electron.framework 	0x0000000102cc7f16 0x10242c000 + 9027350
71  com.github.electron.framework 	0x000000010242e747 AtomMain + 71
72  io.adlk.franz                 	0x0000000102420ec6 main + 38
73  libdyld.dylib                 	0x00007fffda37b255 start + 1

**Comment by kevinsawicki** [comment] 2017-03-20 21:14
@Daij-Djan what version of Electron is it using?

**Comment by Daij-Djan** [comment] 2017-03-20 21:25
@kevinsawicki 
sure sorry -- 10m later - how to find it without access to the source.
I only have the bundled binary

**Comment by kevinsawicki** [comment] 2017-03-20 22:09
Looks like this is a duplicate of https://github.com/electron/electron/issues/6642 which was released in Electron 1.3.2.

Looking at the build on their website it looks like they are using a version prior to that, upgrading should resolve this, closing this out here.

**Closed by kevinsawicki** 2017-03-20 22:09 UTC
