### ISSUE TITLE
ipcRenderer.send() freezes renderer thread.

### ISSUE THREAD

**Issue by vshesh** [electron/electron#5775] opened 2016-05-30 21:57 UTC
* Electron version: 1.2.0
* Operating system: Mac OSX Yosemite

I am using React to render the view on the frontend, and have a dropzone element.
I am able to receive the files that are uploaded, and I've written a function that updates a local db (lowDB - just a json file) and runs some scripts to process the files. 

However, while it is processing (on the main thread) the renderer thread freezes and gives a beach ball of death. I am sending events back to the renderer thread that contain the progress of this long-running process, but those only appear AFTER the process is complete, all in a row, like they've been clogged up in a pipe somewhere. 

Roughly:

View file:
```js

var DropzoneDemo = React.createClass({
  onDrop: function (files) {
    console.log('sending files: ' + JSON.stringify(files));
    ipcRenderer.send('photo-upload', files.map((file) => file.path));
  },
  
  render: function () {
    return (
      <div>
      	<Dropzone onDrop={this.onDrop}>
      	  <div>Drop some files here, or click to select files to upload.</div>
      	</Dropzone>
        {this.props.hashed} of {this.props.totalfiles}
      </div>
    );
  }
});
```

main.js
```js
ipcMain.on('photo-upload', function(event, arg) {
  db.resetDB();
  //Long term process being run as a shell script
  resizeAll(dir, function(error, stdout, stderr){
    if(error){
      console.log(error);
      console.log(stderr);
    }
  });
  // ... more code here to run another process that deals with the first process
  console.log("returning from photo-upload event.")
})
```

The log `returning from photo-upload event` occurs immediately after calling the function, which means that nothing is blocking the thread... yet everything freezes.

Help!

**Comment by davej** [comment] 2016-05-31 10:48
Just because the line is logged out does not mean that the operation is not blocking it just means that it doesn't immediately synchronously block.

A pattern that has developed among Electron apps is to use a worker window to do these kind of tasks. Generally it is a hidden window that performs CPU intensive tasks. You can then send `ipc` events to the worker window by proxying it through the main process.

This question is probably better suited to StackOverflow or similar.

**Comment by zcbenz** [comment] 2016-05-31 13:19
Closing since it is a usage question, thanks @davej for answering this.

**Closed by zcbenz** 2016-05-31 13:19 UTC

**Comment by tommoor** [comment] 2016-06-16 22:51
@zcbenz we've also started to see similar behaviour since upgrading to 1.2 from 0.37 - I think there might have been a regression introduced somewhere actually that is causing the renderer thread to block...

**Comment by huanghaiyang** [comment] 2017-07-13 13:19
it freeze css , html render and js execute

**Comment by bridiver** [comment] 2017-07-13 13:55
@davej @vshesh  said it was running in a shell script so if the log message is printed immediately that means he must be using a non-blocking child process. Anything that blocks the browser process UI thread will effectively freeze the whole app, but at least from his explanation that doesn't sound like what is happening here

**Comment by davej** [comment] 2017-07-13 14:39
@bridiver would need a smaller more isolated test case to verify that.

**Comment by bridiver** [comment] 2017-07-13 14:51
@vshesh can you add the code for `resizeAll`?

**Comment by vshesh** [comment] 2017-07-14 05:30
```js
/**
* calls the resizeall script on the arguments (each of which should be a
* directory).
* callback is from child_process.execFile, and it takes error/stdout/stderr
*/
function resizeAll(dir, callback) {
  var e = execFile('bash',
    Array.isArray(dir) ?
      fp.concat(['tools/resizeall'], dir)
      : ['tools/resizeall', dir],
    callback);
  cleanup(() => e.kill());
}
```

it's been a while since I touched this project, and I'm not sure what a minimal example would be. I'm also not sure whether this issue still persists in the latest version of electron...
