### ISSUE TITLE
BrowserView.setAutoResize shifts upwards when resized

### ISSUE THREAD

**Issue by blingenau** [electron/electron#13468] opened 2018-06-27 18:56 UTC
* Electron Version: 1.7.x, 1.8.x, 2.0.x
* Operating System (Platform and Version): OSX 10.12.6
* Last known working Electron version: Don't think it ever did

**Expected Behavior**
BrowserView should resize automatically with a BrowserWindow resize, maintaining its position.

**Actual behavior**
When the BrowserWindow resizes, the BrowserView seems to shift into the titlebar, cutting off pixels at the top.

**To Reproduce**
```javascript
const window = new BrowserWindow({width: 400, height: 400});
const view = new BrowserView();
window.setBrowserView(view);
view.setBounds({x: 0, y: 0, width: 400, height: 400});
view.setAutoResize({width: true, height: true});
view.webContents.loadURL('https://github.com');
```
**Screenshots**
After starting up, resize the BrowserWindow and the BrowserView will appear to shift upwards. See a gif of it here: https://imgur.com/bEfTkMD

**Additional Information**
Observed with Electron Fiddle on multiple versions, from 1.7-2.0

**Comment by austincondiff** [comment] 2019-01-26 21:38
This is still an issue with me. Even with your fix I still see it shifting upwards.

**Comment by austincondiff** [comment] 2019-01-31 18:38
Doesn't work. This hack really shouldn't be necessary though.

**Comment by Nashorn** [comment] 2019-05-21 16:07
I am running 
Node 12, Electron 5.0.1 -- I am able to reproduce this bug. Resizing the browser window causes the browserview to shift upwards by about 75-80% of the browser windows original height even with setAutoResize() being used.

I was able to correct it by setting my browserwindow height to 1200 and the browserview to 935, setAutoResize() then keeps it synched.

Definitely a bug.

**Comment by juanger** [comment] 2019-06-19 00:18
This behavior is too erratic, it gets worse when you don't set a `minWidth` or `minHeight`. I'm doing my own auto-resize on 'will-resize' and it seems to be even faster/more fluid than with `setAutoResize`.

```
const viewAnchor = {x: 0, y: 100};
window.on('will-resize', (_event, newBounds) => {
    view.setBounds({ ...viewAnchor, width: newBounds.width, height: newBounds.height - viewAnchor.y});
  })
```

**Comment by tlentz** [comment] 2019-07-02 15:41
I am running into the same issue, is there a known solution for this?  Seems to work fine on windows, but MacOS shifts upwards.

**Comment by Nashorn** [comment] 2019-07-02 16:24
@juanger seems to have a solution i did not try. I resorted to not embedding the views 👎

**Comment by pushkin-** [comment] 2019-07-16 15:31
@juanger That does appear to be more fluid, but it seems to break the case where the window is resized by clicking the maximize button. It looks like will-resize doesn't get emitted in that case, and the browser view doesn't resize.

**Comment by juanger** [comment] 2019-07-16 17:06
@pushkin- Maximize and full screen works for me with electron `5.0.2`. Maybe that is a different bug in different versions?

**Comment by pushkin-** [comment] 2019-07-16 17:14
@juanger  Ok, I tried in 5.0.6. I believe I resized manually first by dragging the edge a bunch of times, and then I tried maximizing it and saw the black strips on the side. (note I added your workaround and removed the setAutoResize call)

**Comment by pushkin-** [comment] 2019-07-16 20:52
@juanger Looked at [docs](https://electronjs.org/docs/api/browser-window#event-will-resize-macos-windows) and `'will-resize'` only gets emitted if the window is being resized manually. (I presume that means by dragging the edge). Even if clicking the maximize button works for you, programmatic resizes won't resize the BrowserView.

**Comment by kevinlinv** [comment] 2019-08-06 01:23
I had the same issue recently.

**Here is my Hypothesis**:
I think the core reason why it is broken, is due to the difference between the `BrowserWindow` 
bounds and the `BrowserView` bounds.

The case above assumes that `BrowserWindow` height will be `400` while in fact it is not (at least not in the context we assumes that it is). Reason being that it takes into account the height of the titlebar frame, meaning that when it is set like the following:

```JS
// actual browserWindow height will be `378` here,
// since `22` px is used for the titlebar frame on mac.
// I mean it is still `400` tbh 😅 
const window = new BrowserWindow({width: 400, height: 400});
const view = new BrowserView();
window.setBrowserView(view);

// However, the height of browserView is still `400` here,
// which will now go out of bounds by `22` px to begin with.
view.setBounds({x: 0, y: 0, width: 400, height: 400});

// therefore, when it tries to resize itself according to the `browserWindow` size
// there will be a `22`px diff that the `browserView` does not what to do with 🤷‍♂ 
view.setAutoResize({width: true, height: true});
view.webContents.loadURL('https://github.com');
```

**And my solution**:
Initialising the height of the `browserView` using the `BrowserWindow.getContentBounds` measurements fixes the problem for me. That said though, I have not tested this when there is no `minimum height and width` exists.

```JS
const window = new BrowserWindow({width: 400, height: 400});
const view = new BrowserView();
window.setBrowserView(view);

const windowContentBounds = window.getContentBounds();
view.setBounds({
  x: 0,
  y: 0,
  width: windowContentBounds.width,
  // this will return `400` - `22` on mac to accomodate the titlebar's frame.
  height: windowContentBounds.height 
});

// Mow the auto resize will hopefully work as intended 🎉 
view.setAutoResize({width: true, height: true});
view.webContents.loadURL('https://github.com');
```

**Comment by sofianguy** [comment] 2019-08-09 00:23
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 20:53
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 20:53 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS, version/1.7.x, version/1.8.x

**Comment by payitforwardnow** [comment] 2019-10-31 21:29
Issue is still present:
OSX 10.13.6
Node v12.13.0
Electron v7.0.0

**Comment by pushkin-** [comment] 2020-01-24 19:48
@sofianguy maybe you didn't get the other notifications, but this is still an issue

**Comment by sdnyco** [comment] 2020-03-17 15:50
Still an issue:

Electron  v8.1.1
OSX 10.15.3
Node v13.0.1

**Comment by lrondanini** [comment] 2020-04-29 05:43
Still a problem: 

Electron v8.2.3
OSX 10.15.3

Have you tried to set frame:false? it seems to solve the problem (of course this is not a solution, just an indication of where the problem may be)

**Comment by sdnyco** [comment] 2020-06-07 10:41
So I have been playing with this a litte further.

If you set the `BrowserView` height "manually" by passing the values on resize of the `BrowserWindow` it works expected. This is NOT a fix, but here is what I did:

`````
// Basic setup
const mainWindow = new BrowserWindow({ width: 100, height: 100 })
const mainView = new BrowserView()
mainWindow.addBrowserView(mainView)
mainView.setBounds({ x: 0, y: 0, width: 100, height: 100 })

mainView.setAutoResize({ width: true, height: false }) // very important to set height to false

// catch resize event emitted on window
mainWindow.on('resize', function() {

  // store window's new size in variable
  let newBounds = mainWindow.getBounds()

  // set BrowserView's bounds explicitly
  mainView.setBounds({ x: 0, y: 0, width: newBounds.width, height: newBounds.height })
})
`````

Again, this is not a fix. But it illustrates that setAutoResize seems to be broken in some cases.

**Comment by FrankenApps** [comment] 2022-07-18 09:50
This issue seems to be connected to the title bar. Therefore if you create a frameless parent window
```javascript
const mainWindow = new BrowserWindow({
    frame: false,
    height: 600,
    width: 800,
  });
``` 
it also works as expected. You need to roll your own custom title bar afterwards.

This is not a fix and the underlying issue still does not seem to be resolved on Eelectron v. 19.0.8.

**Comment by Akazm** [comment] 2022-12-27 21:16
Just a little tumbleweed passing through, nothing to see here

**Comment by courtsimas** [comment] 2024-04-16 04:38
Still an issue in electron 30
