### ISSUE TITLE
[Bug]: 在docker中运行electron,开启nodeIntegration: true,时，无法启动electron

### ISSUE THREAD

**Issue by 343058360** [electron/electron#37710] opened 2023-03-25 11:22 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Other Linux

### Operating System Version

node:14.17-alpine

### What arch are you using?

x64

### Expected Behavior

node:14.17-alpine

开启nodeIntegration: true,时，在docker中无法启动electron

webPreferences: {
      devTools: true,
      contextIsolation: false,
      nodeIntegration: true,
    },

Dockerfile

FROM node:14.17-alpine

WORKDIR /workspace
COPY . .

CMD npm run electron:serve
EXPOSE 80

### Actual Behavior

在docker中运行electron,开启nodeIntegration: true,时，无法启动electron

**Comment by so1ve** [comment] 2023-03-25 12:18
ENGLISH PLEASE，不是所有人都看得懂中文

### Preflight Checklist
* [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
* [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
* [x]  I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version
16.0.2

### What operating system are you using?
Other Linux

### Operating System Version
node:14.17-alpine

### What arch are you using?
x64

### Last Known Working Electron version
_No response_

### Expected Behavior
It should startup

node:14.17-alpine

webPreferences: { devTools: true, contextIsolation: false, nodeIntegration: true, },

Dockerfile

FROM node:14.17-alpine

WORKDIR /workspace COPY . .

CMD npm run electron:serve EXPOSE 80

### Actual Behavior
Cannot startup electron when running electron with nodeIntegration: true

### Testcase Gist URL
_No response_

### Additional Information
_No response_

**Comment by ckerr** [comment] 2023-03-27 14:26
Duplicate of #37712

**Closed by ckerr** 2023-03-27 14:26 UTC
Labels: bug :beetle:, duplicate
