### ISSUE TITLE
Since 1.6, on MacOS, "inset-hidden" window buttons appear as "hidden"

### ISSUE THREAD

**Issue by erusev** [electron/electron#8629] opened 2017-02-08 12:02 UTC
* Electron version: 1.6
* Operating system: 10.11

### Expected behavior

![image](https://cloud.githubusercontent.com/assets/184170/22736528/35f96038-ee07-11e6-8a72-eecd29f114db.png)

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/184170/22736530/3b42f734-ee07-11e6-9794-fc381f07e801.png)

**Comment by MarshallOfSound** [comment] 2017-02-08 12:44
Hey @erusev 

This appears to be a duplicate of the resolved issue #8610 👍

**Closed by MarshallOfSound** 2017-02-08 12:44 UTC
