### ISSUE TITLE
setting appData and app name does not recompute userData

### ISSUE THREAD

**Issue by bughit** [electron/electron#22899] opened 2020-03-30 22:04 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v9.0.0-beta.12 x86
* **Operating System:**
  * win7 sp1 x64

### Expected Behavior

userData to be recomputed from the overridden appData and app name

### Actual Behavior
userData stays the same

### To Reproduce
create the following app as index.js in a folder and run it via the folder

```js
'use strict';

const {app, BrowserWindow} = require('electron'),
      Path = require('path');

let win;

console.log('default appData: %s', app.getPath('appData'));
console.log('default app name: %s', app.getName());
console.log('default userData: %s', app.getPath('userData'));

const appName = Path.basename(__dirname);
app.setName(appName);
console.log('overridden app name: %s', app.getName());

app.setPath('appData', __dirname);
console.log('overridden appData: %s', app.getPath('appData'));

console.log('new userData: %s', app.getPath('userData'));


app.once('ready', async () => {

  win = new BrowserWindow();

});
```

For bugs that can be encapsulated in a small experiment, you can use Electron Fiddle (https://github.com/electron/fiddle) to publish your example to a GitHub Gist and link it your bug report.
-->

**Comment by codebytere** [comment] 2020-03-31 03:36
We feel that this behavior is working as intended.

Those paths are effectively a key-value map with calculated defaults;  the default of B depending on A doesn't necessarily mean that updating A should update B, and making it do so would be more unintuitive than doing so. Additionally, many apps depend on userData path determination , so changing it would reverberate through the ecosystem and break many apps. From a usage perspective, it's very easy to reason that if you want the userData path to change, you have to set it.  It's much harder to reason that if you don't want it to change, you have to set it back to its original value.

As such, we are going to close this issue.

**Closed by codebytere** 2020-03-31 03:36 UTC

**Comment by bughit** [comment] 2020-03-31 05:28
@codebytere 

> doesn't necessarily mean that updating A should update B.

I would argue the when you are in the init phase, before app ready, it should mean that.

Since userData is documented as `${appData}/${appName}`, if it's not set explicitly, it should be lazily computed. That's the logical, least-surprise behavior.

**Comment by nornagon** [comment] 2020-03-31 16:08
@bughit I don't think we document that userData is computed from appData and appName anywhere? Would be happy to update the docs if there's anything misleading though.

**Comment by bughit** [comment] 2020-03-31 16:30
The docs say this:

"userData The directory for storing your app's configuration files, which by default it is the appData directory appended with your app's name."
https://www.electronjs.org/docs/api/app#appgetpathname

To me that says that if you don't set it explicitly it will be computed (note the term append) from appData and appName, which definitely implies that if you override appData and appName early, in the init phase, before userData is actually used, your values will affect it. That is the point after all, of changing these paths, to affect things that depend on them.
