### ISSUE TITLE
[Bug]: double click drag area (-webkit-app-region: drag), browser window not maximize.

### ISSUE THREAD

**Issue by En777** [electron/electron#33845] opened 2022-04-20 06:08 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.3

### What operating system are you using?

Windows

### Operating System Version

windows 10.0.19042.1526

### What arch are you using?

ia32

### Last Known Working Electron version

12.0.2

### Expected Behavior

double click drag area (webkit-app-region: drag), browser window will maximize.
it's working on electron v12.0.2.
not working on electron v12.0.3.

### Actual Behavior

double click drag area (webkit-app-region: drag), browser window size not change.

### Testcase Gist URL

https://gist.github.com/Zomono/abe80b19d76607182bbef111dd325846

### Additional Information

double click drag area (webkit-app-region: drag), browser window will maximize.
it's working on electron v12.0.2, v12.0.0.
not working on electron v12.0.3, v12.2.3, and I test more: 12.1.0/12.0.15/12.0.9/12.0.5/12.0.3 also not working.

same problem:
https://github.com/electron/electron/issues/32502
`frame: false,
transparent: true,
maximizable: true
`

**Comment by En777** [comment] 2022-04-20 06:13
The bug has been introduced since electron v12.0.3

**Comment by pushkin-** [comment] 2022-04-20 14:48
there is already an issue for this. This one can be closed

**Comment by mlaurencin** [comment] 2022-04-20 20:49
Thanks for taking the time to contribute!

As mentioned, since this is a duplicate of https://github.com/electron/electron/issues/32502, I will be closing this issue. You may want to subscribe to the other issue for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by mlaurencin** 2022-04-20 20:49 UTC
Labels: bug :beetle:
