### ISSUE TITLE
Doesn

### ISSUE THREAD

**Issue by soichih** [electron/electron#5551] opened 2016-05-16 15:30 UTC
If I git clone the quick start tutorial and npm install, it pulls in electron-prebuilt@1.1.0 which doesn't work with the latest default installation of Windows 10.

If I downgrade to 1.0.1, things starts working.
```
npm install electron-prebuilt@1.0.1 -g
electron app
```

**Comment by mnquintana** [comment] 2016-05-16 17:37
Do you get any errors with 1.1.0? If so, can you post them here? Thanks!

**Comment by fbereche** [comment] 2016-05-16 22:16
I had the same problem. Actually I tried to install electron-prebuilt but any command just doesn't seem to output anything. I just run:

`npm install -g electron-prebuilt`

I tried several commands on my project folder:

`electron .`
`electron`
`electron -v`

But it just starts a new command line and it doesn't seem to be doing anything at all. I'm on Windows 7 by the way.

**Comment by casaval** [comment] 2016-05-16 23:43
This is the error I get:
```
$ ./node_modules/.bin/electron main.js
C:/Program Files/nodejs/node.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

```

Downgrading to 1.0.1 works

**Comment by zcbenz** [comment] 2016-05-17 00:19
This is a duplicate of #5528 and fix will be included in next release.

**Closed by zcbenz** 2016-05-17 00:19 UTC
Labels: more-information-needed
