### ISSUE TITLE
[Feature Request]: How to get localStorage from session ?

### ISSUE THREAD

**Issue by zilchhu** [electron/electron#30283] opened 2021-07-27 02:38 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

the only way to get localstorage is to invoke executeJavascript() in webContent , this is not useful to get localstorage from partitions which are lot.  

### Proposed Solution

add localStorage property to session like cookie.

### Alternatives Considered

add fromPartition() method to webConetent.

### Additional Information

is there anyway to export localstorage data from persist partition webview

**Comment by MarshallOfSound** [comment] 2021-07-27 02:47
Please do not raise duplicate issues

Duplicate of #30282

**Closed by MarshallOfSound** 2021-07-27 02:47 UTC
Labels: enhancement :sparkles:
