### ISSUE TITLE
"certificate-error" app event should emit when "net" requests fail

### ISSUE THREAD

**Issue by fasterthanlime** [electron/electron#8074] opened 2016-11-24 16:17 UTC
* Electron version: 1.4.8
* Operating system: macOS 10.12.1

Debugging proxies generate their own certificates to be able to do SSL Proxying — you can usually either install them OS-wide (bad idea), ignore certificate errors (still a bad idea), or just tell the app you're testing to trust it (by installing it — which electron has support for).

In my case, I'd just like to detect whenever a certificate error happens so I can deal with it. I see the `app` module has a `certificate-error` event, which is all I ever dreamt of and more, but it doesn't seem to be emit when doing `net` requests.

### Expected behavior

Setting an (SSL-proxying) proxy (either explicitly via `session.defaultSession.setProxy` then waiting for callback, or implicitly via OS settings (which are correctly detected)), then emitting a request similar to this one:

```typescript
import {net} from "electron";

const req = net.request({
  method: "get",
  url: "https://itch.io"
});
// subscribe to various req events here
req.end();
```

should emit the app event `certificate-error`.

### Actual behavior

The `certificate-error` event is not actually emitted when `net` requests are made. Setting a BrowserWindow's `window.location` to any https address does emit it as expected.

Furthermore, no events (no `error`, no `abort`, no `close`) are emitted on the ClientRequest itself. Which is probably expected, since it's all waiting for the `certificate-error` event callback to be called with either true or false — and decide whether the request error'd or can continue (because the certificate was trusted).

*~~edit: a net::ERR_PROXY_CONNECTION_FAILED error is thrown, see [this comment](https://github.com/electron/electron/issues/8074#issuecomment-262814677)~~*

*edit 2: the ERR_PROXY_CONNECTION_FAILED is only thrown when the proxy isn't running (Charles stops running after 30min, so, false alarm)*

### How to reproduce

~~It shouldn't be hard to reproduce — the hairy part is you need a proxy server somewhere: I've reproduced with Charles for macOS, with Fiddler for Windows, it just looks like an oversight when implementing the net API.~~

~~I can try coming up with a minimal repo that shows off the issue!~~

See [this comment](https://github.com/electron/electron/issues/8074#issuecomment-262817460) for a repo and instructions.

**Comment by fasterthanlime** [comment] 2016-11-24 16:40
After investigation via my repro repo here: https://github.com/fasterthanlime/electron-certificate-error — there's an exception thrown in the app process, which I guess could be the basis for a good workaround in the meantime:

![screen shot 2016-11-24 at 17 39 07](https://cloud.githubusercontent.com/assets/7998310/20605715/10a292c6-b26d-11e6-9cfb-e90f5462f8fc.png)

**Comment by fasterthanlime** [comment] 2016-11-24 16:56
I improved the reproduction code:

  * https://github.com/fasterthanlime/electron-certificate-error

It shows how proxy-less requests work, proxy-full requests don't emit anything, and BrowserWindow requests emit `certificate-error` as expected:

![screen shot 2016-11-24 at 17 55 31](https://cloud.githubusercontent.com/assets/7998310/20606124/48e4e308-b26f-11e6-8f76-8859b35f7529.png)

**Comment by arantes555** [comment] 2017-03-20 15:42
Any news on this?

Plus, I do not think this should be classified as an "enhancement". It prevents from even knowing something wrong has happened: it's definitely a bug.

**Comment by zcbenz** [comment] 2017-05-31 08:19
Electron is just reporting the events received from Chromium, this behavior is more likely a problem of Chromium, and I'm not sure if we can work around it in Electron.

**Comment by dlmanning** [comment] 2017-08-02 18:52
FYI: `webRequest` does seem to call `.onErrorOccured` when the cert is invalid, though one cannot specifically that that was the reason:

```javascript
session.fromPartition('yolo').webRequest.onErrorOccured({}, details => {
  console.log(details)
})

net.request({
  url: 'https://bobsdomain.biz',
  session: session.fromPartition('yolo')
}).end()
```

gives something like:
```
{ 
  error: 'net::ERR_ABORTED',
  fromCache: false,
  id: 1,
  method: 'GET',
  referrer: '',
  resourceType: 'other',
  timestamp: 1501699505906.511,
  url: 'https://bobsdomain.biz'
}
```

`net::ERR_ABORTED` is better than nothing, I suppose.

**Comment by tejohnso** [comment] 2017-08-06 16:00
Note that this problem will appear on any Linux system with outdated 128bit ca-certificates because Chromium no longer accepts 128bit certs.

It is still happening in `1.7.5` and it is definitely happening within Chromium as [previously mentioned](https://github.com/electron/electron/issues/8074#issuecomment-305119883)

It can be replicated without a proxy by disabling the certificate authority. For example, if ![GeoTrust Global CA](https://user-images.githubusercontent.com/1511535/29004775-765952fc-7a9b-11e7-8be6-3a4fd32d521e.png) is disabled, browsing to www.google.com will show a security error.

At that point, a simple `net.request` to www.google.com will not emit any event, nor will the app *certificate-error* event fire.  The request is silently abandoned. The only way to handle the situation is to include a timeout on the request, which leaves no indication of what the problem was.

**Comment by p120ph37** [comment] 2019-02-12 22:52
You can reproduce this even more simply by using `https://self-signed.badssl.com`.  A `net` request in the main thread against that domain will result in a silent stall with no reported error or response, and no `app.certificate-error` event thrown.

**Comment by electronart** [comment] 2020-02-05 11:27
Any updates on this? Is there an alternate way to make a request that will detect invalid certificate correctly?

**Comment by nornagon** [comment] 2020-02-05 18:48
Here's a fiddle that reproduces the issue: https://gist.github.com/2736447e54e2d074c372bb200ebfc493

**Comment by nornagon** [comment] 2020-02-05 18:51
Assuming you want to bypass SSL errors, here's an example of a workaround using `ses.setCertificateVerifyProc`: https://gist.github.com/7e0c6d1133dbeaae9eebbbbb37f6d46e

**Comment by pimterry** [comment] 2020-06-16 17:20
@nornagon thanks so much for the above! Great workaround. In my case I want to trust my cert everywhere, so the default session is better than explicitly creating a separate one. For that case, this is fixed with just:

```js
app.on('ready', () => {
  electron.session.defaultSession.setCertificateVerifyProc(
    (req, callback) => {
      if (certIsTrusted(req)) {
        callback(0); // All good
      } else {
        callback(-3); // Fallback to Chromium's result
      }
    }
  )
});
```

Running that at the start of my app seems to let me trust any certificate I like for electron.net requests.

Would absolutely be preferable to have this handled by certificate-error instead, but this is a reasonable workaround in the meantime.

**Comment by electron-triage** [comment] 2021-03-10 21:09
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Closed by electron-triage** 2021-03-10 21:09 UTC
Labels: 7-1-x, 8-x-y, bug :beetle:, component/net
