### ISSUE TITLE
Audio get wrong duration in Chrome 53

### ISSUE THREAD

**Issue by Murriouz** [electron/electron#7667] opened 2016-10-19 05:17 UTC
* Electron version: 1.4.3
* Operating system: macOS 10.12

```<audio>``` gets wrong mp3 duration in Chrome 53, and Chrome 54 seems like have fixed this issue.

So update to chromium 54 may fix this.

**Comment by MarshallOfSound** [comment] 2016-10-19 05:57
You can track the update to Chromium 54 here https://github.com/electron/electron/projects/2

If the issue is fixed in Chrome 54 then the fix should be pulled in during that upgrade.

**Closed by MarshallOfSound** 2016-10-19 05:57 UTC
Labels: fixed-in-upstream
