### ISSUE TITLE
createCipheriv crash renderer window

### ISSUE THREAD

**Issue by githoniel** [electron/electron#16214] opened 2018-12-29 07:29 UTC
### Version Info
electron: 4.0.0
OS: Windows 10   x64 10.0.17134.472

### Expected Behavior 
```js
require('crypto').createCipheriv('rc4', 'asdasd', null)
require('crypto').createCipheriv('rc4', 'asdasd', '')
```
 work well as  node v10.15.0 

### Actual behavior
```js
require('crypto').createCipheriv('rc4', 'asdasd', null)
```
cause renderer process crash 
```js
require('crypto').createCipheriv('rc4', 'asdasd', '')
```
throw 
```
Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119)
    at new Cipheriv (internal/crypto/cipher.js:225)
    at Object.createCipheriv (crypto.js:105)
    at <anonymous>:1:19
createCipherBase @ internal/crypto/cipher.js:79
createCipherWithIV @ internal/crypto/cipher.js:119
Cipheriv @ internal/crypto/cipher.js:225
createCipheriv @ crypto.js:105
```
### To Reproduce

exec code above in devTools

**Comment by shiftkey** [comment] 2018-12-29 12:34
Likely the same root cause as #16195

**Comment by orangeChu** [comment] 2018-12-30 15:13
Before it is repaired, you may be able to use the method of the main process.:)

**Comment by nornagon** [comment] 2019-01-02 18:49
Duplicate of #16195

**Closed by nornagon** 2019-01-02 18:49 UTC
Labels: 4-0-x, bug :beetle:, platform/windows
