### ISSUE TITLE
[Bug]: WebView crashes on initialization

### ISSUE THREAD

**Issue by adlk** [electron/electron#32129] opened 2021-12-08 09:26 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

15.3.3, 14.2.2

### Expected Behavior

When having one or multiple WebViews with the `src` prop the app should not crash (obviously)

### Actual Behavior

When having one or multiple WebViews with the `src` prop, the app is crashing with this message for each WebView:

```
[3720:1208/095924.304776:ERROR:child_thread_impl.cc(231)] Invalid PlatformChannel receive right
```

An app crash does not happen every time the WebView is initialized but when reloading the app once or more the app will crash at one point.

### Testcase Gist URL

https://gist.github.com/2ca7642de34e48dc1a27e644fa2577a2

### Additional Information

I've tested to initialize a WebView without a `src` parameter, this does not crash the WebView. Loading the src via `webview.loadURL()` later on however has a high chance of crashing the app.

The Electron Fiddle Demo is using `src="data:text/plain,Hello, world!"` for simplicity. The same behavior is happening with every src prop though.

**Comment by boristian** [comment] 2022-01-24 13:40
I have the same problem on macOS 10.14.6. I have also tried the Gist with electron-fiddle, it also breaks.

**Comment by nornagon** [comment] 2022-01-24 17:56
I can reproduce this. Here's a trace (from current main):

```
[56948:0124/093858.958308:FATAL:web_view_guest_delegate.cc(39)] Check failed: embedder_web_contents_ == content::WebContents::FromRenderFrameHost(embedder_frame) (0x7f87c8044800 vs. 0x0)
0   Electron Framework                  0x000000012a7016e9 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x000000012a627403 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework                  0x000000012a64163f logging::LogMessage::~LogMessage() + 175
3   Electron Framework                  0x000000012a64260e logging::LogMessage::~LogMessage() + 14
4   Electron Framework                  0x0000000126225b9e electron::WebViewGuestDelegate::AttachToIframe(content::WebContents*, int) + 206
5   Electron Framework                  0x000000012616d7cf gin_helper::Invoker<gin_helper::IndicesHolder<0ul, 1ul, 2ul>, electron::api::WebContents*, content::WebContents*, int>::DispatchToCallback(base::RepeatingCallback<void (electron::api::WebContents*, content::WebContents*, int)>) + 143
6   Electron Framework                  0x000000012616d638 gin_helper::Dispatcher<void (electron::api::WebContents*, content::WebContents*, int)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 344
7   Electron Framework                  0x0000000127a1d7eb v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 811
8   Electron Framework                  0x0000000127a1b794 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 1748
9   Electron Framework                  0x0000000127a193f3 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 483
10  Electron Framework                  0x0000000127a18f7d v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) + 109
11  ???                                 0x0000001807edeab8 0x0 + 103212247736
```

and a dump from 16.0.7:

[e551e0d0-5eea-4eca-ba9e-ddce5c83bf15.dmp.zip](https://github.com/electron/electron/files/7927696/e551e0d0-5eea-4eca-ba9e-ddce5c83bf15.dmp.zip)

In debug builds, this is the DCHECK that's failing: https://github.com/electron/electron/blob/2fe5d0e1e83a94d647b87a4ae803f738e54402e1/shell/browser/web_view_guest_delegate.cc#L38-L39

and in release builds, since the DCHECK is compiled out, the app plows on to https://github.com/electron/electron/blob/2fe5d0e1e83a94d647b87a4ae803f738e54402e1/shell/browser/web_view_guest_delegate.cc#L50-L52

which results in a segfault.

**Comment by nornagon** [comment] 2022-01-24 19:27
Bisected to https://github.com/electron/electron/compare/v16.0.0-nightly.20210802...v16.0.0-nightly.20210803, which implicates https://github.com/electron/electron/pull/24344 cc @deepak1556

**Comment by MikeBoht** [comment] 2022-01-25 16:54
Same issue, observed on macOS 12.1.

Also noticed that deleting the application specific folder in `~/Library/Application Support/` avoids the crash the next time the app starts up from local, but the app will still crash on subsequent starts after that.

Tried different versions to see where it started, with these results:
  - 16.0.7 --> PlatformChannel error
  - 16.0.6 --> PlatformChannel error
  - 16.0.0 --> PlatformChannel error
  - 15.3.5 --> PlatformChannel error
  - 15.3.3 --> PlatformChannel error (@adlk mentioned this version worked for him)
  - 15.0.0 --> PlatformChannel error
  - 14.2.4 --> Works!

**Comment by MikeBoht** [comment] 2022-01-26 16:30
Here is a crash dump as well, hopefully it helps.
[platformchannel_error_crash_dump.txt](https://github.com/electron/electron/files/7943373/platformchannel_error_crash_dump.txt)
.

**Comment by MikeBoht** [comment] 2022-06-07 05:29
No longer seeing this issue, when upgrading to 18.3.0!

**Comment by codebytere** [comment] 2022-07-27 14:26
Closing this out as resolved - please ping if it crops up again and i'll reopen!

**Closed by codebytere** 2022-07-27 14:26 UTC
Labels: component/webview, bug :beetle:, platform/all, 16-x-y, 17-x-y
