### ISSUE TITLE
FATAL ERROR opening files on macOS High Sierra

### ISSUE THREAD

**Issue by quinton-ashley** [electron/electron#12493] opened 2018-03-31 23:18 UTC
* Electron version: 1.8.4
* Operating system: macOS  1.13.3

### Expected behavior

A file should be opened.

### Actual behavior

The system dialog box shows up but as soon as a file is selected an error occurs which seems to soft lock the program.

### How to reproduce

Try to open a file.

```javascript
dialog.showOpenDialog({
	properties: ['openFile', 'openDirectory', 'multiSelections']
});
```
```
npm start

> qodemate@0.0.14 start /Users/qashto/Documents/dev/apps/qodemate
> electron .

Pug interceptor registered successfully
objc[16203]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffaccb8b68) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1218a1cd8). One of the two will be used. Which one is undefined.
```

**Comment by codebytere** [comment] 2018-04-01 03:51
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently, as here it's somewhat unclear what the issue is or what your desired behavior was. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by quinton-ashley** [comment] 2018-04-01 04:19
It's pretty straight forward but sure I'll comply with the template format.

**Comment by MarshallOfSound** [comment] 2018-04-01 04:27
@quinton-ashley That line is not an error, simply an OS warning due to some other things you will have installed on your system.  See here: https://github.com/jarvisteach/appJar/issues/285 for an issue with the same log message from a completely different framework.

Can you explain in more detail what you mean by "soft lock" the program.

**Comment by quinton-ashley** [comment] 2018-04-01 23:51
I don't have that program on my computer.  A soft lock is when a program doesn't crash and close but crashes and prevents further user interaction.  I can't even reload electron without quitting.

**Comment by sethlu** [comment] 2018-04-05 07:02
Found this too: https://stackoverflow.com/questions/46999695/class-fifindersyncextensionhost-is-implemented-in-both-warning-in-xcode-si

**Comment by quinton-ashley** [comment] 2018-04-14 23:26
That answer says it not a problem but it is for me, unless I'm not using the open command correctly.  The project does not log the path of the file or folder I choose, instead I get that error and then if I try to open something else the system dialog pops up and I can choose a file but the app won't respond.
```javascript
{
			label: 'File',
			submenu: [{
				label: 'Open',
				click() {
					let proj = dialog.showOpenDialog({
						properties: ['openFile', 'openDirectory']
					});
					log(proj);
					ent.open(proj);
				}
			}]
		}
```

**Comment by quinton-ashley** [comment] 2018-04-14 23:38
This is kind of disheartening because I just started using electron and I really like it but I won't be able to use it anymore if users can't open files or folders with my app.   If this is an Apple issue do you all think they will fix this issue soon or should I stop using electron and go back to running a local server for my app?

**Comment by codebytere** [comment] 2018-04-14 23:51
@quinton-ashley do you think you could provide a minimum testcase for this? something i could run that would produce this issue for me locally?

**Comment by sethlu** [comment] 2018-04-14 23:52
@quinton-ashley Can you provide a screen capture for this scenario?
I'm not sure what "soft lock" appears to be like from your end?

**Comment by quinton-ashley** [comment] 2018-04-16 03:55
My screenshot would just contain the error log I already sent so that wouldn't be helpful.  I'm literally just running the template from the dialog example.  I commented out the app specific code I'm using.   This is my render.js file:
```javascript
module.exports = function () {
	const {
		app,
		dialog,
		Menu
	} = require('electron').remote;
	// const fs = require('fs-extra'); // open source library adds functionality to standard node.js fs
	// const md = require('markdown-it')();
	const path = require('path');
	// const $ = require('jquery');

	// window.$ = window.jQuery = $;
	// window.Tether = require('tether');
	// window.Bootstrap = require('bootstrap');

	const __homeDir = require('os').homedir();
	const log = console.log;

	// const Presenter = require('./presenter.js');
	// let ent = new Presenter();

	const template = [
		{
			label: 'File',
			submenu: [{
				label: 'Open',
				click() {
				let proj = dialog.showOpenDialog({
					properties: ['openFile', 'openDirectory']
				});
				log(proj);
				ent.open(proj);
				}
			}]
		},
		{
			label: 'Edit',
			submenu: [
				{
					role: 'undo'
				},
				{
					role: 'redo'
				},
				{
					type: 'separator'
				},
				{
					role: 'cut'
				},
				{
					role: 'copy'
				},
				{
					role: 'paste'
				},
				{
					role: 'pasteandmatchstyle'
				},
				{
					role: 'delete'
				},
				{
					role: 'selectall'
				}
    ]
  },
		{
			label: 'View',
			submenu: [
				{
					role: 'reload'
				},
				{
					role: 'forcereload'
				},
				{
					role: 'toggledevtools'
				},
				{
					type: 'separator'
				},
				{
					role: 'resetzoom'
				},
				{
					role: 'zoomin'
				},
				{
					role: 'zoomout'
				},
				{
					type: 'separator'
				},
				{
					role: 'togglefullscreen'
				}
    ]
  },
		{
			role: 'window',
			submenu: [
				{
					role: 'minimize'
				},
				{
					role: 'close'
				}
    ]
  },
		{
			role: 'help',
			submenu: [
				{
					label: 'Learn More',
					click() {
						require('electron').shell.openExternal('https://electronjs.org')
					}
      }
    ]
  }
]

	if (process.platform === 'darwin') {
		template.unshift({
			label: app.getName(),
			submenu: [
				{
					role: 'about'
				},
				{
					type: 'separator'
				},
				{
					role: 'services',
					submenu: []
				},
				{
					type: 'separator'
				},
				{
					role: 'hide'
				},
				{
					role: 'hideothers'
				},
				{
					role: 'unhide'
				},
				{
					type: 'separator'
				},
				{
					role: 'quit'
				}
    ]
		})

		// Edit menu
		template[1].submenu.push({
			type: 'separator'
		}, {
			label: 'Speech',
			submenu: [
				{
					role: 'startspeaking'
				},
				{
					role: 'stopspeaking'
				}
      ]
		})

		// Window menu
		template[3].submenu = [
			{
				role: 'close'
			},
			{
				role: 'minimize'
			},
			{
				role: 'zoom'
			},
			{
				type: 'separator'
			},
			{
				role: 'front'
			}
  ]
	}

	const menu = Menu.buildFromTemplate(template);
	Menu.setApplicationMenu(menu);

	// $('#close').click(ent.close);
	// $('#next').click(ent.next);
	// $('#play').click(ent.play);
	// $('#reset').click(ent.reset);

};

```

**Comment by codebytere** [comment] 2018-04-16 12:56
Awesome! Glad it's solved 😁 

Feel free to @ me if something else come up; i'm going to go ahead and close this for now

**Closed by codebytere** 2018-04-16 12:56 UTC
Labels: bug :beetle:, platform/macOS, version/1.8.x
