### ISSUE TITLE
setContentSize seems to have no effect on windows.

### ISSUE THREAD

**Issue by kunkinkan** [electron/electron#6241] opened 2016-06-25 22:24 UTC
Works on Mac, but not on windows;

`      electron.remote.getCurrentWindow().setContentSize(600, parseInt(document.documentElement.scrollHeight, 10), false);
`

(No error, just no change).

**Comment by zcbenz** [comment] 2016-06-26 03:04
Can you provide a minimal app that can reproduce this problem? I'm unable to reproduce with your code.

**Comment by zcbenz** [comment] 2016-07-20 11:10
Closing until more information is provided.

**Closed by zcbenz** 2016-07-20 11:10 UTC
Labels: more-information-needed
