### ISSUE TITLE
chrome://webrtc-internals stopped working since Chromium 80 was introduced (v8.0.0-beta.3)

### ISSUE THREAD

**Issue by kubaau** [electron/electron#22375] opened 2020-02-25 13:28 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.0-beta.3 and later (including v8.0.1)
* **Operating System:**
  * OS-independent (tested on macOS 10.15.3 / Windows 10 (1909)) 
* **Last Known Working Electron version:**
  * v8.0.0-beta.2

### Expected Behavior

Should be able to open chrome://webrtc-internals under Electron.

### Actual Behavior

Blank page is displayed.
Console error says: "Not allowed to load local resource: chrome://webrtc-internals/" and "No resource with given URL found"

### To Reproduce
Simply open chrome://webrtc-internals in some BrowserWindow under Electron, e.g.:
https://gist.github.com/kubaau/20accd9a83080d9e0a402b9c1c469825

### Additional Information

Many other chrome:// pages have stopped working as well, e.g. chrome://about.

**Comment by codebytere** [comment] 2020-02-26 03:57
Duplicate of https://github.com/electron/electron/issues/22120

**Closed by codebytere** 2020-02-26 03:57 UTC
