### ISSUE TITLE
electron 10.1.0 minimize and maximize does not work

### ISSUE THREAD

**Issue by IncinerateZ** [electron/electron#25207] opened 2020-08-31 05:13 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  
10.1.0
* **Operating System:**
  *  
Windows 10 (19041)
* **Last Known Working Electron version:**
  *  
N/A

### Expected Behavior
 
minimize() and maximize() to minimize and maximize the window respectively.

### Actual Behavior
 
nothing changed/happened.

### To Reproduce
 
remote.BrowserWindow.getFocusedWindow().minimize()

 
https://gist.github.com/IncinerateZ/9aae814bf6d3e97c474be6629d9400e3

copy paste gist files to electron fiddle.

### Additional Information

strangely enough, close() does work.

**Comment by codebytere** [comment] 2020-09-02 23:44
Duplicate of https://github.com/electron/electron/issues/24759

**Closed by codebytere** 2020-09-02 23:44 UTC
Labels: 10-x-y, bug :beetle:, platform/windows
