### ISSUE TITLE
Console.assert errors for CSSModel.js when starting electron app

### ISSUE THREAD

**Issue by ari62** [electron/electron#27005] opened 2020-12-14 22:02 UTC
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

***Node version:**
node v14.4.0 (npm v6.14.5)
***Electron Version:**
v8.5.2
***Operating System:**
MacOS High Sierra 10.13.6

### Expected Behavior
No errors in terminal.
### Actual Behavior

I get this when my app starts. Any ideas? I start my app using "npm run electron:start" from the terminal.

`[65359:1214/165019.518828:ERROR:CONSOLE(63)] "console.assert", source: devtools://devtools/bundled/sdk/CSSModel.js (63)
[65359:1214/165019.518982:ERROR:CONSOLE(63)] "console.assert", source: devtools://devtools/bundled/sdk/CSSModel.js (63)
[65359:1214/165019.519196:ERROR:CONSOLE(63)] "console.assert", source: devtools://devtools/bundled/sdk/CSSModel.js (63)
[65359:1214/165019.519358:ERROR:CONSOLE(63)] "console.assert", source: devtools://devtools/bundled/sdk/CSSModel.js (63)
[65359:1214/165019.519614:ERROR:CONSOLE(63)] "console.assert", source: devtools://devtools/bundled/sdk/CSSModel.js (63)
[65359:1214/165019.519694:ERROR:CONSOLE(63)] "console.assert", source: devtools://devtools/bundled/sdk/CSSModel.js (63)
[65359:1214/165019.519863:ERROR:CONSOLE(63)] "console.assert", source: devtools://devtools/bundled/sdk/CSSModel.js (63)`

### Screenshots
<img width="962" alt="Screen Shot 2020-12-14 at 4 55 01 PM" src="https://user-images.githubusercontent.com/8607924/102140488-44950780-3e2d-11eb-9fae-a77308cf07a8.png">

**Comment by ckerr** [comment] 2020-12-16 19:22
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by ckerr** [comment] 2020-12-16 19:25
...oh, I see also that this was Electron 8. FWIW, Electron 8 has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions). You may want to test your application against a newer version of Electron and see if the problem persists.

**Comment by sofianguy** [comment] 2021-01-05 21:39
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2021-01-05 21:39 UTC
Labels: 8-x-y, blocked/need-repro, platform/macOS

**Comment by zaynekomichi** [comment] 2022-11-10 14:39
Definitely, a bug involved was facing the same issue, had to do with looping using the map function. The key/index is required on each item you return. Not sure if it applies to everyone but mainly looping objects. Hope that helps. And I'm sure you can check when the error pops up in the console that's the only way to see which code is causing this.

**Comment by zaynekomichi** [comment] 2022-11-10 14:59
Tried reproducing, app won't start, using linux. Just get a blank electron screen
