### ISSUE TITLE
BrowserWindow width is not correct

### ISSUE THREAD

**Issue by UAVova** [electron/electron#6364] opened 2016-07-06 12:18 UTC
* Electron version: 1.2.5
* Operating system: Windows 10

`let win = new BrowserWindow({height: 600, width: 680})`
As a result of `win.show()` i get BrowserWindow with 664px width(-16 px of actual width value)

**Comment by zcbenz** [comment] 2016-07-06 12:39
This is a duplicate of #4045.

**Closed by zcbenz** 2016-07-06 12:39 UTC
