### ISSUE TITLE
'-webkit-app-region: drag' doesn't work on overlapped elements.

### ISSUE THREAD

**Issue by daltonmenezes** [electron/electron#7605] opened 2016-10-13 12:41 UTC
* Electron version: 1.4.3
* Operating system: Ubuntu 16.04

I have a frameless window with a title bar configured with `-webkit-app-region: drag`. It work's. But, if I set the webview with: 
```
width: 100%; 
height: 100%; 
position: fixed;
-webkit-app-region: no-drag;
``` 
and my title bar overlapping that with `position` and `z-index` seted, the drag feature doesn't work anymore. It's seems like the 'no-drag' from webview is conflicting with 'drag' from title bar, even it being overlapped. What can I do about that? Or it's a Chromium bug?

**Comment by zcbenz** [comment] 2016-10-24 03:23
The draggable region does not respect CSS position rules and `no-drag` takes precedence over `drag`, so I'm closing this since it is expected behavior.

For improving this behavior, I suggest bringing this up at [Chromium's issues list](https://crbug.com).

**Closed by zcbenz** 2016-10-24 03:23 UTC

**Comment by fabiospampinato** [comment] 2020-06-08 00:33
> The draggable region does not respect CSS position rules and no-drag takes precedence over drag, so I'm closing this since it is expected behavior.

How is this expected behavior though 🤔
