### ISSUE TITLE
[Bug]: os.machine() doesn't work in electron environment

### ISSUE THREAD

**Issue by CaveNightingale** [electron/electron#36334] opened 2022-11-14 14:02 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.2.3

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu jammy

### What arch are you using?

x64

### Expected Behavior

`require('os').machine()` returns `x86_64` on  my computer, same as what it does in plain nodejs environment.

### Actual Behavior

`require('os').machine()` is not a function and lead to erroring.

**Comment by codebytere** [comment] 2022-11-14 14:33
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by CaveNightingale** [comment] 2022-11-14 16:01
> Thanks for reporting this and helping to make Electron better!
> 
> Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

https://gist.github.com/CaveNightingale/2269cf32f7398945f12b9e1e58af753a
The bug is easy to reproduce. The test has only one line in `main.js`.

**Comment by codebytere** [comment] 2022-11-14 16:18
This is a new function in Node.js. It was added in `v18.9.0` and then backported to `v16.18.0`, neither of which Electron yet bundles. This will be resolved when we upgrade Node.js to a version containing those - v21 never will.

**Closed by codebytere** 2022-11-14 16:18 UTC
Labels: platform/linux, bug :beetle:, blocked/need-repro, 21-x-y
