### ISSUE TITLE
Running a cpu-intensive task on the main thread causes significant lags in browser window

### ISSUE THREAD

**Issue by arekkas** [electron/electron#9266] opened 2017-04-23 11:31 UTC
* Electron version: `^1.6.2`
* Operating system: OSX, Windows

### Expected behavior

CPU-intensive tasks running in the electron main thread should not have impact on BrowserWindow performance.

### Actual behavior

CPU-intensive tasks running in the electron main thread have a significant impact on performance of BrowserWindow.

### How to reproduce

Unfortunately, I don't have a very simple set up of reproducing this. But I can show you what it looks like in this gif. I delayed the load of the cpu intensive task for ~800ms after window load which is why the spinner runs smoothly at first and then starts lagging.

![lag-electorn](https://cloud.githubusercontent.com/assets/3372410/25313136/f465a940-2828-11e7-85cd-88e58c548ce9.gif)

The spinner itself is built using css animations, no javascript. I also tried SVG-based animations which had even worse lags.

Any ideas how to resolve this?

**Comment by Brain-Gamer** [comment] 2017-04-23 12:34
Isn't it possible to run the cpu intensive task as a child process? Maybe that would fix it

**Comment by arekkas** [comment] 2017-04-23 12:36
That could be a possibility, however I don't really know how well child processes run from within a asar production build.

**Comment by MarshallOfSound** [comment] 2017-04-24 07:54
@arekkas CPU intensive tasks should be offloaded to either workers in renderer processes or child processes from the main process.

> however I don't really know how well child processes run from within a asar production build.

Forking the main process works exactly as it would in a node process, just give it the path to a JS script to run 👍

**Comment by arekkas** [comment] 2017-04-24 08:08
Web workers don't have node integration, right? So in my case (running an express server) should be offloaded to a child process?

Thank you for your time replying to this.

**Comment by MarshallOfSound** [comment] 2017-04-24 08:54
@arekkas Web workers *can* have node integration in more recent builds of Electron.

See https://github.com/electron/electron/pull/8852

Not sure the express server itself should be in a different process, just the actual intensive code

**Comment by arekkas** [comment] 2017-04-27 09:11
Thanks, I'll play around with that. So just to clarify, there is currently no way of decoupling main process and browser window other than having a subprocess/webworker?

**Comment by MarshallOfSound** [comment] 2017-04-27 09:52
There is a lot of behind the scenes internal Electron communication between BrowserWindow's and the main process, this means if the main process is executing a blocking task that communication can't take place.

Currently the best way to handle this is to offload process intensive tasks to a subprocess somehow 👍

**Comment by zcbenz** [comment] 2017-06-20 07:40
Script runs in the UI thread of the main process, so any CPU-intensive task you do would heavily affect your app's behavior. In Chrome it is not allowed to run any heavy task in UI thread for performance, but in Electron you are given the permission to do anything you want.

Closing since it is expected behavior.

**Closed by zcbenz** 2017-06-20 07:40 UTC
