### ISSUE TITLE
[Bug]: Electron launches apps like firefox on X11/xwayland mode, even if they should run in native wayland

### ISSUE THREAD

**Issue by fabiscafe** [electron/electron#28793] opened 2021-04-23 07:32 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.
- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

### Electron Version

12.0.5

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

Other (specify below)

### Expected Behavior

Electron shouldn't change the default behavior of apps, launched by electron

### Actual Behavior

All electron apps will start additional 3rd party apps in xwayland mode. This results in a conflict for some of them. Like firefox, if firefox is already launched and you press a link in an electron app, firefox will respond with a message "Firefox is already running, but is not responding. To use Firefox, you must first close the existing Firefox process, restart your device, or use a different profile.", because firefox xwayland can not run inside a native wayland firefox.

### Additional Information

Steps to reproduce:
1. Be on a wayland session (with xwayland support, like GNOME; check with `echo $XDG_SESSION_TYPE`)
2. Launch firefox in wayland mode: `MOZ_ENABLE_WAYLAND=1 firefox` (could be default on your distro anyways, you can check after launch in _about:support_.)
3. make sure that firefox is your default browser.
3. Launch an Electron app
4. Click a link in this electron app

**Comment by vially** [comment] 2021-04-23 18:15
It's not entirely clear from the description, but I suppose the Electron app is run using XWayland, right (e.g.: without passing the `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags)?

If that's the case then this could be caused by #28436 and it might be worth trying to run the Electron app as native Wayland app to see if that makes any difference. Obviously this is *not* a solution because then you would have the opposite effect (apps run from Electron being forced to run as Wayland apps) but it should help confirm if it's the same underlying bug.

**Comment by fabiscafe** [comment] 2021-04-25 13:35
> I suppose the Electron app is run using XWayland,

Yes, without any additional command or any flag passed. 

> might be worth trying to run the Electron app as native Wayland app to see if that makes any difference.

If I launch it with `--enable-features=UseOzonePlatform --ozone-platform=wayland` it works, But will in that case enforce wayland on the launching apps

You are right with #28436 that one sounds exactly like my problem. So I guess my one is a duplicate.

**Comment by nornagon** [comment] 2021-04-27 19:30
Duplicate of #28436

**Closed by nornagon** 2021-04-27 19:30 UTC
Labels: bug :beetle:
