### ISSUE TITLE
The release file ffmpeg-v30.3.1-darwin-x64.zip is wrong

### ISSUE THREAD

**Issue by GazeboXu** [electron/electron#44313] opened 2024-10-18 12:56 UTC
the file url is: [https://github.com/electron/electron/releases/download/v30.3.1/ffmpeg-v30.3.1-darwin-x64.zip](https://github.com/electron/electron/releases/download/v30.3.1/ffmpeg-v30.3.1-darwin-x64.zip), as the name suggestion, it should be x86 arch, but if you unzip the file and use the command `lipo -info libffmpeg.dylib`, it shows that the arch is arm "Non-fat file: libffmpeg.dylib is architecture: arm64".

thanks!

**Comment by codebytere** [comment] 2024-10-31 11:32
@GazeboXu is this also true for [currently supported releases](https://www.electronjs.org/docs/latest/tutorial/electron-timelines)?

**Comment by jkleinsc** [comment] 2024-10-31 14:15
Closing as a duplicate of #43076.  @GazeboXu  this issue has been fixed for newer releases. Please upgrade to the latest 30-x-y version (https://github.com/electron/electron/releases/tag/v30.5.1) to resolve your issue.

**Closed by jkleinsc** 2024-10-31 14:15 UTC
Labels: blocked/need-info ❌

**Comment by GazeboXu** [comment] 2024-11-01 01:14
@codebytere , yes, the current release(31.7.3) is ok.

thanks
