### ISSUE TITLE
net.request response is missing content-type header in 304 responses

### ISSUE THREAD

**Issue by themadtitanmathos** [electron/electron#27895] opened 2021-02-24 16:57 UTC
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
10.1.7
* **Operating System:**
Windows 10 Enterprise 1909

When making a request with `net.request`, I can see that my response has a `content-type` header of `application/json; charset=utf-8` inside of my `webRequest.onHeadersReceived` handler:

```
electron.session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
  // details.responseHeaders['content-type'] === 'application/json; charset=utf-8'
});
```

But by the time the `net.request` `request.on('response')` handler receives the headers, the content-type is gone.

```
request.on('response', (response) => {
  /* 
  response.headers === {
    // no content-type
  };
  */
});
```

I haven't tested if this is an issue in all types of responses, but I can tell you this is occurring without fail for the case when the `response.statusCode === 200`, but the `response.headers.status === 304`.

### Expected Behavior
For `net.request` response handler to receive the content-type that clearly should exist on the response (proved by `webRequest.onHeadersReceived`).

### Actual Behavior
`net.request` response handler is receiving what seems to be a cached set of headers (or something?), which do not match what is seen in `webRequest.onHeadersReceived`.

**Comment by ckerr** [comment] 2021-02-24 20:22
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Mr-Wallet** [comment] 2021-03-03 15:00
Follow-up to this, `net` seems to be adding the `status` header on its own. We've mostly (but not exclusively) been testing against GitHub's REST API, and we've confirmed through Postman that the servers we've hit don't include the `status` header, but it consistently comes back `304` on many requests, even when we craft a brand-new requests and completely clear the site's data from Chrome to make sure there's nothing in the session that could trigger or populate a 304. So far it seems like we're getting back legitimate 200s and net is arbitrarily adding `status: 304` and deleting the `content-type` header (and removing custom headers,  #27894 which may be the same issue). When we force GitHub to give us a 304 by including an ETag in `If-None-Match`, `net.request` gives us back a completely normal-looking 304 with no body, which tends to rule out the idea that the "weird" response is Chromium poorly populating the response from cache.

**Comment by arantes555** [comment] 2021-03-11 13:56
I just hit the same problem : electron does not repopulate `content-type` and `content-length` when a 304 is "transformed" in 200 from the cache.

Also, I can confirm that the behaviour was different on electron <= 6 : up to electron6, the 200 seen in this case correctly has `content-type` and `content-length`.

**Comment by arantes555** [comment] 2021-03-11 15:38
Here is a standalone testcase : 

https://gist.github.com/arantes555/99f8976266d340bad42b2894cb50d7d5

This shows that when the server responds with a 200, `response` correctly contains `content-type` and `content-length`. But when the server responds with a 304, `response` is shown to be a 200 but does **not** contain  `content-type` and `content-length`.

I also showed the behaviour of `onHeadersReceived` that @themadtitanmathos noticed : on this callback, headers are correct. 

Also, with electron@6, everything is correct.

**Comment by Mr-Wallet** [comment] 2021-03-11 15:59
we never got to the point of setting up our own server to test, but testing against GitHub and GitLab APIs, we only got a repro _while we had something in the cache._ For whatever reason, when we manually set our own `If-None-Match` that would prompt a 304 from the server, we got back an unmolested 304 (i.e. 304 status code, no body). We came to the conclusion that it was because of a bad interaction with the Electron and/or Chrome request caches. I'm confident that if you cleared both caches and ran the 304 first, you would get back the `content-type` and `content-length` as expected. In other words, I believe it's some problematic way that the cache results are being "merged" into the final results that causes the headers to drop. The same mechanism is probably also preventing the `onHeadersReceived` callback from working (#27895) by overriding the results _after_ the callback occurs.

**Comment by nornagon** [comment] 2021-03-11 18:18
Thanks for the standalone repro @arantes555! With that I've been able to confirm that this also happens on macOS, and in 12.x and 13.x.

**Comment by nornagon** [comment] 2021-03-11 19:01
This looks like a regression caused by https://github.com/electron/electron/pull/21552. As an experiment, I tried adding the non-"raw" headers to the internal response object:

```diff
diff --git a/shell/browser/api/electron_api_url_loader.cc b/shell/browser/api/electron_api_url_loader.cc
index afe48e40c..6a836f7af 100644
--- a/shell/browser/api/electron_api_url_loader.cc
+++ b/shell/browser/api/electron_api_url_loader.cc
@@ -68,6 +68,22 @@ struct Converter<network::mojom::CredentialsMode> {
   }
 };  // namespace gin

+template <>
+struct Converter<net::HttpResponseHeaders> {
+  static v8::Local<v8::Value> ToV8(
+      v8::Isolate* isolate,
+      const net::HttpResponseHeaders& headers) {
+    gin_helper::Dictionary dict = gin::Dictionary::CreateEmpty(isolate);
+    size_t i = 0;
+    std::string name;
+    std::string value;
+    while (headers.EnumerateHeaderLines(&i, &name, &value)) {
+      dict.Set(name, value);
+    }
+    return dict.GetHandle();
+  }
+};
+
 }  // namespace gin

 namespace electron {
@@ -561,6 +577,8 @@ void SimpleURLLoaderWrapper::OnResponseStarted(
   DCHECK(response_head.raw_request_response_info);
   dict.Set("rawHeaders",
            response_head.raw_request_response_info->response_headers);
+  dict.Set("headers",
+           *response_head.headers);
   Emit("response-started", final_url, dict);
 }
 
```

The `headers` object contained the correct `content-type` and `content-length`, even when the `rawHeaders` didn't. For example:

![image](https://user-images.githubusercontent.com/172800/110839757-c5ab4180-8258-11eb-87c9-91d4e4800524.png)

As further confirmation, the above PR was backported to 7.x in v7.1.10. When I run the fiddle on v7.1.9, it works as expected.

cc @zcbenz

**Comment by zcbenz** [comment] 2021-03-12 00:44
Comparing the `response.headers` between 6 and 7, it seems that we should pass filtered headers instead of the raw headers to JS. So https://github.com/electron/electron/pull/21552 should be reverted, but we would then need a fix to https://github.com/electron/electron/issues/20631.

**Comment by Mr-Wallet** [comment] 2021-05-19 17:30
We're not exactly sure why (this was reported from end users), but in very rare cases it's clear that this is also happening on non-304 responses as well, and no extra `status` header is added in those cases.

Right now our solution is to play fast and loose with content-type and simply attempt to parse anything missing its content-type as a JSON and see if it works. Hopefully nobody responds with plain-text `null`/`true` while the content-type is being dropped 🤞

**Comment by arantes555** [comment] 2021-10-24 00:40
I can confirm this is still happening up to 16.0.0-beta.2 .

Also, here is a simplified test-case : https://gist.github.com/arantes555/4849273fe59b87313f0cb472ae65ae5b

**Comment by anderklander** [comment] 2022-05-11 13:56
This is still an issue in 18.2.2 (and 19.0.0-beta.5). Any news or plans to fix this?

**Comment by taras-dubyk** [comment] 2022-06-22 07:52
I have encountered the same issue while working with GitHub API.
`Content-type` header and some GitHub custom headers are missing if a response is returned from the cache.
Is there any workaround except disabling caching using the` 'Cache-Control': 'no-cache'` header?

**Comment by arantes555** [comment] 2022-10-06 09:37
bump

**Comment by RealAlphabet** [comment] 2022-11-03 00:19
Any news ?

**Comment by nornagon** [comment] 2022-11-03 19:12
Right, seems like the problem is that we're using `rawHeaders` instead of `headers` to fill the header list, but the content-type / content-length only come back in `headers`. Seems we might have to merge these somehow in order to fix this but preserve the fix for https://github.com/electron/electron/issues/20631.

**Closed** 2022-12-21 22:53 UTC
Labels: blocked/need-info ❌, bug :beetle:, component/net, platform/all, 10-x-y, 12-x-y, 13-x-y
