### ISSUE TITLE
'silent: true' for printing not working in version 12.0.6 and 13.1.9

### ISSUE THREAD

**Issue by CoWayger** [electron/electron#30539] opened 2021-08-16 09:58 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.9

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Last Known Working Electron version

11.0.5

### Expected Behavior

Prints the webpage

### Actual Behavior

Not printing, no error.

### Additional Information

I found issue tracker with same problem for version 5 https://github.com/electron/electron/issues/18123 It is working fine in 11.0.5 but no success with 12 or 13 branch.

Example: 
`let printersInfo = printWindow.webContents.getPrinters();
let printer = printersInfo.filter(printer => printer.isDefault === true)[0];
const options = {
                silent: true,
                deviceName: printer.name
            }

            printWindow.webContents.print(options, () => {
                printWindow = null;
            });`

**Comment by pushkin-** [comment] 2021-08-16 12:47
dupe of [this](https://github.com/electron/electron/issues/29334)

**Comment by ckerr** [comment] 2021-08-18 19:23
Closing as a duplicate

**Closed by ckerr** 2021-08-18 19:23 UTC
Labels: bug :beetle:
