### ISSUE TITLE
[Bug]: Playing any form of audio causes electron to ask for Accessibility permissions on macOS

### ISSUE THREAD

**Issue by josh-signal** [electron/electron#31558] opened 2021-10-22 23:07 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.5.1

### What operating system are you using?

macOS

### Operating System Version

Any version

### What arch are you using?

x64

### Last Known Working Electron version

13.5.0

### Expected Behavior

I would like an option to stop asking for Accessibility entitlement if our app doesn't need it.

### Actual Behavior

User is prompted for permission for application to control their computer and it's listed under Accessibility in macOS Security & Privacy section.

### Additional Information

This is the commit that introduced this behavior: https://github.com/electron/electron/commit/75349f58adb31cd73eb71713c8ebf30962726013#diff-4390247d2e627f63ca771b47b71bfe35268814a3472039f1749ea424bec3359dR32

We'd love to be on 13.5.1 or later since that fixes the Let's Encrypt CA but the entitlement makes it so we can't.

**Comment by indutny-signal** [comment] 2021-11-11 16:06
@codebytere was it fixed in 15.3.1? Judging by commit history the change should have made its way there, but we are seeing reports from internal testing that the Accessibility permissions popup is back after electron update.

**Comment by indutny-signal** [comment] 2021-11-11 21:02
@codebytere could you reopen this, please? Looks like the issue wasn't fixed by that PR and is in fact caused by:

```C++
  // Add an event tap to intercept the system defined media key events.
  event_tap_ = CGEventTapCreate(
      kCGSessionEventTap, kCGHeadInsertEventTap, kCGEventTapOptionDefault,
      CGEventMaskBit(NX_SYSDEFINED), EventTapCallback, this);
```

in `ui/base/accelerators/media_keys_listener_mac.mm`. I'm investigating why this function (`StartEventTapIfNecessary) is called at all. Commenting the line fixes the issue completely, but I'm not sure if this is what we want to do.

**Comment by indutny-signal** [comment] 2021-11-11 21:12
Alright, I see what's going on now. `kGlobalRequiresAccessibility` has no effect whatsoever anymore so essentially whenever we use `kGlobal` it ends up requiring accessibility permissions.

**Comment by indutny-signal** [comment] 2021-11-11 21:17
Reading full path now I realize that this enum was added in the same patch, and the`media_keys_listener_mac.mm` probably never supported it?

**Closed** 2021-11-15 13:16 UTC
Labels: bug :beetle:

**Comment by ArmelChesnais** [comment] 2021-12-17 19:25
@codebytere seems this is now happening on electron 14.2.1 If we could either reopen this, or I can open a separate issue for it if needed.

**Comment by indutny-signal** [comment] 2021-12-17 20:14
@ArmelChesnais I think #31805 just needs to be backported there.

**Comment by ArmelChesnais** [comment] 2021-12-23 09:46
> @ArmelChesnais I think #31805 just needs to be backported there.

@indutny-signal how do we initiate it? I'm not seeing any indication of backporting for 14.2.1 on that PR
