### ISSUE TITLE
Modal Windows don't yield on close

### ISSUE THREAD

**Issue by Anaerin** [electron/electron#8677] opened 2017-02-14 01:26 UTC
* Electron version: 1.4.15
* Operating system: Windows 10

### Expected behavior
Closing a modally opened window should yield control back to it's parent when it is closed.

### Actual behavior
Modal window closes, parent window refuses to accept input (playing generic error ding when you try and click or type into it)

### How to reproduce
```JavaScript
mainWindow = new BrowserWindow();
mainWindow.loadURL("http://localhost:8000/OverlayControl.html");
mainWindow.webContents.openDevTools();
mainWindow.on("closed", () => {
	mainWindow = null;
});
var authWindow = new BrowserWindow({ parent: mainWindow, modal: true });
authWindow.loadURL("http://localhost:8000/test.html");
```

Then close the popup window, and notice that mainwindow doesn't accept input.

**Comment by zeke** [comment] 2017-02-22 17:49
I'm not able to reproduce this problem on Windows 10 with Electron 1.4.15.

One possible reason might be that your `authWindow` is not created in the global scope, so it's getting garbage collected. But in that case you'd probably see an error, so I'm not sure.

Can you try [this branch](https://github.com/zeke/electron-quick-start/commits/issue-8677) and see if the problem exists there?

```sh
git clone https://github.com/zeke/electron-quick-start                
cd electron-quick-start 
git checkout issue-8677
npm install
npm start
```

**Comment by zeke** [comment] 2017-03-02 18:18
Hi @Anaerin. Were you able to reproduce this issue with the code I shared above?

**Comment by foreverglory** [comment] 2017-03-04 17:12
I'm the same problem.
```js
//renderer.js
const electron = require('electron')
const BrowserWindow = electron.remote.BrowserWindow

const btn = document.getElementById('open')
btn.addEventListener('click', function(){
    var main = BrowserWindow.getFocusedWindow()
    let newWin = new BrowserWindow({
        frame: true,
        modal: true,
        parent: main
    })
    newWin.on('close', function(){
        newWin = null
    })
    newWin.loadURL('http://localhost/new')
    newWin.show()
})
```

When I close the new window, the main window can not click, can not enter, not even close.


Electron version: 1.6.1
Operating system: Windows 10

**Comment by zeke** [comment] 2017-03-04 17:28
@foreverglory what if you initialize `newWin` at the top of the file? I'm wondering if this is a garbage collection issue.

**Comment by zcbenz** [comment] 2017-06-06 07:40
Closing until more information is provided.

**Closed by zcbenz** 2017-06-06 07:40 UTC
Labels: component/modal, platform/windows, triage/bug

**Comment by gautamsi** [comment] 2017-06-07 23:35
looks like a bug in `.show()`. noticed that this problem only happens if you call `.show()` after creating a modal window. Also noticed that if you hide the window once (right after creating by calling `.hide()`) and then call `.show()` it does not have any problem.

**Comment by matortheeternal** [comment] 2017-11-04 01:05
@gautamsi's fix worked for me.  was having the same issue with Windows 7 and Electron 1.7.6.
