### ISSUE TITLE
Silent print settings margins flashback，Flashback occurs if margins are added

### ISSUE THREAD

**Issue by 1134506391** [electron/electron#21076] opened 2019-11-11 09:12 UTC
node:12.0.0
electron: 7.1.1
Silent print settings margins flashback，Flashback occurs if margins are added
```
            margins: {
              marginType: 'custom',
              left: 0
            }
```

complete

```
        webview.print(
          {
            silent: true,
            printBackground: true,
            deviceName: this.printDeviceName,
            landscape: true,
            margins: {
              marginType: 'custom',
              left: 0
            }
          }
        )
```

**Comment by codebytere** [comment] 2019-11-13 12:33
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by xland** [comment] 2019-11-20 10:38
@codebytere 

See #21167

**Comment by electron-triage** [comment] 2020-02-19 23:56
Duplicate of #21167

**Closed by electron-triage** 2020-02-19 23:56 UTC
Labels: 7-1-x, blocked/need-info ❌
