### ISSUE TITLE
`window.loadURL()` re-renders the same html page instead of rendering another

### ISSUE THREAD

**Issue by bakahakka** [electron/electron#13062] opened 2018-05-24 13:26 UTC
* Electron Version: 2.0.1
* Operating System (Platform and Version): macOS High Sierra 10.13.4
* Last known working Electron version: 2.0.0

**Expected Behavior**
`window.loadURL()` should render new page on event sent from html. 

**Actual behavior**
An event from html is received in the main process, but `window.loadURL()` just re-renders the same page.

**To Reproduce**
```sh
$ git clone https://github.com/bakahakka/electron-quick-start.git -b master
$ npm install
$ npm start || electron .
```

**Comment by NicksWorld** [comment] 2018-05-25 20:52
I have tested this on Electron 2.0.1, and have the same OS. This seems to be a non-existent issue. Could you have been getting confused by the slight delay between the button click and the load of the new page? All I received is the new html page, and `Navigated to file:///Users/coding/Desktop/test/electron-quick-start/clicked.html` in the web inspector's console.

**Comment by bakahakka** [comment] 2018-05-29 08:06
@NicksWorld Unfortunately no, I've tried debugging the process and still it just reloads the same page after click instead of loading the other html file

**Comment by DeerMichel** [comment] 2019-07-03 15:45
Do you know whether the issue still exists in Electron v5 or v6 beta? I can't reproduce it (macOS 10.14.5). If not, you can close the issue.

**Comment by sofianguy** [comment] 2019-08-09 00:42
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-09 00:42 UTC
Labels: 2-0-x, bug :beetle:, platform/macOS
