### ISSUE TITLE
Windows lib files for old versions of Electron appear to have been deleted

### ISSUE THREAD

**Issue by murgatroid99** [electron/electron#18855] opened 2019-06-18 00:08 UTC
When building a native addon for Electron on Windows, node-gyp downloads the `.lib` files for linking from `https://atom.io/download/electron/<version number>/win-x86/node.lib`. This link is now accessible for version numbers 4.0.0 and above, and 404 for lower version numbers. I assume that is unintentional because I have not seen any announcement about those versions no longer being supported.

**Comment by nornagon** [comment] 2019-06-18 00:10
Duplicate of https://github.com/electron/electron/issues/18787

**Closed by nornagon** 2019-06-18 00:10 UTC
