### ISSUE TITLE
Tray does not work in production, Windows 10 and possibly OSX as well

### ISSUE THREAD

**Issue by ehguo** [electron/electron#9945] opened 2017-07-05 19:46 UTC
* Electron version: 1.6.10
* Operating system: Windows 10

### How to reproduce

Tray works in development, but once I run build and install the app, tray doesn't work.

$ git clone https://github.com/ehguo/ZenFocus -b tray
$ yarn
$ yarn run package-win

Installer found in the "release" folder in root directory

$ yarn run dev
will confirm that it works in development.

Relevant files can be found in `app/electron/tray/index.js` and `app/main.dev.js` (very last line)

**Comment by MarshallOfSound** [comment] 2017-07-06 21:08
@ehguo Without a minimal reproduction example we can't really help out here, issues like this are normally errors in user code and we can't dive into the code base of a project we've never seen before looking for the error 😄 

I'd recommend running your "release" file from a command prompt window so that you can see logs and ensure that their aren't any uncaughtExceptions.  Also ensure you are resolving paths to the tray icon correctly and not doing a path relative to CWD.

Also https://github.com/ehguo/ZenFocus/tree/tray doesn't exist, looks like you haven't pushed the branch up

**Comment by ehguo** [comment] 2017-07-06 22:16
@MarshallOfSound Oooo yea it looks like the branch got deleted, been making a lot of updates.

Thanks for the tip on running the release through command prompt - I will try that next and get back to you.

**Comment by ehguo** [comment] 2017-07-06 22:30
Okay it looks like it is an error with grabbing the path for the location of the icon.

Currently using
```
path.join(__dirname, '../../../resources/icon.ico');
```

How could I change that to make it relative to install location?

**Closed** 2017-07-06 22:44 UTC
Labels: waiting/needs-repro

**Comment by dphans** [comment] 2019-07-29 10:20
Duplicated: https://github.com/electron/electron/issues/1522#issuecomment-515934455
