### ISSUE TITLE
API: Documented way to close a WebContents

### ISSUE THREAD

**Issue by nornagon** [electron/electron#26929] opened 2020-12-10 18:55 UTC
There should be a documented way to close a WebContents and allow it to be garbage collected.

I'd prefer not to document the existing `webContents.destroy()` method if possible as it's quite aggressive and makes the underlying WebContents object unusable after being called. Ideally, I'd like to have a `webContents.close()` method that returns the object to the state that it was in prior to `loadURL()` being called, and marks it as available for GC once references are dropped.

i.e. this should work:

```js
const bv = new BrowserView
bv.webContents.loadURL("https://example.com")
// ... later ...
bv.webContents.close()
// If the reference to `bv` were dropped here, both `bv` and the webContents would be available for collection

// ... but if the reference is retained, the WebContents should be re-usable at a later date:
bv.webContents.loadURL("https://example.com")
```

Ref https://github.com/electron/electron/pull/23578.

**Comment by kevinlinv** [comment] 2021-01-04 23:53
Heya @nornagon @ckerr, Happy new year 🎉 

I noticed that this issue has been labeled as an enchancement, is there any way we can label it with something that convey a bit more urgency? e.g. a bug/regression perhaps.

Reasoning as partially quoted from the https://github.com/electron/electron/pull/23578#issuecomment-742706524 by @yohan1234 in PR discussion which removes `BrowserView::destroy`.

>[...] The problem is:
>
> - BrowserView.destroy was removed
> - webContents does not have a public API destroy function
>
> [...]

So a previously working browser view (_in electron v10 and below_) now cause a memory leak (_in electron v11 and above_) which makes it unusable. 1 work around proposed in the discussion was to  **use an undocumented `webContents.destroy()`**  which is not ideal so would love to avoid it if possible.

**Comment by pushkin-** [comment] 2021-01-05 00:00
[related issue](https://github.com/electron/electron/issues/27071)

**Comment by kevinlinv** [comment] 2021-01-05 00:06
👋 @pushkin- thanks for linking, OOC, are you currently on electron v11 in your app? 
if so, have you been using `webContents.destroy`? 
I am interested in whether the method is safe enough to use without causing any crashes 🤔

**Comment by pushkin-** [comment] 2021-01-05 00:08
@kevinlinv Yes I'm on Electron 11. I encountered a crash which was because I wasn't detaching the BrowserView from the BrowserWindow before destroying its WebContents, but now that I'm doing that, I haven't seen any crashes.

**Comment by kevinlinv** [comment] 2021-01-05 00:10
Nice, thanks for the info, I might consider using `webContents.destroy` and update to `electron v11` given the need to support Apple ARM 👌

**Comment by kevinlinv** [comment] 2021-01-15 07:13
A friendly 🏓 sorry for the noise. Would appreciate if this issue is looked at by someone who knows the codebase 👍 
It's rather unfortunate for browser view to leak in latest version of electron by default.

**Comment by stewartlord** [comment] 2021-01-20 18:16
+1 for this issue. The work-around (calling destroy() on webContents) addressed the leak for me, but I did experience a hard crash that required wrapping the destroy call in `setImmediate` to avoid.

**Comment by nornagon** [comment] 2021-02-02 21:30
> a previously working browser view (_in electron v10 and below_) now cause a memory leak (_in electron v11 and above_) which makes it unusable.

Just so I'm clear on what the issue is here, the app were previously calling `browserview.destroy()`, then that function was removed—so the app was changed to not call `destroy()`, and now leaks?

I think this should be straightforwardly fixable by calling `browserview.webContents.destroy()` where there was previously a call to `browserview.destroy()`. I'm aware that the `WebContents.destroy()` method is not documented, but in this case I think it's OK to use. Once there exists a documented way to shut down a WebContents, the `destroy()` call can be replaced with that.

@stewartlord would you be able to file a separate bug with the crash info?

**Comment by kevinlinv** [comment] 2021-02-03 03:46
Hey @nornagon thanks for the reply.

> Just so I'm clear on what the issue is here, the app were previously calling browserview.destroy(), then that function was removed—so the app was changed to not call destroy(), and now leaks?

Yes, it's exactly as you've pointed out.

> I think this should be straightforwardly fixable by calling browserview.webContents.destroy() where there was previously a call to browserview.destroy(). I'm aware that the WebContents.destroy() method is not documented, but in this case I think it's OK to use. Once there exists a documented way to shut down a WebContents, the destroy() call can be replaced with that.

True, from my own use case, I'd prefer to not use undocumented api, but not too fussed I really have to and will do so to allow upgrading to `electron@11`

---

It is more into the point of view of new `BrowserView` users that would make this issue slightly unfortunate, as they would immediately run into a memory leak and may not be aware of it before they stumble into this issue.

**Comment by vladimiry** [comment] 2021-06-10 11:09
> +1 for this issue. The work-around (calling destroy() on webContents) addressed the leak for me, but I did experience a hard crash that required wrapping the destroy call in setImmediate to avoid.

@stewartlord I've just placed [the respective issue](https://github.com/electron/electron/issues/29626) with attached core dump.

**Comment by stewartlord** [comment] 2021-06-10 16:52
@vladimiry Thank you 🙏 ..and @nornagon looks like I failed to deliver repro steps - very sorry about that!

**Comment by vladimiry** [comment] 2021-06-15 08:14
> @stewartlord would you be able to file a separate bug with the crash info?

Unfortunately placing a separate issue appears to be a time-wasting procedure since it just got closed with `won't fix` status.

**Closed** 2022-09-16 23:23 UTC
Labels: enhancement :sparkles:
