### ISSUE TITLE
Can't disable contex menu item with role on mac

### ISSUE THREAD

**Issue by nieheyong** [electron/electron#27975] opened 2021-03-03 04:17 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.5
* **Operating System:**
  * macOS 10.15.7
* **Last Known Working Electron version:**
  * unknow

### Expected Behavior
 on Mac os,A contex menu with disabled=true should disabled this menu
### Actual Behavior
 on Mac os, A contex menu item without role can be disable ,but if a menu item with role="selectAll" we can't disable it

### To Reproduce

please load this gist in fiddle  https://gist.github.com/nieheyong/a460f9ed84d9b65dea3df4118a7d5dbc  ,after launch it,click mouse right and see contex menu

### Screenshots

![image](https://user-images.githubusercontent.com/9368693/109751777-24017000-7c1a-11eb-8e91-ce3ec5f2fc2c.png)

**Comment by pdesantis** [comment] 2021-03-10 03:43
I think @codebytere looked in to this here https://github.com/electron/electron/issues/13554

**Comment by nornagon** [comment] 2021-03-12 00:20
Duplicate of #13554

**Closed by nornagon** 2021-03-12 00:20 UTC
Labels: 10-x-y, bug :beetle:, has-repro-gist, platform/macOS
