### ISSUE TITLE
[Bug]: Unable to programmatically resize a maximized window

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#28170] opened 2021-03-13 03:56 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Last Known Working Electron version

6?

### Expected Behavior

At least back in the day, we were able to programatically resize a maximized window (via `setSize` or `setBounds`)

### Actual Behavior

Now, we can't. Nothing happens.

This is a continuation of [this closed issue](https://github.com/electron/electron/issues/22027).

1. start main.js
2. click the "Resize" button
3. notice it resizes
4. maximize the window
5. click the button
6. nothing happens

main.js:
```
const { app, BrowserWindow, ipcMain } = require('electron')

async function createWindow() {
  const mainWindow = new BrowserWindow({ webPreferences: { nodeIntegration: true, contextIsolation: false } });
  await mainWindow.loadFile(__dirname + "/index.html");

  ipcMain.on("resize", () => {
    mainWindow.setSize(500, 500);
  });
}

app.on('ready', createWindow)
```

index.html:
```
<button id="b">Resize Window to 500x500</button>
<script>
  require('./renderer.js')
</script>
```

renderer.js:
```
const { ipcRenderer } = require("electron");
document.getElementById("b").onclick = () => {
    ipcRenderer.send("resize");
};
```

**Comment by nornagon** [comment] 2021-03-15 20:50
Just to check, would you expect the window state to become something other than 'maximized' once you resize it?

**Comment by pushkin-** [comment] 2021-03-15 21:38
@nornagon I guess? I don't think this is actually a serious problem for me, but it used to behave differently I believe, so I figured you could determine if that was an intentional change or not. I can live with the current behavior. But yes, if a resize were to happen for a maximized window, it should stop being maximized.

That being said, Chrome doesn't let you resize maximized windows with `Window::resizeTo`. Maybe that's what "broke" the behavior

**Comment by pushkin-** [comment] 2021-03-15 21:45
@nornagon [relevant Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1024323&q=resizeTo&can=2):

>Chromium used to allow it to work on Windows with versions < 78, however the code that allowed it to work was actually a bug and has since been removed

... so Electron 6 and under I guess

**Comment by nornagon** [comment] 2021-03-15 22:16
So... this is working as intended?

**Comment by pushkin-** [comment] 2021-03-15 22:27
@nornagon I guess so. I just wasn't sure if there was Electron logic controlling this, and if we wanted to deviate from Chrome behavior. We can close this though, if you don't think Electron will pursue a "fix"

**Comment by nornagon** [comment] 2021-03-16 19:31
It's unclear to me what the correct behavior here is, if someone feels strongly about it I'd be happy to consider a PR. I'm going to close this out for now though.

**Closed by nornagon** 2021-03-16 19:31 UTC
Labels: 12-x-y, bug :beetle:, component/BrowserWindow, platform/windows
