### ISSUE TITLE
bug: webview1 setDevToolsWebContents to webview2, and then webview1 openDevTools, devtools is open, but the tab "Elements" cannnot show the html hierachy of the webview1

### ISSUE THREAD

**Issue by cyqresig** [electron/electron#15874] opened 2018-11-29 03:38 UTC
Output of `node_modules/.bin/electron --version`: `v3.0.7`   (I tried almost all the versions above 3.0.0)
Operating System (Platform and Version): Mac OSX Sierra
Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
do webview1.getWebContents().setDevToolsWebContents(webview2.getWebContents())
do webview1..getWebContents().openDevTools() 
and then webview2 show the chrome dev-tool panel and the panel tab "Elements" should show the html hierachy of the webview1

**Actual behavior**
webview2 show the chrome dev-tool panel and the panel tab "Elements" does not show the html hierachy of the webview1. It seems dev-tool is not valid.

**To Reproduce**

https://github.com/cyqresig/electron-quick-start/tree/bug/setDevToolsWebContents_cyq_20181129

```sh
$ git clone https://github.com/cyqresig/electron-quick-start -b bug/setDevToolsWebContents_cyq_20181129
$ npm install
$ npm start || electron .
```

![image](https://user-images.githubusercontent.com/1388338/49197855-84662f00-f3cb-11e8-9a10-162a5525a459.png)

**Comment by wty15858221599** [comment] 2018-12-03 08:05
i have this bug,too.anyone fix it??with out setDevToolsWebContents ,devtools will be OK in another window.but it dont work when i set it to a webview's webcontents.However,the official doc has its demo:
<html>
<head>
  <style type="text/css">

    * { margin: 0; }
    #browser { height: 70%; }
    #devtools { height: 30%; }
  </style>
</head>
<body>
  <webview id="browser" src="https://github.com"></webview>
  <webview id="devtools"></webview>
  <script>
    const browserView = document.getElementById('browser')
    const devtoolsView = document.getElementById('devtools')
    browserView.addEventListener('dom-ready', () => {
      const browser = browserView.getWebContents()
      browser.setDevToolsWebContents(devtoolsView.getWebContents())
      browser.openDevTools()
    })
  </script>
</body>
</html>
it  not work obviously.

**Comment by wxungang** [comment] 2018-12-06 09:23
i have this bug,too!  
electron: v 3.0.10
Operating System (Platform and Version): win10

**To Reproduce**
https://github.com/UIorPM/electron/blob/master/src/views/render/devTools.js

**Comment by damoqiongqiu** [comment] 2019-01-06 12:57
Same but in v 4.0.1, on Windows 10 64bit.

**Comment by njleonzhang** [comment] 2019-03-01 06:47
same issue, https://github.com/electron/electron/issues/17168

**Comment by freedomelf** [comment] 2019-04-15 08:51
Same bug in v 4.1.0, on macOS

**Comment by freedomelf** [comment] 2019-04-15 14:57
> same issue, #17168. mac, electron 4.0.2. Have you worked around it?

https://github.com/electron/electron/issues/17168#issuecomment-483224164

**Comment by kitze** [comment] 2019-06-07 08:07
@freedomelf @cyqresig did you maybe find a solution?

**Comment by Kilian** [comment] 2019-10-08 13:07
This is a duplicate of #14095

**Closed** 2019-10-09 14:59 UTC
Labels: 3-0-x, 4-2-x, bug :beetle:, platform/macOS

**Comment by huyifan** [comment] 2020-07-03 03:29
hi guys who troubled with using devTools in webView. if you do want to use webView to load devTools and debug the page ,you can try this way.

*1
you can add those code in main process which can open a socket server that contains all devUrl you need

const { app } = require('electron');
……
app.commandLine.appendSwitch('remote-debugging-port', ${debugPort});
app.commandLine.appendSwitch('remote-debugging-address', 'http://127.0.0.1');

*2
in render process you can fetch the url '127.0.0.1:debugPort/json' and it will resp all devUrls .

*3
if you set webView url such as 'http://github.com',And in step 2 you has got all devUrls , you just need to get the devUrl which .url.indexOf('http://github.com')

*4
devtoolsViewDom.setAttribute("src", http://127.0.0.1:${debugPort}${devUrl})

above may not easy to understand ,I will give a demo soon.
