### ISSUE TITLE
[Mac] Hover styles and events don't work when window is unfocused

### ISSUE THREAD

**Issue by natew** [electron/electron#14567] opened 2018-09-12 05:03 UTC
* Output of `node_modules/.bin/electron --version`: 3.0.0-beta.8
* Operating System (Platform and Version): Mac OSX Mojave

**Expected Behavior**

There should be an option to accept mouse events when a window is unfocused.

**Actual behavior**

WIndows don't accept any hover CSS states or events while unfocused.

**Additional Information**

I know about this ticket: https://github.com/electron/electron/issues/2797, but it was already closed and I'm not sure why. It's actually a requirement for desktop apps that want to feel native, as electron hopes to provide.

I understand this would need to be enabled in Chromium, hoping to hear if there's been any progress here, perhaps the latest builds enable it, or even just tips on where to look to make these changes.

**Comment by MarshallOfSound** [comment] 2018-09-12 05:08
This would need to be fixed / implemented in Chromium, if you want this feature you should raise it on Chromium's bug tracker and ask them to implement it.

Closing as duplicate of #2797

**Closed by MarshallOfSound** 2018-09-12 05:08 UTC

**Comment by natew** [comment] 2018-09-12 05:51
Don’t close it just because it’s upstream. This lets people vote on it and
discuss it. You’re shutting down discussion of a valid feature request
that’s related to electron.
