### ISSUE TITLE
Error: net::ERR_CERT_INVALID     on app start

### ISSUE THREAD

**Issue by ttushka** [electron/electron#25354] opened 2020-09-07 10:24 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.1

* **Operating System:**
  * macOS 10.15.6

### Expected Behavior

Start of the app.

### Actual Behavior

Error in Terminal:

```
rollup v2.26.9
bundles src/main.ts → app...
created app in 6.9s

 waiting for changes...
Failed to fetch extension, trying 4 more times
Failed to fetch extension, trying 3 more times
Failed to fetch extension, trying 2 more times
Failed to fetch extension, trying 1 more times
Failed to fetch extension, trying 0 more times
Error: net::ERR_CERT_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6400)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:482:12)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:137:15)
[45843:0907/120131.534046:ERROR:gles2_cmd_decoder.cc(18929)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[45843:0907/120131.534136:ERROR:gles2_cmd_decoder.cc(18950)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[45843:0907/120131.534174:ERROR:gles2_cmd_decoder.cc(13814)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[45843:0907/120131.534213:ERROR:gles2_cmd_decoder.cc(18929)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[45843:0907/120131.534245:ERROR:gles2_cmd_decoder.cc(18950)] [.DisplayCompositor

```
### To Reproduce

Not sure, since all I was doing was follow the very basic instructions over at Rocket.Chat to start developing. https://github.com/RocketChat/Rocket.Chat.Electron#development
The steps are: 
```
git clone https://github.com/RocketChat/Rocket.Chat.Electron.git
cd Rocket.Chat.Electron
yarn
yarn start
```

Following the `yarn start` command I get the aforementioned output.
This seems to be an Electron issue rather than Rocket.Chat.

### Screenshots

![Screenshot 2020-09-07 at 12 22 26](https://user-images.githubusercontent.com/56022690/92377738-e60d0e80-f104-11ea-84d3-3e4622e22b06.png)

**Comment by msyfls123** [comment] 2020-12-07 09:49
Have u tried to add this line of code?
```
app.commandLine.appendSwitch('ignore-certificate-errors', true);
```

**Comment by TarVK** [comment] 2021-03-07 02:28
Is there any known proper fix for this? We're running into the same issue on mac with websites that definitely have signed certificates such as google, and would rather not disable certificate checking all together.

**Comment by csett86** [comment] 2021-03-11 21:41
I have reproduced this error with the mac app store sandbox and the minimal example at https://github.com/csett86/electron-boilerplate/tree/certificate-error

Tested electron versions: 8, 10, 11 and 12.

**Comment by nornagon** [comment] 2021-03-11 23:43
@csett86 is the MAS sandbox required to reproduce this...? It's surprising to me that it would be related, especially since the original report mentioned experiencing the error when unpackaged.

**Comment by nornagon** [comment] 2021-03-11 23:51
The error message in the original report appears to be coming from a Vue devtools installation plugin: https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/54f9b6b2907db0e542aea7c2af4dacef551efe15/lib/installVueDevtools/downloadChromeExtension.js#L40

@csett86 I tried running your repro, but the app starts normally for me. What OS version are you running on?

**Comment by csett86** [comment] 2021-03-12 05:37
You're right, the app starts, but when you open devtools you see that the external jquery file cannot be loaded due to "net::ERR_CERT_INVALID" (the requested site obviously has a valid certificate and when removing the app-sandbox the file loads fine)

I'm running this under macOS 11.2

**Comment by csett86** [comment] 2021-03-12 18:56
@nornagon You're right, this is not related, I will open a proper new bug describing the certificate issue with the mac app store sandbox.

**Comment by nornagon** [comment] 2021-03-15 18:49
Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

**Comment by nornagon** [comment] 2021-07-06 21:44
Since we don't have a repro for this, I'm closing the issue. Happy to reopen if you're able to provide a repro.

**Closed by nornagon** 2021-07-06 21:44 UTC
Labels: 10-x-y, 11-x-y, 12-x-y, 8-x-y, blocked/need-repro, bug :beetle:, platform/macOS

**Comment by DavidBlowi** [comment] 2025-08-22 02:36
> Since we don't have a repro for this, I'm closing the issue. Happy to reopen if you're able to provide a repro.

I am encountering this error whenever I open the (Electron) app [Motrix](https://github.com/agalwood/Motrix) on my MacBookPro13,3 running macOS Monterey 12.7.6. 

The exact text of the error is:

**Error** 
Cannot check for updates: Error:net::ERR_CERT_INVALID at SimpleURLLoaderWrapper.<anonymous>
(node:electron/js2c/browser_init:2:49386) at SimpleURLLoaderWrapper.emit (node:events:513:28)
