### ISSUE TITLE
PDF not rendering on temporary partition 

### ISSUE THREAD

**Issue by AbyAbyss** [electron/electron#26692] opened 2020-11-25 09:23 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * (output of `node_modules/.bin/electron --version`) e.g. 11.0.3
* **Operating System:**
  * (Platform and Version) e.g. macOS / Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Render PDF in BrowserWindow and webview for all partition

### Actual Behavior
Renders PDF in `default partition` and partition with `persist:`
but does not work for partitions without `persist:` 
eg: 
```javascript
{partition: 'somepartition'}
```

### To Reproduce
Please use this modified template to verify
https://github.com/AbyAbyss/electron-quick-start.git

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/AbyAbyss/electron-quick-start.git
$ npm install
$ npm start
```

### Screenshots

![image](https://user-images.githubusercontent.com/24456144/100207552-b7494c00-2f2d-11eb-91d6-48ea63ef87ca.png)

**Comment by simann** [comment] 2020-11-27 09:23
Greetings,

i had the same bug. If i create a temporary session(without "persist") the PDF is empty.

With the "persist:xxx" everything seems to work.

**Comment by codebytere** [comment] 2021-02-10 19:46
Duplicate of https://github.com/electron/electron/issues/27121

**Closed by codebytere** 2021-02-10 19:46 UTC
Labels: 11-x-y, platform/windows
