### ISSUE TITLE
Some HTTP requests not shown in 'network' devtools panel.

### ISSUE THREAD

**Issue by burtonator** [electron/electron#17946] opened 2019-04-24 14:25 UTC
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Some HTTP requests via pdf.js are not shown.

I'm loading a PDF via HTTP and express embedded in Electron. 

pdf.js uses fetch (or XHR, not sure) to fetch a PDF locally.

I can verify via the HTTP logs in express that the request is being performed but they're not logged in the dev tools network panel.

* **Electron Version:**
  * 3.0.6 and 5.0-beta9
* **Operating System:**
  * Ubuntu 18.0.4
* **Last Known Working Electron version:**:
  * none

### Expected Behavior
The request should be logged including request/response headers just like a normal request.

Normal Chrome does the right thing in our webapp - just not in our desktop version.

### Actual Behavior

Nothing is logged for these requests.  HTTP requests for static resources are logged just fine.

### To Reproduce

Probably to download Polar , open up a PDF and then load dev tools

I'm can take screenshots of our webapp vs electron version too.

**Comment by burtonator** [comment] 2019-04-24 14:33
I thought this might have something to do with us using partitions and I disabled them but this doesn't seem to resolve the problem.

**Comment by burtonator** [comment] 2019-04-24 14:52
It seems to be something related to scrolling through the document.  pdf.js seems to not abort pages that won't need to be rendered as we've moved too far forward.  

I think we're seeing two problems:

1. Electron 5.x might be slow at rendering pages so rule this out.

2. pdf.js might not abort when scrolling through the document and maintaining the buffer of pages.  if we could tell it when a page is invalidated it could abort rendering that page.  We might just have to look at a queue and then abort that page when it's not going to be used anyway.

**Comment by burtonator** [comment] 2019-04-24 14:53
3.  This could STILL be an Polar issue so I need to rule this out entirely by loading up the default demo app.

**Comment by burtonator** [comment] 2019-04-24 14:56
I loaded up the electron demo app with the large doc.. it's not amazingly fast but still MUCH faster than ours... It might be our event handlers or something else in the way.

There still does seem to be a scroll lag though.. need to try it on the browser.

**Comment by burtonator** [comment] 2019-04-24 14:59
Chrome is definitely faster but it's just an issue with lagginess not a massive CPU impact...

**Comment by burtonator** [comment] 2019-04-24 15:03
ok.. disabling our webapp and JUST running pdf.js shows that it's still insanely slow. So I think this means it's something to do with our Electron window settings maybe.

**Comment by burtonator** [comment] 2019-04-24 15:20
OK... it has to do with nodeIntegration.. at least when turning off node integration things are much much faster within pdf.js.. I can try to disable it in the worker and see what happens.

**Comment by burtonator** [comment] 2019-04-24 15:26
ok... I spent more time and tracked this down.  I'm not 100% certain what's causing it but I think it has something to do with either partitions or nodeIntegrationInWorker / nodeIntegration.  Will update when I have more details.

**Comment by videahealth-jeannei** [comment] 2019-07-10 14:55
Any update on this? I am facing the same issue with electron `5.0.5`.

**Comment by divefox** [comment] 2019-07-30 11:43
I have the same question

**Comment by gannons** [comment] 2019-08-07 11:41
This seems to be a long standing issue. Surprised by how sparse the available information is

https://stackoverflow.com/questions/50090977/how-to-get-a-network-panel-show-up-when-debugging-electron-node-applications/50179917

https://github.com/electron/electron/issues/828

**Comment by adityak368** [comment] 2019-08-25 19:27
For me, fetch requests run fine. But xhr requests dont show up the in dev-tools

**Comment by gannons** [comment] 2019-08-26 09:44
I had not noticed that difference as all my requests are xhr based

**Comment by alisherafat01** [comment] 2020-01-06 10:20
I also have this problem

**Comment by electron-triage** [comment] 2020-02-19 19:58
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:22
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:22 UTC
Labels: 3-0-x, 5-0-x, blocked/need-info ❌, bug :beetle:, platform/linux

**Comment by Ybasthis** [comment] 2021-04-04 13:40
Hello I have this problem with iframe, electron = 12.0.1
