### ISSUE TITLE
[Bug]: loadUrl sometimes returns wrong html content

### ISSUE THREAD

**Issue by bayun2** [electron/electron#36138] opened 2022-10-26 04:05 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.5.2

### What arch are you using?

x64

### Expected Behavior

loadURL can return correct html content

### Actual Behavior

loadURL can return correct html content at first, when i use cmd + R to refresh html, sometimes return js content as html.

html file content inside asar is always correct

### Additional Information

when i use cmd + R to refresh html, sometimes return js content as html.

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/3183696/197931504-bb19e701-f428-4372-8f5b-c76ff5114db7.png">
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/3183696/197931530-e6c93086-bee3-496e-8f35-793aeb613b13.png">
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/3183696/197932126-3d8d7324-c21e-457f-80a1-d0613bb6ae66.png">

html file content inside asar is always correct
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/3183696/197931604-ba1a2af6-10e7-4054-9ac8-8a4ab356016a.png">

loadUrl in the following way
<img width="670" alt="image" src="https://user-images.githubusercontent.com/3183696/197931984-919d10d7-959e-4c73-80b9-d83fc73fdd08.png">

windowConfig
```
static defaultWindowOptions: () => Electron.BrowserWindowConstructorOptions = () => ({
  ...LBConfig.defaultWindowSizeOptions,
  minWidth: 1440,
  minHeight: 800,
  titleBarStyle: 'hidden',
  frame: false,
  titleBarOverlay: false,
  acceptFirstMouse: true,
  webPreferences: {
    minimumFontSize,
    sandbox: false,
    nodeIntegration: false,
    contextIsolation: true,
    preload: __dirname + '/preload.js',
    devTools: true,
  }
})
```
Probably an error caused by autoupdate，The zip package has been downloaded, but the installation has not been triggered

**Comment by deermichel** [comment] 2022-10-26 11:48
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com/) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

Regarding the update hypothesis, there might be a small time window during app restart when an update is applied that causes undefined behavior (ref https://github.com/electron/electron/issues/36117) - however this doesn't affect the app during regular runtime.

**Comment by bayun2** [comment] 2022-10-28 02:44
I have found a path to reproduce.

When the software exits with quitAndInstall or autoInstallOnAppQuit = true, if the software is quickly opened again during Shipit running, the software is still running the old code. At this time, the bug described can be reproduced by refreshing with cmd+R.

I'm sorry, I can't provide a direct testcase because this bug depends on an update of the package to reproduce

**Comment by VerteDinde** [comment] 2022-10-31 17:28
@bayun2 We have a fix for this Shipit bug incoming here: https://github.com/electron/electron/pull/36130

**Comment by codebytere** [comment] 2023-01-05 12:34
Closing as https://github.com/electron/electron/pull/36130 has been merged.

**Closed by codebytere** 2023-01-05 12:34 UTC
Labels: platform/macOS, bug :beetle:, blocked/need-repro, 21-x-y
