### ISSUE TITLE
Developer console error output is confusing

### ISSUE THREAD

**Issue by littleskunk** [electron/electron#8778] opened 2017-02-26 21:10 UTC
* Electron version: 1.6.1
* Operating system: Windows 10 64bit running a 32bit binary

### Expected behavior

Our app is throwing errors at the moment. These errors have a low priority and will not be fixed soon.

Electron 1.4.15 has a very good developer console. Each error is only 1 line and I can click on it if I would like to see more details. I am able to find any unknown error.
![electron_1 4 15](https://cloud.githubusercontent.com/assets/6333390/23343697/16efc188-fc70-11e6-92b4-de7178959ee1.jpg)

### Actual behavior

The developer console of Electron 1.6.1 is not as good as the old one. Each error needs now ~10 lines. I only see 1/10 and that makes it hard to find any unknow error. 
![electron_1 6 1](https://cloud.githubusercontent.com/assets/6333390/23343698/20029cf0-fc70-11e6-8523-c25804355918.jpg)

**Comment by MarshallOfSound** [comment] 2017-02-27 01:45
@littleskunk I believe that this depends on whether the devtools are open or not while the errors occur, also this would be a Chromium change not an Electron change.  Will defer to others for confirmation of that theory 👍

**Comment by littleskunk** [comment] 2017-02-27 07:24
Chrome version 56.0.2924.87
I don't know which chrome version electron 1.4.15 was working.

Closed or open developer console has no effect. In both cases the same confusing output.

**Comment by tonyganch** [comment] 2017-02-28 18:00
I believe this is not Electron's issue.
For reference, here is the commit in Chromium that changed appearance of errors in console:
https://codereview.chromium.org/2284123002
And here is the corresponding bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=610559

What `console.error` does is basically concatenates two objects (string and error in your case) and highlights it with red.
What changed in newer version is that Chromium changed how error objects are displayed in console by printing the whole stack.

@groundwater, regarding labels, this is not platform specific, the change affects all platforms.

**Comment by tonyganch** [comment] 2017-02-28 18:10
To reproduce the behaviour mentioned in this issue, log a string and an error in one `console.error` call:
```js
var error = new Error('pandas');
console.error('nani', error);
```

**Comment by kevinsawicki** [comment] 2017-03-01 20:17
@tonyganch thanks for investigating this, closing this out since this is a deliberate behavior change in Chrome.

@littleskunk you may want to open a Chrome issue (or comment on the original) upstream to discuss this changed behavior.

**Closed by kevinsawicki** 2017-03-01 20:17 UTC
Labels: platform/windows, triage/bug, version/1.6.x
