### ISSUE TITLE
Setting to make window ignore all clicks

### ISSUE THREAD

**Issue by OlsonDev** [electron/electron#2864] opened 2015-09-21 23:50 UTC
Back in January, [it was documented](https://github.com/atom/electron/commit/bda3711815ef0e01ae0c380dbc262d7efd604aa9#diff-b0dbfed07f681b0f2ecb1eb01f0ed85b) that an API to set window shape would be coming once an upstream bug was resolved. That bug was already "lower than Priority 1" at the time.

I'm curious if it would be possible to make a setting in the interim to just ignore all clicks and pass them through to whatever's underneath? I'd like to make an overlay type program and would effectively like to say my window shape is a 0x0 rectangle. In my case, I'd be fine with strictly Windows compatibility.

**Comment by zcbenz** [comment] 2015-09-22 02:13
This is kind of a duplicate of #1335, but only support ignoring all clicks should be much easier to implement.

**Comment by ButzYung** [comment] 2015-10-05 06:35
I am very interested in seeing progress in this feature development. I am building a desktop gadget application that makes heavy use of canvas and transparent elements. In the mean time, I am using NW.js for this project, and while it supports transparent window as well, the fact that the transparent area is still blocking mouse clicks reduces the usability of the gadgets (especially when they are "always on top"). Having a setting to ignore all clicks will definitely be the one feature that attracts me to move to Electron.

**Comment by billyct** [comment] 2015-11-10 10:55
+1

**Comment by sevengo8378** [comment] 2015-11-20 09:53
+1

**Comment by TimvdEijnden** [comment] 2015-12-01 14:05
I'm interested too, i'm building an app with a semi transparent window that's on top of other applications but mouseevents need to get through to the other applications.

**Comment by atdrago** [comment] 2015-12-03 17:15
+1

It doesn't look like the Chromium team wants to get anywhere near this one. It's now labeled as "WontFix". https://code.google.com/p/chromium/issues/detail?id=387234

**Comment by iamdriz** [comment] 2016-02-02 13:37
@zcbenz Any chance of getting this into Windows versions of Electron?

**Comment by TimvdEijnden** [comment] 2016-02-02 15:37
@billyct Is it hard to also get this working on Windows?

**Comment by ButzYung** [comment] 2016-02-03 07:12
Didn't notice that `win.setIgnoreMouseEvents(ignore)` was already introduced for OSX in recent updates. I wonder if there can be a Windows version as well.

**Comment by Schrims** [comment] 2016-02-05 07:17
+1

**Comment by billyct** [comment] 2016-02-07 16:52
@timruffles maybe you should look forward to the windows api

**Comment by billyct** [comment] 2016-02-07 18:10
maybe the code below can do ignore clicks with windows 😂 😂 😂,i will try it during Chinese New Year,happy Chinese new year @zcbenz ,also everyone
```
DWORD style = ::GetWindowLong(hwnd_, GWL_EXSTYLE); 
::SetWindowLong(hwnd_, GWL_EXSTYLE, style | WS_EX_TRANSPARENT);
```

**Comment by ButzYung** [comment] 2016-05-08 06:04
Any progress for the Windows version of "setIgnoreMouseEvents"?

**Closed** 2016-06-07 12:05 UTC
Labels: enhancement
