### ISSUE TITLE
MenuItem Accelerators Not Working in Ubuntu 16.04.2 LTS for 3.0.0-beta.1~6

### ISSUE THREAD

**Issue by hackjutsu** [electron/electron#14252] opened 2018-08-22 04:59 UTC
* Electron Version: 3.0.0-beta.1 ~ 3.0.0-beta.6
* Operating System (Platform and Version): Ubuntu 16.04.2 LTS
* Last known working Electron version: versions before 3.0.0-beta.1

**Expected Behavior**
Console prints out `time to print stuff` when `Ctrl+P` is pressed.
```
const {Menu, MenuItem} = require('electron')
const menu = new Menu()
  
app.on('ready', () => {
  createWindow()
  menu.append(new MenuItem({
    label: 'Print',
    accelerator: 'CmdOrCtrl+P',
    click: () => { console.log('time to print stuff') }
  }))
  Menu.setApplicationMenu(menu)
})
```
https://github.com/hackjutsu/electron-quick-start/commit/6ceb5d7dcd2d946c071b43a3fdd1b0434ddebff5
**Actual behavior**
No output. The accelerator event is not triggered.

**To Reproduce**
```sh
git clone https://github.com/hackjutsu/electron-quick-start
cd electron-quick-start
npm install
npm run start
```
Try pressing `Ctrl+P`, and observe the output. (nothing happen...)
Change the electron version back to 2.0.0 in `pakcage.json`
```sh
npm install
npm run start
```
Try pressing `Ctrl+P`, and observe the output. (the log `time to print stuff` will show up in console)

**Comment by ckerr** [comment] 2018-08-22 22:26
Thank you for 
I'm not able to reproduce this issue in 18.04.1 + 3.0.0 beta 7.

```sh
$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
electron-quick-start:

```text
We are using Node.js 10.2.0, Chromium 66.0.3359.181, and Electron 3.0.0-nightly.20180821.
```
In this setup, `Ctrl+P` yields `time to print stuff` in the terminal.

At first I thought this might be due to a difference in using a nightly instead of 3.0.0-beta.6, but I get the exact same behavior in 3.0.0-beta.6.

Marking this as `blocked/needinfo` as I'm not sure how to reproduce this issue.

**Comment by hackjutsu** [comment] 2018-08-23 03:30
Just confirmed that MenuItem Accelerators is working for Ubuntu 18.
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```
But not for Ubuntu 16
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by TGWKE** [comment] 2018-10-03 22:54
Hi! The Desktop Environment matters for this issue. Ubuntu 16.04 was probably tested w/ Unity while Ubuntu 18.04 was probably tested with GNOME.  The issue is only on Unity (so far that I know - I haven't tested all DEs).  This is also an issue on Ubuntu 18.04/Unity.  I can switch between The GNOME DE and the Unity DE on the same 18.04 system and can see the different behavior.

**Closed** 2018-11-09 21:54 UTC
Labels: 3-0-x, bug :beetle:, platform/linux/ubuntu

**Comment by hackjutsu** [comment] 2018-11-12 22:43
So how’s the status of this issue? Is it fixed or won’t fix?
