### ISSUE TITLE
Disabled/hidden menu appears anyway after upgrade to 4.0.0-beta.8

### ISSUE THREAD

**Issue by zadam** [electron/electron#15901] opened 2018-11-30 16:51 UTC
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.8
* Operating System (Platform and Version): Ubuntu Linux 18.10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v4.0.0-beta.7

**Expected Behavior**
No application menu appears.

**Actual behavior**
Menu appeared, additionally it's invisible before clicking on it (see screenshots).

**To Reproduce**
```sh
$ git clone https://github.com/zadam/trilium -b master
$ npm install
$ npm run start-electron
```
**Screenshots**

The weird thick title bar is actually a menu after clicking on it:

![image](https://user-images.githubusercontent.com/617641/49302654-fa4fc080-f4c7-11e8-9c64-bf24c9cb557e.png)

This is the menu after clicking on it:

![image](https://user-images.githubusercontent.com/617641/49303191-60891300-f4c9-11e8-8ef2-8d4e76a3c450.png)

**Additional Information**

To be clear my app doesn't have any app menu so the menu isn't enabled. This worked as expected with 4.0.0-beta.7 and earlier versions.

**Comment by ckerr** [comment] 2018-11-30 19:07
This is possibly fixed by https://github.com/electron/electron/pull/15878 which will be in `4.0.0-beta.9`.

Could you please retest with that once it's released?

**Comment by ckerr** [comment] 2018-11-30 19:08
OH -- also, thank you for testing your app with the betas! :heart:

**Comment by ckerr** [comment] 2018-11-30 21:57
This works in 64874660e1b5578f0eebed3a1dbb2cb363cbec4a but not in 7cc7d4a360b58ab2dfbf6a67a1a33d19e0b0c59c, so I think https://github.com/electron/electron/pull/15094 that caused this regression.

@nitsakh I'm happy to investigate this, but if you have an idea of the cause, do you want this ticket?

**Comment by TheFeelTrain** [comment] 2018-12-29 20:13
Same issue here after updating to 4.0.0 on Arch Linux with KDE Plasma 5.

**Comment by ventr1x** [comment] 2019-01-14 09:53
Any info regarding this?

setMenu(null) is not working at all.
Overwriting the menu template afterwards works, but results in the debug menu appearing for a few seconds until initialization.

"electron": "^4.0.1" on macOS

**Comment by andrewheadricke** [comment] 2019-01-18 05:49
stumbled onto same issue. v4.0.1

**Comment by vladimiry** [comment] 2019-01-18 05:55
> Any info regarding this?

As an ugly workaround, you can set [autoHideMenuBar](https://electronjs.org/docs/api/browser-window#new-browserwindowoptions) to true creating the BrowserWindow. So menu will remain hidden until user presses alt key.

**Comment by bluenote10** [comment] 2019-02-09 11:17
I have a similar issue (menu is always visible despite `setMenu(null)`, no black font color). Tested with 4.0.1 and 4.0.4 under Linux.

**Comment by Ajeey** [comment] 2019-03-18 05:20
> > Any info regarding this?
> 
> As an ugly workaround, you can set [autoHideMenuBar](https://electronjs.org/docs/api/browser-window#new-browserwindowoptions) to true creating the BrowserWindow. So menu will remain hidden until user presses alt key.

After you've done the above, an even uglier workaround is to disable the alt key press - 

```
document.addEventListener('keydown', (event) => {
    if(event.altKey) {
        event.preventDefault();
        return;
    }
});
```

Tested this on 4.0.8 and works :dancer:

**Comment by jacobq** [comment] 2019-04-08 16:51
The work-around I am using is to call [`win.setMenuBarVisibility(false)`](https://electronjs.org/docs/api/browser-window#winsetmenubarvisibilityvisible-windows-linux). That seems to avoid the problem with the Alt key revealing the menu. Am I missing something?

**Comment by pronebird** [comment] 2019-04-29 10:03
@jacobq yep you're missing the fact that it does not work on Ubuntu Linux. The only way to hide the menu was to set `autoHideMenuBar: true`, but `win.setMenuBarVIsibility(false)` does nothing at all.

**Comment by jacobq** [comment] 2019-05-03 18:10
@pronebird 
> it does not work on Ubuntu Linux

Really? Try my [minimal demo here](https://github.com/jacobq/electron-quick-start/tree/setMenu-test). It works for me on Debian. What is the difference?

**Comment by Ajeey** [comment] 2019-05-09 08:51
@jacobq Try hiding for a child window

**Comment by electron-triage** [comment] 2020-02-19 21:38
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by joehonton** [comment] 2020-02-21 01:44
This is the code that hid the menu from the window. It was working in 3.10 but broke in 4.0.0 --
```
var browserWindow = new Electron.BrowserWindow(options);
browserWindow.setMenu(null);

```
I have just now tested this on these versions all of which still exhibit the broken behavior:

- 4.0.1
- 5.0.13
- 6.1.7
- 7.1.13
- 8.0.1


This ticket should be kept opened.

**Comment by jacobq** [comment] 2020-02-21 12:59
Does the `Menu.setApplicationMenu(null)` work-around mentioned in the linked issue help?

**Comment by ventr1x** [comment] 2020-02-21 13:56
"We completely ignored this issue for nearly two years, please test again if it magically disappeared so we can keep ignoring it.Thanks, your truly. useless bot."

**Comment by joehonton** [comment] 2020-02-21 16:53
@jacobq The `Menu.setApplicationMenu(null)` purported work-around does not work.

There appears to be two scenarios intermingled in this discussion. The one I'm reporting is where I have an application window that _does_ have a menu, and a second window, for informational purposes, that does not.

This is the desired pseudo code:
```
menu = Electron.Menu.buildFromTemplate(template);
Electron.Menu.setApplicationMenu(menu); 
. . .
myApplicationWindow = new Electron.BrowserWindow(options);
. . .
mySecondWindow = new Electron.BrowserWindow(options);
mySecondWindow.setMenu(null);
```

**Comment by jacobq** [comment] 2020-02-21 17:54
> @jacobq The `Menu.setApplicationMenu(null)` purported work-around does not work.

OK, so IIUC the reason in your case is that [`Menu.setApplicationMenu(menu)`](https://www.electronjs.org/docs/api/menu#menusetapplicationmenumenu) affects all windows (on Windows / Linux) but you need to control specific windows.

Would you be willing to share an [electron-fiddle](https://github.com/electron/fiddle) demonstrating the problem? I would be curious to see it since I have run into similar problems in the past but was always able to work around them somehow (e.g. wait for ready event).

**Comment by joehonton** [comment] 2020-02-22 18:10
I have worked through the issue stripping down the code to bare essentials, TL;DR I am now satisfied that `browserWindow.setMenu(null)` **does work** as expected.

The longer story is that my app has a lengthy initialization phase (approximately 1000ms to 1500ms depending on the file it's opening), which causes a race condition between creating the menu with `Electron.Menu.buildFromTemplate` and creating the first and second browser windows. This triggers an occasional artifact where the `setMenu(null)` for the second window is overridden by `setMenu(menu)` being called on the first window.

It would be OK with me to close this ticket, but the real solution would be to change `new BrowserWindow(options)` to have an option that explicitly states that the window should not have a menu.

**Comment by electron-triage** [comment] 2021-03-09 03:45
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 03:45 UTC
Labels: 4-2-x, 6-1-x, 7-1-x, 8-x-y, bug/regression :leftwards_arrow_with_hook:, platform/linux, status/confirmed
