### ISSUE TITLE
OSR now seems to use display device scale rather than 1.0 as it used to?

### ISSUE THREAD

**Issue by vulture** [electron/electron#18692] opened 2019-06-07 18:27 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 3.0.16

### Expected Behavior
When passing in a width and height to an offscreen renderer (with frameless/notshown settings), we expect the `.on('paint')` callback passes in an image of exactly the same width and height specified.

### Actual Behavior
Instead, it seems that with latest Electron, we get an image that is likely scaled based on the machine's display device scaling, and so is inconsistent between end user machines. We have been using the OSR as an offscreen renderer (philosophically speaking, off "screen" and not tied to a physical "screen") and so this breaks our app. It seems likely related to this PR https://github.com/electron/electron/pull/15733 and so maybe this is totally by design, but it breaks our app trying to upgrade from E3 to E5, since we actually rely on it having a consistent size that matches what we pass in to it.

I can totally see that some use cases might prefer to use the device scale, but that won't work for us. Maybe this is a half bug (it breaks our app, so it's a bug to us at least) / half feature request -- but to preserve both desired use cases, maybe there could be an option somewhere to the BrowserWindow that we can pass in to force device scale of 1 (which could work for us for the OSR)? I wasn't seeing it in the docs if there already is one. I found a command line arg that seems to force a global device scale, but generally speaking we need to preserve actual display device scale for main windows, and only use 1.0 for our OSR windows.

### To Reproduce
1. Set windows display device scaling to something not 100%
2. `electron main.js`
main.js:
```
const {app, BrowserWindow} = require('electron')

//app.disableHardwareAcceleration()

let win
app.once('ready', () => {
  win = new BrowserWindow({
    webPreferences: {
      offscreen: true,
    },
    show: false,
    transparent: true,
    width: 800,
    height: 600,
    frame: false,
  })
  win.loadURL('https://github.com/')
  win.webContents.on('paint', (event, dirty, image) => {
    console.log(' ' + image.getSize().width + 'x' + image.getSize().height);
  })
  win.webContents.setFrameRate(30)
})
```

We expect it to always print out 800x600. Instead, it may print out e.g. 1999x1502 and/or 2000x1500 at 250% display device scaling.

**Comment by electron-triage** [comment] 2020-02-19 19:05
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:16
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:16 UTC
Labels: 5-0-x, blocked/need-info ❌, bug :beetle:, platform/windows

**Comment by ejrcavenago** [comment] 2020-10-13 09:25
I can confirm that the issue is still in place with electron 10.1.2, the provided example from @vulture is still valid as well.
