### ISSUE TITLE
CrashReporter don't send data to server

### ISSUE THREAD

**Issue by popod** [electron/electron#7482] opened 2016-10-04 13:08 UTC
* Electron version: 1.4.1
* Operating system: macOS Sierra

Crash reporter do not send data. I got empty POST variable on server !

**Comment by MTRNord** [comment] 2016-10-04 14:57
Already open issue: https://github.com/electron/electron/issues/7237

**Comment by enlight** [comment] 2016-10-04 15:28
Closing this as duplicate of #7237

**Closed by enlight** 2016-10-04 15:28 UTC
