### ISSUE TITLE
scalefactor on mac retina display doesn't work correctly

### ISSUE THREAD

**Issue by kepi0809** [electron/electron#15170] opened 2018-10-15 15:21 UTC
Hi,

as the title already describes the electronScreen.getPrimaryDisplay().scaleFactor doesn't work as it should be working. It works in some cases right (macbook air 13 2017 for example) but in my case it doesn't work (Macbook pro 15 2017) with the base screen setup.

(there isn't any difference between window.devicePixelRatio)

**Comment by codebytere** [comment] 2018-10-15 15:31
@kepi0809 we require the PR template to be filled out and not deleted in order for us to begin to address bugs. Additionally, "doesn't work as it should be working" does not tell us what the issue is, how we could recreate it, or what you believe should be occurring.

**Comment by kepi0809** [comment] 2018-10-16 08:20
so scalefactor supposed to work in a way, that you multiply your values by it and then it would be the normal screen resolution. So on my mac the scaleFactor was 2 but the real scaleFactor was 1.86, I don't really know the whys I only know that it was working with that value and not 2. Now I changed my base resolution, and now it doesn't fit... So it was obviously only a static solution. I'm not sure if you could give me a solution to this, since scaleFactor is js and not really electron.

You can recreate it with retina displays -> Macbooks. (I have a Macbook pro 15 2017)
As I mentioned above, it was working on smaller retina display (13") but this depends on the screen settings. This app should be working on WinOS and Mac therefore it would be essential working it on macbooks. 

Btw thanks for the fast reply, and sorry for not being clear enough. I hope you could understand my problem now. If something is not clear just let me know :)

**Comment by jimmy-tfp** [comment] 2019-02-14 19:48
Hi,
This bug is impacting me too, what can we do remove the "blocked" tags?
Thanks.
MacBook Pro (15-inch, 2016) 
macOS 10.14.3

**Comment by codebytere** [comment] 2019-06-07 18:17
With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info! Specifically, we would need to know what versions of Electron you are using, taking into account our currently [supported versions](https://electronjs.org/docs/tutorial/support).

**Closed by codebytere** 2019-06-07 18:17 UTC
Labels: blocked/need-info ❌, platform/macOS

**Comment by jimmy-tfp** [comment] 2019-11-20 22:39
Hi,

This is happening with the latest Electron 6.1.4 on my MacBook Pro (15-inch, 2018) running 10.15.1.

What else can I do to get this opened?

Thanks,
Jimmy

**Comment by kepi0809** [comment] 2019-11-21 10:43
@jimmy-tfp the best thing you could do is make a reproduction public repo and open a new ticket, it has been a long time ago and we could find a workaround, so it doesn't affect me anymore. You could even link this issue in your new issue.

Wish you good luck!

**Comment by dimafet001** [comment] 2021-09-27 22:48
Same issue. Macbook Air 2020 M1 13" on MacOS Big Sur 11.5.2. **Default scale.** The screen (screenshotting tool) shows twice less pixels than Electron.

{
[1]   screen: [
[1]     {
[1]       id: 2,
[1]       bounds: [Object],
[1]       workArea: [Object],
[1]       accelerometerSupport: 'unknown',
[1]       monochrome: false,
[1]       colorDepth: 24,
[1]       colorSpace: '{primaries:BT709, transfer:BT709_APPLE, matrix:RGB, range:FULL}',
[1]       depthPerComponent: 8,
[1]       size: [Object],
[1]       displayFrequency: 59,
[1]       workAreaSize: [Object],
[1]       scaleFactor: 2,
[1]       rotation: 0,
[1]       internal: false,
[1]       touchSupport: 'unknown'
[1]     }
[1]   ]
[1] }

**Comment by dimafet001** [comment] 2021-09-28 04:54
Checked it with a different library. Scale factors are still the same. They just work weirdly on mac.
