### ISSUE TITLE
process.stdout no longer output logs to terminal in renderer process

### ISSUE THREAD

**Issue by jwu** [electron/electron#5051] opened 2016-04-06 10:13 UTC
* Electron version: v0.37.3, v0.37.4
* Operating system: Mac OSX

This starts from 0.37.3, I used to output renderer console logs to terminal through `process.stdout.write`, it works very well in v0.37.2 and v0.36.*, but since v0.37.3 and the version above, it will not output my text to terminal, is this an expect behaviour or just a bug?

**Comment by zcbenz** [comment] 2016-04-07 13:21
It seems to be caused by the upgrade of Node. But you should not rely on this behavior any way, it totally depends on Node and does not work on certain platforms.

I suggest hooking `process.stdout.write` and send the output to the main process to print. I'm closing this as won't fix.

**Closed by zcbenz** 2016-04-07 13:21 UTC

**Comment by marton78** [comment] 2016-04-26 11:52
This might be related to my problem so I won't open a new issue:

We develop an Electron app with a native node addon (written in C++, compiled with node-gyp). Since Electron v0.37, the native addon's output is not printed to stdout any more, which makes debugging it very difficult. Is there any way to restore the old behaviour?

**Comment by zcbenz** [comment] 2016-04-27 01:06
@marton78 It should be some change in Node or libuv caused this, so there must be a way to revert that. I would be very happy to accept a PR to restore the old behavior, but we are not going to do it ourselves.

**Comment by rahatarmanahmed** [comment] 2016-06-18 19:46
@zcbenz This doesn't seem to be caused by a change in Node. Here's the `process.versions` of the two versions before and after the break:

### Electron v0.37.2 process.versions

```json
{
  "http_parser": "2.6.0",
  "node": "5.1.1",
  "v8": "4.9.385.28",
  "uv": "1.7.5",
  "zlib": "1.2.8",
  "ares": "1.10.1-DEV",
  "modules": "47",
  "openssl": "1.0.2e",
  "electron": "0.37.2",
  "atom-shell": "0.37.2",
  "chrome": "49.0.2623.75"
}
```

### Electron v0.37.2 process.versions

```json
{
  "http_parser": "2.6.0",
  "node": "5.1.1",
  "v8": "4.9.385.28",
  "uv": "1.7.5",
  "zlib": "1.2.8",
  "ares": "1.10.1-DEV",
  "modules": "47",
  "openssl": "1.0.2e",
  "electron": "0.37.3",
  "atom-shell": "0.37.3",
  "chrome": "49.0.2623.75"
}
```

The only thing that changed between these two versions was electron.

The bug is a bit of a minor inconvenience since you can work around it by sending ipc messages to the main process, but it'd be nice to have this fixed.

**Comment by rahatarmanahmed** [comment] 2016-06-18 20:24
Further investigation leads me to this commit: https://github.com/electron/node/commit/d6bccdb1a108ff99a5a7b572e88f7e40c58c1cd9. I guess it's failing to create the write stream and fallsback to a stream that writes to nothing. I don't know how to debug and step through node core so I'm not sure why it fails.
