### ISSUE TITLE
window.show() on current desktop

### ISSUE THREAD

**Issue by pronebird** [electron/electron#8734] opened 2017-02-22 19:41 UTC
MacOS supports multiple desktops. I show window when user taps on tray icon and hide it when user clicks somewhere else. Is there any way to show window on current desktop? 

Using `setVisibleOnAllWorkspaces` makes window visible on all desktops but calls to `window.show` still cause switch to the desktop where the window was initially created/displayed. 

I know I could re-create window each time, but that's slow. Would be awesome to have a method like `BrowserWindow.showOnCurrentDesktop()` or something like that. Not sure I can patch it externally without patching Electron/Atom.

* Electron version: 1.6.0
* Operating system: macOS Sierra

**Comment by leethomas** [comment] 2017-02-24 15:17
This should be pretty doable. I'll take this one if no one minds.

**Comment by dkfiresky** [comment] 2017-02-24 16:27
How about extending the [Screen API](http://electron.atom.io/docs/api/screen/) to get current active monitor and then feed it's `id` to the `BrowserWindow.showOnMonitor(id)` somehow? 😀

**Comment by pronebird** [comment] 2017-02-24 16:32
@dkfiresky are those screens actual physical screens or workspaces (desktops)?

**Comment by dkfiresky** [comment] 2017-02-24 18:48
@pronebird I believe that's a physical display API, but I may be wrong.
You can find the source [here](https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_screen.cc)

**Comment by dkfiresky** [comment] 2017-02-24 18:50
There is also [a Display Object](http://electron.atom.io/docs/api/structures/display/#display-object) structure, which contains `id Number - Unique identifier associated with the display.`.

**Comment by pronebird** [comment] 2017-02-24 19:00
I think I have to clarify that I was talking about moving window between spaces or desktops, not different physical displays. While searching on internet I found that moving windows between desktops is a part of private API. However It's possible to specify a window behavior `window.collectionBehavior = NSWindowCollectionBehavior.MoveToActiveSpace`.

>MoveToActiveSpace
>Making the window active does not cause a space switch; the window switches to the active space.

Another option is that seems to be already implemented:

>CanJoinAllSpaces
>The window appears in all spaces. The menu bar behaves this way.

So I guess a combination of both should give desired effect.

**Comment by dkfiresky** [comment] 2017-02-24 19:01
@pronebird you can actually try to implement something like this:
```
const win = new BrowserWindow();
....
win.hide();
....
// Get mouse cursor absolute position
const {x, y} = screen.getCursorScreenPoint();
// Find the display where the mouse cursor will be
const currentDisplay = screen.getDisplayNearestPoint({ x, y });
// Set window position to that display coordinates
win.setPosition(currentDisplay. workArea.x, currentDisplay. workArea.y);
// Center window relatively to that display
win.center();
// Display the window
win.show();
```

**Comment by dkfiresky** [comment] 2017-02-24 19:10
@pronebird 
> So I guess a combination of both should give desired effect.

You can't use both collection behaviors.

**Comment by pronebird** [comment] 2017-02-24 19:13
@dkfiresky you mean those two are mutually exclusive? Otherwise NSWindowCollectionBehavior looks like a mask to me, reference:

https://github.com/electron/electron/blob/1dd37eaab71a8a64d1f68fb88622ac3e2a31bc4a/atom/browser/native_window_mac.mm#L704

**Comment by pronebird** [comment] 2017-02-24 19:46
@dkfiresky in swift you have to use let behavior: NSWindowcollectionBehavior = [.canJoinAllSpaces, .moveToActiveSpace];

**Comment by MarshallOfSound** [comment] 2017-02-26 06:41
I believe this is a duplicate of #5362

**Closed by MarshallOfSound** 2017-02-26 06:41 UTC
Labels: triage/enhancement

**Comment by lsegal** [comment] 2017-12-08 01:28
As a workaround, this hack might work in your use case:

```
win.setVisibleOnAllWorkspaces(true); // put the window on all screens
win.focus(); // focus the window up front on the active screen
win.setVisibleOnAllWorkspaces(false); // disable all screen behavior
```

**Comment by pronebird** [comment] 2017-12-08 10:44
@lsegal thanks! It works better on Electron 1.7.9 and doesn't switch to the primary workspace anymore but the window disappears upon transition to new workspace.

**Comment by vojtabohm** [comment] 2024-07-17 21:41
I modified ghost's code to work in the latest version of Electron (not sure why the center function did not work, maybe because of negative coordinate space).

```
  // Get mouse position
  const { x, y } = screen.getCursorScreenPoint();
  // Find the display where the mouse cursor is
  const currentDisplay = screen.getDisplayNearestPoint({ x, y });
  // Center window relatively to that display
  const centerX = Math.round((currentDisplay.workArea.width - mainWindow.getBounds().width) / 2);
  const centerY = Math.round((currentDisplay.workArea.height - mainWindow.getBounds().height) / 2);
  mainWindow.setPosition(currentDisplay.workArea.x + centerX, currentDisplay.workArea.y + centerY);
  ```
  
  This works nicely. Positions the window on any external display where the mouse is (which we can safely assume is where the user expects it).
