### ISSUE TITLE
utilityProcess.fork() crashes before app ready

### ISSUE THREAD

**Issue by jtbandes** [electron/electron#44461] opened 2024-10-29 19:03 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.2

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sequoia 15.1 (24B83)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

`utilityProcess.fork()` should work or fail with a catchable error.

### Actual Behavior

If `utilityProcess.fork` is called before the app is ready, the whole app crashes with SIGSEGV.

### Testcase Gist URL

https://gist.github.com/jtbandes/af5c08cc25c8a75b16aeffae5d120778

### Additional Information

The stack trace from macOS is:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Electron [62194]
Path:                  /Users/USER/Desktop/*/Electron.app/Contents/MacOS/Electron
Identifier:            com.github.Electron
Version:               33.0.2 (33.0.2)
Code Type:             ARM-64 (Native)
Parent Process:        Exited process [62193]
Responsible:           Terminal [1439]
User ID:               502

Date/Time:             2024-10-29 12:02:05.4395 -0700
OS Version:            macOS 15.1 (24B83)
Report Version:        12
Anonymous UUID:        5C690097-B082-371F-F115-8F762A2B4BB6

Sleep/Wake UUID:       A864BE94-F4E3-4884-BBF3-1ABAACF04E81

Time Awake Since Boot: 61000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000100
Exception Codes:       0x0000000000000001, 0x0000000000000100

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [62194]

VM Region Info: 0x100 is not in any region.  Bytes before following region: 4307123968
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100b98000-100b9c000    [   16K] r-x/r-x SM=COW  /Users/USER/Desktop/*/Electron.app/Contents/MacOS/Electron

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Electron Framework            	       0x10a44848c v8::CodeEvent::GetComment() + 118216
1   Electron Framework            	       0x10a3afe90 v8::CpuProfileNode::GetDeoptInfos() const + 197828
2   Electron Framework            	       0x10a3b1c3c v8::CpuProfileNode::GetDeoptInfos() const + 205424
3   Electron Framework            	       0x10a3657d0 v8::internal::ThreadIsolation::WriteProtectMemory(unsigned long, unsigned long, v8::PageAllocator::Permission) + 236996
4   Electron Framework            	       0x10a3b2bb4 v8::CpuProfileNode::GetDeoptInfos() const + 209384
5   Electron Framework            	       0x10a3b2a80 v8::CpuProfileNode::GetDeoptInfos() const + 209076
6   ???                           	       0x157e0f58c ???
7   ???                           	       0x157e0d45c ???
8   ???                           	       0x157e0df34 ???
9   ???                           	       0x157f98de4 ???
10  ???                           	       0x157e0d45c ???
11  ???                           	       0x157e0d45c ???
12  ???                           	       0x157e0d45c ???
13  ???                           	       0x157e0d45c ???
14  ???                           	       0x157e0d45c ???
15  ???                           	       0x157e0d45c ???
16  ???                           	       0x157e0d45c ???
17  ???                           	       0x157e0d45c ???
18  ???                           	       0x15000ba88 ???
19  ???                           	       0x157e0b088 ???
20  ???                           	       0x157e0acd4 ???
21  Electron Framework            	       0x10b697168 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) + 720
22  Electron Framework            	       0x10b57e6c8 v8::Function::Call(v8::Isolate*, v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 372
23  Electron Framework            	       0x1114132fc node::loader::ModuleWrap::SyntheticModuleEvaluationStepsCallback(v8::Local<v8::Context>, v8::Local<v8::Module>) + 472
24  Electron Framework            	       0x10ba8f120 v8::Platform::SystemClockTimeMillis() + 2211296
25  Electron Framework            	       0x10ba3a0f4 v8::Platform::SystemClockTimeMillis() + 1863092
26  Electron Framework            	       0x10b56ddc4 v8::Module::Evaluate(v8::Local<v8::Context>) + 484
27  Electron Framework            	       0x111414b24 node::loader::ModuleWrap::Evaluate(v8::FunctionCallbackInfo<v8::Value> const&) + 1216
28  ???                           	       0x157e0f58c ???
29  ???                           	       0x157e0d45c ???
30  ???                           	       0x157e4dba8 ???
31  ???                           	       0x157f24d58 ???
32  ???                           	       0x157e3c83c ???
33  ???                           	       0x157e0af54 ???
34  Electron Framework            	       0x10b697f30 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) + 4248
35  Electron Framework            	       0x10b698ce4 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) + 7756
36  Electron Framework            	       0x10b698e38 v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) + 8096
37  Electron Framework            	       0x10b6c621c v8::Unwinder::PCIsInV8(unsigned long, v8::MemoryRange const*, void*) + 193412
38  Electron Framework            	       0x1113b4b84 node::CallbackScope::~CallbackScope() + 948
39  Electron Framework            	       0x1113b484c node::CallbackScope::~CallbackScope() + 124
40  Electron Framework            	       0x1114f0d28 fontations_ffi$cxxbridge1$BridgeOutlineCollection$operator$sizeof + 346736
41  Electron Framework            	       0x1114efcd4 fontations_ffi$cxxbridge1$BridgeOutlineCollection$operator$sizeof + 342556
42  Electron Framework            	       0x10a31476c uv_async_send + 1168
43  Electron Framework            	       0x10a325254 uv_free_interface_addresses + 1964
44  Electron Framework            	       0x10a314c38 uv_run + 376
45  Electron Framework            	       0x10a4ae6e0 node::FreeArrayBufferAllocator(node::ArrayBufferAllocator*) + 18280
46  Electron Framework            	       0x10a40e184 v8::BackingStore::MaxByteLength() const + 66772
47  Electron Framework            	       0x10c6a1ff8 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 6522844
48  Electron Framework            	       0x10c6a523c v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 6535712
49  Electron Framework            	       0x10c6a19c8 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(v8::internal::compiler::MapRef, v8::internal::compiler::MapRef, v8::internal::InternalIndex, v8::internal::compiler::ObjectRef) const + 6521260
50  Electron Framework            	       0x10a66d738 v8::CodeEvent::GetScriptLine() + 463080
51  Electron Framework            	       0x10a66e6fc v8::CodeEvent::GetScriptLine() + 467116
52  Electron Framework            	       0x10a66e57c v8::CodeEvent::GetScriptLine() + 466732
53  Electron Framework            	       0x10a66cf9c v8::CodeEvent::GetScriptLine() + 461132
54  Electron Framework            	       0x10a66d084 v8::CodeEvent::GetScriptLine() + 461364
55  Electron Framework            	       0x10a32593c ElectronMain + 204
56  dyld                          	       0x197380274 start + 2840

[removed the rest for brevity]
```

**Comment by codebytere** [comment] 2024-10-30 10:50
Duplicate of https://github.com/electron/electron/issues/41396

**Closed by codebytere** 2024-10-30 10:50 UTC
Labels: platform/macOS, bug :beetle:, has-repro-gist, 33-x-y
