### ISSUE TITLE
Loading a large image in a webview will cause a renderer crash

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#1562] opened 2015-05-03 19:17 UTC
1. Create a page with a WebView
1. Load http://images3.wikia.nocookie.net/__cb20130920075004/zombieclan/images/7/79/Untitled-5.jpg in the page
1. :boom:

Didn't seem like there was anything in particular in the Chromium bug tracker, I'll try to get a crash stack

**Comment by zcbenz** [comment] 2015-05-04 05:45
Following code seems to work fine, I'm wondering if it is caught by other reasons:

```js
var w = new WebView;
w.src = 'http://images3.wikia.nocookie.net/__cb20130920075004/zombieclan/images/7/79/Untitled-5.jpg';
document.body.appendChild(w);
```

**Comment by paulcbetts** [comment] 2015-05-04 16:46
We're already probably using a ton of memory, I can get you a crash dump of the webview process if that helps

**Comment by paulcbetts** [comment] 2015-05-04 16:47
You can also repro that by opening the Slack Windows app, drop in the link, then open the lightbox. We've also seen it with giant (~90MB+) animated GIFs

**Comment by zcbenz** [comment] 2015-10-30 03:59
It seems that this problem has been worked around, or been fixed in later Chrome upgrades.

**Comment by AndreySudarchikov** [comment] 2016-02-29 22:05
Hi! i have a same issue, large images makes Crash renderer process
to reproduce it simple open new browser window with image tag which has more than 7000x3500px and over 20mb 
Windows 7, Windows 10 platform, 0.36.9 electron
open such images on a regular Chrome is ok, and works fine.
but Electron fire renderer window crash event and close it

Thanks in advance

**Comment by MrSaints** [comment] 2016-04-08 10:24
This doesn't seem to be an issue on OSX, but it's definitely an issue on Linux.

**Comment by zcbenz** [comment] 2016-06-22 00:29
Unable to reproduce with the example in #4639 anymore.

**Closed by zcbenz** 2016-06-22 00:29 UTC
Labels: bug, webview, windows

**Comment by taigrr** [comment] 2017-09-12 00:56
Is still an issue on Linux.

**Comment by mduclehcm** [comment] 2020-05-21 04:26
Is still an issue on 32bit build. WebContent crashed every time display a large image.
