### ISSUE TITLE
scale factor error in webview/webcontents.capturePage

### ISSUE THREAD

**Issue by mattgalvin** [electron/electron#8314] opened 2016-12-30 17:37 UTC
* Electron version: 1.4.13
* Operating system: MacOS 10.12.2 running on MacBook Pro (Retina, 13-inch, Early 2015)

### Expected behavior
webview.capturePage() without specifying a dimension should return an image with the full viewable area on a Retina display. The dimensions of the resulting image should be either the actual pixels of the viewable area or perhaps the actual pixels * the device scale factor.

Specifying a dimension should return the viewable area of that dimension with the resulting image being sized correctly (and consistently with the use case of no rect specified).

### Actual behavior
Calling webview.capturePage() without specifying a dimension returns in image that is the pixel size of the viewable area * the scale factor the area covered by the viewable area divided by the scale factor.

For example, on a webview that is 524 pixels wide, the resulting image of capturePage() is 1048 pixels wide, but only contains the image data from the first 262 pixels. That image is then upsized by the scale factor twice to get to the 1048 width. Not only does this not capture the full viewable page, it also introduces significant scaling artifacts.

Similar results occur if a rect is specified to capturePage.

### How to reproduce

On a Retina display, create a page with a webview that loads some web site:
`<webview id="webview" src="http://www.msn.com/" ></webview>`

Capture the page:
```
// used to get the viewable dimensions of the webview
function getWebviewMeta(cb) {
    var code = "var r = {}; \
        r.totalHeight = document.body.offsetHeight; \
        r.pageHeight = window.innerHeight; \
        r.pageWidth = window.innerWidth; \
        r;";
    webview.executeJavaScript(code, false, function(r) {
        let webviewMeta = {};
        webviewMeta.captureHeight = r.pageHeight;
        webviewMeta.captureWidth = r.pageWidth;
        cb(webviewMeta);
    });
}

getWebviewMeta(function(webviewMeta) {
    let captureRect = {
        x: 0, y: 0,
        width: webviewMeta.captureWidth,
        height: webviewMeta.captureHeight
    };

    webview.capturePage((img) => {
        console.log("image size: ", img.getSize());
        let jpgFile = img.toJPEG(90);
        // save file as testDefault.jpg, I used jetpack.writeAsync
    });

    webview.capturePage(captureRect, (img) => {
        console.log("image size: ", img.getSize());
        let jpgFile = img.toJPEG(90);
        // save file as testSetViewSize.jpg, I used jetpack.writeAsync
    });

    captureRect.width = +captureRect.width * electron.screen.getPrimaryDisplay().scaleFactor;
    captureRect.height = +captureRect.height * electron.screen.getPrimaryDisplay().scaleFactor;

    webview.capturePage(captureRect, (img) => {
        console.log("image size: ", img.getSize());
        let jpgFile = img.toJPEG(90);
        // save file as testScaled.jpg, I used jetpack.writeAsync
    });
});
```

The first two results, testDefault.jpg and testSetViewSize.jpg will be identical. They will be captureRect * scale factor in size but will only contain captureRect / scale factor from the webview.

The third result, testScaled.jpg, will contain the captureRect data from the webview but will be captureRect * scale factor * scale factor in size.

All images have upscaling artifacts in them.

### Note
On non-retina displays (where the scale factor is 1), capturePage works as expected.

Also, using webview.capturePage or webview.getWebContents().capturePage makes no difference. It also does not matter if the code is executed in the main or renderer process. I wouldn't expect there to be a difference in either, but I did test both to make sure.

I have a discussion started about this but decided to enter an issue here because I believe there is a bug in how the scale factor is used. https://discuss.atom.io/t/webview-capturepage-doesnt-capture-full-page-on-retina-display/37560

**Comment by jarek-foksa** [comment] 2017-01-08 18:29
Chrome's [webview.captureVisibleRegion()](https://developer.chrome.com/apps/tags/webview#method-captureVisibleRegion) API also appears to be affected by the same bug.

**Comment by zeke** [comment] 2017-02-08 19:45
cc @li-xinyang and @abnerlee who opened similar issues.

I am able to reproduce this on macOS (with a retina display) using Electron 1.4, 1.5, and 1.6.

From the [contents.capturePage docs](http://electron.atom.io/docs/api/web-contents/#contentscapturepagerect-callback): 

> Omitting rect will capture the whole visible page.

Issues #8586 and #8587 both included a `rect` argument in their repro example, so I thought maybe that was the problem. But no, the problem exists even if the `rect` is omitted:

```
const webContents = remote.getCurrentWebContents()
const filename = path.join(__dirname, 'screenshot.png')
webContents.capturePage((img) => {
  fs.writeFileSync(filename, img.toPng())
  shell.openItem(filename)
})
```


@li-xinyang and @abnerlee: are you on retina (or some other high resolution) screens?

**Comment by zeke** [comment] 2017-02-08 19:46
> Chrome's webView.captureVisibleRegion() API also appears to be affected by the same bug.

@jarek-foksa.. but given the name of the API, shouldn't it do exactly that? Capture the "visible" region?

**Comment by jarek-foksa** [comment] 2017-02-08 22:09
@zeke Yes, Chrome's API captures the visible region, but the resulting image is cut off as described by @mattgalvin. Therefore, I suspect this might be upstream bug.

**Comment by li-xinyang** [comment] 2017-02-09 01:27
@zeke Yes, I am using the new MacBook Pro which has a retina display.

**Comment by peerbolte** [comment] 2017-02-09 08:22
I'm experiencing the same issues on my MacBook Pro retina. This results in different behaviour when using my application on retina and non-retina.

**Comment by peerbolte** [comment] 2017-04-12 15:34
Is there an update on this issue? Is this something that has to be fixed upstream in Chrome?

**Comment by RonAtPyramid** [comment] 2017-04-18 16:19
anyone?

**Comment by asafbe** [comment] 2017-04-19 08:05
Our code also affected by this issue. Is someone currently working on this? any known solution? Thx

**Comment by Marais** [comment] 2017-04-19 08:11
Our code is also affected by this

**Comment by guyalizi** [comment] 2017-04-19 08:32
Our code is also affected by this

**Comment by ronalb** [comment] 2017-04-19 08:41
I'm trying to capture page which is bigger then the page size, I tried to create bigger web page
but nothing works.it seems electron "knows" my screen size .
 btw in phantomjs this feature is working.
any solution? anyone?

**Comment by mattgalvin** [comment] 2017-04-19 12:42
The issue still happens for me, but I have code implemented that works around the issue in a reliable manner - our application has been in production for a couple of months. I am tied up for most of the day but I will try and get sample working code posted for you guys this afternoon.

**Comment by matan-dr** [comment] 2017-04-20 07:11
this issue also happens to me , does anyone has an a workaround solution till this issue will be solved?

**Comment by mattgalvin** [comment] 2017-04-21 01:53
Hey guys, I apologize for the delayed response. So here is some code from our application that we are using to capture the page. This code is running on Windows 10, Linux Mint Debian Edition, non-retina Macs, and retina MacBooks. This is essentially the 3rd scenario from my original post on this issue - _the root issue is still present, but can be managed_. We have just accepted that the captured jpeg on retina displays will have a higher image resolution than expected but we have found that the quality of the image is acceptable. In our case, the application is being used for digital evidence preservation so we opted to keep the raw captured image. However, if you want the resulting image to be the expected dimensions you would resize it down by scaleFactor.

Please note that I ripped out the pertinent code from our application and had to sanitize it quite a bit as it is a closed source application. As such, this code as it's copied here is not running exactly as is - it's meant to just show what we're doing.

The code is currently running against Electron v1.4.15 in production and v1.6.5 in dev.

```
// webview is the WebView element in my html page

// Injects javascript into the webview page in order to determine the viewable window height
function getWebviewMeta(cb) {
    var code = "var r = {}; \
        r.pageHeight = window.innerHeight; \
        r.pageWidth = window.innerWidth; \
        r;";
    webview.executeJavaScript(code, false, function (r) {
        let webviewMeta = {};
        webviewMeta.captureHeight = r.pageHeight;
        webviewMeta.captureWidth = r.pageWidth;
        cb(webviewMeta);
    });
}

// Creates an image of the visible area of the WebView
function captureWeb() {
    getWebviewMeta(function (webviewMeta) {

        // builds a rectangle whose dimensions are scaled based on the display scale factor
        // this rectangle represents the scaled viewable window in the Electron application for the WebView
        let captureRect = {
            x: 0,
            y: 0,
            width: +webviewMeta.captureWidth * electron.screen.getPrimaryDisplay().scaleFactor,
            height: +webviewMeta.captureHeight * electron.screen.getPrimaryDisplay().scaleFactor
        };

        webview.capturePage(captureRect, (img) => {
            if (img.isEmpty()) {
                // DIDN’T CAPTURE
                // NOTE - in my application we are manually scrolling the view and timing of the record
                // is an issue - sometimes the captured image is empty, we delay a few hundred ms
                // and capture again
            } else {
                // SAVE YOUR JPEG FILE
                let jpgFile = img.toJPEG(90);

                // If you want the image size to be the expected pixel resolution, resize it by scaleFactor:
                let resizedImg = img.resize({width : img.getSize().width / electron.screen.getPrimaryDisplay().scaleFactor});
                let resizedJpgFile = resizedImg.toJPEG(90);
            }
        });
    });
}
```

**Comment by iammugik** [comment] 2017-10-11 10:27
This issue actual for me, does it will fixed?

**Comment by iver56** [comment] 2018-01-12 16:11
Note that in the code snippet that @mattgalvin provided there's a chance that captureRect.width and captureRect.height become "non-integer" floats. If f.ex. `captureRect.width` is `3120.5`, then an exception may be raised because integers are expected.

To fix this, I replaced

```
      let captureRect = {
        x: 0,
        y: 0,
        width: +webviewMeta.captureWidth * electron.screen.getPrimaryDisplay().scaleFactor,
        height: +webviewMeta.captureHeight * electron.screen.getPrimaryDisplay().scaleFactor
      };
```

with

```
      let captureRect = {
        x: 0,
        y: 0,
        width: parseInt(webviewMeta.captureWidth * electron.screen.getPrimaryDisplay().scaleFactor),
        height: parseInt(webviewMeta.captureHeight * electron.screen.getPrimaryDisplay().scaleFactor)
      };
```

**Comment by codebytere** [comment] 2018-09-24 04:39
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 04:39 UTC
Labels: bug :beetle:, platform/macOS, version/1.6.x

**Comment by pabloleban** [comment] 2018-10-06 21:32
This still happens on > 2.x.x

**Comment by iamapig120** [comment] 2019-01-24 03:57
> We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

It still happens on 2.0.16

**Comment by operapreneur** [comment] 2019-03-04 01:05
I followed a couple of issues to this thread and the above, while helpful, didn't necessarily solve the original issue that got me here:

> webContents.capturePage take a screenshot of the complete webpage

In my example, I am opening an offscreen BrowserWindow and enabling the window to be larger than the screen through the following BrowserWindow([options]): `enableLargerThanScreen: true`

Execute Javascript on the webContents to return the `document.body.offsetHeight`

Before executing the capturePage method, resize the BrowserWindow with `win.setContentSize()` using the page's offsetHeight result.

I haven't used this in production but this is returning a complete webpage.

**Comment by jacklovepdf** [comment] 2019-03-17 13:31
> I followed a couple of issues to this thread and the above, while helpful, didn't necessarily solve the original issue that got me here:
> 
> > webContents.capturePage take a screenshot of the complete webpage
> 
> I found a fix by opening an offscreen BrowserWindow and enabling the window to be larger than the screen through the following BrowserWindow([options]): `enableLargerThanScreen: true`
> 
> Execute Javascript on the webContents to return the `document.body.offsetHeight`
> 
> Before executing the capturePage method, resize the BrowserWindow with `win.setContentSize()` using the page's offsetHeight result.
> 
> I haven't used this in production but this is returning a complete webpage.

it's seems  an indirect way to solved the problem.

**Comment by futurist** [comment] 2019-03-21 06:37
> > I followed a couple of issues to this thread and the above, while helpful, didn't necessarily solve the original issue that got me here:
> > > webContents.capturePage take a screenshot of the complete webpage
> > 
> > 
> > I found a fix by opening an offscreen BrowserWindow and enabling the window to be larger than the screen through the following BrowserWindow([options]): `enableLargerThanScreen: true`
> > Execute Javascript on the webContents to return the `document.body.offsetHeight`
> > Before executing the capturePage method, resize the BrowserWindow with `win.setContentSize()` using the page's offsetHeight result.
> > I haven't used this in production but this is returning a complete webpage.
> 
> it's seems an indirect way to solved the problem.

Can this work around method be tested and merged?

**Comment by jacklovepdf** [comment] 2019-03-21 09:26
> > > I followed a couple of issues to this thread and the above, while helpful, didn't necessarily solve the original issue that got me here:
> > > > webContents.capturePage take a screenshot of the complete webpage
> > > 
> > > 
> > > I found a fix by opening an offscreen BrowserWindow and enabling the window to be larger than the screen through the following BrowserWindow([options]): `enableLargerThanScreen: true`
> > > Execute Javascript on the webContents to return the `document.body.offsetHeight`
> > > Before executing the capturePage method, resize the BrowserWindow with `win.setContentSize()` using the page's offsetHeight result.
> > > I haven't used this in production but this is returning a complete webpage.
> > 
> > 
> > it's seems an indirect way to solved the problem.
> 
> Can this work around method be tested and merged?
It's good idea, i have an other solution to solve the problem.

**Comment by operapreneur** [comment] 2019-03-25 16:46
I should have added that my method is a ***workaround*** - it's not something that I think should be merged. 

It seems the method `webContents.capturePage` should have some clarification since it seems most developers expect it to capture the full page length instead of what's visible in the viewport.

I have yet to try [Puppeteer's full-page screenshot](https://pptr.dev/#?product=Puppeteer&version=v1.13.0&show=api-pagescreenshotoptions) method but this sounds like what developers are looking for in Electron: `page.screenshot([fullPage: true])`

**Comment by karlitos** [comment] 2020-09-16 21:09
If someone would be interested in code of the workaround:

```javascript
let offscreenRenderer;

const exportToPNG = async () => {
    try {
        const pageRect = await BrowserView.fromId(2).webContents.executeJavaScript(
            `(() => { return {x: 0, y: 0, width: document.body.offsetWidth, height: document.body.offsetHeight}})()`);

        offscreenRenderer = new BrowserWindow({
            enableLargerThanScreen: true,
            show: false,
            webPreferences: {
                offscreen: true,
                nodeIntegration: false, // is default value after Electron v5
                contextIsolation: true, // protect against prototype pollution
                enableRemoteModule: false, // turn off remote
            }
        });
        
        offscreenRenderer.setContentSize(pageRect.width, pageRect.height);
        await offscreenRenderer.loadURL('http://foo/bar/baz');
        const screenshot = await offscreenRenderer.webContents.capturePage(pageRect);
        await fs.promises.writeFile('some/path/filename.png', screenshot.toPNG());
    } catch (err) { 
        console.error(err)
    } finally {
        if (offscreenRenderer && !offscreenRenderer.isDestroyed()) {
            offscreenRenderer.destroy();
        }
}
```

You can use a callback for the `paint` event:

````javascript
    offscreenRenderer.webContents.on('paint', (evt, dirtyRect, image) => {
        fs.writeFile('some/path/filename.png', image.toPNG(), (err) => {
            if (err) throw err;
        });
    });
````

but I also do export to PDF and other formats and found it difficult to convert the callback to Promise-resolving (using Deferred maybe ?)

And no guarantee, that the `offscreenRenderer` will be properly destroyed and the code does not cause any memory leaks. Correct me please if I am wrong.

**Comment by Aaronphy** [comment] 2021-09-08 09:44
> If someone would be interested in code of the workaround:
> 
> ```js
> let offscreenRenderer;
> 
> const exportToPNG = async () => {
>     try {
>         const pageRect = await BrowserView.fromId(2).webContents.executeJavaScript(
>             `(() => { return {x: 0, y: 0, width: document.body.offsetWidth, height: document.body.offsetHeight}})()`);
> 
>         offscreenRenderer = new BrowserWindow({
>             enableLargerThanScreen: true,
>             show: false,
>             webPreferences: {
>                 offscreen: true,
>                 nodeIntegration: false, // is default value after Electron v5
>                 contextIsolation: true, // protect against prototype pollution
>                 enableRemoteModule: false, // turn off remote
>             }
>         });
>         
>         offscreenRenderer.setContentSize(pageRect.width, pageRect.height);
>         await offscreenRenderer.loadURL('http://foo/bar/baz');
>         const screenshot = await offscreenRenderer.webContents.capturePage(pageRect);
>         await fs.promises.writeFile('some/path/filename.png', screenshot.toPNG());
>     } catch (err) { 
>         console.error(err)
>     } finally {
>         if (offscreenRenderer && !offscreenRenderer.isDestroyed()) {
>             offscreenRenderer.destroy();
>         }
> }
> ```
> 
> You can use a callback for the `paint` event:
> 
> ```js
>     offscreenRenderer.webContents.on('paint', (evt, dirtyRect, image) => {
>         fs.writeFile('some/path/filename.png', image.toPNG(), (err) => {
>             if (err) throw err;
>         });
>     });
> ```
> 
> but I also do export to PDF and other formats and found it difficult to convert the callback to Promise-resolving (using Deferred maybe ?)
> 
> And no guarantee, that the `offscreenRenderer` will be properly destroyed and the code does not cause any memory leaks. Correct me please if I am wrong.

I think this indirect way can only solve the non-interactive webpage  case
