### ISSUE TITLE
Electron Crash on Windows

### ISSUE THREAD

**Issue by bennyn** [electron/electron#7283] opened 2016-09-21 08:44 UTC
- Electron version: 1.2.8
- Operating system: Windows 10 Home

Our Electron-based app (`Wire.exe`) crashed on Windows. I have the symbols server setup in Visual Studio but it was unable to find the `atom_bindings.cc`. Can you help me providing better feedback?

**Screenshot**

![Screenshot](https://cloud.githubusercontent.com/assets/469989/18703937/464a9994-7fe8-11e6-8561-4d4c2bfeb61e.PNG)

**Comment by zcbenz** [comment] 2016-09-26 03:32
The crash happened in the `crashed` event handler of `WebContents`, are you doing anything special there?

**Comment by bennyn** [comment] 2016-09-26 09:37
We reload the `BrowserWindow` on `crashed`:

```coffee
  main = new BrowserWindow({
    'titleBarStyle': 'hidden-inset',
    'title': config.NAME,
    'width': config.DEFAULT_WIDTH_MAIN,
    'height': config.DEFAULT_HEIGHT_MAIN,
    'minWidth': config.MIN_WIDTH_MAIN,
    'minHeight': config.MIN_HEIGHT_MAIN,
    'show': false,
    'autoHideMenuBar': false,
    'icon': path.join(app.getAppPath(), 'img', 'wire.ico'),
    'webPreferences': {
      'nodeIntegration': false,
      'preload': PRELOAD_JS
    }
  });

  main.webContents.on('crashed', function() {
    main.reload();
  });
```

**Comment by zcbenz** [comment] 2016-09-27 12:20
Do you have code calling `process.crash` in your app? From the stack trace the crash seems to be caused by an `process.crash()` call.

**Comment by lipis** [comment] 2016-09-27 16:19
@zcbenz [No we don't](https://github.com/wireapp/wire-desktop/search?utf8=%E2%9C%93&q=crash). As already mentioned at the moment we just reloading when the [`webContents` crashes](https://github.com/wireapp/wire-desktop/blob/master/electron/main.js#L221-L223).

**Comment by zcbenz** [comment] 2016-10-03 08:03
It is also possible that a fatal V8 error happened, the error information would be printed to console when you run the app under command line.

**Comment by webdesus** [comment] 2017-03-10 17:18
This situations happen for me in next cases:

Firts:

```javascript
// call C function and send callback argument
fun_call_c_code('test', (err, result)=>{
    console.log(jjjj);
})
```

Second:

```javascript
fun_call_c_code('test', (err, result)=>{
    jjjj = 5; //if write let jjjj = 5 or  var jjjj = 5 all work perfect.
})
```

I think when C code call js callback function, this function run inside scope without write access. When we tryid get access to undefined variable process trying create this variable in scope with value undefined. But we do not have rights. 

I using [node-ffi](https://github.com/node-ffi/node-ffi) for calls C codes. 

@zcbenz I run from console, but not see error information.

**Comment by zcbenz** [comment] 2017-05-30 10:13
I'm closing this since it is impossible to solve the problem with the very limited. information.

**Closed by zcbenz** 2017-05-30 10:13 UTC
Labels: more-information-needed
