### ISSUE TITLE
[Bug]: cannot open devTools

### ISSUE THREAD

**Issue by pluschong** [electron/electron#32647] opened 2022-01-27 12:26 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

10.x

### What operating system are you using?

Windows

### Operating System Version

windows 10 version unknown

### What arch are you using?

ia32

### Expected Behavior

webContents.openDevTools({ mode: 'detach' }) should open developer tools

### Actual Behavior

Cannot open developer tools，No errors were reported。It only happens to some real users，The development environment cannot be reproduced。I really want to know under what circumstances will such a problem occur。I want the local environment to reproduce。 have no clue！！！！

**Comment by codebytere** [comment] 2022-01-27 12:59
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-01-27 13:01
We are no longer implementing bugfixes for versions of Electron < `13.x`. In order for us to proceed with triage, please demonstrate that this occurs on a [supported version](https://www.electronjs.org/docs/latest/tutorial/support#currently-supported-versions). Otherwise, this issue will be closed in 10 days.

**Closed** 2022-02-07 11:46 UTC
Labels: bug :beetle:, blocked/need-repro

**Comment by hjlld** [comment] 2023-01-11 04:26
@codebytere 

1. I fully understand as a developer, bug fixing for old version is difficult, but bug fixes does not equal to issue resolving, at least leave the issue to us to discuss.
2. For many huge applications is not easy or impossible to upgrade to the lastest electron.
3. Do you have a public and serious support plan or instruction for telling us clearly each version would be not supported in some certain date? For now, the year 2023, which version will be not supported?
