### ISSUE TITLE
Electron it doesn't start with a single module

### ISSUE THREAD

**Issue by PiVirus** [electron/electron#26791] opened 2020-12-02 08:41 UTC
electron - 11.0.3
Windows_NT 10.0.17763
node - v14.15.1
npm - v6.14.8

Module [here](https://github.com/dilame/instagram-private-api)
In the main process, it is enough to connect `const { IgApiClient } = require('instagram-private-api')` and at the start, the electron immediately falls with an error

npm ERR! errno 4294930435
npm ERR! app@1.0.0 start: `electron . `
npm ERR! Exit status 4294930435
npm ERR!
npm ERR! Failed at the app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle app@1.0.0~prestart: app@1.0.0
6 info lifecycle app@1.0.0~start: app@1.0.0
7 verbose lifecycle app@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle app@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\App\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\7-Zip;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\WiX Toolset v3.11\bin;C:\Users\PiVirus\AppData\Local\Microsoft\WindowsApps;C:\Users\PiVirus\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\PiVirus\AppData\Roaming\npm;C:\Program Files (x86)\WiX Toolset v3.11\bin;
9 verbose lifecycle app@1.0.0~start: CWD: D:\App
10 silly lifecycle app@1.0.0~start: Args: [ '/d /s /c', 'electron . ' ]
11 silly lifecycle app@1.0.0~start: Returned: code: 4294930435  signal: null
12 info lifecycle app@1.0.0~start: Failed to exec start script
13 verbose stack Error: app@1.0.0 start: `electron . `
13 verbose stack Exit status 4294930435
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid app@1.0.0
15 verbose cwd D:\App
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 4294930435
22 error app@1.0.0 start: `electron . `
22 error Exit status 4294930435
23 error Failed at the app@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294930435, true ]

Tried electron-rebuild but it didn't help, reinstalled, tried different versions of electron and node.

**Comment by ckerr** [comment] 2020-12-02 16:28
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a folloup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2021-01-05 21:39
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2021-01-05 21:39 UTC
Labels: 11-x-y, blocked/need-repro, bug/crash :boom:, platform/windows
