### ISSUE TITLE
window.open windows not visible when created from BrowserView with nativeWindowOpen enabled

### ISSUE THREAD

**Issue by gerges** [electron/electron#10707] opened 2017-10-06 18:28 UTC
* Electron version: 1.7.8
* Operating system: MacOS Sierra 10.12.6

### Expected behavior
The new window should be opened, and visible

### Actual behavior
The new window is created, but it never becomes visible to the user. These windows can be accessed via the return of `window.open` and appear to be loading content internally.

### How to reproduce
Example repo here: https://github.com/gerges/electron-quick-start/tree/issue/browser-view-native-window-open

**Comment by qazbnm456** [comment] 2017-10-10 03:57
I take your sample code, try it on Electron v1.8.1, and it turns out that this situation happened to 1.8.x series too.

**Comment by Anrock** [comment] 2018-03-26 11:57
Any news on this?

**Comment by Anrock** [comment] 2018-03-26 12:03
Also, parent browser view doesn't produce new-window event for me.

**Comment by codebytere** [comment] 2018-09-24 05:33
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by Anrock** [comment] 2018-09-24 09:14
@codebytere first comment in this issue claims it's reproducible in 1.8. 
And i just reproduced it with provided example project on 1.8.8, 2.0.10 and 3.0.0

**Closed** 2018-11-27 06:59 UTC
Labels: 2-0-x, 3-0-x, bug :beetle:, platform/macOS, version/1.8.x
