### ISSUE TITLE
[Feature Request]: Way to determine if notifications are enabled to send from main process

### ISSUE THREAD

**Issue by YeetOrBeYate** [electron/electron#30054] opened 2021-07-08 14:55 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If you're sending notification from the main process, theres no way to determine programmatically if the OS allows them to display.

### Proposed Solution

There should be a function or something one could run on start up to determine if notifications are allowed to display from the main process. I thought there was one, but I can't find any reference to it. 

### Alternatives Considered

I can't find any other way to check if my app has permissions to send notifications on Mac or Windows. If y'all do please let me know. 

### Additional Information

Please don't like me mdn docs for renderer process notifications permissions. I'm sending these from the main process.

**Comment by nornagon** [comment] 2021-07-08 17:49
Duplicate of #28519

**Closed by nornagon** 2021-07-08 17:49 UTC
Labels: enhancement :sparkles:
