### ISSUE TITLE
[Bug]: MacOS crash

### ISSUE THREAD

**Issue by nashaofu** [electron/electron#34704] opened 2022-06-22 16:11 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.5

### What operating system are you using?

macOS

### Operating System Version

monterey

### What arch are you using?

x64

### Expected Behavior

Applications don't crash

### Actual Behavior

App exit with error `[NativeWidgetMacNSWindowBorderlessFrame _surrenderToolbarViewForFullScreenWindow]: unrecognized selector sent to instance 0x7f79d2327370`
<img width="1331" alt="WX20220623-000604@2x" src="https://user-images.githubusercontent.com/19303058/175081578-cbe8dc03-1b42-4573-9adf-b85a878b9a9a.png">

### Testcase Gist URL

https://github.com/nashaofu/electron-screenshots-issue/tree/electron-bug

### Additional Information

**To Reproduce**
1. git clone https://github.com/nashaofu/electron-screenshots-issue.git
2. git checkout electron-bug
3. yarn && yarn start
4. Press the shortcut key `Ctrl + Shift + A`，Then the program will crash

**Comment by VerteDinde** [comment] 2022-06-22 19:20
Confirmed this crash - also happens with a Fiddle repro here: https://gist.github.com/b4ec28ded8cbb7c85d286f0a6e0ae393 I could reproduce this as far back as 16.0.0, so it doesn't look like it was recently introduced.

**Comment by Macias131987** [comment] 2022-06-23 00:08
Running

**Comment by codebytere** [comment] 2022-08-23 12:41
Duplicate of https://github.com/electron/electron/issues/35403

**Closed by codebytere** 2022-08-23 12:41 UTC
Labels: platform/macOS, crash :boom:, bug :beetle:, status/confirmed, has-repro-gist, 17-x-y, 18-x-y, 19-x-y

**Comment by minzhang2** [comment] 2022-11-04 10:20
The problem reappeared
