### ISSUE TITLE
The function to detect whether the current window is maximized is invalid

### ISSUE THREAD

**Issue by jikunguo** [electron/electron#23931] opened 2020-06-03 03:36 UTC
The function to detect whether the current window is maximized is invalid

```
mainWindow = new BrowserWindow({
        height: 670,
        useContentSize: true,
        width: 1022,
        minWidth: 1022,
        frame: false,
        resizable: false,
        icon: path.resolve(__dirname, '../renderer/assets/icon.png')
    })
```

```
ipcMain.on('max', e => {
    if (mainWindow.isMaximized()) {
        mainWindow.unmaximize()
        // mainWindow.setFullScreen(false)
    } else {
        // mainWindow.setFullScreen(true)
        mainWindow.maximize()
    }
})
```
`mainWindow.isMaximized() `always returns false

**Comment by codebytere** [comment] 2020-06-05 22:37
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by jikunguo** [comment] 2020-06-06 07:31
> 我们需要填写所有新问题和拉取请求的模板。我们这样做，以便我们可以确定，我们拥有所有所需的信息，以有效地解决您的提交。这允许维护人员花费更多时间修复 Bug、实施增强功能以及查看和合并拉取请求。
> 
> 一旦您这样做，我们将能够更密切地关注您的问题。如果上述问题未得到解决，此问题将在 7 天内关闭。

https://github.com/jikunguo/elec-test

**Comment by sofianguy** [comment] 2020-06-17 21:30
@jikunguo What Electron version and what operating system?

**Comment by codebytere** [comment] 2020-06-19 00:42
Duplicate of https://github.com/electron/electron/issues/20969

**Closed by codebytere** 2020-06-19 00:42 UTC
Labels: blocked/need-info ❌, bug :beetle:
