### ISSUE TITLE
electron window is black on Win10

### ISSUE THREAD

**Issue by kaipc** [electron/electron#14402] opened 2018-08-31 10:41 UTC
* Output of `node_modules/.bin/electron --version`:I'm not using node_modules; I'm running electron using the 2.0.8-win32-x64
* Operating System (Platform and Version):Windows 10 (x64, 1803)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
electron should capture screen normally and display screen.

**Actual behavior**
when I run 'electron .' ,it capture screen of electron is black on Win10, but it is normal on Win7 and Mac.

**To Reproduce**
https://github.com/kaipc/capture

**Additional Information**
I realize this might be difficult to reproduce and could involve hardware specific issues so any pointers how I might debug what's happening would be appreciated.

**Comment by pailjin** [comment] 2019-03-21 01:27
https://github.com/electron/electron/issues/6599#issuecomment-257923572
the description of the upper link is detail. 
i test on electron 5.0 beta, win 10. the problem is same as the description in the link 

i don't know when will be fixed?

**Comment by pailjin** [comment] 2019-03-21 02:16
what's more, when share MS office window, the local video play screen is freezed, but resize the window of MS office, the screen will be refresh.
this is not friendly.

**Comment by CapOM** [comment] 2019-12-06 19:58
It is now working:
https://bugs.chromium.org/p/webrtc/issues/detail?id=10734
https://bugs.chromium.org/p/chromium/issues/detail?id=700037

Would need to back port to electron/chromium the CLs attached to them.

**Comment by electron-triage** [comment] 2020-02-19 20:17
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:20
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:20 UTC
Labels: 2-0-x, 5-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
