### ISSUE TITLE
Some emojis are not displayed properly

### ISSUE THREAD

**Issue by bhim3003** [electron/electron#16530] opened 2019-01-24 13:38 UTC
Electron version: 3.0.9
Operating system: macOS 10.13.6

**Expected Behavior**
The emoji shouldn't have the strange symbol at the end.

**Actual behavior**
![image](https://user-images.githubusercontent.com/8445316/51681502-c77b0200-200a-11e9-8d40-9be6372bf132.png)

**To Reproduce**
Select the emoji from Ctrl+Cmd+Space menu under Mac.
<img width="332" alt="screen shot 2019-01-24 at 7 05 08 pm" src="https://user-images.githubusercontent.com/8445316/51681647-4a03c180-200b-11e9-89be-c4804e970582.png">

**Additional Information**
Seems it was [fixed earlier](https://github.com/electron/electron/issues/11874), but it breaking in the newer version of electron.

**Comment by b18050** [comment] 2019-01-24 20:45
i want to fix this issue. will you help me in this?

**Comment by nornagon** [comment] 2019-01-24 21:20
I believe we inherit this issue from upstream chromium.

I can reproduce this in 4.0.2 but not 5.0.0-beta so the upstream fix must be somewhere after M69 (and before M72).

Looks like crbug.com/774302 is the upstream issue. The fix is fairly involved & includes rolling the HarfBuzz dependency, so it might be challenging to backport.

**Comment by felixfbecker** [comment] 2019-02-12 11:37
For reference, this issue existed before: https://github.com/electron/electron/issues/11874

**Comment by codebytere** [comment] 2019-04-05 19:12
Seconding @nornagon above; this fix is challenging and it's fixed in 5 so i don't think this is something we're prepared to backport. As such, i'm labeling this a wontfix.

**Closed by codebytere** 2019-04-05 19:12 UTC
Labels: 3-0-x, 4-1-x, bug :beetle:, platform/macOS
