### ISSUE TITLE
Should Electron (macOS) use replyToApplicationShouldTerminate?

### ISSUE THREAD

**Issue by gabriel** [electron/electron#7121] opened 2016-09-06 23:58 UTC
* Electron version: 1.3.5
* Operating system: macOS 10.11

I noticed that Electron always returns `NSTerminateCancel` from `applicationShouldTerminate` and then exits manually.
Maybe it should use `NSTerminateLater` and then `replyToApplicationShouldTerminate`?

I think this is why when rebooting sometimes, you briefly get an "Atom interrupted the computer from restarting" (or whatever that thing says), but this is pure speculation.

**Comment by kevinsawicki** [comment] 2016-09-07 16:35
Closing as a duplicate of https://github.com/electron/electron/issues/230, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2016-09-07 16:35 UTC
