### ISSUE TITLE
globalShortcut - MediaTrackNext only works one time

### ISSUE THREAD

**Issue by danieldaeschle** [electron/electron#12415] opened 2018-03-22 22:15 UTC
if i register a globalshortcut for a media it works only one time. for all others linux displays me an "x".

* Electron version: 1.8.4
* Operating system: Ubuntu 16.04

### Expected behavior
It should work every time

### Actual behavior
It should work only one time

### How to reproduce
```javascript
globalShortcut.register('MediaPlayPause', () => {
    console.log(true)
})
```

**Comment by danieldaeschle** [comment] 2018-03-23 13:56
Seems like there is a workaround: #5268
I will check it later.

**Comment by danieldaeschle** [comment] 2018-09-07 09:04
This workaround only works on Ubuntu with Gnome. Not on Manjaro/Arch with Gnome.

**Comment by sofianguy** [comment] 2019-01-07 21:31
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:42
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by gadtfly** [comment] 2019-03-15 04:07
This issue still exists as in Electron 4.0.6 on Ubuntu 18.10.

**Comment by xevrem** [comment] 2019-04-22 11:05
can confirm this only appears to occur in Gnome, not necessarily Ubuntu's Gnome.

I run Manjaro w/ Gnome 3.32 w/ GTK 3.24 and the issue is present (single use media key events) and then it appears to get captured by something else (not sure what). On Manjaro w/ KDE Plasma 5.15 w/ Frameworks 5.56, it is not an issue and the events will execute as intended.

**Comment by felicianotech** [comment] 2019-06-03 03:19
Facing this issue as well. My stack:

- Ubuntu 19.04
- Gnome 3.32.1
- Electron 5.0.1

**Comment by electron-triage** [comment] 2020-02-19 22:14
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by danieldaeschle** [comment] 2020-02-20 10:39
i no longer need this. if you guys want it to fix, test it yourself 😂

**Comment by electron-triage** [comment] 2020-03-06 19:56
We are going to close this for now, but we would be happy to reopen if this issue is still present in later, supported versions of Electron.

**Closed by electron-triage** 2020-03-06 19:56 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/linux, version/1.8.x
