### ISSUE TITLE
[Bug]: White flash before window is rendered in all electron apps I use on windows 11

### ISSUE THREAD

**Issue by skareel** [electron/electron#44121] opened 2024-10-06 02:45 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11 24H2

### What arch are you using?

x64

### Expected Behavior

Contents of the window is shown without a white flash happening very quickly first. It's like a flashbang of white and then the contents renders in the window for chromium/electron based apps.

I'm not a developer and I don't know anything about electron but I don't know where else to post this problem and have anybody look into it. I originally thought this was an issue with windows dark mode and I posted on the Windows feedback hub about it but never got a response. I also posted on the Windows 11 subreddit and they said this was an issue with electron instead of Windows itself.

### Actual Behavior

When opening a window in an electron app (figma or todoist in this case), it flashes the entire screen white before rendering the contents of the window. I've seen this happen on chrome, figma, todoist, microsoft to do, and others that use electron. This has been happening for at least 5 years when I was using Windows 10 and now with Windows 11.

**Comment by mlaurencin** [comment] 2024-10-07 16:37
If this is happening for you with Chrome, then your issue is likely due to something in Chromium rather than Electron. In general, if a problem in an Electron app is reproducible in Chrome, there is little Electron maintainers can do to fix it for Electron. The Chromium issue tracker would be the place to look and see if anyone has reported an issue similar to your own.

Additionally, if you would like to report an Electron issue in the future, we ask that you include a standalone testcase with only the code necessary to reproduce the issue. Although you mentioned that you are not a developer, due to time constraints, triaging code with third-party dependencies (as is present in those other applications you mentioned) is usually not feasible for a small team like Electron's. [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

I am closing this issue now due to it being an upstream problem. I hope this information helps!

**Closed by mlaurencin** 2024-10-07 16:37 UTC
Labels: platform/windows, bug :beetle:, 33-x-y

**Comment by skareel** [comment] 2024-10-07 16:41
It is happening in chrome, discord, todoist, brave, vivaldi that I've tested so far. Aren't all of these apps based on electron?

**Comment by mlaurencin** [comment] 2024-10-07 17:40
Chrome is not an Electron app

**Comment by skareel** [comment] 2024-10-07 17:42
Ok I can check on chrome's support forum to see if there has been any
resolution to the problem with their browser. I do believe todoist and
figma are electron apps though
