### ISSUE TITLE
Webview: window.onfocus fired whenever clicking into webview

### ISSUE THREAD

**Issue by bpasero** [electron/electron#14259] opened 2018-08-22 10:58 UTC
* Electron Version: 3.0.0-beta.6
* Operating System (Platform and Version): macOS
* Last known working Electron version: 3.0.0-beta.5

**Expected Behavior**
The `onfocus` event is not fired when contents inside the webview element is focused

**Actual behavior**
The `onfocus` event is not fired whenever focus moves between webview contents and page contents

**To Reproduce**
* run this fiddle: https://gist.github.com/bpasero/d53f48f04af6b4a94c284189079c246d
* click into the input box of the GitHub landing page
* observe that the `onfocus` event is emitted
* click into the page 
* observe that the `onfocus` event is emitted again

This breaks VSCode's assumption about the entire window loosing or gaining focus.

**Comment by zcbenz** [comment] 2018-08-29 10:26
This is the expected behavior for iframe, and there is no way to suppress the focus event of window from JavaScript's side. I'm trying to find out a way to change how blink decides whether a page is focused, I may have to close this issue if Chromium does not provide a way to do that.

**Comment by zcbenz** [comment] 2018-08-30 12:28
To hack blink's focusing behavior, I have tried to patch [`FocusController::SetFocusedFrame`](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/page/focus_controller.cc?sq=package:chromium&dr=C&g=0&l=773) to keep the main frame being focused on when clicking into webview. But there are a few severe problems:

1. There is no way to distinguish a webview from normal remote iframe on blink's side, OOPIF is implemented on content module's  side.
2. We can only suppress the focus/blur events, we can not trick Chromium to think there are 2 focused frames, by design in blink only one frame can have focus.

To fix the problems we have to do a much larger patch to blink's architecture, to make Chromium able to treat iframe like normal elements. Which I don't think we can do.

I'll add documents to webview to explain its underlying architecture and what behaviors to expect.

**Comment by bpasero** [comment] 2018-08-30 12:36
Yeah -1 for larger hacks/patches.

**Closed** 2018-08-31 20:52 UTC
Labels: app-feedback-program, bug :beetle:, platform/macOS, version/3.0.x

**Comment by bpasero** [comment] 2018-09-01 09:28
@zcbenz would it make sense to state a possible workaround, which is to listen to `app` events `browser-window-blur` and `browser-window-focus`? From my first testing it seems that these events are not firing when focus goes in or out of a `webview` but only when the entire window looses or gains focus.

**Comment by zcbenz** [comment] 2018-09-01 11:10
@bpasero To subscribe to the focus state of the window, the best way is to listen to the `focus`/`blur` events of the `BrowserWindow` object.

The `window.onfocus` event in DOM is emitted when the page gets focused, instead of the window, and it is DOM's specification that switching focuses in main/sub frames will also changing their focus states.

**Comment by bpasero** [comment] 2018-09-01 13:51
@zcbenz is there any difference to the `app` events `browser-window-blur` and `browser-window-focus`?

**Comment by zcbenz** [comment] 2018-09-02 01:41
@bpasero The `browser-window-focus` events are implemented by listening to the `focus` event of `BrowserWindow`, there is no real difference.

**Comment by bpasero** [comment] 2018-09-02 10:50
@zcbenz what is the recommended way to restore focus to a `<webview>` element? I tried a few things (`webview.focus()`, `webview.getWebContents().focus()`) but none result in the `document.activeElement` to actually be the `<webview>`. VSCode needs to be able to programmatically set focus back to the element in certain cases.

The only (hacky?) way I could make this work is calling: `webview.sendInputEvent({ type: 'mouseDown', x: 0, y: 0, button: 'left', clickCount: 1 })` but not sure about the consequences.

**Comment by zcbenz** [comment] 2018-09-02 13:46
@bpasero Currently for the master branch you can use `webview.contentWindow.focus`, I'll patch `webview.focus` to make it work.
