### ISSUE TITLE
[Bug]: Invalid node module version

### ISSUE THREAD

**Issue by pelletier197** [electron/electron#36899] opened 2023-01-12 16:45 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.1

### What operating system are you using?

Windows

### Operating System Version

Edition	Windows 11 Pro Version	22H2 Installed on	‎12/‎13/‎2022 OS build	22621.1105 Experience	Windows Feature Experience Pack 1000.22638.1000.0

### What arch are you using?

x64

### Last Known Working Electron version

19.1.9

### Expected Behavior

It is expected that the `node_module_version` matches the one [specified by node](https://nodejs.org/en/download/releases/) when loading native modules.  In this case, since i'm using node 16.17.1, I would expect the `node_module_version` to be 93, and not 110. 

From this, I would expect that tests executed with Jest are compatible with code executed in electron, since they should use the same node module version.

### Actual Behavior

When launching the electron process, and running the line `console.log(process.versions)`, the output is the following:

**Electron output**
```javascript
{
 node: '16.17.1',
 modules: '110',
 electron: '22.0.1'
 // and more... 
 }
```

When running in jest, this is what I have

**Jest output**
```javascript
{
  node: '16.17.1',
  modules: '93',
  // and more...
}
```

again, according to [this table](https://nodejs.org/en/download/releases/), seems to me that `electron-builder` installs/builds the wrong version of the module. For some reason, the module ends up working when launched from electron, but when running jest as is, I get the following error

```
[electron] [2023-01-12T11:43:04]    ERROR Failed to initialize server Error: The module '\\?\C:\xxx\node_modules\better-sqlite3-multiple-ciphers\build\Release\better_sqlite3.node'
[electron] was compiled against a different Node.js version using
[electron] NODE_MODULE_VERSION 110. This version of Node.js requires
[electron] NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
```

I found a way to re-compile the library to the right target, but then the tests pass and electron fails with the reverse error. I don't know where this issue comes from, but I have no idea how to fix this from here. I don't know if it's a bug or misconfiguration. 

Thanks in advance

**Comment by miniak** [comment] 2023-01-12 18:10
Electron has separate `node_module_version`
https://github.com/nodejs/node/blob/main/doc/abi_version_registry.json

**Comment by miniak** [comment] 2023-01-12 18:10
Thanks for taking the time to contribute!

We noticed that this is a duplicate of [Issue URL]. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by miniak** 2023-01-12 18:10 UTC
Labels: bug :beetle:

**Comment by miniak** [comment] 2023-01-12 18:11
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by pelletier197** [comment] 2023-01-12 18:24
Thank you for the hint. I managed to fix this by running jest using the same node instance as the code. 

```shell
cross-env ELECTRON_RUN_AS_NODE=true ./node_modules/.bin/electron node_modules/jest/bin/jest.js '.*/integrationTest.*' --max-workers=1
```
