### ISSUE TITLE
On full screen window size, no green traffics light button

### ISSUE THREAD

**Issue by eugene-pr** [electron/electron#23201] opened 2020-04-21 14:22 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  9.0.0-beta.18
* **Operating System:**
  macOS 10.14.6
* **Last Known Working Electron version:**
  9.0.0-beta.10

### Expected Behavior
On window full screen, should be a green traffic lights button

### Actual Behavior
On window full screen, no green traffic lights button;

### To Reproduce
Click on red traffic lights button, to set the window full screen

### Screenshots
9.0.0-beta.10
![Screen Shot 2020-04-21 at 17 06 09](https://user-images.githubusercontent.com/9944915/79876932-50424280-83f4-11ea-85a2-61f101c7d452.png)

9.0.0-beta.18
![image](https://user-images.githubusercontent.com/9944915/79876828-3143b080-83f4-11ea-88b3-9e30ad838f68.png)

**Comment by codebytere** [comment] 2020-04-24 03:52
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Your "To Reproduce" section contains no code, and as there are many different configurations which may have produced this behavior, we cannot triage until you have provided some.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by zcbenz** [comment] 2020-05-12 00:16
I'm unable to reproduce with 9.0.0-beta.18 on macOS, I assume it requires certain combinations of options to reproduce. I'm closing this issue until an reproducible example is provided.

**Closed by zcbenz** 2020-05-12 00:16 UTC
Labels: 9-x-y, blocked/need-info ❌

**Comment by eugene-pr** [comment] 2020-05-25 14:11
Found the issue, When I create a BrowserWindow with the frame parameter set to false, and then apply to it setWindowButtonVisibility(true). In fullScreen state, there is no yellow traffic light button. And, if not in fullScreen state, no yellow, and green traffic lights.
