### ISSUE TITLE
Electron crashing with EXC_BAD_ACCESS when running with Atom snapshot

### ISSUE THREAD

**Issue by leroix** [electron/electron#11387] opened 2017-12-09 01:13 UTC
I'm working on upgrading Atom to Electron 1.7. However, something in the snapshot is causing Atom to crash within seconds of starting up. When a snapshot is not used, Atom starts without crashing.

Here's the startup script that the Atom build process generates for use when creating a snapshot:
https://gist.github.com/leroix/f2d68bf754ce39c6ec3c10e472e56a76

I'm creating a snapshot using the startup script by running:
```
./script/node_modules/electron-mksnapshot/bin/mksnapshot out/startup.js --startup_blob out/Atom.app/Contents/Frameworks/Electron\ Framework.framework/Resources/snapshot_blob.bin 
```

I've found that if I comment out lines 25261-25262 in the startup script, which prevents preloading bundled Atom packages, the crashing issue is resolved. However, this reduces the benefit of using a snapshot in the first place.

Here's a crashlog:
https://gist.github.com/leroix/d3eaf4f8b9ff22fff896d53657c52ade

**Comment by leroix** [comment] 2017-12-10 23:30
I found out there's something else at play besides just running Atom's entrypoint with Electron and a snapshot blob https://github.com/atom/atom/pull/16282#issuecomment-350590010.

I'm not sure if it's something in the Atom startup script, packaging, etc.

**Comment by leroix** [comment] 2017-12-13 02:37
Adding a bit more info:

I found that if I download a fresh electron binary for 1.7.9 and move Atom's build folder "./out/app" into "electron/Electron.app/Contents/Resources", as per https://electronjs.org/docs/tutorial/application-distribution, and run it, Atom starts. However, when I move Atom's snapshot blob into "electron/Electron.app/Contents/Frameworks/Electron\ Framework.framework/Resources" and run it, Atom crashes on startup.

**Comment by leroix** [comment] 2017-12-13 05:07
Alternatively, if I skip copying app into "electron/Electron.app/Contents/Resources" and just copy the startup snapshot from the Atom build into "electron/Electron.app/Contents/Frameworks/Electron\ Framework.framework/Resources" and run ```./electron/Electron.app/Contents/MacOS/Electron ./out/app/src/main-process/main.js```
Atom starts up without crashing.

**Comment by iolsen** [comment] 2017-12-15 19:16
This issue is preventing Atom from upgrading to 1.7.x. The relevant PR is https://github.com/atom/atom/pull/16282.

**Comment by leroix** [comment] 2017-12-15 21:41
Another odd thing I found was that if I symlink the app folder into "electron/Electron.app/Contents/Resources" instead of copying it (when using a snapshot), Atom doesn't crash.

**Comment by leroix** [comment] 2017-12-15 22:01
Here's a symbolicated crash log https://gist.github.com/leroix/e1e6e73e02bb787ad63cf8af262ab233

**Comment by MarshallOfSound** [comment] 2017-12-16 09:19
@leroix Might be even more of a long shot but can you see if this crash / failure occurs on 1.8.x?

**Comment by 50Wliu** [comment] 2017-12-16 14:20
@MarshallOfSound Just tried it out on Windows, still an instant crash.

**Comment by leroix** [comment] 2017-12-17 06:56
I figured out that I can place the app in "Electron.app/Contents" and place a symlink to "../app" in "Electron.app/Contents/Resources", and Atom runs without crashing. However, if I place the app folder itself in "Electron.app/Contents/Resources", it crashes.

**Comment by leroix** [comment] 2017-12-19 03:04
@hashseed It's possible this is a v8 bug with snapshots. I'm trying to create a debug build of libchromiumcontent in electron, but in the meantime, any chance you have any insight?

**Comment by hashseed** [comment] 2017-12-19 05:38
`mksnapshot` doesn't work with native references out of the box. If what ever Atom packages you load has native bindings (e.g. functions back by a C++ implementation), the serializer would not know how to handle them unless it's provided to V8. Like [this](https://github.com/v8/v8/blob/2c4704abf59850fd6c64e3c38a75ebe1e3c8b7b7/test/cctest/test-serialize.cc#L2406). This feature is fairly new and not directly exposed in mksnapshot (I wouldn't know how). Previously you had to use [electron-link](https://github.com/atom/electron-link) as workaround.

**Comment by hashseed** [comment] 2017-12-19 05:39
It probably suffices to build `mksnapshot` in debug mode and attempt to create the snapahot, in order to find the issue.

**Comment by leroix** [comment] 2017-12-19 06:33
@hashseed The Atom startup script is built using electron-link still, and the startup script is checked using `vm.runInThisContext` as part of the build script. Would that catch it?

I'm working on building `mksnapshot` in debug mode as well like you mentioned.

**Comment by leroix** [comment] 2017-12-19 20:52
@hashseed is there a debug build of `mksnapshot` for macOS somewhere that I could grab. I'm not having much luck building it myself.

**Comment by leroix** [comment] 2017-12-20 06:51
Here's a crash log I got from running `mksnapshot` from a local build of libchromiumcontent on the Atom startup script using the electron master branch @ https://github.com/electron/electron/commit/85ef42d99e12578010e86f7ab52c791a64a41f22.

https://gist.github.com/leroix/c4b72de917689deed7857617a73e2b35

**Comment by hashseed** [comment] 2017-12-20 07:30
Interesting. What is happening is that there is an object that has an embedder field - a field that stores a pointer to arbitrary embedder-owned data. V8's serializer has no idea how to deal with that, and you would have to define a [callback](https://github.com/v8/v8/blob/18dc491c7a7857da109556e8bef66345da396950/include/v8.h#L8251) to handle it.

I'm not all that familiar with how electron uses mksnapshot. Is it built from vanilla V8, or patched somehow? I can't reproduce the issue with the `startup.js` linked above.

**Comment by leroix** [comment] 2017-12-20 07:53
Thanks @hashseed. As far as I can tell, electron just copies mksnapshot from libchromiumcontent for its release. I believe libchromiumcontent contains an unpatched version of chromium. 

Also, when I run using the downloaded build of libchromiumcontent (retrieved using `./script/bootstrap.py`), it doesn't crash which is really strange. Maybe something is just screwed up with my local build?

Note: the bootstrap script downloads libchromiumcontent into the ./vendor/downloads folder. The downloaded `mksnapshot` is located at ./vendor/downloads/libchromiumcontent/static_library/mksnapshot.

**Comment by nathansobo** [comment] 2017-12-21 04:49
@hashseed After building v8 in debug mode with all DCHECKs enabled, we're getting some clues. 

* The first issue was that `lodash.isequal` instantiates an ArrayBuffer at eval time, which violated a DCHECK at `objects.cc:19177` when running `mksnapshot`. We commented out that line and hit the next issue...
* The next issue is more mysterious. We're failing at this check in `partial-serializer.cc:84`:
  ```
  // Pointers from the partial snapshot to the objects in the startup snapshot
  // should go through the root array or through the partial snapshot cache.
  // If this is not the case you may have to add something to the root array.
  DCHECK(!startup_serializer_->reference_map()->Lookup(obj).is_valid());
  ```

Can you shed some light on that comment? Do you have any idea why our startup script worked in V8 5.6 but now does not not in V8 6.1? Have the rules for creating snapshots changed, or were we getting away with things in the older version that some changes have brought to the surface?

Attached is the original `startup.js` that seems to be producing these issues in case it might help illuminate what's going on.

[startup.js.zip](https://github.com/electron/electron/files/1577957/startup.js.zip)

**Comment by hashseed** [comment] 2017-12-21 06:38
Before I dive deeper, can you confirm that you are using the vanilla `mksnapshot` that V8 provides? Or do I have to get it from somewhere else? I wasn't able to reproduce the issue with newest V8 (6.4).

The failure is due to an object being serialized first by the startup serializer because it is considered context-independent. But later we attempt to serialize it with the context serializer, which would be a contradiction.

Iirc we added support for TypedArrays and ArrayBuffers to the serializer some time ago. Maybe we fixed some bug between 6.1 and 6.4 so that I can't reproduce? In that case we probably should find out what the fix is.

**Comment by as-cii** [comment] 2017-12-21 08:09
> Before I dive deeper, can you confirm that you are using the vanilla mksnapshot that V8 provides? 

Yes, we built a debug version of `mksnapshot` that's included in vanilla v8 (commit: f29d55e6190, tag: 6.1.534.41).

> Maybe we fixed some bug between 6.1 and 6.4 so that I can't reproduce?

Yeah that seems possible. In such case, I agree it would be cool if we could track down the fix so that we can backport it into Electron. It is probably going to take some time before Electron uses v8 6.4.

Thanks so much for your help on this, @hashseed! 🙏

**Comment by hashseed** [comment] 2017-12-21 11:49
I can reproduce the ArrayBuffer issue with 6.1. I'm not sure what line to comment out in startup.js to avoid that problem though.

ArrayBuffer support in V8's serializer/deserializer has been added in [V8 6.2](https://chromium.googlesource.com/v8/v8/+/a5f321cd9bfe93e5b097969d02cb759f2c7ae9fb).

The issue you then ran into was fixed in [V8 6.3](https://chromium.googlesource.com/v8/v8/+/29691f8063ccdb41f77ff60d8cf2d048886ff617). We have a [tracking bug](https://bugs.chromium.org/p/v8/issues/detail?id=6422) where I already requested a merge to 6.1 and 6.2.

**Comment by nathansobo** [comment] 2017-12-21 19:04
After removing the script that constructs an `ArrayBuffer` at eval time and passing the `--no-use_ic` flag to `mksnapshot`, we're able to create a snapshot and start Atom on the following versions:

* Electron 1.7.10, V8 5.8.283.38
* Electron 1.8.2-beta.3, V8 5.9.211.38

On cursory inspection, disabling inline caches does not seem to have a big impact on startup time, though we haven't investigated deeply.

@hashseed a couple of questions:

* Could you help us understand the implications of disabling inline caches? Is it just that we need to pay the cost of populating these caches at runtime?
* Would it be possible to backport the fix to [the bug you mentioned](https://bugs.chromium.org/p/v8/issues/detail?id=6422) to V8 5.8 or 5.9? Otherwise we'll need to wait until Electron 1.9 to re-enable inline caches, which could take months. It's not yet clear how big a problem it is to disable inline caches however. It may be okay to just proceed without them in the meantime.

We deeply appreciate your engagement on this issue @hashseed. Without your help on this, I'm not sure we have figured out a workaround. ⚡️ ❤️ ✨ 🍺 🍺 🍺

**Comment by hashseed** [comment] 2017-12-21 19:16
`--no-use-ic` should be safe to use for `mksnapshot`, and is a valid workaround for this issue.

I don't think it will affect performance when you use that snapshot. We clear ICs when creating the snapshot anyways (which was broken prior to the bug fix), so I don't think there is any difference other than maybe `mksnapshot` itself performing worse.

Rather than back merging, I would suggest to simply add `i::FLAG_use_ic = false;` to [`mksnapshot.cc`](https://cs.chromium.org/chromium/src/v8/src/snapshot/mksnapshot.cc?l=145&rcl=f5b1d1d4f29b238ca2f0a13bf3a7b7067854592d) for versions up to V8 6.3.

**Comment by as-cii** [comment] 2017-12-22 08:58
Thanks for the clarification, @hashseed! I'll go ahead and close this since it seems like we can safely disable inline caches when running `mksnapshot` until Electron ships with a version of V8 >= 6.3.

Nice joint effort on this! ⚡️

**Closed by as-cii** 2017-12-22 08:58 UTC
Labels: triaged/bug
