### ISSUE TITLE
[2.0] redraw problem when change dom element style

### ISSUE THREAD

**Issue by s1b** [electron/electron#12830] opened 2018-05-04 09:53 UTC
* Electron version: 2.0.0
* Operating system: mac os x Yosemite 10.10.5

* Last known working Electron version: 1.8.6

### Actual behavior

![2018-05-04 6 43 37](https://user-images.githubusercontent.com/16533037/39621969-89a7f09c-4fcb-11e8-926d-76267a461ff3.png)

### How to reproduce

[test.html.txt](https://github.com/electron/electron/files/1973935/test.html.txt)
[main.js.txt](https://github.com/electron/electron/files/1973938/main.js.txt)

**Comment by s1b** [comment] 2018-05-04 09:57
when open with "electron test.html", it works well

**Comment by s1b** [comment] 2018-05-04 17:41
adding css 
body { background: white; }
solve this problem

**Comment by codebytere** [comment] 2018-05-05 19:06
It's unclear what the problem is, can you please provide more detail?

**Comment by s1b** [comment] 2018-05-06 06:38
Please understand that I did not speak English and I used a translator.
If you modify the style of the dom element to implement the move effect, there will be a residual image in the background like the screenshot above
The problem is solved by adding background color to body css.
As a personal guess, I suspect that if the background of the BrowserWindow is transparent, it will not be redrawed.
In addition, I attach a screenshot that browses a web page via Electron's BrowserWindow. 
Some web pages will not redraw properly when scrolled.
I think this is a similar problem.

![2018-05-06 3 31 05](https://user-images.githubusercontent.com/16533037/39670581-f39be332-5142-11e8-8449-14c199d955c0.png)

**Comment by sofianguy** [comment] 2019-08-09 00:52
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 21:07
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 21:07 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS
