### ISSUE TITLE
[Bug]: "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle

### ISSUE THREAD

**Issue by pedrinfx** [electron/electron#32148] opened 2021-12-10 21:12 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2 19042.1348

### What arch are you using?

x64

### Expected Behavior

Electron work correctly

### Actual Behavior

Prints on console: `[14124:1210/180539.694:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[14124:1210/180539.699:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)`
and the browser/electron app turns white

### Additional Information
I'm using React as renderer and also I'm using electron-forge.

### Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/47058899/145642121-62010456-0479-4d1c-91e0-37f750ee1f9e.png)

**Comment by miniak** [comment] 2021-12-22 03:29
Duplicate of #32133

**Closed by miniak** 2021-12-22 03:29 UTC
Labels: bug :beetle:
