### ISSUE TITLE
[Bug]: electron 18 uses Nodejs native module (context aware). Sometimes Devtools reload for electron will lead to render process crash. Is there any way to locate the problem？

### ISSUE THREAD

**Issue by Candylong** [electron/electron#36816] opened 2023-01-06 08:47 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0

### What operating system are you using?

Windows

### Operating System Version

windows or mac

### What arch are you using?

x64

### Last Known Working Electron version

18.0.0

### Expected Behavior

normal fresh

### Actual Behavior

![image](https://user-images.githubusercontent.com/76611653/210965007-716eb012-5896-4b0c-be99-24fc4ca5ec6e.png)
![image](https://user-images.githubusercontent.com/76611653/210965041-2c93c7d1-11c4-4c36-95f0-624380b342ed.png)

### Testcase Gist URL

https://github.com/Candylong/napi-electron-demo

### Additional Information

 I mainly run it on windows, and it can be reproduced after about 5 operations.(click button then reload)

**Comment by Candylong** [comment] 2023-01-13 09:50
I am not quite sure about the underlying principle of electron reload. Does reload cause an exception on Node?

**Comment by codebytere** [comment] 2023-02-15 11:14
@Candylong v18 is EOL. In order for us to continue triaging this, you'll need to demonstrate that it occurs on a supported version (v22 and newer) Otherwise, this issue will be closed in 10 days.

**Comment by Candylong** [comment] 2023-02-16 10:15
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

@codebytere ，hi,
 I can't use electron21 and up because I use nodejs addon built with node-addon-api, which is incompatible with V8 sandboxed pointers used by electron 21. Using electron 21 and above also causes another crash for my plugin. node-adon-api is not available for V8 sandboxed pointers. Can you repeat this problem using the demo I provide(it can run in electron 20)

**Comment by mlaurencin** [comment] 2023-03-01 22:19
Unfortunately since v20 and below are no longer supported, I am going to have to close this issue. If it can be reproduced in a supported version in the future, feel free to open a new issue.

**Closed by mlaurencin** 2023-03-01 22:19 UTC
Labels: platform/windows, bug :beetle:, component/node-integration
