### ISSUE TITLE
Window maximization of frameless window with task bar at top of screen produces undesired effect

### ISSUE THREAD

**Issue by Jcozman** [electron/electron#5930] opened 2016-06-08 04:17 UTC
* Electron version: 1.2.1
* Operating system: Windows 10 64-bit

Can't upload a screenshot right now. Steps to reproduce:

1. Create a frameless browser window
2. Set your windows taskbar location to be at top of screen
3. Maximize the window

You'll be able to see the effect I'm describing. If you move the window it becomes more apparent

**Comment by zcbenz** [comment] 2016-06-08 08:54
A screenshot would be helpful.

**Comment by MarshallOfSound** [comment] 2016-06-08 11:29
@zcbenz I just tried to replicate this and it is a duplicate of #5267.

When maximizing a frameless window on Windows it sometimes overflows on certain axis.  In this case it overflows **into** the top taskbar.

![strange](https://cloud.githubusercontent.com/assets/6634592/15892927/f7f2453c-2dbf-11e6-8599-ee9b29c8e9cd.PNG)

That thin black line is the top of the task bar.  The thin grey line above it is the top of my frameless window.

**Comment by Jcozman** [comment] 2016-06-08 21:47
![capture](https://cloud.githubusercontent.com/assets/4622925/15912191/f0be49ec-2da0-11e6-9fb5-ee4ce6143df9.PNG)

Here is the effect behind the taskbar when the window is maximized.

![capture2](https://cloud.githubusercontent.com/assets/4622925/15912205/fe38b3d2-2da0-11e6-8737-322f27f68696.PNG)

After the window is maximized and has been moved away from the taskbar

![capture3](https://cloud.githubusercontent.com/assets/4622925/15912216/096919e0-2da1-11e6-9a7f-be41ec930338.PNG)

Non-maximized window

**Comment by zcbenz** [comment] 2016-06-09 03:37
@MarshallOfSound Thanks for trying this, I'm merging this to #5267.

**Closed by zcbenz** 2016-06-09 03:37 UTC
Labels: more-information-needed
