### ISSUE TITLE
[Bug]: desktopCapturer not working in ubuntu 21 (black screen issue)

### ISSUE THREAD

**Issue by SarathKmrM** [electron/electron#33802] opened 2022-04-15 10:31 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21

### What arch are you using?

x64

### Expected Behavior

I have been using desktopCapturer to capture screenshot in my app. It was working perfectly on old ubuntu version (16,18 and 20). But its not working in ubuntu 21.

### Actual Behavior

I am getting black image on ubuntu 21.

### Additional Information

```
desktopCapturer.getSources({ types: ['screen'] }).then( sources => {
  fs.writeFile(`screenshot.jpg`, sources[0].thumbnail.toJPEG(25), (err) => {
    if (err) throw err
      console.log('Image Saved')
  })
})
```
The above code was tested and working in ubuntu 18 and 20. 
But its not working in Ubuntu 21. I am getting screenshot of black image on ubuntu 21.

Thank you in advance

**Comment by mlaurencin** [comment] 2022-04-18 20:44
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/electron/electron/issues/31588. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by mlaurencin** 2022-04-18 20:44 UTC
Labels: bug :beetle:
