### ISSUE TITLE
There was something wrong when using event.sender.send

### ISSUE THREAD

**Issue by zeusLeeJh** [electron/electron#8214] opened 2016-12-16 06:57 UTC
* Electron version: 1.4.4
* Operating system: windows 10

## In main process
```
ipcMain.on('close-current', function (event ,data) {
  // do something close current window
  event.sender.send('asynchronous-reply', 'had-close-current');
});
```
## In  renderer process 
```
ipcRenderer.send('close-current');
ipcRenderer.on('asynchronous-reply', function(event, data) { 
  console.log('close');
});
```
Finally I successfully closed the current window,but then it is warning like that:

![_20161216144640](https://cloud.githubusercontent.com/assets/15540537/21254317/7613b688-c39f-11e6-8d9f-fa23d83965a6.png)

Should I avoid using ` event.sender.send` after I closed the current window ?

**Comment by MarshallOfSound** [comment] 2016-12-16 09:38
This issue has been fixed in the later versions of Electron.  Can you test `1.4.11` or `1.4.12` to see if this issue still occurs.

**Comment by zeusLeeJh** [comment] 2016-12-19 03:17
Unfortunely, this issue still occurs.

**Comment by cungminh2710** [comment] 2017-01-03 00:38
I am facing a similar issue where ipcRenderer failed to send a message.
What i wrote was 
```javascript
const {ipcMain} = require('electron');
.... // Some logic
ipcRenderer.send('pasted', message); // it failed here
```
The error message was 
`\node_modules\electron\dist\resources\electron.asar\renderer\api\ipc-renderer-setu…:6 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.`

**Comment by kevinsawicki** [comment] 2017-01-04 18:23
> // do something close current window
> event.sender.send('asynchronous-reply', 'had-close-current');

@zeusLeeJh Are you closing the window before running `event.sender.send`?

`event.sender` is the `webContents` associated with the window, so if the window is destroyed then the web contents is destroyed and you can not send messages back to it.

**Comment by kevinsawicki** [comment] 2017-01-12 01:30
I believe this is expected behavior since you can't  access `event.sender` once you close the window that contains it since it gets destroyed on window close.

Closing this out.

**Closed by kevinsawicki** 2017-01-12 01:30 UTC
Labels: more-information-needed
