### ISSUE TITLE
Overlay icon sometimes does not render when combined with a 'minimize()' on the hidden BrowseWindow

### ISSUE THREAD

**Issue by avoidwork** [electron/electron#4818] opened 2016-03-15 20:30 UTC
* Electron version: 0.36.10
* Operating system: Windows 7-SP1, Windows 8, Windows 8.1, Windows 10

Hi,

The app I'm creating runs primarily from the tray for longevity, such that the user can 'close' BrowserWindow (intercept and hide) and the app continues to run; inside the app we have the notion of 'notices' and decorate the tray & taskbar via `setOverlayIcon()`. This is the function that handles task (some variables are in lexical scope):

```javascript
function badgeText (ev, arg) {
	let main = windows.main;

	total = arg;

	if (main) {
		if (total && !main.isVisible()) {
			main.minimize();
			console.log('[core] Minimizing the hidden main window');
		}

		if (osx) {
			if (total) {
				app.dock.show();
				app.dock.setBadge(total.toString());

				if (!main.isFocused() && !bounce) {
					bounce = app.dock.bounce('critical');
					console.log('[core] Bouncing dock');
				}
			} else {
				if (bounce) {
					app.dock.cancelBounce(bounce);
					bounce = null;
					console.log('[core] Cancelling bouncing dock');
				}

				app.dock.setBadge('');
			}
		} else {
			if (total) {
				main.setOverlayIcon(nativeImage.createFromPath(iconPath('dot.png')), total + ' items');
				console.log('[core] Set overlay icon on taskbar');
			} else {
				main.setOverlayIcon(nativeImage.createEmpty(), '');
				console.log('[core] Cleared overlay icon on taskbar');
			}
		}
	}
}
```

Generally, if the `total` is > 0 and you've closed the window, we want to bring it back & add an overlay for Windows users.

This works sometimes. More often than not, on a VM I'll see the taskbar item appear, and no overlay even though it's apparently executed the function & logged to console for verification. On a host Windows 10 I consistently get proper behavior, but teammates with their own machines do not. I noticed that when running in a VM that 'fails', I can get it to work by executing the exe from a cmd window; it appears the stdout blocks something long enough to draw the overlay everytime.

![pasted image at 2016_03_15 12_43 pm](https://cloud.githubusercontent.com/assets/369698/13792906/a62e4c6a-eaca-11e5-88be-fc48a3d52ce5.png)

At a high level, it looks like there's a race condition between the `win.minimize()` & applying the overlay icon; I say this because if the window is minimized the overlay always works.

**Comment by avoidwork** [comment] 2016-03-15 20:35
The app icon is the green one at the right.

**Comment by zcbenz** [comment] 2016-03-27 02:14
Are you able to make a reproducible example?

**Comment by avoidwork** [comment] 2016-03-27 13:51
I thought that function was good enough, what would you like? The bug as I understand it currently is calling `minimize()` on a hidden window & setting the overlay on the same tick causes the overlay not to render.

I could put together a sample app tomorrow if want.

**Comment by zcbenz** [comment] 2016-03-31 10:36
I'm unable to reproduce with your code snippet, either I'm missing something or the problem you saw is probably caused by other things.

**Comment by zcbenz** [comment] 2016-04-28 03:44
Closing until more information is provided.

**Closed by zcbenz** 2016-04-28 03:44 UTC
Labels: more-information-needed
