### ISSUE TITLE
app.dock.hide() prevents any errorBox to be displayed, and freezes the app when trying to display one

### ISSUE THREAD

**Issue by tex0l** [electron/electron#6615] opened 2016-07-26 13:07 UTC
- Electron version: 1.3.0
- Operating system: OSX 10.11.6

Hi,
In my application, when I run this kind of code with an unsigned app:

``` javascript
import {app, autoUpdater} from 'electron'
import {updateURL} from './config'

app.on('ready', () => {
  autoUpdater.on('error', e => {
    console.log('an error was thrown')
    console.log(e.toString())
  })
  autoUpdater.setFeedURL(updateURL)
  console.log('autoUpdater has been fed')
})
```

I get only:

```
an error was thrown
Error: Could not get code signature for running application
```

The application is never killed, but I never get `autoUpdater has been fed`.

I was expecting the app to crash, or to keep running, but not freeze in the middle of the execution because an error was thrown through an EventEmitter. 

Is it the expected behaviour ?

**Comment by tex0l** [comment] 2016-07-26 13:30
Actually, to make this issue even more troubling, the previous code runs properly: it emits the error and keep on running.

But the following code doesn't (without showing an errorBox):
```javascript
import {app, autoUpdater, dialog} from 'electron'
import {updateURL} from './config'

app.on('ready', () => {
  autoUpdater.on('error', e => {
    console.log('an error was thrown')
    dialog.showErrorBox('error', e.toString())
  })
  autoUpdater.setFeedURL(updateURL)
  console.log('autoUpdater has been fed')
})
```
And neither this one:
```javascript
import {app, autoUpdater, dialog} from 'electron'
import {updateURL} from './config'

app.on('ready', () => {
  autoUpdater.setFeedURL(updateURL)
  console.log('autoUpdater has been fed')
})
```

Any idea where it comes from ?

**Comment by kevinsawicki** [comment] 2016-07-26 18:07
@tex0l I'm having a little trouble reproducing this.

With your example I'm seeing:

```js
app.on('ready', () => {
  autoUpdater.on('error', e => {
    console.log('error', e.toString())
  })
  autoUpdater.setFeedURL(updateURL)
  console.log('autoUpdater has been fed')
})
```

Output:

```
an error was thrown
Error: Could not get code signature for running application
autoUpdater has been fed
```

So which of your code examples is the one that isn't working properly?

**Comment by tex0l** [comment] 2016-07-26 20:18
Ok, my bad. I didn't bother to reproduce the bug in a vanilla app, sorry. It's actually a bit more complicated. Let me clarify with this vanilla example I've tested with electron-prebuilt 1.3.0 on OSX 10.11.6 :

```javascript
const {app, autoUpdater, dialog} = require('electron')

app.on('ready', () => {
  Promise.resolve()
    .then(() => {
      dialog.showErrorBox('ok', 'ok')
      // autoUpdater.on('error', e => {
      //   console.error('listener', e)
      //   dialog.showErrorBox('error', e)
      // })
      autoUpdater.setFeedURL('https://www.google.com/')
      console.log('here')
    })
    .catch(e => {
      console.error('catch', e)
      dialog.showErrorBox('error', e)
    })
})

```
In this example:
 - first an error box 'ok', 'ok' shows up
 - the `autoUpdater.setFeedURL`throws an error in the promise because no 'error' listener is set
 - the catch statement logs the error with `console.error`
 - then the app freezes as if an error box were displayed, but none is displayed.

If we try again uncommenting the commented part:
 - first an error box 'ok', 'ok' shows up
 - the `autoUpdater.setFeedURL` makes autoUpdater emit an 'error' event
 - the listener callback logs the error with `console.error`
 - then the app freezes as if an error box were displayed, but none is displayed.

Can you reproduce this ?

BTW: congratulations, it's astonishing to see how fast you handle issues with your team.

**Comment by tex0l** [comment] 2016-07-26 20:48
Sorry again, this example fails because I try to `dialog.showErrorBox('error', e)` instead of `dialog.showErrorBox('error', e.toString())` ...

I've pinpointed the exact origin of my problem and it has nothing to do with the autoUpdater:

```javascript
const { app, dialog } = require('electron')

app.on('ready', () => {
  dialog.showErrorBox('show up', 'ok')
  if (process.platform === 'darwin') {
    app.dock.hide()
  }
  dialog.showErrorBox('doesn\'t show up', 'and freezes the app')
  console.log('here')
})
```
It is only because the error box is hidden when the dock icon is hidden...

Is it the expected behaviour ? Can it be changed so that an error box would show up even if the dock icon is hidden ?

**Comment by kevinsawicki** [comment] 2016-07-26 21:14
> Is it the expected behaviour ? Can it be changed so that an error box would show up even if the dock icon is hidden ?

Yeah, this is unexpected to me but I'm not sure if it is something that can be addressed or if it is a macOS issue when an app with open dialogs is hidden from the dock, seems somewhat related to #4849

**Comment by zcbenz** [comment] 2017-05-30 09:25
I'm closing this since it is an issue of macOS, I suggest reporting this to Apple instead.

**Closed by zcbenz** 2017-05-30 09:25 UTC
Labels: fixme/bug, platform/macOS
