### ISSUE TITLE
[Feature Request]: WebRequest API: Allow to read response body

### ISSUE THREAD

**Issue by bitnom** [electron/electron#36261] opened 2022-11-06 22:46 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The WebRequest API was previously added to Electron but you can't read response bodies from the intercepted requests.

### Proposed Solution

This appears to have been added upstream to Chromium version 87.0.4280.88.

Original post: https://bugs.chromium.org/p/chromium/issues/detail?id=487422
Commits: https://github.com/SHiftLin/chromium/commits/read-response-body

### Alternatives Considered

The only other way I have heard of to accomplish the result is monkeypatching via a chromium extension.

**Comment by zcbenz** [comment] 2022-11-08 11:28
It is not added to upstream Chromium. Someone has implemented the feature in their fork as demo, but they did not upstream the code.

And we can not simply reuse the implementation, as it simply copies the whole response body to a buffer which will not work for requests that has very large response body.

I'm closing this issue as it is a duplicate of https://github.com/electron/electron/issues/8374.

**Closed by zcbenz** 2022-11-08 11:28 UTC
Labels: enhancement :sparkles:
