### ISSUE TITLE
[Bug]: after resizing the window, app zooms out completely 

### ISSUE THREAD

**Issue by J6K** [electron/electron#31723] opened 2021-11-04 21:57 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.5.1

### What arch are you using?

x64

### Expected Behavior

Resizing window does not change zoom level

### Actual Behavior

Resizing the window zooms out the app completely

### Additional Information

Keyboard command to zoom in does not work.

Need to use the menu bar to zoom in or go back to actual size

**Comment by codebytere** [comment] 2021-11-08 10:39
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests. Additionally, Electron v11 is no longer supported. You will need to demonstrate that this issue occurs on a [supported version](https://www.electronjs.org/docs/latest/tutorial/support) in order for us to proceed.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by sofianguy** [comment] 2021-11-23 05:16
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2021-11-23 05:16 UTC
Labels: platform/macOS, bug :beetle:, blocked/need-repro, 11-x-y
