### ISSUE TITLE
setTimeout not working reliably

### ISSUE THREAD

**Issue by schwiet** [electron/electron#7079] opened 2016-09-02 23:57 UTC
- Electron version: 1.3.5
- Operating system: OS X

This is going to sound ridiculous, but setTimeout is not working for me in the main process. Consider this trivial application, no windows or anything:

```
var Electron = require( 'electron' );
var app = Electron.app;  // Module to control application life.

// This method will be called when Electron has done everything
// initialization and ready for creating browser windows.
app.on('ready', function() {

  var x = 0;
  var timeout_tester = function run_again(){

    console.log( x, x, x );
    x += 1;
    setTimeout( run_again, 30 );
  };

  timeout_tester();
});
```

When I run this, I see the counter increment on the console until ~900. From then on it very sporadically fires. I cannot tell you how long it took me to track an issue I was having down to this, and even then I did not believe it. Please tell me someone can reproduce this or point out the wildly stupid thing I am doing.

Thanks in advance

**Comment by zeke** [comment] 2016-09-03 18:09
Very strange indeed. I'm observing the same behavior. I changed the log statement to:

```js
console.log(x, (new Date()).getSeconds())
```

And I see this:

```
888 31
889 31
890 31
891 31
892 31
893 31
894 31
895 31
896 41
897 51
898 52
899 2
900 12
901 22
902 32
903 42
```

**Comment by MarshallOfSound** [comment] 2016-09-03 18:15
An important thing to remember here is that `setTimeout` is **NOT** guarunteed to fire exactly the provided number of milliseconds after calling.

See this section of the MSDN docs for more information https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout#Reasons_for_delays_longer_than_specified

In particular this bit
> In addition to "clamping", the timeout can also fire later when the page (or the OS/browser itself) is busy with other tasks.

Even in Chrome and firefox my `setTimeout` calls are a few `ms` most of the time.

That being said, this does seem like quite a large jump from "just a few ms". Perhaps Electron's queue is generally a lot busier 😕

**Comment by schwiet** [comment] 2016-09-03 21:41
@MarshallOfSound: Understood. I wasn't expecting or needing it to be accurate down to milliseconds, but as you said, it's significantly worse than that and seems to happen after a certain lapse of time. Thanks @zeke for confirming/reproducing.

Any ideas? Is there a better, more idiomatic way to introduce a small delay in a repeated routine on the main process?

**Comment by zcbenz** [comment] 2016-09-12 06:19
It looks like a bug of Electron's node integration, for a temporary solution, you can probably do the timer in renderer process and send messages to the main process.

**Comment by zhang-ning** [comment] 2016-10-06 15:08
Timer in renderer process is not working reliably , too.

**Comment by schwiet** [comment] 2016-11-24 15:36
Any progress or forecast for when this might get addressed? If the answer is: No. That's fine, would just like to know. Thanks.

**Comment by brian-mann** [comment] 2017-03-09 19:24
This is a pretty devastating problem for us at Cypress.

If it helps I can put together a reproducible example.

As it stands because delays are wildly inaccurate and inconsistent it can cause flaky test failures in peoples code.

**Comment by baconface** [comment] 2017-03-10 20:48
`setTimer` has [never been accurate](http://stackoverflow.com/questions/21097421/what-is-the-reason-javascript-settimeout-is-so-inaccurate) and never will be by design. It is just usually just _good enough_. So I am unsure if this is something that can be fixed. Maybe improved but never fixed. An alternative is using a self adjusting timer. There are [guides](https://www.sitepoint.com/creating-accurate-timers-in-javascript/) and [libraries](https://www.npmjs.com/package/tick-tock) to help achieve this. But again, cannot be 100% accurate especially if you are dealing with milliseconds.

**Comment by brian-mann** [comment] 2017-03-10 21:00
The problem isn't milliseconds. It's off by orders of magnitude. Something that's supposed to respond in 500ms can take 5-10 seconds sometimes.

**Comment by schwiet** [comment] 2017-03-10 21:01
@baconface perhaps you misread the issue or didn't try it out for yourself. Passing `setTimeout()` 30 milliseconds and having your function called on the order of 10s of seconds later is well outside of a reasonable expectation of _good enough_. The suggestions in the guide you linked to would suffer from this, as well. The library you posted uses `setTimeout` under the hood. Neither reference offers anything helpful with regard to this bug.

**Comment by baconface** [comment] 2017-03-10 21:59
I read it properly. And I meant it is used because it is _good enough_ in a general context. Not just Electron. Many things can block a timer's ability to work properly. As a result it was never recommended to use this for accuracy sensitive jobs as they were never designed to be an accurate timer since they were subject to interrupts.

So when someone says it isn't working right in the render or main. There could be things to improve it but never fix it outright. This would involve redesigning timers completely.

**Comment by baconface** [comment] 2017-03-10 22:03
While this may not affect Electron. Timers in browsers are potentially [going to get worse](https://thenextweb.com/apps/2017/01/26/chrome-throttle-background-tabs-google). This change already made it out in Chromium 56 beta according to the discussion.

**Comment by michaelwoodson** [comment] 2017-05-20 19:17
FWIW, I tried adding a call to `powerSaveBlocker.start('prevent-app-suspension');` and that made the test case work much more consistently on my mac. (See #5101)

```
var Electron = require( 'electron' );
var app = Electron.app;  // Module to control application life.

// Following 2 lines are the fix (workaround?) from #5101
var powerSaveBlocker = require('electron').powerSaveBlocker;
powerSaveBlocker.start('prevent-app-suspension')

// This method will be called when Electron has done everything
// initialization and ready for creating browser windows.
app.on('ready', function() {

    var x = 0;
    var timeout_tester = function run_again(){

	console.log( x, x, x );
	x += 1;
	setTimeout( run_again, 30 );
    };

    timeout_tester();
});
```

**Comment by billorcutt** [comment] 2017-05-20 23:51
Thanks for the tip. Didn't fix my issue unfortunately. I'll create a test case and open a new issue perhaps.

**Comment by brianmmorton** [comment] 2017-06-23 15:18
Here is a potential solution that works for my use case if anyone sees it fit:

Create a bash script, timer.sh
`
#!/usr/bin/env bash

while :; do date +%s; sleep $1; done;
`
Execute that using spawn and take in the stdout to use as the timer
`
const child = spawn('bash', [__dirname + '/timer.sh', TIMEOUT_DURATION]);
child.on('exit', () => {
  console.log('process exit');
});

child.stdout.pipe(process.stdout)
child.stderr.pipe(process.stderr)
`

**Comment by zeke** [comment] 2017-06-23 18:52
@brianmmorton thanks for sharing this approach. Note however, that it probably wouldn't work for most Windows users. I know Bash on Windows is a thing now but I don't know how ubiquitous is yet.

Also I just looked in the `sleep` docs and see it supports decimals too, e.g. `sleep 0.1` for 100ms. 👍

**Comment by baconbrad** [comment] 2017-06-23 21:11
> Note however, that it probably wouldn't work for most Windows users. I know Bash on Windows is a thing now but I don't know how ubiquitous is yet.

Bash on Windows is not enabled by default. It isn't hard but you have to [change settings and meet certain requirements](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide) to get use it.

**Comment by baconbrad** [comment] 2017-06-26 18:04
@zeke Yes, I know it isn't a good practice on Github but I did it for uniformity with all my other online usernames.

**Comment by zeke** [comment] 2017-06-26 22:13
> I did it for uniformity

I just wanted to make sure my memory wasn't playing tricks on me. 😅

**Comment by tarruda** [comment] 2017-07-04 18:12
> It looks like a bug of Electron's node integration, for a temporary solution, you can probably do the timer in renderer process and send messages to the main process.

This could be a bug/feature of chromium event loop, which will run timers less often on a background tab to lower CPU usage.

One possible workaround is to use `child_process.fork` to run a pure node.js/libuv event loop, which will have reliable timers. `setTimeout` requests can be forwarded to the child, and `process.send` can be used to invoke callbacks in the main process.

**Comment by dregenor** [comment] 2017-07-06 12:56
thanks to @tarruda 

c++ simple timer implementation

```c++
#ifdef _WIN32
#include <windows.h>
#define delay(n) Sleep(n)
#else
#include <unistd.h>
#define delay(n) usleep(n * 1000)
#endif
#include <iostream>

// this simple clock application
// one available(not required) argument - timeout between ticks in milliseconds (by default 1000)

int main(int argc, char **argv) {
  int step = 1000;
  if (argc > 1) {
     step = atoi(argv[1]);
  }
  std::cout << "step: " << step << "\n";
  for (;;) {
    delay(step);
    std::cerr << "tick\n";
  }
}
```
std::cerr because on linux/windows std::cout can be buffered, 
or you can try `std::cout << "tick\n" << std::flush`

How you can use this in electron:
```TypeScript
    let timer = cp.spawn("path/to/clock", ["500"], { stdio: "pipe" });
    timer.stderr.on("data", () => { triggerCallbacks(Date.now()); });
    process.on("exit", ()=>{ timer.kill(); };
```
do not forget implement `triggerCallbacks` function. :)

**Comment by zeke** [comment] 2017-07-06 23:28
> One possible workaround is to use `child_process.fork`

@tarruda do you think this is worth creating a tutorial doc for?

**Comment by tarruda** [comment] 2017-07-07 09:36
> @tarruda do you think this is worth creating a tutorial doc for?

I don't think it would be ideal to encourage users to do this.

Not sure if the `child_process.fork` would work as I haven't tested. As @dregenor commented, in our project we use a simple C++ program to wake the main process with stdout messages(similar to @brianmmorton solution, but cross platform). We chose to do this because a new electron process would consume a lot more memory, and our requirements are simple.

I'm still not 100% sure this is a chromium bug, I assume this is because it seems to affect `setTimeout` of plain chrome renderers(if the tab is in background). If there's no hope of fixing this in the short term with a libchromiumcontent patch, maybe we could use a similar approach as a short term fix by replacing electron's `setTimeout`/`setInterval` with versions that use the hack on behalf of the users, and if/when we manage to fix in chromium, revert it.

**Comment by brian-mann** [comment] 2017-07-13 06:53
Has anyone noticed `setImmediate` also being affected? I have not but just curious.

I tried out the suggested @tarruda `fork` implementation - and it appears to be working so far.

I ended up having to replace all global `setTimeout`, `setInterval`, `clearInterval`, `clearTimeout` and adding my own lightweight queuing mechanism to manage the callback functions.

**Comment by TimNZ** [comment] 2017-08-01 03:13
I don't if this is the cause, but my setTimeout() are blowing out in an active BrowserWindow.

Using an infinite scroller component which async loads more items as container is scrolled, and a setTimeout({},1) can sometimes take 2-3 sec to trigger, after it's been executed about 10 times beforehand.

Nothing else is happening in the renderer.

What's weird is the throttling only happens when I use magic mouse to scroll to bottom of container trigger another load.

If I use the keyboard to page down to the bottom, or drag scrollbar to the bottom, no throttling.

There is no code in the Infinite Scroller component that differentiates, all tied to 'scroll' event.

I guess I'll make an example app to see if I can reproduce.

**Comment by brian-mann** [comment] 2017-08-01 05:08
Here's a gist with our code copied / pasted with the fixes for setTimeouts.

https://gist.github.com/brian-mann/94429cba31ec3a17b08649072bf15578

I'll be happy to point users directly to how it's integrated into Cypress once we open source in the next or two.

This works by spawning a forked process and using ipc with the child process (which will be spawned in node, not electron) and is not susceptible to busted timers.

You then override all of the global timers (first thing in your code) and create a lightweight queuing mechanism that reimplements setTimeout, clearTimeout, setInterval, and clearInterval.

We disable node-integration so this was only a problem outside the renderer process for us. It sounds more complicated than it really was to setup.

I can confirm that this 100% fixes the problem.

**Comment by TimNZ** [comment] 2017-08-01 05:12
Holy smoke, def a hack.

Thanks.

**Comment by brian-mann** [comment] 2017-08-01 05:20
Nothing worse than the way polyfills have worked for years and years in Javascript.

**Comment by CapOM** [comment] 2017-08-29 15:44
Just pass the command line argument "--disable-background-timer-throttling" (see https://peter.sh/experiments/chromium-command-line-switches/)

**Comment by syrnick** [comment] 2018-05-11 22:53
Node timers have other side-effects on mac os: https://github.com/nodejs/node/issues/20661 .

**Comment by Augus** [comment] 2018-06-14 10:36
@CapOM Useful answer if you run `setTimeout` in `background.js`

**Comment by MarshallOfSound** [comment] 2018-09-24 04:42
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so I'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by cristiangiagante** [comment] 2018-10-12 12:30
This is actually happens in the last version of electron 3.0.4 I have a delay near about 1000 ms

**Comment by jcollinsnw** [comment] 2019-05-10 14:37
For anyone still having this issue, I realized that VSCode was adding in

`import { setTimeout } from 'timers';`

automatically and causing this issue. I removed that and problem solved.

**Comment by qq1162667214** [comment] 2019-05-21 08:17
> For anyone still having this issue, I realized that VSCode was adding in
> 
> `import { setTimeout } from 'timers';`
> 
> automatically and causing this issue. I removed that and problem solved.

Yeah,that's it.

**Comment by huangdongqin** [comment] 2019-06-13 15:23
> For anyone still having this issue, I realized that VSCode was adding in
> 
> `import { setTimeout } from 'timers';`
> 
> automatically and causing this issue. I removed that and problem solved.

bingo!!!but why??

**Comment by sofianguy** [comment] 2019-08-09 23:17
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:05
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:05 UTC
Labels: 3-0-x, blocked/need-info ❌, bug :beetle:

**Comment by NAYCHO334** [comment] 2020-02-11 18:08
**contents.setBackgroundThrottling(allowed)**
_allowed Boolean_

> Controls whether or not this WebContents will throttle animations and timers when the page becomes backgrounded. This also affects the Page Visibility API.

**Comment by ChuckJonas** [comment] 2020-06-05 17:52
We had a simple multi-timer app using `setInterval` and noticed it was significantly slow when the tab was minimized or not in focus.  Adding `mainWindow.webContents.setBackgroundThrottling(false);`` seemed to have fixed it.
