### ISSUE TITLE
BrowserWindow.focus() does not focus

### ISSUE THREAD

**Issue by ondras** [electron/electron#5206] opened 2016-04-19 10:13 UTC
* Electron version: the one bundled with Atom 1.7.1, also 0.36.0
* Operating system: Linux

The "focus()" call does not actually focus the window, it only raises it. Focus remains in the caller app (terminal, for instance).

No "focus stealing prevention" is used. This can be reproduced on multiple window managers (xfwm, unity).

Steps to reproduce, using Atom (as an example -- works with any other Electron-based app that focuses itself):

1. open terminal
1. `atom myfile.txt`
1. switch back to terminal
1. `atom myfile.txt`
1. note that Atom raised itself, but the focus is still in terminal.

**Comment by panther7** [comment] 2016-04-19 13:32
Same problem on Windows

**Comment by zcbenz** [comment] 2016-04-20 00:37
For Linux, whether a window should be focused is depended on the desktop environment you use, and for most desktop environments it is common to prevent program from taking the focus without user's behavior.

For Windows, this is a duplicate of #2867.

**Comment by ondras** [comment] 2016-04-20 06:58
Hi @zcbenz,

> For Linux, whether a window should be focused is depended on the desktop environment you use, and for most desktop environments it is common to prevent program from taking the focus without user's behavior.

My window manager (xfwm) is (by default) configured to respect these requests for focus. And honors them -- which can be seen with basically any other application I use, including Firefox, Pidgin, Sublime Text etc.

It should be noted that Electron-based apps *try* to get focused by sending the `_NET_ACTIVE_WINDOW` ClientMessage. For some reason, they get raised but not focused.

By doing a simple `wmctrl -a`, I am able to focus an Electron-based window easily. So the window manager is 1) configured corectly, 2) focusing windows when they request it. Yet, for some strange reason, any Electron-based app fails to do so.

I would say that it is perfectly reasonable (from a UX point of view) to expect *all* apps, even those written using Electron, to behave in the same way. Currently, this behavior is present on all apps minus Electron. Looks like a bug to me.

I understand that you are busy adding features, but closing the issue without letting the second party reply to your arguments shows a bit of a STFU attitude.

**Comment by zcbenz** [comment] 2016-04-20 11:32
@ondras Thanks for the investigation work, after looking into wmctrl and Chromium's source code, the only difference seems to be wmctrl calling `XMapRaised` after sending the `_NET_ACTIVE_WINDOW` message, we should probably do the same in Electron.

**Comment by joepie91** [comment] 2016-05-31 22:21
I suspect I am running into the same issue here. openSUSE 13.1 (64-bits), XFCE4. My [application](https://git.cryto.net/joepie91/npmbar) is bound to a hotkey (F8), and is visibility-toggled when that hotkey is pressed, and [focused immediately afterwards](https://git.cryto.net/joepie91/npmbar/src/a94e22b926e14983d96aac411e09016a07c53a1d/src/app.js#L44-L47).

The following __works__:

1. Start application
2. Hit F8 to show
3. Enter search query
4. Hit F8 to hide
5. Hit F8 to show
6. Modify search query

The following __does not work__:

1. Start application
2. Hit F8 to show
3. Enter search query
4. Hit F8 to hide
5. __Type something into the previously focused window (eg. my editor)__
6. Hit F8 to show *(fails to focus, even though the window is shown correctly)*
7. Modify search query *(output goes to editor, not my Electron application)*

It's unclear to me whether this is a result of desktop environment settings, but other applications like Guake (which uses a similar visibility-toggle mechanism) do not have this issue at all.

**Closed** 2016-06-06 08:26 UTC
Labels: beginner, bug, linux

**Comment by joepie91** [comment] 2016-06-06 09:10
@zcbenz Assuming that I'm using `electron-prebuilt`, is there any particular way I can help verify that the fix resolves the issue in my case? I don't really know anything about what the build process normally looks like, or whether I can assume `master` to be in a functional state.

**Comment by zcbenz** [comment] 2016-06-06 10:37
@joepie91 You have to either wait for next release, or build Electron yourself.
