### ISSUE TITLE
[Bug]: App Crashes when loading https://google.com in BrowserWindow or BrowserView

### ISSUE THREAD

**Issue by yiheyang** [electron/electron#29917] opened 2021-06-28 16:13 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.X.X

### What operating system are you using?

macOS

### Operating System Version

macOS 11

### What arch are you using?

x64

### Last Known Working Electron version

12.X.X

### Expected Behavior

load https://google.com successfully

### Actual Behavior

app immediately crashes right after google's homepage loaded

### Additional Information

access google.com from mainland china via proxy, not sure if that cause the problem.

**Comment by nornagon** [comment] 2021-06-28 16:23
Duplicate of #29898

**Closed by nornagon** 2021-06-28 16:23 UTC
Labels: bug :beetle:
