### ISSUE TITLE
Guidance on fixing TypeScript type-definitions

### ISSUE THREAD

**Issue by zewa666** [electron/electron#16264] opened 2019-01-04 07:44 UTC
* Output of `node_modules/.bin/electron --version`: v1.8.8
* Operating System (Platform and Version): macOS

**Expected Behavior**
When reading up the docs for [BrowserWindow.setBounds](https://electronjs.org/docs/api/browser-window#winsetboundsbounds-animate) I expected the function to take a `Partial<Rectangle>` as first argument

**Actual behavior**
but instead the generated type definitions are:

```typescript
/**
  * Resizes and moves the window to the supplied bounds
  */
setBounds(bounds: Rectangle, animate?: boolean): void;
```

Now what I'd be really looking for is some minor instruction on how to contribute such fixes by myself. Looking through the [package.json of electron](https://github.com/electron/electron/blob/master/package.json#L57) I noticed the use of a [custom dependency](https://github.com/electron/electron-typescript-definitions) to generate the definitions out of a previously generated api.json from this [module](electron-docs-linter). Now the later kinda sounds like the fix needs to be done inside the documentation. So after digging around [the docs for the BrowserWindow](https://raw.githubusercontent.com/electron/electron/5ae3d1a1b2dbe11d3091d366467591d9cb21fdfe/docs/api/browser-window.md) show this content to define the method:

```
#### `win.setBounds(bounds[, animate])`

* `bounds` [Rectangle](structures/rectangle.md)
* `animate` Boolean (optional) _macOS_
```

Am I on the right track with my assumptions? If so how would I mark the Rectangle of the bounds property to be Partial. Are there any docs to see all the available constructs to be used as annotation or which features of TS are supported (think of Unions, Conditional Types etc.)

**Comment by zewa666** [comment] 2019-01-04 08:02
Whats even more funny, providing only `x` and `y` and omitting `width` and `height` leads to an exception. So clearly something is wrong with the docs or behavior of this method

**Comment by MarshallOfSound** [comment] 2019-01-05 04:07
If we were writing the definitions in plain typescript you are correct @zewa666 we would use `Partial<Rectangle>` however we aren't 😆for many long and annoying reasons that are much wider spreading that this issue.

The way we would do this with our current auto-generation set up is either declare those properties as optional in markdown in a new PartialRectangle structure.  E.g.

```markdown
#### `win.setBounds(bounds[, animate])`

* `bounds` [PartialRectangle](structures/partial-rectangle.md)
* `animate` Boolean (optional) _macOS_
```

or the better (IMO) way to do it would be to introduce a new `(partial)` tag similar to our `(optional)` tag that the linter and typescript generator would read to generate a `Partial<T>` instead of just `T`.

All this is a bit interesting because I'm currently rewriting our docs parsing logic to be lossless (`electron-docs-linter` is actually lossy at the moment, random bits of paragraphs code blocks and such get lost during the parsing process).  Happy to push that work up somewhere if you want to play with it but it wouldn't be a good idea IMO to implement this in `electron-docs-linter` when I'm about to blow it out of the water 😆

**Comment by MarshallOfSound** [comment] 2019-01-05 04:09
As a side note (untested) our current typescript generator is literally just based on strings, you might just be able to do this and it would work.


```markdown
#### `win.setBounds(bounds[, animate])`

* `bounds` [Partial<Rectangle>](structures/rectangle.md)
* `animate` Boolean (optional) _macOS_
```

**Comment by zewa666** [comment] 2019-01-06 07:15
@BinaryMuse ok that clarifies this issue. I'm on 1.8.8 so all good.

@MarshallOfSound I think the Tag approach sounds promising just needs some grammar rules for multiple cases like partial and optional.
I'll check out the string approach tomorrow back in office

**Comment by zewa666** [comment] 2019-01-07 07:21
@MarshallOfSound ok I've tried out your last comments approach, which fails with:
```
index.d.ts(1759,23): error TS2314: Generic type 'Partial' requires 1 type argument(s).
```

and creates this as a resulting d.ts

```typescript
/**
     * Resizes and moves the window to the supplied bounds. Any properties that are not
     * supplied will default to their current values.
     */
    setBounds(bounds: Partial, animate?: boolean): void;
```

Note the lack of the generic type argument.

**Comment by vladimiry** [comment] 2019-07-23 15:59
@BinaryMuse the issue is being labeled with documentation label but it doesn't seem to be documentation problem. Documentation is correct but typescript declaration is wrong.

**Comment by MarshallOfSound** [comment] 2019-07-23 16:09
@vladimiry The TS defs are generated from our docs, if the defs are wrong it's a documentation issue.

**Comment by vladimiry** [comment] 2019-07-23 18:04
Got it. It's just a little misleading seeing just "documentation" label here while the solution requires fixing the code (presumably scripts that generate the ts-defs from the docs).

**Comment by zewa666** [comment] 2019-07-23 18:27
Ouch thats quite long ago. My feature story at that time got abandoned so I didnt follow up on this any longer. @MarshallOfSound did you make any progress with your docs-gen rewrite?

**Comment by MarshallOfSound** [comment] 2019-07-24 00:43
@zewa666  The rewrite has landed and `Partial<Rectangle>` should be super easy to support now 👍 

Case and point, here's a PR --> https://github.com/electron/electron/pull/19416

**Closed** 2019-07-24 06:51 UTC
Labels: documentation :notebook:
