### ISSUE TITLE
webview and preload do not work when there is no script tag in HTML

### ISSUE THREAD

**Issue by tangrui** [electron/electron#1117] opened 2015-02-10 01:06 UTC
I have a very little demo like this:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Hello World!</title>
    </head>
    <body>
        <webview src="https://www.google.com/" autosize="on" minwidth="576" minheight="432"></webview>
    </body>
</html>
```

When I run the application, I get a blank page, nothing displayed. But if I add some script to the page, the webview will render. e.g.:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Hello World!</title>
    </head>
    <body>
        <script>console.log("Hello World");</script>
        <webview src="http://www.baidu.com/" autosize="on" minwidth="576" minheight="432"></webview>
    </body>
</html>
```

**Comment by tangrui** [comment] 2015-02-10 02:52
I'm using atom-shell v0.21.2 on OSX.

**Comment by frankhale** [comment] 2015-02-10 03:38
I can confirm this behavior on Windows 8.1 as well with Atom-Shell 0.21.2. 

FWIW, I was able to get the webview in the first HTML file (without the script tag) to work by opening the DevTools and hitting F5 to refresh.

**Comment by zcbenz** [comment] 2015-02-10 13:12
Chrome has an "optimization" that if there is no script in HTML then it will not create script context in the page, this unfortunately disabled our scripts that injected into the page, which resulted in `<webview>` not working.

**Comment by thyrrestrup** [comment] 2015-05-18 13:35
Any news on this issue?

**Comment by Tribex** [comment] 2015-05-18 14:36
@thyrrestrup I think for now you just ought to add a script tag. An interesting idea though would be to have the webview auto-insert one (if a better work-around cannot be found).

**Comment by thyrrestrup** [comment] 2015-05-18 18:21
@Tribex - How would you do that? Is it something I can do on my side?

**Comment by Tribex** [comment] 2015-05-18 22:53
@thyrrestrup It depends, what does your app look like? It should be as simple as adding a tiny scripts before the webview tag.

**Comment by thyrrestrup** [comment] 2015-05-22 18:07
@Tribex - The issue I'm having is this #1580. It's related to this issue. The problem is that I don't have control over the content being loaded through the webview (it's an online resource) so I can't add script tags inside the page to make the preload script load.

-Tobias

**Comment by Tribex** [comment] 2015-05-22 23:05
@thyrrestrup So what you're saying is your window loads content from another location, which contains a webview, but no script tags?
In this case you *could* add a preload script to the window and have it inject a script tag, though that might be a bit hacky.

**Comment by danielisaksen** [comment] 2015-08-05 03:55
I am experiencing this issue as well, on Windows Server 2012 R2 (equivalent to Windows 8.1). I am using `electron-prebuilt` from NPM during development.

Is it possible to fix this issue in the electron repo, alternately add a warning note to add a non-empty `<script>` tag to the host page at [web-view-tag.md](https://github.com/atom/electron/tree/master/docs/api/web-view-tag.md)?

I am asking considering adding a small `<script`> before the `<webview>` tag is not obvious unless explicitly specified in the documentation. Nonetheless, having to do that is "wonky".

**Comment by frankhale** [comment] 2015-08-05 04:30
I think documenting this would be helpful. Would you consider adding this to https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md and submitting a pull request?

That said, I think @zcbenz said it best with his comment on Feb 10th (see above). In my opinion I think this issue should be closed. The solution is to just create a script tag. I think it's fairly unlikely if you are using Electron to write an app that you won't have a script tag.

**Comment by danielisaksen** [comment] 2015-08-05 04:32
I was to use a seperate window to bootstrap and a script-less window to host the `<webview>`, but that is just silly I suppose. Not really common, but still prone to being a nuisance. I will fork, modify and submit a pull request.

**Comment by frankhale** [comment] 2015-08-05 04:34
can you add a script tag before your webview tag?

**Comment by danielisaksen** [comment] 2015-08-05 04:36
Elaborate? If you are referring to the issue I experienced, which was why I was posting here to begin with, I did add a `<script`> tag before the `<webview>` tag, and the issue was fixed for me. I just did `console.log("");`

**Comment by frankhale** [comment] 2015-08-05 04:46
@zcbenz, already mentioned why the behavior happens. If adding a script tag fixes it we should close this issue as this is expected behavior from Chrome. Is it unfortunate? Yes, but in the same breath Electron apps are special and it's very unlikely that they won't contain a script tag. I'm playing devil's advocate here, not trying to be an ass but this smells of a Chrome issue (or not an issue at all but designed specifically this way) not an Electron one.

**Comment by danielisaksen** [comment] 2015-08-05 04:48
I do agree with you, but I also think it can be a nuisance to some developers, which is why I am asking if it will be fixed or documented. I will add it to the documentation ASAP. I do not understand why this conversation still is going. This is most likely a Chromium/CEF issue. Most certainly feels like one anyway.

**Comment by frankhale** [comment] 2015-08-05 04:53
I totally agree, the web-view documentation should mention that you have to have a script tag otherwise bad things will happen, LOL!

**Comment by eshikafe** [comment] 2015-10-10 10:45
Even adding a <script> above the <webview> tag is not working - still not displaying the webpage. I am using Windows 7 + Chrome Version 45.0.2454.101. The issue is not yet fixed.

**Comment by Tribex** [comment] 2015-10-10 11:55
@eshikafe You also need to run something inside of the script. A simple `console.log` will suffice.

**Comment by eshikafe** [comment] 2015-10-10 13:55
I did that. It did not work.

**Comment by maxogden** [comment] 2015-11-13 18:34
@zcbenz Do you know if there is a chromium issue for this? So we can track the upstream "block" status. Or even a link to the optimization you mentioned here https://github.com/atom/electron/issues/1117#issuecomment-73696516

**Comment by zcbenz** [comment] 2015-11-16 02:07
@maxogden I can not find a Chromium issue for this, it is probably because it is not a bug in Chromium.

**Comment by PalmerAL** [comment] 2015-11-30 23:46
You can work around this issue by sending an IPC message to the webview, something like this worked for me:

```

webview.addEventListener("did-finish-load", function(e) {
    this.send("dummy-ipc-message");
});
```

**Closed** 2016-04-12 06:32 UTC
Labels: blocked, bug, webview
