### ISSUE TITLE
Focused elements don't blur when Spotlight or similar windows appear

### ISSUE THREAD

**Issue by xywz** [electron/electron#5995] opened 2016-06-10 20:02 UTC
In non-Electron applications they do.

* Electron version: 1.2.2
* Operating system: OS X

**Comment by zcbenz** [comment] 2016-06-13 01:24
This is because unlike native elements, web pages do not have the concept of [key windows](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/WinPanel/Concepts/ChangingMainKeyWindow.html), so browsers do not change focused state when the window is not key window anymore but still being a main window. You can reproduce the same behaviors in the web pages opened in Chrome and Safari.

We are not able to fix on Electron's side, to fix it we have to make the page keep focused state while do not have a focused element, which is not possible without changes to Chromium and probably web standards.

I'm closing this won't fix.

**Closed by zcbenz** 2016-06-13 01:24 UTC
