### ISSUE TITLE
child_process.fork() process are not getting terminated in electronjs when created from rendered process

### ISSUE THREAD

**Issue by workswithweb** [electron/electron#7084] opened 2016-09-03 14:26 UTC
* Electron version: v1.3.5
* Operating system: Ubuntu 16.04 LTS

In electronjs app, if I create new process using child_process.fork() from electron renderer process and if I close the electron app or kill electron process, my app gets closed and all electron process are terminated expect the process I created with child_process.fork() (it still runs as separate node process. I can see it in Ubuntu process manager) however if I create same process from electrons main process, all process gets terminated along with process I created with child_process.fork(). How do I make sure to terminate all process created with child_process.fork() from renderer process? Would this be a bug in electron?
![when_electron_app_running](https://cloud.githubusercontent.com/assets/17054312/18225484/6e824454-71b8-11e6-8c8e-6899206a5ffa.png)
![after_electron_app_terminated](https://cloud.githubusercontent.com/assets/17054312/18225485/7052a454-71b8-11e6-937b-d385faef9c1a.png)

**Comment by ClementNerma** [comment] 2016-09-03 20:43
When you close this process, run your application again and close it, is there still an electron process running ?

**Comment by workswithweb** [comment] 2016-09-03 22:57
Yes, there is new node process created again when I kill and re-run the app.
If I open and kill app 5 times, I see 5 node process created (each time I
open app, and run child_process.fork() from renderer process, and kill app,
new node process is getting created and not getting destroyed.). As mention
in issue, it gets killed when forked from main process but not from
renderer process.

**Comment by ClementNerma** [comment] 2016-09-04 08:33
When you say you 'kill' your application, you mean 'exit' (process.exit, ALT+F4...) or 'kill' (killing in task manager for example).

**Comment by workswithweb** [comment] 2016-09-04 13:58
kill = app.quit() or CTRL+C from terminal.

**Comment by singhshashi** [comment] 2016-09-04 14:15
From the [documentation](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) of child_process.fork() 

> 
It is important to keep in mind that spawned Node.js child processes are independent of the parent with exception of the IPC communication channel that is established between the two. Each process has it's own memory, with their own V8 instances. Because of the additional resource allocations required, spawning a large number of child Node.js processes is not recommended.

Electron is built on top of Chromium and I think Chromium takes care of ending all processes spawned/forked  from the main process. This can be seen in the Chrome browser , where if the main process is killed all the tabs and other related processes are also ended. 

I don't think the same is implemented for processes spawned/forked from the renderer process. For that, you can save the reference to the child process when you spawn it and later kill it yourself. 

e.g 
```

child_process = spawn(scriptPath,[arg1, arg2 ] ,{detached:true});

process.kill(-child_process.pid);

```

**Comment by ClementNerma** [comment] 2016-09-04 14:15
Really strange... Can you provide a minimal app to reproduce this problem ?

**Comment by workswithweb** [comment] 2016-09-04 16:35
This is what I do in rendere process.
var child_process = require('child_process');
var process1 = child_process.fork('./workers.js');

You can look into my code in below file (I just added for debugging)
https://github.com/workswithweb/MQTTBox/blob/0.1.1/src/app/services/MqttClientService.js

I did same in main process and works fine. (all forked process gets closed
on app close.)

**Comment by zcbenz** [comment] 2016-09-12 07:27
I can also reproduce on macOS, it is probably because Electron didn't cleanup Node state in renderer process.

**Comment by kevinsawicki** [comment] 2016-09-19 18:07
> How do I make sure to terminate all process created with child_process.fork() from renderer process? Would this be a bug in electron?

On macOS, I'm seeing the forked process stay around after quit regardless of if they are forked from the main or renderer process.

But it looks like node (6.3.0) behaves the same if I run `node index.js` with the following `index.js`:

```js
require('child_process').fork('./forever.js')
process.exit(0)
```

with `forever.js` containing:

```js
setInterval(function () {
  console.log('hey')
}, 10000)
```

I see the forked `node` process hang around after the first process exits.

**Comment by zcbenz** [comment] 2016-09-20 06:53
I can also reproduce with Node 6.6.0, so this is either an expected behavior or a bug of upstream Node. I suggest reporting this to Node's issues list instead and I'm closing this since it is an upstream bug.

**Closed by zcbenz** 2016-09-20 06:53 UTC
Labels: bug, more-information-needed
