### ISSUE TITLE
window.open returns undefined in child iframes

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#7090] opened 2016-09-04 23:51 UTC
* Electron version: all
* Operating system: OSX

[Example repo is here.](https://github.com/brian-mann/electron-iframe-window-open-bug)

If you embed an `<iframe>` and then within that `<iframe>` you do this:

```javascript
// child returns undefined
var child = window.open(...)
```

`child` will be `undefined`, instead of the `BrowserWindowProxy `.

Changing the code to this works by returning the proxy:

```javascript
var child = window.top.open(...)
```

In my case I am embedding guest content in an `<iframe>` and cannot force the users to update their code.

**Comment by deepak1556** [comment] 2016-09-06 05:43
Duplicate of https://github.com/electron/electron/issues/6617, merging to https://github.com/electron/electron/issues/2644

**Closed by deepak1556** 2016-09-06 05:43 UTC
