### ISSUE TITLE
webContents.print doesn't work on Windows 

### ISSUE THREAD

**Issue by fxckdead** [electron/electron#5103] opened 2016-04-10 06:18 UTC
* Electron version:0.37.2
* Operating system: Windows 7 Pro 64 Bits 
* node: 4.4.2

I'm working on a Kiosk App and i use my Macbook to do it, but, the soft will run on Windows, so, i did everything on my macbook, and everything works fine, but, when i was on the windows machine and build the release for windows, it doesn't print, and don't show any error, so idk how to debug it.

I'm using the Printer Api included in Electron, and like i said, in osx it works !, i'm doing this:

    var window = BrowserWindow.getFocusedWindow();
    window.webContents.print({
        silent:true
    });

The thing is, if i use the print with `silent:false` and i select some printer it send the task, but it's never printed (i can saw just for a sec the print queue but it disappear immediately). So, i tried to do a `printToPDF()` and it works, it saves the PDF, i can see it.

I tried to send the task to a "PDFGenerator printer" and it generates a PDF but, it says that it's "not a pdf or corrupt" 

I hope this make sense to anyone.

Related issue #5093 

PD: I just make the same question on [Stackoverflow](http://stackoverflow.com/questions/36509989/electron-printing-on-windows-doesnt-work) and [atom.discuss](https://discuss.atom.io/t/printing-on-windows-doesnt-work/27674)

**Comment by mnquintana** [comment] 2016-04-10 07:28
Thanks for the report! This looks like a duplicate of https://github.com/electron/electron/issues/4906 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-04-10 07:28 UTC
