### ISSUE TITLE
[Bug]: Crash in SecondWeakCallback with electron 13

### ISSUE THREAD

**Issue by t57ser** [electron/electron#30019] opened 2021-07-05 16:12 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.985

### What arch are you using?

x64

### Expected Behavior

No crash

### Actual Behavior

App crashes.
I was unable to create a reproducable example till now. It does not happen often but I was able to get a crashlog and view the call stack with visual studio
![image](https://user-images.githubusercontent.com/10595986/124498162-33591b80-ddbc-11eb-90fe-183c4417618b.png)
[040cccc3-b16c-4bd4-a090-4e7e964e941a.zip](https://github.com/electron/electron/files/6765435/040cccc3-b16c-4bd4-a090-4e7e964e941a.zip)

**Comment by VerteDinde** [comment] 2021-07-06 19:39
@t57ser Thanks for reporting this issue! Just trying to get a bit more information on the crash - did you notice this starting with any version of Electron 13+, or did it seem to start in 12 specifically? I know you don't have a repro, but any additional information would be awesome 🙇‍♀️

**Comment by t57ser** [comment] 2021-07-06 19:48
This seemed to start with 13, I never tried with 12 so I can not comment on that. I don't remember seeing this in 11.
I don't know if there is a relation but as far as I know the last log output in my app log was always a did-start-loading event, but this could be a coincidence or maybe there is something happening afterwards that causes it.

**Comment by t57ser** [comment] 2021-07-08 12:07
[71641ef1-35c9-4ab9-a2e7-bfe748854a41.zip](https://github.com/electron/electron/files/6784264/71641ef1-35c9-4ab9-a2e7-bfe748854a41.zip)
Crash happened again, log attached, looks a bit different
![image](https://user-images.githubusercontent.com/10595986/124918798-be712600-dff5-11eb-9839-b0e097102e7c.png)

**Comment by t57ser** [comment] 2021-07-08 12:45
This happened with 13.1.6

**Comment by t57ser** [comment] 2021-07-09 07:49
Another one:
![image](https://user-images.githubusercontent.com/10595986/125043091-e1a1e100-e09a-11eb-97ac-dfb06dfac46e.png)

**Comment by VerteDinde** [comment] 2021-07-14 04:50
Linking to a related issue, which is also showing the crash in `gin_helper::CallbackHolderBase::SecondWeakCallback`:  #27482

The linked crash seems to be specific to closing a window - @t57ser, sorry, I'm working on adding an additional crash key that can hopefully tell us which component these crashes are originating from, so we have some more actionable information in the crash report. I'm aiming to get these crash keys into an upcoming beta release.

Do you happen to have any data on when these crashes are occurring for you? For example: closing a window, opening a notification, triggering the desktop capturer, clicking the app in the tray, etc? There are about ~20 files that could potentially hold an active reference after their gin_wrappable has been deleted; I know you mentioned a `did-start-loading event` upthread, but any other information would be appreciated 🙇‍♀️

**Comment by NhaLeader** [comment] 2021-07-14 05:24
K

**Comment by t57ser** [comment] 2021-07-14 06:18
It always happens when the app restores the users previous state (startup). During that windows are opened and loaded. There is surely no notification, desktop capturer or tray click happening. Though it's possible that the initial window is getting closed.

**Comment by t57ser** [comment] 2021-07-27 09:52
[821c3dcf-cfe6-463b-99d4-0a2bd90f49b1.zip](https://github.com/electron/electron/files/6884500/821c3dcf-cfe6-463b-99d4-0a2bd90f49b1.zip)

**Comment by t57ser** [comment] 2021-08-04 13:57
[d959a1a8-71f0-4604-b4cb-0dd5baa0cbdd.zip](https://github.com/electron/electron/files/6931768/d959a1a8-71f0-4604-b4cb-0dd5baa0cbdd.zip)
This is with electron 13.1.8, not sure if the new crash key is already there

**Comment by nornagon** [comment] 2021-08-04 20:05
Interesting, looks like it's not one of the ones we tagged (or, possibly, our tagging code isn't functioning as intended)

```
  module_list[0].annotation_objects["gin-wrappable-fatal.location"] = Deleted kWrapperInfo does not match listed component. Please review listed crash keys.
```

**Comment by nornagon** [comment] 2021-08-04 22:59
looks like we were still missing some keys. https://github.com/electron/electron/pull/30404

**Comment by t57ser** [comment] 2021-08-15 17:28
[3fa50a30-eb7b-48e3-bab8-7515234affab.zip](https://github.com/electron/electron/files/6988560/3fa50a30-eb7b-48e3-bab8-7515234affab.zip)
with electron 13.1.9

**Comment by VerteDinde** [comment] 2021-08-17 16:29
@t57ser We just released version 13.2.0 that contains additional crash keys - if you wouldn't mind sharing crash data using that version, that would be very helpful. Thank you so much for all of your time with this and for sharing so much data, it's been a huge help! Hopefully we can get this fixed for you soon 🙇‍♀️

**Comment by t57ser** [comment] 2021-08-18 13:13
[6902bf65-7819-48b8-b462-a60b4f4e9779.zip](https://github.com/electron/electron/files/7007442/6902bf65-7819-48b8-b462-a60b4f4e9779.zip)
Here you go :)

**Comment by nornagon** [comment] 2021-08-18 18:29
sad news 😭 :

```
  simple_annotations["ver"] = 13.2.0
  module_list[0].annotation_objects["gin-wrappable-fatal.location"] = Deleted kWrapperInfo does not match listed component. Please review listed crash keys.
```

**Comment by t57ser** [comment] 2021-08-25 08:14
![grafik](https://user-images.githubusercontent.com/10595986/130753378-fda50777-0fe6-4d3b-a72c-70ffb1ddf7c7.png)
with one of the crashlogs, visual studio showed this, I don't remember seeing this previously, does it help?

**Closed** 2021-09-16 08:33 UTC
Labels: platform/windows, crash :boom:, bug :beetle:, 13-x-y, 14-x-y
