### ISSUE TITLE
Electron crashes on showErrorBox in certain conditions

### ISSUE THREAD

**Issue by horymury** [electron/electron#13048] opened 2018-05-23 12:47 UTC
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 10 x64
* Last known working Electron version: -

**Expected Behavior**
When showing a modal error message(electron.dialog.showErrorBox), I expect to not being able to manipulate the electron main app window and main process not to consequently crash.

**Actual behavior**
When a modal error message (electron.dialog.showErrorBox) is shown, I am able to press the context menus of the main window. After randomly pressing the context menu items of the main window, closing the error box always results in a crash. This originally happened to one of our production electron based applications.

**To Reproduce**
Created a small app based on the quick startup repo, with only a button which triggers a dlg error.  Also added a link to a video reproducing the issue on the **Additional information** step. 
https://github.com/horymury/electron_crash

**Screenshots**

**Additional Information**
Video with the issue here:
https://drive.google.com/open?id=1KtAuXntDTfpaaHkaRG7m18mC0fRvGsNR

**Comment by vwvww** [comment] 2018-06-10 13:35
I could also reproduce it on Ubuntu 16.04, and could not reproduce it on macOS High Sierra 10.13.4. Can I take this issue, if there is nobody working on?

**Comment by horymury** [comment] 2018-06-11 08:37
would be great if this gets fixed! thank you.

**Comment by sofianguy** [comment] 2019-08-09 00:43
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 21:03
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 21:03 UTC
Labels: 2-0-x, blocked/need-info ❌, bug/crash :boom:, platform/windows
