### ISSUE TITLE
webRequest.onBeforeSendHeaders is dead on service worker

### ISSUE THREAD

**Issue by mihaiav** [electron/electron#23486] opened 2020-05-09 22:40 UTC
### Issue Details
I'm trying to add extra headers(e.g. cache-control) to local files using a service worker(the only thing that seems to work<kind of>) The issue is that the service worker requests are no longer intercepted by ``webRequest.onBeforeSendHeaders`` and this breaks my application. Is this a known bug? Why service worker requests are not intercepted by webRequest.onBeforeSendHeaders ?

```
  const remoteFilter = {
      urls: ['https://*.example.com/*']
    };
        session.defaultSession.webRequest.onBeforeSendHeaders(localFilter, (details, callback) => {
                throw("i'm working");
        });

```

* **Electron Version:**
  8.2.5
* **Operating System:**
 MacOS
* **Last Known Working Electron version:**
  8.2.5

### Expected Behavior
throw()/get called  when a remote resources  matching the filter is requested (via a service worker).
### Actual Behavior
It does nothing
### To Reproduce
on app "ready" event add the handler below:

  ```
  const remoteFilter = {
      urls: ['https://*.example.com/*']
    };
        session.defaultSession.webRequest.onBeforeSendHeaders(localFilter, (details, callback) => {
                throw("i'm working");
        });

```

**Comment by JimminiKin** [comment] 2020-09-20 17:41
Encountering the same issue on linux here. From what I can see it's happening since 7.x.x

I created a small reproduction repo : 
 - [Broken version on 7.x](https://github.com/JimminiKin/demo_sw_events_issues_elec/tree/7xKO) 
 - [Working version on 6.x](https://github.com/JimminiKin/demo_sw_events_issues_elec/tree/6xOK)

In this repo the renderer calls for the same CORS restricted api that can only be called with a https://example.com Origin in two ways : 

 - One directly in the renderer
 - The other where the fetch happens in the Service Worker

The main process registers onBeforeSendHeaders to add the needed Origin to the headers to bypass CORS.

The handler is called in both cases but doesn't seem to have any effect on the Service Worker side.

**Comment by HyperClockUp** [comment] 2020-12-31 08:28
So how can service worker requests a CORS fetch? session.defaultSession.webRequest cannot  make it.

**Comment by electron-triage** [comment] 2021-03-10 18:30
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Closed by electron-triage** 2021-03-10 18:30 UTC
Labels: 8-x-y, bug :beetle:, platform/macOS
