### ISSUE TITLE
Electron hangs when I add session to the app

### ISSUE THREAD

**Issue by tarjei** [electron/electron#7183] opened 2016-09-13 06:18 UTC
* Electron version: 1.3.5
* Operating system: Ubuntu 14.04

I tried to add the following to my app:
```
app.on('ready', async() => {
  await installExtensions();
  const {session} = require('electron')
  const ses = session.fromPartition('persist:name')

    mainWindow = new BrowserWindow({
        show: false,
        width: 1400,
        height: 900,
        webPreferences: {
          session: ses
        }
    });
```

And now it just hangs when I start it. This is using 1.3.5. I'm not sure, but it seems related.

I run the app with the following command:
`node_modules/.bin/electron  -r babel-register -r babel-polyfill ./main.development.js `

Babel version:
"babel-core": "^6.14.0",
    "babel-eslint": "^6.1.2",
    "babel-loader": "^6.2.5",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-plugin-webpack-loaders": "^0.7.1",
    "babel-polyfill": "^6.13.0",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-react-optimize": "^1.0.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.14.0",

If I remove `session:sess` from the BrowserWindow options then the application loads perfectly.

**Comment by tarjei** [comment] 2016-09-13 06:20
This also happens if I try to use `partition: 'persistent:foo'` instead of session.

**Comment by tarjei** [comment] 2016-09-13 08:12
Output of `--enable-logging`:
```
$ node_modules/.bin/electron --enable-logging  -r babel-register -r babel-polyfill ./main.development.js 
[22980:0913/101108:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[22980:0913/101109:ERROR:nss_util.cc(842)] After loading Root Certs, loaded==false: NSS error code: -8018
```

**Comment by deepak1556** [comment] 2016-09-13 08:13
`session` and `partition` options works fine as far as I tested, might be something wrong with the application. Can you provide a minimal app that reproduces the problem ?

**Comment by tarjei** [comment] 2016-09-13 08:23
More output:

```
[23719:0913/102154:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[23721:0913/102154:VERBOSE1:zygote_main_linux.cc(600)] ZygoteMain: initializing 0 fork delegates
[23721:0913/102154:INFO:systeminfo.cc(82)] Available number of cores: 4
[23719:0913/102156:VERBOSE1:gpu_info_collector_x11.cc(25)] NVCtrl extension does not exist.
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(849)] All gsettings tests OK. Will get proxy config from gsettings.
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(1605)] Obtained proxy settings from GSETTINGS
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(849)] All gsettings tests OK. Will get proxy config from gsettings.
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(1605)] Obtained proxy settings from GSETTINGS
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(849)] All gsettings tests OK. Will get proxy config from gsettings.
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(1605)] Obtained proxy settings from GSETTINGS
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(849)] All gsettings tests OK. Will get proxy config from gsettings.
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(1605)] Obtained proxy settings from GSETTINGS
[23719:0913/102156:VERBOSE1:bus.cc(720)] Requested to remove an unknown filter function: 1 with associated data: 0x2347446e75a0
[23719:0913/102156:VERBOSE1:bluez_dbus_manager.cc(172)] Bluetooth not supported.
[23719:0913/102156:ERROR:nss_util.cc(842)] After loading Root Certs, loaded==false: NSS error code: -8018
[23769:0913/102156:VERBOSE1:child_thread_impl.cc(343)] Mojo is enabled on child
[23773:0913/102156:VERBOSE1:child_thread_impl.cc(343)] Mojo is enabled on child
[23767:0913/102156:VERBOSE1:child_thread_impl.cc(343)] Mojo is enabled on child
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(1717)] Detected no-op change to proxy settings. Doing nothing.
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(1717)] Detected no-op change to proxy settings. Doing nothing.
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(1717)] Detected no-op change to proxy settings. Doing nothing.
[23719:0913/102156:VERBOSE1:proxy_config_service_linux.cc(1717)] Detected no-op change to proxy settings. Doing nothing.
[23719:0913/102156:VERBOSE1:navigator_impl.cc(201)] Failed Provisional Load: ask://root/, error_code: -3, error_description: , showing_repost_interstitial: 0, frame_id: 1
```

It seems to be related to me using a custom protocol. I'll try to create a minimal app

**Comment by tarjei** [comment] 2016-09-13 08:30
OK, here's a minimal version:

main.js:
```
const { session, protocol, app, BrowserWindow, Menu, shell } = require('electron');

const path = require('path')
const URL = require('url');


let menu;
let template;
let mainWindow = null;


if (process.env.NODE_ENV === 'development') {
    require('electron-debug')(); // eslint-disable-line global-require
}

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') app.quit();
});


//protocol.registerStandardSchemes(['ask'])

app.on('ready', () => {

  protocol.registerFileProtocol('ask', (request, callback) => {
      let url = URL.parse(request.url)
      let filename = url.pathname
      if (url.pathname == '/') {
        filename = 'index.html'
      }
      console.log("Req:", request, path.normalize(`${__dirname}/${filename}`))
      callback({ path:  path.normalize(`${__dirname}/${filename}`) })
  }, (error) => {
      if (error) console.error('Failed to register protocol')
  })

  protocol.registerServiceWorkerSchemes(['ask'])

    mainWindow = new BrowserWindow({
        show: false,
        width: 1400,
        height: 900,
        webPreferences: {
          // https://github.com/electron/electron/issues/7183
         partition: 'persistent:ask',
        }
    });

    mainWindow.loadURL('ask://root/');
    //mainWindow.loadURL(`https://gt`);

    mainWindow.webContents.on('did-finish-load', () => {
        mainWindow.show();
        mainWindow.focus();
    });

    mainWindow.on('closed', () => {
        mainWindow = null;
    });

});
```

index.html: 
```
<h1>Hello world </h1>
```

Running this without the `partition` key results in the hello world window.

**Comment by tarjei** [comment] 2016-09-13 08:33
q: Would it be better for me if I just started a http server on localhost instead of using a custom protocol? Are custom protocols buggy?

**Comment by tarjei** [comment] 2016-09-13 08:41
Note: electron actually emits a failed-provisional-load error: 
app.on("did-fail-provisional-load", (error_code, error_description, url) => {
  console.error('Failed provisional load:', error_code, error_description, url)
})

**Comment by deepak1556** [comment] 2016-09-13 08:42
The problem is you have registered the protocol handler to the default partition but loading the window in a different partition, hence the url doesn't load.

```
const { session, protocol, app, BrowserWindow, Menu, shell } = require('electron');

const path = require('path')
const URL = require('url');


let menu;
let template;
let mainWindow = null;


if (process.env.NODE_ENV === 'development') {
    require('electron-debug')(); // eslint-disable-line global-require
}

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') app.quit();
});


//protocol.registerStandardSchemes(['ask'])

app.on('ready', () => {
  const partition = 'persistent:ask'
  const ses = session.fromPartition(partition)

  ses.protocol.registerFileProtocol('ask', (request, callback) => {
      let url = URL.parse(request.url)
      let filename = url.pathname
      if (url.pathname == '/') {
        filename = 'index.html'
      }
      console.log("Req:", request, path.normalize(`${__dirname}/${filename}`))
      callback({ path:  path.normalize(`${__dirname}/${filename}`) })
  }, (error) => {
      if (error) console.error('Failed to register protocol')
  })

  protocol.registerServiceWorkerSchemes(['ask'])

    mainWindow = new BrowserWindow({
        show: false,
        width: 1400,
        height: 900,
        webPreferences: {
          // https://github.com/electron/electron/issues/7183
         partition: partition,
        }
    });

    mainWindow.loadURL('ask://root/');
    //mainWindow.loadURL(`https://gt`);

    mainWindow.webContents.on('did-finish-load', () => {
        mainWindow.show();
        mainWindow.focus();
    });

    mainWindow.on('closed', () => {
        mainWindow = null;
    });

});
```

Also for persistent partitions should use `persist:<partition_name>` not `persistent:`. Closing this out since its not a bug in Electron.

**Closed by deepak1556** 2016-09-13 08:42 UTC
Labels: more-information-needed

**Comment by deepak1556** [comment] 2016-09-13 08:44
Thanks for the test case!

> Are custom protocols buggy?

Nope, they work fine for their intended behavior.

**Comment by tarjei** [comment] 2016-09-13 08:47
Thanks a bundle for helping me resolve this one! Good work. :)

**Comment by tarjei** [comment] 2016-09-13 08:48
When should the `registerStandardSchemes` and `registerServiceWorkerSchemes` methods be used? I'm a bit confused about those two.

**Comment by deepak1556** [comment] 2016-09-13 08:52
Well if you want the pages loaded over custom schemes to handle service workers then should register with `registerServiceWorkerSchemes`. `registerStandardSchemes` should be used for the scenarios described in the [documentation](https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocolregisterstandardschemesschemes)

**Comment by tarjei** [comment] 2016-09-13 09:12
OK, thanks.
