### ISSUE TITLE
[Bug]: Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: ERR_FAILED (-2)

### ISSUE THREAD

**Issue by webappdevelp** [electron/electron#29188] opened 2021-05-17 11:30 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version

### What arch are you using?

x64

### Expected Behavior

use webview to load a same url, then throw the error info: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: ERR_FAILED (-2)

### Actual Behavior

```html
<webview id="printPage" class="webview print" :src="printUrl"></webview>
```
```javascript
<script>
export default {
    setup() {
       useOnBroadcast('print', (datas = {}) => {
            const { url = '', data = {} } = datas;
            const printPage = document.querySelector('#printPage');
            printUrl.value = `${origin}print/${url}?info=${JSON.stringify(data)}&t=${new Date().getTime()}`;
            nextTick(() => {
                printPage.addEventListener('did-finish-load', async () => {
                    console.log(printPage);
                });
            });
        });
    }
}
</script>
```
if the printUrl.value has the same url , then throw error info: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: ERR_FAILED (-2)

**Comment by abnerlee** [comment] 2021-05-18 15:46
Same here
```
webview = document.createElement("webview");
webview.setAttribute("id", "uni-preference-panel-view");
webview.setAttribute("src", "xxx.html"));
webview.setAttribute("nodeintegration", "true");
webview.setAttribute("enableremotemodule", "false");
document.querySelector("#xxxx").appendChild(webview);

webview.executeJavaScript("window.somemethod()"); // throw GUEST_VIEW_MANAGER_CALL here
```

**Comment by nornagon** [comment] 2021-07-08 18:14
Duplicate of #28208

**Closed by nornagon** 2021-07-08 18:14 UTC
Labels: 12-x-y, bug :beetle:, component/webview, platform/windows

**Comment by 1075264664** [comment] 2022-04-13 06:04
我也遇到了这个问题 有人解决了吗？

**Comment by amouratoglou** [comment] 2023-05-03 17:09
same here can't seem to find a solution.

**Comment by fanybook** [comment] 2024-09-29 01:48
> Duplicate of #28208

@nornagon no Duplicate

webview open https://www.globaltimes.cn/ don't work, but BrowserWindow loadURL can work

**Comment by fanybook** [comment] 2024-09-29 01:49
> 我也遇到了这个问题 有人解决了吗？

@1075264664 有解决么
