### ISSUE TITLE
First opened electron window takes 20 seconds more time to initialize than second one

### ISSUE THREAD

**Issue by atanas-tick42** [electron/electron#11381] opened 2017-12-08 16:18 UTC
* Electron version: 1.7.9
* Operating system: Windows 10  version 1709 (OS Build 16299.64)

### Expected behavior

Windows should load much faster, or at least for a similar time

### Actual behavior

First window loads for 22s and the second one for 1.3s

---

This started happening after a windows 10 update. Everything was working fine before the update.
However other Electron apps (Visual Studio, GitKraken) don't have that problem

---

### How to reproduce

```
var electron = require('electron');
var app = electron.app
var BrowserWindow = electron.BrowserWindow;

console.time('dialog1');

app.on('ready', function(){
  var dialog = new BrowserWindow({width: 600, height: 600});

  dialog.webContents.once('dom-ready', function() {
    console.timeEnd('dialog1');
    console.time('dialog2');

    var dialog2 = new BrowserWindow({width: 200, height: 200});
    dialog2.loadURL("https://electronjs.org/");

    dialog2.webContents.once('dom-ready', function() {
      console.timeEnd('dialog2');
    });
  });

  dialog.loadURL("https://github.com");
});
```
![electron-slow](https://user-images.githubusercontent.com/29654491/33774352-a6317798-dc43-11e7-9c26-eb624ba209c5.gif)

**Comment by MarshallOfSound** [comment] 2017-12-08 16:27
@atanas-tick42 Do you see the same situation when you load local files instead of remote ones?

**Comment by atanas-tick42** [comment] 2017-12-08 16:34
Sorry I didn't checked that.
It's working fine with files loaded with file://... with load time around 200ms, but files from http://localhost still have an issue.

**Comment by Vishal1419** [comment] 2018-02-26 18:05
I still have same issue on Windows 8.1 and electron 1.8.2
When loading local files it takes time in some milliseconds.
But when loading any url even localhost url, it takes time in some seconds.

**Comment by Davidzhu001** [comment] 2018-05-09 09:00
any solution on this?

**Comment by qlassiqa** [comment] 2018-05-25 12:53
I was interested in Electron for desktop development, but I stumbled across the same issue: I simply tried opening some of the Electron Demo apps, and any of them just load a blank window, then after a few seconds the window contents loads, too, which makes it not feel like a native app due to the waiting, besides being annoying to wait while staring at a blank window.

**Comment by qlassiqa** [comment] 2018-05-30 13:07
I always uncheck that option after I install Windows, but the delay is still there, even on the freshest of Windows.

**Comment by sofianguy** [comment] 2019-01-07 23:20
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by qlassiqa** [comment] 2019-01-08 08:16
I retried using the new Electron 2.0.2 demo app, and the results are similar as you can see yourself from the GIF _(blank canvas on every open or on every new window created, lasts 1-2 sec. on a freshly booted PC, and a tad longer after a day of heavy PC use)_:

![electron_202](https://user-images.githubusercontent.com/2369312/50817996-5959ee00-132e-11e9-8b9d-f8c393c6ee65.gif)

**Comment by nattajame27** [comment] 2019-01-24 07:50
remove CDN in index.html :)

**Comment by qlassiqa** [comment] 2019-01-24 08:14
> remove CDN in index.html :)

There is no CDN in the index.html file whatsoever in the Electron Demos app.

**Comment by enggjiten** [comment] 2019-03-26 08:51
I built my app which is loading just html pages and reading the data and render.
At very first start of app, it takes 25-30 seconds. I removed unnecessary packages. But still it is taking long time to load. 
I am using windows 7 64-bit and Windows 10 64-bit OS.
Let me know how can i reduce load time to 5-7 seconds.

**Comment by russfleming** [comment] 2019-04-01 20:25
I'm seeing something that may be related.  I'm starting an Express server in the main Electron process that will receive REST messages from my Angular 7 client GUI code.  This GUI code is shared by both a Node server and as part of an Electron stand-alone application.  

My issue is that at startup, the client sends a REST message which the main process server doesn't receive for about 20 seconds.  There seems to be some sort of initial 20 second delay in the Express server's ability to receive messages.  After the 20 seconds, everything works normally.  Waiting 10 seconds after startup results in about a 10 second delay.

I've created a repo based off the Electron quick-start repo demonstrates this.  

https://github.com/electron/electron/issues/17600  **20 second delay before main process REST server can receive message from renderer process**

**Comment by vjdv** [comment] 2019-04-17 20:42
> I retried using the new Electron 2.0.2 demo app, and the results are similar as you can see yourself from the GIF _(blank canvas on every open or on every new window created, lasts 1-2 sec. on a freshly booted PC, and a tad longer after a day of heavy PC use)_:
> 
> ![electron_202](https://user-images.githubusercontent.com/2369312/50817996-5959ee00-132e-11e9-8b9d-f8c393c6ee65.gif)

i'm having the same electron experience, did you find how to solve it or why is caused? thanks

**Comment by qlassiqa** [comment] 2019-04-17 21:01
> i'm having the same electron experience, did you find how to solve it or why is caused? thanks

Nope, I quit trying. I don't know how Atom loads so fast without this lag considering that it also uses Electron... (maybe in the future it will load faster if they make use of WebAssembly, which is a lot faster)

**Comment by aicioara** [comment] 2019-04-17 21:20
@vjdv what else do you have open in the background? Could this be related to https://github.com/electron/electron/issues/17810

**Comment by sofianguy** [comment] 2019-08-09 03:38
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:10
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:10 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows, version/1.7.x
