### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by damima0001** [electron/electron#34006] opened 2022-05-02 12:12 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

The application is not loading
![image](https://user-images.githubusercontent.com/95316551/166231589-5c961664-5b42-4e75-92fd-56a3ecf24f14.png)

### Actual Behavior

not working

**Comment by ckerr** [comment] 2022-05-02 15:23
Hi @damima0001, looks like this is the discord-bot-app in the screenshot, which is not maintained by the Electron project.

Triaging code with third-party dependencies is usually not feasible for a small team like Electron's. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com) that Electron maintainers can use.

If the bug you've found can be tested with a pass/fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug by checking your test against different OSes and Electron versions.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

**Comment by ckerr** [comment] 2022-05-02 15:26
Ah, I see you flagged this for Electron 3.1.0. That version of Electron came out three years ago, but I see that there's a fork of discord-bot-client that's currently at 3.1.0. Looks like maybe you meant to report this bug there?

Because of that, I'm going to close this issue. Please file a new one at https://github.com/Flam3rboy/discord-bot-client so that the right people will see it. Thank!

**Closed by ckerr** 2022-05-02 15:26 UTC
Labels: bug :beetle:, blocked/need-repro
