### ISSUE TITLE
[Bug]: i use webContents.print pageRanges:[{ from:0,  to:2,}] is true，but pageRanges:[{ from:0,  to:1,}] is false.why that..

### ISSUE THREAD

**Issue by origani** [electron/electron#39784] opened 2023-09-08 06:41 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

10.4.5

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

10.4.5

### Expected Behavior

i want only print one page,but i cant,it at least two

### Actual Behavior

![image](https://github.com/electron/electron/assets/40393124/24ef5ba0-e29a-4713-b1b8-587488a534ed)

**Comment by bagonterman** [comment] 2023-09-08 12:09
Does the range work if silent is false?

**Comment by origani** [comment] 2023-09-10 05:33
> Does the range work if silent is false?

does not work

**Comment by origani** [comment] 2023-09-10 05:36
> Does the range work if silent is false?

<img width="427" alt="F8EB85A8-111D-4892-BB15-E9E022486575" src="https://github.com/electron/electron/assets/40393124/f795e2e6-a807-436a-9f78-fa2dab84e479">
it will popup my printer setting,but i want silent print

**Comment by mlaurencin** [comment] 2023-09-25 18:40
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

If you’re still experiencing this issue in Electron 24.x.y or later (in addition to 22.x.y), please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2023-11-29 10:23
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2023-11-29 10:23 UTC
Labels: blocked/need-info ❌, bug :beetle:

**Comment by carchrae** [comment] 2024-06-11 19:30
> Does the range work if silent is false?

@codebytere - i can confirm the pageRange does work with `silent:false` on ubuntu (20.04), with v30, v31, and also the latest nightly build - however, when `silent:true` the pageRange is ignored (all pages are printed)  

and perhaps unrelated, but with `silent:false` my pageSize is ignored.  i need it to work with `silent:true` so not a concern for me (may be due to system not having my custom page size as an option)

example of options
```js
{
            pageSize: {
              width: 352 * 150,
              height: 352 * 300,
            },
            scaleFactor: 90,
            margins: {
              marginType: 'none'
            },
            silent: true,
            // NOTE: this does not appear to work!  :/
            pageRanges: [{from: 0, to: 0}],
}
```
