### ISSUE TITLE
[Bug]: Electron 18.0.X window freeze when an older electron version (ex: 17.4.0) of the same app is opened

### ISSUE THREAD

**Issue by hgouveia** [electron/electron#33847] opened 2022-04-20 12:57 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 21H2 (22000.613)

### What arch are you using?

x64

### Last Known Working Electron version

17.4.0

### Expected Behavior

I have 2 version of the same app

App 1 : Electron 17.4.0
App 2:  Upgraded to 18.0.4

If App 2 is running, and App 1 is opened, App 2 get freeze

Expected Behavior: 

App 1 get closed and App 2 does not freeze

### Actual Behavior

If App 2 is running and App 1 is opened, App 1 will get closed but App 2 get freeze

### Additional Information

I've tried this using older versions of electron and 17.4.0 and can confirm this happens just on Electron 18.0.X

Output from App1 when is opened while App 2 is running
```shell
[31804:0420/144542.463:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[31804:0420/144542.464:ERROR:cache_util.cc(146)] Unable to move cache folder C:\Users\{user}\AppData\Roaming\{app}\GPUCache to C:\Users\{user}\AppData\Roaming\{app}\old_GPUCache_000
[31804:0420/144542.464:ERROR:disk_cache.cc(185)] Unable to create cache
[31804:0420/144542.465:ERROR:shader_disk_cache.cc(612)] Shader Cache Creation failed: -2       
[34204:0420/144552.426:ERROR:broker_win.cc(56)] Error reading broker pipe: The pipe has been ended. (0x6D)
[20964:0420/144557.464:ERROR:broker_win.cc(56)] Error reading broker pipe: The pipe has been ended. (0x6D)
```

no logs in App 2

Also if App1 and App 2 are in 18.0.X, this issue does not happens

**Comment by mlaurencin** [comment] 2022-04-20 22:44
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/electron/electron/issues/33801. Though we do appreciate the additional information, this issue will be closed as it is a duplicate. You may want to subscribe to the other issue for updates, and if you have any additional information you would like to provide, you may do so there. 

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by mlaurencin** 2022-04-20 22:44 UTC
Labels: platform/windows, bug :beetle:, 18-x-y, 19-x-y
