### ISSUE TITLE
[Bug]: Drag region continues eating events when set to `unset` or `no-drag`

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#37137] opened 2023-02-05 01:34 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.11

### What operating system are you using?

Windows

### Operating System Version

Windows 11 (22000.1455)

### What arch are you using?

x64

### Last Known Working Electron version

Seemed to work in 18.3.x but maybe I need to retest

### Expected Behavior

Setting `no-drag` or `unset` on a previously draggable region should disable the drag region behavior.

### Actual Behavior

The element must be removed from the DOM - OR - the window must be resized for the change in drag behavior to be applied.

Possibly related to: https://github.com/electron/electron/pull/36230 - since I don't believe this issue occurred in 18.3.x (but I may be wrong)

### Additional Information

It may only occur when these styles are first adjusted via `webContents.insertCSS` - but again I'm not certain yet.

**Comment by Slapbox** [comment] 2023-02-05 01:43
Changing the `zIndex` to a negative number also seems to update the draggable status - but that's not always a reasonable option.

**Comment by nornagon** [comment] 2023-02-22 17:48
Duplicate of #32341

**Closed by nornagon** 2023-02-22 17:48 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, component/webcontents, 20-x-y, duplicate
