### ISSUE TITLE
[Bug]: Electron app loses instance lock after Steam starts

### ISSUE THREAD

**Issue by Covkie** [electron/electron#43350] opened 2024-08-19 03:06 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2.1, 29.0.0

### What operating system(s) are you using?

Other Linux

### Operating System Version

Linux bakery 6.10.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:05 +0000 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

Instance should not lose lock after Steam opens

### Actual Behavior

App loses lock resulting in another instance of the app opening

### Testcase Gist URL

https://gist.github.com/c478967d645d1c8ae7d2c2f2fcf7db37

### Additional Information

I think Electron Fiddle has an issue with instance locking so you must close all open instances after launching TWO (main and instance that detects a lock) instances.

Steps to repro:
1. Launch app from fiddle
2. Press F5 to open another instance- see the original instance refocuses
3. close instance opened in 1.
4. Launch app from fiddle
5. Open Steam
6. Press F5 to open another instance- see the original instance does NOT refocus and another instance is spawned.

Issue that made me look into this: https://github.com/Vencord/Vesktop/issues/640.

cc: @TheFeelTrain @kimjongbing @coinkillerl, If any of you three can repro this with another action(ex: opening steam in this bug report) in between launching and relaunching please comment what you did

**Comment by TheFeelTrain** [comment] 2024-08-19 18:47
Thank you for the CC. 

I can reproduce by launching Steam 100% of the time. 

However I can't get it to happen consistently doing anything else. There are definitely more triggers, possibly also Steam-related. It seems to also occur when launching games and playing them for a certain amount of time, but I can't be sure.

**Comment by kimjongbing** [comment] 2024-08-20 07:03
From what I can tell, it happens when I have closed the window but it's in my system tray and then I open the .desktop file again. 
![image](https://github.com/user-attachments/assets/9fbd4eba-8c6a-4bb1-bd3f-2a2891162cf6)

It happens very consistently right now for me.

**Comment by coinkillerl** [comment] 2024-09-17 12:24
Can always reproduce by launching Vesktop, launching steam, closing the vesktop window, and then launching the vesktop .desktop file. Another istance will be started instead of using the currently running one.

**Comment by Arcitec** [comment] 2024-09-22 23:35
+2 (+1 and +1)

This happens on my computer and my mother's computer. We both use Vesktop and Steam. See https://github.com/Vencord/Vesktop/issues/868

**Comment by Arcitec** [comment] 2024-09-22 23:40
Here are some vesktop debug logs which shows that Electron has a segmentation fault in its attempt to resume an instance, and then it decides to create a new instance:

---

1. First I close the existing app window (so that it goes to the tray), and then I run `vesktop` in the terminal:

```
$ vesktop


#
# Fatal process out of memory: Failed to reserve virtual memory for CodeRange
#
----- Native stack trace -----

[1]    973327 trace trap (core dumped)  vesktop
```

2. Then I try again in the terminal, and now it starts the duplicate Vesktop instance:

```
$ vesktop
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: rpm
Checking for update
[arRPC > ipc] not available, trying again (attempt 1)
[arRPC > ipc] listening at /run/user/1000/discord-ipc-1
[arRPC > websocket] 6463 in use!
[arRPC > websocket] listening on 6464
[arRPC > process] started
src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

src/gbm_drv_common.c:131: GBM-DRV error (get_bytes_per_component): Unknown or not supported format: 808530000

Update for version 1.5.3 is not available (latest version: 1.5.3, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

3. And now I try `vesktop` in terminal again while the duplicate copy is running:

```
$ vesktop
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: rpm
Checking for update
Vesktop is already running. Quitting...
```

So it seems to me like the existing instance check fails and core-dumps once. Then, the next time, it starts a new instance instead, and then after that, it's able to find the new instance and bring that to the front.

**Comment by Arcitec** [comment] 2024-09-23 00:10
@Covkie Because the 1st log output is generated by Electron.

**Comment by Vendicated** [comment] 2024-09-23 00:20
Like cookie said, keep in mind that this issue is about electron and not any app in specific. Sharing logs of a full app is just noise and not really relevant here as it is not possible for electron maintainers to reproduce or do anything with that. 

I highly suggest sticking to only the minimal reproduction example linked in the issue description and reproducing with that. That way, everyone is on the same page and the issue is completely isolated from anything else.

___

Also, re your comment @Arcitec, your error
```
Fatal process out of memory: Failed to reserve virtual memory for CodeRange
```
is unrelated to this issue and from my own findings is related to selinux preventing the sandbox from allocating enough virtual memory for its sandbox (and is an issue with chromium, not electron). You can work around it by temporarily disabling selinux. But like I said, that's irrelevant to this issue so here is not the right place to discuss it

**Closed as completed** 2024-11-03 10:49 UTC
Labels: platform/linux, bug :beetle:, has-repro-gist
