### ISSUE TITLE
[Bug]: On Wayland closing apps to the system tray, then reopening them makes the app forget which monitor it was previously opened on (Signal, ProtonVPN, MullvadVPN)

### ISSUE THREAD

**Issue by Victor239** [electron/electron#34788] opened 2022-06-29 12:04 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Kubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

- When closing these apps they normally stay open as system tray icons to allow easily monitoring and reopening them.
- When using a PC with multiple physical monitors, reopening these apps from the system tray should remember which monitor it was last opened on. 

Tested on Signal Desktop, ProtonVPN and MullvadVPN. On a Wayland desktop, opening these apps in Electron Wayland mode `--ozone-platform=wayland`.

### Actual Behavior

Reopening these apps from the system tray *forgets* which monitor it was last opened on. It seems to default to the primary monitor.

**Comment by mlaurencin** [comment] 2022-06-29 21:46
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a follow-up comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2022-07-14 10:50
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-07-14 10:50 UTC
Labels: bug :beetle:, blocked/need-repro
