### ISSUE TITLE
[Bug]: <input type=file> not working in WebContentsView

### ISSUE THREAD

**Issue by safris** [electron/electron#42018] opened 2024-05-02 16:39 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When loading a webpage with a `WebContentsView`, clicking on an `<input type="file">` does not bring up a file selector.

This can be reproduced with the following test that brings up two windows:
1. Window 1 is a `BrowserWindow` with the HTML loaded in the `BrowserWindow`.
   In this window, clicking on the "Choose File" button brings up the file selector.
2. Window 2 is a `BrowserWindow` with a `WebContentsView` added as a child view of its `contentView`.
   In this window, clicking on the "Choose File" button does not bring up the file selector.

--------

`file.html`
```html
<html>
<body>
  <input type="file" name="file">
</body>
</html>
```

`index.js`
```js
const { app, BrowserWindow, WebContentsView } = require("electron");

app.whenReady().then(() => {
  const win1 = new BrowserWindow({ x: 100, y: 100 });
  win1.loadFile("file.html");

  const win2 = new BrowserWindow({ x: 500, y: 500 });
  const wcv = new WebContentsView();
  win2.contentView.addChildView(wcv);
  wcv.setBounds({x: 0, y: 0, width: 300, height: 300 });
  wcv.webContents.loadFile("file.html");
});
```

### Actual Behavior

When loading a webpage with a `WebContentsView`, clicking on an `<input type="file">` does not bring up a file selector.

**Comment by safris** [comment] 2024-05-02 16:48
Sorry, I just saw this bug is already reported in #42013.

**Comment by dsanders11** [comment] 2024-05-06 07:41
Duplicate of #42013.

**Closed by dsanders11** 2024-05-06 07:41 UTC
Labels: bug :beetle:

**Comment by zhangyanling678** [comment] 2024-07-22 06:41
how to resolve?
