### ISSUE TITLE
[Bug]: Crash on attaching the file using generic input type="file" form control

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#30858] opened 2021-09-06 14:12 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0-beta.2

### What operating system are you using?

Linux 5.13.13 kernel

### What arch are you using?

x64

### Last Known Working Electron version

14.0.0

### Expected Behavior

The app doesn't crash.

### Actual Behavior

The app crashes.

### Testcase Gist URL

https://github.com/vladimiry/ElectronMail/releases/tag/v4.12.6

### Additional Information

It's not so trivial task to create an isolated repro for the case like this, but link to the app release has been attached as well as the crash stack.

Downgrading `15.0.0-beta.2 => 14.0.0` resolves the issue.

See attached [crash stack](https://github.com/electron/electron/files/7116429/dump.txt).

**Comment by vladimiry** [comment] 2021-09-07 22:54
Hi @VerteDinde, thanks for thorough clarifying questions. Not promising that I will be able to provide a minimal isolated repro project but I should be able to address rest of the points you raised in the next 3 days.

> even if you could point me to where in ElectronMail you handle dialogs, that would be very appreciated

The ElectronMail itself triggers the file system-related dialog I think only in one place - selecting a destination folder for batch emails exporting (being handled in the main process [here](https://github.com/vladimiry/ElectronMail/blob/c73cad5d98149311ad0df86204119aa11e982c98/src/electron-main/api/endpoints-builders/general.ts#L153)). This requires the account to be added into the app and the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) option to be enabled for that account (so you then switch to the "local store" mode and do export stuff).

But the app comes with an embedded https://github.com/ProtonMail/WebClients web clients stack which might potentially have a lot of file system-related dialog opening entry points. One of such entry points is adding the attachment to the draft email - you just compose a new email and attach any file and it gets crashed without showing the dialog (yes I've initially noticed that some dialog things are mentioned in the stack trace). This entry point, just composing new email and adding the attachment, is how the issue got noticed by the end-user. It's by the way unclear yet what system was used by that user (I've asked for details). For that user that could potentially be Windows, but I was able to reproduce the issue on Linux.

**Comment by vladimiry** [comment] 2021-09-07 23:01
> The ElectronMail itself triggers the file system-related dialog I think only in one place - selecting a destination folder for batch emails exporting

I've just tested the case using https://github.com/vladimiry/ElectronMail/releases/tag/v4.12.6 on Linux and there is no crash in this case. So for now I can only say that it crashes during adding an attachment to email - so file selecting dialog triggered from the embedded into webview [WebClients](https://github.com/ProtonMail/WebClients) client/page (so not folder selecting, but file). I understand that this information is not very helpful but still believe it narrows down the scope.

**Comment by vladimiry** [comment] 2021-09-08 09:40
> you just compose a new email and attach any file and it gets crashed without showing the dialog

I was of course wrong here. It of course shows the dialog and crashes after the file/files get selected.

> One other question: could you try downgrading from 15.0.0-beta.2 to 15.0.0-alpha.9? We have a similar report on Windows that seems to appear beginning in 15.0.0-alpha.10, and I'm curious if this could have the same root cause.

Can confirm that 15.0.0-alpha.9 doesn't crash but 15.0.0-alpha.10 does.

**Comment by vladimiry** [comment] 2021-09-08 10:15
@VerteDinde it crashes even for the following simple snippet (even without webview involving), so should be easy to reproduce. I didn't compare the stacktraces though but it's likely the same issue (crashes starting from 15.0.0-alpha.10).

```javascript
const {app, BrowserWindow} = require('electron')

app.whenReady().then(() => {
  new BrowserWindow().loadURL(`data:text/html,
    <html>
    <body>
    <form method="post" enctype="multipart/form-data">
        <input type="file" name="file" multiple>
    </form>
    </body>
    </html>
  `)
})
```

**Comment by nornagon** [comment] 2021-09-08 19:06
cc @codebytere. Possibly https://github.com/electron/electron/pull/30663 is relevant (might fix this issue?).

**Comment by codebytere** [comment] 2021-09-08 19:11
@nornagon i imagine it might though it might be a pain/unwise to backport so I can look to fix this as a one-off pending that larger PR being merged

**Comment by VerteDinde** [comment] 2021-09-08 19:18
@codebytere The root of the issue seems to be in this block within `FileSelectHelper::OnOpenDialogDone`:
```
      if (render_frame_host_ && !paths.empty()) {
        auto* browser_context = static_cast<electron::ElectronBrowserContext*>(
            render_frame_host_->GetProcess()->GetBrowserContext());
        render_frame_host_->GetProcess();
        browser_context->prefs()->SetFilePath(prefs::kSelectFileLastDirectory,
                                              paths[0].DirName());
      }
```

I _think_ this Chromium roll broke it, since it seems to be broken on both Windows and Linux. Mac is unaffected: https://github.com/electron/electron/pull/30370 Trying to find a fix now

**Comment by vladimiry** [comment] 2021-09-08 20:58
> FWIW, the above repro doesn't work for me in Fiddle on Windows

I ran it on Linux only.

**Comment by codebytere** [comment] 2021-09-08 21:59
@vladimiry also reproduces on Linux for me, thanks!

**Closed** 2021-09-13 13:25 UTC
Labels: platform/windows, platform/linux, crash :boom:, bug :beetle:

**Comment by VerteDinde** [comment] 2021-09-13 15:52
@vladimiry I think my merging the fix PR automatically closed this issue, but should be addressed in 15-beta.5, which will release in a few hours! Could you let me know if you still see the behavior after beta.5 is released? If it persists, I'll reopen the issue.

Thanks again for reporting this! 🙇‍♀️

**Comment by vladimiry** [comment] 2021-09-13 18:16
@VerteDinde the issue appears to be fixed for me in 15-beta.5 on Linux. Thanks everyone involved into fixing it.
