### ISSUE TITLE
React DevTools tab not appearing Electron@10.x.x

### ISSUE THREAD

**Issue by sprout2000** [electron/electron#25990] opened 2020-10-16 05:12 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.3
* **Operating System:**
  * macOS 10.15.7
* **Last Known Working Electron version:**
  * 8.5.2

### Expected Behavior

In my project I am loading ReactDevTool.

```javascript
app.whenReady().then(async () => {
  await createWindow();
  await session.defaultSession.loadExtension(path.join(os.homedir(), extPath));
});
```
In the terminal for version 10.1.3 we see warnings:

```bash
(node:6207) ExtensionLoadWarning: Warnings loading extension at /Users/foobar/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.8.2_0:
Unrecognized manifest key 'browser_action'. 
Unrecognized manifest key 'minimum_chrome_version'. 
Unrecognized manifest key 'update_url'. 
Manifest contains a differential_fingerprint key that will be overridden on extension update. 
Cannot load extension with file or directory name _metadata. 
Filenames starting with "_" are reserved for use by the system.
```

And the extension doesn't work.

### Actual Behavior

With warnings: `ExtensionLoadWarning`, no extension working.

### To Reproduce

```bash
$ git clone git@github.com:electron/electron-quick-start.git
$ cd electron-quick-start
$ npm install
```

and edit `main.js`

```javascript
// Modules to control application life and create native browser window
const { app, BrowserWindow, session } = require('electron');
const os = require('os');
const path = require('path');

const extPath =
  '/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.8.2_0';

async function createWindow() {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
    },
  });

  // and load the index.html of the app.
  await mainWindow.loadFile('index.html');

  // Open the DevTools.
  mainWindow.webContents.openDevTools({ mode: 'detach' });
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(async () => {
  await createWindow();
  await session.defaultSession.loadExtension(path.join(os.homedir(), extPath));
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  app.quit();
});
```

**Comment by ckerr** [comment] 2020-10-19 20:28
gist version of ^

**Comment by sprout2000** [comment] 2020-10-22 04:40
Same with Windows10.

- Electron Version: 
  - v10.1.3

- Operating System:
  - Windows10 (1909)

- Last Known Working Electron version:
  - v8.5.2

- React Devtools version:
  - v4.8.2_0

```shell
(node:880) ExtensionLoadWarning: Warnings loading extension at C:\Users\foobar\AppData\Local\Google\Chrome\User Data\Default\Extensions\fmkadmapgofadopljbjfkapd
koienihi\4.8.2_0: 
Unrecognized manifest key 'browser_action'. 
Unrecognized manifest key 'minimum_chrome_version'. 
Unrecognized manifest key 'update_url'. 
Manifest contains a differential_fingerprint key that will be overridden on extensionupdate. 
Cannot load extension with file or directory name _metadata. 
Filenames starting with "_" are reserved for use by the system.
```

**Comment by searene** [comment] 2020-10-28 14:01
Same on Linux.

- Electron Version: 10.1.5
- Operating System: Linux archlinux 5.4.72-1-lts #1 SMP Sat, 17 Oct 2020 13:30:57 +0000 x86_64 GNU/Linux
- Last Known Working Electron version: Not sure
- React Devtools version: 4.9.0_0

**Comment by nornagon** [comment] 2020-10-29 23:37
Looks like a duplicate of #23662. Please reopen if I'm wrong!

**Closed by nornagon** 2020-10-29 23:37 UTC
Labels: 10-x-y, 9-x-y, bug :beetle:, platform/macOS
