### ISSUE TITLE
Electron hangs after closing and reopening

### ISSUE THREAD

**Issue by Graren** [electron/electron#9409] opened 2017-05-08 22:37 UTC
I did not want to ask here but I asked on [discuss](https://discuss.atom.io/t/electron-hangs-on-windows/42224) and did not get an answer

* Electron version: 1.6.6
* Operating system: Windows 10 x64

### Expected behavior
Running 
` ...> electron
`
Should show the default electron drag and drop
Or on your [quickstart](https://github.com/electron/electron-quick-start)
`
npm start
`
Should show the quickstart window.
And in fact it does, I could see those windows, but just once, the first time the command is ran on a session.
### Actual behavior
Opening ANY electron app after closing it a first time, displays the following
```
...>electron myApp

_
```
That down there is the blinking cursor, never opens a window, or shows anything.
The task manager displays (depending on the app) a few electron processes, not consuming anything, and not doing anything, whereas, when it does open(the first time) some of them are actually using system resources.

### How to reproduce
`...>electron`
For a repo, the quickstart would be a good start

**Comment by KagamiChan** [comment] 2017-05-10 06:49
There have been some similar reports from users of our app, but I could not reproduce it on my own machine and have no clue yet, except that this happens only for 1.6.x, and some users commented the 32-bit version of Electron is OK.

I wonder if there is any tool or method to dig a little deeper on this issue

**Comment by Graren** [comment] 2017-05-11 21:29
Can confirm, on windows 10 1.6.6 32bits works perfectly, 1.7.0 beta 64bits still suffers from the same issue, 1.3.8 64 bits is functional, But  all versions work as expected on windows 8 64 bits, and windows 8.1 64 bits, they just seem to be failing on windows 10, I really hope this is of help... Maybe some update from windows broke a library? I hope this was of help, any other info you need just ask!

**Comment by Graren** [comment] 2017-05-13 19:51
Is it possible to tag this as a bug? I know It's platform dependent and a small population from your userbase, but certain apps that where created under electron 1.6.x remain unusuable for me :( which is kinda heartbreaking

**Comment by zcbenz** [comment] 2017-06-21 08:10
Can you try using a debugger to get the stack trace when it hangs? Otherwise it is impossible to know what actually happened.

**Comment by codebytere** [comment] 2017-09-27 01:19
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:19 UTC
Labels: more-information-needed
