### ISSUE TITLE
😢The filter of webRequest has no effects.

### ISSUE THREAD

**Issue by TongDaDa** [electron/electron#19223] opened 2019-07-12 09:38 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * LATEST
  
* **Operating System:**
  * macOS 10.13.6 

### Expected Behavior

```javascript

const filter = {
     urls: [
          "file://*.sobot.com/*"
     ]
}

browserWindow.webContents.session.webRequest.onBeforeRequest(filter,  (details, callback) => {
            const { id, url, method, resourceType, timestamp, uploadData } = details;
            // url === "file://users/liutong/Desktop/**/projectName/app/***"
           callback({
                cancel: false,
                redirectURL: 'http' + url.slice(4)
            })
        })
```

The callback of `onBeforeRequest` will be called by any request from the file scheme.

### Actual Behavior

For the above codes, I just want to redirect a request that contains the '*.sobot.com' domain,
But I received a URL from the local path of `/users/Oliver/Desktop` in the callback of `onBeforeRequest`.

When I add "file://\*.sobot.com/\*" a rule in the array, for the rule, I actually expected it only to match request that domain is '.sobot.com', but It appears to listen to all requests. e.g 

```
[ "file://users/Oliver/Desktop/**/projectName/app/caching_resources/***" ]
```

### Additional Information

As for my final purpose, you can refer to this [issue](https://github.com/electron/electron/issues/19200). so my fallback is to exclude any request that contains a path of 'caching_resources' as to redirect to the `HTTP` scheme.

**Comment by TongDaDa** [comment] 2019-07-14 04:43
My filter list is :

```json
["file://www.sobot.com/chat/*", "file://crumb.sobot.com/1.gif*", "file://cdn.console.pipacoding.com/*"],
```

**Comment by pushkin-** [comment] 2019-07-15 18:53
This is a dupe of [this issue](https://github.com/electron/electron/issues/11371)

**Comment by TongDaDa** [comment] 2019-07-19 03:29
Yes, I am dupe

**Comment by codebytere** [comment] 2019-07-19 03:44
Closing as duplicate of https://github.com/electron/electron/issues/11371 in agreement with @pushkin-

**Closed by codebytere** 2019-07-19 03:44 UTC

**Comment by TongDaDa** [comment] 2019-07-19 03:58
@codebytere so, how to resolve it? you think it is correct?

**Comment by TongDaDa** [comment] 2019-07-19 04:00
If this is a bug, please fix it as soon as possible

**Comment by TongDaDa** [comment] 2019-07-19 04:01
I don't know what reason let you spend so much time on this bug?
