### ISSUE TITLE
[Bug]: MacOS Ventura M1 mediaDevices.getUserMedia takes long time

### ISSUE THREAD

**Issue by daniel-sapir** [electron/electron#36523] opened 2022-12-01 09:33 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.5.4

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

x64

### Expected Behavior

The camera stream should be loaded in less than 2 seconds and always succeeded.
Using the getUserMedia function.

### Actual Behavior

It takes around 8-10 seconds for the camera device to be loaded and sometimes fails with this error:
`NotReadableError: Failed to allocate videosource`

### Additional Information

It worked well for me for a long time and started happening in a specific case:
It happens only on M1 MacBooks with Ventura OS with an Intel electron build.
It works well when I build my app on M1, but I want to keep building it on an Intel-based Mac.
If I try to build and arm64 build on x64 this issue keeps happening.

**Comment by nornagon** [comment] 2022-12-01 18:20
Is this behavior also present in Chrome?

**Comment by nornagon** [comment] 2022-12-01 18:20
Also, the version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

**Comment by daniel-sapir** [comment] 2022-12-03 15:22
This behavior does not happen in Chrome.
I tried to build my app with Electron 20 as well and it happens too.

**Comment by joinwen** [comment] 2022-12-05 06:43
On Ventura 13.0.1, Electron 20.3.1
It takes around 8-10 seconds for the camera device to be loaded and sometimes fails with this error:
NotReadableError: Could not start video source
What should I do?

**Comment by ngaer** [comment] 2022-12-05 08:27
Facing the same issues on Ventura 13.0.1, Electron 22.0.0. Either up to 10 seconds of camera initialization or getting a NotReadableError error. The same app works well on Chrome.

**Comment by joinwen** [comment] 2022-12-05 09:00
@ngaer are you getting a NotReadableError message with "Could not start video source"

**Comment by ngaer** [comment] 2022-12-05 09:03
Yes, from time to time. So it either takes 10 seconds to get the stream or it throws this error.

**Comment by daniel-sapir** [comment] 2022-12-05 16:21
@nornagon do you need more info?

**Comment by cglacken** [comment] 2022-12-08 12:03
Is this going to get the blocked tag removed?

**Comment by daniel-sapir** [comment] 2022-12-11 09:57
@nornagon it seems like this issue reproduces for many of us. May you remove the blocked tag, please?

**Comment by louisencontre** [comment] 2022-12-12 16:17
Hello everyone
Is this only happening on Ventura 13.0.1? Was it happening with Ventura 13.0.0?

**Comment by louisencontre** [comment] 2022-12-16 09:04
After updating to macOS 13.1.0, we were not able to reproduce the issue.

**Comment by codebytere** [comment] 2023-01-05 13:06
Closing as an OS-specific error fixed by the OS: https://github.com/electron/electron/issues/36523#issuecomment-1354418065

**Closed by codebytere** 2023-01-05 13:06 UTC
Labels: blocked/need-info ❌, bug :beetle:

**Comment by louisencontre** [comment] 2023-01-05 13:43
@codebytere Maybe we should ask other people if updating to macOS 13.1.0 fixed the issue for them as well before closing the ticket 🙏

**Comment by louisencontre** [comment] 2023-01-05 14:22
> On Ventura 13.0.1, Electron 20.3.1 It takes around 8-10 seconds for the camera device to be loaded and sometimes fails with this error: NotReadableError: Could not start video source What should I do?

Do you still have the issue with macOS 13.1.0?

**Comment by ngaer** [comment] 2023-01-05 14:30
Yeah, I haven't faced the issue either after updating to macOS 13.1.0.

**Comment by daniel-sapir** [comment] 2023-01-08 09:28
@louisencontre We do have the same issue even after we've upgraded to macOS 13.1.0

**Comment by daniel-sapir** [comment] 2023-01-08 09:29
@ngaer what Electron version are you using?

**Comment by ngaer** [comment] 2023-01-08 18:18
We use Electron v22.0.0.

Do you still have both the 10s delay and `NotReadableError` error?

On my side, I haven't faced the error since the update to 13.1.0, but still have some delay of about 2-3 seconds. Which is fine for us. I think it might be related to this new continuity camera thing.

**Comment by joinwen** [comment] 2023-01-09 08:12
MacOS: Ventura 13.1.0
Electron: 22.0.0
I also have delay of 6-7seconds when I invoke getUserMedia

**Comment by louisencontre** [comment] 2023-01-09 08:42
Yes we have users with issue still with macOS 13.1.0...

**Comment by louisencontre** [comment] 2023-01-09 08:43
@codebytere Could we reopen the issue please?

**Comment by daniel-sapir** [comment] 2023-01-09 09:12
It still takes around 10 seconds for the getUserMedia to get things going.
Our users still get the same error even after upgrading to macOS 13.1.0

@codebytere may you reopen this issue please?

**Comment by louisencontre** [comment] 2023-01-09 09:44
@daniel-sapir Do you still have `NotReadableError` error or just the delay after upgrading?

**Comment by joinwen** [comment] 2023-01-15 06:46
Try to config arch option with electron-forge, see https://electron.github.io/electron-packager/main/interfaces/electronpackager.options.html#arch

**Comment by ashleyvernon** [comment] 2023-02-15 23:31
We are on electron version 20.0.3, Ventura 13.1.0 and it is still taking ~10 seconds as well. Can we please reopen this issue?

**Comment by daniel-sapir** [comment] 2023-02-16 07:57
I think this issue should be re-open.
It might not be the most attractive one to handle, but it should be at the top of the backlog.

**Comment by cglacken** [comment] 2023-03-03 13:59
It looks like the latest version of Ventura addresses this. I see a new process called ContinuityCaptureAgent that I suspect is doing something, I have no proof - but either way the camera is now loading fast for me now.

**Comment by waleedbhatti** [comment] 2023-03-08 12:01
> It looks like the latest version of Ventura addresses this. I see a new process called ContinuityCaptureAgent that I suspect is doing something, I have no proof - but either way the camera is now loading fast for me now.

@cglacken I am facing this, can you please share details about ContinuityCaptureAgent and where you are using it in your app?

**Comment by cglacken** [comment] 2023-03-08 12:03
@waleedbhatti I am not directly using that, it is only an assumption as I feel this whole issue was probably related to that feature - but again I have no proof of that. I can only say that the issue is resolved for me in the latest MacOS.

**Comment by louisencontre** [comment] 2023-03-09 08:37
> @waleedbhatti I am not directly using that, it is only an assumption as I feel this whole issue was probably related to that feature - but again I have no proof of that. I can only say that the issue is resolved for me in the latest MacOS.

Hey @cglacken on which version of Ventura was the issue fixed for you?

**Comment by cglacken** [comment] 2023-03-09 08:38
@louisencontre 13.2.1

**Comment by tyfiero** [comment] 2023-11-10 19:42
I'm still getting this error, I ask for microphone access with getUserMedia, and it takes about 8 seconds for it to run, and it blocks the main thread as it loads, freezing the UI. Hardly ideal. I'm on MacOS Ventura 13.5 and Electron 27.0.2. Any idea how to fix this?

**Comment by daniel-sapir** [comment] 2023-11-12 11:25
Hey all :) 
After we've published a universal version of Electron this issue was fixed, I suggest you all switch to a universal build

**Comment by lichenglong-blog** [comment] 2024-02-03 06:15
> Electron

你好！请问是哪个版本呢
