### ISSUE TITLE
preload scripts are being injected into _blank windows

### ISSUE THREAD

**Issue by koush** [electron/electron#6991] opened 2016-08-26 05:43 UTC
* Electron version:
1.3.3
* Operating system:
OSX El Capitan

My app loads a BrowserWindow at custom://foo/bar. This window creation has a script preload.
That window has an <a> tag (to an http link) that loads on a _blank target. If that is clicked, the new window  automatically also uses the same preload.

Is this by design?

**Comment by MarshallOfSound** [comment] 2016-08-26 05:46
@koush Yes this is by design.

A preload script assigned to a `BrowserWindow` or a `WebView` will always run on every page load before all scripts on that page.

**Closed by MarshallOfSound** 2016-08-26 05:46 UTC

**Comment by koush** [comment] 2016-08-26 05:48
@MarshallOfSound Thanks, that makes sense.

Is there any way to override the behavior of clicking a _blank a tag link?

I tried to replace window.open with no luck.

**Comment by koush** [comment] 2016-08-26 05:52
Found the answer, thanks

http://electron.atom.io/docs/api/web-contents/#event-new-window
