### ISSUE TITLE
app. Ispackaged is also false after it is packaged by electronic builder

### ISSUE THREAD

**Issue by message163** [electron/electron#35153] opened 2022-08-01 03:00 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16

### What operating system are you using?

Windows

### Operating System Version

window 11

### What arch are you using?

x64

### Expected Behavior

```ts
import { app, BrowserWindow } from 'electron'

import path from 'path'
let win: BrowserWindow | null;

const createWindow = () => {

win = new BrowserWindow({
    webPreferences: {
        devTools:true,
        contextIsolation: false,
        nodeIntegration: true
    }
})

//  app.isPackaged  returns  false
if (app.isPackaged) {
    win.loadFile(path.join(__dirname, '../index.html'))
} else {
    win.loadURL(`http://${process.env['VITE_DEV_SERVER_HOST']}:${process.env['VITE_DEV_SERVER_PORT']}`)
}
}

app.whenReady().then(createWindow)
```

### Actual Behavior

//  app.isPackaged  returns  true

**Comment by RaisinTen** [comment] 2022-08-01 07:32
what do you get when you print `app.getPath('exe')`?

**Comment by message163** [comment] 2022-08-01 15:39
> 

C:\Users\TR\Desktop\electron\electron.exe

**Comment by message163** [comment] 2022-08-01 15:46
![image](https://user-images.githubusercontent.com/32630999/182188279-f9e81e21-6530-42c3-895b-e2d0b0432c11.png)

**Comment by RaisinTen** [comment] 2022-08-02 14:39
I didn't get a chance to try to package an electron app using electron-builder yet but the reason why this happens is clear - https://github.com/electron/electron/blob/31be6ecf7b1e63f278b03c5d64d59288ee2f1cd7/shell/browser/api/electron_api_app.cc#L988-L1003.
`app.isPackaged` works by checking if the name of the executable is `electron`. If it is so (which is true in your case), it assumes that it is not packaged, otherwise it thinks that it's packaged. If this is blocking your progress, you could try to set the environment variable, `ELECTRON_FORCE_IS_PACKAGED`, with any value you want and that would make electron think that it's always a packaged app.

I'd also like to know what version of electron or electron-builder where this problem was introduced in. That info would be very helpful!

**Comment by message163** [comment] 2022-08-03 01:37
set ELECTRON_FORCE_IS_PACKAGED   Or false

**Comment by RaisinTen** [comment] 2022-08-05 11:00
@message163 I tried to package a dummy app using electron-builder v23.3.3 on Windows and I wasn't able to repro this locally because the name of the executable is the same as the name of the packaged app. I'm adding [`blocked/need-info ❌`](https://github.com/electron/electron/labels/blocked/need-info%20❌), so that you can share the steps for reproducing this. It would be really awesome if you're able to share a GitHub gist / repo that has the repro code!

**Comment by RaisinTen** [comment] 2022-09-19 08:09
No follow-up for more than a month, closing.

**Closed by RaisinTen** 2022-09-19 08:09 UTC
Labels: bug :beetle:, blocked/need-repro

**Comment by YangEzzz** [comment] 2023-03-24 03:06
> No follow-up for more than a month, closing.



> I didn't get a chance to try to package an electron app using electron-builder yet but the reason why this happens is clear -
> 
> https://github.com/electron/electron/blob/31be6ecf7b1e63f278b03c5d64d59288ee2f1cd7/shell/browser/api/electron_api_app.cc#L988-L1003
> 
> .
> `app.isPackaged` works by checking if the name of the executable is `electron`. If it is so (which is true in your case), it assumes that it is not packaged, otherwise it thinks that it's packaged. If this is blocking your progress, you could try to set the environment variable, `ELECTRON_FORCE_IS_PACKAGED`, with any value you want and that would make electron think that it's always a packaged app.
> I'd also like to know what version of electron or electron-builder where this problem was introduced in. That info would be very helpful (might help us understand if opening this issue in the electron-builder repo makes more sense, which you have already done in [electron-userland/electron-builder#7034](https://github.com/electron-userland/electron-builder/issues/7034))!

when i change the productName of build parameter to the name except electron, `app.isPackaged` seems right after building
