### ISSUE TITLE
Regression: titleBarStyle 'hidden-inset' option is treated as 'hidden'

### ISSUE THREAD

**Issue by feross** [electron/electron#8694] opened 2017-02-15 23:04 UTC
* Electron version: v1.6.0 beta
* Operating system: macOS Sierra 10.12.3

### Expected behavior

The OS "traffic light" buttons are inset.

![screen shot 2017-02-15 at 3 02 29 pm](https://cloud.githubusercontent.com/assets/121766/22999361/c9c8f98a-f38f-11e6-81d1-7a970b29e733.png)

### Actual behavior

The OS "traffic light" buttons are not inset. It's as if the option `'hidden-inset'` is interpreted as `'hidden'`. This is a regression.

![screen shot 2017-02-15 at 3 00 46 pm](https://cloud.githubusercontent.com/assets/121766/22999363/cd4341c4-f38f-11e6-9b90-7e8034e12a5c.png)

### How to reproduce

Create a browser window with the `titleBarStyle` option set to `'hidden-inset'`.

```js
var win = new electron.BrowserWindow({
  titleBarStyle: 'hidden-inset'
})
```

**Comment by kevinsawicki** [comment] 2017-02-15 23:09
I believe this is a duplicate of #8610 which is fixed on master and will be included in the 1.6.1 release, hopefully out later this week.

**Comment by feross** [comment] 2017-02-15 23:10
@kevinsawicki Thanks, sorry for the noise. I searched but that issue didn't come up for some reason. Cheers!

**Closed by kevinsawicki** 2017-02-15 23:09 UTC

**Comment by kevinsawicki** [comment] 2017-02-15 23:11
> Thanks, sorry for the noise. I searched but that issue didn't come up for some reason. Cheers!

No worries 👋
