### ISSUE TITLE
[Bug]: Input type=color doesn't show after resizing electron window a few times.

### ISSUE THREAD

**Issue by valueerrorx** [electron/electron#38110] opened 2023-04-24 20:49 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11, MacOS Catalina, Ubuntu 22.04

### What arch are you using?

x64

### Expected Behavior

the input type=color colorpicker should show as expected

### Actual Behavior

after resizing the electron window several times it stops showing. 

### Additional Information

i added a simple

<input type=color> 

element to my app - tested it several times. then i start resizing the app 2 or three times and suddenly it stops working.

**Comment by valueerrorx** [comment] 2023-04-24 21:13
i realised that there are two different problems. 

on ubuntu: resizing causes the color-picker to stay hidden
on macos catalina:    window.setAlwaysOnTop(true, "screen-saver", 1)   makes the color picker stay hidden from the beginning

**Comment by codebytere** [comment] 2023-04-25 08:49
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed** 2023-05-06 01:51 UTC
Labels: bug :beetle:, blocked/need-repro
