### ISSUE TITLE
[Bug]: form Post with “target” attribute sending GET request instead of POST

### ISSUE THREAD

**Issue by amigup** [electron/electron#28804] opened 2021-04-23 17:52 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

After submitting form with method='post' and target='_blank' (or target='windowname') Electron open new window with POST request.

### Actual Behavior

After submitting form with method='post' and target='_blank' (or target='windowname') Electron open new window with GET request instead of POST. Form data will not be sent.

### Additional Information

logging this as new bug as #2816 is marked as closed.

**Comment by nornagon** [comment] 2021-04-23 23:06
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by nornagon** [comment] 2021-06-04 00:07
I can't reproduce this on any version of Electron since 4.x. Here's my gist:

https://gist.github.com/24fc62cf9a17e825ed27b1a92123c8e9

I'm going to close this for now as I'm unable to reproduce the issue. If you're able to provide a standalone test case which shows the behavior you're seeing, we can reopen.

**Closed by nornagon** 2021-06-04 00:07 UTC
Labels: blocked/need-repro, bug :beetle:
