### ISSUE TITLE
[Bug]: 'menu'-support broken (wayland, linux)

### ISSUE THREAD

**Issue by slynobody** [electron/electron#37635] opened 2023-03-21 17:53 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.4.3

### What operating system are you using?

Other Linux

### Operating System Version

debian

### What arch are you using?

x64

### Expected Behavior

menu functionality (exporting electron-apps menu to menu-field in DE-controlbar) out of the box for all old and new linux-users (wayland)

### Actual Behavior

global menu not showing up (brave, freetube, signal, heroic) in a wayland environment (Linux)

workaround is falling back to x11 by setting GDK_BACKEND="x11" (while *not* setting --ozone-platform=wayland at all or making it default).

= bunchs of electron-apps are  not benefiting from wayland (scaling, UHD-resolution, security) while wayland is mainstreaming and new users have the first linux-impression 'where is the menu'?

also see #34335

**Comment by jkleinsc** [comment] 2023-03-22 01:43
Closing as duplicate of #34335

**Closed by jkleinsc** 2023-03-22 01:43 UTC
Labels: bug :beetle:
