### ISSUE TITLE
Can not get cookies on restart after calling session.clearStorageData

### ISSUE THREAD

**Issue by chamerling** [electron/electron#9776] opened 2017-06-16 07:41 UTC
* Electron version: 1.7.3
* Operating system: OS X 10.11.6

Hi all,

I have a strange behaviour and need some advice wether it is a bug or not: I was able to get my cookies from `mainWindow.webContents.session.cookies.get` after restarting my application until I called `session.clearStorageData`.  Since then I am not able to retrieve any cookie even if I flush them with `cookies.flushStore`

I wonder if there is something to call to retrieve the initial behaviour or if it is a bug.

Thx

**Comment by paul321** [comment] 2017-06-20 13:46
We have the same behavior our app is doing a lot of ajax requests and even usiing webviews all the cookies are saved in devtools cookies under file:/// after we restart the app and check again the devtools / cookies under file:/// there is nothing, if we open the same webview that we used before to login into a website, it says we are not logged in because there are no cookies. Even mainWindow.webContents.session.cookies.get is returning an empty array. Any suggestion?

Thanks

**Comment by deepak1556** [comment] 2017-06-23 03:59
@chamerling are you not able to retrieve any cookie data which are set after calling `clearStorageData` ? Can you provide a minimal example, its not clear from the description what the problem is. Thanks!

**Comment by chamerling** [comment] 2017-06-23 12:57
@deepak1556 I am going to provide you a server and an electron app, need time for this.

If `clearStorageData` is called, I can still save and retrieve cookies until the app is restarted. If I restart the app, I can not get the cookies previously saved on the previous app launch.

This was working well before the first time I called `clearStorageData`: I was able to store cookies and retrieve them on next app launches. Now it seems that the cookies are never saved to disk anymore.

**Comment by zanza54** [comment] 2017-08-26 13:43
This issue might explain my current issue. Could anyone try out my code in my stackoverflow link and tell me if they have the same issue?
I did execute the ``clearStorageData`` function before trying to get cookies from session in webContents.

**Comment by sofianguy** [comment] 2017-10-17 17:13
@chamerling 
Thank you for your issue!

We haven't gotten a response to our questions in our comment [here](https://github.com/electron/electron/issues/9776#issuecomment-310565152). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2017-10-17 17:13 UTC
Labels: more-information-needed, waiting/needs-repro
