### ISSUE TITLE
Electron crashes when making HTTP request

### ISSUE THREAD

**Issue by vulpino** [electron/electron#6837] opened 2016-08-14 02:01 UTC
Recently upgraded from 0.35 to 1.3, and now, simply put, the electron process (specifically the `webContents`?) crashes every time a request is made to an HTTP URL.

* Electron version: 1.3.3
* Operating system: Arch Linux

There's no discernible error message, the window goes white and the devtools report they have been disconnected, and the `mainWindow.webContents` throws a `crashed` event but not much else. The Network tab of the devtools shows that the request begins and reaches Waiting (TTFB), but does not start actually downloading the content.

I've tried requesting pages using both the `request` and `needle` libraries, and both cause the crash. HTTP calls in the server (i.e., where `app.on('ready')` is defined) do NOT crash the client in any form.

Not sure if I've missed something obvious. Any help would be appreciated.

**Comment by kevinsawicki** [comment] 2016-08-15 21:50
So your main page loaded via `window.loadURL` is crashing? Or is it just requests made from within that page? Do Ajax requests crash as well?

**Comment by ecellani** [comment] 2016-08-16 18:33
I'm having the same situation here.

My main page is loaded via `win.loadURL('file://...')`. That will consume REST JSON web APIs, but the app crash.

**Comment by kevinsawicki** [comment] 2016-08-16 18:34
@ecellani are you also on Arch Linux?

**Comment by ecellani** [comment] 2016-08-16 18:43
No, I am using OSX

**Comment by kevinsawicki** [comment] 2016-08-16 18:51
@ecellani are you able to provide a sample app that reproduces the crash for you?

**Comment by ecellani** [comment] 2016-08-16 18:58
sure, [clone this repo](https://github.com/ecellani/electron-react.git)

**Comment by zcbenz** [comment] 2016-08-17 13:29
Stack trace:

```
0   libmodules.dylib              	0x000000010d97fbde blink::BodyStreamBuffer::processData() + 174
1   libcontent.dylib              	0x000000010b742187 0x10b2d8000 + 4628871
2   libcontent.dylib              	0x000000010b74bb0b content::WebURLLoaderImpl::Context::OnReceivedData(std::__1::unique_ptr<content::RequestPeer::ReceivedData, std::__1::default_delete<content::RequestPeer::ReceivedData> >) + 187
3   libcontent.dylib              	0x000000010b74c2b3 content::WebURLLoaderImpl::RequestPeerImpl::OnReceivedData(std::__1::unique_ptr<content::RequestPeer::ReceivedData, std::__1::default_delete<content::RequestPeer::ReceivedData> >) + 35
4   libcontent.dylib              	0x000000010b72d564 content::ResourceDispatcher::OnReceivedData(int, int, int, int) + 580
5   libcontent.dylib              	0x000000010b72f0fa 0x10b2d8000 + 4550906
```

This is a duplicate of #6830.

**Closed by zcbenz** 2016-08-17 13:29 UTC
Labels: crash, linux
