### ISSUE TITLE
Electron ignores custom system date formats

### ISSUE THREAD

**Issue by craxal** [electron/electron#28206] opened 2021-03-15 22:32 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

Electron should respect to the OS's date/time format settings.

### Actual Behavior

Electron only uses the date/time format for the OS's current locale.

Rehash of #13023.

**Comment by nornagon** [comment] 2021-03-15 22:43
This issue is worse than #13023 so I'm going to close it and reopen the original.

**Comment by nornagon** [comment] 2021-03-15 22:43
Duplicate of #13023

**Closed by nornagon** 2021-03-15 22:43 UTC
Labels: bug :beetle:

**Comment by mfalkvidd** [comment] 2021-03-16 06:54
> This issue is worse than #13023 so I'm going to close it and reopen the original.

Well, stop closing unresolved issues then 😂
