### ISSUE TITLE
BrowserWindow.isMaximized always returns false (at least on Windows anyway)

### ISSUE THREAD

**Issue by westacotta** [electron/electron#12559] opened 2018-04-06 16:48 UTC
* Electron version: 2.0 beta 1
* Operating system: Windows 7

### Expected behavior

After calling BrowserWindow.maximize() then calling BrowserWindow.isMaximized() at some point int he future it should return true

### Actual behavior

returns false

### How to reproduce

Create browser window
call maximize
have some trigger to call isMaximized()

check the value returned.

**Comment by tgambet** [comment] 2018-04-06 17:56
Same issue with version 2.0.0-beta.7 on Windows 10

**Comment by codebytere** [comment] 2018-04-13 16:43
Can't reproduce this on mac, but i think the issue may be this:
> For window without WS_THICKFRAME style, we can not call Maximize().

**Comment by westacotta** [comment] 2018-04-13 16:47
Ah yes that would make sense

Which file is that in?  I'm going to have a look round there myself

**Comment by codebytere** [comment] 2018-04-13 16:49
@westacotta `electron/atom/browser/native_window_views.cc` 

Method starts on line 453!

**Comment by abalad** [comment] 2018-05-30 13:37
In the previous version I used the following code:
```javascript
  ipcMain.on('APPLICATION-MAXIMIZE', () => {
    mainWindow.isMaximized() ? mainWindow.unmaximize() : mainWindow.maximize()
  });
```
But in the current version it does not work anymore :(
The code `mainWindow.isMaximized()` always returns `FALSE`

**Comment by bradleyhodges** [comment] 2018-08-01 13:40
Can confirm this is still an issue. `.isMaximized()` always returns `false` on Windows.

**Comment by wslx520** [comment] 2019-01-17 05:09
same here. electron 3.0.9. 
`frame:false, transparent:true`

**Comment by nornagon** [comment] 2019-01-17 21:45
cc @brenca maybe?

**Comment by suedama1756** [comment] 2019-02-06 18:58
I'm not sure if this is the same issue, but I've found calling BrowserWindow.maximize when you have frame: false, thickFrame: false does not work. IsMaximized() returns false and worse still GetNormalBounds is updated to think the maximized bounds are the new restore bounds. We require thickFrame: false to disable aero snapping in our application. 

My current fix is to replace the maximize method in BrowserWindow when it is created with a call to a native NAPI module. The native napi module wraps the winapi ShowWindow(hWnd, nCmdShow). native.showWindow(window.getNativeWindowHandle(), 3).

Note: NAPI addons work great with electron 4.0 and do not require recompilation across node/electron versions.

**Comment by sofianguy** [comment] 2019-08-09 03:18
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:06
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:06 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows

**Comment by Z3RoMan** [comment] 2019-08-25 10:17
It appears this particular issue is still present in Electron 6.0.4.

- Electron version: 6.0.4
- NodeJS version: 10.16.2
- Windows version: 10 (1903, 24-08-2019)

Whenever the window is maximized, `isMaximized()` will still report false. This issue isn't present on every system, as it will function normally on some, such as my own.

The window in question has the `frame` and `transparent` variable set to `false`. The latter was for testing purposes.

**Comment by rahmatkruniawan** [comment] 2019-11-05 08:57
I still got this problem for windows 10.  But this working on Linux

**Comment by StrasGus** [comment] 2020-05-15 23:27
i have the same issue on electron 8.2.5

**Comment by yurnery** [comment] 2020-05-28 02:46
+1, still have this problem

**Comment by NeptuneNeptune** [comment] 2020-07-11 09:14
The same to me...

**Comment by OriginZero** [comment] 2020-12-14 06:34
It still exists today....

**Comment by gigadeplex** [comment] 2020-12-23 07:31
Hey peeps. To do this you just need three things: 1. browser position, 2. browser size, 3. max window size. Check if browser pos is at 0,0 while the size is at max, if both are true then your window is maximized.
```
const win: BrowserWindow = remote.getCurrentWindow();
const pos: number[] = win.getPosition();
const size: number[] = win.getSize();

const isMaximized: boolean =
      _.isEqual(pos, [0, 0]) &&
      _.isEqual(size, [window.outerWidth, window.outerHeight]);
```

Hope this thing gets fixed soon though... pce.

**Comment by suedama1756** [comment] 2020-12-23 08:27
Not sure why this issue is closed, the window management in electron on windows is pretty bad. I've seen misreported windows states, windows reseting their "normal" bounds to the special -32k coords windows uses internally, frameless windows getting smaller by one pixel each time you log into your windows session, poor support for HDPi etc. Electron team don't seem very interested in fixing and usually blame upstream chrome. Our solution in the end to all these issues was to write a NAPI plugin and call the windows API directly with the window handle. Under the scenes windows does correctly know the state, can report full HDPi information, etc. which makes it even more bizarre that electron does not.

**Comment by westacotta** [comment] 2020-12-23 09:06
Does this account for multiple monitors though?

The window will likely not be zero if maximised on a non-primary monitor.

**Comment by xielikang** [comment] 2021-05-13 07:02
new BrowserWindow({
  minWidth: width,
  minHeight: height,
  resizable: true, // set it, win.isMaximized() can work~，include win.on('maximize || unmaximize')
})
