### ISSUE TITLE
MAS build (2.0.6) is rejected by the App Store

### ISSUE THREAD

**Issue by ivandroid** [electron/electron#13958] opened 2018-08-06 21:43 UTC
* Electron version: 2.0.6
* Operating system: MacOS High Sierra (latest)

### Expected behavior
The mas build should be accepted by the App Store. 

### Actual behavior 
The App Store suddenly started to reject my mas build based on the Electron Framework v. 1.7.9. The upgrade to the last stable version 2.0.6 didn’t solve the problem. Any ideas?

I always get the following message:

Your app uses or references the following non-public APIs:

From framework: 
-Symbol: _CGDisplayUsesForceToGray
From framework: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
-Symbols: ___CFRunLoopSetOptionsReason, __CFIsObjC
From framework: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

In binary: 
-Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework

Please help.

**Comment by nornagon** [comment] 2018-08-06 22:45
Duplicate of #13938

**Closed by nornagon** 2018-08-06 22:45 UTC
