### ISSUE TITLE
[Bug]: ReduceIPAddressChangeNotification not set in Chromium, leading to many ERR_NETWORK_CHANGED on macOS

### ISSUE THREAD

**Issue by jshier** [electron/electron#42546] opened 2024-06-18 02:01 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

All

### What operating system are you using?

macOS

### Operating System Version

macOS 14.5

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

Unknown

### Expected Behavior

Chromium fixed a bug in v124 where network requests on macOS would often fail due to the frequent creation and teardown of network interfaces by the OS, especially when connected to Apple devices for development. Chromium added the `ReduceIPAddressChangeNotification` flag to try and address this behavior. Many, if not all of the Electron apps I use suffer from this bug, so having Electron set it directly by default would help make Electron apps on macOS much more reliable.

https://chromium-review.googlesource.com/c/chromium/src/+/5348265

### Actual Behavior

Without this flag many apps fail network calls repeatedly. Depending on their resilience this could even present as a DoS, as they may not retry requests. Today's Discord update failed repeatedly during load due to this bug.

### Additional Information

I searched the codebase and didn't see any use of this flag so I assumed it wasn't used.

**Comment by jshier** [comment] 2024-06-24 22:14
This is becoming increasingly annoying, so I'm perfectly willing to do a PR myself if someone can point me to where these settings live.

**Comment by michalzaq12** [comment] 2024-07-03 08:07
This has already been fixed in Electron 31 and newer versions (Chromium from version 124 has the `ReduceIPAddressChangeNotification` flag enabled by default)

**Comment by jshier** [comment] 2024-07-03 14:10
Ah, they enabled it by default later, it was just disabled in that changeset. Guess I'll keep reminding the apps I use to update. And I also don't think the flag completely fixes the issue, just makes it less common, depending on the frequency of the interface changes.

Should I just close this?

**Comment by clavin** [comment] 2024-07-03 17:05
Sounds like this issue got resolved naturally :) I'm going to close it out as completed, based on the analysis above that this flag got enabled by default in Chromium 124.

Regarding the point that this flag is not a full fix for the root cause, only making it very rare: since the root cause exists in Chromium, I'd say it's best to track the problem in their issue tracker.

**Closed by clavin** 2024-07-03 17:05 UTC
Labels: platform/macOS, bug :beetle:, 32-x-y
