### ISSUE TITLE
webRequest.onBeforeSendHeaders callback response requestHeaders not optional in 7.0.0

### ISSUE THREAD

**Issue by binux** [electron/electron#20751] opened 2019-10-25 21:24 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.0.0
* **Operating System:**
  * macOS
* **Last Known Working Electron version:**
  * v6.1.2

### Expected Behavior
Additional headers sent without changes as documented
https://github.com/electron/electron/blob/v7.0.0/docs/api/web-request.md

> https://github.com/electron/electron/blob/v7.0.0/docs/api/web-request.md

```
<head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-GB",
    "Addition-Header": "hello world",
    "Host": "httpbin.org",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-User": "?1",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.146 Electron/6.1.2 Safari/537.36"
  }
}
</pre></body>
```

### Actual Behavior
Additional headers removed and not sent to server.

```
<head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "headers": {
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-GB",
    "Host": "httpbin.org",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "none",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3905.1 Electron/7.0.0 Safari/537.36"
  }
}
</pre></body>
```

### To Reproduce
run following snippet:
https://gist.github.com/binux/3c2023793e1bf1ff03a8fcb24b026162

```
electron electron_bug.webRequest.onBeforeSendHeaders.js
```

### Additional Information

Workaround will be change callback as `callback({ requestHeaders: details.requestHeaders })`.

**Comment by sandeep1995** [comment] 2019-11-26 08:20
I am trying to connect to a local WebSocket server.
For connecting to the WebSocket server, I need to set the `Origin` header to be `null`

I was on electron `4.2.x`, it was working fine then. I tried upgrading to electron `7.1.1`, it's not working now.

I am using the following code
```js
session.defaultSession.webRequest.onBeforeSendHeaders(
  {
    urls: [
      '*://*/*',
    ],
  },
  (details, callback) => {
    let reqHeaders = Object.assign({}, details.requestHeaders, {
      Origin: null,
    });
    callback({
      cancel: false,
      requestHeaders: reqHeaders,
    });
  }
);
```

**Comment by vladimiry** [comment] 2019-11-26 08:29
@sandeep1995 I'd suggest trying 7.1.2+, see #20923 for details.

**Comment by jalanga** [comment] 2019-11-28 11:13
@vladimiry on 7.1.2, ```onBeforeSendHeaders``` is not called, at leas I can't find an output in console after a ```console.log```. The header CCC is not sent, neither the origin. Any suggestions please?
```
  session.defaultSession.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
    details.requestHeaders.Origin = constants.originHeader;
    details.requestHeaders.CCC = '1';
    callback({
      cancel: false,
      requestHeaders: details.requestHeaders
    });
  });
```

**Comment by sandeep1995** [comment] 2019-11-28 17:53
I am still not able to connect to a local WebSocket server from the renderer as I could not modify the `Origin`

I tried `7.1.2` and even electron `8.0.0-beta.3`. Still no luck.

**Comment by vladimiry** [comment] 2019-11-28 18:49
@sandeep1995 origin header is being successfully modified here https://github.com/vladimiry-playground/electron-quick-start-cors-issue/blob/357c37682d5f881d76a7be94c995edc7d22c35ac/main.js#L70 using electron@v7.1.2

**Comment by sandeep1995** [comment] 2019-11-28 18:58
@vladimiry Maybe that is because you are trying to modify for an XHR request.
I am trying for a WebSocket (`wss://`) request.

According to my investigation, it seems like it's a bug on the Chromium side which got fixed in Chromium version [`80.0.3979.1`](https://github.com/chromium/chromium/commit/9ff2e3335e9b05a2c3efa0fc3f1f6f2c965a530f)

Sadly currently Electron 9 nightly build uses `8.0.3954.0` so I can not test

**Comment by vladimiry** [comment] 2019-11-28 19:02
Got it, so I overlooked the websockets use.

**Comment by danielweck** [comment] 2020-06-05 15:10
I filed a similar issue for Electron v8 and `WebRequest.onBeforeSendHeaders` (`WebRequest.onHeadersReceived` seems to "do the right thing" as per the documentation and previous Electron versions' behaviour).
I provided a Gist to reproduce the issue in the console, and compare `onBeforeSendHeaders` vs. `onHeadersReceived`:
https://github.com/electron/electron/issues/23988

**Comment by danielweck** [comment] 2020-06-05 15:30
I have now executed tests with the latest available version of each of the 3 major Electron revisions (i.e. `6.1.2`, `7.3.1`, `8.3.1`) via Electron Fiddle, and I can confirm that the regression bug seems to appear after v6.

See: https://github.com/electron/electron/issues/23988

According to my tests with Electron Fiddle, version `6.1.2` is not affected, but versions `10.0.0-beta.2`, `9.0.2`, `8.3.1` and `7.3.1` are affected, so this seems like a regression from version 6 to 7+.

**Comment by binux** [comment] 2020-09-06 01:22
NOTE: the workaround `callback({ requestHeaders: details.requestHeaders })` will cause the request header reordered when sent to target website, which might be used as a fingerprint to detect electron.

There is an other workaround `callback(undefined)` wouldn't have this issue if you just want to peek on the headers sent. (you have to specifically send `undefined` here, otherwise will get a `TypeError: Insufficient number of arguments.` error.

**Closed** 2021-06-22 06:08 UTC
Labels: 10-x-y, 7-1-x, bug :beetle:, platform/macOS
