### ISSUE TITLE
9.0.x version won't work on windows 10

### ISSUE THREAD

**Issue by leolivier** [electron/electron#24035] opened 2020-06-09 20:29 UTC
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Downloaded 9.0.2 and 9.0.3 electron.exe --version does not provide anything
* **Operating System:**
  * Windows 10 Insider preview (build 19631.1)
* **Last Known Working Electron version:**
  * 8.3.5
### Expected Behavior
Double-click on electron in file explorer should open a window.
### Actual Behavior
Nothing happens. Starting from a terminal does not open a UI and does not show any trace even using 

```
PS C:\Users\olivi\Downloads\electron903> .\electron.exe --version
PS C:\Users\olivi\Downloads\electron903> .\electron.exe --enable-logging -v=10
PS C:\Users\olivi\Downloads\electron903>
```
### To Reproduce
1. Downloaded electron-v9.0.3-win32-x64.zip from the releases.
2. Unzip it in a directory
3. Double click on electron.exe in the file explorer
4. Or run .\electron.exe in the directory from a windows terminal
5. Absolutely nothing happens, and you get back to the prompt

### Additional Information
Bug discovered while testing keeweb 1.15.x which runs on electron 9.0.x
Keeweb 1.14.3 running on electron 8.2.5 works fine
I downloaded electron 8.3.5 and did the same (unzip in a directory and double clic) and it works!!!

**Comment by HashimotoYT** [comment] 2020-06-09 20:33
Duplicate of #23841

**Closed by HashimotoYT** 2020-06-09 20:33 UTC
