### ISSUE TITLE
[Bug]: Regression in File System API after partial proper implementation in v30

### ISSUE THREAD

**Issue by bradisbell** [electron/electron#42983] opened 2024-07-22 03:54 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.2.1

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2 22621.3880

### What arch are you using?

x64

### Last Known Working Electron version

29

### Expected Behavior

In Electron v29 and previous, we could enable file system access with a flag:

```
app.commandLine.appendSwitch('enable-experimental-web-platform-features');
```

This would always approve file system access.  A FileSystemDirectoryHandle could be persisted to IndexedDB, loaded again on a subsequent app load, and the app could then still access files in the directory.

### Actual Behavior

Since there was a partial implementation of permissions with https://github.com/electron/electron/issues/28422, it is no longer possible for the experimental web platform features flag to enable access to directories.  Loading previously  `granted` directories now only gives `prompt` permissions.  But, there is seemingly no way to actually prompt for permissions anyway.

### Testcase Gist URL

https://gist.github.com/bradisbell/86ae72ea9709c471a0c4f49fea9dd0e0

### Additional Information

What we really need is a way for the main app to just approve file system access like other permissions.

Please see the Electron Fiddle gist for a concrete example.

**Comment by bradisbell** [comment] 2024-07-22 04:01
@codebytere Any thoughts on this?  I think you're the expert on this area of Electron.

**Comment by codebytere** [comment] 2024-07-22 08:21
Duplicate of https://github.com/electron/electron/issues/41957 - please continue tracking there

**Closed by codebytere** 2024-07-22 08:21 UTC
Labels: bug :beetle:, has-repro-gist, 31-x-y
