### ISSUE TITLE
Electron 2.0.1 'transparent: true' having issues with Windows 10 build 1803

### ISSUE THREAD

**Issue by zJesusJavier** [electron/electron#13001] opened 2018-05-18 16:13 UTC
* Electron Version: 2.0.1
* Operating System (Platform and Version): Windows 10 build 1803 x64
* Last known working Electron version: 2.0.0

**Expected Behavior**
The Window should open properly with 'transparent: true'.

**Actual behavior**
With **'transparent: true'** enable the Windows opens very small and is not resizable or maximizable. 

**To Reproduce**
Add 'transparent: true' to your main.js.

**Screenshots**
Without 'transparent: true'
![8fb4ee92d9c8dc386db335869b5cf18e](https://user-images.githubusercontent.com/39272785/40245563-1bf68ca6-5a94-11e8-86b2-84d19850d121.gif)

With 'transparent: true'
![78a5dd0cd2f03d53bb34fd0c2a89cc04](https://user-images.githubusercontent.com/39272785/40245752-7c20126e-5a94-11e8-96eb-d2f301f42ac6.gif)

**Comment by brenca** [comment] 2018-05-18 17:26
This is a duplicate of #12989

**Closed by brenca** 2018-05-18 17:26 UTC
