### ISSUE TITLE
[Bug]: intermittent segfault in JS on windows 7

### ISSUE THREAD

**Issue by nevermore-kl** [electron/electron#28561] opened 2021-04-07 06:17 UTC
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 7 SP1

### What arch are you using?

ia32

### Last Known Working Electron version

9.3.5

### Expected Behavior

webview can be loaded successfully

### Actual Behavior

random webview crashed in windows

This is the crash report
[report.zip](https://github.com/electron/electron/files/6269372/report.zip)

**Comment by nornagon** [comment] 2021-04-09 22:56
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).

**Comment by NeverMore-KL** [comment] 2021-04-13 02:40
> The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).

this bug occurred in v11.3.0

**Comment by nornagon** [comment] 2021-04-20 22:54
Oops, sorry, I misread. Thanks for the clarification.

The stack traces you're reporting look like they're crashing in blink, not Electron. Are you seeing the same issues on Electron 12 or 13 (which include newer versions of Chromium)?

**Comment by NeverMore-KL** [comment] 2021-04-23 10:38
> Oops, sorry, I misread. Thanks for the clarification.
> 
> The stack traces you're reporting look like they're crashing in blink, not Electron. Are you seeing the same issues on Electron 12 or 13 (which include newer versions of Chromium)?

I created a demo(run in 11,12,13)
load ten webviews at once or quickly add webview
some webview cannot loaded 
minidump in `%appdata%/electron-react-boilerplate`
run in window7 sp1 x86 


https://github.com/NeverMore-KL/electron-28561

**Comment by nornagon** [comment] 2021-04-23 22:01
Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

Thanks in advance! Your help is appreciated.

**Comment by NeverMore-KL** [comment] 2021-04-25 05:46
> Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Thanks in advance! Your help is appreciated.

I created
https://gist.github.com/a81d42b5301a6d4511e505868cf751e6

**Comment by NeverMore-KL** [comment] 2021-04-25 06:02
It appears when I package ia32 run in win7 x86 and x64

**Comment by jiangjianping** [comment] 2021-04-27 02:24
I test from electron 10-13, this fatal error only occurred in windows7.

**Comment by jiangjianping** [comment] 2021-04-27 02:31
@NeverMore-KL 

BTW, where can I find the crash report in windows 7 like you mentioned? An alternative solution till now is: catch the render-process-gone and reload the page/url.

**Comment by NeverMore-KL** [comment] 2021-04-27 04:53
> @NeverMore-KL
> 
> BTW, where can I find the crash report in windows 7 like you mentioned? An alternative solution till now is: catch the render-process-gone and reload the page/url.

use `crashReporter` generate minidump in `%appdata%/{your app name}/crashed` or use `Sentry`

reload when webview crashed too

**Comment by nornagon** [comment] 2021-04-27 18:51
It's likely this is a duplicate of #28487, but without a crash dump it's hard to say for sure. I'll leave this open until we get a crash dump.

**Comment by NeverMore-KL** [comment] 2021-04-28 06:55
> It's likely this is a duplicate of #28487, but without a crash dump it's hard to say for sure. I'll leave this open until we get a crash dump.

console output in debug mode
`Exception thrown during bootstrapping
Error installing extension 'extensions::SafeBuiltins'.
[5076:0428/145240.492:FATAL:v8_initializer.cc(95)] V8 error: Empty MaybeLocal. (
v8::ToLocalChecked).`

this is crash report
[crash-report.zip](https://github.com/electron/electron/files/6389637/crash-report.zip)

**Comment by jiangjianping** [comment] 2021-04-28 22:51
Exception thrown during bootstrapping
installing extension:extensions::SafeBuiltins
Error installing extension 'extensions::SafeBuiltins'.
[7588:0415/151203.689:FATAL:v8_initializer.cc(95)] V8 error: Empty MaybeLocal. (
v8::ToLocalChecked).
[2021-04-15 15:12:03.708]-[info]: mainwindow render process gone:::{"reason":"cr
ashed","exitCode":-2147483645}
[2021-04-15 15:12:08.559]-[info]: [index.js]::mainWindow not show in time
installing extension:extensions::SafeBuiltins


#
# Fatal error in , line 0
# ignored
#
#
#
#FailureMessage Object: 0015D998Backtrace:
        v8::internal::Version::GetString [0x01D229D3+595]
        v8::MemorySpan<unsigned char const >::MemorySpan<unsigned char const > [
0x012F4D41+213729]
        v8::Isolate::NumberOfHeapSpaces [0x053AE924+1013988]
        v8::FunctionTemplate::RemovePrototype [0x03E01DB2+511650]
        v8::Value::IsInt32 [0x0399C3BB+152939]
        v8::MemorySpan<unsigned char const >::MemorySpan<unsigned char const > [
0x012E1791+134449]
        v8::MemorySpan<unsigned char const >::MemorySpan<unsigned char const > [
0x012E1696+134198]
        v8::MemorySpan<unsigned char const >::MemorySpan<unsigned char const > [
0x012E0E18+132024]
        v8::MemorySpan<unsigned char const >::MemorySpan<unsigned char const > [
0x012E0B08+131240]
        v8::Object::SetPrototype [0x0166C938+73544]
        v8::Object::SetPrototype [0x0166C6DB+72939]
        v8::Object::SetPrototype [0x0166BB22+69938]
        v8::Object::SetPrototype [0x0166B911+69409]
        v8_inspector::protocol::Binary::operator= [0x02CB99F7+371799]
        v8_inspector::protocol::Binary::operator= [0x02C65AF5+27989]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C65A66+27846]
        v8_inspector::protocol::Binary::operator= [0x02C63D78+20440]
        v8_inspector::protocol::Binary::operator= [0x02C63B9B+19963]
        v8::Isolate::GetCurrentContext [0x036FC4CA+189690]
        v8::Isolate::GetCurrentContext [0x036FB250+184960]
        v8::Script::Run [0x017D6250+432]
        v8::TryCatch::CanContinue [0x017D57FE+2558]
        std::__1::vector<v8::CpuProfileDeoptInfo,std::__1::allocator<v8::CpuProf
ileDeoptInfo> >::end [0x017D4977+1255]
        v8::StackFrame::GetScriptName [0x017D444C+191052]
        v8::StackFrame::GetScriptName [0x017D4228+190504]
        v8::Isolate::CreateParams::CreateParams [0x026CE2F6+676230]
        v8_inspector::V8StackTraceId::V8StackTraceId [0x01A07D92+325426]
        v8_inspector::V8StackTraceId::V8StackTraceId [0x01A07B40+324832]
        v8::BackingStore::operator delete [0x01882E6F+70271]
        v8::BackingStore::operator delete [0x01882D98+70056]
        v8::BackingStore::operator delete [0x01882CEB+69883]
        v8::String::StringEquals [0x01D7CFB9+69833]
        v8::String::StringEquals [0x01D7CDA3+69299]
        v8::MicrotasksScope::PerformCheckpoint [0x036A33DC+15868]
        v8::MicrotasksScope::PerformCheckpoint [0x036A19B8+9176]
        v8::MicrotasksScope::PerformCheckpoint [0x036A1593+8115]
        v8::FunctionTemplate::RemovePrototype [0x03D9E032+102690]
        v8_inspector::StringView::is8Bit [0x01ADF68E+7358]
        v8::Template::SetLazyDataProperty [0x018193AD+52941]
        v8_inspector::V8StackTraceId::V8StackTraceId [0x019E2698+172088]
        electron::fuses::IsRunAsNodeEnabled [0x02C58670+434224]
        electron::fuses::IsRunAsNodeEnabled [0x02C58C7D+435773]
        v8::Extension::set_auto_enable [0x01EABF7D+123037]
        v8::Extension::set_auto_enable [0x01EABB1F+121919]
        GetHandleVerifier [0x02A9A93C+3586732]
        v8::FunctionTemplate::RemovePrototype [0x03DCB89A+289162]
        BaseThreadInitThunk [0x756BEF8C+18]
        RtlInitializeExceptionChain [0x76EB367A+239]
        RtlInitializeExceptionChain [0x76EB364D+194]

**Comment by nornagon** [comment] 2021-04-29 22:09
Duplicate of #28487

**Closed by nornagon** 2021-04-29 22:09 UTC
Labels: bug :beetle:, crash :boom:
