### ISSUE TITLE
[Bug]: thick windows frame showing on startup with frameless window

### ISSUE THREAD

**Issue by bpasero** [electron/electron#32583] opened 2022-01-22 08:42 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.x

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

13.x

### Expected Behavior

Starting a frameless window with hidden title does not draw a thick frame.

### Actual Behavior

I see a thick frame:

![Recording 2022-01-22 at 09 41 34](https://user-images.githubusercontent.com/900690/150631317-18da4e2d-9c1a-4670-8694-23e460ea9900.gif)

Compared to Electron 13:

![Recording 2022-01-22 at 09 42 32](https://user-images.githubusercontent.com/900690/150631349-2c9a460d-5b10-4da0-89fd-774d2bee79ed.gif)

### Testcase Gist URL

https://gist.github.com/cawa-93/2b4c2171fc64899bb394d0e83896f853

**Comment by bpasero** [comment] 2022-01-22 08:43
cc @deepak1556

**Comment by samuelmaddock** [comment] 2022-01-22 19:05
Duplicate of #30760

**Closed by samuelmaddock** 2022-01-22 19:05 UTC
Labels: bug :beetle:
