### ISSUE TITLE
Click event ignored with on macOS

### ISSUE THREAD

**Issue by kirly-af** [electron/electron#7983] opened 2016-11-15 23:00 UTC
I am aware of #6773, but I thought this should be a separate issue (the former being Ubuntu specific). 
@seppestas maybe can tell if it's a duplicate ?

Consider the following simple app:

```js
const {app, Menu, Tray} = require('electron')

app.on('ready', () => {
    const appIcon = new Tray('/path/to/icon.png')
    const contextMenu = Menu.buildFromTemplate([
        {label: 'Item1', type: 'radio'},
        {label: 'Item2', type: 'radio'}
    ])

    appIcon.setContextMenu(contextMenu)
    appIcon.on('click', () => console.log('click'))
})
```

`click` events are not fired when clicking the tray icon. As noted in #6773, this means [menubar](https://github.com/maxogden/menubar) apps will not work.

macOS version: 10.12
Electron version: 1.4.6

**Comment by kevinsawicki** [comment] 2016-11-15 23:12
I  believe this is a duplicate of https://github.com/electron/electron/issues/4796.

The click event isn't fired when a context menu is explicitly set via `setContextMenu`, you can use `popUpContextMenu` to pop up the menu in response to a click event.

https://github.com/electron/electron/blob/307b504eb411add469fb9e9bbf8fea93ece178b9/atom/browser/ui/tray_icon_cocoa.mm#L234-L239

If you comment out ` appIcon.setContextMenu(contextMenu)` you'll see that the click event does fire.

**Closed by kevinsawicki** 2016-11-15 23:12 UTC

**Comment by kirly-af** [comment] 2016-11-15 23:22
Thanks a lot @kevinsawicki, saved my day !
