### ISSUE TITLE
electron clipboard writeImage only png type

### ISSUE THREAD

**Issue by sanghoTW** [electron/electron#14601] opened 2018-09-13 02:54 UTC
ex]
let image = nativeImage.createFromDataURL(reader.result);
clipboard.writeImage(image, 'jpeg'); 

React js and Electron are used together.
Even if the jpeg type is specified, it is saved as a png file to the clipboard.
Please tell me how I am converting in the wrong way, thank you.

**Comment by MarshallOfSound** [comment] 2018-09-13 03:36
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by sanghoTW** [comment] 2018-09-13 04:09
> It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.
> 
> In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.



> It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.
> 
> In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.



> It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.
> 
> In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

---------------------------------------------------------------------------------------------------------



* Output of `node_modules/.bin/electron --version`: 

[ I have verified the package.json file. ]
    "electron": "2.0.2",
    "electron-builder": "19.31.1",
    "electron-prebuilt": "^1.4.13",
    "electron-rebuild": "^1.5.11",

* Operating System (Platform and Version):   [ window10 ]


* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

### Expected behavior

  [  jpeg type images must be saved to the clipboard.]

### Actual behavior

                 [ An image of type png is saved to the clipboard. ] 

### How to reproduce

**Comment by sanghoTW** [comment] 2018-09-13 04:12
* Output of `node_modules/.bin/electron --version`: 

[ I have verified the package.json file. ]
    "electron": "2.0.2",
    "electron-builder": "19.31.1",
    "electron-prebuilt": "^1.4.13",
    "electron-rebuild": "^1.5.11",

* Operating System (Platform and Version):   [ window10 ]
### Expected behavior

  [  jpeg type images must be saved to the clipboard.]

### Actual behavior

                 [ An image of type png is saved to the clipboard. ] 


[Security is not possible. Sorry. Attach react source code instead.]

copyClipboard(){
        let that = this;
        var xhr = new XMLHttpRequest();
        xhr.onload = function() {
            var reader = new FileReader();
            reader.onloadend = function() {    
     
                let image = nativeImage.createFromDataURL(reader.result);
                clipboard.writeImage(image, 'jpeg');

            }
            reader.readAsDataURL(xhr.response);
        };
        xhr.open('GET', imgURL);
        xhr.responseType = 'blob';
        xhr.send();
}

**Comment by biosina1** [comment] 2018-09-14 03:04
> 귀하가 [이슈 템플릿을](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) 작성하지 않은 것처럼 보입니다. [문제 템플릿](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) 에 요청 된 모든 정보를 제공해 주시면 도와 드리겠습니다.
> 
> 장래에 템플릿없이 작성한 이슈가 닫히면 [여기](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) 에서 이슈 템플릿을 찾을 수 있으며 새로운 이슈 양식에 자동으로 채워집니다.


Please check my comment. ^^

**Comment by sofianguy** [comment] 2019-08-08 23:52
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:34
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:34 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
