### ISSUE TITLE
Preload script doesn't execute on Windows

### ISSUE THREAD

**Issue by arquLV** [electron/electron#8893] opened 2017-03-10 13:42 UTC
* Electron version: 1.6.3 (tried everything down to 1.5.1)
* Operating system: Win10 64bit

Recently tried building a Windows version of an app we've been developing for Mac OS for some time.

```javascript   
   windows.main = new BrowserWindow({
      width: display.width,
      height: display.height,
      minWidth: 1020,
      minHeight: 600,
      resizable: true,
      titleBarStyle: "hidden-inset",
      frame: (os == 'darwin' ? false : true),
      show: (os == 'darwin' ? false : true),
      webPreferences: {
         nodeIntegration: true,
         preload: (os == 'win32' ? 'file://' : '') + path.join(app.getAppPath(), 'windows/main.js')
      }
   })
```
Preload script loads and works fine on Mac OS. However on Windows it seems it isn't executed. Console.logs don't work and since I expose `Electron = { ... }` global object there, it isn't visible and I get a not defined error in the Meteor app inside.

```
Uncaught ReferenceError: Electron is not defined
    at meteorInstall.client.startup.js
```

Any ideas how to approach this?

**Comment by j-f1** [comment] 2017-03-10 13:44
`path.join(app.getAppPath(), 'windows', 'main.js')`? Windows uses `\` as path delimiters.

**Comment by MarshallOfSound** [comment] 2017-03-10 13:47
As @j-f1 mentioned the path separator on Windows is not the same as darwin or linux.  You should use `path.resolve` without any slashes in the path.

Also you might find a more deterministic path to the file is `path.resolve(__dirname, '..', 'path', 'to', 'main.js')`  "__dirname" is the current directory of the current file 👍

**Comment by arquLV** [comment] 2017-03-10 13:57
Thanks but that doesn't really help. I've tried just writing the full path there as well (and opening it with fs read to check if it's right).
I'm pretty sure there's something else responsible for this :/

**Comment by MarshallOfSound** [comment] 2017-03-10 14:01
@arquLV Wait, why do you have the conidition win32 check for `file://` you just need to path not a URI scheme as well.

For instance this is what my preload script looks like

```js
preload: path.resolve(`${__dirname}/../renderer/generic/index.js`),
```

**Comment by arquLV** [comment] 2017-03-10 14:31
Random resources on the web where people said windows needs it, e.g. https://discuss.atom.io/t/unable-to-load-preload-script-on-windows-7-environment/28607/3

Without it I get the mentioned `unable to load preload script` error in the console. I've tried many different ways to write the path. No luck so far.

**Comment by MarshallOfSound** [comment] 2017-03-10 14:33
@arquLV Can you provide a minimal sample application that replicates your issue.  As mentioned before the code I supplied is known to work on all platforms 👍

**Comment by premitius** [comment] 2017-03-16 20:26
I have the exact same error. The preload script loads (no "unable to load preload script" errors) but doesn't run.

**Comment by jrobeson** [comment] 2017-03-16 22:06
@premitius If you want people to to be able to figure out the issue, then you're gonna need to create a minimal example application that can reproduce it as @MarshallOfSound says.

**Comment by premitius** [comment] 2017-03-17 14:30
I think I figured it out. When my preload path was incorrect, the preload script didn't load, and no errors were thrown. However if I used:

preload: path.resolve(`${__dirname}/../renderer/generic/index.js`),

The preload script was loaded but I got an error "Unable to load preload script" which is confusing, since the preload script did load, as well as an error that one of my native modules node-sqlite3 couldn't be found. If this fixes the problem for @arquLV maybe the solution is to make the error messages a bit more clear and don't say that the preload script didn't load when it actually did.

**Comment by MarshallOfSound** [comment] 2017-03-17 15:23
FYI: The "Unable to load preload script" error occurs when we failed to load your preload script because it threw an error during load

**Comment by premitius** [comment] 2017-03-18 00:41
@MarshallOfSound yes, the phrasing confused me. "Unable to load preload script" means in my world that the preload script couldn't load (wasn't found). Maybe replace with the phrasing to something like "There was an error in the preload script 'preload.js'"?

**Comment by kevinsawicki** [comment] 2017-03-31 22:27
Closing this out since it seems the original issues seems to be resolved, pull request welcomed to make the errors more clear.

**Closed by kevinsawicki** 2017-03-31 22:27 UTC

**Comment by viatenaw** [comment] 2019-12-28 16:27
Hey guys 

> @MarshallOfSound yes, the phrasing confused me. "Unable to load preload script" means in my world that the preload script couldn't load (wasn't found). Maybe replace with the phrasing to something like "There was an error in the preload script 'preload.js'"?
@premitius 
@kevinsawicki 
Exactly the same issue I'm facing, It was able to successfully load modules like 'tracer' and 'ipcRenderer' but failed to load a few modules like 'request', 'fs-extra'.
The error message is very generic and confusing, cause actually it fails to load some module from required in the script. This is very confusing and I have no idea what could make it not load odd modules, any help would be very much appreciated.

**Comment by ryanpdwyer** [comment] 2020-08-08 02:05
I also rand into this issue - I second that the phrasing is confusing - 'there was an error in the preload script "preload.js"' would be much more helpful.
