### ISSUE TITLE
[Bug]: Screen permissions are granted but have no effect

### ISSUE THREAD

**Issue by Guuuxu** [electron/electron#35039] opened 2022-07-25 03:18 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.9

### What operating system are you using?

macOS 12.0.1

### Operating System Version

macOS Monterey 13-inch,m1,2020

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

not found

### Expected Behavior

after i install my electron app, screen permissions are selected by default.

<img width="524" alt="截屏2022-07-25 上午11 01 28" src="https://user-images.githubusercontent.com/33110299/180692645-d6120881-108c-4a04-986b-eb37b0103ceb.png">

but the result of systemPreferences.getMediaAccessStatus('screen') is `denied`
<img width="363" alt="截屏2022-07-25 上午11 05 30" src="https://user-images.githubusercontent.com/33110299/180692081-20b6bc51-18ab-4bd8-ac22-ceb23968c366.png">

I want permission to share the screen or window

### Actual Behavior

It didn't work

**Comment by has-n** [comment] 2022-07-25 04:16
Can confirm the same issue on MacOS 12.0.1. 

FWIW, this happens when my app is launched by Playwright from a CircleCI pipeline. 

If the app is launched locally by Playwright, the app can see the permission.

**Comment by codebytere** [comment] 2022-07-25 07:51
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by MarshallOfSound** [comment] 2022-07-25 08:05
@has-n @Guuuxu Permissions for screen sharing (and other similar permissions) are provided via TCC on macOS which works via inheritance.  i.e. if you launch `MyApp` from terminal it actually inherits the TCC permissions of `Terminal` not `MyApp`.

This means that you actually need to (for instance on CircleCI) provide TCC screen capture permissions to Terminal and sshd, not your actual app

**Closed by MarshallOfSound** 2022-07-25 08:05 UTC
Labels: bug :beetle:, blocked/need-repro

**Comment by has-n** [comment] 2022-07-25 21:06
Thanks for your continued support @MarshallOfSound . That still didn't work. I can confirm that the permissions are assigned but the app still doesn't see the permission.

```
com.app_name.app                                          kTCCServiceMicrophone     2         
com.apple.Terminal                                        kTCCServiceMicrophone     2         
com.github.Electron                                       kTCCServiceMicrophone     2         
/usr/sbin/sshd                                            kTCCServiceMicrophone     2         
```

**Comment by ibc** [comment] 2022-12-21 10:28
This is easy to reproduce in any Electron app in macOS Monterey 21.5:
- I assume you are gonna launch the app from `Terminal.app` so media permissions must be those in `Terminal.app`.
- Before launching the Electron app ensure that "Microphone" and "Screen Recording" permissions are not enabled for `Terminal.app` in OSX "Preferences - Security & Privacy".
     <img width="679" alt="CleanShot-2022-12-21-at-11 22 57@2x" src="https://user-images.githubusercontent.com/16191/208882422-d088ed7c-1d8f-46b0-90cf-cd8379edecbe.png">
- Open `Terminal.app` and launch the Electron app.
- Run `systemPreferences.getMediaAccessStatus('microphone')`. It will return `denied` as expected.
- Run `systemPreferences.getMediaAccessStatus('screen')`. It will return `denied` as expected.
- Grant `Terminal.app` permission in "Microphone" and "Screen Recording" sections. Don't close `Terminal.app` but click on "Later" button instead.
    ![CleanShot-2022-12-21-at-11 26 12@2x](https://user-images.githubusercontent.com/16191/208883104-4f71caa9-fe4e-46e7-9a61-7dc15d7c1d17.png)
- Run `systemPreferences.getMediaAccessStatus('microphone')`. Now it will return `granted` as expected.
- Run `systemPreferences.getMediaAccessStatus('screen')`. It will still return `denied`. This is the problem: 'screen' permission changes are not updated in Electron land when querying for the permission again.

**Comment by ibc** [comment] 2022-12-21 10:37
I'm gonna delete my last comment since the original reported issue was different.
