### ISSUE TITLE
Canceling the print dialog via the "print()" call in dev tools, breaks applications

### ISSUE THREAD

**Issue by xpyxel** [electron/electron#19937] opened 2019-08-25 17:20 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.2
* **Operating System:**
  * Pop! OS x64 19.04 5.0.0-25-generic
* **Last Known Working Electron version:**
  * 4.2.7

### Expected Behavior
App should remain working as normal, continue working as it should.

### Actual Behavior
Application seems to break completely, clicking in the client either reloads the app, crashes it, or it stays broken, components in things like React no longer work properly, hitting enter in text boxes create a new line instead of sending, signaling that javascript and other functionality is no longer working.

### To Reproduce
1. Open dev tools in any Electron based application
2. Open dev tools, and go to the javascript console
3. Type `print();` in the console, and hit enter
4. Click the "cancel" button on the print dialog
5. Attempt to interact normally with the app

### Screenshots
Not applicable in this situation

### Additional Information
All functionality seems to break, in this bug. Javascript seems to stop completely.

**Comment by Rahun** [comment] 2019-09-02 07:14
Оn Windows too.
since print() is blocking js for execution, then when you click cancel, there is simply no way out of the method.

**Comment by vladimiry** [comment] 2019-09-11 05:52
Linux is also affected, quite severe issue.

**Comment by TerrapinSoftware** [comment] 2019-10-03 15:20
Tested on WIndows 10 latest build (10.0.17763.737) and Mac OSX 10.14.6 as well: Steps to reproduce: 

1) Download the Get Started app
2) Edit index.html and add `<button onclick="window.print()>Click me</button>`
3) Run the app
4) Click button
5) In the print dialog, click Cancel
6) Try to click the button again: nothing happens

**Please increase the priority. This appears to affect all Electron programs!!!**

**Comment by codebytere** [comment] 2020-03-03 23:34
This has been fixed in v7 and beyond.

**Closed by codebytere** 2020-03-03 23:34 UTC
Labels: 6-1-x, bug :beetle:, platform/macOS
