### ISSUE TITLE
Electron project can't start normally without network environment

### ISSUE THREAD

**Issue by 1772844816** [electron/electron#13779] opened 2018-07-24 07:08 UTC
* Electron Version:2.0.4
* Operating System (Platform and Version):Windows 10 64bit
* Node version:v8.0.4
* Last known working Electron version: Unknown

**Expected Behavior**
The Electron project can start normally when all network adapters are disabled or network cables are unplugged.

**Actual behavior**
Electron cannot start because of the following error:
```sh
dns.js:246 Uncaught Error: EFILE
    at new Resolver (dns.js:246)
    at dns.js:377
    at dns.js:431
    at NativeModule.compile (bootstrap_node.js:606)
    at NativeModule.require (bootstrap_node.js:550)
    at net.js:45
    at net.js:1730
    at NativeModule.compile (bootstrap_node.js:606)
    at NativeModule.require (bootstrap_node.js:550)
    at internal/child_process.js:6
Resolver	@	dns.js:246
(anonymous)	@	dns.js:377
(anonymous)	@	dns.js:431
NativeModule.compile	@	bootstrap_node.js:606
NativeModule.require	@	bootstrap_node.js:550
(anonymous)	@	net.js:45
(anonymous)	@	net.js:1730
NativeModule.compile	@	bootstrap_node.js:606
NativeModule.require	@	bootstrap_node.js:550
(anonymous)	@	internal/child_process.js:6
(anonymous)	@	internal/child_process.js:936
NativeModule.compile	@	bootstrap_node.js:606
NativeModule.require	@	bootstrap_node.js:550
(anonymous)	@	child_process.js:35
(anonymous)	@	child_process.js:685
NativeModule.compile	@	bootstrap_node.js:606
NativeModule.require	@	bootstrap_node.js:550
(anonymous)	@	ELECTRON_ASAR.js:4
(anonymous)	@	ELECTRON_ASAR.js:703
(anonymous)	@	ELECTRON_ASAR.js:704
NativeModule.compile	@	bootstrap_node.js:606
NativeModule.require	@	bootstrap_node.js:550
(anonymous)	@	VM43:7
setupAsarSupport	@	bootstrap_node.js:619
startup	@	bootstrap_node.js:60
(anonymous)	@	bootstrap_node.js:622

Uncaught ReferenceError: require is not defined
    at (index):1
(anonymous) @ (index):1
renderer.js:1 Uncaught ReferenceError: module is not defined
    at renderer.js:1
(anonymous) @ renderer.js:1
```

**To Reproduce**
First create a simple Electron project, then disable all network adapters or unplug the network cable, and finally start the project.

**Comment by haykerman** [comment] 2018-07-24 08:56
@1772844816 , have you done npm install before disabling all network adapters or unplug the network cable?

**Comment by 1772844816** [comment] 2018-07-24 09:23
@haykerman Yes, all the npm installation has been completed, and the project can run normally if the network cable is plugged in.

**Comment by Neil-Pan** [comment] 2018-07-24 18:17
I have the same problem. Have you solved it yet?

**Comment by aister** [comment] 2018-08-16 17:32
I encounter this exact problem on my electron app, except that it doesn't even go to index.js. Just disconnect from the internet is enough for the error to pop up for me, while normal non-electron node app works perfectly fine so no I don't think it's node's problem.

Also, according to the above issue, it was supposed to be fixed in node 9, however in my case it wasn't even when I update it to node 10.8

**Comment by haykerman** [comment] 2018-08-16 17:37
@aister,
I am not sure electron depends on your local version of node. It comes with it's own version prebuilt.

**Comment by aister** [comment] 2018-08-16 18:43
@haykerman in that case, then the latest version of electron didn't solve the problem

**Comment by jrobeson** [comment] 2018-08-16 20:37
@aister : latest which: stable or beta?

**Comment by aister** [comment] 2018-08-17 11:28
updating to beta fixed the problem for me, still it's weird how latest works for some and not for others

**Comment by jrobeson** [comment] 2018-08-17 21:34
this isn't the only open ticket for this issue.  Some of the other ones might have more detail.

**Comment by Neil-Pan** [comment] 2018-08-21 07:54
After configuring DNS and restart computer,then it works well.

**Comment by Xashyar** [comment] 2018-11-28 23:10
this seems to be resolved in 3.0.9 as in:
https://github.com/signalapp/Signal-Desktop/issues/2786

**Comment by sofianguy** [comment] 2019-08-09 00:15
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by Xashyar** [comment] 2019-08-09 12:04
> If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

Hey @sofianguy  
I'm currently using Electron 4.2.2, on [Signal-Desktop](https://github.com/signalapp/Signal-Desktop), and the issue has been unnoticed since Electron 3.0.9

**Comment by sofianguy** [comment] 2019-08-19 20:51
reported as fixed

**Closed by sofianguy** 2019-08-19 20:51 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
