### ISSUE TITLE
GN Build Possibilities and Tradeoffs (Chrome 54)

### ISSUE THREAD

**Issue by groundwater** [electron/electron#7940] opened 2016-11-11 08:16 UTC
After talking with @zcbenz and @bridiver about updating to Chrome 54, I wanted to summarize the discussion here.

Discuss in the [#chrome-54-update](https://atomio.slack.com/archives/chrome-54-update) room

# Problem

- chrome 54 and above no longer use *gyp* but *gn*
- Under gn, there is no way to have v8 build as a standalone static library. This is because v8 and other intermediate targets used to build `chrome.exe` are `source_set` [targets in chrome's gn files](https://goo.gl/VM4xOk). These are like virtual targets, and only object (`.o`) files are ever generated for them.
  - i.e. [libcc](https://github.com/electron/libchromiumcontent) does not contain any `v8.{a,lib}` files in the generated `out/static` directory.
- both electron (by way of chromium) and node.js need v8
- we want to avoid electron developers from having to build chromium themselves (this takes many hours on most machines)

# Solutions

Each of these will be listed for completeness. If you have another solution, we can add it. Pros and cons will follow.

## Build electron with *gn* and have it depend on the v8 `source_set` target

- This would require developers to build chromium when building electron. This would take a loooooong time on most laptops.

## Modify the *gn* binary to treat `source_set(...)` like `static_library(...)`

- This would require a modified version of *gn*

## Pre-process the `BUILD.gn` files

- swap `source_set` for `static_library` in *gn* files for static builds

# Refs

- #7909

**Comment by bridiver** [comment] 2016-11-11 15:21
the issue isn't just build time, you also can't have v8 in both the node shared lib and the final electron target because you will get two copies of the v8 singleton. I've been experimenting with using `set_sources_assignment_filter(["*"])` in the v8 source sets and I'm making some progress, but no working solution yet

**Comment by bridiver** [comment] 2016-11-11 17:57
there is still an easy way to build v8 as a static lib because it still has a gyn file and that's what I used to build the v8 libs for node. `set_sources_assignment_filter(["*"])` worked to keep node out of the chromium targets, but I'm hoping that I can use `set_defaults` or similar instead of patching the v8 BUILD.gn to add them all

**Comment by zcbenz** [comment] 2016-11-16 08:18
@bridiver We still want to build Electron with prebuilt binaries of libchromiumcontent, instead of building Electron as part of Chromium, so only patching V8 is probably not enough, since many other targets in Chromium have also been converted to `source_set`.

**Comment by zcbenz** [comment] 2017-05-31 07:29
Closing this since current build workflow works quite good.

**Closed by zcbenz** 2017-05-31 07:29 UTC
Labels: discussion

**Comment by nornagon** [comment] 2018-04-02 21:38
I'm confused, it looks like v8 has had an option to build as static libraries since Nov 2016? https://chromium.googlesource.com/v8/v8/+/1f74f551d0dc7404e16a20811553bae558687e82

There's also been a more recent change (Nov 2017) to support building a monolithic static library: https://chromium.googlesource.com/v8/v8/+/925ed598e338df20afdcfb8f49bff8beedae0359
