### ISSUE TITLE
When I use unmaximize on mousedown event, not working

### ISSUE THREAD

**Issue by MyCupOfTeaOo** [electron/electron#24759] opened 2020-07-28 08:36 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 9.1.1
* **Operating System:**
  * windows 10 (os version: 19041,421)

### Expected Behavior

```js
function unmaximize() {
  const win = require("electron").remote.getCurrentWindow()
  win.unmaximize()
  console.log("mousedown!")
}

document.querySelector("#click").addEventListener("mousedown", unmaximize)
```
I think it should quit to maximize

### Actual Behavior

not happend
but when i use click event, everything is normal

### To Reproduce

https://github.com/MyCupOfTeaOo/electron-mousedown-bug
```sh
$ git clone git@github.com:MyCupOfTeaOo/electron-mousedown-bug.git
$ npm install
$ npm start
```
click button

**Comment by aryanshridhar** [comment] 2020-07-28 12:14
Hi , It's working perfectly fine for me in <code>Ubuntu 18.08 x64</code> .

Try changing <code>win.unmaximize()</code> to <code>win.restore()</code> as mentioned <a href = 'https://stackoverflow.com/questions/43173985/electron-win-unmaximize-not-working'>here</a> .

**Comment by ckerr** [comment] 2020-07-28 16:56
When I use Electron 9.1.1, @MyCupOfTeaOo's code reproduces the bug for me on Windows 10 but not on Ubuntu 20.04.

**Comment by MyCupOfTeaOo** [comment] 2020-07-29 01:11
> Hi , It's working perfectly fine for me in `Ubuntu 18.04 x64` .
> 
> Try changing `win.unmaximize()` to `win.restore()` as mentioned [here](https://stackoverflow.com/questions/43173985/electron-win-unmaximize-not-working) .

I tried it, it still doesn't work on win10

**Comment by mlaurencin** [comment] 2021-05-10 23:24
@MyCupOfTeaOo Unfortunately this might just be due to how messages are handled upstream. Does adding a 1s timeout like in [this gist](https://gist.github.com/mlaurencin/aa471eea5e6faba403049e5d242f7998) work for you? If so, this might be the only viable workaround at the moment.

**Comment by MyCupOfTeaOo** [comment] 2021-05-14 06:36
> @MyCupOfTeaOo Unfortunately this might just be due to how messages are handled upstream. Does adding a 1s timeout like in [this gist](https://gist.github.com/mlaurencin/aa471eea5e6faba403049e5d242f7998) work for you? If so, this might be the only viable workaround at the moment.

This is indeed feasible, I am now doing so,thanks

**Comment by nornagon** [comment] 2021-07-14 21:50
Closing this as it seems the problem is resolved.

**Closed by nornagon** 2021-07-14 21:50 UTC
Labels: 9-x-y, platform/windows, status/confirmed
