### ISSUE TITLE
Clipboard.readImage() not working with Windows Explorer

### ISSUE THREAD

**Issue by redhotbeani** [electron/electron#7778] opened 2016-10-27 21:04 UTC
- Electron version: 1.4.4
- Operating system: Windows 10

Scenario:
I want to paste a copied image in my Electron app. But when I copy an image in Windows Explorer (png or jpg) and try to retrieve it from Clipboard, Clipboard.readImage() returns an empty NativeImage Object.

Based on the docs, I assumed it would work with all operating systems:
http://electron.atom.io/docs/api/clipboard/#clipboardreadimagetype

The same code is working fine in macOS. But the majority of our customers are using Windows.

**Comment by redhotbeani** [comment] 2016-10-28 12:01
Note: when I copy an image inside a Windows app, like Windows Photos, Clipboard.readImage() returns usable NativeImage Object. But when I select an image in Windows Explorer and copy it, clipboard.readImage() is empty.

**Comment by zcbenz** [comment] 2016-11-16 01:43
When you copy an image in Windows Explorer, you are copying the file instead of copying the contents of image.

This is a duplicate of #2244.

**Closed by zcbenz** 2016-11-16 01:43 UTC
Labels: bug, clipboard, windows

**Comment by saikksub** [comment] 2018-08-22 07:44
Hello @redhotbeani 

Did you find any solution for this?

**Comment by pangu663** [comment] 2019-09-25 03:14
windows用不了解决了吗

**Comment by Oleg1983** [comment] 2020-08-27 17:59
This problem exist on Electron 9. Why this issue was closed without fix ?

**Comment by AkshayCloudAnalogy** [comment] 2020-10-15 15:37
Any solution for this?

**Comment by chenendian** [comment] 2020-10-19 07:33
有什么解决办法吗？
