### ISSUE TITLE
How can I get the source app when handle `open-url` event?

### ISSUE THREAD

**Issue by m01i0ng** [electron/electron#30906] opened 2021-09-10 07:23 UTC
As https://www.electronjs.org/docs/api/app#事件-open-url-macos described, only `url` passed as argument.
But how can I do if I want to get source Application, example:

If I open https://github.com from iTerm2

```js
app.on('open-url', (e, url, source) => {
	console.log(`open ${url}, from ${source}`)
	// open https://github.com, from iTerm2
})
```

Is there a way or it hasn't been achieved?

**Comment by miniak** [comment] 2021-09-10 15:48
Thanks for taking the time to contribute!

We noticed that this is a duplicate of [Issue URL]. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by miniak** 2021-09-10 15:48 UTC

**Comment by miniak** [comment] 2021-09-10 20:12
It looks like it's not possible to get the app invoking the URL unfortunately.

**Comment by m01i0ng** [comment] 2021-09-13 00:38
@miniak Any plan about it?

**Comment by miniak** [comment] 2021-10-03 02:14
@m01i0ng there is no plan as I mentioned that I don’t think it’s possible to do it.
