### ISSUE TITLE
Could devtools of webview tag  be opened in a webview not a new window?

### ISSUE THREAD

**Issue by JasonFang93** [electron/electron#10055] opened 2017-07-18 13:06 UTC
i find someone else have mentioned the issue previously, but the feature couldn't be realized because of Chromium, now it might be realized probably, and i find that nw.js has supported this, therefore, is my profound hope that the feature will be supported in the future~ :pray:  :pray:  :pray:

**Comment by MarshallOfSound** [comment] 2017-07-18 18:21
It's not currently possible.  Duplicate of #3177

**Closed by MarshallOfSound** 2017-07-18 18:21 UTC
