### ISSUE TITLE
[Bug]: Failed to get fd for plane, Failed to export buffer to dma_buf

### ISSUE THREAD

**Issue by amiria703** [electron/electron#41082] opened 2024-01-23 14:49 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.4

### What operating system are you using?

Other Linux

### Operating System Version

ArchLinux
AMD RS880 Radeon HD 4250 (It's an iGPU and doesn't support vulkan)

### What arch are you using?

x64

### Expected Behavior

Create an electron window and just work!

### Actual Behavior

```
[27745:0123/181227.968858:ERROR:gbm_wrapper.cc(75)] Failed to get fd for plane.: No such file or directory (2)
[27745:0123/181227.970367:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:101)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:493)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:379)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:301)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:556)

[27745:0123/181427.556458:ERROR:gl_display.cc(515)] EGL Driver message (Error) eglCreateContext: Requested GLES version (3.1) is greater than max supported (3, 0).
Warning: eglCreateContext failed with EGL_BAD_ATTRIBUTE
    at CheckEGL (../../third_party/dawn/src/dawn/native/opengl/UtilsEGL.cpp:84)
    at Create (../../third_party/dawn/src/dawn/native/opengl/ContextEGL.cpp:101)
    at Create (../../third_party/dawn/src/dawn/native/opengl/PhysicalDeviceGL.cpp:110)
```

### Additional Information

Recently I have this problem with electron (maybe new versions?) Today tried to create a new project using electron-nuxt and same thing happened.

**Comment by ckerr** [comment] 2024-01-24 02:34
Appears to be a duplicate of https://github.com/electron/electron/issues/38189?

**Comment by codebytere** [comment] 2024-02-06 22:09
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2024-02-06 22:09 UTC
Labels: bug :beetle:, blocked/need-repro, 28-x-y

**Comment by frame430** [comment] 2024-05-31 05:44
I meet the same problem when I run the start guide example.

![image](https://github.com/electron/electron/assets/42229413/a53cfd92-4aaa-4bb9-be96-bc22e6cdeba9)

**Comment by Johng117** [comment] 2025-03-09 19:04
I am experiencing this issue too (identical to the screenshot in frame430's comment). There is also a delay, but that may be my raspberry pi.
