### ISSUE TITLE
Tray#displayBalloon `icon` parameter does not work

### ISSUE THREAD

**Issue by mysticatea** [electron/electron#10769] opened 2017-10-12 08:38 UTC
* Electron version: 1.7.9
* Operating system: Windows 7 Pro SP1 (64 bits)

### Expected behavior

With the following code, Electron shows a balloon like ![image](https://user-images.githubusercontent.com/1937871/31486697-40be3556-af73-11e7-962f-677e88722bb3.png)

```js
    const tray = new Tray(ICON_PATH)
    tray.displayBalloon({
        icon: ICON_PATH,
        title: "Hello",
        content: "Icon test."
    })
```

### Actual behavior

Electron does not show any balloon.

### How to reproduce

1. `git clone https://github.com/mysticatea/electron-tray-test.git`
2. `cd electron-tray-test`
3. `npm install`
4. `npm run test:none` ... It works if the `icon` parameter is nothing.
5. `npm run test:string` ... It does not work if the `icon` parameter is a string. It showed the tray icon, but does not show the balloon.
6. `npm run test:image` ... It does not work if the `icon` parameter is a NativeImage instance. It showed the tray icon, but does not show the balloon.

----

A side note, The document of `Tray#displayBalloon` says `title` and `content` are optional, but it's wrong.

https://electron.atom.io/docs/api/tray/#traydisplayballoonoptions-windows

**Comment by robinwassen** [comment] 2017-10-26 18:40
I can reproduce this issue on Windows 10 Fall Creators Update.

If I replace the `.ico` image with a `.png` image it works as intended.

**Comment by insideGen** [comment] 2017-11-15 18:04
https://github.com/electron/electron/issues/5844#issuecomment-344664016

**Comment by codebytere** [comment] 2018-09-24 05:35
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 05:35 UTC
Labels: bug :beetle:, component/tray, platform/windows, version/1.7.x
