### ISSUE TITLE
window.print() causes Electron to crash on Windows 10

### ISSUE THREAD

**Issue by mUtterberg** [electron/electron#19590] opened 2019-08-02 12:00 UTC
#Issue Details

* **Electron Version:**
5.0.8 and 6.0.0 (but not 5.0.1 or 4.0.0)
* **Operating System:**
Windows 10
* **Last Known Working Electron version:**
5.0.1

### Expected Behavior
App would continue to run after window.print()

### Actual Behavior
Print job sends to printer, but Electron crashes and window disappears.

### To Reproduce
[Repo Link](https://github.com/mUtterberg/bug_test)

```sh
$ git clone https://github.com/mUtterberg/bug_test
$ npm install
$ .\node_modules\electron\dist\electron.exe .
```
Printing window in version 5.0.8 (repo default) or 6.0.0 will trigger Electron crash.

It appears to have been fixed in a previous version, as seen in #15188, but the bug has returned in recent versions (listed above).

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Comment by codebytere** [comment] 2019-08-02 21:52
Duplicate of https://github.com/electron/electron/issues/19539.

**Closed by codebytere** 2019-08-02 21:52 UTC
