### ISSUE TITLE
[RS5] Electron apps and loopback adapter

### ISSUE THREAD

**Issue by sashar2** [electron/electron#14757] opened 2018-09-21 15:30 UTC
**Electron version:** 1.7.8
**Operating system:** Windows 10 RS5 17763 (x86, x64)

Electron based applications doesn’t work on latest Windows 10 RS5 builds without internet connection, startup fails on require('child_process').spawn(). Its reproduced on the our application and Microsoft Visual Studio Code too. According to our preliminary research it occurs when electron try to use loopback address for communication by IPC between processes. We assume that this is due to the lack of loopback adapter in recent RS5 builds.

![image](https://user-images.githubusercontent.com/2525501/45889070-2cf28400-bdc8-11e8-9131-60182505b2f9.png)

**Repro steps:**
1. Install the Visual Studio Code.
2. Disable internet connection (plug off **all** network cables).
3. Try to start VS Code. 

**Actual:** VSCode tries to start processes, but immediately shutdown.
**Expected:** VSCode started successfully.

**Workaround:** [install Microsoft loopback adapter](https://social.technet.microsoft.com/Forums/en-US/a4e5c780-7920-49e0-908f-aee0987ad41b/how-to-install-microsoft-loopback-adapter-on-windows-10?forum=win10itpronetworking)

**Comment by bpasero** [comment] 2018-09-22 05:40
@sashar2 can you reproduce with Electron 3.0.x? We have a version of Code around: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by sashar2** [comment] 2018-09-24 08:04
> @sashar2 can you reproduce with Electron 3.0.x? We have a version of Code around: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)

@bpasero, thank you, It seems the bug is fixed in Electron 3.0.

**Comment by sofianguy** [comment] 2019-01-07 22:52
Closing due to reports that it is fixed in Electron 3.0.x

**Closed by sofianguy** 2019-01-07 22:52 UTC
Labels: bug :beetle:, platform/windows, version/1.7.x
