### ISSUE TITLE
Hard crash when calling webContents.removeWorkSpace or addWorkSpace 

### ISSUE THREAD

**Issue by schmod** [electron/electron#6616] opened 2016-07-26 15:33 UTC
* Electron version: 1.3.0
* Operating system: OS X 10.11.6

[OS X Crash report](https://gist.github.com/schmod/654df9ae9f37f82848f8891359bf5e60)

Electron hard-crashes when running the following snippet:

```
webContents.isDevToolsOpened(); // true

var wsd = "/Users/schmod/path/to/a/directory";

try {
    webContents.removeWorkSpace( wsd );
} catch (e) {}

webContents.addWorkSpace( wsd );
```

![screenshot 2016-07-25 11 27 01](https://cloud.githubusercontent.com/assets/1102667/17144299/443d130c-5324-11e6-995d-bd9fd4179997.png)

Adding a folder to the workspace via the UI also causes a crash.

See also: https://github.com/s-a/iron-node/issues/114

**Comment by kevinsawicki** [comment] 2016-07-26 17:05
This is a duplicate of #6610 which has a fix in the works in #6613

**Closed by kevinsawicki** 2016-07-26 17:05 UTC
Labels: crash
