### ISSUE TITLE
speechSynthesis.getVoices() returns an empty array

### ISSUE THREAD

**Issue by whizyrel** [electron/electron#22844] opened 2020-03-26 05:41 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  ^8.0.2

* **Operating System:**
  *  Ubuntu 18.04 x64

* **Last Known Working Electron version:**
  *  Not ^4.x.y, I never tried below

### Expected Behavior
 An array of voices is expected

### Actual Behavior
 speechSynthesis.getVoices() returns an empty array always with or without the internet

### To Reproduce

 
Here fiddle link: https://gist.github.com/cfe130888196196153f5240e30d8e4b5

 
```sh
$ git clone https://github.com/whizyrel/app-bible -b electron-devel
$ npm install
$ electron .
```

### Screenshots

![Screenshot from 2020-04-01 06-57-30](https://user-images.githubusercontent.com/38155356/78746232-3289cd80-795e-11ea-9e21-96fdfc9d48ee.png)

### Additional Information

With or without the internet speechSynthesis.getVoices() returns an empty array. In the browser, it returns an array of SpeechSynthesisVoice using chrome when the internet is connected.
Further info:
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/getVoices

**Comment by codebytere** [comment] 2020-03-31 04:05
@whizyrel in order to properly triage this, we'll need an example that makes it clear it's an Electron-specific issue; an entire app is too unwieldy for us to proceed with.

Additionally, can you please clarify:

> speechSynthesis.getVoices() returns an enjoy area always w/ the internet

? I'm not sure if you mean empty array, or something else.

**Comment by whizyrel** [comment] 2020-04-08 05:03
> @whizyrel in order to properly triage this, we'll need an example that makes it clear it's an Electron-specific issue; an entire app is too unwieldy for us to proceed with.
> 
> Additionally, can you please clarify:
> 
> > speechSynthesis.getVoices() returns an enjoy area always w/ the internet
> 
> ? I'm not sure if you mean empty array, or something else. This issue will be closed if there is no response within 10 days.

Hello, check it again. It should have enough info from the screenshot for a triage😏

**Comment by codebytere** [comment] 2020-04-09 16:01
@whizyrel:

> in order to properly triage this, we'll need an example that makes it clear it's an Electron-specific issue; an entire app is too unwieldy for us to proceed with.

This has not yet been addressed, and we cannot proceed until it is.

**Comment by whizyrel** [comment] 2020-04-12 05:43
> @whizyrel:
> 
> > in order to properly triage this, we'll need an example that makes it clear it's an Electron-specific issue; an entire app is too unwieldy for us to proceed with.
> 
> This has not yet been addressed, and we cannot proceed until it is.

Please find fiddle link in the submitted issue. Thank you.

**Comment by whizyrel** [comment] 2020-04-20 11:36
Good day and keep up the good work.
Do you mind filling me in on what I should expect, possible solutions or something... Thank you

**Comment by nornagon** [comment] 2020-04-20 18:55
Seems like this has never worked (I tried v4–v9) on macOS, so this isn't a regression.

https://github.com/electron/electron/pull/14070 seems relevant.

**Comment by codebytere** [comment] 2020-04-20 18:56
Also reproducible on macOS - i'll try to take a look soon.

**Comment by ahallicks** [comment] 2020-04-22 09:38
I don't know if this is the case but this worked for me:

I think the reason that `getVoices()` returns an empty array is because they are not there by default. BUT, the following works for me:

```
const speech = window.speechSynthesis;
if(speech.onvoiceschanged !== undefined)
{

	speech.onvoiceschanged = () => this.populateVoiceList();

}

**Comment by whizyrel** [comment] 2020-05-01 02:19
> Also reproducible on macOS - i'll try to take a look soon.

Thank you, looking forward to it

**Comment by LoLei** [comment] 2020-05-29 14:19
I'm getting the same on Linux Electron 9.0.0.

I have installed `speech-dispatcher` and `espeak-ng`.
I am starting Electron with `app.commandLine.appendSwitch('enable-speech-dispatcher')`.

Calling `window.speechSynthesis.getVoices()` at any time after loading the page, returns an empty array.

In Firefox, it returns
```
Array(109) [ SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, … ]
```

However, the default voice can still be used in Electron. Which is unfortunately in Afrikaans, since it is the first voice in the list.

So *using* a voice from within Electron is possible, it uses the default voice, but *retrieving* a list of voices is not possible, and therefore setting the voice to a new one is not possible either. 

It can be tested by using this website: https://mdn.github.io/web-speech-api/speak-easy-synthesis/
With a slight modification to get arround a null reference due to the empty list.

I can confirm though that this also happens in Chromium (83.0.4103.61) (`chromium --enable-speech-dispatcher`) itself, although Chromium reports:
>You are using an unsupported command-line flag: `--enable-speech-dispatcher`. Stability and security will suffer.

However, I also found out that if you let Chromium sit for a long while, and try `window.speechSynthesis.getVoices()` again, it *will* load the full array. Or if you reload the page. Sometimes. It does not seem deterministic.
As pointed out [here](https://stackoverflow.com/q/21513706/4644044), it seem like the `speechSynthesis` module itself is loaded some time after the page is loaded. This is a distinct event from the `voiceschanged` event, which I've tried incorporating in Chromium to no avail. In Firefox, it works fine.

I can get it working in Electron relatively consistently by starting the Electron app from the command line, then reloading the page manually. Once the initial reload is done, the voices are ready as well.

Another difference between Firefox and Electron/Chromium:
In Firefox the voices have their languages set properly in the `lang` property.
E.g.
```
SpeechSynthesisVoice
default: false
lang: "en-GB"
localService: false
name: "English (Scotland)"
voiceURI: "urn:moz-tts:speechd:English%20(Scotland)?en-GB"
```

And in Chromium the `lang` property is missing and the name contains the local synth software for some reason.
```
SpeechSynthesisVoice
default: true
lang: ""
localService: true
name: "Afrikaans espeak-ng"
voiceURI: "Afrikaans espeak-ng"
```

So all I can conclude is that something is messed up.

I have looked at https://github.com/electron/electron/issues/586, https://github.com/electron/electron/issues/11585.

**Comment by whizyrel** [comment] 2020-07-30 15:34
Good day, #14070 applies to windows OS

**Comment by whizyrel** [comment] 2020-07-30 15:34
> I'm getting the same on Linux Electron 9.0.0.
> 
> I have installed `speech-dispatcher` and `espeak-ng`.
> I am starting Electron with `app.commandLine.appendSwitch('enable-speech-dispatcher')`.
> 
> Calling `window.speechSynthesis.getVoices()` at any time after first loading the page, returns an empty array.
> 
> In Firefox, it returns
> 
> ```
> Array(109) [ SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, SpeechSynthesisVoice, … ]
> ```
> 
> However, the default voice can still be used in Electron. Which is unfortunately in Afrikaans, since it is the first voice in the list.
> 
> So _using_ a voice from within Electron is possible, it uses the default voice, but _retrieving_ a list of voices is not possible, and therefore setting the voice to a new one is not possible either.
> 
> It can be tested by using this website: https://mdn.github.io/web-speech-api/speak-easy-synthesis/
> With a slight modification to get arround a null reference due to the empty list.
> 
> I can confirm though that this also happens in Chromium (83.0.4103.61) (`chromium --enable-speech-dispatcher`) itself, although Chromium reports:
> 
> > You are using an unsupported command-line flag: `--enable-speech-dispatcher`. Stability and security will suffer.
> 
> However, I also found out that if you let Chromium sit for a long while, and try `window.speechSynthesis.getVoices()` again, it _will_ load the full array. Or if you reload the page. Sometimes. It does not seem deterministic.
> As pointed out [here](https://stackoverflow.com/q/21513706/4644044), it seem like the `speechSynthesis` module itself is loaded some time after the page is loaded. This is a distinct event from the `voiceschanged` event, which I've tried incorporating in Chromium to no avail. In Firefox, it works fine.
> 
> I can get it working in Electron relatively consistently by starting the Electron app from the command line, then reloading the page manually. Once the initial reload is done, the voices are ready as well.
> 
> Another difference between Firefox and Electron/Chromium:
> In Firefox the voices have their languages set properly in the `lang` property.
> E.g.
> 
> ```
> SpeechSynthesisVoice
> default: false
> lang: "en-GB"
> localService: false
> name: "English (Scotland)"
> voiceURI: "urn:moz-tts:speechd:English%20(Scotland)?en-GB"
> ```
> 
> And in Chromium the `lang` property is missing and the name contains the local synth software for some reason.
> 
> ```
> SpeechSynthesisVoice
> default: true
> lang: ""
> localService: true
> name: "Afrikaans espeak-ng"
> voiceURI: "Afrikaans espeak-ng"
> ```
> 
> So all I can conclude is that something is messed up.
> 
> I have looked at #586, #11585.
> 
> #### EDIT
> Turns out it doesn't solely depend on a reload. The nonworking `window.speechSynthesis.getVoices()` also needs to be called once before the reload.
> 
> So what I ended up doing, in `index.html`:
> 
> 1. On page load: `window.speechSynthesis.getVoices()` // nonworking but necessary
> 2. Reload page
> 3. Enjoy working `window.speechSynthesis.getVoices()`
> 
> Of course also with setting a flag to refresh the page only once.

I am looking into this

**Comment by whizyrel** [comment] 2020-07-31 07:35
@LoLei You are right. List of voices are returned after manually reloading the page but this does not fit angular at all.
So what i did was load from URL the first time and when it resolves, reload manually and load from URL again. Well, it may not be smart, but it looks fair and is not what i want but I would take it.
This is a work around for anyone that might have this issue again, thanks @LoLei.
I guess this issue can be closed now, if there is no activity in a long time, I would close it.

summarily,
- [x] win.minimize()
- [x] win.hide()
- [x] Load from URL
- [x] reload page
- [x] Load from URL again
- [x] show window
```js
win.loadURL(
   url.format({...})
).then(() => {
   win.reload();
   win.loadURL(
      url.format({...})
   ).then(() => win.show());
);
```

Thanks everyone.

**Comment by codebytere** [comment] 2020-08-26 20:49
Closing as latest comments indicate this is resolved.

**Closed** 2020-08-26 20:49 UTC
Labels: 8-x-y, bug :beetle:

**Comment by LoLei** [comment] 2020-08-27 06:54
@codebytere We found a cumbersome workaround, the underlying issue is still there.

**Comment by caarmen** [comment] 2021-02-07 14:14
I also notice that `getVoices()` returns an empty list in electron, on Ubuntu 20.04, until I force a manual reload. I haven't figured out yet how to manage this reload programmatically (I don't yet understand the [comment](https://github.com/electron/electron/issues/22844#issuecomment-666980901) describing that). 

Is there no way to change anything in electron so we don't need this workaround?

**Comment by LoLei** [comment] 2021-02-07 16:04
@caarmen: In case this helps, I've described in a [comment](https://github.com/electron/electron/issues/22844#issuecomment-635997898) above how I use a workaround that doesn't rely on any framework like Angular:
>So what I ended up doing, in index.html:
>
>1. On page load: window.speechSynthesis.getVoices() // nonworking but necessary
>2. Reload page
>3. Enjoy working window.speechSynthesis.getVoices()
>
>Of course also with setting a flag to refresh the page only once.

Something like this:
```js
window.addEventListener("load", function()
{
  window.speechSynthesis.getVoices();
  if (window.localStorage)
  {
    if (!localStorage.getItem('refresh'))
    {
      localStorage['refresh'] = true;
      location.reload(true);
    }  
    else
    {
      localStorage.removeItem('refresh');
    }
  }
});
```

**Comment by caarmen** [comment] 2021-02-07 19:04
> @caarmen: In case this helps, I've described in a [comment](https://github.com/electron/electron/issues/22844#issuecomment-635997898) above how I use a workaround that doesn't rely on any framework like Angular:

Awesome, this works! Thanks! 🙇‍♀️

**Comment by Victor-Nikliaiev** [comment] 2021-05-20 01:33
> I don't know if this is the case but this worked for me.
> 
> I think the reason that `getVoices()` returns an empty array is because they are not there by default. BUT, the following works for me:
> 
> ```
> const speech = window.speechSynthesis;
> if(speech.onvoiceschanged !== undefined)
> {
> 
> 	speech.onvoiceschanged = () => populateVoiceList();
> 
> }
> function populateVoiceList()
> {
> 	speech.getVoices(); // now should have an array of all voices
> }
> ```

Thanks, it works for me as well!

**Comment by mbuffa** [comment] 2024-07-26 09:22
Doubt this will help, but I think this is an upstream issue (chromium?).

I can reproduce it with a simple app calling `speechSynthesis.getVoices()` (building an Elixir LiveView app) in Arc and Edge (Windows).

Workaround providfed by @ahallicks works (thanks!). Event isn't triggered on eg. Firefox.

Calling `getVoices()` in a CHrome console always works for me, but never when loading some javascript.

Arc build info:
```
Build Info: 1.11.3.39079 (0000)
OS Version: 10.0.22631
User ID: WGA8sshmbvfPULuwq6KSlkGpm2z2
Chromium Engine Version 126.0.6478.183
```
