### ISSUE TITLE
Electron + PDFJS + Angular 6 - DataCloneError: Failed to execute 'postMessage' on 'Worker'

### ISSUE THREAD

**Issue by MateEke** [electron/electron#13416] opened 2018-06-25 14:59 UTC
* Electron Version: 2.0.3
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: ?

**Expected Behavior**
PDF gets displayed

**Actual behavior**
```
ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Worker': TypeError: https.request is not a function could not be cloned.
Error: Failed to execute 'postMessage' on 'Worker': TypeError: https.request is not a function could not be cloned.
```

**To Reproduce**
Create electron app with PDFJS and Angular 6

**Additional Information**
In google Chrome everything works fine.

VadimDez/ng2-pdf-viewer#326
mozilla/pdf.js#9840
angular/angular-cli#11368

**Comment by timfish** [comment] 2018-06-27 10:55
`pdfjs-dist@1.8.619` works fine for us in Electron 2.0.3.

As you've filed issues elsewhere, it looks like you're not even sure if this is an Electron issue. If you find that it is, can you provide a minimal sample that reproduces the bug?

**Comment by sofianguy** [comment] 2018-07-06 03:56
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2018-07-06 03:56 UTC
Labels: blocked/needs-repro, bug :beetle:, platform/windows, version/2.0.x

**Comment by giridharkannan** [comment] 2018-09-08 05:45
The issue is not what the error message says, it's actually something else. Since error handling faced another exception while reporting, things got messed up.

The reason for the issue is, Http module misses "require" method to be precise both Http and Https modules are empty.

When using pdf.js in Chrome browser, it uses PDFFetchStream to read data whereas when using pdf.js in Electron it uses PDFNodeStream. When in Electron, to resolve Http request PDFNodeStream uses Node's Http module ( require('http') ), somehow the http variable got overwritten.

Moving Http import inside PDFNodeStreamFullReader and PDFNodeStreamRangeReader solves the issue that we face.

I don't know why http variable got overwritten or who is responsible for this issue as am very new to frontend development but it would be helpful if someone helps us out to resolve this problem.

**Comment by HamedSalameh** [comment] 2019-03-03 14:54
Hi @giridharkannan ,
I am facing the same issue & I think your solution might help. can you please help me understand what should I do? I could not understand what needs to be done here:

> Moving Http import inside PDFNodeStreamFullReader and PDFNodeStreamRangeReader solves the issue that we face.

Thanks

**Comment by giridharkannan** [comment] 2019-03-03 16:22
@HamedSalameh 
It seems 'am using a much simpler workaround than the suggested one

Before calling `getDocument` method try calling the below code snippet (in case if it's electron)

`pdfjsDisplayAPI.setPDFNetworkStreamFactory((params) => {
    return new PDFFetchStream(params);
});`
