### ISSUE TITLE
Electron v33.0.0 > Webview Devtools saves zero-byte .HAR file

### ISSUE THREAD

**Issue by Nashorn** [electron/electron#44316] opened 2024-10-18 14:38 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

14.7

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

v32

### Expected Behavior

I upgraded from v32 of electron to v33.0.0 and the devtools that i am opening for the webview saves a zer-byte .har file. it's now empty.

### Actual Behavior

I upgraded from v32 of electron to v33.0.0 and the devtools that i am opening for the webview saves a zer-byte .har file. it's now empty.

**Comment by codebytere** [comment] 2024-10-29 20:39
I can't reproduce this - loading https://github.com on 33 and clicking around then downloading as specified results in the following non-empty file:

![Image](https://github.com/user-attachments/assets/cd1ddc6f-9ac7-4b41-9014-28301d7b4029)

**Comment by codebytere** [comment] 2024-11-12 21:38
Closing for now then - happy to reopen if it recurs.

**Closed by codebytere** 2024-11-12 21:38 UTC
Labels: platform/macOS, bug :beetle:, 33-x-y
