### ISSUE TITLE
Electron 4.0 breaks interceptStreamProtocol.

### ISSUE THREAD

**Issue by burtonator** [electron/electron#16192] opened 2018-12-26 01:03 UTC
I reported this bug on the 3.x series and it was never addressed.

The community had a workaround by calling the callback via setTimeout.

https://github.com/electron/electron/issues/13519

... but now the workaround is dead in the 4.x.x series.

The devs NEED to take this seriously.  This just killed my app and if it's not fixed I might as well shut down the entire project.

I tried to refactor my code to call the callback without setTimeout and that doesn't fix the problem.  

Can someone from the Electron team prioritize this or let me know of a way to prioritize this.  This is **critical** for may app...

**Comment by burtonator** [comment] 2019-01-12 23:40
This is a pretty severe regression on 4.0... a main API should not simply stop working and it shouldn't take weeks to resolve. 

Is this API not tested?  How did the 4.0 release even happen?

It makes it hard to commit to Electron when major platform APIs simply don't work.

**Comment by groundwater** [comment] 2019-01-15 22:07
Hi @burtonator. We need to have a talk about your approach to the project, and people working on Electron.

Open source is tricky, and I understand that relying heavily on a project like Electron can be scary, frustrating, and confusing. We do not want to break anyones apps. None of the maintainers want that. We even run a program to help ensure we fix participating app's major issues during our beta cycle.

Despite that, the issue track is not a place for snide, snark, and comments belittling folks working to maintain a gigantic project.

Moving forward, I would recommend reading and following the advice in [Creators, contributors, and collaborators](https://github.community/t5/Studies-in-Community/Creators-contributors-and-collaborators/ba-p/234).

Just so we're clear, you are welcome to continue participating in the following ways:

1. submitting bug reports with enough detail to reproduce - ideally a [Fiddle](https://github.com/electron/fiddle) example
2. a new feature request with context
3. logistical questions that may not be covered in the docs (e.g. asking about release timelines in a polite way)

Including additional comments such as "How did the 4.0 release even happen" or "The devs NEED to take this seriously" are off-topic and will result in those issues being closed immediately.

_Please follow the next step exactly_

Let's all take a moment to digest the above. **Please do not interact with the project for 24-hours.** No comments, new issues, or pull-requests. After that, please look through your open issues and edit them to ensure they're _entirely_ on-topic, and we can continue the discussion here about the best way to engage going forward.

**Comment by ckerr** [comment] 2019-01-15 22:54
Other discussion aside, I'm closing this as a duplicate of #13519.

This is a procedural action & not intended as commentary on the rest of the discussion.

**Closed by ckerr** 2019-01-15 22:54 UTC

**Comment by burtonator** [comment] 2019-01-15 23:18
@groundwater 

Jacob.

I think there's a misunderstanding here.

I always treat people with respect - the way I would expect to be treated.  

There was no snide or underhanded comment on my part here and certainly not my intention at all.

I usually go out of my way to clarify my intentions just so that my thoughts are clear. In fact I think in another bug on the issue I literally went out of my way to thank the devs for all the hard work.

I just re-read my post and while my issue raised concern I don't think it goes anywhere near being snide or expressing any negative tone.

I also asked a few people on my end what their thoughts were and they agreed.

My tone was one of urgency and concern.  

Also, these issues tend to be very subjective.  For example how can you objectively say that something is snide?  How can I falsify it and say it is not snide?  

How can I express that a bug is deeply concerning to me and that it seriously negatively impacts my project without using those worse?

Again.  Wanted to make it clear that I appreciate ALL the hard work from the Electron team. 

As an external user of the APIs I'm trying to express severe concern in a platform regression and not sure how to do that without actually raising that concern.
