### ISSUE TITLE
`./script/bootstrap.py` stack trace on OS X 10.9.5

### ISSUE THREAD

**Issue by codekiln** [electron/electron#8690] opened 2017-02-15 18:49 UTC
* Electron version: v1.6.0-195-g0ac3969
* Operating system: OS X 10.9.5

### Expected behavior

`$ ./script/bootstrap.py --dev` should correctly bootstrap the source or give an appropriate error.

### Actual behavior

`bootstrap.py` fails on 10.9.5 / Mavericks when `./tools/mac/find_sdk.py` is unable to find `/Library/Developer/CommandLineTools/SDKs` which causes the script to fail with a stacktrace.
  
```
$ ./script/bootstrap.py --dev
Download Mantle       64733  [100.0%]
Download ReactiveCocoa      301942  [100.0%]
Download Squirrel      311396  [100.0%]
Traceback (most recent call last):
  File "./tools/mac/find_sdk.py", line 92, in <module>
    print main()
  File "./tools/mac/find_sdk.py", line 60, in main
    sdks = [re.findall('^MacOSX(10\.\d+)\.sdk$', s) for s in os.listdir(sdk_dir)]
OSError: [Errno 2] No such file or directory: '/Library/Developer/CommandLineTools/SDKs'
gyp: Call to 'python ./tools/mac/find_sdk.py 10.10' returned exit status 1 while in electron.gyp.

Traceback (most recent call last):
  File "./script/bootstrap.py", line 264, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 65, in main
    run_update(defines, args.msvs)
  File "./script/bootstrap.py", line 260, in run_update
    execute_stdout(args)
  File "/Users/pnore/dev/electron/script/lib/util.py", line 182, in execute_stdout
    execute(argv, env)
  File "/Users/pnore/dev/electron/script/lib/util.py", line 170, in execute
    raise e
subprocess.CalledProcessError: Command '['/usr/local/opt/python/bin/python2.7', '/Users/pnore/dev/electron/script/update.py']' returned non-zero exit status 1
```

### How to reproduce

See above. 

FYI: 
```
$ cat /Applications/Xcode.app/Contents/version.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildVersion</key>
	<string>11</string>
	<key>CFBundleShortVersionString</key>
	<string>6.2</string>
	<key>CFBundleVersion</key>
	<string>6776</string>
	<key>ProductBuildVersion</key>
	<string>6C131e</string>
	<key>ProjectName</key>
	<string>IDEFrameworks</string>
	<key>SourceVersion</key>
	<string>6776000000000000</string>
</dict>
</plist>
```

**Comment by kevinsawicki** [comment] 2017-02-16 19:39
> /Library/Developer/CommandLineTools/SDKs

@codekiln do you have the command line tools SDKs installed to a different location or not installed at all? Thanks.

**Comment by codekiln** [comment] 2017-02-16 21:04
I believe so ... 

```
$ ls /Library/Developer/CommandLineTools/usr/bin
BuildStrings       as                 dsymutil           git-upload-pack    llvm-profdata      rebase             svnsync
CpMac              asa                dwarfdump          gm4                lorder             redo_prebinding    svnversion
DeRez              bison              dyldinfo           gnumake            m4                 resolveLinks       unifdef
GetFileInfo        c++                flex               gperf              make               rpcgen             unifdefall
MergePef           c89                flex++             hdxml2manxml       mig                segedit            unwinddump
MvMac              c99                g++                headerdoc2html     mkdep              size               what
ResMerger          cc                 gatherheaderdoc    indent             nasm               strings            xml2man
Rez                clang              gcc                install_name_tool  ndisasm            strip              yacc
RezDet             clang++            gcov               ld                 nm                 svn
RezWack            cmpdylib           git                lex                nmedit             svnadmin
SetFile            codesign_allocate  git-cvsserver      libtool            otool              svndumpfilter
SplitForks         cpp                git-receive-pack   lipo               pagestuff          svnlook
UnRezWack          ctags              git-shell          lldb               projectInfo        svnrdump
ar                 ctf_insert         git-upload-archive llvm-cov           ranlib             svnserve

```

**Comment by kevinsawicki** [comment] 2017-02-22 16:21
@codekiln can you check for a folder named ` MacOSX.sdk` in `/Library/Developer/CommandLineTools`?

**Comment by codekiln** [comment] 2017-02-22 16:34
It's not there:

$ ls /Library/Developer/CommandLineTools
Library usr

**Comment by kevinsawicki** [comment] 2017-02-22 16:45
@codekiln can you run `xcodebuild -showsdks`?

**Comment by codekiln** [comment] 2017-02-22 19:40
This is an interesting result considering I actually do have Xcode ...

$ xcodebuild -showsdks
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer
directory '/Library/Developer/CommandLineTools' is a command line tools
instance

**Comment by kevinsawicki** [comment] 2017-02-22 19:50
> This is an interesting result considering I actually do have Xcode ...

Yeah, looks like something is missing or misconfigured on your machine, but I still think the error that `script/bootstrap.py` displayed could be more helpful so lets leave this issue open and provide a better error as a fix for this.

**Comment by kevinsawicki** [comment] 2017-02-22 21:13
@codekiln what version of Xcode do you have installed?

**Comment by zcbenz** [comment] 2017-06-06 07:44
I'm closing this since it s caused by misconfigured system, which we are not able to help with.

**Closed by zcbenz** 2017-06-06 07:44 UTC
Labels: component/build, platform/macOS, triage/bug
