### ISSUE TITLE
desktopCapturer: very poor frame rate on Mac OSX

### ISSUE THREAD

**Issue by demian85** [electron/electron#8278] opened 2016-12-23 19:04 UTC
* Electron version: 1.4.13
* Operating system: Mac OSX 10.12.2

I'm having serious issues using desktopCapturer API on Mac OSX. Works great on Linux.

I need to capture entire screen or specific window and attach audio stream also, so I'm using desktopCapturer without audio, passing selected source ID as option and using MediaStream/MediaSource/MediaRecorder API's to accomplish that.
Here is an example of what I'm doing:
```javascript
const opts = Object.assign({
  sourceId: null,
  width: screen.availWidth,
  height: screen.availHeight,
  frameRate: 25,
}, options);
const videoProps = {
  audio: false,
  video: {
    mandatory: {
      chromeMediaSource: 'desktop',
      chromeMediaSourceId: opts.sourceId,
      maxWidth: opts.width,
      maxHeight: opts.height,
      maxFrameRate: opts.frameRate,
    }
  }
};
const audioProps = {
  audio: true,
  video: false
};
return Promise.all([
  navigator.mediaDevices.getUserMedia(videoProps),
  navigator.mediaDevices.getUserMedia(audioProps)
])
.then(onStreamSuccess)
.catch((err) => {
  console.error(err);
  alert(`Unable to start recording: ${err.message}`);
});

function onStreamSuccess([videoStream, audioStream]) {
  const audioTrack = audioStream.getAudioTracks()[0];
  videoStream.addTrack(audioTrack);
  const mediaRecorder = new MediaRecorder(videoStream, recorderOptions);
  //...
}
```

On Linux, video stream & audio gets recorded as expected, encoded as webm using vp9/opus.
Testing on my new Mac, the result is a very poor video with serious lag. Audio works great, but actions on the screen are not being captured. It's like the frame rate is under 1fps.

Is there anything I can do? Is this a bug or am I doing something wrong?

Help is really appreciated, since I'm developing an app that heavily depends on this feature. 

Thank you.

EDIT: recording video from webcam works as expected, so somehow the source coming from desktopCapturer is having issues. Even tried this demo: https://www.webrtc-experiment.com/msr/video-recorder.html

**Comment by aredfox** [comment] 2016-12-25 08:53
@demian85 experiencing somewhat the same behaviour (see https://github.com/electron/electron/issues/8246). Where the desktopcapturer freezes the entire process and it's windows for a brief moment when calling getSources() - did you experience that as well. I'm having that issue on all three platforms though. 

The developers of KAP (https://github.com/wulkano/kap) also experienced performance issues they said (in https://github.com/wulkano/kap/issues/20) - and therefore implemented their own capturing logic on macOS, but unfortunately haven't worked on Windows or Linux tooling for the capturing process.

**Comment by demian85** [comment] 2016-12-25 20:15
Great to know I'm not the only one and there is a workaround for Mac OSX. I can keep using desktopCapturer API for Windows or Linux.
However, I wonder how Google Hangouts works, since it allows you to select screen to share and it works on Mac, am I right?
I know there is a Chrome API specifically for desktop capturing inside extensions, but I'm not sure if it's available in Electron and if there are any differences with the desktopCapturer API.

**Comment by demian85** [comment] 2016-12-27 13:43
Some feedback would be great, as I'm not sure if this bug needs to be reported for Chromium project instead :/

**Comment by hokein** [comment] 2016-12-27 19:36
@demian85 Can you run your sample on Chrome to verify whether it is a Chromium related issue?

**Comment by demian85** [comment] 2016-12-27 19:40
How can I test on Chrome if I'm using an electron API? You mean to try
using Chrome extension API?

**Comment by hokein** [comment] 2016-12-27 19:51
hmm,  the code snippet you pasted above doesn't use any electron APIs. There are two ways:

* If you are using `desktopCapturer.getSources()` to retrieve the sourceId, you can replace it with [chrome.desktopCapture](https://developer.chrome.com/extensions/desktopCapture) API, but you have to learn a bit more about chrome extension/apps development.
* You can modify you code getting rid of electron APIs, `sourceId` is not required for capturing the full screen, read the beginning paragraph in [doc](https://github.com/electron/electron/blob/master/docs/api/desktop-capturer.md).

**Comment by demian85** [comment] 2016-12-27 23:11
Well, it's too complicated to re-create a working example on Chrome, so I tried this demo: https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/#9281250928330272

It uses the same chrome API and it works great. Shared a single window source with a PC in the same network and stream plays great without stuttering.
So, is this a Chromium/Electron related bug?

**Comment by hokein** [comment] 2016-12-29 20:18
If the example works well on chrome, it is more likely an Electron bug.

However, I could not reproduce the poor frame rate on OS X 10.11.6. I tested the API with [`electron-screen-recorder`](https://github.com/hokein/electron-screen-recorder):
1. Record the desktop along with audio.
2. The video looks fine to me, as well as the saved `webm` file.

**Comment by demian85** [comment] 2016-12-29 21:39
Well, this is a bit disturbing... because your app works great for me!
Will need to further investigate the code because I cannot find any significant difference from my code and seems that I'm doing something wrong on my side...

**Comment by demian85** [comment] 2016-12-29 22:47
Okay, after saving my recorded video into a local file, it plays okay inside chrome. Seems that performance is not good when playing video inside video tag using MediaSource Extensions API... and only on Mac! 
Will be back with more details tomorrow...

**Comment by aredfox** [comment] 2016-12-30 04:49
hey all, what I can say is that whenever I call getSources() I have a freeze in the application that is unacceptable. All open windows and processes freeze when I call that function :/...

**Comment by demian85** [comment] 2016-12-30 12:27
Well, now I realize that the mouse cursor is not visible, either with your app or mine. This is a mess.
Should I report whatever the bug is in the chromium project?

**Comment by BrstDev123** [comment] 2017-01-02 07:51
Can you please help me that How can I create desktop application using electron. I have node js app which has been already built. I was using enclose module but that was causing issue, so i want to change module using which I can compile the code of app and create exe file.

Can you please help me out in this?

**Comment by demian85** [comment] 2017-01-02 13:59
https://www.hyfy.io/

Somehow this guys created a Chrome extension that records screen including mouse and works perfect... Can someone explain this please?

**Comment by hokein** [comment] 2017-01-02 20:31
I'm closing this now as you have already opened another issue tracking the non-visible mouse cursor problem.

**Closed by hokein** 2017-01-02 20:31 UTC

**Comment by demian85** [comment] 2017-01-10 16:43
Please see https://github.com/electron/libchromiumcontent/issues/253

**Comment by TimNZ** [comment] 2017-06-01 03:01
@demian85 Have you had a chance to test with 1.7.x - are the issues fixed?

**Comment by blcktqq** [comment] 2018-01-03 13:37
Probably, i'm expecting same issue on macOS 10.12.6.
After  calling
`  const stream = await navigator.mediaDevices.getUserMedia(getCaptureScreenOptions(s));
` 
my fps goes down

**Comment by CapOM** [comment] 2018-03-23 14:19
With electron 1.8.2 just pass --webrtc-max-cpu-consumption-percentage=100 to disable the throttling, see https://github.com/electron/libchromiumcontent/pull/434
