### ISSUE TITLE
shell.openExternal(..., {activate:false}) opens in foreground

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#7174] opened 2016-09-11 09:52 UTC
* Electron version: 1.3.5
* Operating system: Windows 10, Ubuntu 15.04, Ubuntu 16.04 xfce, Linux Mint 18 *-- possibly more*

`shell.openExternal('http://google.com', {activate:false})` opens urls in the foreground. This **does work on osx**, but doesn't look like it works on any other platform.

**Comment by enlight** [comment] 2016-09-11 10:07
As per [the docs](http://electron.atom.io/docs/api/shell/#shellopenexternalurl-options), the `options` argument is only used on macOS, so what you're describing is the expected behavior.

Closing this out since it works as documented.

**Closed by enlight** 2016-09-11 10:07 UTC

**Comment by Thomas101** [comment] 2016-09-11 10:10
Ah sorry, I missed that!
