### ISSUE TITLE
webContents.printToPDF doesn't work for webpages containing iframe

### ISSUE THREAD

**Issue by vishalini253** [electron/electron#25548] opened 2020-09-20 19:08 UTC
I am trying to convert my webpage to PDF using webContents.printToPDF. Most of the times its working fine but for **pages containing iframe** which I am using for youtube videos this method doesn't end at all. To update the electron version is impossible for my application. I tried to use webview in the place of iframe which was also not helping. Is there any way to fix this in the same version of electron.

Electron version : 5.0.13
OS: mac OS, Windows

```
win.webContents.printToPDF({
    printBackground: true,
    landscape: false,
    marginsType: 1,
    pageSize
    }, (error, data) => {
        console.log('Inside printToPDF callback')
        if(error) {
        showMessage("Unable to export PDF")
        return console.log(error.message);
        }
        fs.writeFile(filePath, data, (err) => {
        if (error) {
        showMessage("Unable to export PDF")
        return console.log(error.message);
        }
        console.log('Write PDF successfully!');
        showMessage(`PDF exported successfully !`);
    });
});
```

For pages containing iframe, the log "Inside printToPDF callback" is never printed.

**Comment by codebytere** [comment] 2020-09-24 03:36
Duplicate of https://github.com/electron/electron/issues/20634

**Closed by codebytere** 2020-09-24 03:36 UTC
