### ISSUE TITLE
Slowdown while typing in <webview>

### ISSUE THREAD

**Issue by MehediH** [electron/electron#6759] opened 2016-08-06 22:15 UTC
- Electron version: 1.3.2
- Operating system: Windows 10 Version 1607, x64

Hi guys, I built an app that uses the <webview> tag. It was using Electron 0.36 for a while now, but after upgrading to 1.3.2, the app starts to lag when the user tries to type something in the webview. It doesn't happen for everyone tho, only for some users.

Any ideas?

**Comment by felixrieseberg** [comment] 2016-08-07 16:16
Do you have a spellchecker attached? Spellchecking is still synchronous and sometimes the cause for lags. We have similar issues in the desktop versions of Ghost and Wordpress.

**Comment by MehediH** [comment] 2016-08-07 16:20
@felixrieseberg We do, but the slowdown occurs even when the feature is disabled. You can try it out yourself: tweeten.xyz

And yes, I also experienced lags while typing a while ago because of the spellchecker. Any idea if that's being fixed anytime soon?

**Comment by MarshallOfSound** [comment] 2016-08-07 17:23
@MehediH This spell checker might reduce the performance hit you are seeing

https://github.com/paulcbetts/electron-spellchecker

**Comment by MehediH** [comment] 2016-08-07 17:38
@MarshallOfSound Get this error when trying to install it: 
![image](https://cloud.githubusercontent.com/assets/10274434/17464084/1cb3bac6-5cce-11e6-8d77-c038629d77ed.png)

**Comment by MarshallOfSound** [comment] 2016-08-07 17:41
@MehediH That error isn't the bit that is helpful to me 😆 

Scroll up above the list of NPM packages and there is a more useful error telling us what it exactly failed to build

**Comment by MehediH** [comment] 2016-08-07 17:42
@MarshallOfSound Sorry about that, here's the full thing https://pastee.org/y33f

**Comment by MarshallOfSound** [comment] 2016-08-07 17:43
Well that error is a bit obvious 😆 

> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

Install Python 2.7 👍

**Comment by MehediH** [comment] 2016-08-07 17:46
That's sorted, now it looks like I need to install Visual Studio.

**Comment by MarshallOfSound** [comment] 2016-08-07 17:51
@MehediH Yeah, it's a native dependency that requires C++ compilation at install time.

**Comment by MarshallOfSound** [comment] 2016-08-07 17:54
@MehediH FWIW you don''t need all of visual studio.  You just need the build tools (lot quicker to install)

http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by MehediH** [comment] 2016-08-07 17:56
@MarshallOfSound  Awesome, thanks for the link!

**Comment by MehediH** [comment] 2016-08-07 18:14
@MarshallOfSound Well I am struggling to install the Net Framework 2.0 SDK. Downloaded it from MS site, but it doesn't open on W10 :/

**Comment by zcbenz** [comment] 2016-08-08 07:58
Can you try how does the page work in this Chrome app?
https://chrome.google.com/webstore/detail/browser-sample/edggnmnajhcbhlnpjnogkjpghaikidaa

It is using `<webview>` in Chrome, I want to verify whether it is an upstream problem.

**Comment by MehediH** [comment] 2016-08-08 09:36
@zcbenz As I have mentioned, I am not having the typing lag, so I have contacted a few guys that were reporting the issue (you can see the lag in "action" here: https://twitter.com/SynTheFeer/status/761808413823205376)

I can confirm it has nothing to do with spellchecker. I even built a new Electron app with a webview for tweetdeck.twitter.com to confirm, and the lag was still there according to one user who was having the typing lag. 

I will get back to you as soon as I can get them to try the Chrome app.

**Comment by MehediH** [comment] 2016-08-08 10:54
@zcbenz There doesn't seem to be any lag in the Chrome app:

http://puu.sh/qtPU7.mp4

But there's a lot of lag in the Electron app: 

 http://puu.sh/qtPUk.mp4

**Comment by zcbenz** [comment] 2016-08-08 11:33
@MehediH Thanks for helping, can you also ask them to test whether tweetdeck.twitter.com has the lag in Chrome app?

**Comment by MehediH** [comment] 2016-08-08 11:50
@zcbenz It's fast on the Chrome app http://puu.sh/qtSfq.gif

**Comment by MehediH** [comment] 2016-08-08 11:54
@zcbenz It's fast on the Chrome app http://puu.sh/qtSr3.mp4 :confused:

**Comment by zcbenz** [comment] 2016-08-08 12:52
That's unlucky, I have no idea why this happens.

**Comment by MehediH** [comment] 2016-08-08 12:54
Damn, any idea what would be a good thing to do? :/

**Comment by MehediH** [comment] 2016-08-09 18:46
Hey guys, any update on this? I have spent hours trying to figure out what's wrong but no clue whatsoever.

**Comment by TimNZ** [comment] 2016-08-13 09:10
Mind blown: discovers <webview> comes from Chrome Apps API, discovers Chrome Apps is pretty cool..

**Comment by MehediH** [comment] 2016-08-23 15:07
Hi @zcbenz,

I have been trying to fix this issue for a while now with no luck. It seems to be an issue related to Electron,  and it really slows down TweetDeck: https://puu.sh/qLxwp.mp4 -- this is a completely new app, built using Electron 1.3.3. I have checked in Chromium, and TweetDeck works just fine (https://puu.sh/qLxrf.mp4).

I would really appreciate it if you could look into this issue, I am available to provide you with any information you need. 

Thanks for your time.

**Comment by Timo-V** [comment] 2017-05-17 17:26
Hi guys,

Sorry to bump this old topic, but I can't find anything else about Tweetdeck and lagging.
I have no idea what Electron is, so sorry about that. Did you solve it already? 
I have the same problem, I don't have Electron I think..?

Cheers.

**Comment by codebytere** [comment] 2017-09-27 01:18
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:18 UTC
Labels: more-information-needed
