### ISSUE TITLE
MenuItem.checked state inconsistent in MenuItem.click handler

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#5515] opened 2016-05-13 00:01 UTC
* Electron version: 0.37.8
* Operating system: All

Add a checkable `MenuItem` and a click handler for it. In the click handler, print out `MenuItem.checked`. Now try it. You'll see a pattern of:
```
true
true
false
true
true
false
```

**Comment by danhp** [comment] 2016-05-14 20:24
I tried to debug this but couldn't reproduce this in `v1.0.2`
Not sure if we had the same code.

```
const menu = new Menu();
menu.append(new MenuItem(
  {
    label: 'Test',
    type: 'checkbox',
    click(item, win) {
      console.log(item.checked)
    }
  }
));
```

**Comment by kevinsawicki** [comment] 2016-06-29 01:46
@CharlieHess are you still seeing issue? Could you provide a code sample if you are? Thanks.

**Comment by zcbenz** [comment] 2016-07-09 02:01
Closing until more information is provided.

**Closed by zcbenz** 2016-07-09 02:01 UTC
Labels: more-information-needed
