### ISSUE TITLE
Orphaned process on Windows

### ISSUE THREAD

**Issue by TimNZ** [electron/electron#6120] opened 2016-06-18 07:53 UTC
- Electron version: 1.2.3
- Operating system: Windows 2008 R2 and Windows 7 SP1

I am load testing a Nightmare based app.
It loads a URL, does various actions and then the process exits.

I have a BAT file running this in a loop.

There's an issue that I'm trying to figure out if it is Nightmare or Electron.

Whilst debugging this I noticed unexpected behaviour.

Occasionally an electron.exe process will be launched as a child of the main electron.exe but will not be terminated on exit of the parent node.exe process

Process tree (as displayed in ProcMon):

node.exe
-> index.js (Nightmare script)
----> electron.exe (main) 
-----------> electron.exe (#1, renderer)
-----------> electron.exe (#2, unknown) <- this is the one that gets orphaned in the process tree

Is there any simple way of doing debug/logging on what triggers a new electron process to be launched for a window?
Why would the #2 process be orphaned on process tree termination?

There is a single BrowserWindow.
The orphan #2 child electron is only using around 2.8mb

**Comment by TimNZ** [comment] 2016-06-18 09:53
Ran the loop for 2 hours.  Each run takes about 7-10 seconds, with the process tree terminated each time on completion.

11 instances of electron.exe left orphaned.

![microsoft remote desktop - - 18 june 2016 at 9 51 pm screen shot](https://cloud.githubusercontent.com/assets/1051701/16170202/f730d3e8-359e-11e6-847c-30f11c9d73a2.png)

**Comment by zcbenz** [comment] 2016-06-19 11:05
Can you install [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) and use it to get the command line parameters of those orphaned processes?

**Comment by TimNZ** [comment] 2016-06-19 12:38
"C:\Services\AutomateWeb\node_modules\electron-prebuilt\dist\electron.exe" --type=renderer --no-sandbox --primordial-pipe-token=978A05126CF11DFFF64A3D3833F1A765 --lang=en-US --node-integration=false --preload="C:\Services\AutomateWeb\node_modules\nightmare\lib\preload.js" --hidden-page --enable-pinch --device-scale-factor=1 --num-raster-threads=1 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --channel="2676.0.874407457\815309623" --mojo-platform-channel-handle=1132 /prefetch:1

**Comment by zcbenz** [comment] 2016-06-20 00:31
It looks like a normal renderer process, not sure why it is not closed.

**Comment by TimNZ** [comment] 2016-06-20 04:42
PID 5608 is the electron.exe launched by nighmare.

PID 15280 is representative of the 2nd renderer process that occasionally gets orphaned.
I can normally see it reach about 6mb memory usage, stays at 2.8mb when it becomes orphaned.

Commandline arguments:

* 5608 - C:\Services\AutomateWeb\node_modules\electron-prebuilt\dist\electron.exe C:\Services\AutomateWeb\node_modules\nightmare\lib\runner.js "{\"dock\":false}"

* 14192 - "C:\Services\AutomateWeb\node_modules\electron-prebuilt\dist\electron.exe" --type=renderer --no-sandbox --primordial-pipe-token=BB610D4BF602AB03782D114567C80FD4 --lang=en-US --node-integration=false --preload="C:\Services\AutomateWeb\node_modules\nightmare\lib\preload.js" --hidden-page --enable-pinch --device-scale-factor=1 --num-raster-threads=1 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --channel="5608.0.828496910\443575164" --mojo-platform-channel-handle=1128 /prefetch:1

* 15280 - "C:\Services\AutomateWeb\node_modules\electron-prebuilt\dist\electron.exe" --type=renderer --no-sandbox --primordial-pipe-token=6A3AEBBD20F0FD40E0CC11F96B637224 --lang=en-US --node-integration=false --preload="C:\Services\AutomateWeb\node_modules\nightmare\lib\preload.js" --hidden-page --enable-pinch --device-scale-factor=1 --num-raster-threads=1 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --channel="5608.1.1012994134\115282895" --mojo-platform-channel-handle=1904 /prefetch:1


![microsoft remote desktop - - 20 june 2016 at 4 34 pm screen shot](https://cloud.githubusercontent.com/assets/1051701/16183351/f8ea9e6e-3704-11e6-9242-f344f3af4185.png)

![microsoft remote desktop - - 20 june 2016 at 4 36 pm screen shot](https://cloud.githubusercontent.com/assets/1051701/16183388/4bc6dda0-3705-11e6-8eff-0c991ccc0c0d.png)

**Comment by TimNZ** [comment] 2016-07-01 23:03
How can I help in a realistic way with this?  Going to be a major issue for a service based app, and there appears to be an issue with electron.exe running under a Windows service vs desktop, which I'll issue separately.

<img width="1194" alt="microsoft remote desktop - - screen shot 2-07-2016 11 01 00 am" src="https://cloud.githubusercontent.com/assets/1051701/16536345/5d6164ca-4044-11e6-8868-8e38766f4d27.png">

**Comment by TimNZ** [comment] 2016-07-02 01:25
More details.
Nightmare is spawning an Electron instance to do its thing and then at some point it calls spawned child_process instance.kill()

Left behind is a child renderer process that is pointing to a non-existent parent

I'm not an expert on node, electron, or process lifetime.
If I run electron.exe directly, a main and renderer process instance are started.
If I kill the main process via task manager, the renderer dies as well.

A quick google on process tree killing in Windows doesn't make clear if children die automatically so don't know if you handle that explicitly.

Let me know if I can provide more details.  I can run a watchdog app that kills orphaned processes every X minutes.  

Ideally this loose end can be clarified/resolved.

<img width="1078" alt="microsoft remote desktop - - screen shot 2-07-2016 1 13 24 pm" src="https://cloud.githubusercontent.com/assets/1051701/16537472/24507b9a-4057-11e6-9018-6134924e0a67.png">

<img width="516" alt="google chrome - github com - - screen shot 2-07-2016 1 23 31 pm" src="https://cloud.githubusercontent.com/assets/1051701/16537513/2e9b1a46-4058-11e6-9a15-7a52f7e6eb9c.png">

**Comment by zcbenz** [comment] 2016-07-02 08:32
Can you provide a minimal nightmare script that can show this problem? I'm unable to reproduce by running nightmare's demo code.

**Comment by TimNZ** [comment] 2016-07-03 20:18
Yes I will create an app to to stress test this, next week.

**Comment by kevinsawicki** [comment] 2016-09-30 17:47
> Yes I will create an app to to stress test this, next week.

@TimNZ any updates on this?

**Comment by TimNZ** [comment] 2016-10-01 00:32
@kevinsawicki Not yet, low priority as it was a server app for one user and I handled the orphaned processes via an hourly cleanup script.

**Comment by kevinsawicki** [comment] 2016-11-16 23:36
Going to close this out until more information is available, please comment if you are still seeing this on 1.4.7+.

**Closed by kevinsawicki** 2016-11-16 23:36 UTC
Labels: more-information-needed

**Comment by TimNZ** [comment] 2016-11-17 00:26
Fair enough.  I'll test it again in December.
