### ISSUE TITLE
async shell.moveItemToTrash ?

### ISSUE THREAD

**Issue by YurySolovyov** [electron/electron#11555] opened 2018-01-02 17:44 UTC
* Electron version: 1.7.10
* Operating system: All

### Expected behavior

`shell.moveItemToTrash` API should have async version

### Actual behavior

`shell.moveItemToTrash` API only has sync version which is bad for Renderer process responsiveness

**Comment by YurySolovyov** [comment] 2018-01-03 08:29
I _think_ it could be done in a backwards-compatible way via looking at callback function presence.

**Comment by MarshallOfSound** [comment] 2018-01-03 08:40
@YurySolovyov We can't always make a synchronous API asynchronous.  In this case, the platform specific API's are synchronous on all platforms; if trashing the item is slowing your process down I'd recommend offloading it to a new process.

**Comment by YurySolovyov** [comment] 2018-01-03 09:44
@MarshallOfSound thanks, I think I'll be fine by doing it in main process instead of renderer.

But out of curiosity, shouldn't chrome's scheduler have a way to spawn a thread for such things?
It seems like a valid approach to make most sync-designed APIs async-friendly

**Comment by YurySolovyov** [comment] 2018-01-03 10:40
TBH, I didn't do any measurements yet, but I'd expect them to be significant because I'm going to allow users to delete arbitrary folders they'll select. In cause I'll to it in renderer, that will block thread for amount of time proportional to the amount of files being deleted, but at least if I do it in main I'll free my UI thread and keep app responsive regardless of amount of files.

I'll try to measure the impact this week.

**Comment by YurySolovyov** [comment] 2018-01-03 18:06
Note for myself: https://chromium.googlesource.com/chromium/src/+/lkcr/docs/threading_and_tasks.md

**Comment by YurySolovyov** [comment] 2018-01-07 17:05
@MarshallOfSound side question, docs do not specify if path should be a file path or dir or if it matters at all - am I getting it right that both file paths and dir paths are supported?

**Comment by YurySolovyov** [comment] 2018-01-07 18:38
@MarshallOfSound I did some simple testing with making the call to `shell` in renderer and using `shell` from main and calling it via IPC:

As delete target I made a dir and ran:
```
npm i webpack
```
Then I wrapped calls with `console.time/.timeEnd` to get for how long the call takes up the thread:

Direct calls in renderer:
```
delete-sync: 493.988037109375ms
delete-sync: 562.8349609375ms
delete-sync: 609.74609375ms
```

Calls to main via IPC:
```
delete-async: 0.156982421875ms
delete-async: 0.13916015625ms
delete-async: 0.172119140625ms
```

Obviously deletion itself takes pretty much the same amount of time, but IPC version returns control faster, but...

...weird thing I noticed is that even tho `-async` version seems faster, UI still gets frozen, not sure why, maybe blocking call in main blocks IPC or something, but I used async IPC variant, so at least that's not something obvious.

> am I getting it right that both file paths and dir paths are supported?

Seems like so, BTW.

**Comment by YurySolovyov** [comment] 2018-01-08 18:22
@MarshallOfSound I was trying to get it working, but I have troubles running the actual callback.
When I'm trying to invoke it, nothing happens, I tried several ways and I either can't make type checker pass or nothing happens. My guess is that I'm doing memory management wrong.

There is a `_test` dir I used to test it and it works like this:

1. build electron
   
    ```sh
    ./script/build.py -c D
    ```
2. run test script
    ```sh
    out/D/electron _test/
    ```

In the test, I'm using an interval to make sure event loop is not blocked, working run will print "Done: true" in the end and close the app.

Branch is here: https://github.com/YurySolovyov/electron/tree/move-to-trash-task-runner

**Comment by YurySolovyov** [comment] 2018-02-13 18:24
@MarshallOfSound I got it working and I can submit a PR if anyone can review it and suggest doing it better somehow.

**Comment by YurySolovyov** [comment] 2018-03-07 20:44
I updated [my branch](https://github.com/YurySolovyov/electron/tree/move-to-trash-task-runner) with (kinda) working Promise-based implementation.
"Kinda" because it works for success (`.then`) case, and hangs on fail (`.catch`) case.
I'd be glad if someone can take a look, but I'm also going to investigate that.

**Comment by YurySolovyov** [comment] 2018-03-08 20:00
@MarshallOfSound or maybe @deepak1556 

[These branches look mostly symmetrical to me](https://github.com/YurySolovyov/electron/blob/move-to-trash-task-runner/atom/common/api/atom_api_shell.cc#L90-L96), I have no idea why rejection does not work.

I'm using test code like this:

```js
const { app, shell } = require('electron');
const fs = require('fs');
const path = require('path');

var count = 0;
setInterval(() => {
  console.log(count++);
  if (count === 100) {
    app.quit();
  }
}, 50);

app.on('ready', function() {
  const filepath = path.join(__dirname, 'test.md');
  fs.writeFileSync(filepath, '# Hello');
  setTimeout(() => app.quit(), 4000);

  // this thing is only called if/when I hit Ctrl+C
  shell.moveItemToTrash(filepath + '123').then(function() {
  // this works perfectly fine, and removes the file
  // shell.moveItemToTrash(filepath).then(function() {
    console.log('Done: success');
    app.quit();
  }).catch(function(error) {
    console.log('Error: ', error);
    app.quit();
  });
});
```

**Comment by YurySolovyov** [comment] 2018-03-13 20:10
Found the issue: basically rejection does not work cause it hangs on [this line](https://github.com/YurySolovyov/electron/blob/move-to-trash-task-runner/atom/common/platform_util_linux.cc#L45).

I'm not sure what causes it to hang, cause if I run 
```
kioclient5 move /home/yury/test/test.md123 trash:/
```
manually from terminal it just prints
```
"The file or folder /home/yury/test/test.md123 does not exist."
```
and exits with code status 1

**Comment by MicahZoltu** [comment] 2019-10-18 08:08
On Windows, deleting a large (200 MB) `node_modules` folder takes about 15 seconds on a reasonably powerful machine with an SSD.  The issue is that Windows is fairly slow at moving folders with many files to the trash (it iterates over them all individually) and `node_modules` folders are notoriously file count heavy.

VSCode uses this for its delete functionality, and currently it runs in the renderer thread which means the entire UI [locks up](https://github.com/microsoft/vscode/issues/71243) for up to minutes depending on the size of `node_modules`.  While VSCode _can_ move this call to a background thread, this is one of those calls that feels like it should _never_ be run in the renderer thread because it is sync at has unbounded time cost (depending on parameters passed in) and there are normal situations where it can take seconds to minutes to complete.

**Comment by bpasero** [comment] 2019-10-18 08:21
> While VSCode can move this call to a background thread

To clarify: I do not think VSCode can or should do that. We could move it to the main process or even our shared process, but that one would lock up for a long time as well. Electron must fix this on their end by possibly moving this call onto a thread.

@deepak1556 would that be easy to do?

**Comment by jonigl** [comment] 2020-05-08 00:08
any update on this?

**Comment by guoyunhe** [comment] 2020-07-09 13:07
Another related "freeze when move to trash" issue https://github.com/microsoft/vscode/issues/101920

**Comment by nornagon** [comment] 2020-08-24 16:37
I agree we should fix this! Unfortunately fixing it will be a breaking change, as the API currently returns a boolean indicating success/failure, so it can't be changed to return a promise.

I propose:

1. Deprecate and eventually remove the `moveItemToTrash` API.
2. Create an improved, asynchronous replacement API, `trashItem`:

```
### `shell.trashItem(path[, options])`
* `path` String - path to the item to be moved to the trash.
* `options` Object (optional)
  * `deleteOnFail` Boolean (optional) - Whether or not to unilaterally remove the item if the Trash is disabled or unsupported on the volume. _macOS_

Returns `Promise<void>` - Resolves when the operation has been completed. Rejects if there was an error while deleting the requested item.

This moves a path to the OS-specific trash location (Trash on macOS, Recycle Bin on Windows, and a desktop-environment-specific location on Linux).
```

**Closed** 2020-09-02 17:32 UTC
Labels: enhancement :sparkles:, platform/all, version/1.7.x
