### ISSUE TITLE
Crash when calling BrowserWindow.close() in will-navigate event

### ISSUE THREAD

**Issue by SamyPesse** [electron/electron#4374] opened 2016-02-05 14:26 UTC
Some of our users (including me now) are signalling crash of our application ([GitBook Editor beta](https://www.gitbook.com/blog/releases/editor-5-beta)).

I don't know exactly how to reproduce it (it happens only for a few users on Windows/Mac). It seems related to the closing of a `BrowserWindow` (after a `win.close()`).

Crash report: https://gist.github.com/SamyPesse/17b165a93b17480cf244
The application is using electron `0.36.7`

I'll be happy to provide more information (ex: code snippets) to help understand the source of this bug,
Thanks :beers:

**Comment by zcbenz** [comment] 2016-02-15 03:36
Stack track:

```
url::Parsed::set_inner_parsed(url::Parsed const&) (in Electron Framework) (url_parse.h:194)
GURL::operator=(GURL) (in Electron Framework) (gurl.cc:170)
content::NavigationHandleImpl::DidRedirectNavigation(GURL const&) (in Electron Framework) (navigation_handle_impl.cc:195)
content::WebContentsImpl::DidGetRedirectForResourceRequest(content::RenderFrameHost*, content::ResourceRedirectDetails const&) (in Electron Framework) (web_contents_impl.cc:2573)
base::internal::Invoker<base::IndexSequence<0ul, 1ul, 2ul>, base::internal::BindState<base::internal::RunnableAdapter<void (*)(int, int, scoped_ptr<content::ResourceRedirectDetails, base::DefaultDeleter<content::ResourceRedirectDetails> >)>, void (int, int, scoped_ptr<content::ResourceRedirectDetails, base::DefaultDeleter<content::ResourceRedirectDetails> >), base::internal::TypeList<int, int, base::internal::PassedWrapper<scoped_ptr<content::ResourceRedirectDetails, base::DefaultDeleter<content::ResourceRedirectDetails> > > > >, base::internal::TypeList<base::internal::UnwrapTraits<int>, base::internal::UnwrapTraits<int>, base::internal::UnwrapTraits<base::internal::PassedWrapper<scoped_ptr<content::ResourceRedirectDetails, base::DefaultDeleter<content::ResourceRedirectDetails> > > > >, base::internal::InvokeHelper<false, void, base::internal::RunnableAdapter<void (*)(int, int, scoped_ptr<content::ResourceRedirectDetails, base::DefaultDeleter<content::ResourceRedirectDetails> >)>, base::internal::TypeList<int const&, int const&, scoped_ptr<content::ResourceRedirectDetails, base::DefaultDeleter<content::ResourceRedirectDetails> > > >, void ()>::Run(base::internal::BindStateBase*) (in Electron Framework) (bind_internal.h:343)
base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask const&) (in Electron Framework) (task_annotator.cc:51)
base::MessageLoop::RunTask(base::PendingTask const&) (in Electron Framework) (message_loop.cc:482)
base::MessageLoop::DoWork() (in Electron Framework) (message_loop.cc:605)
base::MessagePumpCFRunLoopBase::RunWork() (in Electron Framework) (message_pump_mac.mm:328)
base::mac::CallWithEHFrame(void () block_pointer) (in Electron Framework) (call_with_eh_frame_asm.S:38)
...
base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) (in Electron Framework) (message_pump_mac.mm:680)
base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) (in Electron Framework) (message_pump_mac.mm:239)
base::RunLoop::Run() (in Electron Framework) (run_loop.cc:56)
content::BrowserMainLoop::MainMessageLoopRun() (in Electron Framework) (browser_main_loop.cc:1339)
content::BrowserMainLoop::RunMainMessageLoopParts() (in Electron Framework) (browser_main_loop.cc:917)
content::BrowserMainRunnerImpl::Run() (in Electron Framework) (browser_main_runner.cc:236)
content::BrowserMain(content::MainFunctionParams const&) (in Electron Framework) (browser_main.cc:26)
content::ContentMainRunnerImpl::Run() (in Electron Framework) (content_main_runner.cc:798)
content::ContentMain(content::ContentMainParams const&) (in Electron Framework) (content_main.cc:19)
```

I think it is an upstream bug which had already been fixed by https://chromium.googlesource.com/chromium/src/+/314c15b4182d6c1c12c02dc2b2a2adc66dd4ed1e%5E%21/. We will get the fix once we upgraded to Chrome 48.

**Comment by zcbenz** [comment] 2016-02-15 03:38
Also if you are using the `did-get-redirect-request` event in your code, it might help by removing it.

**Comment by SamyPesse** [comment] 2016-02-15 08:41
Thank you @zcbenz 

I've removed the `did-get-redirect-request`, but it's still crashing (https://gist.github.com/SamyPesse/d93f9bce28d7da455677).

I'll wait for the next release with chrome 48 and let you know if it fix it.

**Comment by zcbenz** [comment] 2016-02-15 09:23
@SamyPesse The new crash report makes it look like another bug, can you try making an reproducible example for this? The most suspicious parts are the ones that call `loadURL`.

**Comment by SamyPesse** [comment] 2016-02-15 10:28
@zcbenz Here is some part of the app that reproduce the error: https://github.com/SamyPesse/electron-error

But the bug is happening after authenticating the user (you'll need a [gitbook](https://www.gitbook.com) account), feel free to create a tmp one if you want to and I can delete it after)

**Comment by zcbenz** [comment] 2016-02-15 11:53
I have found the cause, calling `BrowserWindow.close()` in the handler of `will-navigate` will crash the program. To work around it, you can wrap your call of `close` in `handleCallback` with `setImmediate`:

```js
            // Close the browser if code found or error
            setImmediate(function() {
              authWindow.close();
            });

```

**Comment by SamyPesse** [comment] 2016-02-15 13:08
Thanks!

**Closed** 2016-12-28 21:40 UTC
Labels: bug, crash
