### ISSUE TITLE
Cannot load libpepflashplayer.so plugin on Linux in electron Window

### ISSUE THREAD

**Issue by jeandera** [electron/electron#20378] opened 2019-09-30 15:36 UTC
I've made an electron application to execute a flash application using the pepflashplaye plugin several platforms.

I have followed the doc https://electronjs.org/docs/tutorial/using-pepper-flash-plugin

It works fine on Windows, Mac but when i execute it on linux, the electron window is 
launched and a message appear "cannot load plug-in" . Nothing is displayed in devTool console. (Notice the  the plugin works fine with chrome browser), not warnings, no errors ..

Is there a way to know the reason electron cannot load the plugin ?
Can i activate some verbose logs or other messages to understand what happens ?
Is it a known problem or bug ? 

I've displayed my ppapi-flash-path before opening the window and it's the good one ..

pluginName = '/libpepflashplayer.so';
pluginPath =  path.join(__dirname, pluginName)
console.log ("pp = " + pluginPath)
app.commandLine.appendSwitch('ppapi-flash-path', pluginPath)

node version is : v10.16
electron version is : V6.0.10
chromium : v76
Linux CentOS 7
lipepflashplayer.so version : Pepper Flash 32.0.0.255

**Comment by aquaspy** [comment] 2019-10-06 15:19
Same here. I can't build flash apps in electron with newer version. I am using 4.2.6 because of it.

I reported the same here
https://github.com/electron/electron/issues/20309

**Comment by aquaspy** [comment] 2019-10-06 16:29
Use the electron 4.2.11

To install use: npm install electron@4.2.11 in the directory that u want.

**Comment by vsellen** [comment] 2019-11-24 03:22
Just ran into this myself. Apparently there is an issue with sandboxing. See #17034 

> The Flash Player under Linux never worked in a mixed-sandbox or (full-)sandbox environment. As of v5.0.x, mixed-sandbox is forced. This prevents the plugin from loading.

The work around is to add `app.commandLine.appendSwitch('no-sandbox')`

Worked for me v8.0.x custom build. Now to look into the associated risks of running 'no-sandbox'.

**Comment by miniak** [comment] 2019-12-09 23:17
Duplicate of #20309

**Closed by miniak** 2019-12-09 23:17 UTC
Labels: 6-0-x, bug :beetle:, platform/linux
