### ISSUE TITLE
[Bug]: Failed to read shortcut link

### ISSUE THREAD

**Issue by fanchenio** [electron/electron#35780] opened 2022-09-23 07:27 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

20.1.1

### Expected Behavior

Read shortcuts correctly

### Actual Behavior

shell.readShortcutLink read shortcut error

(node:32700) UnhandledPromiseRejectionWarning: Error: Failed to read shortcut link
    at IpcMainImpl.eval (webpack://QLaunch/./src/main/ipcEvent.js?:515:74)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11014)
    at EventEmitter.emit (node:events:527:28)
    at emitUnhandledRejectionWarning (node:internal/process/promises:191:15)
    at processPromiseRejections (node:internal/process/promises:270:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:97:32)
(node:32700) Error: Failed to read shortcut link
    at IpcMainImpl.eval (webpack://QLaunch/./src/main/ipcEvent.js?:515:74)
    at IpcMainImpl.emit (node:events:527:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11014)
    at EventEmitter.emit (node:events:527:28)

The current problem is that some shortcuts can be obtained normally, while others cannot be obtained and an error is reported.
May I know more detailed error information?

**Comment by codebytere** [comment] 2022-09-25 19:59
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-10-12 07:46
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-10-12 07:46 UTC
Labels: bug :beetle:, blocked/need-repro

**Comment by fanchenio** [comment] 2022-10-20 03:13
![image](https://user-images.githubusercontent.com/88647148/196847675-29232854-1732-4acf-9639-c1eb00db8fbd.png)
@codebytere 
This is a clean project, I just added this line of code to read my local shortcuts.
