### ISSUE TITLE
[Bug]: cannot input anything with input method except English one  after clicking macos tray to show the browserwindow

### ISSUE THREAD

**Issue by zhoushaokun** [electron/electron#34952] opened 2022-07-18 12:06 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.3.0-19.0.6

### What operating system are you using?

macOS

### Operating System Version

macos big sur 11.6

### What arch are you using?

x64

### Expected Behavior

In macos system, click your electron app icon in the task bar in the top-right screen, the input in the just showing browserwindow for your click can be inputed by spelling language input method except English, such as Chinese, Japanese...    

### Actual Behavior

First of all, make sure you have set the tray and has some input element in your browserWindow which likes this [dist](https://gist.github.com/zhoushaokun/c8750830e323834ef42ee12b43c5c570).
1. In your macOs system, just put other application on the top of the window, to make sure your test electron app lose the foucs.
2. Then, click the tray icon to put the electron application on top of the window and make the test electron app focus.
3. The input in you test electron cannot be keyed by many language except English. I gusess the language input method which needs spelling and keying space may all have this problem.
![image](https://user-images.githubusercontent.com/32841670/179505593-b081d3cb-95f7-47ed-abb5-375848b9c9b4.png)

And this problem may only occurs in macos  and it will disppear if you just click the other area expect your test electron app to make it blur and click the electron app again to make it focus

### Testcase Gist URL

https://gist.github.com/zhoushaokun/c8750830e323834ef42ee12b43c5c570

**Comment by codebytere** [comment] 2022-07-20 19:28
Duplicate of https://github.com/electron/electron/issues/32307

**Closed by codebytere** 2022-07-20 19:28 UTC
Labels: platform/macOS, bug :beetle:, component/BrowserWindow, has-repro-gist, 11-x-y, 19-x-y
