### ISSUE TITLE
 Loading PDF shows a grey screen only

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#27721] opened 2021-02-12 18:40 UTC
* **Electron Version:** v12.0.0-beta.25 (also tested different v12.0.0-beta versions - all affected)
* **Operating System:** Linux (not tested on other systems)
* **Last Known Working Electron version:** 11.2.3

### Expected Behavior
The PDF content should be displayed.

### Actual Behavior
Only the gray screen is displayed.

### To Reproduce

Load any PDF file using `browserWindowInstance.loadURL / browserWindowInstance.loadFile` methods.

Main process code sample if needed:
```javascript
const {app, BrowserWindow} = require("electron");

app.whenReady().then(() => {
  app.on("web-contents-created", (...[, webContents]) => {
    webContents.on("did-fail-load", (...[, errorCode, errorDescription, validatedURL, isMainFrame]) => {
      console.log({errorCode, errorDescription, validatedURL, isMainFrame});
    });
  });

  // loading via "loadURL" call also affected
  new BrowserWindow().loadFile("path-to-pdf-file.pdf");
});
```

### Additional Information
Possibly similar to #22286. CC @nornagon.

**Comment by vladimiry** [comment] 2021-02-12 21:38
The `did-fail-load` event setup this way:
```javascript
app.on("web-contents-created", (...[, webContents]) => {
  webContents.on("did-fail-load", (...[/* event */, errorCode, errorDescription, validatedURL, isMainFrame]) => {
    console.log({errorCode, errorDescription, validatedURL, isMainFrame});
  });
});
```

Gets triggered with the following data:

```
{
  errorCode: -6,
  errorDescription: 'ERR_FILE_NOT_FOUND',
  validatedURL: 'chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html',
  isMainFrame: true
}
```

**Comment by codebytere** [comment] 2021-02-16 23:30
@vladimiry that should be https://github.com/electron/electron/pull/27499 - i'll see that it gets back to `v12.x`

**Comment by nornagon** [comment] 2021-02-17 22:42
bisected to https://github.com/electron/electron/compare/v12.0.0-nightly.20201026...v12.0.0-nightly.20201030, probably https://github.com/electron/electron/commit/bf89237f602037055d1ea9fdb59cbc5da53372ff is the cause.

**Comment by nornagon** [comment] 2021-02-17 22:43
ah @codebytere already fixed this. Can we close this out now?

**Closed** 2021-02-17 23:50 UTC
Labels: 12-x-y, bug :beetle:, platform/linux
