### ISSUE TITLE
Installation electron failed

### ISSUE THREAD

**Issue by HeiShanLaoYao889** [electron/electron#21251] opened 2019-11-22 07:20 UTC
### Issue Details
There was an error when I executed the command `npm i -D electron@latest`.

`(node:29679) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 0.0.0.0:443
    at ClientRequest.<anonymous> (/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:291:20)
    at ClientRequest.emit (events.js:208:15)
    at ClientRequest.origin.emit (/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:29679) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29679) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

The node version:v12.8.1
The operating system:Mac osx10.15

**Comment by xland** [comment] 2019-11-25 02:14
If you are in a hurry, you can install it manually.
See #20994

**Comment by xland** [comment] 2019-11-25 02:37
I see your id is `Hei Shan Lao Yao`.
I think `GFW` caused your problem.
Try add an environment variable to your system.

> key: ELECTRON_MIRROR
> value: https://npm.taobao.org/mirrors/electron/

**Comment by HeiShanLaoYao889** [comment] 2019-11-29 03:01
I tried many times, but I still couldn't download it

**Comment by amorist** [comment] 2019-11-29 03:06
https://electronjs.org/docs/tutorial/installation#%E9%95%9C%E5%83%8F
```
ELECTRON_MIRROR="https://cdn.npm.taobao.org/dist/electron/"
```

**Comment by xland** [comment] 2019-11-29 04:08
@HeiShanLaoYao889 

Try
```
npm config set ELECTRON_MIRROR http://npm.taobao.org/mirrors/electron/
```

**Comment by ekoneko** [comment] 2019-11-29 05:17
I think the problem is this: [electron/get#125](https://github.com/electron/get/issues/125)

Electron 7 use `@electron/get` instead of electron-download. I hope the install script can read
download config from package.json. (Like `build.electronDownload` in electron-builder)

**Comment by HeiShanLaoYao889** [comment] 2019-11-29 05:39
"json": true,
  "user-agent": "npm/6.9.0 node/v10.8.0 darwin x64",
  "metrics-registry": "https://registry.npmjs.org/",
  "scope": "",
  "home": "https://www.npmjs.org",
  "registry": "https://registry.npmjs.org/",
  "ELECTRON_MIRROR": "http://npm.taobao.org/mirrors/electron/",
  "access": null,
  "allow-same-version": false,
  "always-auth": false,
  "also": null,
  "audit": true,
  "audit-level": "low",

**Comment by xland** [comment] 2019-11-29 07:40
@HeiShanLaoYao889 
What do you mean?

@ekoneko 
I try your method. It doesn't help me.


Now I use this method.

> Create a file named path.txt in node_modules\electron folder.
Write electron.exe in it.
Download electron package manualy.
Unpackage the electron files into node_modules\electron\dist
Run your start script

**Comment by HeiShanLaoYao889** [comment] 2019-11-29 09:30
I've switched to taobao source, but I still can't

**Comment by xland** [comment] 2019-11-29 09:47
Until now on,there is no other good way but to install Electron(^7.0.0) manually.

**Comment by ekoneko** [comment] 2019-11-29 11:39
I write a package ([electron-version-manager](https://github.com/ekoneko/electron-version-manager)) to download electron binary file instead of electron npm package. The package supports mirror options as same as `electron-builder`.

It works fine for me.

**Comment by HeiShanLaoYao889** [comment] 2019-12-02 14:03
> I write a package ([electron-version-manager](https://github.com/ekoneko/electron-version-manager)) to download electron binary file instead of electron npm package. The package supports mirror options as same as `electron-builder`.
> 
> It works fine for me.

试了很多办法,都不行,官方也没人出来说,这个好坑

**Comment by codebytere** [comment] 2019-12-05 22:15
Closing as this is not a problem with Electron itself, as discussed above.

**Closed by codebytere** 2019-12-05 22:15 UTC

**Comment by chanble** [comment] 2019-12-28 14:06
> > I write a package ([electron-version-manager](https://github.com/ekoneko/electron-version-manager)) to download electron binary file instead of electron npm package. The package supports mirror options as same as `electron-builder`.
> > It works fine for me.
> 
> 试了很多办法,都不行,官方也没人出来说,这个好坑

add a path.txt in `node_modules/electron` folder, and put `electron` or `electron.exe` into the path.txt, and download version you want unzip into `node_modules/electron/dist` it work.

在node_modules/electron文件夹下建个path.txt, 写进electron或是electron.exe(windows)，去淘宝镜像上下载个对应版本的electron，解压到node_modules/electron/dist(没有就新建一个)文件夹下。

**Comment by dilingchen** [comment] 2020-05-27 09:51
`npm config set ELECTRON_MIRROR http://npm.taobao.org/mirrors/electron/` works for me.

**Comment by liuzeyafzy** [comment] 2022-05-28 09:18
`npx cross-env ELECTRON_GET_USE_PROXY=true GLOBAL_AGENT_HTTPS_PROXY=http://140.82.113.3:443 yarn` works for me. `140.82.113.3` is `github.com` IP.

use `https://ping.chinaz.com/github.com` to get github.com`s IP
