### ISSUE TITLE
BrowserWindows with type:'desktop' don't emit onmouseover events

### ISSUE THREAD

**Issue by blahsd** [electron/electron#12901] opened 2018-05-12 00:00 UTC
* Electron Version: 1.4.13
* Operating System (Platform and Version): macOS 10.13.4
* Last known working Electron version: None that I know of

**Expected Behavior**
When hovering with the mouse over an html item of a BrowserWindow, the item should emit an onmouseover event.

**Actual behavior**
When BrowserWindow has the 'type' set to 'desktop', html items emit onmouseover events when clicked, rather than when hovered. 

**To Reproduce**
Set a BrowserWindow 'type' attribute to 'desktop'.

[This repo](https://github.com/blahsd/electron-quick-start/tree/doesnt-emit-onmouseover) is a clone of electron-quick-start, with a div bound to an onmouseover event. However, the event isn't generated when the mouse hovers the div. Setting the 'type' attribute to anything but 'desktop' resolves the issue.

```sh
$ git clone https://github.com/blahsd/electron-quick-start -b doesnt-emit-onmouseover
$ npm install
$ npm start || electron .
```
**Additional Information**
An identical issue affects the application of the :hover selector.

**Comment by javan** [comment] 2018-05-15 10:25
That seems like the documented behavior:
> The `desktop` type places the window at the desktop background window level (`kCGDesktopWindowLevel - 1`). Note that desktop window will not receive focus, keyboard or mouse events, but you can use `globalShortcut` to receive input sparingly.

**Comment by blahsd** [comment] 2018-05-15 11:02
Yep. Seems you're right, my bad. I was confused because I was still getting clicks to the app, even with type:'desktop' – it took me reading your comment to realise it must have only been working because my desktop was deactivated.

Is there any other way to have a window non focusable but responsive to hover events? I'm trying out focusable:false, but this also impairs hovers.

**Comment by sofianguy** [comment] 2018-05-15 22:43
Hi @blahsd, can you please give a later version of Electron (e.g., 1.8.6 or 2.0.0) a try and let us know if you are still experiencing the issue and which version.

**Comment by codebytere** [comment] 2018-11-02 19:51
Closing as resolved (intended behavior)

**Closed by codebytere** 2018-11-02 19:51 UTC
Labels: bug :beetle:, platform/macOS, version/1.8.x
