### ISSUE TITLE
[Bug]: Silent print not working on Windows 10 (+solution strategy)

### ISSUE THREAD

**Issue by conteit** [electron/electron#40785] opened 2023-12-18 13:39 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.x.y-29.x.y

### What operating system are you using?

Windows

### Operating System Version

Windows 10 1809 and newer

### What arch are you using?

x64

### Last Known Working Electron version

24.8.8

### Expected Behavior

I expect to be able to print webpage content on the whole page at the right size, instead  This is what happens if printing non silently or with Chromium/Google Chrome.

### Actual Behavior

I get everything printed in the center of the page in approx. a 4x5cm area. As reported thoughtfully in issue #39179.

### Additional Information

I know how to fix it, but I lack C++ and project knowledge for presenting a Pull Request.
The print out get shrunk because, if not specified, silent print, prints at 72 DPI. A better approach would be to query the printer for the actual DPI setting required (see `GetDeviceCaps(hdc, LOGPIXELSX)` and `GetDeviceCaps(hdc, LOGPIXELSY)` where `hdc = CreateDCW(null, <printerName>, null, devmod)` and devmod is retrieved from the printer via `DocumentPropertiesW` call)

I worked around it via print options object and resolved missing information outside electron. By checking electron code you should have everything in place for resolving the information I'm mentioning.

See #39179 for examples and further details.
Would be nice to have the issue back ported at least on 28.x.y.

Hope it helps.

**Comment by victorcarablut** [comment] 2023-12-19 15:05
...other code

mainWindow.hide(); 

const options = {
      silent: true,
      margins: {
        marginType: "none" 
      },
      dpi: {
        horizontal: 600,
        vertical: 600
      },
      color: false
    }

    mainWindow.webContents.print(options, async (success, failureReason) => {
      if (!success) {
        console.log(failureReason);
        mainWindow.close();
      }
      else {
        mainWindow.close();
      }
    });

**Comment by jkleinsc** [comment] 2024-01-08 22:19
- Closing as duplicate of #39179

**Closed by jkleinsc** 2024-01-08 22:19 UTC
Labels: bug :beetle:

**Comment by conteit** [comment] 2024-01-09 07:55
@jkleinsc, I've open the issue because the one I'm duplicating was stale. Is there any actual plan to fix this behaviour?

**Comment by hothaifadev** [comment] 2024-01-11 08:09
@conteit it's not just a windows 10 issue, i'm using windows 11 and have the same issue.
