### ISSUE TITLE
Blank window in any app on Raspberry Pi with OpenGL enabled (used to work in v1.7.x)

### ISSUE THREAD

**Issue by s6joui** [electron/electron#12937] opened 2018-05-15 10:15 UTC
* Electron Version: 2.0.0
* Operating System (Platform and Version): Raspbian Stretch
* Last known working Electron version: 1.7.14

**Expected Behavior**
App renders correctly

**Actual behavior**
Blank / empty glitchy window

**To Reproduce**
Enable OpenGL (Full KMS) in raspi-config
Run the quickstart app on electron 2.0

**Additional Information**
I need to have OpenGL enabled to run some WebGL apps. Works on 1.7.x and earlier but no longer works on 2.0.0.

**Comment by RicoBrase** [comment] 2018-05-15 15:13
Can confirm this with a similiar configuration (Raspberry Pi w/ Raspbian stretch and electron@2.0.0).

In my case, the frame of the window gets drawn, but the content (where the HTML should be rendered) is really buggy (very similiar to "Windows XP window glitch").

Note, that I already had problems getting 1.8.X (I think it was 1.8.4) to work, maybe there were relevant changes on the hardware acceleration?

**Comment by RicoBrase** [comment] 2018-05-16 07:26
Just did some further testing, disabling hardware acceleration by calling `app.disableHardwareAcceleration();` before creating the window made the app start as normal.

While this makes the app run again (for me, at least), I personally wouldn't call it a "fix", since the whole point of enabling OGL (Full KMS)  is to make advantage of the hardware acceleration to improve the speed of electron applications (especially for (not necessarily fancy) animations).

**Comment by dave986** [comment] 2018-06-14 07:37
Hello all, FYI, the same happens on **Linux Mint 17.3 XFCE** with Intel GF driver. I tried the same app with the latest version prior to 2.0.0 and it renders correctly. Also disabling the HW accel. works.

**Comment by RicoBrase** [comment] 2019-01-10 19:37
The problem got fixed for me by https://github.com/electron/electron/pull/15763 (backport of https://github.com/electron/electron/pull/15555).

Since I'm using `electron-prebuilt-compile`, I wasn't able to check electron version 3.0.11 directly, but I compared 3.0.10 and 3.0.13. Issue was gone in 3.0.13.

**Comment by sofianguy** [comment] 2019-08-09 00:48
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 21:03
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 21:03 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/linux
