### ISSUE TITLE
Mac Modal windows should not have rounded corners

### ISSUE THREAD

**Issue by dgmid** [electron/electron#24216] opened 2020-06-20 07:51 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.4
* **Operating System:**
  * macOS 10.15.4
* **Last Known Working Electron version:**
  * 8x

### Expected Behavior
Mac os modal windows that are attached to the parent window as a sheet should have square corners and no border.

### Actual Behavior
In Electron 9.0.4 modal windows attached to the parent window have rounded corners and a border like the parent window

### To Reproduce
Create a parent window with a modal window attached

### Screenshots
Example of a modal window using Electron 8x
<img width="607" alt="electron-8x" src="https://user-images.githubusercontent.com/1267580/85196606-89efd680-b2db-11ea-9062-a4518076cba2.png">

Example of a modal window using Electron 9.0.4
<img width="618" alt="electron-9x" src="https://user-images.githubusercontent.com/1267580/85196613-9411d500-b2db-11ea-8cce-72bc933454bb.png">

**Comment by dgmid** [comment] 2020-06-20 17:19
I've since discovered that if the modal window has the option `frame: false` it gets the frame and rounded corners.

If the option is not set, or is set to `frame: true` it gets no frame and squared corners as it should have.

**Comment by codebytere** [comment] 2020-06-22 19:20
@dgmid i'm not sure i understand what the issue is here. I ran https://gist.github.com/422259047e163df95f647bb96589fdca

and saw:

<img width="912" alt="Screen Shot 2020-06-22 at 12 20 21 PM" src="https://user-images.githubusercontent.com/2036040/85326845-c447a800-b482-11ea-857d-687b328b6d07.png">

framelessness isn't really a concept for sheet windows anyway, but i see no rounded corners.

**Comment by dgmid** [comment] 2020-06-23 05:35
OK, I've found the exact circumstances in which this happens.
If the modal window has:
```
transparent: true,
vibrancy: 'popover',
frame: false
```

it will result in a frame with rounded corners. Setting the frame to `true` removes the frame and rounded corners.

Example:
https://gist.github.com/92c4cb71888289374cedbf83b5c83126

<img width="503" alt="Screenshot 2020-06-23 at 07 29 22" src="https://user-images.githubusercontent.com/1267580/85364712-0674f600-b524-11ea-929c-2094dc86b207.png">

**Comment by codebytere** [comment] 2020-06-23 05:38
@dgmid ah gotcha, that's an easy fix 😛  PR up in a minute.

**Comment by codebytere** [comment] 2020-06-23 05:42
https://github.com/electron/electron/pull/24250 will close this one out, expect it in the next 9.x release!

**Closed** 2020-06-24 14:30 UTC
Labels: 9-x-y, bug :beetle:, platform/macOS
