### ISSUE TITLE
Atom Shell applications not detaching from shell when started via symlink on OS X 10.10

### ISSUE THREAD

**Issue by kopischke** [electron/electron#1151] opened 2015-02-18 15:15 UTC
I’ve run into an [odd issue testing the *Neovim.AS* Atom Shell app](https://github.com/coolwanglu/neovim.as/issues/7), where I cannot get its window to accept keyboard input on OS X 10.10.2 when I start it via the *atom-shell* CLI; instead, all keyboard input goes to the last active application – in the case of the screenshot, the shell in which *Neovim.AS* was started:

![neovim](https://cloud.githubusercontent.com/assets/80906/6232019/c3640e22-b6c9-11e4-87c2-ba6f09075326.png)

I also can’t switch to the window with `Cmd-Tab`, its OS X menu does not display, and the only way to quit it is issuing `^C` in the originating shell. I have reproduced the issue with [another, more straightforward Atom Shell app, *pamm-atom*](https://github.com/pamods/pamm-atom), incidentally showing that the apps are responding to mouse input (Vim not being a really good object to judge that :)).

If I start *pamm-atom* via the GUI, none of the above occurs (not testable with *Neovim.AS* due to the Grunt requirement and lack of `app` folder).

**Configuration:**

- OS X 10.10.2 German locale, German keyboard input. I’ve tried disabling my input hacks (specifically, [Seil](https://pqrs.org/osx/karabiner/seil.html.en) and [Karabiner](https://pqrs.org/osx/karabiner/index.html.en)) and switching to a US keyboard map, but none of that helped.
- *atom-shell* version 0.21.2 64 bit without symbols, downloaded from the Releases pages. The Atom Shell app runs without a hitch by itself, as does *Atom* the editor (which accepts my keyboard input like a champ, I hasten to add).
- OS X stock Terminal.app running the system *bash* (`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)`). The above screenshot shows a version running with *TotalTerminal* injected, but the same issue occurs within standard terminal windows \[EDIT: and in iTerm 2\].

**Comment by advanderveer** [comment] 2015-02-22 14:12
Having the same issue with the same OSX version, actually also experience the issue with nw.js - Feeling like I missed something here.

**Comment by zcbenz** [comment] 2015-02-27 21:08
It seems that OS X doesn't treat the window as a normal window and prevents it to get focus, I tried OS X 10.10.2 with neovim.as app, but could not reproduce.

**Comment by leungwensen** [comment] 2015-02-28 04:58
having the same issue with the same osx version. is there any solution available now?

**Comment by kopischke** [comment] 2015-02-28 11:22
If @zcbenz cannot reproduce, the interesting question is if we all have some configuration in common?

- [x] non-English locale (German in my case)
- [x] non-English keyboard map (German in my case)
- [x] using [Seil](https://pqrs.org/osx/karabiner/seil.html.en)
- [x] using [Karabiner](https://pqrs.org/osx/karabiner/index.html.en)
- [x] using [Moom](http://manytricks.com/moom/)
- [x] using [f.lux](https://justgetflux.com/)

(scraping the bottom of the barrel a bit with these last two, but I’ve tried to include everything I can think of possibly affecting window behaviour) – @advanderveer, @leungwensen how about you?

**Comment by advanderveer** [comment] 2015-02-28 11:37
@kopischke Did you run atom from the cli e.g `$> atom-shell ../app-dir/` while trying to reproduce? How about the terminal you are using? (I'm using default Terminal.app) For the list:

- [ ] non-English locale (US)
- [ ] non-English keyboard map (US)
- [ ] 3rd party keyboard nooks (nope)
- [ ] using a global hotkey hooking app (nope)
- [ ] using a window management app (nope)
- [ ] using a screen management app (nope)

**Comment by kopischke** [comment] 2015-02-28 11:40
> Did you run atom from the cli e.g $> atom-shell ../app-dir/ while trying to reproduce? How about the terminal you are using?

@advanderveer see my original report, it’s all there.

**Comment by advanderveer** [comment] 2015-02-28 13:09
Sorry my question was aimed at @zcbenz

**Comment by kopischke** [comment] 2015-02-28 13:14
> Sorry my question was aimed at @zcbenz

Thought so :). Terminal type is unlikely to play a part in this, tho, as I have reproduced the issue in iTerm 2 in the meanwhile…

**Comment by leungwensen** [comment] 2015-03-02 02:31
@kopischke in my case:

- [x ] non-English locale (Chinese)
- [ ] non-English keyboard map (US)
- [ ] 3rd party keyboard nooks (nope)
- [ ] using a global hotkey hooking app (nope)
- [ ] using a window management app (nope)
- [ ] using a screen management app (nope)

hope this would help

**Comment by d--b** [comment] 2015-03-21 00:06
Same issue here.
Probably related: application menus do not work either... The menu bar remains the Terminal menu bar.

**Comment by d--b** [comment] 2015-03-21 00:10
Note that starting the atom application from the Terminal without argument, and dragging the application in the drop area does work.

**Comment by d--b** [comment] 2015-03-21 16:52
Not ideal but running:

    nohup atom.app myapp

will work

**Comment by kopischke** [comment] 2015-03-21 17:15
> The menu bar remains the Terminal menu bar.

Yup, that was what I meant by “its OS X menu does not display”. Good call about `nohup`: I tried backgrounding the process, but that option slipped my mind. However, workaround is just forcing *atom-shell* to do what it should do anyway: detach from its originating shell; the underlying bug still needs to fixed.

**Comment by d--b** [comment] 2015-03-21 22:57
Mmh. This is in fact debatable. For instance, running `/Applications/Calculator.app/Contents/MacOS/Calculator` from the CLI suffers the same symptoms...

**Comment by pwestling** [comment] 2015-04-12 16:30
Not sure whether this will help you guys out, but I hit this same issue and discovered that it was because my `atom-shell` command was a symlink - specifying the full path to the Atom command within Atom.app solved the issue for me.

**Comment by kopischke** [comment] 2015-04-14 16:37
Confirmed. Using the full path works.

**Comment by builden** [comment] 2015-05-27 15:33
sublime text 3 start from terminate can input on OS X 10.10.3

**Comment by zcbenz** [comment] 2015-10-04 13:06
I have been using Electron on 10.10 for months and didn't observe this bug any more, I'm assuming it has been fixed by OS X.

**Comment by jordansissel** [comment] 2015-11-21 03:00
I appear to be having the problem described in this ticket - OSX keyboard input doesn't work, window focus seems ignored, and no menubar. Mouse input works as i can select text within the Electron app (neovim-e).

```
% Electron --version
v0.35.1
% git rev-parse HEAD
2a05427a05c50818750689190edab6df621e4e8e
```

On OSX 10.11.1

I have no experience with electron, so I may not be of much help debugging or speculating what is causing this.

**Comment by iamitava** [comment] 2016-04-17 16:55
FWIW, this discussion was the top result when I googled "os x symlink app doesn't get keyboard focus", and my issue was not even for neovim or Atom Shell. I am trying out Spacemacs, and after installing emacs (`brew install` + `brew linkapps`) I unnecessarily created a symlink to the linked app. Starting emacs via this symlink had the same issues—no keyboard focus, nothing in the menubar, etc. Using the full path worked. Not sure what's going on, but it's not just Atom Shell.

(I'm on El Capitan 10.11.4)

**Comment by zcbenz** [comment] 2016-05-06 07:12
I'm closing this as won't fix since this is apparently a bug of OS X, and there is no way to fix this on app's side.

**Closed by zcbenz** 2016-05-06 07:12 UTC
Labels: bug, osx
