### ISSUE TITLE
[Bug]: In Gnome, the file picker dialogue does not retain its set size.

### ISSUE THREAD

**Issue by abrattic** [electron/electron#34277] opened 2022-05-18 19:59 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.3

### What operating system are you using?

Other Linux

### Operating System Version

Archlinux

### What arch are you using?

x64

### Expected Behavior

After opening the file chooser, and resizing it to desired size, it should retain the size on closing and opening it again.

### Actual Behavior

When the file chooser is opened and closed repeatedly, it grows a larger, and larger until it grows to the size of the whole screen.

### Additional Information

**This does not happen in any other app.**
I initially reported this in signal-desktop [here](https://github.com/signalapp/Signal-Desktop/issues/5930).

### Steps to Reproduce
1.  Choose the '+' option in a chat to open the file picker, and resize it to desired size.
2.  Close it and open it again. It will be a bit larger than before.
3.  Doing this repeatedly will cause it to grow to the size of the whole screen.

**Comment by codebytere** [comment] 2022-05-19 11:06
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-05-21 08:20
@abrattic does this happen when you open a file picker with Google Chrome on the same device?

**Comment by abrattic** [comment] 2022-05-21 09:03
@codebytere Yes, the same bug occurs.

**Comment by herbdool** [comment] 2022-06-10 21:16
This appears to be an issue with all Chromium-based browsers on Gnome, after I upgraded to Gnome 42.1.

**Comment by codebytere** [comment] 2022-06-13 11:55
@abrattic @herbdool unfortunately this isn't the best place for this issue then - you should file a bug at https://crbug.com. When they address the issue, we'll receive the fix automatically via our Chromium upgrade process.

**Closed by codebytere** 2022-06-13 11:55 UTC
Labels: platform/linux, bug :beetle:, blocked/need-repro, 17-x-y

**Comment by abrattic** [comment] 2022-06-13 15:43
@codebytere @herbdool I just checked. This issue seems to be fixed for me now. I didn't notice when it got fixed, unfortunately.
