### ISSUE TITLE
<webview> tag's ondrop method not working

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#9377] opened 2017-05-05 03:05 UTC
* Electron version: 1.6.x
* Operating system: All platforms

### Expected behavior

Drag a file or link into an webview with ondrop method, and ondrop method will be trigged

### Actual behavior

ondrop method is not trigged

### How to reproduce

Create a browser window with webview tag, for example
```html
<!DOCTYPE html>
<html>
<body>
  <webview src="about:blank" ondrop="event.preventDefault();"></webview>
</body>
</html>
```
drag a file or link into webview and the `preventDefault()` in ondrop method isn't called and webview will be navigated to the file or link's url

**Comment by MarshallOfSound** [comment] 2017-05-05 05:13
@KochiyaOcean You need to handle the drop from within the webview, so handle the drop event on the webviews window object 👍

**Comment by KochiyaOcean** [comment] 2017-05-05 08:03
@MarshallOfSound It works on former version of electron (for example, 1.3.x). So it's a man-made change?

**Comment by KochiyaOcean** [comment] 2017-05-05 08:08
@MarshallOfSound I've tried set `window.ondrop = e => e.preventDefault()` and still navigates :-(

**Comment by KochiyaOcean** [comment] 2017-05-08 11:18
Set
```js
remote.getCurrentWebContents().addListener('will-navigate', e => e.preventDefault())
```
on webview's preload script is also not working to prevent a drag-and-drop navigation.

So is there any way to prevent a drag-and-drop navigation? 😢

**Comment by MarshallOfSound** [comment] 2017-05-08 11:36
@KochiyaOcean You can't use `e.preventDefault()` in a remote event listener as the call will be asyncronous.  Set the event listener in the main process not through remote 👍

**Comment by KochiyaOcean** [comment] 2017-05-08 12:10
@MarshallOfSound so I called e.preventDefault() on main process when url start with 'file' as a workaround for ondrop callback didn't work on both webview and webview's window object 😓

**Comment by flying-circus** [comment] 2017-05-17 20:46
Dup of https://github.com/electron/electron/issues/8667

**Comment by zcbenz** [comment] 2017-06-21 07:35
The webview is implemented as browser plugins in Chromium, so you have to run the code inside the webview. I'm closing this since the behavior is by design, I suggest reporting this to https://crbug.com for improvement.

**Closed by zcbenz** 2017-06-21 07:35 UTC
