### ISSUE TITLE
No subpixel rendering on Linux

### ISSUE THREAD

**Issue by sorentycho** [electron/electron#10955] opened 2017-10-28 01:16 UTC
* Electron version: 1.7.9
* Operating system: Linux (same behavior on Arch and a fresh Ubuntu 17.04 install)

### Expected behavior

Text is rendered with subpixel font antialiasing when that feature is enable at the OS level

### Actual behavior

Electron uses greyscale font antialiasing no matter what:

![2017-10-23-130950_324x76_scrot](https://user-images.githubusercontent.com/30617489/31985527-44e89b66-b91a-11e7-970b-4993df129934.png)

(on top is Electron 1.7.9, on the bottom, nwjs 0.26.0 (Chrome 62), purple border is a window manager border - these are running side-by-side on the same machine)

Here's the pixel difference:
![2017-10-23-130950_324x76_scrot_diff](https://user-images.githubusercontent.com/30617489/32012206-fc530a9c-b96b-11e7-8dde-e820e59403f5.png)

Instrumenting `atom/browser/native_window.cc` after line 88 shows that system-level font rendering settings are being picked up correctly (antialiasing is on, subpixel is set to RGB which is correct for my monitor, etc), indicating that the problem probably exists somewhere inside libchromiumcontent. Right now this is the only app on my systems affected this way, and it occurs on multiple machines and flavors of Linux. Significantly, installing a patched fontconfig/freetype/etc bundle (Infinality) has no effect on font rendering in Electron while working as expected everywhere else including Chromium.

### How to reproduce
```
  $ git clone git@github.com:sorentycho/blackmirror.git
  $ npm install
  $ npm start || electron .
```
...and then observe any text in the application.

**Comment by kolya-ay** [comment] 2017-11-07 11:26
Might be related to electron/libchromiumcontent#384

**Comment by bhack** [comment] 2017-12-15 00:28
Seems that https://github.com/electron/libchromiumcontent/issues/384 is mainly solved. When you will pull a new libchromiumcontent version?

**Comment by burtonator** [comment] 2018-07-16 22:05
Ah... this is biting me right now... It spent about 45 minutes trying to figure out why text looked fuzzy on Electron but not in Chrome. Let's try to fix this!

**Comment by itaniknight** [comment] 2018-10-10 16:15
Is there any news or progress on this one? Coding in Atom/VSCode is hurting my eyes.

**Comment by sorentycho** [comment] 2018-10-10 18:09
They've been ignoring this issue for over two years now (it had been a long-standing bug when I reported it). I eventually switched my project to NW.js just to get decent font rendering.

**Comment by burtonator** [comment] 2018-10-10 18:32
There's an easy workaround to just set the background-color of the window to #fff .... I just got lucky to find it.

Apparently the DEFAULT is supposed to be #fff but they're wrong.

IF someone were to submit a PR for this then it would be fixed on Windows.

**Comment by burtonator** [comment] 2018-10-10 23:37
This is such a simple bug to fix and I reported it in the other thread..  someone needs to send a PR for this.. anyone know where the default constructor is setup?  Let's just create a PR and send it off.

**Comment by burtonator** [comment] 2018-10-10 23:37
And the default is supposed to be #fff anyway.. so the docs are wrong.

**Comment by sorentycho** [comment] 2018-11-08 22:41
Further testing shows that `#000` works as a `backgroundColor` to keep subpixel rendering as well. Not sure about other colors, though I don't think so seeing as e.g. Discord doesn't seem to have subpixel rendering on on linux.

**Comment by burtonator** [comment] 2018-11-22 18:00
It looks like there's a --background-color=#FFF command line option that could be used to set the default everywhere. I haven't figured out if this resolves the situation for me though as I set background-color in the window constructor myself.

However, the issue I have now is that even if I set this in the main BrowserWindow , webviews still break.

I was trying to figure out if I can set this manually in the source by doing my own build and might try that route... but --background-color doesn't actually fix the problem.

I wonder if it's even possible to create a unit test for this. It *might* be possible to take a screenshot of the machine after it's rendered but that might change per platform and with font changes, etc.

At least if we create a unit test we can verify if it regresses.

**Comment by burtonator** [comment] 2018-11-22 18:04
Also, I can't find where the default is set... 

https://github.com/electron/electron/blob/746beb0d8b28809ec96d6ce9ad1ee252402584a7/atom/browser/api/atom_api_browser_window.cc#L44

https://github.com/electron/electron/blob/2f3a8ecd42d70d6466aec5bb1748dfea8f08764e/atom/browser/web_contents_preferences.cc#L284

... which updates the background color but I can't find the defaults for the BrowserWindowConstructor or the defaults for the Webview

**Comment by sofianguy** [comment] 2019-01-08 18:22
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by burtonator** [comment] 2019-01-08 18:39
Definitely still a major issue on the latest 3.0.12 release

**Comment by sorentycho** [comment] 2019-01-08 19:05
I'm also still experiencing this on 3.0.7, though the workaround listed above still works for me.

**Comment by burtonator** [comment] 2019-01-08 20:15
This is meant to be constructive criticism.

There are some major core bugs in Electron that I"m tracking and every major version update we seem to get a post like "if we don't get an update on this bug we're going to close it" without ever trying to figure out if the bug impacts the current version.

I've seen this in 2.x bugs and 3.x bugs too.  Which means that major bugs aren't getting any attention. 

It might be nice to have some sort of acknowledgement that something *is not* being worked on or even that it's acknowledged by the core team.  

I'd rather know that it's not actively being worked on so the community can find a solution.  Some of these CORE issues aren't something that the community can readily fixx.

**Comment by nornagon** [comment] 2019-01-09 00:55
I don't believe anyone is currently working on fixing this issue. We'd be happy to review a PR though!

**Comment by heronils** [comment] 2019-01-19 04:07
I have created a pr for the official docs which adds a page 'fixing blury fonts' which documents this. See #16459

**Closed** 2019-05-07 19:49 UTC
Labels: 3-0-x, bug :beetle:

**Comment by burtonator** [comment] 2019-05-08 20:39
Note that it might not be a good idea to close this bug yet... we see it on iframes too and there's no way to fix that problem.

It also happens when using CSS transforms.  

Chrome doesn't exhibit any of the same problems.

The above documentation is great but really just a workaround.
