### ISSUE TITLE
[Bug]: Showing a window on all virtual desktops 

### ISSUE THREAD

**Issue by DavitMob** [electron/electron#34676] opened 2022-06-21 08:16 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

I have an always on top window, which should always be present when the user switches between virtual desktops. The following code 

```
win.setAlwaysOnTop(true, "floating");
win.setVisibleOnAllWorkspaces(true, {visibleOnFullScreen: true});
```

works perfectly on MacOS. However, on Windows, the window is not present when the user switches between virtual desktops. Is there a way/solution for this on Windows? 

### Actual Behavior

setting `win.setVisibleOnAllWorkspaces(true, {visibleOnFullScreen: true});` should make the window visible on all virtual desktops.

**Comment by DavitMob** [comment] 2022-06-27 09:03
> It's in the docs: "Note: This API does nothing on Windows."

Do you know any alternative to solve this problem on windows?

**Comment by DeverStyle** [comment] 2022-06-27 09:08
No, sorry. I was looking for a different bug and found your issue and wasn't aware this method existed. 
I went to the docs to see if it's something that could be useful for our code and noticed it doesn't do anything on Windows.

**Comment by mlaurencin** [comment] 2022-06-29 00:32
I am going to close this issue as the functionality of `setVisibleOnAllWorkspaces` is as intended [per the docs](https://www.electronjs.org/docs/latest/api/browser-window#winsetvisibleonallworkspacesvisible-options-macos-linux) as mentioned above.

**Closed by mlaurencin** 2022-06-29 00:32 UTC
Labels: bug :beetle:
