### ISSUE TITLE
Forking a process in main.js doesn't work

### ISSUE THREAD

**Issue by IrosTheBeggar** [electron/electron#8773] opened 2017-02-25 15:32 UTC
* Electron version: 1.4.15
* Operating system: Windows 10

I have a simple nodeJS app that has a function to scrape file metadata. Since scraping metadata can be intensive I made the app run this as a child process using fork.

```
const metaParser = child.fork(  fe.join(__dirname, 'parse-metadata.js'), [jsonLoad]);
```

When run in main.js the process is successfully created, but immediately exits. I added some logging to parse-metadata.js and found out that parse-metadata.js executed successfully and ran long enough to run the first few lines of code and then exited.

How do I get electron to fork parse-metadata.js and keep it alive until the end?

**Comment by groundwater** [comment] 2017-02-25 17:17
Hi @IrosTheBeggar, I would like to help get this solved. Can you provide a minimal reproducible case? Many folks just fork https://github.com/electron/electron-quick-start and modify it to produce their bug. We're happy to clone repos while reviewing bugs.

**Comment by IrosTheBeggar** [comment] 2017-02-25 20:04
Ok, working on it now

**Comment by IrosTheBeggar** [comment] 2017-02-25 21:33
After doing some more digging I realized the script was failing silently when it was trying to load the SQLite module.  The SQLite module works just fine throughout the rest of the app, but for some reason electron tries to load it from the wrong location when using fork

```
{ Error: Cannot find module 'C:\Users\paul\Documents\Code\testapp-electron\node_modules\sqlite3\lib\binding\node-v50-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\paul\Documents\Code\testapp-electron\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3) code: 'MODULE_NOT_FOUND' }
```

There is no node-v50-win32-x64 directory in the node_modules folder.  Any idea how to get SQLite module to work?

**Comment by MarshallOfSound** [comment] 2017-02-25 21:37
This now looks like a duplicate of https://github.com/electron/electron/issues/8727

Would recommend following that one for updates :)

**Closed by MarshallOfSound** 2017-02-25 21:37 UTC
Labels: triage/bug, waiting/needs-repro
