### ISSUE TITLE
Notifications are orphaned in notification center if added/removed quickly

### ISSUE THREAD

**Issue by scottnonnenberg-signal** [electron/electron#12887] opened 2018-05-11 00:57 UTC
* Electron Version: 1.8.4
* Operating System (Platform and Version): MacOS 10.11.6
* Last known working Electron version: Unknown

**Expected Behavior**
Any notification, no matter when or how created, is able to be closed and removed from the OS notification area.

**Actual behavior**
When notifications are being created and removed quickly, notifications can be 'orphaned' such that they must be removed from the notification center manually by the user.

**To Reproduce**
In the console, try this:

```
var count = 1;
var notification1 = new Notification(count++ + 'hello!'); notification1.close();
var notification2 = new Notification(count++ + 'hello!'); notification2.close();
var notification3 = new Notification(count++ + 'hello!'); notification3.close();
```

All three notifications will persist in the notification area, even though they were closed.

This behavior even continues if you add some delays:

```
var count = 1;
var notification1 = new Notification(count++ + 'hello!'); setTimeout(() => notification1.close(), 250);
var notification2 = new Notification(count++ + 'hello!'); setTimeout(() => notification2.close(), 250);
var notification3 = new Notification(count++ + 'hello!'); setTimeout(() => notification3.close(), 250);
```

On my machine, Electron starts to reliably remove the notifications around 500-1000ms.

**Comment by sethlu** [comment] 2018-05-19 21:15
The issue only seems occurring with the renderer process.

Since Electron also implements a native solution to system notifications, the expected behavior can be achieved with the following setup. Both notifications should disappear.

```js

const {electron, app, Notification} = require("electron");

app.on("ready", function () {
    var count = 1;

    var notification1 = new Notification({
        "title": "main" + count++
    });
    notification1.show();
    notification1.close();

    var notification2 = new Notification({
        "title": "main" + count++
    });
    notification2.show();
    setTimeout(() => notification2.close(), 250);

});
```

**Comment by pronebird** [comment] 2018-10-11 12:33
Still an issue in Electron 3.0

**Comment by pronebird** [comment] 2018-11-07 11:33
@ckerr how did the review go? is it a bug in chromium?

**Comment by sofianguy** [comment] 2019-08-09 23:08
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 21:05
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 21:05 UTC
Labels: 3-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS, status/reviewed, version/1.8.x
