### ISSUE TITLE
[Bug]: App's tray instantly disappears

### ISSUE THREAD

**Issue by X-Legendary** [electron/electron#32994] opened 2022-02-19 19:08 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Last Known Working Electron version

14.0.0

### Expected Behavior

It is expected for the tray and it's menus to appear until the app is stopped.

### Actual Behavior

After launching the app, the tray dissappears after a couple of seconds (sometimes even instantly).

### Testcase Gist URL

https://gist.github.com/d107ead5c69a6af1795e235b180272f4

### Additional Information

I have read [this article](https://www.electronjs.org/docs/latest/faq#my-apps-tray-disappeared-after-a-few-minutes) in the Electron FAQ, and I still get the same issue. I managed to replicate the same issue on my Windows 7 laptop (64-bit).

**Comment by codebytere** [comment] 2022-02-22 15:12
Duplicate of https://github.com/electron/electron/issues/31564 - looking into it!

**Closed by codebytere** 2022-02-22 15:12 UTC
Labels: bug :beetle:, duplicate

**Comment by codebytere** [comment] 2022-02-22 15:38
@X-Legendary opened up a PR - see linked issue for more info
