### ISSUE TITLE
[Bug]: Electron app crashes on windows 10

### ISSUE THREAD

**Issue by JiaFuGuo** [electron/electron#36515] opened 2022-12-01 01:44 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

13.6.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

ia32

### Expected Behavior

Normal and stable running with no crashs or  less crash。

### Actual Behavior

This dump file has a breakpoint exception stored in it.
The stored exception information can be accessed via .ecxr.
For analysis of this file, run !analyze -v
\*\*\* WARNING: Unable to verify timestamp for ntdll.dll
Unable to load image C:\\Windows\\syswow64\\KERNELBASE.dll, Win32 error 0n2
\*\*\* WARNING: Unable to verify timestamp for KERNELBASE.dll
eax=00000000 ebx=09dfee74 ecx=3d548d30 edx=06ca88b0 esi=09dfecc8 edi=00000000
eip=7792fd91 esp=09dfec84 ebp=09dfecec iopl=0 nv up ei pl zr na pe nc
cs=0023 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000246
ntdll+0x1fd91:
7792fd91 83c404 add esp,4
0:000\> .ecxr;.exr -1;k;.logclose;qd
Unable to load image C:\\Users\\Administrator\\AppData\\Roaming\\electron\\electron\\electron.exe, Win32 error 0n2
\*\*\* WARNING: Unable to verify timestamp for electron.exe
eax=41510a85 ebx=3d548d30 ecx=3d548d30 edx=06ca88b0 esi=3d548d30 edi=00000002
eip=024e4d98 esp=09dff428 ebp=09dff434 iopl=0 nv up ei pl nz na po nc
cs=0023 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000202
electron!content::RenderFrameImpl::Delete+0x78:
024e4d98 cc int 3
ExceptionAddress: 024e4d98 (electron!content::RenderFrameImpl::Delete+0x00000078)
ExceptionCode: 80000003 (Break instruction exception)
ExceptionFlags: 00000000
NumberParameters: 1
Parameter\[0\]: 00000000
\*\*\* Stack trace for last set context - .thread/.cxr resets it
ChildEBP RetAddr
09dff434 0175840d electron!content::RenderFrameImpl::Delete+0x78 \[C:\\projects\\src\\content\\renderer\\render_frame_impl.cc @ 2362\]
09dff500 024f49c3 electron!content::mojom::FrameStubDispatch::Accept+0x11d \[C:\\projects\\src\\out\\Default\\gen\\content\\common\\frame.mojom.cc @ 3397\]
09dff510 03d99f13 electron!content::mojom::FrameStub\<mojo::RawPtrImplRefTraits\<content::mojom::Frame\> \>::Accept+0x13 \[C:\\projects\\src\\out\\Default\\gen\\content\\common\\frame.mojom.h @ 608\]
09dff550 03e267c3 electron!mojo::InterfaceEndpointClient::HandleValidatedMessage+0x93 \[C:\\projects\\src\\mojo\\public\\cpp\\bindings\\lib\\interface_endpoint_client.cc @ 554\]
09dff580 03e2adfa electron!mojo::MessageDispatcher::Accept+0x53 \[C:\\projects\\src\\mojo\\public\\cpp\\bindings\\lib\\message_dispatcher.cc @ 43\]
(Inline) -------- electron!IPC::\`anonymous namespace'::ChannelAssociatedGroupController::AcceptOnProxyThread+0xc7 \[C:\\projects\\src\\ipc\\ipc_mojo_bootstrap.cc @ 945\]
09dff61c 03e2aca6 electron!base::internal::FunctorTraits\<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message) __attribute__((thiscall)),void\>::Invoke\<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message) __attribute__((thiscall)),scoped_refptr\<IPC::(anonymous namespace)::ChannelAssociatedGroupController\>,mojo::Message\>+0x13a \[C:\\projects\\src\\base\\bind_internal.h @ 509\]
(Inline) -------- electron!base::internal::InvokeHelper\<0,void\>::MakeItSo+0x1b \[C:\\projects\\src\\base\\bind_internal.h @ 648\]
(Inline) -------- electron!base::internal::Invoker\<base::internal::BindState\<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message) __attribute__((thiscall)),scoped_refptr\<IPC::(anonymous namespace)::ChannelAssociatedGroupController\>,mojo::Message\>,void ()\>::RunImpl+0x1e \[C:\\projects\\src\\base\\bind_internal.h @ 721\]
09dff63c 03d5af3c electron!base::internal::Invoker\<base::internal::BindState\<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message) __attribute__((thiscall)),scoped_refptr\<IPC::(anonymous namespace)::ChannelAssociatedGroupController\>,mojo::Message\>,void ()\>::RunOnce+0x36 \[C:\\projects\\src\\base\\bind_internal.h @ 690\]
(Inline) -------- electron!base::OnceCallback\<void ()\>::Run+0x10 \[C:\\projects\\src\\base\\callback.h @ 101\]
09dff6a8 03e194af electron!base::TaskAnnotator::RunTask+0x10c \[C:\\projects\\src\\base\\task\\common\\task_annotator.cc @ 173\]
(Inline) -------- electron!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl+0x157 \[C:\\projects\\src\\base\\task\\sequence_manager\\thread_controller_with_message_pump_impl.cc @ 351\]
09dff764 02609bd3 electron!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork+0x1ff \[C:\\projects\\src\\base\\task\\sequence_manager\\thread_controller_with_message_pump_impl.cc @ 264\]
09dff7ac 02611c69 electron!base::MessagePumpDefault::Run+0xb3 \[C:\\projects\\src\\base\\message_loop\\message_pump_default.cc @ 41\]
09dff7e4 0218bc6d electron!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run+0x79 \[C:\\projects\\src\\base\\task\\sequence_manager\\thread_controller_with_message_pump_impl.cc @ 463\]
09dff834 024f6dde electron!base::RunLoop::Run+0x8d \[C:\\projects\\src\\base\\run_loop.cc @ 135\]
09dff90c 017b81b8 electron!content::RendererMain+0x2de \[C:\\projects\\src\\content\\renderer\\renderer_main.cc @ 253\]
09dff928 017b8961 electron!content::RunOtherNamedProcessTypeMain+0x168 \[C:\\projects\\src\\content\\app\\content_main_runner_impl.cc @ 637\]
09dff974 017b7b09 electron!content::ContentMainRunnerImpl::Run+0x171 \[C:\\projects\\src\\content\\app\\content_main_runner_impl.cc @ 958\]
09dffa84 017b7ddf electron!content::RunContentProcess+0x2d9 \[C:\\projects\\src\\content\\app\\content_main.cc @ 372\]
09dffaa4 0120a61d electron!content::ContentMain+0x2f \[C:\\projects\\src\\content\\app\\content_main.cc @ 398\]
09dffb68 0120a261 electron!wWinMain+0x39d \[C:\\projects\\src\\electron\\shell\\app\\electron_main.cc @ 285\]
Unable to load image C:\\Windows\\syswow64\\kernel32.dll, Win32 error 0n2
\*\*\* WARNING: Unable to verify timestamp for kernel32.dll
09dffb84 766bcb82 electron!FiberBinder+0x11 \[C:\\projects\\src\\electron\\shell\\app\\electron_main.cc @ 127\]
WARNING: Stack unwind information not available. Following frames may be wrong.
09dffbbc 766bcb3a kernel32+0x3cb82
09dffbcc 00000000 kernel32+0x3cb3a``

**Comment by VerteDinde** [comment] 2022-12-01 18:23
Closing as a duplicate of #36516

**Closed by VerteDinde** 2022-12-01 18:23 UTC
Labels: bug :beetle:
