### ISSUE TITLE
Popup MenuItem click handlers not being called

### ISSUE THREAD

**Issue by gshahbazian** [electron/electron#11818] opened 2018-02-02 21:45 UTC
* Electron version: Electron built at aea06ed
* Operating system: macOS 10.13.2

### Expected behavior

`MenuItem` click handlers should get called in the popped up context menu.

### Actual behavior

Click handlers never getting called back.

### How to reproduce

Open a popup in the main window:

```
window.webContents.on('context-menu', (event) => {
    const menu = new Menu()
    menu.append(new MenuItem({label: 'MenuItem1', click() { console.log('item 1 clicked') }}))
    menu.append(new MenuItem({type: 'separator'}))
    menu.append(new MenuItem({label: 'MenuItem2', type: 'checkbox', checked: true}))
    menu.popup(mainWindow)
  })
```

Right click on the running window and select `MenuItem1`, the log `item 1 clicked` should print but doesn't.

**Comment by codebytere** [comment] 2018-02-05 03:55
@gshahbazian i'll try to get to this this week

**Comment by codebytere** [comment] 2018-02-25 13:35
i'll be continually investigating this issue this week

**Comment by bpasero** [comment] 2018-02-25 15:16
This is easy to reproduce also from within dev tools: Just try to use the context menu on debug breakpoints and see how they do not work.

**Comment by codebytere** [comment] 2018-02-25 20:53
verdict: caused by [this commit](https://github.com/electron/electron/commit/d7bc127c6065f3206284269f6b886546f4cdb91e#diff-0a6d4ddeae086b5db6034ab060fc8d94)

**Comment by PalmerAL** [comment] 2018-03-05 23:38
Would it be possible to backport the fix for this to 2.0?

**Comment by codebytere** [comment] 2018-03-06 01:11
@PalmerAL i'll go out with the next beta :)

**Comment by PalmerAL** [comment] 2018-03-06 01:13
@codebytere OK, thanks!

**Comment by bpasero** [comment] 2018-03-06 05:56
@codebytere any reason it did not?

**Comment by MarshallOfSound** [comment] 2018-03-06 05:58
C62 was merged to master and this fix wasn't backported, we're still getting used to the new versioning policy so we forgot to backport a few things (this included)

**Closed** 2018-03-08 14:37 UTC
Labels: merged/2-0-x, platform/macOS, triaged/bug, version/2.0.x
