### ISSUE TITLE
Getting blank screen after reload

### ISSUE THREAD

**Issue by johndave8116** [electron/electron#14978] opened 2018-10-05 06:40 UTC
I am using electron 3.0.2 with angular build.
first time it will load perfectly when i try to reload the screen gets blank.

also in network showing failed to load the build. in flash.

u can reproduce this with basic default template of angular 6. 

steps to reproduce

1. npm install -g @angular/cli
2. ng new my-dream-app
3. cd my-dream-app
4. ng build
use this angular build to build electron app, run it and reload. u will get the blank screen

**Comment by pronebird** [comment] 2018-10-08 00:01
Not enough steps to reproduce this issue.

**Comment by johndave8116** [comment] 2018-10-08 11:36
@pronebird 
steps to reproduce 
1. npm install -g @angular/cli
2. ng new my-dream-app
3. cd my-dream-app
4. ng build

use this angular build to build electron app, run it and reload. u will get the blank screen

**Comment by pronebird** [comment] 2018-10-08 12:36
It would be the best if you didn't trash the template in the origin message and instead put all of the information that I have to extract from you in there. The chances of resolving this issue would definitely grow much higher. Until then it's only me and 0 maintainers who looked at this. 🤷‍♂️ Bureaucracy sucks but there are 1000 issues like this in here, all low quality posts that take other people's time. 😞

**Comment by Dari-K** [comment] 2019-02-28 17:45
The problem is because Electron can't handle the history API being used. You can reproduce this easily on a build from master with the default Electron app.
`out/Debug/Electron.app/Contents/MacOS/Electron`
Open dev console
`history.pushState(null, '', './test');`
cmd/ctrl + r or `location.reload()`
Left with a white window.
On a page refresh it needs to repeat the logic it uses to find the index.html in the first place.

**Comment by Dari-K** [comment] 2019-03-01 13:51
In https://github.com/electron/electron/blob/4f8ebafa972c260d83cb396369d2a7c416651a61/lib/browser/navigation-controller.js#L57 you update your internal history when `history.pushState` is called, so it's treating 'navigation' with the history API the same as actual page navigation.

**Comment by Dari-K** [comment] 2019-03-01 17:53
Could do something along the lines of
```diff
diff --git a/lib/browser/navigation-controller.js b/lib/browser/navigation-controller.js
index c3dd89d52..f18c8562e 100644
--- a/lib/browser/navigation-controller.js
+++ b/lib/browser/navigation-controller.js
@@ -38,9 +38,11 @@ const NavigationController = (function () {
       if (this.inPageIndex > -1 && !inPage) {
         // Navigated to a new page, clear in-page mark.
         this.inPageIndex = -1
+        this.inPageUrl = null
       } else if (this.inPageIndex === -1 && inPage && !replaceEntry) {
         // Started in-page navigations.
         this.inPageIndex = this.currentIndex
+        this.inPageUrl = this.history[this.currentIndex]
       }
       if (this.pendingIndex >= 0) {
         // Go to index.
@@ -125,10 +127,13 @@ const NavigationController = (function () {
     return p
   }
 
-  NavigationController.prototype.getURL = function () {
+  NavigationController.prototype.getURL = function (checkInPageUrl) {
     if (this.currentIndex === -1) {
       return ''
     } else {
+      if (checkInPageUrl && this.inPageUrl) {
+        return this.inPageUrl
+      }
       return this.history[this.currentIndex]
     }
   }
@@ -140,12 +145,12 @@ const NavigationController = (function () {
 
   NavigationController.prototype.reload = function () {
     this.pendingIndex = this.currentIndex
-    return this.webContents._loadURL(this.getURL(), {})
+    return this.webContents._loadURL(this.getURL(true), {})
   }
 
   NavigationController.prototype.reloadIgnoringCache = function () {
     this.pendingIndex = this.currentIndex
-    return this.webContents._loadURL(this.getURL(), {
+    return this.webContents._loadURL(this.getURL(true), {
       extraHeaders: 'pragma: no-cache\n'
     })
   }
@@ -171,6 +176,7 @@ const NavigationController = (function () {
     this.currentIndex = -1
     this.pendingIndex = -1
     this.inPageIndex = -1
+    this.inPageUrl = null
   }
 
   NavigationController.prototype.goBack = function () {
```

Which would fix the reload electron triggers with cmd/ctrl + r, but from the javascript side if you call `location.reload()`, it will still bork. Ideally we could have some sort of `singlePageApplication` option for `BrowserWindow` or `WebContents`, which would always serve the specified file for any loaded path. Seems like that could be difficult to plumb through on the chromium side though? Is there any point in submitting a pull request with this diff, or what else could we do here?

**Comment by iyobo** [comment] 2019-04-06 14:09
I think the fix for ctrl/cmd + r is a worthwhile patch. Sometimes I just want to do that but I can't right now as it just goes blank. I wonder how Slack does it because I can cmd/ctrl + r there and it loads everything the same. Perhaps the do it by running a local server and run BrowserWindow off that as opposed to off file:// ?

**Comment by juanreynolds** [comment] 2019-07-10 14:45
I found the solution here:
https://discuss.atom.io/t/angular-2-routes-breaking-on-electron-app-refresh/28370/5#post_6

> first you should add this to imports
> imports: [
> BrowserModule,
> NgxElectronModule,
> RouterModule.forRoot(routes, { useHash: true }) // add :{ useHash: true }
> ],
> than change <base href="./"> to <base href="">

**Comment by sofianguy** [comment] 2019-08-09 22:51
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by Dari-K** [comment] 2019-08-13 12:03
Same problem with electron 4.2.4.

**Comment by NatoBoram** [comment] 2019-08-15 16:03
Same problem with `"electron": "^6.0.2",`.

**Comment by juanreynolds** [comment] 2019-08-16 03:52
I don't think this is an Electron problem. In so far as it pertains to Angular it seems to be an Angular issue for which there is a solution.

**Comment by Dari-K** [comment] 2019-08-16 11:39
@juanreynolds I disagree, sure you can fix it by turning on `useHash: true` for your routing style, but all that does is switch from the new browser history API to the old fragment routing, the problem is that Electron doesn't handle use of the history API correctly, it's nothing to do with Angular any app which uses the history API would have problems.

**Comment by iyobo** [comment] 2019-08-16 21:32
@juanreynolds correct. I use react and have the same problem.

**Comment by Christilut** [comment] 2019-09-07 23:50
Same problem here with Vue.

**Comment by joaodforce** [comment] 2019-09-25 20:10
I'm also having the same issue, adding `useHash: true` did not change the behaviour at all.

However I have a hint as why this happens.

This problem happens the same way if you don't configure `.htaccess` on a webserver for example.
the thing is that Angular does not have actual files for all the routes that are configured on the Angular router. The only "real page" is `index.html`, but as soon as you navigate to another route, the loaded url changes to `URL_PREFIX/navigated_route/` for example, and then if you try to reload the page with `F5`, `Ctrl+R` or by code `window.location.reload()` electron will try to load `navigated_route` that does not exist!

On webservers we fix this by using `.htaccess` to route all 404 not found to index.html. If you dont do that when you try to reload a page on the browser, you will get a 404 not found from the server.

We need to find a way to do this using electron.

**Comment by XatMassacrE** [comment] 2019-10-09 10:19
@joaodforce Work for me, thank you.

**Comment by XatMassacrE** [comment] 2019-10-09 10:36
```
globalShortcut.register('CommandOrControl+R', () => {
  console.log('CommandOrControl+R is pressed');
  win.loadURL(url.format({
    pathname: path.join(__dirname, 'dist/index.html'),
    protocol: 'file:',
    slashes: true
  }));
})
```
will also work for me, but if you use `location.reload()` in devtools you will still get blank screen.

**Comment by joaodforce** [comment] 2019-10-09 10:43
> ```
> globalShortcut.register('CommandOrControl+R', () => {
>   console.log('CommandOrControl+R is pressed');
>   win.loadURL(url.format({
>     pathname: path.join(__dirname, 'dist/index.html'),
>     protocol: 'file:',
>     slashes: true
>   }));
> })
> ```
> 
> 
> will also work for me, but if you use `location.reload()` in devtools you will still get blank screen.

This is a very bad solution on my books, since it only solves half of the problem.
Since you might actually need to reload your page programatically, on my software I need to use `location.reload()` when the user changes the language, since everything needs to be reloaded to change properly.

**Comment by XatMassacrE** [comment] 2019-10-09 10:53
@joaodforce You're right, i forget about some other reload actions. Fallback to the default index.html can also avoiding some other `fail load` error.

**Comment by kukulski** [comment] 2020-02-19 21:56
I just lost a day to 'Getting blank screen after reload'.  Based on @sofianguy 's tag of 3 hours ago, I updated my Electron to latest and it cleared up.  The `yarn install` took long enough to make me wonder if it was stuck. I wonder if I'd broken things yesterday cancelling an apparently-hung yarn operation.

**Comment by amiller-gh** [comment] 2020-04-08 06:21
In case it helps anyone, here is the latest that I've settled on for my project (inspired by @joaodforce's solution above)

```js
  let location = '/';
  win.webContents.on('did-navigate-in-page', () => {
    location = win.webContents.getURL().replace(/^file:\/\//, '');
  });

  win.webContents.on('did-fail-load', async() => {
    await win.loadFile(pagePath);
    win.webContents.executeJavaScript(`
      require('preact-router').route('${location}');
    `);
  });
```
I happen to be using `preact-router`, but you can replace the `executeJavaScfript` code with whatever is required to load a path in your framework. You may also choose to replace this with an IPC call.

**Closed** 2020-04-15 12:45 UTC
Labels: 3-0-x, 4-2-x, 6-0-x, 6-1-x, bug :beetle:

**Comment by hussaa1** [comment] 2020-10-21 04:05
If it helps someone else, for my Angular 8 single page project, as inspired by @joaodforce's solution above, it worked for me like this;

win.webContents.on('did-fail-load', () => {
  console.log('on browser reload it did-fail-load and reloaded the app');
  win.loadURL(`file://${__dirname}/dist//index.html`);
});

**Comment by capc0** [comment] 2021-02-05 15:46
the only problem I see with @joaodforce solution is that if the loading actually fails (due to other errors), it would lead to an infinite  loading loop.

**Comment by joaodforce** [comment] 2021-02-05 16:02
> the only problem I see with @joaodforce solution is that if the loading actually fails (due to other errors), it would lead to an infinite loading loop.

That is an excellent point, but as long as the fallback page is accessible it should not be an issue. I think it is up to the developer to implement safeguards in that case, like a retry count policy, of a check if the failed to page is the same as the fallback cash the software graciously for example.

I did not implement any however, because I did not think of that at the time. but I'll certainly change this in my projects in the future.

**Comment by capc0** [comment] 2021-02-05 16:35
I ended up with a global angular service as the only point in my application where ```window.location.reload()``` is called. The service first sends an IPC message to the main process where a flag is set - indicating the next ```did-fail-load``` event will be due to a manual app reload.

In the ```did-fail-load``` callback I check if the flag is enabled and either try to reload the window/url (and reset the flag) or gracefully crash the app (as an unknown error).

**Comment by LeonardoRick** [comment] 2021-02-24 13:55
@capc0 would be nice to see an example of your solution

**Comment by capc0** [comment] 2021-02-24 14:03
@LeonardoRick sure - no problem.

browser context (only function where window.location.reload is executed):

```ts

reloadWindowGracefully() {
  ipcRenderer.send('WILL_RELOAD');
  window.location.reload();
}

```

electron context:

```ts
let nextFailedLoadIsDueToReload: boolean = false;

ipcMain.on('WILL_RELOAD', () => {
  nextFailedLoadIsDueToReload= true;
});

window.webContents.on('did-fail-load', async (err) => {
        if (nextFailedLoadIsDueToReload) {
            nextFailedLoadIsDueToReload = false;
            await window.loadURL(url.format({
                pathname: path.join(__dirname, '../../dist/index.html'),
                protocol: 'file:',
                slashes: true
            }));
        }
        else {
            // crash due to other reasons
            throw err;
        }

    });


```

**Comment by pattrickrice** [comment] 2021-03-03 22:19
`url.format` is now deprecated, is there an example of using the WHATWG URL API?

**Comment by clark-97** [comment] 2021-03-22 05:16
> In case it helps anyone, here is the latest that I've settled on for my project (inspired by @joaodforce's solution above)
> 
> ```js
>   let location = '/';
>   win.webContents.on('did-navigate-in-page', () => {
>     location = win.webContents.getURL().replace(/^file:\/\//, '');
>   });
> 
>   win.webContents.on('did-fail-load', async() => {
>     await win.loadFile(pagePath);
>     win.webContents.executeJavaScript(`
>       require('preact-router').route('${location}');
>     `);
>   });
> ```
> 
> I happen to be using `preact-router`, but you can replace the `executeJavaScfript` code with whatever is required to load a path in your framework. You may also choose to replace this with an IPC call.

@amiller-gh  I got error:  Uncaught ReferenceError: require is not defined

**Comment by cawa-93** [comment] 2021-05-02 17:37
You can use custom [`FileProtocol`](https://www.electronjs.org/docs/api/protocol#protocolregisterfileprotocolscheme-handler) to solve this problem.

[Here is an example of my solution.](
https://github.com/cawa-93/anime-library/blob/2485fae4edbb34753838a40feb98ee9dff054306/packages/main/src/createCustomProtocol.ts#L6-L19)


It Works like a proxy: on all requests ending in `/` returns the root html. And For all others - the file in the specified path:
```
app://./ -> file://project/renderer/dist/index.html
app://./route/name/ -> file://project/renderer/dist/index.html
app://./index.js -> file://project/renderer/dist/index.js
app://./route/name/styles.css -> file://project/renderer/dist/route/name/styles.css
```

**Comment by simonv3** [comment] 2022-04-22 22:13
I'm still experiencing this issue in electron `18.0.3`, and it's a little unfortunate that it was marked as closed by OP cause I'm not seeing that it was actually fixed. I feel like hacking a reload here is not really desirable?

**Comment by TraderSamwise** [comment] 2022-12-14 20:22
For future reference, I was previously doing

```
 _win.webContents.on(
    'did-fail-load',
    async (
      event,
      errorCode,
      errorDescription,
    ) => {
        if (!isDev) {
          if (errorCode === -6) {
            await _win.loadURL(`file://${path.join(__dirname, '../build/index.html')}`);
          }
        }
    }
  );
```

This stopped working when upgrading to React 18. Also tried upgrading electron, still broken.

The solution was to use HashRouter for electron. We are still using normal Router for web, but electron w/ HashRouter solved all our reloading issues.

**Comment by temaqwest** [comment] 2023-02-14 14:45
Does anyone knows what `/#/` symbols in uri means? I've faced with the same problem on Vue + Electron and adding this - > `/#/` at the start of each route helps to solve problem with reloading

**Comment by simonv3** [comment] 2023-02-14 15:21
@temaqwest you're probably using [hash routing](https://upmostly.com/tutorials/what-is-hash-routing)
