### ISSUE TITLE
Updated to v1.3.4 errors : Out of memory. size=4194304

### ISSUE THREAD

**Issue by bdxing** [electron/electron#6988] opened 2016-08-26 02:54 UTC
* Electron version: v1.3.4
* Operating system:  Windows_NT 6.1.7601

======================= ERROR INFO========================
D:\linksame>electron .

[3008:0826/112836:FATAL:memory.cc(19)] Out of memory. size=4194304
Backtrace:
        (No symbol) [0x000000013FB18B51]
        (No symbol) [0x000000013FB121DC]
        icu_56::Transliterator::setID [0x00000001427F9ABA+1286202]
        icu_56::MessagePattern::partSubstringMatches [0x0000000142D838E4+5754468
]
        icu_56::MessagePattern::partSubstringMatches [0x0000000142D834A3+5753379
]
        icu_56::Calendar::weekNumber [0x0000000141703DA5+4723845]
        icu_56::Calendar::weekNumber [0x000000014174A053+5011251]
        icu_56::Calendar::weekNumber [0x00000001417491EE+5007566]
        icu_56::Calendar::weekNumber [0x0000000141756292+5060978]
        icu_56::Calendar::weekNumber [0x000000014180982D+5795597]
        icu_56::Calendar::weekNumber [0x000000014178B7F6+5279446]
        icu_56::Calendar::weekNumber [0x000000014178BD52+5280818]
        icu_56::Calendar::weekNumber [0x000000014178CF50+5285424]
        icu_56::Calendar::weekNumber [0x00000001417783C4+5200548]
        icu_56::Calendar::weekNumber [0x00000001417130C9+4786089]
        icu_56::Calendar::weekNumber [0x00000001417AE8FE+5423070]
        icu_56::Calendar::weekNumber [0x00000001417A8D95+5399669]
        icu_56::Calendar::weekNumber [0x00000001417120F3+4782035]
        icu_56::Calendar::weekNumber [0x000000014170C5F8+4758744]
        icu_56::MessagePattern::partSubstringMatches [0x0000000142A7E49C+2587164
]
        icu_56::MessagePattern::partSubstringMatches [0x0000000142B5559A+3468058
]
        icu_56::MessagePattern::partSubstringMatches [0x0000000142B5505D+3466717
]
        icu_56::MessagePattern::partSubstringMatches [0x0000000142B7864F+3611599
]
        icu_56::MessagePattern::partSubstringMatches [0x0000000142B2E143+3307203
]
        icu_56::MessagePattern::partSubstringMatches [0x0000000142B2DF4D+3306701
]
        icu_56::MessagePattern::partSubstringMatches [0x0000000142B2DEA7+3306535
]
        icu_56::MessagePattern::partSubstringMatches [0x0000000142B0BCCC+3166796
]
        icu_56::TimeZone::setID [0x000000014052E699+3726873]
        icu_56::TimeZone::setID [0x000000014052E56E+3726574]
        GetHandleVerifier [0x000000013FBB1ED1+375729]
        (No symbol) [0x000000013FB347AA]
        BaseThreadInitThunk [0x0000000076D55A4D+13]
        RtlUserThreadStart [0x0000000076F8B831+33]

**Comment by zcbenz** [comment] 2016-08-26 11:56
Under most cases the out of memory crashes are caused by memory leaks in apps, which we are not able to fix, it is also possible this is caused by memory leaks in Electron, but we need a minimal reproducible example to clearly show it.

**Comment by kevinsawicki** [comment] 2016-09-30 18:00
Closing this out for now until more details or an app that reproduces the issue are provided.

**Closed by kevinsawicki** 2016-09-30 18:00 UTC
Labels: more-information-needed
