### ISSUE TITLE
window.open() always open an invisible window if created an invisible new BrowserWindow before

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#8275] opened 2016-12-23 05:56 UTC
* Electron version: 1.4.5
* Operating system: win 10

### Expected behavior

`window.open()` always opens a visible window.

### Actual behavior

`window.open()` opens an invisible window if run `new BrowserWindow({ show: false });` before.

### How to reproduce

**index.html**
```
<button type=button onclick="window.open('index.html')">Open</button>
```

**index.js**
```
const {app, BrowserWindow} = require('electron');
app.once('ready', () => {
	let win = new BrowserWindow({ show: false }); //create a invisible window and show it later
	win.maximize();
	win.show();
	win.loadURL(__dirname + '/index.html');
});
```

Run the app, click the **Open** button, the new window is not visible.

**Comment by akashwoz** [comment] 2016-12-23 06:15
Yep, this seems to be a bug, reproduced on 1.4.13

**Comment by kevinsawicki** [comment] 2016-12-29 18:00
I believe this is a duplicate of #3751, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2016-12-29 18:00 UTC
Labels: bug
