### ISSUE TITLE
Segmentation fault on startup if XDG_CONFIG_DIRS (or GTK2_RC_FILES) contains too many items

### ISSUE THREAD

**Issue by settel-np** [electron/electron#11234] opened 2017-11-23 20:44 UTC
* Electron version: 1.7.9
* Operating system: Linux (Ubuntu 17.10)
also affected: Electron version 1.6.15 (comes with Atom 1.22.1)
also affected: Electron version 1.6.2 (comes with "Electron API Demos-linux-x64")

### Expected behavior

Application window should open

### Actual behavior

Crash right at the start, before the main window shows up.

```
 Electron API Demos-linux-x64/ $ ./Electron\ API\ Demos 
Segmentation fault
```

### How to reproduce 

Could only be reproduced with packaged electron applications like Atom or Electron API Demo

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start/
npm install
npm install --save-dev electron-packager
node_modules/.bin/electron-packager . eqs
XDG_CONFIG_DIRS=a:b:c:d:e:f:g:h:i:j:k eqs-linux-x64/eqs
```

### Workaround
unset XDG_CONFIG_DIRS and GTK2_RC_FILES before running your application
```
export XDG_CONFIG_DIRS=""
export GTK2_RC_FILES=""
./Electron\ API\ Demos
```

### References
* https://community.spotify.com/t5/Ongoing-Issues/Segfault-when-too-many-paths-in-GTK2-RC-FILES/idi-p/1274917
* https://github.com/atom/atom/issues/15944

**Comment by settel-np** [comment] 2017-12-05 22:08
I couldn't reliably reproduce the crash on all my Ubuntu 17.10 machines. One crashes most of the time, two others don't. 

Anyone besides me who can reproduce this?

**Comment by adamdrake** [comment] 2017-12-09 17:06
I can confirm I have the same issue ever since I upgraded to 17.10, and that this resolved it.  It's definitely an Electron issue since it is happening to people with Atom, Visual Studio Code, Slack, etc.

**Comment by csharp** [comment] 2017-12-12 16:34
I can also confirm.   In my case, I saw the behavior for a bit, then it disappeared, but it's certainly back now -- Slack, Atom, Opera all crash when started from the dock or command line.   If I unset the GTK2_RC_FILES, they start fine.

**Comment by nergdron** [comment] 2017-12-15 23:28
same issue, with same solution of setting GTK2_RC_FILES to nothing fixes it.

**Comment by TheLQ** [comment] 2017-12-18 18:57
Also reproducible on Ubuntu with v1.8.2-beta.3 and v1.6.15 on Ubuntu 17.10. Can run with XDG_CONFIG_DIRS= electron. By default Ubuntu ships with

```
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg/xdg-ubuntu:/etc/xdg/xdg-ubuntu:/etc/xdg/xdg-ubuntu:/etc/xdg/xdg-ubuntu:/etc/xdg/xdg-ubuntu:/etc/xdg
```

Got below output with ELECTRON_ENABLE_STACK_DUMPING=1

```
Received signal 11 SEGV_MAPERR ffffffffffffe41c
#0 0x0000037e48b7 <unknown>
#1 0x0000037e442f <unknown>
#2 0x7f4597f92150 <unknown>
#3 0x0000037dd162 <unknown>
#4 0x000003f8a236 <unknown>
#5 0x0000037f16a5 calloc
#6 0x7f4593af15d1 g_malloc0
#7 0x7f45965114c9 <unknown>
#8 0x7f4596516855 g_type_register_static
#9 0x7f4596516af5 g_type_register_static_simple
#10 0x7f45976a8f24 gdk_display_manager_get_type
#11 0x7f45976a8f69 gdk_display_manager_get
#12 0x7f4597a85954 <unknown>
#13 0x7f4597a6bf28 <unknown>
#14 0x7f4593af7fdf g_option_context_parse
#15 0x7f4597a6c538 gtk_parse_args
#16 0x7f4597a6c5b9 gtk_init
#17 0x0000014be056 <unknown>
#18 0x0000014b5597 <unknown>
#19 0x0000014b7a06 <unknown>
#20 0x000003f5c9a0 brightray::BrowserMainParts::PreEarlyInitialization()
#21 0x000003dee6d9 atom::AtomBrowserMainParts::PreEarlyInitialization()
#22 0x000001a1a924 <unknown>
#23 0x0000016a69dc <unknown>
#24 0x0000019b8292 <unknown>
#25 0x0000015acda8 <unknown>
#26 0x0000005c963f <unknown>
#27 0x0000015ad012 <unknown>
#28 0x000003de5788 main
#29 0x7f45913c31c1 __libc_start_main
#30 0x0000005a9c79 <unknown>
  r8: 00001497792521e0  r9: 0000000000000010 r10: 000000006a72fdac r11: 0000000000000001
 r12: 0000000000000050 r13: 0000000000000000 r14: 00001497792050b0 r15: 00001497792cc4b0
  di: 0000000000000050  si: 0000000000000005  bp: ffffffffffffe414  bx: 0000000000001beb
  dx: 0000000000000000  ax: 000000000000000f  cx: 0000000000000004  sp: 00007ffc977b0040
  ip: 00000000037dd162 efl: 0000000000010213 cgf: 002b000000000033 erf: 0000000000000005
 trp: 000000000000000e msk: 0000000000000000 cr2: ffffffffffffe41c
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by rh314** [comment] 2017-12-28 13:52
Adding my stack trace too if it helps (the call chain is very similar)

```Received signal 11 SEGV_MAPERR ffffffffffffe633
#0 0x00000342c087 <unknown>
#1 0x7f1d11538150 <unknown>
#2 0x0000033aeacb <unknown>
#3 0x000003d05a78 <unknown>
#4 0x0000033a6023 calloc
#5 0x7f1d0ce8f5d1 g_malloc0
#6 0x7f1d0fab74c9 <unknown>
#7 0x7f1d0fabc855 g_type_register_static
#8 0x7f1d0fabcaf5 g_type_register_static_simple
#9 0x7f1d10c4de04 gdk_display_get_type
#10 0x7f1d10c4ed00 <unknown>
#11 0x7f1d0faba1c9 g_type_class_ref
#12 0x7f1d0fa9fd98 g_object_new_with_properties
#13 0x7f1d0faa0801 g_object_new
#14 0x7f1d10c4ef75 gdk_display_manager_get
#15 0x7f1d1102b954 <unknown>
#16 0x7f1d11011fcb <unknown>
#17 0x7f1d0ce95fdf g_option_context_parse
#18 0x7f1d11012538 gtk_parse_args
#19 0x7f1d110125b9 gtk_init
#20 0x00000134c3b6 <unknown>
#21 0x00000134493f <unknown>
#22 0x000001347366 <unknown>
#23 0x000003cd7adb brightray::BrowserMainParts::PreEarlyInitialization()
#24 0x000003b8a629 atom::AtomBrowserMainParts::PreEarlyInitialization()
#25 0x0000017ee1cb <unknown>
#26 0x0000017d76ff <unknown>
#27 0x00000164dde8 <unknown>
#28 0x00000134fe04 <unknown>
#29 0x000001350210 <unknown>
#30 0x000003b82e73 main
#31 0x7f1d0a75a1c1 __libc_start_main
#32 0x00000059a3b9 <unknown>
  r8: 00003465e25ea0c0  r9: 0000000000000010 r10: 0000000004824ff1 r11: 0000000000000001
 r12: 0000000005201a38 r13: 0000000000000000 r14: 00003465e259d0b0 r15: 00003465e265d230
  di: 0000000000000050  si: 0000000000000005  bp: ffffffffffffe62b  bx: 00000000000019d4
  dx: 0000000000000000  ax: 000000000000000f  cx: 000000000000000c  sp: 00007ffd05b8c9e0
  ip: 00000000033aeacb efl: 0000000000010213 cgf: 002b000000000033 erf: 0000000000000005
 trp: 000000000000000e msk: 0000000000000000 cr2: ffffffffffffe633
[end of stack trace]```

**Comment by xloem** [comment] 2018-01-13 18:15
I've been experiencing this issue on Debian Stretch.  It happens intermittently.  Sometimes only outside the debugger, sometimes only when certain modules are present ...  It looks like it happens inside an OS library.

**Comment by antonpiatek-imanage** [comment] 2018-02-19 11:21
Just been hitting this with several apps all morning on ubuntu 17.10 - workaround of exporting empty env vars worked for me allowing Postman and gitkraken to start

**Comment by lakonis** [comment] 2018-02-19 19:56
The workaround setting XDG_CONFIG_DIRS to nothing does not work for me. 
See [atom issue #16784](https://github.com/atom/atom/issues/16784)
Any help from Electron ?

**Comment by xloem** [comment] 2018-02-19 20:10
Some time ago I tried to get this to happen inside a debugger, but when I built electron from source the problem did not occur, so I assumed some dependency had a bugfix since the last release and the problem will disappear in the next.

It would be good to see if anybody can reproduce this when electron is built from source.

**Comment by lakonis** [comment] 2018-02-19 20:28
thanks @xloem , would you have a (relatively detailed) procedure for me to test this ?
I understand electron comes with atom. I don't "see" anything about electron on my machine presently. Therefore, does installing electron independantly from atom would affect the way atom is working ?

**Comment by tosho** [comment] 2018-04-21 12:12
I'm currently running Ubuntu 17.10 (upgraded from 17.04) and few days ago suddenly all my Electron apps stopped working - VSCode, Discord, Ganache, Lisk Nano (just to name a few) installed from .deb, snap and from .AppImage. Some of the apps that I run from the terminal gave me "segmentation fault (core dumped)" others didn't start nor gave me an error at all.
Adding  ` export XDG_CONFIG_DIRS="" , export GTK2_RC_FILES="" ` to my `.profile` solved the issue for me (for now) and all the apps are running normal.

**Comment by codebytere** [comment] 2018-09-24 05:16
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 05:16 UTC
Labels: bug/crash :boom:, platform/linux/ubuntu, version/1.6.x, version/1.7.x
