### ISSUE TITLE
Crash or missing login event with proxy server

### ISSUE THREAD

**Issue by felixrieseberg** [electron/electron#20943] opened 2019-11-04 16:56 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0-beta.4 through 7.0.0, 8.x
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**: 7.0.0-beta.3, 6.x

### Expected Behavior
Starting an app with a proxy server should not lead to a crash, the `login` event should be emitted.

### Actual Behavior
Electron `7.0.0-beta.4`: Silent crash
Electron `7.0.0-beta.5 – 7.0.0`: `login` event not emitted, network non-functional

### To Reproduce
You'll need a proxy server to reproduce the missing `login` event, which might be a somewhat difficult to get. In our testing, the issue exists regardless of the proxy server used (even a simple basic auth proxy fails just like a fancy NTLM one).

https://gist.github.com/4d032c5ec44983f714d5bbab2bb472e9

**Comment by nornagon** [comment] 2019-11-04 19:20
Seems like a duplicate of #20752?

**Comment by nornagon** [comment] 2019-11-04 19:26
Duplicate of #20752

**Closed by nornagon** 2019-11-04 19:26 UTC
Labels: 7-0-x, 8-x-y
