### ISSUE TITLE
TouchBarPopover broken in electron 11.x

### ISSUE THREAD

**Issue by ggreco** [electron/electron#26761] opened 2020-12-01 14:02 UTC
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.0.3
* **Operating System:** MacOS catalina 10.15.7
* **Last Known Working Electron version:** 10.1.3

The TouchBarPopover item does not work anymore, creating a popover and clicking on it shows an empty touch bar.

### Expected Behavior
The TouchBarPopover defined TouchBar should be displayed.

### Actual Behavior
The TouchBarPopover is not showing the TouchBar specified in his items field.

### To Reproduce

Here is a minimal example, this is the main process script, the test does not need renderer code at all.

```javascript
const { app, BrowserWindow,TouchBar } = require('electron');
const { TouchBarButton, TouchBarPopover } = TouchBar;

const touchBar = new TouchBar({
    items: [
        new TouchBarPopover({
            label: "2D",
            items: new TouchBar({
                items: [
                    new TouchBarButton({ label:"Disc", click: ()=> console.log("new", "Disc")}),
                    new TouchBarButton({ label:"Beam", click: ()=> console.log("new", "Beam")}),
                ]
            })
        })
    ]
});

function createWindow () {
  const win = new BrowserWindow({ width: 800, height: 600, webPreferences: { nodeIntegration: true } });
  win.setTouchBar(touchBar);
}

app.whenReady().then(createWindow);
```

... it needs a mac to be tested!

### Screenshots
Wanted behaviour (as with electron 10.1.6):

![IMG_3739](https://user-images.githubusercontent.com/1829939/100750275-14d61080-33e6-11eb-968f-7dc9ccca6c20.jpg)
Actual behaviour (electron 11.0.2 and electron 11.0.3):
![IMG_3738](https://user-images.githubusercontent.com/1829939/100750318-24555980-33e6-11eb-87a7-bb6e9abadf9d.jpg)

**Comment by erickzhao** [comment] 2020-12-01 16:46
Bisecting with Electron Fiddle, it seems like this broke between the July 16 and July 17 nightlies. You can see the diff here:
https://github.com/electron/electron/compare/v11.0.0-nightly.20200716...v11.0.0-nightly.20200717

In particular, PR https://github.com/electron/electron/pull/24511 stands out as one that directly refactors the TouchBar code.

**Comment by erickzhao** [comment] 2020-12-01 16:52
Seems like a duplicate of https://github.com/electron/electron/issues/26615

**Comment by MarshallOfSound** [comment] 2020-12-01 17:28
Duplicate of #26615

**Closed by MarshallOfSound** 2020-12-01 17:28 UTC
