### ISSUE TITLE
Limitations of executeJavaScript Should Be Documented

### ISSUE THREAD

**Issue by shellscape** [electron/electron#9288] opened 2017-04-25 21:20 UTC
* Electron version: 1.6.6
* Operating system: MacOS 10.12.4

I was struggling something awful with why I couldn't return a collection of Nodes through `executeJavaScript`. That was, until I ran across a thread with an obscure comment instructing that DOM elements could not be passed through IPC. The documentation for this limitation should be front and center for the method, but is nowhere to be found: https://github.com/electron/electron/blob/master/docs/api/web-contents.md

### Expected behavior

```
webContents.executeJavaScript(`document.querySelector('div')`, (result) => {
  console.log(result);
});
```
A DOM Element should be returned as the result.

### Actual behavior

The running app freezes/locks and must be Force Quit.

### How to reproduce

Follow this link https://discuss.atom.io/t/how-to-return-value-from-webcontents-executejavascript/22726/9 to a discussion about returning DOM elements from `executeJavascript`.

**Comment by kevinsawicki** [comment] 2017-04-25 21:53
You should be able to access DOM elements this way, can you share the code where you saw it freeze/lock up?

It might be hanging if the DOM element has lots of properties that are being serialized, https://github.com/electron/electron/issues/7286

**Comment by shellscape** [comment] 2017-04-25 23:46
I attempted to return the following on google.com with the same results:

`document.querySelector('body');`

`document.querySelector('div');`

`document.querySelectorAll('div')[0];`

At a point I thought there might be an operation it was hanging on, so I let the `querySelector('div')` call sit for about 30 minutes while I prepared some food. Unfortunately it was still hung when I returned.

**Comment by kevinsawicki** [comment] 2017-04-25 23:55
> I attempted to return the following on google.com with the same results:

Can you try it with a smaller page and see if it returns the expected data? Just to try and confirm it is the large node issue.

**Comment by MaharishiCanada** [comment] 2017-05-24 10:00
For what it is worth, my experience is also that I cannot pass DOM elements. I can pass strings, but never a DOM element. I have the most recent version of Electron. I am on Ubuntu 16.10.

**Comment by MaharishiCanada** [comment] 2017-05-24 10:08
Are all the events available in executeJavaScript? It might be documented that the onload event is not available. I never could catch this event in executeJavaScript.  It would be great if there was no limitation.

**Comment by shellscape** [comment] 2017-05-24 12:22
@kevinsawicki I neglected to reply, but fwiw I did try to run the same on a very small page. I posted a bare bones html page to my github pages site that contained a single `div` in the body, and got the same result.

**Comment by MaharishiCanada** [comment] 2017-05-26 06:27
Perhaps this sentence from https://electron.atom.io/docs/development/atom-shell-vs-node-webkit/ explains the limitations: 
> In order to avoid the complexity of building all of Chromium, Electron uses libchromiumcontent to access Chromium’s Content API.
Since webContents, even as an attribute of BrowserWindow, is executed in the main process, it seems natural that the script executed in executeJavaScript would be interpreted to use this API. It's different than a script executed natively in the renderer. The API might provide a way to get DOM elements, but I never succeeded. Certainly, it would explains why we don't have access to all events native to the renderer.  The message  loops of these two different processes might not be fully integrated.  Well, this is not an answer. I am learning.  It's my guess.

**Comment by MaharishiCanada** [comment] 2017-06-02 08:36
Well, I finally checked and we do have access to click, change, etc. in executeJavaScript. I also succeeded to get the entire window element using executeJavaScript.  Here is the code that I used: 

```
var script =  `Promise.resolve(window);`
app.on('ready', () => {
  var win = new BrowserWindow();
  win.loadURL('file://' + __dirname + '/index.html');
  var maincontents = win.webContents; 
  maincontents.on('did-finish-load', () => {
       allwebcontents = webContents.getAllWebContents();
       viewcontents = allwebcontents[1]; // There was a simple webview tag in index.html. 
       viewcontents.executeJavaScript(script)
               .then((value) => {console.log(value);  }) // The entire window object of the webview.
               .catch((error) => console.log(error));
  });  
  win.on('closed', () => {win = null});
}); 
```

**Comment by shellscape** [comment] 2017-06-02 12:31
What were the context of the index.html file you used for this example?

**Comment by MaharishiCanada** [comment] 2017-06-02 19:49
I just added  `<webview src="https://github.com" ></webview>` in the Hello World example of the documentation: 

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    <!-- All of the Node.js APIs are available in this renderer process. -->
    We are using Node.js <script>document.write(process.versions.node)</script>,
    Chromium <script>document.write(process.versions.chrome)</script>,
    and Electron <script>document.write(process.versions.electron)</script>.

    <webview src="https://github.com" ></webview> 
      
  </body>
</html>
```

**Comment by MaharishiCanada** [comment] 2017-06-03 02:11
I realized that it does not work. I am learning about the architecture of Electron.  I start to consider the possibility that HTML DOM objects cannot exist in the main process. They can only exist in the renderer. This would explain why I can serialize with `var s = new XMLSerializer(); var str = s.serializeToString(adiv);` and send the string `str` as a resolved promise, but then it is pointless to try to de-serialize it as an HTML DOM object in the main process. The window  object is not an HTML DOM object, so it worked partially.  This is my guess.

**Comment by zcbenz** [comment] 2017-06-20 08:10
Data sent back to `executeJavaScript` are passed by IPC so only properties that can be serialized are kept. You can observe same behavior when sending DOM nodes to WebWorkers.

For the original issue you posted, sending DOM nodes should not freeze the app, can you provide a minimal app that can reproduce the problem?

**Comment by gerges** [comment] 2017-07-09 00:45
If possible, it may be beneficial to not send the response over ipc if `userGesture` and `callback` aren't provided. I started experiencing locking when upgrading from `1.6.2` to `1.6.8` when `executeJavascript` was called with any `jQuery` operation even though they're all fire/forget.

It's terrible, but here's the workaround I've added in the meantime. For some reason `WebView` doesn't exist when my preload script executes, so I had to do the following.

```
let patched;
Object.defineProperty(window, 'WebView', {
  get: () => {
    return patched
  },
  set: (WebView) => {
    if (!WebView.prototype._patched) {
      let originalExecuteJavascript = WebView.prototype.executeJavaScript;
      WebView.prototype.executeJavaScript = function (code, userGesture, callback) {
        if (!userGesture && !callback) {
          originalExecuteJavascript.call(this, `() => {${code}}();`)
        } else {
          originalExecuteJavascript.apply(this, arguments);
        }
      };
      WebView.prototype._patched = true;
    }
    patched = WebView;
  }
});
```

**Comment by codebytere** [comment] 2017-09-27 01:19
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:19 UTC
Labels: more-information-needed
