### ISSUE TITLE
something wrong with utf-8 encoding?

### ISSUE THREAD

**Issue by lqm229026** [electron/electron#7137] opened 2016-09-08 11:44 UTC
* Electron version: **v1.3.5**
* Operating system: **win7 x64**

I have created a simple example here: there are only two files in the directory: _package.json_ and _main.js_. I'm sured that they are saved by UTF-8 encoding.
There are only two keys in _package.json_: _name_ and _main_, just like this
```
{
    "name":"simple-example",
    "main":"main.js"
}
```

the _main.js_ has only one line:
`console.log("中文")`

When I run `electron .` under that directory, the output on console is not right.
![image](https://cloud.githubusercontent.com/assets/15317435/18348113/1560a882-75fc-11e6-9929-674bdc18584c.png)

While if I run node main.js, I can see the expected result:
![image](https://cloud.githubusercontent.com/assets/15317435/18348148/42ca86bc-75fc-11e6-8692-ccb7a5740d7c.png)

I think there are something wrong with encoding, can anyone here tell me how to fix it and why?

**Comment by vsemozhetbyt** [comment] 2016-09-08 11:55
This info could be useful:

1. Do you use the same console window for the both cases?
2. What shell do you use (cmd.exe or something else)?
3. What is output of the `chcp` command in the console with the problem case?

**Comment by lqm229026** [comment] 2016-09-08 12:07
1. yes
2. cmd
3. 936

![image](https://cloud.githubusercontent.com/assets/15317435/18348735/bf4ded8e-75ff-11e6-89d6-a091516edeae.png)

**Comment by vsemozhetbyt** [comment] 2016-09-08 12:26
Is the problem fixed when you:

1. run `chcp 65001` in the console before `electron .`
2. set default Unicode cp for all consoles via Windows registry:
```
[HKEY_CURRENT_USER\Console]
"CodePage"=dword:0000fde9
```

**Comment by kevinsawicki** [comment] 2016-09-08 16:01
I believe this is a duplicate of https://github.com/electron/electron/issues/5761, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2016-09-08 16:01 UTC

**Comment by boly38** [comment] 2024-02-02 12:42
for git bash user and`chcp` => `chcp.com 65001` is the way
