### ISSUE TITLE
Menu items don't show keyboard shortcuts

### ISSUE THREAD

**Issue by erusev** [electron/electron#7363] opened 2016-09-27 16:24 UTC
* Electron version: 1.4.0
* Operating system: Ubuntu 16

This is replicatable in Atom.

**Comment by kevinsawicki** [comment] 2016-09-28 17:21
Reproduced this on Ubuntu 16 and Electron 1.4.1, was also able to reproduce it there with 1.3.x so I'm not sure when this regressed.

This does not seem to impact Ubuntu 14.

**Comment by kevinsawicki** [comment] 2016-09-28 17:34
Looks like this is Chrome bug, the shortcuts are missing there as well on Ubuntu 16.

<img width="588" alt="screen shot 2016-09-28 at 10 25 41 am" src="https://cloud.githubusercontent.com/assets/671378/18925017/16064448-8567-11e6-8f78-29cf25e45a07.png">

Tracked by https://bugs.chromium.org/p/chromium/issues/detail?id=636718

**Comment by magicae** [comment] 2016-10-17 19:54
> This would appear to be a Unity bug: fixed in Ubuntu 16.10 release candidate. The bug also affected Firefox, and that is fixed in the Ubuntu 16.10 RC as well.

**Comment by kevinsawicki** [comment] 2016-10-24 03:21
Closing this out since it is now fixed in newer versions of Ubuntu.

**Closed by kevinsawicki** 2016-10-24 03:21 UTC
Labels: blocked, bug, linux, linux-distribution-specific, menu
