### ISSUE TITLE
A native addon that depends on BoringSSL fails to build for Electron 5

### ISSUE THREAD

**Issue by murgatroid99** [electron/electron#18122] opened 2019-05-02 17:16 UTC
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0
* **Operating System:**
  * Debian 4.19.28
* **Last Known Working Electron version:**:
  * 4.1.0

### Expected Behavior
The build completes successfully with no errors

### Actual Behavior
The build fails with the following error:

```
../deps/grpc/third_party/boringssl/include/openssl/base.h:143:0: error: "OPENSSL_THREADS" redefined [-Werror]
 #define OPENSSL_THREADS
```

### To Reproduce

Doing this requires node, python and a working C and C++ compilation toolchain.

```sh
$ git clone --recursive https://github.com/grpc/grpc-node.git
$ cd grpc-node/packages/grpc-native-core
$ HOME=~/.electron-gyp ./node_modules/.bin/node-pre-gyp configure rebuild package --runtime=electron --target=5.0.0 --disturl=https://atom.io/download/electron
```

Note that replacing `5.0.0` with `4.1.0` results in a successful build. 

### Additional Information
The extra definition seems to be coming from `common.gypi` in the headers tarball. The line that defines it does not appear in the `4.1.0` version of the headers tarball.

**Comment by nornagon** [comment] 2019-05-02 17:24
Looks like it was added here: https://github.com/nodejs/node/commit/765766be641c747b5bcb4a472801452bd041323f. Not sure what the Right Answer™ is, but you could maybe try hacking around this by setting `node_shared_openssl` to `true`, as it looks like that variable guards the definition in common.gypi. Or you could explicitly remove the define from the command line with `defines!`, e.g. https://github.com/nodejs/node/blob/master/node.gypi#L46

**Comment by refack** [comment] 2019-05-02 19:30
> but you could maybe try hacking around this by setting `node_shared_openssl` to `true`

IMO that's might even be better then my suggestion in https://github.com/nodejs/node/issues/27540#issuecomment-488800646 (which is similar to @nornagon's other suggestion).
`node_shared_openssl` indicates to the build scaffolding that you want to link against a shared OpenSSL (or OpenSSL like) library. Although it's original intent was to enable creating a node binary without embedded static OpenSSL, I believe it will suite this use case.

**Comment by refack** [comment] 2019-05-06 12:08
Hello @murgatroid99, has the workaround been sufficient for your use-case?

**Comment by murgatroid99** [comment] 2019-05-06 23:50
The workaround works for me, but that doesn't change the fact that this is a bug in Electron that should be fixed in Electron.

**Comment by followbin** [comment] 2019-09-25 12:21
Now, a same problem ：i use 'ffi' node module in electron@4.1.0 successfully,but can`t work in electron 5.0.0 or 6.0.0. please give me same help?

**Comment by electron-triage** [comment] 2020-02-19 19:56
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:14
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:14 UTC
Labels: 5-0-x, blocked/need-info ❌, bug :beetle:, platform/linux
