### ISSUE TITLE
[Bug]: in mac, when use use roundedCorners false and frame false , BrowserWindow.close has no effect

### ISSUE THREAD

**Issue by eyun-tv** [electron/electron#32514] opened 2022-01-18 07:25 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0-beta.1

### What operating system are you using?

macOS

### Operating System Version

12.1

### What arch are you using?

x64

### Expected Behavior

in mac, when use use roundedCorners false and frame false , BrowserWindow.close has no effect
``` 
{
  skipTaskbar: true,
  frame: false,
  minimizable: false,
  maximizable: false,
  webPreferences: { preload: '/Users/z/git/rv/desk/dist/preload/index.cjs' },
  width: 800,
  height: 500,
  roundedCorners: false,
  resizable: false
}
```

### Actual Behavior

should close

**Comment by codebytere** [comment] 2022-01-18 09:47
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by kyleshay** [comment] 2022-01-18 23:37
Here's a repro: 

https://gist.github.com/759a9871d17d1fcf89eaf162c02ebef3

There is a setTimeout that calls mainWindow.close() after 1000ms in main.js (if you comment out `roundedCorners:false` it will close.)

**Comment by kyleshay** [comment] 2022-01-18 23:38
Also, is it possible that this is related? #28686

**Comment by nornagon** [comment] 2022-01-19 00:56
Yep, I bet it's the same issue. Closing as a duplicate of #28686.

**Closed by nornagon** 2022-01-19 00:56 UTC
Labels: platform/macOS, bug :beetle:, blocked/need-repro, 17-x-y
