### ISSUE TITLE
The futex facility returned an unexpected error code.

### ISSUE THREAD

**Issue by bisakhmondal** [electron/electron#24211] opened 2020-06-19 13:15 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Just started with the electron, but whenever running `npm start`, it's failing due to the futex error. So I cloned [this](https://www.electronjs.org/docs/tutorial/first-app#running-your-app) boilerplate from official documentation and ran starting script, unfortunately, the bash output is same and facing the same futex error.
```bash
🔥➜electron-quick-start git:(master) npm start

> electron-quick-start@1.0.0 start /home/bisakh/Desktop/Electron/electron-quick-start
> electron .

The futex facility returned an unexpected error code.
```
It seems like a multithreading error, haven't found any solution yet. Any help will be highly appreciated.
* **Electron Version:**
  * 9.0.4
* **Operating System:**
  * Ubuntu 20.04 LTS x86_64
* **Last Known Working Electron version:**
  * __

### To Reproduce

```bash
# Clone the repository
git clone https://github.com/electron/electron-quick-start
# Go into the repository
cd electron-quick-start
# Install dependencies
npm install
# Run the app
npm start
```

**Comment by ckerr** [comment] 2020-06-22 19:48
That's really strange; I'm not able to reproduce this issue.

When I clone electron-quick-start and run, I get the usual window saying:

> We are using Node.js 12.14.1, Chromium 83.0.4103.104, and Electron 9.0.4.

Same setup as described in this report:

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID:  Ubuntu
Description:  Ubuntu 20.04 LTS
Release:  20.04
Codename:  focal

$ uname -m
x86_64
```

@bisakhmondal, since I'm unable to reproduce this issue I'm going to mark it as blocked. If you find more information on how to reproduce the issue, please add it in-ticket. Thank you!

**Comment by bisakhmondal** [comment] 2020-06-23 07:49
Hey @ckerr, Thanks for the reply. You are actually right, it can't be reproduced in default bash terminal in Ubuntu. I also just did the same now and it's working. But the error is still thrown in the Visual Studio Code(VSCode) integrated terminal which I was using earlier. Should the issue be closed?

**Comment by szkrd** [comment] 2020-07-04 13:55
This happened to me when I tried to run an electron app without env vars "or anything" (in `env -i bash --noprofile --norc`), not sure if it helps or if it makes reproducible, but seeing the _integrated terminal_ above, this may be a clue.

**Comment by ktorn** [comment] 2020-08-14 15:34
I also ran into this issue, temporarily, but having "fixed it" now I also can't replicate it.

Originally I was trying to start electron on a remote raspberry pi, via SSH, logged in to a user other than the one running the desktop. That is when I got the `The futex facility returned an unexpected error code.`

When I rectified the issue, by starting the app directly on the desktop it worked first time.

Now I'm trying to replicate the original issue but can't.

I'll leave these details here in case it helps troubleshooting.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

$ uname -m
armv7l

$ node -v
v12.18.3

$ npm -v
6.14.6

$ electron -v
v9.2.0
```

**Comment by matti** [comment] 2020-10-11 12:03
for me it was fixed with DISPLAY=:0 missing

**Comment by pedrorenan** [comment] 2020-10-24 23:05
> for me it was fixed with DISPLAY=:0 missing

Where did you set DISPLAY=:0 ?

**Comment by matti** [comment] 2020-10-25 14:20
env variable DISPLAY

**Comment by pedrorenan** [comment] 2020-10-26 01:36
> env variable DISPLAY

Thanks, works fine for me.

**Comment by markdeloura** [comment] 2020-12-19 01:24
I was getting this same error using WSL2 in Windows10, and adding a DISPLAY environment value in bash ("export DISPLAY=192.168.1.10:0") and starting up an Xwindows server on the Windows side solved the problem.

**Comment by ksauzz** [comment] 2021-02-18 01:23
I faced the same issue on Ubuntu 20.04 w/ ssh remote login. My workaround is: 

`DISPLAY=:44 xvfb-run --server-num 44 electron <args>`

**Comment by musicjeremy** [comment] 2021-02-21 02:34
> I faced the same issue on Ubuntu 20.04 w/ ssh remote login. My workaround is:
> 
> `DISPLAY=:44 xvfb-run --server-num 44 electron <args>`

Thank you, this worked for me, Ubuntu 20.04 with ssh remote login.
To be clear I ran:

export DISPLAY=:44
xvfb-run --server-num 44 electron <args>

**Comment by mwoodpatrick** [comment] 2021-02-27 12:22
I saw the same issue when running my electron app under WSL-2, same solution but with my X based VNC server running in a container

**Comment by electron-triage** [comment] 2021-03-09 16:20
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 16:20 UTC
Labels: 9-x-y, blocked/need-repro, bug/crash :boom:, platform/linux

**Comment by bblanke** [comment] 2021-05-10 15:35
I had this issue while running Electron within a docker container with X11 installed in the container.

I needed to: 
* ensure the `DISPLAY` environment variable was set (`export DISPLAY=:0`)
* Make sure X11 was allowing electron to use the display server (`xhost local:` allows all local users to use X11)
