### ISSUE TITLE
[Bug]: App crashes when unloading webview before it finished rendering since Electron 26.1.0

### ISSUE THREAD

**Issue by wartab** [electron/electron#40288] opened 2023-10-20 10:25 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

26.0.0

### Expected Behavior

The application should just move on and not crash.

### Actual Behavior

The application closes without any error message shown or logged.

### Additional Information

Unfortunately, we didn't have enough time to investigate on our customer's computer. The computer was very slow and took several seconds to render a webview. So we cannot really provide a concise reproduction, as we cannot manage to replicate the slowness of the rendering.

However, I managed to narrow down the issue fairly well, as it only happens in the following situation:
- Electron 26.1.0 or higher (including Electron 27). Electron 26.0.0 isn't affected, nor is 25.
- It was on Windows 10 on a slow computer.
- We render a webview. Not sure if relevant, but the src attribute isn't a regular URL but is a data URL starting with `data:text/html;charset=utf-8,<lots of HTML>`.
- The webview remains white for several seconds, because the computer seems to be slow to render that HTML.
- We unload the webview before it rendered anything.
- The application crashes.
- There is no error message anywhere, even if we run the application from command line.

Let me know if there's anything I can do to help.

**Comment by jpschw** [comment] 2023-10-20 15:19
Bump. This is crashing our application as well since this version. Anything loaded in a <webview> crashes the client.

**Comment by wartab** [comment] 2023-10-30 19:45
Not really possible, given the circmustances of what happens. We could only reproduce it on our machines by running the CPU stress test software Prime95 at levels that would even make Windows bluescreen a few minutes later.

**Comment by jkleinsc** [comment] 2023-10-30 19:56
Given that there isn't a reproducible test case, there really isn't any way for this issue to be addressed, so I am going to go ahead and close this issue.

**Closed by jkleinsc** 2023-10-30 19:56 UTC
Labels: bug :beetle:

**Comment by wartab** [comment] 2023-10-30 20:00
The fact I didn't narrow it down to a specific minor version having caused this isn't helping at all?
