### ISSUE TITLE
[Bug]: load custom chrome extensions will crash

### ISSUE THREAD

**Issue by liangxiwei** [electron/electron#33149] opened 2022-03-04 09:36 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

macOS

### Operating System Version

Darwin bogon 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

### What arch are you using?

x64

### Expected Behavior

will load my chrome extensions sucess

### Actual Behavior

crash.

### Additional Information

debug log is :
xproject/make-user/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGTRAP
[64831:0304/172814.745000:ERROR:mach_port_rendezvous.cc(310)] bootstrap_look_up com.github.Electron.MachPortRendezvousServer.1: Permission denied (1100)

[64832:0304/172814.751833:ERROR:mach_port_rendezvous.cc(310)] bootstrap_look_up com.github.Electron.MachPortRendezvousServer.1: Permission denied (1100)

[64832:0304/172814.752886:ERROR:child_thread_impl.cc(226)] Mach rendezvous failed, terminating process (parent died?)
xproject/make-user$[64831:0304/172814.978933:ERROR:child_thread_impl.cc(226)] Mach rendezvous failed, terminating process (parent died?

**Comment by codebytere** [comment] 2022-03-07 17:12
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-03-17 18:02
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-03-17 18:02 UTC
Labels: bug :beetle:, blocked/need-repro
