### ISSUE TITLE
macOS: "PageUp" and "PageDown" menu item shortcut indicators are visually too similar to "Up" and "Down"

### ISSUE THREAD

**Issue by MarcelGruenauer** [electron/electron#23376] opened 2020-05-01 09:04 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
When using an app built with Electron (https://github.com/SabakiHQ/Sabaki) I noticed that the way some keyboard shortcuts are displayed is a bit confusing.

See the attached screenshot of the "Navigation" menu. It took me a long time to realize that these are different shortcuts and not the same shortcut used for two items. The shortcuts in the upper circled area are `CmdOrCtrl+Up` and `CmdOrCtrl+Down`; the ones in the lower circled area are `CmdOrCtrl+PageDown` and `CmdOrCtrl+PageUp`.

Also when using a shortcut like `CmdOrCtrl+Shift+1`, it renders as `⌘!`, not as `⌘⇧1`. This is just a minor thing, but I find `⌘⇧1` clearer than `⌘!`.

<img width="261" alt="80763099-11239800-8b3e-11ea-944c-fa851b94ee0e" src="https://user-images.githubusercontent.com/60425018/80794748-ff241280-8b9a-11ea-9873-262f53f0b3b1.png">

Thank you!

**Comment by miniak** [comment] 2020-05-21 06:59
I can reproduce this in a native application using XCode as well. It looks like macOS behavior. Electron cannot do anything about it. Closing.

**Closed by miniak** 2020-05-21 06:59 UTC
