### ISSUE TITLE
saveDialog should list available extensions

### ISSUE THREAD

**Issue by juliangruber** [electron/electron#10335] opened 2017-08-23 10:09 UTC
* Electron version: 1.7.5
* Operating system: macOS Sierra 10.12.6

### Expected behavior

When creating a `saveDialog` with multiple extensions configured in `.filter`, the dialog should allow the user to pick an extension, like here:

![screen shot 2017-08-23 at 12 07 51](https://user-images.githubusercontent.com/10247/29610825-b547ffe6-87fb-11e7-927b-8a8311ff2ef7.png)

### Actual behavior

There is no extension picker:

![screen shot 2017-08-23 at 12 08 13](https://user-images.githubusercontent.com/10247/29610844-c510b706-87fb-11e7-88b7-37952d66ec25.png)

### How to reproduce

```js
const { dialog } = require('electron').remote

dialog.showSaveDialog({
  filters: [
    { name: 'M3U8', extensions: ['m3u8'] },
    { name: 'PLS', extensions: ['pls'] }
  ]
}, filePath => {})
```

**Comment by zeke** [comment] 2017-09-08 14:55
Possible duplicate of https://github.com/electron/electron/issues/10335

**Closed** 2018-02-11 04:32 UTC
Labels: platform/macOS, triaged/bug, version/1.7.x
