### ISSUE TITLE
Transparent window has white background window

### ISSUE THREAD

**Issue by delvedor** [electron/electron#2170] opened 2015-07-09 12:47 UTC
Hi, I've some issue with the transparent window, my code is:
```javascript
win = new BrowserWindow({
  width: 100,
  height: 50,
  transparent: true,
  frame: false
});
```
On Mac I have not any kind of problem, on my Windows 7 Parallels virtual machine again no problem, but on another pc (not virtualized) with Windows 7 transparent windows doesn't work (I have a white background).

I haven't error logs from console.
In both Windows 7 machines I have DWM enabled and running (in fact, both are using aero).

**Comment by zcbenz** [comment] 2015-07-10 05:26
This is usually related to hardware, can you open the `chrome://gpu` url on each machine and compare the results?

**Comment by delvedor** [comment] 2015-07-10 08:25
*Graphics Feature Status* - exactly the same in mac, windows virtualized (via parallels) and windows pc.
*Driver Bug Workarounds* - the same in both windows machine, different in mac
*Problems Detected* - the same in both windows machine, different in mac
*Version Information & Driver Information* - similar but changes some parameters in every machine, like GPU0, Sanboxed, Driver version/vendor.

If you want I can provide you more accurate screenshots.

**Comment by zcbenz** [comment] 2015-07-10 08:47
I think it is a bug of Chrome's rendering code, and it should be GPU/hardware related. I'm afraid we can not fix it on Electron's side.

**Comment by delvedor** [comment] 2015-07-10 08:56
Ok, so your advice is to wait for the next versions of Chrome?

**Comment by delvedor** [comment] 2015-07-10 12:52
I have an update, that's strange.

On the virtualized Windows, as you know is all ok, but on the pc if the window is at least *160x80 pixels*, the transparent option works.

In my specific case, *100x50px* is the standard size of my window, I increase the dimensions by *12x5px* every time I click on my own button by using 
```javascript
win.setSize(x, y);
````
Recap:
dimension < 160x80px : *white background*
dimension >= 160x80px : *transparent background*

**Comment by ankitaggarwal011** [comment] 2015-07-10 17:35
I can confirm this on my windows 7(x64) machine as well. When the transparent flag is set to true.
Just as @delvedor said, for,
dimension < 160x80px : white background
dimension >= 160x80px : transparent background

**Comment by Auxolust** [comment] 2015-09-03 20:11
I came across this recently as well, and I've fiddled with the height and width to try see what happens. Turns out that if both width and height values are smaller than 160, you will see the white screen, ie 

159 x 159 = white screen 

However if at least one value is >= 160 than it will be transparent, so

160 x 1 = transparent
1 x 160 = transparent

I tried to see if re-sizing  the browser window programmatically might help, but it doesn't, although I did see that it adds the white background behind the window. If you are using a background of say rgba(0,0,0,0.2) you will see it will be discoloured because of the white window behind it

**Comment by frankhale** [comment] 2015-09-03 20:16
This is most likely related to this issue: https://github.com/atom/electron/issues/861

**Comment by KevinMartin** [comment] 2015-10-06 17:29
I'm on the latest Electron (v0.33.6) and on Yosemite. It works fully for me... I instantiate the window like so:

```js
        const window = new BrowserWindow({
                width,
                height,
                'node-integration': true,
                frame: false,
                transparent: true
        });

        window.loadUrl('http://localhost:8002' + uri);
        window.openDevTools();
```

The only flaw I see is when I open Dev Tools, the background is white until I close it, then it becomes transparent.

**Comment by KevinMartin** [comment] 2015-10-06 17:36
Just realized this seems to be an issue with Microsoft Windows

**Comment by delvedor** [comment] 2015-10-06 17:38
@KevinMartin yes, it is!

**Comment by alexgleason** [comment] 2015-10-06 17:45
Also having this problem on Linux. I'm just trying to do a "Hello world" with transparent bg to see if it works, but I'm getting a white background. Can someone post a full index.html and main.js file that works on their machine so I can test to make sure I'm not doing something wrong?

Here's what I have.
[main.js](http://pastebin.com/3LKGLUQV)
[index.html](http://pastebin.com/kUZU2ReC)

Thanks!

I'm on elementary OS Freya 64-bit. It's an Ubuntu 14.04 based distro running GTK3.

**Comment by ishankhare07** [comment] 2016-02-18 13:37
i have the same problem on ubuntu linux

**Comment by zcbenz** [comment] 2016-05-06 10:23
This issue is deeply related to the hardware and drivers, we are not able to solve this on Electron's side, so I'm closing this as won't fix. For people troubled with this issue, the only suggestion I can give is to wait for upgrades of Chrome and see if it can fix this.

**Closed by zcbenz** 2016-05-06 10:23 UTC
Labels: blocked, bug, machine-dependent, transparent-window

**Comment by PaulBGD** [comment] 2016-11-08 07:54
Is it possible to reopen this? I'm experience unique problems on the Cinnamon desktop with Ubuntu 16.04 running the latest NVIDIA drivers.

Example:
![Image](https://i.imgur.com/1dAhkIM.png)

How it should look
![Should](https://camo.githubusercontent.com/80baf3b156d81b618a0fb27c39251a93a0f32599/68747470733a2f2f692e696d6775722e636f6d2f505161586d6c782e706e67)

**Comment by madipor** [comment] 2016-12-27 14:53
Hi, 

I have the same problem, there is white background.
Windows Express 2008 R2 
Electron version: 1.4.12

```
win = new BrowserWindow(
{ height: 161, width: 81, show: false, frame: false, transparent: true, resizable: false}
);
```

I tried almost everything
any idea??

![image](https://cloud.githubusercontent.com/assets/10109614/21501880/573cb8aa-cc54-11e6-90d1-d271fa0621f2.png)

**Comment by jfgilliam** [comment] 2016-12-27 15:06
I can get transparency to work if I create the window, wait a few seconds for it to render, then move it a little bit.

**Comment by madipor** [comment] 2016-12-27 17:15
@jfgilliam what do you mean when you say "move it a little bit"? 
change the window position?

**Comment by jfgilliam** [comment] 2016-12-27 17:36
Yes. Create the window where you don't want it. Then move it. The key is to wait until it renders.

- Jeff

**Comment by davydka** [comment] 2017-03-31 16:15
I was having this issue as well on 1.6.2. Using Electron 1.4.14 solves it. I'm running Xbuntu 14.04.

**Comment by samkelly** [comment] 2017-04-01 15:48
@davydka I can confirm this issue as well on vanilla Ubuntu 16.04. Switching back to 1.4.14 solves it. Out of curiosity, do you have UI-scaling enabled on your OS? I noticed that when I downgraded back to 1.4.14 the scaling on my whole electron window changed, so maybe this bug is caused by 1.6.2 trying to respect linux ui scaling parameters, but messing up transparency in the process? In my case, I do have ui scaling enabled at 1.25x.

**Comment by optimisme** [comment] 2017-04-07 09:38
Yes, it works on 1.4.14 but does not work on 'latest' version. 
Also the argument ' --enable-transparent-visuals' is needed.
I am using electron on Fedora 25 with open source NVIDIA drivers.

**Comment by samkelly** [comment] 2017-04-07 20:01
@optimisme in your case, does os-level UI scaling have anything to do with it?

**Comment by Sential** [comment] 2017-04-07 20:41
Will be the issue fixed in 1.6.x? I don't want to downgrade to 1.4.x, because I'm making a web browser, which requires the newest Chromium.

**Comment by samkelly** [comment] 2017-04-07 20:45
this should be a high priority issue IMO as it breaks existing behavior that a number of programs rely on

**Comment by davydka** [comment] 2017-04-10 18:30
@samkelly Sorry for the delay. I'm not using any  UI scaling. In xfce I checked Settings Editor-> xsettings –> Xft -> DPI and my value is -1. I

**Comment by CharlSteynberg** [comment] 2017-04-16 23:02
Same problem here.

Using:
- hardware: HP laptop (no special GPU)
- OS: openSUSE
- electron: v1.6.2

**Comment by optimisme** [comment] 2017-04-19 06:11
@sam0x17, no scaling with my hardware/software

**Comment by sam0x17** [comment] 2017-04-19 16:02
ok, scaling probably unrelated, then

**Comment by kevinsawicki** [comment] 2017-04-27 18:44
> Yes, it works on 1.4.14 but does not work on 'latest' version.

Can people reporting it working in 1.4.14 give this comment a 👍  if it is still working in 1.4.15  and a 👎 if it isn't working in 1.4.15?

I'm trying to narrow down whether this regressed because of an Electron change or because of a Chrome upgrade, thanks.

**Comment by Sential** [comment] 2017-04-27 20:44
@kevinsawicki it is working even on 1.4.16.

**Comment by kevinsawicki** [comment] 2017-04-27 20:46
@Sential okay, so you only start seeing issues in 1.5.x and 1.6.x?

**Comment by Sential** [comment] 2017-04-27 20:50
On Electron 1.4.x I have another issue with transparency on Debian 8 Jessie and Gnome 3.14. I have added `--enable-transparent-visuals` option.

![screen](http://i.imgur.com/gPFmYr1.png)

**Comment by davydka** [comment] 2017-04-27 20:58
Ok, just tried 1.4.15, and 1.4.16 and it's working when using `--enable-transparent-visuals`.
On 1.5.x it starts to no longer shows transparency.

**Comment by egordorichev** [comment] 2017-05-01 06:57
Same thing: 

```js
new BrowserWindow({
width: 800, 
height: 600, 
transparent: true,
frame: false })
```

And white back.

**Comment by xkisu** [comment] 2017-05-23 06:08
Can confirm that >1.4.16 transparency is broken. Running a custom Ubuntu 16.4 distro, I tried tons of stuff like window sizing, type, etc. but the only thing that fixed it was downgrading to 1.4.16.

**Comment by DaniGuardiola** [comment] 2017-08-15 12:10
Hey, I'm having this issue as well. This is blocking for my project, any news?

**Comment by sam0x17** [comment] 2017-08-17 09:51
We are still locking to 1.4.16 because of this issue. Has someone taken this up with the chromium team?

**Comment by DaniGuardiola** [comment] 2017-08-17 14:52
Same here, would appreciate some news

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by davydka** [comment] 2017-08-22 00:14
Sounds like we need more **transparency**.

**Comment by sam0x17** [comment] 2017-08-22 04:32
This issue should not be closed

**Comment by gabrielstuff** [comment] 2017-09-21 22:33
Yes, since 1.4.16 transparency is broken.... issue should stay open @zcbenz

**Comment by verashira** [comment] 2017-10-02 11:31
Does not seem to be fixed with most recent beta v1.8.1.

**Comment by sam0x17** [comment] 2017-10-03 09:18
It's a bit frustrating that electron used to be advertised as the only cross platform desktop app framework that supports translucency, and has now marked that feature with a `wontfix` :/

We are still locking to the old version

**Comment by gabrielstuff** [comment] 2017-10-04 10:42
Would be nice to hear someone from Electron team tell us what they think. Apparently it has been work on it in 2016 with https://bugs.chromium.org/p/chromium/issues/detail?id=589509. It was in June, just after the ticket has been marked as `wont-fix`. 

It appears that it should work on the os. I'm going to test latest chrome and report.

Thanks

**Comment by sidneys** [comment] 2017-11-12 17:50
This issue should be resolved soon, it makes Linux a broken Electron platform for many application concepts requiring transparency effects.

**Comment by sam0x17** [comment] 2017-11-12 19:46
@zcbenz this should be a top priority right now as there are now a number of major companies locking the electron versions for their desktop apps to 1.4.16 -- please see @gabrielstuff's comment above as it sounds like the Chrome team has a fix for this, in which case we can finally resolve this

**Comment by palyga** [comment] 2017-11-15 16:48
Hi, I had the same issue in Ubuntu 16.04 with electron - "1.7.8", electron-builder - "^19.45.4", I fixed it by adding options `--enable-transparent-visuals --disable-gpu` to Exec in my *.desktop file.
Now  "Exec" in my desktop file look like `"/opt/StepShot Guides/StepShot Guides" --enable-transparent-visuals --disable-gpu %U`. 
This article helped me to solve the issue https://www.techiediaries.com/github-electron/how-to-make-a-transparent-window-with-github-electron/

**Comment by sam0x17** [comment] 2017-11-16 05:10
@palyga Yes I am aware of the `--enable-transparent-visuals --disable-gpu` trick. AFAIK this was always required to get this to work, but has been broken since 1.4.17. Is this suddenly working in 1.7.8????

**Comment by zcbenz** [comment] 2017-11-20 01:56
The ability of transparent window is provided by Chromium, but they never officially supported this feature, so we have to patch Chromium on our side to make transparent window work.

But with the complex GPU rendering of Chromium, making the browser window transparent is really very hard work, and requires related knowledge and plenty of time to make things work perfectly. Unfortunately we don't have those resources in Electron team.

**Comment by zcbenz** [comment] 2017-11-20 01:59
As for the fixes in Chromium, we already have them in Electron, but transparent window has never been an official feature of Chromium, they did not do much tests and they do not guarantee it would work.

**Comment by DaniGuardiola** [comment] 2017-11-20 12:05
@zcbenz well, as one of the most important projects making use of the Chromium project, given the rising amount of support for this feature, I figure you can at least raise the concern to the Chromium team and try to collaboratively work on a good fix for the issue.

This is blocking to many projects and teams, including mine and some big ones like the Slack desktop app which is widely used.

I think I speak for everyone on this issue when I say that I believe this deserves more attention. It is a big headache for tons of devs.

To share my case, I had to halt development of my project, which was pretty serious and has a working MVP, because I realized this bug was being postponed and no information was given, without known efforts or steps taken to progress on it.

I know it is not trivial and than it depends a lot of the Chromium team, but we would appreciate if the electron team raised the issue "officially" to Chrome, as the support for this feature from your users has been clearly expressed in these comments.

At the very least, we would like to know if this will ever be considered or if we should just move to NWJS to at least be able to ship our products instead of changing or cancelling them due to limitations.

I hope my concerns don't come as inconsiderate, I have a huge respect for the electron dev team, I'm just frustrated that there are no known steps being taken and no one is taking our issue seriously.

Hopefully, if you talk to the Chromium team, they will give official support to transparency and work with you on it. It's probably almost trivial to them. They just need to know this is something serious to a lot of their users (through the electron platform).

Thank you and good day :)

**Comment by justUmen** [comment] 2017-12-05 13:36
The lack of an official answer is indeed frustrating. 
I've migrated to NWJS for this exact reason. 
Sadly, I can't use and/or recommend Electron until this is resolved.
Good day all. :)

**Comment by davydka** [comment] 2017-12-05 14:38
@justUmen Just curious but since the problem stems from Chrome, doesn't the same issue affect NW.js? If not then I'll definitely be switching on future projects.

**Comment by justUmen** [comment] 2017-12-05 17:23
I'm just a user, I have no idea where the problem come from.
All i can say is that : I have no transparency problem with the last nw.js and my custom browser.
`nw.js v0.26.6`
`Node v9.1.0`
`Chromium 62.0.3202.94`
I don't even know what chrome version Electron is using now, but isn't 62.0.3202 the last stable ?

**Comment by justUmen** [comment] 2017-12-05 17:31
I'm just a user, I have no idea where the problem come from.
All i can say is that : I have no transparency problem with the last nw.js and my custom browser.
`nw.js v0.26.6`
`Node v9.1.0`
`Chromium 62.0.3202.94`
I don't even know what chrome version Electron is using now, but isn't 62.0.3202 the last stable ?

**Comment by justUmen** [comment] 2017-12-05 17:37
It's just on my system, i have used https://dl.nwjs.io/v0.26.6/nwjs-v0.26.6-linux-x64.tar.gz.
But I didn't try in a clean environment.

**Comment by gabrielstuff** [comment] 2017-12-05 21:52
From https://nwjs.io/blog/v0.26.0/, `nw.js` is using `Chrome 62.0.3202.62`. The thing is that nw.js use a custom build of Chromium see for instance https://github.com/nwjs/chromium.src/pull/97/commits/6b98d3a1a5aba6980edb95fc8c0db24132c87a5a where Electron is using a part of Chromium Render not touched: https://electronjs.org/docs/tutorial/about#core-philosophy

It might come from there.

**Comment by davydka** [comment] 2017-12-05 22:05
I've been sticking with electron@1.4.6 and that is using Chrome 53.0.2785.143.

**Comment by rewhex** [comment] 2018-01-03 22:21
okay, finally I found a solution! Using latest electron version and this code in main proccess transparency works fine in all windows:

```
const {app, BrowserWindow, protocol} = electron

app.disableHardwareAcceleration()

app.on('ready', () => {
  protocol.unregisterProtocol('', () => {
    new BrowserWindow({
      width: anysize,
      height: anysize,
      frame: false,
      transparent: true
    })
  })
})
```

I don't know what protocol.unregisterProtocol does, but with him, transparency working fine.
Who knows if it's bad, please tell me about it.

**Comment by sam0x17** [comment] 2018-01-05 00:46
@rewhex so this works on linux?

**Comment by rewhex** [comment] 2018-01-05 00:53
@sam0x17 yes, i'm using openSUSE, works fine.

**Comment by bundyo** [comment] 2018-01-05 11:45
Probably needs sufficient time to disable the acceleration. We're not using unregisterProtocol, but we have a sufficiently long init, it seems, so transparency works on openSUSE too.

**Comment by rewhex** [comment] 2018-01-05 13:22
@bundyo so, unregisterProtocol in my example, just make more time for new BrowserWindow?

**Comment by bundyo** [comment] 2018-01-05 13:47
This is just a guess, since it works here without it.

**Comment by rewhex** [comment] 2018-01-05 15:36
@bundyo true, i see, using setTimeout in 10 ms, transparency works.

**Comment by madipor** [comment] 2018-01-07 09:51
@rewhex  Did you try this for Windows Server 2008 R2?

**Comment by rewhex** [comment] 2018-01-07 09:58
@madipor , no, i have only openSUSE os.

**Comment by stepanvanzuriak** [comment] 2018-01-09 11:08
Tested  @rewhex solution on https://github.com/zeit/hyper/pull/2571 and it works without `app.disableHardwareAcceleration()`

**Comment by Himujjal** [comment] 2018-01-21 18:54
```
let mainWindow
app.disableHardwareAcceleration();

function createWindow () {
  protocol.unregisterProtocol('',()=>{
    mainWindow = new BrowserWindow({
      width: 200, 
      height: 250,
      transparent: true,
      frame: false,
      show: false
      })
  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))
  mainWindow.on('closed', function () {
    mainWindow = null
  })
  setTimeout(() => {
    console.log('The window will now show up')
  }, 2000);
  mainWindow.once('ready-to-show',()=>{
    mainWindow.show()
  })
  })
}
app.on('ready', createWindow)

```

The above is my code for a simple window. 

I also tried `--enable-transparent-visuals --disable-gpu`. But to no avail. 

I am currently using the following machine configuration:
```
Windows 7 x64 (VirtualBox Windows)
RAM: 2048
Graphics: No Graphics acceleration in VirtualBox
Electron 1.4.14 --global
Electron 1.4.14 --local 
```
Please help me! My client is gonna kill me. This is the only problem left to solve.

And also its working damn fine in my Windows 10 PC with the latest version of Electron.

**Comment by xkisu** [comment] 2018-01-21 19:07
@Himujjal It's probably because your in VirtualBox with graphics acceleration disabled. Transparent stuff like this normally uses graphics acceleration for the transparency 😉

**Comment by DaniGuardiola** [comment] 2018-01-30 10:25
Can confirm transparency workaround works for latest version:
```javascript
app.on('ready', async () => {
  await Promise.delay(10) // transparency workaround
  await createMainWindow()
})
```

**Comment by hesus123** [comment] 2018-02-14 22:39
For me the problem was with the developer console, is the app starts with the developer console active just comment this line win.webContents.openDevTools()

**Comment by sam0x17** [comment] 2018-02-18 05:31
@hesus123 yes having dev console open will disable translucency.

**Comment by VinceOPS** [comment] 2018-03-09 23:12
I can confirm the fix using `app.disableHardwareAcceleration();` and a "delayed" creation of BrowserWindow. In my case, I simply used:

```typescript
setTimeout(createWindow);
```

Debian Stretch (9.3) running on a Dell XPS 13 (9370) with Electron 1.8.3.

**Comment by sam0x17** [comment] 2018-03-10 15:26
Yes, ironically hardware acceleration would probably help a lot with the rendering of a translucent window

**Comment by alexcroox** [comment] 2018-03-11 11:29
I didn't need to `disableHardwareAcceleration()`, just needed to add a long enough delay before creating the window `setTimeout(() => {..}, 100)`. 

`10` was too short a lot of the time, `100` has been working reliably on both macOS and Linux.

**Comment by mncharity** [comment] 2018-03-19 22:45
I confirm @alexcroox .  Current electron-quick-start (electron 1.8.4) on Ubuntu 17.10 and Intel HD Graphics 520.  Simply doing `transparent:true` and `app.on('ready', () => { setTimeout(createWindow, 100) })` works.  And `10` ms doesn't.   No hardware deceleration needed.  Thank you!!!

**Comment by natew** [comment] 2018-03-20 17:25
Not sure exactly which version, but I have a new behavior now where the dev tools turns it white, but turning off devtools keeps it white.

Also if a chrome remote instance connects with screensharing, the same bug triggers.

**Comment by kabalage** [comment] 2018-06-20 12:44
I too experience this problem. I'm using `electron@2.0.2` in arch linux with compton compositor.
Transparency only works if I call `app.disableHardwareAcceleration()` and delay window creation  
with `app.on('ready', () => setTimeout(createWindow, 100))`. If any of these is missing, the background is black and does not get updated, previously rendered frames are visible.

The problem is that animations are janky without hardware acceleration.

**Comment by DaniGuardiola** [comment] 2018-06-20 13:20
I created a bug in Chromium's bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=854601

I'd appreciate if you can chime in, star the issue and share your information there so that we can help them solve this.

The more support and information we give, the better. Just remember not to spam with "+1" comments, that's what the stars are for.

Now go!

**Comment by DaniGuardiola** [comment] 2018-06-20 13:21
PD: if someone is able to create a self-contained and minimal example that replicates this bug with the latest version of Electrum (that should contain the latest used version of Chromium), that would be very helpful to the Chromium devs!

**Comment by kabalage** [comment] 2018-06-20 20:43
@DaniGuardiola I created an example demonstrating the issue (https://github.com/kabalage/electron-transparency-issue) and also posted it in the Chromium bug tracker. Thank you for helping.

**Comment by DaniGuardiola** [comment] 2018-06-22 19:35
The issue has been reproduced by the Chromium team! https://bugs.chromium.org/p/chromium/issues/detail?id=854601#c7

I suggest everyone interested in an official fix by the Chromium team to go and start the project, and offer any relevant information you have. That will give the bug more visibility!

**Comment by durasj** [comment] 2018-08-14 13:49
Hi @zcbenz, the Chromium team [responded in the issue](https://bugs.chromium.org/p/chromium/issues/detail?id=854601#c21) with

> Chromium should support transparency, provided you pick a rgba visual (which is somewhat non-trivial, but [see how it's done here](https://cs.corp.google.com/clankium/src/ui/views/widget/desktop_aura/desktop_window_tree_host_x11.cc?q=DesktopWindowTreeHostX11::InitX11Window&dr=CSs&l=1450)), and that you have a compositing manager of course.

>I have no idea how electron sets up its window, so I don't know if it's actually hooked up properly or not.

Do you think there is any chance you could help them figure it out from the Electron side?

Thank you

**Comment by Sombian** [comment] 2018-11-13 07:58
still not fixed.

**Comment by eNzyOfficial** [comment] 2018-12-14 08:32
> I too experience this problem. I'm using `electron@2.0.2` in arch linux with compton compositor.
> Transparency only works if I call `app.disableHardwareAcceleration()` and delay window creation
> with `app.on('ready', () => setTimeout(createWindow, 100))`. If any of these is missing, the background is black and does not get updated, previously rendered frames are visible.
> 
> The problem is that animations are janky without hardware acceleration.

Still not fixed, this worked for me

**Comment by Airwiq** [comment] 2019-01-11 09:59
Got another workaround without disabling the hardware acceleration^^
I found out that it has something to do with the main window and all windows created in the backend JS file.
I’ve managed to get transparency when opening a window with the default “window.open(…)” in the html page within my main window and catching the event in the backend JS. All electron BrowserWindow instances created in the event listener are all able to obtain transparency, except when the devTools are being used.

```
win.webContents.on('new-window', (event, url, frameName, disposition, options, additionalFeatures) => {
        event.preventDefault();
        // create your BrowserWindow here :)
});
```

**Comment by sam0x17** [comment] 2019-01-11 20:32
@Airwiq that's great, and yes the devtools thing is consistent with my experience. If devtools is open it's impossible to have translucency.

**Comment by doom-fr** [comment] 2019-01-15 11:37
For me, I have to set wait delay up to 300ms !!

Have requested an event on this. https://github.com/electron/electron/issues/15947

**Comment by vifird** [comment] 2019-06-22 19:06
I still have this problem, and it's worse for me. I got a whole black window when start, i have tried `setTimeout`,`--enable-transparent-visuals --disable-gpu`,`disableHardwareAcceleration`, but nothing works for me, in other cases, i got half black window(half is transparent).
`Electron`: `6.0.0-beta.5`;
`OS`: Window10(64bit), Window7(32bit in VM)
![image](https://raw.githubusercontent.com/vifird/assets/master/imgs/2019-06-22%20am.3.02.02.png)  
![image](https://raw.githubusercontent.com/vifird/assets/master/imgs/2019-06-23%20pm.3.02.02.png)

**Comment by doom-fr** [comment] 2019-06-22 19:59
Have you tried to add a huge wait (at least 500ms) before creating you window
https://stackoverflow.com/a/54784577/1619521

What's the behavior if you clone [this repo](https://gitlab.com/doom-fr/electron-transparency-demo
) and set delay to 0ms, 100ms and 500ms ?

**Comment by vifird** [comment] 2019-06-23 06:17
@doom-fr 
When the parameter `frame` was `true`, i got two state of the window. State 1: at the beginning, the window was transparent; State2: after about 1000ms later, the window turned into black. I didn't load the html, so the window was empty; and this happened when i runed `start` and `startWithTransparentOption`, while `startWithAllOptions` directly leaded the window to be black.

When the parameter `frame` was `false`, i got a white window directly. no mater what the script was.

**Comment by doom-fr** [comment] 2019-06-23 08:34
Have you try to downgrade electron, for example to version 4.* ?

**Comment by vifird** [comment] 2019-06-23 13:55
@doom-fr Yeah ,i did. the vertion of `electron` is `4.2.5`.

**Comment by doom-fr** [comment] 2019-06-23 14:18
@vifird Try to set wait to 3000 ms.
(I know, this is not acceptable, but it is just for test purpose)

Remember to test `npm start` and `npm run startWithTransparentOption` and `npm run startWithAllOptions`
Maybe try also to put back the load of the html.

**Comment by fengerzh** [comment] 2019-12-27 10:12
This issue should not be closed, please reopen it again, thanks!

**Comment by doom-fr** [comment] 2019-12-27 10:52
If waiting 3000ms before creating the window fixes your problem 
> Have you tried to add a huge wait (at least 500ms) before creating you window
> https://stackoverflow.com/a/54784577/1619521
> 
> What's the behavior if you clone [this repo](https://gitlab.com/doom-fr/electron-transparency-demo) and set delay to 0ms, 100ms and 500ms ?

Then this issue is the good for you :
https://github.com/electron/electron/issues/16809

**Comment by liuzhenyilang** [comment] 2020-03-02 09:48
The opposite happened to me, windows 7 pro, the app window is transparent when started.

**Comment by vkolova** [comment] 2020-03-03 13:02
No amount of waiting fixes the problem for me. Using latest version of Electron on Windows 10.

**Comment by cookmscott** [comment] 2020-06-23 14:11
I played around with a lot of these options on Windows 10, Electron v8 and found that transparency worked when I launched the application without dev tools or launched with dev tools undocked
ex: `openDevTools({mode:'undocked'})`

**Comment by embu18** [comment] 2020-09-26 17:52
Same issue on linux. Transparency not working and it's not related to window size.

**Comment by arnabuchiha** [comment] 2020-10-08 18:46
Its been 5 years but still it couldn't be fixed. 😿

**Comment by andredezzy** [comment] 2020-12-01 05:13
If somebody with the same issue, the only way I found to solve, is disabling hardware acceleration.

```js

app.disableHardwareAcceleration();

app.on('ready', () => {
  setTimeout(() => {
    createWindow();
    autoUpdater.checkForUpdatesAndNotify();
    createMenu();
  }, 50);
});
```

I hope helped somebody...

**Comment by serban-mihai** [comment] 2021-01-04 21:50
> `app.disableHardwareAcceleration();`
> Timeout to `50`

@andredezzy you're my hero, give this guy a beer! 🍺 

Tested and working on Linux Mint 20 with XFCE and `"electron": "^11.1.0"`

**Comment by doom-fr** [comment] 2021-01-05 13:27
Be careful, the wait delay seems to depend of the platform.
So an event triggering is needed : https://github.com/electron/electron/issues/16809

**Comment by bundyo** [comment] 2021-01-05 13:29
My take is that with HW accel stopped, the delay is not needed.

**Comment by bundyo** [comment] 2021-01-05 13:47
Nah, seems it is still needed.

**Comment by sam0x17** [comment] 2021-01-07 06:19
Yeah if you try on a variety of desktop environments / platforms / distros you'll notice it's still needed and it needs to be several seconds to work consistently. Same as back in 2015 :/

**Comment by GodLyons** [comment] 2021-01-21 07:18
> Its been 5 years but still it couldn't be fixed. 😿

now，its 6.

**Comment by angjelonuho** [comment] 2021-05-16 10:52
I found a different  solution for me,  I had to disable : `webContents.openDevTools()` and was working fine.

**Comment by sam0x17** [comment] 2021-05-17 19:55
@angjelonuho yes as a general note when dev tools is open translucency automatically turns off because the window mode changes

**Comment by Tibinsunny** [comment] 2021-05-23 17:37
I was having a black screen while trying to enable the transparent property on my Arch Linux Manjaro. Adding the flag ``--enable-transparent-visuals --disable-gpu`` in the `start` script inside package.json fixed the issue for me.
I think this is indeed something related to the hardware

**Comment by lixiaohulee** [comment] 2021-07-28 11:06
I resolve this problem 

if you want to make a transparent window,  remember to invoke the window.setBackgroundColor after win.loadUrl or win.loadFile method 

`const win = new BrowserWindow({ transparent: true, frame: false }   win.loadUrl('xxx').  win.setBackgroundColor(' a transparent color like #00000000')` 

[https://github.com/electron/electron/pull/28022/commits/193d41b4b4f9937dbde9ba6f4412b7362cca8e4e](url)
