### ISSUE TITLE
msvcp40.dll

### ISSUE THREAD

**Issue by guohailin0323** [electron/electron#7317] opened 2016-09-23 06:11 UTC
* Electron version: v1.3.2
* Operating system: win10

hello dear:
     I use the "depends.exe" tool to view the electron, I did not find the dependent msvcp140.dll. I update electron to the latest. Also found no msvcp140.dll,But my electron application can run normally, I don't know what's the reason.
I opened this link and found electron dependent msvcp140.dll。
https://github.com/electron/electron/pull/5538/files
I want to make it clear.

thanks very much

![v1 3 2](https://cloud.githubusercontent.com/assets/21256636/18775820/2c814516-8197-11e6-8e3d-3c19d38da2ce.png)
![v1 3 2-01](https://cloud.githubusercontent.com/assets/21256636/18775821/2c85aa98-8197-11e6-90f6-25635b7e56cc.png)

**Comment by enlight** [comment] 2016-09-23 07:05
The MSVC CRT is [statically linked in Electron release builds](https://github.com/electron/electron/pull/5602) as of Electron v1.1.1, so users don't need to have `msvcp140.dll` installed on their machines.

Please refrain from creating duplicate issues covering the same subject. participants will still be notified about comments you make in a closed issue.

Closing as duplicate of #7315.

**Closed by enlight** 2016-09-23 07:05 UTC

**Comment by guohailin0323** [comment] 2016-09-23 07:15
ok,thank you very much,
I found this problem when I upgraded the electron,
So there's such a doubt。
