### ISSUE TITLE
"will-prevent-unload" event does not emit

### ISSUE THREAD

**Issue by LinYunWen** [electron/electron#26220] opened 2020-10-28 08:20 UTC
As the title, I cannot catch the "will-prevent-unload" event on main process when I closed the window.

This is the snippet in [doc](https://www.electronjs.org/docs/api/web-contents#event-will-prevent-unload)
```javascript
const { app } = require("electron");
app.on("ready", () => {
  const { BrowserWindow, dialog } = require('electron')
  const win = new BrowserWindow({ width: 800, height: 600 })
  win.webContents.on('will-prevent-unload', (event) => {
    const choice = dialog.showMessageBoxSync(win, {
      type: 'question',
      buttons: ['Leave', 'Stay'],
      title: 'Do you want to leave this site?',
      message: 'Changes you made may not be saved.',
      defaultId: 0,
      cancelId: 1
    })
    const leave = (choice === 0)
    if (leave) {
      event.preventDefault()
    }
  })
});
```
There are not any dialog open after I click close window button.
Even though I just console the "hello world" on the event handler, the text is not shown here.
```javascript
const { app } = require("electron");
app.on("ready", () => {
  const { BrowserWindow } = require('electron')
  const win = new BrowserWindow({ width: 800, height: 600 })
  win.webContents.on('will-prevent-unload', (event) => {
    console.log("hello world")
  })
});
```

I use electron 9.3.1 on macos and windows 10.

**Comment by bigben0123** [comment] 2020-10-29 02:43
It seems that will-prevent-unload will be fired when a dialog is closing, such as alert, confirm. 
It's not clear how to fire the event.

**Comment by nornagon** [comment] 2020-10-30 20:38
Works for me: https://gist.github.com/b12895f4fbb5a5110bcb4f35f2f3e5ab

**Comment by LinYunWen** [comment] 2020-11-02 12:31
> Works for me: https://gist.github.com/b12895f4fbb5a5110bcb4f35f2f3e5ab

I cloned the code in gist and ran it on my computer.
However, it still doesn't work. Here is the [video](https://imgur.com/xjdUgNg) of the process.

Did I do something wrong?

**Comment by bigben0123** [comment] 2020-11-03 02:42
try this, it'll be ok.

```
    window.onbeforeunload = function(event) {
      return confirm("are you sure to exit?");
    }
```

**Comment by electron-triage** [comment] 2021-03-09 16:23
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 16:23 UTC
Labels: 9-x-y, blocked/need-repro, bug :beetle:, platform/macOS, platform/windows
