### ISSUE TITLE
navigator.mediaDevices.enumerateDevices in macOs 10.14.6 works incorrect affter disable microphone

### ISSUE THREAD

**Issue by FitsnerAS** [electron/electron#23882] opened 2020-06-01 16:26 UTC
It seems that we have problem with navigator.mediaDevices.enumerateDevices in macOs 10.14.6;
Not sure about all users.  If microphone is disabled via System preferences>Security&Privacy>Privacy
Ordinary behavior on Chrome : we receive device without label and id in case if it disable:

{ "id": "", "groupId": "3ca2a959b76cff05fe18d721a6b94f31e1a52f4f23efd116298fa9604db83ae0", "kind": "audioinput", "label": "" }
In our case we receive:

{ "id": "default", "groupId": "2877000843271b9e8b3aabfd280b5362138ce3a373f7c47d4bd021a52c389330", "kind": "audioinput", "label": "Default - Unknown USB Audio Device" }

### Issue Details

* **Electron Version:**
  *7.1.11
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior
Returned deviceInfos disabled devices without label

### Actual Behavior
Disabled microphone returned with label

Thanks a lot!
### To Reproduce
call navigator.mediaDevices.enumerateDevices() microphone is disabled via System preferences>Security&Privacy>Privacy

**Comment by Draginfable** [comment] 2021-02-10 11:47
Hello @codebytere,
This issue is still reproducible with both latest electron(11.2.3) and macOS(Big Sur 11.2). Has there been any progress?

I have prepared an example to reproduce the issue: 
https://github.com/Draginfable/Electron-samples/tree/electron11-macMediaBug

```sh
git clone https://github.com/Draginfable/Electron-samples.git -b electron11-macMediaBug
cd Electron-samples
npm i
```

**Comment by Draginfable** [comment] 2021-06-07 07:01
I have also tested this on electron 13.1.1 and macOS 11.3.1 and the problem still exists.

Here is the example: 
https://github.com/Draginfable/Electron-samples/tree/electron13-macMediaBug

```sh
git clone https://github.com/Draginfable/Electron-samples.git -b electron13-macMediaBug
cd Electron-samples
npm i
```

**Comment by nornagon** [comment] 2021-06-18 20:16
Hm, I think this might be working as intended. Looking through the code, it seems that the Chromium layer asks the embedder whether or not the page has permission to access the device:

https://source.chromium.org/chromium/chromium/src/+/main:content/browser/media/media_devices_util.cc;l=181-202;drc=05977529e2cc592eb573f4e92b7a8c523b724bd6

That `has_permission` value comes from the call to `CheckMediaAccessPermission`:

https://source.chromium.org/chromium/chromium/src/+/main:content/browser/media/media_devices_permission_checker.cc;l=44-45;drc=05977529e2cc592eb573f4e92b7a8c523b724bd6

Which ultimately ends up in the user-supplied permission check handler: https://www.electronjs.org/docs/api/session#sessetpermissioncheckhandlerhandler

This code causes the behavior to match Chrome's behavior when the microphone is disabled:

```js
  session.defaultSession.setPermissionCheckHandler((webContents, permission, origin, details) => {
    if (permission === 'media') {
      return false
    }
    return true
  })
```

You might want to combine this with [systemPreferences.getMediaAccessStatus](https://www.electronjs.org/docs/api/system-preferences#systempreferencesgetmediaaccessstatusmediatype-windows-macos) for a complete solution.

I'm going to close this for now because I think this is working as intended, but it is a little confusing. If you have thoughts about how to make this clearer or better, I'm happy to continue discussing in this issue.

**Closed by nornagon** 2021-06-18 20:16 UTC
Labels: 11-x-y, 12-x-y, 13-x-y, 7-3-x, bug :beetle:, has-repro-repo, platform/macOS

**Comment by Draginfable** [comment] 2021-06-23 12:51
Thank you for the analysis @nornagon.
 
It seems a little weird that the method gives a different result on Chrome and Electron. However, by using  **systemPreferences.getMediaAccessStatus** as you suggested, we can do a workaround. 

That being said we noticed that **navigator.mediaDevices.getUserMedia** also behaves differently when the microphone is disabled. I have opened a separate ticket for that. electron/electron/issues/29861
