### ISSUE TITLE
moveToApplicationsFolder causes error

### ISSUE THREAD

**Issue by tvinzz** [electron/electron#26299] opened 2020-11-01 22:28 UTC
### Issue Details

* **Electron Version:**
  * 9.3.1
* **Operating System:**
  * macOS Catalina

### Expected Behavior
Application successfully copied to Applications folder. No warnings and errors.

### Actual Behavior
Got error message after application copied to Applications folder.

### Additional Information
I'm using `moveToApplicationsFolder` to move application file into Applications folder:

```
const checkIsInApplicationsFolder = () => {
    if (!app.isInApplicationsFolder()) {
        log.error('App has been run not from Application folder');
        dialog.showMessageBox({
            type: 'question',
            message: i18n.__('folder_check_dialog_message.message'),
            detail: i18n.__('folder_check_dialog_detail.message'),
            buttons: [i18n.__('folder_check_dialog_quit.message'), i18n.__('folder_check_dialog_move.message')],
            defaultId: 1,
        }).then((result) => {
            if (result.response === 1) {
                try {
                    const successfullyMoved = app.moveToApplicationsFolder();
                    if (successfullyMoved) {
                        log.warn('App was successfully moved to Applications folder');
                    }
                } catch (error) {
                    log.error(`Error moving App to Application folder: ${error.message}`);
                }
            } else {
                log.info('Force quit application');
                app.exit();
            }
        }).catch((error) => {
            log.error(`Error moving App to Application folder: ${error.message}`);
        });
    }
};
```

 but after moving I get the error:

![image](https://user-images.githubusercontent.com/15062885/97816993-9f720580-1caa-11eb-8461-93b5f3bbca63.png)

**Comment by ckerr** [comment] 2020-11-03 03:59
`internal/stream_base_commons.js:87:16` is pretty much what one would expect:

```js
function onWriteComplete(status) {
  debug('onWriteComplete', status, this.error);

  const stream = this.handle[owner_symbol];

  if (stream.destroyed) {
    if (typeof this.callback === 'function')
      this.callback(null);
    return;
  }

  if (status < 0) {
    const ex = errnoException(status, 'write', this.error);
    stream.destroy(ex, this.callback);
    return;
  }
```

**Comment by ckerr** [comment] 2020-11-03 04:00
@tvinzz, was this a one-time error or is it reproducible?

If it's reproducible, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by MarshallOfSound** [comment] 2020-11-04 19:26
`moveToApplicationsFolder` does not use Node.JS filesystem APIs, this error will be coming from your own code.  My guess is _while_ you're moving your app you are either reading or writing a file inside your app bundle.  As a result of the move operation that read / write stream is aborted because the file is no longer in the same place on disk.  I'm going to close this out because `moveToApplicationsFolder` causing an `fs` stream error is outside of Electrons codebase.  Happy to revisit if I've missed something however.

**Closed by MarshallOfSound** 2020-11-04 19:26 UTC
Labels: 9-x-y, blocked/need-info ❌, bug :beetle:, platform/macOS
