### ISSUE TITLE
vue-devtools dosen't work in 7.0.0

### ISSUE THREAD

**Issue by hayatesa** [electron/electron#20742] opened 2019-10-25 11:08 UTC
### Issue Details

* **Electron Version:**
  * 7.0.0
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * 6.0.x

### Actual Behavior

![vue](https://user-images.githubusercontent.com/31161642/67565983-41d2e100-f759-11e9-8514-d88947e9f719.png)

### To Reproduce
I tried two ways to intall vue-devtools, but they didn't work:
1. Added vue-devtools manually  by using chrome extension files.
2. Applied this lib -> https://github.com/zce/vue-devtools.

**Comment by booterbrought** [comment] 2019-10-27 15:54
#20677

**Comment by ladislavjacho** [comment] 2019-10-28 11:26
Same here with REACT_DEVELOPER_TOOLS, on the other side REDUX_DEVTOOLS works.

**Comment by miniak** [comment] 2019-10-28 21:27
Duplicate of #20677

**Comment by miniak** [comment] 2019-10-28 21:51
Duplicate of #20677

**Closed by miniak** 2019-10-28 21:51 UTC
