### ISSUE TITLE
shell.moveItemToTrash does not work when Recycle Bin is disabled

### ISSUE THREAD

**Issue by 50Wliu** [electron/electron#4974] opened 2016-03-31 19:58 UTC
- Electron version: 0.36.8
- Operating system: Windows 10 x64

I have the Recycle Bin set up to immediately delete files.  This seems to cause `shell.moveItemToTrash()` to fail.  As this is a native Windows option (at least for Windows 7+), it should be supported.

![recycle-bin-immediately-delete](https://cloud.githubusercontent.com/assets/2766036/14189087/90a8576e-f759-11e5-96bb-1518472c6f47.png)

**Comment by felixrieseberg** [comment] 2016-03-31 23:20
Did a quick investigation: This won't be easy.

**Comment by baconface** [comment] 2016-04-06 18:20
Would ```fs.unlink``` or ```fs.unlinkSync``` work for you since you have no need to put it in the bin?

**Comment by allistercsmith** [comment] 2016-06-13 16:16
Hey guys,

Any progress on this issue yet? Just wanted to add that this is an issue for OS X too. I have almost no experience with objective-C coding, so unfortunately can't be much help coding/testing wise.

However, just browsing around the web a bit ([here](https://developer.apple.com/library/mac/releasenotes/Foundation/RN-FoundationOlderNotes/), just search for NSFileManager Trash APIs), I noticed that there is a NSFeatureUnsupportedError returned if trash isn't supported for the volume.

Perhaps we can make a change in the `platform_util_mac.mm` file to the following lines:

```
bool MoveItemToTrash(const base::FilePath& full_path) {
  NSString* path_string = base::SysUTF8ToNSString(full_path.value());
  BOOL status = [[NSFileManager defaultManager]
                trashItemAtURL:[NSURL fileURLWithPath:path_string]
                resultingItemURL:nil
                error:nil];
  
  // Check if error = NSFeatureUnsupportedError.
  // If so, make a call to removeItemAtPath instead to directly delete the file.
  // Otherwise, continue as normal.
  
  if (!path_string || !status)
    LOG(WARNING) << "NSWorkspace failed to move file " << full_path.value()
                 << " to trash";
  return status;
}
```

There may be a bit more work involved with error messages/logging, but is there anyone who could try this out?

**Comment by slikts** [comment] 2016-07-07 13:25
This is a rather crippling issue, but thankfully a workaround exists for Windows (see atom/tree-view#856).

**Comment by codebytere** [comment] 2017-09-27 01:42
closing due to abandonment.

**Comment by jcj52436999** [comment] 2017-09-27 01:43
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (106/100 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:40671)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-96d6-jcjackson=joe-jackson.net@sgmail.github.com>)
	id 1dx1Ny-0016PP-IR
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:43:41 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=ViFKQz2QMZXcqzKHLXxVEleNh+s=; b=Ir2wZiMdlkC0MCpj
	Kq0MIkt8WQX0EZk7RuHEaSy3l+AsDr9LjHFHpqBMB2Qdn0NHWRFMBk4TmLxMta/1
	Db6XWLX2QpMgIZw76OZtXa+h4vWYtCVkgOZ9+9J29+i/Sm4jQgug4mPnMu+PlkYI
	4OufHwW8TO7QE/w840mwY7g46UE=
Received: by filter0973p1mdw1.sendgrid.net with SMTP id filter0973p1mdw1-14500-59CB021B-1E
        2017-09-27 01:42:51.922570987 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0013p1iad2.sendgrid.net (SG) with ESMTP id zjCGKquSQcKzOhGlkAOz9Q
	for <jcjackson@joe-jackson.net>; Wed, 27 Sep 2017 01:42:51.958 +0000 (UTC)
Date: Wed, 27 Sep 2017 01:42:51 +0000 (UTC)

**Comment by jcj52436999** [comment] 2017-09-27 01:43
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  joe.jackson.two@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (107/100 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:7597)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-96d6-jcjackson=joe-jackson.net@sgmail.github.com>)
	id 1dx1O0-0016Qc-EE
	for jcjackson@joe-jackson.net; Tue, 26 Sep 2017 20:43:43 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=C++GGxYoXkyVMXqm8/c/eNiKTUU=; b=t3zJirtMuvZmKN1F
	ps+M8hDih90ssbYA2PZECRueG3/LxBVX9OlYmtbkXhm7ygJjTH9jyxkT0MaUKqy5
	rqobI8cIXmmV1vDOFLbTCQQ17k20ot7IuqNw8pFgAassRBSd/J7oUCsVAsjJAY8e
	OVRfJZqZg192vzPcBZBCvNr7urI=
Received: by filter0554p1mdw1.sendgrid.net with SMTP id filter0554p1mdw1-32458-59CB0216-2F
        2017-09-27 01:42:46.5402004 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0007p1iad1.sendgrid.net (SG) with ESMTP id c8ztBk_fT1GpMUYlINHJeg
	for <jcjackson@joe-jackson.net>; Wed, 27 Sep 2017 01:42:46.468 +0000 (UTC)
Date: Wed, 27 Sep 2017 01:42:46 +0000 (UTC)

**Comment by 50Wliu** [comment] 2017-09-27 05:54
@codebytere would you mind reopening this?  I originally opened it on behalf of Atom (https://github.com/atom/tree-view/issues/856), and it appears that this is still a bug on at least Electron 1.6.9.

**Comment by MarshallOfSound** [comment] 2017-09-27 06:59
_Deleted auto-reply emails_

**Comment by codebytere** [comment] 2017-09-27 11:54
@50Wliu for sure! we're just making an effort to weed out abandoned issues :)

**Comment by codebytere** [comment] 2018-09-24 04:38
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by 50Wliu** [comment] 2018-09-24 22:09
@codebytere I can confirm that this is still an issue using Electron 2.0.9.  To test, I set the Recycle Bin to delete all items automatically, then opened Atom and attempted to delete a file using the Tree View.  The operation failed.

**Comment by sofianguy** [comment] 2019-08-09 04:08
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2019-08-30 17:56
Closing as we've implemented this on macOS with https://github.com/electron/electron/pull/19700 and Windows is not possible at this time.

**Closed by codebytere** 2019-08-30 17:56 UTC
Labels: 7-0-x, enhancement :sparkles:, platform/windows
