### ISSUE TITLE
Object properties no longer accessible via `remote` [!!]

### ISSUE THREAD

**Issue by bengotow** [electron/electron#5599] opened 2016-05-19 00:18 UTC
Hey! We've been investigating several very subtle issues in N1, which are caused by instance variables of remote objects returning `undefined` (Using Electron `1.0.1`).

In the browser/main process, we have a global called "application", and we were previously reading some state flags off it, like this: 

```
require('electron').remote.getGlobal('application').quitting
=> undefined
```

The boolean value is no longer returned, it's just undefined. I think this behavior is pretty dangerous, and it's definitely a regression. I believe this worked up until 0.37.8, but it could have been broken earlier. We were able to work around it by making a getter (`isQuitting()`).

**Comment by kevinsawicki** [comment] 2016-05-19 00:32
Hmm, this appears to be working in 1.1.0 for me:

```js
require('electron').remote.getCurrentWebContents().id
1
```

**Comment by bengotow** [comment] 2016-05-19 00:34
Ahh yeah - I realized that example was a separate issue actually. I was reading the docs, but that `id` property was only added 18 hours ago :-). Will try to put together a test case for this real quick.

**Comment by bengotow** [comment] 2016-05-19 00:42
It looks like this problem might be caused by caching of remote objects. Here's an example that reproduces the issue:

main process:

```
class Application {
  constructor() {
    setTimeout(() => {
      this.quitting = true;
    }, 4000);
  }
}

global.application = new Application();
```

renderer process:
```
setInterval(()=> {
  console.log("Quitting is " + remote.getGlobal('application').quitting);
}, 1000);
```

If you watch the console, the value never becomes `true` as expected.

(See entire demo app attached)

[test-remote-prop.zip](https://github.com/electron/electron/files/271661/test-remote-prop.zip)

**Comment by zcbenz** [comment] 2016-05-19 12:08
The remote objects returned by `remote` module is not aware of the new properties added to the original object, so if you add a new property to the object in the main process after calling `remote.getGlobal`, you can not read it with the remote object.

You didn't encounter this problem before probably because you were always using `remote.getGlobal` to access the remote object, which generated a new object for every call before we cached the remote objects.

It is possible to solve this by implementing `remote` module with Proxy, but it will introduce huge performance problems since many basic operations would involve sending synchronous messages, like iterating the object.

I'm closing since this is expected behavior with current implementation of `remote` module.

**Closed by zcbenz** 2016-05-19 12:08 UTC

**Comment by bengotow** [comment] 2016-05-19 16:28
Thanks for the explanation - I'd definitely expected calling `getGlobal` to give me a fresh copy of the global with the updated `quitting` value. I think it'd be worth mentioning this in the docs because the expected behavior of the implementation may not be the expected behavior in general.
