### ISSUE TITLE
Change in audio output default device in the system is not reflected inside the electron

### ISSUE THREAD

**Issue by Syed-Umair** [electron/electron#12365] opened 2018-03-20 10:31 UTC
The change in audio output default device in the system is not reflected inside the electron.

* Electron version: 1.7.x, 1.8.x, 2.0.0-beta.x
* Operating system: Windows 10, Macintosh 
* Devices Used: built-in output device and plantronics c320 usb headset device

### Expected behavior

[Checking the behavior in chrome](https://youtu.be/5qMNrUHNPPE)

The output device value changes with the change in default playback device.

### Actual behavior

[Checking the behavior in electron](https://youtu.be/LxDYWpeZivw)

The output device value doesn't change in electron with the change in default playback device.

### How to reproduce
Try running this following snippet after everytime you set the default output device in the system. This will get the default output device label.

```javascript
navigator
    .mediaDevices
    .enumerateDevices()
    .then( devices => {
        const audioDevices = devices.filter(device => device.kind === 'audiooutput');
        const defaultOuput = audioDevices.find(audio => audio.deviceId == 'default');
        audioDevices.shift();
        const outputDevice = audioDevices.find(audio => defaultOuput.groupId == audio.groupId);
        console.log(outputDevice.label);    
    });
```

**Comment by nornagon** [comment] 2018-04-04 01:05
Looks related to #12311.

**Comment by philfreo** [comment] 2018-04-04 13:25
If so then #12311 should be renamed to not just say "Windows" since this report was Mac.

**Comment by Egorikhin** [comment] 2018-11-20 11:22
Hi, are there any intentions to fix this somehow?

**Comment by sofianguy** [comment] 2019-08-09 03:25
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:07
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:07 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS, platform/windows, version/1.7.x, version/1.8.x
