### ISSUE TITLE
[Bug]: Setting setProxy to report error: err_ NO_ SUPPORTED_ PROXIES

### ISSUE THREAD

**Issue by dylan-7** [electron/electron#28419] opened 2021-03-27 09:23 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

MacOS Big Sur 11.2.3

### What arch are you using?

x64

### Last Known Working Electron version

12.0.2

### Expected Behavior

Set proxy IP

### Actual Behavior

I set proxy to report error: err_ NO_ SUPPORTED_ PROXIES。 How to solve this problem?

`app.commandLine.appendSwitch('proxy-server', 'socks5://username:password@ip:port')`
`win.webContents.session.setProxy({proxyRules: 'socks5://username:password@ip:port'})`

Thanks!!!

**Comment by Prinzhorn** [comment] 2021-03-27 10:53
https://github.com/electron/electron/issues/12443

**Comment by ckerr** [comment] 2021-03-28 22:41
Closing this issue as a duplicate of https://github.com/electron/electron/issues/12443

**Closed by ckerr** 2021-03-28 22:41 UTC
Labels: bug :beetle:
