### ISSUE TITLE
process.windowsStore returns undefined even in AppX packages in Electron 5.0.x

### ISSUE THREAD

**Issue by dangeredwolf** [electron/electron#18161] opened 2019-05-04 23:20 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Tested on electron 5.0.0, through 5.0.6
* **Operating System:**
  * Windows 10 (Tested on both 1803 and 1809)

### Expected Behavior
`process.windowsStore` should return true if running inside of an appx package, as described in https://electronjs.org/docs/api/process#processwindowsstore

### Actual Behavior
`process.windowsStore` returns undefined, even when running in an appx package

### To Reproduce
I forked electron-quick-start to demonstrate the issue I found.
[https://github.com/dangeredwolf/electron-quick-start](https://github.com/dangeredwolf/electron-quick-start)

You can then use `npm run buildWindows` to create the appx.

If you're unfamiliar with appx deployment, appx files need to be signed to be installed, even in developer mode. [This is basically how to do that (from Microsoft's docs)](https://docs.microsoft.com/en-gb/windows/uwp/packaging/sign-app-package-using-signtool)

`process.windowsStore` is undefined in both the main and renderer processes when installed as an AppX

### Screenshots

I set it up to throw a dialog box of whatever process.windowsStore is

![image](https://user-images.githubusercontent.com/2636265/57185775-bb230280-6e9f-11e9-901b-0bb384de9fe8.png)

It's obvious from electron itself that it's running from C:\Program Files\WindowsApps

![image](https://user-images.githubusercontent.com/2636265/57185783-d726a400-6e9f-11e9-8d05-bfc38a959897.png)

### Additional Information

After further testing, I confirmed that this is an issue introduced in Electron 5.0.0. You can test this by cloning [the electron-quick-start fork with process.windowsStore checks](https://github.com/dangeredwolf/electron-quick-start) and changing `package.json`'s `"devDependencies"`>`"electron"` from `"^5.0.0"` to `"^4.2.0"`

![image](https://user-images.githubusercontent.com/2636265/57185900-e9561180-6ea2-11e9-84b7-75a4e3ef7a48.png)

**Comment by codebytere** [comment] 2019-05-06 15:14
@dangeredwolf do you have `nodeIntegration` specifically enabled? As [documented](https://github.com/electron/electron/blob/4808f305384ce8eaaf2c054ff3ec02a35090981f/docs/api/breaking-changes.md#L99-L117), we made a change in `5.0.0` to disable it by default.

**Comment by dangeredwolf** [comment] 2019-05-08 01:12
Yes. nodeIntegration is enabled in both the example and the project I initially ran into the issue on. But remember, it also occurs in the main process.

**Comment by dangeredwolf** [comment] 2019-05-09 04:31
As I have mentioned before, nodeIntegration is on and there is no documentation as to the API itself changing, being removed, or no longer working, so perhaps it's a good idea to remove the blocked tag.

**Comment by codebytere** [comment] 2019-05-09 15:13
@dangeredwolf are other properties on `process` correctly defined? I see your fork only checks this one specific property.

**Comment by dangeredwolf** [comment] 2019-05-09 15:58
Let me check that for you! I haven't noticed any issues with other variables thus far, but I'll verify that the others work properly.

**Comment by codebytere** [comment] 2019-05-09 17:36
Hmm, interesting! So that property is set [here](https://github.com/electron/electron/blob/4ee201c56e22f0319b8c1700efaaa10804f095db/atom/common/api/electron_bindings.cc#L84-L87), and if i uncomment those conditionals it shows up so what that tells me is that `IsRunningInDesktopBridge()` isn't returning the correct boolean value in your case. Windows isn't my area of project expertise but I can try to see if something changed in there!

cc @felixrieseberg, you may have more answers here!

**Comment by dangeredwolf** [comment] 2019-05-10 00:39
I had a look at the code myself too, and I suspected that as well, but I couldn't find the IsRunningInDesktopBridge() function myself and I wasn't in the mood to download the whole source tree, so thank you! Haha

**Comment by miniak** [comment] 2019-05-20 21:15
I've compared the implementation between 4-2-x and 5-0-x. `IsRunningInDesktopBridge()` is exactly the same code, just moved around as I removed brightray.

**Comment by dangeredwolf** [comment] 2019-05-23 04:17
@miniak Weird, as it is returning different results if it is indeed the same code.

**Comment by dangeredwolf** [comment] 2019-06-03 03:18
Electron 5.0.2 has been released and it still seems to be affected by the issue.

**Comment by dangeredwolf** [comment] 2019-06-16 04:00
Electron 5.0.3 is also still affected by this issue, I have not had the chance to check 5.0.4 yet.

**Comment by dangeredwolf** [comment] 2019-06-21 23:55
Electron 5.0.5 is affected by this issue still.

**Comment by dangeredwolf** [comment] 2019-06-26 23:31
Electron 5.0.6 is still affected by this issue.

**Comment by steffanhalv** [comment] 2019-07-27 18:06
Thanks, I thought it was just me, our app was rejected after upgrading to electron 5 because of this.

I tested the appx version again and noticed all functionality disabled for it was running. Temporary I manually set environment variables to `forceWindowsStore = true` and check for ` if (window.process.env.forceWindowsStore === 'true') ...` instead of `if (process.windowsStore)`.

I hope this will be fixed soon ^^

**Comment by gaodeng** [comment] 2019-08-11 05:42
any news  on this?

**Comment by gaodeng** [comment] 2019-08-11 10:00
Electron 6.x version does not seem to have this problem. We plan to skip version 5.x .

**Comment by dangeredwolf** [comment] 2019-08-22 18:22
Indeed, I just verified for myself that it works now. So there are no plans to backport fixes?

**Comment by codebytere** [comment] 2019-08-22 18:33
@dangeredwolf this seems to be on the Chromium side - we didn't change anything in Electron. As such we're actually not 100% sure what they even fixed. When we find out, we can try to backport that.

**Comment by bitdisaster** [comment] 2020-01-08 18:11
This problem is back in Electron 7

**Comment by danutzcodrescu** [comment] 2020-03-18 09:50
It also happens on Electron 8 (tried it on 8.0.1 and 8.1.1)

**Comment by koenoe** [comment] 2020-03-18 14:05
It worked for me on Electron 7, but is broken again in Electron 8 (only tried 8.1.1).

**Comment by mifi** [comment] 2020-04-03 09:34
Also broken in 8.2.0

**Comment by erpy** [comment] 2020-04-04 16:42
Just got it from MS Store for supporting... but doesn't work at all...
Black screen, no UI...no settings...

![image](https://user-images.githubusercontent.com/734976/78456447-004d4700-76a4-11ea-83fc-3d13ab5d6cb7.png)

**Comment by mifi** [comment] 2020-04-04 16:50
@erpy I'm sorry that your app crashes. This error is unrelated to that.  I created a new issue here:  https://github.com/mifi/lossless-cut/issues/292
Let's continue discussing your issue there

**Comment by gaodeng** [comment] 2020-04-06 05:03
This bug is too annoying. Now I use the old method to do this   https://github.com/electron/electron/commit/4aaa936803ffd5f985dd0e42a7b69238f6e67a22

**Comment by mifi** [comment] 2020-04-06 05:18
I agree. Thanks for sharing The workaround @gaodeng !
Are you sure that Windows Store will always install apps under the WindowsApps directory? I had an instance of a user of my app where the app was stored on a different drive E:, it suggests that it is possible to set a custom install directory in windows

**Comment by mahnunchik** [comment] 2020-05-16 18:27
Any news?

**Comment by mahnunchik** [comment] 2020-05-19 14:31
Hi @codebytere @MarshallOfSound one year of this error. Do you plan to fix it? The solution https://github.com/electron/electron/issues/18161#issuecomment-609566904

**Comment by semireg** [comment] 2020-05-19 21:05
I think I'm getting bit with this on 8.3.0. I just published a Windows appx to Microsoft Store and users started complaining that the app was broken. I checked it out and sure enough, it's showing as if it's not running with windowsStore being set.

For example, because of this I'm seeing this error because electron-updater is firing up... 
![2020-05-19 at 4 04 PM](https://user-images.githubusercontent.com/1819762/82378279-79052a00-99ea-11ea-8d15-0946bd1dd8f9.png)

**Comment by mifi** [comment] 2020-05-20 06:10
I added a PR to update the docs so we don't have more developers going into this trap.

**Comment by semireg** [comment] 2020-05-20 12:48
For completeness, here's how I tried to solve this (but still failing).

I added this to package.json:
```
    "package-appx": "cross-env FORCE_MS_STORE=true npm run build && electron-builder --win appx",
```

Added to webpack.config for renderer/main:
```
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'production',
      FORCE_MS_STORE: process.env.FORCE_MS_STORE || false
    }),
```

I admit, I don't have a good way to test my unsigned appx builds other than submitting them to the store. If I run through a mac build I can verify that setting the env in this way does show up inside the app. So the build logic is sound.
```
  log.info(`isWindowsStoreForced process.env.FORCE_MS_STORE: ${process.env.FORCE_MS_STORE}`);
```

I submitted to MS store and I'm still getting the same behavior. Perhaps it's not process.windowsStore, but something else... I'm coming up short on ideas on how to troubleshoot this.

When my app launches I get my app's "first run experience" where they have to accept a license agreement. I use electron-settings, which still seems to "work" - so I have write access somewhere.

Strangely, I have a menu option to "show logs" which doesn't work.

![2020-05-20 at 7 44 AM](https://user-images.githubusercontent.com/1819762/82447581-18b7cc00-9a6e-11ea-928e-cf1bebfe5dbb.png)

This directory should be available because electron-log should write to these locations. Something is very wonky on these latest builds.

```
    "electron-better-ipc": "git://github.com/semireg/electron-better-ipc.git#semireg-remove-listeners",
    "electron-debug": "^1.5.0",
    "electron-is": "^3.0.0",
    "electron-log": "^4.0.6",
    "electron-prompt": "^1.4.0",
    "electron-settings": "^3.2.0",
    "electron-updater": "^4.3.1",
    "electron": "^8.3.0",
    "electron-builder": "^22.6.1",
    "electron-notarize": "^0.1.1",
    "electron-rebuild": "^1.8.6",
```

Hmmmmm. Anyone have any ideas? If unrelated, perhaps I should open a new issue.

**Comment by semireg** [comment] 2020-05-20 13:08
I did end up finding the logs. They are at this location. Hmmm... This means that electron-log is saving to this location, but findLogPath is resolving as somewhere else.

![2020-05-20 at 8 06 AM](https://user-images.githubusercontent.com/1819762/82449443-d774eb80-9a70-11ea-83b7-55f4c145b785.png)

```
const openLogsDir = () => {
  const logPath = log.transports.file.findLogPath();
  if (logPath == null) {
    return;
  }
  const logDir = path.dirname(logPath);
  log.info(`logDir: ${logDir}`);
  shell.openExternal(`file://${logDir}`);
};
```

To me, this is indicative of windowsStore being set wrong.

**Comment by semireg** [comment] 2020-05-20 15:28
In an attempt to *not* leave a bunch of open investigations in this thread, it looks like my problem was twofold. A recent change was preventing the most recent build of main.prod.js from being bundled into my app, and electron-log had deprecated findLogPath(). I'm going to submit and report back in hopefully <36 hours.

**Comment by zcbenz** [comment] 2020-05-26 01:28
It seems that there is an API for this:
https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-query-package-identity-information

I'll see if it can be used.

**Comment by zcbenz** [comment] 2020-05-26 02:29
I'm trying to reproduce this issue but it seems that `process.windowsStore` works correctly with following steps:

1. Download a win-x64 release from https://github.com/electron/electron/releases
2. Unzip it to `/electron`
3. Put the files of https://gist.github.com/zcbenz/d0b709d36e1f1006f2da2cfa59491490 under `/electron/resources/app`.
4. Run `electron-windows-store --input-directory electron --output-directory out --package-version 1.0.0.0 --package-name electron`
5. Install `out/electron.appx` and run.

**Comment by mahnunchik** [comment] 2020-05-26 08:36
@zcbenz @semireg if I understood correctly this happens with the Appx installed from Windows Store.

**Comment by zcbenz** [comment] 2020-05-26 09:51
@mahnunchik Do you mean it only happens when the app is submitted to Windows Store?

**Comment by gaodeng** [comment] 2020-05-26 11:08
@zcbenz   Thank you for your attention to this issue. I remember that electron v4.x and v6.x did not have this issue, v5.x v8.x  process.windowsStore reported wrong results，Haven't tried v7.x。

**Comment by zcbenz** [comment] 2020-05-27 01:35
@gaodeng Thanks for the information, I'm able to reproduce with 8.x, it seems that 9.x is not affected by the bug.

**Closed** 2020-05-27 17:50 UTC
Labels: 5-0-x, 7-1-x, bug :beetle:, platform/windows
