### ISSUE TITLE
7.1.0 crash on BrowserWindow::UpdateDraggableRegions

### ISSUE THREAD

**Issue by EtienneLem** [electron/electron#21005] opened 2019-11-06 15:40 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.0
* **Operating System:**
  * macOS 10.15.1

### To Reproduce
I unfortunately haven’t found a way to reproduce yet. Getting reports from multiple users claiming random crashes. I’m opening an issue nonetheless because I haven’t found any similar one yet and seeing the same stack trace on multiple crash occurrences. I was hoping the stack trace could help identify a possible cause from the codebase.

The stack trace suggests it may be related to changes since 0b25176, which is fairly new (v7).

Also feels like it may be when initiating a new BrowserWindow? Worth mentioning that our app always has a preloaded & hidden BrowserWindow (`show: false`) available for almost-instant initialization. When needed, we `win.show()` the preloaded window and preload a new one. _It may_ be when the crash happens in our case, but again I can’t reproduce on my end. Sorry about that.

### Crash report
```
Operating system: Mac OS X
                  10.15.1 19B88
CPU: amd64
     family 6 model 158 stepping 13
     16 CPUs

GPU: UNKNOWN

Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0x0
Process uptime: 8107 seconds

Thread 0 (crashed)
 0  Electron Framework!electron::api::BrowserWindow::UpdateDraggableRegions(std::__1::vector<mojo::StructPtr<electron::mojom::DraggableRegion>, std::__1::allocator<mojo::StructPtr<electron::mojom::DraggableRegion> > > const&) [atom_api_browser_window_mac.mm : 85 + 0x0]
 1  Electron Framework!electron::api::WebContents::UpdateDraggableRegions(std::__1::vector<mojo::StructPtr<electron::mojom::DraggableRegion>, std::__1::allocator<mojo::StructPtr<electron::mojom::DraggableRegion> > >) [atom_api_web_contents.cc : 1045 + 0x9]
 2  Electron Framework!electron::mojom::ElectronBrowserStubDispatch::Accept(electron::mojom::ElectronBrowser*, mojo::Message*) [api.mojom.cc : 1905 + 0x10]
 3  Electron Framework!mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*) [interface_endpoint_client.cc : 554 + 0x9]
 4  Electron Framework!mojo::internal::MultiplexRouter::ProcessIncomingMessage(mojo::internal::MultiplexRouter::MessageWrapper*, mojo::internal::MultiplexRouter::ClientCallBehavior, base::SequencedTaskRunner*) [multiplex_router.cc : 877 + 0x8]
 5  Electron Framework!mojo::internal::MultiplexRouter::Accept(mojo::Message*) [multiplex_router.cc : 598 + 0xb]
 6  Electron Framework!mojo::Connector::DispatchMessage(mojo::Message) [connector.cc : 514 + 0x9]
 7  Electron Framework!mojo::Connector::ReadAllAvailableMessages() [connector.cc : 589 + 0xb]
 8  Electron Framework!mojo::SimpleWatcher::OnHandleReady(int, unsigned int, mojo::HandleSignalsState const&) [callback.h : 132 + 0x9]
 9  Electron Framework!base::TaskAnnotator::RunTask(char const*, base::PendingTask*) [callback.h : 98 + 0x3]
10  Electron Framework!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*) [thread_controller_with_message_pump_impl.cc : 365 + 0x13]
11  Electron Framework!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoDelayedWork(base::TimeTicks*) [thread_controller_with_message_pump_impl.cc : 291 + 0x5]
12  Electron Framework!base::MessagePumpCFRunLoopBase::RunWork() [message_pump_mac.mm : 494 + 0xa]
13  Electron Framework!base::mac::CallWithEHFrame(void () block_pointer) + 0xa
14  Electron Framework!base::MessagePumpCFRunLoopBase::RunWorkSource(void*) [message_pump_mac.mm : 463 + 0x5]
15  CoreFoundation + 0x57b81
16  CoreFoundation + 0x57b20
17  CoreFoundation + 0x3b154
18  CoreFoundation + 0x3a760
19  CoreFoundation + 0x39fe3
20  HIToolbox + 0xa67d
21  HIToolbox + 0xa3bd
22  HIToolbox + 0xa147
23  AppKit + 0x17864
24  AppKit + 0x165d4
25  AppKit + 0x10d76
26  Electron Framework!base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) [message_pump_mac.mm : 850 + 0xd]
27  Electron Framework!base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) [message_pump_mac.mm : 186 + 0xc]
28  Electron Framework!non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) [thread_controller_with_message_pump_impl.cc : 463 + 0x6]
29  Electron Framework!base::RunLoop::Run() [run_loop.cc : 156 + 0x13]
30  Electron Framework!content::BrowserMainLoop::RunMainMessageLoopParts() [browser_main_loop.cc : 1509 + 0x8]
31  Electron Framework!content::BrowserMainRunnerImpl::Run() [browser_main_runner_impl.cc : 149 + 0x5]
32  Electron Framework!content::BrowserMain(content::MainFunctionParams const&) [browser_main.cc : 47 + 0x9]
33  Electron Framework!content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams&, bool) [content_main_runner_impl.cc : 556 + 0x8]
34  Electron Framework!content::ContentMainRunnerImpl::Run(bool) [content_main_runner_impl.cc : 871 + 0x10]
35  Electron Framework!service_manager::Main(service_manager::MainParams const&) [main.cc : 423 + 0xa]
36  Electron Framework!content::ContentMain(content::ContentMainParams const&) [content_main.cc : 19 + 0x8]
37  Electron Framework!AtomMain [atom_library_main.mm : 23 + 0x5]
38  Missive + 0x9e0
39  libdyld.dylib + 0x112e5
40  libdyld.dylib + 0x112e5
```

**Comment by codebytere** [comment] 2019-11-06 19:38
cc @nornagon for mojo refactoring

**Comment by EtienneLem** [comment] 2019-11-18 14:07
Quick note: Narrowed it down to when a window gets closed.

Getting a lot of “silent” crash reports when people quit their app (could do without the false-positive reports, but that’s mostly unharmful for our users), but also when sub-windows get closed which happens quite more often and crashes the main process.

**Comment by flashyu** [comment] 2019-11-21 09:11
all cpu is amd64 in crash report dump. why?

**Comment by drslump** [comment] 2019-11-22 17:07
Also seeing this crash since upgrading from 6 to 7.1.1. The issue seems to be triggered when closing *frameless* windows, although it doesn't crash with every close it's relatively common.

**Comment by electron-triage** [comment] 2021-03-09 04:03
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 04:03 UTC
Labels: 7-1-x, bug/crash :boom:, platform/macOS
