### ISSUE TITLE
Electron v1.2.3 App is crashing with following error

### ISSUE THREAD

**Issue by mina-from-the-jungle** [electron/electron#6185] opened 2016-06-22 17:51 UTC
* Electron version: v1.2.3
* Operating system: Ubuntu 16.04 

While running my build with the following command:
ELECTRON_ENABLE_LOGGING=true ./build/...

I am getting the following error log:

```
[4707:0622/184120:INFO:CONSOLE(207)]`` "Rotate array of 25", source:  (207)
[4726:0622/184120:ERROR:gles2_cmd_decoder.cc(14814)] [.CommandBufferContext.RenderWorker-0x32155d26280]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[4726:0622/184120:ERROR:gles2_cmd_decoder.cc(14814)] [.CommandBufferContext.RenderWorker-0x32155d26280]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[4726:0622/184120:ERROR:gles2_cmd_decoder.cc(14814)] [.CommandBufferContext.RenderWorker-0x32155d26280]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[4726:0622/184120:ERROR:gles2_cmd_decoder.cc(14814)] [.CommandBufferContext.RenderWorker-0x32155d26280]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[4726:0622/184120:ERROR:gles2_cmd_decoder.cc(14814)] [.CommandBufferContext.RenderWorker-0x32155d26280]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[4726:0622/184120:ERROR:gles2_cmd_decoder.cc(14814)] [.CommandBufferContext.RenderWorker-0x32155d26280]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[4726:0622/184120:ERROR:gles2_cmd_decoder.cc(14814)] [.CommandBufferContext.RenderWorker-0x32155d26280]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[4726:0622/184120:ERROR:gles2_cmd_decoder.cc(14814)] [.CommandBufferContext.RenderWorker-0x32155d26280]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[4726:0622/184120:ERROR:gles2_cmd_decoder.cc(14814)] [.CommandBufferContext.RenderWorker-0x32155d26280]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[4726:0622/184120:ERROR:gles2_cmd_decoder.cc(14814)] [.CommandBufferContext.RenderWorker-0x32155d26280]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[4726:0622/184120:ERROR:gles2_cmd_decoder.cc(14814)] [.CommandBufferContext.RenderWorker-0x32155d26280]GL ERROR :GL_INVALID_OPERATION : glBindTexImage2DCHROMIUM: no image found with the given ID
[4740:0100/000000:WARNING:ipc_channel_posix.cc(912)] Message needs unreceived descriptors channel:0x32155d3f600 message-type:4294967280 `header()->num_fds:1
App has crashed let's quit
```

**Comment by zcbenz** [comment] 2016-06-22 23:29
The errors are caused by GPU acceleration not working correctly, but it usually should not cause crashes. Can you also set `ELECTRON_ENABLE_STACK_DUMPING=1` and see if there is stack trace printed?

**Comment by zcbenz** [comment] 2016-07-09 02:02
Closing until more information is provided.

**Closed by zcbenz** 2016-07-09 02:02 UTC
Labels: more-information-needed
