### ISSUE TITLE
[Bug]: "console.assert" by preloaded resource

### ISSUE THREAD

**Issue by keyiis** [electron/electron#36386] opened 2022-11-17 11:41 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.3.1

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Expected Behavior

Don't show error

### Actual Behavior

If the following warning appears in electron console
![1668685019830](https://user-images.githubusercontent.com/7766085/202436309-940e9d85-74e4-40a3-838f-43caf2a3628c.png)
The main process will print the following error
```
[13236:1117/192319.259:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[13236:1117/192319.259:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[13236:1117/192319.259:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[13236:1117/192319.259:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[13236:1117/192319.260:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[13236:1117/192319.260:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[13236:1117/192319.260:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[13236:1117/192319.260:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
```

**Comment by VerteDinde** [comment] 2022-11-17 17:40
Closing as a dupe of 35399 (thanks @Prinzhorn!)

**Closed by VerteDinde** 2022-11-17 17:40 UTC
Labels: bug :beetle:

**Comment by clark-tan** [comment] 2023-05-29 02:08
I had the same problem 

win10 x64

"electron": "22.3.10","echarts": "^5.4.2"

```[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)
[electron] [21176:0529/093232.675:ERROR:CONSOLE(6)] "console.assert", source: devtools://devtools/bundled/panels/console/console.js (6)```
