### ISSUE TITLE
[Bug]: Unable to create three browsers that use 'window.open'

### ISSUE THREAD

**Issue by takman00** [electron/electron#28217] opened 2021-03-16 09:45 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 20H2

### What arch are you using?

x64

### Expected Behavior

Run "window.open" to display the three levels of browsers in the Electron browser.

### Actual Behavior

The parent screen -> child screen is displayed, but the child screen -> grandchild screen is not displayed correctly.

### Test github.io repository
- https://github.com/takman00/electron-test

### Test github.io pages
- https://takman00.github.io/electron-test/

#### Electron oparation

![electron1](https://user-images.githubusercontent.com/1650903/111288148-4322e780-8687-11eb-90dc-50e2021b5d34.jpg)

#### Chrome oparation

![electron2](https://user-images.githubusercontent.com/1650903/111288158-461dd800-8687-11eb-9b4a-716bca282907.jpg)

**Comment by takman00** [comment] 2021-03-16 09:48
```javascript
    wnd.webContents.setWindowOpenHandler(({url, frameName}) => {
      
      return {
        action: 'allow',
        overrideBrowserWindowOptions: {
          webPreferences: {
            webSecurity: false,
            nodeIntegration: false,
            webviewTag: false,
            sandbox: true,
            nativeWindowOpen: false,
            contextIsolation: false,
          },
          frame: true,
        }
      }
    });
```

**Comment by takman00** [comment] 2021-03-16 16:14
We tested using "electron-quick-start".
The following results were found.

- Success pattern

```javascript
   webPreferences: {
      sandbox: false,
      nativeWindowOpen: false,
    }
```

- Failure pattern
  - If either or both **sandbox** and **nativeWindowOpen** are set to **true**


Probably, the success pattern is due to the fact that the following source code is executed `isNativeWindowOpen == false`.

https://github.com/electron/electron/blob/5b205731f6ff77372656f0c85c52b703ec523e6f/lib/browser/guest-window-manager.ts#L77-L89

I don't want **window.loadURL** to be executed, so I want to solve this problem.
If you need any other additional information, please contact me.

**Comment by schontz** [comment] 2021-06-04 01:16
I have this bug on MacOS as well.

**Comment by MarshallOfSound** [comment] 2021-06-04 01:40
I can't explain _why_ but this works correctly in 14.0.0-beta.3 🤔 We've done a lot of tinkering with things like navigation controllers and prefs so it's possible we fixed this by accident.  If someone has time bisecting over our published nightly versions to figure out when it was fixed might help if we wanted to fix in older versions too

**Comment by schontz** [comment] 2021-06-12 05:13
Is there a quicker way of testing across versions besides npm installing each version?

**Comment by pushkin-** [comment] 2021-06-12 13:24
@schontz [electron-fiddle](https://www.electronjs.org/fiddle)

**Comment by schontz** [comment] 2021-06-14 21:03
> I can't explain _why_ but this works correctly in 14.0.0-beta.3 🤔 We've done a lot of tinkering with things like navigation controllers and prefs so it's possible we fixed this by accident. If someone has time bisecting over our published nightly versions to figure out when it was fixed might help if we wanted to fix in older versions too

I was able to do just that. The issue was fixed in 14.0.0-nightly.20210426. All prior versions break. Hope that helps.

![image](https://user-images.githubusercontent.com/2080286/121959038-1d09f380-cd19-11eb-9cbf-91d0cc8af213.png)

**Comment by MarshallOfSound** [comment] 2021-06-14 22:25
@schontz Awesome thanks for doing that, the diff there is this range --> https://github.com/electron/electron/compare/v14.0.0-nightly.20210413...v14.0.0-nightly.20210426

However the thing that stands out for me there is https://github.com/electron/electron/pull/28786 which deals with same-process webcontents preference mapping and may have fixed this issue.  Unfortunately it's stacked on top of multiple other changes that make it unlikely to be backported.

There's also https://github.com/electron/electron/pull/28552 which in combination of the above may have fixed it 😆  Unfortunately yeah, a lot of these architectural changes to window.open are stacked on top of each other and finding the exact combination which fixes this issue is gonna be quite tricky (and risky) to backport.

**Comment by schontz** [comment] 2021-06-15 18:29
Good to know. We won't expect any changes until v14 then.

**Comment by decafdennis** [comment] 2021-06-17 04:19
I believe this is what fixed the problem: https://github.com/electron/electron/commit/4ca518468d015a2d78524cad88e9917775921232

My theory is that there is a bug that causes `webContents.browserWindowOptions.webContents` to be wrong and interfere with the native window open logic. That `webContents` property appears to be the only thing that's different between opening the second window and opening the third window. The aforementioned commit stops using `webContents.browserWindowOptions` entirely, thereby fixing the bug.

I was able to work around the issue in both 12.x and 13.x by deleting that `webContents` property for every window created, as demonstrated here: https://github.com/frontapp/electron-nested-window-open-repro/blob/main/index.js#L8

(I actually went a step further and deleted that entire `browserWindowOptions` property to opt out of the option inheritance as well:

```tsx
function didCreateWindow(window) {
  delete window.webContents.browserWindowOptions;
  window.webContents.on('did-create-window', newWindow => didCreateWindow(newWindow));
}

const window = new BrowserWindow(...);
didCreateWindow(window);
```

**Comment by nornagon** [comment] 2021-06-17 18:25
Is this a duplicate of #29094?

**Comment by decafdennis** [comment] 2021-06-17 20:28
@nornagon Looks like it to me, yes!

**Comment by pushkin-** [comment] 2021-07-07 15:39
@decafdennis Do you (or someone on the Electron team) know how safe your workaround is? Can it cause problems?

`delete newWindow.webContents.browserWindowOptions.webContents;`

**Comment by nornagon** [comment] 2021-07-07 17:42
I'm going to close this as fixed in Electron 14, and sadly the fix is likely not backportable.

**Closed by nornagon** 2021-07-07 17:42 UTC
Labels: 12-x-y, bug :beetle:, platform/windows
