### ISSUE TITLE
Allow to get a BrowserWindow by its name

### ISSUE THREAD

**Issue by popod** [electron/electron#8129] opened 2016-12-02 13:17 UTC
Add a "name" option in [BrowserWindow](http://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions) and a method `BrowserWindow.fromName(name)` to allow us to get a window by its name (similar than [`BrowserWindow.fromName(name)`](http://electron.atom.io/docs/api/browser-window/#browserwindowfromidid) but with a determinate attribute).

**Comment by Smile42RU** [comment] 2017-01-09 10:12
@kevinsawicki issue looks like as useful enhancement. Someone from contributors already implemented it or preparing for it? If not may i try?

**Comment by enlight** [comment] 2017-01-10 01:45
It seems like you want to use the "name" as an identifier, but each window already has an identifier, and you can associate the window name and any additional information you may need with that identifier. I don't think this feature is worth including in the core API as it can be easily implemented in userland, so 👎 from me.

**Comment by MarshallOfSound** [comment] 2017-01-10 02:01
I agree with @enlight we already have a unique identifier (guaranteed to be unique) and adding a second one doesn't make much sense.

Also as mentioned it is relatively simple to implement in userland (see my [implementation](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/utils/WindowManager.js#L12) for instance).  Basically I feel this adds unneeded complexity.

**Comment by Smile42RU** [comment] 2017-01-10 02:06
@MarshallOfSound Okay, it sounds reasonable. It not need for me directly, but i want try help Electron with a tons of issues and this issue just looked as not too difficult for newbie and marked as "enhancement". 

May you forward me to really important issues which i can try resolve? Also, if this feature will not be implemented may close issue?

**Comment by MarshallOfSound** [comment] 2017-01-10 02:11
@Smile42RU The issue isn't closed as I believe it is still up for discussion I was simply stating my opinion on the proposal.

**Comment by kevinsawicki** [comment] 2017-01-10 16:55
>  I don't think this feature is worth including in the core API as it can be easily implemented in userland

👍 This sounds like a great userland module for apps that want finer-grained window management APIs and helpers.

> May you forward me to really important issues which i can try resolve?

Great to hear, thank you, you may want to check out https://github.com/electron/electron/issues?q=is%3Aopen+is%3Aissue+label%3Abeginner for some other possible issues to work on.

There are lots of issues as well with platform and subsystem labels so, depending on what platform you want to target or section of Electron you want to focus on, the issue labels should help you find them.

>  Also, if this feature will not be implemented may close issue?

Sounds good to me, closing this out.

**Closed by kevinsawicki** 2017-01-10 16:55 UTC
Labels: enhancement

**Comment by popod** [comment] 2018-12-15 15:54
@enlight @MarshallOfSound 

I agree with you, but in some case, it will be really useful to have a choose identifier available.. I do not want an other unique identifier, but just an other way to simple identify a window by a choosed name (like "printing-window", advanced-window", "main-window", ...). The window `title` is a solution, but it is display to the user (in the window title), so it can change depending of the user language, etc.

Let's me explain my situation : I create multiple `BrowserWindow` from a renderer process (which is the main window of my application). To close all the windows generated, it is more simple to tell "close all the windows with the name "advanced-windows" (or "close all the windows which are not "main-window") than matching all windows id with my "custom window manager". If I want to do this from the main process, my "custom window manager" is not available. But with my proposition of adding a custom identifiant to the windows, it will be possible.

Hop you understand what I'm trying to tell :) Do you think that we could reopen and implement this ?
