### ISSUE TITLE
Tray Icon not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by daniloribeiro00** [electron/electron#30172] opened 2021-07-16 22:57 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Expected Behavior

Tray icon should be the image set in `new Tray`

### Actual Behavior

It only shows correctly on Windows.
On Ubuntu it shows a purple icon instead.
![tray icon](https://user-images.githubusercontent.com/68981163/126015721-c993c377-c158-4509-b1e9-0dde3610d814.png)

### Additional Information

The same icon works as app icon and in notifications (the blue atom icon).
![notification](https://user-images.githubusercontent.com/68981163/126015760-493355e9-688c-45e2-b491-2a0222e62735.png)
![side bar](https://user-images.githubusercontent.com/68981163/126015763-4b9fc11e-f889-494d-900d-e17f3c179de4.png)

Here's my code:
```
function createTray() {
	const icon = path.join(process.resourcesPath, 'assets/favicon.png');
	tray = new Tray(nativeImage.createFromPath(icon));
	const contextMenu = Menu.buildFromTemplate([
		{
			label: 'Show',
			click: () => {
				createWindow();
			},
		},
		{
			label: 'Quit',
			click: () => {
				app.quit();
			},
		},
	]);

	tray.setContextMenu(contextMenu);
	tray.setToolTip('Desktop Client');
	tray.setTitle('Desktop Client');

	showNotification();
}
```

I'm using the same path to show the notification icon and it work.

Here's the icon in the project folder:
![folder](https://user-images.githubusercontent.com/68981163/126015947-42f45306-8f41-457c-b841-5beff68f52da.png)

**Comment by codebytere** [comment] 2021-07-21 20:24
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2021-08-17 17:44
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2021-08-17 17:44 UTC
Labels: platform/linux, component/tray, bug :beetle:, blocked/need-repro, 13-x-y
