### ISSUE TITLE
[Bug]: Developer Tools issue on right click menu not show in front

### ISSUE THREAD

**Issue by Seagrt** [electron/electron#40231] opened 2023-10-17 04:33 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Last Known Working Electron version

24.8.8

### Expected Behavior

Developer Tools openning status with separat window, the function 'right click menu' need to be show in front.
I made three versions to compare the result. Versions are v24.8.8 / 25.0.0 / 27.0.0. 
Only v24.8.8 is fine to work. Both version (25.0.0 / 27.0.0) have the issue about 'right click menu  not shown'

### Actual Behavior

Developer Tools openning status with separat window, the function 'right click menu' is not shown in front.
I made three versions to compare the result. Versions are v24.8.8 / 25.0.0 / 27.0.0. 
Only v24.8.8 is fine to work. Both version (25.0.0 / 27.0.0) have the issue about 'right click menu  not shown'

**Comment by Seagrt** [comment] 2023-10-18 11:25
> Hello @Seagrt. Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> Now adding the [ blocked/need-repro](https://github.com/electron/electron/labels/blocked%2Fneed-repro) Needs a test case to reproduce the bug label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

Hi, nice reply! I followed above idea to use Electron Fiddle, it is easy to switch version, however the pre-version only support to v25.0.0, thus I could not show issue corret result from v24.8.8. following picture is for test v25.0.0. Red rectangle is abnormal right menu (not show front when developer tools under separate mode). (Dock to right / to bottom / to left) have not this issue.

![image](https://github.com/electron/electron/assets/105124748/350012ec-b19f-407a-bf1c-be9dff8ed551)

**Comment by xueqianz** [comment] 2023-10-19 08:08
Also happened here. The menu is rendered behind the DevTools.

**Comment by codebytere** [comment] 2023-10-19 15:24
Ah - this is a duplicate of https://github.com/electron/electron/issues/38790 - see https://github.com/electron/electron/issues/38790#issuecomment-1592911862 for workaround.

**Closed by codebytere** 2023-10-19 15:24 UTC
Labels: bug :beetle:

**Comment by Seagrt** [comment] 2023-10-20 12:30
> Also happened here. The menu is rendered behind the DevTools.

Under your main.js or your main window first page to add following
app.commandLine.appendSwitch('disable-features', 'WidgetLayering');
