### ISSUE TITLE
Hash algorithms available to Electron are severely limited

### ISSUE THREAD

**Issue by mslipper** [electron/electron#16442] opened 2019-01-18 06:44 UTC
* Output of `node_modules/.bin/electron --version`: v4.0.1
* Operating System (Platform and Version): OSX Mojave
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): N/A

**Expected Behavior**

I'd expect that hash algorithms available to Electron would mirror those available to Node v10.11.0. So, something like:

```
> c.getHashes();
[ 'RSA-MD4',
  'RSA-MD5',
  'RSA-MDC2',
  'RSA-RIPEMD160',
  'RSA-SHA1',
  'RSA-SHA1-2',
  'RSA-SHA224',
  'RSA-SHA256',
  'RSA-SHA384',
  'RSA-SHA512',
  'blake2b512',
  'blake2s256',
  'md4',
  'md4WithRSAEncryption',
  'md5',
  'md5-sha1',
  'md5WithRSAEncryption',
  'mdc2',
  'mdc2WithRSA',
  'ripemd',
  'ripemd160',
  'ripemd160WithRSA',
  'rmd160',
  'sha1',
  'sha1WithRSAEncryption',
  'sha224',
  'sha224WithRSAEncryption',
  'sha256',
  'sha256WithRSAEncryption',
  'sha384',
  'sha384WithRSAEncryption',
  'sha512',
  'sha512WithRSAEncryption',
  'ssl3-md5',
  'ssl3-sha1',
  'whirlpool' ]
```

**Actual behavior**

Instead, the list of hashes is really small:

<img width="566" alt="screen shot 2019-01-17 at 10 42 58 pm" src="https://user-images.githubusercontent.com/67953/51369662-44592980-1aa9-11e9-972d-e3650066213f.png">

**To Reproduce**

Run `require('crypto').getHashes()` anywhere in your Electron app - you'll see that the available hashes is really small.

**Screenshots**
See the one above.

**Additional Information**
`ripemd160` specifically is very important to any cryptocurrency-related application, since RMD160 is used by Bitcoin-like chains to hash transaction data.

**Comment by nornagon** [comment] 2019-01-18 19:40
Duplicate of #16195

**Closed by nornagon** 2019-01-18 19:40 UTC
