### ISSUE TITLE
silent: true print option is causing prints to be very tiny. When silent is false it prints regular[Bug]: 

### ISSUE THREAD

**Issue by bagonterman** [electron/electron#39778] opened 2023-09-07 14:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 10.0.19044

### What arch are you using?

x64

### Expected Behavior

Expected behavior when using win.webContents.print(testoptions.... that the printed image would be the original size

### Actual Behavior

Actual behavior is the printed image is 100 times smaller than original even the header.

### Testcase Gist URL
https://gist.github.com/bagonterman/4abe303168c57b0ac8d6ec8d4ae01a49

**Comment by Hedwig188** [comment] 2023-09-07 20:40
Dup of #39179

**Comment by bagonterman** [comment] 2023-09-08 12:22
Hedwig188 you are right I didn't see it. This is an answer. Setting the dpi:{ horizontal: 600, vertical: 600 } on the printOptions can workaround the issue.

**Comment by VerteDinde** [comment] 2023-09-11 21:58
Closing as a dupe of #39179

**Closed by VerteDinde** 2023-09-11 21:58 UTC
Labels: bug :beetle:
