### ISSUE TITLE
IpcRenderer does not execute normally in preload.js

### ISSUE THREAD

**Issue by ChinaLiuxiaosong** [electron/electron#21437] opened 2019-12-09 09:57 UTC
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.3
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * never

### Expected Behavior
In `preload.js`, `ipcRenderer.on` can work when script loading.

### Actual Behavior
In `preload.js`, `ipcRenderer.on` does not work while script loaded.

### To Reproduce
https://gist.github.com/8beadb34f2123ee942968494edf439d0

### Screenshots
![image](https://user-images.githubusercontent.com/49019363/70426017-45be8680-1aad-11ea-9493-544d01dc00eb.png)

![image](https://user-images.githubusercontent.com/49019363/70425953-29224e80-1aad-11ea-9c79-c9030f61a2c7.png)

**Comment by reZach** [comment] 2020-01-08 05:08
I'd like to add some detail, it appears ipcRenderer does not include all methods when executing in a preload.js script. This is problematic, because there is no other way to pass an *ipcRenderer* to a renderer process. What does this mean? Renderer process cannot use [ipcRenderer.on("", {})](https://electronjs.org/docs/api/ipc-renderer#ipcrendereronchannel-listener).

**preload.js**
```
const { contextBridge, ipcRenderer } = require("electron");

console.log(ipcRenderer);
contextBridge.exposeInMainWorld(
    "electron",
    {
        ipcRenderer: ipcRenderer
    }
);
```

What gets displayed in the console:
![image](https://user-images.githubusercontent.com/4740370/71951968-8e4b8b80-31a2-11ea-93c9-c311744267fe.png)

**Comment by reZach** [comment] 2020-01-09 02:32
@sofianguy @ChinaLiuxiaosong 

It appears the **ipcRenderer** is only an [EventEmitter](https://nodejs.org/api/events.html#events_class_eventemitter) instance in the preload.js There must be some lifecycle code/event/gen that populates the [various properties](https://electronjs.org/docs/api/ipc-renderer) for an ipcRenderer, and this process isn't happening in the preload script.

**Comment by reZach** [comment] 2020-01-10 02:55
I will pay $100 for the bug fix for this issue: https://news.ycombinator.com/item?id=21998676

**Comment by reZach** [comment] 2020-01-11 00:07
I would gladly help if someone could point me in the right direction, my familiarity with the source code is very low.

**Comment by reZach** [comment] 2020-01-11 05:13
Another note, if you preload the **ipcRenderer**, using the contextBridge, even in a renderer process you get a subset of the methods (only the EventEmitter methods as described above), _not_ the entire method set as mentioned in the [docs](https://electronjs.org/docs/api/ipc-renderer). So the issue is not with the ipcRenderer but with the context bridge.

**Comment by reZach** [comment] 2020-01-11 05:48
There is no issue with contextBridge, simply the preload script itself, see MVP where you can test the bug (Electron v.7.1.8): https://github.com/reZach/broken-preload-example

**Comment by reZach** [comment] 2020-01-11 17:46
It looks like the problem is here: https://github.com/electron/electron/blob/ee58d6061282e65fa8f16d9e8929f65ed1390dcc/lib/renderer/init.ts#L42-L52. Can anyone explain _why_ we need to use an EventEmitter here?

**Comment by reZach** [comment] 2020-01-11 23:02
Update on the sample repo. @ChinaLiuxiaosong It turns out ipcRenderer.on works fine in the preload, at least in my sample repo. Please view the [following gist](https://gist.github.com/reZach/80358dbddfc002c3d27d48120a8b68d1) for more details. [My test repo](https://github.com/reZach/broken-preload-example) has also been updated to show you _can_ call ipcRenderer.on in the preload.

**_However_** - you still cannot call ipcRenderer.on(event, args) from the renderer process. This is desired because it is not feasible to put all logic regarding the ipcRenderer in the preload. ie. I have a [i18n library](https://github.com/reZach/i18next-electron-fs-backend) that needs to send ipc messages to the main process in order to save translation files to disk. This library exists in the renderer process, and in order for the translation files to be saved it needs to call out to the main process (which has access to `fs`). Upon finishing writing translation files, the library must finish executing it's code. Without ipcRenderer.on available in the renderer process, this process is impossible.
![image](https://user-images.githubusercontent.com/4740370/72211548-c993d600-3492-11ea-9093-49dbd07b1b1e.png)

Again, the **[MVP test repo](https://github.com/reZach/broken-preload-example)** has been updated and can replicate this problem for someone to replicate the issue.

**Comment by reZach** [comment] 2020-01-11 23:14
I've posted a **$230** [bounty](https://www.bountysource.com/issues/85135915-ipcrenderer-does-not-execute-normally-in-preload-js) on this issue for prioritization, thanks!

**Comment by reZach** [comment] 2020-01-13 05:14
Turns out, the problem _is_ contextBridge. A possible solution is to [not use contextBridge](https://github.com/electron/electron/pull/20307#issuecomment-573458696) and simply load the `ipcRenderer` to the renderer process the "old-way". More discussion is in that thread.

**Comment by MarshallOfSound** [comment] 2020-01-13 06:14
@reZach That is **not** a solution and is a **terrible** idea.  The problem is **not** the context bridge.

Copying your desired state from your other issue, this is how you do it correctly:

<details>

### renderer
```
class LibraryClass {
    constructor(myValue = 1) {
        this.classValue = myValue;

        window.electron.ipcRenderer.on("response", (IpcRendererEvent, args) => {
            if (args.success) this.classValue++;
        });
    }

    send() {
        window.electron.ipcRenderer.send("request", {
            data: this.classValue
        });
    }
}
```

### main
```
let win = new BrowserWindow({...});

ipcMain.on("request", (IpcMainEvent, args) => {
    // Use node module (ie. "fs");
    // perhaps save value of args.data to file with a timestamp

    win.webContents.send("response", {
        success: true
    });
});
```

</details>

### Isolated Preload

```js
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('myapi', {
  request: (data) => ipcRenderer.send("request", {
    data,
  }),
  onResponse: (fn) => {
    ipcRenderer.on('response', fn);
  }
}
```

### Renderer
```
class LibraryClass {
    constructor(myValue = 1) {
        this.classValue = myValue;

        window.myapi.onResponse((IpcRendererEvent, args) => {
            if (args.success) this.classValue++;
        });
    }

    send() {
        window.myapi.request(this.classValue);
    }
}
```

### Main Process
```
let win = new BrowserWindow({...});

ipcMain.on("request", (IpcMainEvent, args) => {
    // Use node module (ie. "fs");
    // perhaps save value of args.data to file with a timestamp

    win.webContents.send("response", {
        success: true
    });
});
```

### Things to note

1. Exposing a minimal API surface from the preload to the renderer, just two helpers, not the entire ipcRenderer module
2. Core business logic still remains in the renderer (LibraryClass) just the stuff that requires Electron APIs lives in the isolated preload
3. Even with this set up you should validate the incoming arguments are valid / what you would expect when you are handling the event in the main process


### Final Note

@reZach I'd ask that you stop spamming these issues as your issue is not this _potential bug_ rather user issues with how the APIs work.

**Comment by ChinaLiuxiaosong** [comment] 2020-01-13 08:47
@MarshallOfSound Now, I have two questions:

1. In `proload.js`, what should I do to know when` ipcRenderer.on` will normal work? Since I have some scripts that must work in `proload.js`, I need to know when` ipcRenderer.on` will work and I will trigger it.
2. On line 27 of [preload.js](https://gist.github.com/8beadb34f2123ee942968494edf439d0#file-preload-js), the args of ` sendTo` are different. But on line 16, the args of the two `on test.reply` are the same.

**Comment by MarshallOfSound** [comment] 2020-01-13 08:48
@ChinaLiuxiaosong sorry my reply above wasn't to you, the reply was addressing a user who is **not** experiencing whatever you are and I haven't looked into your particular hug report yet.

**Comment by reZach** [comment] 2020-01-13 12:10
@MarshallOfSound Yes, this is my fault. I continued the conversation after I had realized the issue was not related to @ChinaLiuxiaosong's. I did so to help anyone who might find value in the process to work around my specific issue, not the one created. 

Thank you for steering me on the right course for this repo with you are a member of. I will remember my faults and not repeat them again.

**Comment by reZach** [comment] 2020-01-14 03:47
@ChinaLiuxiaosong, can you explain what you are trying to achieve, I think it would help us solve for you your question. What I _think_ you are trying to do is communicate between two BrowserWindows? I think your current code _can_ work, but I feel its not set up in the best way it can be. 

I took a stab at your code and I was able to see the "LOADED" message as I _think_ you were aiming to see that. Something about the .once() calls were getting caught, so I removed it and removed the "LOADING" message as well (we could just send a LOADED message when done, it can feel redundant to send a LOADING message because we know it's still loading :))
```javascript
const {
    remote,
    ipcRenderer
} = require("electron");

const winName = process.argv.pop();
const webContentsId = remote.getCurrentWebContents().id;
const otherWebContents = remote.webContents.getAllWebContents().find(wc => wc.id != webContentsId);
const otherWebContentsId = otherWebContents && otherWebContents.id;

function now() {
    let date = new Date();
    return `${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}.${date.getMilliseconds()}`;
}

function sendToOtherWin(msg) {
    // console.log(`[${now()}] listen once 'test.reply'`);
    // ipcRenderer.once("test.reply", (event, message) => {
    //     console.log(`[${now()}] on 'test.reply' [message: ${message}] (expected message: reply.${msg})`);
    // });
    console.log(`[${now()}] send 'test' [message: ${msg}] to worker`);
    ipcRenderer.sendTo(otherWebContentsId, "test", msg);
}

if (winName == "worker") {
    console.log(`[${now()}] load preload in worker (${webContentsId})`);
    console.log(`[${now()}] listen 'test'`);
    ipcRenderer.on("test", (event, message) => {
        console.log(`[${now()}] on 'test' [message: ${message}], reply to ui`);
        ipcRenderer.sendTo(event.senderId, "test.reply", `reply.${message}`);
        // event.sender.sendTo(event.senderId, "test.reply", `reply.${message}`);
    });
} else if (winName == "ui") {
    console.log(`[${now()}] load preload in ui (${webContentsId})`);
    ipcRenderer.on("test.reply", (event, message) => {
        console.log(`[${now()}] on 'test.reply' [message: ${message}]`);
    });    
    //sendToOtherWin("LOADING");
    window.addEventListener("load", () => {
        let button = document.createElement("button");
        button.innerHTML = "send";
        button.onclick = () => {
            sendToOtherWin("LOADED");
        };
        document.body.appendChild(button);
    });
}

console.log(`[${now()}] loaded`);
```

I keep on thinking, and of course Marshall is the better judge here because he's actually developing in the codebase, but my thought is that you need to communicate between the browser windows through your main file. My thought was something like this:
![image](https://user-images.githubusercontent.com/4740370/72311712-38b42a80-364b-11ea-8454-cae612a2a25e.png)

Each browser window maintains it's own state, (ie. when it is "ready"), and when it is, each browser window can send an event back to the main process. The main process can keep track when both browser windows are ready and perform any logic you were thinking that should happen. This code is **very rough** but I hope it gives you an idea.

**preload.js** (probably can be the same preload for both BrowserWindows)
```javascript
const {
    remote,
    ipcRenderer
} = require("electron");

const winName = process.argv.pop();

ipcRenderer.on("receive", (event, args) => {
    console.log(`Received message from ${args.name}: '${args.message}'.`);
    if (typeof args.callback === "function") args.callback();
});

window.api = {
    "sendInformation": function(data){
        ipcRenderer.send("send", {
            name: winName,
            message: data
        });
    }
};
```

**index.html**
```html
<!DOCTYPE html>
<html lang="en-US">

<head>
    <title>Title</title>
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'">
</head>

<body>
    <script>
        // Send data to main process
        window.api.sendInformation("data");
    </script>
</body>

</html>
```

**main**
```javascript
const {
    app,
    BrowserWindow,
    ipcMain
} = require("electron");
const path = require("path");

let workerWin;
let uiWin;
let windows = ["worker", "ui"];

app.on("ready", async () => {
    workerWin = new BrowserWindow({
        height: 600,
        width: 800,
        title: "Worker",
        webPreferences: {
            preload: path.join(__dirname, "./preload.js"),
            additionalArguments: [windows[0]]
        },
    });
    await workerWin.loadFile(path.join(__dirname, "./index.html"));
    workerWin.webContents.openDevTools();

    uiWin = new BrowserWindow({
        height: 600,
        width: 800,
        title: "UI",
        webPreferences: {
            preload: path.join(__dirname, "./preload.js"),
            additionalArguments: [windows[1]]
        },
    });
    await uiWin.loadFile(path.join(__dirname, "./index.html"));
    uiWin.webContents.openDevTools();
});

ipcMain.on("send", (event, data) => {
    // find other window to send the event to
    let other = windows[0] !== data.name ? windows[0] : windows[1];

    if (other === "worker"){
        workerWin.webContents.send("receive", {
            name: "ui",
            message: data
        });
    } else {
        uiWin.webContents.send("receive", {
            name: "worker",
            message: data
        });
    }
});
```

**Comment by miniak** [comment] 2020-05-26 13:22
Closing due to lack of activity

**Closed by miniak** 2020-05-26 13:22 UTC
Labels: 7-1-x, bug :beetle:, platform/windows

**Comment by BeardScript** [comment] 2020-11-15 15:09
> @reZach That is **not** a solution and is a **terrible** idea. The problem is **not** the context bridge.
> 
> Copying your desired state from your other issue, this is how you do it correctly:
> 
> ### Isolated Preload
> ```js
> const { contextBridge, ipcRenderer } = require('electron');
> 
> contextBridge.exposeInMainWorld('myapi', {
>   request: (data) => ipcRenderer.send("request", {
>     data,
>   }),
>   onResponse: (fn) => {
>     // Deliberately strip event as it includes `sender` 
>     ipcRenderer.on('response', (event, ...args) => fn(...args));
>   }
> }
> ```
> 
> ### Renderer
> ```js
> class LibraryClass {
>     constructor(myValue = 1) {
>         this.classValue = myValue;
> 
>         window.myapi.onResponse((args) => {
>             if (args.success) this.classValue++;
>         });
>     }
> 
>     send() {
>         window.myapi.request(this.classValue);
>     }
> }
> ```
> 
> ### Main Process
> ```js
> let win = new BrowserWindow({...});
> 
> ipcMain.on("request", (IpcMainEvent, args) => {
>     // Use node module (ie. "fs");
>     // perhaps save value of args.data to file with a timestamp
> 
>     win.webContents.send("response", {
>         success: true
>     });
> });
> ```
> 
> ### Things to note
> 1. Exposing a minimal API surface from the preload to the renderer, just two helpers, not the entire ipcRenderer module
> 2. Core business logic still remains in the renderer (LibraryClass) just the stuff that requires Electron APIs lives in the isolated preload
> 3. Even with this set up you should validate the incoming arguments are valid / what you would expect when you are handling the event in the main process
> 
> ### Final Note
> @reZach I'd ask that you stop spamming these issues as your issue is not this _potential bug_ rather user issues with how the APIs work.

Thanks for sharing this @MarshallOfSound. I just found it while looking into a similar issue. This seems to solve my problem but, now I'm wondering, wouldn't sending a callback to the preload script potentially give access to Electron and node APIs to a hijacker?

Also, if I'm not mistaken there's a memory leak here right?:

```js
onResponse: (fn) => {
     // Deliberately strip event as it includes `sender` 
     ipcRenderer.on('response', (event, ...args) => fn(...args));
}
```

The event handler is being created over and over and never cleaned up.

**Comment by raphael10-collab** [comment] 2020-12-14 15:45
@MarshallOfSound 

In an electron-react-typescript-webpack app I'm trying to make two windows communicate.

preload.ts :  

    import { ipcRenderer, contextBridge, BrowserWindow } from 'electron';

    let secondWindow;

    contextBridge.exposeInMainWorld('electron', {
      openNewWindow: () => ipcRenderer.send('open-second-window', {
        secondWindow = new BrowserWindow({width: 1000, height: 1200});
      });
    });

index.d.ts  :  

    declare interface Window {
      electron: {
        //doThing(): void;
        openNewWindow(): void;
      };
      myapi;
    }

main.ts :  

    import { app, BrowserWindow, ipcMain } from 'electron';

    ipcMain.on("reply", (IpcMainEvent, message) => {
      console.log(event, message);
      mainWindow.webContents.send('messageFromMain', `This is the message from the second 
    window: ${message}`);
    });

renderer.ts: 

    window.myapi.onResponse('messageFromMain', (event, message) => {
      console.log(`This is the message from the second window sent via main: ${message}`);
    });

    const openSecondWindowButton = document.getElementById('open-second-window');

    window.electron.openNewWindow();

app/components/App.tsx  : 

    import logo from '@static/logo.png';
    import React from 'react';
    import { hot } from 'react-hot-loader';

    interface AppProps {
      title?: string;
    }

    interface AppState {
      counter: number;
    }

    class App extends React.Component<AppProps, AppState> {
      readonly state: AppState = { counter: 0 };

      render(): JSX.Element {
        return (
          <div className='container'>
            <h2 className='heading'>
              <img src={logo} width='32' title='Codesbiome' /> &nbsp;
                Two Windows Communication
           </h2>

            <button
              onClick={(): void =>
                this.setState({ counter: this.state.counter + 1 })
              }
           >
            Counter &nbsp; <span>{this.state.counter}</span>
           </button>
           <p>
             <button id="open-second-window">Open Second Window</button>
           </p>
         </div>
       );
     }
   }

   export default hot(module)(App);



I get this error: electron_WEBPACK_IMPORTED_MODULE_0__.BrowserWindow is not a constructor

![image](https://user-images.githubusercontent.com/70313067/102102005-9d63a080-3e2b-11eb-8365-36143d70347c.png)


These are the specs of the API Objects: https://www.electronjs.org/docs/all#api-objects

The lines that cause this error seems to be this line in preload.ts :  

    const secondWindow = new BrowserWindow({width: 1000, height: 1200});

together with this line in renderer.ts:

    window.electron.openNewWindow();

How to solve the error?

**Comment by Slapbox** [comment] 2021-03-18 19:31
@MarshallOfSound do you have any advice for how to remove an individual listener from a channel with this pattern, since it's an anonymous function that's being registered? 

Or is there any good workaround to avoid increasing the attack surface? I'm having trouble formulating a reasonable alternative.

```js
contextBridge.exposeInMainWorld('myapi', {
  request: (data) => ipcRenderer.send("request", {
    data,
  }),
  onResponse: (fn) => {
    // Deliberately strip event as it includes `sender` 
    ipcRenderer.on('response', (event, ...args) => fn(...args)); // How could this listener be removed without a function name?
  }
}
```

**Comment by Slapbox** [comment] 2021-03-18 19:35
I guess we could do something like this but it seems likely to quickly get out of hand, not to mention precluding the possibility of returning a value from `onResponse`.

```js
contextBridge.exposeInMainWorld('myapi', {
  request: (data) => ipcRenderer.send("request", {
    data,
  }),
  onResponse: (fn) => {
    const saferFn = (event, ...args) => fn(...args)
    // Deliberately strip event as it includes `sender` 
    ipcRenderer.on('response', saferFn);
    return saferFn; // Return the newly created function so the user can store it somewhere and later remove it.
  }
}
```

Unfortunately storing these extra references would quickly make the code quite convoluted.

**Comment by MarshallOfSound** [comment] 2021-03-18 20:50
@Slapbox Unfortunately that wouldn't work as every time a function is passed over the bridge a new proxy function is made.  i.e.

function A (world 1) --> function B (world 2)
function B (world 2) --> function C (world 1)

It's a known inefficiency of the contextBridge.

How I'd do this is by using some kind of token system.


```js
const listeners = {};

contextBridge.exposeInMainWorld('myapi', {
  request: (data) => ipcRenderer.send("request", {
    data,
  }),
  onResponse: (fn) => {
    const saferFn = (event, ...args) => fn(...args)
    // Deliberately strip event as it includes `sender` 
    ipcRenderer.on('response', saferFn);
    const key = symbol();
    listeners[key] = saferFn;
    return key;
  },
  removeResponseHandler: (key) => {
    const fn = listeners[key];
    delete listeners[key];
    ipcRenderer.removeListener('response', fn);
  }
}
```

You can always make a pretty helper for this to make the usage for multiple IPC events much cleaner

**Comment by Slapbox** [comment] 2021-03-18 21:57
@MarshallOfSound thanks so much for letting me know that what I'd outlined wouldn't work! The extra logic required is unfortunate, but it makes sense; security doesn't come free.

**Comment by rm44436** [comment] 2021-05-19 07:01
> I guess we could do something like this but it seems likely to quickly get out of hand.
> 
> ```js
> contextBridge.exposeInMainWorld('myapi', {
>   request: (data) => ipcRenderer.send("request", {
>     data,
>   }),
>   onResponse: (fn) => {
>     const saferFn = (event, ...args) => fn(...args)
>     // Deliberately strip event as it includes `sender` 
>     ipcRenderer.on('response', saferFn);
>     return saferFn; // Return the newly created function so the user can store it somewhere and later remove it.
>   }
> }
> ```
> 
> Unfortunately storing these extra references would quickly make the code quite convoluted.

whats the use of fn or saferfn , how do i use it . what function fn is . As ar as i know ipcrenderer.on(event, data (data which we received not function)) , its used as this type.

also how to paas data coming from electron to browser window , cause only preload can use incoming data , not browserwindow or main.js file which contains jsx and js files (in react terms)

**Comment by shumeiko** [comment] 2021-07-15 18:43
Here is another simple way to avoid the problem of not being able to remove the listener because of that function references issues:
```
// preload.js
contextBridge.exposeInMainWorld('ipc', {
  on: (channel, listener) => {
    ipcRenderer.on(channel, listener);
    return () => {
      ipcRenderer.removeListener(channel, listener);
    };
  },
});

// renderer process
const removeListener = window.ipc.on('channel', () => {
  // listener code
});
removeListener();
```

**Comment by JanMisker** [comment] 2021-08-08 11:51
> Here is another simple way to avoid the problem of not being able to remove the listener because of that function references issues:
> 
> ```
> // preload.js
> contextBridge.exposeInMainWorld('ipc', {
>   on: (channel, listener) => {
>     ipcRenderer.on(channel, listener);
>     return () => {
>       ipcRenderer.removeListener(channel, listener);
>     };
>   },
> });
> 
> // renderer process
> const removeListener = window.ipc.on('channel', () => {
>   // listener code
> });
> removeListener();
> ```

Thanks for this @shumeiko, really helped me. Would you say this is a good way to generalise your approach, also stripping away the `IpcRendererEvent` (not so useful in generic case?) and not exposing all channels.

```
// preload.js
function makeListener(channel) {
  return function (listener) {
    ipcRenderer.on(channel, (_evt, ...args) => listener(...args));
    return () => ipcRenderer.removeListener(channel, listener);
  };
}
contextBridge.exposeInMainWorld("__MY_API__", {
  attributeA: 42, // initial value
  onAttributeA: makeListener("set-attribute-a"),
  onAttributeB: makeListener("set-attribute-b"),
});
```
```
// main.js
win.webContents.send("set-attribute-a", 42);
```
```
// renderer
const removeListenerA = window.__MY_API__.onAttributeA((value) => { 
  // do something with the value
});
```
```
// renderer with React, semi-pseudo-code
export const useMyApi = () => {
  const myApi = useRef(window.__MY_API__);
  const [attributeA, setAttributeA] = useState(myApi.current?.attributeA);
  
  useEffect(() => {
    if (myApi.current?.onAttributeA) {
      const unsub = myApi.current.onAttributeA(setAttributeA);
      return () => unsub();
      // or if you like short code that the next dev wont understand: return myApi.current.onAttributeA(setAttributeA);
    }
  }, [myApi.current?.onAttributeA]);

  return { attributeA };
}
```

**Comment by alex8088** [comment] 2022-03-29 09:55
Easy to expose Electron APIs (ipcRenderer,webFrame,process) to renderer with [@electron-toolkit/preload](https://github.com/alex8088/electron-toolkit/tree/master/packages/preload)

**Comment by DarkSynx** [comment] 2023-03-21 14:53
2022 simple and functional
``` typescript
//main.js 
    ipcMain.on('messageFromRenderer', (event, arg) => {
        console.log(arg); // Affiche "Hello world !" dans la console principale
        event.reply('responseToRenderer', 'Message reçu !'); // Répond à l'ipcRenderer
    });

```
```html
//index.html
...
<WebView id='frame' preload="./js/preload.js" src='URL' nodeintegration spellcheck=1></WebView>
...

```
```typescript
// preload.js

    const { ipcRenderer } = require('electron');

    ipcRenderer.send('messageFromRenderer', 'Hello world !'); // Envoie un message à l'ipcMain

    ipcRenderer.on('responseToRenderer', (event, arg) => {
        console.log(arg); // Affiche "Message reçu !" dans la console de la WebView
    });

```

**Comment by DarkSynx** [comment] 2023-03-21 16:48
version controle button in index.html 
I solved the problem by sending "webContents" in a global variable "mainWindowWebContents" for later use 

```typescript
//index.html
...
<WebView id='frame' preload="./js/preload.js" src='URL' nodeintegration spellcheck=1></WebView>
<button onclick="ipcaction()">Button action</button>
...
<script>
const ipc = require("electron").ipcRenderer;
function ipcaction() {
    console.log("ipcaction");
    ipc.send('messageFromMain', 'Hello world 555 !');
}
</script>
```

//main.js
```typescript
const { app, BrowserWindow, ipcMain } = require('electron');
const ipc = require("electron").ipcMain;
let mainWindowWebContents = null;

app.on('ready', () => {
  const mainWindow = new BrowserWindow({ width: 800, height: 600, webPreferences: { nodeIntegration: true } })
  mainWindow.loadFile('index.html')

    ipc.on("messageFromMain", event => {
        console.log('messageFromMain');
        sendToMainWindow('Hello from main.js W!');
    });

})

function sendToMainWindow(message) {
    if (mainWindowWebContents) {
        mainWindowWebContents.send('messageFromMain', message)
    }
}

    app.on("web-contents-created", (event, webContents) => {

        webContents.on('did-finish-load', () => {
            if (webContents.getType() === 'webview') {
                mainWindowWebContents = webContents;
                sendToMainWindow('Hello from main.js X!');
            }
        });
});
```

```typescript
//preload.js    :::: WebView id='frame' preload="./js/preload.js"
window.addEventListener('load', () => {

    const { ipcRenderer } = require('electron')
    ipcRenderer.on('messageFromMain', (event, arg) => {
        console.log(arg) // affiche "Hello world 555 !"
    })
    
 });
```
