### ISSUE TITLE
isFullScreen returns false for transparent fullscreen window

### ISSUE THREAD

**Issue by gnomesley** [electron/electron#8321] opened 2017-01-02 07:16 UTC
* Electron version: 1.4.13
* Operating system: Windows 8.1

### Expected behavior

Calling isFullScreen() on a transparent fullscreen window should return true.

### Actual behavior

isFullScreen() returns false (it returns true when transparent is set to false in the example below).

### How to reproduce

```
electron.app.on("ready", function () {
    var win = new BrowserWindow({
        show: true,
        frame: false,
        fullscreen: true,
        transparent: true
    });
    console.log(win.isFullScreen());
});
```

**Comment by liusy182** [comment] 2017-01-16 03:56
this is probably fixed by some other changes. I am not able to reproduce it in version `1.4.14` on windows.

**Comment by kevinsawicki** [comment] 2017-01-17 18:42
@gnomesley are you able to still reproduce this in Electron 1.4.14?

**Comment by gnomesley** [comment] 2017-01-18 22:01
Now win.isFullScreen() returns true, but the window is no longer transparent (it has a white background). Should I make a new issue for this?

**Comment by kevinsawicki** [comment] 2017-01-18 22:28
@gnomesley yes, please do 👍

**Comment by foxymoron** [comment] 2018-03-19 06:07
Hi @kevinsawicki . Can you tell me which version of electron resolves this issue ? I am able to reproduce it in v1.8.3 ( win.isFullScreen() returns false for transparent fullscreen window)

**Comment by Eugeny** [comment] 2018-09-22 11:52
It's still not fixed in 3.0.0-beta.9

**Comment by Eugeny** [comment] 2018-09-22 12:01
Same on 3.0.0 final

**Comment by codebytere** [comment] 2018-09-22 21:49
@Eugeny i'll take a stab at this imminently

**Comment by codebytere** [comment] 2018-09-23 16:55
Ok i just ran 
```
const {app, BrowserWindow} = require('electron')

let win

app.on('ready', () => {
  win = new BrowserWindow({
    frame: false,
    fullscreen: true,
    transparent: true
  })

  win.loadFile('index.html')
  console.log(win.isFullScreen())

  win.on('closed', () => { win = null })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (win === null) createWindow()
})
```
using current `master` and it correctly went fullscreen and printed `true`. 
@Eugeny can you confirm the same is true on your end?

**Comment by Eugeny** [comment] 2018-09-23 18:31
@codebytere before I attempt to build Electron from source, on my side I'm using W10 and doing `setFullScreen()` after the window is created.

**Comment by cow613** [comment] 2018-10-16 10:51
I am also having trouble with this issue, using Electron v1.8.6. 
When running the following demo app (based on @codebytere's sample), you can see that the isFullScreen API always returns false, and the window can be resized, even though it is supposed to be in fullscreen mode.

`const {app, BrowserWindow} = require('electron')

let win

app.on('ready', () => {
    win = new BrowserWindow({frame: false, transparent: true, fullscreen: true})

    win.loadURL('http://www.google.com')

    win.on('closed', () => { win = null })
    
    setInterval(() => { 
        console.log('Fullscreen: ' + win.isFullScreen()); 
    }, 3000);
})

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit()
    }
})

app.on('activate', () => {
    if (win === null) createWindow()
})
`

**Comment by cow613** [comment] 2018-10-16 10:54
I am also having trouble with this issue, using Electron v1.8.6. 
When running the following demo app (based on @codebytere's sample), you can see that the isFullScreen API always returns false, and the window can be resized, even though it is supposed to be in fullscreen mode.

```
const {app, BrowserWindow} = require('electron')

let win

app.on('ready', () => {
    win = new BrowserWindow({frame: false, transparent: true, fullscreen: true})

    win.loadURL('http://www.google.com')

    win.on('closed', () => { win = null })
    
    setInterval(() => { 
        console.log('Fullscreen: ' + win.isFullScreen()); 
    }, 3000);
})

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit()
    }
})

app.on('activate', () => {
    if (win === null) createWindow()
})
```

**Comment by codebytere** [comment] 2019-08-30 18:01
Fixed by https://github.com/electron/electron/commit/727cd68ceec7ef869674c4a5b92683fea433478d.

**Closed by codebytere** 2019-08-30 18:01 UTC
Labels: component/transparent, platform/windows
