### ISSUE TITLE
[Bug]: electron13.6.1→14.0.0： execute loadURL, BrouserWindow crashed

### ISSUE THREAD

**Issue by HarunoOi** [electron/electron#31828] opened 2021-11-15 08:37 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

macOS

### Operating System Version

mac OS mojave 10.14.6

### What arch are you using?

x64

### Last Known Working Electron version

13.6.1

### Process
1. create window  and execute loadURL
this.window.loadURL(`${this.viewsPath}/image_display.html.ejs`)
2. Drag and drop the photo
3. Reload ejs 
this.window.loadURL(`${this.viewsPath}/image_display.html.ejs`)
4. Display photo

Console after reloading ejs
```
start loading 
frame-finish-load
did-finish-load
stop loading 
 ```

### Main Process
```
module.exports = class PhotoWindow extends MainWindow {
  
  async ready() {
    //DELETE: Electron14
    //app.allowRendererProcessReuse = false;
    this.droppedFileHandler = (/* nullable */event, imageUrls, movieUrls) => {
        //drag and drop
        Bluebird.map(movieUrls, (movieUrl) => {
        let photo = new Photo(movieUrl)
        
                    ~~~
        
        this.displayPhoto(new Photo(movieUrls[0]))
      })
    }
    this.createWindow()
  }
  
  createWindow() {
    this.window = new BrowserWindow({
      width: 1024,
      height: 800,
      backgroundColor: '#606060',
      title: this.l.t('application.title'),
      icon: this.iconPath,
      nativeWindowOpen: false,
      webPreferences: {
        preload: path.resolve(path.join(__dirname, '/preload_modules/image_display_modules.js')),
        enableRemoteModule: true,
        contextIsolation: false,
        nativeWindowOpen: false
      }
    })
    
        ~~~
      
    this.window.loadURL(`${this.viewsPath}/image_display.html.ejs`)
  }
  
  async displayPhoto(photo) {
    this.photo = photo
    this.ejsOptions.fileopened = true
    this.ejsOptions.fileName = this.photo.fileName
    this.ejsOptions.imageSize = this.photo.imageSize

    this.window.webContents.once('did-finish-load', () => { console.log(`did-finish-load`) })
    this.window.webContents.once('did-start-loading', () => { console.log(`start loading `) })
    this.window.webContents.once('did-frame-finish-load', () => { console.log(`frame-finish-load`) })
    this.window.webContents.once('did-stop-loading', () => { console.log(`stop loading `) })

    this.window.loadURL(`${this.viewsPath}/image_display.html.ejs`)
    }
}

```

### Actual Behavior

1. create window  and execute loadURL
this.window.loadURL(`${this.viewsPath}/image_display.html.ejs`)
2. Drag and drop the photo
3. Reload ejs  <- failed
this.window.loadURL(`${this.viewsPath}/image_display.html.ejs`)
4. Display photo

Console after reloading ejs
```
start loading 
Electron Helper (Renderer)(66863,0x113c6f5c0) malloc: *** error for object 0x7fca15dafbc0: pointer being freed was not allocated
Electron Helper (Renderer)(66863,0x113c6f5c0) malloc: *** set a breakpoint in malloc_error_break to debug
stop loading 
 ```

The screen does not appear after executing loadURL.
* The image is not displayed
* frame-finish-load and did-finish-load in not firing
* `this.window.webContents.on('crashed', (event) => {` is fired
* DevTools 
`devtools was disconnected from the page. Once page is reloaded, DevTools will automatically reconnect.`
* If you reload in the above state, the screen will be drawn.

I think the change between electron13.6.1 and electron14.0.0, especially app.allowrendererprocess reuse,  is relevant.

**Comment by codebytere** [comment] 2021-11-16 13:08
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by HarunoOi** [comment] 2021-11-22 02:58
Thank you. I'm preparing a standalone testcase now.
There are also new things to discover.

I'm calling my own module in preload js (image_display_modules.js), 
but when I comment out that part `require("my-module");` , the screen doesn't crash.

Are there any 'require module' related changes between 13 and 14?

**Comment by codebytere** [comment] 2022-01-10 14:40
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-01-10 14:40 UTC
Labels: bug :beetle:, blocked/need-repro
