### ISSUE TITLE
3.0 regression: spurious did-fail-load(net::ERR_ABORTED) emits for successful form posts

### ISSUE THREAD

**Issue by bughit** [electron/electron#14004] opened 2018-08-09 19:30 UTC
* Electron Version: v3.0.0-beta.4 x86
* Operating System (Platform and Version): win7 x64 sp1
* Last known working Electron version: 2.0.7 x86

**Expected Behavior**
no did-fail-load events for successful posts

**Actual behavior**
did-fail-load events for successful posts
here's the output from the repro steps
```
storages cleared

did-start-navigation: file:///C:/tmp/form_post.html

did-navigate: 200 file:///C:/tmp/form_post.html

did-finish_load

did-start-navigation: http://example.org/

did-navigate: 200 http://example.org/

did-fail-load:
{ errorCode: -3,
  errorDescription: '',
  validatedURL: 'http://example.org/' }

did-finish_load
```

**To Reproduce**

##### run
```
electron test_app.js file://path_to/form_post.html
```

##### test_app.js
```js
'use strict';

//debugger;

const {app, BrowserWindow, session} = require('electron');

let brWin;

app.on('ready', async () => {

  await new Promise(resolve => session.defaultSession.clearStorageData({storages: ['cookies', 'localstorage', 'cachestorage']}, () => {
    console.log('storages cleared\n');
    resolve();
  }));
  
  brWin = new BrowserWindow({
    width: 1366,
    height: 768,
    webPreferences: {
      nodeIntegration: false,
    },
  });
  
  brWin.webContents.on('did-start-navigation', (event, url, isInPlace, isMainFrame, frameProcessId, frameRoutingId) => {
    if (isMainFrame && !isInPlace)
      console.log('did-start-navigation: %s\n', url);
  });

  brWin.webContents.on('did-navigate', (event, url, httpResponseCode, httpStatusText) => {
    console.log('did-navigate: %i %s\n', httpResponseCode, url);
  });
  
  brWin.webContents.on('did-fail-load', (event, errorCode, errorDescription, validatedURL, isMainFrame, frameProcessId, frameRoutingId) => {
    if (isMainFrame)
      console.log('did-fail-load:\n%O\n', {errorCode, errorDescription, validatedURL});
  });
  
  brWin.webContents.on('did-finish-load', event => {
    console.log('did-finish_load\n');
  });
  
  brWin.loadURL(process.argv[2]);
  //brWin.webContents.openDevTools({mode: 'right'});
  
});

app.on('window-all-closed', () => app.exit());
```

##### form_post.html
```html
<form action="http://example.org/" method="post">
  <input type="submit" name="submit">
</form>
```

**Comment by bughit** [comment] 2018-08-09 19:46
@zcbenz 

In `WebContents::DidFinishNavigation` `ERR_ABORTED` is explicitly ignored

```c++
    // Do not emit "did-fail-load" for canceled requests.
    if (code != net::ERR_ABORTED)
      Emit("did-fail-load", code, description, url, is_main_frame,
           frame_process_id, frame_routing_id);
```

but these are legitimate `ERR_ABORTED`, the ones in this bug are coming from `WebContents::DidFailLoad`, so presumably from libcc, so it seems it would be wrong to just ignore them on the electron side and they need to be fixed at the source?

**Comment by ckerr** [comment] 2018-08-09 20:01
That code in `WebContents::DidFinishNavigation` [2+ years old](https://github.com/electron/electron/blame/152422af812631c6afb6a5e129a780b77559cdf0/atom/browser/api/atom_api_web_contents.cc), so it's unlikely to be the cause of this regression

**Comment by bughit** [comment] 2018-08-09 20:08
I am not suggesting it is, I mentioned that the relevant emit for this bug is in WebContents::DidFailLoad.

DidFinishNavigation is only interesting because it ignores ERR_ABORTED but I don't think this makes sense in this case because these are not legitimate  ERR_ABORTED.

**Comment by bughit** [comment] 2019-04-04 18:48
this should be labeled for 4.x and 5.x

@zcbenz You (the project) evidently believe this is not worth fixing, could you at least say why?

**Comment by felixrieseberg** [comment] 2019-04-04 19:44
@bughit We're all just volunteers here – as you can tell, Electron as a project doesn't employ any engineers and doesn't charge users anything to use.

If you're asking people for reasons why _they_ haven't worked on it, may I ask you why you haven't fixed it yet?

**Comment by bughit** [comment] 2019-04-05 15:15
Thank you for reminding me that this is an open-source project. However project management still goes on here. There are project boards and bug triage.

This issue for instance was reported on v3.0.0-beta.4 and made it to the the active board of the 3.0 project. So it was clearly given a higher priority initially, but subsequently de-prioritized and essentially shelved, without comment. I just would like to understand why, is that ok?

**Comment by lee-dohm** [comment] 2019-04-09 22:55
@bughit, your track record of actionable, well-detailed bug reports is appreciated. However, it doesn't excuse passive-aggressive comments like "why is this being ignored" and "you evidently believe this is not worth fixing". Such language is considered against [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). Please moderate yourself with a less antagonistic tone.

This is not the first time that you've had to be warned for an adversarial tone. If it continues, you will be banned for a week.

That said, I believe the maintainers also share some blame: we made the project boards public to increase transparency, but haven't always done a good job of annotating issues when moving them between columns. That includes #14004, so I can understand your frustration in not knowing why it was moved from Blocks to Doesn't Block. Moreover, saying "this is open source" is not an excuse for lack of transparency -- quite the opposite, in fact. In future, we'll try to do a better job of annotating issues when changing their project board priority.

**Comment by rozumny** [comment] 2019-05-28 07:31
Getting did-fail-load on 3.0.X to 5.0.2 when I run http POST and receive 303 redirection. I fixed it by downgrading to version  2.0.18

**Comment by meetDeveloper** [comment] 2019-07-12 09:07
This issue is happening in our work environment too, we also have custom OAuth login and it often fails, I suppose it is because of some race condition.

**Comment by harryi3t** [comment] 2019-07-12 09:37
@lee-dohm @codebytere 
Since this is happening on 4.x and 5.x versions too, could you update the labels? This would help others who are planning to migrate to these newer versions.

Thanks :)

**Comment by meetDeveloper** [comment] 2019-07-17 11:59
This is causing serious changes in our architecture, and stopping us from having many flows, can you guys look at it @lee-dohm

**Comment by gannons** [comment] 2019-09-04 15:19
Noticed in our setup too when connecting to our custom oAuth

https://idbroker.webex.com/idb/oauth2/v1/authorize

**Comment by electron-triage** [comment] 2020-02-19 20:19
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:20
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:20 UTC
Labels: 3-0-x, 4-2-x, 5-0-x, blocked/need-info ❌, bug/regression :leftwards_arrow_with_hook:, component/plznavigate, platform/windows, status/confirmed
