### ISSUE TITLE
need support for accept field of html5 file input

### ISSUE THREAD

**Issue by marswong** [electron/electron#11104] opened 2017-11-13 07:36 UTC
* Electron version: 1.7.9
* Operating system: macOS 10.13.1

### Expected behavior

user can only choose audio files

### Actual behavior

the `accept` field doesn't work at all, user can choose any files

### How to reproduce

use [electron-with-create-react-app](https://github.com/csepulv/electron-with-create-react-app) to build a mvp:

```
git clone https://github.com/csepulv/electron-with-create-react-app.git
cd electron-with-create-react-app/
npm install
npm run dev
```

and then just add a file input to the `App.js`:

```html
<input type="file" accept="audio/*" />
```

**Comment by Nikitikitavi** [comment] 2017-11-16 18:57
Hi, any new info on it? Have same problem. Maybe you have alternative ways?

**Comment by echoes221** [comment] 2017-11-21 15:06
Finding this as well. It looks like it was fixed in a previous release but it's no longer working again. https://github.com/electron/electron/issues/1768

**Comment by marswong** [comment] 2017-11-22 00:54
it seems that it lack a unit test for it

**Comment by Voyager-One** [comment] 2017-12-19 02:06
same issue :(

**Comment by dengyaolong** [comment] 2018-01-05 06:06
I think it cause by this commit:
https://github.com/mattermost/desktop/issues/497#issuecomment-355463151

**Comment by marswong** [comment] 2018-01-05 08:59
refer to #9745:
@yuya-oc Excuse me, could you explain why it should allow all files when extension is specified? It equals to disabling filters. Thank you :)

**Comment by dengyaolong** [comment] 2018-01-05 13:57
here is  my pull request, https://github.com/electron/electron/pull/11573  @yuya-oc

**Comment by yuya-oc** [comment] 2018-01-05 15:14
@marswong Our app assumed the case where the file has unexpected extension (however its content is correct). I could create a custom dialog if the app was built on BrowserWindow. But our app is using webview and core features work in it, so I couldn't use such approach.

Chrome has an option to select "All Files" filter even when the accept field is specified. It's very convenient in our case. So I wanted similar feature, but my PR was not tested enough on Mac.

@dengyaolong As I wrote at https://github.com/mattermost/desktop/issues/497#issuecomment-355573835, the PR looks good to me.

**Comment by codebytere** [comment] 2018-01-23 14:13
Closing as duplicate of https://github.com/electron/electron/issues/11456, we'll try to get https://github.com/electron/electron/pull/11573 reviewed by EOD.

**Closed by codebytere** 2018-01-23 14:13 UTC
Labels: platform/macOS, triaged/bug, version/1.7.x
