### ISSUE TITLE
window.alwaysOnTop` no longer work in Electron versions above v6

### ISSUE THREAD

**Issue by lacymorrow** [electron/electron#23614] opened 2020-05-15 21:11 UTC
The other issue is tagged V7 so I'm creating this for visibility.
Link: https://github.com/electron/electron/issues/20933

Issue Details
Electron Version:
7 - 9, possibly above
Operating System:
Windows 10
Last Known Working Electron version:
6.0.7
Expected Behavior
BrowserWindow with alwaysOnTop should remain above other windows even after losing focus.

Actual Behavior
The BrowserWindow keeps focus when being launched but after changing properties on the window and losing focus, the window goes behind the focused window.

To Reproduce
You can reproduce using a small utility repo here: lacymorrow/crossover.

The package.json starts with a working Electron v6.0.7.

$ git clone https://github.com/lacymorrow/crossover.git
$ npm install
$ npm start
Test that window stays above other focused windows, and toggle a few times with CTRL+SHIFT+X.

rm -rf node_modules and change the Electron version in package.json to 7.0.0

$ npm install
$ npm start
Toggle with CTRL+SHIFT+X and focus another window. The Electron window loses focus.

To see the problem immediately you can use the executable from the releases page here: lacymorrow/crossover/releases

v0.2.12 Uses Electron v7 and exhibits the issue
v0.2.13 Uses Electron v6.0.7 and works as expected

**Comment by HashimotoYT** [comment] 2020-05-15 21:15
Duplicate of #20933

**Closed by HashimotoYT** 2020-05-15 21:15 UTC

**Comment by lacymorrow** [comment] 2020-05-16 08:13
Thanks for marking @HashimotoYT!
