### ISSUE TITLE
[Bug]: disable-gpu switch doesn't disable the GPU

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#28164] opened 2021-03-12 20:51 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Last Known Working Electron version

6.1.9

### Expected Behavior

I expect that passing the `disable-gpu` switch (`app.commandLine.appendSwitch("disable-gpu")`) will disable the GPU. Similarly, I expect that calling `app.disableHardwareAcceleration` will prevent the GPU process from spawning (though it may do other things as well)

### Actual Behavior

the GPU process spawns

main.js:
```
const {app, BrowserWindow} = require('electron');

app.commandLine.appendSwitch("disable-gpu");

app.on('ready', () => {
	const mainWindow = new BrowserWindow();
	mainWindow.loadURL("https://google.com");
});
```

GPU process will spawn.

I've been working around this by doing:

```
app.disableHardwareAcceleration();
app.commandLine.appendSwitch("disable-software-rasterizer");
```

I believe just calling `app.disableHardwareAcceleration()` used to work (to prevent GPU from spawning), but now it doesn't.

This is a continuation of [this closed issue](https://github.com/electron/electron/issues/20702).

[There](https://github.com/electron/electron/issues/20702#issuecomment-594852742) I discovered this:

>Passing the --disable-gpu and --disable-software-rasterizer switches to Chrome 80 prevents the GPU process from starting.

>Passing these switches via app.commandLine.appendSwitch in addition to calling app.disableHardwareAcceleration() prevents the GPU process from starting in Electron 6.1.9 (latest Electron 6 patch), but stopped working in Electron 7.0.0-beta.1 (earliest Electron 7).

>The Chromium version between the two Electron versions changed from 76.0.3809.146 to 78.0.3866.0. Maybe something in Chromium broke this.

>When loading chrome://gpu in Electron 6 vs 7beta:
"Metal" disabled in 6; not present in 7
"Multiple Raster Threads" disabled in 6; enabled in 7
"Surface Control" disabled in 6; not present in 7
"Surface Synchronization" enabled in 6; not present in 7
"WebGL/GL2" disabled in 6; "software only, hardware acceleration unavailable" in 7

**Comment by nornagon** [comment] 2021-03-15 20:55
This is a Chromium implementation detail, we don't do anything special to mess with the GPU process launch criteria. I suspect Chromium chooses to launch a separate GPU process even when hardware acceleration is disabled for stability reasons (i.e. so that the GPU process can be restarted after a crash without taking the whole browser down).

You might have luck with `--in-process-gpu`, but I'm going to close this as it's not a bug in Electron.

**Closed by nornagon** 2021-03-15 20:55 UTC
Labels: 12-x-y, bug :beetle:, platform/windows
