### ISSUE TITLE
[Bug]: webview can't open "https://play.google.com/store/apps"

### ISSUE THREAD

**Issue by lzdyes** [electron/electron#30284] opened 2021-07-27 06:29 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.7

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.1110

### What arch are you using?

x64

### Expected Behavior

The website is displayed normally

### Actual Behavior

is a blank page

### Additional Information

If used BrowserWindow, "https://play.google.com" It can be displayed successfully.

**Comment by hrishikeshnikam2000** [comment] 2021-07-29 18:48
It works on my System and the specifications are same.

**Comment by clavin** [comment] 2021-08-03 01:23
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #25469. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by clavin** 2021-08-03 01:23 UTC
Labels: bug :beetle:
