### ISSUE TITLE
Cursor can't be hidden on a webview

### ISSUE THREAD

**Issue by jbleuzen** [electron/electron#7747] opened 2016-10-26 08:43 UTC
- Electron version: 1.4.4
- Operating system: macOS

Cursor can't be hidden when I'm hovering a webview. It's not working but I'm not sure it can be done...

I made a repo that show the issue : [https://github.com/jbleuzen/electron-webview-cursor](https://github.com/jbleuzen/electron-webview-cursor)

**Comment by zeke** [comment] 2016-10-27 21:23
Thanks for creating that repo. I can confirm that the `cursor` property is not respected in the webview, regardless of the value used.

https://github.com/electron/electron/issues/1222 looks like a related issue, but no solution yet.

**Comment by zcbenz** [comment] 2016-11-16 01:39
This seems to be an upstream Chromium issue.

**Comment by MBALOTA** [comment] 2016-11-24 16:49
Is there any way to fix it or write a bug ticket for chromium? ._. **This bug is annoying the hell out of me.**

**Comment by jbleuzen** [comment] 2016-11-24 17:22
Yes me too, I would to help but I dont know how to do a bug ticket on Chromium...

**Comment by MBALOTA** [comment] 2016-11-24 18:03
It's really weird that only hidden doesn't work. The other ones work as far as I know.

**Comment by MBALOTA** [comment] 2016-11-24 18:06
When the mouse isn't moving its visible, when I move the mouse it hides the courser for a "split second" and it shows it again. Using electron 1.4.8 on Windows 7 and yes I know it might be a chromium bug.

**Comment by fallafeljan** [comment] 2017-01-16 15:45
Any news on this? Same issue here, Electron 1.4.7 on macOS 10.12.2. Setting the cursor to `pointer` or `none` on the container will affect only the container, but not the webview itself.

**Comment by Splder** [comment] 2017-03-24 08:53
I found that setting the view you would like to change the cursor to:
`display: inline-block;`
or
`float: left;`
would make it work

**Comment by FibreFoX** [comment] 2018-08-27 14:03
Is there any progress on this one? Any plans or something?

**Comment by markuslerner** [comment] 2019-10-18 17:01
This worked best for me (overriding cursor for all elements):
```
let css = `* { cursor: ${visible ? 'auto' : 'none'} !important; }`;
win.webContents.insertCSS(css);
```

**Comment by electron-triage** [comment] 2021-03-09 17:06
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 17:06 UTC
Labels: bug :beetle:, component/webview

**Comment by FibreFoX** [comment] 2021-03-09 18:23
I hate these auto-close bots ....
