### ISSUE TITLE
Electron 9.x + Redux DevTools: Store not found

### ISSUE THREAD

**Issue by petef19** [electron/electron#24638] opened 2020-07-19 01:42 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
9.1.0
* **Operating System:**
Win10 x64
* **Last Known Working Electron version:**
8.4.0

### Expected Behavior
Redux DevTools should find the store, which exists.

### Actual Behavior
Redux tab is added to Chome devtools, but clicking on the tab displays the message `No store found. Make sure to follow the instructions.`. Running the exact same minimal app in Electron 8.4.0 does show the store.

This has been mentioned at electron-devtools-installer [here](https://github.com/MarshallOfSound/electron-devtools-installer/issues/130) and now is indicated as an Electron issue.

### To Reproduce
electron package.json
```
{
    "name": "electron_3",
    "version": "1.0.0",
    "description": "",
    "main": "main.js",
    "scripts": {
        "start": "electron .",
        "install": "electron-rebuild",
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "electron": "^9.1.0",
        "electron-devtools-installer": "^3.0.0"
    }
}
```

Ng package.json

```
{
    "name": "test",
    "version": "0.0.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "~9.1.11",
        "@angular/common": "~9.1.11",
        "@angular/compiler": "~9.1.11",
        "@angular/core": "~9.1.11",
        "@angular/forms": "~9.1.11",
        "@angular/platform-browser": "~9.1.11",
        "@angular/platform-browser-dynamic": "~9.1.11",
        "@angular/router": "~9.1.11",
        "rxjs": "~6.5.4",
        "tslib": "^1.10.0",
        "zone.js": "~0.10.2",
        "ngx-electron": "^2.2.0",
        "@ngrx/effects": "^9.2.0",
        "@ngrx/store": "^9.2.0"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.901.8",
        "@angular/cli": "~9.1.8",
        "@angular/compiler-cli": "~9.1.11",
        "@types/node": "^12.11.1",
        "@types/jasmine": "~3.5.0",
        "@types/jasminewd2": "~2.0.3",
        "codelyzer": "^5.1.2",
        "jasmine-core": "~3.5.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~5.0.0",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage-istanbul-reporter": "~2.1.0",
        "karma-jasmine": "~3.0.1",
        "karma-jasmine-html-reporter": "^1.4.2",
        "protractor": "~7.0.0",
        "ts-node": "~8.3.0",
        "tslint": "~6.1.0",
        "typescript": "~3.8.3",
        "@ngrx/schematics": "^9.2.0",
        "@ngrx/store-devtools": "^9.2.0"
    }
}
```

Create a minimal store in Ng project. Then open Electron app. In Electron 8.4.0 you'll see the Store interface in the Redux tab in DevTools, in Electron 9.x you'll see the above message. see pics below.

### Screenshots
**Electron 8.4.0**
![redux_8 4 0](https://user-images.githubusercontent.com/67035258/87865177-da804100-c926-11ea-9f9f-4d90119fc29c.png)

**Electron 9.1.0**
![redux_9 1 0](https://user-images.githubusercontent.com/67035258/87865132-30a0b480-c926-11ea-9411-efecfb979699.png)

**Comment by DmitryMK** [comment] 2020-07-19 21:30
That is a general problem of all extension in v9.0.0+, probably linux-specific. So it looks like a duplicate of the following issue: https://github.com/electron/electron/issues/24011

**Comment by petef19** [comment] 2020-07-19 22:15
we're on Win10 x64 - not Linux

**Comment by gnujeremie** [comment] 2020-07-24 13:30
having the same problem on MacOS

**Comment by danielweck** [comment] 2020-07-25 17:27
MacOS here, same problem.

**Comment by danielweck** [comment] 2020-07-25 17:31
I must say, sometimes the Redux Dev Tools tab works, so I guess it is a timing issue. See this "workaround" here: https://github.com/electron/electron/issues/23662#issuecomment-656756927

**Comment by petef19** [comment] 2020-07-26 07:52
> I must say, sometimes the Redux Dev Tools tab works, so I guess it is a timing issue. See this "workaround" here: [#23662 (comment)](https://github.com/electron/electron/issues/23662#issuecomment-656756927)

I tried the approach from the example from your link by either loading the Chrome extension directly (as the post did) or by loading it via `electron-devtools-installer` - both still result in `No store found. Make sure to follow the instructions.` on Electron 9.1.1...

**Comment by hebronivy** [comment] 2020-07-28 10:03
Same problem in MacOS 10.15.6.Store not found.  
The first time when I upgrade electron9.1.1, dev tools opened the Redux tab successfully.But failed every time after that.  
With console error:  
![image](https://user-images.githubusercontent.com/34730612/88651789-a2ce8180-d0fc-11ea-8dcf-4111a4984978.png)

**Comment by amalcaraz** [comment] 2020-08-11 14:03
Any progress in this?

**Comment by lpillonel** [comment] 2020-08-28 14:13
Also having issues with this on version 9.1.1 (and 10.1.0). Had to downgrade to 8.5.0 to have thing working again

**Comment by mgwo** [comment] 2020-10-28 18:17
Any progress? I have the same

**Comment by SolarIceMedia** [comment] 2020-11-20 06:34
works for me, did you install both the redux dev tools extention and the @ngrx/store-devtools ?

**Comment by SolarIceMedia** [comment] 2020-11-20 06:39
![Screenshot from 2020-11-19 22 38 17](https://user-images.githubusercontent.com/72262951/99767497-fef84f80-2ab7-11eb-8031-742c990f1ed3.png)
what I get with a simple quick test the button styles are wacked but its an app I've been building that I eventually need the store in so I just tossed a quick test into it

**Comment by SolarIceMedia** [comment] 2020-11-20 06:43
dunno about Windows or MacOS I use Elementary-OS (Ubuntu Linux based)

**Comment by SolarIceMedia** [comment] 2020-11-20 06:46
only other thing I can think of is this is my app.on ready:
```
app.on("ready", () =>
{
	setTimeout(createWindow, 400);
	installExtension(REDUX_DEVTOOLS)
		// eslint-disable-next-line @typescript-eslint/restrict-template-expressions
		.then((name) => console.log(`Added Extension:  ${name}`))
		.catch((err) => console.log("An error occurred: ", err));
});
```

**Comment by petef19** [comment] 2020-11-20 11:36
doesn't work, just tested Electron 10.1.6 w/ Ng 11.0.2 on Win 10 - same behavior as on Electron 9.x, there is a REDUX tab but clicking on it shows `No store found. Make sure to follow the instructions.`

**Comment by petef19** [comment] 2020-11-21 00:25
I also just tested this with latest Electron 11.0.2 - exact same behavior, Redux tab shows that it cannot find the store.

Using the exact same Ng build on Electron 8.5.5 does work.

All on Win 10 here.

PLEASE HELP !!!

**Comment by jhlee8804** [comment] 2020-12-23 08:52
+!

**Comment by brioapp** [comment] 2020-12-26 08:47
+1

**Comment by daszkowski** [comment] 2020-12-28 11:05
+1

**Comment by Hybueno09** [comment] 2021-01-21 09:20
Any progress?

**Comment by calumpwebb** [comment] 2021-01-31 07:38
Any progress?

**Comment by leohxj** [comment] 2021-02-19 08:43
Electron@11.2.3 also show: `No store found. Make sure to follow the instructions.`

**Comment by Hybueno09** [comment] 2021-03-17 01:15
Hi,any progress?

**Comment by nornagon** [comment] 2021-03-17 22:39
Duplicate of #23662

**Closed by nornagon** 2021-03-17 22:39 UTC
Labels: 10-x-y, 11-x-y, 9-x-y, component/devtools

**Comment by petef19** [comment] 2021-04-09 03:04
was finally able to get this working on Win10 w/ Electron 12.0.2 by loading the extension directly (NOT via 'electron-devtools-installer' package)

**Comment by Hybueno09** [comment] 2021-04-09 07:21
@petef19  how did u do that?Is there any demo?

**Comment by petef19** [comment] 2021-04-11 21:17
> @petef19 how did u do that?Is there any demo?

loaded it when app is ready...

```
app.on('ready', async() =>
{
       const ext_fp = '<path to Chrome extension>';
        await session.defaultSession.loadExtension(ext_fp, {allowFileAccess: true});
});
```

Electron 12.0.2
Redux DevTools 2.17.0 installed in local Chrome
Win 10 x64

**Comment by shahkeyur** [comment] 2021-07-08 20:30
Had same issue.

Moving installExtenstion to app's 'ready' event instead of 'did-finish-load' of webcontents worked like a charm.

**Comment by JeremyRubin** [comment] 2021-08-27 23:47
note: whenReady seems to trigger at the wrong time, but on('ready') seems ok!

**Comment by Firshta** [comment] 2022-08-19 20:20
> note: whenReady seems to trigger at the wrong time, but on('ready') seems ok!

can you give a specific example on how this is done?

**Comment by Firshta** [comment] 2022-08-19 20:22
> Had same issue.
> 
> Moving installExtenstion to app's 'ready' event instead of 'did-finish-load' of webcontents worked like a charm.

can you give specific example on how this is done please?
