### ISSUE TITLE
Unable to list files recursively from folder in Electron using webkitdirectory

### ISSUE THREAD

**Issue by saikrishnadeep** [electron/electron#9002] opened 2017-03-24 08:35 UTC
I've a input element like `<input type="file" webkitdirectory="" multiple="" name="files[]" id="files"">` which prompts a user to select a folder. I need to get file names & paths of all the files within that folder.
    
    var input = document.getElementById('files');
    input.onchange = function(e) {
        var files = e.target.files; // File list
        for (var i = 0; i < files.length; ++i) {
          
          var fpath = files[i].webkitRelativePath;
          var ftype = files[i].type;
          var fsize = files[i].size;
          
          console.log(fname)
          }
        }

This works perfectly fine when run from chrome web browser as shown here: https://jsfiddle.net/7prshjfz/. However, when I try to run the same app via electron it gives ONLY the folder name and nothing else. When I tried to debug further, I released that when a folder is selected, only the folder name, size, modified etc details are available.

Therefore, clearly there is a different implementation of `webkitdirectory` in electron.  Is this an intended implementation?

**My Problem:** I know I can use the `dialog.showOpenDialog` and read the `fs` using the directory path. But, I find this to be a bad solution for my case (or perhaps for anyone) because, I want my code to be minimal for the sake of the web app. I want to reuse as much of the functionality from the webapp with additional implementation in Electron and NodeJS. I would be grateful to know if there is any special implementation of webkitdirectory that works BOTH in an Internet Browser and Electron app with minimal modifications, for instance, to the above displayed code/ jsFiddle.

I'm not sure If  I this is a missing feature/ bug or neither. Any feedback will be appreciated :)

**Comment by MarshallOfSound** [comment] 2017-03-24 12:57
@saikrishnadeep Can you verify your code works in Chromium 56, latest chrome might act differently / fix this issue 👍

**Comment by saikrishnadeep** [comment] 2017-03-24 19:42
@MarshallOfSound Yes, it does work on the latest version of Chromium and not in  Electron. However, if you meant to ask if it worked on a earlier version of Chromium, then I can assure you it has been working over the last 1 and a half years of Chromium releases with no bugs to the above code. This was implemented on one of my websites and it did exactly what it does not back then as well.

**Comment by kevinsawicki** [comment] 2017-03-31 21:55
This looks like a duplicate of https://github.com/electron/electron/issues/839, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2017-03-31 21:55 UTC
