### ISSUE TITLE
Chromium as a shared resource?

### ISSUE THREAD

**Issue by dragonDScript** [electron/electron#26426] opened 2020-11-10 18:54 UTC
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Duplicates
First of all, these duplicates are questions; not discussions so this issue can be open yet.
[#10861](https://github.com/electron/electron/issues/10861)

Hello guys, so, in the past months I've been using Electron and I have to say that it's a really good framework. But I've found the great issue; app size.

Electron apps are way TOO BIG, more than they shouldn't. I know that this is because of the Chromium engine who needs to be packaged with Electron.

My question would be...
**Why not package Chromium as a shared resource (per system or per user)**
This could work like Node Modules do; every Electron version has a chromium engine. So if for example, Discord has electron 7 and vscode does too we are reducing app size.

This could be done as an optional electron-builder/packager/forge option.

**Comment by nornagon** [comment] 2020-11-10 19:36
Duplicate of #673

**Closed by nornagon** 2020-11-10 19:36 UTC
