### ISSUE TITLE
[Bug]:  pageRanges options  doesn't work in silent print

### ISSUE THREAD

**Issue by sunchanglong** [electron/electron#31890] opened 2021-11-18 08:12 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.1

### What operating system are you using?

Windows

### Operating System Version

window 10

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

5 pages in total, print with `pageRanges: [{from: 0, to: 2}]`, print first three pages.

### Actual Behavior

it won't do print task. if i select Microsft Pdf Printer,  the pdf file created is broken, can't be opend.
if i remove the pageRanges key from options, it works.

**Comment by sunchanglong** [comment] 2021-11-18 08:16
#26318

**Comment by codebytere** [comment] 2021-11-18 08:53
Duplicate of https://github.com/electron/electron/issues/26318

**Closed by codebytere** 2021-11-18 08:53 UTC
Labels: bug :beetle:
