### ISSUE TITLE
[Bug]: Forked process immediately exits in production

### ISSUE THREAD

**Issue by mikecbone** [electron/electron#29125] opened 2021-05-12 17:18 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

Other Linux

### Operating System Version

Linuxmint 20.1 ulyssa - x86_64 Linux 5.4.0-73-generic

### What arch are you using?

x64

### Expected Behavior

Production build `const { fork } = require('child_process');`  to run same as in development.

### Actual Behavior

In development, the forked js file works as intended. In production, the forked js file immediately exits with exitCode 1

### Additional Information

Electron-Vue app using [Vue-Cli-Plugin-Builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#notes).

Render calls a method in main via IPC. This calls a method from an imported custom script, which in turn forks some child processes to handle some work. Then they all resolve back up to the render process.

Works fine in development, but in production once built, the forked process immediately exits. 

Thought it was down to not being able to [fork a script that is in the asar](https://github.com/electron/electron/issues/7688), so used [electron-builders extra-resources](https://www.electron.build/configuration/contents#extraresources) to keep them outside but this didn't change anything.

Originally was using [execa.node](https://github.com/sindresorhus/execa#execanodescriptpath-arguments-options) but this didn't work in production as it just kept opening new electron windows for each forked process instead.

I have looked into this [issue](https://github.com/electron/electron/issues/6656), but it hasn't cleared anything up for me because as far as I can tell the issue there is a forked process can't access any of electrons methods but my forked processes do _not_ require any electron methods.

```js
// ./background.js
import forkProcess from '@/scripts/forkedProcessManager ';

ipcMain.handle('_TEST_', async (event, arg) => {
  const workerPath = process.env.NODE_ENV === 'development'
    ? path.resolve('src/scripts/forkedProcessWorker.js')
    : path.join(path.dirname(__dirname), 'scripts', 'forkedProcessWorker.js');
  const result = await forkProcess(arg, workerPath);
  return result;
});
```

```js
// ./src/scripts/forkedProcessManager.js

const { fork } = require('child_process');
const data= require('./data.json');

function manager(name, workerPath) {
  let index = 0;
  let running = 0;
  const limit = 8;
  const output = [];
  const keys = Object.keys(data);

  return new Promise((resolve) => {
    function createWorker() {
      try {
        while (running <= limit && index < keys.length) {
          const worker = fork(workerPath);
          worker.on('message', (response) => {
            output.push(response);
          });
          worker.on('exit', () => {
            running -= 1;
            createWorker();
          });
          worker.send({ key: keys[index], name });
          running += 1;
          index += 1;
        }
        if (index === keys.length && running === 0) {
          resolve(output);
        }
      } catch (error) {
        console.log(error);
      }
    }
    createWorker();
  });
}

async function forkProcess(name, workerPath) {
  const resolveResult = await manager(name, workerPath);
  return resolveResult;
}

export default forkProcess;
```

```js
// ./src/scripts/forkedProcessWorker.js

const got = require('got');
const data= require('./data.json');

function doSomeStuff(msg) {
// ...
}

process.on('message', (msg) => {
  doSomeStuff(msg).then((resultString) => {
    process.send(resultString);
  }).finally(() => {
    process.exit(0);
  });
});

```

```js
// vue.config for the extra-resources
module.exports = {
  pluginOptions: {
    electronBuilder: {
      preload: 'src/preload.js',
      builderOptions: {
        extraResources: [
          {
            from: './src/scripts/',
            to: 'scripts',
          },
        ],
      },
    },
  },
};

```

**Comment by jkleinsc** [comment] 2021-05-12 20:34
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2021-05-19 14:33
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2021-05-19 14:33 UTC
Labels: 12-x-y, blocked/need-repro, bug :beetle:, platform/linux

**Comment by leopucci** [comment] 2021-06-23 16:25
@mikecbone have you suceeded?
I am having the same problem

**Comment by davidsmartwei** [comment] 2021-07-12 10:17
I have the same problem too

**Comment by jayczech23** [comment] 2021-12-02 04:03
I am having this issue as well, more specifically when trying to run a child_process on Windows 10 platform. (packaged using `electron-forge`'s Squirrel maker.

**Comment by lucic42** [comment] 2022-01-30 00:28
Any update/solution, i am also facing this issue.

**Comment by Visual-Dawg** [comment] 2022-12-21 14:03
Same here

**Comment by mulgurul** [comment] 2023-04-25 20:42
Is it possible for someone in the electron team to point us to a working example of using utilityProcess.fork which also works when packaged and run in production. Seems after searching and reading all I can find, that it is very difficult to find any working solution examples, instead only discussions of many problems occurring.

**Comment by jharrisonio** [comment] 2024-07-21 02:33
I've raised a new ticket with minimum repro here: #42978
