### ISSUE TITLE
[Bug]: the latest document example not working

### ISSUE THREAD

**Issue by tiny-ant** [electron/electron#30513] opened 2021-08-12 15:46 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.4

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

the example code is from here: https://www.electronjs.org/docs/latest/api/ipc-main
and I just created a new BroserWindow like this:

```js
let mainWindow = new BrowserWindow({
    WebPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    }
}
mainWindow.loadFile('index.html')
```

### Actual Behavior

I found that no matter wether `contextIsolation` or `contextIsolation` is turned on or off, I can't see the result as expected.

when i paste the code in my editor and launched the devtools, i saw a `Uncaught ReferenceError: require is not defined`.
some of my code worked in older electron, I'm just learning the new API，but  I'm really confused how to ge help from the offcial documentation...

**Comment by codebytere** [comment] 2021-08-17 17:42
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by MarshallOfSound** [comment] 2021-08-19 18:05
@tiny-ant You have a typo in your code, it should be `webPreferences` not `WebPreferences`. (note the lower case `w`)

**Closed by MarshallOfSound** 2021-08-19 18:05 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, 13-x-y
