### ISSUE TITLE
Clean memory 

### ISSUE THREAD

**Issue by fabdelgado** [electron/electron#7038] opened 2016-08-30 18:04 UTC
* Electron version: 1.3
* Operating system: Windows

My app load images every 1 minute and RAM memory is full in electronjs.

**Comment by zcbenz** [comment] 2016-08-31 11:51
Can you provide a minimal app that can reproduce this problem?

**Comment by bpasero** [comment] 2016-09-13 05:47
Looks like https://github.com/electron/electron/issues/6275

**Comment by kevinsawicki** [comment] 2016-09-30 18:02
Closing as duplicate of #6275

**Closed by kevinsawicki** 2016-09-30 18:02 UTC
Labels: more-information-needed
