### ISSUE TITLE
TypeScript translation broken for NodeJS.Process

### ISSUE THREAD

**Issue by jayem9000** [electron/electron#9626] opened 2017-05-30 23:03 UTC
* Electron version: 1.7.2 beta
* Operating system: All

### Expected behavior
```
// Should compile successfully.
process.on('uncaughtException', recordException);
```

### Actual behavior
```
// Fails to compile because electron.d.ts overrides the `on` method.
process.on('uncaughtException', recordException);
```

### How to reproduce
Update the repo to electron 1.7.2. Use TypeScript. Create a module and copy/paste the code snippet above. If using an IDE with TypeScript IntelliSense (i.e. Visual Studio Code), the 'uncaughtException' will produce the following error

>[ts] Argument of type '"uncaughtException"' is not assignable to parameter of type '"loaded"'.

**Comment by eanders-MS** [comment] 2017-05-31 18:33
Similarly, In 1.7.2, the 'exit' event is no longer part of NodeJS.Process. Compiling this TypeScript:
```
process.on('exit', function () {});
```
results in this error:
error TS2345: Argument of type '"exit"' is not assignable to parameter of type '"loaded"'.

**Comment by eanders-MS** [comment] 2017-06-01 18:35
My workaround for now:
```javascript
(process as NodeJS.EventEmitter).on('exit', function () {});
```

**Comment by zeke** [comment] 2017-06-01 19:09
Thanks for sharing your workaround, @eanders-MS. We'll get this sorted soon. 👍

**Comment by eugirdor** [comment] 2017-06-05 18:14
I am seeing this in 1.6.10

**Comment by zeke** [comment] 2017-06-07 17:29
Paraphrasing @MarshallOfSound 

> Hm, even nodejs typings don't declare that event
>
> only reason ours errors is because we don't allow the generic string type for event name
> 
> I imagine a bit of hackery around https://github.com/electron/electron-typescript-definitions/blob/master/index.js#L36
>
> to inject the generic string type event handlers would solve that persons error
>
> the correct solution is to patch the nodejs typings to include the `uncaughtException` and `unhandledRejection` events
> 
> but that could take *insert long amount of time here*

**Comment by zeke** [comment] 2017-06-12 17:04
See also https://github.com/electron/electron-typescript-definitions/issues/44 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16486

**Comment by zeke** [comment] 2017-06-12 17:21
Related improvements to `@types/node` just landed, thanks to @mdebruijne: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16705

Not sure what the DefinitelyTyped npm release cadence is, but it should be published soon.

**Comment by eanders-MS** [comment] 2017-06-12 22:10
Here's an interesting one. In 1.7.2 I can no longer do this:
```javascript
['resize', 'move'].forEach(e => mainWindow.on(e, () => {}))
```
(`mainWindow` is of type `Electron.BrowserWindow`)

Would it be possible to expose a fallback `on` that accepts a string for the event?

**Comment by zeke** [comment] 2017-06-12 22:12
>  I can no longer do this

What happens when you try?

**Comment by eanders-MS** [comment] 2017-06-12 22:17
I get this typescript compile-time error: error TS2345: Argument of type 'string' is not assignable to parameter of type '"unresponsive"'.

**Comment by MarshallOfSound** [comment] 2017-06-13 04:12
@eanders-MS I wonder where our generic string types went 😕 I'll investigate

**Comment by craxal** [comment] 2017-06-19 20:56
I've encountered this issue with `process.on` as well:
```
Argument of type '"unhandledRejection"' is not assignable to parameter of type '"loaded"'.
```

My guess is a declaration merge with Node declarations isn't happening as expected?

(Might I suggest adding another label to this issue? This is a compilation problem, not just documentation.)

**Comment by chgibb** [comment] 2017-07-30 02:51
Seeing this in 1.6.11.

**Comment by MarshallOfSound** [comment] 2017-07-30 03:02
With the fix for this landing in `@types/node` all we need to do is bump our dependency in `electron-prebuilt` right @zeke ?

**Comment by zeke** [comment] 2017-08-01 00:06
☝️  right.

**Comment by zeke** [comment] 2017-08-09 16:36
> bump our dependency in electron-prebuilt right @zeke?

prebuilt is actually being [retired](https://github.com/electron-userland/electron-prebuilt/pull/275) so the bump will need to be in https://github.com/electron/electron/blob/master/npm/package.json instead.

**Comment by mgroenhoff** [comment] 2017-12-12 15:01
I am seeing this with Typescript 2.6.2 and Electron 1.7.9. I think this is caused by the fact that the `Process` interface from the original node typings does not contain its own `removeListener` but it is inherited from `EventEmitter` and when the Electron typings augment the node typings it adds the method `removeListener` to the `Process` interface instead of adding an overload for it. This should be fixed by adding the `removeListener` overloads on the original node typings [in this section](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/736ebf768cd4e493adb38538516487713fb77f2a/types/node/index.d.ts#L617-L713).

Current i work arround this by adding a .d.ts file to my project that contains the following
```typescript
declare namespace NodeJS {
	interface Process extends EventEmitter {
		removeListener(event: string | symbol, listener: (...args: any[]) => void): this;
	}
}
```

**Comment by karlfus** [comment] 2018-04-24 23:09
Still seeing this in TS 2.8.1 and Electron 1.7.11.  :cry:

**Comment by miniak** [comment] 2019-05-18 09:17
Are you still seeing this issue with Electron >= 3?

**Comment by rlugge** [comment] 2019-10-02 16:08
@miniak I'm running into with Electron 6.

Here's a [StackOverflow](https://stackoverflow.com/questions/58205153/is-this-typescript-error-about-overloads-not-matching-my-code-or-a-bug-in-the-pr) question from where I couldn't tell if this was me being wrong, or a bug with Electron.  Based on this issue, I'm leaning towards it being an electron issue.

**Comment by ceonizm** [comment] 2019-10-30 13:02
Hello,
I've got the same problem since I've updated to 7.0.0

**Comment by MarshallOfSound** [comment] 2021-05-13 08:34
I don't know how I ended up here, but this is definitely working in Electron 12

**Closed by MarshallOfSound** 2021-05-13 08:34 UTC
Labels: documentation :notebook:
