### ISSUE TITLE
worker_threads does not work correctly in ELECTRON_RUN_AS_NODE mode.

### ISSUE THREAD

**Issue by chris1201** [electron/electron#17030] opened 2019-02-18 17:53 UTC
* **Electron Version**
  * 4.0.5  ( run as node: 10.11.0 )
* **Operating System** (Platform and Version):
  * Windows 10 (1809)
* **Last known working Electron version** (if applicable):
  * N/A

### Expected Behavior
```sh
>node --experimental-worker app.js
hello from electron as node
hello from main thread
hello from electron as node
hello from worker thread
hello from worker
0

>node -v
v10.11.0
```

### Actual behavior
```sh
>electron --experimental-worker app.js
hello from electron as node
hello from main thread

>electron -v
v10.11.0
```

### To Reproduce
[app.js]
```js
console.log("hello from electron as node")
const {
    Worker,
    isMainThread,
    parentPort
} = require('worker_threads');

if (isMainThread) {
    console.log("hello from main thread")
    function createWorker() {
        let worker = new Worker(__filename);
        worker.on('message', (msg) => {
	    console.log(msg);
        });
        worker.on('error', (err) => {
            console.log(err);
        });
        worker.on('exit', (code) => {
            console.log(code);
        });
    }
    createWorker();
} else {
   console.log("hello from worker thread")
   parentPort.postMessage("hello from worker");
}
```

**Comment by tfmeneses** [comment] 2019-06-20 16:58
Hi,

I've the same issue. Have any idea how to fix this?

**Comment by ermod** [comment] 2019-07-11 14:16
I also have this problem on Linux with:
```
Electron v5.0.6
Chromium v73.0.3683.121
Node v12.0.0
v8 v7.3.492.27-electron.0
```

**Comment by codebytere** [comment] 2019-10-03 08:38
Closing as duplicate of https://github.com/electron/electron/issues/18540

**Closed by codebytere** 2019-10-03 08:38 UTC
Labels: 4-2-x, bug :beetle:, platform/windows
