### ISSUE TITLE
[Bug]: v29 `fs` module fails to recognize files containing emojis on Windows

### ISSUE THREAD

**Issue by brianpetro** [electron/electron#41484] opened 2024-02-29 16:35 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Last Known Working Electron version

28

### Expected Behavior

`fs.existsSync` should return true for file paths containing emojis.

### Actual Behavior

`fs.readdirSync` lists files with the emojis; however, calling `fs.existsSync` fails for the same files.

**Comment by brianpetro** [comment] 2024-03-02 01:09
I understand not moving forward on this without a test case, which unfortunately will not be made by myself within the seemingly arbitrary time limit. But automatically closing the issue, essentially pretending that this bug doesn't exist, seems disingenuous to future electron users.

🌴

**Comment by Rn145** [comment] 2024-03-02 23:48
This is a problem of the fs module and encodings. Electron has nothing to do with it.

**Comment by brianpetro** [comment] 2024-03-03 00:14
@Rn145 are you sure about that?

Why would changing from electron 28 to electron 29 cause the issue, with the same node and presumably `fs` version?

**Comment by Rn145** [comment] 2024-03-03 01:33
I can't say anything about switching to another version of Electron. But on a simple script for Node.js (version 20.11.1) I have the same problem with emoticons.
```js
const fs = require('fs');

const files = fs.readdirSync(".");
files.forEach((filename, i)=>{
	console.log(filename, fs.existsSync(filename));
});
```
If he does not accept the filenames that he returned, then this is at least strange.

However, it does not work with a heart.
![image](https://github.com/electron/electron/assets/78321542/284b9ea7-884b-4c69-9ebf-ceb3c6f41d6f)

**Comment by Rn145** [comment] 2024-03-03 02:00
@brianpetro 
I think this is the answer: https://github.com/nodejs/node/issues/48673
they didn't fix it for the LTS version.

**Comment by brianpetro** [comment] 2024-03-03 03:01
@Rn145 thanks for your help in getting to the bottom of this.

What are the implications? Is this going to remain broken in Electron versions that use the affected node  versions?

**Comment by VerteDinde** [comment] 2024-03-04 23:31
@Rn145 Thanks so much for hunting down the root cause in Node, very appreciated! 🙇‍♀️ 

@brianpetro Thanks for the original issue report - I'll see what the status is for getting this fixed in Node 20 LTS, in which case we can update to the fixed version. We could possibly cherry-pick or patch in the libuv fix if needed, we just try to avoid drift with upstream dependencies when we can. I'll check on this and report back.

**Comment by Prinzhorn** [comment] 2024-03-22 20:31
See https://github.com/electron/electron/pull/41673

**Comment by Prinzhorn** [comment] 2024-03-25 07:50
@codebytere the PR was merged, can this be closed as well?

**Comment by codebytere** [comment] 2024-03-25 09:01
Closed in https://github.com/electron/electron/pull/41673

**Closed by codebytere** 2024-03-25 09:01 UTC
Labels: platform/windows, bug :beetle:, blocked/upstream ❌, status/confirmed, 29-x-y
