### ISSUE TITLE
cannot find Chrome binary

### ISSUE THREAD

**Issue by vlinsw** [electron/electron#17939] opened 2019-04-24 06:25 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Selenium Version:**
selenium=3.12
* **Electron Version:**
electron=1.8.7
* **Operating System:**
Windows7
* **Last Known Working Electron version:**:
dont know
### Expected Behavior
    electron Application startup
### Actual Behavior
    The electron application failed to start because of an error
### My Code

	public static void main(String[] args) throws Exception {
              String electronBinary = "C:\\Program Files (x86)\\cochatPC\\cochatPC.exe";
                 String electronBinary = "C:\\Program Files (x86)\\cochatPC\\cochatPC.exe";
		System.setProperty("webdriver.chrome.driver", new File(driverPath).getAbsolutePath());
		ChromeOptions options = new ChromeOptions();
		options.setBinary(electronBinary);
		ChromeDriver driver = null;
		try {
			driver = new ChromeDriver(options);
			System.out.println("start success.");
		} catch (Exception e) {
			if (driver == null) {
				e.printStackTrace();
				System.err.println("driver is null.");
				System.exit(-1);
			}
		}
		WebElement ele = driver.findElement(By.id("//input[@id='kw']"));
		ele.sendKeys("search");
		driver.findElement(By.id("//input[@id='su']")).click();
		Thread.sleep(4000);
		driver.quit();
	}

### Exception

Starting ChromeDriver 2.29 (8e8216e581c512667203931f81c1a1ead47222e5) on port 8431
Only local connections are allowed.
org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.29 (8e8216e581c512667203931f81c1a1ead47222e5),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 96 milliseconds
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'PETER-PC', ip: '10.211.55.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_201'
Driver info: driver.version: ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at com.lenovo.automation.electron.LocalTest.main(LocalTest.java:54)
driver is null.

**Comment by vlinsw** [comment] 2019-04-24 07:01
Has anyone ever had this problem？

**Comment by MarshallOfSound** [comment] 2019-04-24 07:13
Thank you for taking the time to report this issue and helping to make Electron better.

This issue has been marked for closing because this series of Electron has reached end-of-life and is no longer supported.

If you're still experiencing this issue in the latest version of Electron and would like this issue to remain open, please add a comment specifying the version you're testing with and any other information that a maintainer needs to know to reproduce the issue.

I'm setting the blocked/need-info label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-04-26 22:36
@vlinsw Are you experiencing this issue on an Electron version later than 3.0.x? Per our [supported versions policy](https://electronjs.org/docs/tutorial/support#supported-versions), we do not support versions older than 3.0.x.

**Comment by codebytere** [comment] 2019-05-08 01:06
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2019-05-08 01:06 UTC
Labels: blocked/need-info ❌
