### ISSUE TITLE
[Bug]: Custom Draggable Title is not working with electron 15

### ISSUE THREAD

**Issue by LOMFM** [electron/electron#31179] opened 2021-09-28 21:28 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

9.3.0

### Expected Behavior

Custom titlebar with Draggable region would working with the resizable:false browser window.

Browser window property: resizable: false
CSS Property: -webkit-app-region: drag

### Actual Behavior

It is not working with fixed-size browser window.
It is working with only resizable browser window.

**Comment by codebytere** [comment] 2021-09-29 08:32
Duplicate of https://github.com/electron/electron/issues/30788

**Closed by codebytere** 2021-09-29 08:32 UTC
Labels: bug :beetle:
