### ISSUE TITLE
ipcRenderer.invoke | Error: Failed to serialize arguments

### ISSUE THREAD

**Issue by ramaralo** [electron/electron#25017] opened 2020-08-18 15:23 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `9.0.4`
* **Operating System:**
  * macOS `10.14.5`
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

I'm trying to remove the dependency for `remote` module. I currently have `isolationContext` disabled, and on the `preload` file I'm writing directly on the window object creating an API under `window.myApi`. Some of these api methods will need to send and receive data from the main process, so I tried to replace current methods with calls to `ipcRenderer.invoke()`. So on the `preload` file I have:

```javascript
window.myapi = {
    foo: async () => {
        const resp = await ipcRenderer.invoke("channel", [123]);
        console.log(222, resp);
    },
}
```

and on the main process I have:
```javascript
app.on("ready", () => {
ipcMain.handle("channel", (ev, args)=> {
            log.info(111, ev, args);
            return 321;
        });
})
```
When I run the app from source code, I'd expect message to be sent without any errors.

### Actual Behavior

When I run the app from source code, after the app starts, I open dev tools and type:
```javascript
myApi.foo()
```
And I get this error on the terminal:
```javascript
Error occurred in handler for 'channel': Error: Failed to serialize arguments
    at WebContents../lib/browser/api/web-contents.js.WebContents.send (electron/js2c/browser_init.js:3763:15)
```
and this error on the developer tools:
```javascript
Uncaught Error: Uncaught Error: Error invoking remote method 'channel': Error: Failed to serialize arguments
```
Although main process is able to receive the arguments, the response `321` never reaches the `renderer` process

**Comment by nornagon** [comment] 2020-08-18 23:54
Hm, I can't reproduce the issue.

Here's an example which I tried to make as close to your description as possible: https://gist.github.com/22af908d47c6bb3b289da07486754820

I'm closing this issue since we treat our issue tracker as our backlog, and this doesn't represent a bug that needs to be fixed. But I'm happy to continue discussing here.

**Closed by nornagon** 2020-08-18 23:54 UTC

**Comment by ramaralo** [comment] 2020-08-19 14:23
Hi, @nornagon 

Thank you so much fo taking the time to analise this!

Well I've done a deeper debug and found that the problem was on the call for the log here:
```javascript
ipcMain.handle("channel", (ev, args)=> {
            log.info(111, ev, args);
            return 321;
        });
})
```

The `ev` event object has some circular references that my logger had problems with. If I log `log.info(111, args);` I don't have the problem anymore or if I use `console.log` the event object doesn't cause a problem.

So after this I can effectively send and receive the expected values.

I also notices you set `sandbox: true` on your example. Is this recommended?

Thanks!

**Comment by nornagon** [comment] 2020-08-19 22:38
@ramaralo, glad you were able to resolve the problem! It's likely not the circular references that cause the issue—circular references can be serialized over IPC just fine—but rather, the reference to `WebContents` contained in the event.

As for sandbox, yes, I recommend `sandbox: true` for most use cases.

**Comment by sanidhya711** [comment] 2021-06-05 16:24
i was also getting this same error but my problem was different. I looked up the documentation of ipcRenderer and found that we cant pass file and that was what i was trying to do

**Comment by JohnScience** [comment] 2023-01-22 04:09
I was trying to pass an instance of AppWindow which extended BrowserWindow. But I have no idea how to fix it.
