### ISSUE TITLE
Layouting issues on Electron 8.0.0-beta.3

### ISSUE THREAD

**Issue by sentialx** [electron/electron#21242] opened 2019-11-21 17:30 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0-beta.3
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 8.0.0-beta.2

### Expected Behavior

![2019-11-21-18-23-47](https://user-images.githubusercontent.com/11065386/69361317-8a17ed00-0c8c-11ea-8c27-42719d9d3137.gif)

### Actual Behavior

Also, there's a little flicker when changing the tabs on GitHub.

![2019-11-21-18-24-23](https://user-images.githubusercontent.com/11065386/69361473-db27e100-0c8c-11ea-9a28-746e7196813e.gif)

### To Reproduce
https://gist.github.com/sentialx/16bb70ff9ee870a8e8d27441ca1ab91f

**Comment by ckerr** [comment] 2019-12-18 18:56
Reproducible on Windows 10 and Linux (not tested on Mac): clicking from the "Code" tab to the "Issues" tab does not flicker in 8.0.0-beta.2, but consistently flickers in -beta.3 and -beta.4.

**Comment by ckerr** [comment] 2019-12-18 20:09
...although it no longer seems to be present in acd2eabdfd5a5b145b99f336d57ca820b13b48e2. @sentialx, please test out beta.5 when it gets released (coming soon). For the time being, I'm closing this issue because I believe it to be fixed.

My guess is this was caused by an upstream regression that broke in the pre-beta.3 Chromium roll and got fixed in the pre-beta.5 Chromium roll @ 3f889340257c34e8c7ec24888de3505d0296535d

**Closed by ckerr** 2019-12-18 20:09 UTC
Labels: 8-x-y, bug :beetle:, platform/linux, platform/windows, status/confirmed

**Comment by sentialx** [comment] 2019-12-18 20:10
@ckerr Thanks, I will check

**Comment by sentialx** [comment] 2019-12-19 19:30
@ckerr Thanks, works perfectly right now.
