### ISSUE TITLE
9.0.0 does not display local images

### ISSUE THREAD

**Issue by whyboris** [electron/electron#23757] opened 2020-05-26 00:13 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v9.0.0
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * v8.3.0

### Expected Behavior
My app shows a gallery of images from local disk. Electron 8.2.0 would show images. v9.0.0 shows blanks with error:
```
GET file:///C:/VHA/vha-videos/filmstrips/6f3acc0aeee45a7af5404e3849d8719f.jpg 
net::ERR_UNKNOWN_URL_SCHEME
```

### Actual Behavior
App does not show local images

### To Reproduce
Clone https://github.com/whyboris/Video-Hub-App
Run the app, create a "hub" (give it a folder with videos) and it will create a gallery of images.
Exit the app, update to Electron 9 (comment out 2 lines of `shell.openItem`) and run app again

### Screenshots

![image](https://user-images.githubusercontent.com/17264277/82849048-31880d80-9ec4-11ea-95fc-6639cf36e858.png)

**Comment by codebytere** [comment] 2020-05-27 04:13
@whyboris could you please provide a more minimal sample? That app is rather large which makes it harder for us to isolate the Electron-mediated issue separate from the rest of the app's workings.

**Comment by whyboris** [comment] 2020-05-27 13:53
Thank you @codebytere -- I will see if I can create a minimal sample 👍

**Comment by astoilkov** [comment] 2020-05-27 14:14
I am experiencing the same problem. I think it is related to the fact that I am running `webpack-dev-server` on `localhost` but requesting images from the filesystem via `file://` links. The same approach worked in version 8.

**Comment by lyswhut** [comment] 2020-05-27 16:41
same problem.
In v9.0.0, when browserWindow uses http protocol to load the page, the audio tag cannot load the local audio file,
When the file protocol is used to load the page, the local audio file can be loaded normally.

The last working version: v8.3.0

**Comment by codebytere** [comment] 2020-05-27 16:44
@lyswhut @astoilkov as i mentioned above - a repro will get this moving a lot faster!

**Comment by lyswhut** [comment] 2020-05-27 17:44
@codebytere This problem occurs when the audio tag uses an absolute path to load local resources when the page is loaded using the http protocol, and it works fine when using a relative path.

Platform: windows 10

repro: https://github.com/lyswhut/test-load-local-file
1. First run `npm run server`
2. Then `npm run start2`

**Comment by codebytere** [comment] 2020-05-27 19:02
Thanks! Just checked on macOS and it ran correctly so it looks like a Windows specific problem. I'll dig in more as soon as i can.

**Comment by whyboris** [comment] 2020-05-27 20:56
Just FYI, my original Issue (of not showing images) is broken on both Windows & Mac (I tested on both) 😓

**Comment by jcc** [comment] 2020-05-28 03:53
The same problem. It can't work well when I upgrade the 9.0.0 version on Mac.

**Comment by astoilkov** [comment] 2020-05-28 15:22
I can also verify it isn't Windows-specific. I am experiencing the problem on macOS 10.14.6.

**Comment by astoilkov** [comment] 2020-05-28 15:30
I successfully replicated the problem with https://github.com/lyswhut/test-load-local-file. I just had to replace the line `const filePath = dir + '/t-rex-roar.mp3'` with `const filePath = 'file://' + dir + "/t-rex-roar.mp3";`.

**Comment by lyswhut** [comment] 2020-05-28 15:57
> I successfully replicated the problem with https://github.com/lyswhut/test-load-local-file. I just had to replace the line `const filePath = dir + '/t-rex-roar.mp3'` with `const filePath = 'file://' + dir + "/t-rex-roar.mp3";`.

I have updated repro and Linux has the same problem: https://github.com/electron/electron/issues/23757#issuecomment-634829046

Switch to electron@8.3.0 to resume work

**Comment by JonasKruckenberg** [comment] 2020-06-04 15:13
As a heads up to all the people having the same issue, I ran into the same issue, but got it working again by *replicating* the file:/// scheme with the `protocol` module like so:
```javascript
protocol.registerFileProtocol('file', (request, cb) => {
    const pathname = request.url..replace('file:///','')
    cb(resolve(pathname))
});
```
This works fine in production mode and you can have the main process decide wether or not to resolve the requested file. ( Maybe something like a request guard thingy )
The problem is this breaks as soon as it is packaged, even though as of my testing the protocol handler should be bypassed when the document is loaded via file:///
But I dont know, maybe we can figure out something here

**Comment by ethan-ou** [comment] 2020-06-07 02:23
A recap for anyone else who's having this issue:

1. Make sure you've enabled `webSecurity` from your `BrowserWindow` settings as pre-update:

```javascript
win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      nodeIntegrationInWorker: true,
      webSecurity: false,
    },
  });
```

2. Register a file protocol for handling local files. The electron docs recommends you wrap this registration so that it only registers when the app is ready.

```javascript
app.whenReady().then(() => {
  protocol.registerFileProtocol('file', (request, callback) => {
    const pathname = request.url.replace('file:///', '');
    callback(pathname);
  });
});
```

3. If you're also finding that URI's with spaces are not working in your application, wrap the pathname with `decodeURI()`. This will undo any conversion of characters the browser may have added to the file.

```javascript
app.whenReady().then(() => {
  protocol.registerFileProtocol('file', (request, callback) => {
    const pathname = decodeURI(request.url.replace('file:///', ''));
    callback(pathname);
  });
});
```

**Comment by irelance** [comment] 2020-06-16 11:51
is this the same problem with Electron 9.0.4 webview webpreferences webSecurity option can't disables CSP? i try to registerFileProtocol but still not working

**Comment by venuseo** [comment] 2020-06-29 18:32
there's still no image load if url contains question mark, such as 'file:///c:/images/clock.jpg?time=16'

**Comment by JonasKruckenberg** [comment] 2020-06-29 20:28
> still does not display local image if url contains question mark, such as 'file:///c:/images/clock.jpg?time=16'

This is not because of this bug, but because the querystring is part of the http url scheme not of the file url scheme.
See [This StackOverflow answer](https://stackoverflow.com/a/13547134/13827857)
This is pretty much intended behavior as there is no server to parse the querystring with file urls anyway.

**Comment by venuseo** [comment] 2020-06-30 16:26
before upgrade to version 9, all local images works with src 'file:///c:/name.jpg' or 'file:///c:/name.jpg?time=16', last one which I used to force to refresh image. And upgrade to electron 9, all of images could be loaded.  After taking steps mentioned above,  most of images wors normal now except the one with querystring.  I think you are right about scheme reason with file protocal. But I am not sure whether current solution will be work around for now or Electron team will keep those behaviors for all version later.

**Comment by venuseo** [comment] 2020-06-30 16:37
yes, when image path contains querystring it breaks completely to stop image shown.  and report below error message, 

GET file:///C://clock.jpg?1593534885821 net::ERR_FILE_NOT_FOUND

those src path could work normal before elctron 9.

**Comment by Bug-Reaper** [comment] 2020-07-23 07:34
This workaround feels terrible, but thanks for figuring out this issue. I miss the conf file setting just working.

**Comment by Bug-Reaper** [comment] 2020-07-23 08:03
@JonasKruckenberg 
Re: your edit:

Will something like :
```
import { protocol } from "electron";

app.whenReady().then(() => {
  protocol.registerFileProtocol('file', (request, callback) => {
    const pathname = decodeURI(request.url.replace('file:///', ''));
    callback(pathname);
  });
});```
Not work in production. If so how would I alter that sample to use "media:///" as you describe,

**Comment by JonasKruckenberg** [comment] 2020-07-23 08:45
@Bug-Reaper 
This workaround solves the problem where you use a http server to serve your app in development and still want to use the file url scheme to load images / json an the like.
**However**, everything you execute in the *registerFileProtocol* callback in your example will not be executed when the app us served via the file protocol itself. (i.e. in a production environment)
This is fine if you just want to polyfill the weird electron behaviour, but as soon as you’re also putting resolving guards or custom logic in the file handler you have to use a custom protocol like `media:///`
To do this you just have to replace file with media:
```js
import { protocol } from "electron";

app.whenReady().then(() => {
  protocol.registerFileProtocol('media', (request, callback) => {
    const pathname = decodeURI(request.url.replace('media:///', ''));
// some custom resolver logic here
    callback(pathname);
  });
}); 
```

**Comment by linonetwo** [comment] 2020-08-16 09:01
I tried this solution but still get

```
GET file:///Users/linonetwo/Library/Application%20Support/TiddlyGit/pictures/815887e0-df97-11ea-b661-cb296e8e96ce.png net::ERR_FILE_NOT_FOUND
```

**Comment by linonetwo** [comment] 2020-08-16 09:15
Oh, two reasons for my `net::ERR_FILE_NOT_FOUND`:

1. I need to `const pathname = decodeURIComponent(request.url.replace('file:///', ''));`, to decode `%20` to empty space
1. I register this protocol too late, I need to register it as soon as `app.whenReady()`

**Comment by zerrol** [comment] 2020-08-17 03:29
> yes, when image path contains querystring it breaks completely to stop image shown. and report below error message,
> 
> GET file:///C://clock.jpg?1593534885821 net::ERR_FILE_NOT_FOUND
> 
> those src path could work normal before electron 9.

same problem, in electron 8.x, c://localpath/hello.jpg?param=1 work fine. But in 9，get an error. is there any way to fix it in electron 9?

**Comment by JonasKruckenberg** [comment] 2020-08-17 07:58
> > yes, when image path contains querystring it breaks completely to stop image shown. and report below error message,
> > GET file:///C://clock.jpg?1593534885821 net::ERR_FILE_NOT_FOUND
> > those src path could work normal before electron 9.
> 
> same problem, in electron 8.x, c://localpath/hello.jpg?param=1 work fine. But in 9，get an error. is there any way to fix it in electron 9?

What you, @venuseo are reporting is caused by the fact that querystrings are not a thing in file urls as per [RFC8089](https://tools.ietf.org/html/rfc8089) They exist in the http and https url standard but not in the file url standard. ( How would they translate to file system paths anyway? ) So using querystrings in file urls is pretty hacky and is only possible because the chromium url parser apparently ignores querystrings in file urls.
Our solution doesn't however, since all it does is URI decoding and removing the `file:///` part.
So your url `file:///c://localpath/hello.jpg?param=1` will be turned into `c://localpath/hello.jpg?param=1` which obviously is not a working filesystem path.
What you do to replicate the electron 8.x behaviour however, is to split the parsed path at the first question mark and return the first element in the array:
```js
import { protocol } from "electron";

app.whenReady().then(() => {
  protocol.registerFileProtocol('file', (request, callback) => {
    const pathname = decodeURI(request.url.replace('file:///', ''));
    const parts = pathname.split('?')
    callback(parts[0]);
  });
});
```
**I would discourage you from using querystrings completely though, since standards exist for a reason**
Maybe find a different solution like rerendering the img tag for example.

**Comment by jdzl** [comment] 2020-11-18 16:55
any update  ? same problem electron v11,

**Comment by ChamHerz** [comment] 2021-01-05 23:27
> A recap for anyone else who's having this issue:
> 
> 1. Make sure you've enabled `webSecurity` from your `BrowserWindow` settings as pre-update:
> 
> ```js
> win = new BrowserWindow({
>     width: 800,
>     height: 600,
>     webPreferences: {
>       nodeIntegration: true,
>       nodeIntegrationInWorker: true,
>       webSecurity: false,
>     },
>   });
> ```
> 
> 1. Register a file protocol for handling local files. The electron docs recommends you wrap this registration so that it only registers when the app is ready.
> 
> ```js
> import { protocol } from "electron";
> 
> app.whenReady().then(() => {
>   protocol.registerFileProtocol('file', (request, callback) => {
>     const pathname = request.url.replace('file:///', '');
>     callback(pathname);
>   });
> });
> ```
> 
> 1. If you're also finding that URI's with spaces are not working in your application, wrap the pathname with `decodeURI()`. This will undo any conversion of characters the browser may have added to the file.
> 
> ```js
> import { protocol } from "electron";
> 
> app.whenReady().then(() => {
>   protocol.registerFileProtocol('file', (request, callback) => {
>     const pathname = decodeURI(request.url.replace('file:///', ''));
>     callback(pathname);
>   });
> });
> ```

Esto funciono perfecto, gracias

**Comment by miki-long** [comment] 2021-01-13 02:51
> A recap for anyone else who's having this issue:
> 
> 1. Make sure you've enabled `webSecurity` from your `BrowserWindow` settings as pre-update:
> 
> ```js
> win = new BrowserWindow({
>     width: 800,
>     height: 600,
>     webPreferences: {
>       nodeIntegration: true,
>       nodeIntegrationInWorker: true,
>       webSecurity: false,
>     },
>   });
> ```
> 
> 1. Register a file protocol for handling local files. The electron docs recommends you wrap this registration so that it only registers when the app is ready.
> 
> ```js
> import { protocol } from "electron";
> 
> app.whenReady().then(() => {
>   protocol.registerFileProtocol('file', (request, callback) => {
>     const pathname = request.url.replace('file:///', '');
>     callback(pathname);
>   });
> });
> ```
> 
> 1. If you're also finding that URI's with spaces are not working in your application, wrap the pathname with `decodeURI()`. This will undo any conversion of characters the browser may have added to the file.
> 
> ```js
> import { protocol } from "electron";
> 
> app.whenReady().then(() => {
>   protocol.registerFileProtocol('file', (request, callback) => {
>     const pathname = decodeURI(request.url.replace('file:///', ''));
>     callback(pathname);
>   });
> });
> ```

it doesn't work in electron 11.1.1

**Comment by ShanZiJun** [comment] 2021-01-13 06:15
> > A recap for anyone else who's having this issue:
> > 
> > 1. Make sure you've enabled `webSecurity` from your `BrowserWindow` settings as pre-update:
> > 
> > ```js
> > win = new BrowserWindow({
> >     width: 800,
> >     height: 600,
> >     webPreferences: {
> >       nodeIntegration: true,
> >       nodeIntegrationInWorker: true,
> >       webSecurity: false,
> >     },
> >   });
> > ```
> > 
> > 
> > 
> > 1. Register a file protocol for handling local files. The electron docs recommends you wrap this registration so that it only registers when the app is ready.
> > 
> > ```js
> > import { protocol } from "electron";
> > 
> > app.whenReady().then(() => {
> >   protocol.registerFileProtocol('file', (request, callback) => {
> >     const pathname = request.url.replace('file:///', '');
> >     callback(pathname);
> >   });
> > });
> > ```
> > 
> > 
> > 
> > 1. If you're also finding that URI's with spaces are not working in your application, wrap the pathname with `decodeURI()`. This will undo any conversion of characters the browser may have added to the file.
> > 
> > ```js
> > import { protocol } from "electron";
> > 
> > app.whenReady().then(() => {
> >   protocol.registerFileProtocol('file', (request, callback) => {
> >     const pathname = decodeURI(request.url.replace('file:///', ''));
> >     callback(pathname);
> >   });
> > });
> > ```
> 
> it doesn't work in electron 11.1.1

Using protocol with a custom partition or session

```
const { session, app, protocol } = require('electron')
const path = require('path')

app.whenReady().then(() => {
  const partition = 'persist:example'
  const ses = session.fromPartition(partition)

  ses.protocol.registerFileProtocol('atom', (request, callback) => {
    const url = request.url.substr(7)
    callback({ path: path.normalize(`${__dirname}/${url}`) })
  })

  mainWindow = new BrowserWindow({ webPreferences: { partition } })
})
```

**Comment by mifi** [comment] 2021-02-06 21:04
@ethan-ou's solution works except with some special characters. For example it fails with a file with this name:

```
!@#$%^&'";<>.jpg
```

However if you replace `decodeUri` with `decodeURIComponent` it works even with fishy file names, e.g.:

```js
import { protocol } from "electron";

app.whenReady().then(() => {
  protocol.registerFileProtocol('file', (request, callback) => {
    const pathname = decodeURIComponent(request.url.replace('file:///', ''));
    callback(pathname);
  });
});
```

**Comment by linonetwo** [comment] 2021-03-21 14:28
This seems only work with absolute path, And things like `file:///images/default-icon.png` will fail in production.

**Comment by nornagon** [comment] 2021-04-01 21:48
Here's a minimal gist that shows the issue: https://gist.github.com/3e9239970afe56956d7fc93f97b4881f

Bisected to https://github.com/electron/electron/compare/v9.0.0-beta.12...v9.0.0-beta.13.

Seems https://github.com/electron/electron/pull/22919 is the cause, which is a backport of https://github.com/electron/electron/pull/22903. cc @zcbenz

**Closed** 2021-04-07 01:46 UTC
Labels: 12-x-y, 13-x-y, 9-x-y, bug :beetle:, bug/regression :leftwards_arrow_with_hook:, platform/all

**Comment by bei-yang** [comment] 2021-04-12 11:41
It is useful to add the following code to the created window.

My requirement is to upload a local file.

```
win.webContents.session.protocol.registerFileProtocol('file', (request, callback) => {
    const url = request.url.substr(8)
    callback(decodeURI(url))
})
```

**Comment by Paratron** [comment] 2021-08-22 20:09
The bug seems to persist somehow still in electron `13.1.9`. I am able to just pass a local image path to an `<img src="C:/test.jpg" />` tag and the image will show up fine. However, when I take the same URL and set it as background  of a `<div>` like this: `<div style="background-image: url('file:///C:/test.jpg')" />` it won't load and the console says: `ERR_FILE_NOT_FOUND`.

Registering the file protocol manually as mentioned above does not change anything.

**Comment by whyboris** [comment] 2021-08-23 03:46
@Paratron - I'm unsure what's not working out in your setup, but in my Electron 13 application it seems to work 🤔 
You can see my code, a `<div>` with `'background-image'` working:
https://github.com/whyboris/Video-Hub-App/blob/4f97b2a749022e610efdcd18000c5032663f2a09/src/app/components/views/thumbnail/thumbnail.component.html#L25
Perhaps this might help 🙏

**Comment by eliw00d** [comment] 2022-08-22 22:01
Is this no longer possible? If I follow [this](https://github.com/electron/electron/issues/23757#issuecomment-640146333) exactly nothing happens. But, if I use a custom protocol instead, it works. Are we no longer able to registerFileProtocol for `file`?

**Comment by miki-long** [comment] 2023-08-25 18:02
[Mickey]已经收到了，谢谢

**Comment by hxlhxl** [comment] 2024-05-13 09:00
if u use an iframe and apply the sandbox attribute without the `allow-same-origin` property, this proplem will happen.
I think it has nothing to do with the latest electron, just add `allow-same-origin` property to sandbox or remove sandbox completely.

electron version: 30.0.3

**Comment by miki-long** [comment] 2024-05-13 09:01
[Mickey]已经收到了，谢谢

**Comment by vmartins** [comment] 2024-08-12 13:58
After Electron 25 [protocol.registerFileProtocol](https://github.com/electron/electron/blob/v25.0.0/docs/api/protocol.md#protocolregisterfileprotocolscheme-handler-deprecated) is [deprecated](https://github.com/electron/electron/blob/v25.0.0/docs/breaking-changes.md#deprecated-protocolregisterinterceptbufferstringstreamfilehttpprotocol)! Use [protocol.handle](https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocolhandlescheme-handler)

```js
const { app, protocol, net } = require('electron')

protocol.registerSchemesAsPrivileged([{
    scheme: 'media',
    privileges: {
        secure: true,
        supportFetchAPI: true,
        bypassCSP: true,
        stream: true
    }
}])

app.whenReady().then(() => {
    protocol.handle('media', request => {
        const pathToMedia = new URL(request.url).pathname
        return net.fetch(`file://${pathToMedia}`)
    })

    // (...)
})
