### ISSUE TITLE
[Bug]: inconsistent ArrayBuffer limitation depending on chunk size

### ISSUE THREAD

**Issue by masa-nuc** [electron/electron#33962] opened 2022-04-28 09:44 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

from v12 to v18+

### What operating system are you using?

Windows

### Operating System Version

Windows 10, Version 20H2, OS build 19042.1645

### What arch are you using?

x64

### Last Known Working Electron version

11.5.0

### Expected Behavior

- new ArrayBuffer() returns the allocated memory without `RangeError: Array buffer allocation failed` until no free space
- when the app allocates the memory by new ArrayBuffer() continually, it can allocate the consistent size in total

### Actual Behavior

- Depending on the chunk size, the total allocated size is inconsistent
- Please refer these results:
  - https://github.com/masa-nuc/arraybuffer-test/blob/master/results/README.md

### Testcase Gist URL

https://github.com/masa-nuc/arraybuffer-test

### Additional Information

- I found this issue. Probably the root cause is the same
  - https://github.com/electron/electron/issues/31330
- However, even if `V8 pointer compression` is enabled, why total allocated ArrayBuffer size is inconsistent?
  - Are these allocated buffers safe to use?
- The result page indicates the summary. When you run the test, it can show the detail, like:
~~~
=== Electron:18.1.0, Node:16.13.2, Chrome:100.0.4896.127 ===
Try to allocate: 8.00 GiB, chunk:1.00 MiB, loop:8192

Start Memory
{
  "rss": 46825472,
  "heapTotal": 5332992,
  "heapUsed": 3287060,
  "external": 1489435,
  "arrayBuffers": 0
}

Allocate Memory
crashed at:4091/8192, RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (node:internal/buffer:959:5)
    at createUnsafeBuffer (node:internal/buffer:1062:12)
    at Function.alloc (node:buffer:362:17)
    at allocateMemory (arraybuffer-test\common\testMemoryUsage.js:21:28)
    at exports.testMemoryUsage (arraybuffer-test\common\testMemoryUsage.js:48:3)
    at App.<anonymous> (arraybuffer-test\index.js:8:3)
    at App.emit (node:events:390:28)
{
  "rss": 4354654208,
  "heapTotal": 4808704,
  "heapUsed": 2989116,
  "external": 4290110879,
  "arrayBuffers": 0
}

Memory Usage
{
  "rss": 4307828736,
  "heapTotal": -524288,
  "heapUsed": -297944,
  "external": 4288621444,
  "arrayBuffers": 0
}

Total allocated ArrayBuffer:3.99 GiB, chunk:1.00 MiB @ Electron:18.1.0, Node:16.13.2, Chrome:100.0.4896.127
~~~

**Comment by nornagon** [comment] 2022-04-28 18:45
Does this replicate in Chrome? This doesn't seem to be an Electron-specific issue. The right place to report Chrome bugs is https://crbug.com.

**Comment by masa-nuc** [comment] 2022-04-29 02:28
Hello @nornagon, thank you for your reply.

As I described in the [README.md](https://github.com/masa-nuc/arraybuffer-test), this test works on the electron main process. This does not use the BrowserWindow.

It seems that electron enabled the `pointer compression` at [v9](https://github.com/electron/electron/pull/21468).  At the electron v8, v9, v10 and v11, they can allocate the ArrayBuffer as expected. This expected means total allocated size. (e.g. 16GiB). Please see the [results here](https://github.com/masa-nuc/arraybuffer-test/blob/master/results/README.md). However, from the v12, the total allocation size was reduced. Furthermore, v12 causes application crash. Thus, this page does not have the v12 result. 

I am not sure how electron project handles Chrome, Node and V8. But from the electron v9 to v11, they can allocate the expected ArrayBuffers at main process in spite of enabling the `pointer compression`.

Does this limitation depend on the Chrome?

**Comment by masa-nuc** [comment] 2022-04-29 02:51
One more comment. When I see the [results](https://github.com/masa-nuc/arraybuffer-test/blob/master/results/README.md), the electron from v8 to v11, they use the Node v12.

If electron main process depends on the Node (or V8 in it), does this limitation come from here?

**Comment by masa-nuc** [comment] 2022-04-29 22:47
I have added a branch to test this for pure Node env and browser window. Here is the results.
https://github.com/masa-nuc/arraybuffer-test/tree/feature/browserWindow/results

- The Node env is not enabled the `pointer compression`. There is no limitation.
- The limitation is same between electron main process and browser window.

Does this mean that both(main process and browser windows) run under the Chrome at the electron?

**Comment by robinchrist** [comment] 2022-04-30 14:45
Possibly related #33994

**Comment by ckerr** [comment] 2022-05-02 16:38
Agree with @robinchrist, this and 33962 are the same issue. That is the cause for the main change in allocated size.

As for the other minor fluctuations, e.g. between 7.87 GiB and 7.75 GiB in chunk sizes of 128, I'd refer back to @nornagon's comment about testing this out in Chrome to see if Electron is actually behaving any differently than Chrome. If they're behaving the same and you feel that these fluctuations are a bug, they should be reported at crbug.com.

**Comment by ckerr** [comment] 2022-05-02 16:39
I'm closing this as a duplicate issue because I think this is the same issue as 33962. If this is in error, please open a new bug report. Thank you!

**Comment by ckerr** [comment] 2022-05-02 16:40
Duplicate of #33994,.

**Closed by ckerr** 2022-05-02 16:40 UTC
Labels: bug :beetle:
