### ISSUE TITLE
Webview is not separated from electron view

### ISSUE THREAD

**Issue by snajperek130** [electron/electron#12890] opened 2018-05-11 06:52 UTC
In electron version 1.8.6 I created webview search component to separate those two views. In ^2.0 there was a nodeintegration fix: https://electronjs.org/blog/webview-fix. After those changes webview is not separated anymore. 
Version: ^2.0.0
Operating system: win 10
Last known working Electron version: 1.8.6
Expected behavior: Separate views,
Actual behavior: When I search for a phrase webview search component is being marked as well. 
How to reproduce: https://github.com/rhysd/electron-in-page-search
Change electron version to ^2.0.0.

**Comment by MarshallOfSound** [comment] 2018-05-11 06:54
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by snajperek130** [comment] 2018-05-11 10:33
Ok the issue is updated now

**Comment by ckerr** [comment] 2018-05-14 18:50
> How to reproduce: https://github.com/rhysd/electron-in-page-search
> Change electron version to ^2.0.0.

Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by snajperek130** [comment] 2018-05-15 06:46
Hi, here it is: https://github.com/snajperek130/webview-issue

**Comment by sofianguy** [comment] 2019-08-09 00:49
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 21:05
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 21:05 UTC
Labels: 2-0-x, blocked/need-info ❌, bug/regression :leftwards_arrow_with_hook:, platform/windows
