### ISSUE TITLE
webview-tag content scrolling not constrained by parent tag size

### ISSUE THREAD

**Issue by jzimmek** [electron/electron#9147] opened 2017-04-08 07:54 UTC
* Electron version:
v1.6.6

* Operating system:
macOS Sierra
10.12.4 (16E195)

### Expected behavior

A webview-tag which size is bigger than the parent tag (max-width/height) should show scrollbars within/constrained by the of the parent tag.

### Actual behavior

A webview-tag which size is bigger than the parent-tag shows scrollbars which are not within/constrained by the parent tag but the surrounding BrowserWindow.

### How to reproduce

git clone https://github.com/jzimmek/electron-quick-start
cd electron-quick-start
npm install
npm upgrade
npm start

The relevant code is in "index.html".

Works as expected:

```
      .webviewWrapper {
        width: 500px;
        min-width: 500px;
        max-width: 500px;
        height: 100vh;
      }
      .webview {
/*        width: 1500px;
        min-width: 1500px;
        max-width: 1500px;*/
        height: 100vh;
      }
```

Broken: 

```
      .webviewWrapper {
        width: 500px;
        min-width: 500px;
        max-width: 500px;
        height: 100vh;
      }
      .webview {
        width: 1500px;
        min-width: 1500px;
        max-width: 1500px;
        height: 100vh;
      }
```

When adding a `overflow-x: scroll` directive to .webviewWrapper then horizontal scrolling stops to work at all.

**Comment by zcbenz** [comment] 2017-06-15 08:08
Webview in Chromium is essentially a browser plugin, so the normal assumptions of iframe do not work for webview, for improving the situation, I suggest reporting this to Chromium's issues list instead.

Closing since it is expected behavior.

**Closed by zcbenz** 2017-06-15 08:08 UTC

**Comment by mnicic** [comment] 2018-01-24 19:30
To hide scroolbars do the follow...
Register "dom-ready" event on a webview element
Then, implement function to insert a CSS styles, something like:
myWebView.insertCSS('html,body{ overflow: hidden !important; }');
