### ISSUE TITLE
Clipboard unable to copy GIFs

### ISSUE THREAD

**Issue by dcrousso** [electron/electron#8485] opened 2017-01-23 23:21 UTC
* Electron version: 1.3.3
* Operating system: macOS 10.12.3 Beta (16D30a)

### Expected behavior
The image is copied to the clipboard such that pasting into Messages or TextEdit will paste the actual GIF

### Actual behavior
Something is copied to the clipboard, but it appears as a space character `" "` when pasted into TextEdit.

### How to reproduce
Execute the following from inside a "click" event listener in a webview (renderer process):
```js
require("electron").clipboard.write({
	html: "<img src=\"http://i.imgur.com/zc7CRZx.gif\">",
});
```

### Other Info
I am trying to change the functionality for [GIFBar](https://github.com/dcrousso/gifbar) such that it copies the actual GIF instead of its URL to the clipboard.

**Comment by baconface** [comment] 2017-01-23 23:43
Are you trying to copy the gif as a buffer or HTML markup? The reproduction example doesn't appear to like it would paste an image because the contents is an HTML string. I believe the API you are looking for is [clipboard.readImage](https://github.com/electron/electron/blob/master/docs/api/clipboard.md#clipboardreadimagetype).

**Comment by baconface** [comment] 2017-01-23 23:46
Are you trying to copy the gif as a buffer or HTML markup? The reproduction example doesn't appear like it would paste an image because the contents is an HTML string. The applications you are pasting to might be looking for a buffer and not markup. I believe the API you are looking for is [clipboard.writeImage](https://github.com/electron/electron/blob/master/docs/api/clipboard.md#clipboardwriteimageimage-type).

**Comment by kevinsawicki** [comment] 2017-01-24 00:13
GIFs cannot be directly saved on the clipboard API yet as images, subscribe to #5078 for updates on that.

**Comment by dcrousso** [comment] 2017-01-24 00:17
@baconface would `clipboard.writeImage` work with a remote URL?  Like something from **imgur** or **Giphy**?  I'm not sure how `NativeImage` works, so any advice/pointers would be greatly appreciated.

**Comment by kevinsawicki** [comment] 2017-01-24 00:23
> would clipboard.writeImage work with a remote URL?

`NativeImage` objects can only be created from a local file or a `Buffer`. So the content would need to be local, either on disk or in memory.

**Comment by kevinsawicki** [comment] 2017-01-24 22:16
Closing this out, please track #5078 for any updates on native clipboard support for GIFs.

**Closed by kevinsawicki** 2017-01-24 22:16 UTC
Labels: more-information-needed

**Comment by zpzxgcr** [comment] 2018-04-18 15:16
@dcrousso How did you solve it?
