### ISSUE TITLE
[regression] Linux Electron after upgrade to 6.0+ always unnecessary opens BrowserWindow menu on every keyboard layout switch via Alt+Shift & Alt+Ctrl hotkeys

### ISSUE THREAD

**Issue by MurzNN** [electron/electron#22213] opened 2020-02-16 07:16 UTC
Electron version: all versions after 6.0 release

Operating system: All Linux distributions with KDE environment

**Expected behavior:**

When user change keyboard layout via Alt+Ctrl or Alt+Shift hotkeys, it should just change keyboard layout and have no effect on any focused Electron input elements.

**Actual behavior:**

At every layout changing on any input element (textarea, input, etc) - it lose focus, so users can't continue typing text, and need manually click on input element to restore focus and continue typing. This is very annoying for all non-English users!

**How to reproduce:**

1. Add any second keyboard layout in KDE settings, default hotkey for switch will be "Alt+Shift".

2. Open any app, using Electron 6.0 version, for example "Quick start" app.

3. Make focus on any input element, start typing some text.

4. Press "Alt+Shift" and try continue typing, you will can't, because element lose focus! Via "Alt" key press Electron activates app menu, and you can press "Esc" for deactivate it and continue typing, or click via mouse on element.

**How to fix:**

Downgrade Electron application to 5.x or earlier versions of Electron, and this issue will not reproduced! 

Please investigate source of this issue and fix this regression on fresh Electron versions!

P.S. Some Electron 4.x apps was have similar issue, that can be fixed via workaround with adding keyboard shortcuts to all menu elements (here is example of fix: https://github.com/vector-im/riot-web/issues/4345), but this workaround stops working on Electron 6.x+ versions.

**Comment by AlexDerbenew** [comment] 2020-02-16 07:33
Is this a regression?

**Comment by MurzNN** [comment] 2020-02-16 07:38
Yes, because all applications, using Electron 4.x-5.x, that fixes issue https://github.com/electron/electron/issues/11106 via "menu shortcuts" workaround, works well with "Alt+Shift" layout switch, but broken again after upgrade dependency to Electron 6.0. So, as result, Electron 6.0 do some new change, that broke normal behavior of Alt+Shift layout switch hotkey!

**Comment by steve-todorov** [comment] 2020-02-20 10:07
This is really annoying issue. I am having it as well as many other people and it makes apps pretty much unusable when you have multi-language environment. It's also affecting Skype, RocketChat/Rocket.Chat.Electron#1355 and other apps which rely on newer versions of Electron.

**Comment by AlexDerbenew** [comment] 2020-02-20 10:09
This also happens with all apps made by nativefier (using electron inside)

**Comment by manussos** [comment] 2020-03-31 21:23
Really annoying issue. Noticed it on Slack and VSCode (on Fedora 31 with KDE).
Trying to avoid it by using Meta+Space to switch language, but changing a 25+ year old habit is hard! (Also, that's not a solution, it's a workaround)...

**Comment by chameleon-lizard** [comment] 2020-04-22 10:46
The focus is also stolen if you are using Alt+Space shortcut to switch language. Fix, please!

**Comment by vetash** [comment] 2020-04-24 07:46
This shit is pissed me off. Why this happens again? I just cant get it. This bug covers SO MANY SOFWARE why this still present in this framework?

**Comment by jkleinsc** [comment] 2020-04-27 14:37
@vetash your comment was deleted as a violation of [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). You may consider this an official warning.

**Please do not interact with the project for 24 hours.** After that, please look through your open issues and edit them to ensure they're entirely on-topic, and we can continue the discussion here about the best way to go forward.

**Comment by Dreyk007** [comment] 2020-05-08 12:04
Very annoying. Issue actual for every electron app (VSCode, Zulip, etc...)
KDE Neon (Ubuntu 18.04)

**Comment by faerics** [comment] 2020-06-21 00:30
Also influences two projects I often use:

- [Joplin](https://github.com/laurent22/joplin) laurent22/joplin#3345
- [Typora](https://github.com/typora) by @abnerlee, did not find the issue there.

Quite annoying. From now, when I think of using new app, I check if it based on Electron or not.
And if it is, I shall not use it.

Please, fix it!

**Comment by MurzNN** [comment] 2020-07-07 22:27
Maybe commenting out this https://github.com/electron/electron/blob/dc72f74020eb64afff7f01f8a9f13db69546724a/shell/browser/ui/views/root_view.cc#L24 section can help with workaround for this issue? I can't understand how to compile Electron from source to test this, does anybody can do this test?

**Comment by mrkeuz** [comment] 2020-07-10 14:41
On Ubuntu 18.04, KDE, this menu behavior appears even when rebind shortcut to change layout to other compilation like Ctrl+Shift, Ctrl+CapsLock or probably other.

Environment:
Vscode 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-62-generic
KDE Frameworks: 5.44.0
KDE Plasma 5.12.9

**Comment by faerics** [comment] 2020-07-11 21:27
Being curious, looked at the places @MurzNN pointed out.

While reading, I found [this comment](https://github.com/electron/electron/blob/master/shell/browser/ui/views/root_view.cc#L137) somewhat strange, because afaik the menu bar should be toggled when any key is pressed with alt modifier except those which points to a submenu.

Looking for someone to help us here! :pray:

**Comment by MurzNN** [comment] 2020-07-13 18:46
@faerics thanks for pointing to right place! At first look all rules are right, but when we pressing `Shift` after holding `Alt` - code seems think that this is modifier, and catch it via this `if` https://github.com/electron/electron/blob/master/shell/browser/ui/views/root_view.cc#L122 
Maybe commenting this https://github.com/electron/electron/blob/master/shell/browser/ui/views/root_view.cc#L134 line can solve this issue?
Can anybody, who can compile Electron with test app from scratch, test this?

**Comment by mrkeuz** [comment] 2020-07-20 00:38
@MurzNN ok, I don't have skills in electron, but comment pointed only for `alt` + modifier command, but in my case it appears even I do `Ctrl` +  modifier. (Even system meta key set to `Meta` aka `Super` versus system default `Alt`). Of course maybe I missed something important and system meta key not affect it at all to bug. But what can I say for sure that `Ctrl` + modifier or other as KB layout affect this issue.

![System_meta key](https://user-images.githubusercontent.com/6247921/87889259-65e9f700-ca39-11ea-8d15-31043613d8c9.jpg)

**Comment by faerics** [comment] 2020-07-21 06:52
@sofianguy Hello, we will be glad if you find a couple of minutes to answer two questions:

* Please, provide @mrkeuz some instruction for building a small test app (just a set of links to start with should be enough I think)
* Please, we need a person from Electron team to help with resolvong this issue asap. Could you be that person? If not, could you point out some other contributor / member to communicate with? It won't consume much time as we will try to do everithing on owr own here.

Cheers... and thank you for your help.
Hae a nice day!

**Comment by DanielLitvak** [comment] 2020-08-18 12:52
@mrkeuz this still happens to me in vscode version 1.48

I would like to clarify the steps to reproduce. pressing **alt** then **shit** then releasing **alt** first will cause the issue, the issue does not occur when releasing **shift** first.

**Comment by NemchinovSergey** [comment] 2020-08-27 09:20
The issue reproduces in Zulip v5.4.2 and Postman v7.30.1

**Comment by DanielLitvak** [comment] 2020-08-27 11:26
@NemchinovSergey This probably won't work for versions 6+ of electron

**Comment by timabbott** [comment] 2020-08-27 19:12
Zulip desktop v5.4.2 is based on Electron 9.

**Comment by NemchinovSergey** [comment] 2020-08-28 05:00
Probably you are right but I fixed it with these actions and maybe it will help someone else.

**Comment by vetash** [comment] 2020-09-30 10:28
If you're don't need window menu at all you can remove it completely.
0 close slack app
1 Install python jsbeautifier over pip3, npm, npx
`sudo pip3 install jsbeautifier`
`sudo install npm`
`sudo npm install npx`
2 Go to `/usr/lib/slack`
cd `/usr/lib/slack`
3 backup original archive
`sudo cp resources/app.asar resources/app.asar.back`
4 unpack resource pack
`sudo npx asar extract resources/app.asar unpacked_asar`
5 Make backup of `main.bundle.js`, then open with kate and comment (or remove) code in function `buildMenu(changedKeys) {`
`cp unpacked_asar/dist/main.bundle.js unpacked_asar/dist/main.bundle.js.back`
`kate unpacked_asar/dist/main.bundle.js` find `buildMenu(changedKeys) {`  and remove\comment all between brackets `{}`
6 pack resource pack back
`sudo npx asar pack unpacked_asar/ resources/app.asar`
Run slack again.

**Comment by electron-triage** [comment] 2021-03-10 03:31
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Closed by electron-triage** 2021-03-10 03:31 UTC
Labels: 6-1-x, bug :beetle:, platform/linux

**Comment by MurzNN** [comment] 2021-03-10 06:07
Okay, if this is closed without any reasons :angry: , let's fill the new fresh one: https://github.com/electron/electron/issues/28088 :rocket:

**Comment by ihorch** [comment] 2021-05-24 09:13
I'm reproducing this right now with Debian Testing (slack-desktop 4.16 on Gnome 3.38).

**Comment by nohhhon** [comment] 2021-05-24 13:41
- [ ] []()https:/)darpa.mil
