### ISSUE TITLE
[Bug]: using session object prevents urls from being loaded

### ISSUE THREAD

**Issue by socratese** [electron/electron#31446] opened 2021-10-15 11:55 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.5.2

### What operating system are you using?

macOS

### Operating System Version

macOS big sur

### What arch are you using?

x64

### Last Known Working Electron version

8.5.5

### Expected Behavior

window should load the youtube page

### Actual Behavior

when adding the session object to the web preferences of creating a browser window ( settings here:

 _mainWindow = new BrowserWindow({
            width: Math.round((width / 100) * 20),
            height: Math.round((height / 100) * 40),
            title: 'Neuron AIO: Local Solver',
            frame: true,
            webPreferences: {

                enableRemoteModule: true,
                nodeIntegration: true,
                session: ses, // , <- this cuases whitescreen, but without we cannot get the callback
                webviewTag: true,
            },
        });_

when loading a site, like this

_BrowserWindow.fromId(msg.payload).loadURL(
                'https://accounts.google.com/signin/v2/identifier?continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Den%26next%3Dhttps%253A%252F%252Fwww.youtube.com%252F&hl=en&service=youtube&flowName=GlifWebSignIn&flowEntry=ServiceLogin',
                {
                    userAgent: 'Chrome',
                },_

gives error: _electron: Failed to load URL: URL HERE with error: ERR_UNKNOWN_URL_SCHEME_

removing session lets it load as normal
ses is defined as:  const ses = session.defaultSession

**Comment by codebytere** [comment] 2021-10-19 08:36
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2021-11-01 13:54
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2021-11-01 13:54 UTC
Labels: bug :beetle:, blocked/need-repro
