### ISSUE TITLE
Paste shortcut doesn't work in DevTools in 3.0.0

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#14685] opened 2018-09-19 09:23 UTC
* Output of `node_modules/.bin/electron --version`: 3.0.0
* Operating System (Platform and Version): macOS High Sierra 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.0

**Expected Behavior**
Hitting `Cmd+V` should paste the contents of the clipboard in the DevTools Console tab. 

**Actual behavior**
Nothing happens as if I haven't pressed anything.

**To Reproduce**
You can run any Electron app running 3.0.0 and the issue will be reproduced. I tried it with our own project and also a boilerplate project that contained nothing but the setup code to run the app.

**Comment by pfrazee** [comment] 2018-10-08 18:51
Reopening because the fix got reverted: https://github.com/electron/electron/pull/14876

**Comment by MarshallOfSound** [comment] 2018-10-08 22:39
The fix wasn't reverted but it hasn't been backported to the 3-0-x branch

**Comment by pfrazee** [comment] 2018-10-12 17:19
Confirmed this is fixed in 3.0.4, thanks so much

**Closed by pfrazee** 2018-10-12 17:19 UTC
Labels: app-feedback-program, bug :beetle:, platform/macOS, version/3.0.x
