### ISSUE TITLE
Refreshing app removes vibrancy

### ISSUE THREAD

**Issue by morlauth** [electron/electron#8408] opened 2017-01-13 18:48 UTC
* Electron version: 3.1.1
* Operating system: Mac 10.12.2

### Expected behavior
When I refresh the app by pressing `command+r` the page should refresh and the vibrancy effect should not be removed.

### Actual behavior
When I actually refresh the page, the vibrancy effect is removed and I only get a white background.

### How to reproduce
Here is my main code
```
function createWindow() {
	var bounds = getBounds();
	var options = {
		vibrancy: 'light',
		width: bounds.width,
		height: bounds.height,
		x: bounds.x,
		y: bounds.y,
		titleBarStyle: 'hidden'
	}

	mainWindow = new BrowserWindow(options);

	mainWindow.loadURL(viewFile);

	mainWindow.on('close', () => {
		saveBounds();
	});
	mainWindow.on('closed', () => {
		mainWindow = null;
	});

	return mainWindow;
}
```
getBounds just loads the bounds from a json file.

**Comment by kevinsawicki** [comment] 2017-01-13 18:54
Closing as duplicate of #8310, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2017-01-13 18:54 UTC
