### ISSUE TITLE
[Bug]: On macOs, the frame is set to false, and the cursor is invalid for elements within about 20px from the top

### ISSUE THREAD

**Issue by CahierX** [electron/electron#32431] opened 2022-01-12 08:46 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.01

### What operating system are you using?

macOS

### Operating System Version

macOS 11.5.2

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The frame is set to false, and the cursor is valid for elements within about 20px from the top

### Actual Behavior

On macOs, the frame is set to false, and the cursor is invalid for elements within about 20px from the top

https://user-images.githubusercontent.com/31394482/149093734-7e7a98bf-8820-45a3-830b-6a506d9c4efe.mov

### Testcase Gist URL

https://gist.github.com/0ac6a79ca57018e9a0e78981f8e77cfb

**Comment by codebytere** [comment] 2022-01-12 12:08
@CahierX can you please explain more about what you expect? you can still click the button in the repro so i'm not sure precisely what is broken.

**Comment by CahierX** [comment] 2022-01-13 02:05
> @CahierX你能解释一下你的期望吗？您仍然可以单击复制中的按钮，所以我不确定到底是什么坏了。

button and text set style cursor:pointer attributes is not work，I set pointer attributes, gesture should be showing but arrow is showing

**Comment by nornagon** [comment] 2022-01-27 00:07
duplicate of https://github.com/electron/electron/issues/5723?

**Comment by CahierX** [comment] 2022-02-09 07:08
> #5723的副本？

YES

**Comment by codebytere** [comment] 2022-02-09 09:23
Closing in agreement with above - follow https://github.com/electron/electron/issues/32431 for more updates.

**Closed by codebytere** 2022-02-09 09:23 UTC
Labels: platform/macOS, bug :beetle:, has-repro-gist, 16-x-y
