### ISSUE TITLE
print callback is not called when cancelling the print dialog

### ISSUE THREAD

**Issue by fxha** [electron/electron#17270] opened 2019-03-07 20:10 UTC
* **Electron Version:** 
  * 4.0.7
* **Operating System:** 
  * Linux x86_64 4.20.x
* **Last Known Working Electron version:**:
  * 3.0.9 (not tested afterwards)

### Expected Behavior

When calling `webContents.print` and cancelling the native print dialog the callback should be called directly.

### Actual Behavior

The callback is called after (during?) the window is closed/destroyed.

### To Reproduce

```js
const win = ...
win.webContents.print({ printBackground: true }, () => {
    log('Printing finished')
    // ...
})
```

### Screenshots

![print_callback](https://user-images.githubusercontent.com/22716132/53985690-98cd6c80-411c-11e9-9623-7dbfc0543b58.gif)

The crash in the example happened because the window is destroyed and the callback is called, which normally removes stuff from the window.

**Comment by popod** [comment] 2019-03-07 22:29
Same bug here #16085 on macOS Mojave and Windows 10 with Electron 3.0.10. This appends in Electron 4.0.7 too !

**Comment by codebytere** [comment] 2019-03-07 22:43
Closing as duplicate of https://github.com/electron/electron/issues/16085.

**Closed by codebytere** 2019-03-07 22:43 UTC
