### ISSUE TITLE
[Bug]: Some Drop down menus displaying artifacts in manu background

### ISSUE THREAD

**Issue by FIXXERAUTO** [electron/electron#33901] opened 2022-04-22 17:55 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

2.0.7

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Expected Behavior

I expected the application to launch without errors and drop-down menus to have opaque backgrounds matching the current theme of the OS.

### Actual Behavior

Launches with error:
(electronplayer:505459): Gtk-WARNING **: 11:48:17.422: Theme parsing error: gtk.css:1418:23: 'font-feature-settings' is not a valid property name
 (electronplayer:505459): Gtk-WARNING **: 11:48:17.427: Theme parsing error: gtk.css:3295:25: 'font-feature-settings' is not a valid property name
(electronplayer:503542): Gtk-WARNING **: 11:21:41.318: Theme parsing error: gtk.css:3757:23: 'font-feature-settings' is not a valid property name
/usr/share/libdrm/amdgpu.ids: No such file or directory
"electronplayer" Services" "Developer" and "Help" menus display with artifacts:
![Screenshot from 2022-04-22 11-44-13-2](https://user-images.githubusercontent.com/38957889/164767726-9b68f5f6-97ff-4622-b0ec-d8cd7732a37f.png)
"Settings" and "Edit" menus are unaffected

### Additional Information

Machine is AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx

**Comment by codebytere** [comment] 2022-05-12 11:05
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed** 2022-05-22 07:57 UTC
Labels: bug :beetle:, blocked/need-repro
