### ISSUE TITLE
[Bug]: The "openAtLogin" function does not work when the App is built as appx.

### ISSUE THREAD

**Issue by 0Quake** [electron/electron#43333] opened 2024-08-15 13:26 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.4.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11 23H2 (build 22631.4307)

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

I used this code:

    app.setLoginItemSettings({
      openAtLogin: true,
    })

The app should start with OS.

アプリがOS起動時に自動起動するはずである。

### Actual Behavior

The "openAtLogin" function does not work when the App is built as appx.

appx形式でビルドした場合、"openAtLogin"機能（スタートアップ、自動起動機能）が動作しない。

### Additional Information

This function has worked when I built the App as any other format such as ".exe".

I had used electron-forge and electron-builder to build the app. However, the problem has happened in both cases.

Today, many apps using electron have built as appx and published in Microsoft Store.The "openAtLogin" function is important for many apps.Therefore, this problem may affect many apps seriously.

(I just start to learn English....)
___

".exe"など、他の形式でビルドした場合には、この機能は正常に動作しました。
electron-forgeやelectron-builder等、複数のツールでビルドしましたが、やはりappxでビルドした場合のみ問題が発生しました。

現在、さまざまなelectron製アプリがMicrosoft Storeで公開されており、"openAtLogin"機能もまた、さまざまな場面で利用されています。この問題は多くのアプリに影響する

**Comment by codebytere** [comment] 2024-08-15 13:29
Duplicate of https://github.com/electron/electron/issues/42016

**Closed by codebytere** 2024-08-15 13:29 UTC
Labels: platform/windows, bug :beetle:, 31-x-y
