### ISSUE TITLE
The power monitoring callback function will be triggered twice, in electron 8.4.0

### ISSUE THREAD

**Issue by renhaoweixiao** [electron/electron#24793] opened 2020-07-30 08:04 UTC
`const { app, powerMonitor } = require('electron')

app.on('ready', () => {
  powerMonitor.on('suspend', () => {
    console.log('The system is going to sleep')
  })
})`

The system is going to sleep
The system is going to sleep

**Comment by sevilen** [comment] 2020-07-31 06:21
the same #24803

**Comment by codebytere** [comment] 2020-08-04 04:59
Closing as duplicate of https://github.com/electron/electron/issues/24803

**Closed by codebytere** 2020-08-04 04:59 UTC
