### ISSUE TITLE
Has electron worked for anyone using raspberry pi 3 b and the raspbian stretch

### ISSUE THREAD

**Issue by wscotgrey** [electron/electron#10468] opened 2017-09-07 22:55 UTC
I have a new install of Raspbian, not Jessie but Stretch, and using node 8.4.0 and npm 5.3.0. 

Tried the `electron-quick-start` to no avail.

first had to force the `npm install` with `--save-sev --save-exact`. This version installed locally with 1.6.13, so I don't know if it conflicted with the install I did (also forced with `npm install -g electron --unsafe-perm=true --allow-root` which installed latest (1.7.6). No install would work without forcing.

So electron installed, but when I `npm start`, I get 

`
> electron-quick-start@1.0.0 start /home/pi/electron-quick-start
> electron . 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: 'electron .'
npm ERR! Exit status 1
npm ERR!

npm ERR! Failed at the electron-quick-start@1.0.0 start script` ...

You all get it. 

So I've found a lot of fixes for Jessie, but none for Stretch, and the electron readme even says they take about a month to catch up to all of the updating, so is that what I'm waiting for? Is there a stable release somewhere I'm missing?

I've been back and forth on this, plus another app that uses electron.js (MagicMirror^2) and I'm getting discouraged, so if there are fellow travelers who've solved this particular puzzle, and can explain what I'm missing, I'd appreciate it. 

Thanks for your time

**Comment by kounelios13** [comment] 2017-09-10 22:51
have you tried fixing npm permissions?

**Comment by wscotgrey** [comment] 2017-09-15 16:46
Okay, found my problem, sorry for the delayed reply, btw (work), but still don't know how to fix it. 

I can launch electron from the desktop shell, but not from outside of the desktop. I am not sure what causes this, but I got it working in the shell, but am stymied on the PI when I ctrl+alt+F3 out and use the command line. 
Hope someone has answers for that. Thanks again for all of you wizards' help!

**Comment by mohankumargupta** [comment] 2017-09-19 08:31
What worked for me is installing electron in a local directory, then doing 

npm init
npm install electron --unsafe-perm=true --allow-root --save-dev --save-exact

Create a script called "start" with value "electron ."
Then
npm start

This works with the example for main.js and index.html given in the Quick Start
https://electron.atom.io/docs/tutorial/quick-start/

**Comment by wscotgrey** [comment] 2017-09-23 05:48
Hey There, 

Thanks for replying.

In answer to your solutions,

I have tried both.

I am installing electron to use with the Magic Mirror 2  <https://github.com/MichMich/MagicMirror/>, The install for that includes the start shell, and it doesn’t work from command line, but will work from terminal shell on the desktop.

When the install didn’t work, i tinkered with it for hours, including the <npm install electron —unsafe-perm=true —allow-root —save-dev —save-exact>

I do thank you for trying to help me figure this out, I know it isn’t a big deal, as I have accomplished my task, but I would like to be able to modify the launch to not include a desktop if there is a power outage or something as the RPI will automatically reboot. 

I’ll keep trying for an answer, and hopefully be able to get back to you sooner.

Scot

**Comment by hsoj95** [comment] 2017-10-26 04:03
I seem to be suffering from a similar issue. On my Pi3, I can launch Electron version 1.6.15, but it seems anything above that doesn't work. I used the prebuilt binaries, as the app I'm making is supposed to be an all-in-one idea.  I have no clue if actually installing Electron 1.6.15 actually works on the Pi, but I can confirm the prebuilt binary will run. I do hope a work around is found soon, as I'd like to be able to run my app in a more updated environment.

**Comment by KellyLSB** [comment] 2017-10-27 07:05
Biggest port required to make this possible is the kernel and back ported
device drivers; with arm this hits hardest with GPU drivers, architecture
extensions and impedance/voltage/clock adjustments.

This is more notable with distribution releases that are not using, and
contributing to mainline builds from kernel.org (git://
github.com/torvalds/linux.git). Furthermore it is not uncommon for debian
deviants to maintain their own libraries in their releases, despite being
the same distribution.

It's generally wise to stick to kernels and sources that are part of the
debian continuous integration pipeline via http://ci.debian.net or
https://anonscm.debian.org/cgit/

**Comment by hsoj95** [comment] 2017-10-28 23:52
@KellyLSB Ah! Yeah, that does make sense. It makes more sense because the only two superiorly popular distros for the Pi are Raspbian, a Debian remix made specifically for the Pi, and Ubuntu MATE, which though a good distro it already puts a strain on the Pi. Hopefully, with the newest release of Debian 9 and Raspbian 'Stretch', a port of the newer versions of Electron will be made for the Pi soon.

**Comment by KellyLSB** [comment] 2017-10-29 20:01
Proper mainstream device/kernel support for Debian's releases would go a
long way.

I would advocate against making raspbian a separate distribution; rather
just a device supporting repo that has dependency on upstream.

On Oct 28, 2017 4:52 PM, "J K" <notifications@github.com> wrote:

@KellyLSB <https://github.com/kellylsb> Ah! Yeah, that does make sense. It
makes more sense because the only two superiorly popular distros for the Pi
are Raspbian, a Debian remix made specifically for the Pi, and Ubuntu MATE,
which though a good distro it already puts a strain on the Pi. Hopefully,
with the newest release of Debian 9 and Raspbian 'Stretch', a port of the
newer versions of Electron will be made for the Pi soon.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/electron/electron/issues/10468#issuecomment-340227512>,
or mute the thread

**Comment by bgsuello** [comment] 2017-11-04 12:20
i got it working by building the app on another machine and disable hardware acceleration.

OS | Node| Electron
---|--------|----------
Raspbian Stretch | 8.9.0 | 1.7.9

**Comment by hsoj95** [comment] 2017-11-04 23:32
@KellyLSB Raspbian technically is Debian I think, or at least it shares the same relation Ubuntu does. So if a version is made to work for Debian, it should work for the Pi to.

@bgsuello That's fantastic news! Thanks for sharing that!

**Comment by wscotgrey** [comment] 2017-11-05 05:03
As I said in OP, electron is working on the newest raspian, but I can’t launch from command line, it has to have the Desktop GUI then it’ll launch just fine, whether directly from Terminal, or from script. I was trying to get it to launch without a desktop.

**Comment by MarshallOfSound** [comment] 2017-11-05 05:19
> I was trying to get it to launch without a desktop.

This isn't possible (and doesn't make much sense).  If you want to run Electron without any form of GUI then it's basically just node.js.  If you want to run Electron headlessly you'll need something like xvfb running 👍

**Comment by hsoj95** [comment] 2017-11-05 09:17
Glad to know at least that it is working on the newest releases!

**Comment by codebytere** [comment] 2017-12-02 14:36
Seems like some resolution has been reached here, so i'm going to go ahead and close this.

**Closed by codebytere** 2017-12-02 14:36 UTC
Labels: triaged/helpme, version/1.6.x

**Comment by schrockwell** [comment] 2018-02-09 19:55
@bgsuello Oh my god, downgrading from electron v1.8.2 to v1.7.9 made all the difference! Thank you!

**Comment by darshan94** [comment] 2018-03-06 21:30
@schrockwell Hi, how you downgraded them ?

**Comment by bgsuello** [comment] 2018-03-08 11:20
try `npm install electron@1.7.9`

**Comment by borismus** [comment] 2018-03-15 22:19
Umm... so @1.8.2 and @1.8.3 are both broken on RPi 3. Downgrading to @1.7.9 worked for me too. Please reopen and fix.

**Comment by jkleinsc** [comment] 2018-03-15 22:30
@borismus what OS are you using on the RPi 3 and is it 32-bit or 64-bit?

**Comment by borismus** [comment] 2018-03-15 22:37
AFAICT all official RPi3 OS are 32-bit: <https://raspberrypi.stackexchange.com/questions/69562/is-current-raspbian-pi-3-b-32-or-64-bits-os>.

Mine seems to be too: `Linux raspberrypi 4.9.35-v7+ #1014 SMP armv7l`

**Comment by jkleinsc** [comment] 2018-03-16 19:06
@borismus I was able to verify the issue on both a RPi 3 and a RPi 2.
I tested 1.8.2, 1.8.3 and the newly released 1.8.4 and the issue is present in all three; however 2.0.0-beta.4 works correctly.
 I am going to open a new issue to specifically track the issue in 1.8.x

**Comment by borismus** [comment] 2018-03-16 19:22
Great. I’ll stick to 1.7.9 for now but happy that it reproduces.

**Comment by jkleinsc** [comment] 2018-03-16 19:28
1.8.x issue here: https://github.com/electron/electron/issues/12329

**Comment by readonemohamed** [comment] 2018-03-17 20:00
OS: Stretch
Node: 9.8.0
electron: 1.6.11

Works well so far.

**Comment by brubbel** [comment] 2018-04-02 13:47
Same issue here.
RPI3B @ Raspbian GNU/Linux 9 (stretch)
Node v8.11.1
electron 1.8.4
Headless (xvfb), window.webContents emits a crash event at window.loadURL(...)

**Comment by adamplabarge** [comment] 2019-02-14 21:59
If it is any help - I got electron to build correctly using
Node.js 12.0.0, Chromium 72.0.3626.52, and Electron 5.0.0-beta.2.
On Rasbian Stretch after updating everything via apt updates.

Previous versions of electron i tried were 1.7.9, 4.0.4, and they were having issues with the libc versions.  

Might not be the exact answer to this question but might help others in getting electron to run the quick start.

**Comment by rdzidziguri** [comment] 2019-05-19 07:04
@adamplabarge any advice on how to run app build using electron-package on rasbian-strech-lite from SSH and let me clarify i only have xserver-xorg xserver-xorg-video-fbdev xinit installed think nothing else is needed to run the app. I have no node or electron on raspberry side and i think it should not be required after packing app so any advice would be helpful.

**Comment by adamplabarge** [comment] 2019-05-19 19:16
@rdzidziguri unfortunately no. i found developing and building on the Raspberry itself to be very slow and would often blow up.  I decided to just develop/build on a desktop.

**Comment by rdzidziguri** [comment] 2019-06-04 18:47
@adamplabarge sorry for the late response, but what I mean is that i build and develop on my windows box and would like to run on raspbian-stretch-lite but only have xorg and xinit packages.

**Comment by adamplabarge** [comment] 2019-06-05 03:11
@rdzidziguri - I was able to get this built and running - though I'm developing from Ubuntu.
https://github.com/adamplabarge/lastbrewtime

**Comment by rdzidziguri** [comment] 2019-06-11 23:32
@adamplabarge Sounds great but were u able to run it on raspbian-lite with only xserver xinit installed? I would be very thankful if you could share your experience and steps to follow.

**Comment by iot-dev01** [comment] 2019-06-14 12:03
> 
> 
> @rdzidziguri - I was able to get this built and running - though I'm developing from Ubuntu.
> https://github.com/adamplabarge/lastbrewtime
Thanks a lot @adamplabarge we add following line to our package.json and get it running
`"linux": {
      "target": {
        "target": "deb",
        "arch": "armv7l"
      },
      "category": "Development"
    },
    "deb": {
      "fpm": [
        "--architecture",
        "armhf"
      ]
}`

> 
> 
> @adamplabarge Sounds great but were u able to run it on raspbian-lite with only xserver xinit installed? I would be very thankful if you could share your experience and steps to follow.

I try to make the app run on a raspbian lite in kioskmode.
Installing lightdm and it works perfectly as expected.
Unfortunately xserver xinit **only** not work on my environment for now.
