### ISSUE TITLE
nativeImage.createFromBuffer crashes on Windows on ARM

### ISSUE THREAD

**Issue by jkleinsc** [electron/electron#25069] opened 2020-08-20 21:32 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

This issue was discovered while working on #25018

* **Electron Version:**
  * 11.0.0-nightly.20200723
* **Operating System:**
  * Windows on ARM
* **Last Known Working Electron version:**
  * 11.0.0-nightly.20200721.

### Expected Behavior

Calling `nativeImage.createFromBuffer` with an invalid image or a bitmap image should not crash Electron on Windows on ARM

### Actual Behavior

Calling `nativeImage.createFromBuffer` with an invalid image or a bitmap image crashes Electron on Windows on ARM

### To Reproduce

The following example of calling  nativeImage.createFromBuffer with a bitmap will crash:
```
const imageA = nativeImage.createFromPath(path.join(__dirname, 'fixtures', 'assets', 'logo.png'));
const imageC = nativeImage.createFromBuffer(imageA.toBitmap(), { ...imageA.getSize(), scaleFactor: 2.0 });
```

The following example will also crash when the file passed into `nativeImage.createFromPath` isn't an image:
```
const image = nativeImage.createFromPath('/Users/somebody/readme.txt')
```

webContents.startDrag will also cause this crash if the icon passed in isn't an image:
```
const w = new BrowserWindow({ show: false });
w.webContents.startDrag({ file: __filename, icon: __filename });
```
### Additional Information
Running test cases through windbg reveals the following stack traces:
####  nativeImage.createFromBuffer(imageA.toBitmap()....)
<img width="950" alt="callstack2" src="https://user-images.githubusercontent.com/609052/90827170-bccd3f80-e309-11ea-8b48-652c4d54ed5e.png">

####  webContents.startDrag
![callstack3](https://user-images.githubusercontent.com/609052/90827581-775d4200-e30a-11ea-836a-bb8df594b5c4.png)

#### Assessment
In both cases a longjmp is failing. Apparently Windows thinks it is invalid for the process, as far as I can understand from this: https://docs.microsoft.com/en-us/windows/win32/devnotes/guardchecklongjumptarget
Here's where setjmp gets called: https://source.chromium.org/chromium/chromium/src/+/master:ui/gfx/codec/jpeg_codec.cc;l=179
and here's where longjmp gets called: https://source.chromium.org/chromium/chromium/src/+/master:ui/gfx/codec/jpeg_codec.cc;l=43

This issue was introduced in the chromium roll: #24575

In that chromium roll libjpeg_turbo was updated: https://chromium.googlesource.com/chromium/deps/libjpeg_turbo/+log/0241a1304fd183ee24fbdfe6891f18fdedea38f9..9d4f8005bc6c888e66b00fd00188531ee9bd3344?n=10000&pretty=fuller (edited) 
That update includes an update to TurboJPEG 2.0.5
which includes this change: https://github.com/libjpeg-turbo/libjpeg-turbo/commit/ae87a958613b69628b92088b313ded0d4f59a716 which may be the root of the issue.

**Comment by nornagon** [comment] 2020-08-20 21:39
Probably a good idea to file this against libjpeg-turbo: https://github.com/libjpeg-turbo/libjpeg-turbo/issues/new/choose

**Comment by jkleinsc** [comment] 2020-08-20 22:53
@nornagon I think it may actually be an implementation issue in https://source.chromium.org/chromium/chromium/src/+/master:ui/gfx/codec/jpeg_codec.cc.  Eg see https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/example.txt#L311

**Comment by kaadam** [comment] 2020-09-01 09:01
Hi, @jkleinsc  unfortunately I couldn't reproduce this issue on my WoA device Asus NovaGo (winver: Windows 10 Pro, OS Build 19041.450, MSVC 16.7.2). I have checked with Electron v11-0.0-nightly.20200825/20200723 ( Node v12.18.3). It could be I missed something. 
Could you share your gn args and your Windows environment where these tests are running on?

Many thanks,
Adam

**Comment by jkleinsc** [comment] 2020-09-01 16:07
@kadam our CI Windows environment is a Lenovo Yoga C630 running Windows 10 Home 10.0.19041 Build 19041/10.0.19041.423.  As far as GN args are concerned, they are here: 
https://github.com/electron/electron/blob/master/build/args/testing.gn - for our testing builds
and 
https://github.com/electron/electron/blob/master/build/args/release.gn for our release builds.

We also have a Microsoft Surface Pro X in CI which is running on Windows 10 Enterprise v 10.0.18362.752.  I can verify if it also fails there.

**Comment by jkleinsc** [comment] 2020-09-01 19:35
@kaadam also tested on the Surface Pro X running on Windows 10 Enterprise v 10.0.18362.752 and I can reproduce the issue there as well.

**Comment by kaadam** [comment] 2020-09-08 16:11
@jkleinsc 
I managed to reproduce this issue, and it seems it is not related to jpeg_codec implementation. Maybe the problem is how llvm is handling longjmp call for arm64-win. I got the this error:
"Unhandled exception at 0x00007FFC1B783838 (ntdll.dll) in electron.exe: RangeChecks instrumentation code detected an out of range array access." Despite we compile it with /guard:cf,nochecks [1].
I could reproduce it with this small example [2]; compiled/linked it as Chromium does. I got the same crash.

This CL [3]  causes the issue, so earlier in the build config '/guard:cf/nolongjmp' was set, which allows the users to link in object
files that call setjmp that weren't compiled with '/guard:cf', but it leaved the longjmp unprotected (there was no check). 

I would say we should use this ldflag option only for arm64 as a workaround to avoid this crash until it is fixed in llvm. 

[1] https://source.chromium.org/chromium/chromium/src/+/master:build/config/win/BUILD.gn;l=100;bpv=1;bpt=0
[2]
```
#include <setjmp.h>
#include <stdio.h>
jmp_buf buf;
void g() {
  printf("before longjmp\n");
  fflush(stdout);
  longjmp(buf, 1);
}
void f() {
  if (setjmp(buf)) {
    printf("setjmp returned non-zero\n");
    return;
  }
  g();
}
int main() {
  f();
  printf("hello world\n");
}
```
[3] https://chromium-review.googlesource.com/c/chromium/src/+/2298284/13/build/config/win/BUILD.gn

**Comment by richard-townsend-arm** [comment] 2020-09-08 17:22
LLVM/LLD issue opened: https://bugs.llvm.org/show_bug.cgi?id=47463

**Comment by jkleinsc** [comment] 2020-09-08 18:34
@kaadam and @richard-townsend-arm thanks for your help on this.  I'll put together a PR to use the proper ldflag option only for arm64.

**Comment by jkleinsc** [comment] 2020-09-08 18:38
Also, just to close the loop on this, https://chromium-review.googlesource.com/c/chromium/src/+/2298284/13/build/config/win/BUILD.gn was part of the chromium roll here: #24575 where we first saw this issue.

**Comment by nornagon** [comment] 2020-09-08 18:39
@jkleinsc @richard-townsend-arm perhaps shoot a quick email to wfh@chromium.org with a link to the llvm bug?

**Comment by richard-townsend-arm** [comment] 2020-09-09 12:59
Done ✔️ I don't imagine there'll be a problem passing /guard:cf,nolongjmp temporarily until the toolchain's fixed.

**Comment by richard-townsend-arm** [comment] 2020-09-09 17:49
@jkleinsc : if you implement the workaround, could you reference this bug? https://bugs.chromium.org/p/chromium/issues/detail?id=112654 

Otherwise I'll get started on it tomorrow.

**Comment by jkleinsc** [comment] 2020-09-09 17:53
@richard-townsend-arm can you verify that bug link?  When I click on it, the issue listed (Issue 112654: Crash on clicking App launcher thrice) doesn't appear to relate to this issue.

**Comment by jkleinsc** [comment] 2020-09-09 17:55
Ah think I found it: https://crbug.com/1126549

**Comment by richard-townsend-arm** [comment] 2020-09-09 17:56
Ooops, apologies (edited with the fix).

**Comment by jkleinsc** [comment] 2020-09-09 18:00
Pull request to use `/guard:cf,nolongjmp` is here: #25396.

**Closed** 2020-09-10 18:42 UTC
Labels: 11-x-y, WOA, bug/crash :boom:
