### ISSUE TITLE
[Bug]: query string missed when form submit get in browserview

### ISSUE THREAD

**Issue by lazyManLearn** [electron/electron#29915] opened 2021-06-28 02:36 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 7 

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0

### Expected Behavior

when i use browserview load a page which has a form(method="get" target="_blank"),  I intercept the new-window event of webcontents and the parameter url does not have querystring

### Actual Behavior

new-window event parameter url with querystring

**Comment by Prinzhorn** [comment] 2021-06-28 07:33
Very similar to https://github.com/electron/electron/issues/28688

**Comment by nornagon** [comment] 2021-06-28 17:59
@lazyManLearn please try `nativeWindowOpen: true` and report whether that fixes the issue!

**Comment by lazyManLearn** [comment] 2021-06-29 01:19
> Very similar to #28688

I've seen this issue and tried the methods in it, but I can't solve it

**Comment by lazyManLearn** [comment] 2021-06-29 01:21
> @lazyManLearn please try `nativeWindowOpen: true` and report whether that fixes the issue!

I tried, but it didn't work out

**Comment by nornagon** [comment] 2021-06-30 00:05
Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by lazyManLearn** [comment] 2021-06-30 02:20
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance! Your help is appreciated.

https://gist.github.com/lazyManLearn/a62e465871a67616344b49dbd63c447b

**Comment by nornagon** [comment] 2021-06-30 22:04
Great, I'm able to confirm the issue with that repro. I've further simplified it; it seems the problem isn't specific to browserview. Here's an example that reproduces the issue just using `BrowserWindow`: https://gist.github.com/0b6a2648da537c0e0df4789277cce4b0

Additionally, the above Fiddle is automatable, in that it exits with 0 if the query string is present, or 1 if it isn't. Using that I was able to auto-bisect the issue to the range https://github.com/electron/electron/compare/v9.0.0-beta.5...v9.0.0-beta.6. Within that range, #22198 seems like the most likely culprit.

Another bisection on the 10.x nightlies revealed https://github.com/electron/electron/compare/v10.0.0-nightly.20200303...v10.0.0-nightly.20200304 as a breaking range which includes #22064, a similar chromium roll.

**Comment by lzdyes** [comment] 2021-07-21 06:57
same bug in 13.1.2，i used webview

**Comment by clavin** [comment] 2021-07-27 23:32
I think I've figured this out! This has to do with how Chrome makes requests for form data submissions, notably that the [url it uses originally](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/loader/form_submission.cc;drc=2f763d9d815a46a9ec05cea5f9b2b392536a326d;l=285) is just the raw `action` URL, whereas later in the navigation it [actually sets the URL's query field to the form data](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/loader/form_submission.cc;drc=2f763d9d815a46a9ec05cea5f9b2b392536a326d;l=359).

A quick patch on the first link to set the form data in the original request that makes its way to our open handler fixed this issue for me, properly showing the form data in the URL.

I'll work on figuring out a PR for this.

**Comment by clavin** [comment] 2021-07-28 00:04
Okay, a little more digging and I found it: https://chromium-review.googlesource.com/c/chromium/src/+/1922699

That change to chromium, dated 6 Feb 2020 and shows up in the chromium roll listed above, made some changes to the form submission code, notably refactoring it and changing the behavior to cause this bug.

Looking at the code, I'm not exactly sure about some of the changes, like why the query string is being set only on navigation. I'll make a PR that moves that code earlier in the lifecycle so we get a request with the right URL.

**Comment by lzdyes** [comment] 2021-08-09 10:47
any updates?

**Comment by clavin** [comment] 2021-09-01 21:23
The [change I made in upstream](https://chromium-review.googlesource.com/c/chromium/src/+/3062655) got merged into Chromium's main branch. I suspect that this fix should show up in Electron 15 or 16, not exactly sure which.

**Comment by clavin** [comment] 2021-09-21 23:55
This is fixed in the latest nightly versions of Electron 16 👍. Closing this.

**Closed by clavin** 2021-09-21 23:55 UTC
Labels: bug :beetle:, bug/regression :leftwards_arrow_with_hook:, status/confirmed, 9-x-y, 10-x-y, has-repro-gist, 11-x-y, 12-x-y, 13-x-y, 14-x-y
