### ISSUE TITLE
[Bug]: Crash in debug mode when backgroundColor contains alpha value

### ISSUE THREAD

**Issue by arenevier** [electron/electron#41395] opened 2024-02-21 17:28 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28

### What operating system are you using?

Other Linux

### Operating System Version

linux

### What arch are you using?

x64

### Expected Behavior

no crash

### Actual Behavior

When electron is built in debug mode. And when opening a browserWindow with a backgroundColor set to` rgba(255, 255, 255, 0.9)'` (or really any alpha value that is not 0 or 1), an assertion will fail, and electron will crash. It looks like [RenderWidgetHostViewBase::SetBackgroundColor](https://github.com/MonarchEngineering/chromium/blob/master/content/browser/renderer_host/render_widget_host_view_base.cc#L316) only supports fully opaque or fully transparent background color.

[Documentation](https://www.electronjs.org/docs/latest/api/browser-window)  mentions that setting an alpha is supported if transparent is set to true, but the crash happens whether or not the property is set. 

```
[122897:0221/092742.783814:FATAL:render_widget_host_view_base.cc(322)] Check failed: SkColorGetA(color) == SK_AlphaOPAQU09:27:42 [53/494]
color) == SK_AlphaTRANSPARENT.                                                                                                           
#0 0x55a553ed5442 base::debug::CollectStackTrace()                                                                                       
#1 0x55a553ebd333 base::debug::StackTrace::StackTrace()                                                                                  
#2 0x55a553dd17b4 logging::LogMessage::Flush()
#3 0x55a553dd168d logging::LogMessage::~LogMessage()
#4 0x55a553db9563 logging::(anonymous namespace)::DCheckLogMessage::~DCheckLogMessage()
#5 0x55a553db8fc3 logging::CheckError::~CheckError()
#6 0x55a552e8ca94 content::RenderWidgetHostViewBase::SetBackgroundColor()
#7 0x55a54e6f191d electron::api::WebContents::HandleNewRenderFrame() 
#8 0x55a54e6f4b3e electron::api::WebContents::RenderFrameCreated()
#9 0x55a55304416c content::WebContentsImpl::WebContentsObserverList::NotifyObservers<>()
#10 0x55a553060a18 content::WebContentsImpl::RenderFrameCreated()
#11 0x55a552dba3f3 content::RenderFrameHostImpl::RenderFrameCreated()
#12 0x55a552e54a3d content::RenderViewHostImpl::CreateRenderView()
#13 0x55a55306a72d content::WebContentsImpl::CreateRenderViewForRenderManager()
#14 0x55a552e24734 content::RenderFrameHostManager::InitRenderView() 
#15 0x55a552e1c9a5 content::RenderFrameHostManager::ReinitializeMainRenderFrame()
#16 0x55a552e19f96 content::RenderFrameHostManager::GetFrameHostForNavigation()
#17 0x55a552e18cab content::RenderFrameHostManager::DidCreateNavigationRequest()
#18 0x55a552c9352e content::FrameTreeNode::TakeNavigationRequest()
#19 0x55a552d931e0 content::Navigator::Navigate()
#20 0x55a552d2e723 content::NavigationControllerImpl::NavigateWithoutEntry()
#21 0x55a552d2d62e content::NavigationControllerImpl::LoadURLWithParams()
#22 0x55a54e6fac4d electron::api::WebContents::LoadURL()
#23 0x55a54e62cf96 base::RepeatingCallback<>::Run()
#24 0x55a54e71909a gin_helper::Invoker<>::DispatchToCallback()
#25 0x55a54e718cb2 gin_helper::Dispatcher<>::DispatchToCallback()
#26 0x55a551cf5707 Builtins_CallApiCallbackGeneric
Task trace:
#0 0x55a54e8329c2 electron::NodeBindings::WakeupMainThread()

```

**Comment by codebytere** [comment] 2024-02-21 20:15
This is known and not something we're considering a bug as it doesn't currently affect end-user behavior. I can look into it,  bit but I'm closing it out as not a bug for that reason.

It's true that it's supported because it is - you're hitting a DCHECK which wouldn't happen in an app using a released version of Electron.

Background colors in Electron generally are a bit of a mess because they're a big mess upstream too unfortunately - it's probably something upstream needs to streamline first.

**Closed by codebytere** 2024-02-21 20:15 UTC
Labels: bug :beetle:

**Comment by codebytere** [comment] 2024-07-08 17:58
hey @arenevier i ended up fixing this - see https://github.com/electron/electron/pull/42824.

turns out i was wrong about some upstream behavior and it seems like it's changed in our favor in the last ~6 months
