### ISSUE TITLE
[Bug]: Eletron 18 renderer process turn to a weired white screen after staying idle for a while

### ISSUE THREAD

**Issue by wendychengc** [electron/electron#33816] opened 2022-04-18 06:27 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10, intel core i7-7700 

### What arch are you using?

ia32

### Expected Behavior

renderer process turn to a weired white screen after staying idle for a while

### Actual Behavior

staying well all the time. 

### Additional Information

My electron app sometimes turns in to a totally white screen, after staying idle for a while.

but when i hover on the page, the mouse can change to hover style on buttons.

when i try to click these button area, and then check my log file, i found my click function is currently triggered, all logic code seem to runs well, only the screen is white.

And when i clicked the application entrance (My app is a sub module of another bigger app, started with independent process), which actually calls my Browser window show() function in main process, the page turns back rendering currently.

Then I try to minimize it, then restore it, it breaks again.

Usually occur when i leave my application staying idle for a while(for example. turns windows into lock screen, and goes for a meeting).

I've catched all exceptions in main process using:

`process.on('unhandledRejection', (error) => {
  logger.error(error?.toString());
});

process.on('uncaughtException', (error) => {
  logger.error(error?.toString());
});`

lately I updated my version to 18.0.3，but it still happen sometime. It's not only happen to me, but alse happen to my users with Windows system ( mac seems to be all right）

This bug is really annoying, but i have no idea what I do wrong. Looks like the chromium render engine has lost its context after something happen, But why?

Is there anyway i can know about this weired white screen appearance?
Is there anything i can do to prevent this from happening? 

I'm totally confused up. Please help me, Thanks very much.

**Comment by mlaurencin** [comment] 2022-04-18 19:43
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2022-05-11 12:17
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-05-11 12:17 UTC
Labels: bug :beetle:, blocked/need-repro
