### ISSUE TITLE
webContents.print success callback is not triggered.

### ISSUE THREAD

**Issue by alevani** [electron/electron#25801] opened 2020-10-07 12:51 UTC
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
`v10.1.3`
* **Operating System:**
`Windows 10`
* **Last Known Working Electron version:**
`2.0.4`

### Expected Behavior
When a file is printed, the callback of `webContents.print` should be trigger and `success` should be `true`

### Actual Behavior
The callback is not triggered (though it is when the print fails). + If tested with a FileToPDF printer, it prints an empty PDF.

### To Reproduce
```javascript
printWindow.webContents.print(
 {
 deviceName: printerName,
 silent: true
 },
  (ok, failureReason) => {
    if (ok) {
      success();
     } else {
      console.log(failureReason);
       failure();
    }
  }
 );
```

This is tested with a custom FileToPDF printer, and it seems that electron might be blocked in the printing process as the PDF output is empty? Could be related to #14705

**Comment by alevani** [comment] 2020-10-07 14:44
This is tested with a custom FileToPDF printer, and it seems that electron might be blocked in the printing process as the PDF output is empty? Could be related to https://github.com/electron/electron/issues/14705

**Comment by alevani** [comment] 2020-10-13 07:22
Hi @zcbenz, will this be fix quickly or have you decided to look into it for a 11-x-y version? I would like to know as if this will be fix in the following days/weeks, I will wait for it, otherwise I will just downgrade my electron for a while. Thanks!

**Comment by codebytere** [comment] 2020-10-14 04:03
@alevani i ran the above code and saw the callback successfully printed to console - i am unable to reproduce. Does this: https://gist.github.com/0c1c8affb9262ae83bde4d08d3401f0c work for you?

**Comment by alevani** [comment] 2020-10-14 15:48
@codebytere 
I took the liberty to change [this function](https://gist.github.com/codebytere/0c1c8affb9262ae83bde4d08d3401f0c#file-main-js-L52)  to 
```javascript
ipcMain.on('print', (event, options) => {
  mainWindow.webContents.print(
    options, (success, errorType) => {
      if (!success) console.log(errorType)
      else {
        console.log("success")
      }
    }
  )
})
```
to see if I would get any "success" printed in the console after a print, and I do not. It correctly asks what printer I want to print on, I select my FileToPDF printer and click print. A pop up asking me what the name of the file should be pops up, and then when I click `save` the file is created but is empty, and `console.log("success")` is not called.

Now if I downgrade to my "Last Known Working Electron version", 2.0.4, the callback is called and the saved file contains the expected content.

**Comment by codebytere** [comment] 2020-10-14 16:37
Oh you're saving to PDF! not just hitting "print". Ok, that's different - the success callback is only called for _printing_ and not other actions taken from the menu.

**Comment by alevani** [comment] 2020-10-16 06:59
@codebytere Oh! I will try right away on a printer then, but everything should be fine. I however think that it would make great sense for the success callback to be triggered even if it's saving to a PDF as it is a FileToPDF **printer**, IMO. Also the file is empty when printing and saving to PDF in `10.1.3` so that's related to the callback not being triggered (I imagine). Many thanks for your time.

**Comment by codebytere** [comment] 2021-03-04 20:26
This is fixed in latest stable versions of Electron.

**Closed by codebytere** 2021-03-04 20:26 UTC
Labels: 10-x-y, 11-x-y, blocked/need-repro, bug :beetle:, component/printing

**Comment by TariqDev43** [comment] 2024-09-05 14:26
No I am in electron version 32.0.1 and still success callback function is not being called.
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    const pdfWindow = new BrowserWindow({ show: true });
    pdfWindow.loadURL(url);

    pdfWindow.webContents.on("did-finish-load", async () => {
      console.log("PDF window finished loading");
      console.log("Attempting to print");
      await wait(3000);
      console.log("await end");

      await pdfWindow.webContents.print(
        {
          silent: true,
          printBackground: false,
        },
        (success, errorType) => {
          if (success) {
            console.log("Printing Success");
            pdfWindow.close();
          }
          if (errorType) {
            console.log(errorType);
            throw new Error(errorType);
          }
        }
      );
      console.log("print-end");
      console.log("SetTimeout End");
    });
  });
};.

**Comment by droutin** [comment] 2025-06-10 07:29
Same issue on version 36.3.2

**Comment by codebytere** [comment] 2025-06-10 07:59
@droutin  see https://github.com/electron/electron/pull/47400
