### ISSUE TITLE
[Bug]: GamePad API doesn't work when App is not on focus

### ISSUE THREAD

**Issue by msartiano** [electron/electron#32998] opened 2022-02-20 12:34 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

GamePad API continues to respond to events when the App is not on top of all the other apps, unless chosen not to

### Actual Behavior

GamePad API events are not triggering

### Additional Information

Apologies if this is not a bug. I am building an automation App that responds to GamePad, and I would like it to work when the App is not on top of the others. The App reads inputs well when on focus, but doesn't detect events when not. Could you please suggest how to approach this situation?

Thanks in advance for the support.

**Comment by codebytere** [comment] 2022-02-21 13:24
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by polygonnedpotato** [comment] 2022-03-05 22:18
The Chromium framework does not handle gamepad events when a window or view is not in focus. This is similar to playing PC games with gamepad support. If the game is not in focus, and you are trying to interact with it with the gamepad, it will do nothing. Bringing it back into focus allows interaction again.

Your best bet would be to use a different framework that can handle gamepad events even without window focus.

I hope this helped.
-- brendan.

**Closed** 2022-04-12 17:33 UTC
Labels: bug :beetle:, blocked/need-repro
