### ISSUE TITLE
[Bug]: requestLEScan No information is available

### ISSUE THREAD

**Issue by yirandidi** [electron/electron#35395] opened 2022-08-21 17:20 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3

### What operating system are you using?

Windows

### Operating System Version

1909

### What arch are you using?

x64

### Expected Behavior

requestLEScan requestLEScan 

### Actual Behavior

No callback can be obtained

**Comment by yirandidi** [comment] 2022-08-21 17:22
![image](https://user-images.githubusercontent.com/57606461/185803222-d36a35e4-577c-4367-baf3-6184bf2e5498.png)
This is what it looks like in the browser, and you get the list

**Comment by VerteDinde** [comment] 2022-08-22 02:29
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by codebytere** [comment] 2022-08-22 13:24
It looks like you're trying to access [WebBluetooth functionality](https://googlechrome.github.io/samples/web-bluetooth/scan.html)? Are you trying to run it from a file? if yes, this is known as broken: CRBUG:1137504

**Comment by yirandidi** [comment] 2022-08-22 14:50
> 看起来您正在尝试访问[WebBluetooth 功能](https://googlechrome.github.io/samples/web-bluetooth/scan.html)？您是否尝试从文件中运行它？如果是，这被称为损坏：[CRBUG:1137504](https://bugs.chromium.org/p/chromium/issues/detail?id=1137504)



> 

Yes

**Comment by codebytere** [comment] 2022-08-24 13:12
@yirandidi as @VerteDinde said we need a sample of the failing code to proceed. Please attach one or we will unfortunately need to close this issue.

**Closed** 2022-09-06 14:16 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, 20-x-y
