### ISSUE TITLE
Multiple Monitor issue

### ISSUE THREAD

**Issue by ThexXTURBOXx** [electron/electron#17933] opened 2019-04-23 22:46 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.1
* **Operating System:**
  * Windows 10 (1803)

### Expected Behavior
Saving the window state on multiple monitors should work as intended. When I close an electron based app on my right monitor in maximized mode, it should reopen it exactly like this next time.

### Actual Behavior
The above behavior can only be achieved when tricking the system. For more information about this "trick", see the link at the bottom of this issue. There are a few more explanations, too.

### To Reproduce
1. Open an Electron-based app
2. Drag it to another monitor, which is not your main monitor
3. Maximize the window on that monitor
4. Close the app
5. Reopen the app
6. The app will appear maximized on the main monitor, not the non-main monitor

### To Trick the system
1. Open an Electron-based app
2. Drag it to another monitor, which is not your main monitor
3. Here comes the "trick": Don't maximize the window, let it unmaximized on the monitor
4. Close the app
5. Reopen the app
6. The app will appear on the non-main monitor in its last state
7. Maximize the window on that screen now
8. Close the app
9. Reopen the app
10. Now, it should have started maximized on the non-main monitor, which should be the expected behavior, even without that trick

### Additional Information
See the issue, I was talking about here: https://github.com/ShadyThGod/altus/issues/20

**Comment by RosieCode95** [comment] 2019-05-05 08:05
i dont think this is an issue with electron but in the project you linked you use `electron-window-state` so this is prob the source as electron does not save windows positions

**Comment by harryi3t** [comment] 2019-08-05 12:22
I was able to reproduce the issue.
The problem seems to be that when you maximize an electron app, the top boundary moves slightly out of the top boundary of the monitor.
So the `y` coordinate becomes negative. My buggy implementation was that I was converting the negative coordinate into `null`.
I was able to fix the issue by fixing the logic which sanitizes the coordinates.

Not sure what might be causing it for the `Atlus` app. Will check the implementation of the `electron-window-state`.

So not an Electron issue I guess. But the window moving out of the boundary (and hence the coordinate becoming negative) seems like a bug.

**Comment by electron-triage** [comment] 2020-02-19 20:43
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:26
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:26 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/windows
