### ISSUE TITLE
Unity Badge Count implementation 

### ISSUE THREAD

**Issue by JMarteF** [electron/electron#16001] opened 2018-12-10 20:08 UTC
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version): Ubuntu 18.04
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): Electron 3.0.10

**Expected Behavior**
The BADGE COUNT will be present on the app icon if there are any unread messages.

**Actual behavior**
Nothing happens

**To Reproduce**
I'm using an app called Nativefier to create a native app using electron.  According to the electron docs this can be implemented by first creating a .desktop file of the app. However, when  try to implemented it gives me a "TypeError" when trying to launch the application.

1)Clone the repository from [here](https://github.com/jiahaog/nativefier)
2)run 
```
nativefier --counter -e 3.0.10 web.whatsapp.com 
```

3)Create a .desktop file and include the linux implementation on main.js  inside the "nativefied" app. More specifically,  in **~/whatsapp-web-linux-x64/resources/app/lib/

4) Open the app and see that error pop up.

```
**Screenshots**
![image](https://user-images.githubusercontent.com/42979355/49758546-426f9f80-fc8d-11e8-982b-33e13404b534.png)


![image](https://user-images.githubusercontent.com/42979355/49758474-089e9900-fc8d-11e8-848c-43c55dea0b7a.png)

**Additional Information**
I think it might have to somehow "find" the .desktop file within the code but I don't have any idea of how it would look like.

**Comment by JMarteF** [comment] 2018-12-10 20:08
![image](https://user-images.githubusercontent.com/42979355/49758608-7054e400-fc8d-11e8-90aa-0a865d95b2df.png)

**Comment by JMarteF** [comment] 2018-12-10 20:09
![image](https://user-images.githubusercontent.com/42979355/49758643-8c588580-fc8d-11e8-9766-c714a78c2ada.png)

**Comment by jnugh** [comment] 2018-12-12 07:37
It's hard to tell where line 77 is. But are you sure `count` is an integer? 
```
electron._app.setBadgeCount(parseInt(count));
```
If this is not the problem, could you please highlight line 77?

**Comment by jayarjo** [comment] 2019-05-18 14:30
@JMarteF so I think I figured it out for. When they say in the docs that:

> On Linux, it only works for Unity launcher. 

They literally mean just that. Unity was dropped by Ubuntu, so neither 18.04, nor even 17.04 don't include it. So I guess it is safe to say that `setBadgeCount` is not supported on current versions of Ubuntu.

Documentation should reflect that, 'cause even contributors get somewhat confused @jnugh.

**Comment by jnugh** [comment] 2019-05-18 15:56
You are probably right. It seems like chromium is not able to add badge counters to dash-to-dock entries on the default gnome desktop.
I had a quick look and it seems like dash to dock supports the unity dbus schema and should be able to handle those just fine. Maybe chrome dropped support when dash to dock was not able to handle those signals or chromium is checking the environment for unity before emitting ¯\_(ツ)_/¯. 
I will try to find out whats going on here. However I don't know the chromium project well...

**Comment by jayarjo** [comment] 2019-05-18 18:38
@jnugh I filed another issue here, which is somewhat related: https://github.com/electron/electron/issues/18349. I also followed it to Chromium and came to conclusion that Chromium itself gets confused on whether Unity is running and available or not. My wild guess would be that while Ubuntu removed Unity it still left a bunch of stuff behind (like .desktop file for example), so maybe they have simply have some stubs laying around or fake flags just to keep stuff working until they finalize migration.

**Comment by jnugh** [comment] 2019-05-19 10:55
Electron simulates the existence of unity (see my comment on the linked issue). Desktop files are pretty much standard across all environments as is dbus.
Counter and progress bar are special dbus signals originally defined by Canonical (`com.canonical.Unity.LauncherEntry`). As long as dbus is available this signal can be dispatched without  checking for special desktop environments as long as the environment either implements the feature correctly or not at all.

**Comment by jayarjo** [comment] 2019-05-19 14:05
@jnugh so practically it is possible to show both - a badge and progress in Ubuntu without unity?

One question that I've not received an answer to is whether these (badge, progress, etc) work for majority of other users - does it work for you for example (I mean maybe it's something wrong with my Ubuntu + Electron setup)? In other words does Electron require any patch to make it work or it already works (eventhough the workaround is confusing)?

**Comment by jnugh** [comment] 2019-05-19 14:25
No, it should be possible as long as the desktop environment supports it (e.g. by handling `com.canonical.Unity.LauncherEntry` correctly which is not limited to unity even though the string contains Unity).

The dock that is currently used by Ubuntu by default (`dash-to-dock`) should support this and therefor support badge and progress since https://github.com/micheleg/dash-to-dock/pull/590 has been merged. As far as I can tell chromium is not emitting a dbus signal at all right now which means there is nothing to be handled by the dock.

I'm currently cloning / building electron and the necessary chromium parts, which takes quite a few hours on my connection and machine, to have a look at why this does not work anymore. Hope to have some sort of solution afterwards :smile: 

It does not work for me and as there is no dbus signal emitted I'm pretty sure it does not work for anyone on Ubuntu running the default desktop environment. My example does not work right now on Ubuntu 19.04 and most likely does not work since 17.10.

**Comment by jnugh** [comment] 2019-05-20 20:20
Turns out, chromium uses libunity which still works as long as the setup is correct. However when debugging chromium I noticed that the desktop file name was not matching the existing desktop file. With this approach I was able to create two files where one invokes the other which is then able to set a badge count for the first one:
![image](https://user-images.githubusercontent.com/143341/58048847-d05c8a00-7b4b-11e9-9e13-ddedfec0f42d.png)
However I consider this a bug in the packager I used or the way electron is actually invoked. Would you be able to share your desktop file (and it's name) as well as whatever `console.log(process.env['CHROME_DESKTOP']);` prints during startup. What tool do you use to package your app (if any)?

**Comment by jayarjo** [comment] 2019-05-21 06:07
I use `electron-builder`. It is able to generate AppImages that can self-integrate into the system (so no additional daemons or utilities) required. However if naming of the desktop file is a concern I should say that it prefixes AppImages with `appimagekit-`. For example here is my `.desktop` file:

```
Name=iName
Comment=iName Desktop App
Exec="/path_to_appimage/iName-1.0.38_x86_64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-iname
StartupWMClass=iName
X-AppImage-Version=1.0.38
MimeType=x-scheme-handler/iii;x-scheme-handler/inameapp;
Categories=AudioVideo;
X-AppImage-BuildId=1LRzn46zX34FlPOY9uerRMGQUdU
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_iName7ia6dD/AppRun
TryExec=/path_to_appimage/iName-1.0.38_x86_64.AppImage
```
The name of this `.desktop` file is `appimagekit-iname.desktop`, while `CHROME_DESKTOP` shows: `iName.desktop`. I should say that I tried to rename `.desktop` file, but the AppImage that `electron-builder` generates contains a script that runs when it launches and recreates `appimagekit-iname.desktop` file if  itdoesn't already exist (and maybe associates itself with it, rather than the one from CHROME_DESKTOP var).

**Comment by jayarjo** [comment] 2019-05-21 06:59
Ok, it _has_ something to do with file naming. I've extracted `AppImage` and disabled the part in the desktop integration script where it was recreating a `.desktop` file. Then packed it back and renamed the desktop file to match the value of `CHROME_DESKTOP`. When I launched AppImage then it logged `Desktop file is missing.` - so it is still looking for the desktop file that it is associated with. However when I launched it from a desktop file it launched and the badge showed up on the icon!

Something is wrong with the desktop integration script that `electron-builder` bundles into the AppImage. Now I'm not sure at the moment where does it come from, I was not able to locate it nor in electro-builder nor AppImage related repos.

**Comment by jayarjo** [comment] 2019-05-21 07:27
Where does `CHROME_DESKTOP` value come from actually? I've now approached it from the other end and forcefully set `process.env['CHROME_DESKTOP'] = 'appimagekit-iname.desktop'` from inside the main file and it also works.

**Comment by jayarjo** [comment] 2019-05-21 07:35
I mean maybe it's not a packagers fault after all, but rather somethings wrong with how `CHROME_DESKTOP` value is initialized?

This is how AppImage registers a .desktop file in the system:

```
THIS="$0"
DESKTOP_FILE="$APPDIR/iname.desktop"
VENDORPREFIX=appimagekit
DESTINATION_DIR_DESKTOP="$HOME/.local/share/applications"
# $APPIMAGE is path to the executable and is passed from outside

desktop-file-install --rebuild-mime-info-cache \
  --vendor=$VENDORPREFIX --set-key=Exec --set-value="\"${APPIMAGE}\" %U" \
  --set-key=X-AppImage-Comment --set-value="Generated by ${THIS}" \
  --set-icon="appimagekit-iname" --set-key=TryExec --set-value=${APPIMAGE// /\\s} "$DESKTOP_FILE" \
  --dir "$DESTINATION_DIR_DESKTOP" \
  --mode=755
```

Notice `$VENDORPREFIX` thing, that's where prefix is added. Also for some reason `$DESKTOP_FILE` is generated all lowercase. But it shouldn't matter, 'cause registration process itself is a valid one according to the `desktop-file-install` manual.

**Comment by jnugh** [comment] 2019-05-21 07:35
Awesome that it works after hacking around. Even though my initial dev setup does not work correctly anymore I would consider this a bug in electron-builder as it works when changing the package contents accordingly. You should probably open an issue there and check if there is a reason for the current naming. 

It was not really intended to work in a dev environment (because you usually don't have a desktop file there) so I will not debug my setup any further. 

There is probably no way to fix this on the electron side because it's not possible to find out the desktop file name that was used to launch the application as far as I know...

**Comment by jayarjo** [comment] 2019-05-21 07:44
@jnugh do you know where `CHROME_DESKTOP` value comes from?

**Comment by jayarjo** [comment] 2019-05-21 07:59
Ok it looks like I've fixed it without hacking. I tracked `CHROME_DESKTOP` initialization logic to this line: https://github.com/electron/electron/blob/master/lib/browser/init.ts#L144.

```
// Set application's desktop name.
if (packageJson.desktopName != null) {
  app.setDesktopName(packageJson.desktopName)
} else {
  app.setDesktopName(`${app.name}.desktop`)
}
```
And simply set `desktopName` in the `package.json` to `appimagekit-iname`, and it works! :O

Now that I know what to look for I went to documentation page and found this paragraph, under the description for [win.setProgressBar](winsetprogressbarprogress):

> On Linux platform, only supports Unity desktop environment, you need to specify the *.desktop file name to desktopName field in package.json. By default, it will assume app.getName().desktop.

I think the same thing should be mentioned under `setBadgeCount` method. It's obviously not obvious at all :/

**Comment by jnugh** [comment] 2019-05-21 08:21
I didn't know this as well :smile: (actually didn't know this when I first implemented the badge count feature). So once this is documented we can close this issue, right? :confetti_ball:

**Comment by jayarjo** [comment] 2019-05-21 08:23
I guess so. And the other one probably as well.

**Comment by electron-triage** [comment] 2021-03-09 19:15
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 19:15 UTC

**Comment by Skywalker13** [comment] 2024-08-22 07:58
> Where does `CHROME_DESKTOP` value come from actually? I've now approached it from the other end and forcefully set `process.env['CHROME_DESKTOP'] = 'appimagekit-iname.desktop'` from inside the main file and it also works.

It doesn't work anymore since appimagekit use id like `appimagekit_aa5419784332bc7418958e442d87de48.desktop` and I don't know how to retrieve this id.

**Comment by Skywalker13** [comment] 2024-08-22 08:38
> It doesn't work anymore since appimagekit uses id like `appimagekit_aa5419784332bc7418958e442d87de48.desktop` and I don't know how to retrieve this id.

OK, it's simple. It's the MD5 of the AppImage location.

For example:
```
/home/toto/Applications/toto-1.0.0.AppImage
```

Just compute the MD5 of `file:///home/toto/Applications/toto-1.0.0.AppImage`.
```
dc1cc0d616a1f680d281eb10bd3c8b98
```

The desktop file is named: `appimagekit_dc1cc0d616a1f680d281eb10bd3c8b98.desktop`

See https://github.com/probonopd/go-appimage/blob/bf3088f94b548b7a68549479ca31b6ab6d14e519/src/appimaged/appimage.go#L48
