### ISSUE TITLE
[Bug]: second instance send "--allow-file-access-from-files" to master instance on Windows

### ISSUE THREAD

**Issue by fxha** [electron/electron#32933] opened 2022-02-16 18:20 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

15.3.7, 17.0.1

### What operating system are you using?

Windows

### Operating System Version

Win10 x64

### What arch are you using?

x64

### Last Known Working Electron version

???

### Expected Behavior

```sh
$myApp.exe --path C:\tmp\foo.txt --foo=1 --show 1
```

The command above is converted into `argv` (below) in the second instance and is received without any changes in the master instance when `requestSingleInstanceLock` is used.

```
argv = [
  'myApp.exe',
  '--path',
  'C:\tmp\foo.txt',
  '--foo=1',
  '--show',
  '1'
]
```

No `--allow-file-access-from-files` is send to master instance because it was not included in original `argv` and no sorting is performed.

Optionally if `--allow-file-access-from-files` is needed by Chromium, it should be appended or inserted after the application path but before the first user argument.

### Actual Behavior

The `argv` is correctly built in the second instance, but Electron inserts a `--allow-file-access-from-files` flag at an unexpected position that may destroy argument parsing when sending to master. In addition the `argv` received by the master seem to be "sorted".

The `argv` received by the master instance via `app.on('second-instance')`:

```
argv = [
  'myApp.exe',
  '--path',
  '--foo=1',
  '--show',
  '--allow-file-access-from-files',
  'C:\tmp\foo.txt',
  '1'
]
```

Happy argument parsing 😄 

### Additional Information

Build a dummy Electron app with following code:

```js
app.on('second-instance', (event, argv, workingDirectory) => {
  console.log(argv)
})

const gotSingleInstanceLock = app.requestSingleInstanceLock()
if (!gotSingleInstanceLock) {
  process.stdout.write('Other instance detected: bye\n')
  app.exit()
  return
}
```

**Comment by nornagon** [comment] 2022-02-16 21:29
Duplicate of #20322

**Closed by nornagon** 2022-02-16 21:29 UTC
Labels: bug :beetle:, duplicate

**Comment by fxha** [comment] 2022-02-17 15:53
Hey @nornagon, could you please update the documentation that other users know that `argv` isn't actually the original command line arguments that are passed to the application but a pre-parsed one? According to the linked issue, a user should never use the provided information because they may invalid.

Since when is `additionalData` available as `requestSingleInstanceLock` parameter? v15 doesn't seem to have this option available according TS definitions.
