### ISSUE TITLE
Allow registering multiple accelerators in MenuItem

### ISSUE THREAD

**Issue by sentialx** [electron/electron#19431] opened 2019-07-24 16:06 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Currently, the `accelerator` property in `MenuItem` accepts only one string, therefore it's not possible to register multiple shortucts.

### Proposed Solution
The `accelerator` property in `MenuItem` class should accept an array of strings.

### Alternatives Considered
Adding multiple basically the same `MenuItem`s.

```javascript
[
        {
          accelerator: 'CmdOrCtrl+L',
          label: 'Toggle Overlay',
          click() {
            appWindow.webContents.send('toggle-overlay');
          },
        },
        {
          accelerator: 'Ctrl+Space',
          label: 'Toggle Overlay',
          click() {
            appWindow.webContents.send('toggle-overlay');
          },
        },
]
```

**Comment by pushkin-** [comment] 2019-07-24 18:01
dupe of [this](https://github.com/electron/electron/issues/5256)

**Comment by codebytere** [comment] 2019-07-24 18:41
Closing as duplicate of https://github.com/electron/electron/issues/5256.

**Closed by codebytere** 2019-07-24 18:41 UTC
