### ISSUE TITLE
Set use_vaapi=true build flag

### ISSUE THREAD

**Issue by TRPB** [electron/electron#18942] opened 2019-06-22 16:00 UTC
According to https://aur.archlinux.org/packages/chromium-vaapi 

> I have learned today that we don't need to patch Chromium sources to get VA-API support, an interesting alternative is to simply compile Chromium with use_vaapi=true flag and libva as a dependency, and then VA-API stays disabled by default, but users can enable it on case-by-case basis using --ignore-gpu-blacklist.

I'd like to see Electron built with VA-API if possible. An it looks like Chromium now supports it. 

I haven't been able to test this as running `gn gen out/Release --args="import(\"//electron/build/args/release.gn\") use_vaapi=true"`

gives me the following error:

```
ERROR at //printing/BUILD.gn:151:22: Script returned non-zero exit code.
      cups_version = exec_script("cups_config_helper.py",
                     ^----------
Current dir: /home/media/electron-gn/src/out/Release/
Command: python /home/media/electron-gn/src/printing/cups_config_helper.py --api-version /home/media/electron-gn/src/build/linux/debian_sid_amd64-sysroot
Returned 1.
stderr:

  File "/home/media/electron-gn/src/printing/cups_config_helper.py", line 70
    print 'cups-config not found: %s' % cups_config
                                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('cups-config not found: %s' % cups_config)?

See //BUILD.gn:142:7: which caused the file to be included.
      "//printing:printing_unittests",
```

and I have no idea where to start on fixing so cannot tell whether or not this will work, but it looks like it should as long as electron uses the version of Chromium that looks for use_vaapi.

**Comment by MarshallOfSound** [comment] 2019-06-23 22:00
@TRPB That error looks like you're using the wrong version of python.  It needs to be using Python 2.7 for all of Chromiums build scripts

**Comment by TRPB** [comment] 2019-06-24 11:37
thanks, yes, I managed to build it. Unfortunately, although it did something, I couldn't get any videos to play with hardware acceleration enabled.

**Comment by tcd156** [comment] 2019-07-17 18:31
I have had the same issue - I attempted to add the patches from:
https://chromium-review.googlesource.com/c/chromium/src/+/532294 
and
https://github.com/saiarcot895/chromium-ubuntu-build/blob/master/debian/patches/enable_vaapi_on_linux_2.diff

with no luck. 

I take the dist.zip and use it in electron-builder, and build an AppImage. I haven't been able to see hardware acceleration work yet. The ubuntu build from above has worked for me.

Our app would benefit from having hardware acceleration on linux. Is there anything else I can do here? I know a lot of people have pushed the issue, but even maintaining our own custom build is viable at this point, so long as I can get it working.

**Comment by TRPB** [comment] 2019-07-18 17:04
@tcd156  I changed my app to use mpv.js instead. https://github.com/Kagami/mpv.js Not only does it work  with HW Acceleration, you can play codecs like x265 which aren't supported by chromium. Perhaps not ideal, it may be a good alternative.

**Comment by tcd156** [comment] 2019-07-18 17:10
Huh, I'll have to try that out! Thanks @TRPB

**Comment by tcd156** [comment] 2019-07-18 17:50
Actually, that probably won't work for us unfortunately.

**Comment by tcd156** [comment] 2019-07-21 21:16
Using a patch from the Ubuntu build I mentioned above (https://github.com/saiarcot895/chromium-ubuntu-build) with some slight modifications gave me a working build with hardware acceleration.

If I just use that patch and the matching vdpau-va-driver, hw acceleration clearly works, but it requires vaapi 1.3 through libva. Instead, I was able to remove the check for the libva version and see MojoVideoDecoder working, but it seems like it may potentially be a little flaky. If I can figure out how to actually get it pointing to a newer version of libva, I'll put the check back and rebuild.

**Comment by tcd156** [comment] 2019-07-22 15:08
I was running on ubuntu 18.04 LTS and the libva version available is too low - using 19.04 worked so long as I had the vdpau-va-driver from saiarcot895. So I have a hardware acelerated build of Electron curently working.

**Comment by maximbaz** [comment] 2019-07-31 23:08
Hey guys, thanks for creating this issue and investigating!

@TRPB you said you managed to compile with `use_vaapi=true`, but HW acceleration is not working even though you provide `--ignore-gpu-blacklist` flag, is that correct? I am wondering if you are able somehow to open `chrome://media-internals` and `chrome://gpu` pages in Electron, the former will show you the currently used decoder while the latter will show you if there are any errors and if your flag was indeed recognized.

@tcd156 you don't really need that patch at all if you are able to provide `--ignore-gpu-blacklist` flag, so perhaps you could simplify your solution, and even propose a PR? 😉 😉

**Comment by tcd156** [comment] 2019-08-05 20:09
@maximbaz I'm not understanding - are you saying just by compiling with `use_vaapi=true` and then using the `--ignore-gpu-blacklist` flag I can get hardware acceleration to work? I just built using the flags available, and have been passing the gpu flag to my executables this whole time, and no dice.

The only way I've been able to get it to work is with that patch, by adding it to the patches directory that are run against Chromium. Are you suggesting I add that as a PR, or something simpler?

**Comment by maximbaz** [comment] 2019-08-05 20:22
> @maximbaz I'm not understanding - are you saying just by compiling with `use_vaapi=true` and then using the `--ignore-gpu-blacklist` flag I can get hardware acceleration to work? 

That is exactly right, that's for example what I'm doing with `chromium-vaapi` package for Arch Linux as mentioned in the first comment of this thread.

As far as I understand, the patch that you referred earlier is simply enabling `--enable-accelerated-video` flag, it makes it behave just like `--ignore-gpu-blacklist`.

Would you be able to try again, build Electron using `use_vaapi=true`, launch it with `--ignore-gpu-blacklist` and open `chrome://gpu` and `chrome://media-internals` while playing a Youtube video? It should say "GpuVideoDecoder" or "MojoVideoDecoder", depending on Chromium version that is used by Electron.

**Comment by tcd156** [comment] 2019-08-05 20:30
I have been doing that for quite some time and have been unable to get it to work without the patch. Now, that said, with the patch I had to upgrade the Ubuntu version to get the proper libva versions, so maybe I have to do the same here as well. I will test again and get back to you.

**Comment by tcd156** [comment] 2019-08-13 17:19
@maximbaz you were correct, that did work.

However (and this is probably just Ubuntu related at the moment):
- I did still have to use the patched version of `vdpau-va-driver` from `ppa:saiarcot895/chromium-beta`
- I had to be running at least Ubuntu 19.04 in order to have the latest `libva` packages (using 6.0.0 latest)
- I also had to install `vainfo` (likely for libva-drm2 package)

**Comment by maximbaz** [comment] 2019-08-13 17:32
Great! Thanks for verifying this!  

In this case I suggest we propose a PR that permanently adds "use_vaapi=true" to Electron, and then it will be up to user to install necessary dependencies and actually enable hardware decoding. Worth noting, by only adding "use_vaapi=true" the default behavior of Electron will not change for all users, unless they intentionally enable vaapi. 

would you submit a PR please? 😉

**Comment by tcd156** [comment] 2019-08-13 21:08
https://github.com/electron/electron/pull/19736 🤷‍♂

**Comment by sebakerckhof** [comment] 2019-08-22 12:35
@tcd156 Do you know what's the minimum libva version required?

**Comment by maximbaz** [comment] 2019-08-22 12:47
There's no minimal version, the only requirement is that libva version used during compilation must match exactly libva version that you will have installed on your system when you will be running electron.

**Comment by tcd156** [comment] 2019-08-22 12:52
Hmm.. I built it on 18.04 and had trouble running it on 18.04 without upgrading to 18.10 to get libva 2.2.0 or higher. Maybe I missed something, but I will have to give it another try.

**Comment by maximbaz** [comment] 2019-08-22 13:25
I haven't encountered this but maybe some really old versions are not compatible, so you might be right!

**Comment by tcd156** [comment] 2019-08-22 19:09
This is the error I see:
```
[4194:0822/150819.734391:ERROR:vaapi_wrapper.cc(346)] The system version 1.1 should be greater than or equal to 1.3
```

**Comment by sebakerckhof** [comment] 2019-09-05 08:01
Ok, I was able to make a build with the `use_vaapi=true` flag on a system with libva 2.4.0.
I now try to test it on the same system.

First thing I notice is that, if I have the `ignore-gpu-blacklist` runtime flag, it will say the video is hardware accelerated in the chrome gpu page, both for my build as for the regular build (!). So even without using `use_vaapi=true` it will say it's doing hardware acceleration on the gpu page. So that page seems rather useless. 

Looking into media internals, I can see a difference. In the regular/non-patched build, it will immediately go to FFMpegDecoder for H264 video. In my patched build it first tries to use the MojoVideoDecoder, but then fails (VDA ERROR 4) and falls back on FFMpegDecoder.

Does someone know what this VDA Error 4 means? I'm on a Debian 10 intel system (no dedicated card).

**Comment by tcd156** [comment] 2019-09-05 12:15
@sebakerckhof I had to still apply the patch from that chromium-ubuntu-build repo in order to get past the VDA error 4.

I'm using Nvidia, however, so I had to use the patched vdpau-va-driver from that repo as well.

However, for me at least, it shows MojoVideoDecoder and everything seems to work fine, but occasionally, a video will end up being black, and it gives me some different errors.

**Comment by sebakerckhof** [comment] 2019-09-05 15:26
@tcd156 Thanks, but the patch fails to apply for me. Is that for the current version (6.0.7?)
Anyway, the weird thing is that my build does work WITH hardware acceleration on ubuntu 18.10 (without the patch, only the build flag). So it seems to be some Debian 10 thing. But then again, the ubuntu-chromium build does work on debian 10.

**Comment by tcd156** [comment] 2019-09-05 16:00
Ah my bad, it's for 6.0.2. I'm seeing the same thing that you are.

**Comment by sebakerckhof** [comment] 2019-09-06 14:33
@tcd156 nevermind, I got it working with 6.0.7 after moving it earlier in the patches list. Now it indeed seems to work on my Debian 10 system. Awesome!

**Comment by tcd156** [comment] 2019-09-06 14:36
@sebakerckhof where did you move it in the patch list?

**Comment by sebakerckhof** [comment] 2019-09-06 14:46
Basically all the way at the top now (was all the way at the bottom before).

**Comment by paravz** [comment] 2020-09-03 06:22
FYI Fedora maintains and builds chromium with vaapi support: https://github.com/rpmfusion/chromium-freeworld/tree/master

**Comment by superm1** [comment] 2021-02-23 16:52
In the PR for this bug there was a mention of:

> @tcd156 We are trying to remain as close as possible to upstream Chromium to avoid us having to handle upstream issues in code paths that upstream does not exercise. Once Chromium enables this by default we will inherit that flag.

It's been merged into chromium stable as of R88.  Some links:
https://bugs.chromium.org/p/chromium/issues/detail?id=1097029#c28
https://www.reddit.com/r/linux/comments/k5s4n5/google_chrome_v88_got_hardwareaccelerated/
https://www.reddit.com/r/linux/comments/lqkbuq/google_chrome_v88_is_stable_now_and_finally/

Perhaps this can _now_ be merged into electron too, and projects using electron can then benefit as well.

**Comment by Informatic** [comment] 2021-03-03 15:13
Well then. Since Electron 12 based on Chromium 89 has been released yesterday this should likely work. However I don't seem to be able to get anything beyond `Video decode: Software only. Hardware acceleration disabled.` with following flags:
```
      app.commandLine.appendSwitch('enable-accelerated-mjpeg-decode');
      app.commandLine.appendSwitch('enable-accelerated-video');
      app.commandLine.appendSwitch('ignore-gpu-blocklist');
      app.commandLine.appendSwitch('enable-native-gpu-memory-buffers');
      app.commandLine.appendSwitch('enable-gpu-rasterization');
      app.commandLine.appendSwitch('enable-oop-rasterization');
      app.commandLine.appendSwitch('disable-gpu-driver-bug-workarounds');
```

"Accelerated video decode has been disabled, either via blocklist, about:flags or the command line".

Am I missing something still? I'd assume switch order doesn't really matter? Confirmation that this works from someone else would be greatly appreciated, as _i use nixos btw_, and that might be the culprit somewhere...

**Comment by superm1** [comment] 2021-03-03 15:37
@Informatic  Presumably Intel right?  Make sure you have https://github.com/intel/intel-vaapi-driver installed too.

**Comment by fabianski7** [comment] 2021-03-03 16:50
> Am I missing something still? I'd assume switch order doesn't really matter? Confirmation that this works from someone else would be greatly appreciated, as _i use nixos btw_, and that might be the culprit somewhere...

try `enable-accelerated-video-decode` instead of just `enable-accelerated-video`

**Comment by Informatic** [comment] 2021-03-03 17:49
Ah, nice catch, but that sadly doesn't seem to change either. I'll check if this even works in plain chrome in that specific environment in the following days.

**Comment by Informatic** [comment] 2021-03-04 15:39
I've managed to get this tested on Ubuntu & Intel x64-based laptop using following script: https://gist.github.com/Informatic/6a5597ed8321035074e2c9a5a2847371 (with plain electron 12 downloaded from npm)

Electron returns:
```
Graphics Feature Status
Canvas: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Hardware accelerated
OpenGL: Enabled
Rasterization: Hardware accelerated on all pages
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
Problems Detected
Accelerated video decode has been disabled, either via blocklist, about:flags or the command line.
Disabled Features: video_decode
```

Chromium (Version 88.0.4324.182 (Official Build) snap (64-bit)) running on the same hardware with `chrome://flags/#enable-accelerated-video-decode` flag manually switched however seems to work fine:
```
Graphics Feature Status
Canvas: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Hardware Protected Video Decode: Unavailable
Rasterization: Software only. Hardware acceleration disabled
Skia Renderer: Enabled
Video Decode: Hardware accelerated
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

Any tips on what am I might be missing still?

**Comment by superm1** [comment] 2021-03-09 05:39
Try to launch with this flag: `-enable-feature=VaapiVideoDecoder"`

**Comment by Informatic** [comment] 2021-03-09 06:46
Ah, thanks. That indeed did the trick. Totally missed a note about that
flag on Arch Wiki I've been scrolling through for the past couple of days...

Only other issue I have now is that general gpu performance on my intel
test box seems to be atrocious (4k video in 500x500px video tag gets
rendered at approx 1fps, bottlenecking at `Render/3D/0` in intel-gpu-top,
unless I completely disable all gpu accel, but that might be just some
xorg/driver/compositor misconfiguration), but that is completely unrelated,
and I will need to investigate it regardless.

**Comment by superm1** [comment] 2021-03-09 12:46
> Ah, thanks. That indeed did the trick. Totally missed a note about that
> flag on Arch Wiki I've been scrolling through for the past couple of days...
> 
> Only other issue I have now is that general gpu performance on my intel
> test box seems to be atrocious (4k video in 500x500px video tag gets
> rendered at approx 1fps, bottlenecking at `Render/3D/0` in intel-gpu-top,
> unless I completely disable all gpu accel, but that might be just some
> xorg/driver/compositor misconfiguration), but that is completely unrelated,
> and I will need to investigate it regardless.
> 

So just to confirm - using that option alone is enough to get it "working"?

**Comment by Informatic** [comment] 2021-03-09 12:55
Yes, seems like just the following flag is sufficient to get the video start getting decoded using hardware acceleration. 
```js
app.commandLine.appendSwitch('enable-features', 'VaapiVideoDecoder');
```

`chrome://gpu` shows `Video decoding: hardware accelerated`, and `chrome://media-internals` shows `MojoVideoDecoder` being used.

**Comment by superm1** [comment] 2021-03-09 15:43
Great! @TRPB this issue can now be closed that means.  Any electron app that wants to enable this just needs to add
```javascript
app.commandLine.appendSwitch('enable-features', 'VaapiVideoDecoder');
```

And as long as host has the right VA library it should work.

**Comment by electron-triage** [comment] 2021-03-09 19:39
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 19:39 UTC
Labels: component/build
