### ISSUE TITLE
Opening multiple windows with `fullscreen: true` does not work correctly

### ISSUE THREAD

**Issue by caseywebdev** [electron/electron#13077] opened 2018-05-25 21:47 UTC
* Electron Version: 2.0.2
* Operating System (Platform and Version): macOS 10.13.4
* Last known working Electron version: 

**Expected Behavior**
If N windows are created with the `fullscreen: true` option, all N will open in fullscreen.

**Actual behavior**
Only the first of N windows is fullscreen while the others remain windowed.

**To Reproduce**

```js
const { app, BrowserWindow } = require('electron');

app.on('ready', () => {
  const win1 = new BrowserWindow({ fullscreen: true });
  const win2 = new BrowserWindow({ fullscreen: true });
});
```

Notice that `win1` will successfully fullscreen while `win2` stays windowed. Additionally, there is an audible system error beep.

**Additional Information**
We are currently working around this issue in our product by queueing fullscreen calls so they happen serially, but it would be much nicer if this concern was handled in electron itself.

**Comment by codebytere** [comment] 2018-07-13 22:15
I've successfully reproduced this, and also hear the system beep, but am having some trouble surfacing anything resembling an error to give me a hint as to why this is happening.

I'll continue to investigate!

**Comment by bpasero** [comment] 2018-12-05 14:04
This hits VSCode users as well: https://github.com/Microsoft/vscode/issues/32247

Even worse, if you ask the window for being fullscreen or not, it reports that it is fullscreen which causes some behaviour in VSCode which then is getting into a bad state.

**Comment by codebytere** [comment] 2018-12-05 16:30
I'm fairly certain this issue arises because both windows initially attempt to fullscreen into the same space, which MacOS disallows. I'll look to see how this might be mitigated.

**Comment by bpasero** [comment] 2018-12-05 16:41
Yeah that is a good theory 👍

**Comment by codebytere** [comment] 2018-12-05 17:19
After some research i don't think there's currently a way to address this :( In order to ensure that both windows fullscreen into separate spaces i'd need first to identify the currently occupied space, and then to force the N+1 window into a new space. The only APIs that exist to do this are private CoreGraphics APIs as seen [here](https://gist.github.com/rjw57/5495406), which would accomplish the goal but then prevent any user of these APIs from submitting to the Ap store, which imo is too high a cost compared to benefit. As such, i'm going to close this out for now but will come back to and reopen it the moment that Apple steps up their Spaces support and documentation.

**Closed by codebytere** 2018-12-05 17:19 UTC
Labels: 2-0-x, bug :beetle:, platform/macOS

**Comment by ariofrio** [comment] 2019-03-08 04:58
VSCode user here. This is a pretty significant usability issue. Would it make sense to implement the workaround with CoreGraphics APIs behind a flag? This way apps that are not on the Mac App Store, such as VSCode, anyway can choose to enable it.
