### ISSUE TITLE
[Bug]:  electron 14 gpu init error

### ISSUE THREAD

**Issue by kevinwang930** [electron/electron#30806] opened 2021-09-02 06:29 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.0

### What operating system are you using?

Windows

### Operating System Version

windows 10 version 19042

### What arch are you using?

x64

### Last Known Working Electron version

13.2

### Expected Behavior

electron start without error message.

### Actual Behavior

electron start with gpu init error message
```
[8792:0902/141605.106:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
```

**Comment by codebytere** [comment] 2021-09-02 07:19
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by kevinwang89** [comment] 2021-09-03 09:14
I can not use Electron Fiddle because I can not add other kinds of files in fiddle.
there are just 2 error messages in the main console, the app works fine. 
```
[8976:0903/171252.173:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
[30528:0903/171325.398:ERROR:command_buffer_proxy_impl.cc(328)] GPU state invalid after WaitForGetOffsetInRange.
```

**Comment by kevinwang89** [comment] 2021-09-03 20:24
locate one error caused by `commandline.appendSwitch` 
[gist link](https://gist.github.com/kevinwang89/20fac2d445e956d115b30559b638ce07)

**Closed** 2021-09-27 13:50 UTC
Labels: bug :beetle:, blocked/need-repro

**Comment by ivancuric** [comment] 2021-09-30 12:00
I am getting this same error when updating a React state by dragging an `<input>` slider. Happens if the video is onscreen or not.

https://user-images.githubusercontent.com/2827047/135451198-05858463-0430-4825-addd-21031d533059.mp4
