### ISSUE TITLE
Dropping items onto a webview doesn't trigger the 'drop' event

### ISSUE THREAD

**Issue by flexpaper** [electron/electron#8667] opened 2017-02-13 00:07 UTC
* Electron version: 1.6.0
* Operating system: OSX

### Expected behavior

Expecting event 'drop' on the document object to fire

### Actual behavior
Electron triggers a file open dialogue

### How to reproduce
1) Bind the drop event in the BrowserWindow control, ie;

```js
document.addEventListener('drop',function(event){
      console.log("I'm getting " + event.dataTransfer.files.length); 
});
```

2) Drop a file into a webview in the browser window. Event listener doesn't fire. Fires in stable versions of electron. This may be intended but it used to fire the event. Version 1.4.15 fires the event even if dropped into a webview

**Comment by tlgreg** [comment] 2017-02-13 13:13
You also need to run `event.preventDefault()` on the drop and dragover events too (on document), does that help?

**Comment by tlgreg** [comment] 2017-02-13 17:01
On Windows it works.
`event.preventDefault()` both in `document.ondragover` and `document.ondrag` prevents the opening of the file. If either missing it will open the file, if not prevented in the ondragover then your drag event doesn't run at all. Same behavior in 1.4.15 and 1.6 beta on Windows.

**Comment by flexpaper** [comment] 2017-02-13 20:07
@tigreg did you drop the file into a Webview control on 1.6.0 on Windows (not the main browser window)?

**Comment by tlgreg** [comment] 2017-02-14 01:29
Sorry, my bad. I tried in an existing app, but we use an overlay above the webview when dragging a file. (_I always tell myself not to comment when didn't slept._)

I just tried with fresh app and reproducable with Windows (8.1).

What I can add to the issue is the webview crashes on dragenter.
Also if the webview didn't crash before the drop, the drop event only fired in the external document, but not on the webview object in the parent BrowserWindow.

**Comment by kevinsawicki** [comment] 2017-02-14 21:32
> What I can add to the issue is the webview crashes on dragenter.

@tlgreg are you able to provide the code you are using when you see this crash? Thanks.

**Comment by kevinsawicki** [comment] 2017-02-15 01:10
May be related to https://github.com/electron/electron/issues/3146

**Comment by ronnievdv** [comment] 2017-02-24 07:06
Drag and drop between webviews also doesn't trigger drop, dragenter, dragleave or dragover events.  See attached example which works in 1.4 but not in 1.6

[electron-dnd.zip](https://github.com/electron/electron/files/798555/electron-dnd.zip)

**Comment by brenca** [comment] 2017-03-09 20:19
I've looked into this, and fixed it with a tiny patch in electron/libchromiumcontent#267.

**Comment by flying-circus** [comment] 2017-04-01 15:10
I just updated to latest electron@beta (1.6.5) supposed to have this fixed but this bug still exists. 
Anyone else can confirm?

**Comment by kevinsawicki** [comment] 2017-04-01 15:11
@flying-circus can you include a reproduction example that shows this still happening?

I was testing it out with https://github.com/electron/electron/files/798555/electron-dnd.zip

**Comment by flying-circus** [comment] 2017-04-01 15:32
Thanks for the quick reply. 
Your example is half-working. It works if you drop the "drag div" in it, but if I drop a url in it, although it fires the 'drop event', it also navigates to the url. So my quick bet is sth in event.preventDefault isn't working?

**Comment by kevinsawicki** [comment] 2017-04-05 18:20
> So my quick bet is sth in event.preventDefault isn't working?

@brenca would you be able to look into this?

**Comment by brenca** [comment] 2017-04-07 14:20
@kevinsawicki sure, I'll look into it

**Comment by brenca** [comment] 2017-04-09 14:31
@kevinsawicki @flying-circus I've tested the behaviour of electron 1.4 and 1.6 with this patch applied, and I see the same thing happening. In the given example in `right.js` only a `stopPropagation` is called on the `drop` event, thus the default behaviour is not prevented (in fact both 1.4 and 1.6 patched loads the url). If I call `preventDefault`, the url is not loaded. Can you confirm this?

**Comment by flying-circus** [comment] 2017-04-11 10:41
@brenca You're right and I apologize, my reply to kevinsawicki was hasty. I still have a problem though, I ll try to locate it and give feedback.

**Comment by flying-circus** [comment] 2017-04-12 14:31
@brenca The problem is that in my case I am setting event listeners from index.html to a webview. In the @kevinsawicki 's example they are inserted by a preload script **inside** each webview. Trying to prove this using Kevin's example, I removed the the `preload` script "right.js" from webview tag at line 9 of `index.html`, and tried to add it into `renderer.js` (which is loaded from index.html) like this:
```js
document.addEventListener('DOMContentLoaded', () => {
	setTimeout(() => {
		let leftView = document.getElementById('left-view');
		leftView.openDevTools();

		let rightView = document.getElementById('right-view');
		rightView.openDevTools();
                //START of my insertion 
	        rigthView.addEventListener('drop', function(ev) {  //Reference rightView error??!!?
		  this.style.backgroundColor = 'lightgrey';
		  alert('dropped!');
	        });
               //END
	}, 1000);
}, false);;
```
I'm getting a reference error right after it's refernced OK from the .opedDevTools() method??? 
Is sth broken in HTMLObjectElement.prototype and the way is applied to webview tags instances?
Adding it "manually" like `document.getElementById('right-view'),addEventListener()`  doesnt work either. 
Catching "event listerner breakpoints" from DevTools doesn't seem to work either.

**Comment by flying-circus** [comment] 2017-04-12 14:44
@brenca The problem is that in my case I am setting event listeners from index.html to a webview. In the @kevinsawicki 's example they are inserted by a preload script **inside** each webview. Trying to prove this using Kevin's example, I removed the the `preload` script "right.js" from webview tag at line 9 of `index.html`, and tried to add it into `renderer.js` (which is loaded from index.html) like this:
```js
document.addEventListener('DOMContentLoaded', () => {
	setTimeout(() => {
		let leftView = document.getElementById('left-view');
		leftView.openDevTools();

		let rightView = document.getElementById('right-view');
		rightView.openDevTools();
                //START of my insertion 
	        rigthView.addEventListener('drop', function(ev) {  //Reference rightView error??!!?
		  this.style.backgroundColor = 'lightgrey';
		  alert('dropped!');
	        });
               //END
	}, 1000);
}, false);;
```
I'm getting a reference error right after it's refernced OK from the .opedDevTools() method??? 
Is sth broken in HTMLObjectElement.prototype and the way is applied to webview tags instances?
Adding it "manually" like `document.getElementById('right-view'),addEventListener()`  doesnt work either. 
Catching "event listerner breakpoints" from DevTools doesn't seem to work either.

**Comment by KochiyaOcean** [comment] 2017-04-19 12:23
I've found that drop an image on webview will make it navigate even if event.preventDefault() is called.
It can be reproduced on electron 1.6.x but former version havn't this problem.

For example, create an webview like 
```html
<webview src="about:blank" ondrop="event.preventDefault();"></webview>
```
and drop an image on it.

**Comment by zcbenz** [comment] 2017-06-06 06:53
The webview is implemented as browser plugins in Chromium, so you have to run the code inside the webview. I'm closing this since the behavior is by design, I suggest reporting this to https://crbug.com for improvement.

**Closed by zcbenz** 2017-06-06 06:53 UTC
Labels: component/drag-and-drop, component/webview, fixme/regression, triage/bug, version/1.6.x
