### ISSUE TITLE
frameless window  win.maximizable and win.isMaximizable() always return false

### ISSUE THREAD

**Issue by rbmyself** [electron/electron#23493] opened 2020-05-11 03:53 UTC
### code 

header.vue:
```
import { remote, ipcRenderer, clipboard, shell } from 'electron';
let thisWindow = remote.getCurrentWindow();
const thisview = thisWindow.getBrowserView();
export default {
    name: 'header',
    created() {
        console.log(thisWindow, thisWindow.maximizable, thisview);
        this.isMaximizable = thisWindow.maximizable;
    },
}
```
after I change the frame value to true while create the window , the maximizable will return the right value which is set while created the window
### Issue Details

* **Electron Version:**
  "electron": "8.2.0",

**Comment by codebytere** [comment] 2020-06-04 21:08
Duplicate of https://github.com/electron/electron/issues/20151

**Closed by codebytere** 2020-06-04 21:08 UTC
