### ISSUE TITLE
BrowserWindow with sandbox enabled gets unresponsive and crashes when 'new-window' event is prevented

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#21377] opened 2019-12-04 07:56 UTC
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.3
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * Unkown

### Expected Behavior
To prevent the creation of the new window without crashing and unresponsive.

### Actual Behavior
The subprocess gets unresponsive and crashes.

### To Reproduce
https://gist.github.com/4d36be07d7b1cfc6244477cb989b86d3

### Screenshots
![image](https://user-images.githubusercontent.com/5815794/70123868-350cab80-167c-11ea-842b-47a41b3a005b.png)
![image](https://user-images.githubusercontent.com/5815794/70123915-4950a880-167c-11ea-8455-41853ea76dac.png)

**Comment by loc** [comment] 2019-12-04 21:05
Duplicate of #20086. We're working on it!

**Closed by loc** 2019-12-04 21:05 UTC
