### ISSUE TITLE
webContents.print silent option ignored when passed callback.

### ISSUE THREAD

**Issue by obermillerk** [electron/electron#10545] opened 2017-09-18 15:42 UTC
* Electron version: 1.7.6
* Operating system: Windows 10 1703

### Expected behavior

The print task should be sent without showing the system dialog.

### Actual behavior

The system dialog is shown and no print event is sent until the dialog is addressed.  Additionally, canceling the dialog doesn't seem to do anything with the callback which is perhaps intended behavior but leaves my app hanging since it depends on that callback being called to know it can continue.

### How to reproduce

clone [`https://github.com/obermillerk/electron-print-bug`](https://github.com/obermillerk/electron-print-bug)
npm install
npm start

Note that if the page actually prints, it should be blank since the webpage didn't necessarily load yet, but the behavior when a callback is provided should be the same.

You can remove the callback to see that the silent printing works without it.

You can also see that cancelling the system dialog doesn't call the callback because it prints nothing.

**Comment by felipebcs** [comment] 2017-11-02 14:24
I'm using electron 1.6.10 and the behavior is the same. I had to remove the callback to print silently.

**Comment by dalewesa** [comment] 2018-02-13 17:21
I'm using electron 1.7.6 and the issue is still there

**Comment by shhdharmen** [comment] 2018-04-04 14:52
I had the same issue, I updated electron to 1.8.4 and it's working now. It might help to you guys too.

**Comment by sofianguy** [comment] 2019-01-08 18:30
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:14
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-01-15 20:14 UTC
Labels: blocked/need-info, bug :beetle:, platform/windows, version/1.7.x
