### ISSUE TITLE
[Bug]: "ready-to-show" call twice.

### ISSUE THREAD

**Issue by Kenhuey** [electron/electron#30308] opened 2021-07-28 13:35 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.X

### What operating system are you using?

Windows

### Operating System Version

w10 19042.1110

### What arch are you using?

x64

### Expected Behavior

```
browserWindow.on("ready-to-show", () => {
    browserWindow.show();
    mainLogger.info("Main window ready to show.");
  });
```

### Actual Behavior

When window ready normally this lambda method call once, but twice called.

Console output result:
```
[2021-07-28T21:35:06.524] [INFO] main - Main window ready to show.
[2021-07-28T21:35:06.736] [INFO] main - Main window ready to show.
```

**Comment by Kenhuey** [comment] 2021-07-28 13:42
May browserWindow.once(...) can deal with it, but i think "ready-to-show" call twice is a bug, when i use the electron generate code it still happened.

**Comment by codebytere** [comment] 2021-07-28 14:01
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by MarshallOfSound** [comment] 2021-07-28 21:07
It's not documented or implied that `ready-to-show` will only be emitted once, in fact I'm fairly sure it will be emitted every time the window is painted and the window has not yet been shown.  Closing this out as expected behavior, if you truly what to only have to occur once then as you indicated you should use `.once` instead of `.on`

**Closed by MarshallOfSound** 2021-07-28 21:07 UTC
Labels: blocked/need-repro, bug :beetle:

**Comment by Kenhuey** [comment] 2021-07-29 06:18
@MarshallOfSound Thank you,  .once work well. but this event emitted twice, why? did the window painted twice?

**Comment by yykoypj** [comment] 2023-07-07 09:38
I think it should be mentioned in docs if `ready-to-show` may emit twice or more.
