### ISSUE TITLE
Silent Print Not Working...

### ISSUE THREAD

**Issue by victormongi** [electron/electron#18543] opened 2019-05-31 10:02 UTC
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  *

**Comment by jkleinsc** [comment] 2019-05-31 14:59
Closing as duplicate of #18123

**Closed by jkleinsc** 2019-05-31 14:59 UTC
