### ISSUE TITLE
Debugging electron (osx)?

### ISSUE THREAD

**Issue by wilsonpage** [electron/electron#6381] opened 2016-07-07 15:08 UTC
I want to contribute to the Electron project. I read the [build instructions](https://github.com/electron/electron/blob/master/docs/development/build-instructions-osx.md) and was able to build with no issues. Now I want to start making code changes, but as Electron is built with Ninja and not XCode, I'm a little confused where to begin.

- What IDE should I be using?
- Can I use XCode?
- What is the recommended development/debugging workflow?

**Comment by wilsonpage** [comment] 2016-07-07 15:10
Ping @joshaber who worked on xcode related patch https://github.com/electron/electron/pull/3015

**Comment by zcbenz** [comment] 2016-07-08 00:31
This is a duplicate of #5494.

To answer your questions:

> What IDE should I be using?

You can use any text editor you like, such as Atom and VS Code.

> Can I use Xcode?

You can only use it like a text editor, but the IDE features are not available.

> What is the recommended development/debugging workflow?

Edit the source code in text editor, and build Electron with the scripts.

**Closed by zcbenz** 2016-07-08 00:31 UTC
