### ISSUE TITLE
In renderer process invoking the DownloadItem.setSavePath still pop prompt a save dialog

### ISSUE THREAD

**Issue by guanyong1993** [electron/electron#6964] opened 2016-08-25 02:54 UTC
* Electron version:1.3.3
* Operating system:Windows7

Why in renderer process the webContents.session Event 'will-download' callbacks params DownloadItem Method setSavePath('path')  it had no effect. But in main process is all right

```
// In the renderer process.
const {BrowserWindow} = require('electron').remote
let win = new BrowserWindow()
win.webContents.session.on('will-download', (event, item, webContents) => {
    // Set the save path, making Electron not to prompt a save dialog.
    item.setSavePath('/tmp/save.pdf')
    // Then Electron still pop prompt a save dialog.
})
```

**Comment by enlight** [comment] 2016-08-25 03:02
Duplicate of #4061

**Closed** 2016-08-25 03:34 UTC

**Comment by MarshallOfSound** [comment] 2016-08-25 03:35
As @enlight , this is a duplicate of #4061

**Comment by guanyong1993** [comment] 2016-08-25 04:07
Thanks, The problem has been solved.  In main process, add prototype method to BrowserWindow. Then in renderer process invoking this method.  
code:

```
// In the main process.
const electron = require('electron');
electron.BrowserWindow.prototype.setDownloadSavePath = function (path) {
    this.webContents.session.once('will-download', (event, item) => {
        item.setSavePath(path + '/' + item.getFilename());
    });
};


// In the renderer process.
const remote = require('electron').remote;
let win = remote.getCurrentWindow();
win.setDownloadSavePath(`${remote.app.getPath('downloads')}`);
```
