### ISSUE TITLE
print  blurring

### ISSUE THREAD

**Issue by hinnncom** [electron/electron#18951] opened 2019-06-24 03:13 UTC
### Issue Details

* **Electron Version:**
  * 3.1.11
* **Operating System:**
  * Windows Server 2012 R2
* **Last Known Working Electron version:**
  * None

### Expected Behavior
webContents.print(option, callback) print  blurring use virtual pdf printer when deviceName have value .

### Actual Behavior
webContents.print({ silent: true, printBackground:true,deviceName: data.deviceName }

print  blurring when deviceName have value print blurring
![image](https://user-images.githubusercontent.com/48546169/59989222-c9f08f00-9670-11e9-89a6-4f46b487f018.png)

but if deviceName have no value , print is defined

I'm not sure if this is a BUG, and I still want to find a solution. Thank!!!

**Comment by codebytere** [comment] 2019-06-24 04:13
Duplicate of https://github.com/electron/electron/issues/18917.

**Closed by codebytere** 2019-06-24 04:13 UTC
