### ISSUE TITLE
[Bug]: Mac crash on WebWorker destructor

### ISSUE THREAD

**Issue by DanielMcAssey** [electron/electron#35384] opened 2022-08-19 13:30 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.3

### What operating system are you using?

macOS

### Operating System Version

12.3

### What arch are you using?

x64

### Last Known Working Electron version

20.0.2

### Expected Behavior

When destructing WebWorkers, it should not crash

### Actual Behavior

When destructing a WebWorker that uses WebAssembly, it crashes the v8 context.

### Additional Information

It seems linked to the recent change to the "stop_and_close_uv_loop" change, seen here: #35322
If I revert that single change, it does not crash.

Attached is a minidump

[minidump.zip](https://github.com/electron/electron/files/9382529/e9384a04-0947-4e26-b452-c85e84309bf9.zip)

**Comment by zcbenz** [comment] 2022-08-22 07:11
@DanielMcAssey Can you also paste the crash report which can be found in `Console.app`?

**Comment by codebytere** [comment] 2022-08-22 08:07
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by DanielMcAssey** [comment] 2022-08-22 15:14
> @DanielMcAssey Can you also paste the crash report which can be found in `Console.app`?

Here is the crash report

[Electron Helper (Renderer)-2022-08-19-112907.zip](https://github.com/electron/electron/files/9395536/Electron.Helper.Renderer.-2022-08-19-112907.zip)

**Comment by DanielMcAssey** [comment] 2022-08-22 15:46
> @DanielMcAssey could you please also attach a reproducible sample? Perhaps using Fiddle?

Here is the gist: https://gist.github.com/211d077ebeef2d0c19b136000503db59

**Comment by miniak** [comment] 2022-08-28 20:26
I am getting these crashes in https://github.com/electron/fiddle/pull/1169 and https://github.com/electron/fiddle/pull/1168
I don't seem to have a repro in https://github.com/electron/fiddle/pull/1170 as `UV_LOOP_INTERRUPT_ON_IO_CHANGE` is not present in 18-x-y

**Comment by zcbenz** [comment] 2022-08-29 07:26
@miniak Does the https://github.com/electron/electron/pull/35422 fix the crashes?

**Comment by DanielMcAssey** [comment] 2022-08-29 13:46
@codebytere Thank you!

**Closed** 2022-08-29 13:45 UTC
Labels: platform/macOS, platform/linux, bug :beetle:, 20-x-y, 21-x-y
