### ISSUE TITLE
polling desktopCapturer.getSources() crashes the electron app

### ISSUE THREAD

**Issue by deeptabs** [electron/electron#11304] opened 2017-12-01 07:55 UTC
Electron version: 1.7.9
Operating system: OSX

### Expected behavior

App should not crash when **desktopCapturer.getSources()** is polled.

### Actual behavior

Calling **desktopCapturer.getSources()** causes the app to crash, using the code this way 

```
pollForDesktopCapturer: function(){
         var self= this;
         electron.desktopCapturer.getSources({types: ['window', 'screen']}, function(error, sources) {
             if (error) throw Logger.error("error getting screen share content --- ", error);
             self.model.set('screens', sources);
             setTimeout(self.pollForDesktopCapturer.bind(self), 7000);
        });
},
```

### Why am i polling?

Need to update users with the latest screen capture of the apps open every 5 to 7 seconds, even if the user opens an app freshly. I realise that `getSources` is a highly-expensive API and it is not advised to poll. Is there an alternative method i can use?
Considering that i need the source id of the app since i need to start screen share of the app when the user clicks on the image displayed.

**Comment by anand-io** [comment] 2017-12-01 15:59
This is happening for us too.
* Electron version: Electron version: any version with ```electron.desktopCapturer.getSources``` API 
* Operating system: OSX High Sierra 10.13.1

Steps to reproduce:
Call this below code between 1-10 times, the app will crash.

```require('electron').desktopCapturer.getSources({ types: ['screen'] }, (error, sources) => {
console.log(sources[0].id);
});```

Note: this is happening only in OSX High Sierra

**Comment by Nikitikitavi** [comment] 2017-12-06 12:03
+1
Same situation.

 As understand @rongilson in this issue https://github.com/electron/electron/issues/9600 able to fix the problem. But I don't understand how to implement his fix, no those folders in electron project. 

Any update on this?

**Comment by Ajeey** [comment] 2017-12-07 07:22
+1

I am able to easily reproduce this issue on Mac.
Here is the sample repo that demonstrates the issue
https://github.com/Ajeey/electron-crash-demo

**Comment by kamesh-a** [comment] 2017-12-07 13:50
+1

**Comment by Ajeey** [comment] 2017-12-14 08:07
@zcbenz @zeke @MarshallOfSound Can we get some attention on the above issue please?
It is turning out to be a show stopper for us :(

**Comment by zeke** [comment] 2018-01-24 19:53
Looks like a fix for this landed in https://github.com/electron/libchromiumcontent/pull/418

**Closed by zeke** 2018-01-24 19:53 UTC
Labels: fixme/crash, platform/macOS, version/1.7.x

**Comment by jstlaurent** [comment] 2018-01-24 20:23
@zeke, was this bundled with today's releases (1.7.11, 1.8.2)? I'm still new to developing with Electron, so I'm unsure where I can see if that's the case.

**Comment by zeke** [comment] 2018-01-25 18:42
@jstlaurent I think this will land in 2.0.0. Not sure we have a target date for that yet.
