### ISSUE TITLE
Tiny border visible on frameless, transparent window

### ISSUE THREAD

**Issue by kkitay** [electron/electron#15712] opened 2018-11-14 16:49 UTC
Mac OS 10.14
Electron v3.0.6

**Expected Behavior**
A frameless, transparent window with no shadow should have no borders.

**Actual behavior**
There is a border not being generated by my HTML file wrapping around the top of the browser window. It's small and white but quite obvious on certain backgrounds.

<img width="314" alt="screen shot 2018-11-14 at 11 47 34" src="https://user-images.githubusercontent.com/1082318/48498002-3fef6680-e803-11e8-9938-f4dc1fb8aa4c.png">

**To Reproduce**
```
$ git clone git@github.com:kkitay/terra.git
$ npm install
$ npm run dev
```

**Comment by nornagon** [comment] 2018-11-14 21:17
Duplicate of #13164

**Closed by nornagon** 2018-11-14 21:17 UTC
