### ISSUE TITLE
Electron 2.0.X requires High Perf GPU on macOS

### ISSUE THREAD

**Issue by DeathTickle** [electron/electron#13303] opened 2018-06-19 19:20 UTC
* Electron Version: 2.0.0, 2.0.1, 2.0.2
* Operating System (Platform and Version): macOS 10.12.6
* Last known working Electron version: 1.8.7

**Expected Behavior**
I expect Electron to not use the dedicated GPU by default.

**Actual behavior**
On macOS, using a Macbook pro with both integrated and dedicated graphics (Early 2011 model), when starting an Electron app, I can observe the graphics card switching to High Perf mode in Activity Monitor. I can also see it is the Electron app that requires High Perf GPU.

**To Reproduce**
Run the electron-quick-start project. Using the latest version, observe the activity monitor and check the Graphics Card status.

Then revert to a previous commit before the upgrade to 2.0 Electron version and reinstall dependencies. Run the project, observe the activity monitor and check the Graphics Card status.

I am guessing that to reproduce this a Macbook model with dedicated graphics is required. The linked issue shows the behavior happens on macOS 10.12 and 10.13.

**Linked Issue**
Issue first reported in Signal [here](https://github.com/signalapp/Signal-Desktop/issues/2455).

**Comment by miniak** [comment] 2018-07-03 13:51
@DeathTickle is your app using WebGL?

**Comment by DeathTickle** [comment] 2018-07-19 18:28
@miniak I am just using the electron-quick-start app. I wouldn't think that one would be using WebGL. The original app I found the problem in is Signal and I don't think that one uses WebGL either.

**Comment by sallar** [comment] 2018-08-24 16:36
I confirm this is a UI glitch in Electron 2.x. I downgraded to Electron 1.8 and everything is fine.

**Comment by jcayzac** [comment] 2018-08-26 13:03
As posted [here](https://github.com/atom/atom/issues/17694#issuecomment-414645196), I can reproduce this on my MBP 2010 but not my MBP 2013 (both on the latest version of High Sierra and both with NVidia GPUs).

Passing the `--disable-gpu` does disable using the discrete GPU, but only in the helper processes (`Atom Helper`). The main process (`Atom`) still requires the discrete GPU.

In Chromium, using the `Disable Hardware Acceleration` setting does disable the user of the discrete GPU for all the Chromium processes.

**Comment by pronebird** [comment] 2018-10-22 12:23
Can you reproduce this with Electron v3?

**Comment by nornagon** [comment] 2018-10-22 19:36
There's an entry in the [gpu driver bug list](https://chromium.googlesource.com/chromium/src/+/66.0.3359.203/gpu/config/gpu_driver_bug_list.json) that forces usage of the discrete GPU on older macbooks:

```
    {
      "id": 48,
      "description": "Force to use discrete GPU on older MacBookPro models",
      "cr_bugs": [113703],
      "os": {
        "type": "macosx"
      },
      "machine_model_name": ["MacBookPro"],
      "machine_model_version": {
        "op": "<",
        "value": "8"
      },
      "gpu_count": {
        "op": "=",
        "value": "2"
      },
      "features": [
        "force_discrete_gpu"
      ]
    },
```

and another entry that specifically avoids the Intel HD 3000 card due to crashes:

```
    {
      "id": 228,
      "description": "Intel HD 3000 driver crashes frequently on Mac",
      "cr_bugs": [720152],
      "os": {
        "type": "macosx"
      },
      "vendor_id": "0x8086",
      "device_id": ["0x0116", "0x0126"],
      "multi_gpu_style": "amd_switchable",
      "features": [
        "force_discrete_gpu"
      ]
    },
```

Can you confirm whether one of these is applying? You can check by opening `about:gpu` in Chrome and searching for `force_discrete_gpu`.

Does Chrome also force usage of the discrete GPU?

**Comment by jcayzac** [comment] 2018-10-22 22:54
@nornagon I will check about_gpu when I’m back home. I think they probably apply (mine is a 6,2 model) but checking the misnamed “Disable Hardware Acceleration” setting has Chrome stick nicely to using the integrated GPU only.

**Comment by nornagon** [comment] 2018-10-22 23:39
If you disable hardware acceleration, chrome won't be using any gpu at all 🤷‍♂️

**Comment by jcayzac** [comment] 2018-10-22 23:42
@nornagon _directly_ is an important missing keyword in that last statement of yours.

If a pixel lights up on my display a GPU is being used. The days of a CPU addressing graphic memory are 20 years over.

**Comment by pronebird** [comment] 2018-10-24 20:03
We've got similar reports and were bummed that a browser window could spin off discrete GPU while rendering a solid background. Folks complained about loud fans, battery drain, and that the room temperate went up by 2 degrees. 

Does anyone know if the problem remains on Electron v3.0.5?

**Comment by sallar** [comment] 2018-10-27 10:55
Electron 3 seems to be ok and the issue is not there anymore in our case.

**Comment by Firstyear** [comment] 2018-11-03 00:55
> 
> Can you confirm whether one of these is applying? You can check by opening `about:gpu` in Chrome and searching for `force_discrete_gpu`.
> 

My system is an MBP 8,2 which would mean it's using the "      "description": "Intel HD 3000 driver crashes frequently on Mac"," Force option. Despite this "working just fine for me" with forcing the intel gpu to be active, I'm sure that there is a reason why this check was added by the chrome/chromium team. It could be worth following up with them and re-assessing if this is still needed because there have been many updates to MacOS since that could have resolved the issue.

**Comment by nornagon** [comment] 2018-11-05 23:32
Closing this issue; adjusting the GPU blacklist is beyond the scope of the Electron project and would need to be raised with the Chromium project.

**Closed by nornagon** 2018-11-05 23:32 UTC
Labels: 2-0-x, bug :beetle:, platform/macOS

**Comment by nornagon** [comment] 2018-11-06 01:07
Yes, you can pass `--ignore-gpu-blacklist`, though there might be some issues with that currently, see https://github.com/electron/electron/issues/15339

**Comment by mycroftcanner** [comment] 2020-11-09 15:38
I am getting super annoyed by all these electron apps using high perf GPU while I am on battery. You guys have complete disregard for the environment!

**Comment by jkleinsc** [comment] 2020-11-09 22:13
@mycroftcanner your comment was deleted as a violation of [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). You may consider this an official warning.

**Please do not interact with the project for 24 hours.** After that, please look through your open issues and edit them to ensure they're entirely on-topic, and we can continue the discussion here about the best way to go forward.
