### ISSUE TITLE
Fullscreen on Mac still shows window title and kiosk mode not working

### ISSUE THREAD

**Issue by iamdriz** [electron/electron#1054] opened 2015-01-25 13:31 UTC
I have the following code that creates a fullscreen window on OS X

atom-shell: 0.20.7

~~~
app.on('ready', function() {
	
	var Screen = require('screen');
	
	var size = Screen.getPrimaryDisplay().size;
	
	var width = size.width;
	var height = size.height;
	
	// Create the browser window.
	mainWindow = new BrowserWindow({
	  'width': width,
	  'height': height,
	  'max-width': width,
	  'max-height': height,
	  'fullscreen': true,
	  'frame': false,
	  'kiosk': true,
	  'transparent': true,
	  'show': true,
	  'resizable': false
	});
	
});
~~~

I have set the window to be the width and height of the window (this is because on OS X, you have a fullscreen API so windows can be fullscreen with any width or height.).

I have also set the window to be transparent, this is because if you hover your mouse over the menu bar then the window title slides down (grey with title). I have also disabled the frame to remove the shadows and rounded corners from the window.

However there are a couple of bugs:

1.) The window title bar still appears when you hover the menubar (even in transparent mode) the titlebar still appears (although the grey bar and title itself are removed).

![screen shot 2015-01-25 at 13 23 59](https://cloud.githubusercontent.com/assets/801252/5891580/6a831d24-a496-11e4-9173-33b9181e7b13.png)

2.) Is it possible to disable the menubar and dock when in fullscreen mode? I thought of using Kiosk mode, but even when I have that set to true, I can still access the menubar and dock!
**If I set the fullscreen to false then the kiosk mode works. It has to be set to false though, not setting the fullscreen option or setting it to null breaks the kiosk mode again.**

**Comment by zcbenz** [comment] 2015-01-26 18:28
It seems that kiosk mode is not working any more.

**Comment by mcdermed** [comment] 2015-02-10 20:15
Kiosk seems to be working on OSX but not Ubuntu 14 using atom-shell v0.21.2.

```
BrowserWindow({
  width: 800,
  height: 600,
  kiosk: true,
  show: true
});
```

**Comment by bryankennedy** [comment] 2015-04-24 16:20
I'm seeing the same behavior on 10.9.5. Kiosk mode doesn't block access to the dock or the menubar.

I've had this same problem with running Chrome in kiosk mode directly from the command line. The only way I was able to fix it was to modify the Info.plist file in the Chrome.app with this new directive:

    <key>LSUIPresentationMode</key>
    <integer>3</integer>

which is from the [Apple Launch Services documentation](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-108256).

I'm not that familiar with the Electron structure, but maybe it's possible that the kiosk config option could conditionally added this directive in [Electron's Info.plist](https://github.com/atom/electron/blob/master/atom/renderer/resources/mac/Info.plist).

**Comment by anonrig** [comment] 2015-07-06 17:04
@zcbenz this problem still continues. any news?

**Comment by szymonkaliski** [comment] 2015-07-30 19:33
Any news/workarounds on that?

**Comment by snawbel** [comment] 2015-10-21 07:28
Is it possible to somehow help out with this? Electron could be a *really* great and simple platform to make kiosk apps.

**Comment by anonrig** [comment] 2015-10-22 21:17
I believe this problem is solved with the new version

**Comment by bryankennedy** [comment] 2015-10-22 22:48
@anonrig Do you know what the problem was. Have a link to the fix code? Just personally curious.

**Comment by anonrig** [comment] 2015-10-25 19:00
Actually, I don't know the specific problem but I was using 0.30.0 and than updated my application to latest successful build and the problem was gone. Also, kiosk mode is working way more efficient and stable than before.

**Comment by snawbel** [comment] 2015-11-03 10:27
On OS X10.10.2 and Electron 0.34.0 with `kiosk: true, fullscreen: true, frame: false` the Apple bar and application bar is still visible on hover. So I wouldn't call this "solved".

![screen shot 2015-11-03 at 11 22 54](https://cloud.githubusercontent.com/assets/554578/10905879/8a0fe00e-821d-11e5-9d19-5ccf3f70bb86.jpg)

**Comment by superfunkminister** [comment] 2015-11-03 12:22
+1

**Comment by cgaubuchon** [comment] 2015-11-03 21:53
I have found that modifying the Info.plist and adding:

`
<key>LSUIPresentationMode</key>
<integer>3</integer>
`

Does what is intended for hiding both the taskbar and system menu bar and prevents them from being shown on hover.

However, once Electron is launched, if I drag a project (any project) to the Electron shell the menu and system bars will appear on hover, seemingly overriding the LSUIPresentationMode setting.

Electron: 34.2
OS: 10.10.4

**Comment by cgaubuchon** [comment] 2015-11-04 02:56
Did some investigation and found the issue to be related to [this SO post].(http://stackoverflow.com/questions/26694142/nsapplicationpresentationhidedock-has-no-effect) 

Basically, I built a version of electron that adds the code from the link to `windowDidEnterFullScreen`

What I found is that I can prevent process switching, toolbar, yet I cannot completely disable the dock. For some reason, the dock is being set to`NSApplicationPresentationAutoHideMenuBar` rather than being disabled `NSApplicationPresentationHideMenuBar ` no matter what I set the value to [as documented in the ADC](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSApplication_Class/#//apple_ref/c/econst/NSApplicationPresentationHideDock)

**Comment by zcbenz** [comment] 2016-01-06 14:34
I'm unable to reproduce this in 0.36.2.

**Comment by bryankennedy** [comment] 2016-01-06 17:49
I am still seeing this problem with 0.36.2. If it matters, I'm still running Yosemite (OS X 10.10.5).

I am running the Electron 0.36.2 prebuilt binary. To help demonstrate I forked the quick-start repo and only made two small changes: required 0.36.2 specifically, and enabled kiosk mode in the window call. The window call looks like:

```
mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  kiosk: true,
});
```

Once I install and launch electron I can still get to the dock and the menu bar with no problem.

Steps to reproduce:

```
$ git clone https://github.com/scimusmn/electron-kiosk-quick-start.git
$ cd electron-kiosk-quick-start
$ npm install && npm start
```

You can still get to the OS X menu bar by mousing to the top of the screen. Screenshot:
![screen shot 2016-01-06 at 11 37 46 am](https://cloud.githubusercontent.com/assets/236741/12149721/e004d5c6-b46a-11e5-8dbd-c26eb5238c67.png)

**Comment by zcbenz** [comment] 2016-01-07 06:35
This is weird, it seems to work fine on 10.11.2.

**Comment by bryankennedy** [comment] 2016-01-20 21:40
I am doing a bit more testing on this. If I write a set timeout I can get the true fullscreen kiosk mode working on 10.10.5.

In my main app.js file I use:

```
app.on('ready', function() {

mainWindow = new BrowserWindow({
  x: 0,
  y: 0,
  width: 800,
  height: 600,
});

/**
 * Hack to make fullscreen kiosk mode work.
 */
setTimeout(function() {
  mainWindow.setKiosk(true);
}, 100);
```

With that the app launches, goes fullscreen and then the OS X menu bar and Dock are completely inaccessible. But the exact same app does not work if I use the `kiosk: true` setting in the `BrowserWindow` call.

**Comment by zcbenz** [comment] 2016-07-12 06:23
After looking into this, I'm afraid this looks more like a bug of OS X 10.10 to me, and since kiosk mode works perfectly OS X 10.11, I'm closing this as won't fix.

**Closed by zcbenz** 2016-07-12 06:23 UTC
Labels: blocked, bug, osx

**Comment by stickywes** [comment] 2016-07-29 18:35
I initially had this issue when trying to deploy an electron app to a Mac Mini with 10.10.4 on it, but updated to 10.10.5 made the issue go away.
