### ISSUE TITLE
`defaultPath` option does not work in remote.dialog.showOptionDialog()

### ISSUE THREAD

**Issue by sonicdjgh** [electron/electron#24623] opened 2020-07-17 10:22 UTC
for example :

`const { remote } = window.require('electron');`
`let props = [];`
`const result = await remote.dialog.showOpenDialog(
            {
                defaultPath: path,
                properties: props,
                // filters: [
                //     { name: "All Files", extensions: ["*"] }
                // ]
            });`

well, but "defaultPath" did not work. any value... 

if i can't set a default path, I can only select a file from root path every time, that is a bad experience >.<

but JAVA Swing can do this... - =

So, please fix it.

By the way, my electron version is 9.1.0.  Windows platform.

Wish you best.

**Comment by ckerr** [comment] 2020-07-20 15:54
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Also, please note that this may be an issue with use of `remote` which, since it's deprecated and slated for removal, is unlikely to be prioritized. Further discussion on replacing `remote` calls can be found at https://github.com/electron/electron/issues/21408 and https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31#d978

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2020-09-01 03:29
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2020-09-01 03:29 UTC
Labels: 9-x-y, blocked/need-repro, platform/windows
