### ISSUE TITLE
One-way audio issue

### ISSUE THREAD

**Issue by xdurand** [electron/electron#8927] opened 2017-03-14 23:24 UTC
I’m working to implement a softphone solution in WebRTC.
Input devices are retrieved by calling the `navigator.mediaDevices.getUserMedia()` method.
After a while and for some reason, it seems that electron (chromium?) looses the input audio stream, causing *one way audio* calls: the user can hear the other part but the other part cannot hear the user.
All calls are happening in the same BrowserWindow object.

Does anyone already experienced this kind of issue and have found a workaround?
The only fix I found is to close and re-open the app.

* Electron version: 1.6.2 (but happened on previous versions as well)
* Operating system: macOS / Windows 7, 8, 8.1 & 10

### Expected behavior

Connection between an electron app and an audio stream should not be closed after a while.

### Actual behavior

Input audio stream seems to be closed by electron (chromium?) at some point.

### How to reproduce
Unfortunately, I can't manage to reproduce this issue and can't find any pattern to replicate it. Will update this issue if I can find something.

### Workaround

Here are some workarounds I'm thinking about:
- Prevent a user that the stream is lost and ask him to restart its app: appears to happen several times a day, so not a good user experience
- Launch each calls in a different Electron process: code is not designed to work like that at all. Not sure that this will actually solve the issue.

Do you guys have more idea to implement?

Thanks for your help!

**Comment by enlight** [comment] 2017-03-15 00:20
Are you able to reproduce this in Chrome 56?

**Comment by xdurand** [comment] 2017-03-15 00:24
Yes and you're right, it seams that the issue is more related to Chromium.
My app is running on Electron 1.6.2, so Chromium 56.

**Comment by xdurand** [comment] 2017-03-15 09:59
I know there's some issue pending on Chromium side, and don't know if those one are fixed with the v57 release: https://bugs.chromium.org/p/webrtc/issues/detail?id=4799

**Comment by zcbenz** [comment] 2017-06-14 11:02
Closing since it is an upstream Chromium issue.

**Closed by zcbenz** 2017-06-14 11:02 UTC
