### ISSUE TITLE
[Bug]: use app.commandLine.appendSwitch("js-flags", "--max-old-space-size=8192") not working! d

### ISSUE THREAD

**Issue by t-pk** [electron/electron#34305] opened 2022-05-21 10:27 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.3

### What operating system are you using?

Windows

### Operating System Version

windows 1909

### What arch are you using?

x64

### Expected Behavior

any method by which I can increase the memory.

### Actual Behavior

currently I use 
`app.commandLine.appendSwitch("js-flags", "--max-old-space-size=8192");`

pre-set ready,
but it still can't increase the memory.
is there any way i can increase the memory above 4GB?

**Comment by miniak** [comment] 2022-05-22 20:22
Duplicate of #31330

**Closed by miniak** 2022-05-22 20:22 UTC
Labels: bug :beetle:
