### ISSUE TITLE
Window maximize button disabled when using titleBarStyle: hidden in 12.0.0-beta11 and higher

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#27318] opened 2021-01-14 06:38 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 12.0.0-beta.11 and higher
  * 
* **Operating System:** macOS 10.15 and 11.0
  * 
* **Last Known Working Electron version:** 12.0.0-beta.10
  * 

Testcase:

```
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    },
    titleBarStyle: 'hidden'
  })
```

Working behavior (in beta 10 and lower):

<img width="368" alt="Screen Shot 2021-01-14 at 12 27 37 AM" src="https://user-images.githubusercontent.com/10314059/104553589-85d13080-5600-11eb-99ff-f347a26e3829.png">

Broken behavior (in beta 11):

<img width="572" alt="Screen Shot 2021-01-14 at 12 30 30 AM" src="https://user-images.githubusercontent.com/10314059/104553604-8f5a9880-5600-11eb-9652-41a437561a96.png">

#26960 looks related?

**Comment by jkleinsc** [comment] 2021-01-14 15:00
Closing as this is a duplicate of #27283.  If you have additional comments on this issue, please post them there.

**Closed by jkleinsc** 2021-01-14 15:00 UTC
