### ISSUE TITLE
webContents.print() doesn't respond when adding parameters

### ISSUE THREAD

**Issue by akito8261** [electron/electron#18858] opened 2019-06-18 09:56 UTC
### Issue Details

* **Electron Version:**
  * 5.0.4
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * None

### Expected Behavior
webContents.print(option, callback) can work with parameters.

### Actual Behavior
webContents.print() will work without parameters.
But it doesn't respond when adding parameters, no errors, and no callback. If the window is closed at this time, a "false" callback will be made.

`printPage.webContents.print() // may work`

`printPage.webContents.print({silent: true}, (e) => console.log(e)) // no respond`

I'm not sure if this is a BUG, and I still want to find a solution. Thank!!!

**Comment by popod** [comment] 2019-06-19 08:31
Just some more precisions. This bug affect 4.2.x too and as Tzott said in #17670:

> Actual Behavior
> 
> First call:
> No response, no callback, no results returned
>
> Call again:
> Callback returns error, console output: false

**Comment by mapleby** [comment] 2019-06-21 04:50
![image](https://user-images.githubusercontent.com/45815225/59898359-f747fd80-9422-11e9-9de0-90aa55b520d0.png)
The error results from setting this parameter

**Comment by codebytere** [comment] 2019-06-24 21:58
Duplicate of https://github.com/electron/electron/issues/18123.

**Closed by codebytere** 2019-06-24 21:58 UTC
Labels: 5-0-x, bug :beetle:, platform/windows
