### ISSUE TITLE
WebView Tag not working on Angular App.

### ISSUE THREAD

**Issue by aminubakori** [electron/electron#4972] opened 2016-03-31 19:07 UTC
Hello Everyone,
I'm having a really big challenge trying to get the webview tag to work on my app. The app is esentially written in AngularJS and at some point i need to render some external content via an iframe. But then i started having issues with loading websites like facebook, google etc. So i searched for a solution and got webview tag. When i use it in the first html page of my electron app discarding the whole angular, it seems to work, but as soon as i return it back to its location in the app, it stops working. I need urgent help on this please. 
Thanks

* Electron version: v0.35.6
* Operating system: Mac OS X 10.11

**Comment by kevinsawicki** [comment] 2016-03-31 22:52
What is the error you are seeing? Do you have a stack trace or some other error logs from the Console tab of the dev tools?

**Comment by aminubakori** [comment] 2016-03-31 22:57
Nothing is being displayed both on the console and the main screen. After trying to monitor its load process, it doesn't fire the onload event and from the network tab, nothing is being requested. I'm not sure what's going on currently.

**Comment by aminubakori** [comment] 2016-03-31 22:57
No errors are displayed everything seems fine.

**Comment by kevinsawicki** [comment] 2016-03-31 22:58
Do you have the dev tools enabled on the webview?

http://electron.atom.io/docs/v0.37.3/api/web-view-tag/#methods

**Comment by aminubakori** [comment] 2016-03-31 22:59
Yes I have tried that too.

**Comment by kevinsawicki** [comment] 2016-03-31 23:01
Can you include the source code that isn't working for you and also describe in more details what specifically is failing? Thanks

**Comment by aminubakori** [comment] 2016-03-31 23:05
It only worked when it's the first page that loads on electron.

**Comment by aminubakori** [comment] 2016-03-31 23:08
<script type=text/javascript">console.log("hello world");</script>
<webview src="https://www.google.com/" style="height: 300px; width: 400px; display: inline-block></webview>

**Comment by aminubakori** [comment] 2016-03-31 23:09
I'm using the exact example given in your link above.

**Comment by aminubakori** [comment] 2016-03-31 23:11
The only difference is that I'm loading the script inside an ng-view using ui router template from another file.

**Comment by aminubakori** [comment] 2016-04-01 19:43
`<div class="indicator"></div>
                    <webview id="foo" src="http://localhost:8888" style="width:640px; height:480px; display: inline-block;"></webview>

                    <script type="text/javascript">
                        console.log('yesssssss');
                        var webview = document.getElementById("foo");
                        var indicator = document.querySelector(".indicator");

                        console.log(Object.getPrototypeOf(webview));

                        webview.addEventListener("dom-ready", function(){
                          webview.openDevTools();
                        });
                      
                        var loadstart = function() {
                            console.log('loading');
                          indicator.innerText = "loading...";
                        }
                        var loadstop = function() {
                          indicator.innerText = "";
                        }
                        webview.addEventListener("loadstart", loadstart);
                        webview.addEventListener("loadstop", loadstop);
                    </script>`

**Comment by aminubakori** [comment] 2016-04-01 19:44
Sorry for the late response.

The Object.getPrototypeOf(webview) is returning a HTMLElement array in the console. I hope this helps.

**Comment by zcbenz** [comment] 2016-04-07 02:07
I suggest following existing guides on web that show how to use Angular in Electron:
https://www.google.com/search?q=electron+angular

I'm closing this since apparently other users are using Angular without problems, if you found any bug of Electron, please report back and provide a minimal app that can reproduce the problem, and I'll reopen.

**Closed by zcbenz** 2016-04-07 02:07 UTC
Labels: more-information-needed

**Comment by gabestev** [comment] 2017-02-23 09:53
Seems i got the issue too,

Its not about packaging angular into electron, but a <webview> which load url with angular app inside it. any clue about it?

**Comment by nightCapLounge** [comment] 2017-07-28 13:40
I realize this is closed, but for those of you who got here via Google-foo, I solved this issue by ensuring that a protocol existed in the src url.  
e.g. "http://www.google.com" instead of just "www.google.com"

**Comment by aminubakori** [comment] 2017-08-28 11:51
Issue still persists. Here is a more detailed explanation.  https://github.com/electron/electron/issues/10369
