### ISSUE TITLE
[Bug]: BrowserWindow object .on("restore", (e) => {}); Does not fire at all

### ISSUE THREAD

**Issue by XfaonAE** [electron/electron#30425] opened 2021-08-05 20:26 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.8

### What operating system are you using?

Windows

### Operating System Version

10.0.19042 Pro N

### What arch are you using?

x64

### Expected Behavior

When the following code is exectuted:
```ts
appWindow.on("restore", (event: any) => {
    console.log("AppWindow.restore");
});
```

This should output AppWindow.restore in the editor terminal after running the main file.

### Actual Behavior

When the following code is exectuted:
```ts
appWindow.on("restore", (event: any) => {
    console.log("AppWindow.restore");
});
```

Failed to do what is expected, but the same code and swapping restore for maximized seems to work, and all the other events

**Comment by pushkin-** [comment] 2021-08-05 21:00
not sure what you mean by "swapping restore for maximized", but are you just seeing [this issue](https://github.com/electron/electron/issues/28570)?

**Comment by XfaonAE** [comment] 2021-08-05 21:02
yes @pushkin- thats the issue im getting, seems like theres no answeres on that issue

**Comment by clavin** [comment] 2021-08-07 02:25
Thanks for taking the time to contribute!

I'm closing losing this as a duplicate of #28570. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by clavin** 2021-08-07 02:25 UTC
Labels: bug :beetle:
