### ISSUE TITLE
[Bug]: Typing in Devtools causes crashes (onerror handler is hit)

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#34350] opened 2022-05-25 16:17 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

18.3.0

### Expected Behavior

I should be able to type in the devtools without triggering the window's `onerror` handler.

### Actual Behavior

`onerror` is triggered with the error: "Possible side-effect in debug-evaluate"

### Testcase Gist URL

https://gist.github.com/54d5f29ef2094fe21e5ba6b2de4ca876

### Additional Information

1. start app
2. type something in devtools
3. observe the error popup

Here's the code I'm running:

main.js:
```
const {app, BrowserWindow} = require('electron')

async function createWindow () {
  const mainWindow = new BrowserWindow()
  await mainWindow.loadFile('index.html')
  mainWindow.webContents.openDevTools()
}

app.whenReady().then(() => {
  createWindow()
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

index.html:
```
<script src="./renderer.js"></script>
```

renderer.js:
```
window.onerror = (e, url, line, col, error) => {
  alert(error.message);
};
```

**Comment by codebytere** [comment] 2022-05-25 18:50
This was caused by https://chromium-review.googlesource.com/c/v8/v8/+/3557234/ and fixed in https://chromium-review.googlesource.com/c/v8/v8/+/3660253 - it'll be resolved when we roll Chromium to contain the fix.

**Comment by pushkin-** [comment] 2022-05-25 19:11
@codebytere  Cool thanks. Is that [this PR](https://github.com/electron/electron/pull/34349), or is there another one?

**Comment by pushkin-** [comment] 2022-05-26 15:47
FWIW, my browser is on 102.0.5005.63 and I can still repro the crash in the webapp (in Chrome vs in Electron), so I'm not sure if the fix is there yet

**Comment by aidar87** [comment] 2022-05-30 10:38
The same problem with 102.0.5005.63 Chrome version, should wait for the next release?

**Comment by codebytere** [comment] 2022-06-01 11:59
Yes - it'll be in https://github.com/electron/electron/pull/34403.

**Comment by pushkin-** [comment] 2022-06-01 15:02
huh, so Electron 19 is currently on 102. Do you know if Chromium is going to backport that fix, to 102, or will Electron 19 be forever broken?

**Comment by codebytere** [comment] 2022-06-01 15:04
@pushkin- 19 will get it too! it still get chromium updates and will for a while.

**Comment by pvshake** [comment] 2022-06-08 19:54
thanks for this topic

**Closed** 2022-07-13 07:33 UTC
Labels: bug :beetle:, platform/all, 19-x-y

**Comment by pushkin-** [comment] 2022-07-15 21:18
seems like 20.0.0-beta.9 has the fix

**Comment by danieldocki** [comment] 2022-07-28 02:11
it seems that in version 19.0.10 it is still broken

**Comment by deermichel** [comment] 2022-07-28 08:32
Can confirm 19 is still affected. cc @codebytere do you know whether there will be a backport 19 roll?

**Comment by remss** [comment] 2022-08-03 08:03
Electron 20.0.0 published yesterday is affected.

**Comment by pushkin-** [comment] 2022-08-03 18:03
@remss Are you sure? I can't repro with Electron 20

**Comment by remss** [comment] 2022-08-04 09:05
I double checked and typing "foo()" in the devtools console will trigger the onerror handler and an the alert() open the popup.
Windows 10 x64, Electron 20.0.1

Note that I reproduce the issue on Chrome 104.0.5112.81 and also on 106.0.5218.0 canary. So maybe we should stop tracking this issue here.

Here the test page for Chrome (open devtools, type "foo()" in the console and see that the onerror handler is hit)
```
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
</head>
<body>
    <p>TestMe</p>
    <script>
    window.onerror = function(e) { 
      console.log('error handler hit!!!!');
      debugger;
    }	
    </script>
</body>
</html>
```

**Comment by remss** [comment] 2022-08-04 11:49
https://chromium-review.googlesource.com/c/chromium/src/+/3560458/

> ensures that (caught) errors caused by DevTools injected scripts (via the Console prompt) still trigger the error handlers

I'm afraid that this is the new expected behavior of Chrome 😥

**Comment by pushkin-** [comment] 2022-08-04 13:33
@remss Oh, I think we're talking about different issues. You're saying that if you execute code in the devtools that causes an error (because `foo` isn't defined for example), the error handler gets triggered.

This issue was meant to track that typing any character into devtools (without hitting Enter) was triggering the `onerror` handler per character. That behavior was fixed in Electron 20.
