### ISSUE TITLE
Electron breaks windowing system hover/drop

### ISSUE THREAD

**Issue by paulshapiro** [electron/electron#8520] opened 2017-01-26 21:42 UTC
* Electron version: 1.5.0
* Operating system: MacOS 10.12.2

### Expected behavior

Lack of actual behavior!

### Actual behavior

It appears that when running Electron in my dev environment, working on this app (with dev tools open on a single window), occasionally Electron appears to cause the rest of the operating system to lose its ability to track or report where the mouse currently is to applications. The windowing sys also loses the ability to do drag-and-drops because the drop never registers. It goes away but only apparently after I restart.

This makes developing using Electron quite difficult at times, as you may imagine. Can't do stuff like cmd-tab switching w/cursor, etc. Hovering doesn't work in 99% of the system. Also can't easily implement dragging and dropping as I have to keep restarting.

### How to reproduce

Unfortunately I'm not sure exactly how to repro. This has been happening since way before I started fiddling with anything to do with drag-and-drop listeners. It /might/ be the dev tools? But for some reason it doesn't feel like it. Happy to provide any addtl info. Thanks a bunch.

**Comment by kevinsawicki** [comment] 2017-01-26 21:44
> Electron version: 1.5.0

Does this also happen using `1.4.15`?

**Comment by kevinsawicki** [comment] 2017-01-26 23:25
> This has been happening since way before I started fiddling with anything to do with drag-and-drop listeners.

Are you ever able to reproduce using just the default Electron app or are you always seeing this when developing/running your own app? Just trying to narrow down whether it could be something app-specific.

> It /might/ be the dev tools? But for some reason it doesn't feel like it. Happy to provide any addtl info. Thanks a bunch.

Any details on why you think it could be related to the dev tools? Are they usually open when you start seeing this happen?

**Comment by paulshapiro** [comment] 2017-01-26 23:28
Hey there,

> Are you ever able to reproduce this using just the default Electron app or are you always seeing this when developing/running your own app? Just trying to narrow down whether it could be something app-specific.

Definitely the thing to do but I've barely tested the built version of the app. Just been going like this: `NODE_ENV=development electron ./local_modules/main/main.electron.js`

> Any details on why you think it could be related to the dev tools? Are they usually open when you start seeing this happen?

Just wanted to make sure I mentioned it is all. I've had the dev tools open for almost the entire time I've been building the app so don't have much experience w/o it running.

**Comment by paulshapiro** [comment] 2017-02-13 16:47
You know, I think this might happen if I initiate a drag from apps like TextMate while I have the above command running.

**Comment by paulshapiro** [comment] 2017-02-15 22:56
Scratch that. No drag seems necessary.

**Comment by paulshapiro** [comment] 2017-03-16 16:19
Hi, bit of an update.

I switched away from TextMate, etc to control for variables. and found the bug still happens, and it appears to have happened when I had a text area / input focused while I was removing it from the DOM. It doesn't happen every time though so obvs hard to repro and pin it down. In fact, not sure if it's even the real cause. All I know so far is it keeps happening. :)

**Comment by zcbenz** [comment] 2017-06-06 02:12
While we would like to fix this, I'm afraid it is only happening on your machine and we have no idea of why it happened at all. I'm closing this since we are unable to fix it.

**Closed by zcbenz** 2017-06-06 02:12 UTC
Labels: triage/bug
