### ISSUE TITLE
[Bug]: webContents.executeJavaScript and webFrameMain.executeJavaScript are different when a Promise is returned

### ISSUE THREAD

**Issue by smartguy1196** [electron/electron#32756] opened 2022-02-05 00:46 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro version 21H1

### What arch are you using?

x64

### Expected Behavior

When running the following

```
const { app, BrowserWindow } = require( "electron" )

app.whenReady().then(()=>{

  let main = new BrowserWindow({
    "height" : 600,
    "width" : 800
  })

  main.loadURL( "https://...." )
  main.webContents.on( "did-finish-load", ()=>{

    let iframe = main.webContents.mainFrame.frames[ 0 ]
    let injection = "new Promise(( resolve )=>{ resolve('hello') })"
    let handler = ( result ) => { console.log( result ) }

    //this code does not evaluate the same:
    iframe.executeJavaScript( injection ).then( handler ) //returns "{}"
    main.webContents.executeJavaScript( injection ).then( handler ) ) //returns "hello"

  })

})

```

I would expect the following output:

```
hello
hello
```

### Actual Behavior

Instead, I get:

```
{}
hello
```

**Comment by smartguy1196** [comment] 2022-02-05 00:57
#32164 - possibly relevant issue

**Comment by codebytere** [comment] 2022-02-07 11:42
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by smartguy1196** [comment] 2022-02-08 18:26
[To future proof the gist, I added a comment for some clarity...](https://gist.github.com/t57ser/ce254e6e2e828949809bf872ed4168b6?permalink_comment_id=4058115#gistcomment-4058115)

**Closed** 2022-08-17 04:08 UTC
Labels: bug :beetle:, status/confirmed, has-repro-gist, 17-x-y
