### ISSUE TITLE
window.setSize: height is incorrect at custom DPI settings

### ISSUE THREAD

**Issue by sachetsharma1** [electron/electron#27742] opened 2021-02-16 17:47 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.1, 11.2.3
* **Operating System:**
  * win7, win 10
* **Last Known Working Electron version:**
  * None

### Expected Behavior
window.setSize should set the height according to input 

### Actual Behavior
Height is different upto +- 3 pixels

### To Reproduce
 - Open any window 
 - Change the height using window.setSize
 - Read the height using window.getSize

Below is the code and output of running the fiddle on my machine with 100% and 125% DPI scaling

```js
mainWindow.setSize(800, 750)
console.log(mainWindow.getSize())
```
#### 100% DPI
```sh
12:22:11 PMElectron v11.1.1 started.

**12:22:11 PM[ 800, 750 ]**
```

#### 125% DPI
```sh
12:23:11 PMElectron v11.1.1 started.

**12:23:12 PM[ 800, 751 ]**
```

**Comment by zcbenz** [comment] 2021-02-17 07:57
This is a duplicate of https://github.com/electron/electron/issues/27651.

**Closed by zcbenz** 2021-02-17 07:57 UTC
Labels: bug :beetle:, platform/windows
