### ISSUE TITLE
[Bug]: The title bar overlay is not updated to fit the settings of the window

### ISSUE THREAD

**Issue by 0xENDER** [electron/electron#32285] opened 2021-12-25 22:35 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 11 21H2

### What arch are you using?

x64

### Expected Behavior

If a window has the `maximizable` property set to `false`, the built-in title bar overlay should be updated and the maximise button should be disabled. And if a window has the `minimizable` property set to `false`, the built-in title bar overlay should be updated and the minimise button should be disabled.

### Actual Behavior

These buttons are still active on the windows that have these properties set to `false`.
![image](https://user-images.githubusercontent.com/72353925/147394733-edffab52-5fea-483d-a62a-840596810551.png)

Main Window (the first one):
maximizable -> true
minimizable -> true

Editor Window (the second one):
maximizable -> true
minimizable -> true

Custom Alert Window (the third one):
maximizable -> false
minimizable -> true

About Window (the fourth one):
maximizable -> false
minimizable -> false

**Comment by ahmadjubair33** [comment] 2021-12-28 17:12
can i contribute to this
?

**Comment by codebytere** [comment] 2022-01-03 10:39
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by limacheb** [comment] 2022-01-18 13:12
I'd very much appreciate a fix of this bug as well.  
I am adding a Gist URL here to reproduce the issue.  
I hope this is fine.  
https://gist.github.com/b678be9ee0717d20e946bfaef0f9b8d0

**Comment by limacheb** [comment] 2022-06-21 06:09
Still happening in Electron 19.
This makes the WCO unusable for us.
I would appreciate a statement from the electron team in respect to the timeline by when this could be fixed.  Otherwise planning is difficult.

@codebytere   
Any update?  
Any simple workaround? Unfortunately there is no event such as 'will-maximize' in order to cancel maximizing the window

**Comment by limacheb** [comment] 2022-06-21 06:25
Possible (ugly) workaround:  
```
  window.on('minimize', (event) => {
      setTimeout(() => window.restore(), 0)
  });
```

**Comment by codebytere** [comment] 2022-06-21 09:26
hey folks - got around to this, PR is up at #34677

**Closed** 2022-06-23 17:08 UTC
Labels: platform/windows, bug :beetle:, component/BrowserWindow, 16-x-y, component/wco

**Comment by limacheb** [comment] 2022-07-02 11:17
@codebytere
Thanks a lot! Works fine.

Still, I do see a related issue:   
- I start my window in maximzed state (calling method `maximize()` immediate after the `BrowserWindow` creation.
- The window gets maximized, the 'minimize' caption button is disabled => This is all fine.
- The 'unmaximize' button is enabled though => One could consider this button to be disabled as well, like the 'maximize' button is when the window is in 'unmaximize' state  

@codebytere What do you think?


```
function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    minimizable: false,
    maximizable: false,
    resizable: false,
    // closable: false,
    movable: false,
    titleBarStyle: 'hidden',
    titleBarOverlay: {
      color: '#ffffff'
    },
    frame: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })
  mainWindow.maximize()
```
