### ISSUE TITLE
3.0 regression: first webContents.debugger message is Inspector.targetReloadedAfterCrash

### ISSUE THREAD

**Issue by bughit** [electron/electron#14759] opened 2018-09-21 21:29 UTC
* Output of `node_modules/.bin/electron --version`: 3.0.0 x86
* Operating System (Platform and Version): win7 sp1 x64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.10

**Expected Behavior**
no Inspector.targetReloadedAfterCrash

**Actual behavior**
Inspector.targetReloadedAfterCrash, which indicates something is not quite right

**To Reproduce**
run the following
```js
'use strict';

const {app, BrowserWindow} = require('electron'),
      OFFSCREEN = true;

let win;

if (OFFSCREEN)
  app.disableHardwareAcceleration();

app.on('ready', () => {

  win = new BrowserWindow({
    width: 1440,
    height: 900,
    useContentSize: true,
    show: !OFFSCREEN,
    webPreferences: {
      nodeIntegration: false,
      partition: 'memory_partition_1',
      offscreen: OFFSCREEN
    },
  });

  if (OFFSCREEN) {
    //win.webContents.setFrameRate(1);
    //win.webContents.stopPainting();
  }

  win.webContents.on('did-start-navigation', (event, url, isInPlace, isMainFrame, frameProcessId, frameRoutingId) => {
    if (isMainFrame && !isInPlace)
      log('did-start-navigation: %s\n', url);
  });

  win.webContents.on('did-navigate', (event, url, httpResponseCode, httpStatusText) => {
    log('did-navigate: %i %s\n', httpResponseCode, url);
  });

  win.webContents.on('did-fail-load', (event, errorCode, errorDescription, validatedURL, isMainFrame, frameProcessId, frameRoutingId) => {
    if (isMainFrame)
      log('did-fail-load:\n%O\n', {errorCode, errorDescription, validatedURL});
  });

  win.webContents.on('did-finish-load', event => {
    log('did-finish-load: %s\n', win.webContents.getURL());
  });

  win.webContents.on('did-start-loading', event => {
    log('did-start-loading\n');
  });

  win.webContents.on('did-stop-loading', async event => {
    log('did-stop-loading: %s\n', win.webContents.getURL());
    setTimeout(async () => {
      // const navPerf   = await win.webContents.executeJavaScript('performance.getEntriesByType("navigation")[0].toJSON()'),
      //       paintPerf = await win.webContents.executeJavaScript('performance.getEntriesByName("first-contentful-paint")[0].toJSON()');
      // //log('navigation perf entry:\n %O\n', navPerf);
      // log('first-contentful-paint perf entry:\n %O\n', paintPerf);
      if (OFFSCREEN)
        exit();
    }, 1000);
  });

  const dev = win.webContents.debugger;
  dev.on('message', (event, method, params) => {
    log('devtools event %s:\n%O\n', method, params);
  });
  log('before debugger.attach()\n');
  dev.attach();
  log('after debugger.attach()\n');
  //dev.sendCommand('Network.enable');
  log('before Page.enable\n');
  dev.sendCommand('Page.enable');
  log('after Page.enable\n');
  if (!OFFSCREEN)
    win.webContents.openDevTools({mode: 'right'});

  log('before loadURL\n');
  win.loadURL('http://example.org/');
  log('after loadURL\n');

});


function exit() {
  log('exiting\n');
  app.exit();
}

function log(msg, ...args) {
  console.log(`[${new Date().toISOString()}] ${msg}`, ...args);
}
```

**Additional Information**

electron 2.0.10 output
```
[2018-09-21T21:13:15.913Z] before debugger.attach()

[2018-09-21T21:13:15.917Z] after debugger.attach()

[2018-09-21T21:13:15.919Z] before Page.enable

[2018-09-21T21:13:15.921Z] after Page.enable

[2018-09-21T21:13:15.925Z] before loadURL

[2018-09-21T21:13:15.941Z] did-start-loading

[2018-09-21T21:13:15.942Z] after loadURL

[2018-09-21T21:13:16.152Z] devtools event Page.frameStartedLoading:
```

electron 3.0.0 output
```
[2018-09-21T21:11:46.843Z] before debugger.attach()

[2018-09-21T21:11:46.846Z] after debugger.attach()

[2018-09-21T21:11:46.847Z] before Page.enable

[2018-09-21T21:11:46.848Z] after Page.enable

[2018-09-21T21:11:46.850Z] before loadURL

[2018-09-21T21:11:46.854Z] devtools event Inspector.targetReloadedAfterCrash:
{}

[2018-09-21T21:11:46.864Z] did-start-loading

[2018-09-21T21:11:46.866Z] did-start-navigation: http://example.org/

[2018-09-21T21:11:46.868Z] after loadURL

[2018-09-21T21:11:47.025Z] devtools event Page.frameStartedLoading:
```

**Comment by deepak1556** [comment] 2018-09-21 22:01
Thanks for the report, this is intentional, whenever there is a navigation in the default mode there will be a process swap which will cause the first load of the inspector connection to fail. The inspector will be connected again as soon as the process swaps complete and receives page lifecycle events as expected. Closing since its not a bug.

**Closed by deepak1556** 2018-09-21 22:01 UTC

**Comment by bughit** [comment] 2018-09-21 22:08
> there will be a process swap which will cause the first load of the inspector connection to fail

Would this not apply to 2.0? But 2.0 does not get this Inspector.targetReloadedAfterCrash event.

**Comment by deepak1556** [comment] 2018-09-21 22:10
> Would this not apply to 2.0? But 2.0 does not get this Inspector.targetReloadedAfterCrash event.

Nope it doesn't apply, the navigation architecture was changed with 3.x and above https://github.com/electron/electron/pull/12535

**Comment by bughit** [comment] 2018-09-21 22:20
> Nope it doesn't apply, the navigation architecture was changed with 3.x and above #12535

Just to be sure I understand this change, did it also introduce the renderer process swap which you mentioned is the cause? 

> there will be a process swap which will cause the first load of the inspector connection to fail

Or is it the process swap in combination with plznavigate that manifests this event?

**Comment by deepak1556** [comment] 2018-09-21 22:28
> Or is it the process swap in combination with plznavigate that manifests this event?

This is the reason, in plznavigate there are different stages in the navigation cycle, where the browser process decides which site instance should used once the navigation completes, in the default non-sandboxed mode we don't want same site instance from an existing navigation or a site instance thats already prepared by the browser process, so we provide our own and this causes the swap. Before plznavigte this request for site intsance will happen only when the navigation is about to commit, but now it happen before the request load and also before navigation commit.
