### ISSUE TITLE
use partition when create browserwindow, but can't loadUrl sessessful after build , this is loadUrl param (app.//index.html)

### ISSUE THREAD

**Issue by GavinZJM** [electron/electron#45095] opened 2024-12-25 12:29 UTC
use partition when create browserwindow, but can't loadUrl sessessful after build , this is loadUrl param (app.//index.html), wipe off code about partition, browserWindow show successfully
here is my code, please help!
        

> this.win = new BrowserWindow({
>                 width: 900,
>                 height: 650,
>                 title: 'robot',
>                 icon: process.env.WEBPACK_DEV_SERVER_URL ?  path.join('./public/', 'logo.png'): path.join(__dirname, './logo.png'),
>                 frame: false,
>                 resizable: false,
>                 movable: true,
>                 show: false,
>                 transparent: false,
>                 type: undefined,
>                 webPreferences: {
>                   devTools: true,
>                   // Use pluginOptions.nodeIntegration, leave this alone
>                   // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration for more info
>                   nodeIntegration: true,
>                   contextIsolation: false,
>                   webSecurity: false,
>                   preload:  path.join(__dirname, './preload.js'),
>                   partition: `persist:part${this.loginRes.merchantId}_${this.loginRes.userId}`
>                 }
>         })
> 
>       await this.win.loadURL(app.//index.html)

**Comment by nikwen** [comment] 2024-12-25 14:39
Can you try using a partition name that only contains alphanumeric characters? Not sure if underscores are supported. (Hyphens are supported if I remember correctly.)

Apart from that, it might have something to do with the `nodeIntegration`, `contextIsolation`, and `webSecurity` settings used in combination with `partition`.

Could you please do the following?

1. Create a reproduction in [Fiddle](https://www.electronjs.org/fiddle) so that maintainers can reproduce (and fix) your issue easily
2. Close this issue
3. Reopen the issue through [this link](https://github.com/electron/electron/issues/new?template=bug_report.yml) and fill in the issue template
4. Include the Fiddle gist link in the new issue

**Comment by VerteDinde** [comment] 2024-12-25 22:46
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.

**Closed by VerteDinde** 2024-12-25 22:46 UTC
