### ISSUE TITLE
Accelerators in menus are hard coded to US keyboard layout on macOS

### ISSUE THREAD

**Issue by alexdima** [electron/electron#26907] opened 2020-12-09 16:03 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

This is incredibly similar to #26888 , but IMHO it cannot be a 100% duplicate since according to the bisect the last known good version is `3.1.13` and the first known bad version is `4.0.0-beta.1.`, whereas the other one has a different timeline. Also, this one is on the mac, while the other one is on Windows.

* **Electron Version:**
  * `4.0.0-beta.1.` and above
* **Operating System:**
  * macOS 10.15.7
* **Last Known Working Electron version:**
  * `3.1.13`

### Expected Behavior
* When using a keyboard layout like `Spanish - ISO` on macOS, `Cmd+Shift+7` in an accelerator should be rendered as `Cmd+Shift+7` or as `Cmd+/`. Here is a screenshot of the Spanish - ISO keyboard layout. As you can see, `Shift+7` on the `Spanish - ISO` keyboard layout produces `/` and not `&` (like on the US keyboard layout):
![image](https://user-images.githubusercontent.com/5047891/101653127-4d599800-3a3f-11eb-9753-93a3c173f9b1.png)

### Actual Behavior
* Since Electron `4.x`, `Cmd+Shift+7` is always rendered as `Cmd+&` (or for a while as `Cmd+Shift+&`?)  which is only correct for keyboard layouts where `Shift+7` produces `&`, such as the US keyboard layout, but is incorrect and misleading for any other keyboard layout.

### To Reproduce
* Electron Fiddle that uses `cmd+shift+7` as an accelerator: https://gist.github.com/f9dd95b576133c293fe7ad9a5fccb154
* Switch the keyboard layout to `Spanish - ISO` on macOS

relevant code snippet:
```
  const template = [
    {
      label: 'Edit',
      submenu: [
        { label: 'Test', accelerator: 'Cmd+Shift+7' },
      ]
    }
  ]

  const menu = Menu.buildFromTemplate(template)
  Menu.setApplicationMenu(menu)
```

### Screenshots
* `3.1.13` (last known good version):
![image](https://user-images.githubusercontent.com/5047891/101653562-bb05c400-3a3f-11eb-93d4-ae27592911e7.png)
* `4.0.0-beta.1` (first bad version):
![image](https://user-images.githubusercontent.com/5047891/101653670-db358300-3a3f-11eb-82a1-63cd187508d9.png)
* `12.0.0-beta.7` (latest version):
![image](https://user-images.githubusercontent.com/5047891/101653799-04eeaa00-3a40-11eb-93df-773a46f73934.png)

### Additional Information

* As I mentioned, this is incredibly similar to https://github.com/electron/electron/issues/26888 but appears to have been introduced one version later in Electron

**Comment by ckerr** [comment] 2020-12-16 19:46
I believe this is the same issue as https://github.com/electron/electron/issues/26125, so I'm going to close this as a duplicate.

**Closed by ckerr** 2020-12-16 19:46 UTC

**Comment by alexdima** [comment] 2021-02-26 07:50
@ckerr FYI according to https://github.com/electron/electron/issues/19747#issuecomment-786353034 it looks like this issue is not a duplicate of #26125 and #19747 because #19747 "did not work in **3.1.13** and never has".

**Comment by clavin** [comment] 2021-02-26 18:16
I will add this issue, however, is possibly a duplicate of #21790, just with the added perspective of different keyboard layouts.
