### ISSUE TITLE
Multiple dev tool windows causes extensions to fail to load

### ISSUE THREAD

**Issue by pgeeh** [electron/electron#23383] opened 2020-05-01 22:59 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Creating two windows (either two visible, or one hidden and one visible) and opening dev tools on both windows causes extensions on the second window to fail (order does not matter). It appears that the dev tools extensions only load correctly in the first window. It seems that `chrome.devtools` is undefined in the second dev tool window.

Errors
* `[32006:0501/183746.550343:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'panels' of undefined", source: chrome-extension://redux-devtools/js/devtools.bundle.js (1)`
* `[32006:0501/183746.677275:ERROR:CONSOLE(40)] "Uncaught TypeError: Cannot read property 'inspectedWindow' of undefined", source: chrome-extension://react-developer-tools/build/main.js (40)`

Steps
* With two BrowserWindows open, open dev tools in the first
    * Note on the command line that no errors show and panels are available
* Open dev tools in the second window
    * Errors similar to the ones noted above should occur
* Close the dev tools in first and second windows
* Open dev tools in second window
    * Errors should not occur and panels are available
* Open dev tools in first window
    * Errors will occur again

Notes
* **Electron Version:**
  * 8.2.5
* **Operating System:**
  * CentOS Linux release 7.6.1810 (Core) x64 (VM)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Dev tool extensions should load in all dev tool windows.

### Actual Behavior
Dev tool extensions fail to load if another window already has dev tools opened.

### To Reproduce

Suggest running the two npm run commands in separate windows in order to see the errors from electron. Note: If you get the sandbox issue with electron, run `./addSuidElectron.sh`
```sh
$ git clone  https://github.com/pgeeh/electron-tool-bug -b master
$ npm install
$ npm run start
$ npm run electron
```

**Comment by dave3068** [comment] 2020-05-07 08:16
I have got the same problem.

I have 3 windows of my application (A, B, C). 
If open the A-window devTools at first, and continue to open devTools of others window, then the A-devTools is OK, but others got these ERROR.
If open B or C window devTools at first, and continue to open other devTools, then the first opened devTools is OK, others got ERROR.

**Comment by stevenroussey-privicy** [comment] 2020-05-30 18:50
Ah, this is it! Since Electron 8. I have windows open hidden with devtools open and ready for when i show them.

**Comment by anon353249** [comment] 2020-08-20 09:59
I am also experiencing this very same bug but on Windows 10 version 2004.
I came looking for this actually, it's a problem I've had for quite some time.
Please add the platform/windows label.

Details are exactly the same as mentioned in the opening comment.
I however have the 2nd BrowserWindow open via a button on the first BrowserWindow, but once I have both open, I can reproduce the bug as mentioned above following the same steps.

Electron Version:
8.5.0
Operating System:
Microsoft Windows 10 Version 2004 [OS Build 19041.450]
Last Known Working Electron version:
N/A

**Comment by janakg** [comment] 2020-09-04 02:16
yes same issue

**Comment by davitdaniel** [comment] 2020-09-27 04:00
yes same issue

**Comment by nornagon** [comment] 2020-09-28 19:30
Is this also happening on Electron 9?

**Comment by electron-triage** [comment] 2021-03-10 18:31
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Closed by electron-triage** 2021-03-10 18:31 UTC
Labels: 8-x-y, bug :beetle:, platform/linux
