### ISSUE TITLE
how to dealwith the warn

### ISSUE THREAD

**Issue by hainuo** [electron/electron#6727] opened 2016-08-04 10:38 UTC
* Electron version:1.3.2
* Operating system: mac osx 10.12

```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
IOVARendererID property not found
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
```

**Comment by zcbenz** [comment] 2016-08-04 13:09
According to the upstream Chromium it has been fixed in Chrome 53, so currently the only option is to wait for next stable release of Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=626534

**Closed by zcbenz** 2016-08-04 13:09 UTC

**Comment by RCasatta** [comment] 2016-12-02 09:48
This is caused by libevent, version 2.0.22 has been [patched](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libevent.rb#L11-L14)

if you have libevent 2.0.22 version you need to force uninstall and reinstall
`brew update`
`brew uninstall --ignore-dependencies libevent`
`berw install libevent`
