### ISSUE TITLE
Electron crashing with native module

### ISSUE THREAD

**Issue by carlskii** [electron/electron#5138] opened 2016-04-13 10:59 UTC
* Electron version:
0.37.5.
* Operating system:
OSX 10.11.4

I'm using the X509 (https://www.npmjs.com/package/x509)

I followed the instructions here https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md to but the module is still crashing electron. 
```
npm install --save-dev electron-rebuild

# Every time you run "npm install", run this
./node_modules/.bin/electron-rebuild

# On Windows if you have trouble, try:
.\node_modules\.bin\electron-rebuild.cmd
```

**Comment by zcbenz** [comment] 2016-04-14 05:15
This is a duplicate of #1410, and unfortunately we are not able to solve this because of Chromium using a fork of OpenSSL.

**Closed by zcbenz** 2016-04-14 05:15 UTC
