### ISSUE TITLE
[Bug]: webrtc / peerJS connection troubles

### ISSUE THREAD

**Issue by PxlLoewe** [electron/electron#29648] opened 2021-06-11 21:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2

### What arch are you using?

x64

### Expected Behavior

I want to create a voice chat with the electron framework. For testing pureposes I created the Simple-peer /webrtc voice-chat as a website. The connection between the Browser instances works.

### Actual Behavior

As soon as I start accessing the exact same website in Electron ( with `mainWindow.loadURL` or copy and pasting the code and adjusting some urls) It throws there errors: 

> [4712:0611/224806.608:ERROR:audio_rtp_receiver.cc(95)] AudioRtpReceiver::OnSetVolume: No audio channel exists.

> [4712:0611/224846.392:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.2.x:52325 ({653D86EF-2890-4553-8A92-A3CB302B2D3A})

Amazingly, the connection works when the Electron App gets the calls but now when Electron tries to call other peers.

### Testcase Gist URL

https://gist.github.com/PxlLoewe/7a2ff3a3577be27533cd12a6d87e8dde

**Comment by Prinzhorn** [comment] 2021-06-14 06:37
Possible duplicate of https://github.com/electron/electron/issues/9886 and https://github.com/electron/electron/issues/11112
I've searched the issue tracker for "No audio channel exists"

**Comment by PxlLoewe** [comment] 2021-06-14 11:39
I know these reports. But this one is more related to peerJS

**Comment by VerteDinde** [comment] 2021-06-16 03:39
Hey @PxlLoewe, thanks for reporting this issue! I took a look at your repro gist - do you happen to have a working Electron Fiddle example or a small repo that we could clone down to take a look? It looks like there are several dependencies that we'll need to get the .txt file code in the gist up and running, so having a working repo would go a long way into helping us debug this.

Thanks, appreciate your time! 🙂

**Comment by PxlLoewe** [comment] 2021-06-16 16:07
Hi @VerteDinde , thanks for investigating this! I have adaded you to my repository.

**Comment by nornagon** [comment] 2021-06-17 00:19
Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by PxlLoewe** [comment] 2021-06-20 17:47
I have created a gist with just the effected part of my app. I addad an additional comment on the bottom of renderer.js.

https://gist.github.com/4c0bf88dba44c407ac4914ef5d4d0fbf

Maybe this is connected to the console logs of the 'normal' electron project on the first bug report.

**Comment by nornagon** [comment] 2021-06-21 17:33
Duplicate of #23529

**Closed by nornagon** 2021-06-21 17:33 UTC
Labels: 13-x-y, blocked/need-info ❌, bug :beetle:, platform/windows
