### ISSUE TITLE
Documented code to load flash no longer works on Electron 5.x.x

### ISSUE THREAD

**Issue by coreybruce** [electron/electron#19093] opened 2019-07-03 02:51 UTC
-EDIT-
Duplicate issue.
https://github.com/electron/electron/issues/18824

### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
   Electron 5.0.6
* **Operating System:**
  * 
    Linux,Windows 
* **Last Known Working Electron version:**
  * 
   Electron 4.1.1
### Expected Behavior

  Load flash plugin
### Actual Behavior

  Unable to load plugin
### To Reproduce

 git clone https://gitlab.com/gamerworld/application
npm install electron@latest jquery
 npm start

than go to Plazma Burst 2 for example and you will see it is unable to load the flash plugin. Close it than do npm i electron@4.1.1 than npm start and do the same thing and you will see it works with older version of electron and breaks on the current version. 

### Screenshots

Electron 4.1.1
https://imgur.com/RMgZJ84.png

Electron 5.0.9:
https://imgur.com/w1LTrcL.png

**Comment by MarshallOfSound** [comment] 2019-07-03 22:05
Duplicate of #18824

**Closed by MarshallOfSound** 2019-07-03 22:05 UTC
