### ISSUE TITLE
Putting all release files in a subfolder except exe? 

### ISSUE THREAD

**Issue by kunkinkan** [electron/electron#5830] opened 2016-06-01 20:32 UTC
When electron has compiled a windows or linux app, there's a bunch of files created in the same directory as the exe. 

I'd like it if those files could be put in a subfolder, named "helpers" or whatever. That way it's easy for the user to find the exe without having to sort through a bunch of files. 

Is there an option to accomplish this? 

Thanks.

**Comment by paulcbetts** [comment] 2016-06-01 20:43
This isn't an option because of how DLL lookup on Windows works, sorry

**Comment by carlosperate** [comment] 2016-06-01 22:30
That's a shame, this is something I've been wondering for a long time as well :(

**Comment by wesleywesley** [comment] 2016-06-02 07:20
what about linux?

**Comment by wesleywesley** [comment] 2016-06-02 07:32
oh btw i suppose it could still be done if there was a second exe which only purpose is to launch the real exe in the subfolder :-)

**Comment by miniak** [comment] 2016-06-02 10:13
Actually it should be possible using SXS manifest

**Comment by miniak** [comment] 2016-06-02 11:01
Chrome does that

**Comment by zcbenz** [comment] 2016-06-03 04:30
One possible solution is to separate the entry function from the actual implementation, i.e. splitting `electron.exe` into `electron.exe` and `somedir/electron.dll`. But it would make the architecture of Electron more complicated, and I don't think we should do that.

If you just want to make it easier to find the executable, you can simply put the app into a folder write a batch script to execute it.

**Comment by carlosperate** [comment] 2016-06-03 08:30
> If you just want to make it easier to find the executable, you can simply put the app into a folder write a batch script to execute it. 

That's the way I currently have it, but it's quite "scary" for inexperience users to be running batch files.

**Comment by miniak** [comment] 2016-08-31 09:15
It's related to this issue https://github.com/Squirrel/Squirrel.Windows/issues/798

**Comment by miniak** [comment] 2016-08-31 09:20
@zcbenz How complicated would it be to split electron.exe into `electron.exe` and `electron.dll`?
We are hitting the same problem with the firewall prompt, which is caused by the EXE path changing every time the application updates. If `electron.exe` and `electron.dll` were separate files, and all the resources and data files were resolved relative to `electron.dll`, we would be able to optionally put all the files into a subdirectory (redirecting the DLLs using an SXS manifest, like Chrome does it). That would allow us to update the app while running, putting the new version side-by-side with the old one. The running `electron.exe` can be renamed to `electron.exe.old` and the new one placed instead.

**Comment by miniak** [comment] 2016-08-31 09:22
The nice thing about this is that existing applications wouldn't be broken in any way, as placing all the other files into a subdirectory would be optional.

**Comment by zcbenz** [comment] 2016-09-13 05:36
@miniak Separating `electron.exe` and `electron.dll` wouldn't be very hard, we are already doing a very similar thing on Mac where the app is spliced into main app/helper app/electron framework.

And I agree doing this would be very helpful for auto-updating on Windows, and I'm reopening this issue for discussion.

**Comment by paulcbetts** [comment] 2016-09-13 19:19
> That would allow us to update the app while running, putting the new version side-by-side with the old one. The running electron.exe can be renamed to electron.exe.old and the new version put into the same folder with electron.exe name (again, exactly what Chrome is doing)

I don't think that this is possible, if an executable is running you definitely can't rename it. This also means that auto-updaters are now in the game of special-casing Electron (or at the very least, writing special code to copy electron.exe up a folder). 

While I agree that it would solve a bunch of small annoying cases on Windows (and believe me, I have been annoyed by these cases), I think it'd also be much more likely to cause failed installations because of the added complexity. Squirrel.Windows is already literally as dumb as I can _possibly_ make it, and it's still prone to failure (and every failure == a person stranded)

**Comment by miniak** [comment] 2016-09-13 21:11
> I don't think that this is possible, if an executable is running you definitely can't rename it.
Have you tried? It's possible.

**Comment by miniak** [comment] 2016-09-13 21:14
@paulcbetts I am also not saying, that Squirrel.Windows has to special case Electron. There are other installers/updaters that can be used for Electron apps.

**Comment by miniak** [comment] 2016-09-13 21:14
> I'm certainly willing to hear proposals on what we could do though, and the electron.exe/dll split wouldn't affect anyone in the short term

That's the point. If you have a custom installer, it allows you to do the update the way Chrome does it.

**Comment by miniak** [comment] 2016-09-13 21:18
@paulcbetts Our main problem is that the path to the executable is changing every time there is an update. This is triggering a firewall prompt for our app.

**Comment by codebytere** [comment] 2018-01-30 02:03
Given that this issue has not seen action in a long time and there is no clear path forward for implementing this, i'm going to go ahead and close it.

**Closed by codebytere** 2018-01-30 02:03 UTC
Labels: discussion, platform/windows
