### ISSUE TITLE
Customize Electron/Chromium cache location

### ISSUE THREAD

**Issue by emmkimme** [electron/electron#18309] opened 2019-05-15 14:40 UTC
### Problem Description
I would like to customize the location of the Electron/Chromium cache (for Windows and other OS/s). Currently cache used the same folder than getPath('userData')
2 reasons :
- having cache in the roaming user part impacts the size of the profile. When your deploy your application on system like Citrix, it has a huge cost ($) in term of space disk and cost (time) to synchronize profile.
- we store our own user data under getPath('userData'). But this folder is shared with the Electron cache, so there is a mix of Electron folders/files and of our product folders/file. It is bit confusing.

### Proposed Solution
I see in C++ code an attempt of 'cache'/ 'userCache' path implementation. But not finished. As far as I see, it would be to add a piece of code here (very roughly) :

src\electron\atom\browser\atom_browser_context.cc
`
AtomBrowserContext::AtomBrowserContext
...
>> if (!base::PathService::Get(DIR_CACHE, &path_)) {
    if (!base::PathService::Get(DIR_USER_DATA, &path_)) {
      base::PathService::Get(DIR_APP_DATA, &path_);
      path_ = path_.Append(base::FilePath::FromUTF8Unsafe(GetApplicationName()));
      base::PathService::Override(DIR_USER_DATA, path_);
    }
  }
`

### Alternatives Considered
We customized setPath('userData') at startup of our application to force the cache to another location but later in the code, we can no more use getPath('userData') for storing our data. We expose a new method but it is less friendly and error prone.

### Additional Information
I have not the background /context of the 1st attempt, it may have a good reason to stop. If you can share your concerns and see if it is feasible, will be grateful

I can manage a MR, if you agree.

**Comment by nornagon** [comment] 2021-06-23 23:49
Duplicate of #1404

**Closed by nornagon** 2021-06-23 23:49 UTC
Labels: enhancement :sparkles:
