### ISSUE TITLE
Beta 3.0.0 Window titleBar Controls are invisible on 'hidden' or 'hiddenInset' on Mac

### ISSUE THREAD

**Issue by setpixel** [electron/electron#14129] opened 2018-08-16 12:25 UTC
* Electron Version: v3.0.0-beta.5
* Operating System (Platform and Version): Mac 10.12.6 (16G1510)
* Last known working Electron version: v2

**Expected Behavior**
Window controls should be visible.

**Actual behavior**
They are invisible. HOWEVER, they are clickable, if you click in the right spot.

**To Reproduce**

```
  mainWindow = new BrowserWindow({
    acceptFirstMouse: true,
    backgroundColor: '#333333',

    width: Math.min(width, 2480),
    height: Math.min(height, 1350),

    title: path.basename(filename),

    minWidth: 1024,
    minHeight: 640,
    show: false,
    resizable: true,
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      webgl: true,
      experimentalFeatures: true,
      experimentalCanvasFeatures: true,
      devTools: true,
      plugins: true
    } 
  })

```

**Comment by codebytere** [comment] 2018-08-16 22:18
Closing as duplicate of https://github.com/electron/electron/issues/12726

**Closed by codebytere** 2018-08-16 22:18 UTC
Labels: bug :beetle:, platform/macOS, version/3.0.x

**Comment by setpixel** [comment] 2018-08-17 01:39
I don't have a crash though. So I don't know if it's really a duplicate but
yeah, I'm sure you guys know. Thanks!

**Comment by KagamiChan** [comment] 2018-08-20 08:29
@codebytere The issue you referenced is about the combination of `titlebarStyle` and vibrancy, But this issue here only uses `titlebarStyle`.

I figure that the window control works fine with 2.0.7 + `titlebarStyle: hidden`, but it disappears with 3.0.0-nightly 20180818. So it seems to me these 2 issues are somewhat different

**Comment by KagamiChan** [comment] 2018-08-20 08:30
And if we click on the enlarge button (green one) and restore the window again, these 3 buttons will show up

**Comment by setpixel** [comment] 2018-08-20 08:48
yes @codebytere i don't know if it's exactly the same source of the problem, but the symptoms are different.

**Comment by KagamiChan** [comment] 2018-09-03 12:42
update: this issue only happens on macOS sierra (10.12) and it'll be OK on high sierra (10.13)

Since more and more users will upgrade their OS, I'm going to simply disable titlebarStyle on sierra
