### ISSUE TITLE
Coding from https format

### ISSUE THREAD

**Issue by rastajamz** [electron/electron#13998] opened 2018-08-09 10:23 UTC
* Electron version:
* Operating system:

* Last known working Electron version:

**Comment by rastajamz** [comment] 2018-08-09 10:39
view-source:chrome://browser/content/aboutLogins.js

**Comment by ckerr** [comment] 2018-08-09 14:30
I'm going to close this issue due to lack of information -- I literally can't tell what this issue is about.

Please file a new issue _and follow the issue template_ that prompts you to describe the issue, the Electron version, platform, expected results, and actual results. For reproducible issues, what would be ideal is if you could create a fork of `electron/electron-quick-start` that reproduces the issue.

**Closed by ckerr** 2018-08-09 14:30 UTC
