### ISSUE TITLE
Possible bug in webview

### ISSUE THREAD

**Issue by leo-combes** [electron/electron#8361] opened 2017-01-07 15:37 UTC
I'm trying to use a webview to navigate between some streaming pages like tunein, soundcloud, youtube, etc.
The webview works correctly loading pages, but if in some of them I play a streaming content (music or video) and later change the url to another page, only a blank page is displayed.

How to reproduce it:
- clone hokein/electron-sample-apps
- run the webview sample with electron electron-sample-apps/webview/browser/
- load the url http://tunein.com (everything will work fine)
- load the url https://soundcloud.com/ (everything will work fine)
- load the url http://tunein.com, search for a radio station (you can type "BBC" in the search field for some suggestion) and play it. This should also work.
- change the url again to https://soundcloud.com/. You will now see an empty page.

**Comment by deepak1556** [comment] 2017-01-07 17:36
I am unable to reproduce with webview in default app. Can you provide a minimal example to reproduce the issue ?

**Comment by leo-combes** [comment] 2017-01-08 15:52
Yes, you can use the same code that I was use. Just clone https://github.com/hokein/electron-sample-apps and run the webview/browser example.
I used that code to reproduce the issue.

**Comment by deepak1556** [comment] 2017-01-26 10:11
> ust clone https://github.com/hokein/electron-sample-apps and run the webview/browser example.
I used that code to reproduce the issue.

Sorry for the delayed response, I tried the steps with default app and it worked fine. Were you able to reproduce the issue with the default app ?

**Comment by kevinsawicki** [comment] 2017-03-31 23:50
Closing this out until more information is available.

**Closed by kevinsawicki** 2017-03-31 23:50 UTC
Labels: more-information-needed
