### ISSUE TITLE
Can node worker_thread work in the background thread ?

### ISSUE THREAD

**Issue by DaniGTA** [electron/electron#19376] opened 2019-07-23 06:47 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta.13
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
-

### Expected Behavior
Use the worker in the background thread.

### Actual Behavior
Webpack generated this 2 files:
```
  dist_electron\index.js          2235.09 KiB           503.87 KiB
  dist_electron\test.worker.js    0.01 KiB              0.03 KiB
```
It compiled successfully.

I use node 12.6.0 so i have worker_threads and vscode detect it fine.

BUT when i launch electron i get this:

```
App threw an error during load
ReferenceError: Worker is not defined
    at new ./node_modules/worker-loader/dist/cjs.js!./src/test.worker.ts.module.exports (c:\Users\myname\Desktop\my-project\dist_electron\index.js:56406:3)
    at Module../src/background.ts (c:\Users\myname\Desktop\my-project\dist_electron\index.js:60661:16)
    at __webpack_require__ (c:\Users\myname\Desktop\my-project\dist_electron\index.js:20:30)
    at Object.0 (c:\Users\myname\Desktop\my-project\dist_electron\index.js:60752:18)
    at __webpack_require__ (c:\Users\myname\Desktop\my-project\dist_electron\index.js:20:30)
    at c:\Users\myname\Desktop\my-project\dist_electron\index.js:84:18
    at Object.<anonymous> (c:\Users\myname\Desktop\my-project\dist_electron\index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
```

### To Reproduce
`npm install -g @vue/cli`

`vue create vue_app`

`cd vue_app`
`vue add electron-builder`

In `background.ts` i add this:

```
import workerPath from "file-loader?name=[name].js!./test.worker";
import { Worker } from 'worker_threads';

const worker = new Worker(workerPath);
```

The file-loader module looks like this:

```
declare module "file-loader?name=[name].js!*" {
    const value: string;
    export = value;
}
```

The test.worker file is empty for the test.

The last step is: `npm run serve:electron`

### TS Config:
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "mocha",
      "node",
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "es6",
      "es7",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ]
}
```

**Comment by walmat** [comment] 2019-07-29 03:01
Electron is shipped with its own version of NodeJS, so your local version doesn't factor in here. Also, I know a couple of other issues that are related to NodeJS worker_threads lib, so I'm going to link them here as related.

Related #18540 #17030

**Comment by codebytere** [comment] 2019-10-03 08:38
Closing as duplicate of https://github.com/electron/electron/issues/18540

**Closed by codebytere** 2019-10-03 08:38 UTC
Labels: 6-0-x, platform/windows
