### ISSUE TITLE
[Bug]: hidden/hiddenInset title bar shows again with tabs

### ISSUE THREAD

**Issue by paulnewell-signifyd** [electron/electron#34414] opened 2022-06-01 22:25 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.1

### What operating system are you using?

macOS

### Operating System Version

macOS 12.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

With no tabs and with more than one tab the title bar should not show when "hidden" or "hiddenInset" is set during build
![Slice 1](https://user-images.githubusercontent.com/105880492/171511769-5b44c822-e206-4977-8e2d-1d510653844c.png)

### Actual Behavior

**Title bar does not show with a window with no/single tab...**

<img width="826" alt="Screen Shot 2022-06-01 at 6 15 05 PM" src="https://user-images.githubusercontent.com/105880492/171510833-6412947f-93bf-4882-ab71-c200f2185883.png">

**But if there is a second (or more) tab added then the title bar shows...**
<img width="837" alt="Screen Shot 2022-06-01 at 6 15 13 PM" src="https://user-images.githubusercontent.com/105880492/171510891-7f5bc3d7-a1e6-4153-8c97-425940d5f9d3.png">

### Additional Information

nativefier --name 'docs.google.com' --user-agent firefox --title-bar-style hiddenInset

**Comment by codebytere** [comment] 2022-06-02 08:38
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-06-14 15:53
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-06-14 15:53 UTC
Labels: platform/macOS, bug :beetle:, blocked/need-repro, 18-x-y
