### ISSUE TITLE
Developer Tools - Accessibility tab is not functional 

### ISSUE THREAD

**Issue by kolaps33** [electron/electron#18716] opened 2019-06-10 17:57 UTC
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
    4.0.0. ,  5.0.0
* **Operating System:**
  Windows 10 (1803) 
* **Last Known Working Electron version:**
I did not find any working version

Repro steps:
- open developer tools 
- go to Elements tab
- select any html element
- open Accessibility tab

### Expected Behavior
- accessibility tab show accessibility tree 

### Actual Behavior
- accesisbility tab is empty
Error in console:
`[99978:0610/175341.131749:ERROR:CONSOLE(24)] "Empty response arrived for script 'devtools://devtools/remote/serve_file/@f200986dfaabd6aad6a4b37dad7aae42fec349e9/accessibility/accessibility_module.js'", source: devtools://devtools/bundled/shell.js (24)
[99978:0610/175341.140809:ERROR:CONSOLE(109)] "Uncaught (in promise) Error: Could not instantiate: Accessibility.AccessibilitySidebarView", source: devtools://devtools/bundled/shell.js (109)`

### Screenshots
Screenshot took from Electron Fiddle:

![image](https://user-images.githubusercontent.com/22620150/59215318-425b4880-8bb9-11e9-98bd-c002db5d3cd9.png)

**Comment by codebytere** [comment] 2019-06-10 21:43
Duplicate of https://github.com/electron/electron/issues/13008

**Closed by codebytere** 2019-06-10 21:43 UTC
