### ISSUE TITLE
Inconsistent reporting of offline storage quota

### ISSUE THREAD

**Issue by mann-david** [electron/electron#16029] opened 2018-12-12 02:53 UTC
**Expected Behavior**
According to all documentation I can find, including Issue #4550, Electron should have 1/3 of free space available for offline storage.  In addition, our apps should only be able to use 20% of that, per https://developer.chrome.com/apps/offline_storage#table.  

**Actual behavior**
I run the following code inside my Electron app:
```
const estimation = await navigator.storage.estimate();
console.log(`Quota: ${estimation.quota}`);
console.log(`Usage: ${estimation.usage}`);
``` 
and it reports that I actually have 100% of my free disk space available (i.e my 200GB drive has 105 GB free, and the code reports 105 GB available for use).  I've tried this on multiple machines with 3 different Electron apps and it is consistent.  

If it matters, I'm specifically interested in IndexedDb.

**To Reproduce**
Run the above code inside any Electron app (either in the app or just in the console inside the renderer process).  Compare the results to the actual free space on your drive.

**Additional Information**
Primarily, I'm just looking for a clarification on whether what I'm seeing in the code is correct, that we have 100% of free disk space, or whether the documentation is correct and the code incorrect.  Secondarily, I'd like to know if Electron will ever evict my data (specifically IndexedDb).

Thanks.

**Comment by kodezen** [comment] 2019-01-04 02:42
Interested in the answer to this as well

**Comment by mann-david** [comment] 2019-02-28 02:02
Tested again in Electron 4.0.5 with the same results.  Is there any official word?

**Comment by jacobq** [comment] 2019-10-30 22:41
I wonder if this has anything to do with the disabling of the DOM storage quota checks in [`dom_storage_limits.patch`](https://github.com/electron/electron/blob/master/patches/chromium/dom_storage_limits.patch).
(https://github.com/electron/electron/issues/13465)

**Comment by jacobq** [comment] 2019-11-01 04:07
According to https://github.com/electron/electron/issues/9498#issuecomment-302142276 it sounds like there is "unlimited and durable storage for all origins", which seems like it would agree with the "100% available" result you mentioned.

**Comment by mann-david** [comment] 2019-11-01 12:56
@jacobq: agree, but it would be nice to see this officially documented somewhere.  I can't base my app on this assumption and then have data loss because something got evicted.

**Comment by elrDevelopment** [comment] 2019-11-26 17:30
Has anyone found the documentation for the limits yet?

**Comment by lvkins** [comment] 2019-11-26 22:02
@elrDevelopment 

https://en.wikipedia.org/wiki/Web_storage

**Comment by jacobq** [comment] 2019-11-26 22:50
> However, Electron has a patch for dom storage limits: https://github.com/electron/electron/blob/master/patches/chromium/dom_storage_limits.patch

@elrDevelopment I believe that's only for `localStorage` and `sessionStorage` (and in current electron 9 nightlies the limit for those is 100MiB), not `IndexedDB`. So far I have not seen it officially documented, but I believe there is no limit for storage in `IndexedDB`

**Comment by elrDevelopment** [comment] 2019-11-26 22:51
I believe that to be the case as well. But cant find anything in the DOCS about it.

**Comment by lvkins** [comment] 2019-11-27 01:27
This is implementatio-specific I believe. The docs regarding storage rules can be found here: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Storage_limits so the actual limit can range up to 2GB

**Comment by mann-david** [comment] 2019-11-27 02:03
@lvkins: Thanks, but the contents on the mozilla site and wikipedia are pretty generic, and not really what this issue is about.  The original question is specifically about IndexedDb.  The code shown above contradicts everything I can find documented regarding IndexedDb limits and data eviction for Chrome.  I'm specifically trying to determine what the situation is for Electron which does not appear to be documented anywhere.

I've tested again in Electron 7.1.2 and still see the same results: available storage quota is the total free space on the drive, minus any space already used for persistent storage.

**Comment by lvkins** [comment] 2019-11-27 02:19
@mann-david Indeed, those links I posted are mostly directed to the @elrDevelopment that asked for the docs.

Regarding this issue, that I'm subscribing for few months out of curiosity, A good idea might be to test chromium behavior on that, because there seem to be no regulations in electron regarding this.

If you will be able to reproduce same behavior on standalone chromium build and you are determined enough, you can dig into the chromium IndexedDb implementation. [There is a documentation](https://www.chromium.org/developers/design-documents/indexeddb) available if you're interested. Quite outdated, but might be a good starting point for digging.

**Comment by elrDevelopment** [comment] 2019-11-27 03:48
> @lvkins: Thanks, but the contents on the mozilla site and wikipedia are pretty generic, and not really what this issue is about. The original question is specifically about IndexedDb. The code shown above contradicts everything I can find documented regarding IndexedDb limits and data eviction for Chrome. I'm specifically trying to determine what the situation is for Electron which does not appear to be documented anywhere.
> 
> I've tested again in Electron 7.1.2 and still see the same results: available storage quota is the total free space on the drive, minus any space already used for persistent storage.

@mann-david not sure why this is so hard for a person from the electron team couldn't answer this.

**Comment by jacobq** [comment] 2020-01-27 20:05
@zcbenz @deepak1556 Would you mind taking a moment to help clear this up? There seem to be some apparently contradictory claims here: 

1. Limit is same as Chromium (Is that still 1/3? A quick test in my browser tells me probably not.)
    https://github.com/electron/electron/issues/4550#issuecomment-186795099
    https://github.com/electron/electron/issues/21558#issuecomment-566689499
2. Unlimited 
    https://github.com/electron/electron/issues/9498#issuecomment-302142276

* Does electron change the way that Chromium applies these quotas? (I know there's a patch for DOM storage, but I didn't see anything obviously related to `IndexedDB`)
* If not, is there anything being done to normalize this across versions or does each version just stand on its own?

**Comment by mann-david** [comment] 2020-01-27 22:41
I've given up on IndexedDB simply because I couldn't get an answer on this and couldn't risk my product on it changing.

**Comment by zcbenz** [comment] 2020-01-28 01:55
It seems that the storage quota in Electron is unlimited:
https://github.com/electron/electron/blob/master/shell/browser/special_storage_policy.cc#L20-L22

I think we can provide an API to let users set the storage quota themselves.

**Comment by zcbenz** [comment] 2020-01-28 03:05
I'm looking into how Chromium calculates the storage quota, it seems that their algorithm is:
`min(TotalDiskSpace * 0.8, FreeDiskSpace)`, so for most people all free disk space would be returned.

I have also tested with Chrome 79 and it returned all free disk space as storage quota.

**Comment by zcbenz** [comment] 2020-01-28 03:07
This behavior seems to be intended:
https://bugs.chromium.org/p/chromium/issues/detail?id=897276

**Comment by ccorcos** [comment] 2020-10-29 18:47
I did some testing myself and it appears that indexeddb quota is pretty high, if not unlimited as stated.

https://github.com/ccorcos/electron-indexeddb-quota

**Comment by zcbenz** [comment] 2020-12-10 07:34
I'm closing this issue since Electron's behavior aligns with Chromium.

**Closed by zcbenz** 2020-12-10 07:34 UTC
Labels: bug :beetle:
