### ISSUE TITLE
error when html page with <img src="//test.com/123.jpg">

### ISSUE THREAD

**Issue by fishbar** [electron/electron#1747] opened 2015-05-21 15:54 UTC
some webpage omit the `http` prefix to minify the page, like `http://taobao.com`
electron now can not recognize this kind of url, and will log error like this:

```
[22608:0521/234915:INFO:CONSOLE(0)] "Not allowed to load local resource: file://g.alicdn.com/kg/offline/3.0.1/index-min.js?t=20131121234724.js", source: http://www.taobao.com/ (0)
```

**Comment by frankhale** [comment] 2015-05-21 16:05
Related issue: https://github.com/atom/electron/issues/1139

We need some way to instruct Electron that if it finds a protocol relative URL it should probably assume at least http first.

**Comment by frankhale** [comment] 2015-06-08 01:14
Reference issue: https://github.com/atom/electron/issues/1895

**Comment by frozeman** [comment] 2016-01-23 11:30
To add my issue here too:

It should not assume at least HTTP, it should assume the current protocol where its loaded from. Which can also be a custom protocol! See #4145

**Comment by frozeman** [comment] 2016-01-25 15:53
@zcbenz any timeframe when this will be fixed? It currently makes custom protocols unusable, as you can't load any proper website with it.

**Comment by zcbenz** [comment] 2016-01-26 03:02
@frozeman The fix should be very simple, but it would require a long time debugging to find out, the debugging might take hours, days, and even weeks, I can never give estimate on fixing a non-crash bug like this, so I have to put resources on more important issues.

**Comment by frozeman** [comment] 2016-01-26 10:42
@zcbenz i can create a reproduction repo if that helps.

**Comment by frozeman** [comment] 2016-01-26 13:45
I was trying to create a repo and it seems to load now the files, even from relative paths (though sometimes not). While doing multiple reloads i experienced a crash. Please see the log https://gist.github.com/frozeman/c3ba0ee4b04d8ddb25c2

Looks like a memory leak somewhere in the custom protocol code.

**Comment by retrohacker** [comment] 2016-03-03 08:54
I've encountered this as well. Here is a simple reproduction:

```js
var electron = require('electron')
var app = electron.app

app.on('ready', function(e) {
  electron.protocol.registerFileProtocol(
    'peer',
    function(req,cb) {
      console.log(req)
      var file_path = __dirname+'/'+req.url.substring('peer://'.length)
      console.log(file_path)
      cb({path: file_path})
    },
    function registeredProtocol(e) {
      var mainWindow = new electron.BrowserWindow()
      mainWindow.loadURL('peer://index.html')
    })
})
```

The above simply returns the file requested from the project directory. I.E. `peer://index.html` will return `index.html` from the project's directory.

```html
<html>
  <head>
  </head>
  <body>
    <img src='./test.png'>
  </body>
</html>
```

The desired behaviour would be to interpret this as `peer://test.png` but, instead, this appears to do nothing. 

This behaviour breaks serving webpages over custom protocols.

**Comment by retrohacker** [comment] 2016-03-15 03:54
I created a set of tests which demonstrate the problem: https://github.com/retrohacker/electron/blob/protocol_request/spec/api-protocol-spec.js#L108

I'm having trouble finding the code in electron relevant to this. It looks like all parsing is delegated to blink; it seems strange that there is an edge case like this.

**Comment by retrohacker** [comment] 2016-03-15 03:55
In those tests, the first 2 fail and the last passes.

**Comment by retrohacker** [comment] 2016-03-19 16:29
While trying to find context for debugging, I came across the original PR by @zcbenz.

It is beautiful code!

From the comments, it looks like this behaviour was intentional (or, at least, this was the only behaviour desired at the time for atom)

https://github.com/atom/electron/pull/65#issuecomment-23270312

**Comment by zcbenz** [comment] 2016-04-21 07:39
While looking for a solution for this bug, I just realized it can not be reproduced in 0.37.x anymore. It seems upgrading to Chrome 49 has fixed this.

**Closed by zcbenz** 2016-04-21 07:39 UTC
Labels: bug, help-wanted

**Comment by retrohacker** [comment] 2016-04-24 15:31
This doesn't appear to be fixed @zcbenz 

The tests on the master branch, release branch, and the 0.37.6 tag fail with the following errors:

![screenshot1](https://cloud.githubusercontent.com/assets/1081565/14768427/e6e58f5c-0a0f-11e6-9ada-966ae0cac370.png)

**Comment by retrohacker** [comment] 2016-04-24 15:35
I just added a test for protocol relative urls, these are failing as well.

**Comment by zcbenz** [comment] 2016-04-25 08:52
@retrohacker It is actually a different bug from this one, can you open a new issue for it?

**Comment by flyingcong** [comment] 2016-09-12 03:32
I tried to open url "https://i.taobao.com", and got the error:"seed-min.js:70 GET file:///D:/tools/develop/nodejs/node_modules/.electron_npminstall/node_modu…s,anim/base-min.js,promise-min.js,anim/timer-min.js,anim/transition-min.js net::ERR_FILE_NOT_FOUND"

**Comment by mim-Armand** [comment] 2017-06-17 17:28
In case you are here with the same problem using `Webpack 2.x`, `React` and/or `Redux`, there is a chance that this would solve your problem:
> Search your project directory for "publicPath" and change its value from `/` to `./`
> with all the different available boilerplates this setting may be found in different locations, In my case using `redux-cli` which uses `redux-starter-kit`, it was in the `project.config.js`:
``` javascript
publicPath: './',
```
Also if you are building for `Electron` you may need to add/modify the Webpack `target` property.
Stay Happy!! 😄

**Comment by itsaakashpatel** [comment] 2018-07-09 06:15
It's because of your all files are being served from the local file system rather than the relative app path.
The solution is to intercept the file protocol. Do following changes in main.js file
### Main.js
`mainWindow = new BrowserWindow({width: 1100, height: 700, icon: __dirname + '/icon.ico'})
  mainWindow.loadURL(url.format({
   pathname:'index.html',
   protocol: 'file',
   slashes: true
 }))`

`app.on('ready', () => {
  protocol.interceptFileProtocol('file', (request, callback) => {
   const url = request.url.substr(7)    /* all urls start with 'file://' */
   callback({ path: path.normalize(`${__dirname}/${url}`)})
 }, (err) => {
   if (err) console.error('Failed to register protocol')
 })
 createWindow() /* callback function */
})`
