### ISSUE TITLE
Closing windows created by nativeWindowOpen=true and sandbox=true or nodeIntegrationInSubFrames will freeze the creator window.

### ISSUE THREAD

**Issue by markleutloff** [electron/electron#20377] opened 2019-09-30 13:35 UTC
### Issue Details

* **Electron Version:**
 greater equal 6.0.0
 greater equal 7.0.0-beta.1

* **Operating System:**
Windows 10 17763 x64

* **Last Known Working Electron version:**
lesser equal 5.0.11
lesser equal 6.0.0-beta.12

### Expected Behavior
Closing the created window should not let the creator window freeze.

### Actual Behavior
The creator window freezes.

### To Reproduce
1. Create a window (this is the creator window) with following webPreferences set:

> preload: some preload file which at least requires the electron remote module
> nativeWindowOpen: true
> sandbox: true (can be false when nodeIntegrationInSubFrames is true)
> nodeIntegrationInSubFrames: true (can be false when sandbox is true)

_When at least one of sandbox or nodeIntegrationInSubFrames is set to true the problem occours._

2. Load a website which opens a new window on a click (I used https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open3).

3. Open a new window by clicking a link which should open a new window.
4. Close the new window.
5. Try to select some text in the creator window, when the problem occours any interaction should not be possible.

**Comment by kirilpopov** [comment] 2019-10-01 13:08
Seems related to https://github.com/electron/electron/issues/20086 and https://github.com/electron/electron/issues/20350

**Comment by miniak** [comment] 2019-11-05 13:44
Duplicate of #20086

**Closed by miniak** 2019-11-05 13:44 UTC
