### ISSUE TITLE
npm install electron failure

### ISSUE THREAD

**Issue by azmuth94** [electron/electron#7394] opened 2016-09-28 19:40 UTC
* Electron version: 1.4.1
* Operating system: Linux 4.4.11-v7+

![image](https://cloud.githubusercontent.com/assets/8680993/18929251/bb65db54-8591-11e6-8790-4c49a90cd4a5.png)

**Comment by amitkumarj441** [comment] 2016-09-28 21:18
@azmuth94 Can you tell me on which Linux distro you're installing electron!

**Comment by kevinsawicki** [comment] 2016-09-28 22:45
@azmuth94 what is your system time? is it accurate?

That looks to be the cause of the "certificate is not yet valid" errors.

http://stackoverflow.com/questions/23668148/npm-issue-cert-not-yet-valid-on-raspberry-pi

https://github.com/npm/npm/issues/10861

Closing this out.

**Closed by kevinsawicki** 2016-09-28 22:45 UTC

**Comment by enlight** [comment] 2016-09-29 01:47
Duplicate of #7386.
