### ISSUE TITLE
[Bug]: CPU-related tests often flake in linux-x64-testing-node

### ISSUE THREAD

**Issue by VerteDinde** [electron/electron#34575] opened 2022-06-15 04:44 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

main

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu Linux / other Linux distros

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

 linux-x64-testing-node should not hit CPU test flakes

### Actual Behavior

Different cpu-related tests often flake when running linux-x64-testing-node jobs. An example run is here: https://app.circleci.com/pipelines/github/electron/electron/54580/workflows/bf840e76-a70d-4b5f-b640-7df2ed186b79/jobs/1246990

These flaky tests are a bit of a heisenbug - they seem to consistently pass both when run locally on Ubuntu 20.04 and when run from SSH within CircleCI itself.

**Comment by codebytere** [comment] 2022-07-15 08:29
Duplicate of https://github.com/electron/electron/issues/34472

**Closed by codebytere** 2022-07-15 08:29 UTC
Labels: bug :beetle:, component/node-integration, ci-flake ⭕️, upgrade-follow-up
