### ISSUE TITLE
Electron reports 'bad option', dev-tools won't open

### ISSUE THREAD

**Issue by leegee** [electron/electron#18412] opened 2019-05-23 00:24 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 v5.0.1
* **Operating System:**
Windows 10, 1803
* **Last Known Working Electron version:**
N/A

When starting electron I sometimes get the following output on the console, and find that dev-tools will not open -- otherwise my appears to function normally.

Sorry this is vague - everything has been fine up to now. Does this make any sense?

```
X\node_modules\electron\dist\electron.exe: bad option: --type=gpu-process
X\node_modules\electron\dist\electron.exe: bad option: --disable-features=SpareRendererForSitePerProcess
X\node_modules\electron\dist\electron.exe: bad option: --disable-gpu-sandbox
X\node_modules\electron\dist\electron.exe: bad option: --use-gl=disabled
X\node_modules\electron\dist\electron.exe: bad option: --gpu-preferences=KAAAAAAAAACAAwAAAQAAAAAAAAAAAGAAAAAAAAEAAAAIAAAAAAAAACgAAAAEAAAAIAAAAAAAAAAoAAAAAAAAADAAAAAAAAAAOAAAAAAAAAAQAAAAAAAAAAAAAAAFAAAAEAAAAAAAAAAAAAAABgAAABAAAAAAAAAAAQAAAAUAAAAQAAAAAAAAAAEAAAAGAAAA
X\node_modules\electron\dist\electron.exe: bad option: --service-request-channel-token=9078526690365816071
X\node_modules\electron\dist\electron.exe: bad option: --mojo-platform-channel-handle=2708
```

**Comment by samvv** [comment] 2019-07-04 19:01
I'm having a similar issue. Not sure if it is the same but I'll post it here before opening a separate issue. Any luck pinning down where it came from @leegee?

Here's my terminal output (paths trimmed for brevity):


```
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --type=renderer
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-logging
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --disable-features=SpareRendererForSitePerProcess
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --service-pipe-token=18402242350250830864
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --lang=en-GB
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --app-path=/Users/samvv/Projects/lightning/lib
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --node-integration
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-sandbox
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-zygote
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --background-color=#fff
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --num-raster-threads=4
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-zero-copy
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-gpu-memory-buffer-compositor-resources
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-main-frame-before-activation
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --service-request-channel-token=18402242350250830864
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --renderer-client-id=4
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-v8-untrusted-code-mitigations
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --type=renderer
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-logging
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --disable-features=SpareRendererForSitePerProcess
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --service-pipe-token=5723814129953772926
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --lang=en-GB
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --app-path=/Users/samvv/Projects/lightning/lib
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-sandbox
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-zygote
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --num-raster-threads=4
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-zero-copy
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-gpu-memory-buffer-compositor-resources
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-main-frame-before-activation
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --service-request-channel-token=5723814129953772926
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --renderer-client-id=6
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-v8-untrusted-code-mitigations
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --type=renderer
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-logging
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --disable-features=SpareRendererForSitePerProcess
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --service-pipe-token=17435414548445152172
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --lang=en-GB
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --app-path=/Users/samvv/Projects/lightning/lib
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-sandbox
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-zygote
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --num-raster-threads=4
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-zero-copy
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-gpu-memory-buffer-compositor-resources
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-main-frame-before-activation
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --service-request-channel-token=17435414548445152172
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --renderer-client-id=6
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-v8-untrusted-code-mitigations
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --type=renderer
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-logging
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --disable-features=SpareRendererForSitePerProcess
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --service-pipe-token=11340355404196682303
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --lang=en-GB
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --app-path=/Users/samvv/Projects/lightning/lib
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --node-integration
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-sandbox
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-zygote
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --background-color=#fff
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --num-raster-threads=4
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-zero-copy
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-gpu-memory-buffer-compositor-resources
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --enable-main-frame-before-activation
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --service-request-channel-token=11340355404196682303
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --renderer-client-id=4
./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper: bad option: --no-v8-untrusted-code-mitigations
```

**Comment by leegee** [comment] 2019-07-04 19:07
It just comes and goes. Had no noticable impact, but may be indicative of
deeper issues?

**Comment by samvv** [comment] 2019-07-04 19:14
Strangest thing about this is that it has **no** impact whatsoever on the rest of the application. Ah well, maybe someone else can make sense of it. 🤷‍♂

**Comment by stevebaxter** [comment] 2019-08-13 12:50
Are you using any sort of child processes, e.g. through `worker-farm`? I'm having a very similar problem when I switched from `jest-worker` to `worker-farm`.

**Comment by leegee** [comment] 2019-08-13 18:13
Yes!  I was using a child process spawned from Node!

**Comment by samvv** [comment] 2019-08-13 18:17
Hmm strange my comment didn't get through. I was also spawning something through `child_process`, and I'm pretty sure that that caused the issue. As to the 'why', still no idea.

**Comment by stevebaxter** [comment] 2019-08-13 18:32
So I've spent all day looking at this. The only difference I could see between what `jest-worker` was doing and what `worker-farm` is doing is that `jest-worker` set an environment variable for each forked process along the lines of `JEST_WORKER_ID=xxx`. If I set this in the `worker-farm` processes, hey presto it all works again. 

It looks like something in Electron is special-casing for Jest, though I haven't found out exactly what though. I'd like to get to the bottom of this before letting this hack in to our code!

**Comment by stevebaxter** [comment] 2019-08-13 19:56
OK, I have now got to the bottom of what is happening, I think this is a bug in Electron, specifically the modified version of Node that Electron uses.

For child processes to work correctly, they must have `ELECTRON_RUN_AS_NODE=1` set as an environment variable. There is some code here that tries to ensure this is done for forked processes:

https://github.com/electron/node/commit/f263751ced67b2fcc9710b886c4f73838089e76d

The problem comes when the caller of `child_process.fork()` does something like this:

```
child_process.fork("myscript.js", [], { env: process.env });
```

Here we are directly passing in process.env (the environment of the current process) as an option to fork(). This seems to be a pretty common thing to do.

The problem is that this is the original process.env, not a copy. When this line tries to set ELECTRON_RUN_AS_NODE to 1, it in fact gets set to "1": 

https://github.com/electron/node/commit/f263751ced67b2fcc9710b886c4f73838089e76d#diff-1dea15b19e826b37828eef6c41166ffeR57

This prevents ELECTRON_RUN_AS_NODE from doing its thing, and stuff all gets subtly broken.

The solution is to either not pass in the environment as an option, or pass a copy, e.g.:

```
child_process.fork("myscript.js", [], { env: { ...process.env } });
```

I'll raise a bug for this in the electron/node repo.

**Comment by stevebaxter** [comment] 2019-08-13 22:27
Actually what I said above isn't quite right. It's a bit worse than that, updated bug with a fiddle to reproduce the problem:

https://github.com/electron/electron/issues/19738

**Comment by codebytere** [comment] 2019-08-14 03:33
Closing in favor of https://github.com/electron/electron/issues/19738!

**Closed by codebytere** 2019-08-14 03:33 UTC

**Comment by leegee** [comment] 2019-08-14 10:45
I saw the error described in this now-closed ticket only every few runs, each run being identical.
