### ISSUE TITLE
Remove Border Radius From Frameless Window On Mac

### ISSUE THREAD

**Issue by Subash** [electron/electron#414] opened 2014-06-20 05:25 UTC
Fameless window on mac contains border radius on both top and bottom, is there any option to remove that ?
![prepros_app](https://cloud.githubusercontent.com/assets/3478693/3336788/4a182816-f83b-11e3-82ad-e15a6ed3467c.png)

**Comment by zcbenz** [comment] 2015-01-01 00:09
The problem is it is actually quite hard to remove the bottom rounded corners, there is an upstream bug tracked at:
https://code.google.com/p/chromium/issues/detail?id=355412

**Comment by captbaritone** [comment] 2015-04-23 21:21
Looking to use Electron to build an OSx version of https://github.com/captbaritone/winamp2-js, but I would need to be able to turn off rounded corners for it to look good.

Seems like it might not be a solvable problem, but I wanted to add another example where non-rounded corners might be useful.

**Comment by Cheapskate01** [comment] 2015-10-13 13:00
I'm actually having the exact opposite problem. I would like the corners to round on windows and linux. Can anybody help me out?

**Comment by mikaa123** [comment] 2015-12-06 07:55
A hack that I used to remove the rounded border was to make the window transparent, then use a css `clip-path` property.

**Comment by KevCJones** [comment] 2016-04-20 15:39
A bit of a bump but wondering if anyone found a non-hack way of doing this?

**Comment by gabrielstuff** [comment] 2016-05-14 19:48
@mikaa123 how do you handle the click through the transparent window ? A real life example of border radius issue is when you want to display content on a video projector or a LED screen or any other projector.
Real life example, you want a frameless window in 500x500 and you have 10 of them.
You think you will simply start a script to place each window side by side and let the app start.
Well, no you can't, you are forced to put all of your app in one application and manage your tiled window inside one app. This sucks : /

**Comment by mikaa123** [comment] 2016-05-14 22:27
@gabrielstuff I don't it's possible to let a click go through a window, even if it's transparent

**Comment by ivmelo** [comment] 2017-01-26 21:26
Is there a way to remove only the top rounded corners? I am building a tray app and it kinda looks off with the top rounded corners.

**Comment by brockb** [comment] 2017-01-28 01:09
I really need square corners as well. I'm doing screen capture of a video in a chromeless window, let's say placed at X=0, Y=0, and the screen capture is picking up those rounded corners. I need to be able to capture every pixel of the video (including the missing pixels in the corners). There has to be a way to make it where border radius can be set. I really need a radius of zero.

**Comment by MondoGao** [comment] 2017-10-21 13:14
Leave the corners away!
You can get a radius-less window-like window by:
```javascript
  win = new BrowserWindow({
    frame: false, 
    transparent: true,
  });
```
```css
html {
  width:  /* less then window's size */;
  height: /* the same */;
  background: /* some color here */;
}
```

It's a little hack though. But it works well~

**Comment by labina26** [comment] 2017-12-28 01:23
So, is it impossible to remove the border radius corners on mac? I found this https://apple.stackexchange.com/questions/50280/how-can-i-disable-rounded-window-corners-in-os-x but I don't think it would work, just tried that.

**Comment by codebytere** [comment] 2018-09-23 17:03
Given that there exist workarounds, this is something that isn't on our current roadmap and which I am thus goin to tag as `wontfix`.

**Comment by andrienko** [comment] 2019-02-08 15:56
Sadly, these "workarkounds" do not work for me on High Sierra. Kinda shame.

**Comment by gcxfd** [comment] 2020-08-24 10:33
![image](https://user-images.githubusercontent.com/69608605/91034807-2d40cd00-e638-11ea-847e-8d75bc369285.png)

titleBarStyle: 'customButtonsOnHover' and frame: false

**Comment by zcbenz** [comment] 2020-12-12 03:46
I'm reopening this issue since there is an easy way to do that on newer versions of macOS.

**Comment by greggsdavis** [comment] 2021-01-05 02:20
@zcbenz What is the easier way to remove rounded corners in newer versions of macOS?

**Comment by zcbenz** [comment] 2021-01-05 02:26
Applying `NSFullSizeContentViewWindowMask` style on the window can remove the rounded corners, and I'm adding a new option for it.

**Closed** 2021-02-09 16:38 UTC
Labels: enhancement :sparkles:, good first issue, platform/macOS
