### ISSUE TITLE
desktopCapturer.getSources() with 'screen' type causes crash. (v3.0.0)

### ISSUE THREAD

**Issue by Jay-Rad** [electron/electron#14772] opened 2018-09-23 01:27 UTC
* Output of `node_modules/.bin/electron --version`:  v3.0.0
* Operating System (Platform and Version): Windows 10 v1803
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.8

**Expected Behavior**
Get 'screen' sources by calling desktopCapturer.getSources({types: ['screen']}, (error, sources) => {...}).

**Actual behavior**
Electron crashes.

**To Reproduce**
In the dev console of any Electron app using v3.0.0:
require("electron").desktopCapturer.getSources({types: ['screen']}, (error, sources) => {})

**Additional Information**
This was working fine before updating from v2.0.8 to v3.0.0.  After updating, trying to get screen sources crashes immediately.  I was able to reproduce this with the quick start app using v3.0.0.

I tried unplugging my external monitor to see if that made a difference, but it didn't.

**Comment by MarshallOfSound** [comment] 2018-09-23 01:39
@Jay-Rad Can you post the stack trace from the crash?  If one isn't appearing in your command line just set `ELECTRON_ENABLE_STACK_DUMPING=true` and `ELECTRON_ENABLE_LOGGING=true` as environment variables.

**Comment by Jay-Rad** [comment] 2018-09-23 01:51
@MarshallOfSound  Of course.  Here ya go:

[18164:0922/184953.104:VERBOSE1:CONSOLE(7847)] "Main._lateInitialization: 1.02001953125ms", source: chrome-devtools://devtools/bundled/shell.js (7847)
[18164:0922/184955.912:WARNING:dxgi_adapter_duplicator.cc(108)] Cannot initialize any DxgiOutputDuplicator instance.
[18164:0922/184955.912:WARNING:dxgi_duplicator_controller.cc(259)] Failed to initialize DxgiAdapterDuplicator on adapter 1
[18164:0922/184955.913:WARNING:dxgi_adapter_duplicator.cc(108)] Cannot initialize any DxgiOutputDuplicator instance.
[18164:0922/184955.913:WARNING:dxgi_duplicator_controller.cc(259)] Failed to initialize DxgiAdapterDuplicator on adapter 2
[18164:0922/184955.926:WARNING:dxgi_duplicator_controller.cc(82)] Count of references reaches zero, DxgiDuplicatorController will be unloaded.
[18164:0922/184955.970:WARNING:dxgi_output_duplicator.cc(106)] Failed to duplicate output from IDXGIOutput1, error 000002A887D6F0E0, with code -2005270524
[18164:0922/184955.970:WARNING:dxgi_adapter_duplicator.cc(85)] Failed to initialize DxgiOutputDuplicator on output 0
[18164:0922/184955.972:WARNING:dxgi_output_duplicator.cc(106)] Failed to duplicate output from IDXGIOutput1, error 000002A887D6F0E0, with code -2005270524
[18164:0922/184955.978:WARNING:dxgi_adapter_duplicator.cc(85)] Failed to initialize DxgiOutputDuplicator on output 1
[18164:0922/184955.980:WARNING:dxgi_adapter_duplicator.cc(108)] Cannot initialize any DxgiOutputDuplicator instance.
[18164:0922/184955.982:WARNING:dxgi_duplicator_controller.cc(259)] Failed to initialize DxgiAdapterDuplicator on adapter 0
[18164:0922/184955.983:WARNING:dxgi_adapter_duplicator.cc(108)] Cannot initialize any DxgiOutputDuplicator instance.
[18164:0922/184955.984:WARNING:dxgi_duplicator_controller.cc(259)] Failed to initialize DxgiAdapterDuplicator on adapter 1
[18164:0922/184955.985:WARNING:dxgi_adapter_duplicator.cc(108)] Cannot initialize any DxgiOutputDuplicator instance.
[18164:0922/184955.986:WARNING:dxgi_duplicator_controller.cc(259)] Failed to initialize DxgiAdapterDuplicator on adapter 2
[18164:0922/184955.988:WARNING:dxgi_duplicator_controller.cc(281)] Cannot initialize any DxgiAdapterDuplicator instance.
[18164:0922/184956.000:WARNING:dxgi_duplicator_controller.cc(82)] Count of references reaches zero, DxgiDuplicatorController will be unloaded.
[18164:0922/184956.155:WARNING:dxgi_output_duplicator.cc(106)] Failed to duplicate output from IDXGIOutput1, error 000002A887D6DC40, with code -2005270524
[18164:0922/184956.156:WARNING:dxgi_adapter_duplicator.cc(85)] Failed to initialize DxgiOutputDuplicator on output 0
[18164:0922/184956.158:WARNING:dxgi_output_duplicator.cc(106)] Failed to duplicate output from IDXGIOutput1, error 000002A887D6EF80, with code -2005270524
[18164:0922/184956.159:WARNING:dxgi_adapter_duplicator.cc(85)] Failed to initialize DxgiOutputDuplicator on output 1
[18164:0922/184956.160:WARNING:dxgi_adapter_duplicator.cc(108)] Cannot initialize any DxgiOutputDuplicator instance.
[18164:0922/184956.161:WARNING:dxgi_duplicator_controller.cc(259)] Failed to initialize DxgiAdapterDuplicator on adapter 0
[18164:0922/184956.162:WARNING:dxgi_adapter_duplicator.cc(108)] Cannot initialize any DxgiOutputDuplicator instance.
[18164:0922/184956.163:WARNING:dxgi_duplicator_controller.cc(259)] Failed to initialize DxgiAdapterDuplicator on adapter 1
[18164:0922/184956.164:WARNING:dxgi_adapter_duplicator.cc(108)] Cannot initialize any DxgiOutputDuplicator instance.
[18164:0922/184956.165:WARNING:dxgi_duplicator_controller.cc(259)] Failed to initialize DxgiAdapterDuplicator on adapter 2
[18164:0922/184956.166:WARNING:dxgi_duplicator_controller.cc(281)] Cannot initialize any DxgiAdapterDuplicator instance.
[18164:0922/184956.179:WARNING:dxgi_duplicator_controller.cc(82)] Count of references reaches zero, DxgiDuplicatorController will be unloaded.
Received fatal exception EXCEPTION_ACCESS_VIOLATION
Backtrace:
        (No symbol) [0x00007FF628C3B279]
        (No symbol) [0x00007FF628D47945]
        (No symbol) [0x00007FF628D77B7F]
        (No symbol) [0x00007FF628D771E9]
        (No symbol) [0x00007FF628D718A6]
        (No symbol) [0x00007FF628D7D5B6]
        BaseThreadInitThunk [0x00007FFF48873034+20]
        RtlUserThreadStart [0x00007FFF4B3B1461+33]

**Comment by Jay-Rad** [comment] 2018-09-23 01:56
Missed the last line...

[15684:0922/185406.855:ERROR:broker_win.cc(134)] Error sending sync broker message: The pipe is being closed. (0xE8)

**Comment by ajmacd** [comment] 2018-11-01 18:12
Sorry, forgot about this! I'll take a look at it next week.

**Comment by exKAZUu** [comment] 2018-11-14 05:57
@ajmacd (cc @felixrieseberg @MarshallOfSound)

We are facing the same issue now. `ignore-gpu-blacklist` doesn't affect on this issue.
We CAN reproduce this issue on the following Windows PC
```
- Electron: 3.0.9
- OS: Windows 10 Home (10.0.17134)
- CPU: Intel Core i5 7200U
- Video: Intel HD Graphics 620
```
but, CANNOT reproduce it on Mac PCs and the following Windows PC
```
- Electron: 3.0.9
- OS: Windows 10 Pro (10.0.17134)
- CPU: Intel Core i7 7500U
- Video: Intel HD Graphics 620
```

**Comment by ajmacd** [comment] 2018-11-15 00:30
I'm having some difficulty seeing how this could happen by inspection, and without an in-house repro case, I can't debug.

@Jay-Rad @embirico @exKAZUu, grasping at straws, but would you mind checking if you're able to screen share in Chrome on the affected machines using a WebRTC-based service like Hangouts?

It would also be helpful to get as much information about your machines as possible (like what @exKAZUu shared) to try to narrow down a repro case. Thanks!

**Comment by Jay-Rad** [comment] 2018-11-15 03:30
@ajmacd Hangouts is working in Chrome 70.0.3538.102 on my affected machine.

It's also working using my Electron screen sharing app, but only with Electron v2.0.x.  The portable binaries can be downloaded here:  https://my.doxm.app/Clients.  Then you can control the computer here:  https://my.doxm.app/RemoteControl

I recently open-sourced the project I'm working on.  Here's the code where it's crashing, in WarmUpRTC function:  https://github.com/Jay-Rad/DoXM/blob/master/DoXM_Remote_Control/Services/RCClient.ts 

Affected Machine:
- Windows 10 Pro (Build 17134.345)
- Intel Core i7-6700HQ
- Dual Video Adapters: Intel HD Graphics 530 and NVidia GeForce GTX 960M

Just a hunch with no basis at all...  Could the dual video adapters have something to do with it?

**Comment by Jay-Rad** [comment] 2018-11-15 21:57
@ajmacd I got this working.  For me, it was an issue with the NVIDIA drivers.

Following my previous hunch, I was going to force every application to use the dedicated GPU.  You can do this in Control Panel - NVIDIA Control Panel.  When I tried to open it, though, I got an error saying, "NVIDIA Display settings are not available.  You are not currently using a display attached to an NVIDIA GPU."

I wasn't having any issues with the GPU in any other applications, though.  So yeah, weird.

I installed the latest drivers from NVIDIA, and now everything's fine.

@exKAZUu @embirico Do you also have dual display adapters?  Are you able to open the NVIDIA Control Panel (if they're NVIDIA cards)?  Does installing the latest drivers have any effect?

**Comment by ajmacd** [comment] 2019-01-21 23:56
@exKAZUu can you confirm that a driver update fixed the crash you were seeing as well? We've seen a crash with some screen sharing Slack users in the wild now, and I'm wondering if a driver update is a general solution to this.

**Comment by exKAZUu** [comment] 2019-01-22 00:10
@Jay-Rad Thank you for sharing the solution!
@ajmacd Unfortunately, I’m now unable to use the PC where this issue occured. I’ve asked a peer and he said he would test it day after tomorrow. I will share the result here.

**Comment by exKAZUu** [comment] 2019-01-30 05:37
@ajmacd Hmm, my peer confirmed there was no error now (he could not reproduce the bug) though he doesn't remember whether he upgraded the NVIDIA drivers or not.

**Comment by ryan-codingintrigue** [comment] 2019-01-31 14:04
Just to chime in here, we are also seeing this issue in the wild.

One of our users is seeing this crash:

> [12588:0123/105838.902:WARNING:dxgi_duplicator_controller.cc(49)] Count of references reaches zero, DxgiDuplicatorController will be unloaded.

Our user is also using the aforementioned graphics card:

**Intel(R) UHD Graphics 620**

Updating their graphics drivers does not seem to help.

I don't know if it's related or not, but the issue seems to occur more frequently if they have Adobe Reader opened 😕

**Comment by rhwu** [comment] 2019-03-27 05:04
We are seeing this issue as well on a laptop with windows 10,  Intel® HD Graphics 620. We updated the driver to the latest version but that doesn't help. Latest Chrome on the same machine has no problem on screen sharing. 100% reproducible. Our electron version is 4.04. 

Anything we can do to help resolving this issue?

**Comment by MarshallOfSound** [comment] 2019-03-28 22:04
Potentially the same thing (and root cause) as #17551

**Comment by rhwu** [comment] 2019-03-29 05:04
If there's a patch for the issue, we can help to try it out on the problematic computer.

**Comment by Leoword** [comment] 2019-07-03 10:27
```js
desktopCapturer.getSources({
  types: ['window']
}).then(() => {
  desktopCapturer.getSources({types: ['screen']}, (error, sources) => {})
});
```

it works,
but we don't know why...

**Comment by ajmacd** [comment] 2019-07-04 07:17
Interesting, thanks! That's probably a little better than the conceptually similar workaround we started using of capturing any screen with `getUserMedia` momentarily before calling `getSources`.

**Comment by sofianguy** [comment] 2019-08-09 22:54
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:16
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:16 UTC
Labels: 3-0-x, blocked/need-info ❌, bug/crash :boom:, bug/regression :leftwards_arrow_with_hook:, platform/windows

**Comment by ADoesGit** [comment] 2020-09-26 23:45
This seems to still happen on Electron ``10.1.2``

**Comment by gkarmas** [comment] 2021-01-01 22:11
type Screen crashes with multiple peers connected on latest version too. It works up to 3 peers, on the 4th peer it hits 100% CPU and crashes.

**Comment by kyr0** [comment] 2022-06-10 17:23
And it still happens in `18.2.3`. Maybe the documentation here: https://www.electronjs.org/docs/latest/api/desktop-capturer 
should be updated to @Leoword answer -- atm you copy & paste -> crash on macOS 12.4 on an M1 Max
