### ISSUE TITLE
[Bug]: browserWindow.webContents.print() causes app to crash

### ISSUE THREAD

**Issue by saugatdai** [electron/electron#32276] opened 2021-12-23 02:51 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Expected Behavior

Print the contents of browser window to the default attached printer.

### Actual Behavior

Application got crashed...
![image](https://user-images.githubusercontent.com/36808955/147180511-d5e2498e-e5b0-47d7-bed3-74dff101d022.png)

**Comment by codebytere** [comment] 2022-01-25 12:37
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-02-07 09:42
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-02-07 09:42 UTC
Labels: platform/linux, component/printing, bug :beetle:, blocked/need-repro, 16-x-y

**Comment by Sulekhiya** [comment] 2023-02-10 07:56
@codebytere  I am facing the same issue.  Can we reopen this thread or make a new thread so that you can check this issue again?

For me webContents.print() worked for one printer but the app crashed for another printer.
