### ISSUE TITLE
[Bug]: There are no external screen in desktopCapturer.getSources result after hot plug-unplug-plug

### ISSUE THREAD

**Issue by an9949an** [electron/electron#36287] opened 2022-11-09 09:59 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

reproduced in 8, 17-21

### What operating system are you using?

Windows

### Operating System Version

Windows 10 pro 21H2 19044.2130, also was tested on other versions

### What arch are you using?

x64

### Last Known Working Electron version

---

### Expected Behavior

`desktopCapturer.getSources(...)` should return correct amount of sources after any amount of screen plug-unplug-plug,

### Actual Behavior

1. Plug external screen.
2. Check `desktopCapturer.getSources(...)` result. External screen is present.
3. Unplug external screen.
4. Plug external screen again.
5. Check `desktopCapturer.getSources(...)` result. There are no external monitor.

### Additional Information

This issue was tested on latest versions from 17 to 21, also 8. It was tested on different laptops with intel and amd iGPUs, same result. Also in virtualbox with VBoxSVGA adapter.

**Comment by an9949an** [comment] 2022-11-09 18:25
There are was mistake in original description that electron 8 has no such issue. After retesting I can confirm that electron 8 also has it.

**Comment by codebytere** [comment] 2022-11-10 11:19
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed** 2023-01-10 02:04 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, component/desktopcapturer, 21-x-y
