### ISSUE TITLE
BrowserWindow 'close' event doesn't fire in renderer process

### ISSUE THREAD

**Issue by yishn** [electron/electron#8196] opened 2016-12-13 13:13 UTC
* Electron version: v1.4.10
* Operating system: Windows 10

While trying to find a workaround for #7977 using the `close` event of a `BrowserWindow`, I found out that it doesn't fire in the renderer process as it would in the main process.

### How to reproduce

Just add the following lines at the start inside `<body>` of the default app `index.html`:

~~~js
require('electron').remote.getCurrentWindow().on('close', evt => evt.preventDefault())
~~~

But you can still close the window.

**Comment by enlight** [comment] 2016-12-13 14:13
This is expected behavior, and a duplicate of #4473

**Closed by enlight** 2016-12-13 14:13 UTC
