### ISSUE TITLE
[Bug]: "Ozone X11" briefly displayed in window title on Linux

### ISSUE THREAD

**Issue by lukas2** [electron/electron#34467] opened 2022-06-07 15:01 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

22.04

### What arch are you using?

x64

### Last Known Working Electron version

13.3.0

### Expected Behavior

Expect to see no title in the title bar, before our app title is displayed.

### Actual Behavior

No text "Ozone X11" shown in title bar, before our app title is displayed.
![IMG_6217 Medium](https://user-images.githubusercontent.com/213249/172413759-25121bc3-1c28-4fc4-8775-dbe0d3939dad.jpeg)

**Comment by deermichel** [comment] 2022-06-09 07:32
Thanks for reporting this and helping to make Electron better!

I cannot reproduce this issue neither on 17.1.0 nor on newer versions (Ubuntu 22.04).

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com/) that Electron maintainers can use.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by ckerr** [comment] 2022-06-14 18:15
Looks like this is coming from `ui/ozone/platform/x11/ozone_platfomr_x11.cc`:

```c++
    std::unique_ptr<PlatformWindow> CreatePlatformWindow(
        PlatformWindowDelegate* delegate,
        PlatformWindowInitProperties properties) override {
      auto window = std::make_unique<X11Window>(delegate);
      window->Initialize(std::move(properties));
      window->SetTitle(u"Ozone X11");
      return std::move(window);
    }
```

**Comment by lukas2** [comment] 2022-07-11 13:51
@ckerr oh wow, is this an omission? Perhaps time to open an issue issue over at Chromium?

**Comment by RaisinTen** [comment] 2022-07-15 11:18
The fix has landed on main in https://github.com/electron/electron/pull/34770 but it probably won't get backported automatically, so I have submitted a backport PR for v19 - https://github.com/electron/electron/pull/34929. Will attempt to backport it back to v17 if folks are okay with the current PR.

**Comment by RaisinTen** [comment] 2022-07-18 06:39
The fix has landed on 19-x-y and it will be available in the next v19 release, closing!

**Closed by RaisinTen** 2022-07-18 06:39 UTC
Labels: platform/linux, bug :beetle:, blocked/need-repro, 17-x-y, 18-x-y, 19-x-y

**Comment by lukas2** [comment] 2022-08-10 12:07
@RaisinTen + others: thank you very much! 🙂

**Comment by lukas2** [comment] 2022-08-11 13:54
I have to come back to this. 

I _still_ see the "Ozone X11" during startup. As I write this I am cloning electron source code to look for the reason, as Github search doesn't make searching specific commits easy. But it looks like the `setTitle(...)` part was just moved elsewhere.

I'll try to find it, but if someone else knows..

**Comment by lukas2** [comment] 2022-08-12 09:15
Hi guys can we please re-open this for Electron 20? I just checked, my team moved on to 20.0.0 and there we still have the issue. Checking here: https://github.com/electron/electron/blob/v20.0.0/DEPS

I see:

```
  'chromium_version':
    '104.0.5112.65',
```

but if I check that tag in the chromium repo I get this:

```
~/code/chromium [(HEAD detached at 104.0.5112.65)] $ rg -i "setTitle.*ozone x11"
ui/ozone/platform/x11/ozone_platform_x11.cc
105:    window->SetTitle(u"Ozone X11");
```

which is Linux bug..

Can you please fix it here, too? Or should I open a new issue? Whichever is most convenient.

@RaisinTen @ckerr @deermichel (listing usernames, because I am not sure if you get pinged if I write in a closed issue otherwise..) ;)

**Comment by RaisinTen** [comment] 2022-08-12 10:10
Hi @lukas2, your analysis is correct! The change has only landed on v18.3.6. I'll try to get the fix backported to 19-x-y and 20-x-y. 21-x-y doesn't require a backport because it's on Chromium M106, which already has the fix.

**Comment by RaisinTen** [comment] 2022-08-12 10:12
19-x-y backport - https://github.com/electron/electron/pull/35316
20-x-y backport - https://github.com/electron/electron/pull/35316

**Comment by lukas2** [comment] 2022-08-15 07:38
Thank you, much appreciated!
