### ISSUE TITLE
Windows System Tray Icon Resolution

### ISSUE THREAD

**Issue by engelgabriel** [electron/electron#2248] opened 2015-07-16 16:54 UTC
I've created a few tray icons for windows with the @2x, @1.5x, etc  notation.. but it doesn't seem to get used at all. 

Am I doing something wrong or is it a known limitation of the tray api that it only loads the standard image.

Or, does the Windows "Change the size of all items" has no effect on the calculation of the tray icon for Electron?

![screen shot 2015-07-16 at 13 51 03](https://cloud.githubusercontent.com/assets/1000217/8729484/ef5c4a36-2bc1-11e5-88e4-8c89a4880882.png)

As far as I know, Slack for Windows is built on Electron, and their System Tray icon looks perfect in all sizes I've tried.

**Comment by zcbenz** [comment] 2015-07-16 17:46
Closing since Slack's tray icon works well and I'm assuming it is not a bug of Electron.

/cc @paulcbetts might have an idea of how to achieve what you want.

**Comment by paulcbetts** [comment] 2015-07-16 18:20
We don't use the @2x images, I think that they actually don't work with Tray, we just use a 32x32 image

**Comment by engelgabriel** [comment] 2015-07-16 20:24
Shame.. the @2x works on the Mac tray for retina display really well... could it be a feature request to make it work on Windows tray too? Just relying on windows to resize the image has very inconsistent results. Maybe allowing .ico files in windows tray? (that's Microsoft recommendation)

Is there any way to get the current "Change the size of all items" on the app?

If so, I could decide what icon to use on the application level... maybe that is what Slack does?

**Comment by jstejada** [comment] 2015-11-09 21:59
@engelgabriel I'm actually having a similar issue on mac: https://github.com/atom/electron/issues/3376

Do you have any ideas?

**Comment by engelgabriel** [comment] 2015-11-10 03:26
I was going to try native .ico support... but haven't tried yet.

@zcbenz seems to think that Slack works, but this is not true. They just used an icon that resizes well.. but you can see it is not the right dimension for the resolution.

I'd not consider this issue closed if you cannot use multi resolution .ico files as recommended by MS :(

**Comment by jasmussen** [comment] 2015-12-02 09:24
I'm working on a Windows app that's affected by this issue. I've created a few test cases to confirm it.

First I extracted a stock Windows app icon, to confirm it wasn't an issue with my .ico file. Then I baked in text detailing the resolution of each icon:

![icon-app-screenshot](https://cloud.githubusercontent.com/assets/1204802/11526862/acd52546-98dd-11e5-8fa6-2d7d8a058b95.png)

Here's the test icon file I created: https://cloudup.com/cO5RWp-v0Zp

Here's the result in Windows 10 and Windows 7:

![win10-tray](https://cloud.githubusercontent.com/assets/1204802/11526908/fe6fa9e4-98dd-11e5-90d9-19b598c17fe1.png)

![win7-tray](https://cloud.githubusercontent.com/assets/1204802/11526912/016f1abc-98de-11e5-8655-7a4a9fb84fad.png)

As you can see, the 32px version is used even when the 16px version should be used. Scaling down the image to 16px results in a fair amount of artifacts, which explains why the tray icons look pixelated.

To further confirm it wasn't an issue with the icon itself, I created a shortcut to an app, and assigned my test icon as its icon:

![custom-shortcut](https://cloud.githubusercontent.com/assets/1204802/11526964/53527568-98de-11e5-9e6c-81a148483069.png)

When viewed in a list view the 16px version is correctly used:

![custom-shortcut-result](https://cloud.githubusercontent.com/assets/1204802/11526971/5e5f8bd0-98de-11e5-9010-e04c843bdbfe.png)

One "fix" for this is to only include the 16px version in the .ico file itself. This results in the correct resolution being loaded, as it's the only density to load. But obviously this will result in blurry scaled icons on high density displays, or with text zoom enabled. 

This could be an upstream issue, since Google Chrome seems to have a similar issue with packaged apps that run in the tray. Here's <a href="https://chrome.google.com/webstore/detail/google-hangouts/nckgahadagoaajjgafhacjanaoiihapd?hl=en">Hangouts</a> running in the tray:

![hangouts](https://cloud.githubusercontent.com/assets/1204802/11527032/bc35ea38-98de-11e5-8aa7-219ac21cf4e0.png)

Notice how the edges are badly artifacted, especially the right edge.

**Comment by natetyler** [comment] 2016-05-16 15:42
I'd like to vote for this issue, we're having the same problem - in the title bar not the tray. Windows 7. Looks fine with a 16px only icon but does not render properly if other sizes are included. In fact, the default electron icon looks like garbage in the title bar. You can see it rendering properly at the same size in Explorer

![screen shot 2016-05-16 at 11 41 03 am](https://cloud.githubusercontent.com/assets/4826751/15294702/5266d2b6-1b5b-11e6-9544-a6a96b46aa28.png)

**Comment by paulcbetts** [comment] 2016-05-16 18:06
@natetyler This is also a longstanding bug, create the BrowserWindow without an icon explicitly set, it will inherit the EXE's icon but using the proper scaling

**Comment by paulcbetts** [comment] 2016-05-16 18:07
Basically the core issue is that Skia has no concept of an HICON, so the image gets piped to a Real Bitmap then piped back to an HICON which ends up degrading it

**Comment by natetyler** [comment] 2016-05-16 20:03
I don't think I'm setting an icon on the BrowserWindow:
```
  mainWindow = new BrowserWindow({
    width: 1350,
    height: 800,
    show: false,
    title: app.getName()
  });
```

**Comment by zcbenz** [comment] 2016-05-17 00:15
@natetyler You probably also need to set AppUserModelId for your app.

**Closed** 2016-05-20 14:30 UTC
Labels: bug, windows
