### ISSUE TITLE
PDF printing by user operation, PDF cannot be printed normally 

### ISSUE THREAD

**Issue by sujiewen** [electron/electron#28558] opened 2021-04-07 02:15 UTC
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7 and window 10 v2004

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0

### Expected Behavior

Trigger print pdf by user button， round that the pdf (file has been downloaded locally) cannot be printed normally。Window and mac have the same problem， code show as below：

export function printPage2(strUrl, isLocal = false, callback) {
  const printWindow = new BrowserWindow({
    title: 'Printer',
    show: true,
    width: 1024,
    height: 768,
    parent: tmpMinWindow,
    plugins: true,
    webPreferences: {
      devTools: false,
      nodeIntegration: true, //开启渲染进程中调用模块  即require
      enableRemoteModule: true,
      contextIsolation: false
    }
  })
  console.log('printPage2=' + strUrl)

  printWindow.loadFile(strUrl)
  
  // did-finish-load
  printWindow.webContents.on('did-finish-load', () => {
    console.log('did-finish-load')
    printWindow.webContents.print(
      { silent: false, printBackground: false },
      (success, failureReason) => {
        console.log('success=' + success + ' failureReason =' + failureReason)
        if (callback) {
          callback(success ? null : failureReason)
        }
      }
    )
  })

  let sList = printWindow.webContents.getPrinters()
  console.log('sList = ' + JSON.stringify(sList))

  printWindow.webContents.on('did-fail-load', (event, errorCode, errorDes, validateURL) => {
    console.log('did-fail-load =' + errorCode)
    if (callback) {
      callback(errorDes)
    }
  })
}

### Actual Behavior

BrowserWindow.webContents.print Unable to respond normally, no results are returned, one of the local printer jobs shows that the print job is being received, and there is no response on the printing side

Using pdf internal pdf printing can print normally, but it cannot work normally through BrowserWindow.webContents.print

**Comment by sujiewen** [comment] 2021-04-07 02:24
Click the print button, the local print task shows that it is receiving data, and the printer is not responding

[
![1617762176625](https://user-images.githubusercontent.com/1973318/113801361-47748900-978b-11eb-85a8-9dc5c2f90714.jpg)
<img width="630" alt="截屏2021-04-07 上午10 07 44" src="https://user-images.githubusercontent.com/1973318/113801377-4e030080-978b-11eb-90cb-8e1bf6891d2c.png">

](url)

**Comment by ckerr** [comment] 2021-04-07 04:10
Hey @sujiewen, thanks for reaching out!

In your bug report I think you may have mistyped something; you reported that it last worked in 11.3.0 but is also broken in 11.3.0. Can you check the versions and confirm the versions for when it worked before and the version it's broken in?

**Comment by codebytere** [comment] 2021-04-08 16:37
Duplicate of https://github.com/electron/electron/issues/27954

**Closed by codebytere** 2021-04-08 16:37 UTC
Labels: 11-x-y, blocked/need-info ❌, bug :beetle:, component/printing, platform/macOS
