### ISSUE TITLE
Scope issues with eval()

### ISSUE THREAD

**Issue by ButzYung** [electron/electron#8854] opened 2017-03-07 14:30 UTC
* Electron version: 1.6.2
* Operating system: Windows 10 64-bit

### Expected behavior

eval() should run in the current scope and be able to access global variables. The following script, which is executed on the main process (global scope), should produce no error (in fact, it does work properly in Electron v1.4.15).

```
eval(
  "const app = electron.app;\n"
+ "const BrowserWindow = electron.BrowserWindow;\n"
+ "app.on('ready', function() {\n"
+ "  mainWindow = new BrowserWindow({ ... });\n"
+ "});"
);
```

### Actual behavior

Error occurs on the "new BrowserWindow" part saying BrowserWindow is not defined. The defined global variable BrowserWindow is not accessible inside the function.

As a workaround, I have to enclose the script inside an anonymous self-invoking function so that a local scope is created to avoid the problem.

```
eval (
  "(function () {\n"
......
+ "})();"
);
```

**Comment by MarshallOfSound** [comment] 2017-03-07 14:41
@ButzYung Are you using babel?

**Comment by ButzYung** [comment] 2017-03-07 16:28
@MarshallOfSound No. Just some hand-written JavaScript running on a prebuilt version of Electron.

**Comment by kevinsawicki** [comment] 2017-03-08 00:31
@ButzYung are you setting up `electron` as a global somewhere? In your example I don't see where you assign `electron = require('electron)`.

Both of these examples work for me when running this file with `electron eval.js`:

```js
eval(
  "const electron = require('electron');\n"
+  "const app = electron.app;\n"
+ "const BrowserWindow = electron.BrowserWindow;\n"
+ "app.on('ready', function() {\n"
+ "  mainWindow = new BrowserWindow();\n"
+ "});"
)
```

```js
const electron = require('electron')

eval(
  "const app = electron.app;\n"
+ "const BrowserWindow = electron.BrowserWindow;\n"
+ "app.on('ready', function() {\n"
+ "  mainWindow = new BrowserWindow();\n"
+ "});"
)
```

Can you include the entire file you are running the main process?

**Comment by ButzYung** [comment] 2017-03-08 08:01
I thought the above script was the mininal test case (which is not after actual test), but after some more testings, it seems the situation is more complicated.

In my actual app, the eval part is not directly parsing an inline string. Instead, it parses the content of an external file. The cause of the scope issue looks quite "random", and it seems to be related to the locations of some of those JavaScript comments. I have managed to create a minimal test case, but still I don't exactly know the cause. If I remove some comments here and there, the script would run.

Anyways, here it is. Load the main script that contains the followings.

```
const electron = require('electron')
const fs = require('fs')
eval(fs.readFileSync(__dirname + '\\zzz.txt').toString())
```

And inside the same folder, add the attached "zzz.txt.

Run it on Electron v1.6.2, and an error will occur saying "BrowserWindow" is undefined.

PS: What's even more confusing is that if you convert the content of "zzz.txt" into an inline string and eval it directly, it will work.
[zzz.txt](https://github.com/electron/electron/files/826980/zzz.txt)

**Comment by enlight** [comment] 2017-03-08 08:07
@ButzYung I'd suggest checking the encoding of the source file.

**Comment by ButzYung** [comment] 2017-03-08 08:10
@enlight It's a standard UTF-8 encoded document created in Notepadd++, nothing abnormal as far as I can see. The point is, the exact same script did run on older version of Electron (the last I tested was v1.4.15).

**Comment by MarshallOfSound** [comment] 2017-03-08 08:11
@ButzYung Can you try

```js
eval(fs.readFileSync(__dirname + '\\zzz.txt', 'utf8'))
```

Just to see what happens 👍

**Comment by ButzYung** [comment] 2017-03-08 08:16
@MarshallOfSound  Tested, but it didn't change anything. The script would still return an error at the same point saying BrowserWindow is not defined.

**Comment by pronebird** [comment] 2017-03-08 12:22
@ButzYung I looked at your zzz.txt and I would suggest to put `;` at the end of statement, cuz you know, javascript..

**Comment by albinekb** [comment] 2017-05-20 02:07
I think this is relevant, https://github.com/webpack/webpack/issues/2145 🤔

**Comment by zcbenz** [comment] 2017-06-13 09:58
I'm closing this since it is a problem caused by the update of V8 or Node.js, you have to find out the root cause yourself and report it to V8 or Node.js, we are unable to fix this on Electron's side.

**Closed by zcbenz** 2017-06-13 09:58 UTC
Labels: more-information-needed, triage/bug
