### ISSUE TITLE
Windows: SelectBox wrongly rendered after a reload

### ISSUE THREAD

**Issue by isidorn** [electron/electron#9364] opened 2017-05-03 15:35 UTC
* Electron version: 1.6.6 (does not happen with 1.4.6)
* Operating system: Win10. Does not happen on OS X

### Expected behavior
Clicking on a select box dropdown all the select box options are nicely rendered.

### Actual behavior
Clicking on a select box dropdown after a fresh reload most of the options are black. Looks like a rendering bug.

### How to reproduce

1. git clone https://github.com/isidorn/electron-quick-start
2. Run the app on windows - reload the app and click on the select box, notice how the options are badly rendered
3. Try to relaod a couple of times since sometimes it does not repro

A VSCode bug that surfaces this issue (gifs and pictures are attached there) https://github.com/Microsoft/vscode/issues/25700

**Comment by ydcoming** [comment] 2017-06-09 11:42
This seems to be caused by setting backgroundThrottling for the Window.

**Comment by zcbenz** [comment] 2017-06-20 09:01
Does it happen in v1.7.x?

**Comment by isidorn** [comment] 2017-06-20 12:57
@zcbenz it does not repro with latest

**Comment by isidorn** [comment] 2017-09-01 09:44
@zcbenz users can actually repro with electron v1.7.x, more details can be found here https://github.com/Microsoft/vscode/issues/25700#issuecomment-322958705
Let me know if you need more details from our side --thanks

**Comment by codebytere** [comment] 2018-09-24 04:52
We are no longer implementing bugfixes for versions of Electron < `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-09-24 04:52 UTC
Labels: bug :beetle:, platform/windows, version/1.6.x
