### ISSUE TITLE
[Bug]: When webview.src = devtool_app.html and  entering the breakpoint,  the page is stuck

### ISSUE THREAD

**Issue by yinhunfeixue** [electron/electron#30394] opened 2021-08-04 02:24 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.13

### What operating system are you using?

macOS

### Operating System Version

macos 11.5

### What arch are you using?

x64

### Expected Behavior

The debug button can be clicked

### Actual Behavior

The debug button can't be clicked

## This is the describe
![image](https://user-images.githubusercontent.com/29660825/128110003-da95c97d-daac-4034-9410-c21479d952c8.png)

## This is the code

[my-electron-app.zip](https://github.com/electron/electron/files/6928127/my-electron-app.zip)

### steps
1. unzip
2. `npm i && npm start`
3. Click the button at the top
4. then debug buttons cannot be clicked

**Comment by clavin** [comment] 2021-08-04 21:03
Thanks for taking the time to contribute!

I noticed that this is a duplicate of #27523. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by clavin** 2021-08-04 21:03 UTC
Labels: bug :beetle:
