### ISSUE TITLE
Audio issues (glitch sound)

### ISSUE THREAD

**Issue by riadd** [electron/electron#7101] opened 2016-09-05 12:23 UTC
* Electron version: 1.3.3
* Operating system: Windows 10

We recently updated to Electron 1.3.3 from version 0.36.5 and some of our users are experiencing two types of audio issues when playing music now:

1. Tracks that would play though and loop properly before are now often restarting every 3 seconds or so.
2. There is a unpleasant glitch sound that randomly appears when tracks are stopped.

You can hear the second problem in this video https://youtu.be/yHiFkkvSzVY?t=1m42s
It appears multiple times throughout the video.

We're using buzz.js to play .ogg files. Everything worked prior to updating the Electron version, so I would suspect that Electron is the problem. Unfortunately, I was not able to reliably reproduce the issue on my machine.

**Comment by enlight** [comment] 2016-09-05 12:55
Have you tried reproducing the issue in the Chrome?

**Comment by riadd** [comment] 2016-09-05 12:57
@enlight I was not able to repro the issue in Chrome

I also forgot to mention that the problem of repeating sounds seems to become worse the longer the application is running. After two hours of playing the bug appears much more often.

**Comment by zcbenz** [comment] 2016-09-12 06:58
Are you using Chrome 53 or 54? Next minor release of Electron will use Chrome 54 so it might be able to fix the problem.

Electron uses Chrome's code for audio things, so we are not able to solve this kind of problems and your only hope is to wait for Chrome upgrades.

**Comment by zcbenz** [comment] 2016-10-20 02:21
Closing since it is very likely an issue of Chrome.

**Closed by zcbenz** 2016-10-20 02:21 UTC
Labels: more-information-needed
