### ISSUE TITLE
looks like run into infinite loop

### ISSUE THREAD

**Issue by maicss** [electron/electron#13401] opened 2018-06-23 14:53 UTC
* Electron Version: `2.0.3`
* Operating System (Platform and Version): `Mac OS 10.13.5`
* Last known working Electron version: `none`

**Expected Behavior**
Print `file` or `dir` or ` invalid path error `
**Actual behavior**
Nothing happened, the CPU usage going up high
**To Reproduce**

```
const electron = window.require('electron')
const fs = electron.remote.require('fs')
const path = electron.remote.require('path')
const utils = electron.remote.require('util')

const _readDir = utils.promisify(fs.readdir)
const _stat = utils.promisify(fs.stat)
const imageSuffix = ['.jpeg', '.jpg', '.gif', '.bmp', '.png']

const dirFileFilter = file => {
  return _stat(file).then(stat => {
    if (stat.isDirectory()) {
      return `dir`
    } else {
      if (imageSuffix.includes(path.parse(file).ext)) {
        return `image file`
      }
    }
  }).catch(e => ({error: e}))
}

// comment this line, works fine.
dirFileFilter('/Users/maicss/Development/images/test1').then(d => console.log(d)).catch(e => console.error(e))

```

**Additional Information**
I followed [this guide](https://medium.freecodecamp.org/building-an-electron-application-with-create-react-app-97945861647c) to build my work environment. here is my config:
```
{
  "name": "image-viewer",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "antd": "^3.6.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-redux": "^5.0.7",
    "react-router": "^4.3.1",
    "redux": "^4.0.0",
    "redux-saga": "^0.16.0"
  },
  "main": "src/main.js",
  "homepage": "./",
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "electron": "ELECTRON_START_URL=http://localhost:3000 electron ."
  },
  "devDependencies": {
    "electron": "^2.0.3",
    "prop-types": "^15.6.1",
    "react-scripts": "1.1.4"
  }
}

```

**Comment by pronebird** [comment] 2018-06-25 07:45
Do you have node integration disabled in renderer or what’s the reason behind using  `electron.remote.require` instead of normal `require`?

**Comment by MarshallOfSound** [comment] 2018-06-25 12:31
@maicss It looks like you are using webpack through Create React App, if webpack is not configured properly for electron things like `fs`, `path`, `util` and `electron` will not function correctly.  If you `require` them you will simply get empty objects, or browser mocks of the real APIs.

I'd recommend trying to reproduce the problem without webpack (and you will most likely find everything works)

**Comment by maicss** [comment] 2018-06-25 12:44
but with `electron.remote.require` i got `fs` as expect. and `no webpack` means use electron without any other package ?

**Comment by codebytere** [comment] 2019-02-05 23:22
Given that this hasn't been reproduced in a context that tells us this bug is electron-specific, i'm going to close this.

**Closed by codebytere** 2019-02-05 23:22 UTC
Labels: 2-0-x, bug :beetle:, platform/macOS
