### ISSUE TITLE
webview doesn't render and support deviceEmulation

### ISSUE THREAD

**Issue by soulteary** [electron/electron#5488] opened 2016-05-11 08:37 UTC
* Electron version: v0.37.8
* Operating system: OSX 10.11.4

Hi, I've some problem with electron on devtools(both BrowserWindow and webview)/deviceEmulation.

I use ```<webview> ``` tag to load url which page i wanna test. 

If i use ```enableDeviceEmulation``` in ```BrowserWindow```,  the ```<webview>``` wouldn't render any content, unless i open BrowserWindow's devtools and click ```[toggle device mode]```. 

Code here:

```
let mainWindow = new BrowserWindow({
    show  : false,
    width : 1024,
    height: 728
  });

 const webContents = mainWindow.webContents;
    webContents.enableDeviceEmulation({
      screenPosition: 'mobile',
      screenSize: { width: 480, height: 640 },
      deviceScaleFactor: 0,
      viewPosition: { x: 0, y: 0 },
      viewSize: { width: 480, height: 640 },
      fitToView: false,
      offset: { x: 0, y: 0 }
    });
    // whether you open devtools and click toggle device button.
    // mainWindow.openDevTools();
```

Then i remove above code. Just wait webview ```dom-ready```, and open webview's devtools , i found the devtools doesn't contain ```toggle device mode``` button, and i can't ```enableDeviceEmulation``` in ```webview```.

I found if i detach the BrowserWindow's devtools window, it's toggle device button will miss as the same, but it seems no way to dock the webview's devtools window...

**Comment by deepak1556** [comment] 2016-05-11 19:28
`screenPosition: mobile` will disable [plugins](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/web/DevToolsEmulator.cpp&sq=package:chromium&l=272&rcl=1462965594), hence `webview` doesn't show up. `detach` devtools mode is mostly used to inspect processes with no views, hence `toggle device mode` is not available, its a feature on chromium side.

**Comment by zcbenz** [comment] 2016-05-12 01:33
I'm closing this since it is an expected behavior of Chromium, and we are not able to change this on Electron's side, if you would like to change this I suggest creating an issue at Chromium's issues list.

**Closed by zcbenz** 2016-05-12 01:33 UTC

**Comment by GnorTech** [comment] 2016-05-12 03:09
@soulteary Consider NW.js which supports deviceEmulation.

**Comment by soulteary** [comment] 2016-05-12 03:17
@deepak1556 @zcbenz thx.

**Comment by zcbenz** [comment] 2016-05-12 12:32
@GnorTech Thanks for answering this issue, even though you didn't actually read it.

Please allow me to share you some experience on how to promote an open source project, since you are trying hard to do that. One of the keys is issues management, you need to answer every issue, categorize them, and close them when they are resolved, so people can trust your project and are confident to contribute to it.

I'm not saying you do not understand that, it is just amusing that you spend more time answering issues in Electron instead of NW.js, while trying to persuade people to use the latter.

**Comment by GnorTech** [comment] 2016-05-12 22:14
@zcbenz I do read the requirement. I'm just helping @soulteary and give him a way out with a feature in NW which you don't want to support. I don't see any problem in it. Promoting NW is just a side effect.

If you're curious on my role in NW, unfortunately that doesn't include issue scrubbing. My work has been focused on helping Chromium rebase so that NW could release after Chromium upgrade soon.

**Comment by zcbenz** [comment] 2016-05-12 23:58
@GnorTech No you didn't, if you really read it you will find out it is not about `enableDeviceEmulation` working, it is about `<webview>`. You are not helping people, you are just trolling.

**Comment by GnorTech** [comment] 2016-05-13 01:12
Hey @zcbenz the issue is about webview **and** the device emulation, as OP said `open webview's devtools , i found the devtools doesn't contain toggle device mode button, and i can't enableDeviceEmulation in webview"`.

btw, NW's webview has more features than the one in Chromium, you probably didn't know it.

**Comment by soulteary** [comment] 2016-05-13 03:54
Hey @GnorTech / @zcbenz , thank you again, both of you're nice and plz take it easy.

** SORRY FOR MY POOR ENGLISH  :grin: **

You're right but no all,  is my fault, i should describe more clear.

I'm trying to make a software to help front-end coder to test GUI and user action on web page easy, just like someone suggest that electron may able to.

The web page running in standard  browser/any kind of webview.

I've tried those way to collect user action:

- use browser bookmark to inject record.js
- use chrome extension to inject record.js

They work find at most scenes, but i'm trying to record case by case, there're so many case need to managed.

Because developer's testing target in different network environment as usual, replay user action in server by casper.js/phantomjs is a way but not a wise choice.

Because browser plugin api possible changes with browser release new version, and it often update, it won't be a reliable base for replay or manage test case which record by developer.

So, make browsers or use browser like container(just like electron or node-webkit) is better way to help me finish the job.

that's all my demands.

But when i try to use electron to record my test case, i found it's ```<webview>``` can't offer the device emulator, so many mobile website will doesn't work, then i ask you this question.

---

We know that two heads are better than one.
Both electron and nw.js are great one, it is not necessary to quarrel or angry.
Maybe we should seeking common ground while putting aside differences.

**Comment by gengdaoping** [comment] 2017-01-05 08:57
how to emulate mobile page in electron ？

**Comment by wbpmrck** [comment] 2017-04-25 08:04
so the answer is no?

**Comment by 76765357** [comment] 2018-05-31 02:13
i have the same question, but no idea........
