### ISSUE TITLE
OSX showOpenDialog does not show all icons when it open

### ISSUE THREAD

**Issue by arrayoutofbounds** [electron/electron#5190] opened 2016-04-18 00:18 UTC
The file dialog opens from a renderer process, but most of the icons are missing for the files and the folders. 

[screenshot](http://imgur.com/BZWIYaI)

* Electron version: 0.37.2
* Operating system: OSX 10.11.4

**Comment by DannyvanderJagt** [comment] 2016-04-18 07:28
@arrayoutofbounds I did a quick test on OS X (10.11.3) and electron (0.37.5) and everything worked fine. I used `Electron.remote.dialog.showOpenDialog()` in a browserWindow. I will update OS X this afternoon and try again.

Are you sure it is Electron related instead of OS X related?

**Comment by zcbenz** [comment] 2016-04-18 13:07
This is a duplicate of #4236.

**Closed by zcbenz** 2016-04-18 13:07 UTC
