### ISSUE TITLE
[Bug]: Render process does not catch pointer events properly in frameless mode within -webkit-app-region: drag; element

### ISSUE THREAD

**Issue by kashamalasha** [electron/electron#38196] opened 2023-05-05 10:34 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

24.2.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.2

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.3.8

### Expected Behavior

Steps to Reproduce:

Set BrowserWindow property "frame" to "false".
Set "-webkit-app-region: drag" on the body of an HTML file.
Try to catch UIEvents "pointerdown" and "pointerup" on any elements within the draggable parent.

Expected result:
The app should catch and handle the "pointerdown" and "pointerup" events.

### Actual Behavior

Actual Result:
The app does not catch the "pointerdown" events as expected. Instead, it catches a two-finger "pointerdown" event only. Additionally, "pointerup" events are not caught at all.

Workaround:
Add explicitly property -webkit-app-region: no-drag; to the elements that need to be listened to. 
But in version 22.3.8 it was possible to hook the event.shiftKey event and leave the whole window dragged on a normal click, and be able to listen to UI events when the Shift key was pressed. 

### Testcase Gist URL

https://gist.github.com/99fc6e7521a7e3e44d6110b49c0dd061

### Additional Information

This bug was not present in the previous work version of Electron (22.3.8).

**Comment by kashamalasha** [comment] 2023-05-05 12:02
It has the same behavior in 23.0.0 release as well.

**Comment by BlobTheKat** [comment] 2023-05-05 14:40
Duplicate of #37789

**Comment by codebytere** [comment] 2023-05-08 19:21
Closing as duplicate of https://github.com/electron/electron/issues/37789

**Closed by codebytere** 2023-05-08 19:21 UTC
Labels: bug :beetle:
