### ISSUE TITLE
Warning from HTML dialog tag: "GtkDialog mapped without a transient parent. This is discouraged."

### ISSUE THREAD

**Issue by jfabiani** [electron/electron#12423] opened 2018-03-23 22:43 UTC
I get the below message when opening a hidden dialog (used standard HTML tag dialog)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

* Electron version: electron beta 5
* Operating system:  OpenSuse 42.3 Linux

### Actual behavior
Actually the dialog works as expected without any issues.  I don't see this on 1.8.4 so I can only assume it has something to do with beta 5.  Also I see the message in the terminal (not in the Dev tools console) while in dev mode (not ready for production at this time).

**Comment by jfabiani** [comment] 2018-03-23 22:47
I should point out that the message is a warning.  Also the dialog is using "showModal".  When I tried to research the issue I found that GTK3 wants a parent to be passed to function/method.  The GTK modal needs a parent to be modal too.

**Comment by ckerr** [comment] 2018-03-25 17:09
This happens in `showOpenDialog()` even if the `browserWindow` parent argument is passed in.

Atom is using `libgtkui::SetGtkTransientForAura()`, which seems to succeed at actually handling the transient/modal nature, but in terms of silencing this warning, the dialog's [gtk_window_get_transient_for() has to return non-null](https://git.gnome.org/browse/gtk/tree/gtk/gtkdialog.c?h=gtk-3-22#n779). This is a minor problem since Electron is using libchromiumcontent to create windows rather than `gtk_window_new()`

This is a hacky suggestion, but -- since we are already handling the issue that the warning is about by delegating transient/modal to libgtkui::SetGtkTransientForAura()` -- maybe we should just silence this warning by creating a window for the sole purpose of calling `gtk_window_set_transient_for()`, similar to how `libgtkui::GtkUi` creates a `fake_window_` for monitoring scale-factor changes.

**Comment by niikoo** [comment] 2018-09-01 11:25
+1

**Comment by avishkarabhishek786** [comment] 2018-09-03 07:47
It happened with me when I used on closed event:

`let wc = mainWindow.webContents

    wc.on('new-window', (event, url)=>{
        event.preventDefault()
        const win = new BrowserWindow({height:600, width:800, x:10, y:10, show:false})
        win.on('ready-to-show', ()=>win.show())
        win.loadURL(url)
        event.newGuest = win

        win.on('closed', ()=>{
            win = null
        })
    })`

If I remove on closed event the error is gone.

**Comment by dNvl** [comment] 2018-09-18 07:16
Yes i experience the same thing. I don't think it is appropriate to toss the in close event as it is responsible for destroying the window object probably. Would appreciate if this would be fixed somehow. But if it is not a real issure i will ignore it for now as well.

**Comment by stalina** [comment] 2018-09-19 15:47
I faced the same problem while using vscode. Vscode is, somehow, locking the file system and the watchers cannot load them when loading the application.

If you do use vscode and you are facing this problem, try closing vscode and launching your electron app in a simple terminal.
This might do the trick

**Comment by joehonton** [comment] 2018-12-25 18:03
I am receiving this message with Electron 4.0.0 on Ubuntu 18.04.1 for both the showOpenDialog() and showSaveDialog().

Samples:

	var parentWindow = remote.getCurrentWindow();
	var filenames = remote.dialog.showOpenDialog(parentWindow, options);

	var parentWindow = remote.getCurrentWindow();
	var filename = remote.dialog.showSaveDialog(parentWindow, options);

**Comment by jaysaurus** [comment] 2019-03-16 04:03
still seems to be a problem. Ubuntu 16 is giving me this message too :/

**Comment by iamthe-Wraith** [comment] 2019-04-14 03:16
I'm still seeing this issue as well. Doesn't seem to be an issue, but is really annoying seeing this all the time...any solution or even a work around found to silence this?

**Comment by Stuyk** [comment] 2019-05-23 20:52
I've come into this issue when running the 'closed' or 'close' event. I don't need to do a bunch of unloading but for those of you who are running into this; a simple work-around for now is to just do `app.exit()`.

```
this.MainWindow.on('close', (e) => {
      e.preventDefault();
      app.exit();
    })
```

**Comment by kmaher9** [comment] 2019-06-02 19:30
+1 keeping this alive, error persists when using dialog.showOpenDialog()

![image](https://user-images.githubusercontent.com/18217965/58766338-4c57c880-8575-11e9-843f-b4b27b612cae.png)


Built using simulatedgreg

**Comment by neytjs** [comment] 2019-06-24 02:50
Yes, I am also getting this same warning when calling dialog.showOpenDialog(). I'm using Electron version 5.0.5.

**Comment by ckerr** [comment] 2019-06-24 18:28
Not sure what's changed, but I can no longer reproduce this.

Could someone provide an https://github.com/electron/electron-quick-start repro fork?

**Comment by sofianguy** [comment] 2019-08-09 03:24
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-09 03:24 UTC
Labels: 2-0-x, bug :beetle:, platform/linux, status/confirmed, version/1.8.x

**Comment by betamos** [comment] 2019-08-25 00:22
Just calling `dialog.showOpenDialog` is sufficient on my setup, with Electron 6.0.2. Here's a repro: https://github.com/betamos/electron-quick-start/commit/b22555a8c13c757a6e23abb2f5d90dcf0a84f83d

```
$ uname -a
Linux [redacted] 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ apt-cache policy libgtk2.0-0 libgtk-3-0
libgtk2.0-0:
  Installed: 2.24.32-1ubuntu1
  Candidate: 2.24.32-1ubuntu1
  Version table:
 *** 2.24.32-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
libgtk-3-0:
  Installed: 3.22.30-1ubuntu4
  Candidate: 3.22.30-1ubuntu4
  Version table:
 *** 3.22.30-1ubuntu4 500
        500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.22.30-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

**Comment by kosarev** [comment] 2019-10-15 22:43
@sofianguy Sofia, what information you need to resolve this?

**Comment by ig3** [comment] 2020-01-28 09:12
@sofianguy @ckerr: In response to your updates of 9 Aug 2019 and 25 Jun 2019 respectively, I have forked electron-quick-start and made fairly minimal changes to reproduce the behaviour I experienced that produced the following message when showOpenDialog is called:

> Gtk-Message: 21:06:57.025: GtkDialog mapped without a transient parent. This is discouraged.

I get this error each time I open the open file dialog from Open file... of the File menu, on Linux Mint 19.2 (Tina) with Node.js 12.8.1, Chromium 78.0.3904.130, and Electron 7.1.10.

I hope this provides what you need to investigate this issue. If anything else might be helpful, please let me know.

**Comment by manavmehta** [comment] 2020-07-01 12:16
@sofianguy We are facing a [similar issue](https://github.com/zulip/zulip-desktop/issues/932) in Zulip-Desktop.
The app, when installed through snap gives the similar error, ref this [comment](https://github.com/zulip/zulip-desktop/issues/932#issuecomment-613521375)
Whereas when installed through apt, the error is not there.

**Comment by Akela223** [comment] 2020-07-12 21:27
tengo el  mismo problema tratando de correr gnuradio 3.8.1.0.rc1  instalado por pybombs 2.3.4a0  ... no se como avanzar, llevo varios dìas intentandolo

I have the same problem trying to run gnuradio 3.8.1.0.rc1 installed by pybombs 2.3.4a0 ... I don't know how to proceed, I have been trying for several days

Gtk-Message: 16:23:43.537: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by BATMAH69** [comment] 2020-07-28 16:31
I had same issue and change `dialog.showOpenDialog()` to input.click() for <input type="file" style="display:none" />

**Comment by ulvido** [comment] 2020-08-07 17:20
same here. 

platform: Elementary OS Hera (ubuntu 18.04 based)
version: "electron": "9.1.2"

#### # index.js
```javascript
...

const version = app.getVersion();

app.on('ready', () => {

 // dialogbox
  dialog.showMessageBox(null, { message: `Current version: ${version}` });

 // terminal
  console.log(`Current version: ${version}`);

});

...
```
#### # dialogbox
![image](https://user-images.githubusercontent.com/27722274/89670973-c8bd0880-d8ea-11ea-9ab3-a9cea103fb4e.png)

#### # terminal
![image](https://user-images.githubusercontent.com/27722274/89670481-f2c1fb00-d8e9-11ea-97e2-38142639089d.png)

## Is this a development-only warning?

**Comment by marcoippolito** [comment] 2020-08-09 14:59
I'm experiencing the same problem with 

  System:
    OS: Linux 5.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm

  typescript: 3.9.7
  electron: 9.0.0

**Comment by raddevus** [comment] 2020-09-26 15:32
The following code (opening a file dialog) produces the error while running on 
Ubuntu 18.04.5 LTS
Running Node.js 12.16.3, Chromium 85.0.4183.93, and Electron 10.1.1.
The output I see in the terminal is:

> Gtk-Message: 11:27:26.395: GtkDialog mapped without a transient parent. This is discouraged.
That is output each time the open file dialog is opened.
```
ipc.on('open-file-dialog', function (event) {
  dialog.showOpenDialog({
    properties: ['openFile'],
    defaultPath: specialFoldersPath,
    
  }).then((files) =>  {
    if (files) event.sender.send('selected-file', files.filePaths)
  })
})
```
