### ISSUE TITLE
Double render on alternating redraws while scrolling

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#6950] opened 2016-08-24 00:42 UTC
* Electron version: 1.3.3
* Operating system: OSX 10.10.5

This was filed on my project: https://github.com/pfrazee/beaker/issues/68

Scrolling down the page exhibits a "double draw" condition, whether via scrollwheel or dragging the elevator. It remains visibly doubled until something forces a redraw event.

![screenshot](https://cloud.githubusercontent.com/assets/552254/17912025/dbb90b32-6945-11e6-9127-401e72a41190.gif)

I had the user dump their chrome://gpu in https://github.com/pfrazee/beaker/issues/68#issuecomment-241921890.

What can we try? Thanks!

**Comment by zcbenz** [comment] 2016-08-24 08:22
This looks like a Chrome rendering bug to me, and I'm closing this since Electron uses Chromium's rendering code directly and we are not able to fix this on our side.

I'm afraid your best choice is to try to reproduce this with Chrome bowser and then report it to Chromium's issues list, or you can just wait and see if next Chrome upgrade would fix this.

**Closed by zcbenz** 2016-08-24 08:22 UTC
