### ISSUE TITLE
Don't download updates automatically?

### ISSUE THREAD

**Issue by wesleywesley** [electron/electron#5865] opened 2016-06-04 07:28 UTC
I'd like to let the user control whether or not to download the update. User may be using a mobile connection for all we know (tethered), so downloading automatically is not something that should happen without user consent. (same for installing automatically)

**Comment by wesleywesley** [comment] 2016-06-04 17:59
it appears both squirrel.mac and squirrel.windows have this option, so will this be integrated? 

https://github.com/Squirrel/Squirrel.Mac/issues/173
https://github.com/Squirrel/Squirrel.Windows/issues/721

**Comment by zcbenz** [comment] 2016-06-06 01:21
This is a duplicate of #4587.

**Closed by zcbenz** 2016-06-06 01:21 UTC
