### ISSUE TITLE
Kubuntu 17.10 switching keyboard layout opens BrowserWindow menu

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#11106] opened 2017-11-13 10:33 UTC
* Electron version: 1.7.9, 1.8.2-beta.2, 2.0.14, 3.0.14, 3.1.0, 4.0.1
* Operating system: Kubuntu 17.10, Kubuntu 18.04

### Expected behavior

When a global keyboard is setup to change keyboard layout using <kbd>Alt</kbd>+<kbd>Ctrl</kbd> or <kbd>Alt</kbd>+<kbd>Shift</kbd> should just change keyboard layout and have no effect on any focused electron windows.

### Actual behavior

Keyboard layout is changed correctly, but if an electron browser window is focused the menu appears. If the menu has not been enabled on the BrowserWindow, but the application menu has been set the menu bar is shown and menu opened

### How to reproduce

Electron Quick start will reproduce with an application menu set, as per the example in the [docs](https://electron.atom.io/docs/api/menu/#main-process).

Configure a global keyboard shortcut to switch keyboard layouts
* Open System Settings
* Go to Input Devices
* Select Keyboard and then the Layouts tab
* Change the Main Shortcut
  ![1](https://user-images.githubusercontent.com/103586/32720888-bfaf5884-c85c-11e7-845d-dfeb906a3f0a.png)
* Pick <kbd>Alt</kbd>+<kbd>Ctrl</kbd> or <kbd>Alt</kbd>+<kbd>Shift</kbd> as a shortcut
![2](https://user-images.githubusercontent.com/103586/32720973-ef73fc28-c85c-11e7-827d-c50ab9e43b80.png)

Now you're configured, press <kbd>Alt</kbd>+<kbd>Ctrl</kbd> (note that it must be in that order, not ctrl then alt) it will change the keyboard layout and also present the menu in the focused window.

**Comment by felixrieseberg** [comment] 2017-11-14 21:58
Forgive my ignorance, but wouldn't it be on Kubuntu to capture the keyboard event and to not propagate it? It seems impossible for Electron to detect if the operating system (or other apps) have any handlers registered.

**Comment by Thomas101** [comment] 2017-11-15 08:52
I'm not 100% sure what's going on under the hood here and normally my bias would be towards it needing to be fixed in Kubuntu; hoever I tried running the same test with a few other apps, namely, Firefox and Dolphin, but didn't see the same behaviour. That's what made me suspicious that it's something that electron is doing.

The only other app I managed to see the same behaviour with alongside my test apps was Slack - which is on electron too.

@felixrieseberg What's the best way forward that you recommend here? Report to Kubuntu and see if they have any insight or do you think it's worth investigating if there's anything in electron?

**Comment by mtb-xt** [comment] 2017-11-21 21:57
The same issue happens under Cinnamon desktop in Archlinux, applications have to work around this in some obscure ways - https://github.com/RocketChat/Rocket.Chat.Electron/issues/50.
ALL electron based apps are affected, and this is very annoying.

Slack, Messenger for Desktop just to name a few. I use alt shift to change keyboard layouts and every time I need to insert a russian word in a chat, it opens this damned menu.

Please fix

**Comment by mpeshev** [comment] 2017-11-23 19:18
I can confirm the same issue with Fedora running Mate.

I ran some tests referenced in a [Russian forum](http://linuxhub.ru/viewtopic.php?t=2759&sid=93c05586bb242384f65ae0a175acf309&start=10 ) where different suggestions editing the Window or Edit labels were referenced.

I've played with adding an accelerator element to `buildEditMenu()` for `Edit` but that crashed Slack and I couldn't progress further.

It's been happening for weeks and I can't reproduce it in any other web or desktop application that I use daily.

On Slack, a couple of important keyboard shortcuts use "Alt + Shift" as well and those are inactive for me at the moment.

**Comment by gedia** [comment] 2017-12-14 12:47
Same on gentoo with slack 2.8.2. Several of the previous versions were affected too. This wasn't present several releases ago...

**Comment by vetash** [comment] 2017-12-14 13:48
@gedia switch to 2.6.0. This is latest release that not have this behaviour.

**Comment by msva** [comment] 2017-12-21 21:35
@vetash wasn't it 2.6.3? // and there is no 2.6.0 in portage anyways.

P.S. looks like issue still appears in 3.0.2, although slack's support sweared me to fix this in "next version"

**Comment by vetash** [comment] 2017-12-23 07:51
@msva No. Exact 2.6.0. You can mannualy download any release from slack.com by changed url
`https://downloads.slack-edge.com/linux_releases/slack-desktop-2.6.0-amd64.deb`

**Comment by gedia** [comment] 2018-01-19 15:35
Still affecting slack 3.0.5, released this week...

**Comment by kivan-mih** [comment] 2018-01-23 09:02
The same on mint 18 with slack 3.0.5

**Comment by gagarin55** [comment] 2018-02-12 19:34
Could you please fix it, this bug killing me

**Comment by yumm-git** [comment] 2018-02-15 09:56
Is there any workaround for the issue?

**Comment by msva** [comment] 2018-02-15 10:59
> Is there any workaround for the issue?

Not on the end user side.
Just apps developers should stop adding menu entries without an anchors.

**Comment by mlyubushkin** [comment] 2018-02-15 13:12
> Is there any workaround for the issue?

Press "Shift + Alt" instead of "Alt + Shift"

**Comment by a-atalla** [comment] 2018-11-24 07:43
i fix this when building electron apps by assigning  keyboard shortcut for each menu item `&File` instead of just `File` , this should be done to all top level menu items

**Comment by sofianguy** [comment] 2019-01-07 22:33
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by Thomas101** [comment] 2019-01-08 09:14
@sofianguy I can confirm that this still affects electron 2, 3 and 4 as well as newer versions of Kubuntu. I've updated the original issue to reflect this

**Comment by MurzNN** [comment] 2019-03-28 16:23
Same problem on Kubuntu with Electron 4.x and seems all newer versions too.

**Comment by scottnonnenberg-signal** [comment] 2019-10-07 16:40
This is reproducing on other distros of Linux on Electron 6.0.9, via Signal Desktop https://github.com/signalapp/Signal-Desktop/issues/3621

**Comment by Beelink** [comment] 2019-10-15 10:12
OS: Manjaro XFCE 18.1.0
Electron: 6.0.12

**Comment by alexey-v-paramonov** [comment] 2019-10-22 13:43
Linux Mint 19.2, same problem in Skype, Slack.
Very annoying.

**Comment by rparkhunovsky** [comment] 2019-10-22 13:53
Absolutely annoying in Skype and Slack as well. Had to downgrade Slack back to 4.0.2.
Ubuntu 16.04/Plasma 5.14.3

**Comment by vmavromatis** [comment] 2019-10-26 11:07
Same on **Signal v1.27.2-beta.1** - I remember it was not happening 2-3 weeks ago.
Manjaro/GNOME 3.34.1

**Comment by steve-todorov** [comment] 2019-10-29 18:08
This is the **MOST ANNOYING** bug I have encountered ever! The only workaround for it is if the application has `fullscreen` mode. If you put the app (i.e. Skype) in fullscreen mode it won't show the menu and you won't hit this issue. However if it doesn't support fullscreen (like Rocket.Chat) things become totally unusable as the menus get activated and typing fast and switching between languages is impossible.

**Comment by KirylKovaliov** [comment] 2019-10-29 18:52
Please fix. It's impossible to use Slack or Skype. Linux Mint 19.2 Cinnamon

**Comment by asamofal** [comment] 2019-10-30 11:14
Thanks to developers of Electron, now I can't use Slack and Skype, just because this f***ing menu focusing every time when I try to change my language layout.
I've found only one solution - downgrade Slack to version 4.0.2, now I can work without annoying.

Ubuntu 18.04 (default GNOME shell).

**Comment by bars83** [comment] 2019-11-20 09:22
"Shift + Alt" works fine, instead of "Alt + Shift". But it is very unusual after 25 years of using "Alt + Shift".
I'm using Ubuntu 18.04.3 LTS/5.0.0-36-generic + XFCE 4.14
This behavior occurs in Skype, Slack, Visual Studio Code, Mattermost, etc

**Comment by MurzNN** [comment] 2019-11-23 06:33
It starts happens on VS Code after some recent updates, seems they add new menu items without shortcuts, here is how we can fix https://github.com/electron/electron/issues/11106#issuecomment-441350115

But the source of issue is Electron Linux build, and already 3 YEARS! Please fix this problem in Electron!

**Comment by MurzNN** [comment] 2019-11-23 06:43
@Thomas101 can you please update task title to something more actual? Maybe like this: _Linux Electron always opens BrowserWindow menu on every switching keyboard layout via Alt+Shift & Alt+Ctrl_

**Comment by Sarbinski** [comment] 2019-12-20 09:50
Any progress on that?

**Comment by AlexDerbenew** [comment] 2019-12-30 02:22
Manjaro KDE. Same problem in Slack and manually nativefied by [nativefier](https://github.com/jiahaog/nativefier) apps

**Comment by MurzNN** [comment] 2020-02-01 09:07
@Thomas101 can you please update task title to something more actual? because this happens not only on old Kubuntu, but on any fresh Linux!

Maybe make title like this: `Linux Electron always unnecessary opens BrowserWindow menu on every keyboard layout switch via Alt+Shift & Alt+Ctrl hotkeys`

**Comment by MurzNN** [comment] 2020-02-16 07:21
Current issue is for too old Electron (2.0+) and have workaround via adding keyboard shortcuts to all menu items (example of fixing - here https://github.com/vector-im/riot-web/issues/4345#issuecomment-315965578), that solve reported problem on related versions in most of popular Electron apps.

But Electron 6.0 release introduce new issue, that can't solved via proposed workaround, and need separate investigate for find right fix. So I fill new separate issue for Electron 6.0 version here: https://github.com/electron/electron/issues/22213 - please vote!

**Comment by Dreyk007** [comment] 2020-05-08 12:04
Very annoying. Issue actual for every electron app (VSCode, Zulip, etc...)
KDE Neon (Ubuntu 18.04)

**Comment by protist** [comment] 2020-05-31 00:03
This bug is still present in Electron 9.0.0.

**Comment by vetash** [comment] 2020-06-15 03:31
My job is consist of endles suffering because of this. Even if you having a habit press `esc` or worse `ALT` ANY TIME YOU WANT TO SWITCH LAYOUT this behaviour apppears. You just cant switch to NORMAL app, so you continue press this `ALT` key in every application you work so this make app open context menu. This not just annoying bug this destroy all of my and i'm sure not only my productivity.

**Comment by oukooveu** [comment] 2020-06-24 10:27
Most probably this issue related to electron indirectly and actual root cause is https://gitlab.freedesktop.org/xorg/xserver/-/issues/258 (opened 15 years ago).

**Comment by MurzNN** [comment] 2020-06-24 10:41
> Most probably this issue related to electron indirectly and actual root cause is https://gitlab.freedesktop.org/xorg/xserver/-/issues/258 (opened 15 years ago).

But why this works in old Electron 5.0 apps (with fresh xorg), and breaks if they upgrade to Electron 6.0 and later versions?

**Comment by oukooveu** [comment] 2020-06-24 11:14
> But why keyboards switching laoyuts works well in old Electron 5.0 apps (with fresh xorg), and breaks if they upgrade to Electron 6.0 and later versions?

I suggest there was some workaround in previous electron version (upgrade from linux mint 18.3 to 19.3 broke my slack for example), anyway xorg-server patch from issue above works for me (but in manjaro linux, not sure about ubuntu based distributions).

**Comment by DanielLitvak** [comment] 2020-08-18 13:00
@oukooveu looks like this wont work for me because I am running Debian 10 using Gnome 3.30.2 and i have to use Xorg because Wayland does not work with Nvidia.

I think we can agree that this issue should be solved in electron.

**Comment by protist** [comment] 2020-08-18 13:11
@oukooveu This also won't work for me, because I'm affected by the Electron bug and not the Xorg bug. I use [At-home-modifier](https://gitlab.com/at-home-modifier) with my ergonomic keyboard to use `Enter` as `Alt` when held down. Hence, before sending `Enter`, my system presses and releases `Alt` first, which triggers the electron menu, removing focus, and not sending `Enter` to the right place. Super frustrating!

So I agree; this issue can only be solved in Electron for me too.

**Comment by vavadik** [comment] 2020-09-08 12:28
A little trick for those who struggle with VS Code: set window.titleBarStyle option to 'custom' and the issue is gone.

**Comment by Sarbinski** [comment] 2020-09-08 13:04
> A little trick for those who struggle with VS Code: set window.titleBarStyle option to 'custom' and the issue is gone.

Thank you for this, now somebody to give a solution for Slack :100:

**Comment by electron-triage** [comment] 2021-03-10 21:12
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Closed by electron-triage** 2021-03-10 21:12 UTC
Labels: 2-0-x, 3-0-x, 4-2-x, 6-1-x, bug :beetle:, platform/linux, version/1.7.x, version/1.8.x

**Comment by protist** [comment] 2021-03-11 03:22
The similar issue #22213 was also closed by the bot. The new issue is #28088.
