### ISSUE TITLE
Exit code 3221225477 - IsSandboxedProcess / GetHandleVerifier

### ISSUE THREAD

**Issue by MatthiasSchmalz** [electron/electron#13772] opened 2018-07-23 15:58 UTC
* Electron Version: 2.0.5
* Operating System (Platform and Version): Windows 10 64bit 1607
* Node version: v8.11.3
* Last known working Electron version: Unknown

**Expected Behavior**
No crash occurs

**Actual behavior**
Electron crashes with following backtrace:
````
	IsSandboxedProcess [0x00007FF68EEE8C86+611526]
	IsSandboxedProcess [0x00007FF68EEC61E2+469538]
	IsSandboxedProcess [0x00007FF68F94AC2C+11498604]
	IsSandboxedProcess [0x00007FF68EEC39E4+459300]
	IsSandboxedProcess [0x00007FF68EEC11AC+449004]
	IsSandboxedProcess [0x00007FF68EEC0ACB+447243]
	IsSandboxedProcess [0x00007FF68EEC12A9+449257]
	GetHandleVerifier [0x00007FF68ECCD75C+17855308]
	GetHandleVerifier [0x00007FF68ED3435A+18276170]
	IsSandboxedProcess [0x00007FF68EE9DAD4+303892]
	IsSandboxedProcess [0x00007FF68EE70E58+120472]
	GetHandleVerifier [0x00007FF68DC38115+466181]
	GetHandleVerifier [0x00007FF68DBEFE55+170565]
	GetHandleVerifier [0x00007FF68DBF0943+173363]
	GetHandleVerifier [0x00007FF68DC38681+467569]
	GetHandleVerifier [0x00007FF68DC382F4+466660]
	GetHandleVerifier [0x00007FF68DBEA9FF+148975]
	IsSandboxedProcess [0x00007FF68EFCFF88+1558472]
	IsSandboxedProcess [0x00007FF68EFD1366+1563558]
	IsSandboxedProcess [0x00007FF68F1A5412+3480658]
	IsSandboxedProcess [0x00007FF68F4347F8+6164536]
	IsSandboxedProcess [0x00007FF68F165DFD+3221053]
	IsSandboxedProcess [0x00007FF68F165CF0+3220784]
	IsSandboxedProcess [0x00007FF68FED11BE+17291774]
	GetHandleVerifier [0x00007FF68ECB1540+17740080]
	(No symbol) [0x00007FF68D9CBC85]
	IsSandboxedProcess [0x00007FF6904C5BD3+23536659]
	BaseThreadInitThunk [0x00007FFEC3F48364+20]
	RtlUserThreadStart [0x00007FFEC6A1E821+33]
````

**To Reproduce**
Create a simple Electron project which opens the following index.html:
````
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <style>.hide {display:none;}</style>
  </head>
  <body>
		<div>
			<button onclick="toggleBcp()" type="button" >Toggle</button>
		</div>
		<span id="container" style="height:100%;" class="">
			<webview id="bcp" src=""  width="100%" style="height:100%;"></webview>
		</span>
</body>
  <script>
	$ = require('./bootstrap/jquery-3.2.1.min.js');
  
	function toggleBcp() {
		$( "#container" ).toggleClass( "hide" );
	}

  </script>
</html>
````
Run the app and click the button twice.

**Additional Information**
This sample is extremly simplified. Clicking the button will cause the Web View to be hidden and afterwards to be shown again. At that time it does not have content loaded.
This seems to be similar to https://github.com/electron/electron/issues/9646 which has no longer be reproducible with Electron 1.7.8. and got closed a while ago.

**Comment by sofianguy** [comment] 2019-08-09 00:15
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:38
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:38 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows

**Comment by rush2arjun** [comment] 2020-09-01 15:51
Hi Team,

Electron Version - 2.0.2
Operating System: Windows 10 64bit
Node version: 12.17.0

I am facing similar kind of error, electron is creating more then 30 processes due to which CPU usage is very high

Below screen shot shows multiple processes created by electron,
![image](https://user-images.githubusercontent.com/7426061/91874800-4a107c80-ec98-11ea-86bd-1a0ec4b51717.png)

Also, below is the backtrack,
ntoskrnl.exe!KeSynchronizeExecution+0x5b46
ntoskrnl.exe!KeWaitForSingleObject+0x1c2d
ntoskrnl.exe!KeWaitForSingleObject+0xab4
ntoskrnl.exe!KeWaitForSingleObject+0x255
ntoskrnl.exe!RtlClearBitsEx+0x15a7
ntoskrnl.exe!KeWaitForSingleObject+0x3828
ntoskrnl.exe!KeSynchronizeExecution+0x3120
ntdll.dll!RtlGetCurrentServiceSessionId+0xba8
ntdll.dll!RtlFreeHeap+0x51
ucrtbase.dll!free_base+0x1b
CTI-Endpoint.exe!GetHandleVerifier+0x9ac58
CTI-Endpoint.exe!GetHandleVerifier+0xe1c134
CTI-Endpoint.exe!GetHandleVerifier+0xe1cfaf
CTI-Endpoint.exe!GetHandleVerifier+0xe1c4d5
CTI-Endpoint.exe!GetHandleVerifier+0xe1bc85
CTI-Endpoint.exe!GetHandleVerifier+0xea3195
CTI-Endpoint.exe!GetHandleVerifier+0x121ea75
CTI-Endpoint.exe!IsSandboxedProcess+0x3b746a
CTI-Endpoint.exe!GetHandleVerifier+0x11c6640
CTI-Endpoint.exe!IsSandboxedProcess+0x16769d0
CTI-Endpoint.exe!IsSandboxedProcess+0x9c58f
CTI-Endpoint.exe!IsSandboxedProcess+0x3139ca
CTI-Endpoint.exe!IsSandboxedProcess+0x1dad3
CTI-Endpoint.exe!IsSandboxedProcess+0x1c631
CTI-Endpoint.exe!IsSandboxedProcess+0x3139ca
CTI-Endpoint.exe!IsSandboxedProcess+0xa4999
CTI-Endpoint.exe!IsSandboxedProcess+0xa4784
CTI-Endpoint.exe!GetHandleVerifier+0x35ea6
CTI-Endpoint.exe!IsSandboxedProcess+0x3cdea9
CTI-Endpoint.exe!IsSandboxedProcess+0x3cd704
CTI-Endpoint.exe!IsSandboxedProcess+0x3cdfa2
CTI-Endpoint.exe!GetHandleVerifier+0x71d35
CTI-Endpoint.exe!GetHandleVerifier+0x29a45
CTI-Endpoint.exe!GetHandleVerifier+0x2a533
CTI-Endpoint.exe!GetHandleVerifier+0x722a1
CTI-Endpoint.exe!GetHandleVerifier+0x71f14
CTI-Endpoint.exe!GetHandleVerifier+0x245ef
CTI-Endpoint.exe!IsSandboxedProcess+0x16f348
CTI-Endpoint.exe!IsSandboxedProcess+0x170716
CTI-Endpoint.exe!IsSandboxedProcess+0x321ed2
CTI-Endpoint.exe!IsSandboxedProcess+0x5d50e8
CTI-Endpoint.exe!IsSandboxedProcess+0x30725d
CTI-Endpoint.exe!IsSandboxedProcess+0x307150
CTI-Endpoint.exe!IsSandboxedProcess+0x107d91e
CTI-Endpoint.exe!GetHandleVerifier+0x10eb5a0
CTI-Endpoint.exe+0xdbc85
CTI-Endpoint.exe!IsSandboxedProcess+0x1673333
KERNEL32.DLL!BaseThreadInitThunk+0x14

Request to please help in resolving this issue.
