### ISSUE TITLE
Electron 1.2.4 doesn't boot on Ubuntu 16.04 x64 with system node.

### ISSUE THREAD

**Issue by envygeeks** [electron/electron#6191] opened 2016-06-22 22:07 UTC
## Description

When trying to boot an electron application with electron command (directly or indirectly) electron does not boot the app, it simply exits without word, reason or logs, there are no exceptions thrown, there are no logs output, there is no indication of what is actually happening.  This was initially discovered when our tests started timing out and the ChromeDriver logs also have no details of what is going on.

* Operating system: Ubuntu 16.04 x64.
* Electron version: v1.2.4

```
doctor@who ~/development/envygeeks/easy-electron-base (master +) → 
node_modules/.bin/electron app/entry.js --enable-logging --debug --verbose
```

1. Window does not load.
1. Contents:
    ```js
require("babel-register")
require("./win")

    ```
1. Contents of win.js:
    ```js
import Config from "./config"
import { default as electron, BrowserWindow } from "electron"
import AppMenu from "./menu"
import Dev from "./dev"

// --

let mainWindow
const app = electron.app
const config = global.appConfig = new Config(app)
new AppMenu(app, config).enable()

/*
 * Create the main application window.
 */
function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    minWidth: 1024,
    minHeight: 768,
    height: 720
  })

  // So that electron-connect doesn't disrupt.
  if (config.nodeEnv == "development")
    mainWindow.minimize()

  mainWindow.loadURL(`file://${__dirname}/index.html`)
  mainWindow.on("closed", () => mainWindow = null)
  new Dev(config, BrowserWindow, mainWindow).
    possiblyEnable()
}

// --

app.on("ready", createWindow)
app.on("activate", () => {
  if (mainWindow === null) {
    createWindow()
  }
})

// --

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    config.saveUserConfig(() => {
      app.quit()
    })
  }
})
    ```

## Important Notes:

* This does not happen on v1.2.2 (installed system-wide) or v1.2.3 (what it was before an hour ago).
* We have not tested this on macOS or Windows and have only tested on Fedora and Ubuntu.

**Comment by kevinsawicki** [comment] 2016-06-22 22:11
This appears to be a duplicate of #6178

**Closed by kevinsawicki** 2016-06-22 22:11 UTC

**Comment by envygeeks** [comment] 2016-06-22 22:44
Didn't notice it, thanks for pointing me there!
