### ISSUE TITLE
After <webview>.clearHistory(), <webview>.canGoBack() reports false after navigating

### ISSUE THREAD

**Issue by nous-** [electron/electron#12147] opened 2018-03-06 21:41 UTC
index.html contents:
```
<webview src="https://google.com" style="position:absolute; top:0; left:0; right:0; bottom:0; display:inline-flex !important;" >
```

Steps:
1. Open `BrowserWindow` to `index.html`, which navigates to google
2. Perform a search to generate history
3. In development console: `document.querySelector('webview').canGoBack()` is `true`
4. In development console: `document.querySelector('webview').clearHistory()`
5. In development console: `document.querySelector('webview').canGoBack()` is `false`
6. Click on a search result link to generate history
7. In development console: `document.querySelector('webview').canGoBack()` is `false`

Step 7, canGoBack() reports false, where it should report true.

Electron version: 1.8.2
Operating system: OSX High Sierra 10.13.1 (17B1003)

**Comment by codebytere** [comment] 2018-03-07 03:07
Seems there's some upstream chatter about this: https://bugs.chromium.org/p/chromium/issues/detail?id=794020

**Comment by nous-** [comment] 2018-03-07 12:12
@codebytere Thanks for looking. Don't know if your link is mobile specific, or even along the same code path.  clearHistory(), navigate, canGoBack() == false seems pretty vanilla.

**Comment by nous-** [comment] 2018-03-08 10:04
Flipping through some source:

Unlikely upstream issue, `navigation-controller.js` is an electron's mirror of Chromium's NavigationController. See the comments in this file.

In the `NavigationController` constructor: 
```
this.clearHistory()

// webContents may have already navigated to a page.
if (this.webContents._getURL()) {
  this.currentIndex++
  this.history.push(this.webContents._getURL())
}
```

`clearHistory()` sets various indexes to `-1`. This block above increments currentIndex to `0` (still `canGoBack() == false`). Then on navigation, I'm guessing `currentIndex` is incremented again to `1`, which would result with `canGoBack() == true` as `this.getActiveIndex() > 0`.

This conditional block above should probably be moved to `clearHistory()`.

Didn't debug or walk all these statements. Need to see about setting up a dev environment for electron.

**Comment by sofianguy** [comment] 2019-01-07 21:45
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:41
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-01-15 20:41 UTC
Labels: blocked/need-info, bug :beetle:, platform/macOS, version/1.8.x

**Comment by dko-slapdash** [comment] 2019-10-31 00:33
FYI for googlers, the issue seems to be not fixed an the moment.

My work-arounds is the following:
```
webContents.clearHistory();
webContents.executeJavaScript("history.pushState({}, '', location.href)");
```
