### ISSUE TITLE
[Feature Request]: Electron apps each bring shared libraries that could be provided by OS or browser

### ISSUE THREAD

**Issue by elosha** [electron/electron#35784] opened 2022-09-23 10:10 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron is carrying a load of libs + a browser engine that is native to most modern operating systems – either being included in the OS itself (MacOS/iOS, Windows) or installed in form of a separate Webkit (Chromium/Chrome) browser.

(At least on Mac OS) All of this is deployed over and over with each Electron app: MS Teams, Figma, etc.. Electron apps could be lightweight, but instead wasting FS space and RAM by leading the concept of shared libraries ad absurdum.

### Proposed Solution

Wherever possible, use the native browsing engine and libraries by default. If not: Install a runtime containing missing libraries (like a WebKit engine, Swift runtime) if needed.

### Alternatives Considered

Running Electron apps as webapps in a native browser.

**Comment by Prinzhorn** [comment] 2022-09-23 14:29
Somewhat duplicate of https://github.com/electron/electron/issues/673 and https://github.com/electron/electron/issues/28604

**Comment by MarshallOfSound** [comment] 2022-09-23 19:33
Duplicate of #673

**Closed by MarshallOfSound** 2022-09-23 19:33 UTC
Labels: enhancement :sparkles:
