### ISSUE TITLE
[Bug]: Browserwindow.isMaximized() return an error boolean value.

### ISSUE THREAD

**Issue by aristocracy** [electron/electron#34606] opened 2022-06-17 03:17 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### What arch are you using?

x64

### Last Known Working Electron version

19.0.4

### Expected Behavior

First time click the minSize button to change window small(**BrowerWindow.setSize(331,40)**) not minisize and then click again to minisize the window.
After I first time click the minSize button, I click the maxSize button to restore(**BrowerWindow.setSize(720,386)**) the window and click again to maxsize the window(**BrowserWindow.getFocusedWindow().maximize()**).
I was confused why the `BrowserWindow.getFocusedWindow().isMaximized()` always return **false**, it should be ture or false.

### Actual Behavior

The default `BrowserWindow.getFocusedWindow().resizable` value is **true**. After I setSize the window, `BrowserWindow.getFocusedWindow().isMaximized()` always return **false**, the below code is where the exception happen
ipcMain.handle('minumWin', () => {
  if (BrowserWindow.getFocusedWindow().resizable) {
    BrowserWindow.getFocusedWindow().setSize(331, 40, true);
    BrowserWindow.getFocusedWindow().center();
    BrowserWindow.getFocusedWindow().resizable = false;
  } else {
    BrowserWindow.getFocusedWindow().minimize();
  }
});
ipcMain.handle('maxWin', (event) => {
  if (BrowserWindow.getFocusedWindow().resizable) {
    BrowserWindow.getFocusedWindow().maximizable = true;
    **BrowserWindow.getFocusedWindow().isMaximized() ? BrowserWindow.getFocusedWindow().restore() : BrowserWindow.getFocusedWindow().maximize();**
    event.sender.send('winStatus', BrowserWindow.getFocusedWindow().isMaximized());
  } else {
    BrowserWindow.getFocusedWindow().resizable = true;
    BrowserWindow.getFocusedWindow().setSize(720, 486, true);
    BrowserWindow.getFocusedWindow().center();
  }
});

**Comment by codebytere** [comment] 2022-06-17 13:55
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed** 2022-06-28 14:09 UTC
Labels: bug :beetle:, blocked/need-repro
