### ISSUE TITLE
Hard crashes on OSX and Windows

### ISSUE THREAD

**Issue by bootrino** [electron/electron#11157] opened 2017-11-18 00:21 UTC
Hi folks,

I'm getting hard crashes in Electron.

I'm running 1.8.2 beta

Sorry but I just don't have any idea how to diagnose.  I thought it was because of https://github.com/electron/electron/issues/10651 because I also use the aws-sdk and the google sdk but using the 1.8.2 beta has not fixed it so now I'm completely lost and don't know how to proceed to diagnose/resolve. 

UPDATE: it still seems to crash even if I avoid the aws code
UPDATED #2: downgrading electron to 1.6.15 appears to have fixed it.

The crashes don't happen at the same point and seems to return different crash messages so I can't seem to nail it down to some particular thing.

Happy to provide more information if someone can suggest what would be helpful.

Versions shown in screenshot here:

![screen shot 2017-11-18 at 11 15 52 am](https://user-images.githubusercontent.com/22624099/32974415-fb09e27a-cc51-11e7-8756-07a104ab5815.png)

```
[35223:1118/111225.252117:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1.
0   Electron Framework                  0x000000010baa8d3c crashpad::CloseMultipleNowOrOnExec(int, int) + 970204
1   Electron Framework                  0x000000010ba70553 crashpad::CloseMultipleNowOrOnExec(int, int) + 738803
2   Electron Framework                  0x000000010ba87fb1 crashpad::CloseMultipleNowOrOnExec(int, int) + 835665
3   Electron Framework                  0x000000010e72584c crashpad::CloseMultipleNowOrOnExec(int, int) + 47618284
4   libnode.dylib                       0x0000000110162021 v8::internal::DeferredHandles::Iterate(v8::internal::ObjectVisitor*) + 19633
5   libnode.dylib                       0x0000000110161f46 v8::internal::DeferredHandles::Iterate(v8::internal::ObjectVisitor*) + 19414
6   libnode.dylib                       0x0000000110402c89 v8::internal::Heap::CreateFillerObjectAt(unsigned char*, int, v8::internal::ClearRecordedSlots) + 16233
7   libnode.dylib                       0x00000001103ff417 v8::internal::Heap::CreateFillerObjectAt(unsigned char*, int, v8::internal::ClearRecordedSlots) + 1783
8   libnode.dylib                       0x00000001103fe813 v8::internal::DeferredHandleScope::Detach() + 110595
9   libnode.dylib                       0x000000011080dd72 v8::internal::ScavengeJob::IdleTask::RunInternal(double) + 466
10  Electron Framework                  0x000000010e6e58c8 crashpad::CloseMultipleNowOrOnExec(int, int) + 47356264
11  Electron Framework                  0x000000010e71dedd crashpad::CloseMultipleNowOrOnExec(int, int) + 47587197
12  Electron Framework                  0x000000010e6bc031 crashpad::CloseMultipleNowOrOnExec(int, int) + 47186129
13  Electron Framework                  0x000000010e6bc53f crashpad::CloseMultipleNowOrOnExec(int, int) + 47187423
14  Electron Framework                  0x000000010bab98c1 crashpad::CloseMultipleNowOrOnExec(int, int) + 1038689
15  Electron Framework                  0x000000010e6c6e2f crashpad::CloseMultipleNowOrOnExec(int, int) + 47230671
16  Electron Framework                  0x000000010e6c4e82 crashpad::CloseMultipleNowOrOnExec(int, int) + 47222562
17  Electron Framework                  0x000000010bab98c1 crashpad::CloseMultipleNowOrOnExec(int, int) + 1038689
18  Electron Framework                  0x000000010ba81c7b crashpad::CloseMultipleNowOrOnExec(int, int) + 810267
19  Electron Framework                  0x000000010ba81fcc crashpad::CloseMultipleNowOrOnExec(int, int) + 811116
20  Electron Framework                  0x000000010ba82383 crashpad::CloseMultipleNowOrOnExec(int, int) + 812067
21  Electron Framework                  0x000000010ba8580a crashpad::CloseMultipleNowOrOnExec(int, int) + 825514
22  Electron Framework                  0x000000010ba349ca crashpad::CloseMultipleNowOrOnExec(int, int) + 494186
23  Electron Framework                  0x000000010ba8522f crashpad::CloseMultipleNowOrOnExec(int, int) + 824015
24  CoreFoundation                      0x00007fffa84dd321 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
25  CoreFoundation                      0x00007fffa84be21d __CFRunLoopDoSources0 + 557
26  CoreFoundation                      0x00007fffa84bd716 __CFRunLoopRun + 934
27  CoreFoundation                      0x00007fffa84bd114 CFRunLoopRunSpecific + 420
28  Foundation                          0x00007fffa9ed0252 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 277
29  Electron Framework                  0x000000010ba85eae crashpad::CloseMultipleNowOrOnExec(int, int) + 827214
30  Electron Framework                  0x000000010ba8566c crashpad::CloseMultipleNowOrOnExec(int, int) + 825100
31  Electron Framework                  0x000000010ba8194e crashpad::CloseMultipleNowOrOnExec(int, int) + 809454
32  Electron Framework                  0x000000010ba9aa83 crashpad::CloseMultipleNowOrOnExec(int, int) + 912163
33  Electron Framework                  0x000000010c3ea51c crashpad::CloseMultipleNowOrOnExec(int, int) + 10675644
34  Electron Framework                  0x000000010bc56f8b crashpad::CloseMultipleNowOrOnExec(int, int) + 2732075
35  Electron Framework                  0x000000010d719bc8 crashpad::CloseMultipleNowOrOnExec(int, int) + 30792808
36  Electron Framework                  0x000000010bc561e4 crashpad::CloseMultipleNowOrOnExec(int, int) + 2728580
37  Electron Framework                  0x000000010b830eca AtomMain + 74
38  Electron Helper                     0x000000010b828f26 main + 38
39  libdyld.dylib                       0x00007fffbdc45235 start + 1
40  ???                                 0x0000000000000011 0x0 + 17
```

**Comment by jameseggers** [comment] 2017-11-28 12:17
I have this issue too, only fixed by downgrading. It occurs when I use Pusher's js library. Any idea as to the cause?

**Comment by zcbenz** [comment] 2017-12-26 07:14
I'm merging this to #11457.

**Closed by zcbenz** 2017-12-26 07:14 UTC
Labels: fixme/crash, version/1.8.x
