### ISSUE TITLE
Memory leaks when changing window size in offscreen mode

### ISSUE THREAD

**Issue by yotamlaufer** [electron/electron#8051] opened 2016-11-22 12:19 UTC
* Electron version: 1.4.7
* Operating system: Mac OS 10.11.6 & Ubuntu 14.04

### Expected behavior

Garbage collector should clean memory.

### Actual behavior

Memory usage increases rapidly in Main process. Eventually app performance will degrade until unusable.

### How to reproduce

```js
const path = require('path');
const {app, BrowserWindow} = require('electron');
app.disableHardwareAcceleration();

app.once('ready', () => {
  const win = new BrowserWindow({
    width: 4096,
    height: 3072,
    useContentSize: true,
    enableLargerThanScreen: true,
    show: false,
    frame: false,
    hasShadow: false,
    transparent: true,
    webPreferences: {
      devTools: false,
      webSecurity: false,
      textAreasAreResizable: false,
      defaultEncoding: 'utf8',
      backgroundThrottling: false,
      offscreen: true,
      zoomFactor: 1,
      experimentalFeatures: false,
      experimentalCanvasFeatures: false
    }
  });

  let index = 0;
  const sizes = [
    {width: 1024, height: 768},
    {width: 2048, height: 1536},
    {width: 4096, height: 3072}
  ];

  win.loadURL('https://www.apple.com');
  win.webContents.setFrameRate(60);
  win.webContents.once('dom-ready', () => {
    setInterval(() => {
      if (index === sizes.length) {
        index = 0;
      }
      const size = sizes[index++];

      // changing the window size causes the memory leak
      win.setSize(size.width, size.height, false);
    }, 100);
  })
});

```

**Comment by liusy182** [comment] 2016-12-07 06:53
Correct me if I am wrong. I think the memory leak is caused by `NativeImage` created in [`webContents.onPaint`](https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_web_contents.cc#L1394) not garbage collected.

**Comment by yotamlaufer** [comment] 2016-12-07 16:13
@liusy182 I'm actually not sure about that. In the included code there's no reference to paint events.

**Comment by liusy182** [comment] 2016-12-07 23:00
@yotamlaufer if you trace the code path, each `setSize` triggers `Resize` which in turn triggers `onPaint` event. Since `NativeImage` is not directly created from JavaScript, based on my limited knowledge I am deducing that garbage collection does not happen.

**Comment by zcbenz** [comment] 2017-04-11 05:37
This is a duplicate of  #7350.

**Closed by zcbenz** 2017-04-11 05:37 UTC
Labels: component/offscreen, fixme/bug, in progress
