### ISSUE TITLE
General overall speed of electron based products

### ISSUE THREAD

**Issue by denysvitali** [electron/electron#5672] opened 2016-05-24 07:57 UTC
Hi everyone,
I opened this issue to discuss about the actual speed of electron based applications.

I myself do really like Atom Text Editor and Electron based applications, but I feel like they're really heavy, even tough I do have a fast computer.
When compared to native solutions electron based applications are really, really much slower. At least in Linux.

I'm not here to blame the developers of this awesome framework, but instead putting my efforts to help optimizing it to reach native speeds [as NativeScript is doing with mobile apps](https://www.youtube.com/watch?v=YzaTuxpk5Cc&feature=youtu.be).
At the moment I do feel like running any electron based app is glitchy and really, really heavy / slow.

I do not have made actual comparison between for example Sublime Text and Atom, but I think that anybody can confirm by doing a comparison that actually an Electron based app is really cool, but slow.

I just found [this comparison on YouTube](https://www.youtube.com/watch?v=VugTuB2msts) that shows how slow Atom is compared to Sublime Text.
Maybe [this](https://www.youtube.com/watch?v=K43JvJfAjOg) could give an idea of what I'm talking about.

Again, I opened this issue not to blame about the electron framework, but instead to find a way to optimize it, discuss about these speed problems and find a way to make it feel less heavy to run.

Btw, electron is just awesome, keep up the good work!

**Comment by sedwards2009** [comment] 2016-05-25 10:19
@denysvitali The general speed of Electron is highly dependent on the upstream project Blink which is the "guts" of the Google Chrome browser and also Electon. Electron itself doesn't have much control over how the guts works, also Electron most likely doesn't have much negative impact either.

Also note that you are assuming that the speed difference between native apps and Electron based apps is purely dependent on Electron itself. How the apps which run on Electron are designed and written has a huge impact on their performance.

Sublime text for example can, and probably does, do its own lay out and rendering of text into the window. Electron based apps could also do this by using the Canvas API or even WebGL, but generally they don't. They use HTML and CSS for layout and rendering because this way they can also get a lot of functionality for "free". It is a big trade off of course.

**Comment by mnquintana** [comment] 2016-05-25 15:20
This has much more to do with how individual Electron-based apps are written than it does Electron itself. Yes, DOM operations can be very slow, and Electron UIs are (generally) written with DOM APIs. But, they don't *have* to be slow, at least not perceptibly – if you find Electron apps that seem slow, that means they made design choices that traded off speed / responsiveness for something else. In Atom's case, the tradeoff was for hackability – it's way easier for people to write packages and hacks when they have the whole DOM available to them (instead of Canvas or something, which Atom's editor could've been built to use instead). And even still, Atom isn't *stuck* in its current state – there are still plenty of optimizations left to make that can make it much, much faster, even while using the DOM.

IMO the best way to improve performance in Electron itself, if you're still interested in that, would be to contribute back to Chromium / Blink upstream like @sedwards2009 mentioned, since that is entirely responsible for rendering all visible UI in an Electron app (among a lot of other things).

Speed isn't an inherent limitation of Electron though. If you prioritize it, you can get native-like performance and responsiveness in Electron.

**Comment by feross** [comment] 2016-05-27 03:46
In my experience, the biggest cause of slow app startup is having too many `require()` calls at the top of your `main.js`.

By design, `require()` is synchronous. And it can touch lots of files on the filesystem. If your users have a spinning disk drive, then all the random accesses will kill your startup time. You can improve the situation by bundle your app with ASAR, so only one file needs to be read.

Another huge win, is to optimize the order that you `require()` files. By lazy loading as much as possible, we were able to get [WebTorrent Desktop](https://webtorrent.io/desktop) to under 500ms startup time on a Macbook 12" (basically a netbook with an SSD).

It is possible to build fast apps with Electron, but you have to be ruthless about lazy loading, and choosing small, focused modules over huge framework modules. I think of it as similar to developing for mobile -- you want to parse as little JavaScript as possible before your app window shows up.

**Comment by zcbenz** [comment] 2016-06-14 05:57
I'm closing this since it has been perfectly answered.

**Closed by zcbenz** 2016-06-14 05:57 UTC
Labels: discussion

**Comment by Fishrock123** [comment] 2016-07-15 09:47
I'm not certain that is the end of the story here.

Please see `cachedData` parameter of the VM module. the https://nodejs.org/dist/latest-v6.x/docs/api/vm.html#vm_new_vm_script_code_options

It is now possible to have V8 use pre-JIT'd (compiled, or byte-coded, not sure which) code. Chromium uses that technique to speed up it's startup time.

I believe we may also use that now in Node.js for core modules.


--

I'm not exactly sure how that could be applied here, but it should be possible as part of a bundling step, I think.

cc @indutny who helped implement usage of it in Node.

**Comment by Acidic9** [comment] 2018-02-17 17:43
I just used this C++ benchmark code as a standalone executable, and as a node extension for an electron app.

Standalone executable result:
**`-0.169059907`**

Electron C++ node addon:
**`-0.169059906`**

As you can see, the numbers are almost identical benchmark times, only the last digit is one lower, which in this case is next to no difference.

I know very little about benchmarking and all, I just did this test on my PC and thought I'll share the results.

**Comment by JoshuaKGoldberg** [comment] 2018-02-21 22:27
This issue comes up near-first on Google searches. Can someone post links to the relevant Blink discussions/issues for tracking?
