### ISSUE TITLE
Use babel-register with ELECTRON_RUN_AS_NODE makes process exit late

### ISSUE THREAD

**Issue by zhm** [electron/electron#4944] opened 2016-03-29 23:21 UTC
- Electron version: 0.37.2 + 0.36.12
- Operating system: OS X 10.11.4 (15E65)

The process doesn't seem to exit like `node` does. I've reduced it to something `babel-register` is doing. I'm not sure if this is a bug within babel or electron, so feel free to close this if it's a bug with babel. It's the same behavior on both 0.37.2 and 0.36.12.

``` sh
# works properly, does nothing and exits
node -e "require('babel-register')"

# hangs forever until you ctrl+c
ELECTRON_RUN_AS_NODE=true node_modules/.bin/electron -e "require('babel-register')"
```

A complete test:

``` sh
mkdir electron-node-hang
cd electron-node-hang
npm init -y
npm install electron-prebuilt babel-register --save
ELECTRON_RUN_AS_NODE=true node_modules/.bin/electron -e "require('babel-register')"
```

**Comment by zcbenz** [comment] 2016-03-31 13:34
This is essentially a duplicate of #4265 and should have been fixed by #4927, the fix will be included in next release.

**Comment by zhm** [comment] 2016-04-04 13:12
This still seems to be happening with 0.37.4. It actually _does_ exit, but it takes over 30 seconds.

**Comment by zcbenz** [comment] 2016-04-07 08:14
Yeah `npm` works now but `babel-register` still has problems.

**Comment by OutsourcedGuru** [comment] 2017-02-27 19:00
I've read the suggestions here about babel-register and the related bug.  It was mentioned that the spawned process eventually exits after 30 seconds but I'm not finding this.

* Run "electron.exe"
![threeprocesses](https://cloud.githubusercontent.com/assets/15971213/23374864/e88038a8-fcda-11e6-89ff-902f5c05ae91.png)
* Close the application
* At this point, the command prompt hasn't returned.  
![threeprocesses-still](https://cloud.githubusercontent.com/assets/15971213/23374867/edf3cd5e-fcda-11e6-8f95-23783ef85b23.png)
![stuckprocess](https://cloud.githubusercontent.com/assets/15971213/23375003/8bec210a-fcdb-11e6-8b0a-cfda50ae05ae.png)

What's interesting is that a couple of these processes are still active.  I just let them sit for well over five minutes and they didn't timeout and die as suggested by some of the comments.

It requires an additional Ctrl-C to close the three open processes.

* npm version 3.10.10
* Windows 7 Professional 64-bit
* electron-v1.4.15-win32-x64.zip

**Comment by codebytere** [comment] 2018-01-30 03:30
We are no longer implementing bugfixes for versions of Electron < `1.6.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Closed by codebytere** 2018-01-30 03:30 UTC
Labels: component/node-integration, fixme/bug
