### ISSUE TITLE
[Bug]: GitHub issue tags do not get updated when updating description

### ISSUE THREAD

**Issue by nikwen** [electron/electron#43498] opened 2024-08-29 00:13 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sonoma 14.6

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

When the author of a GitHub issue updates its description, the assigned tags (e.g. Electron version or `has-repro-gist`) get updated.

### Actual Behavior

Currently, the tags do not seem to get updated.

Examples:

- https://github.com/electron/electron/issues/43041 – OP updated the Electron version. The tags are still on `blocked/need-info ❌` and the previous Electron version.
- https://github.com/electron/electron/issues/43498 (this issue) — I created it with Electron version 31.4.0, then updated the description to 32.0.0. The tag is still `31-x-y`.

**Comment by Vsangg1** [comment] 2024-08-31 00:09
> ### Preflight Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.
> 
> ### Electron Version
> 32.0.0
> 
> ### What operating system(s) are you using?
> macOS
> 
> ### Operating System Version
> macOS Sonoma 14.6
> 
> ### What arch are you using?
> arm64 (including Apple Silicon)
> 
> ### Last Known Working Electron version
> _No response_
> 
> ### Expected Behavior
> When the author of a GitHub issue updates its description, the assigned tags (e.g. Electron version or `has-repro-gist`) get updated.
> 
> ### Actual Behavior
> Currently, the tags do not seem to get updated.
> 
> Examples:
> 
> * [[Bug]: MacBook M1 chip with macOS Sonoma version 14.5 SVG blurry #43041](https://github.com/electron/electron/issues/43041) – OP updated the Electron version. The tags are still on `blocked/need-info ❌` and the previous Electron version.
> * [[Bug]: GitHub issue tags do not get updated when updating description #43498](https://github.com/electron/electron/issues/43498) (this issue) — I created it with Electron version 31.4.0, then updated the description to 32.0.0. The tag is still `31-x-y`.
> 
> ### Testcase Gist URL
> _No response_
> 
> ### Additional Information
> _No response_

Duplicate of #

**Comment by dsanders11** [comment] 2024-09-04 16:17
Hi @nikwen, thanks for opening an issue. I don't really consider this to be a bug - the auto-labeling that happens on issue open is meant to be some lightweight automation to help out maintainers, but it is not meant to be exhaustive. Specifically, once an issue is open the description can be edited by a user to be anything they want, so a lot of assumptions about how the description is structured would no longer be true. We'll continue to rely on our maintainers to manage the labels on issues after the initial auto-labeling.

**Closed by dsanders11** 2024-09-04 16:17 UTC
Labels: platform/macOS, bug :beetle:, 31-x-y

**Comment by nikwen** [comment] 2024-09-04 17:09
Hi @dsanders11, thanks for sharing! What's the best way to get labels updated on issues where maintainers haven't done it yet?
