### ISSUE TITLE
Binary data gets corrupted after injecting with protocol.interceptHttpProtocol

### ISSUE THREAD

**Issue by winamp** [electron/electron#8558] opened 2017-02-01 23:32 UTC
* Electron version: 1.5.0
* Operating system: Linux Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

### Expected behavior
binary data passed through callback uploadData.data gets uploaded as-is

### Actual behavior
binary data gets corrupted

### How to reproduce
1. clone https://github.com/winamp/electron-binary-issue
2. npm install
3. npm start

It creates simple web server on 8085 port, serves simple web form.
Upon click on submit button, electron intercepts POST http request, injects binary data into uploadData and sends it. Server side parses the request via [formidable](https://github.com/felixge/node-formidable), compares each byte of received data with original and responds with result (either corrupted or ok).

**Comment by deepak1556** [comment] 2017-02-02 15:33
Thanks for the test case. But I think this is most likely a misuse of formidable or a bug in it, depends on if the encoding of the data is maintained when written to the file. Replace `fileData` with the following,

```
const defaultEncodedFileData = fs.readFileSync(files.upload.path)
const fileData = Buffer.from(defaultEncodedFileData.toString(), 'binary')
```

Also tested with

```
// Replace upload data in http handler with:
resRequest.uploadData = {
  contentType: 'application/octet-stream',
  data: binaryData.toString('binary')
};

// replace /upload path handler with:
if (req.url == '/upload' && req.method.toLowerCase() == 'post') {
  let body = ''
  req.on('data', (data) => {
    if (data) {
      body += data
    }
  })
  req.on('end', () => {
    const equal = binaryData.equals(Buffer.from(body, 'binary'))
    res.writeHead(200, {'content-type': 'text/plain'});
    res.end(`Binary data is ${equal ? 'ok' : 'corrupted'}`);
  })
  return;
}
```

Closing since its not a bug in Electron. Also upload with custom protocol isn't much flexible for file uploads now, there is an issue tracking to enhance it https://github.com/electron/electron/issues/8503

**Closed by deepak1556** 2017-02-02 15:33 UTC
