### ISSUE TITLE
Code protection, again

### ISSUE THREAD

**Issue by craftpip** [electron/electron#9912] opened 2017-07-02 19:57 UTC
Not really an issue, 

I know this question has been asked a lot of times here, to compile javascript code into v8's snapshot. Which slows down the application by 50% - 30%. It was a wise option to not include it in electron,

However,
Recently NWjs published an article claiming to that the performance issue has been fixed.
https://nwjs.io/blog/js-src-protect-perf/

Quote from article: 
> compiled binary code now run as fast as JS source code without performance overhead. This brings 3x-4x improvement according to our test

Please give this another thought, Thanks!

**Comment by paulcbetts** [comment] 2017-07-03 00:01
Dupe of #2570, please subscribe there

**Closed by paulcbetts** 2017-07-03 00:01 UTC

**Comment by craftpip** [comment] 2017-07-08 07:47
Done, thanks 👍
