### ISSUE TITLE
Problem with Sequelize orm after Electron-forge package

### ISSUE THREAD

**Issue by e-sauvage** [electron/electron#26080] opened 2020-10-21 15:06 UTC
Hey Guys, 

i am getting some errors after running electron-forge package. 
My electronPackagerConfig is:

```
"asar": {
          "unpackDir": "{files/**/*, files/*}"
        }
```

In my files folder i have my sequelize db + models + migrations.
files/db/

```
let seatDefinitionsPath = path.join(app.getAppPath(),'files/db/models/seat_definition', 'seat_definitions.js');
  /**Add the Database Models**/
    fs
        .readdirSync(path.join(app.getAppPath(), 'files/db/models/seat_definition'))
        .filter(file =>
            (file.indexOf('.') !== 0) &&
            (file !== basename) &&
            (file.slice(-3) === '.js'))
        .forEach(file => {
          console.log(db_);
          let model = db_.seat_definition.import(seatDefinitionsPath);
          db_[model.name] = model;
        });

```

I am accessing my models like this at the beginning. 
If i run my code without unpacking i dont get this error.

The error i am getting is:

```
file-change-cache.js:255 Uncaught Error: Asked for C:\Users\e.kilic\Desktop\Development\electron\dummy-surveying\out\DummySurveying-win32-x64\resources\app.asar.unpacked\files\db\models\seat_definition\seat_definitions.js but it was not precompiled!
    at FileChangedCache.getHashForPathSync (file-change-cache.js:255)
    at CompilerHost.compileReadOnlySync (compiler-host.js:493)
    at CompilerHost.compileSync (compiler-host.js:414)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\e.kilic\Desktop\Development\electron\dummy-surveying\out\DummySurveying-win32-x64\resources\app.asar\node_modules\electron-compile\lib\require-hook.js:68:48)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at Sequelize.import (C:\Users\e.kilic\Desktop\Development\electron\dummy-surveying\out\DummySurveying-win32-x64\resources\app.asar\node_modules\sequelize\lib\sequelize.js:481)
    at fs.readdirSync.filter.forEach.file (global.js? [sm]:38)
    at Array.forEach (<anonymous>)
    at initDatabases (global.js? [sm]:37)
    at HTMLDocument.<anonymous> (index-nonav.js? [sm]:20)
    at j (jquery-2.1.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.1.1.min.js:2)
    at Function.ready (jquery-2.1.1.min.js:2)
    at HTMLDocument.I (jquery-2.1.1.min.js:2)

```
I can access the folder via readdirSync but the problem is with the import call on sequelize model. How can i fix this bug? I think something is caching or so or he is trying to cache something and can't access.

**Comment by ckerr** [comment] 2020-10-21 20:03
Hi @e-sauvage,

If this is a bug in electron-forge, you may want to report it at https://github.com/electron-userland/electron-forge/issues so that the Forge maintainers can track it there.

Also, if you're looking for general discussion on Electron tips & packaging etc with other Electron app developers, you may want to check out the new Discord server that was recently added at https://discord.com/invite/electron .

I hope this helps!

Since this doesn't appear to be a bug in Electron itself, though, I'm going to close this issue. If this is in error, please re-open a ticket and follow the issue template wrt what version of Electron you're using and, ideally, a repro gist that the Electron  users can use to reproduce the issue. Thanks!

**Closed by ckerr** 2020-10-21 20:03 UTC
