### ISSUE TITLE
error in electron@nightly Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"

### ISSUE THREAD

**Issue by jawadafghanistany** [electron/electron#15625] opened 2018-11-07 19:12 UTC
* Output of `node_modules/.bin/electron electron@nightly`:
* Operating System (Platform and Version): Debian GNU/Linux 9 (stretch) 64-bit (gnome version 3.22.2)
* Output of `node_modules/.bin/electron --version` on last known working Electron version : electron@2.0.5

**Expected Behavior**
i write below code : 
`const {app, BrowserWindow} = require(`electron`);`
`app.on(`ready`, () => {new BrowserWindow({ "width": 400, "height": 400});});`
expected behavior: show window and native menu

**Actual behavior**
but when the window is opened the fonts color is transparent (text-color of native menu is transparent)

**Screenshots**
![screenshot from 2018-11-07 22-32-20](https://user-images.githubusercontent.com/32559547/48154138-1d2df100-e2dd-11e8-8860-c31db485e264.png)

**reproduce**
https://github.com/jawadafghanistany/someeditor.git

**Additional Information**
i have the same problem in electron@3.0.7 
but before this versions i use electron@2.0.2, and in this version don't exists this problem

this is my font.conf: 
[fonts.txt](https://github.com/electron/electron/files/2558819/fonts.txt)

**Comment by jacobq** [comment] 2019-04-08 20:36
@jawadafghanistany I get the same warning mentioned in the this issue's title when I launch `google-chrome` (73.0.3683.103) on my Linux system (Debian 9.8 / kernel 4.9.0-8-amd64 with `fontconfig` 2.11.0-6.7+b1). I think that is caused by an upstream problem, separate from `electron` (see also https://unix.stackexchange.com/questions/504335/fontconfig-warning-etc-fonts-fonts-conf-line-100-unknown-element-blank). Also, it does not show up for me with electron 3.x (presumably because the chromium version is older). However, that is not what is causing the problem you describe.

The main problem with the code you shared is that the HTML file is not in the default location (see https://electronjs.org/docs/tutorial/first-app to learn more) and your script does not tell the `BrowserWindow` to load anything -- hence a blank / broken window. Since you went to the trouble of creating a reproduction repo I went ahead and [created a PR for you](https://github.com/jawadafghanistany/someeditor/pull/1/commits/ed52bc6ae0d623a683810322415a2f3dc32f3664) showing one way to correct the problem:

```js
const { app, BrowserWindow } = require(`electron`);

app.on(`ready`, () => {
    const win = new BrowserWindow({
        "width": 400,
        "height": 400
    });
    win.loadFile('assets/html/index.html'); // <---- tells the window what document to load
});

```

**Comment by sofianguy** [comment] 2019-08-09 22:35
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:13
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:13 UTC
Labels: 3-0-x, blocked/need-info ❌, bug :beetle:, platform/linux
