### ISSUE TITLE
Let multiple applications share core files without installing multiple copies of Electron

### ISSUE THREAD

**Issue by joshas** [electron/electron#6488] opened 2016-07-14 16:11 UTC
With electron getting more popular, there's an issue when user installs several apps using electron - each application will have same duplicate codebase, except actual app part.
I'd like to suggest to find a solution to this issue. E.g. provide electron core as separate library, so multiple apps could use it without eating a lot of disk space.

**Comment by enlight** [comment] 2016-07-14 17:56
See existing issue #673

**Comment by kevinsawicki** [comment] 2016-07-14 18:06
Closing as duplicate of #673 which is where the current discussion about this is happening.

**Closed by kevinsawicki** 2016-07-14 18:06 UTC
