### ISSUE TITLE
Dynamically linked libprotobuf.so.9

### ISSUE THREAD

**Issue by sla89** [electron/electron#13563] opened 2018-07-05 05:42 UTC
* Electron Version: since 2.x.x
* Operating System (Platform and Version): windows and linux
* Last known working Electron version: 1.8.7

**Expected Behavior**
Protobuf should always be statically linked.

**Actual behavior**
It seems that the `protobuf` library is statically linked into the windows executable and dynamically linked into the linux executable since `electron` version 2.x.x.

I took a look with a dependency walker on `electron.exe` (v2.0.3) and couldn't find `protobuf` as dependency. 

`ldd electron | grep proto` on the `electron` 1.8.7 executable shows no dependencies to `libprotobuf`:

```
sla89@sla89 ~/Downloads % ldd electron-v1.8.7-linux-x64/electron | grep proto
```

while doing the same on the `electron` 2.x.x executable shows the dynamic dependency to `libprotobuf`:

```
sla89@sla89 ~/Downloads % ldd electron-v2.0.3-linux-x64/electron | grep proto 
libmirprotobuf.so.3 => /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3 (0x00007f3504328000)
libprotobuf-lite.so.9 => /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9 (0x00007f3503a62000)
```

Maybe this was introduced by this commit: https://github.com/electron/electron/commit/7a23a79b5883661e134bba981ed96ead48c90618#diff-1d3ea6a4d036c2b34e8fdba461eb4daa

**How this affected me**
I have upgraded my `electron` version from 1.8.3 to 2.0.3 and now I am receiving the following error when I start my application:

```
[1] [libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.1.0 of the
Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you 
compiled the program yourself, make sure that your headers are from the same version of Protocol 
Buffers as your link-time library.
```

This error only occurs under linux. On windows everything still works as expected.
In my program I am using a library that is statically linked against `protobuf` 3.1.0. 

I couldn't find anything in the docs about this but maybe I was just blind.

**Comment by logidelic** [comment] 2019-06-14 17:16
Did you ever figure this out? Running into a similar issue (electron 5) but find it confusing since electron (same ver) does not seem to be linked to that library on another system.

**Comment by AlexxxRu** [comment] 2019-06-17 15:19
Absolutely same trouble. I have a native lib which using the protobuf statically. 
On the Linux Mint ldd doesn't show any protobuf dependencies, but with Ubuntu LTS I have this issue.

**Comment by electron-triage** [comment] 2020-02-19 20:19
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:20
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:20 UTC
Labels: 2-0-x, 5-0-x, blocked/need-info ❌, platform/linux, platform/windows
