### ISSUE TITLE
[Feature Request]: Make Main Process APIs Importable (alternative to the Context Bridge)

### ISSUE THREAD

**Issue by 7ombie** [electron/electron#33318] opened 2022-03-17 01:36 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, the correct way to expose Node functionality to the Renderer Process is via the Context Bridge, which just binds stuff to the `window` object, which is clunky.

Binding to the `window` object goes against everything we've been trying to accomplish with the adoption of ES6 modules (and everything we suffered for years before that, where every JS file was a giant closure). The Context Bridge is less bad than libraries sharing a global namespace, but it could easily clobber future additions to the `window` object still.

The current API also provides no means for extending the various types of worker and worklet, which have their own runtimes.

### Proposed Solution

I'm not sure precisely how it should work internally, but the obvious interface for exposing functionality to various threads would be modules and ES6 imports/exports.

Ideally, we would be able to use JS modules with access to Node libraries to implement and export APIs that are safe to expose to the Renderer Process. We would then place those modules in some directory, and configure Electron to expose that directory (recursively) to the renderer process. Safe APIs could then be imported from the specified directory.

EDIT: I originally wrote a bunch of stuff about a custom protocol for accessing these files, but had completely overthought it. I'm working on a project where I need a custom protocol, but it shouldn't be required in the current context (the user knows where they put the directory with their *bridge modules* in, so they can import from it directly).

### Alternatives Considered

Just using the Context Bridge in the main thread, and having to expose *that* functionality to other threads, where possible.

**Comment by 7ombie** [comment] 2022-03-17 03:11
Note that the domain name for accessing these files could be a single (top-level) name (without any dots), but this looks inconsistent when compared with `file` URLs, due to the domain name only being distinguishable by the extra slash. For example:

```
file:///foo/bar.js    -> path is `/foo/bar.js`, with no domain
spam://foo/bar.js     -> path is `/bar.js`, with `foo` as the domain
```

Given the close conceptual relationship that would exist between the two types of URL, a conventional domain name below a TLD would be more readable. Which could then be anything, but `electron://context.bridge/path/to/file.js` seems like an obvious starting point.

**Comment by miniak** [comment] 2022-03-28 19:07
@7ombie main process APIs won't be accessible in the renderer process, that's by design.

**Comment by miniak** [comment] 2022-03-28 19:11
> The Context Bridge is less bad than libraries sharing a global namespace, but it could easily clobber future additions to the window object still.

you are supposed to expose a single global object, which contains your application APIs, such as
`window.myDesktopAPIs = {...}`

**Comment by 7ombie** [comment] 2022-03-28 23:51
> ideally the renderer process is also sandboxed, which means there is no Node environment in the renderer process.

@miniak - This feature request assumes that Node Integration is disabled. Otherwise *bridge modules* would just be regular modules. These modules would replace `preload.js`, so would be able to access Node, exactly like `preload.js` does. The difference is that bridge modules export APIs, instead of binding them to `window`.

> you are supposed to expose a single global object, which contains all your application APIs

I see. Sorry. I thought you could create more than one API. Nesting everything inside a single namespace (using a name obscure enough that it will never be clobbered) is safer, but clunkier, so the point still stands generally.

At the end of the day, you need to expose functionality to different types of threads, with different global namespaces, and modules are the standard way of doing that. Binding everything to a hash that is bound to the global object is about as current as jQuery.

**Comment by MarshallOfSound** [comment] 2022-03-29 00:19
> These modules would replace preload.js, so would be able to access Node, exactly like preload.js does. The difference is that bridge modules export APIs, instead of binding them to window.

What you are describing is not technically possible, synchronous cross-process bridging (as node would have to be out of process in this scenario) is both unsafe and outside of technical feasibility.

> I see. Sorry. I thought you could create more than one API.

You can

> The current API also provides no means for extending the various types of worker and worklet, which have their own runtimes.

This is again, by design / technical limitation.  The `contextBridge` works as both contexts are in the same thread in the same process and as such we can safely expose (via our fancy proxying logic) synchronous JS execution across contexts.  As soon as you go into the realm of workers in other threads or even worse other processes that isn't something we can safely provide and as such you'll have to implement your own transport, probably using something like `MessageChannel` and `MessagePort` to communicate / perform actions in other threads / contexts.

> Binding everything to a hash that is bound to the global object is about as current as jQuery.

You're connecting this to the wrong concept, this is significantly more similar to injecting `window.chrome` like Chrome does for chrome extension / cast support.  You are you injecting `window.myApp` instead.

I'm going to close this out as there isn't a path to the technical implementation for what is described, if you have a more scoped feature request that is implementable (rather than just saying "globals are bad") feel free to raise an [RFC](https://github.com/electron/governance/blob/main/wg-api/design-spec-process.md) with some technical specifics.

**Closed by MarshallOfSound** 2022-03-29 00:19 UTC
Labels: enhancement :sparkles:

**Comment by 7ombie** [comment] 2022-03-29 00:23
@MarshallOfSound - I didn't just say "globals are bad". I suggested an approach that is not technically feasible, but would almost certainly be better, if it could be implemented. I was hoping the sleight of hand used by the Context Bridge could be used by modules and exports.

Thanks for taking the time to explain.
