### ISSUE TITLE
[Bug]: DevTools ContextMenu (Right Click) on any element does not open in foreground

### ISSUE THREAD

**Issue by pmadhur** [electron/electron#38831] opened 2023-06-17 15:38 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2

### What arch are you using?

x64

### Last Known Working Electron version

24.5.1

### Expected Behavior

When right clicking on any element in DevTools, context menu, if available, should open in the foreground. Here an example:

![image](https://github.com/electron/electron/assets/16571328/aa28c482-232d-4493-a076-1a3f03539ae6)

### Actual Behavior

When right clicking on any element in DevTools, context menu, if available, opens in the background. Here an example:

![image](https://github.com/electron/electron/assets/16571328/1c1a144a-e96b-42a7-b94f-75d74e26e182)

### Testcase Gist URL

https://gist.github.com/pmadhur/3d8526a68a57610ed709a54a1e58c621

**Comment by codebytere** [comment] 2023-06-18 19:42
Duplicate of https://github.com/electron/electron/issues/38790

**Closed by codebytere** 2023-06-18 19:42 UTC
Labels: bug :beetle:
