### ISSUE TITLE
Opening an Electron app causes a CPU overload in Firefox

### ISSUE THREAD

**Issue by pmoris** [electron/electron#19694] opened 2019-08-09 09:29 UTC
### Issue Details

* **Electron Version:**
  * 4.2.7
  * Visual Studio Code Version: 1.37.0
     Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
     Date: 2019-08-08T01:24:14.598Z
     Electron: 4.2.7
     Chrome: 69.0.3497.128
     Node.js: 10.11.0
     V8: 6.9.427.31-electron.0
     OS: Linux x64 5.0.0-23-generic
* **Operating System:**
  * Linux Mint 19.1 (Tessa)
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
Opening an Electron application should not interfere with Firefox.

### Actual Behavior
Opening an Electron application (e.g. Visual Studio Code v1.37.0) causes high CPU usage of Firefox processes that temporarily freezes all opened tabs. This lasts for just under a minute, but the issue repeats itself intermittently while both programs have been running for some time. I have not been able to determine what triggers these additional CPU spikes (e.g. opening a new tab in either program, or it just happening after a fixed time period).

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
7855 user    20   0 3191708 245344 150488 R  88,9  1,5   8:50.05 Web Content
10154 user    20   0 2930072 353724 240076 R  88,9  2,2   8:09.32 Web Content
11583 user    20   0 2777788 239144 115968 R  88,9  1,5   8:47.71 Web Content
19947 user    20   0 2877960 262884 142116 R  88,9  1,6   4:52.29 Web Content
26155 user    20   0 2902648 315952 208004 R  88,9  2,0   7:03.70 Web Content
26853 user    20   0 2606420 134368  90932 R  77,8  0,8   7:21.41 WebExtensions
19995 user    20   0 3072248 259668 139052 R  72,2  1,6   5:20.31 Web Content
26220 user    20   0 3148676 376308 170272 R  61,1  2,3  11:03.09 Web Content
9751 user    20   0 3101144 228504 132316 R  50,0  1,4  14:14.05 Web Content
1891 user    20   0 3839872 264724  97036 S  11,1  1,6  13:36.35 cinnamon
```

### To Reproduce
Have a Firefox session open and launch Visual Studio Code v1.37.0. The CPU usage will spike immediately.

### Additional Information

This problem has already been reported on VSCode's issue tracker (https://github.com/microsoft/vscode/issues/77816) and on Bugzilla (https://bugzilla.mozilla.org/show_bug.cgi?id=1566053). The latter contains more in-depth information, pointing to `libchromiumcontent` and SIGSYS font-lookups as the culprit.

> Attaching gdb to a running /usr/lib/firefox/firefox shows that, as soon as electron is started, the firefox process gets a massive amount of SIGSYS signals. Apparently all due to looking for font files. And each firefox process does gets these signals which seems to cause the overload, we're talking about ca 12000 signals on my system, probably due to the great number of font files I have installed here. 

I'm cross-posting this issue here in the hope of a solution being found, as I'm not knowledgeable enough to assess whether the bug was introduced by Firefox or by Electron.

**Comment by ckerr** [comment] 2019-08-15 17:25
@tim-janik's description in https://bugzilla.mozilla.org/show_bug.cgi?id=1566053 says that this issue can be triggered even without Electron, with just the presence of Chrom* + FF, so I'm not sure that addressing this at the Electron level makes sense?

If this is a bug in Chromium, it should be reported upstream to the Chromium devs and then Electron will pick up the fix there as it's upgraded to newer versions of Chromium.

That said, I'm sympathetic to this issue. If there _is_ something that make sense fixing at the Electron level -- or, say, if this is fixed in Chromium and you'd like us to ensure that fix is backported to older versions of Electron -- please feel free to file a new issue with that actionable information.

**Closed by ckerr** 2019-08-15 17:25 UTC
Labels: 4-2-x, bug :beetle:, platform/linux

**Comment by tim-janik** [comment] 2019-08-15 20:30
> @tim-janik's description in https://bugzilla.mozilla.org/show_bug.cgi?id=1566053 says that this issue can be triggered even without Electron, with just the presence of Chrom* + FF, so I'm not sure that addressing this at the Electron level makes sense?

I agree that FF#1566053 should *not* be filed as an Electron issue. FF keeps misbehaving after being triggered by newer libchromiumcontent startups even after the Electron/google-chrome processes have terminated. So there's something in FF that definitely needs fixing. And only Electron versions >= 4 manage to trigger Firefox.

That said, if someone has *any* idea what in the libchromiumcontent startup code could be causing FF to visit all font files on a system (maybe through some fontconfig crawling mechanism?), that could be helpful to produce better test cases or get closer to the root cause.

**Comment by Mema5** [comment] 2020-04-13 06:53
I take the liberty of posting in this issue as I was facing the same annoying problem with Firefox eating up 100% CPU when launching VSCode. With some research I found a workaround that worked for me and I wanted to point to it here as it might help people.

The root of the problem seems to have been identified [in this thread](https://askubuntu.com/questions/1076412/firefox-freezing-with-100-cpu-usage-for-30-seconds-when-launching-chromium), and the solution proposed in [this answer](https://askubuntu.com/a/1089841/1063687) worked for me. More precisely, renaming one of my local font folder (`mv ~/.local/share/font-manager/ ~/.local/share/font-manager_old/`) solved the issue.
