### ISSUE TITLE
二进制adb文件，electron构建之后在某些系统内无法访问

### ISSUE THREAD

**Issue by icepy** [electron/electron#11566] opened 2018-01-04 02:52 UTC
* Electron version: 1.7.10
* Operating system: Mac 10.13.1

### Expected behavior

可以启动adb service通过`adb devices` 获取到设备id

### Actual behavior

```JavaScript

A JavaScript error occurred in the main process

Uncaught Exception:

Error : spawn ENOTDIR

```

adb放置在`resources/mac/adb`，代码写在src/index.js中，整体的目录结构如下：

```
resources // adb二进制文件
src //源代码
.babelrc
package.json
```

代码：

```JavaScript
import os from 'os';
import path  from 'path';
import childProcess from 'child_process';
const spawn = childProcess.spawn;
const PLATFORM = {
  MAC: 'mac',
  WINDOWS: 'windows',
  UNKNOWN: 'unknown'
}
function fetchPlatform(){
  switch(os.platform()){
    case 'darwin':
        return PLATFORM.MAC;
      break;
    case 'win32':
        return PLATFORM.WINDOWS;
      break;
    default:
        return PLATFORM.UNKNOWN;
      break;
  }
}
const platform = fetchPlatform();
const rootDir = path.resolve(__dirname,'../');
const RESOURCES = path.resolve(rootDir,'resources')
const _adbPath = path.resolve(RESOURCES,platform);
function fetchAdbPath(){
  switch(platform){
    case PLATFORM.MAC:
        return path.resolve(_adbPath,'adb');
      break;
    case PLATFORM.WINDOWS:
        return path.resolve(_adbPath, 'adb.exe');
      break;
    default:
        return false;
      break;
  }
}
export function start_server(callback){
  let adbExecPath = fetchAdbPath();
  if (adbExecPath){
    let adb = spawn(adbExecPath,['start-server']);
    adb.stdout.on('data', function (data) {
      console.log('stdout: ' + data);
    });
    adb.stderr.on('data', function (data) {
      console.log('stderr: ' + data);
    });
    adb.on('exit', function (code) {
      typeof callback === 'function' && callback(code);
    });
    adb.stdin.end();
  } else {
    throw new Error('Not Found Android Debug Bridge');
  }
}
```

### How to reproduce

将上述代码做为一个npm包，假设叫`adb-test-a`，然后在electron工程里，`npm install adb-test-a`，调用`start_server`，必抛错误：`Error : spawn ENOTDIR`。

**Comment by icepy** [comment] 2018-01-10 07:37
问题依旧没有解决，说了一圈社区里的人，都说是electron的问题，希望能帮忙指导一下，怎么解决。

**Comment by KagamiChan** [comment] 2018-01-10 07:57
`ENOTDIR` means `not a directory`, this usually means that you're passing a wrong path, check that using `fs.stat` or anything similar

**Comment by icepy** [comment] 2018-01-10 08:44
@KagamiChan  i know, but my example code did not use fs or anything similar, please help me, check my example code .

some os the dir path is 'app.asar', some other is 'app.asar.unpacked', i am very confused about this.

**Comment by sindresorhus** [comment] 2018-01-10 09:10
Duplicate of #9459

**Comment by MarshallOfSound** [comment] 2018-01-10 09:18
Good catch @sindresorhus 👍 Closing as duplicate

**Closed by MarshallOfSound** 2018-01-10 09:18 UTC

**Comment by vanxv** [comment] 2019-03-13 13:12
> unpacked



> @KagamiChan i know, but my example code did not use fs or anything similar, please help me, check my example code .
> 
> some os the dir path is `app.asar`, some other is `app.asar.unpacked`, i am very confused about this.

not understand 

step：
1.  add **adb file** to app.asar
2. use **electron-util#fixpathforasarunpackpath**，get **app.asar.unpacked**
3. use **exec run adb command**
