### ISSUE TITLE
[Bug]: Symbol generation failing on 32-bit Windows release builds (nightlies)

### ISSUE THREAD

**Issue by VerteDinde** [electron/electron#34413] opened 2022-06-01 21:47 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

main

### What operating system are you using?

Windows

### Operating System Version

Windows

### What arch are you using?

ia32

### Last Known Working Electron version

20.0.0

### Expected Behavior

Release builds succeed

### Actual Behavior

Symbol generation on 32-bit Windows release builds on nightlies and 19-x-y are failing with the following error:

```
FAILED: gen/electron/electron_app_symbols.stamp 
C:/depot_tools/bootstrap-2@3_8_10_chromium_23_bin/python3/bin/python3.exe ../../electron/build/dump_syms.py ./dump_syms.exe electron.exe breakpad_symbols gen/electron/electron_app_symbols.stamp
failed to get function name
WriteSymbols failed.
Traceback (most recent call last):
  File "../../electron/build/dump_syms.py", line 53, in <module>
    main(*sys.argv[1:])
  File "../../electron/build/dump_syms.py", line 42, in main
    symbol_data = subprocess.check_output(args).decode(sys.stdout.encoding)
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_23_bin\python3\bin\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\depot_tools\bootstrap-2@3_8_10_chromium_23_bin\python3\bin\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./dump_syms.exe', 'electron.exe']' returned non-zero exit status 1.
ninja: build stopped: subcommand failed.
Command exited with code 1
```

### Testcase Gist URL

https://ci.appveyor.com/project/electron-bot/electron-ia32-release/build/1.0.1818

### Additional Information

Introduced in #34272

**Comment by khwaaj** [comment] 2022-06-02 05:43
I ran into this recently when building the v20 alpha for `win-ia32`. Maybe you are already aware, but the cause is that `dump_syms.exe` actually runs out of available virtual address space for 32-bit executables on Windows.

Generating the symbols does work if you use the `win-x64` version of `dump_syms.exe` instead, so one solution would be to always build the host tooling as 64-bit.

Just a FYI that could maybe save you some time if you were not already aware of it 😄

**Comment by RaisinTen** [comment] 2022-07-27 05:37
Closing since https://github.com/electron/electron/pull/35078 has landed on main, thanks for the fix. Feel free to reopen if you want this to stay open till the fix gets backported to 18-x-y since that branch was affected too!

**Closed by RaisinTen** 2022-07-27 05:37 UTC
Labels: bug :beetle:, main, upgrade-follow-up
