### ISSUE TITLE
Electron web page not working correctly

### ISSUE THREAD

**Issue by Linch1** [electron/electron#23318] opened 2020-04-28 16:41 UTC
* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 6.1.5**
* **Operating System: Ubuntu 19.10**
* **Last Known Working Electron version:**

I'm trying to simply load some pages with electron, one of this is the tiktok website, when i load this page i cannot visit mine and other users profiles and i'm wondering why.

### Expected Behavior

Tiktok website work as on normal browser

### Actual Behavior

Tiktok website prevents me to visit the profiles.
[this](https://i.ibb.co/T873BDn/Schermata-da-2020-04-28-11-28-55.png) is the image that shows what happens when i visit a tiktok profile.
Baically it says `Page not aviable`

In the main console of the electron app no errors are displayed.
In thwe window that loaded the website this error is displayed:

```
profile:66 Uncaught (in promise) DOMException
(anonymous) @ profile:66
load (async)
(anonymous) @ profile:65
```

Related to this tiktok page script

```
// Check that service workers are supported
if ('serviceWorker' in navigator) {
 // Use the window load event to keep the page load performant
    window.addEventListener('load', function() {
          navigator.serviceWorker.register('/sw.js');
    });
 }
```

( But it gives the same error if i go in other pages of the website that are correctly load for example in the trending page, instead the `@ profile` it says `@ trending` and so on for all the pages So i think that's irrelevant but maybe i'm wrong)

### To Reproduce
```

const {app, BrowserWindow} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })
  mainWindow.loadURL('https://www.tiktok.com/@worldeconomicforum?lang=en')

}

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('ready', createWindow)

```

**Comment by codebytere** [comment] 2020-04-30 04:35
I did not see this when running the repro - there were no errors in console and the page loaded. Perhaps this is an issue with your internet?

**Comment by Linch1** [comment] 2020-04-30 08:15
@codebytere the page loaded showing the0 profile details? Actually i don't think is a problem with my internet, with outhe rbrowsers it works correctly

**Comment by codebytere** [comment] 2020-06-04 18:47
Still not able to reproduce sadly. I'm going to close this for now and if more information comes to light i'll reopen.

**Closed by codebytere** 2020-06-04 18:47 UTC
Labels: 6-1-x, blocked/need-repro, platform/linux
