### ISSUE TITLE
[Bug]: PDF in iframe broken in non persisted sessions

### ISSUE THREAD

**Issue by rhysbrettbowen** [electron/electron#41288] opened 2024-02-08 19:38 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.3

### What operating system are you using?

macOS

### Operating System Version

14.2.1 (23C71)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

PDF will load and show

### Actual Behavior

White box with scrollbars

### Additional Information

Tried to create electron fiddle but seems to work, possibly because it is a local file being shown?

We load URLs in to different sessions and display them in BrowserViews. In the persisted session the PDF is displayed correctly with the chrome PDF header bar. Tried removing the "persist:" from the session name and the PDF in an iframe no longer displays (below).
![Screenshot 2024-02-08 at 2 37 42 PM](https://github.com/electron/electron/assets/728134/0bcb6e9b-fbe5-49cf-8be9-42e8e2cf7d1c)

using the following options on the BrowserView:

```
  allowRunningInsecureContent: false,
  nodeIntegration: false,
  webSecurity: true,
  sandbox: true,
  contextIsolation: true,
```

**Comment by mlaurencin** [comment] 2024-02-09 20:46
@rhysbrettbowen It will be a bit difficult for maintainers to test this with the current information provided. If you cannot reproduce the issue using Fiddle, could you try cloning [electron-quick-start](https://github.com/electron/electron-quick-start) and see if you can reproduce it that way instead?

**Comment by codebytere** [comment] 2024-02-10 21:31
Duplicate of https://github.com/electron/electron/issues/27121

**Closed by codebytere** 2024-02-10 21:31 UTC
Labels: blocked/need-info ❌, bug :beetle:
