### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by Genchou** [electron/electron#7409] opened 2016-09-29 14:16 UTC
On an up to date Arch system, electron doens't start, same with other electron apps (atom for example) , with the following error :

`electron: symbol lookup error: electron: undefined symbol: _ZN3re23RE23Arg9parse_intEPKciPv`

The issue is discuted [here](https://bugs.archlinux.org/task/51025) and narrowed down to electron interaction with the recently updated re2 package :

> After replacing '#include "third_party/re2/src/re2/re2.h"' with #include "re2/re2.h" in 'electron' sources I was able to compile it. And it fixed the problem with atom.

> Here is the description of the problem: there are multiple places in electron that hardcode path to re2 main header third_party/re2/src/re2/re2.h. And it is included even if system re2 library is configured. So outdated version of re2/re2.h is included from electron while subsequent includes of 're2/xxx.h' are from system package. This mismatch causes ABI confusion.

**Comment by deepak1556** [comment] 2016-09-29 15:27
The problem is with Electron arch package, since they are building with custom chromium and they seem to have fixed it https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/electron&id=d14c8d8c671b32b9db84a6035e069f0ae2f36b00 . Closing this out since its not a bug in Electron.

I believe the repo you would want to raise the issue is https://github.com/tensor5/arch-atom

**Closed by deepak1556** 2016-09-29 15:27 UTC
Labels: linux-distribution-specific
