### ISSUE TITLE
Conflict between ready-to-show and BrowserWindow.setThumbarButtons?

### ISSUE THREAD

**Issue by KeitIG** [electron/electron#9049] opened 2017-03-28 19:57 UTC
* Electron version: 1.6.2
* Operating system: Win32

### Expected behavior

Thumbnail Toolbar should appear on a BrowserWindow shown with the `ready-to-show` event

### Actual behavior

It does not

### How to reproduce

Ok, so this is very strange, I had a thumbbar working properly until I switched to the "ready-to-show" event to show my main browser window. [This commit](https://github.com/KeitIG/museeks/commit/e101238b8ad98948e2dd57d1003b7ff5b0769459) in my app apparently changed something, and the thumbbar is not appearing since. If I rollback to the old way of showing the thumbbar, then everything is ok.

My previous implementation was "show the window only when the renderer process sends the `appReady` event". Then I decided to use the `ready-to-show` event to avoid that flash on window show.

``` javascript
mainWindow.once('ready-to-show', () => {
    mainWindow.show(); // Thumbbar is not showing
});

ipcMain.on('appReady', () => {		
    mainWindow.show(); // Thumbbar shows correctly	
});
```

I didn't have time to create any repo for it, please tell me if you need one, but it's fairly simple to test.

**Comment by kevinsawicki** [comment] 2017-04-03 23:34
Is the `ready-to-show` event firing? There have been other issues reported about it not firing in certain cases.

**Comment by KeitIG** [comment] 2017-04-04 11:58
`ready-to-show` is firing indeed, otherwise the window would not be shown

**Comment by zcbenz** [comment] 2017-06-15 07:11
It looks like that some other API broke the thumbar buttons after you delayed the call of `show`, the `ready-to-show` is not the cause of this problem.

Can you try working out a minimal app that can reproduce this problem?

I'm closing this until a reproducible case is provided.

**Closed by zcbenz** 2017-06-15 07:11 UTC
Labels: more-information-needed
