### ISSUE TITLE
Maximized Frameless electron windows regularly offset from proper location

### ISSUE THREAD

**Issue by TomSputz** [electron/electron#13391] opened 2018-06-22 23:13 UTC
* Electron Version: 2.0.3
* Operating System (Platform and Version): Windows_NT x64 10.0.17134
* Last known working Electron version: None

**Expected Behavior**
When a window is maximized, the edges of the window should be in the same position as the edges of the screen it is maximized in

**Actual behavior**
Every other time a window is maximized, the window if offset downwards by 17 pixels for seemingly no reason. 

**To Reproduce**
[Demonstration repository](https://github.com/TomSputz/electron-frameless-demo)

To start the application:
```sh
$ git clone https://github.com/TomSputz/electron-frameless-demo
$ cd electron-frameless-demo
$ start.bat
```
**Screenshots**
(Using the demo application)
Normal:
![Picture of application taking up whole screen without issue](https://i.imgur.com/5q2JcC5.png)
Issue:
![Picture of identical application, however it is shifted 17 pixels downwards, revealing the application behind it](https://i.imgur.com/QkBlCv2.png)

**Additional Information**
This is quite similar to an issue that was close last year in #8728 , I don't know if they're related but looking at the changes made could be of use. As I understand it there is also a good chance that this is an upstream issue, if so is there any way I might generate support for that being fixed?

**Comment by GrantGryczan** [comment] 2018-06-25 07:10
Additionally, if you have a second monitor (at least to the left; haven't tested to the right), the window size will be extended onto it by exactly 1 pixel while maximized.

**Comment by timfish** [comment] 2018-06-27 10:59
This looks like a duplicate of #12971.

**Closed** 2018-06-27 21:07 UTC
Labels: bug :beetle:, platform/windows, version/2.0.x
