### ISSUE TITLE
[Bug]: Minimized window stops painting when backgroundThrottling is false (Windows 10)

### ISSUE THREAD

**Issue by dwang3142** [electron/electron#36707] opened 2022-12-20 08:57 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Minimized windows continues to paint and is not throttled. Works on Mac version where minimized window continues to paint when background throttling is false.

### Actual Behavior

Minimized window content stays blank. No paint events are generated.

**Comment by mlaurencin** [comment] 2023-02-07 21:19
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/electron/electron/issues/31016. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by mlaurencin** 2023-02-07 21:19 UTC
Labels: bug :beetle:, duplicate
