### ISSUE TITLE
Bug report: webview requires a <script> in <body>

### ISSUE THREAD

**Issue by snoblenet** [electron/electron#5109] opened 2016-04-11 06:21 UTC
UPDATE: I've solved the problem but I am now filing a bug report instead of a request for help. See below.

**Original request for help:**

* Electron version: v0.37.5
* Operating system: Mac OS X 10.11.4

I'm building my first Electron app. 

My WebView, which was working just fine, has suddenly stopped loading URLs and/or data URLs.

I was distracted and didn't notice what change if any I made at the time the WebView stopped working.

In my `index.html`, I'm trying each of the following, one at a time:
`<webview src="data:text/plain,Hello, world!"></webview>`
`<webview src="https://www.example.com/"></webview>`

The overall structure of my `index.html` is:

```
div display:table
    div display:table-row
        div display:table-cell
            sidebar content
        div display:table-cell
            div wrapper (height & width set to 100%)
                webview
```

In my `index.css` I have:

```
webview {
  autosize: on;
  min-width: 800px; // the width of the enclosing div's parent
  min-height: 600px; // the ehight of the enclosing div's parent
  background-color: blue; // just so I can visually check the webview's dimensions
  display: inline-block;
}
```

My `main.js` instantiates the browser window in the usual way:

```
  mainWindow = new BrowserWindow({
    width: 1050, 
    height: 622,
    resizable: false,
  });

```

The window and its sidebar content load and display correctly.

The webview displays with a blue background in the desired location and with the desired dimensions.

However, it contains no content -- neither the "Hello world" message nor the Example.com website.

When I change the webview to an iframe, the content does load and the iframe is in the correct location, though smaller than intended.

When I made a new copy of `electron-quick-start` and paste in just the webview code, it initially displays the "Hello world" message and/or the Example.com website, but when I paste in the entire HTML and CSS it stops working. And now it's stopped working full-stop.

I've linked to the code in full case it helps:

- [app/html](https://gist.github.com/snoblenet/23dd8aea10ee6a7e9d04685a7e22d9ae)
- [app/index.css](https://gist.github.com/snoblenet/7c462c18d28367ca74f27667a8eed081)
- [main.js](https://gist.github.com/snoblenet/a69e7ae17f0e8442009398987d89f93a)
- [package.json](https://gist.github.com/snoblenet/9308701e22bc45bf3a669ffb2ead7c0a)

What process would I follow to debug this?

**UPDATE & BUG REPORT**

I solved this by inserted random non-empty script into the <body> of the HTML (inspired by an earlier bug report about an earlier version of Electron that required a script in <head> for <webview> to render correctly.  This appears to to be a new bug.

Incidentally, I also had to comment out `display: inline-block;` in the stylesheet for the webview to be the right height and width once it started displaying again.

**Comment by zcbenz** [comment] 2016-04-11 23:48
This is a duplicate of #1117.

**Closed by zcbenz** 2016-04-11 23:48 UTC

**Comment by xywz** [comment] 2016-04-12 02:53
For webview stylesheet, see #5070.
