### ISSUE TITLE
[Bug]: fullscreen or maximize window restore event not fired

### ISSUE THREAD

**Issue by Deuscx** [electron/electron#33819] opened 2022-04-18 09:30 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.9

### What operating system are you using?

Windows

### Operating System Version

windows10 19042

### What arch are you using?

x64

### Expected Behavior

restore minimized fullscreen window will emit restore event

### Actual Behavior

event don't fired

```js

async function createWindow() {
  // Create the browser window.
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    // fullscreen: true,
  });

   win.loadURL("app://./index.html");
  
  // when set fullscreen or maximize the window, then restore event not fire
  win.on("restore", () => {
    console.log("restored");
  });

  win.on("minimize", () => {
    console.log("minimize");
  });
}
```

**Comment by mlaurencin** [comment] 2022-04-18 18:48
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/electron/electron/issues/28570. You may want to subscribe there for updates.

Because we treat our issues list as [the project team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by mlaurencin** 2022-04-18 18:48 UTC
Labels: bug :beetle:
