### ISSUE TITLE
[Bug]: registerStringProtocol crashes the entry app

### ISSUE THREAD

**Issue by mahnunchik** [electron/electron#28579] opened 2021-04-08 11:39 UTC
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.4.4, 10.4.2, 11.4.2, 12.0.2

### What operating system are you using?

macOS

### Operating System Version

11.2.2

### What arch are you using?

x64

### Last Known Working Electron version

-

### Expected Behavior

App works

### Actual Behavior

App crashes

### Testcase Gist URL

https://gist.github.com/mahnunchik/aaef0dffd6c03020b80c58925f31d2af

But removing callback call from the `registerStringProtocol` handler keeps app working.

**Comment by mahnunchik** [comment] 2021-04-08 11:42
The similar issue was before, but should be fixed. It seems the bug was introduces again:

* https://github.com/electron/electron/issues/10432
* https://github.com/electron/electron/issues/9342

**Comment by mahnunchik** [comment] 2021-04-08 12:30
@pfrazee previous fix is from your commit, maybe you know whats wrong with `registerStringProtocol` method ?

**Comment by codebytere** [comment] 2021-04-08 15:43
Duplicate of https://github.com/electron/electron/issues/28407

**Closed by codebytere** 2021-04-08 15:43 UTC
Labels: bug :beetle:, component/protocol, platform/all

**Comment by mahnunchik** [comment] 2021-04-08 15:53
@codebytere are you sure that it is related with #28407 ? In my case app crashes after click and handle the custom protocol link.

**Comment by pfrazee** [comment] 2021-04-12 15:26
No idea if it's the same issue, I was working with pretty limited understanding. I detailed everything I knew/understood in the PR
