### ISSUE TITLE
takeHeapSnapshot on webview webContents is very slow in Electron 5+ 

### ISSUE THREAD

**Issue by tervicz** [electron/electron#24509] opened 2020-07-10 18:28 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.x.x and higher
* **Operating System:**
  * Windows 10, Mac OS, Linux
* **Last Known Working Electron version:**
  * 4.x.x

### Expected Behavior
duration of takeHeapSnapshot method called on webview webcontents should be comparable to the same operation on main window and with time in Electron prior v. 5

### Actual Behavior
takeHeapSnapshot on webview webcontents takes 10 and more times than in Electron 4, it performs especially slow on windows, but the regression seems to affect all the platforms. calling openDevTools before (but not immediatelly) "fixes" the problem and figures are then close to expected ones.

### To Reproduce

Call take takeHeapSnapshot on webview webconents on Electron 5 and higher, measure the time when the promise is resolved. Compare this time to Electron 4. In the same scenario, open the devtools on webcontents ~1s + before the snapshot is taken, observe the major reduction of the time for all subsequent snapshots.

Test app which shows the scenario  attached.

[wv-snapshot.zip](https://github.com/electron/electron/files/4904383/wv-snapshot.zip)

**Comment by ckerr** [comment] 2020-07-14 16:37
gist of wv-snapshot.zip:

https://gist.github.com/ckerr/4c3d501c4058bd6b600f1c2434c8a57c

**Comment by ckerr** [comment] 2020-07-14 16:53
Yep, repro is pretty much exactly what @tervicz says. Seems to affect every post-4.x version of Electron.

| Electron Version | Snapshot Size | Exec Time |
|------------------|--------------:|----------:|
| 4.2.12           |       5.60 MB |     0.218 |
| 5.0.13           |       5.57 MB |     8.027 |
| 6.1.12           |       8.06 MB |     7.684 |
| 9.1.0            |       5.24 MB |     7.512 |
| 10.0.0-beta.11   |       5.30 MB |     7.628 |

**Comment by deepak1556** [comment] 2020-07-14 17:37
@ckerr Just to update with what I found so far, the issue has nothing to do with webview webContents. You can eliminate webview from the picture, I will share two different tests that will be good enough starting point for debugging.

```
const { app, BrowserWindow, webContents, ipcMain, contentTracing } = require('electron')
const path = require('path')
const { statSync } = require('fs')

let webViewWC = {}
let mainWindow = null

const createWindow = () => {

  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      webSecurity: false,
      sandbox: true
    }
  })

  mainWindow.webContents.on('did-finish-load', (e, webContents) => {
      webViewFilePath = path.join(__dirname, `/webview-snap.heapsnapshot`)
      const start = Date.now()      
      console.log('Taking V8 HeapSnapshot')
      mainWindow.webContents.takeHeapSnapshot(webViewFilePath)
        .then(() => {
          const stats = statSync(webViewFilePath)
          const fileSizeInMegabytes = stats["size"] / 1000000
          console.log(`WebView V8 HeapSnapshot taken successfully, size: ${fileSizeInMegabytes}MB, execution time: ${((Date.now() - start)/1000).toString()}`)
          contentTracing.stopRecording(__dirname + '/snap.log').then(path => {
            console.log(path)
          })
        }) 
        .catch(err => { console.log(err) })
  })

  contentTracing.startRecording({
    categoryFilter: '*',
    traceOptions: 'record-until-full,enable-sampling'
  }).then(() => {
    mainWindow.loadURL(`https://office.com`)
  })

  mainWindow.on('closed', () => mainWindow = null)
};

app.on('ready', createWindow)
app.on('window-all-closed', () => process.platform !== 'darwin' && app.quit())
app.on('activate', () => mainWindow === null && createWindow())
```

1) Load the page with some considerable javascript `https://github.com` or the link from the above test is fine too in the main page

   * load the content trace in `chrome://tracing`, the problem is at the ipc layer, you will see the ipc for completing heapsnapshot in the renderer shows the actual delayed timing that is logged by the app
![Screenshot (7)](https://user-images.githubusercontent.com/964386/87457932-0d8ca280-c5be-11ea-9d32-93b6e68674ee.png)


  

2) Load a page with minimal javascript, `https://github.com`

![Screenshot (8)](https://user-images.githubusercontent.com/964386/87457890-ff3e8680-c5bd-11ea-99ae-7531a688fa65.png)

**Comment by ckerr** [comment] 2020-07-22 20:36
After removing webview as a suspect, I think we can also remove our mojo code from that list too -- even though it was a nice red herring because mojoification took place around the time this slowdown showed up.

However the Mojoification passes a wrapped nativefile from the browser to the renderer -- this is a very thin wrapper around a file handle on win, fd on posix -- and Mojo does the Right Thing in passing these cross-process (e.g. in public/cpp/platform/socket_utils_posix.cc). By the time we get to  HeapSnapshotOutputStream writing to disk with base::File::WriteAtCurrentPos(), we really **are** just writing to a regular file.

In fact, all  the time spent seems to be in the V8 call. If you stub out the file IO completely:

```diff
   v8::OutputStream::WriteResult WriteAsciiChunk(char* data, int size) override {
-    auto bytes_written = file_->WriteAtCurrentPos(data, size);
-    return bytes_written == size ? kContinue : kAbort;
+    // NOCOMMIT this paragraph is stubbed out for testing and should not be merged
+    // auto bytes_written = file_->WriteAtCurrentPos(data, size);
+    // return bytes_written == size ? kContinue : kAbort;
+    return kContinue;
   }
```

...the snapshot *still* takes the same execution time:

```
WebView V8 HeapSnapshot taken successfully, size: 0MB, execution time: 11.82
```

**Comment by deepak1556** [comment] 2020-07-22 21:22
Nice work identifying the problematic area, thats quite an old v8 version to debug, might get help with debugging at https://groups.google.com/g/v8-users

**Comment by ckerr** [comment] 2020-07-22 23:01
It seems to all be coming from the HeapSnapshotGenerator's V8HeapExplorer. Some time between Electron 4 and 5 -- in V8 7.0, presumably -- the heap snapshot added a new section named "locations":

**V8 in Electron 4**

```cc
void HeapSnapshotJSONSerializer::SerializeImpl() {
...
    writer_->AddString("\"samples\":[");
    SerializeSamples();
    if (writer_->aborted()) return;
    writer_->AddString("],\n");
  
    writer_->AddString("\"strings\":[");
    SerializeStrings();
    if (writer_->aborted()) return;
    writer_->AddCharacter(']');
    writer_->AddCharacter('}');
    writer_->Finalize();
  }
```

**V8 in Electron 5 (similar code in newer versions)**

```cc
    writer_->AddString("\"samples\":[");
    SerializeSamples();
    if (writer_->aborted()) return;
    writer_->AddString("],\n");
  
    writer_->AddString("\"locations\":[");
    SerializeLocations();
    if (writer_->aborted()) return;
    writer_->AddString("],\n");
  
    writer_->AddString("\"strings\":[");
    SerializeStrings();
    if (writer_->aborted()) return;
    writer_->AddCharacter(']');
    writer_->AddCharacter('}');
    writer_->Finalize();
```

`V8HeapExplorer::IterateAndExtractReferences()` is where all the action happens both in 4 and 5. In 5, there's a new call there to `V8HeapExplorer::ExtractLocation()` to populate the locations vector shown in the above code.

This location lookup is quite expensive: if I comment out `IterateAndExtractReferences()`'s call to `ExtractLocation()`, the snapshot generation time drops from ~11 seconds to ~0.4 seconds, back on par with Electron 4 again.

If anyone else wants to confirm this -- **and also, @tervicz, if this is an urgent issue where a short-term hack would be useful for unblocking anyone** -- you can just patch the location info out by commenting this section in `v8/src/profiler/heap-snapshot-generator.cc`:

```diff
diff --git a/src/profiler/heap-snapshot-generator.cc b/src/profiler/heap-snapshot-generator.cc
index 2ae2222419..94dc8ebcf4 100644
--- a/src/profiler/heap-snapshot-generator.cc
+++ b/src/profiler/heap-snapshot-generator.cc
@@ -1522,12 +1540,15 @@ bool V8HeapExplorer::IterateAndExtractReferences(
     }
 
     // Extract location for specific object types
-    ExtractLocation(entry, obj);
+    // ExtractLocation(entry, obj);
 
     if (!progress_->ProgressReport(false)) interrupted = true;
   }
 
   generator_ = nullptr;
```
 
There is more research to be done here, e.g. perhaps there is low-hanging fruit in `ExtractLocation()`. That would be the ideal solution, since we could upstream that and everyone would benefit.

**Comment by ckerr** [comment] 2020-07-22 23:16
BTW thank you for providing a repro; it made tracking this down much easier

**Comment by ckerr** [comment] 2020-07-23 19:50
Another breadcrumb: it looks like a large part of the slowdown comes from Script::getPositionInfo() which tries to find the source code location of  a position. If line endings available, this is done with a binary search; otherwise, "slow mode" is used which does a sequential walk. As you've probably guessed, our use case is hitting slow mode.

**Comment by codebytere** [comment] 2020-10-08 23:39
Poked into this a bit more - it actually unfortunately seems that we're _not_ hitting slow mode in `Script::getPositionInfo()`. `GetPositionInfoSlow` gets called when we don't have line endings, and local testing demonstrates that they get initialized and set [here](https://source.chromium.org/chromium/chromium/src/+/master:v8/src/objects/objects.cc;drc=da8e399b1f509d29565224190204860b22c9062b;bpv=1;bpt=1;l=4776) and we drop into [this second faster block](https://source.chromium.org/chromium/chromium/src/+/master:v8/src/objects/objects.cc;l=4840;drc=da8e399b1f509d29565224190204860b22c9062b;bpv=1;bpt=1) consistently

**Comment by ckerr** [comment] 2020-10-23 20:32
> Poked into this a bit more - it actually unfortunately seems that we're _not_ hitting slow mode in `Script::getPositionInfo()`. `GetPositionInfoSlow` gets called when we don't have line endings, and local testing demonstrates that they get initialized and set [here](https://source.chromium.org/chromium/chromium/src/+/master:v8/src/objects/objects.cc;drc=da8e399b1f509d29565224190204860b22c9062b;bpv=1;bpt=1;l=4776) and we drop into [this second faster block](https://source.chromium.org/chromium/chromium/src/+/master:v8/src/objects/objects.cc;l=4840;drc=da8e399b1f509d29565224190204860b22c9062b;bpv=1;bpt=1) consistently

@codebytere and I discussed this in DM but to repeat some of it here for transparency -- Not all scripts get treated the same way by V8; some get metainfo e.g. line numbers preloaded s.t. "slow mode" is never used. Otherwise, it does drop back to slow mode and that's what's happening in wv-snapshot.zip / https://gist.github.com/ckerr/4c3d501c4058bd6b600f1c2434c8a57c so making the position lookup faster is still relevant to this issue and still helpful to V8 overall. In addition, the patch eliminates half of the position lookups regardless of whether fast or slow mode is used, so it will still be twice as fast no matter what other variables are in play.

However it's all well and good to say this, but a patch doesn't do anyone any good unless it actually gets used :slightly_frowning_face: so I'll prioritize upstreaming this and also make an interim patch for Electron.

**Comment by deepak1556** [comment] 2020-10-23 21:01
@ckerr what does removing the position lookup mean for the actual snapshot generated https://github.com/electron/electron/issues/24509#issuecomment-662739258, does it have impact on rendering the snapshot data ?

**Comment by ckerr** [comment] 2020-10-23 21:12
> @ckerr what does removing the position lookup mean for the actual snapshot generated [#24509 (comment)](https://github.com/electron/electron/issues/24509#issuecomment-662739258), does it have impact on rendering the snapshot data ?

@deepak1556 it's [this block here](https://github.com/electron/electron/pull/26138/files#diff-7dc77bfd7d170b6437fe470b3f90600b8013b613e7220884b8f66d51aba3ce46R97).  The code currently makes separate calls to get the line number and to get the column number, even though both route down to the same GetPositionInfo(). Here we just call GetPositionInfo() so that for each item, only one lookup is needed instead of two.

**Comment by ckerr** [comment] 2020-10-27 14:41
Periodic update: this fix is being reviewed upstream @ https://chromium-review.googlesource.com/c/v8/v8/+/2496065

**Comment by ckerr** [comment] 2020-11-03 00:42
This is fixed now in Electron 8 and higher.

Sample run from original test case in Electron 8.5.3:

```
Taking V8 HeapSnapshot
WebView V8 HeapSnapshot taken successfully, size: 7.537737MB, execution time: 0.406
Taking V8 HeapSnapshot
WebView V8 HeapSnapshot taken successfully, size: 6.492518MB, execution time: 0.357
```

**Closed by ckerr** 2020-11-03 00:42 UTC
Labels: 10-x-y, 7-3-x, 8-x-y, 9-x-y, bug/regression :leftwards_arrow_with_hook:, platform/all, status/confirmed
