### ISSUE TITLE
Building fails with v6.0.8

### ISSUE THREAD

**Issue by barbalex** [electron/electron#20205] opened 2019-09-11 17:16 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Running `del yarn.lock && rmdir /s node_modules && yarn && yarn dev` leads to error while `yarn` is building the app:

```
alexa@PCA C:\Users\alexa\awel-personal
$ del yarn.lock && rmdir /s node_modules && yarn && yarn dev
C:\Users\alexa\awel-personal\yarn.lock konnte nicht gefunden werden
Möchten Sie "node_modules" löschen (J/N)? j
yarn install v1.17.3
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning react-json-view > flux > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
warning jest > jest-cli > prompts > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
warning jest > jest-cli > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning testcafe > testcafe-browser-tools > babel-runtime > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning testcafe-live@0.1.4: This module is now deprecated. In TestCafe v1.0.0, we have integrated features from the testcafe-live module into the main TestCafe code.
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "styled-components > stylis-rule-sheet@0.0.10" has unmet peer dependency "stylis@^3.5.0".
warning " > styled-components@5.0.0-beta.8" has unmet peer dependency "react-is@>= 16.8.0".
warning " > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning "@typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning " > eslint-config-react-app@5.0.1" has incorrect peer dependency "eslint-plugin-react-hooks@1.x".
[5/5] Building fresh packages...
success Saved lockfile.
$ yarn build-dll && electron-builder install-app-deps package.json && opencollective-postinstall
yarn run v1.17.3
$ cross-env NODE_ENV=development webpack --config ./configs/webpack.config.renderer.dev.dll.babel.js --colors

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

Hash: ec9f7e26dbadbc6e5407
Version: webpack 4.39.3
Time: 49ms
Built at: 2019-09-11 19:03:50
              Asset      Size    Chunks             Chunk Names
renderer.dev.dll.js  14.7 KiB  renderer  [emitted]  renderer
Entrypoint renderer = renderer.dev.dll.js
[0] dll renderer 12 bytes {renderer} [built]
[better-sqlite3] external "better-sqlite3" 42 bytes {renderer} [built]
[bootstrap] external "bootstrap" 42 bytes {renderer} [built]
[classnames] external "classnames" 42 bytes {renderer} [built]
[date-fns] external "date-fns" 42 bytes {renderer} [built]
[devtron] external "devtron" 42 bytes {renderer} [built]
[electron-debug] external "electron-debug" 42 bytes {renderer} [built]
[exceljs] external "exceljs" 42 bytes {renderer} [built]
[history] external "history" 42 bytes {renderer} [built]
[jquery] external "jquery" 42 bytes {renderer} [built]
[mobx] external "mobx" 42 bytes {renderer} [built]
[mobx-react-lite] external "mobx-react-lite" 42 bytes {renderer} [built]
[mobx-state-tree] external "mobx-state-tree" 42 bytes {renderer} [built]
[moment] external "moment" 42 bytes {renderer} [built]
[mst-middlewares] external "mst-middlewares" 42 bytes {renderer} [built]
    + 19 hidden modules
Done in 2.17s.
  • electron-builder  version=21.2.0
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=better-sqlite3@5.4.3, integer@2.1.0 platform=win32 arch=x64
  • rebuilding native dependency  name=better-sqlite3 version=5.4.3
  • rebuilding native dependency  name=integer version=2.1.0
  ⨯ cannot execute  cause=exit status 1
                    out=yarn run v1.17.3
    $ node-gyp rebuild

    alexa@PCA C:\Users\alexa\awel-personal\node_modules\integer
    $ if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
    Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
      integer.cpp
      win_delay_load_hook.cc
    c:\users\alexa\.electron-gyp\6.0.8\include\node\v8.h(8207): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\integer.cpp) [C:\Users\alexa\awel-personal\node_modules\integer\build\integer.vcxproj]
      c:\users\alexa\.electron-gyp\6.0.8\include\node\v8.h(6668): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\integer.cpp)
    c:\users\alexa\.electron-gyp\6.0.8\include\node\v8.h(8216): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\integer.cpp) [C:\Users\alexa\awel-personal\node_modules\integer\build\integer.vcxproj]
      c:\users\alexa\.electron-gyp\6.0.8\include\node\v8.h(6668): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\integer.cpp)
    ..\src\integer.cpp(370): warning C4804: '-': unsafe use of type 'bool' in operation [C:\Users\alexa\awel-personal\node_modules\integer\build\integer.vcxproj]
    node.lib(node.exe) : fatal error LNK1112: module machine type 'ARM64' conflicts with target machine type 'x64' [C:\Users\alexa\awel-personal\node_modules\integer\build\integer.vcxproj]
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

                    errorOut=gyp info it worked if it ends with ok
    gyp info using node-gyp@5.0.3
    gyp info using node@12.10.0 | win32 | x64
    gyp info find Python using Python version 2.7.16 found at "C:\Python27\python.exe"
    gyp info find VS using VS2015 (14.0) found at:
    gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
    gyp info find VS run with --verbose for detailed information
    gyp info spawn C:\Python27\python.exe
    gyp info spawn args [
    gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'msvs',
    gyp info spawn args   '-I',
    gyp info spawn args   'C:\\Users\\alexa\\awel-personal\\node_modules\\integer\\build\\config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   'C:\\Users\\alexa\\.electron-gyp\\6.0.8\\include\\node\\common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=C:\\Users\\alexa\\.electron-gyp\\6.0.8',
    gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
    gyp info spawn args   '-Dnode_lib_file=C:\\Users\\alexa\\.electron-gyp\\6.0.8\\<(target_arch)\\node.lib',
    gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\alexa\\awel-personal\\node_modules\\integer',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'C:\\Users\\alexa\\awel-personal\\node_modules\\integer\\build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
    gyp info spawn args [
    gyp info spawn args   'build/binding.sln',
    gyp info spawn args   '/clp:Verbosity=minimal',
    gyp info spawn args   '/nologo',
    gyp info spawn args   '/p:Configuration=Release;Platform=x64'
    gyp info spawn args ]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:196:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    gyp ERR! System Windows_NT 10.0.18362
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\alexa\awel-personal\node_modules\integer
    gyp ERR! node -v v12.10.0
    gyp ERR! node-gyp -v v5.0.3
    gyp ERR! not ok
    error Command failed with exit code 1.

                    command='C:\Program Files\nodejs\node.exe' 'C:\Program Files (x86)\Yarn\bin\yarn.js' run install
                    workingDir=C:\Users\alexa\awel-personal\node_modules\integer
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

* **Electron Version:**
  * 6.0.8
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 6.0.7

### Expected Behavior
Project should build. This is how it works in v6.0.7:

```
alexa@PCA C:\Users\alexa\awel-personal
$ del yarn.lock && rmdir /s node_modules && yarn && yarn dev
C:\Users\alexa\awel-personal\yarn.lock konnte nicht gefunden werden
Möchten Sie "node_modules" löschen (J/N)? j
yarn install v1.17.3
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning react-json-view > flux > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
warning jest > jest-cli > prompts > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
warning jest > jest-cli > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning testcafe > testcafe-browser-tools > babel-runtime > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning testcafe-live@0.1.4: This module is now deprecated. In TestCafe v1.0.0, we have integrated features from the testcafe-live module into the main TestCafe code.
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "styled-components > stylis-rule-sheet@0.0.10" has unmet peer dependency "stylis@^3.5.0".
warning " > styled-components@5.0.0-beta.8" has unmet peer dependency "react-is@>= 16.8.0".
warning " > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning "@typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning " > eslint-config-react-app@5.0.1" has incorrect peer dependency "eslint-plugin-react-hooks@1.x".
[5/5] Building fresh packages...
success Saved lockfile.
$ yarn build-dll && electron-builder install-app-deps package.json && opencollective-postinstall
yarn run v1.17.3
$ cross-env NODE_ENV=development webpack --config ./configs/webpack.config.renderer.dev.dll.babel.js --colors

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

Hash: ec9f7e26dbadbc6e5407
Version: webpack 4.39.3
Time: 74ms
Built at: 2019-09-11 19:18:41
              Asset      Size    Chunks             Chunk Names
renderer.dev.dll.js  14.7 KiB  renderer  [emitted]  renderer
Entrypoint renderer = renderer.dev.dll.js
[0] dll renderer 12 bytes {renderer} [built]
[better-sqlite3] external "better-sqlite3" 42 bytes {renderer} [built]
[bootstrap] external "bootstrap" 42 bytes {renderer} [built]
[classnames] external "classnames" 42 bytes {renderer} [built]
[date-fns] external "date-fns" 42 bytes {renderer} [built]
[devtron] external "devtron" 42 bytes {renderer} [built]
[electron-debug] external "electron-debug" 42 bytes {renderer} [built]
[exceljs] external "exceljs" 42 bytes {renderer} [built]
[history] external "history" 42 bytes {renderer} [built]
[jquery] external "jquery" 42 bytes {renderer} [built]
[mobx] external "mobx" 42 bytes {renderer} [built]
[mobx-react-lite] external "mobx-react-lite" 42 bytes {renderer} [built]
[mobx-state-tree] external "mobx-state-tree" 42 bytes {renderer} [built]
[moment] external "moment" 42 bytes {renderer} [built]
[mst-middlewares] external "mst-middlewares" 42 bytes {renderer} [built]
    + 19 hidden modules
Done in 2.30s.
  • electron-builder  version=21.2.0
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=better-sqlite3@5.4.3, integer@2.1.0 platform=win32 arch=x64
  • rebuilding native dependency  name=better-sqlite3 version=5.4.3
  • rebuilding native dependency  name=integer version=2.1.0
Done in 110.97s.
yarn run v1.17.3
$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

Starting Main Process...

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3


> personal@1.2.3 start-main-dev C:\Users\alexa\awel-personal
> cross-env HOT=1 NODE_ENV=development electron -r @babel/register ./app/main.dev.js



WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

Done in 19.14s.
```

### Actual Behavior
See issue details.

### To Reproduce
- fork https://github.com/barbalex/awel-personal.git
- cd into the folder
- up electron version from 6.0.7 to 6.0.8
- run `yarn`

### Additional Information
Could be related to:
- https://github.com/electron/electron/issues/20198
- https://github.com/electron/electron/issues/20185

**Comment by jkleinsc** [comment] 2019-09-11 20:57
Closing as duplicate of #20185

**Closed by jkleinsc** 2019-09-11 20:57 UTC
