### ISSUE TITLE
[Bug]: Frameless window cannot resize if not focused

### ISSUE THREAD

**Issue by Nebula-Developer** [electron/electron#33466] opened 2022-03-28 02:38 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 (Home N) 19044.1586

### What arch are you using?

x64

### Expected Behavior

The window should resize as normal, without any problems.

### Actual Behavior

The cursor will display that it can resize, but will not do anything. I have to click on the inside of the window, then resize.
[https://streamable.com/uyy4e6](https://streamable.com/uyy4e6) Example

**Comment by Nebula-Developer** [comment] 2022-03-28 02:40
Its behavior changes each time I try to resize the window.

**Comment by codebytere** [comment] 2022-03-28 13:23
Duplicate of https://github.com/electron/electron/issues/33443

**Closed by codebytere** 2022-03-28 13:23 UTC
Labels: bug :beetle:, duplicate
