### ISSUE TITLE
Crash electron 2.0.4 -> Out of memory

### ISSUE THREAD

**Issue by burkoyuriy** [electron/electron#13750] opened 2018-07-20 07:17 UTC
OS Linux mint 17.3 xfce4 32bit
Purpose of the program: Image Viewer
When adding a 34 mb image to the DOM, the electron renderer process stops working.
Error:
[5456:0720/101129.927019:FATAL:memory.cc(22)] Out of memory. size=336060416

**Comment by computerquip-streamlabs** [comment] 2018-07-23 16:45
Perhaps related to https://github.com/electron/electron/issues/13467

**Comment by ckerr** [comment] 2018-07-30 16:13
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by computerquip-streamlabs** [comment] 2018-07-30 17:25
If I could reliably reproduce this, I would have fixed it months ago.

**Comment by burkoyuriy** [comment] 2018-07-31 10:50
App that reproduces the issue by itself:
npm i
npm start

https://drive.google.com/open?id=19PzRpCQXVqhRJsgtO8yFIunQrH0gmqPj

**Comment by groy** [comment] 2018-09-27 13:37
Also having this issue, seems to happen in our app once every 2-3 days of runtime. Not able to post any conde examples unfortunately.

**Comment by orendin** [comment] 2019-01-13 14:51
I'm also having this issue, on a raspberry pi 3 with raspbian. Simple Image Viewer, index page, cycling through pictures. At the start I thought it was the large image size, but it also happens with "smaller" images, ~4mbs. Seemingly at random, sometimes I get the error after 30minutes, sometimes after 5 minutes. I hope I find time to create a minimal sample reproducing the issue, and post it here.

**Comment by sofianguy** [comment] 2019-08-09 00:15
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:38
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:38 UTC
Labels: 2-0-x, blocked/need-info ❌, bug/crash :boom:, platform/linux

**Comment by gearcoded** [comment] 2020-12-09 11:46
I think I was able to reproduce the issue. By default, Electron uses the `/tmp` folder on Linux. When I delete that folder, Electron stops working with that error. It doesn't help if you create a new `/tmp` directory again.
I noticed that it creates a file `org.chromium.Chromium` + random symbols. That file is removed almost immediately.
So, if somehow the `/tmp` folder is deleted, Electron won't work until you restart it.

It seems to be a Chromium issue:
https://bugs.launchpad.net/ubuntu/+source/tmpreaper/+bug/1003186
https://bugs.chromium.org/p/chromium/issues/detail?id=44606

I tried to set the temp path like this:
```
app.setPath('temp', __dirname)
```
But it didn't help.

**Comment by Kyi-Moe-Min** [comment] 2021-04-03 05:31
@groy did you find the solution? I facing same issue

**Comment by groy** [comment] 2021-04-03 11:15
Hey, completely lost this thread after I found my solution. The issue was JavaScript memory leaks. Which are a PITA to find. I wrote a dev.to article about it afterwards. 

https://dev.to/groy/dealing-with-complex-memory-leaks-in-javascript-3g1b

**Comment by groy** [comment] 2021-04-03 11:17
@Kyi-Moe-Min ^^ tagging cause I forgot to in my post above.

**Comment by yashrajsapra** [comment] 2024-06-12 07:53
I'm also facing the same issue, I can see my application getting out of memory, 20times a day
