### ISSUE TITLE
Google Drive link won't open in webview

### ISSUE THREAD

**Issue by kotor96** [electron/electron#29264] opened 2021-05-20 16:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^11.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2

### What arch are you using?

x64

### Expected Behavior

When clicking https://drive.google.com/drive/my-drive inside a webview through on board of google apps,  the Google Drive home page should open

### Actual Behavior

The webview is blank and reloading the webview does nothing.

Use webview  tag in react

<webview       
        src={props.src}
        autosize="on">
</webview>

### Additional Information

I tried to test the:
1) behavior when loading https://drive.google.com/drive/my-drive from webview.loadURL(src) - normal
2) behavior when clicked link https://drive.google.com/drive/my-drive in google search inside webview - normal

**Comment by nornagon** [comment] 2021-06-22 22:57
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by nornagon** [comment] 2021-06-22 23:16
Duplicate of #29189

**Comment by nornagon** [comment] 2021-06-22 23:16
Marking as a duplicate of #29189, which has a repro.

**Closed by nornagon** 2021-06-22 23:16 UTC
Labels: blocked/need-repro, bug :beetle:
