### ISSUE TITLE
setDevToolsWebContents is not working for OOPIF webview

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#14095] opened 2018-08-14 21:45 UTC
It seems that Chromium disallows using guest view as devtools, I need to find out the code in Chromium to fix it.

```
not ok 55 <webview> tag setDevToolsWebContents() API sets webContents of webview as devtools
  AssertionError: expected '' to equal 'InspectorFrontendHostImpl'
      at Context.it (/Users/zcbenz/codes/electron/spec/webview-spec.js:721:26)
```

**Comment by kitze** [comment] 2019-06-07 08:02
@zcbenz does this mean that the only way to dock devtools is in a BrowserView until this is resolved?

**Comment by kitze** [comment] 2019-07-26 08:43
@zcbenz can you please confirm my question above when you have the time? 

I'm thinking of downgrading electron because so many users of [sizzy.co](https://sizzy.co) are requesting this option.

**Comment by kitze** [comment] 2019-07-26 08:46
@codebytere sorry I'm bringing you here but I'm not sure if **@zcbenz** is active and saw you were active on other issues. I'd appreciate an answer if you know what's going on.

**Comment by codebytere** [comment] 2019-07-26 15:03
@kitze no problem, ty for the ping. You're correct, the only current way to dock devtools is in a BrowserView at present. I can try to jump this up in my backlog within the next few weeks though and see if i can make some headway :)

**Comment by kitze** [comment] 2019-07-26 15:21
@codebytere thanks for the reply. That would be *amazing*. I'd be happy to do whatever it takes to help and resolve this issue. I was planning to set up a bounty on Bountysource so let me know if that might help. Thanks so much!

**Comment by sofianguy** [comment] 2019-08-09 23:03
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by kitze** [comment] 2019-08-11 10:52
@sofianguy the issue still exists in Electron 6.0, sorry if I didn't make that clear. When trying to render the devtools in a custom webview (by following the example in the docs), it doesn't work. 

Changing the Electron version back to 2.0 fixes the problem. 

I would really appreciate it if you don't close the issue.

**Comment by kitze** [comment] 2019-09-26 15:30
Hey @codebytere @sofianguy, I'm really glad this has moved to 6-0-x :) We have a big 1.0 release in a few weeks, and it would be amazing if we can add this feature to the app before the release. 

Do you have any idea if it might happen within that timeline? Is there anything that I can do to help? Can I maybe pay extra and sponsor someone to prioritize it? Thank you!

**Comment by codebytere** [comment] 2019-10-04 10:34
@kitze great q - the crux of this bug is that Chromium itself removed/disallowed this functionality and we're not quite sure where and how they did so.

It's unfortunately the sort of irritating bug that's way more grounded in annoying detective work than anything but i'm planning to spend a few hours on it today and will see what i come up with.

**Comment by kitze** [comment] 2019-10-04 14:34
Thanks so much, @codebytere, I appreciate the update! I'm popping champagne when this issue will be closed 😅

**Comment by Pines-Cheng** [comment] 2020-03-23 02:52
BrowserView instead work fine.

**Comment by kitze** [comment] 2020-03-24 08:09
@Pines-Cheng but you cannot use a BrowserView like you would a webview (like a DOM element)

**Comment by schacker** [comment] 2020-06-23 13:00
> BrowserView instead works fine.
@Pines-Cheng 
what is the version ?

**Comment by chemzqm** [comment] 2020-07-10 10:32
Still not work, use example code from https://www.electronjs.org/docs/api/web-contents#contentssetdevtoolswebcontentsdevtoolswebcontents and electron 9.1.0

**Comment by zhongkai** [comment] 2020-07-28 16:03
Still not work, use example code from https://www.electronjs.org/docs/api/web-contents#contentssetdevtoolswebcontentsdevtoolswebcontents and electron 9.1.1

**Comment by wyang0816** [comment] 2020-08-07 08:25
fix on Electon 9.1.2 please go https://github.com/electron/electron/issues/17168#issuecomment-670396592

**Comment by christlee1989** [comment] 2020-09-23 03:16
@kitze @codebytere still not work on electron 9.1.2
Is there a conclusion on this question?

**Comment by nornagon** [comment] 2022-03-03 22:45
Looks like this is fairly stale. I'm going to close this as there hasn't been any attention in a while; if this issue is still occurring on a [supported version](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions), please open a new issue with that info and link to this one.

**Closed by nornagon** 2022-03-03 22:45 UTC
Labels: component/devtools, component/webview, bug/regression :leftwards_arrow_with_hook:, 6-0-x, 6-1-x
