### ISSUE TITLE
BrowserWindow Maximizing

### ISSUE THREAD

**Issue by MunGaaKei** [electron/electron#10494] opened 2017-09-12 08:40 UTC
- electron version: 1.6.2
- os: windows 7

Okay, here's a problem I've met:
If I set the BrowserWindow with option "transparent: true", the function ".isMaximized()" always return the "false" value, which means I cant reset the window into its initial size.

**Comment by robinwassen** [comment] 2017-09-25 06:07
Duplicate of: #9092 

You might find more information about how people has worked around this issue there.

**Comment by sofianguy** [comment] 2018-08-22 20:41
please follow #9092 for updates

**Closed by sofianguy** 2018-08-22 20:41 UTC
Labels: bug :beetle:, platform/windows, version/1.6.x
