### ISSUE TITLE
React Developer Tools can not load using session apis

### ISSUE THREAD

**Issue by xalc** [electron/electron#23812] opened 2020-05-28 02:39 UTC
I use the electron 9.0.0 and using the session API to load the react development tools,
the core code as follow:
```
app.on('ready', () => {
  const reactExtension = path.join(os.homedir(), '/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.7.0_0');
  session.defaultSession.loadExtension(reactExtension).then(({ id }) => {
    logger.debug(`load react extension ${id}`);
  });
});
```
But it throw some warnings and the tool is not loaded:
```
load react extension fmkadmapgofadopljbjfkapdkoienihi
(node:18404) ExtensionLoadWarning: Warnings loading extension at /Users/xalc/Library/Application Support/Google/Chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.7.0_0: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'minimum_chrome_version'. Unrecognized manifest key 'update_url'. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system. 
```

**Comment by DmitryMK** [comment] 2020-06-02 20:55
This is a duplicate of [ #23662](https://github.com/electron/electron/issues/23662). Most likely you are loading your page via file:// protocol and it looks like it is impossible at the moment with Electron 9.x

**Comment by nornagon** [comment] 2020-06-02 21:11
Duplicate of #23662.

**Closed by nornagon** 2020-06-02 21:11 UTC
