### ISSUE TITLE
[Bug]: canvas getImageData Segmentation fault

### ISSUE THREAD

**Issue by rschlesser** [electron/electron#28762] opened 2021-04-21 15:02 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.10

### What arch are you using?

x64

### Last Known Working Electron version

9.4.4

### Expected Behavior

Calling getImageData on a canvas inside of the main process should not cause a segmentation fault.

### Actual Behavior

Calling getImageData on a canvas inside of the main process causes a segmenation fault and crashes the app.
This happens starting electron version 10.0.0-beta.1. Any version below 10.0.0-beta.1 seems to be fine.
Canvas Version: 2.7.0

app.js

`const  { createCanvas } = require("canvas")`
`const electron = require('electron');`
`const canvas = createCanvas(100, 100);`
`var ctx = canvas.getContext('2d');`
`ctx.rect(10, 10, 100, 100);`
`ctx.fill();`
`ctx.getImageData(50, 50, 100, 100);`

Results in:

> PID 338779 received SIGSEGV for address: 0x0
electron/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x3370)[0x7fd8e6a62370]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14bb0)[0x7fd8eceb1bb0]
electron/node_modules/electron/dist/electron exited with signal SIGSEGV

Fiddle not possible because of:

> .config/Electron Fiddle/electron-bin/12.0.5/electron: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory

**Comment by ckesselh** [comment] 2021-04-26 21:05
Here's what I get when I try to reproduce this problem using a custom (testing) build of Electron 12.0.5:

```
$ e start --version
Running "/home/ubuntu/electron/src/out/Testing/electron --version"
v12.0.5

$ ls 
app.js  package.json

$ npm install --save canvas
...

$ npm install --save-dev electron-rebuild
...

$ ./node_modules/.bin/electron-rebuild canvas --debug
...

$ e start app.js 
Running "/home/ubuntu/electron/src/out/Testing/electron app.js"

#
# Fatal error in ../../v8/src/objects/backing-store.cc, line 705
# Debug check failed: !result->second.lock().
#
#
#
#FailureMessage Object: 0x7ffcceac5c10
 1: 0x55e2f29854b2  [/home/ubuntu/electron/src/out/Testing/electron app.js]
 2: 0x55e2f0f2b6d8  [/home/ubuntu/electron/src/out/Testing/electron app.js]
 3: 0x55e2f0f2b2b5  [/home/ubuntu/electron/src/out/Testing/electron app.js]
 4: 0x55e2ebd54ea0  [/home/ubuntu/electron/src/out/Testing/electron app.js]
 5: 0x55e2ebd54806 v8::internal::BackingStore::~BackingStore() [/home/ubuntu/electron/src/out/Testing/electron app.js]
 6: 0x55e2eb9273e7  [/home/ubuntu/electron/src/out/Testing/electron app.js]
 7: 0x7f470c6134e6 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() [/home/ubuntu/app/node_modules/canvas/build/Debug/canvas.node]
 8: 0x7f470c612b15 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() [/home/ubuntu/app/node_modules/canvas/build/Debug/canvas.node]
 9: 0x7f470c611c9c std::__shared_ptr<v8::BackingStore, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() [/home/ubuntu/app/node_modules/canvas/build/Debug/canvas.node]
10: 0x7f470c611cbc std::shared_ptr<v8::BackingStore>::~shared_ptr() [/home/ubuntu/app/node_modules/canvas/build/Debug/canvas.node]
11: 0x7f470c611ddc Nan::TypedArrayContents<unsigned char>::TypedArrayContents(v8::Local<v8::Value>) [/home/ubuntu/app/node_modules/canvas/build/Debug/canvas.node]
12: 0x7f470c61d32e Context2d::GetImageData(Nan::FunctionCallbackInfo<v8::Value> const&) [/home/ubuntu/app/node_modules/canvas/build/Debug/canvas.node]
13: 0x7f470c5fe1cc  [/home/ubuntu/app/node_modules/canvas/build/Debug/canvas.node]
14: 0x55e2eb996c27  [/home/ubuntu/electron/src/out/Testing/electron app.js]
15: 0x55e2eb9953af  [/home/ubuntu/electron/src/out/Testing/electron app.js]
16: 0x55e2eb9935f5  [/home/ubuntu/electron/src/out/Testing/electron app.js]
17: 0x55e2eb9930da  [/home/ubuntu/electron/src/out/Testing/electron app.js]
18: 0x55e2ecb09e7f  [/home/ubuntu/electron/src/out/Testing/electron app.js]
Received signal 4 ILL_ILLOPN 55e2f0f31c92
#0 0x55e2ee286b39 base::debug::CollectStackTrace()
#1 0x55e2ee1ccc93 base::debug::StackTrace::StackTrace()
#2 0x55e2ee286691 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f47158b93c0 (/usr/lib/x86_64-linux-gnu/libpthread-2.31.so+0x153bf)
#4 0x55e2f0f31c92 v8::base::OS::Abort()
#5 0x55e2f0f2b6e5 V8_Fatal()
#6 0x55e2f0f2b2b5 v8::base::(anonymous namespace)::DefaultDcheckHandler()
#7 0x55e2ebd54ea0 v8::internal::GlobalBackingStoreRegistry::Unregister()
#8 0x55e2ebd54806 v8::internal::BackingStore::~BackingStore()
#9 0x55e2eb9273e7 std::__1::__shared_ptr_pointer<>::__on_zero_shared()
#10 0x7f470c6134e6 <unknown>
#11 0x7f470c612b15 <unknown>
#12 0x7f470c611c9c <unknown>
#13 0x7f470c611cbc <unknown>
#14 0x7f470c611ddc <unknown>
#15 0x7f470c61d32e <unknown>
#16 0x7f470c5fe1cc <unknown>
#17 0x55e2eb996c27 v8::internal::FunctionCallbackArguments::Call()
#18 0x55e2eb9953af v8::internal::(anonymous namespace)::HandleApiCallHelper<>()
#19 0x55e2eb9935f5 v8::internal::Builtin_Impl_HandleApiCall()
#20 0x55e2eb9930da v8::internal::Builtin_HandleApiCall()
#21 0x55e2ecb09e7f Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
  r8: 0000000000000000  r9: 000000000000004c r10: 000055e2e87b5cb8 r11: 0000000000000000
 r12: 000055e2e858d4f3 r13: 00007ffcceac5ed0 r14: 00000000000002c1 r15: 000055e2e83bed96
  di: 00007f47140c14b0  si: 0000000000000000  bp: 00007ffcceac5c00  bx: 00007f47140bf780
  dx: 0000000000000001  ax: 0000000000000000  cx: 0000000000000001  sp: 00007ffcceac5c00
  ip: 000055e2f0f31c92 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000006 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
ERROR Error: Command failed: /home/ubuntu/electron/src/out/Testing/electron app.js
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:15)
    at Command.<anonymous> (/home/ubuntu/.electron_build_tools/src/e:81:20)
    at Command.listener (/home/ubuntu/.electron_build_tools/node_modules/commander/index.js:291:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/home/ubuntu/.electron_build_tools/node_modules/commander/index.js:672:12)
    at Command.parse (/home/ubuntu/.electron_build_tools/node_modules/commander/index.js:459:21)
    at Object.<anonymous> (/home/ubuntu/.electron_build_tools/src/e:256:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)```

**Comment by ckesselh** [comment] 2021-04-27 17:04
I have now managed to isolate the problematic code to only 2 lines of C++. Maybe someone with more knowledge of V8 and Electron could take a closer look and let me know if this is indeed a bug and if so, in which component :-).

The 2 lines in question:
```
v8::Local<v8::ArrayBuffer> buffer = v8::ArrayBuffer::New(v8::Isolate::GetCurrent(), 1024);
std::shared_ptr<v8::BackingStore> hack = buffer->GetBackingStore();
```

I've uploaded a small sample project that may help to showcase the issue:
```
$ git clone https://github.com/ckesselh/electron-bug-sample
$ cd electron-bug-sample
$ npm i
$ npm run configure
$ npm run build
$ node --version
v14.16.0
$ node app.js 
String returned by native extension: This is a thing.

$ npm install --save-dev electron-rebuild
$ ./node_modules/.bin/electron-rebuild --force
$ e start --version
v12.0.5
$ e node --version
v14.16.0
$ e node app.js 
Running "/home/ubuntu/electron/src/out/Testing/electron app.js"

#
# Fatal error in ../../v8/src/objects/backing-store.cc, line 705
# Debug check failed: !result->second.lock().
#
#
#
#FailureMessage Object: 0x7ffe364e3280
 1: 0x55be7a50f4b2  [/home/ubuntu/electron/src/out/Testing/electron]
 2: 0x55be78ab56d8  [/home/ubuntu/electron/src/out/Testing/electron]
 3: 0x55be78ab52b5  [/home/ubuntu/electron/src/out/Testing/electron]
 4: 0x55be738deea0  [/home/ubuntu/electron/src/out/Testing/electron]
 5: 0x55be738de806 v8::internal::BackingStore::~BackingStore() [/home/ubuntu/electron/src/out/Testing/electron]
 6: 0x55be734b13e7  [/home/ubuntu/electron/src/out/Testing/electron]
 7: 0x7fd49c7ecc85 aHack(Nan::FunctionCallbackInfo<v8::Value> const&) [/home/ubuntu/dummy-project/build/Release/NativeExtension.node]
 8: 0x7fd49c7eb8e6  [/home/ubuntu/dummy-project/build/Release/NativeExtension.node]
 9: 0x55be73520c27  [/home/ubuntu/electron/src/out/Testing/electron]
10: 0x55be7351f3af  [/home/ubuntu/electron/src/out/Testing/electron]
11: 0x55be7351d5f5  [/home/ubuntu/electron/src/out/Testing/electron]
12: 0x55be7351d0da  [/home/ubuntu/electron/src/out/Testing/electron]
13: 0x55be74693e7f  [/home/ubuntu/electron/src/out/Testing/electron]
ERROR Error: Command failed: /home/ubuntu/electron/src/out/Testing/electron app.js
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:15)
    at Command.<anonymous> (/home/ubuntu/.electron_build_tools/src/e:108:20)
    at Command.listener (/home/ubuntu/.electron_build_tools/node_modules/commander/index.js:291:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/home/ubuntu/.electron_build_tools/node_modules/commander/index.js:672:12)
    at Command.parse (/home/ubuntu/.electron_build_tools/node_modules/commander/index.js:459:21)
    at Object.<anonymous> (/home/ubuntu/.electron_build_tools/src/e:256:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

**Comment by nornagon** [comment] 2021-04-27 18:58
This is because your extension isn't built with the same compiler and standard library as Electron itself. See also #28414. There aren't easy workarounds for this yet sadly, but at some point soon electron-rebuild will be updated to automatically use the correct compiler and build against libc++.

I'm closing this as #28414 captures the same issue.

**Closed by nornagon** 2021-04-27 18:58 UTC
Labels: 12-x-y, bug :beetle:, crash :boom:, platform/linux
