### ISSUE TITLE
setAsDefaultProtocolClient 'tel' and 'callto' does not work on Windows 10

### ISSUE THREAD

**Issue by maxleverin** [electron/electron#16106] opened 2018-12-17 17:52 UTC
**Isssue**
`tel` and `callto` links not opened in app despite having been registered with `setAsDefaultProtocolClient`

_It is very similar (identical?) to [this issue](https://github.com/electron/electron/issues/14108). It is 6 months old and has received 7 thumbs up but no further attention, hence this new attempt._

Specifics:
* Output of `node_modules/.bin/electron --version`:
_v.3.0.10_

* Operating System (Platform and Version):
_**Windows 10**
Version 1709
OS Build 16299.125_

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
_Not applicable_

**Expected Behavior**
`app.setAsDefaultProtocolClient('tel')` and `app.setAsDefaultProtocolClient('callto')` should make your application become available in the list of apps appearing when opening a `tel:` or `callto:` link.

**Actual behavior**
Application is not included in the list of apps appearing when clicking a tel or callto link.

**To Reproduce**
1. Download [the latest Electron demo (v2.0.1)](https://github.com/electron/electron-api-demos/releases/tag/v2.0.1)

2. In function `createWindow` found in `main.js`, add these two lines:
```
const defaultProtocolSet = app.setAsDefaultProtocolClient('tel'); //can also be set to 'callto' instead of 'tel'
console.log('defaultProtocolSet? ', defaultProtocolSet);
```

3. Open Windows's Command Prompt and run `npm install && run dev`
   You should now see _'defaultProtocolSet? true'_ in the Command Prompt window

4. Open a browser and in the address field enter `tel://0123456789`(replace number with number of your choice) and press return. Alternatively you can click on any `tel` link you have available.

Result:
A menu with a list of applications will be opened, but your app will not be represented here.

**Additional Information**
There does not seem to be a problem registering and opening custom protocol links, such as `'myOwnTestProtocol'`

Thanks for your time and consideration!

**Comment by MarshallOfSound** [comment] 2018-12-17 19:55
> It is very similar (identical?) to this issue. It is 6 months old and has received 7 thumbs up but no further attention, hence this new attempt.

This is a duplicate of that issue, please don't raise duplicates as a "new attempt".

**Closed by MarshallOfSound** 2018-12-17 19:55 UTC
