### ISSUE TITLE
Provide info about webcontent in a request to registered protocol

### ISSUE THREAD

**Issue by Gozala** [electron/electron#14806] opened 2018-09-25 20:17 UTC
**Is your feature request related to a problem? Please describe.**

At the moment it is impossible to identify a [WebContents](https://electronjs.org/docs/api/web-contents#class-webcontents) request originated from, in order to trigger, lets say, user permission prompt. In theory one could use [`webRequest.onBeforeSendHeaders`](https://electronjs.org/docs/api/web-request#webrequestonbeforesendheadersfilter-listener) handler to overcome this limitation but unfortunately that does not seem to work either as reported in #14804

**Describe the solution you'd like**
Ideally request passed to registered protocol handlers would contain same details as [`webRequest.onSendHeaders`](https://electronjs.org/docs/api/web-request#webrequestonsendheadersfilter-listener) handler.

**Describe alternatives you've considered**
Alternative would be to use [`webRequest.onBeforeSendHeaders`](https://electronjs.org/docs/api/web-request#webrequestonbeforesendheadersfilter-listener) and attach desired info to a request headers instead.

**Additional context**
In my use case I would like to get user consent before making requested data available (unless access was already granted) or deny access otherwise. At the moment I'm unable to display user prompt in the corresponding view as I'm unable to identify where request came from. At best I can iterate all the views and try to match by request origin but changes are there might be multiple matches there for there is no reliable solution to do this.

**Comment by marvin-martian** [comment] 2020-01-28 21:17
I was just thinking about a similiar issue. Ideally the webRequest method handlers should include the view or window id in the details so you can determine from where (which view/window) the webRequest was instigated from when you have multiple views/windows sharing the same session partition.

I noticed in the [Chrome webRequest documentation](https://developer.chrome.com/extensions/webRequest)  that in their details they do support multiple identifiers (tabId, parentFrameId, frameId) in their supplied details.

At the moment in electron the details.webContentsId is "optional" .. whatever that means, and the other id (details.id) just seems to be a counter. I am guessing the equivalent of details.id in Chrome is details.requestId.  The electron  documentation is pretty thin on explaining what these parameters are, and their expected behavior.

Ultimately I feel that the webRequest "onXYZ(...details)" methods in electron should also be just events that can have multiple listeners added like they do in Chrome.

**Comment by codebytere** [comment] 2020-03-28 03:39
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!

**Closed by codebytere** 2020-03-28 03:39 UTC
Labels: enhancement :sparkles:

**Comment by pushkin-** [comment] 2020-04-01 15:20
@codebytere Is someone volunteering a PR the only way this could get fixed, or could this be reopened if there's enough support for this enhancement (measured in Likes or something)?
