### ISSUE TITLE
set icon

### ISSUE THREAD

**Issue by hattatyazilim** [electron/electron#26619] opened 2020-11-20 19:49 UTC
`mainWindow.setIcon("./resources/icon.ico");`

When i deploy it does not work.

![Capture](https://user-images.githubusercontent.com/74716855/99843599-de48fc00-2b82-11eb-8361-5103a5a3938f.PNG)

**Comment by ckerr** [comment] 2020-11-20 20:18
Thanks for reporting this and helping to make Electron better!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Also, sould it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2021-01-05 21:32
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2021-01-05 21:32 UTC
Labels: blocked/need-info ❌, blocked/need-repro
