### ISSUE TITLE
Electron 5 & Puppeteer: Target.createTarget - Not supported

### ISSUE THREAD

**Issue by gaeldestrem** [electron/electron#17776] opened 2019-04-13 19:48 UTC
### Issue Details

* **Electron Version:**
  * v5.0.0-beta.8
* **Operating System:**
  * MacOS 10.14

### Actual Behavior
I'm trying to use puppeteer-core (v1.12.2) with Electron v5. I'm unable to create a new page through the remote-debugging-port. I encounter the following error `Error: Protocol error (Target.createTarget): Not supported` when using `await browser.newPage();`

Is there a security flag/option to enable or is it something that isn't supposed to work?

### To reproduce

```
app.commandLine.appendSwitch('remote-debugging-port', '8315')

async function fetchPage(url) {
    const response = await fetch(`http://localhost:8315/json/version`)
    const { webSocketDebuggerUrl } = await response.json();

    const browser = await puppeteer.connect({
        browserWSEndpoint: webSocketDebuggerUrl
    })	

     const page = await browser.newPage();
      ...
}
```

**Comment by peterdanis** [comment] 2019-04-30 19:58
@gaeldestrem were you able to launch electron with puppeteer atleast? I've played with electron and puppeteer before and for electron 4.x.x it worked (https://github.com/peterdanis/electron-puppeteer-demo). Now after upgrading to electron 5.0.0 I am getting error `Error: Protocol error (Page.enable)`.



Stack trace
`(node:9472) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.enable): Target closed.
    at C:\Projects\electron-puppeteer-demo\node_modules\puppeteer-core\lib\Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Projects\electron-puppeteer-demo\node_modules\puppeteer-core\lib\Connection.js:182:12)
    at Function.create (C:\Projects\electron-puppeteer-demo\node_modules\puppeteer-core\lib\Page.js:47:18)
    at C:\Projects\electron-puppeteer-demo\node_modules\puppeteer-core\lib\Target.js:71:32
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at async Promise.all (index 0)
    at async BrowserContext.pages (C:\Projects\electron-puppeteer-demo\node_modules\puppeteer-core\lib\Browser.js:304:19)
    at async Promise.all (index 0)
    at async Browser.pages (C:\Projects\electron-puppeteer-demo\node_modules\puppeteer-core\lib\Browser.js:233:26)`

**Comment by itsinprog** [comment] 2019-05-03 23:00
Possible Cause -
Since version v1.5.0, when Puppeteer connects to a browser it requests all existing browser
contexts with the Target.getBrowserContexts() protocol method.
Method Target.getBrowserContexts() is supposed to be implemented by content embedders.
Electron doesn't implement the method, so Puppeteer connect to electron fails (#3793).

Link to issue -- https://github.com/GoogleChrome/puppeteer/issues/4283

**Comment by hrivero8** [comment] 2019-06-29 15:12
Hi, the fix I found in https://stackoverflow.com/questions/55093700/electron-5-0-0-uncaught-referenceerror-require-is-not-defined

I have electron 5.0.4 and puppeteer 1.18.1

**Comment by lvkins** [comment] 2019-07-03 08:38
@hrivero8 I don't think it has anything to do with this issue. It doesn't solve it (at least for me) neither. Beeing trying several pupperteer version, including some ancient ones.

**Comment by hrivero8** [comment] 2019-07-03 09:24
I am using electron 5.0.4 and puppeteer 1.18.1

**Comment by lvkins** [comment] 2019-07-03 10:21
@hrivero8 Yes, I saw that. If it does really work for you, then thats one mystery because electron lacks some of protocol methods, hence it has no right to work. Could you provide a demo repository at least?

**Comment by hrivero8** [comment] 2019-07-03 18:20
First, I think that ensuring that the solution is not correct because I can't do this is not good, second, we are there to support us, not to point us out. I leave the code:

function createWindow(){
    win=new BrowserWindow({width:800,height:600,webPreferences: {
        nodeIntegration: true
            }
    });

<script src="jquery.min.js" onload="window.$ = window.jQuery = module.exports;"></script>

**Comment by caslt** [comment] 2019-07-23 09:34
if you want a workaround, you could try this closed PR.
https://github.com/GoogleChrome/puppeteer/pull/4720

I could connect to the existing chrome with --remote-debugging-port, and puppeteer v1.18.1

**Comment by electron-triage** [comment] 2020-02-19 20:00
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:21
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:21 UTC
Labels: 5-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS
