### ISSUE TITLE
Electron 4.x: Linux executable is not executable anymore

### ISSUE THREAD

**Issue by bpasero** [electron/electron#19162] opened 2019-07-09 07:11 UTC
This looks like a regression in Electron 4. In Electron 3 the electron file is executable, in 4 it is not.

![image](https://user-images.githubusercontent.com/900690/60866810-96456580-a229-11e9-8ec8-c0f2a3b4643a.png)

**Comment by malept** [comment] 2019-07-09 07:49
This is a duplicate of #15406, and the reason is described in one of its comments: https://github.com/electron/electron/issues/15406#issuecomment-435480303

**Closed by malept** 2019-07-09 07:49 UTC
