### ISSUE TITLE
A packaged app crashes on Windows when it's launched without a shell and calls createDataChannel of RTCPeerConnection in WebRTC

### ISSUE THREAD

**Issue by webarchymeta** [electron/electron#5629] opened 2016-05-20 19:27 UTC
* Electron version: 1.1.1
* Operating system: Windows 7

The system has no visual studio 2015 installed and the application is packaged using electron-packager.

When it crashes:

* Launched by double clicking the executable file or its shortcut (link) inside file explorer or on desktop

When it does not crash:

* Laucned inside of a Windows command shell.
* On Linux.

What was observed is that when `createDataChannel` is called on the system it was run, there are minor error log output, most likely through the stderr outlet. So maybe it has something to do with mis-handled stderr or stdout?

**Comment by zcbenz** [comment] 2016-05-22 07:23
Can you provide a minimal app that can reproduce this problem?

**Comment by webarchymeta** [comment] 2016-05-22 08:56
OK, I have product a simple app based on **electron-quick-start**, it can be cloned [here](https://github.com/webarchymeta/electron-quick-start). The version of electron-packager is 7.02. It crashes at line
```
createDataChannel
```

**Comment by zcbenz** [comment] 2016-05-23 08:09
I can reproduce with v1.1.1, and it seems to have been fixed in #5648.

**Comment by webarchymeta** [comment] 2016-05-24 06:53
is there any possibility to fix it in later versions that are based on chrome 50.x. I ask this because chrome 51.x is still in beta ...

**Comment by zcbenz** [comment] 2016-05-24 10:50
@webarchymeta Since it is fixed in Chrome 51 I'll not work on this, but I will accept PR that fixes this for Chrome 50.

And Chrome 51 will be stable very soon.

**Comment by feross** [comment] 2016-05-26 05:05
This was causing the WebTorrent Desktop team to pull out our hair. (We use WebRTC Data Channel extensively in WebTorrent.)

@zcbenz What was the source of the bug? Was it a bad merge? Because I don't believe that Chrome 50 has broken WebRTC support.

(cc @dcposch)

**Comment by zcbenz** [comment] 2016-05-26 05:18
@feross I don't have much idea of this bug. The Electron shipped with Chrome 51 is going to be released today, and I verified it would fix this.

Closed with #5648.

**Closed by zcbenz** 2016-05-26 05:18 UTC
Labels: bug, crash, windows

**Comment by dcposch** [comment] 2016-05-26 05:20
>  The Electron shipped with Chrome 51 is going to be released today

chrome 51 just got into the stable channel earlier today. thanks for the fast turnaround!

**Comment by feross** [comment] 2016-05-26 05:41
@zcbenz Great work, thanks!

**Comment by webarchymeta** [comment] 2016-05-30 08:08
Chrome 5.1 is still buggy (I can't play audio streams in certain cases). I rolled back to v1.1.3 which solved the problem...

**Comment by ManRueda** [comment] 2016-06-06 23:51
I'm having similar issues, with a simple ```let pc1 = new webkitRTCPeerConnection(servers);``` the application start having render issues.
The screen doesn't render my html/css properly. And sometime when i start electron with this code inside, the devtool shows some weird squares... 

![screenshot from 2016-06-06 20-48-49](https://cloud.githubusercontent.com/assets/2576444/15841494/2062646e-2c28-11e6-8bb8-029927c7f547.png)

I have enabled the chromium logging to the maximum and don't get nothing of interest.
