### ISSUE TITLE
[Bug]: Cannot load main.js when package.json contains "type":"module"

### ISSUE THREAD

**Issue by markddrake** [electron/electron#32616] opened 2022-01-25 20:29 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

Windows

### Operating System Version

Winows 11

### What arch are you using?

x64

### Expected Behavior

The Electron file "electron\dist\resources\default_app.asar\main.js" should determine when package.json contains "type":"module" and load the "main.js" via "import" rather than "require"

### Actual Behavior

Electron throws an exception when loading my application.

```
C:\Development\electron>npm  start

> yadamu@1.0.0 start
> electron ./


App threw an error during load
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Development\electron\main.js from C:\Development\electron\node_modules\electron\dist\resources\default_app.asar\main.js not supported.
C:\Development\electron\main.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename C:\Development\electron\main.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in C:\Development\electron\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at loadApplicationPackage (C:\Development\electron\node_modules\electron\dist\resources\default_app.asar\main.js:110:16)
    at Object.<anonymous> (C:\Development\electron\node_modules\electron\dist\resources\default_app.asar\main.js:222:9)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (node:electron/js2c/browser_init:193:3197)
    at Object../lib/browser/init.ts (node:electron/js2c/browser_init:193:3401)
    at __webpack_require__ (node:electron/js2c/browser_init:1:128)
    at node:electron/js2c/browser_init:1:1200
    at node:electron/js2c/browser_init:1:1267
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
Terminate batch job (Y/N)? C:\Development\electron\node_modules\electron\dist\electron.exe exited with signal SIGINT
```

Two files required 
#1: package.json
```
{
  "name": "yadamu",
  "type": "module",
  "version": "1.0.0",
  "description": "User Interface for YADAMU",
  "main": "main.js",
  "scripts": {
    "start": "electron ./"
  },
  "repository": {
    "type": "git",
    "url": "TBD"
  },
  "author": "Mark D Drake",
  "license": "SEE LICENSE IN TDB.txt",
  "dependencies": {
    "@electron/remote": "^2.0.1"
   
  },
  "devDependencies": {
    "electron": "^16.0.7"
  }
}
```
#2: main.js
```

// Modules to control application life and create native browser window
import  path = from 'path'
import  {app, BrowserWindow, ipcMain} from 'electron'
impport eRemote  from '@electron/remote/main'
eRemote.initialize()

app.on('ready', main)

async function main() {

}
```

Clearly this is a nonesense testcase, at it won't even open a window if the load succeeds, but I don't think it should fail in way it currently does

To reproduce create an empty folder containing the package.json and main.js files. 
run "npm import" followed by "npm start"

### Additional Information

Let me start of stating that I realize that there are several threads related using ES6 style modules with different versions of Electron.  For example, https://github.com/electron/electron/issues/9920#issuecomment-575839738. After reading them I decided to open a new one since a lot of them appear to reference older versions of electron where comprehensive and complete support for import was missing from the underlying electron component stack. 

I have a standalone testcase, attached. Not sure how to add a package.json to Electron Fiddle, so couldn't build a 'fiddle'.

**Comment by markddrake** [comment] 2022-01-25 20:38
Obviously changing main.js to main.cjs is non-started if the intent is to utilize ES6 modules, as doing so will simply throw 

```
C:\Development\electron>npm  start

> yadamu@1.0.0 start
> electron ./


App threw an error during load
C:\Development\electron\main.cjs:3
import  path = from 'path'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at loadApplicationPackage (C:\Development\electron\node_modules\electron\dist\resources\default_app.asar\main.js:110:16)
    at Object.<anonymous> (C:\Development\electron\node_modules\electron\dist\resources\default_app.asar\main.js:222:9)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
``
and I cannot change the contents of "\electron\dist\resources\default_app.asar\main.js"

**Comment by nornagon** [comment] 2022-01-25 20:39
Duplicate of #21457.

**Closed by nornagon** 2022-01-25 20:39 UTC
Labels: bug :beetle:
