### ISSUE TITLE
Login event doesn't trigger

### ISSUE THREAD

**Issue by WelaurS** [electron/electron#14480] opened 2018-09-06 16:15 UTC
* Output of `node_modules/.bin/electron --version`: 2.0.0
* Operating System (Platform and Version): MacOS High Sierra v10.13.4

**Expected Behavior**
Event triggering with the possibility to auth the proxy.

**Actual behavior**
Event doesn't trigger, `connected` work (see following code).

**To Reproduce**
Create app and try to login to private proxy.

```
    mainWindow = new BrowserWindow({
        width: 1440,
        height: 900,
        'web-preferences': {
            'web-security': false
        },
        titleBarStyle: 'hiddenInset'
    });

    mainWindow.webContents.session.setProxy({
        proxyRules: 'https://***.***.***.***:3333'
    }, function () {
        mainWindow.loadURL('https://www.whatismyip.com');
        console.log('connected');
    });

    mainWindow.webContents.on('login', (event, request, authInfo, callback) => {
        console.log('login event');
        if (authInfo.isProxy)
            callback('user', 'passwd');
    });
```

**Comment by nornagon** [comment] 2019-05-09 23:32
Closing as we no longer support 2.0.x. Feel free to reopen if you're still experiencing this issue in a [supported version of Electron](https://electronjs.org/docs/tutorial/support#supported-versions).

**Closed by nornagon** 2019-05-09 23:32 UTC
Labels: 2-0-x, bug :beetle:, platform/macOS

**Comment by WelaurS** [comment] 2019-05-09 23:36
:D

**Comment by dawiidio** [comment] 2020-01-10 22:31
I have exactly the same issue, with newer versions of electron and system. Above reproduce example seems to be still valid, my params:
Electron v7.0.0
macOS Catalina v10.15.2

It looks like neither http basic auth fires `login` event, so it's not only proxy case, it's probably much more generic. Same code executed on Ubuntu 18/19 works well.
