### ISSUE TITLE
Mac OS: setting parent window ignores show attribute and does not trigger ready-to-show

### ISSUE THREAD

**Issue by ionphractal** [electron/electron#9339] opened 2017-05-01 14:55 UTC
* Electron version: 1.4.16 1.6.6
* Operating system: Mac OS 10.11.6

### Expected behavior
When creating a new window, setting property "show" to false should make the window stay hidden unless show() is called. The window should also send 'ready-to-show' event once its done loading.

### Actual behavior
It works properly unless you set a parent window on Mac OS. On Linux and Windows it works as expected.

### How to reproduce
```bash
git clone https://github.com/ionphractal/electron-quick-start.git -b mac-show-bug
cd electron-quick-start
npm install
npm start || electron .
```

**Comment by kevinsawicki** [comment] 2017-05-01 15:44
I believe this is a duplicate of #8836, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2017-05-01 15:44 UTC
