### ISSUE TITLE
Is Electron following semver?

### ISSUE THREAD

**Issue by mafintosh** [electron/electron#5561] opened 2016-05-17 09:48 UTC
When developing apps for Electron I usually use [electron-prebuilt](https://github.com/electron-userland/electron-prebuilt) with npm and a semver to track updates. This makes it easier for me to update to newer versions of Electron without worrying too much about my app breaking.

However I just noticed that 1.0.2 was recently released and contained new features compared to 1.0.1, https://github.com/electron/electron/releases/tag/v1.0.2 and not just bug fixes.

Does this mean Electron isn't following semver? If so I'd like to know so I can start pinning the dependency.

**Comment by davej** [comment] 2016-05-17 10:12
+1. Even if it's not fully semver, I would be interested to know if there will potentially be breaking changes without a major version bump.

**Comment by zcbenz** [comment] 2016-05-17 10:31
Currently we're bumping version numbers with following rules:

* for Electron API breakage, bump major version;
* for major Chrome upgrades, minor Node upgrades, significant Electron changes, behavior changes, bump minor version;
* for new features and bug fixes, bump patch version;

So no, we are not following semver in Electron for now. We only guarantee there is no API changes between major version bumps, but Chrome and Node.js updates can still introduce breaking changes.

Currently for nearly every release of Electron, we are adding lots of things. If we follow semver strictly, the version number of Electron would be something like 32.15.0. I don't think it is better than what we have now, from current version number of Electron you can know:

* every patch version bump means bug fixes and new things, it is safe to upgrade;
* minor version bumps are dangerous, your app is supposed to still work, but you have to check carefully for possible breaks;
* major version bump means there are API changes of Electron, and you have to modify your app to run with it.

I think the root problem is we are adding new too fast, and publishing new releases too frequently. The only time when a new release only includes fixes is when we back-port fixes to old versions, or hot-fixing the latest release, which rarely happens. So following semver becomes meaningless in our case.

We should probably document explicitly that we are not following semver, and people should always use fixed version number.

**Comment by davej** [comment] 2016-05-17 11:09
Personally I don't have a problem with version numbers like `v32.15.0`. I understand it's messy from a general user standpoint (i.e. If this was Atom and not Electron) but I think most developers understand what this means.

Anyway, thanks for defining this. Even if Electron doesn't follow semver, it's good to know what to expect and I understand that releasing Electron 2.0 (because of the new Node major version) a few days after the big 1.0 milestone might feel a bit odd.

**Comment by maxogden** [comment] 2016-05-17 11:37
Agree the comment from @zcbenz above should go into the docs. Having a custom semantic meaning for versions that looks like semver but is actually something else is kind of misleading, so user education becomes more important.

**Comment by jprichardson** [comment] 2016-05-17 13:08
> I think the root problem is we are adding new too fast, and publishing new releases too frequently.

You can never publish new releases too quickly. Please don't change this. If you hold them back and then submit new releases less frequently, it's going to be very painful for people to upgrade and pin down where problems are. Frequent releases makes it really easy to track down what's causing the problem.

> Personally I don't have a problem with version numbers like v32.15.0.

Nor do I. Case in point, Chrome.

> Agree the comment from @zcbenz above should go into the docs. Having a custom semantic meaning for versions that looks like semver but is actually something else is kind of misleading, so user education becomes more important.

I also agree with this. It is a bit misleading, so clearly documenting the meaning of the version numbers is important.

**Comment by felixrieseberg** [comment] 2016-05-17 18:00
Y'all are super right, I just added a little document summarizing the rules and recommendations.

**Comment by gmaclennan** [comment] 2016-05-17 18:57
+1 to semver. Then people everybody knows what updates mean. If the downside is only having version numbers like v32.15.0, I'm not sure many developers would have a problem with that.

**Comment by feross** [comment] 2016-05-17 19:13
Why not this policy instead:

- **Major bump for:** Electron API breakage, Major Node upgrades
- **Minor bump for:** New features, Major Chrome upgrades (since these are never breaking -- you don't break the Web)
- **Patch bump for:** Bug fixes

This is intuitive to the Node.js/npm community and wouldn't make the version v32.x.x too quickly, since Major Node upgrades happen only every 6 months.

**Comment by jbenet** [comment] 2016-05-17 19:13
- semver is very good for machines and developers as an agreed-upon protocol to follow.
- for many humans, it is very good be clear when _very drastic_ **product** changes happen ("v1" to "v2", etc)

Re: "version numbers like v32.15.0", i understand and agree with the problem of saying "Electron v32". For this, consider this or something like it: 

> "[vanity semver](https://github.com/jbenet/random-ideas/issues/35)": `<vanity>.<major>.<minor>.<patch>`, where `<vanity>` is for marketing and the rest is for API changes.
>
> Eg. `1.32.15.0` or really, "Electron v1" with package-manager friendly semver `32.15.0`.

Some very relevant notes here, but i do not mean to derail. vanity semver [discussion can happen here](https://github.com/jbenet/random-ideas/issues/35), or another thread (many, many people have suggested this kind of a thing. there's some others).

- the vanity/marketing version number is very important for end users who want to know whether this is "Thing alpha (v0)", "Thing stable (v1)", or "Totally new, redone Thing (v2)".
- **semver is very important for clear understanding of APIs and compatibility in packaging / deployments / package managers.**
- adding another number is not a big deal, given how big version numbers for browsers are in general.
- can package all vanity under same semver, if  `<major>` remains monotonic, so `1.32.15.0`, `2.33.15.0`. can get packaged under semvers `32.15.0` and `33.15.0` just fine.
- or if you _really_ want to roll `<major>` back to 0 when making a `<vanity>` upgrade, make `<vanity>` part of the package name, eg `electron-prebuilt` and `electron-prebuilt-v2` once you make a marketing break.

**Comment by feross** [comment] 2016-05-17 19:16
> the vanity/marketing version number is very important for end users 

Disagree. Do users care that they're using OS X 10.11.4? They're using "Yosemite" or "El Capitan". Version numbers are for developers.

**Comment by ungoldman** [comment] 2016-05-17 19:29
@jbenet Adding a number is a big deal. When in doubt, use community standards. Electron is built on Node and npm, electron-prebuilt is distributed via npm, so I think it's wise to go with the [established standards](https://docs.npmjs.com/getting-started/semantic-versioning). A project with a `package.json` should respect the consequences of changing the version number w/r/t the default way that packages are added via `npm install --save`. Running `npm install electron-prebuilt --save` yields:

```
{
  ...
  "dependencies": {
    "electron-prebuilt": "^1.1.0"
  }
}
```

The `^` has implications that rely on a project adhering to semantic versioning. Marketing concerns should not be the primary driver when responsibly versioning a software product that is used exclusively by node developers.

**Comment by paulcbetts** [comment] 2016-05-17 19:31
> Major Chrome upgrades (these are never breaking)

This hasn't been our experience, upgrading just Chrome can definitely break your app

**Comment by jbenet** [comment] 2016-05-17 19:31
@feross

The named OS X releases include their proper version number distinctions, like "10.10" and "10.11", which form a vital part of major compatibility barriers for thousands of developers building for OS X. "Things should work" but often major breaking problems happen, and the effort required for a dramatic change like that is much larger than every time a single breaking change is committed. this applies to electron

"end users" there includes developers. There are different kinds of developers, with different kinds of expectations for versions. "I want to know the difference between a v1 and a v2, and that's not captured by semver" is something i've heard dozens (maybe hundreds?) of times from other developers. This is not all, but a sizable number of the people who know the value of semver and still choose not use it. 

---

@ungoldman please re-read. I'm strongly in favor of Electron using semver and packing exactly according to semver. I'm suggesting a compromise that enables the Electron team to layer any non-semver expectations separately.

**Comment by jbenet** [comment] 2016-05-17 19:32
Btw, i think @feross's suggestion here https://github.com/electron/electron/issues/5561#issuecomment-219823045 is a really good idea for Electron.

**Comment by paulcbetts** [comment] 2016-05-17 19:46
If we were to change the version number scheme, I propose that the major version follows the Chrome version directly, so we would immediately jump to `v50.0.0`, and that we only do node updates during Chrome updates. This would follow Semver rules as well as have the bonus side-effect of being able to tell the Chrome version from the Electron version.

This has the side-effect that means that breaking Electron API changes have to happen alongside a Chrome release, but tbh I consider that a Feature Not A Bug :)

**Comment by feross** [comment] 2016-05-17 19:49
> @paulcbetts Upgrading just Chrome can definitely break your app

Sure, but those changes also break the web -- real, deployed websites -- without any notice. Chrome is pretty conservative about that and usually only do it to bring Chrome in line with the spec. Examples: Chrome deprecations in [M49](https://developers.google.com/web/updates/2016/02/chrome-49-deprecations) and [M50](https://developers.google.com/web/updates/2016/03/chrome-50-deprecations).

> @paulcbetts I propose that the major version follows the Chrome version directly

This is better, because at least it's semver. But it has the effect of making most major version bumps "noise" since most Chrome updates don't break anything. Ah, tradeoffs...

**Comment by ungoldman** [comment] 2016-05-17 19:54
I think the path of least resistance is going with the current version scheme and number set while making sure new features are minor bumps and bug fixes are patch bumps, which is what most users expect. I think the question of how to manage Chrome and Node upgrades is a little out of the scope of this issue, however I will say I would not advise jumping from 1.x to 50.x 😉

**Comment by feross** [comment] 2016-05-17 20:05
Good point, @ungoldman. That's what @mafintosh's original issue was about -- new features ending up in a patch release.

**Comment by paulcbetts** [comment] 2016-05-17 21:30
> Sure, but those changes also break the web -- real, deployed websites -- without any notice. Chrome is pretty conservative about that and usually only do it to bring Chrome in line with the spec.

From a web perspective I'd totally agree, but from the actual implementation perspective it isn't the case. For example, at some point Chrome enabled DirectWrite by default on Windows, which meant that a certain group of people with garbage video cards went from a working app to something that was a fuzzy blurry mess.  Or for example, Chromium flags can completely change from major version to major version and if you're relying on a certain behavior, you're broken. Or in M48ish, Flash was completely deprecated, even if you tried to enable it via flags - if your app was working before, now it's :fire:

**Comment by feross** [comment] 2016-05-17 22:15
> @paulcbetts Interesting, thanks for the context.

**Comment by zcbenz** [comment] 2016-05-18 00:30
Chrome upgrades are breaking changes, every time we upgrade Chrome version there are crashes and regressions, so if we follow semver it has to bump the major version. The same goes for Node upgrades, and probably toolchain upgrades (like from Visual Studio 2013 to 2015).

The problem with following semver is, we will not be able to distinguish Electron API changes from dependencies upgrades, all of them are bumping major versions. They are two different levels of changes, you have to modify your app for Electron API changes, while you can probably just do nothing to get Chrome upgrades.

Keep current version scheme but bump minor version for new features, is nice but doesn't quite suit Electron's current situation. For most releases of Electron we are adding new features, so if we use this rule there will basically be no patch version bumps, and users will not be able to judge whether it is safe to upgrade Electron when there are minor version bumps.

**Comment by mafintosh** [comment] 2016-05-18 02:11
If Chrome upgrades are potentially breaking changes I'd personally just bump the major version every time you upgrade Chrome in Electron. Node already follows semver so you only need to bump the major when node does. New API features are a minor bump and bug fixes a patch.

Pros: Easy for developers to identify breaking changes + a community standard + works with npm defaults
Cons: Potentially higher version numbers.

I don't really understand why having a higher major version number is an issue personally.

If I want to figure if it is safe to upgrade to a new major version I'll read the CHANGELOG. I already do this for Node anyway.

**Comment by baconface** [comment] 2016-05-18 04:22
I disagree that Chrome/Node updates should bump the major. The difference with breaking API changes is they can be planned. Chrome/Node breaking changes are not always planned and more of a side effect. And the goal of updating them is to not break things but fix/improve things in the upstream. They are also updated quite often. Bumping the major version often I feel would degrade the importance of the major number.

Exceptions could be made if the breaking changes made by Chrome/Node are major. But making them control the major with every change goes against and breaks the versioning system rather than resolves it.

**Comment by ljharb** [comment] 2016-05-18 09:12
The major number *has* no importance, except to convey breaking changes from the previous one. It's semantic versioning, not sentimental versioning.

**Comment by baconface** [comment] 2016-05-18 16:35
> The major number has no importance, except to convey breaking changes from the previous one. It's semantic versioning, not sentimental versioning.

The importance _is_ to convey breaking changes. And updating Chrome and and Node.js are not always breaking changes or always intended to be breaking changes.

**Comment by ljharb** [comment] 2016-05-18 18:23
Sure, you'd only break it for a user-visible breaking change - but that includes ABI compatibility as well as JS features, which updating chrome and major versions of node are almost guaranteed to break.

**Comment by ungoldman** [comment] 2016-11-15 18:27
I think this question has now been appropriately addressed in the documentation http://electron.atom.io/docs/tutorial/electron-versioning/ -- safe to close?

**Comment by kevinsawicki** [comment] 2016-11-15 18:30
> safe to close?

I think so, closing this out, thanks everyone for the valuable discussion here.

**Closed by kevinsawicki** 2016-11-15 18:30 UTC
Labels: discussion

**Comment by paranoidjk** [comment] 2017-09-12 09:35
I suggest you guys document in readme that electron do not obey semver.

Right now electron 1.8.0 released , but actullay it's a beta release according realease note and npm, dist-tag, but consider Facebook react-devtool https://github.com/facebook/react-devtools/blob/master/packages/react-devtools/package.json#L26

**Comment by MarshallOfSound** [comment] 2017-09-12 12:16
@paranoidjk https://github.com/electron/electron/blob/master/docs/tutorial/electron-versioning.md

FWIW I generally advise people to lock the patch version as well (enforce a single version)
