### ISSUE TITLE
How to send "Enter" keypress event?

### ISSUE THREAD

**Issue by binux** [electron/electron#8977] opened 2017-03-21 11:34 UTC
* Electron version: v1.6.2
* Operating system: macOS

### Expected behavior

```
{
  "type": "keypress",
  "isTrusted": true,
  "init": {
    "key": "Enter",
    "code": "Enter",
    "charCode": 13,
    "keyCode": 13,
    "which": 13
  }
}
```

And no text written in input box.

### Actual behavior

```
{
  "type": "keypress",
  "isTrusted": true,
  "init": {
    "key": "Enter",
    "code": "Enter",
    "charCode": 69,
    "keyCode": 69,
    "which": 69
  }
}
```

And text "EnteEnte" written in input box

### How to reproduce

```
const {app, BrowserWindow} = require('electron')

app.on('ready', () => {
  let win = new BrowserWindow();
  win.loadURL(`data:text/html,<input><script>
      function eventToJSON(event) {
        const ret = {
          type: event.type,
          isTrusted: event.isTrusted,
          init: {
            key: event.key,
            code: event.code,
            charCode: event.charCode,
            keyCode: event.keyCode,
            which: event.which,
          }
        };
        console.log(ret);
        return ret;
      };
      const input = document.querySelector('input');
      input.focus();
      let event = null;
      input.addEventListener('keypress', e => event = eventToJSON(e));
      </script>`);
  win.webContents.on('did-finish-load', async () => {
    win.webContents.sendInputEvent({ type: 'char', keyCode: 'Enter' });
    await new Promise(r => setTimeout(r, 200));
    win.webContents.executeJavaScript('event', (result) => {
      console.log(result);
    });
  });
});
```

BTW: I found a workaround by reading the [source code](https://github.com/electron/electron/blob/master/atom/common/keyboard_util.cc#L26): `sendInputEvent({type: 'char', keyCode: String.fromCharCode(0x0D)})`, but sending a string instead of an Enter keypress with `sendInputEvent({ type: 'char', keyCode: 'Enter' })` is not what I expected.

**Comment by zcbenz** [comment] 2017-06-14 11:47
The `key` passed to `sendInputEvent` must be a single character, the mappings of accelerators are not support in `sendInputEvent` (I'm not sure whether we should add the support). We probably need to make the document more clear.

Closing since it is expected behavior.

**Closed by zcbenz** 2017-06-14 11:47 UTC
Labels: fixme/bug

**Comment by binux** [comment] 2017-06-15 02:25
@zcbenz The document said: 
> keyCode String (required) - The character that will be sent as the keyboard event. Should only use the valid key codes in Accelerator.
Accelerator said:
> Available key codes
> Return (or Enter as alias)

I think it's clear but wrong in document.

**Comment by jbmonroe** [comment] 2018-02-08 20:41
Unfortunately I don't think it's clear at all.  What does the structure that gets send to sendInputEvent for the Enter or Return key look like?  I'm trying to build a virtual keyboard for a kiosk and no permutation or combination of values I send produces the desired result.  I either get EnteEnte or an exception thrown because some code under the hood doesn't like the event object I send.

**Comment by FibreFoX** [comment] 2018-09-14 09:02
@jbmonroe I had this issue too, the electron documentation is flawed here!

To workaround this, I had to use [RobotJS](https://github.com/octalmage/robotjs/) to simulate some special keys:
```js
// keyData.key is coming from a function call from a different location, which gets passed to a webview in React
let inputEventToPass = {
    type: 'char',
    keyCode: keyData.key
};
if ( keyData.key === 'ENTER') {
    inputEventToPass = {
        type: 'char',
        keyCode: '\u000d',
        // @ts-ignore
        charCode: 13
    };
}
if ( keyData.key === 'BACKSPACE') {
    let robot = require('robotjs');
    robot.keyTap('backspace');
    /*
    // does not work
    inputEventToPass = {
        type: 'char',
        keyCode: 'Backspace'
    };
    */
    return;
}
if ( keyData.key === 'DELETE') {
    let robot = require('robotjs');
    robot.keyTap('delete');
    /*
    // does not work
    inputEventToPass = {
        type: 'char',
        keyCode: 'Delete'
    };
    */
    return;
}

// @ts-ignore
this.webviewRef.current.sendInputEvent(inputEventToPass);
```

@zcbenz maybe there should be a statement in the documentation, that these special keys are not "sendable", or a hint how to actually send these keys/chars.

**Comment by jbmonroe** [comment] 2018-09-14 13:36
I could probably live without the Enter key but the lack of Page Up and Page Down makes the customer and the users unhappy.

I'll look into RobotJS to see how much fuss would be involved in adding it to the project (we're just about to completion and the interval before we upload the "final" release is very short).  For future projects, this could be exactly what I need.

**Comment by parkerdan** [comment] 2019-12-20 17:10
This issue should be re-opened.

The documentation is **NOT** clear
