### ISSUE TITLE
[Bug]: Headers are getting lost in protocol.interceptBufferProtocol

### ISSUE THREAD

**Issue by amitmisratas** [electron/electron#34243] opened 2022-05-15 09:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

When we use protocol.interceptBufferProtocol and return the header values to the callback function... 

ses.protocol.interceptBufferProtocol("https", async (req, callback) => {
                    const request2 = net.request(req)
                    request2.on('response', res => {
                        const chunks = []
                        var headers = res.headers;
                        res.on('data', chunk => {
                            chunks.push(Buffer.from(chunk))
                        })
                        res.on('end', async () => {
                            const file = Buffer.concat(chunks)
                            callback({data: file, headers: headers})
                        })
                    })
 });

The headers values are not being read... and therefore "set-cookie" headers are also being lost and the cookies are not at all being saved when we intercept HTTPS protocol... 

Ideally, these values should be respected in the callback function and they should be returned to the browserWindow so that page can set headers appropriately even if we are using interceptBufferProtocol functionality.

### Actual Behavior

When we use protocol.interceptBufferProtocol and pass on the the header values to the callback function... 

ses.protocol.interceptBufferProtocol("https", async (req, callback) => {
                    const request2 = net.request(req)
                    request2.on('response', res => {
                        const chunks = []
                        var headers = res.headers;
                        res.on('data', chunk => {
                            chunks.push(Buffer.from(chunk))
                        })
                        res.on('end', async () => {
                            const file = Buffer.concat(chunks)
                            callback({data: file, headers: headers})
                        })
                    })
 });

The headers values are not being read... and therefore "set-cookie" headers are also being lost and the cookies are not at all being saved when we intercept HTTPS protocol...

**Comment by vladimiry** [comment] 2022-05-15 13:02
Also see #13228.

**Comment by codebytere** [comment] 2022-05-16 07:45
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed** 2022-05-26 09:58 UTC
Labels: platform/windows, component/protocol, bug :beetle:, blocked/need-repro, 18-x-y

**Comment by jonnytest1** [comment] 2022-10-03 12:18
i made a gist https://gist.github.com/8cef0bf0632a0b2d5e2cf67e913b83d5
