### ISSUE TITLE
Form controls have incorrect focus color in 9.0

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#23853] opened 2020-05-30 02:55 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.0.0
* **Operating System:** macOS 10.14.6
* **Last Known Working Electron version:** 8.3.0

### To Reproduce

* Create any page with an `<input>`, `<textarea>`, or other control, open it in Electron, and focus it.

### Expected Behavior

The control should have a blue outline, as it does in Chrome 83:

<img width="587" src="https://user-images.githubusercontent.com/10314059/83318021-c8233a00-a1f6-11ea-9485-f47595a0fbd2.png">

### Actual Behavior

The control has an orange outline:

<img width="714" src="https://user-images.githubusercontent.com/10314059/83318032-d6715600-a1f6-11ea-8dc6-dc7a7f3c0bcc.png">

**Comment by codebytere** [comment] 2020-06-03 20:43
Duplicate of https://github.com/electron/electron/issues/23768.

**Closed by codebytere** 2020-06-03 20:43 UTC

**Comment by PalmerAL** [comment] 2020-06-03 20:47
@codebytere I think it's a different issue; that issue is about form controls always being blue regardless of the accent color preferences, whereas the issue I'm having is that the controls are orange (instead of the standard blue color).

This works correctly in Chrome for me (but not Electron), so I think there's something in Electron that's causing this beyond the changes that Chrome made to form controls.

**Comment by MarshallOfSound** [comment] 2020-06-03 20:56
Upgrade your version of Chromium.  This is part of their new form control styles.

https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html

**Comment by PalmerAL** [comment] 2020-06-03 21:09
@MarshallOfSound I'm running the latest version of Chrome, and I'm seeing the new form controls there as well. The issue is that the new form controls are rendering differently in Electron than they are in Chrome.

Here's what the new controls look like in Chrome 83.0.4103.97 (with :focus set on each one in the devtools):

<img width="503" src="https://user-images.githubusercontent.com/10314059/83689225-48112180-a5b4-11ea-84a3-ff8fb81304f7.png">

And here's what they look like in Electron 9.0.2:

<img width="510" src="https://user-images.githubusercontent.com/10314059/83689249-52cbb680-a5b4-11ea-99cb-b8deb3ba08b4.png">

The value of the accent color preference doesn't affect either Chrome or Electron's rendering.

**Comment by PalmerAL** [comment] 2020-06-04 18:05
@MarshallOfSound could this be re-opened?

**Comment by YingXue** [comment] 2020-12-08 18:31
I am also seeing the issue with Electron 9.0.2
