### ISSUE TITLE
[Bug]: history.back() does nothing after refresh

### ISSUE THREAD

**Issue by jlongster** [electron/electron#28933] opened 2021-04-29 14:21 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

macOS

### Operating System Version

11.1

### What arch are you using?

x64

### Expected Behavior

EDIT: This issue was fixed in the comments, but now see this comment: https://github.com/electron/electron/issues/28933#issuecomment-829311747

When pushing state with a location change like this:

```
  history.pushState(
    { counter:  1 },
    null,
    '/ok'
  );
```

The location state `counter` should consistently persist across reloads and navigating back and forth. The app should also never freeze.

### Actual Behavior

EDIT: This issue was fixed in the comments, but now see this comment: https://github.com/electron/electron/issues/28933#issuecomment-829311747

See the gist for example app, I'm going to post screenshots of it here.

## Refreshing the page

Initial app:

<img width="348" alt="Screen Shot 2021-04-29 at 10 06 06 AM" src="https://user-images.githubusercontent.com/17031/116563981-8e5d2680-a8d2-11eb-901c-075263ff46d1.png">

When I press `Click foo` the app now looks like this, meaning the location now has state:

<img width="368" alt="Screen Shot 2021-04-29 at 10 06 43 AM" src="https://user-images.githubusercontent.com/17031/116564051-a03ec980-a8d2-11eb-8564-ff00cb33bf7a.png">

However, if **I refresh the page** it loses state:

<img width="329" alt="Screen Shot 2021-04-29 at 10 07 07 AM" src="https://user-images.githubusercontent.com/17031/116564152-b64c8a00-a8d2-11eb-808a-1430724dd4ee.png">

This is unlike all other browsers where the state the kept.

## Going back

Let's do the same thing when navigating back. Starting with some state:

<img width="323" alt="Screen Shot 2021-04-29 at 10 11 25 AM" src="https://user-images.githubusercontent.com/17031/116564782-48ed2900-a8d3-11eb-93ae-c3150be4680e.png">

Pressing "back" does properly go back to the previous state:

<img width="331" alt="Screen Shot 2021-04-29 at 10 11 15 AM" src="https://user-images.githubusercontent.com/17031/116564824-50accd80-a8d3-11eb-83df-bce3fb59aab9.png">

## Combining refresh and going back

Here's where things get weird. Let's start with pressing "Click foo" twice:

<img width="323" alt="Screen Shot 2021-04-29 at 10 12 12 AM" src="https://user-images.githubusercontent.com/17031/116564943-69b57e80-a8d3-11eb-94c7-e49758f6472a.png">

Now press "back":

<img width="331" alt="Screen Shot 2021-04-29 at 10 13 49 AM" src="https://user-images.githubusercontent.com/17031/116565181-9f5a6780-a8d3-11eb-8276-31254cc68c96.png">

Now refresh the page, the state is kept!

<img width="324" alt="Screen Shot 2021-04-29 at 10 14 05 AM" src="https://user-images.githubusercontent.com/17031/116565234-ac775680-a8d3-11eb-8c79-15a3ca70b93b.png">

However, **refreshing again** loses the state!

<img width="324" alt="Screen Shot 2021-04-29 at 10 14 37 AM" src="https://user-images.githubusercontent.com/17031/116565317-bef19000-a8d3-11eb-8777-21ae7e2f16ba.png">

There's a really weird inconsistent behavior here: it _sometimes_ keeps the state but for the most part, it does not.

## Window freezing

There's a more significant problem in my app that I could not reproduce in the simple app. The renderer window completely hangs after pushing/popping state a few times, and then refreshing the page. In this example, the modal opens because I used `pushState` to go to a new URL and passed some state telling the app to open it in a modal. To close the modal, all it needs to do is run `history.back`. However, after doing that, if I refresh the page the renderer window completely hangs. I have to restart the app. It's definitely not an infinite loop or something in my code, I've double-checked it and I'm sure it has something to do with the location state.

Sorry I wasn't able to reproduce this in the simple app, but I'm hoping if the code is looked at you will keep this in mind. I'm happy to answer any more questions about the code used here.

Video of freezing:

https://user-images.githubusercontent.com/17031/116566205-8ef6bc80-a8d4-11eb-9743-61ce608bff33.mp4

### Testcase Gist URL

https://gist.github.com/jlongster/c727d96ca9a4b6623627c56b610f1c2a

**Comment by Prinzhorn** [comment] 2021-04-29 14:43
Are you by any chance setting `app.allowRendererProcessReuse = false;`? It defaults to `true` since 10.0.0. I cannot reproduce this with `app.allowRendererProcessReuse = true; ` only with `false`.

**Comment by Prinzhorn** [comment] 2021-04-29 15:22
`webContents.goBack() `does not work either in this case even though `webContents.canGoBack() === true`

This does look like a bug to me, so you might want to make a self contained Fiddle gist for the Electron team to look into this. You can push `'?yeah'` instead of `/yeah` to make it work with the `file:///` protocol.

> Hah, you're welcome! I had forgotten about that. Did it help your app?

Indeed, it changed my view on Electron application architecture entirely and everything is smooth now.

**Comment by jlongster** [comment] 2021-04-29 15:32
> This does look like a bug to me, so you might want to make a self contained Fiddle gist for the Electron team to look into this. You can push `'?yeah'` instead of `/yeah` to make it work with the `file:///` protocol.

👍  I can try to do that later today

Also good to mention - I'm not using the `file:///` protocol. I've installed a custom protocol and loading my app like `app://actual/` so I can use normal browser history with things like `react-router`. In my test, the page didn't even flash. I'll make a small test case

> Indeed, it changed my view on Electron application architecture entirely and everything is smooth now.

Awesome!

**Comment by Prinzhorn** [comment] 2021-04-29 15:34
I was testing with both `file:///` and `http://localhost:8080` so the protocol shouldn't matter

**Comment by obermillerk** [comment] 2021-07-01 17:05
I'm also experiencing this issue, which is very annoying. I think this might not be tied to the state directly, but rather the history object itself. After refresh `history.length` is 1, regardless of what it was before. My guess is it sees length 1 and doesn't think there's anything to go back to, regardless of what the `state`'s `position` says. Interestingly, as noted  before, adding history by navigating and then going back (meaning we end up where we were right after refresh) _does_ allow going back from the original refresh position again, and the history length jumps up to what it probably should be. I think `length` is likely the culprit here, it needs to be retained after refresh.

![electron-history-length-bug](https://user-images.githubusercontent.com/28601113/124162862-f663f080-da6c-11eb-9955-cbcb0c72659f.png)

This is also present in electron 13.1, which is where I got that screenshot.

**Comment by nornagon** [comment] 2021-07-06 19:02
@obermillerk Would you be able to try this out on the v14 beta? https://github.com/electron/electron/pull/28839 is in v14 which significantly changes the navigation logic.

**Comment by obermillerk** [comment] 2021-07-06 19:26
Sure, I can give it a shot in a few hours

**Comment by obermillerk** [comment] 2021-07-06 19:31
Nevermind that, I just tried it, it is fixed in the v14 beta.

**Comment by nornagon** [comment] 2021-07-06 19:46
Great, I'm going to close this then. Given the nature of that change, unfortunately we're not able to backport it to v13 and earlier, but this will be fixed from v14 onward.

**Closed by nornagon** 2021-07-06 19:46 UTC
Labels: 12-x-y, bug :beetle:, has-repro-gist, platform/macOS

**Comment by obermillerk** [comment] 2021-07-06 21:27
@nornagon Sounds good. Just curious, is there any roadmap for when v14 might be stable? Sorry if there's an obvious answer to that...

**Comment by nornagon** [comment] 2021-07-06 21:41
https://www.electronjs.org/docs/tutorial/electron-timelines
