### ISSUE TITLE
[Bug]: Cannot respond to click events when setting -webkit-app-region: drag on Mac

### ISSUE THREAD

**Issue by CryUshio** [electron/electron#38817] opened 2023-06-16 03:13 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.4

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.3.7

### Expected Behavior

Respond to click events when setting -webkit-app-region: drag on Mac

### Actual Behavior

Cannot respond to click events when setting -webkit-app-region: drag on Mac

**Comment by ivanggq** [comment] 2023-06-16 14:32
I believe this ticket is a duplicate of #37789 .

**Comment by codebytere** [comment] 2023-06-16 18:36
Duplicate of https://github.com/electron/electron/issues/37789

**Closed by codebytere** 2023-06-16 18:36 UTC
Labels: platform/macOS, bug :beetle:, 25-x-y
