### ISSUE TITLE
tls.socket.write: data not sent even if which is written to kernel buffer on windows

### ISSUE THREAD

**Issue by leewill1120** [electron/electron#7042] opened 2016-08-31 07:28 UTC
- Electron version:v1.3.4
- Operating system:windows 7 sp1 64bit
  
  I develop a linux shell with electron and xterm.js.
  That't ok when I connect linux with net.socket.
  But when tls.socket, I got a problem which I cannot use command 'passwd' to change password. I found that the whole word 'passwd' cannot send to server, only 'p' is sent. The others are written to kernel buffer and socket.write returns true. I‘m so confused. 
  I try it on linux(CentOS 7.2) with same electron version and configures, the problem is gone.

**Comment by zcbenz** [comment] 2016-09-01 04:45
The problem is probably in the module you use, does this happen if you run the code in Node?

**Comment by leewill1120** [comment] 2016-09-02 01:56
@zcbenz I did some tests(xterm.js is not used),  I found data can be sent when delay time is zero, cannot be sent when delay time is non-zero (e.g. 1000ms). By the way I got the socket from request.on('upgrade', ...):
```
req.on('upgrade', (res, socket, upgradeHead) => {
        $scope.socket = socket;
       //....
})
```

My test code:
```
$scope.test = function() {
        var delay = 1000;
        $scope.socket.write('passwd\n');

        setTimeout(function() {
            //send password after delay ms
            $scope.socket.write('1', () => { //1
                console.log('1 sent');
                $scope.socket.write('23456', () => { //123456
                    console.log('23456 sent');
                    $scope.socket.write('\n', () => { //123456\n
                        console.log('\\n sent');
                        $scope.socket.write('123456\n'); //123456\n
                    });
                });
            });
        }, delay);
    }
```

Output:
when delay is 0:
```
1 sent
23456 sent
\n sent
```
There's no output when delay is 1000.

P.S. other linux commands are ok, only 'passwd' command has this problem

**Comment by zcbenz** [comment] 2016-09-12 05:51
I can't see what's going from your description, can you provide a minimal app that can reproduce this problem?

**Comment by kevinsawicki** [comment] 2016-11-16 23:44
Closing this out until more information is provided.

**Closed by kevinsawicki** 2016-11-16 23:44 UTC
Labels: more-information-needed
