### ISSUE TITLE
Can't change locale

### ISSUE THREAD

**Issue by r4tz52** [electron/electron#20196] opened 2019-09-11 02:56 UTC
### Issue Details

* **Electron Version:**
  * 6.0.8
* **Operating System:**
  * Windows 10 (1809)

### Expected Behavior
*app.getLocale()* should return value passed to *app.commandLine.appendSwitch('lang', VALUE)*

### Actual Behavior
*app.getLocale()* always returns *'en-US'*

### To Reproduce
```
const app = require('electron').app;
app.commandLine.appendSwitch('lang', 'ja');
app.on('ready', () => console.log('locale:', app.getLocale()));
```

### Additional Information
As far as I see, it was broken many versions ago. Is there any workaround or fixes?

**Comment by DeerMichel** [comment] 2019-09-11 12:19
Closing this as a duplicate of https://github.com/electron/electron/issues/17995.

**Closed by DeerMichel** 2019-09-11 12:19 UTC
