### ISSUE TITLE
There was a problem when I tried to use this API

### ISSUE THREAD

**Issue by zpzxgcr** [electron/electron#12681] opened 2018-04-21 11:44 UTC
* Electron version:1.8.4
* Operating system:win7 64

* Last known working Electron version: 1.8.4

### Expected behavior

successful replication of different types of data.
### How to reproduce
code:  clipboard.write({text: 'first', html: '<b>last</b>'})
 just copied the first data.
use the [api:](https://electron.atom.io/docs/api/clipboard/#clipboardwritedata-type)

**Comment by codebytere** [comment] 2018-04-22 02:44
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue. You said that there was an issue with the clipboard API, but it's not clear what exactly the issue is and what exactly you expected to happen.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by zpzxgcr** [comment] 2018-04-22 02:53
`var clipboard = require('electron').clipboard `
`clipboard.write({text: 'first', html: 'last'})`
The paste board content shows 'first'

I'm using the official demo.
@codebytere thanks

**Comment by zpzxgcr** [comment] 2018-05-06 08:41
Look forward to a quick settlement @codebytere

**Comment by sofianguy** [comment] 2019-01-07 20:46
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:21
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-01-15 20:21 UTC
Labels: blocked/need-info, bug :beetle:, platform/windows, version/1.8.x
