### ISSUE TITLE
Electron transparent window use maximize() can not emit 'maximize' event

### ISSUE THREAD

**Issue by wunairuoshi** [electron/electron#12854] opened 2018-05-08 03:16 UTC
* Electron Version: 2.0.0
* Operating System (Platform and Version): windows 8.1
* Last known working Electron version: none

**Expected Behavior**
I create a browerwindow with frame: false and transparent: true, when i use maximize(), i need the event 'maximize' and isMaximized() return true.

**Actual behavior**
no event emited, and isMaximize() return false.

**Comment by ckerr** [comment] 2018-05-08 03:29
@wunairuoshi, thanks for reporting this issue!

Would it be possible for you to create a small test app -- e.g., forking https://github.com/electron/electron-quick-start and adding a few lines -- for the Electron team to test with?

**Comment by ZaDarkSide** [comment] 2019-07-15 22:59
This is still happening for Electron 5.0.6 very old bug that wasn't been fixed.

**Comment by a1292999652** [comment] 2019-08-28 09:21
I also encountered this problem in Electron 6.02, transparent: true in Windows10 will lead to isMaximized() being false all the time

**Comment by OuyangZq** [comment] 2019-09-11 10:16
watching and waiting +1

**Comment by chenjietao** [comment] 2020-03-21 15:43
I wrote a plug-in to fix this problem. See [electron-frameless-window-plugin](https://www.npmjs.com/package/electron-frameless-window-plugin). In fact, I rewrote several  methods of BrowserWindow instance, including `getNormalBounds()`, `maximize()`, `unmaximize()` and `isMaximzed()`. And I've added some features to make frameless windows work better. Such as disable the menu when right clicking the drag region.

**Comment by DuannHang** [comment] 2020-05-03 02:45
楼上老哥，真佩服你！

**Comment by codebytere** [comment] 2020-06-19 00:47
Duplicate of https://github.com/electron/electron/issues/23275

**Closed by codebytere** 2020-06-19 00:47 UTC
Labels: 6-0-x, 6-1-x, bug :beetle:, platform/windows

**Comment by AmrBinBashir** [comment] 2020-06-22 05:48
@chenjietao thanks, man. you're a life saver.

**Comment by Nihilop** [comment] 2021-01-09 13:25
> I wrote a plug-in to fix this problem. See [electron-frameless-window-plugin](https://www.npmjs.com/package/electron-frameless-window-plugin). In fact, I rewrote several methods of BrowserWindow instance, including `getNormalBounds()`, `maximize()`, `unmaximize()` and `isMaximzed()`. And I've added some features to make frameless windows work better. Such as disable the menu when right clicking the drag region.

Genius !

**Comment by TechWorldInc** [comment] 2021-04-28 21:43
> I wrote a plug-in to fix this problem. See [electron-frameless-window-plugin](https://www.npmjs.com/package/electron-frameless-window-plugin). In fact, I rewrote several methods of BrowserWindow instance, including `getNormalBounds()`, `maximize()`, `unmaximize()` and `isMaximzed()`. And I've added some features to make frameless windows work better. Such as disable the menu when right clicking the drag region.
> 
> Code:
> 
> ```js
>   if (win.webContents.browserWindowOptions.transparent) {
>     // rewrite getNormalBounds, maximize, unmaximize and isMaximized API for the transparent window
>     let resizable = win.isResizable()
>     let normalBounds = win.getNormalBounds ? win.getNormalBounds() : win.getBounds()
> 
>     win.getNormalBounds = function () {
>       if (!this.isMaximized()) {
>         if (BrowserWindow.prototype.getNormalBounds) {
>           normalBounds = BrowserWindow.prototype.getNormalBounds.call(this)
>         } else {
>           normalBounds = BrowserWindow.prototype.getBounds.call(this)
>         }
>       }
>       return normalBounds
>     }.bind(win)
> 
>     win.maximize = function () {
>       normalBounds = this.getNormalBounds() // store the bounds of normal window
>       resizable = this.isResizable() // store resizable value
>       BrowserWindow.prototype.maximize.call(this)
>       if (!BrowserWindow.prototype.isMaximized.call(this)) {
>         // while isMaximized() was returning false, it will not emit 'maximize' event
>         this.emit('maximize', { sender: this, preventDefault: () => {} })
>       }
>       this.setResizable(false) // disable resize when the window is maximized
>     }.bind(win)
> 
>     win.unmaximize = function () {
>       const fromMaximized = BrowserWindow.prototype.isMaximized.call(this)
>       BrowserWindow.prototype.unmaximize.call(this)
>       if (!fromMaximized) {
>         // isMaximized() returned false before unmaximize was called, it will not emit 'unmaximize' event
>         this.emit('unmaximize', { sender: this, preventDefault: () => {} })
>       }
>       this.setResizable(resizable) // restore resizable
>     }.bind(win)
> 
>     win.isMaximized = function () {
>       const nativeIsMaximized = BrowserWindow.prototype.isMaximized.call(this)
>       if (!nativeIsMaximized) {
>         // determine whether the window is full of the screen work area
>         const bounds = this.getBounds()
>         const workArea = electron.screen.getDisplayMatching(bounds).workArea
>         if (bounds.x <= workArea.x && bounds.y <= workArea.y && bounds.width >= workArea.width && bounds.height >= workArea.height) {
>           return true
>         }
>       }
>       return nativeIsMaximized
>     }.bind(win)
>   }
> ```

Wonderful job, this is the key to near perfect transparent frameless windows, mainly for use with say for example a window that needs border-radius. I love this plugin and will be using it very often. Thanks, @chenjietao

**Comment by paddotk** [comment] 2022-06-26 15:25
@chenjietao Thanks, it doesn't seem to work (anymore) though. For one, `browserWindowOptions` has been removed from `win.webContents`, and when I remove this check (and adding `const electron = require('electron');` at the top of my main.js file) it makes the window act weirdly when maximizing/unmaximizing; but the `maximize`, `unmaximize` and `minimize` events are not fired.

**Comment by distant-xingsu** [comment] 2023-07-08 14:57
win.unmaximize = function () {
    const fromMaximized = BrowserWindow.prototype.isMaximized.call(this)
    BrowserWindow.prototype.unmaximize.call(this)
    if (!fromMaximized) {
      // isMaximized() returned false before unmaximize was called, it will not emit 'unmaximize' event
      this.emit('unmaximize', { sender: this, preventDefault: () => {} })
      win.setContentSize(normalBounds.width,normalBounds.height)
      win.setPosition(normalBounds.x,normalBounds.y)
    }
    this.setResizable(resizable) // restore resizable
  }.bind(win)

**Comment by distant-xingsu** [comment] 2023-07-08 14:57
`win.unmaximize = function () {
    const fromMaximized = BrowserWindow.prototype.isMaximized.call(this)
    BrowserWindow.prototype.unmaximize.call(this)
    if (!fromMaximized) {
      // isMaximized() returned false before unmaximize was called, it will not emit 'unmaximize' event
      this.emit('unmaximize', { sender: this, preventDefault: () => {} })
      win.setContentSize(normalBounds.width,normalBounds.height)
      win.setPosition(normalBounds.x,normalBounds.y)
    }
    this.setResizable(resizable) // restore resizable
  }.bind(win)`

**Comment by distant-xingsu** [comment] 2023-07-08 14:57
`
win.unmaximize = function () {
    const fromMaximized = BrowserWindow.prototype.isMaximized.call(this)
    BrowserWindow.prototype.unmaximize.call(this)
    if (!fromMaximized) {
      // isMaximized() returned false before unmaximize was called, it will not emit 'unmaximize' event
      this.emit('unmaximize', { sender: this, preventDefault: () => {} })
      win.setContentSize(normalBounds.width,normalBounds.height)
      win.setPosition(normalBounds.x,normalBounds.y)
    }
    this.setResizable(resizable) // restore resizable
  }.bind(win)
`

**Comment by distant-xingsu** [comment] 2023-07-08 14:59
```javascript
win.unmaximize = function () {
    const fromMaximized = BrowserWindow.prototype.isMaximized.call(this)
    BrowserWindow.prototype.unmaximize.call(this)
    if (!fromMaximized) {
      // isMaximized() returned false before unmaximize was called, it will not emit 'unmaximize' event
      this.emit('unmaximize', { sender: this, preventDefault: () => {} })

      // add+
      win.setContentSize(normalBounds.width,normalBounds.height)
      win.setPosition(normalBounds.x,normalBounds.y)

    }
    this.setResizable(resizable) // restore resizable
  }.bind(win)
```

**Comment by winchestercanal** [comment] 2025-01-29 13:40
> Escrevi um plug-in para corrigir esse problema. Ver [plug-in de janela sem estrutura eletrônica](https://www.npmjs.com/package/electron-frameless-window-plugin). . Na verdade, reescrevi vários métodos de instância do BrowserWindow, inclusive `getNormalBounds()`, `maximize()`, `unmaximize()` e `isMaximzed()`. E adicionei alguns recursos para fazer com que as janelas sem moldura funcionem melhor. Como desabilitar o menu ao clicar com o botão direito na região de arrastar.
> 
> Código:
> 
>   se (ganhar.conteúdos Web.browserWindowOpções.transparente) {
>     // reescrever getNormalBounds, maximizar, desmaximizar e isMaximized API para a janela transparente
>     deixar redimensionável = ganhar.é redimensionável()
>     deixar limites normais = ganhar.obterLimites normais ? ganhar.obterLimites normais() : ganhar.obter limites()
> 
>     ganhar.obterLimites normais = função () {
>       se (!isto.isMaximizado()) {
>         se (Janela do navegador.protótipo.obterLimites normais) {
>           limites normais = Janela do navegador.protótipo.obterLimites normais.ligar(isto)
>         } outra outra {
>           limites normais = Janela do navegador.protótipo.obter limites.ligar(isto)
>         }
>       }
>       retorno limites normais
>     }.ligar(ganhar)
> 
>     ganhar.maximizar = função () {
>       limites normais = isto.obterLimites normais() // armazene os limites da janela normal
>       redimensionável = isto.é redimensionável() // armazenar valor redimensionável
>       Janela do navegador.protótipo.maximizar.ligar(isto)
>       se (!Janela do navegador.protótipo.isMaximizado.ligar(isto)) {
>         //enquanto isMaximized () estava retornando falso, ele não emitirá evento 'maximizar'
>         isto.emitir('maximizar', { remetente: isto, prevenir padrão: () => {} })
>       }
>       isto.definirResizável(falso) //desativar redimensionar quando a janela estiver maximizada
>     }.ligar(ganhar)
> 
>     ganhar.não maximizar = função () {
>       const doMaximizado = Janela do navegador.protótipo.isMaximizado.ligar(isto)
>       Janela do navegador.protótipo.não maximizar.ligar(isto)
>       se (!doMaximizado) {
>         // isMaximized () retornou falso antes de unmaximize foi chamado, ele não vai emitir 'unmaximize' evento
>         isto.emitir('desmaximizar', { remetente: isto, prevenir padrão: () => {} })
>       }
>       isto.definirResizável(redimensionável) // restaurar redimensionável
>     }.ligar(ganhar)
> 
>     ganhar.isMaximizado = função () {
>       const nativoIsMaximizado = Janela do navegador.protótipo.isMaximizado.ligar(isto)
>       se (!nativoIsMaximizado) {
>         //determinar se a janela está cheia da área de trabalho do ecrã
>         const limites = isto.obter limites()
>         const área de trabalho = elétron.tela.getDisplayMatching(limites).área de trabalho
>         se (limites.x <= área de trabalho.x && limites.y <= área de trabalho.y && limites.largura >= área de trabalho.largura && limites.altura >= área de trabalho.altura) {
>           retorno verdadeiro
>         }
>       }
>       retorno nativoIsMaximizado
>     }.ligar(ganhar)
>   }

como faço para usar sua soluçao?

> I wrote a plug-in to fix this problem. See [electron-frameless-window-plugin](https://www.npmjs.com/package/electron-frameless-window-plugin). In fact, I rewrote several methods of BrowserWindow instance, including `getNormalBounds()`, `maximize()`, `unmaximize()` and `isMaximzed()`. And I've added some features to make frameless windows work better. Such as disable the menu when right clicking the drag region.
> 
> Code:
> 
>   if (win.webContents.browserWindowOptions.transparent) {
>     // rewrite getNormalBounds, maximize, unmaximize and isMaximized API for the transparent window
>     let resizable = win.isResizable()
>     let normalBounds = win.getNormalBounds ? win.getNormalBounds() : win.getBounds()
> 
>     win.getNormalBounds = function () {
>       if (!this.isMaximized()) {
>         if (BrowserWindow.prototype.getNormalBounds) {
>           normalBounds = BrowserWindow.prototype.getNormalBounds.call(this)
>         } else {
>           normalBounds = BrowserWindow.prototype.getBounds.call(this)
>         }
>       }
>       return normalBounds
>     }.bind(win)
> 
>     win.maximize = function () {
>       normalBounds = this.getNormalBounds() // store the bounds of normal window
>       resizable = this.isResizable() // store resizable value
>       BrowserWindow.prototype.maximize.call(this)
>       if (!BrowserWindow.prototype.isMaximized.call(this)) {
>         // while isMaximized() was returning false, it will not emit 'maximize' event
>         this.emit('maximize', { sender: this, preventDefault: () => {} })
>       }
>       this.setResizable(false) // disable resize when the window is maximized
>     }.bind(win)
> 
>     win.unmaximize = function () {
>       const fromMaximized = BrowserWindow.prototype.isMaximized.call(this)
>       BrowserWindow.prototype.unmaximize.call(this)
>       if (!fromMaximized) {
>         // isMaximized() returned false before unmaximize was called, it will not emit 'unmaximize' event
>         this.emit('unmaximize', { sender: this, preventDefault: () => {} })
>       }
>       this.setResizable(resizable) // restore resizable
>     }.bind(win)
> 
>     win.isMaximized = function () {
>       const nativeIsMaximized = BrowserWindow.prototype.isMaximized.call(this)
>       if (!nativeIsMaximized) {
>         // determine whether the window is full of the screen work area
>         const bounds = this.getBounds()
>         const workArea = electron.screen.getDisplayMatching(bounds).workArea
>         if (bounds.x <= workArea.x && bounds.y <= workArea.y && bounds.width >= workArea.width && bounds.height >= workArea.height) {
>           return true
>         }
>       }
>       return nativeIsMaximized
>     }.bind(win)
>   }

How do I use your solution?
