### ISSUE TITLE
app.makeSingleInstance returns true even for the first instance, sometimes

### ISSUE THREAD

**Issue by webarchymeta** [electron/electron#5294] opened 2016-04-26 07:24 UTC
* Electron version: 0.37.7
* Operating system: Windows 64, Ubuntu 14.04, 15.10

One of the application of us packaged with electron 0.37.7 will quit silently before seeing the window when run. The cause is found, using debugger on a ubuntu 14.04 virtual machine, to be  `app.makeSingleInstance` in the main.js file returns true even for the first instance of the program. All the machines having the problem had not run (or "installed") the program before. After down grade to 0.37.6 and re-package, the program startup OK and the problem disappears. Then, after upgrade to 0.37.7 again the problem also does not re-appear (due to this reason, it never manifests on our development machine and other old machines having used to program packaged with lower versions of electron). It is found that the problem is still there even for a very simple probram with empty main page and almost empty main.js.

Any ideas?

**Comment by zcbenz** [comment] 2016-04-26 07:44
This is a duplicate of #5289.

**Closed by zcbenz** 2016-04-26 07:44 UTC

**Comment by webarchymeta** [comment] 2016-04-26 09:30
I don't understand how they are related??

**Comment by zcbenz** [comment] 2016-04-26 10:36
@webarchymeta I was pasting the wrong issue number.
