### ISSUE TITLE
Transparent frame on Ubuntu

### ISSUE THREAD

**Issue by Vatanay** [electron/electron#26030] opened 2020-10-19 09:52 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.3
* **Operating System:**
  * Ubuntu 20.04 x64
* **Last Known Working Electron version:**
  * 4.0.5

### Expected Behavior
I'm trying to create a transparent Electronjs frame on Ubuntu.

### Actual Behavior
Black background

`const { app, BrowserWindow } = require('electron')

function createWindow () {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    frame: false,  // open for original windows state
    transparent: true,
    webPreferences: {
      nodeIntegration: true
    }
  })

  win.loadFile('index.html')
  //win.webContents.openDevTools()
}

app.whenReady().then(createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})`

### Screenshots
![Screenshot from 2020-10-19 12-49-07](https://user-images.githubusercontent.com/51656705/96429371-89276c80-1209-11eb-8592-256156047940.png)

**Comment by ckerr** [comment] 2020-10-19 18:15
I'm closing this issue as it appears to be a duplicate of #25153. If this is in error, please reopen / refile. Thanks!

**Closed** 2020-10-19 18:48 UTC
