### ISSUE TITLE
Path with '(' problem

### ISSUE THREAD

**Issue by doganmurat** [electron/electron#9756] opened 2017-06-14 13:01 UTC
* Electron version: 1.6.11
* Operating system: Windows 64 Bit

### Expected behavior

On start open index.html from asar archieve

### Actual behavior

If path contains "(" electron could not load index.html on startup. (like C:\Program Files (x86)\Program)

### How to reproduce
Change directory name with a name that contains "("

**Comment by codebytere** [comment] 2018-02-02 14:42
Please confirm that this is still occurring in more recent versions

**Comment by codebytere** [comment] 2018-02-23 14:02
We haven't gotten a response to our questions in our comment. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2018-02-23 14:02 UTC
Labels: more-information-needed, platform/windows, version/1.6.x

**Comment by ckerr** [comment] 2018-02-23 16:49
FWIW I'm unable to reproduce this using a build from master on Linux, e.g. if I put `electron-api-demos` in a directory named `/tmp/(foo)` and try to run it:

`$ ./out/D/electron /tmp/\(foo\)/electron-api-demos/`

This runs correctly
