### ISSUE TITLE
Window still showing when display set to false

### ISSUE THREAD

**Issue by stoneRdev** [electron/electron#20352] opened 2019-09-27 07:53 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.7
* **Operating System:**
  * Lastest Arch Linux (`pacman -Syu` is on cron every 24hr)
* **Last Known Working Electron version:**
  * v6.0.7
### Expected Behavior

Expect window created with `show: false` to not be displayed

### Actual Behavior

Window created with `show:false` is immediately shown anyways
### To Reproduce

The code I am using is:
```

const {app, BrowserWindow,screen} = require('electron')
const path = require('path')

let ui = {}
app.on('ready',() => {
    console.log('App Ready')
    ui.els = require('electron-localshortcut');
     const { width, height } = require('screen').screen.getPrimaryDisplay().workAreaSize
    ui.window = new BrowserWindow({
      width,
      height,
      title: 'Vast',
      backgroundColor: '#2e2c29',
      frame: false,
      fullscreen: true,
      show: false,
      webPreferences: {
        nodeIntegration: true
      }
    })
    ui.els.register(ui.window,'F12',()=> {
        console.log('got f12')
        ui.window.webContents.openDevTools()
    })
    ui.window.loadURL(path.resolve(__dirname,'./test.html'))
    ui.window.on('closed',() => {
        console.log('Window Closed')
      ui.window = null
    })
    ui.window.once('ready-to-show',() => {
        console.log('Window Ready to show')
        // This is never reached because window is already displayed.
        // The line below was commented out to prove that the window is being displayed on its own
        //ui.window.show()
        console.log('Window Displayed')
    })    
})
```
The html file is just a static (and valid) hello world template

**Comment by stoneRdev** [comment] 2019-09-27 08:47
So, after more digging / testing, I have found that this is somehow due to a collision between the `fullscreen: true` and `show:false` properties in the constructor call. That has been circumvented by removing `fullscreen:true` from the constructor call and using `ui.window.setFullScreen(true)` in `'ready-to-show'` event. However, this raised a new problem. The `'ready-to-show'` event is never fired, even though the window is not  displayed. It sounds it's related to [this](https://github.com/electron/electron/issues/7779). I will keep looking for a temp fix.

**Comment by stoneRdev** [comment] 2019-09-27 10:22
After two hours of digging through documentation and various testing, we cant get it to work. Instead, we have  opted to allow the screen to start white and fade the window to the background color using css animations (on the body element). This looks good and is acceptable for our use case. If anyone is interested, here is the css:
```
body {
   background-color: white;    
   -webkit-animation: body_background 3s linear both;
  animation: body_background 3s linear both
}
@keyframes body_background {
  from {background-color: white;}
  to {background-color: black;}
}

```

**Comment by scottnonnenberg-signal** [comment] 2019-11-14 23:01
My testing indicates that `maximized: true` can also conflict with `show: false`.

**Comment by MarkNjunge** [comment] 2020-01-15 10:36
Still an issue on `7.1.9` with `maximixed: true`.  

The issue does not occur on MacOS.

**Comment by 04a391c1b7aa** [comment] 2020-02-15 09:56
This issue also applies to 7.x and 8.x.

**Comment by codebytere** [comment] 2020-03-04 00:47
A window which is fullscreen cannot also be un-shown, and neither can it be maximized. All three of those are mutually exclusive states; this is not a bug. If you are experiencing a separate issue with event emission, you're welcome to open a new issue, but I'm closing this out in the meantime.

**Closed by codebytere** 2020-03-04 00:47 UTC
Labels: 6-1-x, bug :beetle:, platform/linux
