### ISSUE TITLE
[Bug]: a frame showing before create frameless window

### ISSUE THREAD

**Issue by dube116** [electron/electron#32202] opened 2021-12-16 02:39 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1

### What arch are you using?

x64

### Last Known Working Electron version

12.0.15

### Expected Behavior

directly show a frameless window

### Actual Behavior

![LUAmfIS](https://user-images.githubusercontent.com/8154554/146297296-5dde7b79-85c7-4601-9fd4-e4efdc1a80b7.gif)

### Additional Information

main,js
```
const { app, BrowserWindow, } = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    frame: false
  })
}

app.whenReady().then(() => {
    createWindow()
})
```
titleBarStyle: 'hidden also trigger this

**Comment by YasharNmadar** [comment] 2021-12-17 13:00
Same issue. can't find a way to fix it.

**Comment by samuelmaddock** [comment] 2021-12-20 05:33
Closing as this is a duplicate of #30760

**Closed by samuelmaddock** 2021-12-20 05:33 UTC
Labels: bug :beetle:
