### ISSUE TITLE
[Bug]: Notification#on('click', ...) is broken in Electron 21+

### ISSUE THREAD

**Issue by johnheroy** [electron/electron#36430] opened 2022-11-22 22:31 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2

### What arch are you using?

x64

### Last Known Working Electron version

20.3.6

### Expected Behavior

1. Show a notification from 'main' process (`const notif = new Notification({ ... }); notif.on('click', () => { console.log('clicked'); }); notif.show();`)
2. User clicks on notification
3. Click handler is called in main process

### Actual Behavior

No click handler fires. Reproduces on both macOS and Windows

**Comment by codebytere** [comment] 2022-11-23 10:52
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by dtzxporter** [comment] 2022-12-02 22:46
FWIW, I actually have it working on macos using 22 beta, but does nothing in windows still.

**Comment by codebytere** [comment] 2023-01-10 11:09
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2023-01-10 11:09 UTC
Labels: bug :beetle:

**Comment by U-OK** [comment] 2023-10-18 08:25
Hi all! I also encountered this problem and it frayed a lot of nerves. The click handler worked in dev mode, but did not work after building in prod.
But I found the solution. Maybe it will be helpfull for you.
The problem is that missing between your appId, so notification and click on it don't have connection with your application.

How to resolve this isuue: 
In your `forge.config.js` find your appBundleId or set it:
```
packagerConfig: {
    appBundleId: 'my.app.id',
    ...
}
```

And then in main process you should write:
```
app.on('ready', () => {
    if (process.platform === 'win32') {
      app.setAppUserModelId('my.app.id');
    }
    createWindow();
    createNotification();
  });
```

After that, your notify click listner will be work not only in dev, but in prod! 
I hope my solution was useful to you.
