### ISSUE TITLE
Cannot use Icon in MenuItem: "Could not call remote method 'buildFromTemplate'" error

### ISSUE THREAD

**Issue by dropsonic** [electron/electron#23444] opened 2020-05-07 12:12 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.2 (also checked on 8.2.5.)
* **Operating System:**
  * Windows 10 Pro (1903)
* **Last Known Working Electron version:**
  * 

### Expected Behavior
The menu is created without any errors

### Actual Behavior
Error:

```
render.js:48 Uncaught (in promise) Error: Could not call remote method 'buildFromTemplate'. Check that the method signature is correct. Underlying error: Error processing argument at index 1, conversion failure from 
Underlying stack: TypeError: Error processing argument at index 1, conversion failure from 
    at Menu../lib/browser/api/menu.js.Menu.insert (electron/js2c/browser_init.js:1855:23)
    at Menu../lib/browser/api/menu.js.Menu.append (electron/js2c/browser_init.js:1835:15)
    at electron/js2c/browser_init.js:1913:12
    at Array.forEach (<anonymous>)
    at Function../lib/browser/api/menu.js.Menu.buildFromTemplate (electron/js2c/browser_init.js:1909:10)
    at electron/js2c/browser_init.js:6745:67
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6610:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3873:23)
    at WebContents.emit (events.js:210:5)

    at electron/js2c/browser_init.js:6748:21
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6610:27)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3873:23)
    at WebContents.emit (events.js:210:5)
getVideoSources @ render.js:48
async function (async)
getVideoSources @ render.js:32
```

### To Reproduce

```sh
$ git clone https://github.com/dropsonic/223-electron-screen-recorder.git -b master
$ npm install
$ npm start
```
Press 'Choose a Video Source' button.

The code:

```node
async function getVideoSources() {
	const inputSources = await desktopCapturer.getSources({
		types: [ 'window', 'screen' ],
		fetchWindowIcons: true
	});

	const videoOptionsMenu = Menu.buildFromTemplate(
		inputSources.map((source) => {
			return {
				label: source.name,
				icon: source.appIcon,
				click: () => selectSource(source)
			};
		})
	);

	videoOptionsMenu.popup();
}
```

### Screenshots
![image](https://user-images.githubusercontent.com/1544021/81292903-18363300-9075-11ea-84d1-e22368f0f1ec.png)

### Additional Information
I've also tried to set `nativeImage.createEmpty()` as an icon but got the same error.

**Comment by codebytere** [comment] 2020-05-12 06:01
@dropsonic in the short term, remove the icons from the MenuItems and that'll fix it. This seems to be caused by a conversion error borne of the fact that the sources returned from `desktopCapturer.getSources` contain invalid `appIcon`s. I'll try to look further into it.

**Comment by dropsonic** [comment] 2020-05-12 08:02
@codebytere it looks like it is not related to `desktopCapturer.getSources` because if I use `nativeImage.createEmpty()` as an icon I get the same error.

**Comment by codebytere** [comment] 2020-05-12 15:23
@dropsonic yep, exactly.

**Comment by dropsonic** [comment] 2020-05-12 15:30
@codebytere oh, now I see. So it means that if I define icons for menu items, I have to define a valid icon for each item?

**Comment by codebytere** [comment] 2020-05-12 15:58
@dropsonic i think the root of this issue may lie with us :) I'll do some digging and see what i find.

**Comment by codebytere** [comment] 2020-05-12 21:33
@dropsonic i've determined the underlying issue and opened a PR. Feel free to follow the above linked PR to track it to a release once it's merged :)

**Comment by dropsonic** [comment] 2020-05-13 04:51
@codebytere wow, that was blazingly fast. Thanks a lot!

**Closed** 2020-05-18 16:29 UTC
