### ISSUE TITLE
Application gets crash after app.accessibility-support-changed

### ISSUE THREAD

**Issue by Masaccioi** [electron/electron#23216] opened 2020-04-22 08:59 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 7.2.1
  * 
* **Operating System:** 10.14.5
  * 
* **Last Known Working Electron version:** unknown
  * 

### Expected Behavior

The application crashes consistently. Before crashing, we find app.accessibility-support-changed from the sentry. And this error EXC_BREAKPOINT / EXC_I386_BPT: Fatal Error: EXC_BREAKPOINT / EXC_I386_BPT
### Actual Behavior

The application doesn't crash
### Screenshots

![image](https://user-images.githubusercontent.com/19363587/79961800-ce1c5180-84b9-11ea-9e1f-5e9641cd17cd.png)
[670f9cefb30d474db62ce71915e405cf-symbolicated.txt](https://github.com/electron/electron/files/4514961/670f9cefb30d474db62ce71915e405cf-symbolicated.txt)

### Additional Information

![image](https://user-images.githubusercontent.com/19363587/80302871-3d0de900-87df-11ea-8725-09c78bf45d78.png)
![image](https://user-images.githubusercontent.com/19363587/80302887-4b5c0500-87df-11ea-9988-c54c53fb6447.png)
![image](https://user-images.githubusercontent.com/19363587/80302893-557e0380-87df-11ea-8678-fa4a00f54c95.png)

**Comment by ckerr** [comment] 2020-04-22 22:48
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Masaccioi** [comment] 2020-04-26 08:35
@ckerr  Thank you for your answer. This crash happened on our customer's computer. I can't reproduce it too. I post the call stack. I hope it can help to investigate.

**Comment by codebytere** [comment] 2020-06-16 19:30
Without a repro, we can't triage this. Since there's been no more follow-up, i'm going to go ahead and close this, but should one become available we're open to re-opening this.

**Closed by codebytere** 2020-06-16 19:30 UTC
Labels: 7-2-x, blocked/need-repro, platform/macOS
