### ISSUE TITLE
Electron crash when typing in devtools console

### ISSUE THREAD

**Issue by BOOMER74** [electron/electron#11738] opened 2018-01-26 08:12 UTC
* Electron version: 1.8.2 beta 3 and 4 (ia32 and x64)
* Operating system: Windows 10 and Arch Linux

### Expected behavior

Devtools work.

### Actual behavior

Electron crash.

### How to reproduce

Start electron, open devtools and type anything in console. Electron crash with error (0xC0000005). Unlike https://github.com/electron/electron/issues/10188 no any log was created.

**Comment by codebytere** [comment] 2018-01-26 14:13
Hi yes we're aware of this, PRs are currently up and this will be fixed shortly.

**Closed by codebytere** 2018-01-26 14:13 UTC

**Comment by brenca** [comment] 2018-01-28 23:57
Duplicate of #11375
