### ISSUE TITLE
Can't load video from asar archive

### ISSUE THREAD

**Issue by RobsonMi** [electron/electron#5621] opened 2016-05-20 10:58 UTC
* Electron version: 1.1.0
* Operating system: Linux

Video tag can't load mp4 file from asar. Can anyone help with that?

**Comment by zcbenz** [comment] 2016-05-22 07:19
Can you provide a minimal app that can reproduce this problem?

**Comment by aaroncalderon** [comment] 2016-06-23 16:15
I have found this issue myself, the workaround I have implemented is to exclude those troublesome files from the asar archive. Like setting the `asar-unpack` option to a regular expression that will pick all those files and unpack them for you.

In my case I am working on an app that uses `PowerShell` scripts, which I found out do not run/execute when read from the asar archive, so I set my `'asar-unpac': '*.ps1'` and problem solved.

**Comment by kevinsawicki** [comment] 2016-06-29 01:53
I was able to play an mp4 downloaded from http://www.sample-videos.com/ from within a `<video>` tag without unpacking it from the `.asar` archive.

```html
<video src="./video.mp4" height=400 width=400 autoplay>
```

![screen shot 2016-06-28 at 6 51 34 pm](https://cloud.githubusercontent.com/assets/671378/16438085/6ffc8ff0-3d61-11e6-91b9-e75ddea6cc13.png)

If you are still experiencing this issues then please comment with a minimal app that reproduces the problem and we'll look into it further, closing it out for now.

**Comment by RobsonMi** [comment] 2016-06-29 11:53
Hi, sorry it took me so long to respond.

Your example video doesn't work for me. Still same issue. I managed to narrow it down to MEDIA_ERR_SRC_NOT_SUPPORTED error in video tag.

Attached you'll find simple app that causes this issue. You must of course package it to see it fail - it works perfectly when started with "npm start".

[TestApp.zip](https://github.com/electron/electron/files/339159/TestApp.zip)

**Comment by RobsonMi** [comment] 2016-06-29 12:46
The only workaround I found is this:

var fs = require('fs');

// function to encode file data to base64 encoded string
function base64_encode(file) {
    // read binary data
    var bitmap = fs.readFileSync(file);
    // convert binary data to base64 encoded string
    return new Buffer(bitmap).toString('base64');
}

window.onload = function() {
    var base64str = 'data:video/mp4;base64,' + base64_encode('./resources/app.asar/app/video.mp4');
    document.getElementById('videoframe').setAttribute('src', base64str);
};

It works, but it's not pretty...

**Comment by MarshallOfSound** [comment] 2016-06-29 12:48
@RobsonMi What OS are you using?

**Comment by RobsonMi** [comment] 2016-06-29 12:50
Right now windows 10 64bit

**Comment by kevinsawicki** [comment] 2016-06-29 15:12
Thanks @RobsonMi for the details, will try on Windows today

**Comment by MarshallOfSound** [comment] 2016-06-30 01:37
@RobsonMi @kevinsawicki 

FWIW The sample app provided reproduces the error for me on Windows 10

**Comment by kevinsawicki** [comment] 2016-07-01 17:33
@MarshallOfSound what version of Electron were you using when you reproduced this?

I tried the master branch on Windows 10 and still see the video play on launch and no errors in the console:

<img width="911" alt="screen shot 2016-07-01 at 10 31 57 am" src="https://cloud.githubusercontent.com/assets/671378/16529320/2184da72-3f77-11e6-945f-742e564bea38.png">

@RobsonMi do you see this issue on Electron 1.2.5?

**Comment by MarshallOfSound** [comment] 2016-07-01 23:10
I ran `npm install` on the sample app provided.  From memory that was version 1.2.5.

**Comment by zcbenz** [comment] 2016-07-12 07:25
I can also reproduce this on macOS. From the `MEDIA_ERR_SRC_NOT_SUPPORTED` error, I think it is because wrong headers were sent.

**Closed** 2016-09-09 11:59 UTC
Labels: asar, bug
