### ISSUE TITLE
[Bug]: Blank window after launch from context menu

### ISSUE THREAD

**Issue by zarubond** [electron/electron#28929] opened 2021-04-29 09:57 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

ia32

### Last Known Working Electron version

11.0.0-beta.11

### Expected Behavior

In the example below, if you open child window from context menu (click "Open Menu with window"), the content of that window is blank. The content will be rendered only after the window is moved or some other window is focused. This is repeatable about 50% of time which seems like some kind of race condition. My best guess is that this commit is responsible https://github.com/electron/electron/commit/9852e1f190bff620ba2c9e39dc084e130125434e

### Actual Behavior

The window content should be visible right after opening. 

### Testcase Gist URL

https://github.com/zarubond/electron-quick-start/tree/blank_window

**Comment by zcbenz** [comment] 2021-05-12 02:34
I confirm this only started to happen from v11.0.0-beta.12, changes between beta.11 and beta.12:
https://github.com/electron/electron/compare/v11.0.0-beta.11...v11.0.0-beta.12

Unfortunately there is a large Chromium upgrade in them, so it might not be Electron code responsible for the bug.

**Comment by zcbenz** [comment] 2021-05-13 07:06
After trying to revert related commits in beta.12, I confirm this is caused by the Chromium upgrade.

The Chromium upgrade was a large one so I don't plan to bisect the troubling commit for now, but I have found a workaround:

```js
  mainWindow.webContents.on('new-window', (event, url, frameName, disposition, options, additionalFeatures) => {
    event.preventDefault()
    Object.assign(options, {
      show: false,
    })
    const win = event.newGuest = new BrowserWindow(options)
    win.once('ready-to-show', () => win.show())
  })

```

**Comment by nornagon** [comment] 2021-07-13 19:14
We've had a few "fail-to-paint" bugs recently, e.g. https://github.com/electron/electron/issues/27353, https://github.com/electron/electron/issues/29050, #28865, #27353, #29189.

Perhaps there's a common thread here?

**Comment by nornagon** [comment] 2021-07-13 19:14
cc @zcbenz and @codebytere who have both looked into this some.

**Comment by deermichel** [comment] 2021-09-21 11:42
I was able to reproduce this issue on latest versions of Electron 12 & 13. But starting Electron 14, it got fixed.

**Comment by VerteDinde** [comment] 2022-09-15 23:06
Closing this as fixed in versions 14 and higher.

**Closed by VerteDinde** 2022-09-15 23:06 UTC
Labels: platform/windows, bug :beetle:, 11-x-y, 12-x-y, has-repro-repo, 13-x-y
