### ISSUE TITLE
MenuItems with a role set cannot be disabled

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#6800] opened 2016-08-10 17:42 UTC
If you create a MenuItem with a `role` it will not respect the `enabled` property.

```
electronMenu.append(new electron.remote.MenuItem({
    type: 'normal',
    label: 'Cut',
    role: 'cut',
    accelerator: 'CommandOrControl+X',
    enabled: false, // this does nothing
}));
```

You can see that the Cut menu item is still enabled:

<img width="232" alt="screen shot 2016-08-10 at 10 40 52 am" src="https://cloud.githubusercontent.com/assets/62191/17564061/f856b37a-5ee6-11e6-9ba5-7c8c66a3d542.png">

Here it is without the role:

```
electronMenu.append(new electron.remote.MenuItem({
    type: 'normal',
    label: 'Cut',
    accelerator: 'CommandOrControl+X',
    enabled: false, // this works now
}));
```

And you can see it is now disabled:

<img width="229" alt="screen shot 2016-08-10 at 10 41 57 am" src="https://cloud.githubusercontent.com/assets/62191/17564083/16164182-5ee7-11e6-95b7-2b91dfc05bf5.png">

* Electron version: 1.3.3
* Operating system: macOS

**Comment by sindresorhus** [comment] 2016-08-10 21:45
Duplicate of https://github.com/electron/electron/issues/5860.

This is how I worked around it: https://github.com/sindresorhus/electron-context-menu/blob/7b6c1dd31fb5fe483206d4999a8e849a09532342/index.js#L16-L19

**Comment by kevinsawicki** [comment] 2016-08-10 21:54
Closing as duplicate, refs #5794

**Closed by kevinsawicki** 2016-08-10 21:54 UTC
