### ISSUE TITLE
I use npm install electron@latest --save it ' show I don't correctly install In orther Project it' always happened

### ISSUE THREAD

**Issue by WingDust** [electron/electron#21702] opened 2020-01-08 09:46 UTC
![image](https://user-images.githubusercontent.com/45911286/71967468-5db92f80-323e-11ea-839f-2f9b87f364f3.png)

![image](https://user-images.githubusercontent.com/45911286/71967549-7cb7c180-323e-11ea-9d22-f67461027ab1.png)

**Comment by WingDust** [comment] 2020-01-08 10:41
![image](https://user-images.githubusercontent.com/45911286/71970240-403a9480-3243-11ea-87d5-28599f4c9080.png)

I am use chromedriver-v7.1.7-win32-x64.zip to install it still don't work

**Comment by jacobq** [comment] 2020-01-08 20:45
This looks like a duplicate of #20731 What's different?

**Comment by codebytere** [comment] 2020-01-08 21:25
Duplicate of https://github.com/electron/electron/issues/20455. Also, for future issues, we require the template be filled out. Failure to do so will prevent maintainers from triaging your issues.

**Closed by codebytere** 2020-01-08 21:25 UTC
