### ISSUE TITLE
[Bug]: `app.getPath('crashDumps')` returns incorrect path on Linux

### ISSUE THREAD

**Issue by timfish** [electron/electron#31643] opened 2021-10-31 21:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0-beta.4

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Last Known Working Electron version

15.3.0

### Expected Behavior

On Linux, `app.getPath('crashDumps')` should return something like:
```
~/.config/{{appName}}/Crash Reports/
```

### Actual Behavior

However, with v16 beta it returns:
```
~/.config/Electron/Crash Reports/
```

### Additional Information

This only appears to be an issue on Linux so likely to do with the migration to Crashpad?

**Comment by clavin** [comment] 2021-11-03 23:12
This is a duplicate of #31565

**Closed by clavin** 2021-11-03 23:12 UTC
Labels: platform/linux, bug :beetle:, 16-x-y
