### ISSUE TITLE
Debugging Node process in Electron can produce invalid JSON in target

### ISSUE THREAD

**Issue by roblourens** [electron/electron#11524] opened 2017-12-26 15:56 UTC
A VS Code user is reliably getting this issue: https://github.com/Microsoft/vscode/issues/40501#issuecomment-353902838

- OS is 32 bit Win 7 (`Windows_NT ia32 6.1.7601`)
- Computer language is set to Chinese
- Starts VS Code's extension host process by forking with `--inspect-brk=1234` and setting `ELECTRON_RUN_AS_NODE`
- Then we hit `http://localhost:1234/json`, and get a response that has characters that prevent the response from being parsed as JSON, like:

```
[ {
  "description": "node.js instance",
  "devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:10309/2e42e8f4-f7f0-472b-952a-f07180cabef8",
  "faviconUrl": "https://nodejs.org/static/favicon.ico",
  "id": "2e42e8f4-f7f0-472b-952a-f07180cabef8",
  "title": "qcu(",
  "type": "node",
  "url": "file://",
  "webSocketDebuggerUrl": "ws://127.0.0.1:10309/2e42e8f4-f7f0-472b-952a-f07180cabef8"
} ]
```

I can't reproduce this myself, but what could cause the title to be set to something like that? I asked the user to try using `node` by itself and he couldn't reproduce the issue, only with electron.

Is this code in node the same code running for this scenario with Electron? I don't see any similar code in Electron.
Sets the fields for this response:  https://github.com/nodejs/node/blob/98a6f63e457859be44bb76a051fc17ccf296edbf/src/inspector_socket_server.cc#L358

`getTargetTitle`:  https://github.com/nodejs/node/blob/73ad3f9bea3993b486621aaf9e61484dc37741d4/src/inspector_io.cc#L496

Eventually, `uv_get_process_title` in libuv:  https://github.com/libuv/libuv/blob/d708df110a03332224bd9be1bbd23093d9cf9022/src/win/util.c#L438

**Comment by MarshallOfSound** [comment] 2017-12-26 22:12
@roblourens It looks like that user has a non-utf8 compliant path to `VSCode.exe` (this absolute path is what would be in the title on Windows).  I'd suggest trying to get the path for VSCode changed on that users machine (or at least figure out what it is at the moment).

Will leave this open temporarily just in case it's something on our end, but as far as I can see that code path isn't modified in electrons patches on top of node so it should be identical logic.

**Comment by roblourens** [comment] 2017-12-27 05:11
That's a good idea. The user says Code is installed to `D:\Program Files\Microsoft VS Code\Code.exe` which should be fine, but I asked him to try installing on C.

**Comment by padmanabanjk** [comment] 2018-03-27 09:59
Hi, I am facing the same problem while running the electron js application. my system is behind internal proxy.  But same program runs in another computer which is not behind proxy without any problem. 

Error Message: 
Cannot connect to runtime process, timeout after 10000 ms - (reason: Response from the target seems invalid: [ {
  "description": "node.js instance",
  "devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:14448/b42bb6a8-b960-4dd4-a81a-c75def68e4f8",
  "faviconUrl": "https://nodejs.org/static/favicon.ico",
  "id": "b42bb6a8-b960-4dd4-a81a-c75def68e4f8",
  "title": "���",
  "type": "node",
  "url": "file://",
  "webSocketDebuggerUrl": "ws://127.0.0.1:14448/b42bb6a8-b960-4dd4-a81a-c75def68e4f8"
} ]

).

**Comment by vfan** [comment] 2018-07-03 09:11
I meet this question too,from china.
![image](https://user-images.githubusercontent.com/1477088/42210660-250b7698-7ee4-11e8-87c1-dc92f1a96ad0.png)

**Comment by sofianguy** [comment] 2019-01-15 22:05
Is this bug present in Electron v2.0.x or later?

**Comment by roblourens** [comment] 2019-01-15 22:31
Yeah, we were seeing it in 2.0.x: https://github.com/Microsoft/vscode/issues/63618

I don't know about 3 or because I couldn't actually repro it myself.

**Comment by sofianguy** [comment] 2019-08-09 03:34
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:10
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:10 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
