### ISSUE TITLE
Clipboard gets pasteboard exception

### ISSUE THREAD

**Issue by blainesch** [electron/electron#6671] opened 2016-08-01 05:30 UTC
* Electron version: 1.3.1
* Operating system: OSX El Capitan

I can't reliably reproduce this, but once I get into the state it is only fixed by restarting my machine.

When I attempt to ask about any potential image on the clipboard I can an exception saying that it can't allocate a new block. Text and other formats seem to work, but when I try `readImage()` or `availaleFormats()` I get the error in the console.

When I'm in this weird state, the exception is only throw when I do not have an image in my clipboard. Once I copy text or html into my clipboard the exception comes back.

~~~
▶ electron -i
> var clipboard = require('electron').clipboard
undefined
> clipboard.readImage()
2016-07-31 22:27:36.857 Electron[47607:1538529] Can't allocate a new block for a pasteboard. Creation of a new Pasteboard will fail.
{ toPNG: [Function: toPNG],
  toJPEG: [Function: toJPEG],
  getNativeHandle: [Function: getNativeHandle],
  toDataURL: [Function: toDataURL],
  isEmpty: [Function: isEmpty],
  getSize: [Function: getSize],
  setTemplateImage: [Function: setTemplateImage],
  isTemplateImage: [Function: isTemplateImage],
  toPng: [Function: toPng],
  toJpeg: [Function: toJpeg] }
> clipboard.readText()
'ConfigFile'
> clipboard.availableFormats()
2016-07-31 22:27:50.510 Electron[47607:1538529] Can't allocate a new block for a pasteboard. Creation of a new Pasteboard will fail.
[ 'text/plain' ]
~~~

~~~
> process.versions
{ http_parser: '2.7.0',
  node: '6.3.0',
  v8: '5.2.361.43',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '49',
  openssl: '1.0.2h',
  electron: '1.3.1',
  'atom-shell': '1.3.1',
  chrome: '52.0.2743.82' }
~~~

**Comment by zcbenz** [comment] 2016-08-02 00:29
This looks like an upstream issue of Chromium, but it should have been fixed in Chrome 52:
https://bugs.chromium.org/p/chromium/issues/detail?id=467296

Can you try whether the example in that issue can reproduce in Chrome browser and Electron on your machine?

**Comment by blainesch** [comment] 2016-08-02 01:50
<img width="986" alt="all_messages_and_extensions" src="https://cloud.githubusercontent.com/assets/769039/17314335/6a2793fa-5818-11e6-998d-d6180e0923bd.png">

<img width="366" alt="about" src="https://cloud.githubusercontent.com/assets/769039/17314342/729fd24a-5818-11e6-86db-0054809daac7.png">

How would I test it in electron? A quick search said electron won't support extensions. [#1498](https://github.com/electron/electron/issues/1498#issuecomment-96995155)

**Comment by zcbenz** [comment] 2016-08-02 12:56
Thanks for testing with Chrome, it is enough to locate the problem. This is an upstream bug of Chromium, can you report this back to Chromium's issues list?

I'm closing this issue since it is an upstream bug and we are not able to fix it on Electron's side.

**Closed by zcbenz** 2016-08-02 12:56 UTC
Labels: more-information-needed
