### ISSUE TITLE
[Bug]: Web Bluetooth API calls crashes Electron in macOS Big Sur

### ISSUE THREAD

**Issue by zeenfaizpy** [electron/electron#31167] opened 2021-09-27 22:33 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0 ( only in macOS Catalina )

### Expected Behavior

When I call navigator.bluetooth.requestDevice({ acceptAllDevices: true}) I expect a promise to be returned as per the documentation

### Actual Behavior

When I call navigator.bluetooth.requestDevice({ acceptAllDevices: true}) (or any other Web Bluetooth API call) electron crashes.

### Additional Information

(macOS Big Sur 11.6) Electron v15, v14, v13, v12, v11 all are crashing
(macOS Catalina ) Last worked version 11.3.0

**Comment by zeenfaizpy** [comment] 2021-09-28 04:53
After adding terminal app to "System Preferences" —> "Security & Privacy" —> "Bluetooth" resolves the issue and not crashing. ( in macOS Big Sur 11.6 )

Will default permission from electron like https://github.com/electron/electron/pull/26730 solves the issue ?

**Comment by codebytere** [comment] 2021-09-28 09:02
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2021-09-29 10:28
@zeenfaizpy I tested with https://gist.github.com/67d6c02907f90608001a681d0383e207 and experienced no issues on Big Sur running the stated version.

**Comment by reillyeon** [comment] 2021-09-29 22:24
The issue is likely that the application needs to ask for the Bluetooth entitlement and the Info.plist needs to have the NSBluetoothAlwaysUsageDescription and NSBluetoothPeripheralUsageDescription strings or else macOS will crash the application when it attempts to use the system Bluetooth API. Chrome includes these in its application bundle. I am not familiar with how Electron apps handle this. Note that the behavior when running on the command line is different from when an application is launched from a bundle, as command line applications can inherit entitlements from Terminal.app rather than requiring their own.

When macOS kills the application there should be an error indicating the reason.

**Comment by genarorg** [comment] 2022-02-16 02:55
I just ran into this issue, and the default terminal app in Monterey will prompt the user for Bluetooth permissions, but other terminal apps like iTerm won't, and will need be manually added to the list of allowed apps to use Bluetooth

**Comment by codebytere** [comment] 2022-05-11 13:43
Closing in light of above.

**Closed by codebytere** 2022-05-11 13:43 UTC
Labels: platform/macOS, bug :beetle:, blocked/need-repro, Big Sur 🍎, 15-x-y
