### ISSUE TITLE
Frameless Electron App not work css cursor:pointer

### ISSUE THREAD

**Issue by sujkh85** [electron/electron#8730] opened 2017-02-22 05:48 UTC
* Electron version:1.4.14
* Operating system: mac v10.12.3

### Expected behavior

setting  BrowserWindow options frame false

browser Top frame zone 

There is an invisible window

i want work css cursor:pointer

my option code

	mainWindow = new BrowserWindow({
            show: false,
            frame: false,// look
            title: "",
            useContentSize: false,
            width: mainWindowWidth,
            minWidth: mainWindowWidth,
            height: mainWindowHeight,
            minHeight: mainWindowHeight,
            maximizable:false,
            fullscreenable:false,
            icon: iconPath
        });

**Comment by groundwater** [comment] 2017-02-22 06:24
Hi @sujkh85.

Can you show me a link to your code?
Or, please include an example. Thank you.

**Comment by sujkh85** [comment] 2017-02-22 06:55
Hi @groundwater 

i sorry  i am not good at English

Please acknowledge it beforehand.

electron app is an invisible frame at the top.

example 

     <!DOCTYPE html>
     <head></head>
     <body>
         <div style='cursor:pointer'>look at me1</div>
         <div style='cursor:pointer'>look at me2</div>
     </body>


cursor pointer area is not applied on look at me1

but 

	mainWindow = new BrowserWindow({
            show: false,
            frame: true,// look
            title: "",
            useContentSize: falㅊse,
            width: mainWindowWidth,
            minWidth: mainWindowWidth,
            height: mainWindowHeight,
            minHeight: mainWindowHeight,
            maximizable:false,
            fullscreenable:false,
            icon: iconPath
        });

It works when you change the frame option.

cursor pointer area is applied

**Comment by groundwater** [comment] 2017-02-22 07:14
Thank you!

> i sorry i am not good at English

You can write in any language. We will translate it to English.

I will explain the next steps:

1. We will review your issue. Please wait 7-days.
2. If there is a bug, we can try to fix it. Sometimes we cannot.
3. If you can help fix the bug, we accept pull-requests, and will help you.

**Comment by pronebird** [comment] 2017-02-28 10:29
I have `frame` disabled and `cursor:pointer` works on any element in HTML. (Electron@beta 1.6.1)

**Comment by tonyganch** [comment] 2017-02-28 21:57
I am able to reproduce it on `master` with macOS 10.12.3.
Looks like a duplicate of #7696.

**Comment by pronebird** [comment] 2017-03-01 11:03
@tonyganch can you reproduce that without dev tools open?

**Comment by tonyganch** [comment] 2017-03-01 11:04
@pronebird, yep, I didn't have devtools open at all.

**Comment by tonyganch** [comment] 2017-03-01 11:06
There is a small area at the very top of the window, about 10 pixels high, that doesn't react to any hovers/clicks. The first "look at me" div just happens to be at the top, so it's visibly affected. If you add `margin-top: 100px` or just `cursor: pointer` to the whole `body`, then you see the issue.

**Comment by tonyganch** [comment] 2017-03-01 11:39
May be related to #5723.

**Comment by sarneeh** [comment] 2017-03-16 19:47
Experiencing the same issue with macOS 10.12.3, electron@^1.4.13.

**Comment by johnryan** [comment] 2017-05-17 17:39
@zeke It seems that unless you set `-webkit-app-region: no-drag` on an element on windows with a frameless window it doesn't receive any mouse events (which causes this cursor issue as well as issues with click handling). Is this a bug in electron?

**Comment by sarneeh** [comment] 2017-05-18 05:29
@johnryan I think You are talking about some different issue. `-webkit-app-region: no-drag` doesn't fix anything - there is still a small area at the top of the window which does not handle any mouse events. Correct me if I'm wrong.

**Comment by johnryan** [comment] 2017-05-18 15:54
@sarneeh i think you're right, i'll open a new ticket if appropriate

**Closed** 2017-06-05 21:30 UTC
Labels: fixme/bug, platform/macOS

**Comment by JohannBlake** [comment] 2017-11-22 18:57
Does the cursor now show at the top using css? I'm using electron 1.6.11 and prefer not to upgrade at the moment to the latest version. So if this isn't fixed, then I have even less reason to upgrade.

**Comment by amok** [comment] 2017-12-04 15:51
experiencing the same issue
in my case size of that small area is 22px

```
macos: High Sierra 10.13.1
electron: v1.7.9 (the same with 1.8.2-beta.2)
```

@kevinsawicki seems like the problem is not fixed

**Comment by GreggSchaffter** [comment] 2017-12-13 05:12
Yeah, I'm having a similar issue. In browser, the webpage I have with the hover event works perfectly with the hovering of the element. However, with a frameless window attempting to use hover with elements at the top of the window doesn't work.

**Comment by 4eveRS** [comment] 2018-02-06 17:51
Still happening at v 1.7.10... is there any plan to release it in a near future?

**Comment by bsparacino** [comment] 2018-02-15 02:50
I am having this same issue on v1.7.12, thought I was going crazy.

**Comment by RickyWong33** [comment] 2018-02-23 15:42
still get this happening at  v1.8.2. 
` cursor: pointer` function badly at frameless mode in electron.

**Comment by RickyWong33** [comment] 2018-02-24 02:47
@zeke no, not at all. when trun `frame` option off, every setting of `cursor` css functions well; on contrast, `cursor: pointer` works badly not only in topbar area but many other areas(especially right side of the window)

**Comment by TDJLKK** [comment] 2018-03-04 21:52
Is there any way to fix this at the moment? I tried the latest stable and beta versions, none of them work. 
I have a 22px button with a hover effect (that doesen't work), if I make it bigger, the hover works on the bottom of the button.

**Comment by MarshallOfSound** [comment] 2018-03-04 22:33
@TDJLKK To explain the "fix" for this issue for anyone on this thread

* This issue was closed due to the new feature introduced in #8958
* The symptoms described in this issue occur when using `titleBarStyle: `hidden` or `frame: false` (for which the default is `titleBarStyle: 'hidden'`)
* The symptoms are resolved when using `titleBarStyle: 'customButtonsOnHover` as described in the linked PR

> Apps can opt-in to this feature by setting `titleBarStyle` to `customButtonsOnHover` on the BrowserWindow options constructor when using frameless windows.

**Comment by GreggSchaffter** [comment] 2018-04-17 10:42
Another fix I found is that for any element you have that you want a click event or different cursor, the element must have `-webkit-app-region: no-drag;` in it. 

Here is where I found the solution: https://github.com/electron/electron/issues/1354

**Comment by raphadko** [comment] 2018-07-12 05:42
Using no-drag kinda solved it. But what if you want to show a move cursor when drag is enabled? 
Very common feature

**Comment by starpit** [comment] 2018-08-17 12:44
i can verify that `titleBarStyle: customButtonsOnHover` resolves the issue for us.

**Comment by zerrol** [comment] 2020-07-14 12:58
```javascript
win = createWindow("main", {
    titleBarStyle: "hidden",
    ...otherOptions
});

// setTrafficLightPosition is undefined in windows
win.setTrafficLightPosition && win.setTrafficLightPosition({
    x: 10,
})
```
works for me

**Comment by castroCrea** [comment] 2020-11-03 14:36
Shorter way, note that it just reduce the height of the hidden title bar so you still have the problem but just from 10px from the top of the app
```
win = createWindow("main", {
    titleBarStyle: "hidden",
    trafficLightPosition: {
      x: 10,
      y: 15
    },
    ...otherOptions
});
```

**Comment by nickrupert7** [comment] 2021-08-22 20:48
I'm a little late to the party, but I'd like to thank @MarshallOfSound for your answer! Your suggestion of `customButtonsOnHover` resolved the issue for me after HOURS of twiddling with CSS.

For the benefit of future readers, I thought I might describe the problem in slightly clearer terms, and explain my understanding of why this solution works. Before I start, I'll note that I'm using MacOS, and I honestly have no idea how this situation plays out on Windows and Linux.

When using a `frameless` window in electron, the default task bar provided by the OS appears to be hidden. However, even in the frameless window, you can't trigger the `cursor: pointer` style (or for that matter, _any_ cursor styles) in the top 44 pixels  of the window (i.e. the exact height of the MacOS default window task bar). I believe this is happening because the default task bar is simply made to be _invisible_, rather than actually being _removed entirely._ That is, the task bar is still present, and overriding the window's choice of cursor defined in your CSS, even though you can't see it or otherwise interact with it.

I believe that by setting the `taskBarStyle: 'customButtonsOnHover'` option, you are telling the OS that YOU will define custom functionality in the area of the task bar, and thus the OS relinquishes its control and, among other things, allows you to set your own pointer styles.

**Comment by nickrupert7** [comment] 2021-08-22 22:37
After playing with this a bit more, and finding the [official electron documentation on frameless windows](https://www.electronjs.org/docs/api/frameless-window), it became clear that the `taskBarStyle: 'customButtonsOnHover'` still show the "traffic light" buttons. If you are like me, and are seeking a way to have a truly frameless window, with no traffic light buttons, and no "hidden" taskbar that overrides your pointer styles, **I do not believe that it is natively possible**. 

However, I've come up with what I believe to be the next-best solution. Granted, it's not 100% ideal, but it works.

The trick here is to extend your window by the height of the task bar, and make that area _transparent_.

So effectively, you have a 44px-tall region at the top of your window which is invisible, and the one compromise here is that clicking in that otherwise invisible region will cause your window to become active. For the most part this side-effect should be harmless, except in a situation that the user is trying to click another window that happens to be behind your invisible region, in which case this could be _very_ confusing.

There is currently an [open issue to provide "click-through transparency,"](https://github.com/electron/electron/issues/1335) which I believe would resolve this side-effect, but until that becomes available, we just have to accept the shortcomings.

The other side-effect here is that you have to make some changes to your CSS to ensure that the rest of your element consider the "top" of the window to start below the 44px margin, as well as adjustments to the appearance.

I've posted a couple of gists which show the necessary changes to get everything functioning properly:

[Browser Window Configuration](https://gist.github.com/nickrupert7/a433363eb9ec0f9aa5baac97073a27e1)
[CSS](https://gist.github.com/nickrupert7/78f84dc16069ff5c82cbd4780f324ac4)

**Comment by dluc** [comment] 2022-06-28 21:12
Electron: 19.0.6. Still occurring, `cursor: pointer` not working as expected.

The solutions above address the "click-ability" but not the original issue about the pointer: CSS `cursor: pointer` doesn't work in the top area of the window. Elements (e.g. custom buttons) can be clicked but the mouse pointer doesn't change for the top pixels.

Area where `cursor: pointer` works:
![image](https://user-images.githubusercontent.com/371009/176288597-fef86f98-0c84-4001-ade3-fd88643848f4.png)

Top pixels where it doesn't:
![image](https://user-images.githubusercontent.com/371009/176288503-a68b5797-8205-493f-87fa-242e3d6cf96d.png)

This happens only with Electron, when `frame: false`. E.g. opening the same page in a browser everything works as expected: 
![image](https://user-images.githubusercontent.com/371009/176288752-381dd0a4-1788-4f22-9965-67eeb1da9b42.png)

I've tried the suggestions about `titleBarStyle`, `setTrafficLightPosition` and `-webkit...` but the problem persists.

**Comment by OldDream** [comment] 2022-07-07 04:41
> Electron: 19.0.6. Still occurring, `cursor: pointer` not working as expected.
> 
> The solutions above address the "click-ability" but not the original issue about the pointer: CSS `cursor: pointer` doesn't work in the top area of the window. Elements (e.g. custom buttons) can be clicked but the mouse pointer doesn't change for the top pixels.
> 
> Area where `cursor: pointer` works: ![image](https://user-images.githubusercontent.com/371009/176288597-fef86f98-0c84-4001-ade3-fd88643848f4.png)
> 
> Top pixels where it doesn't: ![image](https://user-images.githubusercontent.com/371009/176288503-a68b5797-8205-493f-87fa-242e3d6cf96d.png)
> 
> This happens only with Electron, when `frame: false`. E.g. opening the same page in a browser everything works as expected: ![image](https://user-images.githubusercontent.com/371009/176288752-381dd0a4-1788-4f22-9965-67eeb1da9b42.png)
> 
> I've tried the suggestions about `titleBarStyle`, `setTrafficLightPosition` and `-webkit...` but the problem persists.

I have the same problem, did you solve it?

**Comment by dluc** [comment] 2022-07-07 20:04
> I have the same problem, did you solve it?

unfortunately not, I gave up... Some people point at the OS, but I think it's a fundamental limitation of Electron. Spotify (not an electron app) found a way to make it work, so I'm assuming it's possible:

![image](https://user-images.githubusercontent.com/371009/177861995-f489d118-9df8-4ecc-a01b-79e7c48786a8.png)

As a workaround, an alternative idea is showing a bg shadow on mouse over, e.g. see Apple apps

![image](https://user-images.githubusercontent.com/371009/177860755-20e90b6b-86d9-423a-ba64-d681c3d634ac.png)
![image](https://user-images.githubusercontent.com/371009/177862045-bc10a113-3bab-402b-9506-c257554c6665.png)

or replacing the icon with a highlight, e.g. MS Teams

![image](https://user-images.githubusercontent.com/371009/177861039-d209596c-b321-414b-b6bb-f613528e18e1.png)

**Comment by OldDream** [comment] 2022-07-11 02:41
> 

If we add `roundedCorner: false`, the `cursor: pointer` would behave as we expect with electron 16.0.7 + macOS 12.4. But I have no idea if this is another bug 😂.

**Comment by dluc** [comment] 2022-07-11 20:51
> > 
> 
> If we add `roundedCorner: false`, the `cursor: pointer` would behave as we expect with electron 16.0.7 + macOS 12.4. But I have no idea if this is another bug 😂.

probably because that removes the OS frame like a modal window. 
(btw the option is plural `roundedCorners`)

**Comment by sohobloo** [comment] 2022-08-11 11:27
open a new issue for 19+ ?

**Comment by marindedic** [comment] 2022-08-17 13:44
For anyone still having this problem in electron 19+ (macOS):

To enable `cursor: pointer` in the upper portion of the window while having a frameless window (`frame: false`), you need to remove rounded corners: `roundedCorners: false`. Unfortunately, the resulting window has a non-native look to it with the rounded corners removed now.

**Comment by kanweiwei** [comment] 2022-08-25 07:03
Electron 17 also has the problem. 
If you set `roundedCorners: false`, the native traffic light of macos will display. That is too terrible 😣

**Comment by pnegahdar** [comment] 2022-09-29 15:13
Should be reopened. Issue still persists in the latest electron.

**Comment by lengband** [comment] 2022-12-27 07:12
I found the `cursor: pointer` in the `position: absolute` dom is failure, you can cancel `position: absolute` dom provisionally, it is effective for me

**Comment by s1nistr4** [comment] 2023-03-24 00:36
Still an issue in 2023? Damn, I feel like this is a one-line of code fix

**Comment by vincent-bru** [comment] 2023-04-26 17:46
Hello, I want to be abble to change my custom titlebar color and this issue is still in my way.
