### ISSUE TITLE
Doesn't work click event when electron has option `frame: false`.

### ISSUE THREAD

**Issue by rluisr** [electron/electron#6395] opened 2016-07-08 10:58 UTC
### Problem
when electron creates window with `frame: false`, doesn't work click event.
(ex. can't click `<a href`). But Mac OS X works fine.

### Code
app.js
```javascript
app.on('ready', () => {
            mainWindow = new BrowserWindow({
                height: 600,
                width: 800,
                resizable: false,
                frame: true,
                transparent: false,
                nodeIntegration: false,
                titleBarStyle: 'hidden' // for macOS
            });

            mainWindow.loadURL('file://' + __dirname + '/index.html');
        });
```
How do i get click event?

* Electron version:
0.4.1

* Operating system:
Windows 10 x64

**Comment by zcbenz** [comment] 2016-07-09 02:00
Can you provide a minimal app that can reproduce this problem? Also 0.4.1 does not seem like a valid version number, unless you are really using an old version from years ago.

**Comment by rluisr** [comment] 2016-07-10 09:55
@zcbenz Thanks reply.

Minimal app works fine.
Sorry, I use **electron version 1.2.6**

I found a cause.
If it uses Photon kit, don't work click event.

Sorry for making issue....

**Comment by zcbenz** [comment] 2016-07-10 10:44
I'm closing this since it seems to be an issue of photon kit.

**Closed by zcbenz** 2016-07-10 10:44 UTC
Labels: more-information-needed
