### ISSUE TITLE
File dialog can not show after destroying a modal child window

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#8554] opened 2017-02-01 12:06 UTC
* Electron version: 1.4.15
* Operating system: MacOS 10.12.3 (16D32)

During WebRTC session with screensharing (desktopCapturer), I'm trying to click on input with type file and application is not responding any more. Can quit only with "Force quit".

With electron_enable_logging I see following error in console:
<details>

```
[1765:0201/145109:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=1
[1765:0201/145109:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=2
[1765:0201/145109:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=3
[1765:0201/145109:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=4
[1765:0201/145109:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=5
[1765:0201/145109:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=6
[1765:0201/145109:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=7
[1765:0201/145109:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=8
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=9
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=10
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=11
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=12
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=13
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=14
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=15
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=16
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=17
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=18
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=19
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=20
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=21
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=22
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=23
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=24
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=25
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=26
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=27
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=28
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=29
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=30
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=31
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=32
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=33
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=34
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=35
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=36
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=37
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=38
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=39
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=40
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=41
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=42
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=43
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=44
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=45
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=46
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=47
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=48
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=49
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=50
[1765:0201/145110:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=51
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=52
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=53
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=54
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=55
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=56
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=57
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=58
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=59
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=60
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=61
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=62
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=63
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=64
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=65
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=66
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=67
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=68
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=69
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=70
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=71
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=72
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=73
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=74
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=75
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=76
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=77
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=78
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=79
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=80
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=81
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=82
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=83
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=84
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=85
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=86
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=87
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=88
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=89
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=90
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=91
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=92
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=93
[1765:0201/145111:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=94
[1765:0201/145112:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=95
[1765:0201/145112:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=96
[1765:0201/145112:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=97
[1765:0201/145112:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=98
[1765:0201/145112:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=99
[1765:0201/145112:WARNING:audio_sync_reader.cc(132)] AudioSyncReader::Read timed out, audio glitch count=100
[1765:0201/145112:WARNING:audio_sync_reader.cc(135)] (log cap reached, suppressing further logs)
```

</details>
 
Issue reproduce only if I share screen, if I join WebRTC session with video (web cam) once I get same error but in only reached count 5 and chose file modal was opened. With only audio call never saw this log.

**Comment by cumajkeee** [comment] 2017-02-02 13:17
Tried to see what happen with LLDB, got following

2017-02-02 16:08:52.770848 App[8747:517290] kAudioUnitErr_TooManyFramesToProcess : inFramesToProcess=1024, mMaxFramesPerSlice=441
2017-02-02 16:08:56.922779 App[8747:515930] WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.3 instead of 10.12.3. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
2017-02-02 16:08:56.923097 App[8747:515930] 0   CarbonCore                          0x00007fffb18f41e1 ___Gestalt_SystemVersion_block_invoke + 121
2017-02-02 16:08:56.923123 App[8747:515930] 1   libdispatch.dylib                   0x00007fffc5f0c0b8 _dispatch_client_callout + 8
2017-02-02 16:08:56.923141 App[8747:515930] 2   libdispatch.dylib                   0x00007fffc5f0c075 dispatch_once_f + 38
2017-02-02 16:08:56.923157 App[8747:515930] 3   CarbonCore                          0x00007fffb1882272 _Gestalt_SystemVersion + 976
2017-02-02 16:08:56.923170 App[8747:515930] 4   CarbonCore                          0x00007fffb1881a8d Gestalt + 139
2017-02-02 16:08:56.923182 App[8747:515930] 5   Electron Framework                  0x0000000101dc2f8e _ZN4base8internal14NarrowingRangeIilE3minEv + 28918670
2017-02-02 16:08:56.923192 App[8747:515930] 6   Electron Framework                  0x0000000101dc308c _ZN4base8internal14NarrowingRangeIilE3minEv + 28918924

**Comment by groundwater** [comment] 2017-02-03 05:21
Hi @cumajkeee, are you able to provide a repro case?

If you suspect this is a Chromium issue, it might be listed in the [chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=AudioSyncReader&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids).

**Comment by javan** [comment] 2017-02-03 14:26
Possibly related https://github.com/electron/electron/issues/8457? Perhaps the file dialog is blocking in an undesirable way.

**Comment by cumajkeee** [comment] 2017-02-03 15:06
@groundwater, unfortunately I can't share app, and to create sample I'll spend a lot of time :(
I suspect it as chromium but chrome from the box it not support screensharing in WebRTC. And problem appears only in such case. I'll try to find an closer issue, or create topic on discussion portal.

**Comment by rogeru** [comment] 2017-02-04 19:51
I'm working with @cumajkeee. Issue is not related to desktop-capturer. Crash happens when closing a modal window using `destroy()` instead of `close()`. Very simple example attached.

[MacCrashDestroyChildWindow.zip](https://github.com/electron/electron/files/752520/MacCrashDestroyChildWindow.zip)

**Comment by groundwater** [comment] 2017-02-14 18:04
Hey @rogeru, thanks for the repro-case. I definitely get some strange behavior when calling `destroy()`. I discussed this issue in our weekly meeting, and I'm curious why you're not using `close()` instead?

**Comment by rogeru** [comment] 2017-02-14 19:06
Hey @groundwater, yes once I tracked the issue down to the `destroy()` we switched to `close()`. So we are all good. I just wanted to let you guys know that there is an issue with `destroy()` as you have observed as well.

**Comment by zcbenz** [comment] 2017-06-06 05:33
As I tested in v1.7.x, it does not crash anymore, but the file dialog does not show neither, so it is still a bug.

**Comment by codebytere** [comment] 2018-02-16 04:44
this is still reproducing on `1.8.2`, but i've tracked down the root cause to an IO threading issue with lldb...when the file chooser is clicked it's called from a thread that disallows IO so it crashes with the following `Function marked as IO-only was called from a thread that disallows IO!`

**Comment by sofianguy** [comment] 2019-01-07 22:46
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:30
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-01-15 20:30 UTC
Labels: blocked/need-info, bug :beetle:, component/dialog, good first issue, platform/macOS, version/1.8.x
