### ISSUE TITLE
Notification onclick action never called on Linux

### ISSUE THREAD

**Issue by AltarBeastiful** [electron/electron#8474] opened 2017-01-22 23:36 UTC
* Electron version: 1.4.15 and latest master (22b21d0)
* Operating system: OpenSUSE 42.2 with KDE

### Expected behavior

When a notification is clicked, the notification `onclick` function should be called.

### Actual behavior

`onclick` is not called on Linux.

### How to reproduce

* Open the notification app from this repo :
https://github.com/AltarBeastiful/electron-sample-apps/tree/master/notifications
* Open the devtools console using <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>I</kbd>.
* Click on "Basic Notification".
* For Linux: Click on the "View" button of the notification. For Windows: Click on the notification.

On Windows, a message : `Notification clicked` appears in the console. 
On Linux the `onclick` function is never called.

Tested on KDE only. Anyone can report what happens in Gnome, Cinnamon or other DE?

**Comment by AltarBeastiful** [comment] 2017-01-22 23:41
After more testing, I got the notification action to fire on KDE by doing the following : 
* Open the notification app from the same repo and open devtools console
* Click on "Basic Notification".
* Click on the cross to close the notification
* Click on "Basic Notification" to get another notification
* Click the "View" button of the notification.
=> I get a `Notification Clicked` in the console

Looking at the [linux notification code in brightray](https://github.com/electron/brightray/blob/master/browser/linux/libnotify_notification.cc), I don't know yet why this behavior happens.

**Comment by deepak1556** [comment] 2017-02-23 12:47
> Anyone can report what happens in Gnome

It works as expected on gnome. The problem maybe with only KDE, i haven't verified it. Someone else from the team will look into this. Thanks!

**Comment by liliakai** [comment] 2017-04-12 23:01
I can easily reproduce this on Ubuntu 16.04 with Gnome/Unity, but I'm pretty sure it's because my notification server, `notify-osd` [doesn't support notification actions](https://github.com/electron/brightray/blob/master/browser/linux/libnotify_notification.cc#L100).

@AltarBeastiful Is your system running notify-osd?

**Comment by zcbenz** [comment] 2017-06-06 01:49
Closing since it seems to be a problem of user's notification service.

**Closed by zcbenz** 2017-06-06 01:49 UTC
Labels: platform/linux, triage/bug, waiting/needs-repro

**Comment by solanoepalacio** [comment] 2018-05-21 15:51
I have the same problem in ubuntu 16.04 + kde
