### ISSUE TITLE
Electron 5 failing to launch on WSL

### ISSUE THREAD

**Issue by ruslang02** [electron/electron#17321] opened 2019-03-10 13:07 UTC
* **Electron Version:**
  * 5.0.0-beta
* **Operating System:**
  * Ubuntu 16.04 **on WSL** Windows 10 Enterprise 1809 + Xming 6.9.0.31
* **Last Known Working Electron version:**:
  * 4.0.5

### Expected Behavior
Launching and working as it should with `export DISPLAY=:0 && npm test`
```...
"test": "electron . -d --remote-debugging-port=9229",
"test-no-sandbox": "electron . -d --no-sandbox --remote-debugging-port=9229 --disable-gpu",
"test-no-gpu": "electron . -d --disable-gpu --remote-debugging-port=9229"
...
```

### Actual Behavior
While Electron does do that, Electron 5 throws an error and exits:
```
[2894:0310/125857.514560:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox. 
```
Launching with --no-sandbox opens up a window and after a second crashes:
```
[3122:0310/130304.279934:FATAL:gpu_data_manager_impl_private.cc(892)] The display compositor is frequently crashing. Goodbye.
```

### To Reproduce
Run any Electron app

### Screenshots
![image](https://user-images.githubusercontent.com/25264730/54085357-4f646380-434e-11e9-99e2-c39a679c5cde.png)

### Additional Information
I heard and saw similar problems earlier, but this one _seems_ to be different.

**Comment by vladimiry** [comment] 2019-03-11 08:08
Duplication of https://github.com/electron/electron/issues/16631?

**Comment by ruslang02** [comment] 2019-03-11 13:51
> Duplication of #16631?

I guess it is at some point, but I don't get the gpu_data_manager fatal errors, though on 4.0 everything is working correctly.

**Comment by vladimiry** [comment] 2019-03-11 14:21
> 4.0 everything is working correctly.

Because v4 was not yet forcing the sandbox mode as v5 does.

**Comment by ruslang02** [comment] 2019-03-11 14:45
Yes, but I don't get the link between display compositor errors and sandbox issues

**Comment by nornagon** [comment] 2019-03-11 17:12
The link is that the GPU process is launched sandboxed in v5.

Does Chromium launch without error under WSL? If so, then this is a duplicate of #16631 and will be fixed by enabling the setuid sandbox.

**Comment by ruslang02** [comment] 2019-03-11 17:25
> The link is that the GPU process is launched sandboxed in v5, even if no renderer processes are.
> 
> Does Chromium launch without error under WSL? If so, then this is a duplicate of #16631 and will be fixed by enabling the setuid sandbox.

Launches only with command `DISPLAY=:0 sudo chromium-browser --no-sandbox`.

Launching with `DISPLAY=:0 chromium-browser` gives out:
```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Permission denied                                                                                                                   Trace/breakpoint trap (core dumped)
```

**Comment by nornagon** [comment] 2019-03-11 20:46
Yeah, if Chromium won't boot in that environment then I'm afraid you'll likely have trouble getting Electron to work.

I'm going to close this for now, but feel free to reopen if you get Chromium working well & Electron still doesn't!

**Closed by nornagon** 2019-03-11 20:46 UTC
