### ISSUE TITLE
`shell.openItem` should activate the opened app

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#10477] opened 2017-09-09 19:14 UTC
* Electron version: 1.7.7
* Operating system: macOS 10.12.6

### Expected behavior

For example, if I ask it to open a path to a directory, it should open it in Finder and focus the Finder window.

### Actual behavior

It opens the Finder window in the background and my app window is still focused.

### How to reproduce

```js
shell.openItem('path/to/some/dir/');
```

---

Focusing the opened app is expected behavior on macOS and should at least be an option.

The `shell.openExternal` method has this, so it's clear you agree. We just need the behavior/option added to this method too.

**Comment by MarshallOfSound** [comment] 2017-09-09 20:03
Afaik this is because our implementation of `openItem` on macOS doesn't use `NSWorkspace` rather the now deprecated `AE` api's.  This is due to a number of bugs with alternate implementations.

https://github.com/electron/electron/blob/master/atom/common/platform_util_mac.mm#L127

If you want to open it with activation I believe you can just pass the file path to `openExternal`

**Comment by sindresorhus** [comment] 2017-09-09 21:15
> /atom/common/platform_util_mac.mm@master#L127

The first mentioned issue there is fixed in Chromium. They're using `NSWorkspace` now: https://cs.chromium.org/chromium/src/chrome/browser/platform_util_mac.mm?l=30&rcl=975794ee43d7036fb94be988a9f6751db85c7a3a

> If you want to open it with activation I believe you can just pass the file path to openExternal

Yes, that's [my workaround](https://github.com/wulkano/kap/pull/228/files), but it's ugly as it requires converting the path to a file URL.

**Comment by codebytere** [comment] 2017-09-20 03:05
👋 @sindresorhus this fix is now in master, so i'm going to go ahead and close this issue!

**Closed** 2017-09-20 03:05 UTC
Labels: platform/macOS, triage/bug, version/1.7.x

**Comment by sindresorhus** [comment] 2017-09-20 04:11
@codebytere Thank you for fixing this 🙌

**Comment by stanleyxu2005** [comment] 2020-03-27 18:18
I noticed this bug for long time. And I can confirm it is still buggy for Windows 7 with (latest) Electron 8.2.0

**Comment by n-smits** [comment] 2020-04-16 00:38
Works great on mac, but how about making it optional?
Boolean: should the app be activated (if the item was successfully opened), default true.

Use case: dev experience - working on a file exporter and would love to see the file live reload -- without having to alt-tab back to the editor.

I suspect a work-around is possible through shell.openExternal as it has activate bool option.
