### ISSUE TITLE
Menu enabled/visible property doesn't affect top-level menu items

### ISSUE THREAD

**Issue by tzvetelin-vassilev** [electron/electron#11435] opened 2017-12-14 13:10 UTC
Issue #8703 describes exactly the problem. It is duplicate of #2895 but is much more clearly described. The problem is that it is closed but is not resolved.

**Comment by codebytere** [comment] 2018-01-19 21:36
Closing as a duplicate of https://github.com/electron/electron/issues/8703, since that is more clearly described as you said.

**Closed by codebytere** 2018-01-19 21:36 UTC
Labels: component/menu, platform/macOS, platform/windows, triaged/bug, version/1.4.x
