### ISSUE TITLE
CrashReporter

### ISSUE THREAD

**Issue by snene** [electron/electron#9160] opened 2017-04-10 17:56 UTC
I am using Electron version 1.4.15. I observe that when the crash report is sent using the crashReporter API the product is reported as Electron and not the product name that is specified when calling crashReporter.start. Is this expected?

**Comment by kevinsawicki** [comment] 2017-04-25 22:25
@snene it should be the product name of the app, are you passing the `productName` option to `crashReporter.start`? It defaults to `app.getName()` when unset.

The `prod` field sent to the server is `Electron`, the `_productName` should be the app name itself.

**Comment by snene** [comment] 2017-04-25 23:13
@kevinsawicki Thanks for the reply! Yes, I am setting the productName field. I am using version 1.4.15 of Electron.

**Comment by kevinsawicki** [comment] 2017-04-25 23:53
> I am setting the productName field. I am using version 1.4.15 of Electron.

So the `_productName` on your server is being reported as `Electron` even though you are setting it to something else?

Can you include the code you are using to start the crash reporter?

**Comment by snene** [comment] 2017-04-26 04:41
Yes, productName is getting reported as 'Electron'. Here is the code to start the crashReporter:

const crashReporterURL = config.crashReporterURL ? config.crashReporterURL : 'https://Client_Alpha.server.com/post/';
logger.debug(`Starting the crash reporter with submit URL as ${crashReporterURL}`);
  
crashReporter.start({productName: 'MyCompany',
    companyName: 'MyProduct',
    submitURL: crashReporterURL,
    extra: getCrashReporterData('browser'),
    uploadToServer: true
});

**Comment by kevinsawicki** [comment] 2017-04-26 16:26
@snene I just tried with the following app and was not able to reproduce, are you seeing this on all platforms? Can you try the following example and update it to point to your server:

```js
const {app, BrowserWindow, crashReporter} = require('electron')

let window

app.once('ready', function () {
  crashReporter.start({
    productName: 'MyCompany',
    companyName: 'MyProduct',
    submitURL: 'http://localhost:1127/post',
    uploadToServer: true
  })

  window = new BrowserWindow()
  window.loadURL(`file://${__dirname}/index.html`)
})
```

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script>
      const {crashReporter} = require('electron')
      crashReporter.start({
        productName: 'MyProduct',
        companyName: 'MyCompany',
        submitURL: 'http://localhost:1127/post',
        uploadToServer: true
      })
      setTimeout(process.crash, 5000)
    </script>
  </head>
  <body>
    will crash in 5 seconds
  </body>
</html>
```

The following was sent to my server with this sample app:

```
_companyName: MyCompany
_productName: MyProduct
_version: 1.6.5
guid: 803d5f30-7dc3-4125-a0f9-6966dc3ab53c
platform: darwin
process_type: renderer
prod: Electron
ver: 1.6.5
```

**Comment by snene** [comment] 2017-04-26 20:33
@kevinsawicki Thanks for your help! The server I am using is using the 'prod' field to display the product name and so I see Electron as the product.

It is working as expected by you. And so you can close the issue. Thanks for all the help!

**Comment by kevinsawicki** [comment] 2017-04-26 20:39
@snene thanks for the update, closing this out.

**Closed by kevinsawicki** 2017-04-26 20:39 UTC
Labels: more-information-needed
