### ISSUE TITLE
maximized window sometimes doesn't fill available height

### ISSUE THREAD

**Issue by shiftkey** [electron/electron#13466] opened 2018-06-27 18:17 UTC
* Electron Version: tested on 1.8.7, 2.0.0, 2.0.3, 3.0.0-beta.1.
* Operating System (Platform and Version): tested on Windows 10.0.17134.112
* Last known working Electron version: Unclear

**Expected Behavior**

When using a frameless Window on Windows, the maximize behaviour is not consistent. To test this out, repeat these steps:

 - ensure the window is not maximized
 - maximize the window with **Windows Key** + **Up** 
 - unmaximize the window **Windows Key** + **Down** to revert to normal size
 - repeat

Each time you maximize, the available screen height should be used to render the frame.

<img width="1239" src="https://user-images.githubusercontent.com/359239/41991903-6c2a7bda-7a1d-11e8-8742-bb8a30d92df6.png">

**Actual behavior**

The window alternates between being in the correct spot (`[-8,-8]`) and incorrect spot (`[-8, 9]`) after maximizing which results in some of the desktop behind behind visible, with a white bar across the top of the frame.

I switched my desktop background to green to emphasize the distinct parts:

<img width="1241" src="https://user-images.githubusercontent.com/359239/41991619-748425a2-7a1c-11e8-89e3-94e5cb37a38a.png">

I gather the white is the additional space outside the usable space available to the app, and is intended to be drawn offscreen.

**To Reproduce**

```sh
$ git clone https://github.com/shiftkey/electron-quick-start -b frameless-maximize-issue
$ npm install
$ npm start
```

**Screenshots**

**Additional Information**

**Comment by timfish** [comment] 2018-06-27 20:59
I'm pretty sure this is a duplicate of #12971.

**Closed** 2018-06-27 21:07 UTC
