### ISSUE TITLE
Crash on application menu click

### ISSUE THREAD

**Issue by acstacey** [electron/electron#16696] opened 2019-02-02 06:29 UTC
* Output of `node_modules/.bin/electron --version`: v5.0.0-beta.1
* Operating System (Platform and Version): Windows 10 Version 1803 build 17134.523
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v4.0.3

**Expected Behavior**
Menu item click function should execute.  e.g. toggle dev tools

**Actual behavior**
Clicking any application menu item causes electron to crash.

**To Reproduce**
Run electron-api-demos with 5.0.0-beta.1 and click any application menu item.  Node integration to true for it to launch properly.

**Comment by ckerr** [comment] 2019-02-27 22:09
I _think_ we left this issue open in the last 5.0.x bug meeting because we weren't sweren't certain this was a duplicate of #16883?

After further investigation, both seem to have the same root cause and I've confirmed that #17164 fixes both of them, so I'm closing this issue as a dupe.

**Closed by ckerr** 2019-02-27 22:09 UTC
Labels: 5-0-x, platform/linux, platform/windows, status/confirmed
