### ISSUE TITLE
NativeImage not able to create from a buffer

### ISSUE THREAD

**Issue by anthli** [electron/electron#7950] opened 2016-11-12 06:46 UTC
* Electron version: 1.4.6
* Operating system: macOS

### Expected behavior

Creating a `NativeImage` from a `Buffer` using `nativeImage.createFromBuffer(buffer)` should return a non-empty `NativeImage`.

### Actual behavior

The `NativeImage` returned is empty. Calling `isEmpty()` returns `true` and `getSize()` returns
`{ width: 0, height: 0 }`.

### How to reproduce

Create a `NativeImage` using a `Buffer`, then call `isEmpty()` and `getSize()` on it and log the results.

**Comment by MarshallOfSound** [comment] 2016-11-12 06:47
@anthli Can you provide an example that reproduces the issue 👍

**Comment by gerhardberger** [comment] 2016-11-12 17:31
@anthli I assume you try to create an image from a bitmap buffer, because currently `createFromBuffer` only works with [PNG and JPEG buffers](https://github.com/electron/electron/blob/master/atom/common/api/atom_api_native_image.cc#L85). It is relatively easy to support bitmap buffers with `gfx::Image::CreateFrom1xBitmap` I believe. I try to implement it in the near future if I find time.

**Comment by zcbenz** [comment] 2016-11-17 03:37
I'm closing since this seems to be a misunderstanding of the API.

**Closed by zcbenz** 2016-11-17 03:37 UTC
Labels: more-information-needed
