### ISSUE TITLE
Input borderless if top or left are odd

### ISSUE THREAD

**Issue by NicoGrapsas** [electron/electron#6007] opened 2016-06-12 05:02 UTC
* Electron version: 1.2.2
* Operating system: Windows 10 x64

<img width="590" alt="electron issue borderles" src="https://cloud.githubusercontent.com/assets/19884742/15989068/a7c0611a-3040-11e6-9538-52854e3cedec.png">

I've found this while playing around with some input that where absolute positioned.
But this also applies to relative positioning, changing padding should produce the same behavior.

If i open html In google chrome i get the normal expected result.

**Comment by zcbenz** [comment] 2016-06-13 06:16
Can you provide a minimal app that can reproduce this problem?

**Comment by NicoGrapsas** [comment] 2016-06-13 06:47
src: https://goo.gl/d81wmi
It turns out it's a chrome problem. I didn't had it installed on my laptop.
On desktop everything runs fine (electron and chrome).
On laptop same issue on both.

<img width="960" alt="bug" src="https://cloud.githubusercontent.com/assets/19884742/15999035/289eb60a-3119-11e6-8a54-830dcbf4c7aa.png">

Not shure about the reason, laptop has a recent clean install of windows 10, updated, drivers ok.
The only difference is that i had screen size 150% (because of 13" Full HD screen) but replicating same on desktop enviroment doesnt produce such behavior.

**Comment by zcbenz** [comment] 2016-06-13 07:08
Thanks for trying with Chrome browser, you have encountered a bug of Chromium and I suggest reporting this to [Chromium's issues list](https://crbug.com) instead.

I'm closing this since it is an upstream bug and we are not able to fix it on Electron's side.

**Closed by zcbenz** 2016-06-13 07:08 UTC
Labels: more-information-needed
