### ISSUE TITLE
I have a big deal →_→

### ISSUE THREAD

**Issue by xzycn** [electron/electron#11197] opened 2017-11-21 08:25 UTC
* Electron version: 1.8.1
* Operating system: Windows 7

### Expected behavior

I want to start a master process as daemon process in master.js,and then start a new process  to run electron app(go.js) that long time running.When the electron app exited, daemon process will restart the app.

### Actual behavior

When I used child_process.spawn, there will be a problem just like I mentioned in #11172 .So I turn to another way: using child_process.fork instead. The problem has gone, but another one appears.In go.js,
I can't get object throught require('electron'),but get a electron path. This case I have read from api doc before:
if the process.execPath is node, require('electron') will return electron path,if it is electron,will return electron object.
So, I print the process.execPath in go.js, and get a packaged exe binary file as expected.Yes, it is also just the same with the description about child_process.fork.Well, I don't know that cause this problem,then I found a environment variable 'ELECTRON_RUN_AS_NODE'，I print *process.env.ELECTRON_RUN_AS_NODE* ,get a *1*, I tried to change the env when called *let sp = childProcess.fork('./go.js',[],{cwd:__dirname,env: {'ELECTRON_RUN_AS_NODE':"0"}});*, however,it still is *1*,this is my whole trip :)

### How to reproduce

I have created a repo for demonstration: https://github.com/xzycn/el_test
Above is a sample using spawn，if use fork instead,it seems like everything is OK, but require('electron') don't work as expected.If I passed 'ELECTRON_RUN_AS_NODE':'0',the problem still there.ELECTRON_RUN_AS_NODE can't be changed to '0',maybe because this line:
https://github.com/electron/node/blob/5f4afdcf434e5e0e0c0c86cba96077bfe01c63e2/lib/child_process.js#L102

**Comment by ckerr** [comment] 2017-11-21 09:44
Hi xyzcn,

Thank you for reporting this issue. However I'm having a difficult time understanding the issue that you're reporting.

Would it be possible for you to write a small test application that can be used to reproduce the bug, as well with the expected output of the test application?

**Comment by xzycn** [comment] 2017-11-21 10:17
@ckerr Hi, this is my mistake, I will write a test soon :)

**Comment by xzycn** [comment] 2017-11-21 14:44
@ckerr  I have created a repo for demonstration: https://github.com/xzycn/el_test :)

**Comment by felixrieseberg** [comment] 2017-11-21 18:39
It seems like you're trying to fork the Electron process. That is a bad idea.

What are you trying to achieve?

**Comment by xzycn** [comment] 2017-11-22 01:12
@felixrieseberg Emmmm,I want to make a electron app automatically restart when it crashed.Because I don't have  any environment(like node,electron,etc.) on remote server, so I need to package everything to a exe installer.

**Comment by logidelic** [comment] 2017-11-22 19:41
@xzycn I don't have any comment on your problem, but FWIW, I've achieved a very similar goal using child_process.exec (electron 1.7.9). The master process spawns another instance of itself using child_process.exec, but with a modified argument list so that the child knows that it is not the master... Works perfectly.

**Comment by xzycn** [comment] 2017-11-23 02:06
@ logidelic Thank you for your comment, could you please show me a  sample code or create a git,merry Thanksgiving :)

**Comment by xzycn** [comment] 2017-11-23 07:24
@logidelic I have figured it out almost, however, I encountered some difficulties.Now,I have one problem need to solve.How can I make the information of package.json useful in child prodcess.
I can't get the information in package.json,for example: app.getVersion return the version of electron not the version field in package.json. :)

**Comment by logidelic** [comment] 2017-11-23 16:14
```
const pjson = require('./package.json');
console.log(pjson.version)
```
:)

**Comment by xzycn** [comment] 2017-11-24 01:35
@logidelic I have tried to do that first,but this solution has a problem with auto-update.I guess, auto-update determines if to update with the version field in package.json,and we couldn't change the version of app but get for now.So, I made some changes that moved the codes related to child process to a sub-directory named app or whatever you like.Finally, there has three package.json in my project.And exists a little issue in my solution that I should change the version field in two package.json when package the app. :)

**Comment by ckerr** [comment] 2017-11-24 09:54
I'm going to close this issue because it contains several different topics and is therefore difficult to manage, and it appears that some of this is a topic for discussion rather than an issue to be triaged and fixed.

To be clear, this is for issue management. Feel free to continue discussion and to report discrete issues separately. Thank you!

**Closed by ckerr** 2017-11-24 09:54 UTC
Labels: more-information-needed, platform/windows, version/1.8.x
