### ISSUE TITLE
[Bug]: setContentProtection problem

### ISSUE THREAD

**Issue by cgri1** [electron/electron#39452] opened 2023-08-10 07:06 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.0

### What operating system are you using?

macOS

### Operating System Version

macOs Monterey 12.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The function of setContentProtection(true) work in the always-on-top mode. The participants don't see the block of the always-on-top mode.

### Actual Behavior

The function of setContentProtection(true) does not work in the always-on-top mode. The participants see the block of the always-on-top mode.
<img width="853" alt="Screen Shot 2023-08-11 at 08 15 34" src="https://github.com/electron/electron/assets/39028198/67474b06-3613-40d7-82e4-fef1d5c37afc">

**Comment by codebytere** [comment] 2023-08-10 13:53
Electron {VERSION} isn't supported and hasn't been in some time. For us to continue triaging this issue, it must be present on a [currently supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) version of Electron. This issue will be closed in 10 days f there is no response.

**Comment by cgri1** [comment] 2023-08-11 04:49
The function of setContentProtection(true) does not work in Electron v25. I tried it. It does not prevent the window content. So the application is visible to other participants.

**Comment by codebytere** [comment] 2023-08-13 20:00
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by cgri1** [comment] 2023-08-14 07:39
https://gist.github.com/134dc069d09354bd808224ed9991c40c

@codebytere Thanks for your answer. I found an example of my situation. This is a good example of my problem. Firstly, you can run an example with version 21.4.1. You can see that the window of google.com is not seen in the main window. And then you update the version of electron 25.4.0. This time the window of google.com is seen in the main window. So same code but the function of setContentProtection(true) does not work in version 25.4.0

**Comment by cgri1** [comment] 2023-08-18 10:40
This problem is a little bit emergency situation for our application. Is there any development in this problem? @codebytere

**Comment by flyyuan** [comment] 2023-08-19 18:04
I have the same problem. setContentProtection only working in single window, not working in screen.

**Comment by flyyuan** [comment] 2023-08-19 18:04
#19880

**Comment by MarshallOfSound** [comment] 2023-08-19 22:29
Duplicate of #19880

**Closed by MarshallOfSound** 2023-08-19 22:29 UTC
Labels: platform/macOS, blocked/need-info ❌, bug :beetle:, 25-x-y
