### ISSUE TITLE
Remove GPU memory limit

### ISSUE THREAD

**Issue by coreybruce** [electron/electron#15305] opened 2018-10-20 10:49 UTC
Hey guys I really think the gpu memory 512mb limit should be removed or at least documented better on how to either enable the limit or remove the limit and have full access the the gpu memory since it already does know what GPU you are using ect.

It's really confusing when the code keeps changing, the command to do so use to be 
app.commandLine.appendSwitch('js-flags', '--max-old-space-size=4096');

but I wish there was a way to have access to full gpu memory and not allocate a certain amount which could run into issues with different pc configurations.

**Comment by nornagon** [comment] 2018-10-22 23:44
`max-old-space-size` affects v8 heap parameters, and has nothing to do with the GPU. Which memory limit are you talking about?

**Comment by coreybruce** [comment] 2018-10-23 05:13
That command is what I have been told to use but obviously wasn't what I was looking for, what I am looking for is a way to remove the gpu memory limit from 512mb to the max amount of allocated memory a gpu has to be used. How do I go with removing this limit?

**Comment by nornagon** [comment] 2018-10-23 19:31
Where are you getting that 512 MB limit from? What API are you calling that's returning 512 MB as the limit?

**Comment by coreybruce** [comment] 2018-10-24 02:02
@nornagon on my last comment I gave a screenshot showing what I meant

**Comment by MarshallOfSound** [comment] 2018-10-24 02:06
@coreybruce Your screenshot shows the number 512 but gives no indication where that number comes from or what API is provided that number as the "max".  We need that information 😄

**Comment by coreybruce** [comment] 2018-10-24 02:09
@MarshallOfSound I am sorry for the lack of information I am still learning and developing with the help of friends who do know electron better than I do. Pointing back at my screenshot which shows max 512mb gpu memory is that the allocated memory limit on it or am I incorrect to assume this?

**Comment by brenca** [comment] 2018-10-24 02:34
@coreybruce @MarshallOfSound I think that's the on screen FPS display HUD you can enable with a command line parameter, I think it's `--show-fps`. Also it looks like that limit comes from [here](https://cs.chromium.org/chromium/src/content/renderer/render_widget.cc?type=cs&sq=package:chromium&g=0&l=2868), and you can use `--force-gpu-mem-available-mb` to force it to a different value.

**Comment by coreybruce** [comment] 2018-10-24 02:48
@brenca I know how to enable the fps display hud and have that already enabled, adding --force-gpu-mem-available-mb to the end of the application while now no longer shows a min and max gpu memory or the gpu on the hud at all but now causes issues on the application not loading correctly and other web graphical issues. Looks like this is a bug with "--force-gpu-mem-available-mb"

**Comment by coreybruce** [comment] 2018-10-24 03:36
Before:

https://i.imgur.com/QMLpgUN.png

After:

https://i.imgur.com/4cIqIaC.png

Seems to loaded but doesn't show up and flickers the top bar sometimes, I can move the mouse around and see I can click on stuff but I cannot see it.

**Comment by MarshallOfSound** [comment] 2018-10-24 05:34
@coreybruce What exactly are you running from the CLI (all arguments)?

**Comment by coreybruce** [comment] 2018-10-24 05:38
I run the application than the argument after it 

e.g 
./GamerWorld --force-gpu-mem-available-mb

**Comment by MarshallOfSound** [comment] 2018-10-24 05:46
@coreybruce You need to give that switch a value, just the switch and no value is probably forcing it to 0 or something and causing the strange behavior.  E.g.

```bash
electron . ----force-gpu-mem-available-mb=2000
```

**Comment by coreybruce** [comment] 2018-10-24 05:53
@MarshallOfSound I can see the web gui now but it's still only showing 512mb gpu memory max

http://i.imgur.com/uPbKRVj.png

**Comment by coreybruce** [comment] 2018-10-24 06:50
@nornagon Might be a good idea to remove the "blocked/need-info" tag now

**Comment by brenca** [comment] 2018-10-24 15:55
@coreybruce I suppose you could 
1. look for an `npm` module or API call that can determine what kind of GPU the system has, and how much memory it has available
2. set the limit to that number

**Comment by coreybruce** [comment] 2018-10-24 16:19
@brenca Do you have any recommendations on a module to do that?

**Comment by nornagon** [comment] 2018-10-24 17:49
Thanks @brenca for finding that code reference! Are you sure that it applies to WebGL though? I traced the blame for that line back to [this commit from 2014](https://codereview.chromium.org/308743005) which says that the limit does not apply to "unmanaged" memory, e.g. WebGL. I can't find any reference on the internet for a hard-coded limit on WebGL memory.

@coreybruce are you seeing allocation failures when you allocate beyond 512MB, or is this a theoretical problem? If you're seeing failures, it would be helpful to have a reproduction that we could run.

Determining the amount of available GPU memory is a very non-trivial problem, see e.g. this thread on the Khronos mailing list: https://www.khronos.org/webgl/public-mailing-list/public_webgl/1303/msg00029.php

>I'm not sure that it will be possible to give a firm precise
measurement, as the notion of "how much memory there is" varies too much
from a device to another:
> - some devices have dedicated texture memory, while some others have
unified memory
> - beyond actual memory, there is virtual memory; some devices have
virtualized texture memory, some haven't.
> - there are many variations of what the above concepts mean on
different devices.

**Comment by coreybruce** [comment] 2018-10-24 18:05
@nornagon I haven't had any issues when manually allocating more gpu memory over 512mb but for my end users this won't be a practical option also it could be a potential issue as games will need more gpu memory as they grow visually and as the games get bigger and the limit of 512mb is not good enough.

Could you please show me where the example is and explain how to do it on here please?

**Comment by nornagon** [comment] 2018-10-24 18:21
If you can allocate more than 512MB of memory on your system, why wouldn't you be able to do so on an end-user's machine?

Given that:
a) You're reporting that there is no 512MB limit on WebGL memory, as you haven't run into any errors allocating over 512MB, and
b) The limit you're observing in the FPS meter was traced to a commit in Chromium that claims it doesn't apply to WebGL,

I'm closing this issue as I don't believe there's any action to take on part of Electron. Determining the amount of available GPU memory is beyond the scope of the Electron project, and is something you'll need to find your own way to do depending on your needs.

**Closed by nornagon** 2018-10-24 18:21 UTC
Labels: enhancement :sparkles:

**Comment by nornagon** [comment] 2018-10-24 18:41
That limit does not apply to WebGL.

See https://github.com/nornagon/electron-webgl-memory-test, which adapts Khronos's [out-of-memory test for WebGL](https://github.com/KhronosGroup/WebGL/blob/master/conformance-suites/2.0.0/extra/out-of-memory.html). On my machine, this test was able to allocate upwards of 16GB of memory.

There is no 512MB WebGL memory limit.

**Comment by coreybruce** [comment] 2018-10-24 18:43
Okay but what about on Electron applications? does this gpu memory limit affect WebGL games and there memory allocation at all?

**Comment by nornagon** [comment] 2018-10-24 18:43
No.

**Comment by coreybruce** [comment] 2018-10-24 18:45
Hmm ok what about Unity WebGL games? because I have had issues with a couple games giving me a unity out of memory error box

**Comment by brenca** [comment] 2018-10-25 00:55
@coreybruce What version of electron have you tested that with? Can you please try the latest beta (4.0.0-beta.something)? Also, if you can observe a difference between the latest chrome and our latest beta, please give us a sample game to confirm the bug.

@nornagon I didn't know if it affected WebGL or not, just recognized the HUD and wanted to move the conversation forward a bit.

**Comment by coreybruce** [comment] 2018-10-25 02:58
@brenca Electron 3.0.4

AHA! Confirmed, bug persists between from the version I am using 3.0.4 and the latest 3.0.6 on two known games that had out of memory issues  (another game which was a lot more tested and experience in this bug seems to be working on electron 3.0.4 ) all seem to be running without crashing with a out of memory issue on 4.0.0-beta.5.

**Comment by brenca** [comment] 2018-10-26 10:42
@coreybruce I know, but if we can't get concrete examples (games) to test with, we can't fix this in 3.0.x.

**Comment by coreybruce** [comment] 2018-10-26 13:06
@brenca 

Examples:

https://www.gameflare.com/online-game/battle-royale/

https://nadgames.com/combat_online This game use to do it but I think the issue might of been fixed either by Electron or the devs themselves

https://whalesandgames.itch.io/colossorama

These were the example games, after using Electron 4.0.0 there is no more out of memory message.
