### ISSUE TITLE
Observing GPU process `FatalExit`

### ISSUE THREAD

**Issue by hunterlester** [electron/electron#16422] opened 2019-01-16 19:17 UTC
* Output of `node_modules/.bin/electron --version`: v4.0.1
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.1.1

**Expected Behavior**
Utilizing [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon).
Upon execution of [electron-quick-start](https://github.com/electron/electron-quick-start), I expect to observe 2 child processes running. A GPU process and renderer process.
![image](https://user-images.githubusercontent.com/10050403/51271056-694f7e80-197b-11e9-9000-ea05e2d7c7af.png)

**Actual behavior**
Utilizing [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon).
Upon execution of [electron-quick-start](https://github.com/electron/electron-quick-start), I observe a third process that has been closed, containing in it's last thread stack a Windows `FatalExit + 0xa`.
![image](https://user-images.githubusercontent.com/10050403/51271485-93557080-197c-11e9-8e0d-893a42050f59.png)

Of note:
- The first two processes begin running at `10:48:06 AM` and no end time.
- The last closed process begins running at `10:48:20 AM`, ending at `10:48:21 AM`
- System Error code 0xa (10) defined as `ERROR_BAD_ENVIRONMENT`

Thread stack:
```
0	ntoskrnl.exe	RtlGetIntegerAtom + 0x780	0xfffff80264ec3490	C:\WINDOWS\system32\ntoskrnl.exe
1	ntoskrnl.exe	ObQueryObjectAuditingByHandle + 0x956	0xfffff80264ec58e6	C:\WINDOWS\system32\ntoskrnl.exe
2	ntoskrnl.exe	IoGetDeviceProperty + 0xf9b	0xfffff80264f8ac8b	C:\WINDOWS\system32\ntoskrnl.exe
3	ntoskrnl.exe	setjmpex + 0x6f63	0xfffff80264bca743	C:\WINDOWS\system32\ntoskrnl.exe
4	ntdll.dll	NtTerminateProcess + 0x14	0x7ffe6b9aaf24	C:\Windows\System32\ntdll.dll
5	ntdll.dll	RtlExitUserProcess + 0xe3	0x7ffe6b957e53	C:\Windows\System32\ntdll.dll
6	kernel32.dll	FatalExit + 0xa	0x7ffe6ae8b19a	C:\Windows\System32\kernel32.dll
7	electron.exe	uv_stream_set_blocking + 0x83cdbd	0x7ff73dbcd1ed	C:\Users\guilf\safe\electron-quick-start\node_modules\electron\dist\electron.exe
8	electron.exe	uv_stream_set_blocking + 0x83ce87	0x7ff73dbcd2b7	C:\Users\guilf\safe\electron-quick-start\node_modules\electron\dist\electron.exe
9	electron.exe	uv_stream_set_blocking + 0x82a814	0x7ff73dbbac44	C:\Users\guilf\safe\electron-quick-start\node_modules\electron\dist\electron.exe
10	kernel32.dll	BaseThreadInitThunk + 0x14	0x7ffe6ae83034	C:\Windows\System32\kernel32.dll
11	ntdll.dll	RtlUserThreadStart + 0x21	0x7ffe6b983691	C:\Windows\System32\ntdll.dll
``` 

**To Reproduce**
- Clone [electron-quick-start](https://github.com/electron/electron-quick-start)
- Use either [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) or alternative tool.
- Suggested to add a filter to solely observe `electron` processes.
- If using Process Monitor, use `CTRL + T` to open `Process Tree`, then scroll to `electron` processes.

**Why report this obscure potential bug?**
I'm experiencing a great, yet vague, application issue that I'm attempting to narrow down. The steps to reproduce that [issue](https://github.com/maidsafe/safe_browser/issues/410) are too many to reasonably request of this community. In short, black screen `webview`'s and crashed application. Observed cross-platform, not specific to Windows.

**Comment by nornagon** [comment] 2019-01-17 21:55
Hm, that stack trace is confusing to me. I think it's incorrectly labeling those addresses as `uv_stream_set_blocking` because a) that function can't be directly called from `BaseThreadInitThunk`, b) that function doesn't call itself, and c) that function isn't 75KB long.

Would love to see the properly symbolicated version of this stack trace though, looks like a juicy crash!

**Comment by hunterlester** [comment] 2019-01-31 17:40
So these thread stacks have been observed in Process Monitor while running `electron-quick-start`, so that it'd be easy to reproduce.

Some more background:
How I came to start watching electron processes was a thread stack that is actually being printed in my terminal when I run [this app](https://github.com/joshuef/detached_auth_poc/tree/MakingBrowser).

What's printed in my terminal is:
```
# Fatal error in , line 0
# Check failed: element->ToUint32(&number).
#
#
#
#FailureMessage Object: 00000075BA12BCF8Backtrace:
        node::InternalCallbackScope::MarkAsFailed [0x00007FF61E99718B+76811]
        uv_fileno [0x00007FF61F8A9887+5341815]
        IsSandboxedProcess [0x00007FF61EFDBC75+1476585]
        v8::internal::Isolate::random_number_generator [0x00007FF61E2754E2+38562]
        v8::internal::Isolate::random_number_generator [0x00007FF61E2743A1+34145]
        v8::internal::Isolate::random_number_generator [0x00007FF61E27423E+33790]
        v8::internal::Isolate::random_number_generator [0x00007FF61E273367+29991]
        v8::internal::Isolate::random_number_generator [0x00007FF61E2725FB+26555]
        v8::internal::Isolate::random_number_generator [0x00007FF61E27391F+31455]
        v8::internal::Isolate::random_number_generator [0x00007FF61E26E97D+11069]
        v8::internal::RegisterConfiguration::AreAliases [0x00007FF61E38409F+314687]
        v8::internal::Parser::BuildIteratorCloseForCompletion [0x00007FF61E7BF572+1495346]
```

Searching through the thread stacks in Process Monitor, the corresponding stack is the following:
```
0    ntoskrnl.exe    PspCallThreadNotifyRoutines + 0x140    0xfffff8011bd45490    C:\WINDOWS\system32\ntoskrnl.exe
1    ntoskrnl.exe    PspExitThread + 0x106    0xfffff8011bd478e6    C:\WINDOWS\system32\ntoskrnl.exe
2    ntoskrnl.exe    NtTerminateProcess + 0xeb    0xfffff8011be0cc8b    C:\WINDOWS\system32\ntoskrnl.exe
3    ntoskrnl.exe    KiSystemServiceCopyEnd + 0x13    0xfffff8011ba4c743    C:\WINDOWS\system32\ntoskrnl.exe
4    ntdll.dll    NtTerminateProcess + 0x14    0x7ffb2c41af24    C:\Windows\System32\ntdll.dll
5    ntdll.dll    RtlExitUserProcess + 0xe3    0x7ffb2c3c7e53    C:\Windows\System32\ntdll.dll
6    kernel32.dll    ExitProcessImplementation + 0xa    0x7ffb2c2ab19a    C:\Windows\System32\kernel32.dll
7    electron.exe    uv_stream_set_blocking + 0x83a9dd    0x7ff6216f23ad    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
8    electron.exe    uv_stream_set_blocking + 0x83aaa7    0x7ff6216f2477    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
9    electron.exe    uv_stream_set_blocking + 0x8537ee    0x7ff62170b1be    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
10    electron.exe    IsSandboxedProcess + 0x16b816    0x7ff61efdeca2    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
11    electron.exe    IsSandboxedProcess + 0x168800    0x7ff61efdbc8c    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
12    electron.exe    v8::internal::Isolate::random_number_generator + 0x96a2    0x7ff61e2754e2    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
13    electron.exe    v8::internal::Isolate::random_number_generator + 0x8561    0x7ff61e2743a1    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
14    electron.exe    v8::internal::Isolate::random_number_generator + 0x83fe    0x7ff61e27423e    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
15    electron.exe    v8::internal::Isolate::random_number_generator + 0x7527    0x7ff61e273367    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
16    electron.exe    v8::internal::Isolate::random_number_generator + 0x67bb    0x7ff61e2725fb    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
17    electron.exe    v8::internal::Isolate::random_number_generator + 0x7adf    0x7ff61e27391f    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
18    electron.exe    v8::internal::Isolate::random_number_generator + 0x2b3d    0x7ff61e26e97d    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
19    electron.exe    v8::internal::RegisterConfiguration::AreAliases + 0x4cd3f    0x7ff61e38409f    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
20    electron.exe    v8::internal::Parser::BuildIteratorCloseForCompletion + 0x16d132    0x7ff61e7bf572    C:\Users\guilf\safe\detached_auth_poc\node_modules\electron\dist\electron.exe
21    <unknown>    0x75ba12c4e0    0x75ba12c4e0  
```

Where do I find clues to debug?

**Comment by meekaah** [comment] 2019-04-11 09:11
i'm facing the same issue on macos using electron 4.0.1

**Comment by electron-triage** [comment] 2020-02-19 21:23
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:35
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:35 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/windows
