### ISSUE TITLE
Out of memory crash in renderer

### ISSUE THREAD

**Issue by computerquip-streamlabs** [electron/electron#13467] opened 2018-06-27 18:37 UTC
* Electron Version: 2.0.1
* Operating System (Platform and Version): Windows 10.0.17134
* Process Type: renderer

Crash report: https://gist.github.com/computerquip-streamlabs/d765a9646418bc7553af629f67379390

**Additional Information**
Reproducing this has proven impossible on local computers (laptops, desktops, weak or strong computers, different graphics vendors, etc.)  but these kinds of crashes have happened much more significantly since March~April when we upgraded to electron 2.x. 

Some of the crash report has been sanitized to remove usernames. I have a few thousand instances of this particular crash which are produced from our streaming application [here](https://github.com/stream-labs/streamlabs-obs). If more instances of the crash are wanted or more information is needed, I can provide them on request. 

I'm not sure the best method of proceeding on crashes like this given reproduction is difficult so advice on that would be nice. I've tried playing with a test-case to reproduce with no luck though it feels like finding a needle in a haystack. 

What I can say from the snippet above is that out of memory crashes, at least to that extent, seems unlikely given several thousand people have had them occur while for most people, the application sits at less than a few hundred megabytes of memory on a 64-bit distribution across all spawned processes. As it appears to be in the chromium renderer, we'll be looking into Electron v3.0.0 due to the upgraded chromium base.

Any insight on the issue would be useful, thanks.
There's a bounty on the issue provided whenever a solution provided leads to a fix of the issue.

**Comment by computerquip-streamlabs** [comment] 2018-06-27 19:55
Link to [bounty portal](https://www.bountysource.com/issues/60205425-out-of-memory-crash-in-renderer)

**Comment by computerquip-streamlabs** [comment] 2018-07-19 21:34
Here's another stack trace with a similar out of memory exception:
```
>	Streamlabs OBS.exe!atom::`anonymous namespace'::FatalErrorCallback(const char * location, const char * message) Line 30	C++
 	node.dll!v8::Utils::ReportOOMFailure(const char * location, bool is_heap_oom) Line 422	C++
 	node.dll!v8::internal::V8::FatalProcessOutOfMemory(const char * location, bool is_heap_oom) Line 388	C++
 	node.dll!v8::internal::Heap::FatalProcessOutOfMemory(const char * location, bool is_heap_oom) Line 6110	C++
 	node.dll!v8::internal::Factory::NewTransitionArray(int capacity) Line 1242	C++
 	node.dll!v8::internal::TransitionArray::Insert(v8::internal::Handle<v8::internal::Map> map, v8::internal::Handle<v8::internal::Name> name, v8::internal::Handle<v8::internal::Map> target, v8::internal::SimpleTransitionFlag flag) Line 108	C++
 	node.dll!v8::internal::Map::ConnectTransition(v8::internal::Handle<v8::internal::Map> parent, v8::internal::Handle<v8::internal::Map> child, v8::internal::Handle<v8::internal::Name> name, v8::internal::SimpleTransitionFlag flag) Line 9037	C++
 	node.dll!v8::internal::Map::CopyReplaceDescriptors(v8::internal::Handle<v8::internal::Map> map, v8::internal::Handle<v8::internal::DescriptorArray> descriptors, v8::internal::Handle<v8::internal::LayoutDescriptor> layout_descriptor, v8::internal::TransitionFlag flag, v8::internal::MaybeHandle<v8::internal::Name> maybe_name, const char * simple_flag, v8::internal::SimpleTransitionFlag) Line 9077	C++
 	node.dll!v8::internal::Map::CopyAddDescriptor(v8::internal::Handle<v8::internal::Map> map, v8::internal::Descriptor * descriptor, v8::internal::TransitionFlag) Line 9638	C++
 	node.dll!v8::internal::Map::CopyWithField(v8::internal::Handle<v8::internal::Map> map, v8::internal::Handle<v8::internal::Name> name, v8::internal::Handle<v8::internal::FieldType> type, v8::internal::PropertyAttributes attributes, v8::internal::PropertyConstness representation, v8::internal::Representation) Line 3616	C++
 	node.dll!v8::internal::Map::TransitionToDataProperty(v8::internal::Handle<v8::internal::Map> map, v8::internal::Handle<v8::internal::Name> name, v8::internal::Handle<v8::internal::Object> value, v8::internal::PropertyAttributes attributes, v8::internal::PropertyConstness store_mode, v8::internal::Object::StoreFromKeyed) Line 9434	C++
 	node.dll!v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject> receiver, v8::internal::Handle<v8::internal::Object> value, v8::internal::PropertyAttributes attributes, v8::internal::Object::StoreFromKeyed store_mode) Line 380	C++
 	node.dll!v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator * it, v8::internal::Handle<v8::internal::Object> value, v8::internal::Object::StoreFromKeyed store_mode) Line 1561	C++
 	node.dll!v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator * lookup, v8::internal::Handle<v8::internal::Object> value, v8::internal::Object::StoreFromKeyed store_mode) Line 1655	C++
 	node.dll!v8::internal::StoreIC::Store(v8::internal::Handle<v8::internal::Object> object, v8::internal::Handle<v8::internal::Name> name, v8::internal::Handle<v8::internal::Object> value, v8::internal::Object::StoreFromKeyed store_mode) Line 1638	C++
 	node.dll!v8::internal::KeyedStoreIC::Store(v8::internal::Handle<v8::internal::Object> object, v8::internal::Handle<v8::internal::Object> key, v8::internal::Handle<v8::internal::Object> value) Line 2255	C++
 	node.dll!v8::internal::Runtime_KeyedStoreIC_Miss(int args_length, v8::internal::Object * * args_object, v8::internal::Isolate * isolate) Line 2494	C++
 	0000010d010047a1()	Unknown
 	node.dll!v8::internal::Runtime_KeyedStoreIC_Miss(int args_length, v8::internal::Object * * args_object, v8::internal::Isolate * isolate) Line 2494	C++
 	0000002e00000000()	Unknown

```

**Comment by miniak** [comment] 2018-08-26 12:16
@computerquip-streamlabs did you try increasing the V8 heap size limit?

**Comment by miniak** [comment] 2018-08-26 12:16
Closing as this is not a bug report nor a feature request.

**Closed by miniak** 2018-08-26 12:16 UTC
Labels: bug :beetle:, platform/windows, version/2.0.x
