### ISSUE TITLE
Auth http basic doesn't work

### ISSUE THREAD

**Issue by lesleyandreza** [electron/electron#21082] opened 2019-11-11 14:23 UTC
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * \>= electron v7.0.0-beta.4
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * electron v7.0.0-beta.3

### Expected Behavior
Load all resources.

### Actual Behavior
Doesn't load all resources.

### To Reproduce

For bugs that can be encapsulated in a small experiment, you can use Electron Fiddle (https://github.com/electron/fiddle) to publish your example to a GitHub Gist and link it your bug report.

Was created a web page with HTTP Basic to reproduce bug: https://urr8o0dc29gon6u1.prodoctor.net with user and password equals urr8o0dc29gon6u1.

`main.js`
```javascript
const {app, BrowserWindow} = require('electron')

let mainWindow

function createWindow () {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })

  mainWindow.loadURL('https://urr8o0dc29gon6u1.prodoctor.net')

  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('login', (event, webContents, request, authInfo, callback) => {
  callback('urr8o0dc29gon6u1', 'urr8o0dc29gon6u1');
})

app.on('ready', createWindow)

app.on('window-all-closed', function () {
  app.quit()
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})
```

**Comment by t57ser** [comment] 2019-11-11 14:30
Related: https://github.com/electron/electron/issues/20752

**Comment by nornagon** [comment] 2019-11-13 00:23
Duplicate of #20752

**Closed by nornagon** 2019-11-13 00:23 UTC
