### ISSUE TITLE
setAsDefaultProtocolClient for protocol tel:// does not work at Windows 10

### ISSUE THREAD

**Issue by GeorgeTsaplin** [electron/electron#14108] opened 2018-08-15 11:51 UTC
* Electron Version: v2.0.5
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: 

**Expected Behavior**
On calling url with protocol "tel://" electron application must appeare at dialog window with appropriate applications wich can handle tel protocol.

**Actual behavior**
On calling url with protocol "tel://" Electron application does not appeare at list of applications wich can handle tel protocol.

**To Reproduce**
1. Include `app.setAsDefaultProtocolClient(Protocol);` at main.js;
2. Package application for Windows;
3. Install application from step 2 (will be run automatically after installing);
4. Call any "tel://" url (for example from Win+R execute command "tel://1234");

```sh
$ git clone https://github.com/GeorgeTsaplin/FinesseConnector -b master
$ npm install
$ yarn install
$ yarn dist
```
**Additional Information**
Possible solution will be change `SetAsDefaultProtocolClient` implementation at [browser_win.cc](/electron/electron/blob/master/atom/browser/browser_win.cc): for Windows 10 must be set such registry keys:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Classes\callto]
@="URL:callto"
"URL Protocol"=""

[HKEY_CURRENT_USER\SOFTWARE\Classes\tel]
@="URL:tel"
"URL Protocol"=""

[HKEY_CURRENT_USER\SOFTWARE\Classes\{Electron application name}.callto]

[HKEY_CURRENT_USER\SOFTWARE\Classes\{Electron application name}.callto\DefaultIcon]
@="{path to electron application exe file}"

[HKEY_CURRENT_USER\SOFTWARE\Classes\{Electron application name}.callto\shell]

[HKEY_CURRENT_USER\SOFTWARE\Classes\{Electron application name}.callto\shell\open]

[HKEY_CURRENT_USER\SOFTWARE\Classes\{Electron application name}.callto\shell\open\command]
@="\"{path to electron application exe file}" %1"

[HKEY_CURRENT_USER\SOFTWARE\{Electron application name}]

[HKEY_CURRENT_USER\SOFTWARE\{Electron application name}\Capabilities]
"ApplicationDescription"="{Electron application description}"
"ApplicationName"="{Electron application name}"

[HKEY_CURRENT_USER\SOFTWARE\{Electron application name}\Capabilities\URLAssociations]
"callto"="{Electron application name}.callto"
"tel"="{Electron application name}.callto"

[HKEY_CURRENT_USER\SOFTWARE\RegisteredApplications]
"{Electron application name}"="Software\\{Electron application name}\\Capabilities"
```

Also must be changed `IsDefaultProtocolClient` and `RemoveAsDefaultProtocolClient`

**Comment by maxleverin** [comment] 2018-12-18 09:20
Additional information:
I just tested this in Electron v.3.0.10. Issue still exists, both for `tel` and `callto` urls.

Operating System:
- Windows 10
- Version 1709
- OS Build 16299.125

**Comment by Mika56** [comment] 2018-12-18 09:27
As a workaround, anyone wanting to register the tel protocol can use this snippet:
```ts
import {Registry} from 'rage-edit';

if(process.platform === 'win32') {

    (async () => {
        await Registry.set('HKCU\\Software\\Your app name\\Capabilities', 'ApplicationName', 'Your app name');
        await Registry.set('HKCU\\Software\\Your app name\\Capabilities', 'ApplicationDescription', 'Your app name');

        await Registry.set('HKCU\\Software\\Your app name\\Capabilities\\URLAssociations', 'tel', 'Your app name.tel');

        await Registry.set('HKCU\\Software\\Classes\\Your app name.tel\\DefaultIcon', '', process.execPath);

        await Registry.set('HKCU\\Software\\Classes\\Your app name.tel\\shell\\open\\command', '', `"${process.execPath}" "%1"`);

        await Registry.set('HKCU\\Software\\RegisteredApplications', 'Your app name', 'Software\\Your app name\\Capabilities');
    })();
}
```

The registration is per user, so you need to execute this code for every user. You can execute it at every launch of your app, it won't do any harm.
This won't prevent you from building on Linux or macOS, rage-edit uses the `reg` command, and a such is not a native dependency.

**Comment by clusterberries** [comment] 2019-07-02 16:02
Hello!
Thank you for workaround for Windows 10.

I found out a case when tel: protocol cannot be used on Windows 7. If there is no default application for tel: protocol, I can register my own application and it works perfect. But if there is another program already registered, my application isn't even displayed in the list of available applications. 
Maybe somebody know what are the registry keys that should be added to display my application in the list for tel: protocol?

**Comment by sofianguy** [comment] 2019-08-09 00:06
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by clusterberries** [comment] 2019-08-13 07:19
@sofianguy the issue for Windows 7 I described in the last comment is reproduced on 5.0.2. I guess issue for Windows 10 is reproduced on the same version. I'll check it today.

**Comment by clusterberries** [comment] 2019-08-13 08:14
The issue is reproduced with Electron 5.0.2 on Windows 10

**Comment by joeyer** [comment] 2019-11-11 12:43
@clusterberries  Is there a solution for win7?

**Comment by joeyer** [comment] 2019-11-13 06:23
As a workaround, anyone wanting to register the tel protocol in window 7 can use this snippet:

import {Registry} from 'rage-edit';
(async () => {
        await Registry.set('HKCR\\Your app name', '', `Your app name`);
        await Registry.set('HKCR\\Your app name\\DefaultIcon', '', `"${process.execPath}" "%1"`);
        await Registry.set('HKCR\\Your app name\\shell\\open\\command', '', `"${process.execPath}" "%1"`);
        await Registry.set('HKCR\\tel', '', 'Your app name');
        await Registry.set('HKCR\\tel\\DefaultIcon', '', process.execPath);
        await Registry.set('HKCR\\tel\\shell\\open\\command', '', `"${process.execPath}" "%1"`);

        await Registry.set('HKLM\\SOFTWARE\\Classes\\Your app name', '', 'Your app name');
        await Registry.set('HKLM\\SOFTWARE\\Classes\\Your app name\\DefaultIcon', '', process.execPath);
        await Registry.set('HKLM\\SOFTWARE\\Classes\\Your app name\\shell\\open\\command', '', `"${process.execPath}" "%1"`);
        await Registry.set('HKLM\\SOFTWARE\\Classes\\tel', '', 'Your app name');
        await Registry.set('HKLM\\SOFTWARE\\Classes\\tel\\DefaultIcon', '', process.execPath);
        await Registry.set('HKLM\\SOFTWARE\\Classes\\tel\\shell\\open\\command', '', `"${process.execPath}" "%1"`);
    })();

**Comment by clusterberries** [comment] 2019-11-15 09:09
@joeyer I tried to find solution for windows 7, I tried to set keys to HKLM, but it requires admin rights. My application doesn't have admin rights, so it is not an appropriate solution for me.

**Comment by electron-triage** [comment] 2020-02-19 20:18
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:20
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:20 UTC
Labels: 2-0-x, 5-0-x, blocked/need-info ❌, bug :beetle:, platform/windows

**Comment by N4COM** [comment] 2022-02-23 08:23
Hi, I'm using electron 15.0.0 with Windows 10. The method seems not work. I tried with "tel", "callto" and with a custom protocol. The app is not registered for the protocol I specify, so when I call the url, the app won't be opened. Also app can't be registered as default app manually, so the problem is that the method doesn't register the app for handling protocol.

My code is very simple:

```
const protocol = "tel"; //or "callto" or "customprotocol"
app.setAsDefaultProtocolClient(protocol);
```

Is there some log I can activate in order to investigate it? Should I manually write the keys into register?

**Comment by gr33k** [comment] 2022-02-23 21:41
Found this when searching for a solution to https://github.com/electron/electron/issues/22565 - The best are workarounds which require admin privileges for your application (not even sure how well they work in windows 7,8,10 let alone 11). Do the Electron SDK devs anticipate this will ever be fixed? If so, do we have ETA please?

**Comment by PeteAUK** [comment] 2023-02-03 12:39
This appears to still be an issue in that it's not possible to use `app.setAsDefaultProtocolClient('tel')` to register the application so that it appears within the Windows list of applications.  Don't really want to hook up a registry hack for this.  Please could this issue be reopened and investigated.

Running ElectronJS v22.2.0 on a Windows 10 PC.  I've also got local administrator rights, although the end user may not.

**Comment by thanhle7** [comment] 2023-08-14 23:35
Not making any sense. Setting default app for some type of document requires some admin privileges. How to could we make it possible from an user's app.

**Comment by PeteAUK** [comment] 2023-08-15 07:21
> Not making any sense. Setting default app for some type of document requires some admin privileges. How to could we make it possible from an user's app.

Pretty sure the handler for the tel protocol doesn't require admin privileges to set in Windows in the same way as setting the default handler for a .doc file doesn't because it should be being set at a user level, not machine.  The whole point (and this issue is closed btw) is that the setAsDefaultProtocolClient doesn't work

**Comment by galletafromjell666** [comment] 2024-02-21 20:19
This issue has been present for a while, I do not think it will be solved in a near future since Windows uses a hash to validate the protocol association (at least it has been reverse engineered, [link](https://kolbi.cz/blog/2017/10/25/setuserfta-userchoice-hash-defeated-set-file-type-associations-per-user/)). 

You can check the registry entry for the association here:
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\Shell\Associations\UrlAssociations\tel\UserChoice`

To have a similar experience as `setAsDefaultProtocolClient` you could include a flow like:
1 - Register the app using this [workaround](https://github.com/electron/electron/issues/14108#issuecomment-448153935). Alternatively, you can use electron-builder and a custom NSIS.
2 - Remove the current protocol association:
```js
const { Registry } = require('rage-edit');

await Registry.delete('HKCU\\Software\\Microsoft\\Windows\\Shell\\Associations\\UrlAssociations\\tel\\UserChoice');
```
3 - Make the association modal appear with:
```js
const { shell } = require('electron');

shell.openExternal('tel:');
```

You can tweak the flow checking if your app is currently the protocol handler:
```js
const myAppName = 'your-app-name'
const protocol = 'tel'
const registryAppName = await Registry.get(
      `HKCU\\Software\\Microsoft\\Windows\\Shell\\Associations\\UrlAssociations\\${protocol}\\UserChoice`,
      'ProgId'
    );

const associatedAppName = registryAppName.replace(`.${protocol}`, '');
const isMyAppAssociated = associatedAppName === myAppName 
```

Please do not forget to remove your entries from the Windows Registry when your app is being uninstalled.

**Comment by logivadivelu** [comment] 2024-10-24 15:15
I implemented deep-linking and tested in windows 11,  it was not working. 

 ```
 if (process.defaultApp) {
        if (process.argv.length >= 2) {
            app.setAsDefaultProtocolClient(protocol, process.execPath, [path.resolve(process.argv[1])])
        }
    } else {
        app.setAsDefaultProtocolClient(protocol)
    }
```
