### ISSUE TITLE
Window10 system education version electron startup failed

### ISSUE THREAD

**Issue by gaohui1994** [electron/electron#44957] opened 2024-12-05 10:02 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

31.0.1

### What operating system(s) are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

新开发的, 不太清楚

### Expected Behavior

electron startup success

### Actual Behavior

electron startup failed

----- Native stack trace -----

 1: 00007FF66DFDD64A uv_cpumask_size+72986
 2: 00007FF66DF7A42F node::InitializeOncePerProcess+1663
 3: 00007FF66DF79DD5 node::InitializeOncePerProcess+37
 4: 00007FF66C2F1F08 node::loader::ModuleWrap::SelfSize+3096
 5: 00007FF66C239774 std::__Cr::vector<v8::CpuProfileDeoptFrame,std::__Cr::allocator<v8::CpuProfileDeoptFrame> >::__alloc+73812
 6: 00007FF66D12F7EF uv_timer_set_repeat+1137887
 7: 00007FF66D133593 uv_timer_set_repeat+1153667
 8: 00007FF66D12ED9D uv_timer_set_repeat+1135245
 9: 00007FF66C3EFAE2 v8::ScriptCompiler::ScriptStreamingTask::ScriptStreamingTask+482914
10: 00007FF66C3F0D0A v8::ScriptCompiler::ScriptStreamingTask::ScriptStreamingTask+487562
11: 00007FF66C3F0AF1 v8::ScriptCompiler::ScriptStreamingTask::ScriptStreamingTask+487025
12: 00007FF66C3EF2FF v8::ScriptCompiler::ScriptStreamingTask::ScriptStreamingTask+480895
13: 00007FF66C3EF4DD v8::ScriptCompiler::ScriptStreamingTask::ScriptStreamingTask+481373
14: 00007FF66C12B563 std::__Cr::vector<v8::CpuProfileDeoptFrame,std::__Cr::allocator<v8::CpuProfileDeoptFrame> >::vector<v8::CpuProfileDeoptFrame,std::__Cr::allocator<v8::CpuProfileDeoptFrame> >+56611
15: 00007FF67053EFE2 Cr_z_adler32+5714626
16: 00007FF94AB87374 BaseThreadInitThunk+20
17: 00007FF94C11CC91 RtlUserThreadStart+33

**Comment by clavin** [comment] 2024-12-06 19:20
Duplicate of #44881

**Closed by clavin** 2024-12-06 19:20 UTC
Labels: platform/windows, bug :beetle:, 31-x-y

**Comment by yangllu** [comment] 2024-12-10 03:48
@gaohui1994 As mentioned in https://github.com/electron/electron/issues/44881, I discovered that this crash occurs because the nul device service has been disabled. However, I still don't understand why this service was disabled. 

Could you please help confirm if you have also encountered the nul device service being disabled? If so, do you have any insights about why it might be disabled?
