### ISSUE TITLE
[Bug]: printToPDF freeze / stuck the app (is not responding)

### ISSUE THREAD

**Issue by Brouilles** [electron/electron#31695] opened 2021-11-03 14:55 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22000.282

### What arch are you using?

x64

### Expected Behavior

Generate the PDF in the background and don't stuck the main window of the application.

### Actual Behavior

During the generation of the PDF. The main window not respond and Windows show "is not responding" in the Task Manager. Can't interact with the content of the app or move it.

### Additional Information

I have trying to run the printToPDF on a node worker or fork processus. Without success. My renderer don't wait any answer from the main. After a couple of seconds, when the pdf is generated, the app work correctly.

```js
// Print to PDF
ipcMain.on('generatePDF', (event, name, type, id) => {
  const pdfOptions = {
    marginsType: 1,
    pageSize: 'A4',
    printBackground: true,
    printSelectionOnly: false,
    landscape: false
  };

  let win = new BrowserWindow({
    show: false,
    webPreferences: {
      preload: PDF_WINDOW_PRELOAD_WEBPACK_ENTRY,
    }
  });
  
  win.loadURL(PDF_WINDOW_WEBPACK_ENTRY + `?${new URLSearchParams({id, type})}`);

  const filePath = dialog.showSaveDialogSync(mainWindow, {
    defaultPath: name,
    filters: [
      { name: 'PDF', extensions: ['pdf'] }
    ]
  });

  event.sender.send('onPDFStartResponse');

  if (filePath && filePath.length > 0) {
    win.webContents.on('did-finish-load', () => {
      win.webContents.printToPDF(pdfOptions).then(data => {
        fs.writeFile(filePath, data, function (err) {
          if (err) {
            log.error(err);
          } else {
            log.info('PDF Generated Successfully');
            event.sender.send('onPDFGeneratedResponse', path.basename(filePath));
          }

          win.close();
          win = null;
          // shell.openExternal(filePath);
        });
      }).catch(error => {
        log.error(error)
        win.close();
        win = null;
      });
    });
  } else {
    win.close();
    win = null;
  }
});
```

Inside my preload: 
```js
import { ipcRenderer, contextBridge } from 'electron';

contextBridge.exposeInMainWorld('electron', {
    generatePDF: (name, type, id) => ipcRenderer.send('generatePDF', name, type, id),
});
```

Inside my app: `window.electron.generatePDF(`Devis-${this.estimate.id.toString().padStart(6, 0)}.pdf`, 'estimate', this.estimate.id);`

**Comment by Brouilles** [comment] 2021-11-03 15:00
Maybe related https://github.com/electron/electron/issues/17171

**Comment by codebytere** [comment] 2021-11-08 15:29
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed** 2021-11-09 17:26 UTC
Labels: bug :beetle:, blocked/need-repro
