### ISSUE TITLE
Can't compile electron

### ISSUE THREAD

**Issue by Zhairgling** [electron/electron#9522] opened 2017-05-18 17:08 UTC
Hiii all,

* Operating system:
```
@ubuntu:~/buildElectron/electron$ uname  -a
Linux ubuntu 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```
I've followed this : https://electron.atom.io/docs/development/build-instructions-linux/

Here is the error message
```
/usr/bin/python /home/ju/buildElectron/electron/vendor/libchromiumcontent/script/build -R -t x64
ninja: Entering directory `src/out-x64/static_library'
[2046/19926] ACTION //third_part...build/toolchain/linux:clang_x64)
FAILED: gen/blink/core/XPathGrammar.cpp gen/blink/core/XPathGrammar.h 
python ../../third_party/WebKit/Source/build/scripts/rule_bison.py ../../third_party/WebKit/Source/core/xml/XPathGrammar.y gen/blink/core bison
Traceback (most recent call last):
  File "../../third_party/WebKit/Source/build/scripts/rule_bison.py", line 82, in <module>
    returnCode = subprocess.call([bisonExe, '-d', '-p', prefix, inputFile, '-o', outputCpp])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[2051/19926] ACTION //third_part...build/toolchain/linux:clang_x64)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/ju/buildElectron/electron/vendor/libchromiumcontent/script/build", line 53, in <module>
    sys.exit(main())
  File "/home/ju/buildElectron/electron/vendor/libchromiumcontent/script/build", line 39, in main
    subprocess.check_call([NINJA, '-C', os.path.relpath(out_dir), target], env=env)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ju/buildElectron/electron/vendor/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'src/out-x64/static_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "/home/ju/buildElectron/electron/script/build-libchromiumcontent.py", line 51, in <module>
    sys.exit(main())
  File "/home/ju/buildElectron/electron/script/build-libchromiumcontent.py", line 34, in main
    execute_stdout([sys.executable, build, '-R', '-t', args.target_arch])
  File "/home/ju/buildElectron/electron/script/lib/util.py", line 180, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/ju/buildElectron/electron/vendor/libchromiumcontent/script/build', '-R', '-t', 'x64']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 287, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 44, in main
    build_libchromiumcontent(args.verbose, args.target_arch, defines)
  File "./script/bootstrap.py", line 216, in build_libchromiumcontent
    execute_stdout(args + ['--target_arch', target_arch])
  File "/home/ju/buildElectron/electron/script/lib/util.py", line 180, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/ju/buildElectron/electron/script/build-libchromiumcontent.py', '-v', '--defines', ' clang=0', '--target_arch', 'x64']' returned non-zero exit status 1

```

**Comment by cifratila** [comment] 2017-05-18 17:41
@Zhairgling Any reason you are trying to build libchromiumcontent as part of electron build?

I you still want to compile libchromiumcontent you need to go here: https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md and install all the pre-requisites.

**Comment by Zhairgling** [comment] 2017-05-19 09:06
@cifratila Hi, yes i want to build the whole electron project for running on armv6.
I have read your link and the System requirements looks insane.Do I really have to start the process that 
 you suggested?

**Comment by cifratila** [comment] 2017-05-19 16:03
@Zhairgling You can do this:

> Once you have checked out the code, and assuming you're using Ubuntu, `run build/install-build-deps.sh

Just run this script: `https://chromium.googlesource.com/chromium/src/+/master/build/install-build-deps.sh`

From experience, just so you are prepared, depending on your computer compiling libcc will take up to 5 hours. Also the dependency script will have to install hundreds of packages.

**Comment by Zhairgling** [comment] 2017-05-19 18:44
@cifratila 
It seems rather that it is a problem with python because when I use the command:
```
./script/bootstrap.py -v 
```
.
I have a similar problem.

**Comment by cifratila** [comment] 2017-05-22 09:54
@Zhairgling Don't think the problem is python. You might need to check what the bootstrap script does.
I would recommend to run the clean script and then give the bootstrap script one more try.

Seems it fails on updating node modules, basically on running the following method: https://github.com/electron/electron/blob/master/script/bootstrap.py#L170

Try to run `npm install --verbose`

Also the script sets up the clang environment variables in order to compile native node modules.

**Comment by cifratila** [comment] 2017-05-24 16:22
@Zhairgling Any success with this one?

**Comment by enlight** [comment] 2017-07-30 10:17
Closing until more info is provided.

**Closed by enlight** 2017-07-30 10:17 UTC
Labels: component/build, more-information-needed, platform/linux/ubuntu
