### ISSUE TITLE
Node IPC not working after spawning Electron with empty env

### ISSUE THREAD

**Issue by pofider** [electron/electron#6868] opened 2016-08-16 20:28 UTC
I'm unable to make a simple IPC communication between node and spawned electron process working on linux ubuntu. It works fine on Windows.

node.js code

``` js
var electron = require('electron-prebuilt')
var spawn = require('child_process').spawn

var child = spawn(electron, ['electron-script.js'], {
  stdio: ['ipc']
})

child.on('message', function (m) {
  console.log('Yes it works!')
})
```

electron script

``` js
process.send('I am ok')
process.exit(0);
```

On windows I get back `Yes it works!` to console. There seems to be no communication happening and nothing is printed on ubuntu. Thank you for the help.
- Electron version: ~ 1.3.1
- Operating system: Ubuntu

**Comment by zcbenz** [comment] 2016-08-18 06:11
Hmm I can get `Yes it works!` in console on Ubuntu with Electron 1.3.3.

**Comment by pofider** [comment] 2016-08-18 07:28
Thank you for looking at it. I have the following configuration:

electron-prebuilt: 1.3.3
node: 4.4.7
ubuntu: 14.04

Then I simply type: `node node_script.js`. Process exits and nothing is printed out.

I'll gladly email you ssh to the public VM or test this on different node/ubuntu configuration if you say.

**Comment by bjrmatos** [comment] 2016-08-29 00:01
i've found the issue, it only occurs in linux (ubuntu in my case).

OS: ubuntu 16
node: 4.4.7
electron: 1.3.4 (installed with `electron-prebuilt`)

the issue happens when passing the `env` option (even with an empty object) for the `child_process.spawn` method.

nodejs code:

```js
var electron = require('electron-prebuilt');
var spawn = require('child_process').spawn;

var child = spawn(electron, ['electron-script.js'], {
  stdio: ['pipe', 'pipe', 'pipe', 'ipc'],
  // if you pass some value, even an empty object, 
  // the electron process will always exit immediately on linux, works fine in OSX
  env: {} 
});

child.on('exit', function() {
  console.log('child process exit..');
});

child.on('message', function (m) {
  console.log('yes it works');
});
```

electron-script code:

```js
process.send('I am ok')
process.exit(0);
```

![electron-linux-issue](https://cloud.githubusercontent.com/assets/4262050/18037769/a454dcb0-6d51-11e6-8938-232b70a6ce68.gif)


seems like the entire `env` object for the electron process in linux is overridden and that's why it ended up crashed.

@pofider can you update the issue's title to reflect the real problem? thnks!

@zcbenz can you verify the issue?

**Comment by zcbenz** [comment] 2016-08-30 07:45
Thanks for narrowing down the problem, I can reproduce it on Linux and it works fine on mac.

**Comment by bjrmatos** [comment] 2016-09-03 22:26
@zcbenz shouldn't the label be `linux` instead of `osx` ?

**Comment by mikeys** [comment] 2016-09-27 18:26
Any progress on this issue? This is a major pain...

**Comment by karolba** [comment] 2016-10-08 13:00
This doesn't seem to happen if you leave DISPLAY set.

        env: { 'DISPLAY': process.env.DISPLAY },

That seems to be documented in [docs/tutorial/testing-on-headless-ci.md](https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md).

>Being based on Chromium, Electron requires a display driver to function. If Chromium can't find a display driver, Electron will simply fail to launch

**Comment by pofider** [comment] 2016-11-12 20:40
@karolba That seems to work, thank you

**Comment by MatthieuLemoine** [comment] 2017-12-20 15:18
I'm experiencing a similar issue with a packaged linux electron (1.8.1) app.

When running the following script to spawn the electron app : 

```javascript
const { spawn } = require('child_process');

const command = '/path/to/binary';

const child = spawn(command, [], {
  stdio    : ['pipe', 'pipe', 'pipe', 'ipc']
});
```
The window does open but the app won't load : 
![electron-crash](https://user-images.githubusercontent.com/8517072/34213839-b9acf91c-e5a0-11e7-857e-580f4a3447c1.png)

If I remove the fourth fd `ipc`, it's working fine : 

```javascript
const { spawn } = require('child_process');

const command = '/path/to/binary';

const child = spawn(command, [], {
  stdio    : ['pipe', 'pipe', 'pipe']
});
```

Actually I have no use for the ipc channel but I use [pm2](http://pm2.keymetrics.io/) to start this app which spawn the given app using [ipc](https://github.com/Unitech/pm2/blob/master/lib/God/ForkMode.js#L99).

**Comment by roccomuso** [comment] 2018-01-16 12:39
@MatthieuLemoine but if you omit the `ipc` with the `fork()` it throws an exception. This is valid only for `spawn()`

**Comment by codebytere** [comment] 2018-05-09 03:37
Does this occur on `2.0.0`?

**Comment by codebytere** [comment] 2018-05-18 15:41
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2018-05-18 15:41 UTC
Labels: blocked/need-info, bug :beetle:, platform/linux, version/1.8.x

**Comment by bjrmatos** [comment] 2018-05-18 17:40
> With only the information that is currently in the issue, we don't have enough information to take action

hmm i'm not sure that is true, i've provided [an example that shows the bug](https://github.com/electron/electron/issues/6868#issuecomment-243007963), it is short to try it, and it was even confirmed by another member in the electron team. 

however i will try electron v2 and see if the bug is still there

**Comment by adamdoyle** [comment] 2019-03-20 18:33
@codebytere I reverted to 2.0.0 and the issue persists for me.

**Comment by adamdoyle** [comment] 2019-03-20 18:35
If it matters, I'm on CentOS 7

**Comment by adamdoyle** [comment] 2019-03-20 19:08
Related to:  #17044
