### ISSUE TITLE
Setting `content-length` fails in `net` in electron@7

### ISSUE THREAD

**Issue by arantes555** [electron/electron#21091] opened 2019-11-12 11:06 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * macOS 14.6
* **Last Known Working Electron version:**
  * 6.1.4

### Expected Behavior
When creating a request with `net`, if you explicitly set a `content-length` header, electron should send the request with this `content-length` header.

### Actual Behavior
If you set a `content-length`, the request fails with `net::ERR_INVALID_ARGUMENT`.

### To Reproduce

```sh
$ git clone https://github.com/arantes555/electron-bug-net-content-length.git
$ npm install
$ npm start
```

### Additional Information

This is not a huge problem for normal requests, as the `content-length` is automatically computed and set by the `net` module. However, for requests that set `chunkedEncoding: true`, the request is sent in chunks so the `net` module cannot know, so does not send, the `content-length`.

Also, I am the author of [`electron-fetch`](https://www.npmjs.com/package/electron-fetch), and I just wanted to say that this change makes it harder to implement the `fetch` specification correctly against `net`.

**Comment by nornagon** [comment] 2019-11-13 22:14
It looks like the root cause here is https://cs.chromium.org/chromium/src/services/network/public/cpp/header_util.cc?q=header_util.cc&sq=package:chromium&g=0&l=23-25, the network service doesn't allow the consumer to set such a header. I agree that it should be possible to set the `Content-length` header for a chunked-encoding stream though. Perhaps there's some other way we can indicate the size of the upload body other than setting the header directly.

**Comment by nornagon** [comment] 2019-11-13 22:18
It looks like `net` specifically does not set a `Content-Length` header for chunked encoding: https://cs.chromium.org/chromium/src/net/http/http_network_transaction.cc?l=941-949&rcl=bcf164cac37e6d7b8338c3f5e1d6637466089ab1

What requires this header to be set? Does `fetch` in the browser actually set that header in the case that the uploaded data is not a body of known size?

**Comment by arantes555** [comment] 2019-11-13 23:58
@nornagon The thing is, the `content-length` can be known for the app, but unknown to `net`. For example, in case I want to upload a large file, I know the exact size of it, but it makes way more sense to open it as a stream and pipe it to the request.

For `fetch` in the browser, there is no body of unknown size, as browsers do not (yet) allow sending a stream in a `fetch` request, so basically the `content-length` is always set.

**Comment by nornagon** [comment] 2019-11-14 00:04
I don't believe there's a particular reason to use chunked encoding if you know the size in advance. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding additionally states:

> **chunked**
>    Data is sent in a series of chunks. _The `Content-Length` header is omitted in this case_ [...]

Further, the [HTTP Spec](https://tools.ietf.org/html/rfc7230#section-3.3.2) forbids it:

> A sender MUST NOT send a Content-Length header field in any message that contains a Transfer-Encoding header field.

**Comment by nornagon** [comment] 2019-11-14 00:11
I'm closing this as it seems like intended behavior to me, but happy to continue discussion and reopen if needed.

**Closed by nornagon** 2019-11-14 00:11 UTC
Labels: 7-1-x, component/net

**Comment by popod** [comment] 2019-11-14 08:11
@nornagon so what to do ?

Before I have this config

``` js
headers: {
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(data),
    'User-Agent': 'myApp'
  }
```

And it does not works with newer electron versions. Should I only remove the `Content-Length` property to make this works ?

Thanks

**Comment by arantes555** [comment] 2019-11-14 15:02
@nornagon after further investigation, it appears you were right : the fact that electron <= 6 allowed to set a `content-length` when `chunkedEncoding` was used was not spec-compliant so could be considered a bug.

However, the fact that electron@7 does not allow to manually set the `content-length` at all (whether or not `chunkedEncoding` is used) is not documented at all, neither in the `ClientRequest.setHeader` documentation, nor in the changelog which should definitely mention this breaking change.

Also, further testing shows a lot of similar breaking changes in `net` in electron@7, as well as weird crashes. I'll open relevant issues when I have time to put together repro cases.

@popod yes, you can just remove the `content-length` alltogether.

**Comment by szmarczak** [comment] 2019-11-15 15:54
This is a bug. Electron does not do this:

https://github.com/sindresorhus/got/blob/13c0990c1a139d517c9d50869bec3ef33dec9aed/source/utils/get-body-size.ts#L24-L31

**Comment by arantes555** [comment] 2019-11-15 16:05
@szmarczak it is actually not. It is indeed a breaking change in behaviour, not present in the changelog, and not documented at all, yes. But the new behaviour kinda makes sense:
- If `chunkedEncoding` is false, electron buffers the whole body before sending the request, so it can compute the precise `content-length` itself
- If `chunkedEncoding` is true, the HTTP spec forbids sending a `content-length` header

So preventing the user from setting the `content-length` is not absurd. I could even say it is better than the behaviour of electron <= 6.1.4, which actually stalls and never terminates a request when you set a wrong `content-length`...

However, the undocumented breaking change in this behaviour is indeed ... less than ideal :)

**Comment by szmarczak** [comment] 2019-11-15 17:14
> electron buffers the whole body before sending the request

Source code please?

**Comment by arantes555** [comment] 2019-11-15 17:42
@szmarczak I do not have source code, as it's directly in Chromium and I'm not very comfortable with C++. However : 
- The doc says so : https://electronjs.org/docs/api/client-request#requestchunkedencoding
> Using chunked encoding is strongly recommended if you need to send a large request body as data will be streamed in small chunks instead of being internally buffered inside Electron process memory.
- The test-case I wrote for this report proves it:
```
$ git clone https://github.com/arantes555/electron-bug-net-content-length.git
$ npm install
$ npm start
```
You will see that, even when using Streams, the server receives a `content-length` that is correct.

**Comment by szmarczak** [comment] 2019-11-15 18:31
Ah, you're right: https://github.com/electron/electron/blob/master/lib/browser/api/net.js

Thanks for the explaination :)
