### ISSUE TITLE
Top area of application window is not clickable after BrowserWindow is maximized then restored when titleBarStyle set to "hiddenInset"

### ISSUE THREAD

**Issue by circleapps** [electron/electron#17425] opened 2019-03-17 10:08 UTC
* **Electron Version:**
  *  4.x, 3.x
* **Operating System:**
  * macOS 10.13.5
* **Last Known Working Electron version:**:
  * unknown

### Expected Behavior

Top area is always clickable no matter what window state is.

### Actual Behavior

Top area is not clickable after BrowserWindow is maximized then restored when titleBar set to "hiddenInset"

### To Reproduce

1. Create a simple electron app.
2. Set titleBarStyle of BrowserWindow to "hiddenInset"
3. put a button in the top area of the Window, give it a click handler
4. maximize then restored the Window, you will find the button is not clickable.

Or 

git clone https://github.com/circleapps/electron-quick-start
npm install
npm start

1. Click the button in the middle of the top area of the Window, it is clickable 
2. Maximize the Window.
3. Restore the Window to its normal size
4. Click the button again, the button is not clickable.

**Comment by circleapps** [comment] 2019-03-19 00:54
I know this bug sounds weird, but it does happen.

To workaround this problem, I have to hide the title bar buttons completely and mimic their behaviour by my own code. The performance is not good as the native title bar buttons, that is why I have to open this bug.

Hope someone could take a look on this problem, it is fairly easy to reproduce by cloning my repo. 
Thanks.

**Comment by codebytere** [comment] 2019-03-19 21:14
Closing as duplicate of https://github.com/electron/electron/issues/16418.

**Closed by codebytere** 2019-03-19 21:14 UTC
