### ISSUE TITLE
Electron 10.1.1 app crashes when saving a pdf from the print dialog

### ISSUE THREAD

**Issue by dgmid** [electron/electron#25397] opened 2020-09-09 21:39 UTC
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.1
* **Operating System:**
  * macOS 10.15.6 
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
I should be able to save a pdf file from the pdf menu without the app crashing

### Actual Behavior
the pdf saves, but the app crashes

### To Reproduce

Electron fiddle:
https://gist.github.com/c5de74c2973633e178803eef65b827df

### Screenshots
![pdf-menu](https://user-images.githubusercontent.com/1267580/92657588-62feda80-f2f5-11ea-8639-6c63c576703f.png)

### Additional Information
It seems to be any of the options in this menu that crashes the app.
Removing the callback and running it like this:
```
mainWindow.webContents.print(printOptions)
```
seems to resolve it -- but I need the callback

**Comment by dgmid** [comment] 2020-09-11 08:17
Just tried electron 11.0.0-beta.6 and this issue is fixed in that version

**Comment by hmt** [comment] 2020-09-12 20:23
Seems to be a duplicate of #25327 At least I came to the same conclusion in my fiddle :)

**Comment by dgmid** [comment] 2020-09-13 07:34
@hmt I'm having no problems actually printing from my app -- for me it's the PDF menu in the print dialog that crashes the app.

Looking at it again, the gist I posted is a bit simpler than the actual setup in my app. In my app, on printing I create a new hidden browserWindow with the contents to print in it and then close the hidden browserWindow after printing.

For me, printing works every time using this method. What doesn't work is the PDF menu.
I don't doub't that it is the same bug though!

**Comment by hmt** [comment] 2020-09-14 05:56
I mean, blaming the callback seems to fit both categories. Probably the underlying problem is the same in both instances. PDF printing and printing in general.

**Comment by codebytere** [comment] 2020-09-14 16:32
Yep, this is known - it's not the callback per se as this is specific to the dialog presented by the pdf viewer. The wiring is not the same.

**Comment by dgmid** [comment] 2020-09-15 06:39
@codebytere thanks for the explanation.
Hopefully this gets fixed soon in 10-x otherwise I'll wait for 11-x as that seems to work perfectly.

**Comment by pushkin-** [comment] 2020-09-22 21:04
I can repro this in 10.1.2 on Windows 10. not mac specific

**Comment by pushkin-** [comment] 2020-09-22 21:26
Is this the same as [this issue](https://github.com/electron/electron/issues/25254)?

**Comment by codebytere** [comment] 2020-09-24 16:37
They look different - just tested the other one. I'll try to look today.

**Comment by alex-drocks** [comment] 2020-09-28 18:45
I am getting the crash on Window 10 with window.print() and BrowserWindow.getCurrent.webContents.print().
Does not matter if I print to paper or pdf it crashes when the window is closed.

**Comment by codebytere** [comment] 2020-09-28 23:13
@alex-drocks that is solved with https://github.com/electron/electron/pull/25622, which i will backport when i have a moment

**Comment by codebytere** [comment] 2020-09-28 23:19
This issue is fixed by https://github.com/electron/electron/pull/25530, due out in next release

**Closed by codebytere** 2020-09-28 23:19 UTC
Labels: 10-x-y, bug/crash :boom:, platform/macOS

**Comment by alex-drocks** [comment] 2020-09-29 12:40
Thank you that is awesome.
