### ISSUE TITLE
Webview sometimes crashes on page navigation on linux

### ISSUE THREAD

**Issue by daltonmenezes** [electron/electron#6139] opened 2016-06-20 00:29 UTC
I have two buttons. Each one has a link for a youtube video. If I do not click on the video to play after it appears in the webview, I can change the src of webview by clicking on another button and I can see the image of the other video appears in the window. But if I click on either one and play the video, when I try to click on another button to see the another video, the webview is broken and all black and do not show me the video.

I tried too reload the window on standard menu of Electron, and the window is blank. Same behavior only If I play one video. is this a bug? how can I fix it?

[EDIT]
If you want to reproduce this behavior and check the code, here's the repository:
https://github.com/daltonmenezes/electron-error-example

[Video showing the error]
https://www.youtube.com/watch?v=ADoJGvNyJ7E&feature=youtu.be
- Electron version: 1.2.2
- Operating system: Ubuntu 16.04

**Comment by MarshallOfSound** [comment] 2016-06-20 02:54
Can you upload a minimum example

**Comment by daltonmenezes** [comment] 2016-06-20 03:53
@MarshallOfSound , here
https://github.com/daltonmenezes/electron-error-example

**Comment by MarshallOfSound** [comment] 2016-06-20 11:10
FWIW I can't replicate this on Windows, booting into Ubuntu now

**Comment by daltonmenezes** [comment] 2016-06-20 15:38
@MarshallOfSound , That's true. I tested on Windows now and it works, but Ubuntu the strange behavior happens.

**Comment by zcbenz** [comment] 2016-06-21 00:32
I'm also not able to reproduce on Ubuntu. Can you also test the page by putting it in a [Chrome app](https://developer.chrome.com/apps/first_app)? I want to verify whether it is an upstream Chromium bug.

**Comment by daltonmenezes** [comment] 2016-06-21 01:44
@zcbenz , I tried to create the chrome app, but the simplest hello world don't run. Could you try it? My code is [here](https://github.com/daltonmenezes/electron-error-example/blob/master/main.html) 
There are another way for me to help?

**Comment by zcbenz** [comment] 2016-06-21 01:52
In Chrome app you need to call `webview.src = '...'`.

The problem is no one can reproduce this except for yourself, so you are basically on your own.

**Comment by daltonmenezes** [comment] 2016-06-21 18:58
@zcbenz  I've tested the code on ubuntu virtualized on windows and it works well, but when I've tested on ubuntu 14 LTS on my notebook, the strange behavior happens. so, I did a clean instalation on my pc again with ubuntu 16.04 and the strange behavior happens too.

**Comment by daltonmenezes** [comment] 2016-06-23 01:54
There are some problem with webview, because I've tested now with iframes and the code works.

**Comment by MarshallOfSound** [comment] 2016-06-23 01:59
@daltonmenezes Can you try launching electron with the `--disable-gpu` flag

**Comment by daltonmenezes** [comment] 2016-06-23 02:04
@MarshallOfSound haha, man. This makes the code works well. How can I put this in app? There are something better instead of put this for standard on app?

**Comment by MarshallOfSound** [comment] 2016-06-23 02:18
@daltonmenezes I believe you call this method

https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration

For @zcbenz 
I clicked when I saw the youtube video, this issue is reproducible on certain hardware on Linux distributions.  I've seen the issue before, it's been described as "the app becomes a white screen and unresponsive".  I think their is some kind of GPU error that causes the renderer process to crash.

Example issues: 
MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/885  
MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/296  

It became such a common problem we had to write a [Wiki Entry](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ#i-am-part-of-the-glorious-linux-master-race-and-it-doesnt-go-past-the-sign-in-screen) about it.

It appears to be isolated to crashing when a navigation occurs inside a WebView.  I.e. If you don't change pages it doesn't crash.

**Comment by daltonmenezes** [comment] 2016-06-23 02:36
@MarshallOfSound Thank you so much, man. Now, I believe this problem occurs on AMD gpu on Linux. All my tests mentioned I did and got this failures on amd gpu. My specs:

Intel i7 12GB ram, AMD R9 270.
My current drivers is [oibaf](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers)
But the standard drivers started on Ubuntu doesn't work too.

**Comment by MarshallOfSound** [comment] 2016-06-30 22:23
@zcbenz Do you have any thoughts as to why the webview is crashing.  At the moment the workaround is just to add

```js
if (process.platform === 'linux') {
    app.disableHardwareAcceleration();
}
```

Which is hardly a good long term solution as it compromises performance

**Comment by zcbenz** [comment] 2016-07-01 12:20
@MarshallOfSound It is very likely a Chromium bug.

**Comment by MarshallOfSound** [comment] 2016-07-01 12:23
@zcbenz I both suspected and dreaded as much 😢

**Comment by daltonmenezes** [comment] 2016-07-01 14:33
@zcbenz @MarshallOfSound check this post and the comments http://www.kelvinblog.tk/enable-chromium-vaapi-hardware-acceleration-linux/

**Comment by derfmilo** [comment] 2016-08-29 05:38
When Adding pmx it solves this issue and many other cross native bugs on memory cluster issues

**Comment by paulcbetts** [comment] 2016-08-29 05:41
@MarshallOfSound tbh we ship Slack to always disable GPU because it causes so many issues :cry:

**Comment by derfmilo** [comment] 2016-08-29 09:28
That's why so many use alerts or idle handlers.

**Comment by ericbets** [comment] 2017-02-05 01:19
I bought an AMD gpu for a change and sadly I also have this problem on Fedora 25, though it's certainly not confined to only in webview page navigation. --disable-gpu helps alot.

**Comment by codebytere** [comment] 2018-05-09 03:26
Given the conversation above, it appears that the actionable issues in this have been addressed. In that event, i'm going to go ahead and close this, but please feel free to @ me if something else arises!

**Closed by codebytere** 2018-05-09 03:26 UTC
Labels: blocked/upstream, bug :beetle:, component/webview, platform/linux

**Comment by DuBistKomisch** [comment] 2018-06-01 04:45
@codebytere shouldn't this be left open while tracking the upstream bug and until it's merged into electron? Assuming it hasn't already, but doesn't seem like it based on this issue.

We're also seeing it on Windows sometimes, FWIW.
