### ISSUE TITLE
[Bug]: Tmp files should be cleaned

### ISSUE THREAD

**Issue by xoxloviwan** [electron/electron#40630] opened 2023-11-28 20:19 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Files generated in `Users\[username]\AppData\Local\Temp` after asar unpacking (tmp.js, tmp.png etc) must be removed by electron.
Other solution must be cleaning mechanism of tmp folder or subfolder for current launch.

### Actual Behavior

as described in #10139

**Comment by mlaurencin** [comment] 2023-11-29 17:14
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

If you’re still experiencing this issue in Electron 26.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2024-01-29 12:01
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2024-01-29 12:01 UTC
Labels: blocked/need-info ❌, bug :beetle:

**Comment by Phillipus** [comment] 2024-06-30 12:03
I've installed two Electron based apps for Windows (Signal and Twinkle Tray) and both create temp files that are not cleaned up on the app's exit. This can potentially create gigabytes of files on a user's drive. See [here](https://github.com/xanderfrangos/twinkle-tray/issues/542) for an example. For me Electron based apps on Windows are a no-go because of this. I don't know how other users manage, perhaps they just buy a new hard drive every so often?
