### ISSUE TITLE
[mac] "quit" is not work after packaging

### ISSUE THREAD

**Issue by wuww5511** [electron/electron#8687] opened 2017-02-15 07:19 UTC
There is a quit option on the menu which is shown after right clicking the dock icon. After packaging the app with electron-packager, the quit option do not work.

**Comment by MarshallOfSound** [comment] 2017-02-15 07:20
@wuww5511 Can you provide a minimal sample application that reproduces the issue, I'm struggling to reproduce on `1.4.x` or `1.6.x`.

A common cause for this issue is people preventing default on `will-quit`, you should ensure you aren't doing that as well.

**Comment by wuww5511** [comment] 2017-02-15 07:58
Maybe it is caused by the package "fix-path". When I add "require('fix-path')();", the quit action will not work.

**Comment by kevinsawicki** [comment] 2017-03-09 01:16
@wuww5511 can you provide a code snippet for an Electron app using `fix-path` that fails for you? Thanks.

**Comment by wuww5511** [comment] 2017-03-12 09:53
@kevinsawicki I cloned "https://github.com/electron/electron-quick-start" and added `require('fix-path')();` to main.js at the first line. Then I packaged it with "electron-packager". The version of electron is v1.6.3 and the OS is macOS Sierra 10.12.

**Comment by wuww5511** [comment] 2017-03-12 10:14
@kevinsawicki I have made a video. https://www.youtube.com/watch?v=M6E3yWMg9n4

**Comment by zcbenz** [comment] 2017-06-06 07:43
I'm closing this since it is caused by a third party module, not an issue of Electron.

**Closed by zcbenz** 2017-06-06 07:43 UTC
Labels: more-information-needed
