### ISSUE TITLE
ffmpeg.so is larger from separate download compared to release

### ISSUE THREAD

**Issue by bpasero** [electron/electron#5160] opened 2016-04-14 16:34 UTC
* Electron version: 0.37.5
* Operating system: Linux

We recently switched to Electron 0.37.5 for VS Code and changed our build scripts to replace ffmpeg with the version you guys offer as separate download. Our understanding is that this version is built with the target "chromium" as opposed to "chrome" and thus includes less codecs.

Surprisingly though the ffmpeg.so file for Linux is almost double the size for the separate download compared to what is included in the release.

Maybe the scripts are flipped and the separate download actually is the one built with "chrome" as target?

**Comment by kevinsawicki** [comment] 2016-04-14 16:37
Might this be a duplicate of https://github.com/electron/electron/issues/4905 ?

**Comment by bpasero** [comment] 2016-04-14 16:43
Oh yeah, seems related :+1:

**Comment by zcbenz** [comment] 2016-04-15 11:03
Merging to #4905.

**Closed by zcbenz** 2016-04-15 11:03 UTC
