### ISSUE TITLE
Top ~24px of a frameless BrowserWindow ignores CSS cursor style

### ISSUE THREAD

**Issue by pdesantis** [electron/electron#20102] opened 2019-09-03 23:36 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0-beta.4
  * 6.0.7
  * 5.0.10
  * 4.2.10
  * 3.1.13
  * 2.0.18
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * unknown (doesn't work on the latest major releases listed above)

### Expected Behavior

Cursor style is applied when mousing over a frameless `BrowserWindow`.

### Actual Behavior

Cursor style is ignored for the top ~24px of a frameless `BrowserWindow`

### To Reproduce
1. Create a `BrowserWindow` with `frame: false`
2. Add the following to the page's HTML:
```html
<div style="height: 50px; width: 100%; background-color: red; cursor: pointer;"></div>
```
3. Run the app
4. Hover your cursor over the top of the window

Electron Fiddle example:
https://gist.github.com/7bc823b3ce1797d45841cf799f52008f

### Screenshots
![2019-09-03 16 09 47](https://user-images.githubusercontent.com/1420364/64214409-4b308300-ce65-11e9-99ab-c7dd16a012f1.gif)

### Additional Information
The affected area _appears to be_ the height of a native macOS title bar.

**Comment by pdesantis** [comment] 2019-09-03 23:38
After filing, I found some closed issues that seem related but are still relevant:
* https://github.com/electron/electron/issues/5723
* https://github.com/electron/electron/issues/6725
* https://github.com/electron/electron/issues/13911

**Comment by MarshallOfSound** [comment] 2019-09-03 23:52
Duplicate of #5723, the platform limitations are explained in that issue along with potential work arounds

**Closed by MarshallOfSound** 2019-09-03 23:52 UTC
