### ISSUE TITLE
[Bug]: Warning: Class WebSwapCGLLayer is implemented in both system library and electron distribution

### ISSUE THREAD

**Issue by geronimus** [electron/electron#33685] opened 2022-04-08 20:19 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0

### What operating system are you using?

macOS

### Operating System Version

12.3.1

### What arch are you using?

x64

### Last Known Working Electron version

17.3.1

### Expected Behavior

Starting electron using the npm script `"app":  "electron ."` starts the app with no warnings.

### Actual Behavior

Electron starts normally, but with the following warning:

```
Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffa5a006318) and /{path/to/app}/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10f8a89c8). One of the two will be used. Which one is undefined.
```
(`{path/to/app}` has been substituted for the actual path to the app on my system.)

**Comment by miniak** [comment] 2022-04-09 13:12
@geronimus why didn't you use a proper title for the bug?

**Comment by geronimus** [comment] 2022-04-10 06:58
Apologies. I don't often do these on github, and the structured form took me a little by surprise.

**Comment by WuYunlong** [comment] 2022-04-11 08:06
```bash
objc[60540]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffa4bc3c318) and /Users/macos/Desktop/ezos-electron-vite/node_modules/.pnpm/electron@18.0.3/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x111a019c8). One of the two will be used. Which one is undefined.

```

**Comment by miniak** [comment] 2022-04-12 00:51
`WebSwapCGLLayer` is defined in https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.mm

**Comment by miniak** [comment] 2022-04-12 00:55
it can be fixed by applying this patch in third_party/angle
```patch
diff --git a/src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.h b/src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.h
index 783a3dff4..8cfca6aa6 100644
--- a/src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.h
+++ b/src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.h
@@ -17,8 +17,7 @@ typedef _CGLContextObject *CGLContextObj;
 struct __IOSurface;
 typedef __IOSurface *IOSurfaceRef;
 
-// WebKit's build process requires that every Objective-C class name has the prefix "Web".
-@class WebSwapCGLLayer;
+@class SwapCGLLayer;
 
 namespace rx
 {
@@ -87,7 +86,7 @@ class WindowSurfaceCGL : public SurfaceGL
                                               const gl::FramebufferState &state) override;
 
   private:
-    WebSwapCGLLayer *mSwapLayer;
+    SwapCGLLayer *mSwapLayer;
     SharedSwapState mSwapState;
     uint64_t mCurrentSwapId;
 
diff --git a/src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.mm b/src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.mm
index 21894682d..fd95c07df 100644
--- a/src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.mm
+++ b/src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.mm
@@ -24,7 +24,7 @@
 #    include "libANGLE/renderer/gl/StateManagerGL.h"
 #    include "libANGLE/renderer/gl/cgl/DisplayCGL.h"
 
-@interface WebSwapCGLLayer : CAOpenGLLayer {
+@interface SwapCGLLayer : CAOpenGLLayer {
     CGLContextObj mDisplayContext;
 
     bool initialized;
@@ -38,7 +38,7 @@ - (id)initWithSharedState:(rx::SharedSwapState *)swapState
             withFunctions:(const rx::FunctionsGL *)functions;
 @end
 
-@implementation WebSwapCGLLayer
+@implementation SwapCGLLayer
 - (id)initWithSharedState:(rx::SharedSwapState *)swapState
               withContext:(CGLContextObj)displayContext
             withFunctions:(const rx::FunctionsGL *)functions
@@ -213,9 +213,9 @@ - (void)drawInCGLContext:(CGLContextObj)glContext
     mSwapState.lastRendered   = &mSwapState.textures[1];
     mSwapState.beingPresented = &mSwapState.textures[2];
 
-    mSwapLayer = [[WebSwapCGLLayer alloc] initWithSharedState:&mSwapState
-                                                  withContext:mContext
-                                                withFunctions:mFunctions];
+    mSwapLayer = [[SwapCGLLayer alloc] initWithSharedState:&mSwapState
+                                               withContext:mContext
+                                             withFunctions:mFunctions];
     [mLayer addSublayer:mSwapLayer];
     [mSwapLayer setContentsScale:[mLayer contentsScale]];
```

**Comment by Superoryco** [comment] 2022-04-19 05:59
For me, change loader in webpack config to '@vercel/webpack-asset-relocator-loader', solved my problem, but I don't know why.

**Comment by codebytere** [comment] 2022-05-10 11:12
Looks like they tried to fix this: https://bugs.chromium.org/p/angleproject/issues/detail?id=5253 but it seems now WebCore has the one they changed it to? Not sure 🤔

**Comment by miniak** [comment] 2022-05-10 16:08
@codebytere LOL, we'll just need to change it to yet another name here to avoid the conflict then.

**Comment by pickhardt** [comment] 2022-05-15 04:06
Does this warning cause any actual problems? I'm on a Mac and get this in my console, but it still seems to work fine. The warning says "which one is undefined" which seems to imply it could be using the wrong one, but so far the Electron app runs OK for me.

**Comment by Delagen** [comment] 2022-05-18 14:29
As for me it looks like https://github.com/electron/electron/issues/33508 both in dev & packaged mode

**Comment by tjx666** [comment] 2022-05-23 18:30
Same here: https://github.com/tjx666/electron-vue-vite-boilerplate

**Comment by Delagen** [comment] 2022-05-25 14:20
@miniak any news? Issue is blocking update on current supported version. 17 is last working version, but not supported by electron team.

**Comment by WUTONK** [comment] 2022-05-26 06:35
<img width="712" alt="截屏2022-05-26 14 32 20" src="https://user-images.githubusercontent.com/76605143/170431158-44c5823f-4295-4ac0-b1f9-f0e54d7e87cc.png">
I have encountered similar problems, but the electronic application is loaded normally. I have encountered some installation problems due to GFW before. I successfully installed it using a reliable yarn image source (taoabao)

**Comment by dengshenkk** [comment] 2022-06-02 08:05
`npm install --save-dev electron` 
`"electron": "^19.0.2"`
`electron .` is reproduce

**Comment by maneetgoyal** [comment] 2022-06-02 11:30
Working fine in "electron": "^17.4.7",. Facing issue in the latest version 19.x.

**Comment by changyongyong** [comment] 2022-06-12 12:01
我也碰到这个问题，不过是我项目结构所导致的，我想实现的是一个项目会有多个界面，所以我打算用vue输出有多个静态入口，不同页面加载对应的静态入口，我的vue.config.js配置中pages会有多个，下边是我项目的结构，这个问题有方法解决么
<img width="844" alt="image" src="https://user-images.githubusercontent.com/10693934/173232095-a998bb90-ad2c-4038-8f65-6597502a76bb.png">

**Comment by changyongyong** [comment] 2022-06-12 12:02
> 我也碰到这个问题，不过是我项目结构所导致的，我想实现的是一个项目会有多个界面，所以我打算用vue输出有多个静态入口，不同页面加载对应的静态入口，我的vue.config.js配置中pages会有多个，下边是我项目的结构，这个问题有方法解决么 <img alt="image" width="844" src="https://user-images.githubusercontent.com/10693934/173232095-a998bb90-ad2c-4038-8f65-6597502a76bb.png">

这是控制台打印的结果：
(node:21660) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/changyong/workspace/gitlab/electron/com_me/dist_electron/package.json' of 'background.js'. Please either fix that or report it to the module author
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:21660) ExtensionLoadWarning: Warnings loading extension at /Users/changyong/Library/Application Support/com_me/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
objc[21661]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x24a27f808) and /Users/changyong/workspace/gitlab/electron/com_me/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10734d348). One of the two will be used. Which one is undefined.

**Comment by MattCCC** [comment] 2022-06-12 12:46
Can you speak in English please, guys? I'm observing the situation here as this bug affects my app as well :(

**Comment by GoetheDady** [comment] 2022-06-23 09:00
> Same issue here, any fix?

I think no~ because, i still console that with using the latest version, just now now now

**Comment by cnryb** [comment] 2022-07-12 06:23
Follow progress

**Comment by adrorocker** [comment] 2022-07-15 02:45
> Follow progress

x2

**Comment by IanButterworth** [comment] 2022-07-15 02:46
Please just subscribe to the issue rather than comment

**Comment by adrorocker** [comment] 2022-07-15 03:08
Commenting  is a way to bring attention. Sorry if this is not allowed, will subscribe now.

**Comment by slavikator** [comment] 2022-07-15 14:19
Same issue.
In my case, the app starts but doesn't do what it is supposed to do. And I can't figure out what's wrong because the console doesn't log anything.
It is asking:
`.....One of the two will be used. Which one is undefined.`
And waits for the answer. Doesn't it? What should I "answer"?

**Comment by codebytere** [comment] 2022-07-20 09:48
Feel free to follow https://bugs.chromium.org/p/angleproject/issues/detail?id=7123. That is where upstream progress is being tracked.

**Comment by xgqfrms** [comment] 2022-07-29 09:40
## Q:

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/7291672/181731682-c94a0ad2-f7a4-435a-a0e6-4cd355e089c2.png">

## A: 

TODO

**Comment by AndreiSoroka** [comment] 2022-08-05 20:48
Hi! electron@20.0.1 the same problem

<img width="384" alt="image" src="https://user-images.githubusercontent.com/6079139/183160193-f9a90c53-06d0-44b0-9253-8b27cc58430d.png">

need to add tag 20.x.y

**Comment by nxm** [comment] 2022-08-15 20:58
Hey,

v20.0.2 the same issue

**Comment by MarshallOfSound** [comment] 2022-08-15 21:06
There is no indication in this issue thread that it has been fixed, continually posting "Version {random} same issue" comments is not helpful to anyone and only serves to spam maintainers who are subscribed to these updates.  I'll be locking this issue temporarily to avoid such comments.

Following https://bugs.chromium.org/p/angleproject/issues/detail?id=5253 is your best bet

**Comment by miniak** [comment] 2022-10-10 11:06
@MarshallOfSound we need to patch it ourselves. WebKit on Mac is also using ANGLE and will be exporting the symbol. Chromium / Electron needs to use a different name for it.

**Closed** 2023-01-05 06:49 UTC
Labels: platform/macOS, bug :beetle:, 18-x-y, 19-x-y
