### ISSUE TITLE
Google Font Api is broken in Electron Beta V3.0.0

### ISSUE THREAD

**Issue by CreatorVilius** [electron/electron#13399] opened 2018-06-23 13:11 UTC
* Electron Version: <sup>3.0.0 BETA</sup>
* Operating System (Platform and Version): <sub> Windows </sub>
* Last known working Electron version: 2.0.0

**Expected Behavior**
Website font should render, example: Google Font Api's Font Should Render like in Non-beta Electron

**Actual behavior**
Google fonts don't work in css using `@import url('https://fonts.googleapis.com/css?family=Share+Tech+Mono');` **Works in electron earlier versions**

**To Reproduce**
Install electron-quick-start, install Electron v3.0.0 beta

**Additional Information**
`<link>` tag for google api doesn't work either...

# Changing version to 2.0.3 fixes this

**Comment by CreatorVilius** [comment] 2018-06-23 13:17
>!lol

**Comment by jkleinsc** [comment] 2018-07-10 21:06
I can reproduce this in 3.0.0-beta.1 and 3.0.0-beta.2.  It looks like an SSL error:

```[8428:0710/170416.244:ERROR:ssl_client_socket_impl.cc(1098)] handshake failed; returned -1, SSL error code 1, net_error -107```

**Comment by jkleinsc** [comment] 2018-07-10 21:08
I believe this is the same issue as #13375

**Comment by MarshallOfSound** [comment] 2018-07-11 00:47
Tested in `3.0.0-beta.2` and this works for me, @jkleinsc @CreatorVilius can you double check beta.2 and provide a failing test case

**Comment by jkleinsc** [comment] 2018-07-11 00:56
@MarshallOfSound did you test it on Windows?

**Comment by jkleinsc** [comment] 2018-07-11 01:43
I just retested in Windows with 3.0.0-beta.2 and it is working for me.

**Comment by MarshallOfSound** [comment] 2018-07-11 02:08
Closing out, any follow up should go in #13375

**Closed by MarshallOfSound** 2018-07-11 02:08 UTC
Labels: bug/regression :leftwards_arrow_with_hook:, platform/windows, status/confirmed, version/3.0.x
