### ISSUE TITLE
crash-reporter broken on mac (0.31.0) ?

### ISSUE THREAD

**Issue by felicienfrancois** [electron/electron#2609] opened 2015-08-27 08:32 UTC
With the upgrade to io.js 3.1.0, my app is crashing electron on linux and mac osx if I don't rebuild modules.

On linux the crash reports are successfully sent, on mac I get the following error:
```error
ERROR:http_transport_mac.mm(186)] Could not connect to the server. (NSURLErrorDomain -1004)
```

When I remove the following code from the renderer, the app still crash but I no longer get the NSURLErrorDomain error
```javascript
require('crash-reporter').start({
	productName: 'MyAppName',
	companyName: 'MyCompanyName',
	submitUrl: 'https://mydomain.com/crash-report.php',
	autoSubmit: true
});
```
_In the example I replaced names and urls by fake ones. Original are valid ones. Url is on https with a valid certificate, and works at least on linux._

Also, the app no longer quit when the renderer is crashed, even with the following code on the main side (on both linux and mac osx)
```javascript
app.on('window-all-closed', function() {
	app.quit();
});
```

**Comment by zcbenz** [comment] 2015-08-27 09:25
Can you try if this app works for you?
https://gist.github.com/zcbenz/9c75ccda4f925faf92ca

Also there was an update of Electron that requires you to start crash reporter on both main process and renderer process to make it work.

**Comment by felicienfrancois** [comment] 2015-08-28 08:13
Hi @zcbenz,
I know about the requirement to start crash reporter on both main and renderer processes and my app do it.

I tested the app from gist using the following command line:
```Electron.app/Contents/MacOS/Electron app_folder```

And I get the following error in both 0.31.0 and 0.31.1:
```
[694:0828/100438:INFO:renderer_main.cc(200)] Renderer process started
{ _companyName: 'GitHub, Inc',
  _productName: 'crash-reporter-test',
  _version: '',
  guid: '5f1dfcf3-d22f-4cde-b927-759d8874add1',
  platform: 'darwin',
  process_type: 'renderer',
  prod: 'Electron',
  ver: '0.31.1' }
[0828/100438:ERROR:http_transport_mac.mm(186)] The network connection was lost. (NSURLErrorDomain -1005)
```

I am on Yosemite, I'm connected to internet through a router (but without proxy), my DNS servers are google DNS. all others apps and browsers are working well.

**Comment by zcbenz** [comment] 2015-08-29 07:25
@felicienfrancois The test app created a small server and printed the received data when the page crashes, and from the output the crash reporter works as expected. Can you modify the test app and make it behave more like your app and then see if you can make a reproducible example of your problem? Otherwise there is no way for us to find out what's going wrong.

**Comment by felicienfrancois** [comment] 2015-08-29 09:20
If I change the submitUrl to my external server, I get the following error:
```
[0829/110129:ERROR:http_transport_mac.mm(186)] cannot parse response (NSURLErrorDomain -1017)
```

I checked the server's logs. I get a POST request with an empty body. The server answered HTTP 200 (empty body)

If i exec the same app with electron 0.26.1, I don't get this error and it works perfectly. From 0.27.x it is broken.

I will try to reproduce exactly the same error than with my app (`Could not connect to the server. (NSURLErrorDomain -1004)`) but I suspect the connection is closed too early, before the body is sent or in my case, before the request is initiated. Maybe it is attached to the renderer process and killed at the same time.

On top of that, the event "window-all-closed" is not fired when the renderer process crash. I think it should be.

**Comment by zcbenz** [comment] 2015-08-31 01:34
> On top of that, the event "window-all-closed" is not fired when the renderer process crash. I think it should be.

`window-all-closed` is fired when windows are all closed, while when a renderer process crashed the window is left open so you can choose to close it or reload it.

**Comment by nylki** [comment] 2015-09-02 10:24
I get the same error:
```
http_transport_mac.mm(186)] Could not connect to the server. (NSURLErrorDomain -1004)
```
on electron 0.31 (OS X 10.10.4), when `var socket = require('socket.io-client')('http://localhost:3000')`
removing the dependency on *socket.io* the electron app starts fine.
On 0.30 the problem does not exist.

**Comment by tommoor** [comment] 2015-10-25 17:50
I don't know if this is relevant but on our app we found that the submitUrl *must* include a path, `https://crashes.mydomain.com/crash-report` would work, but `https://crashes.mydomain.com` would not.

**Comment by felicienfrancois** [comment] 2015-10-25 19:47
@tommoor I don't think this is related because I got the issue with an url with a path

**Comment by zcbenz** [comment] 2015-11-30 08:21
From v0.33.3 there was an update of the Squirrel library in Electron, can you try if the Electron versions after that work?

**Comment by felicienfrancois** [comment] 2015-11-30 14:25
@zcbenz I remade the https://github.com/atom/electron/issues/2609#issuecomment-135965787 test with more versions and:
- I still get the `[0829/110129:ERROR:http_transport_mac.mm(186)] cannot parse response (NSURLErrorDomain -1017)` error on 0.33.X (tested up to 0.33.9) but no longer on latest 0.35.2
- I still get empty post to my submitUrl, with both 0.33.X and latest 0.35.2. It worked with 0.26.X

**Comment by felicienfrancois** [comment] 2015-11-30 14:27
unfortunatelly as my setup changed a lot, I cannot replay my original test easily (the one which triggered the 1004 error)

**Comment by zcbenz** [comment] 2015-12-11 08:48
Since 0.35.3 Electron is linked back to OS X 10.10 SDK, does it fix the problem?

**Comment by felicienfrancois** [comment] 2015-12-11 10:12
@zcbenz it does not fixes the [empty POST issue](https://github.com/atom/electron/issues/2609#issuecomment-160644258)
But the NSURLErrorDomain error no longer occurs since 0.35.X (so may not be related to OSX SDK version)

The strange thing is that it works with the local server (I get the json data printed out to console with your test app). But changing it to my remote server, I get empty POST while it works with old releases (0.26.X).

In the tests I made, electron and the renderer are untouched on crash (left opened) so the crash report submit should not be interrupted 
My submitURL looks like https://mydomain.com/php/crash-report.php with a valid SSL certificate, the server supports HTTP/2 & SPDY, the POST is printed out server side in php.
Here the logs comparison:
- v0.26.1
```
"POST /php/crash-report.php HTTP/1.1" 200 20B 2876335μs "-" "crash_report_sender/1.0 CFNetwork/760.1.2 Darwin/15.0.0 (x86_64)"
[SPDY31-1] Crash report: {"process_type":"renderer","_companyName":"GitHub, Inc","prod":"Electron","_version":"","ver":"0.26.1","ptime":"0","_productName":"crash-reporter-test","platform":"darwin","guid":"7f84aa8c2b9b95bd4c20077"}
```
- v0.35.2, v0.35.3, v0.35.4, v0.36.0 (same output)
```
"POST /php/crash-report.php HTTP/1.1" 200 20B 40135μs "-" "crashpad_handler (unknown version) CFNetwork/760.1.2 Darwin/15.0.0 (x86_64)"
[SPDY31-1] Empty POST: $_GET=[] $_POST=[] $_FILES=[]
```

**Comment by zcbenz** [comment] 2016-05-06 10:50
I'm closing this since this is the only report on this issue, and we are not able to do further investigations because of lack of a way to reproduce it.

**Closed by zcbenz** 2016-05-06 10:50 UTC
Labels: bug, machine-dependent, osx
