### ISSUE TITLE
Appindicator as replecement for legacy tray icon on GNOME

### ISSUE THREAD

**Issue by mhalano** [electron/electron#10427] opened 2017-09-02 00:42 UTC
GNOME 3.26 will deprecate the legacy tray icons. Electron apps (I can mention Skype for Linux and Blink1Control2) shows, on Ubuntu 17.10, just the legacy tray icon instead the more modern app indicator icon (which is supported even on GNOME). The idea here is deprecate GNOME legacy tray icons which should promote app indicator as preferred option to exhibit sytray icons. The next logical step is implement other protocols to show systray icons.

**Comment by jhasse** [comment] 2017-09-15 10:57
See https://github.com/snapcrafters/discord/issues/4

**Comment by jhasse** [comment] 2017-09-15 11:01
This is somehow fixed by https://github.com/electron/electron/commit/dc43dc2a1316d5f96e1c3a9cf6079c4150214f66, but only on Ubuntu! Instead of checking `XDG_CURRENT_DESKTOP` it would be more reliable to see if the DBus interface `org.kde.StatusNotifierWatcher` is available, see https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/74.

**Comment by simonvanderveldt** [comment] 2018-01-27 11:00
Any chance this can be fixed by checking the above mentioned D-Bus interface? That would be a lot more reliable and also prevent issues on GNOME 3.26 (and later) installs that are using https://github.com/Ubuntu/gnome-shell-extension-appindicator (i.e. all new Ubuntu installs)

**Comment by mhalano** [comment] 2018-02-02 19:38
FYI: The new Skype snap has a app indicator.

**Comment by ckerr** [comment] 2018-02-02 21:16
If @simonvanderveldt's suggestion of using the DBus interface would make Electron's appindicators work on Ubuntu and non-Ubuntu systems alike, and if a volunteer would like to submit a PR for that, I'd be very inclined to merge it quickly

**Comment by TingPing** [comment] 2018-02-02 23:36
I don't even see where `XDG_CURRENT_DESKTOP` is read in the repo so perhaps that is in Chromium? Actually looking at Chromium I see that env var returns `DESKTOP_ENVIRONMENT_UNITY` but I can't find that used anywhere related to the tray either.

**Comment by jhasse** [comment] 2018-02-28 10:43
> I don't even see where XDG_CURRENT_DESKTOP is read in the repo

Here: https://github.com/electron/electron/blob/master/lib/browser/init.js#L166

**Comment by TingPing** [comment] 2018-02-28 14:09
@jhasse Yea I saw that but it doesn't actually *do* anything, somewhere deeper is what reads it.

**Comment by TingPing** [comment] 2018-02-28 14:17
Anyway I might as well document what should be done if anybody else gets around to it:

1. Add some API to expose to applications if the tray is or isn't supported
   - NOTE: That in real usage the tray can come or go at any time and applications need to dynamically handle this
1. Check if bus name `org.kde.StatusNotifierWatcher` is owned
2. If owned and:
   - appindicator is installed, use that
   - appindicator is missing, assume the user wanted to use that and disable tray
      - NOTE: You could fallback to xorg but its easier to assume their desktop has the service for a reason
3. If unowned: Check for the X11 tray service: https://wiki.gnome.org/Initiatives/StatusIconMigration/Guidelines/TraySupportCheck

**Comment by jhasse** [comment] 2018-02-28 14:26
Why not always use libappindicator as it already implements the X11 legacy tray fallback?

**Comment by TingPing** [comment] 2018-02-28 14:29
> Why not always use libappindicator as it already implements the X11 legacy tray fallback?

- AppIndicator is optional, thus a fallback path must be handled anyway
- AppIndicator's internal fallback has weird quirks like using middle-click for actions instead of left click
- AppIndicator is actually a terrible unmaintained library and it doesn't properly check that the x11 tray even exists, so we would actually be back to square one where applications don't have a tray but think they do. This cannot even be added without a new API like I suggest to tell the application *"Hey, there is no tray and nothing we can do about it"*.

**Comment by jhasse** [comment] 2018-02-28 21:40
> AppIndicator is optional, thus a fallback path must be handled anyway

I'm suggesting to make it mandatory for tray support. So if it isn't present, assume that there's no tray.

> AppIndicator's internal fallback has weird quirks like using middle-click for actions instead of left click

What do you mean by "actions"?

> AppIndicator is actually a terrible unmaintained library and it doesn't properly check that the x11 tray even exists, so we would actually be back to square one where applications don't have a tray but think they do.

AppIndicator is open-source, so instead of reinventing the wheel in every application, this feature can be submitted as a patch to libappindicator.

>  This cannot even be added without a new API like I suggest to tell the application "Hey, there is no tray and nothing we can do about it".

Couldn't `app_indicator_new` return `NULL` in this case? Or maybe [one of the reserved fields](https://bazaar.launchpad.net/~indicator-applet-developers/libappindicator/trunk.16.10/view/head:/src/app-indicator.h#L226) can be used to stay binary-compatible.

**Comment by TingPing** [comment] 2018-02-28 23:39
> What do you mean by "actions"?

`app_indicator_set_secondary_activate_target`

> AppIndicator is open-source, so instead of reinventing the wheel in every application, this feature can be submitted as a patch to libappindicator.

You missed the point that it sees no active development. The stack doesn't even actually build on other distros and hasn't for many many years.

Now could it become maintained? Sure. Am I volunteering? No.

> Couldn't app_indicator_new return NULL in this case? 

No that doesn't make sense as I mentioned tray support can come and go. Plus constructors failing is an anti-pattern in GObject.

> Or maybe one of the reserved fields can be used to stay binary-compatible.

Yes but all software using it is still broken until they update their API usage.

**Comment by jhasse** [comment] 2018-03-01 13:39
> `app_indicator_set_secondary_activate_target`

I think it's debatable if this is intended or a bug. Anyway: Should be an easy fix.

> You missed the point that it sees no active development.

Does this mean they ignore patches / PRs?

> Yes but all software using it is still broken until they update their API usage

The same is true if this was fixed in Electron/Chromium with the difference, that Electron is a static dependency and therefore the fix can't be easily backported.

**Comment by TingPing** [comment] 2018-03-01 15:19
> I think it's debatable if this is intended or a bug

It is absolutely intended, AppIndicator wants the fallback to behave like an indiciator in Unity. Problem is that isn't behavior that makes sense for users not on Unity (which is soon to be very few).

> Does this mean they ignore patches / PRs?

The bug tracker on launchpad is disabled, no third party contributions in years, so probably?

> I guess most developers won't care about such a corner case, which is exactly why you would want to do it right at one place, i.e. a dynamically linked library like libappindiactor.

I don't think that makes it ok to make a technically wrong API. If we are in a position to make an API and correct past mistakes lets not half ass it?

**Comment by jhasse** [comment] 2018-03-01 16:55
> Unity

GNOME Shell and macOS behave the same way (left click always opens the menu).

> The bug tracker on launchpad is disabled, no third party contributions in years, so probably?

Just remembered that there already was a discussion about this here: https://github.com/Ubuntu/gnome-shell-extension-appindicator/issues/74#issuecomment-333525826
I've bumped the thread, let's hope Canonical has enough dev power to maintain libappindicator or give it to someone who has.

> If we are in a position to make an API and correct past mistakes lets not half ass it?

In general I think it's better to extend on existing stuff, not rewrite from scratch. Especially since the reserved fields *are* there. Writing a new lib with a new .so name won't help all the existing binaries out there.

**Comment by TingPing** [comment] 2018-03-02 17:51
> GNOME Shell and macOS behave the same way (left click always opens the menu).

GNOME-Shell < 3.26 used left click for actions on XEmbed trays. Since it no longer has any tray though...

> In general I think it's better to extend on existing stuff, not rewrite from scratch. Especially since the reserved fields are there. Writing a new lib with a new .so name won't help all the existing binaries out there.

My proposal is an API addition to Electron, AppIndicator can stay the implementation and be improved externally but we have to start with a solid API in Electron or its all a moot point.

**Comment by jhasse** [comment] 2018-03-07 17:31
> GNOME-Shell < 3.26 used left click for actions on XEmbed trays. Since it no longer has any tray though...

XEmbed was always a second class citizen, especially when it was on the bottom left. I was talking about indicators via extensions (e.g. https://extensions.gnome.org/extension/841/freon/) or the appindicator extension.

> My proposal is an API addition to Electron, AppIndicator can stay the implementation and be improved externally but we have to start with a solid API in Electron or its all a moot point.

There's an API already: [`Tray`](https://github.com/electron/electron/blob/master/docs/api/tray.md)

**Comment by TingPing** [comment] 2018-03-07 20:52
@jhasse This entire conversation is about the fallback XEmbed support of AppIndicator though. So on older GNOME, Mate, XFCE, LXDE, etc its behavior is confusing.

> There's an API already: Tray

Which doesn't accurately represent how trays work. It needs new methods to indicate when a tray appears and disappears and applications need to be modified to handle that.

**Comment by jhasse** [comment] 2018-03-08 10:26
> This entire conversation is about the fallback XEmbed support of AppIndicator though. So on older GNOME, Mate, XFCE, LXDE, etc its behavior is confusing.

Right, I see your point now :)

> It needs new methods to indicate when a tray appears and disappears and applications need to be modified to handle that.

IMHO the tray should never appear/disappear. Anyway: This is offtopic and should be discussed in a different issue.

**Comment by TingPing** [comment] 2018-03-08 20:30
> IMHO the tray should never appear/disappear.

Opinions have no effect on the reality of how technology works =)

**Comment by jhasse** [comment] 2018-03-09 08:48
Technology works the way it does, because of the opinions of its developers.

**Comment by TingPing** [comment] 2018-03-09 21:18
> Technology works the way it does, because of the opinions of its developers.

This is certainly going off topic but no. X11 and DBus allow clients to own names, this all happens asynchronously out of process and other clients have no knowledge or control over this. Thus just by the fact of really how all IPC works other clients must asynchronously handle that ownership appearing and disappearing.

The same situation happens on Windows btw, if you kill `explorer.exe` applications have to handle that event or they will be in a broken state. The difference there is applications can safely assume it always comes back.

**Comment by TingPing** [comment] 2018-03-12 19:44
> Or else?

Or you get what you already have which is many tray using apps are broken on GNOME because it hides its window expecting users to have access to a non-existing tray.

**Comment by jhasse** [comment] 2018-03-12 19:58
On (vanilla) GNOME the tray is always non-existing, but you were talking about appearing and disappearing.

**Comment by TingPing** [comment] 2018-03-12 21:27
> On (vanilla) GNOME the tray is always non-existing, but you were talking about appearing and disappearing.

I get your point but don't believe its valid. If something can go wrong it will. AppIndicator for example does handle the DBus service coming and going as it does whenever the shell crashes, you manually enable/disable/update the extension, etc. The same logic just needs to be applied to the X11 tray.

**Comment by jhasse** [comment] 2018-03-12 22:52
Yes, but what does this have to do with the API for the *application*?

**Comment by TingPing** [comment] 2018-03-13 00:57
How many times do I have to repeat the same thing. If the tray isn't there and applications assume so the entire situation is broken.

**Comment by jhasse** [comment] 2018-03-13 08:35
Because you're mixing up two situations:

1. the tray isn't there
2. the tray might disappear and appear

1 is easily fixable by an addition to the API which returns a boolean. 2 on the other hand is rather hard to fix: It needs an event / callback and applications have to think of quite a few situations: Do I need to reshow my window when the tray disappears? Or should I quit / stay in the background? The tray is used to show a progressbar, I'd might need to change my GUI to show this. If the tray appears, should I show a tray icon? And move my progressbar to the tray like I would have done if the tray was there in the first place? What about the menu items that are only accessible through the tray menu?

In situation 1, the application developer only has to think about those questions once, which actually might be a lot easier (because his GUI can be changed easily during its construction).

Situation 2 is even less common than situation 1 (which is mostly vanilla GNOME), so in my *opinion* it isn't worth it to implement an API for this. I guess most developers will even ignore 1, because most users are using Windows, macOS, Ubuntu, which all have a tray.

**Comment by phw** [comment] 2018-03-13 08:49
@TingPing If I understand you correctly app indicator would already handle the tray appearing / dissapearing, so if Electron apps would support the AppIndicator interface that would be already handled?

@jhasse Above you said "IMHO the tray should never appear/disappear" and that leads you to the assumption that it would be best to ignore that the tray *will* appear / dissapear. It's not only Gnome, also other environments implement the tray as e.g. an applet which can be added or removed by the user.

**Comment by TingPing** [comment] 2018-03-14 00:16
> @TingPing If I understand you correctly app indicator would already handle the tray appearing / dissapearing, so if Electron apps would support the AppIndicator interface that would be already handled?

Not quite. AppIndicator does not in any way properly handle X11 trays existing or not existing

**Comment by MrObvious** [comment] 2018-04-09 16:48
Why not just forget trying to find a workaround for now, just accept that if the tray won't be there, put the app in the background where you can only get to it by relaunching it, or if a notification comes from the app, use libnotify, then click the notification to open that app? 

It sucks, but it's where Gnome is forcing things.

**Comment by TingPing** [comment] 2018-04-10 01:48
@MrObvious Just accepting the user can lose a window is bad engineering when there are clear and correct solutions to it. It isn't a GNOME problem it can happen anywhere, trays are optional, period.

**Comment by KeitIG** [comment] 2018-04-10 07:38
I agree with @TingPing even if I would have preferred a better solution. Is there any way to detect if a Tray was not created so we can implement a fallback in our apps?

**Comment by TingPing** [comment] 2018-04-10 09:17
@KeitIG This issue is filled with discussion on it but no there needs to be an API addition for that.

**Comment by MrObvious** [comment] 2018-04-10 14:33
@TingPing I see what you're saying. I just hope this gets fixed soon as I have to use ugly workarounds for now.

**Comment by luisfpg** [comment] 2018-05-02 15:47
Even if the current solution is a hack, it could still benefit other GNOME users out there to just add `GNOME` to the whitelist of `XDG_CURRENT_DESKTOP` choices to enable the indicator support.
Here is the current source code: https://github.com/electron/electron/blob/a0ebde018100153f635bc6eeb6b72f90d1704ea3/lib/browser/init.js#L166

Anyway, TopIconsPlus is dead, and can no longer be installed on GNOME 3.28+.
Chances are GNOME 3.28+ users either have no extension installed or have the [indicator support extension](https://extensions.gnome.org/extension/615/appindicator-support/) installed. So not only those running the `ubuntu:GNOME` or `pop:GNOME` variants would benefit.
In the worst case, if supporting old GNOME 3 versions is a concern, indicators can be enabled only for 3.28+ (the version can be checked on `/usr/share/gnome/gnome-version.xml`).

**Comment by TingPing** [comment] 2018-05-02 16:36
> indicators can be enabled only for 3.28+ (the version can be checked on /usr/share/gnome/gnome-version.xml).

I tried to explain through-out this issue that checking versions is a bad solution. That is also entirely broken in a sandbox like Snap or Flatpak.

**Comment by MrObvious** [comment] 2018-05-02 17:04
What about if the window doesn’t have a tray icon, it just minimizes? Simple, elegant, and quick to push out?

**Comment by IvanMalison** [comment] 2018-05-02 18:38
> I tried to explain through-out this issue that checking versions is a bad solution.

But its still better than doing notihg, which seems to be the alternative... is the point that @luisfpg and others are making.

**Comment by IvanMalison** [comment] 2018-05-11 00:37
It seems like chrome might get a better SNI/appindicator implementation soon.
see https://bugs.chromium.org/p/chromium/issues/detail?id=419673

Not sure how relevant this is, but I did notice that even when setting 
`XDG_CURRENT_DESKTOP=Unity` for electron apps, they seem to use the same horribly out of spec implementation as chrome does, so it seems like there is a dependency there.

**Comment by TingPing** [comment] 2018-05-11 00:44
@IvanMalison Based on what I read all they have done is *"Always use libappindicator if available"* which I suppose you could call better for this problem but still broken.

**Comment by IvanMalison** [comment] 2018-05-11 00:48
@TingPing I suppose what I wanted to point out is only tangentially related to this problem. But basically chrome's SNI implementation currently simply does not follow the spec at all. In my SNI host implementation I have to add an entirely new special case just to handle chrome icons here:

https://github.com/IvanMalison/gtk-sni-tray/blob/8a248da47a5ae39fd49b205c3a607f9b6dbe9c18/src/StatusNotifier/Tray.hs#L75

I would be happy to try to fix this issue if its not too hard. Is there already a dbus client/library available or would I need to deal with figuring out how to add that?

**Comment by TingPing** [comment] 2018-05-11 00:54
Here is one implementation I know of: https://github.com/jjk-jacky/statusnotifier

It is certainly more strict than libappindicator but it also doesn't automatically fallback to XEmbed.

**Comment by IvanMalison** [comment] 2018-05-11 01:17
> It is certainly more strict than libappindicator but it also doesn't automatically fallback to XEmbed.

@TingPing which is why I asked about a dbus client. In order to properly detect things, we need to make certain dbus calls ourselves.

**Comment by damianobarbati** [comment] 2018-08-03 12:13
So what's the status of tray on Linux? I can't see anything, I also installed bot libgconf* and libappindicator1* :(

**Comment by TingPing** [comment] 2018-08-05 14:04
@damianobarbati That isn't a complete question, it depends upon what shell/distro you use.

**Comment by lukasbash** [comment] 2018-09-12 16:32
I am using manjaro with a 4.17 kernel.
My DE is gnome 3.27.

What is the status on this?

Thank you guys!

**Comment by tapir** [comment] 2018-11-08 12:30
Please make electron work with https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by enzingerm** [comment] 2019-04-20 13:28
@tapir I got it (precisely the tray icon of the Electron-based Riot messenger) to work again together with the appindicator support extension by installing `libappindicator-sharp` and `libappindicator-gtk3` (Gnome 3.32, Arch)

**Comment by MattSturgeon** [comment] 2019-04-20 14:46
I can confirm I've had the [appindicator extension](/ubuntu/gnome-shell-extension-appindicator) working fine with electron apps (Discord in my case) for a while, just checked and I do also have `libappindicator-gtk3` installed which provides the following files:

```
/usr/include/libappindicator3-0.1/libappindicator/app-indicator-enum-types.h
/usr/include/libappindicator3-0.1/libappindicator/app-indicator.h
/usr/lib/girepository-1.0/AppIndicator3-0.1.typelib
/usr/lib/libappindicator3.so
/usr/lib/libappindicator3.so.1
/usr/lib/libappindicator3.so.1.0.0
/usr/lib/pkgconfig/appindicator3-0.1.pc
/usr/share/gir-1.0/AppIndicator3-0.1.gir
/usr/share/vala/vapi/appindicator3-0.1.deps
/usr/share/vala/vapi/appindicator3-0.1.vapi
```

**Comment by DuncanCasteleyn** [comment] 2019-04-22 01:20
@MattSturgeon I'm on manjaro gnome, installing libappindicator-gtk3 made discord appear in the tray icon. Though, I don't think this should be seen as the permanent solution.

**Comment by MattSturgeon** [comment] 2019-04-25 19:39
Well, if you have no system tray (as is the case by default in gnome) you can't appear there.
If you have an appindicater extension, and an appindicator library (in this case the gtk one) then you can tell the gtk lib to show us in the indicator tray. (This works currently in electron).

The fact that you had to install the library yourself isn't _really_ electrons problem - that's the distro and/or user's responsibility. Presumably _no_ gtk apps were able to show appindicators until you installed `libappindicator-gtk3`.

What "permanent solution" do you propose?

**Comment by DuncanCasteleyn** [comment] 2019-04-26 15:10
One that supports the app indicator that is installed by default on both Manjaro and Ubuntu https://github.com/ubuntu/gnome-shell-extension-appindicator

**Comment by MattSturgeon** [comment] 2019-04-26 15:24
That appindicator extension does work, since all it does is _show_ indicators on the underlying appindicator system.

The libappindicator-gtk3 library has nothing to do with _showing_ indicators, instead it is what is used by gtk3 apps to control the indicators themselves.

To clarify, electron does work with [gnome-shell-extension-appindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator) and any other appindicator frontend. But electron can't _create_ an indicator without libappindicator-gtk3.

**Comment by vladimiry** [comment] 2019-12-14 11:57
By the way, the tray icon displaying mechanisms on Linux got changed since Electron version 8, see #21445.

**Comment by vladimiry** [comment] 2019-12-19 10:27
Besides since Electron version 8 `libappindicator-gtk3`/`libappindicator3-1` seems to be not needed anymore (worked for me in differens systems, Xfce/KDE/Gnome).

**Comment by mhalano** [comment] 2021-08-25 00:10
Can I declare this issue solved and close it? I would close myself, but I saw there was a great discussion about it.

**Comment by zcbenz** [comment] 2022-11-08 11:16
Let's close this since it is solved. People can still find the discussion since it is closed instead of deleted.

**Closed by zcbenz** 2022-11-08 11:16 UTC
Labels: enhancement :sparkles:
