### ISSUE TITLE
print job is stuck at Spooling when using webContents.print()

### ISSUE THREAD

**Issue by SmellydogCoding** [electron/electron#22695] opened 2020-03-15 16:34 UTC
### Issue Details

* **Electron Version:**
  * 9.0.0-beta-7
* **Operating System:**
  * Windows 10 Version 2004 Build 19041.153
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
Using webContents.print() will invoke the Windows print dialog which will print the contents of the BrowserWindow.

### Actual Behavior
The Windows dialog box does appear, but after clicking Print the print job is stuck at Spooling.
screenshot: [https://1drv.ms/u/s!AuHiR7uxGtQWgfxRefLP6MkcrwsQmQ?e=ZrQwP1](https://1drv.ms/u/s!AuHiR7uxGtQWgfxRefLP6MkcrwsQmQ?e=ZrQwP1)

### Code
```
ipcMain.on('print', (event, file) => {
    // create new window
    let printWindow = new BrowserWindow({ width: 800, height: 600, show: false })
    // load the file (URL in development, file path in production).
    printWindow.loadURL(file)
    // make sure the file is loaded and the window is ready before continuing
    let p1 = new Promise((resolve) => printWindow.webContents.on('did-finish-load', resolve))
    let p2 = new Promise((resolve) => printWindow.on('ready-to-show', resolve))
    Promise.all([p1, p2])
      .then(() => {
        console.log('resolved') // did both promises reslove?
        printWindow.webContents.print({ printBackground: true }, (success, error) => {
          console.log('print function invoked') // was the print function called?
          if (success) {
            console.log('success')
            printWindow = null
          } else if (error) {
            console.log(error)
          } else { console.log('unknown') }
        })
      })
  })
```

### Additional Information
When this runs 'resolved' is printed to the console but 'print function invoked' is not.  I can't tell if webContents.print() is firing at all since nothing in the callback seems to run.

**Comment by t57ser** [comment] 2020-03-17 12:20
I have experienced this too, it seems to happen if there is an iframe with a cross-domain src on the page. Does your page include an iframe too?

**Comment by SmellydogCoding** [comment] 2020-03-17 18:41
The print window is opening the pdf using chromium's built in pdf viewer.  It doesn't use an iframe but it does use an embed:
```
<embed name="E9D59870AA124573B4DD3044D575490A" style="position:absolute; left: 0; top: 0;"
 width="100%" height="100%" src="about:blank" type="application/pdf"
 internalid="E9D59870AA124573B4DD3044D575490A">
```
The source is in the same domain:
```
http://localhost:8080/7a8cfb16a78903084dc0ba5003b4e6cd.pdf
```
In production the file would be on the local machine

**Comment by markleutloff** [comment] 2020-11-27 06:40
This behaves like https://github.com/electron/electron/issues/20634.

Issuing a print job through either webContents.print, webContents.printToPdf or window.print when the page contains frames (the pdf viewer extension uses this too) will in the current versions of Electron never finish the proint job.

Tested with Electron (Windows 10 x64):
11.0.3
12.0.0-beta.3
12.0.0-beta.4

I am not sure why this issue is not of higher priority, as printing is a use case often performed. Currently printing any page with a frame or just a pdf will not finish the printing.

**Comment by mikkorantalainen** [comment] 2020-12-04 08:55
If the document to print contains Youtube iframe embed, is there any known workaround to be able to get the `printToPDF()` to not hang? I would want something else but setting display:none to all <iframe> elements.

**Comment by codebytere** [comment] 2021-02-09 22:12
Closing in favor of https://github.com/electron/electron/issues/27605

**Closed by codebytere** 2021-02-09 22:12 UTC
Labels: 9-x-y, bug :beetle:, component/printing, platform/windows

**Comment by ashishgehlot** [comment] 2022-05-30 10:58
I am still facing this issue with Electron 18.3.1. 
Attaching minimal reproduction repo.

https://github.com/ashishgehlot/Electron_PrintStuck.git

**Comment by MarcoGiorgi** [comment] 2022-07-19 18:00
I confirm the bug is still there. printToPDF using webContents stuck at pooling.
```
  let win: any = new BrowserWindow({ show: false });

  win.loadURL(args.url);

  win.webContents.once('did-finish-load', () => {
    win.webContents
      .printToPDF({ printBackground: true, silent: true })
      .then((data: any) => {
        const buf = Buffer.from(data).toString('base64');
        const url = `data:application/pdf;base64,${buf}`;

        // @ts-ignore
        win.webContents.on('ready-to-show', () => {
          if (process.env.NODE_ENV === 'development') win.show();
          win.webContents.print(
            { printBackground: true, silent: true },
            (success, failureReason) => {
              console.log('Print Initiated in Main...');
              if (!success) console.log('[print][failed]', failureReason);
            }
          );
        });

        // @ts-ignore
        win.webContents.on('closed', () => {
          win = null;
        });

        return win.loadURL(url);
      })
      .catch((error) => {
        console.log(error);
      });
  });
```

**Comment by sassouiabd** [comment] 2022-08-30 03:53
Hello,
I am also still facing  this issue when trying to print  usibf webContents.print(.., callback).
The print job got stuck in spooling status and the callback  inside  the print methods is never called. 
Has any found a solution  or workaround  to this issue?

**Comment by priyeshshah11** [comment] 2023-01-06 05:16
> Closing in favor of #27605

@codebytere I don't think this issue is the same as the one referenced in your comment.
Either way this bug still seems to exist (at least on windows), does anyone know the root cause of this? Or any solutions? 

Thus, this issue should be re-opened and investigated further.
