### ISSUE TITLE
Playing and removing HTML5 videos leaks memory

### ISSUE THREAD

**Issue by sapandiwakar** [electron/electron#18277] opened 2019-05-13 05:19 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `5.0.1`
* **Operating System:**
  * Ubuntu 16.04
* **Last Known Working Electron version:**:
  * None

### Expected Behavior
Playing a video causes the resident size to increase.  When playing multiple videos one after the other after removing the previous one, the resident size should peak at a particular point and then stop increasing. 

### Actual Behavior
The resident size keeps increasing and in a sufficiently memory constrained environment, the OS kills the app eventually. This ins't an app specific memory leak as the heap size remains stable while the resident size keeps increasing.

### To Reproduce
[electron_mem_leak.zip](https://github.com/electron/electron/files/3171211/electron_mem_leak.zip)

```sh
$ yarn
$ yarn electron .
```

### Additional Information

Here is the log of `process.memoryUsage()` (converted to MB) over a few minutes. 

[1557722682347.log](https://github.com/electron/electron/files/3171214/-1557722682347.log)

**Comment by MarshallOfSound** [comment] 2019-05-13 23:37
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by MarshallOfSound** [comment] 2019-05-13 23:39
I can't reproduce this on macOS, the GC appears to be working fine.  Deferring to someone else to try repro on linux / win

**Comment by sapandiwakar** [comment] 2019-05-14 06:04
Yes, it doesn't happen on macOS, only on Linux. On a side note, is there a way to limit electron from acquiring too much resident memory as a workaround while this is being looked at?

**Comment by electron-triage** [comment] 2020-02-19 19:26
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:15
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:15 UTC
Labels: 5-0-x, blocked/need-info ❌, bug :beetle:, platform/linux
