### ISSUE TITLE
[Bug]: TypeError: fs.existsSync is not a function

### ISSUE THREAD

**Issue by shankybhor92** [electron/electron#29750] opened 2021-06-17 12:57 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

13.1.2

### Expected Behavior

I am building an application with react and electron.
I try to call a electron function from react.
Something like - 
const { remote } = require('electron');
const mainProcess = remote.require('./electron-starter.js');
it should work as per the scenario.

 

### Actual Behavior

×
TypeError: fs.existsSync is not a function
getElectronPath
C:/Users/pbhor/Downloads/react/node_modules/electron/index.js:7
   4 | var pathFile = path.join(__dirname, 'path.txt')
   5 | 
   6 | function getElectronPath () {
>  7 |   if (fs.existsSync(pathFile)) {
   8 |     var executablePath = fs.readFileSync(pathFile, 'utf-8')
   9 |     if (process.env.ELECTRON_OVERRIDE_DIST_PATH) {
  10 |       return path.join(process.env.ELECTRON_OVERRIDE_DIST_PATH, executablePath)
View compiled
(anonymous function)
C:/Users/pbhor/Downloads/react/node_modules/electron/index.js:18
  15 |   }
  16 | }
  17 | 
> 18 | module.exports = getElectronPath()
  19 | 
View compiled
./node_modules/electron/index.js
http://localhost:3000/static/js/vendors~main.chunk.js:494:30
__webpack_require__
C:/Users/pbhor/Downloads/react/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
C:/Users/pbhor/Downloads/react/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module.<anonymous>
C:/Users/pbhor/Downloads/react/src/components/Home.js:4
  1 | // import { testCalling } from "../Common";
  2 | // import { TRUE } from "node-sass";
  3 | // const window: {require:''};
> 4 | const { remote } = require('electron');
  5 | const mainProcess = remote.require('./electron-starter.js');
  6 | function Home() {
  7 |   console.log(mainProcess.testCalling());
View compiled
Module../src/components/Home.js
http://localhost:3000/static/js/main.chunk.js:392:30
__webpack_require__
C:/Users/pbhor/Downloads/react/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
C:/Users/pbhor/Downloads/react/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
▶ 2 stack frames were collapsed.
__webpack_require__
C:/Users/pbhor/Downloads/react/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
C:/Users/pbhor/Downloads/react/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
▶ 2 stack frames were collapsed.
__webpack_require__
C:/Users/pbhor/Downloads/react/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
C:/Users/pbhor/Downloads/react/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
http://localhost:3000/static/js/main.chunk.js:729:18
__webpack_require__
C:/Users/pbhor/Downloads/react/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
checkDeferredModules
C:/Users/pbhor/Downloads/react/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
C:/Users/pbhor/Downloads/react/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:59
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by codebytere** [comment] 2021-06-17 15:54
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by qkrooz** [comment] 2021-06-19 18:35
You need to add the following configuration to your BrowserWindow.

  webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true,
      webSecurity: false,
    },

**Comment by shankybhor92** [comment] 2021-06-21 10:06
> You need to add the following configuration to your BrowserWindow.
> 
> webPreferences: {
> nodeIntegration: true,
> contextIsolation: false,
> enableRemoteModule: true,
> webSecurity: false,
> },

**Comment by shankybhor92** [comment] 2021-06-21 10:09
> Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by nornagon** [comment] 2021-06-21 17:00
@shankybhor92 thanks for the gist, but unfortunately it appears to be incomplete—for instance, it requires files that are not included in the gist. In order to debug this we require a complete testcase.

**Comment by shankybhor92** [comment] 2021-06-21 17:11
Should I create a git repository?

**Comment by nornagon** [comment] 2021-06-21 17:12
Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Ideally, you should make a standalone testcase with only the code necessary to reproduce the issue. For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by shankybhor92** [comment] 2021-06-22 07:59
https://gist.github.com/1d6a7b8f2683137e970640273b559930
New gist is generated with Electron Fiddle.

**Comment by nornagon** [comment] 2021-06-22 18:18
The `remote` module is no longer supported in Electron. See https://github.com/electron/remote for its replacement.

**Closed by nornagon** 2021-06-22 18:18 UTC
Labels: blocked/need-repro, bug :beetle:
