### ISSUE TITLE
[Bug]: await shell.openExternal("https://www.google.com/") not return after the url has been open

### ISSUE THREAD

**Issue by tangjfn** [electron/electron#39037] opened 2023-07-10 10:48 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

macOS

### Operating System Version

13.4.1

### What arch are you using?

x64

### Last Known Working Electron version

24.6.2

### Expected Behavior

await shell.openExternal("https://www.google.com/");

console.log("ok");

### Actual Behavior

await shell.openExternal("https://www.google.com/");

// not here
console.log("ok");

**Comment by tangjfn** [comment] 2023-07-10 14:14
[files.zip](https://github.com/electron/electron/files/12002890/files.zip)

extract files.zip to a directory.
cd /path/to/the/directory
electron main.js

**Comment by marcoancona** [comment] 2023-10-07 16:44
I confirm the issue, which started after the upgrade from Electron 24 to 26.3.0

**Comment by Arthur-Zeng** [comment] 2023-10-12 09:41
Also experienced this issue, looks like `shell.openExternal` can invoke the system's default browser to open the given URL, but it won't return. Moving it to the main process and using IPC calls worked for me.

**Comment by marcoancona** [comment] 2023-10-12 12:09
While in most cases you can live with it by removing the `await`, if you need to capture exceptions this is problematic.

**Comment by zawata** [comment] 2024-01-11 19:09
After running into this bug and working around it by just not awaiting the promise, we got a followup bug report caused by #38540 where it was suggested that you can workaround that by calling `shell.showItemInFolder` from the main process instead of the render process.

I can confirm that the same workaround applies here as well; calling `shell.openExternal` from the main process via IPC does not cause it to hang.

@codebytere determined the other issue was also introduced by the same chromium bump that was suggested above here: https://github.com/electron/electron/commit/3fa03977c7f5be9442b356ae39dd310276314dce

**Comment by Imperat** [comment] 2024-02-12 10:08
I just added some `printf` statements to debug:

```objective-c
void OpenExternal(const GURL& url,
                  const OpenExternalOptions& options,
                  OpenCallback callback) {
  DCHECK([NSThread isMainThread]);
  NSURL* ns_url = net::NSURLWithGURL(url);
  if (!ns_url) {
    printf("test - 1\n");
    std::move(callback).Run("Invalid URL");
    return;
  }

  bool activate = options.activate;
  __block OpenCallback c = std::move(callback);
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0),
                 ^{
                   printf("test - 2\n");
                   __block std::string error = OpenURL(ns_url, activate);
                   printf("test - 3\n");
                   dispatch_async(dispatch_get_main_queue(), ^{
                     printf("test - 4\n");
                     std::move(c).Run(error);
                   });
                 });
}
```

and I have got:

```
test - 2
test - 3
```

Not sure what should be the proper fix there 🤔

**Closed** 2024-05-08 14:00 UTC
Labels: platform/macOS, bug :beetle:, component/shell
