### ISSUE TITLE
[Bug]: goBack/goForward can lead to -3 ERR_ABORTED errors, because the previous navigation isn't awaited

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#36253] opened 2022-11-04 16:02 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I expect that I can call `goBack()` or `goForward()` in sequence without error

### Actual Behavior

Multiple calls in a row causes issues, because I believe [this code](https://github.com/electron/electron/blob/c625b36e6a3ef280aba3abf5c6ea8db5f139d180/lib/browser/api/web-contents.ts#L459) is triggered, and we get ERR_ABORTED

### Testcase Gist URL

https://gist.github.com/9f70946995df89c69fff7eb528e1c3f5

### Additional Information

If `goBack` or `goForward` returned promises that resolved when the previous operation was finished, or if they internally waited for the previous operation, that would be nice.

Otherwise, it seems like I'd have to latch onto to the `did-finish-load` event myself and resolve some promise that is awaited before further `goBack` / `goForward` calls are made.

In my case, I have a toolbar with a back and forward button.

If you start my gist, open a window, navigate google twice to some page, and then click quickly between "Go Back" and "Go Forward", you'll get a crash.

calling `webContents.stop()` before the back/forward calls doesn't help.

**Comment by zcbenz** [comment] 2022-11-09 08:15
The referenced code is used to reject the promise returned by `loadURL`, which is not related to the `did-fail-load` event used by the test case gist. The `ERR_ABORTED` error in this case is a valid error generated from Chromium itself instead of Electron's wrapper code.

In Chromium, an aborted navigation is an error, even when it is caused by users with `goBack` or another `loadURL`. When implementing browsers, there is no need to listen to the `did-fail-load` event for most times, the `did-fail-load` event is usually only used by automated scripts.

So I'm closing this issue as it is expected behavior.

**Closed by zcbenz** 2022-11-09 08:15 UTC
Labels: bug :beetle:, has-repro-gist

**Comment by pushkin-** [comment] 2022-11-09 15:25
@zcbenz I'm using `did-fail-load` to provide a custom error page when the URL navigation failed. (while [this PR](https://github.com/electron/electron/pull/25128) hasn't been completed yet).

Is that an appropriate usecase for `did-fail-load`, or should I be using something else?

And so is your recommendation to basically handle this case myself and wait for previous `goBack`/`goForward` calls to complete before making another call?

**Comment by zcbenz** [comment] 2022-11-11 01:49
The event added by https://github.com/electron/electron/pull/25128 unfortunately won't be the best place for custom error page neither, the official way to implement it is by overriding `PrepareErrorPage` which we don't have an API in Electron yet:
https://source.chromium.org/chromium/chromium/src/+/main:content/public/renderer/content_renderer_client.h;l=147-170;drc=76ee012c8192bdfd62f59e451cc5ecd8aaf6e3c1

For now you can only use `did-fail-load` event to emulate the feature, but you have to handle a few edge cases like most CEF apps do:
https://github.com/anaisbetts/libcef/blob/master/cef3/tests/cefclient/client_handler.cpp#L305-L330

And I suggest not do special things to goBack/goForward calls, things like Refresh or Stop may also generate `did-fail-load` errors, and users may also do goBack/goForward in renderers with keyboard shortcuts or JavaScript which you can not hook to.

**Comment by asd281533890** [comment] 2023-03-30 08:34
> @zcbenz I'm using `did-fail-load` to provide a custom error page when the URL navigation failed. (while [this PR](https://github.com/electron/electron/pull/25128) hasn't been completed yet).
> 
> Is that an appropriate usecase for `did-fail-load`, or should I be using something else?
> 
> And so is your recommendation to basically handle this case myself and wait for previous `goBack`/`goForward` calls to complete before making another call?

This is how I handled it:
```
webview.executeJavaScript('window.location.href').then(href => {
  if (href.startsWith('chrome-error://chromewebdata')) {
    // show the custom error page
  }
})
```
