### ISSUE TITLE
"Command+Plus" accelerator appears in menu as "Shift Command =" instead of "Command +" or "Shift Command +" on OS X

### ISSUE THREAD

**Issue by mark-wagon** [electron/electron#1507] opened 2015-04-27 23:08 UTC
* Electron versions: at least 0.23.0 and 0.24.0
* OS: Mac

The [list of key codes](https://github.com/atom/electron/blob/master/docs/api/accelerator.md#available-key-codes) available for use in menu item accelerators includes `Plus`.  When this key is used in an accelerator like `Command+Plus` on OS X, the key combination appears as "Shift Command =".  Given that the key name is `Plus`, it would be preferable to have the corresponding key combination appear as "+" or "Shift +" instead of "Shift =".  The [Keyboard Shortcut section of the OS X Human Interface Guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Keyboard.html) indicates that "Shift Command +" is preferable to "Shift Command ="--look for the paragraph starting with "Identify a key with two characters."

A minimal Electron app that demonstrates this behavior can be found [in this gist](https://gist.github.com/mark-wagon/e4765596cbd9580e26a9).  Repro steps are outlined in the gist's readme.

**Comment by technicalpickles** [comment] 2015-07-03 20:54
I ran into this as well when trying to implement "Zoom In" and "Zoom Out". For "Zoom In", I ended up using `Command+=`. It doesn't show up like you'd expect to in the menu, but it does work like you'd expect it to with the accelerator.

**Comment by technicalpickles** [comment] 2015-07-03 21:07
For "Zoom In" semantics, I think most browser-like things set their accelerator to ⌘+ (ie ⌘ shift =), but setup a second 'alias' for ⌘= to do the same thing. I don't see a way to do that kind of alias with the Electron javascript API yet.

**Comment by ricardomatias** [comment] 2015-10-19 09:43
This is also broken for me on Linux.

**Comment by mkscrg** [comment] 2015-12-04 00:44
Broken on Windows as well, at least as of 0.34.3

**Comment by niftylettuce** [comment] 2016-01-14 01:15
+1

**Comment by atdrago** [comment] 2016-04-22 15:56
> For "Zoom In" semantics, I think most browser-like things set their accelerator to ⌘+ (ie ⌘ shift =), but setup a second 'alias' for ⌘= to do the same thing. **I don't see a way to do that kind of alias with the Electron javascript API yet.**

Would be great if this could be addressed. Instead of `accelerator`, maybe add an `accelerators` option could be specified. An array where the first item is the key combo shown, and the rest are aliases.

For example:
``` javascript
{ label: 'Zoom In', accelerators: [ 'Command+Plus', 'Command+=' ] }
```

The "Zoom In" scenario is a very common one on Mac OS X.

**Comment by luclu** [comment] 2016-05-26 14:47
OS X version of **Ethereum-Wallet** is also affected: https://github.com/ethereum/mist/issues/703
`accelerator: 'CommandOrControl+Shift+1'`

![](https://cloud.githubusercontent.com/assets/10135872/15523476/f3b475f4-221a-11e6-865d-2d39d0547ecd.png)

**Comment by xMrWhite** [comment] 2016-05-29 01:39
this bug is upstream in OS X here is a screenshot of the Spelling and Grammar menu in Safari.
[http://puu.sh/p8D7L/5b4c647951.png]

**Comment by xMrWhite** [comment] 2016-05-29 01:57
Here is another example in the photos app.
Bigger
![Photos App](http://puu.sh/p8DWw/bdd84524d6.png)
Zoom In
![Photos App](http://puu.sh/p8E0b/59b3f1ec07.png)

**Comment by xMrWhite** [comment] 2016-05-29 22:34
Seems to be Fixed in 1.2 
![Electron](http://puu.sh/p9CUI/0468590664.png)
`accelerator: 'Command+Plus',`
just added the example menu to the quick start app and inserted the two actions as accelerators.

**Comment by zcbenz** [comment] 2016-05-30 04:06
@xMrWhite I can verify, thanks for revisiting this!

**Comment by cumajkeee** [comment] 2016-05-31 14:52
@zcbenz, seem that accelerator now displays correct but works as ctrl+cmd+Plus

**Comment by xMrWhite** [comment] 2016-06-01 03:56
From my testing cmd+plus, shift+cmd+plus, and shift+cmd+= all show as cmd+ in the menu. Same with CommandOrControl instead of cmd

**Comment by zcbenz** [comment] 2016-06-01 04:49
It seems that we got a new weird bug. :(

**Comment by xMrWhite** [comment] 2016-06-01 17:38
I just tested adding this menu-item to the electron-quick-start
```{
        label: 'Test',
        accelerator: 'CmdOrCtrl+Plus',
        click() {
          console.log('Test');
        }
      },```
Cmd+Plus (shift+cmd+=) logs "Test" to the console. No need to press ctrl, and ctrl+Plus correctly does not log "Test".
Electron 1.2.0, OSX 10.11.5

**Comment by cumajkeee** [comment] 2016-06-02 10:44
Yeap, confirm that shortcut is cmd+shift+plus, but IMO, a lot of apps has cmd+plus working shortcut for zoom, and it displays as cmd+ not cmd=. As quick example Chrome has this behaviour

**Comment by xMrWhite** [comment] 2016-06-02 11:31
Cms+= is not the same keys as cmd+ plus. 
In Apple apps, see Photos, I have seen both cmd+ plus and shift+ command+= at the same time.

![photos](http://puu.sh/p8EjI/42b705e640.png)

This issue is clearly solved in 1.2 just close it.

**Comment by zcbenz** [comment] 2016-06-03 04:33
@xMrWhite Thanks for the testing and explanation, I'm closing this since current behavior is expected.

**Closed by zcbenz** 2016-06-03 04:33 UTC
Labels: bug

**Comment by cumajkeee** [comment] 2016-06-03 07:50
I same photos app, on Window tab you can found zoom in (cmd+plus) zoom out (cmd+minus) they work by press cmd+ and cmd-. And see in your example how shortcut displays: it show **shift**, cmd and +, in electron for same keys in electron we have cmd and + only.

**Comment by cumajkeee** [comment] 2016-06-08 09:19
@zcbenz , can we reopen ticket according my comment above?

**Comment by zcbenz** [comment] 2016-06-08 10:39
@cumajkeee What you want should be #5256.

**Comment by cumajkeee** [comment] 2016-06-08 10:56
@zcbenz thanks.

**Comment by callodacity** [comment] 2016-09-27 08:06
I know this is closed but I'm using `electron 1.3.4` and `1.3.5` and I'm seeing a similar issue.

When I set the accelerator to `Command+Shift+1` or `CmdOrCtrl+Shift+1` the shortcut appears in the menu as `Command-!`. (The same thing happens for all the numbers, 2 = @, 3 = #, etc...)

Here's a gist similar to the OP's that demonstrates it - run it with `electron .` or equivalent.

**Comment by xMrWhite** [comment] 2016-09-27 10:55
That is the correct behavior look at Apple dev guidelines above. Also this is closed because the key map menu code actually lives upstream in the chrome code  not in the electrum code.

**Comment by callodacity** [comment] 2016-09-28 01:36
@xMrWhite oh - I assumed that it was incorrect behaviour because under _System Preferences -> Keyboard -> Shortcuts -> Screen Shots_ "⇧⌘3" is there rather than "⌘#".  

I was just under the impression that `Command+Shift+1` is simpler for the user than `Command+!` or similar.

But if it's upstream in the Chrome code not much we can do about it here!  
Thanks all the same @xMrWhite

**Comment by xMrWhite** [comment] 2016-09-28 01:49
The behaviour changes in nested menus, if you look at the photos app it has both. It's not super consistent even in Apple apps.

**Comment by loveencounterflow** [comment] 2019-05-07 12:50
I can sadly confirm this to be partly unsolved on Linux running Electron 5.0.1; with a German keyboard I have to configure `      { role: 'zoomIn', accelerator: 'Ctrl+=',  }`; the menu item shows `Ctrl+=` (so at least not changed), but I have to hit `Ctrl+Plus` to get zoom-in (which as such is the intended behavior). (Also, selecting the menu item for any of `resetZoom`, `zoomIn`, `zoomOut` does not do anything other than closing the menu but leaving the menu title highlighted; FWIW this also happens to other menu items that use the `role` mechanism).

**Comment by MattIPv4** [comment] 2019-05-26 21:29
This looks to be a very old issue but one people keep coming back to, so I guess I’ll do the same. I’m having the same issue as above where `Cmd+Shift+` becomes `Cmd+@`. I understand that this is behaviour based on the Apple guidelines but is there any way to tell electron not to “compact” the key combination and show it in the “raw” form?
