### ISSUE TITLE
Cannot compile native add on with 6.0.8 on x64 architecture

### ISSUE THREAD

**Issue by mastergberry** [electron/electron#20198] opened 2019-09-11 07:34 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.8
* **Operating System:**
  * Windows 10 (Build 18362)
* **Last Known Working Electron version:**
  * 6.0.2

### Expected Behavior

For the node-gyp to properly compile my native add on.
### Actual Behavior

Getting a compiler error:

`node.lib(node.exe) : fatal error LNK1112: module machine type 'ARM64' conflicts
with target machine type 'x64'` (this file comes from https://atom.io/download/electron)

### To Reproduce

Run node-gyp for a native add on...

`node-gyp build --target=6.0.8 --arch=x64 --dist-url=https://atom.io/download/electron`

### Additional Information

This is only happening on x64, ia32 is still working as intended.

**Comment by mastergberry** [comment] 2019-09-11 07:47
I believe this relates to https://github.com/electron/electron/pull/20113

I also was able to downgrade to 6.0.7 and not have any issues compiling my native add-on...so most likely this pull request above.

**Comment by malept** [comment] 2019-09-11 14:06
I believe this is a duplicate of #20185.

**Comment by jkleinsc** [comment] 2019-09-11 20:56
Closing as duplicate of #20185

**Closed by jkleinsc** 2019-09-11 20:56 UTC
