### ISSUE TITLE
electron-v9.0.5-win32-ia32 crash 

### ISSUE THREAD

**Issue by wanghua2717** [electron/electron#27146] opened 2020-12-29 08:22 UTC
FAULTING_IP: 
WeLink!v8::internal::ConcurrentMarkingVisitor::VisitPointersInSnapshot+df [C:\projects\src\v8\src\heap\concurrent-marking.cc @ 249]
01713d5f 8b1c8a          mov     ebx,dword ptr [edx+ecx*4]

EXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 01713d5f (WeLink!v8::internal::ConcurrentMarkingVisitor::VisitPointersInSnapshot+0x000000df)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: ff34b311
Attempt to read from address ff34b311

PROCESS_NAME:  WeLink.exe

ADDITIONAL_DEBUG_TEXT:  
Use '!findthebuild' command to search for the target build information.
If the build information is available, run '!findthebuild -s ; .reload' to set symbol path and load symbols.

MODULE_NAME: WeLink

FAULTING_MODULE: 77410000 ntdll

DEBUG_FLR_IMAGE_TIMESTAMP:  5ef0f577

ERROR_CODE: (NTSTATUS) 0xc0000005 - 0x%p

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - 0x%p

EXCEPTION_PARAMETER1:  00000000

EXCEPTION_PARAMETER2:  ff34b311

READ_ADDRESS:  ff34b311 

FOLLOWUP_IP: 
WeLink!v8::internal::ConcurrentMarkingVisitor::VisitPointersInSnapshot+df [C:\projects\src\v8\src\heap\concurrent-marking.cc @ 249]
01713d5f 8b1c8a          mov     ebx,dword ptr [edx+ecx*4]

FAULTING_THREAD:  0000633c

BUGCHECK_STR:  APPLICATION_FAULT_INVALID_POINTER_READ_WRONG_SYMBOLS

PRIMARY_PROBLEM_CLASS:  INVALID_POINTER_READ

DEFAULT_BUCKET_ID:  INVALID_POINTER_READ

LAST_CONTROL_TRANSFER:  from 017144ce to 01713d5f

STACK_TEXT:  
159beb00 017144ce 5b01fb0d 159bec88 0800001d WeLink!v8::internal::ConcurrentMarkingVisitor::VisitPointersInSnapshot+0xdf [C:\projects\src\v8\src\heap\concurrent-marking.cc @ 249]
159beb20 0170ff20 1028eb19 5b01fb0d 00000000 WeLink!v8::internal::ConcurrentMarkingVisitor::VisitJSObjectSubclass<v8::internal::JSWeakCollection,v8::internal::JSWeakCollection::BodyDescriptorImpl>+0xce [C:\projects\src\v8\src\heap\concurrent-marking.cc @ 223]
159bf49c 01714a43 00000004 0d1a29b4 159bf514 WeLink!v8::internal::ConcurrentMarking::Run+0x18f0 [C:\projects\src\v8\src\heap\concurrent-marking.cc @ 450]
159bf4ac 028973d7 19f1e2e0 00000000 028da839 WeLink!v8::internal::ConcurrentMarking::Task::RunInternal+0x13 [C:\projects\src\v8\src\heap\concurrent-marking.cc @ 366]
159bf514 0398c0a9 05cfc154 159bf5f0 00000301 WeLink!base::TaskAnnotator::RunTask+0xe7 [C:\projects\src\base\task\common\task_annotator.cc @ 142]
159bf52c 0398bbcf 159bf5f0 0398a2eb 0d0dadd0 WeLink!base::internal::TaskTracker::RunSkipOnShutdown+0x29 [C:\projects\src\base\task\thread_pool\task_tracker.cc @ 770]
159bf5e8 0398b854 00000000 05c45068 05c4504f WeLink!base::internal::TaskTracker::RunTask+0x22f [C:\projects\src\base\task\thread_pool\task_tracker.cc @ 635]
159bf714 042f0e11 159bf760 19e66728 0d0dadd0 WeLink!base::internal::TaskTracker::RunAndPopNextTask+0x174 [C:\projects\src\base\task\thread_pool\task_tracker.cc @ 504]
159bf77c 042f0afc 000000df 7d688fe8 159bf7b0 WeLink!base::internal::WorkerThread::RunWorker+0x1f1 [C:\projects\src\base\task\thread_pool\worker_thread.cc @ 339]
159bf78c 028cfbb5 0f96c748 00000a40 00000a40 WeLink!base::internal::WorkerThread::RunPooledWorker+0x1c [C:\projects\src\base\task\thread_pool\worker_thread.cc @ 224]
159bf7b0 76786359 18e63988 76786340 159bf81c WeLink!base::`anonymous namespace'::ThreadFunc+0x95 [C:\projects\src\base\threading\platform_thread_win.cc @ 113]
WARNING: Stack unwind information not available. Following frames may be wrong.
159bf7c0 77478944 18e63988 5058dc50 00000000 kernel32+0x16359
159bf81c 77478914 ffffffff 7749a0df 00000000 ntdll+0x68944
159bf82c 00000000 028cfb20 18e63988 00000000 ntdll+0x68914

does any can help me ?

**Comment by codebytere** [comment] 2020-12-29 17:43
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. As such i'm going to close it, but if you would like us to triage this issue, you are welcome to fill out our _required_ issue template with all requisite fields including reproducible sample.

**Closed by codebytere** 2020-12-29 17:43 UTC
