### ISSUE TITLE
[Bug]: Crash when use mainWindow.loadURL() that contains window.open() inside the URL web site

### ISSUE THREAD

**Issue by oalfroukh** [electron/electron#32062] opened 2021-11-30 12:04 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro

### What arch are you using?

x64

### Last Known Working Electron version

14.2.1

### Expected Behavior

Open a new window when the user clicks on the button.

### Actual Behavior

* Crash the electron app when the user clicks on the button for the second time,
   - The user clicks on the button => the new window created.
   - The user closed the created window after that clicked on the same button =>the new window was created and the electron app crashed.
* If I changed the `nativeWindowOpen` to `false` the crash is fixed.

### Additional Information

I have an electron app that used loadURL inside the main window, and this URL contains a button that uses a `window.open("https://www.w3schools.com")` method.

```
const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      contextIsolation: false,
      nodeIntegration: true,
      nativeWindowOpen: true,
    },
  });

  mainWindow.loadURL("http://localhost:3000/");
```

The issue reproducible just in Electron **v16.0.2** and **v15.3.2**

**Comment by oalfroukh** [comment] 2021-11-30 12:08
`http://localhost:3000/` contains this react app:

![image](https://user-images.githubusercontent.com/80884942/144044561-db42580b-ce45-440c-bcd1-02deb85282a6.png)

**Comment by codebytere** [comment] 2022-01-10 14:07
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-01-20 09:27
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed by codebytere** 2022-01-20 09:27 UTC
Labels: bug :beetle:, blocked/need-repro, 16-x-y
