### ISSUE TITLE
electron11+ 版本存在较大的问题

### ISSUE THREAD

**Issue by AceAZhe** [electron/electron#27547] opened 2021-01-29 04:32 UTC
electron 10.1.1 的版本存在的问题 
1. win.reload()会崩溃应用。
2. 在企业版window10的1809版本，无法创建渲染进程，即win.loadUrl()渲染不出页面，而且gpu-process线程不存在。

electron 11+版本存在的问题：
1. 创建的应用，较高频率出现白屏或者卡页面（即报错页面崩溃），需要点击一下电脑桌面任意地方才会渲染出来。
2. 创建的应用，打开时前几秒无法点击，点了界面没有任何反应，几秒之后页面才会有反应。
3. 在企业版window10的1809版本，存在可以打印渲染进程的日志，但是没有显示渲染进程。

**Comment by ckerr** [comment] 2021-01-29 13:20
translate.google.com:

> Problems with electron 10.1.1 version
>
> win.reload() will crash the application.
> In version 1809 of the enterprise version of window10, the rendering process cannot be created, that is, the page cannot be rendered by win.loadUrl(), and the gpu-process thread does not exist.
>
> Problems with electron 11+ version:
>
> The created application has a high frequency of white screen or stuck page (that is, the error page crashes), and it will be rendered by clicking anywhere on the computer desktop. The created application cannot be clicked in the first few seconds when it is opened, and there is no response when the interface is clicked. After a few seconds, the page will respond. In version 1809 of the enterprise version of window10, there is a log of the rendering process that can be printed, but the rendering process is not displayed.

**Comment by ckerr** [comment] 2021-01-29 13:21
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by AceAZhe** [comment] 2021-01-29 14:14
electron 10.1.1版本存在的问题：
基于electron-vue搭建的项目demo，默认electron是2.0.18版本。
1.  electron的2.0.18版本的demo在企业版window10的1809版本，可以正常显示。
2.  electron的2.0.18版升级到10.1.1的demo在企业版window10的1809版本，无法正常显示，没有渲染页面进程，日志触发的是'unresponsive'。
3.  electron的2.0.18版升级到11.0.0的demo在企业版window10的1809版本，可以正常显示。

electron 11+版本存在的问题：
应用同时创建了2个窗口（启动动画窗口（默认show:true）和主界面窗口（默认show:false）），在加载页面动画窗口加载动画效果加载循环一圈且接口请求返回结果之后，关闭启动动画窗口（close()），让主界面显示出来（show()）。这种场景下，打包的应用，会出现的问题：
1.创建的应用，较高频率出现白屏或者卡页面（即报错页面崩溃），需要点击一下电脑桌面任意地方才会渲染出来。
2.创建的应用，打开时前几秒无法点击，点了界面没有任何反应，几秒之后页面才会有反应。

**Comment by xland** [comment] 2021-01-30 01:47
@AceAZhe 

Hey, Bro, I think your issue will be dismiss if you cann't explicitly specify how the issue occurred.

我也是个中国人

**Comment by ckerr** [comment] 2021-02-02 15:20
Because of time constraints, triaging issues with third-party dependencies is usually not feasible for a small team like Electron's. Can you reproduce this issue without Vue?

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

**Comment by electron-triage** [comment] 2021-03-09 16:28
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2021-03-09 16:28 UTC
Labels: 10-x-y, 11-x-y, blocked/need-repro, bug :beetle:, platform/windows

**Comment by paulyu12** [comment] 2023-02-21 05:01
Waiting for solutions, too.

**Comment by Halecoder** [comment] 2024-04-17 16:11
> electron 10.1.1版本存在的问题： 基于electron-vue搭建的项目demo，默认electron是2.0.18版本。
> 
> 1. electron的2.0.18版本的demo在企业版window10的1809版本，可以正常显示。
> 2. electron的2.0.18版升级到10.1.1的demo在企业版window10的1809版本，无法正常显示，没有渲染页面进程，日志触发的是'unresponsive'。
> 3. electron的2.0.18版升级到11.0.0的demo在企业版window10的1809版本，可以正常显示。
> 
> electron 11+版本存在的问题： 应用同时创建了2个窗口（启动动画窗口（默认show：true）和主界面窗口（默认show：false）），在加载页面动画窗口加载动画效果加载循环一圈且接口请求返回结果之后，关闭启动动画窗口（close（）），让主界面显示出来（show（））。这种场景下，打包的应用，会出现的问题： 1.创建的应用，较高频率出现白屏或者卡页面（即报错页面崩溃），需要点击一下电脑桌面任意地方才会渲染出来。 2.创建的应用，打开时前几秒无法点击，点了界面没有任何反应，几秒之后页面才会有反应。

请问您怎们解决的，我遇到了一个一样问题

**Comment by Halecoder** [comment] 2024-04-18 03:09
记录一下，我解决了，需要关闭GPU渲染
app.disableHardwareAcceleration();//禁用硬件加速 
来源：
https://zhuanlan.zhihu.com/p/347902214
