### ISSUE TITLE
[Bug]: ```nativeTheme.themeSource``` not changing to dark mode

### ISSUE THREAD

**Issue by happer64bit** [electron/electron#34979] opened 2022-07-19 16:26 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v19.0.8

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

v19.0.8

### Expected Behavior

![Screenshot (6)](https://user-images.githubusercontent.com/96770798/179801175-51009830-d576-4529-9bcf-08a53b1e2875.png)

### Actual Behavior

```  nativeTheme.themeSource = 'dark'``` not working

### Additional Information

# title bar theme is not dark mode

![Screenshot (4)](https://user-images.githubusercontent.com/96770798/179800835-f509c01d-ab51-4039-a837-756f36040e55.png)

# That is how I want to look like it

![Screenshot (6)](https://user-images.githubusercontent.com/96770798/179801175-51009830-d576-4529-9bcf-08a53b1e2875.png)

**Comment by ckerr** [comment] 2022-07-19 17:35
@happer64bit You listed 19.0.8 as being the broken version and the last working version -- if you try this out on older versions of Electron, do you see different behavior?

**Comment by happer64bit** [comment] 2022-07-20 03:55
@ckerr What version should I install?

**Comment by codebytere** [comment] 2022-07-20 09:35
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed** 2022-07-20 16:24 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, 19-x-y

**Comment by happer64bit** [comment] 2022-07-20 16:26
@codebytere do you mean nightly version?

**Comment by DoneDeal0** [comment] 2023-01-21 14:35
On electron 22.0.2 it doesn't work either. `nativeTheme.themeSource = "dark"` does nothing.

**Comment by BernhardBehrendt** [comment] 2023-02-13 23:09
Fo me it works once when I switch it for the first time (regardless if light->dark or dark->light)

But whenever I toggle it then 
- for the first time the UI totally freezes and the Window/Devtools switch immediatlley) after a while the UI also switches the mode

- when I repeat and want to change for the second time then the ui freezes endlessly and I have to fully restart the app
