### ISSUE TITLE
Sending the same objects in one message by IPC gets NULL. 

### ISSUE THREAD

**Issue by ivarptr** [electron/electron#6969] opened 2016-08-25 11:07 UTC
* Electron version: 1.3.3
* Operating system: os x 10.11.4

Consider this scene:

    let child = {name: 'hello'};
    let foo = {id: 1, child: child};
    let bar = {id: 2, child: child};
    let message = [foo, bar];

i.e. both object `boo` and `bar` contains the same object `child`, when sends the object `message` from ipcMain to ipcRenderer (or from ipcRenderer to ipcMain),  will get this result:

    [
    {id:1, child:{name:'hello'}}, 
    {id:2, child:null}
    ]

The property value of 'child' in the second item is **NULL** instead of {name: 'hello'}.

But it's ok when send this message by `event.returnValue = ...` in the ipcMain.on event.

**Comment by enlight** [comment] 2016-08-25 11:22
Duplicate of #3598

**Comment by kevinsawicki** [comment] 2016-08-25 16:05
Closing as duplicate of #3598 but I'm going to reopen that issue since I believe it can be addressed now.

**Closed by kevinsawicki** 2016-08-25 16:05 UTC
