### ISSUE TITLE
Wrong touch position on touch-screen laptop while using pepper flash plugin

### ISSUE THREAD

**Issue by JenningsWu** [electron/electron#5098] opened 2016-04-09 06:29 UTC
* Electron version: v0.37.5
* Operating system: Win10
* Pepper flash version: 19.0.0.226 or 21.0.0.197
* On touch-screen laptop (ie. Surface Pro)

It seems that flash's touch position is wrong in electron v0.37.x.
~~As shown below,
https://cloud.githubusercontent.com/assets/6861365/14402137/97e23c66-fddf-11e5-8538-5602674fecd6.png
The pepper flash start from (i, j), and if we touch the blue point (x, y), the purple point (x+i, y+j) will actually be clicked.~~

It is strange that if we open the Developer Tools and choose any element in Elements, the touch position in flash area will go back to normal.

### Correction:
We are trying to simplify our app, and find that this issue is in related with `webview`. The flash is in a `webview` and the touch position offset is the same as the `webview`'s position.
![nov jn1 xp 2a8 ypkl6 b](https://cloud.githubusercontent.com/assets/6861365/14402311/8cadf676-fde6-11e5-86dc-cf181936bbde.png)
As shown above, the `webview` start from (i, j), and if we touch the blue point (x, y), the purple point (x+i, y+j) will actually be clicked.

**Comment by KochiyaOcean** [comment] 2016-04-09 07:42
[This repo](https://github.com/KochiyaOcean/electron-flash-touch-bug) (for windows) can reproduce the bug.

**Comment by zcbenz** [comment] 2016-04-11 11:53
It seems that Chrome 49 has some regressions on touch events in webview (https://crbug.com/598957), can you try if the same problem reproduces in the webview tag of Chrome apps? I don't have a touch device so I'm unable to try.

**Comment by JenningsWu** [comment] 2016-04-12 09:17
I tried [this](https://github.com/KochiyaOcean/chrome-webview-bug) as a chrome app on Surface and reproduced the same problem.

**Comment by KochiyaOcean** [comment] 2016-04-13 17:50
Created a new issue for this bug https://crbug.com/603133

**Comment by KochiyaOcean** [comment] 2016-04-26 14:03
The bug is fixed by https://chromium.googlesource.com/chromium/src.git/+/335bb76db170d76ba46fa003a8838255a5d46187 in Chrome Canary.

**Comment by zcbenz** [comment] 2016-04-27 01:13
@KochiyaOcean The commit you referred to only changes the code of layout tests, I don't think it is related.

**Comment by KochiyaOcean** [comment] 2016-04-27 07:10
@zcbenz Maybe I found a wrong commit, but it actually fixed on latest Chrome Dev.

**Comment by xywz** [comment] 2016-06-11 18:48
Fixed: https://bugs.chromium.org/p/chromium/issues/detail?id=603133#c9.

**Comment by zcbenz** [comment] 2016-06-14 05:35
@xywz Thanks for looking into this, I'm closing this since it has been fixed in Chrome51.

**Closed by zcbenz** 2016-06-14 05:35 UTC
Labels: blocked, bug, fixed-in-upstream, webview
