### ISSUE TITLE
Proposal: Electron Daemon

### ISSUE THREAD

**Issue by frank-dspeed** [electron/electron#16227] opened 2019-01-01 18:07 UTC
**Is your feature request related to a problem? Please describe.**
running many electron apps uses much memory and harddisk space overhead

**Describe the solution you'd like**
electron should run as a daemon so that more then 1 app can share functions

**Describe alternatives you've considered**
create os level bindings for all functions something like nativ apps done via cordova

**Additional context**

**Comment by nornagon** [comment] 2019-01-02 18:36
Duplicate of #673

**Closed by nornagon** 2019-01-02 18:36 UTC
Labels: enhancement :sparkles:
