### ISSUE TITLE
[Bug]: Wrong main window hidden state on macOS when using 'parent' option

### ISSUE THREAD

**Issue by ZIMkaRU** [electron/electron#29732] opened 2021-06-16 16:17 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.4

### What arch are you using?

x64

### Last Known Working Electron version

11.4.5

### Expected Behavior

  - create the main window with `show: false` option
  - create the child window with a loading spinner and show it immediately
  - after 10 sec hide the child window and show the main one

### Actual Behavior

The main window is shown along with the child window, disregarding the `show: false` flag. This behavior is seen only on macOS.

### Testcase Gist URL

https://gist.github.com/f2a3a5e8d9130223f18b8ddade390f20

**Comment by nornagon** [comment] 2021-06-17 19:46
Seems related to the `parent` option. Commenting out the `parent: mainWindow` line produces correct-seeming behavior.

**Comment by codebytere** [comment] 2021-06-21 12:24
This is unfortunately intended behavior: macOS `NSWindow`s do not make it possible by design to show child windows at the same time their parents are hidden. This can also be seen if you call `window.hide()` - all the child windows for `window` will also be hidden by that call.

**Comment by codebytere** [comment] 2021-06-21 12:25
Oops, i misinterpreted this and closed it. I'll keep digging into this.

**Comment by codebytere** [comment] 2021-06-22 10:13
Unfortunately all signs point to this changing as a result of Chromium updating from Xcode 12.2 to Xcode 12.4 in [this CL](https://chromium-review.googlesource.com/c/chromium/src/+/2715984) - that means here unfortunately that the change in behavior is consequent to the SDK change in the XCode update. Apple likely changed the underlying behavior of [`addChildWindow`](https://developer.apple.com/documentation/appkit/nswindow/1419152-addchildwindow?language=objc) and as such there's not really a fix on Electron's side. I'm going to close this out as a wontfix, but if a fix does eventually become possible for this I'll come back to it.

**Closed by codebytere** 2021-06-22 10:13 UTC
Labels: bug :beetle:, has-repro-gist, platform/macOS

**Comment by ZIMkaRU** [comment] 2021-06-22 10:19
Sorry to hear that, thanks for trying to fix the issue
