### ISSUE TITLE
Spellcheck API Improvements

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#12605] opened 2018-04-12 19:25 UTC
* Electron version: Latest
* Operating system: OSX, Windows

I've been rebuilding the spellchecker for [notion.so](www.notion.so/desktop) and I thought I would compile some of the quirks I ran into.

The de facto solution right now is to use [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker) and we've been using it for the past year, but recently the language auto-detect stopped working on Mac. Probably a recent OS update or something. Slack has language select in their settings menu so I'd imagine fixing this issue isn't such a high priority for them (I believe the maintainer works there ;).

So I went about building my own solution that uses [node-cld](https://github.com/dachev/node-cld) to detect the language on `selectionchange` events and [node-spellchecker](https://github.com/atom/node-spellchecker) to access native spellcheck APIs on MacOS and Window 8+. Here are some feature requests:

- Async [`webFrame.setSpellCheckProvider`](https://github.com/electron/electron/blob/master/docs/api/web-frame.md#webframesetspellcheckproviderlanguage-autocorrectword-provider) https://github.com/electron/electron/issues/10734 -- if we could throttle spellcheck to wait for users to stop typing, there would be a lot less jank and feel a lot more performant.

- `webFrame.checkSpelling(elm: HTMLElement)` -- currently, a user has to move their selection through an editable element before the spellchecker will run. It would be nice if we could trigger this manually.

- [`webContents.replaceMisspelling`](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsreplacemisspellingtext) doesn't remove misspelling underline -- The `webFrame.checkSpelling` API could be a simple workaround to fix this.

- Multi-language support is not quite possible because the [`webFrame.setSpellCheckProvider`](https://github.com/electron/electron/blob/master/docs/api/web-frame.md#webframesetspellcheckproviderlanguage-autocorrectword-provider) API only lets you check one word at a time. Thus you cannot have multiple languages in the same input because it needs to decide on only one language. One solution is for the API to pass the entire textContent and return a list of selections that are misspelled.

- Tangentially related: `node-spellchecker` has `Add to Dictionary` and `Remove from Dictionary` support, but it doesn't have `isAddedToDictionary` so its hard to know when to show the `Remove from Dictionary` option in the context menu.

Finally, I just want to highlight how good the Google Chrome spellchecker is. It handles language detection with multiple languages in the same input. Its asynchronous and non-blocking. It has all the native dictionary support. If we were able to pull the Google Chrome spellchecker into Chromium, then all the Electron-based note taking apps and email clients would benefit greatly. https://github.com/electron/electron/issues/3211

CC: @paulcbetts 

Thanks!

**Comment by sofianguy** [comment] 2018-04-13 07:45
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #3211. You may want to subscribe there for updates.

Because we treat our issues list as the project team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the [CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by sofianguy** 2018-04-13 07:45 UTC
Labels: enhancement :sparkles:, platform/macOS, platform/windows, version/1.8.x
