### ISSUE TITLE
Input field's cursor disappears

### ISSUE THREAD

**Issue by LeamonLee** [electron/electron#20400] opened 2019-10-02 01:29 UTC
Hello electron team,

I'm using electron with Angular. There's one input field in my homepage. But I ran into an issue where right after an alert window popped up, the focus(cursor) of the input field disappeared and never show up again no matter how many times I clicked it. It only shows up again either I minimized the whole window and then bring it back up, or I turned on the developer tools. 

Is there any parameters or settings I missed?  Thanks

O.S:  windows 10
Electron version: V6.0.10
Angular version: V7.0.3

**Comment by Slapbox** [comment] 2019-10-07 21:57
@LeamonLee are you able to test this on any other systems?

I wonder if this is related to a bug I've been struggling with, only on Windows: https://github.com/electron/electron/issues/20464

It seems like something is wonky with focus management on Windows where it thinks it has proper focus on a window when it doesn't.

I see a lot of people seem to be having your issue, so anyone experiencing it, please add some details to this bug or the one I linked (whichever is more relevant).

This bug report (20400) is incomplete and unlikely to be investigated without more details.

**Comment by mobitar** [comment] 2019-10-08 15:16
I'm experiencing this same issue with both Electron 5 and 6. When an alert appears and is dismissed, inputs do not properly regain focus and do not allow editing until you minimize the app and maximize, or focus on another window, then focus again on your app.

**Comment by mobitar** [comment] 2019-10-08 16:07
The earliest mention I could find of this issue was [June 5, 2019](https://github.com/electron/electron/issues/18646), so it's unlikely we'll get a fix anytime soon. I was able to use the following workaround to fix this behavior:

```javascript
  const isWindows = process.platform === 'win32';
  let needsFocusFix = false;
  let triggeringProgrammaticBlur = false;

  win.on('blur', (event) => {
    if(!triggeringProgrammaticBlur) {
      needsFocusFix = true;
    }
  })

  win.on('focus', (event) => {
    if(isWindows && needsFocusFix) {
      needsFocusFix = false;
      triggeringProgrammaticBlur = true;
      setTimeout(function () {
        win.blur();
        win.focus();
        setTimeout(function () {
          triggeringProgrammaticBlur = false;
        }, 100);
      }, 100);
    }
  })

```

**Comment by LeamonLee** [comment] 2019-10-15 06:33
@Slapbox  Sorry for the late reply. It's exactly the same as how mobitar described. Whenever you use the javascript built-in alert() function. the focus will get lost. But as long as you click on other window, or minimize the app and resume it back, the focus will be back to normal. In the end, I used my own css-style alert window to get around this.

**Comment by hldgaofeng** [comment] 2019-10-22 06:25
When will this problem be fixed?

**Comment by PhotonAmpere** [comment] 2019-11-21 09:11
To work around this I replaced at the beginning of my code the alert function by the showMessageBoxSync function:
````javascript
alert = function(str){
  var options = {
    type: 'warning',
    buttons: ["Ok"],
    defaultId: 0,
    cancelId:0,
    detail:str,
    message: ''
  }
  dialog.showMessageBoxSync(null,options)
}
````
The main advantage is that you can easily delete this piece of code whenever alert() is working again, and don't have to change anything else in your code.
You can change the type depending on what you want.

**Comment by ChristmasIn2015** [comment] 2020-06-02 10:10
Codes as "window.alert" may have no choice but be replaced by our own css alert component.
Here is a very simple but strange resolution for "window.print()":

Prepare a new page in router just for running print()，
    and then it will lose electron window focus after we finish our print work.
But our homepage will not lose the window focus after close this special Page :) !

**Comment by rrettig98** [comment] 2020-10-09 20:48
> To work around this I replaced at the beginning of my code the alert function by the showMessageBoxSync function:
> 
> ```js
> alert = function(str){
>   var options = {
>     type: 'warning',
>     buttons: ["Ok"],
>     defaultId: 0,
>     cancelId:0,
>     detail:str,
>     message: ''
>   }
>   dialog.showMessageBoxSync(null,options)
> }
> ```
> 
> The main advantage is that you can easily delete this piece of code whenever alert() is working again, and don't have to change anything else in your code.
> You can change the "type" in the options depending on what you want.

Where are you adding this code snippet? I'm trying to override window.alert() within the entry file of my Electron app (main.js) so that I am able to use the Dialog API, but I cannot reference window as it is not defined. If I just override alert as done in your snippet it is never called.

**Comment by rrettig98** [comment] 2020-10-09 22:55
@andi23rosca - hello!

I had tried a preload file but was unable to get it working (dialog was undefined). I figured out the problem though - I was not accessing the [Dialog module using the remote](https://www.electronjs.org/docs/api/dialog#dialog). 

Here is my working `preload.js` for anyone in the future:
```
const {dialog} = require('electron').remote;

window.alert = function (str) {
  const options = {
    type: 'warning',
    buttons: ["Ok"],
    defaultId: 0,
    cancelId: 0,
    detail: str,
    message: ''
  }
  dialog.showMessageBoxSync(null, options)
}
```
And my `BrowserWindow` instantiation:
```
win = new BrowserWindow({
    width: 1200,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      preload: path.join(__dirname, 'preload.js')
    }
  });
```
Thank you!

**Comment by fishbone1** [comment] 2020-11-02 10:06
And don't forget `confirm()`:

```js
const remote = window['require']('electron').remote;
window.confirm = function(message) {
  const buttonIdx = remote.dialog.showMessageBoxSync(null, {
    type: 'question',
    buttons: ['OK', 'Cancel'],
    defaultId: 0,
    cancelId: 1,
    detail: message,
    message: ''
  });
  return buttonIdx === 0;
};
```

**Comment by electron-triage** [comment] 2021-03-09 19:55
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 19:55 UTC
Labels: 6-0-x

**Comment by pushkin-** [comment] 2021-03-12 20:15
this is a dupe of [this](https://github.com/electron/electron/issues/19977)

**Comment by Lumine7** [comment] 2022-05-07 03:23
this problem still exist until today ,wtf
I was going to Check and Accept my course project but found this problem
why not fix it!!!

**Comment by TeddyBear06** [comment] 2022-05-21 23:38
> The earliest mention I could find of this issue was [June 5, 2019](https://github.com/electron/electron/issues/18646), so we may not get a fix anytime soon. I was able to use the following workaround to fix this behavior:
> 
> ```js
>   const isWindows = process.platform === 'win32';
>   let needsFocusFix = false;
>   let triggeringProgrammaticBlur = false;
> 
>   win.on('blur', (event) => {
>     if(!triggeringProgrammaticBlur) {
>       needsFocusFix = true;
>     }
>   })
> 
>   win.on('focus', (event) => {
>     if(isWindows && needsFocusFix) {
>       needsFocusFix = false;
>       triggeringProgrammaticBlur = true;
>       setTimeout(function () {
>         win.blur();
>         win.focus();
>         setTimeout(function () {
>           triggeringProgrammaticBlur = false;
>         }, 100);
>       }, 100);
>     }
>   })
> ```
> 
> **Update**: the workaround above causes unintended consequences when attempting to refocus the app, where the app can blur but not refocus at times. The only solution for now appears to be ditching alert() for a custom implementation.

Thanks man... Made my day.

**Comment by Slapbox** [comment] 2022-05-22 21:49
I believe the underlying issue is this: https://github.com/electron/electron/issues/20464

Please go upvote it for attention. The need for these fixes is ridiculous.

**Comment by KrPawan** [comment] 2022-10-08 19:00
> ```js
> alert = function(str){
>   var options = {
>     type: 'warning',
>     buttons: ["Ok"],
>     defaultId: 0,
>     cancelId:0,
>     detail:str,
>     message: ''
>   }
>   dialog.showMessageBoxSync(null,options)
> }
> ```

How to use this it is generating error when i directly used this

**Comment by iamqiz** [comment] 2023-05-05 22:09
> ```js
> showMessageBoxSync
> ```

https://www.electronjs.org/docs/latest/api/dialog
