### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by knaos** [electron/electron#32113] opened 2021-12-06 10:16 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

When using `app.setLoginItemSettings({ openAtLogin: true, openAsHidden: false });` I expect the application would start on login.
The path to the application is the default one. 

### Actual Behavior

The application starts but an error is thrown.
![image](https://user-images.githubusercontent.com/7912102/144828277-7901ae65-9b09-4daa-b8de-1ff799bf5793.png)

### Additional Information

I am packaging the application with electron-builder. The path in the registry is correctly set to the .exe of the application. If I start the application manually there is no problem.

**Comment by nornagon** [comment] 2022-01-05 20:20
This looks like an issue with the way native modules are bundled in your app, not a bug with Electron per se. Can you try raising this issue on the electron-builder repository? I'm going to close this for now, but if it turns out there's something broken in Electron itself we can consider reopening.

**Closed by nornagon** 2022-01-05 20:20 UTC
Labels: bug :beetle:

**Comment by xuhaichaoy** [comment] 2022-02-16 07:23
same problem
