### ISSUE TITLE
Main process crashes on webview navigation

### ISSUE THREAD

**Issue by iwiedenm** [electron/electron#25872] opened 2020-10-10 06:00 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.3, 9.3.2
* **Operating System:**
  * macOS & Windows
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior
`webview.loadURL()` should either call .then during success or .catch during an error. 

### Actual Behavior
In some instances (fully reproducible Fiddle attached) it crashes the whole app. Namely, when on twitter.com and then navigating away the app crashes.

### To Reproduce
`index.html`
```html
<webview id="wv" src="https://twitter.com"></webview>
```

`renderer.js`
```js
let done = false;
document.addEventListener('DOMContentLoaded', function() {
  const wv = document.getElementById('wv');
  wv.addEventListener('dom-ready', function() {
    if (!done) {
      done = true;
      setTimeout(function () {
        wv.loadURL('https://google.com');
      }, 3000);
    }
  })  
})
```

Fiddle: https://gist.github.com/iwiedenm/8373c65e5854089894aa4a288e576ad6
Fiddle is very simple... loads index.html and waits for the webview (starting on https://twitter.com) to be ready, then waits another few seconds and navigates to https://google.com. Then the whole app crashes.

**Comment by zcbenz** [comment] 2020-10-12 00:13
I can reproduce this crash:

```
Received signal 11 SEGV_MAPERR 000000000050
0   Electron Framework                  0x000000011c27d249 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x000000011c177be3 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework                  0x000000011c27d111 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 2385
3   libsystem_platform.dylib            0x00007fff6ee5b5fd _sigtramp + 29
4   ???                                 0x00007feaf9d17de0 0x0 + 140647190330848
5   Electron Framework                  0x000000011b087de6 content::RenderFrameHostManager::SetRWHViewForInnerContents(content::RenderWidgetHostView*) + 118
6   Electron Framework                  0x000000011b2c9aca content::WebContentsImpl::ReattachToOuterWebContentsFrame() + 186
7   Electron Framework                  0x000000011b2ee723 content::WebContentsImpl::NotifyViewSwapped(content::RenderViewHost*, content::RenderViewHost*) + 963
8   Electron Framework                  0x000000011b2fce8b content::WebContentsImpl::NotifySwappedFromRenderManager(content::RenderFrameHost*, content::RenderFrameHost*, bool) + 379
9   Electron Framework                  0x000000011b07f855 content::RenderFrameHostManager::CommitPending(std::__1::unique_ptr<content::RenderFrameHostImpl, std::__1::default_delete<content::RenderFrameHostImpl> >, std::__1::unique_ptr<content::BackForwardCacheImpl::Entry, std::__1::default_delete<content::BackForwardCacheImpl::Entry> >, bool) + 2213
10  Electron Framework                  0x000000011b07ee0f content::RenderFrameHostManager::CommitPendingIfNecessary(content::RenderFrameHostImpl*, bool, bool, bool) + 399
11  Electron Framework                  0x000000011b07ec57 content::RenderFrameHostManager::DidNavigateFrame(content::RenderFrameHostImpl*, bool, bool, bool, blink::FramePolicy const&) + 23
12  Electron Framework                  0x000000011b0350c5 content::Navigator::DidNavigate(content::RenderFrameHostImpl*, FrameHostMsg_DidCommitProvisionalLoad_Params const&, std::__1::unique_ptr<content::NavigationRequest, std::__1::default_delete<content::NavigationRequest> >, bool) + 1541
13  Electron Framework                  0x000000011b04f289 content::RenderFrameHostImpl::DidCommitNavigationInternal(std::__1::unique_ptr<content::NavigationRequest, std::__1::default_delete<content::NavigationRequest> >, std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, bool) + 2617
14  Electron Framework                  0x000000011b04e48d content::RenderFrameHostImpl::DidCommitNavigation(std::__1::unique_ptr<content::NavigationRequest, std::__1::default_delete<content::NavigationRequest> >, std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) + 1085
15  Electron Framework                  0x000000011b04f635 content::RenderFrameHostImpl::DidCommitPerNavigationMojoInterfaceNavigation(content::NavigationRequest*, std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) + 341
16  Electron Framework                  0x000000011b07cc12 base::internal::Invoker<base::internal::BindState<void (content::RenderFrameHostImpl::*)(content::NavigationRequest*, std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>), base::internal::UnretainedWrapper<content::RenderFrameHostImpl>, content::NavigationRequest*>, void (std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>)>::RunOnce(base::internal::BindStateBase*, std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >&&, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>&&) + 82
17  Electron Framework                  0x0000000118226c7e content::mojom::NavigationClient_CommitNavigation_ForwardToCallback::Accept(mojo::Message*) + 478
18  Electron Framework                  0x000000011c71aa87 mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*) + 1431
19  Electron Framework                  0x000000011c71e60b mojo::MessageDispatcher::Accept(mojo::Message*) + 251
20  Electron Framework                  0x000000011c71bdb1 mojo::InterfaceEndpointClient::HandleIncomingMessage(mojo::Message*) + 97
21  Electron Framework                  0x000000011c779af2 IPC::(anonymous namespace)::ChannelAssociatedGroupController::AcceptOnProxyThread(mojo::Message) + 706
22  Electron Framework                  0x000000011c77694c base::internal::Invoker<base::internal::BindState<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message), scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController>, mojo::Message>, void ()>::RunOnce(base::internal::BindStateBase*) + 140
23  Electron Framework                  0x000000011c20d44b base::TaskAnnotator::RunTask(char const*, base::PendingTask*) + 395
```

**Comment by iwiedenm** [comment] 2020-10-12 03:38
@zcbenz Thank you for providing this information. In the future, where can I look to get the log you have provided so I can be more helpful?

**Comment by zcbenz** [comment] 2020-10-12 08:18
On macOS, you can find app's crash reports in `Console.app`.

**Comment by holmberd** [comment] 2020-10-19 17:14
Seems potentially related to:
- [#25421](https://github.com/electron/electron/issues/25421)
- [#25469](https://github.com/electron/electron/issues/25469)

**Comment by holmberd** [comment] 2020-10-22 23:29
Some more testing notes.

With `allowRendererProcessReuse = false`, navigation to `https://twitter.com` will render the content, i.e. `getBoundingClientRect()` height and width is not zero. But any navigation within the same webview that requires a redirect(301) will cause the main process to crash, e.g. **http**://google.com

Direct navigation to `http://twitter.com` will render a blank page where the rect height and width is zero.

With `allowRendererProcessReuse = true`, navigation to `https://twitter.com` renders with rect height and width zero and any navigation to a url causing a redirect will crash the main process.

**Comment by nornagon** [comment] 2020-10-22 23:55
Closing as duplicate of #25469.

**Closed by nornagon** 2020-10-22 23:55 UTC
Labels: 10-x-y, 11-x-y, 9-x-y, bug :beetle:, bug/crash :boom:, component/webview, platform/macOS, platform/windows
