### ISSUE TITLE
[Bug]: Can't set cookies when using protocol.interceptStreamProtocol()

### ISSUE THREAD

**Issue by JiMcNulty** [electron/electron#32167] opened 2021-12-13 20:38 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

When using protocol.interceptStreamProtocol(), all HTTP headers, including Cookie and Set-Cookie, are provided to the intercept callback (when a request is being made), and accepted by the intercept callback's callback (when a response is being accepted). This works for all requests, including requests made by Electron's <webview>.

### Actual Behavior

When the HTTP/S protocol is being intercepted, and when a Set-Cookie header is included in the headers object passed back to the callback inside StreamProtocolResponse, the Set-Cookie header never makes it to the <webview> (the page never receives and sets the cookie, and the cookie doesn't appear in Chrome Dev Tools).

### Additional Information

A repro is available at https://github.com/ondrej/electron-quick-start/tree/cookie-bug. Clone, then run npm start. The page will load github.com in a <webview>. If you try to sign in, GitHub will error out with "Cookies must be enabled to use GitHub." This happens even though the intercept callback passes on all the headers it receives back to Electron, including the Set-Cookie header. In Chrome Dev Tools, the request will appear with all its headers, except, for some reason, the Set-Cookie header.

**Comment by Prinzhorn** [comment] 2021-12-14 18:27
I think this is https://github.com/electron/electron/issues/23865 ?

**Comment by the-cobbler** [comment] 2021-12-14 18:31
> I think this is #23865 ?

Does not seems like the same problem

**Comment by dsanders11** [comment] 2022-03-15 00:58
Duplicate of #30717.

@JiMcNulty, I'm closing this as a duplicate, but if you believe that is a mistake, please ping me with an explanation on how the two issues differ. Thanks!

**Closed by dsanders11** 2022-03-15 00:58 UTC
Labels: bug :beetle:
