### ISSUE TITLE
Flicker when showing transparent window on Windows

### ISSUE THREAD

**Issue by michalrousal** [electron/electron#10069] opened 2017-07-20 11:29 UTC
* Electron version: 1.7.* (tested with 1.7.5 and 1.7.4) and probably older as well
* Operating system: Windows 7-10 (all supporting window transparency)

### Expected behavior

Transparent window is displayed without extra flicker

### Actual behavior

It seems like the window is first displayed, then hidden and then showed again with 'fade-in' effect which causes annoying flicker. This doesn't happen when the window is not transparent.
Repro rate is not 100% but on fast Windows 10  system it was close to 100%, on slow Windows 7 machine repro rate was about 30%.

### How to reproduce

run attached main.js and open/close window using ctrl+x shortcut

[repro.zip](https://github.com/electron/electron/files/1162100/repro.zip)

**Comment by farzher** [comment] 2018-03-22 19:12
still an issue on latest electron. at least now i know it's caused by transparency

**Comment by codebytere** [comment] 2018-09-24 05:31
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by jjustin3** [comment] 2018-10-01 18:00
@codebytere I am still experiencing this in Electron ^2.0.7.

My project utilizes a lot of programmatic showing and hiding of windows (with animations on hiding and showing), so I have been able to notice some weird things happening. It appears that the reason the window appears to be "flickering" is because one window is shown, immediately hidden, and then the window is shown again.

In my case, upon first launch of the window after being created the transparent window and contents display normally without a flicker or flash. I then hide the window with `win.hide()`.
Upon `win.show()`, the previous state of the window (before being hidden) appears and is then immediately hidden. The window then appears again, but with the new, intended state.

I have tested on a couple of different projects and the transparency issue remains persistent among all of them.

**Comment by nornagon** [comment] 2018-10-01 18:07
Thanks for the response!

**Comment by jjustin3** [comment] 2018-10-08 20:37
Updating with another finding:
Even after destroying the window that flickers, repeating the action that causes the [now destroyed] window to show allows for the "first flash" to happen again, but with no new window being shown thereafter (the latter of which is expected).

This shows that even though the window doesn't exist, the first part of the flicker still occurs with the previous content of the now defunct window. Figured this was worth throwing on this ticket.

**Comment by jjustin3** [comment] 2018-12-05 01:40
I can confirm my earlier speculation is the current behavior from a superficial standpoint. After adding animations to my application and a timeout that waits until all window contents are hidden before closing said window, the re-opened window does not flicker.

Until a solution is found, my recommendation is to add "fade-out" animations to the window content so that closing a transparent window will not flicker on re-open.

**Comment by farzher** [comment] 2019-04-11 10:04
found a simple workaround

```javascript
// hide
browserWindow.setOpacity(0)
browserWindow.hide()

// show
browserWindow.show()
setTimeout(() => {
  browserWindow.setOpacity(1)
}, 1000/60)
```

**Comment by dannya** [comment] 2019-04-11 10:23
@farzher would you be able to raise a pull request for this change please?

**Comment by farzher** [comment] 2019-04-11 10:53
> @farzher would you be able to raise a pull request for this change please?

that would be cool but sorry i'm not sure how to do that properly

**Comment by dannya** [comment] 2019-04-11 11:01
@farzher no problem, what file and lines have you changed?

**Comment by sofianguy** [comment] 2019-08-09 03:48
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by jjustin3** [comment] 2019-08-15 17:01
Still experiencing this issue in v5.0.9. Currently, only work-around I could find that best suits my purpose is a timeout on hiding. It still appears that a transparent window's previous state (before it hides) is first flashed before the window is properly shown.

**Comment by benpolinsky** [comment] 2019-09-05 19:01
Also seeing this behavior on `v5.0.9`

**Comment by electron-triage** [comment] 2020-02-19 20:25
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:20
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:20 UTC
Labels: 2-0-x, 5-0-x, blocked/need-info ❌, bug :beetle:, platform/windows

**Comment by raphadko** [comment] 2020-05-07 03:22
It's still happening on Eletron 8.2.0

**Comment by fanchenio** [comment] 2023-11-06 07:43
It's still happening on Eletron 26.4.2
