### ISSUE TITLE
[Bug]: PDF Plugin not working in webview with partition 

### ISSUE THREAD

**Issue by A-Prorel** [electron/electron#41068] opened 2024-01-22 08:57 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Iframe with Chromium PDF viewer.

### Actual Behavior

Iframe with blank white background.

### Testcase Gist URL

https://gist.github.com/A-Prorel/6e9d10855f3935980eea7dde0988c8f8

### Additional Information

If i remove the partition attribute, it's working.

**Comment by codebytere** [comment] 2024-01-29 11:56
Duplicate of https://github.com/electron/electron/issues/27121

**Closed by codebytere** 2024-01-29 11:56 UTC
Labels: bug :beetle:, component/pdf-viewer, 28-x-y
