### ISSUE TITLE
Crash when clicking links within pdf

### ISSUE THREAD

**Issue by ibash** [electron/electron#11722] opened 2018-01-25 00:06 UTC
* Electron version: Built for macos at commit ea1da93e5ec09d5e1d0f5fbf2333e5e4be8bd8a8
* Operating system: macos 10.13.2

### How to reproduce

1. Open a pdf that has links in the chrome://pdf-viewer.
2. Click a link

I can reproduce this as needed, I haven't tried against latest master (yet).

### Expected behavior

Open the link clicked

### Actual behavior

Get a crash.
Here is the full crash log: https://gist.github.com/ibash/72b716f17349a56d9dc0a1c7206e5dba
For the thread that crashed, here's the stack for `com.github.electron.framework`:
```
base::debug::BreakDebugger() (in Electron Framework) (debugger_posix.cc:267)
logging::LogMessage::~LogMessage() (in Electron Framework) (string:1226)
content::NavigationEntryImpl::SetBindings(int) (in Electron Framework) (navigation_entry_impl.cc:406)
content::NavigationControllerImpl::RendererDidNavigate(content::RenderFrameHostImpl*, FrameHostMsg_DidCommitProvisionalLoad_Params const&, content::LoadCommittedDetails*, bool, content::NavigationHandleImpl*) (in Electron Framework) (navigation_controller_impl.cc:997)
content::NavigatorImpl::DidNavigate(content::RenderFrameHostImpl*, FrameHostMsg_DidCommitProvisionalLoad_Params const&, std::__1::unique_ptr<content::NavigationHandleImpl, std::__1::default_delete<content::NavigationHandleImpl> >) (in Electron Framework) (navigator_impl.cc:636)
content::RenderFrameHostImpl::OnDidCommitProvisionalLoad(IPC::Message const&) (in Electron Framework) (render_frame_host_impl.cc:1584)
content::RenderFrameHostImpl::OnMessageReceived(IPC::Message const&) (in Electron Framework) (render_frame_host_impl.cc:849)
IPC::ChannelProxy::Context::OnDispatchMessage(IPC::Message const&) (in Electron Framework) (ipc_channel_proxy.cc:330)
base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask*) (in Electron Framework) (task_annotator.cc:59)
base::MessageLoop::RunTask(base::PendingTask*) (in Electron Framework) (message_loop.cc:423)
base::MessageLoop::DeferOrRunPendingTask(base::PendingTask) (in Electron Framework) (message_loop.cc:433)
base::MessageLoop::DoWork() (in Electron Framework) (message_loop.cc:540)
base::MessagePumpCFRunLoopBase::RunWork() (in Electron Framework) (message_pump_mac.mm:421)
base::mac::CallWithEHFrame(void () block_pointer) (in Electron Framework) + 10
base::MessagePumpCFRunLoopBase::RunWorkSource(void*) (in Electron Framework) (message_pump_mac.mm:400)
...
base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) (in Electron Framework) (message_pump_mac.mm:766)
base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) (in Electron Framework) (message_pump_mac.mm:144)
base::RunLoop::Run() (in Electron Framework) (run_loop.cc:112)
content::BrowserMainLoop::MainMessageLoopRun() (in Electron Framework) (browser_main_loop.cc:1698)
content::BrowserMainLoop::RunMainMessageLoopParts() (in Electron Framework) (browser_main_loop.cc:1174)
content::BrowserMainRunnerImpl::Run() (in Electron Framework) (browser_main_runner.cc:143)
content::BrowserMain(content::MainFunctionParams const&) (in Electron Framework) (browser_main.cc:46)
content::ContentMainRunnerImpl::Run() (in Electron Framework) (content_main_runner.cc:686)
service_manager::Main(service_manager::MainParams const&) (in Electron Framework) (main.cc:469)
content::ContentMain(content::ContentMainParams const&) (in Electron Framework) (content_main.cc:19)
AtomMain (in Electron Framework) (atom_library_main.mm:24)
```

**Comment by deepak1556** [comment] 2018-01-25 00:22
Can you provide a minimal example to reproduce the issue ? Thanks!

**Comment by ibash** [comment] 2018-01-25 06:07
@deepak1556 sure thing - I added one here: https://github.com/ibash/pdf-crash
The example repo uses the electron 1.8 beta, as I was able to reproduce there too.

Let me know if theres any other way I can help :)

**Comment by abnerlee** [comment] 2018-08-14 13:25
I'm also able to reproduce this in macOS 10.13.6 and Electron 2.0.5

**Comment by JMS-1** [comment] 2018-11-14 16:58
The crash still happens in 2.0.13 on Windows 10 1803 with the same stack trace as initially reported (although content::NavigationEntryImpl::SetBindings seems to run into DebugBreak / int 3 immediatly). I consider a total crash as quite an issue so please check again!

To reproduce: load some HTML with an iframe src="bad.pdf" using the appended sample PDF (only one line of text and a hyperlink). Then click the link.

[bad.pdf](https://github.com/electron/electron/files/2581759/bad.pdf)

**Comment by JMS-1** [comment] 2018-11-21 15:54
Is there any chance that this will be fixed or do we have to check for alternate solutions (although I guess these will be worse in some aspect - e.g. deployment and maintenance may be an issue for us).

**Comment by jeffrson** [comment] 2018-12-27 12:51
Still crashing in 2.0.16.

Since PDF Viewer is disabled in 3.0 and beyond (https://github.com/electron/electron/issues/12337) please provide a fix or a workaround for 2.0.x!

The problem according to the stacktrace (in 2.0.16) is here:
https://chromium.googlesource.com/chromium/src/+/61.0.3163.100/content/browser/frame_host/navigation_entry_impl.cc#405

I don't know enough about what "binding" is, and why it might have changed unexpectedly - but I would suppose it shouldn't be too much of a problem to fix.

Interestingly the crash doesn't seem to happen when the PDF isn't loaded inside an IFrame but the BrowserWindow itself. Unfortunately this is not really a usable workaround :-(

Any "official" statement after nearly one year since the issue has been opened?

**Comment by sofianguy** [comment] 2019-08-09 03:33
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:10
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:10 UTC
Labels: 2-0-x, blocked/need-info ❌, bug/crash :boom:, component/pdf-viewer, version/1.8.x

**Comment by jeffrson** [comment] 2019-08-19 19:48
Well, you should know that viewing pdf files is not possible at all in vanilla electron > 2: Despite of { plugins: true } the pdf file is just offered to be downloaded.

This in itself does not mean, the issue is fixed or not relevant. So closing it appears a bit oversimplified...

What's the state of PDF viewer in Electron?
