### ISSUE TITLE
unable to make connection using mqtts in newer versions of electron

### ISSUE THREAD

**Issue by JasonCubic** [electron/electron#18105] opened 2019-05-01 21:39 UTC
### Preflight Checklist

* [X] I have read the [Contributing Guidelines]
* [X] I agree to follow the [Code of Conduct]
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * v2.0.6 - mqtts works
  * v3.1.9 - mqtts works
  * v4.1.5 - mqtts does not work
  * v5.0.0 - mqtts does not work
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**:
  * 3.1.9

### Expected Behavior
  * mqtts protocol works
  * I am trying to upgrade an electron 2 app for windows. One of the main things the app does is fork a process to listen to a message bus (mqtts). It works in election 2 and 3 but not in any of the newer versions of election. I need to upgrade to the newest version of electron.

### Actual Behavior
This is the specific error I am seeing in electron 4 and up:
```
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1296:19)
    at Object.onceWrapper (events.js:282:20)
    at TLSSocket.emit (events.js:199:15)
    at endReadableNT (_stream_readable.js:1141:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
Emitted 'error' event at:
    at TLSSocket.handleTLSerrors (C:\node_sandbox\electron-mqtt-test-2\node_modules\mqtt\lib\connect\tls.js:26:18)
    at TLSSocket.emit (events.js:199:15)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

### To Reproduce
you will need a mqtts broker setup?  I'm using IBM MQ on a corp network.  I've made an example project that shows how my code is setup: https://github.com/JasonCubic/electron-mqtt-problem

code doesn't run without a mqtts broker to connect to. . .

### Screenshots
N/A

### Additional Information

I believe that electron is intercepting the mqtts protocol and I do not see anywhere how to tell electron to stop doing that.  I want the mqtts protocol to passthrough untouched.  

I see electron 5 has a "protocol" feature but everything I see is about registering a new protocol.  I need electron to ignore a protocol and stop intercepting it.  Or to configure electron somehow so that the connection works securely.

I have been working on this a few days.  Any help I get I GREATLY appreciate.  Thank You in advance,

**Comment by nornagon** [comment] 2019-05-02 16:46
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by JasonCubic** [comment] 2019-05-02 17:53
okay sure.  what I did was make sure all the info was included and deleted the template.  how do I fill out the template at this point?

**Comment by nornagon** [comment] 2019-05-02 17:57
The template has a specific format to make it easy for maintainers to quickly see at a glance a lot of relevant information. It'd be great if you could grab the template from [here](https://github.com/electron/electron/edit/master/.github/ISSUE_TEMPLATE/Bug_report.md) and edit the issue to follow that format.

**Comment by JasonCubic** [comment] 2019-05-02 17:59
### Preflight Checklist

* [X ] I have read the [Contributing Guidelines]
* [X] I agree to follow the [Code of Conduct]
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * v2.0.6 - mqtts works
  * v3.1.9 - mqtts works
  * v4.1.5 - mqtts does not work
  * v5.0.0 - mqtts does not work
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**:
  * 3.1.9

### Expected Behavior
  * mqtts protocol works

### Actual Behavior
produces error: Client network socket disconnected before secure TLS connection was established

### To Reproduce
you will need a mqtts broker setup?  I'm using IBM MQ on a corp network.  I've made an example project that shows how my code is setup: https://github.com/JasonCubic/electron-mqtt-problem

code doesn't run without a mqtts broker to connect to. . .



### Screenshots
N/A

### Additional Information
see first post in this thread for more comments

**Comment by nornagon** [comment] 2019-05-02 22:02
Thanks for filling out the template!

I don't think electron's "protocol" feature is related to this issue; that's for registering custom protocol schemes like `my-app://[...]`, which you're not doing. Looking at your code, it looks like you're using `childProcess.fork` to fork a helper process which communicates with MQTT. `childProcess.fork` spawns a new process that behaves very similarly to pure `node`. Does your helper process code run correctly when run directly with `node`?

Unfortunately I can't do any further debugging without a reproduction case that I can run locally, and I don't have or know what an mqtts broker is. Can you potentially reduce the reproduction case to something simpler (e.g. a raw `net` call?)

**Comment by JasonCubic** [comment] 2019-05-02 22:07
To create a reproducible bug I would need a mqtt broker running somewhere to connect to.  Any idea's about how to do that part?

I have a workaround.  I bundled the forked process into an exe using something called pkg.  Then I use spawn instead of fork and I think that it works.  I haven't been able to test every edge case yet though.

It adds about 20mb file size to the project because it packages up its own version of node with the exe.  but you gotta do what you gotta do.

Wish it worked just using fork though.

**Comment by JasonCubic** [comment] 2019-05-02 22:13
oh i forgot to answer your first question.  The helper process runs fine using pure node.

**Comment by nornagon** [comment] 2019-05-02 22:29
Try running it with `ELECTRON_RUN_AS_NODE=1 .../path/to/electron.exe .../path/to/script.js`

**Comment by JasonCubic** [comment] 2019-05-02 23:24
I tried it.  and got a new error.  maybe I have some nomenclature wrong?

the fork nomenclature:
```
const backgroundTicketListener = childProcess.fork(process.execPath, [backgroundTicketListenerFile], { cwd, env:{ "ELECTRON_RUN_AS_NODE": "1" } });
```
the new error:
```
 starting child process:  C:\node_sandbox\electron-mqtt-test-2\src\static\background-ticket-listener-fork\background-ticket-listener.js
C:\node_sandbox\electron-mqtt-test-2\node_modules\electron\dist\electron.exe:1
MZx


SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:752:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:873:10)
    at internal/main/run_main_module.js:21:11
```
Interested I tried to spawn the electron exe with the ELECTRON_RUN_AS_NODE env value set to 1 and it returned the same error as we originally saw.

**Comment by JasonCubic** [comment] 2019-05-02 23:46
I changed the fork syntax a little and unfortunately it still returns the original error.
```
const backgroundTicketListener = childProcess.fork(backgroundTicketListenerFile, [], { cwd, env:{ "ELECTRON_RUN_AS_NODE": "1" } });
```
the error:
```
events.js:171
      throw er; // Unhandled 'error' event
      ^

Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1296:19)
    at Object.onceWrapper (events.js:282:20)
    at TLSSocket.emit (events.js:199:15)
    at endReadableNT (_stream_readable.js:1141:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
Emitted 'error' event at:
    at TLSSocket.handleTLSerrors (C:\node_sandbox\electron-mqtt-test-2\node_modules\mqtt\lib\connect\tls.js:26:18)
    at TLSSocket.emit (events.js:199:15)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

```

**Comment by JasonCubic** [comment] 2019-05-02 23:53
I don't know what's going on but this is the line that error gets thrown:  https://github.com/nodejs/node/blob/v12.x/lib/events.js#L171

I tried wrapping the mqtt.connect line in my code with a try/catch with no change to the problem.

**Comment by JasonCubic** [comment] 2019-05-02 23:59
okay I added this to the code:
```
mqttClientHandle.on('error', (mqttError) => console.log('mqtt error', mqttError));
```
and now it throws this error every second:
```
mqtt error { Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1296:19)
    at Object.onceWrapper (events.js:282:20)
    at TLSSocket.emit (events.js:199:15)
    at endReadableNT (_stream_readable.js:1141:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
  code: 'ECONNRESET',
  path: undefined,
  host: 'mydevserver.mycorpintra.net',
  port: 8883,
  localAddress: undefined }
```

**Comment by nornagon** [comment] 2019-05-03 00:13
Sorry, i meant directly running it on the command line with that environment variable set.

Also, hm, given that the error is `ECONNRESET`, it looks like the server is shutting down the connection. Perhaps you could try dumping the packets with [Wireshark](https://www.wireshark.org/) during the connection to see if anything's different between node and electron?

**Comment by JasonCubic** [comment] 2019-05-03 01:04
I can try that tomorrow.  Yes, the server is shutting down the connection.  I'm guessing because it's checking the certs and seeing that electron was in the middle.  Mitm attack basically.  It works from node without electron.

**Comment by MarshallOfSound** [comment] 2019-05-03 05:49
@JasonCubic electron isn't in the middle of that request, any request going out of node doesn't even hit the Chromium layer in Electron.  It's basically identical to `node` which is why this is somewhat strange.  It might be connected to our use of boringssl vs openssl.

As @nornagon suggested dumping and inspecting the packets going back and forth will be helpful.  I'd also like to know the TLS versions that the server supports.

**Comment by JasonCubic** [comment] 2019-05-03 17:10
@MarshallOfSound I bet you are right.  When did the change from openssl to boringssl happen?  I looked through the release notes but couldn't find when that change happened.  **What versions of TLS does boringsll not support?**

I don't know what version of TLS the server uses.  I'm in one of those giant corps with hundreds of thousands of employee's, it might take me a few days even to figure out how to contact the MQ team to ask.  I will try though.  hopefully I can find the right person who is on that team who knows.  I'll start working to figure out what internal ticket to fill out to ask that question.

**Comment by nornagon** [comment] 2019-05-03 17:26
You can detect the supported TLS versions of the remote server yourself with a tool like nmap, e.g.

```
$ nmap --script ssl-enum-ciphers -p 443 www.example.com
| ssl-enum-ciphers:
|   TLSv1.0:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       [...]
|   TLSv1.1:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       [...]
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       [...]
```

According to [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_TLS_implementations#Protocol_support), boringssl does not support SSLv2 or SSLv3, as those are insecure protocols.

Electron switched to BoringSSL in 4.0.0.

**Comment by JasonCubic** [comment] 2019-05-03 17:53
You guys are great.  I bet the is the root cause.  great catch guys.  I ran the nmap and got this:
```
C:\>nmap --script ssl-enum-ciphers -p 8883 mydevserver.mycorpintra.net
Starting Nmap 7.70 ( https://nmap.org ) at 2019-05-03 10:50 Pacific Daylight Time
Nmap scan report for mydevserver.mycorpintra.net (redacted ip)
Host is up (0.0030s latency).
rDNS record for (redacted ip): redactedloadbalancer.mycorpintra.net

PORT     STATE SERVICE
8883/tcp open  secure-mqtt
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|     compressors:
|       NULL
|     cipher preference: indeterminate
|     cipher preference error: Too few ciphers supported
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 10.10 seconds

```

**Comment by JasonCubic** [comment] 2019-05-03 18:23
also, I tried the test that was suggested earlier.  I added a script that connects straight to the broker.  Then I added these two lines to the scripts section in package.json:
```
    "electron_test": "set ELECTRON_RUN_AS_NODE=1 && .\\node_modules\\electron\\dist\\electron.exe ticket-listener.js",
    "node_test": "node ./ticket-listener.js",
```
The node_test works and the electron_test has the same ECONNRESET error that we've been seeing.  "Error: Client network socket disconnected before secure TLS connection was established"

**Comment by JasonCubic** [comment] 2019-05-08 17:44
looks like the version of node bundled in with electron doesn't offer cipher spec "SSL_RSA_WITH_AES_128_CBC_SHA256"

46 cipher specs proposed by node:
![node cipher specs](https://user-images.githubusercontent.com/8921015/57395745-bf8c3b80-717d-11e9-8b46-1a18aa612e00.png)

only 18 cipher specs proposed by the version of node inside of electron:
![electron cipher specs](https://user-images.githubusercontent.com/8921015/57395822-e21e5480-717d-11e9-91e5-0a9c763e2c41.png)

Can the version of node inside of electron be setup to propose cipher spec "SSL_RSA_WITH_AES_128_CBC_SHA256"?

**Comment by nornagon** [comment] 2019-05-08 18:15
Node delegates the list of ciphers to the underlying SSL engine, which in Node is OpenSSL, and in Electron (and Chrome) is BoringSSL. We don't control the list of ciphers that BoringSSL will announce itself as supporting—that list is [here](https://boringssl.googlesource.com/boringssl/+/refs/heads/master/ssl/ssl_cipher.cc#159).

Is it possible that you could configure your server to offer a broader cipher set? All that's needed is one cipher that's shared between the server and BoringSSL's offered set. It looks like the server is configured to only offer `TLS_RSA_WITH_AES_128_CBC_SHA256`. BoringSSL supports `TLS_RSA_WITH_AES_128_CBC_SHA` but not `TLS_RSA_WITH_AES_128_CBC_SHA256`. Electron wouldn't expand the cipher suite unless we could get support for that cipher landed upstream in BoringSSL.

It's actually [pretty easy](https://boringssl.googlesource.com/boringssl/+/HEAD/CONTRIBUTING.md) to contribute to BoringSSL; I'd recommend opening a CL (google-speak for PR) against the repository that adds `TLS_RSA_WITH_AES_128_CBC_SHA256` to the `kCiphers` list in `ssl/ssl_cipher.cc` and add agl@google.com as a reviewer :)

**Comment by JasonCubic** [comment] 2019-05-08 18:48
It appears that BoringSSL purposely removed the CBC ciphers: 
 https://boringssl.googlesource.com/boringssl/+/6e678eeb

Our MQTT team is looking at adding ciphers to server.  so I feel like we've explored the electron connection pretty well at this point.  Thank you guys!

**Closed** 2019-05-08 18:48 UTC
Labels: 4-0-x, 4-2-x, 5-0-x, platform/windows

**Comment by nornagon** [comment] 2019-05-08 18:50
Great, thanks for the follow-up and the Boring ask change, that's good to
know!
