### ISSUE TITLE
Some electron apps flicker

### ISSUE THREAD

**Issue by Akronix** [electron/electron#8127] opened 2016-12-02 10:00 UTC
* Electron version: Not applicable. Franz: 4.0.4, GitKraken: 1.9.1 Atom: 1.12.6
* Operating system: Ubuntu 16.04

### Actual behavior

Apps based on electron flicker sometimes.

### How to reproduce
Web view blinks sometimes within electron apps. Apparently, when they are doing "heavy" graphics tasks.
For example, try using Telegram inside Franz and look for a gif (for instance, "Ralph") using @gif inline bot. Screen momentarily flickers as you're scrolling though the gif lists. Curiously, it seems to happen only when Franz window is maximized ("full size").

I have experienced same momentarily flickers in GitKraken or, less often, in Atom.

Seem to be related to chromium because I can reproduce this opening WebTelegram in a chromium browser tab but not in Firefox.

**Comment by MarshallOfSound** [comment] 2016-12-02 10:10
Without a consistently reproducible example their isn't much we can do.

FWIW though I've seen this before on my app and I fixed it my **not** calling `app.disableHardwareAcceleration()` on macOS

**Comment by r4v5** [comment] 2016-12-19 15:35
If you are running with Intel graphics, you may be seeing the effects of an issue documented in [chromium bug 606152](https://bugs.chromium.org/p/chromium/issues/detail?id=606152).

**Comment by Akronix** [comment] 2016-12-19 15:59
It seems to be related to that.
I've being using the nvidia discrete graphics for some time now and I don't
remember to have experienced any flicker again.

**Comment by alexeyten** [comment] 2016-12-22 17:32
It looks like tiny horizontal lines. Here in Slack

![screenshot from 2016-12-22 20 21 18](https://cloud.githubusercontent.com/assets/44377/21434218/add8c5da-c88c-11e6-847b-3302ca99ac74.png)

**Comment by kevinsawicki** [comment] 2017-01-12 01:32
> If you are running with Intel graphics, you may be seeing the effects of an issue documented in chromium bug 606152.

Thanks for finding this @r4v5. I'm going to close this out since it looks to be an open Chrome bug, please subscribe to it there for updates.

**Closed by kevinsawicki** 2017-01-12 01:32 UTC
Labels: more-information-needed

**Comment by novoj** [comment] 2017-03-07 16:16
Problem in chrome can be fixed by appending these arguments:

`--disable-gpu-driver-bug-workarounds --enable-native-gpu-memory-buffers`

Unfortunatelly passing same arguments to Electron based app (Mattermost) doesn't help. Are arguments taken into account in Electron app?

**Comment by ccnokes** [comment] 2017-06-20 18:07
@novoj how are you appending those arguments? Like `app.commandLine.appendArgument('enable-native-gpu-memory-buffers')`? `appendSwitch` doesn't seem to accept arbitrary arguments so just thought I'd double check.

**Comment by novoj** [comment] 2017-06-20 18:46
Directly to the commandline when running MaterMost application:

`/opt/Mattermost/mattermost-desktop --hidden --disable-gpu-driver-bug-workarounds --enable-native-gpu-memory-buffers`

**Comment by reyramos** [comment] 2017-07-24 18:10
I had the same issue, but I had a different solution. Can I ask if you change the name of the electron.exe file within the directory?

**Comment by novoj** [comment] 2018-11-29 07:39
Meanwhile I've upgraded to Ubuntu 18.04 and problem vanished. But because entire system was wiped, there are many things that could affected the result (including MattermostMost/Electron upgrade). I can't verify your recommendation but nevertheless I thank you.

**Comment by betimbryma** [comment] 2019-03-22 10:21
i still have the same problem on Fedora 29, i mean i use `--disable-gpu-driver-bug-workarounds`, but it's just interesting to see why this is still an issue.

**Comment by simformsolutions** [comment] 2019-08-05 12:09
I am still facing flicking issue on `macOS HighSierra 10.13.6` and Graphics .`NVIDIA GeForce GT 710 2047 MB`

Using Electron version : 6.0.0
Expected behaviour was working fine on `electron version: 4.2.8` but getting now as shown below in latest version


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8736329/62463529-e7ecfb80-b7a7-11e9-8204-84d242d63610.gif)


Please help:
@MarshallOfSound @ccnokes

**Comment by floating** [comment] 2019-09-23 02:40
@simformsolutions I'm seeing this as well. 

Have you found a solution for this other than downgrading? If not we should open a new issue for this particular case.

**Comment by bolatovumar** [comment] 2019-10-18 02:47
I'm also experiencing this issue. See https://github.com/LN-Zap/zap-desktop/issues/2938 for details (includes video). This started happening exactly when the project was upgraded from Electron v5 to v6.

**Comment by itsthisjustin** [comment] 2019-11-07 18:22
> @simformsolutions I'm seeing this as well.
> 
> Have you found a solution for this other than downgrading? If not we should open a new issue for this particular case.

No we haven't found any fix. I see this issue is closed. Is there a fix inbound?
