### ISSUE TITLE
[Bug]: VS Code with custom titlebar still draws the system titlebar

### ISSUE THREAD

**Issue by mystiquewolf** [electron/electron#29523] opened 2021-06-03 09:29 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

Other Linux

### Operating System Version

Kubuntu 21.04

### What arch are you using?

x64

### Expected Behavior

VS Code draws just the client-side custom titlebar, no system title bar is drawn from the compositor side.

### Actual Behavior

VS Code draws both system and custom client-side titlebars at the same time.

### Additional Information

According to [THIS](https://github.com/microsoft/vscode/issues/109176#issuecomment-853438875) comment, either Electron asks KWin to draw a titlebar, or KWin decides on its own to draw the titlebar. 

So i'm moving down the stack by one and filing a bug at Electron.

VS Code is started with the following command line in order to use Wayland implementation: ```/usr/share/code/code --enable-features=UseOzonePlatform --ozone-platform=wayland --no-sandbox --unity-launch %F```
VS Code info:
> Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.11.0-17-lowlatency

Kubuntu info:
> Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.90
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-17-lowlatency (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7,6 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by nornagon** [comment] 2021-06-18 20:50
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by mystiquewolf** [comment] 2021-06-20 14:51
I'm not sure if i would be able to create a reduced testcase. I am not an Electron developer and i would have to create a custom titlebar on my own, when VS Code already has one.

Basically in this issue it should be checked whether Electron asks KWin to draw a system toolbar and if so - why it asks it when VS Code already draws its own custom titlebar.

If Electron does not ask KWin to draw the titlebar, then the bug is lower in the software stack - at the KWin compositor level. 
If there is someone else who wants to create a reduced testcase - please feel free to do so.

**Comment by vially** [comment] 2021-08-02 20:11
I'm not running KDE so I'm unable to test this but I just came across this upstream Chromium issues ([chromium#1138724](https://bugs.chromium.org/p/chromium/issues/detail?id=1138724)) which seems to describe the same problem.

It looks like it should have been fixed starting from chromium version `93.0.4567.0` that will be part of the Electron version `14.0.0-beta.18` which I think should be released soon (https://github.com/electron/electron/commit/36226a4e0e76bd74b5eacce4ea8e7ef902d4e3b4).

It may be worth testing this again with the latest `beta`, `alpha` and `nightly` releases.

**Comment by RaisinTen** [comment] 2022-07-15 05:52
https://code.visualstudio.com/updates/v1_69#_electron-18-update tells me that the latest VS Code is on Electron v18 where the fix has included. @mystiquewolf @vially could y'all test it out and let me know if this is still an outstanding issue?

**Comment by mystiquewolf** [comment] 2022-07-15 13:51
It's fixed here.

**Comment by RaisinTen** [comment] 2022-07-15 13:59
Thanks for confirming, closing! :)

**Closed by RaisinTen** 2022-07-15 13:59 UTC
Labels: platform/linux, bug :beetle:, blocked/need-repro, 12-x-y, wayland
