### ISSUE TITLE
Printing not occurring when window is closed

### ISSUE THREAD

**Issue by sameel** [electron/electron#7064] opened 2016-09-02 02:41 UTC
- Electron version: 1.3.4
- Operating system: Windows 10

Ran into an issue where I wanted to call the win.webcontents.print() function then close the window. The issue is that print function isn't completed and the window is closed so the print job isn't getting sent.

```
        window.PrintFile = function(url) {
            const {BrowserWindow} = require('electron').remote;
            let win = new BrowserWindow({show: false});
            win.loadURL(url);
            win.webContents.on('did-finish-load', function(){
                try{
                    console.log(win.webContents.print({silent: true}));
                    send_tray_notification('../dist/img/successIcon.png');
                }
                catch(e){
                    send_tray_notification('../dist/img/errorIcon.png');
                }
              win.close();
            });
        }
```

The tray notification is sent but the window isn't closed. This could mean the printing function would need a promise to let the program know it is done and the print job was sent so we can safely close the window. Without the "win.close()" line, the print job won't be sent and the browserwindow will remain open in the background.

**Comment by zcbenz** [comment] 2016-09-12 06:05
Does your code quit the app when window is closed?

**Comment by sameel** [comment] 2016-09-12 15:02
My app does not quit. It continues to the run. The only thing that gets closed is that temporary browserWindow I created

**Comment by zcbenz** [comment] 2017-05-30 09:36
I'm closing this as won't fix since calling `close` would terminate the renderer process immediately by design, waiting until the work in web page gets done is something that should be done on user's side.

**Closed by zcbenz** 2017-05-30 09:36 UTC
Labels: component/printing, fixme/bug, platform/windows
