### ISSUE TITLE
[Bug]: browserWindow worked well in windows 10, but crashed sometimes in windows 7

### ISSUE THREAD

**Issue by jiangjianping** [electron/electron#28634] opened 2021-04-13 11:43 UTC
[exceptions.txt](https://github.com/electron/electron/files/6303484/exceptions.txt)
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2,11.x

### What operating system are you using?

Windows

### Operating System Version

windows 7

### What arch are you using?

ia32

### Last Known Working Electron version

I do not know

### Expected Behavior

Worked well as windows 10

### Actual Behavior

1. crashed sometimes, not everytime
2. or the same as #28487
3. the contextIsolation is false

**Comment by VerteDinde** [comment] 2021-04-14 22:43
Hey @jiangjianping , thanks for reporting this issue! Unfortunately, without more information or a repro, this is going to be difficult for us to try to pin down and fix.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks so much!

**Comment by jiangjianping** [comment] 2021-04-15 05:19
@vaartis,

I test the electron version 10.x-12.x even with the default_app.asar, this problem or  ##28487 can occur once in a while. I  test it in cmd console in win32 ia32 in win7,running and exit many times, then problem occurred.

**Comment by jiangjianping** [comment] 2021-04-15 08:32
@VerteDinde 
The reason is render process crashed.  disableHardwareAcceleration (no gpu) is better than gpu, but both ecounter the crash very easily under win7.

**Comment by jiangjianping** [comment] 2021-04-15 09:40
the default_app.asar crashed with gpu enabled:
![output](https://user-images.githubusercontent.com/14144270/114848691-894ba200-9e11-11eb-80c6-f56b2abd15a2.PNG)
My app with gpu disabled and render-process-gone catched. the exception stack maybe output
[newexception.txt](https://github.com/electron/electron/files/6316849/newexception.txt)

**Comment by StaZhu** [comment] 2021-06-06 10:14
I have tried remove "ldflags += ["/stack:0x80000"]" which introduced in 11.2.1 for x86 arch cpu, and rebuild the electron. then issue has been completed solved!  just for reference, seems the stack size from 1.5MiB to 0.5MiB causes the issue.

**Comment by nornagon** [comment] 2021-06-22 19:10
Seems like this is a duplicate of #29177 then.

**Closed by nornagon** 2021-06-22 19:10 UTC
Labels: 11-x-y, 12-x-y, bug :beetle:, platform/windows
