### ISSUE TITLE
Electron 6 Main Process can send via Node-IPC but not receive (Worked in 4.1.5)

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#20385] opened 2019-09-30 23:27 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.10
* **Operating System:**
  * Windows 7 / macOS 10.13.6
* **Last Known Working Electron version:**
  * 4.1.5

### Expected Behavior
Electron Main Process should receive incoming `messages` from another process.

### Actual Behavior
Electron Main Process can only send messages, but not receive

### To Reproduce
TBD

### Additional Information
Is there a reason anyone suspects this wouldn't work? I reviewed the changelog meticulously but I don't see anything that seems relevant in either 5.x or 6.x. I see the sandbox is enabled by default, but it seems to only apply to the `renderer` processes and not the `main` as far as I can tell. Currently I haven't a clue what the cause could be, but if any Electron Team dev or anyone else could point me in the right direction I'd appreciate it hugely.

**Comment by lincolnthree** [comment] 2019-10-03 16:10
Could this be related? https://github.com/electron/electron/pull/20214

**Comment by nornagon** [comment] 2019-10-03 18:17
Unfortunately there's not enough information in this issue to be able to understand what the problem is. Please provide a test case that reproduces the issue you're seeing, preferably using [Electron Fiddle](https://github.com/electron/fiddle). Thanks!

**Comment by Slapbox** [comment] 2019-10-03 18:38
@nornagon thanks for taking a look. I'll try to continue to gather information on the issue.

@lincolnthree - I think that's not implemented yet, so probably not, but that seems potentially very helpful for me in terms of digging into the issue further to try to find a cause. Thank you.

**Comment by Slapbox** [comment] 2019-10-03 19:03
It looks like (at least on Windows 7) upgrading my `node` executable to be built with `node@12` works.
Drawbacks:
- Revalidation of functionality on 3 platforms
- Packaging using `pkg` - some users are reporting random freezes in their packaged applications when upgrading from `node@10` to `node@12`

**Comment by lincolnthree** [comment] 2019-10-03 20:32
@Slapbox Glad to help. I am one of those users experiencing crashes on startup / random freezes with node@12 on Electron 6+. I have been trying to put the pieces together but nothing so far. That's what led me here, trying to follow the rabbit hole.

Out of curiosity, since you're updating from the same version of Electron I'm currently working with, I'm assuming you haven't seen any of the crash on startup issues in your packaged app? If you have, any tips to resolve?

**Comment by Slapbox** [comment] 2019-10-03 20:41
Just to clarify, the issue I mentioned with `node@12` is specifically related to [pkg](https://www.npmjs.com/package/pkg)

I strongly suspect that freezes could be caused by this issue. Unfortunately what I suspect is the root cause of the issue is seemingly upstream from Electron, in Chromium itself, introduced in version 76, which `Electron@6` is based on. #20383 - I see similar issues in Chrome as well. It seems to be related to specific machines. On my development machine, Chrome has really turned to crap. On my personal machine, works fine.

**Comment by nornagon** [comment] 2019-10-03 21:50
I'm still not sure what the actual issue is here. Is it something you can reproduce? Is this a duplicate of #20383, or a different issue?

**Comment by Slapbox** [comment] 2019-10-13 20:07
It seems like `app.commandLine.appendSwitch('--no-sandbox');` is required for `Node-IPC` communications to work, even from the `main` process.

@nornagon any thoughts on why that might be? I had thought only the renderer process was affected by this.

**Comment by miniak** [comment] 2019-11-10 16:14
It seems like you are having an issue with a 3rd part module. This need to be reported in their issue tracker instead

**Closed by miniak** 2019-11-10 16:14 UTC
Labels: blocked/need-info ❌
