### ISSUE TITLE
multi-level menu for tray loading too slow

### ISSUE THREAD

**Issue by orangeChu** [electron/electron#16926] opened 2019-02-13 15:02 UTC
* **Electron Version** (output of `node_modules/.bin/electron --version`): 4.0.x also in 3.x.x or older
* **Operating System** (Platform and Version): Windows 7 & Windows 10

### Expected Behavior
The tray menu displays the same speed as normal.

### Actual behavior
Windows 7:
It took almost a second to show up.
Almost impossible to display when the number of menus increases.
macOS 10.14.2:
No difference from the normal menu. There is no problem.

### To Reproduce
[multi-level-menu-for-tray](https://github.com/orangeChu/multi-level-menu-for-tray.git)
[link issue#16156](https://github.com/electron/electron/issues/16156)
[link issue#16413](https://github.com/electron/electron/issues/16413)

### Screenshots
![screen](https://user-images.githubusercontent.com/25950247/51219452-f7bc0400-196b-11e9-866f-9d5e91b06bc1.gif)

### Additional Information
In issue #16413, codebytere is said to be a limitation of the Windows platform, but I use the [`miniblink`](https://github.com/weolar/miniblink49) (more compact, which implements most of the electron functions) to create a tray menu that loads the multi-level menu at a different speed than the normal menu. . So I want to re-create a new problem for loading multi-level menus.
[demo(with miniblink).zip](https://github.com/electron/electron/files/2860844/demo.zip)
Can you please re-emphasize this issue? Thanks.

@codebytere @MarshallOfSound @zcbenz

**Comment by MarshallOfSound** [comment] 2019-02-14 02:38
Hey @orangeChu 

You have raised this issue in #16156 and #16413 and both have been closed, continually raising new duplicate issues is not the way forward here.

The original issue #16156 was closed **correctly** as being a platform limitation (whether this is Chromium's menu implementation or a Windows limitation).  The Menu API is Chromium/Electron is not designed to and will never be intended to support this use case (of a ridiculous quantity of menu items).

I'm going to close this issue out as a duplicate of #16156 and #16413

**Closed by MarshallOfSound** 2019-02-14 02:38 UTC
Labels: 3-0-x, 4-0-x, bug :beetle:, platform/windows

**Comment by orangeChu** [comment] 2019-02-14 06:42
Hi @MarshallOfSound 
Thank you for your patience, maybe I really shouldn't create too many menus that don't work.
