### ISSUE TITLE
Add hardware-media-key-handling disabling option

### ISSUE THREAD

**Issue by luluuu** [electron/electron#21731] opened 2020-01-10 16:30 UTC
---
name: Feature request
about: Add hardware-media-key-handling disabling option

---

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Recently, the hardware-media-key-handling has been enabled by default in chromium, and we do not have the possibility to disable it from electron

### Proposed Solution
Add the hardware-media-key-handling flag to the chrome-command-line-switches list

### Alternatives Considered
Any alternative which results in disabling the hardware-media-key-handling :) No other idea than the proposed solution

### Additional Information
The main problem is on windows 10, when you are reading a video and, for example, change the volume value from the device keybord you have a big black block next to the volume on the screen with the possibility of play/pause/next/prev. I would like to disable this awful thing.

Thanks !

**Comment by thangab** [comment] 2020-01-10 16:39
Do something please !

**Comment by jacobq** [comment] 2020-01-10 16:58
@luluuu Please update this issue so that it matches the ["Feature Request" template](https://github.com/electron/electron/blob/master/.github/ISSUE_TEMPLATE/Feature_request.md). This will help the electron team get to it faster.

**Comment by codebytere** [comment] 2020-01-18 05:53
That feature is exposed as a flag: you can disable it with `--disable-features={flag}` or `--{flag}=0`.

**Comment by luluuu** [comment] 2020-01-20 15:29
@codebytere Hi thanks for your reply but I can't make it work... 
I've tried with the `commandLine.appendSwitch(--disable-features={flag})` (with and without the "--") and even directly launching electron with it `electron --{flag}=0 myEntryPoint.js`. Do I miss something ?

**Comment by codebytere** [comment] 2020-01-20 18:04
you should just need to run `electron --disable-features={flag} /path/to/app`

**Comment by codebytere** [comment] 2020-01-23 06:11
Closing as the above will remedy the issue as confirmed with local testing.

**Closed by codebytere** 2020-01-23 06:11 UTC
Labels: enhancement :sparkles:

**Comment by Pabloitto** [comment] 2020-02-14 16:06
Hey, @codebytere 
So the command should looks like this ? `electron --disable-features=hardware-media-key-handling` ?

Thanks

**Comment by rocka** [comment] 2020-02-21 08:04
@Pabloitto it's `HardwareMediaKeyHandling`, and you can do this with `app.commandLine.appendSwitch`, see https://github.com/electron/electron/issues/18253#issuecomment-589542934 for details

**Comment by Pabloitto** [comment] 2020-02-21 17:27
@rocka awesome, thanks for your answer :)

**Comment by Pabloitto** [comment] 2020-02-21 18:14
@rocka I already tested and works like a charm buddy, thank you 👍

**Comment by luluuu** [comment] 2020-03-03 09:41
Thanks a lot @rocka ! Didn't make it work until your solution

**Comment by fanium** [comment] 2022-12-02 01:24
Thank you, I spent 1 day to reach to here. Please let me use my play/stop button. Please disable Teams "MEDIA KEY SUPPORT"
