### ISSUE TITLE
calling setCertificateVerifyProc cancels requests in an unrelated session with net::ERR_CERT_DATABASE_CHANGED

### ISSUE THREAD

**Issue by jjason685** [electron/electron#25338] opened 2020-09-05 22:39 UTC
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  10.1.1
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**
  *  6.1.10

### Expected Behavior

The request to function normally except the certificate handler works as intended.

### Actual Behavior

When sending concurrent requests at once, the net request throws an error with net::ERR_CERT_DATABASE_CHANGED.

### To Reproduce

session.setCertificateVerifyProc((r, cb) => cb(0));

// Send net requests as normal

Soon enough, the code will start producing the error shown above.

**Comment by 1nfility** [comment] 2020-11-12 00:39
Any update on this? I'm having the same issue.

**Comment by nornagon** [comment] 2020-11-13 22:29
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by jjason685** [comment] 2020-11-14 00:01
Hey @nornagon ,

Sorry for not including this in the main post - I had trouble initially reproducing this out of a closed-source environment, but managed to do so in the following gist.

https://gist.github.com/e068cd996e68ce89b0043fd844d60efd

Thanks for looking into this.

**Comment by nornagon** [comment] 2020-11-14 00:14
@jjason685 in your example, it looks like you're calling `setCertificateVerifyProc` while a request is in flight. Changing the certificate verify proc requires signaling that the certificate database has been updated: https://github.com/electron/electron/blob/bb3fb548d817c101b11ed54af1eb77f3ee7ccc6e/shell/browser/api/electron_api_session.cc#L624. This is required to clear the cert cache, otherwise the new procedure won't be called. Signaling that the certificate database has changed triggers a notification that SSL configuration has changed: https://source.chromium.org/chromium/chromium/src/+/master:net/socket/ssl_client_socket.cc;l=150;drc=3980dd6e559b6d986dd29439ebbe5c9e6b7cb700, and subsequently flushes all open connections with an error: https://source.chromium.org/chromium/chromium/src/+/master:net/socket/transport_client_socket_pool.cc;l=841;drc=3980dd6e559b6d986dd29439ebbe5c9e6b7cb700.

So this is expected behavior from Chrome's network stack. You shouldn't have any trouble if you just call `setCertificateVerifyProc` once, at the beginning of your code, and don't change it thereafter.

I'll close this issue now as it seems things are working as intended, but I'm happy to continue discussion here.

**Comment by jjason685** [comment] 2020-11-14 00:28
@nornagon does this mean that when there are concurrent requests being executed, one can't call setCertVerifyProc on a new session? if this isn't feasible, is there any way we can have a method that exposes the same functionality of setCertVerifyProc, but in a way that doesn't use chromium's method? I remember sifting thru the source of v6 electron (where this worked as intended for our use case) and it was vastly different - we tried rebuilding with the same idea but to no avail.

**Comment by jjason685** [comment] 2020-11-14 21:36
@nornagon alternatively, is there any way to validate and force only legitimate certificates to be used in net requests (essentially preventing self signed certificates)?

**Comment by 1nfility** [comment] 2020-11-14 22:26
@nornagon jjason685's example only calls setCertificateVerifyProc once per session.

**Comment by nornagon** [comment] 2020-11-16 18:28
Ah, sorry, it seems I misunderstood the issue—you're observing that calling `setCertificateVerifyProc` in one session results in canceling requests in an unrelated session. Is that accurate? It does seem like the call to OnCertDBChanged is service-wide, not restricted to a particular context. I'll reopen the issue and retitle it accordingly.

FWIW, `Session` objects, once created, are never deleted, so I'd advise against creating many of them in your app.

**Closed** 2020-11-17 19:12 UTC
Labels: 10-x-y, bug :beetle:, platform/all, status/wontfix 🚫
