### ISSUE TITLE
[Bug]: Fails to remember last save directory between sessions

### ISSUE THREAD

**Issue by EvocativeOlash** [electron/electron#29770] opened 2021-06-18 00:58 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

newest?

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1 19043.1052

### What arch are you using?

x64

### Last Known Working Electron version

NA

### Expected Behavior

Last save directory should be remembered between sessions

### Actual Behavior

Only remembers new save location during current session, Reverts between program restarts

### Additional Information

This issue is seen in Element version: 1.7.30, which apparently inherits this issue from electron

**Comment by nornagon** [comment] 2021-06-18 18:42
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by EvocativeOlash** [comment] 2021-06-29 03:48
Its a problem in the element matrix client.  I reported it there but they said they inherited the issue from this code.

For whatever reason the program remembers the initial file save location after installation and never lets it go.   Its a problem as I upgraded with more storage so no longer have to save to that spinning drive, but the program insists on spinning up that drive to save on each program start anyways, and only remembers the new save location during the current session.

I don't know how to do a test case, so I can only tell you what happened.

**Comment by nornagon** [comment] 2021-06-29 23:49
Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. If we can get a standalone test case for this I'm happy to look into it, but Element is too big of an app for me to spend the time to understand in order to evaluate this report.

I'm going to close this for now as there's no repro, but I'm happy to reopen if we can get a standalone test case.

**Closed by nornagon** 2021-06-29 23:49 UTC
Labels: blocked/need-repro, bug :beetle:
