### ISSUE TITLE
Electron 2.0.x: running with ELECTRON_ENABLE_LOGGING=1 freezes window (Linux)

### ISSUE THREAD

**Issue by bpasero** [electron/electron#12380] opened 2018-03-21 06:42 UTC
* Electron version: 2.0.0-beta.5
* Operating system: Ubuntu 17

### Expected behavior

It should not freeze the window.

### Actual behavior

Window freezes right on startup.

### How to reproduce

* `export ELECTRON_ENABLE_LOGGING=1`
* `./electron`

results in:

![image](https://user-images.githubusercontent.com/900690/37697140-604a81be-2cdb-11e8-8ceb-7bdc4710e9d7.png)

**Comment by bpasero** [comment] 2018-03-21 09:01
Forgot to mention: the freeze does not reproduce when running with `--disable-gpu`

**Comment by zcbenz** [comment] 2018-03-22 05:52
I tested on my Fedora 26 virtual machine, but could not reproduce. I probably need to install Ubuntu 17 to test it.

And are you running Ubuntu 17 on a virtual machine? It is common that Linux virtual machines have problems with hardware rendering.

**Comment by bpasero** [comment] 2018-03-22 06:14
@zcbenz yes forgot to mention, this is running on macOS 10.13.3 in Parallels.

**Comment by ckerr** [comment] 2018-03-26 17:35
I'm not seeing this when running on a native Ubuntu 18.04 install.

![logging-fs8](https://user-images.githubusercontent.com/70381/37922330-e4f1ddd0-30f1-11e8-8c7a-ba1c4a3c73af.png)

I suspect this is a VM issue rather than an Electron issue and so am closing this issue. If this is in error and is something that should be addressed inside Electron, please @ me with more information and I'll be happy to reopen & revisit the issue. Thanks.

**Closed by ckerr** 2018-03-26 17:35 UTC
Labels: platform/linux/ubuntu, triaged/bug :beetle:, version/2.0.x

**Comment by Kagami** [comment] 2018-07-22 00:09
I can reproduce it in electron-quick-start with

```
ELECTRON_ENABLE_LOGGING=1 npm start -- --v=1
```

With `--disable-gpu` it works as expected.

**Comment by Kagami** [comment] 2018-07-22 00:32
Also duplicate of #13624

**Comment by joaomlneto** [comment] 2018-09-24 15:46
May be interesting to note that I had the same problem using different VM software and a different guest OS.

- Hardware: MacBook Pro 15 mid-2015 (with AMD GPU)
- Virtualization Software: VMWare Fusion 10.1.3
- Host: macOS 10.13.6 "High Sierra"
- Guest: Linux Mint 19 "Tara"

**Comment by Exidex** [comment] 2018-10-08 11:39
Having same problem on Manjaro: 
![image](https://user-images.githubusercontent.com/16986685/46606995-8b756d00-caff-11e8-8244-e1fa273fa8bf.png)
