### ISSUE TITLE
Electron 2 app freezes upon launch on macOS 10.14 Beta

### ISSUE THREAD

**Issue by jarek-foksa** [electron/electron#13564] opened 2018-07-05 12:45 UTC
* Electron version: 2.0.4-mas-x64
* Operating System: macOS Mojave 10.14 Beta
* Stack traces: [stack-traces.zip](https://github.com/electron/electron/files/2166543/stack-traces.zip)

**Expected Behavior**

Electron app should not freeze upon launch.

**Actual behavior**

Electron app freezes and becomes unresponsive upon launch.

**To Reproduce**

1. Download "Type Fu" app from the Mac App Store (please drop a message to jarek@type-fu.com to get a promo code).
2. Launch the app.

**Additional Information**

I'm not sure whether this issue is affecting only my app or every Electron-based app on macOS 10.14 and whether it is specific to Electron 2.0.3. I will do further testing when I setup a virtual machine with macOS 10.14 Beta (the current bug report is based on the information I received from one of my users).

**Comment by kode54** [comment] 2018-07-10 01:23
If it uses a global keyboard hook, then it needs to ask for the Accessibility security permission to access that API. Apparently, the program also needs to be restarted after the permission is granted for the API to start working.

**Comment by jarek-foksa** [comment] 2018-07-10 07:05
@kode54 The app is not using `globalShortcut` Electron API, it relies only on the standard DOM keyboard APIs.

**Comment by jakubzitny** [comment] 2018-07-13 12:38
I am having similar problems with Electron, main process crashes at a specific call in my application. I am trying to locate the exact place/cause. I believe [webtorrent](https://github.com/webtorrent/webtorrent-desktop/issues/1421) and [etcher](https://github.com/resin-io/etcher/issues/2404) have similar issues as well (they have multiple related issues on their GH). I tried electron v`2.0.4` and v`1.7.5`. [Here](https://gist.github.com/jakubzitny/c046f4a8f7f5cc08b767f76aeb887f60) is my electron crash log.

I have problems analyzing the system stack traces, so there might be few different causes. But it's definitely related to Mojave (previous beta, and the latest `18A326h` as well).

**Comment by jakubzitny** [comment] 2018-07-13 12:51
Ok, so I managed to find the cause of the problem. I've noticed the [BrowserWindow#setProgressBar()](https://electronjs.org/docs/api/browser-window#winsetprogressbarprogress-options) call in some of the logs. Also the `setDoubleValue` method is called in electron repository only [here](https://github.com/electron/electron/blob/0ec4ad288d52f0eb7b25c664b307c592c057572b/atom/browser/native_window_mac.mm#L1090) which is related to setting the dock icon progress.

**Comment by GaryREM** [comment] 2018-07-21 21:35
Interesting. Was having a problem with the Twitch app crashing under 10.14.

I had an icon saved in the dock. When I removed the icon the crashes stopped. Putting the icon back and everything still worked.

**Comment by ckerr** [comment] 2018-08-10 22:38
This appears to be the same as https://github.com/electron/electron/issues/13751 so I'm going to close this one. If this is in error, please @ me and I'll re-open.

**Closed by ckerr** 2018-08-10 22:38 UTC
Labels: bug :beetle:, platform/macOS, version/2.0.x
