### ISSUE TITLE
Non scrollable TouchBarPopover

### ISSUE THREAD

**Issue by idoodler** [electron/electron#17002] opened 2019-02-16 07:51 UTC
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 3.0.3
* **Operating System** (Platform and Version):
  * macOS 10.14.3
* **Last known working Electron version** (if applicable):
  * Never

### Expected Behavior
Touchbar items should be scrollable in a `TouchBarPopover`

### Actual behavior
Touchbar items are not scrollable and just the first 5 items (depending on the width) are visible.

### To Reproduce
Just add a few `TouchBarButton` items to a `TouchBarPopover`, nothing is scrollable.

<details><summary>Example code</summary>
<p>

#### Just adds 10 `TouchBarButton` to a `TouchBarPopover`

```javascript
const { app, BrowserWindow, TouchBar } = require('electron')

const { TouchBarLabel, TouchBarButton, TouchBarPopover } = TouchBar

const popoverCnt = 10
var popoverItems = [
  new TouchBarLabel({
    label: "You should see " + popoverCnt + " items:"
  })
]
for (var i = 0; i < popoverCnt; i++) {
  popoverItems.push(new TouchBarButton({
    label: "Button " + i
  }))
}

const touchBar = new TouchBar([
  new TouchBarPopover({
    label: "Popover, click here...",
    items: popoverItems
  })
])

let window

app.once('ready', () => {
  window = new BrowserWindow({
    frame: false,
    titleBarStyle: 'hiddenInset',
    width: 200,
    height: 200,
    backgroundColor: '#000'
  })
  window.loadURL('about:blank')
  window.setTouchBar(touchBar)
})
```
1. Save the above file to your computer as `touchbar.js`
2. Install Electron via `npm install electron`
3. Run the example inside Electron: `electron touchbar.js`
</p>
</details>

**Comment by koryhutchison** [comment] 2019-04-16 05:18
I'm having the same issue, but I'm using electron v4.1.4. This is definitely something that should be scrollable. @sofianguy, any idea on when this might be looked at? The app I'm making needs this functionality. Looks like there are a lot of open issues though so I totally get that it'll take time.

**Comment by electron-triage** [comment] 2020-02-19 21:06
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:34
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:34 UTC
Labels: 3-0-x, 4-2-x, blocked/need-info ❌, bug :beetle:, platform/macOS
