### ISSUE TITLE
[Bug]: webContents.capturePage() returns empty image for hidden BrowserWindow on Windows 

### ISSUE THREAD

**Issue by lwj06** [electron/electron#36061] opened 2022-10-18 02:39 UTC
[Bug]: webContents.capturePage() returns empty image for fully occluded BrowserWindow on Windows 
Electron version 20.0.1
windows 10

**Comment by codebytere** [comment] 2022-10-18 14:38
Duplicate of https://github.com/electron/electron/issues/35953

**Closed by codebytere** 2022-10-18 14:38 UTC
