### ISSUE TITLE
[Bug]:  Stuck on a blank screen 

### ISSUE THREAD

**Issue by Gabyxxpower** [electron/electron#32154] opened 2021-12-11 17:37 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

i dont use 

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

idk

### Expected Behavior

Not loading 

### Actual Behavior

Blank grey image

**Comment by LILNUT1** [comment] 2021-12-11 19:27
Any answers for this, happening to me to!

**Comment by DarkFireOG** [comment] 2021-12-12 23:17
Same with me. Once I start this up, the screen just goes completely grey. It still says things like File, Edit, View, etc.

**Comment by kromain** [comment] 2021-12-22 18:22
Assuming you're just using the main branch, this is probably a duplicate of #32169: the reason you see a blank window with just the menu bar is because the renderer process has crashed due to the failing assertion described in the other ticket.

Still no fix to date in either `main` or `17-x-y`, but it will be fixed eventually. Note that these are not stable release branches, I recommend sticking to either official releases or the latest release branch `16-x-y` to avoid these issues.

**Comment by codebytere** [comment] 2022-01-03 14:01
Closing in agreement with above - follow that issue for further progress please!

**Closed by codebytere** 2022-01-03 14:01 UTC
Labels: bug :beetle:
