### ISSUE TITLE
linux build ubuntu icon invalid 

### ISSUE THREAD

**Issue by tkggusraqk** [electron/electron#28350] opened 2021-03-23 14:35 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.2 x64

### What arch are you using?

x64

### Last Known Working Electron version

12.0.1

### Expected Behavior

icon visible

### Actual Behavior

icon is the default

### Testcase Gist URL

https://github.com/tkggusraqk/electron-demo

**Comment by Prinzhorn** [comment] 2021-03-23 15:11
Did you mean to report this to https://github.com/electron-userland/electron-forge/issues ? This is probably the wrong repository. If not then provide clear steps how to reproduce the issue, you only linked to a repository.

**Comment by ckerr** [comment] 2021-03-29 17:22
Thanks for reporting this and helping to make Electron better!

@tkggusraqk is forge required to reproduce this bug?

If this is an Electron bug (e.g. if it can be reproduced using only Electron), would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Because of time constraints, triaging code with dependencies on another project is usually not feasible for a small team like Electron's.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2021-05-05 14:59
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2021-05-05 14:59 UTC
Labels: 12-x-y, blocked/need-info ❌, bug :beetle:
