### ISSUE TITLE
Widevine version 1.4.8.903 not working with Electron 1.4.4-1

### ISSUE THREAD

**Issue by godlikemouse** [electron/electron#7865] opened 2016-11-03 19:17 UTC
* Electron version: 1.4.4-1
* Operating system: Arch Linux x86_64

I've tried everything I could find to get Widevine working in Electron however, no matter what I try neither DRM Test (http://www.dash-player.com/demo/drm-test-area/) nor Shaka Player (https://shaka-player-demo.appspot.com/demo/) will work.  I've verified that the plugins are loaded via navigator.plugins as I've added the appropriate appendSwitches to the app.commandLine object and ensured that plugins are enabled.  I've also tried loading ppapi and register-pepper-plugins with still no luck.  Any help here would be greatly appreciated, thanks.

**Comment by godlikemouse** [comment] 2016-11-03 19:21
As a follow up, both versions of Chrome and Electron match up.  The above DRM and Shaka Player sites work just fine in Chrome, but Electron won't enable nor play Widevine content.

**Comment by joshuabenuck** [comment] 2016-11-05 03:40
Have you verified that your Chrome and Electron installs are both 32-bit or 64-bit? I just realized that my Chrome install was 32-bit while "npm install electron" defaulted to 64-bit since I'm on a 64-bit system. Chrome is 32-bit unless it mentions 64-bit in its version string, For example, Chrome's About page should show a version like: Version 54.0.2840.87 m (64-bit).

Try running 'file' on your browsers and the widevine .so's to make sure they are built for the same arch. I'm on Windows and that's what tipped me off.

Output from 'file' before and after the switch:

> widevinecdm.dll: PE32 executable (DLL) (console) Intel 80386, for MS Windows
> widevinecdm.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows

Upgrading Chrome to 64-bit, loading some DRM content (Netflix in my case), and then copying over the updated widevine DLLs fixed it for me. Prior to this I could not get widevine or flash content to load.

Worked for me using both Electron 1.4.2 and 1.4.5 using Widevine 1.4.8.903 under Windows 10.

If you would prefer to switch Electron to 32-bit, try "npm install -g --arch=ia32 electron". That was going to be my next attempt if I had trouble switching to 64-bit Chrome.

**Comment by godlikemouse** [comment] 2016-11-05 14:52
Thanks for the info however, on my machine both Chrome and Electron are 64bit.  I checked libwidevinecdmadapter.so and libwidevinecdm.so and both are 64bit as well.

**Comment by njbmartin** [comment] 2016-11-11 13:23
Also facing the same issue. However the workaround in #6516 does trigger the plugin to load for me. Seems that the plugin isn't being loaded correctly.

**Comment by zcbenz** [comment] 2016-11-17 01:28
Closing since it seems to be a duplicate of #6516.

**Closed by zcbenz** 2016-11-17 01:28 UTC

**Comment by godlikemouse** [comment] 2016-11-17 21:08
I don't want to necro bump this thread, but just want to say thanks to njbmartin for the response however, I didn't work for me.  I'll continue to try and find help and answers in #6516.
