### ISSUE TITLE
`--remote-debugging-port` doesn't work since 1.6.11

### ISSUE THREAD

**Issue by develar** [electron/electron#10445] opened 2017-09-05 16:16 UTC
`--remote-debugging-port` is used to debug renderer process in the IDE.

It works in the Electron `1.5.1`, but doesn't work in the 1.6.11+ (I have checked 1.6.11, 1.7.5 and 1.8.0).

Project — https://github.com/develar/__debug_electron-quick-start

Change electron version in the `package.json` from `"1.5.1"` to `"1.6.11"` to reproduce — WebStorm/VSCode cannot connect to localhost:9222

Debug works only if add `app.commandLine.appendSwitch('remote-debugging-port', '9222')` to `main.js`

Is it regression or intended change?

**Comment by MarshallOfSound** [comment] 2017-09-06 02:15
I know in `1.7+` the debugging technique changed to use new new `--inspect` and that's how I debug things through VS Code now, might be worth playing with that?

**Comment by develar** [comment] 2017-09-06 08:28
@MarshallOfSound `--inspect` is used to debug main process, `--remote-debugging-port` to debug renderer.

**Comment by ramya-rao-a** [comment] 2017-11-30 00:18
What about the case when there are multiple renderers?

**Comment by sofianguy** [comment] 2017-12-03 02:10
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by develar** [comment] 2017-12-03 07:28
@sofianguy it is bug and not a question ;)

**Comment by sofianguy** [comment] 2017-12-06 22:41
@develar my bad, reopening

**Comment by hatpick** [comment] 2018-04-24 03:05
Any update on this? Adding the following on main configuration has no effect.
```
"runtimeArgs": [        
   "--remote-debugging-port=9222"
 ]
```

**Comment by prigara** [comment] 2018-08-21 12:55
Hey, @MarshallOfSound! I'm from the WebStorm team. I can confirm that the debug flag now works correctly with Electron 2.0.7 and 3.0.0-beta.6. Thanks for looking into it and getting back to us on Twitter!

**Comment by MarshallOfSound** [comment] 2018-08-21 15:16
@prigara No problem, good to hear it's cleared itself up.  I'm going to leave this open so I can write some tests to make sure this doesn't break in the future but at least we know it's working as expected now :)

**Comment by natew** [comment] 2018-09-05 01:58
@MarshallOfSound this seems to have regressed for me. I'm actually getting a timeout for some reason. I tired electron 3.0.0 beta 3, 5, and 8.

It was working before, but suddenly stopped. It's odd it will actually hang for a while and then timeout:

```
 ETIMEDOUT 127.0.0.1:9002 FetchError: request to http://127.0.0.1:9002/json failed, reason: connect ETIMEDOUT 127.0.0.1:9002
```

Using node 9.11.2. I haven't seen anyone log a timeout issue, should I open a new ticket?

**Comment by MarshallOfSound** [comment] 2018-09-05 05:11
> It was working before, but suddenly stopped. It's odd it will actually hang for a while and then timeout:

Sounds like you have some phantom processes hanging around with a claim on the debugger ports still.  Do a clean restart and try again, especially if it was working before 👍

**Comment by natew** [comment] 2018-09-05 16:06
I actually have a specific kill-port 9002 running before I run electron.
Would that not ensure it’s fine? Any other way to programmatically ensure
it’s clear?

**Comment by mihe** [comment] 2019-05-28 12:05
So I just gave Electron 6.0.0-beta.4 a try, and it seems this issue has been fixed there. I can now start Electron with `--remote-debugging-port=9222` in a VS Code launch configuration, which wasn't possible with Electron 5.

**Comment by natew** [comment] 2019-06-05 16:08
I can confirm electron 6 beta 3 seems to have fixed it, which is a huge help for us. Thank you.

**Comment by MarshallOfSound** [comment] 2019-06-05 23:47
Closing this out as I've been using `--remote-debugging-port` for a _looonngggg_ time (since the days of 3.x and it's been working for me.  + reports above that others have it working

**Closed by MarshallOfSound** 2019-06-05 23:47 UTC
Labels: 3-0-x, bug :beetle:
