### ISSUE TITLE
Flash SWF content not correctly loaded in Electron 7

### ISSUE THREAD

**Issue by frankieta** [electron/electron#20744] opened 2019-10-25 15:07 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * 6.1.2

### Expected Behavior
Loading flash content through an swf file results in the correct visualization of said content

### Actual Behavior
An error "GET http://interactive-mirror3.nfb.ca/FrameLoader.swf net::ERR_INVALID_ARGUMENT" appears:

![Annotazione 2019-10-25 170420](https://user-images.githubusercontent.com/6009920/67582177-8a829e00-f749-11e9-8e0d-1d08c4930084.png)

### To Reproduce
Try embedding this flash website in an electron project (http://bear71.nfb.ca/#/bear71) following this tutorial: https://electronjs.org/docs/tutorial/using-pepper-flash-plugin

### Screenshots
![Annotazione 2019-10-25 170420](https://user-images.githubusercontent.com/6009920/67582177-8a829e00-f749-11e9-8e0d-1d08c4930084.png)

**Comment by GhostlyDark** [comment] 2019-10-26 14:33
Introduced with v7.0.0-beta.4

**Comment by georgelesica-wf** [comment] 2019-11-06 22:06
This also seems to manifest on Mac.

**Comment by ncodeyx** [comment] 2019-11-17 23:03
Confirmed on Windows and Mac.

**Comment by misbeliever** [comment] 2019-11-20 08:54
Same in 7.1.2 :(

**Comment by eric-zhangqi** [comment] 2019-11-22 10:10
some in 7.1.2  not in 6.0.7

**Comment by misbeliever** [comment] 2019-11-26 11:46
Same in 8.0.0-beta.3

**Comment by lovoror** [comment] 2019-11-28 02:23
Same in 8.0.0-beta.3 and  7.1.2

**Comment by kkannan-carecloud** [comment] 2019-12-06 23:04
Anyone here know which version of electron supports flash in MacOS ?

**Comment by Rosslington** [comment] 2019-12-08 15:47
This is also still broken in 7.1.3

**Comment by kkannan-carecloud** [comment] 2019-12-09 15:52
If someone here is looking for the last version known to work with flash, it will be 6.1.2

**Comment by GhostlyDark** [comment] 2019-12-09 18:00
Anything before v7 works. v7 and after are broken, since the bug was patched into master. If I had to take a guess, it is one of the features introduced by v7.0.0-beta.4

It would be awesome if somebody could confirm what PR caused this. I suspect #18671 since the error is a network error and that PR was backported to v7 released with beta 4.

**Comment by Tackyou** [comment] 2019-12-12 20:30
The last version it works with is 7.0.0-beta.3, in beta.4 they updated chromium which broke it. I also noticed that it works using pepperflash version 32.0.0.270, but when using the newer version 32.0.0.303 it does not. Maybe this has to do with the push to disable flash by default? Having a workaround for electron would be great though.

**Comment by GhostlyDark** [comment] 2019-12-15 23:32
Could that Chromium commit be the cause?
https://chromium.googlesource.com/chromium/src/+/e3e480e63aca01cc7d3c0be286b7721a63cbe1d3

**Comment by GhostlyDark** [comment] 2019-12-16 15:51
Using flash version 32.0.0.270 does not work.

**Comment by t57ser** [comment] 2019-12-17 07:45
> 
> 
> Using flash version 32.0.0.270 does not work.

Can confirm, I also tried and it did not work

**Comment by Tackyou** [comment] 2019-12-17 12:17
Did you use 7.0.0-beta3 ?
Any higher version doesn’t work no mattter which pepperflash version.

**Comment by GhostlyDark** [comment] 2019-12-17 13:07
7.0.0-beta.3 and earlier will work with pretty much any flash version, including 32.0.0.303.

**Comment by fp07** [comment] 2019-12-26 20:11
Any updates? Workaround? The last working version is 6.1.2 for flash 32.0.0.238.

**Comment by Tackyou** [comment] 2019-12-29 08:53
> 7.0.0-beta.3 and earlier will work with pretty much any flash version, including 32.0.0.303.
You're right there was a mistake in my code.

**Comment by fp07** [comment] 2020-01-06 17:45
Updates?

**Comment by lkonstantinov** [comment] 2020-01-07 15:34
The problem has nothing to do with the sandboxing problem suggested in #20309. It is actually caused by a bad header :)

Chromium added more complex CORS handling that required consumers (like Electron) to register list of 'safe' headers that are exempt from the CORS process. One such header is X-Requested-With which is injected by the Flash plugin.

Since that change is missing in Electron, the CORS handler is rejecting the request (because it has an unrecognized header) and you get the `net::ERR_INVALID_ARGUMENT` error.

The fix is to amend `SystemNetworkContextManager::CreateDefaultNetworkContextParams()` in `electron\shell\browser\net\system_network_context_manager.cc` to reflect the `chrome\browser\net` version by adding (with the corresponding includes):

```
  content::UpdateCorsExemptHeader(network_context_params.get());
  variations::UpdateCorsExemptHeaderForVariations(network_context_params.get());
```

For more info - check out the relevant Chromium ticket - https://bugs.chromium.org/p/chromium/issues/detail?id=940331

**Comment by Tinysymphony** [comment] 2020-01-14 17:49
Same in 7.1.7

**Comment by JeimeRhee** [comment] 2020-01-15 06:09
Same in v7.1.9

**Comment by JeimeRhee** [comment] 2020-01-17 03:29
I edited electron "system_network_context_manager.cc" as @lkonstantinov said and electron build succeed.

I want to testing this electron module embedding on my local project, but I don't know how to change modified electron module to local npm packages...

Can anyone help me?

**Comment by lkonstantinov** [comment] 2020-01-17 05:38
@JeimeRhee - you can repack electron (instructions are on the build page here - https://electronjs.org/docs/development/build-instructions-gn ) and then just replace it I guess.

**Comment by t57ser** [comment] 2020-01-20 09:00
@JeimeRhee you don't need to use it as an npm module, you can use the build version in /out and just modify the asar. Use:
`npx asar unpack default_app.asar some_folder_name`
modify the files and pack it again via:
`npx asar pack some_folder_name default_app.asar`

I managed to build it on linux but turns out it doesn't work on linux (master). Flash does not work when sandbox is enabled so it needs to be disabled via `app.commandLine.appendSwitch('no-sandbox')` but then nothing works anymore... (unrelated to flash).

**Comment by JeimeRhee** [comment] 2020-01-23 07:45
@lkonstantinov  Thx for reply. I'm sorry to late checked your reply.
I already read build instruction and try to packaging but when I execute
  ninja -C out/Release electron:electron_dist_zip
it always print out "ninja no work to do." messages...
My build environment is Windows 10 is that command only working on linux environment?

**Comment by fp07** [comment] 2020-01-23 21:48
Someone an tutorial how to apply the fix?

**Comment by kyle-mcknight** [comment] 2020-01-29 19:45
Why a tutorial on how to apply a fix rather than a fix being committed?

**Comment by kyle-mcknight** [comment] 2020-01-29 19:47
This does work in Electron 6.1.7 (32bit at least).

**Comment by andreieftimie** [comment] 2020-01-31 14:23
Can this be prioritized for a fix?

**Comment by fp07** [comment] 2020-02-05 20:01
> Can this be prioritized for a fix?
> 
> We're reverting to Electron 6 as our app still requires flash for some (old) functionality which we can't yet deprecate.

Indeed

**Comment by t57ser** [comment] 2020-02-06 19:08
I've managed to build this locally and can confirm the fix is working. If anyone needs to fix this manually before it gets released you can check out the pull request (https://github.com/electron/electron/pull/22072) for the required changes.

**Closed** 2020-02-09 01:50 UTC
Labels: 7-1-x, bug :beetle:, platform/windows
