### ISSUE TITLE
[Bug]: `desktopCapturer` thumbnails not respecting `thumbnailSize`, always low-res (29.3.2)

### ISSUE THREAD

**Issue by Galkon** [electron/electron#42032] opened 2024-05-03 17:55 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.3.2

### What operating system are you using?

macOS

### Operating System Version

Sonoma 14.4.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

28.3.1

### Expected Behavior

Using the `desktopCapturer` API to capture a screen's thumbnail respects the `thumbnailSize` provided and when providing a thumbnailSize equivalent to the display width or height provides a full resolution thumbnail.

https://github.com/electron/electron/assets/1406556/17e2043f-a7f6-4480-8f39-d73ee84daf9f

### Actual Behavior

Instead, on 29.3.2, the thumbnail is always a low-resolution image scaled up to the specified `thumbnailSize`.

https://github.com/electron/electron/assets/1406556/e44b3a9e-31cd-448f-9fa7-6001fd8c76dc

### Testcase Gist URL

https://gist.github.com/Galkon/18fcba517464f6c1f09d79ce083c898a

### Additional Information
Appears to be fixed in 30.x and 31 alpha

**Comment by codebytere** [comment] 2024-05-06 18:05
Duplicate of https://github.com/electron/electron/issues/41630

**Closed by codebytere** 2024-05-06 18:05 UTC
Labels: platform/macOS, bug :beetle:, component/desktopcapturer, 29-x-y
