### ISSUE TITLE
Black screen with an Nvidia GPU

### ISSUE THREAD

**Issue by Jerska** [electron/electron#4380] opened 2016-02-05 18:34 UTC
Hi there,

I've recently forced my computer to always use my GPU instead of automatically choosing between the chipset and the GPU.
When I did that, the Slack application started rendering only a black window.
I've submitted a bug report to Slack and Nvidia.

Then I discovered the webview engine for Slack is `electron`, so to confirm my thoughts, I went ahead and downloaded `Atom`: same issue.

![Imgur](http://i.imgur.com/0U4bOnc.png)

I'm using the latest Nvidia drivers, so I'm unsure if it comes from them or `electron` which is why I've submitted the bug report at both places.

Information:
- Electron version : Unknown, the one used in latest released Atom and Slack
- OS: Windows 10
- GPU: GTX 870M

**Comment by zcbenz** [comment] 2016-02-15 04:15
Does Chrome browser have the same problem?

**Comment by CharlieHess** [comment] 2016-02-24 20:50
We have a couple more users hitting this. It's not exclusive to Nvidia as this user had a Matrox GPU: [DxDiag.txt](https://github.com/atom/electron/files/145392/DxDiag.1.txt).

Furthermore, starting the Slack app with the `--disable-gpu` argument fixes the issue.

**Comment by PetrJuricaProfiq** [comment] 2016-03-03 14:00
Same thing happened to us on Windows 7 with AMD card.

**Comment by ndoeberlein** [comment] 2016-03-03 16:16
We have found that with the Matrox GPUs, the update.exe app is actually the culprit.  --disable-gpu does not have any effect and still shows the black screen. 

Changing the shortcut target from the default 
`C:\Users\xxx\AppData\Local\slack\Update.exe --processStart slack.exe --disable-gpu` 
to 
`C:\Users\xxx\AppData\Local\slack\app-2.0.0\slack.exe --disable-gpu`

Solved the issue for us.  We also had the best luck disabling "Launch app on login"

**Comment by CharlieHess** [comment] 2016-03-09 22:37
@ndoeberlein: Update.exe supports passing arguments, try this instead:
```
C:\Users\xxx\AppData\Local\slack\Update.exe --processStart slack.exe --process-start-args --disable-gpu
```

**Comment by petrfelzmann** [comment] 2016-03-11 11:05
We also have several customers who suffers from this issue.

**Comment by petrfelzmann** [comment] 2016-03-14 07:33
One configuration reported is
Windows 7 64b, ATI Radeon HD 5670

**Comment by avoidwork** [comment] 2016-03-14 13:49
Hi,

I've come across this many times over the last few months of building an electron app. When I run the app in a Windows 7 VM with the following settings the window goes black after the app writes to disk (repeatable; sometimes the whole window, sometimes just a part during a reflow). For me, it's always on a DOM reflow.

#### settings
<img width="772" alt="screen shot 2016-03-14 at 9 44 35 am" src="https://cloud.githubusercontent.com/assets/369698/13746389/a8a29f5c-e9c9-11e5-88fe-dd44870d8173.png">

#### initial load (spinner is implying over the wire retrieval)
<img width="1632" alt="screen shot 2016-03-14 at 9 45 52 am" src="https://cloud.githubusercontent.com/assets/369698/13746408/bc7ec28a-e9c9-11e5-8b38-aa42627d56d4.png">

#### when the spinner goes away & reflows, the view breaks
<img width="1632" alt="screen shot 2016-03-14 at 9 46 00 am" src="https://cloud.githubusercontent.com/assets/369698/13746436/d76df156-e9c9-11e5-839a-e1a435200338.png">

I originally assumed this was just an issue with the gpu being virtualized, but a small user base is reporting similar problems.

**Comment by avoidwork** [comment] 2016-03-14 13:51
The VM I'm using is from https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/

The machine I'm using is does have an nvidia gpu:

<img width="698" alt="screen shot 2016-03-14 at 9 50 59 am" src="https://cloud.githubusercontent.com/assets/369698/13746545/4a55a790-e9ca-11e5-9fdc-5d5506eea1db.png">

**Comment by CharlieHess** [comment] 2016-03-16 17:13
Windows 7 + AMD Radeon X series; Chrome 49 didn't make a difference. :disappointed: 

![](https://slack.zendesk.com/attachments/token/xgpS6vLMPcNRfNSnIBlpkOfEt/?name=GPUtestSlack.PNG).

**Comment by petrvecera** [comment] 2016-03-17 09:03
Interesting note: We are seeing this issue on machine which have both Windows 7 and Windows 8 in dual boot. (AMD graphic card) 
Windows 7 - error (black screen)
Windows 8 - everything OK

So this might be caused by specific HW/SW configuration.
Also we have quite a lot of users reporting this issue to us. Mostly from W7.

**Comment by avoidwork** [comment] 2016-03-17 10:38
I only see the issue in a Win7 VM; I move to 8 & 10 for dev.

**Comment by pavelzaruba** [comment] 2016-03-17 11:46
The black screen appears after downloading a big file on Windows 32 bit as well. It might be a memory problem, accessing an array out of bounds, etc.

https://github.com/atom/electron/issues/4814

**Comment by pavelzaruba** [comment] 2016-03-17 11:49
There are more black screen bugs out there, e.g.: https://github.com/atom/electron/issues/4828.

**Comment by petrvecera** [comment] 2016-03-18 16:40
@zcbenz You asked if there is the same problem also in chrome so I looked into it.
Google Chrome also suffered from this issue but hey fixed it.
https://productforums.google.com/forum/#!msg/chrome/E6auRoL3p3w/ftSy9a8y8gIJ

The users are reporting that launching with these params fixed the issue. 
`--disable-gpu` or
`--disable-d3d11`

So I looked how they solved it. When I launch the Chrome on the W7 system where Electron works without any problem the Chrome has just normal parameters. 

But when I launch Chrome on W7 system where Chrome works, Electron not. **The Chrome is launched automatically with param --disable-d3d11 !!**

The whole command on the affect computer looks like this:
`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --type=gpu-process --channel="4348.0.1693403075\1912414666" --disable-d3d11 --supports-dual-gpus=false --gpu-driver-bug-workarounds=3,9,11,16,25,54 --gpu-vendor-id=0x1002 --gpu-device-id=0x0000 --gpu-driver-vendor="Advanced Micro Devices, Inc." --gpu-driver-version=15.200.1062.1004 --ignored=" --type=renderer " /prefetch:2`

**Comment by CharlieHess** [comment] 2016-03-18 19:21
@zcbenz: Is there any way we could tap into the abundance of [GPU information](https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/gpu/gpu_data_manager_impl.cc&sq=package:chromium&type=cs) Chrome is collecting, and potentially reuse the same command-line arguments within Electron? Seems like this would resolve a number of rendering glitches.

**Comment by frenchbread** [comment] 2016-03-23 03:16
Same issue here. 

App build on OSX 10.11 works smoothly. 

When running same app's build for `win32` on Windows 10 (on Virtual Box VM) also works fine. Black screen appears sometimes after `dialog.showSaveDialog` has been opened. (In my case only when `showSaveDialog` window is opened)

**Comment by zcbenz** [comment] 2016-03-27 13:53
Chromium ships with a blacklist for GPU drivers and models, and should be able to disable GPU for troubling machines, somehow it is not working.

**Comment by paulcbetts** [comment] 2016-03-27 18:19
@zcbenz It seems at least some of this code lives in the browser process, https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/gpu/three_d_api_observer.cc&sq=package:chromium&type=cs et al

**Comment by petrvecera** [comment] 2016-03-28 20:13
Unfortunately I don't have reproducible environment anymore. But our users are reporting that they didn't have a problem with version 0.36.1 - so it means that the automatic gpu disable most likely worked before.

Could anyone confirm this and perhaps found the exact version when the issue started?

**Comment by frenchbread** [comment] 2016-03-29 10:49
@petrvecera For me it was `v0.36.0`, then I've jumped straight to `v0.37.2` which seems not to have this issue.

**Comment by petrbrzek** [comment] 2016-07-05 11:37
Still happening in Electron 1.2.1. The `--disable-gpu` flag helped one of our customers.

**Comment by creshal** [comment] 2016-09-05 09:46
Still happening on 1.3.4, Win 7 x64, and an Intel GPU (Sandy Bridge, IIRC). `--disable-gpu` didn't help, disabling Aero did.

**Comment by NigelClarkExient** [comment] 2016-10-17 15:09
Looks like this is still an issue on Win10 x64.
![screengrap rocketchat](https://cloud.githubusercontent.com/assets/9834106/19443275/24966af2-9484-11e6-925e-0234c0efa30b.PNG)

**Comment by rainfarmer** [comment] 2016-10-26 23:19
This worked for me:

"C:\Users\xxx\AppData\Local\slack\Update.exe --processStart slack.exe" --disable-gpu 
to 
"C:\Users\xxx\AppData\Local\slack\app-2.0.0\slack.exe" --disable-gpu

Also worked for my Postman app which had the same issue

**Comment by armand1m** [comment] 2016-12-14 12:45
Having the same issue with Hyper Terminal using a Windows 7 VHD in my work. When trying to start the app it just suddenly shows a black screen and keeps some weird behavior that doesn't allow me to do a single thing

## this issue was my salvation

I just needed to change the shortcut target from the default:
`C:\Users\xxx\AppData\Local\hyper\Update.exe" --processStart "Hyper.exe`
to
`C:\Users\xxx\AppData\Local\hyper\app-1.0.0\Hyper.exe --disable-gpu --disable-d3d11`

Then the application spinned up as it would normally do ;)

**Comment by jeekajoo** [comment] 2017-01-19 14:26
`--disable-gpu` fixes it for me with `slack` on linux with `01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Venus XT [Radeon HD 8870M / R9 M270X/M370X] (rev ff)`
Webview rendering issues happen with google signin password challenge. cc @slackhq 
When it happens, I have a white screen.

**Comment by eyurtsev** [comment] 2017-02-13 13:37
black screen when running ubuntu 16.04.01 LTS on a virtual machine under OS X El Capitan

--disable-gpu doesn't help (i typically do have to run chrome with --disable-gpu)

**Comment by Brusalk** [comment] 2017-02-17 04:33
I'm also seeing this with VS Code (https://github.com/Microsoft/vscode/issues/10091) running Ubuntu 16.10 on a Windows host via Virtualbox.

**Comment by drumboog** [comment] 2017-03-16 16:06
Has the disable-d3d11 option always been available in electron?  We were getting reports of this issue and tried disable-d3d11 with version 0.33.6 of electron.  It did not help, but we have since updated to version 1.4.15 (without disable-d3d11).  We still get reports of the issue; would trying disable-d3d11 again have a different impact in the newer version?

**Comment by paul321** [comment] 2017-04-02 15:36
We have the same issue with Electron 1.6.3, the window goes white for some of our users.

**Comment by zinkkrysty** [comment] 2017-04-20 06:57
This issue is the same as in https://bugs.chromium.org/p/chromium/issues/detail?id=661596

I fixed it in my browser by disabling graphics blacklist (I used the flag --ignore-gpu-blacklist). I don't know how to do this in Electron apps (Slack, Atom).


For me the issue happens every time I connect/disconnect an external screen (because it switches from integrated graphics to dedicated)


Using MacBook Pro Early 2011 model with dedicated graphics (although the blacklisted model is the integrated card - Intel HD 3000)

**Comment by Insood** [comment] 2017-04-21 19:04
Just started having this issue today w/ Slack.

Win 10 pro, 64-bit. Running a quadro M2000M with 377.11 drivers.

**Comment by VivaLosDoyers** [comment] 2017-05-12 03:58
@zinkkrysty I have the same laptop, and the same issue with Slack.

**Comment by davidjkrause** [comment] 2017-07-23 19:49
FWIW, a personal Electron app I have was exhibiting a black screen 100% of the time for the main window on an OpenSUSE Linux machine with NVidia graphics.  Upgraded to Electron v1.7.5 beta, and the black screen issue is resolved.  Version 1.7.x of Electron picks up Chrome v58.  The Chromium bug referenced above by @zinkkrysty was marked as resolved in Chrome v57.

**Comment by purefan** [comment] 2017-08-25 09:29
Im seeing partial black outs on apps (for example Slack and VSCode) running on Ubuntu, when hovering over some items that display a tooltip, the tooltip displays maybe a few characters and the rest is blacked out

**Comment by akayami** [comment] 2017-09-15 16:14
Hi, 

I'm on linux, and I have observed the following. 

Slack (and chrome) work fine, when the machine is booted freshly. However, if I suspend it and wake it up, both chrome and slack do not work (chromium on the other hand is fine). I have tested slack, and running it with --disable-gpu fixes the issue. 

The problem is recent. It used to work fine. I have changed my nvidia drivers to nouveau recently. When I have a bit of time, I'll try to switch back to nvidia drivers and see if the issue persist.

**Comment by 2E0PGS** [comment] 2018-01-08 02:17
`--disable-gpu` works for me on applications using electron running inside virtual box (KVM mode).

**Comment by sizijee** [comment] 2018-01-30 20:08
For Windows 10  Users
Steps
1. Navigate to C:\Users\\{username}\AppData\Local\slack\app-{version}\slack.exe
2. Select properties 
3. Select compatibility tab
4. Select compatibility mode  windows 8
5. Launch slack

![image](https://user-images.githubusercontent.com/22740294/35588609-05c92570-05b6-11e8-8e28-1564b62c2b39.png)

**Comment by colibrae** [comment] 2018-02-23 14:52
I can confirm --disable-gpu fixed the problem also, and I have Nvidia driver 390.25. it's pretty much an intolerable problem, and cpu rendering is woeful, so I will try a different Nvidia driver version.

**Comment by perlun** [comment] 2018-08-29 09:47
@akayami I am seeing the exact same problem as you - all Chromium-based apps (Chrome, Slack, Spotify) dies on suspend. I also have an nVidia card and the nouveau drivers are not an option for me unfortunately, so `--disable-gpu` might be the workaround for now.

**Comment by mariorodriguespt** [comment] 2019-01-21 19:23
This issue is annoying.
After opening my laptop lid, every Electron based app crashes. Sometimes it's a black screen, sometime the app stills runs but fails to render the UI correctly.

Google Chrome works fine without any issue.
Screenshot of vscode:
![screenshot from 2019-01-21 19-20-13](https://user-images.githubusercontent.com/1017581/51494737-aec3df80-1db1-11e9-8633-4cc59cf75dbd.png)

in case you're wondering: The entire UI doesn't work, I can not open a file on even scroll. Only fix is to reopen the app again.

**Comment by ArfyFR** [comment] 2019-06-11 07:47
Hi,
For information, I face the same after upgrading video drivers @Home or @Work with some electron clients like
- Visual studio code in the console
- Hyper console
- Mudlet client
after a video driver update.

**Usually NVIDIA GPU update.**
But this morning on my DELL XPS 15 9570 also with the Intel video driver update.

**Comment by gengshenghong** [comment] 2020-03-03 09:19
Any update/fix on this issue (except disable gpu fully always)? I've also got black screen in Windows 7 installed in Parralls Desktop in MacBook air, with 3D accelerator off, it works. Also, when I am using VirtualBox with the same Windows 7 image, it work with/without 3D accelerator. Chrome always work in the same VM.

Thanks,
Shenghong

**Comment by gengshenghong** [comment] 2020-03-03 10:25
I even tried to add code "app.commandLine.appendSwitch('--disable-gpu');" in Electron, but it still got black screen?? Any idea?

Thanks,
Shenghong

**Comment by gengshenghong** [comment] 2020-03-03 10:57
In the same VM, using Chrome, "chrome://gpu" show 3D accelerator is enabled. Why does Electron not support?

**Comment by Nikit-Singh** [comment] 2020-04-30 15:12
Not a black screen issue but this issue keeps happening with electron based apps on my windows machine with Nvidia GPU
![Error](https://user-images.githubusercontent.com/31632952/80727229-10c9d380-8b23-11ea-86a6-95d78deed063.png)

**Comment by teebu** [comment] 2020-06-26 23:39
My VS Code also having issues, when I have a lot of tabs open in chrome. Whole computer goes black after a few minutes I can recover but, VS freezes, all chrome windows go black. When hardware acceleration is enabled.

**Comment by BacnNguyen** [comment] 2020-09-29 11:31
I have the same problem with VS on my PC. I have a GTX card and driver but no monitor. Then I connected to a monitor. It worked fine. Maybe VS needs displayed in a monitor and have GPU/CPU. Hope this help

**Comment by adespawn** [comment] 2020-11-25 11:03
I have similar problems with electron apps on my computer with my Nvidia Gpu in linux after booting up from hibernation

**Comment by electron-triage** [comment] 2021-03-10 21:08
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Closed by electron-triage** 2021-03-10 21:08 UTC
Labels: bug :beetle:, platform/windows
