### ISSUE TITLE
BrowserWindow isVisibile not returning accurate state in Windows 10 for minimize

### ISSUE THREAD

**Issue by Miker87** [electron/electron#17540] opened 2019-03-25 19:42 UTC
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
The issue is similar to this Mac specific issue [https://github.com/electron/electron/issues/16776](https://github.com/electron/electron/issues/16776).  I thought I'd open this in case the fix for that issue does not cover Windows.

I've noticed that on Windows, Electron's `isVisible` method always returns true when minimizing the window.

* **Electron Version:**
  * 4.1.1
* **Operating System:**
  * Windows 10 (10240) VM
* **Last Known Working Electron version:**:
  * Not sure

### Expected Behavior

 The [BrowserWindow.isVisible](https://electronjs.org/docs/api/browser-window#winisvisible) documentation specifies that the `isVisible` method should return whether the window is currently visible to the user.  When minimizing the window on Mac, I can see that the visibility is false.  I would expect the same behaviour on Windows.

### Actual Behavior

I noticed when running the [electron quick start](https://github.com/electron/electron-quick-start) that `isVisible` returned true when minimizing the window.

### To Reproduce

Fork
https://github.com/Miker87/electron-quick-start
```sh
$ git clone git@github.com:Miker87/electron-quick-start.git
$ npm install
$ npm start.
```

The actual modifications in `main.js`
```javascript
const events = ['blur', 'focus', 'hide', 'maximize', 'minimize', 'restore', 'show']

events.forEach(_event => {
  mainWindow.on(_event, () => console.log(_event, mainWindow.isVisible()));
});
```
- Ran the project with `npm start`
- Minimized the window and observed the cmd window's output

### Screenshots

![screen_shot_2019-03-22_at_1 07 56_pm](https://user-images.githubusercontent.com/4311414/54947038-c3d30100-4f0f-11e9-8970-4ca1609c6217.png)

**Comment by electron-triage** [comment] 2020-02-19 20:49
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:32
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by erickzhao** [comment] 2021-01-14 22:09
This bug is still present in latest versions of Electron.

See Fiddle Gist repro: https://gist.github.com/ce37701f69d1aa7e12ed66d8a0424fba

**Comment by erickzhao** [comment] 2021-01-19 19:54
After further investigation, it seems like Electron and Chromium inherit the `isVisible` property from the [`IsWindowVisible` Win32 API](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-iswindowvisible) on Windows, which checks for the `WS_VISIBLE` Window Style.

Playing around with Powershell scripts on Windows 10, it seems like `IsWindowVisible` will return `true` for minimized windows.

See code for: [`isVisibleTest.ps1`](https://gist.github.com/erickzhao/80ce4100f414b595792dddcb2a9e672f)

It seems to me that this is intended behaviour according to the OS, so I'll be closing this issue. Maybe adding additional documentation in a future PR would be appropriate?

**Closed by erickzhao** 2021-01-19 19:54 UTC
Labels: 11-x-y, 4-2-x, bug :beetle:, platform/windows
