### ISSUE TITLE
electron 7.1.7 crash when use baseURLForDataURL 

### ISSUE THREAD

**Issue by chinayu9** [electron/electron#21671] opened 2020-01-03 10:42 UTC
main.js like this: 

``` js
 // and load the index.html of the app.
  // mainWindow.loadFile('index.html')
  const html = `
    <!DOCTYPE html>
    <html>
      <body>
        <h1>TEST</h1>
      </body>
    </html>
  `

  mainWindow.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`, {
    baseURLForDataURL: 'file:///index.html'
  })
```

crash info like this:

``` log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
7 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle electron-quick-start@1.0.0~start: PATH: D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\electron\srs\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Program Files\TortoiseGit\bin;D:\Program Files\erl8.3\bin;D:\nodejs;D:\nodejs\node_modules;D:\Program Files\Java\jdk1.8.0_231\bin;D:\Program Files\Java\jre1.8.0_231\bin;D:\nodejs\;d:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Users\admin\.windows-build-tools\python27\;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Users\admin\AppData\Roaming\npm;d:\Programs\Microsoft VS Code\bin;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;
9 verbose lifecycle electron-quick-start@1.0.0~start: CWD: D:\electron\srs
10 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '/d /s /c', 'electron .' ]
11 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 2147483651  signal: null
12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
13 verbose stack Exit status 2147483651
13 verbose stack     at EventEmitter.<anonymous> (D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid electron-quick-start@1.0.0
15 verbose cwd D:\electron\srs
16 verbose Windows_NT 10.0.18362
17 verbose argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 2147483651
22 error electron-quick-start@1.0.0 start: `electron .`
22 error Exit status 2147483651
23 error Failed at the electron-quick-start@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2147483651, true ]

```

**Comment by vladimiry** [comment] 2020-01-03 11:19
See the original issue and workaround here #20700

**Comment by codebytere** [comment] 2020-01-03 16:16
Closing as this is a duplicate of the above linked issue.

**Closed by codebytere** 2020-01-03 16:16 UTC
