### ISSUE TITLE
Tray Icon: .setTitle() for Linux

### ISSUE THREAD

**Issue by mkg20001** [electron/electron#9475] opened 2017-05-15 17:55 UTC
* Electron version: 1.6.6
* Operating system: Ubuntu 16.04

### Expected behavior

`Tray.setTitle("Something...")` should work on Linux (at least on Unity/appindicator) because text can be displayed alongside the icon. 
![screenshot](https://cloud.githubusercontent.com/assets/7735145/26071420/58f4ac04-39a8-11e7-994e-c7dbb9586e00.png)

### Actual behavior

It only works on macOS

### How to reproduce

```
const {app, Menu, Tray} = require('electron')

let appIcon = null
app.on('ready', () => {
  appIcon = new Tray('/path/to/my/icon')
  appIcon.setTitle("Something")
})
```

**Comment by kevinsawicki** [comment] 2017-05-15 18:00
I believe this is a duplicate of #4742, please subscribe to that issue for updates.

**Closed by kevinsawicki** 2017-05-15 18:00 UTC
