### ISSUE TITLE
MenuItem.label does not reflect changes after being appended to a menu

### ISSUE THREAD

**Issue by YellowAfterlife** [electron/electron#20247] opened 2019-09-16 22:10 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
MenuItem's label cannot be changed once it's appended to a Menu, despite other properties taking effect as usual.

```js
let electron = require("electron");
let menu = new electron.remote.Menu();
let item = new electron.remote.MenuItem({label:"one!"});
item.label = "two!";
menu.append(item);
item.label = "three!";
item.enabled = false; // (to verify that other properties can be changed)
menu.popup();
```
shows "two!" rather than "three!"; menu item appears disabled - only label change takes no effect.

* **Electron Version:**
  * 7.0.0-beta.4, same effect on 6.0.9 and 4.2.8
* **Operating System:**
  * Windows 10 (18362)
* **Last Known Working Electron version:**
  * (doesn't seem like there's one)

### Expected Behavior
A menu showing "three!"

### Actual Behavior
A menu showing "two!"

### To Reproduce
[fiddle gist](https://gist.github.com/YellowAfterlife/25b6d98c01f3e479469489067dc08ef6)

### Screenshots
![image](https://user-images.githubusercontent.com/731492/64996338-59ab7f80-d8e6-11e9-8966-bd21673b4de0.png)

### Additional Information
Is this a limitation like #527? Could add a note to documentation if so.

**Comment by MarshallOfSound** [comment] 2019-09-18 23:26
Duplicate of https://github.com/electron/electron/issues/528

**Closed by MarshallOfSound** 2019-09-18 23:26 UTC
Labels: 4-2-x, 6-0-x, 7-0-x, bug :beetle:, platform/windows
