### ISSUE TITLE
Hello I am having a issue starting my electron app may your team please help me[Bug]: [14880:1207/145651.085:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by PythonDev1231** [electron/electron#33080] opened 2022-02-25 01:02 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.0

### What operating system are you using?

Windows

### Operating System Version

Win 11, latest

### What arch are you using?

x64

### Last Known Working Electron version

13.6.3

### Expected Behavior

GPU behaves normally, no errors logged.

### Actual Behavior

Actual Behavior
After a few minutes upon starting the App, the following message logs:

[16060:0103/160518.653:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is

the application doesn't crash directly but it seems as though hardware acceleration is disabled anf it quietly fallsback to software rendering, which leads to worse performance / dropped frames.

Did some intense Google search and found a lot of similar errors throughout the Web, all relating back to Chromium. This error doesn't appear in older version of Electron but affects all recent ones.

It may have also todo with an Nvidia driver, since I recently updated that to the latest version.

**Comment by vishnu-marthala** [comment] 2022-03-09 08:28
you could try disabling hardware acceleration. `app.disableHardwareAcceleration()`

**Comment by Choko256** [comment] 2022-03-11 15:22
same issue here (but on Manjaro Linux). Disabling hardware acceleration from the ` app`  object does nothing.

**Comment by PythonDev1231** [comment] 2022-03-12 21:04
Yeah I tried

**Comment by miniak** [comment] 2022-04-29 19:30
Duplicate of #32317

**Closed by miniak** 2022-04-29 19:30 UTC
Labels: bug :beetle:
