### ISSUE TITLE
[Bug]: Opening a file chooser dialog crashes Ferdi on electron 16.0.0 on macos

### ISSUE THREAD

**Issue by vraravam** [electron/electron#31854] opened 2021-11-16 03:32 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

macOS

### Operating System Version

Monterey

### What arch are you using?

x64

### Last Known Working Electron version

15.3.1

### Expected Behavior

The file chooser dialog (eg in this same GH issue edit page) where it says "Attach files by dragging....". When clicking on that area, in older versions, the file chooser dialog would open.

### Actual Behavior

After upgrading to electron 16.0.0, my electron-based app (Ferdi) crashes

### Additional Information

http://github.com/getferdi/ferdi

**Comment by codebytere** [comment] 2021-11-16 12:52
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by PerfectionVR** [comment] 2021-11-17 14:51
I am building an electron app with just webpack, typescript and react, where I use the rendererIPC to invoke a message to the main process.
There I try to open a dialog like so:

```typescript
  /**
   * Returns the BrowserWindow from sender
   * @param event IpcMainEvent
   * @returns BrowserWindow
   */
  private async _openDialog({ sender }: IpcMainEvent, options: OpenDialogOptions): Promise<OpenDialogReturnValue> {
    processLogger.log(`Open file dialog in window ${sender.id}`);
    const w = BrowserWindow.fromWebContents(sender);
    return await dialog.showOpenDialog(w, options);
  }
```

This seems to crash the application abruptly, both renderer and main are gone. Sadly, I'm very time constrained and can't help with a isolated test case. I hope this helps regardless.

**Comment by VerteDinde** [comment] 2021-11-17 16:58
@vraravam Sorry, could you possibly link me to the code in Ferdi that specifically handles the file dialog/opening files? I was reading through the code, but it was difficult to find - if you could point us in the right direction with a link to the file or component, that would be a huge help. Thanks!

**Comment by vraravam** [comment] 2021-11-17 17:04
Thanks for reaching out @VerteDinde!
The main suspect code is documented here: https://github.com/getferdi/ferdi/pull/2239#issuecomment-970310225

Ferdi just renders different services in chromium tabs. Even as I type this, if I click on the "Attach files by dragging & dropping, selecting or pasting them." area below the text area in this github ticket page, Ferdi will crash. Not sure if this explanation is helpful though

**Closed** 2021-11-17 22:13 UTC
Labels: bug :beetle:, component/dialog, blocked/need-repro, 16-x-y
