### ISSUE TITLE
Priority on Electron deciding which app to run

### ISSUE THREAD

**Issue by mangopearapples** [electron/electron#8970] opened 2017-03-20 18:50 UTC
* Electron version: 1.6.2
* Operating system: Windows 10 64-bit

### Expected behavior

Electron usually runs /resources/app.asar if it is present however you can also run a certain app by doing `Electron your_app_path.asar`.
I expected Electron to run app.asar when started without any arguments (this does happen) but to run the provided alternative app when the argument is provided. 

### Actual behavior

However, Electron will still run /resources/app.asar even when the alternative app archive is provided as an argument.

### How to reproduce

To reproduce, simply have an app.asar in /resources/ and another alternative.asar also in the resources folder. Then run `Electron resources/alternative.asar`. It will run the app.asar app. Then rename app.asar to app_old.asar and do the same command and it should run the alternative.asar app.

**Comment by baconbrad** [comment] 2017-03-20 19:19
This is a duplicate of an issue #6167 I posted awhile back and I couldn't seem to push the idea. There is a workaround in this issue that worked for my purposes. Basically app.asar worked as a loader for another asar. But it felt hacky to me. I agree it makes sense to have an argument bypass the default behavior even if app.asar is present.

**Comment by mangopearapples** [comment] 2017-03-20 20:01
Ah yes sorry my bad for not searching properly. I guess I'll have to find a workaround for this issue then. Thanks.

**Comment by MarshallOfSound** [comment] 2017-03-20 22:04
Hey @mangopearapples 

If you wish to use different ASAR files depending on certain situations (CLI args or something), you need to implement some kind of bootstrap `app.asar` yourself.  I.e. A single JS file which simply "requires" the .asar entrypoint that you want to use.

Closing out as a duplicate, see the linked issue above for more discussion on the matter

**Closed by MarshallOfSound** 2017-03-20 22:04 UTC

**Comment by baconbrad** [comment] 2017-03-20 23:16
The downfall of this is app.asar is always locked now. And the other.asar is not loaded in completely like app.asar would be. We may also want to run both asars as separate programs in single instance mode. I am unsure why this hardcoded feature is in place but I feel like this unnecessarily adds restrictions to Electron and should be reconsidered.

**Comment by mangopearapples** [comment] 2017-03-21 00:10
Oh wow thanks for that. Didn't realise it was that simple.
