### ISSUE TITLE
Tray click event opens a Context Menu even if none is set (Linux Mint 19.1)

### ISSUE THREAD

**Issue by chrisalexandrepena** [electron/electron#18402] opened 2019-05-22 07:13 UTC
### Issue Details

* **Electron Version:**
  v5.0.1
* **Operating System:**
  Linux Mint 19.1, using the Cinnamon desktop environment

### Expected Behavior
When creating a tray and setting a click event (but no context menu) it was expected that the event would trigger when clicking directly on the tray icon.

### Actual Behavior
Instead the tray displays a context menu with a normal menu item that uses as label the tray tooltip (or the project name if no tooltip has been set). The click event is triggered when clicking on the menu item, not on the tray icon.
Also since the tooltip is used to create a menu item, none appears when hovering the tray icon.

### To Reproduce
Here's the repo for my project : git@github.com:chrisalexandrepena/googledrive_linux.git
The index.js only creates a tray with click event that opens a window.
All that is needed to run the code is:
$ git clone git@github.com:chrisalexandrepena/googledrive_linux.git
$ npm install
$ npm start

**Comment by eatmyvenom** [comment] 2019-05-23 06:06
Did you try to set the context menu to null

**Comment by chrisalexandrepena** [comment] 2019-05-23 06:21
Yes, it didn't work

**Comment by vladimiry** [comment] 2019-05-24 14:47
It's a known issue https://github.com/electron/electron/issues/14941

**Comment by sofianguy** [comment] 2019-05-29 20:46
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14941. You may want to subscribe there for updates.

**Closed by sofianguy** 2019-05-29 20:46 UTC
Labels: 5-0-x, bug :beetle:, platform/linux
