### ISSUE TITLE
Windows: multiple print dialogue

### ISSUE THREAD

**Issue by rijulzalpuri** [electron/electron#12499] opened 2018-04-02 08:25 UTC
* Electron version: 2.0.0-beta.5
* Operating system: Windows

### Expected behavior

On Windows, on opening multiple browserWindow's executing the webContents.print() method all the browserWindow should have their individual print dialogue

### Actual behavior

only the first window opened has the print dialogue, subsequent window's wont open new dialogue if the last opened window didnt close it, on linux and mac every new window has their individual print dialogue irrespective of whether or not the last window closed its print dialogue 

### How to reproduce
on a button click i am executing this 
` 
```
let browserWindow = new BrowserWindow({
      width: 960,
      height: 768,
      resizable: false,
      minimizable: false,
      maximizable: false
    });
```

    // Load URL
    browserWindow.loadURL(URL);

    // Check finish load event
    browserWindow.webContents.on('did-finish-load', () => {
      setTimeout(() => {
        // Use default print options
        browserWindow.webContents.print({}, success => {
          // Close window after print
          browserWindow.close();
        });
        // Keep track of all the print browser windows
        // This is helpful to determine all the opened browser windows for print
        this.Window.push(browserWindow);
      }, 700);
    });`

**Comment by jkleinsc** [comment] 2018-04-03 15:01
I tested this issue in the following versions on Windows 10 and have validated that it behaves as described in all versions:
1.4.14
1.5.1
1.6.17
1.7.13
1.8.4
2.0.0-beta.6

So this has always worked this way.  I think you could argue it is a bug though because the print function does not even return an error status, the additional print dialogs just don't display.

**Comment by rijulzalpuri** [comment] 2018-04-03 18:13
@jkleinsc thanks for your time, from my point of view it is a bug though as each browserWindow should be able to have it's own print dialogue, also my use case requires uniformity across all three platform's which is surely not the case.

**Comment by sofianguy** [comment] 2019-08-09 03:18
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:07
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:07 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows, status/reviewed
