### ISSUE TITLE
[Bug]: window.print pdf stalled the window

### ISSUE THREAD

**Issue by magmaliang** [electron/electron#28848] opened 2021-04-26 12:52 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.0 12.0.0

### What operating system are you using?

macOS

### Operating System Version

macos 11.2.3

### What arch are you using?

x64

### Expected Behavior

clone the `electron-quick-start` example.

Fill index.html with following content: 
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <!-- https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP -->
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'">
    <meta http-equiv="X-Content-Security-Policy" content="default-src 'self'; script-src 'self'">
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using Node.js <span id="node-version"></span>,
    Chromium <span id="chrome-version"></span>,
    and Electron <span id="electron-version"></span>.

    <form id="searchForm" action="http://www.africau.edu/images/default/sample.pdf" method="get">
      <div class="btn-group form-inline">
          <button name='submit'>open pdf window</button>
      </div>
    </form>

    <!-- You can also require other files to run in this process -->
    <script src="./renderer.js"></script>
  </body>
</html>


```
open pdf window 

Then just execute `window.print()` within pdf_window. Print dialog model opened, click ok, content should be printed && the pdf_window can scroll normally.

### Actual Behavior

The `pdf_window`  will been stalled with no response to any interaction.

**Comment by hdmr14** [comment] 2021-09-13 21:20
probably same issue on Windows 10(x64), but works fine by downgrading to 3 in my case.
It also stalled when printing by actual printer device, not only pdf.

I also checked out for 4.x ~ 15.x(beta).

stalled after dialog: 12, 13
not stalled after dialog, but not working correctly: 7 to 11
stalled with no dialog: 4 to 6
App closed with no dialog: 14, 15

It causes Application Error(Event ID: 10000, Exception code x80000003).

**Comment by codebytere** [comment] 2022-02-07 09:52
Closing as duplicate of https://github.com/electron/electron/issues/27605

**Closed by codebytere** 2022-02-07 09:52 UTC
Labels: bug :beetle:, 11-x-y, 12-x-y, has-repro-comment
