### ISSUE TITLE
WebView prevents <input> from being unselected by clicking

### ISSUE THREAD

**Issue by Polunom** [electron/electron#13261] opened 2018-06-16 00:12 UTC
* Electron Version: v2.0.2
* Operating System (Platform and Version): Windows 10 Build 17134
* Last known working Electron version: N/A

**Expected Behavior**
Highlighted input text should be able to unselected/allow the caret to be moved by clicking on it regardless if a WebView is present or not.

**Actual behavior**
When a WebView is added to the page, it becomes impossible to click on an input element to unhighlight/unselect text.

**To Reproduce**
Put an input and WebView in the same HTML file, like so:
```<!DOCTYPE html>
<html>
  <input type="text">
  <webview src="http://google.com"></webview>
</html>
```
**Screenshots**
When text is highlighted
![before](https://user-images.githubusercontent.com/9621004/41493736-2f8ce364-70bf-11e8-8b0e-2d3f3d325f63.PNG)
Clicking between "is" and "some" should move the caret there.
![after](https://user-images.githubusercontent.com/9621004/41493733-2bd71c80-70bf-11e8-8a2e-40bbfc072c52.PNG)

This is not possible to do when a WebView is loaded:
![with](https://user-images.githubusercontent.com/9621004/41493712-dbfbd78c-70be-11e8-99db-e5c994421fe1.png)

**Comment by javan** [comment] 2018-06-17 12:06
Related: https://github.com/electron/electron/issues/4539#issuecomment-250991454

**Comment by pbmzero** [comment] 2019-01-25 21:56
I had similar issues:

- version 1.8.8  caret always appears in content inside webview tag container
- version 4.0.2 cart would often disappear from remote input boxes inside webview but on separate input boxes on different webview forms. I also noticed that my Accessibility Support would stop working at this same time, i'm using app.setAccessibilitySupportEnabled(true); where i did not have this issue in 1.8.8. 

Overall this issue seems to be most likely to occur on touch screen clicks but you can reproduce in a number of seconds in 4.0.2 just with some aggressive touching on a screen input.

I isolated my webview content to a separate BrowserWindow with webSecurity on and nodeintegrtion off and the problems no longer occurs in 4.0.2.

**Comment by sofianguy** [comment] 2019-08-09 00:28
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 20:58
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 20:58 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
