### ISSUE TITLE
Electron 11: `remote.screen` EventEmitter methods are undefined

### ISSUE THREAD

**Issue by deanylev** [electron/electron#26713] opened 2020-11-27 08:25 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.03
* **Operating System:**
  * macOS 11.0.1

### Expected Behavior
`remote.screen` has EventEmitter methods such as `on` defined, to listen to screen events such as `display-added`

### Actual Behavior
`remote.screen` does not have any defined EventEmitter methods

### To Reproduce
In the devtools, inspect `require('electron').remote.screen` and notice that it does not have the `on` method defined

### Additional Information
There was a PR to address other `remote.screen` methods not being defined that was merged in 11.0.3 (https://github.com/electron/electron/pull/26660), but it did not seem to address this bug

**Comment by nornagon** [comment] 2020-12-01 01:17
Duplicate of #26610.

**Comment by nornagon** [comment] 2020-12-01 01:17
Oops, I see now that this is a different issue.

**Closed** 2020-12-08 04:47 UTC
Labels: 11-x-y, 12-x-y, bug/regression :leftwards_arrow_with_hook:
