### ISSUE TITLE
webpages are too bright

### ISSUE THREAD

**Issue by ghost** [electron/electron#10737] opened 2017-10-10 11:15 UTC
* Electron version: Latest
* Operating system: Mac

### Expected behavior

Take a look at the following screenshot from chrome.
<img width="1424" alt="screen shot 2017-10-10 at 6 11 17 pm" src="https://user-images.githubusercontent.com/753950/31383805-90e2864c-ade6-11e7-8574-38f95b686f69.png">

### Actual behavior
This is how it appears using electron.
<img width="1440" alt="screen shot 2017-10-10 at 6 11 09 pm" src="https://user-images.githubusercontent.com/753950/31383812-9654a2c2-ade6-11e7-8ec6-27ec24fece2e.png">

### How to reproduce

I've noticed this happening in both my custom electron apps, and in other apps that are built on top of electron: The brightness just seems to be higher than on chrome.
But, i've also noticed this issue when using [qutebrowser](https://qutebrowser.org/) so my guess is that this might be a chromium issue?

**Comment by teleclimber** [comment] 2017-10-10 16:26
This could be the same problem as the bug I filed yesterday: #10732

**Comment by piotryordanov** [comment] 2017-10-12 12:48
It is indeed the same as the bug you filed.
I'm not sure what I can do to help though!

**Comment by teleclimber** [comment] 2017-11-03 21:36
Actually, I take it back. I think there is something else going on.

<img width="492" alt="screen shot 2017-11-03 at 4 10 10 pm" src="https://user-images.githubusercontent.com/5631748/32396465-52ea3a08-c0b3-11e7-88ff-1a4f2d19edb2.png">

You'll notice it's only the `<pre>` and `<br>` that look significantly different. It turns out these are styled as:

```
font-family: monospace;
```

I presume this is the same font as is used to show the XML code in the screenshots above. So the issue appears to have something to do with that font, or the way Chrome renders that font.

Beyond that, I'm not sure.

**Comment by sorentycho** [comment] 2017-11-06 19:00
I suspect this is something similar to #10955 or so.

**Comment by sofianguy** [comment] 2019-01-07 22:39
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:34
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-01-15 20:34 UTC
Labels: blocked/need-info, bug :beetle:, platform/macOS, version/1.8.x
