### ISSUE TITLE
Define preload script inline in main.js webPreferences

### ISSUE THREAD

**Issue by petef19** [electron/electron#28981] opened 2021-05-04 02:30 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Looking to set my preload script directly inline in the webPreferences of main.js.

I found these two PRs that seems to be about that (please correct if wrong): #27741, #27546

But the threads state no updated information on when this is going to be released and/or the syntax to use this feature.

So, Is this doable at the moment ? If so, could you post a short example on how to do that ?

Thanks.

```
Electron 12.0.5
Win x64
```

### Proposed Solution

n/a

### Alternatives Considered

n/a

### Additional Information

n/a

**Comment by Prinzhorn** [comment] 2021-05-04 06:49
> Looking to set my preload script directly inline in the webPreferences of main.js.

Could you elaborate why you want to do this? I can only see downsides.

**Comment by petef19** [comment] 2021-05-04 10:19
@Prinzhorn 

> Could you elaborate why you want to do this (this belongs in the "Problem Description" section, please follow the template in the future)? I can only see downsides.

sorry about the "reasons" missing from "problem description", but as per my OP I was asking **_if_** this is already possible currently (I wasn't sure).

A couple of reasons:

(1) one less file to worry about or take care of: preload.js, especially for a small, single preload script this is all that is needed.

(2) we're protecting the app by using `ctxisolation` with `sandbox` - and in addition we're using `bytenode` to protect the source code, as unfortunately `electron` does not come w/ any features to protect `main.js` - contrary to `NW.js` which has features built-in.

But using `ctxisolation` with `sandbox` removes the `require` method, which is needed to protect the `preload` script with `bytenode`. In the latter scenario, preload.js _requires_ a protected preload.jsc bytenode file which has all the preload code protected. This approach does not work currently with `ctxisolation` and `sandbox`  both set to true, but if we were able to define preload inline in `main.js`, then this would work just fine.

Since all of these ongoing changes and upgrades are about **security**, yet no security features are built into `Electron` yet to protect source code, this would allow users to at least utilize 3rd party packages for protection/security and still use strict `ctxisolation` with `sandbox`.

Lmk if questions, please.
Thanks.

**Comment by Prinzhorn** [comment] 2021-05-04 15:33
> sorry about the "reasons" missing from "problem description", but as per my OP I was asking **_if_** this is already possible currently (I wasn't sure).

I'm just trying to triage issues to make it easier for the Electron team. And there are a lot of issues that do not follow the templates, which oftentimes is an indicator that this is not the correct place. For general questions it's preferred to use one of the other support channels listed here: https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support

Thanks for providing a use-case. I don't have any experience with bytenode. If you would provide the preload script as string literal I assume it would still easily be recoverable from the bytecode? E.g. via `strings(1)`? Because it can't be turned into bytecode at compile time, because the preload script is evaluated at runtime for each WebContent (just like any `<script>` in your renderer). I would also argue that the preload script is more closely related to your render code than your main code. If you need preload at all, then it's usually just a thin API bridge to the main process, no code to steal here really. How do you protect your renderer/frontend code (React or whatever)? I'd apply the same to preload if you need to. But like I said I haven't looked closely into obfuscating application code yet.

> Since all of these ongoing changes and upgrades are about **security**, yet no security features are built into `Electron` yet to protect source code

I think bytenode is more about obfuscating and protecting your intellectual property (and maybe faster startup) than it is about security. So maybe the term security is not accurate here.

**Comment by MarshallOfSound** [comment] 2021-05-04 21:25
>  I was asking if this is already possible currently (I wasn't sure).

It is not.

> I think bytenode is more about obfuscating and protecting your intellectual property (and maybe faster startup) than it is about security. So maybe the term security is not accurate here.

This is correct, there is no way to protect your code from end users.  If your code is running on their machine, it is always reverse engineerable, all you're doing is making it slightly harder (and barely at that)

Closing as duplicate of https://github.com/electron/electron/issues/14012

**Closed by MarshallOfSound** 2021-05-04 21:25 UTC
Labels: enhancement :sparkles:

**Comment by petef19** [comment] 2021-05-05 04:00
> Because it can't be turned into bytecode at compile time, because the preload script is evaluated at runtime for each WebContent (just like any <script> in your renderer). I would also argue that the preload script is more closely related to your render code than your main code.

well, currently we are protecting main.js via `bytenode`, meaning `main.js` is fully `bytenode` encoded, w/ an external `preload.js` script - all of this works just fine. So if that works, then why would `preload` defined inside `main.js` not work ?

> If you would provide the preload script as string literal I assume it would still trivially be recoverable from the bytecode?

right, but strings can be obfuscated further to prevent string search and/or make it much harder to identify logic at hand.

> I think bytenode is more about obfuscating and protecting your intellectual property (and maybe faster startup) than it is about security. So maybe the term security is not accurate here.

I agree, although this is splitting hairs to some degree IMO, but protection is definitely a more descriptive term here.  :-)

> If your code is running on their machine, it is always reverse engineerable, this problem is not limited to JS or Electron, decompilers are a thing

sure, but the point for us is to make it **as hard as possible** - and it seems you make it as easy as possible for yourself saying "just accept sw piracy" :-|

It seems this is completely unsupported by team Electron yet you hammer away with security measures re `contextisolation` and `sandbox`. Once an app is hacked, and this will obviously occur more often w/ apps that have little to no protection added, they can change functionality add/remove stuff and then redistribute the hacked version etc etc etc.

Do not forget: not every app is online. Let me repeat this: **not every app is online and/or requires constant online access**.  Not every app is `Slack`.

This particular one here does not and cannot (for a variety of reasons in this particular industry) other than for the initial online activation.

> your business logic should be done on your backend if you don't want people figuring it out, all you're doing is making it slightly harder (and barely at that)

would love for you to elaborate on what "backend" means here. Is that the main process or an online server ? If the latter, then see my last point. If the former, then we'd still need to protect that - **as much as we can**.

The more guidance and recommendations you can provide here, the better. As you know, this is a subject that constantly, repeatedly comes up (every year) and responses like yours are simply dismissing the issue. Like I said 'NW.js' has protection features built in.

Thanks.

**Comment by Prinzhorn** [comment] 2021-05-05 09:01
> yet you hammer away with security measures re `contextisolation` and `sandbox`

You brought this up before, but I don't see how this is related to this discussion at all. These are features protecting your users. And I wouldn't say Electron keeps adding security features, rather they are undoing design decisions that originally seemed like a good idea but made things way less secure by loosening the security features that Chromium comes with. Or even worse by introducing `nodeIntegration`.

This discussion doesn't seem to be very productive right now as `preload` is only a minuscule part of the problem. I am working on an offline (no server backend) app as well, so I'm kind of in the same boat as you are. This is a hard problem to ~solve~ approximate and I assume NW.js can do that because they have a very different architecture than Electron.
Electron is an open-source project and a lot of Electorn apps are open-source. The ones that are not are often Slack-like and basically just wrap their website. Or at least they have user authentication +  a backend with business logic. And then there is probably a small amount of offline apps with some sort of license-key mechanism. Honestly I don't know of any, but I'm not _that_ familiar with the ecosystem. Anyway, what I'm trying to say is that features like this don't just appear out of thin air. There needs to be interest on either Electron's side or from some commercial entity to fund and maintain such a feature. And then the question is if the effort (and downsides) are really worth it given that virtually every software, including every pc game ever, has a cracked version available. No matter in what language they were written.

> As you know, this is a subject that constantly, repeatedly comes up (every year) and responses like yours are simply dismissing the issue

Maybe you can compile a list of issues / discussions / blog posts around that topic? How are others solving this? What options are available? Maybe you can add something new to the discussion? What small but impactful changes could be made to Electron to make this easier in user-land (things like `preload` as string maybe)? And then you could turn this into a section in the docs, so that there's at least some sort of official acknowledgement that this problem exists but that there is (and can't be) a universal solution.

**Comment by petef19** [comment] 2021-05-05 10:52
> Maybe you can add something new to the discussion?

Well, you learned about `bytenode` already from my post

> What options are available?

`bytenode`

> How are others solving this?

`bytenode`

> What small but impactful changes could be made to Electron to make this easier in user-land (things like preload as string maybe)? 

No, don't use the `preload` script as a string, simply allow to define a callback method for `preload` instead of an external file path, that callback is either anonymous inline or a method in `main.js`. Done, as outlined in the OP.

> Maybe you can compile a list of issues / discussions / blog posts around that topic?

I'm not sure where you've been, but if you never heard about this particular topic (protection of source code and IP in Electron) then you need to get more involved in the ecosystem. Next problem is that while your post is appreciated, it contains zero approaches, solutions or help.

Question you have to ask yourself is: do you want to evolve Electron into a better app or keep arguing about something that should have been done years ago ? --> add source code protection

Unless of course, you want Electron solely to be a solution for small open source app, online only apps or for apps that follow a open-source business model, but then this should be clearly advertised and labeled as such - that your src code will be exposed to the world, which disqualifies this for the majority of projects.

Don't misunderstand these posts here, it's not that we don't like Electron. Oh yes. And it's not that we don't have to live with the bugs and issues. Oh yes, we do. And it's not that we're not willing to live with it's shortcomings, such as IP and src code protection. Oh yes we do. And by going the extra 1000 miles by using Bytenode and a variety of other things. Not b/c we want to, but b/c we have to, currently.

But when then topics like these get posted (there are others), with really easy to integrate solutions (simply allow preload to be a method in `main.js`) and we hear these responses and then threads closed w/ bogus answers, it's just a really bad sign of where this is going.

Let's see what happens.

**Comment by Prinzhorn** [comment] 2021-05-05 11:18
> No, don't use the `preload` script as a string, simply allow to define a callback method for `preload` instead of an external file path, that callback is either anonymous inline or a method in `main.js`. Done, as outlined in the OP.

Sorry, I misunderstood your OP then and thought "set my preload script directly inline in the webPreferences of main.js." meant inline _as a string_. The linked issues also had "load preload script directly as a string " as title, adding to the confusion :sweat_smile: 

Having a function as `preload` sounds like a reasonable feature requests in general, independent from the whole source code protection topic. There might be more use-cases to dynamically decide which preload to load or _how_ to load it, not sure though. I'd be great to have a clean feature request for that so it doesn't get buried in here :+1:

**Comment by petef19** [comment] 2021-05-05 12:01
> I'd be great to have a clean feature request for that so it doesn't get buried in here 👍

done, see #29014

Thanks.
