### ISSUE TITLE
Fall of FPS when moving objects across the screen

### ISSUE THREAD

**Issue by abalad** [electron/electron#11404] opened 2017-12-11 16:35 UTC
* Electron version: 1.7.7
* Operating system: Windows 10 and Linux Ubuntu 16.04

I'm running some performance tests on Eletron and I've encountered a serious problem with your engine.

I ran the same project in one application with **NW.js** and another with **ElectronJS**. In the electron I noticed that there is a great drop of FPS when moving objects by the screen and this does not occur in NW.

I think it's strange because they both use the same engine. Does anyone have any idea of what can be done to improve this performance?

**Comment by MarshallOfSound** [comment] 2017-12-11 21:56
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out. In particular, steps to reproduce are very important in helping us identify any potential issues.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by sofianguy** [comment] 2018-01-03 05:10
@abalad Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/11404#issuecomment-350871279). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2018-01-03 05:10 UTC
Labels: more-information-needed, platform/linux/ubuntu, platform/windows, version/1.7.x
