### ISSUE TITLE
Dom frozen after cancel close window.print dialog.

### ISSUE THREAD

**Issue by purocean** [electron/electron#19768] opened 2019-08-15 05:42 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.2
* **Operating System:**
  * Windows 10.0.18362.267

---------------------------------------------------------------------------------------------------
[Version 6.0.2](https://github.com/electron/electron/releases/tag/v6.0.2) solved print crash problem. But is still trouble when I cancel print dialog.

There is a closed same issue.
https://github.com/electron/electron/issues/14705

**Comment by CaseyLeeMurphy** [comment] 2019-09-05 18:14
I don't believe this is a windows only issue. I'm observing this behavior on mac in version 7.0.2

**Comment by vladimiry** [comment] 2019-09-11 05:51
This is a quite severe issue. Besides, Linux is also affected.

**Comment by jngbng** [comment] 2019-10-01 07:54
I'm observing it on Mac (Mojave 10.14.5) in version 6.0.10, too.

**Comment by HaNdTriX** [comment] 2019-10-07 10:22
This issue also effects the window.opener api:

```js
const opener = window.open('/')
opener.print() // -> freezes current webview
```

**Comment by jarek-foksa** [comment] 2019-10-14 07:22
I can reproduce this issue with Electron 5.0.11 on macOS Mojave.

**Comment by HaNdTriX** [comment] 2019-10-14 09:15
Fyi: This issue seems to be resolved in version `v7.0.0-beta.6`

**Comment by TristonJ** [comment] 2019-10-18 17:25
This issue seems to be fixed in `v7.0.0-beta.6` and `v7.0.0-beta7`, but in those versions I am experiencing a different issue (appears to be the same as https://github.com/electron/electron/issues/14705). The print dialog only works once (Ubuntu 19.04).

**Comment by codebytere** [comment] 2019-12-09 19:14
@vladimiry this should be fixed in 8

**Comment by codebytere** [comment] 2019-12-09 19:16
Closing as this has been fixed - however the "only works once" issue is valid and will now be tracked in https://github.com/electron/electron/issues/21397.

**Closed by codebytere** 2019-12-09 19:16 UTC
Labels: 6-0-x, bug/crash :boom:, platform/windows
