### ISSUE TITLE
[Bug]: Windows 10 pro - win.setAlwaysOnTop(true, 'pop-up-menu') not cover windows taskbar 

### ISSUE THREAD

**Issue by ellatom** [electron/electron#35225] opened 2022-08-04 14:07 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.3.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10 pro

### What arch are you using?

x64

### Expected Behavior

The win.setAlwaysOnTop(true, 'pop-up-menu') should cover the taskbar in windows  as dock covered in mac.

### Actual Behavior

The win.setAlwaysOnTop(true, 'pop-up-menu') not cover the taskbar in windows 10 pro.
In mac the dock is covered, while on windows the task bar isn't being covered.

**Comment by ckerr** [comment] 2022-08-04 17:21
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by ellatom** [comment] 2022-08-04 19:19
@ckerr see created gist:
[](https://gist.github.com/da0d2e9c7a46d65ffc7f4625a7a84d8a)

**Comment by wapgear** [comment] 2022-08-05 06:00
If you use `setFullscreen(true)` it'll work as expected for you?

**Comment by codebytere** [comment] 2022-08-05 07:49
I can't reproduce with your gist - it shows above the task bar as expected. I also verified that it does _not_ show above the task bar for lower values like `floating`.

**Comment by ellatom** [comment] 2022-08-05 10:51
@wapgear No.The task bar of the window with red window still appear below the task bar.
@codebytere The bug only happens on windows- I have windows 10 pro. It looks that no matter what window size provided and whether it full screen or not the window always appear below the task bar. 
I have used the documentation and according to it only values above 'pop-up-menu' should set the taskbar below the window and the window should be set on top.
So it really strange that the window shows above.
`win.setAlwaysOnTop(flag[, level][, relativeLevel])
flag boolean
level string (optional) macOS Windows - Values include normal, floating, torn-off-menu, modal-panel, main-menu, status, pop-up-menu, screen-saver, and dock (Deprecated). The default is floating when flag is true. The level is reset to normal when the flag is false. Note that from floating to status included, the window is placed below the Dock on macOS and below the taskbar on Windows. From pop-up-menu to a higher it is shown above the Dock on macOS and above the taskbar on Windows. See the [macOS docs](https://developer.apple.com/documentation/appkit/nswindow/level) for more details.
relativeLevel Integer (optional) macOS - The number of layers higher to set this window relative to the given level. The default is 0. Note that Apple discourages setting levels higher than 1 above screen-saver.`

**Comment by codebytere** [comment] 2022-08-05 10:53
@ellatom - yes. I tested on Windows. The red window shows _above the last bar_ for me.

**Comment by ellatom** [comment] 2022-08-05 10:55
@codebytere Have you used the gist? Have you changed something there?
Can you attach your code to compare? What windows version you have?

**Comment by ellatom** [comment] 2022-08-07 07:05
@ckerr I also see there is an open issue- perhaps it's the same issue:
https://github.com/electron/electron/issues/20933
and someone has described in this discussion that window set behind taskbar
https://github.com/electron/electron/issues/20933#issuecomment-795093872

**Comment by ellatom** [comment] 2022-08-08 09:53
@wapgear I have made some changes when app is running on mac and when it runs on windows.
I have added to windows setFullscreen(true) and removed on windows setFullScreenable(false) and it worked. 
Thanks.
@ckerr This issue can be closed

**Closed** 2022-08-10 12:10 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, 18-x-y
