### ISSUE TITLE
WebView's preload has a bug

### ISSUE THREAD

**Issue by livelyPeng** [electron/electron#34868] opened 2022-07-10 13:55 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows11

### What arch are you using?

x64

### Expected Behavior

There is a problem with WebView and preload in version 19. Add attributes to the window. Not found on the embedded page

### Actual Behavior

![image](https://user-images.githubusercontent.com/32978177/178147758-31acfbc2-57ca-418e-8483-9e78701faadd.png)
![image](https://user-images.githubusercontent.com/32978177/178147773-eb749e49-34a0-41c8-972d-85dd7cf6106e.png)

There is a problem with WebView and preload in version 19. Add attributes to the window. Not found on the embedded page

![image](https://user-images.githubusercontent.com/32978177/178147860-f2d2b8b5-dac6-414a-b93a-03d8f967cafb.png)

**Comment by livelyPeng** [comment] 2022-07-10 13:55
![image](https://user-images.githubusercontent.com/32978177/178147895-ea915c01-0a5d-483b-bae3-88ab30ded456.png)

**Comment by codebytere** [comment] 2022-07-11 10:46
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-07-21 09:13
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-07-21 09:13 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, 19-x-y
