### ISSUE TITLE
Electron app memory is too hight on screen sharing and live webcam app crash on 1GB memory even i have 8 GB of Ram

### ISSUE THREAD

**Issue by saifur-rehman** [electron/electron#13059] opened 2018-05-24 08:04 UTC
* Electron Version: 1.8.4
* Operating System (Platform and Version): macOS Sierra
* Last known working Electron version: 

**Expected Behavior**
My electron app is running smoothly as i run screen sharing and live webcam functionality memory reached over 1 GB some times app crashed on 700MB

**Actual behaviour**
Actual behaviour is to send screen shares and live cam to a node server which is running good but as passage of time memory become high and higher

**Screenshots**
![screen shot 2018-05-24 at 1 03 12 pm](https://user-images.githubusercontent.com/21338011/40472423-e2e9c4fa-5f52-11e8-997a-572ee640c6e2.png)

**Comment by MarshallOfSound** [comment] 2018-05-24 08:27
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by imtiyazs** [comment] 2018-05-30 05:09
Hello,  I am also using electron 1.8.4 for video conferencing and screensharing using openvidu. But I did not face any memory leaks inside electron, rather at initial stage, there was a memory leak that occurred in navigator.getUserMedia method because media stream was not cleared from application memory. On each new connection, new blob was stored in memory and crashed at some point where memory crossed GB.

**Comment by saifur-rehman** [comment] 2018-06-01 11:02
i am still looking for a solution about app crash this is happens only when i share screen form my app or open camera for more than 1 minute app crashed otherwise everything works perfectly
i am using vue-web-cam module for live streaming and electron.desktopCapturer for screen sharing.
any solution regards this issue will be pretty thank full

**Comment by miniak** [comment] 2018-09-02 11:00
@saifur-rehman does it reproduce with Electron 2.0 or 3.0 beta?

**Comment by saifur-rehman** [comment] 2018-09-02 11:47
@miniak it's on electron 2.0

**Comment by imtiyazs** [comment] 2018-09-03 14:33
Can you show me the code ?

**Comment by sofianguy** [comment] 2019-08-09 00:42
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 21:01
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 21:01 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/macOS, version/1.8.x
