### ISSUE TITLE
WebRequest.onHeadersReceived callback missing webContentsId field

### ISSUE THREAD

**Issue by rahatarmanahmed** [electron/electron#15329] opened 2018-10-23 07:03 UTC
* Output of `node_modules/.bin/electron --version`: v3.0.0
* Operating System (Platform and Version): MacOS High Sierra 10.13.6 (17G65)

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.12

### Expected behavior

`details.webContentsId` in WebRequest.onHeadersReceived callback should be populated, as is [documented](https://github.com/electron/electron/blob/master/docs/api/web-request.md#webrequestonheadersreceivedfilter-listener). (Although it does say optional, but it's not clear when it would be missing.)

### Actual behavior

`details.webContentsId` is undefined.

### How to reproduce

Ran this snippet in Electron Fiddle, identified the change was introduced between [2.0.12 and 3.0.0-beta.1](https://github.com/electron/electron/compare/v3.0.0-beta.1...v2.0.12).

```javascript
const {app, BrowserWindow} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow()
  mainWindow
      .webContents
      .session
      .webRequest
      .onHeadersReceived((details, cb) => {
        const id = details.webContentsId;
        console.log('webContentsId:', id);
        // Exit with 1 (fail) if id is missing,
        // or 0 (pass) if id is present
        app.exit(Number(id == undefined));
      })
  mainWindow.loadURL('http://example.com')
}

app.on('ready', createWindow)
```

**Comment by rahatarmanahmed** [comment] 2018-10-23 23:27
I suspect it only becomes undefined for the initial request that a window is navigating to. All subsequent requests afterwards have the webContentsId set. Is this an intentional change? It's pretty inconvenient, especially for the case where we want to handle 302 redirects to the initial URL load.

**Comment by codebytere** [comment] 2018-10-26 04:01
As a brief update to this: `webContentsId` appears to be getting set to 0 in your example, and we only set it if it's greater than 0, which is why it's returning undefined. As to _why_ it's returning 0, more 🕵️‍♀️  work is in order.

**Comment by codebytere** [comment] 2018-10-30 15:23
also @rahatarmanahmed the build instructions change between 3 and 4, they're the same between 2 and 3

**Comment by rahatarmanahmed** [comment] 2018-10-30 18:48
I'm pretty sure they changed? From the release notes for [v3.0.0-beta.1](https://github.com/electron/electron/releases/tag/v3.0.0-beta.1):

> Added the ability to build with GN. #12837, #12884, #12948, #13286, #13005, #12885, #12647, #12882, #12950, #12952, #13124, #13285, #12953 , #12949, #13284, #12957, #12951, 12738

**Comment by codebytere** [comment] 2018-10-30 19:01
The ability was added but not defaulted. It's still perfectly possible to build `3-0-x` with gyp.

**Comment by rahatarmanahmed** [comment] 2018-11-13 18:51
Okay, figured out what my problems were and bisected this overnight. This is what I got:
```
65e8199a932e1cf6ce0a9959ac919a88a5eff5a6 is the first bad commit
commit 65e8199a932e1cf6ce0a9959ac919a88a5eff5a6
Author: Robo <hop2deep@gmail.com>
Date:   Fri Apr 6 12:52:52 2018 +0530

    Enable plznavigate aka browser side navigation (#12535)

    * enable plznavigate code path

    * AtomBrowserClient::GetGeolocationApiKey returns the right default

    * use IsLoadingToDifferentDocument to identify top level navigation in mainFrame

    * use candidate site instance when available

    * spec: don't test httpReferrer option for file origin

    * update libcc ref

    * affinity: only group same site in this mode

    * plznavigate: don't emit did-get-response-details event for blob scheme

:040000 040000 bae90bc2edea754774d23f0476adaf87e5a493d6 69d49f0147bc15948e3a1f672bb202025cc5bfbd M      atom
:040000 040000 1d77c5e7841de4e07f9b4a92c72846d6a9e1bc1f f9b52f03f71ff94e7e0730397caeaac6fa216a09 M      spec
:040000 040000 ebbc7966ced4d40ae1c23211c58107dc4cbbdcee ca1fd3e152cbcdacf8df9b13caaab90c2a546f00 M      vendor
```

**Comment by sofianguy** [comment] 2019-08-09 22:42
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by rahatarmanahmed** [comment] 2019-08-09 23:03
Confirmed the issue is still present on v6.0.1

**Comment by RangerMauve** [comment] 2020-10-03 22:11
Issue is still present in Electron 11 Beta 9

**Comment by RangerMauve** [comment] 2020-10-03 22:13
To be more clear: This works fine when webContents perform a request via `fetch()` or `XHR`, but it doesn't work when the request is being performed due to the page loading.

**Comment by RangerMauve** [comment] 2020-10-03 22:27
Seems like the webContentsId is missing for onBeforeRequest, too. It'd be nice if the docs talked more about when we should and shouldn't expect it to be present. 😅

**Comment by RangerMauve** [comment] 2020-10-03 22:29
Yeah, it seems like mainFrame requests never get a webContentsId

**Comment by sohobloo** [comment] 2021-07-14 09:51
still in Electron 12.0.7
how can i relate a web request to a webContents

**Comment by nornagon** [comment] 2021-07-14 17:52
The snippet in the top post works correctly (exits with code 0) as far back as Electron 7.x. I'm closing this as fixed, if you're experiencing a similar problem, please open a new issue with a new failing repro case!

**Closed by nornagon** 2021-07-14 17:52 UTC
Labels: 11-x-y, 3-0-x, 6-0-x, 6-1-x, bug :beetle:, platform/macOS
