### ISSUE TITLE
GlobalShortcutListenerMac Crash after closing app on Mac

### ISSUE THREAD

**Issue by Superjo149** [electron/electron#15717] opened 2018-11-14 19:08 UTC
* Output of `node_modules/.bin/electron --version`: **3.0.9**
* Operating System (Platform and Version): **Max OSX 10.14**
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): **Not sure**

**Expected Behavior**
Open and close without crashes or hickups.

**Actual behavior**
Upon opening my app, first of all, the jumping application of your starting app in the dock (on Mac) is freezing a couple of times, which looks like something is already breaking there.

During application use, everything seems fine, nothing is broken. But upon closing the application, I receive following error: 

```
Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation        0x00007fff37b77ccc CFHash + 372
1   com.apple.CoreFoundation        0x00007fff37ba3547 CFBasicHashGetCountOfKey + 198
2   com.apple.CoreFoundation        0x00007fff37ba7524 CFSetContainsValue + 73
3   com.apple.CoreFoundation        0x00007fff37bc40d2 CFRunLoopRemoveSource + 366
4   com.github.electron.framework   0x00000001096335d4 extensions::GlobalShortcutListenerMac::StopWatchingMediaOrVolumeKeys() + 36
5   com.github.electron.framework   0x0000000109633f7a extensions::GlobalShortcutListenerMac::UnregisterAcceleratorImpl(ui::Accelerator const&) + 202
6   com.github.electron.framework   0x0000000109632d3b extensions::GlobalShortcutListener::UnregisterAccelerator(ui::Accelerator const&, extensions::GlobalShortcutListener::Observer*) + 139
7   com.github.electron.framework   0x0000000109632e88 extensions::GlobalShortcutListener::UnregisterAccelerators(extensions::GlobalShortcutListener::Observer*) + 280
8   com.github.electron.framework   0x0000000109527832 atom::api::GlobalShortcut::UnregisterAll() + 34
9   com.github.electron.framework   0x00000001095277ea atom::api::GlobalShortcut::~GlobalShortcut() + 58
10  com.github.electron.framework   0x0000000109527899 atom::api::GlobalShortcut::~GlobalShortcut() + 9
11  com.github.electron.framework   0x00000001095278ce atom::api::GlobalShortcut::~GlobalShortcut() + 14
12  com.github.electron.framework   0x00000001095278ed non-virtual thunk to atom::api::GlobalShortcut::~GlobalShortcut() + 13
13  com.github.electron.framework   0x0000000109595f0f mate::TrackableObjectBase::Destroy() + 15
14  com.github.electron.framework   0x0000000109591d2a 0x1094f9000 + 625962
15  com.github.electron.framework   0x0000000109591cf8 0x1094f9000 + 625912
16  com.github.electron.framework   0x0000000109591cbc 0x1094f9000 + 625852
17  com.github.electron.framework   0x0000000109595ff4 base::internal::Invoker<base::internal::BindState<void (mate::TrackableObjectBase::*)(), base::WeakPtr<mate::TrackableObjectBase> >, void ()>::RunOnce(base::internal::BindStateBase*) + 20
18  com.github.electron.framework   0x00000001094fecb5 0x1094f9000 + 23733
19  com.github.electron.framework   0x000000010959ce80 atom::AtomBrowserMainParts::PostMainMessageLoopRun() + 96
20  com.github.electron.framework   0x0000000109c25383 0x1094f9000 + 7521155
21  com.github.electron.framework   0x0000000109c50759 0x1094f9000 + 7698265
22  com.github.electron.framework   0x0000000109c21385 0x1094f9000 + 7504773
23  com.github.electron.framework   0x0000000109916d09 0x1094f9000 + 4316425
24  com.github.electron.framework   0x000000010b5c0662 0x1094f9000 + 34371170
25  com.github.electron.framework   0x0000000109915924 0x1094f9000 + 4311332
26  com.github.electron.framework   0x00000001094fbb84 AtomMain + 68
27  be.sneljo.auryo                 0x00000001094f2f16 main + 38
28  libdyld.dylib                   0x00007fff64c3d085 start + 1
```
Full error: https://pastebin.com/NxYCxE02

**To Reproduce**
You can fork https://github.com/Superjo149/auryo. If you want to be sure nothing is changed, please use https://github.com/Superjo149/auryo/tree/v2.2.1.

**Additional Information**
I'm pretty sure it started happening as of v3.X but I also updated some other dependencies, so I'm not sure if electron is the root cause here. Or if it is some package interfering.

**Comment by codebytere** [comment] 2018-11-15 18:08
Duplicate of https://github.com/electron/electron/issues/14837.

**Closed by codebytere** 2018-11-15 18:08 UTC
