### ISSUE TITLE
No folder icons in save file dialog (when app is run from tmux)

### ISSUE THREAD

**Issue by svileng** [electron/electron#4236] opened 2016-01-26 14:56 UTC
I want to handle saving of a file to set the download path:

``` javascript
  mainWindow.webContents.session.on('will-download', function(event, item) {
    var filename = item.getFilename();
    var savePath = require('dialog').showSaveDialog({
      title: filename,
      defaultPath: require('os').homedir() + '/' + filename
    });
    if (savePath) {
      item.setSavePath(savePath);
    } else {
      item.cancel();
    }
  });
```

It's all good, except that the dialog comes out without icons for ~~files and~~ folders (file type icons are fine, only folder icons), and is missing the usual items in the left sidebar:
![screen shot 2016-01-26 at 14 48 17](https://cloud.githubusercontent.com/assets/351592/12583848/9d643414-c43c-11e5-88ca-101249f60846.png)
My electron version is `0.36.4`, running OSX `10.11.2`.

Is it possible to have the icons back and make the dialog look more native? Thanks!

**Comment by zcbenz** [comment] 2016-01-27 11:09
It looks very likely a problem of OS X, the file dialog should show like other apps.

Can you try restarting your machine and see if it is still there?

**Comment by svileng** [comment] 2016-01-27 17:38
Restarted my machine, no effect. A colleague of mine ran the app (OSX `10.11.2`), and he doesn't experience that problem, which is well weird. Also, I do see certain icons for files, such as PNGs, but most file icons are also missing. I'm currently running OSX `10.11.3`.

**Comment by svileng** [comment] 2016-01-28 16:57
Both Chrome and Atom's file dialogs work normally.

**Comment by zcbenz** [comment] 2016-01-29 01:40
This makes the problem more strange, all of these apps are actually sharing the same dialog code.

Maybe you can cleanup your project and do a complete rebuild, or try renaming your app to another name and see if the problem is still there.

**Comment by bengotow** [comment] 2016-02-01 04:00
@jstejada was running into this a week or two ago as well—I remember we opened Console.app and there was a lot of noise coming from LaunchServices. Something to the effect of "Can't establish XPC connection". Do you see anything there?

I think this must be a Mac OS X bug, but it's super interesting that it doesn't seem to impact other apps.

**Comment by svileng** [comment] 2016-02-01 10:32
@bengotow Yes, looks like I've got the same! I got about ~1100 of those when I clicked on a link that triggers the save file dialog:
```
01/02/2016 10:25:42.921 Electron[61351]: LaunchServices: received XPC_ERROR_CONNECTION_INTERRUPTED trying to map database
01/02/2016 10:25:42.921 Electron[61351]: LaunchServices: Database mapping failed with result -10822, retrying
01/02/2016 10:25:42.921 Electron[61351]: LaunchServices: received XPC_ERROR_CONNECTION_INTERRUPTED trying to map database
```
And a bunch of those, as well as at the end of the logs:
```
01/02/2016 10:25:43.823 Electron[61351]: Error returned from iconservicesagent: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.iconservices" UserInfo={NSDebugDescription=connection to service named com.apple.iconservices}
01/02/2016 10:25:43.831 Electron[61351]: Error returned from iconservicesagent: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.iconservices" UserInfo={NSDebugDescription=connection to service named com.apple.iconservices}
```

**Comment by jstejada** [comment] 2016-02-02 18:32
yes, I'm getting this error:

```
Electron[61018:6395526] Communications error: <OS_xpc_error: <error: 0x7fff7de7cc90> { count = 1, contents =
        "XPCErrorDescription" => <string: 0x7fff7de7cf78> { length = 18, contents = "Connection invalid" }
}>
```

**Comment by ChrisPenner** [comment] 2016-04-14 05:18
I'm experiencing the same error:
```
2016-04-13 23:15:24.240 Electron[7123:3584536] Communications error: <OS_xpc_error: <error: 0x7fff75beec90> { count = 1, contents =
        "XPCErrorDescription" => <string: 0x7fff75beef78> { length = 18, contents = "Connection invalid" }
}>
```

**Comment by thomastuts** [comment] 2016-06-16 09:27
Just wanted to chime in here and say that I have the same exact issue (also in open file dialogs). I'm also getting the XPC error (`connection invalid`).

I'm using Node `6.1.0`, Electron `1.2.2` and OSX `10.11.5` if that's any help.

**Comment by matthewatabet** [comment] 2016-06-29 16:19
Same problem for me too.
```2016-06-29 09:15:28.063 Electron[57773:4161280] Communications error: <OS_xpc_error: <error: 0x7fff7a2a9c90> { count = 1, contents =
        "XPCErrorDescription" => <string: 0x7fff7a2a9f78> { length = 18, contents = "Connection invalid" }```

**Comment by inferno1005** [comment] 2016-08-11 17:28
Was having the exact same issue with:
OSX `10.11.3`
Node `4.4.7`
Electron `1.3.2`


Updated to:
OSX `10.11.6` 

and the problem is not happening anymore!

**Comment by EllDoubleYew** [comment] 2016-08-19 13:11
I am running into this issue as well:
OSX: 10.11.2
Node: 4.4.5
Electron: 1.2.5

It has nothing to do with my file dialog but when I call my XHHTP requests.

**Comment by gammons** [comment] 2016-08-30 18:31
What @inferno1005 said is correct!  I ran into this issue as well, and it turns out that running the electron app from within `tmux` was the issue.

**Comment by zeke** [comment] 2016-08-31 19:56
It sounds like running the app from `tmux` is the issue. @svileng are you also using `tmux`?

**Comment by jbeard4** [comment] 2016-10-23 05:00
Confirmed this issue occurs for me when running electron from tmux. The problem is resolved when running the program outside of tmux.

**Comment by svileng** [comment] 2016-10-24 09:56
@zeke Yes, I do. I'm no longer working on that Electron project, so I cannot give it another go without tmux.

**Comment by zcbenz** [comment] 2017-06-06 01:54
Running Electron from tmux has some [unintended behaviors](https://github.com/electron/electron/issues?q=is%3Aissue+tmux+is%3Aclosed), I'm not sure whether is a bug of tmux or macOS, but we are not able to fix it on Electron's side, and tmux is not designed to be run any GUI program inside at all. So I'm closing this as won't fix.

**Closed by zcbenz** 2017-06-06 01:54 UTC
Labels: blocked, component/dialog, fixme/bug, platform/macOS
