### ISSUE TITLE
[Bug]: Set-Cookie is not exposed on response header

### ISSUE THREAD

**Issue by Vijayalakshmiushab** [electron/electron#29013] opened 2021-05-05 09:35 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.6

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

Hi,

The response header set-cookie is not present in the response. Pls check the below code. you can directly execute the code because url is used in the code has been exposed for public usage.

Code : 

const { app, BrowserWindow } = require('electron');
let mainWindow;
app.commandLine.appendSwitch('ignore-certificate-errors', 'true');

app.whenReady().then(() => {
    const { net } = require('electron')
    var option = {
        method: "POST",
        uri: "http://testhtml5.vulnweb.com/login",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded"
        },
        body: "username=admin&password=",
        redirect: "manual",
        useSessionCookies: true,
        credentials: "include"
    }
    const request = net.request(option)
    request.on('response', (response) => {
        console.log(response.statusCode);
        response.on('data', (chunk) => {
            //console.log(`BODY: ${chunk}`)
        })
        response.on('end', () => {
        })
    })
    request.on("redirect", (statusCode, method, redirectUrl, responseHeaders) => {
           if (option.redirect == "follow") {
            request.followRedirect();
        } else {
            console.log(responseHeaders["Set-Cookie"]);
            request.abort();
        }
    });
    request.write(option.body || "");
    request.end()
})

Ouptput is undefined. But i can assure you that set-cookie is exposed on response while using browser.  I have attached a browser screenshot.

![image](https://user-images.githubusercontent.com/57345061/117121846-ccff4f00-adb2-11eb-80a6-d3e19fcbd879.png)

Please let me know if you need further inputs.  

### Actual Behavior

set-cookie is not exposed on response header.

**Comment by Prinzhorn** [comment] 2021-05-05 09:56
https://www.electronjs.org/docs/api/incoming-message#responseheaders

> All header names are lowercased.

**Comment by Vijayalakshmiushab** [comment] 2021-05-05 10:14
Thank you for your reply. set-cookie headers are not exposed even with console.log(responseHeaders["set-cookie"]);

are you able to get set-cookie response header? you can directly run my above program and check the response.

**Comment by Prinzhorn** [comment] 2021-05-05 10:23
> you can directly run my above program and check the response.

I'm getting `ERR_CONNECTION_REFUSED`

This might be a Chromium issue with setting cookies in a 302 redirect, but it might also be entirely unrelated :shrug: 

https://bugs.chromium.org/p/chromium/issues/detail?id=696204
https://bugs.chromium.org/p/chromium/issues/detail?id=150066

**Comment by Vijayalakshmiushab** [comment] 2021-05-06 05:25
I think you are using old version of node.  So if you change the uri line to below, it will work for you.
url: "http://testhtml5.vulnweb.com/login",

And I confirm that set-cookie is exposed on chromium browser.  Pls check the below screenshot.

![image](https://user-images.githubusercontent.com/57345061/117245989-65e8a580-ae59-11eb-81e3-3ec89acb852e.png)


This is a breaking bug for me. It will be helpful for me if anyone suggested workaround.

**Comment by Prinzhorn** [comment] 2021-05-06 07:45
> I think you are using old version of node

I was using Electron 12.0.6 via [Electron Fiddle](https://github.com/electron/fiddle). Please provide a Fiddle gist that reproduces the problem.

**Comment by Vijayalakshmiushab** [comment] 2021-05-06 14:02
Thank you for your reply. i have created fiddle gist. Please check the below url.

https://gist.github.com/101e9ffb33b5cc5158288c39b020519f


OUTPUT OF ELECTRON FIDDLE :

![image](https://user-images.githubusercontent.com/57345061/117311408-ca2f5780-aea1-11eb-84a0-228ba1c666b5.png)

**Comment by Prinzhorn** [comment] 2021-05-06 15:22
Thanks, I can reproduce this now. It looks like `responseHeaders` is actually missing.

I've proxied the request through mitmproxy to see what's happening. And you can see in the screenshot that the server does send `set-cookie` but `responseHeaders` does not have it.

![Selection_879](https://user-images.githubusercontent.com/679144/117323699-6a2fb580-ae8f-11eb-98ed-9c8e819f71df.png)

**But it turns out this is a duplicate of #23865**. So it can be closed.

**Comment by nornagon** [comment] 2021-06-30 23:16
Duplicate of #23865

**Closed by nornagon** 2021-06-30 23:16 UTC
Labels: 12-x-y, bug :beetle:, platform/windows
