### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by brysgo** [electron/electron#9162] opened 2017-04-11 11:53 UTC
I totally understand why #562 was closed, but with android apps making their way to chromebooks, I think the android question should be reopened (given their [popularity](http://www.theverge.com/2016/5/19/11711714/chromebooks-outsold-macs-us-idc-figures)).

With tighter security through app sandboxing and fine grained permissions, mobile operating systems are an obvious choice for the future of desktops and laptops. While this will no doubt complicate our development environments a bit, it seems like bringing over extensible code editors/IDEs (at least a couple of which are written in electron) would be an obvious place to start.

**Comment by baconbrad** [comment] 2017-04-13 21:47
It isn't a matter of if it should be supported. It is a matter if it could be supported. And everyone came to the conclusion it is unlikely to be supported. And I suspect this issue will be closed due to the same conclusion. This wouldn't be as easy as changing some code and getting it to build for Android. There are a lot of incompatibilities and roadblocks preventing this from ever taking off.

**Comment by brysgo** [comment] 2017-04-14 01:01
I admit to not having a complete picture of the challenge, but where there is a will there's a way.

**Comment by timfish** [comment] 2017-05-04 09:24
You can already build an app that runs on electron, cordova, chromeOS and in the browser using a single codebase. I'm working on one right now. 

Anything that runs in a browser will run on all the platforms already and there are surprisingly few areas where native functionality overlaps. Even where it does overlap, why should the electron team attempt to solve a problem solved long ago by cordova?

The platform detection is trivial and for each you load different wrapper implementations depending on what is supported on that platform. I have a few simple wrappers which give a common interfaces over `fs` on electron and `cordova-plugin-file` on cordova, `powerSaveBlocker` on electron and `Insomnia-PhoneGap-Plugin` on cordova, `chrome.serial` on ChromeOS and `node-serialport` on electron, `cordova-plugin-bluetoothle` on cordova, `chrome.bluetooth` on ChromeOS, `sandeepmistry/noble` on electron, etc, etc.

The most complicated thing by far is getting the the build process setup to target all the different platforms and this can be achieved in the community with a few simple boilerplates.

**Comment by brysgo** [comment] 2017-05-04 10:36
Rather than having yet another boilerplate, I'd love to see a simple utility that builds an election app using a collection of API wrappers.

As somewhat of an aside, in the same way that babel became a generic transpiler, it might be cool to have a generic way to define API equivalencies and swap dependencies, or insert wrappers.

**Comment by timfish** [comment] 2017-05-04 11:13
Part of the problem is that much of the native functionality can't be abstracted out to a common interface without severely limiting desktop . For example, when it comes to file systems on mobile, file access varies so it's already had to be simplified to abstract out the differences between iOS/Android. In electron you can prompt the user for a save location with a dialog and save literally anywhere you have permissions. iOS doesn't have a file browser as app files are segregated per app. If you do try and abstract it out for electron too, you're either severely limiting desktop functionality or you have more than 1 API, and then you're back where you started.

Cordova already has as cli which does this and they now support Windows/OSX/Ubuntu as targets. However, plugins will only work if the plugin maintainer has added code for these platforms. Where they have, you will generally find that the API's are based around the least flexible platform (usually iOS) and this is the limiting factor.

**Comment by brysgo** [comment] 2017-05-04 17:23
> Part of the problem is that much of the native functionality can't be abstracted out to a common interface without severely limiting desktop . For example, when it comes to file systems on mobile, file access varies so it's already had to be simplified to abstract out the differences between iOS/Android. In electron you can prompt the user for a save location with a dialog and save literally anywhere you have permissions. iOS doesn't have a file browser as app files are segregated per app. If you do try and abstract it out for electron too, you're either severely limiting desktop functionality or you have more than 1 API, and then you're back where you started.

Just because the action of selecting a file is different on both platforms, doesn't mean they couldn't have a unified API. For instance, if you had your file prompt include a recommended location, the file picker could use that location on desktop to start at, but automatically choose the location on mobile.
> 
> Cordova already has as cli which does this and they now support Windows/OSX/Ubuntu as targets. However, plugins will only work if the plugin maintainer has added code for these platforms. Where they have, you will generally find that the API's are based around the least flexible platform (usually iOS) and this is the limiting factor.

I am much more a fan of the graceful degradation approach than being limited by the weakest link.

**Comment by zcbenz** [comment] 2017-06-15 08:14
Anyone wants this are free to contribute, we would be more than happy to merge pull requests on mobile support. Closing for the same reason with #562.

**Closed by zcbenz** 2017-06-15 08:14 UTC
Labels: triage/discussion

**Comment by trusktr** [comment] 2018-02-05 04:30
Here's how to do it, at least on Android, just do what this project does: [Termux](https://github.com/termux/termux-app)

Inside the Termux app sandbox, I can `apt-get install` things like `node`, `git`, `neovim`, etc, etc. It's Linux! I develop Node.js apps on my Android phone, and serve them on `localhost` and open them in the Android Chrome browser.

I'm sure that getting Electron to work like this is fairly easy now that we know how Termux works... (but I don't have time to spend on it right now, this is just conceptual)

**Comment by ericlewis** [comment] 2018-02-09 07:08
Termux runs docker apps on droid and docker has some dev environments setup for vscode avail. So you could probably tune the docker config and get it to work on droid. You should be able to bundle things like git and eslint or prettier too.
