### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Mr-zohaibkhalid** [electron/electron#27123] opened 2020-12-25 10:02 UTC
Getting this error after Upgrade my electron version from 9.1.2 to 11.1.1 and my app screen is blank. On Window 10
![electron error](https://user-images.githubusercontent.com/37456749/103131316-27461180-4655-11eb-8357-b82c113bd144.PNG)

**Comment by yiming1995** [comment] 2020-12-25 11:55
Hi, Did you set the node integration?
  const mainWindow = new BrowserWindow({
    width: 900,
    height: 600,
    frame: true,
    webPreferences: {
      nodeIntegration: true,   
    },
  });

**Comment by Mr-zohaibkhalid** [comment] 2020-12-25 11:58
Yes .. but still getting this error

**Comment by yiming1995** [comment] 2020-12-25 12:05
Can you upload your project? I think config may have mistakes.

**Comment by Mr-zohaibkhalid** [comment] 2020-12-25 12:52
Packeg.json
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
{
  "name": "arztis",
  "version": "8.0.0-alpha0008",
  "description": "Physician Information System",
  "main": "electron.js",
  "repository": "https://git.et-innovations.org/electron/arztis",
  "author": "Hernold Koch <hernold.koch@et-innovations.org>",
  "license": "",
  "private": true,
  "scripts": {
    "dev": "electron ."
  },
  "dependencies": {
    "archiver": "5.0.0",
    "comment-json": "3.0.2",
    "deepmerge": "4.2.2",
    "electron-store": "6.0.0",
    "fs-extra": "9.0.1",
    "jsonwebtoken": "8.5.1",
    "lodash": "4.17.19",
    "os": "0.1.1",
    "raven": "2.6.4",
    "raven-js": "3.27.2",
    "shelljs": "0.8.4",
    "yargs": "15.4.1"
  },
  "devDependencies": {
    "electron": "9.1.2",
    "colors": "1.4.0"
  }
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
electron.js

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/* global __dirname */

const app = require('electron').app
const args = require('yargs').parse(require('electron').argv)
const BrowserWindow = require('electron').BrowserWindow
const Config = require('electron-store')
const electron = require('electron')
const fs = require("fs-extra")
const json = require('comment-json')
const os = require('os')
const Raven = require('raven')
const { URL } = require('url')

let config = new Config()
let mainWindow = null // Keep a global reference of the window object
let server = null // Keep a global reference of the server object


// Sentry set-up (backend)
Raven.config('https://2842f5d94de64ce78ba569d9390edea2:1c865cba3d9849b78ed1b1a6d65f2e5a@sentry.et-innovations.org/9', {
  captureUnhandledRejections: true,
  tags: {
    process: process.type,
    electron: process.versions.electron,
    chrome: process.versions.chrome,
    platform: os.platform(),
    platform_release: os.release()
  }
}).install()


// config set-up
let defaultConfig = json.parse(fs.readFileSync(`${__dirname}/default-config.json`).toString())

if (JSON.stringify(config.store) == "{}") { config.store = defaultConfig }
else { update_config() }

// storage clean-up
// window.localStorage.clear();
// window.localStorage.removeItem("token")
global.jwt = {
  token: null
}


// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
app.on('ready', function () {
  load_app();

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});

// special behaviour for OS X, when clicking on icon in the dockbar.
app.on('activate-with-no-open-windows', function () {
  load_app();
});

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit();
  }
});


// SSL/TSL: this is the self signed certificate support
// see: https://electron.atom.io/docs/api/app/#event-certificate-error
app.on('certificate-error', (event, webContents, url, error, certificate, callback) => {
  // On certificate error we check if it's our internal API-Gateway
  // disable default behaviour (stop loading the page)
  // and we then say "it is all fine" to the callback
  let unsecureUrl = new URL(url)
  if (unsecureUrl.origin === args.server || config.get("apiGateway.host")) {
    event.preventDefault()
    callback(true)
  } else {
    callback(false)
  }
});

app.on('before-quit', (event) => {
  console.log(mainWindow.webContents.session.defaultSession)
})


function load_app() {
  let workArea = electron.screen.getPrimaryDisplay().workArea
  let windowConf = config.get("_window")

  // check & set window dimensions & position
  windowConf.height <= workArea.height || config.set("_window.height", Math.round(workArea.height * 2 / 3))
  windowConf.width <= workArea.width || config.set("_window.width", Math.round(workArea.width * 2 / 3))
  windowConf.x + windowConf.width <= workArea.width || config.set("_window.x", workArea.x)
  windowConf.y + windowConf.height <= workArea.height || config.set("_window.x", workArea.y)

  mainWindow = new BrowserWindow({
    frame: config.get("window.useNativeFrame"),
    height: config.get("_window.height"),
    icon: `${__dirname}/app/images/icon.png`,
    minHeight: 256,
    minWidth: 256,
    webPreferences: {
      nodeIntegration: true, // TODO refactor, cause it's insecure to allow all
      contextIsolation:true
    },
    width: config.get("_window.width"),
    x: config.get("_window.x"),
    y: config.get("_window.y")
  });
  mainWindow.setAutoHideMenuBar(true)
  mainWindow.setMenu(null)
  mainWindow.removeMenu()

  if (args.devTools) { mainWindow.openDevTools() }

  mainWindow.loadURL('file://' + __dirname + '/index.html');
  
  // Open the DevTools.
   mainWindow.webContents.openDevTools()
}

function update_config() {
  Object.keys(defaultConfig).forEach((key) => {
    let existingKey = Object.keys(config.store).find((k) => k == key)
    if (!existingKey || (existingKey && get_type(config.store[key]) != get_type(defaultConfig[key]))) {
      let updatedJson = config.store
      updatedJson[key] = defaultConfig[key]
      config.store = updatedJson
    }
  })
}

function get_type(data) {
  if (Array.isArray(data)) return 'array';
  else if (typeof data == 'string') return 'string';
  else if (data != null && typeof data == 'object') return 'object';
  else return 'other';
}
**/* global __dirname */

const app = require('electron').app
const args = require('yargs').parse(require('electron').argv)
const BrowserWindow = require('electron').BrowserWindow
const Config = require('electron-store')
const electron = require('electron')
const fs = require("fs-extra")
const json = require('comment-json')
const os = require('os')
const Raven = require('raven')
const { URL } = require('url')

let config = new Config()
let mainWindow = null // Keep a global reference of the window object
let server = null // Keep a global reference of the server object


// Sentry set-up (backend)
Raven.config('https://2842f5d94de64ce78ba569d9390edea2:1c865cba3d9849b78ed1b1a6d65f2e5a@sentry.et-innovations.org/9', {
  captureUnhandledRejections: true,
  tags: {
    process: process.type,
    electron: process.versions.electron,
    chrome: process.versions.chrome,
    platform: os.platform(),
    platform_release: os.release()
  }
}).install()


// config set-up
let defaultConfig = json.parse(fs.readFileSync(`${__dirname}/default-config.json`).toString())

if (JSON.stringify(config.store) == "{}") { config.store = defaultConfig }
else { update_config() }

// storage clean-up
// window.localStorage.clear();
// window.localStorage.removeItem("token")
global.jwt = {
  token: null
}


// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
app.on('ready', function () {
  load_app();

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});

// special behaviour for OS X, when clicking on icon in the dockbar.
app.on('activate-with-no-open-windows', function () {
  load_app();
});

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit();
  }
});


// SSL/TSL: this is the self signed certificate support
// see: https://electron.atom.io/docs/api/app/#event-certificate-error
app.on('certificate-error', (event, webContents, url, error, certificate, callback) => {
  // On certificate error we check if it's our internal API-Gateway
  // disable default behaviour (stop loading the page)
  // and we then say "it is all fine" to the callback
  let unsecureUrl = new URL(url)
  if (unsecureUrl.origin === args.server || config.get("apiGateway.host")) {
    event.preventDefault()
    callback(true)
  } else {
    callback(false)
  }
});

app.on('before-quit', (event) => {
  console.log(mainWindow.webContents.session.defaultSession)
})


function load_app() {
  let workArea = electron.screen.getPrimaryDisplay().workArea
  let windowConf = config.get("_window")

  // check & set window dimensions & position
  windowConf.height <= workArea.height || config.set("_window.height", Math.round(workArea.height * 2 / 3))
  windowConf.width <= workArea.width || config.set("_window.width", Math.round(workArea.width * 2 / 3))
  windowConf.x + windowConf.width <= workArea.width || config.set("_window.x", workArea.x)
  windowConf.y + windowConf.height <= workArea.height || config.set("_window.x", workArea.y)

  mainWindow = new BrowserWindow({
    frame: config.get("window.useNativeFrame"),
    height: config.get("_window.height"),
    icon: `${__dirname}/app/images/icon.png`,
    minHeight: 256,
    minWidth: 256,
    webPreferences: {
      nodeIntegration: true, // TODO refactor, cause it's insecure to allow all
      contextIsolation:true
    },
    width: config.get("_window.width"),
    x: config.get("_window.x"),
    y: config.get("_window.y")
  });
  mainWindow.setAutoHideMenuBar(true)
  mainWindow.setMenu(null)
  mainWindow.removeMenu()

  if (args.devTools) { mainWindow.openDevTools() }

  mainWindow.loadURL('file://' + __dirname + '/index.html');
  
  // Open the DevTools.
   mainWindow.webContents.openDevTools()
}

function update_config() {
  Object.keys(defaultConfig).forEach((key) => {
    let existingKey = Object.keys(config.store).find((k) => k == key)
    if (!existingKey || (existingKey && get_type(config.store[key]) != get_type(defaultConfig[key]))) {
      let updatedJson = config.store
      updatedJson[key] = defaultConfig[key]
      config.store = updatedJson
    }
  })
}

function get_type(data) {
  if (Array.isArray(data)) return 'array';
  else if (typeof data == 'string') return 'string';
  else if (data != null && typeof data == 'object') return 'object';
  else return 'other';
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
index.html

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
<!doctype html>
<html>

<head>
  <meta charset="utf-8">
  <title>ArztIS</title>

  <script>
    // Electron imports
    const _ = require('lodash')
    const args = require('yargs').parse(require('electron').remote.process.argv)
    const { clipboard, ipcRenderer, webFrame } = require('electron')
    const { app, BrowserWindow } = require('electron').remote
    const Config = require("electron-store")
    const config = new Config()
    const jwt = require("jsonwebtoken")

    let focusedWindow = BrowserWindow.getFocusedWindow()
    console.log("window ID", focusedWindow.id)
    // store window size on resize to settings
    // win.removeAllListeners()
    focusedWindow.on('resize', _.debounce(function () {
      let winBounds = focusedWindow.getBounds()

      config.set('_window.height', winBounds.height)
      config.set('_window.width', winBounds.width)
    }, 100))
    // store window position on move to settings
    focusedWindow.on('move', _.debounce(function () {
      let winBounds = focusedWindow.getBounds()

      config.set('_window.x', winBounds.x)
      config.set('_window.y', winBounds.y)
    }, 100))

    // set JWT authentication token for new windows
    ipcRenderer.on('token-changed', function (token) {
      document.getElementById('app').token = token
    });

    // set middleware-endpoint
    window.Arztis = window.Arztis || {}
    window.Arztis.middleware = window.Arztis.middleware || {}
    window.Arztis.middleware.server = args.server || config.get("apiGateway.host")
    window.Arztis.middleware.socketIoServer = config.get("apiGateway.socketIoHost")

    // set default-zoom level
    webFrame.setZoomFactor(config.get('window.zoom') || 1)
  </script>

  <link rel="import" href="app/arztis-app.html">

  <style>
    body {
      font-family: 'Roboto', 'Noto', 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-weight: 400;
      height: 100vh;
      letter-spacing: 0em;
      line-height: 1.43em;
      margin: 0;
      -webkit-font-smoothing: antialiased;
    }

    arztis-app {
      height: 100vh;
    }
  </style>
</head>

<body>
  <arztis-app id="app"></arztis-app>
</body>

</html>

**Comment by yiming1995** [comment] 2020-12-25 12:54
Can you upload as file?

**Comment by Mr-zohaibkhalid** [comment] 2020-12-25 12:59
[electronProjectFiles.zip](https://github.com/electron/electron/files/5741988/electronProjectFiles.zip)

**Comment by Mr-zohaibkhalid** [comment] 2020-12-25 13:01
Or if it's physible for you we can make a zoom call, I will show you my whole project.

**Comment by yiming1995** [comment] 2020-12-25 13:36
I tested with basic electron config file.
Please check result.
![image](https://user-images.githubusercontent.com/55419065/103136199-472f1100-46f9-11eb-8a88-d163a406bd00.png)

**Comment by Mr-zohaibkhalid** [comment] 2020-12-25 13:42
Can you please give me a minute on zoom call ? . or give me your Gmail id so I will give you my whole project

**Comment by Mr-zohaibkhalid** [comment] 2020-12-25 13:43
You getting this error because you didn't have to the whole project.

**Comment by yiming1995** [comment] 2020-12-25 13:48
I used only simple electron config file.
```
 mainWindow = new BrowserWindow({
    width: 900,
    height: 600,
    frame: true,
    webPreferences: {
      nodeIntegration: true,
      devTools: true,
      enableRemoteModule:true
    },
  });
```

**Comment by Mr-zohaibkhalid** [comment] 2020-12-25 13:52
what did you suggest I do?

**Comment by yiming1995** [comment] 2020-12-25 13:59
Please check this file.
[sample.zip](https://github.com/electron/electron/files/5742041/sample.zip)

**Comment by Mr-zohaibkhalid** [comment] 2020-12-25 14:05
i test this . it mean "focusedWindow" is Null

**Comment by codebytere** [comment] 2020-12-29 17:45
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. As such i'm going to close it, but if you would like us to triage this issue, you are welcome to fill out our **_required_** issue template with all requisite fields including reproducible sample.

**Closed by codebytere** 2020-12-29 17:45 UTC
