### ISSUE TITLE
[Bug]: Print Option "PageRanges" Not Work

### ISSUE THREAD

**Issue by 1339240789** [electron/electron#35446] opened 2022-08-25 07:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

11.4.10

### What operating system are you using?

Windows

### Operating System Version

win 11

### What arch are you using?

x64

### Expected Behavior

when i print ,this option pageRanges not work.
![image](https://user-images.githubusercontent.com/71307878/186599569-ce43a098-4897-4ce3-a62b-0b33341ef015.png)

### Actual Behavior

when i print ,this option pageRanges not work.
![image](https://user-images.githubusercontent.com/71307878/186599569-ce43a098-4897-4ce3-a62b-0b33341ef015.png)

**Comment by pushkin-** [comment] 2022-08-25 14:09
Are you seeing [this issue](https://github.com/electron/electron/issues/26318)?

**Comment by codebytere** [comment] 2022-08-26 07:41
Duplicate of https://github.com/electron/electron/issues/26318

**Closed by codebytere** 2022-08-26 07:41 UTC
Labels: bug :beetle:
