### ISSUE TITLE
Window edges not rounded

### ISSUE THREAD

**Issue by XENOTpro** [electron/electron#24650] opened 2020-07-20 18:22 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
9.1.0
* **Operating System:**
macOS 10.16 Beta 2
* **Last Known Working Electron version:**
none

### Expected Behavior
I would expect rounded corners.

### Actual Behavior
None of the four corners of the electron window are rounded like any other electron application.

### To Reproduce
Download electron-quick-start and start

### Screenshots
![image](https://user-images.githubusercontent.com/53019576/87972113-a9d70d80-cac6-11ea-9da7-932e4df0cc3a.png)

**Comment by codebytere** [comment] 2020-07-21 15:52
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. macOS 10.16 does not exist, and i cannot reproduce this on my computer.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by XENOTpro** [comment] 2020-07-21 16:09
Sorry, I actually thought I filled out the template. Can you tell me what information is missing, so I can append it?

**Comment by codebytere** [comment] 2020-07-21 16:25
> macOS 10.16 does not exist, and i cannot reproduce this on my computer.

**Comment by XENOTpro** [comment] 2020-07-21 16:47
Surely MacOS 10.16 does exist. It’s called MacOS Big Sur.

**Comment by codebytere** [comment] 2020-07-21 16:59
That would be macOS 11, and for more information about related bugs, see: https://github.com/electron/electron/issues/24319

**Closed by codebytere** 2020-07-21 16:59 UTC
Labels: 9-x-y, blocked/need-info ❌, platform/macOS
