### ISSUE TITLE
[Bug]: window-all-closed event not called and app.quit() not fired

### ISSUE THREAD

**Issue by lincdh** [electron/electron#34970] opened 2022-07-19 10:19 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.7

### What operating system are you using?

macOS

### Operating System Version

macos 12.2.1 (21D62)

### What arch are you using?

x64

### Expected Behavior

App quits after right click app icon and clicking Quit button or clicking the red X close button

### Actual Behavior

Window-all-closed event is not called at all. And app.quit() does not quit the app in mainWindow.on("closed", () => app.quit())  => cannot quit the app;

However in mainWindow.on("closed", () => app.exit()) quit the app successfully but with a Problem Report more like a crash:
![Screen Shot 2022-07-19 at 17 55 44](https://user-images.githubusercontent.com/21136244/179734225-0dd900c0-c803-4f85-a521-0dc7ab80f5f6.png)

### Additional Information

sample code: https://github.com/oliverfindl/electron-vue-boilerplate/blob/master/src/electron-app/main.js

**Comment by codebytere** [comment] 2022-07-19 11:57
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-07-29 08:23
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-07-29 08:23 UTC
Labels: platform/macOS, bug :beetle:, blocked/need-repro, 12-x-y
