### ISSUE TITLE
Frameless windows break mouse cursor on High DPI monitors with scaling

### ISSUE THREAD

**Issue by sbatten** [electron/electron#14787] opened 2018-09-24 22:10 UTC
* Operating System (Platform and Version): Ubuntu 18.04 amd64 

Tested Electron version 2.0.9 and 3.0.0

**Expected Behavior**
Elements set with cursor `text` should show the text cursor when using frameless windows on High DPI monitors with scaling higher than 100%.

**Actual behavior**
When using higher than 100% scaling on a high dpi monitor and frameless electron windows, elements with a text cursor revert to the default cursor half-way down the element.

**To Reproduce**
In VSCode you can enable the custom title bar by setting `window.titleBarStyle` to `custom`. This will use a frameless window. On a high DPI monitor with your display settings set to 200%, you can see that mousing around the editor reveals this bug. You can also repro this using Electron Fiddle and a single div in the page with cursor set to text. Make sure the div is fairly large (say 500px).

Initially reported in VSCode: https://github.com/Microsoft/vscode/issues/58383#issuecomment-423955747

**Comment by sofianguy** [comment] 2019-08-08 23:42
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by joaomoreno** [comment] 2019-08-09 06:02
@sofianguy This sounds very similar to https://github.com/electron/electron/issues/5723, where people are reporting that it still occurs on 6.0.0: https://github.com/electron/electron/issues/5723#issuecomment-517908005

**Comment by joaomoreno** [comment] 2019-09-25 09:19
This appears to be fixed on today's VS Code Insiders, which is based on Electron 6.0.9! :fireworks: 

Can you confirm @sbatten?

@sofianguy Did any work happen here?

**Comment by sbatten** [comment] 2019-09-25 18:07
confirmed that this does not repro in the latest insiders of VS Code using 6.0.9 as @joaomoreno suggests

**Comment by sofianguy** [comment] 2019-09-26 16:33
closing because this issue is reported as fixed

**Closed by sofianguy** 2019-09-26 16:33 UTC
Labels: 2-0-x, 3-0-x, 6-0-x, bug :beetle:, platform/linux
