### ISSUE TITLE
Error on "npm start" with "Ubuntu" version="18.04.2 LTS (Bionic Beaver)" 

### ISSUE THREAD

**Issue by abhishekvirtual** [electron/electron#19386] opened 2019-07-23 14:59 UTC
Hi there ,

we are using node v10.16.0 and npm 6.10.1 on the server environment, we already put 
X11Forwarding yes in /etc/ssh/sshd_config file but still having the issue with electron starter app 

(electron:2310): Gtk-WARNING **: 14:47:14.095: cannot open display: 127.0.0.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron --no-sandbox .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

please help me with the same

**Comment by codebytere** [comment] 2019-07-23 18:14
Duplicate of https://github.com/electron/electron-quick-start/issues/298.

**Closed by codebytere** 2019-07-23 18:14 UTC
