### ISSUE TITLE
[Bug]: Cannot change webview background color anymore

### ISSUE THREAD

**Issue by Akwd22** [electron/electron#31019] opened 2021-09-19 23:23 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

14.0.1

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Last Known Working Electron version

13.4.0

### Expected Behavior

When the property `backgroundColor` of the BrowserWindow is set with anything than white (eg. red), webviews contained in this BrowserWindow should have their background color set to the same color.
Same for transparency.

### Actual Behavior

When the property `backgroundColor` of the BrowserWindow is set with anything than white (eg. red), webviews contained in this BrowserWindow have their background color stay white.
If transparency is applied on the BrowserWindow, webviews stay opaque.

### Additional Information

I made sure that the background was set to `transparent` in my CSS webview html page.

**Comment by hgouveia** [comment] 2021-09-20 10:01
Same issue

**Comment by ramanjitsingh-hub** [comment] 2021-09-20 10:41
Hi a newbie can you guide me to solve this issue

**Comment by eelco** [comment] 2021-09-28 15:53
+1 for this issue.

We’re experiencing it on macOS.

it seems to be introduced in 14, version 13.5.0 works as expected too. All later versions have this bug (tested up to 16 alpha 1)

Note that we **don’t** set any background color on windows/views, and before this bug that meant that the background color of the HTML loaded in the `BrowserWindow` would be shown.

**Comment by VerteDinde** [comment] 2021-11-02 20:53
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. Thanks so much!

**Comment by eelco** [comment] 2021-11-02 21:18
@VerteDinde Wow, that’s a cool tool!

Here is a reproduction for this issue, I basically added one line (`mainWindow.setBackgroundColor("red")`) which works in 13.5.0 but does not work in the latest versions (sorry, did not do a full bisect): https://gist.github.com/80a2cc491e9c6320b703f98c5900137e

**Comment by miniak** [comment] 2021-11-06 05:27
Is this the same issue as #31686? Can you check if #31722 fixes it?

**Comment by theolivenbaum** [comment] 2021-11-16 08:43
Not sure if related, but on 15 and 16, calling setBackgroundColor on a transparent window with vibrancy enabled on macOS would disable the transparency and render a white background instead.

**Comment by codebytere** [comment] 2021-11-16 20:22
hey @eelco - i'm not sure why this used to work but it's documented that `backgroundColor` must be a hex value: https://github.com/electron/electron/blob/e6b1d95a1c328049d421390d92e61eb6d98e45da/docs/api/browser-window.md#L202-L204.

Tweaking your Fiddle to 

```
mainWindow.setBackgroundColor("#ff0000")
```

works perfectly.

**Comment by hgouveia** [comment] 2021-11-17 09:46
just checked out with **Electron 15.3.1** and **15.3.2** and transparent background is now working fine in the webview for me

**Comment by hovancik** [comment] 2021-11-23 16:24
Same issue on all platforms. Right now doing to workaround: 
-  send background color from main to renderer
- set background color with javascript for `document.body`

**Comment by arsinclair** [comment] 2021-12-02 08:48
This is something that started happening for me after I upgraded from 14.0.0 to 14.0.1. The culprit seems to be https://github.com/electron/electron/pull/30819, which states that `backgroundColor` option is now having an effect.

I don't know about everyone else, but for me it always worked, and upgrading to 14.0.1 actually breaks it. On 14.0.0 when an application starts it renders the correct background colour, and on 14.0.1 it starts with a white colour, and only after some time changes it to the desired colour.

I understand why does is happen from this comment https://github.com/electron/electron/issues/30759#issuecomment-909695092, however I don't see how as a consumer we can control that Blink setting.

How can this be fixed on a consumer side?

(I was trying to record a gif with actual behaviour, but oddly gif recorder shows the correct colour and not the white, however the white is seen on the screen)

**Comment by KorbsStudio** [comment] 2022-01-07 23:09
I think this is fixed now in Electron 16, I'm now able to change background to transparent by inserting CSS and the webview no longer shows a white background behind it.
I tested this with Glasstron as well.

**Comment by codebytere** [comment] 2022-01-12 09:22
Closed as fixed in v16

**Closed by codebytere** 2022-01-12 09:22 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro
