### ISSUE TITLE
Capture media for specified WebContents

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#4776] opened 2016-03-13 02:14 UTC
- Electron version: `0.37.0`
- Operating system: All

I've been trying for weeks now to figure this out, I need to somehow capture the audio output from my electron application.  But the `desktopCapturer` API appears to exclude that exact use case :cry: 

Is there an alternative way of performing this capture WITHOUT capturing the entire computers audio through the "screen" capturer?

https://github.com/atom/electron/blob/master/docs/api/desktop-capturer.md

Also open to any JS methods of capturing a stream from an Audio element

**Comment by MarshallOfSound** [comment] 2016-03-13 02:16
Worth noting the Chrome API I believe this was supposed to mirror / implement supports audio streams.

https://developer.chrome.com/extensions/tabCapture

**Comment by zcbenz** [comment] 2016-03-13 13:28
I don't think our current API set is capable of this.

**Comment by mgmorcos** [comment] 2016-07-04 02:11
+1

**Comment by demian85** [comment] 2017-03-07 15:45
Not sure why #7255 is closed since example in docs is still not working and thrown error does not provide info whatsoever.
From the docs:

> To capture both audio and video from the entire desktop the constraints passed to navigator.webkitGetUserMedia must include chromeMediaSource: 'screen', and audio: true, but should not include a chromeMediaSourceId constraint.

However, at least on Mac OSX, that throws `NavigatorUserMediaError` with no message.

Also, the constraints [spec](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints) has changed and `mandatory` property is not needed anymore.
`webkitGetUserMedia` has also changed to `mediaDevices.getUserMedia()`

**Comment by ajbdev** [comment] 2017-08-17 20:10
Will there be any attempt to fix this? 

Just out of curiosity, what is the blocking reason for this?

I can't figure out how to capture audio at all on Mac. On Windows I can capture audio from every possible input only (mic, apps, etc).

**Comment by mhashmi** [comment] 2017-09-14 07:25
Echoing what others are saying, I just tried audio / video capture on Mac (Sierra), Linux (Debian Jessie) and Windows 10 using the constraints specified in the desktopCapture API. As ajbdev noted, on Windows, the audio capture works correctly, however, on Linux and Mac we simply get an error (or more specifically, the error callback with no error defined). 

I have thus far tried with Electron 1.7.6 and 1.6.5[1] with similar results. Is there any version we can switch to where audio capture works? Is it perhaps possible to capture audio and video separately and add the audio track to the video stream? 

[1] Electron v1.6.5 does not throw an error on the constraints[2] outlined in the desktopCapture API, however, we get a audio sync state error in the terminal when the video stream is initialised. 

[2] Passing constraints: 

```
let constraints = {
  audio: {
    mandatory: {
      chromeMediaSource: 'desktop'
    }
  },
  video: {
    mandatory: {
      chromeMediaSource: 'desktop'
    }
  }
} 
```

**Comment by CapOM** [comment] 2018-02-21 15:47
Have you tried chrome.desktopCapture.chooseDesktopMedia ? (doc https://developer.chrome.com/extensions/desktopCapture)

**Comment by icecoll** [comment] 2018-04-11 01:30
- electron v1.8.4
- Ubuntu 16.04
```
function startRecord() {
    electron.desktopCapturer.getSources({types: ['window', 'screen']}, (error, sources) => {
      if (error) throw error
      for (let i = 0; i < sources.length; ++i) {
        if (sources[i].name === "foo") {
          navigator.mediaDevices.getUserMedia({
            audio: false,
            video: {
              mandatory: {
                chromeMediaSource: 'desktop',
                chromeMediaSourceId: sources[i].id,
                minWidth: 1280,
                maxWidth: 1280,
                minHeight: 720,
                maxHeight: 720
              }
            }
          })
            .then((stream) => handleStream(stream))
            .catch((e) => handleError(e))
          return
        }
      }
    });
}

function handleStream(stream) {
    navigator.mediaDevices.getUserMedia({audio: true, video: false}).then(function(mediaStream){
      const audioTrack = mediaStream.getAudioTracks()[0];
      stream.addTrack(audioTrack);
      recorder = new MediaRecorder(stream);
      recorder.ondataavailable = function(event) {
        // deal with your stream
      };
      recorder.start(1000);
    }).catch(function(err) {
      //console.log("handle stream error");
    })
}

```
It works! [reference](https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API)

**Comment by mhashmi** [comment] 2018-04-11 09:56
@icecoll That worked, many thanks!

**Comment by mhashmi** [comment] 2018-04-12 15:15
@icecoll the capture is unfortunately from the microphone. I confirmed too quickly as I had headphones attached to my mac which were lying next to where the mac's microphone is, hence the confusion. 

Other in the bug report I opened (#10515)  pointed this out.

**Comment by icecoll** [comment] 2018-05-18 01:59
I think `getUserMedia` can only get the microphone's sound but not the speaker and headphone's, if you want to get the output device sound, you must try other way. If you just want to get sound from `<video>/<audio>` tags, I think you can try to use `getAudioTracks` method, and add the audio tracks to your stream.

**Comment by gio1217** [comment] 2018-05-28 14:43
same issue

**Comment by bhavinshiroya1994** [comment] 2018-05-29 10:18
@icecoll same problem please solve this issue.

**Comment by peererror** [comment] 2018-05-30 12:20
is any way to get speaker audio from webrtc or apps audio

**Comment by m-onz** [comment] 2018-06-12 20:28
Same issues... I have not got any audio working on osx or linux

**Comment by AmarBouchibane** [comment] 2018-10-12 08:50
> @icecoll the capture is unfortunately from the microphone. I confirmed too quickly as I had headphones attached to my mac which were lying next to where the mac's microphone is, hence the confusion.

I ran into the same mistake. I hope this will be fixed someday.

**Comment by danmo** [comment] 2019-02-25 09:07
2019 - no luck, hope is still strong on this one.

**Comment by 4eveRS** [comment] 2019-06-26 06:33
Any update on this enhancement request? looking forward for it.

**Closed** 2020-05-26 20:34 UTC
Labels: enhancement :sparkles:
