### ISSUE TITLE
User agent set on <webview> is not used in some of the requests

### ISSUE THREAD

**Issue by ajarosz** [electron/electron#7203] opened 2016-09-14 12:13 UTC
- Electron version: 1.3.2 prebuilt
- Operating system: Win8.1

I have a <webview> tag with custom user agent value, set via useragent property. Using proxy sniffer I can observe that when the webpage is being loaded into that webview, some of the resources are requested with user agent different than set. My server responds with different resources based on which user agent is used for request thus some of the requested resources are invalid.
Invalid user agent has following format:
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) electron-app-name/0.0.1 Chrome/52.0.2743.82 Electron/1.3.2 Safari/537.36

It looks like every run gives different set of resources requested with wrong user agent. I suspect that this issue might be related to the application cache mechanism (all these resources are defined in cache manifest).

**Comment by kevinsawicki** [comment] 2016-09-16 22:39
Are you able to provide a URL or example application to help reproduce this?

**Comment by kevinsawicki** [comment] 2016-11-15 22:37
Closing this issue out since further details weren't provided in the last 2 months.

If you are still experiencing this please comment with an example URL or application that demonstrates the issue and we'll reopen this, thanks.

**Closed by kevinsawicki** 2016-11-15 22:37 UTC
Labels: more-information-needed
