### ISSUE TITLE
Crash the electron when I start to enter a command in the console

### ISSUE THREAD

**Issue by danyadev** [electron/electron#11744] opened 2018-01-26 21:13 UTC
* Electron version: v1.8.2-beta.4
* Operating system: Windows 7 Ultimate x64

### Expected behavior

Enter the command and its execution

### Actual behavior

the electron crash when I start enter the command

### How to reproduce

1) open developer tools
2) open console
3) try to enter any character (and you will get a crash)

**Comment by brenca** [comment] 2018-01-26 21:28
Closing as a duplicate of #11732

**Closed by brenca** 2018-01-26 21:28 UTC
