### ISSUE TITLE
ipcMain.handle() return misformated error on reject

### ISSUE THREAD

**Issue by popod** [electron/electron#25196] opened 2020-08-28 17:46 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  9.2.1
* **Operating System:**
  *  macOS Catalina
* **Last Known Working Electron version:**
  * 

### Expected Behavior

When `ipcMain.handle()` return a rejected promise, no message should be printed on the main console and the error message in `ipcRenderer.invoke().reject()` should contain the exact error message.

### Actual Behavior

When `ipcMain.handle()` return a rejected promise, a message like this is printed in the main console:

```
Error occurred in handler for '<channel>': Error: <rejected error message>

-> the attempted result here is that no message should be displayed in main console !
```

And the `ipcRenderer.invoke().reject()` error message is:

```
Error invoking remote method '<channel>': Error: my-error

-> the attempted error message here is only "Error: my-error"
```

### To Reproduce

main.js

```
ipcMain.handle('channel', (event, options) => {
  return Promise.reject(new Error('my-error'))
})
```

renderer.js

```
ipcRenderer.invoke('channel').then(result => {
  console.log(result)
}).catch(err => {
  console.log(err)
})
```

**Comment by twitharshil** [comment] 2020-10-06 13:00
Same behavior on electron v7.3.2

**Comment by noahlevenson** [comment] 2020-10-25 16:10
I'm on Electron 10.1.5 and experiencing the same behavior.  It would be nice to have more exact control over the reason returned in the Promise rejection, if only to make it less painful to integrate remote method calls with one's logging system.

**Comment by HSalah-EP** [comment] 2020-10-30 19:03
HI,

I'm not sure if it's the question, but you can define a throw statement on your main process, you will have to catch the error on your renderer process:

#### main

    ipcMain.handle('channel', (event, options) => {
      if (true) {
          // do anything
      } else  throw "error"
    })

#### renderer

    ipcRenderer.invoke('channel').then(r=> console.log(r)).catch(err => console.log(err))

Bye!

**Comment by nornagon** [comment] 2020-10-30 20:25
Duplicate of #24427

**Closed by nornagon** 2020-10-30 20:25 UTC
Labels: 9-x-y, bug :beetle:, platform/macOS

**Comment by m4heshd** [comment] 2021-03-05 00:58
@HSalah-EP I think you can't. I tried it but can't seem to catch the error. Did you try it? Nothing in the documentation.
