### ISSUE TITLE
Inconsistent behavior when setting the window title to an empty string

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#19151] opened 2019-07-08 15:00 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.6
  * 
* **Operating System:** macOS Mojave
  * 
* **Last Known Working Electron version:**
  *  n/a

### Expected Behavior

Calling `BrowserWindow.setTitle ( '' )` should have a consistent effect across all platforms.

### Actual Behavior

In macOS when I set the title to an empty string it kind of resets itself to the application name.

In linux (Lubuntu 18) instead my windows have "Unnamed Window" as title.

### To Reproduce

call `#setTitle ( '' )` on a window in Linux.

**Comment by erickzhao** [comment] 2019-07-08 18:42
Closing as duplicate of https://github.com/electron/electron/issues/19152!

**Closed by erickzhao** 2019-07-08 18:42 UTC
