### ISSUE TITLE
[Bug]: BrowserWindow `restore` event fires late (non-maximized) or not at all (maximized)

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#28570] opened 2021-04-07 21:03 UTC
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10; 20H2

### What arch are you using?

x64

### Expected Behavior

I expect that the restore event fires when restoring a previously maximized window

### Actual Behavior

restore event doesn't fire. It only fires for normal state windows

1. start app
2. maximize window
3. minimize window
4. restore window
5. see that "restored" isn't logged to the console, but is if you skipped step 2

main.js:
```
const {app, BrowserWindow } = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow();
  mainWindow.on("restore", () => {
    console.log("restored");
  });
}

app.whenReady().then(() => {
  createWindow()
  
  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

**Comment by clavin** [comment] 2021-08-07 02:23
I was trying this out just now. I can confirm this happens. Additionally, in my testing non-maximized windows have their `restore` event show up very late. For me, it was when the window closes/app exits (not sure which exactly).

**Comment by pushkin-** [comment] 2021-08-07 02:36
@clavin Hm, I couldn't repro the behavior you're seeing in my Electron 11 app. For me, it fires immediately

**Comment by clavin** [comment] 2021-08-07 02:53
Oh! Sorry, that behavior is only on v12+. I figured that was implied from the issue text & labels.

**Comment by XfaonAE** [comment] 2021-08-07 18:03
Sometimes window.isMaximised() always seems to return false on frameless windows. I fixed it by re-enabling the frame and then disableing it. That fixed it somehow, i'm not sure why

**Comment by mlaurencin** [comment] 2022-08-25 18:08
With https://github.com/electron/electron/pull/35342 merged, I will close this issue as well. As mentioned in https://github.com/electron/electron/issues/35223, I was not able to reproduce the firing late portion of this issue, so if that problem still remains, this issue can be reopened.

**Closed by mlaurencin** 2022-08-25 18:08 UTC
Labels: platform/windows, bug :beetle:, bug/regression :leftwards_arrow_with_hook:, component/BrowserWindow, 12-x-y, 13-x-y, has-repro-comment, 16-x-y, 19-x-y
