### ISSUE TITLE
[Bug]: RequestError: certificate has expired

### ISSUE THREAD

**Issue by jianggangsheng** [electron/electron#41133] opened 2024-01-26 05:39 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

npm i electron

### What operating system are you using?

macOS

### Operating System Version

Darwin MacBook-Pro.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64

### What arch are you using?

x64

### Expected Behavior

npm install --save-dev electron  

### Actual Behavior

npm install --save-dev electron  

npm ERR! RequestError: certificate has expired

**Comment by TueWords** [comment] 2024-01-26 05:49
I have the same problem

**Comment by cnryb** [comment] 2024-01-26 07:02
> I have the same problem

+1

**Comment by TueWords** [comment] 2024-01-26 08:28
虽然不是好的方法，但起码解决了。
![image](https://github.com/electron/electron/assets/74801131/e8196d4c-7a1c-4c2c-9b1b-51fdb9e27249)

**Comment by TueWords** [comment] 2024-01-26 08:29
虽然不是好的方法，但起码解决了我的问题
![image](https://github.com/electron/electron/assets/74801131/a42c9e2e-fdaa-404e-9183-cc6f560eefe3)

**Comment by ckerr** [comment] 2024-01-26 21:04
Duplicate of https://github.com/electron/electron/issues/41089

**Closed by ckerr** 2024-01-26 21:04 UTC
Labels: bug :beetle:
