### ISSUE TITLE
[Bug]: hover on Picture-in-Picture video player show red background

### ISSUE THREAD

**Issue by CN-Tower** [electron/electron#35205] opened 2022-08-03 13:25 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

macOS

### Operating System Version

MacBook Pro (13-inch, M1, 2020)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

17.4.10

### Expected Behavior

should be an nomore min video player:
![image](https://user-images.githubusercontent.com/20727404/182618393-a62878ce-80a4-4325-a5d9-e92748c698bb.png)

### Actual Behavior

got an red player when hover it:
![image](https://user-images.githubusercontent.com/20727404/182618979-632fd6c5-d7ef-44d9-9596-fe9b65652a66.png)

**Comment by codebytere** [comment] 2022-08-03 13:40
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by CN-Tower** [comment] 2022-08-04 02:59
@codebytere Demo here: https://gist.github.com/605dea9d8a92149f908114bf389178f4

**Comment by codebytere** [comment] 2022-08-04 11:06
Duplicate of https://github.com/electron/electron/issues/34406

**Closed by codebytere** 2022-08-04 11:06 UTC
Labels: bug :beetle:, blocked/need-repro
