### ISSUE TITLE
CSS support in different OS's

### ISSUE THREAD

**Issue by iremlopsum** [electron/electron#8903] opened 2017-03-10 23:39 UTC
Not sure if related directly to Electron, but will probably get an answer here.

On Windows position: sticky; works perfectly, but on Mac it's not supported. Any ideas?

**Comment by deprilula28** [comment] 2017-03-16 15:52
I don't have a mac, but in my iPad the sticky position doesn't work either, maybe it's an apple system thing.

**Comment by kevinsawicki** [comment] 2017-03-31 22:25
> On Windows position: sticky; works perfectly, but on Mac it's not supported. Any ideas?

@iremlopsum are you seeing the same behavior in standalone Chrome?

**Comment by iremlopsum** [comment] 2017-03-31 22:31
@kevinsawicki Nope. standalone chrome works like a charm. Using electron version 1.6.0

**Comment by kevinsawicki** [comment] 2017-03-31 22:37
> Nope. standalone chrome works like a charm. Using electron version 1.6.0

What version of Chrome did you try? Looks like there are several sticky issues on mac that fixed and still open, https://bugs.chromium.org/p/chromium/issues/list?can=1&q=sticky+OS%3DMac+&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids

Can you include a small reproduction example that shows the issue you are seeing? Thanks.

**Comment by kevinsawicki** [comment] 2017-05-31 16:55
Closing this out until more information is available.

**Closed by kevinsawicki** 2017-05-31 16:55 UTC
Labels: more-information-needed
