### ISSUE TITLE
Fetching google.com through the node.js request module crashes randomly on Electron 5

### ISSUE THREAD

**Issue by ruslang02** [electron/electron#17007] opened 2019-02-16 17:46 UTC
* **Electron Version**:
  * 5.0.0-beta (all)
* **Operating System**:
  * Ubuntu 18.10, Linux 4.18, x64
* **Last known working Electron version** (if applicable):
  * 4.0.5

### Expected Behavior
Google API should work as it they are meant to.

### Actual behavior
Any Google API calls may crash renderer process (even if they are run on Worker thread).
The request may be done and the answer given, but immediately or after several seconds the renderer process may crash.

### To Reproduce
```sh
$ git clone https://github.com/ruslang02/youtube-electron-crash-example
$ npm install electron@beta
$ npm start || electron .
```
Version 5 will randomly crash, version 4: doesn't

### Additional Information
May be a Node.JS bug, but not sure

**Comment by CopyNippyJoin** [comment] 2019-02-17 01:15
I have a similar issue were a https request from node (via the request module) crashes electron and can also crash a node child process. Just doing one request isn't enough, it also needs some interaction (adding elements to dom, minimizing/maximizing, etc.), but it isn't really predictable. 

Example: https://github.com/CopyNippyJoin/electron-quick-start

**Comment by ruslang02** [comment] 2019-02-28 13:18
This issue continues to `5.0.0-beta.4` as well

**Comment by ruslang02** [comment] 2019-03-08 21:12
Same issue on `5.0.0-beta.5`

**Comment by zcbenz** [comment] 2019-03-27 05:31
It seems that something wrong happened in navigation controller.

Crash stack trace:

```
[9118:0327/143018.997984:FATAL:navigation_controller_impl.cc(2410)] Check failed: !replace. 
0   Electron Framework                  0x0000000118729a49 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x00000001186154d8 logging::LogMessage::~LogMessage() + 232
2   Electron Framework                  0x00000001176d9909 content::NavigationControllerImpl::InsertOrReplaceEntry(std::__1::unique_ptr<content::NavigationEntryImpl, std::__1::default_delete<content::NavigationEntryImpl> >, bool) + 313
3   Electron Framework                  0x00000001176d747b content::NavigationControllerImpl::RendererDidNavigateToNewPage(content::RenderFrameHostImpl*, FrameHostMsg_DidCommitProvisionalLoad_Params const&, bool, bool, bool, content::NavigationHandleImpl*) + 2555
4   Electron Framework                  0x00000001176d60ca content::NavigationControllerImpl::RendererDidNavigate(content::RenderFrameHostImpl*, FrameHostMsg_DidCommitProvisionalLoad_Params const&, content::LoadCommittedDetails*, bool, bool, content::NavigationRequest*) + 1370
5   Electron Framework                  0x00000001176f5aea content::NavigatorImpl::DidNavigate(content::RenderFrameHostImpl*, FrameHostMsg_DidCommitProvisionalLoad_Params const&, std::__1::unique_ptr<content::NavigationRequest, std::__1::default_delete<content::NavigationRequest> >, bool) + 586
6   Electron Framework                  0x000000011770c4af content::RenderFrameHostImpl::DidCommitNavigationInternal(content::NavigationRequest*, FrameHostMsg_DidCommitProvisionalLoad_Params*, bool) + 1103
7   Electron Framework                  0x000000011770bb25 content::RenderFrameHostImpl::DidCommitNavigation(content::NavigationRequest*, std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) + 1205
8   Electron Framework                  0x000000011770bcfa non-virtual thunk to content::RenderFrameHostImpl::DidCommitProvisionalLoad(std::__1::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::__1::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>) + 58
9   Electron Framework                  0x00000001154fa543 content::mojom::FrameHostStubDispatch::Accept(content::mojom::FrameHost*, mojo::Message*) + 2419
10  Electron Framework                  0x00000001189c63b6 mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*) + 950
11  Electron Framework                  0x00000001189c5cd6 mojo::FilterChain::Accept(mojo::Message*) + 150
12  Electron Framework                  0x00000001189c7775 mojo::InterfaceEndpointClient::HandleIncomingMessage(mojo::Message*) + 117
13  Electron Framework                  0x0000000118f67529 IPC::(anonymous namespace)::ChannelAssociatedGroupController::AcceptOnProxyThread(mojo::Message) + 761
14  Electron Framework                  0x0000000118f649f4 base::internal::Invoker<base::internal::BindState<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message), scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController>, base::internal::PassedWrapper<mojo::Message> >, void ()>::RunOnce(base::internal::BindStateBase*) + 228
15  Electron Framework                  0x000000011868f093 base::TaskAnnotator::RunTask(char const*, base::PendingTask*) + 323
16  Electron Framework                  0x00000001186abaaf base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*) + 719
17  Electron Framework                  0x00000001186abfe6 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() + 150
18  Electron Framework                  0x000000011875f443 base::MessagePumpCFRunLoopBase::RunWork() + 51
19  Electron Framework                  0x00000001185e7aca base::mac::CallWithEHFrame(void () block_pointer) + 10
20  Electron Framework                  0x000000011875ec2f base::MessagePumpCFRunLoopBase::RunWorkSource(void*) + 63
```

**Comment by zcbenz** [comment] 2019-04-08 08:11
After investigation, I found that this is a duplicate of #17309.

**Closed by zcbenz** 2019-04-08 08:11 UTC
Labels: 5-0-x, bug :beetle:
