### ISSUE TITLE
WebContents.capturePage can freeze browser process

### ISSUE THREAD

**Issue by CezaryKulakowski** [electron/electron#27891] opened 2021-02-24 16:01 UTC
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 13.0.0-nightly.20210223
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * It probably never worked

### Expected Behavior
Call to BrowserWindow.webContents.capturePage does not freeze the application.

### Actual Behavior
Call to BrowserWindow.webContents.capturePage freezes the application.

### To Reproduce
Run following app:
```
const { app, BrowserWindow } = require('electron')

function startTest() {
  let win = new BrowserWindow();

  win.on('hide', () => {
    // We have to wait a moment as 'hide' is called too soon
    // and windows isn't really hidden at this point.
    setTimeout( () => {
      win.webContents.capturePage();
      app.quit();
    }, 100);
  });

  win.webContents.loadURL('about:blank');
  win.hide();
}

app.on('ready', startTest)
```

**Comment by pushkin-** [comment] 2021-02-24 18:34
I think this can be closed as a dupe of [this](https://github.com/electron/electron/issues/6015) @codebytere assigned that issue to herself yesterday FYI

**Comment by codebytere** [comment] 2021-02-24 18:35
I think it is - i'm also not sure that we want to solve this recursively as in your PR.

**Closed** 2021-03-09 13:51 UTC
Labels: 11-x-y, 12-x-y, component/webcontents, performance :checkered_flag:, platform/all
