### ISSUE TITLE
app.getPath('pepperFlashSystemPlugin') exception !!!!

### ISSUE THREAD

**Issue by StringKe** [electron/electron#17603] opened 2019-03-29 08:59 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.1
* **Operating System:**
  * windows7
* **Last Known Working Electron version:**:
  * none

### Expected Behavior
load flash plugin and no exception

### Actual Behavior
![image](https://user-images.githubusercontent.com/31089228/55221066-a7063880-5243-11e9-9503-6822310ca3c7.png)

### To Reproduce
in win7
```javascript
const flashPath = app.getPath('pepperFlashSystemPlugin'); // error
if (flashPath && ['dll', 'so', 'plugin'].forEach(item => flashPath.endsWith(item))) {
      app.commandLine.appendSwitch('ppapi-flash-path', flashPath);
}
```

### Screenshots
![image](https://user-images.githubusercontent.com/31089228/55221066-a7063880-5243-11e9-9503-6822310ca3c7.png)

### Additional Information
none

**Comment by StringKe** [comment] 2019-03-29 09:00
index.js
```javascript
import { app, BrowserWindow, ipcMain } from 'electron';
import fs from 'fs';

if (process.env.NODE_ENV !== 'development') {
  global.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\');
}

let mainWindow;
const winURL = process.env.NODE_ENV === 'development'
  ? 'http://localhost:9080/index.html'
  : `file://${__dirname}/index.html`;

process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = true;

class Browser {
  createWindow() {
    mainWindow = new BrowserWindow({
      show: false,
      height: 620,
      width: 1240,
      minHeight: 430,
      minWidth: 800,
      useContentSize: true,
      frame: false,
      webSecurity: false,
      allowRunningInsecureContent: true,
      fullscreenWindowTitle: false,
      webPreferences: {
        plugins: true,
      },
    });
    mainWindow.loadURL(winURL);
    mainWindow.once('ready-to-show', () => {
      mainWindow.show();
    });
  }

  start() {
    const flashPath = app.getPath('pepperFlashSystemPlugin');
    if (flashPath && ['dll', 'so', 'plugin'].forEach(item => flashPath.endsWith(item))) {
      app.commandLine.appendSwitch('ppapi-flash-path', flashPath);
    }
    app.on('ready', this.createWindow);
    app.on('window-all-closed', () => {
      if (process.platform !== 'darwin') {
        app.quit();
      }
    });
    app.on('activate', () => {
      if (mainWindow === null) {
        this.createWindow();
      }
    });
    this.listenRender();
  }

  listenRender() {
    ipcMain.on('fun-minWindow', (event, obj) => {
      mainWindow.minimize();
    });
    ipcMain.on('fun-closeWindow', (event, obj) => {
      app.quit();
      app.exit(0);
    });
    ipcMain.on('fun-reStart', (event, obj) => {
      app.relaunch({ args: process.argv.slice(1).concat(['--relaunch']) });
      app.exit(0);
    });
    ipcMain.on('fun-maxWindow', (event, obj) => {
      if (mainWindow.isMaximized()) {
        mainWindow.unmaximize();
        mainWindow.setSize(1000, 560);
      } else {
        mainWindow.maximize();
      }
    });
  }
}

new Browser().start();
```

**Comment by Galunid** [comment] 2019-03-29 19:52
Perhaps https://github.com/electron/electron/issues/8469#issuecomment-277086664 explains this behavior.

**Comment by StringKe** [comment] 2019-03-30 01:15
> Perhaps [#8469 (comment)](https://github.com/electron/electron/issues/8469#issuecomment-277086664) explains this behavior.

I use electron to make a browser. In theory, I should read the flash that the user has installed. Otherwise, I will update my program every time the flash is updated.

**Comment by miniak** [comment] 2019-05-12 19:25
Duplicate of https://github.com/electron/electron/issues/8469

**Closed by miniak** 2019-05-12 19:25 UTC
Labels: 4-2-x, bug :beetle:, platform/windows

**Comment by miniak** [comment] 2019-05-12 19:26
Electron does not implement this directly, it just calls https://cs.chromium.org/chromium/src/chrome/common/chrome_paths.cc?type=cs&q=FILE_PEPPER_FLASH_SYSTEM_PLUGIN&sq=package:chromium&g=0&l=308
