### ISSUE TITLE
[Feature Request]: PointerLock

### ISSUE THREAD

**Issue by latel88** [electron/electron#33587] opened 2022-04-03 02:03 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Problem Description

I am developing and distributing a FPS game using electron on Steam.
In 18.0.1, pointerLock is now the same as the web specification, as a result if you remove the pointerLock and lock it again, an error will occur if a certain amount of time has not elapsed.
This specification is quite troublesome for game developers.

### Proposed Solution

`
  new BrowserWindow({
    webPreferences: {
      disablePointerLockWait: true
    }
  })
`

### Alternatives Considered

Could you add an option to BrowserWindow's options (or others, of course) to disable this waiting time?

**Comment by codebytere** [comment] 2022-04-04 07:49
@latel88 does this waiting behavior occur differently from Chrome? Our implementation is intended to adhere to that in https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API, and so if this behavior occurs there as well this is something we consider intended behavior and would heavily prefer not to diverge from.

**Comment by latel88** [comment] 2022-04-04 08:00
ok thank you

**Comment by latel88** [comment] 2022-04-04 12:48
Sorry, I am not fluent in English.

**Comment by zcbenz** [comment] 2022-04-06 01:48
Can you check if the [WebContents.setBackgroundThrottling](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentssetbackgroundthrottlingallowed) API can suppress this behavior?

**Comment by latel88** [comment] 2022-04-07 04:57
I could not suppress the behavior with setBackgroundThrottling on my application.
Would it be better to try it on an electron that is as clean status as possible?

**Comment by lachsen** [comment] 2022-06-22 18:45
Hi! Another game developer that is bothered by this feature.
The time-delay to restart a pointerLock makes sense in the browser context, where the user must be quaranteed a way to escape the lock.
But for a Desktop application (especially games) you want to have the flexibility to disable this. Otherwise, certain control schemes are simply not possible.

**Comment by latel88** [comment] 2022-06-23 08:53
Most games are more CPU and GPU intensive than most applications, and if you deactivate an application, it should recognize this and reduce its load. This is because the user may open a browser to look up information about the game and thus make the application inactive. Therefore, I do not want to stop throttling with "setBackgroundThrottling", at least I do not want to.

**Comment by codebytere** [comment] 2024-05-30 13:13
Closing as we currently see this as intended behavior and isn't something we're prepared to diverge from Chromium and therefore patch to achieve. Should something change, we'll re-open this.

**Closed by codebytere** 2024-05-30 13:13 UTC
Labels: enhancement :sparkles:

**Comment by Tonihtml** [comment] 2025-12-24 23:59
Hi i am also making a game and this delay is very annoying i understand that its a safety feature ad i honestly have no idea how to solve this issue without lacking safety. since i also use electron for my project does anyone have an idea if at this point in time there is a way to remove or at least shorten the delay? right now i just set a boolean to true wich tries to lock every frame after click wich results in a lot of errors in teh console and eventually locks the cursor. this just isnt nice for production
