### ISSUE TITLE
[Bug]: ERROR:service_worker_storage.cc(1904)] Failed to delete the database: Database IO error

### ISSUE THREAD

**Issue by vishnuc** [electron/electron#35036] opened 2022-07-23 08:37 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

macOS

### Operating System Version

Mac OS monterey version 12.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

There should be no error while navigating the pages

### Actual Behavior

But I keep getting following error 

`[61692:0723/135956.830004:ERROR:service_worker_storage.cc(1904)] Failed to delete the database: Database IO error
` 

### Additional Information

hi , I get following error rangomly when i am loading url like https://google.com etc , when i do the same activity again its not occuring again.. but it occurs again randomly.

Also because of this error , some webpages are not loading fine with following error

`Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The document is in an invalid state.
`

**Comment by VerteDinde** [comment] 2022-07-25 02:43
Thanks for reporting this issue! Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance!

**Comment by vishnuc** [comment] 2022-07-26 05:44
Hi, this bug is appearing when I open two times.

**Comment by pushkin-** [comment] 2022-11-09 18:35
still repros in v21. This might be a dupe of [this](https://github.com/electron/electron/issues/33801). I see both errors in my terminal when running two apps at once.

**Comment by paralin** [comment] 2022-11-10 07:55
I have the same issue when running two Electron instances at once.

**Comment by nicszerman** [comment] 2022-11-26 01:57
+1; having this issue

**Comment by nornagon** [comment] 2022-11-29 20:57
Running multiple instances of an app with the same user-data directory isn't supported by Chrome, and thus isn't supported by Electron either. You'll need to use requestSingleInstanceLock, an in-memory session, or a separate data directory for each instance.

**Closed by nornagon** 2022-11-29 20:57 UTC
Labels: bug :beetle:, blocked/need-repro

**Comment by Tatsujinichi** [comment] 2023-01-19 09:52
I see this very often, when ever I do a git commit, and fill out the commit message in the editor.  After closing the editor tab.

**Comment by sellerofair** [comment] 2023-01-28 05:51
heaving the issue while commiting.
i use vscode for typing commit info.

**Comment by varunwy** [comment] 2023-05-01 12:38
> I see this very often, when ever I do a git commit, and fill out the commit message in the editor. After closing the editor tab.
Get this every time on VSCode Version: 1.77.0 (Universal) with Git 2.40.1

**Comment by Andres97x** [comment] 2023-05-29 06:32
I'm getting the same error when comitting using VSCode as default editor, I have to say that the commit works but I don't know if something else is broken elsewhere due to that error

**Comment by erikiva** [comment] 2024-04-24 12:47
Also, having this issue when having more than one instance of the app opened.  I opened the build and was running the dev version at the same time.

**Comment by ashesh2512** [comment] 2024-05-31 20:44
Just wanted to comment to let you know, this error persists as of May 2024, when using VSCode as default editor in MacOS

**Comment by paralin** [comment] 2024-06-01 01:11
Ensure that only one instance of the app is running and if you need to run multiple, use a different userDataDir.

**Comment by jegelstaff** [comment] 2025-06-07 22:30
Wild ass guess... this issue only showed up for me in VSCode after I experienced this issue: https://github.com/microsoft/vscode/issues/52855

Is something about the shuffling of folders that VSCode goes through when this happens, breaking something in electron? Is there a setting somewhere that needs to be reverted after fixing the underlying VSCode issue, and there's an underscore in a path deep in the config still?
