### ISSUE TITLE
Hovering disabled item of tray's menu makes the submenu disappear

### ISSUE THREAD

**Issue by vedatyilmaz** [electron/electron#1788] opened 2015-05-27 15:21 UTC
i have a submenu item (enabled: false) in my tray menu. when i mouse over disabled menu item, menu disappear..

os: windows 7

**Comment by zcbenz** [comment] 2015-05-28 08:05
Can you provide an example?

**Comment by vedatyilmaz** [comment] 2015-05-28 08:46
sample code here..
https://gist.github.com/vedatyilmaz/f9c27b2562f739e0412e

submenu items changing some situations.. for example when service running, start button false.. you can only stop and restart.. if service stoppped, stop and restart button false, start button enabled..

so, if you mouse over disabled item in submenu, submenu disappear..

**Comment by zcbenz** [comment] 2015-05-29 10:40
You need to use a Boolean value instead of String for `enabled`, e.g. `enabled: false` instead of `enabled: 'false'`.

**Comment by vedatyilmaz** [comment] 2015-05-29 11:38
its already used as a bool value on my project.. 

i dont know how i wrote as a string for sample code.. :)
gist file updated.. submenu still goes away when i mouseover it..

**Comment by zcbenz** [comment] 2015-06-01 04:34
Can you share some screenshots of the problem?

**Comment by vedatyilmaz** [comment] 2015-06-01 05:57
animated gif here. You can see problem here.. When mouse over disabled item, menu closed..
http://imgur.com/HFIpNtN

**Comment by zcbenz** [comment] 2015-06-03 10:29
I can not reproduce with your example, and it doesn't match your screenshot. In your screenshot the "Stop" and "Restart" is disabled however in your example things are reversed. I think it is something else in your code that caused this.

**Comment by vedatyilmaz** [comment] 2015-06-03 10:42
i just show disabled item there.. it doesnt matter whichone.. if item disabled, submenu closed..

in my gist example submenu will close when you mouse over start button..

**Comment by vedatyilmaz** [comment] 2015-06-03 10:45
gist file updated..
code: https://gist.github.com/vedatyilmaz/f9c27b2562f739e0412e
result: http://imgur.com/HFIpNtN

**Comment by vedatyilmaz** [comment] 2015-09-10 13:35
Hello,

any plan about this stuation?

**Comment by petejkim** [comment] 2015-12-09 01:21
This is a real problem

**Comment by codebytere** [comment] 2017-09-27 11:58
Closing due to abandonment.

**Closed by codebytere** 2017-09-27 11:58 UTC
Labels: component/menu, component/tray, fixme/bug, platform/windows
