### ISSUE TITLE
[Bug]: The current Electron app doesn't include in the window sources

### ISSUE THREAD

**Issue by oalfroukh** [electron/electron#36412] opened 2022-11-20 13:06 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19041

### What arch are you using?

x64

### Last Known Working Electron version

17.4.11

### Expected Behavior

The current Electron app should be included in the sources when getting the windows sources using `desktopCapturer.getSources` as previous Windows versions (<= 17.4.11), and macOS versions.

### Actual Behavior

The current Electron app doesn't include in the sources when getting the windows sources using `desktopCapturer.getSources` as previous Windows versions (<= 17.4.11) and macOS versions.

### Testcase Gist URL

https://gist.github.com/oalfroukh/d0618e119aa1cb9112c9cde885850f1f

### Additional Information

For example, using the attached project, it has `Hello World!` window:
- Using Electron `v17.4.11`: 
```js
const sources = await desktopCapturer?.getSources({
      types: ["window"],
      thumbnailSize: {
        width: 150,
        height: 150,
      },
      fetchWindowIcons: true,
    });
```
The captured sources = `Hello World!` and `Electron Fiddle` while using an upper Electron version will be `Electron Fiddle` only.

**Comment by codebytere** [comment] 2022-11-21 18:08
Duplicate of https://github.com/electron/electron/issues/36037

**Closed by codebytere** 2022-11-21 18:08 UTC
Labels: bug :beetle:

**Comment by blcyzycc** [comment] 2024-01-08 07:56
I also encountered the same problem and had to revert back to version 17.17.4.1
