### ISSUE TITLE
Print issue on Electron from v7 - Print only works once (window.print())

### ISSUE THREAD

**Issue by ChenAlon** [electron/electron#21397] opened 2019-12-05 16:47 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  Not working since v7.00.  
  Tested on:
  * v8.0.0-beta.4
  * v7.0.0
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * v6.1.5

### Expected Behavior
That the ```window.print()``` will work, even after the first time.  
Like in versions prior to v7.0.0

### Actual Behavior
The ```window.print()``` function only works one time.  
After the first time, it's not working.
The print dialog appears but the actual printing is not.

### To Reproduce
Run ```window.print()``` twice.  
On the Electron Fiddle app example, click on the Print Page and print.
After that first time, click on the Print Page button again and try to print again.
[Link to the Gist](https://gist.github.com/ChenAlon/1d2253dc2c5ad1201370700cd200b0fa)

### Screenshots
[Link to video](https://drive.google.com/file/d/1QfXvhPVGuNv6Zvdn9JkbHGgXAklx2F-N/view?usp=sharing)

**Comment by codebytere** [comment] 2019-12-05 21:40
@ChenAlon Running that exact gist on `v8.0.0-beta.4` on macOS 10.14.5 works for me without incident as expected - are you sure that it's broken there?

**Comment by ChenAlon** [comment] 2019-12-08 07:26
@codebytere, yes. Did you see the video?
I just tried the same on a different machine, macOS 10.14.6 and I still see the same issue (```v8.0.0-beta-4```).

Here are some logs from the Console app logs:

This happen after I click the print button:
```
default	09:20:26.517943 +0200	Electron	failed to get application bundle
default	09:20:26.517986 +0200	Electron	Error in AHRegisterHelpBookWithURL: -50
default	09:20:26.546347 +0200	Electron	failed to get application bundle
default	09:20:26.546375 +0200	Electron	Error in AHRegisterHelpBookWithURL: -50
default	09:20:26.546978 +0200	Electron	failed to get application bundle
default	09:20:26.547006 +0200	Electron	Error in AHRegisterHelpBookWithURL: -50
default	09:20:26.551532 +0200	Electron	failed to get application bundle
default	09:20:26.551558 +0200	Electron	Error in AHRegisterHelpBookWithURL: -50
```

And this after I click Print on the Print dialog (Save to PDF):
```
error	09:20:44.808648 +0200	Electron	errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
default	09:20:44.808700 +0200	Electron	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(ficl,askM handler=0x7fff4f4e929b isSys=NO) err=0/noErr
default	09:20:44.902731 +0200	Electron	Adding presenter FB6315CE-2576-4C18-9CD3-6FD62B32F914 for URL: <private>
default	09:20:49.907229 +0200	Electron	Removing presenter FB6315CE-2576-4C18-9CD3-6FD62B32F914
default	09:20:51.715695 +0200	Electron	LSExceptions shared instance invalidated for timeout.
```

**Comment by codebytere** [comment] 2019-12-09 19:15
I'll do my best to check into this!

**Comment by daveajones** [comment] 2020-01-24 15:02
I think this should block a stable release until fixed.  Only being able to print once seems like a pretty severe issue.  I know it's a show-stopper for us.  We tried resolving by rolling back to v6.x, but then got hit with https://github.com/electron/electron/issues/19768 .  In our case (site wrapper) the workarounds don't help, so we're pretty much stuck.  IMO getting back to print stability in v8 would finally take this off the table.

**Comment by codebytere** [comment] 2020-01-24 21:56
@daveajones https://github.com/electron/electron/pull/21889 should fix this - i tested with this gist: https://gist.github.com/codebytere/efcda9c7b2c31c9252f0e3f9b60187b7 and have seen no issues thus far. I'm not 100% sure if this will be backportable into 7 owing to architectural changes in Chromium, but it will work as expected in 8. I do agree that it was a notable issue, so i appreciate your hanging with us as we work to compensate for Chromium's print work.

**Closed** 2020-01-27 18:54 UTC
Labels: 7-1-x, 8-x-y, bug :beetle:, platform/macOS

**Comment by barbalex** [comment] 2020-01-28 20:24
I can confirm this in v8.0.0-beta.7

**Comment by codebytere** [comment] 2020-01-28 20:25
@barbalex that it's working?

**Comment by barbalex** [comment] 2020-01-28 20:27
@codebytere sorry, that printing works only once. 

And yes, obviously your merge will only be in the next release so sorry for bugging.

And THANKS A LOT for solving the issue!

**Comment by codebytere** [comment] 2020-01-28 20:28
@barbalex of course! printing is an ongoing struggle so apologies for the occasional failures, but it's something i care about to large extent so i'm always happy to tackle printing bugs when they come up :D

**Comment by dipunj** [comment] 2020-09-11 22:01
Hi,

I am encountering the exact same problem in version 10.1.1 (latest version currently) on mac. Can anyone else please confirm if the issue has been reintroduced? 

Btw, I have tried to approaches to printing:

1. button onclick="window.print()"
2. using ipc, window.webContents.print()

PS: I am new to electron. Thank you!

**Comment by umeduardo** [comment] 2020-09-18 14:12
Downgrade to version 1.8. Works to me.

**Comment by codebytere** [comment] 2020-09-18 14:17
I just tested with  https://gist.github.com/0f0e776b138452d6815ef4efc16aa0d1 and had no issues running window.print multiple times on v10 with macOS.

**Comment by dipunj** [comment] 2020-09-18 14:24
@codebytere thank you for that gist. I will compare your gist with my code and update you here.

**Comment by codebytere** [comment] 2020-09-18 16:38
@dipunj https://github.com/electron/electron/pull/25530 will handle the issue! Should be fixed in next version of 10.

**Comment by exander77** [comment] 2021-09-13 18:36
I still have problems on version 13 and 14.
