### ISSUE TITLE
webview.webContents.addListener returns an empty object

### ISSUE THREAD

**Issue by jdknowstocode** [electron/electron#37295] opened 2023-02-16 05:04 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro version 22H2

### What arch are you using?

x64

### Expected Behavior

```javascript
const webview = webContents.fromId(webviewel.getWebContentsId())
webview.addListener('will-navigate', e => console.log(e))
```
This code must return an boject like this
```javascript
{
    isTrusted: false
    url: "https://mail.google.com/"
    bubbles: false
    cancelBubble: false
    cancelable: false
    composed: false
    currentTarget: null
    defaultPrevented: false
    eventPhase: 0
    returnValue: true
    srcElement: webview#webview.w-screen.h-[calc(100vh-40px)]
    target: webview#webview.w-screen.h-[calc(100vh-40px)]
    timeStamp: 1475.2000000001863
    type: "will-navigate"
}
```

### Actual Behavior

But returns an empty object with no data
```
{}
```

### Additional Information

I do not understand the issue here properly. Please get to me as soon as possible.

**Comment by codebytere** [comment] 2023-02-16 11:23
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by miniak** [comment] 2023-02-16 14:14
Which process are you running this in? `webContents.fromId()` is only available in the main process, while `webview. getWebContentsId()` can only be called in the renderer.

**Comment by miniak** [comment] 2023-02-16 14:52
if you are using the `remote` module, then you might need to report this to https://github.com/electron/remote instead

**Comment by jdknowstocode** [comment] 2023-02-18 12:41
yeah i was using `remote` module. i will report this to them. thank you

**Closed** 2023-02-19 00:29 UTC
Labels: platform/windows, bug :beetle:, 23-x-y
