### ISSUE TITLE
Electron 10.x crashes with SIGSEGV on exit if a worker was created

### ISSUE THREAD

**Issue by regular** [electron/electron#26103] opened 2020-10-22 09:30 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.4
* **Operating System:**
  * both, macOS 10.14.6 and ArchLinux kernel 5.8.5-arch1-1 (did not test on Windows)

* **Last Known Working Electron version:**
  * 9.3.2

### Expected Behavior

Electron quits normally

### Actual Behavior

Electron crashes with SIGSEGV

### To Reproduce

Here's a minimal code example that crashes electron

``` js
const {Worker} = require('worker_threads')
const {app} = require('electron')

const worker_code = `
  process.exit(0)
`

app.on('ready', ()=>{
  const worker = new Worker(worker_code, {
    eval: true
  })

  worker.on('exit', code=>{
    console.log('exited with code', code)
  })

  setTimeout( ()=>{
    app.quit()
  }, 1000)
})

```

**Comment by ckerr** [comment] 2020-10-22 16:03
backtrace from v10.1.3 using @regular's repro:

```
exited with code 0
Received signal 11 SEGV_MAPERR 000000000018
#0 0x55d40730d159 base::debug::CollectStackTrace()
#1 0x55d407260ab3 base::debug::StackTrace::StackTrace()
#2 0x55d40730cca5 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f63040843c0 (/lib/x86_64-linux-gnu/libpthread-2.31.so+0x153bf)
#4 0x55d40b83feb3 node::NodePlatform::AddIsolateFinishedCallback()
#5 0x55d40b78707f node::Environment::AddArrayBufferAllocatorToKeepAliveUntilIsolateDispose()
#6 0x55d40b87edd8 node::worker::(anonymous namespace)::SABLifetimePartner::CleanupHook()
#7 0x55d40b783112 node::Environment::RunCleanup()
#8 0x55d40b7550ae node::FreeEnvironment()
#9 0x55d403a7b594 electron::ElectronBrowserMainParts::PostMainMessageLoopRun()
#10 0x55d40647772c content::BrowserMainLoop::ShutdownThreadsAndCleanUp()
#11 0x55d40647984f content::BrowserMainRunnerImpl::Shutdown()
#12 0x55d406473e32 content::BrowserMain()
#13 0x55d40631237a content::ContentMainRunnerImpl::RunServiceManager()
#14 0x55d406311d53 content::ContentMainRunnerImpl::Run()
#15 0x55d408bdfbd5 service_manager::Main()
#16 0x55d404a2e431 content::ContentMain()
#17 0x55d4039a758f main
#18 0x7f63024be0b3 __libc_start_main
#19 0x55d4039a72aa _start
  r8: 0000000000000002  r9: 0000000000000017 r10: 00002ff9ece0c990 r11: 0000000000000004
 r12: 00002ff9ec664238 r13: 0000049f00000000 r14: 00002ff9ec664230 r15: 000055d40b787b70
  di: 00002ff9ec664238  si: 0000000000000001  bp: 00007ffc77befb30  bx: 0000000000000001
  dx: 0000000000000001  ax: 0000000000000000  cx: a74916a591e5b603  sp: 00007ffc77befb00
  ip: 000055d40b83feb3 efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000018
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by nornagon** [comment] 2020-10-22 17:43
Looks like a duplicate of #25691.

**Closed by nornagon** 2020-10-22 17:43 UTC
Labels: 10-x-y, bug/crash :boom:, bug/regression :leftwards_arrow_with_hook:, platform/linux, platform/macOS, status/confirmed

**Comment by regular** [comment] 2020-10-22 18:59
@nornagon actually, this might not be a duplicate of #25691.

#25691 and #23315 both describe a crash when a worker_thread is running while electron shuts down. My problem is that even when I wait for all threads to have terminated, Electron still crashes. This is a regression from 9.x.x that is still present in 11.0.0.beta13, so it was not fixed by upgrading Node to v14.

**Comment by nornagon** [comment] 2020-10-22 19:04
The stack trace is nearly identical. Perhaps it wasn't actually fixed with Node 14?

**Comment by nornagon** [comment] 2020-10-22 19:05
Actually, 11.0.0-beta.13 is still Node 12.

**Comment by nornagon** [comment] 2020-10-22 19:07
The example you gave does not crash on v12.0.0-nightly.20201015.

**Comment by regular** [comment] 2020-10-22 19:24
@nornagon ah, ok, thanks for checking!

**Comment by javagrendel** [comment] 2020-12-09 21:14
This is occurring again in electron v11.0.4 and node v14.15.1. The minimal code given in this ticket produces this:

~/sandbox/electron-quick-start/node_modules/electron/dist/electron exited with signal SIGSEGV
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2020-12-09T21_07_47_847Z-debug.log
[2020-12-09T21_11_16_067Z-debug.log](https://github.com/electron/electron/files/5668692/2020-12-09T21_11_16_067Z-debug.log)

**Comment by subatta** [comment] 2021-02-05 21:51
Having same issue with just: /usr/app/node_modules/electron/dist/electron exited with signal SIGSEGV. Nothing else on console.
Ubuntu 18.04
Node 15

**Comment by bierzorutas** [comment] 2021-06-17 21:47
Same problem here in MacOS and node 14.16.0, 
why so many closed issues without solution ?

**Comment by nornagon** [comment] 2021-06-17 23:08
If you're still experiencing a similar bug, please open a new issue and fill out the template. Especially, it is very helpful if you can include a minimal repro case, for instance using [Electron Fiddle](/electron/fiddle). This helps us quickly evaluate the bug and determine next steps.

**Comment by BassoliCodes** [comment] 2023-01-05 18:19
I also have the same error at the company where I work, we are currently running on version:

Node: v14.21.2
Electron: ^11.0.1

**Comment by DaveFlashNL** [comment] 2023-06-01 11:48
on my arch linux same issues, any fix forthcoming?
