### ISSUE TITLE
`GLIBC_2.29' not found` on linux

### ISSUE THREAD

**Issue by jlongster** [electron/electron#18181] opened 2019-05-06 17:46 UTC
### Issue Details

* **Electron Version:** 5.0.0
* **Operating System:**  LTS version of Ubuntu (18.04) (and other various versions)
* **Last Known Working Electron version:**: none

### Expected Behavior
I just released a Linux version of my app and several users have reported that on launch it fails with the error `GLIBC_2.29' not found`.

### Actual Behavior
App should launch

### To Reproduce
You can probably package up Electron 5.0.0 and try to run an AppImage on linux and you'll see it. I gave out a linux build at 4.* before and I think it also had the same issue?

I feel like this might be a simple issue: the latest electron versions require glibc 2.29 and many linux distros aren't up-to-date with that yet. If so, I would have expected to see many other issues reported, because I've had many users complain about this (see https://www.reddit.com/r/actualbudget/comments/bghvfg/any_plans_for_a_linux_client_in_the_future/). Am I doing something wrong?

**Comment by codebytere** [comment] 2019-05-06 18:24
Closing as duplicate of https://github.com/electron/electron/issues/16205

**Closed by codebytere** 2019-05-06 18:24 UTC

**Comment by jlongster** [comment] 2019-05-06 18:45
Can somebody explain the issue a little further? The linked issue only has glibc in common - and it's talking about a different glibc version. Are each chrome versions pinned to a specific glibc version, so each electron is as well? How come my users can run the latest Chrome but not my app built on Electron 5.0.0?

**Comment by wodin** [comment] 2019-05-06 22:54
FYI it works for me on Ubuntu MATE 18.04 (x86_64) (which shares most packages with Ubuntu 18.04) using glibc 2.29-0ubuntu2.

**Comment by inukshuk** [comment] 2019-05-07 13:24
Electron itself should work fine on Ubuntu 18. Just tested this on Ubuntu 16 GLIBC 2.23 which we're using for Linux builds.

![Screenshot from 2019-05-07 15-14-49](https://user-images.githubusercontent.com/325102/57302653-fc9ff180-70db-11e9-8289-184c9efe3463.png)

I would guess the issue here is really a native module like SQLite. That's the reason we're using and old Ubuntu image to create the builds, because if you compile a native module it will be linked against your local libc version. It should be possible to keep around an older libc and link to it specifically, but using a sufficiently old distro should work also. In my experience, when we shipped builds I had compiled on Arch Linux we would get frequent reports like the one above ; ever since using Ubuntu 16 all our Linux users seem to be covered.

**Comment by jlongster** [comment] 2019-05-07 15:44
Thank you @wodin and @inukshuk. You are absolutely correct. Now that I look deeper into the error I see that it is coming from the sqlite3 module I'm using. I will setup an older image so that it links in an older glibc version. Sorry for thinking it was electron.

**Comment by codebytere** [comment] 2019-05-07 15:49
@jlongster @inukshuk i'm glad y'all figured this out! if something else arises please @ me and we can re-open and keep looking :)

**Comment by nhandl3** [comment] 2020-04-14 23:15
@jlongster I have the same problem with `grpc` native module. Because I use `electron-rebuild`, I think the tool affects the version of GLIBC. My Ubuntu has GLIBC 2.30.

![grpc-vscode](https://user-images.githubusercontent.com/1247539/79282781-41352f00-7ee0-11ea-9a17-b053178b9f94.jpg)

Could you solve your issue with sqlite3?

**Comment by LuigiCerone** [comment] 2020-11-10 09:15
@nhandl3 Were you able to fix it?

**Comment by quolpr** [comment] 2023-02-02 14:55
Hmm, we have report that our user on Ubuntu 18.04 has the same issue with better-sqlite 8.0.0 + electron
```
Failed to process command Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_RemNotvHCOdw/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2037)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/tmp/.mount_RemNotvHCOdw/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/tmp/.mount_RemNotvHCOdw/resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64) {
  code: 'ERR_DLOPEN_FAILED'
}
```
