### ISSUE TITLE
[Feature Request]: Allow access to Devtools Extensions when app is loaded over custom protocol (eg app://)

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#34386] opened 2022-05-30 22:14 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

React Devtool's Profiler is meant to be used with production builds, but if your packaged app is set to run over `app://` instead of `file://` then devtools extensions cannot load.

This makes dogfooding your own work much more difficult and time consuming, and adds up to potentially dozens of hours of wasted time over the course of a year.

### Proposed Solution

Implement a flag similar to that introduced in #25198

I guess this is probably not possible due to Chromium lacking a feature for this - but I hope very much that the developer experience can be improved somehow if this is not viable.

### Alternatives Considered

The only alternative would be to rework all our build scripts and our internal environmental config management to accommodate a new mode of running the app in the development environment but with it forced to production mode. This would require some re-thinking and re-implementation on our part.
 
But much worse than having to rewrite some code is that issues cannot be investigated as they arise during real world usage with this alternative. Instead the user's data would need to be replicated into the dev environment and then run with a special command to force it to run in production mode. This would take the time for investigating a simple issue from a few seconds to a minimum of probably ten minutes - and would need to be repeated for every individual issue that arises during dogfooding.

----

I suppose one other alternative would be loading debug_prod versions of our app over the `file://` protocol, but that means a departure from what we're shipping, which undercuts the benefits of dogfooding, as well as more code complexity to support this and potential security ramifications for users using the debug_prod versions.

**Comment by reZach** [comment] 2022-06-29 04:03
This feature in Electron is important - the genesis came from [this issue](https://github.com/reZach/secure-electron-template/issues/2) where it [was outlined](https://github.com/moloch--/reasonably-secure-electron#signal-desktop) that running an Electron app in a non-file:// origin was preferred to better secure an application. Allowing Devtools Extensions to run over a custom protocol would help to continue to build upon the landscape of secure Electron apps.

**Comment by Slapbox** [comment] 2022-10-20 20:25
@MarshallOfSound @codebytere are there any plans to help developers in this situation? Is it within the power of the Electron team, or is the limiting factor upstream?

We've been without access to React profiling tools for 6 months now while dogfooding and I see no hope on the horizon that we'll ever get them back. This is a significant devEx issue with major repercussions for the performance of the app, and therefore for the end users.

**Comment by MarshallOfSound** [comment] 2022-11-13 12:12
Duplicate of https://github.com/electron/electron/issues/26812

**Closed by MarshallOfSound** 2022-11-13 12:12 UTC
Labels: enhancement :sparkles:, component/devtools, component/protocol
