### ISSUE TITLE
<datalist> auto-completion is broken

### ISSUE THREAD

**Issue by AdorianDoran** [electron/electron#11081] opened 2017-11-10 14:06 UTC
* Electron version: 1.7.9
* Operating system: Windows

### Expected behavior

The datalist element should let the user to select a predefined value from a drop-down list for input elements.

### Actual behavior

After selecting a value from drop-down list, that value is displayed in the input field, but the "value" property of that input element is an empty string instead of the selected value.

### How to reproduce

Using the below code snippet. The input element's value will be displayed as the window title.

```HTML
<input id="test-field" type="text" list="test-list" />

<datalist id="test-list">
  <option value = "Car" />
  <option value = "Bike" />
  <option value = "Truck" />
</datalist>

<script>
  document.getElementById("test-field").addEventListener("input", (e) => {
    document.title = "Value is: " + e.target.value;
  });
</script>
```

**Comment by brenca** [comment] 2017-11-10 14:56
Duplicate of #9860

**Comment by sofianguy** [comment] 2017-11-15 05:02
@AdorianDoran 
Thanks for taking the time to contribute!

We noticed that this is a duplicate of [#9860](https://github.com/electron/electron/issues/9860). You may want to subscribe there for updates.

Because we treat our issues list as the project team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the [CONTRIBUTING guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).

**Closed by sofianguy** 2017-11-15 05:02 UTC
Labels: platform/windows, version/1.7.x
