### ISSUE TITLE
[Bug]: Tray.getBounds() returns incorrect x y values on macOS

### ISSUE THREAD

**Issue by RockRockWhite** [electron/electron#36031] opened 2022-10-14 12:53 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

 v13.6.9

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.6

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Returns the correct tray icon screen position data.

### Actual Behavior

As the issue #33515, he got the the incorrect position data of tray bounds '{x:0, y:900}'. And I got the totally same wrong bounds in which x was 0 and y was 900.

### Testcase Gist URL

Not matter the icon were, the return bounds was always '{x:0, y:900}'.

### Additional Information

I've dug up to the code of this method. 
I found that the implement of this method in macOS is in "tray_icon_cocoa.mm".

```cpp
//  "tray_icon_cocoa.mm"
gfx::Rect TrayIconCocoa::GetBounds() {
  return gfx::ScreenRectFromNSRect([status_item_view_ window].frame);
}
```
the gfx::ScreenRectFromNSRect() methods, I thought that is from chromium.
the code above is what I got from [chromium.org](https://source.chromium.org/chromium/chromium/src/+/main:ui/gfx/mac/coordinate_conversion.mm;l=28)

```cpp
// code in "ui/gfx/mac/coordinate_conversion.h"
Rect ScreenRectFromNSRect(const NSRect& rect) {
  return Rect(rect.origin.x,
              PrimaryDisplayHeight() - rect.origin.y - rect.size.height,
              rect.size.width, rect.size.height);
}
```

I'm using MacBook Air Late 2020, whose display resolution is 1400 x 900(high dpi).
I purposed there might be something wrong with the "status_item_view_" variable in "tray_icon_cocoa.mm", making [status_item_view_ window].frame.origin.x and [status_item_view_ window].frame.origin.y be 0. 
Then in "coordinate_conversion.mm", because rect.origin.x is 0, so Rect.x is 0. PrimaryDisplayHeight() get my screen's Height, 900, minus rect.origin.y(which was also 0), got 900 in Rect.y .

**Comment by RockRockWhite** [comment] 2022-10-14 12:57
It's a pity that I am not so familiar with Objective-C. So I cannot be able to read up the code to find out what exactly the problem is. So I created this issue and gave the information I've known.

**Comment by clavin** [comment] 2022-10-14 22:31
Thanks for writing in! Your additional information and investigation is really appreciated. 🙇

This looks like a duplicate of #35984, so I'm going to close this issue so we don't have duplicates in our issue tracker. I'll add a note in that issue that there are some helpful details here though. Thanks again!

**Closed by clavin** 2022-10-14 22:31 UTC
Labels: bug :beetle:
