### ISSUE TITLE
Electron 1.2.4 does not start in Linux

### ISSUE THREAD

**Issue by ivannugo** [electron/electron#6178] opened 2016-06-22 11:02 UTC
* Electron version: 1.2.4
* Operating system: Linux xxx 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:27:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I was trying to set 1.2.2 - 1.2.3 versions and works fine. When updating to 1.2.4 app.on('ready'...) never works. No errors output on console.
Trying "Quick start" from electron. https://github.com/electron/electron-quick-start

**Comment by kubijo** [comment] 2016-06-22 15:12
+1, I got only segfaults from electron executable

node --version && npm --version
>> v6.2.2
>> 3.9.6

**Comment by pixcai** [comment] 2016-06-22 15:30
I have the same problem as you. Unable to start the program and no errors output. My system is Ubuntu 16.06.

**Comment by LinusU** [comment] 2016-06-22 15:42
Seems like our kernel is killing the process because of a [general protection fault](https://en.wikipedia.org/wiki/General_protection_fault).

> kernel:  [ 4854.800894] traps: electron[3267] general protection ip:ba3650 sp:7ffea43867f8 error:0 in electron[400000+3c55000]

**Comment by albinekb** [comment] 2016-06-22 15:50
Confirmed. Unable to start the program, kernel problem:
>kernel: [ 4854.800894] traps: electron[3267] general protection ip:ba3650 sp:7ffea43867f8 error:0 in electron[400000+3c55000]
My system is Ubuntu 16.04.

**Comment by qrohlf** [comment] 2016-06-22 20:02
I believe that https://github.com/electron/electron/issues/6186 may be a dupe of this. In which case, here's a minimal repro example: https://gist.github.com/qrohlf/02b4152d788a103a9596b2444b0d5500

**Comment by antitoxic** [comment] 2016-06-22 20:12
Same problem with virtualbox and lubuntu. 1.2.2 works, latest version doesn't. Tested with quick starter example. Had the following logging and trace:

```
[18236:0622/231148:ERROR:browser_main_loop.cc(219)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Received signal 11 <unknown> 000000000000
#0 0x00000140f1eb <unknown>
#1 0x7f8adb36ed10 <unknown>
#2 0x000000ba3650 <unknown>
#3 0x000000bd5b80 hb_shape_plan_create_cached
#4 0x000000bd5524 hb_shape
#5 0x7f8ad4de3457 <unknown>
#6 0x7f8ad9b50b86 pango_shape_full
#7 0x7f8ad9b42e13 <unknown>
#8 0x7f8ad9b44680 <unknown>
#9 0x7f8ad9b46b86 <unknown>
#10 0x7f8ad9b47b40 pango_layout_get_unknown_glyphs_count
#11 0x7f8adadce440 <unknown>
#12 0x7f8adadd15f5 <unknown>
#13 0x7f8ad9405f99 g_type_create_instance
#14 0x7f8ad93e9867 <unknown>
#15 0x7f8ad93eb25d g_object_newv
#16 0x7f8ad93eb9f4 g_object_new
#17 0x000001268672 <unknown>
#18 0x000001267c5b <unknown>
#19 0x000001262209 <unknown>
#20 0x00000126215b <unknown>
#21 0x000000678896 brightray::BrowserMainParts::ToolkitInitialized()
#22 0x000001d5cfae <unknown>
#23 0x000001b51f32 <unknown>
#24 0x000001b51ad6 <unknown>
#25 0x000000ba1a77 <unknown>
#26 0x000000ba0490 <unknown>
#27 0x00000055d650 main
#28 0x7f8ad500aa40 __libc_start_main
#29 0x00000055d509 <unknown>
  r8: 0000000000000000  r9: 000000000000000f r10: 0000000000001a8a r11: 0000000000bd5500
 r12: 000008fe22026900 r13: 00007ffc6e513320 r14: e83f8b48fb894853 r15: 00007f8ad2b7e620
  di: e83f8b48fb8948b3  si: 00007ffc6e513320  bp: 00007f8ad2b7e620  bx: 0000000000000000
  dx: 00007ffc6e513430  ax: 00007ffc6e51343c  cx: 0000000000000000  sp: 00007ffc6e5132e8
  ip: 0000000000ba3650 efl: 0000000000010202 cgf: 0000000000000033 erf: 0000000000000000
 trp: 000000000000000d msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
```

**Comment by ColdNightHour** [comment] 2016-06-22 20:29
Is there a fix for this?

**Comment by kevinsawicki** [comment] 2016-06-22 20:30
> Is there a fix for this?

There is not currently a fix, it is being investigated, you might want to use a previous version, such as `1.2.3` until this is resolved.

**Comment by batmantis** [comment] 2016-06-22 20:31
I'm having this issue also on Ubuntu 14.04 with 1.2.4.  I tried installing 1.2.3 and it gives me the same problem.  Any ideas?

node --version && npm --version
v6.2.1
3.9.3

**Comment by duncanwerner** [comment] 2016-06-22 20:49
```
>ELECTRON_ENABLE_LOGGING=true node_modules/.bin/electron
[9625:0622/134755:ERROR:browser_main_loop.cc(219)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
```

**Comment by boatrite** [comment] 2016-06-22 21:31
Same issue.

Ubuntu 16.04
Node v4.4.3
NPM 2.15.1

1.2.4 does not work. 1.2.3 _does_.

**Comment by envygeeks** [comment] 2016-06-22 22:47
@duncanwerner that SUID sandbox is just chrome complaining.

**Comment by janstuemmel** [comment] 2016-06-22 23:50
same here. on ubuntu 14.04

```
jan@ubu:~$ npm -v && node -v 
2.14.12
v4.3.2
```

1.2.3 works, 1.2.4 not

thanks

**Closed** 2016-06-23 03:04 UTC
Labels: bug, crash, linux
