### ISSUE TITLE
Frameless window is unclickable on Windows 10 1803

### ISSUE THREAD

**Issue by i2gor87** [electron/electron#12972] opened 2018-05-17 06:18 UTC
* Electron version: 2.0.0
* Operating system: Windows 10 1803 Update

### Expected behavior

User clicks on item in tray menu, new BrowserWindow pops out. User fills the form and saves it by clicking on button. 

### Actual behavior

The user can't interact with interface of frameless BrowserWindow.

### How to reproduce

settingsWindow =  new BrowserWindow({
        width: 600,
        height: 270,
        show: true,
        frame: false,
        resizable: false
    })

If I delete **frame: false**, it works, but with ugly frames.

**Comment by bpasero** [comment] 2018-07-12 14:38
@i2gor87 I cannot reproduce with your example on Windows 10, I can click into the window. So there must be more to it to reproduce.

**Comment by PeterChen1997** [comment] 2018-11-09 04:19
I came into the same problem, my app's navbar cannot click until i set the frame: true

but it's fine in macOS

my Repo:https://github.com/PeterChen1997/electron-learning-note/tree/master/electron-pomodoro

**Comment by PeterChen1997** [comment] 2018-11-09 05:48
i think it's maybe a problem in the app's height calculating..

i have to let the img under the header's height, that works
![image](https://user-images.githubusercontent.com/21072589/48243566-faeebd00-e41b-11e8-9813-d78674e79bed.png)
![image](https://user-images.githubusercontent.com/21072589/48243570-0215cb00-e41c-11e8-9058-a2f3096378e1.png)

**Comment by sofianguy** [comment] 2019-08-09 00:47
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 21:04
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 21:04 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
