### ISSUE TITLE
Having config menu popping up above bottom of windows instead of having to scroll. 

### ISSUE THREAD

**Issue by JeffHeon** [electron/electron#14261] opened 2018-08-22 14:15 UTC
**Is your feature request related to a problem? Please describe.**
I use VS Code maximized or full screen, and clicking on the config gear always bring a truncated menu. I'd rather have it in full and higher because I have to scroll every time.

I filed this previously on VS Code and they correctly redirected me here: https://github.com/Microsoft/vscode/issues/56921

**Describe the solution you'd like**
Having config menu popping up above bottom and expanded in full instead of having to scroll. 

**Describe alternatives you've considered**
I can scroll instead.

**Additional context**
I'm using MacOS 10.13.16

Showing might help, please see my two screen shots.

Thank you for your time.

<img width="285" alt="44414137-088e5800-a53b-11e8-8228-76cda8f27744" src="https://user-images.githubusercontent.com/1154213/44468739-e99fcc80-a5f3-11e8-9259-809c696bee0a.png">
<img width="210" alt="44414136-07f5c180-a53b-11e8-9fc0-39286d6a14d3" src="https://user-images.githubusercontent.com/1154213/44468740-e99fcc80-a5f3-11e8-9278-4c1419fc3b88.png">

**Comment by bpasero** [comment] 2019-03-14 07:24
@MarshallOfSound @deepak1556 this does not look like an enhancement to me, rather a bug. Imho native menus should never scroll.

**Comment by bpasero** [comment] 2019-12-17 15:06
We suffer from this in VSCode: https://github.com/microsoft/vscode/issues/40262

**Comment by bpasero** [comment] 2019-12-17 15:06
(and it still reproduces in Electron 7)

**Comment by electron-triage** [comment] 2021-03-08 21:05
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by bpasero** [comment] 2021-03-12 15:53
This reproduces in Electron 11 in latest VSCode:

![image](https://user-images.githubusercontent.com/900690/110964418-74cc4380-8353-11eb-9e85-5b39e0a2ff35.png)

**Comment by nornagon** [comment] 2021-03-15 20:59
Duplicate of #13279

**Comment by zcbenz** [comment] 2022-08-02 09:01
I'm reopening this issue since it is actually a different one. https://github.com/electron/electron/issues/13279 is about the menu of select tag, while this one is about context menu.

**Comment by bpasero** [comment] 2022-08-02 13:03
@zcbenz repro in https://gist.github.com/d755ee5021a5488027b6e43dab67bb46

When you run and click the button bottom left, I see this menu:

![image](https://user-images.githubusercontent.com/900690/182381302-c0e84790-bcb7-4a88-8ef3-b928f39d4735.png)

**Comment by zcbenz** [comment] 2022-08-03 00:51
Thanks or the repo, it seems that this is related to whether dock is displaying. I have autohide dock and the problem does not occur, but changing dock to always show can make the problem happen.

**Comment by bpasero** [comment] 2022-08-03 04:25
Awesome 👏

**Closed** 2022-08-03 08:52 UTC
Labels: platform/macOS, bug :beetle:, 4-2-x, 5-0-x, 6-0-x, 6-1-x
