### ISSUE TITLE
[Bug]: Unable to disable devTools with overrideBrowserWindowOptions

### ISSUE THREAD

**Issue by joshuakoh1** [electron/electron#33694] opened 2022-04-10 13:45 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 20H2

### What arch are you using?

x64

### Expected Behavior

I copied the webPreferences from mainWindow into my new window handler. In the new window I am able to use Ctrl + Shift + I to open Dev Tools even though it is explicitly disabled with devTools: false. This behaviour is not seen in the main window.
```
    mainWindow.webContents.setWindowOpenHandler(({ url }) => {
      if (url === 'about:blank') {
        return {
          action: 'allow',
          overrideBrowserWindowOptions: {
            webPreferences: {
              autoHideMenuBar: true,
              contextIsolation: false,
              enableRemoteModule: true,
              webviewTag: true,
              titleBarStyle: 'hidden',
              webSecurity: false,
              devTools: false,
            },
            icon: __dirname + '/logo.png',
          }
        }
      }
      return { action: 'deny' }
    })
```

### Actual Behavior

Dev Tools should not open

**Comment by codebytere** [comment] 2022-04-13 13:45
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Closed** 2022-04-23 07:31 UTC
Labels: bug :beetle:, component/BrowserWindow, blocked/need-repro, 17-x-y

**Comment by xDroni** [comment] 2023-02-19 14:17
I ran into this problem too, but found some workarounds.

### Option 1. 
If you don't need the default menu in the new window, add a listener on the `did-create-window` event and remove it. This will disable the Ctrl + Shift + I shortcut (DevTools), but note that it will also disable the other shortcuts (like Ctrl + R for reload, etc).
```javascript
mainWindow.webContents.on('did-create-window', (window) => {
    window.removeMenu();
});
```

### Option 2.
If you want to keep the current menu behavior and just disable the DevTools menu item, modify the properties of the Menu instance:
```javascript
const menu = Menu.getApplicationMenu();
const viewMenuIndex = menu.items.findIndex((menuItem) => menuItem.role === 'viewmenu');
const viewMenuItems = menu.items[viewMenuIndex].submenu.items;
for (const viewMenuItem of viewMenuItems) {
  if (viewMenuItem.role === 'toggledevtools') {
    viewMenuItem.enabled = false;
    viewMenuItem.visible = false;
    break;
  }
}
```
Note that this will change the menu in all windows.

### Option 3.
Create an additional hidden window and redirect the DevTools to it (using the `did-create-window' listener).
```javascript
const devToolsHiddenWindow = new BrowserWindow({
    show: false
});
devToolsHiddenWindow.loadURL('about:blank');

mainWindow.webContents.on('did-create-window', (window) => {
    window.webContents.setDevToolsWebContents(devToolsHiddenWindow.webContents);
});
```
