### ISSUE TITLE
BrowserWindow alwaysOnTop don't work in linux

### ISSUE THREAD

**Issue by eboukamza** [electron/electron#12445] opened 2018-03-27 13:04 UTC
* Electron version: 1.8.4
* Operating system: Linux mint 18 (based on ubuntu 16.04)

### Expected behavior
creating a new Browser window with the flag alwaysOnTop at true in linux

    new BrowserWindow({alwaysOnTop: true})

The electron app should show always on top of other window

### Actual behavior

The window can be hidden by another window.

### How to reproduce

- download the electron quick start https://github.com/electron/electron-quick-start
- add the property allwaysOnTop set at true.
- launch the electron app
- try to set an other windows on top the electron app.

NOTE: this fonctionality works fine in other platforms like Windows.

**Comment by wuzzard** [comment] 2018-03-28 15:02
I'm having the same issue with 1.8.4 on Linux Mint (18.1 Cinnamon 3.2.7).  A browser window opened by a parent can go under its parent:

`let win = new BrowserWindow({ alwaysOnTop:true, width:400, height:200 })`

**Comment by ckerr** [comment] 2018-04-03 22:47
This is still present in 2.0.x and master

**Comment by YoussF** [comment] 2018-04-27 23:03
Same issue here under Archlinux (gnome)

**Comment by kotrodenx** [comment] 2018-04-28 04:49
i just had the same issue as @YoussF and i just tried to set manually `mainWindow.setAlwaysOnTop(true)`. It works, don't know why it doesn't in the options

**Comment by LeoFlandin** [comment] 2018-05-17 12:35
It's working for me on Ubuntu 16.04
But it does not on Ubuntu 18.04
Both electron app were installed with the same deb packed with electron-builder.

**Comment by geekysrm** [comment] 2018-07-17 23:11
Not working for me on Ubuntu 16.04.3

**Comment by KyleMoser** [comment] 2018-08-13 21:02
Seconded; the `alwaysOnTop `option does not work when provided as a constructor option to the `BrowserWindow`. Similarly, the `fullscreen` option does not work properly. I have found the following workaround: you can call `window.setFullScreen` and `window.setAlwaysOnTop` to cause the settings to apply properly. Furthermore, beware that the `window.setFullScreen` will not behave properly unless `resizable` is set to true, so I recommend calling `window.setResizable(true)` beforehand.

**Comment by nirajkaushal** [comment] 2018-08-18 11:43
**Not working on Ubuntu 18.04**
When I pass `alwaysOnTop` on options, its not working but when I use `win.setAlwaysOnTop(true)`, it's working fine. Thanks @kotrodenx  for providing alternative solution :smile:

**Comment by Javierkaiser** [comment] 2018-09-12 14:58
Also not working in electron 3 beta 4
    Electron version: 3.0.0-beta.4
    Operating system: Linux mint 18 (based on ubuntu 16.04)

**Comment by avant5** [comment] 2018-09-17 22:07
Also PeppermintOS (Ubuntu 16.04). Electron 2.0.9

**Comment by CapOM** [comment] 2019-06-21 22:38
Can someone re-test with latest electron and https://github.com/electron/electron-quick-start . It is working for me so maybe it depends on other flags.

**Comment by sofianguy** [comment] 2019-08-09 03:19
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:07
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 19:07 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/linux, version/1.8.x

**Comment by chap-wong** [comment] 2019-08-28 08:18
I am having the same issue, but none of above work for me, I am using Ubuntu 16.04.
I solve it by setting {focusable: false}.
Just leave my solution here for anyone stumble on this problem.

**Comment by belvederef** [comment] 2021-01-21 16:48
Still experiencing this. None of the solutions above worked for me.

**Comment by abacaj** [comment] 2021-03-08 04:27
Started working when I changed the level:

```
mainWindow.setAlwaysOnTop(true, 'screen-saver');
```

**Comment by kroko** [comment] 2021-03-16 16:30
On Ubuntu 20.04.2 LTS combination of following props works for me

```javascript
export const BROWSER_WINDOW_COMMON_OPTIONS_MAIN = {
  width: 1300,
  height: 900,
  x: 0,
  y: 0,
  useContentSize: false,
  center: true,
  minWidth: 400,
  minHeight: 400,
  maxWidth: 1300,
  maxHeight: 900,
  resizable: (__TIER_DEVELOPMENT__ || __TIER_TESTING__),
  movable: true,
  minimizable: false, // FIXME:
  maximizable: false, // FIXME:
  closable: true,
  focusable: true,
  alwaysOnTop: true,
  fullscreen: false,
  fullscreenable: false,
  simpleFullscreen: false,
  skipTaskbar: true, // REVIEW:
  kiosk: false,
  title: 'Dummy Title', // takes precedence
  // icon: // FIXME:
  show: false, // REVIEW: set false as ready-to-show event is used
  paintWhenInitiallyHidden: true, // REVIEW: set true, as show is false
  frame: true,
  parent: null,
  modal: false,
  acceptFirstMouse: false,
  disableAutoHideCursor: false,
  autoHideMenuBar: false,
  enableLargerThanScreen: false,
  backgroundColor: '#00ffff', // TODO:
  hasShadow: true,
  opacity: 1.0,
  darkTheme: false, // possible forcing, but only works on GTK+3
  transparent: false,
  // type: // TODO:
  // visualEffectState: // TODO:
  titleBarStyle: 'default', // FIXME:
  // trafficLightPosition: // TODO:
  fullscreenWindowTitle: false,
  thickFrame: true,
  // vibrancy: // TODO:
  zoomToPageWidth: false,
  // tabbingIdentifier: // TODO:
  webPreferences: BROWSER_WINDOW_COMMON_OPTIONS_WEBPREFERENCES
};

    winObjRef.once('ready-to-show', () => {
      winObjRef.show();
    });

    winObjRef.once('show', () => {
      winObjRef.focus();
      // PLATFORMALIGN: signal force always on top after show
      winObjRef.setAlwaysOnTop(true);
    });

```

actually it woks if `focus()` and `setAlwaysOnTop()` are called in `'ready-to-show'`, this just seems cleaner.
