### ISSUE TITLE
[2.0] MenuItem initialized as `visible: false` can't be found

### ISSUE THREAD

**Issue by magne4000** [electron/electron#12816] opened 2018-05-03 13:33 UTC
* Electron version: 2.0.0
* Operating system: MacOS 10.13.4

* Last known working Electron version: 1.8.4

### Expected behavior
When a submenu item is initialized with `visible: false`, it should be retrievable with `getMenuItemById` or by iterating through `menu.items`.

### Actual behavior
Those items can't be found

### How to reproduce
```javascript
{
      label: 'View',
      submenu: [
        {
          id: 'show-teammates-bar',
          label: 'Show Teammates Sidebar',
          type: 'checkbox',
          visible: false,
          checked: true,
          click() {
            ...
          },
        },
        {
          type: 'separator',
        },
       {
          label: 'Show All',
          selector: 'unhideAllApplications:',
        }
      ],
    };
```
In this example, `show-teammates-bar` can't be retrieved, but if initialized with `visible: true`, and set to `false` once build, it works as expected.

**Comment by codebytere** [comment] 2018-05-04 06:37
Closing as duplicate ofhttps://github.com/electron/electron/issues/12025 , which is in the process of being fixed by https://github.com/electron/electron/pull/12825!

**Closed by codebytere** 2018-05-04 06:37 UTC
