### ISSUE TITLE
Using WebView in `innerText` will get to the CSS code and JavaScript code

### ISSUE THREAD

**Issue by baihuibo** [electron/electron#6544] opened 2016-07-20 09:40 UTC
- Electron version: 1.2.0
- Operating system: mac os 10.11.5

file `index.html`

``` html
<html>
    <head>...</head>
    <body>
     <style>.test { display : block}</style>
     <a class="test"> test link</a>
     <script>
        var a = document.querySelector('.test')
        a.href = 'http://www.baidu.com';
     </script>
   </body>
</html>
```

file `main.html`

``` html
<html>
   ...
  <body>
     <webview src="index.html" preload="test.js"></webview>
     <script>
       var w =  document.querySelector('webview')
      w.addEventListener('ipc-message' ,  function(e){
         console.log('e.args' , e.args[0]);
         // return `.test{display:block}  test link  var a = document......`
         // Here will accidentally `script` and `style` tags in the content also get to
      })
     </script>
  </body>
</html>
```

file `test.js`

``` js
   var ipcRenderer = require('electron').ipcRenderer;
   window.onload = function(){
     // return a `body` content
      ipcRenderer.sendToHost('result' , document.body.innerText);
   }
```

Is it a bug?

**Comment by zcbenz** [comment] 2016-07-21 09:30
I tried with your code but it works as expected, it seems that the problem is in your other parts of code.

**Comment by baihuibo** [comment] 2016-07-21 09:48
So what about this?

file `test.js`
```js
var ipcRenderer = require('electron').ipcRenderer;
document.addEventListener('DOMContentLoaded' , function () {
    ipcRenderer.sendToHost('result' , document.body.innerText);
})
```

file `main.html`
```html
<html>
...
  <body>
  <webview src="http://www.ptfish.com/thread-1161551-1-1.html"
         preload="test.js"></webview>
<script>
    var w = document.querySelector('webview');
    w.addEventListener('ipc-message', function (e) {
        console.log('e.args', e.args[0]);
        // The returned content comes with 'style' and `script` code
    })
</script>
 </body>
</html>
```

I have tried it in the Chrome browser, it is right, but the result is not correct in electron

**Comment by zcbenz** [comment] 2016-07-21 10:55
I didn't see any difference.

**Comment by kevinsawicki** [comment] 2016-09-30 17:49
@baihuibo are you still experiencing this issue on Electron 1.4.x?

**Comment by kevinsawicki** [comment] 2016-11-16 20:51
Closing this out until more information is provided.

**Closed by kevinsawicki** 2016-11-16 20:51 UTC
Labels: more-information-needed

**Comment by baihuibo** [comment] 2016-11-21 06:11
@kevinsawicki   This problem has been solved, is the target site to rewrite the `innerText` reader to achieve the node

I'm sorry, I'm late to see the news.
