### ISSUE TITLE
Problem with Mac os

### ISSUE THREAD

**Issue by Devhercule** [electron/electron#10689] opened 2017-10-04 15:19 UTC
Hi,

I want to use Electron on mac.

* Electron version: 1.6.14
* Operating system: Mac Os 10.10.5

### Actual behavior

```
<<<< VTVideoEncoderSelection >>>> VTSelectAndCreateVideoEncoderInstanceInternal: no video encoder found for 'avc1'

[10:22:51.406] VTSelectAndCreateVideoEncoderInstanceInternal signalled err=-12908 (err) (Video encoder not available) at /SourceCache/CoreMedia_frameworks/CoreMedia-1562.238/Sources/VideoToolbox/VTVideoEncoderSelection.c line 1245
[10:22:51.407] VTCompressionSessionCreate signalled err=-12908 (err) (Could not select and open encoder instance) at /SourceCache/CoreMedia_frameworks/CoreMedia-1562.238/Sources/VideoToolbox/VTCompressionSession.c line 946
```

Can you help me fix this issue?

Thank you

**Comment by zeke** [comment] 2017-10-04 22:35
Please share a code example that reproduces the issue.

**Comment by Devhercule** [comment] 2017-10-05 07:21
This is produced with the Electron quick start example given in :

```
# Clone the Quick Start repository
$ git clone https://github.com/electron/electron-quick-start

# Go into the repository
$ cd electron-quick-start

# Install the dependencies and run
$ npm install && npm start
```

**Comment by MarshallOfSound** [comment] 2017-10-05 07:56
@Devhercule I can't reproduce this issue on any of the macOS versions I am running at the moment.  What exactly happens when this log message is displayed?  E.g. Does Electron crash?

**Comment by Devhercule** [comment] 2017-10-05 08:11
No, Electron does not crash. But It's a message displayed on the terminal. I don't know if it will have effect after in navigation. 
I tried it with other example of code, always the same error message (only on mac, on windows it works perfectly)

**Comment by MarshallOfSound** [comment] 2017-10-05 08:17
@Devhercule If electron doesn't crash and no noticeable issue can be seen it is probably just a debug log coming from either macOS or Chromium, these occur on different machines for different reasons.  This log appears to come from within macOS api's.

I'm going to close this out as there isn't an actual issue here.

**Closed by MarshallOfSound** 2017-10-05 08:17 UTC
Labels: more-information-needed
