### ISSUE TITLE
The connection from pid 0 was invalidated from this process.

### ISSUE THREAD

**Issue by ph55** [electron/electron#9201] opened 2017-04-15 14:28 UTC
* Electron version: v1.6.2
* Operating system: macOS Sierra 10.12.4

### Expected behavior

No errors should appear

### Actual behavior

When switching focus back to app, error thrown:
```
Electron[29940:760255] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : [self textInputContext]=0x0 *NO* NSRemoteViewController to client, NSError=Error Domain=NSCocoaErrorDomain Code=4099 "The connection from pid 0 was invalidated from this process." UserInfo={NSDebugDescription=The connection from pid 0 was invalidated from this process.}, com.apple.inputmethod.EmojiFunctionRowItem
```

### How to reproduce
Run app with `electron .`
Switch focus to another app and back to electron app again - error thrown.
Reproduced with electron-quick-start:

`$ git clone https://github.com/electron/electron-quick-start`
`$ cd electron-quick-start`
`$ npm install && npm start`

**Comment by MarshallOfSound** [comment] 2017-04-15 23:11
@ph55 I've seen this before a few times I think and AFAIK it didn't cause any obvious issues, not saying it's not a problem that should be fixed but has this caused any noticeable issue for you?

**Comment by ph55** [comment] 2017-04-16 13:35
@MarshallOfSound 
Yes, seems that it doesn't affect workflow. 
But for smooth user experience error should be fixed IMHO.

**Comment by kevinsawicki** [comment] 2017-04-27 18:04
Looks like this has also been reported against other apps that aren't electron-based like macvim, https://trac.macports.org/ticket/53838

Might be worth opening an upstream issue for this if it can be reproduced in standalone Chrome.

**Comment by kevinsawicki** [comment] 2017-04-27 18:05
> Might be worth opening an upstream issue for this if it can be reproduced in standalone Chrome.

I tried launching Chrome from the terminal and switched focus a couple times but couldn't get it to log out this message.

**Comment by zcbenz** [comment] 2017-06-20 07:09
I saw this a lot when writing native Cocoa apps, it usually happens when the app does not use any native Cocoa view that accepts keyboard input. You can simply reproduce this by creating an empty `NSWindow` and then switch between apps:

<img width="614" alt="screen shot 2017-06-20 at 16 07 50" src="https://user-images.githubusercontent.com/639601/27320780-a1d7438c-55d2-11e7-9f94-a14ea93fecb7.png">

Chrome does not have problem because it uses `NSTextField` in lots of places.

So this is a macOS bug and we are not able to fix it on Electron's side.

**Closed by zcbenz** 2017-06-20 07:09 UTC
Labels: fixme/bug, platform/macOS

**Comment by natew** [comment] 2017-11-01 06:49
How about just quieting this error, is there a way to hook into even console.log and silence it? It triggers my warning bell continuously, but patching over the console.* events didn't seem to catch it.

**Comment by sushilei** [comment] 2018-04-03 06:47
dose this have solved? I encountered the same problem
