### ISSUE TITLE
[Bug]: WCO on Windows occludes dev tools

### ISSUE THREAD

**Issue by sbatten** [electron/electron#34129] opened 2022-05-06 21:42 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.4.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

Using WCO and frameless windows on Windows, the WCO does not occlude the top right corner of the dev tools when they are placed on the right side.

### Actual Behavior

Using WCO and frameless windows on Windows, the WCO occludes the top right corner of the dev tools when they are placed on the right side.

**Comment by codebytere** [comment] 2022-05-09 13:03
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by sbatten** [comment] 2022-05-12 00:09
@codebytere for whatever reason, fiddle is not letting me post to a gist. The whole repro is very simple. Here is the full fiddle code 
<img width="824" alt="image" src="https://user-images.githubusercontent.com/6561887/167966879-aa6eb14b-17a9-47d0-8a55-bf3c519021a6.png">

The only important part is this set of options for `BrowserWindow`
```js
    {
      frame: false,
      titleBarOverlay: true,
      titleBarStyle: "hidden"
    }
```

Then open dev tools in the window that is created and see the native controls occlude the dev tools

**Comment by codebytere** [comment] 2022-05-12 10:57
cc @clavin and/or @mlaurencin

**Comment by clavin** [comment] 2022-05-12 23:08
Can confirm this happens. The window controls cover up the dev tools, most notably the settings, customization, and close buttons of the devtools (all very important!)

It seems Chrome avoids this issue by *always* opening the devtools detached on all PWAs (not restricted to just WCO windows, interestingly) and the dev tools do not allow docking on the window.

**Comment by panther7** [comment] 2022-06-01 08:25
electron v19.0.1, windows 11

![2022-06-01 10 14 44](https://user-images.githubusercontent.com/3808250/171361184-6e7cf6e7-fd1a-4610-9f24-681658d3087d.png)

**Closed** 2022-08-11 13:16 UTC
Labels: platform/windows, bug :beetle:, status/confirmed, 17-x-y, 18-x-y, 19-x-y

**Comment by ArturoRSX** [comment] 2025-03-06 07:39
Hello, this error is currently present in vs code (using lastest version of VS Code, Windows 11)

**Comment by mlaurencin** [comment] 2025-03-06 16:44
@ArturoRSX If you can make a reproduction of this issue with only the code necessary, feel free to make a new issue including that reproduction ([Electron Fiddle](https://www.electronjs.org/fiddle) is a good resource for that). If you cannot, I suggest you file an issue with VS Code first.

**Comment by ArturoRSX** [comment] 2025-03-06 16:50
Hello,

There's no code.

Just do this:

1. Install Visual Studio Code
2. Open Developer Tools in VS
3. In the Developer Tools Window, Click in the 3 dots -> Dock to right

And that's all.
Now the Windows buttons are occluding a section of the application.

Lastest update of Visual Studio Code and Windows 11

**Comment by mlaurencin** [comment] 2025-03-10 01:16
@ArturoRSX Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. Please report your issue to VS Code. If they direct you back here, since this specific issue has already been marked as closed, please make a new issue with your information.
