### ISSUE TITLE
Electron not working when running in terminal on Ubuntu Linux

### ISSUE THREAD

**Issue by RyanZim** [electron/electron#12850] opened 2018-05-07 19:35 UTC
* Electron Version: 2.0.0
* Operating System (Platform and Version): Lubuntu/Ubuntu 17.10
* Last known working Electron version: 1.8.x

**Expected Behavior**
Electron should open and be functional when run from the terminal

**Actual behavior**
Electron either doesn't open, opens to a black screen, or freezes shortly after opening. The command doesn't exit, it just hangs there.

**To Reproduce**
```sh
$ git clone https://github.com/electron/electron-quick-start
$ npm install
$ npm start
```

**Additional Information**
If you run `npm start > /dev/null`, `npm start 2> /dev/null`, or `npm start &> /dev/null`, the issue cannot be reproduced. This makes me suspect that there's some bug with streaming to a terminal emulator (perhaps the terminal emulator gives backpressure that electron can't handle?)

**Comment by ckerr** [comment] 2018-05-07 23:59
I'm not seeing this when running either `2.0.0` or `master` in Ubuntu 18.04.

Could you try the same experiment on a clean system to see if it's reproducible for you there too?

**Comment by ckerr** [comment] 2018-05-08 05:36
@alice-em, saying "app X crashes" is essentially inviting the Electron team to triage arbitrary codebases that they are unfamliar with, so I encourage reporters to follow @RyanZim's example of having a small standalone 'hello world' style app that can be tested with.

In any case, the `env->async_hooks_init_function().IsEmpty()` assertion appears to be a duplicate of #10905. The discussion there implies that it's an issue with the `natives` module rather than an Electron issue.

**Comment by alice-em** [comment] 2018-05-08 06:13
Electron worked on a second attempt with an entirely new project.  It must've been something in the api that changed just before `1.8.4` for me to case my particular issue on my first project.

**Comment by RyanZim** [comment] 2018-05-08 16:37
@ckerr I spun up a fresh VM of Lubuntu 17.10 and got the same result as https://github.com/electron/electron/issues/12850#issuecomment-387246000 with electron v2.0.0

**Comment by Klooven** [comment] 2018-05-15 14:04
I'm also having this problem after upgrading from Ubuntu 16.04 to 18.04. Running `ELECTRON_ENABLE_LOGGING=true npm start` does not give me any messages related to this.

<br><br>

_Ps. My app is based on the [electron-next skeleton](https://github.com/leo/electron-next-skeleton) (probably doesn't have anything to do with this)_

**Comment by Klooven** [comment] 2018-05-17 14:02
I've been investigating a bit more and I actually discovered that the app works correctly in the VS Code debugger without [electron-next](https://github.com/leo/electron-next), so for me it might be a different problem.

**Comment by peterdanis** [comment] 2018-06-18 08:15
I can also reproduce the issue with Electron 2.0.2 on Fedora 27 and Ubuntu 18.04.

My application (https://github.com/peterdanis/wrapbox) works when I build it (as AppImage) and run it from file manager, but hangs after a very short time (1-2s) when started from command line.

Can be also reproduced by running the default Electron "app" (see picture below), by running `yarn electron` - this works for 20-30s on my two VMs and than it stops responding.

By default Electron app I mean:
![image](https://user-images.githubusercontent.com/26599181/41525123-3cff446a-72e0-11e8-862d-ae35b4b1e6be.png)

I do not have `electron` installed globally.

**Comment by Klooven** [comment] 2018-07-24 09:44
I found this (temporary) solution: https://github.com/electron/electron/issues/13624#issuecomment-404537806 (use `--disable-gpu`). It worked for me.

**Comment by wamoyo** [comment] 2018-10-24 16:42
I'm still having the same issue. I want to use electron, but even the sample app opens up with a blank screen: 

![screenshot from 2018-10-24 12 38 42](https://user-images.githubusercontent.com/1170326/47446728-d3e08c00-d789-11e8-89e8-e4154dc3f0ab.png)

I'm on Ubuntu 14.04 which is quite old at this point. I'll try again at 18.04. Getting a new machine in November.

**Comment by wamoyo** [comment] 2018-10-24 16:45
I'm still having the same issue. I want to use electron, but even the sample app opens up with a blank screen: 

![screenshot from 2018-10-24 12 38 42](https://user-images.githubusercontent.com/1170326/47446728-d3e08c00-d789-11e8-89e8-e4154dc3f0ab.png)

I'm on Ubuntu 14.04 which is quite old at this point. I'll try again at 18.04. Getting a new machine in November.

The interesting bit is that slack works just fine on my setup, and I'm almost certain they're running on electron.

**Comment by ioev** [comment] 2018-11-09 17:50
Same issue running Ubuntu 18.04/18.10 through VMWare 14.1.3, Intel(R) UHD Graphics 630.  Running "npm start" from the terminal locks up after a few seconds, sometimes rendering the entire VM unresponsive to mouse input (but can alt-tab to the terminal and control-c to restore it.)  Running as suggested "npm start > /dev/null" solves the problem, but running with "--disable-gpu" does not.

**Comment by SudoHenk** [comment] 2018-11-10 17:55
Debian Jessie, Dell XPS 15 9560 with a GTX 1050 using bumblebee seems to having the same problem. Interestingly, I tried both 3.0.8 where the window opens but nothing of the HTML is displayed, and 2.0.2 where everything worked fine. The fix npm start > /dev/null seems to work, but this does not feel like a permanent fix.

**Comment by CharlesBunders** [comment] 2018-11-13 02:33
Debian 9.6 Stretch with Node 10.13.0 and Electron 3.0.6 same issue.

**Comment by Maurimura7** [comment] 2018-11-13 20:04
Same here. 

Debian 9.6 Node v11.1.0 Electron 3.0.9 

Works fine using `--disable-gpu` as @Klooven mentioned.

**Comment by rogithub** [comment] 2018-11-27 20:49
this does not work for me 
ELECTRON_ENABLE_LOGGING=true npm start

`> ccclient@1.0.0 start /home/ro/Documents/code/ccclient
> electron . --disable-gpu

[9674:1127/144912.824933:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
Failed to load browser extensions from directory: /home/ro/.config/ccclient/DevTools Extensions
{ Error: ENOENT: no such file or directory, open '/home/ro/.config/ccclient/DevTools Extensions'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at App.<anonymous> (/home/ro/Documents/code/ccclient/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:419:52)
    at Object.onceWrapper (events.js:273:13)
    at App.emit (events.js:187:15)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/ro/.config/ccclient/DevTools Extensions' }
[9674:1127/144912.929499:ERROR:nss_util.cc(724)] After loading Root Certs, loaded==false: NSS error code: -8018
[9674:1127/144912.972778:ERROR:service_manager_context.cc(258)] Attempting to run unsupported native service: /home/ro/Documents/code/ccclient/node_modules/electron/dist/content_gpu.service
[9674:1127/144913.066875:INFO:CONSOLE(184)] "%cElectron Security Warning (Insecure Content-Security-Policy)", source: /home/ro/Documents/code/ccclient/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js (184)`

**Comment by JPustkuchen** [comment] 2018-11-30 16:34
I can also confirm this on Ubuntu 18.04 as VMWare Workspace virtual instance.

As a workaround
> /dev/null 
-- disable-gpu 

both works for me.

**Comment by kuun** [comment] 2018-12-05 14:29
I had the same issue when I set display mode as 'Join Displays'.

**Comment by fmiceli24** [comment] 2018-12-10 14:14
Same here. --disable-gpu workaround.

Ubuntu 14.04, Gnome. Electron version 3.0.0

**Comment by sdetweil** [comment] 2019-01-29 11:53
i still see the same bug, electron 2.0.0 or 2.0.16 on Ubuntu 18.04, npm start 2>/dev/null bypass works

**Comment by Maurimura7** [comment] 2019-01-30 00:00
> Same here.
> 
> Debian 9.6 Node v11.1.0 Electron 3.0.9
> 
> Works fine using `--disable-gpu` as @Klooven mentioned.

Works now in electron v3.1.1. thanks!

**Comment by sofianguy** [comment] 2019-08-09 00:52
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 21:04
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 21:04 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/linux
