### ISSUE TITLE
[Bug]: detecting online status is not working

### ISSUE THREAD

**Issue by GeekCornerGH** [electron/electron#29709] opened 2021-06-15 17:37 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2 professionnal

### What arch are you using?

x64

### Expected Behavior

Using `window.addEventListener('online', () => {` (offline too) should be fired

### Actual Behavior

Event is not fired (added console.log to test)

### Testcase Gist URL

https://gist.github.com/27cdc54750d780486a1de8df4a8bb660

**Comment by nornagon** [comment] 2021-06-15 17:46
What are you doing to trigger the event? Are you turning off the network from the system tray?

Does this event fire when you try the same logic in Chrome?

**Comment by GeekCornerGH** [comment] 2021-06-15 18:12
@nornagon Google Chrome is not returning anything. Also, yes I am turning off network from icon in systray (also tried with plane mode)

**Comment by nornagon** [comment] 2021-06-15 19:00
@GeekCornerGH do you mean that Chrome also doesn't fire those events?

If this feature is functioning the same in Electron as it does in Chrome, then that's working as intended.

**Comment by GeekCornerGH** [comment] 2021-06-15 19:14
@nornagon What to do?

**Comment by nornagon** [comment] 2021-06-15 23:58
Since this behavior is working as intended, it's not a bug and I'm going to close this issue. You might have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Closed by nornagon** 2021-06-15 23:58 UTC
Labels: blocked/need-info ❌, bug :beetle:

**Comment by xudafeng** [comment] 2021-09-10 12:25
https://github.com/electron-modules/network-interface

The goal of this project is to provide a library that can be used by Node.js so that we can accurately obtain the current computer network status and support the integrated use of frameworks like Electron. At this stage, only some APIs of wlanapi and netlistmgr are wrapped.
