### ISSUE TITLE
Electron 6.0.0 not support windows 7

### ISSUE THREAD

**Issue by zlab** [electron/electron#19569] opened 2019-08-01 16:34 UTC
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 6.0.0
  * 
* **Operating System: Windows 7 32bit
  * 
* **Last Known Working Electron version: 5.0.8
  * 

### Expected Behavior

can start on win7

### Actual Behavior

can not start

### To Reproduce

* https://github.com/electron/electron-quick-start
* edit package.json electron version to 6.0.0
* npm start
* can not start electron

**Comment by codebytere** [comment] 2019-08-01 18:03
@zlab as it stands, this is not enough information for us to take action. What, precisely, happens when you try to run `npm start`? Is there an error?

**Comment by zlab** [comment] 2019-08-02 00:58
when i run `npm start`, nothing happened, no error, you can clone the project and try it

**Comment by giridharkannan** [comment] 2019-08-06 13:57
@codebytere There is no issue in creating the exe file nor when using npm start. When you install and run in an actual 32bit Windows OS is when you will see the issue. The App will crash and will be stuck in a black screen

**Comment by miniak** [comment] 2019-08-06 16:51
I've tried reproducing the issue using a Windows 7 32-bit VM from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and it works just fine.
<img width="1509" alt="Screen Shot 2019-08-06 at 6 50 25 PM" src="https://user-images.githubusercontent.com/1281234/62559366-230c2f00-b87b-11e9-86fe-044c6d5b8cfb.png">

**Comment by giridharkannan** [comment] 2019-08-06 17:14
Instead of using "election ." could you create an exe file and check the same. Even after that if you dont face any issue, I will try to send the crash dump.

**Comment by MarshallOfSound** [comment] 2019-08-06 18:10
I can't validate on a 32bit VM, and I only have 64bit physical machines to test with (can't repro their either)

**Comment by giridharkannan** [comment] 2019-08-06 19:00
When you say you can't validate on your 32bit VM, did you create and exe file to test it or you just used "electron ." or "npm start". One more thing, I don't know whether this is also the reason, I created the exe buid file using my Linux (ubuntu machine) and then used the exe in Windows 32

**Comment by giridharkannan** [comment] 2019-08-13 14:14
@sofianguy Let me know if you need anymore information from my end, am more than happy to share those

**Comment by enOehTsIsihT** [comment] 2019-08-15 23:44
[https://github.com/ipfs-shipyard/ipfs-desktop/issues/951](url)
 the same issue?

**Comment by giridharkannan** [comment] 2019-08-17 09:56
@enOehTsIsihT I don't think it's related to that, as the .Net version that we have is 4.6.1

**Comment by enOehTsIsihT** [comment] 2019-08-17 12:02
@giridharkannan 4.6.1 has black screen issue. 
.NET Framework 4.7.1 or higher  is required ,because it has KB4019990.

https://support.microsoft.com/en-us/help/4019990/update-for-the-d3dcompiler-47-dll-component-on-windows

**Comment by giridharkannan** [comment] 2019-08-17 12:48
@enOehTsIsihT I just came to reply you back and saw you message, As you said the issue is fixed in .NET 4.7
Appreciate your help. Now we are testing the stability (making it run for a day to see if there is some issue)

**Comment by codebytere** [comment] 2019-09-16 22:35
This seems to be a .NET issue and not an issue with Electron, so i'm going to close this out.

**Closed by codebytere** 2019-09-16 22:35 UTC
Labels: 6-0-x, blocked/need-info ❌, platform/windows

**Comment by lonelymoon** [comment] 2019-10-31 02:44
> @giridharkannan 4.6.1 has black screen issue.
> .NET Framework 4.7.1 or higher is required ,because it has KB4019990.
> 
> https://support.microsoft.com/en-us/help/4019990/update-for-the-d3dcompiler-47-dll-component-on-windows

thx, i fixed it

**Comment by fubojie** [comment] 2019-11-14 09:52
> > @giridharkannan 4.6.1 has black screen issue.
> > .NET Framework 4.7.1 or higher is required ,because it has KB4019990.
> > https://support.microsoft.com/en-us/help/4019990/update-for-the-d3dcompiler-47-dll-component-on-windows
> 
> thx, i fixed it

### **You need to install .net framework 4.7.1 and above in the development environment, then recompile and package.**

**Comment by ixlei** [comment] 2020-04-08 13:40
The version of d3dcompiler_47.dll used by electron@6.x is 10.0.17763.132. If it is replaced with 10.0.17134.12, the black screen is fixed. Of course Chrome is also used 10.0.17134.12

**Comment by roy2651** [comment] 2020-05-21 10:13
@ixlei how do you know electron use d3dcompiler_47.dll version I'm working on some with windows compatibility can show my electron app

**Comment by bonniss** [comment] 2020-06-12 18:00
- install .NET Framework on client's machine
- install .NET Framework on developer's machine, then rebuild
- downgrade Electron version

Did all of these, same black screen. Then I moved the portable app folder from `D:` to` C:` and re-ran the` .exe`, it strangely worked!

When it comes to building on specific platform, Electron kills me every time.
