### ISSUE TITLE
BrowserWindow transparency not working on Linux in v1.6.2

### ISSUE THREAD

**Issue by elvisvoer** [electron/electron#9164] opened 2017-04-11 15:27 UTC
* Electron version: v1.6.2
* Operating system: Ubuntu 16.04.2 LTS

### Expected behavior

BrowserWindow should be transparent and show only the content

### Actual behavior

BrowserWindow is rendered with a white background and graphics seem broken

### How to reproduce

 $ git clone https://github.com/elvisvoer/electron-shadow-issue.git
 $ npm install
 $ electron . || electron . --disable-gpu --enable-transparent-visuals

**Comment by sillyslux** [comment] 2017-04-13 13:43
I think this is a duplicate of #8532 and #2170.
My workaround was to downgrade to a version which i know works fine (1.3.4).
Would be nice to know with what version this has started.

**Comment by kevinsawicki** [comment] 2017-04-27 18:38
> I think this is a duplicate of #8532 and #2170.

Thanks, merging this into #8532 

@elvisvoer please subscribe to that issue for updates.

**Closed** 2017-04-27 18:41 UTC
