### ISSUE TITLE
Windows are often shown ~1s after wnd.show() (behavior similar to CSS opacity:0)

### ISSUE THREAD

**Issue by wp777** [electron/electron#21129] opened 2019-11-14 10:43 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.1, v6.1.4, v6.0.0
* **Operating System:**
  * Manjaro 18.1.0 x64 (KDE Plasma 5.16.5)
* **Last Known Working Electron version:**
  * v5.0.12

### Expected Behavior
Window should be visible immediately after window.show() call.

### Actual Behavior
Window is often shown ~1s after window.show() call. This issue doesn't happen every time.

### To Reproduce
Create an Electron app with following code:
```js
const { app, BrowserWindow, dialog } = require("electron");
function createMainWindow() {
    let win = new BrowserWindow();
    win.loadURL("data:text/html;charset=utf-8,test");
    setTimeout(() => {
        let win2 = new BrowserWindow({ show: false, width: 410, height: 310 });
        win2.loadURL("data:text/html;charset=utf-8,<textarea cols='47' rows='17'></textarea>");
        setTimeout(() => {
            console.log("show()-before")
            win2.show();
            console.log("show()-after")
        }, 50);
    }, 2500);
    return win;
}
app.on("ready", createMainWindow);
```
Start the app from console (keep the console in sight). Wait for "show()-*" messages to appear on the console. Second window will appear at the same time (OK) or after ~1s (bug). Both messages, "show()-before" and "show()-after", always appear at the same time. I was unable to reproduce this issue on Windows/Mac/Ubuntu 18.04 (Gnome).

### Additional Information
Immediately after window.show() the window is at it's place, but it's not visible. However, it is reacting to mouse events. For instance, if textarea is placed inside the second window, hovering mouse over the area where the textarea will be visible causes mouse pointer to change (the window is not visible yet). You can click the invisible textarea, type text, etc. Overall, the window behaves similarly to a HTML element with opacity set to 0.

**Comment by pushkin-** [comment] 2020-11-10 21:26
dupe of [this](https://github.com/electron/electron/issues/23730)?

**Comment by electron-triage** [comment] 2021-03-09 03:26
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 03:26 UTC
Labels: 6-1-x, 7-1-x, bug :beetle:, platform/linux
