### ISSUE TITLE
[Bug]: electron crash __memmove_avx_unaligned_erms

### ISSUE THREAD

**Issue by bruceauyeung** [electron/electron#34458] opened 2022-06-07 06:43 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.1

### What operating system are you using?

Other Linux

### Operating System Version

a derived distro based on LXQT

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

coredump first (unnecessary thread stacks tripped, e.g. threads pthread_cond_wait / nanosleep/futex_wait/...):
~~~
           PID: 14638 (myprocess)
           UID: 1956784317 (hidden-for-security-purpose)
           GID: 697200513 (hidden-for-security-purpose)
        Signal: 11 (SEGV)
     Timestamp: Mon 2022-06-06 09:24:43 CST (1min 18s ago)
  Command Line: /opt/myprocess/myprocess --type=renderer --enable-crashpad --crashpad-handler-pid=14524 --enable-crash-reporter=df0c4458-d0fa-4b40-a609-655e27eb08d9,no_channel --user-data-dir=/home/hidden-for-security-purpose/.config/myprocess --standard-schemes=app --secure-schemes=app --bypasscsp-schemes --cors-schemes --fetch-schemes --service-worker-schemes --streaming-schemes --app-path=/opt/myprocess/resources/app.asar --no-sandbox --no-zygote --node-integration-in-worker --lang=zh-CN --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=4 --launch-time-ticks=2246916945305 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,2120808396371144062,4314148708288885912,131072 --disable-features=PlzServiceWorker,SpareRendererForSitePerProcess --enable-crashpad IS_MAIN_WINDOW
    Executable: /opt/myprocess/myprocess
 Control Group: /
         Slice: -.slice
       Boot ID: 34d0f05b860b49b0880c725cde71396b
    Machine ID: f853be9ceaf24eb58ce0eb46ed227c2f
      Hostname: LIN-C044248F540
       Storage: /var/lib/systemd/coredump/core.myprocess.1956784317.34d0f05b860b49b0880c725cde71396b.14638.1654478683000000.lz4
       Message: Process 14638 (myprocess) of user 1956784317 dumped core.
                
                Stack trace of thread 14670:
                #0  0x000055a027c2b333 n/a (myprocess)
                #1  0x000055a027c2b3f9 n/a (myprocess)
                #2  0x000055a027bdf680 n/a (myprocess)
                #3  0x000055a027bdded6 n/a (myprocess)
                #4  0x000055a027bb94c0 n/a (myprocess)
                #5  0x000055a027bb8cf2 n/a (myprocess)
                #6  0x000055a027bb87b3 n/a (myprocess)
                #7  0x000055a027bb821a n/a (myprocess)
                #8  0x000055a027c54406 n/a (myprocess)
                #9  0x000055a027c419c5 n/a (myprocess)
                #10 0x000055a027c42544 n/a (myprocess)
                #11 0x000055a027c52720 n/a (myprocess)
                #12 0x000055a027c5112f n/a (myprocess)
                #13 0x000055a0269b6716 n/a (myprocess)
                #14 0x000055a0269d24cd n/a (myprocess)
                #15 0x000055a02698175e n/a (myprocess)
                #16 0x000055a0269d2e54 n/a (myprocess)
                #17 0x000055a02699fbdc n/a (myprocess)
                #18 0x000055a025a4859c n/a (myprocess)
                #19 0x000055a026a0edb3 n/a (myprocess)
                #20 0x00007f00bb4362de start_thread (libpthread.so.0)
                #21 0x00007f00b5f86133 __clone (libc.so.6)
                
                Stack trace of thread 14638:
                #0  0x00007f00b5fe8273 __memmove_avx_unaligned_erms (libc.so.6)
                #1  0x000055a024e939de n/a (myprocess)
                #2  0x0000053e07f888d0 n/a (n/a)
                #3  0x0000053e002d7391 n/a (n/a)
                #4  0x0000053e00369538 n/a (n/a)
                #5  0x0000053e00369a51 n/a (n/a)
                #6  0x0000053e00249165 n/a (n/a)
                #7  0x0000053e07e8a6dc n/a (n/a)
                #8  0x0000053e07e8a407 n/a (n/a)
                #9  0x000055a024ef05c8 n/a (myprocess)
                #10 0x000055a024eefa0a _ZN2v88internal9Execution4CallEPNS0_7IsolateENS0_6HandleINS0_6ObjectEEES6_iPS6_ (myprocess)
                #11 0x000055a024de3f3c _ZN2v88Function4CallENS_5LocalINS_7ContextEEENS1_INS_5ValueEEEiPS5_ (myprocess)
                #12 0x000055a02a15d64d n/a (myprocess)
                #13 0x000055a02a15d933 _ZN4node12MakeCallbackEPN2v87IsolateENS0_5LocalINS0_6ObjectEEENS3_INS0_8FunctionEEEiPNS3_INS0_5ValueEEENS_13async_contextE (myprocess)
                #14 0x000055a02a1bc690 napi_make_callback (myprocess)
                #15 0x00007f00a51c0a8a _ZN3FFI12CallbackInfo12DispatchToV8EPNS_13callback_infoEPvPS3_b (.org.chromium.Chromium.hx9Ptd)
                #16 0x00007f00a51c1690 _ZN3FFI12CallbackInfo15WatcherCallbackEP10uv_async_s (.org.chromium.Chromium.hx9Ptd)
                #17 0x000055a023d811f0 n/a (myprocess)
                #18 0x000055a023d8f9f6 n/a (myprocess)
                #19 0x000055a023d815c2 uv_run (myprocess)
                #20 0x000055a023ec7a03 n/a (myprocess)
                #21 0x000055a0269b6716 n/a (myprocess)
                #22 0x000055a0269d24cd n/a (myprocess)
                #23 0x000055a02698175e n/a (myprocess)
                #24 0x000055a0269d2e54 n/a (myprocess)
                #25 0x000055a02699fbdc n/a (myprocess)
                #26 0x000055a029fa75d1 n/a (myprocess)
                #27 0x000055a02400126b n/a (myprocess)
                #28 0x000055a024001ee4 n/a (myprocess)
                #29 0x000055a023fff3fe n/a (myprocess)
                #30 0x000055a023fffe13 n/a (myprocess)
                #31 0x000055a023d921c8 n/a (myprocess)
                #32 0x00007f00b5ead873 __libc_start_main (libc.so.6)
                #33 0x000055a0239eb92a _start (myprocess)
~~~
myprocess uses `node-ffi-napi` to invoke into / callback from  c functions.
before this crash happen, myprocess has already run over 10 days without restart.
while this crash happen, myprocess  is doing cpu-intensive operations( video meeting) and consumes huge memory(possibly over 2G).

`#15`, `#16` : happened in `node-ffi-napi` actually. `CallbackInfo.WatcherCallback` ,`CallbackInfo.DispatchToV8` are functions defined in `node-ffi-napi`. i don't know why coredump said it happened in `.org.chromium.Chromium.hx9Ptd` but i am sure this is wrong.
according to the stacktrace, it is callbacking from ffi at the moment, and it is `memcpy`ing ( implemented with `memmove_avx_unaligned_erms`)

but i don't know:
1, why SEGV happened in `memmove_avx_unaligned_erms` ?
2, does this indicates a bug in `memmove_avx_unaligned_erms`? or in electron ? or in ffi ? or somewhere else ?

### Actual Behavior

SEGV happened in `memmove_avx_unaligned_erms` (libc)

**Comment by deermichel** [comment] 2022-06-07 09:48
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small testcases and publishing them as [gists](https://gist.github.com/) that Electron maintainers can use.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment] 2022-07-14 10:50
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-07-14 10:50 UTC
Labels: platform/linux, crash :boom:, bug :beetle:, blocked/need-repro, 17-x-y
