### ISSUE TITLE
Partition preference doesn't work on custom protocols

### ISSUE THREAD

**Issue by mavidser** [electron/electron#7383] opened 2016-09-28 11:49 UTC
* Electron version: 1.2.8
* Operating system: Ubuntu 16.04

I get `gvfs-open: app://main/index.html: error opening location: The specified location is not supported` if I try to open the app via `mainWindow.loadURL('app://main/index.html')`.

Removing the partition preference, or using `file://` to load the URL fixes the issue.

Is there a way to use custom protocols while using partition preference too?

Sample code:
```javascript
const electron = require('electron');
const { app, BrowserWindow, protocol } = electron;

let mainWindow;

protocol.registerStandardSchemes(['app'])

function createWindow () {

  protocol.registerFileProtocol('app', (request, callback) => {
    const url = request.url.substr(5)
    callback({path: path.normalize(`${__dirname}/${url}`)})
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })

  mainWindow = new BrowserWindow({
    webPreferences: {
      partition: 'persist:xxx'
    }
  });
  mainWindow.loadURL(`app://main/index.html`)

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

app.on('ready', createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (mainWindow === null) {
    createWindow();
  }
});
```

**Comment by deepak1556** [comment] 2016-09-28 14:21
You need to register the protocol handler in the same partition for the browser to consider that the scheme is handled.

```
const partition = 'persist:<name>`
const ses = session.fromPartition(partition)

ses.protocol.registerFileProtocol()
```

Same as issue https://github.com/electron/electron/issues/7183 . Closing it out since its not a bug in Electron.

**Closed by deepak1556** 2016-09-28 14:21 UTC

**Comment by mhuggins** [comment] 2018-07-30 21:56
@deepak1556 Is that approach possible for webviews as well?  Our app uses custom protocols within webviews, and the partition attribute is only used on webviews, not the main `BrowserWindow`.

(Happy to open a new issue or reach out directly if that's more appropriate!)
