### ISSUE TITLE
The problem regarding two tap on webview

### ISSUE THREAD

**Issue by vinebrancho** [electron/electron#6059] opened 2016-06-15 09:31 UTC
- Electron version: 1.0.2
- Operating system: Linux 4.4.3, Window8

I am developing webapps on touch based device using electron. As I use, electron is very cool solution for desktop app. Thanks for all developers of electron. 

Now I have faced the problem regarding use of webview. 
When I do two taps on anchor tag in a webview, new page is loaded on the webview normally.
But any touch events on newly loaded page don't occur by single finger, so that I can't interact the page.
By the way, two more fingers occurs touch events. And mouse events occur and are handled normally. 

I simply loaded the following local file using electron. For options of BrowserWindow, I use one defined as default.
You can also reproduce my problem by doing two taps on touch monitor.

```
<html>
   <body>  
     <webview src="http://electron.atom.io" style="width:100%;height:100%;"></webview>  
  </body>  
</html>
```

May I define something to avoid this problem? Otherwise, Is this a bug of webview?

**Comment by zcbenz** [comment] 2016-06-16 04:21
Can you try whether the same problem occurs in this Chrome app?
https://chrome.google.com/webstore/detail/browser-sample/edggnmnajhcbhlnpjnogkjpghaikidaa

I want to verify whether it is an upstream Chromium bug, but I don't have any touch device by handle.

**Comment by vinebrancho** [comment] 2016-06-16 05:11
I installed and run browser-sample chrome app in my Windows. 
In browser-sample that you said, same problem didn't occurs. 
My chrome version of Windows is chrome version 51.0.2704.84m that is lastest.

**Comment by zcbenz** [comment] 2016-06-16 05:25
Can you try Electron v1.2.x which is Chromium 51 based? It could happen that you encountered an old bug of Chromium.

**Comment by vinebrancho** [comment] 2016-06-17 16:45
As I tried in electron v.1.2.3, this problem still occurs. Only occurrence frequency become less. When I touch anchor tag more 3 times quickly on any website, this problem occurs almost always.

**Comment by zcbenz** [comment] 2016-06-19 10:40
Hmm I have no idea of this, the underlying code of webview in Electron should be exactly the same with Chromium.

**Comment by khkramer** [comment] 2016-07-12 14:49
I have this issue as well.
Whenever I quickly tap a link multiple times, touch input doesn't work on the next page.
If i swipe over a link then tap it and swipe again it also happens.

**Comment by ogerik** [comment] 2016-07-13 06:15
I also have this issue as described above!

**Comment by milkmanjr** [comment] 2016-07-28 14:22
I'm able to reproduce this consistently.

Add an webview and then tap on an anchor a lot.

**Comment by zcbenz** [comment] 2016-07-29 01:08
Does it still happen in v1.3.x?

**Comment by milkmanjr** [comment] 2016-07-29 01:25
@zcbenz  thanks for the quick response. Just upgraded the app to v1.3.x and it still happens.

**Comment by khkramer** [comment] 2016-08-31 08:59
If it helps I could upload an example with the minimum conditions to reproduce the bug.

**Comment by zeke** [comment] 2016-08-31 20:05
> I could upload an example with the minimum conditions to reproduce the bug.

@khkramer thanks, please do!

**Comment by kevinsawicki** [comment] 2016-09-30 17:46
can people try 1.4.x and see if this is still happening?

**Comment by katsura-da** [comment] 2016-09-30 22:57
Yep (v1.4.2). But the interesting thing is that if I add an event listener to the `document` in the developer tools it still logs the touch event.

Just tried a preload script with `touchstart`, `touchcancel`, `touchend`, and `click` eventhandlers. `touchcancel` never fires, `touchstart` and `touchend` always, and `click` only when the navigation actually will happen. Clicking with the mouse still works and fires the `click` event.

Does not happen in iframes.

**Comment by katsura-da** [comment] 2016-10-01 10:24
I did some more testing. This does not seem to happen on single page apps, but only when the page reloads.

More interestingly if I add my `preload.js` with the event handlers to the `index.html` (so my main script) then I tap fast enough on links, I noticed that sometimes when the page reloads the main script catches the touch events although I'm still tapping on the webview. And when this happens the touch stops firing the `click` event, even outside the webview. This does not seem to happen in the mentioned Chrome extension.

The only thing I can think about that is different in Chrome is that Electron forces the renderer to restart for every navigation (based on https://github.com/electron/electron/issues/4985#issuecomment-243041839), so might be something related to that code. But in the Chrome extension this 'touch event bleed through' cannot be reproduced even when I navigate across different domains.

I'm open to any ideas of what I should test next.

**Comment by benweissmann** [comment] 2016-12-02 17:25
I'm also seeing this bug. I can reliably reproduce it by creating a keyboard shortcut that refreshes the webview, and then holding a finger on the touchscreen while hitting that shortcut to refresh the webview. When the page finishes reloading, i see the behavior katsura-da describes: touchstart and touchend get fired, but no click events.

I'm building a single-page app that runs in a webview. We sometimes end up in this state even without reloading the webview. It's a particularly bad issue for us because our app is designed to be a kiosk app that runs on a touchscreen, so from a user's perspective, when they're in this state, the app appears entirely unresponsive. I have not been able to reliably reproduce this issue without reloading the webview as described above.

I'm working around this for now by observing touchstart and touchend events in a preload script and  manually sending clicks by calling `sendInputEvent` on the webview with mousedown and mouseup.

Let me know if there's anything I can test or help with on my end.

**Comment by benweissmann** [comment] 2016-12-12 19:58
Some more info:

- I'm seeing two different types of (maybe related) errors.
- As described above, if you leave a finger on the screen while refreshing the webview, the webview ends up in a state where it gets `touchstart` and `touchend` events, but no `click` events are fired and scrolling doesn't work. Using a mouse still works, but touches don't trigger clicks or scrolls. The `touches` array in the event object for `touchstart` and `touchend` are accurate (they correctly reflect the touches on the screen). This case is consistently reproducible.
- Every once in a while, Electron will end up in a similar state *without* refreshing the webview. The most consistent way i've found to reproduce this is to place one finger on the screen, then a second, then lift both fingers. It's easiest to reproduce right after starting the app. In this problematic state, we see similar behavior (`touchstart` and `touchend` without `click` or scrolling), but we see a phantom touch in the `touches` array -- there's an extra touch in the array that doesn't correspond to a physical touch on the screen. Sometimes, this state goes away after using the mouse. However, our users report that the app is totally frozen, because they're using it on a touchscreen with no mouse or keyboard, and from their perspective, touching and scrolling is unresponsive.

The rest of the operating system continues to work fine, so this doesn't appear to be a hardware or OS issue.

**Comment by benweissmann** [comment] 2016-12-12 23:10
I have a minimal app that reproduces the first issue (leaving a touch on the screen while reloading the webview): https://github.com/benweissmann/electron-browser

I will try to reproduce the intermittent issue and report back, but hopefully that reproduction is enough to look into the first issue. Let me know if there's anything else I can help with -- what's the best place in the Electron or Chromium source to start tracking this down?

**Comment by benweissmann** [comment] 2016-12-12 23:33
I am able to occasionally reproduce the second case of the bug (where it happens without a page reload) on the minimal app. It seems to happen after the app has been idle for a while and then i touch the app with two fingers.

**Comment by benweissmann** [comment] 2016-12-12 23:46
I've reproduce the second case of the bug and shot a video: https://vimeo.com/195381674

Note that i'm touching the screen with a single finger, but the console is reporting three touches (before the video, i ran `document.addEventListener('touchstart', (evt) => console.log(evt.touches))` to have it log the TouchList)

**Comment by krokofant** [comment] 2017-01-22 21:44
I think a deployed application of mine is subject to this bug. I haven't been able to reproduce it successfully but it just seem to occur when there are a lot of touch presses.

My app consists of a navbar which controls a webview. I've just done the ugliest workaround of just restarting the application after a given interval incase it freezes up the touch.

For a while I thought that I didn't implement good enough error handling in regards to the electron process or window hanging but that wasn't the problem.

**Comment by zcbenz** [comment] 2017-06-12 07:53
While we would like to solve this, I'm afraid this is an upstream bug of Chromium, and none of us in Electron team are familiar with Chromium's touch device code enough to be able to fix it. So I'm closing this as won't fix.

**Closed by zcbenz** 2017-06-12 07:53 UTC
Labels: blocked, component/touch, more-information-needed
