### ISSUE TITLE
Display problem with MacOS High Sierra GM

### ISSUE THREAD

**Issue by doomtr666** [electron/electron#10559] opened 2017-09-20 15:58 UTC
Hi, i work on an app for windows and mac. On mac os with the High Sierra Golden Master update i've display issue:

![image](https://user-images.githubusercontent.com/7236074/30653863-8e4b7822-9e2c-11e7-8d0c-bdeb8f3ac3b7.png)

On previous version of macOs all the background was white. In addition I get this new warning when app starts:

```
2017-09-20 17:11:28.872 Electron[4131:874453] *** WARNING: Textured window <AtomNSWindow: 0x7fbed1c4f0d0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.1.22.1/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3
```

* Electron version: 1.8.0
* Operating system: MacOS High Sierra GM

**Comment by doomtr666** [comment] 2017-09-21 08:07
My fault, I've set up body background to white and it fixes the display issue. Anyway I still have the warning.

**Comment by codebytere** [comment] 2017-09-22 17:55
The warning is expected i believe, but now that you've fixed the primary issue i'm going to go ahead and close this. Feel free to ping me if something else comes up!

**Comment by joevo2** [comment] 2017-09-27 08:47
@doomtr666 I have this issue as well I've set the background white in both the js file or the html file as css but during the initial startup it flashes grey as well and is quite annoying. 
```
mainWindow = new BrowserWindow({
    backgroundColor: '#ffffff',
  });
```
Issues as reported here https://github.com/vitorgalvao/fog/issues/4

**Comment by doomtr666** [comment] 2017-09-28 11:47
@joevo2 luckily i had already do something similar, so didn't notice the blinking ;)

**Comment by joevo2** [comment] 2017-09-29 02:24
@doomtr666 this should be an issue right? Since the default behaviour should be white background? @codebytere

**Comment by codebytere** [comment] 2017-09-29 02:27
If this is still an issue, definitely happy to reopen! We're just trying to close out issues that haven't seen activity in some time are and are not on our radars at the moment.

**Comment by doomtr666** [comment] 2017-09-29 07:28
On previous version of Mac OS defaut behavior was white background. This behavior is specific to High Sierra... So this is an issue ;)

**Comment by Muukuro** [comment] 2017-11-08 15:25
I, too, am running High Sierra and 1.8.1. For me, this warning appears only appears when I create a window with {frame: false}. Creating the window with {backgroundColor: '#FFFFFF'} does not make a difference.

**Comment by TimHerbert** [comment] 2017-11-28 19:36
I had a simple game written in electron that was working. I've updated to high sierra and am seeing the same issue.

**Comment by WickedSik** [comment] 2017-12-19 10:32
I'm having the same issue with a small internal project, frameless windows throw up this error, and it seems to crash the application, but of that I'm not sure.

**Comment by lggarrison** [comment] 2018-01-08 20:57
I am seeing a similar issue using Electron on Mac Sierra.

`/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4`
`/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 5`
`/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 6`
`/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 7`
`/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 8`

I am using
- MacOS 10.12.6
- Node 8.9.1
- Electron 1.7.10

**Comment by hmontes** [comment] 2018-02-12 13:29
Same issue here with a simple code.

```
const electron = require('electron');

const { app } = electron;

app.on('ready', () => {
  console.log('App is now ready');
});
```

my console

> App is now ready
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 5
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 6
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 7
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 9
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 10
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 11
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/

**Comment by hmontes** [comment] 2018-02-12 14:32
Update. If i add app.disableHardwareAcceleration() to the code, the app works fine.

```
const electron = require('electron');

const { app } = electron;

app.on('ready', () => {
  console.log('App is now ready');
})
```

console
App is now ready
>

**Comment by sofianguy** [comment] 2019-01-07 22:42
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:30
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-01-15 20:30 UTC
Labels: blocked/need-info, bug :beetle:, platform/macOS, version/1.8.x
