### ISSUE TITLE
full support for multiple webkitdirectory

### ISSUE THREAD

**Issue by jimtang9527** [electron/electron#839] opened 2014-11-19 03:52 UTC
<input> file . multiple webkitdirectory in chrome can get sub files.but atom-shell can select directory,sub file set only current directory? is bug?

**Comment by appelgriebsch** [comment] 2015-09-21 21:13
+1

**Comment by inossidabile** [comment] 2017-02-06 02:20
+1 - quite a misleading problem really

**Comment by filipe-nunes** [comment] 2017-09-26 15:32
+1 - only one file in the htmlElement.files and it only brings its basic info...

**Comment by camow7** [comment] 2017-12-05 22:35
+1 I'm seeing this as well. On chrome localhost it works perfectly but once built for electron it only gets the selected folder name.

**Comment by zhangling0443** [comment] 2017-12-24 11:57
+1 only gets the selected folder name! I need to support webkitdirectory strongly!

**Comment by dengyaolong** [comment] 2017-12-29 08:28
duplicate of https://github.com/electron/electron/issues/9002

**Comment by dengyaolong** [comment] 2017-12-29 09:35
+1 ！ webkitdirectory is necessary！

**Comment by DenisVuyka** [comment] 2018-01-23 15:10
This ticket is 3+ years old already and still causes lots of issues. Are there any plans to address it?

**Comment by negamaxi** [comment] 2018-06-15 09:15
No updates on this?

**Comment by ythvg** [comment] 2018-06-20 07:02
the same problem, no updates ???

**Comment by schwiet** [comment] 2018-09-06 05:50
Does anyone have a workaround for this?

**Comment by dengyaolong** [comment] 2018-09-08 02:16
@schwiet my workaround is use dialog choose dir, and use node.js walk the dir.

**Comment by codebytere** [comment] 2018-09-23 17:05
Given that there exist workarounds, this is something that isn't on our current roadmap and which I am thus goin to tag as `wontfix`.

**Closed by codebytere** 2018-09-23 17:05 UTC
Labels: bug :beetle:

**Comment by dengyaolong** [comment] 2018-09-26 03:39
@codebytere but webkitdirectory is really important while workaround need a lot of hack code.

**Comment by MajuMadhusudanan** [comment] 2018-10-01 14:44
need a fix to address this issue. Workaround provided require more changes and risky also

**Comment by eggerand13** [comment] 2018-11-18 14:54
I think it would be really helpful if that issue was addressed, especially since the workaround is quite troublesome.

**Comment by fristys** [comment] 2019-01-14 11:59
+1 on the fix. Labelling this as `wontfix` and making people use beyond hacky workarounds is completely unacceptable.
