### ISSUE TITLE
PDF server request is called twice

### ISSUE THREAD

**Issue by MCMicS** [electron/electron#12226] opened 2018-03-12 11:34 UTC
Hello, if I try to load a pdf from server and aopen it in an BrowserWindow with enabled plugins the pdf go to the server twice.
And some times a server got an error with 

> An established connection was aborted by the software in your host machine

* Electron version: 1.8.2
* Operating system: Win 10

### Expected behavior
PDF is received once from server. With Chrome I receive only one request.

### Actual behavior

Two calls for same pdf and sometimes an error on server-side.

**Comment by Tim91084** [comment] 2018-06-19 19:21
@MCMicS I notice the same thing.  Another issue that goes along with this is that the second request seems to always win, and is always sent with a GET.  So in my case, the initial request is a POST to load a PDF with some parameters.  Since those parameters are sent in the second request, the pdf fails to render.

**Comment by sofianguy** [comment] 2019-01-07 21:35
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:42
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-01-15 20:42 UTC
Labels: blocked/need-info, bug :beetle:, platform/windows, version/1.8.x
