### ISSUE TITLE
Background randomly flickering

### ISSUE THREAD

**Issue by 04fsnape** [electron/electron#13393] opened 2018-06-22 23:17 UTC
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: 2.0.0

**Expected Behavior**
Background colour to be consistent.

**Actual behavior**
It seems as though my app is divided vertically into thirds, and each third will randomly start pulsing a slightly different brightness to that of my app's background colour. This is usually triggered by clicking on/hovering over an input or button. Sometimes it will stop for a while and other times it will just continuously flicker. It's driving me crazy, I have tried a lot of things such as removing large sections of my HTML one by one, removing all unnecessary CSS, removing my javascript files, and yet the issue persists.

**To Reproduce**
Electron app with a dark background such as #171717 and inputs (perhaps a select box).

**Screenshots**
As you can see, one third of the screen is a different brightness to the rest after interacting with an input: http://prntscr.com/jy955s

**Additional Information**
I experience no such issues when viewing my website in the regular Chrome browser, I only have this problem in electron.

**Comment by btzr-io** [comment] 2018-06-23 01:15
Same here, noticed after updating electron to version `2.0.3` :disappointed:

**Comment by btzr-io** [comment] 2018-06-23 01:17
@04fsnape Workaround, use `rgb` instead of `hex` and set opacity to `0.99`

```CSS
{ background: rgba(23, 23, 23, 0.99); }
```

**Comment by btzr-io** [comment] 2018-06-23 01:51
https://github.com/atom/atom/issues/12634

**Comment by 04fsnape** [comment] 2018-06-23 09:02
@btzr-io I replaced every single background-color with rgba(x, y, z, 0.99) and the problem still persists. I also tried adding these to my main.js:

```
app.commandLine.appendSwitch('--disable-gpu')
app.commandLine.appendSwitch('--force-gpu-rasterization')
app.commandLine.appendSwitch('--enable-gpu-rasterization')
```

and yet that did not work...

**Comment by 04fsnape** [comment] 2018-06-23 10:51
I don't seem to experience this problem on my laptop...

**Comment by btzr-io** [comment] 2018-06-24 01:30
@04fsnape Weird it works for me, try https://github.com/atom/atom/issues/12634#issuecomment-248899027 or https://github.com/atom/atom/issues/12634#issuecomment-248899027

Anyway looks like the bug was fixed, is this a regression or something? :confused:

**Comment by 04fsnape** [comment] 2018-06-24 10:02
@btzr-io You linked the same comment twice and as I already said I tried adding `app.commandLine.appendSwitch('--disable-gpu')` but it did not work...

**Comment by sofianguy** [comment] 2019-08-09 00:26
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 20:55
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-08-19 20:55 UTC
Labels: 2-0-x, blocked/need-info ❌, bug :beetle:, platform/windows
