### ISSUE TITLE
Electron apps steal focus

### ISSUE THREAD

**Issue by nkkollaw** [electron/electron#12369] opened 2018-03-20 14:43 UTC
* Electron version: multiple
* Operating system: Xubuntu (Bionic)

### Expected behavior

Electron apps should not steal focus

### Actual behavior

Electron apps steal focus

### How to reproduce

Open any app, then navigate to another app.

**Comment by MarshallOfSound** [comment] 2018-03-20 14:57
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by nkkollaw** [comment] 2018-03-20 15:18
Ehm... What is a standalone test?

I'm a user reporting a bug, not necessarily an Electron developer.

**Comment by ckerr** [comment] 2018-03-21 03:32
I know the `more-info-needed` label is already listed, but for the record -- I followed the bug reporter's recipe by starting with one app and navigating to another one. Focus behaved as normal for my desktop whether or not an Electron app was involved.

As the issue description does not explain what apps to test with, nor what version of the apps or Electron were being used, I have no way of testing this further without additional information.

**Comment by nkkollaw** [comment] 2018-03-21 06:46
I see @ckerr. On Xfce, right..?

**Comment by codebytere** [comment] 2018-05-04 17:10
Given comments above and lack of actionable next steps on this issue, i'm going to go ahead and close it. If more information becomes available and we can reproduce the issue, we're happy to go ahead and re-open this.

**Closed by codebytere** 2018-05-04 17:10 UTC
Labels: blocked/need-info, platform/linux/ubuntu

**Comment by lyda** [comment] 2018-11-12 16:00
I'm seeing this with slack. From time to time is steals focus.

**Comment by igtm** [comment] 2020-02-08 14:12
Has it been already fixed? lots of electron based-app I use such as `Discord` , `Slack` etc.. have this very annoying behavior especially when starting those apps.
Native apps like 'Safari' never ever steal focus even when starting it.

**Comment by borekb** [comment] 2020-02-12 14:56
Not sure if it's the same issue but with Visual Studio Code on **macOS**, the app "steals" an entire **space** (screen / Mission Control space). It's probably the same issue as reported here: https://github.com/microsoft/vscode/issues/85294.

I cannot reliably reproduce it but it happens quite frequently when I have an **external monitor** connected to my MacBook. It doesn't matter if VSCode is in full-screen mode or in normal windowed mode, if I'm Cmd-tab'ing into an app that is in another space, VSCode will steal the focus on switch the space right back to where VSCode is.

**Comment by borekb** [comment] 2020-02-14 10:21
I've posted longer description here: https://github.com/microsoft/vscode/issues/90680.

**Comment by chuim** [comment] 2020-11-25 23:01
I just wanted to report that I'm seeing exactly the same issues as @borekb reported, especially when I have a macOS space that is split between VSCode and iTerm.

**Comment by jeffomatic** [comment] 2023-04-06 14:07
Late to the party here, but I'm also observing this behavior. The exact behavior I see is: I close the last application in one MacOS space, and the OS will switch over to an Electron app in a different space and bring it to the foreground. I'm currently on MacOS 13.2.1, but I have the strong impression that the problem predates Ventura.

One thing I can add is that it seems to affect some Electron apps more frequently than others. This may be entirely due to my usage patterns, but it happens with [Unity Hub](https://unity.com/unity-hub) _very_ frequently (I even reported it tot them as a [bug](https://unity3d.atlassian.net/servicedesk/customer/portal/2/IN-37523)), and I have also seen it occur with Figma.

Meanwhile, I keep Slack, Discord, and VSCode nearly all the time, and I don't have any specific memories of it happening with those apps. I'm also an iTerm user and keep that open in its own space all the time, but I haven't noticed any patterns with it; certainly, iTerm itself does not exhibit the focus-stealing.

**Comment by pubkraal** [comment] 2024-09-05 06:55
Still very late, but since it's still happening: Discord and slack are notoriously doing this. Discord is probably worse because it steals focus _many_ times during startup. Can't add anything more that hasn't been said yet.
