### ISSUE TITLE
Setting focusable:false breaks the focus event 

### ISSUE THREAD

**Issue by t57ser** [electron/electron#21459] opened 2019-12-10 15:27 UTC
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.5
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * ?

### Expected Behavior
If the window is focusable then the focus event should be triggered

### Actual Behavior
Setting the window initially to focusable: false and later to true again will not enable the focus events. Even when focusing the window, the event will never be triggered.

### To Reproduce
```
let browserWindow1 = new BrowserWindow({
	show: false,
	x: 1,
	y: 1,
	width: 800,
	height: 700,
	title: "test-title-1",
	focusable: false,
});
browserWindow1.on("focus", () => {console.log("focus");});
browserWindow1.loadURL("http://www.google.com");
browserWindow1.setFocusable(true);
browserWindow1.show();
```

**Comment by loc** [comment] 2019-12-10 19:47
I can repro on macOS in 6.1.5 but it seems to be fixed in 7 and 8. Want to verify on Windows? 

Obligatory fiddle plug, in case anyone reading this doesn't know: [Electron Fiddle](https://github.com/electron/fiddle) is the easiest way to test things quickly in multiple Electron versions.

**Comment by t57ser** [comment] 2019-12-11 07:58
7.1.4 and 8.0.0-beta.4 do not work on windows

**Comment by zcbenz** [comment] 2020-01-21 06:46
I can reproduce on Windows but not macOS.

**Closed** 2020-01-22 01:13 UTC
Labels: 6-1-x, 7-1-x, 8-x-y, bug :beetle:, platform/windows
