### ISSUE TITLE
[Linux] Menu bar text color doesn't follow desktop theme colors

### ISSUE THREAD

**Issue by Photon89** [electron/electron#9681] opened 2017-06-06 08:22 UTC
First of all, let me say sorry for the fact that this issue will most probably not comply with the issue reporting guidelines. This is due to the fact that I am not a developer using electron but just a user using electron apps, in particular Franz (http://meetfranz.com) and Skype (the new electron version of it). Since the issue I want to report appeared in both apps, I assume that it is an issue of electron itself, but if I am wrong here, let me know.

The issue is of rather cosmetic nature: The text color in the menu bar seems to be hard coded to white when not hovered and black when hovered. This leads to the problem that in dark themes the text becomes hard to read when hovered and on light themes when not hovered. Here are some screenshots demonstrating the issue in Skype:

Light theme, not hovered: ![auswahl_054](https://cloud.githubusercontent.com/assets/1191480/26819946/5afdde44-4aa1-11e7-97ae-0d6f34cd9567.png)
Light theme, hovered: ![auswahl_053](https://cloud.githubusercontent.com/assets/1191480/26819944/5af10cf0-4aa1-11e7-8f73-4ef3a30d232e.png)
Dark theme, not hovered: ![auswahl_051](https://cloud.githubusercontent.com/assets/1191480/26819943/5aeda5d8-4aa1-11e7-9b7a-62664926b7c0.png)
Dark theme, hovered: ![auswahl_052](https://cloud.githubusercontent.com/assets/1191480/26819945/5afb6312-4aa1-11e7-9997-e70b0f0a1661.png)

* Electron version: Unknown, I'm using binary packages of Franz and Skype. 
* Operating system: Manjaro Linux

### Expected behavior

The text color in the menu bar should follow the theme settings like in native (GTK) applications

### Actual behavior

The text color is hard to read if hovered on dark themes or not hovered on light themes

### How to reproduce

Use Skype or Franz on Linux with light or dark GTK themes.

**Comment by bil-elmoussaoui** [comment] 2017-06-13 13:02
This is a duplicate of #2927

**Comment by Photon89** [comment] 2017-06-16 11:35
Actually, I realized that this problem does not appear on another machine, where the GTK2 theme being used has no GTK3 variant. It looks like the apps fall back to GTK2 then where the problem does not appear. So I suspect that this is a problem in the GTK3 implementation, isn't it? If electron used GTK2 rather than GTK3, as #2927 indicates, the problem should not appear on the original machine, like it doesn't appear on the machine with a GTK2 only theme. Maybe my reasoning has some flaw? 😄

**Comment by sofianguy** [comment] 2018-01-17 23:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of [#2927](https://github.com/electron/electron/issues/2927). You may want to subscribe there for updates.

Because we treat our issues list as the project team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by sofianguy** 2018-01-17 23:15 UTC
