### ISSUE TITLE
timeZone is not defined in OS X High Sierra

### ISSUE THREAD

**Issue by cetra3** [electron/electron#11670] opened 2018-01-19 03:00 UTC
Time Zone isn't set correctly in OS X High Sierra.   This may be related to some timezones that are currently in daylight savings time, such as Australian Eastern Standard:

![](https://user-images.githubusercontent.com/6415435/35132758-aec68174-fd1c-11e7-8b10-0cca657dacb5.png)

In this screenshot, `date` prints out correctly, but `date.toLocaleString()` is an hour behind, and the `timeZone` value is `undefined`.

* Electron version: `1.7.10`
* Operating system: `OS X High Sierra 10.13.2 (17C205)`

### Expected behavior

The timeZone value is set to the system time zone.

### Actual behavior

* The timeZone value is `undefined`. 
* The toLocaleString function of a date does not display correctly.

### How to reproduce

* Set your OS X system to a timezone such as `Melbourne - Australia`

* Make a new quick start project from the readme:

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start
```

* Open up the developer console by using `Toggle Developer Tools`

* Type in `Intl.DateTimeFormat().resolvedOptions().timeZone`

This relates to: https://github.com/mattermost/desktop/issues/679

**Comment by codebytere** [comment] 2018-01-22 13:55
Hmm, i'm unable to reproduce this using Electron `v1.7.10` and MacOS High Sierra 10.13.2. Is there anything else you had in your repo when you saw this bug?

**Comment by cetra3** [comment] 2018-01-22 22:31
Did you change your system timezone?

**Comment by codebytere** [comment] 2018-01-22 22:49
update, looks like it only likes American time zones 🤔  for some time zones (ex in South America) i get `Uncaught RangeError: Unsupported time zone specified undefined at Object.DateTimeFormat` and for others i get `undefined`. i'll keep digging.

**Comment by brenca** [comment] 2018-01-22 23:06
I tried a few different timezones on Windows 10, can't reproduce there, so seems to be OS specific.

**Comment by brenca** [comment] 2018-01-22 23:13
@codebytere @cetra3 Could [this](https://bugs.chromium.org/p/chromium/issues/detail?id=520783) be related? Look at the last comment, and the bugs they linked there, this might be an upstream issue.

**Comment by codebytere** [comment] 2018-01-23 20:24
hmm yeah i think you're right @brenca, we don't really do anything electron-specific with timezone so i would also be inclined to think we inherited something from chromium that's causing this issue.

**Comment by cetra3** [comment] 2018-01-23 22:00
I have checked the latest version of chromium `66.0.3330.0` and it does not show up in there.

**Comment by codebytere** [comment] 2018-01-23 22:18
@cetra3 we're not running that though, can you check on our current version (61)? keep in mind we're also in the process of upgrading to c62 and c63

**Comment by cetra3** [comment] 2018-01-24 00:47
@codebytere It seems that it's a bug in version 61.  I've used the [following guide](https://www.chromium.org/getting-involved/download-chromium) to find versions to download.

* Version `61.0.3163.0` downloaded from [here](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/488512/) is **Not Working** and shows the timezone as undefined.
* Couldn't any the `62`. version using the guide above.
* Version `63.0.3239.0` downloaded from [here](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/508578/) is **Working** and shows the correct timezone.

**Comment by brenca** [comment] 2018-01-24 00:54
This seems to be in line with the chromium bug discussion, thanks for taking a look.

**Comment by codebytere** [comment] 2018-01-24 04:05
In that case, it'll be resolved when we officially update to Chromium 63; please see https://github.com/electron/electron/projects/7 for progress! I'm going to go ahead and close this.

**Closed by codebytere** 2018-01-24 04:05 UTC
Labels: platform/macOS, triaged/bug, version/1.7.x
