### ISSUE TITLE
Implement chrome headless option

### ISSUE THREAD

**Issue by aight8** [electron/electron#9106] opened 2017-04-04 07:21 UTC
Please, implement the headless option which is available from chrome version 57.

Reason:
Easier usage for testing and scraping (without the xfb hack)

**Comment by MrSaints** [comment] 2017-04-04 11:00
Duplicate of https://github.com/electron/electron/issues/228

**Comment by enlight** [comment] 2017-04-04 14:11
Thanks @MrSaints, closing as duplicate.

**Closed by enlight** 2017-04-04 14:11 UTC
