### ISSUE TITLE
Electron apps freezes / hangs with GPU acceleration enabled

### ISSUE THREAD

**Issue by SWW13** [electron/electron#15696] opened 2018-11-13 11:04 UTC
* Output of `node_modules/.bin/electron --version`:
- multiple affected versions

* Operating System (Platform and Version):
- multiple affected systems

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
- unknown

**Expected Behavior**
Running an electron app does not freezes the app / pc.

**Actual behavior**
Freezes of app / pc happens on some systems.

**To Reproduce**
See https://github.com/signalapp/Signal-Desktop/issues/2442 for a list of affected systems.

**Screenshots**
-

**Additional Information**
This maybe unrelated to electron but I spend some days searching for this issue and electron seems to be the common factor for me, so I'm opening this issue for others having the same / similar problems.

The GPU acceleration of chromium seems to trigger the problem, but it maybe related to the driver / hardware.

Related GitHub Issues:
- https://github.com/signalapp/Signal-Desktop/issues/2442
- https://github.com/swaywm/sway/issues/2508

**Comment by MarshallOfSound** [comment] 2018-11-13 11:11
Duplicate of #13415

**Closed by MarshallOfSound** 2018-11-13 11:11 UTC
