### ISSUE TITLE
[Bug]: Can't detect deviceorientation events

### ISSUE THREAD

**Issue by keyiis** [electron/electron#34242] opened 2022-05-15 06:18 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.0

### What operating system are you using?

Windows

### Operating System Version

win10 21H2

### What arch are you using?

x64

### Expected Behavior

Don't block deviceorientation events.

### Actual Behavior

It block deviceorientation events.
```
The deviceorientation events are blocked by permissions policy. See <URL>
t.captcha.qq.com/tdc.js?app_data=6931482429477642240&t=516349110?t=1652594192:1 The deviceorientation events are blocked by permissions policy. See https://github.com/w3c/webappsec-permissions-policy/blob/master/features.md#sensor-features
```

**Comment by VerteDinde** [comment] 2022-05-16 20:57
Hey @keyiis, thanks for reporting this. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Just a quick note on this: based on Chrome's spec, it looks like by default, the deviceorientation, deviceorientationabsolute and devicemotion events are restricted to top-level document and same-origin subframes (it follows from features default allow list 'self'): https://chromestatus.com/feature/5758486868656128 So depending on how you're trying to access these events, this may be expected behavior. If so, we can close this issue, but we can wait and see a repro first.

Thanks in advance!

**Comment by codebytere** [comment] 2022-07-14 10:51
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-07-14 10:51 UTC
Labels: bug :beetle:, platform/all, blocked/need-repro
