### ISSUE TITLE
[Bug]: Cannot extend method to remote web content

### ISSUE THREAD

**Issue by MzoroHaHa** [electron/electron#28953] opened 2021-05-01 09:16 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Last Known Working Electron version

11.0.4

### Expected Behavior

no error like 11.0.4

### Actual Behavior

I want to extend ```window``` through preload.js, but it doesn't work
```
const ElectronApi = require('./src/render')
window.ElectronApi = ElectronApi
console.log(window.ElectronApi)
```
I can see the result in devTools like this
```
Object
saveServer: ƒ saveServer(type, path)
__proto__: Object
````
but when I invoke this method ```saveServer``` ,
```
window.ElectronApi.saveServer("","")
```
I will get an error 

```
cant read saveServer of undefined 
```

**Comment by Prinzhorn** [comment] 2021-05-01 10:02
For security reasons you cannot do that anymore by default. You _could_ use `contextIsolation: false`, but the proper way is to use https://www.electronjs.org/docs/api/context-bridge#contextbridge

```
const { contextBridge } = require('electron')

contextBridge.exposeInMainWorld('ElectronApi', ElectronApi)
```

**Comment by codebytere** [comment] 2021-05-03 10:14
Closing as this is intended behavior.

**Closed by codebytere** 2021-05-03 10:14 UTC
Labels: bug :beetle:
