### ISSUE TITLE
`uploadData` is missing on custom protocol's request when send via XHR

### ISSUE THREAD

**Issue by Gozala** [electron/electron#14720] opened 2018-09-20 05:06 UTC
* Output of `node_modules/.bin/electron --version`:
v2.0.8
* Operating System (Platform and Version):
MacOS 10.13.6

**Expected Behavior**

Sent data via POST / PUT `XMLHttpRequest` to custom [stream protocol handler](https://github.com/electron/electron/blob/2-0-x/docs/api/protocol.md#protocolregisterstreamprotocolscheme-handler-completion) should appear under [`uploadData`](https://github.com/electron/electron/blob/2-0-x/docs/api/structures/upload-data.md) property in of the request object.

**Actual behavior**

`request.uploadData` property is `undefined` when data is send via `XMLHttpRequest`, although it's worth mentioning that it does appear as expected if data is send via `fetch` API.

I will try to create self contained reproducible test case, but posting this here in case it's already a known issue or limitation.

**Comment by Gozala** [comment] 2018-09-20 05:12
This is the code used for sending requests:

```js
var writeFile = (url, data) => new Promise((resolve, reject) => {
  const request = new XMLHttpRequest()
  request.open("PUT", url, true)
  request.setRequestHeader("Content-Type", "text/plain;charset=UTF-8")
  request.onerror = () => reject(request)
  request.onloadend = () => resolve(request.response)
  request.send(data)
})
```

On the protocol handle I get no `uploadData` regardless if I send plain text, blob, array buffer, or form data.

P.S.: I also noticed that in the DevTools network panel no `Request Payload` is displayed.

**Comment by Gozala** [comment] 2018-09-21 01:08
Here is the self contained example illustrating the issue
https://github.com/gozala/electron-quick-start/tree/xhr-upload-data

**Comment by chrisregnier** [comment] 2019-07-03 20:03
Did this ever go anywhere, cause I've got the same problem and can't see a good way to get the uploaded contents into my custom protocol.

**Comment by sofianguy** [comment] 2019-08-08 23:43
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-08-19 19:25
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by vyunikov** [comment] 2019-12-14 15:50
It still doesn't work, event with Electron 7 and Electron 8 beta.
uploadData is never being filled for custom protocols. I can provide more info if needed

**Comment by kamil-kielczewski** [comment] 2020-01-16 19:23
@sofianguy problem still exist - `uploadData` is `undefined` - please reopen this bug

**Comment by DeltaF1** [comment] 2020-08-04 20:19
@sofianguy I am still experiencing this bug on Electron 9.1.0. Can you please reopen this bug?

Platform:
Manjaro Linux 64-bit

**Comment by DeltaF1** [comment] 2020-08-05 06:56
In case more info is needed for re-opening:
PUT requests work fine using the fetch API on custom protocols. The problem seems to only exist for XHR-generated requests on custom protocols. When logging the request in the protocol handler there is no body/uploadData at all present in the request from XHR.

**Comment by kamil-kielczewski** [comment] 2020-08-05 07:27
@Gozala Can you open this issue (because problem still exists) ?

**Comment by Gozala** [comment] 2020-08-05 16:18
> @Gozala Can you open this issue (because problem still exists) ?

I can't only members of the repo can, which I am not.

**Comment by kamil-kielczewski** [comment] 2020-08-05 16:28
@MarshallOfSound can you open this issue?

**Comment by kamil-kielczewski** [comment] 2021-01-21 22:26
@codebytere can you open this issue?

**Comment by 6XGate** [comment] 2021-02-20 16:08
@MarshallOfSound or @codebytere ; would someone please re-open this issue. It still persists in Electron 11.3.0. I have tested this with axios and direct XMLHttpRequest instances.

For anyone who needs some form of custom protocol communication with POST, PUT, or other methods that need a body. The standard `fetch` API still works just fine.

**Comment by jakuski** [comment] 2021-07-16 14:55
Still an issue on 13.1.7

**Comment by nornagon** [comment] 2021-07-19 23:14
Here is an updated and slightly simplified Fiddle version of @Gozala's repro: https://gist.github.com/aa94ddd8980d68a392c35873dfd7e2c5

**Comment by nornagon** [comment] 2021-07-20 00:04
It turns out this is hard-coded in blink.

1. blink checks `AreMethodAndURLValidForSend` in `send`: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/xmlhttprequest/xml_http_request.cc;l=838;drc=9fc2e23338b14a5e9f430d7c8552093c5b8d8d32
2. `AreMethodAndURLValidForSend` checks `KURL::ProtocolIsInHTTPFamily`: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/xmlhttprequest/xml_http_request.cc;l=802;drc=347c808b0a69e3a5d0e1d30003c91e996ea56f59
3. `KURL::ProtocolIsInHTTPFamily` will only return true if the protocol is `http` or `https`: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/weborigin/kurl.cc;l=952-960;drc=347c808b0a69e3a5d0e1d30003c91e996ea56f59

I did a little research and it has been this way since blink was WebKit was KHTML: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/xmlhttprequest/xml_http_request.cc;l=243;drc=7ea4ebf0bee3d58001fa2b7f7774262701f8e6be

I'm not sure if it is worth us floating a patch here, but I've thrown something up upstream. Let's see what Chromium has to say: https://chromium-review.googlesource.com/c/chromium/src/+/3040243

**Comment by nornagon** [comment] 2021-07-22 01:58
My patch landed in upstream: https://chromium-review.googlesource.com/c/chromium/src/+/3040243 so I'm going to close this out. Should be fixed the next time we roll Chromium, and will go out in Electron 15. Wouldn't be too hard to backport if we need to.

**Closed by nornagon** 2021-07-22 01:58 UTC
Labels: 13-x-y, 2-0-x, blocked/upstream ❌, bug :beetle:, has-repro-gist, status/confirmed
