### ISSUE TITLE
[Bug]: The `focus` method of a Window object doesn't bring the window to front

### ISSUE THREAD

**Issue by XanderEmu** [electron/electron#29016] opened 2021-05-05 15:26 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.6

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 2004

### What arch are you using?

x64

### Expected Behavior

- The app opens a child window using `window.open` method (`nativeWindowOpen` is set to `true`).
- User clicks on a button that is supposed to bring the previously opened window to front. The app calls `win.focus()` on a said child window object.
- The child window should appear above the main window.

### Actual Behavior

Nothing happens when `win.focus()` is called.

### Additional Information

When running (almost) the same code as a web app (in Chrome), the focus method brings the window to the top.

There was a similar issue reported a few years back:
https://github.com/electron/electron/issues/2867

**Comment by pushkin-** [comment] 2021-05-05 15:30
If I'm not mistaken, the linked issue was more about calling `BrowserWindow::focus()` (on the Electron side), not `win.focus()` on the browser side. This looks like a dupe of [this](https://github.com/electron/electron/issues/25578)

**Comment by nornagon** [comment] 2021-05-05 18:37
Duplicate of #25578

**Closed by nornagon** 2021-05-05 18:37 UTC
Labels: bug :beetle:
