### ISSUE TITLE
Menu (Linux) - setting application menu multiple times causes lost items or duplicates

### ISSUE THREAD

**Issue by bpasero** [electron/electron#2440] opened 2015-08-06 19:18 UTC
We are seeing an issue in VS Code on Ubuntu 15 where top level menu items show up duplicate or are even missing. This seems to be caused by updating the menu via setApplicationMenu() after it has already been set. Since that is the only way to update a menu, we need to do it that way (I guess Atom has to too).

We are sitting on Electron 0.28.3. Have you guys heard of this issue before?

**Comment by zcbenz** [comment] 2015-08-24 03:27
I don't think I saw similar problems in Atom, but it might be a bug since the application menu bar implementation on Ubuntu Unity is completely different from other operating systems. Can you provide some code snippets that can reproduce this problem?

**Comment by bpasero** [comment] 2015-08-24 06:22
I can try but basically what we do is to set a menu structure and update it frequently (by resetting the entire structure because there is no other way).

Atom might not show this issue because it sits on a very old electron version :)

**Comment by zcbenz** [comment] 2016-05-06 07:49
Didn't receive similar reports after this, and we really need a reproducible case to be able to look into it. So I'm closing this.

**Closed by zcbenz** 2016-05-06 07:49 UTC
Labels: bug, linux, menu
