### ISSUE TITLE
[Bug]: shortcut Ctrl + R won't refresh the app anymore in the  electron version 17

### ISSUE THREAD

**Issue by pejman1** [electron/electron#32730] opened 2022-02-03 15:53 UTC
shortcut Ctrl + R won't refresh the app anymore in the  electron version 17

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

16.0.8

### Expected Behavior

shortcut Ctrl + R won't refresh the app anymore in the new version of the electron 

### Actual Behavior

Ctrl + R should refresh the app

**Comment by miniak** [comment] 2022-02-04 04:43
Please add a title to the issue

**Comment by nornagon** [comment] 2022-02-04 19:40
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by nornagon** [comment] 2022-02-04 19:41
NB, I can't reproduce this on Windows with the following Fiddle repro: https://gist.github.com/82ce4d1683e806ddff1970d18b60177a. Ctrl+R seems to work fine.

**Comment by pejman1** [comment] 2022-02-05 06:31
> NB, I can't reproduce this on Windows with the following Fiddle repro: https://gist.github.com/82ce4d1683e806ddff1970d18b60177a. Ctrl+R seems to work fine.

it happens in my application. when I upgrade it to version 17, Ctrl+R won't work anymore. unfortunately I can not share my source code. I don't know what makes this problem in the new version of electron to reproduce it

**Comment by MarshallOfSound** [comment] 2022-02-05 08:52
> unfortunately I can not share my source code. I don't know what makes this problem in the new version of electron to reproduce it

Without more information or a consistent repro there isn't anything we can do here.  Given the basic case failed to repro I'm going to close this out, if you repro it in the future please @ mention me with the repro and we can re-open this

**Closed by MarshallOfSound** 2022-02-05 08:52 UTC
Labels: bug :beetle:, blocked/need-repro
