### ISSUE TITLE
Typing lag on some websites

### ISSUE THREAD

**Issue by MehediH** [electron/electron#7633] opened 2016-10-15 08:05 UTC
* Electron version: 1.4.3
* Operating system: Windows 10 1607

On Electron 1.4.3, tweetdeck.twitter.com has a very weird typing lag. This has been present since 1.0.x, but I wasn't able to find any help regarding this issue. The latest version of Google Chrome and Chromium works fine on tweetdeck.twitter.com, but the lag only seems to be affecting Electron 1.4.3.

I built a sample app using Electron Quick Start, and it is lagging there as well:

![2016-10-15_09-03-14](https://cloud.githubusercontent.com/assets/10274434/19408485/3b150cae-92b6-11e6-947e-b5148aa33bde.gif)

**Comment by MarshallOfSound** [comment] 2016-10-15 08:08
I'm going to have to close this out as a duplicate of #6759

Lack of updates / progress on one issue is not a good reason to open a new one.  👍

**Closed by MarshallOfSound** 2016-10-15 08:08 UTC

**Comment by MehediH** [comment] 2016-10-15 08:10
@MarshallOfSound I did try to get a fix on the initial thread but there hasn't been any update on that for a while now. Are you  able to repro the issue?

**Comment by MarshallOfSound** [comment] 2016-10-15 08:27
@MehediH To be honest, I've never tried, if I get time I sometimes go through open issues and try to repro and fix.  But I've never tried yours

**Comment by MarshallOfSound** [comment] 2016-10-15 08:34
@MehediH And FWIW I just tried just now, and I get no input lag at all.  Even when stupidly spamming my keyboard 👍 

Possibly machine specific?

**Comment by MehediH** [comment] 2016-10-16 08:29
@MarshallOfSound It isn't machine specific, several other users have reported the same issue and it wasn't happening on my machine up until recently. :/

**Comment by Nekromancer** [comment] 2016-10-20 13:06
Got same problem on 2 applications (GitKraken and Slack) only on work laptop. On my private desktop everything works just fine.

**Comment by MehediH** [comment] 2016-10-20 13:09
@Nekromancer Good to know, thought it was only affecting TweetDeck. Hopefully the Electron devs will try to get it sorted now :)

**Comment by Nekromancer** [comment] 2016-10-20 13:21
It seems they're trying to fix it for some time, no luck so far :/
