### ISSUE TITLE
[Bug]: require is not defined

### ISSUE THREAD

**Issue by lijinzedev** [electron/electron#31569] opened 2021-10-25 10:25 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Screenshots
![image](https://user-images.githubusercontent.com/41108332/138679241-2564fbe3-93b3-433e-8a90-3384ded42c17.png)
![Uploading image.png…]()

I'm using Vue and no matter how I set it up it's going to get an error, okay

### Actual Behavior

require is not defined

**Comment by codebytere** [comment] 2021-11-02 13:57
Closing as intended behavior.

**Closed by codebytere** 2021-11-02 13:57 UTC
Labels: platform/windows, bug :beetle:, blocked/need-repro, 15-x-y
