### ISSUE TITLE
[Bug]: context-menu for webviews in renderer broken by #30831

### ISSUE THREAD

**Issue by Kilian** [electron/electron#31276] opened 2021-10-04 15:34 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.1.0

### What operating system are you using?

Ubuntu

### Operating System Version

ubuntu 18.04

### What arch are you using?

x64

### Last Known Working Electron version

15.0.0

### Expected Behavior

When invoking a context-menu event on the webcontents of a webview in the renderer process, the function works and does not give an error.

### Actual Behavior

Since #30831 `frame` is sent along with the params, but `frame` is not serializable so can not cross from the main process to the renderer process. This results in an error being shown to the user.

### Additional Information

I'm aware that getting the webContents in the renderer process (using @electron/remote) is an antipattern. Still, I feel this is something we should not break in a minor release.

**Comment by erickzhao** [comment] 2021-10-04 17:06
Might be duplicate of #31249?

**Comment by miniak** [comment] 2021-10-04 17:42
It's a duplicate of #31249. #31259 fixes that.

**Closed** 2021-10-04 17:42 UTC
Labels: bug :beetle:, bug/regression :leftwards_arrow_with_hook:, component/webcontents, 15-x-y, 16-x-y
