### ISSUE TITLE
Widevine CDM no longer works on v4

### ISSUE THREAD

**Issue by steverandy** [electron/electron#16285] opened 2019-01-05 04:18 UTC
* Output of `node_modules/.bin/electron --version`: v4.0.1
* Operating System (Platform and Version): macOS 10.14.1
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.0.14

**Expected Behavior**
Widevine CDM should load and webview should be able to play DRM content.

**Actual behavior**
Widevine CDM seems not loaded and getting error `Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()` on the page.

**To Reproduce**

**Widevine CDM works on Electron v3**
1. Clone this repo: https://github.com/steverandy/electron-quick-start/
2. Checkout branch v3-cdm to test Electron v3
3. Run npm install and npm start
4. Wait for page to load and click on "Load"
5. DRM enabled stream should play

**Widevine CDM does not work on Electron v4**
1. Clone this repo: https://github.com/steverandy/electron-quick-start/
2. Checkout branch v4-cdm to test Electron v4
3. Run npm install and npm start
4. Wait for page to load and click on "Load"
5. Video will not play and will get an error Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()

**Screenshots**
![screenshot 2019-01-05 at 12 17 43 pm](https://user-images.githubusercontent.com/525332/50720230-ec531800-10e3-11e9-8a84-ad4a3c5ef029.png)

**Comment by javiergarmon** [comment] 2019-01-06 15:06
I confirm this also happens in Electron 4.0.0 for Windows 10 (x64)

**Comment by javiergarmon** [comment] 2019-01-08 09:21
Please, add `platform/windows` as label, this also happens there

**Comment by steverandy** [comment] 2019-02-04 03:18
@deepak1556 I previously reported similar issue for electron v3, which had been fixed on v3. But now having similar issue on v4. Is there a plan to fix this issue? Thanks.

**Comment by steverandy** [comment] 2019-03-23 15:05
I was able to make the Widevine plugin works on Electron v4.0.1 by updating the CDM plugin to `v4.10.1303.2` and changing the `widevine-cdm-path` to the parent directory instead of the binary file itself. I've updated the sample project for reference.

However the same configuration does not work on Electron v5.0.0-beta.6

**Comment by oscartbeaumont** [comment] 2019-04-19 10:30
@steverandy what OS did you get that working with? I can get Widevine loaded and working on my Mac but neither Windows or Linux are working with v4.

**Comment by steverandy** [comment] 2019-04-19 14:57
macOS 10.14. I have not tried on Windows or Linux.

**Comment by Scrumplex** [comment] 2019-04-27 17:32
[We are working on getting modern versions of Widevine CDM working with Electron 5.0.0](https://github.com/oscartbeaumont/ElectronPlayer/issues/20). Asa @oscartbeaumont already reported it somehow works on macOS using [this](https://github.com/oscartbeaumont-ext/electron-widevinecdm-dev) node module. Is there any way to get debug info with this process? It seems like electron is not willing to show any error messages.

**Comment by oscartbeaumont** [comment] 2019-06-13 14:23
Can this issues tag be changed to all platforms as it is a problem for all platforms (minus Mac which looks to be fixed)? Is there any idea what is causing it on Linux and Windows cause I really need to try and fix it. My project [ElectronPlayer](https://github.com/oscartbeaumont/ElectronPlayer) is currently unable to play Netflix due to the old browser version of Electron which is required for Widevine to work. This means my application is basically useless (at least to me cause I only use it for Netflix). I am willing to try and fix it if someone points me in the correct direction in the Electron codebase. @steverandy do you have any ideas for fixing it on Linux or Windows? I tried pointing the path at the directory and the individual Widevine files as well as trying many versions and versions from different download sources.

**Comment by electron-triage** [comment] 2020-02-19 21:26
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:36
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:36 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/macOS
