### ISSUE TITLE
macOS: dock menu can get into broken state

### ISSUE THREAD

**Issue by bpasero** [electron/electron#11159] opened 2017-11-18 10:54 UTC
* Electron version: 1.7.9
* Operating system: macOS 10.12.6

### Expected behavior

The dock menu of the application separates actions and recent entries.

### Actual behavior

There are entries mixed.

### How to reproduce

See this:

![image](https://user-images.githubusercontent.com/900690/32979525-f59dd440-cc56-11e7-8f06-218c489ce97b.png)

We are using a combination of `app.clearRecentDocuments` and `app.addRecentDocument` whenever a file or folder is opened with VS Code. We always first clear all recent documents and then add all the ones in MRU order. 

What further information can I provide to find out more?

**Comment by sethlu** [comment] 2017-11-21 07:34
@bpasero Since the recent documents menu is only updated in `historyMainService.ts`, can you provide a sample `mru = this.getRecentlyOpened()` that causes the menu to fail? I can help debug if it's something fixable within Electron's scope.

**Comment by bpasero** [comment] 2017-11-22 09:15
@sethlu I can reproduce by the following recent documents:

```js
electron.app.clearRecentDocuments();
electron.app.addRecentDocument('/Users/bpasero/Development/vscode.code-workspace');
electron.app.addRecentDocument('/Users/bpasero/Desktop/test-js');
electron.app.addRecentDocument('/Users/bpasero/Development/monaco/src/typings/electron.d.ts')
electron.app.addRecentDocument('/Users/bpasero/Development/bpaser-chokidar');
electron.app.addRecentDocument('/Users/bpasero/Development/bpaser-fsevents');
electron.app.addRecentDocument('/Users/bpasero/Development/skype/patch-electron.code-workspace');
```

Results in:

![image](https://user-images.githubusercontent.com/900690/33119065-1d86e93c-cf6e-11e7-9c2d-44216d961743.png)

**Comment by sethlu** [comment] 2017-11-22 09:17
@bpasero Great! 👍 Testing it now...

**Comment by sethlu** [comment] 2017-11-22 09:56
@bpasero From my testing with macOS 10.13.2 an overflowing of menu items seems working fine. What's your settings in "System Preferences" for recent items? 😕 It appears that `bpaser-chokidar` and `bpaser-fsevents` are overridden by the separator and the "Hello World!" in the screenshot...

![screenshot 2017-11-22 01 55 13](https://user-images.githubusercontent.com/3168941/33120889-374b86ca-cf28-11e7-88be-f86b17005208.png)

**Comment by bpasero** [comment] 2017-11-22 09:58
@sethlu 

![image](https://user-images.githubusercontent.com/900690/33121068-1fa72d70-cf74-11e7-9587-c3961ba9c2d5.png)

**Comment by sethlu** [comment] 2017-11-22 10:14
So far I could come up with 2 tests:

1. If it's something happening on the OS level, the Atom editor should experience a similar issue
1. If it's to do with VSCode specifically, probably commenting out [vs/code/electron-main/menus.ts#L309-L316](https://github.com/Microsoft/vscode/blob/9932a4981f4c463dcdafd23bf519b83680410ed5/src/vs/code/electron-main/menus.ts#L309-L316) would fix the broken layout?

**Comment by bpasero** [comment] 2017-11-23 06:20
@sethlu how is this issue related to VS Code, I can reproduce it with the code I provided in a standalone electron application?

**Comment by sethlu** [comment] 2017-11-23 19:14
Since Electron only offers a thin layer on top of the actual system API, I doubt if this is an issue with macOS itself. 😬 There was an app that I was using yesterday (OmniOutliner, non-Electron-based app) and it’s experiencing a same issue.

**Comment by sethlu** [comment] 2017-11-24 01:48
Mhm I’m finding difficulty reproducing the failing case. I'm wondering whether the recent document menu items are out of the scope of Electron’s layer (not set with `NSApplication`’s `dockMenu`) since they are managed with `addRecentDocument`/`clearRecentDocuments`. There seems to be also quite a short of documentation on the handling of menu model and how the dock menu we set is drawn in interference with the automatically populated items.

There are two tests whose results I’m interested in investigating however:

1. If we clear the recent documents first and afterwards add each link at an one-second interval, will the issue still occur?
1. If we do not clear the recent documents but directly add all the recent documents (since repeating entries are accepted and managed by AppKit), will the menu items still overflow?

**Comment by bpasero** [comment] 2017-11-24 10:00
@sethlu I can still reproduce when I delay the addition of recent documents by 1s each.

**Comment by sethlu** [comment] 2017-11-24 19:36
@bpasero I think this may be an issue related to macOS rather than Electron... Can you provide a screenshot of the final result? Also did you leave the dock menu as default as well?

**Comment by bpasero** [comment] 2017-11-25 07:05
@sethlu screenshot is in https://github.com/electron/electron/issues/11159#issuecomment-346289562

> Also did you leave the dock menu as default as well?

Yes, I only added recent documents

**Comment by sethlu** [comment] 2017-11-30 10:11
@bpasero From another native macOS app:

<img width="192" alt="screen shot 2017-11-30 at 2 08 41 am" src="https://user-images.githubusercontent.com/3168941/33425498-bc3c57d2-d573-11e7-936d-00b55292aadb.png">

**Comment by bpasero** [comment] 2017-11-30 10:16
Looks less broken to me, but still a bit weird....

**Comment by hparadiz** [comment] 2018-08-14 15:03
I was able to get rid of the bad entries!

`killall Dock` forced a reset of the Dock process which cleared out the fake "open" files from my dock menu.

https://www.quora.com/What-is-the-best-way-to-delete-a-recently-opened-file-history-on-a-Mac

**Comment by sofianguy** [comment] 2019-01-08 18:11
@bpasero is this still an issue in version 2.0.x or later?

**Comment by bpasero** [comment] 2019-01-09 07:13
@sofianguy yes

**Comment by bpasero** [comment] 2019-03-11 14:34
I finally figured out what is triggering it: if you add an entry to the dock that does not exist on disk, the list gets into this broken state!

**Comment by bpasero** [comment] 2019-03-11 14:46
Related discussion: https://github.com/Microsoft/vscode/issues/57272#issuecomment-470554699

**Comment by clshortfuse** [comment] 2019-03-11 15:26
It could help to add support for:

https://developer.apple.com/documentation/appkit/nsdocumentcontroller/1514976-recentdocumenturls

If we can call `recentdocumenturls`, then we can do a cross-comparison of what we expect to be in the dock and what's actually in the dock. Then we can tell the app to clear and recreate the dock entries if there's a mismatch. Unfortunately, it doesn't seem like the Mac OS X API lets us manipulate entries one-by-one, but it's better then nothing.

**Comment by sofianguy** [comment] 2019-08-09 03:41
@bpasero is this bug still happening on version 4.2.x or later?

**Comment by bpasero** [comment] 2019-08-09 05:18
Yeah, nothing changed. The workaround for VSCode is to make sure that every entry in the dock we add exists on disk.

**Comment by electron-triage** [comment] 2020-02-19 23:39
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-03-06 19:54
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-03-06 19:54 UTC
Labels: 2-0-x, 4-2-x, blocked/need-info ❌, bug :beetle:, platform/macOS, version/1.7.x
