### ISSUE TITLE
How does Electron capture shortcuts and get the target path

### ISSUE THREAD

**Issue by cnblogco** [electron/electron#30060] opened 2021-07-09 02:35 UTC
我想通过快捷方式来获取目标路径的参数，是否有详细的API ，或者代码，想通过参数来打开软件跳转到不同的页面，请问，大大们是否有相关的质料。

I want to get the parameters of the target path through the shortcut. Do you have a detailed API or code to open the software to jump to different pages through the parameters? Could you please tell me if you have the relevant materials?

Is there a demo？

**Comment by cnblogco** [comment] 2021-07-09 02:36
![40RF_I5IR3IGIAUPY4KERJA](https://user-images.githubusercontent.com/53510577/125015180-8b846c00-e0a1-11eb-83e0-c5b93358109d.png)

**Comment by nornagon** [comment] 2021-07-09 19:22
Duplicate of #30046

**Closed by nornagon** 2021-07-09 19:22 UTC
