### ISSUE TITLE
[Bug]: save dialog adds weird suffix to the path

### ISSUE THREAD

**Issue by bpasero** [electron/electron#44192] opened 2024-10-11 08:53 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.2.0

### What operating system(s) are you using?

macOS

### Operating System Version

15.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

The file name I enter into a save dialog is returned a such.

### Actual Behavior

When entering a file name such as `Untitled.foo`, I get back `Untitled.foo.f`.

### Testcase Gist URL

https://gist.github.com/rssowlreader/95a1441849e5452ce4502bd1d500c949

**Comment by bpasero** [comment] 2024-10-11 08:54
@codebytere could you take a look? Here is a video of what I get:

![Image](https://github.com/user-attachments/assets/348504a8-1f8d-4585-ae3d-583b651d7d4a)

**Comment by codebytere** [comment] 2024-10-11 09:44
@bpasero just tested on macOS 14.6.1 using Electron v32.2.0 and cannot reproduce: 

![Image](https://github.com/user-attachments/assets/5ff55fd6-799b-4a79-80d7-d67c54e9d34d)

**Comment by bpasero** [comment] 2024-10-11 09:46
Yeah it very likely is, that was my thought as well.

**Comment by deepak1556** [comment] 2024-10-11 09:58
Unable to repro in Chrome with https://googlechromelabs.github.io/text-editor/ that uses the `showSaveFilePicker` API on macOS 15. Also upstream it doesn't seem like upstream have any recent changes to their file dialog implementation for macOS 15 https://source.chromium.org/chromium/chromium/src/+/main:components/remote_cocoa/app_shim/select_file_dialog_bridge.mm, so maybe an issue with our API usage on sequoia.

**Comment by codebytere** [comment] 2024-10-11 11:59
@bpasero confirmed on Sequoia! I just updated to check and will continue to investigate.

**Comment by codebytere** [comment] 2024-10-11 18:34
@deepak1556 i actually think we _can_ repro this in Chromium. If I go https://googlechromelabs.github.io/text-editor, and save a default file with no edits, and then change the filename to `Untitled.foo` from `Untitled.txt`, I see this:

![Image](https://github.com/user-attachments/assets/e905bc1d-cb2f-42ca-874e-ec6a38deb315)

Indicating that the `.f` suffix has been unexpectedly appended just as @bpasero showed above!

**Comment by deepak1556** [comment] 2024-10-12 00:10
> then change the filename to Untitled.foo from Untitled.txt, I see this:

Ah nice catch! I only looked at the extension that was displayed, so have looked at the extension that was saved.

> Look like a bug in Sequoia

Wonder if there is a tracking bug, if not we should file one https://developer.apple.com/bug-reporting/

**Comment by codebytere** [comment] 2024-10-13 17:55
@bpasero @deepak1556 good news: this seems to be fixed in macOS Sequoia 15.1 Beta (24B5070a). Is there any other resolution that you'd like to see on our end? Otherwise i think we may be good to close this out :)

**Comment by bpasero** [comment] 2024-10-13 17:56
Cool sounds good to close then 👍

**Closed** 2024-10-13 17:59 UTC
Labels: platform/macOS, bug :beetle:, status/confirmed, has-repro-gist, 32-x-y

**Comment by bpasero** [comment] 2024-10-30 08:06
@codebytere this still reproduces in macOS 15.1 with the following Gist: https://gist.github.com/rssowlreader/8fe61ec20a5d2d320e6d0fa800c8a65d

**Comment by codebytere** [comment] 2024-10-30 11:12
@bpasero unfortunately there's still nothing we can do on our end about this - I suggest filing this both with https://developer.apple.com/bug-reporting/ and also potentially with Chromium since they're impacted as well cc @deepak1556
