### ISSUE TITLE
BrowserWindow can not dock after setting setResizable

### ISSUE THREAD

**Issue by PerfectionCSGO** [electron/electron#11568] opened 2018-01-04 15:42 UTC
* Electron version: 1.7.10 (But seems to occur from 1.4.14 and up. Works below.)
* Operating system: Windows 10

### Expected behavior

The browserWindow should be dockable to the edges of the screen. (Windows + LEFT/RIGHT or by dragging.) And resizable aswell as maximizable.

### Actual behavior

The browserWindow can no longer be maximized or docked.
However, it can be resized.

### How to reproduce

```
# Clone this repository
git clone https://github.com/PerfectionCSGO/electron-dwm-issue
# Go into the repository
cd electron-quick-start
# Install dependencies
npm install
# Run the app
npm start
# Change the values around of setResizable and resizable to fiddle with the behavior.
```

P.S. Sometimes when maximizing there's a spaced border on the sides and a white border above the BrowserWindow that I can't get rid of. It tends to happen when double clicking on the draggable Region that I've marked in grey but never when regularly maximizing.

**Comment by PerfectionCSGO** [comment] 2018-01-31 14:35
Poking for activity..

**Comment by sanchezpablo** [comment] 2018-07-11 07:17
Also with this settings:

  win = new BrowserWindow({
    x: xPos,
    y: yPos,
    webPreferences: { experimentalFeatures: true, webSecurity: false },
    width: WINDOW_WIDTH,
    height: WINDOW_HEIGHT,
    minWidth: WINDOW_WIDTH,
    minHeight: WINDOW_HEIGHT,
    autoHideMenuBar: true,
    frame: false,
    resizable: true,
    thickFrame: false,
    hasShadow: true,
    icon: ICON_PATH
  });

the snap is not working.

The problem is with thikFrame: false, if this is not set (default is true) then the snap is working but when maximizing/minimizing every second time there is a gap between top window border and top screen border... (bug?)

Any help appreciated. Thanks!

**Comment by Astrych** [comment] 2018-07-11 13:52
@sanchezpablo [Try this for that gap bug.](https://github.com/electron/electron/issues/12971#issuecomment-403956396)

**Comment by sofianguy** [comment] 2019-01-07 23:08
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:24
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by abettadapur** [comment] 2019-06-28 21:50
@sofianguy I am on electron 5 and I still see this behavior. We have a window that is initially not resizeable, but we call setResizeable(true) later. I cannot snap the window in Windows

Can we reopen this issue?

**Comment by electron-triage** [comment] 2020-02-19 20:22
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:20
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:20 UTC
Labels: 5-0-x, blocked/need-info ❌, bug :beetle:, platform/windows, version/1.7.x

**Comment by dontpanic5** [comment] 2021-04-05 11:32
Hello, I am still seeing this issue on Electron v12. I recently added transparency to my window and it now cannot use the Windows aero snap.

**Comment by sha-N** [comment] 2021-06-17 06:52
same for version 13

**Comment by rmill777** [comment] 2021-09-28 04:08
same for version 15
