### ISSUE TITLE
Could not call remote function 'showErrorBox' on Electron Version 1.2.5

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [electron/electron#6793] opened 2016-08-10 14:13 UTC
* Electron version: 1.2.5 x32
* Operating system: Windows

I may be running on a Remote bug here, but I'm not sure, since I'm new on Electron. I have an application running where I want to show an Error Dialog. Therefore I'm using [Dialogs](https://github.com/electron/electron/blob/master/docs/api/dialog.md).

My code, "behaviour.js" is pretty simple and uses remote:

```
const {app} = require('electron').remote.app;
const {dialog} = require('electron').remote;

console.log(dialog);
dialog.showErrorBox("Error Title!", "Thats an error :D");
```

That leads me to an error related to the Remote:
![image](https://cloud.githubusercontent.com/assets/293596/17556636/82488f74-5eea-11e6-8a84-c3dc7504570f.png)

I also tried:

> const {dialog} = require('electron').remote.dialog;
> const dialog = require('electron').remote;
> const dialog = require('electron').remote.dialog;

But, from my point of view, I'm doing it correctly since it's not returning a null pointer and the Object itself has all the properties that are expected. But I'm unable to check the functions itself because of Remote:

![image](https://cloud.githubusercontent.com/assets/293596/17556813/27c9fbcc-5eeb-11e6-9f73-e66826992a82.png)

Any help would be appreciated.
Thanks in advance!

**Comment by kevinsawicki** [comment] 2016-08-10 16:44
Are you able to reproduce this on `1.3.2`? I'm having trouble reproducing it by calling the following from the Console tab of the dev tools.

```js
require("electron").remote.dialog.showErrorBox("Error Title!", "Thats an error :D")
```

**Comment by Marcelo-Petrucelli** [comment] 2016-08-11 13:30
Hello @kevinsawicki 

I got the same error, in the same way, using: v1.3.3.
All screenshots also remain the same.

I'll explain again what I'm doing. I'm running on Windows, have a app that I want to run and, inside my app I have a behaviour.js (which is not the main.js from electron) which I want to create a Error Message Box. Therefore, I'm doing things like:

```
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const app = require('electron').remote.app;
const cp = require('child_process');
```
and wanted to use:

`const dialog = require('electron').remote;`

Any help would be appreciated. Thanks in advance!

**Comment by kevinsawicki** [comment] 2016-08-11 16:18
@Marcelo-Petrucelli would it be possible for your to provide a full sample app that reproduces the issue? I was unable to reproduce it following your initial instructions.

**Comment by Marcelo-Petrucelli** [comment] 2016-08-11 16:52
Unfortunately I can't...

I'll provide a sample that has the same issue. **A quick reminder, Currently I'm just testing on windows.

File Tree:
* index.html
* main.js
* package.json
* pepflashplayer32_22_0_0_192.dll
* js (folder)
  * behaviour.js

Files:

main.js
```
const path = require('path');
const fs = require('fs');
const {app, BrowserWindow} = require('electron');  // Module to control application life and create native browser window.

app.commandLine.appendSwitch('--enable-npapi');

//Adds Pepper's Flash Plugin
var ppapi_flash_path = null;
if(process.platform  == 'win32')
{
    ppapi_flash_path = path.join(__dirname, 'pepflashplayer32_22_0_0_192.dll');
}
/*else if (process.platform == 'linux')
{
    ppapi_flash_path = path.join(__dirname, 'libpepflashplayer.so');
}
else if (process.platform == 'darwin')
{
    ppapi_flash_path = path.join(__dirname, 'PepperFlashPlayer.plugin');
}*/

app.commandLine.appendSwitch('ppapi-flash-path', ppapi_flash_path);
app.commandLine.appendSwitch('ppapi-flash-version', '22.0.0.192');

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
let mainWindow = null
app.on('ready', function() {
    var size = require('electron').screen.getPrimaryDisplay().workAreaSize;
    // Create the browser window.
    mainWindow = new BrowserWindow(
    {
		width: size.width,
		height: size.height,
		webPreferences: {
			plugins: true,
			webgl: true,
			webSecurity: false
        },
        minWidth: 800,
        minHeight: 600,
		frame: false,
		fullscreen: true
    });
    mainWindow.setAlwaysOnTop(true);
    mainWindow.loadURL('file://' + __dirname + '/index.html');

    // Emitted when the window is closed.
    mainWindow.on('closed', function()
    {
        mainWindow = null;
    });
});

// Quit when all windows are closed.
app.on('window-all-closed', function()
{
    // On OS X it is common for applications and their menu bar
    // to stay active until the user quits explicitly with Cmd + Q
    if (process.platform != 'darwin')
    {
        app.quit();
    }
});
```

index.html
```
<!DOCTYPE html>
<html>
<head>
	<title>Hello World Test</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<script type="text/javascript" src="js/behavior.js"></script>
</head>
<body>
	Hello World
</body>
</html>
```

behaviour.js
```
const njspath = require('path');
const remote = require('electron').remote;
const app = remote.app;
const dialog = remote.dialog;

console.log(dialog);

if(process.platform  == 'win32'){
	try {
		if (true){
			throw new Error('Thats an error message.');
		}
	} catch(error) {
		alert(error.message);
		dialog.showErrorBox("Error Title!", error);
	}
}
else if (process.platform == 'linux'){
	alert('Not implemented yet!');
}
```

**Comment by kevinsawicki** [comment] 2016-08-11 17:01
> dialog.showErrorBox("Error Title!", error);

I think this line is causing issues, the second parameter must be a String, not an Error, can you try if `error.message` works?

**Comment by Marcelo-Petrucelli** [comment] 2016-08-11 17:47
Damn it, that was such a simple mistake of mine! It was indeed that.
Thanks @kevinsawicki, I'm sorry for waste your time with such a dumb mistake.

This Issue can be closed. Sorry about it =(

**Comment by kevinsawicki** [comment] 2016-08-11 20:15
No worries, the error message was missing the type of the parameter which would have helped in this case, the next release will have this fixed via https://github.com/zcbenz/native-mate/pull/5

It would instead say something like

> Error processing argument at index 1, conversion failure from #<Error>

Instead of

> Error processing argument at index 1, conversion failure from

**Closed by kevinsawicki** 2016-08-11 20:15 UTC
Labels: more-information-needed
