### ISSUE TITLE
[Bug]: Unexpected `UnhandledPromiseRejectionWarning` errors when running heavy operations in the `main process`

### ISSUE THREAD

**Issue by PoiraudVictor** [electron/electron#28691] opened 2021-04-16 12:18 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.1.3

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur v11.1.0

### What arch are you using?

x64

### Expected Behavior

I am running heavy synchronous and I/O operations inside the `main process`, it should not raise any unknown `UnhandledPromiseRejectionWarning` errors, generated by electron itself.

### Actual Behavior

Everything works perfectly fine, exept the fact that when I/O operations are run, electron generates `UnhandledPromiseRegectionWarning` errors. Please, find the mentioned errors hereinafter :  

```JSON
(node:24247) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:87:1544)
    at electron/js2c/renderer_init.js:115:431
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:99:346)
    at EventEmitter.emit (events.js:310:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:818)
(node:24247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
Successfully uploaded 10 files to our cloud
(node:24247) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/renderer_init.js:87:1544)
    at electron/js2c/renderer_init.js:115:431
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:99:346)
    at EventEmitter.emit (events.js:310:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:818)
```

The errors are even thrown by my `api`, while there should not be any connection between my app and my api beside the I/O operation I have explicitly defined in my code. Please find the `api` error log hereinafter : 

```JSON
[1618567551418] ERROR	 (15948 on MacBook-Pro-de-Victor.local): 528b32fbdfb88b62f29c7c9da5a2b7fd0a091952b324d6387e14260f1b0440f2 is not authorized to access /electron/js2c/renderer_init.js
    trace.id: "bea144b89c5b02c0ebd1e3ca38fd0e0c"
    transaction.id: "953642929229595c"
[1618567551419] ERROR	 (15948 on MacBook-Pro-de-Victor.local): 528b32fbdfb88b62f29c7c9da5a2b7fd0a091952b324d6387e14260f1b0440f2 is not authorized to access /events.js
    trace.id: "96e2a94c38b87c59d20865666d925e96"
    transaction.id: "b000b4e706a7654a"
```

Please, here follows my app's dependecies : 

```JSON
"dependencies": {
    "@types/node": "14.14.0",
    "@types/react": "16.9.51",
    "@types/webpack-env": "1.15.3",
    "at-least-node": "1.0.0",
    "axios": "0.21.1",
    "builder-util-runtime": "8.7.2",
    "debug": "4.3.0",
    "dotenv": "8.2.0",
    "electron-log": "4.2.4",
    "electron-store": "7.0.1",
    "electron-updater": "4.3.5",
    "follow-redirects": "1.13.3",
    "fs-extra": "9.0.1",
    "getmac": "5.17.0",
    "graceful-fs": "4.2.4",
    "js-yaml": "3.14.0",
    "jsonfile": "6.0.1",
    "lazy-val": "1.0.4",
    "ms": "2.1.2",
    "node-fetch": "2.6.1",
    "prop-types": "15.7.2",
    "query-string": "6.13.5",
    "react": "16.14.0",
    "react-app-rewired": "2.1.6",
    "react-dom": "16.14.0",
    "react-scripts": "3.4.3",
    "semver": "7.3.2",
    "source-map-support": "0.5.19",
    "ts-loader": "8.0.4",
    "typescript": "4.2.3",
    "universalify": "2.0.0",
    "webfontloader": "1.6.28"
  },
  "devDependencies": {
    "@babel/preset-react": "7.10.4",
    "@types/chrome": "0.0.122",
    "@types/firefox-webext-browser": "78.0.1",
    "@types/react-dom": "16.9.8",
    "babel-loader": "8.1.0",
    "babel-preset-react": "6.24.1",
    "electron": "10.1.3",
    "electron-builder": "22.9.1",
    "electron-notarize": "1.0.0",
    "eslint": "6.8.0",
    "npm-run-all": "4.1.5",
    "prettier": "2.1.2",
    "react-app-rewired": "2.1.6",
    "react-test-renderer": "16.13.1"
  },
```

IMPORTANT: these errors only show up when I have a `renderer process` up runing. As well, when I `fork` a `child_process` from the `main process` to run the heavy operations in, regardless of having a `renderer process` up runing or not, the errors does not pop until I re-run operations in the `main process`.

**Comment by Prinzhorn** [comment] 2021-04-16 13:49
Could you create a Electron Fiddle https://github.com/electron/fiddle that reproduces the problem? Can you still reproduce this with a more recent Electron version than 10?

> when I `fork` a `child_process` from the `main process` to run the heavy operations in, regardless of having a `renderer process` up runing or not, the errors does not pop until I re-run operations in the `main process`.

I recommend using a child process or worker thread (that's what I've chosen) for all intensive application logic. Because blocking the main process will also block the renderer processes (https://github.com/electron/electron/blob/da8c35e3b256b4f9ad0c16edfbc2b56748b3a740/docs/tutorial/performance.md#3-blocking-the-main-process). This doesn't fix the underlying bug you've described, but you won't run into it anymore.

> Under no circumstances should you block this process and the UI thread with long-running operations. Blocking the UI thread means that your entire app will freeze until the main process is ready to continue processing.

**Comment by PoiraudVictor** [comment] 2021-04-19 08:48
Hi @Prinzhorn, thanks a lot for your input. Actually, we are upgrading our app to the latest stable version of electron this week, we still have some compliance issues, but asa there're addressed I'll jump back to this thread to tell you if the same errors are persistent. For now, thanks again 😄

**Comment by nornagon** [comment] 2021-07-06 22:39
Closing as this seems to be resolved.

**Closed by nornagon** 2021-07-06 22:39 UTC
Labels: 10-x-y, bug :beetle:, platform/macOS
