### ISSUE TITLE
Command + Shift + / does not open help menu on MacOS

### ISSUE THREAD

**Issue by kinueng** [electron/electron#19048] opened 2019-06-29 17:04 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 3.1.8
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 2.0.12

### Expected Behavior
When using keyboard combination `Command Shift /`, I expected the Help menu to open for the application in the top menu bar.

### Actual Behavior
See Screenshots section for a working example of what visually appears when using `Command Shift /` on Firefox 67.0.4 (64-bit) on MacOS 10.14.5.

### To Reproduce
- Install the latest version of Microsoft Visual Studio Code (vscode)  for Mac https://code.visualstudio.com/Download **or** the latest Spotify Desktop Application for Mac https://www.spotify.com/us/download/other/
- Open vscode **or** Spotify
- Press Command Shift / on the keyboard
- Observe the help menu is not opened
- Edit Jul 1: Slack Desktop App Version 3.4.2 also has the same issue
- Edit Jul 5: The `electron-quick-start` application shows the same issue https://github.com/electron/electron-quick-start#to-use.  At time of testing, the app displayed these versions `We are using Node.js 12.0.0, Chromium 73.0.3683.121, and Electron 5.0.6.`

### Screenshots
![image](https://user-images.githubusercontent.com/31117513/60387158-cf7d1900-9a64-11e9-8705-c723a7533319.png)

### Additional Information
This problem was originally reported by microsoft/vscode#69375 and microsoft/vscode#68604

Here is the 'Command + Shift + /' output from `monitorevents(window, 'keydown')` when using Chrome DevTools
![image](https://user-images.githubusercontent.com/31117513/60724369-d3dd8200-9efb-11e9-83e6-1c67b46cb7d8.png)

`console.log(globalShortcut.isRegistered('Command+Shift+/'))` returns false when added to bottom of `main.js` in the `electron-quick-start` app https://github.com/electron/electron-quick-start/blob/master/main.js

**Comment by kinueng** [comment] 2019-07-08 14:39
Hello,
I have updated the original description with additional debugging information under `To Reproduce` and `Additional Information`.  The findings are mostly me trying to learn how to debug an electron application for the first time.  I hope it helps save you some time.

**Comment by kinueng** [comment] 2020-07-14 15:40
Hello,
This issue belongs to a closed project [3.0.x / 3.1.x](https://github.com/orgs/electron/projects/14#card-23501358) release.  Is this issue still being tracked?  

If you can give some guidance on how to debug this issue further, I can try to see if I can create a fix.

**Comment by esambo** [comment] 2020-07-15 02:34
@kinueng The current versions of Slack 4.7.0 and VS Code 1.46.1 (I don't know about Spotify) still exhibit this behavior on macOS Catalina 10.15.5

**Comment by kinueng** [comment] 2020-09-18 02:56
I suspecting maybe the root cause to why `Shift+Command+/` isn't working is due to `⇧⌘/` is being incorrectly converted to `⌘?` somewhere in Electron.  I came across https://github.com/electron/electron/issues/21790 that made me come to this suspicion.

# Debugging
When I use the following [accelerator](https://www.electronjs.org/docs/api/accelerator) documentation to create a shortcut in the [electron-quick-start](https://github.com/electron/electron-quick-start) project, I noticed `Shift+CommandOrControl+/` and `CommandOrControl+?` behave the same.

```
  globalShortcut.register('Shift+CommandOrControl+/', () => {
    console.log('Pressed')
  })
```

```
  globalShortcut.register('CommandOrControl+?', () => {
    console.log('Pressed')
  })
```

When I `grep` the electron source code for `CommandOrControl` or `CmdOrCtrl`, I don't see any predefined accelerator related to `/` or `?`.  

I noticed this file, [accelerator.patch](https://github.com/electron/electron/blob/master/patches/chromium/accelerator.patch) that makes me think Chromium code needs to be debugged. 

# Workaround
When you change the default "Show Help menu" shortcut (`⇧⌘/`) to custom shortcut (`⌥⇧/`) , the "Show Help menu" starts to work again in Electron based applications.

![image](https://user-images.githubusercontent.com/31117513/93547886-b394ba00-f92b-11ea-917c-1d49a0d3aa12.png)


I tested the workaround on VSCode (details below) on MacOS 10.15.6.
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by clavin** [comment] 2021-02-19 21:48
This was fixed in #27701! With that fix, the help menu opens correctly when using the default keyboard shortcut, <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>/</kbd>.

**Comment by kinueng** [comment] 2021-02-22 15:31
@clavin Thank you so much for getting a fix built!  I cannot wait to start using `Command + Shift + /` again 🎉 .

An off-topic question, what tool did you use to make those diagram pictures in your PR https://github.com/electron/electron/pull/27701#issuecomment-780203318?

**Comment by clavin** [comment] 2021-02-22 20:42
@kinueng No problem! You can test it out in [this latest beta build too](https://github.com/electron/electron/releases/tag/v12.0.0-beta.28)!

For the diagrams I just drafted them up in [Figma](https://figma.com/) since that is what I'm most comfortable with, even though it's not exactly the most robust diagramming tool 😅

**Comment by electron-triage** [comment] 2021-03-08 21:00
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-08 21:00 UTC
Labels: 3-1-x, bug :beetle:, platform/macOS

**Comment by IAkumaI** [comment] 2023-10-19 13:11
Couldn't find where to remove the shortcut in Mac. Thanks :)
