### ISSUE TITLE
Wrong position of flash context menu

### ISSUE THREAD

**Issue by GhostlyDark** [electron/electron#12077] opened 2018-02-28 13:50 UTC
Hello there.

Doing a right click on a flash object opens up a context menu as expected, but the positioning in 2.0.0-beta.1 is wrong. This happens on both 32-bit and 64-bit builds for Windows and also on Ubuntu 64-bit.

The positioning is correct in v1.8.2.

Additional info:
Windows 7 x64
Flash Player: 28.0.0.161

Minimal app for reproducing (win-64bit and linux-64bit):
[wrong-context-menu-position.zip](https://github.com/electron/electron/files/1767276/wrong-context-menu-position.zip)

**Comment by codebytere** [comment] 2018-02-28 18:17
Closing as duplicate of https://github.com/electron/electron/issues/12047

**Closed by codebytere** 2018-02-28 18:17 UTC
