### ISSUE TITLE
[Bug]: Uncaught TypeError: Cannot read properties of undefined (reading 'instance')

### ISSUE THREAD

**Issue by robertpatrick** [electron/electron#32768] opened 2022-02-07 13:29 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterrey 12.1

### What arch are you using?

x64

### Last Known Working Electron version

16.0.8

### Expected Behavior

Application starts up without error.

### Actual Behavior

On startup, I see the following error:

[10770:0207/071932.843529:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read properties of undefined (reading 'instance')", source: devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@7f5320c63197ddacf4c8094154bd0cd63af422b5/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (1)

### Additional Information

Our [application](https://github.com/oracle/weblogic-toolkit-ui) is working fine with Electron 16.0.8.  After upgrading the app to Electron 17.0.0, I am seeing the aforementioned error.  No changes to the app other than the Electron version change.

**Comment by Aaqu** [comment] 2022-02-08 07:37
Same problem I create new project in elecron 17.0.0
macOS 12.2

[6179:0208/081811.249591:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read properties of undefined (reading 'instance')", source: devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@7f5320c63197ddacf4c8094154bd0cd63af422b5/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (1)

**Comment by codebytere** [comment] 2022-02-08 10:44
Duplicate of https://github.com/electron/electron/issues/32702

**Closed by codebytere** 2022-02-08 10:44 UTC
Labels: bug :beetle:

**Comment by projektorius96** [comment] 2022-02-09 21:21
Exact same issue for `Windows Home 10 Windows Feature Experience Pack 120.2212.3920.0 , arch x64`
Worth to mention @codebytere v17.0.0 also produce strange behaviour than cancel BrowserWindowProxy (e.g. cancel printing dialog) with an error message:
`Segmentation fault "$NODE_EXE" "$NPX_CLI_JS" "$@"`
---
Thanks to @robertpatrick I've downgraded to v16.0.8 which sorted all above . v16.0.8 seems quite stable, but 17.0.0 definitely not . 🤔
