### ISSUE TITLE
It seems electron not support captureStream method

### ISSUE THREAD

**Issue by percy507** [electron/electron#12754] opened 2018-04-30 15:32 UTC
> Electron version: 1.8.4
> Operating system: Mac OS 10.13.1

I want capture the stream of &lt;video> element.

In normal browser, i can use `$('#video')[0].captureStream()` to get a MediaStream object.

But in electron, it seems not work. And the console reports [ xxx.captureStream is not a function ]

* Normal browser console

![image](https://user-images.githubusercontent.com/18365078/39660360-a633801a-506f-11e8-899c-4211d88bb368.png)

* Electron console

![image](https://user-images.githubusercontent.com/18365078/39660373-eae6e9e0-506f-11e8-8ecd-abc19c181450.png)

See [HTMLMediaElement.captureStream()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/captureStream)

**Comment by MarshallOfSound** [comment] 2018-04-30 15:35
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by percy507** [comment] 2018-05-05 06:27
@MarshallOfSound 

Hello. 

I upload some images. This should clearly describe the problem. 😁

**Comment by icecoll** [comment] 2018-05-24 05:50
To use this method in Google Chrome, you need to enable the “Experimental Web Platform features” flag.  [referance](https://zhirzh.github.io/2017/09/02/mediarecorder/). 
```
mainWindow = new BrowserWindow({  webPreferences: { experimentalFeatures: true  }   })
```

**Comment by sofianguy** [comment] 2019-01-07 20:44
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:44
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-01-15 20:44 UTC
Labels: blocked/need-info, bug :beetle:, platform/macOS, version/1.8.x
