### ISSUE TITLE
Can not view PDF

### ISSUE THREAD

**Issue by anuradhamudalige** [electron/electron#17110] opened 2019-02-25 07:40 UTC
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 

### Expected Behavior
PDF must be viewable

### Actual behavior
It says 'Couldn't load plugin'

### To Reproduce
I've set the plugins to true on BrowserWindows->webPreference but nothing works

**Comment by beig** [comment] 2019-02-25 07:46
Take a look at this issue: https://github.com/electron/electron/issues/12337

**Comment by MarshallOfSound** [comment] 2019-02-25 18:01
Duplicate of #12337

**Closed by MarshallOfSound** 2019-02-25 18:01 UTC

**Comment by anuradhamudalige** [comment] 2019-02-26 13:49
Is this fixed?

On Feb 25, 2019, at 11:32 PM, Samuel Attard <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #17110<https://github.com/electron/electron/issues/17110>.

**Comment by anuradhamudalige** [comment] 2019-03-18 18:31
Why is this issue closed? it's still there!

**Comment by ThomasMoutel** [comment] 2019-03-19 08:42
> Why is this issue closed? it's still there!

It has been marked as a duplication of #12337 , see above.

**Comment by Nashorn** [comment] 2019-05-30 11:28
Running Electron 6.0.0-beta.4
Still no pdf support 👎
