### ISSUE TITLE
[Feature Request]: Run headless electron without xvfb

### ISSUE THREAD

**Issue by mrmeku** [electron/electron#29164] opened 2021-05-14 02:59 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Electron's docs indicate that it is not possible to run an electron app without a display server running (see https://www.electronjs.org/docs/tutorial/testing-on-headless-ci ). 

However, chromium no longer needs a display server to run in headless mode.

I believe it should be possible for electron to be run in the same way as chromium and no longer require that the linux system have xvfb installed or have a display server.

### Proposed Solution

Ideally, this ends up being a documentation issue only and electron can already be run without a display server but the docs need to be updated to reflect that. 

Electron might need a different set of startup flags to run in a headless mode. Chromium needs to be run using its own `--headless` flag to enable this behavior. Maybe that flag could be used for electron as well.

### Alternatives Considered

Electron already interacts with the environment variable `ELECTRON_RUN_AS_NODE` to spawn electron as a node process. Maybe that is a better escape hatch for the display server requirement. 

### Additional Information

I'm filling this bug since I wish to be able run the cypress test runner without having to use `xvfb`. I've filed an associated issue on their repo with a bit more context for that use case https://github.com/cypress-io/cypress/issues/16505

**Comment by nornagon** [comment] 2021-07-08 18:15
Duplicate of #228

**Closed by nornagon** 2021-07-08 18:15 UTC
Labels: enhancement :sparkles:
