### ISSUE TITLE
Transparent windows have white background after loadURL or loadFile change

### ISSUE THREAD

**Issue by natew** [electron/electron#20357] opened 2019-09-27 19:31 UTC
### Issue Details

* **Electron Version:** 4.0 => 8.0 nightly
* **Operating System:** Mac OS Mojave

### Expected Behavior

Should keep transparency (not show white background)

### Actual Behavior

Shows a white background after navigation

### To Reproduce

```js
const BrowserWindow = require('electron').BrowserWindow

setTimeout(() => {
  y = new BrowserWindow({
    width: 500,
    height: 500,
    hasShadow: true,
    frame: false,
    vibrancy: 'light',
    transparent: true,
    background: '#00000000',
    titleBarStyle: 'hiddenInset',
  })

  y.loadURL('http://localhost:4000')

  setTimeout(() => {
    y.loadURL('http://localhost:4000?')
  }, 1000)
}, 100)
```

I'm serving a simple index.html on 4000:

```
<!DOCTYPE html>
<html lang="en">
  <head></head>
  <style>
    body {
      font-family: -apple-system, 'SF Pro Text', BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue',
        Helvetica, 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Droid Sans', sans-serif;
      margin: 0;
      padding: 0;
      color: #fff;
      background: #00000000;
      font-size: 14px;
      line-height: 1.3rem;
      -webkit-app-region: drag;
      user-select: none;
      height: 100%;
      width: 100%;
    }
    html,
    body {
      height: 100%;
      width: 100%;
    }
    body * {
      display: flex;
      box-sizing: border-box;
    }
  </style>
  <body>
    <div style="align-items: center; justify-content: center; height: 100%; width: 100%;">
      <div style="font-size: 16px; font-weight: 300;">
        Loading...
      </div>
    </div>
  </body>
</html>
```

I'm really happy to look into this and patch it, I have electron pulled locally and all set up for debugging. If anyone knows the "area" to look for I'll spend a day poking around. Maybe it's not clear where this goes wrong, if so I likely can't spend enough time to find it.

**Comment by pronebird** [comment] 2019-10-07 10:50
https://github.com/electron/electron/pull/19973 does not address this for some reason.

**Comment by yuanyuZQ** [comment] 2019-11-21 07:51
crying~,i met the same issue

**Comment by kaitlynbrown** [comment] 2019-11-21 15:39
Seeing the same behaviour

**Comment by mantou132** [comment] 2019-11-25 14:39
same issue

**Comment by yuanyuZQ** [comment] 2019-11-26 09:19
i had solved that problem,my windows system is win7,just open the windows server "Desktop Window Manager Session Manager",then the window will be transparent .
![image](https://user-images.githubusercontent.com/22787985/69615134-63342f00-106f-11ea-8e5f-1a7839cb4ffd.png)
but i meet the other issue, i can't througth in the desk.in my project,there is a flexible menu,when it shrink，the original area can't be click ,jusk like here is still a shadow.


And  another computer has another problem . The transparent window can't grasp mouse action when  the mouse over or down。i can get the dom，but can’t get the cursor，unless i set the background-color。i want to open a transparent canvas， paint it by mouse.

**Comment by sdetweil** [comment] 2019-12-03 14:45
same issue, was ok on 3.0.13, now on 6.0.12 shows white background.
```
				viewerinfo.window = new BrowserWindow({
					width: viewerinfo.config.width,   // 300
					height: viewerinfo.config.height, // 300
					x: new_x,
					y: new_y,
					alwaysOnTop: true,
					show:false,
					transparent: true,
					backgroundColor: "#000000",
					dx: 0,
					dy: 0,
					frame: false,
					skipTaskbar: true
				})
```

**Comment by Jip-Hop** [comment] 2020-01-04 00:16
I think I'm hitting this bug too. I'm trying to make a new transparent window, opened with window.open() from a BrowserWindow with nativeWindowOpen set to true. But the new window has a white background. See [my example gist](https://gist.github.com/Jip-Hop/07be8c1d881d7732f1bd08158d65e00c) to reproduce. Gist can be loaded in Electron Fiddle.

Platform: MacOS Mojave 10.14.6
Electron v7.1.7, v8.0.0-beta.5, v9.0.0-nightly.20200101

**Comment by marcopompili** [comment] 2020-05-06 15:17
If I set the `background-color: transparent` for `html, body` in `index.html` the window is transparent for me (on Windows):

```
html, body {
background-color: transparent;
}
```

**Comment by sdetweil** [comment] 2020-05-06 17:52
@marcopompili   yes, the color property is the color of text , so the background is the real color you would see.. and if transparent.. nothing..

**Comment by toonvanvr** [comment] 2020-05-17 01:23
I do not get a white background when the color is set to `#00ffffff` on MacOS Catalina.

- `#00000000` => non-transparent white
- `#00000001` => transparent
- `#00ffffff` => transparent

It may be a simple issue like wrongly skipping a falsy number.

**Comment by toonvanvr** [comment] 2020-05-17 19:10
I used to have the same issue over a year ago on Windows, but that's probably fixed by #19973 (already mentioned by pronebird).

Not an issue on Windows 10 Pro v1909 build 18363.836 for electron v8.3.0. It even supports `#00000000` unlike macOs.

**Comment by Thalinda** [comment] 2020-07-29 13:27
try making developer tools undocked or disabled if developer tool enable it's not going to be a transparent window it's going to be a white background what ever you do 
`win.webContents.openDevTools({mode:'undocked'})`

**Comment by johnperuzzi** [comment] 2020-10-11 18:13
Yeah I was able to fix this issue by setting {transparent: true} when making the window and then setting backgroundColor to an rgba value (if you set background color in your css for the body, html elements make sure they also have rgba values), with a transparent alpha. I think this is what toonvanvr was saying

**Comment by electron-triage** [comment] 2021-03-09 19:56
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Closed by electron-triage** 2021-03-09 19:56 UTC
Labels: bug :beetle:, platform/macOS

**Comment by lixiaohulee** [comment] 2021-07-28 11:07
I resolve this problem 

if you want to make a transparent window,  remember to invoke the window.setBackgroundColor after win.loadUrl or win.loadFile method 

`const win = new BrowserWindow({ transparent: true, frame: false }   win.loadUrl('xxx').  win.setBackgroundColor(' a transparent color like #00000000')` 

[https://github.com/electron/electron/pull/28022/commits/193d41b4b4f9937dbde9ba6f4412b7362cca8e4e](url)

**Comment by SolberLight** [comment] 2022-09-16 14:01
> const win = new BrowserWindow({ transparent: true, frame: false } win.loadUrl('xxx'). win.setBackgroundColor(' a transparent color like #00000000')

`frame: false` is really important if set to true it won't work !

**Comment by Stanlyhalo** [comment] 2023-11-13 04:02
I don't know if this is because of the acrylic backgroundMaterial. But even if I have the same options, my window is white until I minimize and then bring it back, then it's properly rendering. If I disable the frame, it has a greyish light brown (idk how to describe so I attached an image), and once I resize, it will then render acrylic properly.
![image](https://github.com/electron/electron/assets/36088749/998bbb96-6b9e-46d7-8acc-5fc1c933db07)

**Comment by nextep** [comment] 2023-11-25 00:33
I noticed that if you run devtools, transparency goes away and you get a solid color. If in regular mode, you get white. If set in dark mode, you get black. It would be nice to set a warning at startup along those lines :)
