### ISSUE TITLE
Unable to add empty string as value using session.cookies.set

### ISSUE THREAD

**Issue by walmat** [electron/electron#26240] opened 2020-10-29 01:11 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 10.1.3
  * 
* **Operating System:** macOS 10.15.6
  * 
* **Last Known Working Electron version:** Unsure, possibly never?
  * 

### Expected Behavior

`session.cookie.set({ name: "example", value: "" })` should set the cookie properly with an empty string as the value.

### Actual Behavior

`session.cookie.set({ name: "example", value: "" })` throws error: `[Error: Setting cookie failed]`

### To Reproduce

Using any session, try to set a cookie with an empty string as the value, should error out. I can make a MVP if need be, but the problem is pretty self explanatory.

### Additional Information

Not sure if there are other related issues with setting cookies, but seems that there could be perusing through the open issues regarding them. Apologies if this has already been reported and is being worked on!

**Comment by nornagon** [comment] 2020-10-29 23:33
Seems like you're missing the required `url` argument.

I'm closing this for now as I can't reproduce this when the `url` argument is supplied. We should have a better error message for this case, though (the current is "Error: Failed to get cookie domain")

**Closed by nornagon** 2020-10-29 23:33 UTC
