### ISSUE TITLE
webcontents.printToPDF creates multiple pages for specific page size

### ISSUE THREAD

**Issue by comatory** [electron/electron#16547] opened 2019-01-25 13:26 UTC
* Output of `node_modules/.bin/electron --version`:
v4.0.1
* Operating System (Platform and Version):
macOS 10.13.6 (17G4015)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
N / A

**Expected Behavior**
When using `webview.getWebContents().printToPDF()` and set `pageSize` object `width` and `height` properties to webview's size, I expect that the saved PDF file will have exact dimensions as the webview (so I don't end up with content on multiple pages).

**Actual behavior**
I load image as `src` parameter of `<webview>` component. I set `style` property on webview according to loaded image. When calling `webview.getWebContents().printToPDF()` I set `pageSize` object to the size of webview element so my image does not end up on multiple pages in PDF. However some images end up on two pages anyway like this one ![bad](https://user-images.githubusercontent.com/5990424/51748321-59871700-20ac-11e9-90b1-cb99d3c055ec.png)

If I crop the image's width to around 2000 pixels, it works as expected.

**To Reproduce**
https://github.com/comatory/electron-print-to-pdf

Read `readme.MD` for instructions.

**Screenshots**
This is the resulting PDF file that was generated with `bad.png` file (that is attached also): 
[bad.pdf](https://github.com/electron/electron/files/2796232/bad.pdf)

**Additional Information**

**Comment by comatory** [comment] 2019-09-03 08:46
How high / low is this on the priority list?

**Comment by comatory** [comment] 2019-10-09 07:24
@sofianguy Hey Sofia, do you have any information on this?

**Comment by codebytere** [comment] 2020-01-27 05:08
@comatory this is unfortunately a WONTFIX on our end, not because we don't wish to but because we simply pipe through to Chromium's own print logic and so are not capable of fixing issues of this nature without introducing potentially significant patches that would introduce untenable maintenance cost. I would recommend trying to reproduce this in Chrome itself, and if you are successful, opening a bug at crbug.com

**Closed by codebytere** 2020-01-27 05:08 UTC
Labels: 4-2-x, bug :beetle:, platform/macOS, status/wontfix 🚫

**Comment by comatory** [comment] 2020-01-28 07:07
@codebytere Thanks for the info, I might file issue in Chromium.
