### ISSUE TITLE
Can't disable menu item with submenu 

### ISSUE THREAD

**Issue by albinekb** [electron/electron#11813] opened 2018-02-02 11:49 UTC
* Electron version: ^1.7.11
* Operating system: 10.13.2 (17C88)

### Expected behavior

Using the following menu template:
```js
Menu.buildFromTemplate([
  {
    label: 'Windows',
    enabled: false,
    submenu: []
  }
])
```
I expect the option to be disabled:
![image](https://user-images.githubusercontent.com/5027156/35731897-b31fd6f2-0817-11e8-847f-e9d7135e6c4e.png)

### Actual behavior

Option is not disabled, it shows as an empty menu, `enabled` does not affect options with a submenu.
![image](https://user-images.githubusercontent.com/5027156/35731809-69a51a50-0817-11e8-952d-bd26aeeef320.png)

### How to reproduce

Create a menu with an empty submenu and set `enabled` to false.

**Comment by codebytere** [comment] 2018-02-04 03:30
This is related to a pre-existing bug where `enabled: false` doesn't work for top-level menu items; closing as duplicate of https://github.com/electron/electron/issues/8703

**Closed by codebytere** 2018-02-04 03:30 UTC

**Comment by albinekb** [comment] 2018-02-05 11:57
@codebytere, `enabled: false` seems to work for it once I stop sending the array, so as a workaround i send `null` instead of the array and it will be disabled. Maybe I'm mis-understanding the meaning of top level? top level for me is all the items in the root and it works with just a plain text (no submenu) one.

https://github.com/wulkano/kap/blob/a5fa34ed8509d994d840808a062b35b2a463ee96/app/src/renderer/js/size-selector.js#L160-L164

**Comment by codebytere** [comment] 2018-02-05 17:24
@albinekb interesting 🤔 this might help us with the other issue, thanks!
