### ISSUE TITLE
'will-navigate' preventDefault fail

### ISSUE THREAD

**Issue by adammeyer** [electron/electron#16520] opened 2019-01-23 20:44 UTC
* Output of `node_modules/.bin/electron --version`: 4.0.1
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
The documentation states that event.preventDefault should stop the navigation from occurring.  Using my example below, the url should print to console, then browser navigation should stop.

**Actual behavior**
preventDefault does not stop navigation.

**To Reproduce**
```javascript
popupWindow.webContents.on('will-navigate', (event, url) => {
          console.log(url);
          event.preventDefault();
});
```

**Comment by codebytere** [comment] 2019-01-23 20:49
Are you running this in the renderer process? `event.preventDefault()` needs to be called synchronously, and owing to ipc it wouldn't be if you're in the renderer process

**Comment by adammeyer** [comment] 2019-01-23 20:58
Yes, this is in the render process. `const popupWindow = new remote.BrowserWindow()`  Is there a to prevent navigation in a BrowserWindow setup in the render process?

**Comment by MarshallOfSound** [comment] 2019-01-23 22:15
@adammeyer No, due to the synchronous nature of that event calling `preventDefault()` has to be done in the main process.

Closing this out as expected behavior 👍

**Closed by MarshallOfSound** 2019-01-23 22:15 UTC
