### ISSUE TITLE
[Bug]: webContents.startDrag sometimes crashes main process

### ISSUE THREAD

**Issue by chase-itay** [electron/electron#32389] opened 2022-01-09 17:10 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

webContents.startDrag sometimes crashes the main electron process with memory violation, 

### Actual Behavior

do not crash

### Additional Information

DUMP File attached

[b107877d-83c8-46f7-949a-459a9ec6555b.zip](https://github.com/electron/electron/files/7835517/b107877d-83c8-46f7-949a-459a9ec6555b.zip)

**Comment by codebytere** [comment] 2022-01-10 10:44
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by codebytere** [comment] 2022-01-20 09:25
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Closed by codebytere** 2022-01-20 09:25 UTC
Labels: platform/macOS, bug :beetle:, blocked/need-repro, 16-x-y

**Comment by nornagon** [comment] 2022-01-20 19:04
Here's the symbolicated crash stack:

```
Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0x0
Process uptime: 63 seconds

Thread 0 (crashed)
 0  electron.exe!ui::OSExchangeDataProviderWin::HasCustomFormat(ui::ClipboardFormatType const &) [os_exchange_data_provider_win.cc : 670 + 0x0]
    rax = 0x00004e5aefa20728   rdx = 0x000000760c9fd190
    rcx = 0x0000000000000000   rbx = 0x0000025602ba0000
    rsi = 0x0000000000000400   rdi = 0x0000025601b92238
    rbp = 0x000000760c9fd610   rsp = 0x000000760c9fd170
     r8 = 0x0000000000000000    r9 = 0x0000000000000000
    r10 = 0x0000000000000001   r11 = 0xfffffffff7083095
    r12 = 0x0000025602021400   r13 = 0x0000025602ba0000
    r14 = 0x00000256020839b0   r15 = 0x0000000000000013
    rip = 0x00007ff6850674eb
    Found by: given as instruction pointer in context
 1  electron.exe!static void content::`anonymous namespace'::PrepareDropData(struct content::DropData *, const class ui::OSExchangeData & const) [web_contents_view_aura.cc : 311 + 0x8]
    rbx = 0x0000025602ba0000   rbp = 0x000000760c9fd610
    rsp = 0x000000760c9fd1d0   r12 = 0x0000025602021400
    r13 = 0x0000025602ba0000   r14 = 0x00000256020839b0
    r15 = 0x0000000000000013   rip = 0x00007ff6811bf850
    Found by: call frame info
 2  electron.exe!content::WebContentsViewAura::OnDragEntered(ui::DropTargetEvent const &) [web_contents_view_aura.cc : 1301 + 0x8]
    rbx = 0x0000025602ba0000   rbp = 0x000000760c9fd610
    rsp = 0x000000760c9fd4a0   r12 = 0x0000025602021400
    r13 = 0x0000025602ba0000   r14 = 0x00000256020839b0
    r15 = 0x0000000000000013   rip = 0x00007ff6811bf6da
    Found by: call frame info
 3  electron.exe!void views::DesktopDropTargetWin::Translate(struct IDataObject *, unsigned long, struct tagPOINT, unsigned long, class std::__1::unique_ptr<ui::OSExchangeData,std::__1::default_delete<ui::OSExchangeData> > *, class std::__1::unique_ptr<ui::DropTargetEvent,std::__1::default_delete<ui::DropTargetEvent> > *, class aura::client::DragDropDelegate * *) [desktop_drop_target_win.cc : 152 + 0x5]
    rbx = 0x0000025602ba0000   rbp = 0x000000760c9fd610
    rsp = 0x000000760c9fd530   r12 = 0x0000025602021400
    r13 = 0x0000025602ba0000   r14 = 0x00000256020839b0
    r15 = 0x0000000000000013   rip = 0x00007ff685b1a479
    Found by: call frame info
 4  electron.exe!views::DesktopDropTargetWin::OnDragOver(IDataObject *,unsigned long,tagPOINT,unsigned long) [desktop_drop_target_win.cc : 79 + 0x19]
    rbx = 0x0000025602ba0000   rbp = 0x000000760c9fd610
    rsp = 0x000000760c9fd5d0   r12 = 0x0000025602021400
    r13 = 0x0000025602ba0000   r14 = 0x00000256020839b0
    r15 = 0x0000000000000013   rip = 0x00007ff685b1a511
    Found by: call frame info
 5  electron.exe!ui::DropTargetWin::DragOver(unsigned long,_POINTL,unsigned long *) [drop_target_win.cc : 67 + 0xd]
    rbx = 0x0000025602ba0000   rbp = 0x000000760c9fd610
    rsp = 0x000000760c9fd6d0   r12 = 0x0000025602021400
    r13 = 0x0000025602ba0000   r14 = 0x00000256020839b0
    r15 = 0x0000000000000013   rip = 0x00007ff685b1a8fa
    Found by: call frame info
 6  ole32.dll + 0x333ce
    rbx = 0x0000025602ba0000   rbp = 0x000000760c9fd610
    rsp = 0x000000760c9fd740   r12 = 0x0000025602021400
    r13 = 0x0000025602ba0000   r14 = 0x00000256020839b0
    r15 = 0x0000000000000013   rip = 0x00007ffd7ba833ce
    Found by: call frame info
 7  ole32.dll + 0x11318
    rsp = 0x000000760c9fd760   rip = 0x00007ffd7ba61318
    Found by: stack scanning
 8  ole32.dll + 0x331ff
    rsp = 0x000000760c9fd790   rip = 0x00007ffd7ba831ff
    Found by: stack scanning
 9  ole32.dll + 0x33240
    rsp = 0x000000760c9fd7a0   rip = 0x00007ffd7ba83240
    Found by: stack scanning
10  USER32.dll!SetThreadDpiAwarenessContext + 0x4c
    rsp = 0x000000760c9fd800   rip = 0x00007ffd7b48c58c
    Found by: stack scanning
11  ole32.dll + 0x31740
    rsp = 0x000000760c9fd830   rip = 0x00007ffd7ba81740
    Found by: call frame info
12  ole32.dll + 0x3166d
    rsp = 0x000000760c9fd8a0   rip = 0x00007ffd7ba8166d
    Found by: stack scanning
13  ole32.dll + 0x32389
    rsp = 0x000000760c9fd8d0   rip = 0x00007ffd7ba82389
    Found by: stack scanning
14  ole32.dll + 0xe1708
    rsp = 0x000000760c9fd918   rip = 0x00007ffd7bb31708
    Found by: stack scanning
15  ole32.dll + 0xe1748
    rsp = 0x000000760c9fd9f8   rip = 0x00007ffd7bb31748
    Found by: stack scanning
16  electron.exe!_tailMerge_winusb.dll + 0x1577fef
    rsp = 0x000000760c9fda48   rip = 0x00007ff6882d76e0
    Found by: stack scanning
17  ole32.dll + 0xf2040
    rsp = 0x000000760c9fda60   rip = 0x00007ffd7bb42040
    Found by: stack scanning
18  SHELL32.dll + 0x16ad00
    rsp = 0x000000760c9fda70   rip = 0x00007ffd7a5cad00
    Found by: stack scanning
19  electron.exe!download::DownloadItemImpl::MarkAsComplete() [download_item_impl.cc : 1455 + 0x1]
    rsp = 0x000000760c9fdb50   rip = 0x00007ff6844f0000
    Found by: stack scanning
```

Which is a crash on [this line](https://source.chromium.org/chromium/chromium/src/+/refs/tags/96.0.4664.55:ui/base/dragdrop/os_exchange_data_provider_win.cc;l=670;drc=c8c123536f8e93a36ba0f032674accdd77a62215).

Not sure what's going on there, without a repro it's hard to say more.
