### ISSUE TITLE
BrowserWindow cannot be closed

### ISSUE THREAD

**Issue by ChangMM** [electron/electron#6994] opened 2016-08-26 07:36 UTC
* Electron version:1.3.4
* Operating system:Mac OS 10.11.6 
electron can not close browserWindow when the broswerWindow open the page which has a 
Rich Text Editor(i guess) (such as mp.weixin.qq.com)

**Comment by zcbenz** [comment] 2016-08-29 05:12
I'm unable to reproduce by opening `mp.weixin.qq.com`, can you provide a minimal app that can reproduce this problem?

**Comment by kevinsawicki** [comment] 2016-09-30 18:01
Closing this out until more information is provided.

**Closed by kevinsawicki** 2016-09-30 18:01 UTC
Labels: more-information-needed
