### ISSUE TITLE
stop removing tags from your repo

### ISSUE THREAD

**Issue by brjsp** [electron/electron#42025] opened 2024-05-03 07:45 UTC
Hello. I maintain the electron package in openSUSE.

Yesterday you have added a `v29.3.2` tag to the repository. It was live long enough for me to download the tarball and start preparing the release.

It is impossible now to verify which commit the source code corresponds to, because you have deleted the tag. I managed to catch this before publishing the new version but you are wasting time of me, the openSUSE release team, and possibly my counterparts in other distros. I'm going to tag them just to alert them to this bad practice of yours: @alerque @selfisekai @tagattie

**Comment by brjsp** [comment] 2024-05-03 07:52
The tagged commit seems to be 19f0abd62eb4cdf2863ee2936d4681ae0658226d

**Comment by alerque** [comment] 2024-05-03 08:10
Yes, very much the same complaint here. The practice of re-tagging on this repo has cost me quite a bit of time in the past and is a regular source of frustration. I've complained about it in the past too, but it keeps happening.

It would be much appreciated if a different workflow could be setup. If a release goes wrong and you want to get some extra commit it, just tag a new minor version. Or figure out a way to run your release checks privately without pushing the tag to the public repo until you know it is good to go.

@brjsp You can usually identify what commit a tarball is from (assuming it is a `git archive` generated one) with `zcat package.tar.gz | git get-tar-commit-id`.

**Comment by selfisekai** [comment] 2024-05-03 08:31
alpine linux package maintainer here, i think i haven't noticed it myself before on this repo, actually. though i think i'm also the only one here only tracking one branch at a time

**Comment by MarshallOfSound** [comment] 2024-05-03 08:49
Hey folks, appreciate there is a disconnect here. Unfortunately changing how we do tags / releases is not a thing that would be easy to do, even if we wanted to do it.

For clarity, if at any point the release process fails in an unrecoverable way we initiate a "clean up" that removes all our temporary artifacts and deletes the tag completely. This, along with the rest of our release process, is fully automated.

If you're looking for a clear indication of "when an electron release is actually released" you can operate off of either:
* npm version tags (once it's live on npm, it's actually live)
* github releases (not tags), the tag is made quite early during the release process, an associated release is only published as the final step
* Operate off of our canonical Source Of Truth for electron releases. https://releases.electronjs.org (or the JSON feed https://releases.electronjs.org/releases.json). Things only show up in that feed when they've been published.

> I managed to catch this before publishing the new version but you are wasting time of me, the openSUSE release team, and possibly my counterparts in other distros

Just want to note here, this isn't a thing we actively support / know y'all are doing. So to be fair, it's not like we're doing it deliberately

**Comment by alerque** [comment] 2024-05-03 09:09
Thanks for the response. Just a couple points:

1. I did switch from starting test releases when a tag landed to not launching anything until it lands as an announcement on releases.elctronjs.org. That is *not* as infallible as you suggest though, twice now releases have been posted there only to later disappear with no explanation.
1. The GH Releases system has some glitches too, it is not uncommon for a release to get missed entirely there, and other times they get labeled as pre-releases and the label never removed even long after the release is posted on the website and even the next release lands.
1. Deleting half-baked artifacts is one thing, but yanking the tag with no visible explanation and eventually re-posting the same number is definitely an anti-pattern.

**Comment by MarshallOfSound** [comment] 2024-05-03 09:14
> That is not as infallible as you suggest though, twice now releases have been posted there only to later disappear with no explanation.

I'd be interested in version numbers for these cases, we keep detailed release logs and it _shouldn't_ be possible for a release to show up on releases.electronjs.org and then later be removed 🤔 I can chase down why that is occurring.

> other times they get labeled as pre-releases

Not sure what this is referring to specifically, but we label and leave all "alpha" and "beta" releases as `pre-release`. There shouldn't be able stable `x.y.z` versions tagged as "pre-release" on github.

> Deleting half-baked artifacts is one thing, but yanking the tag with no visible explanation and eventually re-posting the same number is definitely an anti-pattern.

I don't necessarily disagree, just noting how things currently work and that changing them is unlikely to be a thing. What we can do is make sure there is _something_ that y'all can use as a source of truth, I believe it is releases.electronjs.org but if that is exhibiting similar conditions then that might be something we have to look into as noted above.

**Comment by brjsp** [comment] 2024-05-03 09:40
> @brjsp You can usually identify what commit a tarball is from (assuming it is a `git archive` generated one) with `zcat package.tar.gz | git get-tar-commit-id`.

@alerque We don't do “use git archive and add a separate tarball with vendored stuff” for Electron. It's impractical as the bulk of the code is patched Chromium, and the “main” repo lives in an `electron/` subdirectory. We just download everything using gclient and remove the irrelevant libraries and binary blobs afterwards (since we would have to do that anyway) — the git metadata do not survive that process.

<a href="https://build.opensuse.org/projects/devel:languages:nodejs/packages/nodejs-electron/files/create_tarball.sh?expand=1">See the script we're using.</a>

**Comment by alerque** [comment] 2024-05-03 09:40
`29.1.1` is one tag that hit the releases website and then later wasn't there for an extended time. I had a bit of an exchange with a RISC-V packager for an Arch Linux port about it and tried to defend it being there when he couldn't find it, and then eventually force refreshed my browser on the announcement page and got a 404. The tag had lived on Git for at least a couple days, then was gone for about a week at least (Mar 1st–6th) before coming back with lots of new content. At the time that happened I *remembered* it having happened before but I do not have a record of what tag it was.

Is there a public build log somewhere that we could check to see if a release was pulled and see what commit SHA was originally tagged? That would be quite useful for us distro packagers to review.

**Comment by alerque** [comment] 2024-05-03 09:47
@brjsp Understood, and yes that would loose the meta data (c.f. my request for a log of yanked tags and their commit hashes), and yes I understand why you've taken that route to handling the sources. We did something similar for a long time, and now take a bit different tactic: We [scripted something up](https://gitlab.archlinux.org/archlinux/packaging/packages/electron30/-/blob/main/makepkg-source-roller.py?ref_type=heads) that iterates through the sources manifest for a given release and finds all the pinned commits for vendered sources, then regenerates [this list of sources](https://gitlab.archlinux.org/archlinux/packaging/packages/electron30/-/blob/main/PKGBUILD?ref_type=heads#L77) that we can checkout using a sources cache that is available across builds and even Electron versions to save bandwidth and local storage while still tracking hashes for all our input sources.

**Comment by alerque** [comment] 2024-05-03 09:59
Understood, I wasn't suggesting you copy the approach. There are definitely pros and cons to each possible way, and we've tried quite a few for this project. This is the best suited to our build tooling so far. And no Arch does not keep archived copies of source inputs like OpenSUSE, Debian, and a few others do. We do have hashes not jsut for the sources but for every file in the sources too, and this is useful for comparing with the sources being used in other distros. See e.g. [electron30 on whatsrc.org](https://whatsrc.org/search?q=electron30).

Thanks for the pointer on your `keeplibs` list. I might review that as a way to trim our source setup.

**Comment by brjsp** [comment] 2024-05-03 10:11
> alpine linux package maintainer here, i think i haven't noticed it myself before on this repo, actually. though i think i'm also the only one here only tracking one branch at a time

@selfisekai At openSUSE we also track only one branch (we neither have resources for maintaining multiple versions nor has such a need come up yet). Though i rather tend to follow https://3rdpartysource.microsoft.com/ for the question of “what is the latest stable version” rather than github, since VSCode (the most complicated app we ship) likes to break in unexpected ways (I recall 15 and 23 being problematic in that — both are Electron branches that bumped the Node major)

**Comment by alerque** [comment] 2024-06-11 17:22
Evidently 29.4.3 was yanked.

**Comment by alerque** [comment] 2024-09-10 13:39
The problem is hardly stale given several tags have been yanked in the last few weeks, but clearly this seems to be a "won't fix" issue. The solution would be to trigger the release workflow directly without pushing the tag to the public repo, then posting the tag after the rest of the process succeeds. Given comments above and elsewhere it seems that pushing the tags publicly on the canonical repo and then yanking them if the release workflow doesn't finish is just going to be the norm. Feel free to close as "won't fix" to indicate the de facto status.

**Comment by alerque** [comment] 2024-10-17 08:00
**NEW ITERATION OF THIS ISSUE**

So based on feedback above it seemed clear the project isn't adjusting the release process, so I've been trying to build releases that track what gets announced on the [releases dashboard](https://releases.electronjs.org/) per [this comment](https://github.com/electron/electron/issues/42025#issuecomment-2092579593) where @MarshallOfSound asserts that is the canonical release status.

However lately it seems there is yet another workflow wrinkle where releases get cut and never get announced there. For example [v31.7.0](https://github.com/electron/electron/releases/tag/v31.7.0) was tagged and released on GitHub, but the release never showed up on the dashboard. Usually when that happens the release gets yanked, but this one never got yanked, and now it has at least 10k asset downloads and many upstream projects started building against it. I've updated Arch Linux based on that info, but...

...that was just a random judgement call outside of the workflow mentioned here as canonical. What is going on and how can this be cleaned up so it isn't such a subjective gamble every time?

**Comment by MarshallOfSound** [comment] 2024-10-17 08:05
It's also non-trivial to inject that release data into our JSON feed after something like this goes wrong (for good reason, it's not supposed to be easy to fake/mutate that data).

As I said though, we are working on it 👍

**Comment by MarshallOfSound** [comment] 2024-10-17 19:11
Hey @alerque we've identified the issue in our release infrastructure, no eta on when it will be fixed but we have paused release automation until we've got it sorted. We also plan on backfilling the information that is currently missing once we've identified all impacted releases, recently we've noted `33.0.1` and `31.7.0` but we will be checking back a couple of years worth of history to ensure this hasn't happened before and just no one has noticed.

**Comment by dsanders11** [comment] 2024-10-26 00:54
@alerque, we've fixed the issue and backfilled missing releases (there were 7 releases missing - 3 stable and 4 nightlies). We'll be setting up some automated audits to ensure we don't miss an issue like that again in the future.

**Comment by brjsp** [comment] 2024-12-05 15:39
Happened again, and it's getting worse.
7691f5886117841034525a6078e247fc436d0326 just got tagged as 31.7.6 whereas fb47716885d6c68f32296e99f573e4c979b89026 was tagged as this for over a week.

**Comment by alerque** [comment] 2024-12-05 15:45
Yes, I've noticed at least half a dozen in the last couple weeks. Most of them short lived (a couple hours), but some much longer. I still think the tags should not be pushed until the release workflows are verified, but it doesn't seem like they are interested in re-tooling upstream to make that happen.

**Comment by dsanders11** [comment] 2024-12-06 03:40
> Happened again, and it's getting worse.
> https://github.com/electron/electron/commit/7691f5886117841034525a6078e247fc436d0326 just got tagged as 31.7.6 whereas https://github.com/electron/electron/commit/fb47716885d6c68f32296e99f573e4c979b89026 was tagged as this for over a week.

@brjsp, it was already explained in https://github.com/electron/electron/issues/42025#issuecomment-2092579593 why tags are not the source of truth for Electron releases. Did you see that release in one of the definitive sources listed in that comment, such as https://releases.electronjs.org/ and https://releases.electronjs.org/releases.json, or GitHub releases? I can see that v31.7.6 failed on Nov 27th but it looks like the tag wasn't deleted until today when a new release was going out. It failed before creating the GitHub release or updating https://releases.electronjs.org/releases.json, so it shouldn't have appeared in either of those sources.

To be clear, we have already explained the automated release process and that tags can and will be deleted for failed releases. I'm going to close this as "Not Planned" since we don't plan to change the behavior, and have provided sources of truth for successful releases.

If you discover future issues where a successful release (published on npm) is missing in one of those sources of truth, or is listed there but not tagged, that would be a bug in our release automation, so feel free to open a new issue for that.

**Closed by dsanders11** 2024-12-06 03:40 UTC

**Comment by brjsp** [comment] 2024-12-06 06:07
> If you discover future issues where a successful release (published on npm) is missing in one of those sources of truth, or is listed there but not tagged, that would be a bug in our release automation, so feel free to open a new issue for that.

I'm not interested in npm releases! I'm building electron from source, and could not care less about your CI or “successful releases”. Since you do not provide source tarballs, i am forced to use git tags.

**Comment by dsanders11** [comment] 2024-12-06 06:19
@brjsp, you can use https://releases.electronjs.org/releases.json or GitHub releases as the source of truth for successful releases.

**Comment by benz0li** [comment] 2024-12-06 06:25
I am following this discussion for a while now.

@dsanders11 @MarshallOfSound Is there a specific reason to push the tag *so early* [in the release process][^1]? What is the argument against using the hash throughout the release process and push the tag *just before* the associated release is published?

[^1]: I am not familiar with GitHub releases. Maybe that is a requirement.

**Comment by alerque** [comment] 2024-12-06 07:28
@dsanders11 As for as I know in the last month or so since it was fixed the `releases.json` file and website haven't miss-reported releases. Their biggest fault is that they were regularly missing releases that *were* finalized, not the other way around. At least for the last couple cycles I haven't seen that happen.

On the other hand please don't suggest the GitHub Releases feed as a source of truth because that still does get reset sometimes. Not as often as the tags get yanked, but I have seen it.

----

@benz0li It would require some non trivial re-tooling, but it is certainly possible. Using hashes and then switching to tags would be pretty messy and leave them with artifacts without the right meta data baked in. The simplest way would be to use a non-canonical forked repository on the side to test run builds and maybe save artifacts, but it would be a little convoluted. Another approach would be to have the workflow itself read the *proposed* tag data from somewhere (e.g. a workflow trigger rather than an on push) and have it tag internal to the workflow and have the workflow push the tag when it succeeds. There are other ways too, but it's worth acknowledging that this is a huge beast and the workflow they have is deeply ingrained in the build so fixing this would not be trivial.

**Comment by kxxt** [comment] 2024-12-06 08:15
I don't think pushing the tag early is wrong, which many open source projects do in practice. But if the release pipeline fails for some unfortunate reason and a rerun cannot solve it,  then a new tag with the fix should be released instead of clobbering the old tag.

**Comment by alerque** [comment] 2024-12-06 08:45
@kxxt Yes that would absolutely be a better (and very easy to implement) flow than the status quo.

**Comment by brjsp** [comment] 2025-05-24 11:18
Happened again, 35.5.0 was yanked
