### ISSUE TITLE
process is not defined even with nodeIntegration: true

### ISSUE THREAD

**Issue by antcolag** [electron/electron#27973] opened 2021-03-02 21:26 UTC
* **Electron Version:**
  * ^12.0.0
* **Environment:**
  * Arch Linux, npm 6.14.11, node v15.10.0
* **Last Known Working Electron version:**
  * ^11.0.0

### Expected Behavior
```
<script>document.write(process.versions.node)</script>
```
should not throw an error

### Actual Behavior
Uncaught ReferenceError: process is not defined

### To Reproduce
index.js
```
const electron = require('electron')

function createWindow () {
  if (electron.BrowserWindow.getAllWindows().length) {
    return
  }
  const win = new electron.BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
    }
  })
  win.loadFile('index.html')
  win.openDevTools()
}

electron.app.whenReady().then(createWindow)
```
index.html
```
We are using node <script>document.write(process.versions.node)</script>,
Chrome <script>document.write(process.versions.chrome)</script>,
and Electron <script>document.write(process.versions.electron)</script>.
```
package.json
```
{
  "name": "fe",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "electron ./index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "electron": "^12.0.0"
  }
}
```

it works fine with electron ^11.0.0

**Comment by aodin** [comment] 2021-03-02 23:44
Duplicate of https://github.com/electron/electron/issues/27957

Defaults changed in v12.0.0 and the tutorial has not been updated. The `createWindow` function should be:

```js
function createWindow () {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false
    }
  })

  win.loadFile('index.html')
}
```

**Comment by MarshallOfSound** [comment] 2021-03-03 00:44
To be clear, if possible, please update your application to support `contextIsolation: true`.  Setting that option to `false` actively makes your app less secure, there is a reason we updated the default value.

Check out the [Context Isolation](https://www.electronjs.org/docs/tutorial/context-isolation) document for more information

**Closed by MarshallOfSound** 2021-03-03 00:44 UTC

**Comment by antcolag** [comment] 2021-03-03 00:51
I didn't notice [#27957](https://github.com/electron/electron/issues/27957).
Thanks!
