### ISSUE TITLE
GlobalShortcut - Mac OS X - CMD+Space still triggers "Spotlight Search"

### ISSUE THREAD

**Issue by sancarn** [electron/electron#9203] opened 2017-04-16 13:58 UTC
I setup a global keyboard shortcut as command+space:

```
	globalShortcut.register('CommandOrControl+Space', function(){
		mainWindow.show()
	})
```

This is actually what happens though:

https://www.youtube.com/watch?v=HTN9aIRaLWw

I would expect spotlight search to be disabled.

**Comment by MarshallOfSound** [comment] 2017-04-16 14:07
As far as I know this is expected behavior.  If a system level app (spotlight) wants to listen to a specific key combination there is little you can do to stop it.  To be honest I'm surprised your key listener works at all 😆 

Other spotlight replacements like Alfred have long FAQ pages specifically for this kind of issue, i don't believe there is a way to programmatically prevent or change spotlights reaction to the hotkey.  You have to get the user to change the hotkey spotlight uses.

https://www.alfredapp.com/help/troubleshooting/cmd-space

Will leave open for know but pretty sure there is nothing we can do about this

**Comment by sancarn** [comment] 2017-04-16 14:33
Hmm same resources I found also.

The only lead I had to solving the issue was this post:

http://stackoverflow.com/a/7227903/6302131

```
defaults write -g NSUserKeyEquivalents -dict-add Duplicate '~@d' Minimize '\0'
defaults write com.apple.finder NSUserKeyEquivalents '{"Show Package Contents"="@\r";}'
```

But I fear that it'd screw up spotlight in general xD

**Comment by kevinsawicki** [comment] 2017-04-27 21:15
>  i don't believe there is a way to programmatically prevent or change spotlights reaction to the hotkey. You have to get the user to change the hotkey spotlight uses.

Yeah, I think this is expected behavior and probably the only workaround is those items from the alfred faq on this topic. This issue is similar to #9206, I'm going to close it out since this is something under the control of the operating system and the `RegisterEventHotKey` API provided on macOS.

**Closed by kevinsawicki** 2017-04-27 21:15 UTC
