### ISSUE TITLE
5.0.8 electron Mac App Store Private API Rejection

### ISSUE THREAD

**Issue by panbin** [electron/electron#20040] opened 2019-08-30 10:57 UTC
ITMS-90338: Non-public API usage - The app contains or inherits from non-public classes in Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: CAContext, CALayerHost, NSAccessibilityRemoteUIElement, NSNextStepFrame, NSThemeFrame, NSURLFileTypeMappings . If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by codebytere** [comment] 2019-08-30 16:13
Closing as duplicate of https://github.com/electron/electron/issues/20027

**Closed by codebytere** 2019-08-30 16:13 UTC
