### ISSUE TITLE
Cannot load ZeroMQ (zmq) into Electron app

### ISSUE THREAD

**Issue by stanleyxu2005** [electron/electron#6805] opened 2016-08-11 04:09 UTC
* Electron version: 1.3.2 (x64)
* Operating system: Windows 7 (x64)

I can successfully load ZeroMQ (zmq) module in Node environment. I can see `C:\app\node_modules\zmq\build\Release\zmq.node` is the correct ZMQ binary. But when I load it into an Electron app, it will show such error message, although the ZMQ binary exists at the location.
```
C:\app\node_modules\bindings\bindings.js:91 Uncaught Error: Could not locate the bindings file. Tried:
 → C:\app\node_modules\zmq\build\zmq.node
 → C:\app\node_modules\zmq\build\Debug\zmq.node
 → C:\app\node_modules\zmq\build\Release\zmq.node
 → C:\app\node_modules\zmq\out\Debug\zmq.node
 → C:\app\node_modules\zmq\Debug\zmq.node
 → C:\app\node_modules\zmq\out\Release\zmq.node
 → C:\app\node_modules\zmq\Release\zmq.node
 → C:\app\node_modules\zmq\build\default\zmq.node
 → C:\app\node_modules\zmq\compiled\6.1.0\win32\x64\zmq.node
```

Someone raised a question on stackoverflow, please [click here](http://stackoverflow.com/questions/38439854/is-zeromq-for-node-js-compatible-with-electron) to check details.

**Comment by MarshallOfSound** [comment] 2016-08-11 04:22
Have you rebuilt it using the Electron headers

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by stanleyxu2005** [comment] 2016-08-11 05:58
I haven't tried rebuild, because some dependencies are very difficult to be downloaded. (I'm in China and these deps are hosted at s3.amazon, which is blocked in China.) But the SO question http://stackoverflow.com/questions/38439854/is-zeromq-for-node-js-compatible-with-electron indicates, someone has already rebuilt the electron couple of times. So I am doubt whether rebuild really helps.

**Comment by MarshallOfSound** [comment] 2016-08-11 06:44
@stanleyxu2005 Without setting up ZeroMQ on my own machine all I can say is I doubt a module that is compatible with Node.JS is **not** compatible with Electron.  Can you try rebuilding the zmq module and testing if it works.

I believe their is a Chinese mirror available on the README https://github.com/electron/electron#mirrors

**Comment by stanleyxu2005** [comment] 2016-08-11 07:28
_Placeholder: Thank you. I'll confirm after I can rebuild Electron successfully._

**Comment by rgbkrk** [comment] 2016-08-11 18:51
Hey @stanleyxu2005, we're using Electron and ZMQ in https://github.com/nteract/nteract

Your version of node (at the command line) needs to match the version of Electron that you're using. In our case, we're using node 6 and (:soon:) electron-prebuilt@1.1.3

The nteract devs created their own prebuilt zmq fork in https://github.com/nteract/zmq-prebuilt, though it only works on OS X for the moment.

**Comment by zcbenz** [comment] 2016-08-12 08:32
Thanks @rgbkrk for providing the information, I'm closing this issue since it is not a bug.

**Closed by zcbenz** 2016-08-12 08:33 UTC
Labels: more-information-needed

**Comment by rgbkrk** [comment] 2016-12-13 23:08
As an update for folks who end up here via Google - [zeromq.js (`zeromq` on npm) provides prebuilt binaries for Electron across all platforms](https://github.com/zeromq/zeromq.js#rebuilding-for-electron).
