### ISSUE TITLE
Why make it impossible to release Mac versions of our Electron apps?

### ISSUE THREAD

**Issue by johnjohn1231** [electron/electron#11652] opened 2018-01-16 16:41 UTC
I asked previously a couple of times about why I can only build a Windows and Linux package on my Windows machine, but not a Mac one. It seems to have something to do with "symlinks" inside the Mac Electron ZIP file not being unpacked/packed correctly and thus breaking everything if you use a Windows machine, which (once again) is a requirement as I:

1. Don't own a Mac.
2. Cannot afford a Mac.
3. Even if I did have a Mac, I obviously still wouldn't want to have to manually transfer over files and "fiddle about" on a separate machine just for the Mac version of my app. That's madness and goes entirely against the supposed "easy cross-platformness" that is half the point of Electron or any "webview".

I frankly cannot tell if the Electron developers just don't care anymore, or if it's once again a case of "doing anything to mess with Windows users". If it's the latter, I can tell you this: I hate Windows. There. Now you know. If there were a *real* alternative, I would switch in a heartbeat. (No, Linux is *not* an alternative as I have established in hundreds of tests of mine over the years, the last time recently.)

So please remove those "symlinks" from the Mac version unless they are somehow absolutely necessary.

And before you tell me to use one of those "auto builders" for Electron: I spent many, many hours reading through their documentation, trying to figure them out, but they are just (all three that I know of and which are commonly linked to) absolute nonsense. I don't know what else to say about that, but they are *not* easy or logical to use. I like to know every step taken, which is why I have my own script to "build" my Electron packages. Would be interesting to know how those tools do the unpacking/packing for Mac, though, assuming they even run on Windows at all.

I'd appreciate if this issue wasn't "closed" as this is very much a real issue. I cannot "ask somewhere else".

**Comment by lee-dohm** [comment] 2018-01-17 01:43
Closing as duplicate of https://github.com/electron/electron/issues/11634 and https://github.com/electron/electron/issues/11622.

**Closed by lee-dohm** 2018-01-17 01:43 UTC
