### ISSUE TITLE
Wrong timezone Brasil UTC -3

### ISSUE THREAD

**Issue by LeoFC97** [electron/electron#21176] opened 2019-11-18 17:40 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
      "electron": "^4.1.4",
* **Operating System:**
    Ubuntu 18.04 x64

### Expected Behavior
[ LOG ] , "hora"
[ LOG ] , 9
[ LOG ] , "campo hora do horaro"
[ LOG ] , 9

### Actual Behavior
![image](https://user-images.githubusercontent.com/33994116/69075453-31d4b700-0a10-11ea-87e6-c74a945a9df1.png)

### To Reproduce

`
const timeStamp={"seconds":1574079167,"nanoseconds":901462000}
const valueInDate = timeStamp.toDate()
const brTime= new Date(valueInDate) //2019-11-18T12:12:47.901Z
const hour = brTime.getHours() // 10 EXPECTED TO BE 9 PROBLEM HERE
`

### Additional Information
This year Brasil lost his summerTimezone, from octuber to feburary brasil was -2UTC(from te last 7 years) but this year its -3UTC. 

This problem occurs only when i running in Electron, if i open in the browser works fine

**Comment by nornagon** [comment] 2019-11-18 17:57
Duplicate of #20998

**Closed by nornagon** 2019-11-18 17:57 UTC
