### ISSUE TITLE
Electron broken, when with nodejs all fine

### ISSUE THREAD

**Issue by darrrk** [electron/electron#5835] opened 2016-06-02 12:38 UTC
* Electron version: 1.1.3
* Operating system: Kubuntu 16.04

Simply inject this code (install deps before) in devtools console and wait some time (no longer)

```javascript
asynk = require('async'); // 1.5.2
csvParse = require('csv-parse')
ms = require('mississippi')
request = require('request')
securityToken = "24e8a1c890fb0d16ecdce4926dc4b2d6"

asynk.forEachOf({
    "kiwitaxi_countries": "https://kiwitaxi.com/services/data/csv/countries",
    "kiwitaxi_regions": "https://kiwitaxi.com/services/data/csv/regions",
    "kiwitaxi_place_types": "https://kiwitaxi.com/services/data/csv/place_types",
    "kiwitaxi_places": "https://kiwitaxi.com/services/data/csv/places",
    "kiwitaxi_routes": "https://kiwitaxi.com/services/data/csv/routes",
    "kiwitaxi_transfer_types": "https://kiwitaxi.com/services/data/csv/transfer_types",
    "kiwitaxi_transfers": "https://kiwitaxi.com/services/data/csv/transfers"
  }, function(url, collection, cb) {
    ms.pipe(
      request(url + '?security_token=' + securityToken),
      csvParse({columns: true, delimiter: '\t', quote: ''}),
      cb
    );
});
```

**Comment by zcbenz** [comment] 2016-06-03 04:47
I installed those modules and ran the code, but nothing happened?

**Comment by darrrk** [comment] 2016-06-03 09:48
So... This only appears in big app, where I work.
When I run this snippet, some time later I get:
```
Devtools was disconnected from the page.
Once page is reloaded, DevTools will automatically reconnect.
```
I don't understand, what's happened. How I can debug this or catch it before this crash happened.

**Comment by darrrk** [comment] 2016-06-03 10:08
I find cause of this problem.
This happens, when I require `trace` module.
If comment requiring `trace` module, all fine.

**Comment by victorporof** [comment] 2016-06-03 19:22
I see the exact same message here https://github.com/electron/electron/issues/5855

**Comment by zcbenz** [comment] 2016-07-01 07:07
I'm closing this since we don't have a reproducible example.

**Closed by zcbenz** 2016-07-01 07:07 UTC
Labels: more-information-needed
