### ISSUE TITLE
Electron crashes when restarting application

### ISSUE THREAD

**Issue by M0rious** [electron/electron#17438] opened 2019-03-18 16:17 UTC
* **Electron Version:**
  * 4.0.7
* **Operating System:**
  * Windows 7

### Expected Behavior
Application should restart without problems

### Actual Behavior
Sometimes instead of restarting, "... has stopped working" dialog appears.

### To Reproduce
App runs around the clock and restarts every few hours with this code:
```typescript
import {app} from "electron";
import schedule, {Job} from "node-schedule";  
function startRestartProcess() {  
    for (const time of configuration.restartTimes) {  
        const rule = new schedule.RecurrenceRule();
        rule.hour = time.hour;
        rule.minute = time.minute;
        schedule.scheduleJob(rule, () => {
            app.on("will-quit", () => {
                app.relaunch()
            });
            app.quit();
        });
    }
}
```

### Additional Information
Crash-Reporter is active and reports the following every time:
```
[ 0  ] std::list<scoped_refptr<media::AudioBuffer>,std::allocato... (list:1006) 
[ 1  ] atom::AtomBrowserMainParts::RegisterDestructionCallback(b... (atom_browser_main_parts.cc:119) 
[ 2  ] mate::TrackableObjectBase::TrackableObjectBase()             (trackable_object.cc:34) 
[ 3  ] atom::api::Session::Session(v8::Isolate *,atom::AtomBrows... (atom_api_session.cc:376) 
[ 4  ] atom::api::Session::CreateFrom(v8::Isolate *,atom::AtomBr... (atom_api_session.cc:714) 
[ 5  ] atom::api::Session::FromPartition(v8::Isolate *,std::basi... (atom_api_session.cc:740) 
[ 6  ] `anonymous namespace'::FromPartition(std::basic_string<ch... (atom_api_session.cc:796) 
[ 7  ] base::internal::Invoker<base::internal::BindState<content... (bind_internal.h:662) 
[ 8  ] mate::internal::Invoker<mate::internal::IndicesHolder<0,1... (function_template.h:196) 
[ 9  ] mate::internal::Dispatcher<v8::Local<v8::Value> (const st... (function_template.h:239) 
[ 10 ] v8::internal::FunctionCallbackArguments::Call(v8::interna... (api-arguments-inl.h:95) 
[ 11 ] v8::internal::`anonymous namespace'::HandleApiCallHelper<... (builtins-api.cc:110) 
[ 12 ] v8::internal::Builtin_Impl_HandleApiCall(v8::internal::Bu... (builtins-api.cc:140) 
[ 13 ] v8::internal::Builtin_HandleApiCall(int,v8::internal::Obj... (builtins-api.cc:128) 
```

```
cpu.count	4
uname.sysname	"Windows NT"
uname.version	"6.1.7601 Service Pack 1"
hostname	"M067CQL55513014"
uname.machine	"x86"
error.message	"EXCEPTION_ACCESS_VIOLATION_WRITE"
```

**Comment by ckerr** [comment] 2019-03-21 00:36
Hi @M0rious, thanks for opening this issue and for providing details on how to reproduce and what kind of crash you're seeing. I appreciate the detail!

After talking about this issue with @MarshallOfSound, we suspect the issue is that `app.exit()` is being called _before_ `app.relaunch()` which is likely putting app into an unknown state.

The docs suggest this:

> Note that this method does not quit the app when executed, you have to call `app.quit` or `app.exit` after calling `app.relaunch` to make the app restart.

I'm going to close this issue as discussion for now since I think this is the root cause. However if this is not the case, please let us know.

**Comment by M0rious** [comment] 2019-03-21 07:21
Hi @ckerr,
thanks for the response and the suggestion!
Unfortunately the code I started with was
```typescript
import {app} from "electron";
import schedule, {Job} from "node-schedule";
function startRestartProcess() {
    for (const time of configuration.restartTimes) {
        const rule = new schedule.RecurrenceRule();
        rule.hour = time.hour;
        rule.minute = time.minute;
        jobs.push(schedule.scheduleJob(rule, () => {
            app.relaunch();
            app.exit(0);
        }));
    }
}
```
This gave the exact same error, the code I posted here was a try to fix the problem.

**Comment by M0rious** [comment] 2019-03-27 08:46
Hi @ckerr , @sofianguy , @MarshallOfSound ,
any more ideas what to try to get to a working solution?
Our application is still crashing... I changed the restart code to
```typescript
app.relaunch();
app.quit();
```
but get still get the same error.
This does not happen every time - just 1/3 restarts fail.
Is there anything I can provide to help find a solution?

Thanks!

**Comment by MarshallOfSound** [comment] 2019-03-27 18:37
@M0rious Can you provide a minimal repro (preferably a [Fiddle](https://electronjs.org/fiddle)) that demonstrates this crash

**Comment by oskarszura** [comment] 2019-03-29 08:00
Hi, just wanted to say I have exactly the same issue when using:
```
    app.relaunch();
    app.quit();
```
we're facing Windows 'Application stopped working' window (also in the similar ratio  = 1/3 restarts and with Electron 4).

It suggests more common problem. Any idea that can cause it?

**Comment by MarshallOfSound** [comment] 2019-03-29 18:30
@oskarszura 

> @M0rious Can you provide a minimal repro (preferably a Fiddle) that demonstrates this crash

**Comment by sofianguy** [comment] 2019-05-01 05:34
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by sofianguy** 2019-05-01 05:34 UTC
Labels: 4-1-x, blocked/needs-repro ❌, bug/crash :boom:, discussion :speech_balloon:, platform/windows

**Comment by joeyer** [comment] 2020-02-20 01:16
Is there any fix, I also appeared

**Comment by aprilandjan** [comment] 2020-03-23 12:15
We are using electron@4.0.2 in production and encounter this problems in windows os, too 😭

**Comment by 1nfility** [comment] 2020-05-03 22:49
Any update on this?

**Comment by jontonsoup** [comment] 2020-05-28 20:50
I have a crash dump for this: 

[1ce5cc72b1594b2097a3fe02165d9777-symbolicated.crash.zip](https://github.com/electron/electron/files/4698198/1ce5cc72b1594b2097a3fe02165d9777-symbolicated.crash.zip)
