### ISSUE TITLE
Accelerator for Backspace and Delete togehter

### ISSUE THREAD

**Issue by sandor** [electron/electron#10787] opened 2017-10-13 14:02 UTC
I am constructing this in my main menu structure:

```
            {
                label: 'Delete',
                accelerator: 'Backspace',
                click: function () {
                    var focusedWindow = BrowserWindow.getFocusedWindow();
                    focusedWindow.webContents.send('remove', 'removing');
                }
```

Now I would like to use The Backspace AND the Delete keys as an accelerator. Have tried several combination for the accelerator, like:

`accelerator: 'Alt+Backspace,Alt+Delete'`

or 

```
accelerator: 'Alt+Backspace'
accelerator: 'Alt+Delete'
```
But with both attempts, Electron just used the second one. Is there really now way how we can use two keys for the same Accelerator?

**Comment by codebytere** [comment] 2017-10-13 16:32
closing as duplicate of https://github.com/electron/electron/issues/10787

**Closed by codebytere** 2017-10-13 16:32 UTC
