### ISSUE TITLE
Broken event: page-title-updated

### ISSUE THREAD

**Issue by vishalwy** [electron/electron#9090] opened 2017-04-02 16:59 UTC
According to https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-page-title-updated doing preventDefault() on the event should prevent the title from updating. However due to https://github.com/electron/electron/pull/3645 the event delivery becomes async and calling preventDefault() does nothing.

* Electron version: v1.6.2
* Operating system: Mac OS X 10.12.3

**Comment by deepak1556** [comment] 2017-04-05 09:58
I am unable to reproduce the issue, can you provide a minimal example. Thanks!

**Comment by kevinsawicki** [comment] 2017-05-31 16:58
Closing this out until more information is available.

**Closed by kevinsawicki** 2017-05-31 16:58 UTC
Labels: waiting/needs-repro

**Comment by x4080** [comment] 2020-05-10 23:35
Yes, I confirmed that e.preventDefault() in page-title-updated cannot stop webpages title to change window title (in windows at least)

**Comment by jakerobb** [comment] 2020-06-19 15:13
I am also experiencing this issue.
