### ISSUE TITLE
Toggle device toolbar button don't work in undock mode

### ISSUE THREAD

**Issue by jianghongfei** [electron/electron#5756] opened 2016-05-29 13:49 UTC
* Electron version:1.2.0
* Operating system:Windows 10

Toggle device toolbar button don't work in undock mode.

![undock](https://cloud.githubusercontent.com/assets/304166/15633713/109597e6-25e7-11e6-8122-bd209972ca4a.gif)

**Comment by zcbenz** [comment] 2016-05-30 03:33
This is a duplicate of #738.

**Closed by zcbenz** 2016-05-30 03:33 UTC
