### ISSUE TITLE
Accelerator keys don't work

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#24938] opened 2020-08-11 15:54 UTC
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.0.4
* **Operating System:** Windows 10
* **Last Known Working Electron version:** not sure

### Expected Behavior
If I add an accelerator like "Ctrl+P", I expect that hitting control and P will activate the context menu item action.

### Actual Behavior
Nothing happens though I do see "Ctrl+P" added to the context menu item label.

### To Reproduce
1. Start the app below and open a window: `window.open("https://google.com", "a");`
2. Right click and notice the Print item and the "Ctrl+P" label
3. press ctrl+p - nothing happens

```
(async () => {
  const {app, BrowserWindow, Menu} = require("electron");

  await app.whenReady()

  const window = new BrowserWindow({
    webPreferences: {
      sandbox: true,
      nodeIntegration: false,
      nativeWindowOpen: true
    }
  });

  window.removeMenu();

  await window.loadURL("https://google.com");
  window.webContents.openDevTools();

  app.on("browser-window-created", (_e, window) => {
    window.removeMenu();

    window.webContents.on("context-menu", () => {
        const menuItems = [{
            label: "Print",
            accelerator: "Ctrl+P",
            click: () => {
                window.webContents.print({});
            }
      }];

      const contextMenu = Menu.buildFromTemplate(menuItems);
      contextMenu.popup({ window });
     });
  });
})();

```

**Comment by zcbenz** [comment] 2020-08-17 02:25
The accelerator keys only work when the menu is an application menu or window menu, they do not work in context menus. The key however still shows in the menu item if you set one, because it is useful in some cases (for example indicating global shortcuts in a tray menu).

I'm closing this issue since it is expected behavior, and we won't implement accelerator keys in context menus because it is against most operating systems' guidelines.

**Closed by zcbenz** 2020-08-17 02:25 UTC
