### ISSUE TITLE
Menu Accelerators don't follow macOS HIG

### ISSUE THREAD

**Issue by Kilian** [electron/electron#21790] opened 2020-01-15 14:42 UTC
### Issue Details

When using an accelerator like `Shift+CmdOrCtrl+3`, the shown accelerator should be `⇧⌘3`, However, it's shown as `⌘#`. 

The HIG show menus with the shift arrow: https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/

* **Electron Version:** 7.x
* **Operating System:** macOS 10.14.6

### Expected Behavior
The accelerator is shown as `⇧⌘3`.

### Actual Behavior
The accelerator is shown as `⌘#`.

Will create a small fiddle later.

**Comment by nornagon** [comment] 2020-01-16 01:17
This seems to be different for different keys, e.g. Cmd+Shift+= should be shown as <kbd>⌘+</kbd> not <kbd>⌘⇧=</kbd>

**Comment by clavin** [comment] 2021-02-24 21:48
I think <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>=</kbd> should be shown as `⇧⌘=` given this case in Apple's System Preferences:

<img width="780" alt="Screen Shot 2021-02-19 at 2 44 37 PM" src="https://user-images.githubusercontent.com/9995434/108564865-04388680-72c1-11eb-9837-781134f459a1.png">

<kbd>Shift</kbd> + <kbd>/</kbd> is just a question mark `?`, and the keyboard shortcut is meant to open the "Help" menu, so `⌘?` would make some sense; however it is shown in the menu as `⇧⌘/` because those three keys must be pressed. Also, <kbd>Shift</kbd> + <kbd>/</kbd> may not always correspond to `?` given different keyboard layouts (see #26907). @nornagon thoughts?

**Comment by nornagon** [comment] 2021-02-25 19:09
macOS itself is inconsistent here.

![a screenshot of the Help menu, where the accelerator is shown as command-questionmark](https://user-images.githubusercontent.com/172800/109204209-eacc8a00-7759-11eb-9b80-75d89a2b2c52.png)

**Comment by electron-triage** [comment] 2021-03-09 03:55
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by alexdima** [comment] 2021-03-10 08:53
@clavin Can we please reopen this? This is impacting vscode which is on a very recent Electron version, so the issue still reproduces in Electron 11.

https://github.com/electron/electron/issues/26907 was marked as a duplicate of this issue and now this issue got closed super aggressively and incorrectly by the robot.

cc @deepak1556 @bpasero

**Comment by Kilian** [comment] 2021-03-10 09:58
I've added the 11 label and reopened this _but_ as shown by @nornagon it's not really clear what the fix should be given there doesn't seem to be a consistent implementation in macOS itself.

**Comment by alexdima** [comment] 2021-03-10 10:07
> it's not really clear what the fix should be

To clarify, the bug I have filed via #26907 is not that under the US kb layout `Shift+/` is sometimes rendered as `shift+/` and sometimes as `?`.

The bug is that `Shift+/` is rendered as `?` on all keyboard layouts, even when `Shift+/` does not produce `?`.

Perhaps #26907 is not a duplicate of this issue.

e.g.
> ![image](https://user-images.githubusercontent.com/5047891/110612697-bb257500-8190-11eb-96ca-e78b4acdedff.png)

**Comment by nornagon** [comment] 2021-03-10 19:42
@alexdima how does the macOS preferences UI vs Help menu render this accelerator when the keyboard layout is different?

**Comment by alexdima** [comment] 2021-03-11 08:36
@nornagon The macOS always shows keybindings using the WYSIWIG principle.

#### The US keyboard layout

![image](https://user-images.githubusercontent.com/5047891/110757682-f5a01800-824b-11eb-950b-fae0ecfa3622.png)

If I look at my US keyboard layout and press the keys labeled `cmd+shift+/` the action executes, thus the displayed keybinding is correct:
<img width="796" alt="Screen Shot 2021-03-11 at 09 28 33" src="https://user-images.githubusercontent.com/5047891/110758022-53ccfb00-824c-11eb-94b8-bed5d70d4ceb.png">

#### The Spanish ISO keyboard layout

![image](https://user-images.githubusercontent.com/5047891/110758217-8bd43e00-824c-11eb-80a0-e0028194befa.png)

If I look at the Spanish ISO keyboard layout and press the keys labeled `cmd+shift+/` the action executes, thus the displayed keybinding is correct:
<img width="856" alt="Screen Shot 2021-03-11 at 09 32 54" src="https://user-images.githubusercontent.com/5047891/110758508-e1a8e600-824c-11eb-93a7-3d0880194349.png">

---

So it looks that Apple is changing the keys to be pressed across keyboard layouts, which makes sense, why not.

But if you please look at #26907, you will see that the bug is about when passing `Cmd+Shift+7` as a keybinding to Electron menu items, Electron incorrectly renders this as `Cmd+&` which makes 0 sense when having the Spanish ISO keyboard, where `&` is produced by `Shift+6`, not by `Shift+7`.

**Comment by nornagon** [comment] 2021-03-11 19:34
Hm, Apple's display of the help menu shortcut there is surprising to me in the Spanish ISO keyboard layout. It's inconsistent with the US keyboard version—in US, the <kbd>/</kbd> is _unshifted_, whereas in the Spanish layout, typing <kbd>/</kbd> requires holding <kbd>Shift</kbd>.

Also, with the Spanish keyboard layout selected, I still see this in the Help menu:

![image](https://user-images.githubusercontent.com/172800/110843909-b084e180-825d-11eb-9439-44c418e0683f.png)

**Comment by alexdima** [comment] 2021-03-11 20:18
I see the same. When I press `cmd+shift+'` on the Spanish ISO keyboard layout (i.e. `cmd` + `shift` + the key to the right of `0`, the Help menu item executes. So Apple delivers a WYSIWYG consistent experience.

<img width="928" alt="Screen Shot 2021-03-11 at 21 07 50" src="https://user-images.githubusercontent.com/5047891/110848180-17ca8200-82ae-11eb-99d5-3c39bdae9da7.png">

But for example in VS Code we are not able to deliver a WYSIWYG experience to our users e.g. for Toggle Line Comment: when we render with HTML, we can render the keybinding correctly as `Cmd+Shift+7`, and pressing `Cmd+Shift+7` will trigger the keybinding. But when we pass `Cmd+Shift+7` to Electron's menu item this gets rendered as `Cmd+&`, which will be interpreted by a Spanish ISO user as `Cmd+Shift+6`, thus confusing our users:

<img width="1547" alt="Screen Shot 2021-03-11 at 21 14 50" src="https://user-images.githubusercontent.com/5047891/110849024-0766d700-82af-11eb-8d66-a46a0c0ffc7d.png">

**Comment by nornagon** [comment] 2021-03-11 20:26
Oh my goodness, so actually there are _two accelerators_ here, and one of them overrides the other when they happen to be generated by the same keystrokes.

Try this:

1. Have System Preferences focused
2. Enable US keyboard layout
3. Press the keys <kbd>Cmd+Shift+/</kbd> (i.e. the key to the left of the right Shift)

You'll observe that the "macOS User Guide" window opens. This is because the "System Preferences Help" menu item has been activated.

4. Enable Spanish ISO keyboard layout
5. Press the keys <kbd>Cmd+Shift+7</kbd>

The help menu is focused, but the "System Preferences Help" window does not open.

6. Press the keys <kbd>Cmd+Shift+'</kbd> (i.e. the key two to the left of Backspace)

The "System Preferences Help" window opens.


So the accelerator <kbd>Cmd+Shift+/</kbd> behaves differently from the accelerator <kbd>Cmd+?</kbd> if the keyboard layout is such that `?` is not generated by `Shift+/`!

**Comment by clavin** [comment] 2021-03-11 23:13
I have been messing with `NSMenu`s at the Cocoa level recently. @nornagon you are indeed correct that the system-level "Show Help menu" shortcut (which defaults to <kbd>Cmd + Shift + /</kbd>) is a completely different shortcut from the one that shows in menus (determined by each individual app, but in System Preferences it happens to be <kbd>Cmd + ?</kbd>).

1. In normal circumstances, using the US keyboard layout and with the default "Show Help menu" shortcut, pressing the <kbd>Cmd + Shift + /</kbd> will activate the system-level action to activate [the application's help menu](https://developer.apple.com/documentation/appkit/nsapplication/1428644-helpmenu?language=objc).
2. There also happens to be a menu item in the Help menu whose shortcut has been set to <kbd>Cmd + ?</kbd> *by the app developer* which would normally be activated by pressing the <kbd>Cmd + Shift + /</kbd> keys. However, since the system handled the event first, the menu item with this <kbd>Cmd + ?</kbd> shortcut is never reached and its action is never triggered.

Now, I'd like to make it very explicit that <kbd>Cmd + Shift + /</kbd> and <kbd>Cmd + ?</kbd> are distinct shortcuts and *not the exactly the same*.

As demonstrated above, if you change your keyboard layout such that <kbd>/</kbd> and <kbd>?</kbd> are no longer on the same physical key, then you are now able to freely activate either <kbd>Cmd + Shift + /</kbd> or <kbd>Cmd + ?</kbd> as completely separate shortcuts.

This is consistent with the WYSIWYG principle suggested by @alexdima. I would like to make one important addition to that principle though:

If a character that requires the shift key to type (in the current keyboard layout) is shown in a shortcut, then that shortcut implicitly requires the shift key be pressed in order to activate that shortcut, even if the shift key isn't shown in the shortcut itself.

For example, in the French keyboard layout, the <kbd>:</kbd> is an unshifted key, whereas in the US layout it is a shifted key. That means the shortcut <kbd>Cmd + :</kbd> does not require shift when using a French keyboard layout, but does require shift when using a US keybaord layout, even though shift is not part of the shortcut itself.

This also applies to the option key.

In the French keyboard layout, typing the `@` character requires the option key to be pressed. Similarly, the <kbd>Cmd + @</kbd> shortcut implicitly requires the option key to be pressed on a French keyboard layout. On a US layout, this shortcut would implicitly require the shift key instead.

I have confirmed all of this by testing on a very primitive Cocoa application with NSMenus.

---

All of that to say: accelerators should be shown in menus the same as they are typed in accelerator strings. If an accelerator string is `"CmdOrCtrl+Shift+7"` then the menu item should show `⇧⌘7`, not `⌘&` (no matter the keyboard layout). This also applies to `⇧⌘/` versus `⌘?` because they are distinct and different shortcuts.

**Comment by zcbenz** [comment] 2021-05-17 00:02
Related: https://github.com/electron/electron/issues/1507.

**Closed** 2021-06-02 07:32 UTC
Labels: 11-x-y, 12-x-y, 13-x-y, bug :beetle:, platform/macOS
