### ISSUE TITLE
[win32/macOS] EXCEPTION_ACCESS_VIOLATION_READ on shutdown

### ISSUE THREAD

**Issue by xpirt** [electron/electron#26032] opened 2020-10-19 14:32 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.0
* **Operating System:**
  * Windows 10 (19041, 18363, 18362, 16299)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
The application should not crash.

### Actual Behavior
The application crashes.

### To Reproduce
This seems happening sporadically when application exits (all windows get closed, destroyed and app is quit).
It happens only on Windows, MacOS does not seem to affected.
My code snippet:
```
  app.removeAllListeners('window-all-closed')
  BrowserWindow.getAllWindows().forEach((browserWindow) => {
    browserWindow.close()
    browserWindow.destroy()
  })
  app.quit()
````

### Stack Trace
Pastebin: https://pastebin.com/raw/MYvbpWe2
Snippet:
```
Fatal Error: EXCEPTION_ACCESS_VIOLATION_READ

Thread 10196 Crashed:
0   MyApp.exe                     0x7ff75f43a632      [inlined] base::internal::UncheckedObserverAdapter::IsEqual (observer_list_internal.h:30)
1   MyApp.exe                     0x7ff75f43a632      [inlined] base::ObserverList<T>::RemoveObserver::<T>::operator() (observer_list.h:283)
2   MyApp.exe                     0x7ff75f43a632      [inlined] std::__1::find_if (algorithm:933)
3   MyApp.exe                     0x7ff75f43a632      base::ObserverList<T>::RemoveObserver (observer_list.h:281)
4   MyApp.exe                     0x7ff76101f28c      extensions::ProcessManager::Shutdown (process_manager.cc:289)
5   MyApp.exe                     0x7ff761e3a08d      [inlined] DependencyManager::ShutdownFactoriesInOrder (dependency_manager.cc:127)
6   MyApp.exe                     0x7ff761e3a08d      DependencyManager::DestroyContextServices (dependency_manager.cc:83)
7   MyApp.exe                     0x7ff75f2e8de6      electron::ElectronBrowserContext::~ElectronBrowserContext (electron_browser_context.cc:158)
8   MyApp.exe                     0x7ff75f2e9abf      electron::ElectronBrowserContext::~ElectronBrowserContext (electron_browser_context.cc:154)
9   MyApp.exe                     0x7ff75f287a9d      [inlined] base::RefCountedDeleteOnSequence<T>::Release (ref_counted_delete_on_sequence.h:52)
10  MyApp.exe                     0x7ff75f287a9d      [inlined] scoped_refptr<T>::Release (scoped_refptr.h:322)
11  MyApp.exe                     0x7ff75f287a9d      [inlined] scoped_refptr<T>::~scoped_refptr (scoped_refptr.h:224)
12  MyApp.exe                     0x7ff75f287a9d      electron::api::Session::~Session (electron_api_session.cc:313)
13  MyApp.exe                     0x7ff75f28cdaf      electron::api::Session::~Session (electron_api_session.cc:294)
14  MyApp.exe                     0x7ff75f2eb641      [inlined] base::OnceCallback<T>::Run (callback.h:98)
15  MyApp.exe                     0x7ff75f2eb641      electron::ElectronBrowserMainParts::PostMainMessageLoopRun (electron_browser_main_parts.cc:545)
16  MyApp.exe                     0x7ff760a01750      content::BrowserMainLoop::ShutdownThreadsAndCleanUp (browser_main_loop.cc:1095)
17  MyApp.exe                     0x7ff760a031a6      content::BrowserMainRunnerImpl::Shutdown (browser_main_runner_impl.cc:178)
18  MyApp.exe                     0x7ff7609fee69      content::BrowserMain (browser_main.cc:49)
19  MyApp.exe                     0x7ff76090405c      content::RunBrowserProcessMain (content_main_runner_impl.cc:530)
20  MyApp.exe                     0x7ff760904c00      content::ContentMainRunnerImpl::RunServiceManager (content_main_runner_impl.cc:980)
21  MyApp.exe                     0x7ff7609048c2      content::ContentMainRunnerImpl::Run (content_main_runner_impl.cc:879)
22  MyApp.exe                     0x7ff761870252      service_manager::Main (main.cc:454)
23  MyApp.exe                     0x7ff75fcd8265      content::ContentMain (content_main.cc:19)
24  MyApp.exe                     0x7ff75f23140a      wWinMain (electron_main.cc:210)
25  MyApp.exe                     0x7ff7646a6e91      [inlined] invoke_main (exe_common.inl:118)
26  MyApp.exe                     0x7ff7646a6e91      __scrt_common_main_seh (exe_common.inl:288)
27  KERNEL32.DLL                    0x7ffed8a97033      BaseThreadInitThunk
28  ntdll.dll                       0x7ffed97dcec0      RtlUserThreadStart
```

### Additional Information
This seems a crash on shutdown/destroy of windows (from `base::Process::Terminate (process_win.cc)`, not sure if it's chromium-related (https://chromium.googlesource.com/chromium/src/+/master/docs/shutdown.md)

**Comment by xpirt** [comment] 2020-10-19 16:55
**Update:**
It seems we have a similiar crash affecting also macOS (10.15, 10.14, 10.13) and most probably have the same root cause.

Pastebin: https://pastebin.com/raw/EqLZpypt
Snippet:
```
Fatal Error: EXC_BAD_ACCESS / KERN_INVALID_ADDRESS

Thread 20239 Crashed:
0   Electron Framework              0x10b8b78c0         extensions::ExtensionRegistry::RemoveObserver (observer_list_internal.h:30)
1   Electron Framework              0x10b8d90d0         extensions::ProcessManager::Shutdown (process_manager.cc:289)
2   Electron Framework              0x10cebd60b         DependencyManager::DestroyContextServices (dependency_manager.cc:127)
3   Electron Framework              0x1095bab39         electron::ElectronBrowserContext::~ElectronBrowserContext (electron_browser_context.cc:158)
4   Electron Framework              0x1095badbd         electron::ElectronBrowserContext::~ElectronBrowserContext (electron_browser_context.cc:154)
5   Electron Framework              0x109546d42         electron::api::Session::~Session (ref_counted_delete_on_sequence.h:70)
6   Electron Framework              0x10954709d         electron::api::Session::~Session (electron_api_session.cc:294)
7   Electron Framework              0x1095bd324         electron::ElectronBrowserMainParts::PostMainMessageLoopRun (callback.h:98)
8   Electron Framework              0x10b0f18e0         content::BrowserMainLoop::ShutdownThreadsAndCleanUp (browser_main_loop.cc:1095)
9   Electron Framework              0x10b0f3183         content::BrowserMainRunnerImpl::Shutdown (browser_main_runner_impl.cc:178)
10  Electron Framework              0x10b0eef03         content::BrowserMain (browser_main.cc:49)
11  Electron Framework              0x10af98265         content::ContentMainRunnerImpl::RunServiceManager (content_main_runner_impl.cc:530)
12  Electron Framework              0x10af97eba         content::ContentMainRunnerImpl::Run (content_main_runner_impl.cc:879)
13  Electron Framework              0x10d51bfe7         service_manager::Main (main.cc:454)
14  Electron Framework              0x10a218683         content::ContentMain (content_main.cc:19)
15  Electron Framework              0x1094e8593         ElectronMain (electron_library_main.mm:23)
16  MyApp                           0x106897110         <unknown>
```

**Comment by nornagon** [comment] 2020-10-19 17:13
Duplicate of #25983.

**Closed by nornagon** 2020-10-19 17:13 UTC
