### ISSUE TITLE
Provide a mechanism for macOS apps to restore themselves to their original Spaces

### ISSUE THREAD

**Issue by nchammas** [electron/electron#10124] opened 2017-07-26 19:46 UTC
This feature request is related to #5362 but is specific to macOS. It is motivated by https://github.com/Microsoft/vscode/issues/979.

### Expected behavior

When an Electron app is restarted on macOS, all the windows should restore to the Space (i.e. virtual desktop) they were originally in.

### Actual behavior

Currently, there doesn't appear to be a way to do this, and restarted Electron apps like Visual Studio Code restore all their windows to the default Space. The user then has to manually replace all the windows in their correct Space. This happens every time the app or OS is restarted.

### How to reproduce

Install Visual Studio Code and follow the steps here: https://github.com/Microsoft/vscode/issues/979#issuecomment-266401109

### Some notes on a potential solution

macOS seems to offer a concept known as a [_restoration class_](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW26) by which applications can preserve interface data like what Space they belong to. This may be what Electron needs to wrap in order to provide the functionality described here.

For additional information, see these threads:
* https://github.com/Microsoft/vscode/issues/979
* https://bugs.chromium.org/p/chromium/issues/detail?id=74812#c77

**Comment by ericdrobinson** [comment] 2017-07-26 20:30
As [pointed out](https://github.com/Microsoft/vscode/issues/979#issuecomment-266444069) in the [linked threads](https://bugs.chromium.org/p/chromium/issues/detail?id=74812#c56), Apple does not provide a mechanism for apps to restore to previous Spaces during **app restart**.

**_However_**, Apple _does_ provide this capability across **system restart**. Adding support for this would allow apps that were active when the computer began it's reboot process to restore to their previous configuration (including Space assignment) when the computer completes the process. All native Apple apps work this way. The fix is outlined in the [Chromium bug thread](https://bugs.chromium.org/p/chromium/issues/detail?id=74812#c56):

>[I]f they’re trying to do their own state restoration and not going through NSWindow, the space isn’t going to be restored.
>
>These apps need to use NSWindow’s encodeRestorableStateWithCoder: and restoreStateWithCoder:.

**Comment by ericdrobinson** [comment] 2017-07-28 14:17
I should add that this is only related to #5362 in that it refers to "workspaces/virtual desktops". However, it appears that Apple does not provide public APIs for programmatic [Space](https://support.apple.com/kb/PH25574) assignment.

This issue is specifically related to being a "good macOS citizen" and properly restoring windows to their previous Spaces _**after a system reboot**_.

**Comment by codebytere** [comment] 2018-01-30 17:32
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the foreseeable future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.

**Closed by codebytere** 2018-01-30 17:32 UTC
Labels: platform/macOS, triaged/enhancement

**Comment by ericdrobinson** [comment] 2018-01-30 17:42
> since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap.

🤔

@codebytere Am I missing something? If you _do_ use the issues tab as the team's backlog, then shouldn't this remain?

It is correctly labeled as a macOS enhancement. I understand not prioritizing it - perhaps add a Backlog label?

**Comment by GandalfSaxe** [comment] 2018-11-28 11:42
Please prioritize this 👍 It's madness to have to rearrange all the VSCode windows upon system restart.

**Comment by ericdrobinson** [comment] 2019-10-11 16:23
@codebytere The relevant [upstream(?) issue](https://bugs.chromium.org/p/chromium/issues/detail?id=74812) (in Chromium) was recently [closed as `fixed`](https://bugs.chromium.org/p/chromium/issues/detail?id=74812#c107). Is it possible that the Chromium support will affect Electron support for the feature?

**Comment by xgdgsc** [comment] 2020-06-18 14:31
https://bugs.chromium.org/p/chromium/issues/detail?id=1065557  From my experience, it still not working for multi-monitor.

**Comment by gandalfsaxe** [comment] 2020-06-18 14:34
@xgdgsc I'm not 100% sure but it seems to work for me on multiple monitors, at least some of the time. I did notice that it never works if the Mac was not properly shut down, but always if it was restarting / shut down properly.

**Comment by ericdrobinson** [comment] 2020-06-18 15:12
@xgdgsc The bug you linked is for Windows. This Issue is specifically for macOS.

@gandalfsaxe Are you seeing that on macOS with Chrome or Electron-based apps?

Regardless, you might do well to post about your experience on [this Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1012034) to help the cause.

**Comment by gandalfsaxe** [comment] 2020-06-20 18:38
@ericdrobinson I meant Chrome, not electron apps.

But though the fix for Chrome once worked for me (at least most of the time), it doesn't work anymore.

Thanks, left a comment in the issue thread.

**Comment by brandondrew** [comment] 2021-11-05 15:52
> Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the foreseeable future,

This is a request for a bug fix, not for an "enhancement".

**Comment by Xolbek-developer** [comment] 2021-11-05 16:39
Hello

Jum, 5-noy, 2021, 20:54 Brandon Zylstra ***@***.***>:

**Comment by bpasero** [comment] 2023-10-11 05:44
@codebytere can this be reopened to better support VS Code scenarios around restoring all state that the user has setup?

**Comment by ericdrobinson** [comment] 2023-10-11 22:14
@bpasero I created Issue #37494 to track this feature request. It's both still open and contains a lot more information/context (it links both this issue and microsoft/vscode#146915 in the summary, for instance). That might be the better issue to reference...
