### ISSUE TITLE
alwaysOnTop is not honored if it is set while a BrowserWindow is still hidden

### ISSUE THREAD

**Issue by codl** [electron/electron#6103] opened 2016-06-17 13:08 UTC
- Electron version: v1.2.3
- Operating system: Linux x64

``` javascript
let win = new BrowserWindow({
  show: false,
  alwaysOnTop: true
});

win.show();
```

``` javascript
let win = new BrowserWindow({
  show: false
});

win.setAlwaysOnTop(true);

win.show();
```

The two snippets above create a window that is not always on top! The following works fine:

``` javascript
let win = new BrowserWindow({
  show: false
});

win.show();

win.setAlwaysOnTop(true);
```

**Comment by zcbenz** [comment] 2016-06-19 10:06
I can reproduce this, not sure of the cause though, Chromium's implementation seems to do the right thing.

**Comment by codebytere** [comment] 2017-09-27 01:47
closing due to abandonment.

**Closed by codebytere** 2017-09-27 01:47 UTC
Labels: fixme/bug, platform/linux
