### ISSUE TITLE
`net` in electron7: impossible to read the body of an HTTP request that reponds with an error

### ISSUE THREAD

**Issue by arantes555** [electron/electron#21147] opened 2019-11-15 15:51 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * All
* **Last Known Working Electron version:**
  * 6.1.4

### Expected Behavior
When doing a request with `net` and the server responds with a status-code that signifies an error, the user can still read the response's body.

### Actual Behavior
It is impossible to read the reponse's body, as the response object emits a `net::ERR_HTTP_RESPONSE_CODE_FAILURE` error and stops.

### To Reproduce

```sh
$ git clone https://github.com/arantes555/electron-bug-net-body-when-error.git
$ npm install
$ npm start
```

### Additional Information
This is a critical problem with `net`. In addition to making it impossible to implement `fetch` interface correctly, it simply makes `net` unsuitable for anything serious, as reading the body of the response (no matter the status-code) is at the core of what an HTTP request is.

**Comment by arantes555** [comment] 2019-11-15 16:21
It is also the case with `304 Not Modified` response. It indeed should not have a body, but it should not throw.

**Comment by arantes555** [comment] 2019-11-15 16:45
Also, after further testing, it seems that sometimes this error causes electron to exit with `exit code 139 (interrupted by signal 11: SIGSEGV)`. I do not have a 100% reproductible test-case for this yet though.

**Comment by vladimiry** [comment] 2019-11-15 16:48
Probably related issue #20923 and a fix #21099.

**Comment by arantes555** [comment] 2019-11-15 16:52
@vladimiry excellent catch. As this other issue did not have the `component/net` label, I missed it.

I have a few other issues to open that also seem related, but I will refrain until a new version with the fix is released so I can test against it before creating test-cases & opening the issues.

**Comment by kwonoj** [comment] 2019-11-15 18:04
this is https://github.com/electron/electron/issues/21046 / https://github.com/electron/electron/pull/21055

**Comment by MarshallOfSound** [comment] 2019-11-15 23:28
Closing as duplicate of #21046

**Closed by MarshallOfSound** 2019-11-15 23:28 UTC

**Comment by arantes555** [comment] 2019-11-16 17:28
Indeed, as it was not marked with the `component/net` label I missed it
