### ISSUE TITLE
[Bug]: Windows 7-like window visible on startup 

### ISSUE THREAD

**Issue by Goubermouche** [electron/electron#31559] opened 2021-10-23 10:48 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 (OS Build 19042. 1288)

### What arch are you using?

x64

### Expected Behavior

The Electron app opens as expected

### Actual Behavior

After launching my app I can see this windows 7 - like window for a split second, from what I've found this is caused by hiding the title bar with `titleBarStyle: 'hidden'` or `frame: false`. Am I missing something obvious or is this a bug? 

![Screenshot 2021-10-23 124008](https://user-images.githubusercontent.com/71839692/138552845-630512f1-8a40-4c4b-bf53-328d6156f976.png)

### Additional Information

My window constructor looks like this: 
`       mainWindow = new BrowserWindow({
		width: 800,
		height: 600,
		autoHideMenuBar: true,
		titleBarStyle: 'hidden',
		icon: __dirname + 'icon.ico',
		webPreferences:{
			nodeIntegration: true,
			contextIsolation: false,
		}
	});`

**Comment by geroale** [comment] 2021-11-27 13:58
Same issue here

**Comment by snaildos** [comment] 2021-12-18 06:57
v16.0.5 just got released.
I am no longer experiencing this issue.
Anyone else?

**Comment by Fabio286** [comment] 2022-01-11 08:29
> v16.0.5 just got released. I am no longer experiencing this issue. Anyone else?

In my case same situation with 16.0.5, 16.0.6 and 17.0.0-beta.2. 
The only thing tried that solves this issue is downgrade to 13.6.6.

**Comment by snaildos** [comment] 2022-01-11 08:31
> > v16.0.5 just got released. I am no longer experiencing this issue. Anyone else?
> 
> In my case same situation with 16.0.5, 16.0.6 and 17.0.0-beta.2. The only thing tried that solves this issue is downgrade to 13.6.6.

Sadly yeah, I thought it worked, it didn't. This actually needs to get fixed, I can't even deploy my application.

**Comment by nornagon** [comment] 2022-01-12 19:14
Duplicate of #30024

**Closed by nornagon** 2022-01-12 19:14 UTC
Labels: platform/windows, bug :beetle:, 15-x-y
