### ISSUE TITLE
Cookie handling in net module

### ISSUE THREAD

**Issue by arantes555** [electron/electron#8891] opened 2017-03-10 12:20 UTC
* Electron version: 1.6.2
* Operating system: macOS 10.12

### Expected behavior

Requests sent with the net module should behave one of two ways regarding cookies.
- Either not care about cookies at all, and neither store them nor send them back automatically.
- Or, fully handle cookies, store them when getting a `set-cookie` header, and send them back when necessary, automatically (with the possibility of an option to disable this behaviour)

### Actual behavior

Requests sent with the net module store cookies in the Session used by the request when getting a `set-cookie` header, but do not send them back afterwards.

### How to reproduce

```bash
git clone https://github.com/arantes555/electron-net-cookies-testcase.git && cd electron-net-cookies-testcase
npm i
npm start
```
output: 
```
Server started
REQUEST-HEADERS { 'Accept-Encoding': 'gzip, deflate',
  'Accept-Language': 'fr',
  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Electron/1.6.2 Safari/537.36' }
Response SET-COOKIE: undefined
STORED COOKIES: []
REQUEST-HEADERS { 'Accept-Encoding': 'gzip, deflate',
  'Accept-Language': 'fr',
  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Electron/1.6.2 Safari/537.36' }
Response SET-COOKIE: a=1,b=1
STORED COOKIES: [{"name":"a","value":"1","domain":"localhost"},{"name":"b","value":"1","domain":"localhost"}]
REQUEST-HEADERS { 'Accept-Encoding': 'gzip, deflate',
  'Accept-Language': 'fr',
  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Electron/1.6.2 Safari/537.36' }
Response SET-COOKIE: a=1,b=1
```

Btw, if I'm reporting multiple issues with the net module these days, it's because I'm working on https://github.com/arantes555/electron-fetch , if you wanna take a look :)

**Comment by deepak1556** [comment] 2017-03-15 19:03
The behavior was initially to save and send cookies from the cookie store. This was changed due to https://github.com/electron/electron/issues/8223 . Thinking back on it, we should expose `LoadFlags` api and follow the second option described above.

```
fully handle cookies, store them when getting a set-cookie header, and send them back when necessary, automatically (with the possibility of an option to disable this behaviour)
```

**Comment by rajbala** [comment] 2017-04-22 03:11
I can't figure out how to send a cookie with net.request.  Since it doesn't send it automatically, I am trying to set a header like this:

`request.setHeader("Cookie", cookies);`

`cookies` is an object of type Cookies. 

When I try to send that HTTP request I get a runtime error saying "Error processing argument at index 1, conversion failure from [object Array]"

So what type should the cookies header be set to?

**Comment by arantes555** [comment] 2017-04-22 12:11
@rajbala Yes, you have to use `req.setHeader`, but the second argument should be a string, not an Object.
To handle cookies, you can use a library like tough-cookie. Using it, you can build a cookie string like this :
```javascript
cookieJar
        .getCookiesSync(url, { allPaths: true })
        .map(cookie => cookie.cookieString())
        .join('; ')
```
`cookieJar` being a ToughCookie cookie jar

**Comment by jayesbe** [comment] 2018-01-25 19:13
Tried to get around this using ToughCookie and isomorphic-fetch.

```
const Tough = require('tough-cookie');
const CookieStore = new Tough.MemoryCookieStore();
const Cookies = new Tough.CookieJar(CookieStore);
const fetch = require('fetch-cookie')(require('isomorphic-fetch'), Cookies);
```

```
  return fetch( endpoint , {
    ...options,
    method: 'POST',
    headers: headerData,
    body: bodyData,
    credentials: 'include',
  })
  .then( response => {
  })
```

And cookies are still not being passed in subsequent requests.  I use the above to handle cookies for Jest in a react-native project.

**Comment by arantes555** [comment] 2018-01-25 21:55
@jayesbe I'm preaching for my choir here, but take a look at https://www.npmjs.com/package/electron-fetch , and https://github.com/arantes555/electron-fetch/issues/3#issuecomment-358919804 . It's not as elegant as having it all automated, but it works

**Comment by codebytere** [comment] 2018-09-24 04:43
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by Anrock** [comment] 2018-09-24 10:29
@codebytere reproducible with provided project on 1.8.8, 2.0.10, 3.0.0.

**Comment by arantes555** [comment] 2018-09-24 12:42
I can confirm, the bug is still present on newer electron versions

**Comment by codebytere** [comment] 2018-09-24 15:04
Great! Thanks for the fast response.

**Comment by sofianguy** [comment] 2019-08-09 04:04
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by arantes555** [comment] 2019-08-09 08:44
@sofianguy I can confirm the issue still happens with all newer major electron versions.

I have tested:
- 2.0.18
- 3.1.13
- 4.2.9
- 5.0.9

And the issue still happens with all these versions.

**Comment by arantes555** [comment] 2019-11-04 16:47
I confirm the problem still happens on electron@6.1.3 and electron@7.0.1. The repo has been updated accordingly.

**Comment by zcbenz** [comment] 2019-12-17 07:11
I'm labeling this as a feature instead of bug since this would be a breaking change.

**Closed** 2020-03-20 22:56 UTC
Labels: component/net, enhancement :sparkles:
