### ISSUE TITLE
Deleting a single cookie deletes multiple cookies where the URLs are subset of given URL

### ISSUE THREAD

**Issue by harryi3t** [electron/electron#13557] opened 2018-07-04 07:46 UTC
* Electron Version: 1.8.4 (although the issue is in 4.1.1 too)
* Operating System (Platform and Version): MacOS 10.13.4 
* Last known working Electron version: None

**Expected Behavior**
Deleting a single cookie should delete only one cookie

**Actual behavior**
It's deleting all the cookies where the URL partially matches the URL of the cookie to be deleted

**To Reproduce**
```
let electronSession = require('electron').remote.session.fromPartition("test");
    let cookieStore = electronSession.cookies;

cookieStore.set({ url: 'http://foo.com', domain: '.foo.com', path: '/', name: 'name', value: 'root' }, console.log)
cookieStore.set({ url: 'http://foo.com/a', domain: '.foo.com', path: '/a', name: 'name', value: 'a' }, console.log)
cookieStore.set({ url: 'http://foo.com/a/b', domain: '.foo.com', path: '/a/b', name: 'name', value: 'b' }, console.log)

cookieStore.get({}, console.log) // [Object, Object, Object]

cookieStore.remove('http://foo.com/a/b', 'name', console.log) // will remove all 3 cookies

cookieStore.get({}, console.log) // []
```

**Comment by sofianguy** [comment] 2019-01-07 20:32
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment] 2019-01-15 20:47
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by harryi3t** [comment] 2019-03-27 12:03
@sofianguy I tested on the latest version of electron 4.1.1, the issue is still present.

**Comment by harryi3t** [comment] 2019-03-29 09:40
@sofianguy Tested on Windows and Linux as well on the version 4.1.2 and 5.0.0-beta.7 using electron-fiddle. I could reproduce the issue in them.
Seems like the issue is not tied to a particular platform or a version.

**Comment by codenirvana** [comment] 2019-07-18 19:56
This looks like expected behavior because all the three cookies are valid/accessible for the given URL.

```js
// returns all three cookies
cookieStore.get({url: 'http://foo.com/a/b', name: 'name'}, console.log)
```

So, deleting the same-named cookie for the given URL will delete all the accessible cookies with the matching name.

For now, to delete an individual cookie the only way is to invalidate the cookie by setting a past `expirationDate`.

```js
// query using path & name, because there can't be multiple cookies with same name & path
cookieStore.get({url: 'http://foo.com/a/b', path: '/a/b', name: 'name'}, (err, cookies) => {
  cookies[0].url = 'http://foo.com/a/b'; // url is mandatory for .set()
  cookies[0].expirationDate = 0; // past date
  cookieStore.set(cookies[0], console.log)
});
```

**Comment by harryi3t** [comment] 2019-07-19 04:55
@sofianguy Can you confirm if this is working as designed? In that case, we can close this issue and maybe mention this somewhere in the docs.

**Comment by electron-triage** [comment] 2020-02-19 22:02
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment] 2020-02-26 20:40
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by electron-triage** 2020-02-26 20:40 UTC
Labels: 4-2-x, blocked/need-info ❌, bug :beetle:, platform/macOS, version/1.8.x
