### ISSUE TITLE
Electron 7.1.2 - Can't remove the main BrowserWindow menu

### ISSUE THREAD

**Issue by JMorillasGreen** [electron/electron#21268] opened 2019-11-23 01:50 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.2
* **Operating System:**
  * Windows 10 1909
* **Last Known Working Electron version:**
  * 7.x.x (in another Windows 10 1909 computer)
### Expected Behavior
The menu that appears below the app title (the one with File, Edit, View...) must dissappear.

### Actual Behavior
Nothing. It does nothing. The menu is still there. as if nothing happened.

### To reproduce

This is basically the code I am testing:

const { app, BrowserWindow } = require('electron');

function createWindow() {
  let win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
        nodeIntegration: true,
    }
})
win.setMenuBarVisibility(false);
win.loadFile('./public/index.html')
}

app.on('ready', createWindow)

Everything works as expected, except the menu, which it still shows.

### Screenshots
[https://i.imgur.com/kJJf0JE.png](url)

**Comment by frankhale** [comment] 2019-11-23 22:49
`win.removeMenu()` and `win.setMenu(null)` are not getting rid of the menu in 7.1.2. I can confirm this on the Windows build.

**Comment by JMorillasGreen** [comment] 2019-11-27 17:54
I have tried with the latest beta, and still doesn't work. I think I will try with 6.1.5.

**Comment by JMorillasGreen** [comment] 2019-11-27 18:36
Okay, I will edit the main post, but this is what I found so far:
ElectronJS 6.1.5 - It's working.
ElectronJS 7.1.2 - It's not working.
ElectronJS 8.0.0-beta3 - It's not working.

Any ideas?

**Comment by JMorillasGreen** [comment] 2019-11-27 19:39
Okay. I managed to solve it, but I am not sure if this is how is supposed to work in 7.x.x, 8.x.x and 9.x.x.

Instead of using win.setMenuBarVisibility(true), I used autoHideMenuBar: true, in the window properties, like this:
let win = new BrowserWindow({
    width: 800,
    height: 600,
    autoHideMenuBar: true, // ---- THIS
    webPreferences: {
        nodeIntegration: true,
    }

**Comment by frankhale** [comment] 2019-11-29 01:57
> autoHideMenuBar Boolean (optional) - Auto hide the menu bar unless the Alt key is pressed. Default is false.

Setting `autoHideMenuBar` seems like a work around because removing the menubar can be done with the `removeMenu` function in older Electrons. In even older Electron you had to set the menubar to null to remove it. In my particular case I want to remove the menubar completely and this solution would not be enough for that.

**Comment by jacobq** [comment] 2019-12-03 20:38
Isn't this a duplicate of https://github.com/electron/electron/issues/21268?

**Comment by frankhale** [comment] 2019-12-04 01:27
oops, @jacobq you linked to *this* issue instead of the duplicate issue

**Comment by codebytere** [comment] 2019-12-05 18:34
Duplicate of https://github.com/electron/electron/issues/21088

**Closed by codebytere** 2019-12-05 18:35 UTC
Labels: 7-1-x, bug/regression :leftwards_arrow_with_hook:, platform/windows
