### ISSUE TITLE
"Renderer process crashed" on Apple m1 based laptops

### ISSUE THREAD

**Issue by Nimce** [electron/electron#27352] opened 2021-01-18 14:55 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v11.2.0
* **Operating System:** macOS Big Sur 11.1
* **Last Known Working Electron version:**

### Expected Behavior

Electron renderer process not to crash.

### Actual Behavior

Electron renderer process crashes.

### To Reproduce

**Make sure to use the ARM version of node!**
Download GAM file: http://mirror.ifarchive.org/if-archive/games/tads/worlds.zip

```
git clone https://github.com/Durafen/lectrote.git

cd lectrote

git submodule init

git submodule update

npm install

.\node_modules\.bin\electron .
```

And then extract the worlds.gam file to the same directory as lectrote and then load it from the interface.

### Screenshots
![image](https://user-images.githubusercontent.com/7021881/104929729-ee2b6380-59ac-11eb-8abb-7298f4628e0f.png)

### Additional Information
This is the output from the run:
```<--- Last few GCs --->

[43191:0x7100000000]       44 ms: Scavenge 3.0 (4.3) -> 2.9 (4.8) MB, 0.5 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
[43191:0x7100000000]       52 ms: Scavenge 4.1 (5.5) -> 3.7 (8.0) MB, 0.4 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
[43191:0x7100000000]       96 ms: Scavenge 4.9 (8.5) -> 4.5 (9.3) MB, 0.4 / 0.0 ms  (average mu = 1.000, current mu = 1.000) external memory pressure 


<--- JS stacktrace --->

[43185:0118/164751.510962:ERROR:shared_image_manager.cc(143)] SharedImageManager::ProduceGLTexture: Trying to produce a representation from a non-existent mailbox. 93:F0:C7:06:C4:41:42:D4:65:FB:D7:38:76:16:D2:F5
[43185:0118/164751.511256:ERROR:gles2_cmd_decoder.cc(19029)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[43185:0118/164751.511282:ERROR:gles2_cmd_decoder.cc(19050)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[43185:0118/164751.511299:ERROR:gles2_cmd_decoder.cc(13915)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[43185:0118/164751.511313:ERROR:shared_image_manager.cc(143)] SharedImageManager::ProduceGLTexture: Trying to produce a representation from a non-existent mailbox. C2:8E:5D:7C:46:DE:36:D8:DC:4A:AD:2F:D1:39:CC:EB
[43185:0118/164751.511330:ERROR:gles2_cmd_decoder.cc(19029)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[43185:0118/164751.511345:ERROR:gles2_cmd_decoder.cc(19050)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[43185:0118/164751.511358:ERROR:gles2_cmd_decoder.cc(13915)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[43185:0118/164751.511372:ERROR:shared_image_manager.cc(143)] SharedImageManager::ProduceGLTexture: Trying to produce a representation from a non-existent mailbox. A2:84:80:A8:A1:72:CE:4B:6D:0E:A6:B5:7A:F1:64:29
[43185:0118/164751.511386:ERROR:gles2_cmd_decoder.cc(19029)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[43185:0118/164751.511398:ERROR:gles2_cmd_decoder.cc(19050)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[43185:0118/164751.511414:ERROR:gles2_cmd_decoder.cc(13915)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[43185:0118/164751.511425:ERROR:shared_image_manager.cc(143)] SharedImageManager::ProduceGLTexture: Trying to produce a representation from a non-existent mailbox. CB:2A:78:10:69:E1:B9:C3:33:32:F8:EA:E8:4C:60:2F
[43185:0118/164751.511441:ERROR:gles2_cmd_decoder.cc(19029)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[43185:0118/164751.511454:ERROR:gles2_cmd_decoder.cc(19050)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[43185:0118/164751.511472:ERROR:gles2_cmd_decoder.cc(13915)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
[43185:0118/164751.519830:ERROR:gles2_cmd_decoder.cc(19079)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image
[43185:0118/164751.519861:ERROR:gles2_cmd_decoder.cc(19079)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image
[43185:0118/164751.519875:ERROR:gles2_cmd_decoder.cc(19079)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image
[43185:0118/164751.519887:ERROR:gles2_cmd_decoder.cc(19079)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared  @image```

**Comment by glued** [comment] 2021-02-10 18:38
I have seen rendering issues in VSCode's insider edition using the M1 Mac and I wonder if this is related... also:
https://bugs.chromium.org/p/chromium/issues/detail?id=1162947

**Comment by yi-ge** [comment] 2021-03-17 05:45
electron-nightly

**Comment by nornagon** [comment] 2021-03-17 22:37
Duplicate of #27497

**Closed by nornagon** 2021-03-17 22:37 UTC
Labels: 11-x-y, crash :boom:, platform/macOS, 🍎  Si
